### ISSUE TITLE
FontAwesome PRO icons are either Super Small or Lose Color

### ISSUE THREAD

**Issue by mirokosut** [elementor/elementor#10520]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release '31', Revision 'd14ef86' v5.7.28-31
	PHP Version: 7.3.14-6+ubuntu18.04.1+deb.sury.org+1
	PHP Max Input Vars: 10000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.3.2
	Site URL: https://happyelementor.wpengine.com
	Home URL: https://happyelementor.wpengine.com
	WP Multisite: No
	Max Upload Size: 50 MB
	Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.2.2
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.5 Safari/605.1.15

== Active Plugins ==
	Advanced Custom Fields
		Version: 5.8.7
		Author: Elliot Condon

	Elementor
		Version: 2.8.5
		Author: Elementor.com

	Elementor Pro
		Version: 2.8.3
		Author: Elementor.com

	Imagify
		Version: 1.9.8.1
		Author: WP Media

	Smash Balloon Instagram Feed
		Version: 2.2
		Author: Smash Balloon

	WP Rocket
		Version: 3.4.4
		Author: WP Media

== Must-Use Plugins ==
	Force Strong Passwords - WPE Edition
		Version: 1.6.4
		Author: Jason Cosper

	WP Engine Seamless Login Plugin
		Version: 1.5.1
		Author: WP Engine

	WP Engine Security Auditor
		Version: 1.0.8
		Author: wpengine

	WP Engine System
		Version: 3.2.2
		Author: WP Engine

== Elements Usage ==
	
	archive : 3
		archive-posts : 2
		button : 1
		global : 5
		heading : 2
		image : 4
		posts : 1
		text-editor : 3
		theme-archive-title : 2
	footer : 1
		global : 1
		heading : 2
		social-icons : 1
		text-editor : 3
		theme-site-logo : 1
		theme-site-title : 1
	header : 1
		button : 1
		nav-menu : 1
		theme-site-logo : 1
		theme-site-title : 1
	page : 2
		heading : 1
		image : 1
		text-editor : 1
	popup : 1
		global : 1
		heading : 1
		image : 1
		text-editor : 2
	single : 5
		global : 7
		heading : 1
		image : 2
		text-editor : 4
		theme-post-content : 4
		theme-post-featured-image : 3
		theme-post-title : 4
	widget : 0
		divider : 136
	wp-post : 0
		text-editor : 1
	wp-page : 4
		blockquote : 1
		button : 3
		global : 12
		heading : 16
		icon-list : 2
		image : 8
		image-box : 8
		share-buttons : 1
		shortcode : 1
		social-icons : 1
		spacer : 1
		testimonial : 3
		text-editor : 12

== Log ==
	
Log: showing 2 of 22020-02-05 14:28:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.8.5',
  'to' => '2.9.0-beta3',
)]
2020-02-06 22:16:19 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.0-beta3',
  'to' => '2.9.0-beta4',
)]

PHP: showing 5 of 5PHP: 2020-02-05 14:40:51 [notice X 2][/nas/content/live/happyelementor/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-02-05 17:45:02 [error X 9][/nas/content/live/happyelementor/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::259] Uncaught Error: Call to a member function update_meta() on null in /nas/content/live/happyelementor/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:259
Stack trace:
#0 /nas/content/live/happyelementor/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(180): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(54, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /nas/content/live/happyelementor/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /nas/content/live/happyelementor/wp-includes/class-wp-hook.php(288): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /nas/content/live/happyelementor/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters('', [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-02-07 18:43:24 [notice X 6][/nas/content/live/happyelementor/wp-content/plugins/elementor/core/logger/items/js.php::17] Undefined index: url [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-02-10 17:57:34 [notice X 2][/nas/content/live/happyelementor/wp-content/plugins/elementor-pro/modules/query-control/module.php::359] Undefined index: q [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-02-12 17:29:00 [notice X 6][/nas/content/live/happyelementor/wp-content/plugins/elementor-pro/modules/global-widget/widgets/global-widget.php::30] Undefined index: templateID [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 19 of 19JS: 2020-02-05 17:11:19 [error X 22967][https://happyelementor.wpengine.com/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:19667] null is not an object (evaluating \'this.getColorRepresentation().toLowerCase\') 
JS: 2020-02-05 20:35:25 [error X 12][https://happyelementor.wpengine.com/wp-includes/js/jquery/jquery.js?ver=1.12.4-wp:4:30644] undefined is not an object (evaluating \'c.pageYOffset\') 
JS: 2020-02-05 20:35:25 [error X 1][https://happyelementor.wpengine.com/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=2.9.0-beta3:2:58829] undefined is not an object (evaluating \'r.attributes\') 
JS: 2020-02-05 20:59:09 [error X 1][https://happyelementor.wpengine.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.9.0-beta3:2:92159] undefined is not an object (evaluating \'this.container.isEditable\') 
JS: 2020-02-05 21:19:03 [error X 1][https://happyelementor.wpengine.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.9.0-beta3:2:99668] undefined is not an object (evaluating \'elementor.channels.data.request(\"dragging:view\").getContainer\') 
JS: 2020-02-07 18:50:43 [error X 7][https://happyelementor.wpengine.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.9.0-beta4:7:83419] undefined is not an object (evaluating \'elementor.navigator.getLayout().elements\') 
JS: 2020-02-09 15:56:04 [error X 104][https://happyelementor.wpengine.com/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=2.8.5:2:48080] n.attributes[e.name].each is not a function. (In \'n.attributes[e.name].each(function(t){i.push(n.getStyleControls(e.fields,t.attributes))})\', \'n.attributes[e.name].each\' is undefined) 
JS: 2020-02-11 16:10:57 [error X 1][https://happyelementor.wpengine.com/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=2.8.5:2:40610] undefined is not an object (evaluating \'this.getEditorControlModel(t).cid\') 
JS: 2020-02-11 16:59:21 [error X 3][undefined:2:43] null is not an object (evaluating \'document.getElementById(\'elementor-field\').focus\') 
JS: 2020-02-11 16:59:46 [error X 1][undefined:2:42] null is not an object (evaluating \'document.getElementById(\'elementor-fiel\').focus\') 
JS: 2020-02-11 17:00:34 [error X 1][undefined:2:28] null is not an object (evaluating \'document.getElementById(\'\').focus\') 
JS: 2020-02-11 17:00:34 [error X 1][undefined:2:30] null is not an object (evaluating \'document.getElementById(\'en\').focus\') 
JS: 2020-02-11 17:00:34 [error X 1][undefined:2:32] null is not an object (evaluating \'document.getElementById(\'enro\').focus\') 
JS: 2020-02-11 17:00:35 [error X 1][undefined:2:35] null is not an object (evaluating \'document.getElementById(\'enrollm\').focus\') 
JS: 2020-02-11 17:00:35 [error X 1][undefined:2:38] null is not an object (evaluating \'document.getElementById(\'enrollment\').focus\') 
JS: 2020-02-11 17:00:35 [error X 1][undefined:2:39] null is not an object (evaluating \'document.getElementById(\'enrollment-\').focus\') 
JS: 2020-02-11 17:00:35 [error X 1][undefined:2:42] null is not an object (evaluating \'document.getElementById(\'enrollment-for\').focus\') 
JS: 2020-02-11 17:00:36 [error X 2][undefined:2:43] null is not an object (evaluating \'document.getElementById(\'enrollment-form\').focus\') 
JS: 2020-02-12 17:50:14 [error X 3][https://happyelementor.wpengine.com/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=2.8.3:2:43023] undefined is not an object (evaluating \'o.content[0].settings\') 

</details>

**Comment by mirokosut** [comment]
<img width="370" alt="Screenshot 2020-02-12 at 19 44 34" src="https://user-images.githubusercontent.com/60759624/74367177-b9dd1980-4dd1-11ea-9dd9-6423fe18ef1e.png">

**Comment by mirokosut** [comment]
<img width="338" alt="Screenshot 2020-02-12 at 19 44 43" src="https://user-images.githubusercontent.com/60759624/74367209-c5c8db80-4dd1-11ea-9c22-5f8e0ebe1b66.png">

**Comment by mirokosut** [comment]
I am using FontAwesome **PRO** Kit in Elementor "Integrations".

As you can see, the bug behavior is different between SHARE icons and FOLLOW icons. The share icons are TOO small, and the follow icons inherit some default/weird color and cannot be customized. Neither color nor size can be adjusted as long as FontAwesome **PRO** Kit in Elementor "Integrations" is used.

When I deactivate the FontAwesome **PRO** Kit from Integrations, everything works well: The Icons are the size they are configured to be, and also use the color as specified in the elementor settings (social share).

Let me know if you have any questions. You can also call me at the phone number I use in my account on elementor.com (European time :-)).

Thank you.

**Comment by joehspencer** [comment]
I am having a similar problem with the submenu indicator. 
This happened after I linked my Font Awesome Pro Kit.
It is supposed to be a chevron.

![Screen Shot 2020-02-14 at 4 38 56 PM](https://user-images.githubusercontent.com/26941664/74578273-8375da80-4f48-11ea-9de0-8019aa37c7cb.png)
