### ISSUE TITLE
Accessing Form Metadata in Custom Action After Submit

### ISSUE THREAD

**Issue by cventuram** [elementor/elementor#10702]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description
I created a **_Custom Action After Submit_** that sends an email using wp_mail. (I based this custom action on the Sendy example.)
**I am having trouble including the form metadata (remote_ip, date, time, referrer, etc.) in the email message.**

## Steps to reproduce
I tried mimicking the way fields data is pulled by using the following code:
```
// Get Form metadata
		$raw_meta = $record->get('meta');

// Normalize Form metadata
		$meta = [];
		foreach ( $raw_meta as $meta_id => $meta ) {
			$meta[ $meta_id ] = $meta['value'];
		}
```

Then when sending the email I'm trying to include it using:

  ```
 Date: '.$meta['date'].'<br />
   Time: '.$meta['time'].'<br />
   Remote IP: '.$meta['remote_ip'].'<br />
   Page URL: '.$meta['page_url'].'<br />';
```

Normal fields are being pulled and render as expected. For example:
  

```
         Email: '.$fields['email'].'<br />
	Company: '.$fields['company'].'<br />
	Industry: '.$fields['subCategory'].'<br />
```

![Screen Shot 2020-02-28 at 4 25 55 PM](https://user-images.githubusercontent.com/61473848/75592344-ad9ac280-5a47-11ea-9531-7054e5e6dbfd.png)

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X ] This bug happens with a default WordPress theme active.
- [X ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release '31', Revision 'd14ef86' v5.7.28-31
	PHP Version: 7.3.14-6+ubuntu18.04.1+deb.sury.org+1
	PHP Max Input Vars: 10000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.3.2
	Site URL: https://speakwrite.com
	Home URL: https://speakwrite.com
	WP Multisite: No
	Max Upload Size: 50 MB
	Memory limit: 512M
	Permalink Structure: /%category%/%postname%/
	Language: en-US
	Timezone: America/Chicago
	Debug Mode: Inactive

== Theme ==
	Name: SpeakWrite
	Version: 1.0
	Author: Luke Smith
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36

== Active Plugins ==
	ACF: Better Search
		Version: 3.4.3
		Author: Mateusz Gbiorczyk

	ACF Duplicate Repeater
		Version: 2.0.2
		Author: Jörn Lund

	Admin Columns Pro
		Version: 4.7.3
		Author: AdminColumns.com

	Admin Columns Pro - Advanced Custom Fields (ACF)
		Version: 2.5.5
		Author: Admin Columns

	Advanced Custom Fields PRO
		Version: 5.8.7
		Author: Elliot Condon

	Autoclear Autoptimize Cache
		Version: 2.0.0
		Author: Theme Surgeons

	Autoptimize
		Version: 2.6.1
		Author: Frank Goossens (futtta)

	Calculated Fields Form
		Version: 5.0.37
		Author: CodePeople.net

	Change Case
		Version: 2.0.3
		Author: Michael Aronoff

	Classic Editor
		Version: 1.5
		Author: WordPress Contributors

	Contact Form 7
		Version: 5.1.6
		Author: Takayuki Miyoshi

	Contact Form 7 HubSpot
		Version: 1.1.1
		Author: CRM Perks

	Defender Pro
		Version: 2.2.5
		Author: WPMU DEV

	Download Manager
		Version: 3.0.8
		Author: W3 Eden

	Duplicate Post
		Version: 3.2.4
		Author: Enrico Battocchi

	Elementor
		Version: 2.8.5
		Author: Elementor.com

	Elementor Pro
		Version: 2.8.2
		Author: Elementor.com

	Flamingo
		Version: 2.1.1
		Author: Takayuki Miyoshi

	Google Tag Manager for Wordpress
		Version: 1.11.2
		Author: Thomas Geiger

	Honeypot for Contact Form 7
		Version: 1.14.1
		Author: Nocean

	Max Mega Menu
		Version: 2.7.4
		Author: megamenu.com

	Modern Events Calendar Lite
		Version: 5.0.5
		Author: Webnus Team

	My Custom Functions
		Version: 4.41
		Author: Space X-Chimp

	Redirection
		Version: 4.6.2
		Author: John Godley

	Redirection for Contact Form 7
		Version: 1.3.5
		Author: Query Solutions

	Regenerate Thumbnails
		Version: 3.1.2
		Author: Alex Mills (Viper007Bond)

	Search Exclude
		Version: 1.2.5
		Author: Roman Pronskiy

	Simple Custom Post Order
		Version: 2.4.8
		Author: Colorlib

	Smush Pro
		Version: 3.4.2
		Author: WPMU DEV

	SVG Support
		Version: 2.3.17
		Author: Benbodhi

	TablePress
		Version: 1.10
		Author: Tobias Bäthge

	TinyMCE Advanced
		Version: 5.3.0
		Author: Andrew Ozz

	UpdraftPlus - Backup/Restore
		Version: 2.16.3.1
		Author: UpdraftPlus.Com, DavidAnderson

	WPDM - Extended Short-codes
		Version: 2.8.2
		Author: Shaon

	WPMU DEV Dashboard
		Version: 4.7.5
		Author: WPMU DEV

	Yoast SEO
		Version: 12.9.1
		Author: Team Yoast

== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

	Force Strong Passwords - WPE Edition
		Version: 1.6.4
		Author: Jason Cosper

	WP Engine Seamless Login Plugin
		Version: 1.5.3
		Author: WP Engine

	WP Engine Security Auditor
		Version: 1.0.8
		Author: wpengine

	WP Engine System
		Version: 3.2.3
		Author: WP Engine

== Elements Usage ==
	
	page : 3
		button : 1
		divider : 4
		form : 2
		heading : 1
		icon : 3
		image : 21
		menu-anchor : 5
		nav-menu : 1
		spacer : 8
		text-editor : 49
		video : 1
	popup : 13
		button : 2
		form : 6
		global : 1
		heading : 10
		html : 3
		spacer : 6
		text-editor : 9
	section : 10
		button : 4
		call-to-action : 1
		global : 1
		heading : 6
		html : 1
		icon : 7
		image : 1
		spacer : 2
		text-editor : 15
		toggle : 2
		video : 1
	wp-post : 2
		accordion : 1
		button : 74
		call-to-action : 6
		countdown : 2
		counter : 12
		divider : 16
		facebook-comments : 1
		form : 11
		global : 10
		heading : 124
		html : 14
		icon : 59
		icon-box : 1
		icon-list : 6
		image : 66
		media-carousel : 1
		menu-anchor : 11
		nav-menu : 3
		price-table : 5
		share-buttons : 3
		spacer : 48
		testimonial : 1
		text-editor : 225
		toggle : 1
		wp-widget-wpdm_catpacks_widget : 4
	wp-page : 36
		button : 17
		call-to-action : 7
		divider : 3
		form : 3
		heading : 64
		html : 2
		icon : 20
		icon-box : 4
		icon-list : 7
		image : 24
		nav-menu : 3
		posts : 1
		reviews : 13
		spacer : 41
		text-editor : 34

== Log ==
	
Log: showing 20 of 232019-08-16 13:24:09 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.6.2',
  'to' => '2.6.8',
)]
2019-08-16 13:24:10 [info] elementor::elementor_updater Started 
2019-08-16 13:24:10 [info] Elementor/Upgrades - _v_2_6_6_fa4_migration_button Start  
2019-08-16 13:24:10 [info] Elementor/Upgrades - _v_2_6_6_fa4_migration_button Finished 
2019-08-16 13:24:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.6.2',
  'to' => '2.6.8',
)]
2019-10-29 14:39:24 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.6.8',
  'to' => '2.7.5',
)]
2019-10-29 14:39:27 [info] elementor::elementor_updater Started 
2019-10-29 14:39:27 [info] Elementor/Upgrades - _v_2_7_1_remove_old_usage_data Start  
2019-10-29 14:39:27 [info] Elementor/Upgrades - _v_2_7_1_remove_old_usage_data Finished 
2019-10-29 14:39:27 [info] Elementor/Upgrades - _v_2_7_1_recalc_usage_data Start  
2019-10-29 14:39:28 [info] Elementor/Upgrades - _v_2_7_1_recalc_usage_data Finished 
2019-10-29 14:39:28 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.6.8',
  'to' => '2.7.5',
)]
2019-12-11 17:22:34 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.7.5',
  'to' => '2.8.1',
)]
2019-12-31 15:45:41 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.8.1',
  'to' => '2.8.2',
)]
2019-12-31 15:57:12 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.5',
  'to' => '2.8.2',
)]
2020-01-28 10:15:56 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.8.2',
  'to' => '2.8.5',
)]
2020-01-28 10:15:58 [info] elementor::elementor_updater Started 
2020-01-28 10:15:58 [info] Elementor/Upgrades - _v_2_8_3_recalc_usage_data Start  
2020-01-28 10:15:59 [info] Elementor/Upgrades - _v_2_8_3_recalc_usage_data Finished 
2020-01-28 10:15:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.8.2',
  'to' => '2.8.5',
)]

JS: showing 14 of 14JS: 2019-07-23 15:11:03 [error X 1][https://speakwrite.com/wp-content/plugins/elementor/assets/lib/e-select2/js/e-select2.full.min.js?ver=4.0.6-rc.1:1:60824] Cannot read property \'query\' of null 
JS: 2019-07-23 20:15:24 [error X 49][https://speakwrite.com/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=2.6.2:2:38135] n.attributes[e.name].each is not a function 
JS: 2019-07-23 20:15:24 [error X 1][https://speakwrite.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view12502\") has already been destroyed and cannot be used. 
JS: 2019-07-30 19:12:39 [error X 1][https://speakwrite.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view3910\") has already been destroyed and cannot be used. 
JS: 2019-08-22 22:16:40 [error X 15][https://speakwrite.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.6.8:7:19756] Cannot read property \'noUiSlider\' of undefined 
JS: 2019-11-08 11:54:31 [error X 24][https://speakwrite.com/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=2.5.5:2:6433] elementor.templates.getScreens is not a function 
JS: 2019-12-31 22:33:31 [error X 1][https://speakwrite.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.8.2:2:56072] Cannot read property \'select2\' of undefined 
JS: 2020-01-07 18:01:20 [error X 1][https://speakwrite.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view9185\") has already been destroyed and cannot be used. 
JS: 2020-01-22 23:05:23 [error X 1][https://speakwrite.com/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=2.8.2:2:40565] Cannot read property \'findByModelCid\' of undefined 
JS: 2020-01-24 16:39:02 [error X 1][https://speakwrite.com/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=2.8.2:2:46256] Cannot read property \'addChildModel\' of undefined 
JS: 2020-01-24 16:57:08 [error X 2][https://speakwrite.com/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=2.8.2:2:22686] Cannot read property \'children\' of undefined 
JS: 2020-01-31 17:56:17 [error X 26][https://speakwrite.com/wp-content/plugins/elementor/assets/js/editor-document.min.js?ver=2.8.5:2:28800] container or containers are required. 
JS: 2020-02-06 16:39:10 [error X 4][https://speakwrite.com/wp-admin/load-scripts.php?c=0&loadchunk_0=underscore,jquery-core,jquery-migrate,backbone,shortcode,utils,wp-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jqu&loadchunk_1=ery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable&ver=5.3.2:5:30645] Cannot read property \'pageYOffset\' of undefined 
JS: 2020-02-26 19:36:11 [error X 1][https://speakwrite.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view6788\") has already been destroyed and cannot be used. 

PHP: showing 5 of 5PHP: 2019-09-24 11:57:06 [warning X 1][/nas/content/live/speakwrite/wp-content/plugins/elementor-pro/modules/forms/actions/activecampaign.php::251] Invalid argument supplied for foreach() [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-12-11 17:22:24 [error X 1][/nas/content/live/speakwrite/wp-content/plugins/elementor/includes/plugin.php::545] Uncaught Error: Class 'Elementor\Schemes_Manager' not found in /nas/content/live/speakwrite/wp-content/plugins/elementor/includes/plugin.php:545
Stack trace:
#0 /nas/content/live/speakwrite/wp-content/plugins/elementor/includes/plugin.php(479): Elementor\Plugin->init_components()
#1 /nas/content/live/speakwrite/wp-includes/class-wp-hook.php(288): Elementor\Plugin->init('')
#2 /nas/content/live/speakwrite/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters(NULL, Array)
#3 /nas/content/live/speakwrite/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#4 /nas/content/live/speakwrite/wp-settings.php(523): do_action('init')
#5 /nas/content/live/speakwrite/wp-config.php(119): require_once('/nas/content/li...')
#6 /nas/content/live/speakwrite/wp-load.php(37): require_once('/nas/content/li...')
#7 /nas/content/live/speakwrite/wp-blog-header.php(13): require_once('/nas/content/li...')
#8 /nas/content/live/speakwrite/index.php(17): require('/nas/content/li...')
#9 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-12-11 17:22:25 [error X 1][/nas/content/live/speakwrite/wp-content/plugins/elementor/includes/plugin.php::545] Uncaught Error: Class 'Elementor\Schemes_Manager' not found in /nas/content/live/speakwrite/wp-content/plugins/elementor/includes/plugin.php:545
Stack trace:
#0 /nas/content/live/speakwrite/wp-content/plugins/elementor/includes/plugin.php(479): Elementor\Plugin->init_components()
#1 /nas/content/live/speakwrite/wp-includes/class-wp-hook.php(288): Elementor\Plugin->init('')
#2 /nas/content/live/speakwrite/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters(NULL, Array)
#3 /nas/content/live/speakwrite/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#4 /nas/content/live/speakwrite/wp-settings.php(523): do_action('init')
#5 /nas/content/live/speakwrite/wp-config.php(119): require_once('/nas/content/li...')
#6 /nas/content/live/speakwrite/wp-load.php(37): require_once('/nas/content/li...')
#7 /nas/content/live/speakwrite/wp-admin/admin-ajax.php(22): require_once('/nas/content/li...')
#8 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-12-31 15:57:20 [notice X 25330][/nas/content/live/speakwrite/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-url.php::56] Undefined index: return_format [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-01-28 13:02:41 [notice X 1][/nas/content/live/speakwrite/wp-content/plugins/elementor-pro/modules/query-control/module.php::359] Undefined index: q [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

				
</details>

**Comment by cventuram** [comment]
Hi all,

I have managed to solve this by taking a closer look at the [Sendy example](https://developers.elementor.com/forms-api/custom-form-action/) and using basis PHP date functions. Here is the code if anyone needs it:
```
                 $clientip = \ElementorPro\Classes\Utils::get_client_ip();
		$referrer = isset( $_POST['referrer'] ) ? $_POST['referrer'] : '';
		date_default_timezone_set("America/Chicago");
		$date = date ("m/d/Y");
		$time = date ("h:i a");
```

Now emails are displaying data properly.

Thank you!
