### ISSUE TITLE
Template sections with global (HTML) widgets not rendering in editor mode

### ISSUE THREAD

**Issue by mjoswig** [elementor/elementor#10725]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

1. Create new section on page "Test123"
2. Drag HTML element into section and save HTML element as global widget "Global_Widget_Test123"
3. Save section as template "Module_Test123"
4. Create new page and select "Module_Test123" from template library
5. Global widget "Global_Widget_Test123" in inserted template "Module_Test123" is not being rendered in editor mode (see screenshot) ...

When duplicating the template section "Module_Test123", it renders the global widget normally in editor mode. Also, there seems to be an error in the error log ("Undefined index: templateID", see below in the environment details).

<img width="1680" alt="Bildschirmfoto 2020-03-03 um 01 08 46" src="https://user-images.githubusercontent.com/4945802/75699787-f96d9600-5ceb-11ea-9ba7-0568e666aa80.png">

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release '26', Revision 'c8fe767' v5.7.24-26
	PHP Version: 7.2.24-0ubuntu0.18.04.2
	PHP Max Input Vars: 1000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: No
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.3.2
	WP Multisite: No
	Max Upload Size: 100 MB
	Memory limit: 1024M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 5.8.7
		Author: Elliot Condon

	Classic Editor
		Version: 1.5
		Author: WordPress Contributors

	Elementor
		Version: 2.8.1
		Author: Elementor.com

	Elementor Pro
		Version: 2.8.3
		Author: Elementor.com

	Wordfence Security
		Version: 7.4.5
		Author: Wordfence

	Yoast SEO
		Version: 13.1
		Author: Team Yoast


== Must-Use Plugins ==
	rm-version.php
		Version: 
		Author: 


== Elements Usage ==
	
	page : 5
		global : 38
		html : -9
	section : 24
		global : 22
	wp-page : 7
		global : 47
		html : -59


== Log ==
	
PHP: showing 2 of 2PHP: 2020-02-29 05:51:34 [notice X 7][/virtual/www/wordpress/wp-content/plugins/elementor-pro/modules/global-widget/widgets/global-widget.php::30] Undefined index: templateID [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-02-29 05:53:10 [error X 2][/virtual/www/wordpress/wp-content/plugins/elementor/includes/base/controls-stack.php::1913] Uncaught TypeError: Argument 1 passed to Elementor\Controls_Stack::sanitize_settings() must be of the type array, null given, called in /virtual/www/wordpress/wp-content/plugins/elementor/includes/base/controls-stack.php on line 1023 and defined in /virtual/www/wordpress/wp-content/plugins/elementor/includes/base/controls-stack.php:1913
Stack trace:
#0 /virtual/www/wordpress/wp-content/plugins/elementor/includes/base/controls-stack.php(1023): Elementor\Controls_Stack->sanitize_settings(NULL)
#1 /virtual/www/wordpress/wp-content/plugins/elementor/includes/base/element-base.php(710): Elementor\Controls_Stack->get_data()
#2 /virtual/www/wordpress/wp-content/plugins/elementor/includes/base/widget-base.php(552): Elementor\Element_Base->get_raw_data(false)
#3 /virtual/www/wordpress/wp-content/plugins/elementor-pro/modules/global-widget/widgets/global-widget.php(64): Elementor\Widget_Base->get_raw_data(false)
#4 /virtual/www/wordpress/wp-content/plugins/elementor/includes/base/element-base.php(715): ElementorPro\Mod [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 1 of 1JS: 2020-03-02 15:58:39 [error X 3][https://xyz.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.8.1:31:166248] Cannot read property \'get\' of undefined 


				
```
</details>

**Comment by alarstyle** [comment]
Got the same issue!

**Comment by steffanhalv** [comment]
Me to!

**Comment by MichaelDarko** [comment]
+1

**Comment by Aviad-Herman** [comment]
Hello,
Is this still an issue or has it been solved in the latest versions of Elementor?

If the bug persists, we recently updated the infrastructure behind Global Widgets. The update is currently only available on Elementor's developer edition releases (https://elementor.com/blog/introducing-beta-developer-edition/). Could you see if the bug still happens on the developer release?

Important note: the developer releases should not be used on live sites

**Comment by rami-elementor** [comment]
Closing for lack of activity,

Feel free to reopen if the issue persists.
