### ISSUE TITLE
Elementor does not play nicely with Yoast SEO

### ISSUE THREAD

**Issue by bobmulder** [elementor/elementor#10748]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Good morning all! I am kinda confused since I am using Elementor Pro (where I heavily use the theme builder) combined with WooCommerce, Yoast SEO Premium and Yoast WooCommerce.

**Yoast WooCommerce claims to add several schema data to improve search results (like the `@type` `Product`), however I discovered this data is not added at all to my product pages!**

Doing several tests made me conclude this happened by using the theme builder from Elementor to design my single product page. Thing is, Elementors' theme builder overrides existing page templates (which is logically) but doesn't execute necessary hooks like `woocommerce_single_product_summary`. 

After my tests as seen above I have two options to say:
1. Yoast does not play nice with visual builders and should change it's hooks (e.g. `woocommerce_single_product_summary`).
2. Elementor does not play nice with WooCommerce since WooCommerce has standard hooks to be used but does not execute them.

## Steps to reproduce

- Get an installation of Wordpress
- Install Elementor Pro, WooCommerce, Yoast SEO & Yoast WooCommerce (premium plugin)
- Create a 'Single Product' template in the theme builder
- View the page source of your fresh created product
- **See that no `@type: Product` is available under the scheme**

_Whenever you want to see what **should** happen:_

- Disable the 'Single Product' template in the theme builder
- View the page source of your product
- **See that a `@type: Product` is available under the scheme!!!**

## Isolating the problem
- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
Not relevant, plugins used:

- Elementor Pro (including theme builder)
- WooCommerce
- Yoast SEO Premium
- Yoast WooCommerce
</details>

**Comment by bobmulder** [comment]
Addition: I headed over to Yoast to check if there's anything on their responsibility (according the hooking on the actions). See their response here: https://github.com/Yoast/wpseo-woocommerce/issues/545

**Comment by bobmulder** [comment]
Anyone from the Elementor team?

**Comment by bobmulder** [comment]
Beside this issue I connected with Elementor support. To be as complete as possible and to help others with this issue, the reply below:

_Many thanks for your continued patience as we investigated this issue._

> For your information, we have narrowed down this particular issue with the Yoast SEO WC plugin to be stemming from the WC "woocommerce_single_product_summary" action hook not being included for execution while using a single template.
&nbsp;
By its default nature, our Theme Builder essentially removes all default WC template action hooks on the single product template so that only the added sections via the single product widgets are rendered. This can (for example) be the "woocommerce_template_single_title" hook for the Product Title widget, or the "woocommerce_template_single_add_to_cart" for the Add to Cart widget. As it relates to re-adding/re-firing third-party hooks added from other plugins or custom coding, this is a scenario our development team are currently looking into.
&nbsp;
In the interim, as a possible temporary solution (if you are comfortable with coding), you may add a custom shortcode function code to your child theme's "functions.php" file (or by using a PHP code snippet management plugin such as Code Snippets) that will essentially run/re-add this missing WC hook manually.This shortcode would then be added to the single product template (as the last widget on this template if desired) using a Shortcode widget which should, in turn, render the Yoast product schema. For quick reference and testing/modification on your end, please see the coding for the sample shortcode [add_wc_single_product_summary] in the text file attached.
&nbsp;
This shortcode function includes running the WC "woocommerce_single_product_summary" action hook that is also used in WC's default single product content template file to render the content added to this particular hook or template section. However, the undesired WC template action functions that are added to this WC hook must be removed; this is done using the "remove_action()" WP function seen in the coding.
&nbsp;
Please note that we do not provide support for custom coding nor customizations that extends the default Elementor functionalities. However, we've made an exception in this particular case.

I will post a code sample later on...

**Comment by bobmulder** [comment]
Custom shortcode used:

```php
add_shortcode( 'wc_product_seo', 'wc_product_seo' );

function wc_product_seo($atts){
	
 	/* Remove any unwanted 'woocommerce_single_product_summary' hooks */
	remove_action( 'woocommerce_single_product_summary', 'woocommerce_template_single_title', 5 );
	remove_action( 'woocommerce_single_product_summary', 'woocommerce_template_single_rating', 10 );
	remove_action( 'woocommerce_single_product_summary', 'woocommerce_template_single_price', 10 );
	remove_action( 'woocommerce_single_product_summary', 'woocommerce_template_single_excerpt', 20 );
	remove_action( 'woocommerce_single_product_summary', 'woocommerce_template_single_add_to_cart', 30 );
	remove_action( 'woocommerce_single_product_summary', 'woocommerce_template_single_meta', 40 );
	remove_action( 'woocommerce_single_product_summary', 'woocommerce_template_single_sharing', 50 );

	// Run the 'woocommerce_single_product_summary' action hook
	do_action( 'woocommerce_single_product_summary' );
}
```

**Comment by bartekwiak** [comment]
I've used this function / shortcode combo and Product Rich Snippets are showing in Google search results, but when I try to edit an elementor product template with the shortcode present, I get a fatal error:

```
`Fatal error: Uncaught Error: Call to a member function get_id() on bool in /(...)/public_html/wp-content/plugins/judgeme-product-reviews-woocommerce/includes/class-jgm-widget.php:136 Stack trace: 
#0 /(...)/public_html/wp-includes/class-wp-hook.php(287): JGM_Widget::judgeme_preview_badge('') 
#1 /(...)/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array) 
#2 /(...)/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array) 
#3 /(...)/public_html/wp-content/themes/petcostumecenter/functions.php(70): do_action('woocommerce_sin...') 
#4 /(...)/public_html/wp-includes/shortcodes.php(343): add_wc_single_product_summary_handler('', '', 'add_wc_single_p...') 
#5 [internal function]: do_shortcode_tag(Array) 
#6 /(...)/public_html/wp-includes/shortcodes.php(218 in /(...)/public_html/wp-content/plugins/judgeme-product-reviews-woocommerce/includes/class-jgm-widget.php on line 136`
```

class-jgm-widget.php:**136**:
```
	$id = $product->get_id();
```

When I remove the jdg_widget, there's another one that throws this error. And when I remove the custom schema shortcode, it's working.

Anyone else having this issue?

**Comment by hansfineart** [comment]
Hey together,

I had the same problem and I used to code and it seams to work well.

But I have one the Price information displayed in the google search as you can see in this screenshot.

![IMG_7733](https://user-images.githubusercontent.com/112409262/187397168-281f50a0-2b35-4c3e-9d7d-9a7fcc07063b.jpg)

But If I use the google Rich search an analysis the site it's shows the price and the star rating information too still missing the stock information as you can see here.

![Bildschirmfoto 2022-08-30 um 09 10 43](https://user-images.githubusercontent.com/112409262/187397216-22ba0f6c-f979-43b9-8cb6-e033a31f871c.png)

Any ideas why this is happening. I for myself are an absolute dummy of coding etc. I just use this code and was happy that it works.

Thanks Hans
