### ISSUE TITLE
Facebook Comments box appears even when not set

### ISSUE THREAD

**Issue by ohadh** [elementor/elementor#10848]
## Prerequisites

- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X ] The issue still exists against the latest stable version of Elementor.

## Description

Facebook comments box appears on homepage under video. I have disabled all plugins except Elementor, Elementor Pro and GP Premium (Generatepress theme), but FB Comments box persists. Disappears only when disabling Elementor Pro as well. I checked KB and made sure the Facebook App ID field was blank in Elementor Settings > Integrations, but still the comments box persists. 

## Steps to reproduce

Disable all plugins except Elementor, Elementor Pro, and theme plugin (GP Premium)
Ensure Facebook App ID in Elementor Settings > Integrations is blank
Load homepage, Facebook Comments box appears under video
Site: elementor.cbtisrael.co.il

## Isolating the problem

- [X ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [X ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
				
== Server Environment ==
	Operating System: Linux
	Software: Apache/6.6.6
	MySQL version: MariaDB Server v5.5.40-MariaDB-36.1
	PHP Version: 7.3.5
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.3.2
	Site URL: https://elementor.cbtisrael.co.il
	Home URL: https://elementor.cbtisrael.co.il
	WP Multisite: No
	Max Upload Size: 2 MB
	Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: he-IL
	Timezone: 2
	Debug Mode: Inactive

== Theme ==
	Name: GeneratePress
	Version: 2.4.1
	Author: Tom Usborne
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: he_IL
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36

== Active Plugins ==
	ActiveCampaign
		Version: 7.1.2
		Author: ActiveCampaign

	Autoptimize
		Version: 2.6.2
		Author: Frank Goossens (futtta)

	Checkout Field Editor for WooCommerce
		Version: 1.4.1
		Author: ThemeHigh

	Elementor
		Version: 2.9.6
		Author: Elementor.com

	Elementor Pro
		Version: 2.8.5
		Author: Elementor.com

	Envato Market
		Version: 2.0.3
		Author: Envato

	GP Premium
		Version: 1.9.1
		Author: Tom Usborne

	iCount Payment Gateway
		Version: 1.5.6
		Author: iCount Systems

	Imagify
		Version: 1.9.9
		Author: WP Media

	Jetpack by WordPress.com
		Version: 8.3
		Author: Automattic

	Online Appointment Scheduling Widget and Booking System
		Version: 4.0.3
		Author: Simplybook Inc.

	Redirection
		Version: 4.7.1
		Author: John Godley

	Strong Testimonials
		Version: 2.40.1
		Author: MachoThemes

	WooCommerce
		Version: 4.0.0
		Author: Automattic

	WooCommerce Colors
		Version: 1.0.7
		Author: WooThemes

	WooCommerce Google Analytics Integration
		Version: 1.4.19
		Author: WooCommerce

	WooCommerce PayPal Checkout Gateway
		Version: 1.6.20
		Author: WooCommerce

	WooCommerce Services
		Version: 1.22.4
		Author: Automattic

	WooCommerce Zapier Integration
		Version: 1.9.6
		Author: OM4

	WordPress Related Posts Thumbnails
		Version: 1.8.2
		Author: WPBrigade

	WP-Pro-Quiz
		Version: 0.37
		Author: Julius Fischer

	WP Rocket
		Version: 3.5.0.4
		Author: WP Media

	WP Show Posts
		Version: 1.1.3
		Author: Tom Usborne

	WP YouTube Lyte
		Version: 1.7.11
		Author: Frank Goossens (futtta)

	Yoast SEO
		Version: 13.2
		Author: Team Yoast


== Elements Usage ==
	
	page : 59
		accordion : 2
		button : 23
		counter : 4
		divider : 3
		google_maps : 2
		heading : 75
		icon-box : 13
		icon-list : 11
		image : 21
		social-icons : 1
		testimonial : 4
		text-editor : 44
		video : 2
	section : 33
		button : 1
		heading : 1
		image : 1
	single : 1
		breadcrumbs : 1
		heading : 2
		html : 1
		post-info : 1
		posts : 1
		search-form : 1
		spacer : 1
		theme-post-content : 1
		theme-post-featured-image : 1
		theme-post-title : 1
	widget : 0
		button : 3
		call-to-action : 14
		html : 25
		spacer : 5
		text-editor : 88
	wp-post : 119
		audio : 9
		button : 2
		divider : 10
		facebook-comments : 1
		global : 27
		heading : 4
		html : 1
		icon : 3
		image : 3
		spacer : 17
		testimonial-carousel : 1
		text-editor : 51
		video : 18
		wp-widget-categories : 1
		wp-widget-wpsp_widget : 1
	wp-page : 14
		divider : 3
		global : 2
		heading : 2
		html : 1
		image : 5
		posts : 1
		text-editor : 15
		video : 1


== Log ==
	
Log: showing 20 of 362020-01-15 13:27:26 [info] Elementor/Upgrades - _v_2_8_3_recalc_usage_data Start  
2020-01-15 13:32:35 [info] elementor::elementor_updater Started 
2020-01-15 13:32:35 [info] Elementor/Upgrades - _v_2_8_3_recalc_usage_data Start  
2020-01-15 13:37:28 [info] elementor::elementor_updater Started 
2020-01-15 13:37:28 [info] Elementor/Upgrades - _v_2_8_3_recalc_usage_data Start  
2020-01-15 13:42:27 [info] elementor::elementor_updater Started 
2020-01-15 13:42:27 [info] Elementor/Upgrades - _v_2_8_3_recalc_usage_data Start  
2020-01-23 21:38:58 [info] elementor::elementor_updater Started 
2020-01-23 21:38:58 [info] Elementor/Upgrades - _v_2_8_3_recalc_usage_data Start  
2020-01-23 21:53:53 [info] elementor::elementor_updater Started 
2020-01-23 21:53:53 [info] Elementor/Upgrades - _v_2_8_3_recalc_usage_data Start  
2020-02-04 13:37:59 [info] elementor::elementor_updater Started 
2020-02-04 13:37:59 [info] Elementor/Upgrades - _v_2_8_3_recalc_usage_data Start  
2020-02-04 16:08:12 [info] elementor::elementor_updater Started 
2020-02-04 16:08:12 [info] Elementor/Upgrades - _v_2_8_3_recalc_usage_data Start  
2020-02-04 16:58:07 [info] elementor::elementor_updater Started 
2020-02-04 16:58:07 [info] Elementor/Upgrades - _v_2_8_3_recalc_usage_data Start  
2020-02-18 10:18:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.8.3',
  'to' => '2.8.4',
)]
2020-03-12 16:01:41 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.8.4',
  'to' => '2.8.5',
)]
2020-03-12 16:01:42 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.8.4',
  'to' => '2.8.5',
)]

JS: showing 5 of 5JS: 2020-01-16 13:55:31 [error X 2][https://elementor.cbtisrael.co.il/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.8.3:31:180769] Cannot read property \'getBoundingClientRect\' of null 
JS: 2020-01-25 10:04:14 [error X 1][https://elementor.cbtisrael.co.il/wp-admin/post.php?post=8026&action=elementor:1:14] SimplybookWidget is not defined 
JS: 2020-01-25 10:04:24 [error X 2][https://elementor.cbtisrael.co.il/wp-admin/post.php?post=8026&action=elementor:3:47] Cannot set property \'innerHTML\' of null 
JS: 2020-01-25 11:39:18 [error X 8][https://elementor.cbtisrael.co.il/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.8.4:2:67363] Cannot read property \'getContainer\' of undefined 
JS: 2020-02-20 13:25:57 [error X 2][https://elementor.cbtisrael.co.il/wp-content/plugins/elementor/assets/lib/e-select2/js/e-select2.full.min.js?ver=4.0.6-rc.1:1:74235] Cannot read property \'destroy\' of undefined 

PHP: showing 1 of 1PHP: 2020-01-23 21:38:58 [error X 5][/home/cbtisrael/domains/cbtisrael.co.il/public_html/elementor/wp-content/plugins/elementor/includes/managers/elements.php::68] Uncaught TypeError: Argument 1 passed to Elementor\Elements_Manager::create_element_instance() must be of the type array, string given, called in /home/cbtisrael/domains/cbtisrael.co.il/public_html/elementor/wp-content/plugins/elementor/core/base/document.php on line 692 and defined in /home/cbtisrael/domains/cbtisrael.co.il/public_html/elementor/wp-content/plugins/elementor/includes/managers/elements.php:68
Stack trace:
#0 /home/cbtisrael/domains/cbtisrael.co.il/public_html/elementor/wp-content/plugins/elementor/core/base/document.php(692): Elementor\Elements_Manager->create_element_instance('Array')
#1 /home/cbtisrael/domains/cbtisrael.co.il/public_html/elementor/wp-content/plugins/elementor/modules/usage/module.php(566): Elementor\Core\Base\Document->get_elements_raw_data(Array)
#2 /home/cbtisrael/domains/cbtisrael.co.il/public_html/elementor/wp-content/plugins/elementor/modules/usage/module.php(181): Elementor\Modules\Usage\Module->save_document_usage(Object(Elementor\Modules\Library\Documents\Page))
#3 / [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

```
</details>
![Untitled](https://user-images.githubusercontent.com/32332450/76688766-94ddff80-6638-11ea-874c-91539212bc89.png)

**Comment by lior-sh** [comment]
Hi @ohadh,

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
*** Steps to replicate.**
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
