### ISSUE TITLE
Open popup will redirect to 404 when translated with TranslatePress

### ISSUE THREAD

**Issue by tsmedienagentur** [elementor/elementor#10963]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I created a website using Elementor and Elementor Pro with popups that open after clicking on the button linked with the popup. The popups are translated with TranslatePress. In the default language the popups working fine. But when I switch the language the buttons redirect me to a 404 page with the popup link in the url. This issue is just happening with version 2.9.0 and 2.9.1 of Elementor Pro. With Elementor 2.8.5 everything is working fine.

## Steps to reproduce

1. Create a popup
2. Translate the site and the popup with TranslatePress
3. Add a button and link it to the popup with the action "open popup"
4. Switch language and try to open the popup

## Isolating the problem

- [x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x ] This bug happens with a default WordPress theme active.
- [x ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.7.22
	PHP Version: 7.3.15-4+0~20200224.55+debian9~1.gbpbea824
	PHP Max Input Vars: 1000
	PHP Max Post Size: 150M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.3.2
	Site URL: http://michaela.web75.s158.goserver.host
	Home URL: http://michaela.web75.s158.goserver.host
	WP Multisite: No
	Max Upload Size: 150 MB
	Memory limit: -1
	Permalink Structure: /%postname%/
	Language: de-DE
	Timezone: Europe/Berlin
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.2.2
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.137 Safari/537.36 Vivaldi/2.7.1628.33

== Active Plugins ==
	Advanced Custom Fields
		Version: 5.8.8
		Author: Elliot Condon

	Duplicate Post
		Version: 3.2.4
		Author: Enrico Battocchi

	Elementor
		Version: 2.9.6
		Author: Elementor.com

	Elementor Extras
		Version: 2.2.23
		Author: Namogo

	Elementor Pro
		Version: 2.9.1
		Author: Elementor.com

	SEOPress
		Version: 3.8.4
		Author: SEOPress

	TranslatePress - Multilingual
		Version: 1.6.9
		Author: Cozmoslabs, Razvan Mocanu, Madalin Ungureanu, Cristophor Hurduban

	UpdraftPlus - Backup/Restore
		Version: 1.16.22
		Author: UpdraftPlus.Com, DavidAnderson


== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com


== Elements Usage ==
	
	archive : 3
		archive-posts : 1
		ee-calendar : 1
		posts-extra : 1
	footer : 1
		button : 1
		heading : 2
		nav-menu : 1
		social-icons : 1
		text-editor : 2
	header : 3
		heading : 1
		image : 3
		nav-menu : 4
		theme-page-title : 2
		theme-site-logo : 1
	loop : 0
		button : 1
		post-info : 1
		theme-post-title : 1
	popup : 10
		form : 8
		text-editor : 19
	section : 3
		button : 2
		heading : 1
		icon-list : 2
	single : 4
		button : 2
		heading : 13
		icon-list : 5
		post-navigation : 2
		text-editor : 7
		theme-post-content : 3
		theme-post-featured-image : 2
	wp-page : 5
		button : 26
		divider : 4
		ee-calendar : 1
		ee-search-form : 1
		form : 2
		heading : 17
		icon-list : 8
		image : 7
		slides : 1
		text-editor : 28


== Log ==
	
JS: showing 15 of 15JS: 2020-03-03 15:31:14 [error X 198][http://michaela.web75.s158.goserver.host/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=2.8.4:2:54702] Cannot read property \'top\' of undefined 
JS: 2020-03-09 15:04:17 [error X 3][http://michaela.web75.s158.goserver.host/wp-content/plugins/elementor/assets/js/common.min.js?ver=2.9.4:2:106905] Routes: `` not found. 
JS: 2020-03-10 17:33:03 [error X 188][http://michaela.web75.s158.goserver.host/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.9.5:2:73316] Cannot read property \'select2\' of undefined 
JS: 2020-03-11 08:45:11 [error X 1][http://michaela.web75.s158.goserver.host/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view6835\") has already been destroyed and cannot be used. 
JS: 2020-03-11 13:30:38 [error X 1][http://michaela.web75.s158.goserver.host/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=2.9.5:2:36202] Cannot read property \'cid\' of undefined 
JS: 2020-03-11 13:36:33 [error X 1][http://michaela.web75.s158.goserver.host/wp-content/plugins/dynamic-visibility-for-elementor/assets/js/dce-editor-visibility.js?ver=3.0.1:87:5] dce_enable_save_button is not defined 
JS: 2020-03-11 13:45:16 [error X 1][http://michaela.web75.s158.goserver.host/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view5431\") has already been destroyed and cannot be used. 
JS: 2020-03-11 13:48:13 [error X 1][http://michaela.web75.s158.goserver.host/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view7200\") has already been destroyed and cannot be used. 
JS: 2020-03-12 11:28:09 [error X 1][http://michaela.web75.s158.goserver.host/wp-content/plugins/elementor/assets/lib/e-select2/js/e-select2.full.min.js?ver=4.0.6-rc.1:1:74235] Cannot read property \'destroy\' of undefined 
JS: 2020-03-12 11:40:51 [error X 1][http://michaela.web75.s158.goserver.host/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view13856\") has already been destroyed and cannot be used. 
JS: 2020-03-12 12:44:37 [error X 1][http://michaela.web75.s158.goserver.host/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view3566\") has already been destroyed and cannot be used. 
JS: 2020-03-12 13:19:58 [error X 1][http://michaela.web75.s158.goserver.host/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view3244\") has already been destroyed and cannot be used. 
JS: 2020-03-12 13:20:13 [error X 1][http://michaela.web75.s158.goserver.host/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view6533\") has already been destroyed and cannot be used. 
JS: 2020-03-12 13:51:39 [error X 1][http://michaela.web75.s158.goserver.host/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view3386\") has already been destroyed and cannot be used. 
JS: 2020-03-12 14:34:11 [error X 1][http://michaela.web75.s158.goserver.host/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view8604\") has already been destroyed and cannot be used. 

Log: showing 5 of 52020-03-09 11:28:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.3',
  'to' => '2.9.4',
)]
2020-03-09 16:06:56 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.8.4',
  'to' => '2.8.5',
)]
2020-03-10 10:17:11 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.4',
  'to' => '2.9.5',
)]
2020-03-16 10:05:43 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.5',
  'to' => '2.9.6',
)]
2020-03-24 13:54:24 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.8.5',
  'to' => '2.9.1',
)]

PHP: showing 14 of 14PHP: 2020-03-09 12:21:55 [error X 1][/home/www/michaela-new/wp-content/plugins/elementor-pro/modules/forms/widgets/login.php::683] Out of memory (allocated 20971520) (tried to allocate 40960 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-03-10 12:15:22 [notice X 3][/home/www/michaela-new/wp-content/plugins/elementor/includes/template-library/sources/local.php::692] ob_end_clean(): failed to delete buffer. No buffer to delete [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-03-10 12:15:34 [error X 1][/home/www/michaela-new/wp-content/plugins/elementor/includes/managers/controls.php::681] Out of memory (allocated 18874368) (tried to allocate 20480 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-03-10 12:37:24 [error X 1][/home/www/michaela-new/wp-content/plugins/elementor/includes/base/controls-stack.php::1815] Out of memory (allocated 6291456) (tried to allocate 20480 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-03-10 12:39:42 [error X 2][/home/www/michaela-new/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Out of memory (allocated 6291456) (tried to allocate 131072 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-03-10 12:44:15 [error X 1][/home/www/michaela-new/wp-content/plugins/elementor/includes/base/controls-stack.php::622] Out of memory (allocated 6291456) (tried to allocate 12288 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-03-10 12:46:54 [error X 1][/home/www/michaela-new/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Out of memory (allocated 8388608) (tried to allocate 131072 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-03-11 14:08:41 [notice X 4][/home/www/michaela-new/wp-content/plugins/elementor-extras/modules/query-control/types/posts.php::38] Undefined index: object_type [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-03-11 14:19:29 [notice X 8][/home/www/michaela-new/wp-content/plugins/elementor-extras/modules/query-control/types/acf.php::75] Undefined index: show_field_type [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-03-11 14:30:49 [error X 2][/home/www/michaela-new/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Out of memory (allocated 32649216) (tried to allocate 5464288 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-03-11 14:32:16 [error X 1][/home/www/michaela-new/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Out of memory (allocated 22163456) (tried to allocate 5464288 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-03-11 14:40:35 [notice X 16][/home/www/michaela-new/wp-content/plugins/elementor-extras/modules/query-control/types/acf.php::75] Undefined index: show_type [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-03-12 14:03:42 [error X 1][/home/www/michaela-new/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::259] Uncaught Error: Call to a member function update_meta() on null in /home/www/michaela-new/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:259
Stack trace:
#0 /home/www/michaela-new/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(180): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(844, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/www/michaela-new/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/www/michaela-new/wp-includes/class-wp-hook.php(288): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/www/michaela-new/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters('', Array)
#5 /home/www/michaela-new/wp-includes/plu [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-03-25 11:11:56 [notice X 2][/home/www/michaela-new/wp-content/plugins/elementor-extras/modules/display-conditions/module.php::303] Undefined index: ee_display_conditions_enable [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]


		
```
</details>

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account.
