### ISSUE TITLE
Update text in Hebrew appears as squares 

### ISSUE THREAD

**Issue by binnyFriedman** [elementor/elementor#11166]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest stable version of Elementor.

## Description
In elemmentor 2.9.7 (the latest version currently) update button in Hebrew looks like a missing icon.
 
![Screen Shot 2020-04-19 at 10 05 36](https://user-images.githubusercontent.com/49834771/79681790-98f7d100-8225-11ea-8e77-d2b00adeba20.png)

## Steps to reproduce
Wordpress language set to Hebrew;
update elementor to the latest version

## Isolating the problem

- [x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ x] This bug happens with a default WordPress theme active.
- [ x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.17.8
	MySQL version: MariaDB Server v5.5.40-MariaDB-36.1
	PHP Version: 7.0.13
	PHP Max Input Vars: 1000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.4
	Site URL: http://p1413-169-13557.s169.upress.link
	Home URL: http://p1413-169-13557.s169.upress.link
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: he-IL
	Timezone: 3
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Twenty
	Version: 1.2
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: he_IL
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36

== Active Plugins ==
	Classic Editor
		Version: 1.5
		Author: WordPress Contributors

	Elementor
		Version: 2.9.7
		Author: Elementor.com

	Elementor Pro
		Version: 2.9.2
		Author: Elementor.com


== Elements Usage ==
	
	archive : 7
		archive-posts : 1
		breadcrumbs : 2
		heading : 1
		portfolio : 1
		posts : 1
		search-form : 1
		shortcode : 1
		template : 3
		text-editor : 1
		theme-archive-title : 2
	header : 2
		button : 1
		image : 1
		nav-menu : 1
		premium-addon-button : 1
		search-form : 1
		social-icons : 1
		wp-widget-custom_html : 1
	popup : 6
		html : 2
	section : 30
		breadcrumbs : 2
		button : 2
		divider : 2
		form : 4
		heading : 13
		icon : 1
		image : 17
		nav-menu : 5
		posts : 1
		premium-addon-fancy-text : 1
		reviews : 2
		search-form : 1
		social-icons : 1
		text-editor : 10
		theme-post-title : 1
	single : 8
		breadcrumbs : 1
		divider : 2
		global : 2
		heading : 3
		image : 1
		posts : 1
		share-buttons : 1
		shortcode : 1
		template : 5
		theme-post-content : 3
		theme-post-title : 2
	widget : 0
		gallery : 1
		reviews : 1
	wp-post : 18
		image-gallery : 31
		template : 2
		text-editor : 48
		video : 3
	wp-page : 36
		breadcrumbs : 2
		divider : 1
		form : 2
		heading : 5
		html : 8
		image : 31
		image-gallery : 3
		posts : 2
		premium-img-gallery : 2
		search-form : 1
		social-icons : 1
		spacer : 7
		template : 6
		text-editor : 39


== Log ==
	
PHP: showing 6 of 6PHP: 2019-08-07 11:28:07 [notice X 2][/home/sb026853/domains/p1413-169-4400.s169.upress.link/public_html/wp-content/plugins/elementor/core/logger/items/base.php::101] Array to string conversion [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-09-16 09:56:12 [error X 2][/home/sb026853/domains/p1413-169-4400.s169.upress.link/public_html/wp-content/plugins/elementor/includes/controls/number.php::52] Uncaught Error: Undefined class constant 'NUMBER_CATEGORY' in /home/sb026853/domains/p1413-169-4400.s169.upress.link/public_html/wp-content/plugins/elementor/includes/controls/number.php:52
Stack trace:
#0 /home/sb026853/domains/p1413-169-4400.s169.upress.link/public_html/wp-content/plugins/elementor/includes/controls/base.php(73): Elementor\Control_Number->get_default_settings()
#1 /home/sb026853/domains/p1413-169-4400.s169.upress.link/public_html/wp-content/plugins/elementor/includes/managers/controls.php(433): Elementor\Base_Control->__construct()
#2 /home/sb026853/domains/p1413-169-4400.s169.upress.link/public_html/wp-content/plugins/elementor/includes/managers/controls.php(507): Elementor\Controls_Manager->register_controls()
#3 /home/sb026853/domains/p1413-169-4400.s169.upress.link/public_html/wp-content/plugins/elementor/includes/managers/controls.php(526): Elementor\Controls_Manager->get_controls()
#4 /home/sb026853/domains/p1413-169-4400.s169.upress.link/public_html/wp-content/plugins/elementor/inclu [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-09-16 14:40:53 [notice X 20][/home/sb026853/domains/p1413-169-4400.s169.upress.link/public_html/wp-content/plugins/elementor-pro/modules/query-control/module.php::360] Undefined index: q [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-10-23 11:15:07 [notice X 6][/home/ottorita/domains/ottorita.co.il/public_html/wp-content/plugins/elementor-pro/modules/forms/actions/mailchimp.php::194] Undefined index: email_address [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-11-09 10:40:20 [warning X 1][/home/ottorita/domains/ottorita.co.il/public_html/wp-content/plugins/elementor/core/files/manager.php::115] unlink(/home/ottorita/domains/ottorita.co.il/public_html/wp-content/uploads/elementor/css/post-18750.css): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-01-30 12:52:49 [notice X 9][/home/ottorita/domains/ottorita.co.il/public_html/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php::39] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 12 of 12JS: 2019-08-07 13:44:38 [error X 2][http://p1413-169-4400.s169.upress.link/wp-content/plugins/elementor/assets/js/editor-modules.min.js:2:38135] n.attributes[e.name].each is not a function 
JS: 2019-10-02 11:21:42 [error X 12][http://p1413-169-4400.s169.upress.link/wp-content/plugins/elementor/assets/js/editor.min.js:32:63917] this.ui.apply.add is not a function 
JS: 2019-10-07 09:51:20 [error X 1][https://www.ottorita.co.il/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js:22:19954] View (cid: \"view1709\") has already been destroyed and cannot be used. 
JS: 2019-10-10 11:35:19 [error X 4][https://www.ottorita.co.il/wp-content/themes/Nekuda/library/js/scripts.js:123:46] Cannot read property \'top\' of undefined 
JS: 2019-10-23 11:41:00 [error X 2][https://www.ottorita.co.il/wp-content/plugins/elementor-pro/assets/js/editor.min.js:2:32524] Cannot read property \'getControlValue\' of undefined 
JS: 2019-11-05 10:16:09 [error X 2][https://www.ottorita.co.il/wp-content/plugins/elementor/assets/js/editor.min.js:32:132207] Cannot read property \'elementorSerializeObject\' of undefined 
JS: 2019-11-06 12:04:25 [error X 1][https://www.ottorita.co.il/wp-content/plugins/elementor/assets/js/editor.min.js:32:132502] Cannot read property \'html\' of undefined 
JS: 2019-11-06 14:36:18 [error X 4][https://www.ottorita.co.il/wp-content/plugins/elementor/assets/js/editor.min.js:32:171730] this.manager.setPage(...).showView is not a function 
JS: 2019-11-08 22:53:11 [error X 1][https://www.ottorita.co.il/wp-content/plugins/elementor/assets/js/common.min.js?ver=2.7.5:2:66297] Routes: `panel/editor/undefined` not found. 
JS: 2019-11-25 09:55:57 [error X 1][https://www.ottorita.co.il/wp-admin/load-scripts.php?c=0&load%5Bchunk_0%5D=jquery-core,jquery-migrate,underscore,backbone,shortcode,utils,wp-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jqu&load%5Bchunk_1%5D=ery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable&ver=5.3:10:3793] Cannot convert undefined or null to object 
JS: 2019-11-27 09:54:39 [error X 23][https://www.ottorita.co.il/wp-content/plugins/elementor/assets/js/editor.min.js:32:19211] elementor.getCurrentElement(...).isPasteEnabled is not a function 
JS: 2019-12-02 12:54:35 [error X 1][https://www.ottorita.co.il/wp-content/plugins/elementor/assets/js/editor-modules.min.js:2:32565] Cannot read property \'cid\' of undefined 

Log: showing 20 of 242019-09-08 12:39:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '2.5.11',
  'to' => '2.6.5',
)]
2019-09-16 09:56:35 [info] elementor::elementor_updater Started 
2019-09-16 09:56:35 [info] אלמנטור/Upgrades - _v_2_7_0_rename_document_types_to_wp Start  
2019-09-16 09:56:35 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'אלמנטור',
  'from' => '2.6.8',
  'to' => '2.7.0',
)]
2019-09-16 14:17:45 [info] elementor::elementor_updater Started 
2019-09-16 14:17:45 [notice] Could not find אלמנטור/Upgrades - _v_2_7_0_rename_document_types_to_wp callback 
2019-09-16 14:17:45 [notice] Could not find אלמנטור/Upgrades - _v_2_7_0_remove_old_usage_data callback 
2019-09-16 14:17:45 [notice] Could not find אלמנטור/Upgrades - _v_2_7_0_recalc_usage_data callback 
2019-09-16 14:17:45 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור',
  'from' => '2.6.8',
  'to' => '2.7.2',
)]
2019-10-07 12:11:25 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור',
  'from' => '2.7.2',
  'to' => '2.7.4',
)]
2019-11-03 09:30:30 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור',
  'from' => '2.7.4',
  'to' => '2.7.5',
)]
2019-11-09 01:34:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '2.6.5',
  'to' => '2.7.3',
)]
2020-04-19 09:57:01 [info] elementor::elementor_updater Started 
2020-04-19 09:57:01 [info] אלמנטור/Upgrades - _v_2_8_3_recalc_usage_data Start  
2020-04-19 09:57:02 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'אלמנטור',
  'from' => '2.7.5',
  'to' => '2.9.7',
)]
2020-04-19 09:57:02 [info] אלמנטור/Upgrades - _v_2_8_3_recalc_usage_data callback needs to run again 
2020-04-19 09:57:02 [info] אלמנטור/Upgrades - _v_2_8_3_recalc_usage_data Start (x2) 
2020-04-19 09:57:02 [info] אלמנטור/Upgrades - _v_2_8_3_recalc_usage_data Finished 
2020-04-19 09:57:02 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור',
  'from' => '2.7.5',
  'to' => '2.9.7',
)]
2020-04-19 10:00:06 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '2.7.3',
  'to' => '2.9.2',
)]


				
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by shilo-ey** [comment]
Thanks for reporting.

We will address this issue soon and release a patch.

Please follow this thread for updates.

Thanks!

rel: #11168
