### ISSUE TITLE
Motion Effects only work sometimes

### ISSUE THREAD

**Issue by icecandy** [elementor/elementor#11204]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description

Motion effects work inconsistently. I have applied a fade on to all text widgets but only a few to the top of the page work. They do seem to all work on iPhone and iPad. They do not work on desktop on Safari 13.0.5, Chrome 81.0.4044.113 and Firefox 72.0.1 (MacOS Catalina). I believe this is true for all the motion effects, although the only other one I have tried is blur. Other people have commented on this bug before, including in #8529 which is a closed ticket now. Others have noted that if you resize the browser window then the effects start working again and I can confirm that that is the case here as well. I have also tried applying the fade to the section enclosing the text widgets, but again this does not work.

This is obviously a bug in calculating the scroll position of the content so the text widgets fade is not triggered at the correct place.

## Steps to reproduce

Go to the web site https://upstart.gallery. Slowly scroll down the page.

1. The paragraphs starting "A Gallery in your pocket..." and "Preview your work here..." are set to fade on and work correctly

2 All paragraphs further down the page are set to fade on but do not. These include paragraphs starting with "Featured artists...", "Drawing on...", "Experiencing digital art...", "Displays and devices..." and "We are social...".

## Isolating the problem

- [x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ x] This bug happens with a default WordPress theme active.
- [ x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
					
== Server Environment ==
	Operating System: Darwin
	Software: Apache/2.4.37 (Unix) OpenSSL/1.0.2q PHP/7.3.1 mod_perl/2.0.8-dev Perl/v5.16.3
	MySQL version: Source distribution v5.6.41-84.1
	PHP Version: 7.3.1
	PHP Max Input Vars: 1000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.4
	Site URL: http://www.dve2020.dev.cc
	Home URL: http://www.dve2020.dev.cc
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 1024M
	Permalink Structure: /%postname%
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.3.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36

== Active Plugins ==
	All-in-One WP Migration
		Version: 7.20
		Author: ServMask

	Autoptimize
		Version: 2.6.2
		Author: Frank Goossens (futtta)

	Elementor
		Version: 2.9.8
		Author: Elementor.com

	Elementor Pro
		Version: 2.9.3
		Author: Elementor.com


== Elements Usage ==
	
	footer : 1
		heading : 1
	header : 1
		icon-list : 1
		text-editor : 2
	popup : 1
		form : 1
		image : 4
		text-editor : 2
	single : 3
		theme-post-content : 1
	widget : 0
		gallery : 3
		text-editor : 18
	wp-post : 0
		text-editor : 1
		video : 1
	wp-page : 2
		gallery : 1
		html : 1
		image : 2
		spacer : 10
		text-editor : 9


== Log ==
	
PHP: showing 4 of 4PHP: 2020-04-16 14:33:19 [notice X 2840][/Volumes/Macbook Work/Projects/David van Eyssen/DVE Web site 2020/Code/Wordpress/DesktopServer v01/www.dve2020.dev.cc/wp-content/plugins/elementor-extras/admin/settings-api.php::134] Function create_function() is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-04-16 14:34:17 [notice X 17][/Volumes/Macbook Work/Projects/David van Eyssen/DVE Web site 2020/Code/Wordpress/DesktopServer v01/www.dve2020.dev.cc/wp-content/plugins/elementor-extras/modules/posts/widgets/posts.php::3963] Non-static method ElementorPro\Modules\QueryControl\Module::get_query_args() should not be called statically [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-04-19 11:17:45 [error X 1][/Volumes/Macbook Work/Projects/David van Eyssen/DVE Web site 2020/Code/Wordpress/DesktopServer v01/www.dve2020.dev.cc/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::259] Uncaught Error: Call to a member function update_meta() on null in /Volumes/Macbook Work/Projects/David van Eyssen/DVE Web site 2020/Code/Wordpress/DesktopServer v01/www.dve2020.dev.cc/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:259
Stack trace:
#0 /Volumes/Macbook Work/Projects/David van Eyssen/DVE Web site 2020/Code/Wordpress/DesktopServer v01/www.dve2020.dev.cc/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(180): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(7, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /Volumes/Macbook Work/Projects/David van Eyssen/DVE Web site 2020/Code/Wordpress/DesktopServer v01/www.dve2020.dev.cc/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modul [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-04-22 11:42:48 [error X 1][/Volumes/Macbook Work/Projects/David van Eyssen/DVE Web site 2020/Code/Wordpress/DesktopServer v01/www.dve2020.dev.cc/wp-content/plugins/elementor-pro/modules/popup/module.php::98] Uncaught Error: Call to undefined method Elementor\Core\Kits\Documents\Kit::save_display_settings_data() in /Volumes/Macbook Work/Projects/David van Eyssen/DVE Web site 2020/Code/Wordpress/DesktopServer v01/www.dve2020.dev.cc/wp-content/plugins/elementor-pro/modules/popup/module.php:98
Stack trace:
#0 [internal function]: ElementorPro\Modules\Popup\Module->save_display_settings(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#1 /Volumes/Macbook Work/Projects/David van Eyssen/DVE Web site 2020/Code/Wordpress/DesktopServer v01/www.dve2020.dev.cc/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /Volumes/Macbook Work/Projects/David van Eyssen/DVE Web site 2020/Code/Wordpress/DesktopServer v01/www.dve2020.dev.cc/wp-includes/class-wp-hook.php(287): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#3 /Volumes/Macbook Work/Projects/David van Eyssen/DVE Web site 2020/Code/Wordpress/Deskt [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 3 of 3JS: 2020-04-16 14:33:39 [error X 4][http://www.dve2020.dev.cc/wp-content/plugins/elementor-extras/assets/js/frontend.min.js?ver=1.8.1:1:398] Cannot read property \'indexOf\' of undefined 
JS: 2020-04-17 15:10:03 [error X 2][http://www.dve2020.dev.cc/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view4102\") has already been destroyed and cannot be used. 
JS: 2020-04-17 15:10:48 [error X 1][http://www.dve2020.dev.cc/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view4461\") has already been destroyed and cannot be used. 

Log: showing 2 of 22020-04-21 16:37:32 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.7',
  'to' => '2.9.8',
)]
2020-04-21 16:38:20 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.9.2',
  'to' => '2.9.3',
)]


				
```
</details>

**Comment by icecandy** [comment]
I asked about response to bugs to Ben Pines during the recent London online meetup and he said response was usually quite quick. This is 13 days now without a response. Can someone look at this please?

**Comment by dvilloz** [comment]
Having the same issues...

**Comment by lior-sh** [comment]
Hi @icecandy,

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* **Clear steps to replicate.**
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.

**Comment by icecandy** [comment]
I'm not sure what you are missing because all this information is in the first comment. I followed the required template. There is system info. There are perfectly clear steps to replicate and demonstrate the problem. There is a full system info readout. There is only one issue described in this thread. Please read more carefully. What else do you require?

**Comment by icecandy** [comment]
This bug post is now 23 days old. I have had the same experience before logging bugs with Elementor with extremely long feedback times. This does not help your customers develop professional and reliable web sites.

**Comment by matthew16678** [comment]
Hi, just reading through the thread hoping to find the solution but we don’t seem to have one yet, I’m experiencing the exact same problems as mentioned by others, the motion effect triggers are way off on the first visit, it takes a refresh or a window resize to fix the issues, this isn’t good as when clients visit for the first time they are treated with a poorly looking website

**Comment by icecandy** [comment]
@matthew16678 how can we get Elementor to treat this seriously? I don't know how to escalate things.

**Comment by matthew16678** [comment]
I've been troubleshooting this for the past few hours, without going overboard on my steps, the only thing i can point it to is that when the page is loading, the section is oversized when the viewport triggers are set, when the page has fully loaded the elementor-widget-wrap is set to the correct size which is smaler but it causes the triggers to be off, if you see the attachment it may explain it better, does anyone know how to stop elementor loading this section at 750px, because the section contains no images over 400px 
![support](https://user-images.githubusercontent.com/65932781/83201141-c85eff00-a13c-11ea-85c7-6a7546716d46.png)

**Comment by matthew16678** [comment]
I've managed to solve the issue on my site, i cant comment on if it will help out on your sites however, but i'd like to share my progress, it all came down to the image size setting, mine was set to full, so when the page loads for the first time it appears to assume the image is square with a 1:1 ratio,
i had an image which was 750px by 300px, but when loading the page assumed it would be 750x750 which caused the widget-wrap to be extended larger than needed and then offsetting the motion effect triggers, i used the custom image size option and set it exactly to the height and width i needed which fixes all problems, 
I can't say that this will fix everyones issues but it worked for me. if you do try it let me know how you get on,
![image](https://user-images.githubusercontent.com/65932781/83330935-7deb9880-a28a-11ea-924e-0e9bd5bc86a7.png)

**Comment by icecandy** [comment]
I have discovered a very important thing. It is the Elementor Gallery that breaks the motion effects. Everything below the gallery does not work. If I remove the gallery, all the text sections work and fade on as they should do. I tried your tip of assigning a custom size to the gallery images but it made no difference. I tried a few other things changing the settings of the gallery but still it is broken. Not sure what else to try.

**Comment by matthew16678** [comment]
That’s a brilliant find! 
Just a thought off the top of my head, what happens if you use a gallery from ultimate Elementor addons (UEA) or premium addons for Elementor (PA) I know it’s not ideal going for another plugin to use their gallery widget but if it gets it up and running for now it might be worth it, I have pro versions of both but I think both of them offer this gallery widget in the free version

**Comment by icecandy** [comment]
The Premium Addons Media Grid does seem to work in that it does not break the motion effects. I've yet to see if I can make it work as well as the Elementor Pro one.

@matthew16678 Thanks for the tip!

**Comment by sermalefico** [comment]
yes! motion effects dont work with gallery pro widget inside the page. And gallery widget makes another bugs, like the tablet breakpoints don't works. Other bug of gallery pro is the custom size images from dynamic doesn't works, and another bug of gallery widget is that have many errors and compatibility with other things like lightbox deactivation. please check gallery widget with all his options

**Comment by sermalefico** [comment]
For it to work I have to toggle effects on and off until a combination starts working. Once it works I can put the effect that I want. I think the controls are inconsistent. There is a conflict that causes everything to be deactivated and not reflected with the options you choose. It doesn't seem to update well. It's quite annoying

**Comment by sermalefico** [comment]
MOTION EFFECTS NO WORKS FINE
