### ISSUE TITLE
Dynamic Color not working in repeater fields

### ISSUE THREAD

**Issue by bdthemes** [elementor/elementor#11201]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Steps to reproduce

For produce this issue please insert slider widget and open slide 1 and set a dynamic background color from background tab. You can test with fallback color too like this way: http://prntscr.com/s3yx8y and now check the slider in frontend: http://prntscr.com/s3z6wy

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
					
== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.39 (Win64) PHP/7.2.18
	MySQL version: MySQL Community Server (GPL) v5.7.26
	PHP Version: 7.2.18
	PHP Max Input Vars: 2500
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.4
	Site URL: http://192.168.1.100/element-pack-dev
	Home URL: http://192.168.1.100/element-pack-dev
	WP Multisite: No
	Max Upload Size: 32 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Asia/Dhaka
	Debug Mode: Active

== Theme ==
	Name: Rooten Child
	Version: 1.0.0
	Author: BdThemes
	Child Theme: Yes
	Parent Theme Name: Rooten
	Parent Theme Version: 2.0.10
	Parent Theme Author: BdThemes

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36

== Active Plugins ==
	Anywhere Elementor
		Version: 1.2.1
		Author: WPVibes

	BdThemes FAQ
		Version: 1.0.1
		Author: bdthemes

	BdThemes Portfolio
		Version: 1.0.1
		Author: BdThemes

	BdThemes Showcase
		Version: 1.0.0
		Author: BdThemes

	BdThemes Testimonials
		Version: 1.0.0
		Author: BdThemes

	Elementor
		Version: 2.9.8
		Author: Elementor.com

	Elementor Pro
		Version: 2.9.3
		Author: Elementor.com

	Element Pack
		Version: 5.0.0
		Author: BdThemes

	Magic Copy
		Version: 1.0.0
		Author: BdThemes

	Meta Box
		Version: 5.2.10
		Author: MetaBox.io

	Query Monitor
		Version: 3.5.2
		Author: John Blackbourn

	Redis Object Cache
		Version: 1.5.7
		Author: Till Krüss

	Transients Manager
		Version: 1.8
		Author: Pippin Williamson

	WooCommerce
		Version: 4.0.1
		Author: Automattic


== Elements Usage ==
	
	product : 3
		bdt-custom-gallery : 1
		woocommerce-breadcrumb : 1
		woocommerce-product-add-to-cart : 1
		woocommerce-product-data-tabs : 1
		woocommerce-product-images : 1
		woocommerce-product-meta : 1
		woocommerce-product-price : 1
		woocommerce-product-rating : 1
		woocommerce-product-related : 1
		woocommerce-product-short-description : 1
		woocommerce-product-title : 2
		woocommerce-product-upsell : 1
	section : 38
		bdt-advanced-heading : 3
		bdt-advanced-icon-box : 15
		bdt-contact-form-7 : 3
		bdt-countdown : 2
		bdt-custom-carousel : 3
		bdt-flip-box : 12
		bdt-mailchimp : 3
		bdt-marker : 1
		bdt-member : 7
		bdt-offcanvas : 3
		bdt-post-block : 1
		bdt-price-list : 1
		bdt-scrollnav : 4
		bdt-search : 1
		bdt-slideshow : 1
		bdt-social-share : 1
		bdt-tabs : 2
		bdt-trailer-box : 5
		bdt-user-login : 1
		button : 6
		divider : 5
		heading : 31
		icon : 2
		icon-list : 2
		image : 1
		image-box : 15
		image-carousel : 1
		social-icons : 2
		text-editor : 17
	wp-post : 3
		bdt-advanced-button : 6
		bdt-navbar : 1
		bdt-reading-progress : 1
		bdt-table-of-content : 3
		bdt-wc-mini-cart : 1
		button : 6
		heading : 7
		image : 1
		text-editor : 22
	wp-page : 176
		alert : 32
		bdt-advanced-button : 74
		bdt-advanced-gmap : 11
		bdt-advanced-heading : 21
		bdt-advanced-icon-box : 96
		bdt-advanced-image-gallery : 33
		bdt-animated-heading : 13
		bdt-audio-player : 15
		bdt-business-hours : 9
		bdt-call-out : 16
		bdt-carousel : 14
		bdt-chart : 21
		bdt-circle-menu : 6
		bdt-comment : 2
		bdt-contact-form : 2
		bdt-contact-form-7 : 9
		bdt-cookie-consent : 1
		bdt-countdown : 16
		bdt-custom-carousel : 22
		bdt-custom-gallery : 14
		bdt-device-slider : 9
		bdt-document-viewer : 3
		bdt-dropbar : 24
		bdt-dual-button : 31
		bdt-event-carousel : 1
		bdt-event-grid : 1
		bdt-flip-box : 34
		bdt-fluent-forms : 1
		bdt-helpdesk : 3
		bdt-honeycombs : 1
		bdt-hover-box : 1
		bdt-iconnav : 4
		bdt-iframe : 12
		bdt-image-compare : 7
		bdt-image-magnifier : 6
		bdt-instagram : 8
		bdt-lottie-icon-box : 1
		bdt-mailchimp : 7
		bdt-marker : 11
		bdt-member : 27
		bdt-modal : 27
		bdt-navbar : 24
		bdt-news-ticker : 13
		bdt-offcanvas : 39
		bdt-open-street-map : 6
		bdt-panel-slider : 10
		bdt-portfolio-gallery : 1
		bdt-post-block : 7
		bdt-post-block-modern : 5
		bdt-post-card : 8
		bdt-post-gallery : 17
		bdt-post-grid : 12
		bdt-post-grid-tab : 5
		bdt-post-list : 8
		bdt-post-slider : 12
		bdt-price-list : 7
		bdt-price-table : 48
		bdt-progress-pie : 38
		bdt-protected-content : 2
		bdt-qrcode : 8
		bdt-scroll-button : 14
		bdt-scroll-image : 26
		bdt-scrollnav : 8
		bdt-search : 21
		bdt-single-post : 4
		bdt-slider : 13
		bdt-slideshow : 13
		bdt-social-share : 18
		bdt-switcher : 6
		bdt-table : 5
		bdt-tabs : 21
		bdt-testimonial-carousel : 1
		bdt-threesixty-product-viewer : 10
		bdt-thumb-gallery : 12
		bdt-timeline : 14
		bdt-toggle : 7
		bdt-trailer-box : 15
		bdt-twitter-carousel : 6
		bdt-twitter-slider : 6
		bdt-user-login : 14
		bdt-user-register : 6
		bdt-video-gallery : 12
		bdt-video-player : 2
		bdt-wc-carousel : 7
		bdt-wc-categories : 6
		bdt-wc-elements : 4
		bdt-wc-products : 9
		bdt-wc-slider : 5
		bdt-weather : 12
		button : 240
		divider : 10
		google_maps : 2
		heading : 941
		icon : 6
		icon-box : 20
		icon-list : 1
		image : 126
		image-box : 150
		image-gallery : 1
		lightbox : 10
		slides : 1
		social-icons : 7
		spacer : 1
		text-editor : 401
		video : 23
		wc-add-to-cart : 1


== Log ==
	
JS: showing 8 of 8JS: 2020-02-17 04:45:37 [error X 2][http://192.168.1.100/element-pack-dev/wp-content/plugins/elementor/assets/js/editor.js?ver=2.9.0-beta5:14561:9] Cannot read property \'then\' of undefined 
JS: 2020-02-23 12:13:18 [error X 2][http://192.168.1.100/element-pack-dev/wp-admin/post.php?post=47011&action=elementor:4:41] windown is not defined 
JS: 2020-03-16 08:37:10 [error X 6][http://192.168.1.100/element-pack-dev/wp-admin/post.php?post=46001&action=elementor:4:48] window.fluentFormApp is not a function 
JS: 2020-03-28 11:06:13 [error X 1][http://192.168.1.100/element-pack-dev/wp-content/plugins/bdthemes-element-pack/assets/js/widgets/ep-honeycombs.js?ver=4.6.1:10:24] $(...).honeycombs is not a function 
JS: 2020-04-04 05:10:25 [error X 5][http://192.168.1.100/element-pack-dev/wp-content/plugins/elementor/assets/js/editor.js?ver=2.9.7:14782:26] Blocked a frame with origin \"http://192.168.1.100\" from accessing a cross-origin frame. 
JS: 2020-04-04 12:15:48 [error X 1][http://192.168.1.100/element-pack-dev/wp-includes/js/jquery/jquery-migrate.js?ver=1.4.1:102:23] name.toLowerCase is not a function 
JS: 2020-04-07 10:08:29 [error X 1][http://192.168.1.100/element-pack-dev/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.js?ver=2.4.5:1810:9] View (cid: \"view82\") has already been destroyed and cannot be used. 
JS: 2020-04-09 12:13:30 [error X 14][http://192.168.1.100/element-pack-dev/wp-admin/post.php?post=47011&action=elementor#:6:1] Unexpected token \'<\' 

Log: showing 13 of 132020-02-17 16:12:00 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.0-beta5',
  'to' => '2.9.2',
)]
2020-02-27 17:25:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.2',
  'to' => '2.9.3',
)]
2020-03-05 04:06:36 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.3',
  'to' => '2.9.4',
)]
2020-03-08 17:25:26 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.8.2',
  'to' => '2.8.4',
)]
2020-03-12 05:25:09 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.4',
  'to' => '2.9.5',
)]
2020-03-12 05:25:30 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.8.4',
  'to' => '2.9.0-beta2',
)]
2020-03-12 19:42:11 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.5',
  'to' => '2.9.6',
)]
2020-03-16 19:04:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.9.0-beta2',
  'to' => '2.9.0-beta3',
)]
2020-03-18 16:58:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.9.0-beta3',
  'to' => '2.9.1',
)]
2020-03-27 00:05:34 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.6',
  'to' => '2.9.7',
)]
2020-04-01 16:18:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.9.1',
  'to' => '2.9.2',
)]
2020-04-20 03:30:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.9.2',
  'to' => '2.9.3',
)]
2020-04-22 16:20:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.7',
  'to' => '2.9.8',
)]

PHP: showing 20 of 21PHP: 2020-02-18 17:11:59 [error X 1][D:\wamp64\www\element-pack-dev\wp-content\plugins\elementor\includes\template-library\sources\local.php::1044] Uncaught TypeError: Argument 2 passed to Elementor\TemplateLibrary\Source_Local::on_save_post() must be an instance of WP_Post, instance of stdClass given, called in D:\wamp64\www\element-pack-dev\wp-includes\class-wp-hook.php on line 290 and defined in D:\wamp64\www\element-pack-dev\wp-content\plugins\elementor\includes\template-library\sources\local.php:1044
Stack trace:
#0 D:\wamp64\www\element-pack-dev\wp-includes\class-wp-hook.php(290): Elementor\TemplateLibrary\Source_Local->on_save_post(51556, Object(stdClass))
#1 D:\wamp64\www\element-pack-dev\wp-includes\class-wp-hook.php(312): WP_Hook->apply_filters(NULL, Array)
#2 D:\wamp64\www\element-pack-dev\wp-includes\plugin.php(478): WP_Hook->do_action(Array)
#3 D:\wamp64\www\element-pack-dev\wp-includes\post.php(4120): do_action('save_post', 51556, Object(stdClass), true)
#4 D:\wamp64\www\element-pack-dev\wp-includes\post.php(4197): wp_insert_post(Array, false)
#5 D:\wamp64\www\element-pack-dev\wp-admin\includes\post.php(1838): wp_update_post(Array)
#6 D:\wa [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-02-18 22:07:51 [notice X 86][D:\wamp64\www\element-pack-dev\wp-content\plugins\elementor\includes\managers\image.php::35] Undefined index: size [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-02-19 19:36:06 [warning X 70][D:\wamp64\www\element-pack-dev\wp-content\plugins\elementor\core\files\assets\svg\svg-handler.php::694] SimpleXMLElement::__construct(): ^ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-02-22 20:30:27 [error X 1][D:\wamp64\www\element-pack-dev\wp-content\plugins\elementor\includes\template-library\sources\local.php::1044] Uncaught TypeError: Argument 2 passed to Elementor\TemplateLibrary\Source_Local::on_save_post() must be an instance of WP_Post, instance of stdClass given, called in D:\wamp64\www\element-pack-dev\wp-includes\class-wp-hook.php on line 290 and defined in D:\wamp64\www\element-pack-dev\wp-content\plugins\elementor\includes\template-library\sources\local.php:1044
Stack trace:
#0 D:\wamp64\www\element-pack-dev\wp-includes\class-wp-hook.php(290): Elementor\TemplateLibrary\Source_Local->on_save_post(51793, Object(stdClass))
#1 D:\wamp64\www\element-pack-dev\wp-includes\class-wp-hook.php(312): WP_Hook->apply_filters(NULL, Array)
#2 D:\wamp64\www\element-pack-dev\wp-includes\plugin.php(478): WP_Hook->do_action(Array)
#3 D:\wamp64\www\element-pack-dev\wp-includes\post.php(4120): do_action('save_post', 51793, Object(stdClass), true)
#4 D:\wamp64\www\element-pack-dev\wp-includes\post.php(4197): wp_insert_post(Array, false)
#5 D:\wamp64\www\element-pack-dev\wp-admin\includes\post.php(1838): wp_update_post(Array)
#6 D:\wa [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-02-23 16:19:59 [error X 1][D:\wamp64\www\element-pack-dev\wp-content\plugins\elementor\includes\template-library\sources\local.php::1044] Uncaught TypeError: Argument 2 passed to Elementor\TemplateLibrary\Source_Local::on_save_post() must be an instance of WP_Post, instance of stdClass given, called in D:\wamp64\www\element-pack-dev\wp-includes\class-wp-hook.php on line 290 and defined in D:\wamp64\www\element-pack-dev\wp-content\plugins\elementor\includes\template-library\sources\local.php:1044
Stack trace:
#0 D:\wamp64\www\element-pack-dev\wp-includes\class-wp-hook.php(290): Elementor\TemplateLibrary\Source_Local->on_save_post(51853, Object(stdClass))
#1 D:\wamp64\www\element-pack-dev\wp-includes\class-wp-hook.php(312): WP_Hook->apply_filters(NULL, Array)
#2 D:\wamp64\www\element-pack-dev\wp-includes\plugin.php(478): WP_Hook->do_action(Array)
#3 D:\wamp64\www\element-pack-dev\wp-includes\post.php(4120): do_action('save_post', 51853, Object(stdClass), true)
#4 D:\wamp64\www\element-pack-dev\wp-includes\post.php(4197): wp_insert_post(Array, false)
#5 D:\wamp64\www\element-pack-dev\wp-admin\includes\post.php(1838): wp_update_post(Array)
#6 D:\wa [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-02-23 16:55:38 [error X 1][D:\wamp64\www\element-pack-dev\wp-content\plugins\elementor\includes\template-library\sources\local.php::1044] Uncaught TypeError: Argument 2 passed to Elementor\TemplateLibrary\Source_Local::on_save_post() must be an instance of WP_Post, instance of stdClass given, called in D:\wamp64\www\element-pack-dev\wp-includes\class-wp-hook.php on line 290 and defined in D:\wamp64\www\element-pack-dev\wp-content\plugins\elementor\includes\template-library\sources\local.php:1044
Stack trace:
#0 D:\wamp64\www\element-pack-dev\wp-includes\class-wp-hook.php(290): Elementor\TemplateLibrary\Source_Local->on_save_post(51863, Object(stdClass))
#1 D:\wamp64\www\element-pack-dev\wp-includes\class-wp-hook.php(312): WP_Hook->apply_filters(NULL, Array)
#2 D:\wamp64\www\element-pack-dev\wp-includes\plugin.php(478): WP_Hook->do_action(Array)
#3 D:\wamp64\www\element-pack-dev\wp-includes\post.php(4120): do_action('save_post', 51863, Object(stdClass), true)
#4 D:\wamp64\www\element-pack-dev\wp-includes\post.php(4197): wp_insert_post(Array, false)
#5 D:\wamp64\www\element-pack-dev\wp-admin\includes\post.php(1838): wp_update_post(Array)
#6 D:\wa [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-02-23 19:34:19 [error X 1][D:\wamp64\www\element-pack-dev\wp-content\plugins\elementor\includes\template-library\sources\local.php::1044] Uncaught TypeError: Argument 2 passed to Elementor\TemplateLibrary\Source_Local::on_save_post() must be an instance of WP_Post, instance of stdClass given, called in D:\wamp64\www\element-pack-dev\wp-includes\class-wp-hook.php on line 290 and defined in D:\wamp64\www\element-pack-dev\wp-content\plugins\elementor\includes\template-library\sources\local.php:1044
Stack trace:
#0 D:\wamp64\www\element-pack-dev\wp-includes\class-wp-hook.php(290): Elementor\TemplateLibrary\Source_Local->on_save_post(51887, Object(stdClass))
#1 D:\wamp64\www\element-pack-dev\wp-includes\class-wp-hook.php(312): WP_Hook->apply_filters(NULL, Array)
#2 D:\wamp64\www\element-pack-dev\wp-includes\plugin.php(478): WP_Hook->do_action(Array)
#3 D:\wamp64\www\element-pack-dev\wp-includes\post.php(4120): do_action('save_post', 51887, Object(stdClass), true)
#4 D:\wamp64\www\element-pack-dev\wp-includes\post.php(4197): wp_insert_post(Array, false)
#5 D:\wamp64\www\element-pack-dev\wp-admin\includes\post.php(1838): wp_update_post(Array)
#6 D:\wa [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-02-23 20:15:00 [error X 1][D:\wamp64\www\element-pack-dev\wp-content\plugins\elementor\includes\template-library\sources\local.php::1044] Uncaught TypeError: Argument 2 passed to Elementor\TemplateLibrary\Source_Local::on_save_post() must be an instance of WP_Post, null given, called in D:\wamp64\www\element-pack-dev\wp-includes\class-wp-hook.php on line 290 and defined in D:\wamp64\www\element-pack-dev\wp-content\plugins\elementor\includes\template-library\sources\local.php:1044
Stack trace:
#0 D:\wamp64\www\element-pack-dev\wp-includes\class-wp-hook.php(290): Elementor\TemplateLibrary\Source_Local->on_save_post(51902, NULL)
#1 D:\wamp64\www\element-pack-dev\wp-includes\class-wp-hook.php(312): WP_Hook->apply_filters(NULL, Array)
#2 D:\wamp64\www\element-pack-dev\wp-includes\plugin.php(478): WP_Hook->do_action(Array)
#3 D:\wamp64\www\element-pack-dev\wp-includes\post.php(4120): do_action('save_post', 51902, NULL, true)
#4 D:\wamp64\www\element-pack-dev\wp-includes\post.php(4197): wp_insert_post(Array, false)
#5 D:\wamp64\www\element-pack-dev\wp-content\plugins\elementor\includes\db.php(331): wp_update_post(Array)
#6 D:\wamp64\www\element-pack-d [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-02-23 20:55:08 [warning X 60][D:\wamp64\www\element-pack-dev\wp-content\plugins\elementor\core\files\assets\svg\svg-handler.php::694] SimpleXMLElement::__construct(): 		                                                                             ^ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-02-23 21:54:29 [notice X 2][D:\wamp64\www\element-pack-dev\wp-content\plugins\elementor\includes\conditions.php::87] Undefined index: navigation [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-03-01 13:47:22 [notice X 2][D:\wamp64\www\element-pack-dev\wp-content\plugins\elementor\includes\api.php::160] Undefined index: pro_widgets [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-03-10 17:04:05 [error X 1][D:\wamp64\www\element-pack-dev\wp-content\plugins\elementor\includes\template-library\sources\local.php::1044] Uncaught TypeError: Argument 2 passed to Elementor\TemplateLibrary\Source_Local::on_save_post() must be an instance of WP_Post, null given, called in D:\wamp64\www\element-pack-dev\wp-includes\class-wp-hook.php on line 290 and defined in D:\wamp64\www\element-pack-dev\wp-content\plugins\elementor\includes\template-library\sources\local.php:1044
Stack trace:
#0 D:\wamp64\www\element-pack-dev\wp-includes\class-wp-hook.php(290): Elementor\TemplateLibrary\Source_Local->on_save_post(52126, NULL)
#1 D:\wamp64\www\element-pack-dev\wp-includes\class-wp-hook.php(312): WP_Hook->apply_filters(NULL, Array)
#2 D:\wamp64\www\element-pack-dev\wp-includes\plugin.php(478): WP_Hook->do_action(Array)
#3 D:\wamp64\www\element-pack-dev\wp-includes\post.php(4120): do_action('save_post', 52126, NULL, true)
#4 D:\wamp64\www\element-pack-dev\wp-includes\post.php(4197): wp_insert_post(Array, false)
#5 D:\wamp64\www\element-pack-dev\wp-content\plugins\elementor\includes\db.php(331): wp_update_post(Array)
#6 D:\wamp64\www\element-pack-d [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-03-16 18:37:07 [error X 29][D:\wamp64\www\element-pack-dev\wp-content\plugins\elementor\core\base\base-object.php::99] Maximum execution time of 120 seconds exceeded [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-03-29 02:39:47 [notice X 5][D:\wamp64\www\element-pack-dev\wp-content\plugins\elementor\core\files\css\base.php::338] Array to string conversion [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-04-04 16:40:15 [notice X 3][D:\wamp64\www\element-pack-dev\wp-content\plugins\elementor\includes\base\controls-stack.php::1525] Undefined index: tabs_wrapper [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-04-04 22:13:36 [error X 1][D:\wamp64\www\element-pack-dev\wp-content\plugins\elementor\includes\template-library\sources\local.php::1044] Uncaught TypeError: Argument 2 passed to Elementor\TemplateLibrary\Source_Local::on_save_post() must be an instance of WP_Post, instance of stdClass given, called in D:\wamp64\www\element-pack-dev\wp-includes\class-wp-hook.php on line 289 and defined in D:\wamp64\www\element-pack-dev\wp-content\plugins\elementor\includes\template-library\sources\local.php:1044
Stack trace:
#0 D:\wamp64\www\element-pack-dev\wp-includes\class-wp-hook.php(289): Elementor\TemplateLibrary\Source_Local->on_save_post(52700, Object(stdClass))
#1 D:\wamp64\www\element-pack-dev\wp-includes\class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#2 D:\wamp64\www\element-pack-dev\wp-includes\plugin.php(478): WP_Hook->do_action(Array)
#3 D:\wamp64\www\element-pack-dev\wp-includes\post.php(4144): do_action('save_post', 52700, Object(stdClass), true)
#4 D:\wamp64\www\element-pack-dev\wp-includes\post.php(4235): wp_insert_post(Array, false)
#5 D:\wamp64\www\element-pack-dev\wp-admin\includes\post.php(1852): wp_update_post(Array)
#6 D:\wa [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-04-06 20:54:13 [notice X 1][D:\wamp64\www\element-pack-dev\wp-content\plugins\elementor\includes\controls\base-multiple.php::87] Undefined index: wrapper [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-04-06 20:55:04 [notice X 4][D:\wamp64\www\element-pack-dev\wp-content\plugins\elementor\includes\controls\base-multiple.php::87] Undefined index: value [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-04-07 15:03:44 [notice X 2][D:\wamp64\www\element-pack-dev\wp-content\plugins\elementor\includes\controls\groups\image-size.php::107] Undefined index: id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-04-09 20:22:54 [error X 1][D:\wamp64\www\element-pack-dev\wp-content\plugins\elementor\includes\template-library\sources\local.php::1044] Uncaught TypeError: Argument 2 passed to Elementor\TemplateLibrary\Source_Local::on_save_post() must be an instance of WP_Post, instance of stdClass given, called in D:\wamp64\www\element-pack-dev\wp-includes\class-wp-hook.php on line 289 and defined in D:\wamp64\www\element-pack-dev\wp-content\plugins\elementor\includes\template-library\sources\local.php:1044
Stack trace:
#0 D:\wamp64\www\element-pack-dev\wp-includes\class-wp-hook.php(289): Elementor\TemplateLibrary\Source_Local->on_save_post(53223, Object(stdClass))
#1 D:\wamp64\www\element-pack-dev\wp-includes\class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#2 D:\wamp64\www\element-pack-dev\wp-includes\plugin.php(478): WP_Hook->do_action(Array)
#3 D:\wamp64\www\element-pack-dev\wp-includes\post.php(4144): do_action('save_post', 53223, Object(stdClass), true)
#4 D:\wamp64\www\element-pack-dev\wp-includes\post.php(4235): wp_insert_post(Array, false)
#5 D:\wamp64\www\element-pack-dev\wp-admin\includes\post.php(1852): wp_update_post(Array)
#6 D:\wa [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]


				
```
</details>

**Comment by lior-sh** [comment]
Hi @bdthemes,

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.

**Comment by bdthemes** [comment]
Hello @lior-sh, I already did that as per required. But did you try to Steps to reproduce? It's not so much complex to reproduce this issue. please follow that, I hope you understand it easily.

**Comment by SaraKaterji** [comment]
was this issue solved? I am having the same issue. 
In my repeater I have a title, icon and a color. The color only updates if the title is updated. The color does not update on it's own when I change it.
