### ISSUE TITLE
Having two time input fields in a popup crashes/closes the popup when clicking one of them.

### ISSUE THREAD

**Issue by WouS95** [elementor/elementor#11310]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

When adding a form in a popup with two time input fields and click one of them on the live page the popup closes/crashes.

Example page:
https://robaard-agency.klanten.spaandesign.nl/artiesten/featherweights/

Click the buton called: "Featherweights boeken" and then click "begin showtijd" or "eind showtijd", both are time fields. Next you will notice the popup closes and the time picker stays visible, except it is now in an other place.

## Steps to reproduce
**Step 1:**
Create popup with elementor form inside

**Step 2:**
Add fields, including **two** input fields with type set to 'time' where the native html option is turned off.

**Step 3:** 
save the popup and open the page with the popup. Open the popup

**Step 4:** 
Click one of the time fields to set a time. The popup now closes/crashes as soon as the field is clicked.

## Isolating the problem

- [ x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ x] This bug happens with a default WordPress theme active.
- [x ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v5.7.27
	PHP Version: 7.0.33
	PHP Max Input Vars: 100000
	PHP Max Post Size: 1024M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.4.1
	Site URL: https://robaardagency.com/RA_WP
	Home URL: https://robaardagency.com
	WP Multisite: No
	Max Upload Size: 1 GB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: nl
	Timezone: 1
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.3.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: nl_NL
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 5.8.9
		Author: Elliot Condon

	Custom Post Type UI
		Version: 1.7.4
		Author: WebDevStudios

	DynamicConditions
		Version: 1.4.6
		Author: RTO GmbH

	Ele Custom Skin
		Version: 2.1.0
		Author: Dudaster.com

	Elementor
		Version: 2.9.8
		Author: Elementor.com

	Elementor Pro
		Version: 2.9.3
		Author: Elementor.com

	jQuery Updater
		Version: 3.5.1.1
		Author: Ramoonus

	Rank Math SEO
		Version: 1.0.42.3
		Author: Rank Math

	WP Mail SMTP
		Version: 2.0.0
		Author: WPForms


== Elements Usage ==
	
	archive : 3
		heading : 3
		posts : 3
	footer : 1
		button : 1
		heading : 3
		nav-menu : 2
		social-icons : 1
		text-editor : 1
	header : 1
		nav-menu : 1
		theme-site-logo : 1
	loop : 2
		button : 3
		heading : 1
		spacer : 1
		text-editor : 2
		theme-post-title : 1
	popup : 2
		form : 1
		heading : 2
	section : 1
		button : 2
		heading : 1
		text-editor : 1
	single : 5
		button : 1
		google_maps : 1
		heading : 1
		image : 1
		text-editor : 4
		theme-post-content : 3
		theme-post-title : 1
	wp-page : 3
		button : 8
		divider : 1
		form : 1
		heading : 10
		image : 3
		posts : 2
		social-icons : 1
		text-editor : 6


== Log ==
	
Log: showing 5 of 52020-03-19 16:34:47 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.8.2',
  'to' => '2.9.1',
)]
2020-03-25 15:30:57 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.6',
  'to' => '2.9.7',
)]
2020-03-30 10:02:04 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.9.1',
  'to' => '2.9.2',
)]
2020-04-20 16:02:11 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.9.2',
  'to' => '2.9.3',
)]
2020-04-21 19:56:51 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.7',
  'to' => '2.9.8',
)]

PHP: showing 7 of 7PHP: 2020-03-19 20:02:30 [error X 1][/home/robaar1q/public_html/RA_WP/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::259] Uncaught Error: Call to a member function update_meta() on boolean in /home/robaar1q/public_html/RA_WP/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:259
Stack trace:
#0 /home/robaar1q/public_html/RA_WP/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(180): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/robaar1q/public_html/RA_WP/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/robaar1q/public_html/RA_WP/wp-includes/class-wp-hook.php(288): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/robaar1q/public_html/RA_WP/wp-includes/class-wp-hook.php(31 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-03-30 14:12:00 [notice X 12][/home/robaar1q/public_html/RA_WP/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php::34] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-04-05 13:31:38 [warning X 924][/home/robaar1q/public_html/RA_WP/wp-content/plugins/elementor/includes/base/controls-stack.php::1201] Illegal string offset 'url' [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-04-05 14:20:13 [notice X 4][/home/robaar1q/public_html/RA_WP/wp-content/plugins/elementor/includes/template-library/sources/local.php::692] ob_end_clean(): failed to delete buffer. No buffer to delete [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-04-07 15:33:47 [notice X 1][/home/robaar1q/public_html/RA_WP/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-04-10 16:38:42 [error X 1][/home/robaar1q/public_html/RA_WP/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::259] Uncaught Error: Call to a member function update_meta() on boolean in /home/robaar1q/public_html/RA_WP/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:259
Stack trace:
#0 /home/robaar1q/public_html/RA_WP/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(180): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/robaar1q/public_html/RA_WP/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/robaar1q/public_html/RA_WP/wp-includes/class-wp-hook.php(287): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/robaar1q/public_html/RA_WP/wp-includes/class-wp-hook.php(31 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-04-20 12:57:33 [warning X 1][/home/robaar1q/public_html/RA_WP/wp-content/plugins/elementor/includes/base/controls-stack.php::1201] Cannot assign an empty string to a string offset [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 9 of 9JS: 2020-04-01 12:32:53 [error X 2][https://robaardagency.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view94\") has already been destroyed and cannot be used. 
JS: 2020-04-01 12:44:30 [error X 5][https://robaardagency.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view100\") has already been destroyed and cannot be used. 
JS: 2020-04-01 12:56:38 [error X 1][https://robaardagency.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view1096\") has already been destroyed and cannot be used. 
JS: 2020-04-05 11:16:44 [error X 1][https://robaardagency.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view5799\") has already been destroyed and cannot be used. 
JS: 2020-04-10 15:04:04 [error X 4][https://robaardagency.com/wp-content/plugins/elementor/assets/lib/e-select2/js/e-select2.full.min.js?ver=4.0.6-rc.1:1:74235] Cannot read property \'destroy\' of undefined 
JS: 2020-04-10 18:06:27 [error X 5][https://robaardagency.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view80\") has already been destroyed and cannot be used. 
JS: 2020-04-21 13:22:14 [error X 1][https://robaardagency.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view110\") has already been destroyed and cannot be used. 
JS: 2020-04-21 13:37:18 [error X 2][https://robaardagency.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view178\") has already been destroyed and cannot be used. 
JS: 2020-04-26 13:13:47 [error X 1][https://robaardagency.com/wp-content/plugins/elementor/assets/js/common.min.js?ver=2.9.8:2:106915] Routes: `theme-builder-publish/triggers` is already registered. 


				
```
</details>

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account.
