### ISSUE TITLE
Offset feature missing from Post widget

### ISSUE THREAD

**Issue by walgarch** [elementor/elementor#11919]
## Prerequisites

- [ x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x ] The issue still exists against the latest stable version of Elementor.

## Description

The offset feature is missing on the Post widgets.

![image](https://user-images.githubusercontent.com/32451330/88121860-58d03200-cc0a-11ea-9f4d-8193249c7146.png)

## Steps to reproduce

Post widget new and existing post widgets have this consistently.

## Isolating the problem

- [ x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ x ] This bug happens with a default WordPress theme active.
- [ x ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.6.41
	PHP Version: 7.4.6
	PHP Max Input Vars: 10000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.4.2
	Site URL: https://xxxxxxxxx.com
	Home URL: http://xxxxxxxxx.com
	WP Multisite: No
	Max Upload Size: 50 MB
	Memory limit: 512M
	Permalink Structure: /%category%/%year%/%monthnum%/%postname%/
	Language: en-US
	Timezone: 10
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Twenty
	Version: 1.4
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0

== Active Plugins ==
	Elementor
		Version: 2.9.14
		Author: Elementor.com

	Elementor Pro
		Version: 2.10.3
		Author: Elementor.com


== Must-Use Plugins ==
	Force Strong Passwords - WPE Edition
		Version: 1.6.4
		Author: Jason Cosper

	WP Engine Seamless Login Plugin
		Version: 1.5.5
		Author: WP Engine

	WP Engine Security Auditor
		Version: 1.0.9
		Author: wpengine

	WP Engine System
		Version: 4.0.0
		Author: WP Engine


== Elements Usage ==
	
	footer : 2
		divider : 1
		icon : 2
		nav-menu : 2
		social-icons : 1
		text-editor : 3
	header : 2
		heading : 3
		html : 1
		image : 2
		nav-menu : 2
	page : 4
		button : 1
		divider : 2
		heading : 11
		html : 3
		share-buttons : 2
		spacer : 1
		text-editor : 6
	wp-post : 2
		button : 1
		divider : 3
		heading : 15
		html : 4
		share-buttons : 3
		spacer : 1
		text-editor : 7
	wp-page : 1
		posts : 3


== Log ==
	
PHP: showing 2 of 2PHP: 2020-07-17 02:49:20 [notice X 5][/nas/content/live/xxxxxxxxx/wp-content/plugins/elementor/includes/managers/image.php::88] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-07-20 06:14:48 [error X 1][/nas/content/live/xxxxxxxxx/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::259] Uncaught Error: Call to a member function update_meta() on null in /nas/content/live/xxxxxxxxx/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:259
Stack trace:
#0 /nas/content/live/xxxxxxxxx/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(180): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(2332, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /nas/content/live/xxxxxxxxx/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /nas/content/live/xxxxxxxxx/wp-includes/class-wp-hook.php(287): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /nas/content/live/xxxxxxxxx/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 1 of 12020-07-22 10:57:00 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.13',
  'to' => '2.9.14',
)]


				
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by walgarch** [comment]
Found the issue and a workaround
![image](https://user-images.githubusercontent.com/32451330/88122768-c41b0380-cc0c-11ea-975f-e5fb19f12205.png)
Just needed to edit the CSS for the Elementor WYSIWYG editor to make those extra options appear.

**Comment by kalimah-apps** [comment]
The option is hidden under exclude item. If you select exclude you can set the offset. The options will stay set even if changed selection to include.

![image](https://user-images.githubusercontent.com/1753883/130710684-113c2ff8-2986-4198-8bc6-a7b083dfad0c.png)
