### ISSUE TITLE
Section - Background Image Positioning Issue?

### ISSUE THREAD

**Issue by ocbroadband** [elementor/elementor#12147]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

Page template is used with 2 columns.  A section is placed in the designated 'content area' within one of the columns and a image configured for the background under style.   When selecting the Attached option of 'Fixed', the image snaps to the middle of the 'template' center' and not the 'content area' center when using a 'custom' size.  The scroll and default options center the image within the 'content area' correctly.

## Steps to reproduce

1. Create a page template with 2 columns and the content area in either column and assign to a page or pages.
2. Create a page, and within the defined 'content area' provided from the assigned template, create a section.
3. Insert an image as the background, and change the Attachment to 'fixed'.
4. Set the size to 'custom' and adjust the 'position'.  The reference is based upon the template page section, and not the page 'content area' section.

The image will snap to the center of the 'template' Section, and not the section defined in the 'content' area of the page.

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release 23, Revision 500fcf5 v5.7.23-23
	PHP Version: 7.4.9
	PHP Max Input Vars: 1000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5
	Site URL: https://xxx.xxx
	Home URL: https://xxx.xxx
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/Los_Angeles
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.3.0
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.9.14
		Author: Elementor.com

	Elementor Pro
		Version: 2.10.3
		Author: Elementor.com

	Featured Image Admin Thumb
		Version: 1.5.3
		Author: Sean Hayes

	File Media Renamer
		Version: 1.1
		Author: Bradley B. Dalina

	Flexible Elementor Panel
		Version: 2.1.2
		Author: WebMat

	HappyFiles Pro
		Version: 1.2
		Author: Codeer

	Ivory Search
		Version: 4.5.5
		Author: Ivory Search

	JetBlocks For Elementor
		Version: 1.2.4
		Author: Crocoblock

	JetElements For Elementor
		Version: 2.3.2
		Author: Crocoblock

	JetEngine
		Version: 2.4.9
		Author: Crocoblock

	JetSearch For Elementor
		Version: 2.1.7
		Author: Crocoblock

	JetSmartFilters
		Version: 1.8.3
		Author: Crocoblock

	jQuery Manager for WordPress
		Version: 1.10.6
		Author: Remzi Cavdar

	Rank Math SEO
		Version: 1.0.47
		Author: Rank Math

	Shield Security
		Version: 9.1.0
		Author: Shield Security

	Which Elementor Addon
		Version: 1.1.0
		Author: obiPlabon


== Elements Usage ==
	
	archive : 2
		archive-posts : 1
		heading : 5
		image : 1
		jet-listing-dynamic-terms : 1
		jet-listing-grid : 1
		jet-smart-filters-pagination : 1
		posts : 1
		shortcode : 1
	footer : 1
		heading : 1
		spacer : 1
		text-editor : 2
		theme-site-logo : 1
	header : 1
		heading : 1
		jet-breadcrumbs : 1
		jet-nav-menu : 1
		shortcode : 1
		text-editor : 1
		theme-site-logo : 1
	page : 1
		countdown : 1
		divider : 1
		form : 1
		heading : 4
		image : 1
		spacer : 2
	popup : 1
		button : 1
		heading : 1
		text-editor : 1
	section : 3
		button : 1
		form : 1
		heading : 10
		image : 1
		posts : 1
		text-editor : 1
	single : 4
		divider : 3
		google_maps : 2
		heading : 15
		icon : 1
		icon-list : 6
		image : 2
		jet-listing-dynamic-field : 2
		jet-listing-dynamic-image : 2
		jet-listing-dynamic-link : 4
		jet-listing-dynamic-terms : 2
		jet-listing-grid : 3
		post-comments : 1
		posts : 2
		shortcode : 2
		spacer : 6
		theme-post-content : 4
	wp-post : 0
		text-editor : 1
	wp-page : 5
		button : 1
		divider : 5
		form : 3
		google_maps : 1
		heading : 11
		image : 1
		text-editor : 8
	jet-listing-items : 0
		heading : 3
		image : 1
		jet-listing-dynamic-image : 1
		jet-listing-dynamic-link : 7
		spacer : 2


== Log ==
	
PHP: showing 8 of 8PHP: 2020-06-20 17:54:47 [warning X 1][/home4/xxx/public_html/xxx/wp-content/plugins/elementor-pro/modules/forms/actions/mailerlite.php::235] Invalid argument supplied for foreach() [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-06-23 18:58:07 [warning X 4][/home4/xxx/public_html/xxx/wp-content/plugins/elementor/core/files/manager.php::121] unlink(/home4/xxx/public_html/xxx/wp-content/uploads/elementor/css/min): Is a directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-06-29 12:16:30 [notice X 2][/home4/xxx/public_html/xxx/wp-content/plugins/elementor/core/files/css/base.php::724] Undefined index: _id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-07-22 23:27:19 [warning X 3][/home4/xxx/public_html/xxx/wp-content/plugins/elementor/core/kits/manager.php::199] Illegal offset type [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-07-29 21:50:35 [notice X 1][/home4/xxx/public_html/xxx/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-08-01 09:36:53 [notice X 1][/home4/xxx/public_html/xxx/wp-content/plugins/elementor-pro/modules/posts/widgets/posts.php::31] Undefined index: posts_post_type [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-08-02 20:57:44 [notice X 15][/home4/xxx/public_html/xxx/wp-content/plugins/elementor/includes/base/controls-stack.php::1451] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-08-03 06:06:24 [error X 1][/home4/xxx/public_html/xxx/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::259] Uncaught Error: Call to a member function update_meta() on bool in /home4/xxx/public_html/xxx/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:259
Stack trace:
#0 /home4/xxx/public_html/xxx/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(180): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home4/xxx/public_html/xxx/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home4/xxx/public_html/xxx/wp-includes/class-wp-hook.php(287): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home4/xxx/public_html/c [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 20 of 282020-07-20 19:02:08 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Start  
2020-07-20 19:02:08 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Finished 
2020-07-20 19:02:08 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Start  
2020-07-20 19:02:08 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Finished 
2020-07-20 19:02:08 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.13',
  'to' => '3.0.0-beta1',
)]
2020-07-22 23:26:45 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.0-beta1',
  'to' => '3.0.0-beta2',
)]
2020-07-22 23:26:46 [info] elementor::elementor_updater Started 
2020-07-22 23:26:46 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Start  
2020-07-22 23:26:46 [notice] General Settings already exist. nothing to do. 
2020-07-22 23:26:46 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Finished 
2020-07-22 23:26:46 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Start  
2020-07-22 23:26:46 [notice] System colors are disabled. nothing to do. 
2020-07-22 23:26:46 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Finished 
2020-07-22 23:26:46 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Start  
2020-07-22 23:26:46 [notice] Custom colors already exist. nothing to do. 
2020-07-22 23:26:46 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Finished 
2020-07-22 23:26:46 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Start  
2020-07-22 23:26:46 [notice] System typography is disabled. nothing to do. 
2020-07-22 23:26:46 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Finished 
2020-07-22 23:26:46 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.0-beta1',
  'to' => '3.0.0-beta2',
)]

JS: showing 5 of 5JS: 2020-07-21 02:09:21 [error X 2][https://xxx/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.0.0-beta1:2:55914] Cannot read property \'global\' of undefined 
JS: 2020-07-30 04:50:34 [error X 2][https://xxx/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=2.10.3:2:44771] Cannot read property \'settings\' of undefined 
JS: 2020-08-16 18:45:54 [error X 2][https://xxx/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.9.14:31:89241] Cannot read property \'value\' of undefined 
JS: 2020-08-16 18:46:16 [error X 6][https://xxx/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:4698] Cannot read property \'match\' of undefined 
JS: 2020-08-16 18:52:11 [error X 2][https://xxx/wp-content/plugins/elementor/assets/lib/e-select2/js/e-select2.full.min.js?ver=4.0.6-rc.1:1:74235] Cannot read property \'destroy\' of undefined 
```
</details>

**Comment by arielk** [comment]
Unfortunately, we are unable to accurately recover your steps, please try sending us a link to the page so we can assist you.

In general, custom position is a tricky and advanced option and you will achieve a lot of inconsistent behaviors.

**Comment by arielk** [comment]
We are still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.
