### ISSUE TITLE
Call to Action Widget not inheriting Global Styles

### ISSUE THREAD

**Issue by simonclay** [elementor/elementor#12291]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

When dragging in a 'Call to Action' Widget it does not inherit the Global/Theme styles

## Steps to reproduce

Set some Global styles (eg heading colour, button colour), save then drag in a 'Call to Action' Widget into page. It does not inherit the style.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.7.31
	PHP Version: 7.2.32
	PHP Max Input Vars: 1000
	PHP Max Post Size: 1G
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5
	WP Multisite: No
	Max Upload Size: 1 GB
	Memory limit: 1G
	Permalink Structure: /%category%/%postname%/
	Language: en-GB
	Timezone: Europe/London
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.3.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 5.9.0
		Author: Elliot Condon

	All-in-One WP Migration
		Version: 7.26
		Author: ServMask

	All-in-One WP Migration Unlimited Extension
		Version: 2.37
		Author: ServMask

	Custom Adobe Fonts (Typekit)
		Version: 1.0.18
		Author: Brainstorm Force

	Custom Post Type UI
		Version: 1.8.0
		Author: WebDevStudios

	DynamicConditions
		Version: 1.4.6
		Author: RTO GmbH

	Ele Custom Skin
		Version: 3.0.0
		Author: Dudaster.com

	Elementor
		Version: 3.0.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.1
		Author: Elementor.com

	Give - Donation Plugin
		Version: 2.7.5
		Author: GiveWP

	Google Analytics for WordPress by MonsterInsights
		Version: 7.12.2
		Author: MonsterInsights

	InfiniteWP - Client
		Version: 1.9.4.7
		Author: Revmakx

	Lenix Elementor Leads addon
		Version: 1.8.1
		Author: Lenix

	LiteSpeed Cache
		Version: 3.4
		Author: LiteSpeed Technologies

	Redirection
		Version: 4.8
		Author: John Godley

	Safe SVG
		Version: 1.9.9
		Author: Daryll Doyle

	Smush Pro
		Version: 3.6.3
		Author: WPMU DEV

	Swift Control PRO
		Version: 1.4.7
		Author: David Vongries

	Wordfence Security
		Version: 7.4.10
		Author: Wordfence

	Yoast Duplicate Post
		Version: 3.2.5
		Author: Enrico Battocchi & Team Yoast

	Yoast SEO
		Version: 14.8.1
		Author: Team Yoast


== Must-Use Plugins ==
	InfiniteWP - Client Loader
		Version: 
		Author: Revmakx


== Elements Usage ==
	
	archive : 1
		archive-posts : 1
		heading : 3
		spacer : 1
	footer : 1
		breadcrumbs : 1
		heading : 4
		icon-list : 5
		image : 1
		text-editor : 1
	header : 1
		button : 9
		heading : 1
		icon : 4
		nav-menu : 1
		theme-site-logo : 1
	loop : 1
		button : 1
		heading : 1
		image : 1
		text-editor : 1
	page : 2
		breadcrumbs : 1
		heading : 13
		icon-list : 1
		image : 1
		menu-anchor : 1
		text-editor : 16
		toggle : 6
	section : 12
		breadcrumbs : 1
		button : 7
		heading : 20
		icon : 3
		image : 16
		text-editor : 19
	single : 1
		heading : 3
		image : 1
		spacer : 1
		text-editor : 1
		theme-post-content : 1
	wp-post : 2
		breadcrumbs : 14
		button : 4
		call-to-action : 6
		divider : 7
		flip-box : 5
		form : 1
		heading : 80
		icon-list : 9
		image : 24
		menu-anchor : 2
		shortcode : 3
		social-icons : 1
		spacer : 2
		template : 6
		text-editor : 95
		toggle : 7
		uael-image-gallery : 2
		uael-timeline : 1
	wp-page : 18
		divider : 1
		heading : 11
		image : 3
		posts : 2
		spacer : 2
		template : 7
		text-editor : 19


== Log ==
	
Log: showing 20 of 262020-08-25 16:59:08 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.14',
  'to' => '3.0.0',
)]
2020-08-25 16:59:10 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.14',
  'to' => '3.0.0',
)]
2020-08-25 17:08:30 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.10.3',
  'to' => '3.0.0',
)]
2020-08-26 17:21:24 [info] elementor::elementor_updater Started 
2020-08-26 17:21:24 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Start  
2020-08-26 17:21:24 [notice] General Settings already exist. nothing to do. 
2020-08-26 17:21:24 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Finished 
2020-08-26 17:21:25 [info] elementor::elementor_updater Started 
2020-08-26 17:21:25 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Start  
2020-08-26 17:21:25 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Finished 
2020-08-26 17:21:27 [info] elementor::elementor_updater Started 
2020-08-26 17:21:27 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Start  
2020-08-26 17:21:27 [notice] Custom colors already exist. nothing to do. 
2020-08-26 17:21:27 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Finished 
2020-08-26 17:21:28 [info] elementor::elementor_updater Started 
2020-08-26 17:21:28 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Start  
2020-08-26 17:21:28 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Finished 
2020-08-26 17:21:28 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.0',
  'to' => '3.0.1',
)]
2020-08-27 13:42:39 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.1',
  'to' => '3.0.2',
)]
2020-08-27 13:51:13 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.0',
  'to' => '3.0.1',
)]

PHP: showing 3 of 3PHP: 2020-08-25 17:08:20 [error X 1][/home2/fixedstagingco/public_html/talkback-uk.com/wp-content/plugins/elementor-pro/plugin.php::273] Uncaught Error: Class 'ElementorPro\Core\Modules_Manager' not found in /home2/fixedstagingco/public_html/talkback-uk.com/wp-content/plugins/elementor-pro/plugin.php:273
Stack trace:
#0 /home2/fixedstagingco/public_html/talkback-uk.com/wp-includes/class-wp-hook.php(287): ElementorPro\Plugin->on_elementor_init('')
#1 /home2/fixedstagingco/public_html/talkback-uk.com/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#2 /home2/fixedstagingco/public_html/talkback-uk.com/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#3 /home2/fixedstagingco/public_html/talkback-uk.com/wp-content/plugins/elementor/includes/plugin.php(523): do_action('elementor/init')
#4 /home2/fixedstagingco/public_html/talkback-uk.com/wp-includes/class-wp-hook.php(287): Elementor\Plugin->init('')
#5 /home2/fixedstagingco/public_html/talkback-uk.com/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#6 /home2/fixedstagingco/public_html/talkback-uk.com/wp-includes/plugin.php(478): WP_Hook->do_action [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-08-25 17:08:24 [error X 1][/home2/fixedstagingco/public_html/talkback-uk.com/wp-content/plugins/elementor-pro/modules/theme-builder/documents/header.php::8] Class ElementorPro\Modules\ThemeBuilder\Documents\Header contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Elementor\Controls_Stack::get_name) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-08-25 17:31:18 [notice X 14][/home2/fixedstagingco/public_html/talkback-uk.com/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 14 of 14JS: 2020-08-26 12:26:00 [error X 44][/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.1:2:469692] Cannot read property \'document\' of undefined 
JS: 2020-08-26 14:59:41 [error X 1][/wp-content/plugins/elementor/assets/js/common.min.js?ver=3.0.1:2:114956] Data commands: `` not found. 
JS: 2020-08-27 10:13:45 [error X 1][/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view5801\") has already been destroyed and cannot be used. 
JS: 2020-08-27 12:18:58 [error X 1][/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view41977\") has already been destroyed and cannot be used. 
JS: 2020-08-27 12:19:09 [error X 1][/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view42530\") has already been destroyed and cannot be used. 
JS: 2020-08-27 12:24:38 [error X 1][/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view4550\") has already been destroyed and cannot be used. 
JS: 2020-08-27 12:27:02 [error X 1][/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view4320\") has already been destroyed and cannot be used. 
JS: 2020-08-27 12:27:09 [error X 1][/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view4850\") has already been destroyed and cannot be used. 
JS: 2020-08-27 12:27:19 [error X 1][/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view5117\") has already been destroyed and cannot be used. 
JS: 2020-08-27 12:52:41 [error X 1][/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.2:2:474162] Cannot read property \'isDesignable\' of undefined 
JS: 2020-08-27 12:54:21 [error X 4][/wp-includes/js/jquery/jquery.js?ver=1.12.4-wp:2:1825] cannot call methods on resizable prior to initialization; attempted to call method \'destroy\' 
JS: 2020-08-27 13:20:55 [error X 1][/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view5546\") has already been destroyed and cannot be used. 
JS: 2020-08-27 14:28:49 [error X 1][/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view2434\") has already been destroyed and cannot be used. 
JS: 2020-08-27 14:42:58 [error X 1][/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view4989\") has already been destroyed and cannot be used. 


				
```
</details>

**Comment by shilo-ey** [comment]
Hi @simonclay 

Thanks for your feedback.

This is because this widget is not populated with default Global values, but specific ones.

You can change this by selecting different Global value.

Thanks
