### ISSUE TITLE
Tablet and mobile styles (colors) saved in editor but do not display on the front end until you manually apply them for each breakpoint. 

### ISSUE THREAD

**Issue by dlayd** [elementor/elementor#12389]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

After perfecting a desktop design when I go to view the design on mobile to see how it breaks down the colors do not apply to the text, sections, or widgets until you manually go in and reselect the color. It's worth noting the editor does save the color in the picker from desktop. This only seems to apply to blocks that have been created since applying the most recent patch.

## Steps to reproduce

1. Add a new section to a page
2. Add color or gradient to the background
3. Save it
4. View on mobile
5. Go back in and manually set the color for mobile
6. Update
7. Clear site cache
8. Refresh page on mobile device.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.26-29
	PHP Version: 7.4.8
	PHP Max Input Vars: 3000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: No
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5.1
	Site URL: https://dev.lvtdagency.com/docmacchiro
	Home URL: https://dev.lvtdagency.com/docmacchiro
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/Chicago
	Debug Mode: Inactive

== Theme ==
	Name: Neve
	Version: 2.7.7
	Author: ThemeIsle
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36

== Active Plugins ==
	Better Search Replace
		Version: 1.3.3
		Author: Delicious Brains

	Dynamic Content for Elementor
		Version: 1.9.5.4
		Author: Dynamic.ooo

	Elementor
		Version: 3.0.5
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.2
		Author: Elementor.com

	EmbedPress
		Version: 2.6.0
		Author: WPDeveloper

	EmbedPress Pro
		Version: 2.4.4
		Author: WPDeveloper

	Essential Addons for Elementor
		Version: 4.2.2
		Author: WPDeveloper

	Essential Addons for Elementor - Pro
		Version: 4.1.5
		Author: WPDeveloper

	ManageWP - Worker
		Version: 4.9.7
		Author: GoDaddy

	Neve Pro Addon
		Version: 1.2.7
		Author: ThemeIsle

	Premium Addons for Elementor
		Version: 3.21.1
		Author: Leap13

	Premium Addons PRO
		Version: 2.1.0
		Author: Leap13

	Rank Math SEO
		Version: 1.0.47.1
		Author: Rank Math

	SG Optimizer
		Version: 5.6.5
		Author: SiteGround


== Must-Use Plugins ==
	ManageWP - Worker Loader
		Version: 
		Author: GoDaddy


== Elements Usage ==
	
	archive : 1
		archive-posts : 1
		heading : 1
		sidebar : 1
	footer : 1
		button : 1
		dce-tokens : 2
		divider : 1
		eael-data-table : 1
		google_maps : 1
		heading : 1
		social-icons : 1
		text-editor : 3
		theme-site-logo : 1
	header : 1
		global : 1
		image : 1
		nav-menu : 1
		text-editor : 1
	section : 5
		countdown : 1
		divider : 1
		heading : 4
		image : 3
		spacer : 1
		text-editor : 3
	widget : 0
		button : 32
	wp-page : 3
		button : 1
		eael-adv-accordion : 1
		eael-post-grid : 1
		form : 2
		heading : 5
		icon-list : 2
		image : 1
		premium-img-gallery : 1
		text-editor : 4
	single-post : 1
		author-box : 1
		divider : 1
		facebook-comments : 1
		heading : 1
		post-info : 1
		share-buttons : 1
		theme-post-content : 1
		theme-post-excerpt : 1
		theme-post-featured-image : 1
		theme-post-title : 1
	single-page : 2
		countdown : 1
		divider : 1
		heading : 2
		social-icons : 1
		spacer : 1


== Log ==
	
Log: showing 20 of 232020-08-26 21:08:10 [info] elementor::elementor_updater Started 
2020-08-26 21:08:10 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Start  
2020-08-26 21:08:10 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Finished 
2020-08-26 21:08:10 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Start  
2020-08-26 21:08:10 [notice] System colors are disabled. nothing to do. 
2020-08-26 21:08:10 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Finished 
2020-08-26 21:08:10 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Start  
2020-08-26 21:08:10 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Finished 
2020-08-26 21:08:10 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Start  
2020-08-26 21:08:10 [notice] System typography is disabled. nothing to do. 
2020-08-26 21:08:10 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Finished 
2020-08-26 21:08:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.14',
  'to' => '3.0.2',
)]
2020-08-26 21:09:39 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.10.3',
  'to' => '3.0.1',
)]
2020-08-27 19:16:47 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.2',
  'to' => '3.0.3',
)]
2020-08-31 13:54:27 [info] elementor::elementor_updater Started 
2020-08-31 13:54:27 [info] Elementor/Upgrades - _v_3_0_5_re_move_space_between_widgets_to_kit Start  
2020-08-31 13:54:27 [info] Elementor/Upgrades - _v_3_0_5_re_move_space_between_widgets_to_kit Finished 
2020-08-31 13:54:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.3',
  'to' => '3.0.5',
)]
2020-08-31 13:54:27 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.3',
  'to' => '3.0.5',
)]
2020-08-31 13:55:26 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.1',
  'to' => '3.0.2',
)]

JS: showing 11 of 11JS: 2020-08-05 17:33:57 [error X 3][http://localhost/DrTyler/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=2.8.3:2:54590] Cannot read property \'top\' of undefined 
JS: 2020-08-05 20:37:00 [error X 4][http://localhost/DrTyler/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=2.10.3:2:44771] Cannot read property \'settings\' of undefined 
JS: 2020-08-24 00:58:43 [error X 1][https://dev.lvtdagency.com/DocMacDC/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.9.14:31:89241] Cannot read property \'value\' of undefined 
JS: 2020-08-24 00:58:46 [error X 7][https://dev.lvtdagency.com/DocMacDC/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:4698] Cannot read property \'match\' of undefined 
JS: 2020-08-26 21:12:45 [error X 26][https://dev.lvtdagency.com/DocMacDC/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=3.0.1:2:46559] Failed to execute \'observe\' on \'IntersectionObserver\': parameter 1 is not of type \'Element\'. 
JS: 2020-08-26 21:24:15 [error X 2][https://dev.lvtdagency.com/DocMacDC/wp-content/plugins/dynamic-content-for-elementor/assets/js/dce-editor-form.js?ver=1.9.5.4:93:27] Cannot read property \'models\' of undefined 
JS: 2020-08-31 21:10:29 [error X 1][https://dev.lvtdagency.com/docmacchiro/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view27528\") has already been destroyed and cannot be used. 
JS: 2020-08-31 21:10:29 [error X 1][https://dev.lvtdagency.com/docmacchiro/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view78800\") has already been destroyed and cannot be used. 
JS: 2020-09-02 12:48:15 [error X 3][https://dev.lvtdagency.com/docmacchiro/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view97\") has already been destroyed and cannot be used. 
JS: 2020-09-02 12:52:15 [error X 2][https://dev.lvtdagency.com/docmacchiro/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view92\") has already been destroyed and cannot be used. 
JS: 2020-09-02 13:31:29 [error X 1][https://dev.lvtdagency.com/docmacchiro/wp-admin/load-scripts.php?c=1&loadchunk_0=jquery-core,underscore,backbone,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,wp-api-request,shortcode,utils,wp-util,wp-backbo&loadchunk_1=ne,media-models,moxiejs,plupload,wp-plupload,jquery-ui-sortable&ver=5.5.1:2:12675] Syntax error, unrecognized expression: #elementor-control-circle(50% at 50% 50%)-c14328 

PHP: showing 8 of 8PHP: 2020-08-05 17:34:01 [notice X 84][C:\xampp\htdocs\DrTyler\wp-content\plugins\elementor\includes\base\controls-stack.php::1451] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-08-05 19:35:13 [warning X 2][C:\xampp\htdocs\DrTyler\wp-content\plugins\elementor\core\files\manager.php::121] unlink(C:\xampp\htdocs\DrTyler/wp-content/uploads/elementor/css/min): Is a directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-08-05 20:37:00 [notice X 9][C:\xampp\htdocs\DrTyler\wp-content\plugins\elementor\core\common\modules\ajax\module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-08-05 20:58:31 [notice X 2][C:\xampp\htdocs\DrTyler\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-manager.php::180] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-08-24 02:37:50 [error X 1][/home/rivasimages/public_html/dev.lvtdagency.com/DocMacDC/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::259] Uncaught Error: Call to a member function update_meta() on bool in /home/rivasimages/public_html/dev.lvtdagency.com/DocMacDC/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:259
Stack trace:
#0 /home/rivasimages/public_html/dev.lvtdagency.com/DocMacDC/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(180): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/rivasimages/public_html/dev.lvtdagency.com/DocMacDC/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/rivasimages/public_html/dev.lvtdagency.com/DocMacDC/wp-includes/class-wp-hook.php(287): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request( [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-08-26 21:08:12 [warning X 2][/home/rivasimages/public_html/dev.lvtdagency.com/DocMacDC/wp-content/plugins/elementor/core/files/manager.php::121] unlink(/home/rivasimages/public_html/dev.lvtdagency.com/DocMacDC/wp-content/uploads/elementor/css/min): Is a directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-08-27 15:23:50 [notice X 1][/home/rivasimages/public_html/dev.lvtdagency.com/DocMacDC/wp-content/plugins/elementor-pro/modules/posts/widgets/posts.php::31] Undefined index: posts_post_type [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-08-31 13:54:27 [warning X 3][/home/customer/www/dev.lvtdagency.com/public_html/docmacchiro/wp-content/plugins/elementor/core/files/manager.php::121] unlink(/home/customer/www/dev.lvtdagency.com/public_html/docmacchiro/wp-content/uploads/elementor/css/min): Is a directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
```
</details>

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.0.9

Feel free to update

Thanks!
