### ISSUE TITLE
Elementor 3.0.7 - Uncaught TypeError: Cannot read property '[object Array]' of undefined

### ISSUE THREAD

**Issue by dalmo3** [elementor/elementor#12478]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description

After upgrading to 3.0.7 my frontend completely broke and it started throwing this console error:

```
frontend-modules.min.js?ver=3.0.7:2 Uncaught TypeError: Cannot read property '[object Array]' of undefined
    at Frontend.Module.getItems (frontend-modules.min.js?ver=3.0.7:2)
    at Frontend.e.each.r.<computed> [as getItems] (frontend-modules.min.js?ver=3.0.7:2)
    at Frontend.getGeneralSettings (frontend.min.js?ver=3.0.7:2)
    at StretchedSection.getStretchContainer (frontend.min.js?ver=3.0.7:2)
    at StretchedSection.initStretch (frontend.min.js?ver=3.0.7:2)
    at StretchedSection.onInit (frontend.min.js?ver=3.0.7:2)
    at StretchedSection.Module.trigger (frontend-modules.min.js?ver=3.0.7:2)
    at StretchedSection.e.each.r.<computed> [as trigger] (frontend-modules.min.js?ver=3.0.7:2)
    at init (frontend-modules.min.js?ver=3.0.7:2)
    at StretchedSection.Module (frontend-modules.min.js?ver=3.0.7:2)
```

Fixed by rolling back to 3.0.6

## Isolating the problem

- [x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x ] This bug happens with a default WordPress theme active.
- [x ] I can reproduce this bug consistently using the steps above.

## Environment

WP 5.5
Elementor 3.0.7
Elementor pro 3.0.4
<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->

					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.3.23
	PHP Version: 7.3.20
	PHP Max Input Vars: 5000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5.1
	Site URL: https://essencedesign.co.nz
	Home URL: https://essencedesign.co.nz
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 1024M
	Permalink Structure: /%postname%/
	Language: en-NZ
	Timezone: Pacific/Auckland
	Debug Mode: Inactive

== Theme ==
	Name: Customify
	Version: 0.3.5
	Author: WPCustomify
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_NZ
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 5.9.1
		Author: Elliot Condon

	Advanced Custom Fields PRO
		Version: 5.7.9
		Author: Elliot Condon

	Auto Image Attributes From Filename With Bulk Updater
		Version: 1.6
		Author: Arun Basil Lal

	Category Tag Pages
		Version: 1.0
		Author: Marzio Carro

	Central Color Palette
		Version: 1.15.3
		Author: Daniel Menzies

	Cloudflare
		Version: 3.5.1
		Author: Cloudflare, Inc.

	Code Snippets
		Version: 2.14.0
		Author: Code Snippets Pro

	Customify Pro
		Version: 0.1.1
		Author: WPCustomify

	Elementor
		Version: 3.0.6
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.4
		Author: Elementor.com

	GA Google Analytics
		Version: 20200815
		Author: Jeff Starr

	ManageWP - Worker
		Version: 4.9.7
		Author: GoDaddy

	Media Library Assistant
		Version: 2.84
		Author: David Lingren

	Query Monitor
		Version: 3.6.4
		Author: John Blackbourn

	Rank Math SEO
		Version: 1.0.47.1
		Author: Rank Math

	Sassy Social Share
		Version: 3.3.12
		Author: Team Heateor

	Smart Slider 3
		Version: 3.4.1.9
		Author: Nextend

	Smush
		Version: 3.7.0
		Author: WPMU DEV

	WP Rocket
		Version: 3.7.0.1
		Author: WP Media

	WP Sync DB
		Version: 1.5
		Author: Sean Lang

	WP Sync DB Media Files
		Version: 1.1.4b1
		Author: Sean Lang


== Must-Use Plugins ==
	ManageWP - Worker Loader
		Version: 
		Author: GoDaddy


== Elements Usage ==
	
	section : 13
		button : 4
		heading : 8
		icon : 5
		image : 5
		spacer : 1
		testimonial : 5
		text-editor : 1
	page : 1
	wp-post : 0
		animated-headline : 1
		author-box : 4
		button : 3
		counter : 4
		heading : 11
		icon : 3
		icon-box : 8
		icon-list : 2
		image : 5
		image-box : 3
		shortcode : 2
		smartslider : 1
		spacer : 4
		testimonial : 1
		text-editor : 9
	not-supported : 0
		button : 3
		heading : 4
		icon : 4
		shortcode : 1
		spacer : 1
		testimonial : 4


== Log ==
	
Log: showing 20 of 412020-07-30 09:07:29 [info] Elementor/Upgrades - _v_2_8_3_recalc_usage_data Start  
2020-07-30 09:07:29 [info] Elementor/Upgrades - _v_2_8_3_recalc_usage_data Finished 
2020-07-30 09:07:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.8.0',
  'to' => '2.9.13',
)]
2020-07-30 09:19:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.13',
  'to' => '2.9.14',
)]
2020-09-11 10:17:47 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.14',
  'to' => '3.0.7',
)]
2020-09-11 10:18:51 [info] elementor::elementor_updater Started 
2020-09-11 10:18:51 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Start  
2020-09-11 10:18:51 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Finished 
2020-09-11 10:18:51 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Start  
2020-09-11 10:18:51 [notice] System colors are disabled. nothing to do. 
2020-09-11 10:18:52 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Finished 
2020-09-11 10:18:52 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Start  
2020-09-11 10:18:52 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Finished 
2020-09-11 10:18:52 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Start  
2020-09-11 10:18:52 [notice] System typography is disabled. nothing to do. 
2020-09-11 10:18:52 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Finished 
2020-09-11 10:18:52 [info] Elementor/Upgrades - _v_3_0_5_re_move_space_between_widgets_to_kit Start  
2020-09-11 10:18:52 [info] Elementor/Upgrades - _v_3_0_5_re_move_space_between_widgets_to_kit Finished 
2020-09-11 10:18:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.14',
  'to' => '3.0.7',
)]
2020-09-11 10:19:13 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.10.3',
  'to' => '3.0.4',
)]

JS: showing 1 of 1JS: 2020-09-10 22:30:12 [error X 5][https://essencedesign.co.nz/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.0.7:2:49182] Cannot read property \'[object Array]\' of undefined 


				
```
</details>

**Comment by shilo-ey** [comment]
Hi @dalmo3 

Thanks for sharing.

Can you please add the following code to your `wp-config.php` file and let us know what is the console errors which appears in your console?

```PHP
define( 'SCRIPT_DEBUG', true );
define( 'CONCATENATE_SCRIPTS', false );
```

Thanks

**Comment by Vkar90** [comment]
Hello, I'm facing a similar if not the same issue. Frontend completely broke, with a console error:

frontend-modules.min.js?ver=2.7.5:2 Uncaught TypeError: Cannot read property '[object Array]' of undefined
    at Frontend.Module.getItems (frontend-modules.min.js?ver=2.7.5:2)
    at Frontend.e.each.r.<computed> [as getItems] (frontend-modules.min.js?ver=2.7.5:2)
    at Frontend.getKitSettings (frontend.min.js?ver=2.7.5:2)
    at StretchedSection.getStretchContainer (frontend.min.js?ver=2.7.5:2)
    at StretchedSection.initStretch (frontend.min.js?ver=2.7.5:2)
    at StretchedSection.onInit (frontend.min.js?ver=2.7.5:2)
    at StretchedSection.Module.trigger (frontend-modules.min.js?ver=2.7.5:2)
    at StretchedSection.e.each.r.<computed> [as trigger] (frontend-modules.min.js?ver=2.7.5:2)
    at init (frontend-modules.min.js?ver=2.7.5:2)
    at StretchedSection.Module (frontend-modules.min.js?ver=2.7.5:2)

**Comment by rosnermd** [comment]
Hi,

Also experiencing this issue as well using the reviews widget.  Only the first review shows up (set to show 3 at a time) and auto-rotating/arrows do not cycle through the rest.
`
Uncaught TypeError: Cannot read property '[object Array]' of undefined
    at Frontend.Module.getItems (37e18.js:56)
    at Frontend.e.each.r.<computed> [as getItems] (37e18.js:56)
    at Frontend.getGeneralSettings (9f110.js:2)
    at StretchedSection.getStretchContainer (9f110.js:2)
    at StretchedSection.initStretch (9f110.js:2)
    at StretchedSection.onInit (9f110.js:2)
    at StretchedSection.Module.trigger (37e18.js:56)
    at StretchedSection.e.each.r.<computed> [as trigger] (37e18.js:56)
    at init (37e18.js:56)
    at StretchedSection.Module (37e18.js:56)
`

**Comment by rominsol** [comment]
I also have the same problem:

Uncaught TypeError: Cannot read property '[object Array]' of undefined
    at Frontend.Module.getItems (frontend-modules.min.js?ver=2.9.2:2)
    at Frontend.e.each.r.<computed> [as getItems] (frontend-modules.min.js?ver=2.9.2:2)
    at Frontend.getKitSettings (frontend.min.js?ver=2.9.2:2)
    at StretchedSection.getStretchContainer (frontend.min.js?ver=2.9.2:2)
    at StretchedSection.initStretch (frontend.min.js?ver=2.9.2:2)
    at StretchedSection.onInit (frontend.min.js?ver=2.9.2:2)
    at StretchedSection.Module.trigger (frontend-modules.min.js?ver=2.9.2:2)
    at StretchedSection.e.each.r.<computed> [as trigger] (frontend-modules.min.js?ver=2.9.2:2)
    at init (frontend-modules.min.js?ver=2.9.2:2)
    at StretchedSection.Module (frontend-modules.min.js?ver=2.9.2:2)

I have last version of WordPress , elementor v3.0.10 and Elementor Pro v. 3.0.5

**Comment by rominsol** [comment]
I included the commands: 

define( 'SCRIPT_DEBUG', true );
define( 'CONCATENATE_SCRIPTS', false );

This is what I got:


  | Module.getItems | @ | frontend-modules.min.js?ver=2.9.2:2
-- | -- | -- | --
  | e.each.r.<computed> | @ | frontend-modules.min.js?ver=2.9.2:2
  | getKitSettings | @ | frontend.min.js?ver=2.9.2:2
  | getStretchContainer | @ | frontend.min.js?ver=2.9.2:2
  | initStretch | @ | frontend.min.js?ver=2.9.2:2
  | onInit | @ | frontend.min.js?ver=2.9.2:2
  | Module.trigger | @ | frontend-modules.min.js?ver=2.9.2:2
  | e.each.r.<computed> | @ | frontend-modules.min.js?ver=2.9.2:2
  | init | @ | frontend-modules.min.js?ver=2.9.2:2
  | Module | @ | frontend-modules.min.js?ver=2.9.2:2
  | child | @ | frontend-modules.min.js?ver=2.9.2:2
  | child | @ | frontend-modules.min.js?ver=2.9.2:2
  | _createSuperInternal | @ | frontend.min.js?ver=2.9.2:2
  | StretchedSection | @ | frontend.min.js?ver=2.9.2:2
  | addHandler | @ | frontend.min.js?ver=2.9.2:2
  | _default | @ | frontend.min.js?ver=2.9.2:2
  | _runHook | @ | frontend.min.js?ver=2.9.2:2
  | doAction | @ | frontend.min.js?ver=2.9.2:2
  | runReadyTrigger | @ | frontend.min.js?ver=2.9.2:2
  | (anonymous) | @ | frontend.min.js?ver=2.9.2:2
  | each | @ | jquery.js?ver=1.12.4-wp:2
  | each | @ | jquery.js?ver=1.12.4-wp:2
  | runElementsHandlers | @ | frontend.min.js?ver=2.9.2:2
  | onInit | @ | frontend.min.js?ver=2.9.2:2
  | Module.trigger | @ | frontend-modules.min.js?ver=2.9.2:2
  | e.each.r.<computed> | @ | frontend-modules.min.js?ver=2.9.2:2
  | init | @ | frontend-modules.min.js?ver=2.9.2:2
  | Module | @ | frontend-modules.min.js?ver=2.9.2:2
  | child | @ | frontend-modules.min.js?ver=2.9.2:2
  | _createSuperInternal | @ | frontend.min.js?ver=2.9.2:2
  | _default | @ | frontend.min.js?ver=2.9.2:2
  | attachDocumentClass | @ | frontend.min.js?ver=2.9.2:2
  | (anonymous) | @ | frontend.min.js?ver=2.9.2:2
  | each | @ | jquery.js?ver=1.12.4-wp:2
  | each | @ | jquery.js?ver=1.12.4-wp:2
  | attachDocumentsClasses | @ | frontend.min.js?ver=2.9.2:2
  | _default | @ | frontend.min.js?ver=2.9.2:2
  | onDocumentLoaded | @ | frontend.min.js?ver=2.9.2:2
  | initOnReadyComponents | @ | frontend.min.js?ver=2.9.2:2
  | init | @ | frontend.min.js?ver=2.9.2:2
  | (anonymous) | @ | frontend.min.js?ver=2.9.2:2
  | i | @ | jquery.js?ver=1.12.4-wp:2
  | fireWith | @ | jquery.js?ver=1.12.4-wp:2
  | ready | @ | jquery.js?ver=1.12.4-wp:2
  | J | @ | jquery.js?ver=1.12.4-wp:2

**Comment by dalmo3** [comment]
Issue is gone for me with 3.0.11 and Pro 3.0.5.

**Comment by luismts** [comment]
I have 3.0.11 and Pro 3.0.5 and facing the same issue. 

My carousel is not working because of that. Any update on this?

**Comment by luismts** [comment]
I solved the problem by deleting one of two modal popups. It's weird.

I think this can be another issue. I also think this can be related to self-managed JS.

**Comment by LadyDeathKZN** [comment]
Hi, I am getting this issue while using it in Multisites. The other sites are fine, except one. 
Elementor 3.1.3.
Migrate is installed, version 3.3.2
Running on WP Engine


The errors are as follows:

jquery.min.js:2 jQuery.Deferred exception: Cannot read property '[object Array]' of undefined TypeError: Cannot read property '[object Array]' of undefined
    at Frontend.Module.getItems (https://17yy713v5uns344y173csoha-wpengine.netdna-ssl.com/wp-content/plugins/elementor/assets/js/frontend-modules.min.js:2:49182)
    at Frontend.e.each.r.<computed> [as getItems] (https://17yy713v5uns344y173csoha-wpengine.netdna-ssl.com/wp-content/plugins/elementor/assets/js/frontend-modules.min.js:2:48914)
    at Frontend.getGeneralSettings (https://17yy713v5uns344y173csoha-wpengine.netdna-ssl.com/wp-content/plugins/elementor/assets/js/frontend.min.js:2:62892)
    at StretchedSection.getStretchContainer (https://17yy713v5uns344y173csoha-wpengine.netdna-ssl.com/wp-content/plugins/elementor/assets/js/frontend.min.js:2:94329)
    at StretchedSection.initStretch (https://17yy713v5uns344y173csoha-wpengine.netdna-ssl.com/wp-content/plugins/elementor/assets/js/frontend.min.js:2:94213)
    at StretchedSection.onInit (https://17yy713v5uns344y173csoha-wpengine.netdna-ssl.com/wp-content/plugins/elementor/assets/js/frontend.min.js:2:94564)
    at StretchedSection.Module.trigger (https://17yy713v5uns344y173csoha-wpengine.netdna-ssl.com/wp-content/plugins/elementor/assets/js/frontend-modules.min.js:2:50290)
    at StretchedSection.e.each.r.<computed> [as trigger] (https://17yy713v5uns344y173csoha-wpengine.netdna-ssl.com/wp-content/plugins/elementor/assets/js/frontend-modules.min.js:2:48914)
    at init (https://17yy713v5uns344y173csoha-wpengine.netdna-ssl.com/wp-content/plugins/elementor/assets/js/frontend-modules.min.js:2:49075)
    at StretchedSection.Module (https://17yy713v5uns344y173csoha-wpengine.netdna-ssl.com/wp-content/plugins/elementor/assets/js/frontend-modules.min.js:2:50368) undefined
S.Deferred.exceptionHook @ jquery.min.js:2


Uncaught TypeError: Cannot read property '[object Array]' of undefined
    at Frontend.Module.getItems (frontend-modules.min.js:2)
    at Frontend.e.each.r.<computed> [as getItems] (frontend-modules.min.js:2)
    at Frontend.getGeneralSettings (frontend.min.js:2)
    at StretchedSection.getStretchContainer (frontend.min.js:2)
    at StretchedSection.initStretch (frontend.min.js:2)
    at StretchedSection.onInit (frontend.min.js:2)
    at StretchedSection.Module.trigger (frontend-modules.min.js:2)
    at StretchedSection.e.each.r.<computed> [as trigger] (frontend-modules.min.js:2)
    at init (frontend-modules.min.js:2)
    at StretchedSection.Module (frontend-modules.min.js:2)


The website's stretch is no longer working and the animations.
Any feedback would be greatly appreciated

**Comment by ibrahimhajjaj** [comment]
Got the same issue!

**Comment by cgomezhumm** [comment]
Any solutions found yet?

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
