### ISSUE TITLE
[BUG] GLOBAL COLORS - Global button settings - Color disappears after certain action

### ISSUE THREAD

**Issue by MichaelDarko** [elementor/elementor#12728]
### Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I keep having problems with global color disappearing on buttons when I edit global buttons settings.

I finally figured out the exact steps to trigger the bug.

**Here is a screen recording:**

https://www.loom.com/share/7d800021a96d4ad1a874bec9384e1f01

## Steps to reproduce

My exact steps: 

(Could also be happening with other steps.)

(Buttons must by styled only with styling in site settings, no styling on individual widget.)

1. Edit header with globally styled button in it
2. Go to site settings
3. Go to global buttons setting
4. Change box shadow values
5. Save
6. Change box shadow values again
7. [BUG] Global color of buttons gets dropped

(You have to save and then immediately edit the values again and that's when it happens.)

## Isolating the problem

Only Elementor and Hello theme installed.

No error shows up in the console.

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by zocoloco** [comment]
I first posted this during the beta. [#11821,](https://github.com/elementor/elementor/issues/11821)  [ #12181](https://github.com/elementor/elementor/issues/12181) Just had it happen again. This time I lost ALL Global FONTS & COLORS. Elementor Pro 3.0.5. Paid version. Can I bill Elementor for the time I'm wasting having to enter - and reenter Global Settings? I thought this feature was supposed to save us time?

**Comment by lior-sh** [comment]
Hi @MichaelDarko,

Thanks for reporting, we couldn't reproduce the issue.
Please write the System info.
Thanks.

**Comment by perks98** [comment]
I've tried the steps in @MichaelDarko video and I get the same issue, but the styling only drops on the backend and not the front end. It seems changing the box shadow or text shadow of the buttons in the global settings then saving then changing again in the same session brings up the issue. Choosing a different colour for the button brings back the styling. (in my case I only had Astra theme, Elementor and Elementor Pro enabled)

**Comment by MichaelDarko** [comment]
Yes, it's only happening on backend. Frontend is fine. Tested on 3 different websites on different hosting providers, happening everywhere.

**Comment by MichaelDarko** [comment]
<details>
<summary>Here is the system info</summary>	

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.6.41-84.1
	PHP Version: 7.4.6
	PHP Max Input Vars: 10000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5.1
	Site URL: https://mb.mbdemo.cz
	Home URL: https://mb.mbdemo.cz
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: cs
	Timezone: Europe/Prague
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.3.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: cs_CZ
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36

== Active Plugins ==

	Elementor
		Version: 3.0.11
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.5
		Author: Elementor.com


== Must-Use Plugins ==
	installatron_hide_status_test.php
		Version: 
		Author: 


== Elements Usage ==
	
	footer : 2
		heading : 6
		menu-anchor : 1
		nav-menu : 1
	header : 1
		button : 1
		image : 2
		nav-menu : 1
	page : 14
		button : 59
		divider : 15
		heading : 608
		html : 15
		image : 168
		menu-anchor : 14
		testimonial-carousel : 12
	section : 3
		button : 1
		heading : 1
		icon-list : 1
		image : 2
		nav-menu : 1
		search-form : 1
		social-icons : 1
		testimonial-carousel : 1
	wp-page : 5
		button : 8
		divider : 6
		heading : 230
		html : 3
		image : 47
		menu-anchor : 8
		testimonial-carousel : 3
	single-post : 1
		button : 1
		heading : 1
		post-info : 1
		posts : 1
		theme-post-content : 1
		theme-post-title : 1


== Log ==
	
Log: showing 8 of 82020-09-01 16:07:45 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.8.2',
  'to' => '2.10.3',
)]
2020-09-01 16:07:54 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.10.3',
  'to' => '3.0.2',
)]
2020-09-10 07:58:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.5',
  'to' => '3.0.7',
)]
2020-09-10 07:59:18 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.2',
  'to' => '3.0.4',
)]
2020-09-18 17:51:38 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.7',
  'to' => '3.0.9',
)]
2020-09-23 20:33:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.9',
  'to' => '3.0.10',
)]
2020-09-23 20:34:17 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.4',
  'to' => '3.0.5',
)]
2020-10-01 13:33:31 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.10',
  'to' => '3.0.11',
)]

JS: showing 1 of 1JS: 2020-09-10 08:32:22 [error X 35][https://mb.mbdemo.cz/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.7:2:473653] Cannot read property \'document\' of undefined 

PHP: showing 4 of 4PHP: 2020-09-11 02:21:19 [notice X 1][/data/web/virtuals/202311/virtual/www/domains/mb.mbdemo.cz/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-09-13 13:09:13 [error X 1][/data/web/virtuals/202311/virtual/www/domains/mb.mbdemo.cz/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::281] Uncaught Error: Call to a member function update_meta() on bool in /data/web/virtuals/202311/virtual/www/domains/mb.mbdemo.cz/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:281
Stack trace:
#0 /data/web/virtuals/202311/virtual/www/domains/mb.mbdemo.cz/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(162): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /data/web/virtuals/202311/virtual/www/domains/mb.mbdemo.cz/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /data/web/virtuals/202311/virtual/www/domains/mb.mbdemo.cz/wp-includes/class-wp-hook.php(287): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_requ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-09-14 08:37:04 [notice X 14][/data/web/virtuals/202311/virtual/www/domains/mb.mbdemo.cz/wp-content/plugins/elementor/includes/template-library/sources/local.php::697] ob_end_clean(): failed to delete buffer. No buffer to delete [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-09-16 11:32:55 [notice X 3][/data/web/virtuals/202311/virtual/www/domains/mb.mbdemo.cz/wp-content/plugins/elementor/includes/managers/image.php::86] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
	
</details>

**Comment by lior-sh** [comment]
Hi @MichaelDarko,

Thanks for reporting.
We will address this issue soon and release a patch.
Please follow this thread for updates.
Thanks!

**Comment by dlayd** [comment]
Just want to add that this doesn't seem to affect buttons in custom headers made with elementor, but does affect the content within the page body itself. When both buttons (one in the header, one in the page) are present the one with the header is unaffected.

**Comment by markuswaldemar** [comment]
Any news on this issue?
I'm experiencing the same problem. Global color and fonts drops/disappears/resets. It affects both frontend and backend for me.

**Comment by zocoloco** [comment]
> Any news on this issue?
> I'm experiencing the same problem. Global color and fonts drops/disappears/resets. It affects both frontend and backend for me.

No updates that I'm aware of. I have found it only happens when I use Safari. If I use Brave (Chrome) - it doesn't happen.

**Comment by austinsparx** [comment]
I'm experiencing a similar issue here. Global colours assigned to headings, works fine. It then seems like when I edit something on the page, and save, the global colour resets and doesn't show on the front end. 

Weirdly if I click into the element, then go to colours the global colour doesn't show, then after a couple of seconds it will show up.

**Comment by MichaelDarko** [comment]
6 months and still no fix? Anytime you make multiple changes in the site setting styling or global custom css, the styling goes away and you have to reload the editor.

**Comment by paciek** [comment]
I'm also not seeing the global colors displayed. In the editor, I can see the global color, but after saving, it shows as transparent on the site. When I inspect the element, I check --e-global-color-primary and get information that the property is undefined. I've already tried clearing files and regenerating CSS, reinstalling Elementor, and trying different methods of embedding CSS.
