### ISSUE TITLE
Slider background often stops, will not continue.

### ISSUE THREAD

**Issue by Luke-SF** [elementor/elementor#12792]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

Background sliding does not work on some elements, adding more than two causes it to just show 2, never loop back with the infinite option on, possibly because they were from an Elementor 2.x?

## Steps to reproduce

Within a post's _elementor_data, set:

`[{"id":"68009e1","elType":"section","settings":{"content_width":{"size":"500","unit":"px","sizes":[]},"height":"min-height","custom_height":{"unit":"px","size":"500","sizes":[]},"background_background":"slideshow","background_slideshow_gallery":[{"id":"1225","url":"https:\/\/demo-sites.sharefaith.com\/new-test-5f7f3c3e2b562\/wp-content\/uploads\/sites\/390\/2020\/10\/116204990_3156958737714954_6001977417997151844_o.jpg"},{"id":"1226","url":"https:\/\/demo-sites.sharefaith.com\/new-test-5f7f3c3e2b562\/wp-content\/uploads\/sites\/390\/2020\/10\/116582070_3156990841045077_4319555055683129872_n.jpg"},{"id":"1227","url":"https:\/\/demo-sites.sharefaith.com\/new-test-5f7f3c3e2b562\/wp-content\/uploads\/sites\/390\/2020\/10\/120799922_3349951851748974_7736159243373248772_n.jpg"},{"id":"1228","url":"https:\/\/demo-sites.sharefaith.com\/new-test-5f7f3c3e2b562\/wp-content\/uploads\/sites\/390\/2020\/10\/120563334_3349951995082293_6267254495104694511_n.jpg"}],"background_slideshow_ken_burns":"yes","background_overlay_background":"gradient","background_overlay_color":"#324D7E","background_overlay_color_stop":{"unit":"%","size":"28","sizes":[]},"background_overlay_color_b":"#F2295B00","background_overlay_color_b_stop":{"unit":"%","size":"60","sizes":[]},"background_overlay_gradient_type":"radial","background_overlay_gradient_position":"bottom right","css_filters_css_filter":"custom","shape_divider_bottom":"mountains","shape_divider_bottom_color":"#4C5EAB","shape_divider_bottom_height":{"unit":"px","size":"57","sizes":[]},"shape_divider_bottom_above_content":"yes","ang_outer_gap":"no","background_color":"#E39191","background_color_stop":{"unit":"%","size":"11","sizes":[]},"background_color_b":"#0FC21A","background_gradient_type":"radial","background_gradient_position":"bottom right","margin":{"unit":"px","top":"","right":"0","bottom":"","left":"0","isLinked":"1"},"layout":"full_width","css_filters_blur":{"unit":"px","size":"1.1","sizes":[]},"custom_height_tablet":{"unit":"px","size":"350","sizes":[]},"custom_height_mobile":{"unit":"px","size":"200","sizes":[]}},"elements":[{"id":"97c6ff8","elType":"column","settings":{"_column_size":"100"},"elements":[],"isInner":""}],"isInner":""},{"id":"284907cc","elType":"section","settings":{"height":"min-height","layout":"full_width","margin":{"top":"","left":"0","unit":"px","right":"0","bottom":"","isLinked":"1"},"ang_outer_gap":"no","content_width":{"size":"500","unit":"px","sizes":[]},"custom_height":{"size":"500","unit":"px","sizes":[]},"background_color_b":"rgba(26, 126, 229, 0)","custom_height_mobile":{"size":"200","unit":"px","sizes":[]},"custom_height_tablet":{"size":"300","unit":"px","sizes":[]},"shape_divider_bottom":"mountains","background_background":"slideshow","background_color_stop":{"size":"52","unit":"%","sizes":[]},"background_gradient_type":"radial","background_overlay_color":"#1A7EE5","background_overlay_color_b":"rgba(26, 126, 229, 0)","background_overlay_opacity":{"size":"0.59","unit":"px","sizes":[]},"shape_divider_bottom_color":"#1A7EE5","shape_divider_bottom_height":{"size":"50","unit":"px","sizes":[]},"background_slideshow_gallery":[{"id":"1225","url":"https:\/\/demo-sites.sharefaith.com\/new-test-5f7f3c3e2b562\/wp-content\/uploads\/sites\/390\/2020\/10\/116204990_3156958737714954_6001977417997151844_o.jpg"},{"id":"1226","url":"https:\/\/demo-sites.sharefaith.com\/new-test-5f7f3c3e2b562\/wp-content\/uploads\/sites\/390\/2020\/10\/116582070_3156990841045077_4319555055683129872_n.jpg"},{"id":"1227","url":"https:\/\/demo-sites.sharefaith.com\/new-test-5f7f3c3e2b562\/wp-content\/uploads\/sites\/390\/2020\/10\/120799922_3349951851748974_7736159243373248772_n.jpg"},{"id":"1228","url":"https:\/\/demo-sites.sharefaith.com\/new-test-5f7f3c3e2b562\/wp-content\/uploads\/sites\/390\/2020\/10\/120563334_3349951995082293_6267254495104694511_n.jpg"}],"background_overlay_background":"gradient","background_overlay_color_stop":{"size":"27","unit":"%","sizes":[]},"background_slideshow_ken_burns":"yes","background_overlay_color_b_stop":{"size":"60","unit":"%","sizes":[]},"background_overlay_gradient_type":"radial","shape_divider_bottom_above_content":"yes","background_overlay_gradient_position":"bottom right","background_slideshow_transition_duration":"100","background_color":"#C81E1E"},"elements":[{"id":"5d43f02d","elType":"column","settings":{"_column_size":"100"},"elements":[{"id":"d1fb638","elType":"widget","settings":[],"elements":[],"widgetType":"spacer"}],"isInner":""}],"isInner":""}]`

or similar.

Although these are nearly identical in every way - I even changed the json so the upper section is nearly exactly like it according to http://www.jsondiff.com/ - the bottom one will still always hang on the second image.

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.46 (Unix)
	MySQL version: Source distribution v5.7.22
	PHP Version: 7.3.14
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5.1
	Site URL: https://demo-sites.sharefaith.com/new-test-5f7f3c3e2b562
	Home URL: https://demo-sites.sharefaith.com/new-test-5f7f3c3e2b562
	WP Multisite: Yes
	Max Upload Size: 64 MB
	Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.3.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:81.0) Gecko/20100101 Firefox/81.0

== Active Plugins ==
	Sharefaith Templates for Elementor
		Version: 1.4.2
		Author: Sharefaith


== Network Plugins ==
	Classic Editor
		Version: 1.6
		Author: WordPress Contributors

	Duplicate Page
		Version: 4.3
		Author: mndpsingh287

	Elementor
		Version: 3.0.11
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.5
		Author: Elementor.com

	FMS Forms Plugin
		Version: 1.1.7
		Author: Sharefaith

	Galleries by Angie Makes
		Version: 1.67
		Author: Chris Baldelomar

	Modern Events Calendar Lite
		Version: 5.12.5
		Author: Webnus

	MultiSite Clone Duplicator
		Version: 1.5.3
		Author: Julien OGER, Pierre DARGHAM, David DAUGREILH, GLOBALIS media systems

	Prayer Cloud
		Version: 1.1.2
		Author: Sharefaith

	RefTagger
		Version: 2.4.1
		Author: Logos Bible Software

	Sermon Cloud
		Version: 1.4.0
		Author: Sharefaith

	Sharefaith Demo Signup
		Version: 1.3.7
		Author: Sharefaith

	Sharefaith Media Library Plugin
		Version: 1.3.0
		Author: Sharefaith

	Sharefaith Rest to WP-CLI
		Version: 1.1.0
		Author: Sharefaith

	Style Kits for Elementor
		Version: 1.7.4
		Author: AnalogWP

	W3 Total Cache
		Version: 0.15.0
		Author: BoldGrid

	WP Statistics
		Version: 12.6.13
		Author: VeronaLabs

	Yoast SEO
		Version: 15.0
		Author: Team Yoast


== Elements Usage ==
	
	archive : 1
		archive-posts : 1
		breadcrumbs : 1
		image : 1
		theme-archive-title : 1
	footer : 1
		google_maps : 1
		heading : 2
		icon-list : 1
		nav-menu : 1
		social-icons : 1
		text-editor : 2
	header : 1
		nav-menu : 2
		search-form : 1
		social-icons : 1
		theme-site-logo : 2
	page : 16
		MEC : 5
		Prayer Cloud : 1
		SFMBFMS : 6
		accordion : 3
		blockquote : 9
		breadcrumbs : 14
		button : 53
		divider : 24
		heading : 127
		html : 2
		icon-box : 22
		image : 35
		image-box : 10
		posts : 2
		sermon-cloud : 1
		slides : 1
		spacer : 9
		tabs : 1
		text-editor : 30
	section : 29
		MEC : 2
		SFMBFMS : 1
		accordion : 1
		blockquote : 4
		breadcrumbs : 1
		button : 16
		divider : 10
		heading : 32
		icon-box : 11
		image : 13
		image-box : 8
		posts : 1
		slides : 1
		tabs : 1
		text-editor : 10
	single : 2
		breadcrumbs : 2
		button : 1
		divider : 1
		heading : 3
		icon-box : 3
		image : 2
		post-comments : 1
		post-info : 1
		posts : 1
		search-form : 1
		theme-post-content : 1
		theme-post-excerpt : 1
		theme-post-featured-image : 1
		theme-post-title : 1
	widget : 0
		divider : 39
	wp-page : 17
		MEC : 5
		Prayer Cloud : 1
		SFMBFMS : 6
		accordion : 3
		blockquote : 9
		breadcrumbs : 15
		button : 53
		divider : 24
		heading : 129
		html : 2
		icon-box : 25
		image : 36
		image-box : 10
		posts : 2
		search-form : 1
		sermon-cloud : 1
		slides : 1
		spacer : 10
		tabs : 1
		text-editor : 30


== Log ==
	
JS: 2020-10-08 22:54:12 [error X 16][https://demo-sites.sharefaith.com/new-test-5f7f3c3e2b562/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.11:2:474322] this.container is undefined 

PHP: showing 6 of 6PHP: 2020-04-16 22:49:26 [notice X 900][/app/public/wp-content/plugins/elementor/includes/widgets/image.php::596] Undefined index: caption [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-04-23 21:54:36 [error X 1][/app/public/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/icons/custom-icons.php::127] Out of memory (allocated 44564480) (tried to allocate 8192 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-06-05 04:11:12 [notice X 1][/app/public/wp-content/plugins/elementor/core/logger/items/js.php::17] Undefined index: url [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-08-17 19:30:48 [notice X 2][/app/public/wp-content/plugins/elementor/includes/template-library/sources/local.php::585] Trying to get property 'display_name' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-10-08 16:24:33 [notice X 4][/app/public/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-10-10 00:43:31 [error X 3][/app/public/wp-content/plugins/elementor-pro/modules/global-widget/module.php::105] Uncaught TypeError: Argument 1 passed to ElementorPro\Modules\GlobalWidget\Module::get_element_child_type() must be an instance of Elementor\Element_Base, array given, called in /app/public/wp-includes/class-wp-hook.php on line 289 and defined in /app/public/wp-content/plugins/elementor-pro/modules/global-widget/module.php:105
Stack trace:
#0 /app/public/wp-includes/class-wp-hook.php(289): ElementorPro\Modules\GlobalWidget\Module->get_element_child_type(Array, Array)
#1 /app/public/wp-includes/plugin.php(206): WP_Hook->apply_filters(Array, Array)
#2 /app/public/wp-content/plugins/elementor/includes/base/element-base.php(934): apply_filters('elementor/eleme...', Array, Array, Object(Elementor\Element_Column))
#3 /app/public/wp-content/plugins/elementor/includes/base/element-base.php(353): Elementor\Element_Base->get_child_type(Array)
#4 /app/public/wp-content/plugins/elementor/includes/base/element-base.php(961): Elementor\Element_Base->add_child(Array)
#5 /app/public/wp-content/plugins/elementor/includes/base [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 18 of 182020-05-10 17:31:13 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.6',
  'to' => '2.9.8',
)]
2020-05-10 17:31:13 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.9.1',
  'to' => '2.9.4',
)]
2020-06-04 17:02:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.8',
  'to' => '2.9.11',
)]
2020-06-04 17:02:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.9.4',
  'to' => '2.9.5',
)]
2020-07-22 00:24:54 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.11',
  'to' => '2.9.13',
)]
2020-08-31 20:39:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.13',
  'to' => '2.9.14',
)]
2020-10-01 14:57:22 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.14',
  'to' => '3.0.11',
)]
2020-10-01 14:57:22 [info] elementor::elementor_updater Started 
2020-10-01 14:57:22 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Start  
2020-10-01 14:57:23 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Finished 
2020-10-01 14:57:23 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Start  
2020-10-01 14:57:23 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Finished 
2020-10-01 14:57:23 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Start  
2020-10-01 14:57:24 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Finished 
2020-10-01 14:57:24 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Start  
2020-10-01 14:57:24 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Finished 
2020-10-01 14:57:24 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.14',
  'to' => '3.0.11',
)]
2020-10-08 16:17:14 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.9.5',
  'to' => '3.0.5',
)]


				
```
</details>

**Comment by udidol** [comment]
Hi @Luke-SF ,
Please provide detailed steps to reproduce your issue.

**Comment by Luke-SF** [comment]
@udidol any post with similar _elementor_data postmeta should have the issue.

**Comment by udidol** [comment]
I tested your JSON, the background slideshows worked fine.
There is a reason we ask for steps to reproduce. Unfortunately a JSON is not enough.
Try disabling all of your other plugins and see if that solves your problem.

**Comment by DorShahar** [comment]
Closing for lack of activity,
Feel free to reopen if the issue persists.

**Comment by stzog** [comment]
I do have the same problem. Any solution guys?
