### ISSUE TITLE
Elementor 3.x The New Theme Builder is showing parts from last site on Multisite

### ISSUE THREAD

**Issue by shimsa** [elementor/elementor#12831]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Elementor 3.x The New Theme Builder is showing parts from last (changed) site on Multisite.

## Steps to reproduce

- WordPress Multisite with at least two sites and Elementor installed with different site parts created
- on the first WP Multisite site show The New Theme Builder screen
- set conditions (for example, but another action, like create new part also works) on one of the site part
- go to the second WP Multisite site
- show The New Theme Builder screen
- you can see parts from first site
- if you make some action, for example set conditions, now this second site parts is showing on the first site The New Theme Builder screen and so on

![theme-builder](https://user-images.githubusercontent.com/7617350/96002511-7b549e80-0e39-11eb-82ee-2d7881113afe.png)

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by arielk** [comment]
Thanks for reporting,

We can't reproduce this issue, please share with us the system info of your network.

**Comment by rodolphebertozzo** [comment]
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.6.48
	PHP Version: 7.0.33
	PHP Max Input Vars: 16000
	PHP Max Post Size: 130M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5.1
	Site URL: https://deboutlesjeunes.fr
	Home URL: https://deboutlesjeunes.fr
	WP Multisite: No
	Max Upload Size: 128 Mo
	Memory limit: 512M
	Permalink Structure: /%category%/%postname%/
	Language: fr-FR
	Timezone: Europe/Paris
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.3.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: fr_FR
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36 OPR/71.0.3770.271

== Active Plugins ==
	Default featured image
		Version: 1.6.4
		Author: Jan Willem Oostendorp

	Elementor
		Version: 3.0.11
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.5
		Author: Elementor.com

	HappyFiles
		Version: 1.4
		Author: Codeer

	LoginPress - Customizing the WordPress Login
		Version: 1.4.6
		Author: WPBrigade

	User Switching
		Version: 1.5.6
		Author: John Blackbourn & contributors

	Yoast SEO
		Version: 15.1.1
		Author: Team Yoast


== Elements Usage ==
	
	archive : 1
		archive-posts : 1
		heading : 1
		search-form : 1
	footer : 1
		button : 1
		divider : 1
		heading : 2
		icon-list : 1
		social-icons : 1
	header : 2
		nav-menu : 1
		social-icons : 1
		theme-site-logo : 1
	page : 1
		heading : 2
		image : 1
	single : 2
		heading : 1
		post-info : 1
		post-navigation : 1
		shortcode : 2
		spacer : 1
		theme-post-content : 1
		theme-post-featured-image : 1
		theme-post-title : 1
	wp-post : 2
		video : 1
	wp-page : 10
		animated-headline : 1
		button : 3
		call-to-action : 1
		divider : 5
		form : 1
		gallery : 1
		heading : 12
		html : 1
		image : 5
		image-box : 6
		posts : 1
		shortcode : 1
		slides : 1
		social-icons : 6
		spacer : 1
		testimonial-carousel : 1
		text-editor : 5
	single-page : 1
		heading : 1


== Log ==
	
Log: showing 20 of 392020-08-27 09:17:53 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.0',
  'to' => '3.0.1',
)]
2020-08-28 11:07:11 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.2',
  'to' => '3.0.3',
)]
2020-08-30 18:09:26 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.3',
  'to' => '3.0.4',
)]
2020-09-02 11:11:36 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.1',
  'to' => '3.0.2',
)]
2020-09-02 11:11:36 [info] elementor::elementor_updater Started 
2020-09-02 11:11:36 [info] Elementor/Upgrades - _v_3_0_5_re_move_space_between_widgets_to_kit Start  
2020-09-02 11:11:37 [info] Elementor/Upgrades - _v_3_0_5_re_move_space_between_widgets_to_kit Finished 
2020-09-02 11:11:37 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.4',
  'to' => '3.0.5',
)]
2020-09-02 11:11:37 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.4',
  'to' => '3.0.5',
)]
2020-09-02 11:11:37 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.1',
  'to' => '3.0.2',
)]
2020-09-06 17:43:30 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.5',
  'to' => '3.0.6',
)]
2020-09-06 17:43:30 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.2',
  'to' => '3.0.3',
)]
2020-09-09 20:01:31 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.6',
  'to' => '3.0.7',
)]
2020-09-09 20:01:31 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.3',
  'to' => '3.0.4',
)]
2020-09-14 18:31:47 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.7',
  'to' => '3.0.8',
)]
2020-09-15 10:09:53 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.8',
  'to' => '3.0.8.1',
)]
2020-09-19 14:24:07 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.8.1',
  'to' => '3.0.9',
)]
2020-09-23 16:22:04 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.9',
  'to' => '3.0.10',
)]
2020-09-23 16:22:17 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.4',
  'to' => '3.0.5',
)]
2020-09-30 18:06:36 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.10',
  'to' => '3.0.11',
)]

JS: showing 1 of 1JS: 2020-08-25 19:13:17 [error X 10][https://deboutlesjeunes.fr/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.1:2:469692] Cannot read property \'document\' of undefined 

PHP: showing 2 of 2PHP: 2020-09-02 11:12:03 [notice X 20][/home/deboutlejv/www/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-09-24 11:51:57 [error X 3][/home/deboutlejv/www/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::281] Uncaught Error: Call to a member function update_meta() on boolean in /home/deboutlejv/www/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:281
Stack trace:
#0 /home/deboutlejv/www/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(162): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/deboutlejv/www/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/deboutlejv/www/wp-includes/class-wp-hook.php(287): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/deboutlejv/www/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#5 /home/deboutlejv/www/wp-includes/plugin.php( [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

**Comment by shimsa** [comment]
I now created a clean WordPress environment and can confirm, that this issue is really happening.
I think the culprit is some cache in browser, because I deleted the WP environment and create new on the same domain and in the New Theme Builder it was showing the same header (on both sites) from previous WP environment.

First site
----
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.16.0
	MySQL version: MySQL Community Server - GPL v8.0.16
	PHP Version: 7.3.5
	PHP Max Input Vars: 4000
	PHP Max Post Size: 1000M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5.1
	Site URL: http://test.local
	Home URL: http://test.local
	WP Multisite: Yes
	Max Upload Size: 1 MB
	Memory limit: 256M
	Permalink Structure: /blog/%year%/%monthnum%/%day%/%postname%/
	Language: cs
	Timezone: Europe/Prague
	Admin Email: dev-email@testing.local
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.3.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: cs_CZ
	User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.0.12
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.5
		Author: Elementor.com


== Elements Usage ==
	
	header : 1
		heading : 1
	wp-page : 1
		text-editor : 1


== Log ==
	
PHP: showing 1 of 1PHP: 2020-10-21 14:00:50 [notice X 9][/.../wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Second site
----


== Server Environment ==
	Operating System: Linux
	Software: nginx/1.16.0
	MySQL version: MySQL Community Server - GPL v8.0.16
	PHP Version: 7.3.5
	PHP Max Input Vars: 4000
	PHP Max Post Size: 1000M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5.1
	Site URL: http://test.local/test2
	Home URL: http://test.local/test2
	WP Multisite: Yes
	Max Upload Size: 1 MB
	Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: cs
	Timezone: Europe/Prague
	Admin Email: dev-email@testing.local
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.3.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: cs_CZ
	User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.0.12
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.5
		Author: Elementor.com


== Elements Usage ==
	
	footer : 1
		button : 1
	wp-page : 1
		heading : 1
		text-editor : 1


== Log ==
	
PHP: showing 1 of 1PHP: 2020-10-21 14:06:23 [notice X 8][/.../wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

**Comment by shimsa** [comment]
- create new WP environment
- change WP site language to Czech
- create new (second) site with Czech language
- install Elementor Hello Theme and activate on both sites
- install Elementor and Elementor Pro
- activate plugins on both sites
- create new page with Elementor on both sites
- set this page as A static page in Customize option
- "Open Theme Bulder" and create header on the first site
- "Open Theme Bulder" and create footer on the second site

**Comment by rodolphebertozzo** [comment]
+1
