### ISSUE TITLE
Bug with Colors in Safari

### ISSUE THREAD

**Issue by maurocarreraok** [elementor/elementor#12948]
- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X ] The issue still exists against the latest stable version of Elementor.

## Description

I added a gradient on the HEADER on my site. The first color is BLACK and the Second is transparent. I dont know why, but the "transparent color" is taking a "pink" color instead. I try to change it manually and the same happends.

![image](https://user-images.githubusercontent.com/68023943/97366837-c84b6280-1886-11eb-9e15-5d53798b0deb.png)

## Steps to reproduce

1. Add a header.
2. Choose a gradient background color.
3. Color 1: Black º Color 2: Transparent.
4. Check the header on Safari (Mac)

## Isolating the problem

- [ X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X ] This bug happens with a default WordPress theme active.
- [X ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.26-29
	PHP Version: 7.3.23
	PHP Max Input Vars: 3000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5.1
	Site URL: https://staging2.graes.eu
	Home URL: http://staging2.graes.eu
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: es
	Timezone: Europe/Madrid
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.3.0
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: es_ES
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.0.12
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.5
		Author: Elementor.com

	Wordfence Security
		Version: 7.4.12
		Author: Wordfence

	WPS Hide Login
		Version: 1.5.7
		Author: WPServeur, NicolasKulka, tabrisrp

	Yoast SEO
		Version: 15.2
		Author: Team Yoast


== Elements Usage ==
	
	footer : 1
		heading : 2
		image : 2
		nav-menu : 4
	header : 1
		image : 1
		nav-menu : 2
		theme-site-logo : 1
	page : 2
		button : 6
		heading : 7
		icon : 2
		image : 6
		slides : 1
		spacer : 2
		template : 1
		text-editor : 5
	section : 1
		divider : 1
		heading : 1
		image : 3
		image-carousel : 1
	wp-page : 10
		button : 10
		form : 1
		heading : 63
		icon : 2
		image : 58
		slides : 2
		spacer : 3
		template : 6
		text-editor : 56
		video : 5


== Log ==
	
PHP: showing 3 of 3PHP: 2020-10-14 11:32:57 [notice X 23][/home/graese5/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-10-16 16:40:24 [error X 1][/home/graese5/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::281] Uncaught Error: Call to a member function update_meta() on boolean in /home/graese5/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:281
Stack trace:
#0 /home/graese5/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(162): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/graese5/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/graese5/public_html/wp-includes/class-wp-hook.php(287): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/graese5/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#5 /home/graese5/publi [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-10-26 11:30:07 [notice X 1][/home/customer/www/staging2.graes.eu/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php::697] ob_end_clean(): failed to delete buffer. No buffer to delete [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 2 of 22020-10-14 11:47:03 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.3',
  'to' => '3.0.5',
)]
2020-10-21 22:25:00 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.11',
  'to' => '3.0.12',
)]

JS: showing 6 of 6JS: 2020-10-15 02:54:17 [error X 1][https://graes.eu/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view1797\") has already been destroyed and cannot be used. 
JS: 2020-10-15 16:13:21 [error X 3][https://graes.eu/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.11:2:230237] Blocked a frame with origin \"https://graes.eu\" from accessing a cross-origin frame. 
JS: 2020-10-20 14:31:23 [error X 1][https://graes.eu/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.11:2:332336] elementorFrontend is not defined 
JS: 2020-10-21 20:25:07 [error X 19][http://staging2.graes.eu/wp-content/plugins/elementor/assets/js/app-loader.min.js?ver=3.0.12:2:78981] El objeto no acepta la propiedad o el método \'forEach\' 
JS: 2020-10-21 20:26:46 [error X 1][http://staging2.graes.eu/wp-content/plugins/elementor/assets/js/common.min.js?ver=3.0.12:2:110864] El objeto no acepta la propiedad o el método \'fromEntries\' 
JS: 2020-10-27 20:52:49 [error X 1][https://staging2.graes.eu/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.12:2:465738] Cannot read property \'menu\' of undefined 


				
```
</details>
![image](https://user-images.githubusercontent.com/68023943/97366813-bc5fa080-1886-11eb-8d09-46da7ed7cb41.png)

**Comment by portrayaloflife** [comment]
Whats the other gradiant color set to? If it's red and then moved to be fully transparent Safari shows that color so try making the color #000 and then sliding the transparency all the way and clearing your cache and that should fix the issue on safari. I don't know why their browser does that.
