### ISSUE TITLE
URL advanced targeting -Shortlinks

### ISSUE THREAD

**Issue by semiexperienced** [elementor/elementor#12970]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest stable version of Elementor

## Isolating the problem

- [x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x ] This bug happens with a default WordPress theme active.
- [x ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release 84.1, Revision b308619 v5.6.41-84.1
	PHP Version: 7.3.23
	PHP Max Input Vars: 1000
	PHP Max Post Size: 260M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5.3
	Site URL: https://precisemobiledetail.com
	Home URL: https://precisemobiledetail.com
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: -4
	Debug Mode: Inactive

== Theme ==
	Name: Astra
	Version: 2.6.0
	Author: Brainstorm Force
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0

== Active Plugins ==
	Add From Server
		Version: 3.4.4
		Author: Dion Hulse

	Akismet Anti-Spam
		Version: 4.1.7
		Author: Automattic

	Async JavaScript
		Version: 2.20.03.01
		Author: Frank Goossens (futtta)

	Autoptimize
		Version: 2.7.8
		Author: Frank Goossens (futtta)

	Contact Form 7
		Version: 5.3
		Author: Takayuki Miyoshi

	Elementor
		Version: 3.0.12
		Author: Elementor.com

	Elementor - Header, Footer & Blocks
		Version: 1.5.3
		Author: Brainstorm Force, Nikhil Chavan

	Elementor Pro
		Version: 3.0.5
		Author: Elementor.com

	Events Tracker for Elementor
		Version: 1.2.6
		Author: wpl.agency

	HubSpot All-In-One Marketing - Forms, Popups, Live Chat
		Version: 7.46.2
		Author: HubSpot

	Insert PHP Code Snippet
		Version: 1.3.1
		Author: xyzscripts.com

	iQ Block Country
		Version: 1.2.10
		Author: Pascal

	Jetpack by WordPress.com
		Version: 9.0.2
		Author: Automattic

	PDF Poster
		Version: 1.6.3
		Author: bPlugins

	Really Simple SSL
		Version: 3.3.5
		Author: Really Simple Plugins

	Starter Templates
		Version: 2.3.8
		Author: Brainstorm Force

	Temporary Login Without Password
		Version: 1.6.6
		Author: StoreApps

	W3 Total Cache
		Version: 0.15.1
		Author: BoldGrid

	Wordfence Security
		Version: 7.4.12
		Author: Wordfence

	WP Encryption - One Click SSL & Force HTTPS
		Version: 5.2.4
		Author: Go Web Smarty

	WPForms Lite
		Version: 1.6.3.1
		Author: WPForms

	WP Smart Preloader
		Version: 1.12
		Author: catchsquare

	Yoast SEO
		Version: 15.1.1
		Author: Team Yoast

	YOURLS Link Creator
		Version: 2.1.1
		Author: Andrew Norcross

== Elements Usage ==
	
	page : 3
		button : 1
		heading : 2
		image : 1
		price-table : 7
	popup : 9
		form : 3
		heading : 4
		icon : 2
		image : 6
		text-editor : 3
	wp-post : 0
		button : 14
		heading : -12
		image : 1
		price-list : 1
		price-table : 8
		shortcode : 1
		social-icons : 1
		text-editor : -10
	wp-page : 4
		button : 3
		divider : 4
		heading : 5
		image : 5
		image-box : 2
		spacer : 1
		text-editor : 3

== Log ==
	
Log: showing 20 of 272020-08-26 02:34:01 [notice] System typography is disabled. nothing to do. 
2020-08-26 02:34:01 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Finished 
2020-08-26 02:34:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.14',
  'to' => '3.0.1',
)]
2020-09-01 02:33:20 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.1',
  'to' => '3.0.5',
)]
2020-09-01 02:33:21 [info] elementor::elementor_updater Started 
2020-09-01 02:33:21 [info] Elementor/Upgrades - _v_3_0_5_re_move_space_between_widgets_to_kit Start  
2020-09-01 02:33:21 [info] Elementor/Upgrades - _v_3_0_5_re_move_space_between_widgets_to_kit Finished 
2020-09-01 02:33:21 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.1',
  'to' => '3.0.5',
)]
2020-09-01 02:33:22 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.1',
  'to' => '3.0.5',
)]
2020-09-01 02:50:46 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.10.3',
  'to' => '3.0.2',
)]
2020-09-15 00:30:31 [info] elementor::elementor_updater Started 
2020-09-15 00:30:31 [info] Elementor/Upgrades - _v_3_0_5_re_move_space_between_widgets_to_kit Start  
2020-09-15 00:30:31 [info] Elementor/Upgrades - _v_3_0_5_re_move_space_between_widgets_to_kit Finished 
2020-09-15 00:30:31 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.5',
  'to' => '3.0.8.1',
)]
2020-09-18 09:11:49 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.8.1',
  'to' => '3.0.9',
)]
2020-09-21 21:19:19 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.2',
  'to' => '3.0.4',
)]
2020-09-24 08:28:14 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.9',
  'to' => '3.0.10',
)]
2020-09-25 09:06:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.4',
  'to' => '3.0.5',
)]
2020-09-30 21:11:07 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.10',
  'to' => '3.0.11',
)]
2020-10-21 23:53:30 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.11',
  'to' => '3.0.12',
)]

PHP: showing 2 of 2PHP: 2020-10-13 01:47:50 [notice X 2][/home/pjpkj3kpyzl6/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-10-27 21:31:20 [error X 1][/home3/pjpkj3kpyzl6/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::281] Uncaught Error: Call to a member function update_meta() on bool in /home3/pjpkj3kpyzl6/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:281
Stack trace:
#0 /home3/pjpkj3kpyzl6/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(162): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home3/pjpkj3kpyzl6/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home3/pjpkj3kpyzl6/public_html/wp-includes/class-wp-hook.php(287): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home3/pjpkj3kpyzl6/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Ar [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 14 of 14JS: 2020-10-22 13:24:10 [error X 2][https://precisemobiledetail.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.12:2:474628] this.container is undefined 
JS: 2020-10-22 19:14:48 [error X 7][https://precisemobiledetail.com/wp-content/plugins/elementor/assets/lib/nouislider/nouislider.min.js?ver=13.0.0:2:4604] noUiSlider (13.0.0): \'start\' option is incorrect. 
JS: 2020-10-25 16:11:23 [error X 1][https://precisemobiledetail.com/wp-content/plugins/elementor/assets/js/editor-document.min.js?ver=3.0.12:2:229393] Cannot read property \'map\' of undefined 
JS: 2020-10-25 23:26:19 [error X 1][https://precisemobiledetail.com/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=3.0.5:2:143240] this.elements.$submitButton.attr(...) is undefined 
JS: 2020-10-27 02:45:34 [error X 2][https://precisemobiledetail.com/wp-content/plugins/elementor/assets/js/common.min.js?ver=3.0.12:2:157191] Routes: `theme-builder-publish/triggers` is already registered. 
JS: 2020-10-27 02:46:16 [error X 1][https://precisemobiledetail.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.12:2:332570] elementorFrontend is not defined 
JS: 2020-10-29 12:05:34 [error X 1][https://precisemobiledetail.com/wp-includes/js/jquery/jquery.js?ver=1.12.4-wp:2:4] expected expression, got \'<\' 
JS: 2020-10-29 12:05:50 [error X 1][https://precisemobiledetail.com/wp-includes/js/jquery/jquery.js?ver=1.12.4-wp line 2 > eval:3:13] v is not defined 
JS: 2020-10-29 12:05:50 [error X 1][https://precisemobiledetail.com/wp-includes/js/jquery/jquery.js?ver=1.12.4-wp line 2 > eval:3:13] va is not defined 
JS: 2020-10-29 12:05:51 [error X 1][https://precisemobiledetail.com/wp-includes/js/jquery/jquery.js?ver=1.12.4-wp:4:8] missing variable name 
JS: 2020-10-29 12:05:57 [error X 7][https://precisemobiledetail.com/wp-includes/js/jquery/jquery.js?ver=1.12.4-wp:4:8] missing ( before condition 
JS: 2020-10-30 18:17:58 [error X 1][https://precisemobiledetail.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view678\") has already been destroyed and cannot be used. 
JS: 2020-10-30 18:38:36 [error X 1][https://precisemobiledetail.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view2218\") has already been destroyed and cannot be used. 
JS: 2020-10-30 18:39:21 [error X 1][https://precisemobiledetail.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view2707\") has already been destroyed and cannot be used. 

				
</details>

**Comment by semiexperienced** [comment]
Thanksss
