### ISSUE TITLE
Error when submitting form with a required tel field with no ID

### ISSUE THREAD

**Issue by leosolid** [elementor/elementor#13012]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

`Uncaught TypeError: Cannot read property 'error' of undefined` when submitting an elementor form.

## Steps to reproduce

1. Create a form
2. Add tel field. Mark it as required and leave ID blank.
3. Try submitting form.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release '34', Revision '2e68637' v5.7.31-34
	PHP Version: 7.4.10
	PHP Max Input Vars: 10000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5
	Site URL: https://3xequity.com
	Home URL: http://3xequity.com
	WP Multisite: No
	Max Upload Size: 50 MB
	Memory limit: 512M
	Permalink Structure: /blog/%postname%
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.3.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36

== Active Plugins ==
	Code Snippets
		Version: 2.14.0
		Author: Code Snippets Pro

	Elementor
		Version: 3.0.13
		Author: Elementor.com

	Elementor Addon Elements
		Version: 1.7.1
		Author: WP Vibes

	Elementor Pro
		Version: 2.10.3
		Author: Elementor.com

	ElementsKit Lite
		Version: 2.0.9.1
		Author: Wpmet

	Envato Elements
		Version: 2.0.6
		Author: Envato

	Envato Market
		Version: 2.0.3
		Author: Envato

	Error Log Monitor
		Version: 1.6.12
		Author: Janis Elsts

	Formidable Forms
		Version: 4.09
		Author: Strategy11

	Geolocation IP Detection
		Version: 3.1.1
		Author: Yellow Tree (Benjamin Pick)

	Google Analytics for WordPress by MonsterInsights
		Version: 7.12.3
		Author: MonsterInsights

	Insert Headers and Footers
		Version: 1.4.6
		Author: WPBeginner

	JetSticky For Elementor
		Version: 1.0.1
		Author: Crocoblock

	Kirki Customizer Framework
		Version: 3.1.5
		Author: David Vongries

	Master Slider Pro
		Version: 3.2.14
		Author: averta

	MOJO Marketplace
		Version: 1.5.7
		Author: Mike Hansen

	Page Builder Widget Pack
		Version: 1.5.13
		Author: Themovation

	Premium Addons for Elementor
		Version: 3.21.6
		Author: Leap13

	Press Elements - Widgets for Elementor
		Version: 1.7.2
		Author: Press Elements

	Simple Page Ordering
		Version: 2.3.4
		Author: Jake Goldman, 10up

	Smush
		Version: 3.7.1
		Author: WPMU DEV

	UpdraftPlus - Backup/Restore
		Version: 1.16.26
		Author: UpdraftPlus.Com, DavidAnderson

	VideoAsk
		Version: 1.0.2
		Author: Typeform

	Widget Logic
		Version: 5.10.4
		Author: WPChef

	WPForms Lite
		Version: 1.6.3.1
		Author: WPForms

	Yoast SEO
		Version: 15.2.1
		Author: Team Yoast

== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

	Force Strong Passwords - WPE Edition
		Version: 1.6.4
		Author: Jason Cosper

	SSO
		Version: 0.3
		Author: Garth Mortensen, Mike Hansen

	WP Engine Seamless Login Plugin
		Version: 1.5.5
		Author: WP Engine

	WP Engine Security Auditor
		Version: 1.0.9
		Author: wpengine

	WP Engine System
		Version: 4.0.0
		Author: WP Engine

== Elements Usage ==
	
	footer : 3
		divider : 1
		form : 1
		heading : 2
		icon-list : 2
		text-editor : 1
	page : 57
		button : 4
		elementskit-client-logo : 2
		elementskit-funfact : 4
		elementskit-piechart : 8
		elementskit-progressbar : 4
		elementskit-team : 6
		form : 3
		heading : 31
		html : 14
		icon-box : 13
		icon-list : 1
		image : 7
		image-carousel : 2
		media-carousel : 1
		menu-anchor : 2
		nav-menu : 1
		premium-addon-dual-header : 9
		premium-img-gallery : 1
		shortcode : 1
		spacer : 25
		template : 2
		testimonial-carousel : 2
		text-editor : 44
		themo-blog : 1
		themo-button : 4
		video : 2
	popup : 8
		form : 1
		heading : 2
		text-editor : 1
		video : 1
	section : 20
		button : 11
		divider : 3
		ekit-nav-menu : 2
		elementskit-blog-posts : 4
		elementskit-funfact : 8
		elementskit-header-offcanvas : 2
		elementskit-header-search : 2
		elementskit-icon-box : 16
		elementskit-testimonial : 2
		elementskit-video : 4
		form : 4
		heading : 45
		html : 3
		icon-box : 3
		icon-list : 12
		image : 22
		image-carousel : 3
		menu-anchor : 1
		premium-addon-dual-header : 16
		spacer : 8
		template : 1
		testimonial : 3
		text-editor : 14
		themo-button : 1
		themo-image-gallery : 1
		video : 3
	single : 3
		author-box : 1
		facebook-button : 1
		facebook-comments : 1
		heading : 4
		html : 1
		image : 3
		post-info : 1
		posts : 1
		search-form : 1
		template : 4
		theme-post-content : 1
		theme-post-featured-image : 1
	widget : 0
		form : 3
		html : 42
		text-editor : 4
	wp-post : 123
		button : 7
		divider : 7
		form : 1
		global : 2
		heading : 62
		html : 17
		icon-box : 37
		icon-list : 10
		image : 53
		image-box : 7
		media-carousel : 1
		menu-anchor : 8
		posts : 2
		search-form : 1
		shortcode : 1
		spacer : 115
		tabs : 6
		template : 22
		testimonial-carousel : 2
		text-editor : 205
		themo-blog : 12
		themo-button : 18
		themo-formidable-form : 1
		themo-header : 6
		themo-image-gallery : 1
		video : 28
	wp-page : 53
		button : 5
		divider : 9
		ekit-nav-menu : 7
		elementskit-blog-posts : 3
		elementskit-funfact : 3
		elementskit-icon-box : 13
		elementskit-team : 3
		elementskit-testimonial : 1
		elementskit-video : 4
		form : 11
		global : 2
		heading : 49
		html : -7
		icon-box : -4
		icon-list : 18
		image : 22
		image-carousel : 2
		media-carousel : 1
		menu-anchor : 5
		premium-addon-dual-header : 11
		spacer : 6
		template : 1
		text-editor : 3
		themo-feature-bar : 1
		themo-image-gallery : 1
		video : 1

== Log ==
	
PHP: showing 4 of 4PHP: 2020-07-13 19:18:14 [error X 1][/nas/content/live/staging3x/wp-content/plugins/elementor/includes/template-library/sources/local.php::1081] Uncaught TypeError: Argument 2 passed to Elementor\TemplateLibrary\Source_Local::on_save_post() must be an instance of WP_Post, null given, called in /nas/content/live/staging3x/wp-includes/class-wp-hook.php on line 289 and defined in /nas/content/live/staging3x/wp-content/plugins/elementor/includes/template-library/sources/local.php:1081
Stack trace:
#0 /nas/content/live/staging3x/wp-includes/class-wp-hook.php(289): Elementor\TemplateLibrary\Source_Local->on_save_post(4609, NULL)
#1 /nas/content/live/staging3x/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#2 /nas/content/live/staging3x/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#3 /nas/content/live/staging3x/wp-includes/post.php(4153): do_action('save_post', 4609, NULL, true)
#4 /nas/content/live/staging3x/wp-includes/post.php(4244): wp_insert_post(Array, false)
#5 /nas/content/live/staging3x/wp-content/plugins/elementor/includes/db.php(331): wp_update_post(Array)
#6 /nas/content/live/staging3x/wp-content/plugins/elementor/core/b [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-08-07 18:53:13 [notice X 2][/nas/content/live/staging3x/wp-content/plugins/elementor/core/logger/items/js.php::17] Undefined index: url [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-08-31 18:20:23 [notice X 104][/nas/content/live/staging3x/wp-content/plugins/elementor/includes/base/controls-stack.php::1430] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-10-08 22:41:55 [notice X 1][/nas/content/live/staging3x/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 20 of 302020-08-25 17:13:57 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Start  
2020-08-25 17:13:57 [notice] System typography is disabled. nothing to do. 
2020-08-25 17:13:57 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Finished 
2020-08-25 17:13:57 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.14',
  'to' => '3.0.0',
)]
2020-08-26 05:13:13 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.0',
  'to' => '3.0.1',
)]
2020-08-26 17:14:18 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.1',
  'to' => '3.0.2',
)]
2020-08-28 05:12:35 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.2',
  'to' => '3.0.3',
)]
2020-08-30 17:10:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.3',
  'to' => '3.0.4',
)]
2020-08-31 18:15:08 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.4',
  'to' => '3.0.5',
)]
2020-08-31 18:15:22 [info] elementor::elementor_updater Started 
2020-08-31 18:15:22 [info] Elementor/Upgrades - _v_3_0_5_re_move_space_between_widgets_to_kit Start  
2020-08-31 18:15:22 [info] Elementor/Upgrades - _v_3_0_5_re_move_space_between_widgets_to_kit Finished 
2020-08-31 18:15:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.4',
  'to' => '3.0.5',
)]
2020-09-09 16:51:26 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.5',
  'to' => '3.0.7',
)]
2020-09-15 03:28:07 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.7',
  'to' => '3.0.8.1',
)]
2020-09-23 16:27:37 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.8.1',
  'to' => '3.0.10',
)]
2020-09-30 17:53:21 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.10',
  'to' => '3.0.11',
)]
2020-10-21 16:58:31 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.11',
  'to' => '3.0.12',
)]
2020-11-04 17:14:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.12',
  'to' => '3.0.13',
)]
2020-11-04 17:14:49 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.12',
  'to' => '3.0.13',
)]

JS: showing 8 of 8JS: 2020-08-28 18:14:10 [error X 19][https://staging3x.wpengine.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.3:2:470394] Cannot read property \'document\' of undefined 
JS: 2020-08-28 18:18:50 [error X 17928][https://staging3x.wpengine.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.3:2:133222] Cannot read property \'get\' of undefined 
JS: 2020-10-08 18:36:31 [error X 29][https://staging3x.wpengine.com/wp-content/plugins/elementor/assets/js/common.min.js:2:128443] Cannot read property \'error\' of undefined 
JS: 2020-10-22 23:12:00 [error X 1][https://prod3x.wpengine.com/wp-admin/post.php?post=4865&action=elementor:64:20] Cannot set property \'value\' of null 
JS: 2020-10-23 21:02:23 [error X 1][https://3xequity.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view22563\") has already been destroyed and cannot be used. 
JS: 2020-10-23 21:04:53 [error X 1][https://3xequity.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view28208\") has already been destroyed and cannot be used. 
JS: 2020-10-29 21:50:05 [error X 12][https://3xequity.com/wp-admin/post.php?post=4864&action=elementor:9:6] $owl.owlCarousel is not a function 
JS: 2020-11-04 19:47:43 [error X 3][https://3xequity.com/wp-admin/post.php?post=4915&action=elementor#:2:1] Unexpected token \'<\' 
</details>

**Comment by xoich** [comment]
I confirm this issue. The problem in general seems to be that no error messages coming from the backend Ajax handler are being reported to the user because of this javascript error.

**Comment by coachdesign** [comment]
I also confirm the problem.
I tried to downgrade to version 3.0.9 but the problem remains.
Has anyone solved the problem?

**Comment by MichaelDarko** [comment]
Same thing happened to me. This one is scary because the form will not send and doesn't show any error to the user, so you might not even know your form is not working.
