### ISSUE TITLE
backbone.marionette.min.js error

### ISSUE THREAD

**Issue by qwik3r** [elementor/elementor#13059]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

While editing a single product template I am noticing an error in the console relating to backbone.marionette.min.js?ver=2.4.5:22. https://share.getcloudapp.com/eDuPqQk2. First triggered by the fact that my product gallery widget is NOT showing up properly in the editor (shows up fine in the front end)

## Steps to reproduce

Not entirely sure how to reproduce but perhaps try adding a Woocommerce product image gallery to yoru page. 

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release '34', Revision '2e68637' v5.7.31-34
	PHP Version: 7.4.10
	PHP Max Input Vars: 10000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5.3
	Site URL: https://xxx.wpengine.com
	Home URL: https://xxx.wpengine.com
	WP Multisite: No
	Max Upload Size: 50 MB
	Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email:
	Debug Mode: Inactive

== Theme ==
	Name: Blocksy Child
	Version: 
	Author: Creative Themes
	Child Theme: Yes
	Parent Theme Name: Blocksy
	Parent Theme Version: 1.7.40
	Parent Theme Author: CreativeThemes

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields: Font Awesome
		Version: 3.1.1
		Author: mattkeys

	Advanced Custom Fields: Image Aspect Ratio Crop
		Version: 4.1.2
		Author: Johannes Siipola

	Advanced Custom Fields PRO
		Version: 5.9.3
		Author: Elliot Condon

	Ajax add to cart for WooCommerce
		Version: 1.1.4
		Author: QuadLayers

	AnyWhere Elementor Pro
		Version: 2.16
		Author: WP Vibes

	Code Snippets
		Version: 2.14.0
		Author: Code Snippets Pro

	Collapse-O-Matic
		Version: 1.7.13
		Author: twinpictures, baden03

	Crop Thumbnails
		Version: 1.2.6
		Author: Volkmar Kantor

	Custom Icons for Elementor
		Version: 0.3.1
		Author: Michael Bourne

	DynamicConditions
		Version: 1.4.6
		Author: RTO GmbH

	Easy Theme and Plugin Upgrades
		Version: 2.0.1
		Author: Chris Jean

	Elementor
		Version: 3.0.13
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.6
		Author: Elementor.com

	Emage Hover Effects for Elementor
		Version: 4.2.0
		Author: Blocksera

	Emojics WP
		Version: 1.5.4
		Author: Emojics

	Happy Elementor Addons
		Version: 2.15.0
		Author: weDevs

	Happy Elementor Addons Pro
		Version: 1.11.1
		Author: weDevs

	Header and Footer Scripts
		Version: 2.2.1
		Author: Digital Liberation

	JetElements For Elementor
		Version: 2.3.1
		Author: Crocoblock

	JetEngine
		Version: 2.4.9
		Author: Crocoblock

	JetProductGallery For Elementor
		Version: 1.1.5
		Author: Crocoblock

	JetSticky For Elementor
		Version: 1.0.1
		Author: Crocoblock

	JetTricks
		Version: 1.2.9
		Author: Crocoblock

	LearnDash LMS
		Version: 3.2.3.6
		Author: LearnDash

	LearnDash LMS - Elementor
		Version: 1.0.2
		Author: LearnDash

	Login Logout Menu
		Version: 1.1.0
		Author: WPBrigade

	Piotnet Addons For Elementor Pro
		Version: 6.0.16
		Author: Luong Huu Phuoc (Louis Hufer)

	Plugin Notes Plus
		Version: 1.2.2
		Author: Jamie Bergen

	Regenerate Thumbnails Advanced
		Version: 2.3.2
		Author: ShortPixel

	Simple Image Sizes
		Version: 3.2.1
		Author: Rahe

	Stamped.io Reviews & UGC for WooCommerce
		Version: 2.1.9
		Author: Stamped.io

	Sticky Header Effects for Elementor
		Version: 1.4.3
		Author: Rwattner

	Style Kits for Elementor
		Version: 1.7.5
		Author: AnalogWP

	Ultimate Addons for Elementor
		Version: 1.27.0
		Author: Brainstorm Force

	WooCommerce
		Version: 4.7.0
		Author: Automattic

	WooCommerce Amazon S3 Storage
		Version: 2.1.19
		Author: WooCommerce

	WP Revisions Control
		Version: 1.3
		Author: Erick Hitter

	WP Video Popup PRO
		Version: 2.8.4
		Author: David Vongries

	YITH WooCommerce Badge Management Premium
		Version: 1.4.3
		Author: YITH

	Yoast Duplicate Post
		Version: 3.2.6
		Author: Enrico Battocchi & Team Yoast


== Must-Use Plugins ==
	Force Strong Passwords - WPE Edition
		Version: 1.6.4
		Author: Jason Cosper

	LearnDash LMS Multisite
		Version: 1.0.0
		Author: LearnDash

	Local by Flywheel Live Link Helper
		Version: 1.1
		Author: Flywheel

	Stop long comments
		Version: 0.0.4
		Author: WPEngine

	WP Engine Seamless Login Plugin
		Version: 1.5.5
		Author: WP Engine

	WP Engine Security Auditor
		Version: 1.0.9
		Author: wpengine

	WP Engine System
		Version: 4.0.0
		Author: WP Engine


== Elements Usage ==
	
	archive : 1
		heading : 1
		posts : 1
		search-form : 1
	header : 3
		image : 4
		nav-menu : 2
		search-form : 2
		uael-offcanvas : 2
		woocommerce-menu-cart : 4
	loop : 0
		emage_hover_effects : 4
		text-editor : 2
		theme-post-title : 3
	page : 7
		accordion : 8
		ae-portfolio : 1
		ae-post-blocks : 3
		ae-post-image : 1
		ae-post-title : 1
		ae-woo-add-to-cart : 1
		ae-woo-price : 2
		blockquote : 1
		button : 15
		divider : 6
		heading : 45
		icon : 1
		icon-box : 3
		icon-list : 6
		image : 26
		image-gallery : 1
		lottie : 1
		posts : 2
		price-table : 2
		progress : 1
		reviews : 1
		share-buttons : 1
		shortcode : 5
		star-rating : 1
		testimonial : 3
		testimonial-carousel : 1
		text-editor : 34
		uael-advanced-heading : 1
		uael-buttons : 1
		uael-image-gallery : 1
		uael-posts : 1
		uael-video : 2
		uael-woo-add-to-cart : 2
		woocommerce-product-title : 1
	product : 10
		ae-acf : 12
		ae-post-blocks : 8
		ae-woo-add-to-cart : 2
		ae-woo-description : 5
		ae-woo-price : 2
		heading : 69
		image : 6
		jet-listing-dynamic-repeater : 13
		jet-woo-product-gallery-slider : 1
		shortcode : 11
		star-rating : 7
		text-editor : 9
		theme-post-content : 4
		theme-post-featured-image : 2
		uael-faq : 8
		uael-image-gallery : 14
		uael-woo-add-to-cart : 16
		woocommerce-breadcrumb : 13
		woocommerce-product-add-to-cart : 4
		woocommerce-product-images : 4
		woocommerce-product-price : 18
		woocommerce-product-short-description : 4
		woocommerce-product-title : 2
	section : 56
		ae-acf : 2
		ae-post-blocks : 5
		ae-post-title : 1
		ae-woo-add-to-cart : 1
		ae-woo-price : 2
		button : 18
		divider : 12
		emage_hover_effects : 2
		form : 1
		gallery : 15
		heading : 69
		html : 2
		image : 34
		image-box : 4
		jet-blog-video-playlist : 1
		jet-listing-dynamic-repeater : 2
		lottie : 1
		nav-menu : 1
		posts : 3
		price-table : 2
		search-form : 1
		shortcode : 3
		spacer : 1
		table-of-contents : 1
		testimonial : 32
		text-editor : 60
		uael-image-gallery : 5
		uael-nav-menu : 1
		uael-posts : 2
		uael-video : 4
		uael-woo-add-to-cart : 5
		video : 10
		woocommerce-breadcrumb : 2
		woocommerce-menu-cart : 1
		woocommerce-product-add-to-cart : 4
		woocommerce-product-images : 1
		woocommerce-product-price : 5
		woocommerce-product-short-description : 2
		woocommerce-product-title : 4
	footer : 1
		form : 1
		heading : 4
		icon-list : 1
		shortcode : 1
		text-editor : 2
		uael-nav-menu : 2
	single : 2
		ae-post-blocks : 1
		button : 1
		heading : 3
		html : 1
		post-info : 1
		posts : 1
		text-editor : 1
		theme-post-content : 2
		theme-post-title : 2
		uael-video : 1
	widget : 0
		shortcode : 8
		uael-image-gallery : 3
	single-post : 1
		shortcode : 1
		theme-post-content : 1
		wp-widget-ldcourseprogress : 1
	sfwd-topic : 2
		ld-course-content : 1
		ld-course-infobar : 1
		theme-post-content : 1
		theme-post-title : 1
	sfwd-quiz : 2
		ld-course-infobar : 1
		theme-post-content : 1
		theme-post-title : 1
	sfwd-lessons : 1
		ld-course-content : 1
		shortcode : 1
		theme-post-title : 1
	product-post : 0
		accordion : 8
		ae-woo-price : 8
		blockquote : 1
		button : 10
		divider : 10
		gallery : 1
		heading : 87
		icon : 4
		icon-box : 23
		icon-list : 14
		image : 46
		image-gallery : 6
		lottie : 6
		reviews : 1
		share-buttons : 1
		shortcode : 10
		spacer : 10
		star-rating : 1
		testimonial : 1
		testimonial-carousel : 1
		text-editor : 43
		toggle : 2
		uael-advanced-heading : 1
		uael-buttons : 1
		uael-image-gallery : 2
		uael-video : 8
		uael-woo-add-to-cart : 12
		video : 1
		wc-add-to-cart : 1
		woocommerce-product-title : 6
	wp-page : 12
		ae-portfolio : 3
		ae-post-blocks : 5
		author-box : 1
		button : 4
		divider : 2
		form : 1
		heading : 17
		image : 4
		image-box : 3
		spacer : 1
		testimonial : 1
		text-editor : 7
		theme-page-title : 2
		uael-infobox : 1
		video : 1
	wp-post : 0
		ae-post-image : 2
		ae-post-title : 1
		ae-woo-add-to-cart : 1
		ae-woo-description : 1
		ae-woo-price : 2
		divider : 3
		emage_hover_effects : 9
		gallery : 89
		global : 1
		heading : 76
		image : 3
		image-box : 28
		jet-blog-video-playlist : 5
		post-info : 4
		shortcode : 6
		spacer : 1
		table-of-contents : 1
		text-editor : 117
		theme-post-title : 9
		uael-image-gallery : 1
		uael-video : 36
		video : 10
	sfwd-courses : 2
		heading : 1
		ld-course-certificate : 2
		ld-course-content : 2
		ld-course-infobar : 2
		theme-post-content : 2
		theme-post-title : 2


== Log ==
	
Log: showing 20 of 282020-10-05 22:56:42 [notice] System typography is disabled. nothing to do. 
2020-10-05 22:56:42 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Finished 
2020-10-05 22:56:42 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.14',
  'to' => '3.0.11',
)]
2020-10-05 22:56:43 [info] elementor::elementor_updater Started 
2020-10-05 22:56:43 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Start  
2020-10-05 22:56:43 [notice] General Settings already exist. nothing to do. 
2020-10-05 22:56:43 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Finished 
2020-10-05 22:56:43 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Start  
2020-10-05 22:56:43 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Finished 
2020-10-05 22:56:43 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Start  
2020-10-05 22:56:43 [notice] Custom colors already exist. nothing to do. 
2020-10-05 22:56:43 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Finished 
2020-10-05 22:56:43 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Start  
2020-10-05 22:56:43 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Finished 
2020-10-05 22:56:43 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.14',
  'to' => '3.0.11',
)]
2020-10-05 22:56:43 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.14',
  'to' => '3.0.11',
)]
2020-10-05 22:56:50 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.10.3',
  'to' => '3.0.5',
)]
2020-10-20 21:24:28 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.11',
  'to' => '3.0.12',
)]
2020-11-10 00:35:47 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.12',
  'to' => '3.0.13',
)]
2020-11-10 00:35:54 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.5',
  'to' => '3.0.6',
)]

PHP: showing 6 of 6PHP: 2020-10-06 15:23:46 [notice X 1][/nas/content/live/xxx/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-10-06 15:39:02 [notice X 7][/nas/content/live/xxx/wp-content/plugins/elementor-pro/modules/query-control/module.php::382] Undefined index: display [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-10-06 23:03:53 [error X 1][/nas/content/live/xxx/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::281] Uncaught Error: Call to a member function update_meta() on null in /nas/content/live/xxx/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:281
Stack trace:
#0 /nas/content/live/xxx/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(162): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;save_conditions(3940, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /nas/content/live/xxx/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /nas/content/live/xxx/wp-includes/class-wp-hook.php(287): Elementor\Core\Common\Modules\Ajax\Module-&gt;handle_ajax_request(&#039;&#039;)
#4 /nas/content/live/xxx/wp-includes/class-wp-hook.php(311): WP_Hook-&gt;apply_filters(&#039;&#039;, Array)
#5 /n [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-11-05 01:58:15 [notice X 2][/nas/content/live/xxx/wp-content/plugins/elementor-pro/modules/posts/skins/skin-content-base.php::248] Trying to get property &#039;ID&#039; of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-11-09 16:29:31 [notice X 13][/nas/content/live/xxx/wp-content/plugins/elementor/includes/base/controls-stack.php::1430] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-11-11 21:44:30 [notice X 2][/nas/content/live/xxx/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-image.php::40] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 9 of 9JS: 2020-10-06 15:39:21 [error X 1][https://xxx.wpengine.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \&quot;view5809\&quot;) has already been destroyed and cannot be used. 
JS: 2020-10-07 15:06:39 [error X 2][https://xxx.wpengine.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.11:2:466896] Cannot read property \&#039;html\&#039; of undefined 
JS: 2020-10-09 19:53:39 [error X 2][https://xxx.wpengine.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.11:2:474337] Cannot read property \&#039;document\&#039; of undefined 
JS: 2020-11-09 16:29:39 [error X 1][https://xxx.wpengine.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \&quot;view389\&quot;) has already been destroyed and cannot be used. 
JS: 2020-11-09 16:31:53 [error X 1][https://xxx.wpengine.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \&quot;view6828\&quot;) has already been destroyed and cannot be used. 
JS: 2020-11-10 15:18:20 [error X 2][https://xxx.wpengine.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \&quot;view394\&quot;) has already been destroyed and cannot be used. 
JS: 2020-11-10 15:23:38 [error X 1][https://xxx.wpengine.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \&quot;view3374\&quot;) has already been destroyed and cannot be used. 
JS: 2020-11-12 16:42:31 [error X 3][https://xxx.wpengine.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \&quot;view413\&quot;) has already been destroyed and cannot be used. 
JS: 2020-11-12 16:55:16 [error X 1][https://xxx.wpengine.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \&quot;view401\&quot;) has already been destroyed and cannot be used. 



```
</details>

**Comment by madebyreformat** [comment]
You've probably found a fix to this but it looks like Marionette framework not working with jQuery 3 which ships with latest WP update. If you install [Test jQuery Updates](https://wordpress.org/plugins/wp-jquery-update-test/) plugin you can downgrade jQuery to 1.12.4 which seems to still work fine with Elementor. There's info about how core updated shipped WP [here](https://make.wordpress.org/core/2020/06/29/updating-jquery-version-shipped-with-wordpress/) - it's not like them to just change things on updates and be like 'deal with it' (Gutenberg/Image Threshold etc)

**Comment by shilo-ey** [comment]
Hi @qwik3r 

Are you still experiencing this issue?

We addressed most of the jQuery update issues recently and this should be resolved as well.

Waiting for your reply,

Thanks

**Comment by qwik3r** [comment]
> Hi @qwik3r
> 
> Are you still experiencing this issue?
> 
> We addressed most of the jQuery update issues recently and this should be resolved as well.
> 
> Waiting for your reply,
> 
> Thanks

Not at the moment.

**Comment by qwik3r** [comment]
I take it back. I still see references to it on certain templates but it's not all the time. Very hard to figure out what is causing it. For instance I created a two different single product page templates, one had tons of backbone errors the other nothing. I'm trying to widdle it down to potential widget causing the conflict.

**Comment by julien-paris** [comment]
Hi, 
Am getting this error on a few of my pages
![image](https://user-images.githubusercontent.com/73740354/111064145-be7f7000-84b2-11eb-8a8e-387216c4d138.png)

**Comment by julien-paris** [comment]
Hi, any update on this?

**Comment by qwik3r** [comment]
Nope. They apparently don't care. And it's a real problem that exists. Not an isolated thing.

**Comment by shimonacarvalho** [comment]
Are you using async on JS for speed? I had this error on async, something about the order of the loads, and using defer helped.

**Comment by julien-paris** [comment]
Not sure. How did you "defer"? How do you achieve this?

**Comment by fippy** [comment]
Same problem here...

![image](https://user-images.githubusercontent.com/4941813/115121772-60abdf80-9fac-11eb-8c4f-17947b86a0c0.png)

**Comment by qwik3r** [comment]
Piece of junk plugin.

**Comment by chichille** [comment]
Same problem here with dynamic background-image/background-color.

The error only occurs in the editor. In preview or front-end mode the display is correct and i have no error in the console.
The error only occurs with background-image / background-color in a **column or section**.

Elementor free version 3.2.5 WP 5.7.2 and my own Dynamic Tags following [the rules of this page](https://developers.elementor.com/dynamic-tags/).
The plugin 'Enable jQuery Migrate Helper' give me this error for Elementor
**jQuery.holdReady is deprecated** in _http://127.0.0.1/eac/wp-content/plugins/elementor/assets/js/editor.min.js_

Here are the scenarios

![Github-1](https://user-images.githubusercontent.com/74245284/126781524-ba9e8007-d94c-4bcc-9bac-e9742e37c7c4.jpg)

I move the dynamic text to the first column and reload the editor.
The dynamic image/color are not displayed and other dynamic text are grayed

![Github-2](https://user-images.githubusercontent.com/74245284/126781557-78a0355b-763d-4eec-ba68-79b48d1c0cda.jpg)

I put the dynamic text on the widget and after reloading it is correct but I still have the error in the console

![Github-3](https://user-images.githubusercontent.com/74245284/126782456-98179e31-c408-48b0-a2fe-d16c983dec94.jpg)

And here is the code for ACF dynamic image i use

`
................

class Eac_Acf_Image extends Data_Tag {

	public function get_name() {
		return 'eac-addon-image-acf-values';
	}

	public function get_title() {
		return __('ACF Image', 'eac-components');
	}

	public function get_group() {
		return 'eac-acf-groupe';
	}

	public function get_categories() {
		return [
			TagsModule::IMAGE_CATEGORY,
		];
	}
    
	public function get_panel_template_setting_key() {
		return 'acf_image_key';
	}

	protected function register_controls() {
		$this->add_control('acf_image_key',
			[
				'label' => __('Champ', 'eac-components'),
				'type' => Controls_Manager::SELECT,
				'options' => Eac_Acf_Tags::get_acf_fields_options($this->get_acf_supported_fields()),
				'label_block' => true,
			]
		);
	}
	
	public function get_value(array $options = []) {
	    $field_value = '';
		$post_id = '';
		$key = $this->get_settings('acf_image_key');
		$data_image = ['id' => null, 'url' => ''];
		
		if(!empty($key)) {
			list($field_key, $meta_key) = explode('::', $key);
			
			// @since 1.8.4 Récupère l'ID de l'article Page d'Options
			if(class_exists(Eac_Acf_Options_Page::class)) {
				$id_page = Eac_Acf_Options_Page::get_options_page_id($field_key);
				if(!empty($id_page)) {
					$post_id = $id_page;
				}
			}
			
			// Affecte l'ID de l'article courant ou de la page d'options
			$post_id = $post_id === '' ? get_queried_object_id() : $post_id;
			
			// Récupère l'objet Field
			$field = get_field_object($field_key, $post_id);
			
			if($field && !empty($field['value'])) {
				// La valeur par défaut du champ (image)
				$field_value = $field['value'];
			
				switch($field['return_format']) {
					case 'array':
						$data_image = [
							'id' => $field_value['ID'],
							'url' => $field_value['url'],
						];
					break;
					case 'url':
						$data_image = [
							'id' => 0,
							'url' => $field_value,
						];
					break;
					case 'id':
						$src = wp_get_attachment_image_src($field_value, $field['preview_size']);
						$data_image = [
							'id' => $field_value,
							'url' => $src[0],
						];
					break;
				}
			} else {
				$data_image['url'] = Utils::get_placeholder_image_src();
			}
		}
		
		return $data_image;
	}
	
	protected function get_acf_supported_fields() {
		return ['image'];
	}
}
`

**Comment by pixelstorm** [comment]
This still seems to be an issue. It seems to be interfering with acf dynamic fields.

**Comment by taxbax** [comment]
Same issue here discovered when trying to use the hcaptcha plugin's Elementor Pro support. Lots of js min errors in console though.

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account.
