### ISSUE TITLE
Share-Widget-Icon XING: wrong share template in networkTemplates

### ISSUE THREAD

**Issue by nicmare** [elementor/elementor#13112]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Sharing a post with the build in share icon widget does not work any longer if you try to share through "xing" icon. The share url behind the link is outdated:
xing: 'https://www.xing.com/app/user?op=share&url={url}',
new pattern is:
xing: 'https://www.xing.com/spi/shares/new?url={url}',
see docs: https://dev.xing.com/plugins/share_button/docs

## Steps to reproduce

place share widget and activate XING icon

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v5.5.61-MariaDB-38.13
	PHP Version: 7.3.11
	PHP Max Input Vars: 1000
	PHP Max Post Size: 16M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5.3
	Site URL: https://softgarden.de
	Home URL: https://softgarden.de
	WP Multisite: No
	Max Upload Size: 11 GB
	Memory limit: 256M
	Permalink Structure: /blog/%postname%/
	Language: en-US
	Timezone: 2
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.3.0
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36

== Active Plugins ==
	Akismet Anti-Spam
		Version: 4.1.7
		Author: Automattic

	Elementor
		Version: 3.0.13
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.6
		Author: Elementor.com

	Elementor Softgarden
		Version: 1.0.0
		Author: Peak Ace AG

	Elementor Widgets NB
		Version: 1.0.0
		Author: NB

	Enable Media Replace
		Version: 3.5.0
		Author: ShortPixel

	Extras for Elementor
		Version: 2.2.42
		Author: Namogo

	Functions NB
		Version: 1.0
		Author: Nic Bugus

	Google Tag Manager for Wordpress
		Version: 1.11.5
		Author: Thomas Geiger

	Happy Elementor Addons
		Version: 2.15.0
		Author: weDevs

	Happy Elementor Addons Pro
		Version: 1.11.1
		Author: weDevs

	Header Footer Code Manager
		Version: 1.1.8
		Author: 99robots

	Polylang Connect for Elementor
		Version: 1.0.0
		Author: David Decker - DECKERWEB

	Polylang Pro
		Version: 2.8.4
		Author: WP SYNTEX

	Post Type Switcher
		Version: 3.2.0
		Author: John James Jacoby

	Really Simple SSL
		Version: 3.3.5
		Author: Really Simple Plugins

	Redirection
		Version: 4.9.2
		Author: John Godley

	Safe SVG
		Version: 1.9.9
		Author: Daryll Doyle

	Tuxedo Big File Uploads
		Version: 1.2
		Author: Trevor Anderson

	WP Migrate DB Pro
		Version: 1.9.13
		Author: Delicious Brains

	Yoast SEO
		Version: 15.3
		Author: Team Yoast


== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

	WP Migrate DB Pro Compatibility
		Version: 1.2
		Author: Delicious Brains


== Elements Usage ==
	
	archive : 12
		archive-posts : 2
		button : 1
		button-group : 1
		ha-breadcrumbs : 1
		heading : 12
		posts : 7
		search-form : 4
		spacer : 13
		text-editor : 8
		theme-archive-title : 1
	footer : 5
		button : 5
		divider : 2
		form : 2
		heading : 14
		html : 1
		image : 21
		nav-menu : 8
		posts : 2
		social-icons : 5
		spacer : 3
		text-editor : 19
		wpml-language-switcher : 1
	header : 11
		button : 7
		icon : 7
		image : 1
		jet-mega-menu : 1
		main-header : 6
		main-language-switcher : 1
		nav-menu : 5
		polylang-language-switcher : 5
		star-rating : 3
		theme-site-logo : 1
	page : 27
		button : 29
		divider : 5
		gallery : 15
		heading : 155
		html : 8
		icon-list : 28
		image : 113
		image-box : 2
		menu-anchor : 4
		nav-menu : 1
		posts : 1
		price-table : 19
		recruitingcalculator : 2
		spacer : 322
		tabs : 4
		testimonial-carousel : 4
		text-editor : 205
		tooltip-list : 3
		video : 5
	popup : 11
		button : 6
		heading : 51
		image : 3
		recruitingcalculator : 2
		recruitingcalculatorresults : 2
		spacer : 10
		text-editor : 8
	section : 34
		button : 15
		button-group : 1
		divider : 9
		gallery : 3
		global : 3
		heading : 49
		html : 3
		hubspotform : 1
		icon : 28
		icon-list : 2
		image : 10
		recruitingcalculator : 2
		recruitingcalculatorresults : 1
		search-form : 1
		slides : 2
		spacer : 43
		star-rating : 11
		tabs : 1
		text-editor : 35
		tooltip-list : 1
	single : 22
		author-box : 7
		button : 2
		button-group : 1
		gallery : 2
		heading : 52
		html : 8
		hubspotform : 1
		icon-list : 4
		image : 14
		post-comments : 5
		post-info : 8
		posts : 6
		search-form : 1
		share-buttons : 1
		spacer : 105
		table-of-contents : 1
		testimonial-carousel : 2
		text-editor : 47
		theme-post-content : 11
		theme-post-excerpt : 1
		theme-post-title : 10
	widget : 0
		author-box : 1
		gallery : 352
		main-filter : 11
		nav-menu : 1
	wp-post : 28
		button : 2
		call-to-action : 15
		ha-data-table : 1
		heading : 143
		html : 1
		image : 22
		menu-anchor : 42
		read-more : 8
		recruitingcalculator : 1
		recruitingcalculatorresults : 1
		spacer : 37
		text-editor : 237
		video : 2
	wp-page : 200
		alert : 2
		animated-headline : 2
		archive-posts : 1
		blockquote : 14
		button : 119
		button-group : 1
		call-to-action : 32
		circle-progress : 1
		counter : 1
		divider : 22
		ee-inline-svg : -4
		flip-box : 2
		gallery : -18
		global : 5
		ha-animated-text : 1
		ha-fun-factor : 3
		ha-logo-grid : 5
		ha-post-grid : 4
		ha-timeline : 1
		ha-toggle : 1
		heading : 396
		html : -41
		html5-video : 6
		hubspotform : 48
		icon : 99
		icon-box : 15
		icon-list : 5
		image : 49
		image-box : 10
		image-carousel : 2
		inline-editing-example : 1
		main-download : 1
		main-filter : 1
		main-navigation : 1
		main-slider : 1
		main-timeline : 3
		main-tooltip-col : 4
		main-video : 1
		media-carousel : 2
		menu-anchor : 28
		posts : 15
		price-table : 10
		progress : 1
		recruitingcalculator : 7
		recruitingcalculatorresults : 6
		search-form : 1
		slides : 7
		spacer : -74
		star-rating : 28
		testimonial-carousel : 1
		text-editor : 712
		toggle : 6
		tooltip-list : 2
		video : -6
		wp-widget-pages : 3
		wp-widget-text : 3
	search-results : 1
		archive-posts : 1
		heading : 1
		search-form : 1
		spacer : 2


== Log ==
	
PHP: showing 11 of 11PHP: 2020-10-15 11:41:58 [error X 2][/var/www/vhosts/softgarden.io/softgarden.io/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::281] Uncaught Error: Call to a member function update_meta() on null in /var/www/vhosts/softgarden.io/softgarden.io/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:281
Stack trace:
#0 /var/www/vhosts/softgarden.io/softgarden.io/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(162): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(41279, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /var/www/vhosts/softgarden.io/softgarden.io/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /var/www/vhosts/softgarden.io/softgarden.io/wp-includes/class-wp-hook.php(287): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /var/www/vhosts/softgarden.io/softgarden.io/wp-i [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-10-20 14:47:33 [notice X 89][/var/www/vhosts/softgarden.io/softgarden.io/wp-content/plugins/elementor/includes/managers/image.php::33] Undefined index: size [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-10-21 11:33:16 [notice X 1320][/var/www/vhosts/softgarden.io/softgarden.io/wp-content/plugins/elementor/includes/template-library/sources/local.php::589] Trying to get property 'display_name' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-10-21 14:41:24 [warning X 2][/var/www/vhosts/softgarden.io/softgarden.io/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::101] file_get_contents(/var/www/vhosts/softgarden.io/softgarden.io/wp-content/uploads/2018/12/Element-33.svg): failed to open stream: No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-10-21 16:14:21 [warning X 1][/var/www/vhosts/softgarden.io/softgarden.io/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::101] file_get_contents(/var/www/vhosts/softgarden.io/softgarden.io/wp-content/uploads/2018/09/logo-color-grohe.svg): failed to open stream: No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-10-21 16:14:38 [warning X 1][/var/www/vhosts/softgarden.io/softgarden.io/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::101] file_get_contents(/var/www/vhosts/softgarden.io/softgarden.io/wp-content/uploads/2018/09/logo-color-kia.svg): failed to open stream: No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-11-03 14:19:02 [notice X 39][/var/www/vhosts/softgarden.io/softgarden.io/wp-content/plugins/elementor-pro/modules/forms/classes/form-record.php::215] Undefined index: field_label [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-11-09 19:23:55 [warning X 1][/var/www/vhosts/softgarden.io/softgarden.io/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::101] file_get_contents(/var/www/vhosts/softgarden.io/softgarden.io/wp-content/uploads/2018/12/Element-38.svg): failed to open stream: No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-11-10 14:45:29 [notice X 4][/var/www/vhosts/softgarden.io/softgarden.io/wp-content/plugins/elementor-pro/core/utils.php::217] Trying to get property 'post_author' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-11-10 18:26:54 [notice X 1][/var/www/vhosts/softgarden.io/softgarden.io/wp-content/plugins/elementor/includes/frontend.php::1200] Trying to get property 'post_excerpt' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-11-18 14:04:03 [notice X 4][/var/www/vhosts/softgarden.io/softgarden.io/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 15 of 15JS: 2020-10-15 15:21:38 [error X 7][https://softgarden.de/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.11:2:474337] Cannot read property \'document\' of undefined 
JS: 2020-10-21 10:56:46 [error X 40][https://pl.softgarden.io/wp-admin/post.php?post=55275&action=elementor:2:3] hbspt is not defined 
JS: 2020-10-21 12:13:52 [error X 8][https://softgarden.de/wp-content/plugins/elementor/assets/js/editor-document.min.js?ver=3.0.12:2:6233] container or containers are required. 
JS: 2020-10-21 12:49:14 [error X 1][https://softgarden.de/wp-includes/js/jquery/jquery.js?ver=1.12.4-wp:4:11101] b.toLowerCase is not a function 
JS: 2020-10-21 13:13:21 [error X 1][https://softgarden.de/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.0.12:2:54754] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `ha-animated-text` got as `sticky_offset` value. Expected array or object.',
)]
JS: 2020-10-21 13:13:21 [error X 1][https://softgarden.de/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.0.12:2:54754] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `ha-timeline` got as `sticky_offset` value. Expected array or object.',
)]
JS: 2020-10-22 06:45:55 [error X 8][https://softgarden.de/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.12:2:230408] Blocked a frame with origin \"https://softgarden.de\" from accessing a cross-origin frame. Protocols, domains, and ports must match. 
JS: 2020-10-22 06:56:46 [error X 1][https://softgarden.io/wp-content/plugins/happy-elementor-addons-pro/assets/admin/js/marvin-new.min.js?ver=1.10.0:1:5204] undefined is not an object (evaluating \'this.$.get\') 
JS: 2020-10-22 08:34:13 [error X 4][https://pl.softgarden.io/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.12:2:204614] Cannot read property \'data\' of undefined 
JS: 2020-10-26 15:03:10 [error X 12][https://softgarden.de/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.0.12:2:62775] e.get is not a function 
JS: 2020-10-26 15:03:10 [error X 6][https://softgarden.de/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.12:2:478648] Cannot read property \'isDesignable\' of undefined 
JS: 2020-10-26 15:07:16 [error X 10][https://softgarden.de/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.12:2:475202] Cannot read property \'isEditable\' of undefined 
JS: 2020-11-02 10:58:29 [error X 1][https://softgarden.de/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view14464\") has already been destroyed and cannot be used. 
JS: 2020-11-02 13:12:29 [error X 11][https://softgarden.io/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.12:2:230409] Blocked a frame with origin \"https://softgarden.io\" from accessing a cross-origin frame. 
JS: 2020-11-06 11:04:32 [error X 43][https://softgarden.de/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.13:2:230494] Blocked a frame with origin \"https://softgarden.de\" from accessing a cross-origin frame. 

Log: showing 16 of 162020-10-21 11:33:13 [info] elementor::elementor_updater Started 
2020-10-21 11:33:13 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Start  
2020-10-21 11:33:13 [notice] General Settings already exist. nothing to do. 
2020-10-21 11:33:13 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Finished 
2020-10-21 11:33:13 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Start  
2020-10-21 11:33:13 [notice] System colors already exist. nothing to do. 
2020-10-21 11:33:13 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Finished 
2020-10-21 11:33:13 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Start  
2020-10-21 11:33:13 [notice] Custom colors already exist. nothing to do. 
2020-10-21 11:33:13 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Finished 
2020-10-21 11:33:13 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Start  
2020-10-21 11:33:13 [notice] System typography already exist. nothing to do. 
2020-10-21 11:33:13 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Finished 
2020-10-21 11:33:13 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.11',
  'to' => '3.0.12',
)]
2020-11-05 10:22:03 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.12',
  'to' => '3.0.13',
)]
2020-11-05 10:22:03 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.5',
  'to' => '3.0.6',
)]
```
</details>

**Comment by arielk** [comment]
Fix: https://github.com/arielk/elementor/commit/8259104b3d67cc7b9c415d414e69ffe29b53b550
