### ISSUE TITLE
Posts Widget Pagination Not Work On Tablet and Mobile

### ISSUE THREAD

**Issue by LeeChunHao2000** [elementor/elementor#13132]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
There is an issue with Pagination in the Posts Widget.

Only the current page shows up on mobile & tablet in the pagination area. So if you are in Page1, it does not show any link for Page 2 on mobile/tablet - but shows all pages on the desktop

## Steps to reproduce
Add a Posts Widget -> Content -> Pagination
![1606108287362](https://user-images.githubusercontent.com/64617939/99930860-921dd780-2d8d-11eb-98e0-fceea4f49685.jpg)

Desktop display:
![1606108489425](https://user-images.githubusercontent.com/64617939/99930990-ec1e9d00-2d8d-11eb-82c0-018af4cb77e9.jpg)

Tablet and Mobile display:
![1606108563476](https://user-images.githubusercontent.com/64617939/99931030-0eb0b600-2d8e-11eb-8d9e-010bd1db1619.jpg)

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.26-29
	PHP Version: 7.3.24
	PHP Max Input Vars: 3000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5.3
	Site URL: https://www.grenade.tw
	Home URL: https://www.grenade.tw
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 768M
	Permalink Structure: /%category%/%postname%/
	Language: zh-TW
	Timezone: 8
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Seventeen
	Version: 2.4
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: zh_TW
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0

== Active Plugins ==
	All In One SEO Pack
		Version: 3.7.1
		Author: All in One SEO Team

	Code Snippets
		Version: 2.14.0
		Author: Code Snippets Pro

	Code Syntax Block
		Version: 2.0.1
		Author: Marcus Kazmierczak

	Cool Tag Cloud
		Version: 2.21
		Author: WPKube

	Elementor
		Version: 3.0.13
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.6
		Author: Elementor.com

	FileBird Lite
		Version: 4.1
		Author: Ninja Team

	Flexy Breadcrumb
		Version: 1.1.3
		Author: PressTigers

	GA Google Analytics
		Version: 20201120
		Author: Jeff Starr

	HT Mega - Absolute Addons for Elementor Page Builder
		Version: 1.4.7
		Author: HasThemes

	Jetpack by WordPress.com
		Version: 9.1
		Author: Automattic

	Really Simple SSL
		Version: 3.3.5
		Author: Really Simple Plugins

	Share Buttons by AddThis
		Version: 6.2.6
		Author: The AddThis Team

	Simple Tags
		Version: 2.62
		Author: WebFactory Ltd

	Timeline Widget Addon For Elementor
		Version: 1.2.1
		Author: Cool Plugins

	Webcraftic Clearfy – WordPress optimization plugin
		Version: 1.8.0
		Author: Webcraftic <wordpress.webraftic@gmail.com>

	Webcraftic Robin image optimizer
		Version: 1.4.6
		Author: Webcraftic <wordpress.webraftic@gmail.com>

	WP Extended Search
		Version: 1.3.1
		Author: 5um17

	WPFront Scroll Top
		Version: 2.0.2
		Author: Syam Mohan

	WP Statistics
		Version: 12.6.13
		Author: VeronaLabs

	WP User Avatar
		Version: 2.2.7
		Author: ProfilePress


== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com


== Elements Usage ==
	
	archive : 2
		divider : 2
		facebook-page : 2
		heading : 7
		image : 2
		posts : 4
		search-form : 2
		share-buttons : 2
		theme-archive-title : 1
		wp-widget-cool_tag_cloud : 2
	footer : 1
		form : 1
		heading : 2
		image : 1
		social-icons : 1
		text-editor : 1
	header : 1
		image : 1
		nav-menu : 1
		social-icons : 1
	page : 1
		divider : 1
		heading : 2
		image : 2
		nav-menu : 1
		search-form : 1
		social-icons : 2
		spacer : 4
		text-editor : 1
	section : 2
		facebook-page : 1
		heading : 4
		html : 1
		image : 1
		posts : 2
		search-form : 1
		share-buttons : 1
		spacer : 1
		wp-widget-cool_tag_cloud : 1
	single : 1
		divider : 1
		heading : 4
		search-form : 1
	wp-page : 13
		button : 3
		counter : 4
		divider : 29
		facebook-page : 9
		form : 2
		heading : 70
		html : 9
		image : 52
		posts : 19
		search-form : 9
		share-buttons : 8
		slides : 1
		spacer : 10
		text-editor : 30
		timeline-widget-addon : 1
		wp-widget-cool_tag_cloud : 9


== Log ==
	
JS: showing 11 of 11JS: 2020-06-10 10:01:48 [error X 44][https://www.grenade.tw/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.9.11:31:160248] elementorFrontend.elements.window.jQuery is not a function 
JS: 2020-06-10 10:01:48 [error X 19][https://www.grenade.tw/wp-includes/js/jquery/jquery.js?ver=1.12.4-wp:4:30645] Cannot read property \'pageYOffset\' of undefined 
JS: 2020-07-23 05:47:36 [error X 43][https://www.grenade.tw/wp-content/themes/twentyseventeen/assets/js/global.js?ver=20190121:124:3] sidebarPos is undefined 
JS: 2020-07-24 07:33:02 [error X 3][https://www.grenade.tw/wp-content/plugins/elementor/assets/lib/e-select2/js/e-select2.full.min.js?ver=4.0.6-rc.1:1:74232] e is undefined 
JS: 2020-07-25 11:36:44 [error X 1][https://www.grenade.tw/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view3316\") has already been destroyed and cannot be used. 
JS: 2020-10-06 08:49:24 [error X 6][https://www.grenade.tw/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.11:2:474322] this.container is undefined 
JS: 2020-10-16 02:37:52 [error X 1][https://www.grenade.tw/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view1507\") has already been destroyed and cannot be used. 
JS: 2020-10-16 06:47:47 [error X 1][https://www.grenade.tw/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view2061\") has already been destroyed and cannot be used. 
JS: 2020-10-26 05:41:44 [error X 2][https://www.grenade.tw/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.12:2:474643] Cannot read property \'document\' of undefined 
JS: 2020-11-04 05:09:57 [error X 1][https://www.grenade.tw/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view3260\") has already been destroyed and cannot be used. 
JS: 2020-11-09 08:08:49 [error X 4][https://www.grenade.tw/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.0.13:2:54754] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got as `menu_link` value. Expected array or object.',
)]

Log: showing 20 of 282020-09-12 22:13:32 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Finished 
2020-09-12 22:13:32 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Start  
2020-09-12 22:13:32 [notice] System colors are disabled. nothing to do. 
2020-09-12 22:13:32 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Finished 
2020-09-12 22:13:32 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Start  
2020-09-12 22:13:32 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.14',
  'to' => '3.0.7',
)]
2020-09-12 22:13:32 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Finished 
2020-09-12 22:13:32 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Start  
2020-09-12 22:13:32 [notice] System typography is disabled. nothing to do. 
2020-09-12 22:13:32 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Finished 
2020-09-12 22:13:32 [info] Elementor/Upgrades - _v_3_0_5_re_move_space_between_widgets_to_kit Start  
2020-09-12 22:13:32 [info] Elementor/Upgrades - _v_3_0_5_re_move_space_between_widgets_to_kit Finished 
2020-09-12 22:13:32 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.14',
  'to' => '3.0.7',
)]
2020-09-17 11:59:50 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.7',
  'to' => '3.0.8.1',
)]
2020-09-17 11:59:50 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro 專業版',
  'from' => '2.10.3',
  'to' => '3.0.4',
)]
2020-10-01 20:36:02 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.8.1',
  'to' => '3.0.11',
)]
2020-10-12 19:06:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro 專業版',
  'from' => '3.0.4',
  'to' => '3.0.5',
)]
2020-10-21 16:05:50 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.11',
  'to' => '3.0.12',
)]
2020-11-05 04:31:45 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.12',
  'to' => '3.0.13',
)]
2020-11-19 00:45:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro 專業版',
  'from' => '3.0.5',
  'to' => '3.0.6',
)]

PHP: showing 4 of 4PHP: 2020-07-24 15:33:03 [notice X 6][/home/customer/www/grenade.tw/public_html/wp-content/plugins/elementor-pro/modules/query-control/module.php::382] Undefined index: display [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-07-25 19:37:35 [error X 3][/home/customer/www/grenade.tw/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::259] Uncaught Error: Call to a member function update_meta() on bool in /home/customer/www/grenade.tw/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:259
Stack trace:
#0 /home/customer/www/grenade.tw/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(180): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/customer/www/grenade.tw/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/customer/www/grenade.tw/public_html/wp-includes/class-wp-hook.php(287): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/customer/www/grenade.tw/public_html/wp-includes/cla [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-07-25 19:48:01 [notice X 4][/home/customer/www/grenade.tw/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-08-05 15:01:31 [notice X 3][/home/customer/www/grenade.tw/public_html/wp-content/plugins/elementor/core/admin/admin-notices.php::498] Trying to get property 'id' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
```
</details>

**Comment by shilo-ey** [comment]
Hi @LeeChunHao2000 

Thanks for your feedback

You have a CSS rule in your site that hides the pagination in mobiles that derive from your theme. consider switching to Hello theme

![image](https://user-images.githubusercontent.com/45009641/99937300-12344500-2d6e-11eb-9c99-8b9f471122f8.png)


Thanks
