### ISSUE TITLE
PHP 8.0.0 NTS Throws PHP Fatal Error dynamic-tags/manager.php

### ISSUE THREAD

**Issue by DeveloperWil** [elementor/elementor#13394]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description
Installed PHP 8.0.0 NTS on Windows 10.
Elementor throws an error.
PHP Fatal error:  Uncaught Error: Unknown named parameter $id in D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-content\plugins\elementor\core\dynamic-tags\manager.php:123

## Steps to reproduce
Install PHP 8.0.0 NTS on Windows 10
Running PHP as a service c:\php8-NTS\php-cgi.exe -b127.0.0.1:9000 -cc:\php8-NTS\php.ini
Navigate to a local WordPress site running current Elementor core plugin in DEBUG mode
Fatal error reported in debug.log

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
Windows 10 Home
PHP 8.0.0 NTS
Windows 5.6
Elementor 3.0.15
Elementor Pro 3.0.5
```
					
== Server Environment ==
	Operating System: WINNT
	Software: nginx/1.18.0
	MySQL version: mariadb.org binary distribution v10.5.4
	PHP Version: 7.4.7
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.6
	Site URL: http://zpdbranding.local
	Home URL: http://zpdbranding.local
	WP Multisite: No
	Max Upload Size: 2 MB
	Memory limit: 256M
	Permalink Structure: /blog/%year%/%monthnum%/%day%/%postname%/
	Language: en-AU
	Timezone: Australia/Sydney
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor
	Version: 2.3.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_AU
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 5.9.1
		Author: Elliot Condon

	Change Product Author for WooCommerce
		Version: 1.0.0
		Author: Wil Brown @DeveloperWil

	Elementor
		Version: 3.0.15
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.5
		Author: Elementor.com

	Who Is Logged Into WordPress?
		Version: 1.0.0
		Author: Wil Brown @DeveloperWil

	WooCommerce
		Version: 4.5.2
		Author: Automattic

	WooCommerce Stripe Gateway
		Version: 4.5.2
		Author: WooCommerce


== Must-Use Plugins ==
	add-custom-view.php
		Version: 
		Author: 


== Elements Usage ==
	
	header : 1
		nav-menu : 1
		theme-site-logo : 1
	wp-page : 1
		form : 1


== Log ==
	
Log: showing 2 of 22020-10-01 04:27:07 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.10',
  'to' => '3.0.11',
)]
2020-12-24 12:31:55 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.11',
  'to' => '3.0.15',
)]

PHP: showing 1 of 1PHP: 2020-12-24 12:22:01 [error X 2][D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-content\plugins\elementor\core\dynamic-tags\manager.php::123] Uncaught Error: Unknown named parameter $id in D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-content\plugins\elementor\core\dynamic-tags\manager.php:123
Stack trace:
#0 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-content\plugins\elementor\core\dynamic-tags\manager.php(123): call_user_func_array(Array, Array)
#1 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-content\plugins\elementor\core\dynamic-tags\manager.php(84): Elementor\Core\DynamicTags\Manager->parse_tag_text('[elementor-tag ...', Array, Array)
#2 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-content\plugins\elementor\includes\controls\base-data.php(81): Elementor\Core\DynamicTags\Manager->parse_tags_text('[elementor-tag ...', Array, Array)
#3 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-content\plugins\elementor\includes\base\controls-stack.php(1179): Elementor\Base_Data_Control->parse_tags('[elementor-tag ...', Array)
#4 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-content\plugins\elementor\includes\base\controls-stack.php(1030): Elementor\Controls_Stack->parse_dynamic_settings(Array)
#5 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-content\plugins\elementor\core\files\css\post.php(296): Elementor\Controls_Stack->get_parsed_dynamic_settings()
#6 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-content\plugins\elementor\core\dynamic-tags\dynamic-css.php(32): Elementor\Core\Files\CSS\Post->render_styles(Object(ElementorPro\Modules\ThemeBuilder\Widgets\Site_Logo))
#7 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-content\plugins\elementor\core\dynamic-tags\dynamic-css.php(36): Elementor\Core\DynamicTags\Dynamic_CSS->render_styles(Object(ElementorPro\Modules\ThemeBuilder\Widgets\Site_Logo))
#8 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-content\plugins\elementor\core\dynamic-tags\dynamic-css.php(36): Elementor\Core\DynamicTags\Dynamic_CSS->render_styles(Object(Elementor\Element_Column))
#9 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-content\plugins\elementor\core\files\css\post.php(178): Elementor\Core\DynamicTags\Dynamic_CSS->render_styles(Object(Elementor\Element_Section))
#10 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-content\plugins\elementor\core\files\css\base.php(617): Elementor\Core\Files\CSS\Post->render_css()
#11 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-content\plugins\elementor\core\files\base.php(166): Elementor\Core\Files\CSS\Base->parse_content()
#12 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-content\plugins\elementor\core\files\css\base.php(131): Elementor\Core\Files\Base->update_file()
#13 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-content\plugins\elementor\core\files\css\base.php(207): Elementor\Core\Files\CSS\Base->update()
#14 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-content\plugins\elementor\core\files\css\post.php(199): Elementor\Core\Files\CSS\Base->enqueue()
#15 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-content\plugins\elementor\core\dynamic-tags\manager.php(438): Elementor\Core\Files\CSS\Post->enqueue()
#16 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-includes\class-wp-hook.php(287): Elementor\Core\DynamicTags\Manager->after_enqueue_post_css(Object(Elementor\Core\DynamicTags\Dynamic_CSS))
#17 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-includes\class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#18 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-includes\plugin.php(484): WP_Hook->do_action(Array)
#19 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-content\plugins\elementor\core\files\css\base.php(254): do_action('elementor/css-f...', Object(Elementor\Core\Files\CSS\Post))
#20 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-content\plugins\elementor\core\files\css\post.php(199): Elementor\Core\Files\CSS\Base->enqueue()
#21 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-content\plugins\elementor-pro\modules\theme-builder\classes\locations-manager.php(92): Elementor\Core\Files\CSS\Post->enqueue()
#22 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-includes\class-wp-hook.php(287): ElementorPro\Modules\ThemeBuilder\Classes\Locations_Manager->enqueue_styles('')
#23 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-includes\class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#24 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-includes\plugin.php(484): WP_Hook->do_action(Array)
#25 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-includes\script-loader.php(2004): do_action('wp_enqueue_scri...')
#26 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-includes\class-wp-hook.php(287): wp_enqueue_scripts('')
#27 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-includes\class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#28 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-includes\plugin.php(484): WP_Hook->do_action(Array)
#29 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-includes\general-template.php(3005): do_action('wp_head')
#30 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-content\themes\hello-elementor\header.php(21): wp_head()
#31 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-includes\template.php(730): require_once('D:\\Users\\Wil\\Dr...')
#32 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-includes\template.php(676): load_template('D:\\Users\\Wil\\Dr...', true, Array)
#33 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-includes\general-template.php(48): locate_template(Array, true, true, Array)
#34 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-content\themes\hello-elementor\index.php(15): get_header()
#35 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-includes\template-loader.php(106): include('D:\\Users\\Wil\\Dr...')
#36 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-blog-header.php(19): require_once('D:\\Users\\Wil\\Dr...')
#37 d:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\index.php(17): require('D:\\Users\\Wil\\Dr...')
#38 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]


				
```

PHP Fatal error:  Uncaught Error: Unknown named parameter $id in D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-content\plugins\elementor\core\dynamic-tags\manager.php:123
Stack trace:
#0 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-content\plugins\elementor\core\dynamic-tags\manager.php(123): call_user_func_array(Array, Array)
#1 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-content\plugins\elementor\core\dynamic-tags\manager.php(84): Elementor\Core\DynamicTags\Manager->parse_tag_text('[elementor-tag ...', Array, Array)
#2 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-content\plugins\elementor\includes\controls\base-data.php(81): Elementor\Core\DynamicTags\Manager->parse_tags_text('[elementor-tag ...', Array, Array)
#3 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-content\plugins\elementor\includes\base\controls-stack.php(1179): Elementor\Base_Data_Control->parse_tags('[elementor-tag ...', Array)
#4 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-content\plugins\elementor\includes\base\controls-stack.php(1030): Elementor\Controls_Stack->parse_dynamic_settings(Array)
#5 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-content\plugins\elementor\core\files\css\post.php(296): Elementor\Controls_Stack->get_parsed_dynamic_settings()
#6 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-content\plugins\elementor\core\dynamic-tags\dynamic-css.php(32): Elementor\Core\Files\CSS\Post->render_styles(Object(ElementorPro\Modules\ThemeBuilder\Widgets\Site_Logo))
#7 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-content\plugins\elementor\core\dynamic-tags\dynamic-css.php(36): Elementor\Core\DynamicTags\Dynamic_CSS->render_styles(Object(ElementorPro\Modules\ThemeBuilder\Widgets\Site_Logo))
#8 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-content\plugins\elementor\core\dynamic-tags\dynamic-css.php(36): Elementor\Core\DynamicTags\Dynamic_CSS->render_styles(Object(Elementor\Element_Column))
#9 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-content\plugins\elementor\core\files\css\post.php(178): Elementor\Core\DynamicTags\Dynamic_CSS->render_styles(Object(Elementor\Element_Section))
#10 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-content\plugins\elementor\core\files\css\base.php(617): Elementor\Core\Files\CSS\Post->render_css()
#11 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-content\plugins\elementor\core\files\base.php(166): Elementor\Core\Files\CSS\Base->parse_content()
#12 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-content\plugins\elementor\core\files\css\base.php(131): Elementor\Core\Files\Base->update_file()
#13 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-content\plugins\elementor\core\files\css\base.php(207): Elementor\Core\Files\CSS\Base->update()
#14 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-content\plugins\elementor\core\files\css\post.php(199): Elementor\Core\Files\CSS\Base->enqueue()
#15 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-content\plugins\elementor\core\dynamic-tags\manager.php(438): Elementor\Core\Files\CSS\Post->enqueue()
#16 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-includes\class-wp-hook.php(287): Elementor\Core\DynamicTags\Manager->after_enqueue_post_css(Object(Elementor\Core\DynamicTags\Dynamic_CSS))
#17 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-includes\class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#18 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-includes\plugin.php(484): WP_Hook->do_action(Array)
#19 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-content\plugins\elementor\core\files\css\base.php(254): do_action('elementor/css-f...', Object(Elementor\Core\Files\CSS\Post))
#20 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-content\plugins\elementor\core\files\css\post.php(199): Elementor\Core\Files\CSS\Base->enqueue()
#21 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-content\plugins\elementor-pro\modules\theme-builder\classes\locations-manager.php(92): Elementor\Core\Files\CSS\Post->enqueue()
#22 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-includes\class-wp-hook.php(287): ElementorPro\Modules\ThemeBuilder\Classes\Locations_Manager->enqueue_styles('')
#23 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-includes\class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#24 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-includes\plugin.php(484): WP_Hook->do_action(Array)
#25 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-includes\script-loader.php(2004): do_action('wp_enqueue_scri...')
#26 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-includes\class-wp-hook.php(287): wp_enqueue_scripts('')
#27 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-includes\class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#28 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-includes\plugin.php(484): WP_Hook->do_action(Array)
#29 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-includes\general-template.php(3005): do_action('wp_head')
#30 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-content\themes\hello-elementor\header.php(21): wp_head()
#31 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-includes\template.php(730): require_once('D:\\Users\\Wil\\Dr...')
#32 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-includes\template.php(676): load_template('D:\\Users\\Wil\\Dr...', true, Array)
#33 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-includes\general-template.php(48): locate_template(Array, true, true, Array)
#34 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-content\themes\hello-elementor\index.php(15): get_header()
#35 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-includes\template-loader.php(106): include('D:\\Users\\Wil\\Dr...')
#36 D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-blog-header.php(19): require_once('D:\\Users\\Wil\\Dr...')
#37 d:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\index.php(17): require('D:\\Users\\Wil\\Dr...')
#38 {main}
  thrown in D:\Users\Wil\Dropbox\Projects\Github\zpdbranding\www\wp-content\plugins\elementor\core\dynamic-tags\manager.php on line 123

</details>

**Comment by DeveloperWil** [comment]
Closing issue - the problem was resolved in Elementor 3.0.15 plugin - I had 3.0.14.
