### ISSUE TITLE
Large Microsoft Azure logo in Text Editor element when Microsoft Azure Storage plugin is active

### ISSUE THREAD

**Issue by brianyerkes** [elementor/elementor#13468]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description

With the "Microsoft Azure Storage for WordPress" plugin active, there is a large Azure logo when editing in Elementor with the "Text Editor" element. Screenshot here: https://www.dropbox.com/s/hwb44wodnbkwqko/azure.png?dl=0  (and here's how it should look - this is the classic WordPress editor:  https://www.dropbox.com/s/aavihlvighnbzqw/azure-2.png?dl=0 )

## Steps to reproduce

- Install and activate the Microsoft Azure Storage for WordPress" plugin
- Install and activate Elementor
- Edit a page or post with Elementor, and add a "Text Editor" element.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ x] This bug happens with a default WordPress theme active.
- [x ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.7.29
	PHP Version: 7.4.9
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.6
	Site URL: https://test.hacfm.org
	Home URL: https://test.hacfm.org
	WP Multisite: No
	Max Upload Size: 2 MB
	Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: HACFM Child
	Version: 1.0.1
	Author: 
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.3.0
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 5.9.3
		Author: Elliot Condon

	All-in-One WP Migration
		Version: 6.77
		Author: ServMask

	BackWPup
		Version: 3.8.0
		Author: Inpsyde GmbH

	Classic Editor
		Version: 1.6
		Author: WordPress Contributors

	Elementor
		Version: 3.0.15
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.9
		Author: Elementor.com

	Email Encoder - Protect Email Addresses
		Version: 2.1.0
		Author: Ironikus

	Essential Addons for Elementor
		Version: 4.3.9
		Author: WPDeveloper

	Essential Addons for Elementor - Pro
		Version: 4.2.3
		Author: WPDeveloper

	Events Manager
		Version: 5.9.8.1
		Author: Marcus Sykes

	Gravity Forms
		Version: 2.4.22
		Author: Gravity Forms

	Make Column Clickable Elementor
		Version: 1.3.1
		Author: Fernando Acosta

	Microsoft Azure Storage for WordPress
		Version: 4.3.1
		Author: 10up, Microsoft Open Technologies

	Slider Revolution
		Version: 6.3.4
		Author: ThemePunch

	WCAG 2.0 form fields for Gravity Forms
		Version: 1.7.2
		Author: Adrian Gordon

	WP-PageNavi
		Version: 2.93.3
		Author: Lester 'GaMerZ' Chan

	WP Fastest Cache
		Version: 0.9.1.3
		Author: Emre Vona

	WP Fastest Cache Premium
		Version: 1.5.9
		Author: Emre Vona

	WP FullCalendar
		Version: 1.3.1
		Author: Marcus Sykes


== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com


== Elements Usage ==
	
	archive : 2
		eael-cta-box : 2
		heading : 4
		shortcode : 4
		theme-archive-title : 1
	footer : 1
		button : 4
		heading : 5
		icon : 2
		image : 1
		nav-menu : 5
		text-editor : 3
	header : 4
		eael-lightbox : 2
		image : 2
		nav-menu : 2
		shortcode : 4
	page : 19
		alert : 2
		button : 9
		divider : 9
		eael-advanced-menu : 3
		eael-cta-box : 23
		eael-dual-color-header : 12
		eael-info-box : 2
		eael-offcanvas : 1
		global : 3
		heading : 77
		image : 15
		menu-anchor : 9
		shortcode : 5
		text-editor : 99
	section : 11
		button : 1
		eael-advanced-data-table : 1
		eael-dual-color-header : 1
		eael-lightbox : 1
		global : 1
		heading : 15
		image : 7
		nav-menu : 1
		shortcode : 4
		spacer : 1
		text-editor : 58
	single : 1
		divider : 1
		eael-cta-box : 3
		heading : 2
		post-info : 3
		shortcode : 1
		text-editor : 2
	widget : 0
		eael-cta-box : 11
		eael-dual-color-header : 22
		eael-offcanvas : 7
		icon-list : 132
		nav-menu : 120
	wp-page : 37
		alert : 3
		button : 12
		call-to-action : 11
		divider : 28
		eael-advanced-data-table : 1
		eael-advanced-menu : 5
		eael-cta-box : 34
		eael-dual-color-header : 15
		eael-offcanvas : 2
		global : 13
		heading : 145
		image : 46
		menu-anchor : 25
		shortcode : 8
		slider_revolution : 1
		spacer : 1
		text-editor : 213
		toggle : 5
	single-post : 1
		eael-cta-box : 1
		heading : 3
		shortcode : 1
		text-editor : 2
		theme-post-content : 1
	search-results : 1
		eael-cta-box : 3
		heading : 2
		shortcode : 2


== Log ==
	
JS: showing 17 of 17JS: 2020-07-06 14:32:14 [error X 7][http://3.95.76.22/hacfm.org/wp-admin/post.php?post=23&action=elementor#:12:5] Unexpected token \'<\' 
JS: 2020-08-26 17:46:38 [error X 3][http://3.95.76.22/hacfm.org/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=2.10.2:2:7209] Cannot read property \'model\' of null 
JS: 2020-08-26 18:58:38 [error X 1][http://3.95.76.22/hacfm.org/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.2:2:133988] Cannot read property \'model\' of undefined 
JS: 2020-08-26 18:59:09 [error X 2][http://3.95.76.22/hacfm.org/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.2:2:470162] Cannot read property \'document\' of undefined 
JS: 2020-09-03 18:22:56 [error X 5][http://3.95.76.22/hacfm.org/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view205\") has already been destroyed and cannot be used. 
JS: 2020-09-03 18:24:02 [error X 4][http://3.95.76.22/hacfm.org/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view4995\") has already been destroyed and cannot be used. 
JS: 2020-09-03 18:25:47 [error X 3][http://3.95.76.22/hacfm.org/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view6249\") has already been destroyed and cannot be used. 
JS: 2020-09-03 18:25:55 [error X 2][http://3.95.76.22/hacfm.org/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view7420\") has already been destroyed and cannot be used. 
JS: 2020-09-03 18:26:17 [error X 1][http://3.95.76.22/hacfm.org/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view8356\") has already been destroyed and cannot be used. 
JS: 2020-09-03 23:45:22 [error X 1][http://3.95.76.22/hacfm.org/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view271\") has already been destroyed and cannot be used. 
JS: 2020-09-30 13:22:28 [error X 1][http://3.95.76.22/hacfm.org/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view4062\") has already been destroyed and cannot be used. 
JS: 2020-10-02 19:37:10 [error X 1][http://3.95.76.22/hacfm.org/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.9.14:23:102097] Cannot read property \'fas fa-angle-down\' of undefined 
JS: 2020-12-14 19:19:58 [error X 2][http://3.95.76.22/hacfm.org/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=3.0.6:2:155242] Cannot read property \'stretch\' of null 
JS: 2020-12-14 19:19:59 [error X 1][http://3.95.76.22/hacfm.org/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=3.0.6:2:155352] Cannot read property \'reset\' of null 
JS: 2020-12-29 01:48:38 [error X 51][http://3.95.76.22/hacfm.org/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:19643] this.getColorRepresentation() is null 
JS: 2021-01-03 01:45:50 [error X 1][https://test.hacfm.org/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.0.9:2:70002] Cannot set property \'templatesAreSaved\' of undefined 
JS: 2021-01-03 17:00:17 [error X 1][https://test.hacfm.org/wp-includes/js/jquery/jquery.min.js?ver=3.5.1:2:31670] Cannot read property \'querySelector\' of undefined 

Log: showing 17 of 172020-08-26 17:28:04 [info] elementor::elementor_updater Started 
2020-08-26 17:28:04 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Start  
2020-08-26 17:28:05 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Finished 
2020-08-26 17:28:05 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Start  
2020-08-26 17:28:05 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Finished 
2020-08-26 17:28:05 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Start  
2020-08-26 17:28:05 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Finished 
2020-08-26 17:28:05 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Start  
2020-08-26 17:28:05 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Finished 
2020-08-26 17:28:05 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.13',
  'to' => '3.0.2',
)]
2020-08-26 17:28:05 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.13',
  'to' => '3.0.2',
)]
2020-08-26 17:48:18 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.10.2',
  'to' => '2.10.3',
)]
2020-08-26 17:49:06 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.10.3',
  'to' => '3.0.1',
)]
2020-11-12 21:35:46 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.2',
  'to' => '3.0.13',
)]
2020-11-13 17:06:51 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.1',
  'to' => '3.0.6',
)]
2020-12-29 18:21:31 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.13',
  'to' => '3.0.15',
)]
2020-12-29 18:21:38 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.6',
  'to' => '3.0.9',
)]

PHP: showing 4 of 4PHP: 2020-08-26 19:35:23 [error X 1][/opt/bitnami/apps/wordpress/htdocs/hacfm.org/wp-content/plugins/elementor/core/modules-manager.php::51] Uncaught Error: Class 'Elementor\Modules\WpCli\Module' not found in /opt/bitnami/apps/wordpress/htdocs/hacfm.org/wp-content/plugins/elementor/core/modules-manager.php:51
Stack trace:
#0 /opt/bitnami/apps/wordpress/htdocs/hacfm.org/wp-content/plugins/elementor/includes/plugin.php(585): Elementor\Core\Modules_Manager->__construct()
#1 /opt/bitnami/apps/wordpress/htdocs/hacfm.org/wp-content/plugins/elementor/includes/plugin.php(499): Elementor\Plugin->init_components()
#2 /opt/bitnami/apps/wordpress/htdocs/hacfm.org/wp-includes/class-wp-hook.php(287): Elementor\Plugin->init('')
#3 /opt/bitnami/apps/wordpress/htdocs/hacfm.org/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#4 /opt/bitnami/apps/wordpress/htdocs/hacfm.org/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#5 /opt/bitnami/apps/wordpress/htdocs/hacfm.org/wp-settings.php(540): do_action('init')
#6 /opt/bitnami/apps/wordpress/htdocs/hacfm.org/wp-config.php(90): require_once('/opt/bitnami/ap...')
#7 /opt/bitnami/apps/wordpres [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-10-27 19:45:19 [notice X 6][/opt/bitnami/apps/wordpress/htdocs/hacfm.org/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php::34] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-12-08 17:09:59 [error X 1][/opt/bitnami/apps/wordpress/htdocs/hacfm.org/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::281] Uncaught Error: Call to a member function update_meta() on null in /opt/bitnami/apps/wordpress/htdocs/hacfm.org/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:281
Stack trace:
#0 /opt/bitnami/apps/wordpress/htdocs/hacfm.org/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(162): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(7, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /opt/bitnami/apps/wordpress/htdocs/hacfm.org/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /opt/bitnami/apps/wordpress/htdocs/hacfm.org/wp-includes/class-wp-hook.php(287): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /opt/bitnami/apps/wordpress/htdocs/hacfm.org/wp- [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-12-28 20:49:57 [notice X 2][/opt/bitnami/apps/wordpress/htdocs/hacfm.org/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]


				
```
</details>

**Comment by DorShahar** [comment]
Hi
Thanks for your input.
After a check that we did, the issue is at the "Microsoft Azure" plugin, due to the fact that they add an image to the button they add to the TinyMCE

Sorry, but we can't help with that.
