### ISSUE TITLE
Social icons widget spacing/gap not working if is a "Global widget"

### ISSUE THREAD

**Issue by rafaviana** [elementor/elementor#13660]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Hello,
I have social icons in a global widget and everything works fine if I'm editing the website with the page builder. But when I go to the frontend website, social icons appear without the gap. 

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.6.50
	PHP Version: 7.4.8
	PHP Max Input Vars: 16000
	PHP Max Post Size: 130M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.6
	Site URL: https://joanamoreira.pt
	Home URL: https://joanamoreira.pt
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: pt-PT
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.3.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: pt_PT
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36

== Active Plugins ==
	301 Redirects
		Version: 2.53
		Author: WebFactory Ltd

	Advanced Custom Fields
		Version: 5.9.4
		Author: Elliot Condon

	Classic Editor
		Version: 1.6
		Author: WordPress Contributors

	Disqus for WordPress
		Version: 3.0.19
		Author: Disqus

	Elementor
		Version: 3.0.16
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.10
		Author: Elementor.com

	Enable Media Replace
		Version: 3.5.0
		Author: ShortPixel

	Hide My WP
		Version: 6.2.3
		Author: wpWave

	Reading Time WP
		Version: 2.0.10
		Author: Jason Yingling

	Simple Custom Post Order
		Version: 2.5.3
		Author: Colorlib

	Smash Balloon Instagram Feed
		Version: 2.7
		Author: Smash Balloon

	Yoast SEO
		Version: 15.6.2
		Author: Team Yoast


== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com


== Elements Usage ==
	
	archive : 8
		global : 4
		heading : 2
		text-editor : 1
	footer : 1
		button : 1
		form : 1
		heading : 1
		social-icons : 1
		text-editor : 1
	header : 1
		global : 1
		image : 1
		nav-menu : 1
		search-form : 1
	loop : 0
		post-info : 1
		theme-post-excerpt : 2
		theme-post-featured-image : 1
		theme-post-title : 1
	page : 4
		button : 2
		global : 2
		heading : 2
		image : 1
		posts : 2
		shortcode : 1
		social-icons : 1
		text-editor : 1
	popup : 2
		button : 1
		heading : 1
	section : 5
		button : 1
		heading : 2
		image : 2
		social-icons : 1
		text-editor : 4
	widget : 0
		archive-posts : 27
		breadcrumbs : 27
		divider : 18
		facebook-page : 18
		social-icons : 23
	wp-post : 1
		blockquote : 1
		html : 1
		image : 8
		text-editor : 6
	wp-page : 3
		breadcrumbs : 1
		button : 2
		form : 1
		global : 2
		heading : 8
		image : 1
		posts : 2
		shortcode : 1
		social-icons : 1
		spacer : 1
		text-editor : 25
		wp-widget-instagram-feed-widget : 1
	single-post : 1
		breadcrumbs : 1
		button : 1
		global : 3
		heading : 2
		image : 1
		post-info : 1
		post-navigation : 1
		posts : 1
		share-buttons : 1
		social-icons : 1
		spacer : 2
		text-editor : 2
		theme-post-content : 1
		theme-post-title : 1
	search-results : 1
		global : 1
		theme-archive-title : 1
	error-404 : 1
		button : 1
		heading : 1
		spacer : 1
		text-editor : 1


== Log ==
	
Log: showing 3 of 32020-12-05 13:59:35 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.11',
  'to' => '3.0.14',
)]
2021-01-19 21:46:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.14',
  'to' => '3.0.16',
)]
2021-01-23 22:11:08 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.8',
  'to' => '3.0.10',
)]

JS: showing 15 of 15JS: 2020-12-06 15:54:50 [error X 1][http://joanamoreira.pt/wp-includes/js/dist/vendor/react-dom.min.js:150:270] Cannot read property \'android\' of undefined 
JS: 2020-12-06 17:43:11 [error X 1][http://joanamoreira.pt/wp-content/plugins/elementor/assets/js/editor.min.js:2:422629] t.ui.sync.removeClass is not a function 
JS: 2020-12-06 18:09:53 [error X 1][http://joanamoreira.pt/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js:22:19954] View (cid: \"view26558\") has already been destroyed and cannot be used. 
JS: 2020-12-06 20:24:53 [error X 1][http://joanamoreira.pt/ext/elementor/assets/js/common.min.js:2:131271] Cannot read property \'error\' of undefined 
JS: 2021-01-19 22:20:54 [error X 3][http://joanamoreira.pt/wp-content/plugins/elementor/assets/js/editor.min.js:2:494888] t.$el.resizable is not a function 
JS: 2021-01-23 16:07:24 [error X 45][http://joanamoreira.pt/wp-content/plugins/elementor-pro/assets/js/editor.min.js:2:69992] Cannot set property \'templatesAreSaved\' of undefined 
JS: 2021-01-23 16:22:25 [error X 3][http://joanamoreira.pt/wp-content/plugins/wordpress-seo/js/dist/select2/select2.full.min.js:1:73343] Cannot read property \'destroy\' of undefined 
JS: 2021-01-23 16:27:09 [error X 22][http://joanamoreira.pt/wp-content/plugins/elementor/assets/js/editor.min.js:2:204708] Cannot read property \'data\' of undefined 
JS: 2021-01-23 17:20:57 [error X 11][http://joanamoreira.pt/ext/elementor/assets/js/frontend-modules.min.js:2:60285] Cannot read property \'attributes\' of undefined 
JS: 2021-01-23 19:09:41 [error X 1][http://joanamoreira.pt/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js:24:19952] View (cid: \"view157\") has already been destroyed and cannot be used. 
JS: 2021-01-23 21:46:21 [error X 1][http://joanamoreira.pt/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js:24:19952] View (cid: \"view186\") has already been destroyed and cannot be used. 
JS: 2021-01-23 22:08:48 [error X 1][http://joanamoreira.pt/wp-content/plugins/elementor/assets/js/editor.min.js:2:474760] elementorFrontend.elements.window.jQuery is not a function 
JS: 2021-01-24 12:31:11 [error X 2][http://joanamoreira.pt/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js:24:19952] View (cid: \"view12712\") has already been destroyed and cannot be used. 
JS: 2021-01-24 12:31:11 [error X 2][http://joanamoreira.pt/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js:24:19952] View (cid: \"view8678\") has already been destroyed and cannot be used. 
JS: 2021-01-24 15:57:54 [error X 4][http://joanamoreira.pt/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js:24:19952] View (cid: \"view191\") has already been destroyed and cannot be used. 

PHP: showing 5 of 5PHP: 2020-12-06 17:19:03 [error X 2][/home/joanamorsf/www/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::281] Uncaught Error: Call to a member function update_meta() on bool in /home/joanamorsf/www/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:281
Stack trace:
#0 /home/joanamorsf/www/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(162): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/joanamorsf/www/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/joanamorsf/www/wp-includes/class-wp-hook.php(287): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/joanamorsf/www/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(' [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-12-06 17:20:22 [notice X 6][/home/joanamorsf/www/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-12-06 17:31:09 [notice X 2][/home/joanamorsf/www/wp-content/plugins/elementor-pro/modules/posts/widgets/posts.php::31] Undefined index: posts_post_type [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-12-06 20:24:53 [warning X 1][/home/joanamorsf/www/wp-content/plugins/elementor-pro/modules/forms/actions/mailchimp.php::235] Invalid argument supplied for foreach() [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-01-23 22:41:33 [notice X 2][/home/joanamorsf/www/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php::33] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]


				```
</details>

**Comment by Aviad-Herman** [comment]
Hello,
Is this still an issue or has it been solved in the latest versions of Elementor?

If the bug persists, we recently updated the infrastructure behind Global Widgets. The update is currently only available on Elementor's developer edition releases (https://elementor.com/blog/introducing-beta-developer-edition/). Could you see if the bug still happens on the developer release?

Important note: the developer releases should not be used on live sites

**Comment by rafaviana** [comment]
Hi, currently I can't tell you if it works on Elementor's developer edition. Let's see if someone else can test it and give some feedback
