### ISSUE TITLE
Error with global widget insertion in pages

### ISSUE THREAD

**Issue by sergiolucianojr** [elementor/elementor#13692]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest stable version of Elementor.

## Description

When I insert a global widget in a page, it appear in the elementor editor like a "blank" widget. 

![Captura de tela 2021-01-26 180253](https://user-images.githubusercontent.com/16062840/105905613-66270880-6001-11eb-8321-d6044ae2387e.jpg)

Howerver, it is showing normally in front end.

![Captura de tela 2021-01-26 180811](https://user-images.githubusercontent.com/16062840/105905667-7d65f600-6001-11eb-9897-492c30f3e0ee.jpg)

How it should be?
- I have to see the widget data in the elementor editor, not the "blank template" of the widget.

## Steps to reproduce

1. Create a global template
2. Add a global template in a page
3. Save the page
4. Try to edit the global template

## Isolating the problem

- [ x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ x] This bug happens with a default WordPress theme active.
- [ x] I can reproduce this bug consistently using the steps above.

## Environment

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.7.33
	PHP Version: 7.3.26
	PHP Max Input Vars: 1000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.6
	Site URL: https://facilita.social
	Home URL: https://facilita.social
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 1024M
	Permalink Structure: /%postname%/
	Language: pt-BR
	Timezone: America/Sao_Paulo
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.3.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: pt_BR
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36 OPR/73.0.3856.344

== Active Plugins ==
	Advanced Order Export For WooCommerce (Pro)
		Version: 3.1.6
		Author: AlgolPlus

	bbPress
		Version: 2.6.6
		Author: The bbPress Contributors

	bbp style pack
		Version: 4.7.7
		Author: Robin Wilson

	Brazilian Market on WooCommerce
		Version: 3.7.2
		Author: Claudio Sanches

	Code Snippets
		Version: 2.14.0
		Author: Code Snippets Pro

	Complianz | GDPR/CCPA Cookie Consent
		Version: 4.9.4
		Author: Really Simple Plugins

	Elementor
		Version: 3.1.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.10
		Author: Elementor.com

	Facebook for WooCommerce
		Version: 2.2.0
		Author: Facebook

	GA Google Analytics
		Version: 20201120
		Author: Jeff Starr

	JetBlog For Elementor
		Version: 2.2.12
		Author: Crocoblock

	JetElements For Elementor
		Version: 2.5.3
		Author: Crocoblock

	JetEngine
		Version: 2.6.2
		Author: Crocoblock

	JetPopup
		Version: 1.5.1
		Author: Crocoblock

	JetSearch For Elementor
		Version: 2.1.9
		Author: Crocoblock

	JetSmartFilters
		Version: 2.1.0
		Author: Crocoblock

	JetTabs For Elementor
		Version: 2.1.10
		Author: Crocoblock

	JetTricks
		Version: 1.3.3
		Author: Crocoblock

	JetWooBuilder For Elementor
		Version: 1.7.4
		Author: Crocoblock

	License Manager for WooCommerce
		Version: 2.2.1
		Author: Dražen Bebić

	Loco Translate
		Version: 2.5.0
		Author: Tim Whitlock

	Meta Box
		Version: 5.3.7
		Author: MetaBox.io

	Pagar.me for WooCommerce
		Version: 2.5.0
		Author: Pagar.me, Claudio Sanches

	Payment Gateways by User Roles for WooCommerce
		Version: 1.2.3
		Author: Tyche Softwares

	Redux
		Version: 4.1.24
		Author: Redux.io + Dovy Paukstys

	Stop email change password
		Version: 
		Author: 

	SUMO Subscriptions
		Version: 12.4
		Author: Fantastic Plugins

	User Menus
		Version: 1.2.5
		Author: Code Atlantic

	View Admin As
		Version: 1.8.6
		Author: Jory Hogeveen

	WooCommerce
		Version: 4.9.2
		Author: Automattic

	WooCommerce Gateways Country Limiter
		Version: 1.4
		Author: OnTheGoSystems

	WooCommerce NFe
		Version: 1.2.8
		Author: NFe.io

	WooCommerce Shipping & Tax
		Version: 1.25.6
		Author: Automattic

	WordPress TotalDesk
		Version: 1.7.13
		Author: weLaunch

	WP Offload SES Lite
		Version: 1.4.4
		Author: Delicious Brains

	WP phpMyAdmin
		Version: 5.0.4.1
		Author: Puvox.software

	WP User Profile Avatar
		Version: 1.0
		Author: WP Event Manager

== Elementor - Compatibility Tag ==
	
	Elementor Pro: header_not_exists
	JetBlog For Elementor: header_not_exists
	JetElements For Elementor: header_not_exists
	JetSearch For Elementor: header_not_exists
	JetTabs For Elementor: header_not_exists
	JetWooBuilder For Elementor: header_not_exists

== Elements Usage ==
	
	archive : 1
		archive-posts : 1
		heading : 2
	footer : 1
		button : 1
		divider : 2
		heading : 4
		image : 1
		nav-menu : 3
		social-icons : 1
		text-editor : 2
	header : 1
		button : 2
		image : 2
		nav-menu : 2
		woocommerce-menu-cart : 1
	page : 1
		button : 1
		divider : 1
		heading : 8
		image : 7
		image-box : 3
		jet-listing-grid : 1
		jet-pricing-table : 1
		text-editor : 6
		toggle : 1
		video : 1
	popup : 4
		button : 2
		heading : 6
		jet-countdown-timer : 2
		spacer : 1
		text-editor : 4
	product : 2
		heading : 1
		image : 1
		woocommerce-product-add-to-cart : 2
		woocommerce-product-content : 1
		woocommerce-product-short-description : 2
		woocommerce-product-stock : 1
		woocommerce-product-title : 1
	section : 3
		bdt-price-table : 6
		heading : 1
		image : 1
		text-editor : 2
	widget : 0
		jet-pricing-table : 146
	wp-post : 0
		text-editor : 1
		toggle : 1
	wp-page : 17
		divider : 13
		flip-box : 3
		global : 3
		heading : 6
		image : 18
		image-box : -6
		jet-listing-dynamic-field : 1
		jet-listing-grid : 5
		jet-smart-filters-pagination : 2
		jet-smart-filters-radio : 1
		jet-smart-filters-remove-filters : 1
		jet-smart-filters-search : 1
		jet-switcher : 1
		jet-team-member : 3
		shortcode : 2
		spacer : -3
		text-editor : 7
		toggle : 1
		video : 2
		wc-elements : 2
	single-post : 3
		button : 1
		heading : 2
		image : 1
		post-comments : 1
		post-info : 2
		share-buttons : 1
		text-editor : 1
		theme-post-content : 3
		theme-post-featured-image : 1
		theme-post-title : 2
	single-page : 2
		heading : 1
		jet-listing-dynamic-field : 1
		theme-post-content : 2
		theme-post-excerpt : 1
		theme-post-featured-image : 1
		theme-post-title : 2
	product-post : 0
		button : 1
		global : 1
		heading : 1
		text-editor : 2
	jet-popup : 2
		button : 1
		heading : 3
		jet-countdown-timer : 1
		spacer : 2
		text-editor : 2
	jet-listing-items : 0
		divider : 1
		heading : 2
		image : 2
		jet-accordion : 1
		jet-listing-dynamic-field : 15
		jet-listing-dynamic-link : 1
		jet-listing-dynamic-terms : 1
		spacer : 1
		text-editor : 1
		video : 1

== Log ==
	
JS: showing 10 of 10JS: 2020-08-30 23:49:40 [error X 6][https://facilita.social/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.3:2:474394] Cannot read property \'isDesignable\' of undefined 
JS: 2020-09-07 21:34:35 [error X 1][https://facilita.social/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.5:2:470515] Cannot read property \'id\' of null 
JS: 2020-09-18 21:56:12 [error X 5][https://facilita.social/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view414\") has already been destroyed and cannot be used. 
JS: 2020-10-05 13:33:01 [error X 2][https://facilita.social/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.11:2:474337] Cannot read property \'document\' of undefined 
JS: 2020-10-18 04:48:12 [error X 6][https://facilita.social/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.11:2:130804] this.container is undefined 
JS: 2020-10-31 22:31:56 [error X 1][https://facilita.social/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view24839\") has already been destroyed and cannot be used. 
JS: 2020-12-02 02:48:45 [error X 438][https://facilita.social/wp-content/plugins/bdthemes-element-pack/assets/vendor/js/tippy.all.min.js:1:3753] [tippy]: `arrowTransform` is not a valid option 
JS: 2020-12-11 21:20:41 [error X 1][https://facilita.social/wp-content/plugins/bdthemes-element-pack/assets/vendor/js/tippy.all.min.js:1:3753] [tippy]: `html` is not a valid option 
JS: 2021-01-26 15:47:16 [error X 50][https://facilita.social/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.0.10:2:70002] Cannot set property \'templatesAreSaved\' of undefined 
JS: 2021-01-26 15:50:55 [error X 120][https://facilita.social/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.1.0:2:36788] Cannot read property \'attributes\' of undefined 

Log: showing 20 of 262020-08-31 19:55:38 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.4',
  'to' => '3.0.5',
)]
2020-09-07 20:03:43 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.5',
  'to' => '3.0.6',
)]
2020-09-07 20:04:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.2',
  'to' => '3.0.3',
)]
2020-09-09 15:12:07 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.6',
  'to' => '3.0.7',
)]
2020-09-09 15:31:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.3',
  'to' => '3.0.4',
)]
2020-09-16 01:00:47 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.7',
  'to' => '3.0.8.1',
)]
2020-09-17 15:23:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.8.1',
  'to' => '3.0.9',
)]
2020-09-24 17:50:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.9',
  'to' => '3.0.10',
)]
2020-09-24 17:50:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.4',
  'to' => '3.0.5',
)]
2020-10-01 16:02:32 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.10',
  'to' => '3.0.11',
)]
2020-10-23 15:33:12 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.11',
  'to' => '3.0.12',
)]
2020-11-04 23:59:23 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.12',
  'to' => '3.0.13',
)]
2020-11-04 23:59:23 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.5',
  'to' => '3.0.6',
)]
2020-12-11 16:05:46 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.13',
  'to' => '3.0.14',
)]
2020-12-11 16:05:46 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.6',
  'to' => '3.0.8',
)]
2020-12-29 21:20:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.14',
  'to' => '3.0.15',
)]
2020-12-29 21:20:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.8',
  'to' => '3.0.9',
)]
2021-01-18 12:57:44 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.15',
  'to' => '3.0.16',
)]
2021-01-22 19:56:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.9',
  'to' => '3.0.10',
)]
2021-01-26 11:23:30 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.16',
  'to' => '3.1.0',
)]

PHP: showing 6 of 6PHP: 2020-09-08 17:53:58 [warning X 1][/home/colabcolibri/public_html/wp-content/plugins/elementor/core/app/app.php::53] Invalid argument supplied for foreach() [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-09-16 00:27:42 [error X 1][/home/colabcolibri/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::281] Uncaught Error: Call to a member function update_meta() on bool in /home/colabcolibri/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:281
Stack trace:
#0 /home/colabcolibri/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(162): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/colabcolibri/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/colabcolibri/public_html/wp-includes/class-wp-hook.php(287): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/colabcolibri/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-09-16 12:08:22 [notice X 1][/home/colabcolibri/public_html/wp-content/plugins/elementor-pro/modules/woocommerce/widgets/add-to-cart.php::142] Undefined index: post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-10-31 19:01:12 [notice X 2][/home/colabcolibri/public_html/wp-content/plugins/elementor-pro/modules/posts/skins/skin-content-base.php::248] Trying to get property 'ID' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-01-26 11:10:52 [notice X 1][/home/colabcolibri/public_html/wp-content/plugins/elementor-pro/modules/query-control/module.php::738] Trying to get property 'name' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-01-26 17:36:55 [notice X 1][/home/colabcolibri/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

**Comment by DeoThemes** [comment]
I'm also experiencing similar issue. All our custom widgets are broken in editor.

And here is the console error:
TypeError: Cannot read property 'global' of undefined in common.min.js

**Comment by wpbits** [comment]
I had the same issue and fixed removing `array_values()` from `$repeater->get_controls()`

before

```
$this->add_control(
			'elements',
			[
				'label' => esc_html__( 'Elements', 'wpbits-club' ),
				'type' => Controls_Manager::REPEATER,
				'show_label' => true,
				'fields' => array_values( $repeater->get_controls() ),
                                 'title_field' => '{{{ element_type }}}',
				'default' => [ ]	                 
			]
		); 
```


after

 	
```
$this->add_control(
			'elements',
			[
				'label' => esc_html__( 'Elements', 'wpbits-club' ),
				'type' => Controls_Manager::REPEATER,
				'show_label' => true,
				'fields' => $repeater->get_controls(),
                                 'title_field' => '{{{ element_type }}}',
				'default' => [ ]	                 
			]
		); 
```
 


Hope it helps!

**Comment by shilo-ey** [comment]
@sergiolucianojr  @DeoThemes 

What @WPBits suggested fixes the issue in your case?

**Comment by DeoThemes** [comment]
@shilo-ey Yes, array_values is the cause of JS error, after removing it everything works.

**Comment by d19dotca** [comment]
Yes, I see this issue too. Was just about to report this. I used the built-in Testimonials widget which I then made into a Global Widget. When the Global Widget is used, the back-end Elementor editor shows the widget as a default "Lorem ipsum" text, despite it showing correctly in the front-end. Please add this to the bugs label @shilo-ey. It's unclear to me how to implement @wpbits's workaround, however I don't know if I want to follow that yet either as it's not a huge issue but is certainly annoying when editing pages and they show "lorem ipsum" unnecessarily, makes it a bit harder to edit that widget specifically.

**Comment by Aviad-Herman** [comment]
Hey guys,
Is this still an issue or has it been solved in the latest versions of Elementor?

If the bug persists, we recently updated the infrastructure behind Global Widgets. The update is currently only available on Elementor's developer edition releases (https://elementor.com/blog/introducing-beta-developer-edition/). Could you see if the bug still happens on the developer release?

Important note: the developer releases should not be used on live sites

**Comment by SandraWEBK** [comment]
This is still an issue for me (Elementor Pro Version 3.5.0). 
Every global widget I insert shows as "lorem ipsum" in the backend AND the frontend.
I don't have the skills to test the developer edition, but wanted to let you know that it seems to be still an issue. My workaround is to copy paste the global widgets from their original page.
