### ISSUE TITLE
Vertical Scrollbar BUG in Editing Panel

### ISSUE THREAD

**Issue by ClintonGallagher** [elementor/elementor#13735]
## Prerequisites
- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description
The vertical scrollbar in the Editing Panel is typically very narrow and a pain in the ass to use but this reported BUG causes the vertical scrollbar to become unusable.

The more lines of text such as raw HTML or SVG source code in the Editor the thinner the vertical scrollbar becomes to the point of disappearing causing editing to break-down. This is shown in the attached images.

The scrollbar van be reduced in size to ~5 pixels as shown in the attached image. When trying to grab the scrollbar with the mouse to scroll the <-> resizer function loads. The only way to scroll up or down deep into the raw source code or to the bottom of the source is to enter the cursor into the source and --try-- to use the keyboard to --maybe-- Page Up or Page Down.

## Steps to reproduce
This BUG is consistently replicated in Elementor Pro by using the </> HTML widget and pasting inline SVG source code on any other raw HTML source consisting of a large number of lines. This BUG is theme independent.

## Isolating the problem
- [x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: WINNT
	Software: nginx/1.16.0
	MySQL version: MySQL Community Server (GPL) v5.7.24
	PHP Version: 7.2.19
	PHP Max Input Vars: 1000
	PHP Max Post Size: 2G
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.6
	Site URL: http://cashback.local:8080
	Home URL: http://cashback.local:8080
	WP Multisite: No
	Max Upload Size: 2 GB
	Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.1.0
	Author: Clinton Gallagher
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.3.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0

== Active Plugins ==
	Admin Menu Editor
		Version: 1.9.8
		Author: Janis Elsts

	Elementor
		Version: 3.1.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.8
		Author: Elementor.com

	Flexible Elementor Panel
		Version: 2.2.2
		Author: WebMat

	JetEngine
		Version: 2.6.2
		Author: Crocoblock

	Media Library Folders for WordPress
		Version: 6.1.0
		Author: Max Foundry

	UpdraftPlus - Backup/Restore
		Version: 1.16.46
		Author: UpdraftPlus.Com, DavidAnderson

== Elementor - Compatibility Tag ==
	
	Elementor Pro: header_not_exists
	Flexible Elementor Panel: header_not_exists

== Elements Usage ==
	
	header : 1
		image : 1
		nav-menu : 1
		social-icons : 1
	wp-page : 2
		heading : 2
		html : 2
		posts : 1
		text-editor : 1
		wp-widget-text : 1

== Log ==
	
PHP: showing 3 of 3PHP: 2021-01-25 01:39:19 [notice X 2][C:\laragon\www\cashback\wp-content\plugins\elementor\core\common\modules\ajax\module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-01-26 00:49:25 [error X 1][C:\laragon\www\cashback\wp-content\plugins\elementor-pro\core\admin\canary-deployment.php::16] Uncaught Error: Class 'ElementorPro\License\API' not found in C:\laragon\www\cashback\wp-content\plugins\elementor-pro\core\admin\canary-deployment.php:16
Stack trace:
#0 C:\laragon\www\cashback\wp-content\plugins\elementor\core\admin\canary-deployment.php(89): ElementorPro\Core\Admin\Canary_Deployment->get_canary_deployment_remote_info(false)
#1 C:\laragon\www\cashback\wp-content\plugins\elementor\core\admin\canary-deployment.php(56): Elementor\Core\Admin\Canary_Deployment->get_canary_deployment_info()
#2 C:\laragon\www\cashback\wp-includes\class-wp-hook.php(289): Elementor\Core\Admin\Canary_Deployment->check_version(Object(stdClass))
#3 C:\laragon\www\cashback\wp-includes\plugin.php(212): WP_Hook->apply_filters(Object(stdClass), Array)
#4 C:\laragon\www\cashback\wp-includes\option.php(1931): apply_filters('pre_set_site_tr...', Object(stdClass), 'update_plugins')
#5 C:\laragon\www\cashback\wp-includes\update.php(450): set_site_transient('update_plugins', Object(stdClass))
#6 C:\laragon\www\cashback\wp-includ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-01-26 01:25:52 [error X 2][C:\laragon\www\cashback\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-manager.php::281] Uncaught Error: Call to a member function update_meta() on boolean in C:\laragon\www\cashback\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-manager.php:281
Stack trace:
#0 C:\laragon\www\cashback\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-manager.php(162): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 C:\laragon\www\cashback\wp-content\plugins\elementor\core\common\modules\ajax\module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 C:\laragon\www\cashback\wp-includes\class-wp-hook.php(287): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 C:\laragon\www\cashback\wp-includes\class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#5 C:\laragon\www\cashback\wp-in [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 1 of 12021-01-28 16:18:47 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.16',
  'to' => '3.1.0',
)]
			
</details>

![editor default scrollbar](https://user-images.githubusercontent.com/3301515/106218336-bb4b5180-619c-11eb-8dd9-9bc46add64ba.png)

![editor fubar scrollbar](https://user-images.githubusercontent.com/3301515/106218356-c56d5000-619c-11eb-98e3-5ef8656631b2.png)

**Comment by ygirod** [comment]
Interested. Same issue.

**Comment by ygirod** [comment]
Any idea for solution ?
