### ISSUE TITLE
Elementor pulling ACF information from default value not actual post

### ISSUE THREAD

**Issue by Errroron** [elementor/elementor#14014]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

When using dynamic content with ACF plugin. Elementor will pull the dynamic content from the default value set in ACF and not the actual post published.

## Steps to reproduce

Create new CPT UI post type.
Add new field group in ACF with a field type set to text and set default value.
![Screenshot 2021-02-24 002142](https://user-images.githubusercontent.com/79564992/108969820-a8f6f300-7636-11eb-81a4-fed3a7375537.png)
Create post in newly created Post Type.
![Screenshot 2021-02-24 002152](https://user-images.githubusercontent.com/79564992/108970243-c1ffa400-7636-11eb-9713-d68de06d2c3d.png)
In Elementor create header element and link to dynamic ACF post.
![Screenshot 2021-02-24 002159](https://user-images.githubusercontent.com/79564992/108970381-c9bf4880-7636-11eb-9ab7-2ad109e354a3.png)

*Side note dynamic content created on older version of elementor pro still work but creating any new dynamic links do not work on same site. 

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release '35', Revision '5688520' v5.7.32-35
	PHP Version: 7.4.14
	PHP Max Input Vars: 10000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.6.2
	Site URL: https://fircreststage.wpengine.com
	Home URL: http://fircreststage.wpengine.com
	WP Multisite: No
	Max Upload Size: 50 MB
	Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.3.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 5.9.5
		Author: Elliot Condon

	Code Snippets
		Version: 2.14.0
		Author: Code Snippets Pro

	Custom Post Type UI
		Version: 1.8.2
		Author: WebDevStudios

	Duplicate Page
		Version: 4.3
		Author: mndpsingh287

	Elementor
		Version: 3.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.1.0
		Author: Elementor.com

	FileBird Lite
		Version: 4.5
		Author: Ninja Team

	OoohBoi Steroids for Elementor
		Version: 1.6.2
		Author: OoohBoi

== Must-Use Plugins ==
	Force Strong Passwords - WPE Edition
		Version: 1.6.4
		Author: Jason Cosper

	WP Engine Seamless Login Plugin
		Version: 1.5.5
		Author: WP Engine

	WP Engine Security Auditor
		Version: 1.0.9
		Author: wpengine

	WP Engine System
		Version: 4.1.0
		Author: WP Engine

== Elementor - Compatibility Tag ==
	
	Elementor Pro: compatible
	OoohBoi Steroids for Elementor: header_not_exists

== Elementor Pro - Compatibility Tag ==
	

== Elements Usage ==
	
	header : 1
		html : 1
		nav-menu : 3
		theme-site-logo : 1
	footer : 2
		heading : 1
		text-editor : 2
	section : 18
		button : 7
		divider : 2
		heading : 24
		html : 8
		image : 14
		text-editor : 13
	wp-page : 10
		button : 7
		divider : 14
		google_maps : 1
		heading : 215
		html : 20
		image : 110
		text-editor : 164
	error-404 : 1
		heading : 3
		icon-list : 4

== Log ==
	
JS: showing 3 of 3JS: 2021-01-21 00:23:38 [error X 269][https://fircreststage.wpengine.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.16:2:134119] Cannot read property \'get\' of undefined 
JS: 2021-01-28 02:15:09 [error X 1][https://fircreststage.wpengine.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.1.0:2:373418] Cannot read property \'getBoundingClientRect\' of null 
JS: 2021-02-24 07:16:29 [error X 2][https://fircreststage.wpengine.com/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=2.9.14:2:58497] Cannot read property \'model\' of undefined 

PHP: showing 7 of 7PHP: 2021-01-21 00:40:23 [warning X 7][/nas/content/live/fircreststage/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/fonts/typekit-fonts.php::235] count(): Parameter must be an array or an object that implements Countable [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-01-21 19:33:45 [error X 1][/nas/content/live/fircreststage/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::281] Uncaught Error: Call to a member function update_meta() on bool in /nas/content/live/fircreststage/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:281
Stack trace:
#0 /nas/content/live/fircreststage/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(162): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /nas/content/live/fircreststage/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /nas/content/live/fircreststage/wp-includes/class-wp-hook.php(287): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /nas/content/live/fircreststage/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Ar [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-01-27 20:22:07 [notice X 18][/nas/content/live/fircreststage/wp-content/plugins/elementor/includes/managers/image.php::86] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-01-28 18:00:03 [notice X 24][/nas/content/live/fircreststage/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php::33] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-02-10 23:56:12 [notice X 1][/nas/content/live/fircreststage/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-02-11 07:01:46 [notice X 3][/nas/content/live/fircreststage/wp-content/plugins/elementor/includes/managers/image.php::33] Undefined index: size [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-02-24 07:16:29 [error X 1][/nas/content/live/fircreststage/wp-content/plugins/elementor/core/dynamic-tags/manager.php::397] Uncaught Error: Call to a member function get_content() on null in /nas/content/live/fircreststage/wp-content/plugins/elementor/core/dynamic-tags/manager.php:397
Stack trace:
#0 [internal function]: Elementor\Core\DynamicTags\Manager->ajax_render_tags(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#1 /nas/content/live/fircreststage/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /nas/content/live/fircreststage/wp-includes/class-wp-hook.php(287): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#3 /nas/content/live/fircreststage/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#4 /nas/content/live/fircreststage/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#5 /nas/content/live/fircreststage/wp-admin/admin-ajax.php(184): do_action('wp_ajax_element...')
#6 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 13 of 132021-01-27 20:10:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.16',
  'to' => '3.1.0',
)]
2021-02-03 00:11:54 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.0',
  'to' => '3.1.1',
)]
2021-02-16 18:12:39 [info] elementor-pro::elementor_pro_updater Started 
2021-02-16 18:12:39 [info] Elementor Pro/Upgrades - _v_3_1_0_media_carousel Start  
2021-02-16 18:12:39 [info] Elementor Pro/Upgrades - _v_3_1_0_media_carousel Finished 
2021-02-16 18:12:39 [info] Elementor Pro/Upgrades - _v_3_1_0_reviews Start  
2021-02-16 18:12:39 [info] Elementor Pro/Upgrades - _v_3_1_0_reviews Finished 
2021-02-16 18:12:39 [info] Elementor Pro/Upgrades - _v_3_1_0_testimonial_carousel Start  
2021-02-16 18:12:39 [info] Elementor Pro/Upgrades - _v_3_1_0_testimonial_carousel Finished 
2021-02-16 18:12:39 [info] Elementor Pro/Upgrades - _v_3_1_0_slides Start  
2021-02-16 18:12:39 [info] Elementor Pro/Upgrades - _v_3_1_0_slides Finished 
2021-02-16 18:12:39 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.10',
  'to' => '3.1.0',
)]
2021-02-16 18:12:39 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.10',
  'to' => '3.1.0',
)]

</details>

**Comment by Errroron** [comment]
So are we just dropping the ability to use ACF and CPT? The newest update breaks everything even more than the issues I was having before. I've restored from backups to get rid of the updates as rolling back does not fix the issues I was having. As it stands I can no longer update my sites or add new dynamic content to them. Should we rebuild our sites without elementor or is this going to be addressed?

**Comment by julien-paris** [comment]
Same here, I have very strange behaviour all around with ACF Pro and Elementor. 
One example: 
I set an acf field to be "Taxonomy. 
Save
I open it again, it is revereted back to text (but still has the taxonomy related data settings!) 

Also, I cannot save the "load/create/save terms" fields. 

I have had other issues as well. 

Disabling Elementor solves the problems. Rolling back does not (neither Elementor free nor pro).
