### ISSUE TITLE
ACF Driven Images now outputting code

### ISSUE THREAD

**Issue by DavidGMiles** [elementor/elementor#14170]
Prerequisites

ACF, Elementor, Elementor Pro

Steps to replicate

Create an image widget, wire it up to ACF, watch it fail

Isolating the problem

This affects all image widgets from Elementor, those from other providers are not similarly afflicted - I can disable all other plugins barring ACF and a couple of other data plugins that are needed and this still occurs

System info
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.25 (Debian)
	MySQL version: mariadb.org binary distribution v5.6.49-89.0
	PHP Version: 7.4.15
	PHP Max Input Vars: 2500
	PHP Max Post Size: 10M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.6.2
	Site URL: https://dev.natureslens.co.uk
	Home URL: https://dev.natureslens.co.uk
	WP Multisite: No
	Max Upload Size: 10 MB
	Memory limit: 1024M
	Permalink Structure: /%year%/%monthnum%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.3.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15

== Active Plugins ==
	Admin Columns Pro
		Version: 5.4.3
		Author: AdminColumns.com

	Admin Columns Pro - Advanced Custom Fields (ACF)
		Version: 2.6.4
		Author: AdminColumns.com

	Advanced Custom Fields: Extended PRO
		Version: 0.8.7.6
		Author: ACF Extended

	Advanced Custom Fields PRO
		Version: 5.9.5
		Author: Elliot Condon

	Advanced Elements
		Version: 1.7-beta2
		Author: Goose Studio

	AnyWhere Elementor Pro
		Version: 2.17.3
		Author: WP Vibes

	Auto Image Attributes From Filename With Bulk Updater
		Version: 1.6
		Author: Arun Basil Lal

	Code Snippets
		Version: 2.14.0
		Author: Code Snippets Pro

	Display Posts
		Version: 3.0.2
		Author: Bill Erickson

	DynamicConditions
		Version: 1.4.6
		Author: RTO GmbH

	Dynoments Rexy
		Version: 1.0.5.1
		Author: Dynoments

	e-addons DEVELOPER
		Version: 1.0.2
		Author: Nerds Farm

	e-addons DISPLAY
		Version: 1.3.1
		Author: Nerds Farm

	e-addons EDITOR
		Version: 1.8
		Author: Nerds Farm

	e-addons EXTENDED
		Version: 1.2
		Author: Nerds Farm

	e-addons for Elementor
		Version: 2.4
		Author: Nerds Farm

	e-addons INSPECTOR
		Version: 1.0.2
		Author: Nerds Farm

	e-addons MANAGER
		Version: 1.2
		Author: Nerds Farm

	e-addons PRO FORM ACTIONS
		Version: 1.1.2
		Author: Nerds Farm

	e-addons PRO FORM CONDITIONS
		Version: 1.1.2
		Author: Nerds Farm

	e-addons PRO FORM EXTENDED
		Version: 1.3.3
		Author: Nerds Farm

	e-addons TOKENS
		Version: 1.1.1
		Author: Nerds Farm

	Elementor
		Version: 3.1.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.2.0-beta1
		Author: Elementor.com

	Emage Hover Effects for Elementor
		Version: 4.3.1.1
		Author: Blocksera

	Event Page Elements
		Version: 
		Author: 

	Flexible Elementor Panel
		Version: 2.2.2
		Author: WebMat

	Internal Links Manager
		Version: 2.2.4
		Author: webraketen

	JC Submenu
		Version: 0.9.1
		Author: James Collings

	JetSearch For Elementor
		Version: 2.1.9
		Author: Crocoblock

	MalCare Security - Free Malware Scanner, Protection & Security for WordPress
		Version: 4.55
		Author: MalCare Security

	Max Mega Menu
		Version: 2.9.3
		Author: megamenu.com

	NaturesLens Site-Specific Functionality
		Version: 2019.03.04
		Author: David Miles

	OMGF
		Version: 4.2.6
		Author: Daan from FFW.Press

	PDF viewer for Elementor
		Version: 2.9.2
		Author: RedLettuce Plugins

	Perfmatters
		Version: 1.6.7
		Author: forgemedia

	Rank Math SEO
		Version: 1.0.59
		Author: Rank Math

	Rank Math SEO PRO
		Version: 2.3.0
		Author: Rank Math

	Redis Object Cache
		Version: 2.0.17
		Author: Till Krüss

	Search & Filter - Elementor Extension
		Version: 1.0.6
		Author: Code Amp

	Search & Filter Pro
		Version: 2.5.4
		Author: Code Amp

	ShortPixel Image Optimizer
		Version: 4.21.1
		Author: ShortPixel

	Simple Custom CSS and JS
		Version: 3.36
		Author: SilkyPress.com

	Text Spinner
		Version: 1.3.0
		Author: WPGurus

	WP Config File Editor
		Version: 1.7.1
		Author: AHMeD HAMeD

	WP Dark Mode
		Version: 2.0.3
		Author: WPPOOL

	WP Dark Mode Ultimate
		Version: 2.0.1
		Author: WPPOOL

	WP Rocket
		Version: 3.8.6
		Author: WP Media

	WP Rocket | Custom Sitemap Preload Intervals
		Version: 
		Author: WP Rocket Support Team

	WP Taxonomy Order
		Version: 1.0.2
		Author: NuttTaro

== Elementor - Compatibility Tag ==
	
	AnyWhere Elementor Pro: header_not_exists
	e-addons for Elementor: header_not_exists
	Elementor Pro: header_not_exists
	Emage Hover Effects for Elementor: header_not_exists
	Flexible Elementor Panel: header_not_exists
	JetSearch For Elementor: header_not_exists
	PDF viewer for Elementor: header_not_exists
	Search & Filter - Elementor Extension: header_not_exists

== Elementor Pro - Compatibility Tag ==
	

== Elements Usage ==
	
	archive : 3
		ae-acf-gallery : 1
		ae-post-blocks : 1
		ae-post-blocks-adv : 1
		heading : 1
		image : 1
		template : 1
		text-editor : 2
		theme-archive-title : 1
	footer : 1
		button : 1
		heading : 5
		nav-menu : 3
		social-icons : 1
		text-editor : 1
	header : 1
		button : 2
		theme-site-logo : 1
		wp-widget-maxmegamenu : 1
	page : 2
		button : 3
		divider : 5
		heading : 44
		html : 1
		icon-box : 3
		image : 4
		spacer : 11
	popup : 6
		ae-post-blocks : 1
		ae-searchform : 1
		heading : -3
		template : 2
		text-editor : 2
	section : 47
		acf-single-field : 1
		ae-post-content : 1
		ae-post-image : 1
		ae-post-title : 1
		ae-taxonomy : 5
		button : 12
		divider : 11
		e-query-media : 3
		form : 2
		gallery : 1
		heading : 40
		image : 15
		jet-ajax-search : 1
		nav-menu : 1
		repeaters-widget : 2
		search-form : 1
		shortcode : 5
		social-icons : 1
		spacer : 2
		text-editor : 63
		theme-post-title : 1
	single : 0
		text-editor : -6
	widget : 0
		text-editor : 179
	wp-post : 0
		ae-acf-repeater : 1
		ae-post-blocks : 2
		ae-post-content : 9
		ae-post-image : 6
		ae-post-meta : 6
		ae-post-title : 10
		ae-taxonomy : 23
		button : 73
		divider : 38
		emage_hover_effects : 6
		form : 6
		gallery : 13
		global : 6
		gs-ae-repeater : 18
		heading : 131
		html : 2
		icon : 1
		icon-list : 6
		image : 61
		jet-ajax-search : 6
		menu-anchor : 8
		nav-menu : 20
		spacer : 1
		template : 10
		text-editor : 124
	wp-page : 25
		ae-post-blocks : 3
		ae-post-blocks-adv : 3
		button : 1
		divider : 5
		emage_hover_effects : 2
		heading : 50
		html : 3
		image : 6
		pdfjs_viewer : 1
		posts-extra : 1
		search-filter-form : 1
		sitemap : 3
		social-icons : 1
		tabs : 1
		template : 5
		text-editor : 28
		wp-widget-search_filter_register_widget : 1
	single-post : 1
		ae-post-blocks-adv : 1
		button : 5
		emage_hover_effects : 2
		flexible-content-widget : 1
		heading : 4
		image : 1
		repeaters-widget : 1
		text-editor : 10
		theme-post-content : 1
		theme-post-title : 1
	single-list-item : 0
		button : 1
		heading : 4
		image : 1
		text-editor : 1
	search-results : 1
		ae-post-blocks-adv : 1
		ae-searchform : 1
		text-editor : 1
	not-supported : 0
		button : 1
		divider : 9
		heading : 10
		menu-anchor : 6
		social-icons : 1
		text-editor : 22
	error-404 : 1
		heading : 2
		template : 1

== Log ==
	
PHP: showing 12 of 12PHP: 2021-02-16 11:27:06 [notice X 1][/home/556865.cloudwaysapps.com/mqdpyafvut/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::162] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-02-25 17:15:29 [error X 1][/home/556865.cloudwaysapps.com/mqdpyafvut/public_html/wp-content/plugins/elementor-pro/modules/forms/classes/rest-client.php::147] Uncaught Exception: Rest Client Error: response code 0 in /home/556865.cloudwaysapps.com/mqdpyafvut/public_html/wp-content/plugins/elementor-pro/modules/forms/classes/rest-client.php:147
Stack trace:
#0 /home/556865.cloudwaysapps.com/mqdpyafvut/public_html/wp-content/plugins/elementor-pro/modules/forms/classes/rest-client.php(109): ElementorPro\Modules\Forms\Classes\Rest_Client->request('GET', 'groups', NULL)
#1 /home/556865.cloudwaysapps.com/mqdpyafvut/public_html/wp-content/plugins/elementor-pro/modules/forms/classes/mailerlite-handler.php(48): ElementorPro\Modules\Forms\Classes\Rest_Client->get('groups')
#2 /home/556865.cloudwaysapps.com/mqdpyafvut/public_html/wp-content/plugins/elementor-pro/modules/forms/classes/mailerlite-handler.php(27): ElementorPro\Modules\Forms\Classes\Mailerlite_Handler->is_valid_api_key()
#3 /home/556865.cloudwaysapps.com/mqdpyafvut/public_html/wp-content/plugins/elementor-pro/modules/forms/actions/mailerlite.php(143): ElementorPro\Modules\Forms\Classes\Mailerlite_Handler->__construct('81c76de6a7ce0d3...')
#4 /home/556865.cloudwaysapps.com/mqdpyafvut/public_html/wp-content/plugins/e-addons-pro-form-conditions/module [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-02-25 17:16:32 [error X 1][/home/556865.cloudwaysapps.com/mqdpyafvut/public_html/wp-content/plugins/elementor-pro/modules/forms/classes/rest-client.php::147] Uncaught Exception: Rest Client Error: response code 400 in /home/556865.cloudwaysapps.com/mqdpyafvut/public_html/wp-content/plugins/elementor-pro/modules/forms/classes/rest-client.php:147
Stack trace:
#0 /home/556865.cloudwaysapps.com/mqdpyafvut/public_html/wp-content/plugins/elementor-pro/modules/forms/classes/rest-client.php(96): ElementorPro\Modules\Forms\Classes\Rest_Client->request('POST', 'groups/9791726/...', 'false')
#1 /home/556865.cloudwaysapps.com/mqdpyafvut/public_html/wp-content/plugins/elementor-pro/modules/forms/classes/mailerlite-handler.php(121): ElementorPro\Modules\Forms\Classes\Rest_Client->post('groups/9791726/...', false)
#2 /home/556865.cloudwaysapps.com/mqdpyafvut/public_html/wp-content/plugins/elementor-pro/modules/forms/actions/mailerlite.php(144): ElementorPro\Modules\Forms\Classes\Mailerlite_Handler->create_subscriber('9791726', false)
#3 /home/556865.cloudwaysapps.com/mqdpyafvut/public_html/wp-content/plugins/e-addons-pro-form-conditions/modules/condition/extensions/action.php(218): ElementorPro\Modules\Forms\Actions\Mailerlite->run(Object(ElementorPro\Modules\Forms\Classes\Form_Record), Obje [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-01 21:58:20 [error X 1][/home/556865.cloudwaysapps.com/mqdpyafvut/public_html/wp-content/plugins/elementor-pro/modules/forms/classes/rest-client.php::147] Uncaught Exception: Rest Client Error: response code 400 in /home/556865.cloudwaysapps.com/mqdpyafvut/public_html/wp-content/plugins/elementor-pro/modules/forms/classes/rest-client.php:147
Stack trace:
#0 /home/556865.cloudwaysapps.com/mqdpyafvut/public_html/wp-content/plugins/elementor-pro/modules/forms/classes/rest-client.php(96): ElementorPro\Modules\Forms\Classes\Rest_Client->request('POST', 'groups/9791726/...', 'false')
#1 /home/556865.cloudwaysapps.com/mqdpyafvut/public_html/wp-content/plugins/elementor-pro/modules/forms/classes/mailerlite-handler.php(121): ElementorPro\Modules\Forms\Classes\Rest_Client->post('groups/9791726/...', false)
#2 /home/556865.cloudwaysapps.com/mqdpyafvut/public_html/wp-content/plugins/elementor-pro/modules/forms/actions/mailerlite.php(144): ElementorPro\Modules\Forms\Classes\Mailerlite_Handler->create_subscriber('9791726', false)
#3 /home/556865.cloudwaysapps.com/mqdpyafvut/public_html/wp-content/plugins/e-addons-pro-form-conditions/modules/condition/extensions/action.php(21 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-02 09:20:51 [error X 6][/home/556865.cloudwaysapps.com/mqdpyafvut/public_html/wp-content/plugins/elementor-pro/modules/forms/classes/rest-client.php::147] Uncaught Exception: Rest Client Error: response code 400 in /home/556865.cloudwaysapps.com/mqdpyafvut/public_html/wp-content/plugins/elementor-pro/modules/forms/classes/rest-client.php:147
Stack trace:
#0 /home/556865.cloudwaysapps.com/mqdpyafvut/public_html/wp-content/plugins/elementor-pro/modules/forms/classes/rest-client.php(96): ElementorPro\Modules\Forms\Classes\Rest_Client->request()
#1 /home/556865.cloudwaysapps.com/mqdpyafvut/public_html/wp-content/plugins/elementor-pro/modules/forms/classes/mailerlite-handler.php(121): ElementorPro\Modules\Forms\Classes\Rest_Client->post()
#2 /home/556865.cloudwaysapps.com/mqdpyafvut/public_html/wp-content/plugins/elementor-pro/modules/forms/actions/mailerlite.php(144): ElementorPro\Modules\Forms\Classes\Mailerlite_Handler->create_subscriber()
#3 /home/556865.cloudwaysapps.com/mqdpyafvut/public_html/wp-content/plugins/e-addons-pro-form-conditions/modules/condition/extensions/action.php(218): ElementorPro\Modules\Forms\Actions\Mailerlite->run()
#4 /home/556865.cloudwa [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-02 13:25:51 [error X 1][/home/556865.cloudwaysapps.com/mqdpyafvut/public_html/wp-content/plugins/elementor/includes/widgets/toggle.php::356] Out of memory (allocated 67108864) (tried to allocate 32768 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-02 17:57:12 [notice X 42][/home/556865.cloudwaysapps.com/mqdpyafvut/public_html/wp-content/plugins/elementor/includes/controls/base-multiple.php::87] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-03 08:45:03 [warning X 3][/home/556865.cloudwaysapps.com/mqdpyafvut/public_html/wp-content/plugins/elementor/includes/controls/select.php::132] Illegal offset type in isset or empty [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-03 18:07:11 [notice X 6][/home/556865.cloudwaysapps.com/mqdpyafvut/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-06 13:48:51 [error X 1][/home/556865.cloudwaysapps.com/mqdpyafvut/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php::1060] Out of memory (allocated 39845888) (tried to allocate 81920 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-06 15:23:43 [notice X 9][/home/556865.cloudwaysapps.com/mqdpyafvut/public_html/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-color.php::34] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-07 13:48:36 [error X 5][/home/556865.cloudwaysapps.com/mqdpyafvut/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php::1090] Uncaught TypeError: Argument 2 passed to Elementor\TemplateLibrary\Source_Local::on_save_post() must be an instance of WP_Post, instance of stdClass given, called in /home/556865.cloudwaysapps.com/mqdpyafvut/public_html/wp-includes/class-wp-hook.php on line 289 and defined in /home/556865.cloudwaysapps.com/mqdpyafvut/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php:1090
Stack trace:
#0 /home/556865.cloudwaysapps.com/mqdpyafvut/public_html/wp-includes/class-wp-hook.php(289): Elementor\TemplateLibrary\Source_Local->on_save_post()
#1 /home/556865.cloudwaysapps.com/mqdpyafvut/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters()
#2 /home/556865.cloudwaysapps.com/mqdpyafvut/public_html/wp-includes/plugin.php(484): WP_Hook->do_action()
#3 /home/556865.cloudwaysapps.com/mqdpyafvut/public_html/wp-includes/post.php(4309): do_action()
#4 /home/556865.cloudwaysapps.com/mqdpyafvut/public_html/wp-includes/post.php(4411): wp_insert_post()
#5 /home/556865.cloudwaysapps. [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 5 of 5JS: 2021-02-18 16:23:15 [error X 2][http://wordpress-556865-1791351.cloudwaysapps.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.1.1:2:191238] undefined is not an object (evaluating \'t.ui.form.html\') 
JS: 2021-02-18 16:39:23 [error X 12][http://wordpress-556865-1791351.cloudwaysapps.com/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.1.1:2:36775] undefined is not an object (evaluating \'elementorFrontend.config.elements.data\') 
JS: 2021-02-18 20:57:48 [error X 6][http://wordpress-556865-1791351.cloudwaysapps.com/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.1.1:2:34983] can\'t access property \"global\", t[o] is undefined 
JS: 2021-02-25 17:15:30 [error X 8][http://wordpress-556865-1791351.cloudwaysapps.com/wp-content/plugins/elementor/assets/js/common.min.js?ver=3.1.1:2:111556] undefined is not an object (evaluating \'n.error\') 
JS: 2021-02-28 12:51:02 [error X 30][http://wordpress-556865-1791351.cloudwaysapps.com/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.1.1:2:34999] undefined is not an object (evaluating \'t[o].global\') 

Log: showing 20 of 252021-02-25 13:49:34 [info] Elementor Pro/Upgrades - _v_3_1_0_testimonial_carousel Start  
2021-02-25 13:49:34 [info] Elementor Pro/Upgrades - _v_3_1_0_testimonial_carousel Finished 
2021-02-25 13:49:34 [info] Elementor Pro/Upgrades - _v_3_1_0_slides Start  
2021-02-25 13:49:34 [info] Elementor Pro/Upgrades - _v_3_1_0_slides Finished 
2021-02-25 13:49:34 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.1.0-beta3',
  'to' => '3.1.1',
)]
2021-02-25 13:49:41 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.1.0-beta3',
  'to' => '3.1.1',
)]
2021-02-25 13:49:42 [info] elementor-pro::elementor_pro_updater Started 
2021-02-25 13:49:42 [info] Elementor Pro/Upgrades - _v_3_1_0_media_carousel Start  
2021-02-25 13:49:42 [info] Elementor Pro/Upgrades - _v_3_1_0_media_carousel Finished 
2021-02-25 13:49:42 [info] Elementor Pro/Upgrades - _v_3_1_0_reviews Start  
2021-02-25 13:49:42 [info] Elementor Pro/Upgrades - _v_3_1_0_reviews Finished 
2021-02-25 13:49:42 [info] Elementor Pro/Upgrades - _v_3_1_0_testimonial_carousel Start  
2021-02-25 13:49:42 [info] Elementor Pro/Upgrades - _v_3_1_0_testimonial_carousel Finished 
2021-02-25 13:49:42 [info] Elementor Pro/Upgrades - _v_3_1_0_slides Start  
2021-02-25 13:49:42 [info] Elementor Pro/Upgrades - _v_3_1_0_slides Finished 
2021-02-25 13:49:42 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.1.0-beta3',
  'to' => '3.1.1',
)]
2021-02-25 15:11:11 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.1.1',
  'to' => '3.2.0-beta1',
)]
2021-02-25 17:17:28 [error] Save submission failed, db error: Column 'post_id' cannot be null 
2021-03-02 23:12:24 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.1',
  'to' => '3.1.2',
)]
2021-03-03 20:56:43 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.2',
  'to' => '3.1.3',
)]

![elem images](https://user-images.githubusercontent.com/20774089/110386301-06883800-8058-11eb-8270-da174ddc99a7.jpg)

**Comment by DavidGMiles** [comment]
ACF Dynamic Data Tag provider had error in code - not the result of Image Widget
