### ISSUE TITLE
Conflicts with Borlabs Cookie Plugin

### ISSUE THREAD

**Issue by Asored-D** [elementor/elementor#14339]
## Prerequisites

- [ X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ X] The issue still exists against the latest stable version of Elementor.

## Description

When using Borlabs Cookie Plugin Elementor seems to have some trouble with. For example, if I activate the Content Blocker to block facebook iframes before the user accepts, I cannot open the mobile hamburger menu on mobile. There is no error message in the console. Just nothing happens. If I deactivate the facebook content blocker (which is searching for iframes with some url sources), the mobile works as expected.

## Steps to reproduce

1. Install Borlabs Cookie Plugin
2. Activate Facebook Content Blocker (By default it should be activated)
3. Try to open navigation on mobile

## Isolating the problem

- [X ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ X] This bug happens with a default WordPress theme active.
- [ X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: (Ubuntu) v5.7.28
	PHP Version: 7.3.26-nmm1
	PHP Max Input Vars: 3000
	PHP Max Post Size: 200M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.7
	Site URL: https://dev.codepa.de/towa
	Home URL: https://dev.codepa.de/towa
	WP Multisite: No
	Max Upload Size: 200 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: de-DE
	Timezone: Europe/Berlin
	Debug Mode: Inactive

== Theme ==
	Name: De Rosa Webentwicklung
	Version: 1.0.0
	Author: Daniele De Rosa
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36

== Active Plugins ==
	Borlabs Cookie - Cookie Opt-in
		Version: 2.2.22
		Author: Benjamin A. Bornschein, Borlabs

	Elementor
		Version: 3.1.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.2.1
		Author: Elementor.com

	Imagify
		Version: 1.9.14
		Author: WP Media

	Starter Templates
		Version: 2.6.2
		Author: Brainstorm Force

	Ultimate Addons for Elementor
		Version: 1.29.2
		Author: Brainstorm Force


== Elementor - Compatibility Tag ==
	
	Elementor Pro: compatible
	Ultimate Addons for Elementor: compatible

== Elementor Pro - Compatibility Tag ==
	
	Ultimate Addons for Elementor: incompatible

== Elements Usage ==
	
	footer : 1
		facebook-page : 1
		icon-list : 2
		nav-menu : 1
		text-editor : 1
		uael-advanced-heading : 3
	header : 1
		image : 1
		nav-menu : 1
		social-icons : 1
	section : 2
		button : 1
		heading : 3
		social-icons : 1
		spacer : 1
	wp-page : 11
		button : 5
		divider : 4
		facebook-page : 1
		form : 1
		google_maps : 1
		heading : 25
		icon : 4
		icon-list : 1
		image : 8
		image-box : 3
		social-icons : 4
		spacer : 12
		template : 4
		testimonial-carousel : 1
		text-editor : 17
		toggle : 1
		uael-advanced-heading : 15
		uael-dual-color-heading : 9
		uael-image-gallery : 1
		uael-infobox : 4
	single-page : 1
		heading : 1
		theme-post-content : 1


== Log ==
	
PHP: showing 5 of 5PHP: 2021-02-05 10:50:51 [notice X 6][/www/htdocs/w0187e39/dev/towa/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-02-09 16:09:41 [notice X 6][/www/htdocs/w0187e39/dev/towa/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::297] The Plugin::$instance->posts_css_manager argument is <strong>deprecated</strong> since version 2.7.0! Use Plugin::$instance->files_manager instead. [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-02-23 12:13:49 [error X 2][/www/htdocs/w0187e39/dev/towa/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::281] Uncaught Error: Call to a member function update_meta() on null in /www/htdocs/w0187e39/dev/towa/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:281
Stack trace:
#0 /www/htdocs/w0187e39/dev/towa/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(162): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(11, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /www/htdocs/w0187e39/dev/towa/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /www/htdocs/w0187e39/dev/towa/wp-includes/class-wp-hook.php(287): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /www/htdocs/w0187e39/dev/towa/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#5 /www [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-02-23 12:51:49 [error X 1][/www/htdocs/w0187e39/dev/towa/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::281] Uncaught Error: Call to a member function update_meta() on bool in /www/htdocs/w0187e39/dev/towa/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:281
Stack trace:
#0 /www/htdocs/w0187e39/dev/towa/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(162): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /www/htdocs/w0187e39/dev/towa/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /www/htdocs/w0187e39/dev/towa/wp-includes/class-wp-hook.php(287): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /www/htdocs/w0187e39/dev/towa/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#5 /w [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-02-25 13:30:25 [notice X 1][/www/htdocs/w0187e39/dev/towa/wp-content/plugins/elementor-pro/core/upgrade/upgrades.php::911] Undefined index: pagination [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 4 of 4JS: 2021-02-23 11:36:04 [error X 1][https://dev.codepa.de/towa/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view12842\") has already been destroyed and cannot be used. 
JS: 2021-02-25 14:27:53 [error X 1][https://dev.codepa.de/towa/wp-content/plugins/elementor-pro/assets/js/preloaded-elements-handlers.min.js?ver=3.1.1:2:79976] Cannot read property \'setSpeed\' of null 
JS: 2021-03-22 15:55:59 [error X 1][https://dev.codepa.de/towa/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view77\") has already been destroyed and cannot be used. 
JS: 2021-03-23 11:42:04 [error X 1][https://dev.codepa.de/towa/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view755\") has already been destroyed and cannot be used. 

Log: showing 13 of 132021-02-25 13:30:24 [info] elementor-pro::elementor_pro_updater Started 
2021-02-25 13:30:24 [info] Elementor Pro/Upgrades - _v_3_1_0_media_carousel Start  
2021-02-25 13:30:25 [info] Elementor Pro/Upgrades - _v_3_1_0_media_carousel Finished 
2021-02-25 13:30:25 [info] Elementor Pro/Upgrades - _v_3_1_0_reviews Start  
2021-02-25 13:30:25 [info] Elementor Pro/Upgrades - _v_3_1_0_reviews Finished 
2021-02-25 13:30:25 [info] Elementor Pro/Upgrades - _v_3_1_0_testimonial_carousel Start  
2021-02-25 13:30:25 [info] Elementor Pro/Upgrades - _v_3_1_0_testimonial_carousel Finished 
2021-02-25 13:30:25 [info] Elementor Pro/Upgrades - _v_3_1_0_slides Start  
2021-02-25 13:30:25 [info] Elementor Pro/Upgrades - _v_3_1_0_slides Finished 
2021-02-25 13:30:25 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.10',
  'to' => '3.1.1',
)]
2021-02-25 13:30:25 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.10',
  'to' => '3.1.1',
)]
2021-03-23 12:42:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.1',
  'to' => '3.1.4',
)]
2021-03-23 12:43:26 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.1.1',
  'to' => '3.2.1',
)]


				
```
</details>

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
