### ISSUE TITLE
Widget with default values are null

### ISSUE THREAD

**Issue by Mte90** [elementor/elementor#14379]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

```
Fatal error:  Uncaught TypeError: Argument 2 passed to get_glossary_terms_list() must be of the type int, null given, called in /srv/www/glossary/public_html/wp-content/plugins/glossary/integrations/Widgets/Last_Glossaries.php on line 110 and defined in /srv/www/glossary/public_html/wp-content/plugins/glossary/functions/functions.php:21
Stack trace:
#0 /srv/www/glossary/public_html/wp-content/plugins/glossary/integrations/Widgets/Last_Glossaries.php(110): get_glossary_terms_list('last', NULL, Array)
#1 /srv/www/glossary/public_html/wp-content/plugins/elementor/includes/widgets/wordpress.php(271): Glossary\Integrations\Widgets\Last_Glossaries->widget(Array, Array)
#2 /srv/www/glossary/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(1892): Elementor\Widget_WordPress->render()
#3 /srv/www/glossary/public_html/wp-content/plugins/elementor/includes/base/widget-base.php(549): Elementor\Controls_Stack->render_by_mode()
#4 /srv/www/glossary/public_html/wp-content" while reading response header from 
2021/03/29 13:30:03 [error] 3829#3829: *164 open() "/srv/www/glossary/public_html/favicon.ico" failed (2: No such file or directory), client: 192.168.50.1, server: glossary.test, request: "GET /favicon.ico HTTP/1.1", host: "glossary.test", referrer: "http://glossary.test/wp-admin/plugins.php?plugin_status=all&paged=1&s&elementor_updater=continue&_wpnonce=4c3bf298f9"
```

## Steps to reproduce

Try installing https://wordpress.org/plugins/glossary-by-codeat/ move on Elementor edit view of a post. Switch to WordPress widget and add the GLossary Latest Terms widget.  
If you use the WordPress native widget view there aren't errors, so I guess that the implementation to initialize a widget is not complete (as per https://github.com/elementor/elementor/blob/master/includes/widgets/wordpress.php).

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
php 7.3 and latest wp version.
```
</details>

**Comment by Mte90** [comment]
a ping
