### ISSUE TITLE
Theme builder crash (error 500) with Yoast Seo 16.1

### ISSUE THREAD

**Issue by adverman** [elementor/elementor#14454]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

After the Yoast 16.1 update (April 6, 2021), it is not possible to save theme builder templates. A 500 server error is returned.

## Steps to reproduce
Open a template and try to save it.

## Error log
![image](https://user-images.githubusercontent.com/8201505/113735078-2e70c700-96fc-11eb-818b-f3574befb6d6.png)

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>

== Server Environment ==
	Operating System: Linux
	Software: nginx/1.19.8
	MySQL version: mariadb.org binary distribution v10.5.9
	PHP Version: 7.3.27-9+ubuntu20.04.1+deb.sury.org+1
	PHP Max Input Vars: 10000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.7
	Site URL: 
	Home URL: 
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: it-IT
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.3.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: it_IT
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36

== Active Plugins ==
	Classic Editor
		Version: 1.6
		Author: WordPress Contributors

	Elementor
		Version: 3.1.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.2.1
		Author: Elementor.com

	Regenerate Thumbnails
		Version: 3.1.5
		Author: Alex Mills (Viper007Bond)

	Safe SVG
		Version: 1.9.9
		Author: Daryll Doyle

	Yoast SEO
		Version: 16.1
		Author: Team Yoast

== Must-Use Plugins ==
	Kinsta Must-use Plugins
		Version: 2.3.4
		Author: Kinsta Team

== Elementor - Compatibility Tag ==
	
	Elementor Pro: compatible

== Elementor Pro - Compatibility Tag ==
	

== Elements Usage ==
	
	footer : 1
		social-icons : 1
		theme-site-logo : 1
	header : 1
		nav-menu : 1
		theme-site-logo : 1
	popup : 1
		form : 1
		heading : 1
	wp-page : 1
		button : 1
		heading : 14
		icon : 3
		image : 6
		image-carousel : 5
		spacer : 1
		text-editor : 13
		video : 1

== Log ==
	
Log: showing 11 of 112021-03-31 14:37:33 [info] elementor-pro::elementor_pro_updater Started 
2021-03-31 14:37:33 [info] Elementor Pro/Upgrades - _v_3_1_0_media_carousel Start  
2021-03-31 14:37:33 [info] Elementor Pro/Upgrades - _v_3_1_0_media_carousel Finished 
2021-03-31 14:37:33 [info] Elementor Pro/Upgrades - _v_3_1_0_reviews Start  
2021-03-31 14:37:33 [info] Elementor Pro/Upgrades - _v_3_1_0_reviews Finished 
2021-03-31 14:37:33 [info] Elementor Pro/Upgrades - _v_3_1_0_testimonial_carousel Start  
2021-03-31 14:37:33 [info] Elementor Pro/Upgrades - _v_3_1_0_testimonial_carousel Finished 
2021-03-31 14:37:33 [info] Elementor Pro/Upgrades - _v_3_1_0_slides Start  
2021-03-31 14:37:33 [info] Elementor Pro/Upgrades - _v_3_1_0_slides Finished 
2021-03-31 14:37:33 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.10',
  'to' => '3.2.1',
)]
2021-03-31 14:37:33 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.10',
  'to' => '3.2.1',
)]

PHP: showing 3 of 3PHP: 2021-03-31 14:47:20 [warning X 5][/www/public/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::538] libxml_disable_entity_loader() has been disabled for security reasons [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-06 08:31:26 [error X 1][/www/public/wp-content/plugins/elementor-pro/modules/popup/module.php::98] Uncaught Error: Call to undefined method Elementor\Core\Kits\Documents\Kit::save_display_settings_data() in /www/public/wp-content/plugins/elementor-pro/modules/popup/module.php:98
Stack trace:
#0 [internal function]: ElementorPro\Modules\Popup\Module->save_display_settings(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#1 /www/public/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /www/public/wp-includes/class-wp-hook.php(292): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#3 /www/public/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters('', Array)
#4 /www/public/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#5 /www/public/wp-admin/admin-ajax.php(187): do_action('wp_ajax_element...')
#6 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-06 09:06:27 [notice X 3][/www/public/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

</details>

**Comment by adverman** [comment]
### Solved with Yoast 1.6.1.1

16.1.1
Release Date: April 6th, 2021

Bugfixes:

Fixes a bug where a fatal error would be thrown when creating a new Elementor template or editing an existing one.
