### ISSUE TITLE
Elementor Page Layout doesn't change when using WordPress Bulk Edit / Quick Edit to change template from Default to Elementor Full Width

### ISSUE THREAD

**Issue by d19dotca** [elementor/elementor#14522]
## Prerequisites
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

When using the WordPress interface to change the Page Layout (aka "Template") in Theme Builder from Default to Elementor Full Width, for example, Elementor doesn't seem to respect the change.

In other words, I can properly change the Page Layout if I follow the instructions in the [Elementor Documentation](https://elementor.com/help/using-elementors-full-width-page-template/) however I cannot achieve the same result using the WordPress interface to change them in bulk.

## Steps to reproduce

1. Go to WordPress Admin > Elementor Templates > Theme Builder
2. In the Theme Builder template list, choose one and click on Quick Edit
3. Change Template from Default to Elementor Full Width <img width="1233" alt="image" src="https://user-images.githubusercontent.com/8153796/114344528-d7605d00-9b14-11eb-99bd-c98bfded8adb.png">
4. Save the change
5. Now click Edit With Elementor on the same template edited in step 2 above, and go to Page Settings by clicking the gear icon in the lower left corner of the editor. Notice the selection is still Default, not Elementor Full Width. <img width="294" alt="image" src="https://user-images.githubusercontent.com/8153796/114344642-0ecf0980-9b15-11eb-810e-58971470bdb9.png">

Second way of reproducing this is using the Wordpress bulk editing functionality:
1. Go to WordPress Admin > Elementor Templates > Theme Builder
2. Select several templates and click on Bulk Edit dropdown > Edit
3. Change Template from Default to Elementor Full Width <img width="1097" alt="image" src="https://user-images.githubusercontent.com/8153796/114344815-5bb2e000-9b15-11eb-9775-124b058299e5.png">
4. Save the change
5. Now click Edit With Elementor on any of the templates edited in step 2 above, and go to Page Settings by clicking the gear icon in the lower left corner of the editor. Notice the selection is still Default, not Elementor Full Width. <img width="294" alt="image" src="https://user-images.githubusercontent.com/8153796/114344642-0ecf0980-9b15-11eb-810e-58971470bdb9.png">

## Isolating the problem
- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.41 (Ubuntu)
	MySQL version: (Ubuntu) v8.0.23
	PHP Version: 7.4.3
	PHP Max Input Vars: 3000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.7
	Site URL: https://www.example.com
	Home URL: https://www.example.com
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 512M
	Permalink Structure: /%category%/%postname%/
	Language: en-CA
	Timezone: America/Vancouver
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.3.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_CA
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1 Safari/605.1.15

== Active Plugins ==
	AuthLDAP
		Version: 2.4.10
		Author: Andreas Heigl <andreas@heigl.org>

	Better Search Replace
		Version: 1.3.4
		Author: Delicious Brains

	Elementor
		Version: 3.1.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.2.1
		Author: Elementor.com

	Enable Media Replace
		Version: 3.5.0
		Author: ShortPixel

	MainWP Child
		Version: 4.1.5
		Author: MainWP

	MainWP Key Maker
		Version: 1.2
		Author: MainWP

	Pods - Custom Content Types and Fields
		Version: 2.7.26
		Author: Pods Framework Team

	Rank Math SEO
		Version: 1.0.61.1
		Author: Rank Math

	Rank Math SEO PRO
		Version: 2.5.1
		Author: Rank Math

	Redis Object Cache
		Version: 2.0.17
		Author: Till Krüss

	ShortPixel Image Optimizer
		Version: 4.21.2
		Author: ShortPixel

	SMTP Mailer
		Version: 1.1.1
		Author: naa986

	ToolKit For Elementor
		Version: 1.3.8
		Author: ToolKit For Elementor

	WP-Matomo Integration
		Version: 1.0.24
		Author: André Bräkling


== Elementor - Compatibility Tag ==
	
	Elementor Pro: compatible
	ToolKit For Elementor: compatible

== Elementor Pro - Compatibility Tag ==
	
	ToolKit For Elementor: compatible

== Elements Usage ==
	
	archive : 1
		archive-posts : 1
		theme-archive-title : 1
	footer : 1
		divider : 1
		heading : 4
		nav-menu : 1
		search-form : 1
		social-icons : 1
		text-editor : 4
	header : 1
		icon-list : 1
		nav-menu : 1
		theme-site-logo : 1
	section : 1
		heading : 1
		posts : 1
	single : 2
		global : 1
		heading : 1
		image : 1
		post-info : 1
		post-navigation : 1
		share-buttons : 1
		text-editor : 1
		theme-post-content : 2
		theme-post-title : 2
	widget : 0
		form : 57
	wp-post : 8
		accordion : 1
		alert : 4
		button : 17
		code-highlight : 2
		counter : 2
		divider : 2
		form : 2
		global : 4
		heading : 51
		icon-box : 7
		icon-list : 6
		image : 1
		lottie : 4
		portfolio : 1
		social-icons : 3
		table-of-contents : 1
		tabs : 3
		template : 1
		testimonial-carousel : 1
		text-editor : 90
		toggle : 1
	wp-page : 13
		accordion : 1
		alert : 1
		button : 13
		call-to-action : 1
		divider : 2
		facebook-page : 1
		form : 1
		heading : 18
		lottie : 1
		menu-anchor : 4
		posts : 2
		price-list : 2
		price-table : 12
		social-icons : 2
		template : 1
		text-editor : 26
	single-post : 1
		button : 1
		divider : 1
		heading : 1
		image : 1
		portfolio : 1
		post-info : 1
		text-editor : 1
		theme-post-content : 1
		theme-post-title : 1
	single-page : 1
		shortcode : 1
		table-of-contents : 1
		text-editor : 1
		theme-post-content : 1
		theme-post-title : 1
	search-results : 1
		archive-posts : 1
		theme-archive-title : 1
	error-404 : 1
		heading : 2
		nav-menu : 1
		search-form : 1


== Log ==
	
Log: showing 20 of 282020-12-29 16:46:43 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.8',
  'to' => '3.0.9',
)]
2021-01-06 08:56:21 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.15',
  'to' => '3.0.16',
)]
2021-01-25 13:35:56 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.16',
  'to' => '3.1.0',
)]
2021-01-25 13:36:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.9',
  'to' => '3.0.10',
)]
2021-01-31 15:07:08 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.0',
  'to' => '3.1.1',
)]
2021-02-14 10:07:54 [info] elementor-pro::elementor_pro_updater Started 
2021-02-14 10:07:54 [info] Elementor Pro/Upgrades - _v_3_1_0_media_carousel Start  
2021-02-14 10:07:55 [info] Elementor Pro/Upgrades - _v_3_1_0_media_carousel Finished 
2021-02-14 10:07:55 [info] Elementor Pro/Upgrades - _v_3_1_0_reviews Start  
2021-02-14 10:07:55 [info] Elementor Pro/Upgrades - _v_3_1_0_reviews Finished 
2021-02-14 10:07:55 [info] Elementor Pro/Upgrades - _v_3_1_0_testimonial_carousel Start  
2021-02-14 10:07:55 [info] Elementor Pro/Upgrades - _v_3_1_0_testimonial_carousel Finished 
2021-02-14 10:07:55 [info] Elementor Pro/Upgrades - _v_3_1_0_slides Start  
2021-02-14 10:07:55 [info] Elementor Pro/Upgrades - _v_3_1_0_slides Finished 
2021-02-14 10:07:55 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.10',
  'to' => '3.1.0',
)]
2021-02-24 16:22:49 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.1.0',
  'to' => '3.1.1',
)]
2021-03-03 16:29:34 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.1',
  'to' => '3.1.3',
)]
2021-03-10 21:16:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.3',
  'to' => '3.1.4',
)]
2021-03-16 11:17:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.1.1',
  'to' => '3.2.0',
)]
2021-03-22 09:39:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.2.0',
  'to' => '3.2.1',
)]

JS: showing 10 of 10JS: 2020-09-28 05:18:37 [error X 1][https://www.example.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.10:2:421617] t.ui.sync.removeClass is not a function. (In \'t.ui.sync.removeClass(\"eicon-animation-spin\")\', \'t.ui.sync.removeClass\' is undefined) 
JS: 2021-02-20 01:24:09 [error X 1][https://www.example.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view832\") has already been destroyed and cannot be used. 
JS: 2021-02-22 22:01:48 [error X 2][https://www.example.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:17421] Could not find template: \"#tmpl-elementor-templates-modal__header\" 
JS: 2021-02-23 01:14:58 [error X 1][https://www.example.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view890\") has already been destroyed and cannot be used. 
JS: 2021-03-02 21:47:26 [error X 1][https://www.example.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view1945\") has already been destroyed and cannot be used. 
JS: 2021-03-02 21:49:28 [error X 1][https://www.example.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view735\") has already been destroyed and cannot be used. 
JS: 2021-03-02 23:18:26 [error X 6][https://www.example.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view120\") has already been destroyed and cannot be used. 
JS: 2021-03-02 23:18:59 [error X 1][https://www.example.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view912\") has already been destroyed and cannot be used. 
JS: 2021-03-02 23:20:50 [error X 1][https://www.example.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view4246\") has already been destroyed and cannot be used. 
JS: 2021-03-03 00:01:10 [error X 1][https://www.example.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view4774\") has already been destroyed and cannot be used. 

PHP: showing 4 of 4PHP: 2021-03-02 16:01:09 [error X 1][/app/data/public/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::281] Uncaught Error: Call to a member function update_meta() on bool in /app/data/public/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:281
Stack trace:
#0 /app/data/public/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(162): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions()
#2 /app/data/public/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func()
#3 /app/data/public/wp-includes/class-wp-hook.php(287): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#4 /app/data/public/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters()
#5 /app/data/public/wp-includes/plugin.php(484): WP_Hook->do_action()
#6 /app/data/public/wp-admin/admin-ajax.php(184): do_action()
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-09 11:54:39 [notice X 12][/app/data/public/wp-content/plugins/elementor-pro/license/updater.php::75] Undefined index: new_version [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-16 11:19:22 [notice X 4][/app/data/public/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-16 11:21:06 [notice X 2][/app/data/public/wp-content/plugins/elementor-pro/modules/forms/classes/ajax-handler.php::244] Undefined index: post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
```
</details>

**Comment by DorShahar** [comment]
Hi @d19dotca 
Thank you for taking the time and reporting this.

We recreated your process of work and it seems to work properly on the latest version.

Thanks.

**Comment by localghost8000** [comment]
This is still an issue on all environments I've tested.
