### ISSUE TITLE
"Uncaught TypeError" - Conflict between Elementor and other plugin

### ISSUE THREAD

**Issue by valentina-arras** [elementor/elementor#14541]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [ x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

Hello,
I'm opening this issue as requested by one of your colleagues. 
One client of mine has problems modifying the page with Elementor when our plugin is active. He contacts your team first, and you advised him to contact us because the problem occurs just if our plugin is enabled.
Once our widget is active on the page, they get in the Elementor front-end editor the following 500 error:

`Uncaught TypeError: Argument 1 passed to Elementor\Controls_Stack::sanitize_settings() must be of the type array, null given, called in /home/ebadbedc/stanstedlodge.com/wp-content/plugins/elementor/includes/base/controls-stack.php on line 987 and defined in /home/ebadbedc/stanstedlodge.com/wp-content/plugins/elementor/includes/base/controls-stack.php:2038
Stack trace:
#0 /home/ebadbedc/stanstedlodge.com/wp-content/plugins/elementor/includes/base/controls-stack.php(987): Elementor\Controls_Stack->sanitize_settings(NULL)
#1 /home/ebadbedc/stanstedlodge.com/wp-content/plugins/elementor/includes/base/controls-stack.php(1787): Elementor\Controls_Stack->get_data('settings')
#2 /home/ebadbedc/stanstedlodge.com/wp-content/plugins/elementor/core/base/base-object.php(142): Elementor\Controls_Stack->get_init_settings()
#3 /home/ebadbedc/stanstedlodge.com/wp-content/plugins/elementor/core/base/base-object.php(40): Elementor\Core\Base\Base_Object->ensure_settings()
#4 /home/ebadbedc/stanstedlodge.com/wp-content/plugins/el`

Your colleague gave my client your Git repository to speak with your developers.
To understand how to fix the problem, we need more information about it. If you could tell us more information about the "settings" showed in the error, or if you could tell us what is bothering the Elementor code we can understand the problem better and start looking for a solution.

Thank you for your cooperation,
Best Regards,
Valentina

**Comment by stanstedlodge** [comment]
VikWP - message below is what I received from Elementor.
I have given Elementor all my system information, but you have login credentials so you can try again.

On Fri, Apr 30, 2021 at 7:36 AM <support@elementor.com> wrote:
Hi Quinton.
Thank you for getting back to us.

First of all, I will like to give my sincere apologies for the inconveniences you are having due to this issue and on our end, we assure you we will try our best to direct you in the best way we can to resolve this issue.

As my colleague mentioned earlier when the debug mode is activated the error is resolved and this usually happens due to conflict from third-party plugins that may not be compatible with the latest version of Elementor or Elementor Pro.

To forward give you more information on this issue and what plugin is causing the issue, I accessed your site to investigate this further and I can confirm that the "VikWidgetsLoader" plugin was resulting in this error. With the plugin deactivated everything works correctly.

Please refer to this screencast to see the issue with this plugin: http://somup.com/crfvibFwaz

In this case, I hope you will understand that this issue needs to be checked by the third-party plugin causing the issue or conflicting with Elementor, as we have no control over coding for third-party plugins nor themes, we highly recommend that you report this issue to the support team for this plugin so they may further troubleshoot and provide any recommendation (or possible fix) to resolve this issue.
What we support

That being said please note that Elementor Pro works correctly and is stable, however, we cannot guarantee that the third-party plugin you are using on your site will work well with the latest version which is why we recommend that third-party plugin authors ensure to update their plugins accordingly to avoid any conflict. And as you can see from my screencast the third-party plugin you are using is causing the conflict and that needs to be further checked by the developers of that plugin.

Also in regards to Gitbuh, please note that this support channel is different from Github and we do not have control over github support channel from our end as a technical support agent, which is why if you are reporting any issue to github you need to add all information needed for the developers to help them assist you appropriately. But on our end, we are unable to add your system to the github thread as we do not have access to this even if we want to add this, and we appreciate your understanding.

If you are the user that has opened this issue https://github.com/elementor/elementor/issues/14541, keep in mind that you also have to be the one to upload all your information including your system info as you are the one with access to the thread you opened.

Also I hope you will understand that if the developers of the plugin causing the conflict need further assistance from our end as their plugin doesn't seem to work well with Elementor, you need to first report the issue to them and then they (the developers of the plugin not you) can reach out to our developers for further assistance to make their plugin work well with Elementor.


I hope this clarifies things. Please feel free to contact us if you have any questions or need further assistance, we'd be more than happy to help.
Kind Regards.

**Comment by valentina-arras** [comment]
We have changed the description and add the system info. Maybe this will help to get an answer?
Thank you!

**Comment by udidol** [comment]
Hi @valentina-arras,
This issue only happens when you use a 3rd party plugin?
If so, I'm not sure we are able to help, and you should consult with the developers of the 3rd party plugin.

**Comment by DavidGMiles** [comment]
I can get this to happen with just Elementor and elementor Pro

Uncaught TypeError: Argument 1 passed to Elementor\Controls_Stack::sanitize_settings() must be of the type array, null given, called in /Users/davidmiles/Local Sites/devnl/app/public/wp-content/plugins/elementor/includes/base/controls-stack.php on line 1051 and defined in /Users/davidmiles/Local Sites/devnl/app/public/wp-content/plugins/elementor/includes/base/controls-stack.php:2290
Stack trace:
#0 /Users/davidmiles/Local Sites/devnl/app/public/wp-content/plugins/elementor/includes/base/controls-stack.php(1051): Elementor\Controls_Stack->sanitize_settings(NULL)
#1 /Users/davidmiles/Local Sites/devnl/app/public/wp-content/plugins/elementor/includes/base/controls-stack.php(2039): Elementor\Controls_Stack->get_data('settings')
#2 /Users/davidmiles/Local Sites/devnl/app/public/wp-content/plugins/elementor/core/base/base-object.php(142): Elementor\Controls_Stack->get_init_settings()
#3 /Users/davidmiles/Local Sites/devnl/app/public/wp-content/plugins/elementor/core/base/base-object.php(40): Elementor\Core\Base\Ba

This is actually stopping any editing on the site at all - of any type

![santitize error](https://user-images.githubusercontent.com/20774089/130773774-80b95471-566c-4111-af8e-7abd236e3cd9.jpg)

**Comment by DavidGMiles** [comment]
@shilo-ey this is back - I noticed it in the beta - then it went away, but in final release it is back
