### ISSUE TITLE
Elementor Pro doesn't warn about updating regular Elementor first - which can break website

### ISSUE THREAD

**Issue by zevrix** [elementor/elementor#14576]
- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest stable version of Elementor.

## Description

Just updated to **Elementor Pro 3.2** - and went through a few minutes of unpleasant shock when my website got totally broken.

When I went to the Tools section to revert to the previous version, a message there kindly informed me that my Elementor Pro isn't working because my regular Elementor isn't updated.

After updating the regular Elementor everything went back to normal.

I don't update Elementor Pro that often for this to be implanted in my memory.

**Conclusion:**

If Elementor Pro requires an updated Elementor, then it should detect it prior to installing the Pro update - and inform the user that Elementor must be updated first.

Thanks,
Leo

**Comment by d19dotca** [comment]
If you check your WordPress Updates page, you should see an update for Elementor base if it exists already. Usually it's safe to update them all at any given point without one needing to rely on the other, because if a certain Elementor base version is required before Pro can be updated, you should see both updates presented together (and updating them together will be fine). So in this case it seems like maybe your WordPress didn't detect an Elementor base update right away but did immediately afterwards? Seems like more of a WordPress environmental issue than an Elementor issue.

**Comment by zevrix** [comment]
Thanks! Yes, I knew that my regular Elementor wasn't updated .

My point is: it's not immediately clear that, being an Elementor Pro user, I should care about updating the base version of Elementor at all.

And especially that the base version must be updated _prior_ to Elementor Pro.

(Plus their versions are also totally different, which made me think that I probably shouldn't update the base version as my Pro version is already higher).


All I know is that I updated Elementor Pro to 3.2 - and didn't receive any warnings. 

And yet when I opened my website, all Pro features were gone. Which happened, as it turned out, because the base version wasn't updated. And, like I mentioned, it didn't even cross my mind that updating the base version is important for a Pro user.

I believe that users should be protected from this kind of situation. If the Pro version relies on an updated base version, then user must get a clear warning during the Pro update that the base version must be updated as well.

Does it make sense?

**Comment by d19dotca** [comment]
For sure, the process can be improved. Funny enough I thought that Elementor introduced compatibility tags not too long ago which should have resolved that, I'd have thought.

**Comment by zevrix** [comment]
What the hell??

Updating to Elementor Pro 3.3.1 once again BROKE MY WEBSITE AND WORDPRESS.

Had to disable Elementor Pro via FTP.

WHY IT DOESN'T WARN THAT REGULAR ELEMENTOR MUST BE UPDATED FIRST??

How is it possible that Elementor Pro breaks the hell everything - as the installer is apparently unaware that the new version cannot function.

This is a total DISASTER. Totally unacceptable.

And BTW the "rollback" function doesn't do anything either - while it claims it did reinstall  an earlier version of Elementor Pro. I'll submit a separate bug on this.

Here's the error after updating to Elementor Pro 3.3.1: 

Fatal error: Uncaught Error: Cannot call constructor in /homepages/2/d200688780/htdocs/clickandbuilds/ZevrixSolutionsWPNew/wp-content/plugins/elementor-pro/modules/query-control/module.php:51 Stack trace: #0 /homepages/2/d200688780/htdocs/clickandbuilds/ZevrixSolutionsWPNew/wp-content/plugins/elementor/core/base/module.php(83): ElementorPro\Modules\QueryControl\Module->__construct() #1 /homepages/2/d200688780/htdocs/clickandbuilds/ZevrixSolutionsWPNew/wp-content/plugins/elementor-pro/core/modules-manager.php(70): Elementor\Core\Base\Module::instance() #2 /homepages/2/d200688780/htdocs/clickandbuilds/ZevrixSolutionsWPNew/wp-content/plugins/elementor-pro/plugin.php(311): ElementorPro\Core\Modules_Manager->__construct() #3 /homepages/2/d200688780/htdocs/clickandbuilds/ZevrixSolutionsWPNew/wp-includes/class-wp-hook.php(287): ElementorPro\Plugin->on_elementor_init('') #4 /homepages/2/d200688780/htdocs/clickandbuilds/ZevrixSolutionsWPNew/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array) #5 /homepages/2/d20 in /homepages/2/d200688780/htdocs/clickandbuilds/ZevrixSolutionsWPNew/wp-content/plugins/elementor-pro/modules/query-control/module.php on line 51
There has been a critical error on your website. Please check your site admin email inbox for instructions.

**Comment by d19dotca** [comment]
I have to be honest, I'm not quite understanding the issue here with the updates workflow that you're running into, because it doesn't seem like this is much of an issue for others. I've been running Elementor and Elementor Pro for almost 3 years now, and as you know there have been plenty of updates to them both in that time frame, and I've never encountered a scenario yet where I'm updating "out of order" and has never caused any issues for me. So I'm trying to understand how such a situation even occurs and why this issue isn't more common if the ordering was constantly creating problems for users.

If you're updating using WordPress Updates functionality, then it'll update in the correct order automatically (at least it always does for me and I suspect others by updating Elementor core first and then Elementor Pro) in the situation where both have updates available. When only one has an update available, regardless of which package it is for, then that'll work fine too as it's only ever released when the other version is compatible with it. You'll also notice that - at least recently - Elementor Pro reaches the higher version before Elementor core does. I.e. Elementor Pro 3.3 was released over a month before Elementor 3.3 will be released.

So I guess my question is (which maybe you can't answer yet): What is different for you than for others when updating where the order of the updates is a problem?

**Comment by d19dotca** [comment]
Is it happening because you have updates to both versions, but are only installing the Pro update without installing the core update first? In other words, let's say you had Pro 3.3.1 to install (at 3.3.0 before updating) and you ALSO have core Elementor at 3.1.2 for example and it has an update too for 3.2... are you updating only Pro to 3.3.1 while leaving core at the 3.1.2 in that example?

**Comment by zevrix** [comment]
Thanks for your reply.

Yes, you describe the exactly correct scenario: I have both updates to the core Elementor and Elementor Pro available.

NOWHERE it implies that these two versions are linked in any way and that I should update the core version first. NOWHERE.

And it does allow me to install Elementor Pro - which fatally breaks both WordPress and my website. Which is beyond dangerous and wrong.


You mentioned that you upgraded 20+ Elementor sites - and that's exactly the reason why you don't have this issue. As you're obviously a seasoned web professional who's immersed in the world of web software constantly.

I'm just a humble Mac developer who also runs my own website. I'm not deeply invested in the inner workings of web software.

If WordPress plug-ins page lists an Elementor Pro update AND allows me to update, then I will update it. Because there's no reason not to.

And if it results in wiping out my both WordPress and website then, with all due respect, Elementor developers just didn't do their job properly as far as the upgrade procedure is concerned.

**Comment by d19dotca** [comment]
Totally fair. I agree, if there's room for improvement then it should be taken. :-) 

I wonder if they're a bit limited by WordPress's update capabilities to enforce that one version is installed before the other. They may only have the capabilities to add in notices and not actually stop the update from happening out of order (which would have been helpful for those who update manually and remotely who aren't in the actual WordPress GUI).

At least you know the proper solution going forward though so you really shouldn't run into the issue again... always make sure you update the core version first if both packages have updates available, installing the Pro version second to the core (or both at the same time and WordPress will take care of the order).

**Comment by zevrix** [comment]
Who knows maybe I'll forget again. 

I don't think that in the year 2021 this kind of crucial compatibility dependence issue should rely on the user hopefully remembering whatever something! That's not a good development and implementation practice.

I'd expect than when I click _Upgrade_ of the Pro version, it would first check the installed version of the core Elementor. If the core version is incompatible, a warning should be displayed with appropriate instructions, and the upgrade should be cancelled.

Does WordPress prevent plug-in developers from checking the installed version of another plug-in first?

If it does prevent, then a clear ALL CAPS warning must be included in the upgrade info displayed for Elementor Pro that instructs the user to upgrade the core Elementor first, if needed.

**Comment by d19dotca** [comment]
Curious @zevrix - why only update one of the packages instead of both when both have updates available? Is there a reason for doing the Pro updates only?

**Comment by zevrix** [comment]
Of course. I know that I'm using - and paying for - Elementor Pro.

In my dashboard, I see that there's an update available for Elementor Pro. I click _Update_. Why wouldn't I? That's basically the end of discussion! Anything else is the responsibility of the **developers**. Users don't need to be concerned with the internal workings of their software.

Now, to expand further:

Yes, I may (or may not) notice that there's also an update to the core Elementor. Now what? I don't even know what it means. 

Do the core and Pro version have any dependency? Will I invalidate my paid Pro version if I update the free version? Their version numbers are totally different. Should I actually _uninstall_ the free version if I already have the Pro version? It's not at all a common practice to have both Pro and free version of software installed.

As a user, I shouldn't be concerned with any of this. It's the developers' responsibility to make sure I have total peace of mind when I update their software. 

I know that my customers would be very unhappy if I forced them to understand how my software works instead of just using it. Not to mention that otherwise my software would sock them with fatal errors that seemingly imply that customer's crucial data is all but wiped out!
