### ISSUE TITLE
Form Entry for Form with Discord Action After submit errors when submission exceeds discords post character cap.

### ISSUE THREAD

**Issue by SaltedLevity** [elementor/elementor#14635]
## Prerequisites

- [ x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x ] The issue still exists against the latest stable version of Elementor.

## Description

When a user submits a form built with the Discord webhook option included for "Actions After Submit," if the entire submission exceeds the length that discord can embed in a message, the user submission fails _entirely_ (rather than being submitted but failing to appear on discord while other actions function like email).

In addition I haven't tested it fully, but other form field submission types can also prevent submissions from being completed if discord doesn't support them. For example if a form is built with an HTML field added for design purposes, the form will not submit.

The bug portion is in the failure to submit and the failure to provide any sort of error message explaining what happened to troubleshoot. However some possible/expected solutions:
1. Form still submits when there is a discord error but there are other actions after submit added, so the user response is still captured (e.g. I have discord + email, discord won't go through, but email does)
2. Form submits and the discord webhook just hard cuts off/truncates at the character cap
3. Option to add a character cap to the text area field so a website owner can at least manually set a limit so the form is less likely to fail
4. Option in the Discord Actions After Submit settings to pick and choose which fields are submitted to the webhook. This would also allow form builders to exclude known fields that will break the webhook (like the HTML field) while still getting SOME of the info into a discord message.

## Steps to reproduce

1) Create a form with a text area field
2) Include a discord webhook as an option for "Actions After Submit"
3) Attempt to submit the form with text that exceeds discord's character limit for a post (or an embed).

## Isolating the problem

- [ x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ x ] This bug happens with a default WordPress theme active.
- [ x ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.29
	PHP Version: 7.4.11
	PHP Max Input Vars: 1000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.7
	Site URL: https://saltedxiv.com
	Home URL: https://saltedxiv.com
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 256M
	Permalink Structure: /%postname%
	Language: en-US
	Timezone: America/New_York
	Debug Mode: Inactive

== Theme ==
	Name: Salted Hello Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.3.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.128 Safari/537.36

== Active Plugins ==
	ACF Conditional Taxonomy Rules
		Version: 3.0.1
		Author: mattkeys

	ACF Frontend (Premium)
		Version: 2.7.5
		Author: Shabti Kaplan

	Advanced Custom Fields
		Version: 5.9.5
		Author: Elliot Condon

	Classic Editor
		Version: 1.6
		Author: WordPress Contributors

	Cloudflare
		Version: 4.4.0
		Author: Cloudflare, Inc.

	Custom Adobe Fonts (Typekit)
		Version: 1.0.18
		Author: Brainstorm Force

	Custom Post Type UI
		Version: 1.9.1
		Author: WebDevStudios

	Custom Taxonomy Order
		Version: 3.3.0
		Author: Marcel Pol

	DreamHost Panel Login
		Version: 1.0.0
		Author: DreamHost, danielbachhuber

	DynamicConditions
		Version: 1.5.1
		Author: RTO GmbH

	Ele Custom Skin
		Version: 3.0.0
		Author: Dudaster.com

	Ele Custom Skin Pro
		Version: 3.0.0
		Author: Dudaster.com

	Elementor
		Version: 3.1.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.2.1
		Author: Elementor.com

	Enable Media Replace
		Version: 3.5.0
		Author: ShortPixel

	Feedzy RSS Feeds Lite
		Version: 3.6.0
		Author: Themeisle

	Feedzy RSS Feeds Premium
		Version: 1.7.0
		Author: Themeisle

	Google Analytics for WordPress by MonsterInsights
		Version: 7.17.0
		Author: MonsterInsights

	Jetpack by WordPress.com
		Version: 9.6.1
		Author: Automattic

	Max Mega Menu
		Version: 2.9.3
		Author: megamenu.com

	Page Links To
		Version: 3.3.5
		Author: Mark Jaquith

	Post Type Switcher
		Version: 3.2.0
		Author: John James Jacoby

	Proxy Cache Purge
		Version: 5.0
		Author: Mika Epstein

	PublishPress Permissions
		Version: 3.5.2
		Author: PublishPress

	Really Simple SSL
		Version: 4.0.14
		Author: Really Simple Plugins

	Redirection
		Version: 5.1.1
		Author: John Godley

	Smush Pro
		Version: 3.8.4
		Author: WPMU DEV

	TablePress
		Version: 1.13
		Author: Tobias Bäthge

	WPMU DEV Dashboard
		Version: 4.10.8.1
		Author: WPMU DEV

	Yoast Duplicate Post
		Version: 4.1.2
		Author: Enrico Battocchi & Team Yoast

	Yoast SEO
		Version: 16.1.1
		Author: Team Yoast


== Elementor - Compatibility Tag ==
	
	Elementor Pro: compatible

== Elementor Pro - Compatibility Tag ==
	


== Elements Usage ==
	
	archive : 7
		archive-posts : 6
		button : 4
		heading : 18
		icon-list : 34
		posts : 2
		share-buttons : 6
	footer : 1
		button : 2
		heading : 5
		nav-menu : 3
		social-icons : 1
		text-editor : 1
		theme-site-logo : 1
	header : 3
		button : 1
		global : 1
		search-form : 1
		social-icons : 4
		spacer : 1
		theme-site-logo : 2
		wp-widget-maxmegamenu : 1
	loop : 13
		button : 1
		call-to-action : 9
		heading : 8
		html : 1
		icon : 9
		image : 5
		image-box : 1
		post-info : 4
		text-editor : 3
		theme-post-featured-image : 2
		theme-post-title : 2
		video : 1
	page : 8
		archive-posts : 1
		author-box : 1
		button : 3
		call-to-action : 7
		divider : 6
		global : 9
		heading : 63
		html : 1
		icon : -13
		icon-box : 5
		icon-list : 2
		image : 5
		posts : 1
		share-buttons : 1
		social-icons : 3
		spacer : 9
		text-editor : 33
		toggle : 21
	popup : 6
		button : 1
		form : 2
		heading : 6
		icon-list : 1
		image : 1
		nav-menu : 1
		spacer : 3
		template : 1
		text-editor : 4
		theme-site-logo : 2
	section : 23
		acf_ele_form : 1
		call-to-action : 78
		divider : 9
		heading : 30
		icon : 14
		icon-list : 13
		image : 12
		image-box : 5
		posts : 1
		social-icons : 1
		spacer : 17
		text-editor : 23
	single : 5
		breadcrumbs : 1
		button : 1
		global : 1
		heading : 6
		icon : 8
		image : 3
		post-info : 2
		sidebar : 1
		spacer : 1
		text-editor : 5
		theme-post-content : 3
		theme-post-featured-image : 1
		theme-post-title : 1
	widget : 0
		button : 10
		call-to-action : 5
		html : 100
		icon-box : 22
		image : 2
		search-form : 159
		spacer : 1691
		table-of-contents : 359
		text-editor : 91
		toggle : 81
	wp-post : 3
		accordion : 16
		author-box : 14
		blockquote : 3
		button : 34
		call-to-action : 38
		divider : 76
		gallery : 4
		global : 286
		heading : 958
		html : 15
		icon : 19
		icon-box : 11
		icon-list : 17
		image : 169
		image-box : 1
		image-carousel : 1
		menu-anchor : 35
		post-info : 1
		slides : 1
		social-icons : 22
		spacer : 77
		text-editor : 1060
		toggle : 59
		video : 8
	wp-page : 58
		accordion : 1
		animated-headline : 1
		button : 69
		call-to-action : 96
		divider : 121
		form : 1
		gallery : 2
		global : 117
		heading : 794
		html : -69
		icon : 64
		icon-box : 27
		icon-list : 67
		image : 120
		media-carousel : 1
		menu-anchor : 8
		portfolio : 2
		posts : 132
		share-buttons : 1
		shortcode : 7
		social-icons : 14
		spacer : 138
		table-of-contents : 7
		tabs : 2
		template : 19
		text-editor : 433
		theme-site-logo : 1
		toggle : 115
		video : 18
	single-post : 1
		heading : 4
		html : 1
		post-info : 1
		posts : 1
		share-buttons : 1
		theme-post-content : 1
	single-page : 3
		heading : 3
		template : 3
		theme-post-content : 3
	search-results : 1
		archive-posts : 1
		heading : 3
		posts : 1
		share-buttons : 1
	error-404 : 1
		heading : 5
		icon-list : 1
		search-form : 1
		spacer : 3


== Log ==
	
Log: showing 20 of 342021-02-25 01:08:49 [info] Elementor Pro/Upgrades - _v_3_1_0_reviews Start  
2021-02-25 01:09:00 [info] Elementor Pro/Upgrades - _v_3_1_0_reviews Finished 
2021-02-25 01:09:05 [info] elementor-pro::elementor_pro_updater Started 
2021-02-25 01:09:05 [info] Elementor Pro/Upgrades - _v_3_1_0_testimonial_carousel Start  
2021-02-25 01:09:10 [info] Elementor Pro/Upgrades - _v_3_1_0_testimonial_carousel Finished 
2021-02-25 01:09:10 [info] Elementor Pro/Upgrades - _v_3_1_0_slides Start  
2021-02-25 01:09:15 [info] Elementor Pro/Upgrades - _v_3_1_0_slides Finished 
2021-02-25 01:09:15 [info] Elementor Pro/Upgrades - _v_3_1_0_media_carousel Start  
2021-02-25 01:09:20 [info] Elementor Pro/Upgrades - _v_3_1_0_media_carousel Finished 
2021-02-25 01:09:20 [info] Elementor Pro/Upgrades - _v_3_1_0_reviews Start  
2021-02-25 01:09:25 [info] Elementor Pro/Upgrades - _v_3_1_0_reviews Finished 
2021-02-25 01:09:26 [info] elementor-pro::elementor_pro_updater Started 
2021-02-25 01:09:26 [info] Elementor Pro/Upgrades - _v_3_1_0_testimonial_carousel Start  
2021-02-25 01:09:31 [info] Elementor Pro/Upgrades - _v_3_1_0_testimonial_carousel Finished 
2021-02-25 01:09:31 [info] Elementor Pro/Upgrades - _v_3_1_0_slides Start  
2021-02-25 01:09:36 [info] Elementor Pro/Upgrades - _v_3_1_0_slides Finished 
2021-02-25 01:09:36 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.1.0',
  'to' => '3.1.1',
)]
2021-03-09 22:27:17 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.1',
  'to' => '3.1.3',
)]
2021-03-12 20:54:53 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.3',
  'to' => '3.1.4',
)]
2021-04-04 19:29:37 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.1.1',
  'to' => '3.2.1',
)]

PHP: showing 6 of 6PHP: 2021-02-22 04:46:42 [notice X 5][/home/wp_s6kp8b/saltedxiv.com/wp-content/plugins/elementor-pro/core/upgrade/upgrades.php::911] Undefined index: pagination [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-02-26 18:47:05 [notice X 2][/home/wp_s6kp8b/saltedxiv.com/wp-content/plugins/elementor/includes/managers/image.php::86] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-09 21:17:33 [notice X 9][/home/wp_s6kp8b/saltedxiv.com/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-14 07:14:11 [notice X 3][/home/wp_s6kp8b/saltedxiv.com/wp-content/plugins/elementor/includes/embed.php::156] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-16 00:59:58 [error X 1][/home/wp_s6kp8b/saltedxiv.com/wp-content/plugins/elementor-pro/modules/query-control/module.php::21] Uncaught Error: Class 'ElementorPro\Base\Module_Base' not found in /home/wp_s6kp8b/saltedxiv.com/wp-content/plugins/elementor-pro/modules/query-control/module.php:21
Stack trace:
#0 /home/wp_s6kp8b/saltedxiv.com/wp-content/plugins/elementor-pro/plugin.php(140): include()
#1 [internal function]: ElementorPro\Plugin->autoload('ElementorPro\\Mo...')
#2 /home/wp_s6kp8b/saltedxiv.com/wp-content/plugins/elementor-pro/core/modules-manager.php(65): spl_autoload_call('ElementorPro\\Mo...')
#3 /home/wp_s6kp8b/saltedxiv.com/wp-content/plugins/elementor-pro/plugin.php(306): ElementorPro\Core\Modules_Manager->__construct()
#4 /home/wp_s6kp8b/saltedxiv.com/wp-includes/class-wp-hook.php(292): ElementorPro\Plugin->on_elementor_init('')
#5 /home/wp_s6kp8b/saltedxiv.com/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters('', Array)
#6 /home/wp_s6kp8b/saltedxiv.com/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#7 /home/wp_s6kp8b/saltedxiv.com/wp-content/plugins/elementor/includes/plugin.php(541): do_action('elem [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-04 01:22:13 [notice X 266][/home/wp_s6kp8b/saltedxiv.com/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php::33] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 2 of 2JS: 2021-02-26 23:15:17 [error X 4][https://saltedxiv.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view397\") has already been destroyed and cannot be used. 
JS: 2021-02-26 23:16:47 [error X 1][https://saltedxiv.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view7834\") has already been destroyed and cannot be used. 


				
```
</details>

**Comment by marioch5** [comment]
Hey @SaltedLevity i am having this issue too, have you found any workaround??

**Comment by SaltedLevity** [comment]
> Hey @SaltedLevity i am having this issue too, have you found any workaround??

Only to remove all contents of the form (the form data toggle) in the discord setting. Which isn't ideal but basically just means you'll get the alert in discord for a new form entry, but no info about it. 
Or just some text to tell users that the form will fail if the submitted character count is too long.
Both are pretty awful workarounds.
