### ISSUE TITLE
v3.2.1 - Background Image Position options are missing

### ISSUE THREAD

**Issue by DIntriglia** [elementor/elementor#14674]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Background Image positioning options are missing when selecting a background image on the Section or Column blocks.

## Steps to reproduce
1. Attach image
2. Notice there are no options for positioning

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release '36', Revision '7e403c5' v5.7.33-36
	PHP Version: 7.4.16
	PHP Max Input Vars: 10000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.7.1
	Site URL: https://surna2021.wpengine.com
	Home URL: https://surna2021.wpengine.com
	WP Multisite: No
	Max Upload Size: 50 MB
	Memory limit: 512M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: America/Denver
	Debug Mode: Inactive

== Theme ==
	Name: ESTUS Digital - Child Theme
	Version: 1.00
	Author: ESTUS Digital
	Child Theme: Yes
	Parent Theme Name: Astra
	Parent Theme Version: 3.3.3
	Parent Theme Author: Brainstorm Force

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.128 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 5.9.5
		Author: Elliot Condon

	All-in-One WP Migration
		Version: 7.41
		Author: ServMask

	All-in-One WP Migration FTP Extension
		Version: 2.64
		Author: ServMask

	Astra Pro
		Version: 3.3.2
		Author: Brainstorm Force

	Atarim - Client Interface Plugin
		Version: 2.0.7
		Author: Atarim

	Autoptimize
		Version: 2.8.3
		Author: Frank Goossens (futtta)

	Elementor
		Version: 3.2.1
		Author: Elementor.com

	Elementor - ESTUS
		Version: 1.0.4
		Author: ESTUS

	Elementor Pro
		Version: 3.2.1
		Author: Elementor.com

	ESTUS Plugin Manager
		Version: 1.0.11
		Author: ESTUS

	Google Apps Login Premium
		Version: 3.4.2
		Author: Lever Technology LLC

	HappyFiles Pro
		Version: 0.7.0
		Author: Codeer

	JetBlog For Elementor
		Version: 2.2.13
		Author: Crocoblock

	JetElements For Elementor
		Version: 2.5.6
		Author: Crocoblock

	JetEngine
		Version: 2.7.8
		Author: Crocoblock

	JetEngine - Get attachment file link by ID
		Version: 1.1.1
		Author: Crocoblock

	JetPopup
		Version: 1.5.2
		Author: Crocoblock

	JetTabs For Elementor
		Version: 2.1.12
		Author: Crocoblock

	ManageWP - Worker
		Version: 4.9.8
		Author: GoDaddy

	Piotnet Addons For Elementor Pro
		Version: 6.3.63
		Author: Luong Huu Phuoc (Louis Hufer)

	Post Types Order
		Version: 1.9.5.6
		Author: Nsp Code

	Redirection
		Version: 5.1.1
		Author: John Godley

	WP-Optimize - Clean, Compress, Cache
		Version: 3.1.8
		Author: David Anderson, Ruhani Rabin, Team Updraft

	Yoast Duplicate Post
		Version: 4.1.2
		Author: Enrico Battocchi & Team Yoast

	Yoast SEO
		Version: 16.1.1
		Author: Team Yoast


== Must-Use Plugins ==
	Force Strong Passwords - WPE Edition
		Version: 1.6.4
		Author: Jason Cosper

	WP Engine Seamless Login Plugin
		Version: 1.5.5
		Author: WP Engine

	WP Engine Security Auditor
		Version: 1.0.10
		Author: wpengine

	WP Engine System
		Version: 4.1.0
		Author: WP Engine


== Elementor - Compatibility Tag ==
	
	Elementor - ESTUS: header_not_exists
	Elementor Pro: header_not_exists
	JetBlog For Elementor: header_not_exists
	JetElements For Elementor: header_not_exists
	JetTabs For Elementor: header_not_exists
	Piotnet Addons For Elementor Pro: header_not_exists

== Elementor Pro - Compatibility Tag ==
	


== Elements Usage ==
	
	archive : 2
		archive-posts : 1
		divider : 2
		heading : 3
		jet-listing-grid : 2
		theme-archive-title : 1
	footer : 1
		divider : 1
		form : 1
		heading : 11
		html : 1
		icon-list : 5
		social-icons : 1
		theme-site-logo : 1
	header : 2
		button : 2
		heading : 2
		image : 2
		nav-menu : 2
	page : 3
		alert : 1
		button : 8
		form : 2
		heading : 32
		icon : 1
		image : 3
		nav-menu : 1
		spacer : 8
		text-editor : 1
		theme-site-logo : 1
		video : 1
	section : 19
		button : 3
		divider : 5
		form : 1
		heading : 32
		icon : 1
		image : 8
		jet-listing-grid : 5
		jet-slider : 1
		spacer : 7
		toggle : 2
		video : 1
	single : 1
		heading : 2
		theme-post-content : 1
	wp-post : 0
		button : 6
		divider : 9
		form : 1
		heading : 57
		icon : 10
		image : 1
		jet-listing-dynamic-field : 2
		jet-listing-dynamic-image : 1
		jet-tabs : 1
		spacer : 29
		template : 2
		text-editor : 2
		toggle : 1
		video : 1
	wp-page : 21
		button : 1
		divider : 9
		heading : 189
		html : 3
		icon : 30
		image : 46
		jet-listing-grid : 4
		spacer : 48
		template : 24
		text-editor : 2
		video : 2
	single-post : 1
		heading : 4
		icon-box : 1
		icon-list : 1
		post-navigation : 1
		posts : 1
		theme-post-content : 1
		theme-post-excerpt : 1
		theme-post-title : 1
	not-supported : 0
	jet-popup : 1
		heading : 2
		jet-listing-dynamic-field : 1
		spacer : 1
	jet-listing-items : 0
		button : 1
		heading : 19
		icon : 4
		spacer : 2
		theme-post-excerpt : 1


== Log ==
	
Log: showing 20 of 352021-03-24 09:48:23 [info] Elementor Pro/Upgrades - _v_3_1_0_media_carousel Finished 
2021-03-24 09:48:23 [info] Elementor Pro/Upgrades - _v_3_1_0_reviews Start  
2021-03-24 09:48:24 [info] Elementor Pro/Upgrades - _v_3_1_0_reviews Finished 
2021-03-24 09:48:24 [info] Elementor Pro/Upgrades - _v_3_1_0_testimonial_carousel Start  
2021-03-24 09:48:24 [info] Elementor Pro/Upgrades - _v_3_1_0_testimonial_carousel Finished 
2021-03-24 09:48:24 [info] Elementor Pro/Upgrades - _v_3_1_0_slides Start  
2021-03-24 09:48:24 [info] Elementor Pro/Upgrades - _v_3_1_0_slides Finished 
2021-03-24 09:48:24 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.2.0',
  'to' => '3.2.1',
)]
2021-04-23 13:40:47 [info] elementor::elementor_updater Started 
2021-04-23 13:40:47 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Start  
2021-04-23 13:40:47 [notice] General Settings already exist. nothing to do. 
2021-04-23 13:40:47 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Finished 
2021-04-23 13:40:47 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Start  
2021-04-23 13:40:47 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Finished 
2021-04-23 13:40:47 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Start  
2021-04-23 13:40:47 [notice] Custom colors already exist. nothing to do. 
2021-04-23 13:40:47 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Finished 
2021-04-23 13:40:47 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Start  
2021-04-23 13:40:47 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Finished 
2021-04-23 13:40:47 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.4',
  'to' => '3.2.1',
)]

PHP: showing 8 of 8PHP: 2021-03-17 11:41:01 [notice X 48][/nas/content/live/surna2021/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-17 11:48:59 [error X 1][/nas/content/live/surna2021/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::281] Uncaught Error: Call to a member function update_meta() on bool in /nas/content/live/surna2021/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:281
Stack trace:
#0 /nas/content/live/surna2021/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(162): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /nas/content/live/surna2021/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /nas/content/live/surna2021/wp-includes/class-wp-hook.php(292): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/373 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-24 09:55:45 [notice X 449][/nas/content/live/surna2021/wp-content/plugins/elementor/includes/base/controls-stack.php::1405] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-24 10:27:53 [notice X 8][/nas/content/live/surna2021/wp-content/plugins/elementor/includes/managers/image.php::86] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-24 12:24:32 [error X 1][/nas/content/live/surna2021/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::281] Uncaught Error: Call to a member function update_meta() on null in /nas/content/live/surna2021/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:281
Stack trace:
#0 /nas/content/live/surna2021/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(162): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(331, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /nas/content/live/surna2021/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /nas/content/live/surna2021/wp-includes/class-wp-hook.php(292): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /nas/content/live/surna2021/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters('', Array)
#5 /nas/content/ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-24 12:33:31 [notice X 17][/nas/content/live/surna2021/wp-content/plugins/elementor-pro/modules/posts/skins/skin-content-base.php::248] Trying to get property 'ID' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-26 10:06:47 [notice X 96][/nas/content/live/surna2021/wp-content/plugins/elementor/includes/managers/image.php::80] Undefined offset: 2 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-01 12:25:21 [notice X 3][/nas/content/live/surna2021/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php::33] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]


				
![Screen Shot 2021-04-23 at 2 19 24 PM](https://user-images.githubusercontent.com/1638530/115925770-ed3c1f00-a43e-11eb-922c-9122538a810b.png)
![Screen Shot 2021-04-23 at 2 19 49 PM](https://user-images.githubusercontent.com/1638530/115925805-fcbb6800-a43e-11eb-97ff-8878779a8290.png)


```
</details>

**Comment by fleks** [comment]
Sorry, I can't reproduce it. Did you really deactivate all plugins except Elementor? In the secound screenshot at the end of your System Info, there is the Position option ...

**Comment by shilo-ey** [comment]
@DIntriglia Please make sure you are uploading the initial image in the Desktop device and not other.

This is an open issue with the controls conditions mechanism and for meanwhile make sure the initial device you are adding image to is Desktop.

Thank you @fleks as well!
