### ISSUE TITLE
🐞 BUG 3.2.2 - elementorFrontend.config.responsive.activeBreakpoints is undefined

### ISSUE THREAD

**Issue by Cicciokr** [elementor/elementor#14721]
## Prerequisites
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description
When we open Elementor editing page, it broke with an error of undefined, and we have seen that this variable is undefined and broke initStylesheet.
elementorFrontend.config.responsive.activeBreakpoints is undefined

You can see the post on Facebook: https://www.facebook.com/groups/Elementors/permalink/3693479050777854/?comment_id=3693591520766607&notif_id=1619450878428676&notif_t=group_comment&ref=notif

## Steps to reproduce
Open a page and press "edit with elementor"

## Isolating the problem
- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## System Info
Operating System: | Linux |  
Software: | nginx/1.18.0 |  
MySQL version: | MariaDB Server v10.3.28 |  
PHP Version: | 7.4.16 |  
PHP Max Input Vars: | 1000 |  
PHP Max Post Size: | 32M |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected

## WordPress Environment  
Version: | 5.7.1 |  
WP Multisite: | No |  
Max Upload Size: | 32 MB |  
Memory limit: | 256M |   
Debug Mode: | Inactive

## Active Plugins 
Advanced noCaptcha & invisible Captcha - 6.1.5 | By Shamim Hasan |  
Block Specific Plugin Updates - 3.1 | By Dinesh Karki |  
bunny.net - 1.0.8 | By bunny.net |  
Cookie and Consent Solution for the GDPR & ePrivacy - 2.5.0 | By iubenda |  
Customizer Export/Import - 0.9.2 | By The Beaver Builder Team |  
Custom Post Type UI - 1.9.1 | By WebDevStudios |  
Duplicate Page - 4.4 | By mndpsingh287 |  
Elementor - 3.2.2 | By Elementor.com |  
Element Pack - 5.7.7 | By BdThemes |  
Google Tag Manager for Wordpress - 1.12.3 | By Thomas Geiger |  
Imagify - 1.9.14 | By WP Media |  
jQuery Updater - 3.6.0.1 | By Ramoonus |  
Kirki Customizer Framework - 3.1.6 | By David Vongries |  
Loco Translate - 2.5.2 | By Tim Whitlock |  
Maintenance - 4.02 | By WebFactory Ltd |  
Martfury Addons - 2.3.0 | By DrFuri |  
Meta Box - 5.3.10 | By MetaBox.io |  
Newsletter - 7.1.3 | By Stefano Lissa & The Newsletter Team |  
Newsletter - Addons Manager - 1.1.4 | By The Newsletter Team |  
Newsletter - Automated Newsletters - 4.5.0 | By The Newsletter Team |  
Newsletter - Bounce - 1.1.5 | By The Newsletter Team |  
Newsletter - Extended Composer Blocks - 1.3.1 | By The Newsletter Team |  
Newsletter - Geo Resolver - 1.1.0 | By The Newsletter Team |  
Newsletter - Google Analytics - 1.1.2 | By The Newsletter Team |  
Newsletter - Import - 1.2.0 | By The Newsletter Team |  
Newsletter - Leads - 1.2.3 | By The Newsletter Team |  
Newsletter - Reports and Retargeting - 4.3.8 | By The Newsletter Team |  
Newsletter - WooCommerce - 1.6.5 | By The Newsletter Team |  
Newsletter - WP Users Integration - 1.2.6 | By The Newsletter Team |  
Nexi XPay - 5.1.0 | By Nexi SpA |  
Perfmatters - 1.6.9 | By forgemedia |  
Premmerce Permalink Manager for WooCommerce - 2.3.1 | By premmerce |  
User Role Editor - 4.59 | By Vladimir Garagulya |  
WooCommerce - 5.2.2 | By Automattic |  
WooCommerce - Show only lowest prices in variable products - 0.9.22 | By Fernando Tellado |  
WooCommerce All Products For Subscriptions - 3.1.13 | By SomewhereWarm |  
WooCommerce Conversion Tracking - 1.9.5 | By woopt |  
WooCommerce Deals - 1.0.9 | By Drfuri |  
WooCommerce Stripe Gateway - 5.1.0 | By WooCommerce |  
WooCommerce Subscriptions - 3.0.4 | By WooCommerce |  
WooCommerce Variation Swatches Pro - 1.0.7 | By Drfuri |  
Woo Image SEO - 1.2.2 | By Danail Emandiev |  
WP Mail SMTP - 2.7.0 | By WPForms |  
WP Redis - 1.1.2 | By Pantheon, Josh Koenig, Matthew Boynes, Daniel Bachhuber, Alley Interactive |  
WP Rocket - 3.8.8 | By WP Media |  
YITH Advanced Refund System for WooCommerce Premium - 1.2.7 | By YITH |  
YITH Booking and Appointment for WooCommerce Premium - 2.1.24 | By YITH |  
YITH Google Product Feed for WooCommerce Premium - 1.1.21 | By YITH |  
YITH WooCommerce Cart Messages Premium - 1.7.8 | By YITH |  
YITH WooCommerce Order Tracking Premium - 1.6.14 | By YITH |  
YITH WooCommerce Points and Rewards Premium - 2.0.8 | By YITH |  
YITH WooCommerce Social Login Premium - 1.6.9 | By YITH |  
Yoast SEO - 16.1.1 | By Team Yoast |  
Yoast SEO: WooCommerce - 13.7 | By Team Yoast |  
Yoast SEO Premium - 16.1 | By Team Yoast |  
Yoast Test Helper - 1.13 | By Team Yoast

## Temporary resolution
i have changed the **editor.js** file with this function on the code line 26290:

` initStylesheet: function initStylesheet() {
    var _this = this;
    var activeBreakpoints = elementorFrontend.config.responsive.activeBreakpoints;
    var breakpoints = (typeof activeBreakpoints === 'undefined') ? activeBreakpoints = 0 : activeBreakpoints;`

**Comment by m83frey** [comment]
same issue here.

![178042869_10159037154369337_2691047556176720417_n](https://user-images.githubusercontent.com/83241123/116130278-55069a00-a6cb-11eb-8e51-f561232c3db7.jpg)
![178053167_10159037151784337_7600491006054194796_n](https://user-images.githubusercontent.com/83241123/116130284-5637c700-a6cb-11eb-9735-b3cede828a6a.jpg)
![178097367_10159037151469337_1513908028202472292_n](https://user-images.githubusercontent.com/83241123/116130285-5637c700-a6cb-11eb-8f90-588556493a3c.jpg)

**Comment by udidol** [comment]
Hi @Cicciokr,
Do you have any plugins other than Elementor installed? please share your system info.

**Comment by Cicciokr** [comment]
I have updated the post.

**Comment by DorShahar** [comment]
Hi @Cicciokr 
Please deactivate your plugins one by one in order to understand if one of them is causing the error. 
Our bet is Element Pack, (so you can start with that)  since it extends Elementor and might write a control not according to our best practice. 

Thanks

**Comment by Cicciokr** [comment]
In my case i have found the this plugin broke Elementor:

WooCommerce Subscriptions - 3.0.4 | By WooCommerce

**Comment by m83frey** [comment]
> Hi @Cicciokr
> Please deactivate your plugins one by one in order to understand if one of them is causing the error.
> Our bet is Element Pack, (so you can start with that) since it extends Elementor and might write a control not according to our best practice.
> 
> Thanks

Hi @DorShahar @udidol - please find my system info below.
I already tried to troubleshoot a potential plugin conflict by using the "health and troubleshoot" plugin. Unfortunately without success. May you have an idea?!

The error codes from the console are also in the pictures I uploaded above.


== Server Environment ==
	Operating System: Linux
	Software: nginx/1.18.0
	MySQL version: Debian 10 v10.3.27
	PHP Version: 7.4.16
	PHP Max Input Vars: 1000
	PHP Max Post Size: 32M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.7.1
	Site URL: https://naehdeinenstil.com
	Home URL: https://naehdeinenstil.com
	WP Multisite: No
	Max Upload Size: 32 MB
	Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: de-DE
	Timezone: Europe/Berlin
	Admin Email: elke@ellepuls.com
	Debug Mode: Inactive

== Theme ==
	Name: BuddyBoss Child
	Version: 1.0.0
	Author: BuddyBoss.com
	Child Theme: Yes
	Parent Theme Name: BuddyBoss Theme
	Parent Theme Version: 1.6.5
	Parent Theme Author: BuddyBoss

== User ==
	Role: administrator
	WP Profile lang: de_DE_formal
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36

== Active Plugins ==
	Affiliate Royale Merchant Edition
		Version: 1.4.18
		Author: Caseproof, LLC

	All-in-One WP Migration
		Version: 7.40
		Author: ServMask

	All-in-One WP Migration Unlimited Extension
		Version: 2.39
		Author: ServMask

	BBQ Pro
		Version: 3.0
		Author: Jeff Starr

	Borlabs Cookie - Cookie Opt-in
		Version: 2.2.24
		Author: Benjamin A. Bornschein, Borlabs

	BuddyBoss Platform
		Version: 1.5.8.1
		Author: BuddyBoss

	BuddyBoss Platform Pro
		Version: 1.1.1
		Author: BuddyBoss

	Code Snippets
		Version: 2.14.1
		Author: Code Snippets Pro

	Easy WP SMTP
		Version: 1.4.6
		Author: wpecommerce, alexanderfoxc

	Elementor
		Version: 3.2.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.2.1
		Author: Elementor.com

	GamiPress
		Version: 2.0.0
		Author: GamiPress

	GamiPress - BuddyBoss integration
		Version: 1.1.6
		Author: GamiPress

	GamiPress - BuddyPress integration
		Version: 1.4.6
		Author: GamiPress

	If Menu - Visibility control for menu items
		Version: 0.16.2
		Author: Layered

	LearnDash LMS
		Version: 3.4.0.7
		Author: LearnDash

	LearnDash LMS - Course Grid
		Version: 1.7.0
		Author: LearnDash

	LearnDash LMS - MemberPress Integration
		Version: 2.2.0
		Author: LearnDash

	LearnDash LMS - Stripe Integration
		Version: 1.8.0
		Author: LearnDash

	Loco Translate
		Version: 2.5.2
		Author: Tim Whitlock

	MemberPress + BuddyPress Integration
		Version: 1.1.10
		Author: Caseproof, LLC

	MemberPress ConvertKit
		Version: 1.2.2
		Author: Caseproof, LLC

	MemberPress Downloads
		Version: 1.1.3
		Author: Caseproof, LLC

	MemberPress Importer
		Version: 1.6.7
		Author: Caseproof, LLC

	MemberPress PDF Invoice
		Version: 1.1.6
		Author: Caseproof, LLC

	MemberPress Plus 10 (Legacy)
		Version: 1.9.17
		Author: Caseproof, LLC

	Optimus
		Version: 1.6.0
		Author: KeyCDN

	Tag Pages
		Version: 1.0.2
		Author: Bjorn Wijers <burobjorn at burobjorn dot nl>

	The Events Calendar
		Version: 5.5.0.1
		Author: The Events Calendar

	W3 Total Cache
		Version: 2.1.2
		Author: BoldGrid

	wpDataTables
		Version: 3.4.3
		Author: TMS-Plugins


== Must-Use Plugins ==
	Health Check Troubleshooting Mode
		Version: 1.7.2
		Author: 

	LearnDash LMS Multisite
		Version: 1.0.0
		Author: LearnDash


== Elementor - Compatibility Tag ==
	
	Elementor Pro: incompatible

== Elementor Pro - Compatibility Tag ==
	


== Elements Usage ==
	
	page : 3
		bbp-activity : 2
		bbp-dashboard-prior : 2
		bbp-forums-activity : 2
		bbp-members : 2
		bbp-profile-completion : 2
		button : 1
		call-to-action : 6
		global : 2
		heading : 1
		icon-box : 13
		image : 1
		ld-activity : 2
		spacer : 5
		text-editor : 1
	section : 8
		bbp-activity : 1
		bbp-dashboard-grid : 1
		bbp-dashboard-prior : 1
		bbp-forums : 1
		bbp-forums-activity : 1
		bbp-members : 1
		bbp-profile-completion : 1
		button : 5
		call-to-action : 1
		header-bar : 1
		heading : 8
		icon-box : 3
		image : 1
		ld-activity : 1
		nav-menu : 1
		text-editor : 4
	widget : 0
		heading : 101
	wp-page : 19
		accordion : 3
		bbp-activity : 1
		bbp-dashboard-prior : 1
		bbp-forums-activity : 1
		bbp-members : 1
		bbp-profile-completion : 1
		button : 14
		call-to-action : 10
		global : 1
		heading : 41
		icon-box : 10
		image : 11
		ld-activity : 1
		posts : 4
		price-table : 6
		spacer : 2
		text-editor : 21
		video : 17


== Log ==
	
PHP: showing 3 of 3PHP: 2020-10-09 16:32:19 [notice X 14][/var/www/vhosts/naehdeinenstil.com/httpdocs/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-12-30 11:25:13 [warning X 1][/var/www/vhosts/naehdeinenstil.com/httpdocs/wp-content/plugins/elementor/core/files/manager.php::121] unlink(/var/www/vhosts/naehdeinenstil.com/httpdocs/wp-content/uploads/elementor/css/post-83237.css): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-17 13:16:15 [error X 2][/var/www/vhosts/naehdeinenstil.com/httpdocs/wp-content/plugins/elementor/includes/base/controls-stack.php::2038] Uncaught TypeError: Argument 1 passed to Elementor\Controls_Stack::sanitize_settings() must be of the type array, null given, called in /var/www/vhosts/naehdeinenstil.com/httpdocs/wp-content/plugins/elementor/includes/base/controls-stack.php on line 987 and defined in /var/www/vhosts/naehdeinenstil.com/httpdocs/wp-content/plugins/elementor/includes/base/controls-stack.php:2038
Stack trace:
#0 /var/www/vhosts/naehdeinenstil.com/httpdocs/wp-content/plugins/elementor/includes/base/controls-stack.php(987): Elementor\Controls_Stack-&gt;sanitize_settings()
#1 /var/www/vhosts/naehdeinenstil.com/httpdocs/wp-content/plugins/elementor/includes/base/controls-stack.php(1787): Elementor\Controls_Stack-&gt;get_data()
#2 /var/www/vhosts/naehdeinenstil.com/httpdocs/wp-content/plugins/elementor/core/base/base-object.php(142): Elementor\Controls_Stack-&gt;get_init_settings()
#3 /var/www/vhosts/naehdeinenstil.com/httpdocs/wp-content/plugins/elementor/core/base/base-object.php(40): Elementor\Core\Base\Base_Object-&gt;ensure_settings()
#4 /v [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 20 of 362021-02-22 12:17:52 [info] Elementor Pro/Upgrades - _v_3_1_0_testimonial_carousel Start  
2021-02-22 12:17:52 [info] Elementor Pro/Upgrades - _v_3_1_0_testimonial_carousel Finished 
2021-02-22 12:17:52 [info] Elementor Pro/Upgrades - _v_3_1_0_slides Start  
2021-02-22 12:17:52 [info] Elementor Pro/Upgrades - _v_3_1_0_slides Finished 
2021-02-22 12:17:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.10',
  'to' => '3.1.0',
)]
2021-02-22 12:17:52 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.10',
  'to' => '3.1.0',
)]
2021-02-25 09:00:02 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.1.0',
  'to' => '3.1.1',
)]
2021-03-03 11:17:47 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.1',
  'to' => '3.1.2',
)]
2021-03-03 11:17:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.1',
  'to' => '3.1.2',
)]
2021-03-05 07:42:28 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.2',
  'to' => '3.1.3',
)]
2021-03-13 08:04:57 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.3',
  'to' => '3.1.4',
)]
2021-03-13 08:04:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.3',
  'to' => '3.1.4',
)]
2021-03-17 09:17:19 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.1.1',
  'to' => '3.2.0',
)]
2021-03-26 07:27:38 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.2.0',
  'to' => '3.2.1',
)]
2021-04-23 21:34:06 [info] elementor::elementor_updater Started 
2021-04-23 21:34:07 [info] Elementor/Upgrades - _v_3_2_0_migrate_breakpoints_to_new_system Start  
2021-04-23 21:34:07 [info] Elementor/Upgrades - _v_3_2_0_migrate_breakpoints_to_new_system Finished 
2021-04-23 21:34:07 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.4',
  'to' => '3.2.1',
)]
2021-04-23 21:34:07 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.4',
  'to' => '3.2.1',
)]
2021-04-26 15:50:17 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.1',
  'to' => '3.2.2',
)]

JS: showing 4 of 4JS: 2020-12-30 14:17:31 [error X 2][https://naehdeinenstil.com/wp-content/plugins/elementor/assets/js/frontend.min.js:2:63559] Cannot read property \&#039;tools\&#039; of undefined 
JS: 2020-12-30 20:59:58 [error X 17][https://naehdeinenstil.com/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.0.9:2:70002] Cannot set property \&#039;templatesAreSaved\&#039; of undefined 
JS: 2021-02-09 07:07:17 [error X 1][https://naehdeinenstil.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \&quot;view1220\&quot;) has already been destroyed and cannot be used. 
JS: 2021-02-09 07:42:43 [error X 1][https://naehdeinenstil.com/wp-content/themes/buddyboss-theme/inc/plugins/elementor/assets/editor/templates/js/editor.js?ver=1:637:45] Cannot read property \&#039;currentView\&#039; of undefined

**Comment by udidol** [comment]
@m83frey please disable all other plugins (except for Elementor and Elementor Pro) and check if the issue persists. If it does - there is another plugin that is interfering with Elementor's load sequence.

**Comment by DorShahar** [comment]
Closing for lack of activity,
Feel free to reopen if the issue persists.
