### ISSUE TITLE
Price Table Features Icon does not display 

### ISSUE THREAD

**Issue by shloobrown** [elementor/elementor#14899]
**### Prerequisites**
- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest stable version of Elementor.

### **Description**
The pricing table feature icons do not display and the html is not present on inspection.

1. Add feature icons to the pricing table (tested multiple)
2. Click off the table and the icons disappear
3. Click 'Update' and the icons are not visible live or incognito

<img width="1300" alt="Screenshot 2021-05-11 at 10 17 11" src="https://user-images.githubusercontent.com/42063765/117782589-0f58de00-b242-11eb-8226-d4e6d1f19849.png">

I pulled a debug.log and get this notice - didn't have this notice in the previous update:

[06-May-2021 13:43:53 UTC] PHP Notice:  Trying to get property 'post_type' of non-object in /home/dmatac/public_html/wp-content/plugins/wordpress-seo/src/integrations/third-party/elementor.php on line 154

1. Plugins > I deactivated all plug ins except for elementor and elementor pro and the issue persists.
2. Theme > Switched to default 'Twenty Sixteen' them and the issue persists
3.  Inspected my website and the html isn't present
4. Cleared cache on website

### **## Steps to reproduce**

1. Add new section
2. Select pricing table from Blocks
<img width="1303" alt="Screenshot 2021-05-11 at 10 23 26" src="https://user-images.githubusercontent.com/42063765/117783542-eedd5380-b242-11eb-8d88-2ab98e96dc2d.png">
3. Add a feature icons
4. Select update
5. Feature icons are not visible

### **## Isolating the problem**

- [ x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ x] This bug happens with a default WordPress theme active.
- [ x] I can reproduce this bug consistently using the steps above.

### **## Environment**
					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MySQL Community Server - (GPL) v5.7.33
	PHP Version: 7.2.34
	PHP Max Input Vars: 1000
	PHP Max Post Size: 32M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.7.1
	Site URL: https://dmat.ac
	Home URL: https://dmat.ac
	WP Multisite: No
	Max Upload Size: 32 MB
	Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Active

== Theme ==
	Name: Neve
	Version: 2.11.2
	Author: ThemeIsle
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36

== Active Plugins ==
	ActiveCampaign
		Version: 8.1.7
		Author: ActiveCampaign

	Advanced Custom Fields
		Version: 5.9.5
		Author: Elliot Condon

	Duplicate Page
		Version: 4.4
		Author: mndpsingh287

	Duplicator
		Version: 1.4.0
		Author: Snap Creek

	Elementor
		Version: 3.2.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.2.2
		Author: Elementor.com

	Google Analytics for WordPress by MonsterInsights
		Version: 7.17.0
		Author: MonsterInsights

	Google Tag Manager for Wordpress
		Version: 1.12.3
		Author: Thomas Geiger

	Head, Footer and Post Injections
		Version: 3.2.2
		Author: Stefano Lissa

	Hello Dolly
		Version: 1.7.2
		Author: Matt Mullenweg

	Hotjar
		Version: 1.0.9
		Author: Hotjar

	Insert Headers and Footers
		Version: 1.6.0
		Author: WPBeginner

	Orbit Fox Companion
		Version: 2.10.4
		Author: Themeisle

	Simple Custom CSS and JS
		Version: 3.36
		Author: SilkyPress.com

	W3 Total Cache
		Version: 2.1.2
		Author: BoldGrid

	Wordfence Security
		Version: 7.5.2
		Author: Wordfence

	WPForms Lite
		Version: 1.6.6
		Author: WPForms

== Elementor - Compatibility Tag ==
	
	Elementor Pro: compatible

== Elementor Pro - Compatibility Tag ==
	

== Elements Usage ==
	
	footer : 2
		form : 1
		heading : 2
		icon-list : 3
		text-editor : 1
	header : 2
		icon-list : 1
		image : 2
		nav-menu : 1
	page : 11
		button : 1
		call-to-action : 11
		divider : 2
		heading : 15
		icon : 5
		icon-list : 2
		posts : 1
		price-table : 1
		spacer : 2
		testimonial : 1
		text-editor : 11
		toggle : 4
	popup : 9
		button : 1
		form : 4
		heading : 7
		image : 1
		nav-menu : 1
		social-icons : 2
		spacer : 3
		text-editor : 3
	wp-page : 19
		button : 22
		call-to-action : 7
		counter : 2
		divider : 40
		form : 5
		heading : 180
		icon : 9
		icon-box : 7
		icon-list : 1
		image : 86
		image-box : 8
		image-carousel : 4
		image-gallery : 1
		media-carousel : 1
		menu-anchor : 5
		post-info : 2
		posts : 3
		price-table : 5
		reviews : 3
		share-buttons : 3
		shortcode : 4
		sitemap : 1
		social-icons : 11
		spacer : 15
		testimonial-carousel : 6
		text-editor : 143
		toggle : 32
		video : 1

== Log ==
	
JS: showing 18 of 18JS: 2021-02-26 09:09:27 [error X 1][https://dmat.ac/wp-includes/js/jquery/jquery.min.js?ver=3.5.1:2:40905] Cannot create property \'guid\' on string \'c279widgetsticky\' 
JS: 2021-02-26 09:09:27 [error X 1][https://dmat.ac/wp-includes/js/jquery/jquery.min.js?ver=3.5.1:2:40905] Cannot create property \'guid\' on string \'c282widgetsticky\' 
JS: 2021-02-26 09:09:27 [error X 1][https://dmat.ac/wp-includes/js/jquery/jquery.min.js?ver=3.5.1:2:40905] Cannot create property \'guid\' on string \'c285widgetsticky\' 
JS: 2021-02-26 09:09:27 [error X 1][https://dmat.ac/wp-includes/js/jquery/jquery.min.js?ver=3.5.1:2:40905] Cannot create property \'guid\' on string \'c288widgetsticky\' 
JS: 2021-02-26 09:09:27 [error X 1][https://dmat.ac/wp-includes/js/jquery/jquery.min.js?ver=3.5.1:2:40905] Cannot create property \'guid\' on string \'c306widgetsticky\' 
JS: 2021-02-26 09:09:27 [error X 1][https://dmat.ac/wp-includes/js/jquery/jquery.min.js?ver=3.5.1:2:40905] Cannot create property \'guid\' on string \'c318widgetsticky\' 
JS: 2021-02-26 09:09:27 [error X 1][https://dmat.ac/wp-includes/js/jquery/jquery.min.js?ver=3.5.1:2:40905] Cannot create property \'guid\' on string \'c321widgetsticky\' 
JS: 2021-02-26 09:09:27 [error X 1][https://dmat.ac/wp-includes/js/jquery/jquery.min.js?ver=3.5.1:2:40905] Cannot create property \'guid\' on string \'c324widgetsticky\' 
JS: 2021-02-26 09:09:27 [error X 1][https://dmat.ac/wp-includes/js/jquery/jquery.min.js?ver=3.5.1:2:40905] Cannot create property \'guid\' on string \'c327widgetsticky\' 
JS: 2021-02-26 09:09:27 [error X 1][https://dmat.ac/wp-includes/js/jquery/jquery.min.js?ver=3.5.1:2:40905] Cannot create property \'guid\' on string \'c330widgetsticky\' 
JS: 2021-02-26 09:09:27 [error X 1][https://dmat.ac/wp-includes/js/jquery/jquery.min.js?ver=3.5.1:2:40905] Cannot create property \'guid\' on string \'c336widgetsticky\' 
JS: 2021-02-26 09:09:27 [error X 1][https://dmat.ac/wp-includes/js/jquery/jquery.min.js?ver=3.5.1:2:40905] Cannot create property \'guid\' on string \'c339widgetsticky\' 
JS: 2021-02-26 09:09:27 [error X 1][https://dmat.ac/wp-includes/js/jquery/jquery.min.js?ver=3.5.1:2:40905] Cannot create property \'guid\' on string \'c342widgetsticky\' 
JS: 2021-02-26 09:09:27 [error X 1][https://dmat.ac/wp-includes/js/jquery/jquery.min.js?ver=3.5.1:2:40905] Cannot create property \'guid\' on string \'c351widgetsticky\' 
JS: 2021-02-26 09:09:27 [error X 1][https://dmat.ac/wp-includes/js/jquery/jquery.min.js?ver=3.5.1:2:40905] Cannot create property \'guid\' on string \'c368widgetsticky\' 
JS: 2021-02-26 09:09:27 [error X 1][https://dmat.ac/wp-includes/js/jquery/jquery.min.js?ver=3.5.1:2:40905] Cannot create property \'guid\' on string \'c371widgetsticky\' 
JS: 2021-02-26 09:13:02 [error X 2][https://dmat.ac/wp-includes/js/jquery/jquery.min.js?ver=3.5.1:2:40905] Cannot create property \'guid\' on string \'c7369sectionsticky\' 
JS: 2021-02-26 09:14:49 [error X 6][https://dmat.ac/wp-includes/js/jquery/jquery.min.js?ver=3.5.1:2:40905] Cannot create property \'guid\' on string \'c8212widgetsticky\' 

PHP: showing 13 of 13PHP: 2021-02-26 12:35:49 [notice X 12][/home/dmatac/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-08 12:45:56 [notice X 45][/home/dmatac/public_html/wp-content/plugins/elementor-pro/modules/forms/classes/activecampaign-handler.php::133] Undefined index: textarea [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-24 10:14:35 [error X 1][/home/dmatac/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php::1090] Uncaught TypeError: Argument 2 passed to Elementor\TemplateLibrary\Source_Local::on_save_post() must be an instance of WP_Post, null given, called in /home/dmatac/public_html/wp-includes/class-wp-hook.php on line 289 and defined in /home/dmatac/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php:1090
Stack trace:
#0 /home/dmatac/public_html/wp-includes/class-wp-hook.php(289): Elementor\TemplateLibrary\Source_Local->on_save_post(5146, NULL)
#1 /home/dmatac/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#2 /home/dmatac/public_html/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#3 /home/dmatac/public_html/wp-includes/post.php(4309): do_action('save_post', 5146, NULL, true)
#4 /home/dmatac/public_html/wp-includes/post.php(4411): wp_insert_post(Array, false, true)
#5 /home/dmatac/public_html/wp-content/plugins/elementor/includes/db.php(235): wp_update_post(Array)
#6 /home/dmatac/public_html/wp-content/plugins/elementor/core/base/document [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-24 13:24:58 [error X 1][/home/dmatac/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php::1090] Uncaught TypeError: Argument 2 passed to Elementor\TemplateLibrary\Source_Local::on_save_post() must be an instance of WP_Post, null given, called in /home/dmatac/public_html/wp-includes/class-wp-hook.php on line 289 and defined in /home/dmatac/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php:1090
Stack trace:
#0 /home/dmatac/public_html/wp-includes/class-wp-hook.php(289): Elementor\TemplateLibrary\Source_Local->on_save_post(5206, NULL)
#1 /home/dmatac/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#2 /home/dmatac/public_html/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#3 /home/dmatac/public_html/wp-includes/post.php(4309): do_action('save_post', 5206, NULL, true)
#4 /home/dmatac/public_html/wp-includes/post.php(4411): wp_insert_post(Array, false, true)
#5 /home/dmatac/public_html/wp-content/plugins/elementor/includes/db.php(235): wp_update_post(Array)
#6 /home/dmatac/public_html/wp-content/plugins/elementor/core/base/document [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-07 12:02:52 [error X 1][/home/dmatac/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php::1090] Uncaught TypeError: Argument 2 passed to Elementor\TemplateLibrary\Source_Local::on_save_post() must be an instance of WP_Post, instance of stdClass given, called in /home/dmatac/public_html/wp-includes/class-wp-hook.php on line 294 and defined in /home/dmatac/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php:1090
Stack trace:
#0 /home/dmatac/public_html/wp-includes/class-wp-hook.php(294): Elementor\TemplateLibrary\Source_Local->on_save_post(5450, Object(stdClass))
#1 /home/dmatac/public_html/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters(NULL, Array)
#2 /home/dmatac/public_html/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#3 /home/dmatac/public_html/wp-includes/post.php(4384): do_action('save_post', 5450, Object(stdClass), true)
#4 /home/dmatac/public_html/wp-includes/post.php(4486): wp_insert_post(Array, false, true)
#5 /home/dmatac/public_html/wp-content/plugins/elementor/includes/db.php(235): wp_update_post(Array)
#6 /home/dmatac/public_html/wp-cont [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-08 09:25:24 [notice X 3][/home/dmatac/public_html/wp-content/plugins/elementor-pro/modules/query-control/classes/elementor-post-query.php::226] Undefined property: WP_Error::$taxonomy [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-08 10:31:22 [error X 1][/home/dmatac/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php::1090] Uncaught TypeError: Argument 2 passed to Elementor\TemplateLibrary\Source_Local::on_save_post() must be an instance of WP_Post, instance of stdClass given, called in /home/dmatac/public_html/wp-includes/class-wp-hook.php on line 294 and defined in /home/dmatac/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php:1090
Stack trace:
#0 /home/dmatac/public_html/wp-includes/class-wp-hook.php(294): Elementor\TemplateLibrary\Source_Local->on_save_post(5533, Object(stdClass))
#1 /home/dmatac/public_html/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters(NULL, Array)
#2 /home/dmatac/public_html/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#3 /home/dmatac/public_html/wp-includes/post.php(4384): do_action('save_post', 5533, Object(stdClass), true)
#4 /home/dmatac/public_html/wp-includes/post.php(4486): wp_insert_post(Array, false, true)
#5 /home/dmatac/public_html/wp-content/plugins/elementor/includes/db.php(235): wp_update_post(Array)
#6 /home/dmatac/public_html/wp-cont [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-08 11:05:16 [error X 1][/home/dmatac/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php::1090] Uncaught TypeError: Argument 2 passed to Elementor\TemplateLibrary\Source_Local::on_save_post() must be an instance of WP_Post, null given, called in /home/dmatac/public_html/wp-includes/class-wp-hook.php on line 294 and defined in /home/dmatac/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php:1090
Stack trace:
#0 /home/dmatac/public_html/wp-includes/class-wp-hook.php(294): Elementor\TemplateLibrary\Source_Local->on_save_post(5573, NULL)
#1 /home/dmatac/public_html/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters(NULL, Array)
#2 /home/dmatac/public_html/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#3 /home/dmatac/public_html/wp-includes/post.php(4384): do_action('save_post', 5573, NULL, true)
#4 /home/dmatac/public_html/wp-includes/post.php(4486): wp_insert_post(Array, false, true)
#5 /home/dmatac/public_html/wp-content/plugins/elementor/includes/db.php(235): wp_update_post(Array)
#6 /home/dmatac/public_html/wp-content/plugins/elementor/core/base/document [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-13 10:15:01 [error X 1][/home/dmatac/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php::1090] Uncaught TypeError: Argument 2 passed to Elementor\TemplateLibrary\Source_Local::on_save_post() must be an instance of WP_Post, null given, called in /home/dmatac/public_html/wp-includes/class-wp-hook.php on line 294 and defined in /home/dmatac/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php:1090
Stack trace:
#0 /home/dmatac/public_html/wp-includes/class-wp-hook.php(294): Elementor\TemplateLibrary\Source_Local->on_save_post(5718, NULL)
#1 /home/dmatac/public_html/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters(NULL, Array)
#2 /home/dmatac/public_html/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#3 /home/dmatac/public_html/wp-includes/post.php(4384): do_action('save_post', 5718, NULL, true)
#4 /home/dmatac/public_html/wp-includes/post.php(4486): wp_insert_post(Array, false, true)
#5 /home/dmatac/public_html/wp-content/plugins/elementor/includes/db.php(235): wp_update_post(Array)
#6 /home/dmatac/public_html/wp-content/plugins/elementor/core/base/document [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-26 12:33:54 [error X 1][/home/dmatac/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php::1089] Uncaught TypeError: Argument 2 passed to Elementor\TemplateLibrary\Source_Local::on_save_post() must be an instance of WP_Post, instance of stdClass given, called in /home/dmatac/public_html/wp-includes/class-wp-hook.php on line 294 and defined in /home/dmatac/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php:1089
Stack trace:
#0 /home/dmatac/public_html/wp-includes/class-wp-hook.php(294): Elementor\TemplateLibrary\Source_Local->on_save_post(6370, Object(stdClass))
#1 /home/dmatac/public_html/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters(NULL, Array)
#2 /home/dmatac/public_html/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#3 /home/dmatac/public_html/wp-includes/post.php(4384): do_action('save_post', 6370, Object(stdClass), true)
#4 /home/dmatac/public_html/wp-includes/post.php(4486): wp_insert_post(Array, false, true)
#5 /home/dmatac/public_html/wp-content/plugins/elementor/includes/db.php(235): wp_update_post(Array)
#6 /home/dmatac/public_html/wp-cont [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-28 12:21:09 [warning X 1][/home/dmatac/public_html/wp-content/plugins/elementor-pro/modules/forms/actions/activecampaign.php::225] Invalid argument supplied for foreach() [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-30 12:49:22 [notice X 2][/home/dmatac/public_html/wp-content/plugins/elementor-pro/modules/query-control/module.php::738] Trying to get property 'name' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-05-05 13:02:49 [error X 1][/home/dmatac/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::281] Uncaught Error: Call to a member function update_meta() on boolean in /home/dmatac/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:281
Stack trace:
#0 /home/dmatac/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(162): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/dmatac/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/dmatac/public_html/wp-includes/class-wp-hook.php(292): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/dmatac/public_html/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters('', Array)
#5 /home/dmatac/public_html [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 11 of 112021-03-03 17:17:46 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.1',
  'to' => '3.1.3',
)]
2021-03-24 08:37:33 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.3',
  'to' => '3.1.4',
)]
2021-03-24 09:08:03 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.1.1',
  'to' => '3.2.1',
)]
2021-04-26 07:19:05 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.4',
  'to' => '3.2.1',
)]
2021-04-26 07:19:06 [info] elementor::elementor_updater Started 
2021-04-26 07:19:06 [info] Elementor/Upgrades - _v_3_2_0_migrate_breakpoints_to_new_system Start  
2021-04-26 07:19:06 [info] Elementor/Upgrades - _v_3_2_0_migrate_breakpoints_to_new_system Finished 
2021-04-26 07:19:06 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.4',
  'to' => '3.2.1',
)]
2021-04-26 13:30:38 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.1',
  'to' => '3.2.2',
)]
2021-05-05 13:30:12 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.2',
  'to' => '3.2.3',
)]
2021-05-05 13:30:12 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.2.1',
  'to' => '3.2.2',
)]

				

```
</details>

**Comment by Aviad-Herman** [comment]
Hey,
Thanks for the valuable input.
It seems like a bug related to inserted templates.
Until we solve it, it seems like you can just delete all the features and when you re-add new ones instead - the bug is gone.

**Comment by jaysonwebtel** [comment]
Something to add here, I have a very similar issue - I have removed all icons from my pricing tables, and when I click to edit the icons all come back even though none are set. When I click away they usually go away, but not always either.. So there is definitely an issue with something in the widget or the way it is handled.  If you ned more info from me or a example let me know.
