### ISSUE TITLE
Pro: Strange Form Widget Behavior with dynamic values

### ISSUE THREAD

**Issue by nicmare** [elementor/elementor#15101]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

As soon as i insert a dynamic tag to a form field, it suddenly disappears from frontend. Sometime it comes back. But mostly it's removed for ever.

## Steps to reproduce

1. insert a form widget
2. choose first field settings
3. click dynamic tag 
4. choose post title
5. view in frontend

here is a loom of it https://www.loom.com/share/298864d671684ce39280e25b3d6cecdf

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v5.5.61-MariaDB-38.13
	PHP Version: 7.4.18
	PHP Max Input Vars: 1000
	PHP Max Post Size: 16M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.7.2
	Site URL: https://softgarden.com
	Home URL: https://softgarden.com
	WP Multisite: No
	Max Upload Size: 16 MB
	Memory limit: 256M
	Permalink Structure: /blog/%postname%/
	Language: en-US
	Timezone: Europe/Berlin
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.3.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 5.9.6
		Author: Elliot Condon

	Akismet Anti-Spam
		Version: 4.1.9
		Author: Automattic

	DynamicConditions
		Version: 1.5.1
		Author: RTO GmbH

	Elementor
		Version: 3.2.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.2.2
		Author: Elementor.com

	Elementor Softgarden
		Version: 1.0.0
		Author: Peak Ace AG

	Elementor Widgets NB
		Version: 1.0.0
		Author: NB

	Enable Media Replace
		Version: 3.5.0
		Author: ShortPixel

	Extras for Elementor
		Version: 2.2.51
		Author: Namogo

	Formidable Forms
		Version: 4.11
		Author: Strategy11

	Formidable Forms Pro
		Version: 4.11
		Author: Strategy11

	Functions NB
		Version: 1.0
		Author: Nic Bugus

	Happy Elementor Addons
		Version: 2.24.1
		Author: weDevs

	Happy Elementor Addons Pro
		Version: 1.17.1
		Author: weDevs

	Header Footer Code Manager
		Version: 1.1.10
		Author: 99robots

	Health Check & Troubleshooting
		Version: 1.4.5
		Author: The WordPress.org community

	Intuitive Custom Post Order
		Version: 3.1.3
		Author: hijiri

	Polylang Pro
		Version: 3.0.4
		Author: WP SYNTEX

	Post Type Archive Descriptions
		Version: 1.3.0
		Author: Mark Root-Wiley, MRW Web Design, NonprofitWP.org

	Post Type Switcher
		Version: 3.2.0
		Author: John James Jacoby

	Redirection
		Version: 5.1.1
		Author: John Godley

	Resize Image After Upload
		Version: 1.8.6
		Author: ShortPixel

	Safe SVG
		Version: 1.9.9
		Author: Daryll Doyle

	ShortPixel Image Optimizer
		Version: 4.22.2
		Author: ShortPixel

	Simple History
		Version: 2.42.0
		Author: Pär Thernström

	WP Migrate DB Pro
		Version: 2.0.2
		Author: Delicious Brains

	Yoast SEO
		Version: 16.3
		Author: Team Yoast

	Yoast Test Helper
		Version: 1.14
		Author: Team Yoast


== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

	Health Check Troubleshooting Mode
		Version: 1.7.2
		Author: 

	WP Migrate DB Pro Compatibility
		Version: 1.2
		Author: Delicious Brains


== Elementor - Compatibility Tag ==
	
	Elementor Pro: compatible
	Elementor Softgarden: header_not_exists
	Elementor Widgets NB: header_not_exists
	Extras for Elementor: compatible
	Happy Elementor Addons: compatible
	Happy Elementor Addons Pro: compatible

== Elementor Pro - Compatibility Tag ==
	
	Extras for Elementor: compatible
	Happy Elementor Addons: compatible
	Happy Elementor Addons Pro: compatible

== Elements Usage ==
	
	archive : 11
		archive-posts : 3
		author-box : 1
		button : 1
		button-group : 3
		ee-search-form : 3
		heading : 22
		posts : 6
		search-form : 3
		spacer : 9
		text-editor : 6
		theme-archive-title : 3
	footer : 7
		button : 7
		divider : 2
		form : 3
		heading : 15
		html : 1
		image : 21
		nav-menu : 10
		posts : 2
		social-icons : 5
		spacer : 4
		text-editor : 20
		wpml-language-switcher : 1
	header : 7
		button : 10
		icon : 9
		image : 1
		nav-menu : 6
		polylang-language-switcher : 1
		star-rating : 4
		wp-widget-polylang : 5
	page : 26
		button : 30
		divider : 5
		gallery : 15
		heading : 159
		html : 8
		icon-list : 28
		image : 114
		image-box : 2
		menu-anchor : 4
		nav-menu : 1
		post-info : 1
		posts : 1
		price-table : 19
		recruitingcalculator : 2
		spacer : 322
		tabs : 4
		testimonial-carousel : 4
		text-editor : 205
		theme-post-excerpt : 1
		tooltip-list : 3
		video : 5
	popup : 13
		heading : 79
		spacer : 17
	section : 40
		button : 20
		button-group : 1
		divider : 12
		ee-search-form : 1
		ee-switcher : 1
		gallery : 3
		global : 3
		ha-list-group : 3
		heading : 60
		html : 3
		hubspotform : 1
		icon : 38
		icon-list : 2
		image : 17
		recruitingcalculator : 2
		recruitingcalculatorresults : 1
		slides : 3
		spacer : 46
		star-rating : 15
		tabs : 1
		text-editor : 45
		tooltip-list : 1
		video : 2
	single : 20
		author-box : 2
		button : 5
		button-group : 1
		ee-search-form : 1
		gallery : 2
		global : 2
		heading : 50
		html : 4
		hubspotform : 1
		icon-list : 4
		image : 14
		post-comments : 1
		post-info : 4
		posts : 2
		share-buttons : 1
		shortcode : 5
		spacer : 74
		table-of-contents : 1
		testimonial-carousel : 2
		text-editor : 45
		theme-post-content : 6
		theme-post-excerpt : 1
		theme-post-title : 5
	widget : 0
		author-box : 1
		form : 156
		gallery : 456
		main-filter : 11
		nav-menu : 1
		video : 1
	wp-post : 69
		button : 1
		call-to-action : 80
		counter : 3
		heading : 282
		html : 1
		image : 21
		menu-anchor : 2
		progress : 1
		read-more : 11
		recruitingcalculator : 1
		recruitingcalculatorresults : 1
		spacer : 29
		text-editor : 484
		video : 4
		wp-widget-media_audio : 1
	wp-page : 255
		accordion : 15
		alert : 7
		animated-headline : 31
		archive-posts : 1
		blockquote : 23
		button : 158
		button-group : 4
		call-to-action : 38
		circle-progress : 1
		countdown : 2
		counter : 23
		divider : 35
		ee-calendar : 4
		ee-inline-svg : -2
		ee-search-form : 1
		ee-switcher : 2
		flip-box : 2
		form : 10
		gallery : -4
		global : 3
		ha-accordion : 1
		ha-advanced-heading : 2
		ha-animated-text : 3
		ha-feature-list : 2
		ha-fun-factor : 15
		ha-image-grid : 3
		ha-logo-carousel : 9
		ha-logo-grid : 11
		ha-post-grid : 4
		ha-post-tiles : 6
		ha-skills : 9
		ha-social-icons : 2
		ha-step-flow : 36
		ha-timeline : 5
		ha-toggle : 2
		heading : 635
		html : -21
		html5-video : 10
		hubspotform : 62
		icon : 217
		icon-box : 26
		icon-list : 21
		image : 25
		image-box : 8
		image-carousel : 5
		main-download : 1
		media-carousel : 5
		menu-anchor : 55
		pardotmarketing-form-handler : 3
		portfolio : 2
		posts : 17
		price-table : 10
		progress : 1
		recruitingcalculator : 6
		recruitingcalculatorresults : 5
		slides : 16
		spacer : -50
		star-rating : 52
		testimonial-carousel : 4
		text-editor : 789
		timeline : 9
		toggle : 6
		tooltip-list : 2
		unfold : 9
		video : 6
		wp-widget-frm_show_form : 2
		wp-widget-pages : 3
	single-post : 4
		author-box : 2
		blockquote : 1
		button : 13
		button-group : 2
		ee-calendar : 1
		ee-search-form : 2
		ee-switcher : 1
		global : 6
		heading : 45
		html : 3
		image-gallery : 1
		portfolio : 1
		post-comments : 2
		post-info : 3
		posts : 4
		share-buttons : 3
		shortcode : 9
		spacer : 4
		table-of-contents : 2
		text-editor : 1
		theme-post-content : 4
		theme-post-excerpt : 2
		theme-post-featured-image : 4
		theme-post-title : 4
	search-results : 1
		archive-posts : 1
		heading : 1
		search-form : 1
		spacer : 2
	error-404 : 1
		button : 1
		heading : 1
		image : 1


== Log ==
	
JS: showing 11 of 11JS: 2021-02-18 13:33:21 [error X 2][https://softgarden.com/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.1.1:2:33399] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `ha-accordion` got as `sticky_offset` value. Expected array or object.',
)]
JS: 2021-02-22 10:28:48 [error X 3][https://softgarden.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view510\") has already been destroyed and cannot be used. 
JS: 2021-02-23 09:12:18 [error X 1][https://softgarden.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view749\") has already been destroyed and cannot be used. 
JS: 2021-02-23 09:20:12 [error X 1][https://softgarden.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view750\") has already been destroyed and cannot be used. 
JS: 2021-02-23 09:21:15 [error X 1][https://softgarden.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view741\") has already been destroyed and cannot be used. 
JS: 2021-02-23 09:25:28 [error X 1][https://softgarden.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view745\") has already been destroyed and cannot be used. 
JS: 2021-02-23 09:38:40 [error X 2][https://softgarden.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view674\") has already been destroyed and cannot be used. 
JS: 2021-03-03 03:58:57 [error X 1][https://softgarden.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.1.1:2:229206] Cannot read property \'data\' of undefined 
JS: 2021-03-05 07:50:34 [error X 22][https://de.softgarden.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.1.1:2:220731] Blocked a frame with origin \"https://de.softgarden.com\" from accessing a cross-origin frame. 
JS: 2021-03-05 08:04:37 [error X 1][https://softgarden.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.1.1:2:220731] Blocked a frame with origin \"https://softgarden.com\" from accessing a cross-origin frame. 
JS: 2021-05-11 08:08:17 [error X 1][https://softgarden.com/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.2.3:2:33385] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `ha-feature-list` got as `sticky_offset` value. Expected array or object.',
)]

PHP: showing 20 of 20PHP: 2021-02-18 15:38:21 [warning X 2][/var/www/vhosts/softgarden.com/en/softgarden.com/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::101] file_get_contents(/var/www/vhosts/softgarden.com/en/softgarden.com/wp-content/uploads/2018/12/Element-33.svg): failed to open stream: No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-02-19 16:58:56 [notice X 22][/var/www/vhosts/softgarden.com/en/softgarden.com/wp-content/plugins/elementor/includes/managers/image.php::33] Undefined index: size [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-02-22 12:57:10 [notice X 27][/var/www/vhosts/softgarden.com/en/softgarden.com/wp-content/plugins/elementor-pro/modules/query-control/module.php::738] Trying to get property 'name' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-02-23 11:20:05 [notice X 1290][/var/www/vhosts/softgarden.com/en/softgarden.com/wp-content/plugins/elementor/includes/template-library/sources/local.php::591] Trying to get property 'display_name' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-02-23 11:25:12 [notice X 1][/var/www/vhosts/softgarden.com/en/softgarden.com/wp-content/plugins/elementor-pro/modules/posts/widgets/posts.php::31] Undefined index: posts_post_type [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-02-23 11:29:42 [notice X 62][/var/www/vhosts/softgarden.com/en/softgarden.com/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-02-23 11:45:06 [notice X 2][/var/www/vhosts/softgarden.com/en/softgarden.com/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-image.php::59] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-02 12:53:34 [notice X 82][/var/www/vhosts/softgarden.com/en/softgarden.com/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-image.php::56] Undefined index: preview_size [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-18 09:51:57 [warning X 1][/var/www/vhosts/softgarden.com/en/softgarden.com/wp-content/plugins/elementor-extras/elementor-extras.php::108] Use of undefined constant ELEMENTOR_PRO_VERSION - assumed 'ELEMENTOR_PRO_VERSION' (this will throw an Error in a future version of PHP) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-18 09:52:50 [error X 2][/var/www/vhosts/softgarden.com/en/softgarden.com/wp-content/plugins/elementor-pro/plugin.php::354] Uncaught Error: Class 'ElementorPro\Core\Connect\Manager' not found in /var/www/vhosts/softgarden.com/en/softgarden.com/wp-content/plugins/elementor-pro/plugin.php:354
Stack trace:
#0 /var/www/vhosts/softgarden.com/en/softgarden.com/wp-content/plugins/elementor-pro/plugin.php(108): ElementorPro\Plugin->__construct()
#1 /var/www/vhosts/softgarden.com/en/softgarden.com/wp-content/plugins/elementor-pro/plugin.php(377): ElementorPro\Plugin::instance()
#2 /var/www/vhosts/softgarden.com/en/softgarden.com/wp-content/plugins/elementor-pro/elementor-pro.php(58): require('/var/www/vhosts...')
#3 /var/www/vhosts/softgarden.com/en/softgarden.com/wp-includes/class-wp-hook.php(287): elementor_pro_load_plugin('')
#4 /var/www/vhosts/softgarden.com/en/softgarden.com/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#5 /var/www/vhosts/softgarden.com/en/softgarden.com/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#6 /var/www/vhosts/softgarden.com/en/softgarden.com/wp-settings.php(420): do_action('plugins_loaded')
#7 /var/www/vho [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-09 13:23:15 [notice X 160][/var/www/vhosts/softgarden.com/en/softgarden.com/wp-content/plugins/elementor-pro/modules/forms/classes/form-record.php::230] Undefined index: field_label [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-13 16:03:12 [notice X 35874][/var/www/vhosts/softgarden.com/en/softgarden.com/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/module.php::130] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-19 17:55:41 [notice X 55][/var/www/vhosts/softgarden.com/en/softgarden.com/wp-content/plugins/elementor-pro/modules/forms/classes/form-record.php::253] Undefined index: custom_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-27 07:41:03 [notice X 7][/var/www/vhosts/softgarden.io/softgarden.com/wp-content/plugins/elementor-pro/core/utils.php::216] Trying to get property 'post_author' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-28 12:11:12 [notice X 19][/var/www/vhosts/softgarden.io/softgarden.com/wp-content/plugins/elementor-pro/modules/forms/submissions/actions/save-to-database.php::82] Undefined index: field_type [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-05-07 09:41:03 [notice X 88][/var/www/vhosts/softgarden.io/softgarden.com/wp-content/plugins/elementor-pro/modules/forms/classes/form-base.php::212] Undefined index: allow_multiple [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-05-07 10:00:03 [warning X 1766][/var/www/vhosts/softgarden.io/softgarden.com/wp-content/plugins/elementor-extras/modules/display-conditions/conditions/acf-choice.php::175] Invalid argument supplied for foreach() [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-05-12 14:30:25 [warning X 1][/var/www/vhosts/softgarden.io/softgarden.com/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::101] file_get_contents(/var/www/vhosts/softgarden.io/softgarden.com/wp-content/uploads/2018/09/logo-color-ngd.svg): failed to open stream: No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-05-14 15:49:35 [warning X 4][/var/www/vhosts/softgarden.io/softgarden.com/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::101] file_get_contents(/var/www/vhosts/softgarden.io/softgarden.com/wp-content/uploads/2018/09/logo-color-finanzcheck.svg): failed to open stream: No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-05-26 14:46:29 [notice X 11][/var/www/vhosts/softgarden.io/softgarden.com/wp-content/plugins/elementor-pro/modules/forms/classes/form-base.php::54] Undefined index: required [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 11 of 112021-03-05 12:37:37 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.1',
  'to' => '3.1.3',
)]
2021-03-05 16:31:12 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.1.0',
  'to' => '3.1.1',
)]
2021-03-10 17:06:45 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.3',
  'to' => '3.1.4',
)]
2021-03-18 09:57:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.1.1',
  'to' => '3.2.0',
)]
2021-03-22 13:45:42 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.2.0',
  'to' => '3.2.1',
)]
2021-05-07 17:12:26 [info] elementor::elementor_updater Started 
2021-05-07 17:12:26 [info] Elementor/Upgrades - _v_3_2_0_migrate_breakpoints_to_new_system Start  
2021-05-07 17:12:26 [info] Elementor/Upgrades - _v_3_2_0_migrate_breakpoints_to_new_system Finished 
2021-05-07 17:12:26 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.4',
  'to' => '3.2.3',
)]
2021-05-07 17:12:26 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.4',
  'to' => '3.2.3',
)]
2021-05-07 17:12:36 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.2.1',
  'to' => '3.2.2',
)]


				
```
</details>

**Comment by nicmare** [comment]
was able to isolate the source of problems. seems it comes from Happy Addons Pro Plugin. I created another loom https://www.loom.com/share/a0aca794cb2b4544b7fcaa1518eeb620 will try to solve it with their support

**Comment by DorShahar** [comment]
Hi @nicmare 
Thank you for taking the time and reporting this.

We recreated your process of work and it seems to work properly.

Please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
- There is a chance it may be related to your child theme, so please check that as well. 

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details.

Thanks.

**Comment by alfiefeatherstone** [comment]
Been getting the same issue
