### ISSUE TITLE
Global settings deleted several times a day

### ISSUE THREAD

**Issue by redpik** [elementor/elementor#15107]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Hello, I have for several days a bug absolutely incomprehensible. A "Default Kit" template is automatically created and deletes all the global settings of my site. This happens several times a day! Do you have the same problem? I have to recreate all the settings each time :(

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.17.6
	MySQL version: Percona Server (GPL), Release '37', Revision '7c516e9' v5.7.34-37
	PHP Version: 7.3.14-6+ubuntu16.04.1+deb.sury.org+1
	PHP Max Input Vars: 1000
	PHP Max Post Size: 20M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.7.2
	Site URL: https://www.carmila.com
	Home URL: https://www.carmila.com
	WP Multisite: No
	Max Upload Size: 20 Mo
	Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: fr-FR
	Timezone: 1
	Debug Mode: Inactive

== Theme ==
	Name: Carmila 2019
	Version: 1.0
	Author: Axome Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: fr_FR
	User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36

== Active Plugins ==
	Admin Columns Pro
		Version: 5.5.1
		Author: AdminColumns.com

	Admin Columns Pro - Advanced Custom Fields (ACF)
		Version: 2.6.4
		Author: AdminColumns.com

	Advanced Custom Fields PRO
		Version: 5.9.6
		Author: Elliot Condon

	All in One SEO
		Version: 4.1.1.1
		Author: All in One SEO Team

	Autoclear Autoptimize Cache
		Version: 2.1.1
		Author: Theme Surgeons

	Autoptimize
		Version: 2.8.4
		Author: Frank Goossens (futtta)

	Axome - Boost Perf
		Version: 1.0.0
		Author: axome

	Axome Contact
		Version: 1.0.0
		Author: Rémi Marandon (Axome)

	Bulk Delete
		Version: 6.0.2
		Author: Sudar

	Carmila import centres
		Version: 1.0.0
		Author: 

	Carmila import finances
		Version: 1.0.0
		Author: 

	Carmila mise a jour des chiffres clés centres
		Version: 1.0.0
		Author: 

	Disable REST API
		Version: 1.6
		Author: Dave McHale

	Ele Custom Skin
		Version: 3.1.0
		Author: Dudaster.com

	Elementor
		Version: 3.2.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.2.2
		Author: Elementor.com

	Essential Addons for Elementor
		Version: 4.7.0
		Author: WPDeveloper

	Essential Addons for Elementor - Pro
		Version: 4.4.0
		Author: WPDeveloper

	EWWW Image Optimizer
		Version: 6.1.5
		Author: Exactly WWW

	Extras for Elementor
		Version: 2.2.51
		Author: Namogo

	Front Page Custom Post Type
		Version: 1.0
		Author: Nick Halsey

	Gestion de la page Finance
		Version: 1.0.0
		Author: Rémi Marandon (Axome)

	Gestion des centres
		Version: 1.0.0
		Author: Rémi Marandon (Axome)

	Gestion des Chiffres clés
		Version: 1.0.0
		Author: Rémi Marandon (Axome)

	Gestion des Documents presse
		Version: 1.0.0
		Author: Axome

	Google Tag Manager for Wordpress
		Version: 1.13.1
		Author: Thomas Geiger

	Gravity Forms
		Version: 2.4.17
		Author: rocketgenius

	Gravity Forms styler for Elementor
		Version: 1.0.0
		Author: Essential Addons

	Hierarchy
		Version: 1.0.5.1
		Author: Jonathan Christopher

	Import des offres d'emploi
		Version: 1.0.0
		Author: Fayolle Thibault (Axome)

	iThemes Security Pro
		Version: 6.3.1
		Author: iThemes

	Loco Translate
		Version: 2.5.2
		Author: Tim Whitlock

	ManageWP - Worker
		Version: 4.9.8
		Author: GoDaddy

	NotificationX
		Version: 1.9.3
		Author: WPDeveloper

	Polylang Connect for Elementor
		Version: 1.0.5
		Author: David Decker - DECKERWEB

	Polylang Pro
		Version: 2.9
		Author: WP SYNTEX

	Polylang Theme Strings
		Version: 4.0
		Author: Modeewine

	Popup Maker
		Version: 1.16.1
		Author: Popup Maker

	Really Simple SSL
		Version: 4.0.15
		Author: Really Simple Plugins

	Redirection
		Version: 5.1.1
		Author: John Godley

	Restricted Site Access
		Version: 7.2.0
		Author: Jake Goldman, 10up, Oomph

	Rewrite Rules Inspector
		Version: 1.3.1
		Author: Automattic, Daniel Bachhuber

	Schema
		Version: 1.7.9.2
		Author: Hesham

	Slim Image Cropper for Gravity Forms
		Version: 1.4.3
		Author: PQINA

	User Role Editor
		Version: 4.59.1
		Author: Vladimir Garagulya

	Webcraftic Assets manager
		Version: 2.0.7
		Author: Webcraftic <wordpress.webraftic@gmail.com>

	WordPress Importer
		Version: 0.7
		Author: wordpressdotorg

	WP Mail SMTP
		Version: 2.8.0
		Author: WPForms

	WP OAuth Server - Pro
		Version: 3.6.0
		Author: WP OAuth Server

	WP Session Manager
		Version: 4.2.0
		Author: Eric Mann

	WP Super Cache
		Version: 1.7.3
		Author: Automattic


== Must-Use Plugins ==
	assets-manager.php
		Version: 1.0.9
		Author: 

	Axome - Wordpress Importer Customisation
		Version: 1.0
		Author: Marandon Rémi

	Axome Security
		Version: 0.1
		Author: Axome

	ManageWP - Worker Loader
		Version: 
		Author: GoDaddy


== Elementor - Compatibility Tag ==
	
	Elementor Pro: header_not_exists
	Essential Addons for Elementor: header_not_exists
	Essential Addons for Elementor - Pro: header_not_exists
	Extras for Elementor: header_not_exists
	Gravity Forms styler for Elementor: header_not_exists
	Polylang Connect for Elementor: header_not_exists

== Elementor Pro - Compatibility Tag ==
	


== Elements Usage ==
	
	archive : 8
		archive-posts : 4
		button : 4
		ee-breadcrumbs : 6
		heading : 24
		image : 4
		menu-anchor : 6
		nav-menu : 6
		posts-extra : 4
		shortcode : 6
		social-icons : 6
		theme-archive-title : 4
	footer : 8
		ee-offcanvas : 5
		heading : 38
		image : 5
		nav-menu : 8
		text-editor : 27
	header : 4
		button : 4
		image : 8
		menu-anchor : 2
		nav-menu : 4
	loop : 22
		button : 12
		heading : 22
		image : 5
		post-info : 2
		text-editor : 17
		theme-post-featured-image : 2
		theme-post-title : 6
	page : 394
		ax-actus : 7
		ax-storelocator : 4
		axome-cours-action : 7
		axome-finance : 113
		button : 527
		circle-progress : 2
		countdown : 4
		divider : 34
		eael-gravity : 84
		eael-gravity-form : 2
		ee-breadcrumbs : 114
		ee-inline-svg : 24
		flip-box : 34
		gallery : 2
		heading : 2263
		hotspots : 14
		html : 110
		icon : 243
		icon-box : 10
		icon-list : 6
		image : 1224
		image-box : 858
		media-carousel : 8
		menu-anchor : 2
		nav-menu : 146
		posts : 11
		posts-extra : 313
		share-buttons : 2
		shortcode : 47
		slides : 3
		social-icons : 106
		spacer : 89
		template : 30
		testimonial-carousel : 4
		text-editor : 2260
		toggle : 2
		video : 33
	popup : 31
		button : 4
		heading : 46
		icon : 14
		image : 9
		spacer : 2
		text-editor : 34
	section : 200
		axome-finance : 2
		button : 88
		eael-gravity : 4
		ee-breadcrumbs : 22
		heading : 124
		html : 3
		icon : 6
		image : 40
		image-box : 10
		nav-menu : 22
		posts-extra : 42
		shortcode : 6
		slides : 4
		social-icons : 32
		spacer : 2
		text-editor : 34
	single : 40
		axome-boutique : 1
		axome-centres-address : 1
		axome-centres-chiffres-cles : 3
		axome-centres-horaires : 1
		axome-centres-link-gmap : 1
		axome-contact-commercialisation : 1
		button : 40
		divider : 14
		eael-gravity-form : 2
		ee-breadcrumbs : 2
		ee-inline-svg : 2
		ee-toggle-element : 5
		google_maps : 6
		heading : 91
		icon : 15
		icon-box : 11
		icon-list : 7
		image : 7
		image-carousel : 5
		post-info : 4
		posts-extra : 19
		share-buttons : 12
		spacer : 7
		text-editor : 36
		theme-post-content : 12
		theme-post-excerpt : 5
		theme-post-featured-image : 12
		theme-post-title : 12
	widget : 0
		eael-gravity : 2
	wp-post : 4
		button : 38
		countdown : 2
		eael-gravity : 3
		ee-breadcrumbs : 18
		gallery : 1
		google_maps : 1
		heading : 139
		hotspots : 1
		icon : 22
		icon-box : 3
		image : -36
		media-carousel : 1
		nav-menu : 20
		posts-extra : 26
		shortcode : 13
		slides : 1
		social-icons : 21
		spacer : 8
		testimonial : 4
		text-editor : 5
		video : 4
	wp-page : 143
		ax-storelocator : 1
		axome-cours-action : 1
		axome-finance : 88
		button : 128
		circle-progress : 2
		divider : 20
		eael-gravity : 9
		ee-breadcrumbs : 62
		ee-inline-svg : 6
		flip-box : 4
		heading : 706
		html : 32
		icon : 54
		icon-box : 8
		icon-list : 2
		image : 159
		image-box : 80
		media-carousel : 3
		menu-anchor : 4
		nav-menu : 63
		posts : 2
		posts-extra : 65
		share-buttons : 4
		shortcode : 7
		slides : 1
		social-icons : 65
		spacer : 61
		template : -40
		text-editor : 329
		toggle : 1
		video : 15


== Log ==
	
JS: showing 10 of 10JS: 2021-02-16 13:22:28 [error X 1][https://preprod.carmila.axome.cc/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view5120\") has already been destroyed and cannot be used. 
JS: 2021-02-16 13:25:14 [error X 3][https://preprod.carmila.axome.cc/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.1.1:2:280174] Cannot read property \'id\' of null 
JS: 2021-02-16 17:39:04 [error X 2][https://preprod.carmila.axome.cc/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.1.1:2:189771] Cannot read property \'menu\' of undefined 
JS: 2021-02-16 18:57:49 [error X 4][https://preprod.carmila.axome.cc/wp-content/cache/autoptimize/js/autoptimize_d6dbeaaeb0ca9d3f464177485be6c415.js:268:25847] n.Carousel.destroy is not a function 
JS: 2021-02-16 19:41:14 [error X 81][https://preprod.carmila.axome.cc/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.1.1:2:279346] elementorFrontend.elements.window.jQuery is not a function 
JS: 2021-02-16 19:41:16 [error X 1][https://preprod.carmila.axome.cc/wp-includes/js/jquery/jquery.min.js?ver=3.5.1:2:87593] Cannot read property \'clientHeight\' of null 
JS: 2021-03-06 08:19:02 [error X 1][https://www.carmila.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.1.1:2:229172] elementorFrontend.config.elements is undefined 
JS: 2021-04-08 16:49:50 [error X 1][https://www.carmila.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:1:19952] View (cid: \"view34900\") has already been destroyed and cannot be used. 
JS: 2021-04-08 16:49:50 [error X 1][https://www.carmila.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:1:19952] View (cid: \"view34916\") has already been destroyed and cannot be used. 
JS: 2021-04-08 16:49:51 [error X 1][https://www.carmila.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:1:19952] View (cid: \"view34954\") has already been destroyed and cannot be used. 

Log: showing 20 of 282021-02-17 07:19:00 [info] Elementor Pro/Upgrades - _v_3_1_0_slides Start  
2021-02-17 07:19:00 [info] Elementor Pro/Upgrades - _v_3_1_0_slides Finished 
2021-02-17 07:19:00 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.10',
  'to' => '3.1.0',
)]
2021-02-17 07:19:01 [info] elementor-pro::elementor_pro_updater Started 
2021-02-17 07:19:01 [info] Elementor Pro/Upgrades - _v_3_1_0_media_carousel Start  
2021-02-17 07:19:01 [info] Elementor Pro/Upgrades - _v_3_1_0_media_carousel Finished 
2021-02-17 07:19:01 [info] Elementor Pro/Upgrades - _v_3_1_0_reviews Start  
2021-02-17 07:19:01 [info] Elementor Pro/Upgrades - _v_3_1_0_reviews Finished 
2021-02-17 07:19:01 [info] Elementor Pro/Upgrades - _v_3_1_0_testimonial_carousel Start  
2021-02-17 07:19:01 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.10',
  'to' => '3.1.0',
)]
2021-02-17 07:19:02 [info] Elementor Pro/Upgrades - _v_3_1_0_testimonial_carousel Finished 
2021-02-17 07:19:02 [info] Elementor Pro/Upgrades - _v_3_1_0_slides Start  
2021-02-17 07:19:02 [info] Elementor Pro/Upgrades - _v_3_1_0_slides Finished 
2021-02-17 07:19:02 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.10',
  'to' => '3.1.0',
)]
2021-05-24 08:40:27 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.1',
  'to' => '3.2.3',
)]
2021-05-24 08:40:40 [info] elementor::elementor_updater Started 
2021-05-24 08:40:40 [info] Elementor/Upgrades - _v_3_2_0_migrate_breakpoints_to_new_system Start  
2021-05-24 08:40:40 [info] Elementor/Upgrades - _v_3_2_0_migrate_breakpoints_to_new_system Finished 
2021-05-24 08:40:40 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.1',
  'to' => '3.2.3',
)]
2021-05-25 10:42:24 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.1.0',
  'to' => '3.2.2',
)]

PHP: showing 4 of 4PHP: 2021-02-17 07:19:00 [notice X 2][/home/carmila/site/www/wp-content/plugins/elementor-pro/core/upgrade/upgrades.php::911] Undefined index: pagination [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-09 17:04:55 [notice X 11][/home/carmila/site/www/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-12 11:10:54 [notice X 20][/home/carmila/site/www/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-url.php::34] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-05-24 09:40:14 [error X 1][/home/carmila/site/www/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::281] Uncaught Error: Call to a member function update_meta() on null in /home/carmila/site/www/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:281
Stack trace:
#0 /home/carmila/site/www/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(162): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(59201, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/carmila/site/www/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/carmila/site/www/wp-includes/class-wp-hook.php(292): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/carmila/site/www/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters('', Array)
#5 /home/carmila/site/www/wp-includes/p [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]


				
```
</details>

**Comment by DorShahar** [comment]
Hi,

Please create GitHub issues only for bugs reports and feature requests.
**GitHub issues are not for support.**

If you have questions or need general support, Please try:
- Elementor Community on Facebook
- Elementor Knowledge base
- Support forums on WordPress.org
- Elementor Developers docs

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details, or check [here](https://elementor.com/support/).

Thanks.
