### ISSUE TITLE
Make share-link.min.js an optional dependancy to eliminate Elementor x Adblocker issues on lightboxes

### ISSUE THREAD

**Issue by Nazrinn** [elementor/elementor#15320]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description
When user have an adblocker present (I assume, which are interacting with share buttons), it triggers the following error in the browser console:
```
frontend.min.js?ver=3.2.4:formatted:2253 
GET https://[DOMAIN]/wp-content/plugins/elementor/assets/lib/share-link/share-link.min.js?ver=3.2.4 net::ERR_BLOCKED_BY_CLIENT
```

This error doesn't appear on every page of my site, and on pages no share buttons (I suspect the presence of [YouTube?] lightbox alone trigger said bug.). However, when it appears, **no lightbox can be triggered**, even simple image lightboxes. When I click on something that should lead to a lightbox, nothing happens. 

For some reason, Swipers don't seem to be affected by said bug. Only lightboxes.

Considering the amount of people with ad blockers nowadays, it would be great if Elementor wasn't dependant of the blocked file to function; it is common for ad blockers to masks or disable share buttons.

When I disabled my ad blocker, the website worked as intended and no error was found in the console.

## Steps to reproduce

1. Download and activate an ad blocker. The one I was using when encountering the error was [AdGuard](https://chrome.google.com/webstore/detail/adguard-adblocker/bgnkhhnnamicmpeenaelnjfhikgbkllg?hl=fr).
2. Create a page with a lightbox alone, and one with share buttons (manual or not) with a lightbox to see if either one the two page trigger the console error.

If that doesn't help, this error happens on [my client website](https://barbandcarole.ca). You should be able to investigate a minimum here.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.3.29
	PHP Version: 8.0.3
	PHP Max Input Vars: 10000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.7.2
	Site URL: https://barbandcarole.ca
	Home URL: https://barbandcarole.ca
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 512M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-CA
	Timezone: America/Toronto
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.3.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_CA
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 5.9.6
		Author: Elliot Condon

	Advanced Database Cleaner
		Version: 3.0.3
		Author: Younes JFR.

	Asset CleanUp: Page Speed Booster
		Version: 1.3.7.9
		Author: Gabe Livan

	Classic Editor
		Version: 1.6
		Author: WordPress Contributors

	Custom Post Type UI
		Version: 1.9.1
		Author: WebDevStudios

	Duplicator Pro
		Version: 4.0.2.2
		Author: Snap Creek

	Elementor
		Version: 3.2.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.3.0
		Author: Elementor.com

	Enable Media Replace
		Version: 3.5.0
		Author: ShortPixel

	Image optimization service by Optimole
		Version: 3.1.1
		Author: Optimole

	Lightweight Subscribe To Comments
		Version: 1.5.8
		Author: Isabel Castillo

	LiteSpeed Cache
		Version: 3.6.4
		Author: LiteSpeed Technologies

	Phoenix Media Rename
		Version: 3.3.0
		Author: crossi72

	Post Views Counter
		Version: 1.3.4
		Author: Digital Factory

	Simple Custom Post Order
		Version: 2.5.6
		Author: Colorlib

	Site Kit by Google
		Version: 1.34.0
		Author: Google

	SVG Support
		Version: 2.3.18
		Author: Benbodhi

	The SEO Framework
		Version: 4.1.3
		Author: The SEO Framework Team

	Wordfence Security
		Version: 7.5.4
		Author: Wordfence

	WordPress Importer
		Version: 0.7
		Author: wordpressdotorg

	WordPress Popular Posts
		Version: 5.3.3
		Author: Hector Cabrera

	Yoast Duplicate Post
		Version: 4.1.2
		Author: Enrico Battocchi & Team Yoast


== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com


== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==
	


== Elements Usage ==
	
	archive : 2
		button : 3
		form : 1
		heading : 5
		html : 6
		image : 2
		shortcode : 4
		spacer : 1
		text-editor : 3
		theme-archive-title : 1
	footer : 1
		form : 1
		heading : 7
		image : 4
		shortcode : 4
		social-icons : 1
		text-editor : 6
	header : 1
		nav-menu : 1
		social-icons : 1
		theme-site-logo : 1
	section : 2
		button : 2
		heading : 2
		html : 3
		image : 1
		text-editor : 2
	widget : 0
		html : 1
		shortcode : 1
		social-icons : 1
	wp-post : 3
		image : 13
		text-editor : 17
	wp-page : 6
		button : 25
		counter : 2
		divider : 2
		form : 2
		global : 1
		heading : 49
		html : 65
		image : 18
		media-carousel : 1
		shortcode : 18
		social-icons : 2
		spacer : 10
		text-editor : 35
	single-post : 2
		button : 2
		form : 1
		heading : 10
		html : 9
		image-carousel : 1
		post-comments : 1
		post-navigation : 1
		shortcode : 18
		text-editor : 1
		theme-post-content : 1
		theme-post-featured-image : 1
		video : 1
	error-404 : 1
		button : 1
		heading : 2


== Log ==
	
Log: showing 20 of 232021-03-22 14:35:34 [info] elementor::elementor_updater Started 
2021-03-22 14:35:34 [info] Elementor/Upgrades - _v_3_2_0_migrate_breakpoints_to_new_system Start  
2021-03-22 14:35:34 [info] Elementor/Upgrades - _v_3_2_0_migrate_breakpoints_to_new_system Finished 
2021-03-22 14:35:34 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.0-dev8',
  'to' => '3.2.0-beta1',
)]
2021-03-22 14:35:34 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.0-dev8',
  'to' => '3.2.0-beta1',
)]
2021-04-13 07:49:38 [error] Save submission failed, db error: Table 'emrfro02_main.bcr_e_submissions' doesn't exist 
2021-04-27 00:17:56 [info] elementor::elementor_updater Started 
2021-04-27 00:17:56 [info] Elementor/Upgrades - _v_3_2_0_migrate_breakpoints_to_new_system Start  
2021-04-27 00:17:56 [info] Elementor/Upgrades - _v_3_2_0_migrate_breakpoints_to_new_system Finished 
2021-04-27 00:17:56 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.0-beta1',
  'to' => '3.2.2',
)]
2021-04-27 00:17:56 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.0-beta1',
  'to' => '3.2.2',
)]
2021-05-05 21:26:31 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.2',
  'to' => '3.2.3',
)]
2021-05-27 15:14:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.3',
  'to' => '3.2.4',
)]
2021-06-08 01:44:55 [info] elementor-pro::elementor_pro_updater Started 
2021-06-08 01:44:55 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon Start  
2021-06-08 01:44:55 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon Finished 
2021-06-08 01:44:55 [info] Elementor Pro/Upgrades - _v_3_3_0_recalc_usage_data Start  
2021-06-08 01:44:56 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.3.0-dev1',
  'to' => '3.3.0',
)]
2021-06-08 01:44:56 [info] Elementor Pro/Upgrades - _v_3_3_0_recalc_usage_data Finished 
2021-06-08 01:44:56 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.3.0-dev1',
  'to' => '3.3.0',
)]

PHP: showing 19 of 19PHP: 2021-03-17 14:32:45 [error X 2][/home/emrfro02/public_html\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-manager.php::281] Uncaught Error: Call to a member function update_meta() on null in /home/emrfro02/public_html\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-manager.php:281
Stack trace:
#0 /home/emrfro02/public_html\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-manager.php(162): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(7, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/emrfro02/public_html\wp-content\plugins\elementor\core\common\modules\ajax\module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/emrfro02/public_html\wp-includes\class-wp-hook.php(292): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/emrfro02/public_html\wp-includes\class-wp-hook.php(316): WP_Hook->apply_filters [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-21 21:18:14 [notice X 162][/home/emrfro02/public_html\wp-content\plugins\elementor\includes\conditions.php::90] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-30 21:36:25 [warning X 74][/home/emrfro02/public_html\wp-content\plugins\elementor\includes\conditions.php::90] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-01 18:09:41 [warning X 1][/home/emrfro02/public_html\wp-content\plugins\elementor-pro\modules\dynamic-tags\acf\tags\acf-url.php::34] Undefined array key 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-03 23:29:38 [warning X 1][/home/emrfro02/public_html\wp-content\plugins\elementor-pro\modules\assets-manager\asset-types\icons\custom-icons.php::243] unlink(/home/emrfro02/public_html/wp-content/uploads/2021/04/SVG.zip): Resource temporarily unavailable [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-03 23:30:50 [warning X 1][/home/emrfro02/public_html\wp-content\plugins\elementor-pro\modules\assets-manager\asset-types\icons\custom-icons.php::243] unlink(/home/emrfro02/public_html/wp-content/uploads/2021/04/Fontello.zip): Resource temporarily unavailable [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-06 01:30:20 [notice X 3][/home/emrfro02/public_html\wp-content\plugins\elementor\modules\usage\module.php::146] uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-06 12:22:40 [warning X 1][/home/emrfro02/public_html/wp-content/plugins/elementor-pro/modules/forms/actions/mailchimp.php::210] foreach() argument must be of type array|object, null given [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-06 12:24:26 [warning X 1][/home/emrfro02/public_html/wp-content/plugins/elementor-pro/modules/forms/actions/mailchimp.php::189] Undefined array key "email_address" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-10 12:50:25 [warning X 4][/home/emrfro02/public_html/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::101] file_get_contents(/home/emrfro02/public_html/wp-content/uploads/2021/03/crea-logo.svg): Failed to open stream: No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-10 12:50:25 [warning X 15][/home/emrfro02/public_html/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::101] file_get_contents(/home/emrfro02/public_html/wp-content/uploads/2021/03/BCRlogo.svg): Failed to open stream: No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-11 15:39:57 [warning X 2][/home/emrfro02/public_html/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::101] file_get_contents(/home/emrfro02/public_html/wp-content/uploads/2021/03/the-royal_logomark-logo.svg): Failed to open stream: No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-11 15:41:54 [warning X 1][/home/emrfro02/public_html/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::101] file_get_contents(/home/emrfro02/public_html/wp-content/uploads/2021/03/beadonorca_logotype-logo.svg): Failed to open stream: No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-11 15:42:35 [warning X 1][/home/emrfro02/public_html/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::101] file_get_contents(/home/emrfro02/public_html/wp-content/uploads/2021/03/childrens-hospital-of-eastern-ontario_logo_monogram.svg): Failed to open stream: No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-11 15:43:04 [warning X 1][/home/emrfro02/public_html/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::101] file_get_contents(/home/emrfro02/public_html/wp-content/uploads/2021/03/national-art-centre_logomark-logo.svg): Failed to open stream: No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-11 15:46:19 [warning X 1][/home/emrfro02/public_html/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::101] file_get_contents(/home/emrfro02/public_html/wp-content/uploads/2021/03/innovation-logo.svg): Failed to open stream: No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-11 16:01:33 [warning X 5][/home/emrfro02/public_html/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::101] file_get_contents(/home/emrfro02/public_html/wp-content/uploads/2021/03/the-royal_logo.svg): Failed to open stream: No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-13 02:11:37 [warning X 3][/home/emrfro02/public_html/wp-content/plugins/elementor/includes/managers/image.php::86] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-27 11:36:13 [warning X 3][/home/emrfro02/public_html\wp-content\plugins\elementor\core\common\modules\ajax\module.php::171] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]```
</details>

**Comment by rami-elementor** [comment]
Hi @Nazrinn ,

Thank you for submitting a feature request. 

After review, we have decided not to add this to our roadmap for the time being. 

We will, of course, keep this suggestion in mind and consider adding it if there is significant demand in the future.

Please feel free to contact us again with other feature suggestions.
