### ISSUE TITLE
Social Icons widgets layout in Safari / CSS Minify

### ISSUE THREAD

**Issue by steve1401** [elementor/elementor#15437]
The E Pro Social Icon widget allows you to set a column of auto, 1 , 2, 3 etc. columns. 

If it is set to auto, Safari (mobile and desktop) renders the icons on top of each other, even though the Elementor preview shows them as side by side expected. As well as this, if set to auto we have found that the CSS there are all sorts of spacing issues when we minify the CSS.

If we set the columns to 2 (or relative to the number of icons) then the icons behave as expected.

Chrome and Firefox seem to behave in an expected way, regardless of auto or fixed column number.

SYSTEM INFO
==========

					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.3.29
	PHP Version: 7.4.20
	PHP Max Input Vars: 8000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.7.2
	Site URL: https://queenbee.webcetera.uk
	Home URL: https://queenbee.webcetera.uk
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-GB
	Timezone: Europe/London
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.3.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36

== Active Plugins ==
	Activity Log
		Version: 2.7.0
		Author: Activity Log Team

	Elementor
		Version: 3.2.5
		Author: Elementor.com

	Elementor Pro
		Version: 3.3.0
		Author: Elementor.com

	Envato Elements
		Version: 2.0.8
		Author: Envato

	Limit Login Attempts Reloaded
		Version: 2.22.1
		Author: Limit Login Attempts Reloaded

	Rank Math SEO
		Version: 1.0.66
		Author: Rank Math

	Rank Math SEO PRO
		Version: 2.8.0
		Author: Rank Math

	UpdraftPlus - Backup/Restore
		Version: 2.16.58.25
		Author: UpdraftPlus.Com, DavidAnderson

	Yoast Duplicate Post
		Version: 4.1.2
		Author: Enrico Battocchi & Team Yoast

== Must-Use Plugins ==
	installatron_hide_status_test.php
		Version: 
		Author: 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible
	Envato Elements: Compatible

== Elementor Pro - Compatibility Tag ==
	
	Envato Elements: Incompatible

== Elements Usage ==
	
	footer : 1
		form : 1
		heading : 9
		icon-list : 4
		image : 2
	header : 2
		button : 4
		heading : 2
		image : 3
		nav-menu : 2
		social-icons : 2
	section : 4
		button : 19
		divider : 4
		heading : 53
		icon-box : 3
		icon-list : 1
		image : 39
		image-box : 3
		image-carousel : 1
		nav-menu : 1
		social-icons : 1
		spacer : 6
		text-editor : 40
	wp-page : 10
		button : 4
		call-to-action : 6
		divider : 22
		gallery : 1
		heading : 125
		icon-list : 1
		image : 9
		spacer : 32
		text-editor : 25

== Log ==
	
Log: showing 20 of 302021-04-22 09:53:13 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.8.5',
  'to' => '3.2.1',
)]
2021-04-22 09:53:48 [info] elementor::elementor_updater Started 
2021-04-22 09:53:48 [info] Elementor/Upgrades - _v_3_2_0_migrate_breakpoints_to_new_system Start  
2021-04-22 09:53:48 [info] Elementor/Upgrades - _v_3_2_0_migrate_breakpoints_to_new_system Finished 
2021-04-22 09:53:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.4',
  'to' => '3.2.1',
)]
2021-04-22 09:53:48 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.4',
  'to' => '3.2.1',
)]
2021-04-26 12:25:08 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.1',
  'to' => '3.2.2',
)]
2021-05-13 09:38:57 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.2',
  'to' => '3.2.3',
)]
2021-05-13 09:39:25 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.2.1',
  'to' => '3.2.2',
)]
2021-06-01 11:26:46 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.3',
  'to' => '3.2.4',
)]
2021-06-16 09:07:58 [info] elementor-pro::elementor_pro_updater Started 
2021-06-16 09:07:58 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon Start  
2021-06-16 09:07:58 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.2.2',
  'to' => '3.3.0',
)]
2021-06-16 09:08:00 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon callback needs to run more 1 times 
2021-06-16 09:08:00 [info] Elementor Pro/Upgrades - _v_3_3_0_recalc_usage_data Start  
2021-06-16 09:08:00 [info] Elementor Pro/Upgrades - _v_3_3_0_recalc_usage_data Finished 
2021-06-16 09:08:00 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon Start (2 of 2, 100%) 
2021-06-16 09:08:01 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon Finished 
2021-06-16 09:08:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.2.2',
  'to' => '3.3.0',
)]
2021-06-16 16:05:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.4',
  'to' => '3.2.5',
)]

PHP: showing 4 of 4PHP: 2021-04-26 12:32:07 [notice X 1][/home/webcetera/queenbee.webcetera.uk/wp-content/plugins/elementor/includes/template-library/classes/class-import-images.php::162] Undefined index: url [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-26 12:34:31 [notice X 20][/home/webcetera/queenbee.webcetera.uk/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-26 13:50:57 [notice X 4][/home/webcetera/queenbee.webcetera.uk/wp-content/plugins/elementor/includes/managers/image.php::86] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-05-05 10:19:36 [error X 2][/home/webcetera/queenbee.webcetera.uk/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::281] Uncaught Error: Call to a member function update_meta() on null in /home/webcetera/queenbee.webcetera.uk/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:281
Stack trace:
#0 /home/webcetera/queenbee.webcetera.uk/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(162): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(6, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/webcetera/queenbee.webcetera.uk/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/webcetera/queenbee.webcetera.uk/wp-includes/class-wp-hook.php(292): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/webcetera/queenbee.webcetera.uk/wp-includes/class-wp-hook.php(316): WP [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

<img width="1003" alt="Screenshot 2021-06-22 at 14 10 23" src="https://user-images.githubusercontent.com/86303028/122930265-bd889500-d363-11eb-88d3-21d47677490c.png">
<img width="879" alt="Screenshot 2021-06-22 at 14 00 03" src="https://user-images.githubusercontent.com/86303028/122930270-beb9c200-d363-11eb-8d7a-7a5c1bb701ec.png">

## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by Nazrinn** [comment]
I have noticed the same bug and had the same workaround for a while.

I think this is due due to a CSS class Elementor adds to the social media icon widget when a user browse the site using Safari (I don't remember the name of the class, but I remember it having the word "safari" or "apple" in it).

I used this CSS snippet, applied site-wide, fas a better workaround. 
With this, you won't need to specify the number of column every time you use the social media icon widget.
```
.elementor-social-icons-wrapper.elementor-grid {
    display: grid;
    grid-auto-flow: column;
}
```

Let me know!

**Comment by steve1401** [comment]
> I used this CSS snippet, applied site-wide, fas a better workaround.

Thanks, Nazrinn,  I'll investigate this workaround. It still seems to me to be a bug to fix, though?
