### ISSUE TITLE
Google Search Console error with "FAQPage"

### ISSUE THREAD

**Issue by rafaviana** [elementor/elementor#15530]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Hello,
I have several FAQ widgets in the same page and Google Search Console is showing me the error: Duplicate "FAQPage" field.
Is there anyone with the same issue? I think Elementor should check how many FAQ widgets are in the page and output a JSON script with all the Q&A merged, as they show in their website: https://developers.google.com/search/docs/data-types/faqpage

## Steps to reproduce

Add multiple FAQ widgtes into the same page. Check the output code and you'll see multiple FAQPage JSON fields. Google says each FAQ Page should have only one "FAQPage" JSON field.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.3.30
	PHP Version: 7.3.28
	PHP Max Input Vars: 1000
	PHP Max Post Size: 32M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.7.2
	Site URL: https://www.pousadela.pt
	Home URL: https://www.pousadela.pt
	WP Multisite: No
	Max Upload Size: 32 MB
	Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: pt-PT
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: the7dtchild
	Version: 1.0.0
	Author: Dream-Theme
	Child Theme: Yes
	Parent Theme Name: The7
	Parent Theme Version: 9.13.0.1
	Parent Theme Author: Dream-Theme

== User ==
	Role: administrator
	WP Profile lang: pt_PT
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36

== Active Plugins ==
	301 Redirects Pro
		Version: 5.74
		Author: WebFactory Ltd

	Advanced Custom Fields
		Version: 5.9.7
		Author: Delicious Brains

	Advanced Custom Fields Multilingual
		Version: 1.8.2
		Author: OnTheGoSystems

	Better Search Replace
		Version: 1.3.4
		Author: Delicious Brains

	Chaty
		Version: 2.8.2
		Author: Premio

	Classic Editor
		Version: 1.6
		Author: WordPress Contributors

	Compress JPEG & PNG images
		Version: 3.2.1
		Author: TinyPNG

	DynamicConditions
		Version: 1.5.1
		Author: RTO GmbH

	Elementor
		Version: 3.2.5
		Author: Elementor.com

	Elementor Pro
		Version: 3.3.1
		Author: Elementor.com

	Enable Media Replace
		Version: 3.5.0
		Author: ShortPixel

	GDPR Cookie Compliance (CCPA, PIPEDA ready)
		Version: 4.5.6
		Author: Moove Agency

	Google Tag Manager for Wordpress
		Version: 1.13.1
		Author: Thomas Geiger

	iPanorama 360 (PRO)
		Version: 1.6.14
		Author: Avirtum

	Newsletter, SMTP, Email marketing and Subscribe forms by Sendinblue
		Version: 3.1.14
		Author: Sendinblue

	Shortcoder
		Version: 5.4
		Author: Aakash Chakravarthy

	Smash Balloon Instagram Feed
		Version: 2.9.1
		Author: Smash Balloon

	The7 Elements
		Version: 2.5.7.1
		Author: Dream-Theme

	The7 Slider Revolution
		Version: 6.4.11
		Author: ThemePunch

	WP-Optimize - Clean, Compress, Cache
		Version: 3.1.11
		Author: David Anderson, Ruhani Rabin, Team Updraft

	WP Datepicker
		Version: 1.9.2
		Author: Fahad Mahmood

	WPML Multilingual CMS
		Version: 4.4.10
		Author: OnTheGoSystems

	WPML SEO
		Version: 2.0.1
		Author: OnTheGoSystems

	WPML String Translation
		Version: 3.1.8
		Author: OnTheGoSystems

	WPML Translation Management
		Version: 2.10.6
		Author: OnTheGoSystems

	Yoast Duplicate Post
		Version: 4.1.2
		Author: Enrico Battocchi & Team Yoast

	Yoast SEO
		Version: 16.5
		Author: Team Yoast


== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==
	


== Elements Usage ==
	
	footer : 3
		button : 2
		divider : 1
		heading : 2
		image : 6
		nav-menu : 1
		shortcode : 1
		social-icons : 1
		text-editor : 5
	popup : 6
		image : 1
		spacer : 1
		text-editor : 5
	section : 1
		button : 2
		heading : 2
		image : 2
	wp-post : 8
		button : 1
		divider : 12
		facebook-button : 6
		gallery : 1
		heading : 10
		image : 10
		text-editor : 36
		video : 1
	wp-page : 59
		accordion : 3
		button : 39
		divider : 4
		form : 9
		gallery : 4
		google_maps : 1
		heading : 66
		icon-list : 15
		image : 55
		image-box : 19
		menu-anchor : 4
		shortcode : 1
		slider_revolution : 8
		template : 2
		text-editor : 99
		the7-breadcrumb : 4
		wp-widget-instagram-feed-widget : 1
	single-post : 3
		button : 1
		divider : 2
		heading : 1
		image : 1
		image-box : 14
		shortcode : 2
		text-editor : 7
		theme-post-title : 1


== Log ==
	
Log: showing 19 of 192021-05-31 16:14:37 [info] elementor-pro::elementor_pro_updater Started 
2021-05-31 16:14:37 [info] Elementor Pro/Upgrades - _v_3_1_0_media_carousel Start  
2021-05-31 16:14:37 [info] Elementor Pro/Upgrades - _v_3_1_0_media_carousel Finished 
2021-05-31 16:14:37 [info] Elementor Pro/Upgrades - _v_3_1_0_reviews Start  
2021-05-31 16:14:37 [info] Elementor Pro/Upgrades - _v_3_1_0_reviews Finished 
2021-05-31 16:14:37 [info] Elementor Pro/Upgrades - _v_3_1_0_testimonial_carousel Start  
2021-05-31 16:14:37 [info] Elementor Pro/Upgrades - _v_3_1_0_testimonial_carousel Finished 
2021-05-31 16:14:37 [info] Elementor Pro/Upgrades - _v_3_1_0_slides Start  
2021-05-31 16:14:37 [info] Elementor Pro/Upgrades - _v_3_1_0_slides Finished 
2021-05-31 16:14:37 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.10',
  'to' => '3.2.2',
)]
2021-05-31 16:14:38 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.10',
  'to' => '3.2.2',
)]
2021-06-21 11:09:21 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.4',
  'to' => '3.2.5',
)]
2021-06-21 17:18:00 [info] elementor-pro::elementor_pro_updater Started 
2021-06-21 17:18:00 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon Start  
2021-06-21 17:18:00 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.2.2',
  'to' => '3.3.1',
)]
2021-06-21 17:18:01 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon Finished 
2021-06-21 17:18:01 [info] Elementor Pro/Upgrades - _v_3_3_0_recalc_usage_data Start  
2021-06-21 17:18:01 [info] Elementor Pro/Upgrades - _v_3_3_0_recalc_usage_data Finished 
2021-06-21 17:18:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.2.2',
  'to' => '3.3.1',
)]

PHP: showing 7 of 7PHP: 2021-06-08 09:42:47 [notice X 3][/home/pousadel/public_html/staging/wp-content/plugins/elementor-pro/modules/query-control/module.php::738] Trying to get property 'name' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-06-08 13:06:19 [notice X 19][/home/pousadel/public_html/staging/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-06-08 14:17:33 [notice X 1][/home/pousadel/public_html/staging/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::162] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-06-08 15:51:24 [error X 2][/home/pousadel/public_html/staging/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::281] Uncaught Error: Call to a member function update_meta() on bool in /home/pousadel/public_html/staging/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:281
Stack trace:
#0 /home/pousadel/public_html/staging/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(162): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/pousadel/public_html/staging/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/pousadel/public_html/staging/wp-includes/class-wp-hook.php(292): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/pousadel/public_html/staging/wp-includes/class-wp-hook.php(316): WP_Hook->apply [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-06-09 15:48:08 [notice X 33][/home/pousadel/public_html/staging/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-url.php::34] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-06-18 15:08:03 [notice X 4][/home/pousadel/public_html/staging/wp-content/plugins/elementor-pro/modules/query-control/module.php::727] Undefined index: filter_type [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-06-21 17:18:05 [notice X 5][/home/pousadel/public_html/staging/wp-content/plugins/elementor-pro/license/updater.php::75] Undefined index: new_version [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]


				```
</details>

**Comment by DorShahar** [comment]
Hi @rafaviana 
We do not have FAQ widget.
Please check it with the widget developer. 

You can see all of our widgets here: https://elementor.com/widgets/

Thanks

**Comment by rafaviana** [comment]
Hi @DorShahar , 
sorry for the misunderstood, I mentioned that the issue is related with FAQ widget but the issue is related with your accordion widget when "FAQ Schema" option is enabled (image attached)

<img width="671" alt="Elementor___Perguntas_Frequentes" src="https://user-images.githubusercontent.com/5817213/124394882-42c36080-dcf9-11eb-8281-0bb9b40cc1b9.png">

**Comment by nicomollet** [comment]
@DorShahar can this issue be reopened?

Multiple accordion widgets with "FAQ schema" enabled, give structured data errors: `Duplicate field "FAQpage"`

![image](https://user-images.githubusercontent.com/108828/192269422-bb31d77f-9481-4e6b-852d-b675efb155e1.png)

https://search.google.com/test/rich-results?url=https%3A%2F%2Fwww.aquatonic.fr%2Fsaint-malo%2Ffaq%2F

**Comment by nicholaszein** [comment]
Hi!

This issue has been solved a long time ago with the introduction of the Nested Accordion. We recommend enabling the Nested Elements feature in the Elementor > Settings > Features page, and replacing your old Accordions with the new Nested one for better compatibility.

We are closing this issue as it's very outdated.

Kind regards
