### ISSUE TITLE
Site Problem if Elemento-pro is updated (Multipage inside 1 page is loading)

### ISSUE THREAD

**Issue by amindiary** [elementor/elementor#15676]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
Hi, We have an issue with Elementor 3.3.0 , I've tried to rollback but it seems error still persist.

the issue is, in some pages, like example.com/care
all pages that has /care slug (like example.com/local/dorset/care)
are showing there! 
I've attached a video to see.

**https://streamable.com/por28g**

and our error log is like below:

WordPress version 5.7.2
Current theme: Agespace (version 1.0)
Current plugin: Elementor Pro (version 3.1.1) PHP version 8.0.1
Error Details
=============
An error of type E_ERROR was caused in line 69 of the file /var/www/html/wp-content/plugins/elementor-pro/core/modules-manager.php. Error message: Uncaught Error: Class "\ElementorPro\Modules\License\Module" not found in /var/www/html/wp-content/plugins/elementor-pro/core/modules-manager.php:69
Stack trace:
#0 /var/www/html/wp-content/plugins/elementor-pro/plugin.php(306): ElementorPro\Core\Modules_Manager->__construct()
#1 /var/www/html/wp-includes/class-wp-hook.php(292): ElementorPro\Plugin->on_elementor_init('')
#2 /var/www/html/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters('', Array)
#3 /var/www/html/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#4 /var/www/html/wp-content/plugins/elementor/includes/plugin.php(559): do_action('elementor/init')
#5 /var/www/html/wp-includes/class-wp-hook.php(292): Elementor\Plugin->init('')
#6 /var/www/html/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters(NULL, Array)
#7 /var/www/html/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#8 /var/www/html/wp-settings.php(560): do_action('init')
#9 /var/www/html/wp-config.php(95): require_once('/var/www/html/w...')
#10 /var/www/html/wp-load.php(37): require_once('/var/www/html/w...')
#11 /var/www/html/wp-login.php(12): require('/var/www/html/w...')
#12 {main}

WordPress version 5.7.2
Current theme: Agespace (version 1.0)
Current plugin: Elementor Pro (version 3.3.2) PHP version 7.4.14

Error Details
=============
An error of type E_ERROR was caused in line 69 of the file /var/www/html/wp-content/plugins/elementor-pro/core/modules-manager.php. Error message: Uncaught Error: Class '\ElementorPro\Modules\License\Module' not found in /var/www/html/wp-content/plugins/elementor-pro/core/modules-manager.php:69
Stack trace:
#0 /var/www/html/wp-content/plugins/elementor-pro/plugin.php(311): ElementorPro\Core\Modules_Manager->__construct()
#1 /var/www/html/wp-includes/class-wp-hook.php(292): ElementorPro\Plugin->on_elementor_init('')
#2 /var/www/html/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters('', Array)
#3 /var/www/html/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#4 /var/www/html/wp-content/plugins/elementor/includes/plugin.php(559): do_action('elementor/init')
#5 /var/www/html/wp-includes/class-wp-hook.php(292): Elementor\Plugin->init('')
#6 /var/www/html/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters(NULL, Array)
#7 /var/www/html/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#8 /var/www/html/wp-settings.php(560): do_action('init')
#9 /var/www/html/wp-config.php(95): require_once('/var/www/html/w...')
#10 /var/www/html/wp-l

## Steps to reproduce

I've disabed all plusing, enabled Hello elementor Theme, cleared htaccess file , problem not solved.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.29 (Ubuntu)
	MySQL version: mariadb.org binary distribution v10.4.17
	PHP Version: 7.4.14
	PHP Max Input Vars: 1000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.7.2
	Site URL: https://www.agespace.org
	Home URL: https://www.agespace.org
	WP Multisite: No
	Max Upload Size: 100 MB
	Memory limit: 2G
	Permalink Structure: /%postname%
	Language: en-GB
	Timezone: Europe/London
	Debug Mode: Inactive

== Theme ==
	Name: Agespace
	Version: 1.0
	Author: Chris
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 Edg/91.0.864.67

== Active Plugins ==
	301 Redirects
		Version: 2.70
		Author: WebFactory Ltd

	Advanced Ads
		Version: 1.25.1
		Author: Thomas Maier, Advanced Ads GmbH

	Advanced Ads Pro
		Version: 2.12.0
		Author: Advanced Ads GmbH

	Advanced Ads – Geo Targeting
		Version: 1.3.3
		Author: Advanced Ads

	Advanced Ads – Google Ad Manager Integration
		Version: 1.3.1
		Author: Advanced Ads GmbH

	Advanced Ads – Responsive Ads
		Version: 1.10.1
		Author: Advanced Ads GmbH

	Advanced Ads – Tracking
		Version: 2.0.1
		Author: Advanced Ads GmbH

	Advanced Custom Fields: Extended
		Version: 0.8.8.4
		Author: ACF Extended

	Advanced Custom Fields PRO
		Version: 5.9.5
		Author: Elliot Condon

	Advanced Database Cleaner
		Version: 3.0.3
		Author: Younes JFR.

	Basic User Avatars
		Version: 1.0.6
		Author: Stranger Studios

	bbPress
		Version: 2.6.6
		Author: The bbPress Contributors

	Classic Editor
		Version: 1.6
		Author: WordPress Contributors

	Convert custom fields to custom taxonomies
		Version: 1.0.3
		Author: Shounak Gupte

	Custom Field Suite
		Version: 2.6
		Author: Matt Gibbs

	Custom Post Type UI
		Version: 1.9.2
		Author: WebDevStudios

	Custom Taxonomy Order
		Version: 3.3.0
		Author: Marcel Pol

	Delete Expired Transients
		Version: 2.0.7
		Author: WebAware

	DynamicConditions
		Version: 1.5.1
		Author: RTO GmbH

	Ele Custom Skin
		Version: 3.1.1
		Author: Dudaster.com

	Ele Custom Skin Pro
		Version: 3.1.0
		Author: Dudaster.com

	Elementor
		Version: 3.3.0
		Author: Elementor.com

	Elementor Google Map Extended
		Version: 1.2.1
		Author: InternetCSS

	Elementor Pro
		Version: 3.3.1
		Author: Elementor.com

	EL Members
		Version: 1.0.0
		Author: PalmerCreative

	Essential Addons for Elementor
		Version: 4.8.0
		Author: WPDeveloper

	Google Analytics for WordPress by MonsterInsights
		Version: 7.18.0
		Author: MonsterInsights

	Google Tag Manager for Wordpress
		Version: 1.13.1
		Author: Thomas Geiger

	Google XML Sitemap Generator
		Version: 2.0.1
		Author: XmlSitemapGenerator.org

	Gravity Forms
		Version: 2.4.20.5
		Author: Gravity Forms

	Gravity Forms MailChimp Add-On
		Version: 4.6
		Author: rocketgenius

	Gravity Forms User Registration Add-On
		Version: 4.6
		Author: Gravity Forms

	Intuitive Custom Post Order
		Version: 3.1.3
		Author: hijiri

	JetElements For Elementor
		Version: 2.5.8
		Author: المنتور فارسی

	JetMenu
		Version: 2.0.9
		Author: المنتور فارسی

	JetTabs For Elementor
		Version: 2.1.13
		Author: المنتور فارسی

	LiteSpeed Cache
		Version: 3.6.4
		Author: LiteSpeed Technologies

	Max Mega Menu
		Version: 2.9.4
		Author: megamenu.com

	MetForm
		Version: 1.4.8
		Author: Wpmet

	Notification
		Version: 7.2.4
		Author: BracketSpace

	OMGF
		Version: 4.4.4
		Author: Daan from FFW.Press

	Permalink Manager Pro
		Version: 2.2.9.9
		Author: Maciej Bis

	Pre* Party Resource Hints
		Version: 1.7.7.1
		Author: Sam Perrow

	Profile Builder
		Version: 3.4.9
		Author: Cozmoslabs

	Query Monitor
		Version: 3.7.1
		Author: John Blackbourn

	Really Simple SSL
		Version: 5.0.2
		Author: Really Simple Plugins

	reCAPTCHA for bbPress
		Version: 1.0.4
		Author: Hitesh Chandwani

	Remove Noreferrer
		Version: 2.0.0
		Author: Alexander Kadyrov

	SearchWP
		Version: 4.1.21
		Author: SearchWP

	Shortcode in Menus
		Version: 3.5.1
		Author: Gagan Deep Singh

	SVG Support
		Version: 2.3.18
		Author: Benbodhi

	Ultimate Blocks
		Version: 2.4.7
		Author: Ultimate Blocks

	Unlimited Elements for Elementor (Premium)
		Version: 1.4.39
		Author: Unlimited Elements

	Wapuuvatar
		Version: 2.6
		Author: Lee Willis

	What The File
		Version: 1.5.4
		Author: Never5

	WP All Import - ACF Add-On
		Version: 3.3.1
		Author: Soflyy

	WP All Import Pro
		Version: 4.6.5
		Author: Soflyy

	WP Armour - Honeypot Anti Spam
		Version: 1.8.4
		Author: Dnesscarkey

	WP Mail SMTP Pro
		Version: 2.3.1
		Author: WPForms

	WP Offload Media Lite
		Version: 2.5.3
		Author: Delicious Brains

	Yoast Duplicate Post
		Version: 4.1.2
		Author: Enrico Battocchi & Team Yoast

	Yoast SEO
		Version: 16.7
		Author: Team Yoast


== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com


== Elementor - Compatibility Tag ==
	
	Elementor Google Map Extended: Compatibility not specified
	Elementor Pro: Compatibility not specified
	Essential Addons for Elementor: Compatibility not specified
	JetElements For Elementor: Compatibility not specified
	JetTabs For Elementor: Compatibility not specified
	Unlimited Elements for Elementor (Premium): Compatibility not specified

== Elementor Pro - Compatibility Tag ==
	


== Elements Usage ==
	
	archive : 4
		breadcrumbs : 1
		button : 1
		heading : 13
		icon-box : 1
		image : 1
		jet-accordion : 1
		menu-anchor : 1
		posts : 2
		shortcode : 9
		spacer : 1
		text-editor : 1
	loop : 14
		call-to-action : 2
		heading : 5
		icon-box : 1
		image : 1
		spacer : 1
	page : 25
		breadcrumbs : 1
		eael-gravity-form : 2
		form : 2
		heading : 27
		image : 2
		posts : 1
		shortcode : 17
		spacer : 8
		text-editor : 1
	popup : 5
		form : 1
		text-editor : 1
	section : 43
		button : 5
		eael-gravity-form : 4
		form : 3
		heading : 19
		icon-list : 1
		image : 5
		image-box : 1
		jet-mobile-menu : 1
		shortcode : 2
		spacer : 6
	widget : 0
		eb-google-map-extended : 1
		jet-carousel : 1
	wp-post : 23
		blockquote : 4
		button : 57
		eael-gravity-form : 3
		form : 1
		heading : 524
		icon : 1
		icon-box : 33
		icon-list : 29
		image : 189
		menu-anchor : 30
		mf-button : 1
		mf-email : 1
		mf-text : 2
		mf-textarea : 1
		posts : 3
		spacer : 102
		text-editor : 161
		ucaddon_agespace_alertbox : 10
		ucaddon_agespace_btn : 26
		ucaddon_agespace_image_with_border : 4
		ucaddon_agespace_simple_list : 5
		video : 1
		wp-widget-media_video : 2
	wp-page : 280
		blockquote : 2
		breadcrumbs : 5
		button : 1
		call-to-action : 2
		divider : 4
		form : 1
		heading : 346
		html : 2
		image : 129
		menu-anchor : 1
		posts : 1
		shortcode : 10
		sidebar : 1
		spacer : 104
		text-editor : 512
		ucaddon_agespace_accordion : 24
		ucaddon_agespace_alertbox : 41
		ucaddon_agespace_btn : 66
		ucaddon_agespace_image_with_alt : 11
		ucaddon_agespace_qa : 8
		ucaddon_agespace_simple_list : 76
	single-post : 2
		breadcrumbs : 1
		button : 6
		eb-google-map-extended : 2
		gallery : 1
		heading : 13
		icon-list : 3
		image : 3
		image-carousel : 1
		image-gallery : 1
		metform : 1
		posts : 1
		price-table : 3
		shortcode : 7
		spacer : 6
		template : 6
		text-editor : 3
		theme-post-content : 1
		ucaddon_agespace_list : 1
	single-page : 7
		breadcrumbs : 3
		button : 3
		heading : 20
		jet-accordion : 2
		menu-anchor : 3
		shortcode : 19
		spacer : 2
		text-editor : 3


== Log ==
	
Log: showing 20 of 412021-07-16 12:32:16 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.5',
  'to' => '3.3.0',
)]
2021-07-16 12:32:18 [info] elementor::elementor_updater Started 
2021-07-16 12:32:19 [info] Elementor/Upgrades - _on_each_version Start  
2021-07-16 12:32:19 [info] Elementor/Upgrades - _on_each_version Finished 
2021-07-16 12:32:19 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.5',
  'to' => '3.3.0',
)]
2021-07-16 12:32:20 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.5',
  'to' => '3.3.0',
)]
2021-07-16 12:32:27 [info] elementor::elementor_updater Started 
2021-07-16 12:32:27 [info] Elementor/Upgrades - _on_each_version Start  
2021-07-16 12:32:27 [info] Elementor/Upgrades - _on_each_version Finished 
2021-07-16 12:32:28 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.5',
  'to' => '3.3.0',
)]
2021-07-16 12:32:30 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.5',
  'to' => '3.3.0',
)]
2021-07-16 12:32:33 [info] elementor::elementor_updater Started 
2021-07-16 12:32:34 [info] Elementor/Upgrades - _on_each_version Start  
2021-07-16 12:32:34 [info] Elementor/Upgrades - _on_each_version Finished 
2021-07-16 12:32:34 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.5',
  'to' => '3.3.0',
)]
2021-07-16 12:32:41 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.5',
  'to' => '3.3.0',
)]
2021-07-16 12:32:56 [info] elementor::elementor_updater Started 
2021-07-16 12:32:56 [info] Elementor/Upgrades - _on_each_version Start  
2021-07-16 12:33:12 [info] Elementor/Upgrades - _on_each_version Finished 
2021-07-16 12:33:12 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.5',
  'to' => '3.3.0',
)]

PHP: showing 2 of 2PHP: 2021-07-16 12:34:14 [error X 1][/var/www/html/wp-content/plugins/elementor/core/debug/inspector.php::31] Uncaught Error: Class 'Elementor\Tools' not found in /var/www/html/wp-content/plugins/elementor/core/debug/inspector.php:31
Stack trace:
#0 /var/www/html/wp-content/plugins/elementor/includes/plugin.php(609): Elementor\Core\Debug\Inspector->__construct()
#1 /var/www/html/wp-content/plugins/elementor/includes/plugin.php(549): Elementor\Plugin->init_components()
#2 /var/www/html/wp-includes/class-wp-hook.php(292): Elementor\Plugin->init('')
#3 /var/www/html/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters(NULL, Array)
#4 /var/www/html/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#5 /var/www/html/wp-settings.php(560): do_action('init')
#6 /var/www/html/wp-config.php(95): require_once('/var/www/html/w...')
#7 /var/www/html/wp-load.php(37): require_once('/var/www/html/w...')
#8 /var/www/html/wp-blog-header.php(13): require_once('/var/www/html/w...')
#9 /var/www/html/index.php(17): require('/var/www/html/w...')
#10 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-07-16 12:34:19 [error X 1][/var/www/html/wp-content/plugins/elementor/modules/library/documents/not-supported.php::17] Class Elementor\Modules\Library\Documents\Not_Supported contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Elementor\Controls_Stack::get_name) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]


				
```
</details>

**Comment by amindiary** [comment]
Let's Follow same Problem here : https://github.com/elementor/elementor/issues/15677
