### ISSUE TITLE
Elementor Tabs element content using shortcode has broken design when Improved CSS Loading experiment is enabled

### ISSUE THREAD

**Issue by d19dotca** [elementor/elementor#15788]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
There is an issue with the Tabs element in Elementor when the Improved CSS Loading experiment is enabled. 

Screenshot of what it should look like (with the experiment disabled):
<img width="1176" alt="Screen Shot 2021-07-27 at 8 55 15 AM" src="https://user-images.githubusercontent.com/8153796/127186645-c4db2e17-e909-4df8-8aa6-36cee5ac76cc.png">

Screenshot of what it looks like after enabling the Improved CSS Loading experiment:
<img width="1184" alt="Screen Shot 2021-07-27 at 8 51 05 AM" src="https://user-images.githubusercontent.com/8153796/127186691-2f6623d0-1b44-4cf3-a0f7-55e7fe422bcc.png">

## Steps to reproduce
1. Create a page with the Tab element, and use a Shortcode from an Elementor section template to fill in the contents of the Tab.
2. View how it looks, and now enable the Improved CSS Loading experiment and compare.
3. Notice the content is modified and no longer appears as designed in the template in the Tab.

## Isolating the problem
- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```				
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.41 (Ubuntu)
	MySQL version: (Ubuntu) v8.0.23
	PHP Version: 7.4.3
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.8
	Site URL: https://www.staging.cle.d19.ca
	Home URL: https://www.staging.cle.d19.ca
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 1024M
	Permalink Structure: /%category%/%postname%/
	Language: en-CA
	Timezone: America/Vancouver
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.4.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_CA
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Safari/605.1.15

== Active Plugins ==
	AuthLDAP
		Version: 2.4.10
		Author: Andreas Heigl <andreas@heigl.org>

	Better Search Replace
		Version: 1.3.4
		Author: Delicious Brains

	Code Snippets
		Version: 2.14.1
		Author: Code Snippets Pro

	Elementor
		Version: 3.3.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.3.4
		Author: Elementor.com

	MainWP Child
		Version: 4.1.7
		Author: MainWP

	Rank Math SEO
		Version: 1.0.68.1
		Author: Rank Math

	Rank Math SEO PRO
		Version: 2.12.0
		Author: Rank Math

	Redis Object Cache
		Version: 2.0.21
		Author: Till Krüss

	ShortPixel Image Optimizer
		Version: 4.22.2
		Author: ShortPixel

	SMTP Mailer
		Version: 1.1.2
		Author: naa986

	WooCommerce
		Version: 5.5.2
		Author: Automattic

	WP Rocket
		Version: 3.9.0.5
		Author: WP Media


== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==
	


== Elements Usage ==
	
	footer : 2
		divider : 1
		heading : 4
		icon-list : 2
		social-icons : 1
		text-editor : 2
	header : 1
		icon-list : 1
		image : 1
		nav-menu : 1
		search-form : 1
		woocommerce-menu-cart : 1
	page : 2
		heading : 4
		spacer : 1
		theme-site-logo : 1
	section : 6
		alert : 1
		price-list : 6
		text-editor : 1
	widget : 0
		testimonial-carousel : 1
	wp-post : 0
		gallery : 7
		global : 1
		google_maps : 1
		heading : 18
		icon-list : 3
		image : 1
		shortcode : 1
		tabs : 1
		template : 4
		text-editor : 7
		toggle : 1
	wp-page : 12
		animated-headline : 1
		call-to-action : 5
		global : 1
		google_maps : 1
		heading : 5
		image : 1
		lottie : 1
		text-editor : 5
		wc-elements : 1
	single-page : 2
		theme-post-content : 2
		theme-post-title : 2
	product-archive : 2
		divider : 1
		heading : 2
		theme-archive-title : 1
		wc-archive-products : 1
		wc-categories : 1
		woocommerce-products : 1
		wp-widget-woocommerce_layered_nav : 2
		wp-widget-woocommerce_layered_nav_filters : 1


== Log ==
	
PHP: showing 6 of 6PHP: 2021-04-24 06:03:12 [notice X 57][/app/data/public/wp-content/plugins/elementor-pro/license/updater.php::75] Undefined index: new_version [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-05-02 14:25:21 [notice X 36][/app/data/public/wp-content/plugins/elementor/includes/managers/image.php::86] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-06-17 20:13:45 [notice X 10][/app/data/public/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-07-03 10:33:15 [notice X 1][/app/data/public/wp-content/plugins/elementor-pro/modules/posts/skins/skin-content-base.php::248] Trying to get property 'ID' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-07-06 21:44:02 [error X 1][/app/data/public/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::285] Uncaught Error: Call to a member function update_meta() on bool in /app/data/public/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:285
Stack trace:
#0 /app/data/public/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(166): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions()
#2 /app/data/public/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func()
#3 /app/data/public/wp-includes/class-wp-hook.php(292): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#4 /app/data/public/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters()
#5 /app/data/public/wp-includes/plugin.php(484): WP_Hook->do_action()
#6 /app/data/public/wp-admin/admin-ajax.php(187): do_action()
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-07-19 17:16:17 [notice X 1][/app/data/public/wp-content/plugins/elementor-pro/modules/woocommerce/widgets/add-to-cart.php::142] Undefined index: post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 20 of 262021-06-07 23:13:28 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon Finished 
2021-06-07 23:13:28 [info] Elementor Pro/Upgrades - _v_3_3_0_recalc_usage_data Start  
2021-06-07 23:13:28 [info] Elementor Pro/Upgrades - _v_3_3_0_recalc_usage_data Finished 
2021-06-07 23:13:28 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.2.2',
  'to' => '3.3.0',
)]
2021-06-07 23:13:28 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.2.2',
  'to' => '3.3.0',
)]
2021-06-16 08:52:04 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.4',
  'to' => '3.2.5',
)]
2021-06-20 10:32:33 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.3.0',
  'to' => '3.3.1',
)]
2021-07-12 23:28:07 [info] elementor::elementor_updater Started 
2021-07-12 23:28:07 [info] Elementor/Upgrades - _on_each_version Start  
2021-07-12 23:28:07 [info] Elementor/Upgrades - _on_each_version Finished 
2021-07-12 23:28:07 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.5',
  'to' => '3.3.0',
)]
2021-07-12 23:28:07 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.5',
  'to' => '3.3.0',
)]
2021-07-13 16:20:02 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.3.1',
  'to' => '3.3.2',
)]
2021-07-20 10:10:18 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.3.0',
  'to' => '3.3.1',
)]
2021-07-20 10:10:19 [info] elementor::elementor_updater Started 
2021-07-20 10:10:19 [info] Elementor/Upgrades - _on_each_version Start  
2021-07-20 10:10:21 [info] Elementor/Upgrades - _on_each_version Finished 
2021-07-20 10:10:21 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.3.0',
  'to' => '3.3.1',
)]
2021-07-20 22:29:00 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.3.2',
  'to' => '3.3.3',
)]
2021-07-21 21:22:24 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.3.3',
  'to' => '3.3.4',
)]
```
</details>

**Comment by d19dotca** [comment]
@DorShahar or @shilo-ey - can you please reproduce / tag as a bug? This one is keeping me from using the experiment on one of my client sites in particular which makes heavy use of the Tabs element.

**Comment by d19dotca** [comment]
Looking for an update please, @DorShahar.

**Comment by d19dotca** [comment]
This is still an issue @DorShahar & @shilo-ey, I just tried it again today hoping that after all the updates the issue would be resolved even inadvertently, but it still remains.

**Comment by rishikeshw** [comment]
Please fix this issue. I am also facing the same issue where I add media carousel as a saved template and display it in the tabs with shortcodes, the first tab displays the media carousel without any design break, but the rest of the tabs show broken layout. 

Tried everything, requesting you to please fix this asap.

PS : When I use browser zoom +- it displays it properly.

**Comment by markjr** [comment]
Similar issue here with trying to load financial data from EOD Historical Data Financial Data Plugin, want to put Balance Sheet and Income Statement within tabs but the output just breaks up completely.

**Comment by markjr** [comment]
@rishikeshw sorry for delayaed response and thanks for the pointer.
That seems to fix a problem with sliders within tabs, I'm not using sliders in mine, just trying to render output from an external data feed. 

Is there something in #11250 that applies to tabs in general?

**Comment by ElinaMacichina** [comment]
Hello, 
I have same issue with tabs when adding shortcode (elementor section template) as tab content - all icons in page disappears and appears as bullets. And also I see that when adding template to whatever widget as shortcode it appears broken in editting mode. Added photos in attachment. 
![image](https://github.com/elementor/elementor/assets/92719267/25e38f88-8194-47c9-b2bb-bf29b8cd4977)

![image](https://github.com/elementor/elementor/assets/92719267/aa540e1d-b180-40a7-8f37-81a61416da63)

**Comment by roymckenzie** [comment]
A client of mine is experience the same issue as @ElinaMacichina. Specifically the CSS being inlined into the page as text.
