### ISSUE TITLE
Woocommerce Archive Products Issues Not Resolved With 3.3.7 - Can't Set Columns

### ISSUE THREAD

**Issue by sstrantz** [elementor/elementor#15996]
@shilo-ey @DorShahar 

This is a continuation of the issue posted here:  https://github.com/elementor/elementor/issues/15857

**Issue:**  
**-Archive Products Widget Has nowhere to set columns.**

-Using Hello Theme.  When trying to set columns there, it will not allow different columns for each breakpoint.  If it is set to X, it sets to X in all breakpoints.

**To Reproduce:**

-Insert Archive Products widget.
-Can't find anywhere to set columns.
-Go to Hello Theme.  Columns can't be set differently for each breakpoint.

**SYSTEM INFO**

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.32-35
	PHP Version: 7.4.22
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.8
	Site URL: https://sues16.sg-host.com
	Home URL: https://sues16.sg-host.com
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/Indiana/Indianapolis
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.4.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0

== Active Plugins ==
	Code Snippets
		Version: 2.14.1
		Author: Code Snippets Pro

	Elementor
		Version: 3.3.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.3.7
		Author: Elementor.com

	JetSmartFilters
		Version: 2.3.1
		Author: Crocoblock

	LitExtension Customer Password Plugin
		Version: 1.0.0
		Author: LitExtension

	Product Variations Swatches for WooCommerce
		Version: 1.0.1.16
		Author: VillaTheme

	Rank Math SEO
		Version: 1.0.70
		Author: Rank Math

	SiteGround Optimizer
		Version: 5.8.4
		Author: SiteGround

	SiteGround Security
		Version: 1.1.1
		Author: SiteGround

	WooCommerce
		Version: 5.5.2
		Author: Automattic

	WooCommerce PayPal Payments
		Version: 1.5.0
		Author: WooCommerce

== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==
	

== Elements Usage ==
	
	footer : 1
		icon : 1
		icon-list : 3
		image : 1
		text-editor : 2
	header : 1
		icon-list : 2
		nav-menu : 2
		search-form : 2
		text-editor : 2
		theme-site-logo : 2
		woocommerce-menu-cart : 2
	product : 2
		global : 4
		woocommerce-product-add-to-cart : 2
		woocommerce-product-data-tabs : 2
		woocommerce-product-images : 2
		woocommerce-product-price : 2
		woocommerce-product-rating : 1
		woocommerce-product-short-description : 2
		woocommerce-product-title : 2
	section : 3
		image : 1
		text-editor : 1
		woocommerce-product-add-to-cart : 1
		woocommerce-product-data-tabs : 1
		woocommerce-product-images : 1
		woocommerce-product-meta : 1
		woocommerce-product-price : 1
		woocommerce-product-rating : 1
		woocommerce-product-short-description : 1
		woocommerce-product-title : 1
		woocommerce-product-upsell : 1
	widget : 0
		accordion : 1
		jet-smart-filters-active : 1
		jet-smart-filters-checkboxes : 5
		jet-smart-filters-remove-filters : 1
		text-editor : 2
		toggle : 1
	wp-page : 3
		global : 1
	search-results : 1
		archive-posts : 1
		theme-archive-title : 1
	product-archive : 1
		global : 2
		image : 1
		jet-smart-filters-active : 1
		jet-smart-filters-checkboxes : 6
		jet-smart-filters-remove-filters : 2
		testimonial-carousel : 1
		toggle : 1
		wc-archive-products : 1

== Log ==
	
Log: showing 4 of 42021-07-28 12:30:00 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.3.1',
  'to' => '3.3.4',
)]
2021-08-02 08:35:56 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.3.4',
  'to' => '3.3.5',
)]
2021-08-11 10:45:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.3.5',
  'to' => '3.3.6',
)]
2021-08-16 06:47:40 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.3.6',
  'to' => '3.3.7',
)]

PHP: showing 2 of 2PHP: 2021-07-29 07:45:33 [error X 2][/home/customer/www/sues16.sg-host.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::285] Uncaught Error: Call to a member function update_meta() on bool in /home/customer/www/sues16.sg-host.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:285
Stack trace:
#0 /home/customer/www/sues16.sg-host.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(166): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/customer/www/sues16.sg-host.com/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/customer/www/sues16.sg-host.com/public_html/wp-includes/class-wp-hook.php(303): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/customer/www/sues16 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-07-29 08:17:06 [error X 6][/home/customer/www/sues16.sg-host.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::285] Uncaught Error: Call to a member function update_meta() on null in /home/customer/www/sues16.sg-host.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:285
Stack trace:
#0 /home/customer/www/sues16.sg-host.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(166): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(10, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/customer/www/sues16.sg-host.com/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/customer/www/sues16.sg-host.com/public_html/wp-includes/class-wp-hook.php(303): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/customer/www/sues16.s [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

**Comment by avivu** [comment]
Hello @sstrantz,
The Archive Products widget option to set columns and rows is through the WordPress Customize screen, and because of that, we can't add responsive controls to this section.

I marked this issue as a Feature Request, and we will examine the option of adding the columns and rows controls into the Elementor widget panel.
