### ISSUE TITLE
wp_kses_post strips srcset attribute from images

### ISSUE THREAD

**Issue by tomslominski** [elementor/elementor#16111]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

None of my images (using the Image or Featured Image widgets) have a srcset, so they're always downloading the full size image, or whatever size I set the image to.

I think the problem is that the widget uses `wp_kses_post()` in the new `print_attachment_image_html()` function on line 156 of `/elementor/includes/controls/groups/image-size.php`. If I remove the `wp_kses_post()`, the issue disappears.

When filtering `wp_kses_allowed_html('post')`, srcset is not one of the allowed paramaters, hence why this is getting stripped.

## Steps to reproduce

Insert an Image widget into a page, containing any raster image. Check the page source code - the srcset attribute is missing.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.20.1
	MySQL version: mariadb.org binary distribution v10.4.20
	PHP Version: 7.4.20
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.8
	Site URL: https://alc.slominski.dev
	Home URL: https://alc.slominski.dev
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-GB
	Timezone: Europe/London
	Debug Mode: Active

== Theme ==
	Name: ---
	Version: 0.0.1
	Author: Tom Slominski
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.4.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:91.0) Gecko/20100101 Firefox/91.0

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 5.9.9
		Author: Delicious Brains

	Disable Emojis (GDPR friendly)
		Version: 1.7.3
		Author: Ryan Hellyer

	Elementor
		Version: 3.4.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.3.7
		Author: Elementor.com

	External Links
		Version: 6.8.1
		Author: Denis de Bernardy & Mike Koepke

	FAQ Schema For Pages And Posts
		Version: 2.3.0
		Author: Krystian Szastok (SEO Consultant)

	Head, Footer and Post Injections
		Version: 3.2.2
		Author: Stefano Lissa

	HTML Forms
		Version: 1.3.22
		Author: ibericode

	Infinite Scroll Elementor
		Version: 2.3.2
		Author: Joy Chetry

	Redirection
		Version: 5.1.2
		Author: John Godley

	SpinupWP
		Version: 1.3
		Author: Delicious Brains

	Yoast SEO
		Version: 16.7
		Author: Team Yoast


== Must-Use Plugins ==
	SpinupWP Debug Log Path
		Version: 1.0
		Author: Delicious Brains


== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible
	Infinite Scroll Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==
	


== Elements Usage ==
	
	footer : 1
		text-editor : 2
	header : 1
		icon-list : 1
		image : 1
		nav-menu : 1
	section : 1
		form : 1
		heading : 1
	wp-page : 17
		alc_team_slider : 1
		form : 1
		heading : 9
		html : 1
		icon-list : 2
		image : 19
		image-gallery : 2
		infinite-scroll-elementor-widget : 1
		posts : 1
		shortcode : 1
		template : 3
		text-editor : 33
	single-page : 1
		theme-post-content : 1
		theme-post-featured-image : 1
		theme-post-title : 1
	error-404 : 1
		button : 1
		heading : 1
		text-editor : 1


== Log ==
	
PHP: showing 2 of 2PHP: 2021-08-17 16:08:51 [error X 3][/sites/alc.slominski.dev/files/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::285] Uncaught Error: Call to a member function update_meta() on null in /sites/alc.slominski.dev/files/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:285
Stack trace:
#0 /sites/alc.slominski.dev/files/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(166): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions()
#2 /sites/alc.slominski.dev/files/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func()
#3 /sites/alc.slominski.dev/files/wp-includes/class-wp-hook.php(303): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#4 /sites/alc.slominski.dev/files/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()
#5 /sites/alc.slominski.dev/files/wp-includes/plugin.php(470): WP_Hook->do_action()
#6 /sites/alc.slominski.dev/files/wp-admin/admin-ajax.php [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-17 16:21:48 [notice X 4][/sites/alc.slominski.dev/files/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 5 of 52021-08-21 21:20:03 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.0',
  'to' => '3.4.2',
)]
2021-08-21 21:21:03 [info] elementor::elementor_updater Started 
2021-08-21 21:21:03 [info] Elementor/Upgrades - _on_each_version Start  
2021-08-21 21:21:03 [info] Elementor/Upgrades - _on_each_version Finished 
2021-08-21 21:21:03 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.0',
  'to' => '3.4.2',
)]
```
</details>

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.4.3

Feel free to update

Thanks!
