### ISSUE TITLE
New Breakpoints 3.4.2 Not hiding and showing Hamburger Menu and Desktop menu properly

### ISSUE THREAD

**Issue by bradallenfisher** [elementor/elementor#16126]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Trying to use a new breakpoint to set where the Mobile dropdown Breakpoint occurs results in both menu hamburger and desktop menu displaying at all breakpoints. 
## Steps to reproduce
 - enable new breakpoints or start from fresh install
 - add tablet extra and laptop
 - use default widths for new breakpoints
 - set your mobile dropdown breakpoint to either of the new wider breakpoints ( in this case it was tablet extra)
 - in editor the results are as expected. Desktop menu hides where it should and hamburger is presented
 - in frontend site (no editor) both hamburger and desktop are shown at all breakpoints. 
## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with default HELLO theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.25 (Debian)
	MySQL version: mariadb.org binary distribution v10.4.20
	PHP Version: 8.0.9 (Save happens on PHP 7.4, PHP 7.3)
	PHP Max Input Vars: 10000
	PHP Max Post Size: 1000M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.8
	Site URL: https://wordpress-640040-2116565.cloudwaysapps.com
	Home URL: https://wordpress-640040-2116565.cloudwaysapps.com
	WP Multisite: No
	Max Upload Size: 1,000 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.4.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36

== Active Plugins ==
	All-in-One WP Migration
		Version: 7.46
		Author: ServMask

	Category Order and Taxonomy Terms Order
		Version: 1.5.7.5
		Author: Nsp-Code

	Code Snippets
		Version: 2.14.1
		Author: Code Snippets Pro

	Elementor
		Version: 3.4.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.3.8
		Author: Elementor.com

	Envato Elements
		Version: 2.0.9
		Author: Envato

	GeoDirectory
		Version: 2.1.0.20
		Author: AyeCode Ltd

	Regenerate Thumbnails
		Version: 3.1.5
		Author: Alex Mills (Viper007Bond)

	UsersWP
		Version: 1.2.2.27
		Author: AyeCode Ltd

	UsersWP - ReCaptcha
		Version: 1.3.10
		Author: AyeCode Ltd


== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible
	Envato Elements: Incompatible

== Elementor Pro - Compatibility Tag ==
	
	Envato Elements: Compatible

== Elements Usage ==
	
	footer : 1
		divider : 3
		heading : 2
		icon-list : 2
		image : 1
		social-icons : 1
		text-editor : 2
	header : 1
		button : 1
		nav-menu : 1
		theme-site-logo : 1
	popup : 1
		nav-menu : 1
	section : 6
		button : 2
		divider : 4
		heading : 6
		icon-list : 3
		image : 2
		social-icons : 1
		text-editor : 7
	wp-page : 4
		button : 7
		counter : 3
		heading : 5
		icon-list : 1
		image : 1
		image-box : 3
		jet-accordion : 1
		text-editor : 5
	not-supported : 0
	geodirectory-archive-item : 1
		button : 1
	geodirectory-archive : 2


== Log ==
	
PHP: showing 8 of 8PHP: 2021-08-16 15:14:25 [notice X 14][/var/www/html/fws/wordpress/wp-content/plugins/elementor/includes/template-library/sources/remote.php::225] Undefined index: access_level [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-16 15:19:46 [notice X 24][/var/www/html/fws/wordpress/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-17 18:21:16 [error X 1][/var/www/html/fws/wordpress/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::285] Uncaught Error: Call to a member function update_meta() on null in /var/www/html/fws/wordpress/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:285
Stack trace:
#0 /var/www/html/fws/wordpress/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(166): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions()
#2 /var/www/html/fws/wordpress/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func()
#3 /var/www/html/fws/wordpress/wp-includes/class-wp-hook.php(303): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#4 /var/www/html/fws/wordpress/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()
#5 /var/www/html/fws/wordpress/wp-includes/plugin.php(470): WP_Hook->do_action()
#6 /var/www/html/fws/wordpress/wp-admin/admin-ajax.php(187): do_action()
#7 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-19 13:15:50 [error X 10][/var/www/html/fws/wordpress/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::656] Uncaught Error: Call to a member function attributes() on bool in /var/www/html/fws/wordpress/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php:656
Stack trace:
#0 /var/www/html/fws/wordpress/wp-includes/class-wp-hook.php(303): Elementor\Core\Files\Assets\Svg\Svg_Handler->set_svg_meta_data()
#1 /var/www/html/fws/wordpress/wp-includes/plugin.php(189): WP_Hook->apply_filters()
#2 /var/www/html/fws/wordpress/wp-includes/post.php(6366): apply_filters()
#3 /var/www/html/fws/wordpress/wp-admin/includes/media.php(421): wp_update_attachment_metadata()
#4 /var/www/html/fws/wordpress/wp-admin/includes/ajax-actions.php(2549): media_handle_upload()
#5 /var/www/html/fws/wordpress/wp-admin/async-upload.php(33): wp_ajax_upload_attachment()
#6 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-19 13:15:50 [error X 41][/var/www/html/fws/wordpress/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::656] Uncaught Error: Call to a member function attributes() on bool in /var/www/html/fws/wordpress/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php:656
Stack trace:
#0 /var/www/html/fws/wordpress/wp-includes/class-wp-hook.php(303): Elementor\Core\Files\Assets\Svg\Svg_Handler->set_svg_meta_data()
#1 /var/www/html/fws/wordpress/wp-includes/plugin.php(189): WP_Hook->apply_filters()
#2 /var/www/html/fws/wordpress/wp-includes/post.php(6366): apply_filters()
#3 /var/www/html/fws/wordpress/wp-admin/includes/image.php(178): wp_update_attachment_metadata()
#4 /var/www/html/fws/wordpress/wp-admin/includes/ajax-actions.php(2459): wp_update_image_subsizes()
#5 /var/www/html/fws/wordpress/wp-includes/class-wp-hook.php(303): wp_ajax_media_create_image_subsizes()
#6 /var/www/html/fws/wordpress/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()
#7 /var/www/html/fws/wordpress/wp-includes/plugin.php(470): WP_Hook->do_action()
#8 /var/www/html/fws/wordpress/wp-admin/admin-ajax.php(187): do_action()
#9 {ma [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-23 19:36:11 [notice X 2][/var/www/html/fws/wordpress/wp-content/plugins/elementor/core/app/modules/import-export/module.php::87] Trying to get property 'label' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-23 19:42:03 [notice X 1][/var/www/html/fws/wordpress/wp-content/plugins/elementor/includes/managers/image.php::87] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-24 00:29:13 [warning X 1][/home/640040.cloudwaysapps.com/tbfsydxwpw/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 12 of 122021-08-16 17:21:47 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.3.6',
  'to' => '3.3.7',
)]
2021-08-18 23:10:29 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.0',
  'to' => '3.4.1',
)]
2021-08-19 11:54:53 [info] elementor::elementor_updater Started 
2021-08-19 11:54:53 [info] Elementor/Upgrades - _on_each_version Start  
2021-08-19 11:54:53 [info] Elementor/Upgrades - _on_each_version Finished 
2021-08-19 11:54:53 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.0',
  'to' => '3.4.1',
)]
2021-08-19 16:18:24 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.1',
  'to' => '3.4.2',
)]
2021-08-19 16:18:34 [info] elementor::elementor_updater Started 
2021-08-19 16:18:34 [info] Elementor/Upgrades - _on_each_version Start  
2021-08-19 16:18:34 [info] Elementor/Upgrades - _on_each_version Finished 
2021-08-19 16:18:34 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.1',
  'to' => '3.4.2',
)]
2021-08-24 00:13:39 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.3.7',
  'to' => '3.3.8',
)]

```
</details>

**Comment by jesskiri** [comment]
+1 same issue.

**Comment by DorShahar** [comment]
This issue has been added to Elementor Core v3.5.0

Feel free to update

Thanks!
