### ISSUE TITLE
Sticky Header Not working

### ISSUE THREAD

**Issue by maurocarreraok** [elementor/elementor#16131]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

Sticky header is not working properly. It do not stick. Only come sticky when i "resize" de screen (on desktop for example) ... Works in mobile as well. Works in the editor (on deskltio) but is not working on the front end...

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.20.1
	MySQL version: MariaDB Server v10.6.4
	PHP Version: 7.3.29
	PHP Max Input Vars: 3000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.8
	Site URL: https://reports.privatedomain.com
	Home URL: https://reports.privatedomain.com
	WP Multisite: No
	Max Upload Size: 8 MB
	Memory limit: 2048M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/New_York
	Debug Mode: Inactive

== Theme ==
	Name: privatedomain Theme
	Version: 2.0.0
	Author: privatedomain
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.4.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36

== Active Plugins ==
	Autoptimize
		Version: 2.9.1
		Author: Frank Goossens (futtta)

	Elementor
		Version: 3.4.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.3.8
		Author: Elementor.com

	JetEngine
		Version: 2.8.10
		Author: Crocoblock

	TranslatePress - Multilingual
		Version: 2.0.9
		Author: Cozmoslabs, Razvan Mocanu, Madalin Ungureanu, Cristophor Hurduban

	Wordfence Security
		Version: 7.5.5
		Author: Wordfence

	WPSHAPERE
		Version: 6.1.13
		Author: AcmeeDesign Softwares and Solutions


== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==
	


== Elements Usage ==
	
	footer : 1
		form : 1
		heading : 12
		image : 1
	header : 1
		button : 1
		nav-menu : 1
		theme-site-logo : 1
	page : 1
		divider : 4
		heading : 14
		image : 5
		jet-listing-grid : 1
		text-editor : 9
	popup : 2
		button : 2
		heading : 3
		image : 1
		text-editor : 1
	wp-post : 0
		divider : 1
		heading : 1
		nav-menu : 1
	wp-page : 2
		divider : 4
		heading : 18
		image : 13
		text-editor : 12


== Log ==
	
Log: showing 7 of 72021-08-20 07:55:11 [info] elementor::elementor_updater Started 
2021-08-20 07:55:11 [info] Elementor/Upgrades - _on_each_version Start  
2021-08-20 07:55:11 [info] Elementor/Upgrades - _on_each_version Finished 
2021-08-20 07:55:11 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.3.1',
  'to' => '3.4.2',
)]
2021-08-20 07:55:11 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.3.1',
  'to' => '3.4.2',
)]
2021-08-20 08:11:04 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.3.1',
  'to' => '3.3.7',
)]
2021-08-24 09:30:56 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.3.7',
  'to' => '3.3.8',
)]

PHP: showing 20 of 24PHP: 2021-08-20 08:40:29 [error X 1][/var/www/report/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::656] Uncaught Error: Call to a member function attributes() on bool in /var/www/report/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php:656
Stack trace:
#0 /var/www/report/wp-includes/class-wp-hook.php(303): Elementor\Core\Files\Assets\Svg\Svg_Handler->set_svg_meta_data(Array, 89)
#1 /var/www/report/wp-includes/plugin.php(189): WP_Hook->apply_filters(Array, Array)
#2 /var/www/report/wp-includes/post.php(6366): apply_filters('wp_update_attac...', Array, 89)
#3 /var/www/report/wp-admin/includes/media.php(421): wp_update_attachment_metadata(89, Array)
#4 /var/www/report/wp-admin/includes/ajax-actions.php(2549): media_handle_upload('async-upload', '11', Array)
#5 /var/www/report/wp-admin/async-upload.php(33): wp_ajax_upload_attachment()
#6 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-20 08:40:30 [error X 5][/var/www/report/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::656] Uncaught Error: Call to a member function attributes() on bool in /var/www/report/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php:656
Stack trace:
#0 /var/www/report/wp-includes/class-wp-hook.php(303): Elementor\Core\Files\Assets\Svg\Svg_Handler->set_svg_meta_data(Array, 89)
#1 /var/www/report/wp-includes/plugin.php(189): WP_Hook->apply_filters(Array, Array)
#2 /var/www/report/wp-includes/post.php(6366): apply_filters('wp_update_attac...', Array, 89)
#3 /var/www/report/wp-admin/includes/image.php(178): wp_update_attachment_metadata(89, Array)
#4 /var/www/report/wp-admin/includes/ajax-actions.php(2459): wp_update_image_subsizes(89)
#5 /var/www/report/wp-includes/class-wp-hook.php(303): wp_ajax_media_create_image_subsizes('')
#6 /var/www/report/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#7 /var/www/report/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#8 /var/www/report/wp-admin/ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-20 08:40:48 [error X 1][/var/www/report/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::656] Uncaught Error: Call to a member function attributes() on bool in /var/www/report/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php:656
Stack trace:
#0 /var/www/report/wp-includes/class-wp-hook.php(303): Elementor\Core\Files\Assets\Svg\Svg_Handler->set_svg_meta_data(Array, 90)
#1 /var/www/report/wp-includes/plugin.php(189): WP_Hook->apply_filters(Array, Array)
#2 /var/www/report/wp-includes/post.php(6366): apply_filters('wp_update_attac...', Array, 90)
#3 /var/www/report/wp-admin/includes/media.php(421): wp_update_attachment_metadata(90, Array)
#4 /var/www/report/wp-admin/includes/ajax-actions.php(2549): media_handle_upload('async-upload', '66', Array)
#5 /var/www/report/wp-admin/async-upload.php(33): wp_ajax_upload_attachment()
#6 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-20 08:40:48 [error X 5][/var/www/report/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::656] Uncaught Error: Call to a member function attributes() on bool in /var/www/report/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php:656
Stack trace:
#0 /var/www/report/wp-includes/class-wp-hook.php(303): Elementor\Core\Files\Assets\Svg\Svg_Handler->set_svg_meta_data(Array, 90)
#1 /var/www/report/wp-includes/plugin.php(189): WP_Hook->apply_filters(Array, Array)
#2 /var/www/report/wp-includes/post.php(6366): apply_filters('wp_update_attac...', Array, 90)
#3 /var/www/report/wp-admin/includes/image.php(178): wp_update_attachment_metadata(90, Array)
#4 /var/www/report/wp-admin/includes/ajax-actions.php(2459): wp_update_image_subsizes(90)
#5 /var/www/report/wp-includes/class-wp-hook.php(303): wp_ajax_media_create_image_subsizes('')
#6 /var/www/report/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#7 /var/www/report/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#8 /var/www/report/wp-admin/ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-20 08:41:23 [error X 1][/var/www/report/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::656] Uncaught Error: Call to a member function attributes() on bool in /var/www/report/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php:656
Stack trace:
#0 /var/www/report/wp-includes/class-wp-hook.php(303): Elementor\Core\Files\Assets\Svg\Svg_Handler->set_svg_meta_data(Array, 91)
#1 /var/www/report/wp-includes/plugin.php(189): WP_Hook->apply_filters(Array, Array)
#2 /var/www/report/wp-includes/post.php(6366): apply_filters('wp_update_attac...', Array, 91)
#3 /var/www/report/wp-admin/includes/media.php(421): wp_update_attachment_metadata(91, Array)
#4 /var/www/report/wp-admin/async-upload.php(114): media_handle_upload('async-upload', 0)
#5 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-20 08:41:23 [error X 5][/var/www/report/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::656] Uncaught Error: Call to a member function attributes() on bool in /var/www/report/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php:656
Stack trace:
#0 /var/www/report/wp-includes/class-wp-hook.php(303): Elementor\Core\Files\Assets\Svg\Svg_Handler->set_svg_meta_data(Array, 91)
#1 /var/www/report/wp-includes/plugin.php(189): WP_Hook->apply_filters(Array, Array)
#2 /var/www/report/wp-includes/post.php(6366): apply_filters('wp_update_attac...', Array, 91)
#3 /var/www/report/wp-admin/includes/image.php(178): wp_update_attachment_metadata(91, Array)
#4 /var/www/report/wp-admin/includes/ajax-actions.php(2459): wp_update_image_subsizes(91)
#5 /var/www/report/wp-includes/class-wp-hook.php(303): wp_ajax_media_create_image_subsizes('')
#6 /var/www/report/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#7 /var/www/report/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#8 /var/www/report/wp-admin/ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-20 08:44:14 [error X 1][/var/www/report/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::656] Uncaught Error: Call to a member function attributes() on bool in /var/www/report/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php:656
Stack trace:
#0 /var/www/report/wp-includes/class-wp-hook.php(303): Elementor\Core\Files\Assets\Svg\Svg_Handler->set_svg_meta_data(Array, 93)
#1 /var/www/report/wp-includes/plugin.php(189): WP_Hook->apply_filters(Array, Array)
#2 /var/www/report/wp-includes/post.php(6366): apply_filters('wp_update_attac...', Array, 93)
#3 /var/www/report/wp-admin/includes/media.php(421): wp_update_attachment_metadata(93, Array)
#4 /var/www/report/wp-admin/async-upload.php(114): media_handle_upload('async-upload', 0)
#5 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-20 08:44:15 [error X 5][/var/www/report/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::656] Uncaught Error: Call to a member function attributes() on bool in /var/www/report/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php:656
Stack trace:
#0 /var/www/report/wp-includes/class-wp-hook.php(303): Elementor\Core\Files\Assets\Svg\Svg_Handler->set_svg_meta_data(Array, 93)
#1 /var/www/report/wp-includes/plugin.php(189): WP_Hook->apply_filters(Array, Array)
#2 /var/www/report/wp-includes/post.php(6366): apply_filters('wp_update_attac...', Array, 93)
#3 /var/www/report/wp-admin/includes/image.php(178): wp_update_attachment_metadata(93, Array)
#4 /var/www/report/wp-admin/includes/ajax-actions.php(2459): wp_update_image_subsizes(93)
#5 /var/www/report/wp-includes/class-wp-hook.php(303): wp_ajax_media_create_image_subsizes('')
#6 /var/www/report/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#7 /var/www/report/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#8 /var/www/report/wp-admin/ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-20 08:44:34 [error X 1][/var/www/report/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::656] Uncaught Error: Call to a member function attributes() on bool in /var/www/report/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php:656
Stack trace:
#0 /var/www/report/wp-includes/class-wp-hook.php(303): Elementor\Core\Files\Assets\Svg\Svg_Handler->set_svg_meta_data(Array, 94)
#1 /var/www/report/wp-includes/plugin.php(189): WP_Hook->apply_filters(Array, Array)
#2 /var/www/report/wp-includes/post.php(6366): apply_filters('wp_update_attac...', Array, 94)
#3 /var/www/report/wp-admin/includes/media.php(421): wp_update_attachment_metadata(94, Array)
#4 /var/www/report/wp-admin/includes/ajax-actions.php(2549): media_handle_upload('async-upload', '66', Array)
#5 /var/www/report/wp-admin/async-upload.php(33): wp_ajax_upload_attachment()
#6 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-20 08:44:35 [error X 5][/var/www/report/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::656] Uncaught Error: Call to a member function attributes() on bool in /var/www/report/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php:656
Stack trace:
#0 /var/www/report/wp-includes/class-wp-hook.php(303): Elementor\Core\Files\Assets\Svg\Svg_Handler->set_svg_meta_data(Array, 94)
#1 /var/www/report/wp-includes/plugin.php(189): WP_Hook->apply_filters(Array, Array)
#2 /var/www/report/wp-includes/post.php(6366): apply_filters('wp_update_attac...', Array, 94)
#3 /var/www/report/wp-admin/includes/image.php(178): wp_update_attachment_metadata(94, Array)
#4 /var/www/report/wp-admin/includes/ajax-actions.php(2459): wp_update_image_subsizes(94)
#5 /var/www/report/wp-includes/class-wp-hook.php(303): wp_ajax_media_create_image_subsizes('')
#6 /var/www/report/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#7 /var/www/report/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#8 /var/www/report/wp-admin/ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-20 08:45:09 [error X 1][/var/www/report/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::656] Uncaught Error: Call to a member function attributes() on bool in /var/www/report/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php:656
Stack trace:
#0 /var/www/report/wp-includes/class-wp-hook.php(303): Elementor\Core\Files\Assets\Svg\Svg_Handler->set_svg_meta_data(Array, 95)
#1 /var/www/report/wp-includes/plugin.php(189): WP_Hook->apply_filters(Array, Array)
#2 /var/www/report/wp-includes/post.php(6366): apply_filters('wp_update_attac...', Array, 95)
#3 /var/www/report/wp-admin/includes/media.php(421): wp_update_attachment_metadata(95, Array)
#4 /var/www/report/wp-admin/includes/ajax-actions.php(2549): media_handle_upload('async-upload', '66', Array)
#5 /var/www/report/wp-admin/async-upload.php(33): wp_ajax_upload_attachment()
#6 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-20 08:45:09 [error X 5][/var/www/report/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::656] Uncaught Error: Call to a member function attributes() on bool in /var/www/report/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php:656
Stack trace:
#0 /var/www/report/wp-includes/class-wp-hook.php(303): Elementor\Core\Files\Assets\Svg\Svg_Handler->set_svg_meta_data(Array, 95)
#1 /var/www/report/wp-includes/plugin.php(189): WP_Hook->apply_filters(Array, Array)
#2 /var/www/report/wp-includes/post.php(6366): apply_filters('wp_update_attac...', Array, 95)
#3 /var/www/report/wp-admin/includes/image.php(178): wp_update_attachment_metadata(95, Array)
#4 /var/www/report/wp-admin/includes/ajax-actions.php(2459): wp_update_image_subsizes(95)
#5 /var/www/report/wp-includes/class-wp-hook.php(303): wp_ajax_media_create_image_subsizes('')
#6 /var/www/report/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#7 /var/www/report/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#8 /var/www/report/wp-admin/ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-20 08:45:37 [error X 1][/var/www/report/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::656] Uncaught Error: Call to a member function attributes() on bool in /var/www/report/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php:656
Stack trace:
#0 /var/www/report/wp-includes/class-wp-hook.php(303): Elementor\Core\Files\Assets\Svg\Svg_Handler->set_svg_meta_data(Array, 96)
#1 /var/www/report/wp-includes/plugin.php(189): WP_Hook->apply_filters(Array, Array)
#2 /var/www/report/wp-includes/post.php(6366): apply_filters('wp_update_attac...', Array, 96)
#3 /var/www/report/wp-admin/includes/media.php(421): wp_update_attachment_metadata(96, Array)
#4 /var/www/report/wp-admin/includes/ajax-actions.php(2549): media_handle_upload('async-upload', '66', Array)
#5 /var/www/report/wp-admin/async-upload.php(33): wp_ajax_upload_attachment()
#6 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-20 08:45:38 [error X 5][/var/www/report/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::656] Uncaught Error: Call to a member function attributes() on bool in /var/www/report/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php:656
Stack trace:
#0 /var/www/report/wp-includes/class-wp-hook.php(303): Elementor\Core\Files\Assets\Svg\Svg_Handler->set_svg_meta_data(Array, 96)
#1 /var/www/report/wp-includes/plugin.php(189): WP_Hook->apply_filters(Array, Array)
#2 /var/www/report/wp-includes/post.php(6366): apply_filters('wp_update_attac...', Array, 96)
#3 /var/www/report/wp-admin/includes/image.php(178): wp_update_attachment_metadata(96, Array)
#4 /var/www/report/wp-admin/includes/ajax-actions.php(2459): wp_update_image_subsizes(96)
#5 /var/www/report/wp-includes/class-wp-hook.php(303): wp_ajax_media_create_image_subsizes('')
#6 /var/www/report/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#7 /var/www/report/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#8 /var/www/report/wp-admin/ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-20 08:58:46 [error X 1][/var/www/report/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::656] Uncaught Error: Call to a member function attributes() on bool in /var/www/report/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php:656
Stack trace:
#0 /var/www/report/wp-includes/class-wp-hook.php(303): Elementor\Core\Files\Assets\Svg\Svg_Handler->set_svg_meta_data(Array, 102)
#1 /var/www/report/wp-includes/plugin.php(189): WP_Hook->apply_filters(Array, Array)
#2 /var/www/report/wp-includes/post.php(6366): apply_filters('wp_update_attac...', Array, 102)
#3 /var/www/report/wp-admin/includes/media.php(421): wp_update_attachment_metadata(102, Array)
#4 /var/www/report/wp-admin/async-upload.php(114): media_handle_upload('async-upload', 0)
#5 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-20 08:58:47 [error X 5][/var/www/report/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::656] Uncaught Error: Call to a member function attributes() on bool in /var/www/report/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php:656
Stack trace:
#0 /var/www/report/wp-includes/class-wp-hook.php(303): Elementor\Core\Files\Assets\Svg\Svg_Handler->set_svg_meta_data(Array, 102)
#1 /var/www/report/wp-includes/plugin.php(189): WP_Hook->apply_filters(Array, Array)
#2 /var/www/report/wp-includes/post.php(6366): apply_filters('wp_update_attac...', Array, 102)
#3 /var/www/report/wp-admin/includes/image.php(178): wp_update_attachment_metadata(102, Array)
#4 /var/www/report/wp-admin/includes/ajax-actions.php(2459): wp_update_image_subsizes(102)
#5 /var/www/report/wp-includes/class-wp-hook.php(303): wp_ajax_media_create_image_subsizes('')
#6 /var/www/report/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#7 /var/www/report/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#8 /var/www/report/wp-ad [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-20 09:04:16 [error X 1][/var/www/report/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::656] Uncaught Error: Call to a member function attributes() on bool in /var/www/report/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php:656
Stack trace:
#0 /var/www/report/wp-includes/class-wp-hook.php(303): Elementor\Core\Files\Assets\Svg\Svg_Handler->set_svg_meta_data(Array, 103)
#1 /var/www/report/wp-includes/plugin.php(189): WP_Hook->apply_filters(Array, Array)
#2 /var/www/report/wp-includes/post.php(6366): apply_filters('wp_update_attac...', Array, 103)
#3 /var/www/report/wp-admin/includes/media.php(421): wp_update_attachment_metadata(103, Array)
#4 /var/www/report/wp-admin/async-upload.php(114): media_handle_upload('async-upload', 0)
#5 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-20 09:04:17 [error X 5][/var/www/report/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::656] Uncaught Error: Call to a member function attributes() on bool in /var/www/report/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php:656
Stack trace:
#0 /var/www/report/wp-includes/class-wp-hook.php(303): Elementor\Core\Files\Assets\Svg\Svg_Handler->set_svg_meta_data(Array, 103)
#1 /var/www/report/wp-includes/plugin.php(189): WP_Hook->apply_filters(Array, Array)
#2 /var/www/report/wp-includes/post.php(6366): apply_filters('wp_update_attac...', Array, 103)
#3 /var/www/report/wp-admin/includes/image.php(178): wp_update_attachment_metadata(103, Array)
#4 /var/www/report/wp-admin/includes/ajax-actions.php(2459): wp_update_image_subsizes(103)
#5 /var/www/report/wp-includes/class-wp-hook.php(303): wp_ajax_media_create_image_subsizes('')
#6 /var/www/report/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#7 /var/www/report/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#8 /var/www/report/wp-ad [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-20 10:29:24 [error X 1][/var/www/report/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::656] Uncaught Error: Call to a member function attributes() on bool in /var/www/report/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php:656
Stack trace:
#0 /var/www/report/wp-includes/class-wp-hook.php(303): Elementor\Core\Files\Assets\Svg\Svg_Handler->set_svg_meta_data(Array, 105)
#1 /var/www/report/wp-includes/plugin.php(189): WP_Hook->apply_filters(Array, Array)
#2 /var/www/report/wp-includes/post.php(6366): apply_filters('wp_update_attac...', Array, 105)
#3 /var/www/report/wp-admin/includes/media.php(421): wp_update_attachment_metadata(105, Array)
#4 /var/www/report/wp-admin/async-upload.php(114): media_handle_upload('async-upload', 0)
#5 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-20 10:29:24 [error X 5][/var/www/report/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::656] Uncaught Error: Call to a member function attributes() on bool in /var/www/report/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php:656
Stack trace:
#0 /var/www/report/wp-includes/class-wp-hook.php(303): Elementor\Core\Files\Assets\Svg\Svg_Handler->set_svg_meta_data(Array, 105)
#1 /var/www/report/wp-includes/plugin.php(189): WP_Hook->apply_filters(Array, Array)
#2 /var/www/report/wp-includes/post.php(6366): apply_filters('wp_update_attac...', Array, 105)
#3 /var/www/report/wp-admin/includes/image.php(178): wp_update_attachment_metadata(105, Array)
#4 /var/www/report/wp-admin/includes/ajax-actions.php(2459): wp_update_image_subsizes(105)
#5 /var/www/report/wp-includes/class-wp-hook.php(303): wp_ajax_media_create_image_subsizes('')
#6 /var/www/report/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#7 /var/www/report/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#8 /var/www/report/wp-ad [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]


				
```
</details>

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
