### ISSUE TITLE
Elementor Bug when using WooCommerce Blocks

### ISSUE THREAD

**Issue by geofry93** [elementor/elementor#16187]
After lots of testing and disabling of plugins and themes, I've discovered that the cause of the error is an incompatibility with elementor and WooCommerce Blocks. I'm using WooCommerce Blocks to display my checkout page and the issue is that after submitting a purchase, I do not get redirected to the order confirmation page. Here is what the error message looks like:

Fatal error: Uncaught Error: Call to undefined method WP_Error::get_data() in /home/customer/www/staging4.harrym7.sg-host.com/public_html/wp-content/plugins/woo-gutenberg-products-block/src/RestApi.php:64 Stack trace: #0 /home/customer/www/staging4.harrym7.sg-host.com/public_html/wp-content/plugins/woo-gutenberg-products-block/src/BlockTypes/AbstractBlock.php(349): Automattic\WooCommerce\Blocks\RestApi->get_routes_from_namespace('wc/store') #1 /home/customer/www/staging4.harrym7.sg-host.com/public_html/wp-content/plugins/woo-gutenberg-products-block/src/BlockTypes/Checkout.php(99): Automattic\WooCommerce\Blocks\BlockTypes\AbstractBlock->enqueue_data(Array) #2 /home/customer/www/staging4.harrym7.sg-host.com/public_html/wp-content/plugins/woo-gutenberg-products-block/src/BlockTypes/AbstractBlock.php(287): Automattic\WooCommerce\Blocks\BlockTypes\Checkout->enqueue_data(Array) #3 /home/customer/www/staging4.harrym7.sg-host.com/public_html/wp-content/plugins/woo-gutenberg-products-block/src/BlockTypes/Checkout.php(55): Automat in /home/customer/www/staging4.harrym7.sg-host.com/public_html/wp-content/plugins/woo-gutenberg-products-block/src/RestApi.php on line 64
There has been a critical error on this website.

Here's what happens when I complete an order with Elementor enabled (no order summary shows)

![Screen Shot 2021-08-28 at 9 12 26 PM](https://user-images.githubusercontent.com/16586950/131238164-752523f5-f6ef-435d-a72b-de9db9a727d0.PNG)

Here is what happens when I disable Elementor (order summary shows!)

![Screen Shot 2021-08-28 at 9 12 55 PM](https://user-images.githubusercontent.com/16586950/131238173-50174303-1c30-4bad-b9b4-3d69b198736d.PNG)

Thanks!

**Comment by avivu** [comment]
Hello @geofry93,
Thanks for reporting.
We tried to reproduce the issue, but with no success.
Can you please try again:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one until you spot the problematic plugin.
 - Change your WordPress theme to [Hello Theme](https://wordpress.org/themes/hello-elementor/) (or other default WordPress theme).

And see if the issue persists.

If the issue still occurred, please follow the guidelines, so we can help you better.
This report is missing key information: 

* Prerequisites
* Steps to replicate
* Isolating the problem
* System info


Thanks.
