### ISSUE TITLE
Fatal crash after updates

### ISSUE THREAD

**Issue by babstudio** [elementor/elementor#16202]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [ x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x ] This bug happens with a default WordPress theme active.
- [ x] I can reproduce this bug consistently using the steps above.

/ wp-content / plugins / elementor-pro / modules / forms / classes / integration-base.php

## Environment

<details>
<summary>System Info</summary>
```
										
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.3.31
	PHP Version: 7.3.29
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.8
	Site URL: https://testing7.gmfinance.co.il
	Home URL: https://testing7.gmfinance.co.il
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 300M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: he-IL
	Timezone: 2
	Debug Mode: Inactive

== Theme ==
	Name: GeneratePress
	Version: 3.0.2
	Author: Tom Usborne
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: he_IL
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36

== Active Plugins ==
	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Code Snippets
		Version: 2.14.1
		Author: Code Snippets Pro

	Contact Form 7
		Version: 5.1.6
		Author: Takayuki Miyoshi

	Contact Form 7 - Dynamic Text Extension
		Version: 2.0.3
		Author: Chris Mavricos, SevenSpark

	Contact Form 7 Conditional Fields
		Version: 1.7.8
		Author: Jules Colle

	Contact Form 7 digital signature add-ons
		Version: 1.5.7.5
		Author: Approve Me

	Contact Form 7 Signature Addon
		Version: 4.2.2
		Author: Breizhtorm

	Contact Form CFDB7
		Version: 1.2.5.9
		Author: Arshid

	Easy Updates Manager
		Version: 9.0.9
		Author: Easy Updates Manager Team

	Elementor
		Version: 3.4.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.3.8
		Author: Elementor.com

	Form Fields Filler
		Version: 1.0.1
		Author: I. K. Soft

	GP Premium
		Version: 1.12.3
		Author: Tom Usborne

	JetElements For Elementor
		Version: 2.5.2
		Author: Crocoblock

	Lenix Elementor Leads addon
		Version: 1.8.1
		Author: Lenix

	Loco Translate
		Version: 2.5.3
		Author: Tim Whitlock

	One Click Accessibility
		Version: 2.0.3
		Author: One Click Accessibility

	PDF Forms Filler for Contact Form 7
		Version: 1.2.1
		Author: Maximum.Software

	PDF Forms Filler for Contact Form 7 Enterprise Extension
		Version: 1.2.0
		Author: Maximum.Software

	Shortcode For Current Date
		Version: 2.1.5
		Author: Imtiaz Rayhan

	UpdraftPlus - Backup/Restore
		Version: 2.16.60.1
		Author: UpdraftPlus.Com, DavidAnderson

	Void Contact Form 7 Widget For Elementor Page Builder
		Version: 1.1.7
		Author: voidCoders

	WP E-Signature
		Version: 1.6.1
		Author: Approve Me

	WP E-Signature - RTL
		Version: 1.5.7.1
		Author: Approve Me

	WP E-Signature Business add-ons
		Version: 1.6.1
		Author: Approve Me

	WP File Manager
		Version: 7.1.2
		Author: mndpsingh287

	WP Mail SMTP
		Version: 3.0.3
		Author: WPForms

	WPS Hide Login
		Version: 1.8.6
		Author: WPServeur, NicolasKulka, wpformation

	WPS Limit Login
		Version: 1.5.4
		Author: WPServeur, NicolasKulka, wpformation

	Yoast SEO
		Version: 17.0
		Author: Team Yoast


== אלמנטור - Compatibility Tag ==
	
	Elementor Pro: תאימות לא הוגדרה
	JetElements For Elementor: תאימות לא הוגדרה
	Lenix Elementor Leads addon: תאימות לא הוגדרה
	Void Contact Form 7 Widget For Elementor Page Builder: תאימות לא הוגדרה

== אלמנטור פרו - Compatibility Tag ==
	


== Elements Usage ==
	
	footer : 1
		button : 2
		form : 1
		heading : 7
		icon-list : 3
		social-icons : 1
	header : 1
		button : 1
		image : 1
		nav-menu : 1
	popup : 2
		button : 3
		heading : 2
		image : 2
		text-editor : 1
	section : 3
		form : 1
		heading : 3
		media-carousel : 1
		signature-widget : 1
	wp-page : 11
		button : 4
		divider : 4
		form : 2
		heading : 26
		icon : 1
		image : 7
		jet-horizontal-timeline : 4
		jet-timeline : 1
		media-carousel : 1
		shortcode : 1
		social-icons : 1
		text-editor : 5
		toggle : 1


== Log ==
	
Log: showing 20 of 372020-11-16 08:54:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '3.0.5',
  'to' => '3.0.6',
)]
2020-11-16 08:54:24 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור',
  'from' => '3.0.11',
  'to' => '3.0.13',
)]
2020-12-13 21:46:47 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור',
  'from' => '3.0.13',
  'to' => '3.0.14',
)]
2020-12-13 21:46:50 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '3.0.6',
  'to' => '3.0.8',
)]
2021-06-06 00:51:56 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'אלמנטור',
  'from' => '3.0.14',
  'to' => '3.2.4',
)]
2021-06-06 00:51:56 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '3.0.8',
  'to' => '3.2.2',
)]
2021-08-30 22:03:48 [info] elementor::elementor_updater Started 
2021-08-30 22:03:48 [info] אלמנטור/Upgrades - _v_3_2_0_migrate_breakpoints_to_new_system Start  
2021-08-30 22:03:48 [info] אלמנטור/Upgrades - _v_3_2_0_migrate_breakpoints_to_new_system Finished 
2021-08-30 22:03:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור',
  'from' => '3.0.14',
  'to' => '3.4.3',
)]
2021-08-30 22:03:50 [info] elementor-pro::elementor_pro_updater Started 
2021-08-30 22:03:50 [info] אלמנטור פרו/Upgrades - _v_3_1_0_media_carousel Start  
2021-08-30 22:03:50 [info] אלמנטור פרו/Upgrades - _v_3_1_0_media_carousel Finished 
2021-08-30 22:03:50 [info] אלמנטור פרו/Upgrades - _v_3_1_0_reviews Start  
2021-08-30 22:03:50 [info] אלמנטור פרו/Upgrades - _v_3_1_0_reviews Finished 
2021-08-30 22:03:50 [info] אלמנטור פרו/Upgrades - _v_3_1_0_testimonial_carousel Start  
2021-08-30 22:03:50 [info] אלמנטור פרו/Upgrades - _v_3_1_0_testimonial_carousel Finished 
2021-08-30 22:03:50 [info] אלמנטור פרו/Upgrades - _v_3_1_0_slides Start  
2021-08-30 22:03:51 [info] אלמנטור פרו/Upgrades - _v_3_1_0_slides Finished 
2021-08-30 22:03:51 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '3.0.8',
  'to' => '3.4.0',
)]

JS: showing 2 of 2JS: 2020-01-26 19:46:40 [error X 1][https://testing7.gmfinance.co.il/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=2.8.4:2:40610] Cannot read property \'cid\' of undefined 
JS: 2020-01-26 19:46:53 [error X 2][https://testing7.gmfinance.co.il/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=2.8.4:2:40565] Cannot read property \'findByModelCid\' of undefined 

PHP: showing 3 of 3PHP: 2020-10-11 19:32:37 [notice X 1][/home/gmfinanceco/testing7.gmfinance.co.il/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-30 22:04:00 [error X 11][/home/gmfinanceco/testing7.gmfinance.co.il/wp-content/plugins/elementor-pro/modules/forms/classes/integration-base.php::47] Uncaught TypeError: Argument 1 passed to ElementorPro\Modules\Forms\Classes\Integration_Base::register_fields_map_control() must be an instance of ElementorPro\Modules\Forms\Widgets\Form, instance of ElementorPro\Modules\Forms\Widgets\SForm given, called in /home/gmfinanceco/testing7.gmfinance.co.il/wp-content/plugins/elementor-pro/modules/forms/actions/mailchimp.php on line 148 and defined in /home/gmfinanceco/testing7.gmfinance.co.il/wp-content/plugins/elementor-pro/modules/forms/classes/integration-base.php:47
Stack trace:
#0 /home/gmfinanceco/testing7.gmfinance.co.il/wp-content/plugins/elementor-pro/modules/forms/actions/mailchimp.php(148): ElementorPro\Modules\Forms\Classes\Integration_Base->register_fields_map_control(Object(ElementorPro\Modules\Forms\Widgets\SForm))
#1 /home/gmfinanceco/testing7.gmfinance.co.il/wp-content/plugins/signature-widget-elementor/widgets/form.php(733): ElementorPro\Modules\Forms\Actions\Mailchimp->register_settings_section(Object(ElementorPro\Modules\Forms\Widgets\SForm))
#2  [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-30 22:20:54 [error X 4][/home/gmfinanceco/testing7.gmfinance.co.il/wp-content/plugins/elementor-pro/modules/forms/classes/integration-base.php::47] Uncaught TypeError: Argument 1 passed to ElementorPro\Modules\Forms\Classes\Integration_Base::register_fields_map_control() must be an instance of ElementorPro\Modules\Forms\Widgets\Form, instance of ElementorPro\Modules\Forms\Widgets\SForm given, called in /home/gmfinanceco/testing7.gmfinance.co.il/wp-content/plugins/elementor-pro/modules/forms/actions/mailchimp.php on line 143 and defined in /home/gmfinanceco/testing7.gmfinance.co.il/wp-content/plugins/elementor-pro/modules/forms/classes/integration-base.php:47
Stack trace:
#0 /home/gmfinanceco/testing7.gmfinance.co.il/wp-content/plugins/elementor-pro/modules/forms/actions/mailchimp.php(143): ElementorPro\Modules\Forms\Classes\Integration_Base->register_fields_map_control(Object(ElementorPro\Modules\Forms\Widgets\SForm))
#1 /home/gmfinanceco/testing7.gmfinance.co.il/wp-content/plugins/signature-widget-elementor/widgets/form.php(733): ElementorPro\Modules\Forms\Actions\Mailchimp->register_settings_section(Object(ElementorPro\Modules\Forms\Widgets\SForm))
#2  [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]


				
',
)]


				
```
</details>

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it, we simply can't help.

Thanks.
