### ISSUE TITLE
Post Info Widget - PHP errors with deleted custom taxonomy

### ISSUE THREAD

**Issue by euene** [elementor/elementor#16235]
## Steps to reproduce

1. Create a new custom taxonomy (manually with PHP or via CPT UI plug-in).
2. Add a Post Info widget using Elementor editor and add an item with Type "Terms" and select the custom taxonomy.
3. Remove the custom taxonomy so that it no longer exists.
4. The Elementor template is now broken with errors on the front-end and also on the back-end making it completely uneditable (unless the custom taxonomy is re-created again).

```
Warning: Attempt to read property "name" on array in wp-content/plugins/elementor-pro/modules/theme-elements/widgets/post-info.php on line 826

Warning: Attempt to read property "term_id" on array in wp-content/plugins/elementor-pro/modules/theme-elements/widgets/post-info.php on line 828

Fatal error: Uncaught Error: Object of class WP_Error could not be converted to string in wp-includes/formatting.php:1098 Stack trace: #0 wp-includes/formatting.php(4504): wp_check_invalid_utf8(Object(WP_Error)) #1 wp-content/plugins/elementor-pro/modules/theme-elements/widgets/post-info.php(975): esc_attr(Object(WP_Error)) #2 wp-content/plugins/elementor-pro/modules/theme-elements/widgets/post-info.php(898): ElementorPro\Modules\ThemeElements\Widgets\Post_Info->render_item_text(Array, 'f01c3bc') #3 wp-content/plugins/elementor-pro/modules/theme-elements/widgets/post-info.php(1005): ElementorPro\Modules\ThemeElements\Widgets\Post_Info->render_item(Array) #4 wp-content/plugins/elementor/includes/base/controls-stack.php(2144): ElementorPro\Modules\ThemeElements\Widgets\Post_Info->render() #5 wp-content/plugins/elementor/includes/base/widget-base.php(581): Elementor\Controls_Stack->render_by_mode() #6 wp-content/plugins/elementor/includes/base/widget-base.php(722): Elementor\Widget_Base->render_content() #7 wp-content/plugins/elementor/includes/base/element-base.php(450): Elementor\Widget_Base->print_content() #8 wp-content/plugins/elementor/includes/base/element-base.php(744): Elementor\Element_Base->print_element() #9 wp-content/plugins/elementor/includes/base/element-base.php(450): Elementor\Element_Base->print_content() #10 wp-content/plugins/elementor/includes/base/element-base.php(744): Elementor\Element_Base->print_element() #11 wp-content/plugins/elementor/includes/base/element-base.php(450): Elementor\Element_Base->print_content() #12 wp-content/plugins/elementor/core/base/document.php(1509): Elementor\Element_Base->print_element() #13 wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(437): Elementor\Core\Base\Document->print_elements(Array) #14 wp-content/plugins/elementor/includes/frontend.php(1038): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document->print_elements_with_wrapper(Array) #15 wp-content/plugins/elementor-pro/modules/posts/skins/skin-content-base.php(253): Elementor\Frontend->get_builder_content(75, true) #16 wp-content/plugins/elementor-pro/modules/theme-builder/widgets/post-content.php(110): ElementorPro\Modules\ThemeBuilder\Widgets\Post_Content->render_post_content() #17 wp-content/plugins/elementor/includes/base/controls-stack.php(2144): ElementorPro\Modules\ThemeBuilder\Widgets\Post_Content->render() #18 wp-content/plugins/elementor/includes/base/widget-base.php(581): Elementor\Controls_Stack->render_by_mode() #19 wp-content/plugins/elementor/includes/base/widget-base.php(705): Elementor\Widget_Base->render_content() #20 wp-content/plugins/elementor/includes/base/element-base.php(537): Elementor\Widget_Base->get_raw_data(true) #21 wp-content/plugins/elementor/includes/base/element-base.php(537): Elementor\Element_Base->get_raw_data(true) #22 wp-content/plugins/elementor/core/base/document.php(856): Elementor\Element_Base->get_raw_data(true) #23 wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(461): Elementor\Core\Base\Document->get_elements_raw_data(Array, true) #24 wp-content/plugins/elementor/core/base/document.php(540): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document->get_elements_raw_data(NULL, true) #25 wp-content/plugins/elementor/modules/library/documents/library-document.php(65): Elementor\Core\Base\Document->get_initial_config() #26 wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(685): Elementor\Modules\Library\Documents\Library_Document->get_initial_config() #27 wp-content/plugins/elementor/includes/base/controls-stack.php(987): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document->get_initial_config() #28 wp-content/plugins/elementor/core/editor/editor.php(528): Elementor\Controls_Stack->get_config() #29 wp-includes/class-wp-hook.php(303): Elementor\Core\Editor\Editor->enqueue_scripts('') #30 wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array) #31 wp-includes/plugin.php(470): WP_Hook->do_action(Array) #32 wp-includes/script-loader.php(2083): do_action('wp_enqueue_scri...') #33 wp-includes/class-wp-hook.php(303): wp_enqueue_scripts('') #34 wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array) #35 wp-includes/plugin.php(470): WP_Hook->do_action(Array) #36 wp-includes/general-template.php(3015): do_action('wp_head') #37 wp-content/plugins/elementor/includes/editor-templates/editor-wrapper.php(31): wp_head() #38 wp-content/plugins/elementor/core/editor/editor.php(323): include('...') #39 wp-content/plugins/elementor/core/editor/editor.php(164): Elementor\Core\Editor\Editor->print_editor_template() #40 wp-includes/class-wp-hook.php(303): Elementor\Core\Editor\Editor->init('') #41 wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array) #42 wp-includes/plugin.php(470): WP_Hook->do_action(Array) #43 wp-admin/admin.php(408): do_action('admin_action_el...') #44 wp-admin/post.php(12): require_once('...') #45 {main} thrown in wp-includes/formatting.php on line 1098
```

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

WordPress 5.8

Only plug-ins active:
Elementor 3.4.3
Elementor Pro 3.4.0

Active theme:
Hello Elementor 2.4.1

Server:
PHP 8.0.9
Apache/2.4.48
MariaDB 10.6.4

**Comment by euene** [comment]
@shilo-ey Can this be looked at? Thanks.
