### ISSUE TITLE
Share Buttons on Mobile

### ISSUE THREAD

**Issue by maurocarreraok** [elementor/elementor#16323]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.20.1
	MySQL version: MariaDB Server v10.6.4
	PHP Version: 7.3.29
	PHP Max Input Vars: 3000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.8.1
	Site URL: https://Pvt.Pvt.com
	Home URL: https://Pvt.Pvt.com
	WP Multisite: No
	Max Upload Size: 8 MB
	Memory limit: 2048M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/New_York
	Debug Mode: Inactive

== Theme ==
	Name: Pvt Theme
	Version: 2.0.0
	Author: Pvt
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.4.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36

== Active Plugins ==
	Autoptimize
		Version: 2.9.2
		Author: Frank Goossens (futtta)

	Compress JPEG & PNG images
		Version: 3.2.1
		Author: TinyPNG

	Elementor
		Version: 3.4.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.4.1
		Author: Elementor.com

	JetElements For Elementor
		Version: 2.5.9
		Author: Crocoblock

	JetEngine
		Version: 2.9.2
		Author: Crocoblock

	Polylang
		Version: 3.1.1
		Author: WP SYNTEX

	Polylang Connect for Elementor
		Version: 1.0.6
		Author: David Decker - DECKERWEB

	WPSHAPERE
		Version: 6.1.13
		Author: AcmeeDesign Softwares and Solutions

	Yoast SEO
		Version: 17.1
		Author: Team Yoast


== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	JetElements For Elementor: Compatibility not specified
	Polylang Connect for Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==
	


== Elements Usage ==
	
	footer : 2
		form : 2
		heading : 24
		image : 2
	header : 2
		button : 2
		html : 2
		image : 2
		nav-menu : 4
		theme-site-logo : 2
		wp-widget-polylang : 2
	popup : 6
		button : 2
		form : 2
		heading : 5
		image : 1
		share-buttons : 1
		text-editor : 1
		video : 1
	wp-post : 0
		button : 2
		counter : 10
		divider : 8
		heading : 114
		icon : 18
		icon-list : 30
		image : 123
		image-box : 14
		jet-headline : 13
		jet-listing-grid : 2
		spacer : 6
		text-editor : 78
	jet-listing-items : 0
		flip-box : 2


== Log ==
	
Log: showing 14 of 142021-08-20 07:55:11 [info] elementor::elementor_updater Started 
2021-08-20 07:55:11 [info] Elementor/Upgrades - _on_each_version Start  
2021-08-20 07:55:11 [info] Elementor/Upgrades - _on_each_version Finished 
2021-08-20 07:55:11 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.3.1',
  'to' => '3.4.2',
)]
2021-08-20 07:55:11 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.3.1',
  'to' => '3.4.2',
)]
2021-08-20 08:11:04 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.3.1',
  'to' => '3.3.7',
)]
2021-08-24 09:30:56 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.3.7',
  'to' => '3.3.8',
)]
2021-08-30 09:17:00 [info] elementor::elementor_updater Started 
2021-08-30 09:17:00 [info] Elementor/Upgrades - _on_each_version Start  
2021-08-30 09:17:00 [info] Elementor/Upgrades - _on_each_version Finished 
2021-08-30 09:17:00 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.2',
  'to' => '3.4.3',
)]
2021-08-30 09:17:00 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.2',
  'to' => '3.4.3',
)]
2021-08-31 20:07:56 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.3.8',
  'to' => '3.4.0',
)]
2021-09-02 07:30:28 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.4.0',
  'to' => '3.4.1',
)]

PHP: showing 20 of 26PHP: 2021-08-20 08:40:48 [error X 1][/var/www/prv/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::656] Uncaught Error: Call to a member function attributes() on bool in /var/www/prv/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php:656
Stack trace:
#0 /var/www/prv/wp-includes/class-wp-hook.php(303): Elementor\Core\Files\Assets\Svg\Svg_Handler->set_svg_meta_data(Array, 90)
#1 /var/www/prv/wp-includes/plugin.php(189): WP_Hook->apply_filters(Array, Array)
#2 /var/www/prv/wp-includes/post.php(6366): apply_filters('wp_update_attac...', Array, 90)
#3 /var/www/prv/wp-admin/includes/media.php(421): wp_update_attachment_metadata(90, Array)
#4 /var/www/prv/wp-admin/includes/ajax-actions.php(2549): media_handle_upload('async-upload', '66', Array)
#5 /var/www/prv/wp-admin/async-upload.php(33): wp_ajax_upload_attachment()
#6 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-20 08:40:48 [error X 5][/var/www/prv/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::656] Uncaught Error: Call to a member function attributes() on bool in /var/www/prv/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php:656
Stack trace:
#0 /var/www/prv/wp-includes/class-wp-hook.php(303): Elementor\Core\Files\Assets\Svg\Svg_Handler->set_svg_meta_data(Array, 90)
#1 /var/www/prv/wp-includes/plugin.php(189): WP_Hook->apply_filters(Array, Array)
#2 /var/www/prv/wp-includes/post.php(6366): apply_filters('wp_update_attac...', Array, 90)
#3 /var/www/prv/wp-admin/includes/image.php(178): wp_update_attachment_metadata(90, Array)
#4 /var/www/prv/wp-admin/includes/ajax-actions.php(2459): wp_update_image_subsizes(90)
#5 /var/www/prv/wp-includes/class-wp-hook.php(303): wp_ajax_media_create_image_subsizes('')
#6 /var/www/prv/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#7 /var/www/prv/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#8 /var/www/prv/wp-admin/ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-20 08:41:23 [error X 1][/var/www/prv/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::656] Uncaught Error: Call to a member function attributes() on bool in /var/www/prv/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php:656
Stack trace:
#0 /var/www/prv/wp-includes/class-wp-hook.php(303): Elementor\Core\Files\Assets\Svg\Svg_Handler->set_svg_meta_data(Array, 91)
#1 /var/www/prv/wp-includes/plugin.php(189): WP_Hook->apply_filters(Array, Array)
#2 /var/www/prv/wp-includes/post.php(6366): apply_filters('wp_update_attac...', Array, 91)
#3 /var/www/prv/wp-admin/includes/media.php(421): wp_update_attachment_metadata(91, Array)
#4 /var/www/prv/wp-admin/async-upload.php(114): media_handle_upload('async-upload', 0)
#5 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-20 08:41:23 [error X 5][/var/www/prv/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::656] Uncaught Error: Call to a member function attributes() on bool in /var/www/prv/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php:656
Stack trace:
#0 /var/www/prv/wp-includes/class-wp-hook.php(303): Elementor\Core\Files\Assets\Svg\Svg_Handler->set_svg_meta_data(Array, 91)
#1 /var/www/prv/wp-includes/plugin.php(189): WP_Hook->apply_filters(Array, Array)
#2 /var/www/prv/wp-includes/post.php(6366): apply_filters('wp_update_attac...', Array, 91)
#3 /var/www/prv/wp-admin/includes/image.php(178): wp_update_attachment_metadata(91, Array)
#4 /var/www/prv/wp-admin/includes/ajax-actions.php(2459): wp_update_image_subsizes(91)
#5 /var/www/prv/wp-includes/class-wp-hook.php(303): wp_ajax_media_create_image_subsizes('')
#6 /var/www/prv/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#7 /var/www/prv/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#8 /var/www/prv/wp-admin/ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-20 08:44:14 [error X 1][/var/www/prv/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::656] Uncaught Error: Call to a member function attributes() on bool in /var/www/prv/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php:656
Stack trace:
#0 /var/www/prv/wp-includes/class-wp-hook.php(303): Elementor\Core\Files\Assets\Svg\Svg_Handler->set_svg_meta_data(Array, 93)
#1 /var/www/prv/wp-includes/plugin.php(189): WP_Hook->apply_filters(Array, Array)
#2 /var/www/prv/wp-includes/post.php(6366): apply_filters('wp_update_attac...', Array, 93)
#3 /var/www/prv/wp-admin/includes/media.php(421): wp_update_attachment_metadata(93, Array)
#4 /var/www/prv/wp-admin/async-upload.php(114): media_handle_upload('async-upload', 0)
#5 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-20 08:44:15 [error X 5][/var/www/prv/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::656] Uncaught Error: Call to a member function attributes() on bool in /var/www/prv/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php:656
Stack trace:
#0 /var/www/prv/wp-includes/class-wp-hook.php(303): Elementor\Core\Files\Assets\Svg\Svg_Handler->set_svg_meta_data(Array, 93)
#1 /var/www/prv/wp-includes/plugin.php(189): WP_Hook->apply_filters(Array, Array)
#2 /var/www/prv/wp-includes/post.php(6366): apply_filters('wp_update_attac...', Array, 93)
#3 /var/www/prv/wp-admin/includes/image.php(178): wp_update_attachment_metadata(93, Array)
#4 /var/www/prv/wp-admin/includes/ajax-actions.php(2459): wp_update_image_subsizes(93)
#5 /var/www/prv/wp-includes/class-wp-hook.php(303): wp_ajax_media_create_image_subsizes('')
#6 /var/www/prv/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#7 /var/www/prv/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#8 /var/www/prv/wp-admin/ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-20 08:44:34 [error X 1][/var/www/prv/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::656] Uncaught Error: Call to a member function attributes() on bool in /var/www/prv/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php:656
Stack trace:
#0 /var/www/prv/wp-includes/class-wp-hook.php(303): Elementor\Core\Files\Assets\Svg\Svg_Handler->set_svg_meta_data(Array, 94)
#1 /var/www/prv/wp-includes/plugin.php(189): WP_Hook->apply_filters(Array, Array)
#2 /var/www/prv/wp-includes/post.php(6366): apply_filters('wp_update_attac...', Array, 94)
#3 /var/www/prv/wp-admin/includes/media.php(421): wp_update_attachment_metadata(94, Array)
#4 /var/www/prv/wp-admin/includes/ajax-actions.php(2549): media_handle_upload('async-upload', '66', Array)
#5 /var/www/prv/wp-admin/async-upload.php(33): wp_ajax_upload_attachment()
#6 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-20 08:44:35 [error X 5][/var/www/prv/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::656] Uncaught Error: Call to a member function attributes() on bool in /var/www/prv/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php:656
Stack trace:
#0 /var/www/prv/wp-includes/class-wp-hook.php(303): Elementor\Core\Files\Assets\Svg\Svg_Handler->set_svg_meta_data(Array, 94)
#1 /var/www/prv/wp-includes/plugin.php(189): WP_Hook->apply_filters(Array, Array)
#2 /var/www/prv/wp-includes/post.php(6366): apply_filters('wp_update_attac...', Array, 94)
#3 /var/www/prv/wp-admin/includes/image.php(178): wp_update_attachment_metadata(94, Array)
#4 /var/www/prv/wp-admin/includes/ajax-actions.php(2459): wp_update_image_subsizes(94)
#5 /var/www/prv/wp-includes/class-wp-hook.php(303): wp_ajax_media_create_image_subsizes('')
#6 /var/www/prv/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#7 /var/www/prv/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#8 /var/www/prv/wp-admin/ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-20 08:45:09 [error X 1][/var/www/prv/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::656] Uncaught Error: Call to a member function attributes() on bool in /var/www/prv/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php:656
Stack trace:
#0 /var/www/prv/wp-includes/class-wp-hook.php(303): Elementor\Core\Files\Assets\Svg\Svg_Handler->set_svg_meta_data(Array, 95)
#1 /var/www/prv/wp-includes/plugin.php(189): WP_Hook->apply_filters(Array, Array)
#2 /var/www/prv/wp-includes/post.php(6366): apply_filters('wp_update_attac...', Array, 95)
#3 /var/www/prv/wp-admin/includes/media.php(421): wp_update_attachment_metadata(95, Array)
#4 /var/www/prv/wp-admin/includes/ajax-actions.php(2549): media_handle_upload('async-upload', '66', Array)
#5 /var/www/prv/wp-admin/async-upload.php(33): wp_ajax_upload_attachment()
#6 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-20 08:45:09 [error X 5][/var/www/prv/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::656] Uncaught Error: Call to a member function attributes() on bool in /var/www/prv/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php:656
Stack trace:
#0 /var/www/prv/wp-includes/class-wp-hook.php(303): Elementor\Core\Files\Assets\Svg\Svg_Handler->set_svg_meta_data(Array, 95)
#1 /var/www/prv/wp-includes/plugin.php(189): WP_Hook->apply_filters(Array, Array)
#2 /var/www/prv/wp-includes/post.php(6366): apply_filters('wp_update_attac...', Array, 95)
#3 /var/www/prv/wp-admin/includes/image.php(178): wp_update_attachment_metadata(95, Array)
#4 /var/www/prv/wp-admin/includes/ajax-actions.php(2459): wp_update_image_subsizes(95)
#5 /var/www/prv/wp-includes/class-wp-hook.php(303): wp_ajax_media_create_image_subsizes('')
#6 /var/www/prv/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#7 /var/www/prv/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#8 /var/www/prv/wp-admin/ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-20 08:45:37 [error X 1][/var/www/prv/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::656] Uncaught Error: Call to a member function attributes() on bool in /var/www/prv/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php:656
Stack trace:
#0 /var/www/prv/wp-includes/class-wp-hook.php(303): Elementor\Core\Files\Assets\Svg\Svg_Handler->set_svg_meta_data(Array, 96)
#1 /var/www/prv/wp-includes/plugin.php(189): WP_Hook->apply_filters(Array, Array)
#2 /var/www/prv/wp-includes/post.php(6366): apply_filters('wp_update_attac...', Array, 96)
#3 /var/www/prv/wp-admin/includes/media.php(421): wp_update_attachment_metadata(96, Array)
#4 /var/www/prv/wp-admin/includes/ajax-actions.php(2549): media_handle_upload('async-upload', '66', Array)
#5 /var/www/prv/wp-admin/async-upload.php(33): wp_ajax_upload_attachment()
#6 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-20 08:45:38 [error X 5][/var/www/prv/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::656] Uncaught Error: Call to a member function attributes() on bool in /var/www/prv/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php:656
Stack trace:
#0 /var/www/prv/wp-includes/class-wp-hook.php(303): Elementor\Core\Files\Assets\Svg\Svg_Handler->set_svg_meta_data(Array, 96)
#1 /var/www/prv/wp-includes/plugin.php(189): WP_Hook->apply_filters(Array, Array)
#2 /var/www/prv/wp-includes/post.php(6366): apply_filters('wp_update_attac...', Array, 96)
#3 /var/www/prv/wp-admin/includes/image.php(178): wp_update_attachment_metadata(96, Array)
#4 /var/www/prv/wp-admin/includes/ajax-actions.php(2459): wp_update_image_subsizes(96)
#5 /var/www/prv/wp-includes/class-wp-hook.php(303): wp_ajax_media_create_image_subsizes('')
#6 /var/www/prv/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#7 /var/www/prv/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#8 /var/www/prv/wp-admin/ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-20 08:58:46 [error X 1][/var/www/prv/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::656] Uncaught Error: Call to a member function attributes() on bool in /var/www/prv/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php:656
Stack trace:
#0 /var/www/prv/wp-includes/class-wp-hook.php(303): Elementor\Core\Files\Assets\Svg\Svg_Handler->set_svg_meta_data(Array, 102)
#1 /var/www/prv/wp-includes/plugin.php(189): WP_Hook->apply_filters(Array, Array)
#2 /var/www/prv/wp-includes/post.php(6366): apply_filters('wp_update_attac...', Array, 102)
#3 /var/www/prv/wp-admin/includes/media.php(421): wp_update_attachment_metadata(102, Array)
#4 /var/www/prv/wp-admin/async-upload.php(114): media_handle_upload('async-upload', 0)
#5 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-20 08:58:47 [error X 5][/var/www/prv/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::656] Uncaught Error: Call to a member function attributes() on bool in /var/www/prv/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php:656
Stack trace:
#0 /var/www/prv/wp-includes/class-wp-hook.php(303): Elementor\Core\Files\Assets\Svg\Svg_Handler->set_svg_meta_data(Array, 102)
#1 /var/www/prv/wp-includes/plugin.php(189): WP_Hook->apply_filters(Array, Array)
#2 /var/www/prv/wp-includes/post.php(6366): apply_filters('wp_update_attac...', Array, 102)
#3 /var/www/prv/wp-admin/includes/image.php(178): wp_update_attachment_metadata(102, Array)
#4 /var/www/prv/wp-admin/includes/ajax-actions.php(2459): wp_update_image_subsizes(102)
#5 /var/www/prv/wp-includes/class-wp-hook.php(303): wp_ajax_media_create_image_subsizes('')
#6 /var/www/prv/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#7 /var/www/prv/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#8 /var/www/prv/wp-ad [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-20 09:04:16 [error X 1][/var/www/prv/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::656] Uncaught Error: Call to a member function attributes() on bool in /var/www/prv/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php:656
Stack trace:
#0 /var/www/prv/wp-includes/class-wp-hook.php(303): Elementor\Core\Files\Assets\Svg\Svg_Handler->set_svg_meta_data(Array, 103)
#1 /var/www/prv/wp-includes/plugin.php(189): WP_Hook->apply_filters(Array, Array)
#2 /var/www/prv/wp-includes/post.php(6366): apply_filters('wp_update_attac...', Array, 103)
#3 /var/www/prv/wp-admin/includes/media.php(421): wp_update_attachment_metadata(103, Array)
#4 /var/www/prv/wp-admin/async-upload.php(114): media_handle_upload('async-upload', 0)
#5 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-20 09:04:17 [error X 5][/var/www/prv/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::656] Uncaught Error: Call to a member function attributes() on bool in /var/www/prv/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php:656
Stack trace:
#0 /var/www/prv/wp-includes/class-wp-hook.php(303): Elementor\Core\Files\Assets\Svg\Svg_Handler->set_svg_meta_data(Array, 103)
#1 /var/www/prv/wp-includes/plugin.php(189): WP_Hook->apply_filters(Array, Array)
#2 /var/www/prv/wp-includes/post.php(6366): apply_filters('wp_update_attac...', Array, 103)
#3 /var/www/prv/wp-admin/includes/image.php(178): wp_update_attachment_metadata(103, Array)
#4 /var/www/prv/wp-admin/includes/ajax-actions.php(2459): wp_update_image_subsizes(103)
#5 /var/www/prv/wp-includes/class-wp-hook.php(303): wp_ajax_media_create_image_subsizes('')
#6 /var/www/prv/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#7 /var/www/prv/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#8 /var/www/prv/wp-ad [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-20 10:29:24 [error X 1][/var/www/prv/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::656] Uncaught Error: Call to a member function attributes() on bool in /var/www/prv/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php:656
Stack trace:
#0 /var/www/prv/wp-includes/class-wp-hook.php(303): Elementor\Core\Files\Assets\Svg\Svg_Handler->set_svg_meta_data(Array, 105)
#1 /var/www/prv/wp-includes/plugin.php(189): WP_Hook->apply_filters(Array, Array)
#2 /var/www/prv/wp-includes/post.php(6366): apply_filters('wp_update_attac...', Array, 105)
#3 /var/www/prv/wp-admin/includes/media.php(421): wp_update_attachment_metadata(105, Array)
#4 /var/www/prv/wp-admin/async-upload.php(114): media_handle_upload('async-upload', 0)
#5 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-20 10:29:24 [error X 5][/var/www/prv/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::656] Uncaught Error: Call to a member function attributes() on bool in /var/www/prv/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php:656
Stack trace:
#0 /var/www/prv/wp-includes/class-wp-hook.php(303): Elementor\Core\Files\Assets\Svg\Svg_Handler->set_svg_meta_data(Array, 105)
#1 /var/www/prv/wp-includes/plugin.php(189): WP_Hook->apply_filters(Array, Array)
#2 /var/www/prv/wp-includes/post.php(6366): apply_filters('wp_update_attac...', Array, 105)
#3 /var/www/prv/wp-admin/includes/image.php(178): wp_update_attachment_metadata(105, Array)
#4 /var/www/prv/wp-admin/includes/ajax-actions.php(2459): wp_update_image_subsizes(105)
#5 /var/www/prv/wp-includes/class-wp-hook.php(303): wp_ajax_media_create_image_subsizes('')
#6 /var/www/prv/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#7 /var/www/prv/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#8 /var/www/prv/wp-ad [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-31 09:32:57 [notice X 4][/var/www/prv/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-09-08 08:45:27 [notice X 1][/var/www/prv/wp-content/plugins/elementor-pro/modules/forms/classes/ajax-handler.php::118] Undefined index: form_fields [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]


				
```
</details>

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it, we simply can't help.

Thanks.
