### ISSUE TITLE
Global widget in pages/posts (logged out) throws a Fatal error in DEV versions 3.5.0

### ISSUE THREAD

**Issue by mrcrisjan** [elementor/elementor#16354]
## Prerequisites

- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X ] The issue still exists against the latest development version of Elementor.

## Description

Using a Global widget in any pages or posts throws a fatal error (_Uncaught Error: Call to a member function get_component() on null_) when visiting the page/post while being logged out of the website.

This is still happening in the latest DEV versions of Elementor 3.5.0-dev27 and Elementor Pro 3.5.0-dev9.

Screenshot of the fatal error: https://i.imgur.com/CIBiSoE.png

Screencast reproducing the issue: http://somup.com/crQb0lrCa9

## Steps to reproduce

1. Install the DEV versions of Elementor 3.5.0-dev27 and Elementor Pro 3.5.0-dev9.
2. Create a page or post and edit it with Elementor.
3. Insert any widget and save it as a Global widget.
4. Keep the Global widget on that page.
5. Go to the public page URL while being logged in on the website; the page will look good.
6. Go to the public page URL while being logged out of the website or use the incognito window; a fatal error will appear: _Fatal error: Uncaught Error: Call to a member function get_component() on null in websitedomain\wp-content\plugins\elementor-pro\modules\global-widget\widgets\global-widget.php on line 197_

## Isolating the problem

- [X ] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [X ] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: WINNT
	Software: nginx/1.16.0
	MySQL version: mariadb.org binary distribution v10.4.10
	PHP Version: 7.4.1
	PHP Max Input Vars: 4000
	PHP Max Post Size: 1000M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Not connected (cURL error 28: Operation timed out after 5011 milliseconds with 37414 bytes received)

== WordPress Environment ==
	Version: 5.8.1
	Site URL: http://wpml-bug-test.local
	Home URL: http://wpml-bug-test.local
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.4.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.5.0-dev27
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.5.0-dev9
		Author: Elementor.com


== Elementor - Compatibility Tag ==
	
	Elementor Pro: Incompatible

== Elementor Pro - Compatibility Tag ==
	


== Elements Usage ==
	
	widget : 0
		heading : 1
		icon : 1
	wp-page : 2
		heading : 1
		icon : 1


== Log ==
	
Log: showing 10 of 102021-09-17 22:39:44 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.4',
  'to' => '3.5.0-dev27',
)]
2021-09-17 22:39:47 [info] elementor::elementor_updater Started 
2021-09-17 22:39:47 [info] Elementor/Upgrades - _on_each_version Start  
2021-09-17 22:39:47 [info] Elementor/Upgrades - _on_each_version Finished 
2021-09-17 22:39:47 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.4',
  'to' => '3.5.0-dev27',
)]
2021-09-17 22:43:29 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.4.1',
  'to' => '3.5.0-dev9',
)]
2021-09-17 22:43:30 [info] elementor-pro::elementor_pro_updater Started 
2021-09-17 22:43:30 [info] Elementor Pro/Upgrades - _on_each_version Start  
2021-09-17 22:43:30 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2021-09-17 22:43:30 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.4.1',
  'to' => '3.5.0-dev9',
)]

PHP: showing 1 of 1PHP: 2021-09-17 22:48:13 [error X 9][C:\Users\cristian.l\Local Sites\wpml-bug-test\app\public\wp-content\plugins\elementor-pro\modules\global-widget\widgets\global-widget.php::197] Uncaught Error: Call to a member function get_component() on null in C:\Users\cristian.l\Local Sites\wpml-bug-test\app\public\wp-content\plugins\elementor-pro\modules\global-widget\widgets\global-widget.php:197
Stack trace:
#0 C:\Users\cristian.l\Local Sites\wpml-bug-test\app\public\wp-content\plugins\elementor-pro\modules\global-widget\widgets\global-widget.php(68): ElementorPro\Modules\GlobalWidget\Widgets\Global_Widget->is_draft_or_autosave_process()
#1 C:\Users\cristian.l\Local Sites\wpml-bug-test\app\public\wp-content\plugins\elementor\includes\managers\elements.php(86): ElementorPro\Modules\GlobalWidget\Widgets\Global_Widget->__construct(Array, Array)
#2 C:\Users\cristian.l\Local Sites\wpml-bug-test\app\public\wp-content\plugins\elementor\includes\base\element-base.php(347): Elementor\Elements_Manager->create_element_instance(Array, Array, Object(ElementorPro\Modules\GlobalWidget\Widgets\Global_Widget))
#3 C:\Users\cristian.l\Local Sites\wpml-bug-test\app\public\wp-content\plugins\elementor\includes\bas [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]


				```
</details>

**Comment by Aviad-Herman** [comment]
Thanks @mrcrisjan,
We are trying to update the global widget infrastructure to solve all existing bugs and I guess we caused a new bug :)
We will handle this. thanks!
