### ISSUE TITLE
Toggle button doubled

### ISSUE THREAD

**Issue by karin-pacholkova** [elementor/elementor#16624]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest development version of Elementor.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [ ] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Debian 10 v10.3.29
	PHP Version: 7.1.33
	PHP Max Input Vars: 5000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.8.1
	Site URL: https://www.zvsturnov.cz
	Home URL: https://www.zvsturnov.cz
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: cs
	Timezone: Europe/Prague
	Admin Email: karin.pacholkova@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 2.4.1.1630789140
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.4.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: cs_CZ
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36

== Active Plugins ==
	Child Theme Configurator
		Version: 2.5.8
		Author: Lilaea Media

	Elementor
		Version: 3.5.0-dev42
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.5.0-dev16
		Author: Elementor.com

	Wordfence Security
		Version: 7.5.6
		Author: Wordfence

	WordPress Importer
		Version: 0.7
		Author: wordpressdotorg


== Elementor - Compatibility Tag ==
	
	Elementor Pro: Incompatible

== Elementor Pro - Compatibility Tag ==
	


== Elements Usage ==
	
	footer : 1
		divider : 1
		heading : 1
		icon-list : 2
		image : 1
		nav-menu : 1
		social-icons : 1
	header : 2
		button : 1
		nav-menu : 1
		theme-site-logo : 1
	page : 5
		button : 4
		call-to-action : 7
		divider : 1
		heading : 29
		icon : 1
		icon-list : 4
		image : 4
		image-carousel : 1
		spacer : 17
		tabs : 1
		text-editor : 10
		toggle : 12
	popup : 1
		button : 1
		heading : 2
		icon : 1
		spacer : 1
	section : 10
		button : 1
		call-to-action : 9
		form : 1
		google_maps : 1
		heading : 15
		icon-box : 8
		posts : 1
		spacer : 7
	wp-post : 2
		image : 4
		text-editor : 2
	wp-page : 16
		button : 9
		form : 1
		gallery : 1
		google_maps : 2
		heading : 80
		icon-list : 2
		image : 28
		menu-anchor : 2
		posts : 1
		spacer : 26
		text-editor : 37
		wp-widget-nav_menu : 1
	single-post : 1
		post-navigation : 1
		theme-post-content : 1
		theme-post-title : 1
	error-404 : 1
		button : 1
		heading : 2
		spacer : 2


== Elementor Experiments ==
	Optimized DOM Output: Ve výchozím stavu aktivní
	Vylepšené načítání assetů: Ve výchozím stavu aktivní
	Improved CSS Loading: Ve výchozím stavu aktivní
	Font-Awesome Inline: Aktivní
	Vylepšení přístupnosti: Ve výchozím stavu aktivní
	Import Export Template Kit: Aktivní
	Additional Custom Breakpoints: Ve výchozím stavu aktivní
	Hide native WordPress widgets from search results: Ve výchozím stavu aktivní
	Default to New Theme Builder: Ve výchozím stavu aktivní
	Hello Theme Header & Footer: Aktivní
	Landing Pages: Ve výchozím stavu aktivní
	Color Sampler: Ve výchozím stavu aktivní
	Admin Top Bar: Ve výchozím stavu aktivní
	Custom Default Widget Styles: Ve výchozím stavu neaktivní
	Page Transitions: Ve výchozím stavu aktivní
	Form Submissions: Ve výchozím stavu aktivní


== Log ==
	
Log: showing 20 of 402021-10-14 16:54:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.4.1',
  'to' => '3.5.0-dev14',
)]
2021-10-14 16:54:22 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.4.1',
  'to' => '3.5.0-dev14',
)]
2021-10-15 21:20:50 [info] elementor::elementor_updater Started 
2021-10-15 21:20:50 [info] Elementor/Upgrades - _on_each_version Start  
2021-10-15 21:20:51 [info] Elementor/Upgrades - _on_each_version Finished 
2021-10-15 21:20:51 [info] Elementor/Upgrades - _v_3_5_0_remove_old_elementor_scheme Start  
2021-10-15 21:20:51 [info] Elementor/Upgrades - _v_3_5_0_remove_old_elementor_scheme Finished 
2021-10-15 21:20:51 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.0-dev40',
  'to' => '3.5.0-dev41',
)]
2021-10-16 13:09:13 [info] elementor-pro::elementor_pro_updater Started 
2021-10-16 13:09:13 [info] Elementor Pro/Upgrades - _on_each_version Start  
2021-10-16 13:09:13 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2021-10-16 13:09:13 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.5.0-dev14',
  'to' => '3.5.0-dev16',
)]
2021-10-16 13:09:13 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.5.0-dev14',
  'to' => '3.5.0-dev16',
)]
2021-10-18 16:00:33 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.0-dev41',
  'to' => '3.5.0-dev42',
)]
2021-10-18 16:00:33 [info] elementor::elementor_updater Started 
2021-10-18 16:00:33 [info] Elementor/Upgrades - _on_each_version Start  
2021-10-18 16:00:34 [info] Elementor/Upgrades - _on_each_version Finished 
2021-10-18 16:00:34 [info] Elementor/Upgrades - _v_3_5_0_remove_old_elementor_scheme Start  
2021-10-18 16:00:34 [info] Elementor/Upgrades - _v_3_5_0_remove_old_elementor_scheme Finished 
2021-10-18 16:00:34 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.0-dev41',
  'to' => '3.5.0-dev42',
)]

PHP: showing 2 of 2PHP: 2021-10-14 22:56:36 [notice X 14][C:\xampp\htdocs\zvsturnov\wp-content\plugins\elementor\core\common\modules\ajax\module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-10-16 19:59:46 [error X 1][/www/doc/www.zvsturnov.cz/www/wp-content/plugins/elementor/includes/managers/widgets.php::85] Uncaught Error: Class 'Elementor\Widget_shortcode' not found in /www/doc/www.zvsturnov.cz/www/wp-content/plugins/elementor/includes/managers/widgets.php:85
Stack trace:
#0 /www/doc/www.zvsturnov.cz/www/wp-content/plugins/elementor/includes/managers/widgets.php(301): Elementor\Widgets_Manager->init_widgets()
#1 /www/doc/www.zvsturnov.cz/www/wp-content/plugins/elementor/includes/elements/column.php(1026): Elementor\Widgets_Manager->get_widget_types('image')
#2 /www/doc/www.zvsturnov.cz/www/wp-content/plugins/elementor/includes/base/element-base.php(796): Elementor\Element_Column->_get_default_child_type(Array)
#3 /www/doc/www.zvsturnov.cz/www/wp-content/plugins/elementor/includes/base/element-base.php(341): Elementor\Element_Base->get_child_type(Array)
#4 /www/doc/www.zvsturnov.cz/www/wp-content/plugins/elementor/includes/base/element-base.php(841): Elementor\Element_Base->add_child(Array)
#5 /www/doc/www.zvsturnov.cz/www/wp-content/plugins/elementor/includes/base/element-base.php(301): Elementor\Element_Base-> [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Debian 10 v10.3.29
	PHP Version: 7.1.33
	PHP Max Input Vars: 5000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.8.1
	Site URL: https://www.zvsturnov.cz
	Home URL: https://www.zvsturnov.cz
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: cs
	Timezone: Europe/Prague
	Admin Email: karin.pacholkova@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 2.4.1.1630789140
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.4.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: cs_CZ
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36

== Active Plugins ==
	Child Theme Configurator
		Version: 2.5.8
		Author: Lilaea Media

	Elementor
		Version: 3.5.0-dev42
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.5.0-dev16
		Author: Elementor.com

	Wordfence Security
		Version: 7.5.6
		Author: Wordfence

	WordPress Importer
		Version: 0.7
		Author: wordpressdotorg


== Elementor - Compatibility Tag ==
	
	Elementor Pro: Incompatible

== Elementor Pro - Compatibility Tag ==
	


== Elements Usage ==
	
	footer : 1
		divider : 1
		heading : 1
		icon-list : 2
		image : 1
		nav-menu : 1
		social-icons : 1
	header : 2
		button : 1
		nav-menu : 1
		theme-site-logo : 1
	page : 5
		button : 4
		call-to-action : 7
		divider : 1
		heading : 29
		icon : 1
		icon-list : 4
		image : 4
		image-carousel : 1
		spacer : 17
		tabs : 1
		text-editor : 10
		toggle : 12
	popup : 1
		button : 1
		heading : 2
		icon : 1
		spacer : 1
	section : 10
		button : 1
		call-to-action : 9
		form : 1
		google_maps : 1
		heading : 15
		icon-box : 8
		posts : 1
		spacer : 7
	wp-post : 2
		image : 4
		text-editor : 2
	wp-page : 16
		button : 9
		form : 1
		gallery : 1
		google_maps : 2
		heading : 80
		icon-list : 2
		image : 28
		menu-anchor : 2
		posts : 1
		spacer : 26
		text-editor : 37
		wp-widget-nav_menu : 1
	single-post : 1
		post-navigation : 1
		theme-post-content : 1
		theme-post-title : 1
	error-404 : 1
		button : 1
		heading : 2
		spacer : 2


== Elementor Experiments ==
	Optimized DOM Output: Ve výchozím stavu aktivní
	Vylepšené načítání assetů: Ve výchozím stavu aktivní
	Improved CSS Loading: Ve výchozím stavu aktivní
	Font-Awesome Inline: Aktivní
	Vylepšení přístupnosti: Ve výchozím stavu aktivní
	Import Export Template Kit: Aktivní
	Additional Custom Breakpoints: Ve výchozím stavu aktivní
	Hide native WordPress widgets from search results: Ve výchozím stavu aktivní
	Default to New Theme Builder: Ve výchozím stavu aktivní
	Hello Theme Header & Footer: Aktivní
	Landing Pages: Ve výchozím stavu aktivní
	Color Sampler: Ve výchozím stavu aktivní
	Admin Top Bar: Ve výchozím stavu aktivní
	Custom Default Widget Styles: Ve výchozím stavu neaktivní
	Page Transitions: Ve výchozím stavu aktivní
	Form Submissions: Ve výchozím stavu aktivní


== Log ==
	
Log: showing 20 of 402021-10-14 16:54:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.4.1',
  'to' => '3.5.0-dev14',
)]
2021-10-14 16:54:22 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.4.1',
  'to' => '3.5.0-dev14',
)]
2021-10-15 21:20:50 [info] elementor::elementor_updater Started 
2021-10-15 21:20:50 [info] Elementor/Upgrades - _on_each_version Start  
2021-10-15 21:20:51 [info] Elementor/Upgrades - _on_each_version Finished 
2021-10-15 21:20:51 [info] Elementor/Upgrades - _v_3_5_0_remove_old_elementor_scheme Start  
2021-10-15 21:20:51 [info] Elementor/Upgrades - _v_3_5_0_remove_old_elementor_scheme Finished 
2021-10-15 21:20:51 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.0-dev40',
  'to' => '3.5.0-dev41',
)]
2021-10-16 13:09:13 [info] elementor-pro::elementor_pro_updater Started 
2021-10-16 13:09:13 [info] Elementor Pro/Upgrades - _on_each_version Start  
2021-10-16 13:09:13 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2021-10-16 13:09:13 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.5.0-dev14',
  'to' => '3.5.0-dev16',
)]
2021-10-16 13:09:13 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.5.0-dev14',
  'to' => '3.5.0-dev16',
)]
2021-10-18 16:00:33 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.0-dev41',
  'to' => '3.5.0-dev42',
)]
2021-10-18 16:00:33 [info] elementor::elementor_updater Started 
2021-10-18 16:00:33 [info] Elementor/Upgrades - _on_each_version Start  
2021-10-18 16:00:34 [info] Elementor/Upgrades - _on_each_version Finished 
2021-10-18 16:00:34 [info] Elementor/Upgrades - _v_3_5_0_remove_old_elementor_scheme Start  
2021-10-18 16:00:34 [info] Elementor/Upgrades - _v_3_5_0_remove_old_elementor_scheme Finished 
2021-10-18 16:00:34 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.0-dev41',
  'to' => '3.5.0-dev42',
)]

PHP: showing 2 of 2PHP: 2021-10-14 22:56:36 [notice X 14][C:\xampp\htdocs\zvsturnov\wp-content\plugins\elementor\core\common\modules\ajax\module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-10-16 19:59:46 [error X 1][/www/doc/www.zvsturnov.cz/www/wp-content/plugins/elementor/includes/managers/widgets.php::85] Uncaught Error: Class 'Elementor\Widget_shortcode' not found in /www/doc/www.zvsturnov.cz/www/wp-content/plugins/elementor/includes/managers/widgets.php:85
Stack trace:
#0 /www/doc/www.zvsturnov.cz/www/wp-content/plugins/elementor/includes/managers/widgets.php(301): Elementor\Widgets_Manager->init_widgets()
#1 /www/doc/www.zvsturnov.cz/www/wp-content/plugins/elementor/includes/elements/column.php(1026): Elementor\Widgets_Manager->get_widget_types('image')
#2 /www/doc/www.zvsturnov.cz/www/wp-content/plugins/elementor/includes/base/element-base.php(796): Elementor\Element_Column->_get_default_child_type(Array)
#3 /www/doc/www.zvsturnov.cz/www/wp-content/plugins/elementor/includes/base/element-base.php(341): Elementor\Element_Base->get_child_type(Array)
#4 /www/doc/www.zvsturnov.cz/www/wp-content/plugins/elementor/includes/base/element-base.php(841): Elementor\Element_Base->add_child(Array)
#5 /www/doc/www.zvsturnov.cz/www/wp-content/plugins/elementor/includes/base/element-base.php(301): Elementor\Element_Base-> [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]


Submenu indication in the Header /Nav Menu (by the first menu item) is doubled. 

				
</details>

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites
* Steps to replicate
* Isolating the problem
* System info
* One issue per thread

Without it we simply can't help.

Thanks.
