### ISSUE TITLE
Orizzontal Scroll in container not work out of backend

### ISSUE THREAD

**Issue by drau1** [elementor/elementor#16984]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest development version of Elementor.

## Description

 I have tryed to make a container with more image in row, in backend that work fine, and appear a scroll bar to move orizzontally. But it don't work in preview mode or url load

## Isolating the problem

- [ x] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [ x] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ --> 					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.3.28
	PHP Version: 7.4.22
	PHP Max Input Vars: 10000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.8.2
	Site URL: https://www.drau.it
	Home URL: https://www.drau.it
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Europe/Rome
	Admin Email: info@drau.it
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.3.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36

== Active Plugins ==
	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Elementor
		Version: 3.6.0-dev5
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.6.0-dev11
		Author: Elementor.com

	W3 Total Cache
		Version: 2.1.9
		Author: BoldGrid

	Yoast SEO
		Version: 17.6
		Author: Team Yoast


== Must-Use Plugins ==
	akeeba-backup-coreupdate.php
		Version: 
		Author: 


== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==
	


== Elements Usage ==
	
	container : 1
		button : 1
		container : 1
		social-icons : 1
	header : 1
		button : 1
		container : 1
		social-icons : 1
	page : 3
		container : 1
		heading : 2
		lottie : 1
		social-icons : 1
	popup : 2
		button : 1
		form : 1
		heading : 1
		icon : 1
		nav-menu : 1
		social-icons : 1
		spacer : 1
		text-editor : 1
	wp-post : 2
		button : 2
		heading : 1
		icon-list : 1
		lottie : 1
		post-navigation : 1
		theme-post-excerpt : 2
		theme-post-featured-image : 2
		theme-post-title : 2
		theme-site-logo : 2
		video : 1
	wp-page : 2
		button : 1
		container : 12
		gallery : 2
		heading : 10
		image : 8
		text-editor : 5
		toggle : 1


== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active
	Container: Active
	Default to New Theme Builder: Active by default
	Landing Pages: Active
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Custom Default Widget Styles: Inactive by default
	Page Transitions: Active
	Form Submissions: Active by default
	Scroll Snap: Active by default


== Log ==
	
Log: showing 20 of 372021-11-06 21:55:15 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.3.5',
  'to' => '3.5.0',
)]
2021-11-12 17:47:54 [info] elementor-pro::elementor_pro_updater Started 
2021-11-12 17:47:54 [info] Elementor Pro/Upgrades - _on_each_version Start  
2021-11-12 17:47:54 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2021-11-12 17:47:54 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.5.0',
  'to' => '3.6.0-dev11',
)]
2021-11-12 17:47:54 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.5.0',
  'to' => '3.6.0-dev11',
)]
2021-11-12 17:48:26 [info] elementor::elementor_updater Started 
2021-11-12 17:48:26 [info] Elementor/Upgrades - _on_each_version Start  
2021-11-12 17:48:26 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.7',
  'to' => '3.6.0-dev3',
)]
2021-11-12 17:48:26 [info] Elementor/Upgrades - _on_each_version Finished 
2021-11-12 17:48:26 [info] Elementor/Upgrades - _v_3_4_8_fix_font_awesome_default_value_from_1_to_yes Start  
2021-11-12 17:48:26 [info] Elementor/Upgrades - _v_3_4_8_fix_font_awesome_default_value_from_1_to_yes Finished 
2021-11-12 17:48:26 [info] Elementor/Upgrades - _v_3_5_0_remove_old_elementor_scheme Start  
2021-11-12 17:48:26 [info] Elementor/Upgrades - _v_3_5_0_remove_old_elementor_scheme Finished 
2021-11-12 17:48:26 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.7',
  'to' => '3.6.0-dev3',
)]
2021-11-18 12:56:51 [info] elementor::elementor_updater Started 
2021-11-18 12:56:51 [info] Elementor/Upgrades - _on_each_version Start  
2021-11-18 12:56:51 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0-dev3',
  'to' => '3.6.0-dev5',
)]
2021-11-18 12:56:52 [info] Elementor/Upgrades - _on_each_version Finished 
2021-11-18 12:56:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0-dev3',
  'to' => '3.6.0-dev5',
)]

PHP: showing 6 of 6PHP: 2021-08-03 16:47:17 [notice X 2][/var/www/vhosts/drau.it/httpdocs/wp-content/plugins/elementor/core/app/modules/import-export/module.php::156] Undefined index: session [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-25 22:09:57 [error X 8][/var/www/vhosts/drau.it/httpdocs/wp-content/plugins/elementor/core/wp-api.php::26] Uncaught Error: Call to undefined function Elementor\Core\get_plugins() in /var/www/vhosts/drau.it/httpdocs/wp-content/plugins/elementor/core/wp-api.php:26
Stack trace:
#0 /var/www/vhosts/drau.it/httpdocs/wp-content/plugins/elementor/core/wp-api.php(36): Elementor\Core\Wp_Api->get_plugins()
#1 /var/www/vhosts/drau.it/httpdocs/wp-content/plugins/elementor/modules/system-info/reporters/plugins.php(44): Elementor\Core\Wp_Api->get_active_plugins()
#2 /var/www/vhosts/drau.it/httpdocs/wp-content/plugins/elementor/modules/system-info/reporters/plugins.php(75): Elementor\Modules\System_Info\Reporters\Plugins->get_plugins()
#3 /var/www/vhosts/drau.it/httpdocs/wp-content/plugins/elementor/modules/system-info/module.php(298): Elementor\Modules\System_Info\Reporters\Plugins->is_enabled()
#4 /var/www/vhosts/drau.it/httpdocs/wp-content/plugins/elementor/modules/system-info/module.php(255): Elementor\Modules\System_Info\Module->create_reporter(Array)
#5 /var/www/vhosts/drau.it/httpdocs/wp-content/plugins/elementor/includes/ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-09-22 16:52:45 [notice X 3][/var/www/vhosts/drau.it/httpdocs/wp-content/plugins/elementor-pro/modules/forms/classes/form-record.php::179] Undefined index: referrer [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-11-07 16:13:25 [error X 1][/var/www/vhosts/drau.it/httpdocs/wp-content/plugins/elementor/includes/template-library/sources/local.php::1046] Uncaught TypeError: Argument 2 passed to Elementor\TemplateLibrary\Source_Local::on_save_post() must be an instance of WP_Post, null given, called in /var/www/vhosts/drau.it/httpdocs/wp-includes/class-wp-hook.php on line 305 and defined in /var/www/vhosts/drau.it/httpdocs/wp-content/plugins/elementor/includes/template-library/sources/local.php:1046
Stack trace:
#0 /var/www/vhosts/drau.it/httpdocs/wp-includes/class-wp-hook.php(305): Elementor\TemplateLibrary\Source_Local->on_save_post(7869, NULL)
#1 /var/www/vhosts/drau.it/httpdocs/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array)
#2 /var/www/vhosts/drau.it/httpdocs/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#3 /var/www/vhosts/drau.it/httpdocs/wp-includes/post.php(4468): do_action('save_post', 7869, NULL, true)
#4 /var/www/vhosts/drau.it/httpdocs/wp-includes/post.php(4570): wp_insert_post(Array, false, true)
#5 /var/www/vhosts/drau.it/httpdocs/wp-content/plugins/elementor/includes/db.php(235): wp_update_post(Array)
#6 /var/www [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-11-13 18:03:30 [notice X 1][/var/www/vhosts/drau.it/httpdocs/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-11-17 20:26:01 [error X 1][/var/www/vhosts/drau.it/httpdocs/wp-content/plugins/elementor/core/wp-api.php::26] Uncaught Error: Call to undefined function Elementor\Core\get_plugins() in /var/www/vhosts/drau.it/httpdocs/wp-content/plugins/elementor/core/wp-api.php:26
Stack trace:
#0 /var/www/vhosts/drau.it/httpdocs/wp-content/plugins/elementor/core/wp-api.php(36): Elementor\Core\Wp_Api->get_plugins()
#1 /var/www/vhosts/drau.it/httpdocs/wp-content/plugins/elementor/modules/system-info/reporters/plugins.php(44): Elementor\Core\Wp_Api->get_active_plugins()
#2 /var/www/vhosts/drau.it/httpdocs/wp-content/plugins/elementor/modules/system-info/reporters/plugins.php(75): Elementor\Modules\System_Info\Reporters\Plugins->get_plugins()
#3 /var/www/vhosts/drau.it/httpdocs/wp-content/plugins/elementor/modules/system-info/module.php(292): Elementor\Modules\System_Info\Reporters\Plugins->is_enabled()
#4 /var/www/vhosts/drau.it/httpdocs/wp-content/plugins/elementor/modules/system-info/module.php(249): Elementor\Modules\System_Info\Module->create_reporter(Array)
#5 /var/www/vhosts/drau.it/httpdocs/wp-content/plugins/elementor/includes/ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]


				
```
</details>
![2021-11-18-16-33-www drau it](https://user-images.githubusercontent.com/94255240/142446315-17c28187-ffa2-44ed-815a-0ca07cfee43e.png)
![2021-11-18-16-34-www drau it](https://user-images.githubusercontent.com/94255240/142446339-b05a2cc0-0b67-4f4f-8b6e-9ea14438b155.png)
![2021-11-18-16-35-www drau it](https://user-images.githubusercontent.com/94255240/142446359-664a0df9-800e-4ef1-a406-0c557faba02d.png)

**Comment by shilo-ey** [comment]
Hi @drau1 

This feature is currently not supported by the container but we will consider adding it soon.

Thanks!
