### ISSUE TITLE
Editor does not load content or revisions after 3.6.0-dev13 and dev14, reinstalling stable causes content to disappear on front end

### ISSUE THREAD

**Issue by JoshuaGoode** [elementor/elementor#17089]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest development version of Elementor.

## Description

It appears 3.6.0-dev13 introduced various changes that are now breaking the editor for some users and we've had numerous reports on WordPress.com.

After updating, sites may no longer be able to load content in the editor. 

For example, this page has a lot of Elementor-based content that is available in `post_content` but the editor fails to load it. However, the content still loads on the front end.

 ![Screen Shot on 2021-12-01 at 13:18:18](https://user-images.githubusercontent.com/4887830/144291000-b588e2b9-85fa-4c76-8a0c-58d264dd74ef.png)

Attempting to rollback to stable will result in the content no longer being visible on both the front end and editor. Attempting to load revisions will fail.

Rolling back to `-dev11` appears to be a temporary workaround.

## Steps to reproduce

* Install 3.6.0-dev11 and create a page, preferably with multiple revisions.
* Update to 3.6.0-dev13 or -dev14. 

## Findings & Workaround

In `dev13`, it appears `wp-content/plugins/elementor/core/experiments/manager.php` L#327 was modified.

The release_status for the `container` feature was changed from `RELEASE_STATUS_BETA` to `RELEASE_STATUS_ALPHA`.

```
		$this->add_feature( [
			'name' => 'container',
			'title' => esc_html__( 'Container', 'elementor' ),
			'description' => esc_html__(
				'Create advanced layouts and responsive designs using the new Container element.
				When this experiment is active, Containers will be the default building block.
				Existing Sections, Inner Sections and Columns will not be affected.',
				'elementor'
			),
			'release_status' => self::RELEASE_STATUS_ALPHA,
			'default' => self::STATE_INACTIVE,
		] );
	}
```

Changing this back to `RELEASE_STATUS_BETA` is a workaround and will allow the editor and front-end content to load. 

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [x] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [x] I can reproduce this bug consistently using the steps above.

## Environment

Multiple sites on WordPress.com, Siteground, and locally hosted.

Environment for local test:

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Darwin
	Software: nginx/1.16.0
	MySQL version: MySQL Community Server - GPL v8.0.16
	PHP Version: 7.3.5
	PHP Max Input Vars: 4000
	PHP Max Post Size: 1000M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.8.2
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Twenty-One
	Version: 1.4
	Author: the WordPress team
	Child Theme: No

== Active Plugins ==
	Debug Bar
		Version: 1.1.2
		Author: wordpressdotorg

	Elementor
		Version: 3.6.0-dev13
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Query Monitor
		Version: 3.7.1
		Author: John Blackbourn


== Elementor - Compatibility Tag ==
	


== Elements Usage ==
	
	header : 0
		heading : 3
		nav-menu : 3
		social-icons : 3
	wp-page : 3
		button : 3
		container : 39
		heading : 2
		image-carousel : 2
		image-gallery : 1
		progress : 6
		spacer : 18
		text-editor : 8
		toggle : 2


== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	Container: Inactive by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Custom Default Widget Styles: Inactive by default


== Log ==
	
Log: showing 12 of 122021-11-27 16:41:59 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.8',
  'to' => '3.6.0-dev11',
)]
2021-11-27 16:42:12 [info] elementor::elementor_updater Started 
2021-11-27 16:42:12 [info] Elementor/Upgrades - _on_each_version Start  
2021-11-27 16:42:12 [info] Elementor/Upgrades - _on_each_version Finished 
2021-11-27 16:42:12 [info] Elementor/Upgrades - _v_3_5_0_remove_old_elementor_scheme Start  
2021-11-27 16:42:12 [info] Elementor/Upgrades - _v_3_5_0_remove_old_elementor_scheme Finished 
2021-11-27 16:42:12 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.8',
  'to' => '3.6.0-dev11',
)]
2021-12-02 01:03:08 [info] elementor::elementor_updater Started 
2021-12-02 01:03:08 [info] Elementor/Upgrades - _on_each_version Start  
2021-12-02 01:03:08 [info] Elementor/Upgrades - _on_each_version Finished 
2021-12-02 01:03:08 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0-dev11',
  'to' => '3.6.0-dev14',
)]
2021-12-02 01:03:08 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0-dev11',
  'to' => '3.6.0-dev14',
)]

PHP: showing 5 of 5PHP: 2021-11-27 19:14:23 [notice X 22][/srv/htdocs/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-11-29 05:57:46 [notice X 1][/srv/htdocs/wp-content/plugins/elementor/core/common/modules/connect/module.php::230] Trying to get property 'email' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-11-29 09:33:03 [error X 1][/srv/htdocs/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::286] Uncaught Error: Call to a member function update_meta() on bool in /srv/htdocs/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:286
Stack trace:
#0 /srv/htdocs/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /srv/htdocs/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /wordpress/core/5.8.2/wp-includes/class-wp-hook.php(303): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /wordpress/core/5.8.2/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array)
#5 /wordpress/core/5.8.2/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#6 /wordpress/core/5.8.2/wp-admin/admin-ajax.php(187): do_action('wp_ajax_element...')
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-11-29 22:39:34 [notice X 2][/srv/htdocs/wp-content/plugins/elementor/includes/managers/image.php::87] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



				
```
</details>

**Comment by JoshuaGoode** [comment]
It appears the `Container` feature was added `wp-content/plugins/elementor/core/experiments/manager.php` to `3.6.0-dev6`.

At that point, it was set to `RELEASE_STATUS_BETA`.

This was changed to `RELEASE_STATUS_BETA` in `3.6.0-dev13`.

#### Workaround

As mentioned in the report, rolling back to `3.6.0-dev11` allows content to load in the editor again and prevents front end issues.

If a user attempts to reinstall stable, their content will not appear in the editor or the front end.

@KingYes

**Comment by JoshuaGoode** [comment]
#### Additional Context

Due to how Elementor advertises the developer edition in WP-Admin, we see many users install and activate the developer edition without understanding the risks associated.

Upon the release of `3.6.0-dev13`, I personally received dozens of reports of these content and editing issues. 

At WordPress.com, we have highlighted that the developer edition is not meant for live sites and, at first, suggested reinstalling stable.  However, the issue persists with stable on the sites already impacted.   We then confirmed with friends at other hosts and reproduced in local environments to confirm this wasn't a WordPress.com-specific issue. 

At this time, we've suggested rolling back to `3.6.0-dev11` until a clearer solution is available.
