### ISSUE TITLE
Elementor v3.5 - Word Spacing Issue in Nav Menu

### ISSUE THREAD

**Issue by ocbroadband** [elementor/elementor#17182]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
When using the word spacing option in an Elementor Nav Menu, it appears to be separating at the wrong points.  In the case of for example, 'about us', it starts separating after the t in about vs. at the s in the word us.

## Steps to reproduce

1. Create a header with a menu with an item of more than 1 word. (ie, about us)
2. Place into a page and edit the typography for the menu. (Style -> Typography)
3. Enter a value for 'Word Spacing' or use the slider.  The text spacing will start between the words vs. at the end of the entire menu item.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

https://user-images.githubusercontent.com/13633011/146031659-f7001898-1f33-4704-b9f4-bd9cb159b60e.mp4

## Environment

<details>
<summary>System Info</summary>
```
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.25 (Debian)
	MySQL version: mariadb.org binary distribution v10.4.20
	PHP Version: 7.4.24
	PHP Max Input Vars: 2500
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.8.2
	Site URL: https://xxx.com
	Home URL: https://xxx.com
	WP Multisite: No
	Max Upload Size: 100 MB
	Memory limit: 384M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/Los_Angeles
	Admin Email: xxxx@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.0
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.4.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36

== Active Plugins ==
	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Elementor
		Version: 3.5.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.5.2
		Author: Elementor.com

	Flexible Elementor Panel
		Version: 2.3.7
		Author: WebMat

	JetBlocks For Elementor
		Version: 1.2.10
		Author: Crocoblock

	JetElements For Elementor
		Version: 2.6.1
		Author: Crocoblock

	JetEngine
		Version: 2.10.2
		Author: Crocoblock

	JetSearch For Elementor
		Version: 2.1.14
		Author: Crocoblock

	MalCare Security - Free Malware Scanner, Protection & Security for WordPress
		Version: 4.68
		Author: MalCare Security

	Rank Math SEO
		Version: 1.0.78
		Author: Rank Math

	Shield Security
		Version: 13.0.1
		Author: Shield Security

	Which Elementor Addon
		Version: 1.2.0
		Author: obiPlabon

	WP Super Cache
		Version: 1.7.4
		Author: Automattic


== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	Flexible Elementor Panel: Compatibility not specified
	JetBlocks For Elementor: Compatibility not specified
	JetElements For Elementor: Compatibility not specified
	JetSearch For Elementor: Compatibility not specified
	Which Elementor Addon: Compatibility not specified

== Elementor Pro - Compatibility Tag ==
	


== Elements Usage ==
	
	archive : 3
		archive-posts : 1
		heading : 3
		jet-listing-grid : 2
		nav-menu : 1
	footer : 1
		heading : 11
		nav-menu : 4
	header : 1
		heading : 3
		icon-box : 2
		image : 1
		jet-nav-menu : 1
		nav-menu : 1
		search-form : 1
	page : 1
		theme-post-content : 1
	popup : 1
		button : 1
		heading : 1
		image : 1
	section : 3
		heading : 3
		image-carousel : 1
		text-editor : 3
	single : 7
		heading : 21
		image : 1
		jet-listing-dynamic-field : 5
		jet-listing-dynamic-image : 1
		nav-menu : 5
		post-info : 3
		post-navigation : 1
		search-form : 1
		theme-post-content : 6
	wp-page : 9
		alert : 1
		divider : 4
		form : 1
		google_maps : 1
		heading : 19
		icon-box : 2
		image : 4
		image-gallery : 4
		jet-listing-grid : 2
		shortcode : 2
		sitemap : 1
		text-editor : 25
	single-page : 1
		heading : 1
		theme-post-content : 1


== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Inactive by default
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Inactive by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Inactive by default
	Hide native WordPress widgets from search results: Active by default
	Default to New Theme Builder: Inactive
	Hello Theme Header & Footer: Inactive by default
	Landing Pages: Inactive
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Inactive
	Form Submissions: Active by default
	Scroll Snap: Inactive by default


== Log ==
	
Log: showing 20 of 402021-11-03 15:09:09 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.4.2',
  'to' => '3.5.0',
)]
2021-11-16 09:15:14 [info] elementor::elementor_updater Started 
2021-11-16 09:15:14 [info] Elementor/Upgrades - _on_each_version Start  
2021-11-16 09:15:14 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.7',
  'to' => '3.4.8',
)]
2021-11-16 09:15:15 [info] Elementor/Upgrades - _on_each_version Finished 
2021-11-16 09:15:15 [info] Elementor/Upgrades - _v_3_4_8_fix_font_awesome_default_value_from_1_to_yes Start  
2021-11-16 09:15:15 [info] Elementor/Upgrades - _v_3_4_8_fix_font_awesome_default_value_from_1_to_yes Finished 
2021-11-16 09:15:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.7',
  'to' => '3.4.8',
)]
2021-11-30 11:48:04 [info] elementor-pro::elementor_pro_updater Started 
2021-11-30 11:48:04 [info] Elementor Pro/Upgrades - _on_each_version Start  
2021-11-30 11:48:04 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2021-11-30 11:48:04 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.5.0',
  'to' => '3.5.2',
)]
2021-11-30 11:48:04 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.5.0',
  'to' => '3.5.2',
)]
2021-12-14 06:58:27 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.8',
  'to' => '3.5.0',
)]
2021-12-14 06:58:28 [info] elementor::elementor_updater Started 
2021-12-14 06:58:28 [info] Elementor/Upgrades - _on_each_version Start  
2021-12-14 06:58:28 [info] Elementor/Upgrades - _on_each_version Finished 
2021-12-14 06:58:28 [info] Elementor/Upgrades - _v_3_5_0_remove_old_elementor_scheme Start  
2021-12-14 06:58:28 [info] Elementor/Upgrades - _v_3_5_0_remove_old_elementor_scheme Finished 
2021-12-14 06:58:28 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.8',
  'to' => '3.5.0',
)]

PHP: showing 2 of 2PHP: 2021-11-30 11:48:04 [warning X 5][/home/486122.cloudwaysapps.com/guztvuzmbv/public_html/wp-content/plugins/elementor/core/files/manager.php::116] unlink(/home/486122.cloudwaysapps.com/guztvuzmbv/public_html/wp-content/uploads/elementor/css/min): Is a directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-12-09 12:52:47 [error X 3][/home/486122.cloudwaysapps.com/guztvuzmbv/public_html/wp-content/plugins/elementor/core/settings/page/model.php::104] Uncaught Error: Call to a member function get_css_wrapper_selector() on bool in /home/486122.cloudwaysapps.com/guztvuzmbv/public_html/wp-content/plugins/elementor/core/settings/page/model.php:104
Stack trace:
#0 /home/486122.cloudwaysapps.com/guztvuzmbv/public_html/wp-content/plugins/elementor/core/settings/base/css-manager.php(116): Elementor\Core\Settings\Page\Model->get_css_wrapper_selector()
#1 /home/486122.cloudwaysapps.com/guztvuzmbv/public_html/wp-includes/class-wp-hook.php(303): Elementor\Core\Settings\Base\CSS_Manager->add_settings_css_rules()
#2 /home/486122.cloudwaysapps.com/guztvuzmbv/public_html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()
#3 /home/486122.cloudwaysapps.com/guztvuzmbv/public_html/wp-includes/plugin.php(470): WP_Hook->do_action()
#4 /home/486122.cloudwaysapps.com/guztvuzmbv/public_html/wp-content/plugins/elementor/core/files/css/base.php(647): do_action()
#5 /home/486122.cloudwaysapps.com/guztvuzmbv/public_html/wp-content/plugins/elementor/core/files/base.php(141):  [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
```
</details>

**Comment by DorShahar** [comment]
Hi @ocbroadband 

This ain't a bug. This is how **word spacing** works. See here : https://www.w3schools.com/cssref/tryit.asp?filename=trycss_text_word-spacing

In your case, "About us" and "Contact us" are 2 words each, so, `word-spacing` adds a space between the words.

It looks like you need to use Space between or Horizontal padding (under Style > Main menu) for your need.


Thanks
