### ISSUE TITLE
lanuguage failure update

### ISSUE THREAD

**Issue by JohanvdS** [elementor/elementor#17216]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by JohanvdS** [comment]
fatal error: Uncaught Error: Class 'TRX_Addons_Elementor_Widget' not found in /var/sites/t/tvnr.be/public_html/wp-content/plugins/trx_addons/components/api/elementor/elementor.php:1516 Stack trace: #0 /var/sites/t/tvnr.be/public_html/wp-includes/class-wp-hook.php(303): trx_addons_elm_add_params_hide_on_xxx(Object(Elementor\Element_Section), '_section_respon...', Array) #1 /var/sites/t/tvnr.be/public_html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array) #2 /var/sites/t/tvnr.be/public_html/wp-includes/plugin.php(470): WP_Hook->do_action(Array) #3 /var/sites/t/tvnr.be/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(1511): do_action('elementor/eleme...', Object(Elementor\Element_Section), '_section_respon...', Array) #4 /var/sites/t/tvnr.be/public_html/wp-content/plugins/elementor/includes/elements/section.php(1353): Elementor\Controls_Stack->end_controls_section() #5 /var/sites/t/tvnr.be/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(2233): Elementor in /var/sites/t/tvnr.be/public_html/wp-content/plugins/trx_addons/components/api/elementor/elementor.php on line 1516

**Comment by JohanvdS** [comment]
i couldn't find issues on the web :| sorry
