### ISSUE TITLE
🐘 🐞 PHP critical error with PHP 8.0 on Elementor Pro Products Category edit

### ISSUE THREAD

**Issue by seanconklin** [elementor/elementor#17322]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Following is the error and stack trace:

```
2021-12-28T23:23:02+00:00 CRITICAL Uncaught TypeError: strstr(): Argument #1 ($haystack) must be of type string, WP_Error given in /nas/content/live/bestchinese/wp-includes/functions.php:1105
Stack trace:
#0 /nas/content/live/bestchinese/wp-includes/functions.php(1105): strstr(Object(WP_Error), '#')
#1 /nas/content/live/bestchinese/wp-includes/functions.php(1173): add_query_arg('filter_product-...', false, Object(WP_Error))
#2 /nas/content/live/bestchinese/wp-content/plugins/woocommerce/includes/widgets/class-wc-widget-layered-nav.php(423): remove_query_arg('filter_product-...', Object(WP_Error))
#3 /nas/content/live/bestchinese/wp-content/plugins/woocommerce/includes/widgets/class-wc-widget-layered-nav.php(187): WC_Widget_Layered_Nav->layered_nav_list(Array, 'pa_product-type...', 'and')
#4 /nas/content/live/bestchinese/wp-content/plugins/elementor/includes/widgets/wordpress.php(272): WC_Widget_Layered_Nav->widget(Array, Array)
#5 /nas/content/live/bestchinese/wp-content/plugins/elementor/includes/base/controls-stack.php(2172): Elementor\Widget_WordPress->render()
#6 /nas/content/live/bestchinese/wp-content/plugins/elementor/includes/base/widget-base.php(584): Elementor\Controls_Stack->render_by_mode()
#7 /nas/content/live/bestchinese/wp-content/plugins/elementor/includes/base/widget-base.php(708): Elementor\Widget_Base->render_content()
#8 /nas/content/live/bestchinese/wp-content/plugins/elementor/includes/base/element-base.php(534): Elementor\Widget_Base->get_raw_data(true)
#9 /nas/content/live/bestchinese/wp-content/plugins/elementor/includes/base/element-base.php(534): Elementor\Element_Base->get_raw_data(true)
#10 /nas/content/live/bestchinese/wp-content/plugins/elementor/core/base/document.php(876): Elementor\Element_Base->get_raw_data(true)
#11 /nas/content/live/bestchinese/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(397): Elementor\Core\Base\Document->get_elements_raw_data(Array, true)
#12 /nas/content/live/bestchinese/wp-content/plugins/elementor/core/base/document.php(553): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document->get_elements_raw_data(NULL, true)
#13 /nas/content/live/bestchinese/wp-content/plugins/elementor/modules/library/documents/library-document.php(69): Elementor\Core\Base\Document->get_initial_config()
#14 /nas/content/live/bestchinese/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(621): Elementor\Modules\Library\Documents\Library_Document->get_initial_config()
#15 /nas/content/live/bestchinese/wp-content/plugins/elementor/includes/base/controls-stack.php(997): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document->get_initial_config()
#16 /nas/content/live/bestchinese/wp-content/plugins/elementor/core/editor/editor.php(522): Elementor\Controls_Stack->get_config()
#17 /nas/content/live/bestchinese/wp-includes/class-wp-hook.php(303): Elementor\Core\Editor\Editor->enqueue_scripts('')
#18 /nas/content/live/bestchinese/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#19 /nas/content/live/bestchinese/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#20 /nas/content/live/bestchinese/wp-includes/script-loader.php(2083): do_action('wp_enqueue_scri...')
#21 /nas/content/live/bestchinese/wp-includes/class-wp-hook.php(303): wp_enqueue_scripts('')
#22 /nas/content/live/bestchinese/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#23 /nas/content/live/bestchinese/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#24 /nas/content/live/bestchinese/wp-includes/general-template.php(3015): do_action('wp_head')
#25 /nas/content/live/bestchinese/wp-content/plugins/elementor/includes/editor-templates/editor-wrapper.php(31): wp_head()
#26 /nas/content/live/bestchinese/wp-content/plugins/elementor/core/editor/editor.php(317): include('/nas/content/li...')
#27 /nas/content/live/bestchinese/wp-content/plugins/elementor/core/editor/editor.php(158): Elementor\Core\Editor\Editor->print_editor_template()
#28 /nas/content/live/bestchinese/wp-includes/class-wp-hook.php(303): Elementor\Core\Editor\Editor->init('')
#29 /nas/content/live/bestchinese/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#30 /nas/content/live/bestchinese/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#31 /nas/content/live/bestchinese/wp-admin/admin.php(408): do_action('admin_action_el...')
#32 /nas/content/live/bestchinese/wp-admin/post.php(12): require_once('/nas/content/li...')
#33 {main}
  thrown in /nas/content/live/bestchinese/wp-includes/functions.php on line 1105
```

## Steps to reproduce

1. Using WP Engine environment running PHP 7.4, click the button under my.wpengine.com within the site "PHP Test Driver" for PHP 8.0. Or use an environment already running PHP 8.0
2. If not already, set-up WooCommerce and a Products Archive template in Elementor Pro with applicable display condition so it is displaying on the site.
3. Open a product category page on your website.
4. Hover over the "Edit with Elementor" menu and select the name of your Products Archive template.
5. Observe PHP fatal error: "There has been a critical error on this website. Please check your site admin email inbox for instructions. Learn more about troubleshooting WordPress."
6. If you used the WP Engine PHP 8.0 preview, you may clear your cookies to switch back to PHP 7.4, log back into the site, and repeat steps 3 and 4 to see the error go away with PHP 7.4

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>Click to reveal</summary>

````txt

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release '38', Revision '3692a61' v5.7.35-38
	PHP Version: 8.0.13
	PHP Max Input Vars: 10000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.8.2
	Site URL: https://bestchinesemedicines.com
	Home URL: https://bestchinesemedicines.com
	WP Multisite: No
	Max Upload Size: 50 MB
	Memory limit: 512M
	Permalink Structure: /blog/%postname%/
	Language: en-US
	Timezone: America/Los_Angeles
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.4.2
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:95.0) Gecko/20100101 Firefox/95.0

== Active Plugins ==
	Advanced Custom Fields
		Version: 5.11.4
		Author: Delicious Brains

	Akismet Anti-Spam
		Version: 4.2.1
		Author: Automattic

	Cloudflare
		Version: 4.7.0
		Author: Cloudflare, Inc.

	Code Snippets
		Version: 2.14.3
		Author: Code Snippets Pro

	Elementor
		Version: 3.5.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.8
		Author: Elementor.com

	Facebook for WooCommerce
		Version: 2.6.8
		Author: Facebook

	Google Tag Manager for WooCommerce PRO
		Version: 1.5.2
		Author: Handcraft Byte

	Judge.me Product Reviews for WooCommerce
		Version: 1.3.12
		Author: Judge.me

	Klaviyo
		Version: 2.5.5
		Author: Klaviyo, Inc.

	Redirection
		Version: 5.1.3
		Author: John Godley

	Reviews for Schema
		Version: 1.24
		Author: Magazine3

	SASWP Pro Extension Manager
		Version: 1.2.8
		Author: Schema & Structured Data Team

	Schema & Structured Data for WP & AMP
		Version: 1.9.92
		Author: Magazine3

	Smart WooCommerce Search by Searchanise
		Version: 1.0.8
		Author: Searchanise

	User Role Editor
		Version: 4.61
		Author: Vladimir Garagulya

	WooCommerce
		Version: 5.9.0
		Author: Automattic

	WooCommerce - ShipStation Integration
		Version: 4.1.48
		Author: WooCommerce

	WooCommerce Stripe Gateway
		Version: 5.9.0
		Author: WooCommerce

	WP-Optimize - Clean, Compress, Cache
		Version: 3.2.1
		Author: David Anderson, Ruhani Rabin, Team Updraft

	WP Engine Smart Plugin Manager
		Version: 5.9.0
		Author: WP Engine

	YITH WooCommerce Frequently Bought Together Premium
		Version: 1.12.0
		Author: YITH

	YITH WooCommerce Quick View Premium
		Version: 1.5.3
		Author: YITH

	Yoast SEO
		Version: 17.8
		Author: Team Yoast

	Yoast SEO: WooCommerce
		Version: 13.8
		Author: Team Yoast

	Zoho Mail
		Version: 1.4.7
		Author: Zoho Mail


== Must-Use Plugins ==
	Force Strong Passwords - WPE Edition
		Version: 1.8.0
		Author: Jason Cosper

	WPE ElasticPress Autosuggest Logger
		Version: 1.0.0
		Author: WP Engine

	WP Engine Cache Plugin
		Version: 1.0.5
		Author: WP Engine

	WP Engine Seamless Login Plugin
		Version: 1.5.5
		Author: WP Engine

	WP Engine Security Auditor
		Version: 1.0.10
		Author: wpengine

	WP Engine System
		Version: 5.0.1
		Author: WP Engine


== Elements Usage ==
	
	archive : 2
		archive-posts : 2
		author-box : 1
		heading : 2
		html : 1
		image : 1
		text-editor : 2
	footer : 3
		heading : 2
		icon-list : 1
		nav-menu : 4
		social-icons : 1
		spacer : 1
		text-editor : 5
	header : 3
		image : 1
		nav-menu : 1
		search-form : 1
		text-editor : 3
		woocommerce-menu-cart : 1
	product : 2
		divider : 2
		heading : 12
		icon-list : 2
		posts : 2
		share-buttons : 2
		shortcode : 6
		spacer : 8
		tabs : 1
		toggle : 1
		woocommerce-breadcrumb : 2
		woocommerce-product-add-to-cart : 2
		woocommerce-product-content : 2
		woocommerce-product-data-tabs : 2
		woocommerce-product-images : 2
		woocommerce-product-price : 2
		woocommerce-product-related : 2
		woocommerce-product-short-description : 2
		woocommerce-product-title : 2
		woocommerce-product-upsell : 2
	section : 3
		heading : 2
		html : 1
		posts : 1
		spacer : 4
		wp-widget-categories : 1
	single : 2
		author-box : 2
		breadcrumbs : 1
		heading : 8
		html : 1
		post-comments : 1
		post-info : 1
		posts : 1
		share-buttons : 1
		spacer : 3
		theme-post-content : 1
		theme-post-title : 1
		wp-widget-categories : 1
	wp-post : 42
		divider : 80
		form : 1
		heading : 562
		html : 1
		icon-box : 4
		icon-list : 41
		posts : 2
		shortcode : 1
		spacer : 218
		template : 8
		text-editor : 1014
		theme-page-title : 4
		video : 12
		woocommerce-products : 207
		wp-widget-categories : 1
	wp-page : 22
		blockquote : 3
		button : 4
		form : 1
		heading : 53
		html : 8
		icon : 5
		icon-list : 2
		image : 11
		image-box : 3
		nav-menu : 1
		posts : 1
		search-form : 1
		share-buttons : 1
		shortcode : 3
		social-icons : 1
		spacer : 51
		star-rating : 3
		template : 1
		text-editor : 60
		theme-archive-title : 1
		toggle : 2
		wc-categories : 2
		woocommerce-menu-cart : 1
		woocommerce-products : 9
	product-archive : 4
		button : 2
		heading : 8
		html : 2
		image : 7
		shortcode : 1
		spacer : 4
		text-editor : 6
		theme-archive-title : 1
		wc-archive-products : 4
		woocommerce-archive-description : 1
		wp-widget-woocommerce_layered_nav : 2
		wp-widget-woocommerce_layered_nav_filters : 1


== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Inactive
	Inline Font Icons: Inactive
	Accessibility Improvements: Active
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Inactive by default
	Hide native WordPress widgets from search results: Active by default
	Hello Theme Header & Footer: Inactive by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default


== Log ==
	
Log: showing 20 of 362021-12-16 10:15:40 [info] Elementor/Upgrades - _on_each_version Start  
2021-12-16 10:15:40 [info] Elementor/Upgrades - _on_each_version Finished 
2021-12-16 10:15:40 [info] Elementor/Upgrades - _v_3_4_8_fix_font_awesome_default_value_from_1_to_yes Start  
2021-12-16 10:15:40 [info] Elementor/Upgrades - _v_3_4_8_fix_font_awesome_default_value_from_1_to_yes Finished 
2021-12-16 10:15:40 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.8',
  'to' => '3.5.0',
)]
2021-12-21 00:18:46 [info] elementor::elementor_updater Started 
2021-12-21 00:18:46 [info] Elementor/Upgrades - _on_each_version Start  
2021-12-21 00:18:47 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.0',
  'to' => '3.5.1',
)]
2021-12-21 00:18:47 [info] Elementor/Upgrades - _on_each_version Finished 
2021-12-21 00:18:47 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.0',
  'to' => '3.5.1',
)]
2021-12-23 00:00:06 [info] elementor::elementor_updater Started 
2021-12-23 00:00:06 [info] Elementor/Upgrades - _on_each_version Start  
2021-12-23 00:00:06 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.1',
  'to' => '3.5.2',
)]
2021-12-23 00:00:07 [info] Elementor/Upgrades - _on_each_version Finished 
2021-12-23 00:00:07 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.1',
  'to' => '3.5.2',
)]
2021-12-28 13:02:54 [info] elementor::elementor_updater Started 
2021-12-28 13:02:54 [info] Elementor/Upgrades - _on_each_version Start  
2021-12-28 13:02:55 [info] Elementor/Upgrades - _on_each_version Finished 
2021-12-28 13:02:55 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.2',
  'to' => '3.5.3',
)]
2021-12-28 13:02:55 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.2',
  'to' => '3.5.3',
)]

PHP: showing 6 of 6PHP: 2021-10-19 13:02:05 [notice X 438][../wp-content/plugins/elementor-pro/license/updater.php::85] Undefined index: new_version [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-10-19 13:20:23 [notice X 61][../wp-content/plugins/elementor-pro/modules/forms/classes/form-record.php::183] Undefined index: referrer [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-12-16 10:28:17 [notice X 1][../wp-content/plugins/elementor/includes/managers/image.php::87] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-12-23 11:40:06 [notice X 1][../wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-12-28 14:20:31 [warning X 3][../wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-12-28 14:38:16 [warning X 4][../wp-content/plugins/elementor-pro/license/updater.php::85] Undefined array key "new_version" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
				
```
</details>

**Comment by seanconklin** [comment]
Confirmed this is still reproducing with Elementor 3.5.5 and Elementor Pro 3.6.2.

**Comment by seanconklin** [comment]
I've reproduced this on local host as well running PHP 8.0.0 and the Hello Elementor theme and no other plugins enabled, just Elementor 3.6.2 + Elementor Pro 3.6.4 + WooCommerce. I tried the Elementor > Settings > Advanced > Switch Editor Loader Method, and Elementor > Tools > General > Safe Mode, and these had no effect.

**Comment by seanconklin** [comment]
I did some further testing on this in sandbox looking at PHP X-debug. I've isolated it to the product archive template including the product attributes widget. So in order to reproduce this PHP 8.0 crash you must add the "Filter Products By Attribute" WooCommerce widget in your Elementor Products Archive template.

![Screen Shot 2022-04-28 at 3 27 48 PM](https://user-images.githubusercontent.com/19829621/165858589-00dd3697-2ee2-42d1-96ed-eece6b095cbe.png)

**Comment by seanconklin** [comment]
Reproduced with today's Elementor Pro v3.7.0. I've opened a fourth support ticket on the matter too. I'm 100% sure Elementor does not use GitHub Issues based on this and a Yoast SEO WooCommerce plugin conflict I ran into separately and seeing that ticket go unaddressed years on. The community provided a fix to that one, so I'll provide updates here for anybody facing the same trouble.

**Comment by seanconklin** [comment]
Confirmed this is still reproducing with Elementor Version 3.6.6 + Elementor Pro Version 3.7.2 and this is the only non PHP 8.0 compliant plugin that we have on the site, holding us back.

**Comment by Jmp6123** [comment]
Has anyone fixed this issue? Im running woocommerce 6.9.4, wordpress 6.0.3, Elementor 3.7.8 & Elementor Pro 3.7.7 and my site keeps crashing when trying to update to PHP 8.0.

Thank you!

**Comment by seanconklin** [comment]
I had a ticket in with Elementor Pro support. Elementor responded that it was traced to corruption in the template with no further details. I don't think they ever fixed the root cause. However I came-up with a workaround: I made a new template that initially worked then found the trigger to be the Preview setting, which brought back the crash. I unset that and completed the PHP 8.0 upgrade successfully. I asked Elementor to truly fix it though, meanwhile we can clear that Preview setting (gear icon lower-left, preview settings, unset any values here, save, then upgrade to PHP 8.0).

**Comment by awebguy99** [comment]
Did they ever fix this?
PHP 7.4 is now **End of Life and "may be exposed to unpatched security vulnerabilities"**
https://www.php.net/supported-versions.php

**Comment by seanconklin** [comment]
I sure hope they've fixed it by now, but I don't know. Somebody would have to set this up and test to know for sure. Personally I've moved on to Blocks and Full Site Editing in core - replacing Elementor everywhere that I find it.

If you're still reproducing this bug then you can try my workaround (Set to PHP 7.4, edit template, gear icon lower-left, preview settings, unset any values here, save, then upgrade to PHP 8.0).

**Comment by netinstinct** [comment]
Hello Elementor,
I am having the same issue still almost a year later?
I only installed Hello Theme, a single page with a Title and one background image. 

Critical Error message every time. Have to switch back to the unsecure 7.4.

**Comment by Michaelgimii** [comment]
Hi @nicholaszein, Are you aware of this?

**Comment by MrGKanev** [comment]
The issue still persists to this day ...

**Comment by FlourishDesignStudio** [comment]
I have this issue as well! And it's not June 2023! Has anyone been able to get it resolved?

**Comment by KingYes** [comment]
Hi, I want to try to fix it, but I cannot reproduce it in my local environment. Can you explain what you are trying to do and how to get this error?
