### ISSUE TITLE
Custom post types not showing up in condition settings/Cannot set conditions in templates

### ISSUE THREAD

**Issue by mitchellsl** [elementor/elementor#17395]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest development version of Elementor.

## Description

When adding a custom post type with either, JetEngine or CPT UI I am unable to link the post type to a previously build template for that specific post type. It does not show my post type in the dropdown (see attached screenshot). I have checked every setting from enabling it in the Elementor settings, from removing and re-adding the post type numerous times
, nothing seems to work. Although it has worked within a dev version, but when i roll back to a previous version it still doesn't show up.
![Schermafbeelding 2022-01-06 om 10 52 37](https://user-images.githubusercontent.com/82220524/148365540-a98e0a0c-42ef-4752-87d0-7843a05c064f.png)

Another issue i'am experiencing which is very annoying, is that I am unable to set my display conditions for pop-ups and every other element. (see attached screenshot)

The condition modal shows but I am unable to see any options, let alone click them. 
![Schermafbeelding 2022-01-06 om 10 57 22](https://user-images.githubusercontent.com/82220524/148365500-e7761ad9-bdbf-46f2-ab74-cfa9e7ee2dbe.png)

## Steps to reproduce

**Custom post types not showing up in condition settings**

- Have Elementor 3.6.0-dev-25 or below installed
- Make custom post type with either, JetEngine or CPT UI
- Build single post template, and try and set conditions where to display said template

Cannot set conditions in templates

- Build for example a pop-up, and set conditions
- The condition modal is showing, but you cannot set any conditions for said pop-up

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [x] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [x] I can reproduce this bug consistently using the steps above.

## Environment

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v5.5.61-MariaDB-38.13
	PHP Version: 7.4.27
	PHP Max Input Vars: 1000
	PHP Max Post Size: 1G
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.8.2
	Site URL: https://slelementor.devlane.nl
	Home URL: https://slelementor.devlane.nl
	WP Multisite: No
	Max Upload Size: 1 GB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Europe/Amsterdam
	Admin Email: mitch@sociallane.nl
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.4.2
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36

== Active Plugins ==
	Custom CSS and JavaScript
		Version: 2.0.11
		Author: Aspen Grove Studios

	Custom Permalinks
		Version: 2.4.0
		Author: Sami Ahmed Siddiqui

	Custom Post Type UI
		Version: 1.10.1
		Author: WebDevStudios

	Duplicate Menu
		Version: 0.2.2
		Author: Jonathan Christopher

	Duplicate Page
		Version: 4.4.7
		Author: mndpsingh287

	Duplicator
		Version: 1.4.3
		Author: Snap Creek

	Ele Custom Skin
		Version: 3.1.4
		Author: Dudaster.com

	Elementor
		Version: 3.6.0-dev21
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.0-dev2
		Author: Elementor.com

	Elementor White Label Branding
		Version: 1.0.2
		Author: Ozan Canakli

	JetBlocks For Elementor
		Version: 1.3.0
		Author: Crocoblock

	JetElements For Elementor
		Version: 2.6.1
		Author: Crocoblock

	JetEngine
		Version: 2.10.3
		Author: Crocoblock

	JetEngine - Custom visibility conditions
		Version: 1.1.0
		Author: Crocoblock

	JetSearch For Elementor
		Version: 2.1.15
		Author: Crocoblock

	JetTabs For Elementor
		Version: 2.1.15
		Author: Crocoblock

	Schema & Structured Data for WP & AMP
		Version: 1.9.92
		Author: Magazine3

	WebP Express
		Version: 0.25.0
		Author: Bjørn Rosell

	WP Fastest Cache
		Version: 0.9.7
		Author: Emre Vona

	WP Rollback
		Version: 1.7.0
		Author: Impress.org

	Yoast Duplicate Post
		Version: 4.3
		Author: Enrico Battocchi & Team Yoast

	Yoast SEO
		Version: 17.8
		Author: Team Yoast

== Elements Usage ==
	
	archive : 2
		button : 1
		container : 12
		icon : 1
		image : 1
		jet-listing-grid : 1
		nav-menu : 1
		posts : 1
		text-editor : 3
		theme-site-logo : 2
	container : 12
		button : 1
		container : 54
		heading : 8
		icon : 1
		icon-box : 9
		icon-list : 1
		image : 7
		jet-engine-booking-form : 1
		jet-listing-grid : 1
		jet-tabs : 1
		text-editor : 17
	footer : 1
		button : 1
		container : 15
		form : 1
		heading : 4
		icon-list : 4
		image : 1
		jet-listing-dynamic-terms : 1
		jet-listing-grid : 1
		nav-menu : 1
		text-editor : 6
	header : 2
		button : 1
		container : 11
		form : 1
		icon : 2
		image : 1
		jet-breadcrumbs : 2
		nav-menu : 1
		spacer : 2
		text-editor : 3
		theme-site-logo : 3
	loop : 4
		container : 3
		heading : 1
		jet-button : 1
		jet-listing-dynamic-field : 1
		theme-post-excerpt : 3
		theme-post-featured-image : 1
		theme-post-title : 2
	page : 10
		breadcrumbs : 1
		button : 17
		container : 161
		heading : 16
		icon : 5
		icon-list : 2
		image : 32
		image-carousel : 2
		jet-listing-dynamic-field : 14
		jet-listing-dynamic-image : 2
		jet-listing-grid : 2
		jet-tabs : 2
		spacer : 6
		text-editor : 107
		theme-site-logo : 1
	popup : 3
		container : 3
		google_maps : 1
		heading : 2
		icon-list : 1
		nav-menu : 4
	section : 8
		button : 3
		heading : 1
		icon-list : 1
		image : 5
		jet-listing-dynamic-field : 4
		jet-listing-dynamic-image : 1
		text-editor : 17
	widget : 0
		button : 1
		icon-list : 1
		jet-engine-booking-form : 1
		jet-listing-grid : 2
	wp-post : 0
		breadcrumbs : 1
		button : 2
		container : 3
		icon : 1
		image : 1
		jet-listing-dynamic-field : 19
		jet-listing-dynamic-image : 2
		jet-listing-grid : 1
		text-editor : 3
		theme-site-logo : 1
	wp-page : 59
		breadcrumbs : 1
		button : 60
		container : 839
		counter : 4
		form : 4
		heading : 111
		icon : 12
		icon-box : 36
		icon-list : 24
		image : 85
		image-carousel : 1
		image-gallery : 1
		jet-engine-booking-form : 13
		jet-engine-profile-menu : 1
		jet-listing-dynamic-field : 6
		jet-listing-grid : 7
		jet-tabs : 14
		nav-menu : 2
		posts : 2
		price-table : 3
		share-buttons : 2
		text-editor : 375
		theme-site-logo : 4
	single-post : 6
		button : 3
		container : 77
		heading : 11
		icon : 5
		image : 4
		jet-breadcrumbs : 2
		jet-listing-dynamic-field : 30
		jet-listing-dynamic-image : 2
		nav-menu : 2
		share-buttons : 1
		spacer : 2
		template : 1
		text-editor : 10
		theme-post-content : 1
		theme-site-logo : 4
		wp-widget-recent-posts : 1
	single-page : 3
		container : 13
		heading : 4
		icon : 1
		image : 4
		text-editor : 11
	search-results : 1
		container : 1
		jet-listing-grid : 1
	jet-listing-items : 0
		button : 3
		container : 8
		image : 1
		jet-listing-dynamic-field : 10
		jet-listing-dynamic-image : 1
		wp-widget-recent-posts : 1

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Inactive
	Import Export Template Kit: Inactive
	Additional Custom Breakpoints: Inactive
	Hide native WordPress widgets from search results: Inactive
	Container: Active
	: Inactive by default
	Default to New Theme Builder: Active
	Hello Theme Header & Footer: Inactive
	Landing Pages: Active
	Color Sampler: Inactive
	Favorite Widgets: Inactive
	Admin Top Bar: Active
	Custom Default Widget Styles: Inactive
	Page Transitions: Inactive
	Form Submissions: Active by default
	Scroll Snap: Inactive

== Log ==
	
Log: showing 20 of 332021-12-30 14:51:48 [info] elementor::elementor_updater Started 
2021-12-30 14:51:49 [info] BoilerLane/Upgrades - _on_each_version Start  
2021-12-30 14:51:52 [info] BoilerLane/Upgrades - _on_each_version Finished 
2021-12-30 14:51:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'BoilerLane',
  'from' => '3.6.0-dev21',
  'to' => '3.6.0-dev24',
)]
2022-01-03 10:54:15 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'BoilerLane',
  'from' => '3.6.0-dev24',
  'to' => '3.6.0-dev25',
)]
2022-01-03 10:54:15 [info] elementor::elementor_updater Started 
2022-01-03 10:54:15 [info] BoilerLane/Upgrades - _on_each_version Start  
2022-01-03 10:54:16 [info] BoilerLane/Upgrades - _on_each_version Finished 
2022-01-03 10:54:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'BoilerLane',
  'from' => '3.6.0-dev24',
  'to' => '3.6.0-dev25',
)]
2022-01-06 11:16:24 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.0-dev20',
  'to' => '3.7.0-dev2',
)]
2022-01-06 11:16:24 [info] elementor-pro::elementor_pro_updater Started 
2022-01-06 11:16:24 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-01-06 11:16:24 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-01-06 11:16:24 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.0-dev20',
  'to' => '3.7.0-dev2',
)]
2022-01-06 11:16:26 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.0-dev20',
  'to' => '3.7.0-dev2',
)]
2022-01-06 11:18:49 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'BoilerLane',
  'from' => '3.6.0-dev25',
  'to' => '3.6.0-dev26',
)]
2022-01-06 11:18:49 [info] elementor::elementor_updater Started 
2022-01-06 11:18:49 [info] BoilerLane/Upgrades - _on_each_version Start  
2022-01-06 11:18:52 [info] BoilerLane/Upgrades - _on_each_version Finished 
2022-01-06 11:18:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'BoilerLane',
  'from' => '3.6.0-dev25',
  'to' => '3.6.0-dev26',
)]

PHP: showing 9 of 9PHP: 2021-12-23 11:58:21 [error X 1][/var/www/vhosts/devlane.nl/slelementor.devlane.nl/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::286] Uncaught Error: Call to a member function update_meta() on bool in /var/www/vhosts/devlane.nl/slelementor.devlane.nl/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:286
Stack trace:
#0 /var/www/vhosts/devlane.nl/slelementor.devlane.nl/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions()
#2 /var/www/vhosts/devlane.nl/slelementor.devlane.nl/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func()
#3 /var/www/vhosts/devlane.nl/slelementor.devlane.nl/wp-includes/class-wp-hook.php(303): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#4 /var/www/vhosts/devlane.nl/slelementor.devlane.nl/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()
#5 /var/www/vhosts/devlane.nl/slelementor.devl [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-12-23 13:58:53 [notice X 1][/var/www/vhosts/devlane.nl/slelementor.devlane.nl/wp-content/plugins/elementor-pro/modules/forms/classes/ajax-handler.php::260] Undefined index: post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-12-30 15:10:29 [notice X 47][/var/www/vhosts/devlane.nl/slelementor.devlane.nl/wp-content/plugins/elementor/core/base/document.php::210] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-12-30 15:37:26 [error X 14][/var/www/vhosts/devlane.nl/slelementor.devlane.nl/wp-content/plugins/elementor/data/v2/base/controller.php::227] Uncaught Elementor\Data\V2\Base\Exceptions\WP_Error_Exception: Method 'WP_REST_Controller::get_item_permissions_check' not implemented. Must be overridden in subclass. in /var/www/vhosts/devlane.nl/slelementor.devlane.nl/wp-content/plugins/elementor/data/v2/base/controller.php:227
Stack trace:
#0 /var/www/vhosts/devlane.nl/slelementor.devlane.nl/wp-content/plugins/elementor/data/v2/base/base-route.php(105): Elementor\Data\V2\Base\Controller->get_permission_callback()
#1 /var/www/vhosts/devlane.nl/slelementor.devlane.nl/wp-content/plugins/elementor/data/v2/base/base-route.php(242): Elementor\Data\V2\Base\Base_Route->get_permission_callback()
#2 /var/www/vhosts/devlane.nl/slelementor.devlane.nl/wp-includes/rest-api/class-wp-rest-server.php(1107): Elementor\Data\V2\Base\Base_Route->Elementor\Data\V2\Base\{closure}()
#3 /var/www/vhosts/devlane.nl/slelementor.devlane.nl/wp-includes/rest-api/class-wp-rest-server.php(987): WP_REST_Server->respond_to_request()
#4 /var/www/vhosts/devlane.nl/slelementor.devlane.nl/wp-i [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-03 11:11:13 [error X 15][/var/www/vhosts/devlane.nl/slelementor.devlane.nl/wp-content/plugins/elementor-pro/base/base-widget-trait.php::26] Uncaught Error: Call to undefined method ElementorPro\Modules\ThemeBuilder\Widgets\Site_Logo::is_custom_breakpoints_widget() in /var/www/vhosts/devlane.nl/slelementor.devlane.nl/wp-content/plugins/elementor-pro/base/base-widget-trait.php:26
Stack trace:
#0 /var/www/vhosts/devlane.nl/slelementor.devlane.nl/wp-content/plugins/elementor-pro/base/base-widget-trait.php(48): ElementorPro\Modules\ThemeBuilder\Widgets\Site_Logo->get_widget_css_config()
#1 /var/www/vhosts/devlane.nl/slelementor.devlane.nl/wp-content/plugins/elementor/includes/base/widget-base.php(1038): ElementorPro\Modules\ThemeBuilder\Widgets\Site_Logo->get_css_config()
#2 /var/www/vhosts/devlane.nl/slelementor.devlane.nl/wp-content/plugins/elementor/includes/base/widget-base.php(1078): Elementor\Widget_Base->get_widget_css()
#3 /var/www/vhosts/devlane.nl/slelementor.devlane.nl/wp-content/plugins/elementor/includes/base/widget-base.php(596): Elementor\Widget_Base->print_widget_css()
#4 /var/www/vhosts/devlane.nl/slelementor.devlane.nl/wp-content/plu [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-03 11:50:54 [notice X 21][/var/www/vhosts/devlane.nl/slelementor.devlane.nl/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-03 15:59:09 [notice X 1][/var/www/vhosts/devlane.nl/slelementor.devlane.nl/wp-content/plugins/elementor/core/experiments/experiments-reporter.php::89] Undefined index: title [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-03 16:53:24 [warning X 1][/var/www/vhosts/devlane.nl/slelementor.devlane.nl/wp-content/plugins/elementor-beta/modules/developer-edition/core-version-control.php::79] Creating default object from empty value [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-04 09:23:35 [notice X 1][/var/www/vhosts/devlane.nl/slelementor.devlane.nl/wp-content/plugins/elementor-pro/modules/query-control/module.php::764] Trying to get property 'hierarchical' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== BoilerLane - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	Elementor White Label Branding: Compatibility not specified
	JetBlocks For Elementor: Compatibility not specified
	JetElements For Elementor: Compatibility not specified
	JetSearch For Elementor: Compatibility not specified
	JetTabs For Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==
	

				

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by gilesholder** [comment]
Have you got heirarchy enabled in CPT UI? Also in elementor settings make sure the post type is ticked. Works in my sites fine.

**Comment by mitchellsl** [comment]
Hi,

Yes I have got al these settings correctly set up. And it still does not work. With every other version of Elementor outside the dev version, I am not experiencing any problems.

Met vriendelijke groet,


Mitchell Kamp
Webdesigner | Web Developer

Tel: 070 322 90 83
Hellingweg 98 K
2583 WH Den Haag
https://sociallane.nl/

Disclaimer: De inhoud van dit bericht en de eventueel daarbij behorende bijlagen zijn persoonlijk gericht aan en derhalve uitsluitend bestemd voor de geadresseerde. Zij kunnen gegevens met betrekking tot een derde bevatten. De ontvanger die niet de geadresseerde is, noch bevoegd is dit bericht namens geadresseerde te ontvangen, wordt verzocht de afzender onmiddellijk op de hoogte te stellen van de ontvangst. Elk gebruik van de inhoud van dit bericht en/of van de daarbij behorende bijlagen door een ander dan de geadresseerde is onrechtmatig jegens afzender respectievelijk de hiervoor bedoelde derde.
On 7 Jan 2022, 11:47 +0100, gilesholder ***@***.***>, wrote:
> Have you got heirarchy enabled in CPT UI? Also in elementor settings make sure the post type is ticked. Works in my sites fine.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.
> You are receiving this because you authored the thread.Message ID: ***@***.***>

-- 

*Disclaimer: *De inhoud van dit bericht en de eventueel daarbij behorende 
bijlagen zijn persoonlijk gericht aan en derhalve uitsluitend bestemd voor 
de geadresseerde. Zij kunnen gegevens met betrekking tot een derde 
bevatten. De ontvanger die niet de geadresseerde is, noch bevoegd is dit 
bericht namens geadresseerde te ontvangen, wordt verzocht de afzender 
onmiddellijk op de hoogte te stellen van de ontvangst. Elk gebruik van de 
inhoud van dit bericht en/of van de daarbij behorende bijlagen door een 
ander dan de geadresseerde is onrechtmatig jegens afzender respectievelijk 
de hiervoor bedoelde derde.

**Comment by nadworks** [comment]
Has this been resolved? I am experiencing the exact same problem.

**Comment by jonasdaouani** [comment]
2025 and still an issue on my end
