### ISSUE TITLE
Call To Action widget not displaying image

### ISSUE THREAD

**Issue by digitalpasskey** [elementor/elementor#17470]
- [ X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ X] The issue still exists against the latest stable version of Elementor.

## Description

Call To Action widget was working fine with current site until today 12 Jan 2022, when image background stopped displaying on all devices and browsers. Custom styling (font colour, button settings etc) also no longer working. Clearing cookies and cache has no effect. Adding a brand new CTA widget and styling from scratch also has no effect. All other elements and sections on the site are working fine, the problem appears to be isolated to the CTA widget. As the Elementor CTA is currently not working, I have since installed the Call to Action (CTA) Box Animate plugin as a temporary fix, however this was not installed when the issue first occured so cannot be the cause of the problem.

## Isolating the problem

- [X ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X ] This bug happens with a default WordPress theme active.
- [ X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.32-35
	PHP Version: 7.4.27
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.8.3
	Site URL: http://stephend73.sg-host.com
	Home URL: http://stephend73.sg-host.com
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: info@digitalpasskey.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.4.2
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36

== Active Plugins ==
	All-in-One WP Migration
		Version: 7.52
		Author: ServMask

	Elementor
		Version: 3.5.3
		Author: Elementor.com

	Elementor Call to Action (CTA) Box Animate
		Version: 1.0.3
		Author: InternetCSS

	Elementor Pro
		Version: 3.5.2
		Author: Elementor.com

	Premium Addons for Elementor
		Version: 4.8.2
		Author: Leap13

	SiteGround Optimizer
		Version: 6.0.5
		Author: SiteGround

	SiteGround Security
		Version: 1.1.3
		Author: SiteGround

	Widgets for Google Reviews
		Version: 7.8
		Author: Trustindex.io <support@trustindex.io>


== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Form Submissions: Active by default
	Scroll Snap: Inactive by default


== Log ==
	
PHP: showing 4 of 4PHP: 2021-11-30 10:22:12 [notice X 2][/home/customer/www/stephend63.sg-host.com/public_html/wp-content/plugins/elementor-pro/license/updater.php::83] Undefined index: new_version [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-12-15 08:08:40 [notice X 4][/home/customer/www/stephend63.sg-host.com/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-12-28 15:25:48 [error X 1][/home/customer/www/stephend63.sg-host.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::286] Uncaught Error: Call to a member function update_meta() on null in /home/customer/www/stephend63.sg-host.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:286
Stack trace:
#0 /home/customer/www/stephend63.sg-host.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(5, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/customer/www/stephend63.sg-host.com/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/customer/www/stephend63.sg-host.com/public_html/wp-includes/class-wp-hook.php(303): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/custom [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-12-28 19:06:22 [notice X 13][/home/customer/www/stephend63.sg-host.com/public_html/wp-content/plugins/elementor-pro/modules/forms/classes/form-base.php::55] Undefined index: required [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 1 of 1JS: 2021-11-30 13:47:26 [error X 4][http://stephend63.sg-host.com/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.4.8:2:16782] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got as `ma_el_main_image_icon` value. Expected array or object.',
)]

Log: showing 12 of 122022-01-07 22:24:52 [info] elementor::elementor_updater Started 
2022-01-07 22:24:52 [info] Elementor/Upgrades - _on_each_version Start  
2022-01-07 22:24:52 [info] Elementor/Upgrades - _on_each_version Finished 
2022-01-07 22:24:52 [info] Elementor/Upgrades - _v_3_5_0_remove_old_elementor_scheme Start  
2022-01-07 22:24:52 [info] Elementor/Upgrades - _v_3_5_0_remove_old_elementor_scheme Finished 
2022-01-07 22:24:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.8',
  'to' => '3.5.3',
)]
2022-01-07 22:24:52 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.8',
  'to' => '3.5.3',
)]
2022-01-08 17:13:53 [info] elementor-pro::elementor_pro_updater Started 
2022-01-08 17:13:53 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-01-08 17:13:53 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-01-08 17:13:53 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.5.1',
  'to' => '3.5.2',
)]
2022-01-08 17:13:53 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.5.1',
  'to' => '3.5.2',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Call to Action (CTA) Box Animate: Compatibility not specified
	Elementor Pro: Compatible
	Premium Addons for Elementor: Compatible

== Elementor Pro - Compatibility Tag ==
	
	Premium Addons for Elementor: Compatible
				
```
</details>

**Comment by ZEEFAHDESK** [comment]
I have the same issue with CTA widget in Elementor. May please help to sort out the issue.

**Comment by ScottMStubbs** [comment]
This CTA issue seemed to be corrected temporarily with the "Improved CSS Loading = disabled" solution, but I noticed the issue has returned again. Enabling or Disabling doesn't seem to change anything anymore. Anyone have any other solutions by chance? I hate to rebuild the whole area to get around it, but If I must, I must.

**Comment by bruceburstein** [comment]
I experienced the same.  Elementor Call to Action (CTA) provides a nice hover effect but the image vaporizes in Safari 14.1 (Big Sur 11.6) and on iOS.  I initiated thought it was my use of WebP format but conversion of images did not correct.

Resolution:
I did a test to see if it was Elementor CTA.  I put the same image in a plain image frame just above the CTA image ----- Whoa, walla, the CTA image appeared on Safari.

Next, I hid the plain image (Advanced, Responsive, turned all OFF) and the image still appeared in Safari (and Chrome, of course).  I don't know how long this will last but I've refreshed a few times and the CTA image is up.

**Comment by rirakeeb** [comment]
I have solved it in this way ... elementor ➤ settings ➤ Features ➤ Lazy load Background Images ➤ just inactive it. Done....

**Comment by Atala** [comment]
For me I add to unactivate the setting "Lazy Load Background Images" in Elementor > Settings > Experiments tab 

Elementor 3.21.5
Elementor pro 3.20.1
Wordpress 6.5.3

**Comment by SpencerKJH** [comment]
> For me I add to unactivate the setting "Lazy Load Background Images" in Elementor > Settings > Experiments tab
> 
> Elementor 3.21.5 Elementor pro 3.20.1 Wordpress 6.5.3

Thank you so much!
