### ISSUE TITLE
Template Import Error

### ISSUE THREAD

**Issue by meceware** [elementor/elementor#17490]
Hi,

When I try to import a template to Elementor, it generates an error on the frontend saying that an error is occured.

![image](https://user-images.githubusercontent.com/16402717/149662316-1fd2b63f-d693-4301-972b-89acce1636ed.png)

I see that this error is fixed in the past, but I couldn't find a new issue about this. This issue is happening on a new site (I tried it with multisite but it happens on a new install as well), with a simple template as attached. Only Elementor plugin is installed.

![image](https://user-images.githubusercontent.com/16402717/149662343-977190e9-2252-4eae-8190-225720b1ec19.png)

When I check the logs, the error seems to be generated in `manager.php` line `457`.

```
PHP Fatal error:  
Uncaught Error: Cannot use object of type WP_Error as array in ...\\elementor\\includes\\template-library\\manager.php:457

Stack trace:
#0 [internal function]: Elementor\\TemplateLibrary\\Manager->import_template(Array)
#1 ...\\elementor\\includes\\template-library\\manager.php(550): call_user_func(Array, Array)
#2 ...\\elementor\\includes\\template-library\\manager.php(582): Elementor\\TemplateLibrary\\Manager->handle_ajax_request('import_template', Array)
#3 [internal function]: Elementor\\TemplateLibrary\\Manager->Elementor\\TemplateLibrary\\{closure}(Array, Object(Elementor\\Core\\Common\\Modules\\Ajax\\Module))
#4 ...\\elementor\\core\\common\\modules\\ajax\\module.php(171): call_user_func(Object(Closure), Array, Object(Elementor\\Core\\Common\\Modules\\Ajax\\Module))
#5 ...\\wp-includes\\class-wp-hook.php(303): Elementor\\Core\\Common\\Modules\\Ajax\\Module->handle_ajax_request('')
#6 ... in ...\\elementor\\includes\\template-library\\manager.php on line 457, referer: http://localhost/wp.dev/elementor/wp-admin/post.php?post=558&action=elementor
```

The template JSON file: [no-named-template.zip](https://github.com/elementor/elementor/files/7877042/no-named-template.zip)

Could you provide what could be the cause of this issue?

Thank you,

**Comment by MichaelDarko** [comment]
This was also happening to me about a month ago.

Importing into the library through Elementor editor was showing "An error occured - Please try again".

Importing into the library through WordPress admin worked without problem.

But this problem somehow fixed itself in my case and is no longer happening.

**Comment by meceware** [comment]
Hi @MichaelDarko, this actually didn't work for me on a new site. It generates other errors on a fresh install. Not sure why this is happening.

**Comment by MagicSquaresMark** [comment]
Yes, I'm getting the same error when I try to import a JSON file, using v5,8.3 and v5.84 of the Elementor plug-in.

**Comment by willtrking** [comment]
We ran into the same issue, but per @MichaelDarko's comment, importing through the WP Admin interface rather then the Elementor editor worked OK.

**Comment by MagicSquaresMark** [comment]
Yes, I'm getting the same error when I try to import a JSON file, using v5,8.3 and v5.84 of the Elementor plug-in.

> 

Thanks! It took some finding on the WordPress menu but once I did, that worked fine, thank you!

**Comment by carlofabyss** [comment]
I took am getting this error after recently updating some sites, I was trying to move a template from one site to another for a post type single template, and the json file would import into the site but then going to add it in the page also produces the same "An error occured" message without any kind of error code or anything

**Comment by stefyonweb** [comment]
Hi, I have the same problem. What do you mean by import through WP Admin interface? I tried by pasting content from post_content field in posts table to the textarea in page edit (text mode), but result was incomplete.
