### ISSUE TITLE
Cannot use 'in' operator to search for 'length' in A

### ISSUE THREAD

**Issue by Peps03** [elementor/elementor#17525]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

Elementor won't load widget library. Making website un-editable. See:
http://prntscr.com/26gamye
http://prntscr.com/26gami3

Using theme: JupiterX
Everything up to date: yes

Tried disabling plugins. Didn't help.
Tried rolling Elementor back a few versions. Didn't help. 
Tried clearing caches: Yes
Cloudflare dev mode active: Yes

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2
	MySQL version: MariaDB Server v10.6.5
	PHP Version: 7.4.27
	PHP Max Input Vars: 4000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.8.3
	Site URL: https://www.XXXXXX.com
	Home URL: https://www.XXXXXX.com
	WP Multisite: Yes
	Max Upload Size: 1 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 1
	Admin Email: XXXXX@XXXXX.nl
	Debug Mode: Inactive

== Theme ==
	Name: JupiterX
	Version: 1.26.0
	Author: Artbees
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 5.11.4
		Author: Delicious Brains

	Elementor
		Version: 3.5.3
		Author: Elementor.com

	JetElements For Elementor
		Version: 2.6.1
		Author: Crocoblock

	JetPopup
		Version: 1.5.5
		Author: Crocoblock

	JetTricks
		Version: 1.3.8
		Author: Crocoblock

	Jupiter X Core
		Version: 1.23.0
		Author: Artbees

	PEPS Media Redirect Mobile
		Version: 1.0
		Author: PEPS Media - Online Technologies

	PEPS Media SEO Simple
		Version: 3.7
		Author: PEPS Media - Online Technologies

	Slider Revolution
		Version: 6.5.11
		Author: ThemePunch

	Use Any Font
		Version: 6.2
		Author: Dnesscarkey


== Network Plugins ==
	InfiniteWP - Client
		Version: 1.9.6
		Author: Revmakx


== Must-Use Plugins ==
	InfiniteWP - Client Loader
		Version: 
		Author: Revmakx


== Elementor Experiments ==
	Optimized DOM Output: Inactive by default
	Improved Asset Loading: Inactive by default
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Inactive by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Inactive by default
	Hide native WordPress widgets from search results: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default


== Log ==
	
Log: showing 20 of 392021-12-15 09:50:15 [info] Elementor/Upgrades - _on_each_version Finished 
2021-12-15 09:50:15 [info] Elementor/Upgrades - _v_3_5_0_remove_old_elementor_scheme Start  
2021-12-15 09:50:15 [info] Elementor/Upgrades - _v_3_5_0_remove_old_elementor_scheme Finished 
2021-12-15 09:50:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.8',
  'to' => '3.5.0',
)]
2021-12-15 09:50:15 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.8',
  'to' => '3.5.0',
)]
2021-12-21 09:07:38 [info] elementor::elementor_updater Started 
2021-12-21 09:07:38 [info] Elementor/Upgrades - _on_each_version Start  
2021-12-21 09:07:38 [info] Elementor/Upgrades - _on_each_version Finished 
2021-12-21 09:07:38 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.0',
  'to' => '3.5.1',
)]
2021-12-21 09:07:38 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.0',
  'to' => '3.5.1',
)]
2021-12-23 10:41:31 [info] elementor::elementor_updater Started 
2021-12-23 10:41:31 [info] Elementor/Upgrades - _on_each_version Start  
2021-12-23 10:41:31 [info] Elementor/Upgrades - _on_each_version Finished 
2021-12-23 10:41:31 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.1',
  'to' => '3.5.2',
)]
2021-12-23 10:41:31 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.1',
  'to' => '3.5.2',
)]
2021-12-29 10:27:14 [info] elementor::elementor_updater Started 
2021-12-29 10:27:14 [info] Elementor/Upgrades - _on_each_version Start  
2021-12-29 10:27:14 [info] Elementor/Upgrades - _on_each_version Finished 
2021-12-29 10:27:14 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.2',
  'to' => '3.5.3',
)]
2021-12-29 10:27:14 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.2',
  'to' => '3.5.3',
)]

PHP: showing 3 of 3PHP: 2022-01-19 14:10:26 [notice X 132][/home/xxxxxxxx/domains/XXXXXX.com/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $finder_category_name argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-19 14:14:29 [error X 2][/home/xxxxxxxx/domains/XXXXXX.com/public_html/wp-content/plugins/elementor/includes/api.php::164] Uncaught TypeError: Cannot access offset of type string on string in /home/xxxxxxxx/domains/XXXXXX.com/public_html/wp-content/plugins/elementor/includes/api.php:164
Stack trace:
#0 /home/xxxxxxxx/domains/XXXXXX.com/public_html/wp-content/plugins/elementor/core/editor/editor.php(593): Elementor\Api::get_promotion_widgets()
#1 /home/xxxxxxxx/domains/XXXXXX.com/public_html/wp-includes/class-wp-hook.php(303): Elementor\Core\Editor\Editor->enqueue_scripts()
#2 /home/xxxxxxxx/domains/XXXXXX.com/public_html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()
#3 /home/xxxxxxxx/domains/XXXXXX.com/public_html/wp-includes/plugin.php(470): WP_Hook->do_action()
#4 /home/xxxxxxxx/domains/XXXXXX.com/public_html/wp-includes/script-loader.php(2083): do_action()
#5 /home/xxxxxxxx/domains/XXXXXX.com/public_html/wp-includes/class-wp-hook.php(303): wp_enqueue_scripts()
#6 /home/xxxxxxxx/domains/XXXXXX.com/public_html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()
#7 /home/xxxxxxxx/domains/XXXXXX.com/public_html/wp-includes/plugin.php(470): WP_Hook->do_action()
#8 /home/xxxxxxxx/domains/XXXXXX.com/public_html/wp-includes/general-template.php(3015): do_action()
#9 /home/xxxxxxxx/domains/XXXXXX.com/public_html/wp-content/plugins/elementor/includes/editor-templates/editor-wrapper.php(31): wp_head()
#10 /home/xxxxxxxx/domains/XXXXXX.com/public_html/wp-content/plugins/elementor/core/editor/editor.php(317): include('...')
#11 /home/xxxxxxxx/domains/XXXXXX.com/public_html/wp-content/plugins/elementor/core/editor/editor.php(158): Elementor\Core\Editor\Editor->print_editor_template()
#12 /home/xxxxxxxx/domains/XXXXXX.com/public_html/wp-includes/class-wp-hook.php(303): Elementor\Core\Editor\Editor->init()
#13 /home/xxxxxxxx/domains/XXXXXX.com/public_html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()
#14 /home/xxxxxxxx/domains/XXXXXX.com/public_html/wp-includes/plugin.php(470): WP_Hook->do_action()
#15 /home/xxxxxxxx/domains/XXXXXX.com/public_html/wp-admin/admin.php(408): do_action()
#16 /home/xxxxxxxx/domains/XXXXXX.com/public_html/wp-admin/post.php(12): require_once('...')
#17 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-19 14:16:15 [warning X 38][/home/xxxxxxxx/domains/XXXXXX.com/public_html/wp-content/plugins/elementor/includes/api.php::167] Illegal string offset 'pro_widgets' [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	JetElements For Elementor: Incompatible
				
```
</details>

**Comment by gebsl** [comment]
@Peps03: I managed to temporarily get around this issue by installing an old version of Elementor. If this is an option for you, go to https://de.wordpress.org/plugins/elementor/advanced, download an older version and install it manually.

I just tried installing the latest 3.0.x version (https://downloads.wordpress.org/plugin/elementor.3.0.16.zip), which did the trick for me. Maybe also other, more recent versions work. I'm at least happy that I can edit my pages again.

Btw. my site also runs with JupiterX theme, so probably this issue is related to the theme.

**Comment by maximejobin** [comment]
Same problem here.

The site works for Elementor 3.2.4 (or before). After that, same problem.

Also using JupiterX.

**Comment by gebsl** [comment]
@maximejobin thanks a lot for the hint. This also worked for me!

**Comment by cetdelosaltos** [comment]
@maximejobin 
Budget Saver... ThankU
