### ISSUE TITLE
🐞 Bug report: Load more button not working on custom skin Widget Posts

### ISSUE THREAD

**Issue by saulobraine** [elementor/elementor#17604]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I would like add "Categories" to "Classic Skin" on Posts Widget, but it not working very well, here wos a big problem when anyone try to extend Widgets/Skins, the javascript not working properly for the extended widget/skin.
So in this way is lost many funcionalities, like auto ratio, load more button, or filter in Portfolio widget.

Have a way to contour this?

My code:

```
<?php

use Elementor\Controls_Manager;

if ( ! defined( 'ABSPATH' ) ) exit; // Exit if accessed directly

class Extended_Skin_Classic extends ElementorPro\Modules\Posts\Skins\Skin_Classic {
	public function get_id() {
		return 'extended-classic';
	}

	public function get_title() {
		return __( 'Classic Extended', 'elementor-pro' );
	}

	protected function register_meta_data_controls() {
		$this->add_control(
			'meta_data',
			[
				'label' => __( 'Meta Data', 'elementor-pro' ),
				'label_block' => true,
				'type' => Controls_Manager::SELECT2,
				'default' => [ 'date', 'comments' ],
				'multiple' => true,
				'options' => [
					'author' => __( 'Author', 'elementor-pro' ),
					'category' => __( 'Category', 'elementor-pro' ),
					'date' => __( 'Date', 'elementor-pro' ),
					'time' => __( 'Time', 'elementor-pro' ),
					'comments' => __( 'Comments', 'elementor-pro' ),
					'modified' => __( 'Date Modified', 'elementor-pro' ),
				],
				'separator' => 'before',
			]
		);

		$this->add_control(
			'meta_separator',
			[
				'label' => __( 'Separator Between', 'elementor-pro' ),
				'type' => Controls_Manager::TEXT,
				'default' => '///',
				'selectors' => [
					'{{WRAPPER}} .elementor-post__meta-data span + span:before' => 'content: "{{VALUE}}"',
				],
				'condition' => [
					$this->get_control_id( 'meta_data!' ) => [],
				],
			]
		);
	}

	protected function render_meta_data() {
		/** @var array $settings e.g. [ 'author', 'date', ... ] */
		$settings = $this->get_instance_value( 'meta_data' );
		if ( empty( $settings ) ) {
			return;
		}
		?>
<div class="elementor-post__meta-data">
  <?php
			if ( in_array( 'author', $settings ) ) {
				$this->render_author();
			}

			if ( in_array( 'category', $settings ) ) {
				$this->render_category();
			}

			if ( in_array( 'date', $settings ) ) {
				$this->render_date_by_type();
			}

			if ( in_array( 'time', $settings ) ) {
				$this->render_time();
			}

			if ( in_array( 'comments', $settings ) ) {
				$this->render_comments();
			}
			
			if ( in_array( 'modified', $settings ) ) {
				$this->render_date_by_type( 'modified' );
			}
			?>
</div>
<?php
	}

	protected function render_category() {
		?>
<span class="elementor-post-categories">
  <?php
	
		$categories = [];
		foreach(get_the_category() as $category):
				$categories[] = "<a href=". get_category_link( $category->term_id ) ." title='{$category->name}'>{$category->name}</a>"; 
		endforeach;

		echo implode(' • ', $categories);
	 ?>
</span>
<?php
	}

	public function get_container_class() {
		return 'elementor-has-item-ratio';
	}
}
```

### Steps to reproduce

- Create a custom skin extendind classic skin;
- Set posts Widget on page in Elementor and set pagination to Load on Click;
- Try to load on click;

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.19.2
	MySQL version: Source distribution v5.7.31
	PHP Version: 7.4.11
	PHP Max Input Vars: 5000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9
	Site URL: https://braine.dev
	Home URL: https://braine.dev
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: pt-BR
	Timezone: America/Sao_Paulo
	Admin Email: suporte@braine.dev
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 2.4.2.1642535984
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.5.0
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: pt_BR
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36 Edg/97.0.1072.69

== Active Plugins ==
	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Coluna Clicável | Braine
		Version: 1.0
		Author: Saulo Braine

	Elementor
		Version: 3.5.4
		Author: Elementor.com

	Elementor Extend Widget Post - Not Found Template
		Version: 1.0.0
		Author: Saulo Braine

	Elementor Pro
		Version: 3.5.2
		Author: Elementor.com

	Extend Elementor Skin Classic | Braine
		Version: 1.0.0
		Author: Saulo Braine

	JetElements For Elementor
		Version: 2.6.1
		Author: Crocoblock

	JetEngine
		Version: 2.10.3
		Author: Crocoblock

	JetMenu
		Version: 2.1.4
		Author: Crocoblock

	JetTabs For Elementor
		Version: 2.1.15
		Author: Crocoblock

	Mask Form Elementor
		Version: 3.0
		Author: Rodrigo Bogdanowicz

	Braine
		Version: 1.0
		Author: Saulo Braine

	Yoast Duplicate Post
		Version: 4.4
		Author: Enrico Battocchi & Team Yoast

== Uso dos elementos ==
	
	footer : 1
		button : 1
		heading : 4
		icon-list : 1
		nav-menu : 2
		social-icons : 1
		text-editor : 1
		theme-site-logo : 1
	header : 1
		jet-mobile-menu : 1
		nav-menu : 1
		theme-site-logo : 1
	page : 1
		button : 1
		heading : 2
		image : 4
		jet-tabs : 1
		text-editor : 2
	wp-page : 11
		button : 19
		divider : 1
		form : 1
		gallery : 4
		google_maps : 1
		heading : 25
		icon-box : 8
		icon-list : 1
		image : 42
		jet-listing-grid : 2
		jet-tabs : 2
		jet-testimonials : 1
		posts : 3
		social-icons : 1
		spacer : 1
		text-editor : 28
	single-post : 3
		divider : 1
		gallery : 1
		heading : 2
		image : 2
		jet-listing-dynamic-field : 4
		post-navigation : 1
		share-buttons : 1
		theme-post-content : 1
		theme-post-featured-image : 1
	jet-listing-items : 0
		heading : 1
		image : 1
		jet-listing-dynamic-field : 1

== Experimentos do Elementor ==
	Saída DOM otimizada: Ativo por padrão
	Carregamento melhorado de recursos: Ativo por padrão
	Carregamento melhorado de CSS: Ativo por padrão
	Ícones da fonte inline: Inativo por padrão
	Melhorias na acessibilidade: Ativo por padrão
	Importar e exportar Kit de modelos: Ativo por padrão
	Pontos de quebra adicionais personalizados: Ativo por padrão
	Ocultar os widgets nativos do WordPress nos resultados da pesquisa: Ativo por padrão
	Default to New Theme Builder: Ativo por padrão
	Tema Hello - Cabeçalho & Rodapé: Inativo
	Páginas de Aterrissagem: Inativo
	Amostras de cor: Ativo por padrão
	Widgets favoritos: Ativo por padrão
	Barra superior do administrador: Ativo por padrão
	Form Submissions: Ativo por padrão
	Scroll Snap: Ativo por padrão

== Registo ==
	
PHP: showing 4 of 4PHP: 2022-01-18 17:15:20 [notice X 1][/www/wwwroot/braine.dev/wp-content/plugins/elementor/core/common/modules/connect/module.php::230] Trying to get property 'email' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-20 16:48:03 [notice X 7][/www/wwwroot/braine.dev/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-20 16:49:08 [notice X 7][/www/wwwroot/braine.dev/wp-content/plugins/elementor/includes/managers/image.php::87] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-26 16:49:35 [error X 1][/www/wwwroot/braine.dev/wp-content/plugins/elementor/core/wp-api.php::26] Uncaught Error: Call to undefined function Elementor\Core\get_plugins() in /www/wwwroot/braine.dev/wp-content/plugins/elementor/core/wp-api.php:26
Stack trace:
#0 /www/wwwroot/braine.dev/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(96): Elementor\Core\Wp_Api->get_plugins()
#1 /www/wwwroot/braine.dev/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(58): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_with_header()
#2 /www/wwwroot/braine.dev/wp-content/plugins/elementor/modules/compatibility-tag/module.php(57): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_to_check()
#3 /www/wwwroot/braine.dev/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(148): Elementor\Modules\CompatibilityTag\Module->get_plugins_to_check()
#4 /www/wwwroot/braine.dev/wp-includes/class-wp-hook.php(307): Elementor\Modules\CompatibilityTag\Base_Module->Elementor\Modules\CompatibilityTag\{closure}()
#5 /www/wwwroot/Braine.be220 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 5 of 52022-01-24 11:36:36 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.3',
  'to' => '3.5.4',
)]
2022-01-24 11:36:36 [info] elementor::elementor_updater Started 
2022-01-24 11:36:36 [info] Elementor/Upgrades - _on_each_version Start  
2022-01-24 11:36:37 [info] Elementor/Upgrades - _on_each_version Finished 
2022-01-24 11:36:37 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.3',
  'to' => '3.5.4',
)]

JS: showing 9 of 9JS: 2022-01-24 19:25:49 [error X 1][https://braine.dev/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.4:2:453832] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2022-01-25 15:24:11 [error X 3][https://braine.dev/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.4:2:564252] Cannot read properties of undefined (reading \'route\') 
JS: 2022-01-25 18:45:55 [error X 1][https://braine.dev/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=3.5.2:2:10171] Failed to execute \'observe\' on \'IntersectionObserver\': parameter 1 is not of type \'Element\'. 
JS: 2022-01-25 19:06:05 [error X 1][https://braine.dev/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.4:2:228416] Cannot read properties of undefined (reading \'css\') 
JS: 2022-01-25 19:06:05 [error X 2][https://braine.dev/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.5.4:2:5069] Cannot read properties of undefined (reading \'attributes\') 
JS: 2022-01-25 19:11:01 [error X 1][https://braine.dev/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.4:2:348732] elementorFrontend.elements.window.jQuery is not a function 
JS: 2022-01-25 20:34:14 [error X 1][https://braine.dev/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view37177\") has already been destroyed and cannot be used. 
JS: 2022-01-26 18:53:26 [error X 1][https://braine.dev/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view6410\") has already been destroyed and cannot be used. 
JS: 2022-01-26 20:32:10 [error X 1][https://braine.dev/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view1897\") has already been destroyed and cannot be used. 

== Elementor - Compatibility Tag ==
	
	Elementor Extend Widget Post - Not Found Template: Compatibilidade não especificada
	Elementor Pro: Compatível
	Extend Elementor Skin Classic | Braine: Compatibilidade não especificada
	JetElements For Elementor: Incompatível
	JetTabs For Elementor: Incompatível
	Mask Form Elementor: Compatibilidade não especificada

== Elementor Pro - Compatibility Tag ==
	
	JetElements For Elementor: Incompatível
	JetTabs For Elementor: Incompatível

**Comment by mbaierl** [comment]
Yeah, same here. Custom skins don't work very well with reloading or filtering.
