### ISSUE TITLE
BUG in elementor Version 3.6.0-dev35

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#17622]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

In the post widget, the query tab has no content.

### Steps to reproduce

Just add the post widget and open the query tab. There is no option.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.38 (Win32) OpenSSL/1.1.1a PHP/7.3.2
	MySQL version: mariadb.org binary distribution v5.6.42-84.2
	PHP Version: 7.3.2
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.8.3
	Site URL: http://localhost:85/elementor
	Home URL: http://localhost:85/elementor
	WP Multisite: No
	Max Upload Size: 8 MB
	Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: Atlantic/Azores
	Admin Email: hosein.site.98@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.4.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.6.0-dev35
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.5.2
		Author: Elementor.com

== Elements Usage ==
	
	page : 2
		image : 1
	wp-page : 7
		button : 3
		container : 30
		heading : 8
		html : 1
		icon-box : 4
		icon-list : 6
		image : 10
		lottie : 12

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Inactive
	Improved CSS Loading: Active
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Inactive
	Import Export Template Kit: Inactive
	Additional Custom Breakpoints: Inactive
	Hide native WordPress widgets from search results: Active
	Container: Active
	: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Inactive
	Landing Pages: Inactive
	Color Sampler: Active
	Favorite Widgets: Active by default
	Admin Top Bar: Inactive
	Form Submissions: Active
	Scroll Snap: Active by default

== Log ==
	
Log: showing 20 of 362022-01-18 17:55:28 [info] Elementor/Upgrades - _on_each_version Finished 
2022-01-18 17:55:28 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0-dev31',
  'to' => '3.6.0-dev32',
)]
2022-01-18 17:55:30 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0-dev31',
  'to' => '3.6.0-dev32',
)]
2022-01-24 19:19:06 [info] elementor::elementor_updater Started 
2022-01-24 19:19:06 [info] Elementor/Upgrades - _on_each_version Start  
2022-01-24 19:19:06 [info] Elementor/Upgrades - _on_each_version Finished 
2022-01-24 19:19:06 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0-dev32',
  'to' => '3.6.0-dev33',
)]
2022-01-29 18:03:18 [info] elementor::elementor_updater Started 
2022-01-29 18:03:18 [info] Elementor/Upgrades - _on_each_version Start  
2022-01-29 18:03:19 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0-dev33',
  'to' => '3.6.0-dev35',
)]
2022-01-29 18:03:23 [info] Elementor/Upgrades - _on_each_version Finished 
2022-01-29 18:03:24 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0-dev33',
  'to' => '3.6.0-dev35',
)]
2022-01-29 18:03:25 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0-dev33',
  'to' => '3.6.0-dev35',
)]
2022-01-29 18:28:47 [info] elementor-pro::elementor_pro_updater Started 
2022-01-29 18:28:47 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-01-29 18:28:47 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-01-29 18:28:47 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Start  
2022-01-29 18:28:47 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.4.2',
  'to' => '3.5.2',
)]
2022-01-29 18:28:47 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Finished 
2022-01-29 18:28:47 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.4.2',
  'to' => '3.5.2',
)]

PHP: showing 4 of 4PHP: 2022-01-08 15:01:57 [notice X 3][C:\xampp\htdocs\elementor\wp-content\plugins\elementor\core\common\modules\ajax\module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-09 21:04:13 [notice X 19][C:\xampp\htdocs\elementor\wp-content\plugins\elementor-pro\license\updater.php::73] Undefined index: requires [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-18 06:03:29 [error X 1][C:\xampp\htdocs\elementor\wp-content\plugins\elementor\core\wp-api.php::26] Uncaught Error: Call to undefined function Elementor\Core\get_plugins() in C:\xampp\htdocs\elementor\wp-content\plugins\elementor\core\wp-api.php:26
Stack trace:
#0 C:\xampp\htdocs\elementor\wp-content\plugins\elementor\modules\compatibility-tag\base-module.php(96): Elementor\Core\Wp_Api->get_plugins()
#1 C:\xampp\htdocs\elementor\wp-content\plugins\elementor\modules\compatibility-tag\base-module.php(58): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_with_header()
#2 C:\xampp\htdocs\elementor\wp-content\plugins\elementor\modules\compatibility-tag\module.php(57): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_to_check()
#3 C:\xampp\htdocs\elementor\wp-content\plugins\elementor\modules\compatibility-tag\base-module.php(148): Elementor\Modules\CompatibilityTag\Module->get_plugins_to_check()
#4 C:\xampp\htdocs\elementor\wp-includes\class-wp-hook.php(303): Elementor\Modules\CompatibilityTag\Base_Module->Elementor\Modules\CompatibilityTag\{closure}('')
#5 C:\xampp\htdocs\elementor\wp-incl [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-29 18:03:24 [notice X 51][C:\xampp\htdocs\elementor\wp-content\plugins\elementor\modules\dev-tools\deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 2 of 2JS: 2022-01-18 15:24:16 [error X 5][http://localhost:85/elementor/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.0-dev31:2:403874] Cannot read properties of undefined (reading \'parent\') 
JS: 2022-01-29 19:23:08 [error X 4][http://localhost:85/elementor/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.4.2:2:81913] Cannot read properties of undefined (reading \'attributes\') 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Incompatible

== Elementor Pro - Compatibility Tag ==

**Comment by 79ho3ein** [comment]
@rami-elementor

I experience this bug in the dev core version. Therefore, the elementor pro dev version is not active.

elementor : Version 3.6.0-dev39
elementor pro : Version 3.6.1

**Comment by 79ho3ein** [comment]
This issue has been resolved  in elementor beta 3. thank you
