### ISSUE TITLE
page transition is not working properly.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#17698]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

hello @avivu. Thanks for this great update.

1- I tested page transition on all my websites as well as friends. But unfortunately it does not work properly. I do not know if you are aware of it or not, but when we first enter the preloader settings (without selecting the animation for the page transition), if we select an icon or image in the preloader, it will not be displayed! We have to go back to page transition, select an animation to transition to display the icon.

2- The next thing is that if we log in to the website as an admin, the preloader will work properly. But for guest users it is completely broken. The preloader works, but very badly.

3- When the preloader is displayed, the size of the scroll bar changes and then returns to its previous state. This severely damages the UX. Please watch this video And pay attention to the scroll bar :

https://user-images.githubusercontent.com/77163248/152311115-f7ed755a-ffea-46eb-8877-f556ddc771b7.mp4

4- The last thing that is very important is that in the preloader, the animation is not displayed continuously. It is quite clear that it seems to be repeated twice :

https://user-images.githubusercontent.com/77163248/152312931-fe66d127-c3ee-45bd-b19c-002e5b016fdd.mp4

**In most cases, even the content is loaded first and then the preloader is displayed for a moment.** 

It is clear that there is a problem displaying the preloader animation.

**5- When we enter the site directly (domain.com), the preloader is not displayed properly.**
ل

### Steps to reproduce

For number 1 :

1- After updating to the new version, enter the page transition section.
2- Leave this part unchanged. (No transition animation)
3- Enter the preloader section and select an icon or image. Nothing is displayed.
4- Return to section Go to page transition and select an animation.
5- Go to Preloader again and select an image or icon. Now displayed without any problems!

thank you

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.4.17
	PHP Version: 7.4.26
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.8.3
	Site URL: https://avangwebsite.ir
	Home URL: https://avangwebsite.ir
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Asia/Tehran
	Admin Email: avangwebsite@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.4.2
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: fa_IR
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.5.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.6.0
		Author: Elementor.com

	WP Rocket
		Version: 3.10.7
		Author: WP Rocket

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Inactive
	Improved CSS Loading: Inactive
	Inline Font Icons: Inactive
	Accessibility Improvements: Inactive
	Import Export Template Kit: Inactive
	Additional Custom Breakpoints: Inactive
	Hide native WordPress widgets from search results: Active
	Default to New Theme Builder: Active
	Hello Theme Header & Footer: Inactive
	Landing Pages: Inactive
	Color Sampler: Active
	Favorite Widgets: Active by default
	Admin Top Bar: Active
	Page Transitions: Active by default
	Form Submissions: Active
	Scroll Snap: Inactive

== Log ==
	
Log: showing 20 of 362021-12-23 01:29:31 [info] المنتور/Upgrades - _on_each_version Start  
2021-12-23 01:29:31 [info] elementor/Upgrades - _on_each_version Finished 
2021-12-23 01:29:31 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'elementor',
  'from' => '3.5.1',
  'to' => '3.5.2',
)]
2021-12-23 01:29:31 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'elementor',
  'from' => '3.5.1',
  'to' => '3.5.2',
)]
2021-12-29 20:53:27 [info] elementor::elementor_updater Started 
2021-12-29 20:53:27 [info] elementor/Upgrades - _on_each_version Start  
2021-12-29 20:53:27 [info] elementor/Upgrades - _on_each_version Finished 
2021-12-29 20:53:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'elementor',
  'from' => '3.5.2',
  'to' => '3.5.3',
)]
2021-12-29 20:53:28 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'elementor',
  'from' => '3.5.2',
  'to' => '3.5.3',
)]
2022-01-23 14:48:32 [info] elementor::elementor_updater Started 
2022-01-23 14:48:32 [info] elementor/Upgrades - _on_each_version Start  
2022-01-23 14:48:32 [info] elementor/Upgrades - _on_each_version Finished 
2022-01-23 14:48:32 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'elementor',
  'from' => '3.5.3',
  'to' => '3.5.4',
)]
2022-01-23 14:48:32 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'elementor',
  'from' => '3.5.3',
  'to' => '3.5.4',
)]
2022-01-23 14:48:33 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'elementor',
  'from' => '3.5.3',
  'to' => '3.5.4',
)]
2022-02-03 12:03:03 [info] elementor-pro::elementor_pro_updater Started 
2022-02-03 12:03:03 [info] المنتور پرو/Upgrades - _on_each_version Start  
2022-02-03 12:03:03 [info] المنتور پرو/Upgrades - _on_each_version Finished 
2022-02-03 12:03:03 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'elementor pro',
  'from' => '3.5.2',
  'to' => '3.6.0',
)]
2022-02-03 12:03:03 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'elementor pro',
  'from' => '3.5.2',
  'to' => '3.6.0',
)]

PHP: showing 6 of 6PHP: 2021-12-19 16:47:59 [notice X 72][/home2/avangweb/domains/avangwebsite.ir/public_html/wp-content/plugins/elementor-pro/license/updater.php::73] Undefined index: requires [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-12-19 22:48:54 [notice X 1][/home2/avangweb/domains/avangwebsite.ir/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-12-20 16:25:10 [notice X 10][/home2/avangweb/domains/avangwebsite.ir/public_html/wp-content/plugins/elementor-pro/license/updater.php::83] Undefined index: new_version [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-12-28 17:01:06 [notice X 4][/home2/avangweb/domains/avangwebsite.ir/public_html/wp-content/plugins/elementor/includes/managers/image.php::87] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-12 21:53:14 [error X 1][/home2/avangweb/domains/avangwebsite.ir/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::286] Uncaught Error: Call to a member function update_meta() on bool in /home2/avangweb/domains/avangwebsite.ir/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:286
Stack trace:
#0 /home2/avangweb/domains/avangwebsite.ir/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home2/avangweb/domains/avangwebsite.ir/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home2/avangweb/domains/avangwebsite.ir/public_html/wp-includes/class-wp-hook.php(303): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home2/avangweb/d [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-14 19:14:49 [notice X 7][/home2/avangweb/domains/avangwebsite.ir/public_html/wp-content/plugins/elementor-pro/modules/forms/classes/form-record.php::179] Undefined index: referrer [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

**Comment by 79ho3ein** [comment]
Also, unfortunately, the **preloader** works differently in different situations. 

1- Works well when loading tabs created in WordPress. Like contact us, about us and ...
2- Works very badly when displaying product categories. When the content is fully loaded, it appears for a moment and then disappears.
3- When displaying a single product page on the current page (without opening a new window) it works almost perfectly.
4- If the page has the ability to open in a new window, the situation is different.

I played with it a lot to know what the problem was. But unfortunately I did not find the problem. Because each time the result was different and each time the prloader works differently.
**Under the current circumstances, unfortunately the preloader can not be used.**
