### ISSUE TITLE
🐞 BUG in lottie widget - Improved CSS Loading

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#17814]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

hello @shilo-ey , @avivu , @DorShahar .

Explaining this bug is a bit complicated. I will explain it in step-by-step bug reproduction. 
Just know this, the bug is : **If we create a pop-up to display after the website opens, and use the lottie widget in this pop-up, the size of the lottie widget gets out of control and is always 100%. This bug occurs when the Improved CSS Loading option is enabled.**

### Steps to reproduce

**First make sure Improved CSS Loading is disabled.**

1- Create a pop-up and use the lottie widget in it. Save this pop-up unconditionally.
2- Create another pop-up and use the lottie widget in it and**Set the lottie size to 20%**. Set display conditions accordingly : https://prnt.sc/26u2kku , https://prnt.sc/26u2kvt , https://prnt.sc/26u2l80 , And save.
3- Create a footer and add a form widget to it.
4- In the form widget, add actions after submits > a popup.
5- Introduce the pop-up we created in step 1. (After submitting the form, pop-up number 1 will be displayed)
6- Now open the website address as a guest user. According to the conditions, the pop-up we made in step 2 will be displayed.
7- Everything works as expected. (Pay attention to the size of the lottie widget)
8- Now go to the elementor settings and enable the Improved CSS Loading option.
9- Open the web page again as in step 6. After displaying the pop-up, you will see that the lottie size is out of control. (Its size is 100%)

In fact, this interference occurs in stages 4 and 8. I hope you succeed in reproducing it. I tried to describe it in the best way.
My website is such that I have to have steps 2 and 4. Unfortunately, this interference occurs and I have to disable the Improved CSS Loading option.
Of course, this problem has definitely occurred to many users. Please fix this bug if possible. It's very annoying. Let me know if you need a video. But the above description is complete.

I am waiting for your answer from the result of reproduction. thank you

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.38 (Win32) OpenSSL/1.1.1a PHP/7.3.2
	MySQL version: mariadb.org binary distribution v5.6.42-84.2
	PHP Version: 7.3.2
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9
	Site URL: http://localhost:85/jetengine
	Home URL: http://localhost:85/jetengine
	WP Multisite: No
	Max Upload Size: 8 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Asia/Tehran
	Admin Email: hosein.khademabolfazl.79@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.5.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.82 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.5.5
		Author: Elementor.com

	Elementor Pro
		Version: 3.6.0
		Author: Elementor.com

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Inactive
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility Improvements: Inactive by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Inactive by default
	Hide native WordPress widgets from search results: Active by default
	Default to New Theme Builder: Inactive
	Hello Theme Header & Footer: Inactive by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
PHP: showing 10 of 10PHP: 2021-11-11 14:34:38 [notice X 69][C:\xampp\htdocs\jetengine\wp-content\plugins\elementor-pro\license\updater.php::73] Undefined index: requires [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-11-19 17:55:53 [notice X 5][C:\xampp\htdocs\jetengine\wp-content\plugins\elementor\core\common\modules\ajax\module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-12-29 22:51:52 [error X 1][C:\xampp\htdocs\jetengine\wp-content\plugins\elementor\data\v2\base\controller.php::227] Uncaught Elementor\Data\V2\Base\Exceptions\WP_Error_Exception: Method 'WP_REST_Controller::create_item_permissions_check' not implemented. Must be overridden in subclass. in C:\xampp\htdocs\jetengine\wp-content\plugins\elementor\data\v2\base\controller.php:227
Stack trace:
#0 C:\xampp\htdocs\jetengine\wp-content\plugins\elementor\data\v2\base\base-route.php(105): Elementor\Data\V2\Base\Controller->get_permission_callback(Object(WP_REST_Request))
#1 C:\xampp\htdocs\jetengine\wp-content\plugins\elementor\data\v2\base\base-route.php(242): Elementor\Data\V2\Base\Base_Route->get_permission_callback(Object(WP_REST_Request))
#2 C:\xampp\htdocs\jetengine\wp-includes\rest-api\class-wp-rest-server.php(1107): Elementor\Data\V2\Base\Base_Route->Elementor\Data\V2\Base\{closure}(Object(WP_REST_Request))
#3 C:\xampp\htdocs\jetengine\wp-includes\rest-api\class-wp-rest-server.php(987): WP_REST_Server->respond_to_request(Object(WP_REST_Request), '/elementor/v1/f...', Array, NULL)
#4 C:\xampp\htdocs\jetengine\wp-includes\rest-a [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-12-29 22:51:55 [error X 1][C:\xampp\htdocs\jetengine\wp-content\plugins\elementor\data\v2\base\controller.php::227] Uncaught Elementor\Data\V2\Base\Exceptions\WP_Error_Exception: Method 'WP_REST_Controller::delete_item_permissions_check' not implemented. Must be overridden in subclass. in C:\xampp\htdocs\jetengine\wp-content\plugins\elementor\data\v2\base\controller.php:227
Stack trace:
#0 C:\xampp\htdocs\jetengine\wp-content\plugins\elementor\data\v2\base\base-route.php(105): Elementor\Data\V2\Base\Controller->get_permission_callback(Object(WP_REST_Request))
#1 C:\xampp\htdocs\jetengine\wp-content\plugins\elementor\data\v2\base\base-route.php(242): Elementor\Data\V2\Base\Base_Route->get_permission_callback(Object(WP_REST_Request))
#2 C:\xampp\htdocs\jetengine\wp-includes\rest-api\class-wp-rest-server.php(1107): Elementor\Data\V2\Base\Base_Route->Elementor\Data\V2\Base\{closure}(Object(WP_REST_Request))
#3 C:\xampp\htdocs\jetengine\wp-includes\rest-api\class-wp-rest-server.php(987): WP_REST_Server->respond_to_request(Object(WP_REST_Request), '/elementor/v1/f...', Array, NULL)
#4 C:\xampp\htdocs\jetengine\wp-includes\rest-a [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-29 22:30:15 [error X 3][C:\xampp\htdocs\jetengine\wp-content\plugins\elementor\core\dynamic-tags\manager.php::10] Maximum execution time of 30 seconds exceeded [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-01 18:56:37 [error X 1][C:\xampp\htdocs\jetengine\wp-content\plugins\elementor\includes\template-library\sources\local.php::1042] Uncaught TypeError: Argument 2 passed to Elementor\TemplateLibrary\Source_Local::on_save_post() must be an instance of WP_Post, null given, called in C:\xampp\htdocs\jetengine\wp-includes\class-wp-hook.php on line 309 and defined in C:\xampp\htdocs\jetengine\wp-content\plugins\elementor\includes\template-library\sources\local.php:1042
Stack trace:
#0 C:\xampp\htdocs\jetengine\wp-includes\class-wp-hook.php(309): Elementor\TemplateLibrary\Source_Local->on_save_post(2026, NULL)
#1 C:\xampp\htdocs\jetengine\wp-includes\class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#2 C:\xampp\htdocs\jetengine\wp-includes\plugin.php(474): WP_Hook->do_action(Array)
#3 C:\xampp\htdocs\jetengine\wp-includes\post.php(4686): do_action('save_post', 2026, NULL, true)
#4 C:\xampp\htdocs\jetengine\wp-includes\post.php(4788): wp_insert_post(Array, false, true)
#5 C:\xampp\htdocs\jetengine\wp-content\plugins\elementor\includes\db.php(235): wp_update_post(Array)
#6 C:\xampp\htdocs\jetengine\wp-content\plugins\elementor\core\base [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-02 01:35:13 [notice X 1][C:\xampp\htdocs\jetengine\wp-content\plugins\elementor\core\app\modules\import-export\module.php::178] Undefined index: session [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-03 01:37:01 [warning X 1][C:\xampp\htdocs\jetengine\wp-content\plugins\elementor\core\files\manager.php::111] unlink(C:\xampp\htdocs\jetengine/wp-content/uploads/elementor/css/post-1581.css): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-05 15:37:35 [notice X 1][C:\xampp\htdocs\jetengine\wp-content\plugins\elementor-pro\license\updater.php::88] Undefined index: new_version [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-12 03:27:02 [notice X 2][C:\xampp\htdocs\jetengine\wp-content\plugins\elementor-pro\includes\source.php::186] Undefined variable: info_data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 20 of 332021-12-18 22:22:45 [info] elementor-pro::elementor_pro_updater Started 
2021-12-18 22:22:45 [info] Elementor Pro/Upgrades - _on_each_version Start  
2021-12-18 22:22:45 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2021-12-18 22:22:45 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.5.1',
  'to' => '3.5.2',
)]
2021-12-18 22:22:45 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.5.1',
  'to' => '3.5.2',
)]
2022-01-27 13:46:14 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'elementor',
  'from' => '3.5.0',
  'to' => '3.5.4',
)]
2022-01-27 13:46:15 [info] elementor::elementor_updater Started 
2022-01-27 13:46:15 [info] Elementor/Upgrades - _on_each_version Start  
2022-01-27 13:46:15 [info] Elementor/Upgrades - _on_each_version Finished 
2022-01-27 13:46:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.0',
  'to' => '3.5.4',
)]
2022-01-27 13:46:17 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.0',
  'to' => '3.5.4',
)]
2022-02-03 01:37:00 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.5.2',
  'to' => '3.6.0',
)]
2022-02-03 01:37:01 [info] elementor-pro::elementor_pro_updater Started 
2022-02-03 01:37:01 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-02-03 01:37:01 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-02-03 01:37:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.5.2',
  'to' => '3.6.0',
)]
2022-02-12 03:33:35 [info] elementor::elementor_updater Started 
2022-02-12 03:33:35 [info] Elementor/Upgrades - _on_each_version Start  
2022-02-12 03:33:35 [info] Elementor/Upgrades - _on_each_version Finished 
2022-02-12 03:33:35 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.4',
  'to' => '3.5.5',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

**Comment by 79ho3ein** [comment]
@rami-elementor , Were you successful in reproducing this bug?

**Comment by rami-elementor** [comment]
Hi @79ho3ein 

I just tagged this GitHub issue for internal use.

One of our developers or QA engineers will take a look at this issue.

**Comment by 79ho3ein** [comment]
thank you @rami-elementor. Good luck.

**Comment by Michaelgimii** [comment]
I have the same problem

**Comment by Michaelgimii** [comment]
hi @shilo-ey , Do you ignore such bugs in the elementor core? This bug may not have much effect on user performance, but it is a bug anyway!
I hope you read my message.

**Comment by 79ho3ein** [comment]
hi @shilo-ey , I wanted to mention this in the 3.7 beta, but it wasn't the right place to say it.
Please review this bug for updates in the coming weeks if possible. I have fully explained the steps to reproduce this bug above. If you are not successful in reproducing this bug, please let me know so I can investigate further. But I checked this bug on several sites and it exists.
Thank you for your efforts Mr shilo

**Comment by 79ho3ein** [comment]
Hi @nicholaszein , Please check this bug. I'm still experiencing this bug in version 3.8. This is a serious conflict between the Lottie widget and the Improved CSS Loading feature. If I can help please let me know. thank you!

**Comment by nicholaszein** [comment]
Hello @79ho3ein,

the Improved CSS Loading experiment is still in alpha, and some conflicts may still happen. This is a Word In Progress and if it's conflicting with a widget, my advice is to disable the experiment for now. We are working on improving this experiment for the next versions, and this will definitely be taken into account, but it won't be included in v3.8.

Thanks for bringing it to my attention though! 🙏 

Kind regards,

Nick

**Comment by 79ho3ein** [comment]
thank you @nicholaszein , I just wanted you to be aware of that.
