### ISSUE TITLE
🐞 Bug report: 

### ISSUE THREAD

**Issue by laurapnunez** [elementor/elementor#17924]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi, I have a Elementor FORM, and I need that the users can upload a dfx files. But Elementor Form show error with this format, is possible add this types of files in Elementor Form upload?

### Steps to reproduce

When you upload a file dfx

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.7.36
	PHP Version: 7.2.34
	PHP Max Input Vars: 5000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9
	Site URL: https://madridcortelaser.com/nueva
	Home URL: https://madridcortelaser.com/nueva
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: -1
	Permalink Structure: /%postname%/
	Language: es
	Timezone: 0
	Admin Email: laurapnunezweb@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Kadence
	Version: 1.1.14
	Author: Kadence WP
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: es_ES
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36

== Active Plugins ==
	Adapta RGPD
		Version: 1.3.5
		Author: Superadmin

	Click to Chat
		Version: 3.8
		Author: HoliThemes

	Elementor
		Version: 3.5.5
		Author: Elementor.com

	Elementor Pro
		Version: 3.6.2
		Author: Elementor.com

	Kadence Custom Fonts
		Version: 1.1.2
		Author: Kadence WP

	Maintenance
		Version: 4.05
		Author: WebFactory Ltd

	Make Column Clickable Elementor
		Version: 1.3.1
		Author: Fernando Acosta

	Yoast SEO
		Version: 18.1
		Author: Team Yoast

== Experimentos de Elementor ==
	Salida del DOM optimizada: Activo por defecto
	Carga de recursos mejorada: Activo por defecto
	Carga de CSS mejorada: Activo por defecto
	Fuentes de iconos integradas: Inactivo por defecto
	Mejoras de accesibilidad: Activo por defecto
	Importar o exportar un kit de plantillas: Activo por defecto
	Puntos de ruptura personalizados adicionales: Activo por defecto
	Ocultar los widgets nativos de WordPress de los resultados de búsqueda: Activo por defecto
	Por defecto, el nuevo constructor de temas: Activo por defecto
	Páginas de destino: Activo por defecto
	Muestrario de colores: Activo por defecto
	Widgets favoritos: Activo por defecto
	Barra superior de administración: Activo por defecto
	Page Transitions: Activo por defecto
	Envíos de formulario: Activo por defecto
	Ajuste de scroll: Activo por defecto

== Registro ==
	
PHP: showing 2 of 2PHP: 2022-02-16 08:29:57 [error X 1][/homepages/15/d394325597/htdocs/madridcortelaser/nueva/wp-content/plugins/elementor/includes/template-library/manager.php::457] Uncaught Error: Cannot use object of type WP_Error as array in /homepages/15/d394325597/htdocs/madridcortelaser/nueva/wp-content/plugins/elementor/includes/template-library/manager.php:457
Stack trace:
#0 [internal function]: Elementor\TemplateLibrary\Manager->import_template(Array)
#1 /homepages/15/d394325597/htdocs/madridcortelaser/nueva/wp-content/plugins/elementor/includes/template-library/manager.php(550): call_user_func(Array, Array)
#2 /homepages/15/d394325597/htdocs/madridcortelaser/nueva/wp-content/plugins/elementor/includes/template-library/manager.php(582): Elementor\TemplateLibrary\Manager->handle_ajax_request('import_template', Array)
#3 [internal function]: Elementor\TemplateLibrary\Manager->Elementor\TemplateLibrary\{closure}(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#4 /homepages/15/d394325597/htdocs/madridcortelaser/nueva/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Object(Closure), Array, Object(Elementor\Core\Common\Modules\Ajax\Modul [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-17 15:34:34 [notice X 1][/homepages/15/d394325597/htdocs/madridcortelaser/nueva/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::167] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 5 of 52022-02-17 14:45:12 [info] elementor-pro::elementor_pro_updater Started 
2022-02-17 14:45:12 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-02-17 14:45:12 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-02-17 14:45:12 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.5.2',
  'to' => '3.6.2',
)]
2022-02-17 14:45:12 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.5.2',
  'to' => '3.6.2',
)]

JS: showing 1 of 1JS: 2022-02-18 11:48:52 [error X 1][https://madridcortelaser.com/nueva/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.5:2:453832] Cannot read properties of null (reading \'getBoundingClientRect\') 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibilidad no especificada
	Make Column Clickable Elementor: Compatibilidad no especificada

== Elementor Pro - Compatibility Tag ==

**Comment by rami-elementor** [comment]
Hi @laurapnunez ,

Elementor Forms has a list of "not allowed" file extensions:

```php
private function get_blacklist_file_ext() {
	static $blacklist = false;
	if ( ! $blacklist ) {
		$blacklist = [ 'php', 'php3', 'php4', 'php5', 'php6', 'phps', 'php7', 'phtml', 'shtml', 'pht', 'swf', 'html', 'asp', 'aspx', 'cmd', 'csh', 'bat', 'htm', 'hta', 'jar', 'exe', 'com', 'js', 'lnk', 'htaccess', 'htpasswd', 'phtml', 'ps1', 'ps2', 'py', 'rb', 'tmp', 'cgi' ];

		/**
		 * Forms file types black list.
		 *
		 * Filters the black list of  file types that won’t be uploaded using the forms.
		 *
		 * @since 1.0.0
		 *
		 * @param array $blacklist A black list of file types.
		 */
		$blacklist = apply_filters( 'elementor_pro/forms/filetypes/blacklist', $blacklist );
	}

	return $blacklist;
}
```

But `dfx` is not one of them.

----

I think you need to [add a new mime type to WordPress](https://developer.wordpress.org/reference/hooks/upload_mimes/) :

```php
function dfx_mime_type( $mimes ) {
        $mimes['dfx'] = 'application/dfx';
        return $mimes;
}
add_filter( 'upload_mimes', 'dfx_mime_type' );
```
