### ISSUE TITLE
🐞 Bug report: Redirect does not work

### ISSUE THREAD

**Issue by frindly** [elementor/elementor#17961]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I have an elementor page with a form with a single field (email) and a submit button.  I added a collection action and a redirect action.  The redirect action never happens, i've tried internal pages, external pages and it never redirects.  What i want is to redirect to an external page and include the email address from the form in the URL.

<img width="299" alt="Screen Shot 2022-02-23 at 6 48 04 PM" src="https://user-images.githubusercontent.com/1693926/155448084-4c8ff445-a7df-4357-bf09-d04cdbfc6e7a.png">
 

### Steps to reproduce

1) Create a form in an elementor page with an email address entry and a submit button
2) Add a redirect action to the form (you can redirect to https://www.google.com or any url)
3) publish the page
4) enter an email address and press the submit button
EXPECTED: User redirected to the page specified in the action
ACTUAL: User is not redirected

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

<h3 class="wp-heading-inline" style="display: block; font-weight: 600; color: rgb(29, 35, 39); font-size: 1.3em; margin: 1em 0px; font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(240, 240, 241); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">System Info</h3><div style="outline: 0px; color: rgb(60, 67, 74); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(240, 240, 241); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="elementor-system-info-section elementor-system-info-server" style="outline: 0px; margin-bottom: 10px;">

Server Environment |   |  
-- | -- | --
Operating System: | Linux |  
Software: | Apache |  
MySQL version: | MySQL Community Server (GPL) v5.7.36 |  
PHP Version: | 7.4.25 |  
PHP Max Input Vars: | 1000 |  
PHP Max Post Size: | 100M |  
GD Installed: | Yes |  
ZIP Installed: | No |  
Write Permissions: | All right |  
Elementor Library: | Connected |  

</div></div>System Info
Server Environment		
Operating System:	Linux	
Software:	Apache	
MySQL version:	MySQL Community Server (GPL) v5.7.36	
PHP Version:	7.4.25	
PHP Max Input Vars:	1000	
PHP Max Post Size:	100M	
GD Installed:	Yes	
ZIP Installed:	No	
Write Permissions:	All right	
Elementor Library:	Connected	
WordPress Environment		
Version:	5.9.1	
Site URL:	https://www.alcove.co	
Home URL:	https://www.alcove.co	
WP Multisite:	No	
Max Upload Size:	100 MB	
Memory limit:	256M	
Permalink Structure:	/%postname%/	
Language:	en-US	
Timezone:	0	
Admin Email:	jake@alcove.tech	
Debug Mode:	Inactive	
Theme		
Name:	Hello Elementor	
Version:	2.5.0	
Author:	Elementor Team	
Child Theme:	No	If you want to modify the source code of your theme, we recommend using a [child theme](https://go.elementor.com/wordpress-child-themes/).
User		
Role:	administrator	
WP Profile lang:	en_US	
User Agent:	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36	
Active Plugins		
[Custom Post Type UI](https://github.com/WebDevStudios/custom-post-type-ui/) - 1.10.2	By [WebDevStudios](https://webdevstudios.com/)	
[Elementor](https://elementor.com/?utm_source=wp-plugins&utm_campaign=plugin-uri&utm_medium=wp-dash) - 3.5.5	By [Elementor.com](https://elementor.com/?utm_source=wp-plugins&utm_campaign=author-uri&utm_medium=wp-dash)	
[Elementor Pro](https://go.elementor.com/wp-dash-wp-plugins-author-uri/) - 3.6.2	By [Elementor.com](https://go.elementor.com/wp-dash-wp-plugins-author-uri/)	
[HubSpot All-In-One Marketing - Forms, Popups, Live Chat](http://www.hubspot.com/integrations/wordpress) - 8.5.24	By [HubSpot](http://hubspot.com/products/wordpress)	
[SSL Insecure Content Fixer](https://ssl.webaware.net.au/) - 2.7.2	By [WebAware](https://shop.webaware.com.au/)	
[Void Elementor Post Grid Addon for Elementor Page builder](https://voidcoders.com/product/post-grid-add-on-for-elementor-free/) - 2.1.9	By [VOID CODERS](http://voidcoders.com/)	
[WP Lever](https://github.com/obiPlabon/wp-lever) - 0.0.1	By [obiPlabon](https://obiplabon.im/)	
[Yoast Duplicate Post](https://yoast.com/wordpress/plugins/duplicate-post/) - 4.4	By [Enrico Battocchi & Team Yoast](https://yoast.com/)	
Must-Use Plugins		
[Elementor Safe Mode](https://elementor.com/?utm_source=safe-mode&utm_campaign=plugin-uri&utm_medium=wp-dash) - 1.0.0	By [Elementor.com](https://elementor.com/?utm_source=safe-mode&utm_campaign=author-uri&utm_medium=wp-dash)	
Elementor Experiments		
Optimized DOM Output: 	Active by default
Improved Asset Loading: 	Active by default
Improved CSS Loading: 	Active by default
Inline Font Icons: 	Inactive by default
Accessibility Improvements: 	Active by default
Import Export Template Kit: 	Active by default
Additional Custom Breakpoints: 	Active by default
Hide native WordPress widgets from search results: 	Active by default
Default to New Theme Builder: 	Active by default
Hello Theme Header & Footer: 	Active by default
Landing Pages: 	Active by default
Color Sampler: 	Active by default
Favorite Widgets: 	Active by default
Admin Top Bar: 	Active by default
Page Transitions: 	Active by default
Form Submissions: 	Active by default
Scroll Snap: 	Active by default
Log[Clear Log](https://www.alcove.co/wp-admin/admin.php?page=elementor-system-info&elementor-clear-log=1&_wpnonce=b7b48e4317#elementor-clear-log)		
PHP: showing 6 of 6
PHP: 2022-01-27 15:51:08 [notice X 38][/var/www/html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-28 05:28:10 [error X 2][/var/www/html/wp-content/plugins/elementor/includes/template-library/manager.php::457] Uncaught Error: Cannot use object of type WP_Error as array in /var/www/html/wp-content/plugins/elementor/includes/template-library/manager.php:457
Stack trace:
#0 [internal function]: Elementor\TemplateLibrary\Manager->import_template()
#1 /var/www/html/wp-content/plugins/elementor/includes/template-library/manager.php(550): call_user_func()
#2 /var/www/html/wp-content/plugins/elementor/includes/template-library/manager.php(582): Elementor\TemplateLibrary\Manager->handle_ajax_request()
#3 [internal function]: Elementor\TemplateLibrary\Manager->Elementor\TemplateLibrary\{closure}()
#4 /var/www/html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func()
#5 /var/www/html/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#6 /var/www/html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#7 /var/www/html/wp-includes/plugin.php(474): WP_Hook->do_action()
#8 /var/www/html/wp-admin/admin-ajax.php(187): do_action()
#9 {main [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-28 05:32:09 [notice X 4][/var/www/html/wp-content/plugins/elementor/includes/managers/image.php::87] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-28 05:32:17 [error X 1][/var/www/html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::286] Uncaught Error: Call to a member function update_meta() on bool in /var/www/html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:286
Stack trace:
#0 /var/www/html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions()
#2 /var/www/html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func()
#3 /var/www/html/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#4 /var/www/html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#5 /var/www/html/wp-includes/plugin.php(474): WP_Hook->do_action()
#6 /var/www/html/wp-admin/admin-ajax.php(187): do_action()
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-03 05:19:47 [notice X 4][/var/www/html/wp-content/plugins/elementor/includes/managers/image.php::81] Undefined offset: 2 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-03 05:20:11 [notice X 65][/var/www/html/wp-content/plugins/elementor/includes/libraries/bfi-thumb/bfi-thumb.php::751] A non well formed numeric value encountered [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
JS: showing 3 of 3
JS: 2022-01-28 05:35:45 [error X 19][http://34.94.21.144/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.4:2:453832] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2022-02-14 18:55:57 [error X 2][http://34.94.21.144/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.4:2:332595] Cannot read properties of undefined (reading \'isDesignable\') 
JS: 2022-02-20 23:49:10 [error X 2][https://www.alcove.co/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:177:503] Cannot read properties of undefined (reading \'chevron-down\') 
Log: showing 10 of 10
2022-02-24 02:38:49 [info] elementor::elementor_updater Started 
2022-02-24 02:38:49 [info] Elementor/Upgrades - _on_each_version Start  
2022-02-24 02:38:49 [info] Elementor/Upgrades - _on_each_version Finished 
2022-02-24 02:38:49 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.4',
  'to' => '3.5.5',
)]
2022-02-24 02:38:49 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.4',
  'to' => '3.5.5',
)]
2022-02-24 02:38:58 [info] elementor-pro::elementor_pro_updater Started 
2022-02-24 02:38:58 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-02-24 02:38:58 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-02-24 02:38:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.5.2',
  'to' => '3.6.2',
)]
2022-02-24 02:38:58 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.5.2',
  'to' => '3.6.2',
)]

**Comment by frindly** [comment]
I found the RC of the issue:
I’m running my site behind an SSL load balancer, and using the insecure content fixer plugin.  The experiment “Improved Asset Loading” loads some js after the page is loading, these loads are NOT fixed by the plugin and caused the form code that does the redirect to be blocked as insecure content.  Disabling this experiment fixed the issue for me.
