### ISSUE TITLE
🔃 🐞 Bug Report: WooCommerce Button Styles are overwritten in the frontend

### ISSUE THREAD

**Issue by ilkanellop** [elementor/elementor#17975]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When I edit the checkout button in cart widget in live page nothing changes. CSS also doesn't work. Tried with Hello Elementor theme but it doesn't work either. I use Astra free theme for my site.

### Steps to reproduce

Try edit the checkout button in cart widget.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.5.13
	PHP Version: 7.4.28
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.1
	Site URL: https://espawnspot.com
	Home URL: https://espawnspot.com
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 1024M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Europe/Athens
	Admin Email: iliaskanellopoulos@hotmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Astra
	Version: 3.7.7
	Author: Brainstorm Force
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Android 11; Mobile; rv:97.0) Gecko/97.0 Firefox/97.0

== Active Plugins ==
	Advanced Shipment Tracking for WooCommerce
		Version: 3.3.1
		Author: zorem

	Astra Customizer Reset
		Version: 1.0.5
		Author: Brainstorm Force

	Code Snippets
		Version: 2.14.3
		Author: Code Snippets Pro

	Customizer Search
		Version: 1.1.6
		Author: Brainstorm Force

	Elementor
		Version: 3.5.5
		Author: Elementor.com

	Elementor Pro
		Version: 3.6.2
		Author: Elementor.com

	LiteSpeed Cache
		Version: 4.5.0.1
		Author: LiteSpeed Technologies

	Post Types Order
		Version: 1.9.7
		Author: Nsp Code

	Printful Integration for WooCommerce
		Version: 2.1.30
		Author: Printful

	Product Filter by WooBeWoo
		Version: 2.1.0
		Author: WooBeWoo

	Starter Templates
		Version: 3.1.4
		Author: Brainstorm Force

	TI WooCommerce Wishlist
		Version: 1.41.1
		Author: TemplateInvaders

	WooCommerce
		Version: 6.2.1
		Author: Automattic

	WooCommerce Admin
		Version: 3.2.1
		Author: WooCommerce

	WooCommerce Stripe Gateway
		Version: 6.2.0
		Author: WooCommerce

	WP Categories Widget
		Version: 2.1
		Author: WP-EXPERTS.IN TEAM

	WPvivid Backup Plugin
		Version: 0.9.69
		Author: WPvivid Team

== Elements Usage ==
	
	footer : 1
		heading : 5
		icon-list : 2
		nav-menu : 3
		social-icons : 1
		text-editor : 1
	header : 1
		icon : 2
		nav-menu : 1
		search-form : 1
		theme-site-title : 1
		woocommerce-menu-cart : 1
	page : 4
		form : 3
		heading : 1
		image-box : 2
		text-editor : 1
	section : 1
		woocommerce-breadcrumb : 1
	wp-page : 13
		form : 1
		heading : 5
		html : 1
		icon-box : 3
		icon-list : 1
		posts : 1
		slides : 1
		tabs : 2
		text-editor : 4
		woocommerce-breadcrumb : 3
		woocommerce-cart : 1
		woocommerce-products : 3
		woofilters : 3
	product-archive : 3
		woocommerce-breadcrumb : 3
		woocommerce-products : 3
		woofilters : 3

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	Default to New Theme Builder: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
JS: showing 6 of 6JS: 2022-02-17 14:22:43 [error X 4][https://espawnspot.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.5:2:453830] T is null 
JS: 2022-02-17 21:10:18 [error X 3][https://espawnspot.com/wp-includes/js/mediaelement/mediaelement-and-player.min.js?ver=4.2.16:12:153603] Window.getComputedStyle: Argument 1 is not an object. 
JS: 2022-02-18 13:48:49 [error X 1][https://espawnspot.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.5:2:320370] this.$currentEditingArea is null 
JS: 2022-02-18 15:09:25 [error X 10][https://espawnspot.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.5:2:558642] elementorFrontend is not defined 
JS: 2022-02-18 20:21:07 [error X 2][https://espawnspot.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.5:2:112521] C.props.parentRef.current is null 
JS: 2022-02-22 17:29:43 [error X 10][https://espawnspot.com/wp-content/plugins/elementor-pro/assets/js/elements-handlers.min.js?ver=3.6.2:2:7359] t.entrance_animation_duration is undefined 

PHP: showing 8 of 8PHP: 2022-02-17 15:31:39 [notice X 1][/home/espawnsp/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The Plugin::$instance->posts_css_manager argument is deprecated since version 2.7.0! Use Plugin::$instance->files_manager instead. [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-17 16:34:17 [notice X 1][/home/espawnsp/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::167] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-18 16:41:27 [notice X 6][/home/espawnsp/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-18 16:41:54 [notice X 1][/home/espawnsp/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php::256] Undefined index: sub_name [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-18 17:08:04 [notice X 39][/home/espawnsp/public_html/wp-content/plugins/elementor/core/base/document.php::1570] Trying to get property 'post_status' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-18 22:57:49 [warning X 1][/home/espawnsp/public_html/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/icons/icon-sets/fontello.php::32] file_get_contents(/tmp/fontello-bc495f5a/fontello-bc495f5a/css/.css): failed to open stream: No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-18 23:03:29 [warning X 1][/home/espawnsp/public_html/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/icons/custom-icons.php::180] unlink(DOTS.svg): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-22 21:54:15 [error X 2][/home/espawnsp/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::286] Uncaught Error: Call to a member function update_meta() on bool in /home/espawnsp/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:286
Stack trace:
#0 /home/espawnsp/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/espawnsp/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/espawnsp/public_html/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/espawnsp/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#5 /home/espawnsp/pu [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @ilkanellop! 

Thank you for submitting your issue, and for being so patient! 🙏 

Can you please confirm if this happens with the Improve CSS Loading experiment inactive?

Best regards

**Comment by nicholaszein** [comment]
Hello there, 

#### 🕙 It's been a while since we answered you, and we haven't received any feedback. 

## 🚧 For this reason, we are closing this issue because of no activity.

👉 If you wish to continue this discussion, please follow the guidelines for opening a new [🐞 Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml).

👉 If you wish to continue this discussion, please follow the guidelines for opening a new [🚀 Feature Request](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=feature_request.yml).

Feel free to submit a new issue in accordance with these guidelines. 😉 

Kind regards
