### ISSUE TITLE
⛔ 🐞 Bug report: Menu Cart Widget Popup empty of content

### ISSUE THREAD

**Issue by growkal** [elementor/elementor#18017]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi,
On one of our websites we have the following problem.
The menu cart widget on the header is not displaying any content inside it. No matter it is empty to display the text "your cart is empty" or you have products in the cart. They are not displaying and the links to cart/checkout also not displaying.
I'm also attaching a screenshot.
All elementor plugins are updated to the latest version and Wordpress ass well.
www.rohleder.at - link to the website
![Screenshot 2022-02-28 at 14 58 36](https://user-images.githubusercontent.com/100587615/155991593-b30341ea-d062-402b-8480-43e07f51e73f.png)

### Steps to reproduce

Open shop page - www.rohleder.at/shop
Choose one product and add it to your cart.
Then when you click on the menu cart widget in the header it is not displaying anything inside.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.17.5
	MySQL version: mariadb.org binary distribution v10.4.22
	PHP Version: 7.4.27
	PHP Max Input Vars: 10000
	PHP Max Post Size: 2000M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.1
	Site URL: https://rohleder.at
	Home URL: https://rohleder.at
	WP Multisite: No
	Max Upload Size: 2 GB
	Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: office@rohleder.at
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.5.0
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36

== Active Plugins ==
	Brave Conversion Engine (PRO)
		Version: 0.3.5
		Author: Brave

	CoDesigner
		Version: 3.4.2
		Author: Codexpert

	Customer Reviews for WooCommerce
		Version: 4.38
		Author: CusRev

	Disk Usage Sunburst
		Version: 1.1.3
		Author: raidboxes.io

	Elementor
		Version: 3.5.6
		Author: Elementor.com

	Elementor Pro
		Version: 3.6.2
		Author: Elementor.com

	Essential Addons for Elementor
		Version: 5.0.9
		Author: WPDeveloper

	FileBird Lite
		Version: 4.9.8
		Author: Ninja Team

	GDPR Cookie Consent
		Version: 2.1.1
		Author: WebToffee

	Google Listings and Ads
		Version: 1.11.1
		Author: WooCommerce

	Google Tag Manager for Wordpress
		Version: 1.14.2
		Author: Thomas Geiger

	JetSmartFilters
		Version: 2.3.10
		Author: Crocoblock

	JetWooBuilder For Elementor
		Version: 1.12.0
		Author: Crocoblock

	Mailchimp for WooCommerce
		Version: 2.5.4
		Author: Mailchimp

	Make Column Clickable Elementor
		Version: 1.3.1
		Author: Fernando Acosta

	NextMove Lite - Thank You Page for WooCommerce
		Version: 2.15.0
		Author: XLPlugins

	NitroPack
		Version: 1.5.9
		Author: NitroPack LLC

	Sofortueberweisung / Klarna Gateway for Woocommerce
		Version: 1.3.4
		Author: Michael Leithold

	Variation Swatches for WooCommerce
		Version: 2.1.4
		Author: Woosuite

	WooCommerce
		Version: 6.2.1
		Author: Automattic

	WooCommerce Multilingual
		Version: 4.12.6
		Author: OnTheGoSystems

	WooCommerce Stripe Gateway
		Version: 6.2.0
		Author: WooCommerce

	WP Mail SMTP
		Version: 3.3.0
		Author: WPForms

	WPML Media
		Version: 2.7.0
		Author: OnTheGoSystems

	WPML Multilingual CMS
		Version: 4.5.2
		Author: OnTheGoSystems

	WPML SEO
		Version: 2.0.1
		Author: OnTheGoSystems

	WPML String Translation
		Version: 3.2.0
		Author: OnTheGoSystems

	YITH WooCommerce Frequently Bought Together Premium
		Version: 1.14.0
		Author: YITH

	YITH WooCommerce Product Add-ons & Extra Options Premium
		Version: 2.7.0
		Author: YITH

	Yoast SEO
		Version: 18.2
		Author: Team Yoast

== Elements Usage ==
	
	archive : 1
		archive-posts : 1
		button : 4
		divider : 2
		heading : 4
		spacer : 11
		text-editor : 1
	footer : 1
		divider : 1
		icon-list : 3
		image : 1
		text-editor : 2
	header : 2
		html : 1
		icon-list : 1
		nav-menu : 2
		theme-site-logo : 2
		woocommerce-menu-cart : 2
	page : 83
		button : 10
		divider : 4
		heading : 4
		icon-box : 5
		image : 7
		image-box : 4
		spacer : 10
		text-editor : 6
		woocommerce-product-add-to-cart : 1
		woocommerce-product-data-tabs : 1
		woocommerce-product-images : 1
		woocommerce-product-price : 1
		woocommerce-product-title : 1
	popup : 3
		divider : 1
		form : 1
		heading : 1
		image : 1
		text-editor : 2
	product : 18
		button : 47
		divider : 48
		heading : 41
		html : 10
		icon-box : 37
		image : 10
		image-box : 40
		shortcode : 1
		spacer : 100
		video : 1
		woocommerce-product-add-to-cart : 10
		woocommerce-product-data-tabs : 9
		woocommerce-product-images : 10
		woocommerce-product-price : 10
		woocommerce-product-title : 10
	section : 23
		button : 5
		divider : 6
		heading : 4
		image : 2
		image-box : 7
		spacer : 10
		text-editor : 1
	widget : 0
		html : 1
		icon-box : 8
	wp-post : 3
		text-editor : 1
	wp-page : 53
		button : 45
		cart-items : 1
		cart-overview : 1
		coupon-form : 1
		divider : 84
		eael-adv-accordion : 1
		eael-adv-tabs : 1
		eael-advanced-data-table : 1
		eael-flip-box : 6
		eael-post-grid : 1
		eael-woo-checkout : 1
		eicon-woocommerce : 2
		heading : 70
		html : 1
		icon-box : 8
		image : 27
		image-box : 68
		image-gallery : 1
		jet-woo-products : 1
		media-carousel : 8
		menu-anchor : 2
		spacer : 75
		tabs : 1
		testimonial-carousel : 1
		text-editor : 89
		video : 3
	single-post : 1
		heading : 1
		post-info : 1
		post-navigation : 1
		posts : 1
		table-of-contents : 1
		theme-post-content : 1
		theme-post-excerpt : 1
		theme-post-featured-image : 1
		theme-post-title : 1
	product-post : 0
		text-editor : 10
	jet-woo-builder-shop : 0
		heading : 1
		jet-woo-products : 1
		jet-woo-taxonomy-tiles : 1
	jet-woo-builder-checkout : 0
		heading : 1
		image : 1
		jet-checkout-additional-form : 1
		jet-checkout-billing : 1
		jet-checkout-order-review : 1
		jet-checkout-payment : 1
		jet-checkout-shipping-form : 1
	jet-woo-builder-cart : 0
		eicon-woocommerce : 1
		heading : 2
		jet-cart-empty-message : 1
		jet-cart-table : 1
		jet-cart-totals : 1
	jet-woo-builder-archive : 0
		jet-woo-products : 1

== Elementor Experiments ==
	Optimized DOM Output: Inactive by default
	Improved Asset Loading: Inactive by default
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Inactive by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Inactive by default
	Hide native WordPress widgets from search results: Active by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Inactive by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 20 of 282022-02-12 12:53:58 [info] Elementor/Upgrades - _on_each_version Start  
2022-02-12 12:53:59 [info] Elementor/Upgrades - _on_each_version Finished 
2022-02-12 12:53:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.4',
  'to' => '3.5.5',
)]
2022-02-12 12:56:45 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.5.2',
  'to' => '3.6.1',
)]
2022-02-12 12:56:46 [info] elementor-pro::elementor_pro_updater Started 
2022-02-12 12:56:46 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-02-12 12:56:46 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-02-12 12:56:46 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.5.2',
  'to' => '3.6.1',
)]
2022-02-12 12:56:48 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.5.2',
  'to' => '3.6.1',
)]
2022-02-18 16:59:54 [info] elementor-pro::elementor_pro_updater Started 
2022-02-18 16:59:54 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-02-18 16:59:54 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-02-18 16:59:54 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.1',
  'to' => '3.6.2',
)]
2022-02-18 16:59:58 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.1',
  'to' => '3.6.2',
)]
2022-02-28 13:01:07 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.5',
  'to' => '3.5.6',
)]
2022-02-28 13:01:12 [info] elementor::elementor_updater Started 
2022-02-28 13:01:12 [info] Elementor/Upgrades - _on_each_version Start  
2022-02-28 13:01:13 [info] Elementor/Upgrades - _on_each_version Finished 
2022-02-28 13:01:13 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.5',
  'to' => '3.5.6',
)]
2022-02-28 13:01:14 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.5',
  'to' => '3.5.6',
)]

PHP: showing 6 of 6PHP: 2022-01-27 11:32:01 [notice X 21][/home/wp/disk/wordpress/wp-content/plugins/elementor-pro/modules/forms/classes/ajax-handler.php::260] Undefined index: post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-29 11:45:13 [error X 1][/home/wp/disk/wordpress/wp-content/plugins/elementor/includes/template-library/sources/local.php::1042] Uncaught TypeError: Argument 2 passed to Elementor\TemplateLibrary\Source_Local::on_save_post() must be an instance of WP_Post, instance of stdClass given, called in /home/wp/disk/wordpress/wp-includes/class-wp-hook.php on line 305 and defined in /home/wp/disk/wordpress/wp-content/plugins/elementor/includes/template-library/sources/local.php:1042
Stack trace:
#0 /home/wp/disk/wordpress/wp-includes/class-wp-hook.php(305): Elementor\TemplateLibrary\Source_Local->on_save_post()
#1 /home/wp/disk/wordpress/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()
#2 /home/wp/disk/wordpress/wp-includes/plugin.php(470): WP_Hook->do_action()
#3 /home/wp/disk/wordpress/wp-includes/post.php(4468): do_action()
#4 /home/wp/disk/wordpress/wp-includes/post.php(4570): wp_insert_post()
#5 /home/wp/disk/wordpress/wp-content/plugins/elementor/includes/db.php(235): wp_update_post()
#6 /home/wp/disk/wordpress/wp-content/plugins/elementor/core/base/document.php(1099): Elementor\DB->save_plain_text()
#7 /home/wp/disk/wordpress/ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-10 08:30:39 [warning X 2][/home/wp/disk/wordpress/wp-content/plugins/elementor-pro/license/api.php::370] in_array() expects parameter 2 to be array, null given [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-21 16:48:11 [notice X 6][/home/wp/disk/wordpress/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-27 14:00:41 [notice X 2][/home/wp/disk/wordpress/wp-content/plugins/elementor/includes/managers/image.php::87] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-28 13:00:49 [error X 1][/home/wp/disk/wordpress/wp-content/plugins/elementor/core/experiments/manager.php::83] Uncaught Error: Class 'Elementor\Core\Upgrade\Manager' not found in /home/wp/disk/wordpress/wp-content/plugins/elementor/core/experiments/manager.php:83
Stack trace:
#0 /home/wp/disk/wordpress/wp-content/plugins/elementor/core/experiments/manager.php(219): Elementor\Core\Experiments\Manager->add_feature()
#1 /home/wp/disk/wordpress/wp-content/plugins/elementor/core/experiments/manager.php(356): Elementor\Core\Experiments\Manager->add_default_features()
#2 /home/wp/disk/wordpress/wp-content/plugins/elementor/core/experiments/manager.php(630): Elementor\Core\Experiments\Manager->init_features()
#3 /home/wp/disk/wordpress/wp-content/plugins/elementor/includes/plugin.php(695): Elementor\Core\Experiments\Manager->__construct()
#4 /home/wp/disk/wordpress/wp-content/plugins/elementor/includes/plugin.php(636): Elementor\Plugin->init_components()
#5 /home/wp/disk/wordpress/wp-includes/class-wp-hook.php(307): Elementor\Plugin->init()
#6 /home/wp/disk/wordpress/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters( [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 9 of 9JS: 2022-02-12 13:39:15 [error X 10][https://rohleder.at/wp-content/plugins/elementor/assets/js/common.min.js?ver=3.5.5:2:222547] Cannot read properties of undefined (reading \'global\') 
JS: 2022-02-12 13:44:12 [error X 1][https://rohleder.at/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.5:2:252671] Cannot read properties of undefined (reading \'REPLACE_TO_ID\') 
JS: 2022-02-25 08:56:00 [error X 1][https://rohleder.at/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view114\") has already been destroyed and cannot be used. 
JS: 2022-02-26 13:16:44 [error X 4][https://rohleder.at/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.5:2:453832] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2022-02-26 15:39:40 [error X 6][https://rohleder.at/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.5.5:2:12041] this.children.clear is not a function 
JS: 2022-02-27 14:01:39 [error X 3][https://rohleder.at/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.5:2:252935] Cannot read properties of undefined (reading \'html\') 
JS: 2022-02-27 15:45:22 [error X 1][https://rohleder.at/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view7018\") has already been destroyed and cannot be used. 
JS: 2022-02-27 15:45:55 [error X 1][https://rohleder.at/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view8401\") has already been destroyed and cannot be used. 
JS: 2022-02-27 15:46:36 [error X 1][https://rohleder.at/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view14291\") has already been destroyed and cannot be used. 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	Essential Addons for Elementor: Compatibility not specified
	JetWooBuilder For Elementor: Compatibility not specified
	Make Column Clickable Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by philkonick** [comment]
I'm also experiencing this. 

The problem is occuring in both the mini-cart and side-cart. They work fine on WooCommerce pages, i.e. Shop, Basket, etc, but not on any other pages. An exception is on the home page, if a product is added the mini-cart will display, but if you navigate away and then back to the home page it will behave the same as other non-woocommerce pages.

**Comment by essentique** [comment]
I'm also experiencing a similar thing.

- for me the problem occurs on macos using Chrome. It's fine with Safari. Chrome on Windows is also fine.
- I’m on macOS 12.4 running Chrome Version 103.0.5060.114 (Official Build) (x86_64)
- I’m not running any caching or optimization plugins on my site
- I’ve tried with and without server side (reverse proxy) cache and the problem remains
- The problem happens when I have something in the cart, then using either browser navigation buttons, back or forward,  I land on certain pages (like my product archive pages). It only happens on some pages, e.g., it doesn't happen with my home page.
- the problematic pages seem to get loaded from the browser cache, and no request goes back to the server, presumably to get the cart info. So it ends up being a blank side cart page. A la,  ‘?wc-ajax=get_refreshed_fragments&elementor_page_id=…’

**Comment by nicholaszein** [comment]
Hello there, 

### 🕙 It's been a while since you submitted this issue. 

And checking your system Info I can see you were using a Performance Optimization plugin, which is likely the reason why you were having the issue you reported.

Moreover, this is more of a support question, not really something we can answer here.

## 🚧 For this reason, we are closing this issue because of no activity.

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
