### ISSUE TITLE
🐞Product widget on mobile device is at only 50% width.

### ISSUE THREAD

**Issue by KodakoDesign** [elementor/elementor#18166]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Product widget on mobile device is at only 50% width despite being set to 1 column and width at 100%.

### Steps to reproduce

Checkout the widget on any mobile device.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.32-35
	PHP Version: 7.4.28
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.2
	Site URL: https://beayourself.com.au
	Home URL: https://beayourself.com.au
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: studio@kodako.com.au
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.5.0
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:98.0) Gecko/20100101 Firefox/98.0

== Active Plugins ==
	Elementor
		Version: 3.5.6
		Author: Elementor.com

	Elementor Pro
		Version: 3.6.4
		Author: Elementor.com

	FileBird
		Version: 4.2
		Author: Ninja Team

	Payment Plugins for Stripe WooCommerce
		Version: 3.3.17
		Author: Payment Plugins, support@paymentplugins.com

	PWA for WP
		Version: 1.7.43
		Author: Magazine3

	SiteGround Optimizer
		Version: 7.0.6
		Author: SiteGround

	Site Kit by Google
		Version: 1.70.0
		Author: Google

	WooCommerce
		Version: 6.3.1
		Author: Automattic

	WooCommerce Stripe Gateway
		Version: 6.3.0
		Author: WooCommerce

	WPS Hide Login
		Version: 1.9.3
		Author: WPServeur, NicolasKulka, wpformation

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active by default
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Active
	Hide native WordPress widgets from search results: Active by default
	Default to New Theme Builder: Inactive
	Hello Theme Header & Footer: Inactive by default
	Landing Pages: Active
	Color Sampler: Active
	Favorite Widgets: Active by default
	Admin Top Bar: Active
	Page Transitions: Active by default
	Form Submissions: Active
	Scroll Snap: Active by default

== Log ==
	
PHP: showing 3 of 3PHP: 2021-12-14 21:44:26 [notice X 8][/home/customer/www/bea.kodako.com.au/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-02 07:01:00 [error X 22][/home/customer/www/beayourself.com.au/public_html/wp-content/plugins/elementor-pro/modules/woocommerce/widgets/products.php::195] Uncaught Error: Call to undefined function ElementorPro\Modules\Woocommerce\Widgets\wc_print_notices() in /home/customer/www/beayourself.com.au/public_html/wp-content/plugins/elementor-pro/modules/woocommerce/widgets/products.php:195
Stack trace:
#0 /home/customer/www/beayourself.com.au/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(2188): ElementorPro\Modules\Woocommerce\Widgets\Products->render()
#1 /home/customer/www/beayourself.com.au/public_html/wp-content/plugins/elementor/includes/base/widget-base.php(609): Elementor\Controls_Stack->render_by_mode()
#2 /home/customer/www/beayourself.com.au/public_html/wp-content/plugins/elementor/includes/base/widget-base.php(750): Elementor\Widget_Base->render_content()
#3 /home/customer/www/beayourself.com.au/public_html/wp-content/plugins/elementor/includes/base/element-base.php(447): Elementor\Widget_Base->print_content()
#4 /home/customer/www/beayourself.com.au/public_html/wp-content/plugins/elementor/includes/base/element-base.php(741): [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-04 01:09:55 [notice X 2][/home/customer/www/beayourself.com.au/public_html/wp-content/plugins/elementor/includes/managers/image.php::87] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 20 of 402022-02-27 23:15:21 [info] elementor-pro::elementor_pro_updater Started 
2022-02-27 23:15:21 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-02-27 23:15:21 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-02-27 23:15:21 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.5.2',
  'to' => '3.6.2',
)]
2022-02-27 23:15:21 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.5.2',
  'to' => '3.6.2',
)]
2022-03-01 00:43:58 [info] elementor::elementor_updater Started 
2022-03-01 00:43:58 [info] Elementor/Upgrades - _on_each_version Start  
2022-03-01 00:43:58 [info] Elementor/Upgrades - _on_each_version Finished 
2022-03-01 00:43:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.5',
  'to' => '3.5.6',
)]
2022-03-01 00:43:58 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.5',
  'to' => '3.5.6',
)]
2022-03-02 22:17:30 [info] elementor-pro::elementor_pro_updater Started 
2022-03-02 22:17:30 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-03-02 22:17:30 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-03-02 22:17:30 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.2',
  'to' => '3.6.3',
)]
2022-03-02 22:17:30 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.2',
  'to' => '3.6.3',
)]
2022-03-15 22:49:53 [info] elementor-pro::elementor_pro_updater Started 
2022-03-15 22:49:53 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-03-15 22:49:53 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-03-15 22:49:53 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.3',
  'to' => '3.6.4',
)]
2022-03-15 22:49:53 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.3',
  'to' => '3.6.4',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

**Comment by KodakoDesign** [comment]
SiteGround Optimiser plugin compress CSS option will cause this problem.
