### ISSUE TITLE
🐞 Bug report: 

### ISSUE THREAD

**Issue by sciam-digitalmedien** [elementor/elementor#18175]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest development version of Elementor.

### Description

We are testing 3.6.0 beta 4 and find the following issue: With this version installed and the latest version of crocoblock jet engine being activated the elementor editor is not loading.

### Steps to reproduce

Install 3.6.0 beta 4 (it might well have been the case with previous beta-versions)
Activate crocoblock jet engine

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [X] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Ubuntu 18.04 v5.6.49-89.0
	PHP Version: 8.0.15
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.2
	Site URL: https://dev.sciam-digitalmedien.at
	Home URL: https://dev.sciam-digitalmedien.at
	WP Multisite: No
	Max Upload Size: 8 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: de-DE
	Timezone: 0
	Admin Email: martin.oegg@sciam.at
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.5.0
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: de_DE_formal
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0

== Active Plugins ==
	All In One WP Security
		Version: 4.4.10
		Author: Tips and Tricks HQ, Peter Petreski, Ruhul, Ivy

	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Elementor
		Version: 3.6.0-beta4
		Author: Elementor.com

	Elementor Pro
		Version: 3.6.4
		Author: Elementor.com

	GDPR Cookie Compliance
		Version: 4.8.1
		Author: Moove Agency

	JetEngine
		Version: 2.11.5
		Author: Crocoblock

	Math Captcha for Elementor Forms
		Version: 1.1.0
		Author: Albano Toska

	Rank Math SEO
		Version: 1.0.84
		Author: Rank Math

	Rank Math SEO PRO
		Version: 3.0.8
		Author: Rank Math

== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

== Elementor Experiments ==
	Optimized DOM Output: Inactive
	Improved Asset Loading: Inactive
	Improved CSS Loading: Inactive
	Inline Font Icons: Inactive
	Accessibility Improvements: Inactive
	Import Export Template Kit: Inactive
	Additional Custom Breakpoints: Inactive
	Hide native WordPress widgets from search results: Inactive
	: Inactive by default
	Flexbox Container: Inactive
	Default to New Theme Builder: Inactive
	Hello Theme Header & Footer: Inactive
	Landing Pages: Inactive
	Color Sampler: Inactive
	Favorite Widgets: Inactive
	Admin Top Bar: Inactive
	Page Transitions: Inactive
	Form Submissions: Inactive
	Scroll Snap: Inactive

== Log ==
	
Log: showing 20 of 382022-01-23 15:25:49 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.8',
  'to' => '3.5.4',
)]
2022-01-23 15:25:50 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.8',
  'to' => '3.5.4',
)]
2022-03-16 20:38:38 [info] elementor::elementor_updater Started 
2022-03-16 20:38:38 [info] Elementor/Upgrades - _on_each_version Start  
2022-03-16 20:38:38 [info] Elementor/Upgrades - _on_each_version Finished 
2022-03-16 20:38:38 [info] Elementor/Upgrades - _v_3_5_0_remove_old_elementor_scheme Start  
2022-03-16 20:38:38 [info] Elementor/Upgrades - _v_3_5_0_remove_old_elementor_scheme Finished 
2022-03-16 20:38:38 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.4',
  'to' => '3.5.6',
)]
2022-03-16 20:45:18 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.5.1',
  'to' => '3.6.4',
)]
2022-03-16 20:45:18 [info] elementor-pro::elementor_pro_updater Started 
2022-03-16 20:45:18 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-03-16 20:45:18 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-03-16 20:45:18 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.5.1',
  'to' => '3.6.4',
)]
2022-03-16 20:45:20 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.5.1',
  'to' => '3.6.4',
)]
2022-03-16 20:45:40 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.6',
  'to' => '3.6.0-beta4',
)]
2022-03-16 20:45:40 [info] elementor::elementor_updater Started 
2022-03-16 20:45:40 [info] Elementor/Upgrades - _on_each_version Start  
2022-03-16 20:45:40 [info] Elementor/Upgrades - _on_each_version Finished 
2022-03-16 20:45:40 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.6',
  'to' => '3.6.0-beta4',
)]
2022-03-16 20:45:42 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.6',
  'to' => '3.6.0-beta4',
)]

PHP: showing 5 of 5PHP: 2022-01-23 15:25:44 [error X 1][/var/www/vhosts/sciam-digitalmedien.at/sciam-digitalmedien.at/wp_210926/wp-content/plugins/elementor/core/editor/editor.php::869] Uncaught Error: Call to a member function register_controller() on null in /var/www/vhosts/sciam-digitalmedien.at/sciam-digitalmedien.at/wp_210926/wp-content/plugins/elementor/core/editor/editor.php:869
Stack trace:
#0 /var/www/vhosts/sciam-digitalmedien.at/sciam-digitalmedien.at/wp_210926/wp-content/plugins/elementor/includes/plugin.php(750): Elementor\Core\Editor\Editor-&gt;__construct()
#1 /var/www/vhosts/sciam-digitalmedien.at/sciam-digitalmedien.at/wp_210926/wp-content/plugins/elementor/includes/plugin.php(671): Elementor\Plugin-&gt;init_components()
#2 /var/www/vhosts/sciam-digitalmedien.at/sciam-digitalmedien.at/wp_210926/wp-includes/class-wp-hook.php(303): Elementor\Plugin-&gt;init()
#3 /var/www/vhosts/sciam-digitalmedien.at/sciam-digitalmedien.at/wp_210926/wp-includes/class-wp-hook.php(327): WP_Hook-&gt;apply_filters()
#4 /var/www/vhosts/sciam-digitalmedien.at/sciam-digitalmedien.at/wp_210926/wp-includes/plugin.php(470): WP_Hook-&gt;do_action()
#5 /var/www/vhosts/sciam-digitalmedien.at/sciam-digitalmedien.at/wp_210926/wp-settings.php(578): do_action()
#6 /var/www/vhosts/sciam-digitalmedien.at/sciam-digitalmedien.at/wp_210926/wp-config.php(71): require_once(&#039;...&#039;)
#7 /var/www/vhosts/sciam-digitalmedien.at/sciam-digitalmedien.at/wp_210926/wp-load.php(50): require_once(&#039;...&#039;)
#8 /var/www/vhosts/sciam-digitalmedien.at/sciam-digitalmedien.at/wp_210926/wp-cron.php(44): require_once(&#039;...&#039;)
#9 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-16 09:34:10 [warning X 4][/var/www/vhosts/sciam-digitalmedien.at/sciam-digitalmedien.at/wp_210926/wp-content/plugins/elementor-pro/license/updater.php::83] Undefined array key &quot;new_version&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-16 20:45:44 [notice X 26][/var/www/vhosts/sciam-digitalmedien.at/sciam-digitalmedien.at/wp_210926/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-16 20:45:50 [notice X 9][/var/www/vhosts/sciam-digitalmedien.at/sciam-digitalmedien.at/wp_210926/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /var/www/vhosts/sciam-digitalmedien.at/sciam-digitalmedien.at/wp_210926/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /var/www/vhosts/sciam-digitalmedien.at/sciam-digitalmedien.at/wp_210926/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /var/www/vhosts/sciam-digitalmedien.at/sciam-digitalmedien.at/wp_210926/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /var/www/vhosts/sciam-digitalmedien.at/sciam-digitalmedien.at/wp_210926/wp-content/plugins/jet-engine/framework/jet-elementor-extension/jet-elementor-extension.php(95): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-03-16 21:11:12 [warning X 1][/var/www/vhosts/sciam-digitalmedien.at/sciam-digitalmedien.at/wp_210926/wp-content/plugins/elementor/core/experiments/experiments-reporter.php::89] Undefined array key &quot;title&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible
	Math Captcha for Elementor Forms: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by pgrawinkel** [comment]
Seems like a dependency issue. Install and activate WooCommerce and the problem is gone. This is only a workaround. Of course, an update is needed here.
