### ISSUE TITLE
🐞 Bug report: Post Image background only use Mobile-size while running template thru custom loop.

### ISSUE THREAD

**Issue by glorpyz** [elementor/elementor#18228]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When I created a section.
And go to setting: -> Style -> Background -> Normal -> Classic -> background button -> Dynamic Tags  -> Post Image.
[Featured image, Current, Imagesize]

I choose 3 different sizes, one for Desktop, one for Laptop and one for Mobile.

This works, until I run this template thru Ele Custom Skin (custom loop).

Then it will only display the size set for Mobile and use it for the others also.

### Steps to reproduce

Hello Theme.
Make a section.
Set background image, but choose Post Image and click on it again to see the settings.
Choose featured image, current.
Then set one size for Desktopmode. One size for Laptop mode, and one for mobile.
Run template thru custom loop , and it will only show the setting set for mobile.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

							
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.4.24
	PHP Version: 8.0.16
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.2
	WP Multisite: No
	Max Upload Size: 8 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: c.s@ownit.nu
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.5.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US

== Active Plugins ==
	Code Snippets
		Version: 2.14.3
		Author: Code Snippets Pro

	Disable Media Pages
		Version: 1.2.2
		Author: Johannes Siipola

	Duplicate Page
		Version: 4.4.8
		Author: mndpsingh287

	e-addons EXTENDED
		Version: 2.2.3
		Author: Nerds Farm

	e-addons for Elementor
		Version: 3.0.9
		Author: Nerds Farm

	Ele Custom Skin
		Version: 3.1.4
		Author: Dudaster.com

	Ele Custom Skin Pro
		Version: 3.2.3
		Author: Dudaster.com

	Elementor
		Version: 3.5.6
		Author: Elementor.com

	Elementor Pro
		Version: 3.6.4
		Author: Elementor.com

	EWWW Image Optimizer
		Version: 6.4.2
		Author: Exactly WWW

	Limit Login Attempts Reloaded
		Version: 2.23.2
		Author: Limit Login Attempts Reloaded

	LiteSpeed Cache
		Version: 4.5.0.1
		Author: LiteSpeed Technologies

	Mandatory Excerpt
		Version: 1.1.1
		Author: theMikeD

	Really Simple SSL
		Version: 5.3.0
		Author: Really Simple Plugins

	Regenerate Thumbnails
		Version: 3.1.5
		Author: Alex Mills (Viper007Bond)

== Must-Use Plugins ==
	WordPress automation by Installatron
		Version: 
		Author: 

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Inactive
	Hide native WordPress widgets from search results: Active by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
PHP: showing 7 of 7PHP: 2022-02-05 14:00:24 [warning X 72][ wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-05 15:57:55 [error X 4][ wp-content/plugins/elementor/includes/template-library/manager.php::457] Uncaught Error: Cannot use object of type WP_Error as array in  wp-content/plugins/elementor/includes/template-library/manager.php:457
Stack trace:
#0 [internal function]: Elementor\TemplateLibrary\Manager->import_template()
#1  wp-content/plugins/elementor/includes/template-library/manager.php(550): call_user_func()
#2  wp-content/plugins/elementor/includes/template-library/manager.php(582): Elementor\TemplateLibrary\Manager->handle_ajax_request()
#3 [internal function]: Elementor\TemplateLibrary\Manager->Elementor\TemplateLibrary\{closure}()
#4  wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func()
#5  wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#6  wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#7  wp-includes/plugin.php(474): WP_Hook->do_action()
#8  wp-admin/admin-ajax.php(187): do_action()
#9 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-05 16:05:35 [warning X 2][ wp-content/plugins/elementor/includes/managers/image.php::87] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-06 13:24:18 [warning X 4][ wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::167] Undefined array key "editor_post_id" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-13 13:00:59 [error X 3][ wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::286] Uncaught Error: Call to a member function update_meta() on bool in  wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:286
Stack trace:
#0  wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions()
#2  wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func()
#3  wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#4  wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#5  wp-includes/plugin.php(474): WP_Hook->do_action()
#6  wp-admin/admin-ajax.php(187): do_action()
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-27 16:31:31 [warning X 103][ wp-content/plugins/elementor/includes/controls/base-multiple.php::87] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-02 16:29:56 [error X 4][ wp-content/plugins/elementor/core/documents-manager.php::493] Uncaught Error: Call to a member function is_built_with_elementor() on bool in  wp-content/plugins/elementor/core/documents-manager.php:493
Stack trace:
#0 [internal function]: Elementor\Core\Documents_Manager->ajax_save()
#1  wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func()
#2  wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#3  wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#4  wp-includes/plugin.php(474): WP_Hook->do_action()
#5  wp-admin/admin-ajax.php(187): do_action()
#6 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 9 of 9JS: 2022-02-05 20:46:42 [error X 15][wp-content/plugins/ele-custom-skin-pro/assets/js/ecspro.js?ver=3.2.1:172:44] this.swiper.params is undefined 
JS: 2022-02-06 20:33:31 [error X 59][wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.5:2:453830] T is null 
JS: 2022-02-09 20:13:07 [error X 17][wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.5:2:245864] T.params.args.data is undefined 
JS: 2022-02-12 19:45:34 [error X 5][wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.5:2:582472] T is undefined 
JS: 2022-02-15 16:36:15 [error X 2][wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.5:2:558642] elementorFrontend is not defined 
JS: 2022-02-19 16:33:14 [error X 103][wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:19643] this.getColorRepresentation() is null 
JS: 2022-02-24 19:10:38 [error X 1][wp-admin/load-scripts.php?c=0&loadchunk_0=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&loadchunk_1=hooks&ver=5.9.1:4:0] Permission denied to access property \"addEventListener\" on cross-origin object 
JS: 2022-02-24 19:10:38 [error X 1][wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.5:2:0] Permission denied to access property \"jQuery\" on cross-origin object 
JS: 2022-02-24 19:10:38 [error X 1][wp-includes/js/jquery/jquery.min.js?ver=3.6.0:2:0] Permission denied to access property \"jQuery360032163192782222641\" on cross-origin object 

Log: showing 20 of 252022-02-15 16:15:58 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.1',
  'to' => '3.6.2',
)]
2022-02-15 16:15:58 [info] elementor-pro::elementor_pro_updater Started 
2022-02-15 16:15:58 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-02-15 16:15:58 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-02-15 16:15:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.1',
  'to' => '3.6.2',
)]
2022-02-28 17:10:16 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.5',
  'to' => '3.5.6',
)]
2022-02-28 17:10:17 [info] elementor-pro::elementor_pro_updater Started 
2022-02-28 17:10:17 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-02-28 17:10:17 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-02-28 17:10:17 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.2',
  'to' => '3.6.3',
)]
2022-02-28 17:10:17 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.2',
  'to' => '3.6.3',
)]
2022-02-28 17:10:17 [info] elementor::elementor_updater Started 
2022-02-28 17:10:17 [info] Elementor/Upgrades - _on_each_version Start  
2022-02-28 17:10:17 [info] Elementor/Upgrades - _on_each_version Finished 
2022-02-28 17:10:17 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.5',
  'to' => '3.5.6',
)]
2022-03-15 17:17:21 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.3',
  'to' => '3.6.4',
)]
2022-03-15 17:17:22 [info] elementor-pro::elementor_pro_updater Started 
2022-03-15 17:17:22 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-03-15 17:17:22 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-03-15 17:17:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.3',
  'to' => '3.6.4',
)]

== Elementor - Compatibility Tag ==
	
	e-addons for Elementor: Compatible
	Ele Custom Skin: Compatible
	Ele Custom Skin Pro: Compatible
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==
	
	Ele Custom Skin: Incompatible
	Ele Custom Skin Pro: Compatible

**Comment by rami-elementor** [comment]
@glorpyz 

Sounds like this is not an "Elementor" issue but an addon compatibility issue for the "Ele Custom Skin" plugin.

If it's not an Elementor issue, we can't fix it.
