### ISSUE TITLE
🐞 Bug report: After updating to Elementor 3.6.0 Pages and Posts can't be accessed anymore (as well as some pages)

### ISSUE THREAD

**Issue by echojojo** [elementor/elementor#18240]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

After updating to the latest Elementor Version 3.6.0 the pages / posts admin pages don't load anymore. They just display the raw page source code.

Furthermore some pages won't load anymore with the following error.

`
 Fatal error: Uncaught Error: Class 'Elementor\Scheme_Typography' not found
in /home/wp/disk/wordpress/wp-content/plugins/table-addons-for-elementor/includes/class-table-addons-for-elementor-widget.php online 518

Call stack:

Table_Addons_For_Elementor_Widget::_register_controls()
wp-content/plugins/elementor/includes/base/controls-stack.php:2280
Elementor\Controls_Stack::init_controls()
wp-content/plugins/elementor/includes/base/controls-stack.php:494
Elementor\Controls_Stack::get_stack()
wp-content/plugins/elementor/includes/base/widget-base.php:177
Elementor\Widget_Base::get_stack()
wp-content/plugins/elementor/includes/base/controls-stack.php:300
Elementor\Controls_Stack::get_controls()
wp-content/plugins/elementor/includes/base/controls-stack.php:2369
Elementor\Controls_Stack::sanitize_settings()
wp-content/plugins/elementor/includes/base/controls-stack.php:1105
Elementor\Controls_Stack::get_data()
wp-content/plugins/elementor/includes/base/controls-stack.php:2116
Elementor\Controls_Stack::get_init_settings()
wp-content / plugins / elementor / core / base / base-object.php: 142
Elementor\C\B\Base_Object::ensure_settings()
wp-content / plugins / elementor / core / base / base-object.php: 40
Elementor\C\B\Base_Object::get_settings()
wp-content/plugins/elementor/core/files/css/post.php:296
Elementor\C\F\C\Post::render_styles()
wp-content/plugins/elementor/core/files/css/post.php:226
Elementor\C\F\C\Post::add_controls_stack_style_rules()
wp-content/plugins/elementor/core/files/css/post.php:298
Elementor\C\F\C\Post::render_styles()
wp-content/plugins/elementor/core/files/css/post.php:226
Elementor\C\F\C\Post::add_controls_stack_style_rules()
wp-content/plugins/elementor/core/files/css/base.php:753
Elementor\C\F\C\Base::add_repeater_control_style_rules()
wp-content/plugins/elementor/core/files/css/base.php:513
Elementor\C\F\C\Base::add_controls_stack_style_rules()
wp-content/plugins/elementor/core/files/css/post.php:222
Elementor\C\F\C\Post::add_controls_stack_style_rules()
wp-content/plugins/elementor/core/files/css/post.php:298
Elementor\C\F\C\Post::render_styles()
wp-content/plugins/elementor/core/files/css/post.php:226
Elementor\C\F\C\Post::add_controls_stack_style_rules()
wp-content/plugins/elementor/core/files/css/post.php:298
Elementor\C\F\C\Post::render_styles()
wp-content/plugins/elementor/core/files/css/post.php:226
Elementor\C\F\C\Post::add_controls_stack_style_rules()
wp-content/plugins/elementor/core/files/css/base.php:753
Elementor\C\F\C\Base::add_repeater_control_style_rules()
wp-content/plugins/elementor/core/files/css/base.php:513
Elementor\C\F\C\Base::add_controls_stack_style_rules()
wp-content/plugins/elementor/core/files/css/post.php:222
Elementor\C\F\C\Post::add_controls_stack_style_rules()
wp-content/plugins/elementor/core/files/css/post.php:298
Elementor\C\F\C\Post::render_styles()
wp-content/plugins/elementor/core/files/css/post.php:178
Elementor\C\F\C\Post::render_css()
wp-content/plugins/elementor/core/files/css/base.php:632
Elementor\C\F\C\Base::parse_content()
wp-content/plugins/elementor/core/files/base.php:180
Elementor\C\F\Base::update_file()
wp-content/plugins/elementor/core/files/css/base.php:131
Elementor\C\F\C\Base::update()
wp-content/plugins/elementor/core/files/css/base.php:218
Elementor\C\F\C\Base::enqueue()
wp-content/plugins/elementor/core/files/css/post.php:201
Elementor\C\F\C\Post::enqueue()
wp-content/plugins/elementor/includes/frontend.php:639
Elementor\Frontend::enqueue_styles()
wp-content/plugins/jet-theme-core/includes/locations.php:105
Jet_Theme_Core_Locations::enqueue_styles()
wp-includes/class-wp-hook.php:307
WP_Hook::apply_filters()
wp-includes/class-wp-hook.php:331
WP_Hook::do_action()
wp-includes/plugin.php:474
do_action()
wp-includes/script-loader.php:2105
wp_enqueue_scripts()
wp-includes/class-wp-hook.php:307
WP_Hook::apply_filters()
wp-includes/class-wp-hook.php:331
WP_Hook::do_action()
wp-includes/plugin.php:474
do_action()
wp-includes/general-template.php:3042
wp_head()
wp-content/plugins/elementor/modules/page-templates/templates/canvas.php:19
include()
wp-includes/template-loader.php:106
require_once()
wp-blog-header.php:19
require()
index.php:17
`

### Steps to reproduce

Running Wordpress 5.9.2, update Elementor from 3.5.6 to 3.6.0. We do have Elementor Pro 3.6.4 installed.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.17.5
	MySQL version: mariadb.org binary distribution v10.4.24
	PHP Version: 7.4.25
	PHP Max Input Vars: 10000
	PHP Max Post Size: 2000M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.2
	Site URL: https://echometerapp.com
	Home URL: https://echometerapp.com
	WP Multisite: No
	Max Upload Size: 2 GB
	Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Europe/Berlin
	Admin Email: info@echometer.de
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.5.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36

== Active Plugins ==
	Advanced Post Queries
		Version: 1.0.15
		Author: Shabti Kaplan

	Broken Link Checker
		Version: 1.11.16
		Author: WPMU DEV

	Cookie Notice & Compliance for GDPR / CCPA
		Version: 2.2.3
		Author: Hu-manity.co

	Crocoblock Wizard
		Version: 1.2.0
		Author: Crocoblock

	Disk Usage Sunburst
		Version: 1.1.3
		Author: raidboxes.io

	Duplicate Menu
		Version: 0.2.2
		Author: Jonathan Christopher

	Duplicate Page
		Version: 4.4.8
		Author: mndpsingh287

	Ele Custom Skin
		Version: 3.1.4
		Author: Dudaster.com

	Elementor
		Version: 3.5.6
		Author: Elementor.com

	Elementor Pro
		Version: 3.6.4
		Author: Elementor.com

	Enable Media Replace
		Version: 3.6.3
		Author: ShortPixel

	Essential Addons for Elementor
		Version: 5.0.11
		Author: WPDeveloper

	Export Media Library
		Version: 3.0.1
		Author: Mass Edge Inc.

	Header Footer Code Manager
		Version: 1.1.18
		Author: 99robots

	iframe
		Version: 4.5
		Author: webvitaly

	JetBlocks For Elementor
		Version: 1.3.0
		Author: Crocoblock

	JetBlog For Elementor
		Version: 2.2.15
		Author: Crocoblock

	JetElements For Elementor
		Version: 2.6.2
		Author: Crocoblock

	JetEngine
		Version: 2.11.5
		Author: Crocoblock

	JetMenu
		Version: 2.1.6
		Author: Crocoblock

	JetPopup
		Version: 1.5.5
		Author: Crocoblock

	JetSearch For Elementor
		Version: 2.1.15
		Author: Crocoblock

	JetSmartFilters
		Version: 2.3.10
		Author: Crocoblock

	JetTabs For Elementor
		Version: 2.1.15
		Author: Crocoblock

	JetThemeCore
		Version: 1.2.2
		Author: Crocoblock

	JetTricks
		Version: 1.4.0
		Author: Crocoblock

	Lead Forensics
		Version: 3.3.8
		Author: Lead Forensics

	Make Column Clickable Elementor
		Version: 1.3.1
		Author: Fernando Acosta

	Media Cleaner
		Version: 6.3.2
		Author: Jordy Meow

	PDF viewer for Elementor
		Version: 2.9.3
		Author: RedLettuce Plugins

	reSmush.it Image Optimizer
		Version: 0.4.2
		Author: reSmush.it

	Safe SVG
		Version: 1.9.10
		Author: 10up

	Simple 301 Redirects
		Version: 2.0.6
		Author: WPDeveloper

	Smush
		Version: 3.9.5
		Author: WPMU DEV

	Table Addons for Elementor
		Version: 1.1.0
		Author: Iqbal Bary

	TranslatePress - Business
		Version: 1.1.0
		Author: Cozmoslabs, Razvan Mocanu, Madalin Ungureanu

	TranslatePress - Multilingual
		Version: 2.2.3
		Author: Cozmoslabs, Razvan Mocanu, Madalin Ungureanu, Cristophor Hurduban

	UpdraftPlus - Backup/Restore
		Version: 1.22.11
		Author: UpdraftPlus.Com, DavidAnderson

	User Profile Picture
		Version: 2.6.0
		Author: Cozmoslabs

	UTMs Carry Pages
		Version: 1.0
		Author: Riccardo Bertolini

	Velvet Blues Update URLs
		Version: 3.2.10
		Author: VelvetBlues.com

	Wordfence Security
		Version: 7.5.8
		Author: Wordfence

	WP-Sweep
		Version: 1.1.5
		Author: Lester 'GaMerZ' Chan

	WP Activity Log
		Version: 4.4.0
		Author: WP White Security

	Yoast SEO
		Version: 18.3
		Author: Team Yoast

	Yoast SEO Premium
		Version: 18.1
		Author: Team Yoast

== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

== Elements Usage ==
	
	archive : 4
		archive-posts : 1
		button : 1
		heading : 6
		icon-list : 1
		image : 2
		jet-ajax-search : 1
		jet-listing-grid : 1
		text-editor : 1
	header : 2
		button : 1
		image : 1
		nav-menu : 2
		text-editor : 1
	loop : 3
		button : 1
		icon-list : 1
		image : 1
		text-editor : 1
		theme-post-featured-image : 1
		theme-post-title : 2
	page : 23
		alert : 3
		button : 9
		heading : 7
		html : 3
		icon-list : 3
		image : 7
		shortcode : 13
		spacer : 1
		text-editor : 26
		video : 9
	popup : 6
		image : 1
		shortcode : 1
		spacer : 1
		text-editor : 2
	section : 22
		heading : 1
		image : 2
		shortcode : 2
		text-editor : 1
	wp-post : 113
		alert : 1
		blockquote : 1
		button : 5
		divider : 3
		eael-advanced-data-table : 2
		eael-creative-button : 1
		eael-feature-list : 1
		heading : 73
		icon-list : 1
		image : 29
		menu-anchor : 7
		shortcode : 28
		spacer : 2
		text-editor : 152
		video : 3
	wp-page : 83
		blockquote : 1
		button : 20
		counter : 1
		divider : 22
		eael-pricing-table : 3
		heading : 176
		html : 12
		icon : 1
		icon-list : 30
		image : 111
		jet-ajax-search : 1
		jet-listing-grid : 1
		menu-anchor : 5
		pdfjs_viewer : 1
		posts : 14
		shortcode : 32
		spacer : 29
		testimonial : 11
		testimonial-carousel : 2
		text-editor : 150
		theme-site-logo : 2
		video : 14
	single-post : 6
		author-box : 2
		button : 6
		divider : 2
		form : 2
		heading : 30
		icon-list : 9
		image : 10
		jet-ajax-search : 1
		jet-listing-grid : 1
		nav-menu : 2
		post-info : 2
		posts : 5
		share-buttons : 2
		shortcode : 6
		spacer : 2
		text-editor : 5
		theme-post-content : 5
		theme-post-featured-image : 3
		theme-post-title : 5
		theme-site-logo : 2
		video : 1
	search-results : 1
		archive-posts : 1
		button : 1
		heading : 3
		image : 1
		jet-ajax-search : 1

== Elementor Experiments ==
	Optimized DOM Output: Inactive by default
	Improved Asset Loading: Active
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Inactive by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Inactive by default
	Hide native WordPress widgets from search results: Active by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Inactive by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 20 of 302022-03-14 08:57:31 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-03-14 08:57:31 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-03-14 08:57:31 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.2',
  'to' => '3.6.3',
)]
2022-03-14 08:57:32 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.2',
  'to' => '3.6.3',
)]
2022-03-14 08:57:36 [info] elementor-pro::elementor_pro_updater Started 
2022-03-14 08:57:36 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-03-14 08:57:36 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-03-14 08:57:36 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.2',
  'to' => '3.6.3',
)]
2022-03-17 10:36:07 [info] elementor-pro::elementor_pro_updater Started 
2022-03-17 10:36:07 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-03-17 10:36:07 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-03-17 10:36:07 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.3',
  'to' => '3.6.4',
)]
2022-03-17 10:36:07 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.3',
  'to' => '3.6.4',
)]
2022-03-17 10:36:08 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.3',
  'to' => '3.6.4',
)]
2022-03-23 17:08:30 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.6',
  'to' => '3.6.0',
)]
2022-03-23 17:08:34 [info] elementor::elementor_updater Started 
2022-03-23 17:08:34 [info] Elementor/Upgrades - _on_each_version Start  
2022-03-23 17:08:42 [info] Elementor/Upgrades - _on_each_version Finished 
2022-03-23 17:08:42 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.6',
  'to' => '3.6.0',
)]
2022-03-23 17:08:45 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.6',
  'to' => '3.6.0',
)]

JS: showing 6 of 6JS: 2022-02-22 09:20:44 [error X 3][https://echometerapp.com/wp-content/plugins/elementor/assets/js/common.min.js?ver=3.5.5:2:145590] Cannot read properties of undefined (reading \'toLowerCase\') 
JS: 2022-02-22 09:20:47 [error X 1][https://echometerapp.com/wp-content/plugins/elementor/assets/js/common.min.js?ver=3.5.5:2:140375] Cannot read properties of undefined (reading \'$activeItem\') 
JS: 2022-03-09 07:16:10 [error X 2][https://echometerapp.com/wp-content/plugins/elementor/assets/js/common.min.js?ver=3.5.6:2:91631] Routes: `panel/page-settings/yoast-tab` not found. 
JS: 2022-03-10 11:51:14 [error X 1][https://echometerapp.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.6:2:327413] Cannot read properties of undefined (reading \'model\') 
JS: 2022-03-10 16:01:15 [error X 1][https://echometerapp.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.6:2:610977] Cannot read properties of null (reading \'history\') 
JS: 2022-03-21 07:49:25 [error X 6][https://echometerapp.com/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=3.6.4:2:10003] Failed to execute \'observe\' on \'IntersectionObserver\': parameter 1 is not of type \'Element\'. 

PHP: showing 6 of 6PHP: 2022-03-14 13:01:42 [notice X 7][/home/wp/disk/wordpress/wp-content/plugins/elementor/core/app/modules/import-export/module.php::91] Trying to get property 'label' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-16 16:49:46 [notice X 2][/home/wp/disk/wordpress/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-17 10:24:09 [error X 1][/home/wp/disk/wordpress/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::286] Uncaught Error: Call to a member function update_meta() on bool in /home/wp/disk/wordpress/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:286
Stack trace:
#0 /home/wp/disk/wordpress/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions()
#2 /home/wp/disk/wordpress/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func()
#3 /home/wp/disk/wordpress/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#4 /home/wp/disk/wordpress/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#5 /home/wp/disk/wordpress/wp-includes/plugin.php(474): WP_Hook->do_action()
#6 /home/wp/disk/wordpress/wp-admin/admin-ajax.php(187): do_action()
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-17 10:24:15 [notice X 915][/home/wp/disk/wordpress/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $finder_category_name argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-23 17:08:43 [notice X 46][/home/wp/disk/wordpress/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-23 17:15:30 [notice X 2][/home/wp/disk/wordpress/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $finder_category_name argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/wp/disk/wordpress/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /home/wp/disk/wordpress/wp-content/plugins/elementor/core/common/modules/finder/categories-manager.php(68): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home/wp/disk/wordpress/wp-content/plugins/elementor/core/common/modules/finder/categories-manager.php(50): Elementor\Core\Common\Modules\Finder\Categories_Manager -> register()
#4: /home/wp/disk/wordpress/wp-content/plugins/jet-popup/includes/elementor-finder/elementor-finder.php(47): Elementor\Core\Common\Modules\Finder\Categories_Manager -> add_category()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	Essential Addons for Elementor: Compatibility not specified
	JetBlocks For Elementor: Compatibility not specified
	JetBlog For Elementor: Compatibility not specified
	JetElements For Elementor: Compatibility not specified
	JetSearch For Elementor: Compatibility not specified
	JetTabs For Elementor: Compatibility not specified
	Make Column Clickable Elementor: Compatibility not specified
	PDF viewer for Elementor: Compatibility not specified
	Table Addons for Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by echojojo** [comment]
Sry I didn't look properly. It has been reported multiple times.
