### ISSUE TITLE
🐞 Bug report: LearnDash course pages not displaying properly, had to disable Elementor Pro for fix it.

### ISSUE THREAD

**Issue by zamirgo** [elementor/elementor#18329]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

encountered the same problem as Issue [#13725](https://github.com/elementor/elementor/issues/13725), but in my case I need just turn off Element Pro -and the issue is solved.
 I Dwongrade the Elementor Pro version from 3.6.4 back to 2.52 - did not resolve the issue
 I disabled the checkbox in the Elementor settings for the landing pages as advised here - did not resolve the issue.
Please help

### Steps to reproduce

1. The LearnDash LMS system is installed and displays on the course page the option to join the course for registered subscribers on the site under a course defined in LearnDash as a FREE course.
2. When Activate Elementor Pro - the part of joining the course on the Learndash course page disappears and does not allow the user to register as Ennrolled for the course.
3. When you turn off the Elemntor pro - the course page returns to normal and shows the part of joining and registering for the course properly.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.3.34
	PHP Version: 7.4.28
	PHP Memory Limit: 512M
	PHP Max Input Vars: 10240
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.2
	Site URL: https://dev.familyplace.co.il
	Home URL: https://dev.familyplace.co.il
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: he-IL
	Timezone: 2
	Admin Email: zamzamon@gmail.com
	Debug Mode: Active

== Theme ==
	Name: Astra Child
	Version: 1.0.0
	Author: Brainstorm Force
	Child Theme: Yes
	Parent Theme Name: Astra
	Parent Theme Version: 3.7.9
	Parent Theme Author: Brainstorm Force

== User ==
	Role: administrator
	WP Profile lang: he_IL
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.83 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 5.12.1
		Author: Delicious Brains

	All-in-One WP Migration
		Version: 7.57
		Author: ServMask

	Astra Pro
		Version: 3.6.6
		Author: Brainstorm Force

	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Code Snippets
		Version: 2.14.3
		Author: Code Snippets Pro

	Duplicate Page
		Version: 4.4.8
		Author: mndpsingh287

	Elementor
		Version: 3.6.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.6.4
		Author: Elementor.com

	Familyplace
		Version: 1.0.0
		Author: Naveen Verma

	FluentCRM - Marketing Automation For WordPress
		Version: 2.5.8
		Author: Newsletter Team by Fluent CRM

	FluentCRM Pro
		Version: 2.5.7
		Author: Fluent CRM

	Fluent Forms
		Version: 4.3.4
		Author: Contact Form - WPManageNinja LLC

	Fluent Forms Pro Add On Pack
		Version: 4.3.3
		Author: Fluent Forms

	FluentSMTP
		Version: 2.1.1
		Author: FluentSMTP & WPManageNinja Team

	Fluent Support
		Version: 1.5.5
		Author: WPManageNinja LLC

	Fluent Support Pro
		Version: 1.5.5
		Author: WPManageNinja LLC

	iDevAffiliate PMPro Integration
		Version: 2.0
		Author: iDevDirect.com LLC

	JetBlocks For Elementor
		Version: 1.3.1
		Author: Crocoblock

	JetEngine
		Version: 2.11.6
		Author: Crocoblock

	JetPlugins Dynamic Data Addon
		Version: 1.3.1
		Author: Crocoblock

	JetSearch For Elementor
		Version: 2.1.16
		Author: Crocoblock

	JetSmartFilters
		Version: 2.3.11
		Author: Crocoblock

	JetTabs For Elementor
		Version: 2.1.16
		Author: Crocoblock

	JetTricks
		Version: 1.4.1
		Author: Crocoblock

	JSM's Show User Metadata
		Version: 3.0.3
		Author: JS Morisset

	LearnDash LMS
		Version: 4.0.3
		Author: LearnDash

	LearnDash LMS - Paid Memberships Pro
		Version: 1.3.2
		Author: LearnDash

	Loco Translate
		Version: 2.6.1
		Author: Tim Whitlock

	LTR <=> RTL Admin content
		Version: 0.5.7
		Author: Ronny Sherer

	One Click Accessibility
		Version: 2.0.3
		Author: One Click Accessibility

	Paid Memberships Pro
		Version: 2.7.5
		Author: Paid Memberships Pro

	Paid Memberships Pro - Courses for Membership Add On
		Version: 1.0.5
		Author: Paid Memberships Pro

	Paid Memberships Pro - Lock Membership Level
		Version: .3
		Author: Paid Memberships Pro

	Paid Memberships Pro - Register Helper Add On
		Version: 1.7
		Author: Paid Memberships Pro

	Paid Memberships Pro - Takbull Gateway
		Version: 1.1.2.4
		Author: S.P Takbull

	PixelYourSite PRO
		Version: 8.6.9
		Author: PixelYourSite

	PixelYourSite Super Pack
		Version: 3.0.4
		Author: PixelYourSite

	Rank Math SEO
		Version: 1.0.85.1
		Author: Rank Math

	Rank Math SEO PRO
		Version: 3.0.9
		Author: Rank Math

	Search Exclude
		Version: 1.2.6
		Author: Roman Pronskiy

	Uncanny Automator
		Version: 3.8.1.1
		Author: Uncanny Automator, Uncanny Owl

	Uncanny Automator Pro
		Version: 3.8.0.1
		Author: Uncanny Owl

	User Profile Picture
		Version: 2.6.0
		Author: Cozmoslabs

	User Role Editor
		Version: 4.61.2
		Author: Vladimir Garagulya

	User Switching
		Version: 1.5.8
		Author: John Blackbourn & contributors

	WP Rocket
		Version: 3.10.9
		Author: WP Media

== Elementor Experiments ==
	פלט DOM שעבר אופטימיזציה: פעיל כברירת מחדל
	טעינת נכסים משופרת: פעיל כברירת מחדל
	Improved CSS Loading: לא פעיל כברירת מחדל
	Inline Font Icons: לא פעיל כברירת מחדל
	שיפורי נגישות: פעיל כברירת מחדל
	Import Export Template Kit: פעיל כברירת מחדל
	Additional Custom Breakpoints: לא פעיל כברירת מחדל
	Hide native WordPress widgets from search results: פעיל כברירת מחדל
	: לא פעיל כברירת מחדל
	Flexbox Container: לא פעיל כברירת מחדל
	Default to New Theme Builder: פעיל כברירת מחדל
	דפי נחיתה: פעיל כברירת מחדל
	דוגם צבע: פעיל כברירת מחדל
	וידג׳טים מעודפים: פעיל כברירת מחדל
	באר עליון אדמין: פעיל כברירת מחדל
	מעבר עמוד: פעיל כברירת מחדל
	לידים: פעיל כברירת מחדל
	Scroll Snap: פעיל כברירת מחדל

== יומן שינויים ==
	
Log: showing 20 of 252022-03-08 09:46:19 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '3.6.2',
  'to' => '3.6.3',
)]
2022-03-08 13:42:47 [info] elementor-pro::elementor_pro_updater Started 
2022-03-08 13:42:47 [info] אלמנטור פרו/Upgrades - _on_each_version Start  
2022-03-08 13:42:47 [info] אלמנטור פרו/Upgrades - _on_each_version Finished 
2022-03-08 13:42:47 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '3.6.2',
  'to' => '3.6.3',
)]
2022-03-22 17:29:21 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'אלמנטור',
  'from' => '3.5.6',
  'to' => '3.6.0',
)]
2022-03-22 17:29:22 [info] elementor::elementor_updater Started 
2022-03-22 17:29:22 [info] אלמנטור/Upgrades - _on_each_version Start  
2022-03-22 17:29:22 [info] אלמנטור/Upgrades - _on_each_version Finished 
2022-03-22 17:29:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור',
  'from' => '3.5.6',
  'to' => '3.6.0',
)]
2022-03-22 17:29:24 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'אלמנטור',
  'from' => '3.5.6',
  'to' => '3.6.0',
)]
2022-03-29 12:13:11 [info] elementor::elementor_updater Started 
2022-03-29 12:13:11 [info] אלמנטור/Upgrades - _on_each_version Start  
2022-03-29 12:13:11 [info] אלמנטור/Upgrades - _on_each_version Finished 
2022-03-29 12:13:11 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור',
  'from' => '3.6.0',
  'to' => '3.6.1',
)]
2022-04-01 07:36:23 [info] elementor-pro::elementor_pro_updater Started 
2022-04-01 07:36:23 [info] אלמנטור פרו/Upgrades - _on_each_version Start  
2022-04-01 07:36:23 [info] אלמנטור פרו/Upgrades - _on_each_version Finished 
2022-04-01 07:36:23 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '3.6.3',
  'to' => '3.6.4',
)]
2022-04-01 07:36:24 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '3.6.3',
  'to' => '3.6.4',
)]

PHP: showing 10 of 10PHP: 2022-03-11 14:11:58 [error X 1][/home/familyplace/dev.familyplace.co.il/wp-content/plugins/elementor/core/base/module.php::325] Uncaught Error: Class 'ElementorPro\Modules\Pricing\Widgets\Price_Table' not found in /home/familyplace/dev.familyplace.co.il/wp-content/plugins/elementor/core/base/module.php:325
Stack trace:
#0 /home/familyplace/dev.familyplace.co.il/wp-includes/class-wp-hook.php(307): Elementor\Core\Base\Module->init_widgets(Object(Elementor\Widgets_Manager))
#1 /home/familyplace/dev.familyplace.co.il/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#2 /home/familyplace/dev.familyplace.co.il/wp-includes/plugin.php(474): WP_Hook->do_action(Array)
#3 /home/familyplace/dev.familyplace.co.il/wp-content/plugins/elementor/includes/managers/widgets.php(120): do_action('elementor/widge...', Object(Elementor\Widgets_Manager))
#4 /home/familyplace/dev.familyplace.co.il/wp-content/plugins/elementor/includes/managers/widgets.php(302): Elementor\Widgets_Manager->init_widgets()
#5 /home/familyplace/dev.familyplace.co.il/wp-content/plugins/elementor/includes/elements/column.php(1037): Elementor\Widgets_Manager->get_widget_types('nav-menu')
#6 /home/familyplace/dev.familyplace.co.il/wp-content/ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-11 20:27:56 [error X 1][/home/familyplace/dev.familyplace.co.il/wp-content/plugins/elementor-pro/modules/forms/module.php::145] Uncaught Error: Class 'ElementorPro\Modules\Forms\Submissions\Component' not found in /home/familyplace/dev.familyplace.co.il/wp-content/plugins/elementor-pro/modules/forms/module.php:145
Stack trace:
#0 /home/familyplace/dev.familyplace.co.il/wp-content/plugins/elementor-pro/modules/forms/module.php(175): ElementorPro\Modules\Forms\Module->register_submissions_component()
#1 /home/familyplace/dev.familyplace.co.il/wp-content/plugins/elementor/core/base/module.php(85): ElementorPro\Modules\Forms\Module->__construct()
#2 /home/familyplace/dev.familyplace.co.il/wp-content/plugins/elementor-pro/core/modules-manager.php(84): Elementor\Core\Base\Module::instance()
#3 /home/familyplace/dev.familyplace.co.il/wp-content/plugins/elementor-pro/plugin.php(327): ElementorPro\Core\Modules_Manager->__construct()
#4 /home/familyplace/dev.familyplace.co.il/wp-includes/class-wp-hook.php(307): ElementorPro\Plugin->on_elementor_init('')
#5 /home/familyplace/dev.familyplace.co.il/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#6 /home/familyplace/dev.familyplace.co.il/wp-includes/pl [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-12 21:18:57 [error X 8][/home/familyplace/dev.familyplace.co.il/wp-content/plugins/elementor-pro/modules/query-control/module.php::826] Uncaught Error: Class 'ElementorPro\Modules\QueryControl\Controls\Group_Control_Posts' not found in /home/familyplace/dev.familyplace.co.il/wp-content/plugins/elementor-pro/modules/query-control/module.php:826
Stack trace:
#0 /home/familyplace/dev.familyplace.co.il/wp-includes/class-wp-hook.php(307): ElementorPro\Modules\QueryControl\Module->register_controls(Object(Elementor\Controls_Manager))
#1 /home/familyplace/dev.familyplace.co.il/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#2 /home/familyplace/dev.familyplace.co.il/wp-includes/plugin.php(474): WP_Hook->do_action(Array)
#3 /home/familyplace/dev.familyplace.co.il/wp-content/plugins/elementor/includes/managers/controls.php(474): do_action('elementor/contr...', Object(Elementor\Controls_Manager))
#4 /home/familyplace/dev.familyplace.co.il/wp-content/plugins/elementor/includes/managers/controls.php(590): Elementor\Controls_Manager->register_controls()
#5 /home/familyplace/dev.familyplace.co.il/wp-content/plugins/elementor/includes/managers/controls.php(609): Elementor\Controls_Manager->get_controls [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-12 21:50:21 [error X 4][/home/familyplace/dev.familyplace.co.il/wp-content/plugins/elementor/core/base/module.php::325] Uncaught Error: Class 'ElementorPro\Modules\GlobalWidget\Widgets\Global_Widget' not found in /home/familyplace/dev.familyplace.co.il/wp-content/plugins/elementor/core/base/module.php:325
Stack trace:
#0 /home/familyplace/dev.familyplace.co.il/wp-includes/class-wp-hook.php(307): Elementor\Core\Base\Module->init_widgets(Object(Elementor\Widgets_Manager))
#1 /home/familyplace/dev.familyplace.co.il/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#2 /home/familyplace/dev.familyplace.co.il/wp-includes/plugin.php(474): WP_Hook->do_action(Array)
#3 /home/familyplace/dev.familyplace.co.il/wp-content/plugins/elementor/includes/managers/widgets.php(120): do_action('elementor/widge...', Object(Elementor\Widgets_Manager))
#4 /home/familyplace/dev.familyplace.co.il/wp-content/plugins/elementor/includes/managers/widgets.php(302): Elementor\Widgets_Manager->init_widgets()
#5 /home/familyplace/dev.familyplace.co.il/wp-content/plugins/elementor/includes/elements/column.php(1037): Elementor\Widgets_Manager->get_widget_types('nav-menu')
#6 /home/familyplace/dev.familyplace.co.il/wp-c [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-12 21:50:21 [error X 1][/home/familyplace/dev.familyplace.co.il/wp-content/plugins/elementor-pro/plugin.php::327] Uncaught Error: Class 'ElementorPro\Core\Modules_Manager' not found in /home/familyplace/dev.familyplace.co.il/wp-content/plugins/elementor-pro/plugin.php:327
Stack trace:
#0 /home/familyplace/dev.familyplace.co.il/wp-includes/class-wp-hook.php(307): ElementorPro\Plugin->on_elementor_init('')
#1 /home/familyplace/dev.familyplace.co.il/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#2 /home/familyplace/dev.familyplace.co.il/wp-includes/plugin.php(474): WP_Hook->do_action(Array)
#3 /home/familyplace/dev.familyplace.co.il/wp-content/plugins/elementor/includes/plugin.php(647): do_action('elementor/init')
#4 /home/familyplace/dev.familyplace.co.il/wp-includes/class-wp-hook.php(307): Elementor\Plugin->init('')
#5 /home/familyplace/dev.familyplace.co.il/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#6 /home/familyplace/dev.familyplace.co.il/wp-includes/plugin.php(474): WP_Hook->do_action(Array)
#7 /home/familyplace/dev.familyplace.co.il/wp-settings.php(587): do_action('init')
#8 /home/familyplace/dev.familyplace.co.il/wp-config.php(96): require_once('/home/familypla [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-14 20:35:45 [notice X 13][/home/familyplace/dev.familyplace.co.il/wp-content/plugins/elementor/includes/conditions.php::90] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-14 21:16:12 [notice X 120][/home/familyplace/dev.familyplace.co.il/wp-content/plugins/elementor/core/dynamic-tags/manager.php::73] Array to string conversion [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-14 22:27:40 [notice X 5][/home/familyplace/dev.familyplace.co.il/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php::33] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-27 10:57:30 [notice X 1][/home/familyplace/dev.familyplace.co.il/wp-content/plugins/elementor/includes/managers/image.php::87] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-01 08:51:03 [notice X 1][/home/familyplace/dev.familyplace.co.il/wp-content/plugins/elementor/core/experiments/experiments-reporter.php::89] Undefined index: title [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 8 of 8JS: 2022-03-15 18:48:58 [error X 1][http://dev.familyplace.co.il/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.5.6:2:18381] Cannot read properties of undefined (reading \'top\') 
JS: 2022-03-24 15:31:45 [error X 1][http://dev.familyplace.co.il/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view1622\") has already been destroyed and cannot be used. 
JS: 2022-03-26 10:08:41 [error X 1][http://dev.familyplace.co.il/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view346\") has already been destroyed and cannot be used. 
JS: 2022-03-26 10:09:38 [error X 1][http://dev.familyplace.co.il/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view3755\") has already been destroyed and cannot be used. 
JS: 2022-03-26 18:29:49 [error X 1][http://dev.familyplace.co.il/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view348\") has already been destroyed and cannot be used. 
JS: 2022-03-27 17:13:26 [error X 1][http://dev.familyplace.co.il/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view3436\") has already been destroyed and cannot be used. 
JS: 2022-03-29 10:40:55 [error X 1][https://dev.familyplace.co.il/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view3769\") has already been destroyed and cannot be used. 
JS: 2022-03-29 10:42:03 [error X 1][https://dev.familyplace.co.il/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view5321\") has already been destroyed and cannot be used. 

== אלמנטור - Compatibility Tag ==
	
	Elementor Pro: תואם
	JetBlocks For Elementor: לא תואם
	JetSearch For Elementor: לא תואם
	JetTabs For Elementor: לא תואם

== אלמנטור פרו - Compatibility Tag ==
	
	JetBlocks For Elementor: לא תואם
	JetSearch For Elementor: לא תואם
	JetTabs For Elementor: לא תואם

**Comment by joaodath** [comment]
Hey! Has this been fixed? I'm about to start working on a LearnDash website with Elementor and I want to make sure I'm covering all my bases.
