### ISSUE TITLE
🐞 Bug report: Export Template Kit On Multisite

### ISSUE THREAD

**Issue by petranca** [elementor/elementor#18374]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When I try to export the template kit from a website in a multisite installation, the export setting stops at the selection of the plugins. No plugins are displayed and therefore cannot be selected. The next step to export remains disabled.

### Steps to reproduce

1. Create a wordpress multisite installation with min. 2 websites
2. Install some plugins
3. Try to export from the main website the template kit

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

== Server Environment ==
Operating System: Linux
Software: Apache
MySQL version: MariaDB Server v10.3.32
PHP Version: 7.4.28
PHP Memory Limit: 2048M
PHP Max Input Vars: 200000
PHP Max Post Size: 512M
GD Installed: Yes
ZIP Installed: Yes
Write Permissions: All right
Elementor Library: Connected

== WordPress Environment ==
Version: 5.9.3
Site URL: https://XXX.XXX
Home URL: https://XXX.XXX
WP Multisite: Yes
Max Upload Size: 49 MB
Memory limit: 2048M
Max Memory limit: 720M
Permalink Structure: /blog/%postname%/
Language: de-CH
Timezone: Europe/Zurich
Admin Email: webmaster@petranca.ch
Debug Mode: Inactive

== Theme ==
Name: Hello Elementor Child
Version: 1.0.1
Child Theme: Yes
Parent Theme Name: Hello Elementor
Parent Theme Version: 2.5.0
Parent Theme Author: Elementor Team

== User ==
Role: administrator
WP Profile lang: de_CH
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36

== Active Plugins ==
Elementor
Version: 3.6.2
Author: Elementor.com

Elementor Pro
Version: 3.6.4
Author: Elementor.com

HappyFiles Pro
Version: 1.7
Author: Codeer

JetEngine
Version: 2.11.6
Author: Crocoblock

== Network Plugins ==
Elementor
Version: 3.6.2
Author: Elementor.com

Elementor Pro
Version: 3.6.4
Author: Elementor.com

HappyFiles Pro
Version: 1.7
Author: Codeer

JetEngine
Version: 2.11.6
Author: Crocoblock

TranslatePress - Multilingual
Version: 2.2.4
Author: Cozmoslabs, Razvan Mocanu, Madalin Ungureanu, Cristophor Hurduban

WP GeoIP Country Redirect
Version: 3.6
Author: Crivion

WPvivid Staging
Version: 2.0.10
Author: wpvivid.com

== Elementor Experiments ==
Optimized DOM Output: Active
Improved Asset Loading: Active
Improved CSS Loading: Active
Inline Font Icons: Inactive
Accessibility Improvements: Active
Import Export Template Kit: Active
Additional Custom Breakpoints: Active
Hide native WordPress widgets from search results: Active
: Inactive by default
Flexbox Container: Inactive by default
Default to New Theme Builder: Inactive
Hello Theme Header & Footer: Inactive
Landing Pages: Active
Color Sampler: Active
Favorite Widgets: Active
Admin Top Bar: Inactive
Page Transitions: Active
Form Submissions: Active
Scroll Snap: Inactive

== Log ==

PHP: showing 10 of 10PHP: 2022-03-15 13:48:26 [notice X 8][/home/httpd/vhosts/xxx.xx/xxx.xxx/wp-content/plugins/elementor-pro/license/updater.php::84] Undefined index: new_version [array (
'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-15 14:44:23 [error X 6][/home/httpd/vhosts/xxx.xx/xxx.xxx/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::286] Uncaught Error: Call to a member function update_meta() on null in /home/httpd/vhosts/xxx.xx/xxx.xxx/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:286
Stack trace:
#0 /home/httpd/vhosts/xxx.xx/xxx.xxx/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(6, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/httpd/vhosts/xxx.xx/xxx.xxx/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/httpd/vhosts/xxx.xx/xxx.xxx/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/httpd/vhosts/xxx.xx/xxx.xxx/wp-includes/class-wp-hook.ph [array (
'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-15 15:07:08 [error X 1][/home/httpd/vhosts/xxx.xx/xxx.xxx/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::160] Uncaught Error: Call to a member function get_location() on bool in /home/httpd/vhosts/xxx.xx/xxx.xxx/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:160
Stack trace:
#0 /home/httpd/vhosts/xxx.xx/xxx.xxx/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(104): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->get_conditions_conflicts(447, 'include/general')
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_check_conditions_conflicts(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/httpd/vhosts/xxx.xx/xxx.xxx/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/httpd/vhosts/xxx.xx/xxx.xxx/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/httpd/vhosts/xxx.xx/xxx.xxx/wp-inclu [array (
'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-15 15:07:10 [error X 1][/home/httpd/vhosts/xxx.xx/xxx.xxx/wp-content/plugins/elementor/core/documents-manager.php::493] Uncaught Error: Call to a member function is_built_with_elementor() on bool in /home/httpd/vhosts/xxx.xx/xxx.xxx/wp-content/plugins/elementor/core/documents-manager.php:493
Stack trace:
#0 [internal function]: Elementor\Core\Documents_Manager->ajax_save(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#1 /home/httpd/vhosts/xxx.xx/xxx.xxx/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/httpd/vhosts/xxx.xx/xxx.xxx/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#3 /home/httpd/vhosts/xxx.xx/xxx.xxx/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#4 /home/httpd/vhosts/xxx.xx/xxx.xxx/wp-includes/plugin.php(474): WP_Hook->do_action(Array)
#5 /home/httpd/vhosts/xxx.xx/xxx.xxx/wp-admin/admin-ajax.php(187): do_action('wp_ajax_element...')
#6 {main}
thrown [array (
'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-16 23:09:52 [notice X 1][/home/httpd/vhosts/xxx.xx/xxx.xxx/wp-content/plugins/elementor/includes/template-library/sources/local.php::1385] Undefined index: type [array (
'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-16 23:19:14 [error X 1][/home/httpd/vhosts/xxx.xx/xxx.xxx/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::286] Uncaught Error: Call to a member function update_meta() on bool in /home/httpd/vhosts/xxx.xx/xxx.xxx/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:286
Stack trace:
#0 /home/httpd/vhosts/xxx.xx/xxx.xxx/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/httpd/vhosts/xxx.xx/xxx.xxx/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/httpd/vhosts/xxx.xx/xxx.xxx/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/httpd/vhosts/xxx.xx/xxx.xxx/wp-includes/class-wp-hook [array (
'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-23 15:48:46 [notice X 982][/home/httpd/vhosts/xxx.xx/xxx.xxx/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-23 15:48:48 [notice X 32][/home/httpd/vhosts/xxx.xx/xxx.xxx/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/httpd/vhosts/xxx.xx/xxx.xxx/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /home/httpd/vhosts/xxx.xx/xxx.xxx/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home/httpd/vhosts/xxx.xx/xxx.xxx/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home/httpd/vhosts/xxx.xx/xxx.xxx/wp-content/plugins/jet-engine/framework/jet-elementor-extension/jet-elementor-extension.php(95): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-03-23 21:00:07 [notice X 20][/home/httpd/vhosts/xxx.xx/xxx.xxx/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/httpd/vhosts/xxx.xx/xxx.xxx/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /home/httpd/vhosts/xxx.xx/xxx.xxx/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home/httpd/vhosts/xxx.xx/xxx.xxx/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home/httpd/vhosts/xxx.xx/xxx.xxx/wp-content/plugins/jet-engine/framework/jet-elementor-extension/jet-elementor-extension.php(96): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-04-06 13:26:46 [notice X 2][/home/httpd/vhosts/xxx.xx/xxx.xxx/wp-content/plugins/elementor/core/experiments/experiments-reporter.php::89] Undefined index: title [array (
'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 20 of 222022-03-15 15:14:28 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-03-15 15:14:28 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-03-15 15:14:28 [info] Elementor data updater process has been completed. [array (
'plugin' => 'Elementor Pro',
'from' => '3.6.3',
'to' => '3.6.4',
)]
2022-03-15 15:14:29 [info] Elementor data updater process has been queued. [array (
'plugin' => 'Elementor Pro',
'from' => '3.6.3',
'to' => '3.6.4',
)]
2022-03-23 15:48:35 [info] elementor::elementor_updater Started 
2022-03-23 15:48:35 [info] Elementor/Upgrades - _on_each_version Start  
2022-03-23 15:48:35 [info] Elementor/Upgrades - _on_each_version Finished 
2022-03-23 15:48:35 [info] Elementor data updater process has been completed. [array (
'plugin' => 'Elementor',
'from' => '3.5.6',
'to' => '3.6.0',
)]
2022-03-23 15:48:35 [info] Elementor data updater process has been queued. [array (
'plugin' => 'Elementor',
'from' => '3.5.6',
'to' => '3.6.0',
)]
2022-03-23 20:59:47 [info] Elementor data updater process has been queued. [array (
'plugin' => 'Elementor',
'from' => '3.6.0',
'to' => '3.6.1',
)]
2022-03-23 20:59:48 [info] elementor::elementor_updater Started 
2022-03-23 20:59:48 [info] Elementor/Upgrades - _on_each_version Start  
2022-03-23 20:59:48 [info] Elementor/Upgrades - _on_each_version Finished 
2022-03-23 20:59:48 [info] Elementor data updater process has been completed. [array (
'plugin' => 'Elementor',
'from' => '3.6.0',
'to' => '3.6.1',
)]
2022-04-06 09:27:44 [info] Elementor data updater process has been queued. [array (
'plugin' => 'Elementor',
'from' => '3.6.1',
'to' => '3.6.2',
)]
2022-04-06 09:27:45 [info] elementor::elementor_updater Started 
2022-04-06 09:27:46 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-06 09:27:46 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-06 09:27:46 [info] Elementor data updater process has been completed. [array (
'plugin' => 'Elementor',
'from' => '3.6.1',
'to' => '3.6.2',
)]
2022-04-06 09:27:47 [info] Elementor data updater process has been queued. [array (
'plugin' => 'Elementor',
'from' => '3.6.1',
'to' => '3.6.2',
)]

JS: showing 10 of 10JS: 2022-03-16 22:05:19 [error X 1][https://xxx.xxx/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view72\") has already been destroyed and cannot be used. 
JS: 2022-03-16 22:05:52 [error X 1][https://xxx.xxx/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view888\") has already been destroyed and cannot be used. 
JS: 2022-03-16 22:14:18 [error X 2][https://xxx.xxx/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view79\") has already been destroyed and cannot be used. 
JS: 2022-03-16 23:02:22 [error X 4][https://xxx.xxx/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view87\") has already been destroyed and cannot be used. 
JS: 2022-03-16 23:17:39 [error X 1][https://xxx.xxx/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view94\") has already been destroyed and cannot be used. 
JS: 2022-03-16 23:48:16 [error X 1][https://xxx.xxx/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view6158\") has already been destroyed and cannot be used. 
JS: 2022-03-17 00:00:06 [error X 1][https://xxx.xxx/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view100\") has already been destroyed and cannot be used. 
JS: 2022-03-17 00:06:09 [error X 9][https://xxx.xxx/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view93\") has already been destroyed and cannot be used. 
JS: 2022-03-24 07:10:31 [error X 1][https://xxx.xxx/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:17421] Could not find template: \"#tmpl-elementor-container-content\" 
JS: 2022-03-24 07:10:44 [error X 1][https://xxx.xxx/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:30165] b is not a constructor 

== Elementor - Compatibility Tag ==

Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

**Comment by javothemes** [comment]
Same for me. I can't import. Cuz tab is not showing.
We found an error.

is_built_with_elementor

Fatal error: Uncaught Error: Call to a member function is_built_with_elementor() on bool in /home/customer/www/com/public_html/wp-content/plugins/elementor/core/app/modules/import-export/module.php:409
