### ISSUE TITLE
🐞 Bug report: container background dynamic data (background image and color)

### ISSUE THREAD

**Issue by pafmobile** [elementor/elementor#18385]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When i set the background image or color dynamically with a tag: [acf:background_image] or [acf:background_color] in a section of a template it does not work. Regular (old) sections work fine tough!

### Steps to reproduce

1- Create a section with a container
2- Assign a color dynamically with ACF (this color field is part of a repeater field)
3. Show the repeater field in a page
4. It only show the first section correctly
5. The Old Section/Column works correctly!

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.25 (Debian)
	MySQL version: mariadb.org binary distribution v5.6.49-89.0
	PHP Version: 7.4.28
	PHP Memory Limit: 512M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 50M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.3
	Site URL: https://lnk3.me
	Home URL: https://lnk3.me
	WP Multisite: No
	Max Upload Size: 50 MB
	Memory limit: 512M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: pt-PT
	Timezone: 0
	Admin Email: pafmobile@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Astra Child
	Version: 1.0.0
	Author: Brainstorm Force
	Child Theme: Yes
	Parent Theme Name: Astra
	Parent Theme Version: 3.7.9
	Parent Theme Author: Brainstorm Force

== User ==
	Role: administrator
	WP Profile lang: pt_PT
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36

== Active Plugins ==
	ACF Frontend Pro
		Version: 3.2.14
		Author: Shabti Kaplan

	Advanced Custom Fields PRO
		Version: 5.12.1
		Author: Delicious Brains

	Bestfreebie Elementor Icons
		Version: 1.6
		Author: Bestfreebie

	Breeze
		Version: 2.0.2
		Author: Cloudways

	Change WordPress Login Logo
		Version: 1.1.7
		Author: Boopathi Rajan

	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Custom Post Type UI
		Version: 1.11.2
		Author: WebDevStudios

	Dynamic.ooo - Dynamic Content for Elementor
		Version: 2.4.5
		Author: Dynamic.ooo

	Ele Custom Skin
		Version: 3.1.5
		Author: Dudaster.com

	Elementor
		Version: 3.6.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.6.4
		Author: Elementor.com

	JetElements For Elementor
		Version: 2.6.1
		Author: Crocoblock

	Make Column Clickable Elementor
		Version: 1.3.1
		Author: Fernando Acosta

	MouseWheel Smooth Scroll
		Version: 5.9
		Author: KubiQ

	Pretty Links Developer Edition
		Version: 3.2.4
		Author: Pretty Links

	reSmush.it Image Optimizer
		Version: 0.4.2
		Author: reSmush.it

	SVG Support
		Version: 2.4.2
		Author: Benbodhi

	Theme My Login
		Version: 7.1.4
		Author: Theme My Login

	Theme My Login Moderation
		Version: 1.1
		Author: Theme My Login

	Theme My Login Notifications
		Version: 1.1.1
		Author: Theme My Login

	Woody code snippets (PHP snippets | Insert PHP)
		Version: 2.4.4
		Author: Creative Motion, Will Bontrager Software, LLC <will@willmaster.com>

	Wordfence Security
		Version: 7.5.9
		Author: Wordfence

	Wordpress Logo Changer
		Version: 1.4.1
		Author: Rihanet

	WP Mail SMTP
		Version: 3.3.0
		Author: WPForms

	YIKES Simple Taxonomy Ordering
		Version: 2.3.4
		Author: YIKES, Inc.

	Yoast Duplicate Post
		Version: 4.4
		Author: Enrico Battocchi & Team Yoast

== Must-Use Plugins ==
	Object Cache Pro (MU)
		Version: 1.14.1
		Author: Rhubarb Group

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Inactive
	Accessibility Improvements: Active
	Import Export Template Kit: Active
	Additional Custom Breakpoints: Active
	Hide native WordPress widgets from search results: Active
	: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Inactive
	Landing Pages: Active
	Color Sampler: Active
	Favorite Widgets: Active
	Admin Top Bar: Active
	Page Transitions: Active
	Form Submissions: Active
	Scroll Snap: Active

== Log ==
	
JS: showing 20 of 24JS: 2022-04-04 10:31:15 [error X 1][https://lnk3.me/wp-admin/post.php?post=16124&action=elementor:4:30042] Syntax error, unrecognized expression: #elementor-control-polygon(25% 0%, 100% 0%, 75% 100%, 0% 100%)-c92824 
JS: 2022-04-04 10:31:17 [error X 1][https://lnk3.me/wp-admin/post.php?post=16124&action=elementor:4:30042] Syntax error, unrecognized expression: #elementor-control-polygon(50% 0%, 80% 10%, 100% 35%, 100% 70%, 80% 90%, 50% 100%, 20% 90%, 0% 70%, 0% 35%, 20% 10%)-c92824 
JS: 2022-04-04 18:05:20 [error X 7][https://lnk3.me/wp-admin/post.php?post=12783&action=elementor:4:30042] Cannot create property \'guid\' on string \'c107widgetsticky\' 
JS: 2022-04-04 18:34:24 [error X 3][https://lnk3.me/:4:30039] e.dispatchEvent is not a function 
JS: 2022-04-04 19:16:13 [error X 1][https://lnk3.me/wp-admin/post.php?post=12783&action=elementor:4:30042] Cannot create property \'guid\' on string \'c110widgetsticky\' 
JS: 2022-04-04 19:16:15 [error X 1][https://lnk3.me/wp-admin/post.php?post=12783&action=elementor:4:30042] Cannot create property \'guid\' on string \'c113widgetsticky\' 
JS: 2022-04-04 19:16:24 [error X 2][https://lnk3.me/wp-admin/post.php?post=12783&action=elementor:4:30042] Cannot create property \'guid\' on string \'c83widgetsticky\' 
JS: 2022-04-04 19:16:24 [error X 2][https://lnk3.me/wp-admin/post.php?post=12783&action=elementor:4:30042] Cannot create property \'guid\' on string \'c95widgetsticky\' 
JS: 2022-04-05 10:46:11 [error X 1][https://lnk3.me/wp-admin/post.php?post=19673&action=elementor:4:30042] View (cid: \"view3619\") has already been destroyed and cannot be used. 
JS: 2022-04-05 10:47:06 [error X 1][https://lnk3.me/wp-admin/post.php?post=19673&action=elementor:4:30042] View (cid: \"view7157\") has already been destroyed and cannot be used. 
JS: 2022-04-05 10:57:52 [error X 1][https://lnk3.me/wp-admin/post.php?post=19673&action=elementor:4:30042] View (cid: \"view159\") has already been destroyed and cannot be used. 
JS: 2022-04-05 15:36:11 [error X 1][https://lnk3.me/wp-admin/post.php?post=19673&action=elementor:4:30042] View (cid: \"view226\") has already been destroyed and cannot be used. 
JS: 2022-04-05 16:19:27 [error X 2][https://lnk3.me/wp-admin/post.php?post=19673&action=elementor:4:30042] View (cid: \"view228\") has already been destroyed and cannot be used. 
JS: 2022-04-06 10:45:45 [error X 4][https://lnk3.me/wp-admin/post.php?post=19746&action=elementor:4:30042] Cannot read properties of undefined (reading \'isEditable\') 
JS: 2022-04-06 11:21:10 [error X 215][https://lnk3.me/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.2:2:391141] Cannot read properties of undefined (reading \'parent\') 
JS: 2022-04-06 12:09:04 [error X 1][https://lnk3.me/wp-admin/post.php?post=12352&action=elementor:4:30042] View (cid: \"view229\") has already been destroyed and cannot be used. 
JS: 2022-04-06 12:16:44 [error X 1][https://lnk3.me/wp-admin/post.php?post=19746&action=elementor:4:30042] View (cid: \"view1161\") has already been destroyed and cannot be used. 
JS: 2022-04-06 12:26:31 [error X 1][https://lnk3.me/wp-admin/post.php?post=19746&action=elementor:4:30042] Cannot read properties of null (reading \'url\') 
JS: 2022-04-07 09:52:06 [error X 1][https://lnk3.me/wp-admin/post.php?post=19746&action=elementor:4:30042] View (cid: \"view115\") has already been destroyed and cannot be used. 
JS: 2022-04-07 09:52:06 [error X 1][https://lnk3.me/wp-admin/post.php?post=19746&action=elementor:4:30042] View (cid: \"view164\") has already been destroyed and cannot be used. 

PHP: showing 10 of 10PHP: 2022-04-04 18:20:11 [error X 1][/mnt/BLOCKSTORAGE/home/417905.cloudwaysapps.com/vgsxhsnfjk/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::286] Uncaught Error: Call to a member function update_meta() on bool in /mnt/BLOCKSTORAGE/home/417905.cloudwaysapps.com/vgsxhsnfjk/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:286
Stack trace:
#0 /mnt/BLOCKSTORAGE/home/417905.cloudwaysapps.com/vgsxhsnfjk/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions()
#2 /mnt/BLOCKSTORAGE/home/417905.cloudwaysapps.com/vgsxhsnfjk/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func()
#3 /mnt/BLOCKSTORAGE/home/417905.cloudwaysapps.com/vgsxhsnfjk/public_html/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#4 /mnt/BLOCKSTORAGE/home/417905.cloudwaysapps.com/vgsxhsnfjk/public_html/wp [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-05 10:43:10 [notice X 1][/mnt/BLOCKSTORAGE/home/417905.cloudwaysapps.com/vgsxhsnfjk/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-05 15:35:46 [notice X 603][/mnt/BLOCKSTORAGE/home/417905.cloudwaysapps.com/vgsxhsnfjk/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-05 15:36:02 [notice X 14][/mnt/BLOCKSTORAGE/home/417905.cloudwaysapps.com/vgsxhsnfjk/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /mnt/BLOCKSTORAGE/home/417905.cloudwaysapps.com/vgsxhsnfjk/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /mnt/BLOCKSTORAGE/home/417905.cloudwaysapps.com/vgsxhsnfjk/public_html/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /mnt/BLOCKSTORAGE/home/417905.cloudwaysapps.com/vgsxhsnfjk/public_html/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /mnt/BLOCKSTORAGE/home/417905.cloudwaysapps.com/vgsxhsnfjk/public_html/wp-content/plugins/jet-elements/includes/class-jet-elements-integration.php(247): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-04-05 15:36:02 [notice X 14][/mnt/BLOCKSTORAGE/home/417905.cloudwaysapps.com/vgsxhsnfjk/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /mnt/BLOCKSTORAGE/home/417905.cloudwaysapps.com/vgsxhsnfjk/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /mnt/BLOCKSTORAGE/home/417905.cloudwaysapps.com/vgsxhsnfjk/public_html/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /mnt/BLOCKSTORAGE/home/417905.cloudwaysapps.com/vgsxhsnfjk/public_html/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /mnt/BLOCKSTORAGE/home/417905.cloudwaysapps.com/vgsxhsnfjk/public_html/wp-content/plugins/jet-elements/includes/class-jet-elements-integration.php(285): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-04-05 15:36:02 [notice X 14][/mnt/BLOCKSTORAGE/home/417905.cloudwaysapps.com/vgsxhsnfjk/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /mnt/BLOCKSTORAGE/home/417905.cloudwaysapps.com/vgsxhsnfjk/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /mnt/BLOCKSTORAGE/home/417905.cloudwaysapps.com/vgsxhsnfjk/public_html/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /mnt/BLOCKSTORAGE/home/417905.cloudwaysapps.com/vgsxhsnfjk/public_html/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /mnt/BLOCKSTORAGE/home/417905.cloudwaysapps.com/vgsxhsnfjk/public_html/wp-content/plugins/jet-elements/includes/modules/jet-elementor-extension/jet-elementor-extension.php(95): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-04-05 15:36:02 [notice X 14][/mnt/BLOCKSTORAGE/home/417905.cloudwaysapps.com/vgsxhsnfjk/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /mnt/BLOCKSTORAGE/home/417905.cloudwaysapps.com/vgsxhsnfjk/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /mnt/BLOCKSTORAGE/home/417905.cloudwaysapps.com/vgsxhsnfjk/public_html/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /mnt/BLOCKSTORAGE/home/417905.cloudwaysapps.com/vgsxhsnfjk/public_html/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /mnt/BLOCKSTORAGE/home/417905.cloudwaysapps.com/vgsxhsnfjk/public_html/wp-content/plugins/jet-elements/includes/modules/jet-elementor-extension/jet-elementor-extension.php(96): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-04-05 18:10:46 [notice X 15][/mnt/BLOCKSTORAGE/home/417905.cloudwaysapps.com/vgsxhsnfjk/public_html/wp-content/plugins/elementor-pro/modules/forms/classes/form-record.php::179] Undefined index: referrer [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-06 09:20:11 [notice X 5][/mnt/BLOCKSTORAGE/home/417905.cloudwaysapps.com/vgsxhsnfjk/public_html/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php::33] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-06 10:41:29 [warning X 11][/mnt/BLOCKSTORAGE/home/417905.cloudwaysapps.com/vgsxhsnfjk/public_html/wp-content/plugins/elementor/includes/controls/base-multiple.php::87] Illegal string offset 'url' [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 8 of 82022-04-05 15:34:24 [info] elementor::elementor_updater Started 
2022-04-05 15:34:24 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-05 15:34:24 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-05 15:34:24 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.1',
  'to' => '3.6.2',
)]
2022-04-05 15:34:24 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.1',
  'to' => '3.6.2',
)]
2022-04-06 10:03:33 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.1',
  'to' => '3.6.2',
)]
2022-04-06 10:03:34 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Dynamic.ooo - Dynamic Content for Elementor',
  'from' => '1.15.5',
  'to' => '2.4.5',
)]
2022-04-06 10:03:34 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.5.2',
  'to' => '3.6.4',
)]

== Elementor - Compatibility Tag ==
	
	Bestfreebie Elementor Icons: Compatibility not specified
	Dynamic.ooo - Dynamic Content for Elementor: Compatible
	Ele Custom Skin: Compatible
	Elementor Pro: Compatible
	JetElements For Elementor: Incompatible
	Make Column Clickable Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==
	
	Dynamic.ooo - Dynamic Content for Elementor: Compatible
	Ele Custom Skin: Compatible
	JetElements For Elementor: Incompatible

**Comment by rami-elementor** [comment]
Not a compatibility issue...

It works on Sections/Columns. Doesn't work on Containers.
