### ISSUE TITLE
🐞 Bug report: BetterDocs Category Grid

### ISSUE THREAD

**Issue by nikosnull** [elementor/elementor#18444]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

So by installing **Elementor & Elementor Pro** and **BetterDocs & BetterDocs Pro**, I started using a widget called **BetterDocs Category Grid**.

So, as the name suggests, is a grid displaying BetterDocs categories.

In the **Layout Options** of that widget, there is an option to choose Layouts called **Layout Mode** between **Grid, Masonry, and Fit to Screen.**

I am using this widget inside an **Elementor Template.** Then I am loading this template inside an **Advanced Tab** widget, one template for each tab.

So the problem is this: When using **Grid** as Layout mode, all the categories render at the correct place, in my case two categories per row.

At the other side when using **Masonry**, the categories render stacked on top of each other, and they move to their correct places only when resizing the window.

**Note:** The first loaded Tab, using Masonry mode, renders the categories correctly, all the other tabs do not.

**Note 2:** I tried using another tab as default (when refreshing the window another tab will be active first) and Note 1 was correct, the first loaded tab is the one with the correct categories all the other tabs, load them being stacked on top of each other.

### Steps to reproduce

So in the first picture, I am demonstrating how I am loading the template inside the Advanced Tabs widget.
You can see I am loading two widgets, one for desktop one for mobile, when stacked, the mobile one does not “recognize” the desktop that sits above it.

![1](https://user-images.githubusercontent.com/59178728/163330005-3ae549fa-e2ad-4692-b1d5-e4d0e7864271.png)

In the second picture, I am demonstrating the widget I am using and it's settings. Also, that is loads correctly in the Editor with Masonry mode.

![2](https://user-images.githubusercontent.com/59178728/163330402-342a7de1-b4a5-420a-9c97-269aef4446a6.png)

In the third picture, I am demonstrating the “stacked” categories I was mentioning above.

![3](https://user-images.githubusercontent.com/59178728/163330585-505ba934-43c8-4a48-8d82-0f8208b3526e.png)

In the fourth picture, I am demonstrating how the first tab, correctly loads all categories while using Masonry mode.

![4](https://user-images.githubusercontent.com/59178728/163330685-3a562af5-d6fc-4ccc-b4f7-ab8699b32c3a.png)

In the last picture, I am demonstrating that these values do not get passed in the tabs when not being the default one (the one that loads first when refreshing a window).
A correctly loaded Masonry had some left % and some top pixels in every article that made every article load correctly.

**Note:** When stacked, if I resize my browser, the values (left, top) get passed in and the Masonry loads correctly.

![5](https://user-images.githubusercontent.com/59178728/163331242-d2846844-23f5-4ff3-ba53-3ad8b1483ff9.png)

Please feel free to contact me for more info at GitHub or at nikos.koul97@gmail.com, I really need this fixed…

Also, please check the logs, I've censored some information using (-) about my company to avoid any issues with uploading this bug.

Thank you for your time in advanced.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v5.7.37
	PHP Version: 7.4.28
	PHP Memory Limit: 512M
	PHP Max Input Vars: 5120
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.3
	Site URL: [-](https://new-help.classter.com)
	Home URL: [-](https://new-help.classter.com)
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: -
	Debug Mode: Inactive

== Theme ==
	Name: Tikidocs Child
	Version: 1.0
	Author: ModelTheme
	Child Theme: Yes
	Parent Theme Name: Tikidocs
	Parent Theme Version: 2.1
	Parent Theme Author: ModelTheme

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0

== Active Plugins ==
	Advanced Editor Tools (previously TinyMCE Advanced)
		Version: 5.6.0
		Author: Automattic

	Asgaros Forum
		Version: 2.0.0
		Author: Thomas Belser

	Asset CleanUp: Page Speed Booster
		Version: 1.3.8.5
		Author: Gabe Livan

	bbPress
		Version: 2.6.9
		Author: The bbPress Contributors

	BetterDocs
		Version: 2.0.12
		Author: WPDeveloper

	BetterDocs Pro
		Version: 2.0.9
		Author: WPDeveloper

	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Classic Widgets
		Version: 0.3
		Author: WordPress Contributors

	Elementor
		Version: 3.6.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.6.5
		Author: Elementor.com

	ElementsKit Lite
		Version: 2.5.5
		Author: Wpmet

	Erident Custom Login and Dashboard
		Version: 3.5.9
		Author: Libin V Babu

	Essential Addons for Elementor
		Version: 5.0.13
		Author: WPDeveloper

	Frontend Utilities for Asgaros Forum
		Version: 1.1.1
		Author: Quenso

	Helper Lite for PageSpeed
		Version: 3.1.3
		Author: seojacky, mihdan, Каренина, wdup

	Mammoth .docx converter
		Version: 1.19.0
		Author: Michael Williamson

	ModelTheme Framework
		Version: 1.6
		Author: ModelTheme

	Name Directory
		Version: 1.25.1
		Author: Jeroen Peters

	Parallax Backgrounds for VC
		Version: 4.5
		Author: Gambit Technologies, Inc.

	Password Protected
		Version: 2.5
		Author: Ben Huson

	Perfect Images (Retina, Thumbnails, Replace)
		Version: 6.2.3
		Author: Jordy Meow

	Post Type Switcher
		Version: 3.2.1
		Author: Triple J Software, Inc.

	PowerPack Lite for Elementor
		Version: 2.6.12
		Author: IdeaBox Creations

	reCAPTCHA (v2 & v3) for Asgaros Forum
		Version: 1.0.4
		Author: Hitesh Chandwani

	Redirection
		Version: 5.2.3
		Author: John Godley

	Smush
		Version: 3.9.5
		Author: WPMU DEV

	Specify Missing Image Dimensions
		Version: 1.0.2
		Author: WPHowKnow

	Template Library and Redux Framework
		Version: 4.3.12
		Author: Extendify

	Ultimate Carousel For Elementor
		Version: 2.1.7
		Author: Nasir Ahmad

	W3 Total Cache
		Version: 2.2.1
		Author: BoldGrid

	Wordfence Security
		Version: 7.5.9
		Author: Wordfence

	WordPress Importer
		Version: 0.7
		Author: wordpressdotorg

	WPBakery Page Builder
		Version: 6.8.0
		Author: Michael M - WPBakery.com

	Yoast SEO
		Version: 18.5.1
		Author: Team Yoast

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Inactive
	Accessibility Improvements: Active
	Import Export Template Kit: Active
	Additional Custom Breakpoints: Active
	Hide native WordPress widgets from search results: Active by default
	: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active
	Admin Top Bar: Active by default
	Page Transitions: Active
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
JS: showing 9 of 9JS: 2022-03-16 09:50:00 [error X 1][https://new-help.classter.com/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.5.6:2:5067] can\'t access property \"attributes\", e is undefined 
JS: 2022-03-16 17:03:30 [error X 1][https://new-help.classter.com/wp-content/plugins/elementor-pro/assets/js/nav-menu.3de49ba5ef86f9a22ff5.bundle.min.js:2:2581] can\'t access property \"stretch\", this.stretchElement is null 
JS: 2022-03-16 17:03:31 [error X 1][https://new-help.classter.com/wp-content/plugins/elementor-pro/assets/js/nav-menu.3de49ba5ef86f9a22ff5.bundle.min.js:2:2639] can\'t access property \"reset\", this.stretchElement is null 
JS: 2022-03-21 09:04:59 [error X 4][https://new-help.classter.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.6:2:251445] can\'t access property \"menu\", jQuery(...).data(...) is undefined 
JS: 2022-04-11 06:48:04 [error X 2][https://new-help.classter.com/wp-content/plugins/powerpack-lite-for-elementor/assets/js/min/frontend.min.js?ver=2.6.11:1:3088] JSON.parse: unexpected character at line 1 column 1 of the JSON data 
JS: 2022-04-11 07:27:35 [error X 7][https://new-help.classter.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.2:2:368770] can\'t access property \"isEditable\", this.view.container is undefined 
JS: 2022-04-11 07:27:37 [error X 1][https://new-help.classter.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.2:2:362174] can\'t access property \"isEditable\", this.container is undefined 
JS: 2022-04-11 12:34:45 [error X 1][https://new-help.classter.com/wp-content/uploads/essential-addons-elementor/315040dd6.min.js?ver=1649680482:13:14] sidebarclick.add is not a function 
JS: 2022-04-11 16:37:23 [error X 1][https://new-help.classter.com/wp-content/uploads/essential-addons-elementor/315040dd6.min.js?ver=1649695040:6:23] can\'t access property \"addEventListener\", document.getElementById(...) is null 

PHP: showing 9 of 9PHP: 2022-03-16 14:53:41 [warning X 3][-/new-help.classter.com/wp-content/plugins/elementor/includes/template-library/sources/local.php::834] Invalid argument supplied for foreach() [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-16 16:56:27 [notice X 9][-/new-help.classter.com/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-24 07:53:44 [notice X 87][-/new-help.classter.com/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-24 20:24:01 [notice X 3][-/new-help.classter.com/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: -/new-help.classter.com/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: -/new-help.classter.com/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: -/new-help.classter.com/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4:-/new-help.classter.com/wp-content/plugins/elementskit-lite/modules/controls/init.php(52): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-03-24 20:24:01 [notice X 3][-/new-help.classter.com/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: -/new-help.classter.com/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: -/new-help.classter.com/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: -/new-help.classter.com/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: -/new-help.classter.com/wp-content/plugins/elementskit-lite/modules/controls/init.php(56): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-03-24 20:24:01 [notice X 3][-/new-help.classter.com/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: -/new-help.classter.com/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: -/new-help.classter.com/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: -/new-help.classter.com/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: -/new-help.classter.com/wp-content/plugins/elementskit-lite/modules/controls/init.php(60): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-04-07 13:52:34 [error X 2][-/new-help.classter.com/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::286] Uncaught Error: Call to a member function update_meta() on bool in -/new-help.classter.com/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:286
Stack trace:
#0 -/new-help.classter.com/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 -/new-help.classter.com/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 -/new-help.classter.com/wp-includes/class-wp-hook.php(307): Ele [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-08 06:33:52 [notice X 1][-/new-help.classter.com/wp-content/plugins/elementor/core/experiments/experiments-reporter.php::89] Undefined index: title [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-08 06:46:18 [notice X 20][-/new-help.classter.com/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: -/new-help.classter.com/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: -/new-help.classter.com/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: -/new-help.classter.com/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: -/new-help.classter.com/wp-content/plugins/master-addons/class-master-elementor-addons.php(428): Elementor\Controls_Manager -> register_control()
',
)]

Log: showing 20 of 252022-04-05 10:42:55 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.1',
  'to' => '3.6.2',
)]
2022-04-05 10:42:56 [info] elementor::elementor_updater Started 
2022-04-05 10:42:56 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-05 10:42:56 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-05 10:42:56 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.1',
  'to' => '3.6.2',
)]
2022-04-13 09:23:33 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.2',
  'to' => '3.6.3',
)]
2022-04-13 09:23:34 [info] elementor::elementor_updater Started 
2022-04-13 09:23:34 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-13 09:23:34 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-13 09:23:34 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.2',
  'to' => '3.6.3',
)]
2022-04-13 09:23:43 [info] elementor-pro::elementor_pro_updater Started 
2022-04-13 09:23:43 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-04-13 09:23:43 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-04-13 09:23:43 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]
2022-04-13 09:23:43 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]
2022-04-14 06:29:31 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.3',
  'to' => '3.6.4',
)]
2022-04-14 06:29:32 [info] elementor::elementor_updater Started 
2022-04-14 06:29:32 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-14 06:29:32 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-14 06:29:32 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.3',
  'to' => '3.6.4',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	Essential Addons for Elementor: Compatibility not specified
	PowerPack Lite for Elementor: Compatibility not specified
	Ultimate Carousel For Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by nikosnull** [comment]
Almost two months with this.... any news?
