### ISSUE TITLE
🐞 Bug report: 

### ISSUE THREAD

**Issue by glerner** [elementor/elementor#18457]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

WooCommerce cart icon not displaying in page header, if not logged in (so, for most potential customers).
Elementor, Settings, Ongoing Experiments, 
Inline Font Icons - active
Improved CSS Loading - active

### Steps to reproduce

Elementor, Settings, Ongoing Experiments, 
Inline Font Icons
    - is active
Improved CSS Loading
    - is active

Browse to a page with cart icon, logged out. (Incognito window or normal window in Chrome. Also see in Firefox.)

Icon is displayed using a fallback font, which probably doesn't have a defined character for that character code, so it displays a rectangle. 
When it doesn't display, the eicons font file isn't loaded, nor the CSS file for it. 

Deactivate Inline Font Icons and Improved CSS Loading, icon displays properly.
With just Inline Font Icons disabled, didn't work. 
Didn't test if Inline Font Icons enabled and Improved CSS Loading disabled works or not. 

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.18.0
	MySQL version: mariadb.org binary distribution v10.3.17
	PHP Version: 7.4.28
	PHP Memory Limit: 256M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 500M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.3
	Site URL: https://www.mountainvalleycenter.com
	Home URL: https://www.mountainvalleycenter.com
	WP Multisite: No
	Max Upload Size: 500 MB
	Memory limit: 768M
	Max Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/New_York
	Admin Email: webmaster@mountainvalleycenter.com
	Debug Mode: Inactive

== Theme ==
	Name: Astra Child
	Version: 1.0.0
	Author: Brainstorm Force
	Child Theme: Yes
	Parent Theme Name: Astra
	Parent Theme Version: 3.7.9
	Parent Theme Author: Brainstorm Force

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 5.12.2
		Author: Delicious Brains

	Advanced Order Export For WooCommerce
		Version: 3.2.2
		Author: AlgolPlus

	Advanced Shipment Tracking for WooCommerce
		Version: 3.3.2
		Author: zorem

	Amazon Pay WooCommerce payment gateway
		Version: 2.9
		Author: Subhadeep Mondal

	Astra Pro
		Version: 3.6.6
		Author: Brainstorm Force

	Breadcrumb NavXT
		Version: 7.0.2
		Author: John Havlik

	Category Order and Taxonomy Terms Order
		Version: 1.6
		Author: Nsp-Code

	Elementor
		Version: 3.6.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.6.5
		Author: Elementor.com

	Essential Addons for Elementor
		Version: 5.0.13
		Author: WPDeveloper

	GetResponse for WordPress
		Version: 5.5.18
		Author: GetResponse

	Media Library Assistant
		Version: 2.99
		Author: David Lingren

	MP3 Audio Player by Sonaar
		Version: 3.5
		Author: Sonaar Music

	Phoenix Media Rename
		Version: 3.7.0
		Author: crossi72

	Print Invoice & Delivery Notes for WooCommerce
		Version: 4.6.5
		Author: Tyche Softwares

	PW WooCommerce Gift Cards
		Version: 1.203
		Author: Pimwick, LLC

	Relevanssi
		Version: 4.15.1
		Author: Mikko Saari

	Sidebar Manager
		Version: 1.1.7
		Author: Brainstorm Force

	Site Kit by Google
		Version: 1.72.0
		Author: Google

	TI WooCommerce Wishlist
		Version: 1.42.1
		Author: TemplateInvaders

	WooCommerce
		Version: 6.4.0
		Author: Automattic

	WooCommerce - Store Exporter
		Version: 2.7.1
		Author: Visser Labs

	WooCommerce Google Analytics Integration
		Version: 1.5.8
		Author: WooCommerce

	WooCommerce PDF Invoices & Packing Slips
		Version: 2.14.4
		Author: WP Overnight

	WooCommerce PDF Invoices, Packing Slips, Delivery Notes & Shipping Labels (Pro)
		Version: 4.3.4
		Author: WebToffee

	WooCommerce Square
		Version: 2.9.1
		Author: WooCommerce

	Woo Store Vacation
		Version: 1.4.4
		Author: MyPreview

	WP HTML Mail - Email Template Designer
		Version: 3.2
		Author: Hannes Etzelstorfer // codemiq

	WP HTML Mail - WooCommerce
		Version: 2.9.14
		Author: Hannes Etzelstorfer // codemiq

	WP Mail SMTP
		Version: 3.3.0
		Author: WPForms

	Yoast SEO
		Version: 18.5.1
		Author: Team Yoast

	Yoast SEO: WooCommerce
		Version: 14.5
		Author: Team Yoast

	Yoast SEO Premium
		Version: 18.3
		Author: Team Yoast

== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

	SiteDistrict Single Sign-on
		Version: 0.1.0
		Author: SiteDistrict Team

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Inactive
	Inline Font Icons: Inactive
	Accessibility Improvements: Active
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Inactive by default
	Hide native WordPress widgets from search results: Active by default
	: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Landing Pages: Active by default
	Color Sampler: Inactive
	Favorite Widgets: Active by default
	Admin Top Bar: Active
	Page Transitions: Active by default
	Form Submissions: Active
	Scroll Snap: Active by default

== Log ==
	
Log: showing 20 of 232022-03-06 21:16:30 [info] Elementor/Upgrades - _on_each_version Start  
2022-03-06 21:16:30 [info] Elementor/Upgrades - _on_each_version Finished 
2022-03-06 21:16:30 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.5',
  'to' => '3.5.6',
)]
2022-04-03 20:33:01 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.6',
  'to' => '3.6.1',
)]
2022-04-03 20:33:01 [info] elementor::elementor_updater Started 
2022-04-03 20:33:01 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-03 20:33:01 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-03 20:33:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.6',
  'to' => '3.6.1',
)]
2022-04-15 12:38:58 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.1',
  'to' => '3.6.4',
)]
2022-04-15 12:38:58 [info] elementor::elementor_updater Started 
2022-04-15 12:38:58 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-15 12:38:58 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-15 12:38:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.1',
  'to' => '3.6.4',
)]
2022-04-15 12:42:48 [info] elementor-pro::elementor_pro_updater Started 
2022-04-15 12:42:48 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-04-15 12:42:48 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-04-15 12:42:48 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Start  
2022-04-15 12:42:48 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Finished 
2022-04-15 12:42:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.4.2',
  'to' => '3.6.5',
)]
2022-04-15 12:42:48 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.4.2',
  'to' => '3.6.5',
)]

JS: showing 9 of 9JS: 2022-02-09 15:30:48 [error X 1][https://www.mountainvalleycenter.com/wp-admin/post.php?post=112114&action=elementor:3:22112] Cannot read properties of null (reading \'elecode\') 
JS: 2022-02-09 18:53:47 [error X 5][https://www.mountainvalleycenter.com/wp-content/plugins/elementor/assets/js/editor.min.js?fsum=0d5fda0f9ca9:2:453830] T is null 
JS: 2022-02-10 19:22:33 [error X 1][https://www.mountainvalleycenter.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?fsum=b440fb56d1a9:24:0] View (cid: \"view33126\") has already been destroyed and cannot be used. 
JS: 2022-02-10 19:23:21 [error X 7][https://www.mountainvalleycenter.com/wp-content/plugins/elementor/assets/js/editor.min.js?fsum=0d5fda0f9ca9:2:245864] T.params.args.data is undefined 
JS: 2022-02-11 19:30:34 [error X 6][https://www.mountainvalleycenter.com/wp-admin/post.php?post=804&action=elementor:3:22112] Cannot read properties of undefined (reading \'id\') 
JS: 2022-02-12 18:17:02 [error X 1][https://www.mountainvalleycenter.com/wp-admin/post.php?post=619&action=elementor:3:22112] this.target.getContainer is not a function 
JS: 2022-02-19 03:35:21 [error X 8][https://www.mountainvalleycenter.com/wp-content/plugins/elementor/assets/js/editor-modules.min.js?fsum=e35106fb97a3:2:15211] this.document is null 
JS: 2022-02-20 03:46:28 [error X 1][https://www.mountainvalleycenter.com/wp-content/plugins/elementor/assets/js/editor.min.js?fsum=0d5fda0f9ca9:2:558642] elementorFrontend is not defined 
JS: 2022-03-05 02:41:47 [error X 28][https://www.mountainvalleycenter.com/wp-admin/post.php?post=7215&action=elementor:3:22112] Cannot read properties of undefined (reading \'data\') 

PHP: showing 10 of 10PHP: 2022-02-11 20:39:51 [notice X 8][/www/wp-content/plugins/elementor-pro/modules/woocommerce/widgets/add-to-cart.php::142] Undefined index: post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-14 03:50:07 [notice X 4][/www/wp-content/plugins/elementor-pro/modules/query-control/module.php::740] Trying to get property 'name' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-19 15:07:17 [error X 2][/www/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::285] Uncaught Error: Call to a member function update_meta() on bool in /www/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:285
Stack trace:
#0 /www/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(166): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions()
#2 /www/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func()
#3 /www/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#4 /www/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#5 /www/wp-includes/plugin.php(474): WP_Hook->do_action()
#6 /www/wp-admin/admin-ajax.php(187): do_action()
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-05 15:25:43 [notice X 2][/www/wp-content/plugins/elementor/includes/elements/column.php::1007] Undefined index: _column_size [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-03 20:33:08 [notice X 14931][/www/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-03 20:35:54 [notice X 3][/www/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-03 20:35:55 [notice X 94][/www/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /www/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /www/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /www/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /www/wp-content/plugins/elementor-pro/modules/query-control/module.php(826): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-04-03 20:35:55 [notice X 94][/www/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /www/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /www/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /www/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /www/wp-content/plugins/elementor-pro/modules/theme-builder/module.php(162): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-04-03 20:35:55 [notice X 94][/www/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /www/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /www/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /www/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /www/wp-content/plugins/elementor-pro/modules/forms/module.php(72): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-04-03 20:35:55 [notice X 94][/www/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /www/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /www/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /www/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /www/wp-content/plugins/elementor-pro/modules/forms/module.php(73): Elementor\Controls_Manager -> register_control()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	Essential Addons for Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @glerner,

Thank you for submitting your issue, and for being so patient! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
We tested the same configuration as your site, but using the following plugins, experiments, and theme:
- Elementor 3.8.1
- Elementor Pro 3.8.1
- Hello Elementor 2.6.1
- WooCommerce 7.1.0
- All Experiments: Active
- Inline Icons and Improved CSS Loading: Active
- Inline Icons: Active

In all situations, the icons loaded as expected with SVGs.

![image](https://user-images.githubusercontent.com/113993460/202222731-27f5e6e9-b180-40a4-bc87-d7c6d12e89af.png)
![image](https://user-images.githubusercontent.com/113993460/202222795-6f767ee1-5aab-4c44-b8c4-2ccdf098103f.png)

❕ Your issue might be related to your **server cache**, or any **performance optimization** solution you might have running on your server. 

### ✅ What you can do to solve your issue:
* On a staging environment, try to disable any performance optimization solution you might have running, either on your server or at the site level. 
* Make sure to regenerate the CSS & Files in your Dashboard > Elementor > Tools after activating the Inline Font Icons experiment.
* If the issue persists, try deactivating other plugins, one by one while clearing the browser cache and checking if the icons appear.
* If the issue still persists, try switching to the Hello Elementor theme, and then clear the cache again.

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* Please create GitHub issues **only for Elementor bugs**. GitHub issues ARE NOT FOR SUPPORT or for issues with 3rd party plugins.
* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

### ⚠️ Please Note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
