### ISSUE TITLE
🐞 Bug report: ThemeBuilder does not exist

### ISSUE THREAD

**Issue by rahmatsubandi** [elementor/elementor#18479]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hello, I found a bug in Elementor Pro. When I go to Templates->Theme Builder menu I find a problem:
`Error: Method ElementorPro\Modules\ThemeBuilder\Documents\Header::get_site_editor_type() does not exist`

This is not once, but this happened on 2 of my websites. And when I asked my boss to communicate with the new CS Elementor by attaching the existing info system, it just got resolved. For me, this is very troublesome for me and my boss. What is the best way for the Elementor team to take this seriously?

### Steps to reproduce

And when contacting CS this issue was resolved for a while, unfortunately the next day it happened again. I beg your help

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

```
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.53 (Ubuntu) mod_fcgid/2.3.9 OpenSSL/1.1.1
	MySQL version: mariadb.org binary distribution v10.6.7
	PHP Version: 8.0.17
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 32M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.3
	Site URL: https://aaa788.xyz
	Home URL: https://aaa788.xyz
	WP Multisite: No
	Max Upload Size: 32 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%category%/%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: laperterus123@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: aaa788 Themes
	Version: 1.0.1
	Author: Rahmat Subandi
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.5.0
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36

== Active Plugins ==
	Accelerated Mobile Pages
		Version: 1.0.77.42
		Author: Ahmed Kaludi, Mohammed Kaludi

	AMP Pagebuilder Compatibility
		Version: 1.9.82.1
		Author: AMPforWP Team

	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Elementor
		Version: 3.6.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.6.5
		Author: Elementor.com

	Header Footer Code Manager
		Version: 1.1.21
		Author: 99robots

	ImageKit
		Version: 4.1.2
		Author: ImageKit

	NitroPack
		Version: 1.5.10
		Author: NitroPack LLC

	Unlimited Elements for Elementor
		Version: 1.5.11
		Author: Unlimited Elements

	WPS Hide Login
		Version: 1.9.4
		Author: WPServeur, NicolasKulka, wpformation

	Yoast SEO
		Version: 18.6
		Author: Team Yoast


== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default


== Log ==
	
PHP: showing 7 of 7PHP: 2022-04-11 15:09:26 [warning X 83][/home/developer/web/aaa788.xyz/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key &quot;data&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-11 15:37:45 [warning X 3][/home/developer/web/aaa788.xyz/public_html/wp-content/plugins/elementor/includes/template-library/manager.php::229] Undefined array key &quot;types_data&quot; [array (
  'trace' => '
#0: /home/developer/web/aaa788.xyz/public_html/wp-content/plugins/elementor/includes/template-library/manager.php(229): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/developer/web/aaa788.xyz/public_html/wp-content/plugins/elementor/includes/template-library/data/endpoints/templates.php(21): Elementor\TemplateLibrary\Manager -> get_library_data()
#2: /home/developer/web/aaa788.xyz/public_html/wp-content/plugins/elementor/data/v2/base/base-route.php(329): Elementor\Includes\TemplateLibrary\Data\Endpoints\Templates -> get_items()
#3: /home/developer/web/aaa788.xyz/public_html/wp-content/plugins/elementor/data/v2/base/base-route.php(233): Elementor\Data\V2\Base\Base_Route -> base_callback()
#4: /home/developer/web/aaa788.xyz/public_html/wp-includes/rest-api/class-wp-rest-server.php(1141): Elementor\Data\V2\Base\Base_Route -> Elementor\Data\V2\Base\{closure}()
',
)]
PHP: 2022-04-11 15:52:34 [warning X 7][/home/developer/web/aaa788.xyz/public_html/wp-content/plugins/elementor/includes/managers/image.php::87] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-11 17:38:42 [error X 3][/home/developer/web/aaa788.xyz/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::286] Uncaught Error: Call to a member function update_meta() on bool in /home/developer/web/aaa788.xyz/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:286
Stack trace:
#0 /home/developer/web/aaa788.xyz/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;ajax_save_theme_template_conditions()
#2 /home/developer/web/aaa788.xyz/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func()
#3 /home/developer/web/aaa788.xyz/public_html/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module-&gt;handle_ajax_request()
#4 /home/developer/web/aaa788.xyz/public_html/wp-includes/class-wp-hook.php(331): WP_Hook-&gt;apply_filters()
#5 /home/developer/web/aaa788.xyz/public_html/wp-includes/plugin.php(474): WP_Hook-&gt;do_action()
#6 /home/developer/web/aaa788.xyz/public_html/wp-admin/admin-ajax.php(187): do_action()
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-11 21:45:35 [error X 1][/home/developer/web/aaa788.xyz/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::286] Uncaught Error: Call to a member function update_meta() on null in /home/developer/web/aaa788.xyz/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:286
Stack trace:
#0 /home/developer/web/aaa788.xyz/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;ajax_save_theme_template_conditions()
#2 /home/developer/web/aaa788.xyz/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func()
#3 /home/developer/web/aaa788.xyz/public_html/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module-&gt;handle_ajax_request()
#4 /home/developer/web/aaa788.xyz/public_html/wp-includes/class-wp-hook.php(331): WP_Hook-&gt;apply_filters()
#5 /home/developer/web/aaa788.xyz/public_html/wp-includes/plugin.php(474): WP_Hook-&gt;do_action()
#6 /home/developer/web/aaa788.xyz/public_html/wp-admin/admin-ajax.php(187): do_action()
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-13 19:22:57 [warning X 4][/home/developer/web/aaa788.xyz/public_html/wp-content/plugins/elementor/core/experiments/experiments-reporter.php::89] Undefined array key &quot;title&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-18 17:09:43 [warning X 1][/home/developer/web/aaa788.xyz/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::167] Undefined array key &quot;editor_post_id&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 6 of 6JS: 2022-04-11 15:52:18 [error X 1][https://aaa788.xyz/wp-content/plugins/elementor-pro/assets/js/nav-menu.3de49ba5ef86f9a22ff5.bundle.min.js:2:2601] Cannot read properties of null (reading \&#039;stretch\&#039;) 
JS: 2022-04-11 22:06:41 [error X 3][https://aaa788.xyz/wp-content/plugins/elementor-pro/assets/js/gallery.9c61bb9957e10e6d7bda.bundle.min.js:2:5599] Cannot read properties of undefined (reading \&#039;setSettings\&#039;) 
JS: 2022-04-12 01:27:39 [error X 5][https://aaa788.xyz/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.2:2:515479] Cannot read properties of null (reading \&#039;getBoundingClientRect\&#039;) 
JS: 2022-04-12 16:30:16 [error X 2][https://aaa788.xyz/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.2:2:605201] elementorFrontend is not defined 
JS: 2022-04-13 14:15:02 [error X 1][https://aaa788.xyz/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \&quot;view73958\&quot;) has already been destroyed and cannot be used. 
JS: 2022-04-13 14:15:02 [error X 1][https://aaa788.xyz/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \&quot;view74024\&quot;) has already been destroyed and cannot be used. 

Log: showing 15 of 152022-04-12 14:53:42 [info] elementor-pro::elementor_pro_updater Started 
2022-04-12 14:53:42 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-04-12 14:53:42 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-04-12 14:53:42 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]
2022-04-12 14:53:42 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]
2022-04-13 05:05:23 [info] elementor::elementor_updater Started 
2022-04-13 05:05:23 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-13 05:05:23 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-13 05:05:23 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.2',
  'to' => '3.6.3',
)]
2022-04-13 05:05:23 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.2',
  'to' => '3.6.3',
)]
2022-04-13 05:05:24 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.2',
  'to' => '3.6.3',
)]
2022-04-13 17:55:02 [info] elementor::elementor_updater Started 
2022-04-13 17:55:02 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-13 17:55:02 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-13 17:55:02 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.3',
  'to' => '3.6.4',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	Unlimited Elements for Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==
```

**Comment by rami-elementor** [comment]
@rahmatsubandi 

Can't find this method in Elementor Pro. You need to disable all the plugins and use the Hello theme to check if the problem repeats itself.

**Comment by Luke-SF** [comment]
Since Elementor 3.7 was released today, I am seeing this new issue Method get_site_editor_type does not exist,
in several cases that breaks all wp-admin/ editing.

wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php in ReflectionClass::getMethod at line 46

**Comment by Luke-SF** [comment]
Elementor-pro 3.1.0, 3.2.1 are known to be incompatible - updating seems to fix it.

**Comment by Luke-SF** [comment]
Can this incompatibility be fixed in Elementor, since older Elementor versions seem to not take the Elementor-pro update, then updating Elementor breaks everything until one manually removes and re-adds Elementor-pro?

**Comment by rahmatsubandi** [comment]
It's true that sometimes there are some bugs there, but so far it's still safe, after the update. Hopefully the Elementor team can focus more and respond to bugs. Thanks.
