### ISSUE TITLE
🐞 Bug report: Redis Cache incompatibility

### ISSUE THREAD

**Issue by gmariani** [elementor/elementor#18497]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

It appears that mobile view is breaking when using Redis Cache. I suspect that because Elementor writes in-line styling (possibly at runtime?) that is getting cached by Redis and delivered to mobile users. If i style a page for mobile, after I save it, the page will display properly. It will do this up until i clear Redis Cache, after which it will display only the desktop mode even on mobile and it's due to the inline styling overriding the CSS included in separately.

### Steps to reproduce

1. Style a page for desktop and mobile, and have Redis Cache enabled
2. Save the page and view on mobile (should look fine)
3. Clear Redis Cache
4. View same page on mobile and you should only see the desktop mode

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.3.32
	PHP Version: 8.0.17
	PHP Memory Limit: 2048M
	PHP Max Input Vars: 16384
	PHP Max Post Size: 1536M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.3
	Site URL: https://soaringactonacademy.com
	Home URL: https://soaringactonacademy.com
	WP Multisite: No
	Max Upload Size: 2 GB
	Memory limit: 40M
	Max Memory limit: 2048M
	Permalink Structure: /%category%/%postname%/
	Language: en-US
	Timezone: America/Los_Angeles
	Admin Email: wordpress@coursevector.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.5.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0

== Active Plugins ==
	CoBlocks
		Version: 2.22.10
		Author: GoDaddy

	CryptX
		Version: 3.3.3.2
		Author: Ralf Weber

	CV Monitor
		Version: 3.0.2
		Author: CourseVector

	Disable Comments
		Version: 2.3.4
		Author: WPDeveloper

	Elementor
		Version: 3.6.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.6.5
		Author: Elementor.com

	Redis Object Cache
		Version: 2.0.25
		Author: Till Krüss

	Simple History
		Version: 3.2.0
		Author: Pär Thernström

	Wordfence Security
		Version: 7.5.9
		Author: Wordfence

	WP Media folder
		Version: 5.3.26
		Author: Joomunited

== Must-Use Plugins ==
	Nexcess Managed Apps
		Version: 1.27.5
		Author: Nexcess

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Inactive
	Hello Theme Header & Footer: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 20 of 272022-03-31 12:26:56 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.3',
  'to' => '3.6.4',
)]
2022-03-31 12:28:23 [info] elementor-pro::elementor_pro_updater Started 
2022-03-31 12:28:23 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-03-31 12:28:23 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-03-31 12:28:23 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.3',
  'to' => '3.6.4',
)]
2022-04-08 20:45:32 [info] elementor::elementor_updater Started 
2022-04-08 20:45:32 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-08 20:45:32 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-08 20:45:32 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.1',
  'to' => '3.6.2',
)]
2022-04-08 20:45:32 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.1',
  'to' => '3.6.2',
)]
2022-04-14 12:38:39 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.2',
  'to' => '3.6.4',
)]
2022-04-14 12:38:41 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]
2022-04-14 12:38:51 [info] elementor::elementor_updater Started 
2022-04-14 12:38:51 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-14 12:38:51 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-14 12:38:51 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.2',
  'to' => '3.6.4',
)]
2022-04-14 12:38:52 [info] elementor-pro::elementor_pro_updater Started 
2022-04-14 12:38:52 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-04-14 12:38:52 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-04-14 12:38:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]

JS: showing 12 of 12JS: 2022-03-31 19:55:38 [error X 6][https://soaringactonacademy.com/wp-content/plugins/elementor/assets/js/editor.min.js:2:450902] T.getContainer is not a function 
JS: 2022-03-31 20:33:54 [error X 1][https://soaringactonacademy.com/?elementor_library=coming-soon:4:43] Cannot read properties of null (reading \'parentNode\') 
JS: 2022-04-05 19:02:32 [error X 1][https://soaringactonacademy.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js:24:19952] View (cid: \"view4330\") has already been destroyed and cannot be used. 
JS: 2022-04-05 19:03:47 [error X 1][https://soaringactonacademy.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js:24:19952] View (cid: \"view96\") has already been destroyed and cannot be used. 
JS: 2022-04-05 19:03:53 [error X 1][https://soaringactonacademy.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js:24:19952] View (cid: \"view1182\") has already been destroyed and cannot be used. 
JS: 2022-04-05 19:05:18 [error X 1][https://soaringactonacademy.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js:24:19952] View (cid: \"view1273\") has already been destroyed and cannot be used. 
JS: 2022-04-05 19:06:51 [error X 1][https://soaringactonacademy.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js:24:19952] View (cid: \"view1359\") has already been destroyed and cannot be used. 
JS: 2022-04-08 18:24:24 [error X 4][https://soaringactonacademy.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js:24:19952] View (cid: \"view77\") has already been destroyed and cannot be used. 
JS: 2022-04-15 18:51:27 [error X 4][https://soaringactonacademy.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view82\") has already been destroyed and cannot be used. 
JS: 2022-04-15 18:52:18 [error X 14][https://soaringactonacademy.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view78\") has already been destroyed and cannot be used. 
JS: 2022-04-23 04:32:22 [error X 1][https://soaringactonacademy.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view1190\") has already been destroyed and cannot be used. 
JS: 2022-04-23 04:48:01 [error X 24][https://soaringactonacademy.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.4:2:375483] Cannot read properties of undefined (reading \'get\') 

PHP: showing 3 of 3PHP: 2022-04-14 12:41:23 [warning X 1][/chroot/home/a8eb0ce6/f0d6a8e00a.nxcli.net/html/wp-content/plugins/elementor-pro/modules/query-control/module.php::383] Undefined array key "display" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-15 11:51:11 [warning X 3][/chroot/home/a8eb0ce6/f0d6a8e00a.nxcli.net/html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-20 09:09:48 [error X 1][/chroot/home/a8eb0ce6/f0d6a8e00a.nxcli.net/html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::286] Uncaught Error: Call to a member function update_meta() on null in /chroot/home/a8eb0ce6/f0d6a8e00a.nxcli.net/html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:286
Stack trace:
#0 /chroot/home/a8eb0ce6/f0d6a8e00a.nxcli.net/html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(12, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /chroot/home/a8eb0ce6/f0d6a8e00a.nxcli.net/html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /chroot/home/a8eb0ce6/f0d6a8e00a.nxcli.net/html/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /chroot/home/a8eb0ce6/f0d6a8e00a.nxcli.net/html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#5 /chroot/home/a8eb0ce6/f0d6a8e00a.nxcli.net/html/wp-includes/plugin.php(474): WP_Hook->do_action(Array)
#6 /chroot/home/a8eb0ce6/f0d6a8e00a.nxcli.net/html/wp-admin/admin-ajax.php(187): do_action('wp_ajax_element...')
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

**Comment by rami-elementor** [comment]
> I suspect that because Elementor writes in-line styling (possibly at runtime?) that is getting cached by Redis and delivered to mobile users.

You can change the way Elementor prints CSS.

Go to: WordPress Dashboard > Elementor > Settings > Advanced (tab)

![Elementor-‹-dev-edition-—-WordPress](https://user-images.githubusercontent.com/92088692/165235099-2bbb5420-5ed6-4206-8c2e-bbf099b699f5.png)
 
Try to change this to see how Redis reacts

**Comment by gmariani** [comment]
I checked and it was already configured to "External File", but I did try switching to "internal Embedding" and didn't see a noticeable effect. RIGHT after changing, it would display correctly, but after I clear the Redis Cache it breaks again. This happens using either CSS Print Method

internal-embedding-redis-cleared
![internal-embedding-redis-cleared](https://user-images.githubusercontent.com/5058619/165343204-b86ad174-626f-412d-bde5-2137d7683d60.JPG)

external-file-redis-cleared
![external-file-redis-cleared](https://user-images.githubusercontent.com/5058619/165343206-b18f8156-e4ec-431f-ac2f-49bcaec731c6.JPG)
.

**Comment by gmariani** [comment]
Just to be sure, I did disable all plugins except for Elementor, Elementor Pro and Redis Object Cache, no joy.

**Comment by rami-elementor** [comment]
@gmariani 

You should contact "Redis Object Cache" developers. I believe they can help you better than I can because cache is their main business.

**Comment by gmariani** [comment]
I disabled Object Cache (removes the object-cache.php drop-in) and Elementor still exhibited the same behavior. I did open a ticket with Redis Object Cache as recommended. But at this point I'm still thinking it's more of an Elementor issue.

**Comment by gmariani** [comment]
The developer says you guys need to figure it out: "Sorry, this plugin only provides an API for other plugins to use the Redis cache. It’s up to Elementor to solve. Be insistent with them."

But as I said, even with my last comment, when I disabled Redis Cache i still saw the errors. If you'd like access to the site to investigate I'd be open to that.

**Comment by gmariani** [comment]
It's been 20 days with no follow up, I'll take it that Elementor thinks this is "good enough" and how it should work. I'll pass that along to the client and see if they want to drop Elementor or find some other alternative.

**Comment by gmariani** [comment]
I did some debugging and have something I'd like you to confirm. So as you mentioned before, there is the "CSS Print Method" option which you had me manually toggle to "External File" which did nothing. I then found in the code that there is an experiment for "Improved CSS Loading" which also inlines CSS. I set this to "Inactive" to no avail also. I did more debugging and found this:

```
elementor-pro/modules/posts/skins/skin-content-base.php:render_post_content()
255 // Print manually (and don't use `the_content()`) because it's within another `the_content` filter, and the Elementor filter has been removed to avoid recursion.
256 $content = Plugin::elementor()->frontend->get_builder_content( $post->ID, true );

elementor/includes/frontend.php:get_builder_content()
1089 if ( ! empty( $css_file ) && $with_css ) {
1090	$css_file->print_css();
1091 }
```

When the theme builder goes to render the Post Content widget, it calls get_builder_content. But what I want to ask you about is why the "with_css" option is hard coded to true? With that setting hard coded to true, forces the Post Content module to inline CSS which then overrides the external CSS files and causes the issues I'm seeing. Please take a look and see if this is a mistake and/or it's not supposed to be hard-coded and instead controlled by an option. By me manually setting that to false I see my issue resolved. Feel free to Venmo/PayPal me any money for troubleshooting and solving this issue for you. Thanks!

**Comment by NerdvanaNC** [comment]
Unfortunate that no one from the Elementor team has replied; can only assume the bug remains unsolved? Even after @gmariani has gone to lengths to debug.

@gmariani - thank you for taking the time to not only resolve the issue but also come back to post about it. :)
