### ISSUE TITLE
🐞 Bug report: Media Carousel has flex-basis: 100% and no way to override.

### ISSUE THREAD

**Issue by tomas-eklund** [elementor/elementor#18505]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest development version of Elementor.

### Description

I'm using the new container experiment, trying to achieve the following layout.  

![image](https://user-images.githubusercontent.com/1409791/165252178-e63ce525-d635-4148-9162-c565a65b2739.png)

I'm setting `flex-grow: 0;` to all widgets except the button which has `flex-grow: 1;`. But whatever I set `flex-grow` and `flex-shrink` to makes no difference. The result I'm getting is always this:

![image](https://user-images.githubusercontent.com/1409791/165252577-df96c2b6-dff1-4c42-a6b6-92bbafc410fb.png)

I believe the reason is that the Media Carousel has a default `flex-basis: 100%;` rule applied. And there is no way, that I have found, to set the `flex-basis` to `auto `using the Elementor UI.

If I replace the Media Carousel with an Image widget, changing the flex-grow works as expected because the image widget has `flex-basis: auto;` by default.

### Steps to reproduce

* Create two containers, side by side
* Add the Media Carousel and a Text widget to the first container
* Make sure the second container is taller than the first so there is empty space in the first container
* Try to make the Media Carousel not grow using the Elementor UI

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [X] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v5.6.49-89.0
	PHP Version: 7.4.29
	PHP Memory Limit: 256M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 16M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.3
	Site URL: https://elementor.tronica.se
	Home URL: https://elementor.tronica.se
	WP Multisite: No
	Max Upload Size: 16 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Europe/Stockholm
	Admin Email: 
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.5.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.7.0-dev5
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.8.0-dev3
		Author: Elementor.com

== Elements Usage ==
	
	footer : 1
		heading : 1
		spacer : 2
		text-editor : 1
	header : 1
		heading : 1
		nav-menu : 1
		search-form : 1
	wp-post : 0
		alert : 1
		form : 2
		heading : 1
		text-editor : 3
	wp-page : 11
		alert : 2
		author-box : 2
		button : 6
		call-to-action : 1
		code-highlight : 3
		container : 8
		facebook-page : 2
		form : 4
		heading : 8
		image : 3
		media-carousel : 3
		slides : 1
		text-editor : 15

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Active
	Hide native WordPress widgets from search results: Active by default
	: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 20 of 372022-04-25 16:01:33 [info] elementor::elementor_updater Started 
2022-04-25 16:01:33 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-25 16:01:33 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-25 16:01:33 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.3',
  'to' => '3.6.4',
)]
2022-04-25 16:01:33 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.3',
  'to' => '3.6.4',
)]
2022-04-25 16:03:31 [info] elementor-pro::elementor_pro_updater Started 
2022-04-25 16:03:31 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-04-25 16:03:31 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-04-25 16:03:31 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.5.2',
  'to' => '3.6.5',
)]
2022-04-25 16:03:31 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.5.2',
  'to' => '3.6.5',
)]
2022-04-25 16:06:01 [info] elementor::elementor_updater Started 
2022-04-25 16:06:01 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-25 16:06:02 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-25 16:06:02 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.4',
  'to' => '3.7.0-dev5',
)]
2022-04-25 16:06:02 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.4',
  'to' => '3.7.0-dev5',
)]
2022-04-25 16:07:05 [info] elementor-pro::elementor_pro_updater Started 
2022-04-25 16:07:05 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-04-25 16:07:05 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-04-25 16:07:05 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.5',
  'to' => '3.8.0-dev3',
)]
2022-04-25 16:07:05 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.5',
  'to' => '3.8.0-dev3',
)]

PHP: showing 3 of 3PHP: 2021-10-08 02:51:23 [error X 5][/home/vhosts/tronica.se/elementor.tronica.se/wp-content/plugins/elementor/core/wp-api.php::26] Uncaught Error: Call to undefined function Elementor\Core\get_plugins() in /home/vhosts/tronica.se/elementor.tronica.se/wp-content/plugins/elementor/core/wp-api.php:26
Stack trace:
#0 /home/vhosts/tronica.se/elementor.tronica.se/wp-content/plugins/elementor/core/wp-api.php(36): Elementor\Core\Wp_Api->get_plugins()
#1 /home/vhosts/tronica.se/elementor.tronica.se/wp-content/plugins/elementor/modules/system-info/reporters/plugins.php(44): Elementor\Core\Wp_Api->get_active_plugins()
#2 /home/vhosts/tronica.se/elementor.tronica.se/wp-content/plugins/elementor/modules/system-info/reporters/plugins.php(75): Elementor\Modules\System_Info\Reporters\Plugins->get_plugins()
#3 /home/vhosts/tronica.se/elementor.tronica.se/wp-content/plugins/elementor/modules/system-info/module.php(298): Elementor\Modules\System_Info\Reporters\Plugins->is_enabled()
#4 /home/vhosts/tronica.se/elementor.tronica.se/wp-content/plugins/elementor/modules/system-info/module.php(255): Elementor\Modules\System_Info\Module->create_reporter(Array)
#5 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-07 15:35:29 [error X 11][/home/vhosts/tronica.se/elementor.tronica.se/wp-content/plugins/elementor/core/wp-api.php::26] Uncaught Error: Call to undefined function Elementor\Core\get_plugins() in /home/vhosts/tronica.se/elementor.tronica.se/wp-content/plugins/elementor/core/wp-api.php:26
Stack trace:
#0 /home/vhosts/tronica.se/elementor.tronica.se/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(96): Elementor\Core\Wp_Api->get_plugins()
#1 /home/vhosts/tronica.se/elementor.tronica.se/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(58): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_with_header()
#2 /home/vhosts/tronica.se/elementor.tronica.se/wp-content/plugins/elementor/modules/compatibility-tag/module.php(57): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_to_check()
#3 /home/vhosts/tronica.se/elementor.tronica.se/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(148): Elementor\Modules\CompatibilityTag\Module->get_plugins_to_check()
#4 /home/vhosts/tronica.se/elementor.tronica.se/wp-includes/class-wp-hook.php(303): Elementor\Modules\C [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-25 16:01:33 [notice X 1][/home/vhosts/tronica.se/elementor.tronica.se/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 2 of 2JS: 2022-04-25 14:11:18 [error X 1][https://elementor.tronica.se/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.0-dev5:2:502387] this.model.isValidChild is not a function 
JS: 2022-04-25 14:15:12 [error X 35][https://elementor.tronica.se/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.0-dev5:2:185245] Cannot read properties of undefined (reading \'data\') 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Incompatible

== Elementor Pro - Compatibility Tag ==

**Comment by perks98** [comment]
I can replicate the same issue. I can only presume they added a set flex-basis of 100% due to issues raised with swiper widgets in the beta stages
