### ISSUE TITLE
🐞 Several bugs in the container.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#18540]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

1- I do not know why, but on all pages, after using the container, the browser horizontal scroll bar is active. (This is very serious)

https://user-images.githubusercontent.com/77163248/166102356-67cc26ce-a0e5-4e40-83d3-5a16d44e2582.mp4

2- In pop-ups, if we reduce the width of the pop-up, the container handles should be centered based on the width of the pop-up. But this is not the case and they stick to the side. https://prnt.sc/RPIgBes3FkO-

3- I still do not know why, but sometimes when we drag a widget, I can not add it to the page. (Container mode in the form of columns)

https://user-images.githubusercontent.com/77163248/166103432-73d75363-560a-4d2f-9ad2-414170745243.mp4

4- If I copy a widget and paste it in another part, it will be created within a section. 

https://user-images.githubusercontent.com/77163248/166103420-ad268b39-721f-46a7-82ce-0bad3e3be0e6.mp4

5- Sometimes, when I move the mouse over the container, a scroll bar appears. This problem exists in the container and I always deal with it.

https://user-images.githubusercontent.com/77163248/166103673-6b0848bf-15ef-4930-8689-cec9b5c9fa45.mp4

6- In the pop-up, I set the height to fit to screen, but in certain cases the vertical scroll bar is activated. I really do not know why. Please use the template below to diagnose the bug. https://prnt.sc/zsqEbw3X7X4U
The problem is solved when I set the pop-up height to custom.

In general, the container has several problems with pop-ups. In the following, I will send you the pop-up template from which I made the above videos, maybe it will help you @shilo-ey .

[elementor-5110-2022-04-30.zip](https://github.com/elementor/elementor/files/8596806/elementor-5110-2022-04-30.zip)

thank you!

### Steps to reproduce

-

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.4.17
	PHP Version: 7.4.29
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.3
	Site URL: https://-
	Home URL: https://-
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Asia/Tehran
	Admin Email: hosein.79@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.5.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: fa_IR
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.6.5
		Author: Elementor.com

	Elementor Pro
		Version: 3.6.5
		Author: Elementor.com

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Inactive
	Accessibility Improvements: Inactive
	Import Export Template Kit: Inactive
	Additional Custom Breakpoints: Inactive
	Hide native WordPress widgets from search results: Active
	: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Active
	Hello Theme Header & Footer: Inactive
	Landing Pages: Inactive
	Color Sampler: Active
	Favorite Widgets: Inactive
	Admin Top Bar: Active
	Page Transitions: Inactive
	Form Submissions: Active
	Scroll Snap: Inactive

== Log ==
	
JS: showing 5 of 5JS: 2022-03-30 15:26:46 [error X 1][https://-/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view927\") has already been destroyed and cannot be used. 
JS: 2022-04-08 14:06:16 [error X 1][https://-/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view2187\") has already been destroyed and cannot be used. 
JS: 2022-04-08 14:16:56 [error X 1][https://-/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view21419\") has already been destroyed and cannot be used. 
JS: 2022-04-14 17:35:59 [error X 7][https://-/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.4:2:515479] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2022-04-29 20:56:42 [error X 6][https://-/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.4:2:391141] Cannot read properties of undefined (reading \'parent\') 

PHP: showing 13 of 13PHP: 2022-04-01 14:46:51 [notice X 11][/home2/-/domains/-/public_html/wp-content/plugins/elementor-pro/modules/forms/classes/form-record.php::179] Undefined index: referrer [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-08 19:08:59 [notice X 3][/home2/-/domains/-/public_html/wp-content/plugins/elementor-pro/includes/source.php::186] Undefined variable: info_data [array (
  'trace' => '
#0: /home2/-/domains/-/public_html/wp-content/plugins/elementor-pro/includes/source.php(186): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home2/-/domains/-/public_html/wp-content/plugins/elementor-pro/includes/source.php(123): Elementor\TemplateLibrary\EFA_Source :: get_info_data()
#2: /home2/-/domains/-/public_html/wp-content/plugins/elementor-pro/includes/source.php(96): Elementor\TemplateLibrary\EFA_Source :: get_library_data()
#3: /home2/-/domains/-/public_html/wp-content/plugins/elementor/includes/template-library/manager.php(201): Elementor\TemplateLibrary\EFA_Source -> get_items()
#4: /home2/-/domains/-/public_html/wp-content/plugins/elementor/includes/template-library/manager.php(228): Elementor\TemplateLibrary\Manager -> get_templates()
',
)]
PHP: 2022-04-12 20:32:24 [error X 1][/home2/-/domains/-/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php::1050] Uncaught TypeError: Argument 2 passed to Elementor\TemplateLibrary\Source_Local::on_save_post() must be an instance of WP_Post, null given, called in /home2/-/domains/-/public_html/wp-includes/class-wp-hook.php on line 309 and defined in /home2/-/domains/-/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php:1050
Stack trace:
#0 /home2/-/domains/-/public_html/wp-includes/class-wp-hook.php(309): Elementor\TemplateLibrary\Source_Local->on_save_post(4970, NULL)
#1 /home2/-/domains/-/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#2 /home2/-/domains/-/public_html/wp-includes/plugin.php(474): WP_Hook->do_action(Array)
#3 /home2/-/domains/-/public_html/wp-includes/post.php(4687): do_action('save_post', 4970, NULL, true)
#4 /home2/-/domains/-/public_html/wp-includes/post.php(4789): wp_insert_post(Array,  [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-14 21:24:16 [notice X 51][/home2/-/domains/-/public_html/wp-content/plugins/elementor-pro/license/updater.php::69] Undefined index: requires [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-24 09:18:57 [notice X 2][/home2/-/domains/-/public_html/wp-content/plugins/elementor-pro/license/updater.php::84] Undefined index: new_version [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-30 02:22:12 [notice X 168][/home2/-/domains/-/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] Argument $control_id from version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-30 02:37:07 [notice X 15][/home2/-/domains/-/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] Argument $control_id from version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home2/-/domains/-/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /home2/-/domains/-/public_html/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home2/-/domains/-/public_html/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home2/-/domains/-/public_html/wp-content/plugins/jet-search/includes/integration.php(108): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-04-30 02:37:07 [notice X 15][/home2/-/domains/-/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] Argument $control_id from version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home2/-/domains/-/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /home2/-/domains/-/public_html/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home2/-/domains/-/public_html/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home2/-/domains/-/public_html/wp-content/plugins/jet-engine/framework/jet-elementor-extension/jet-elementor-extension.php(95): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-04-30 02:37:07 [notice X 15][/home2/-/domains/-/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] Argument $control_id from version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home2/-/domains/-/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /home2/-/domains/-/public_html/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home2/-/domains/-/public_html/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home2/-/domains/-/public_html/wp-content/plugins/jet-engine/framework/jet-elementor-extension/jet-elementor-extension.php(96): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-04-30 02:37:07 [notice X 15][/home2/-/domains/-/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] Argument $control_id from version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home2/-/domains/-/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /home2/-/domains/-/public_html/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home2/-/domains/-/public_html/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home2/-/domains/-/public_html/wp-content/plugins/elementor-extras/includes/plugin.php(856): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-04-30 02:37:07 [notice X 15][/home2/-/domains/-/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] Argument $control_id from version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home2/-/domains/-/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /home2/-/domains/-/public_html/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home2/-/domains/-/public_html/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home2/-/domains/-/public_html/wp-content/plugins/elementor-extras/includes/plugin.php(857): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-04-30 16:07:00 [notice X 2][/home2/-/domains/-/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php::720] ob_end_clean(): failed to delete buffer. No buffer to delete [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-30 16:23:51 [notice X 1][/home2/-/domains/-/public_html/wp-content/plugins/elementor/core/experiments/experiments-reporter.php::89] Undefined index: title [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 20 of 252022-04-13 14:17:28 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'elementor',
  'from' => '3.6.2',
  'to' => '3.6.3',
)]
2022-04-13 14:17:28 [info] elementor::elementor_updater Started 
2022-04-13 14:17:28 [info] elementor/Upgrades - _on_each_version Start  
2022-04-13 14:17:28 [info] elementor/Upgrades - _on_each_version Finished 
2022-04-13 14:17:28 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'elementor',
  'from' => '3.6.2',
  'to' => '3.6.3',
)]
2022-04-13 14:18:08 [info] elementor-pro::elementor_pro_updater Started 
2022-04-13 14:18:08 [info] elementor pro/Upgrades - _on_each_version Start  
2022-04-13 14:18:08 [info] elementor pro/Upgrades - _on_each_version Finished 
2022-04-13 14:18:08 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'elementor pro',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]
2022-04-13 14:18:08 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'elementor pro',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]
2022-04-14 21:24:04 [info] elementor::elementor_updater Started 
2022-04-14 21:24:04 [info] المنتور/Upgrades - _on_each_version Start  
2022-04-14 21:24:04 [info] المنتور/Upgrades - _on_each_version Finished 
2022-04-14 21:24:04 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'elementor',
  'from' => '3.6.3',
  'to' => '3.6.4',
)]
2022-04-14 21:24:04 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'elementor',
  'from' => '3.6.3',
  'to' => '3.6.4',
)]
2022-04-30 02:22:09 [info] elementor::elementor_updater Started 
2022-04-30 02:22:09 [info] المنتور/Upgrades - _on_each_version Start  
2022-04-30 02:22:09 [info] المنتور/Upgrades - _on_each_version Finished 
2022-04-30 02:22:09 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'elementor',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]
2022-04-30 02:22:09 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'elementor',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

**Comment by 79ho3ein** [comment]
@shilo-ey , Regarding the number1 bug I described above, I realized one thing that might help you.
The scroll bar appears only when the container orientation is set to column. Please watch the video below :

https://user-images.githubusercontent.com/77163248/166113963-508a9697-1402-4a4c-87a5-42e54e19b2c2.mp4

Please let me know if you were not successful in reproducing any of the above. thank you
