### ISSUE TITLE
🐞 Bug report: Method 'WP_REST_Controller::get_item_permissions_check' not implemented. Must be overridden in subclass.

### ISSUE THREAD

**Issue by joshcummingsdesign** [elementor/elementor#18563]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Elementor is extending WP_REST_Controller but not implementing the get_item_permissions_check method.

### Steps to reproduce

See the issue in Sentry:
https://sentry.io/share/issue/a6aea5bd2b894087ab11802547c8374c/

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.3.29
	PHP Version: 7.4.28
	PHP Memory Limit: 2048M
	PHP Max Input Vars: 16384
	PHP Max Post Size: 1536M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.3
	Site URL: https://givewp.com
	Home URL: https://givewp.com
	WP Multisite: No
	Max Upload Size: 2 GB
	Memory limit: 40M
	Max Memory limit: 2048M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/Los_Angeles
	Admin Email: info@givewp.com
	Debug Mode: Active

== Theme ==
	Name: GiveWP Website
	Version: 2022.2.6
	Author: Impress.org
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36

== Active Plugins ==
	ACF Local JSON
		Version: 
		Author: 

	Advanced Custom Fields: Font Awesome
		Version: 4.0.3
		Author: Matt Keys

	Advanced Custom Fields PRO
		Version: 5.12.2
		Author: Delicious Brains

	Advanced Post Types Order
		Version: 4.5.4
		Author: Nsp Code

	AffiliateWP
		Version: 2.9.3
		Author: AffiliateWP

	AffiliateWP - Affiliate Forms For Gravity Forms
		Version: 1.2
		Author: Sandhills Development, LLC

	AffiliateWP - PayPal Payouts
		Version: 1.4
		Author: Pippin Williamson and Andrew Munro

	Akismet Anti-Spam
		Version: 4.2.3
		Author: Automattic

	Author Filters
		Version: 3.5.6
		Author: Clarion Technologies

	Category Order and Taxonomy Terms Order
		Version: 1.6
		Author: Nsp-Code

	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Cloudflare
		Version: 4.8.3
		Author: Cloudflare, Inc.

	Disable Emojis (GDPR friendly)
		Version: 1.7.4
		Author: Ryan Hellyer

	Easy Digital Downloads
		Version: 2.11.6
		Author: Easy Digital Downloads

	Easy Digital Downloads - Advanced Reports
		Version: 1.0.2
		Author: Sandhills Development, LLC

	Easy Digital Downloads - All Access
		Version: 1.1.11
		Author: Easy Digital Downloads

	Easy Digital Downloads - Auto Register
		Version: 1.4.1
		Author: Easy Digital Downloads

	Easy Digital Downloads - Featured Downloads
		Version: 1.0.5
		Author: Sandhills Development, LLC

	Easy Digital Downloads - Google AdWords
		Version: 1.1.1
		Author: flowdee

	Easy Digital Downloads - Invoices
		Version: 1.3.4
		Author: Easy Digital Downloads

	Easy Digital Downloads - Manual Purchases
		Version: 2.0.5
		Author: Easy Digital Downloads

	Easy Digital Downloads - PDF Invoices
		Version: 2.2.29
		Author: Sandhills Development, LLC

	Easy Digital Downloads - Recurring Payments
		Version: 2.11.6
		Author: Easy Digital Downloads

	Easy Digital Downloads - Software Licensing
		Version: 3.8.5
		Author: Easy Digital Downloads

	Easy Digital Downloads - Stripe Pro Payment Gateway
		Version: 2.8.11
		Author: Easy Digital Downloads

	Easy Digital Downloads - Zapier
		Version: 1.3.11
		Author: Easy Digital Downloads

	Easy Digital Downloads integration for Help Scout
		Version: 2.2.0
		Author: Thomas Maier

	Elementor
		Version: 3.6.5
		Author: Elementor.com

	Elementor Pro
		Version: 3.6.5
		Author: Elementor.com

	Enhanced Media Library PRO
		Version: 2.8.8
		Author: wpUXsolutions

	GiveWP Website
		Version: 2022.2.6
		Author: Impress.org

	GN Publisher
		Version: 1.3
		Author: Chris Andrews

	Gravity Forms
		Version: 2.6.1
		Author: Gravity Forms

	Gravity Forms ActiveCampaign Add-On
		Version: 2.0
		Author: Gravity Forms

	Gravity Forms Email Blacklist
		Version: 2.5
		Author: hallme

	Gravity Forms Help Scout Add-On
		Version: 2.1
		Author: Gravity Forms

	Gravity Forms Polls Add-On
		Version: 3.9
		Author: Gravity Forms

	Gravity Forms Zapier Add-On
		Version: 4.2
		Author: Gravity Forms

	Hotjar
		Version: 1.0.12
		Author: Hotjar

	Limit Login Attempts Reloaded
		Version: 2.25.1
		Author: Limit Login Attempts Reloaded

	Make Column Clickable Elementor
		Version: 1.4.0
		Author: Fernando Acosta

	Manage Notification E-mails
		Version: 1.8.2
		Author: Virgial Berveling

	Menu Items Visibility Control
		Version: 0.5
		Author: Hassan Derakhshandeh

	Oembed Cache
		Version: 1.0
		Author: 61 Degrees North

	Public Post Preview
		Version: 2.9.3
		Author: Dominik Schilling

	Regenerate Thumbnails
		Version: 3.1.5
		Author: Alex Mills (Viper007Bond)

	SearchWP
		Version: 4.2.2
		Author: SearchWP

	SearchWP Custom Results Order
		Version: 1.3.6
		Author: SearchWP

	SearchWP Exclude UI
		Version: 1.2.2
		Author: SearchWP

	SearchWP Live Ajax Search
		Version: 1.6.2
		Author: SearchWP, LLC

	Simple Local Avatars
		Version: 2.3.0
		Author: Jake Goldman, 10up

	Simply Schedule Appointments
		Version: 4.5.5.2
		Author: N Squared

	SVG Support
		Version: 2.4.2
		Author: Benbodhi

	User Role Editor
		Version: 4.61.2
		Author: Vladimir Garagulya

	User Switching
		Version: 1.5.8
		Author: John Blackbourn & contributors

	Visibility Logic for Elementor
		Version: 2.3.0
		Author: StaxWP

	WP Crontrol
		Version: 1.12.1
		Author: John Blackbourn & crontributors

	WP Fusion
		Version: 3.40.3
		Author: Very Good Plugins

	WP Fusion - Abandoned Cart Addon
		Version: 1.7.2
		Author: Very Good Plugins

	WP Fusion - Enhanced Ecommerce Addon
		Version: 1.18.6
		Author: Very Good Plugins

	WP Offload SES
		Version: 1.5.6
		Author: Delicious Brains

	Yoast Duplicate Post
		Version: 4.4
		Author: Enrico Battocchi & Team Yoast

	Yoast SEO
		Version: 18.6
		Author: Team Yoast

	Yoast SEO Premium
		Version: 18.4
		Author: Team Yoast

	Zapier for WordPress
		Version: 1.0.4
		Author: Zapier

== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

	Health Check Troubleshooting Mode
		Version: 1.7.2
		Author: 

== Elementor Experiments ==
	Optimized DOM Output: Inactive by default
	Improved Asset Loading: Inactive by default
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Inactive by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Inactive by default
	Hide native WordPress widgets from search results: Active by default
	: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 20 of 372022-04-14 10:54:13 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.6',
  'to' => '3.6.4',
)]
2022-04-14 10:54:13 [info] elementor::elementor_updater Started 
2022-04-14 10:54:13 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-14 10:54:13 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-14 10:54:13 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.6',
  'to' => '3.6.4',
)]
2022-04-14 10:54:14 [info] elementor::elementor_updater Started 
2022-04-14 10:54:14 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-14 10:54:14 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-14 10:54:14 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.6',
  'to' => '3.6.4',
)]
2022-04-14 10:54:14 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.6',
  'to' => '3.6.4',
)]
2022-04-18 13:41:41 [info] elementor-pro::elementor_pro_updater Started 
2022-04-18 13:41:41 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-04-18 13:41:41 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-04-18 13:41:41 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]
2022-04-29 15:46:59 [info] elementor::elementor_updater Started 
2022-04-29 15:46:59 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-29 15:46:59 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-29 15:46:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]
2022-04-29 15:46:59 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]
2022-04-29 15:47:00 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]

PHP: showing 5 of 5PHP: 2022-03-21 16:55:12 [notice X 60][/chroot/home/ab130e41/087c98f5e1.nxcli.net/html/wp-content/plugins/elementor-pro/modules/forms/classes/activecampaign-handler.php::133] Undefined index: textarea [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-01 17:33:20 [error X 2][/chroot/home/ab130e41/087c98f5e1.nxcli.net/html/wp-content/plugins/elementor/data/v2/base/controller.php::227] Uncaught Elementor\Data\V2\Base\Exceptions\WP_Error_Exception: Method 'WP_REST_Controller::get_item_permissions_check' not implemented. Must be overridden in subclass. in /chroot/home/ab130e41/087c98f5e1.nxcli.net/html/wp-content/plugins/elementor/data/v2/base/controller.php:227
Stack trace:
#0 /chroot/home/ab130e41/087c98f5e1.nxcli.net/html/wp-content/plugins/elementor/data/v2/base/base-route.php(105): Elementor\Data\V2\Base\Controller->get_permission_callback(Object(WP_REST_Request))
#1 /chroot/home/ab130e41/087c98f5e1.nxcli.net/html/wp-content/plugins/elementor/data/v2/base/base-route.php(242): Elementor\Data\V2\Base\Base_Route->get_permission_callback(Object(WP_REST_Request))
#2 /chroot/home/ab130e41/087c98f5e1.nxcli.net/html/wp-includes/rest-api/class-wp-rest-server.php(1108): Elementor\Data\V2\Base\Base_Route->Elementor\Data\V2\Base\{closure}(Object(WP_REST_Request))
#3 /chroot/home/ab130e41/087c98f5e1.nxcli.net/html/wp-includes/rest-api/class-wp-rest-server.php(988): WP_REST_Server->respond_to_request( [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-20 12:06:20 [notice X 2][/chroot/home/ab130e41/087c98f5e1.nxcli.net/html/wp-content/plugins/elementor/core/experiments/experiments-reporter.php::89] Undefined index: title [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-23 23:02:39 [warning X 1][/chroot/home/ab130e41/087c98f5e1.nxcli.net/html/wp-content/plugins/elementor/includes/compatibility.php::242] strpos() expects parameter 1 to be string, array given [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-26 11:59:58 [notice X 2][/chroot/home/ab130e41/087c98f5e1.nxcli.net/html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	Make Column Clickable Elementor: Compatibility not specified
	Visibility Logic for Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by joshcummingsdesign** [comment]
See the system info from these issues to see that others are having this issue as well:

#18563, #17887, #17814, #17674, #17653, #17395,

**Comment by Michaelgimii** [comment]
@shilo-ey , Are you aware of this?
