### ISSUE TITLE
🐞 Bug report: Elementor Pro Gallery and Counter widgets not load with Rocket Loader

### ISSUE THREAD

**Issue by MrZyr0** [elementor/elementor#18585]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Since we activated Rocket Loader the images of the Gallery widget are not displayed anymore. The divs are never transformed into img tag.
Even when I disable the deferred mode!

I followed the docs: https://elementor.com/help/elementor-and-cloudflare-rocket-loader/
and by adding the attribute disabling Rocket Loader on the loading of all the scripts integrating the word "gallery" and "elementor". Using a dirty filter.
This does not change anything.

```php
function disable_rocketloader( $tag, $handle, $src ) {
        if ( strpos( $tag, 'gallery' ) !== false ) {
                $tag = str_replace( 'src=', 'data-cfasync="false" src=', $tag );
        }

        if ( strpos( $tag, 'elementor' ) !== false ) {
                $tag = str_replace( 'src=', 'data-cfasync="false" src=', $tag );
        }

        return $tag;
}
add_filter( 'script_loader_tag', 'disable_rocketloader', 10, 3 );
```

### Steps to reproduce

1. Add the image gallery to a page with or without lazy loading enabled
2. Enable Rocket Loader to your website.
3. Watch your page

If you disable Rocker Loader the image will appear.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.53 (Debian)
	MySQL version: Source distribution v10.7.3
	PHP Version: 7.4.29
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.3
	Site URL: XXXX
	Home URL: XXXX
	WP Multisite: No
	Max Upload Size: 64 Mo
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: fr-FR
	Timezone: Europe/Paris
	Admin Email: XXX
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.5.0
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: fr_FR
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 5.12.2
		Author: Delicious Brains

	Cookie Notice & Compliance for GDPR / CCPA
		Version: 2.2.3
		Author: Hu-manity.co

	Elementor
		Version: 3.5.6
		Author: Elementor.com

	Elementor Pro
		Version: 3.6.5
		Author: Elementor.com

	Gravity Forms
		Version: 2.6.2
		Author: Gravity Forms

	Imagify
		Version: 1.10
		Author: WP Media

	Insert Headers and Footers
		Version: 1.6.2
		Author: WPBeginner

	MailPoet 3 (New)
		Version: 3.88.2
		Author: MailPoet

	Make Column Clickable Elementor
		Version: 1.4.0
		Author: Fernando Acosta

	Preloader
		Version: 1.0.9
		Author: Alobaidi

	Profile Builder
		Version: 3.7.5
		Author: Cozmoslabs

	Regenerate Thumbnails Advanced
		Version: 2.4.0
		Author: ShortPixel

	The Plus Addons for Elementor Page Builder
		Version: 2.0.8
		Author: POSIMYTH Themes

	wpMandrill
		Version: 1.33
		Author: Mandrill

	Yoast Duplicate Post
		Version: 4.4
		Author: Enrico Battocchi & Team Yoast

	Yoast SEO
		Version: 18.8
		Author: Team Yoast


== Expériences d’Elementor ==
	Sortie DOM optimisée: Inactif par défaut
	Amélioration du chargement des ressources: Inactif par défaut
	Optimisation du chargement du CSS: Inactif par défaut
	Inline Font Icons: Inactif par défaut
	Améliorations de l’accessibilité: Inactif par défaut
	Kit de modèles pour importation et exportation: Actif par défaut
	Points d’arrêt personnalisés supplémentaires: Inactif par défaut
	Masquer les widgets natifs de WordPress des résultats de recherche: Actif par défaut
	Default to New Theme Builder: Actif par défaut
	En-tête et pied de page du thème Hello: Inactif par défaut
	Page d’atterrissage: Actif par défaut
	Echantillon de couleurs: Actif par défaut
	Widgets favoris: Actif par défaut
	Barre supérieure d’administration: Actif par défaut
	Page Transitions: Actif par défaut
	Envois de formulaire: Actif par défaut
	Scroll Snap: Actif par défaut


== Journal ==
	
Log: showing 20 of 272022-03-01 02:34:39 [info] elementor-pro::elementor_pro_updater Started 
2022-03-01 02:34:39 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-03-01 02:34:39 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-03-01 02:34:39 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.2',
  'to' => '3.6.3',
)]
2022-03-01 02:34:39 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.2',
  'to' => '3.6.3',
)]
2022-03-01 02:34:40 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.2',
  'to' => '3.6.3',
)]
2022-03-07 20:34:24 [info] elementor::elementor_updater Started 
2022-03-07 20:34:24 [info] Elementor/Upgrades - _on_each_version Start  
2022-03-07 20:34:24 [info] Elementor/Upgrades - _on_each_version Finished 
2022-03-07 20:34:24 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.5',
  'to' => '3.5.6',
)]
2022-03-07 20:34:24 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.5',
  'to' => '3.5.6',
)]
2022-04-28 11:13:21 [info] elementor-pro::elementor_pro_updater Started 
2022-04-28 11:13:22 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-04-28 11:13:22 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-04-28 11:13:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.3',
  'to' => '3.6.5',
)]
2022-04-28 15:04:50 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.6',
  'to' => '3.6.5',
)]
2022-04-28 15:05:50 [info] elementor::elementor_updater Started 
2022-04-28 15:05:50 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-28 15:05:50 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-28 15:05:50 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.6',
  'to' => '3.6.5',
)]

PHP: showing 10 of 10PHP: 2022-02-28 12:09:57 [notice X 94][/var/www/wp-content/plugins/elementor-pro/modules/dynamic-tags/tags/post-featured-image.php::36] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-21 23:06:51 [notice X 4][/var/www/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-06 17:08:30 [error X 1][/var/www/wp-content/plugins/elementor/includes/template-library/sources/local.php::1042] Uncaught TypeError: Argument 2 passed to Elementor\TemplateLibrary\Source_Local::on_save_post() must be an instance of WP_Post, instance of stdClass given, called in /var/www/wp-includes/class-wp-hook.php on line 309 and defined in /var/www/wp-content/plugins/elementor/includes/template-library/sources/local.php:1042
Stack trace:
#0 /var/www/wp-includes/class-wp-hook.php(309): Elementor\TemplateLibrary\Source_Local->on_save_post()
#1 /var/www/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#2 /var/www/wp-includes/plugin.php(474): WP_Hook->do_action()
#3 /var/www/wp-includes/post.php(4687): do_action()
#4 /var/www/wp-includes/post.php(4789): wp_insert_post()
#5 /var/www/wp-content/plugins/elementor/includes/db.php(235): wp_update_post()
#6 /var/www/wp-content/plugins/elementor/core/base/document.php(1099): Elementor\DB->save_plain_text()
#7 /var/www/wp-content/plugins/elementor/core/base/document.php(663): Elementor\Core\Base\Document->save_elements()
#8 /var/www/wp-content/plugins/elementor/core/ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-06 17:53:44 [notice X 435][/var/www/wp-content/plugins/elementor-pro/modules/forms/classes/form-record.php::179] Undefined index: referrer [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-13 03:36:01 [error X 1][/var/www/wp-content/plugins/elementor-pro/modules/query-control/module.php::21] Uncaught Error: Class 'ElementorPro\Base\Module_Base' not found in /var/www/wp-content/plugins/elementor-pro/modules/query-control/module.php:21
Stack trace:
#0 /var/www/wp-content/plugins/elementor-pro/plugin.php(141): include()
#1 [internal function]: ElementorPro\Plugin->autoload()
#2 /var/www/wp-content/plugins/elementor-pro/core/modules-manager.php(73): spl_autoload_call()
#3 /var/www/wp-content/plugins/elementor-pro/plugin.php(327): ElementorPro\Core\Modules_Manager->__construct()
#4 /var/www/wp-includes/class-wp-hook.php(307): ElementorPro\Plugin->on_elementor_init()
#5 /var/www/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#6 /var/www/wp-includes/plugin.php(474): WP_Hook->do_action()
#7 /var/www/wp-content/plugins/elementor/includes/plugin.php(647): do_action()
#8 /var/www/wp-includes/class-wp-hook.php(307): Elementor\Plugin->init()
#9 /var/www/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#10 /var/www/wp-includes/plugin.php(474): WP_Hook->do_action()
#11 /var/www/wp-sett [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-22 15:12:36 [warning X 1][/var/www/html/wp-content/plugins/elementor/core/files/base.php::194] file_put_contents(/var/www/html/wp-content/uploads/elementor/css/post-40702.css): failed to open stream: Permission denied [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-24 02:56:45 [warning X 1][/var/www/html/wp-content/plugins/elementor/core/files/base.php::194] file_put_contents(/var/www/html/wp-content/uploads/elementor/css/post-40713.css): failed to open stream: Permission denied [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-06 10:48:26 [notice X 2][/var/www/html/wp-content/plugins/elementor/core/base/document.php::1570] Trying to get property 'post_status' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-06 11:42:05 [error X 2][/var/www/html/wp-content/plugins/elementor/includes/base/controls-stack.php::618] Allowed memory size of 67108864 bytes exhausted (tried to allocate 20480 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-06 11:42:11 [error X 4][/var/www/html/wp-content/plugins/elementor/includes/base/widget-base.php::181] Allowed memory size of 67108864 bytes exhausted (tried to allocate 40960 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 5 of 5JS: 2022-03-21 22:07:22 [error X 1][XXXX/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.6:2:321031] U is undefined 
JS: 2022-03-31 16:38:03 [error X 2][XXXX/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.6:2:453888] T is null 
JS: 2022-04-05 14:49:00 [error X 1][XXXX/wp-includes/js/underscore.min.js?ver=1.13.1 line 2 > Function:9:10] morePresets is undefined 
JS: 2022-04-06 14:11:37 [error X 1][XXXX/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.5.6:2:1397] elementor is not defined 
JS: 2022-04-12 07:05:02 [error X 1][XXXX/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=3.6.4:2:18886] this.$element.sticky is not a function 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibilité non spécifiée
	Make Column Clickable Elementor: Compatibilité non spécifiée
	The Plus Addons for Elementor Page Builder: Compatibilité non spécifiée

== Elementor Pro - Compatibility Tag ==
```

**Comment by MrZyr0** [comment]
Up !
Anyone can tell me if I can fix this bug or if it will be fixed soon ?

**Comment by ofmarconi** [comment]
Up!

I'm in need of the same solution.

**Comment by MrZyr0** [comment]
Up again 😢
