### ISSUE TITLE
🐞 Bug report: My Account widget > Account details - Error messages not showing and save redirect incorrect

### ISSUE THREAD

**Issue by leeneilson** [elementor/elementor#18719]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

On the 'My Account' widget for WooCommerce, when you are on the 'Account details' section if any issues occur with the submitted data, no error messages are show. It seems that the notice box is disabled somehow.

Additionally, if there are no issues with the submission, then the page redirects to '/edit-account/?elementor_library=default-kit'. This does not include the page the widget is on, which is my case was '/my-account/' and of course has the default kit bit at the end. Both with and without the page name, the wrong thing is shown.

Thanks.

### Steps to reproduce

Setup WooCommerce with a my account page, as the 'My Account' WooCommerce widget to this. Then view this page and go to the 'Account details' section. Update your details, but miss off something such as leaving your last name blank. The page is refreshed and no error message is shown. Updates are not saved as well.

To find the second issue, do the above but make sure all details needed on the form are filled in and correct. Then submit and it will redirect.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.4.24
	PHP Version: 7.4.29
	PHP Memory Limit: 128M
	PHP Max Input Vars: 2500
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.3
	Site URL: https://example.org
	Home URL: https://example.org
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-GB
	Timezone: Europe/London
	Admin Email: wp@webdesigntelford.co.uk
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.5.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:100.0) Gecko/20100101 Firefox/100.0

== Active Plugins ==
	Disable Gutenberg
		Version: 2.7
		Author: Jeff Starr

	Elementor
		Version: 3.6.5
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.1
		Author: Elementor.com

	Format Media Titles
		Version: 1.0.0
		Author: David Gwyer

	ManageWP - Worker
		Version: 4.9.13
		Author: GoDaddy

	Product Expiry for WooCommerce
		Version: 1.5
		Author: WebCodingPlace

	Regenerate Thumbnails Advanced
		Version: 2.4.0
		Author: ShortPixel

	ShortPixel Image Optimizer
		Version: 4.22.9
		Author: ShortPixel

	WooCommerce
		Version: 6.5.1
		Author: Automattic

	WooCommerce Stripe Gateway
		Version: 6.4.0
		Author: WooCommerce

	Wordfence Security
		Version: 7.5.10
		Author: Wordfence

	Yoast SEO
		Version: 18.9
		Author: Team Yoast

== Must-Use Plugins ==
	ManageWP - Worker Loader
		Version: 1.0.0
		Author: GoDaddy

== Elementor Experiments ==
	Optimised DOM Output: Inactive by default
	Improved asset loading: Inactive by default
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Accessibility improvements: Inactive by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Inactive by default
	Hide native WordPress widgets from search results: Active by default
	: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Inactive by default
	Landing pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Inactive
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 20 of 312022-04-24 12:55:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.2',
  'to' => '3.6.4',
)]
2022-04-24 12:55:58 [info] elementor-pro::elementor_pro_updater Started 
2022-04-24 12:55:58 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-04-24 12:55:58 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-04-24 12:55:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]
2022-04-27 23:59:28 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]
2022-04-27 23:59:29 [info] elementor::elementor_updater Started 
2022-04-27 23:59:29 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-27 23:59:29 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-27 23:59:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]
2022-05-09 22:13:03 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.5',
  'to' => '3.7.0',
)]
2022-05-09 22:13:05 [info] elementor-pro::elementor_pro_updater Started 
2022-05-09 22:13:05 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-05-09 22:13:05 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-05-09 22:13:05 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.5',
  'to' => '3.7.0',
)]
2022-05-17 00:48:00 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.0',
  'to' => '3.7.1',
)]
2022-05-17 00:48:03 [info] elementor-pro::elementor_pro_updater Started 
2022-05-17 00:48:03 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-05-17 00:48:03 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-05-17 00:48:03 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.0',
  'to' => '3.7.1',
)]

PHP: showing 8 of 8PHP: 2022-04-24 21:51:22 [notice X 4][/home/sites/19a/8/8404d7e937/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-19 04:34:00 [notice X 1][/home/sites/19a/8/8404d7e937/public_html/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php::1483] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-19 05:14:22 [error X 2][/home/sites/19a/8/8404d7e937/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on bool in /home/sites/19a/8/8404d7e937/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /home/sites/19a/8/8404d7e937/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/sites/19a/8/8404d7e937/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/sites/19a/8/8404d7e937/public_html/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/sites/19a/8/8404d7e937/public_html/wp-includes/class-wp [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-20 11:16:10 [notice X 2][/home/sites/19a/8/8404d7e937/public_html/wp-content/plugins/elementor/includes/managers/image.php::87] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-21 10:07:19 [notice X 21][/home/sites/19a/8/8404d7e937/public_html/wp-content/plugins/elementor-pro/modules/woocommerce/widgets/cart.php::2400] Undefined index: section_coupon_display [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-21 10:13:24 [notice X 37][/home/sites/19a/8/8404d7e937/public_html/wp-content/plugins/elementor-pro/modules/woocommerce/widgets/checkout.php::4130] Undefined index: coupon_section_display [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-21 20:52:34 [notice X 5][/home/sites/19a/8/8404d7e937/public_html/wp-content/plugins/elementor-pro/modules/posts/skins/skin-content-base.php::264] Trying to get property 'ID' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-22 05:26:14 [error X 1][/home/sites/19a/8/8404d7e937/public_html/wp-content/plugins/elementor/includes/managers/widgets.php::367] Uncaught Error: Call to a member function is_editable_by_current_user() on bool in /home/sites/19a/8/8404d7e937/public_html/wp-content/plugins/elementor/includes/managers/widgets.php:367
Stack trace:
#0 [internal function]: Elementor\Widgets_Manager->ajax_render_widget(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#1 /home/sites/19a/8/8404d7e937/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/sites/19a/8/8404d7e937/public_html/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#3 /home/sites/19a/8/8404d7e937/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#4 /home/sites/19a/8/8404d7e937/public_html/wp-includes/plugin.php(474): WP_Hook->do_action(Array)
#5 /home/sites/19a/8/8404d7e937/public_html/wp-admin/admin-ajax.php(187): do_action('wp_ajax_element...')
#6 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 3 of 3JS: 2022-05-20 11:01:46 [error X 3][https://example.org/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.5:2:632588] this.container is undefined 
JS: 2022-05-20 11:04:52 [error X 490][https://example.org/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:19643] this.getColorRepresentation() is null 
JS: 2022-05-20 11:40:33 [error X 2][https://example.org/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.5:2:515477] T is null 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by makaus** [comment]
Same problem here.
Any news on this?

**Comment by leeneilson** [comment]
> Same problem here. Any news on this?

Not heard anything yet, unfortunately it's still happening. I couldn't figure out a fix

**Comment by 319heads** [comment]
Same issue here, super annoying.

**Comment by leeneilson** [comment]
Any ideas what we can do @rami-elementor ?

**Comment by beeween** [comment]
If it's message "Warning section_coupon_display" => Enable coupon codes in Woocommerce setting and go to Elementor Cart Page to disable coupon code.

**Comment by banlieues-asbl** [comment]
@line 2384, replace :
if ( '' === $settings['section_coupon_display']) {
by :
if ( '' === $settings['section_coupon_display'] = $settings['section_coupon_display'] ?? '') {

**Comment by vHeemstra** [comment]
> If it's message "Warning section_coupon_display" => Enable coupon codes in Woocommerce setting and go to Elementor Cart Page to disable coupon code.

I'm amazed this is still not fixed after nearly 3 years. Feeling like a true Elementor PRO customer...
