### ISSUE TITLE
🐞 Bug report: Global Setting for Typography word spacing not working

### ISSUE THREAD

**Issue by pauserratgutierrez** [elementor/elementor#18765]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Any value I put in any of the word spacing of every Global typography setting doesn't work. Word spacing for individual elements without global typography works as expected.

### Steps to reproduce

I'm only using Elementor and Elementor Pro and Hello Theme. I haven't done anything special.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.32-35
	PHP Version: 7.4.29
	PHP Memory Limit: 768M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0
	Site URL: http://susannag2.sg-host.com
	Home URL: http://susannag2.sg-host.com
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 40M
	Max Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: es
	Timezone: Europe/Madrid
	Admin Email: terresdalquimia@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.5.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: es_ES
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.6.5
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.1
		Author: Elementor.com

== Experimentos de Elementor ==
	Salida del DOM optimizada: Activo
	Carga de recursos mejorada: Activo
	Carga de CSS mejorada: Activo
	Fuentes de iconos integradas: Activo
	Mejoras de accesibilidad: Activo
	Importar o exportar un kit de plantillas: Activo
	Puntos de ruptura personalizados adicionales: Activo
	Ocultar los widgets nativos de WordPress de los resultados de búsqueda: Activo
	: Inactivo por defecto
	Contenedor Flexbox: Activo
	Por defecto, el nuevo constructor de temas: Activo
	Cabecera y pie de página del tema Hello: Inactivo
	Páginas de destino: Activo
	Muestrario de colores: Activo
	Widgets favoritos: Inactivo
	Barra superior de administración: Activo
	Transiciones de páginas: Inactivo
	Notes: Activo
	Envíos de formulario: Activo
	Ajuste de scroll: Activo

== Registro ==
	
PHP: showing 7 of 7PHP: 2022-04-20 20:07:30 [notice X 1][/home/customer/www/susannag2.sg-host.com/public_html/wp-content/plugins/elementor/core/experiments/experiments-reporter.php::115] Undefined index: title [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-20 20:15:53 [notice X 5][/home/customer/www/susannag2.sg-host.com/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-21 08:12:55 [notice X 1][/home/customer/www/susannag2.sg-host.com/public_html/wp-content/plugins/elementor/core/page-assets/data-managers/font-icon-svg/font-awesome.php::45] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-27 16:34:24 [error X 3][/home/customer/www/susannag2.sg-host.com/public_html/wp-content/plugins/elementor/core/settings/page/manager.php::101] Uncaught Exception: Invalid post. in /home/customer/www/susannag2.sg-host.com/public_html/wp-content/plugins/elementor/core/settings/page/manager.php:101
Stack trace:
#0 /home/customer/www/susannag2.sg-host.com/public_html/wp-content/plugins/elementor/core/base/document.php(1542): Elementor\Core\Settings\Page\Manager->ajax_before_save_settings(Array, NULL)
#1 /home/customer/www/susannag2.sg-host.com/public_html/wp-content/plugins/elementor/core/base/document.php(725): Elementor\Core\Base\Document->save_settings(Array)
#2 /home/customer/www/susannag2.sg-host.com/public_html/wp-content/plugins/elementor/core/kits/manager.php(262): Elementor\Core\Base\Document->update_settings(Array)
#3 /home/customer/www/susannag2.sg-host.com/public_html/wp-content/plugins/elementor/core/kits/manager.php(420): Elementor\Core\Kits\Manager->update_kit_settings_based_on_option('site_name', 'Terres d'A...')
#4 /home/customer/www/susannag2.sg-host.com/public_html/wp-includes/class-wp-hook.php(309): Elementor\Core\Kits\Manager-> [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-27 16:34:45 [error X 2][/home/customer/www/susannag2.sg-host.com/public_html/wp-content/plugins/elementor/core/settings/page/manager.php::101] Uncaught Exception: Invalid post. in /home/customer/www/susannag2.sg-host.com/public_html/wp-content/plugins/elementor/core/settings/page/manager.php:101
Stack trace:
#0 /home/customer/www/susannag2.sg-host.com/public_html/wp-content/plugins/elementor/core/base/document.php(1542): Elementor\Core\Settings\Page\Manager->ajax_before_save_settings(Array, NULL)
#1 /home/customer/www/susannag2.sg-host.com/public_html/wp-content/plugins/elementor/core/base/document.php(725): Elementor\Core\Base\Document->save_settings(Array)
#2 /home/customer/www/susannag2.sg-host.com/public_html/wp-content/plugins/elementor/core/kits/manager.php(262): Elementor\Core\Base\Document->update_settings(Array)
#3 /home/customer/www/susannag2.sg-host.com/public_html/wp-content/plugins/elementor/core/kits/manager.php(424): Elementor\Core\Kits\Manager->update_kit_settings_based_on_option('site_descriptio...', 'Psicologia')
#4 /home/customer/www/susannag2.sg-host.com/public_html/wp-includes/class-wp-hook.php(309): Elementor\Core\Kits\Manager- [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-27 16:47:43 [error X 1][/home/customer/www/susannag2.sg-host.com/public_html/wp-content/plugins/elementor/core/settings/page/manager.php::101] Uncaught Exception: Invalid post. in /home/customer/www/susannag2.sg-host.com/public_html/wp-content/plugins/elementor/core/settings/page/manager.php:101
Stack trace:
#0 /home/customer/www/susannag2.sg-host.com/public_html/wp-content/plugins/elementor/core/base/document.php(1542): Elementor\Core\Settings\Page\Manager->ajax_before_save_settings(Array, NULL)
#1 /home/customer/www/susannag2.sg-host.com/public_html/wp-content/plugins/elementor/core/base/document.php(725): Elementor\Core\Base\Document->save_settings(Array)
#2 /home/customer/www/susannag2.sg-host.com/public_html/wp-content/plugins/elementor/core/kits/manager.php(262): Elementor\Core\Base\Document->update_settings(Array)
#3 /home/customer/www/susannag2.sg-host.com/public_html/wp-content/plugins/elementor/core/kits/manager.php(424): Elementor\Core\Kits\Manager->update_kit_settings_based_on_option('site_descriptio...', 'Psicologias')
#4 /home/customer/www/susannag2.sg-host.com/public_html/wp-includes/class-wp-hook.php(309): Elementor\Core\Kits\Manager [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-27 16:52:38 [warning X 1][/home/customer/www/susannag2.sg-host.com/public_html/wp-content/plugins/elementor/core/app/modules/import-export/import.php::120] Invalid argument supplied for foreach() [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 10 of 102022-04-27 16:17:01 [info] elementor::elementor_updater Started 
2022-04-27 16:17:01 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-27 16:17:01 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-27 16:17:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]
2022-04-27 16:17:01 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]
2022-05-24 19:54:22 [info] elementor-pro::elementor_pro_updater Started 
2022-05-24 19:54:22 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-05-24 19:54:22 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-05-24 19:54:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.5',
  'to' => '3.7.1',
)]
2022-05-24 19:54:22 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.5',
  'to' => '3.7.1',
)]

JS: showing 2 of 2JS: 2022-04-27 16:54:30 [error X 7][http://susannag2.sg-host.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.5:2:605201] elementorFrontend is not defined 
JS: 2022-05-26 18:36:32 [error X 14][http://susannag2.sg-host.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.5:2:391141] Cannot read properties of undefined (reading \'parent\') 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

**Comment by pauserratgutierrez** [comment]
**Update:** I noticed that Word Spacing worked perfectly in a new site with exactly the same setup, version, plugins, themes and elementor experiments. In the site where it wasn't working I changed the Global Typograpgy word spacing to 0 and noticed that word spacing changed to all the above fonts once I setted up the last one.
