### ISSUE TITLE
✅ 🐞 Bug Report: Tab Titles don't stack if if there is not enough horizontal space

### ISSUE THREAD

**Issue by Qara-Penimah** [elementor/elementor#18792]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When using the tabs control with horizontal tabs that extend beyond the column in desktop view the tabs do not stack.

### Steps to reproduce

1. Create a tabs element.
2. Add quite a few tabs.
3. Use horizontal stacking
4. View in desktop mode
5. See that the tabs are cut off at the end

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

<details>
<summary>Click to reveal</summary>

````txt


					
== Server Environment ==
	Operating System: WINNT
	Software: Microsoft-IIS/10.0
	MySQL version: MySQL Community Server - GPL v8.0.28
	PHP Version: 8.1.4
	PHP Memory Limit: 256M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0
	Site URL: https://www.wakeuplookandsee.com
	Home URL: https://www.wakeuplookandsee.com
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 768M
	Max Memory limit: 1024M
	Permalink Structure: /%postname%/
	Language: en-GB
	Timezone: Europe/London
	Debug Mode: Inactive

== Theme ==
	Name: The7
	Version: 10.9.0
	Author: Dream-Theme
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.62 Safari/537.36

== Active Plugins ==
	Ad Inserter
		Version: 2.7.14
		Author: Igor Funa

	Akismet Anti-Spam
		Version: 4.2.4
		Author: Automattic

	All in One SEO
		Version: 4.2.1.1
		Author: All in One SEO Team

	Classic Widgets
		Version: 0.3
		Author: WordPress Contributors

	Disable WP Registration Page
		Version: 1.0.2
		Author: Yudhistira Mauris

	Duplicator Pro
		Version: 4.5.3.1
		Author: Snap Creek

	Elementor
		Version: 3.6.5
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.1
		Author: Elementor.com

	EmbedPress
		Version: 3.3.7
		Author: WPDeveloper

	GDPR Cookie Consent
		Version: 2.3.7
		Author: WebToffee

	Headers Security Advanced & HSTS WP
		Version: 4.8.89
		Author: 🐙  Andrea Ferro, Augusto Bombana

	HTTP Headers
		Version: 1.18.5
		Author: Dimitar Ivanov

	Jetpack
		Version: 10.9.1
		Author: Automattic

	Novel Navigation Links
		Version: 0.1.1
		Author: Mehmet Ali İLGAR

	OneSignal Push Notifications
		Version: 2.2.7
		Author: OneSignal

	PublishPress Series
		Version: 2.9.0.1
		Author: PublishPress

	PWA for WP
		Version: 1.7.46
		Author: Magazine3

	Quotes Collection
		Version: 2.5.2
		Author: Srini G

	Redirection
		Version: 5.2.3
		Author: John Godley

	Redis Object Cache
		Version: 2.0.26
		Author: Till Krüss

	Send email notification to author when post is published
		Version: 1.0.2.1
		Author: I Thirteen Web Solution

	ShortPixel Image Optimizer
		Version: 4.22.9
		Author: ShortPixel

	Simple Custom CSS and JS
		Version: 3.39
		Author: SilkyPress.com

	Stop User Enumeration
		Version: 1.4.4
		Author: Fullworks

	Super Page Cache for Cloudflare
		Version: 4.6.1
		Author: Optimole

	Wicked Folders
		Version: 2.18.12
		Author: Wicked Plugins

	WP 2FA - Two-factor authentication for WordPress
		Version: 2.2.1
		Author: WP White Security

	WP Mail SMTP
		Version: 3.4.0
		Author: WPForms

	WP Offload Media
		Version: 2.6.2
		Author: Delicious Brains


== Elements Usage ==
	
	error-404 : 2
		button : 1
		heading : 1
		spacer : 1
		text-editor : 1
	wp-post : 7
		animated-headline : 2
		blockquote : 27
		heading : 16
		image : 10
		tabs : 1
		text-editor : 62
	wp-page : 11
		accordion : 1
		animated-headline : 1
		blockquote : 1
		divider : 1
		embedpress_pdf : 1
		heading : 13
		image : 7
		image-carousel : 1
		image-gallery : 1
		post-comments : 1
		posts : 5
		reviews : 1
		shortcode : 10
		slides : 1
		social-icons : 1
		spacer : 1
		star-rating : 1
		text-editor : 13


== Elementor Experiments ==
	Optimised DOM Output: Active by default
	Improved asset loading: Active by default
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Accessibility improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Inactive by default
	Hide native WordPress widgets from search results: Active by default
	: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Landing pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default


== Log ==
	
Log: showing 20 of 332022-04-19 09:52:50 [info] elementor-pro::elementor_pro_updater Started 
2022-04-19 09:52:50 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-04-19 09:52:50 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-04-19 09:52:50 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]
2022-04-28 11:32:40 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]
2022-04-28 11:32:42 [info] elementor::elementor_updater Started 
2022-04-28 11:32:42 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-28 11:32:42 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-28 11:32:43 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]
2022-04-28 11:32:44 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]
2022-05-10 13:18:30 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.5',
  'to' => '3.7.0',
)]
2022-05-10 13:18:31 [info] elementor-pro::elementor_pro_updater Started 
2022-05-10 13:18:31 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-05-10 13:18:31 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-05-10 13:18:31 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.5',
  'to' => '3.7.0',
)]
2022-05-16 19:20:32 [info] elementor-pro::elementor_pro_updater Started 
2022-05-16 19:20:32 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-05-16 19:20:32 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-05-16 19:20:32 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.0',
  'to' => '3.7.1',
)]
2022-05-16 19:20:32 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.0',
  'to' => '3.7.1',
)]

PHP: showing 7 of 7PHP: 2022-03-28 10:00:26 [error X 2][..\wp-content\plugins\elementor\includes\controls\groups\base.php::447] Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-01 17:26:18 [warning X 3][..\wp-content\plugins\elementor-pro\modules\library\wp-widgets\elementor-library.php::153] Undefined array key "template_id" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-10 13:18:32 [notice X 3][..\wp-content\plugins\elementor-pro\core\utils\collection.php::75] Return type of ElementorPro\Core\Utils\Collection::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-10 13:35:19 [notice X 2439][..\wp-content\plugins\elementor-pro\core\database\model-base.php::135] Return type of ElementorPro\Core\Database\Model_Base::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: ..\wp-content\plugins\elementor-pro\core\database\model-base.php(10): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ..\wp-content\plugins\elementor-pro\plugin.php(153): class type include()array (
  0 => 'F:\\Websites\\WaleUpLookAndSee\\wp-content\\plugins\\elementor-pro\\core\\database\\model-base.php',
)
#2: ..\wp-content\plugins\elementor-pro\modules\notes\database\models\note.php(18): ElementorPro\Plugin -> autoload()
#3: ..\wp-content\plugins\elementor-pro\plugin.php(153): class type include()array (
  0 => 'F:\\Websites\\WaleUpLookAndSee\\wp-content\\plugins\\elementor-pro\\modules\\notes\\database\\models\\note.php',
)
#4: ..\wp-content\plugins\elementor-pro\modules\notes\data\controller.php(236): ElementorPro\Plugin -> autoload()
',
)]
PHP: 2022-05-13 15:18:24 [notice X 13][..\wp-content\plugins\elementor-pro\core\utils\collection.php::75] Return type of ElementorPro\Core\Utils\Collection::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: ..\wp-content\plugins\elementor-pro\core\utils\collection.php(11): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ..\wp-content\plugins\elementor-pro\plugin.php(153): class type include()array (
  0 => 'F:\\Websites\\WaleUpLookAndSee\\wp-content\\plugins\\elementor-pro\\core\\utils\\collection.php',
)
#2: ..\wp-content\plugins\elementor-pro\core\database\query-builder.php(1222): ElementorPro\Plugin -> autoload()
#3: ..\wp-content\plugins\elementor-pro\core\database\query-builder.php(1081): ElementorPro\Core\Database\Query_Builder -> get_bindings()
#4: ..\wp-content\plugins\elementor-pro\core\database\model-query-builder.php(89): ElementorPro\Core\Database\Query_Builder -> get()
',
)]
PHP: 2022-05-14 09:16:35 [error X 1][..\wp-content\plugins\elementor-pro\modules\notes\usage.php::161] Uncaught Error: Call to a member function format() on null in ..\wp-content\plugins\elementor-pro\modules\notes\usage.php:161
Stack trace:
#0 ..\wp-content\plugins\elementor-pro\modules\notes\usage.php(43): ElementorPro\Modules\Notes\Usage->get_first_interaction()
#1 ..\wp-content\plugins\elementor-pro\modules\notes\usage.php(27): ElementorPro\Modules\Notes\Usage->get_usage_data()
#2 ..\wp-includes\class-wp-hook.php(307): ElementorPro\Modules\Notes\Usage->ElementorPro\Modules\Notes\{closure}()
#3 ..\wp-includes\plugin.php(189): WP_Hook->apply_filters()
#4 ..\wp-content\plugins\elementor\includes\tracker.php(563): apply_filters()
#5 ..\wp-content\plugins\elementor\includes\tracker.php(141): Elementor\Tracker::get_tracking_data()
#6 ..\wp-includes\class-wp-hook.php(307): Elementor\Tracker::send_tracking_data()
#7 ..\wp-includes\class-wp-hook.php(331): WP_Hook->apply_filters()
#8 ..\wp-includes\plugin.php(522): WP_Hook->do_action()
#9 ..\wp-cron.php(138): do_action_ref_array()
#10 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-25 12:54:40 [notice X 1][..\wp-content\plugins\elementor-pro\core\utils\collection.php::75] Return type of ElementorPro\Core\Utils\Collection::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: ..\wp-content\plugins\elementor-pro\core\utils\collection.php(11): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ..\wp-content\plugins\elementor-pro\plugin.php(153): class type include()array (
  0 => 'F:\\Websites\\WaleUpLookAndSee\\wp-content\\plugins\\elementor-pro\\core\\utils\\collection.php',
)
#2: ..\wp-content\plugins\elementor-pro\core\database\query-builder.php(1222): ElementorPro\Plugin -> autoload()
#3: ..\wp-content\plugins\elementor-pro\core\database\query-builder.php(1153): ElementorPro\Core\Database\Query_Builder -> get_bindings()
#4: ..\wp-content\plugins\elementor-pro\modules\notes\database\query\note-query-builder.php(520): ElementorPro\Core\Database\Query_Builder -> update()
',
)]

JS: showing 2 of 2JS: 2022-04-30 13:54:19 [error X 2][https://www.wakeuplookandsee.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.5:2:405325] elementorFrontend.elements.window.jQuery is not a function 
JS: 2022-05-11 09:15:48 [error X 1][https://www.wakeuplookandsee.com/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.6.5:2:5069] Cannot read properties of undefined (reading \'attributes\') 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==
	

			

````

</details>

**Comment by nicholaszein** [comment]
Hello there @Qara-Penimah !

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was solved with the new nested Tabs widget with Elementor Core v3.10.0! 🥳 

To start using it activate the **`Nested Elements`** feature in your WordPress **`Dashboard`** > **`Elementor`** > **`Settings`** > **`Features`** page.

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
