### ISSUE TITLE
🐞 Bug report: open link in new tab (CTRL+CLICK) no longer working when PAGE TRANSITIONS experiment is active

### ISSUE THREAD

**Issue by bauwb** [elementor/elementor#18825]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Open link in new new tab (CTRL+CLICK) is no longer working when 'Page Transitions' is activated. Not for menu links, button links, any links ...

### Steps to reproduce

- activate 'Page Transitions' experiment
- windows: hold CTRL + click on any anchor link (menu, button, whatever, ...)
- apple: not sure what the key binding is to open link in new tab

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.51 (Unix)
	MySQL version: Source distribution v10.3.32
	PHP Version: 7.4.28
	PHP Memory Limit: 512M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0
	Site URL: http://192.168.0.2/mistral
	Home URL: http://192.168.0.2/mistral
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 96M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Europe/Brussels
	Admin Email: bob@spacerkaft.be
	Debug Mode: Active

== Theme ==
	Name: Spacekraft Child Theme
	Version: 1.0.1
	Author: Spacekraft Team
	Child Theme: Yes
	Parent Theme Name: Spacekraft Theme
	Parent Theme Version: 2.5.0
	Parent Theme Author: Spacekraft Team

== User ==
	Role: administrator
	WP Profile lang: nl_NL
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.6.5
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.1
		Author: Elementor.com

Notice: Undefined index: title in /volume1/web/mistral/wp-content/plugins/elementor/core/experiments/experiments-reporter.php on line 89

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Inactive
	Hide native WordPress widgets from search results: Active by default
	: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Inactive
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
PHP: showing 7 of 7PHP: 2022-05-25 01:25:59 [warning X 1][/volume1/web/mistral/wp-content/plugins/elementor/core/app/modules/import-export/import.php::120] Invalid argument supplied for foreach() [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-25 01:34:58 [notice X 41][/volume1/web/mistral/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-25 22:48:00 [notice X 1][/volume1/web/mistral/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php::1483] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-26 17:30:14 [notice X 1][/volume1/web/mistral/wp-content/plugins/elementor/core/experiments/experiments-reporter.php::89] Undefined index: title [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-27 12:41:46 [error X 2][/volume1/web/mistral/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on null in /volume1/web/mistral/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /volume1/web/mistral/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(37, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /volume1/web/mistral/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /volume1/web/mistral/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /volume1/web/mistral/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#5 /volume1/web/mistral/wp-includes/plugin.php(476): [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-27 18:22:37 [notice X 1][/volume1/web/mistral/wp-content/plugins/elementor/includes/managers/image.php::87] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-27 23:41:04 [notice X 8][/volume1/web/mistral/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-gallery.php::36] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 2 of 2JS: 2022-05-25 12:34:28 [error X 9][http://192.168.0.2/mistral/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.5:2:515479] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2022-05-26 13:01:05 [error X 13][http://192.168.0.2/mistral/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.6.5:2:5069] Cannot read properties of undefined (reading \'attributes\') 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

**Comment by bilal53FIX** [comment]
Hello,

We are having the same issue with the latest version of Elementor. Is there any workaround for this?

Thanks & Regards
