### ISSUE TITLE
Elementor Menu Cart Does Not Open Automatically When Adding a Product to Cart

### ISSUE THREAD

**Issue by sstrantz** [elementor/elementor#18831]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

USING HELLO THEME

I have Menu Cart Set to **open automatically when product is added to cart.**
**It does not work.**  I have several sites and it does not work on any of them.

I had to add:  AJAX Add to Cart Plugin to make it work.

-I can't use the AJAX plugin on one of my sites so have to figure out why it doesn't work with Elementor Pro only.

**-I pasted system info, but this happens on all my sites.**

### Steps to reproduce

Adding a product to cart (from product page).  Menu Cart does not open automatically.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.32-35
	PHP Version: 7.4.29
	PHP Memory Limit: 768M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0
	Site URL: https://staging4.sues23.sg-host.com
	Home URL: https://staging4.sues23.sg-host.com
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 40M
	Max Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/Indiana/Indianapolis
	Admin Email: sstrantz@rwps.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.5.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:101.0) Gecko/20100101 Firefox/101.0

== Active Plugins ==
	Code Snippets
		Version: 3.1.0
		Author: Code Snippets Pro

	Custom Product Boxes
		Version: 4.3.1
		Author: WisdmLabs

	Duplicate Page
		Version: 4.4.8
		Author: mndpsingh287

	Elementor
		Version: 3.6.5
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.1
		Author: Elementor.com

	Email Template Customizer for WooCommerce
		Version: 1.1.8
		Author: VillaTheme

	FileBird
		Version: 4.9.9.1
		Author: Ninja Team

	LitExtension: Shopping Carts to WooCommerce
		Version: 1.2.0
		Author: Litextension

	LitExtension Customer Password Plugin
		Version: 1.0.0
		Author: LitExtension

	LitExtension SEO Plugin
		Version: 1.0.1
		Author: LitExtension

	Min Max Quantity & Step Control for WooCommerce
		Version: 2.8
		Author: CodeAstrology

	Min Max Quantity & Step Control for WooCommerce (PRO)
		Version: 2.0.4
		Author: CodeAstrology

	Product Variations Swatches for WooCommerce
		Version: 1.0.5
		Author: VillaTheme

	Rank Math SEO
		Version: 1.0.90
		Author: Rank Math

	Rank Math SEO PRO
		Version: 3.0.13
		Author: Rank Math

	ReviewX
		Version: 1.5.1
		Author: WPDeveloper

	ReviewX Pro
		Version: 1.3.5
		Author: WPDeveloper

	SiteGround Security
		Version: 1.2.8
		Author: SiteGround

	Unlimited Elements for Elementor (Premium)
		Version: 1.5.16
		Author: Unlimited Elements

	W3 Total Cache
		Version: 2.2.1
		Author: BoldGrid

	WooCommerce
		Version: 6.5.1
		Author: Automattic

	WooCommerce Extra Fees Plugin Premium
		Version: 3.8.3
		Author: theDotstore

	WooCommerce Product Add-Ons Ultimate
		Version: 3.11.0
		Author: Plugin Republic

	Woo Discount Rules
		Version: 2.4.1
		Author: Flycart

	WP Rollback
		Version: 1.7.1
		Author: GiveWP.com

== Elements Usage ==
	
	footer : 1
		button : 1
		icon : 1
		icon-list : 3
		image : 1
		text-editor : 2
	header : 1
		icon-list : 2
		image : 2
		nav-menu : 2
		search-form : 2
		woocommerce-menu-cart : 2
	page : 2
		button : 1
		heading : 2
		image : 1
		text-editor : 1
	popup : 1
		video : 1
	product : 10
		accordion : 5
		divider : 8
		heading : 16
		image : 25
		rx-review-widget : 1
		shortcode : 14
		text-editor : 52
		toggle : 6
		ucaddon_woocommerce_product_carousel : 4
		ucaddon_woocommerce_product_grid : 6
		woocommerce-breadcrumb : 9
		woocommerce-product-add-to-cart : 8
		woocommerce-product-images : 8
		woocommerce-product-price : 8
		woocommerce-product-rating : 16
		woocommerce-product-short-description : 2
		woocommerce-product-title : 9
	section : 28
		accordion : 1
		button : 13
		heading : 40
		image : 6
		shortcode : 1
		slides : 1
		text-editor : 20
		toggle : 2
		ucaddon_arrow_navigation : 1
		ucaddon_content_grid2 : 5
		ucaddon_content_slider_new : 1
		ucaddon_remote_control_bullet_navigation : 1
		video : 1
		woocommerce-product-content : 1
	widget : 0
		post-comments : 1
		text-editor : 1
		toggle : 2
		woocommerce-product-content : 1
	wp-page : 13
		button : 6
		heading : 55
		icon-list : 24
		image : 23
		menu-anchor : 1
		template : 25
		text-editor : 76
		toggle : 5
		ucaddon_content_slider_new : 1
		ucaddon_woocommerce_product_carousel : 5
		ucaddon_woocommerce_product_grid : 1
	product-archive : 4
		button : 2
		heading : 12
		text-editor : 9
		theme-archive-title : 3
		ucaddon_woocommerce_category_grid : 1
		ucaddon_woocommerce_product_grid : 10
		woocommerce-archive-description : 3
		woocommerce-breadcrumb : 3

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Inactive
	Accessibility Improvements: Active
	Import Export Template Kit: Inactive
	Additional Custom Breakpoints: Inactive
	Hide native WordPress widgets from search results: Inactive
	: Inactive by default
	Flexbox Container: Inactive
	Default to New Theme Builder: Inactive
	Hello Theme Header & Footer: Inactive
	Landing Pages: Inactive
	Color Sampler: Active
	Favorite Widgets: Inactive
	Admin Top Bar: Active
	Page Transitions: Inactive
	Notes: Active by default
	Form Submissions: Inactive
	Scroll Snap: Inactive

== Log ==
	
PHP: showing 13 of 13PHP: 2022-03-28 11:35:42 [error X 7][/home/customer/www/sues23.sg-host.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::286] Uncaught Error: Call to a member function update_meta() on bool in /home/customer/www/sues23.sg-host.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:286
Stack trace:
#0 /home/customer/www/sues23.sg-host.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/customer/www/sues23.sg-host.com/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/customer/www/sues23.sg-host.com/public_html/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/customer/www/sues23 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-30 08:17:49 [notice X 3026][/home/customer/www/sues23.sg-host.com/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-14 03:25:07 [error X 1][/home/customer/www/sues23.sg-host.com/public_html/wp-content/plugins/elementor/includes/managers/skins.php::111] require(): Failed opening required '/home/customer/www/sues23.sg-host.com/public_html/wp-content/plugins/elementor/includes/base/skin-base.php' (include_path='.:/usr/local/php74/pear') [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-14 04:48:18 [error X 1][/home/customer/www/sues23.sg-host.com/public_html/wp-content/plugins/elementor/includes/plugin.php::714] Uncaught Error: Class 'Elementor\Preview' not found in /home/customer/www/sues23.sg-host.com/public_html/wp-content/plugins/elementor/includes/plugin.php:714
Stack trace:
#0 /home/customer/www/sues23.sg-host.com/public_html/wp-content/plugins/elementor/includes/plugin.php(635): Elementor\Plugin->init_components()
#1 /home/customer/www/sues23.sg-host.com/public_html/wp-includes/class-wp-hook.php(307): Elementor\Plugin->init('')
#2 /home/customer/www/sues23.sg-host.com/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#3 /home/customer/www/sues23.sg-host.com/public_html/wp-includes/plugin.php(474): WP_Hook->do_action(Array)
#4 /home/customer/www/sues23.sg-host.com/public_html/wp-settings.php(587): do_action('init')
#5 /home/customer/www/sues23.sg-host.com/public_html/wp-config.php(102): require_once('/home/customer/...')
#6 /home/customer/www/sues23.sg-host.com/public_html/wp-load.php(50): require_once('/home/customer/...')
#7 /home/customer/www/sues23.sg-host.com/public_html/w [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-19 15:32:08 [error X 1][/home/customer/www/staging2.sues23.sg-host.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::286] Uncaught Error: Call to a member function update_meta() on bool in /home/customer/www/staging2.sues23.sg-host.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:286
Stack trace:
#0 /home/customer/www/staging2.sues23.sg-host.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/customer/www/staging2.sues23.sg-host.com/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/customer/www/staging2.sues23.sg-host.com/public_html/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_requ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-20 09:16:31 [notice X 5][/home/customer/www/staging2.sues23.sg-host.com/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-25 13:58:13 [warning X 1][/home/customer/www/staging2.sues23.sg-host.com/public_html/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/icons/custom-icons.php::180] unlink(circle-1.svg): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-26 08:44:33 [warning X 1][/home/customer/www/staging2.sues23.sg-host.com/public_html/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/icons/icon-sets/icomoon.php::31] file_get_contents(/tmp/Numbers-and-Letters-v1.0/selection.json): failed to open stream: No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-26 08:53:49 [warning X 1][/home/customer/www/staging2.sues23.sg-host.com/public_html/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/icons/icon-sets/icomoon.php::31] file_get_contents(/tmp/Test-v1.0/selection.json): failed to open stream: No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-26 09:10:13 [warning X 1][/home/customer/www/staging2.sues23.sg-host.com/public_html/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/icons/custom-icons.php::180] unlink(circle---f.svg): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-26 09:11:46 [warning X 4][/home/customer/www/staging2.sues23.sg-host.com/public_html/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/icons/icon-sets/icomoon.php::31] file_get_contents(/tmp/Test2-v1.0/selection.json): failed to open stream: No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-26 09:52:51 [warning X 1][/home/customer/www/staging2.sues23.sg-host.com/public_html/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/icons/icon-sets/icomoon.php::31] file_get_contents(/tmp/Test3-v1.0/selection.json): failed to open stream: No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-26 10:56:11 [warning X 1][/home/customer/www/staging2.sues23.sg-host.com/public_html/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/icons/custom-icons.php::180] unlink(circle-4.svg): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 4 of 4JS: 2022-04-04 18:18:03 [error X 1][https://sues23.sg-host.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.1:2:369644] this.$currentEditingArea is null 
JS: 2022-04-19 19:30:43 [error X 20][https://staging2.sues23.sg-host.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.4:2:450542] T.getContainer is not a function 
JS: 2022-05-04 14:37:45 [error X 4][https://staging2.sues23.sg-host.com/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.6.5:2:20179] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got as `content_margin` value. Expected array or object.',
)]
JS: 2022-05-04 17:37:37 [error X 44][https://staging2.sues23.sg-host.com/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:19643] this.getColorRepresentation() is null 

Log: showing 20 of 252022-04-12 07:22:10 [info] elementor-pro::elementor_pro_updater Started 
2022-04-12 07:22:10 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-04-12 07:22:10 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-04-12 07:22:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]
2022-04-12 07:22:10 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]
2022-04-14 05:22:27 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.2',
  'to' => '3.6.4',
)]
2022-04-14 05:22:29 [info] elementor::elementor_updater Started 
2022-04-14 05:22:29 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-14 05:22:30 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-14 05:22:30 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.2',
  'to' => '3.6.4',
)]
2022-04-27 14:11:35 [info] elementor::elementor_updater Started 
2022-04-27 14:11:35 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-27 14:11:35 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]
2022-04-27 14:11:36 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-27 14:11:36 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]
2022-05-17 07:41:07 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.5',
  'to' => '3.7.1',
)]
2022-05-17 07:41:08 [info] elementor-pro::elementor_pro_updater Started 
2022-05-17 07:41:08 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-05-17 07:41:08 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-05-17 07:41:08 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.5',
  'to' => '3.7.1',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	Unlimited Elements for Elementor (Premium): Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by sstrantz** [comment]
I found the problem and it is not with Elementor.  There was a snippet running that was interfering with the menu cart.
