### ISSUE TITLE
🐞 Bug report: Surprising limitation on the archive page for articles

### ISSUE THREAD

**Issue by TajuIK** [elementor/elementor#18926]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When I create a grid for an archive page with a loop element and try to get a lot of search results, only 10 results are possible, no matter what I do. 

When I select Query > Source > Current Query, this happens. For example, if I select Articles, I can specify how many search results are displayed on the archive page. 

Can something be done about this illogicality, preferably soon? I would be very grateful, as this phenomenon is probably an inconvenience for any web designer or weblog designer.

### Steps to reproduce

In my case it's in search results. I use keyword search.

When I select Query > Source > Current Query, this happens. 

For example, if I select Articles, I can specify how many search results are displayed on the archive page. 

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: Apache/2
	MySQL version: MariaDB Server v10.3.32
	PHP Version: 8.0.19
	PHP Memory Limit: 256M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0
	Site URL: https://www.conmentor.fi
	Home URL: https://www.conmentor.fi
	WP Multisite: No
	Max Upload Size: 128 Mt
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%category%/%postname%/
	Language: fi
	Timezone: 0
	Admin Email: ilkka@taju.fi
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.5.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: fi
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 5.12.2
		Author: Delicious Brains

	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Custom Post Type UI
		Version: 1.12.1
		Author: WebDevStudios

	Easy WP SMTP
		Version: 1.4.7
		Author: wpecommerce, alexanderfoxc

	Ele Custom Skin
		Version: 3.1.6
		Author: Dudaster.com

	Elementor
		Version: 3.7.0-dev9
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.8.0-dev17
		Author: Elementor.com

	Envato Elements
		Version: 2.0.11
		Author: Envato

	FileBird Lite
		Version: 4.9.8
		Author: Ninja Team

	HubSpot All-In-One Marketing - Forms, Popups, Live Chat
		Version: 8.12.41
		Author: HubSpot

	Jetpack
		Version: 11.0
		Author: Automattic

	Limit Login Attempts Reloaded
		Version: 2.25.3
		Author: Limit Login Attempts Reloaded

	Malcure WP Malware Scanner &amp; Firewall
		Version: 10.3
		Author: Malcure

	Post Types Order
		Version: 1.9.9
		Author: Nsp Code

	Premium Addons for Elementor
		Version: 4.9.17
		Author: Leap13

	Rank Math SEO
		Version: 1.0.90
		Author: Rank Math

	Site Kit by Google
		Version: 1.75.0
		Author: Google

	Wordfence Security
		Version: 7.5.10
		Author: Wordfence

	WPFront Scroll Top
		Version: 2.0.7.08086
		Author: Syam Mohan

== Must-Use Plugins ==
	WordPress automation by Installatron
		Version: 
		Author: 

== Elements Usage ==
	
	archive : 3
		container : 1
		heading : 1
		posts : 1
	custom_grid : 1
		container : 1
		ele-loop-item : 36
	footer : 1
		container : 11
		heading : 1
		icon : 1
		image-box : 3
		text-editor : 1
	header : 1
		nav-menu : 1
		theme-site-logo : 1
	loop : 1
		container : 2
		icon : 1
		text-editor : 2
		theme-post-featured-image : 1
		theme-post-title : 1
	page : 2
		container : 1
		form : 1
		heading : 1
		icon : 1
		image : 1
		posts : 1
		text-editor : 2
	popup : 2
		heading : 2
		image : 1
		login : 1
	section : 6
		accordion : 1
		button : 14
		divider : 6
		heading : 61
		image : 27
		image-box : 18
		spacer : 3
		testimonial : 11
		text-editor : 22
	widget : 0
		button : 1
	wp-page : 15
		button : 17
		call-to-action : 6
		container : 180
		divider : 2
		form : 1
		gallery : 1
		heading : 55
		icon : 3
		icon-box : 7
		image : 13
		image-box : 6
		image-carousel : 1
		menu-anchor : 8
		posts : 1
		spacer : 3
		testimonial-carousel : 7
		text-editor : 93
	single-post : 1
		container : 2
		icon : 1
		text-editor : 2
		theme-post-content : 1
		theme-post-featured-image : 1
		theme-post-title : 1

== Elementor Experiments ==
	Optimoitu DOM-tulostus: Aktiivinen oletuksena
	Parannettu resurssien lataus: Aktiivinen oletuksena
	Improved CSS Loading: Aktiivinen oletuksena
	Inline Font Icons: Ei-aktiivinen oletuksena
	Saatavuuden parannukset: Aktiivinen oletuksena
	Import Export Template Kit: Aktiivinen oletuksena
	Additional Custom Breakpoints: Aktiivinen oletuksena
	Hide native WordPress widgets from search results: Aktiivinen oletuksena
	: Ei-aktiivinen oletuksena
	Flexbox Container: Aktiivinen
	Default to New Theme Builder: Aktiivinen oletuksena
	Hello Teeman ylä- ja alapalkki: Aktiivinen oletuksena
	Myyntisivut: Aktiivinen oletuksena
	Color Sampler: Aktiivinen oletuksena
	Favorite Widgets: Aktiivinen oletuksena
	Admin Top Bar: Aktiivinen oletuksena
	Page Transitions: Aktiivinen oletuksena
	Notes: Aktiivinen oletuksena
	Form Submissions: Aktiivinen oletuksena
	Scroll Snap: Aktiivinen oletuksena

== Log ==
	
Log: showing 20 of 322022-05-29 03:10:28 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.0-dev8',
  'to' => '3.7.0-dev9',
)]
2022-05-29 03:10:29 [info] Elementor/Upgrades - _on_each_version Finished 
2022-05-29 03:10:29 [info] Elementor/Upgrades - _v_3_7_0_remove_old_elements_usage Start  
2022-05-29 03:10:29 [info] Elementor/Upgrades - _v_3_7_0_remove_old_elements_usage Finished 
2022-05-29 03:10:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.0-dev8',
  'to' => '3.7.0-dev9',
)]
2022-06-06 05:45:28 [info] elementor-pro::elementor_pro_updater Started 
2022-06-06 05:45:28 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-06-06 05:45:28 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-06-06 05:45:28 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.0-dev13',
  'to' => '3.8.0-dev15',
)]
2022-06-06 05:45:29 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.0-dev13',
  'to' => '3.8.0-dev15',
)]
2022-06-08 11:22:49 [info] elementor-pro::elementor_pro_updater Started 
2022-06-08 11:22:49 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-06-08 11:22:49 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-06-08 11:22:49 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.0-dev15',
  'to' => '3.8.0-dev16',
)]
2022-06-12 21:03:42 [info] elementor-pro::elementor_pro_updater Started 
2022-06-12 21:03:42 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-06-12 21:03:42 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-06-12 21:03:42 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.0-dev16',
  'to' => '3.8.0-dev17',
)]
2022-06-12 21:03:43 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.0-dev16',
  'to' => '3.8.0-dev17',
)]
2022-06-12 21:03:44 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.0-dev16',
  'to' => '3.8.0-dev17',
)]

PHP: showing 5 of 5PHP: 2022-05-16 10:26:02 [notice X 13][/home/vpvzraaepp/domains/conmentor.fi/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-16 10:28:42 [notice X 2][/home/vpvzraaepp/domains/conmentor.fi/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/vpvzraaepp/domains/conmentor.fi/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(304): class type trigger_error()
#2: /home/vpvzraaepp/domains/conmentor.fi/public_html/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home/vpvzraaepp/domains/conmentor.fi/public_html/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home/vpvzraaepp/domains/conmentor.fi/public_html/wp-content/plugins/bdthemes-prime-slider-lite/traits/query-controls/select-input/dynamic-select.php(124): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-05-16 11:48:46 [warning X 1][/home/vpvzraaepp/domains/conmentor.fi/public_html/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php::33] Undefined array key 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-05 06:38:49 [warning X 1][/home/vpvzraaepp/domains/conmentor.fi/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key &quot;data&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-08 10:11:27 [error X 3][/home/vpvzraaepp/domains/conmentor.fi/public_html/wp-content/plugins/elementor/core/utils/collection.php::25] Uncaught TypeError: Elementor\Core\Utils\Collection::__construct(): Argument #1 ($items) must be of type array, null given, called in /home/vpvzraaepp/domains/conmentor.fi/public_html/wp-content/plugins/elementor/includes/managers/image.php on line 154 and defined in /home/vpvzraaepp/domains/conmentor.fi/public_html/wp-content/plugins/elementor/core/utils/collection.php:25
Stack trace:
#0 /home/vpvzraaepp/domains/conmentor.fi/public_html/wp-content/plugins/elementor/includes/managers/image.php(154): Elementor\Core\Utils\Collection-&gt;__construct()
#1 /home/vpvzraaepp/domains/conmentor.fi/public_html/wp-content/plugins/elementor/includes/managers/image.php(179): Elementor\Images_Manager-&gt;delete_custom_images()
#2 /home/vpvzraaepp/domains/conmentor.fi/public_html/wp-includes/class-wp-hook.php(309): Elementor\Images_Manager-&gt;Elementor\{closure}()
#3 /home/vpvzraaepp/domains/conmentor.fi/public_html/wp-includes/class-wp-hook.php(331): WP_Hook-&gt;apply_filters()
#4 /home/vpvzraaepp/domains/conmentor.fi/public_html/wp-includes/plugin.php(476): WP_Hook-&gt;do_action()
#5 /home/vpvzraaepp/domains/conmentor.fi/public_html/wp-includes/post.php(6376): do_action()
#6 /home/vpvzraaepp/domains/conmentor.fi/public_html/wp-content/plugins/elementor-pro/modules/screenshots/screenshot.php(113): wp_delete_attachment()
#7 /home/vpvzraaepp/domains/conmentor.fi/public_html/wp-content/plugins/elementor-pro/modules/screenshots/module.php(85): ElementorPro\Modules\Screenshots\Screenshot-&gt;remove_old_attachment()
#8 [internal function]: ElementorPro\Modules\Screenshots\Module-&gt;ajax_delete()
#9 /home/vpvzraaepp/domains/conmentor.fi/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func()
#10 /home/vpvzraaepp/domains/conmentor.fi/public_html/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module-&gt;handle_ajax_request()
#11 /home/vpvzraaepp/domains/conmentor.fi/public_html/wp-includes/class-wp-hook.php(331): WP_Hook-&gt;apply_filters()
#12 /home/vpvzraaepp/domains/conmentor.fi/public_html/wp-includes/plugin.php(476): WP_Hook-&gt;do_action()
#13 /home/vpvzraaepp/domains/conmentor.fi/public_html/wp-admin/admin-ajax.php(187): do_action()
#14 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 5 of 5JS: 2022-05-16 10:32:44 [error X 12][https://www.conmentor.fi/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.7.0-dev8:2:20384] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got as `menu_link` value. Expected array or object.',
)]
JS: 2022-05-16 10:49:32 [error X 1][https://www.conmentor.fi/wp-content/plugins/bdthemes-prime-slider-lite/assets/js/widgets/ps-paranoia.min.js?ver=2.9.4:1:3016] gsap is not defined 
JS: 2022-05-19 09:16:41 [error X 2][https://www.conmentor.fi/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.0-dev8:2:454836] Cannot read properties of undefined (reading \&#039;isEditable\&#039;) 
JS: 2022-05-19 09:16:59 [error X 3][https://www.conmentor.fi/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.7.0-dev8:2:13487] r.get is not a function 
JS: 2022-06-13 10:05:44 [error X 4][https://www.conmentor.fi/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.0-dev9:2:185916] Cannot read properties of undefined (reading \&#039;data\&#039;) 

== Elementor - Compatibility Tag ==
	
	Ele Custom Skin: Compatible
	Elementor Pro: Incompatible
	Envato Elements: Incompatible
	Premium Addons for Elementor: Incompatible

== Elementor Pro - Compatibility Tag ==
	
	Ele Custom Skin: Incompatible
	Envato Elements: Incompatible
	Premium Addons for Elementor: Incompatible

**Comment by rami-elementor** [comment]
It's not an Elementor issue, It's a WordPress issue. Other page builders users report the same problem. By default, archive page query loads 10 items each time.

The solution is very simple, you can change the number of items in your archive pages from WordPress dashboard:

![Reading-Settings-‹-dev-edition-—-WordPress](https://user-images.githubusercontent.com/92088692/175829515-888ae464-ba7b-4747-b945-2ae04b3330bd.png)

**Comment by rami-elementor** [comment]
Related: #13879

**Comment by TajuIK** [comment]
Thank You Rami. <3 I would never have thought of this myself.
