### ISSUE TITLE
🐞 Bug report: elementor pro hooks for forms issue

### ISSUE THREAD

**Issue by themadhatmedia** [elementor/elementor#18936]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

BUG: webhooks not working on prior built content, only on new content.

We built an "After Submit Action".
The the action allows form data to be saved into user meta fields.

The form action allows us to map form fields to "user meta fields"

The problem is that our in our old forms o the site, when our "After Submit Action" is added, the meta fields are supposed to display inside our "control" to be mapped. however they are not.

Any new forms added to he site that we add our "After Submit Action" to, the the Meta Fields are displaying in our "Control" to be mapped.

so we are trying to figure out why our control works perfect and displays all the meta fields to be mapped on a new form, but on an old form not all the meta fields display in the control.

here is a video of the issue:
https://drive.google.com/file/d/18kDbSUqDUmGRiZU0uHAVLgultlKhrL2M/view?usp=sharing

### Steps to reproduce

here is a video of the issue:
https://drive.google.com/file/d/18kDbSUqDUmGRiZU0uHAVLgultlKhrL2M/view?usp=sharing

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.3.34
	PHP Version: 7.4.29
	PHP Memory Limit: 768M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0
	Site URL: https://ipgbusinesscredit.com/portal
	Home URL: https://ipgbusinesscredit.com/portal
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 40M
	Max Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: admin@ipgbusinesscredit.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.5.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.6.6
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.1
		Author: Elementor.com

	Essential Addons for Elementor
		Version: 5.1.5
		Author: WPDeveloper

	Essential Addons for Elementor - Pro
		Version: 5.1.3
		Author: WPDeveloper

	File Manager Advanced
		Version: 4.1.4
		Author: modalweb

	JetEngine
		Version: 2.11.10
		Author: Crocoblock

	JetFormBuilder
		Version: 2.0.6
		Author: Crocoblock

	JetMenu
		Version: 2.1.7
		Author: Crocoblock

	JetTabs For Elementor
		Version: 2.1.17
		Author: Crocoblock

	LearnDash LMS
		Version: 4.2.0.1
		Author: LearnDash

	LearnDash LMS - Elementor
		Version: 1.0.3
		Author: LearnDash

	LearnDash LMS - ProPanel
		Version: 2.1.4.1
		Author: LearnDash

	MadHat Elementor Update Profile
		Version: 1.7
		Author: Mad Hat Media

	Page Redirect Settings
		Version: 1.0.0
		Author: Madhatmedia

	String Locator
		Version: 2.5.0
		Author: Clorith

== Elements Usage ==
	
	footer : 1
		spacer : 1
	header : 3
		eael-offcanvas : 1
		heading : 3
		icon : 1
		image : 1
	page : 8
		button : 37
		call-to-action : 2
		divider : 100
		form : 4
		heading : 52
		icon : 10
		image : 29
		text-editor : 100
	section : 1
		button : 4
		image : 1
	wp-post : 
		button : 205
		call-to-action : 31
		divider : 492
		form : 15
		heading : 308
		icon : 28
		image : 130
		spacer : 11
		text-editor : 512
	wp-page : 16
		button : 9
		divider : 4
		eael-learn-dash-course-list : 1
		form : 9
		heading : 20
		icon : 1
		icon-box : 2
		image : 1
		jet-tabs : 1
		login : 1
		spacer : 2
		text-editor : 12
		video : 1
	single-page : 3
		heading : 6
		icon : 2
		image : 2
		nav-menu : 2
		theme-post-content : 2
	sfwd-topic : 1
		ld-course-content : 1
		ld-course-infobar : 1
		theme-post-content : 1
		theme-post-title : 1
	sfwd-quiz : 1
		ld-course-infobar : 1
		theme-post-content : 1
		theme-post-title : 1
	sfwd-lessons : 1
		ld-course-content : 1
		ld-course-infobar : 1
		theme-post-content : 1
		theme-post-title : 1
	sfwd-courses : 2
		heading : 1
		jet-custom-menu : 1
		ld-course-certificate : 1
		ld-course-content : 2
		ld-course-infobar : 2
		theme-post-content : 1
		theme-post-title : 1

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 7 of 72022-05-16 18:07:30 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.0',
  'to' => '3.7.1',
)]
2022-05-16 18:07:30 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.0',
  'to' => '3.7.1',
)]
2022-06-09 17:15:09 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.5',
  'to' => '3.6.6',
)]
2022-06-09 17:15:09 [info] elementor::elementor_updater Started 
2022-06-09 17:15:09 [info] Elementor/Upgrades - _on_each_version Start  
2022-06-09 17:15:11 [info] Elementor/Upgrades - _on_each_version Finished 
2022-06-09 17:15:11 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.5',
  'to' => '3.6.6',
)]

PHP: showing 14 of 14PHP: 2022-05-16 18:25:43 [notice X 1][/home/ipgbusinesscredi/public_html/portal/wp-content/plugins/elementor-pro/modules/forms/classes/ajax-handler.php::120] Undefined index: form_fields [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-16 19:16:42 [notice X 36][/home/ipgbusinesscredi/public_html/portal/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/ipgbusinesscredi/public_html/portal/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /home/ipgbusinesscredi/public_html/portal/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home/ipgbusinesscredi/public_html/portal/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home/ipgbusinesscredi/public_html/portal/wp-content/plugins/jet-engine/framework/jet-elementor-extension/jet-elementor-extension.php(95): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-05-16 19:16:42 [notice X 36][/home/ipgbusinesscredi/public_html/portal/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/ipgbusinesscredi/public_html/portal/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /home/ipgbusinesscredi/public_html/portal/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home/ipgbusinesscredi/public_html/portal/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home/ipgbusinesscredi/public_html/portal/wp-content/plugins/jet-engine/framework/jet-elementor-extension/jet-elementor-extension.php(96): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-05-20 01:38:50 [notice X 3][/home/ipgbusinesscredi/public_html/portal/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-10 15:37:25 [notice X 4][/home/ipgbusinesscredi/public_html/portal/wp-content/plugins/elementor-pro/modules/query-control/module.php::383] Undefined index: display [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-13 18:09:12 [warning X 12][/home/ipgbusinesscredi/public_html/portal/wp-content/plugins/elementor/core/common/modules/ajax/module.php::269] Cannot modify header information - headers already sent by (output started at /home/ipgbusinesscredi/public_html/portal/wp-content/plugins/MadHat Elementor Update Profile/includes/class-update-action.php:135) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-13 23:57:23 [warning X 1][/home/ipgbusinesscredi/public_html/portal/wp-content/plugins/elementor/core/common/modules/ajax/module.php::269] Cannot modify header information - headers already sent by (output started at /home/ipgbusinesscredi/public_html/portal/wp-content/plugins/MadHat Elementor Update Profile/includes/class-update-action.php:141) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-14 00:02:18 [warning X 2][/home/ipgbusinesscredi/public_html/portal/wp-content/plugins/elementor/core/common/modules/ajax/module.php::269] Cannot modify header information - headers already sent by (output started at /home/ipgbusinesscredi/public_html/portal/wp-content/plugins/MadHat Elementor Update Profile/includes/class-update-action.php:143) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-14 00:08:11 [warning X 6][/home/ipgbusinesscredi/public_html/portal/wp-content/plugins/elementor/core/common/modules/ajax/module.php::269] Cannot modify header information - headers already sent by (output started at /home/ipgbusinesscredi/public_html/portal/wp-content/plugins/MadHat Elementor Update Profile/includes/class-update-action.php:144) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-14 12:57:20 [error X 1][/home/ipgbusinesscredi/public_html/portal/wp-content/plugins/elementor/includes/base/controls-stack.php::2367] Uncaught TypeError: Argument 2 passed to Elementor\Controls_Stack::sanitize_settings() must be of the type array, null given, called in /home/ipgbusinesscredi/public_html/portal/wp-content/plugins/elementor/includes/base/controls-stack.php on line 2381 and defined in /home/ipgbusinesscredi/public_html/portal/wp-content/plugins/elementor/includes/base/controls-stack.php:2367
Stack trace:
#0 /home/ipgbusinesscredi/public_html/portal/wp-content/plugins/elementor/includes/base/controls-stack.php(2381): Elementor\Controls_Stack->sanitize_settings(Array, NULL)
#1 /home/ipgbusinesscredi/public_html/portal/wp-content/plugins/elementor/includes/base/controls-stack.php(1105): Elementor\Controls_Stack->sanitize_settings(Array)
#2 /home/ipgbusinesscredi/public_html/portal/wp-content/plugins/elementor/includes/base/element-base.php(529): Elementor\Controls_Stack->get_data()
#3 /home/ipgbusinesscredi/public_html/portal/wp-content/plugins/elementor/includes/base/widget-base.php(724): Elementor\Element_Base->get_raw_data(tru [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-14 12:57:58 [error X 1][/home/ipgbusinesscredi/public_html/portal/wp-content/plugins/elementor/includes/base/controls-stack.php::2367] Uncaught TypeError: Argument 2 passed to Elementor\Controls_Stack::sanitize_settings() must be of the type array, string given, called in /home/ipgbusinesscredi/public_html/portal/wp-content/plugins/elementor/includes/base/controls-stack.php on line 2381 and defined in /home/ipgbusinesscredi/public_html/portal/wp-content/plugins/elementor/includes/base/controls-stack.php:2367
Stack trace:
#0 /home/ipgbusinesscredi/public_html/portal/wp-content/plugins/elementor/includes/base/controls-stack.php(2381): Elementor\Controls_Stack->sanitize_settings(Array, '')
#1 /home/ipgbusinesscredi/public_html/portal/wp-content/plugins/elementor/includes/base/controls-stack.php(1105): Elementor\Controls_Stack->sanitize_settings(Array)
#2 /home/ipgbusinesscredi/public_html/portal/wp-content/plugins/elementor/includes/base/element-base.php(529): Elementor\Controls_Stack->get_data()
#3 /home/ipgbusinesscredi/public_html/portal/wp-content/plugins/elementor/includes/base/widget-base.php(724): Elementor\Element_Base->get_raw_data(tru [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-14 13:01:24 [warning X 1][/home/ipgbusinesscredi/public_html/portal/wp-content/plugins/elementor/core/common/modules/ajax/module.php::269] Cannot modify header information - headers already sent by (output started at /home/ipgbusinesscredi/public_html/portal/wp-content/plugins/elementor-pro/modules/forms/classes/integration-base.php:73) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-15 09:12:21 [error X 3][/home/ipgbusinesscredi/public_html/portal/wp-content/plugins/elementor/includes/base/controls-stack.php::377] Uncaught TypeError: Argument 2 passed to Elementor\Controls_Stack::add_control() must be of the type array, null given, called in /home/ipgbusinesscredi/public_html/portal/wp-content/plugins/MadHat Elementor Update Profile/includes/class-update-action.php on line 79 and defined in /home/ipgbusinesscredi/public_html/portal/wp-content/plugins/elementor/includes/base/controls-stack.php:377
Stack trace:
#0 /home/ipgbusinesscredi/public_html/portal/wp-content/plugins/MadHat Elementor Update Profile/includes/class-update-action.php(79): Elementor\Controls_Stack->add_control('updateprofileup...', NULL)
#1 /home/ipgbusinesscredi/public_html/portal/wp-content/plugins/elementor-pro/modules/forms/widgets/form.php(819): Update_Action_After_Submit->register_settings_section(Object(ElementorPro\Modules\Forms\Widgets\Form))
#2 /home/ipgbusinesscredi/public_html/portal/wp-content/plugins/elementor/includes/base/controls-stack.php(2282): ElementorPro\Modules\Forms\Widgets\Form->register_controls()
#3 /home/ipgbusinesscredi/pu [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-15 12:29:48 [notice X 2][/home/ipgbusinesscredi/public_html/portal/wp-content/plugins/elementor/core/experiments/experiments-reporter.php::89] Undefined index: title [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 20 of 21JS: 2022-05-18 18:53:54 [error X 18][https://ipgbusinesscredit.com/portal/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.5:2:368805] Cannot read properties of undefined (reading \'isEditable\') 
JS: 2022-05-18 19:37:47 [error X 1][https://ipgbusinesscredit.com/portal/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view213371\") has already been destroyed and cannot be used. 
JS: 2022-05-18 19:37:47 [error X 1][https://ipgbusinesscredit.com/portal/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view213687\") has already been destroyed and cannot be used. 
JS: 2022-05-18 19:37:47 [error X 1][https://ipgbusinesscredit.com/portal/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view204525\") has already been destroyed and cannot be used. 
JS: 2022-05-18 19:37:47 [error X 1][https://ipgbusinesscredit.com/portal/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view133999\") has already been destroyed and cannot be used. 
JS: 2022-05-18 19:37:47 [error X 1][https://ipgbusinesscredit.com/portal/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view213434\") has already been destroyed and cannot be used. 
JS: 2022-05-18 19:37:47 [error X 1][https://ipgbusinesscredit.com/portal/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view213475\") has already been destroyed and cannot be used. 
JS: 2022-05-18 19:37:47 [error X 1][https://ipgbusinesscredit.com/portal/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view213531\") has already been destroyed and cannot be used. 
JS: 2022-05-18 19:37:47 [error X 1][https://ipgbusinesscredit.com/portal/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view213587\") has already been destroyed and cannot be used. 
JS: 2022-05-18 19:37:48 [error X 1][https://ipgbusinesscredit.com/portal/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view214075\") has already been destroyed and cannot be used. 
JS: 2022-05-18 19:37:48 [error X 1][https://ipgbusinesscredit.com/portal/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view214085\") has already been destroyed and cannot be used. 
JS: 2022-05-18 19:37:48 [error X 1][https://ipgbusinesscredit.com/portal/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view214095\") has already been destroyed and cannot be used. 
JS: 2022-05-18 19:37:57 [error X 1][https://ipgbusinesscredit.com/portal/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view214541\") has already been destroyed and cannot be used. 
JS: 2022-05-18 19:37:57 [error X 1][https://ipgbusinesscredit.com/portal/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view215752\") has already been destroyed and cannot be used. 
JS: 2022-05-18 19:37:57 [error X 1][https://ipgbusinesscredit.com/portal/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view215640\") has already been destroyed and cannot be used. 
JS: 2022-05-18 19:37:58 [error X 1][https://ipgbusinesscredit.com/portal/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view216118\") has already been destroyed and cannot be used. 
JS: 2022-05-18 19:37:58 [error X 1][https://ipgbusinesscredit.com/portal/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view216190\") has already been destroyed and cannot be used. 
JS: 2022-05-18 19:37:58 [error X 1][https://ipgbusinesscredit.com/portal/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view216324\") has already been destroyed and cannot be used. 
JS: 2022-05-18 19:37:58 [error X 1][https://ipgbusinesscredit.com/portal/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view216531\") has already been destroyed and cannot be used. 
JS: 2022-05-18 19:37:58 [error X 1][https://ipgbusinesscredit.com/portal/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view216599\") has already been destroyed and cannot be used. 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible
	Essential Addons for Elementor: Compatible
	Essential Addons for Elementor - Pro: Compatible
	JetTabs For Elementor: Incompatible
	LearnDash LMS - Elementor: Compatibility not specified
	MadHat Elementor Update Profile: Compatibility not specified

== Elementor Pro - Compatibility Tag ==
	
	Essential Addons for Elementor: Compatible
	Essential Addons for Elementor - Pro: Compatible
	JetTabs For Elementor: Incompatible

**Comment by sf-steve** [comment]
Are you using an elementor api to pull the fields, and its working inconsistently? If yes, please provide the details including the code you have written for this custom action.
As it stands, this issue is unresolvable, as it relates to a bug in unknown 3rd party code.

As a hint however, if you are using ajax to load the fields, make sure its a POST request, or uses some other cache busting mechanism (append auto generated url param), else your browser could cache the GET request.
