### ISSUE TITLE
🐞 Bug report: Replace URL Does not check Background Images

### ISSUE THREAD

**Issue by jaysonwebtel** [elementor/elementor#19017]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When i run the Replace URL tool I expect it to replace all URLs, including Images

### Steps to reproduce

Copy data from staging site to live site using Plesk Wordpress Toolkit
Run Replace URL tool.  with staging.domain in old field & live domain in new field 
Tool Displays "0 results"

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v5.7.38
	PHP Version: 8.1.7
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 16M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0
	Site URL: https://staging.single-track.co.za
	Home URL: https://staging.single-track.co.za
	WP Multisite: No
	Max Upload Size: 8 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-ZA
	Timezone: Africa/Johannesburg
	Admin Email: jayson@web-telecoms.co.za
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.5.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_ZA
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.53 Safari/537.36 Edg/103.0.1264.37

== Active Plugins ==
	Elementor
		Version: 3.6.6
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.2
		Author: Elementor.com

	Rank Math SEO
		Version: 1.0.91
		Author: Rank Math

	TinyPNG - JPEG, PNG & WebP image compression
		Version: 3.3
		Author: TinyPNG

	WebP Express
		Version: 0.25.5
		Author: Bjørn Rosell

== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

== Elements Usage ==
	
	footer : 1
		heading : 1
	header : 1
		container : 3
		nav-menu : 1
		theme-site-logo : 1
	page : 7
		button : 81
		divider : 44
		form : 2
		heading : 140
		icon-list : 6
		image : 23
		menu-anchor : 11
		price-table : 38
		slides : 72
		social-icons : 4
		spacer : 13
		text-editor : 94
		video : 6
	section : 31
		button : 8
		divider : 4
		form : 1
		heading : 21
		icon : 1
		icon-box : 1
		icon-list : 3
		image : 3
		image-carousel : 1
		menu-anchor : 1
		price-table : 14
		slides : 18
		social-icons : 1
		spacer : 1
		text-editor : 12
		video : 2
	widget : 0
		divider : 1
		heading : 1
		icon-list : 1
		social-icons : 2
		text-editor : 2
	wp-post : 2
		button : 4
		container : 4
		divider : 9
		heading : 15
		image : 6
		slides : 4
		social-icons : 1
		spacer : 3
		text-editor : 17
		video : 1
	wp-page : 6
		button : 25
		container : 7
		divider : 15
		form : 1
		heading : 52
		icon-box : 4
		icon-list : 1
		image : 7
		menu-anchor : 1
		price-table : 19
		slides : 32
		social-icons : 1
		text-editor : 36
		video : 1
	single-post : 1
		post-navigation : 1
		theme-post-content : 1
		theme-post-title : 1

== Elementor Experiments ==
	Optimised DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility Improvements: Active
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Inactive by default
	Hide native WordPress widgets from search results: Active by default
	: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Inactive by default
	Landing Pages: Inactive
	Colour Sampler: Inactive
	Favorite Widgets: Active by default
	Admin Top Bar: Inactive
	Page Transitions: Active by default
	Notes: Inactive
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 20 of 372022-05-11 10:31:34 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-05-11 10:31:34 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.4',
  'to' => '3.7.0',
)]
2022-05-28 15:56:14 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.0',
  'to' => '3.7.1',
)]
2022-05-28 15:56:14 [info] elementor-pro::elementor_pro_updater Started 
2022-05-28 15:56:14 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-05-28 15:56:14 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-05-28 15:56:14 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.0',
  'to' => '3.7.1',
)]
2022-06-11 16:46:58 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.5',
  'to' => '3.6.6',
)]
2022-06-11 16:46:59 [info] elementor::elementor_updater Started 
2022-06-11 16:46:59 [info] Elementor/Upgrades - _on_each_version Start  
2022-06-11 16:47:00 [info] Elementor/Upgrades - _on_each_version Finished 
2022-06-11 16:47:00 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.5',
  'to' => '3.6.6',
)]
2022-06-11 16:47:01 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.5',
  'to' => '3.6.6',
)]
2022-06-17 13:35:36 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.1',
  'to' => '3.7.2',
)]
2022-06-17 13:35:36 [info] elementor-pro::elementor_pro_updater Started 
2022-06-17 13:35:36 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-06-17 13:35:36 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-06-17 13:35:36 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Start  
2022-06-17 13:35:36 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Finished 
2022-06-17 13:35:36 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.1',
  'to' => '3.7.2',
)]

PHP: showing 2 of 2PHP: 2022-06-14 11:22:06 [warning X 5][/var/www/vhosts/single-track.co.za/httpdocs/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-20 12:44:19 [error X 1][/var/www/vhosts/single-track.co.za/staging.single-track.co.za/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on bool in /var/www/vhosts/single-track.co.za/staging.single-track.co.za/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /var/www/vhosts/single-track.co.za/staging.single-track.co.za/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions()
#2 /var/www/vhosts/single-track.co.za/staging.single-track.co.za/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func()
#3 /var/www/vhosts/single-track.co.za/staging.single-track.co.za/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#4 /var/www/vhosts/single-track.co.za/staging.single-track.co.za/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#5 /var/www/vhosts/single-track.co.za/staging.single-track.co.za/wp-includes/plugin.php(476): WP_Hook->do_action()
#6 /var/www/vhosts/single-track.co.za/staging.single-track.co.za/wp-admin/admin-ajax.php(187): do_action()
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 3 of 3JS: 2022-06-20 10:46:15 [error X 2][https://staging.single-track.co.za/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.6:2:611428] Cannot read properties of undefined (reading \'route\') 
JS: 2022-06-20 11:02:04 [error X 21][https://staging.single-track.co.za/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.6:2:391230] Cannot read properties of undefined (reading \'parent\') 
JS: 2022-06-24 14:22:49 [error X 1][https://staging.single-track.co.za/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.6:2:406242] Cannot read properties of null (reading \'id\') 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

**Comment by jtatum** [comment]
I'm seeing this as well. It looks like others are, too. #7376 has a lot of comments, #16967 looks the same, issue seems to go as far back as #1538.

**Comment by vladninja** [comment]
Same for me. Issue is still in place.
How to reproduce: 
1. Use ngrok to share website in other domain
2. Configure ngrok: https://ngrok.com/docs/using-ngrok-with/wordpress
3. Replace URLs in Elementor Tool
4. Regenerate CSS in Elementor

All URLs will be changed, but not for the background images (in my case not for the slider images)
