### ISSUE TITLE
🐞 Bug report: 

### ISSUE THREAD

**Issue by JustinHHarris** [elementor/elementor#19096]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

The My Account widget does not show WooCommerce Subscriptions endpoint

### Steps to reproduce

I can edit the basic WooCommerce endpoints like dashboard, orders, address, etc. But not subscriptions.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.32-35
	PHP Version: 7.4.30
	PHP Memory Limit: 768M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0
	Site URL: https://staging4.theswedishglow.com
	Home URL: https://staging4.theswedishglow.com
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 40M
	Max Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: en-GB
	Timezone: Europe/Amsterdam
	Admin Email: justin@theothersideofthemoon.nl
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.5.0
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Safari/605.1.15

== Active Plugins ==
	Code Snippets
		Version: 3.1.1
		Author: Code Snippets Pro

	Elementor
		Version: 3.6.7
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.2
		Author: Elementor.com

	Enable Media Replace
		Version: 3.6.3
		Author: ShortPixel

	Jetpack
		Version: 11.1
		Author: Automattic

	Mollie Payments for WooCommerce
		Version: 7.2.0
		Author: Mollie

	SiteGround Security
		Version: 1.2.9
		Author: SiteGround

	Ultimate Addons for Elementor
		Version: 1.36.7
		Author: Brainstorm Force

	WooCommerce
		Version: 6.6.1
		Author: Automattic

	WooCommerce All Products For Subscriptions
		Version: 3.3.1
		Author: WooCommerce

	WooCommerce Parcel Pro
		Version: 1.5.36
		Author: Parcel Pro

	WooCommerce Product Bundles
		Version: 6.15.5
		Author: WooCommerce

	WooCommerce Shipping &amp; Tax
		Version: 1.26.2
		Author: WooCommerce

	WooCommerce Subscriptions
		Version: 4.4.0
		Author: WooCommerce

	Yoast Duplicate Post
		Version: 4.5
		Author: Enrico Battocchi & Team Yoast

== Elementor Experiments ==
	Optimised DOM Output: Active
	Improved asset loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Inactive
	Accessibility improvements: Inactive
	Import Export Template Kit: Active
	Additional Custom Breakpoints: Inactive
	Hide native WordPress widgets from search results: Inactive
	: Inactive by default
	Flexbox Container: Inactive
	Default to New Theme Builder: Inactive
	Hello Theme Header & Footer: Active by default
	Landing pages: Inactive
	Color Sampler: Active
	Favorite Widgets: Active
	Admin Top Bar: Inactive
	Page Transitions: Inactive
	Notes: Inactive
	Form Submissions: Inactive
	Scroll Snap: Inactive

== Log ==
	
Log: showing 20 of 222022-06-07 17:46:21 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-06-07 17:46:21 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-06-07 17:46:21 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.4',
  'to' => '3.7.1',
)]
2022-06-16 07:15:53 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.5',
  'to' => '3.6.6',
)]
2022-06-16 07:15:53 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.1',
  'to' => '3.7.2',
)]
2022-06-16 07:15:53 [info] elementor::elementor_updater Started 
2022-06-16 07:15:53 [info] Elementor/Upgrades - _on_each_version Start  
2022-06-16 07:15:53 [info] Elementor/Upgrades - _on_each_version Finished 
2022-06-16 07:15:53 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.5',
  'to' => '3.6.6',
)]
2022-06-16 07:15:59 [info] elementor-pro::elementor_pro_updater Started 
2022-06-16 07:15:59 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-06-16 07:15:59 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-06-16 07:15:59 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Start  
2022-06-16 07:15:59 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Finished 
2022-06-16 07:15:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.1',
  'to' => '3.7.2',
)]
2022-07-05 13:09:56 [info] elementor::elementor_updater Started 
2022-07-05 13:09:56 [info] Elementor/Upgrades - _on_each_version Start  
2022-07-05 13:09:56 [info] Elementor/Upgrades - _on_each_version Finished 
2022-07-05 13:09:56 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.6',
  'to' => '3.6.7',
)]
2022-07-05 13:09:56 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.6',
  'to' => '3.6.7',
)]

JS: showing 10 of 10JS: 2022-06-16 05:28:35 [error X 1115][https://theswedishglow.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.6:2:375571] undefined is not an object (evaluating \&#039;V.get\&#039;) 
JS: 2022-06-24 10:23:25 [error X 8][https://theswedishglow.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.6:2:611428] undefined is not an object (evaluating \&#039;$e.routes.getHistory(\&quot;panel\&quot;).reverse()[0].route\&#039;) 
JS: 2022-06-24 10:23:34 [error X 2][https://theswedishglow.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.6:2:453218] undefined is not an object (evaluating \&#039;elementor.config.document.panel.widgets_settings\&#039;) 
JS: 2022-06-24 11:02:53 [error X 45][https://theswedishglow.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.6:2:516091] null is not an object (evaluating \&#039;T.getBoundingClientRect\&#039;) 
JS: 2022-06-26 04:46:40 [error X 1][https://theswedishglow.com/wp-content/plugins/elementor-pro/assets/lib/sticky/jquery.sticky.min.js?ver=3.7.2:1:757] Argument 1 (\&#039;element\&#039;) to Window.getComputedStyle must be an instance of Element 
JS: 2022-06-26 07:23:13 [error X 1][https://theswedishglow.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.6:2:362277] undefined is not an object (evaluating \&#039;this.container.isEditable\&#039;) 
JS: 2022-06-26 19:11:00 [error X 1][https://theswedishglow.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.6:2:382070] undefined is not an object (evaluating \&#039;this.view.container.isDesignable\&#039;) 
JS: 2022-07-02 09:59:12 [error X 2][https://staging4.theswedishglow.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.6:2:633219] undefined is not an object (evaluating \&#039;this.container.view\&#039;) 
JS: 2022-07-02 11:39:05 [error X 1][https://staging4.theswedishglow.com/wp-content/plugins/elementor-pro/assets/js/gallery.9c61bb9957e10e6d7bda.bundle.min.js:2:5598] undefined is not an object (evaluating \&#039;this.gallery.setSettings\&#039;) 
JS: 2022-07-06 10:39:58 [error X 1][https://staging4.theswedishglow.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.7:3:897947] null is not an object (evaluating \&#039;V.getBoundingClientRect\&#039;) 

PHP: showing 6 of 6PHP: 2022-06-21 08:34:04 [notice X 1][/home/customer/www/theswedishglow.com/public_html/wp-content/plugins/elementor-pro/license/updater.php::84] Undefined index: new_version [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-24 12:22:52 [notice X 32][/home/customer/www/theswedishglow.com/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-24 12:29:45 [notice X 8][/home/customer/www/theswedishglow.com/public_html/wp-content/plugins/elementor/includes/managers/image.php::87] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-24 12:36:13 [error X 3][/home/customer/www/theswedishglow.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on bool in /home/customer/www/theswedishglow.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /home/customer/www/theswedishglow.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/customer/www/theswedishglow.com/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/customer/www/theswedishglow.com/public_html/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module-&gt;handle_ajax_request(&#039;&#039;)
#4 /home/customer/www/theswe [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-29 15:10:38 [notice X 2][/home/customer/www/theswedishglow.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::167] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-01 12:34:03 [notice X 3][/home/customer/www/theswedishglow.com/public_html/wp-content/plugins/elementor/core/experiments/experiments-reporter.php::89] Undefined index: title [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible
	Ultimate Addons for Elementor: Compatible

== Elementor Pro - Compatibility Tag ==
	
	Ultimate Addons for Elementor: Compatible

**Comment by Madgeeno** [comment]
Hi, I'm experiencing this issue as well, and I need a fix for that. 
I see that this issue is open since 3 years already.
Please comment if this is going to be addressed anytime soon. Since my website relies on WCS for managing subscriptions, if there is no solution for this issue we'll need to stop using Elementor Pro as site builder.
Thanks,
Mattia
