### ISSUE TITLE
🐞 Bug report: It looks like the "Unfiltered Uploads" has stopped working.

### ISSUE THREAD

**Issue by wpeasy** [elementor/elementor#19173]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I need to upload JSON files with the Media Uploader.
Elementor settings - Enable Unfiltered File Uploads - Used to work. Now it doesn't

With this enabled I get an unsupported file type warning when uploading JSON files.

If I manually add the PHP code snippet below it works. So it is the Elementor implementation. 

function cc_mime_types($mimes) {
    $mimes['json'] = 'application/json';
    $mimes['svg'] = 'image/svg+xml';
    return $mimes;
}
add_filter('upload_mimes', 'cc_mime_types');

### Steps to reproduce

Enable "Unfiltered File Uploads"

Try to upload a JSON

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MySQL Community Server (GPL) v5.7.37
	PHP Version: 7.4.29
	PHP Memory Limit: 512M
	PHP Max Input Vars: 2000
	PHP Max Post Size: 20M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.1
	Site URL: https://widgets.wpget.au
	Home URL: https://widgets.wpget.au
	WP Multisite: No
	Max Upload Size: 20 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-AU
	Timezone: Australia/Brisbane
	Admin Email: alan@wpget.au
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_AU
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36

== Active Plugins ==
	Code Snippets
		Version: 3.1.1
		Author: Code Snippets Pro

	Elementor
		Version: 3.6.7
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.2
		Author: Elementor.com

	Unlimited Elements for Elementor (Premium)
		Version: 1.5.20
		Author: Unlimited Elements

== Elements Usage ==
	
	container : 1
		container : 7
		gallery : 1
		heading : 5
		html : 3
		icon-box : 2
		text-editor : 6
	footer : 1
		text-editor : 1
	header : 1
		theme-site-logo : 1
	wp-page : 4
		button : 3
		code-highlight : 2
		container : 9
		gallery : 2
		heading : 15
		html : 5
		icon-box : 2
		icon-list : 1
		text-editor : 12
		ucaddon_dynamic_text_js_event : 2

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Inactive
	Hide native WordPress widgets from search results: Active by default
	: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Inactive
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
PHP: showing 4 of 4PHP: 2022-07-14 01:32:53 [notice X 1][/home/widdgetswpget/public_html/wp-content/plugins/elementor/core/common/modules/connect/module.php::230] Trying to get property 'email' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-14 11:40:01 [notice X 3][/home/widdgetswpget/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-14 11:40:41 [notice X 4][/home/widdgetswpget/public_html/wp-content/plugins/elementor/includes/managers/image.php::87] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-14 11:40:45 [error X 1][/home/widdgetswpget/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on null in /home/widdgetswpget/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /home/widdgetswpget/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(6, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/widdgetswpget/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/widdgetswpget/public_html/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/widdgetswpget/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 1 of 1JS: 2022-07-15 03:16:02 [error X 10][https://widgets.wpget.au/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.7:3:475108] Cannot read properties of undefined (reading \'parent\') 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	Unlimited Elements for Elementor (Premium): Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by gerardreches** [comment]
For me it doesn't work many times either when I want to upload some SVG. This option has always been buggy to me for all the time I've been working with Elementor in different websites. Sometimes it works, sometimes it doesn't, which really pisses me off.

**Comment by pajtai** [comment]
Experiencing issue with some SVG files. Won't allow their upload. Have to add a separate plugin to allow unfiltered uploads.

**Comment by caspervoogt** [comment]
Activating 'Enable the option to upload JSON files' in the role manager worked for me.. for SVG files. Elementor should label it better because how would I know toggling on a JSON option would fix SVG uploads?
