### ISSUE TITLE
🐞 Bug report: 

### ISSUE THREAD

**Issue by jje1** [elementor/elementor#19287]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When the plugins, this most recent, Elementor (from version 3.6.7 to 3.6.8), and the one before it, are updated, the Nav Menus become out of consonance. They are still expanded/unstyled. I'm not sure what the technical terms are, but the drop down svg is massive and nested within unstyled <li> tags that take up the majority of the top of the page. I fixed it before I remembered to take a screenshot. The menus are basically expanded in unstyled <li>, and the svg menu icons are very large.

To fix it i have to go into experiments and toggle "Improved CSS Loading" to inactive. Which resolved the problem, then to double check it I reset it back to default and it worked fine as well. I am not sure why it would need to toggle off then back on to fix the issue. The problem was not with LScache or the CDN. I accessed the IP directly and added /?LSCWP_CTRL=before_optm to the URL to bypass the cache.

### Steps to reproduce

Elementor auto updates.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: mariadb.org binary distribution v10.6.8
	PHP Version: 8.1.6
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.1
	Site URL: https://eartian.com
	Home URL: https://eartian.com
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 300M
	Max Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: store@eartian.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 5.12.3
		Author: Delicious Brains

	All In One WP Security
		Version: 4.4.12
		Author: All In One WP Security & Firewall Team

	BEAR – Bulk Editor and Products Manager Professional for WooCommerce
		Version: 2.1.1
		Author: realmag777

	Code Snippets
		Version: 3.2.0
		Author: Code Snippets Pro

	Contact Form 7
		Version: 5.6.1
		Author: Takayuki Miyoshi

	Cost of Goods for WooCommerce
		Version: 2.6.2
		Author: WPFactory

	Discount Rules and Dynamic Pricing for WooCommerce
		Version: 5.8.0
		Author: Asana Plugins

	Elementor
		Version: 3.6.8
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.2
		Author: Elementor.com

	Element Pack Pro
		Version: 6.4.0
		Author: BdThemes

	ElementsKit Lite
		Version: 2.6.3
		Author: Wpmet

	ElementsKit Pro
		Version: 2.6.10
		Author: Wpmet

	Google Listings and Ads
		Version: 2.0.1
		Author: WooCommerce

	HubSpot All-In-One Marketing - Forms, Popups, Live Chat
		Version: 8.15.76
		Author: HubSpot

	Integration for Contact Form 7 and HubSpot
		Version: 1.2.4
		Author: CRM Perks

	LiteSpeed Cache
		Version: 5.0.1
		Author: LiteSpeed Technologies

	MailPoet 3 (New)
		Version: 3.93.0
		Author: MailPoet

	Premium Addons for Elementor
		Version: 4.9.22
		Author: Leap13

	Product Notes for WooCommerce
		Version: 2.8.0
		Author: Algoritmika Ltd

	Real Media Library (Free)
		Version: 4.18.9
		Author: devowl.io

	Site Kit by Google
		Version: 1.79.1
		Author: Google

	Squirrly SEO (Peaks)
		Version: 12.1.10
		Author: Squirrly

	Ultimate Store Kit
		Version: 1.0.2
		Author: BdThemes

	UpdraftPlus - Backup/Restore
		Version: 1.22.14
		Author: UpdraftPlus.Com, DavidAnderson

	WooCommerce
		Version: 6.7.0
		Author: Automattic

	WooCommerce Payments
		Version: 4.5.0
		Author: Automattic

	WooCommerce PayPal Payments
		Version: 1.9.1
		Author: WooCommerce

	WP Extra File Types
		Version: 0.5.2
		Author: Davide Airaghi

	WP Mail SMTP
		Version: 3.5.1
		Author: WPForms

== Elements Usage ==
	
	archive : 2
		theme-archive-title : 2
		woocommerce-products : 2
	footer : 2
		form : 2
		heading : 3
		icon-list : 2
		image : 1
	header : 2
		bdt-search : 2
		nav-menu : 2
		theme-site-logo : 2
		woocommerce-menu-cart : 2
	page : 5
		bdt-advanced-heading : 1
		bdt-tags-cloud : 1
		button : 1
		elementskit-heading : 1
		elementskit-icon-box : 3
		heading : 1
		nav-menu : 1
		premium-addon-banner : 3
		spacer : 1
		text-editor : 1
		usk-shiny-grid : 1
	product : 7
		blockquote : 2
		divider : 2
		elementskit-woo-product-carousel : 2
		heading : 5
		nav-menu : 2
		spacer : 8
		star-rating : 2
		woocommerce-breadcrumb : 2
		woocommerce-product-add-to-cart : 3
		woocommerce-product-content : 3
		woocommerce-product-images : 3
		woocommerce-product-meta : 2
		woocommerce-product-price : 3
		woocommerce-product-related : 1
		woocommerce-product-title : 3
	section : 23
		bdt-search : 1
		button : 1
		divider : 7
		heading : 3
		icon-box : 15
		nav-menu : 1
		premium-addon-maps : 3
		spacer : 2
		text-editor : 1
		theme-site-logo : 1
		usk-shiny-grid : 1
		woocommerce-cart : 1
		woocommerce-menu-cart : 1
	widget : 0
		bdt-dropbar : 3
		divider : 1
		elementskit-woo-product-carousel : 1
		heading : 2
		icon-box : 16
		nav-menu : 2
		premium-addon-maps : 1
		spacer : 1
		text-editor : 1
		usk-shiny-grid : 3
		woocommerce-breadcrumb : 1
		woocommerce-menu-cart : 1
		woocommerce-product-add-to-cart : 1
		woocommerce-product-meta : 1
		woocommerce-product-price : 1
		woocommerce-product-title : 1
	wp-post : 0
		bdt-tags-cloud : 3
	wp-page : 11
		bdt-advanced-heading : 1
		bdt-tags-cloud : 1
		bdt-wc-elements : 1
		blockquote : 2
		button : 1
		divider : 1
		elementskit-contact-form7 : 1
		elementskit-heading : 1
		elementskit-icon-box : 3
		heading : 28
		image : 2
		media-carousel : 2
		nav-menu : 1
		premium-addon-banner : 3
		spacer : 13
		star-rating : 2
		text-editor : 21
		usk-shiny-grid : 4
		woocommerce-cart : 1
		woocommerce-checkout-page : 1
		woocommerce-products : 1
		woocommerce-purchase-summary : 1
	product-post : 0
		bdt-dropbar : 20
		heading : 7
		spacer : 7
		text-editor : 21
		usk-shiny-grid : 7
	product-archive : 6
		heading : 2
		spacer : 5
		theme-archive-title : 1
		usk-shiny-grid : 3
	error-404 : 2
		button : 2
		heading : 2
		text-editor : 2

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
JS: showing 12 of 12JS: 2022-07-02 04:26:12 [error X 7][https://eartian.com/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.6.6:2:5069] Cannot read properties of undefined (reading \'attributes\') 
JS: 2022-07-02 05:02:24 [error X 1][https://eartian.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.6:2:382071] Cannot read properties of undefined (reading \'isDesignable\') 
JS: 2022-07-02 20:54:07 [error X 1][https://eartian.com/wp-includes/js/jquery/jquery.min.js?ver=3.6.0:2:13639] Syntax error, unrecognized expression: . 
JS: 2022-07-03 04:48:28 [error X 1][https://eartian.com/wp-content/uploads/element-pack/minified/js/ep-scripts.js?ver=1656654569:66:754] Cannot read properties of undefined (reading \'tabs_id\') 
JS: 2022-07-04 03:35:02 [error X 17][https://eartian.com/wp-content/uploads/element-pack/minified/js/ep-scripts.js?ver=1656654569:36:64] Cannot read properties of undefined (reading \'titleMultiColor\') 
JS: 2022-07-09 05:07:41 [error X 1][https://eartian.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.7:3:287642] undefined is not an object (evaluating \'T.params.args.data.id\') 
JS: 2022-07-09 05:12:29 [error X 131][https://eartian.com/wp-content/uploads/element-pack/minified/js/ep-scripts.js?ver=1656654569:36:63] undefined is not an object (evaluating \'$settings.titleMultiColor\') 
JS: 2022-07-09 06:57:12 [error X 25][https://eartian.com/wp-includes/js/jquery/jquery.min.js?ver=3.6.0:2:31710] e.dispatchEvent is not a function. (In \'e.dispatchEvent(new CustomEvent(t,{detail:n}))\', \'e.dispatchEvent\' is undefined) 
JS: 2022-07-17 21:56:29 [error X 1][https://eartian.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.7:3:897948] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2022-07-20 04:06:22 [error X 1][https://eartian.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.7:3:443987] Cannot read properties of undefined (reading \'isEditable\') 
JS: 2022-07-21 04:09:12 [error X 1][https://eartian.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.7:3:465985] undefined is not an object (evaluating \'this.view.container.isDesignable\') 
JS: 2022-07-24 21:59:15 [error X 2][https://eartian.com/wp-includes/js/jquery/jquery.min.js?ver=3.6.0:2:13639] Syntax error, unrecognized expression: div.ekit-wc-product-desc.ekit-wc-carousel-desc. 

PHP: showing 13 of 13PHP: 2022-07-02 05:05:48 [notice X 146][/var/www/html/wp-content/plugins/elementor-pro/modules/custom-css/module.php::76] trim(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-02 19:41:28 [notice X 121][/var/www/html/wp-content/plugins/elementor-pro/core/utils/collection.php::75] Return type of ElementorPro\Core\Utils\Collection::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-03 04:51:15 [notice X 7104][/var/www/html/wp-content/plugins/elementor-pro/core/database/model-base.php::135] Return type of ElementorPro\Core\Database\Model_Base::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: /var/www/html/wp-content/plugins/elementor-pro/core/database/model-base.php(10): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /var/www/html/wp-content/plugins/elementor-pro/plugin.php(153): class type include()array (
  0 => '/var/www/html/wp-content/plugins/elementor-pro/core/database/model-base.php',
)
#2: /var/www/html/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php(18): ElementorPro\Plugin -> autoload()
#3: /var/www/html/wp-content/plugins/elementor-pro/plugin.php(153): class type include()array (
  0 => '/var/www/html/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php',
)
#4: /var/www/html/wp-content/plugins/elementor-pro/modules/notes/data/controller.php(236): ElementorPro\Plugin -> autoload()
',
)]
PHP: 2022-07-03 04:51:56 [notice X 2200][/var/www/html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-04 04:01:22 [notice X 801][/var/www/html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /var/www/html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /var/www/html/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /var/www/html/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /var/www/html/wp-content/plugins/ultimate-store-kit/includes/controls/select-input/dynamic-select.php(125): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-07-04 04:22:20 [notice X 2][/var/www/html/wp-content/plugins/elementor-pro/core/utils/collection.php::75] Return type of ElementorPro\Core\Utils\Collection::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: /var/www/html/wp-content/plugins/elementor-pro/core/utils/collection.php(11): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /var/www/html/wp-content/plugins/elementor-pro/plugin.php(153): class type include()array (
  0 => '/var/www/html/wp-content/plugins/elementor-pro/core/utils/collection.php',
)
#2: /var/www/html/wp-content/plugins/elementor-pro/core/database/query-builder.php(1222): ElementorPro\Plugin -> autoload()
#3: /var/www/html/wp-content/plugins/elementor-pro/core/database/query-builder.php(189): ElementorPro\Core\Database\Query_Builder -> get_bindings()
#4: /var/www/html/wp-content/plugins/elementor-pro/modules/notes/database/query/note-query-builder.php(115): ElementorPro\Core\Database\Query_Builder -> add_sub_select()
',
)]
PHP: 2022-07-05 05:22:20 [warning X 1][/var/www/html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::167] Undefined array key "editor_post_id" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-06 02:45:00 [error X 3][/var/www/html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on bool in /var/www/html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /var/www/html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions()
#2 /var/www/html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func()
#3 /var/www/html/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#4 /var/www/html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#5 /var/www/html/wp-includes/plugin.php(476): WP_Hook->do_action()
#6 /var/www/html/wp-admin/admin-ajax.php(187): do_action()
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-07 05:07:34 [error X 3][/var/www/html/wp-content/plugins/elementor-pro/modules/woocommerce/widgets/products.php::398] Uncaught Error: Call to undefined function ElementorPro\Modules\Woocommerce\Widgets\wc_print_notices() in /var/www/html/wp-content/plugins/elementor-pro/modules/woocommerce/widgets/products.php:398
Stack trace:
#0 /var/www/html/wp-content/plugins/elementor/includes/base/controls-stack.php(2221): ElementorPro\Modules\Woocommerce\Widgets\Products->render()
#1 /var/www/html/wp-content/plugins/elementor/includes/base/widget-base.php(609): Elementor\Controls_Stack->render_by_mode()
#2 /var/www/html/wp-content/plugins/elementor/includes/base/widget-base.php(750): Elementor\Widget_Base->render_content()
#3 /var/www/html/wp-content/plugins/elementor/includes/base/element-base.php(447): Elementor\Widget_Base->print_content()
#4 /var/www/html/wp-content/plugins/elementor/includes/base/element-base.php(787): Elementor\Element_Base->print_element()
#5 /var/www/html/wp-content/plugins/elementor/includes/base/element-base.php(447): Elementor\Element_Base->print_content()
#6 /var/www/html/wp-content/plugins/elementor/includes/base/element-base.php(787): Elementor\Element_Base->print_element()
#7 /var/www/html/wp-content/plugins/elementor/includes/base/element-base.php(447): Elementor\Element_Base->print_content()
#8 /var/www/html/wp-content/plugins/elementor/core/base/document.php(1571): Elementor\Element_Base->print_element()
#9 /var/www/html/wp-content/plugins/elementor/core/base/document.php(1022): Elementor\Core\Base\Document->print_elements()
#10 /var/www/html/wp-content/plugins/elementor/includes/frontend.php(1092): Elementor\Core\Base\Document->print_elements_with_wrapper()
#11 /var/www/html/wp-content/plugins/elementor/includes/frontend.php(1006): Elementor\Frontend->get_builder_content()
#12 /var/www/html/wp-includes/class-wp-hook.php(307): Elementor\Frontend->apply_builder_in_content()
#13 /var/www/html/wp-includes/plugin.php(191): WP_Hook->apply_filters()
#14 /var/www/html/wp-content/plugins/wordpress-seo/src/builders/indexable-link-builder.php(103): apply_filters()
#15 /var/www/html/wp-content/plugins/wordpress-seo/src/actions/indexing/abstract-link-indexing-action.php(64): Yoast\WP\SEO\Builders\Indexable_Link_Builder->build()
#16 /var/www/html/wp-content/plugins/wordpress-seo/src/routes/abstract-indexation-route.php(24): Yoast\WP\SEO\Actions\Indexing\Abstract_Link_Indexing_Action->index()
#17 /var/www/html/wp-content/plugins/wordpress-seo/src/routes/indexing-route.php(420): Yoast\WP\SEO\Routes\Abstract_Indexation_Route->run_indexation_action()
#18 /var/www/html/wp-content/plugins/wordpress-seo/src/routes/indexing-route.php(356): Yoast\WP\SEO\Routes\Indexing_Route->run_indexation_action()
#19 /var/www/html/wp-includes/rest-api/class-wp-rest-server.php(1143): Yoast\WP\SEO\Routes\Indexing_Route->index_post_links()
#20 /var/www/html/wp-includes/rest-api/class-wp-rest-server.php(990): WP_REST_Server->respond_to_request()
#21 /var/www/html/wp-includes/rest-api/class-wp-rest-server.php(414): WP_REST_Server->dispatch()
#22 /var/www/html/wp-includes/rest-api.php(394): WP_REST_Server->serve_request()
#23 /var/www/html/wp-includes/class-wp-hook.php(307): rest_api_loaded()
#24 /var/www/html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#25 /var/www/html/wp-includes/plugin.php(524): WP_Hook->do_action()
#26 /var/www/html/wp-includes/class-wp.php(398): do_action_ref_array()
#27 /var/www/html/wp-includes/class-wp.php(770): WP->parse_request()
#28 /var/www/html/wp-includes/functions.php(1330): WP->main()
#29 /var/www/html/wp-blog-header.php(16): wp()
#30 /var/www/html/index.php(17): require('...')
#31 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-19 04:18:43 [error X 4][/var/www/html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on null in /var/www/html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /var/www/html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions()
#2 /var/www/html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func()
#3 /var/www/html/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#4 /var/www/html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#5 /var/www/html/wp-includes/plugin.php(476): WP_Hook->do_action()
#6 /var/www/html/wp-admin/admin-ajax.php(187): do_action()
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-19 04:47:04 [notice X 3][/var/www/html/wp-content/plugins/elementor-pro/core/utils/collection.php::75] Return type of ElementorPro\Core\Utils\Collection::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: /var/www/html/wp-content/plugins/elementor-pro/core/utils/collection.php(11): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /var/www/html/wp-content/plugins/elementor-pro/plugin.php(153): class type include()array (
  0 => '/var/www/html/wp-content/plugins/elementor-pro/core/utils/collection.php',
)
#2: /var/www/html/wp-content/plugins/elementor-pro/core/database/query-builder.php(1222): ElementorPro\Plugin -> autoload()
#3: /var/www/html/wp-content/plugins/elementor-pro/core/database/query-builder.php(1153): ElementorPro\Core\Database\Query_Builder -> get_bindings()
#4: /var/www/html/wp-content/plugins/elementor-pro/modules/notes/database/query/note-query-builder.php(520): ElementorPro\Core\Database\Query_Builder -> update()
',
)]
PHP: 2022-07-19 04:47:34 [notice X 202][/var/www/html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /var/www/html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /var/www/html/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /var/www/html/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /var/www/html/wp-content/plugins/bdthemes-element-pack/includes/controls/select-input/dynamic-select.php(124): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-07-20 05:45:40 [notice X 1][/var/www/html/wp-content/plugins/elementor-pro/core/utils/collection.php::75] Return type of ElementorPro\Core\Utils\Collection::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: /var/www/html/wp-content/plugins/elementor-pro/core/utils/collection.php(11): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /var/www/html/wp-content/plugins/elementor-pro/plugin.php(153): class type include()array (
  0 => '/var/www/html/wp-content/plugins/elementor-pro/core/utils/collection.php',
)
#2: /var/www/html/wp-content/plugins/elementor-pro/core/database/query-builder.php(1222): ElementorPro\Plugin -> autoload()
#3: /var/www/html/wp-content/plugins/elementor-pro/core/database/query-builder.php(1081): ElementorPro\Core\Database\Query_Builder -> get_bindings()
#4: /var/www/html/wp-content/plugins/elementor-pro/core/database/model-query-builder.php(89): ElementorPro\Core\Database\Query_Builder -> get()
',
)]

Log: showing 17 of 172022-07-04 02:33:55 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.6',
  'to' => '3.6.7',
)]
2022-07-04 02:33:56 [info] elementor::elementor_updater Started 
2022-07-04 02:33:56 [info] Elementor/Upgrades - _on_each_version Start  
2022-07-04 02:33:57 [info] Elementor/Upgrades - _on_each_version Finished 
2022-07-04 02:33:57 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.6',
  'to' => '3.6.7',
)]
2022-07-27 20:38:02 [info] elementor::elementor_updater Started 
2022-07-27 20:38:02 [info] Elementor/Upgrades - _on_each_version Start  
2022-07-27 20:38:02 [info] Elementor/Upgrades - _on_each_version Finished 
2022-07-27 20:38:02 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.6.8',
)]
2022-07-27 20:38:03 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.6.8',
)]
2022-07-28 03:52:24 [info] Elementor custom task(s) process has been queued. [array (
  0 => 
  array (
    0 => 
    array (
      0 => 'Elementor\Core\Upgrade\Custom_Tasks',
      1 => 'opt_in_recalculate_usage',
    ),
    1 => 
    array (
      0 => 'Elementor\Core\Upgrade\Custom_Tasks',
      1 => 'opt_in_send_tracking_data',
    ),
  ),
)]
2022-07-28 03:52:25 [info] elementor::custom_task_manger Started 
2022-07-28 03:52:25 [info] Elementor/Tasks - opt_in_recalculate_usage Start  
2022-07-28 03:52:26 [info] Elementor/Tasks - opt_in_recalculate_usage Finished 
2022-07-28 03:52:26 [info] Elementor/Tasks - opt_in_send_tracking_data Start  
2022-07-28 03:52:26 [info] Elementor/Tasks - opt_in_send_tracking_data Finished 
2022-07-28 03:52:26 [info] elementor::custom_task_manger Completed 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible
	Element Pack Pro: Compatible
	Premium Addons for Elementor: Compatible
	Ultimate Store Kit: Compatible

== Elementor Pro - Compatibility Tag ==

**Comment by rami-elementor** [comment]
Basically you are saying that activating "**Improved CSS Loading**" breaks the "**Nav Menu**".

**Comment by jje1** [comment]
Right. If it is activated when elementor updates. After the update I must deactivate it, then I can reactivate it, and it is fine.

---

________________________________

**Comment by rami-elementor** [comment]
Issue title updated.

**Comment by gitout734** [comment]
yes this has not been fixed yet. it still breaks it and causes them to load as bulleted lists instead. making css loading inactive fixes it.

**Comment by karol-may** [comment]
still there

**Comment by JoeFLC** [comment]
I've been experiencing this as well. I manage nearly 40 websites based off the same design for a client and every time Elementor updates at least one or two of them (random) seem to have this issue, causing the entire website to become unusable until I fix it. 

The header is just a site logo widget and a menu widget, with no custom CSS. Everything else under the menu seems fine when I temporarily hide it with live use of 'display: none'.

Clearing third-party cache plugins (when present) has no effect.

In the past I was able to fix it by using Tools -> Regenerate CSS & Data, but for the last two I noticed that the issue went away when I simply clicked on those ubiquitous Database Update notifications that always say they are running in the background but never seem to actually go away without manual intervention (or another pending database update).

After reading the above, I'm going to try turning off 'Improved CSS Loading' indefinitely to see if that is an effective workaround. Losing a little bit of performance is better than losing entire client websites regularly.

**Comment by JoeFLC** [comment]
I just had something similar happen again on a website unrelated to the ones above. I went to disable 'Improved CSS Loading' and it was set to default, but the button was grey instead of green due to 'Inactive' apparently being the new default.

There was a key difference this time: This website was experiencing CSS issues outside of the header area as well (and has done in the past). As before, the problem was resolved by manually forcing the Elementor Pro Data Updater to complete. I checked the ~40 other websites that I had explicitly set to 'Inactive' and they all looked fine.

I suspect that some way to reliably automate or schedule the Data Updater process so that it completes successfully would go a long way to mitigate or even resolve multiple issues. Is there any way to diagnose why it often doesn't do so?

**Comment by abhishukla610** [comment]
Please FIX THIS!
Sorry for my language but this thing is killing me and mental health badly from last 4 days!

Yes this bug is big for an eCommerce store, it's create very chaos, finally after 4th day i find this solution, i literally restore my backups for this and find this solution now.

Yes fix this, basically this bug is casing chunk error and not run fronted side nav library and script.

**Comment by JoeFLC** [comment]
FYI, if your issue is unresolved by changing the 'Improved CSS Loading" setting, the below help page may be useful despite its seemingly unrelated title. 

A few things are discussed but the primary workaround recommended is switching your CSS Print Method to “Internal Embedding”. I believe it's less efficient, but more reliable.

**Title:** My changes do not appear online, what can I do?

**Link:** [https://elementor.com/help/changes-dont-appear-online/](https://elementor.com/help/changes-dont-appear-online/)

**Comment by saawood13** [comment]
+1 this issue just occurred for me. Turned off that experimental css setting and the menu is now fixed.
