### ISSUE TITLE
🐞 Bug report: Display conditions fatal error caused by removing before loading page

### ISSUE THREAD

**Issue by breakerh** [elementor/elementor#19291]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When i open Custom Code and try to edit the conditions, and remove a condition that's still loading.
Conditions crashes and the edit button also disappears.

![example](https://user-images.githubusercontent.com/2008632/181513831-9797f51c-937b-434e-a1ee-f10c497a74a6.gif)

### Steps to reproduce

1. Open custom
2. click Edit at the conditions line
3. Remove a condition that's still loading (for example singular page condition with the last box empty)
4. After the page is loaded it tries to fill the condition which is removed and crashes resulting in the popup closing and the condition edit button disappears.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2
	MySQL version: MariaDB Server v10.4.14
	PHP Version: 7.3.23
	PHP Memory Limit: 2048M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.1
	Site URL: https://virtuelekadoos.nl
	Home URL: https://virtuelekadoos.nl
	WP Multisite: No
	Max Upload Size: 500 MB
	Memory limit: 1024M
	Max Memory limit: 2048M
	Permalink Structure: /%postname%/
	Language: nl
	Timezone: 2
	Admin Email: bram.h@fullstak.nl
	Debug Mode: Inactive

== Theme ==
	Name: Virtuele Kadoos
	Version: 1.1.0
	Author: Fullstak
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.6.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: nl_NL
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36

== Active Plugins ==
	ActiveCampaign Postmark (Official)
		Version: 1.17.1
		Author: Andrew Yates & Matt Gibbs

	Advanced Custom Fields
		Version: 5.12.2
		Author: Delicious Brains

	Advanced Custom Fields PRO
		Version: 5.9.3
		Author: Elliot Condon

	Advanced Order Export For WooCommerce
		Version: 3.3.1
		Author: AlgolPlus

	Big File Uploads
		Version: 2.0.3
		Author: Infinite Uploads

	Complianz | GDPR/CCPA Cookie Consent
		Version: 6.2.4
		Author: Really Simple Plugins

	Elementor
		Version: 3.6.7
		Author: Elementor.com

	Elementor Pro
		Version: 3.6.5
		Author: Elementor.com

	Force Modules Wallet
		Version: 2.0.1
		Author: Force Modules

	Imsanity
		Version: 2.8.1
		Author: Exactly WWW

	JetBlocks For Elementor
		Version: 1.3.2
		Author: Crocoblock

	JetElements For Elementor
		Version: 2.6.6
		Author: Crocoblock

	JetEngine
		Version: 3.0.1
		Author: Crocoblock

	JetMenu
		Version: 2.1.7
		Author: Crocoblock

	JetPopup
		Version: 1.5.6
		Author: Crocoblock

	JetSearch
		Version: 3.0.0
		Author: Crocoblock

	JetSmartFilters
		Version: 2.3.12
		Author: Crocoblock

	JetTabs For Elementor
		Version: 2.1.17
		Author: Crocoblock

	JetTricks
		Version: 1.4.1
		Author: Crocoblock

	JetWooBuilder For Elementor
		Version: 1.12.4
		Author: Crocoblock

	Kadence WooCommerce Email Designer
		Version: 1.5.2
		Author: Kadence WP

	Loco Translate
		Version: 2.6.2
		Author: Tim Whitlock

	Mollie Payments for WooCommerce
		Version: 7.2.0
		Author: Mollie

	Really Simple SSL
		Version: 5.3.2
		Author: Really Simple Plugins

	Sendcloud | Smart Shipping Service
		Version: 2.2.5
		Author: Sendcloud B.V.

	Tawk.to Live Chat
		Version: 0.7.2
		Author: Tawkto

	Virtuele Kadoos Company
		Version: 1.0.2
		Author: Fullstak

	WooCommerce
		Version: 6.6.1
		Author: Automattic

	Wordfence Security
		Version: 7.5.11
		Author: Wordfence

	WP-Optimize - Clean, Compress, Cache
		Version: 3.2.6
		Author: David Anderson, Ruhani Rabin, Team Updraft

	Yoast Duplicate Post
		Version: 4.5
		Author: Enrico Battocchi & Team Yoast

	Yoast SEO
		Version: 19.3
		Author: Team Yoast

== Gebruik van elementen ==
	
	footer : 2
		form : 2
		heading : 6
		icon-list : 4
		text-editor : 2
	header : 2
		icon : 2
		icon-list : 2
		jet-ajax-search : 1
		jet-auth-links : 2
		jet-blocks-cart : 3
		jet-mega-menu : 2
		shortcode : 1
		theme-site-logo : 2
	page : 21
		animated-headline : 1
		button : 4
		form : 1
		heading : 10
		html : 7
		icon-list : 3
		jet-download-button : 2
		text-editor : 10
	wp-page : 17
		animated-headline : 1
		button : 12
		form : 1
		heading : 32
		html : 2
		icon-box : 8
		icon-list : 1
		image : 8
		jet-login : 1
		jet-lottie : 1
		jet-testimonials : 1
		jet-timeline : 1
		jet-video : 1
		lottie : 2
		shortcode : 1
		spacer : 14
		text-editor : 22
	single-page : 1
		button : 2
		heading : 3
		image : 1
		jet-login : 1
		jet-video : 1
		text-editor : 1
	jet-woo-builder-thankyou : 0
		heading : 1
		image : 1
		jet-thankyou-customer-address-details : 1
		jet-thankyou-order-details : 1
	jet-woo-builder-shop : 0
		html : 1
		jet-smart-filters-checkboxes : 1
		jet-smart-filters-pagination : 1
		jet-smart-filters-range : 1
		jet-smart-filters-search : 1
		jet-smart-filters-sorting : 1
		jet-woo-builder-products-description : 1
		jet-woo-builder-products-loop : 1
		jet-woo-builder-products-page-title : 1
		spacer : 1
	jet-woo-builder-myaccount : 0
		heading : 4
		image : 1
		jet-myaccount-account-details : 1
		jet-myaccount-addresses : 1
		jet-myaccount-dashboard : 1
		jet-myaccount-order : 1
	jet-woo-builder-checkout : 0
		heading : 1
		jet-checkout-additional-form : 1
		jet-checkout-billing : 1
		jet-checkout-order-review : 1
		jet-checkout-payment : 1
		jet-checkout-shipping-form : 1
	jet-woo-builder-cart : 0
		heading : 1
		jet-cart-table : 1
		jet-cart-totals : 1
	jet-woo-builder-archive : 0
		jet-woo-builder-archive-product-price : 1
		jet-woo-builder-archive-product-thumbnail : 1
		jet-woo-builder-archive-product-title : 2
		spacer : 1
	jet-woo-builder : 7
		image : 2
		jet-single-add-to-cart : 1
		jet-single-excerpt : 1
		jet-single-images : 1
		jet-single-price : 1
		jet-single-tabs : 2
		jet-single-title : 1
	error-404 : 1
		button : 1
		heading : 1
		text-editor : 1

== Elementor experimenten ==
	Geoptimaliseerde DOM-uitvoer: Actief
	Verbeterd laden van assets: Actief
	Verbeterd laden van CSS: Actief
	Pictogrammen inline lettertype: Standaard inactief
	Toegang verbeteringen: Actief
	Import export template kit: Standaard actief
	Extra aangepaste onderbrekingspunten: Standaard inactief
	Verberg verouderde WordPress widgets voor zoekresultaten: Standaard actief
	: Standaard inactief
	Flexbox container: Standaard inactief
	Default to New Theme Builder: Standaard actief
	Hello Theme header & footer: Standaard inactief
	Landingspagina's: Standaard actief
	Kleur sampler: Standaard actief
	Favoriete widgets: Standaard actief
	Beheerder bovenste balk: Standaard actief
	Page Transitions: Standaard actief
	Form Submissions: Actief
	Scroll Snap: Standaard actief

== Log ==
	
PHP: showing 6 of 6PHP: 2021-10-29 15:07:58 [error X 2][/home/kieskadoos/domains/virtuelekadoos.fullstak.nl/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::285] Uncaught Error: Call to a member function update_meta() on bool in /home/kieskadoos/domains/virtuelekadoos.fullstak.nl/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:285
Stack trace:
#0 /home/kieskadoos/domains/virtuelekadoos.fullstak.nl/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(166): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions()
#2 /home/kieskadoos/domains/virtuelekadoos.fullstak.nl/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func()
#3 /home/kieskadoos/domains/virtuelekadoos.fullstak.nl/public_html/wp-includes/class-wp-hook.php(303): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#4 /home/kieskadoos/domains/virtuelekadoos.fullstak.nl/public_html/wp-includes/class-wp-hook.php(327): W [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-10-29 18:25:02 [notice X 15][/home/kieskadoos/domains/virtuelekadoos.fullstak.nl/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-12-12 01:44:31 [notice X 17][/home/kieskadoos/domains/virtuelekadoos.fullstak.nl/public_html/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-url.php::34] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-04 13:49:27 [notice X 13254][/home/vkadoos/domains/virtuelekadoos.nl/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] Het argument $control_id is verouderd sinds versie 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-04 16:39:54 [notice X 5][/home/vkadoos/domains/virtuelekadoos.nl/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] Het argument $finder_category_name is verouderd sinds versie 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/vkadoos/domains/virtuelekadoos.nl/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /home/vkadoos/domains/virtuelekadoos.nl/public_html/wp-content/plugins/elementor/core/common/modules/finder/categories-manager.php(68): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home/vkadoos/domains/virtuelekadoos.nl/public_html/wp-content/plugins/elementor/core/common/modules/finder/categories-manager.php(50): Elementor\Core\Common\Modules\Finder\Categories_Manager -> register()
#4: /home/vkadoos/domains/virtuelekadoos.nl/public_html/wp-content/plugins/jet-popup/includes/elementor-finder/elementor-finder.php(47): Elementor\Core\Common\Modules\Finder\Categories_Manager -> add_category()
',
)]
PHP: 2022-07-10 18:36:23 [notice X 9][/home/vkadoos/domains/virtuelekadoos.nl/public_html/wp-content/plugins/elementor-pro/license/updater.php::84] Undefined index: new_version [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 20 of 342022-05-04 13:49:30 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.8',
  'to' => '3.6.5',
)]
2022-05-04 14:04:47 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.4.2',
  'to' => '3.6.5',
)]
2022-05-04 14:04:48 [info] elementor-pro::elementor_pro_updater Started 
2022-05-04 14:04:48 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-05-04 14:04:48 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-05-04 14:04:48 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Start  
2022-05-04 14:04:48 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Finished 
2022-05-04 14:04:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.4.2',
  'to' => '3.6.5',
)]
2022-05-04 14:04:50 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.4.2',
  'to' => '3.6.5',
)]
2022-07-01 16:18:12 [info] elementor::elementor_updater Started 
2022-07-01 16:18:12 [info] Elementor/Upgrades - _on_each_version Start  
2022-07-01 16:18:13 [info] Elementor/Upgrades - _on_each_version Finished 
2022-07-01 16:18:13 [info] Elementor/Upgrades - _v_3_5_0_remove_old_elementor_scheme Start  
2022-07-01 16:18:13 [info] Elementor/Upgrades - _v_3_5_0_remove_old_elementor_scheme Finished 
2022-07-01 16:18:13 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.5',
  'to' => '3.6.6',
)]
2022-07-12 12:30:17 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.6',
  'to' => '3.6.7',
)]
2022-07-12 12:30:18 [info] elementor::elementor_updater Started 
2022-07-12 12:30:18 [info] Elementor/Upgrades - _on_each_version Start  
2022-07-12 12:30:19 [info] Elementor/Upgrades - _on_each_version Finished 
2022-07-12 12:30:19 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.6',
  'to' => '3.6.7',
)]

JS: showing 2 of 2JS: 2022-05-04 15:27:15 [error X 1][https://virtuelekadoos.nl/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view12821\") has already been destroyed and cannot be used. 
JS: 2022-07-01 14:56:29 [error X 2][https://virtuelekadoos.nl/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.6:2:516092] Cannot read properties of null (reading \'getBoundingClientRect\') 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibiliteit niet gespecificeerd
	JetBlocks For Elementor: Compatibiliteit niet gespecificeerd
	JetElements For Elementor: Compatibiliteit niet gespecificeerd
	JetTabs For Elementor: Compatibiliteit niet gespecificeerd
	JetWooBuilder For Elementor: Compatibiliteit niet gespecificeerd

== Elementor Pro - Compatibility Tag ==

**Comment by bonbouaz** [comment]
same here

**Comment by breakerh** [comment]
Experienced similar issues today. Can't save when I set a condition..
Seems like the same problem just another manifestation..
If I can find the time I will try to see if i can fix it :)

**Comment by breakerh** [comment]
Any updates? We still can't save conditions in custom code...

**Comment by breakerh** [comment]
https://user-images.githubusercontent.com/2008632/193022044-514b8b1a-5260-4b56-ae2a-ef4a16c8a71c.mp4

**Comment by bonbouaz** [comment]
I am still stuck with this too, 
any help ?

**Comment by bonbouaz** [comment]
Just so you know, here is a workaround 
The condition bug is theme related
If you need to change your condition, you can set a different theme, make your changes on elementor on the new theme, and then roll back to the old theme, and that should work
Cheers
