### ISSUE TITLE
🐞 Bug report: basic gallery widget + flexbox experiment causing horizontal scroll bar

### ISSUE THREAD

**Issue by sean1138** [elementor/elementor#19340]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

flexbox experiment + basic gallery widget = horizontal scroll bar.

i have a workaround to get rid of the horizontal scrollbar, pretty easy but not sure if this is the way to fix it on the elementor dev side of things
https://youtu.be/ZjFkruLo6Wo

### Steps to reproduce

1, with flexbox experiment on, create a new page and then a 2 column container row
![image](https://user-images.githubusercontent.com/6720184/182588874-df1c92ed-d18d-4909-bc59-bbe9a1d76db0.png)

2, then throw in a basic gallery widget, add images, and set some custom spacing
![image](https://user-images.githubusercontent.com/6720184/182589086-f2ddf293-9e86-41f8-a91a-a4b4d99a3aa8.png)

3, view or preview your page and observe the horizontal scroll bar at the bottom of the browser that shouldn't be there
![image](https://user-images.githubusercontent.com/6720184/182589265-87192ce6-e5dc-497a-a82c-fdeb8b3ddf67.png)

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.38-41
	PHP Version: 7.4.30
	PHP Memory Limit: 768M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.1
	Site URL: http://jpbm126.sg-host.com
	Home URL: http://jpbm126.sg-host.com
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 40M
	Max Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/New_York
	Admin Email: jpbmarketing@hotmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36

== Active Plugins ==
	All-in-One WP Migration
		Version: 7.62
		Author: ServMask

	All-in-One WP Migration Unlimited Extension
		Version: 2.46
		Author: ServMask

	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Duplicate Page
		Version: 4.4.9
		Author: mndpsingh287

	Elementor
		Version: 3.6.8
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.3
		Author: Elementor.com

	Flip Book
		Version: 2.0
		Author: flipbuilder.com

== Must-Use Plugins ==
	InfiniteWP - Client Loader
		Version: 
		Author: Revmakx

== Elements Usage ==
	
	footer : 1
		container : 1
		heading : 1
	header : 1
		animated-headline : 1
		container : 9
		icon-box : 4
		icon-list : 1
		nav-menu : 2
		theme-site-logo : 1
	wp-page : 12
		animated-headline : 1
		call-to-action : 8
		container : 62
		form : 1
		heading : 35
		image : 4
		image-carousel : 1
		image-gallery : 3
		social-icons : 2
		tabs : 1
		text-editor : 26
	single-page : 1
		container : 1
		theme-post-content : 1

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Inactive
	Hide native WordPress widgets from search results: Active by default
	: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Inactive
	Hello Theme Header & Footer: Inactive
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 20 of 332022-06-27 09:35:50 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.5',
  'to' => '3.6.6',
)]
2022-07-22 05:51:39 [info] elementor::elementor_updater Started 
2022-07-22 05:51:39 [info] Elementor/Upgrades - _on_each_version Start  
2022-07-22 05:51:39 [info] Elementor/Upgrades - _on_each_version Finished 
2022-07-22 05:51:39 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.6',
  'to' => '3.6.7',
)]
2022-07-22 05:51:39 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.6',
  'to' => '3.6.7',
)]
2022-08-01 13:35:34 [info] elementor-pro::elementor_pro_updater Started 
2022-08-01 13:35:34 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-08-01 13:35:34 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-08-01 13:35:34 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.1',
  'to' => '3.7.2',
)]
2022-08-02 15:19:50 [info] elementor::elementor_updater Started 
2022-08-02 15:19:50 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-02 15:19:50 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-02 15:19:50 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.6.8',
)]
2022-08-02 15:19:50 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.6.8',
)]
2022-08-02 15:22:06 [info] elementor-pro::elementor_pro_updater Started 
2022-08-02 15:22:06 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-08-02 15:22:06 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-08-02 15:22:06 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.2',
  'to' => '3.7.3',
)]
2022-08-02 15:22:06 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.2',
  'to' => '3.7.3',
)]

PHP: showing 6 of 6PHP: 2022-05-03 20:13:33 [warning X 1][/home/customer/www/jpbm126.sg-host.com/public_html/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/icons/icon-sets/fontello.php::32] file_get_contents(/tmp/fontello-6aec0dac/fontello-6aec0dac/css/.css): failed to open stream: No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-04 11:24:31 [notice X 21][/home/customer/www/jpbm126.sg-host.com/public_html/wp-content/plugins/elementor/includes/managers/image.php::87] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-27 09:34:36 [error X 1][/home/customer/www/jpbm126.sg-host.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on null in /home/customer/www/jpbm126.sg-host.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /home/customer/www/jpbm126.sg-host.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(7, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/customer/www/jpbm126.sg-host.com/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/customer/www/jpbm126.sg-host.com/public_html/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/customer/www/jpbm1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-27 10:30:07 [error X 1][/home/customer/www/jpbm126.sg-host.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on bool in /home/customer/www/jpbm126.sg-host.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /home/customer/www/jpbm126.sg-host.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/customer/www/jpbm126.sg-host.com/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/customer/www/jpbm126.sg-host.com/public_html/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/customer/www/jp [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-27 20:19:32 [error X 1][/home/customer/www/jpbm126.sg-host.com/public_html/wp-content/plugins/elementor/core/wp-api.php::26] Uncaught Error: Call to undefined function Elementor\Core\get_plugins() in /home/customer/www/jpbm126.sg-host.com/public_html/wp-content/plugins/elementor/core/wp-api.php:26
Stack trace:
#0 /home/customer/www/jpbm126.sg-host.com/public_html/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(96): Elementor\Core\Wp_Api->get_plugins()
#1 /home/customer/www/jpbm126.sg-host.com/public_html/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(58): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_with_header()
#2 /home/customer/www/jpbm126.sg-host.com/public_html/wp-content/plugins/elementor/modules/compatibility-tag/module.php(57): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_to_check()
#3 /home/customer/www/jpbm126.sg-host.com/public_html/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(148): Elementor\Modules\CompatibilityTag\Module->get_plugins_to_check()
#4 /home/customer/www/jpbm126.sg-host.com/public_html/wp-includes/class-w [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-02 15:20:10 [notice X 7][/home/customer/www/jpbm126.sg-host.com/public_html/wp-content/plugins/elementor-pro/license/admin.php::221] Undefined index: license [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 3 of 3JS: 2022-05-04 17:50:55 [error X 1513][http://jpbm126.sg-host.com/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:16820] Cannot read properties of null (reading \'clone\') 
JS: 2022-05-04 17:50:56 [error X 47][http://jpbm126.sg-host.com/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:21012] Cannot read properties of null (reading \'changestop\') 
JS: 2022-05-04 19:17:40 [error X 148][http://jpbm126.sg-host.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.5:2:391141] Cannot read properties of undefined (reading \'parent\') 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

**Comment by 79ho3ein** [comment]
hi @sean1138 
In version 3.7, the horizontal scrolling problem in the editor has been completely fixed. I haven't tested this, but I don't think there is a problem.
