### ISSUE TITLE
🐞 Bug report: 

### ISSUE THREAD

**Issue by andriussok** [elementor/elementor#19444]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Elementor doesn't handle big-image uploads properly.

### Steps to reproduce

Open to edit page with Elementor;
When uploading big-image (10818 × 5233, 20MB) file in media uploads, wp properly generates [scaled](https://developer.wordpress.org/reference/hooks/big_image_size_threshold/) image;
When trying drag-drop (from computer to elementor editor) same big-image (different name) it throws this error in log files:
```
PHP Notice:  Undefined index: id in /wp-content/plugins/elementor/includes/managers/image.php on line 36
PHP Notice:  Trying to access array offset on value of type bool in /wp-content/plugins/elementor/includes/managers/image.php on line 105
```
Image stays as a grey placeholder.
Sometimes it shows "Uploading...." or "Unexpected end of JSON input" toast popup.
Sometimes wp scales image, most of the time it creates just unscaled original.

This happens without the hook described below.

I'm not uploading images that way, trying to restrict content managers to use insanely big-images as they do it sometimes.
So this hook works fine for general media uploads:
```
function plugin_prefix_max_image_size( $file ) {
  $limit    = 2000; // kb
  $size     = $file['size'] / 1024;
  $is_image = strpos( $file['type'], 'image' ) !== false;
  if ( $is_image && $size > $limit ) {
    $file['error'] = "Image files must be smaller than {$limit}kb";
  }
  return $file;
}
add_filter( 'wp_handle_upload_prefilter', 'plugin_prefix_max_image_size' );
```
However this hook doesn't work properly with Elementor drag and drop function as error occurs on direct upload. 
Any suggestions ?

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Darwin
	Software: Apache/2.4.46 (Unix) OpenSSL/1.0.2u PHP/7.4.21 mod_wsgi/3.5 Python/2.7.13 mod_fastcgi/mod_fastcgi-SNAP-0910052141 mod_perl/2.0.11 Perl/v5.30.1
	MySQL version: MySQL Community Server (GPL) v5.7.34
	PHP Version: 7.4.21
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.1
	Site URL: https://sandbox.test
	Home URL: https://sandbox.test
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: andrius@gloss.agency
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.6.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.7.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.3
		Author: Elementor.com

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Inactive by default
	Import Export Template Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Inactive by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 20 of 352022-06-21 18:04:03 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Start  
2022-06-21 18:04:03 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Finished 
2022-06-21 18:04:03 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.5',
  'to' => '3.7.2',
)]
2022-06-21 18:04:03 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.5',
  'to' => '3.7.2',
)]
2022-07-04 08:37:22 [info] elementor::elementor_updater Started 
2022-07-04 08:37:22 [info] Elementor/Upgrades - _on_each_version Start  
2022-07-04 08:37:22 [info] Elementor/Upgrades - _on_each_version Finished 
2022-07-04 08:37:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.6',
  'to' => '3.6.7',
)]
2022-07-04 08:37:22 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.6',
  'to' => '3.6.7',
)]
2022-08-08 14:04:03 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.7.0',
)]
2022-08-08 14:04:04 [info] elementor::elementor_updater Started 
2022-08-08 14:04:04 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-08 14:04:04 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-08 14:04:04 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.7.0',
)]
2022-08-08 14:12:59 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.2',
  'to' => '3.7.3',
)]
2022-08-08 14:13:00 [info] elementor-pro::elementor_pro_updater Started 
2022-08-08 14:13:00 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-08-08 14:13:00 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-08-08 14:13:00 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.2',
  'to' => '3.7.3',
)]
2022-08-08 14:13:02 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.2',
  'to' => '3.7.3',
)]

PHP: showing 4 of 4PHP: 2022-05-03 12:08:16 [notice X 5][/Users/andrius/Sites/sandbox/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-01 15:58:29 [notice X 13][/Users/andrius/Sites/sandbox/wp-content/plugins/elementor/includes/managers/image.php::87] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-11 14:21:02 [error X 2][/Users/andrius/Sites/sandbox/wp-content/plugins/elementor/includes/base/controls-stack.php::2367] Uncaught TypeError: Argument 1 passed to Elementor\Controls_Stack::sanitize_settings() must be of the type array, null given, called in /Users/andrius/Sites/sandbox/wp-content/plugins/elementor/includes/base/controls-stack.php on line 1105 and defined in /Users/andrius/Sites/sandbox/wp-content/plugins/elementor/includes/base/controls-stack.php:2367
Stack trace:
#0 /Users/andrius/Sites/sandbox/wp-content/plugins/elementor/includes/base/controls-stack.php(1105): Elementor\Controls_Stack->sanitize_settings(NULL)
#1 /Users/andrius/Sites/sandbox/wp-content/plugins/custom-data-fields/dynamic-tags/cdf-dynamic-tag.php(115): Elementor\Controls_Stack->get_data()
#2 /Users/andrius/Sites/sandbox/wp-content/plugins/elementor/core/dynamic-tags/base-tag.php(179): Elementor_Dynamic_Tag_CDF_Field->register_controls()
#3 /Users/andrius/Sites/sandbox/wp-content/plugins/elementor/includes/base/controls-stack.php(494): Elementor\Core\DynamicTags\Base_Tag->init_controls()
#4 /Users/andrius/Sites/sandbox/wp-content/plugins/elemento [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-08 09:21:13 [error X 1][/Users/andrius/Sites/sandbox/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Allowed memory size of 134217728 bytes exhausted (tried to allocate 13711592 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 3 of 3JS: 2022-07-11 11:24:27 [error X 1][https://sandbox.test/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view2585\") has already been destroyed and cannot be used. 
JS: 2022-07-11 11:24:32 [error X 1][https://sandbox.test/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view2612\") has already been destroyed and cannot be used. 
JS: 2022-08-12 09:20:52 [error X 2][https://sandbox.test/wp-content/plugins/elementor/assets/js/editor-document.min.js?ver=3.7.0:2:25976] elementorDevTools is not defined 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

**Comment by rami-elementor** [comment]
@andriussok update issue title
