### ISSUE TITLE
🐞 Bug report: 

### ISSUE THREAD

**Issue by AdvartTechnologies** [elementor/elementor#19522]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

demo.beelittle.in is our staging site. We are continually receiving duplicate admin ajax requests for a single click of add to cart, remove item from cart. We first reported this issue to your support team, they tried resolving it and asked us to raise an issue here.
![elementor menu cart fragments](https://user-images.githubusercontent.com/111477263/185284960-a17e6a8d-e17c-489c-9b7d-68ea4db49d31.PNG) We are seeing this ajax requests as many as 7-21 duplicates for a single click of a add to cart.

Kindly help us resolve this, as its increasing the unnecessary load on the server and slowing down the add to cart functionality speed on our website. WIhour elementor, we are seeing about <1.5sec to add product to cart, with elementor and many ajax requests, its about >4.5sec to add product to cart and same for removing from cart.

### Steps to reproduce

1. Open demo.beelittle.in
2. Open developer console and filter ajax requests - under network tab
3. click add to cart 
4. You will notice duplicates of elementor menu cart fragments

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.51 (Debian)
	MySQL version: mariadb.org binary distribution v10.4.20
	PHP Version: 7.4.30
	PHP Memory Limit: 256M
	PHP Max Input Vars: 6000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.1
	Site URL: https://dev.beelittle.in
	Home URL: https://dev.beelittle.in
	WP Multisite: No
	Max Upload Size: 100 MB
	Memory limit: 2048M
	Max Memory limit: 2048M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Asia/Kolkata
	Admin Email: info@beelittle.in
	Debug Mode: Inactive

== Theme ==
	Name: BeeLittle
	Version: 1.0.0
	Author: Brainstorm Force
	Child Theme: Yes
	Parent Theme Name: Astra
	Parent Theme Version: 3.9.1
	Parent Theme Author: Brainstorm Force

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36

== Active Plugins ==
	Acowebs Product Labels For Woocommerce
		Version: 1.2.8
		Author: Acowebs

	Advance Ecommerce Tracking Premium
		Version: 3.6.4
		Author: theDotstore

	Astra Pro
		Version: 3.6.7
		Author: Brainstorm Force

	CartBounty - Save and recover abandoned carts for WooCommerce
		Version: 7.1.2.6
		Author: Streamline.lv

	Elementor
		Version: 3.6.8
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.2
		Author: Elementor.com

	Engage Abandon Custom REST API
		Version: 1.0.0
		Author: Shiprocket

	Essential Addons for Elementor
		Version: 5.1.8
		Author: WPDeveloper

	FiboSearch - AJAX Search for WooCommerce (Pro)
		Version: 1.18.0
		Author: FiboSearch Team

	File Manager Advanced
		Version: 4.1.5
		Author: modalweb

	Flexible Shipping
		Version: 4.13.2
		Author: Octolize

	Gift Wrapper
		Version: 5.2.1
		Author: Sagehen Studio

	Health Check &amp; Troubleshooting
		Version: 1.4.5
		Author: The WordPress.org community

	Jetpack
		Version: 11.1.2
		Author: Automattic

	Klaviyo
		Version: 3.0.3
		Author: Klaviyo, Inc.

	MalCare Security - Free Malware Scanner, Protection &amp; Security for WordPress
		Version: 4.67
		Author: MalCare Security

	Media Cloud (Premium)
		Version: 4.4.0
		Author: interfacelab

	Open Graph and Twitter Card Tags
		Version: 3.2.0
		Author: PT Woo Plugins (by Webdados)

	PixelYourSite
		Version: 9.1.1
		Author: PixelYourSite

	Razorpay for WooCommerce
		Version: 4.0.0
		Author: Team Razorpay

	Schema &amp; Structured Data for WP &amp; AMP
		Version: 1.9.99
		Author: Magazine3

	Sendinblue - WooCommerce Email Marketing
		Version: 2.0.38
		Author: Sendinblue

	Shiprocket
		Version: 1.0.7
		Author: Shiprocket

	Show Single Variations Shop &amp; Category for WooCommerce
		Version: 2.0
		Author: Gravity Master

	Site Kit by Google
		Version: 1.79.1
		Author: Google

	Smart Manager - WooCommerce Inventory Management, Advanced Bulk Edit &amp; more...
		Version: 6.4.0
		Author: StoreApps

	Store Toolkit for WooCommerce
		Version: 2.3.7
		Author: Visser Labs

	Ultimate Gift Cards For WooCommerce
		Version: 2.4.3
		Author: WP Swings

	WooCommerce
		Version: 6.7.0
		Author: Automattic

	WooCommerce Advanced Bulk Edit
		Version: 4.6
		Author: George Iron

	WooCommerce Product Filter by WooBeWoo
		Version: 2.0.1
		Author: WooBeWoo

	WooCommerce Product Recommendations
		Version: 1.4.7
		Author: SomewhereWarm

	WP Bulk Delete
		Version: 1.2.2
		Author: Xylus Themes

	WPS Hide Login
		Version: 1.9.6
		Author: WPServeur, NicolasKulka, wpformation

	YITH WooCommerce Wishlist
		Version: 3.11.0
		Author: YITH

	Yoast SEO
		Version: 19.4
		Author: Team Yoast

== Must-Use Plugins ==
	Health Check Troubleshooting Mode
		Version: 1.7.2
		Author: 

	Object Cache Pro (MU)
		Version: 1.15.2
		Author: Rhubarb Group

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Inactive by default
	Hide native WordPress widgets from search results: Active by default
	: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 20 of 322022-04-13 19:48:06 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.4',
  'to' => '3.6.3',
)]
2022-04-27 12:26:34 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.5.2',
  'to' => '3.6.5',
)]
2022-04-27 12:26:34 [info] elementor-pro::elementor_pro_updater Started 
2022-04-27 12:26:34 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-04-27 12:26:34 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-04-27 12:26:34 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.5.2',
  'to' => '3.6.5',
)]
2022-04-27 12:26:35 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.5.2',
  'to' => '3.6.5',
)]
2022-04-27 13:14:23 [info] elementor::elementor_updater Started 
2022-04-27 13:14:23 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-27 13:14:23 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-27 13:14:23 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.3',
  'to' => '3.6.4',
)]
2022-07-28 13:05:25 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.4',
  'to' => '3.6.8',
)]
2022-07-28 13:05:26 [info] elementor::elementor_updater Started 
2022-07-28 13:05:26 [info] Elementor/Upgrades - _on_each_version Start  
2022-07-28 13:05:26 [info] Elementor/Upgrades - _on_each_version Finished 
2022-07-28 13:05:26 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.4',
  'to' => '3.6.8',
)]
2022-07-28 13:35:04 [info] elementor-pro::elementor_pro_updater Started 
2022-07-28 13:35:04 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-07-28 13:35:04 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-07-28 13:35:04 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.5',
  'to' => '3.7.2',
)]

PHP: showing 10 of 10PHP: 2022-01-27 16:07:13 [error X 1][/home/667530.cloudwaysapps.com/aphesxtksj/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::286] Uncaught Error: Call to a member function update_meta() on null in /home/667530.cloudwaysapps.com/aphesxtksj/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:286
Stack trace:
#0 /home/667530.cloudwaysapps.com/aphesxtksj/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;save_conditions(286, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/667530.cloudwaysapps.com/aphesxtksj/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/667530.cloudwaysapps.com/aphesxtksj/public_html/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module-&gt;handle_ajax_request(&#039;&#039;)
#4 /home/6675 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-30 07:48:24 [notice X 38][/home/667530.cloudwaysapps.com/aphesxtksj/public_html/wp-content/plugins/elementor-pro/modules/forms/classes/form-record.php::179] Undefined index: referrer [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-14 00:21:29 [notice X 124][/home/667530.cloudwaysapps.com/aphesxtksj/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-14 14:08:20 [notice X 19][/home/667530.cloudwaysapps.com/aphesxtksj/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/667530.cloudwaysapps.com/aphesxtksj/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /home/667530.cloudwaysapps.com/aphesxtksj/public_html/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home/667530.cloudwaysapps.com/aphesxtksj/public_html/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home/667530.cloudwaysapps.com/aphesxtksj/public_html/wp-content/plugins/elementor-pro/modules/query-control/module.php(826): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-04-14 14:08:20 [notice X 19][/home/667530.cloudwaysapps.com/aphesxtksj/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/667530.cloudwaysapps.com/aphesxtksj/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /home/667530.cloudwaysapps.com/aphesxtksj/public_html/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home/667530.cloudwaysapps.com/aphesxtksj/public_html/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home/667530.cloudwaysapps.com/aphesxtksj/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/module.php(162): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-04-14 14:08:20 [notice X 19][/home/667530.cloudwaysapps.com/aphesxtksj/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/667530.cloudwaysapps.com/aphesxtksj/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /home/667530.cloudwaysapps.com/aphesxtksj/public_html/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home/667530.cloudwaysapps.com/aphesxtksj/public_html/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home/667530.cloudwaysapps.com/aphesxtksj/public_html/wp-content/plugins/elementor-pro/modules/forms/module.php(74): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-04-14 14:08:20 [notice X 19][/home/667530.cloudwaysapps.com/aphesxtksj/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/667530.cloudwaysapps.com/aphesxtksj/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /home/667530.cloudwaysapps.com/aphesxtksj/public_html/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home/667530.cloudwaysapps.com/aphesxtksj/public_html/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home/667530.cloudwaysapps.com/aphesxtksj/public_html/wp-content/plugins/elementor-pro/modules/forms/module.php(75): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-04-15 16:09:11 [notice X 1][/home/667530.cloudwaysapps.com/aphesxtksj/public_html/wp-content/plugins/elementor-pro/modules/query-control/module.php::740] Trying to get property &#039;name&#039; of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-24 19:22:44 [notice X 3][/home/667530.cloudwaysapps.com/aphesxtksj/public_html/wp-content/plugins/elementor-pro/license/updater.php::84] Undefined index: new_version [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-18 08:50:40 [notice X 1][/home/797295.cloudwaysapps.com/aphesxtksj/public_html/wp-content/plugins/elementor/core/experiments/experiments-reporter.php::89] Undefined index: title [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 1 of 1JS: 2022-06-15 11:42:20 [error X 1][https://beelittle.in/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:9:30216] Option \&#039;ajax\&#039; is not allowed for Select2 when attached to a element. 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	Essential Addons for Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==
	

[system-info-dev.beelittle.in-18-08-2022.txt](https://github.com/elementor/elementor/files/9367387/system-info-dev.beelittle.in-18-08-2022.txt)

**Comment by AdvartTechnologies** [comment]
@rami-elementor we were building another elementor website. It also has same menu-cart-fragments admin ajax duplicate events. Were you able to identify the issue?

**Comment by ramonfincken** [comment]
![elementor_menu](https://github.com/user-attachments/assets/f1ea6aff-210c-42c8-aceb-5b52d4e35874)

Still present
