### ISSUE TITLE
✅ 🐞 Bug report: Global widget console error

### ISSUE THREAD

**Issue by sarailoo** [elementor/elementor#19617]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

After saving a widget as a global in editor, we can't right click on the widget and it shows a console error.

common-modules.js?ver=3.7.2:2137 Uncaught Error: Model.isValidChild() should be implemented, please provide 'isValidChild' functionality.

### Steps to reproduce

1. Open a new page
2. Edit with elementor
3. Drag & drop a widget
4. Right click on the widget
5. Click save as a global and choose a name and save it
6. Now try to right click on the widget on editor

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

<details>
<summary>Click to reveal</summary>

````txt

== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.53 (Debian)
	MySQL version: Source distribution v10.3.34
	PHP Version: 7.4.29
	PHP Memory Limit: 500M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 500M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.1
	Site URL: http://localhost:8055
	Home URL: http://localhost:8055
	WP Multisite: No
	Max Upload Size: 500 MB
	Memory limit: 40M
	Max Memory limit: 500M
	Permalink Structure: Plain
	Language: en-US
	Timezone: 0
	Debug Mode: Active

== Theme ==
	Name: JupiterX
	Version: 2.1.0
	Author: Artbees
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 5.12.3
		Author: Delicious Brains

	Debug
		Version: 1.10
		Author: SoniNow Team

	Easy Updates Manager
		Version: 9.0.13
		Author: Easy Updates Manager Team

	Elementor
		Version: 3.7.2
		Author: Elementor.com

	JetPopup
		Version: 1.5.6
		Author: Crocoblock

	Jupiter X Core
		Version: 2.5.0
		Author: Artbees

	Sellkit
		Version: 1.2.9
		Author: Artbees

	Sellkit Pro
		Version: 1.2.7
		Author: Artbees

	WooCommerce
		Version: 6.6.1
		Author: Automattic

	WP Rollback
		Version: 1.7.1
		Author: GiveWP.com


== Elements Usage ==
	
	header : 1
		heading : 1
		raven-heading : 1
		raven-photo-album : 1
	page : 3
		button : 1
		counter : 1
		google_maps : 1
		heading : 1
		icon : 1
		raven-alert : 2
		raven-breadcrumbs : 2
		raven-button : 2
		raven-categories : 1
		raven-countdown : 1
		raven-counter : 1
		raven-divider : 1
		raven-flex-spacer : 2
		raven-form : 1
		raven-heading : 1
		raven-icon : 2
		raven-image : 1
		raven-login : 1
		raven-nav-menu : 2
		raven-photo-album : 1
		raven-photo-roller : 1
		raven-post-comments : 2
		raven-post-meta : 1
		raven-posts : 1
		raven-posts-carousel : 1
		raven-price-list : 1
		raven-register : 2
		raven-reset-password : 1
		raven-search-form : 1
		raven-shopping-cart : 2
		raven-site-logo : 2
		raven-social-login : 1
		raven-tabs : 1
		raven-video : 1
		raven-wc-products : 2
		sellkit-order-details : 1
		sellkit-personalised-coupons : 1
		sellkit-product-filter : 2
	popup : 0
		heading : 1
	widget : 0
		heading : 11
		raven-button : 1
		raven-heading : 1
	wp-post : 2
		heading : 1
		raven-product-data-tabs : 1
		raven-product-rating : 1
		text-editor : 1
	wp-page : 23
		button : 2
		counter : 2
		heading : 7
		icon : 2
		raven-alert : 2
		raven-animated-heading : 1
		raven-breadcrumbs : 2
		raven-button : 6
		raven-categories : 2
		raven-countdown : 2
		raven-counter : 2
		raven-divider : 2
		raven-flex-spacer : 2
		raven-form : 2
		raven-heading : 3
		raven-icon : 2
		raven-image : 2
		raven-login : 2
		raven-media-carousel : 1
		raven-nav-menu : 2
		raven-photo-album : 2
		raven-photo-roller : 2
		raven-post-comments : 2
		raven-post-meta : 2
		raven-posts : 2
		raven-posts-carousel : 2
		raven-price-list : 2
		raven-register : 2
		raven-reset-password : 2
		raven-search-form : 2
		raven-shopping-cart : 2
		raven-site-logo : 2
		raven-social-login : 2
		raven-tabs : 2
		raven-video : 2
		raven-wc-products : 2
		sellkit-personalised-coupons : 2
	jupiterx-popups : 15
		heading : 1
	jet-popup : 1
		heading : 1


== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Import Export Template Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default


== Log ==
	
PHP: showing 20 of 20PHP: 2022-07-14 17:29:50 [warning X 1][../elementor/includes/db.php::267] Invalid argument supplied for foreach() [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-14 18:41:08 [notice X 1][../elementor/includes/template-library/sources/local.php::1370] Undefined index: content [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-14 18:42:37 [notice X 4][../elementor/includes/template-library/sources/local.php::1396] Undefined index: type [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-18 09:20:00 [notice X 5][../elementor/core/app/modules/import-export/module.php::90] Trying to get property &#039;label&#039; of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-29 00:19:26 [notice X 2][../elementor-pro/license/updater.php::83] Undefined index: new_version [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-29 00:19:31 [error X 3][../elementor-pro2/elementor-pro.php::75] Cannot redeclare elementor_pro_load_plugin() (previously declared in ../elementor-pro/elementor-pro.php:61) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-29 08:30:16 [error X 10][../elementor/includes/base/controls-stack.php::377] Uncaught ArgumentCountError: Too few arguments to function Elementor\Controls_Stack::add_control(), 0 passed in ../jupiterx-core/includes/extensions/raven/includes/core/document-types/types/popup.php on line 422 and at least 2 expected in ../elementor/includes/base/controls-stack.php:377
Stack trace:
#0 ../jupiterx-core/includes/extensions/raven/includes/core/document-types/types/popup.php(422): Elementor\Controls_Stack-&gt;add_control()
#1 ../elementor/includes/base/controls-stack.php(2282): JupiterX_Core\Raven\Core\Document_Types\Type\Jupiterx_Popup_Document-&gt;register_controls()
#2 ../elementor/includes/base/controls-stack.php(494): Elementor\Controls_Stack-&gt;init_controls()
#3 ../elementor/includes/base/controls-stack.php(300): Elementor\Controls_Stack-&gt;get_stack()
#4 ../elementor/core/settings/page/mode [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-29 14:53:07 [notice X 9][../elementor/includes/controls/base-multiple.php::87] Undefined index: size [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-01 15:43:58 [warning X 1][../elementor-pro/plugin-update-checker/Puc/v4p6/UpdateChecker.php::400] The URL ../json/elementorpro-321.json?installed_version=3.7.0&amp;php=7.4.29&amp;locale=en_US&amp;checking_for_updates=1 does not point to a valid metadata file. WP HTTP Error: cURL error 28: Operation timed out after 10000 milliseconds with 0 out of 0 bytes received [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-04 21:55:04 [error X 2][../elementor-pro/modules/posts/widgets/posts.php::47] syntax error, unexpected &#039;$this&#039; (T_VARIABLE) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-15 04:56:25 [notice X 2656][../elementor-pro/license/api.php::362] Undefined index: license [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-15 05:19:07 [error X 1][../elementor-pro/modules/theme-builder/classes/conditions-manager.php::140] Uncaught Error: Call to a member function get_edit_url() on bool in ../elementor-pro/modules/theme-builder/classes/conditions-manager.php:140
Stack trace:
#0 ../elementor-pro/modules/theme-builder/classes/conditions-manager.php(160): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;get_conditions_conflicts_by_location(&#039;include/general&#039;, &#039;header&#039;, 589)
#1 ../elementor-pro/modules/theme-builder/classes/conditions-manager.php(104): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;get_conditions_conflicts(589, &#039;include/general&#039;)
#2 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;ajax_check_conditions_conflicts(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 ../elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#4 ../wp-includes/clas [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-15 05:55:33 [notice X 2][../elementor-pro/license/api.php::362] Undefined index: license [array (
  'trace' => '
#0: ../elementor-pro/license/api.php(362): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ../elementor-pro/license/notices/trial-period-notice.php(23): ElementorPro\License\API :: is_license_active()
#2: ../elementor/core/admin/admin-notices.php(647): ElementorPro\License\Notices\Trial_Period_Notice -> should_print()
#3: ../wp-includes/class-wp-hook.php(307): Elementor\Core\Admin\Admin_Notices -> admin_notices()
#4: ../wp-includes/class-wp-hook.php(331): WP_Hook -> apply_filters()
',
)]
PHP: 2022-08-15 05:55:33 [notice X 2][../elementor-pro/license/api.php::368] Undefined index: license [array (
  'trace' => '
#0: ../elementor-pro/license/api.php(368): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ../elementor-pro/license/notices/trial-expired-notice.php(22): ElementorPro\License\API :: is_license_expired()
#2: ../elementor/core/admin/admin-notices.php(647): ElementorPro\License\Notices\Trial_Expired_Notice -> should_print()
#3: ../wp-includes/class-wp-hook.php(307): Elementor\Core\Admin\Admin_Notices -> admin_notices()
#4: ../wp-includes/class-wp-hook.php(331): WP_Hook -> apply_filters()
',
)]
PHP: 2022-08-15 06:16:46 [error X 1][../elementor-pro/modules/theme-builder/classes/conditions-manager.php::140] Uncaught Error: Call to a member function get_edit_url() on bool in ../elementor-pro/modules/theme-builder/classes/conditions-manager.php:140
Stack trace:
#0 ../elementor-pro/modules/theme-builder/classes/conditions-manager.php(160): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;get_conditions_conflicts_by_location(&#039;include/general&#039;, &#039;header&#039;, 615)
#1 ../elementor-pro/modules/theme-builder/classes/conditions-manager.php(104): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;get_conditions_conflicts(615, &#039;include/general&#039;)
#2 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;ajax_check_conditions_conflicts(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 ../elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#4 ../wp-includes/clas [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-15 09:31:09 [notice X 2][../elementor-pro/license/api.php::362] Undefined index: license [array (
  'trace' => '
#0: ../elementor-pro/license/api.php(362): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ../elementor-pro/license/notices/trial-period-notice.php(23): ElementorPro\License\API :: is_license_active()
#2: ../elementor/core/admin/admin-notices.php(604): ElementorPro\License\Notices\Trial_Period_Notice -> should_print()
#3: ../wp-includes/class-wp-hook.php(307): Elementor\Core\Admin\Admin_Notices -> admin_notices()
#4: ../wp-includes/class-wp-hook.php(331): WP_Hook -> apply_filters()
',
)]
PHP: 2022-08-15 09:31:09 [notice X 2][../elementor-pro/license/api.php::368] Undefined index: license [array (
  'trace' => '
#0: ../elementor-pro/license/api.php(368): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ../elementor-pro/license/notices/trial-expired-notice.php(22): ElementorPro\License\API :: is_license_expired()
#2: ../elementor/core/admin/admin-notices.php(604): ElementorPro\License\Notices\Trial_Expired_Notice -> should_print()
#3: ../wp-includes/class-wp-hook.php(307): Elementor\Core\Admin\Admin_Notices -> admin_notices()
#4: ../wp-includes/class-wp-hook.php(331): WP_Hook -> apply_filters()
',
)]
PHP: 2022-08-15 09:41:59 [notice X 1][../elementor/core/common/modules/connect/module.php::230] Trying to get property &#039;email&#039; of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-23 07:13:34 [notice X 439][../elementor/core/base/document.php::250] Trying to get property &#039;ID&#039; of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-24 04:56:45 [notice X 4][../elementor/core/files/css/base.php::456] Array to string conversion [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 12 of 122022-08-12 12:27:27 [info] elementor::elementor_updater Started 
2022-08-12 12:27:27 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-12 12:27:27 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-12 12:27:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.6',
  'to' => '3.7.0',
)]
2022-08-12 14:12:26 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.0',
  'to' => '3.7.3',
)]
2022-08-15 05:12:31 [info] elementor-pro::elementor_pro_updater Started 
2022-08-15 05:12:31 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-08-15 05:12:31 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-08-15 05:12:31 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Start  
2022-08-15 05:12:31 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.0',
  'to' => '3.7.3',
)]
2022-08-15 05:12:31 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.0',
  'to' => '3.7.3',
)]
2022-08-15 18:15:07 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.0',
  'to' => '3.7.1',
)]

JS: showing 10 of 10JS: 2022-08-12 13:37:59 [error X 144][../elementor/assets/js/editor-document.min.js?ver=3.7.0:2:25976] elementorDevTools is not defined 
JS: 2022-08-12 19:08:09 [error X 15][../elementor/assets/js/common-modules.min.js?ver=3.7.0:2:51477] n.isValidChild() should be implemented, please provide \&#039;isValidChild\&#039; functionality. 
JS: 2022-08-12 19:27:18 [error X 9][../elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:17421] Could not find template: \&quot;#tmpl-raven-panel-global-widget-no-templates\&quot; 
JS: 2022-08-15 08:10:02 [error X 12][../elementor/assets/js/editor.min.js?ver=3.7.0:3:766552] Cannot read properties of undefined (reading \&#039;localized\&#039;) 
JS: 2022-08-16 05:19:05 [error X 49][../elementor/assets/js/common-modules.min.js?ver=3.7.1:2:51477] Model.isValidChild() should be implemented, please provide \&#039;isValidChild\&#039; functionality. 
JS: 2022-08-18 10:44:03 [error X 1][../jupiterx-core-media/includes/extensions/raven/assets/js/editor.js?ver=6.0.1:2099:77] window.jupiterxOptions.activeElements.getValue is not a function 
JS: 2022-08-23 04:05:05 [error X 15][../elementor/assets/js/editor.min.js?ver=3.7.1:3:766783] Cannot read properties of undefined (reading \&#039;toLowerCase\&#039;) 
JS: 2022-08-23 09:12:43 [error X 1][../jupiterx-core-media/includes/extensions/raven/assets/js/frontend.min.js?ver=6.0.1:1:189965] gapi is not defined 
JS: 2022-08-25 08:51:12 [error X 1][../elementor/assets/js/frontend.js?ver=3.6.8:1346:60] Cannot read properties of undefined (reading \&#039;top\&#039;) 
JS: 2022-08-26 06:38:42 [error X 2][../jupiterx-core-media/includes/extensions/raven/assets/js/frontend.js?ver=6.0.1:1042:23] window.jupiterxPopup is not a function 



== Elementor - Compatibility Tag ==

````

</details>

**Comment by rf-999** [comment]
Short conclusion: Currently it is not possible to...

- get the context menu of a Global Widget by right clicking it
- Delete a Global Widget directly (you have to unlink it from Global first, then delete it)
- Move / Drag and Drop a Global Widget (you have unlink it, delete it, then insert it at the desired place)

As a content administrator, this bug is a big hassle. 

Hope you can solve it soon.

**Comment by Mal027** [comment]
This has been happening as well for me. In addition to that, if I paste a style on anything on a page, I am unable to save a draft or publish the page. I have to copy the section, duplicate the page, and then re-add that section with the updated style.

Quite unfortunate to deal with.

**Comment by AmyrAhmady** [comment]
Any news on this?

**Comment by nicholaszein** [comment]
Hi everyone,

it's been a while since this issue was raised, and a lot has changed. While testing what was reported here using the most recent versions of Elementor and Elementor Pro (v3.29.0), this issue is no longer reproducible. All functionalities are working as intended.

https://github.com/user-attachments/assets/211bfb15-e11f-4deb-ac00-0ab18e162c4a

For this reason I'm closing this issue.

If you think this is still an issue caused by Elementor after following the troubleshooting steps above, feel free to open a new 🐞 [Bug Report](https://elemn.to/gh-new-bug-report).

Kind regards
