### ISSUE TITLE
elementorModules.frontend.tools is undefined when creating a JS Handler for a Custom widget

### ISSUE THREAD

**Issue by MarleyPlant** [elementor/elementor#19709]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When creating a JS Handler for a custom widget I am receiving the following error in the web browser.

```
Uncaught TypeError: Cannot read properties of undefined (reading 'tools')
    at Frontend.initOnReadyComponents (frontend.min.js?ver=3.7.4:formatted:308)
    at Frontend.init (frontend.min.js?ver=3.7.4:formatted:409)
    at HTMLDocument.<anonymous> (frontend.min.js?ver=3.7.4:formatted:418)
    at e (jquery.min.js?ver=3.6.0:formatted:1423)
    at t (jquery.min.js?ver=3.6.0:formatted:1434)
initOnReadyComponents @ frontend.min.js?ver=3.7.4:formatted:308
init @ frontend.min.js?ver=3.7.4:formatted:409
(anonymous) @ frontend.min.js?ver=3.7.4:formatted:418
e @ jquery.min.js?ver=3.6.0:formatted:1423
t @ jquery.min.js?ver=3.6.0:formatted:1434
```

the error seems to be caused by the following like in my handler, this handler is registered as a script depend for my widget and has "elementor-frontend" as a dependancy when registering the script with wordpress

```
jQuery(window).on("elementor/frontend/init", () => {
  //Add Handler
});
```

I can't seem to figure out the reason for this happening, I have followed the documentation exactly.reason

### Steps to reproduce

1) Create custom widget
2) Add Script Dependancy
3) Write Handler
4) add event handler for elementor/frontend/init

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.16.0
	MySQL version: MySQL Community Server - GPL v8.0.16
	PHP Version: 7.4.1
	PHP Memory Limit: 256M
	PHP Max Input Vars: 4000
	PHP Max Post Size: 1000M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.2
	Site URL: http://elementorlibrary.local
	Home URL: http://elementorlibrary.local
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: dev-email@flywheel.local
	Debug Mode: Active

== Theme ==
	Name: Twenty Twenty-Two
	Version: 1.1
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.7.4
		Author: Elementor.com

	Marleyplant Widget Library
		Version: 1.3.8
		Author: MarleyPlant

== Elements Usage ==
	
	wp-page : 1
		image-slider : 1

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Import Export Template Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default

== Log ==

Log: showing 5 of 52022-09-04 17:34:46 [info] elementor::elementor_updater Started 
2022-09-04 17:34:46 [info] Elementor/Upgrades - _on_each_version Start  
2022-09-04 17:34:46 [info] Elementor/Upgrades - _on_each_version Finished 
2022-09-04 17:34:46 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.5',
  'to' => '3.7.4',
)]
2022-09-04 17:34:46 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.5',
  'to' => '3.7.4',
)]

JS: showing 2 of 2JS: 2022-09-04 18:07:00 [error X 42][http://elementorlibrary.local/wp-includes/js/jquery/jquery.min.js?ver=3.6.0:2:31703] Cannot read properties of undefined (reading \'tools\') 
JS: 2022-09-04 18:30:02 [error X 1][http://elementorlibrary.local/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.7.4:2:2235] Cannot read properties of undefined (reading \'data\')

**Comment by rami-elementor** [comment]
Hi @MarleyPlant 

Can you share your code here?

**Comment by MarleyPlant** [comment]
@rami-elementor 

Handler.js
```javascript
(function ($) {
  class ImageSliderHandler extends elementorModules.frontend.handlers.Base {
    currentSlide = 0;
    dotActiveClass = "image-slider__dot--active";

    getDefaultSettings() {
      return {
        selectors: {
          prevButton: ".image-slider__controls__prev",
          nextButton: ".image-slider__controls__next",
          dots: ".image-slider__dot",
          slides: ".image-slider__img",
        },
      };
    }

    getDefaultElements() {
      const selectors = this.getSettings("selectors");
      return {
        $nextButton: this.$element.find(selectors.nextButton),
        $prevButton: this.$element.find(selectors.prevButton),
        $slides: this.$element.find(selectors.slides),
        $dots: this.$element.find(selectors.dots),
      };
    }

    bindEvents() {
      this.elements.$nextButton.on("click", this.nextSlide.bind(this));
      this.elements.$prevButton.on("click", this.prevSlide.bind(this));
      this.elements.$dots.on("click", this.onDotClick.bind(this));
    }

    nextSlide() {
      this.resetSlides();
      this.currentSlide++;
      if (this.currentSlide > slides.length) {
        this.currentSlide = 1;
      }

      dots[this.currentSlide - 1].classList.add(this.dotActiveClass);
      this.showSlide(this.currentSlide - 1);
    }

    showSlide() {
      this.elememts.$slides[slide].style.display = "block";
    }

    resetSlides() {
      this.elements.$dots.removeClass(this.dotActiveClass);
      this.elements.$slides.css("display", "none");
    }

    prevSlide() {
      this.resetSlides();
      if (this.currentSlide > 0) {
        this.currentSlide--;
      } else if (this.currentSlide == 0) {
        this.currentSlide = this.elements.$slides.length - 1;
      }

      if (this.currentSlide > 0) {
        this.elements.$dots[this.currentSlide - 1].classList.add(
          this.dotActiveClass
        );
      } else {
        this.elements.$dots[slides.length - 1].classList.add(
          this.dotActiveClass
        );
      }
      this.showSlide(this.currentSlide);
    }

    onDotClick(event) {
      this.resetSlides();
      this.currentSlide = $(event.target).index();
      this.showSlide(this.currentSlide);
      event.target.classList.add(this.dotActiveClass);
    }
  }

  $(window).on("elementor/frontend/init", () => {
    elementorFrontend.elementsHandler.attachHandler(
      "image-slider",
      ImageSliderHandler
    );
  });
  
})(jQuery);
````

Widget.php
```
<?php

/**
 * Marleyplant Widgets Library
 * php version 7.3.1
 * 
 * @category   Scripts
 * @package    MarleyPlant
 * @subpackage Scripts
 * @author     Marley Plant <marley@marleyplant.com>
 * @license    Apache http://www.apache.org/licenses/
 * @link       https://marleyplant.com
 * @since      1.0
 */

use Elementor\Widget_Base;
use Elementor\Controls_Manager;

if (!defined('ABSPATH')) {
    exit; // Exit if accessed directly
}

/**
 * Elementor Image Comparison Widget
 *
 * This class defines the Image Slider Widget
 * 
 * @category   Scripts
 * @package    MarleyPlant
 * @subpackage Scripts
 * @author     Marley Plant <marley@marleyplant.com>
 * @license    Apache http://www.apache.org/licenses/
 * @link       https://marleyplant.com
 * @since      1.0
 */

class ImageSlider extends \Elementor\Widget_Base
{

    /**
     * Retrieve the widget name.
     *
     * @since 1.0.0
     *
     * @access public
     *
     * @return string Widget name.
     */
    public function get_name()
    {
        return 'image-slider';
    }

    /**
     * Retrieve the widget title.
     *
     * @since 1.0.0
     *
     * @access public
     *
     * @return string Widget title.
     */
    public function get_title()
    {
        return __('Image Slider', 'marleyplant_widgets');
    }

    /**
     * Retrieve the widget icon.
     *
     * @since 1.0.0
     *
     * @access public
     *
     * @return string Widget icon.
     */
    public function get_icon()
    {
        return 'eicon-slider-full-screen';
    }

    /**
     * Retrieve the list of categories the widget belongs to.
     *
     * Used to determine where to display the widget in the editor.
     *
     * Note that currently Elementor supports only one category.
     * When multiple categories passed, Elementor uses the first one.   
     *
     * @since 1.0.0
     *
     * @access public
     *
     * @return array Widget categories.
     */
    public function get_categories()
    {
        return ['general'];
    }

    /**
     * Get custom help URL.
     *
     * Retrieve a URL where the user can get more information about the widget.
     *
     * @since 1.0.0
     * @access public
     * @return string Widget help URL.
     */
    public function get_custom_help_url()
    {
        return 'https://developers.elementor.com/docs/widgets/';
    }


    /**
     * Get widget keywords.
     *
     * Retrieve the list of keywords the oEmbed widget belongs to.
     *
     * @since 1.0.0
     * @access public
     * @return array Widget keywords.
     */
    public function get_keywords()
    {
        return ['plantek'];
    }


    /**
     * Retrieve the list of scripts the widget depended on.
     *
     * Used to set scripts dependencies required to run the widget.
     *
     * @since 1.0.0
     *
     * @access public
     *
     * @return array Widget scripts dependencies.
     */
    public function get_script_depends()
    {
        return ['image-slider-js'];
    }

    /**
     * Register the widget controls.
     *
     * Adds different input fields to allow the user to change and customize the widget settings.
     *
     * @since 1.0.0
     *
     * @access protected
     * @return null
     */
    protected function register_controls()
    {

        $this->start_controls_section(
            'content_section',
            [
                'label' => __('Content', 'plugin-name'),
                'tab' => \Elementor\Controls_Manager::TAB_CONTENT,
            ]
        );

        $repeater = new \Elementor\Repeater();

        $repeater->add_control(
            'heading',
            [
                'label' => esc_html__('Title', 'plugin-name'),
                'type' => \Elementor\Controls_Manager::TEXT,
                'default' => esc_html__('Title', 'plugin-name'),
                'label_block' => true,
            ]
        );

        $repeater->add_control(
            'image',
            [
                'label' => esc_html__('Choose Image', 'plugin-name'),
                'type' => \Elementor\Controls_Manager::MEDIA,
                'default' => [
                    'url' => \Elementor\Utils::get_placeholder_image_src(),
                ],
            ]
        );

        $this->add_control(
            'slides',
            [
                'label' => esc_html__('Slides List', 'plugin-name'),
                'type' => \Elementor\Controls_Manager::REPEATER,
                'fields' => $repeater->get_controls()
            ]
        );

        $this->end_controls_section();

        $this->start_controls_section(
            'section_style',
            [
                'label' => __('Style', 'marleyplant_widgets'),
                'tab' => Controls_Manager::TAB_STYLE,
            ]
        );

        $this->add_control(
            'color_slider',
            [
                'label' => esc_html__('Primary Color', 'plugin-name'),
                'type' => \Elementor\Controls_Manager::COLOR,
                'selectors' => [
                    '{{WRAPPER}} .title' => 'color: {{VALUE}}',
                ],
            ]
        );

        $this->add_control(
            'sliderWidth',
            [
                'label' => __('Width', 'plugin-domain'),
                'type' => Controls_Manager::SLIDER,
                'size_units' => ['%', 'em', 'px'],
                'range' => [
                    '%' => [
                        'min' => 0,
                        'max' => 100,
                    ],
                ],
                'default' => [
                    'unit' => '%',
                    'size' => 100,
                ],
                'selectors' => [
                    '{{WRAPPER}} .image-slider' => 'width: {{SIZE}}{{UNIT}};',
                ],
            ]
        );

        $this->add_control(
            'sliderHeight',
            [
                'label' => __('Height', 'plugin-domain'),
                'type' => Controls_Manager::SLIDER,
                'size_units' => ['%', 'em', 'px'],
                'range' => [
                    '%' => [
                        'min' => 0,
                        'max' => 100,
                    ],
                    "em" => [
                        'min' => 0,
                        'max' => 100
                    ]
                ],
                'default' => [
                    'unit' => '%',
                    'size' => 100,
                ],
                'selectors' => [
                    '{{WRAPPER}} .image-slider' => 'height: {{SIZE}}{{UNIT}};',
                    '{{WRAPPER}} .image-slider__img' => 'height: {{SIZE}}{{UNIT}};',
                ],
            ]
        );

        $this->add_control(
            'objectFit',
            [
                'label' => esc_html__('Object Fit', 'plugin-name'),
                'type' => \Elementor\Controls_Manager::SELECT,
                'default' => 'cover',
                'options' => [
                    'cover'  => esc_html__('Cover', 'plugin-name'),
                    'fill' => esc_html__('Fill', 'plugin-name'),
                    'contain' => esc_html__('Contain', 'plugin-name'),
                    'scale-down' => esc_html__('Scale Down', 'plugin-name'),
                ],
            ]
        );

        $this->add_control(
            'show_controls',
            [
                'label' => esc_html__('Show Controls?', 'plugin-name'),
                'type' => \Elementor\Controls_Manager::SWITCHER,
                'label_on' => esc_html__('Show', 'your-plugin'),
                'label_off' => esc_html__('Hide', 'your-plugin'),
                'return_value' => 'yes',
                'default' => 'yes',
            ]
        );

        $this->add_control(
            'show_dots',
            [
                'label' => esc_html__('Show Dots?', 'plugin-name'),
                'type' => \Elementor\Controls_Manager::SWITCHER,
                'label_on' => esc_html__('Show', 'your-plugin'),
                'label_off' => esc_html__('Hide', 'your-plugin'),
                'return_value' => 'yes',
                'default' => 'yes',
            ]
        );

        $this->end_controls_section();
    }

    /**
     * Render the widget output on the frontend.
     *
     * Written in PHP and used to generate the final HTML.
     *
     * @since 1.0.0
     *
     * @access protected
     * @return null
     */
    protected function render()
    {
        include __DIR__ . '/template.php';
    }
}

```

**Comment by MarleyPlant** [comment]
Would love to know the reason why this isn't working.

**Comment by mapsmarketing** [comment]
Sounds like a similar problem I had when trying to use the `SwiperBase`.

At the bottom of the [page](https://developers.elementor.com/add-javascript-to-elementor-widgets/) you'll notice that the code needs to be transpiled: 

> For wider browser support, it is recommended to transpile your class into ES5 syntax (using a tool such as Babel.js) before deploying it in production.

However, you can create the `Base` class in another way as shown by [meceware](https://github.com/elementor/elementor/issues/9781)

My issue/post has info on how to transpile it if you want to do it that way: https://github.com/elementor/elementor/issues/19858

**Comment by Reichbaum** [comment]
I have the same problem. This bug only appears on the Twenty Twenty-Two and Twenty Twenty-Three themes (WP 6.1, Elementor 3.8.0, clean themes, no other plugins).

The console error:
```
jquery.min.js?ver=3.6.1:2 Uncaught TypeError: Cannot read properties of undefined (reading 'tools')
    at Frontend.initOnReadyComponents (frontend.min.js?ver=3.8.0:2:6682)
    at Frontend.init (frontend.min.js?ver=3.8.0:2:8809)
    at HTMLDocument.<anonymous> (frontend.min.js?ver=3.8.0:2:9035)
    at e (jquery.min.js?ver=3.6.1:2:30038)
    at t (jquery.min.js?ver=3.6.1:2:30340)
```
My code:
```
class WPCC_Widget extends Widget_Base {

	public function __construct( $data = [], $args = null ) {
	parent::__construct( $data, $args );

		if ( defined( 'WPCC_VERSION' ) ) {
			$version = WPCC_VERSION;
		} else {
			$version = '1.0.0';
		}

		wp_register_script( 'wpcc-elementor-script', plugin_dir_url( __FILE__ ) . 'assets/wpcc-elementor-script.js', array( 'elementor-frontend' ), $version, true );
	}
	
	public function get_script_depends() {
		return array( 'wpcc-elementor-script' );
	}
}
```

My Script:
```
(function ($) {
	class wpccClass extends elementorModules.frontend.handlers.Base {
		getDefaultSettings() {
			return {
				selectors: {
					widget: ".wpcc-elementor-block",
				},
			};
		}

		getDefaultElements() {
			const selectors = this.getSettings("selectors");

			return {
				$widgets: this.findElement(selectors.widget),
			};
		}

		bindEvents() {}

		onInit(...args) {
			console.log('here');
		}
	}

	$(window).on("elementor/frontend/init", () => {
		elementorFrontend.elementsHandler.attachHandler('wpcc-widget', wpccClass);
	});
})(jQuery);
```


Moreover, here in the documentation - https://developers.elementor.com/docs/scripts-styles/widget-scripts/ - there is no 'elementor-frontend' in the dependencies, but then the error is like this:
```
Uncaught ReferenceError: elementorModules is not defined
    at wpcc-elementor-script.js:2:36
    at wpcc-elementor-script.js:2:27
    at wpcc-elementor-script.js:1:1
```

But here - https://developers.elementor.com/add-javascript-to-elementor-widgets/#Registering_the_Widget_Handler_with_Elementor - 'elementor-frontend' is in the dependencies - and this solution works in all but these two themes.

I would appreciate any help!

**Comment by nicoblg** [comment]
Same problem here since a year i think. I noticed that this happens for logged in users, however i think i found a temporary workaround for this as the error reported by this bug report shows up even if you enqueue a blank js and this let me think that maybe is a priority issue.

It seems that the scripts are loaded before 'elementor-frontend' is actually loaded, so my solution is to add an high priority to the reccomended code as showed below:
`add_action( 'wp_enqueue_scripts', 'your-register-function', 9999 )`

This seems the only thing that works for now.

**Comment by YahyaTec** [comment]
Yes, this issue occurs stills latest update

**Comment by Reichbaum** [comment]
I found this - the problem occurs on block themes:
https://ibb.co/pJ3TV4s

**Comment by POBrien333** [comment]
This also occurs with the MasterStudy LMS theme.

**Comment by Reichbaum** [comment]
Guys, this bug is still relevant - my custom widget is still causing this error on block themes. Any progress in this area?

**Comment by nicoblg** [comment]
> Guys, this bug is still relevant - my custom widget is still causing this error on block themes. Any progress in this area?

Hi, i think at this point that they did not want to solve this bug. As a solution, created a function in wich i register and localize all my scripts and then enqueue them on init.

So i have a function like this:
```php
public function register_dependencies() {
    $dbp_js_ver  = date("ymd-Gis", filemtime( brainless_elements()->plugin_path . '/assets/js/db-post.js' ));
    wp_register_script( 'db-post-scripts', brainless_elements()->assets_url .'/js/db-post.js', [ 'elementor-frontend' ], $dbp_js_ver, true );
    wp_localize_script( 'db-post-scripts', 'db_post_ajax', array( 'ajaxurl' => admin_url('admin-ajax.php'), 'check_nonce' => wp_create_nonce('db-nonce')) );
}
``` 
and then in init i do this:
```php
add_action( 'wp_enqueue_scripts', [ $this, 'register_dependencies' ], 9999 );
``` 
shortly after registering my widgets and controls. I also noticed that elementor do not load all my registered files, but only the ones the widget depends on where the widget is loaded, using the
```php
public function get_script_depends() {
    return [ 'db-post-scripts' ];
}
``` 
Hope it helps 🤔

**Comment by Reichbaum** [comment]
Hi @nicoblg!

This solution continues to cause an error on block themes. I enqueued the script in the high priority way you suggested above and it works on block themes, but some users are having the problem when using some caching plugins. I'm not 100% sure this is where the problem lies as I haven't had access to the problem sites, but theoretically the possibility is there. Ok, too bad we can't influence this.....

**Comment by webdevs-pro** [comment]
Same for me, `elementorModules.frontend is undefined` on block themes. 2024, 2023 not working. Hello Theme and OceanWP works fine

**Comment by bdkoder** [comment]
![image](https://github.com/user-attachments/assets/f02c74f7-2304-4d51-92c2-5218fe58cb45)

![image](https://github.com/user-attachments/assets/5883c69b-f1e9-43e5-ade7-35d700fc68df)

**Comment by rlegall-eness** [comment]
I'm using the Hello theme, Elementor and Elementor Pro.

Like bdkoder, everything was working fine with 3.23.4 version but since 3.24, frontend is missing in elementorModules.

However, if I deactivate Elementor Pro (v 3.24.3) and I only keep Elementor (v 3.24.5), everything works and frontend isn't missing in elementorModules. The issue seems to be related to Elementor Pro.

**Comment by bdkoder** [comment]
Finally solutions - 
```php
add_action( 'wp_enqueue_scripts', [ $this, 'enqueue_site_scripts' ], 99999 );
```

Note: Don't use 'elementor-frontend' as dependency.

**Comment by mapsmarketing** [comment]
Can you elaborate a bit more on this? @bdkoder

**Comment by bdkoder** [comment]
Hello @mapsmarketing ,
At first look into all your scripts that's working with your widgets, & not talking about vendor scripts.
And then make sure you removed the 'elementor-frontend' dependency from all scripts and also make sure you register a script first then enqueue.
```php
public function your_prefix_enqueue_site_scripts() {
wp_register_script( 'test', 'test.js', [ 'jquery' ], '1.00', true ); //here only dependency is jQuery
wp_enqueue_script( 'test' );
}
```
And then load the script and you can use the priority param to make it happens - 
```php
add_action( 'wp_enqueue_scripts', [ $this, 'your_prefix_enqueue_site_scripts' ], 99999 );
```

And then if you cannot solve the issues, feel free to knock me via my profile. 
Thanks.

**Comment by lae-qguiraudie** [comment]
Hello,
same bug for me for several days,
just find a clean solution into the doc
https://developers.elementor.com/add-javascript-to-elementor-widgets/
we have to move the wp_register_script into our custom widgets __construct 

`class Widget_Class_Name extends \Elementor\Widget_Base {

   public function __construct($data = [], $args = null) {
      parent::__construct($data, $args);

      wp_register_script( 'script-handle', 'path/to/file.js', [ 'elementor-frontend' ], '1.0.0', true );
   }

   public function get_script_depends() {
       return [ 'script-handle' ];
   }

}`

**Comment by mapsmarketing** [comment]
Hi @lae-qguiraudie 

That isn't the solution because that's what I have currently and it adheres to that and the changes mentioned in: https://developers.elementor.com/a-new-method-for-attaching-a-js-handler-to-an-element/

However, the errors continue to persist in even the most latest version of both Elementor and Elementor Pro.

The seriously confusing part is, the docs are showing us something different here https://developers.elementor.com/docs/scripts-styles/widget-scripts/ while showing us to throw it into __construct in here https://developers.elementor.com/add-javascript-to-elementor-widgets/

It would be great to get some clarity on what's going on @nicholaszein

**Comment by lae-qguiraudie** [comment]
@mapsmarketing I agree the doc is confusing.
I've always used "elementor/frontend/after_register_scripts" to register my custom widgets assets (js+css)
Moving them into the widget __construct function yesterday fixed this two errors for me
 ```
Uncaught TypeError: Cannot read properties of undefined (reading 'handlers')
    at 820 (frontend.min.js:2:4477)
    at __webpack_require__ (webpack-pro.runtime.min.js:2:150)
    at 4906 (frontend.min.js:2:4134)
    at __webpack_require__ (webpack-pro.runtime.min.js:2:150)
    at 3000 (frontend.min.js:2:139)
    at __webpack_require__ (webpack-pro.runtime.min.js:2:150)
    at frontend.min.js:2:24995
    at webpackJsonpCallback (webpack-pro.runtime.min.js:2:5854)
    at frontend.min.js:2:69
 ```
 ```
jquery.min.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'tools')
    at Frontend.initOnReadyComponents (frontend.min.js:2:7393)
    at Frontend.init (frontend.min.js:2:9297)
    at HTMLDocument.<anonymous> (frontend.min.js:2:9523)
    at e (jquery.min.js:2:27028)
    at t (jquery.min.js:2:27330)
 ```
Probably a different issue

**Comment by rlegall-eness** [comment]
I found a solution that is working for me, I don't know if it is the right way to handle this issue, but it seems ok for me.

I register my js file before initiating my widget class:
`
public function widgets_js_dependencies() {
        wp_register_script('my-widget-js', plugins_url( '/assets/js/my-widget.js', ELEMENTOR_REALISATION ));
}
add_action( 'elementor/frontend/after_enqueue_scripts', [ $this, 'widgets_js_dependencies' ] );
`

After that I initiate my class and add a JS dependency to my JS file only, I don't add a dependency to 'elementor-frontend'.

`
class My_Widget extends Widget_Base {

	public function __construct($data = array(), $args = null){
		parent::__construct($data, $args);
	}

	public function get_script_depends() {
		return [ 'my-widget-js' ];
	}
}
`

The only thing I changed is the hook I use to add my js file. I was previously using the "wp_enqueue_scripts" hook and even with a 99999 priority parameter, I still got the errors.
I also regenerate Files & Data in Elementor > Tools.

**Comment by mapsmarketing** [comment]
> @mapsmarketing I agree the doc is confusing. I've always used "elementor/frontend/after_register_scripts" action to register my custom widgets assets (js+css) Moving them into the widget __construct function yesterday fixed this two errors for me
> 
> ```
> Uncaught TypeError: Cannot read properties of undefined (reading 'handlers')
>    at 820 (frontend.min.js:2:4477)
>    at __webpack_require__ (webpack-pro.runtime.min.js:2:150)
>    at 4906 (frontend.min.js:2:4134)
>    at __webpack_require__ (webpack-pro.runtime.min.js:2:150)
>    at 3000 (frontend.min.js:2:139)
>    at __webpack_require__ (webpack-pro.runtime.min.js:2:150)
>    at frontend.min.js:2:24995
>    at webpackJsonpCallback (webpack-pro.runtime.min.js:2:5854)
>    at frontend.min.js:2:69
> ```
> 
> ```
> jquery.min.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'tools')
>    at Frontend.initOnReadyComponents (frontend.min.js:2:7393)
>    at Frontend.init (frontend.min.js:2:9297)
>    at HTMLDocument.<anonymous> (frontend.min.js:2:9523)
>    at e (jquery.min.js:2:27028)
>    at t (jquery.min.js:2:27330)
> ```
> 
> Probably a different issue

I have the scripts loading currently in my __construct and the above errors persist. I've never used `elementor/frontend/after_register_scripts` since I've never seen it mentioned in the docs.

Not sure about it being a "different issue" since both are related to elementor-frontend.

**Comment by liveweltDigital** [comment]
We have the same problem on several of our websites. This also affects various plugins in which the scripts are loaded similarly (according to the Elementor documentation).

However, this does not “only” lead to the console error, which we also have, no - in addition, all Elementor Entrance animations (e.g. fade-in) are no longer displayed. The CSS class elementor-visible is no longer removed if widgets are in the viewport, and this affects not only the affected widgets themselves, but all elements on the page.

Do you also experience this?
I think it is due to the errors:
Uncaught TypeError: Cannot read properties of undefined (reading 'handlers')
Uncaught TypeError: Cannot read properties of undefined (reading 'tools')
Both seem to be related to the initial problem.

**Comment by ajoah** [comment]
I found the origin of the issue !

 (I would use the name of the scripts in php code, not the real name of js files)

When `elementorModules ` is initialized, there is no `frontend` attribute : https://github.com/elementor/elementor/blob/c19b48c40ecaf5ecee56e77159b605d7f59daf02/assets/dev/js/modules/modules.js

The attribute is added by `elementor-frontend-modules` : https://github.com/elementor/elementor/blob/540334f7084a4e43ecea6b3ee782aa3567a98fe8/assets/dev/js/frontend/modules.js

This script is a dependence of `elementor-frontend` used by the custom widget, so it should be ok…

**BUT**

the `elementorModules` is initialized by **two** files : `elementor-frontend-modules` AND `elementor-common-modules` https://github.com/search?q=repo%3Aelementor%2Felementor%20modules%2Fmodules&type=code
`elementor-frontend-modules` adds the frontend attribute, but not `elementor-common-modules`

SO if `elementor-common-modules` is loaded after `elementor-frontend-modules`, it reinitializes the `elementorModules` and `elementorModules.frontend` become `undefined`.

That's why the bug seems random and not everyone meet it. If any script using `elementor-common-modules` is loaded before the `elementor-frontend-modules` script, the bug disappears.

A quick workaround is to add  `elementor-common-modules`  to your script dependencies

```
class Widget_Class_Name extends \Elementor\Widget_Base {

   public function __construct($data = [], $args = null) {
      parent::__construct($data, $args);

      wp_register_script( 'script-handle', 'path/to/file.js', [ 'elementor-common-modules', 'elementor-frontend' ], '1.0.0', true );
   }

   public function get_script_depends() {
       return [ 'script-handle' ];
   }

}
```

@nicholaszein : it seems to be a real bug, `elementorModules.frontend` should not become undefined because of the presence of the `elementor-common-modules` script.

**Comment by liveweltDigital** [comment]
Hi @ajoah, thanks for your contribution.
The problem has kept us busy for a long time!
This bug in Elementor definitely needs to be fixed asap.

However, your workaround works perfectly, we have been able to fix 30 of our custom widgets in the last days.
We owe you more than a coffee!

**Comment by steveindzine** [comment]
> Hi [@ajoah](https://github.com/ajoah), thanks for your contribution. The problem has kept us busy for a long time! This bug in Elementor definitely needs to be fixed asap.
> 
> However, your workaround works perfectly, we have been able to fix 30 of our custom widgets in the last days. We owe you more than a coffee!

My issue with this workaround is that the commercial Elementor plugins will also do this, and so far they don't want to as they see it as a bug that Elementor needs to fix.

**Comment by IgnacioJ79** [comment]
> We have the same problem on several of our websites. This also affects various plugins in which the scripts are loaded similarly (according to the Elementor documentation).
> 
> However, this does not “only” lead to the console error, which we also have, no - in addition, all Elementor Entrance animations (e.g. fade-in) are no longer displayed. The CSS class elementor-visible is no longer removed if widgets are in the viewport, and this affects not only the affected widgets themselves, but all elements on the page.
> 
> Do you also experience this? I think it is due to the errors: Uncaught TypeError: Cannot read properties of undefined (reading 'handlers') Uncaught TypeError: Cannot read properties of undefined (reading 'tools') Both seem to be related to the initial problem.

This is exactly what happens to my website. But only happens with 1 section and it happens only sometimes and to some people.

I never had this problem ever before.

**Comment by IgnacioJ79** [comment]
> I found the origin of the issue !
> 
> (I would use the name of the scripts in php code, not the real name of js files)
> 
> When `elementorModules ` is initialized, there is no `frontend` attribute : https://github.com/elementor/elementor/blob/c19b48c40ecaf5ecee56e77159b605d7f59daf02/assets/dev/js/modules/modules.js
> 
> The attribute is added by `elementor-frontend-modules` : https://github.com/elementor/elementor/blob/540334f7084a4e43ecea6b3ee782aa3567a98fe8/assets/dev/js/frontend/modules.js
> 
> This script is a dependence of `elementor-frontend` used by the custom widget, so it should be ok…
> 
> **BUT**
> 
> the `elementorModules` is initialized by **two** files : `elementor-frontend-modules` AND `elementor-common-modules` https://github.com/search?q=repo%3Aelementor%2Felementor%20modules%2Fmodules&type=code `elementor-frontend-modules` adds the frontend attribute, but not `elementor-common-modules`
> 
> SO if `elementor-common-modules` is loaded after `elementor-frontend-modules`, it reinitializes the `elementorModules` and `elementorModules.frontend` become `undefined`.
> 
> That's why the bug seems random and not everyone meet it. If any script using `elementor-common-modules` is loaded before the `elementor-frontend-modules` script, the bug disappears.
> 
> A quick workaround is to add `elementor-common-modules` to your script dependencies
> 
> ```
> class Widget_Class_Name extends \Elementor\Widget_Base {
> 
>    public function __construct($data = [], $args = null) {
>       parent::__construct($data, $args);
> 
>       wp_register_script( 'script-handle', 'path/to/file.js', [ 'elementor-common-modules', 'elementor-frontend' ], '1.0.0', true );
>    }
> 
>    public function get_script_depends() {
>        return [ 'script-handle' ];
>    }
> 
> }
> ```
> 
> [@nicholaszein](https://github.com/nicholaszein) : it seems to be a real bug, `elementorModules.frontend` should not become undefined because of the presence of the `elementor-common-modules` script.

Thanks a lot!

Where do I add that code? Is it in functions.php?

**Comment by steveindzine** [comment]
@IgnacioJ79 this is only to be used when you have your own custom widgets where you are in control of the code. If this isn't your case, each plugin that extends Elementor with additional widgets needs to be updated with this workaround. This is unlikely to happen, as the plugin developers see this as an issue that Elementor needs to fix as they are all doing it correctly as per the documentation.

You could try this workaround, it goes in your functions.php file: https://github.com/elementor/elementor/issues/28839#issuecomment-2569727401

**Comment by ahirhemant** [comment]
Hi,  

This issue still persists with the Hello theme and Elementor + Elementor Pro.

**Comment by emuplugins** [comment]
This issue seems to be caused by the "Optimized Control Loading" option, which is enabled by default in recent versions. Rolling back to version 3.24.6 and disabling this option (which is hidden in newer versions) fixed the problem for me.

Honestly, I’m not sure, because I tried reproducing the error by updating Elementor, but the error didn’t come back! It stopped happening when I reverted to the previous version of Elementor and disabled the option.

It might have been some cache issue, but this solution worked for me.

I encountered this problem both in a new installation of Elementor and in an older one.

In the new installation, to solve the problem, I removed scripts from the Custom Code tab and added them to the child theme. That solved the issue for me.

In the older installation, the solution was disabling the "Optimized Control Loading" option.

**Comment by violetweb** [comment]
Here is what worked for me :  ['strategy' => 'defer']        

I tried the an array specifying the elementor front end modules, without the defer; that did not work.  It would seem you just need to make sure that your script loads after everything else.

wp_register_script('slides-script', plugin_dir_url(__FILE__) . 'assets/slides.js', ['elementor-common-modules', 'elementor-frontend'], '1.0.0', ['strategy' => 'defer']);
