### ISSUE TITLE
3.7.7 Spacer widget in container with flex-direction:row has height = 0px

### ISSUE THREAD

**Issue by joehdevwp** [elementor/elementor#19904]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

in v 3.7.7 absolutely positioned spacer widget in a container with flex-direction:row has no height despite setting a custom height and width in px.

### Steps to reproduce

1. add a spacer widget to a container with flex-direction:row , set the spacer to position: absolute
2. give the spacer a set height and custom width e.g 450px x 450px
3. on front end note that this css sets the spacer height to 0px:

.e-container>.elementor-widget-spacer>.elementor-widget-container>.elementor-spacer>.elementor-spacer-inner {
    height: var(--container-widget-height,var(--spacer-size));
}

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Flywheel/5.1.0
	MySQL version: (Google) v5.7.38
	PHP Version: 7.4.30
	PHP Memory Limit: 128M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 300M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: There are some writing permissions issues with the following directories/files:
		 - WordPress root directory
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.2
	Site URL: https://nawg2.flywheelsites.com
	Home URL: https://nawg2.flywheelsites.com
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 128M
	Max Memory limit: 128M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/Chicago
	Admin Email: web@middle.co
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.6.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 5.12.2
		Author: Delicious Brains

	Custom Post Type UI
		Version: 1.13.1
		Author: WebDevStudios

	Dynamic.ooo - Dynamic Content for Elementor
		Version: 2.7.9
		Author: Dynamic.ooo

	Elementor
		Version: 3.7.7
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.7
		Author: Elementor.com

	Gravity Forms
		Version: 2.6.7
		Author: Gravity Forms

	Machete
		Version: 4.0.1
		Author: Nilo Velez

	WP-Sweep
		Version: 1.1.5
		Author: Lester 'GaMerZ' Chan

== Elements Usage ==
	
	header : 1
		container : 2
		icon : 1
		nav-menu : 2
	wp-page : 2
		button : 8
		container : 12
		dce-dynamicposts-v2 : 2
		heading : 19
		image : 1
		spacer : 1
		text-editor : 8

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Active
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Inactive
	Import Export Template Kit: Inactive
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Inactive
	Landing Pages: Inactive
	Color Sampler: Inactive
	Favorite Widgets: Inactive
	Admin Top Bar: Inactive
	Page Transitions: Inactive
	Notes: Inactive
	Form Submissions: Inactive
	Scroll Snap: Inactive

== Log ==
	
Log: showing 20 of 312022-09-23 09:04:14 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.0',
  'to' => '3.7.7',
)]
2022-09-23 09:08:48 [info] elementor-pro::elementor_pro_updater Started 
2022-09-23 09:08:48 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-09-23 09:08:48 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-09-23 09:08:48 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Start  
2022-09-23 09:08:48 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Finished 
2022-09-23 09:08:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.0',
  'to' => '3.7.7',
)]
2022-09-23 20:24:04 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Dynamic.ooo - Dynamic Content for Elementor',
  'from' => '2.4.0',
  'to' => '2.7.9',
)]
2022-09-23 20:25:46 [info] dynamic-content-for-elementor::dce_updater Started 
2022-09-23 20:25:46 [info] Dynamic.ooo - Dynamic Content for Elementor/Upgrades - _v_2_6_1_views_change_default Start  
2022-09-23 20:25:46 [info] Dynamic.ooo - Dynamic Content for Elementor/Upgrades - _v_2_6_1_views_change_default Finished 
2022-09-23 20:25:46 [info] Dynamic.ooo - Dynamic Content for Elementor/Upgrades - _v_2_5_0_dynamic_charts_background_repeater Start  
2022-09-23 20:25:46 [info] Dynamic.ooo - Dynamic Content for Elementor/Upgrades - _v_2_5_0_dynamic_charts_background_repeater Finished 
2022-09-23 20:25:46 [info] Dynamic.ooo - Dynamic Content for Elementor/Upgrades - _v_2_5_0_dynamic_google_maps_default Start  
2022-09-23 20:25:46 [info] Dynamic.ooo - Dynamic Content for Elementor/Upgrades - _v_2_5_0_dynamic_google_maps_default Finished 
2022-09-23 20:25:46 [info] Dynamic.ooo - Dynamic Content for Elementor/Upgrades - _v_2_5_0_disable_tokens_filters_whitelist Start  
2022-09-23 20:25:46 [info] Dynamic.ooo - Dynamic Content for Elementor/Upgrades - _v_2_5_0_disable_tokens_filters_whitelist Finished 
2022-09-23 20:25:46 [info] Dynamic.ooo - Dynamic Content for Elementor/Upgrades - _v_2_5_0_no_new_features_default Start  
2022-09-23 20:25:47 [info] Dynamic.ooo - Dynamic Content for Elementor/Upgrades - _v_2_5_0_no_new_features_default Finished 
2022-09-23 20:25:47 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Dynamic.ooo - Dynamic Content for Elementor',
  'from' => '2.4.0',
  'to' => '2.7.9',
)]

PHP: showing 10 of 10PHP: 2022-09-23 09:15:12 [notice X 18][/www/wp-content/plugins/elementor-pro/core/utils/collection.php::75] Return type of ElementorPro\Core\Utils\Collection::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-23 16:23:51 [notice X 76][/www/wp-content/plugins/elementor-pro/core/database/model-base.php::135] Return type of ElementorPro\Core\Database\Model_Base::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: /www/wp-content/plugins/elementor-pro/core/database/model-base.php(10): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /www/wp-content/plugins/elementor-pro/plugin.php(153): class type include()array (
  0 => '/www/wp-content/plugins/elementor-pro/core/database/model-base.php',
)
#2: /www/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php(18): ElementorPro\Plugin -> autoload()
#3: /www/wp-content/plugins/elementor-pro/plugin.php(153): class type include()array (
  0 => '/www/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php',
)
#4: /www/wp-content/plugins/elementor-pro/modules/notes/data/controller.php(236): ElementorPro\Plugin -> autoload()
',
)]
PHP: 2022-09-23 20:34:02 [error X 1][/www/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Allowed memory size of 134217728 bytes exhausted (tried to allocate 9149104 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-23 20:46:28 [warning X 1][/www/wp-content/plugins/elementor/core/files/file-types/svg.php::234] simplexml_load_file(): I/O warning : failed to load external entity "https://nawg2.flywheelsites.com/wp-content/uploads/NAWG-logo.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-23 20:51:21 [warning X 1][/www/wp-content/plugins/elementor/core/files/file-types/svg.php::234] simplexml_load_file(): I/O warning : failed to load external entity "https://nawg2.flywheelsites.com/wp-content/uploads/middle-logo.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-23 21:01:18 [notice X 2][/www/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-23 21:02:12 [error X 1][/www/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on bool in /www/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /www/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /www/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /wordpress/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /wordpress/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#5 /wordpress/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#6 /wordpress/wp-admin/admin-ajax.php(187): do_ac [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-23 21:22:12 [warning X 1][/www/wp-content/plugins/elementor/core/files/file-types/svg.php::234] simplexml_load_file(): I/O warning : failed to load external entity "https://nawg2.flywheelsites.com/wp-content/uploads/NEWS.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-23 23:29:25 [warning X 1][/www/wp-content/plugins/elementor/core/files/file-types/svg.php::234] simplexml_load_file(): I/O warning : failed to load external entity "https://nawg2.flywheelsites.com/wp-content/uploads/NEWS2.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-23 23:47:31 [warning X 2][/www/wp-content/plugins/elementor/core/files/file-types/svg.php::234] simplexml_load_file(): I/O warning : failed to load external entity "https://nawg2.flywheelsites.com/wp-content/uploads/grain-icon.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 1 of 1JS: 2022-09-24 02:12:54 [error X 1][https://nawg2.flywheelsites.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.7:3:646945] this.model.isValidChild is not a function 

== Elementor - Compatibility Tag ==
	
	Dynamic.ooo - Dynamic Content for Elementor: Compatible
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==
	
	Dynamic.ooo - Dynamic Content for Elementor: Compatible

**Comment by nicholaszein** [comment]
Hello @joehdevwp! 

Thank you for submitting your issue! 🙏 

Please allow us some time to investigate it, and get back to you with our findings. 🧐 

Best regards

**Comment by Pycroyal** [comment]
Since Elementor 3.7.0 spacer widgets behave strangely. The height change is no longer taken into account.

**Comment by nicholaszein** [comment]
I can reproduce the issue consistently.

Thanks for the report @joehdevwp and @Pycroyal!

**Comment by Pycroyal** [comment]
Do you know when this bug will be fixed?

**Comment by nicholaszein** [comment]
Hello @Pycroyal,

We don't have any ETA for when this will be solved. But I labeled this issue so the responsible team can take a look.

Kind regards

**Comment by Leonieve** [comment]
Hello, I wonder if there's a fix for this problem yet.

**Comment by Pycroyal** [comment]
With Elementor Version 3.8.0 everything seems to be ok

But with 3.8.1 bug come back !

**Comment by Pycroyal** [comment]
Please fix !!!
All my websites design with containers are broken !

**Comment by Pycroyal** [comment]
Here the css applied to spacer :
Strange "var(--container-widget-height,var(--spacer-size))" ???

`.e-con-inner > .elementor-widget-spacer > .elementor-widget-container > .elementor-spacer > .elementor-spacer-inner, .e-con > .elementor-widget-spacer > .elementor-widget-container > .elementor-spacer > .elementor-spacer-inner {
	height: var(--container-widget-height,var(--spacer-size));
}`

**Comment by brettredvers** [comment]
Having the same issues.
Spacer does not work at all.
All sections that contain a spacer widget and are converted no longer work correctly.

**Comment by Lewis8379** [comment]
How is this still not fixed?

**Comment by KJ689** [comment]
I too am getting the same error. When the Direction of the parent container is set to Row-Horizontal the Spacer widget height is rendered as 0px. 

Well, there is a work-around to this issue. You need to place the Spacer widget inside a new container. Check the below structure which explain the before and after 
![Spacer - Error](https://github.com/user-attachments/assets/a004b63b-9885-4954-a1b6-514c8fc41f03)

A workaround to this issue is to place the Spacer widget itself inside another container. 
![Spacer - Workaround](https://github.com/user-attachments/assets/6891c832-3682-4e62-ba2f-444241dbaeb3)

Let me know if this works for anyone.
