### ISSUE TITLE
Custom widget: Can't save widget when inline <script> has php echo (in the render function)

### ISSUE THREAD

**Issue by JorensM** [elementor/elementor#20029]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Basically, I needed to include inline <script> inside the render function of my widget. I can't use `register_scripts` because I need to pass some PHP variables to the script.`script_loader_tag` is also out of the question because the PHP vars are not available at that time yet.

So about the bug -
When I try to echo a var from PHP into my <script>, the elementor editor won't let me save the page if my widget is on the page (gives "Server Error")

Example code: 

      public function render(){
                $var = 123;
               ?>
                       <script>
                                 const js_var = <?php echo $var; ?>
                       </script>
               <?php
      }

### Steps to reproduce

1. Create a new widget
2. Add the script above into the widget render function.
3. Add the widget to a page in the editor, and try to save the page. It should give "Server Error" and not save.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.51 (Debian)
	MySQL version: mariadb.org binary distribution v10.4.20
	PHP Version: 8.0.21
	PHP Memory Limit: 1400M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.2
	Site URL: https://www.matchticketshop.com
	Home URL: https://www.matchticketshop.com
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 40M
	Max Memory limit: 1400M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: sales@voetbaltrips.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36

== Active Plugins ==
	Add to Cart Button Custom Text
		Version: 3.0.6
		Author: Enrique J. Ros

	Breeze
		Version: 2.0.9
		Author: Cloudways

	Disable cart page for WooCommerce
		Version: 1.2.5
		Author: Code4Life

	Elementor
		Version: 3.7.8
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.7
		Author: Elementor.com

	FileBird Lite
		Version: 5.0.8
		Author: Ninja Team

	JetBlocks For Elementor
		Version: 1.3.2
		Author: Crocoblock

	JetElements For Elementor
		Version: 2.6.6
		Author: Crocoblock

	JetEngine
		Version: 3.0.1
		Author: Crocoblock

	JetEngine - Custom visibility conditions
		Version: 1.1.0
		Author: Crocoblock

	JetFormBuilder
		Version: 2.1.7
		Author: Crocoblock

	JetMenu
		Version: 2.1.7
		Author: Crocoblock

	JetSmartFilters
		Version: 2.3.12
		Author: Crocoblock

	JetTabs For Elementor
		Version: 2.1.17
		Author: Crocoblock

	JetWooBuilder For Elementor
		Version: 1.12.4
		Author: Crocoblock

	Matchticketshop widgets
		Version: 1.0.0
		Author: JorensM

	Match Upload
		Version: 
		Author: 

	Plugin for Google Reviews
		Version: 2.2.1
		Author: RichPlugins <support@richplugins.com>

	Really Simple SSL
		Version: 5.3.5
		Author: Really Simple Plugins

	Safe SVG
		Version: 2.0.3
		Author: 10up

	Tawk.to Live Chat
		Version: 0.7.2
		Author: Tawkto

	Widgets for Google Reviews
		Version: 9.5
		Author: Trustindex.io <support@trustindex.io>

	WooCommerce
		Version: 7.0.0
		Author: Automattic

	WooCommerce Remove All Products
		Version: 6.4
		Author: Gabriel Reguly, Erik Golinelli

	WPIDE - File Manager & Code Editor
		Version: 3.4.3
		Author: XplodedThemes

	wptools
		Version: 3.41
		Author: Bill Minozzi

	WP Ultimate CSV Importer Pro
		Version: 6.5
		Author: Smackcoders

== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

== Elements Usage ==
	
	footer : 1
		heading : 8
		icon-list : 1
		image : 2
		jet-subscribe-form : 1
		social-icons : 1
		text-editor : 5
	header : 1
		heading : 1
		icon : 1
		image : 1
		jet-mega-menu : 1
		social-icons : 1
		theme-site-logo : 1
	popup : 1
		icon : 1
		image : 1
		nav-menu : 1
	section : 3
		image : 3
		text-editor : 3
	wp-page : 6
		button : 7
		heading : 19
		icon-box : 18
		icon-list : 1
		image : 2
		image-box : 3
		jet-form-builder-form : 2
		jet-listing-grid : 2
		jet-search : 2
		shortcode : 3
		social-icons : 6
		spacer : 3
		text-editor : 5
	search-results : 1
		heading : 3
		icon-box : 4
		jet-listing-grid : 1
		jet-search : 1
		jet-smart-filters-pagination : 1
		jet-smart-filters-sorting : 1
		social-icons : 1
		text-editor : 2
	product-archive : 3
		heading : 10
		icon-box : 12
		jet-listing-grid : 4
		jet-search : 3
		jet-smart-filters-pagination : 4
		jet-smart-filters-sorting : 2
		social-icons : 3
		spacer : 2
		text-editor : 8
	jet-woo-builder-thankyou : 0
		heading : 1
		jet-thankyou-customer-address-details : 1
		jet-thankyou-order : 1
		jet-thankyou-order-details : 1
		lottie : 1
		social-icons : 1
		text-editor : 1
	jet-woo-builder-checkout : 0
		heading : 2
		jet-checkout-billing : 1
		jet-checkout-order-review : 1
		jet-checkout-payment : 2
		social-icons : 1
		woocommerce-notices : 2
	jet-woo-builder : 4
		button : 1
		heading : 2
		image : 3
		jet-listing-dynamic-field : 4
		social-icons : 1
		spacer : 1
	jet-listing-items : 0
		button : 1
		heading : 3
		image : 5
		jet-listing-dynamic-field : 12
		text-editor : 2

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Inactive
	Import Export Template Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
PHP: showing 10 of 10PHP: 2022-07-03 21:34:40 [warning X 1][/home/67809-72532.cloudwaysapps.com/cdytjksxkp/public_html/wp-content/plugins/elementor/core/common/modules/connect/module.php::230] Attempt to read property "email" on null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-05 19:05:26 [warning X 34][/home/67809-72532.cloudwaysapps.com/cdytjksxkp/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-05 19:10:04 [warning X 1][/home/67809-72532.cloudwaysapps.com/cdytjksxkp/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::167] Undefined array key "editor_post_id" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-06 06:09:48 [error X 3][/home/67809-72532.cloudwaysapps.com/cdytjksxkp/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on bool in /home/67809-72532.cloudwaysapps.com/cdytjksxkp/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /home/67809-72532.cloudwaysapps.com/cdytjksxkp/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions()
#2 /home/67809-72532.cloudwaysapps.com/cdytjksxkp/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func()
#3 /home/67809-72532.cloudwaysapps.com/cdytjksxkp/public_html/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#4 /home/67809-72532.cloudwaysapps.com/cdytjksxkp/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#5 /home/67809-72532.cloudwaysapps.com/cdytjksxkp/public_html/wp-includes/plugin.php(476): WP_Hook->do_action()
#6 /home/67809-72532.cloudwaysapps.com/cdytjksxkp/public_html/wp-admin/admin-ajax.php(187): do_action()
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-16 21:27:55 [notice X 23][/home/67809-72532.cloudwaysapps.com/cdytjksxkp/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $finder_category_name argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-16 21:28:40 [notice X 33][/home/67809-72532.cloudwaysapps.com/cdytjksxkp/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-16 21:28:49 [notice X 8][/home/67809-72532.cloudwaysapps.com/cdytjksxkp/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/67809-72532.cloudwaysapps.com/cdytjksxkp/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /home/67809-72532.cloudwaysapps.com/cdytjksxkp/public_html/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home/67809-72532.cloudwaysapps.com/cdytjksxkp/public_html/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home/67809-72532.cloudwaysapps.com/cdytjksxkp/public_html/wp-content/plugins/jet-popup/includes/integration.php(134): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-07-17 04:28:02 [warning X 1][/home/67809-72532.cloudwaysapps.com/cdytjksxkp/public_html/wp-content/plugins/elementor/core/experiments/experiments-reporter.php::89] Undefined array key "title" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-05 09:02:11 [warning X 1][/home/67809-72532.cloudwaysapps.com/cdytjksxkp/public_html/wp-content/plugins/elementor-pro/license/updater.php::84] Undefined array key "new_version" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-07 18:40:15 [warning X 3][/home/67809-72532.cloudwaysapps.com/cdytjksxkp/public_html/wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 7 of 7JS: 2022-07-07 08:37:40 [error X 3][https://wordpress-72532-2715669.cloudwaysapps.com/wp-admin/load-scripts.php?c=0&loadchunk_0=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&loadchunk_1=hooks&ver=6.0 line 2 > Function:6:7] settings.image is null 
JS: 2022-07-08 15:59:58 [error X 7][https://wordpress-72532-2715669.cloudwaysapps.com/wp-content/plugins/elementor/assets/js/common.min.js?ver=3.6.7:3:84224] C is undefined 
JS: 2022-07-08 16:02:56 [error X 1][https://wordpress-72532-2715669.cloudwaysapps.com/wp-admin/js/editor.min.js?ver=6.0:2:723] f is undefined 
JS: 2022-07-08 16:04:18 [error X 1][https://wordpress-72532-2715669.cloudwaysapps.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.7:3:280607] this.getOption(...).repeaters[this.model.get(...)] is undefined 
JS: 2022-07-17 07:06:17 [error X 1][https://wordpress-72532-2715669.cloudwaysapps.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.7:3:897946] V is null 
JS: 2022-07-19 22:28:53 [error X 1][https://wordpress-72532-2715669.cloudwaysapps.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.7:3:897948] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2022-10-07 18:47:29 [error X 1][https://www.matchticketshop.com/wp-admin/post.php?post=860&action=elementor:6:22] Cannot read properties of null (reading \'url\') 

Log: showing 11 of 112022-10-04 14:16:57 [info] elementor::elementor_updater Started 
2022-10-04 14:16:57 [info] Elementor/Upgrades - _on_each_version Start  
2022-10-04 14:16:57 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.7.8',
)]
2022-10-04 14:16:58 [info] Elementor/Upgrades - _on_each_version Finished 
2022-10-04 14:16:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.7.8',
)]
2022-10-12 06:39:17 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.2',
  'to' => '3.7.7',
)]
2022-10-12 06:39:17 [info] elementor-pro::elementor_pro_updater Started 
2022-10-12 06:39:17 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-10-12 06:39:17 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-10-12 06:39:17 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.2',
  'to' => '3.7.7',
)]
2022-10-12 06:39:18 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.2',
  'to' => '3.7.7',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible
	JetBlocks For Elementor: Incompatible
	JetElements For Elementor: Incompatible
	JetTabs For Elementor: Incompatible
	JetWooBuilder For Elementor: Incompatible

== Elementor Pro - Compatibility Tag ==
	
	JetBlocks For Elementor: Incompatible
	JetElements For Elementor: Incompatible
	JetTabs For Elementor: Incompatible
	JetWooBuilder For Elementor: Incompatible

**Comment by nicholaszein** [comment]
Hello @JorensM! 

Thank you for submitting your issue! 🙏 

Please allow us some time to investigate it, and get back to you with our findings. 🧐 

Best regards

**Comment by rami-elementor** [comment]
Hi @JorensM 

You basically need to pass data to be used in your JS.

Please read this - https://developers.elementor.com/docs/controls/frontend-available/ 

Hopefully, this Dev Doc will help you how to do that in Elementor.

**Comment by nicholaszein** [comment]
Hello @JorensM,

we haven't heard from you in a while. Did Rami's answer solve your issue?

Please let us know.

**Comment by JorensM** [comment]
@nicholaszein No it did not solve the issue. I have to specifically pass the PHP variables in the widget's render function. By the way, besides throwing an error within <script> tags, sometimes the error occurs when I try to echo the variable within regular HTML. 
For example
`<span> <?php echo $variable?> </span>`. I receive an error when the render function contains solely the above code.

**Comment by rami-elementor** [comment]
> `<span> <?php echo $variable?> </span>`. I receive an error when the render function contains solely the above code.

It should not return an error.

```
protected function render() {
	$val = 'No Problem here';
	?>
	<div>
		<span> <?php echo $val; ?> </span>
	</div>
	<?php
}
```

This is a valid code.

**Comment by JorensM** [comment]
@rami-elementor But for some reason it does. The error occurs in the Elementor editor (Internal Server Error) when trying to save the page.

**Comment by rami-elementor** [comment]
@JorensM You probably have some other error on your page. Can you paste the entire code?

**Comment by JorensM** [comment]
Here I found a similar issue #13499

**Comment by rami-elementor** [comment]
@JorensM Can you activate the WordPress debug and paste the error here?

**Comment by JorensM** [comment]
@rami-elementor I tried enabling WP_DEBUG but no errors are shown.
