### ISSUE TITLE
Beta 5 Causing Layout Issues

### ISSUE THREAD

**Issue by donwattz1459** [elementor/elementor#20100]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hmmm. I updated from the stable version to this beta to see if the z-index issue is fixed, but it looks way wonky on one of my development sites: https://abners.wpdevurl.com/

I have regenrated the CSS and files, and cleared cache. Went in to make adjustments, and some of the settings won't work like align items and element gap. This is all using flex containers too.

### Steps to reproduce

Updated from stable to the newest beta 4.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.16.1
	MySQL version: mariadb.org binary distribution v10.5.4
	PHP Version: 7.4.8
	PHP Memory Limit: 256M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.3
	Site URL: https://abners.wpdevurl.com
	Home URL: https://abners.wpdevurl.com
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/New_York
	Admin Email: info@wattzwebdesign.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.6.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15

== Active Plugins ==
	Elementor
		Version: 3.8.0-beta5
		Author: Elementor.com

	Elementor Pro
		Version: 3.8.0-beta5
		Author: Elementor.com

== Must-Use Plugins ==
	WP CLI Login Command Server
		Version: 1.3
		Author: Evan Mattson

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Import Export Website Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Inactive by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 20 of 402022-09-22 12:35:32 [info] elementor::elementor_updater Started 
2022-09-22 12:35:32 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-09-22 12:35:32 [info] Elementor/Upgrades - _on_each_version Start  
2022-09-22 12:35:32 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.5',
  'to' => '3.7.7',
)]
2022-09-22 12:35:32 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.4',
  'to' => '3.7.7',
)]
2022-10-10 12:04:56 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.7',
  'to' => '3.7.8',
)]
2022-10-10 12:04:57 [info] elementor::elementor_updater Started 
2022-10-10 12:04:57 [info] Elementor/Upgrades - _on_each_version Start  
2022-10-10 12:04:57 [info] Elementor/Upgrades - _on_each_version Finished 
2022-10-10 12:04:57 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.7',
  'to' => '3.7.8',
)]
2022-10-10 12:04:57 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.7',
  'to' => '3.7.8',
)]
2022-10-20 15:05:04 [info] elementor-pro::elementor_pro_updater Started 
2022-10-20 15:05:04 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-10-20 15:05:04 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-10-20 15:05:04 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.8.0-beta5',
)]
2022-10-20 15:05:04 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.8.0-beta5',
)]
2022-10-20 15:06:06 [info] elementor::elementor_updater Started 
2022-10-20 15:06:06 [info] Elementor/Upgrades - _on_each_version Start  
2022-10-20 15:06:06 [info] Elementor/Upgrades - _on_each_version Finished 
2022-10-20 15:06:06 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.8',
  'to' => '3.8.0-beta5',
)]

PHP: showing 3 of 3PHP: 2022-09-01 12:41:25 [error X 1][/var/www/abners.wpdevurl.com/htdocs/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on null in /var/www/abners.wpdevurl.com/htdocs/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /var/www/abners.wpdevurl.com/htdocs/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions()
#2 /var/www/abners.wpdevurl.com/htdocs/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func()
#3 /var/www/abners.wpdevurl.com/htdocs/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#4 /var/www/abners.wpdevurl.com/htdocs/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#5 /var/www/abners.wpdevurl.com/htdocs/wp-includes/plugin.php(476): WP_Hook->do_action()
#6 /var/www/abners.wpdevurl [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-10 12:23:50 [error X 1][/var/www/abners.wpdevurl.com/htdocs/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on bool in /var/www/abners.wpdevurl.com/htdocs/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /var/www/abners.wpdevurl.com/htdocs/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions()
#2 /var/www/abners.wpdevurl.com/htdocs/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func()
#3 /var/www/abners.wpdevurl.com/htdocs/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#4 /var/www/abners.wpdevurl.com/htdocs/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#5 /var/www/abners.wpdevurl.com/htdocs/wp-includes/plugin.php(476): WP_Hook->do_action()
#6 /var/www/abners.wpdevurl [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-10 12:25:14 [notice X 1][/var/www/abners.wpdevurl.com/htdocs/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Incompatible

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @donwattz1459! 

Thank you for submitting your issue! 🙏 

Can you show a screenshot of the settings of the container with the problem? And how the page looks vs how it should look?

It seems everything is appearing ok for me.

![image](https://user-images.githubusercontent.com/113993460/197614221-caff7359-159c-41e0-9ee6-df960a1d5661.png)

Best regards

**Comment by donwattz1459** [comment]
I had to restore to a backup.

**Comment by nicholaszein** [comment]
@donwattz1459,

it would be great if we knew how to reproduce your issue and check the container settings, or a video of you trying to edit after the update. Otherwise, we can't help.
