### ISSUE TITLE
In-page scroll menus - button active state not applied correctly if there are sections with lazy loading

### ISSUE THREAD

**Issue by mateitudor** [elementor/elementor#20217]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

If the page has lazy loading components (galleries, listings, etc.), the in-page #anchor navigation doesn't apply the correct "active" state to the menu items corresponding to the section that is in the viewport.

The menu is wrapped in a sticky container.
it's a default menu component based on the WP menu, with #anchors as custom links.

What should happen:
The scroll listening / calculation should take lazy loading into account, or the system should use a newer method like intersectionObserver.

Versions:
Happens at least since 3.7, confirmed on the latest 3.9 beta.

Thanks!

### Steps to reproduce

How to reproduce:

1. Create a regular WP menu with custom links that are anchors. e.g.: #about, #team, etc. — it's more evident the more sections you have;
2. Create an Elementor page with those sections;
3. Create a sticky section with the anchor menu (default, at the top of the page);
4. Make the active state of the menu items something clearly visible, for easier testing;
5. Add components with lazy loading inside those sections. e.g. gallery, listings, etc.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Darwin
	Software: nginx/1.16.0
	MySQL version: MySQL Community Server - GPL v8.0.16
	PHP Version: 8.1.9
	PHP Memory Limit: 256M
	PHP Max Input Vars: 4000
	PHP Max Post Size: 1000M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.3
	Site URL: https://v2.beyond-va.local
	Home URL: https://v2.beyond-va.local
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Europe/Bucharest
	Admin Email: mateitudor@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Beyond VA
	Version: 2.0.4
	Author: Tudor Matei
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.6.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36

== Active Plugins ==
	Change wp-admin login
		Version: 1.1.0
		Author: Nuno Morais Sarmento

	Custom Post Type Permalinks
		Version: 3.4.5
		Author: Toro_Unit

	Elementor
		Version: 3.9.0-dev4
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.9.0-dev5
		Author: Elementor.com

	JetElements For Elementor
		Version: 2.6.7
		Author: Crocoblock

	JetEngine
		Version: 3.0.6
		Author: Crocoblock

	Jetpack
		Version: 11.5
		Author: Automattic

	JetPopup
		Version: 1.6.2
		Author: Crocoblock

	JetSmartFilters
		Version: 3.0.0
		Author: Crocoblock

	Nested Pages
		Version: 3.2.1
		Author: Kyle Phillips

	Performance Lab
		Version: 1.6.0
		Author: WordPress Performance Team

	Qi Addons For Elementor
		Version: 1.5.4
		Author: Qode Interactive

	Qi Addons For Elementor Premium
		Version: 1.0.2
		Author: Qode Interactive

	Rank Math SEO
		Version: 1.0.100.1
		Author: Rank Math

	Rank Math SEO PRO
		Version: 3.0.22
		Author: Rank Math

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Active
	Import Export Website Kit: Active by default
	Hide native WordPress widgets from search results: Inactive
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Inactive
	Hello Theme Header & Footer: Inactive
	Landing Pages: Inactive
	Color Sampler: Inactive
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Lazy Load Background Images: Inactive
	Page Transitions: Inactive
	Notes: Inactive
	Loop: Active by default
	Form Submissions: Active
	Scroll Snap: Inactive

== Log ==
	
JS: showing 17 of 17JS: 2022-10-10 17:16:09 [error X 1][http://v2.beyond-va.local/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view4864\") has already been destroyed and cannot be used. 
JS: 2022-10-10 17:16:09 [error X 1][http://v2.beyond-va.local/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view4793\") has already been destroyed and cannot be used. 
JS: 2022-10-12 08:37:43 [error X 4][http://v2.beyond-va.local/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.9.0-dev2:3:649121] this.model.isValidChild is not a function 
JS: 2022-10-12 14:35:58 [error X 1][http://v2.beyond-va.local/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.9.0-dev2:3:540581] Blocked a frame with origin \"http://v2.beyond-va.local\" from accessing a cross-origin frame. 
JS: 2022-10-12 15:27:21 [error X 7][http://v2.beyond-va.local/wp-content/plugins/elementor-pro/assets/lib/sticky/jquery.sticky.min.js?ver=3.9.0-dev2:1:1410] Failed to execute \'getComputedStyle\' on \'Window\': parameter 1 is not of type \'Element\'. 
JS: 2022-10-12 17:15:25 [error X 1][https://v2.beyond-va.local/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=3.9.0-dev2:2:19333] this.$element.sticky is not a function 
JS: 2022-10-12 23:25:34 [error X 8][https://v2.beyond-va.local/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.9.0-dev2:3:769410] Cannot read properties of undefined (reading \'localized\') 
JS: 2022-10-13 04:16:27 [error X 1][https://beyond-va.mateitudor.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view2540\") has already been destroyed and cannot be used. 
JS: 2022-10-13 04:16:27 [error X 1][https://beyond-va.mateitudor.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view2467\") has already been destroyed and cannot be used. 
JS: 2022-10-16 23:23:16 [error X 1][https://v2.beyond-va.local/wp-content/plugins/elementor/assets/js/common.min.js?ver=3.9.0-dev2:3:83961] Cannot read properties of undefined (reading \'channel\') 
JS: 2022-10-18 11:52:46 [error X 1][https://v2.beyond-va.local/wp-content/themes/beyond-va/assets/js/prod/mastheads-min.js?ver=1.0:1:260] Cannot read properties of null (reading \'scrollWidth\') 
JS: 2022-10-20 06:34:57 [error X 25][https://v2.beyond-va.local/wp-content/themes/beyond-va/assets/js/prod/mastheads-min.js?ver=1.0:1:317] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2022-10-24 00:50:31 [error X 4][https://v2.beyond-va.local/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.9.0-dev4:2:60518] Cannot convert undefined or null to object 
JS: 2022-10-30 23:39:39 [error X 1][https://v2.beyond-va.local/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.9.0-dev4:3:649137] this.model.isValidChild is not a function. (In \'this.model.isValidChild(C)\', \'this.model.isValidChild\' is undefined) 
JS: 2022-10-31 00:48:24 [error X 5][https://v2.beyond-va.local/wp-content/themes/beyond-va/assets/js/prod/mastheads-min.js?ver=1.0:1:316] null is not an object (evaluating \'e.getBoundingClientRect\') 
JS: 2022-10-31 09:56:38 [error X 1][https://v2.beyond-va.local/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=3.9.0-dev5:2:19472] this.$element.sticky is not a function. (In \'this.$element.sticky(this.currentConfig)\', \'this.$element.sticky\' is undefined) 
JS: 2022-10-31 22:14:49 [error X 3][https://v2.beyond-va.local/wp-content/plugins/elementor-pro/assets/js/gallery.9c61bb9957e10e6d7bda.bundle.min.js:2:5599] Cannot read properties of undefined (reading \'setSettings\') 

PHP: showing 6 of 6PHP: 2022-10-12 18:52:44 [notice X 17][/Users/mateitudor/Studio/Code/Sites/beyond-va-v2/app/public/wp-content/plugins/elementor/modules/performance-lab/module.php::31] Optional parameter $size declared before required parameter $url is implicitly treated as a required parameter [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-13 04:28:28 [warning X 13][/Users/mateitudor/Studio/Code/Sites/beyond-va-v2/app/public/wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-13 07:23:45 [warning X 1][/domains/mateitudor.com/beyond-va/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-20 17:40:29 [error X 1][/Users/mateitudor/Studio/Code/Sites/beyond-va-v2/app/public/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on null in /Users/mateitudor/Studio/Code/Sites/beyond-va-v2/app/public/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /Users/mateitudor/Studio/Code/Sites/beyond-va-v2/app/public/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(19313, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /Users/mateitudor/Studio/Code/Sites/beyond-va-v2/app/public/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /Users/mateitudor/Studio/Code/Sites/beyond-va-v2/app/public/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /Users/mateitudor/Studio/Code/Sites/beyond-va-v2/app/public/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#5 /Users/mateitudor/Studio/Code/Sites/beyond-va-v2/app/public/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#6 /Users/mateitudor/Studio/Code/Sites/beyond-va-v2/app/public/wp-admin/admin-ajax.php(187): do_action('wp_ajax_element...')
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-20 17:41:49 [error X 1][/Users/mateitudor/Studio/Code/Sites/beyond-va-v2/app/public/wp-content/plugins/elementor/includes/managers/widgets.php::408] Uncaught Error: Call to a member function is_editable_by_current_user() on bool in /Users/mateitudor/Studio/Code/Sites/beyond-va-v2/app/public/wp-content/plugins/elementor/includes/managers/widgets.php:408
Stack trace:
#0 [internal function]: Elementor\Widgets_Manager->ajax_render_widget(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#1 /Users/mateitudor/Studio/Code/Sites/beyond-va-v2/app/public/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /Users/mateitudor/Studio/Code/Sites/beyond-va-v2/app/public/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#3 /Users/mateitudor/Studio/Code/Sites/beyond-va-v2/app/public/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#4 /Users/mateitudor/Studio/Code/Sites/beyond-va-v2/app/public/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#5 /Users/mateitudor/Studio/Code/Sites/beyond-va-v2/app/public/wp-admin/admin-ajax.php(187): do_action('wp_ajax_element...')
#6 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-31 00:52:19 [notice X 247][/Users/mateitudor/Studio/Code/Sites/beyond-va-v2/app/public/wp-content/plugins/elementor-pro/modules/custom-css/module.php::76] trim(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 19 of 192022-10-24 02:45:48 [info] elementor-pro::elementor_pro_updater Started 
2022-10-24 02:45:49 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-10-24 02:45:49 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-10-24 02:45:49 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.0-dev2',
  'to' => '3.9.0-dev4',
)]
2022-10-24 02:45:49 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.0-dev2',
  'to' => '3.9.0-dev4',
)]
2022-10-24 02:58:27 [info] elementor::elementor_updater Started 
2022-10-24 02:58:27 [info] Elementor/Upgrades - _on_each_version Start  
2022-10-24 02:58:27 [info] Elementor/Upgrades - _on_each_version Finished 
2022-10-24 02:58:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0-dev2',
  'to' => '3.9.0-dev3',
)]
2022-10-27 16:56:28 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0-dev3',
  'to' => '3.9.0-dev4',
)]
2022-10-27 16:56:28 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.0-dev4',
  'to' => '3.9.0-dev5',
)]
2022-10-27 16:56:29 [info] elementor::elementor_updater Started 
2022-10-27 16:56:29 [info] Elementor/Upgrades - _on_each_version Start  
2022-10-27 16:56:29 [info] Elementor/Upgrades - _on_each_version Finished 
2022-10-27 16:56:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0-dev3',
  'to' => '3.9.0-dev4',
)]
2022-10-27 16:56:29 [info] elementor-pro::elementor_pro_updater Started 
2022-10-27 16:56:29 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-10-27 16:56:29 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-10-27 16:56:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.0-dev4',
  'to' => '3.9.0-dev5',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Incompatible
	JetElements For Elementor: Incompatible
	Qi Addons For Elementor: Incompatible
	Qi Addons For Elementor Premium: Incompatible

== Elementor Pro - Compatibility Tag ==
	
	JetElements For Elementor: Incompatible
	Qi Addons For Elementor: Incompatible
	Qi Addons For Elementor Premium: Incompatible

**Comment by nicholaszein** [comment]
Hello @mateitudor! 

Thank you for submitting your detailed report! We appreciate it very much! 🙏 

Please allow us some time to investigate it, and get back to you with our findings. 🧐 

Best regards

**Comment by nicholaszein** [comment]
Hello @mateitudor! 

Just giving an update. I was able to reproduce your issue, and have already labeled it to help our team track it in the future.

Best regards

**Comment by mateitudor** [comment]
Thank you so much @nicholaszein! You're amazing.

**Comment by pedrowoobik** [comment]
Here the same problem... By the moment the solution was using the plugin Page Scroll to id.
Maybe recalculate on each click on link would be better because nowadays pages changes on the fly.. I personally insert new sections from library when the user is scrolling down first time.
By the way, elementor is the best right now :D
