### ISSUE TITLE
⛔ Bug Report: PODS integration not compatible with plain text (repeatable) field

### ISSUE THREAD

**Issue by jamieburchell** [elementor/elementor#20275]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When adding a plain text (repeatable) PODS field as a dynamic tag, a PHP exception is thrown:

```
[02-Nov-2022 12:10:43 UTC] PHP Fatal error:  Uncaught TypeError: preg_match(): Argument #2 ($subject) must be of type string, array given in /var/www/web/wp/wp-includes/class-wp-block-parser.php:417
Stack trace:
#0 /var/www/web/wp/wp-includes/class-wp-block-parser.php(417): preg_match('/<!--\\s+(?P<clo...', Array, NULL, 256, 0)
#1 /var/www/web/wp/wp-includes/class-wp-block-parser.php(256): WP_Block_Parser->next_token()
#2 /var/www/web/wp/wp-includes/class-wp-block-parser.php(236): WP_Block_Parser->proceed()
#3 /var/www/web/wp/wp-includes/blocks.php(924): WP_Block_Parser->parse(Array)
#4 /var/www/web/wp/wp-includes/blocks.php(650): parse_blocks(Array)
#5 /var/www/web/wp/wp-includes/formatting.php(5088): filter_block_content(Array, 'post', Array)
#6 /var/www/web/wp/wp-includes/class-wp-hook.php(307): wp_pre_kses_block_attributes(Array, 'post', Array)
#7 /var/www/web/wp/wp-includes/plugin.php(191): WP_Hook->apply_filters(Array, Array)
#8 /var/www/web/wp/wp-includes/kses.php(909): apply_filters('pre_kses', Array, 'post', Array)
#9 /var/www/web/wp/wp-includes/kses.php(719): wp_kses_hook(Array, 'post', Array)
#10 /var/www/web/wp/wp-includes/kses.php(2106): wp_kses(Array, 'post')
#11 /var/www/web/app/plugins/elementor-pro/modules/dynamic-tags/pods/tags/pods-text.php(37): wp_kses_post(Array)
#12 /var/www/web/app/plugins/elementor/core/dynamic-tags/tag.php(35): ElementorPro\Modules\DynamicTags\Pods\Tags\Pods_Text->render()
#13 /var/www/web/app/plugins/elementor/core/dynamic-tags/manager.php(216): Elementor\Core\DynamicTags\Tag->get_content()
#14 [internal function]: Elementor\Core\DynamicTags\Manager->get_tag_data_content('f70e4e9', 'pods-text', Array)
#15 /var/www/web/app/plugins/elementor/core/dynamic-tags/manager.php(109): call_user_func_array(Array, Array)
#16 /var/www/web/app/plugins/elementor/core/dynamic-tags/manager.php(74): Elementor\Core\DynamicTags\Manager->parse_tag_text('[elementor-tag ...', Array, Array)
#17 [internal function]: Elementor\Core\DynamicTags\Manager->Elementor\Core\DynamicTags\{closure}(Array)
#18 /var/www/web/app/plugins/elementor/core/dynamic-tags/manager.php(73): preg_replace_callback('/\\[elementor-ta...', Object(Closure), '[elementor-tag ...')
#19 /var/www/web/app/plugins/elementor/includes/controls/base-data.php(91): Elementor\Core\DynamicTags\Manager->parse_tags_text('[elementor-tag ...', Array, Array)
#20 /var/www/web/app/plugins/elementor/includes/base/controls-stack.php(1274): Elementor\Base_Data_Control->parse_tags('[elementor-tag ...', Array)
#21 /var/www/web/app/plugins/elementor/includes/base/controls-stack.php(1125): Elementor\Controls_Stack->parse_dynamic_settings(Array)
#22 /var/www/web/app/plugins/elementor/core/files/css/post.php(298): Elementor\Controls_Stack->get_parsed_dynamic_settings()
#23 /var/www/web/app/plugins/elementor/core/files/css/post.php(226): Elementor\Core\Files\CSS\Post->render_styles(Object(Elementor\Widget_Icon_Box))
#24 /var/www/web/app/plugins/elementor/core/files/css/post.php(298): Elementor\Core\Files\CSS\Post->add_controls_stack_style_rules(Object(Elementor\Element_Column), Array, Array, Array, Array)
#25 /var/www/web/app/plugins/elementor/core/files/css/post.php(226): Elementor\Core\Files\CSS\Post->render_styles(Object(Elementor\Element_Column))
#26 /var/www/web/app/plugins/elementor/core/files/css/post.php(298): Elementor\Core\Files\CSS\Post->add_controls_stack_style_rules(Object(Elementor\Element_Section), Array, Array, Array, Array)
#27 /var/www/web/app/plugins/elementor/core/files/css/post.php(226): Elementor\Core\Files\CSS\Post->render_styles(Object(Elementor\Element_Section))
#28 /var/www/web/app/plugins/elementor/core/files/css/post.php(298): Elementor\Core\Files\CSS\Post->add_controls_stack_style_rules(Object(Elementor\Element_Column), Array, Array, Array, Array)
#29 /var/www/web/app/plugins/elementor/core/files/css/post.php(226): Elementor\Core\Files\CSS\Post->render_styles(Object(Elementor\Element_Column))
#30 /var/www/web/app/plugins/elementor/core/files/css/post.php(298): Elementor\Core\Files\CSS\Post->add_controls_stack_style_rules(Object(Elementor\Element_Section), Array, Array, Array, Array)
#31 /var/www/web/app/plugins/elementor/core/files/css/post.php(178): Elementor\Core\Files\CSS\Post->render_styles(Object(Elementor\Element_Section))
#32 /var/www/web/app/plugins/elementor/core/files/css/base.php(643): Elementor\Core\Files\CSS\Post->render_css()
#33 /var/www/web/app/plugins/elementor/core/files/base.php(180): Elementor\Core\Files\CSS\Base->parse_content()
#34 /var/www/web/app/plugins/elementor/core/files/css/base.php(130): Elementor\Core\Files\Base->update_file()
#35 /var/www/web/app/plugins/elementor/core/files/css/base.php(217): Elementor\Core\Files\CSS\Base->update()
#36 /var/www/web/app/plugins/elementor/core/files/css/post.php(201): Elementor\Core\Files\CSS\Base->enqueue()
#37 /var/www/web/app/plugins/elementor-pro/modules/theme-builder/classes/locations-manager.php(93): Elementor\Core\Files\CSS\Post->enqueue()
#38 /var/www/web/wp/wp-includes/class-wp-hook.php(307): ElementorPro\Modules\ThemeBuilder\Classes\Locations_Manager->enqueue_styles('')
#39 /var/www/web/wp/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#40 /var/www/web/wp/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#41 /var/www/web/wp/wp-includes/script-loader.php(2156): do_action('wp_enqueue_scri...')
#42 /var/www/web/wp/wp-includes/class-wp-hook.php(307): wp_enqueue_scripts('')
#43 /var/www/web/wp/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#44 /var/www/web/wp/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#45 /var/www/web/wp/wp-includes/general-template.php(3042): do_action('wp_head')
#46 /var/www/web/app/themes/hello-elementor/header.php(21): wp_head()
#47 /var/www/web/wp/wp-includes/template.php(770): require_once('/var/www/vhosts...')
#48 /var/www/web/wp/wp-includes/template.php(716): load_template('/var/www/vhosts...', true, Array)
#49 /var/www/web/wp/wp-includes/general-template.php(48): locate_template(Array, true, true, Array)
#50 /var/www/web/app/themes/hello-elementor/index.php(15): get_header()
#51 /var/www/web/wp/wp-includes/template-loader.php(106): include('/var/www/vhosts...')
#52 /var/www/web/wp/wp-blog-header.php(19): require_once('/var/www/vhosts...')
#53 /var/www/web/index.php(6): require('/var/www/vhosts...')
#54 {main}
  thrown in /var/www/web/wp/wp-includes/class-wp-block-parser.php on line 417
```

The expected behaviour is this would output the field according to the display format options set against the field in PODS.

A workaround is to add a shortcode which references the field instead.

### Steps to reproduce

1. Create a new field with type Plain Text and set its options as repeatable
2. Add some items to the field
3. Choose the field in any Elementor control where a dynamic tag is permitted

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

```
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.5.16
	PHP Version: 8.0.25
	PHP Memory Limit: 256M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 50M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: There are some writing permissions issues with the following directories/files:
		 - WordPress root directory
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.3
	Site URL: https://example.com/wp
	Home URL: https://example.com
	WP Multisite: No
	Max Upload Size: 40 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-GB
	Timezone: 0
	Admin Email: admin@example.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36

== Active Plugins ==
	Cache Enabler
		Version: 1.8.12
		Author: KeyCDN

	Code Snippets
		Version: 3.2.1
		Author: Code Snippets Pro

	Converter for Media
		Version: 5.3.1
		Author: Image Optimization Team by matt plugins

	Dynamic.ooo - Dynamic Content for Elementor
		Version: 2.8.0
		Author: Dynamic.ooo

	Elementor
		Version: 3.7.8
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.7
		Author: Elementor.com

	Pods - Custom Content Types and Fields
		Version: 2.9.9
		Author: Pods Framework Team

	Rank Math SEO
		Version: 1.0.100.1
		Author: Rank Math

	Wordfence Security
		Version: 7.7.1
		Author: Wordfence


== Must-Use Plugins ==
	Bedrock Autoloader
		Version: 1.0.3
		Author: Roots

	Disable status tests
		Version: 1.0.0
		Author: Roots

	Register Theme Directory
		Version: 1.0.0
		Author: Roots


== Elementor Experiments ==
	Optimised DOM Output: Active
	Improved asset loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility improvements: Active
	Additional Custom Breakpoints: Inactive by default
	Import Export Template Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Inactive by default
	Landing pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default


== Log ==
	
Log: showing 20 of 312022-09-16 08:47:27 [info] elementor::elementor_updater Started 
2022-09-16 08:47:27 [info] Elementor/Upgrades - _on_each_version Start  
2022-09-16 08:47:27 [info] Elementor/Upgrades - _on_each_version Finished 
2022-09-16 08:47:28 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.4',
  'to' => '3.7.6',
)]
2022-10-03 09:02:54 [info] Update DB has been started [array (
  'plugin' => 'Elementor',
  'from' => '3.7.6',
  'to' => '3.7.8',
)]
2022-10-03 09:02:54 [info] elementor::elementor_updater Started 
2022-10-03 09:02:54 [info] Elementor/Upgrades - _on_each_version Start  
2022-10-03 09:02:54 [info] Elementor/Upgrades - _on_each_version Finished 
2022-10-03 09:02:54 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.6',
  'to' => '3.7.8',
)]
2022-10-03 09:02:57 [info] Update DB has been started [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.6',
  'to' => '3.7.7',
)]
2022-10-03 09:02:57 [info] elementor-pro::elementor_pro_updater Started 
2022-10-03 09:02:57 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-10-03 09:02:57 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-10-03 09:02:57 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.6',
  'to' => '3.7.7',
)]
2022-10-03 09:07:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Dynamic.ooo - Dynamic Content for Elementor',
  'from' => '2.7.9',
  'to' => '2.7.10',
)]
2022-11-01 12:27:42 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Dynamic.ooo - Dynamic Content for Elementor',
  'from' => '2.7.10',
  'to' => '2.8.0',
)]
2022-11-01 12:30:02 [info] dynamic-content-for-elementor::dce_updater Started 
2022-11-01 12:30:02 [info] Dynamic.ooo - Dynamic Content for Elementor/Upgrades - _v_2_8_0_conditional_validation_join_lines Start  
2022-11-01 12:30:02 [info] Dynamic.ooo - Dynamic Content for Elementor/Upgrades - _v_2_8_0_conditional_validation_join_lines Finished 
2022-11-01 12:30:02 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Dynamic.ooo - Dynamic Content for Elementor',
  'from' => '2.7.10',
  'to' => '2.8.0',
)]

PHP: showing 8 of 8PHP: 2022-09-12 08:52:28 [warning X 238][/var/www/web/app/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-12 09:50:44 [warning X 29][/var/www/web/app/plugins/elementor/includes/managers/image.php::105] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-12 14:32:52 [error X 1][/var/www/web/app/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on null in /var/www/web/app/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /var/www/web/app/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(5, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /var/www/web/app/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /var/www/web/wp/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /var/www/web/wp/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#5 /var/www/web/wp/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#6 /var/www/web/wp/wp-admin/admin-ajax.php(187): do_action('wp_ajax_element...')
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-21 14:10:53 [warning X 2][/var/www/web/app/plugins/elementor-pro/modules/dynamic-tags/pods/tags/pods-base.php::35] Undefined array key "quotation" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-19 17:14:10 [error X 3][/var/www/web/app/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on null in /var/www/web/app/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /var/www/web/app/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(5, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /var/www/web/app/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /var/www/web/wp/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /var/www/web/wp/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#5 /var/www/web/wp/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#6 /var/www/web/wp/wp-admin/admin-ajax.php(187): do_action('wp_ajax_element...')
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-20 11:12:23 [error X 2][/var/www/web/app/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on bool in /var/www/web/app/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /var/www/web/app/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /var/www/web/app/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /var/www/web/wp/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /var/www/web/wp/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#5 /var/www/web/wp/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#6 /var/www/web/wp/wp-admin/admin-ajax.php(187): do_action('wp_ajax_element...')
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-01 13:17:18 [error X 7][/var/www/web/app/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on bool in /var/www/web/app/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /var/www/web/app/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /var/www/web/app/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /var/www/web/wp/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /var/www/web/wp/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#5 /var/www/web/wp/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#6 /var/www/web/wp/wp-admin/admin-ajax.php(187): do_action('wp_ajax_element...')
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-02 10:47:31 [error X 1][/var/www/web/app/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on null in /var/www/web/app/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /var/www/web/app/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(5, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /var/www/web/app/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /var/www/web/wp/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /var/www/web/wp/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#5 /var/www/web/wp/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#6 /var/www/web/wp/wp-admin/admin-ajax.php(187): do_action('wp_ajax_element...')
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 3 of 3JS: 2022-09-14 08:54:47 [error X 1][https://example.com/app/plugins/elementor/assets/js/editor.min.js?ver=3.7.4:3:693613] this.manager.setPage(...).showView is not a function 
JS: 2022-09-28 08:54:29 [error X 1][https://example.com/app/plugins/elementor/assets/js/editor.min.js?ver=3.7.6:3:1060720] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2022-11-01 13:33:06 [error X 1][https://example.com/app/plugins/elementor/assets/js/editor.min.js?ver=3.7.8:3:294654] Cannot read properties of undefined (reading \'html\') 



== Elementor - Compatibility Tag ==
	
	Dynamic.ooo - Dynamic Content for Elementor: Compatible
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==
	
	Dynamic.ooo - Dynamic Content for Elementor: Compatible
```

**Comment by nicholaszein** [comment]
Hello @jamieburchell,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue we can fix at this moment. Here's why:
* Elementor Pro does not support repeater/repeatable fields natively from any 3rd party plugin (PODS, ACF, Metabox, etc.).
* We have no plans for the time being to add compatibility to repeatable fields.

### ✅ What you can do to solve your issue:
* Use a shortcode as you suggested.
* Read our documentation to be more informed about what types of fields Elementor supports [here](https://elementor.com/help/elementor-integration-with-pods/).
* Read our documentation to learn more about which widgets support PODS fields [here](https://elementor.com/help/which-widgets-support-acf-and-pods-custom-fields/).

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* Please create GitHub issues **only for Elementor bugs**. GitHub issues ARE NOT FOR SUPPORT or for issues with 3rd party plugins.
* Read our documentation before submitting your issue.
* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

### ⚠️ Please Note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards

**Comment by jamieburchell** [comment]
Thanks @nicholaszein. If PODS can output repeatable fields as a single formatted string like the shortcode does, why couldn't the PODS integration do the same - even if it's just passing through and outputting the shortcode directly? I'm not expecting Elementor to have logic to format the array in a particular way, since this is already defined in PODS.

**Comment by nicholaszein** [comment]
Hey @jamieburchell,

I'm not sure if I follow. What do you mean? Are you using a `PODs` dynamic-tag to output the value, or are you using a `Shortcode` dynamic-tag? These are two different things.

### ⚠️ <ins>**Elementor doesn't support repeatable fields.**</ins> 

So they won't work if you use them with the PODs integration with dynamic-tags. But you might be successful if you try to create a shortcode that outputs the repeatable field values. Did you try that?

**Comment by jamieburchell** [comment]
Hey @nicholaszein

The only way I could get this to work was to select "Shortcode" for the dynamic tag and enter `[pods field="my_repeater_field"]`. This then outputs the content as configured in PODS perfectly. I expected the same to work when choosing the PODS field directly as a dynamic tag, but it crashes. So I'm curious why instead of crashing it couldn't just do the shortcode `[pods field="my_repeater_field"]`.

**Comment by nicholaszein** [comment]
@jamieburchell,

because when Elementor integrates with PODs, it does not use shortcodes to do the integration. It's not that simple. There are cases where only the output would suffice, but there are other cases that would require more work to implement. So for now, Elementor does not support repeatable fields.

**Comment by jamieburchell** [comment]
@nicholaszein Fair enough. I'm only talking about my specific case rather than a full blown integration, where it seems just calling 
 the shortcode would suffice. I understand by implementing that, you can no longer say you don't support repeatable fields and I guess that leaves you open to more people asking for other more complicated integrations.

**Comment by nicholaszein** [comment]
@jamieburchell,

we would prefer to implement this correctly instead of replacing it with a shortcode since this would be more of an unfinished hack than something users could have more control. Not to mention the shortcode doesn't work in all cases, and calling shortcodes is not the optimal way, it does take a toll on performance.

If you wish to participate in the discussion to add this feature, please add your +1 on issue #5979.

Kind regards 😉
