### ISSUE TITLE
✅ 🐞 Bug Report: Pop-up Display Conditions are missing after updating from Elementor v3.7.7 to v3.8

### ISSUE THREAD

**Issue by davidefiorio** [elementor/elementor#20379]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

From 3.7.7 to 3.8

Pop-up: disappear content of pop-up.
Downgrading to 3.7.7, all works.

Pop-up activation is "on click" over an icon (burger menu appear/disappear)

I use Hello theme.

Pease verify.

### Steps to reproduce

Create a pop-up.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

<details>
<summary>Click to reveal</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: mariadb.org binary distribution v10.4.21
	PHP Version: 8.0.24
	PHP Memory Limit: 512M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 300M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1
	Site URL: https://www.francescaweddinglab.com
	Home URL: https://www.francescaweddinglab.com
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 640M
	Max Memory limit: 640M
	Permalink Structure: /%category%/%postname%/
	Language: it-IT
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.6.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: it_IT
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36

== Active Plugins ==
	Anti-Spam by CleanTalk
		Version: 5.188
		Author: СleanTalk <welcome@cleantalk.org>

	CAOS
		Version: 4.4.5
		Author: Daan from Daan.dev

	Complianz | GDPR/CCPA Cookie Consent
		Version: 6.3.5
		Author: Really Simple Plugins

	Disable Emojis
		Version: 1.2.0
		Author: LittleBizzy

	Duplicator Pro
		Version: 4.5.8.1
		Author: Snap Creek

	Elementor
		Version: 3.8.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.7
		Author: Elementor.com

	Folders
		Version: 2.8.7
		Author: Premio

	Freesoul Deactivate Plugins
		Version: 1.9.3.3
		Author: Jose Mortellaro

	iThemes Security
		Version: 8.1.3
		Author: iThemes

	Maintenance
		Version: 4.06
		Author: WebFactory Ltd

	ManageWP - Worker
		Version: 4.9.15
		Author: GoDaddy

	OMGF
		Version: 5.4.3
		Author: Daan from Daan.dev

	Rank Math SEO
		Version: 1.0.101
		Author: Rank Math

	Rank Math SEO PRO
		Version: 3.0.23
		Author: Rank Math

	Simple Custom Post Order
		Version: 2.5.6
		Author: Colorlib

	TinyPNG - JPEG, PNG & WebP image compression
		Version: 3.4.1
		Author: TinyPNG

	WebP Express
		Version: 0.25.5
		Author: Bjørn Rosell

	WPML Media
		Version: 2.7.1
		Author: OnTheGoSystems

	WPML Multilingual CMS
		Version: 4.5.13
		Author: OnTheGoSystems

	WPML String Translation
		Version: 3.2.3
		Author: OnTheGoSystems

	WP Rocket
		Version: 3.12.2.1
		Author: WP Media

	Yoast Duplicate Post
		Version: 4.5
		Author: Enrico Battocchi & Team Yoast


== Must-Use Plugins ==
	freesoul deactivate plugins [fdp]
		Version: 1.9.3.3
		Author: Jose Mortellaro

	ManageWP - Worker Loader
		Version: 1.0.0
		Author: GoDaddy


== Utilizzo degli elementi ==
	
	footer : 3
		divider : 3
		heading : 2
		icon-list : 3
		spacer : 3
		text-editor : 4
	header : 12
		divider : 4
		icon : 4
		image : 4
	popup : 6
		form : 1
		heading : 1
		icon-list : 1
		image : 1
		nav-menu : 1
	wp-page : 47
		blockquote : 4
		button : 5
		divider : 3
		form : 1
		gallery : 28
		heading : 68
		icon : 1
		icon-list : 20
		image : 38
		image-carousel : 1
		shortcode : 1
		spacer : 11
		testimonial-carousel : 1
		text-editor : 37
		video : 1


== Esperimenti Elementor ==
	Uscita DOM ottimizzata: Attiva
	Caricamento delle risorse migliorato: Attiva
	Caricamento CSS migliorato: Attiva
	Icone dei font in linea: Inattivo per impostazione predefinita
	Miglioramenti dell'accessibilità: Attiva
	Punti di interruzione aggiuntivi: Inattivo per impostazione predefinita
	Import Export Website Kit: Inattivo
	Nascondi i widget nativi di WordPress dai risultati di ricerca: Attivo per impostazione predefinita
	admin_menu_rearrangement: Inattivo per impostazione predefinita
	Contenitore Flexbox: Inattivo per impostazione predefinita
	Predefinito per Nuovo generatore di temi: Attivo per impostazione predefinita
	Header e Footer del tema Hello: Inattivo per impostazione predefinita
	Landing Page: Inattivo
	Campionatore di colori: Attivo per impostazione predefinita
	Widget preferiti: Attivo per impostazione predefinita
	Barra superiore dell'amministratore: Attivo per impostazione predefinita
	Transizioni pagine: Inattivo
	Notes: Attivo per impostazione predefinita
	Invii forms: Attivo per impostazione predefinita
	Snap scroll: Attivo per impostazione predefinita


== Registro ==
	
Log: showing 20 of 422022-10-15 00:45:38 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Finished 
2022-10-15 00:45:38 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0-beta3',
  'to' => '3.8.0-beta4',
)]
2022-10-17 19:04:08 [info] elementor-pro::elementor_pro_updater Started 
2022-10-17 19:04:09 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-10-17 19:04:09 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-10-17 19:04:09 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Start  
2022-10-17 19:04:09 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Finished 
2022-10-17 19:04:09 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.3',
  'to' => '3.8.0-beta4',
)]
2022-11-05 00:34:09 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0-beta4',
  'to' => '3.8.0',
)]
2022-11-05 00:34:56 [info] elementor::elementor_updater Started 
2022-11-05 00:34:56 [info] Elementor/Upgrades - _on_each_version Start  
2022-11-05 00:34:57 [info] Elementor/Upgrades - _on_each_version Finished 
2022-11-05 00:34:57 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Start  
2022-11-05 00:34:57 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Finished 
2022-11-05 00:34:57 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0-beta4',
  'to' => '3.8.0',
)]
2022-11-12 08:31:33 [info] elementor-pro::elementor_pro_updater Started 
2022-11-12 08:31:33 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-11-12 08:31:33 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-11-12 08:31:33 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.0-beta4',
  'to' => '3.8.1',
)]
2022-11-12 08:31:33 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.0-beta4',
  'to' => '3.8.1',
)]

PHP: showing 1 of 1PHP: 2022-11-12 08:52:47 [error X 1][../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::182] Uncaught Error: Class "\ElementorPro\Modules\ThemeBuilder\Conditions\General" not found in ../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:182
Stack trace:
#0 ../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(264): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->register_condition('general')
#1 ../wp-includes/class-wp-hook.php(308): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->register_conditions('')
#2 ../wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#3 ../wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 ../wp-settings.php(639): do_action('wp_loaded')
#5 ../wp-config.php(92): require_once('/home/clients/9...')
#6 ../wp-load.php(50): require_once('/home/clients/9...')
#7 ../wp-blog-header.php(13): require_once('/home/clients/9...')
#8 ../index.php(17): require('/home/clients/9...')
#9 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Incompatibile

== Elementor Pro - Compatibility Tag ==

````

</details>

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro v3.23.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
