### ISSUE TITLE
ELEMENTOR - Copy paste style shortcut - not allowing you to update work after doing so.

### ISSUE THREAD

**Issue by harryjeffery** [elementor/elementor#20470]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When I used the shortcut when designing on the front end of my website to copy and paste style of a title that I wanted the sizing and font to be transferred, I used the 'copy paste style' button.

This works, as normal until I try and update my work which it simply doesn't work/update or let me save a template.

This is quite a frustrating issue as until i realised what was triggering the problem, hours of work wouldnt save.

Is anyone else having this issue ?

### Steps to reproduce

1) Copy a title on Elementor. 2) Go to another title which you want to replicate the exact design settings from the previous title you copied and click paste style button. 3) Go to update/save, it doesnt save and when you leave the page it resets to the original content you have before originally going on and editing the content.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.39-42
	PHP Version: 7.4.33
	PHP Memory Limit: 768M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://allmanhall.co.uk
	Home URL: https://allmanhall.co.uk
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 256M
	Max Memory limit: 768M
	Permalink Structure: /blog/%postname%
	Language: en-GB
	Timezone: 0
	Admin Email: xenon@allmanhall.co.uk
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36

== Active Plugins ==
	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Elementor
		Version: 3.8.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.8.1
		Author: Elementor.com

	Make Column Clickable Elementor
		Version: 1.4.0
		Author: Fernando Acosta

	SiteGround Optimizer
		Version: 7.2.6
		Author: SiteGround

	SiteGround Security
		Version: 1.3.7
		Author: SiteGround

	Ultimate Addons for Elementor
		Version: 1.36.12
		Author: Brainstorm Force

	WPCode - Insert Headers, Footers, and Code Snippets
		Version: 2.0.3
		Author: WPCode

	Yoast Duplicate Post
		Version: 4.5
		Author: Enrico Battocchi & Team Yoast

	Yoast SEO
		Version: 19.10
		Author: Team Yoast

	Yoast SEO Premium
		Version: 19.5
		Author: Team Yoast

== Elementor Experiments ==
	Optimised DOM Output: Inactive by default
	Improved asset loading: Inactive by default
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Accessibility improvements: Inactive by default
	Additional Custom Breakpoints: Inactive by default
	Import Export Website Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Inactive by default
	Landing pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Inactive by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 20 of 342022-10-30 20:01:42 [info] Elementor/Upgrades - _on_each_version Finished 
2022-10-30 20:01:42 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Start  
2022-10-30 20:01:42 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Finished 
2022-10-30 20:01:42 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.8',
  'to' => '3.8.0',
)]
2022-10-30 20:01:42 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.8',
  'to' => '3.8.0',
)]
2022-10-31 08:01:52 [info] elementor-pro::elementor_pro_updater Started 
2022-10-31 08:01:52 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-10-31 08:01:52 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-10-31 08:01:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.8.0',
)]
2022-10-31 08:01:52 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.8.0',
)]
2022-11-09 08:00:55 [info] elementor-pro::elementor_pro_updater Started 
2022-11-09 08:00:55 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-11-09 08:00:55 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-11-09 08:00:55 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.0',
  'to' => '3.8.1',
)]
2022-11-09 08:00:55 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.0',
  'to' => '3.8.1',
)]
2022-11-13 20:10:07 [info] elementor::elementor_updater Started 
2022-11-13 20:10:07 [info] Elementor/Upgrades - _on_each_version Start  
2022-11-13 20:10:07 [info] Elementor/Upgrades - _on_each_version Finished 
2022-11-13 20:10:07 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0',
  'to' => '3.8.1',
)]
2022-11-13 20:10:07 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0',
  'to' => '3.8.1',
)]

PHP: showing 6 of 6PHP: 2022-09-30 09:42:20 [notice X 6][/home/customer/www/allmanhall.co.uk/public_html/wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-30 20:00:45 [error X 1][/home/customer/www/allmanhall.co.uk/public_html/wp-content/plugins/elementor/includes/elements/section.php::947] Uncaught Error: Class 'Elementor\Shapes' not found in /home/customer/www/allmanhall.co.uk/public_html/wp-content/plugins/elementor/includes/elements/section.php:947
Stack trace:
#0 /home/customer/www/allmanhall.co.uk/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(2310): Elementor\Element_Section->register_controls()
#1 /home/customer/www/allmanhall.co.uk/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(496): Elementor\Controls_Stack->init_controls()
#2 /home/customer/www/allmanhall.co.uk/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(300): Elementor\Controls_Stack->get_stack()
#3 /home/customer/www/allmanhall.co.uk/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(2397): Elementor\Controls_Stack->get_controls()
#4 /home/customer/www/allmanhall.co.uk/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(1107): Elementor\Controls_Stack->sanitize_settings(Array)
#5 /home/customer/www/allmanh [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-14 08:14:32 [notice X 1][/home/customer/www/allmanhall.co.uk/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-15 08:11:39 [notice X 1][/home/customer/www/allmanhall.co.uk/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php::747] ob_end_clean(): failed to delete buffer. No buffer to delete [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-17 19:41:01 [notice X 3][/home/customer/www/allmanhall.co.uk/public_html/wp-content/plugins/elementor-pro/modules/forms/classes/form-record.php::179] Undefined index: referrer [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-21 10:11:14 [notice X 1][/home/customer/www/allmanhall.co.uk/public_html/wp-content/plugins/elementor-pro/modules/forms/actions/mailchimp.php::345] Undefined index: email_address [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 3 of 3JS: 2022-11-08 08:57:41 [error X 9][https://allmanhall.co.uk/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:51824] Cannot read properties of undefined (reading \'replace\') 
JS: 2022-11-11 11:18:21 [error X 4][https://allmanhall.co.uk/wp-content/plugins/elementor/assets/js/new-template.min.js?ver=3.8.0:2:2932] elementor_new_template_form_controls is not defined 
JS: 2022-11-15 11:11:57 [error X 1][https://allmanhall.co.uk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.1:3:1061530] Cannot read properties of null (reading \'getBoundingClientRect\') 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	Make Column Clickable Elementor: Compatibility not specified
	Ultimate Addons for Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @harryjeffery!

Thank you for your submission! 🙏 

### 🔗 This issue is a Duplicate of #20315

Which is on the same subject. 

For this reason, I'm closing this issue and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

### 🔍 Please, in the future, remember to check if there isn't an issue similar to yours already opened. 

Best regards,

Nick
