### ISSUE TITLE
⛔ 🛟 Support Request: Custom CSS Sticky effects added to containers are not transitioning anymore after 3.9.0 update

### ISSUE THREAD

**Issue by ConsultMePL** [elementor/elementor#20664]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi,

I had a custom CSS code for my header - basically to shrink a header on scroll and change its background, nothing super complicated (sticky-header is a class name assigned to the container)

````css
header.sticky-header.e-con-full.elementor-element {
	--header-height: 100px; 
	--shrink-header-to: 0.8; 
	background: linear-gradient(180deg, rgba(0,0,0,0.8494748241093313) 0%, rgba(0,0,0,0.50773812943146) 67%, rgba(106,106,106,0.09877454399728647) 100%);
	--min-height: var(--header-height);
	--transition: 800ms ease-in-out;
	width: 100%;
}

header.sticky-header.e-con.elementor-element.elementor-sticky--effects {
	background: #000000AD;
	box-shadow: 0px 4px 33px 1px rgba(0, 0, 0, .07); 
	-webkit-backdrop-filter: saturate(180%) blur(5px); 
	backdrop-filter: saturate(180%) blur(5px); 
	--min-height: calc( var(--header-height) * var(--shrink-header-to) );
}
````

As soon as I updated to Elementor 3.9, the transition effect stopped working. The class targeting is correct, as everything else works. So it purely the transition effect not working at all.

It's not a plugin conflict - disabling all other plugins doesn't help (although there wasn't really a chance for plugin conflict as there were only 2 Croco plugins loading on the frontend). However, as soon as I update to 3.9 the transition stops working and as soon as I rollback to 3.8.1 it starts working again.

Seriously, such strange issues happening with Elementor...  Yet another reason to move on....

### Steps to reproduce

1. Create Container in Header
2. Apply class-name and CSS code to that Container
3. Upgrade to Elementor 3.9 - it stops working

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.6.11
	PHP Version: 7.4.33
	PHP Memory Limit: 1000M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 500M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://podjablonia.consultme.pl
	Home URL: https://podjablonia.consultme.pl
	WP Multisite: No
	Max Upload Size: 500 MB
	Memory limit: 512M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: pl-PL
	Timezone: Europe/Warsaw
	Admin Email: marketing@consultme.pl
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: pl_PL
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36

== Active Plugins ==
	Category Order and Taxonomy Terms Order
		Version: 1.7.4
		Author: Nsp-Code

	Custom background-image size for Elementor
		Version: 1.0.1
		Author: Michael Gangolf

	Elementor
		Version: 3.8.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.9.0
		Author: Elementor.com

	Hummingbird Pro
		Version: 3.4.0
		Author: WPMU DEV

	JetEngine
		Version: 3.1.0-beta1
		Author: Crocoblock

	JetTabs For Elementor
		Version: 2.1.20
		Author: Crocoblock

	Post Types Order
		Version: 1.9.9.2
		Author: Nsp Code

	Redis Object Cache
		Version: 2.2.2
		Author: Till Krüss

	Smush Pro
		Version: 3.12.3
		Author: WPMU DEV

	UiPress Lite
		Version: 3.0.92
		Author: Admin 2020

	UiPress Pro
		Version: 3.0.3
		Author: Admin 2020

	WPMU DEV Dashboard
		Version: 4.11.17
		Author: WPMU DEV

== Wykorzystanie elementów ==
	
	container : 7
		container : 4
		heading : 2
		jet-listing-grid : 4
	footer : 1
		container : 4
		heading : 3
		icon-list : 2
		theme-site-logo : 1
	header : 1
		container : 1
		image : 1
		nav-menu : 1
	wp-page : 4
		container : 15
		heading : 7
		icon-box : 6
		image : 2
		jet-listing-dynamic-field : 1
		jet-listing-grid : 2
		jet-tabs : 1
		text-editor : 2
	jet-listing-items : 0
		container : 9
		heading : 4
		icon : 2
		jet-listing-dynamic-field : 9
		jet-listing-dynamic-image : 1
		jet-listing-grid : 5
		text-editor : 1

== Eksperymenty z Elementorem ==
	Zoptymalizowany wynik DOM: Domyślnie aktywne
	Ulepszone ładowanie zasobów: Domyślnie aktywne
	Poprawione ładowanie CSS: Domyślnie aktywne
	Czcionka ikon: Włączono
	Ulepszenia w zakresie dostępności: Domyślnie aktywne
	Dodatkowe niestandardowe punkty zmiany: Domyślnie aktywne
	Import Export Website Kit: Domyślnie aktywne
	Ukryj natywne widgety WordPressa w wynikach wyszukiwania: Domyślnie aktywne
	admin_menu_rearrangement: Domyślnie nieaktywne
	Flexbox Container: Włączono
	Default to New Theme Builder: Domyślnie aktywne
	Hello Theme Header & Footer: Domyślnie aktywne
	Strony docelowe: Domyślnie aktywne
	Próbnik kolorów: Domyślnie aktywne
	Ulubione widgety: Domyślnie aktywne
	Górny pasek administratora: Domyślnie aktywne
	Page Transitions: Domyślnie aktywne
	Notes: Nieaktywne
	Loop: Domyślnie aktywne
	Form Submissions: Domyślnie aktywne
	Scroll Snap: Domyślnie aktywne

== Dziennik ==
	
PHP: showing 6 of 6PHP: 2022-11-02 01:55:58 [notice X 9][/home/consultme/domains/consultme.pl/public_html/podjablonia/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-23 22:27:47 [error X 1][/home/consultme/domains/consultme.pl/public_html/podjablonia/wp-content/plugins/elementor/core/documents-manager.php::493] Uncaught Error: Call to a member function is_built_with_elementor() on bool in /home/consultme/domains/consultme.pl/public_html/podjablonia/wp-content/plugins/elementor/core/documents-manager.php:493
Stack trace:
#0 [internal function]: Elementor\Core\Documents_Manager->ajax_save(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#1 /home/consultme/domains/consultme.pl/public_html/podjablonia/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/consultme/domains/consultme.pl/public_html/podjablonia/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#3 /home/consultme/domains/consultme.pl/public_html/podjablonia/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#4 /home/consultme/domains/consultme.pl/public_html/podjablonia/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#5 /home/consultme/domains/consultme.pl/public_htm [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-24 02:42:10 [notice X 6][/home/consultme/domains/consultme.pl/public_html/podjablonia/wp-content/plugins/elementor/includes/base/controls-stack.php::1430] Undefined index: _background_hover_image_tablet [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-24 02:55:12 [notice X 5][/home/consultme/domains/consultme.pl/public_html/podjablonia/wp-content/plugins/elementor/includes/base/controls-stack.php::1430] Undefined index: image_height_tablet [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-24 10:33:30 [error X 1][/home/consultme/domains/consultme.pl/public_html/podjablonia/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on null in /home/consultme/domains/consultme.pl/public_html/podjablonia/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /home/consultme/domains/consultme.pl/public_html/podjablonia/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(6, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/consultme/domains/consultme.pl/public_html/podjablonia/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/consultme/domains/consultme.pl/public_html/podjablonia/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-24 15:58:03 [notice X 67][/home/consultme/domains/consultme.pl/public_html/podjablonia/wp-content/plugins/elementor/includes/base/controls-stack.php::1430] Undefined index: field_bg_image_tablet [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 20 of 242022-11-20 23:43:16 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.0',
  'to' => '3.8.1',
)]
2022-11-20 23:43:26 [info] elementor::elementor_updater Started 
2022-11-20 23:43:26 [info] Elementor/Upgrades - _on_each_version Start  
2022-11-20 23:43:26 [info] Elementor/Upgrades - _on_each_version Finished 
2022-11-20 23:43:26 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0',
  'to' => '3.8.1',
)]
2022-11-20 23:43:26 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0',
  'to' => '3.8.1',
)]
2022-11-22 16:34:18 [info] elementor-pro::elementor_pro_updater Started 
2022-11-22 16:34:18 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-11-22 16:34:18 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.1',
  'to' => '3.8.2',
)]
2022-11-22 16:34:20 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.1',
  'to' => '3.8.2',
)]
2022-12-07 21:03:25 [info] elementor::elementor_updater Started 
2022-12-07 21:03:25 [info] Elementor/Upgrades - _on_each_version Start  
2022-12-07 21:03:25 [info] Elementor/Upgrades - _on_each_version Finished 
2022-12-07 21:03:25 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.1',
  'to' => '3.9.0',
)]
2022-12-07 21:03:25 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.1',
  'to' => '3.9.0',
)]
2022-12-07 21:04:22 [info] elementor-pro::elementor_pro_updater Started 
2022-12-07 21:04:22 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-12-07 21:04:22 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-12-07 21:04:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.2',
  'to' => '3.9.0',
)]
2022-12-07 21:04:22 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.2',
  'to' => '3.9.0',
)]

JS: showing 4 of 4JS: 2022-11-22 13:49:33 [error X 1][https://podjablonia.consultme.pl/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.1:3:649119] this.model.isValidChild is not a function 
JS: 2022-11-22 23:46:29 [error X 15][https://podjablonia.consultme.pl/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.1:3:769459] Cannot read properties of undefined (reading \'localized\') 
JS: 2022-11-24 12:49:23 [error X 6][https://podjablonia.consultme.pl/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.8.2:3:99294] Cannot convert undefined or null to object 
JS: 2022-11-24 15:07:36 [error X 15][https://podjablonia.consultme.pl/wp-content/plugins/jet-tabs/assets/js/jet-tabs-frontend.min.js?ver=2.1.20:1:5806] Failed to execute \'observe\' on \'MutationObserver\': parameter 1 is not of type \'Node\'. 

== Elementor - Compatibility Tag ==
	
	Custom background-image size for Elementor: Kompatybilność nieokreślona
	Elementor Pro: Kompatybilność nieokreślona
	JetTabs For Elementor: Kompatybilność nieokreślona

== Elementor Pro - Compatibility Tag ==

**Comment by ConsultMePL** [comment]
@nicholaszein 

I have contacted a support and after providing login details to tech support but received a following email:

"thanks for reaching out to us! My name is Sara (Tier 2 Customer Experience Engineer) and I'll be assisting you with this issue.

We have no insights that any classes were changed in the latest version but it is possible that there were some improvements within the code."

and  in another follow up email the last paragraph was:

"I understand that this functionality is important for your project, therefore I advise you to contact our developers at [www.github.com/elementor](http://www.github.com/elementor) and create a topic about this matter so that they could inspect this further."

And now you are telling me I should have contacted a support - how should I know what has changed in this regard? Both sides are telling me to contact the other side, how am I am supposed to know which one is it? Sorry, that's a mess on your side

Yet, thanks - it helped.

1. There should be a list of changes when it comes to targeting certain classes
2. If I expect / I am certain an issue is caused by an upgrade, there should be clarified line of contact in such case. Especially, since there is nothing mentioned about such changes in changelog, I guess i'd have to follow every thread on Beta and all iterations to know exactly what has changed.
