### ISSUE TITLE
Background Overlay Lazy Load Background

### ISSUE THREAD

**Issue by slikmedia** [elementor/elementor#20736]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When loading a overlay background with Lazy Load Background feature activated the Overlay disappear completely on the website. 

### Steps to reproduce

1. Add an Overlay Background
2. Activate the Lazy Load Background feature 
3. Go on the live page 

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Darwin
	Software: Apache/2.4.43 (Unix)
	MySQL version: MySQL Community Server - GPL v8.0.16
	PHP Version: 8.1.9
	PHP Memory Limit: 256M
	PHP Max Input Vars: 4000
	PHP Max Post Size: 1000M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: http://localhost:10024
	Home URL: http://localhost:10024
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/Toronto
	Admin Email: eric@slik.media
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.6.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.9.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.9.0
		Author: Elementor.com

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Inactive by default
	Import Export Website Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active
	Landing Pages: Inactive
	Color Sampler: Active
	Favorite Widgets: Active by default
	Admin Top Bar: Inactive
	Lazy Load Background Images: Active
	Save as Default: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active
	Form Submissions: Active
	Scroll Snap: Active by default

== Log ==
	
Log: showing 20 of 262022-11-15 00:35:21 [info] elementor::elementor_updater Started 
2022-11-15 00:35:21 [info] Elementor/Upgrades - _on_each_version Start  
2022-11-15 00:35:21 [info] Elementor/Upgrades - _on_each_version Finished 
2022-11-15 00:35:21 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0',
  'to' => '3.8.1',
)]
2022-11-15 00:35:21 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0',
  'to' => '3.8.1',
)]
2022-11-21 18:58:48 [info] elementor-pro::elementor_pro_updater Started 
2022-11-21 18:58:48 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-11-21 18:58:48 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-11-21 18:58:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.1',
  'to' => '3.8.2',
)]
2022-11-21 18:58:48 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.1',
  'to' => '3.8.2',
)]
2022-12-08 00:31:35 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.1',
  'to' => '3.9.0',
)]
2022-12-08 00:31:35 [info] elementor::elementor_updater Started 
2022-12-08 00:31:35 [info] Elementor/Upgrades - _on_each_version Start  
2022-12-08 00:31:35 [info] Elementor/Upgrades - _on_each_version Finished 
2022-12-08 00:31:35 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.1',
  'to' => '3.9.0',
)]
2022-12-08 01:37:26 [info] elementor-pro::elementor_pro_updater Started 
2022-12-08 01:37:26 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-12-08 01:37:26 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-12-08 01:37:26 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.2',
  'to' => '3.9.0',
)]
2022-12-08 01:37:26 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.2',
  'to' => '3.9.0',
)]

PHP: showing 13 of 13PHP: 2022-11-16 19:59:03 [notice X 5][/Users/erictremblay/Local Sites/immobilier/app/public/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-16 20:08:55 [notice X 2][/Users/erictremblay/Local Sites/immobilier/app/public/wp-content/plugins/elementor/includes/managers/image.php::36] Undefined index: size [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-16 20:18:28 [notice X 6][/Users/erictremblay/Local Sites/immobilier/app/public/wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-16 21:04:33 [error X 1][/Users/erictremblay/Local Sites/immobilier/app/public/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on bool in /Users/erictremblay/Local Sites/immobilier/app/public/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /Users/erictremblay/Local Sites/immobilier/app/public/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /Users/erictremblay/Local Sites/immobilier/app/public/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /Users/erictremblay/Local Sites/immobilier/app/public/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /Users/er [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-18 16:10:41 [notice X 88][/Users/erictremblay/Local Sites/immobilier/app/public/wp-content/plugins/elementor-pro/core/utils/collection.php::75] Return type of ElementorPro\Core\Utils\Collection::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-18 16:24:06 [notice X 18][/Users/erictremblay/Local Sites/immobilier/app/public/wp-content/plugins/elementor-pro/core/database/model-base.php::135] Return type of ElementorPro\Core\Database\Model_Base::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-18 17:27:42 [notice X 96][/Users/erictremblay/Local Sites/immobilier/app/public/wp-content/plugins/elementor-pro/core/database/model-base.php::135] Return type of ElementorPro\Core\Database\Model_Base::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: /Users/erictremblay/Local Sites/immobilier/app/public/wp-content/plugins/elementor-pro/core/database/model-base.php(10): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /Users/erictremblay/Local Sites/immobilier/app/public/wp-content/plugins/elementor-pro/plugin.php(153): class type include()array (
  0 => '/Users/erictremblay/Local Sites/immobilier/app/public/wp-content/plugins/elementor-pro/core/database/model-base.php',
)
#2: /Users/erictremblay/Local Sites/immobilier/app/public/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php(18): ElementorPro\Plugin -> autoload()
#3: /Users/erictremblay/Local Sites/immobilier/app/public/wp-content/plugins/elementor-pro/plugin.php(153): class type include()array (
  0 => '/Users/erictremblay/Local Sites/immobilier/app/public/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php',
)
#4: /Users/erictremblay/Local Sites/immobilier/app/public/wp-content/plugins/elementor-pro/modules/notes/data/controller.php(243): ElementorPro\Plugin -> autoload()
',
)]
PHP: 2022-11-20 22:12:18 [notice X 6][/Users/erictremblay/Local Sites/immobilier/app/public/wp-content/plugins/elementor-pro/core/utils/collection.php::75] Return type of ElementorPro\Core\Utils\Collection::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: /Users/erictremblay/Local Sites/immobilier/app/public/wp-content/plugins/elementor-pro/core/utils/collection.php(11): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /Users/erictremblay/Local Sites/immobilier/app/public/wp-content/plugins/elementor-pro/plugin.php(153): class type include()array (
  0 => '/Users/erictremblay/Local Sites/immobilier/app/public/wp-content/plugins/elementor-pro/core/utils/collection.php',
)
#2: /Users/erictremblay/Local Sites/immobilier/app/public/wp-content/plugins/elementor-pro/core/database/query-builder.php(1222): ElementorPro\Plugin -> autoload()
#3: /Users/erictremblay/Local Sites/immobilier/app/public/wp-content/plugins/elementor-pro/core/database/query-builder.php(189): ElementorPro\Core\Database\Query_Builder -> get_bindings()
#4: /Users/erictremblay/Local Sites/immobilier/app/public/wp-content/plugins/elementor-pro/modules/notes/database/query/note-query-builder.php(115): ElementorPro\Core\Database\Query_Builder -> add_sub_select()
',
)]
PHP: 2022-11-20 22:13:20 [notice X 3][/Users/erictremblay/Local Sites/immobilier/app/public/wp-content/plugins/elementor-pro/core/utils/collection.php::75] Return type of ElementorPro\Core\Utils\Collection::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: /Users/erictremblay/Local Sites/immobilier/app/public/wp-content/plugins/elementor-pro/core/utils/collection.php(11): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /Users/erictremblay/Local Sites/immobilier/app/public/wp-content/plugins/elementor-pro/plugin.php(153): class type include()array (
  0 => '/Users/erictremblay/Local Sites/immobilier/app/public/wp-content/plugins/elementor-pro/core/utils/collection.php',
)
#2: /Users/erictremblay/Local Sites/immobilier/app/public/wp-content/plugins/elementor-pro/core/database/query-builder.php(1222): ElementorPro\Plugin -> autoload()
#3: /Users/erictremblay/Local Sites/immobilier/app/public/wp-content/plugins/elementor-pro/core/database/query-builder.php(1081): ElementorPro\Core\Database\Query_Builder -> get_bindings()
#4: /Users/erictremblay/Local Sites/immobilier/app/public/wp-content/plugins/elementor-pro/core/database/model-query-builder.php(89): ElementorPro\Core\Database\Query_Builder -> get()
',
)]
PHP: 2022-12-02 19:09:16 [warning X 2][/Users/erictremblay/Local Sites/immobilier/app/public/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-08 01:37:30 [notice X 18][/Users/erictremblay/Local Sites/immobilier/app/public/wp-content/plugins/elementor-pro/core/database/model-base.php::135] Return type of ElementorPro\Core\Database\Model_Base::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: /Users/erictremblay/Local Sites/immobilier/app/public/wp-content/plugins/elementor-pro/core/database/model-base.php(10): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /Users/erictremblay/Local Sites/immobilier/app/public/wp-content/plugins/elementor-pro/plugin.php(154): class type include()array (
  0 => '/Users/erictremblay/Local Sites/immobilier/app/public/wp-content/plugins/elementor-pro/core/database/model-base.php',
)
#2: /Users/erictremblay/Local Sites/immobilier/app/public/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php(18): ElementorPro\Plugin -> autoload()
#3: /Users/erictremblay/Local Sites/immobilier/app/public/wp-content/plugins/elementor-pro/plugin.php(154): class type include()array (
  0 => '/Users/erictremblay/Local Sites/immobilier/app/public/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php',
)
#4: /Users/erictremblay/Local Sites/immobilier/app/public/wp-content/plugins/elementor-pro/modules/notes/data/controller.php(243): ElementorPro\Plugin -> autoload()
',
)]
PHP: 2022-12-08 01:43:30 [warning X 35][/Users/erictremblay/Local Sites/immobilier/app/public/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php::1490] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-08 01:44:14 [warning X 2][/Users/erictremblay/Local Sites/immobilier/app/public/wp-content/plugins/elementor/app/modules/import-export/module.php::563] Attempt to read property "label" on null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 3 of 3JS: 2022-11-17 03:14:09 [error X 13][http://localhost:10024/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:51824] Cannot read properties of undefined (reading \'replace\') 
JS: 2022-11-17 06:00:46 [error X 1][http://localhost:10024/wp-content/plugins/elementor/assets/js/new-template.min.js?ver=3.8.1:2:2932] elementor_new_template_form_controls is not defined 
JS: 2022-11-17 06:03:09 [error X 18][http://localhost:10024/wp-content/plugins/elementor/assets/js/common-modules.min.js?ver=3.8.1:2:51471] Model.isValidChild() should be implemented, please provide \'isValidChild\' functionality. 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @slikmedia! 

Thank you for submitting your issue! 🙏 

Please allow us some time to investigate it, and get back to you with our findings. 🧐 

Best regards

**Comment by FauzanEdris** [comment]
are you still investigating for almost 1 year? @nicholaszein
