### ISSUE TITLE
divider widget center invalid css

### ISSUE THREAD

**Issue by sean1138** [elementor/elementor#20811]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

not a huge deal, doesn't break anything just outputs an invalid css rule

https://youtu.be/aY2FOYzlwfc

### Steps to reproduce

1, use a divider widget, not sure if must be in flex containers but that is my case
2, set a px value width in the divider widget
3, set center alignment in the divider widget
4, save page and check/inspect the .elementor-divider-separator element and see margin-center:0; rule made.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.39-42
	PHP Version: 7.4.33
	PHP Memory Limit: 768M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://midohiomedspa.com
	Home URL: https://midohiomedspa.com
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 256M
	Max Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/New_York
	Admin Email: jpbmarketing@hotmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36

== Active Plugins ==
	All-in-One WP Migration
		Version: 7.69
		Author: ServMask

	All-in-One WP Migration Unlimited Extension
		Version: 2.47
		Author: ServMask

	Better Search Replace
		Version: 1.4.1
		Author: Delicious Brains

	Duplicate Page
		Version: 4.5
		Author: mndpsingh287

	Elementor
		Version: 3.9.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.9.1
		Author: Elementor.com

	Filester - File Manager Pro
		Version: 1.7.6
		Author: Ninja Team

	InfiniteWP - Client
		Version: 1.10.0
		Author: Revmakx

	Redirection
		Version: 5.3.6
		Author: John Godley

	SiteGround Optimizer
		Version: 7.2.9
		Author: SiteGround

	SiteGround Security
		Version: 1.3.8
		Author: SiteGround

	Woody code snippets (PHP snippets | Insert PHP)
		Version: 2.4.7
		Author: Creative Motion, Will Bontrager Software, LLC <will@willmaster.com>

	Wordfence Security
		Version: 7.8.2
		Author: Wordfence

	WP Activity Log
		Version: 4.4.3
		Author: WP White Security

	WP Activity Log for Yoast SEO
		Version: 1.3.0
		Author: WP White Security

	Yoast SEO
		Version: 19.13
		Author: Team Yoast

== Must-Use Plugins ==
	InfiniteWP - Client Loader
		Version: 1.0.1
		Author: Revmakx

== Elements Usage ==
	
	footer : 1
		form : 1
		heading : 5
		image : 1
		nav-menu : 1
		text-editor : 3
	header : 1
		container : 3
		image : 1
		nav-menu : 1
		search-form : 1
	page : 3
		button : 4
		divider : 3
		google_maps : 1
		heading : 11
		icon-box : 3
		icon-list : 2
		image : 3
		text-editor : 14
	section : 2
		button : 6
		divider : 11
		heading : 18
		image : 8
		text-editor : 32
	wp-page : 4
		button : 4
		container : 58
		divider : 1
		form : 1
		google_maps : 1
		heading : 22
		icon-box : 3
		image : 1
		image-box : 2
		price-list : 2
		text-editor : 18
	error-404 : 1
		button : 1
		heading : 2
		icon : 1
		spacer : 3

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Inactive
	Import Export Website Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Inactive
	Hello Theme Header & Footer: Inactive
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Lazy Load Background Images: Inactive by default
	Save as Default: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Inactive by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 20 of 382022-12-07 13:18:14 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.1',
  'to' => '3.9.0',
)]
2022-12-07 13:18:15 [info] elementor-pro::elementor_pro_updater Started 
2022-12-07 13:18:15 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-12-07 13:18:15 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-12-07 13:18:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.2',
  'to' => '3.9.0',
)]
2022-12-07 13:18:15 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.2',
  'to' => '3.9.0',
)]
2022-12-07 13:18:15 [info] elementor::elementor_updater Started 
2022-12-07 13:18:15 [info] Elementor/Upgrades - _on_each_version Start  
2022-12-07 13:18:16 [info] Elementor/Upgrades - _on_each_version Finished 
2022-12-07 13:18:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.1',
  'to' => '3.9.0',
)]
2022-12-20 11:24:23 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0',
  'to' => '3.9.1',
)]
2022-12-20 11:24:23 [info] elementor-pro::elementor_pro_updater Started 
2022-12-20 11:24:23 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-12-20 11:24:23 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-12-20 11:24:23 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.0',
  'to' => '3.9.1',
)]
2022-12-20 11:24:24 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.0',
  'to' => '3.9.1',
)]
2022-12-20 11:24:24 [info] elementor::elementor_updater Started 
2022-12-20 11:24:24 [info] Elementor/Upgrades - _on_each_version Start  
2022-12-20 11:24:24 [info] Elementor/Upgrades - _on_each_version Finished 
2022-12-20 11:24:24 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0',
  'to' => '3.9.1',
)]

PHP: showing 4 of 4PHP: 2022-11-05 08:25:17 [notice X 6][/home/customer/www/midohiomedspa.com/public_html/wp-content/plugins/elementor-pro/modules/forms/classes/form-record.php::179] Undefined index: referrer [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-22 09:09:03 [notice X 4][/home/customer/www/midohiomedspa.com/public_html/wp-content/plugins/elementor-pro/license/updater.php::84] Undefined index: new_version [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-28 12:30:17 [notice X 2][/home/customer/www/midohiomedspa.com/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-30 13:19:21 [error X 2][/home/customer/www/midohiomedspa.com/public_html/wp-content/plugins/elementor-pro/modules/screenshots/module.php::206] Uncaught Requests_Exception_HTTP_403: 403 Forbidden in /home/customer/www/midohiomedspa.com/public_html/wp-content/plugins/elementor-pro/modules/screenshots/module.php:206
Stack trace:
#0 /home/customer/www/midohiomedspa.com/public_html/wp-content/plugins/elementor-pro/modules/screenshots/module.php(226): ElementorPro\Modules\Screenshots\Module->is_screenshot_proxy_mode(Array)
#1 /home/customer/www/midohiomedspa.com/public_html/wp-content/plugins/elementor/core/base/module.php(85): ElementorPro\Modules\Screenshots\Module->__construct()
#2 /home/customer/www/midohiomedspa.com/public_html/wp-content/plugins/elementor-pro/core/modules-manager.php(86): Elementor\Core\Base\Module::instance()
#3 /home/customer/www/midohiomedspa.com/public_html/wp-content/plugins/elementor-pro/plugin.php(357): ElementorPro\Core\Modules_Manager->__construct()
#4 /home/customer/www/midohiomedspa.com/public_html/wp-includes/class-wp-hook.php(308): ElementorPro\Plugin->on_elementor_init('')
#5 /home/customer/www/midohiomedspa.com/public [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 1 of 1JS: 2022-12-20 16:50:56 [error X 1][https://midohiomedspa.com/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:51824] Cannot read properties of undefined (reading \'replace\') 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by m1ga** [comment]
The code is here: 
https://github.com/elementor/elementor/blob/ef19421b7637f93d427e1691427e8e87304015a7/includes/widgets/divider.php#L450-L468

since {{value}} is filled with the result of the options (like left, right, center) it will create that "broken" css for the center part. It's been like this for at least 3 years :smile:

**Comment by nicholaszein** [comment]
Hello @sean1138! 

Thank you for submitting your issue! 🙏 

And thank you @m1ga for indicating where the error is as well!

This was a sneaky one! I'm glad you found it. I'll let the team know! 😉 

Best regards
