### ISSUE TITLE
⛔ 📚 🐞 Bug Report: WooCommerce hook `woocommerce_single_product_summary` not working

### ISSUE THREAD

**Issue by aeworkload** [elementor/elementor#20827]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

````php
add_action('woocommerce_single_product_summary', 'out_of_stock_show_form', 30);
function out_of_stock_show_form() {
    global $product;
    if(!$product->is_in_stock( )) {
        echo  '<div class="your-form">';
        echo  do_shortcode('[elementor-template id="3615"]'); // Replace with your own contact form shortcode
        echo  '</div>';
    }
}
````

Applying this code in order to add a contact form on "out of stock" products in WooCommerce. Using Elementor Template for a single product does not allow the form to show up. If Elementor pro is deactivated, the contact form appears. 

![screenshot-martaescauriaza es-2022 12 19-18_46_59](https://user-images.githubusercontent.com/121128923/209005881-f7ac987d-41e2-4c0b-823c-85a474578dec.png)

![screenshot-martaescauriaza es-2022 12 19-18_48_23](https://user-images.githubusercontent.com/121128923/209005884-37a5f9b6-2e08-45af-a45f-164d4f60a94a.png)

### Steps to reproduce

1/Create WooCommerce product
2/add Elementor template for a single product
3/Create a contact form on elementor 
4/add this code in functions.php: 

````php
add_action('woocommerce_single_product_summary', 'out_of_stock_show_form', 30);
function out_of_stock_show_form() {
    global $product;
    if(!$product->is_in_stock( )) {
        echo  '<div class="your-form">';
        echo  do_shortcode('[elementor-template id="3615"]'); // Replace with your own contact form shortcode
        echo  '</div>';
    }
}
````

### Isolating the problem

- [X] This bug happens with only the Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

````txt

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release rel5.7, Revision 26 v5.7.26-29
	PHP Version: 7.4.33
	PHP Memory Limit: 256M
	PHP Max Input Vars: 8000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://martaescauriaza.es
	Home URL: https://martaescauriaza.es
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: es
	Timezone: Europe/London
	Admin Email: info@martaescauriaza.es
	Debug Mode: Inactive

== Theme ==
	Name: OceanWP Child
	Version: 1.0
	Author: Nick
	Child Theme: Yes
	Parent Theme Name: OceanWP
	Parent Theme Version: 3.3.6
	Parent Theme Author: OceanWP

== User ==
	Role: administrator
	WP Profile lang: es_ES
	User Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36

== Active Plugins ==
	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	CookieYes | GDPR Cookie Consent
		Version: 3.0.7
		Author: CookieYes

	Elementor
		Version: 3.9.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.9.1
		Author: Elementor.com

	Fluent Forms
		Version: 4.3.22
		Author: Contact Form - WPManageNinja LLC

	Ocean Extra
		Version: 2.0.6
		Author: OceanWP

	Rank Math SEO
		Version: 1.0.103.1
		Author: Rank Math

	Really Simple SSL
		Version: 6.0.12
		Author: Really Simple Plugins

	Redirection
		Version: 5.3.6
		Author: John Godley

	Sucuri Security - Auditing, Malware Scanner and Hardening
		Version: 1.8.36
		Author: Sucuri Inc.

	WooCommerce
		Version: 7.2.0
		Author: Automattic

	WooCommerce Payments
		Version: 5.1.2
		Author: Automattic

	WP Rocket
		Version: 3.12.3.3
		Author: WP Media

	Yoast Duplicate Post
		Version: 4.5
		Author: Enrico Battocchi & Team Yoast


== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

	object-cache.php
		Version: 
		Author: 

	System Plugin
		Version: 4.59.0
		Author: 


== Uso de los elementos ==
	
	header : 4
		nav-menu : 2
	page : 1
		button : 2
		divider : 4
		form : 1
		google_maps : 1
		heading : 11
		icon-list : 1
		image : 4
		slides : 3
		social-icons : 1
		spacer : 3
		text-editor : 5
		theme-post-featured-image : 1
		toggle : 1
	popup : 5
		button : 2
		divider : 1
		form : 1
		heading : 1
		spacer : 1
		text-editor : 3
		theme-post-featured-image : 1
	product : 4
		heading : 4
		social-icons : 1
		tabs : 1
		text-editor : 1
		woocommerce-checkout-page : 1
		woocommerce-product-add-to-cart : 2
		woocommerce-product-content : 1
		woocommerce-product-data-tabs : 1
		woocommerce-product-images : 3
		woocommerce-product-meta : 1
		woocommerce-product-price : 3
		woocommerce-product-rating : 1
		woocommerce-product-short-description : 3
		woocommerce-product-title : 4
		woocommerce-product-upsell : 1
		woocommerce-products : 1
	section : 7
		form : 2
		video : 3
	wp-page : 27
		animated-headline : 1
		button : 15
		call-to-action : 3
		form : 2
		gallery : 1
		google_maps : 1
		heading : 141
		icon-box : 1
		media-carousel : 14
		nav-menu : 1
		price-list : 15
		social-icons : 17
		spacer : 14
		tabs : 14
		text-editor : 65
	product-archive : 1
		theme-archive-title : 1
		wc-archive-products : 1


== Experimentos de Elementor ==
	Salida del DOM optimizada: Inactivo por defecto
	Carga de recursos mejorada: Inactivo por defecto
	Carga de CSS mejorada: Inactivo por defecto
	Fuentes de iconos integradas: Inactivo por defecto
	Mejoras de accesibilidad: Inactivo por defecto
	Puntos de ruptura personalizados adicionales: Inactivo por defecto
	Importar o exportar un kit web: Activo por defecto
	Ocultar los widgets nativos de WordPress de los resultados de búsqueda: Activo por defecto
	admin_menu_rearrangement: Inactivo por defecto
	Contenedor Flexbox: Inactivo por defecto
	Por defecto, el nuevo constructor de temas: Activo por defecto
	Páginas de destino: Activo por defecto
	Muestrario de colores: Activo por defecto
	Widgets favoritos: Activo por defecto
	Barra superior de administración: Activo por defecto
	Carga diferida de imágenes de fondo: Inactivo por defecto
	Guardar como por defecto: Activo por defecto
	Transiciones de páginas: Activo por defecto
	Notes: Activo por defecto
	Bucle: Inactivo por defecto
	Envíos de formulario: Activo por defecto
	Ajuste de scroll: Activo por defecto


== Registro ==
	
Log: showing 20 of 322022-12-07 03:17:15 [info] Elementor/Upgrades - _on_each_version Finished 
2022-12-07 03:17:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.1',
  'to' => '3.9.0',
)]
2022-12-07 03:17:15 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.1',
  'to' => '3.9.0',
)]
2022-12-07 03:17:16 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.1',
  'to' => '3.9.0',
)]
2022-12-07 15:52:55 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.2',
  'to' => '3.9.0',
)]
2022-12-07 15:52:57 [info] elementor-pro::elementor_pro_updater Started 
2022-12-07 15:52:57 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-12-07 15:52:58 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-12-07 15:52:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.2',
  'to' => '3.9.0',
)]
2022-12-14 21:53:03 [info] elementor::elementor_updater Started 
2022-12-14 21:53:03 [info] Elementor/Upgrades - _on_each_version Start  
2022-12-14 21:53:04 [info] Elementor/Upgrades - _on_each_version Finished 
2022-12-14 21:53:04 [info] Elementor/Upgrades - _on_each_version Start  
2022-12-14 21:53:05 [info] Elementor/Upgrades - _on_each_version Finished 
2022-12-14 21:53:05 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0',
  'to' => '3.9.1',
)]
2022-12-15 10:10:24 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.0',
  'to' => '3.9.1',
)]
2022-12-15 10:10:27 [info] elementor-pro::elementor_pro_updater Started 
2022-12-15 10:10:27 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-12-15 10:10:27 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-12-15 10:10:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.0',
  'to' => '3.9.1',
)]

JS: showing 3 of 3JS: 2022-11-16 09:26:34 [error X 1][https://martaescauriaza.es/wp-content/plugins/elementor/assets/js/new-template.min.js?ver=3.8.1:2:2932] elementor_new_template_form_controls is not defined 
JS: 2022-11-16 17:34:23 [error X 1][https://martaescauriaza.es/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.8.1:3:99294] Cannot convert undefined or null to object 
JS: 2022-11-18 12:25:29 [error X 5][https://martaescauriaza.es/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.1:3:1061530] Cannot read properties of null (reading \&#039;getBoundingClientRect\&#039;) 

PHP: showing 7 of 7PHP: 2022-11-17 13:25:26 [notice X 3][/var/www/wp-content/plugins/elementor/includes/elements/column.php::1010] Undefined index: _column_size [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-18 12:36:18 [error X 64][/var/www/wp-content/plugins/elementor/includes/managers/elements.php::71] Uncaught TypeError: Argument 1 passed to Elementor\Elements_Manager::create_element_instance() must be of the type array, bool given, called in /var/www/wp-content/plugins/elementor-pro/modules/payments/module.php on line 289 and defined in /var/www/wp-content/plugins/elementor/includes/managers/elements.php:71
Stack trace:
#0 /var/www/wp-content/plugins/elementor-pro/modules/payments/module.php(289): Elementor\Elements_Manager-&gt;create_element_instance(false)
#1 /var/www/wp-includes/class-wp-hook.php(308): ElementorPro\Modules\Payments\Module-&gt;submit_stripe_form(&#039;&#039;)
#2 /var/www/wp-includes/class-wp-hook.php(332): WP_Hook-&gt;apply_filters(&#039;&#039;, Array)
#3 /var/www/wp-includes/plugin.php(517): WP_Hook-&gt;do_action(Array)
#4 /var/www/wp-admin/admin-ajax.php(188): do_action(&#039;wp_ajax_submit_...&#039;)
#5 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-21 12:53:30 [notice X 38][/var/www/wp-content/plugins/elementor-pro/modules/forms/classes/form-record.php::179] Undefined index: referrer [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-21 16:49:43 [notice X 2][/var/www/wp-content/plugins/elementor-pro/modules/payments/module.php::300] Undefined index: stripe_test_env_tax_rates_list [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-21 16:53:41 [warning X 14][/var/www/wp-content/plugins/elementor-pro/modules/payments/module.php::243] A non-numeric value encountered [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-21 17:15:21 [error X 12][/var/www/wp-content/plugins/elementor/includes/managers/elements.php::71] Uncaught TypeError: Argument 1 passed to Elementor\Elements_Manager::create_element_instance() must be of the type array, bool given, called in /var/www/wp-content/plugins/elementor-pro/modules/payments/module.php on line 289 and defined in /var/www/wp-content/plugins/elementor/includes/managers/elements.php:71
Stack trace:
#0 /var/www/wp-content/plugins/elementor-pro/modules/payments/module.php(289): Elementor\Elements_Manager-&gt;create_element_instance(false)
#1 /var/www/wp-includes/class-wp-hook.php(308): ElementorPro\Modules\Payments\Module-&gt;submit_stripe_form(&#039;&#039;)
#2 /var/www/wp-includes/class-wp-hook.php(332): WP_Hook-&gt;apply_filters(&#039;&#039;, Array)
#3 /var/www/wp-includes/plugin.php(517): WP_Hook-&gt;do_action(Array)
#4 /var/www/wp-admin/admin-ajax.php(203): do_action(&#039;wp_ajax_nopriv_...&#039;)
#5 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-23 12:39:10 [notice X 7][/var/www/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Incompatible

== Elementor Pro - Compatibility Tag ==


````

**Comment by nicholaszein** [comment]
Hello @aeworkload,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
* Since you're building the Single Product template with Elementor's WooBuilder, there is no `woocommerce_single_product_summary` hook as it does with normal WooCommerce templates. You need to use another hook instead, or a better alternative is to use a shortcode.

### ✅ What you can do to solve your issue:
* You have two options that will work well for you.

1. Add your code to a [shortcode](https://codex.wordpress.org/Shortcode_API), and use the [Shortcode widget](https://elementor.com/help/shortcode-widget/) to display your form.

2. Use the code below with the `woocommerce_before_add_to_cart_button` hook (not tested, use it at your own risk):

````php

/**
 * Adds content Before the Add-to-cart button
 *
 * @param \Elementor\Element_Base $element The element instance.
 */
add_action( 'elementor/frontend/widget/before_render', 'custom_out_of_stock_form_before_add_to_cart' );
function custom_out_of_stock_form_before_add_to_cart( $element ) {
	global $product;

	// Get the widget name
	$widget_name = $element->get_name();

	// Check if we're on a Single Product, and if we're on the correct widget
	if ( is_product() && $widget_name === 'woocommerce-product-add-to-cart' && !$product->is_in_stock() ) {
		add_action( 'woocommerce_before_add_to_cart_button', function() {
			echo  '<div class="your-form">';
			echo  do_shortcode('[elementor-template id="3615"]'); // Replace with your own contact form shortcode
			echo  '</div>';
		});
	}
}

````

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* Please create GitHub issues **only for Elementor bugs**. GitHub issues ARE NOT FOR SUPPORT or for issues with 3rd party plugins.
* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

### ⚠️ Please Note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards

**Comment by aeworkload** [comment]
Hi,

Thanks a lot for coming back to me. Unfortunately none of those solutions
works on my website. I tried both ways, with my code, your code, shortcode
etc...but nothing changes . I really appreciated the time and effort you
put on it to help out. Sadly, I will have to find other way. Many thanks.
