### ISSUE TITLE
Submenu icon in dropdown only opens, doesn't close submenu (with the inline font icons experiment active)

### ISSUE THREAD

**Issue by netalized** [elementor/elementor#20859]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I was creating a dropdown menu and noticed the submenu icon will work when you click to open the item, but it doesn't close menu structure / categories. I was using the standard "Caret down" icon form the list.

After I turned off the experiment "inline font icons experiment" it was working again.

Hopefully it can be fixed somewhere in the future.

Good luck! 

### Steps to reproduce

1) create a dropdown menu with some sub categories
2) add submenu indicator
3) then when testing you'll see it does open, but doesn't close the categorie
4) you need to click precisely on the icon, because clicking next to it left,right,up or down of it, it'll just work as normal

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.20.2
	MySQL version: (Google) v8.0.26
	PHP Version: 7.4.33
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://puurbybabs.elementor.cloud
	Home URL: https://puurbybabs.elementor.cloud
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 512M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: nl
	Timezone: 1
	Admin Email: info@netalized.nl
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: nl_NL
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36

== Active Plugins ==
	Activity Log
		Version: 2.8.5
		Author: Activity Log Team

	Elementor
		Version: 3.10.0-cloud2
		Author: Elementor.com

	Elementor Pro
		Version: 3.10.0-cloud2
		Author: Elementor.com

	Facebook for WooCommerce
		Version: 3.0.6
		Author: Facebook

	Google Listings and Ads
		Version: 2.3.4
		Author: WooCommerce

	MailPoet
		Version: 4.3.0
		Author: MailPoet

	Site Kit by Google
		Version: 1.90.1
		Author: Google

	WooCommerce
		Version: 7.2.2
		Author: Automattic

	WooCommerce Payments
		Version: 5.2.0
		Author: Automattic

	WPFront Scroll Top
		Version: 2.0.7.08086
		Author: Syam Mohan

== Gebruik van elementen ==
	
	container : 2
		animated-headline : 1
		container : 2
		icon-list : 1
		image : 1
	footer : 2
		container : 5
		image : 1
		nav-menu : 1
		search-form : 1
		social-icons : 1
		text-editor : 1
	header : 2
		button : 1
		container : 3
		theme-site-logo : 1
		woocommerce-breadcrumb : 1
		woocommerce-menu-cart : 1
	popup : 1
		container : 1
		nav-menu : 1
	wp-page : 27
		accordion : 1
		animated-headline : 10
		button : 10
		container : 193
		heading : 26
		icon-list : 10
		image : 66
		image-carousel : 1
		star-rating : 3
		table-of-contents : 6
		text-editor : 79

== Instellingen ==
	
	cpt_support: post, page, e-landing-page, product, mailpoet_page
	allow_tracking: yes
	font_display: swap

== Elementor experimenten ==
	Geoptimaliseerde DOM-uitvoer: Actief
	Verbeterd laden van assets: Actief
	Verbeterd laden van CSS: Actief
	Pictogrammen inline lettertype: Inactief
	Toegang verbeteringen: Actief
	Extra aangepaste onderbrekingspunten: Actief
	Verberg verouderde WordPress widgets voor zoekresultaten: Actief
	admin_menu_rearrangement: Standaard inactief
	Flexbox container: Actief
	Default to New Theme Builder: Actief
	Hello Theme header & footer: Actief
	Editor V2: Standaard inactief
	Landingspagina's: Actief
	Nested Elements: Actief
	Lazy-load achtergrondafbeeldingen: Actief
	Opslaan als standaard: Actief
	Page Transitions: Actief
	Notes: Actief
	Loop: Actief
	Loop Carousel: Standaard inactief
	Form Submissions: Actief
	Scroll Snap: Actief

== Log ==
	
PHP: showing 4 of 4PHP: 2022-12-26 19:36:50 [notice X 18][/mnt/customers-3/customers-el-3685166-44252-puurbybabs-wordpress-pvc-63a4b7f8d3a83b00207eb33a/wp-content/wp-content/plugins/elementor/core/common/modules/ajax/module.php::172] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-26 19:56:06 [notice X 5][/mnt/customers-3/customers-el-3685166-44252-puurbybabs-wordpress-pvc-63a4b7f8d3a83b00207eb33a/wp-content/wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-26 19:56:26 [error X 2][/mnt/customers-3/customers-el-3685166-44252-puurbybabs-wordpress-pvc-63a4b7f8d3a83b00207eb33a/wp-content/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::295] Uncaught Error: Call to a member function update_meta() on bool in /mnt/customers-3/customers-el-3685166-44252-puurbybabs-wordpress-pvc-63a4b7f8d3a83b00207eb33a/wp-content/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:295
Stack trace:
#0 /mnt/customers-3/customers-el-3685166-44252-puurbybabs-wordpress-pvc-63a4b7f8d3a83b00207eb33a/wp-content/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(168): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions()
#2 /mnt/customers-3/customers-el-3685166-44252-puurbybabs-wordpress-pvc-63a4b7f8d3a83b00207eb33a/wp-content/wp-content/plugins/elementor/core/common/modules/ajax/module.php(172): call_user_func()
#3 /mnt/customers-3/customers-el-3685166-44252-puurbybabs-wordpress-pvc-63a4b7f8d3a83b00207eb33a/wp-content/wp-includes/class-wp-hook.php(308): Eleme [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-26 21:56:24 [notice X 2][/mnt/customers-3/customers-el-3685166-44252-puurbybabs-wordpress-pvc-63a4b7f8d3a83b00207eb33a/wp-content/wp-content/plugins/elementor-pro/modules/query-control/module.php::384] Undefined index: display [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 8 of 8JS: 2022-12-26 18:44:21 [error X 1][https://puurbybabs.elementor.cloud/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:9:21077] Cannot read properties of null (reading 'getOptions') 
JS: 2022-12-26 19:04:41 [error X 73][https://puurbybabs.elementor.cloud/wp-admin/load-scripts.php?c=1&loadchunk_0=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&loadchunk_1=hooks&ver=6.1.1:4:51824] Cannot read properties of undefined (reading 'replace') 
JS: 2022-12-26 19:34:42 [error X 65][https://puurbybabs.elementor.cloud/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.10.0-cloud2:3:782795] Cannot read properties of undefined (reading 'localized') 
JS: 2022-12-26 20:24:13 [error X 5][https://puurbybabs.elementor.cloud/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.10.0-cloud2:3:662066] this.model.isValidChild is not a function 
JS: 2022-12-26 23:19:09 [error X 1][https://puurbybabs.elementor.cloud/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.10.0-cloud2:3:710633] Cannot read properties of undefined (reading 'widgets_settings') 
JS: 2022-12-27 08:07:52 [error X 1][https://puurbybabs.elementor.cloud/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.10.0-cloud2:3:782288] Cannot read properties of undefined (reading 'toLowerCase') 
JS: 2022-12-27 08:21:36 [error X 1][https://puurbybabs.elementor.cloud/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.10.0-cloud2:3:583495] Cannot read properties of null (reading 'id') 
JS: 2022-12-27 09:32:48 [error X 1][https://puurbybabs.elementor.cloud/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.10.0-cloud2:2:8633] Cannot read properties of undefined (reading 'attributes') 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibel

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @netalized! 

Thank you for submitting your issue! 🙏 

Please allow us some time to investigate it, and get back to you with our findings. 🧐 

Best regards

**Comment by rloes** [comment]
This [plugin/snippet](https://github.com/rloes/elementor-fixed-nav-menu) provides a fix for this issue, until it is fixed.
