### ISSUE TITLE
🚧 🐞 Bug Report: Uncaught TypeError When launching the editor

### ISSUE THREAD

**Issue by Minatanae** [elementor/elementor#20897]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Launching the editor stopped working on it's own one day. Having done the regular stuff like increasing limits and so on, I'm perfectly stumped on this. Disabling everything but elementor/elementor pro and the hello theme does absolutely nothing. No weird scripts or anything being sideloaded either. Different loading method, safe mode and so on does nothing.

**Uncaught TypeError: C.$el.resizable is not a function**
at constructor.resizable (editor.min.js?ver=3.9.2:3:726019)
at new constructor (editor.min.js?ver=3.9.2:3:725742)
at Function._buildRegionFromRegionClass (backbone.marionette.min.js?ver=2.4.5.e1:24:15407)
at Function.buildRegion (backbone.marionette.min.js?ver=2.4.5.e1:24:14993)
at constructor.addRegion (backbone.marionette.min.js?ver=2.4.5.e1:24:15853)
at constructor.<anonymous> (backbone.marionette.min.js?ver=2.4.5.e1:24:15753)
at load-scripts.php?c=1&load%5Bchunk_0%5D=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&load%5Bchunk_1%5D=hooks&ver=6.1.1:2:6374
at Function.<anonymous> (load-scripts.php?c=1&load%5Bchunk_0%5D=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&load%5Bchunk_1%5D=hooks&ver=6.1.1:2:9774)
at constructor.addRegions (backbone.marionette.min.js?ver=2.4.5.e1:24:15644)
at Editor.addRegions (backbone.marionette.min.js?ver=2.4.5.e1:25:8478)

### Steps to reproduce

Launch elementor. That's it.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt


== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: mariadb.org binary distribution v10.9.4
	PHP Version: 8.1.9
	PHP Memory Limit: 256M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://gislavedtrafikskola.se
	Home URL: https://gislavedtrafikskola.se
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: sv-SE
	Timezone: Europe/Stockholm
	Admin Email: [REDACTED]
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: sv_SE
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.9.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.9.2
		Author: Elementor.com

	LiteSpeed Cache
		Version: 5.3.1
		Author: LiteSpeed Technologies

	The SEO Framework
		Version: 4.2.7.1
		Author: The SEO Framework Team

	WP Mail SMTP
		Version: 3.7.0
		Author: WPForms

	WPS Hide Login
		Version: 1.9.6
		Author: WPServeur, NicolasKulka, wpformation


== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com


== Elementor Experiments ==
	Optimized DOM Output: Inaktiv
	Improved Asset Loading: Inaktiv
	Förbättrad CSS-laddning: Inaktiv
	Inline Font Icons: Inaktiv
	Tillgänglighetsförbättringar : Inaktiv
	Ytterligare anpassade brytpunkter: Inaktiv
	Importera/exportera webbplats-kit: Inaktiv
	Dölj inbyggda WordPress-widgetar från sökresultat: Inaktiv
	admin_menu_rearrangement: Inaktiv som standard
	Flexbox Container: Inaktiv
	Default to New Theme Builder: Inaktiv
	Hello Theme Header & Footer: Inaktiv
	Landningssidor: Inaktiv
	Färgprovtagare: Inaktiv
	Favoritwidgetar: Inaktiv
	Admin Top Bar: Inaktiv
	Uppskjuten inläsning av bakgrundsbilder: Inaktiv
	Spara som standard: Inaktiv
	Sidövergångar: Inaktiv
	Notes: Inaktiv
	Loop: Inaktiv
	Formulärinlämningar: Inaktiv
	Scroll Snap: Inaktiv


== Logg ==
	
Log: showing 20 of 292022-12-12 09:42:14 [info] Elementor/Upgrades - _on_each_version Start  
2022-12-12 09:42:14 [info] Elementor/Upgrades - _on_each_version Finished 
2022-12-12 09:42:14 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.1',
  'to' => '3.9.0',
)]
2022-12-12 09:42:14 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.1',
  'to' => '3.9.0',
)]
2022-12-26 09:55:23 [info] elementor::elementor_updater Started 
2022-12-26 09:55:23 [info] Elementor/Upgrades - _on_each_version Start  
2022-12-26 09:55:23 [info] Elementor/Upgrades - _on_each_version Finished 
2022-12-26 09:55:23 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0',
  'to' => '3.9.2',
)]
2022-12-26 10:09:51 [info] elementor-pro::elementor_pro_updater Started 
2022-12-26 10:09:51 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-12-26 10:09:51 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-12-26 10:09:51 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.0',
  'to' => '3.9.2',
)]
2022-12-29 14:52:30 [notice] Re-migrate 3.0.0 globals: Start 
2022-12-29 14:52:30 [notice] Re-migrate 3.0.0 globals: _v_3_0_0_move_default_typography_to_kit 
2022-12-29 14:52:30 [notice] System typography is disabled. nothing to do. 
2022-12-29 14:52:30 [notice] Re-migrate 3.0.0 globals: _v_3_0_0_move_default_colors_to_kit 
2022-12-29 14:52:30 [notice] System colors are disabled. nothing to do. 
2022-12-29 14:52:30 [notice] Re-migrate 3.0.0 globals: _v_3_0_0_move_saved_colors_to_kit 
2022-12-29 14:52:30 [notice] Custom colors already exist. nothing to do. 
2022-12-29 14:52:30 [notice] Re-migrate 3.0.0 globals: End 

PHP: showing 8 of 8PHP: 2022-11-29 11:21:37 [warning X 185][/var/www/html/wp-content/plugins/elementor-pro/modules/forms/classes/form-record.php::179] Undefined array key &quot;referrer&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-26 10:02:46 [error X 1][/var/www/html/wp-content/plugins/elementor-pro/plugin.php::466] Uncaught Error: Class &quot;ElementorPro\Core\Compatibility\Compatibility&quot; not found in /var/www/html/wp-content/plugins/elementor-pro/plugin.php:466
Stack trace:
#0 /var/www/html/wp-content/plugins/elementor-pro/plugin.php(122): ElementorPro\Plugin-&gt;__construct()
#1 /var/www/html/wp-content/plugins/elementor-pro/plugin.php(514): ElementorPro\Plugin::instance()
#2 /var/www/html/wp-content/plugins/elementor-pro/elementor-pro.php(57): require(&#039;...&#039;)
#3 /var/www/html/wp-includes/class-wp-hook.php(308): elementor_pro_load_plugin()
#4 /var/www/html/wp-includes/class-wp-hook.php(332): WP_Hook-&gt;apply_filters()
#5 /var/www/html/wp-includes/plugin.php(517): WP_Hook-&gt;do_action()
#6 /var/www/html/wp-settings.php(480): do_action()
#7 /var/www/html/wp-config.php(91): require_once(&#039;...&#039;)
#8 /var/www/html/wp-load.php(50): require_once(&#039;...&#039;)
#9 /var/www/html/wp-admin/admin-ajax.php(22): require_once(&#039;...&#039;)
#10 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-26 10:03:12 [error X 2][/var/www/html/wp-content/plugins/elementor-pro/modules/global-widget/module.php::28] Uncaught Error: Class &quot;ElementorPro\Modules\GlobalWidget\Data\Controller&quot; not found in /var/www/html/wp-content/plugins/elementor-pro/modules/global-widget/module.php:28
Stack trace:
#0 /var/www/html/wp-content/plugins/elementor/core/base/module.php(85): ElementorPro\Modules\GlobalWidget\Module-&gt;__construct()
#1 /var/www/html/wp-content/plugins/elementor-pro/core/modules-manager.php(86): Elementor\Core\Base\Module::instance()
#2 /var/www/html/wp-content/plugins/elementor-pro/plugin.php(358): ElementorPro\Core\Modules_Manager-&gt;__construct()
#3 /var/www/html/wp-includes/class-wp-hook.php(308): ElementorPro\Plugin-&gt;on_elementor_init()
#4 /var/www/html/wp-includes/class-wp-hook.php(332): WP_Hook-&gt;apply_filters()
#5 /var/www/html/wp-includes/plugin.php(517): WP_Hook-&gt;do_action()
#6 /var/www/html/wp-content/plugins/elementor/includes/plugin.php(652): do_action()
#7 /var/www/html/wp-includes/class-wp-hook.php(308): Elementor\Plugin-&gt;init()
#8 /var/www/html/wp-includes/class-wp-hook.php(332): WP_Hook-&gt;apply_filters()
#9 /var/www/html/wp-includes/plugin.php(517): WP_Hook-&gt;do_action()
#10 /var/www/html/wp-settings.php(617): do_action()
#11 /var/www/html/wp-config.php(91): require_once(&#039;...&#039;)
#12 /var/www/html/wp-load.php(50): require_once(&#039;...&#039;)
#13 /var/www/html/wp-blog-header.php(13): require_once(&#039;...&#039;)
#14 /var/www/html/index.php(17): require(&#039;...&#039;)
#15 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-26 10:39:59 [warning X 6][/var/www/html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key &quot;data&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-29 10:53:53 [notice X 21][/var/www/html/wp-content/plugins/elementor-pro/core/utils/collection.php::75] Return type of ElementorPro\Core\Utils\Collection::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-29 10:54:48 [notice X 3][/var/www/html/wp-content/plugins/elementor-pro/core/database/model-base.php::135] Return type of ElementorPro\Core\Database\Model_Base::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: /var/www/html/wp-content/plugins/elementor-pro/core/database/model-base.php(10): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /var/www/html/wp-content/plugins/elementor-pro/plugin.php(154): class type include()array (
  0 => '/var/www/html/wp-content/plugins/elementor-pro/core/database/model-base.php',
)
#2: /var/www/html/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php(18): ElementorPro\Plugin -> autoload()
#3: /var/www/html/wp-content/plugins/elementor-pro/plugin.php(154): class type include()array (
  0 => '/var/www/html/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php',
)
#4: /var/www/html/wp-content/plugins/elementor-pro/modules/notes/data/controller.php(243): ElementorPro\Plugin -> autoload()
',
)]
PHP: 2022-12-29 14:52:30 [warning X 1][/var/www/html/wp-content/plugins/elementor/core/upgrade/elementor-3-re-migrate-globals.php::102] Undefined variable $active_kit_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-29 14:57:02 [notice X 6][/var/www/html/wp-content/plugins/elementor/core/utils/collection.php::439] Return type of Elementor\Core\Utils\Collection::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 5 of 5JS: 2022-11-29 20:47:45 [error X 4][https://gislavedtrafikskola.se/wp-admin/load-scripts.php?c=1&loadchunk_0=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&loadchunk_1=hooks&ver=6.1.1:4:51816] a is undefined 
JS: 2022-12-29 09:55:54 [error X 83][https://gislavedtrafikskola.se/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.9.2:3:726019] C.$el.resizable is not a function 
JS: 2022-12-29 10:13:03 [error X 2][https://gislavedtrafikskola.se/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.9.2:3:881312] elementorFrontend is not defined 
JS: 2022-12-29 11:01:18 [error X 1][https://gislavedtrafikskola.se/wp-content/plugins/elementor/assets/js/new-template.min.js?ver=3.9.2:2:2932] elementor_new_template_form_controls is not defined 
JS: 2023-01-02 12:46:23 [error X 1][https://gislavedtrafikskola.se/wp-admin/load-scripts.php?c=1&loadchunk_0=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&loadchunk_1=hooks&ver=6.1.1:4:51824] Cannot read properties of undefined (reading \&#039;replace\&#039;) 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Inkompatibel

== Elementor Pro - Compatibility Tag ==
	


````
</details>

**Comment by nicholaszein** [comment]
Hello @Minatanae! 

Thank you for submitting your issue! 🙏 

It seems your issue was likely caused by cache. Can you please confirm that you cleared the server and browser cache after updating Elementor. Did you update to the latest version (3.10), and is the issue still happening with this version installed for both Elementor and Elementor Pro? 

Please let me know. 🧐 

Best regards

**Comment by nicholaszein** [comment]
Hello there @Minatanae, 

### 🕙 It's been a while since we answered you, and we haven't received any feedback. 

## 🚧 For this reason, we are closing this issue because of no activity.

👉 If you wish to continue this discussion, please follow the guidelines for opening a new [🐞 Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml).

Feel free to submit a new issue in accordance with these guidelines. 😉 

Kind regards
