### ISSUE TITLE
Bug with header navigation in Elementor editor when the beta feature page transition is active

### ISSUE THREAD

**Issue by byherskind** [elementor/elementor#20915]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

There is a error with the header/navigation when the beta function Page Transitions is active.

Normally when you edit a page with Elementor (editor open) then the links in the header are "locked" so you can't navigate to another page while the editor is open.

When the page transition function is active then this doesn't work and you can click the menu items and change the page while editing an other page. That also show the new page with the WP admin bar so you can click again "Edit with Elementor" even though the editor is already active. That will of course fuck things up:)

Screen recording: https://www.loom.com/share/28edd7ae67b84d48bc03e7df1a9e103d

### Steps to reproduce

1. Go to Elementor > Settings and activate Page Transitions under Experiments
2. Edit at page with elementor
3. Once the editor is open you can click links in the header (page of course needs to have a header with navigation set first) and the page inside the the Elementor editor will swith according to the menu item or link in the header you clicked (this is normally not possible and is not possible when page transtions is deactivated). 

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.21.5
	MySQL version: mariadb.org binary distribution v10.5.18
	PHP Version: 8.0.26
	PHP Memory Limit: 256M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://demezaphoto.kinsta.cloud
	Home URL: https://demezaphoto.kinsta.cloud
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: da-DK
	Timezone: Europe/Copenhagen
	Admin Email: thomas@byherskind.dk
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.6.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: da_DK
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36

== Active Plugins ==
	Custom Post Type UI
		Version: 1.13.4
		Author: WebDevStudios

	Ele Custom Skin
		Version: 3.1.7
		Author: Dudaster.com

	Ele Custom Skin Pro
		Version: 3.2.4
		Author: Dudaster.com

	Elementor
		Version: 3.9.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.9.2
		Author: Elementor.com

	PowerPack Pro for Elementor
		Version: 2.9.14
		Author: Team IdeaBox - PowerPack Elements

	Yoast SEO
		Version: 19.13
		Author: Team Yoast

== Must-Use Plugins ==
	Kinsta Must-use Plugins
		Version: 3.0.0
		Author: Kinsta Team

== Elements Usage ==
	
	header : 2
		image : 2
		nav-menu : 2
	page : 3
		button : 5
		divider : 4
		heading : 22
		icon-box : 19
		image : 4
		image-carousel : 1
		menu-anchor : 1
		spacer : 5
		testimonial : 3
		text-editor : 9
	section : 4
		button : 1
		divider : 2
		heading : 14
		icon : 1
		icon-list : 5
		image : 6
		image-carousel : 1
		social-icons : 1
		spacer : 4
		text-editor : 5
		video : 1
	wp-post : 1
		button : 1
		divider : 2
		heading : 8
		icon-list : 1
		image : 4
		image-gallery : 1
		spacer : 1
		testimonial : 1
		text-editor : 7
	wp-page : 9
		button : 13
		divider : 9
		heading : 57
		icon-box : 61
		icon-list : 1
		image : 11
		image-box : 3
		image-carousel : 4
		menu-anchor : 3
		spacer : 13
		testimonial : 6
		text-editor : 22
		toggle : 3

== Elementor Experiments ==
	Optimeret DOM-output: Aktiv som standard
	Forbedret ressourceindlæsning : Aktiv som standard
	Forbedret indlæsning af CSS ressourcer: Aktiv som standard
	Inline Font Icons: Inaktiv som standard
	Forbedringer af tilgængeligheden: Aktiv som standard
	Additional Custom Breakpoints: Aktiv som standard
	Import Export Website Kit: Aktiv som standard
	Skjul indbyggede WordPress-widgets fra søgeresultater: Aktiv som standard
	admin_menu_rearrangement: Inaktiv som standard
	Flexbox Container: Inaktiv som standard
	Default to New Theme Builder: Aktiv som standard
	Hello sidehoved og sidefod: Aktiv som standard
	Landingsside: Aktiv som standard
	Color Sampler: Aktiv som standard
	Favorit widgets: Aktiv som standard
	Administrator topbjælke: Aktiv som standard
	Lazy Load baggrundsbilleder: Inaktiv som standard
	Gem som standard: Inaktiv
	Page Transitions: Inaktiv
	Notes: Aktiv som standard
	Loop: Inaktiv
	Modtagne formularer: Aktiv
	Scroll Snap: Aktiv som standard

== Log ==
	
PHP: showing 4 of 4PHP: 2022-11-28 11:09:34 [notice X 12][/www/demezaphoto_123/public/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined index: condition_type [array (
  'trace' => '
#0: /www/demezaphoto_123/public/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /www/demezaphoto_123/public/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /www/demezaphoto_123/public/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /www/demezaphoto_123/public/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2022-12-12 12:59:19 [warning X 1][/www/demezaphoto_123/public/wp-content/plugins/elementor/core/files/file-types/svg.php::234] simplexml_load_file(): I/O warning : failed to load external entity "https://demezaphoto.kinsta.cloud/wp-content/uploads/2022/12/scroll-down-icon.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-16 11:24:41 [error X 2][/www/demezaphoto_123/public/wp-content/plugins/elementor/includes/managers/elements.php::71] Uncaught TypeError: Argument 1 passed to Elementor\Elements_Manager::create_element_instance() must be of the type array, bool given, called in /www/demezaphoto_123/public/wp-content/plugins/powerpack-elements/modules/posts/module.php on line 137 and defined in /www/demezaphoto_123/public/wp-content/plugins/elementor/includes/managers/elements.php:71
Stack trace:
#0 /www/demezaphoto_123/public/wp-content/plugins/powerpack-elements/modules/posts/module.php(137): Elementor\Elements_Manager->create_element_instance(false)
#1 /www/demezaphoto_123/public/wp-includes/class-wp-hook.php(308): PowerpackElements\Modules\Posts\Module->get_post_data('')
#2 /www/demezaphoto_123/public/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#3 /www/demezaphoto_123/public/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /www/demezaphoto_123/public/wp-admin/admin-ajax.php(188): do_action('wp_ajax_pp_get_...')
#5 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-03 18:50:03 [notice X 4][/www/demezaphoto_123/public/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 8 of 8JS: 2022-11-28 12:15:02 [error X 1][https://demezaphoto.kinsta.cloud/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.1:3:851272] Cannot read properties of undefined (reading \'val\') 
JS: 2022-11-29 08:38:17 [error X 59][https://demezaphoto.kinsta.cloud/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:51824] Cannot read properties of undefined (reading \'replace\') 
JS: 2022-11-29 09:08:25 [error X 7][https://demezaphoto.kinsta.cloud/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.1:3:1061530] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2022-11-29 11:14:01 [error X 2][https://demezaphoto.kinsta.cloud/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.1:3:874585] elementorFrontend is not defined 
JS: 2022-12-09 08:22:41 [error X 2][https://demezaphoto.kinsta.cloud/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.1:3:602927] Cannot read properties of undefined (reading \'model\') 
JS: 2022-12-12 14:19:45 [error X 1][https://demezaphoto.kinsta.cloud/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view21460\") has already been destroyed and cannot be used. 
JS: 2022-12-14 09:21:13 [error X 20][https://demezaphoto.kinsta.cloud/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.9.0:2:60518] Cannot convert undefined or null to object 
JS: 2022-12-28 06:51:15 [error X 73][https://demezaphoto.kinsta.cloud/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.9.1:2:60525] Object.entries requires that input parameter not be null or undefined 

Log: showing 20 of 302022-12-16 10:40:13 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0',
  'to' => '3.9.1',
)]
2022-12-16 10:41:20 [info] elementor::elementor_updater Started 
2022-12-16 10:41:20 [info] Elementor/Upgrades - _on_each_version Start  
2022-12-16 10:41:20 [info] Elementor/Upgrades - _on_each_version Finished 
2022-12-16 10:41:20 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0',
  'to' => '3.9.1',
)]
2022-12-16 10:41:20 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.0',
  'to' => '3.9.1',
)]
2022-12-16 10:41:29 [info] elementor-pro::elementor_pro_updater Started 
2022-12-16 10:41:29 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-12-16 10:41:29 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-12-16 10:41:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.0',
  'to' => '3.9.1',
)]
2023-01-03 18:44:40 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.1',
  'to' => '3.9.2',
)]
2023-01-03 18:44:45 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.1',
  'to' => '3.9.2',
)]
2023-01-03 18:45:06 [info] elementor::elementor_updater Started 
2023-01-03 18:45:06 [info] Elementor/Upgrades - _on_each_version Start  
2023-01-03 18:45:06 [info] Elementor/Upgrades - _on_each_version Finished 
2023-01-03 18:45:06 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.1',
  'to' => '3.9.2',
)]
2023-01-03 18:45:08 [info] elementor-pro::elementor_pro_updater Started 
2023-01-03 18:45:08 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-01-03 18:45:08 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-01-03 18:45:08 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.1',
  'to' => '3.9.2',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Kompatibilitet ikke specificeret
	PowerPack Pro for Elementor: Kompatibilitet ikke specificeret

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @byherskind! 

Thank you for submitting your issue! 🙏 

Please allow us some time to investigate it, and get back to you with our findings. 🧐 

Best regards
