### ISSUE TITLE
⛔ 🔗 🐞 Bug Report: Call to Action Button not grabbing proper site settings button styles (Duplicate of #12291)

### ISSUE THREAD

**Issue by seanbajuice** [elementor/elementor#20921]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When editing the Site Settings Button Styles, it's not correctly affecting the button inside a call to action. The call to action button is grabbing it's colors from the Primary Color and ignoring whatever is set in button styles. Additionally if trying to override the button in the CTA button, background color and border color is having no effect, still pulling from primary color. Specifically the hover style.

### Steps to reproduce

Add call to action to the page
Add button to the page
Add primary and secondary colors
Edit border and background colors 
Edit border and background colors for hover

Notice the button on the page is updated but the Call to Action button does not match. Even when trying to override the CTA button still ignores.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release '42', Revision 'b0a7dc2da2e' v5.7.39-42
	PHP Version: 8.0.25
	PHP Memory Limit: 512M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://stonumvineyard.wpengine.com
	Home URL: https://stonumvineyard.wpengine.com
	WP Multisite: No
	Max Upload Size: 50 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%year%/%monthnum%/%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: sean@gorilion.com
	Debug Mode: Inactive

== Theme ==
	Name: Gorilion Hello Elementor Child Theme
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.6.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.9.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.9.2
		Author: Elementor.com

	Yoast Duplicate Post
		Version: 4.5
		Author: Enrico Battocchi & Team Yoast


== Must-Use Plugins ==
	Force Strong Passwords - WPE Edition
		Version: 1.8.0
		Author: Jason Cosper

	WP Engine Cache Plugin
		Version: 1.1.0
		Author: WP Engine

	WP Engine Seamless Login Plugin
		Version: 1.6.0
		Author: WP Engine

	WP Engine Security Auditor
		Version: 1.0.10
		Author: wpengine

	WP Engine System
		Version: 5.0.1
		Author: WP Engine


== Elements Usage ==
	
	footer : 1
		divider : 1
		heading : 2
		social-icons : 1
		text-editor : 1
	header : 1
		image : 1
		nav-menu : 1
	page : 1
		button : 1
		heading : 7
		icon : 3
		text-editor : 4
	section : 0
		divider : 1
		heading : 6
		image : 2
		social-icons : 1
		text-editor : 1
	wp-page : 4
		button : 3
		call-to-action : 4
		divider : 10
		heading : 33
		icon : 3
		image : 13
		spacer : 7
		text-editor : 15


== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Import Export Website Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Lazy Load Background Images: Inactive by default
	Save as Default: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Inactive by default
	Form Submissions: Active by default
	Scroll Snap: Active by default


== Log ==
	
Log: showing 20 of 292022-07-08 14:36:16 [info] Elementor/Upgrades - _on_each_version Finished 
2022-07-08 14:36:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.6',
  'to' => '3.6.7',
)]
2022-07-08 14:36:18 [info] elementor-pro::elementor_pro_updater Started 
2022-07-08 14:36:18 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-07-08 14:36:18 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-07-08 14:36:18 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Start  
2022-07-08 14:36:18 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Finished 
2022-07-08 14:36:18 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.3',
  'to' => '3.7.2',
)]
2022-12-28 21:53:10 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.9.2',
)]
2022-12-28 21:53:10 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.2',
  'to' => '3.9.2',
)]
2022-12-28 21:55:35 [info] elementor::elementor_updater Started 
2022-12-28 21:55:35 [info] Elementor/Upgrades - _on_each_version Start  
2022-12-28 21:55:35 [info] Elementor/Upgrades - _on_each_version Finished 
2022-12-28 21:55:35 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Start  
2022-12-28 21:55:35 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Finished 
2022-12-28 21:55:35 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.9.2',
)]
2022-12-28 21:55:37 [info] elementor-pro::elementor_pro_updater Started 
2022-12-28 21:55:37 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-12-28 21:55:37 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-12-28 21:55:37 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.2',
  'to' => '3.9.2',
)]

PHP: showing 6 of 6PHP: 2022-03-09 20:53:24 [notice X 2][/nas/content/live/gorilionstart/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-09 20:57:57 [notice X 1][/nas/content/live/gorilionstart/wp-content/plugins/elementor/includes/managers/image.php::87] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-03 22:54:05 [warning X 5][/nas/content/live/stonumvineyard/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-04 05:37:36 [error X 1][/nas/content/live/stonumvineyard/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on null in /nas/content/live/stonumvineyard/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /nas/content/live/stonumvineyard/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(28, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /nas/content/live/stonumvineyard/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /nas/content/live/stonumvineyard/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /nas/content/live/stonumvineyard/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#5 /nas/content/live/stonumvineyard/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /nas/content/live/stonumvineyard/wp-admin/admin-ajax.php(188): do_action('wp_ajax_element...')
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-04 18:12:57 [error X 1][/nas/content/live/stonumvineyard/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on bool in /nas/content/live/stonumvineyard/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /nas/content/live/stonumvineyard/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /nas/content/live/stonumvineyard/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /nas/content/live/stonumvineyard/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /nas/content/live/stonumvineyard/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#5 /nas/content/live/stonumvineyard/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /nas/content/live/stonumvineyard/wp-admin/admin-ajax.php(188): do_action('wp_ajax_element...')
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-04 20:10:52 [error X 1][/nas/content/live/stonumvineyard/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on null in /nas/content/live/stonumvineyard/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /nas/content/live/stonumvineyard/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(7, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /nas/content/live/stonumvineyard/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /nas/content/live/stonumvineyard/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /nas/content/live/stonumvineyard/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#5 /nas/content/live/stonumvineyard/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /nas/content/live/stonumvineyard/wp-admin/admin-ajax.php(188): do_action('wp_ajax_element...')
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 1 of 1JS: 2022-03-09 20:58:31 [error X 1][https://gorilionstart.wpengine.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.6:2:453890] Cannot read properties of null (reading \'getBoundingClientRect\') 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Incompatible

== Elementor Pro - Compatibility Tag ==
	

				

````
</details>

**Comment by nicholaszein** [comment]
Hello @seanbajuice,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
* This is the expected behavior since the CTA widget has its own styles (especially if you select the `Cover` skin.
* See also issue #12291.

### ✅ What you can do to solve your issue:
* We have no plans to change this behavior at this moment, but if you feel this could be a nice feature, please submit a [new Feature Request](https://github.com/orgs/elementor/discussions/new?category=feature-request).

For now, that's all we can help with. 

Kind regards
