### ISSUE TITLE
⛔ 🐞 Bug Report: Unable to render JS code in HTML element

### ISSUE THREAD

**Issue by landisoam** [elementor/elementor#20962]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Elementor HTML element is not working. 

### Steps to reproduce

1. Use HTML element 
2. Write in JS code 
3. Unable to render JS code

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release 23, Revision 500fcf5 v5.7.23-23
	PHP Version: 8.1.13
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 516M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://www.aserious.co
	Home URL: https://www.aserious.co
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 8
	Admin Email: admin@aserious.co
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6 Safari/605.1.15

== Active Plugins ==
	Autoptimize
		Version: 3.1.4
		Author: Frank Goossens (futtta)

	Burst Statistics - Privacy-Friendly Analytics for WordPress
		Version: 1.3.2
		Author: Really Simple Plugins

	Elementor
		Version: 3.11.0-dev3
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.10.0-dev1
		Author: Elementor.com

	HostGator
		Version: 1.2.4
		Author: HostGator

	Really Simple SSL
		Version: 6.0.14
		Author: Really Simple Plugins

	WPAdmin AWS CDN
		Version: 2.0.12
		Author: WPAdmin

	WPtouch Mobile Plugin
		Version: 4.3.46
		Author: WPtouch

	Yoast SEO
		Version: 19.13
		Author: Team Yoast


== Must-Use Plugins ==
	burst_rest_api_optimizer.php
		Version: 
		Author: 

	Endurance Page Cache
		Version: 2.2
		Author: Mike Hansen

	Jetpack Server Compatibility for WordPress
		Version: 1.0.13
		Author: Automattic


== Elements Usage ==
	
	container : 0
		button : 9
		container : 6
		google_maps : 1
		heading : 20
		icon-box : 4
		icon-list : 4
		image : 17
		image-box : 13
		social-icons : 2
		spacer : 1
		testimonial : 3
		text-editor : 8
		video : 4
	page : 4
		button : 13
		divider : 1
		heading : 9
		icon : 8
		image : 1
		image-carousel : 1
		spacer : 5
		text-editor : 17
	section : 2
		heading : 3
		image : 1
		text-editor : 1
	wp-page : 8
		animated-headline : 5
		button : 15
		container : 35
		heading : 56
		html : 1
		icon-box : 4
		image : 38
		image-box : 22
		image-carousel : 1
		testimonial : 3
		testimonial-carousel : 1
		text-editor : 44
		video : 1


== Settings ==
	
	cpt_support: post, page, e-landing-page
	disable_color_schemes: yes
	allow_tracking: yes
	css_print_method: internal
	editor_break_lines: 1
	unfiltered_files_upload: 1
	font_display: swap


== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Editor V2: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default
	Save as Default: Active by default
	Page Transitions: Active
	Notes: Active by default
	Loop: Active
	Form Submissions: Active by default
	Scroll Snap: Active


== Log ==
	
Log: showing 17 of 172022-11-12 02:07:45 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-11-12 02:07:45 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.1',
  'to' => '3.10.0-dev1',
)]
2022-11-12 02:07:45 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.1',
  'to' => '3.10.0-dev1',
)]
2022-12-14 17:35:10 [info] elementor::elementor_updater Started 
2022-12-14 17:35:10 [info] Elementor/Upgrades - _on_each_version Start  
2022-12-14 17:35:10 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.0-dev1',
  'to' => '3.11.0-dev1',
)]
2022-12-14 17:35:10 [info] Elementor/Upgrades - _on_each_version Finished 
2022-12-14 17:35:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.0-dev1',
  'to' => '3.11.0-dev1',
)]
2022-12-20 03:06:12 [info] elementor::elementor_updater Started 
2022-12-20 03:06:12 [info] Elementor/Upgrades - _on_each_version Start  
2022-12-20 03:06:13 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.0-dev1',
  'to' => '3.11.0-dev2',
)]
2022-12-20 03:06:13 [info] Elementor/Upgrades - _on_each_version Finished 
2022-12-20 03:06:13 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.0-dev1',
  'to' => '3.11.0-dev2',
)]
2023-01-10 17:19:48 [info] elementor::elementor_updater Started 
2023-01-10 17:19:48 [info] Elementor/Upgrades - _on_each_version Start  
2023-01-10 17:19:48 [info] Elementor/Upgrades - _on_each_version Finished 
2023-01-10 17:19:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.0-dev2',
  'to' => '3.11.0-dev3',
)]

PHP: showing 10 of 10PHP: 2022-11-17 14:45:28 [notice X 9][/home4/m3clvw4d/aserious.co/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-17 16:07:47 [notice X 142][/home4/m3clvw4d/aserious.co/wp-content/plugins/elementor/core/logger/items/js.php::17] Undefined index: url [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-18 13:35:46 [error X 1][/home4/m3clvw4d/aserious.co/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on bool in /home4/m3clvw4d/aserious.co/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /home4/m3clvw4d/aserious.co/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home4/m3clvw4d/aserious.co/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home4/m3clvw4d/aserious.co/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home4/m3clvw4d/aserious.co/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#5 /home4/m3clv [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-26 13:25:37 [notice X 244][/home4/m3clvw4d/aserious.co/wp-content/plugins/elementor-pro/core/database/model-base.php::135] Return type of ElementorPro\Core\Database\Model_Base::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: /home4/m3clvw4d/aserious.co/wp-content/plugins/elementor-pro/core/database/model-base.php(10): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home4/m3clvw4d/aserious.co/wp-content/plugins/elementor-pro/plugin.php(154): class type include()array (
  0 => '/home4/m3clvw4d/aserious.co/wp-content/plugins/elementor-pro/core/database/model-base.php',
)
#2: /home4/m3clvw4d/aserious.co/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php(18): ElementorPro\Plugin -> autoload()
#3: /home4/m3clvw4d/aserious.co/wp-content/plugins/elementor-pro/plugin.php(154): class type include()array (
  0 => '/home4/m3clvw4d/aserious.co/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php',
)
#4: /home4/m3clvw4d/aserious.co/wp-content/plugins/elementor-pro/modules/notes/data/controller.php(243): ElementorPro\Plugin -> autoload()
',
)]
PHP: 2022-11-30 18:06:16 [warning X 3][/home4/m3clvw4d/aserious.co/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-30 18:23:12 [warning X 15][/home4/m3clvw4d/aserious.co/wp-content/plugins/elementor/core/logger/items/js.php::17] Undefined array key "url" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-30 18:26:39 [notice X 39][/home4/m3clvw4d/aserious.co/wp-content/plugins/elementor-pro/core/utils/collection.php::75] Return type of ElementorPro\Core\Utils\Collection::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-14 01:50:53 [notice X 2][/home4/m3clvw4d/aserious.co/wp-content/plugins/elementor/modules/performance-lab/module.php::31] Optional parameter $size declared before required parameter $url is implicitly treated as a required parameter [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-14 17:25:22 [error X 1][/home4/m3clvw4d/aserious.co/wp-content/plugins/elementor/includes/controls/date-time.php::51] Uncaught Error: Undefined constant Elementor\Modules\DynamicTags\Module::DATETIME_CATEGORY in /home4/m3clvw4d/aserious.co/wp-content/plugins/elementor/includes/controls/date-time.php:51
Stack trace:
#0 /home4/m3clvw4d/aserious.co/wp-content/plugins/elementor/includes/controls/base.php(73): Elementor\Control_Date_Time->get_default_settings()
#1 /home4/m3clvw4d/aserious.co/wp-content/plugins/elementor/includes/controls/base-data.php(19): Elementor\Base_Control->__construct()
#2 /home4/m3clvw4d/aserious.co/wp-content/plugins/elementor/includes/managers/controls.php(436): Elementor\Base_Data_Control->__construct()
#3 /home4/m3clvw4d/aserious.co/wp-content/plugins/elementor/includes/managers/controls.php(589): Elementor\Controls_Manager->register_controls()
#4 /home4/m3clvw4d/aserious.co/wp-content/plugins/elementor/includes/managers/controls.php(608): Elementor\Controls_Manager->get_controls()
#5 /home4/m3clvw4d/aserious.co/wp-content/plugins/elementor/includes/managers/controls.php(779): Elementor\Controls_Manager->get_control('section')
#6 /home4/m3clvw4d/aserious.co/wp-content/plugins/elementor/includes/base/controls-stack.php(421): Elementor\Controls_Manager->add_control_to_stack(Object(Elementor\Core\Kits\Documents\Kit), 'document_settin...', Array, Array)
#7 /home4/m3clvw4d/aserious.co/wp-content/plugins/elementor/includes/base/controls-stack.php(1518): Elementor\Controls_Stack->add_control('document_settin...', Array)
#8 /home4/m3clvw4d/aserious.co/wp-content/plugins/elementor/core/base/document.php(1675): Elementor\Controls_Stack->start_controls_section('document_settin...', Array)
#9 /home4/m3clvw4d/aserious.co/wp-content/plugins/elementor/core/kits/documents/kit.php(155): Elementor\Core\Base\Document->register_document_controls()
#10 /home4/m3clvw4d/aserious.co/wp-content/plugins/elementor/includes/base/controls-stack.php(2327): Elementor\Core\Kits\Documents\Kit->register_controls()
#11 /home4/m3clvw4d/aserious.co/wp-content/plugins/elementor/includes/base/controls-stack.php(496): Elementor\Controls_Stack->init_controls()
#12 /home4/m3clvw4d/aserious.co/wp-content/plugins/elementor/includes/base/controls-stack.php(300): Elementor\Controls_Stack->get_stack()
#13 /home4/m3clvw4d/aserious.co/wp-content/plugins/elementor/includes/base/controls-stack.php(2414): Elementor\Controls_Stack->get_controls()
#14 /home4/m3clvw4d/aserious.co/wp-content/plugins/elementor/includes/base/controls-stack.php(1107): Elementor\Controls_Stack->sanitize_settings(Array)
#15 /home4/m3clvw4d/aserious.co/wp-content/plugins/elementor/includes/base/controls-stack.php(2161): Elementor\Controls_Stack->get_data('settings')
#16 /home4/m3clvw4d/aserious.co/wp-content/plugins/elementor/core/base/base-object.php(142): Elementor\Controls_Stack->get_init_settings()
#17 /home4/m3clvw4d/aserious.co/wp-content/plugins/elementor/core/base/base-object.php(40): Elementor\Core\Base\Base_Object->ensure_settings()
#18 /home4/m3clvw4d/aserious.co/wp-content/plugins/elementor/core/kits/manager.php(117): Elementor\Core\Base\Base_Object->get_settings('viewport_mobile')
#19 /home4/m3clvw4d/aserious.co/wp-content/plugins/elementor/core/breakpoints/breakpoint.php(130): Elementor\Core\Kits\Manager->get_current_settings('viewport_mobile')
#20 /home4/m3clvw4d/aserious.co/wp-content/plugins/elementor/core/breakpoints/breakpoint.php(71): Elementor\Core\Breakpoints\Breakpoint->init_value()
#21 /home4/m3clvw4d/aserious.co/wp-content/plugins/elementor/core/breakpoints/breakpoint.php(88): Elementor\Core\Breakpoints\Breakpoint->get_value()
#22 /home4/m3clvw4d/aserious.co/wp-content/plugins/elementor/core/breakpoints/manager.php(195): Elementor\Core\Breakpoints\Breakpoint->is_custom()
#23 /home4/m3clvw4d/aserious.co/wp-content/plugins/elementor/includes/frontend.php(525): Elementor\Core\Breakpoints\Manager->has_custom_breakpoints()
#24 /home4/m3clvw4d/aserious.co/wp-includes/class-wp-hook.php(308): Elementor\Frontend->register_styles('')
#25 /home4/m3clvw4d/aserious.co/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#26 /home4/m3clvw4d/aserious.co/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#27 /home4/m3clvw4d/aserious.co/wp-includes/script-loader.php(2180): do_action('wp_enqueue_scri...')
#28 /home4/m3clvw4d/aserious.co/wp-includes/class-wp-hook.php(308): wp_enqueue_scripts('')
#29 /home4/m3clvw4d/aserious.co/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#30 /home4/m3clvw4d/aserious.co/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#31 /home4/m3clvw4d/aserious.co/wp-includes/general-template.php(3043): do_action('wp_head')
#32 /home4/m3clvw4d/aserious.co/wp-content/plugins/elementor/modules/page-templates/templates/canvas.php(19): wp_head()
#33 /home4/m3clvw4d/aserious.co/wp-includes/template-loader.php(106): include('/home4/m3clvw4d...')
#34 /home4/m3clvw4d/aserious.co/wp-blog-header.php(19): require_once('/home4/m3clvw4d...')
#35 /home4/m3clvw4d/aserious.co/index.php(17): require('/home4/m3clvw4d...')
#36 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-14 17:25:24 [error X 1][/home4/m3clvw4d/aserious.co/wp-content/plugins/elementor/modules/system-info/reporters/server.php::103] Uncaught Error: Call to undefined method Elementor\Utils::get_super_global_value() in /home4/m3clvw4d/aserious.co/wp-content/plugins/elementor/modules/system-info/reporters/server.php:103
Stack trace:
#0 /home4/m3clvw4d/aserious.co/wp-content/plugins/elementor/modules/system-info/reporters/base.php(148): Elementor\Modules\System_Info\Reporters\Server->get_software()
#1 /home4/m3clvw4d/aserious.co/wp-content/plugins/elementor/includes/tracker.php(251): Elementor\Modules\System_Info\Reporters\Base->get_report()
#2 /home4/m3clvw4d/aserious.co/wp-content/plugins/elementor/includes/tracker.php(530): Elementor\Tracker::get_system_reports_data()
#3 /home4/m3clvw4d/aserious.co/wp-content/plugins/elementor/includes/tracker.php(141): Elementor\Tracker::get_tracking_data(false)
#4 /home4/m3clvw4d/aserious.co/wp-includes/class-wp-hook.php(308): Elementor\Tracker::send_tracking_data()
#5 /home4/m3clvw4d/aserious.co/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#6 /home4/m3clvw4d/aserious.co/wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#7 /home4/m3clvw4d/aserious.co/wp-cron.php(188): do_action_ref_array('elementor/track...', Array)
#8 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 15 of 15JS: 2022-11-17 07:40:46 [error X 3][https://www.aserious.co/wp-content/plugins/elementor/assets/js/frontend.js?ver=3.10.0-dev1:1958:25] elementorFrontendConfig is not defined 
JS: 2022-11-17 08:07:28 [error X 50677][https://www.aserious.co/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:16820] Cannot read properties of null (reading \'clone\') 
JS: 2022-11-17 08:07:35 [error X 1195][https://www.aserious.co/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:21012] Cannot read properties of null (reading \'changestop\') 
JS: 2022-11-17 10:02:40 [error X 14][https://www.aserious.co/wp-content/plugins/elementor/assets/js/editor.js?ver=3.10.0-dev1:45514:29] Cannot read properties of undefined (reading \'settings\') 
JS: 2022-11-17 10:03:59 [error X 2][https://www.aserious.co/wp-content/plugins/elementor/assets/js/editor.js?ver=3.10.0-dev1:45770:22] Cannot read properties of undefined (reading \'view\') 
JS: 2022-11-17 10:16:13 [error X 2][https://www.aserious.co/wp-content/plugins/elementor/assets/js/editor.js?ver=3.10.0-dev1:54649:44] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2022-11-19 10:00:22 [error X 30][https://www.aserious.co/wp-content/plugins/elementor/assets/js/lazyload.js?ver=3.10.0-dev1:23:38] Cannot read properties of undefined (reading \'add\') 
JS: 2022-11-30 10:09:31 [error X 2][https://www.aserious.co/wp-content/plugins/elementor/assets/js/editor.js?ver=3.10.0-dev1:45514:28] undefined is not an object (evaluating \'container.settings\') 
JS: 2022-11-30 10:22:58 [error X 4413][https://www.aserious.co/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:16819] null is not an object (evaluating \'this._lastColor.clone\') 
JS: 2022-11-30 10:22:59 [error X 31][https://www.aserious.co/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:21012] null is not an object (evaluating \'this._eventListener[t]\') 
JS: 2022-11-30 10:25:28 [error X 3][https://www.aserious.co/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:19667] null is not an object (evaluating \'this.getColorRepresentation().toLowerCase\') 
JS: 2023-01-09 08:26:52 [error X 1][https://www.aserious.co/wp-content/plugins/elementor/assets/js/editor.js?ver=3.11.0-dev3:45659:28] undefined is not an object (evaluating 'container.settings') 
JS: 2023-01-09 10:10:22 [error X 2][https://www.aserious.co/wp-includes/js/jquery/jquery.js?ver=3.6.1:6621:13] undefined is not an object (evaluating 'ret.replace') 
JS: 2023-01-09 10:29:22 [error X 473][https://www.aserious.co/wp-includes/js/jquery/jquery.js?ver=3.6.1:5221:11] Attempted to assign to readonly property. 
JS: 2023-01-10 07:30:59 [error X 6][https://www.aserious.co/wp-content/plugins/elementor/assets/js/editor.js?ver=3.11.0-dev3:38883:11] undefined is not an object (evaluating 'this.store.find(function (element) { return element.original === char; }).localized') 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==
	

				

````
</details>

**Comment by nicholaszein** [comment]
Hello @landisoam,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
* Depending on what you write and how you write as a custom HTML code (`<script>`) in the HTML widget, WordPress (**<ins>NOT ELEMENTOR</ins>**) will remove the code from the fron-end to avoid malicious code injection. This is called `sanitization`, which is what Elementor uses, by default, following WordPress Coding Standards, to render content. 
* This is not the HTML widget not working, this is simply WordPress removing code it deems suspicious. There is nothing we can do about it.

### ✅ What you can do to solve your issue:
* Either use a dedicated plugin to inject your code (like [Code Snippets](https://wordpress.org/plugins/code-snippets/)).
* Or use [Elementor Pro's Custom Code](https://elementor.com/help/custom-code-pro/) feature.
* We do not recommend inline JS injection using the HTML widget.

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* Please create GitHub issues **only for Elementor bugs**. GitHub issues ARE NOT FOR SUPPORT or for issues with 3rd party plugins.
* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

### ⚠️ Please Note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
