### ISSUE TITLE
⛔ 🐞 Bug Report: Can't load editor on custom post types if the user doesn't have the edit_posts role

### ISSUE THREAD

**Issue by mattmary** [elementor/elementor#21032]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hello,

I'm trying to create a limited profile which is able to edit only one custom post type.
I granted all related rights to this post type and the read one.
I also enabled the Elementor usage on this custom post type.

Unfortunately, when I try to edit this custom post type with Elementor, the loading fails: some elements loaded in ajax are not loaded. It looks like some of your controllers expect the edit_post role.

- Modules\KitElementsDefaults\Data\Controller
- Core\Editor\Data\Globals\Controller

Can you update your controllers to check if the user as the custom post type access right?

### Steps to reproduce

* Create a custom post type cpt with capability_type cpt.
* Create a user profile with the following ACL:
   * read
   * read_cpt
   * 'read_private_cpt
   * edit_cpt
   * edit_cpts
   * edit_others_cpt
   * edit_others_cpts
   * edit_published_cpt
   * publish_cpt
   * publish_cpts
   * delete_others_cpt
   * delete_private_cpt
   * delete_published_cpt
   * delete_cpt
   * delete_cpts
* Allow Elementor usage with this custom post type
* Create an user account with this new profile
* Log in with this account
* Try to edit with Elementor a new element of this custom post type: The interface does not load and there are 403 errors in the console.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt

					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.52 (Ubuntu)
	MySQL version: (Ubuntu) v8.0.31
	PHP Version: 8.0.26
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://local.mywebsite.org
	Home URL: https://local.mywebsite.org
	WP Multisite: No
	Max Upload Size: 8 MB
	Memory limit: 512M
	Max Memory limit: 512M
	Permalink Structure: /blog/%year%/%monthnum%/%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: hello@mywebsite.org
	Debug Mode: Inactive

== Theme ==
	Name: website-child
	Version: 1.3
	Author: the mywebsite team
	Child Theme: Yes
	Parent Theme Name: GeneratePress
	Parent Theme Version: 3.2.4
	Parent Theme Author: Tom Usborne

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0

== Active Plugins ==
	Advanced Custom Fields
		Version: 6.0.6
		Author: WP Engine

	Audit Trail Countries Stats
		Version: 1.0
		Author: Matthieu MARY

	Better Find and Replace
		Version: 1.4.3
		Author: CodeSolz

	Clean Notifications
		Version: 1.1
		Author: Mike Davidson

	Debug Bar
		Version: 1.1.4
		Author: wordpressdotorg

	Disable XML-RPC
		Version: 1.0.1
		Author: Philip Erb

	Duplicate Page
		Version: 4.5
		Author: mndpsingh287

	Elementor
		Version: 3.9.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.9.2
		Author: Elementor.com

	Enable Contributor Uploads
		Version: 1.1
		Author: Road Warrior Creative

	Enable Media Replace
		Version: 4.0.1
		Author: ShortPixel

	GP Premium
		Version: 2.2.2
		Author: Tom Usborne

	Gravity Forms
		Version: 2.6.8
		Author: Gravity Forms

	Gravity Forms + Custom Post Types
		Version: 3.1.29
		Author: Gravity Wiz

	Gravity Forms Multilingual
		Version: 1.6.3
		Author: OnTheGoSystems

	iThemes Security
		Version: 8.1.4
		Author: iThemes

	Markdown
		Version: 1.0
		Author: Piotr Niewiadomski

	Max Mega Menu
		Version: 3.0
		Author: megamenu.com

	Max Mega Menu - Pro Addon
		Version: 2.2.7
		Author: megamenu.com

	Minimum comment length
		Version: 1.1
		Author: Team Yoast

	Open External Links in a New Window
		Version: 1.44
		Author: WebFactory Ltd

	Piwik
		Version: 1.1.2
		Author: mywebsite.org

	Piwik_Login
		Version: 1.1.1
		Author: mywebsite.org

	Plugin Security Scanner
		Version: 2.0.2
		Author: Glen Scott

	Prevent XSS Vulnerability
		Version: 2.0.1
		Author: Sami Ahmed Siddiqui

	Relevanssi
		Version: 4.18.2
		Author: Mikko Saari

	Shortcode Functions
		Version: 1.0
		Author: Piotr Niewiadomski

	Shortlink2Permalink
		Version: 1.0
		Author: Piotr Niewiadomski

	ShortPixel Adaptive Images
		Version: 3.6.1
		Author: ShortPixel

	ShortPixel Image Optimizer
		Version: 5.1.6
		Author: ShortPixel - Convert WebP/AVIF & Optimize Images

	Simple 301 Redirects
		Version: 2.0.7
		Author: WPDeveloper

	SSL Insecure Content Fixer
		Version: 2.7.2
		Author: WebAware

	Sucuri Security - Auditing, Malware Scanner and Hardening
		Version: 1.8.36
		Author: Sucuri Inc.

	TablePress
		Version: 2.0.2
		Author: Tobias Bäthge

	TOC
		Version: 1.0
		Author: Piotr Niewiadomski

	User Role Editor
		Version: 4.63.2
		Author: Vladimir Garagulya

	Views
		Version: 1.0.0
		Author: Piotr Niewiadomski

	Walker
		Version: 1.0
		Author: Piotr Niewiadomski

	wBounce
		Version: 1.8.1
		Author: Kevin Weber

	WordPress Force HTTPS
		Version: 0.1.4
		Author: A. Kai Armstrong

	WP Activity Log
		Version: 4.4.3
		Author: WP White Security

	WPML Multilingual CMS
		Version: 4.5.14
		Author: OnTheGoSystems

	WP Rocket
		Version: 3.12.4
		Author: WP Media

	WP Synchro
		Version: 1.9.0
		Author: WPSynchro

	Yoast SEO
		Version: 19.13
		Author: Team Yoast


== Must-Use Plugins ==
	WP Synchro MU plugin
		Version: 1.0.5
		Author: WP Synchro


== Elementor Experiments ==
	Optimized DOM Output: Inactive by default
	Improved Asset Loading: Inactive by default
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Inactive by default
	Additional Custom Breakpoints: Inactive by default
	Import Export Website Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Lazy Load Background Images: Inactive by default
	Save as Default: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Inactive by default
	Form Submissions: Active by default
	Scroll Snap: Active by default


== Log ==
	
Log: showing 20 of 372022-12-19 21:56:40 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.1',
  'to' => '3.9.1',
)]
2022-12-19 21:56:41 [info] elementor::elementor_updater Started 
2022-12-19 21:56:41 [info] Elementor/Upgrades - _on_each_version Start  
2022-12-19 21:56:41 [info] Elementor/Upgrades - _on_each_version Finished 
2022-12-19 21:56:42 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.1',
  'to' => '3.9.1',
)]
2022-12-19 21:56:44 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.1',
  'to' => '3.9.1',
)]
2022-12-19 22:02:33 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.2',
  'to' => '3.9.1',
)]
2022-12-19 22:02:35 [info] elementor-pro::elementor_pro_updater Started 
2022-12-19 22:02:35 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-12-19 22:02:35 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-12-19 22:02:35 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.2',
  'to' => '3.9.1',
)]
2022-12-19 22:02:38 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.2',
  'to' => '3.9.1',
)]
2023-01-03 22:21:36 [info] elementor::elementor_updater Started 
2023-01-03 22:21:36 [info] Elementor/Upgrades - _on_each_version Start  
2023-01-03 22:21:36 [info] Elementor/Upgrades - _on_each_version Finished 
2023-01-03 22:21:36 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.1',
  'to' => '3.9.2',
)]
2023-01-03 22:21:44 [info] elementor-pro::elementor_pro_updater Started 
2023-01-03 22:21:44 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-01-03 22:21:44 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-01-03 22:21:44 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.1',
  'to' => '3.9.2',
)]

PHP: showing 4 of 4PHP: 2022-11-20 23:58:25 [error X 1][/home/myuser/storage/www/piwik.org/wp-content/plugins/elementor-pro/modules/theme-builder/documents/archive-single-base.php::11] Uncaught Error: Interface "ElementorPro\Base\MarkerInterfaces\Archive_Template_Interface" not found in /home/myuser/storage/www/piwik.org/wp-content/plugins/elementor-pro/modules/theme-builder/documents/archive-single-base.php:11
Stack trace:
#0 /home/myuser/storage/www/piwik.org/wp-content/plugins/elementor-pro/plugin.php(153): include()
#1 /home/myuser/storage/www/piwik.org/wp-content/plugins/elementor-pro/modules/theme-builder/documents/single-base.php(12): ElementorPro\Plugin->autoload('ElementorPro\\Mo...')
#2 /home/myuser/storage/www/piwik.org/wp-content/plugins/elementor-pro/plugin.php(153): include('/home/myuser/sto...')
#3 /home/myuser/storage/www/piwik.org/wp-content/plugins/elementor-pro/modules/theme-builder/documents/single.php(8): ElementorPro\Plugin->autoload('ElementorPro\\Mo...')
#4 /home/myuser/storage/www/piwik.org/wp-content/plugins/elementor-pro/plugin.php(153): include('/home/myuser/sto...')
#5 /home/myuser/storage/www/piwik.org/wp-content/plugins/elementor-pro/modules/theme-builder/classes/templates-types-manager.php(39): ElementorPro\Plugin->autoload('ElementorPro\\Mo...')
#6 /home/myuser/storage/www/piwik.org/wp-includes/class-wp-hook.php(307): ElementorPro\Modules\ThemeBuilder\Classes\Templates_Types_Manager->register_documents(Object(Elementor\Core\Documents_Manager))
#7 /home/myuser/storage/www/piwik.org/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#8 /home/myuser/storage/www/piwik.org/wp-includes/plugin.php(474): WP_Hook->do_action(Array)
#9 /home/myuser/storage/www/piwik.org/wp-content/plugins/elementor/core/documents-manager.php(692): do_action('elementor/docum...', Object(Elementor\Core\Documents_Manager))
#10 /home/myuser/storage/www/piwik.org/wp-content/plugins/elementor/core/documents-manager.php(177): Elementor\Core\Documents_Manager->register_types()
#11 /home/myuser/storage/www/piwik.org/wp-content/plugins/elementor/core/editor/editor.php(237): Elementor\Core\Documents_Manager->get(NULL)
#12 /home/myuser/storage/www/piwik.org/wp-content/plugins/elementor/includes/frontend.php(188): Elementor\Core\Editor\Editor->is_edit_mode()
#13 /home/myuser/storage/www/piwik.org/wp-includes/class-wp-hook.php(307): Elementor\Frontend->init_render_mode('')
#14 /home/myuser/storage/www/piwik.org/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#15 /home/myuser/storage/www/piwik.org/wp-includes/plugin.php(474): WP_Hook->do_action(Array)
#16 /home/myuser/storage/www/piwik.org/wp-includes/template-loader.php(13): do_action('template_redire...')
#17 /home/myuser/storage/www/piwik.org/wp-blog-header.php(19): require_once('/home/myuser/sto...')
#18 /home/myuser/storage/www/piwik.org/index.php(17): require('/home/myuser/sto...')
#19 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-05 23:53:33 [error X 2][/home/myuser/storage/www/piwik.org/wp-content/plugins/elementor/data/v2/base/controller.php::227] Uncaught Elementor\Data\V2\Base\Exceptions\WP_Error_Exception: Method 'WP_REST_Controller::get_item_permissions_check' not implemented. Must be overridden in subclass. in /home/myuser/storage/www/piwik.org/wp-content/plugins/elementor/data/v2/base/controller.php:227
Stack trace:
#0 /home/myuser/storage/www/piwik.org/wp-content/plugins/elementor/data/v2/base/base-route.php(105): Elementor\Data\V2\Base\Controller->get_permission_callback(Object(WP_REST_Request))
#1 /home/myuser/storage/www/piwik.org/wp-content/plugins/elementor/data/v2/base/base-route.php(242): Elementor\Data\V2\Base\Base_Route->get_permission_callback(Object(WP_REST_Request))
#2 /home/myuser/storage/www/piwik.org/wp-includes/rest-api/class-wp-rest-server.php(1138): Elementor\Data\V2\Base\Base_Route->Elementor\Data\V2\Base\{closure}(Object(WP_REST_Request))
#3 /home/myuser/storage/www/piwik.org/wp-includes/rest-api/class-wp-rest-server.php(1018): WP_REST_Server->respond_to_request(Object(WP_REST_Request), '/elementor/v1/f...', Array, NULL)
#4 /home/myuser/storage/www/piwik.org/wp-includes/rest-api/class-wp-rest-server.php(442): WP_REST_Server->dispatch(Object(WP_REST_Request))
#5 /home/myuser/storage/www/piwik.org/wp-includes/rest-api.php(410): WP_REST_Server->serve_request('/elementor/v1/f...')
#6 /home/myuser/storage/www/piwik.org/wp-includes/class-wp-hook.php(308): rest_api_loaded(Object(WP))
#7 /home/myuser/storage/www/piwik.org/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#8 /home/myuser/storage/www/piwik.org/wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#9 /home/myuser/storage/www/piwik.org/wp-includes/class-wp.php(399): do_action_ref_array('parse_request', Array)
#10 /home/myuser/storage/www/piwik.org/wp-includes/class-wp.php(780): WP->parse_request('')
#11 /home/myuser/storage/www/piwik.org/wp-includes/functions.php(1332): WP->main('')
#12 /home/myuser/storage/www/piwik.org/wp-blog-header.php(16): wp()
#13 /home/myuser/storage/www/piwik.org/index.php(17): require('/home/myuser/sto...')
#14 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-06 16:14:29 [warning X 4][/home/myuser/storage/www/piwik.org/wp-content/plugins/elementor-pro/modules/forms/classes/ajax-handler.php::270] Undefined array key "post_id" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-13 22:30:44 [warning X 4][/home/myuser/storage/www/piwik.org/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 2 of 2JS: 2022-12-06 22:31:43 [error X 2][https://fr.mywebsite.org/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.1:3:540651] Blocked a frame with origin \"https://fr.mywebsite.org\" from accessing a cross-origin frame. 
JS: 2022-12-15 23:58:28 [error X 2][https://mywebsite.org/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:51816] a is undefined 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==
	

				

````
</details>

**Comment by nicholaszein** [comment]
Hello @mattmary,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
* This is the expected behavior. To use Elementor the user needs to have the `edit_posts` capability.
* The user needs to be able to edit Elementor Templates as well as Global Settings (Template Kits).
* We do not support what you're reporting as a bug.

### ✅ What you can do to solve your issue:
* Add the `edit_posts` capability to your custom role.

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* Please create GitHub issues **only for Elementor bugs**. GitHub issues ARE NOT FOR SUPPORT or for issues with 3rd party plugins.
* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

### ⚠️ Please Note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

👉 If you think this could be added as a feature, please submit a [Feature Request](https://github.com/orgs/elementor/discussions/new?category=feature-request) and we will add it if there is enough demand from other users. But first, make sure you [search for similar feature requests](https://github.com/elementor/elementor/issues?q=is%3Aopen+is%3Aissue+Role+Manager+label%3Arequest%2Fenhancement) to avoid duplicates.

Kind regards
