### ISSUE TITLE
Infinite Scroll on Post Widget Breaking CSS on Image Rounder Borders.

### ISSUE THREAD

**Issue by maurocarreraok** [elementor/elementor#21081]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

As you can see in this video: https://www.loom.com/share/5e57a28eb48f478d99de8b56746d2f6a

When infinite scroll loads more post, break the CSS on the images of the post. Before infinite scroll images borders are working, then, then more post are loaded, the borders are not-rounded.

### Steps to reproduce

Add post's to have the option of infinite load working.
Add roudned corners to the thumb image of the post.
Scroll till inifinite scroll load more posts
Now the images are not rounded.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.39-42
	PHP Version: x
	PHP Memory Limit: x
	PHP Max Input Vars: x
	PHP Max Post Size: x
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://c42.studio
	Home URL: https://c42.studio
	WP Multisite: No
	Max Upload Size: x
	Memory limit: x
	Max Memory limit: x
	Permalink Structure:x
	Language: en-US
	Timezone: -3
	Admin Email: x
	Debug Mode: Inactive

== Theme ==
	Name: C42.Studio
	Version: 1.0
	Author: C42.Studio
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.6.1
	Parent Theme Author: Elementor Team

== Active Plugins ==
	Elementor
		Version: 3.10.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.10.1
		Author: Elementor.com

	GN Publisher
		Version: 1.5.4
		Author: Chris Andrews

	Imagify
		Version: 2.1
		Author: Imagify – Optimize Images & Convert WebP

	JetSearch
		Version: 3.0.3
		Author: Crocoblock

	JetSmartFilters
		Version: 3.0.4
		Author: Crocoblock

	MainWP Child
		Version: 4.3.1
		Author: MainWP

	Rank Math SEO
		Version: 1.0.106
		Author: Rank Math

	Rank Math SEO PRO
		Version: 3.0.28
		Author: Rank Math

	Save UTMs to Elementor Form
		Version: 1.5
		Author: C42.Studio

	SiteGround Security
		Version: 1.3.8
		Author: SiteGround

	Site Kit by Google
		Version: 1.92.0
		Author: Google

== Elements Usage ==
	
	archive : 1
		archive-posts : 1
		button : 1
		container : 1
		heading : 1
		jet-smart-filters-active : 1
		jet-smart-filters-radio : 1
		jet-smart-filters-search : 1
		jet-smart-filters-select : 1
	footer : 1
		container : 3
		heading : 3
		image : 1
	header : 1
		button : 1
		container : 1
		heading : 1
		image : 1
	page : 1
		button : 1
		container : 1
		heading : 2
	popup : 4
		form : 2
		heading : 2
	wp-page : 8
		button : 4
		container : 6
		form : 3
		heading : 5
		image : 1
		shortcode : 1
		text-editor : 2
	single-post : 1
		button : 2
		container : 4
		form : 2
		heading : 1
		post-info : 1
		post-navigation : 1
		posts : 1
		share-buttons : 1
		theme-post-content : 1
		theme-post-featured-image : 1
		theme-post-title : 1
	error-404 : 1
		button : 2
		container : 2
		heading : 2

== Settings ==
	
	cpt_support: post, page
	disable_color_schemes: yes
	disable_typography_schemes: yes
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap

== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Active
	Hide native WordPress widgets from search results: Inactive
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Inactive
	Hello Theme Header & Footer: Inactive
	Landing Pages: Inactive
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default
	Save as Default: Active by default
	Page Transitions: Inactive
	Notes: Inactive
	Loop: Active
	Loop Carousel: Inactive by default
	Form Submissions: Active
	Scroll Snap: Inactive

== Log ==
	
Log: showing 20 of 272022-12-25 13:28:42 [info] elementor-pro::elementor_pro_updater Started 
2022-12-25 13:28:42 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-12-25 13:28:42 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-12-25 13:28:42 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.2',
  'to' => '3.9.2',
)]
2022-12-25 13:28:42 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.2',
  'to' => '3.9.2',
)]
2022-12-25 13:28:42 [info] elementor::elementor_updater Started 
2022-12-25 13:28:42 [info] Elementor/Upgrades - _on_each_version Start  
2022-12-25 13:28:43 [info] Elementor/Upgrades - _on_each_version Finished 
2022-12-25 13:28:43 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.1',
  'to' => '3.9.2',
)]
2023-01-10 19:15:56 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.2',
  'to' => '3.10.0',
)]
2023-01-10 19:15:57 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.2',
  'to' => '3.10.1',
)]
2023-01-10 19:15:57 [info] elementor::elementor_updater Started 
2023-01-10 19:15:57 [info] Elementor/Upgrades - _on_each_version Start  
2023-01-10 19:15:57 [info] Elementor/Upgrades - _on_each_version Finished 
2023-01-10 19:15:57 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.2',
  'to' => '3.10.0',
)]
2023-01-18 00:01:52 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.0',
  'to' => '3.10.1',
)]
2023-01-18 00:01:52 [info] elementor::elementor_updater Started 
2023-01-18 00:01:52 [info] Elementor/Upgrades - _on_each_version Start  
2023-01-18 00:01:52 [info] Elementor/Upgrades - _on_each_version Finished 
2023-01-18 00:01:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.0',
  'to' => '3.10.1',
)]

PHP: showing 7 of 7PHP: 2022-12-08 17:39:57 [error X 3][/home/customer/www/c42.studio/public_html/wp-content/plugins/elementor/core/wp-api.php::26] Uncaught Error: Call to undefined function Elementor\Core\get_plugins() in /home/customer/www/c42.studio/public_html/wp-content/plugins/elementor/core/wp-api.php:26
Stack trace:
#0 /home/customer/www/c42.studio/public_html/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(96): Elementor\Core\Wp_Api->get_plugins()
#1 /home/customer/www/c42.studio/public_html/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(58): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_with_header()
#2 /home/customer/www/c42.studio/public_html/wp-content/plugins/elementor/modules/compatibility-tag/module.php(57): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_to_check()
#3 /home/customer/www/c42.studio/public_html/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(148): Elementor\Modules\CompatibilityTag\Module->get_plugins_to_check()
#4 /home/customer/www/c42.studio/public_html/wp-includes/class-wp-hook.php(308): Elementor\Modules\CompatibilityTag\Base_Module->Elementor\Modules\CompatibilityTag\{closure}('')
#5 /home/customer/www/c42.studio/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#6 /home/customer/www/c42.studio/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#7 /home/customer/www/c42.studio/public_html/wp-content/plugins/elementor/modules/system-info/module.php(334): do_action('elementor/syste...')
#8 /home/customer/www/c42.studio/public_html/wp-content/plugins/elementor/includes/tracker.php(241): Elementor\Modules\System_Info\Module::get_allowed_reports()
#9 /home/customer/www/c42.studio/public_html/wp-content/plugins/elementor/includes/tracker.php(530): Elementor\Tracker::get_system_reports_data()
#10 /home/customer/www/c42.studio/public_html/wp-content/plugins/elementor/includes/tracker.php(141): Elementor\Tracker::get_tracking_data(false)
#11 /home/customer/www/c42.studio/public_html/wp-includes/class-wp-hook.php(308): Elementor\Tracker::send_tracking_data()
#12 /home/customer/www/c42.studio/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#13 /home/customer/www/c42.studio/public_html/wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#14 /home/customer/www/c42.studio/public_html/wp-cron.php(188): do_action_ref_array('elementor/track...', Array)
#15 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-28 12:04:37 [warning X 9][/home/customer/www/c42.studio/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-28 16:34:10 [notice X 7576][/home/customer/www/c42.studio/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-28 16:34:20 [notice X 100][/home/customer/www/c42.studio/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/customer/www/c42.studio/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(304): class type trigger_error()
#2: /home/customer/www/c42.studio/public_html/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home/customer/www/c42.studio/public_html/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home/customer/www/c42.studio/public_html/wp-content/plugins/jet-smart-filters/framework/jet-elementor-extension/jet-elementor-extension.php(95): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-12-28 16:34:20 [notice X 100][/home/customer/www/c42.studio/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/customer/www/c42.studio/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(304): class type trigger_error()
#2: /home/customer/www/c42.studio/public_html/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home/customer/www/c42.studio/public_html/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home/customer/www/c42.studio/public_html/wp-content/plugins/jet-smart-filters/framework/jet-elementor-extension/jet-elementor-extension.php(96): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-12-30 13:27:08 [notice X 3][/home/customer/www/c42.studio/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php::747] ob_end_clean(): Failed to delete buffer. No buffer to delete [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-03 01:19:28 [warning X 4][/home/customer/www/c42.studio/public_html/wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 8 of 8JS: 2022-12-25 15:58:14 [error X 20][https://c42.studio/wp-admin/load-scripts.php?c=0&loadchunk_0=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&loadchunk_1=hooks&ver=6.1.1:4:51824] Cannot read properties of undefined (reading \'replace\') 
JS: 2022-12-28 19:38:10 [error X 4][https://c42.studio/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.9.2:3:775755] Cannot read properties of undefined (reading \'localized\') 
JS: 2022-12-29 17:20:54 [error X 1][https://c42.studio/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view16130\") has already been destroyed and cannot be used. 
JS: 2022-12-29 20:33:08 [error X 1][https://c42.studio/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.9.2:3:655306] this.model.isValidChild is not a function 
JS: 2023-01-03 12:22:13 [error X 1][https://c42.studio/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view3653\") has already been destroyed and cannot be used. 
JS: 2023-01-03 12:22:25 [error X 1][https://c42.studio/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view5360\") has already been destroyed and cannot be used. 
JS: 2023-01-03 12:22:35 [error X 1][https://c42.studio/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view6758\") has already been destroyed and cannot be used. 
JS: 2023-01-13 14:25:20 [error X 7][https://c42.studio/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:51824] Cannot read properties of undefined (reading 'replace') 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Incompatible
	Save UTMs to Elementor Form: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by maurocarreraok** [comment]
@nicholaszein
