### ISSUE TITLE
My site is broked, I need help please (something wrong with PHP 8.0 and elementor) more details here:

### ISSUE THREAD

**Issue by Engiva** [elementor/elementor#21112]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hello everyone

I need support because my site is broken (please, I need help)... the support of my current hosting informed me of the problem... and they explained to me that the problem is PHP 8.0 and elementor incompatible.

On the other hand, elementor support tells me that elementor is ready to work in PHP 8.0 but that it does not guarantee that it can do it in all hosting... I'm at Kinsta and I can't downgrade PHP... it's the 8.0 and elementor not working.

They tell me:

My hosting support: I mean, that the issue may not be caused by Elementor, but Elementor is having the error just the same

This confirms that Elementor is your issue:
````
2023/01/22 23:34:47 [error] 3476#3476: *90590 upstream timed out (110: Connection timed out) while sending request to upstream, client: 83.50.64.167, server: grupoengiva.industries, request: " POST /wp-admin/admin-ajax.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php8.0-fpm-grupoengiva.sock", host: "grupoengiva.industries:55439" , referrer: "https://grupoengiva.industries/wp-admin/post.php?post=25352&action=elementor"
````

### Steps to reproduce

Open any post, page or any template (this issue start with templates....) before all goes wrong previsuly I coundt edit any template

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt

					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.21.5
	MySQL version: mariadb.org binary distribution v10.5.17
	PHP Version: 8.0.26
	PHP Memory Limit: 256M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://grupoengiva.industries
	Home URL: https://grupoengiva.industries
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 512M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: es
	Timezone: 1
	Admin Email: grupoengiva@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: 
	WP Profile lang: es_EC
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36

== Active Plugins ==
	Activity Log
		Version: 2.8.5
		Author: Activity Log Team

	Advanced Custom Fields PRO
		Version: 5.11.4
		Author: Delicious Brains

	Contact Form DB - Elementor
		Version: 1.8.0
		Author: Web Ace Tech Services

	Copy & Delete Posts
		Version: 1.3.7
		Author: Copy Delete Posts

	Custom Adobe Fonts (Typekit)
		Version: 1.0.18
		Author: Brainstorm Force

	Custom Fonts
		Version: 1.3.7
		Author: Brainstorm Force

	Custom Post Type UI
		Version: 1.13.4
		Author: WebDevStudios

	Elementor
		Version: 3.10.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.10.2
		Author: Elementor.com

	ELEX Dynamic Pricing and Discounts for WooCommerce
		Version: 3.7.7
		Author: ELEX

	Essential Addons for Elementor
		Version: 5.5.2
		Author: WPDeveloper

	Essential Addons for Elementor - Pro
		Version: 5.4.3
		Author: WPDeveloper

	Extensions For Elementor
		Version: 2.0.15
		Author: mayanksdudakiya

	GDPR Cookie Compliance
		Version: 4.9.7
		Author: Moove Agency

	GTM4WP
		Version: 1.16.2
		Author: Thomas Geiger

	Holded integration
		Version: 3.3.5
		Author: Holded

	Imsanity
		Version: 2.8.2
		Author: Exactly WWW

	Indeed Ultimate Learning Pro
		Version: 3.3
		Author: WPIndeed Development

	Indeed Ultimate Membership Pro
		Version: 10.11
		Author: WPIndeed Development

	Login/Signup Popup
		Version: 2.3
		Author: XootiX

	Min Max Quantity & Step Control for WooCommerce
		Version: 3.6
		Author: CodeAstrology Team

	Min Max Quantity & Step Control for WooCommerce (PRO)
		Version: 2.0.7
		Author: CodeAstrology

	Post Type Switcher
		Version: 3.2.1
		Author: Triple J Software, Inc.

	Real Media Library (Free)
		Version: 4.18.28
		Author: devowl.io

	Reveal IDs
		Version: 1.5.4
		Author: Oliver Schlöbe

	The Plus Addons for Elementor
		Version: 5.1.15
		Author: POSIMYTH

	The Plus Addons for Elementor - Pro
		Version: 5.1.4
		Author: POSIMYTH

	TinyPNG - JPEG, PNG & WebP image compression
		Version: 3.4.1
		Author: TinyPNG

	Ultimate Addons for Elementor
		Version: 1.36.14
		Author: Brainstorm Force

	Ultimate Membership Pro Addon - Elementor Widget Lock
		Version: 2.0
		Author: WPIndeed

	Ultimate Membership Pro Addon - Extended Shortcodes
		Version: 1.6
		Author: WPIndeed

	Ultimate Membership Pro Addon - My Group Accounts
		Version: 2.3
		Author: WPIndeed

	Ultimate Membership Pro Addon - WooCommerce Redirect
		Version: 1.3
		Author: WPIndeed

	UpdraftPlus - Backup/Restore
		Version: 2.22.25.26
		Author: UpdraftPlus.Com, DavidAnderson

	User Verification WooCommerce
		Version: 1.2
		Author: XootiX

	VisionVpro Speed Optimization
		Version: 2.3.4
		Author: VisionVpro

	WC - APG NIF/CIF/NIE Field
		Version: 1.7.4
		Author: Art Project Group

	WC Thank You Page
		Version: 1.0.3
		Author: WPToffee

	WooCommerce
		Version: 7.3.0
		Author: Automattic

	Woocommerce Product Excel Import-Export PRO
		Version: 6.4
		Author: extendWP

	WooCommerce Shipping & Tax
		Version: 2.2.0
		Author: WooCommerce

	WooCommerce Stripe Gateway
		Version: 7.0.2
		Author: WooCommerce

	WordPress WhatsApp Support
		Version: 2.3.3
		Author: WeCreativez

	WPC AJAX Add to Cart for WooCommerce
		Version: 1.5.5
		Author: WPClever

	WPC Fly Cart for WooCommerce
		Version: 5.3.1
		Author: WPClever

	WPC Fly Cart for WooCommerce (Premium)
		Version: 5.3.1
		Author: WPClever

	WP Cloud Plugin Use-your-Drive (Google Drive)
		Version: 2.3
		Author: WP Cloud Plugins

	WP Comment Policy Checkbox
		Version: 0.4.1
		Author: Fco. J. Godoy

	WPC Share Cart for WooCommerce
		Version: 1.2.0
		Author: WPClever

	WPC Smart Quick View for WooCommerce
		Version: 3.3.4
		Author: WPClever

	WPC Smart Quick View for WooCommerce (Premium)
		Version: 3.3.4
		Author: WPClever

	wpDataTables
		Version: 5.2
		Author: TMS-Plugins

	WP File Manager
		Version: 7.1.7
		Author: mndpsingh287

	WPForms
		Version: 1.7.9.1
		Author: WPForms

	WP Rocket
		Version: 3.12.4
		Author: WP Media


== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

	Kinsta Must-use Plugins
		Version: 3.0.0
		Author: Kinsta Team

	LearnDash LMS Multisite
		Version: 1.0.0
		Author: LearnDash


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	
	google_maps: Active
	woocommerce: Active


== Experimentos de Elementor ==
	Salida del DOM optimizada: Activo
	Carga de recursos mejorada: Activo
	Carga de CSS mejorada: Activo
	Fuentes de iconos integradas: Activo
	Mejoras de accesibilidad: Activo
	Puntos de ruptura personalizados adicionales: Activo
	Ocultar los widgets nativos de WordPress de los resultados de búsqueda: Activo
	admin_menu_rearrangement: Inactivo por defecto
	Flexbox Container: Activo
	Default to New Theme Builder: Activo
	Cabecera y pie de página del tema Hello: Activo
	Páginas de destino: Activo
	Nested Elements: Inactivo por defecto
	Lazy Load Background Images: Activo
	Guardar como por defecto: Activo por defecto
	Page Transitions: Activo
	Notes: Activo
	Loop: Activo
	Loop Carousel: Inactivo por defecto
	Form Submissions: Activo
	Scroll Snap: Inactivo


== Registro ==
	
JS: showing 20 of 28JS: 2023-01-18 09:50:06 [error X 9][https://grupoengiva.industries/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:9:21077] Cannot read properties of null (reading 'getOptions') 
JS: 2023-01-18 11:24:13 [error X 24][https://grupoengiva.industries/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.10.2:2:61404] Cannot convert undefined or null to object 
JS: 2023-01-18 11:34:35 [error X 19][https://grupoengiva.industries/wp-content/uploads/essential-addons-elementor/eael.js?ver=1674045015:13:300638] Cannot read properties of undefined (reading 'hasOwnProperty') 
JS: 2023-01-18 14:00:05 [error X 3][https://grupoengiva.industries/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.10.1:2:7470] Cannot read properties of null (reading 'editor') 
JS: 2023-01-19 11:29:52 [error X 2][https://grupoengiva.industries/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.10.1:3:646529] elementorFrontend.elements.window.jQuery is not a function 
JS: 2023-01-19 11:29:56 [error X 2][https://grupoengiva.industries/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.10.1:2:9135] Cannot read properties of undefined (reading 'attributes') 
JS: 2023-01-20 08:59:51 [error X 4][https://grupoengiva.industries/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.10.1:3:1075047] Cannot read properties of null (reading 'getBoundingClientRect') 
JS: 2023-01-20 10:58:15 [error X 1][https://grupoengiva.industries/wp-content/plugins/essential-addons-elementor/assets/front-end/js/edit/eael-xd-copy.min.js?ver=1674211407:1:3882] Cannot read properties of null (reading 'elementcode') 
JS: 2023-01-20 10:58:36 [error X 1][https://grupoengiva.industries/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.10.1:2:14150] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got as `single_image_move` value. Expected array or object.',
)]
JS: 2023-01-22 01:29:10 [error X 7][https://grupoengiva.industries/wp-content/plugins/ultimate-elementor/assets/min-js/uael-nav-menu.min.js?ver=1.36.14:1:19643] Cannot read properties of undefined (reading 'includes') 
JS: 2023-01-22 11:51:59 [error X 1][https://grupoengiva.industries/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view482") has already been destroyed and cannot be used. 
JS: 2023-01-22 12:26:01 [error X 1][https://grupoengiva.industries/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view491") has already been destroyed and cannot be used. 
JS: 2023-01-22 17:48:46 [error X 1][https://grupoengiva.industries/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view569") has already been destroyed and cannot be used. 
JS: 2023-01-22 17:51:55 [error X 1][https://grupoengiva.industries/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view527") has already been destroyed and cannot be used. 
JS: 2023-01-22 18:22:22 [error X 18][https://grupoengiva.industries/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.10.1:2:14150] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got as `menu_link` value. Expected array or object.',
)]
JS: 2023-01-22 18:34:58 [error X 2][https://grupoengiva.industries/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view533") has already been destroyed and cannot be used. 
JS: 2023-01-22 19:08:21 [error X 1][https://grupoengiva.industries/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view697") has already been destroyed and cannot be used. 
JS: 2023-01-22 19:09:29 [error X 1][https://grupoengiva.industries/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view588") has already been destroyed and cannot be used. 
JS: 2023-01-22 23:56:04 [error X 1][https://grupoengiva.industries/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view605") has already been destroyed and cannot be used. 
JS: 2023-01-23 09:20:21 [error X 1][https://grupoengiva.industries/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.10.1:3:605276] Cannot read properties of undefined (reading 'models') 

PHP: showing 14 of 14PHP: 2023-01-12 15:11:59 [error X 3][/www/grupoengiva_750/public/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::295] Uncaught Error: Call to a member function update_meta() on bool in /www/grupoengiva_750/public/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:295
Stack trace:
#0 /www/grupoengiva_750/public/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(168): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /www/grupoengiva_750/public/wp-content/plugins/elementor/core/common/modules/ajax/module.php(172): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /www/grupoengiva_750/public/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /www/grupoengiva_750/public/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#5 /www/grupoengiva_750/public/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /www/grupoengiva_750/public/wp-admin/admin-ajax.php(188): do_action('wp_ajax_element...')
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-13 16:07:51 [warning X 12][/www/grupoengiva_750/public/wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-14 17:56:17 [notice X 27][/www/grupoengiva_750/public/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] ¡El argumento $control_id está obsoleto desde la versión 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-15 13:54:13 [warning X 2][/www/grupoengiva_750/public/wp-content/plugins/elementor-pro/modules/woocommerce/widgets/checkout.php::4110] Undefined array key "coupon_section_display" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-16 22:32:02 [warning X 4][/www/grupoengiva_750/public/wp-content/plugins/elementor-pro/modules/woocommerce/widgets/cart.php::2383] Undefined array key "section_coupon_display" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-18 10:48:47 [warning X 1][/www/grupoengiva_750/public/wp-content/plugins/elementor/includes/db.php::267] foreach() argument must be of type array|object, null given [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-18 12:31:59 [warning X 1][/www/grupoengiva_750/public/wp-content/plugins/elementor-pro/modules/payments/module.php::306] Undefined array key "stripe_test_env_tax_rates_list" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-18 14:25:56 [warning X 2][/www/grupoengiva_750/public/wp-content/plugins/elementor-pro/modules/query-control/module.php::749] Attempt to read property "name" on null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-19 09:40:04 [warning X 9][/www/grupoengiva_750/public/wp-content/plugins/elementor-pro/modules/posts/skins/skin-content-base.php::264] Attempt to read property "ID" on null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-20 10:26:27 [warning X 3][/www/grupoengiva_750/public/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::168] Undefined array key "editor_post_id" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-20 13:14:54 [warning X 11][/www/grupoengiva_750/public/wp-content/plugins/elementor/includes/db.php::267] foreach() argument must be of type array|object, int given [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-20 15:38:27 [error X 1][/www/grupoengiva_750/public/wp-content/plugins/elementor-pro/modules/screenshots/module.php::212] Uncaught Requests_Exception_HTTP_403: 403 Forbidden in /www/grupoengiva_750/public/wp-content/plugins/elementor-pro/modules/screenshots/module.php:212
Stack trace:
#0 /www/grupoengiva_750/public/wp-content/plugins/elementor-pro/modules/screenshots/module.php(232): ElementorPro\Modules\Screenshots\Module->is_screenshot_proxy_mode(Array)
#1 /www/grupoengiva_750/public/wp-content/plugins/elementor/core/base/module.php(85): ElementorPro\Modules\Screenshots\Module->__construct()
#2 /www/grupoengiva_750/public/wp-content/plugins/elementor-pro/core/modules-manager.php(86): Elementor\Core\Base\Module::instance()
#3 /www/grupoengiva_750/public/wp-content/plugins/elementor-pro/plugin.php(358): ElementorPro\Core\Modules_Manager->__construct()
#4 /www/grupoengiva_750/public/wp-includes/class-wp-hook.php(308): ElementorPro\Plugin->on_elementor_init('')
#5 /www/grupoengiva_750/public/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#6 /www/grupoengiva_750/public/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#7 /www/grupoengiva_750/public/wp-content/plugins/elementor/includes/plugin.php(652): do_action('elementor/init')
#8 /www/grupoengiva_750/public/wp-includes/class-wp-hook.php(308): Elementor\Plugin->init('')
#9 /www/grupoengiva_750/public/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#10 /www/grupoengiva_750/public/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#11 /www/grupoengiva_750/public/wp-settings.php(617): do_action('init')
#12 /www/grupoengiva_750/public/wp-config.php(81): require_once('/www/grupoengiv...')
#13 /www/grupoengiva_750/public/wp-load.php(50): require_once('/www/grupoengiv...')
#14 /www/grupoengiva_750/public/wp-blog-header.php(13): require_once('/www/grupoengiv...')
#15 /www/grupoengiva_750/public/index.php(17): require('/www/grupoengiv...')
#16 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-22 13:23:39 [warning X 150][/www/grupoengiva_750/public/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php::33] Undefined array key 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-22 22:10:47 [warning X 9][/www/grupoengiva_750/public/wp-content/plugins/elementor/core/common/modules/ajax/module.php::172] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Contact Form DB - Elementor: Compatibilidad no especificada
	Elementor Pro: Compatibilidad no especificada
	Essential Addons for Elementor: Compatibilidad no especificada
	Essential Addons for Elementor - Pro: Compatibilidad no especificada
	Extensions For Elementor: Compatibilidad no especificada
	The Plus Addons for Elementor: Compatibilidad no especificada
	The Plus Addons for Elementor - Pro: Compatibilidad no especificada
	Ultimate Addons for Elementor: Compatibilidad no especificada
	Ultimate Membership Pro Addon - Elementor Widget Lock: Compatibilidad no especificada

== Elementor Pro - Compatibility Tag ==
	

				

````
</details>

**Comment by Engiva** [comment]
and with hello theme too. Only I am using Hello theme

**Comment by rami-elementor** [comment]
@Engiva 

Kinsta moved all their sites to PHP8. They should have checked if the site will break or not, but it seems like they didn't do that in your case.

If they say it's an Elementor issue, they should send the error log or file a proper bug report. Otherwise, there is nothing we can do as we don't have enough data to identify the issue.

I'm closing this issue. Please create a new ticket with more information.

**Comment by nicholaszein** [comment]
Hello @Engiva,

Thanks for contacting us! 🙏 

This is more of a support question, not really something we can answer here.

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Regards,

Nick
