### ISSUE TITLE
⛔ 🐞 Bug Report: Tel in Forms is prefilling the form with the placeholder text

### ISSUE THREAD

**Issue by kulterryan** [elementor/elementor#21233]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

The TEL item in the forms section is showing the prefill text instead of the _**placeholder**_ in the forms.
![image](https://user-images.githubusercontent.com/36154235/216493871-25e0b940-d8e7-46fa-a6b1-ae64bdc5e066.png)

### Steps to reproduce

1. Update to the latest version of Elementor.
2. Create A Form in Popup.
3. Use "Tel" field in the form.
4. Publish the form.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.54 (Debian)
	MySQL version: mariadb.org binary distribution v10.5.11
	PHP Version: 8.1.14
	PHP Memory Limit: 256M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://naukriwala.org
	Home URL: https://naukriwala.org
	WP Multisite: No
	Max Upload Size: 100 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 5.5
	Admin Email: realnaukriwala@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: NW
	Version: 1.0.1
	Author: Aryan Chaurasia
	Child Theme: Yes
	Parent Theme Name: Astra
	Parent Theme Version: 4.0.2
	Parent Theme Author: Brainstorm Force

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.1518.70

== Active Plugins ==
	Advanced Custom Fields
		Version: 6.0.7
		Author: WP Engine

	AffiliateWP
		Version: 2.9.8
		Author: AffiliateWP

	Astra Pro
		Version: 4.0.1
		Author: Brainstorm Force

	Custom Post Type UI
		Version: 1.13.4
		Author: WebDevStudios

	DIGITS: WordPress Mobile Number Signup and Login
		Version: 7.9.4.8
		Author: UnitedOver

	Elementor
		Version: 3.10.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.10.3
		Author: Elementor.com

	Imagify
		Version: 2.1.1
		Author: Imagify – Optimize Images & Convert WebP

	LearnDash LMS
		Version: 4.4.1.2
		Author: LearnDash

	LearnDash LMS - Certificate Builder
		Version: 1.0.3
		Author: LearnDash

	LearnDash LMS - WooCommerce Integration
		Version: 1.9.6
		Author: LearnDash

	MalCare WordPress Security Plugin - Malware Scanner, Cleaner, Security Firewall
		Version: 4.86
		Author: MalCare Security

	OoohBoi Steroids for Elementor
		Version: 2.1.3
		Author: OoohBoi

	Perfmatters
		Version: 2.0.4
		Author: forgemedia

	Rank Math SEO
		Version: 1.0.107.3
		Author: Rank Math

	Razorpay for WooCommerce
		Version: 4.4.2
		Author: Team Razorpay

	URL Params
		Version: 2.3
		Author: Jeremy B. Shapiro

	User Menus
		Version: 1.3.1
		Author: Code Atlantic

	WooCommerce
		Version: 7.3.0
		Author: Automattic

	WP Date and Time Shortcode
		Version: 2.5.3
		Author: Denra.com aka SoftShop Ltd

	WP Rocket
		Version: 3.12.5.2
		Author: WP Media

	Yoast Duplicate Post
		Version: 4.5
		Author: Enrico Battocchi & Team Yoast


== Must-Use Plugins ==
	Object Cache Pro (MU)
		Version: 1.17.0
		Author: Rhubarb Group


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	
	woocommerce: Active


== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Active by default
	Landing Pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Active
	Save as Default: Active
	Page Transitions: Inactive
	Notes: Active by default
	Loop: Active
	Loop Carousel: Inactive by default
	Form Submissions: Active by default
	Scroll Snap: Active by default


== Log ==
	
PHP: showing 11 of 11PHP: 2023-01-10 22:38:35 [error X 1][/home/914347.cloudwaysapps.com/ktgqtzubds/public_html/wp-content/plugins/elementor-pro/modules/popup/module.php::122] Uncaught Error: Call to a member function save_display_settings_data() on bool in /home/914347.cloudwaysapps.com/ktgqtzubds/public_html/wp-content/plugins/elementor-pro/modules/popup/module.php:122
Stack trace:
#0 [internal function]: ElementorPro\Modules\Popup\Module->save_display_settings()
#1 /home/914347.cloudwaysapps.com/ktgqtzubds/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func()
#2 /home/914347.cloudwaysapps.com/ktgqtzubds/public_html/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#3 /home/914347.cloudwaysapps.com/ktgqtzubds/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#4 /home/914347.cloudwaysapps.com/ktgqtzubds/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#5 /home/914347.cloudwaysapps.com/ktgqtzubds/public_html/wp-admin/admin-ajax.php(188): do_action()
#6 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-11 11:53:43 [notice X 7][/home/914347.cloudwaysapps.com/ktgqtzubds/public_html/wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-20 00:07:27 [notice X 506][/home/914347.cloudwaysapps.com/ktgqtzubds/public_html/wp-content/plugins/elementor-pro/core/database/model-base.php::135] Return type of ElementorPro\Core\Database\Model_Base::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: /home/914347.cloudwaysapps.com/ktgqtzubds/public_html/wp-content/plugins/elementor-pro/core/database/model-base.php(10): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/914347.cloudwaysapps.com/ktgqtzubds/public_html/wp-content/plugins/elementor-pro/plugin.php(154): class type include()array (
  0 => '/home/914347.cloudwaysapps.com/ktgqtzubds/public_html/wp-content/plugins/elementor-pro/core/database/model-base.php',
)
#2: /home/914347.cloudwaysapps.com/ktgqtzubds/public_html/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php(18): ElementorPro\Plugin -> autoload()
#3: /home/914347.cloudwaysapps.com/ktgqtzubds/public_html/wp-content/plugins/elementor-pro/plugin.php(154): class type include()array (
  0 => '/home/914347.cloudwaysapps.com/ktgqtzubds/public_html/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php',
)
#4: /home/914347.cloudwaysapps.com/ktgqtzubds/public_html/wp-content/plugins/elementor-pro/modules/notes/data/controller.php(243): ElementorPro\Plugin -> autoload()
',
)]
PHP: 2023-01-20 00:14:53 [notice X 130][/home/914347.cloudwaysapps.com/ktgqtzubds/public_html/wp-content/plugins/elementor-pro/core/utils/collection.php::75] Return type of ElementorPro\Core\Utils\Collection::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-20 20:02:38 [notice X 1][/home/914347.cloudwaysapps.com/ktgqtzubds/public_html/wp-content/plugins/elementor-pro/core/utils/collection.php::75] Return type of ElementorPro\Core\Utils\Collection::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: /home/914347.cloudwaysapps.com/ktgqtzubds/public_html/wp-content/plugins/elementor-pro/core/utils/collection.php(11): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/914347.cloudwaysapps.com/ktgqtzubds/public_html/wp-content/plugins/elementor-pro/plugin.php(154): class type include()array (
  0 => '/home/914347.cloudwaysapps.com/ktgqtzubds/public_html/wp-content/plugins/elementor-pro/core/utils/collection.php',
)
#2: /home/914347.cloudwaysapps.com/ktgqtzubds/public_html/wp-content/plugins/elementor-pro/core/database/query-builder.php(1222): ElementorPro\Plugin -> autoload()
#3: /home/914347.cloudwaysapps.com/ktgqtzubds/public_html/wp-content/plugins/elementor-pro/core/database/query-builder.php(1081): ElementorPro\Core\Database\Query_Builder -> get_bindings()
#4: /home/914347.cloudwaysapps.com/ktgqtzubds/public_html/wp-content/plugins/elementor-pro/core/database/model-query-builder.php(89): ElementorPro\Core\Database\Query_Builder -> get()
',
)]
PHP: 2023-01-20 22:57:02 [notice X 13][/home/914347.cloudwaysapps.com/ktgqtzubds/public_html/wp-content/plugins/elementor-pro/modules/custom-css/module.php::76] trim(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-20 23:06:03 [warning X 4][/home/914347.cloudwaysapps.com/ktgqtzubds/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::172] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-21 13:38:06 [notice X 3][/home/914347.cloudwaysapps.com/ktgqtzubds/public_html/wp-content/plugins/elementor-pro/core/database/model-base.php::135] Return type of ElementorPro\Core\Database\Model_Base::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-21 16:06:18 [warning X 2][/home/914347.cloudwaysapps.com/ktgqtzubds/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key "condition_type" [array (
  'trace' => '
#0: /home/914347.cloudwaysapps.com/ktgqtzubds/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /home/914347.cloudwaysapps.com/ktgqtzubds/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /home/914347.cloudwaysapps.com/ktgqtzubds/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /home/914347.cloudwaysapps.com/ktgqtzubds/public_html/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2023-01-27 22:30:40 [notice X 1][/home/914347.cloudwaysapps.com/ktgqtzubds/public_html/wp-content/plugins/elementor-pro/core/utils/collection.php::75] Return type of ElementorPro\Core\Utils\Collection::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: /home/914347.cloudwaysapps.com/ktgqtzubds/public_html/wp-content/plugins/elementor-pro/core/utils/collection.php(11): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/914347.cloudwaysapps.com/ktgqtzubds/public_html/wp-content/plugins/elementor-pro/plugin.php(154): class type include()array (
  0 => '/home/914347.cloudwaysapps.com/ktgqtzubds/public_html/wp-content/plugins/elementor-pro/core/utils/collection.php',
)
#2: /home/914347.cloudwaysapps.com/ktgqtzubds/public_html/wp-content/plugins/elementor-pro/core/database/query-builder.php(1222): ElementorPro\Plugin -> autoload()
#3: /home/914347.cloudwaysapps.com/ktgqtzubds/public_html/wp-content/plugins/elementor-pro/core/database/query-builder.php(189): ElementorPro\Core\Database\Query_Builder -> get_bindings()
#4: /home/914347.cloudwaysapps.com/ktgqtzubds/public_html/wp-content/plugins/elementor-pro/modules/notes/database/query/note-query-builder.php(115): ElementorPro\Core\Database\Query_Builder -> add_sub_select()
',
)]
PHP: 2023-02-02 19:04:03 [notice X 86][/home/914347.cloudwaysapps.com/ktgqtzubds/public_html/wp-content/plugins/elementor-pro/core/database/model-base.php::135] Return type of ElementorPro\Core\Database\Model_Base::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: /home/914347.cloudwaysapps.com/ktgqtzubds/public_html/wp-content/plugins/elementor-pro/core/database/model-base.php(10): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/914347.cloudwaysapps.com/ktgqtzubds/public_html/wp-content/plugins/elementor-pro/plugin.php(159): class type include()array (
  0 => '/home/914347.cloudwaysapps.com/ktgqtzubds/public_html/wp-content/plugins/elementor-pro/core/database/model-base.php',
)
#2: /home/914347.cloudwaysapps.com/ktgqtzubds/public_html/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php(18): ElementorPro\Plugin -> autoload()
#3: /home/914347.cloudwaysapps.com/ktgqtzubds/public_html/wp-content/plugins/elementor-pro/plugin.php(159): class type include()array (
  0 => '/home/914347.cloudwaysapps.com/ktgqtzubds/public_html/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php',
)
#4: /home/914347.cloudwaysapps.com/ktgqtzubds/public_html/wp-content/plugins/elementor-pro/modules/notes/data/controller.php(243): ElementorPro\Plugin -> autoload()
',
)]

Log: showing 20 of 282023-01-10 23:37:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.2',
  'to' => '3.10.1',
)]
2023-01-19 20:06:51 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.10.1',
  'to' => '3.10.2',
)]
2023-01-19 20:06:51 [info] elementor-pro::elementor_pro_updater Started 
2023-01-19 20:06:51 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-01-19 20:06:52 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-01-19 20:06:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.10.1',
  'to' => '3.10.2',
)]
2023-01-19 20:06:53 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.10.1',
  'to' => '3.10.2',
)]
2023-01-19 20:07:09 [info] elementor::elementor_updater Started 
2023-01-19 20:07:09 [info] Elementor/Upgrades - _on_each_version Start  
2023-01-19 20:07:09 [info] Elementor/Upgrades - _on_each_version Finished 
2023-01-19 20:07:09 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.0',
  'to' => '3.10.1',
)]
2023-02-02 19:00:32 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.1',
  'to' => '3.10.2',
)]
2023-02-02 19:00:33 [info] elementor::elementor_updater Started 
2023-02-02 19:00:33 [info] Elementor/Upgrades - _on_each_version Start  
2023-02-02 19:00:33 [info] Elementor/Upgrades - _on_each_version Finished 
2023-02-02 19:00:33 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.1',
  'to' => '3.10.2',
)]
2023-02-02 19:00:50 [info] elementor-pro::elementor_pro_updater Started 
2023-02-02 19:00:50 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-02-02 19:00:50 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-02-02 19:00:50 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.10.2',
  'to' => '3.10.3',
)]

JS: showing 3 of 3JS: 2023-01-11 16:34:43 [error X 72][https://woocommerce-914347-3173500.cloudwaysapps.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.10.0:3:646529] elementorFrontend.elements.window.jQuery is not a function 
JS: 2023-01-12 16:14:19 [error X 13][https://woocommerce-914347-3173500.cloudwaysapps.com/wp-admin/load-scripts.php?c=0&loadchunk_0=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&loadchunk_1=hooks&ver=6.1.1:4:51824] Cannot read properties of undefined (reading 'replace') 
JS: 2023-01-13 17:56:05 [error X 23][https://woocommerce-914347-3173500.cloudwaysapps.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.10.0:3:782020] Cannot read properties of undefined (reading 'localized') 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible
	OoohBoi Steroids for Elementor: Compatible

== Elementor Pro - Compatibility Tag ==
	
	OoohBoi Steroids for Elementor: Compatible
				

````

**Comment by nicholaszein** [comment]
Hello @kulterryan! 

Thank you for submitting your issue! 🙏 

Please allow us some time to investigate it, and get back to you with our findings. 🧐 

Best regards

**Comment by nicholaszein** [comment]
Hello @kulterryan,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
- If you add a default value to a field, it should be expected to show in the field instead of the label.
### 👍 For now, that's all we can help with. 

If you think this is still an issue caused by Elementor, please feel free to open a new 🐞 [Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml).

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
