### ISSUE TITLE
⛔ 🐞 Bug Report: Critical error when trying to add new, preview or edit existing single product template with PHP 8.0

### ISSUE THREAD

**Issue by berkmh** [elementor/elementor#21250]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

critical error when trying to preview/edit or create new single product template when switching to PHP 8.0. Switching back to 7.4 fixes it. 

@rami-elementor 

````txt

[06-Feb-2023 17:14:21 UTC] PHP Fatal error:  Uncaught TypeError: preg_match(): Argument #2 ($subject) must be of type string, array given in /var/www/.com/wp-includes/class-wp-scripts.php:378
Stack trace:
#0 /var/www/.com/wp-includes/class-wp-scripts.php(378): preg_match()
#1 /var/www/.com/wp-includes/class-wp-dependencies.php(137): WP_Scripts->do_item()
#2 /var/www/.com/wp-includes/class-wp-scripts.php(674): WP_Dependencies->do_items()
#3 /var/www/.com/wp-includes/script-loader.php(2019): WP_Scripts->do_head_items()
#4 /var/www/.com/wp-includes/script-loader.php(2139): print_head_scripts()
#5 /var/www/.com/wp-includes/class-wp-hook.php(308): wp_print_head_scripts()
#6 /var/www/.com/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#7 /var/www/.com/wp-includes/plugin.php(517): WP_Hook->do_action()
#8 /var/www/.com/wp-includes/general-template.php(3043): do_action()
#9 /var/www/.com/wp-content/plugins/elementor/includes/editor-templates/editor-wrapper.php(31): wp_head()
#10 /var/www/.com/wp-content/plugins/elementor/core/editor/editor.php(322): include('...')
#11 /var/www/.com/wp-content/plugins/elementor/core/editor/editor.php(163): Elementor\Core\Editor\Editor->print_editor_template()
#12 /var/www/.com/wp-includes/class-wp-hook.php(308): Elementor\Core\Editor\Editor->init()
#13 /var/www/.com/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#14 /var/www/.com/wp-includes/plugin.php(517): WP_Hook->do_action()
#15 /var/www/.com/wp-admin/admin.php(419): do_action()
#16 /var/www/.com/wp-admin/post.php(12): require_once('...')
#17 {main}

````

### Steps to reproduce

install PHP 8.0
Try to create new or open existing single product template

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.18.0
	MySQL version: Source distribution v8.0.28
	PHP Version: 8.0.27
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: No
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://www..com
	Home URL: https://www..com
	WP Multisite: No
	Max Upload Size: 2 MB
	Memory limit: 1024M
	Max Memory limit: 2048M
	Permalink Structure: /blog/%postname%/
	Language: en-US
	Timezone: America/Phoenix
	Admin Email: info@.com
	Debug Mode: Active

== Theme ==
	Name:
	Version: 0.1
	Author:
	Child Theme: Yes
	Parent Theme Name: GeneratePress
	Parent Theme Version: 3.2.4
	Parent Theme Author: Tom Usborne

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36

== Active Plugins ==
	Add to Cart Buttons
		Version: 1.2
		Author: Martin Gibson

	Add To Cart Redirect for WooCommerce
		Version: 1.1.2
		Author: Jeroen Sormani

	AutomateWoo
		Version: 5.6.4
		Author: WooCommerce

         Webshare
		Version: 1.2.0
		Author: Ayooluwa Isaiah

	CheckoutWC
		Version: 7.8.7
		Author: Objectiv

	CloudFlare Image Resizing
		Version: 1.3
		Author: Mecanik

	Coinbase Commerce
		Version: 1.2.1
		Author: Coinbase Commerce

	Default Attributes for WooCommerce
		Version: 1.1.3
		Author: Condless

	Doofinder for WooCommerce
		Version: 1.5.46
		Author: doofinder

	Elementor
		Version: 3.10.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.10.3
		Author: Elementor.com

	FraudLabs Pro for WooCommerce
		Version: 2.17.7
		Author: FraudLabs Pro

	JetProductGallery
		Version: 2.1.10
		Author: Crocoblock

	Judge.me Product Reviews for WooCommerce
		Version: 1.3.21
		Author: Judge.me

	Klaviyo
		Version: 3.0.7
		Author: Klaviyo, Inc.

	Klaviyo Toolkit
		Version: 1.6
		Author: Tribe Interactive, LLC

	Lootly for WooCommerce
		Version: 1.24
		Author: Lootly

	Manage Notification E-mails
		Version: 1.8.4
		Author: Virgial Berveling

	MonsterInsights - Ads Addon
		Version: 1.8.0
		Author: MonsterInsights Team

	MonsterInsights - eCommerce Addon
		Version: 8.3.9
		Author: MonsterInsights Team

	MonsterInsights Pro
		Version: 8.12.1
		Author: MonsterInsights

	Nextend Social Login
		Version: 3.1.7
		Author: Nextendweb

	Nextend Social Login Pro Addon
		Version: 3.1.7
		Author: Nextendweb

	Nginx Cache
		Version: 1.0.5
		Author: Till Krüss

	Notification
		Version: 8.0.14
		Author: BracketSpace

	Object Cache Pro
		Version: 1.17.1
		Author: Rhubarb Group

	Perfmatters
		Version: 2.0.5
		Author: forgemedia

	Perzonalization - AI Powered Personalization That Sells
		Version: 1.6.0
		Author: Perzonalization

	Post Types Order
		Version: 1.9.9.2
		Author: Nsp Code

	Prepaid for WooCommerce Subscriptions
		Version: 3.2.3
		Author: Meow Crew

	PW WooCommerce Gift Cards Pro
		Version: 1.428
		Author: Pimwick, LLC

	Redirection
		Version: 5.3.9
		Author: John Godley

	ReferralCandy for WooCommerce
		Version: 2.3.3
		Author: ReferralCandy

	Remove Schema
		Version: 1.6.1
		Author: Plugin.nl

	Reorder variation product price
		Version: 0.2.200603
		Author: Matic Pogladič

	RetentionKit
		Version: 1.2
		Author: Tribe Interactive

	Route App
		Version: 2.2.4
		Author: Route

	Sezzle WooCommerce Payment
		Version: 4.0.8
		Author: Sezzle

	ShareASale WooCommerce Tracker
		Version: 1.5.3
		Author: ShareASale.com, Inc.

	snip pro - Structured Data
		Version: 2.30.3
		Author: floriansimeth

	SOGO Add Script Header Footer
		Version: 3.9
		Author: orenhav (SOGO)

	Subscription Modification
		Version: 2.0
		Author: Objects

	The SEO Framework
		Version: 4.2.7.1
		Author: The SEO Framework Team

	The SEO Framework - Extension Manager
		Version: 2.6.0
		Author: The SEO Framework Team

	TI WooCommerce Wishlist
		Version: 2.2.1
		Author: TemplateInvaders

	Visibility Logic for Elementor
		Version: 2.3.2
		Author: StaxWP

	Visibility Logic PRO for Elementor
		Version: 2.3.2
		Author: StaxWP

	WC subscription custom-field
		Version: 1.0
		Author: Objects

	WooCommerce
		Version: 7.3.0
		Author: Automattic

	WooCommerce - ShipStation Integration
		Version: 4.3.2
		Author: WooCommerce

	WooCommerce Authorize.Net Gateway
		Version: 3.8.0
		Author: SkyVerge

	WooCommerce Back In Stock Notifications
		Version: 1.4.3
		Author: WooCommerce

	WooCommerce Brand Link
		Version: 1.0
		Author: 

	WooCommerce Brands
		Version: 1.6.41
		Author: WooCommerce

	WooCommerce Bulk Stock Management
		Version: 2.2.32
		Author: WooCommerce

	WooCommerce Custom Fields
		Version: 2.3.4
		Author: RightPress

	WooCommerce Custom Orders Table
		Version: 1.0.0-rc3
		Author: Liquid Web

	WooCommerce Extended Coupon Features PRO
		Version: 3.3.2
		Author: Soft79

	WooCommerce Force Default Variant
		Version: 1.6.1
		Author: HappyKite

	WooCommerce Load More Products
		Version: 3.1.7.7
		Author: BeRocket

	WooCommerce Product Bundles
		Version: 6.17.3
		Author: WooCommerce

	WooCommerce Shipment Tracking
		Version: 2.0.0
		Author: WooCommerce

	WooCommerce Subscriptions
		Version: 4.7.0
		Author: WooCommerce

	WooCommerce Subscriptions - Cancel After Failed Retries
		Version: 1.0.0
		Author: Prospress Inc.

	WooCommerce Subscriptions - Disable Report Cache Updates
		Version: 1.0
		Author: Prospress Inc.

	WooCommerce Variation Swatches and Photos
		Version: 3.1.6
		Author: Element Stark

	WP-Dropstream
		Version: 1.2.3
		Author: Dropstream

	WP Offload Media
		Version: 3.1.0
		Author: Delicious Brains

	WP Offload SES Lite
		Version: 1.4.6
		Author: Delicious Brains

	WP Webhooks Pro
		Version: 6.1.1
		Author: Ironikus


== Features ==
	Custom Fonts: 3
	Custom Icons: 0

== Integrations ==
	
	recaptcha_v3: Active
	woocommerce: Active


== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Inactive by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Inactive
	Landing Pages: Inactive
	Nested Elements: Active
	Lazy Load Background Images: Inactive
	Save as Default: Active by default
	Page Transitions: Inactive
	Notes: Inactive
	Loop: Inactive by default
	Form Submissions: Inactive
	Scroll Snap: Inactive


== Log ==
	
Log: showing 20 of 252023-01-19 00:05:24 [info] Elementor/Upgrades - _on_each_version Finished 
2023-01-19 00:05:24 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Start  
2023-01-19 00:05:24 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Finished 
2023-01-19 00:05:24 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.1',
  'to' => '3.10.1',
)]
2023-01-19 00:05:37 [info] elementor-pro::elementor_pro_updater Started 
2023-01-19 00:05:37 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-01-19 00:05:37 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-01-19 00:05:38 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.2',
  'to' => '3.10.2',
)]
2023-02-04 23:54:10 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.1',
  'to' => '3.10.2',
)]
2023-02-04 23:54:11 [info] elementor::elementor_updater Started 
2023-02-04 23:54:11 [info] Elementor/Upgrades - _on_each_version Start  
2023-02-04 23:54:11 [info] Elementor/Upgrades - _on_each_version Finished 
2023-02-04 23:54:11 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.1',
  'to' => '3.10.2',
)]
2023-02-04 23:54:13 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.1',
  'to' => '3.10.2',
)]
2023-02-04 23:54:24 [info] elementor-pro::elementor_pro_updater Started 
2023-02-04 23:54:24 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-02-04 23:54:24 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-02-04 23:54:24 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.10.2',
  'to' => '3.10.3',
)]
2023-02-04 23:54:24 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.10.2',
  'to' => '3.10.3',
)]
2023-02-04 23:54:25 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.10.2',
  'to' => '3.10.3',
)]

PHP: showing 11 of 11PHP: 2022-11-23 14:27:36 [error X 1][/var/www/.com/wp-content/plugins/elementor/includes/frontend.php::1364] Uncaught Error: Class 'Elementor\Core\Responsive\Responsive' not found in /var/www/.com/wp-content/plugins/elementor/includes/frontend.php:1364
Stack trace:
#0 /var/www/.com/wp-content/plugins/elementor/core/base/base-object.php(142): Elementor\Frontend->get_init_settings()
#1 /var/www/.com/wp-content/plugins/elementor/core/base/base-object.php(40): Elementor\Core\Base\Base_Object->ensure_settings()
#2 /var/www/.com/wp-content/plugins/elementor/core/base/app.php(36): Elementor\Core\Base\Base_Object->get_settings()
#3 /var/www/.com/wp-content/plugins/elementor/includes/frontend.php(577): Elementor\Core\Base\App->print_config()
#4 /var/www/.com/wp-content/plugins/elementor/includes/frontend.php(766): Elementor\Frontend->enqueue_scripts()
#5 /var/www/.com/wp-includes/class-wp-hook.php(308): Elementor\Frontend->wp_footer()
#6 /var/www/.com/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#7 /var/www/.com/wp-includes/plugin.php(517 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-23 14:27:36 [notice X 234735][/var/www/.com/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php::1482] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-23 16:27:06 [notice X 1][/var/www/.com/wp-content/plugins/elementor/core/experiments/experiments-reporter.php::89] Undefined index: title [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-29 15:03:55 [notice X 34][/var/www/.com/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /var/www/.com/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /var/www/.com/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /var/www/.com/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /var/www/.com/wp-content/plugins/visibility-logic-elementor/core/helpers/Controls.php(74): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-12-18 15:33:50 [notice X 28][/var/www/.com/wp-content/plugins/elementor-pro/modules/forms/classes/ajax-handler.php::270] Undefined index: post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-19 01:13:17 [notice X 52][/var/www/.com/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /var/www/.com/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(304): class type trigger_error()
#2: /var/www/.com/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /var/www/.com/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /var/www/.com/wp-content/plugins/visibility-logic-elementor/core/helpers/Controls.php(74): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2023-01-21 12:57:54 [notice X 38][/var/www/.com/wp-content/plugins/elementor-pro/modules/forms/classes/ajax-handler.php::76] Undefined index: form_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-30 07:35:16 [notice X 2][/var/www/.com/wp-content/plugins/elementor-pro/modules/global-widget/data/controller.php::31] Undefined offset: 0 [array (
  'trace' => '
#0: /var/www/.com/wp-content/plugins/elementor-pro/modules/global-widget/data/controller.php(31): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /var/www/.com/wp-includes/rest-api/class-wp-rest-server.php(1171): ElementorPro\Modules\GlobalWidget\Data\Controller -> get_items()
#2: /var/www/.com/wp-includes/rest-api/class-wp-rest-server.php(1018): WP_REST_Server -> respond_to_request()
#3: /var/www/.com/wp-includes/rest-api/class-wp-rest-server.php(442): WP_REST_Server -> dispatch()
#4: /var/www/.com/wp-includes/rest-api.php(410): WP_REST_Server -> serve_request()
',
)]
PHP: 2023-02-05 00:08:14 [notice X 280][/var/www/.com/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-05 10:54:02 [notice X 1][/var/www/.com/wp-content/plugins/elementor/app/modules/import-export/module.php::628] Trying to get property 'label' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-05 10:54:03 [notice X 1][/var/www/.com/wp-content/plugins/elementor/core/common/modules/ajax/module.php::172] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 6 of 6JS: 2022-12-13 20:17:23 [error X 2][https://www..com/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.6.8:2:4765] undefined is not an object (evaluating \'e.attributes\') 
JS: 2023-01-19 09:39:53 [error X 1][https://www..com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.10.1:3:538263] null is not an object (evaluating 'elementorFrontend.elements.window.document.activeElement.tagName') 
JS: 2023-01-24 16:35:08 [error X 33][https://www..com/wp-admin/load-scripts.php?c=1&loadchunk_0=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&loadchunk_1=hooks&ver=6.1.1:4:51824] Cannot read properties of undefined (reading 'replace') 
JS: 2023-02-03 06:53:48 [error X 2][https://www..com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.10.1:3:781513] Cannot read properties of undefined (reading 'toLowerCase') 
JS: 2023-02-05 08:09:40 [error X 7][https://www..com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.10.2:3:782338] Cannot read properties of undefined (reading 'localized') 
JS: 2023-02-05 19:36:49 [error X 1][https://www..com/wp-content/plugins/elementor/assets/js/new-template.min.js?ver=3.10.2:2:2932] elementor_new_template_form_controls is not defined 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	Visibility Logic for Elementor: Compatibility not specified
	Visibility Logic PRO for Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==
	

				
````

</details>

**Comment by berkmh** [comment]
please close. was plugin issue.
