### ISSUE TITLE
⛔ 🐞 Bug Report: Templates not importing certain images

### ISSUE THREAD

**Issue by udzrbarik** [elementor/elementor#21315]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hello everyone, so I'm actually writing a plugin, that programmatically converts Figma Autolayout into Elementor templates, I have all the logic done, everything is generating perfectly, but I'm unable to use image URLs from Figma REST API to import images into Wordpress through the template uploader. 

I have tried this indipendently and this is an issue with Elementor's import feature not importing the images from URLs that do not have a file extension stated explicitly at the end of the url. **So this is not only an issue of the code generated from my plugin**, but also a problem with importing templates from pages, that have a different permalink structure.

I think it is in Elementor's interest to fix this, as it is a bug not only regarding to my plugin, but also to some websites, that may have a different URL structure, therefore not having explicitly stated paths/file extensions to their assets. 

### STEP 1:
I'm gonna be comparing two same JSON template files, the only difference is, that one has inside an embedded image **URL without an explicit file extension at the end**
[Export v10 - with not working URL.json.zip](https://github.com/elementor/elementor/files/10724868/Export.v10.-.with.not.working.URL.json.zip)

e.g:

````json

 "settings": {
                        "image": {
                            "url": "
https://s3-alpha-sig.figma.com/img/e146/5e54/13dcdc20d1a1ca60ad232c7b985f3690?Expires=1677456000&Signature=PlkmxhUouQJzAU8GANHobkWgNST2REkpwcj~aTk-Rns2wZXKEPSNbfFSnhsQfBfH6kN06C~E5DZIrfibQ1xJekwEY67~sIPl4V5qxfgIbygVjspmjHVf2vYT~aHFvny3zzxdo9I71QnBcKzCQa9EYtHpFy5J9vnWFxtc8-JJtvyqvV4xhLiEDj0UHfxEsx2SAdzZ-MsGtHk1cm-QI1sWsFSRkpNeY14aJJ2qtDqsn7Des3kHb1ZMBtL51-vlZAYHD11JyuecERcWTejRkXl2lTJcq2KpSAbCpAptAqMOLI-EG1W59zB2jdBDf3Kr64K-0t7AKHSZ5TCfpMZdw2elBg__&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4",
                            "id": 3813,
                            "alt": "",
                            "source": "library"
                        },

````

https://s3-alpha-sig.figma.com/img/e146/5e54/13dcdc20d1a1ca60ad232c7b985f3690?Expires=1677456000&Signature=PlkmxhUouQJzAU8GANHobkWgNST2REkpwcj~aTk-Rns2wZXKEPSNbfFSnhsQfBfH6kN06C~E5DZIrfibQ1xJekwEY67~sIPl4V5qxfgIbygVjspmjHVf2vYT~aHFvny3zzxdo9I71QnBcKzCQa9EYtHpFy5J9vnWFxtc8-JJtvyqvV4xhLiEDj0UHfxEsx2SAdzZ-MsGtHk1cm-QI1sWsFSRkpNeY14aJJ2qtDqsn7Des3kHb1ZMBtL51-vlZAYHD11JyuecERcWTejRkXl2lTJcq2KpSAbCpAptAqMOLI-EG1W59zB2jdBDf3Kr64K-0t7AKHSZ5TCfpMZdw2elBg__&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4

and the other **has an explicit file extension at the end** 
[Export v10 - with working URL.json.zip](https://github.com/elementor/elementor/files/10724865/Export.v10.-.with.working.URL.json.zip)

e.g:

````json
 "settings": {
                        "image": {
                            "url": "https://www.google.com/images/branding/googlelogo/2x/googlelogo_light_color_272x92dp.png",
                            "id": 3813,
                            "alt": "",
                            "source": "library"
                        },

````

https://www.google.com/images/branding/googlelogo/2x/googlelogo_light_color_272x92dp.png

### STEP 2:
Upload these files into the Elementor through templates > upload etc. - I also tried directly from the Elementor Page Editor > Template etc.. 

### STEP 3:
See that the image with the file extension gets simply uploaded into the Wodpress library, while the file without an explicit file extension, doesn't => it only provides a placeholder.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: mariadb.org binary distribution v10.5.17
	PHP Version: 8.0.27
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: ---
	Home URL: ---
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 512M
	Max Memory limit: 512M
	Permalink Structure: /%category%/%postname%
	Language: en-US
	Timezone: 0
	Admin Email: ---
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/109.0

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 5.12.3
		Author: Delicious Brains

	CSV Table Display
		Version: 1.0
		Author: Your Name

	CSV to HTML Table
		Version: 1.0
		Author: Your Name

	Custom Post Type UI
		Version: 1.13.4
		Author: WebDevStudios

	Duplicator
		Version: 1.5.2.1
		Author: Snap Creek

	Elementor
		Version: 3.11.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.10.3
		Author: Elementor.com

	WP Fastest Cache
		Version: 1.1.1
		Author: Emre Vona

	Yoast SEO
		Version: 20.1
		Author: Team Yoast


== Elements Usage ==
	
	container : 23
		container : 19
		counter : 3
		icon : 2
		icon-list : 6
		image : 4
		image-box : 1
		text-editor : 5
		text-path : 2
	header : 3
		button : 7
		container : 10
		heading : 1
		icon : 4
		icon-list : 1
		image : 3
		text-editor : 1
	page : 45
		container : 17
		image : 11
	popup : 1
		html : 1
		shortcode : 1
	widget : 0
		icon-list : 1
	wp-page : 4
		accordion : 1
		button : 3
		container : 29
		counter : 6
		heading : 1
		html : 1
		icon : 1
		icon-list : 1
		image : 5
		image-box : 2
		spacer : 2
		text-editor : 12
		text-path : 1
	single-post : 1
		container : 14
		heading : 6
		image : 3
		template : 1
		text-editor : 7


== Settings ==
	
	cpt_support: post, page
	disable_color_schemes: yes
	disable_typography_schemes: yes
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Inactive
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Inactive by default
	Default to New Theme Builder: Active
	Hello Theme Header & Footer: Inactive
	Editor V2: Inactive by default
	Landing Pages: Inactive
	Nested Elements: Active
	Lazy Load Background Images: Inactive
	Save as Default: Active by default
	Page Transitions: Active
	Notes: Inactive
	Loop: Inactive by default
	Form Submissions: Active
	Scroll Snap: Active by default


== Log ==
	
JS: showing 10 of 10JS: 2022-12-24 17:04:24 [error X 39][http://broberto.sk/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:51824] Cannot read properties of undefined (reading \'replace\') 
JS: 2023-01-04 12:43:46 [error X 1][https://broberto.sk/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:51816] a is undefined 
JS: 2023-01-05 23:57:04 [error X 5][https://broberto.sk/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:51823] undefined is not an object (evaluating \'a.replace\') 
JS: 2023-01-06 19:46:53 [error X 2][https://broberto.sk/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.10.0-dev1:2:60525] Object.entries requires that input parameter not be null or undefined 
JS: 2023-01-09 23:13:31 [error X 2][https://broberto.sk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.9.2:3:913407] Cannot read properties of undefined (reading \'settings\') 
JS: 2023-01-11 22:33:16 [error X 1][https://broberto.sk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.9.2:3:655306] this.model.isValidChild is not a function 
JS: 2023-02-02 17:01:14 [error X 18][https://broberto.sk/wp-content/plugins/elementor/assets/js/new-template.min.js?ver=3.10.2:2:2869] elementor_new_template_form_controls is not defined 
JS: 2023-02-04 21:47:53 [error X 1][https://broberto.sk/wp-content/plugins/elementor/assets/js/web-cli.min.js?ver=3.10.2:3:79486] Data commands: `#999999` not found. 
JS: 2023-02-09 23:36:05 [error X 1][https://broberto.sk/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:51824] Cannot read properties of undefined (reading 'replace') 
JS: 2023-02-10 17:58:16 [error X 4][https://broberto.sk/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.10.2:2:31256] elementor.settings.page is undefined 

PHP: showing 8 of 8PHP: 2022-12-24 20:21:59 [notice X 40][/data/4/9/49bc964e-27d7-455a-8ab9-429d60fea73e/broberto.sk/web/wp-content/plugins/elementor/modules/performance-lab/module.php::31] Required parameter $url follows optional parameter $size [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-24 20:30:10 [warning X 45][/data/4/9/49bc964e-27d7-455a-8ab9-429d60fea73e/broberto.sk/web/wp-content/plugins/elementor/app/modules/import-export/module.php::563] Attempt to read property "label" on null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-24 20:55:31 [warning X 32][/data/4/9/49bc964e-27d7-455a-8ab9-429d60fea73e/broberto.sk/web/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-24 21:07:09 [error X 3][/data/4/9/49bc964e-27d7-455a-8ab9-429d60fea73e/broberto.sk/web/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on bool in /data/4/9/49bc964e-27d7-455a-8ab9-429d60fea73e/broberto.sk/web/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /data/4/9/49bc964e-27d7-455a-8ab9-429d60fea73e/broberto.sk/web/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /data/4/9/49bc964e-27d7-455a-8ab9-429d60fea73e/broberto.sk/web/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /data/4/9/49bc964e-27d7-455a-8ab9-429d60fea73e/broberto.sk/web/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /data/4/9/49bc964e-27d7-455a-8ab9-429d60fea73e/broberto.sk/web/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#5 /data/4/9/49bc964e-27d7-455a-8ab9-429d60fea73e/broberto.sk/web/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /data/4/9/49bc964e-27d7-455a-8ab9-429d60fea73e/broberto.sk/web/wp-admin/admin-ajax.php(188): do_action('wp_ajax_element...')
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-06 20:52:08 [error X 1][/data/4/9/49bc964e-27d7-455a-8ab9-429d60fea73e/broberto.sk/web/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on null in /data/4/9/49bc964e-27d7-455a-8ab9-429d60fea73e/broberto.sk/web/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /data/4/9/49bc964e-27d7-455a-8ab9-429d60fea73e/broberto.sk/web/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(52, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /data/4/9/49bc964e-27d7-455a-8ab9-429d60fea73e/broberto.sk/web/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /data/4/9/49bc964e-27d7-455a-8ab9-429d60fea73e/broberto.sk/web/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /data/4/9/49bc964e-27d7-455a-8ab9-429d60fea73e/broberto.sk/web/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#5 /data/4/9/49bc964e-27d7-455a-8ab9-429d60fea73e/broberto.sk/web/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /data/4/9/49bc964e-27d7-455a-8ab9-429d60fea73e/broberto.sk/web/wp-admin/admin-ajax.php(188): do_action('wp_ajax_element...')
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-10 23:04:48 [warning X 2][/data/4/9/49bc964e-27d7-455a-8ab9-429d60fea73e/broberto.sk/web/wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-04 20:59:37 [warning X 29][/data/4/9/49bc964e-27d7-455a-8ab9-429d60fea73e/broberto.sk/web/wp-content/plugins/elementor/includes/base/controls-stack.php::2380] Undefined array key "id" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-13 17:55:54 [warning X 1][/data/4/9/49bc964e-27d7-455a-8ab9-429d60fea73e/broberto.sk/web/wp-content/plugins/elementor-pro/elementor-pro.php::27] Constant ELEMENTOR_PRO_MODULES_URL already defined [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 20 of 252023-01-22 16:27:35 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.0-dev1',
  'to' => '3.10.1',
)]
2023-01-22 16:27:35 [info] elementor-pro::elementor_pro_updater Started 
2023-01-22 16:27:35 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-01-22 16:27:35 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-01-22 16:27:36 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.10.0-dev1',
  'to' => '3.10.2',
)]
2023-01-31 19:39:00 [info] elementor::elementor_updater Started 
2023-01-31 19:39:00 [info] Elementor/Upgrades - _on_each_version Start  
2023-01-31 19:39:01 [info] Elementor/Upgrades - _on_each_version Finished 
2023-01-31 19:39:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.1',
  'to' => '3.10.2',
)]
2023-01-31 19:39:01 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.1',
  'to' => '3.10.2',
)]
2023-01-31 19:43:09 [info] elementor-pro::elementor_pro_updater Started 
2023-01-31 19:43:09 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-01-31 19:43:09 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-01-31 19:43:09 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.10.2',
  'to' => '3.10.3',
)]
2023-01-31 19:43:09 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.10.2',
  'to' => '3.10.3',
)]
2023-02-13 17:56:12 [info] elementor::elementor_updater Started 
2023-02-13 17:56:12 [info] Elementor/Upgrades - _on_each_version Start  
2023-02-13 17:56:12 [info] Elementor/Upgrades - _on_each_version Finished 
2023-02-13 17:56:12 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.2',
  'to' => '3.11.0',
)]
2023-02-13 17:56:12 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.2',
  'to' => '3.11.0',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==
	
````

</details>

**Comment by udzrbarik** [comment]
I also think it might be related with this https://github.com/elementor/elementor/issues/544#issuecomment-468627190 comment's issue, even thought here we are speaking of a LIVE site with LIVE images.

**Comment by nicholaszein** [comment]
Hello @udzrbarik,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
- What you are trying to do is not supported by Elementor, therefore it is not a bug.
- There is no way for Elementor to know if the link in question has (or not) one or more images, and which one it should download.

### ✅ What you can do to solve your issue:
- If you have a suggestion to improve our API, we would gladly review a [Pull Request](https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md#before-submitting-a-pr) that you can submit by following our [Contributing Guidelines](https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md).

### 👍 For now, that's all we can help with. 

If you think this is still an issue caused by Elementor, please feel free to open a new 🐞 [Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml).

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
