### ISSUE TITLE
🚧 📚 🐞 Bug Report: Form validation code provided in your documentation creates duplicate fields

### ISSUE THREAD

**Issue by Fox-Robinson** [elementor/elementor#21347]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

The "Tel match this format XXX-XXX-XXXX, i.e. 123-456-7890" section of code, when added to my site, duplicates the phone field : https://developers.elementor.com/docs/hooks/form-validation/

You can see it happening here: https://solarfast.foxrobinson.com/test/ PASSWORD: cucumber

### Steps to reproduce

1. Add a form element

2. Add a phone field.

3. Add the above code to the site

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.5.12
	PHP Version: 8.0.24
	PHP Memory Limit: 2048M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 2048M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://solarfast.foxrobinson.com
	Home URL: https://solarfast.foxrobinson.com
	WP Multisite: No
	Max Upload Size: 2 GB
	Memory limit: 40M
	Max Memory limit: 2048M
	Permalink Structure: /blog/%postname%/
	Language: en-GB
	Timezone: 0
	Admin Email: contact@solarfast.co.uk
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36

== Active Plugins ==
	Duplicator Pro
		Version: 4.5.9.1
		Author: Snap Creek

	Elementor
		Version: 3.11.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.10.3
		Author: Elementor.com

	Password Protected
		Version: 2.6.0
		Author: WPExperts

	Really Simple SSL
		Version: 6.2.0
		Author: Really Simple Plugins

	Temporary Login Without Password
		Version: 1.8.1.1
		Author: StoreApps

	WPCode Lite
		Version: 2.0.7
		Author: WPCode

	WPMU DEV Dashboard
		Version: 4.11.18
		Author: WPMU DEV


== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com


== Elements Usage ==
	
	archive : 4
		container : 14
		heading : 8
		image : 2
		image-carousel : 8
		loop-grid : 4
		testimonial-carousel : 2
		text-editor : 14
	container : 8
		button : 1
		container : 20
		form : 1
		heading : 10
		icon-list : 5
		image : 3
		text-editor : 12
		uael-faq : 1
	page : 15
		animated-headline : 3
		author-box : 3
		button : 66
		call-to-action : 7
		container : 27
		divider : 7
		facebook-comments : 4
		form : 6
		gallery : 1
		heading : 88
		hotspot : 5
		html : 1
		icon : 8
		icon-box : 38
		icon-list : 7
		image : 42
		image-carousel : 9
		lottie : 3
		menu-anchor : 2
		nav-menu : 2
		post-info : 4
		posts : 5
		progress-tracker : 3
		share-buttons : 3
		spacer : 28
		testimonial-carousel : 1
		text-editor : 95
		uael-faq : 1
	popup : 6
		button : 1
		heading : 4
		image : 1
		lottie : 1
		text-editor : 2
		video : 1
	section : 28
		button : 23
		form : 3
		heading : 27
		hotspot : 1
		icon-box : 23
		icon-list : 3
		image : 11
		image-carousel : 7
		lottie : 1
		menu-anchor : 3
		nav-menu : 1
		posts : 1
		social-icons : 1
		spacer : 5
		testimonial-carousel : 1
		text-editor : 34
	wp-post : 
		button : 8
		container : 332
		divider : 8
		form : 16
		heading : 159
		html : 8
		icon : 40
		icon-box : 32
		icon-list : 8
		image : 46
		image-carousel : 32
		shortcode : 1
		testimonial-carousel : 8
		text-editor : 178
		uael-faq : 16
		ucaddon_location_main_title : 8
		ucaddon_location_office_address : 8
		ucaddon_location_office_opening_hours : 8
		ucaddon_location_office_phone_number : 8
		wpr-feature-list : 2
	wp-page : 30
		animated-headline : 1
		button : 95
		container : 146
		divider : 3
		form : 16
		heading : 167
		hotspot : 8
		html : 6
		icon : 38
		icon-box : 58
		icon-list : 11
		image : 46
		image-carousel : 20
		loop-grid : 2
		lottie : 3
		menu-anchor : 7
		posts : 2
		shortcode : 1
		spacer : 108
		testimonial-carousel : 1
		text-editor : 195
		uael-faq : 1
		video : 1
		wpr-feature-list : 1
		wpr-tabs : 3
	loop-item : 2
		container : 2
		heading : 2
		text-editor : 4
	error-404 : 1
		heading : 2
		icon : 1
		text-editor : 1


== Settings ==
	
	cpt_support: post, page, e-landing-page, wpr_templates, sectors, locations, wpr_mega_menu
	disable_color_schemes: yes
	disable_typography_schemes: yes
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap


== Features ==
	Custom Fonts: 3
	Custom Icons: 1

== Integrations ==
	
	recaptcha: Active
	recaptcha_v3: Active


== Elementor Experiments ==
	Optimised DOM Output: Active
	Improved asset loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility improvements: Inactive by default
	Additional Custom Breakpoints: Inactive by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Inactive by default
	Editor V2: Inactive by default
	Landing pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default
	Save as Default: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active
	Loop Carousel: Inactive by default
	Form Submissions: Active by default
	Scroll Snap: Active by default


== Log ==
	
Log: showing 20 of 232023-01-19 13:33:01 [info] elementor::elementor_updater Started 
2023-01-19 13:33:01 [info] Elementor/Upgrades - _on_each_version Start  
2023-01-19 13:33:02 [info] Elementor/Upgrades - _on_each_version Finished 
2023-01-19 13:33:02 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Start  
2023-01-19 13:33:02 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Finished 
2023-01-19 13:33:02 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.2',
  'to' => '3.10.1',
)]
2023-01-19 13:33:03 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.2',
  'to' => '3.10.1',
)]
2023-02-11 11:51:16 [info] elementor-pro::elementor_pro_updater Started 
2023-02-11 11:51:16 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-02-11 11:51:16 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-02-11 11:51:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.10.2',
  'to' => '3.10.3',
)]
2023-02-11 11:51:29 [info] elementor::elementor_updater Started 
2023-02-11 11:51:29 [info] Elementor/Upgrades - _on_each_version Start  
2023-02-11 11:51:30 [info] Elementor/Upgrades - _on_each_version Finished 
2023-02-11 11:51:30 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.1',
  'to' => '3.10.2',
)]
2023-02-14 12:57:30 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.2',
  'to' => '3.11.0',
)]
2023-02-14 12:57:34 [info] elementor::elementor_updater Started 
2023-02-14 12:57:34 [info] Elementor/Upgrades - _on_each_version Start  
2023-02-14 12:57:37 [info] Elementor/Upgrades - _on_each_version Finished 
2023-02-14 12:57:37 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.2',
  'to' => '3.11.0',
)]

PHP: showing 7 of 7PHP: 2023-01-19 13:49:27 [warning X 1][/home/u229263675/domains/foxrobinson.com/public_html/solarfast\wp-content\plugins\elementor-pro\modules\assets-manager\asset-types\icons\custom-icons.php::199] unlink(SF-Grey-Icons-v1.0-1.7zip): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-19 16:05:25 [warning X 1][/home/u229263675/domains/foxrobinson.com/public_html/solarfast\wp-content\plugins\elementor-pro\modules\assets-manager\asset-types\icons\custom-icons.php::199] unlink(): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-04 16:22:52 [notice X 1][/home/u229263675/domains/foxrobinson.com/public_html/solarfast\wp-content\plugins\elementor-pro\modules\forms\classes\recaptcha-v3-handler.php::124] Undefined index: score [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-09 15:52:30 [notice X 3][/home/u229263675/domains/foxrobinson.com/public_html/solarfast\wp-content\plugins\elementor-pro\modules\usage\module.php::136] Trying to get property 'count' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-10 12:16:37 [error X 2][/home/u229263675/domains/foxrobinson.com/public_html/solarfast\wp-content\plugins\elementor\core\common\modules\ajax\module.php::266] Allowed memory size of 268435456 bytes exhausted (tried to allocate 1466368 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-10 15:02:01 [error X 1][/home/u229263675/domains/foxrobinson.com/public_html/solarfast\wp-content\plugins\elementor-pro\modules\theme-builder\module.php::34] Uncaught Error: Class 'ElementorPro\Core\Utils' not found in /home/u229263675/domains/foxrobinson.com/public_html/solarfast\wp-content\plugins\elementor-pro\modules\theme-builder\module.php:34
Stack trace:
#0 /home/u229263675/domains/foxrobinson.com/public_html/solarfast\wp-content\plugins\elementor-pro\modules\theme-builder\conditions\archive.php(39): ElementorPro\Modules\ThemeBuilder\Module::get_public_post_types()
#1 /home/u229263675/domains/foxrobinson.com/public_html/solarfast\wp-content\plugins\elementor-pro\modules\theme-builder\conditions\condition-base.php(66): ElementorPro\Modules\ThemeBuilder\Conditions\Archive->register_sub_conditions()
#2 /home/u229263675/domains/foxrobinson.com/public_html/solarfast\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-manager.php(183): ElementorPro\Modules\ThemeBuilder\Conditions\Condition_Base->__construct()
#3 /home/u229263675/domains/foxrobinson.com/public_html/solarfast\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-manager.php(194): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->regi [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-13 16:06:50 [error X 1][/home/u229263675/domains/foxrobinson.com/public_html/solarfast\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-manager.php::295] Uncaught Error: Call to a member function update_meta() on bool in /home/u229263675/domains/foxrobinson.com/public_html/solarfast\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-manager.php:295
Stack trace:
#0 /home/u229263675/domains/foxrobinson.com/public_html/solarfast\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-manager.php(168): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions()
#2 /home/u229263675/domains/foxrobinson.com/public_html/solarfast\wp-content\plugins\elementor\core\common\modules\ajax\module.php(172): call_user_func()
#3 /home/u229263675/domains/foxrobinson.com/public_html/solarfast\wp-includes\class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#4 /home/u229263675/domains/foxrobinson.com/public_html/solarfast\wp-includes\class-wp-hook.php(332): WP_Hook->apply_filters()
#5 /home/u229263675/domains/foxrobinson.com/public_html/solarfast\wp-includes\plugin.php( [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 13 of 13JS: 2023-01-19 15:24:25 [error X 34][https://solarfast.foxrobinson.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:9:82426] Cannot read properties of undefined (reading 'name') 
JS: 2023-01-20 15:53:08 [error X 11][https://solarfast.foxrobinson.com/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.10.2:2:61404] Cannot convert undefined or null to object 
JS: 2023-01-20 16:46:39 [error X 5][https://solarfast.foxrobinson.com/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.10.2:2:61404] can't convert undefined to object 
JS: 2023-02-07 15:05:01 [error X 1][https://solarfast.foxrobinson.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view2801") has already been destroyed and cannot be used. 
JS: 2023-02-07 15:05:19 [error X 1][https://solarfast.foxrobinson.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view2951") has already been destroyed and cannot be used. 
JS: 2023-02-08 13:38:12 [error X 55][https://solarfast.foxrobinson.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.10.1:3:377388] Cannot read properties of undefined (reading 'controls') 
JS: 2023-02-08 14:19:20 [error X 18][https://solarfast.foxrobinson.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.10.1:3:661291] this.model.isValidChild is not a function 
JS: 2023-02-08 15:11:55 [error X 3][https://solarfast.foxrobinson.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.10.1:3:919844] Cannot read properties of undefined (reading 'settings') 
JS: 2023-02-08 15:35:31 [error X 1][https://solarfast.foxrobinson.com/wp-content/plugins/elementor/assets/js/web-cli.min.js?ver=3.10.1:3:104425] Routes: `panel/page-settings/yoast-tab` not found. 
JS: 2023-02-10 14:56:04 [error X 1][https://solarfast.foxrobinson.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.10.2:3:262635] Cannot read properties of undefined (reading 'top') 
JS: 2023-02-10 15:22:55 [error X 1][https://solarfast.foxrobinson.com/wp-content/plugins/elementor-pro/assets/js/admin.min.js?ver=3.10.3:2:4622] e is null 
JS: 2023-02-10 15:25:14 [error X 4][https://solarfast.foxrobinson.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.10.2:3:147244] T is undefined 
JS: 2023-02-10 15:41:17 [error X 5][https://solarfast.foxrobinson.com/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:51824] Cannot read properties of undefined (reading 'replace') 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Incompatible

== Elementor Pro - Compatibility Tag ==
	

				
````

</details>

**Comment by nicholaszein** [comment]
Hello @Fox-Robinson! 

Thank you for submitting your issue! 🙏 

Please allow us some time to investigate it, and get back to you with our findings. 🧐 

Best regards

**Comment by Fox-Robinson** [comment]
I dont know if this is bad etiquette here on Github, but I'd like to follow up to get an idea of how long this might take?

**Comment by lensbreak** [comment]
> I dont know if this is bad etiquette here on Github, but I'd like to follow up to get an idea of how long this might take?

Usually 6-24 months as in the usual Elementor habit. Hate to say it but some of the bugs I reported a year ago are still not fixed and many people are complaining. Even the latest bug https://github.com/elementor/elementor/issues/21003 nobody from Elementor has replied so far. That's how they loose our trust and us as customers in the long run. Shame.

**Comment by rami-elementor** [comment]
@Fox-Robinson 

Please read the "[Elementor Form Fields](https://developers.elementor.com/docs/form-fields/)" docs.

There is a good example on [how to create an Elementor addon that adds a new field for phone numbers](https://developers.elementor.com/docs/form-fields/simple-example/).

This way you will be able to create a field with your own phone pattern and your custom form validation message.

**Comment by nicholaszein** [comment]
Hello @Fox-Robinson,

please check Rami's comment above, follow the documentation, and let us know if this solves your issue.

Kind regards

**Comment by nicholaszein** [comment]
Hello there @Fox-Robinson, 

### 🕙 It's been a while since we answered you, and we haven't received any feedback. 

## 🚧 For this reason, we are closing this issue because of no activity.

Kind regards
