### ISSUE TITLE
Dynamic background image not showing after update

### ISSUE THREAD

**Issue by aksellno** [elementor/elementor#21345]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

After updating to Elementor Pro 3.11.0 if a background image is set using the dynamic tags it doesn't show on either sizes.

We were using Featured Image as a dynamic tag for background image on a whole section and it shows in Edit view, but not in Front end.

The code doesn't seem to show that an image has been loaded either.

### Steps to reproduce

Set a featured image for post
In a section, go to Style tab, then under Background set Image as Dynamic tag for Featured Image.
Publish

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.18 (Ubuntu)
	MySQL version: Ubuntu 22.04 v10.6.11
	PHP Version: 8.0.5
	PHP Memory Limit: 
	PHP Max Input Vars: 1000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://aksell.no
	Home URL: https://aksell.no
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%category%/%postname%/
	Language: nb-NO
	Timezone: Europe/Oslo
	Admin Email: developer.sor@07.no
	Debug Mode: Inactive

== Theme ==
	Name: Aksell
	Version: 1.2
	Author: Anja Sofie Nedler Haugen, Anneroos Schieke, Lasse Spilling og Alf Otto Fagermo
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: nb_NO
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36

== Active Plugins ==
	ACF: Better Search
		Version: 4.0.1
		Author: Mateusz Gbiorczyk

	ACF Content Analysis for Yoast SEO
		Version: 3.0.1
		Author: Thomas Kräftner, ViktorFroberg, marol87, pekz0r, angrycreative, Team Yoast

	Add Featured Image Column
		Version: 1.1.6
		Author: Robin Cornett

	Admin Columns for ACF Fields
		Version: 0.1.2
		Author: Florian Eickhorst

	Admin Taxonomy Filter
		Version: 1.0.2
		Author: eLightUp

	Advanced Custom Fields: Extended
		Version: 0.8.9.1
		Author: ACF Extended

	Advanced Custom Fields PRO
		Version: 6.0.7
		Author: WP Engine

	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Classic Widgets
		Version: 0.3
		Author: WordPress Contributors

	Custom Post Type UI
		Version: 1.13.4
		Author: WebDevStudios

	Elementor
		Version: 3.11.0
		Author: Elementor.com

	Elementor Header &amp; Footer Builder
		Version: 1.6.13
		Author: Brainstorm Force, Nikhil Chavan

	Elementor Pro
		Version: 3.11.0
		Author: Elementor.com

	Enable Media Replace
		Version: 4.0.2
		Author: ShortPixel

	Folders Pro
		Version: 2.8.5
		Author: Premio

	Gravity Forms
		Version: 2.7
		Author: Gravity Forms

	Gravity Forms First Error Focus
		Version: 1.4
		Author: Gravity Wiz

	GTM4WP
		Version: 1.16.2
		Author: Thomas Geiger

	Include Me
		Version: 1.3.0
		Author: Stefano Lissa

	Instant Images
		Version: 5.1.0.1
		Author: Darren Cooney

	Loco Translate
		Version: 2.6.3
		Author: Tim Whitlock

	Logos Showcase
		Version: 2.1
		Author: Carlos Moreira

	ManageWP - Worker
		Version: 4.9.16
		Author: GoDaddy

	Notification Attachments for Gravity Forms
		Version: 0.5
		Author: KGM Servizi

	Portfolio Filter Gallery Premium
		Version: 6.9.9
		Author: A WP Life

	Post Types Order
		Version: 1.9.9.2
		Author: Nsp Code

	reBusted!
		Version: 1.1
		Author: Simon Prosser

	Redirection
		Version: 5.3.9
		Author: John Godley

	Search Exclude
		Version: 1.3.1
		Author: QuadLayers

	SearchWP Live Ajax Search
		Version: 1.7.4
		Author: SearchWP, LLC

	SMTP2GO - Email Made Easy
		Version: 1.4.2
		Author: SMTP2GO

	Stop Spammers
		Version: 2022.6
		Author: Trumani

	TF Slide Swiper Addon For Elementor
		Version: 1.0.1
		Author: Themesflat

	WordPress Importer
		Version: 0.8
		Author: wordpressdotorg

	WP SVG Images
		Version: 4.1
		Author: ShortPixel

	WP User Profile Avatar
		Version: 1.0
		Author: WP Event Manager

	Yoast Duplicate Post
		Version: 4.5
		Author: Enrico Battocchi & Team Yoast

	Yoast SEO
		Version: 20.1
		Author: Team Yoast

	Yoast SEO Premium
		Version: 20.1
		Author: Team Yoast

== Must-Use Plugins ==
	ManageWP - Worker Loader
		Version: 1.0.0
		Author: GoDaddy

== Elements Usage ==
	
	archive : 1
		archive-posts : 1
		button : 1
		spacer : 3
		theme-archive-title : 1
	section : 1
		aksell-locations-map : 1
		form : 1
		text-editor : 2
	wp-post : 0
		aksell-animated-bg-pattern : 1
		button : 3
		heading : 6
		hfe-search-button : 2
		html : 7
		icon-box : 8
		icon-list : 2
		image : 8
		social-icons : 1
		spacer : 6
	wp-page : 40
		aksell-animated-bg-pattern : 20
		aksell-animated-icons : 23
		aksell-featured-blog-post : 1
		aksell-featured-post : 19
		aksell-find-people : 1
		aksell-img-grid : 24
		aksell-locations-map : 4
		aksell-posts-grid : 6
		aksell-sliding-words : 3
		aksell-video-grid : 1
		button : 62
		divider : 32
		form : 13
		heading : 111
		html : 17
		icon : 6
		icon-list : 2
		image : 80
		image-carousel : 1
		menu-anchor : 2
		portfolio : 1
		shortcode : 12
		spacer : 234
		text-editor : 129
		theme-post-featured-image : 1
		toggle : 1
	single-post : 4
		aksell-animated-bg-pattern : 2
		author-box : 2
		button : 4
		gallery : 2
		heading : 2
		image : 5
		lottie : 1
		shortcode : 2
		spacer : 14
		theme-post-content : 3
		theme-post-excerpt : 3
		theme-post-featured-image : 2
		theme-post-title : 3
	search-results : 1
		archive-posts : 1
		spacer : 4
		theme-archive-title : 1
	error-404 : 1
		aksell-animated-bg-pattern : 1
		button : 1
		heading : 1
		image : 3
		text-editor : 1

== Innstillinger ==
	
	cpt_support: page
	allow_tracking: yes
	unfiltered_files_upload: 1

== Features ==
	Custom Fonts: 1
	Custom Icons: 0

== Integrasjoner ==
	
	recaptcha: Active
	recaptcha_v3: Active

== Elementor Experiments ==
	Optimized DOM Output: Aktiv som standard
	Improved Asset Loading: Aktiv som standard
	Improved CSS Loading: Aktiv som standard
	Inline Font Icons: Inaktiv som standard
	Forbedringer av tilgjengelighet: Aktiv som standard
	Additional Custom Breakpoints: Aktiv som standard
	admin_menu_rearrangement: Inaktiv som standard
	Flexbox Container: Inaktiv som standard
	Upgrade Swiper Library: Inaktiv som standard
	Default to New Theme Builder: Aktiv som standard
	Editor V2: Inaktiv som standard
	Landingssider: Aktiv som standard
	Nested Elements: Inaktiv som standard
	Lazy Load Background Images: Inaktiv som standard
	Save as Default: Aktiv som standard
	Page Transitions: Aktiv som standard
	Notes: Aktiv som standard
	Loop: Aktiv som standard
	Form Submissions: Aktiv som standard
	Scroll Snap: Aktiv som standard
	Mega Menu: Inaktiv som standard

== Logg ==
	
Log: showing 20 of 382023-01-30 08:28:23 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.1',
  'to' => '3.10.2',
)]
2023-01-30 08:28:30 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.10.2',
  'to' => '3.10.3',
)]
2023-01-30 08:28:38 [info] elementor::elementor_updater Started 
2023-01-30 08:28:38 [info] Elementor/Upgrades - _on_each_version Start  
2023-01-30 08:28:39 [info] Elementor/Upgrades - _on_each_version Finished 
2023-01-30 08:28:39 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.1',
  'to' => '3.10.2',
)]
2023-01-30 08:29:20 [info] elementor-pro::elementor_pro_updater Started 
2023-01-30 08:29:20 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-01-30 08:29:20 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-01-30 08:29:20 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.10.2',
  'to' => '3.10.3',
)]
2023-02-13 12:30:21 [info] elementor::elementor_updater Started 
2023-02-13 12:30:21 [info] Elementor/Upgrades - _on_each_version Start  
2023-02-13 12:30:22 [info] Elementor/Upgrades - _on_each_version Finished 
2023-02-13 12:30:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.2',
  'to' => '3.11.0',
)]
2023-02-13 12:30:22 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.2',
  'to' => '3.11.0',
)]
2023-02-13 12:51:15 [info] elementor-pro::elementor_pro_updater Started 
2023-02-13 12:51:15 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-02-13 12:51:15 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-02-13 12:51:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.10.3',
  'to' => '3.11.0',
)]
2023-02-13 12:51:15 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.10.3',
  'to' => '3.11.0',
)]

JS: showing 1 of 1JS: 2023-01-12 13:06:29 [error X 8][https://aksell.no/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:51824] Cannot read properties of undefined (reading &#039;replace&#039;) 

PHP: showing 3 of 3PHP: 2023-01-25 15:18:56 [error X 1][/var/www/1/72876/www/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::295] Uncaught Error: Call to a member function update_meta() on null in /var/www/1/72876/www/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:295
Stack trace:
#0 /var/www/1/72876/www/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(168): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;save_conditions(10, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /var/www/1/72876/www/wp-content/plugins/elementor/core/common/modules/ajax/module.php(172): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /var/www/1/72876/www/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module-&gt;handle_ajax_request(&#039;&#039;)
#4 /var/www/1/72876/www/wp-includes/class-wp-hook.php(332): WP_Hook-&gt;apply_filters(&#039;&#039;, Array)
#5 /var/www/1/72876/www/wp-includes/plugin.php(517): WP_Hook-&gt;do_action(Array)
#6 /var/www/1/72876/www/wp-admin/admin-ajax.php(188): do_action(&#039;wp_ajax_element...&#039;)
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-31 12:10:47 [warning X 3][/var/www/1/72876/www/wp-content/plugins/elementor-pro/modules/forms/classes/recaptcha-v3-handler.php::124] Undefined array key &quot;score&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-13 12:54:10 [warning X 2][/var/www/1/72876/www/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined array key &quot;data&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Header & Footer Builder: Compatibility not specified
	Elementor Pro: Compatibility not specified
	TF Slide Swiper Addon For Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by aksellno** [comment]
Duplicate of https://github.com/elementor/elementor/issues/21313
