### ISSUE TITLE
⛔ 🐞 Bug Report: Import kit imports empty templates when experimental features are not active

### ISSUE THREAD

**Issue by vladninja** [elementor/elementor#21351]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When the user exports the kit from the WP which uses some experimental features and then import to the WP which do not have active these experimental features, the Importer import the temples, but all are empty.
![image](https://user-images.githubusercontent.com/76119088/219015338-14962a6c-bf1f-40eb-b960-74133cc8b632.png)

Please add a checking mechanism during the import progress and made a decision for the user during the import or activate features which are used in the imported kit.

### Steps to reproduce

1. Export template kit from WP which use some experimental features (in my case nested tabs and containers)
2. Import kit to WP which have default values for the experimental features (disabled nested tabs and containers)

-> Kit will be imported, but all the templates will be empty

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt
	
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.54 (Debian)
	MySQL version: MySQL Community Server - GPL v8.0.31
	PHP Version: 7.4.33
	PHP Memory Limit: 
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: No
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: http://localhost:8083
	Home URL: http://localhost:8083
	WP Multisite: No
	Max Upload Size: 2 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: pl-PL
	Timezone: Europe/Warsaw
	Admin Email: xojeba6362@0pppp.com
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: pl_PL
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36

== Active Plugins ==

	Elementor
		Version: 3.10.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.10.2
		Author: Elementor.com


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Landing Pages: Active by default
	Nested Elements: Inactive
	Lazy Load Background Images: Inactive by default
	Save as Default: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active by default
	Loop Carousel: Inactive by default
	Form Submissions: Active by default
	Scroll Snap: Active by default


== Log ==
	
PHP: showing 5 of 5PHP: 2023-02-15 12:01:58 [notice X 4][/var/www/html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::172] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-15 12:02:02 [notice X 5][/var/www/html/wp-content/plugins/elementor-pro/core/app/modules/import-export/runners/import/templates.php::103] Undefined index: conditions [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-15 12:02:03 [notice X 5][/var/www/html/wp-content/plugins/elementor/core/base/document.php::1563] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-15 12:02:59 [notice X 8][/var/www/html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined index: condition_type [array (
  'trace' => '
#0: /var/www/html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /var/www/html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /var/www/html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /var/www/html/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2023-02-15 12:03:28 [error X 1][/var/www/html/wp-content/plugins/elementor/core/frontend/render-modes/render-mode-base.php::88] Uncaught Error: Call to a member function is_editable_by_current_user() on bool in /var/www/html/wp-content/plugins/elementor/core/frontend/render-modes/render-mode-base.php:88
Stack trace:
#0 /var/www/html/wp-content/plugins/elementor/core/frontend/render-mode-manager.php(133): Elementor\Core\Frontend\RenderModes\Render_Mode_Base->get_permissions_callback()
#1 /var/www/html/wp-content/plugins/elementor/core/frontend/render-mode-manager.php(157): Elementor\Core\Frontend\Render_Mode_Manager->add_current_actions()
#2 /var/www/html/wp-content/plugins/elementor/includes/frontend.php(194): Elementor\Core\Frontend\Render_Mode_Manager->__construct()
#3 /var/www/html/wp-includes/class-wp-hook.php(308): Elementor\Frontend->init_render_mode('')
#4 /var/www/html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#5 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /var/www/html/wp-includes/template-loader.php(13): do_action('template_redire...')
#7 /var/www/html/wp-blog-header. [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==
	

				
````

</details>

**Comment by nicholaszein** [comment]
Hello @vladninja,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
This is the expected and logical behavior. If a certain experiment is not active, it won't be imported. Both sites need to have the same settings for the export/import work correctly.

### ✅ What you can do to solve your issue:
Activate the inactive experiments before importing.

### 👍 For now, that's all we can help with. 

If you think this should be a feature, please submit a new [Feature Request](https://github.com/elementor/elementor/discussions/new?category=feature-request) instead.

Kind regards
