### ISSUE TITLE
Swiper stylesheet is loading even the Improved CSS Loading features is enabled

### ISSUE THREAD

**Issue by Kishorchandth** [elementor/elementor#21362]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hello, dev,

I update both the Elementor and Elementor Pro to the latest version and found the Swiper stylesheet is loading even when I **enabled** the Improved CSS Loading Feature. 

To my knowledge, the issue is related to the **NEW Upgrade Swiper Library Feature**

![swiper](https://user-images.githubusercontent.com/39625343/219276361-4a3a9892-4141-462d-bec0-e18d6bc1729d.jpg)
 
Please keep this mind that even when I set the Upgrade Swiper Library Features to **inactive**, the stylesheet is still loading **_before it didn't_**. I also check whether I use any Swiper-related widgets and turn out I didn't use any.

**This is the inline frontend JS config:**

`<script id='elementor-frontend-js-before'> var elementorFrontendConfig = {"environmentMode":{"edit":false,"wpPreview":false,"isScriptDebug":false},"i18n":{"shareOnFacebook":"Share on Facebook","shareOnTwitter":"Share on Twitter","pinIt":"Pin it","download":"Download","downloadImage":"Download image","fullscreen":"Fullscreen","zoom":"Zoom","share":"Share","playVideo":"Play Video","previous":"Previous","next":"Next","close":"Close"},"is_rtl":false,"breakpoints":{"xs":0,"sm":480,"md":768,"lg":1025,"xl":1440,"xxl":1600},"responsive":{"breakpoints":{"mobile":{"label":"Mobile","value":767,"default_value":767,"direction":"max","is_enabled":true},"mobile_extra":{"label":"Mobile Extra","value":880,"default_value":880,"direction":"max","is_enabled":false},"tablet":{"label":"Tablet","value":1024,"default_value":1024,"direction":"max","is_enabled":true},"tablet_extra":{"label":"Tablet Extra","value":1200,"default_value":1200,"direction":"max","is_enabled":false},"laptop":{"label":"Laptop","value":1366,"default_value":1366,"direction":"max","is_enabled":false},"widescreen":{"label":"Widescreen","value":2400,"default_value":2400,"direction":"min","is_enabled":false}}},
  | "version":"3.11.1","is_static":false,"experimentalFeatures":{"e_dom_optimization":true,"e_optimized_assets_loading":true,"e_optimized_css_loading":true,"e_font_icon_svg":true,"a11y_improvements":true,"container":true,"theme_builder_v2":true,"e_lazyload":true,"kit-elements-defaults":true,"loop":true,"e_scroll_snap":true},"urls":{"assets":"https:\/\/beta.local\/wp-content\/plugins\/elementor\/assets\/"},"swiperClass":"swiper-container","settings":{"page":[],"editorPreferences":[]},"kit":{"active_breakpoints":["viewport_mobile","viewport_tablet"],"lightbox_enable_counter":"yes","lightbox_enable_fullscreen":"yes","lightbox_enable_zoom":"yes","lightbox_enable_share":"yes","lightbox_title_src":"title","lightbox_description_src":"description"},"post":{"id":400,"title":"Remove%20unused%20CSS%20from%20the%20Elementor%20website%20manually%20%E2%80%93%20Testing%20Elementor%20Beta","excerpt":"In this step by step tutorials, we are going to learn how to remove unused CSS from Elementor website without breaking website manually.","featuredImage":"https:\/\/beta.local\/wp-content\/uploads\/2022\/03\/115-business-consulting-agency_blog_7-1024x594.jpg"}};</script>
`

### Steps to reproduce

Update Elementor Core and Pro to version 3.11.1. Whether you enabled or disabled **"Upgrade Swiper Library"**. The stylesheets will load 

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

					
== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.47 (Win64) OpenSSL/1.1.1k PHP/7.4.19
	MySQL version: MySQL Community Server (GPL) v5.7.33
	PHP Version: 7.4.19
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 2G
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://beta.local
	Home URL: https://beta.local
	WP Multisite: No
	Max Upload Size: 2 GB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: 
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 6.0.7
		Author: WP Engine

	Asset CleanUp: Page Speed Booster
		Version: 1.3.9.0
		Author: Gabe Livan

	Code Snippets
		Version: 3.2.2
		Author: Code Snippets Pro

	Elementor
		Version: 3.11.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.11.1
		Author: Elementor.com

	Performance Lab
		Version: 1.9.0
		Author: WordPress Performance Team

	Unlimited Elements for Elementor
		Version: 1.5.52
		Author: Unlimited Elements

== Must-Use Plugins ==
	WP Shifty Loader
		Version: 
		Author: 

== Elements Usage ==
	
	archive : 1
		button : 1
		heading : 3
		posts : 1
		text-editor : 1
	container : 7
		button : 2
		container : 19
		heading : 6
		image : 5
		nav-menu : 1
		text-editor : 6
		ucaddon_ue_site_logo : 1
	footer : 1
		container : 3
		form : 1
		heading : 5
		icon : 1
		social-icons : 1
	header : 3
		container : 1
		nav-menu : 1
		progress-tracker : 1
		theme-site-logo : 1
	page : 2
		button : 2
		container : 4
		countdown : 1
		form : 1
		heading : 25
		icon : 8
		spacer : 5
	section : 2
		button : 2
		nav-menu : 2
		ucaddon_ue_site_logo : 2
	wp-post : 1
		container : 1
		text-editor : 1
	wp-page : 10
		button : 6
		call-to-action : 12
		container : 8
		divider : 13
		form : 1
		google_maps : 2
		heading : 48
		image : 3
		image-carousel : 1
		loop-carousel : 1
		loop-grid : 1
		media-carousel : 1
		posts : 3
		spacer : 8
		text-editor : 32
		ucaddon_horizontal_scroll : 1
		ucaddon_inject_js : 1
		ucaddon_lite_vimeo_embedded : 1
	single-post : 3
		call-to-action : 2
		container : 16
		heading : 4
		html : 4
		image : 1
		loop-grid : 3
		post-comments : 1
		post-info : 4
		shortcode : 1
		table-of-contents : 3
		text-editor : 1
		theme-post-content : 3
		theme-post-excerpt : 3
		theme-post-featured-image : 1
		theme-post-title : 3
		ucaddon_disqus_comment : 2
		ucaddon_featured_image : 2
		ucaddon_post_List : 2
	loop-item : 1
		button : 1
		container : 2
		post-info : 1
		theme-post-excerpt : 1
		theme-post-featured-image : 1
		theme-post-title : 1
	error-404 : 1
		button : 1
		container : 2
		heading : 2
		image : 1
		text-editor : 1

== Settings ==
	
	cpt_support: post, page
	disable_color_schemes: yes
	disable_typography_schemes: yes
	allow_tracking: yes
	editor_break_lines: 1
	unfiltered_files_upload: 1
	font_display: optional

== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Inactive
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Inactive
	Default to New Theme Builder: Active
	Hello Theme Header & Footer: Inactive
	Editor V2: Inactive by default
	Landing Pages: Inactive
	Nested Elements: Inactive
	Lazy Load Background Images: Active
	Save as Default: Active
	Page Transitions: Inactive
	Notes: Inactive
	Loop: Active
	Form Submissions: Inactive
	Scroll Snap: Active
	Mega Menu: Inactive by default

== Log ==
	
Log: showing 20 of 322023-02-08 04:12:41 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.0-beta1',
  'to' => '3.11.0-beta2',
)]
2023-02-08 04:12:41 [info] elementor-pro::elementor_pro_updater Started 
2023-02-08 04:12:41 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-02-08 04:12:41 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-02-08 04:12:41 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.0-beta1',
  'to' => '3.11.0-beta2',
)]
2023-02-13 07:26:26 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.0-beta2',
  'to' => '3.11.0-beta3',
)]
2023-02-13 07:26:27 [info] elementor-pro::elementor_pro_updater Started 
2023-02-13 07:26:27 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-02-13 07:26:27 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-02-13 07:26:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.0-beta2',
  'to' => '3.11.0-beta3',
)]
2023-02-16 05:01:48 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.0-beta1',
  'to' => '3.11.1',
)]
2023-02-16 05:01:49 [info] elementor::elementor_updater Started 
2023-02-16 05:01:49 [info] Elementor/Upgrades - _on_each_version Start  
2023-02-16 05:01:50 [info] Elementor/Upgrades - _on_each_version Finished 
2023-02-16 05:01:50 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.0-beta1',
  'to' => '3.11.1',
)]
2023-02-16 05:04:07 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.0-beta3',
  'to' => '3.11.1',
)]
2023-02-16 05:04:08 [info] elementor-pro::elementor_pro_updater Started 
2023-02-16 05:04:08 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-02-16 05:04:08 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-02-16 05:04:08 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.0-beta3',
  'to' => '3.11.1',
)]

PHP: showing 8 of 8PHP: 2023-01-31 05:31:37 [error X 2][C:\laragon\www\beta\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-manager.php::295] Uncaught Error: Call to a member function update_meta() on bool in C:\laragon\www\beta\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-manager.php:295
Stack trace:
#0 C:\laragon\www\beta\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-manager.php(168): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 C:\laragon\www\beta\wp-content\plugins\elementor\core\common\modules\ajax\module.php(175): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 C:\laragon\www\beta\wp-includes\class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 C:\laragon\www\beta\wp-includes\class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#5 C:\laragon\www\beta\wp-includes\plugin.php(517): WP_ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-05 05:29:03 [warning X 1][C:\laragon\www\beta\wp-content\plugins\elementor\core\files\file-types\svg.php::234] simplexml_load_file(): I/O warning : failed to load external entity "https://beta.local/wp-content/uploads/2023/02/1_Home_Interior_Design-Instagram_Fill.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-05 05:35:40 [warning X 1][C:\laragon\www\beta\wp-content\plugins\elementor\core\files\file-types\svg.php::234] simplexml_load_file(): I/O warning : failed to load external entity "https://beta.local/wp-content/uploads/2023/02/Instagram_Fill.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-09 15:52:57 [notice X 2][C:\laragon\www\beta\wp-content\plugins\elementor\includes\managers\image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-13 09:16:26 [notice X 2][C:\laragon\www\beta\wp-content\plugins\elementor\core\common\modules\ajax\module.php::175] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-13 09:16:27 [notice X 2][C:\laragon\www\beta\wp-content\plugins\elementor-pro\core\app\modules\site-editor\data\endpoints\templates.php::150] Undefined index: condition_type [array (
  'trace' => '
#0: C:\laragon\www\beta\wp-content\plugins\elementor-pro\core\app\modules\site-editor\data\endpoints\templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: C:\laragon\www\beta\wp-content\plugins\elementor-pro\core\app\modules\site-editor\data\endpoints\templates.php(120): class type array_map()
#3: C:\laragon\www\beta\wp-content\plugins\elementor-pro\core\app\modules\site-editor\data\endpoints\templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: C:\laragon\www\beta\wp-content\plugins\elementor\data\base\endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2023-02-13 10:00:36 [notice X 1][C:\laragon\www\beta\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-manager.php::168] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-16 05:13:02 [notice X 1][C:\laragon\www\beta\wp-content\plugins\elementor\app\modules\import-export\module.php::629] Trying to get property 'label' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 2 of 2JS: 2023-01-31 05:35:46 [error X 11][https://beta.local/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.11.0-beta1:3:591818] Cannot read properties of null (reading 'id') 
JS: 2023-02-05 07:12:36 [error X 1][https://beta.local/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.11.0-beta1:3:670621] this.model.isValidChild is not a function 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	Unlimited Elements for Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @Kishorchandth! 

Thank you for submitting your issue! 🙏 

🏷️ This issue has been labeled and will be forwarded to the team for validation and possible solution. Please keep in mind that we can't provide any ETA on when this issue could be fixed if it is validated. We ask for patience.

Best regards

**Comment by samuelmente** [comment]
Would love to see an update on this. Would remove quite a bit of unused css on many of my pages.

**Comment by puregraphx** [comment]
Still no ETA after 1,5 years?

**Comment by itiva-ab** [comment]
Hello,

No ETA still?

I stumbled upon this issue when trying to remove the Lighthouse warning :-)
