### ISSUE TITLE
⛔ 🐞 Bug Report: Elementor Menu dropdown and Popups broken in Safari 12.12 / OS 10.12 Sierra

### ISSUE THREAD

**Issue by EdithAllison** [elementor/elementor#21406]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When accessing the Elementor site on Safari 12.12 / OS 10.12 Sierra the menu dropdown does not load, neither do popups.

### Steps to reproduce

To reproduce, you'd need to:
1. Have Safari 12.12 / OS 10.12 Sierra
2. Visit any Elementor page with a dropdown or popup

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: mariadb.org binary distribution v10.6.10
	PHP Version: 8.1.16
	PHP Memory Limit: -1
	PHP Max Input Vars: 5000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://www.schoolofsound.co.uk
	Home URL: https://www.schoolofsound.co.uk
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 512M
	Max Memory limit: -1
	Permalink Structure: /%postname%/
	Language: en-GB
	Timezone: Europe/London
	Admin Email: sos@schoolofsound.co.uk
	Debug Mode: Inactive

== Theme ==
	Name: The School of Sound
	Version: 4.1.3.1663595029
	Author: Automattic
	Child Theme: Yes
	Parent Theme Name: Storefront
	Parent Theme Version: 4.2.0
	Parent Theme Author: Automattic

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/110.0

== Active Plugins ==
	Advanced Custom Fields
		Version: 6.0.7
		Author: WP Engine

	Akismet Anti-Spam
		Version: 5.0.2
		Author: Automattic

	Complianz | GDPR/CCPA Cookie Consent
		Version: 6.4.1
		Author: Really Simple Plugins

	Duplicate Page
		Version: 4.5.1
		Author: mndpsingh287

	Elementor
		Version: 3.11.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.11.1
		Author: Elementor.com

	EmbedPress
		Version: 3.6.6
		Author: WPDeveloper

	Event Tickets
		Version: 5.5.7
		Author: The Events Calendar

	Event Tickets Extension: Promoter WP Admin Integration
		Version: 1.0.0
		Author: Modern Tribe, Inc.

	Event Tickets Plus
		Version: 5.6.6.1
		Author: The Events Calendar

	FluentSMTP
		Version: 2.2.4
		Author: FluentSMTP & WPManageNinja Team

	Loco Translate
		Version: 2.6.3
		Author: Tim Whitlock

	PDF Invoices & Packing Slips for WooCommerce
		Version: 3.3.2
		Author: WP Overnight

	Pods - Custom Content Types and Fields
		Version: 2.9.11.1
		Author: Pods Framework Team

	Redirection
		Version: 5.3.9
		Author: John Godley

	SearchWP
		Version: 4.2.9
		Author: SearchWP

	SearchWP Metrics
		Version: 1.4.3
		Author: SearchWP

	SearchWP WooCommerce Integration
		Version: 1.3.11
		Author: SearchWP

	Sequential Order Numbers for WooCommerce
		Version: 1.5.0
		Author: WebToffee

	Smart Slider 3
		Version: 3.5.1.13
		Author: Nextend

	SOS Modifications
		Version: 1.0.0
		Author: Edith Allison

	The Events Calendar
		Version: 6.0.9
		Author: The Events Calendar

	The Events Calendar: Virtual Events
		Version: 1.13.5
		Author: The Events Calendar

	The Events Calendar PRO
		Version: 6.0.8
		Author: The Events Calendar

	UpdraftPlus - Backup/Restore
		Version: 1.22.24
		Author: UpdraftPlus.Com, DavidAnderson

	Wonder PDF Embed
		Version: 2.7
		Author: Magic Hills Pty Ltd

	WooCommerce
		Version: 7.4.0
		Author: Automattic

	WooCommerce EU/UK VAT Compliance (Premium)
		Version: 1.27.21
		Author: David Anderson

	WooCommerce Google Analytics Integration
		Version: 1.6.1
		Author: WooCommerce

	WooCommerce Stripe Gateway
		Version: 7.1.0
		Author: WooCommerce

	Wordfence Security
		Version: 7.9.0
		Author: Wordfence

	WP Migrate
		Version: 2.6.1
		Author: WP Engine

	WP Rocket
		Version: 3.12.5.3
		Author: WP Media

	Yoast SEO
		Version: 20.1
		Author: Team Yoast


== Must-Use Plugins ==
	WP Migrate Compatibility
		Version: 1.3
		Author: Delicious Brains


== Features ==
	Custom Fonts: 1
	Custom Icons: 0

== Integrations ==
	
	woocommerce: Active


== Elementor Experiments ==
	Optimised DOM Output: Active by default
	Improved asset loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility improvements: Active by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Inactive by default
	Default to New Theme Builder: Active by default
	Editor V2: Inactive by default
	Landing pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default
	Save as Default: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Mega Menu: Inactive by default


== Log ==
	
JS: showing 20 of 31JS: 2023-02-16 17:14:47 [error X 1][https://www.schoolofsound.co.uk/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:40864] can't assign to property "guid" on "c14632widgetsticky": not an object 
JS: 2023-02-16 17:14:47 [error X 1][https://www.schoolofsound.co.uk/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:40864] can't assign to property "guid" on "c14642widgetsticky": not an object 
JS: 2023-02-16 17:14:47 [error X 1][https://www.schoolofsound.co.uk/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:40864] can't assign to property "guid" on "c14645widgetsticky": not an object 
JS: 2023-02-16 17:14:47 [error X 1][https://www.schoolofsound.co.uk/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:40864] can't assign to property "guid" on "c14648widgetsticky": not an object 
JS: 2023-02-16 17:14:47 [error X 1][https://www.schoolofsound.co.uk/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:40864] can't assign to property "guid" on "c14651widgetsticky": not an object 
JS: 2023-02-16 17:14:47 [error X 1][https://www.schoolofsound.co.uk/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:40864] can't assign to property "guid" on "c14660widgetsticky": not an object 
JS: 2023-02-16 17:14:47 [error X 1][https://www.schoolofsound.co.uk/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:40864] can't assign to property "guid" on "c14663widgetsticky": not an object 
JS: 2023-02-16 17:14:47 [error X 1][https://www.schoolofsound.co.uk/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:40864] can't assign to property "guid" on "c14666widgetsticky": not an object 
JS: 2023-02-16 17:14:47 [error X 1][https://www.schoolofsound.co.uk/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:40864] can't assign to property "guid" on "c14669widgetsticky": not an object 
JS: 2023-02-16 17:14:47 [error X 1][https://www.schoolofsound.co.uk/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:40864] can't assign to property "guid" on "c14678widgetsticky": not an object 
JS: 2023-02-16 17:14:47 [error X 1][https://www.schoolofsound.co.uk/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:40864] can't assign to property "guid" on "c14681widgetsticky": not an object 
JS: 2023-02-16 17:14:47 [error X 1][https://www.schoolofsound.co.uk/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:40864] can't assign to property "guid" on "c14684widgetsticky": not an object 
JS: 2023-02-16 17:14:47 [error X 1][https://www.schoolofsound.co.uk/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:40864] can't assign to property "guid" on "c14687widgetsticky": not an object 
JS: 2023-02-16 17:14:47 [error X 1][https://www.schoolofsound.co.uk/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:40864] can't assign to property "guid" on "c14697widgetsticky": not an object 
JS: 2023-02-16 17:14:47 [error X 1][https://www.schoolofsound.co.uk/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:40864] can't assign to property "guid" on "c14700widgetsticky": not an object 
JS: 2023-02-16 19:10:49 [error X 3][https://www.schoolofsound.co.uk/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:51816] a is undefined 
JS: 2023-02-16 19:52:54 [error X 1][https://www.schoolofsound.co.uk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.11.1:3:1087289] $ is null 
JS: 2023-02-16 19:53:29 [error X 8][https://www.schoolofsound.co.uk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.11.1:3:791626] this.store.find(...) is undefined 
JS: 2023-02-16 21:23:44 [error X 1][https://www.schoolofsound.co.uk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.11.1:3:907712] $e.routes.getHistory(...).reverse()[0] is undefined 
JS: 2023-02-17 16:27:17 [error X 2][https://www.schoolofsound.co.uk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.11.1:3:670939] this.model.isValidChild is not a function 

PHP: showing 11 of 11PHP: 2023-02-16 17:22:07 [notice X 488][/homepages/14/d159824172/htdocs/wp-content/plugins/elementor-pro/core/database/model-base.php::135] Return type of ElementorPro\Core\Database\Model_Base::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: /homepages/14/d159824172/htdocs/wp-content/plugins/elementor-pro/core/database/model-base.php(10): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /homepages/14/d159824172/htdocs/wp-content/plugins/elementor-pro/plugin.php(159): class type include()array (
  0 => '/homepages/14/d159824172/htdocs/wp-content/plugins/elementor-pro/core/database/model-base.php',
)
#2: /homepages/14/d159824172/htdocs/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php(18): ElementorPro\Plugin -> autoload()
#3: /homepages/14/d159824172/htdocs/wp-content/plugins/elementor-pro/plugin.php(159): class type include()array (
  0 => '/homepages/14/d159824172/htdocs/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php',
)
#4: /homepages/14/d159824172/htdocs/wp-content/plugins/elementor-pro/modules/notes/data/controller.php(243): ElementorPro\Plugin -> autoload()
',
)]
PHP: 2023-02-16 17:23:31 [notice X 22][/homepages/14/d159824172/htdocs/wp-content/plugins/elementor-pro/core/utils/collection.php::75] Return type of ElementorPro\Core\Utils\Collection::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-16 17:47:11 [notice X 3][/homepages/14/d159824172/htdocs/wp-content/plugins/elementor-pro/core/utils/collection.php::75] Return type of ElementorPro\Core\Utils\Collection::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: /homepages/14/d159824172/htdocs/wp-content/plugins/elementor-pro/core/utils/collection.php(11): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /homepages/14/d159824172/htdocs/wp-content/plugins/elementor-pro/plugin.php(159): class type include()array (
  0 => '/homepages/14/d159824172/htdocs/wp-content/plugins/elementor-pro/core/utils/collection.php',
)
#2: /homepages/14/d159824172/htdocs/wp-content/plugins/elementor-pro/core/database/query-builder.php(1222): ElementorPro\Plugin -> autoload()
#3: /homepages/14/d159824172/htdocs/wp-content/plugins/elementor-pro/core/database/query-builder.php(1081): ElementorPro\Core\Database\Query_Builder -> get_bindings()
#4: /homepages/14/d159824172/htdocs/wp-content/plugins/elementor-pro/core/database/model-query-builder.php(89): ElementorPro\Core\Database\Query_Builder -> get()
',
)]
PHP: 2023-02-16 18:19:05 [notice X 86][/homepages/14/d159824172/htdocs/wp-content/plugins/elementor-pro/modules/loop-builder/module.php::200] strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-16 19:52:07 [notice X 25][/homepages/14/d159824172/htdocs/wp-content/plugins/elementor-pro/modules/loop-builder/module.php::200] strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /homepages/14/d159824172/htdocs/wp-content/plugins/elementor-pro/modules/loop-builder/module.php(200): class type strpos()
#2: /homepages/14/d159824172/htdocs/wp-content/plugins/elementor-pro/modules/loop-builder/module.php(212): ElementorPro\Modules\LoopBuilder\Module -> is_editing_existing_loop_item()
#3: /homepages/14/d159824172/htdocs/wp-content/plugins/elementor-pro/modules/loop-builder/module.php(60): ElementorPro\Modules\LoopBuilder\Module -> is_loop_theme_builder()
#4: /homepages/14/d159824172/htdocs/wp-content/plugins/elementor-pro/modules/loop-builder/documents/loop.php(386): ElementorPro\Modules\LoopBuilder\Module -> __construct()
',
)]
PHP: 2023-02-16 19:52:07 [notice X 25][/homepages/14/d159824172/htdocs/wp-content/plugins/elementor-pro/modules/loop-builder/module.php::200] strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /homepages/14/d159824172/htdocs/wp-content/plugins/elementor-pro/modules/loop-builder/module.php(200): class type strpos()
#2: /homepages/14/d159824172/htdocs/wp-content/plugins/elementor-pro/modules/loop-builder/module.php(212): ElementorPro\Modules\LoopBuilder\Module -> is_editing_existing_loop_item()
#3: /homepages/14/d159824172/htdocs/wp-content/plugins/elementor-pro/modules/loop-builder/module.php(60): ElementorPro\Modules\LoopBuilder\Module -> is_loop_theme_builder()
#4: /homepages/14/d159824172/htdocs/wp-content/plugins/elementor-pro/modules/loop-builder/documents/loop.php(308): ElementorPro\Modules\LoopBuilder\Module -> __construct()
',
)]
PHP: 2023-02-16 19:52:13 [error X 2][/homepages/14/d159824172/htdocs/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::295] Uncaught Error: Call to a member function update_meta() on bool in /homepages/14/d159824172/htdocs/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:295
Stack trace:
#0 /homepages/14/d159824172/htdocs/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(168): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /homepages/14/d159824172/htdocs/wp-content/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /homepages/14/d159824172/htdocs/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /homepages/14/d159824172/htdocs/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#5 /homepages/14/d159824172/htdocs/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /homepages/14/d159824172/htdocs/wp-admin/admin-ajax.php(188): do_action('wp_ajax_element...')
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-16 19:56:26 [warning X 5][/homepages/14/d159824172/htdocs/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::168] Undefined array key "editor_post_id" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-16 20:27:41 [warning X 5][/homepages/14/d159824172/htdocs/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-16 21:09:32 [notice X 1][/homepages/14/d159824172/htdocs/wp-content/plugins/elementor-pro/modules/woocommerce/module.php::562] parse_str(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-16 21:23:15 [warning X 18][/homepages/14/d159824172/htdocs/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key "condition_type" [array (
  'trace' => '
#0: /homepages/14/d159824172/htdocs/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /homepages/14/d159824172/htdocs/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /homepages/14/d159824172/htdocs/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /homepages/14/d159824172/htdocs/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==
	

				
````
</details>

**Comment by mcxjc** [comment]
I'm also facing this issue. Any workaround? My client sites menu all doesn't have dropdown

**Comment by nicholaszein** [comment]
Hello, there! 

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
- Elementor only supports Safari versions down to v14 (iOS, iPadOS, and MacOS).

Please refer to the [System Requirements](https://elementor.com/help/requirements/) documentation.

### 👍 For now, that's all we can help with. 

If you think this is still an issue caused by Elementor, please feel free to open a new 🐞 [Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml).

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
