### ISSUE TITLE
⛔ 🐞 Bug Report: Import Kit doesn't change the template ID for the Loop Grid widget

### ISSUE THREAD

**Issue by vladninja** [elementor/elementor#21404]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When I export a Kit which uses Loop Grid widget on any page and next import the kit to the clear WP page imports with the Loop Grid widget, but template for loop grid not selected.

I compared an original post and imported post and it's looks like the template_id param is not changed and no more exist in imported WP.

Original settings
```
{
                "id": "288b311c",
                "elType": "widget",
                "settings": {
                  "template_id": "4130",
                  "posts_per_page": 999,
                  "post_query_post_type": "works",
                  "pagination_page_limit": "5",
                  "pagination_prev_label": "Previous",
                  "pagination_next_label": "Next",
                  "text": "Load More",
                  "load_more_no_posts_custom_message": "No more posts to show",
                  "abx_options": [
                    "artist-works"
                  ]
                },
                "elements": [],
                "widgetType": "loop-grid"
              }
```

Imported:
```
{
                "id": "6bf95048",
                "elType": "widget",
                "settings": {
                  "template_id": "4130",
                  "posts_per_page": 999,
                  "post_query_post_type": "works",
                  "pagination_page_limit": "5",
                  "pagination_prev_label": "Previous",
                  "pagination_next_label": "Next",
                  "text": "Load More",
                  "load_more_no_posts_custom_message": "No more posts to show",
                  "abx_options": [
                    "artist-works"
                  ]
                },
                "elements": [],
                "widgetType": "loop-grid"
              }
```

as you can see, the id param changed, but not template_id which is a ID of the post with the element template.
In the imported version, the correct ID  is 557, so this is the reason that not working.

### Steps to reproduce

1. Create some page which uses Loop grid with some Loop element template
2. Export Kit
3. Import kit to another WP
4. Element loop will be added in Theme builder, but in the page in which Loop grid was used the field related to the template of loop item is empty. FE page with loop grid item also empty.
![image](https://user-images.githubusercontent.com/76119088/220148271-dde53c20-c4b7-473a-8d03-7897902ce56b.png)

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info
<details>
<summary>System Info</summary>

````txt
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.54 (Debian)
	MySQL version: MySQL Community Server - GPL v8.0.31
	PHP Version: 7.4.33
	PHP Memory Limit: 
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: No
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: http://localhost:8083
	Home URL: http://localhost:8083
	WP Multisite: No
	Max Upload Size: 2 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: pl-PL
	Timezone: Europe/Warsaw
	Admin Email: xojeba6362@0pppp.com
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: pl_PL
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36

== Active Plugins ==

	Elementor
		Version: 3.10.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.10.2
		Author: Elementor.com

	Polylang
		Version: 3.3.1
		Author: WP SYNTEX

	Polylang Connect for Elementor
		Version: 2.3.5
		Author: Creame


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Landing Pages: Active by default
	Nested Elements: Active
	Lazy Load Background Images: Inactive by default
	Save as Default: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active by default
	Loop Carousel: Inactive by default
	Form Submissions: Active by default
	Scroll Snap: Active by default


== Log ==
	
PHP: showing 5 of 5PHP: 2023-02-15 12:01:58 [notice X 9][/var/www/html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::172] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-15 12:02:02 [notice X 8][/var/www/html/wp-content/plugins/elementor-pro/core/app/modules/import-export/runners/import/templates.php::103] Undefined index: conditions [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-15 12:02:03 [notice X 16][/var/www/html/wp-content/plugins/elementor/core/base/document.php::1563] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-15 12:02:59 [notice X 36][/var/www/html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined index: condition_type [array (
  'trace' => '
#0: /var/www/html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /var/www/html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /var/www/html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /var/www/html/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2023-02-15 12:03:28 [error X 1][/var/www/html/wp-content/plugins/elementor/core/frontend/render-modes/render-mode-base.php::88] Uncaught Error: Call to a member function is_editable_by_current_user() on bool in /var/www/html/wp-content/plugins/elementor/core/frontend/render-modes/render-mode-base.php:88
Stack trace:
#0 /var/www/html/wp-content/plugins/elementor/core/frontend/render-mode-manager.php(133): Elementor\Core\Frontend\RenderModes\Render_Mode_Base->get_permissions_callback()
#1 /var/www/html/wp-content/plugins/elementor/core/frontend/render-mode-manager.php(157): Elementor\Core\Frontend\Render_Mode_Manager->add_current_actions()
#2 /var/www/html/wp-content/plugins/elementor/includes/frontend.php(194): Elementor\Core\Frontend\Render_Mode_Manager->__construct()
#3 /var/www/html/wp-includes/class-wp-hook.php(308): Elementor\Frontend->init_render_mode('')
#4 /var/www/html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#5 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /var/www/html/wp-includes/template-loader.php(13): do_action('template_redire...')
#7 /var/www/html/wp-blog-header. [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible
	Polylang Connect for Elementor: Compatible

== Elementor Pro - Compatibility Tag ==
	
	Polylang Connect for Elementor: Compatible
				
````
<details>

**Comment by nicholaszein** [comment]
Hello @vladninja,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
When exporting/importing templates, if there is a Loop Grid or Loop Carousel, you need to also export/import the Loop Item templates from your Theme Builder library, as they are separate templates.
Then you need to re-select them in your Loop Grid or Loop Carousel widgets, as they will have a different ID after imported. 

Currently unless you export entire Kits (not just single templates), Elementor does not include the Loop Item templates if there are Loop Grid or Loop Carousel widgets. 

### 👍 For now, that's all we can help with. 

If you think this should be a feature, please submit a new [🚀 Feature Request](https://github.com/elementor/elementor/discussions/new?category=feature-request), and we will consider it if there is enough demand from the community. 

Kind regards
