### ISSUE TITLE
In Loop Grid widget the items per page are wrong

### ISSUE THREAD

**Issue by sbikosfp** [elementor/elementor#21402]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

On Loop Grid widget when I set the Source Query to Current Query, the items per page are not correct. Right now on my website i set the items per page to 8 but it shows 10.

### Steps to reproduce

1) Add a new loop grid with a custom template on a custom post type
2) Set the items per page to 8 
3) Set the Source Query to Current Query

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

					
== Server Environment ==
	Operating System: FreeBSD
	Software: nginx/1.22.1
	MySQL version: Source distribution v8.0.31
	PHP Version: 8.1.16
	PHP Memory Limit: 256M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://melweb.wab.gr
	Home URL: https://melweb.wab.gr
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Europe/Athens
	Admin Email: sbikos@fourpillars.studio
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.6.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 6.0.7
		Author: WP Engine

	Custom Post Type UI
		Version: 1.13.4
		Author: WebDevStudios

	Elementor
		Version: 3.11.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.11.1
		Author: Elementor.com

	greeklish-permalinks
		Version: 3.3
		Author: Panagiotis Kontogiannis, elpak

	MouseWheel Smooth Scroll
		Version: 5.9
		Author: KubiQ

	Safe SVG
		Version: 2.0.3
		Author: 10up

	Search & Filter - Elementor Extension
		Version: 1.2.1
		Author: Code Amp

	Search & Filter Pro
		Version: 2.5.13
		Author: Code Amp

	UpdraftPlus - Backup/Restore
		Version: 2.22.25.26
		Author: UpdraftPlus.Com, DavidAnderson

	Wordfence Security
		Version: 7.9.0
		Author: Wordfence

== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Inactive by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active
	Editor V2: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Active
	Lazy Load Background Images: Active
	Save as Default: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Mega Menu: Inactive by default

== Log ==
	
Log: showing 20 of 252023-01-30 02:03:47 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.10.2',
  'to' => '3.10.3',
)]
2023-02-14 16:36:06 [info] elementor-pro::elementor_pro_updater Started 
2023-02-14 16:36:06 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-02-14 16:36:06 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-02-14 16:36:06 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.10.3',
  'to' => '3.11.0',
)]
2023-02-14 16:36:06 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.10.3',
  'to' => '3.11.0',
)]
2023-02-14 16:36:23 [info] elementor::elementor_updater Started 
2023-02-14 16:36:23 [info] Elementor/Upgrades - _on_each_version Start  
2023-02-14 16:36:23 [info] Elementor/Upgrades - _on_each_version Finished 
2023-02-14 16:36:23 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.2',
  'to' => '3.11.0',
)]
2023-02-16 15:04:15 [info] elementor::elementor_updater Started 
2023-02-16 15:04:15 [info] Elementor/Upgrades - _on_each_version Start  
2023-02-16 15:04:15 [info] Elementor/Upgrades - _on_each_version Finished 
2023-02-16 15:04:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.0',
  'to' => '3.11.1',
)]
2023-02-16 15:04:15 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.0',
  'to' => '3.11.1',
)]
2023-02-16 15:04:19 [info] elementor-pro::elementor_pro_updater Started 
2023-02-16 15:04:19 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-02-16 15:04:19 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-02-16 15:04:19 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.0',
  'to' => '3.11.1',
)]
2023-02-16 15:04:19 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.0',
  'to' => '3.11.1',
)]

PHP: showing 14 of 14PHP: 2023-01-30 02:03:57 [notice X 1193][/home/www/pestrofa/wab.gr/melweb/wp-content/plugins/elementor-pro/core/database/model-base.php::135] Return type of ElementorPro\Core\Database\Model_Base::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: /home/www/pestrofa/wab.gr/melweb/wp-content/plugins/elementor-pro/core/database/model-base.php(10): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/www/pestrofa/wab.gr/melweb/wp-content/plugins/elementor-pro/plugin.php(159): class type include()array (
  0 => '/home/www/pestrofa/wab.gr/melweb/wp-content/plugins/elementor-pro/core/database/model-base.php',
)
#2: /home/www/pestrofa/wab.gr/melweb/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php(18): ElementorPro\Plugin -> autoload()
#3: /home/www/pestrofa/wab.gr/melweb/wp-content/plugins/elementor-pro/plugin.php(159): class type include()array (
  0 => '/home/www/pestrofa/wab.gr/melweb/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php',
)
#4: /home/www/pestrofa/wab.gr/melweb/wp-content/plugins/elementor-pro/modules/notes/data/controller.php(243): ElementorPro\Plugin -> autoload()
',
)]
PHP: 2023-01-31 18:31:25 [error X 2][/home/www/pestrofa/wab.gr/melweb/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::295] Uncaught Error: Call to a member function update_meta() on null in /home/www/pestrofa/wab.gr/melweb/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:295
Stack trace:
#0 /home/www/pestrofa/wab.gr/melweb/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(168): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(1234, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/www/pestrofa/wab.gr/melweb/wp-content/plugins/elementor/core/common/modules/ajax/module.php(172): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/www/pestrofa/wab.gr/melweb/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/www/pestrofa/wab.gr/melweb/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#5 /home/www/pestrofa/wab.gr/melweb/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /home/www/pestrofa/wab.gr/melweb/wp-admin/admin-ajax.php(188): do_action('wp_ajax_element...')
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-31 18:31:37 [notice X 3086][/home/www/pestrofa/wab.gr/melweb/wp-content/plugins/elementor-pro/core/utils/collection.php::75] Return type of ElementorPro\Core\Utils\Collection::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-14 16:36:06 [notice X 8129][/home/www/pestrofa/wab.gr/melweb/wp-content/plugins/elementor-pro/modules/loop-builder/module.php::210] strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-15 14:01:57 [error X 1][/home/www/pestrofa/wab.gr/melweb/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::295] Uncaught Error: Call to a member function update_meta() on null in /home/www/pestrofa/wab.gr/melweb/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:295
Stack trace:
#0 /home/www/pestrofa/wab.gr/melweb/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(168): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(1234, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/www/pestrofa/wab.gr/melweb/wp-content/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/www/pestrofa/wab.gr/melweb/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/www/pestrofa/wab.gr/melweb/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#5 /home/www/pestrofa/wab.gr/melweb/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /home/www/pestrofa/wab.gr/melweb/wp-admin/admin-ajax.php(188): do_action('wp_ajax_element...')
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-16 15:06:30 [notice X 4][/home/www/pestrofa/wab.gr/melweb/wp-content/plugins/elementor-pro/modules/custom-css/module.php::76] trim(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-16 15:34:09 [notice X 7][/home/www/pestrofa/wab.gr/melweb/wp-content/plugins/elementor-pro/core/database/model-base.php::135] Return type of ElementorPro\Core\Database\Model_Base::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-16 17:12:39 [warning X 1][/home/www/pestrofa/wab.gr/melweb/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-image.php::40] Undefined array key 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-16 17:12:43 [warning X 7][/home/www/pestrofa/wab.gr/melweb/wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-16 17:26:22 [warning X 3][/home/www/pestrofa/wab.gr/melweb/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-16 17:26:22 [notice X 15][/home/www/pestrofa/wab.gr/melweb/wp-content/plugins/elementor-pro/modules/loop-builder/module.php::200] strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/www/pestrofa/wab.gr/melweb/wp-content/plugins/elementor-pro/modules/loop-builder/module.php(200): class type strpos()
#2: /home/www/pestrofa/wab.gr/melweb/wp-content/plugins/elementor-pro/modules/loop-builder/module.php(212): ElementorPro\Modules\LoopBuilder\Module -> is_editing_existing_loop_item()
#3: /home/www/pestrofa/wab.gr/melweb/wp-content/plugins/elementor-pro/modules/loop-builder/module.php(60): ElementorPro\Modules\LoopBuilder\Module -> is_loop_theme_builder()
#4: /home/www/pestrofa/wab.gr/melweb/wp-content/plugins/elementor-pro/modules/loop-builder/documents/loop.php(386): ElementorPro\Modules\LoopBuilder\Module -> __construct()
',
)]
PHP: 2023-02-16 17:26:22 [notice X 15][/home/www/pestrofa/wab.gr/melweb/wp-content/plugins/elementor-pro/modules/loop-builder/module.php::200] strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/www/pestrofa/wab.gr/melweb/wp-content/plugins/elementor-pro/modules/loop-builder/module.php(200): class type strpos()
#2: /home/www/pestrofa/wab.gr/melweb/wp-content/plugins/elementor-pro/modules/loop-builder/module.php(212): ElementorPro\Modules\LoopBuilder\Module -> is_editing_existing_loop_item()
#3: /home/www/pestrofa/wab.gr/melweb/wp-content/plugins/elementor-pro/modules/loop-builder/module.php(60): ElementorPro\Modules\LoopBuilder\Module -> is_loop_theme_builder()
#4: /home/www/pestrofa/wab.gr/melweb/wp-content/plugins/elementor-pro/modules/loop-builder/documents/loop.php(308): ElementorPro\Modules\LoopBuilder\Module -> __construct()
',
)]
PHP: 2023-02-16 17:26:22 [warning X 15][/home/www/pestrofa/wab.gr/melweb/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key "condition_type" [array (
  'trace' => '
#0: /home/www/pestrofa/wab.gr/melweb/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /home/www/pestrofa/wab.gr/melweb/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /home/www/pestrofa/wab.gr/melweb/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /home/www/pestrofa/wab.gr/melweb/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2023-02-16 18:30:23 [warning X 1][/home/www/pestrofa/wab.gr/melweb/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::168] Undefined array key "editor_post_id" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 3 of 3JS: 2023-01-31 12:31:29 [error X 2][https://melweb.wab.gr/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.10.3:2:61404] Cannot convert undefined or null to object 
JS: 2023-02-10 22:27:08 [error X 98][https://melweb.wab.gr/wp-admin/load-scripts.php?c=0&loadchunk_0=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&loadchunk_1=hooks&ver=6.1.1:4:51824] Cannot read properties of undefined (reading 'replace') 
JS: 2023-02-16 14:30:43 [error X 18][https://melweb.wab.gr/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.11.1:3:791668] Cannot read properties of undefined (reading 'localized') 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible
	Search & Filter - Elementor Extension: Incompatible

== Elementor Pro - Compatibility Tag ==
	
	Search & Filter - Elementor Extension: Incompatible

**Comment by doronwolf** [comment]
Hi @sbikosfp - if you go to **_WP dashboard >  settings >  Reading Settings > Blog pages show at most..._** and change the value that is set in there, would that affect the number of items per page you see?

**Comment by sbikosfp** [comment]
hello @doronwolf - yes that fixed the issue. :) But shouldn't it be set from elementor settings inside the widget?

**Comment by doronwolf** [comment]
I agree this seems to be a conflict and we should address it, I will try to
keep you posted on our progress but can't tell you at the moment what is
the ETA of the solution


--
*Doron Wolf*
Elementor Expert

[image: elementor-sig-animation200x54-tiny.gif]
***@***.***


Follow Elementor on Facebook <https://www.facebook.com/elemntor/>  |
Twitter <https://twitter.com/elemntor>  |  YouTube
<https://www.youtube.com/c/elementor>

**Comment by nicholaszein** [comment]
Hello @sbikosfp! 

Thank you for submitting your issue! 🙏 

As @doronwolf mentioned, when you are editing Archive templates, what dictates the number of posts per page is what is defined in your WordPress **_Dashboard > Settings > Reading_** page.

This is more of a limitation of WordPress and how Archive Queries behave. This means it's something both very tricky and difficult to overcome without some compromise. We understand this might be something confusing, but we are trying to keep the default behavior of WordPress as much as we can. This helps with backward compatibility and also 3rd-party compatibility since any plugin can alter Archive Queries.

This is something we are going to investigate and check if we can address, but keep in mind that it's likely it will take a long time, and possibly has no other workaround than settings the number of pages in WordPress settings.

I hope this clarifies why this happens.

Best regards

**Comment by saqibjavaiddev** [comment]
> Hi @sbikosfp - if you go to **_WP dashboard > settings > Reading Settings > Blog pages show at most..._** and change the value that is set in there, would that affect the number of items per page you see?

I have same issue and tried this solution but not worked for products

**Comment by doronwolf** [comment]
Hi @saqibjavaiddev products archive are affected by woocommerce WordPress settings 
try to play with “Products per row“ and “Rows per page“ settings in the “WP Admin > Appearance > Customize > WooCommerce > Product Catalog” section.

**Comment by raffihakobyan** [comment]
Good afternoon, it looks like this problem is still relevant?

It is not possible to set different values ​​for different pages. It only works with the Goalball settings (Dashboard > Settings > Reading page)

**Comment by tomgacz** [comment]
> Good afternoon, it looks like this problem is still relevant?
> 
> It is not possible to set different values ​​for different pages. It only works with the Goalball settings (Dashboard > Settings > Reading page)

Set in wordpress settings and woocommerxe settings 999 posts and then in elementor loop grid set as You want
