### ISSUE TITLE
Wrong horizontal margins and border radius in the desktop Nav Menu widget dropdown submenus

### ISSUE THREAD

**Issue by NooNoorz** [elementor/elementor#21481]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi, I would like to report 2 issues regarding horizontal margins and border radius in the nav menu widget on the desktop view.

1) Horizontal margins in the dropdown menu: 
   - If a "menu-item-has-children" has just 1 level of dropdown menu:
      => Left margin is correct and takes the internal horizontal margin value specified in the left widget pane;
      => Right margin is always to 0 and never changes whatever value you enter. My understanding is it should work as the vertical margin does which is applied to top and bottom margins of each menu-item in the elementor-nav-menu--dropdown class.
    - If a menu-item-has-children has 2 levels of imbricated dropdowns:  
      => Horizontal left margin is not persistent on both dropdown menus : Parent dropdown has the correct left margin value, however, the child dropdown menu displays a left margin apparently twice the value of the parent dropdown.
      => Right margins remain at 0 in both dropdowns menus (parent and child)

2) Border radius
When specifying border radius values above 0 for the dropdown menu and menu-has-item has 2 levels of imbricated dropdown menus, 2 behaviors occur :
    - If the menu-item in the elementor-nav-menu--dropdown IS NOT the last menu-item: 
       => There is no radius issue for the child dropdown menu-items ;
    - If the menu-item in the elementor-nav-menu--dropdown IS the last menu-item 
       => Then Bottom and Left radius values for the FIRST menu-item of the child dropdown take the wrong values (the ones specified in the left pane) instead of using 0.

2 images to explain visually these issues are attached below. 
Thank you

![menu 1 bug](https://user-images.githubusercontent.com/126283199/221626595-76a902d4-6a9f-40e7-8f77-921ba257255e.jpg)

![menu2 bug](https://user-images.githubusercontent.com/126283199/221630339-a602f189-a5ae-4d47-a789-7af3f8a1c526.jpg)

### Steps to reproduce

1) In Menu (WP/Appearance) => Set a dropdown menu ;  In the navmenu: => With mouse, hover on a menu-item-has-children => 1st (parent) dropdown => Hover on a 2nd menu-item-has-children inside the dropdown => displays a 2nd (child) dropdown menu => You can see the margin differences 

2) In Menu (WP/Appearance)  => Make sure to have 2 imbricated dropdown with a menu-item with children in the first dropdown menu at the last position => In the nav menu:  Hover on a menu-item-has-children in the horizontal menu => Displays 1st (parent) dropdown => Hover on the last menu-item-has-children inside this dropdown => Displays a 2nd (child) dropdown menu, hover on the first menu-item. the radius issue shows up. 

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: nginx/1.20.2
	MySQL version: (Google) v8.0.26
	PHP Version: 7.4.33
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://www.HIDDEN-URL
	Home URL: https://www.HIDDEN-URL
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 512M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Europe/Paris
	Admin Email: HIDDEN
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: fr_FR
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36

== Active Plugins ==
	Burst Statistics - Privacy-Friendly Analytics for WordPress
		Version: 1.3.4
		Author: Really Simple Plugins

	Complianz - Terms and Conditions
		Version: 1.1.5
		Author: Really Simple Plugins

	Complianz | GDPR/CCPA Cookie Consent
		Version: 6.4.1
		Author: Really Simple Plugins

	Dynamic Visibility for Elementor
		Version: 5.0.4
		Author: Dynamic.ooo

	Elementor
		Version: 3.12.0-cloud2
		Author: Elementor.com

	Elementor Pro
		Version: 3.12.0-cloud2
		Author: Elementor.com

	Graphina - Elementor Charts and Graphs
		Version: 1.8.4
		Author: Iqonic Design

	Nextend Social Login
		Version: 3.1.7
		Author: Nextendweb

	Paid Memberships Pro
		Version: 2.10.1
		Author: Paid Memberships Pro

	Paid Memberships Pro - Mailchimp Add On
		Version: 2.3.2
		Author: Paid Memberships Pro

	Paid Memberships Pro - Roles Add On
		Version: 1.4.2
		Author: Paid Memberships Pro

	Royal Elementor Addons
		Version: 1.3.64
		Author: WP Royal

	Smush
		Version: 3.12.5
		Author: WPMU DEV

	Wordfence Security
		Version: 7.9.0
		Author: Wordfence

	WP Super Cache
		Version: 1.9.3
		Author: Automattic

	Yoast Duplicate Post
		Version: 4.5
		Author: Enrico Battocchi & Team Yoast

	Yoast SEO
		Version: 20.1
		Author: Team Yoast

== Elements Usage ==
	
	footer : 2
	header : 6
		button : 4
		nav-menu : 3
		social-icons : 2
		theme-site-logo : 3
	page : 11
		animated-headline : 4
		breadcrumbs : 2
		button : 40
		call-to-action : 20
		column_chart : 5
		container : 18
		counter : 4
		flip-box : 8
		form : 2
		heading : 190
		hotspot : 5
		icon : 5
		icon-box : 54
		icon-list : 2
		image : 66
		image-box : 4
		image-carousel : 1
		media-carousel : 5
		menu-anchor : 10
		nav-menu : 1
		shortcode : 1
		sidebar : 1
		slides : 4
		table-of-contents : 2
		text-editor : 192
		video : 1
		wpr-advanced-slider : 1
		wpr-back-to-top : 5
		wpr-button : 10
		wpr-content-toggle : 4
		wpr-feature-list : 1
		wpr-flip-box : 12
		wpr-mega-menu : 1
		wpr-posts-timeline : 3
	popup : 5
		button : 3
		login : 1
		shortcode : 3
		text-editor : 16
		theme-site-logo : 3
	section : 58
		animated-headline : 1
		blockquote : 1
		breadcrumbs : 1
		button : 15
		call-to-action : 6
		column_chart : 3
		flip-box : 32
		form : 2
		heading : 35
		icon : 1
		icon-box : 34
		image : 11
		image-box : 7
		login : 1
		menu-anchor : 1
		nav-menu : 5
		shortcode : 2
		slides : 5
		social-icons : 1
		table-of-contents : 1
		testimonial : 3
		text-editor : 56
		theme-site-logo : 4
		toggle : 2
		wpr-flip-box : 4
		wpr-posts-timeline : 2
	widget : 0
		breadcrumbs : 1
		button : 5
		nav-menu : 2
		social-icons : 1
	wp-post : 9
		button : 1
		shortcode : 1
		text-editor : 9
	wp-page : 31
		animated-headline : 2
		breadcrumbs : 4
		button : 17
		call-to-action : 2
		column_chart : 1
		container : 57
		counter : 4
		divider : 1
		flip-box : 9
		form : 3
		heading : 96
		hotspot : 1
		icon-box : 21
		icon-list : 7
		image : 30
		login : 1
		media-carousel : 3
		nav-menu : 2
		shortcode : 6
		slides : 4
		spacer : 3
		table-of-contents : 2
		tabs : 1
		text-editor : 113
		wpr-back-to-top : 1
		wpr-button : 9
		wpr-content-toggle : 1
		wpr-flip-box : 4
		wpr-posts-timeline : 1
	single-page : 1
		form : 1
		heading : 9
		shortcode : 1
		text-editor : 16
	search-results : 1
		heading : 3
		posts : 1
		search-form : 1
		text-editor : 1

== Settings ==
	
	cpt_support: post, page, wpr_templates, wpr_mega_menu
	disable_color_schemes: yes
	disable_typography_schemes: yes
	allow_tracking: yes
	editor_break_lines: 1
	unfiltered_files_upload: 1
	load_fa4_shim: yes

== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	

== Elementor Experiments ==
	Optimized DOM Output: Inactive
	Improved Asset Loading: Inactive
	Improved CSS Loading: Inactive
	Inline Font Icons: Inactive
	Accessibility Improvements: Inactive
	Additional Custom Breakpoints: Inactive
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Inactive by default
	Default to New Theme Builder: Inactive
	Hello Theme Header & Footer: Inactive
	Editor V2: Inactive by default
	Landing Pages: Inactive
	Nested Elements: Active
	Lazy Load Background Images: Inactive by default
	Save as Default: Active by default
	Improved Page Actions Layout: Inactive by default
	Page Transitions: Active
	Notes: Inactive
	Loop: Active by default
	Alternate Template: Inactive by default
	Form Submissions: Active
	Scroll Snap: Inactive
	Mega Menu: Inactive by default

== Log ==
	
Log: showing 20 of 232023-01-24 00:51:43 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.0-cloud1',
  'to' => '3.11.0-cloud1',
)]
2023-02-08 02:13:15 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.0-cloud1',
  'to' => '3.12.0-cloud1',
)]
2023-02-08 02:13:16 [info] elementor::elementor_updater Started 
2023-02-08 02:13:16 [info] Elementor/Upgrades - _on_each_version Start  
2023-02-08 02:13:21 [info] Elementor/Upgrades - _on_each_version Finished 
2023-02-08 02:13:21 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.0-cloud1',
  'to' => '3.12.0-cloud1',
)]
2023-02-08 02:13:39 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.0-cloud1',
  'to' => '3.12.0-cloud1',
)]
2023-02-08 02:13:59 [info] elementor-pro::elementor_pro_updater Started 
2023-02-08 02:13:59 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-02-08 02:13:59 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-02-08 02:13:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.0-cloud1',
  'to' => '3.12.0-cloud1',
)]
2023-02-26 05:13:48 [info] elementor-pro::elementor_pro_updater Started 
2023-02-26 05:13:48 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-02-26 05:13:48 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-02-26 05:13:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.0-cloud1',
  'to' => '3.12.0-cloud2',
)]
2023-02-26 05:13:56 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.0-cloud1',
  'to' => '3.12.0-cloud2',
)]
2023-02-26 05:13:56 [info] elementor::elementor_updater Started 
2023-02-26 05:13:56 [info] Elementor/Upgrades - _on_each_version Start  
2023-02-26 05:14:00 [info] Elementor/Upgrades - _on_each_version Finished 
2023-02-26 05:14:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.0-cloud1',
  'to' => '3.12.0-cloud2',
)]

PHP: showing 9 of 9PHP: 2023-01-26 11:59:27 [notice X 21][/mnt/customers-2/customers-el-3785792-29847-HIDDEN-URL-wordpress-pvc-629767a0e2f67900206d3eb4/wp-content/wp-content/plugins/elementor/app/modules/import-export/module.php::639] Trying to get property &#039;label&#039; of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-07 23:13:14 [error X 1][/mnt/customers-2/customers-el-3785792-29847-HIDDEN-URL-wordpress-pvc-629767a0e2f67900206d3eb4/wp-content/wp-content/plugins/elementor/core/settings/manager.php::152] Uncaught Error: Call to a member function get_tabs_controls() on null in /mnt/customers-2/customers-el-3785792-29847-HIDDEN-URL-wordpress-pvc-629767a0e2f67900206d3eb4/wp-content/wp-content/plugins/elementor/core/settings/manager.php:152
Stack trace:
#0 /mnt/customers-2/customers-el-3785792-29847-HIDDEN-URL-wordpress-pvc-629767a0e2f67900206d3eb4/wp-content/wp-content/plugins/elementor/core/base/document.php(591): Elementor\Core\Settings\Manager::get_settings_managers_config()
#1 /mnt/customers-2/customers-el-3785792-29847-HIDDEN-URL-wordpress-pvc-629767a0e2f67900206d3eb4/wp-content/wp-content/plugins/elementor/modules/library/documents/library-document.php(66): Elementor\Core\Base\Document-&gt;get_initial_config()
#2 /mnt/customers-2/customers-el-3785792-29847-HIDDEN-URL-wordpress-pvc-629767a0e2f67900206d3eb4/wp-content/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(666): Elementor\Modules\Library\Documents\Library_Document-&gt;get_initial_config()
#3 /mnt/customers-2/custome [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-09 03:08:22 [error X 2][/mnt/customers-2/customers-el-3785792-29847-HIDDEN-URL-wordpress-pvc-629767a0e2f67900206d3eb4/wp-content/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::295] Uncaught Error: Call to a member function update_meta() on bool in /mnt/customers-2/customers-el-3785792-29847-HIDDEN-URL-wordpress-pvc-629767a0e2f67900206d3eb4/wp-content/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:295
Stack trace:
#0 /mnt/customers-2/customers-el-3785792-29847-HIDDEN-URL-wordpress-pvc-629767a0e2f67900206d3eb4/wp-content/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(168): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;ajax_save_theme_template_conditions()
#2 /mnt/customers-2/customers-el-3785792-29847-HIDDEN-URL-wordpress-pvc-629767a0e2f67900206d3eb4/wp-content/wp-content/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func()
#3 /mnt/customers-2/customers-el-3785792-29847-HIDDEN-URL-wordpress-pvc-629767a0e2f67900206d3eb4/wp-content/wp-includes/class-wp-hook.php(308): E [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-13 20:40:26 [error X 1][/mnt/customers-2/customers-el-3785792-29847-HIDDEN-URL-wordpress-pvc-629767a0e2f67900206d3eb4/wp-content/wp-content/plugins/elementor/includes/template-library/sources/local.php::1080] Uncaught TypeError: Argument 2 passed to Elementor\TemplateLibrary\Source_Local::on_save_post() must be an instance of WP_Post, instance of stdClass given, called in /mnt/customers-2/customers-el-3785792-29847-HIDDEN-URL-wordpress-pvc-629767a0e2f67900206d3eb4/wp-content/wp-includes/class-wp-hook.php on line 310 and defined in /mnt/customers-2/customers-el-3785792-29847-HIDDEN-URL-wordpress-pvc-629767a0e2f67900206d3eb4/wp-content/wp-content/plugins/elementor/includes/template-library/sources/local.php:1080
Stack trace:
#0 /mnt/customers-2/customers-el-3785792-29847-HIDDEN-URL-wordpress-pvc-629767a0e2f67900206d3eb4/wp-content/wp-includes/class-wp-hook.php(310): Elementor\TemplateLibrary\Source_Local-&gt;on_save_post()
#1 /mnt/customers-2/customers-el-3785792-29847-HIDDEN-URL-wordpress-pvc-629767a0e2f67900206d3eb4/wp-content/wp-includes/class-wp-hook.php(332): WP_Hook-&gt;apply_filters()
#2 /mnt/customers-2/customers-el-3785792-29847-HIDDEN-URL-wordpress-pvc-629767a0e2f67900206d3eb4/wp-content/wp-includes/plugin. [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-14 02:55:29 [notice X 16][/mnt/customers-2/customers-el-3785792-29847-HIDDEN-URL-wordpress-pvc-629767a0e2f67900206d3eb4/wp-content/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-14 04:49:32 [notice X 3][/mnt/customers-2/customers-el-3785792-29847-HIDDEN-URL-wordpress-pvc-629767a0e2f67900206d3eb4/wp-content/wp-content/plugins/elementor/includes/utils.php::498] Array to string conversion [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-19 14:23:00 [warning X 1][/mnt/customers-2/customers-el-3785792-29847-HIDDEN-URL-wordpress-pvc-629767a0e2f67900206d3eb4/wp-content/wp-content/plugins/elementor/core/files/base.php::203] unlink(/mnt/customers-2/customers-el-3785792-29847-HIDDEN-URL-wordpress-pvc-629767a0e2f67900206d3eb4/wp-content/wp-content/uploads/elementor/css/post-8350.css): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-21 22:13:25 [notice X 1][/mnt/customers-2/customers-el-3785792-29847-HIDDEN-URL-wordpress-pvc-629767a0e2f67900206d3eb4/wp-content/wp-content/plugins/elementor/includes/widgets/video.php::1095] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-26 16:08:55 [notice X 15][/mnt/customers-2/customers-el-3785792-29847-HIDDEN-URL-wordpress-pvc-629767a0e2f67900206d3eb4/wp-content/wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 10 of 10JS: 2023-01-27 13:34:06 [error X 24][https://HIDDEN-URL.elementor.cloud/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.11.0-cloud1:3:1081296] Cannot read properties of null (reading &#039;getBoundingClientRect&#039;) 
JS: 2023-01-27 18:13:42 [error X 54][https://www.gstatic.com/recaptcha/releases/RGRQD9tdxHtnt-Bxkx9pM75S/recaptcha__fr.js:258:4] reCAPTCHA has already been rendered in this element 
JS: 2023-01-28 18:31:16 [error X 71][https://HIDDEN-URL.elementor.cloud/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:51824] Cannot read properties of undefined (reading &#039;replace&#039;) 
JS: 2023-01-28 19:20:06 [error X 17][https://HIDDEN-URL.elementor.cloud/wp-content/plugins/elementor/assets/js/common-modules.min.js?ver=3.11.0-cloud1:2:53736] Model.isValidChild() should be implemented, please provide &#039;isValidChild&#039; functionality. 
JS: 2023-02-07 23:08:12 [error X 3][https://HIDDEN-URL.elementor.cloud/wp-content/plugins/elementor/assets/js/new-template.min.js?ver=3.11.0-cloud1:2:2932] elementor_new_template_form_controls is not defined 
JS: 2023-02-13 23:54:58 [error X 1][https://HIDDEN-URL.elementor.cloud/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.12.0-cloud1:3:658274] elementorFrontend.elements.window.jQuery is not a function 
JS: 2023-02-14 03:35:37 [error X 4][https://HIDDEN-URL.elementor.cloud/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.12.0-cloud1:2:61404] Cannot convert undefined or null to object 
JS: 2023-02-18 00:55:42 [error X 2][https://HIDDEN-URL.elementor.cloud/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.12.0-cloud1:3:594233] Cannot read properties of null (reading &#039;id&#039;) 
JS: 2023-02-19 03:02:02 [error X 1][https://HIDDEN-URL.elementor.cloud/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.12.0-cloud1:3:793258] Cannot read properties of undefined (reading &#039;toLowerCase&#039;) 
JS: 2023-02-23 12:16:33 [error X 3][https://HIDDEN-URL.elementor.cloud/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.12.0-cloud1:3:877806] Cannot read properties of undefined (reading &#039;val&#039;) 

== Elementor - Compatibility Tag ==
	
	Dynamic Visibility for Elementor: Compatibility not specified
	Elementor Pro: Compatibility not specified
	Graphina - Elementor Charts and Graphs: Compatibility not specified
	Royal Elementor Addons: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @NooNoorz! 

Thank you for submitting your issue! 🙏 

Please allow us some time to investigate it, and get back to you with our findings. 🧐 

Best regards
