### ISSUE TITLE
Fatal error when saving post template

### ISSUE THREAD

**Issue by Mulli** [elementor/elementor#21536]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Upon saving post template Fatal Error:
`PHP Fatal error:  Uncaught TypeError: Argument 2 passed to ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Cache::add() must be of the type array, string given, called in C:\Users\USER\Local Sites\delet\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-cache.php on line 135 and defined in C:\Users\USER\Local Sites\delet\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-cache.php:29
Stack trace:
#0 C:\Users\USER\Local Sites\delet\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-cache.php(135): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Cache->add(Object(ElementorPro\Modules\ThemeBuilder\Documents\Single_Post), '1')
#1 C:\Users\USER\Local Sites\delet\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-manager.php(298): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Cache->regenerate()
#2 C:\Users\USER\Local Sites\delet\app\public\wp-content\plugins\elementor-pro\modules\t in C:\Users\USER\Local Sites\delet\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-cache.php on line 29
`

### Steps to reproduce

1. Generate post template with a Form on 1 or 2 fields
2. Set the default values to initialize from the post ACF fields
3. SAVE
BOOM, fata error occur

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

					
== Server Environment ==
	Operating System: WINNT
	Software: nginx/1.16.0
	MySQL version: MySQL Community Server - GPL v8.0.16
	PHP Version: 7.4.3
	PHP Memory Limit: 1024M
	PHP Max Input Vars: 4000
	PHP Max Post Size: 1000M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://delet.local
	Home URL: https://delet.local
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 4096
	Max Memory limit: 4096
	Permalink Structure: /%postname%/
	Language: he-IL
	Timezone: Asia/Jerusalem
	Admin Email: mulli@site2goal.co.il
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.6.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: he_IL
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36

== Active Plugins ==
	ACF to REST API
		Version: 3.3.3
		Author: Aires Gonçalves

	Advanced Custom Fields PRO
		Version: 6.0.7
		Author: WP Engine

	Digma MBO - Family Management
		Version: 0.9.1
		Author: Mulli

	Elementor
		Version: 3.11.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.11.3
		Author: Elementor.com

	JWT Authentication for WP-API, DigmaTec version
		Version: 1.2.7 - Mulli's
		Author: Mulli Bahr fixes (Orig: Enrique Chavez, https://enriquechavez.co)

== שימוש באלמנטים ==
	
	footer : 1
		heading : 1
		image : 2
	header : 1
		heading : 1
	page : 17
		acf_ele_form : 1
		button : 14
		countdown : 1
		counter : 6
		divider : 2
		edit_post : 2
		form : 4
		heading : 27
		icon : 1
		image : 4
		image-box : 8
		login : 1
		nav-menu : 2
		new_post : 3
		shortcode : 3
		social-icons : 3
		spacer : 1
		text-editor : 10
		theme-post-title : 1
	popup : 2
		button : 2
		heading : 2
		shortcode : 2
		text-editor : 2
	section : 3
		form : 6
		heading : 8
	single : 2
		new_post : 2
		text-editor : 2
		theme-post-title : 2
	widget : 0
		edit_post : 2
		form : 1
		new_post : 1
	wp-page : 17
		button : 7
		edit_post : 3
		form : 12
		heading : 35
		html : 1
		login : 3
		new_post : 2
		posts : 1
		shortcode : 4
		spacer : 2
		text-editor : 7
		theme-post-title : 2
		toggle : 12
	single-post : 11
		acf_ele_form : 1
		button : 1
		edit_post : 5
		form : 5
		shortcode : 1
		theme-post-title : 4

== הגדרות ==
	
	cpt_support: post, page
	allow_tracking: yes
	unfiltered_files_upload: 1
	load_fa4_shim: yes

== תכונות ==
	Custom Fonts: 0
	Custom Icons: 0

== אינטגרציות ==
	

== הניסויים של אלמנטור ==
	פלט DOM שעבר אופטימיזציה: לא פעיל כברירת מחדל
	טעינת נכסים משופרת: לא פעיל כברירת מחדל
	טעינת CSS משופרת: לא פעיל כברירת מחדל
	Inline Font Icons: לא פעיל כברירת מחדל
	שיפורי נגישות: לא פעיל כברירת מחדל
	Additional Custom Breakpoints: לא פעיל כברירת מחדל
	admin_menu_rearrangement: לא פעיל כברירת מחדל
	פלקסבוקס קונטיינר: לא פעיל כברירת מחדל
	שדרג ספריית Swiper: לא פעיל כברירת מחדל
	ברירת מחדל לממשק החדש של בונה התבנית: לא פעיל
	עיצוב כותרת עליונה ותחתונה: לא פעיל כברירת מחדל
	עורך גירסה 2: לא פעיל כברירת מחדל
	דפי נחיתה: לא פעיל
	אלמנטים מקוננים: לא פעיל כברירת מחדל
	טעינה עצלה של תמונות רקע: לא פעיל כברירת מחדל
	שמור כברירת מחדל: פעיל כברירת מחדל
	מעבר עמוד: לא פעיל
	פתקים: לא פעיל
	לולאה: לא פעיל
	לידים: פעיל
	קפיצת גלילה: פעיל כברירת מחדל
	Mega Menu: לא פעיל כברירת מחדל

== יומן שינויים ==
	
Log: showing 20 of 292023-01-29 20:57:51 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור',
  'from' => '3.10.1',
  'to' => '3.10.2',
)]
2023-02-01 04:21:22 [info] elementor-pro::elementor_pro_updater Started 
2023-02-01 04:21:22 [info] אלמנטור פרו/Upgrades - _on_each_version Start  
2023-02-01 04:21:22 [info] אלמנטור פרו/Upgrades - _on_each_version Finished 
2023-02-01 04:21:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '3.10.2',
  'to' => '3.10.3',
)]
2023-02-14 20:44:42 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'אלמנטור',
  'from' => '3.10.2',
  'to' => '3.11.0',
)]
2023-02-14 20:44:42 [info] elementor::elementor_updater Started 
2023-02-14 20:44:42 [info] אלמנטור/Upgrades - _on_each_version Start  
2023-02-14 20:44:45 [info] אלמנטור/Upgrades - _on_each_version Finished 
2023-02-14 20:44:45 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור',
  'from' => '3.10.2',
  'to' => '3.11.0',
)]
2023-02-27 16:52:26 [info] elementor::elementor_updater Started 
2023-02-27 16:52:26 [info] אלמנטור/Upgrades - _on_each_version Start  
2023-02-27 16:52:26 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'אלמנטור',
  'from' => '3.11.0',
  'to' => '3.11.2',
)]
2023-02-27 16:52:28 [info] אלמנטור/Upgrades - _on_each_version Finished 
2023-02-27 16:52:28 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור',
  'from' => '3.11.0',
  'to' => '3.11.2',
)]
2023-02-27 16:53:06 [info] elementor-pro::elementor_pro_updater Started 
2023-02-27 16:53:06 [info] אלמנטור פרו/Upgrades - _on_each_version Start  
2023-02-27 16:53:06 [info] אלמנטור פרו/Upgrades - _on_each_version Finished 
2023-02-27 16:53:06 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '3.10.3',
  'to' => '3.11.3',
)]
2023-02-27 16:53:06 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '3.10.3',
  'to' => '3.11.3',
)]

PHP: showing 9 of 9PHP: 2023-01-26 12:21:41 [notice X 14][/home/ronit/public_html/delet.today/wp-content/plugins/elementor/core/common/modules/ajax/module.php::172] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-26 12:21:42 [warning X 1][/home/ronit/public_html/delet.today/wp-content/plugins/elementor/core/settings/page/manager.php::242] Illegal string offset 'template' [array (
  'trace' => '
#0: /home/ronit/public_html/delet.today/wp-content/plugins/elementor/core/settings/page/manager.php(242): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/ronit/public_html/delet.today/wp-content/plugins/elementor/core/settings/base/manager.php(313): Elementor\Core\Settings\Page\Manager -> get_saved_settings()
#2: /home/ronit/public_html/delet.today/wp-content/plugins/elementor/core/settings/base/manager.php(104): Elementor\Core\Settings\Base\Manager -> create_model()
#3: /home/ronit/public_html/delet.today/wp-content/plugins/elementor/includes/template-library/sources/local.php(622): Elementor\Core\Settings\Base\Manager -> get_model()
#4: /home/ronit/public_html/delet.today/wp-content/plugins/elementor/includes/template-library/sources/local.php(478): Elementor\TemplateLibrary\Source_Local -> get_item()
',
)]
PHP: 2023-01-26 12:21:42 [error X 1][/home/ronit/public_html/delet.today/wp-content/plugins/elementor/includes/base/controls-stack.php::2414] Uncaught TypeError: Argument 1 passed to Elementor\Controls_Stack::sanitize_settings() must be of the type array, string given, called in /home/ronit/public_html/delet.today/wp-content/plugins/elementor/includes/base/controls-stack.php on line 1109 and defined in /home/ronit/public_html/delet.today/wp-content/plugins/elementor/includes/base/controls-stack.php:2414
Stack trace:
#0 /home/ronit/public_html/delet.today/wp-content/plugins/elementor/includes/base/controls-stack.php(1109): Elementor\Controls_Stack->sanitize_settings('d')
#1 /home/ronit/public_html/delet.today/wp-content/plugins/elementor/includes/template-library/sources/local.php(624): Elementor\Controls_Stack->get_data('settings')
#2 /home/ronit/public_html/delet.today/wp-content/plugins/elementor/includes/template-library/sources/local.php(478): Elementor\TemplateLibrary\Source_Local->get_item(13579)
#3 /home/ronit/public_html/delet.today/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(56): Elementor\Tem [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-26 12:24:09 [error X 1][/home/ronit/public_html/delet.today/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-cache.php::29] Uncaught TypeError: Argument 2 passed to ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Cache::add() must be of the type array, string given, called in /home/ronit/public_html/delet.today/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-cache.php on line 135 and defined in /home/ronit/public_html/delet.today/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-cache.php:29
Stack trace:
#0 /home/ronit/public_html/delet.today/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-cache.php(135): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Cache->add(Object(ElementorPro\Modules\ThemeBuilder\Documents\Single_Post), '1')
#1 /home/ronit/public_html/delet.today/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(298): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Cache->regenerate()
#2 /home/ronit/public_html/delet.today/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-man [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-28 20:57:34 [warning X 33][C:\Users\USER\Local Sites\delet\app\public\wp-content\plugins\elementor\core\settings\page\manager.php::242] Illegal string offset 'template' [array (
  'trace' => '
#0: C:\Users\USER\Local Sites\delet\app\public\wp-content\plugins\elementor\core\settings\page\manager.php(242): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: C:\Users\USER\Local Sites\delet\app\public\wp-content\plugins\elementor\core\settings\base\manager.php(313): Elementor\Core\Settings\Page\Manager -> get_saved_settings()
#2: C:\Users\USER\Local Sites\delet\app\public\wp-content\plugins\elementor\core\settings\base\manager.php(104): Elementor\Core\Settings\Base\Manager -> create_model()
#3: C:\Users\USER\Local Sites\delet\app\public\wp-content\plugins\elementor\includes\template-library\sources\local.php(622): Elementor\Core\Settings\Base\Manager -> get_model()
#4: C:\Users\USER\Local Sites\delet\app\public\wp-content\plugins\elementor\includes\template-library\sources\local.php(478): Elementor\TemplateLibrary\Source_Local -> get_item()
',
)]
PHP: 2023-01-28 20:57:34 [error X 12][C:\Users\USER\Local Sites\delet\app\public\wp-content\plugins\elementor\includes\base\controls-stack.php::2414] Uncaught TypeError: Argument 1 passed to Elementor\Controls_Stack::sanitize_settings() must be of the type array, string given, called in C:\Users\USER\Local Sites\delet\app\public\wp-content\plugins\elementor\includes\base\controls-stack.php on line 1109 and defined in C:\Users\USER\Local Sites\delet\app\public\wp-content\plugins\elementor\includes\base\controls-stack.php:2414
Stack trace:
#0 C:\Users\USER\Local Sites\delet\app\public\wp-content\plugins\elementor\includes\base\controls-stack.php(1109): Elementor\Controls_Stack->sanitize_settings('d')
#1 C:\Users\USER\Local Sites\delet\app\public\wp-content\plugins\elementor\includes\template-library\sources\local.php(624): Elementor\Controls_Stack->get_data('settings')
#2 C:\Users\USER\Local Sites\delet\app\public\wp-content\plugins\elementor\includes\template-library\sources\local.php(478): Elementor\TemplateLibrary\Source_Local->get_item(13579)
#3 C:\Users\USER\Local Sites\delet\app\public\wp-content\plugins\elementor\includes\template-library\manager.php( [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-29 01:58:55 [error X 42][C:\Users\USER\Local Sites\delet\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-cache.php::29] Uncaught TypeError: Argument 2 passed to ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Cache::add() must be of the type array, string given, called in C:\Users\USER\Local Sites\delet\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-cache.php on line 135 and defined in C:\Users\USER\Local Sites\delet\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-cache.php:29
Stack trace:
#0 C:\Users\USER\Local Sites\delet\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-cache.php(135): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Cache->add(Object(ElementorPro\Modules\ThemeBuilder\Documents\Single_Post), '1')
#1 C:\Users\USER\Local Sites\delet\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-manager.php(298): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Cache->regenerate()
#2 C:\Users\USER\Local Sites\delet\app\public\wp-content\plugins\elementor-pro\modules\t [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-29 02:29:55 [notice X 88][C:\Users\USER\Local Sites\delet\app\public\wp-content\plugins\elementor-pro\modules\dynamic-tags\acf\tags\acf-text.php::33] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-04 03:07:20 [error X 13][C:\Users\USER\Local Sites\delet\app\public\wp-content\plugins\elementor\includes\base\controls-stack.php::2414] Uncaught TypeError: Argument 1 passed to Elementor\Controls_Stack::sanitize_settings() must be of the type array, string given, called in C:\Users\USER\Local Sites\delet\app\public\wp-content\plugins\elementor\includes\base\controls-stack.php on line 1109 and defined in C:\Users\USER\Local Sites\delet\app\public\wp-content\plugins\elementor\includes\base\controls-stack.php:2414
Stack trace:
#0 C:\Users\USER\Local Sites\delet\app\public\wp-content\plugins\elementor\includes\base\controls-stack.php(1109): Elementor\Controls_Stack->sanitize_settings('d')
#1 C:\Users\USER\Local Sites\delet\app\public\wp-content\plugins\elementor\includes\template-library\sources\local.php(624): Elementor\Controls_Stack->get_data('settings')
#2 C:\Users\USER\Local Sites\delet\app\public\wp-content\plugins\elementor\includes\template-library\sources\local.php(478): Elementor\TemplateLibrary\Source_Local->get_item(13579)
#3 C:\Users\USER\Local Sites\delet\app\public\wp-content\plugins\elementor-pro\core\app\modules\site-editor\data\ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 4 of 4JS: 2023-01-29 08:26:20 [error X 4][https://delet.local/wp-content/plugins/elementor/assets/js/editor.js?ver=3.10.1:15412:7] quicktags is not defined 
JS: 2023-01-29 08:27:14 [error X 3][https://delet.local/wp-content/plugins/elementor/assets/js/editor.js?ver=3.10.1:15497:5] QTags is not defined 
JS: 2023-01-30 16:44:19 [error X 20][https://delet.local/wp-content/plugins/elementor/assets/js/common-modules.js?ver=3.10.2:2195:3] Model.isValidChild() should be implemented, please provide 'isValidChild' functionality. 
JS: 2023-02-01 08:05:42 [error X 1][https://delet.local/wp-content/plugins/elementor/assets/js/editor.js?ver=3.10.2:54884:44] Cannot read properties of null (reading 'getBoundingClientRect') 

== אלמנטור - Compatibility Tag ==
	
	Elementor Pro: תואם

== אלמנטור פרו - Compatibility Tag ==

**Comment by Bartnicolaas** [comment]
Hi, I'm facing this bug at the moment. Can it be solved?
