### ISSUE TITLE
Mega Menu not editable in Elementor

### ISSUE THREAD

**Issue by bodhi1970** [elementor/elementor#21626]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I have created mega menus on a page and two days later I wanted to edit something in them. It was easy and smooth to create then and the work totally fine in frontend.
No when I enter Elementor to edit the header, 1. it take super long to load the whole page and it also shows a message in the browser (Firefox). The last attempt even led to endless waiting, and I even couldn't close Elementor. I had to close the whole tab.
<img width="623" alt="Screenshot 2023-03-11 at 09 17 27" src="https://user-images.githubusercontent.com/5292941/224473430-af407d0f-2051-425c-8ebe-6197826f7e29.png">

2. I can not edit the content of the dropdown. Also it seems it doesn't safe properly as everytime I open the header in Elementor it shows the popup for Revisions in the bottom left. All works fine when editing normal pages, just the header where the mega menu is makes troubles.

Also, another thing that is more annoying then a bug: when click on "Manage Website" it opens always a new tab.
Also 2, adding new widgets is now just a small + in the top left corner. Why not leave it to the nice icon of the grid that it was before? And/or leave the icon, even when it is the plus somewhere more obvious and bigger. Ideally to the very right of this row of icons.
<img width="110" alt="Screenshot 2023-03-11 at 09 27 19" src="https://user-images.githubusercontent.com/5292941/224474063-09b30c4d-84db-40d5-8b7f-c2fe6178bec8.png">

### Steps to reproduce

1. create a mega menu
2. save and close
3. open header again and try to edit it.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

					
== Server Environment ==
	Operating System: FreeBSD
	Software: Apache
	MySQL version: FreeBSD Ports v10.3.38
	PHP Version: 7.4.33
	PHP Memory Limit: 256M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 1028M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://ncbi.ch
	Home URL: https://ncbi.ch
	WP Multisite: No
	Max Upload Size: 1 GB
	Memory limit: 40M
	Max Memory limit: 1028M
	Permalink Structure: /%postname%/
	Language: de-CH
	Timezone: Europe/Zurich
	Admin Email: webmaster@ncbi.ch
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: de_CH_informal
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/110.0

== Active Plugins ==
	Admin Menu Editor
		Version: 1.10.4
		Author: Janis Elsts

	Advanced Post Queries
		Version: 1.1.0
		Author: Shabti Kaplan

	Autoptimize
		Version: 3.1.5
		Author: Frank Goossens (futtta)

	BackWPup
		Version: 4.0.0
		Author: Inpsyde GmbH

	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Disable Comments
		Version: 2.4.3
		Author: WPDeveloper

	Dynamic Visibility for Elementor
		Version: 5.0.4
		Author: Dynamic.ooo

	Elementor
		Version: 3.12.0-beta1
		Author: Elementor.com

	Elementor Pro
		Version: 3.12.0-beta1
		Author: Elementor.com

	Elementor Single Builder for MEC
		Version: 1.7.10
		Author: Webnus

	FileBird
		Version: 5.1.4
		Author: Ninja Team

	LoginWP (Formerly Peter's Login Redirect)
		Version: 3.0.7.0
		Author: LoginWP Team

	miniOrange Broken Link Checker/Finder
		Version: 2.4.2
		Author: miniOrange

	Modern Events Calendar
		Version: 6.8.21
		Author: Webnus

	Music Player for Elementor
		Version: 1.5.9.5
		Author: SmartWPress

	Polylang
		Version: 3.3.2
		Author: WP SYNTEX

	Polylang Connect for Elementor
		Version: 2.3.5
		Author: Creame

	Rank Math SEO
		Version: 1.0.110
		Author: Rank Math

	Restrict User Access
		Version: 2.4.2
		Author: Joachim Jensen - DEV Institute

	Table Rate Shipping for WooCommerce
		Version: 2.28
		Author: JEM Plugins

	Theme and plugin translation for Polylang (TTfP)
		Version: 3.3.3
		Author: Marcin Kazmierski

	WooCommerce
		Version: 7.4.1
		Author: Automattic

	Wordfence Security
		Version: 7.9.1
		Author: Wordfence

	zahls.ch Credit Cards, PostFinance and TWINT for WooCommerce
		Version: 1.2.3
		Author: siebenberge gmbh

== Elements Usage ==
	
	archive : 5
		container : 8
		posts : 4
		theme-archive-title : 4
	container : 5
		container : 1
		heading : 1
		text-editor : 2
	footer : 2
		container : 9
		form : 1
		heading : 5
		icon-list : 4
		social-icons : 1
		text-editor : 2
	header : 2
		accordion : 2
		container : 20
		heading : 20
		icon-list : 6
		image : 1
		mega-menu : 1
		nav-menu : 1
		polylang-language-switcher : 2
		posts : 3
		search-form : 1
		social-icons : 1
		spacer : 5
		template : 1
		text-editor : 1
		theme-site-logo : 1
		woocommerce-menu-cart : 1
	page : 10
		container : 12
		gallery : 2
		heading : 31
		icon-box : 1
		icon-list : 4
		image : 2
		text-editor : 27
	section : 2
		slide-compact-player : 1
	widget : 0
		icon-list : 1
		image : 1
	wp-post : 2
		container : 1
		divider : 3
		heading : 4
		icon-list : 5
		image : 4
		text-editor : 9
		video : 4
	wp-page : 88
		accordion : 7
		audio : 2
		blockquote : 2
		button : 2
		container : 219
		divider : 28
		form : 7
		gallery : 3
		heading : 343
		html : 3
		icon-box : 5
		icon-list : 54
		image : 36
		image-box : 3
		image-carousel : 1
		login : 1
		posts : 6
		slide-compact-player : 1
		slides : 1
		text-editor : 299
		theme-post-title : 1
		video : 19
		woocommerce-products : 1
	single-post : 2
		container : 3
		heading : 1
		post-info : 2
		post-navigation : 1
		posts : 1
		theme-post-content : 1
		theme-post-featured-image : 1
		theme-post-title : 1
	product-archive : 1
		container : 1
		heading : 1
		woocommerce-products : 1
	loop-item : 1
		button : 2
		container : 4
		heading : 2
		text-editor : 3
	error-404 : 1
		heading : 3
		search-form : 1

== Einstellungen ==
	
	cpt_support: post, page, e-landing-page, mec_esb
	disable_color_schemes: yes
	disable_typography_schemes: yes
	allow_tracking: yes
	editor_break_lines: 1
	unfiltered_files_upload: 1
	font_display: block

== Features ==
	Custom Fonts: 1
	Custom Icons: 1

== Integrations ==
	
	recaptcha_v3: Active
	woocommerce: Active

== Elementor Experiments ==
	Optimierte DOM Ausgabe: Aktiv
	Improved Asset Loading: Aktiv
	Improved CSS Loading: Standardmässig aktiv
	Inline Font Icons: Aktiv
	Verbesserungen der Benutzerfreundlichkeit: Aktiv
	Additional Custom Breakpoints: Standardmässig aktiv
	admin_menu_rearrangement: Standardmässig inaktiv
	Flexbox Container: Aktiv
	Upgrade Swiper Library: Aktiv
	Default to New Theme Builder: Standardmässig aktiv
	Hello Theme Header & Footer: Standardmässig aktiv
	Editor Top Bar: Aktiv
	Landingpage (Einstiegsseite): Standardmässig aktiv
	Nested Elements: Aktiv
	Lazy Load Background Images: Aktiv
	Page Transitions: Standardmässig aktiv
	Notes: Standardmässig aktiv
	Loop: Aktiv
	Scroll Snap: Standardmässig aktiv
	Menu: Aktiv

== Log ==
	
Log: showing 20 of 292023-02-24 08:36:11 [info] elementor-pro::elementor_pro_updater Started 
2023-02-24 08:36:11 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-02-24 08:36:11 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-02-24 08:36:11 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.1',
  'to' => '3.11.2',
)]
2023-02-27 11:14:46 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.2',
  'to' => '3.11.3',
)]
2023-02-27 11:14:47 [info] elementor-pro::elementor_pro_updater Started 
2023-02-27 11:14:47 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-02-27 11:14:47 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-02-27 11:14:47 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.2',
  'to' => '3.11.3',
)]
2023-02-27 11:14:49 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.2',
  'to' => '3.11.3',
)]
2023-03-07 00:18:40 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.2',
  'to' => '3.12.0-beta1',
)]
2023-03-07 00:18:41 [info] elementor::elementor_updater Started 
2023-03-07 00:18:41 [info] Elementor/Upgrades - _on_each_version Start  
2023-03-07 00:18:42 [info] Elementor/Upgrades - _on_each_version Finished 
2023-03-07 00:18:42 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.2',
  'to' => '3.12.0-beta1',
)]
2023-03-07 00:19:24 [info] elementor-pro::elementor_pro_updater Started 
2023-03-07 00:19:24 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-03-07 00:19:24 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-03-07 00:19:24 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.3',
  'to' => '3.12.0-beta1',
)]
2023-03-07 00:19:30 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.3',
  'to' => '3.12.0-beta1',
)]

PHP: showing 6 of 6PHP: 2023-02-23 17:31:40 [notice X 1][/home/ncbich/www/wp2022.ncbi.ch/wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-27 11:14:46 [warning X 2][/home/ncbich/www/wp2022.ncbi.ch/wp-content/plugins/elementor/core/files/manager.php::111] unlink(/home/ncbich/www/wp2022.ncbi.ch/wp-content/uploads/elementor/css/post-997.css) [<a href='https://secure.php.net/manual/en/function.unlink.php'>function.unlink.php</a>]: No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-07 00:44:35 [error X 1][/home/ncbich/www/wp2022.ncbi.ch/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::295] Uncaught Error: Call to a member function update_meta() on bool in /home/ncbich/www/wp2022.ncbi.ch/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:295
Stack trace:
#0 /home/ncbich/www/wp2022.ncbi.ch/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(168): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/ncbich/www/wp2022.ncbi.ch/wp-content/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/ncbich/www/wp2022.ncbi.ch/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/ncbich/www/wp2022.ncbi.ch/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Ar [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-07 15:59:16 [notice X 3][/home/ncbich/www/wp2022.ncbi.ch/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-07 15:59:17 [notice X 2][/home/ncbich/www/wp2022.ncbi.ch/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined index: condition_type [array (
  'trace' => '
#0: /home/ncbich/www/wp2022.ncbi.ch/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /home/ncbich/www/wp2022.ncbi.ch/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /home/ncbich/www/wp2022.ncbi.ch/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /home/ncbich/www/wp2022.ncbi.ch/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2023-03-10 10:46:49 [notice X 5][/home/ncbich/www/wp2022.ncbi.ch/wp-content/plugins/elementor/core/logger/items/js.php::17] Undefined index: url [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 7 of 7JS: 2023-03-06 23:25:43 [error X 1][https://ncbi.ch/wp-content/plugins/elementor/assets/js/df16c9d56464dd4f0800.bundle.min.js:2:7805] t.target.closest(...) is null 
JS: 2023-03-06 23:39:39 [error X 6][https://ncbi.ch/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.12.0-beta1:3:785300] this.store.find(...) is undefined 
JS: 2023-03-10 09:46:27 [error X 577][https://ncbi.ch/wp-content/plugins/dynamic-visibility-for-elementor/assets/js/editor-dynamic-visibility.js?ver=5.0.4:205:3] elementorFrontend.config.elements is undefined 
JS: 2023-03-10 09:46:25 [error X 17][https://ncbi.ch/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.12.0-beta1:3:658098] elementorFrontend.elements.window.jQuery is not a function 
JS: 2023-03-10 09:46:25 [error X 106][https://ncbi.ch/wp-includes/js/mediaelement/mediaelement-and-player.min.js?ver=4.2.17:12:0]  
JS: 2023-03-10 09:46:26 [error X 9][https://ncbi.ch/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.12.0-beta1:2:63893] can't convert undefined to object 
JS: 2023-03-10 09:46:28 [error X 143][https://ncbi.ch/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.12.0-beta1:2:4963] undefined has no properties 

== Elementor - Compatibility Tag ==
	
	Dynamic Visibility for Elementor: Incompatible
	Elementor Pro: Incompatible
	Elementor Single Builder for MEC: Compatibility not specified
	Music Player for Elementor: Incompatible
	Polylang Connect for Elementor: Incompatible

== Elementor Pro - Compatibility Tag ==
	
	Dynamic Visibility for Elementor: Incompatible
	Polylang Connect for Elementor: Incompatible

**Comment by bodhi1970** [comment]
Same issue is in Chrome.
Also if I finally manage to make any changes in the header when I click the Publish button it the turning thingy shows up and it doesn't save properly
<img width="499" alt="Screenshot 2023-03-11 at 12 24 30" src="https://user-images.githubusercontent.com/5292941/224481931-6f5ee545-2d1d-4162-a59b-02f36e3adc12.png">
<img width="167" alt="Screenshot 2023-03-11 at 12 33 23" src="https://user-images.githubusercontent.com/5292941/224481934-90c8f686-0f22-4214-ba33-e3af65232eb3.png">

**Comment by Michaelgimii** [comment]
Hi @bodhi1970, It would be much better if you report this problem [here](https://github.com/elementor/elementor/discussions/21553). Because beta 3.12 is on the same topic.

**Comment by nicholaszein** [comment]
Hello @bodhi1970! 

Thank you for submitting your issue! 🙏 

We already identified this issue, and it is being investigated. Please do not post it in the Beta Discussion. Always submit a Bug Report here as you did. You can, however, also comment with a link to your issue if you want. But we can only properly track Bug Reports if they are made here. (@Michaelgimii this is relevant for you too).

Thanks!

Best regards

**Comment by nicholaszein** [comment]
@bodhi1970,

can you please explain how you built your menu? Maybe record a video of the steps you took in detail, what you added inside the menu, how you added links, and anything else relevant.

Thanks 🙏

**Comment by bodhi1970** [comment]
I added a container with some headlines, accordions, icon lists and post grid inside.
Since the latest update it works at least to open the Elementor smoothly and also save changes. I still can not edit with click on the menu item as the dropdown contents opens on mouseover and disappears when moving down. But I found oout I can edit everything in the Navigator (no called Structure :( )

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor **v3.12**! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

Cheers 🥂
