### ISSUE TITLE
Cart Icon styling issues

### ISSUE THREAD

**Issue by YossiDavid** [elementor/elementor#21637]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi!
In the "cart icon" widget, there's a bug that loads the CSS file of the default kit after the CSS file of the current post/page is loaded.
Because of that, the cart icon gets the styling of a regular button and not the style I gave to it in the editor.

![WhatsApp Image 2023-03-10 at 12 38 44](https://user-images.githubusercontent.com/40799241/224672919-a6cf5e45-d117-4f53-b706-098bda7bb66b.jpeg)

### Steps to reproduce

1) add global styling to buttons via "site settings"
2) add a "cart icon" widget to the page (header in my case)
3) style the icon as you want.
4) check on the front - from incognito or none loggedin page.

you'll see in the inspect the order of the files loaded.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.23.1
	MySQL version: MariaDB Server v5.5.40-MariaDB-36.1
	PHP Version: 7.4.32
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://p4w.co.il
	Home URL: https://p4w.co.il
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 128M
	Max Memory limit: 2048M
	Permalink Structure: /%postname%/
	Language: he-IL
	Timezone: Asia/Jerusalem
	Admin Email: team@p4w.co.il
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: he_IL
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Order Export For WooCommerce
		Version: 3.4.0
		Author: AlgolPlus

	Checkout Field Editor for WooCommerce (Pro)
		Version: 3.4.0
		Author: ThemeHigh

	Code Snippets
		Version: 3.3.0
		Author: Code Snippets Pro

	Doubly Pro
		Version: 1.0.41
		Author: Unlimited Elements

	Elementor
		Version: 3.11.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.11.5
		Author: Elementor.com

	HappyFiles Pro
		Version: 1.8.2
		Author: Codeer

	JetEngine
		Version: 3.1.3
		Author: Crocoblock

	JetEngine - Trim string callback
		Version: 1.0.1
		Author: Crocoblock

	JetWooBuilder For Elementor
		Version: 2.1.4
		Author: Crocoblock

	MouseWheel Smooth Scroll
		Version: 6.0
		Author: KubiQ

	Rank Math SEO
		Version: 1.0.110
		Author: Rank Math

	ShortPixel Image Optimizer
		Version: 5.2.1
		Author: ShortPixel - Convert WebP/AVIF & Optimize Images

	WooCommerce
		Version: 7.4.1
		Author: Automattic

	WP Rocket
		Version: 3.12.5.3
		Author: WP Media

	Yaad Sarig Payment Gateway For WC
		Version: 2.1.52
		Author: YAAD-PAY & 10Bit

== תכונות ==
	Custom Fonts: 3
	Custom Icons: 0

== אינטגרציות ==
	
	woocommerce: פעיל

== הניסויים של אלמנטור ==
	פלט DOM שעבר אופטימיזציה: פעיל כברירת מחדל
	טעינת נכסים משופרת: פעיל כברירת מחדל
	טעינת CSS משופרת: פעיל כברירת מחדל
	Inline Font Icons: פעיל
	שיפורי נגישות: פעיל כברירת מחדל
	Additional Custom Breakpoints: פעיל כברירת מחדל
	admin_menu_rearrangement: לא פעיל כברירת מחדל
	פלקסבוקס קונטיינר: פעיל
	שדרג ספריית Swiper: פעיל
	ברירת מחדל לממשק החדש של בונה התבנית: לא פעיל
	עיצוב כותרת עליונה ותחתונה: לא פעיל
	עורך גירסה 2: לא פעיל כברירת מחדל
	דפי נחיתה: פעיל כברירת מחדל
	אלמנטים מקוננים: פעיל
	טעינה עצלה של תמונות רקע: פעיל
	שמור כברירת מחדל: פעיל כברירת מחדל
	מעבר עמוד: לא פעיל
	פתקים: פעיל כברירת מחדל
	לולאה: לא פעיל
	לידים: פעיל כברירת מחדל
	קפיצת גלילה: לא פעיל
	Mega Menu: לא פעיל כברירת מחדל

== יומן שינויים ==
	
JS: showing 12 of 12JS: 2023-03-02 07:50:32 [error X 23][http://p172819-91-32004.s91.upress.link/wp-admin/load-scripts.php?c=0&loadchunk_0=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&loadchunk_1=hooks&ver=6.1.1:4:51824] Cannot read properties of undefined (reading 'replace') 
JS: 2023-03-02 08:30:30 [error X 2][http://p172819-91-32004.s91.upress.link/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.11.2:3:592136] Cannot read properties of null (reading 'id') 
JS: 2023-03-02 08:48:04 [error X 2][http://p172819-91-32004.s91.upress.link/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.11.2:3:791161] Cannot read properties of undefined (reading 'toLowerCase') 
JS: 2023-03-02 08:51:53 [error X 1][http://p172819-91-32004.s91.upress.link/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view16184") has already been destroyed and cannot be used. 
JS: 2023-03-02 08:52:24 [error X 1][http://p172819-91-32004.s91.upress.link/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view23145") has already been destroyed and cannot be used. 
JS: 2023-03-06 07:58:16 [error X 2][https://p4w.co.il/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.11.2:3:670939] this.model.isValidChild is not a function 
JS: 2023-03-06 09:28:04 [error X 2327][https://p4w.co.il/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:16820] Cannot read properties of null (reading 'clone') 
JS: 2023-03-06 09:28:04 [error X 34][https://p4w.co.il/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:21012] Cannot read properties of null (reading 'changestop') 
JS: 2023-03-08 14:03:40 [error X 166][https://p4w.co.il/wp-content/plugins/elementor-pro/assets/js/elements-handlers.min.js?ver=3.11.4:2:9127] Cannot read properties of undefined (reading 'size') 
JS: 2023-03-08 22:33:33 [error X 2][https://p4w.co.il/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.11.3:3:791668] Cannot read properties of undefined (reading 'localized') 
JS: 2023-03-09 08:01:52 [error X 4][https://p4w.co.il/wp-content/plugins/elementor/assets/js/new-template.min.js?ver=3.11.3:2:2932] elementor_new_template_form_controls is not defined 
JS: 2023-03-12 04:03:35 [error X 4][https://p4w.co.il/wp-content/plugins/elementor/assets/js/web-cli.min.js?ver=3.11.3:3:111479] Cannot read properties of null (reading 'classList') 

Log: showing 20 of 242023-03-08 11:42:19 [info] elementor-pro::elementor_pro_updater Started 
2023-03-08 11:42:19 [info] אלמנטור פרו/Upgrades - _on_each_version Start  
2023-03-08 11:42:19 [info] אלמנטור פרו/Upgrades - _on_each_version Finished 
2023-03-08 11:42:19 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '3.11.3',
  'to' => '3.11.4',
)]
2023-03-08 11:42:19 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '3.11.3',
  'to' => '3.11.4',
)]
2023-03-08 11:53:46 [info] elementor::elementor_updater Started 
2023-03-08 11:53:46 [info] אלמנטור/Upgrades - _on_each_version Start  
2023-03-08 11:53:46 [info] אלמנטור/Upgrades - _on_each_version Finished 
2023-03-08 11:53:46 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור',
  'from' => '3.11.2',
  'to' => '3.11.3',
)]
2023-03-08 11:53:46 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'אלמנטור',
  'from' => '3.11.2',
  'to' => '3.11.3',
)]
2023-03-13 11:51:11 [info] elementor-pro::elementor_pro_updater Started 
2023-03-13 11:51:11 [info] אלמנטור פרו/Upgrades - _on_each_version Start  
2023-03-13 11:51:11 [info] אלמנטור פרו/Upgrades - _on_each_version Finished 
2023-03-13 11:51:11 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '3.11.4',
  'to' => '3.11.5',
)]
2023-03-13 11:51:11 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '3.11.4',
  'to' => '3.11.5',
)]
2023-03-13 11:51:12 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '3.11.4',
  'to' => '3.11.5',
)]
2023-03-13 12:02:33 [info] elementor::elementor_updater Started 
2023-03-13 12:02:33 [info] אלמנטור/Upgrades - _on_each_version Start  
2023-03-13 12:02:33 [info] אלמנטור/Upgrades - _on_each_version Finished 
2023-03-13 12:02:33 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור',
  'from' => '3.11.3',
  'to' => '3.11.4',
)]

PHP: showing 6 of 6PHP: 2023-03-06 11:29:03 [notice X 4][/home/pwcoilcf/domains/p4w.co.il/public_html/wp-content/plugins/elementor/core/logger/items/js.php::17] Undefined index: url [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-08 10:41:42 [notice X 1][/home/pwcoilcf/domains/p4w.co.il/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::168] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-08 10:57:26 [error X 2][/home/pwcoilcf/domains/p4w.co.il/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::295] Uncaught Error: Call to a member function update_meta() on bool in /home/pwcoilcf/domains/p4w.co.il/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:295
Stack trace:
#0 /home/pwcoilcf/domains/p4w.co.il/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(168): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions()
#2 /home/pwcoilcf/domains/p4w.co.il/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func()
#3 /home/pwcoilcf/domains/p4w.co.il/public_html/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#4 /home/pwcoilcf/domains/p4w.co.il/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#5 /home/pwcoilcf/domains/p4w.co.il/public_html/wp-includes/plugin.php( [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-08 17:43:35 [notice X 11][/home/pwcoilcf/domains/p4w.co.il/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-09 12:21:45 [notice X 2][/home/pwcoilcf/domains/p4w.co.il/public_html/wp-content/plugins/elementor-pro/core/utils.php::198] Trying to get property 'singular_name' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-10 08:30:51 [notice X 1][/home/pwcoilcf/domains/p4w.co.il/public_html/wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== אלמנטור - Compatibility Tag ==
	
	Elementor Pro: תואם
	JetWooBuilder For Elementor: לא תואם

== אלמנטור פרו - Compatibility Tag ==
	
	JetWooBuilder For Elementor: לא תואם

**Comment by GwendleWeb** [comment]
I'm having this issue too, did a solution ever come up?

**Comment by JaroslavBohac** [comment]
This is a big problem. The basic element ruins the visual impression of the page header. It simply cannot be set.

**Comment by YossiDavid** [comment]
@bainternet @shilo-ey 
Please help us and solve this basic problem.
Thank you

**Comment by klicker33** [comment]
> @bainternet @shilo-ey Please help us and solve this basic problem. Thank you

Help me to please, it's ridiculously long answer

**Comment by JaroslavBohac** [comment]
It seems like this is beyond the power of the Elementor developers. I still have that problem and it looks terrible.

**Comment by doronwolf** [comment]
Hi @YossiDavid I want to make sure I understand this issue correctly - I assume you are having these styling issues for the cart button only if you also set style for buttons in _site settings > theme style > buttons_  right?

**Comment by YossiDavid** [comment]
Hi @doronwolf you're correct, this is the issue I've facing
Thank you

**Comment by doronwolf** [comment]
Thank you @YossiDavid :) in that case, I can confirm we are working on infrastructure changes that should solve the issue, however, it's much more tricky than it sounds (the Theme CSS style for links will always tend to be more specific, and making the widget local settings override them can cause the widget default settings to override them as well, which is, obviously, not what users who use themes or [Elementor's 'theme style'] to achieve)
the bottom line - we are working on a solution but I can't commit to a date on which the solution will be ready, i will try to update here once I have more information I can share
