### ISSUE TITLE
⛔ 🧩 🐞 Bug Report: PHP Fatal error:  Uncaught TypeError: array_merge(): Argument #2 must be of type array, bool given in elementor/includes/managers/controls.php:790

### ISSUE THREAD

**Issue by Striffly** [elementor/elementor#21648]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi

Using Bridge theme (from Qode), when use the Elemntor editor in any page I got the following error :

```php
PHP Fatal error:  Uncaught TypeError: array_merge(): Argument #2 must be of type array, bool given in elementor/includes/managers/controls.php:790
```

I can fix it by using the following code : 
```php
if ( is_array( $control_default_value ) ) {
     $control_data['default'] = isset( $control_data['default'] ) && is_array( $control_data['default'] ) ? array_merge( $control_default_value, $control_data['default'] ) : $control_default_value;
} else {
    $control_data['default'] = isset( $control_data['default'] ) && is_array( $control_data['default'] ) ? $control_data['default'] : $control_default_value;
}
```

### Steps to reproduce

1) Install Wordpress and Bridge theme (from Qode)
2) Log to admin
3) Edit a page with Elementor

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

```
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.22.1
	MySQL version: mariadb.org binary distribution v10.6.12
	PHP Version: 8.1.16
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://xxx.com
	Home URL: https://xxx.com
	WP Multisite: No
	Max Upload Size: 2 Mo
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: fr-FR
	Timezone: Europe/Paris
	Admin Email: chomaz.t@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Bridge
	Version: 29.4
	Author: Qode Interactive
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: fr_FR
	User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36

== Active Plugins ==
	Bridge Core
		Version: 3.0.7
		Author: Qode

	Clean Image Filenames
		Version: 1.4
		Author: Upperdog

	Contact Form 7
		Version: 5.7.4
		Author: Takayuki Miyoshi

	Disable Gutenberg
		Version: 2.9
		Author: Jeff Starr

	Elementor
		Version: 3.11.4
		Author: Elementor.com

	Nested Pages
		Version: 3.2.3
		Author: Kyle Phillips

	Qi Addons For Elementor
		Version: 1.5.7
		Author: Qode Interactive

	Qode LMS
		Version: 3.0.6
		Author: Qode Themes

	Slider Revolution
		Version: 6.6.11
		Author: ThemePunch

	SVG Support
		Version: 2.5.5
		Author: Benbodhi

	W3 Total Cache
		Version: 2.3.0
		Author: BoldGrid

	WP Mail SMTP
		Version: 3.7.0
		Author: WPForms

	WP Migrate
		Version: 2.6.3
		Author: WP Engine

	Yoast SEO
		Version: 20.2.1
		Author: Team Yoast


== Must-Use Plugins ==
	Disable admin email notifications
		Version: 1.0.1
		Author: Pamplemousse

	Disable Comments (Must Use version)
		Version: 1.1.2
		Author: Samir Shah

	Disable XMLRPC and Pingback
		Version: 
		Author: Pamplemousse

	WP Migrate Compatibility
		Version: 1.3
		Author: Delicious Brains


== Expériences d’Elementor ==
	Sortie DOM optimisée: Actif par défaut
	Amélioration du chargement des ressources: Actif par défaut
	Optimisation du chargement du CSS: Actif par défaut
	Icônes de police « inline »: Inactif par défaut
	Améliorations de l’accessibilité: Actif par défaut
	Points d’arrêt personnalisés supplémentaires: Actif par défaut
	admin_menu_rearrangement: Inactif par défaut
	Conteneur Flexbox: Inactif par défaut
	Mettre à niveau la bibliothèque Swiper: Actif par défaut
	Éditeur V2: Inactif par défaut
	Page d’atterrissage: Actif par défaut
	Éléments imbriqués: Inactif par défaut
	Chargement différé des images d’arrière-plan: Inactif par défaut
	Définir comme valeur par défaut: Actif par défaut


== Journal ==
	
PHP: showing 4 of 4PHP: 2023-03-06 17:06:53 [warning X 8][xxxwp-content/plugins/elementor/includes/managers/controls.php::790] array_merge(): Expected parameter 2 to be an array, bool given [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-06 17:10:10 [notice X 63][xxxwp-content/plugins/elementor/core/kits/manager.php::280] Trying to get property &#039;post_status&#039; of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-06 19:50:26 [error X 4][/var/www/xxx/wp-content/plugins/elementor/includes/managers/controls.php::790] Uncaught TypeError: array_merge(): Argument #2 must be of type array, bool given in /var/www/xxx/wp-content/plugins/elementor/includes/managers/controls.php:790
Stack trace:
#0 /var/www/xxx/wp-content/plugins/elementor/includes/managers/controls.php(790): array_merge()
#1 /var/www/xxx/wp-content/plugins/elementor/includes/base/controls-stack.php(421): Elementor\Controls_Manager-&gt;add_control_to_stack()
#2 /var/www/xxx/wp-content/plugins/elementor/includes/elements/repeater.php(117): Elementor\Controls_Stack-&gt;add_control()
#3 /var/www/xxx/wp-content/plugins/qi-addons-for-elementor/inc/admin/inc/shortcodes/translators/elementor/class-qiaddonsforelementor-framework-elementor-translator.php(676): Elementor\Repeater-&gt;add_control()
#4 /var/www/xxx/wp-content/plugins/qi-addons-for-elementor/inc/plugins/elementor/class-qiaddonsforelementor-elementor-widget-base.php(55): QiAddonsForElementor_Framework_Elementor_Translator-&gt;create_controls()
#5 /var/www/xxx/wp-content/plugins/elementor/includes/base/controls-stack.php(2329): QiAddonsForElementor_Elementor_Widget_Base-&gt;register_controls()
#6 /var/www/xxx/wp-content/plugins/elementor/includes/base/controls-stack.php(496): Elementor\Controls_Stack-&gt;init_controls()
#7 /var/www/xxx/wp-content/plugins/elementor/includes/base/widget-base.php(177): Elementor\Controls_Stack-&gt;get_stack()
#8 /var/www/xxx/wp-content/plugins/elementor/includes/managers/widgets.php(368): Elementor\Widget_Base-&gt;get_stack()
#9 [internal function]: Elementor\Widgets_Manager-&gt;ajax_get_widget_types_controls_config()
#10 /var/www/xxx/wp-content/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func()
#11 /var/www/xxx/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module-&gt;handle_ajax_request()
#12 /var/www/xxx/wp-includes/class-wp-hook.php(332): WP_Hook-&gt;apply_filters()
#13 /var/www/xxx/wp-includes/plugin.php(517): WP_Hook-&gt;do_action()
#14 /var/www/xxx/wp-admin/admin-ajax.php(188): do_action()
#15 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-13 21:47:39 [error X 6][/var/www/xxx/wp-content/plugins/elementor/includes/managers/controls.php::790] Uncaught TypeError: array_merge(): Argument #2 must be of type array, bool given in /var/www/xxx/wp-content/plugins/elementor/includes/managers/controls.php:790
Stack trace:
#0 /var/www/xxx/wp-content/plugins/elementor/includes/managers/controls.php(790): array_merge()
#1 /var/www/xxx/wp-content/plugins/elementor/includes/base/controls-stack.php(421): Elementor\Controls_Manager-&gt;add_control_to_stack()
#2 /var/www/xxx/wp-content/plugins/elementor/includes/elements/repeater.php(117): Elementor\Controls_Stack-&gt;add_control()
#3 /var/www/xxx/wp-content/plugins/qi-addons-for-elementor/inc/admin/inc/shortcodes/translators/elementor/class-qiaddonsforelementor-framework-elementor-translator.php(676): Elementor\Repeater-&gt;add_control()
#4 /var/www/xxx/wp-content/plugins/qi-addons-for-elementor/inc/plugins/elementor/class-qiaddonsforelementor-elementor-widget-base.php(55): QiAddonsForElementor_Framework_Elementor_Translator-&gt;create_controls()
#5 /var/www/xxx/wp-content/plugins/elementor/includes/base/controls-stack.php(2329): QiAddonsForElementor_Elementor_Widget_Base-&gt;register_controls()
#6 /var/www/xxx/wp-content/plugins/elementor/includes/base/controls-stack.php(496): Elementor\Controls_Stack-&gt;init_controls()
#7 /var/www/xxx/wp-content/plugins/elementor/includes/base/widget-base.php(177): Elementor\Controls_Stack-&gt;get_stack()
#8 /var/www/xxx/wp-content/plugins/elementor/includes/base/controls-stack.php(300): Elementor\Widget_Base-&gt;get_stack()
#9 /var/www/xxx/wp-content/plugins/elementor/core/files/css/global-css.php(120): Elementor\Controls_Stack-&gt;get_controls()
#10 /var/www/xxx/wp-content/plugins/elementor/core/files/css/global-css.php(66): Elementor\Core\Files\CSS\Global_CSS-&gt;render_schemes_and_globals_css()
#11 /var/www/xxx/wp-content/plugins/elementor/core/files/css/base.php(651): Elementor\Core\Files\CSS\Global_CSS-&gt;render_css()
#12 /var/www/xxx/wp-content/plugins/elementor/core/files/base.php(180): Elementor\Core\Files\CSS\Base-&gt;parse_content()
#13 /var/www/xxx/wp-content/plugins/elementor/core/files/css/base.php(130): Elementor\Core\Files\Base-&gt;update_file()
#14 /var/www/xxx/wp-content/plugins/elementor/core/files/css/base.php(217): Elementor\Core\Files\CSS\Base-&gt;update()
#15 /var/www/xxx/wp-content/plugins/elementor/includes/frontend.php(1048): Elementor\Core\Files\CSS\Base-&gt;enqueue()
#16 /var/www/xxx/wp-content/plugins/elementor/includes/frontend.php(670): Elementor\Frontend-&gt;parse_global_css_code()
#17 /var/www/xxx/wp-includes/class-wp-hook.php(308): Elementor\Frontend-&gt;enqueue_styles()
#18 /var/www/xxx/wp-includes/class-wp-hook.php(332): WP_Hook-&gt;apply_filters()
#19 /var/www/xxx/wp-includes/plugin.php(517): WP_Hook-&gt;do_action()
#20 /var/www/xxx/wp-includes/script-loader.php(2180): do_action()
#21 /var/www/xxx/wp-includes/class-wp-hook.php(308): wp_enqueue_scripts()
#22 /var/www/xxx/wp-includes/class-wp-hook.php(332): WP_Hook-&gt;apply_filters()
#23 /var/www/xxx/wp-includes/plugin.php(517): WP_Hook-&gt;do_action()
#24 /var/www/xxx/wp-includes/general-template.php(3043): do_action()
#25 /var/www/xxx/wp-content/themes/bridge/header.php(28): wp_head()
#26 /var/www/xxx/wp-includes/template.php(783): require_once(&#039;...&#039;)
#27 /var/www/xxx/wp-includes/template.php(718): load_template()
#28 /var/www/xxx/wp-includes/general-template.php(48): locate_template()
#29 /var/www/xxx/wp-content/themes/bridge/full_width.php(35): get_header()
#30 /var/www/xxx/wp-includes/template-loader.php(106): include(&#039;...&#039;)
#31 /var/www/xxx/wp-blog-header.php(19): require_once(&#039;...&#039;)
#32 /var/www/xxx/index.php(17): require(&#039;...&#039;)
#33 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 5 of 52023-03-13 21:46:38 [info] elementor::elementor_updater Started 
2023-03-13 21:46:38 [info] Elementor/Upgrades - _on_each_version Start  
2023-03-13 21:46:38 [info] Elementor/Upgrades - _on_each_version Finished 
2023-03-13 21:46:38 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.2',
  'to' => '3.11.4',
)]
2023-03-13 21:46:38 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.2',
  'to' => '3.11.4',
)]



== Elementor - Compatibility Tag ==
	
	Qi Addons For Elementor: Compatibilité non spécifiée
```

**Comment by nicholaszein** [comment]
Hello,

Thank you for reaching out! 🙏 

### ⛔ 🧩 Please note that while we do welcome bug reports, we can't provide support for 3rd-party themes.

If your issue is specifically happening only when you're using a feature from a 3rd-party software, or only when the 3rd-party software is active, you'll need to contact the support for that specific software or its developers.

To make sure the issue is not being caused by Elementor and isolate this conflict please try these **Troubleshooting steps**:

#### ⚠️ Make a Backup of your website before proceeding, and if possible do it in a staging environment!

1. Disable/Deactivate all your plugins except **Elementor** (and **Elementor Pro**).
    - If this solves the problem, gradually re-activate plugin-by-plugin (and check if the problem returns) to identify the problematic or conflicting plugin. In this case, contact the 3rd-party plugin support as we don't provide support for 3rd party plugins.
    - If it doesn't solve your problem, try the next step:
2. Change your WordPress theme to the [Hello Elementor](https://wordpress.org/themes/hello-elementor/) theme and check if the problem is solved.
3. Clear all cache types, including but not limited to **Server cache**, **WordPress (optimization plugin) cache**, **CDN cache**, and **Browser cache**. Also, try visiting the front page of your website in **incognito/private** mode.
4. Make sure the server resources allocated to your site and WordPress installation meet our [Requirements](https://elementor.com/help/requirements/). 
    - To check this information go to your WordPress `Dashboard` > `Elementor` > `System info` [learn how to copy it here](https://elementor.com/help/hare-my-system-info/). We can't accept issues without it.

👎 If after following these steps the problem persists, you can submit a new issue with details to reproduce it so we can take a look.

Regards

**Comment by manuelwallrapp** [comment]
Same issue here as well.
