### ISSUE TITLE
CORS error not identified when using external live chat script (Odoo) in Chrome

### ISSUE THREAD

**Issue by mikeKstm** [elementor/elementor#21653]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi all! I have been able to reproduce this error on several servers and with different configurations. The error occurs using an external Odoo script that loads a livechat.  When sending a message through the livechat it gives an unknown CORS error. 
The error only occurs when Elementor is activated, if I deactivate the plugin it works correctly. 

Homepage
https://i.imgur.com/rRIYBB7.png

Error
https://i.imgur.com/2N7vQfZ.png

"Unknown CORS error
An unknown CORS error occurred. The error probably comes from a JavaScript file from a different source. (Opening your browser console may give you a clue about the error)."

Console error:
"Uncaught TypeError: Cannot read properties of undefined (reading 'trim')
    at Class._onKeydown (external_lib.js:5281:244)
    at HTMLInputElement.<anonymous> (external_lib.js:4322:11)
    at HTMLDivElement.dispatch (external_lib.js:1488:447)
    at elemData.handle (external_lib.js:1474:166)"

Disabling Elementor the script works correctly.

I don't know if this can happen with other external scripts or if it only happens with Odoo.

Thanks!

### Steps to reproduce

To fully reproduce the error it is necessary to create an Odoo trial account or use the following scripts from a demo I have created (14 days trial). I will try to keep the chat active as long as possible so that it is not necessary to create an account. https://www.odoo.com/trial

The error only occurs in Chrome, in Firefox it seems to work fine.

1) Add the following Odoo script in custom code in <head>
```
            <link rel="stylesheet" href="https://test1317.odoo.com/im_livechat/external_lib.css"/>
            <script type="text/javascript" src="https://test1317.odoo.com/im_livechat/loader/1"></script>
            <script type="text/javascript" src="https://test1317.odoo.com/im_livechat/external_lib.js"></script>
```
2) Go to the main page and send a message in livechat and you will get the CORS error.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.54 (Debian)
	MySQL version: mariadb.org binary distribution v10.11.2-MariaDB-1:10.11.2+maria~ubu2204
	PHP Version: 8.0.27
	PHP Memory Limit: 256M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 2G
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://domain.com
	Home URL: https://domain.com
	WP Multisite: No
	Max Upload Size: 2 GB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: es
	Timezone: 0
	Admin Email: info@domain.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: es_ES
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.11.5
		Author: Elementor.com

	Elementor Pro
		Version: 3.11.6
		Author: Elementor.com

	WPCode Lite
		Version: 2.0.8.1
		Author: WPCode

== Caracteristicas ==
	Custom Fonts: 0
	Custom Icons: 0

== Integraciones ==
	

== Experimentos de Elementor ==
	Salida del DOM optimizada: Inactivo
	Carga de recursos mejorada: Inactivo
	Carga de CSS mejorada: Inactivo
	Fuentes de iconos integradas: Inactivo
	Mejoras de accesibilidad: Inactivo
	Puntos de ruptura personalizados adicionales: Inactivo
	admin_menu_rearrangement: Inactivo por defecto
	Contenedor Flexbox: Inactivo
	Actualizar la librería Swiper: Inactivo
	Por defecto, el nuevo constructor de temas: Inactivo
	Cabecera y pie de página del tema Hello: Activo por defecto
	Editor V2: Inactivo por defecto
	Páginas de destino: Inactivo
	Elementos anidados: Inactivo
	Carga diferida de imágenes de fondo: Inactivo
	Guardar como por defecto: Inactivo
	Transiciones de páginas: Inactivo
	Notas: Inactivo
	Bucle: Inactivo
	Envíos de formulario: Inactivo
	Ajuste de scroll: Inactivo
	Mega Menu: Inactivo por defecto

== Registro ==
	
PHP: showing 2 of 2PHP: 2023-03-10 11:05:11 [warning X 2][/var/www/html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined array key &quot;data&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-14 09:02:40 [warning X 1][/var/www/html/wp-content/plugins/elementor/app/modules/import-export/module.php::629] Attempt to read property &quot;label&quot; on null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 20 of 242023-03-10 11:53:16 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.0',
  'to' => '3.11.4',
)]
2023-03-13 09:23:19 [info] elementor-pro::elementor_pro_updater Started 
2023-03-13 09:23:19 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-03-13 09:23:19 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-03-13 09:23:19 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.4',
  'to' => '3.11.5',
)]
2023-03-13 09:23:19 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.4',
  'to' => '3.11.5',
)]
2023-03-13 09:23:19 [info] elementor::elementor_updater Started 
2023-03-13 09:23:19 [info] Elementor/Upgrades - _on_each_version Start  
2023-03-13 09:23:19 [info] Elementor/Upgrades - _on_each_version Finished 
2023-03-13 09:23:19 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.3',
  'to' => '3.11.4',
)]
2023-03-13 09:23:19 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.3',
  'to' => '3.11.4',
)]
2023-03-14 08:40:10 [info] elementor::elementor_updater Started 
2023-03-14 08:40:10 [info] Elementor/Upgrades - _on_each_version Start  
2023-03-14 08:40:10 [info] Elementor/Upgrades - _on_each_version Finished 
2023-03-14 08:40:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.4',
  'to' => '3.11.5',
)]
2023-03-14 08:40:10 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.4',
  'to' => '3.11.5',
)]
2023-03-14 08:59:03 [info] elementor-pro::elementor_pro_updater Started 
2023-03-14 08:59:03 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-03-14 08:59:03 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-03-14 08:59:03 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.5',
  'to' => '3.11.6',
)]

JS: showing 2 of 2JS: 2023-03-14 09:14:18 [error X 3][https://domain.com/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:40879] Cannot create property &#039;guid&#039; on string &#039;c34widgetsticky&#039; 
JS: 2023-03-14 09:14:19 [error X 4][https://domain.com/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:40879] Cannot create property &#039;guid&#039; on string &#039;c4204widgetsticky&#039; 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

**Comment by mikeKstm** [comment]
I add more data:
The error does not occur using Chrome in incognito mode.

**Comment by bmzero** [comment]
Were you able to resolve this? I am getting the same error, but I do not use Elementor.
