### ISSUE TITLE
⛔ 🐞 Bug Report: Loop carousel changes z-index when sliding

### ISSUE THREAD

**Issue by ncasedk** [elementor/elementor#21656]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I'm using the loop carousel slider, but for some reason it doesn't respect the z-index when showing a slide the second time. First time works like a charm - most of the time, but the second one moves the image up front 🤥

I know it's only release candidate, but does anyone have a solution. It seems to work fine on Chrome and Opera browser, the main problem is with Safari. Same thing in Safari on iOS - even Chrome on iOS.

I've tried using the Testimonial slider but this results in the same issue.

It's in the hero section here: https://dennyopera.holycow.media

### Steps to reproduce

1. go to https://dennyopera.holycow.media (first section on the page)
2. Use the arrows to turn the slider - go forward and then backwards, and then the image will jump in front of the text, logo and menu-icon.
3. Problem is evident on Safari - both iOS and Mac, but it works on Chrome and Opera browsers.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.3.38
	PHP Version: 8.0.27
	PHP Memory Limit: 4097M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 2048M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://dennyopera.holycow.media
	Home URL: https://dennyopera.holycow.media
	WP Multisite: No
	Max Upload Size: 2 GB
	Memory limit: 40M
	Max Memory limit: 4097M
	Permalink Structure: /%postname%/
	Language: da-DK
	Timezone: Europe/Copenhagen
	Admin Email: ka@holycow.media
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.6.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: da_DK
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15

== Active Plugins ==
	Advanced Custom Fields
		Version: 6.0.7
		Author: WP Engine

	Advanced Custom Fields Multilingual
		Version: 1.10.4
		Author: OnTheGoSystems

	DynamicConditions
		Version: 1.6.0
		Author: RTO GmbH

	Elementor
		Version: 3.11.5
		Author: Elementor.com

	Elementor Pro
		Version: 3.11.6
		Author: Elementor.com

	Pods - Custom Content Types and Fields
		Version: 2.9.12.2
		Author: Pods Framework Team

	WPML Multilingual CMS
		Version: 4.6.0
		Author: OnTheGoSystems

	WPML String Translation
		Version: 3.2.4
		Author: OnTheGoSystems

	Yoast Duplicate Post
		Version: 4.5
		Author: Enrico Battocchi & Team Yoast


== Elements Usage ==
	
	header : 1
		icon : 1
		icon-list : 1
	popup : 1
		form : 1
		heading : 2
	section : 3
		heading : 4
		icon : 1
		icon-list : 1
		image : 1
	wp-page : 2
		button : 2
		form : 2
		heading : 24
		image-carousel : 4
		loop-carousel : 1
		loop-grid : 8
		star-rating : 6
		testimonial-carousel : 1
		text-editor : 6
	single-post : 1
		button : 2
		heading : 4
		text-editor : 3
		theme-post-content : 1
		theme-post-title : 1
	loop-item : 5
		button : 2
		heading : 9
		icon : 1
		icon-list : 2
		image : 3
		post-info : 1
		text-editor : 3
		theme-post-title : 4


== Indstillinger ==
	
	cpt_support: post, page
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap


== Funktioner ==
	Custom Fonts: 2
	Custom Icons: 0

== Integrationer ==
	


== Elementor Experiments ==
	Optimeret DOM-output: Inaktiv
	Forbedret ressourceindlæsning : Inaktiv
	Forbedret indlæsning af CSS ressourcer: Inaktiv
	Inline Font Icons: Inaktiv som standard
	Forbedringer af tilgængeligheden: Aktiv som standard
	Additional Custom Breakpoints: Aktiv som standard
	admin_menu_rearrangement: Inaktiv som standard
	Flexbox Container: Inaktiv som standard
	Upgrade Swiper Library: Aktiv
	Default to New Theme Builder: Aktiv som standard
	Hello sidehoved og sidefod: Aktiv som standard
	Editor V2: Inaktiv som standard
	Landingsside: Inaktiv
	Nested Elements: Inaktiv
	Lazy Load baggrundsbilleder: Inaktiv som standard
	Gem som standard: Aktiv
	Page Transitions: Inaktiv
	Notes: Inaktiv
	Loop: Aktiv
	Modtagne formularer: Aktiv
	Scroll Snap: Inaktiv
	Mega Menu: Inaktiv som standard


== Log ==
	
PHP: showing 10 of 10PHP: 2023-03-08 10:43:56 [warning X 11][/home/holycow/dennyopera.holycow.media/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::168] Undefined array key "editor_post_id" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-08 10:44:21 [error X 3][/home/holycow/dennyopera.holycow.media/wp-content/plugins/elementor-pro/modules/dynamic-tags/pods/tags/pods-date.php::29] Uncaught TypeError: strtotime(): Argument #1 ($datetime) must be of type string, array given in /home/holycow/dennyopera.holycow.media/wp-content/plugins/elementor-pro/modules/dynamic-tags/pods/tags/pods-date.php:29
Stack trace:
#0 /home/holycow/dennyopera.holycow.media/wp-content/plugins/elementor-pro/modules/dynamic-tags/pods/tags/pods-date.php(29): strtotime(Array)
#1 /home/holycow/dennyopera.holycow.media/wp-content/plugins/elementor/core/dynamic-tags/tag.php(35): ElementorPro\Modules\DynamicTags\Pods\Tags\Pods_Date->render()
#2 /home/holycow/dennyopera.holycow.media/wp-content/plugins/elementor/core/dynamic-tags/manager.php(216): Elementor\Core\DynamicTags\Tag->get_content()
#3 [internal function]: Elementor\Core\DynamicTags\Manager->get_tag_data_content('1b5ffd8', 'pods-date', Array)
#4 /home/holycow/dennyopera.holycow.media/wp-content/plugins/elementor/core/dynamic-tags/manager.php(109): call_user_func_array(Array, Array)
#5 /home/holycow/dennyopera.holycow.media/wp-content/plugins/elementor/core/dynamic-tags/manager.php(74): Elementor\Core\DynamicTags\Manager->parse_tag_text('[elementor-tag ...', Array, Array)
#6 [internal function]: Elementor\Core\DynamicTags\Manager->Elementor\Core\DynamicTags\{closure}(Array)
#7 /home/holycow/dennyopera.holycow.media/wp-content/plugins/elementor/core/dynamic-tags/manager.php(73): preg_replace_callback('/\\[elementor-ta...', Object(Closure), '[elementor-tag ...')
#8 /home/holycow/dennyopera.holycow.media/wp-content/plugins/elementor/includes/controls/base-data.php(91): Elementor\Core\DynamicTags\Manager->parse_tags_text('[elementor-tag ...', Array, Array)
#9 /home/holycow/dennyopera.holycow.media/wp-content/plugins/elementor/includes/base/controls-stack.php(1276): Elementor\Base_Data_Control->parse_tags('[elementor-tag ...', Array)
#10 /home/holycow/dennyopera.holycow.media/wp-content/plugins/elementor/includes/base/controls-stack.php(1255): Elementor\Controls_Stack->parse_dynamic_settings(Array, Array, Array)
#11 /home/holycow/dennyopera.holycow.media/wp-content/plugins/elementor/includes/base/controls-stack.php(1127): Elementor\Controls_Stack->parse_dynamic_settings(Array)
#12 /home/holycow/dennyopera.holycow.media/wp-content/plugins/elementor/core/files/css/post.php(298): Elementor\Controls_Stack->get_parsed_dynamic_settings()
#13 /home/holycow/dennyopera.holycow.media/wp-content/plugins/elementor/core/dynamic-tags/dynamic-css.php(32): Elementor\Core\Files\CSS\Post->render_styles(Object(Elementor\Widget_Icon_List))
#14 /home/holycow/dennyopera.holycow.media/wp-content/plugins/elementor/core/dynamic-tags/dynamic-css.php(36): Elementor\Core\DynamicTags\Dynamic_CSS->render_styles(Object(Elementor\Widget_Icon_List))
#15 /home/holycow/dennyopera.holycow.media/wp-content/plugins/elementor/core/dynamic-tags/dynamic-css.php(36): Elementor\Core\DynamicTags\Dynamic_CSS->render_styles(Object(Elementor\Element_Column))
#16 /home/holycow/dennyopera.holycow.media/wp-content/plugins/elementor/core/files/css/post.php(178): Elementor\Core\DynamicTags\Dynamic_CSS->render_styles(Object(Elementor\Element_Section))
#17 /home/holycow/dennyopera.holycow.media/wp-content/plugins/elementor/core/files/css/base.php(651): Elementor\Core\Files\CSS\Post->render_css()
#18 /home/holycow/dennyopera.holycow.media/wp-content/plugins/elementor/core/files/base.php(155): Elementor\Core\Files\CSS\Base->parse_content()
#19 /home/holycow/dennyopera.holycow.media/wp-content/plugins/elementor-pro/modules/loop-builder/skins/skin-loop-base.php(143): Elementor\Core\Files\Base->get_content()
#20 /home/holycow/dennyopera.holycow.media/wp-content/plugins/elementor-pro/modules/loop-builder/skins/skin-loop-base.php(129): ElementorPro\Modules\LoopBuilder\Skins\Skin_Loop_Base->print_dynamic_css(51, 17)
#21 /home/holycow/dennyopera.holycow.media/wp-content/plugins/elementor-pro/modules/posts/skins/skin-base.php(866): ElementorPro\Modules\LoopBuilder\Skins\Skin_Loop_Base->render_post()
#22 /home/holycow/dennyopera.holycow.media/wp-content/plugins/elementor-pro/modules/loop-builder/skins/skin-loop-base.php(84): ElementorPro\Modules\Posts\Skins\Skin_Base->render()
#23 /home/holycow/dennyopera.holycow.media/wp-content/plugins/elementor/includes/base/skin-base.php(79): ElementorPro\Modules\LoopBuilder\Skins\Skin_Loop_Base->render()
#24 /home/holycow/dennyopera.holycow.media/wp-content/plugins/elementor/includes/base/widget-base.php(607): Elementor\Skin_Base->render_by_mode()
#25 /home/holycow/dennyopera.holycow.media/wp-content/plugins/elementor/includes/base/widget-base.php(733): Elementor\Widget_Base->render_content()
#26 /home/holycow/dennyopera.holycow.media/wp-content/plugins/elementor/includes/base/element-base.php(536): Elementor\Widget_Base->get_raw_data(true)
#27 /home/holycow/dennyopera.holycow.media/wp-content/plugins/elementor/includes/base/element-base.php(536): Elementor\Element_Base->get_raw_data(true)
#28 /home/holycow/dennyopera.holycow.media/wp-content/plugins/elementor/core/base/document.php(966): Elementor\Element_Base->get_raw_data(true)
#29 /home/holycow/dennyopera.holycow.media/wp-content/plugins/elementor/core/base/document.php(632): Elementor\Core\Base\Document->get_elements_raw_data(Array, true)
#30 /home/holycow/dennyopera.holycow.media/wp-content/plugins/elementor/includes/base/controls-stack.php(1021): Elementor\Core\Base\Document->get_initial_config()
#31 /home/holycow/dennyopera.holycow.media/wp-content/plugins/elementor/core/editor/editor.php(383): Elementor\Controls_Stack->get_config()
#32 /home/holycow/dennyopera.holycow.media/wp-includes/class-wp-hook.php(308): Elementor\Core\Editor\Editor->enqueue_scripts('')
#33 /home/holycow/dennyopera.holycow.media/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#34 /home/holycow/dennyopera.holycow.media/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#35 /home/holycow/dennyopera.holycow.media/wp-includes/script-loader.php(2180): do_action('wp_enqueue_scri...')
#36 /home/holycow/dennyopera.holycow.media/wp-includes/class-wp-hook.php(308): wp_enqueue_scripts('')
#37 /home/holycow/dennyopera.holycow.media/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#38 /home/holycow/dennyopera.holycow.media/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#39 /home/holycow/dennyopera.holycow.media/wp-includes/general-template.php(3043): do_action('wp_head')
#40 /home/holycow/dennyopera.holycow.media/wp-content/plugins/elementor/includes/editor-templates/editor-wrapper.php(31): wp_head()
#41 /home/holycow/dennyopera.holycow.media/wp-content/plugins/elementor/core/editor/editor-loader.php(113): include('/home/holycow/d...')
#42 /home/holycow/dennyopera.holycow.media/wp-content/plugins/elementor/core/editor/editor.php(172): Elementor\Core\Editor\Editor_Loader->print_root_template()
#43 /home/holycow/dennyopera.holycow.media/wp-includes/class-wp-hook.php(308): Elementor\Core\Editor\Editor->init('')
#44 /home/holycow/dennyopera.holycow.media/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#45 /home/holycow/dennyopera.holycow.media/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#46 /home/holycow/dennyopera.holycow.media/wp-admin/admin.php(419): do_action('admin_action_el...')
#47 /home/holycow/dennyopera.holycow.media/wp-admin/post.php(12): require_once('/home/holycow/d...')
#48 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-08 11:37:34 [warning X 5][/home/holycow/dennyopera.holycow.media/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-08 11:37:34 [warning X 6][/home/holycow/dennyopera.holycow.media/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key "condition_type" [array (
  'trace' => '
#0: /home/holycow/dennyopera.holycow.media/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /home/holycow/dennyopera.holycow.media/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /home/holycow/dennyopera.holycow.media/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /home/holycow/dennyopera.holycow.media/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2023-03-08 11:37:35 [warning X 1][/home/holycow/dennyopera.holycow.media/wp-content/plugins/elementor-pro/modules/dynamic-tags/pods/tags/pods-base.php::35] Undefined array key "spilledato" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-13 10:11:04 [warning X 22][/home/holycow/dennyopera.holycow.media/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-color.php::34] Undefined array key 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-13 13:40:20 [warning X 507][/home/holycow/dennyopera.holycow.media/wp-content/plugins/elementor-pro/modules/dynamic-tags/pods/tags/pods-base.php::35] Undefined array key "spilleperiode" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-13 21:16:59 [warning X 1][/home/holycow/dennyopera.holycow.media/wp-content/plugins/elementor/app/modules/import-export/module.php::629] Attempt to read property "label" on null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-14 07:54:54 [notice X 1][/home/holycow/dennyopera.holycow.media/wp-content/plugins/elementor/includes/template-library/sources/local.php::747] ob_end_clean(): Failed to delete buffer. No buffer to delete [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-14 15:24:08 [error X 2][/home/holycow/dennyopera.holycow.media/wp-content/plugins/elementor-pro/modules/popup/module.php::122] Uncaught Error: Call to undefined method Elementor\Core\Kits\Documents\Kit::save_display_settings_data() in /home/holycow/dennyopera.holycow.media/wp-content/plugins/elementor-pro/modules/popup/module.php:122
Stack trace:
#0 [internal function]: ElementorPro\Modules\Popup\Module->save_display_settings(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#1 /home/holycow/dennyopera.holycow.media/wp-content/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/holycow/dennyopera.holycow.media/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#3 /home/holycow/dennyopera.holycow.media/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#4 /home/holycow/dennyopera.holycow.media/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#5 /home/holycow/dennyopera.holycow.media/wp-admin/admin-ajax.php(188): do_action('wp_ajax_element...')
#6 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 12 of 12JS: 2023-03-08 09:43:58 [error X 2][https://dennyopera.holycow.media/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.11.3:3:492611] null is not an object (evaluating 'elementor.documents.getCurrent().id') 
JS: 2023-03-09 09:24:03 [error X 2][https://dennyopera.holycow.media/wp-admin/load-scripts.php?c=1&loadchunk_0=jquery-core,jquery-migrate,underscore,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&loadchunk_1=hooks&ver=6.1.1:2:877] Can't create duplicate variable: '$dcWidgetIdInput' 
JS: 2023-03-09 10:01:49 [error X 1][https://dennyopera.holycow.media/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.11.3:2:19891] undefined is not an object (evaluating 'e.offset().top') 
JS: 2023-03-09 14:30:03 [error X 6][https://dennyopera.holycow.media/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.11.3:3:791668] undefined is not an object (evaluating 'this.store.find((function(T){return T.original===C})).localized') 
JS: 2023-03-09 14:40:51 [error X 3][https://dennyopera.holycow.media/wp-content/plugins/elementor-pro/assets/js/loop-carousel.e7d573cc61a4613d5eaa.bundle.min.js:2:3354] undefined is not an object (evaluating 'this.swiper.params') 
JS: 2023-03-09 15:48:07 [error X 1][https://dennyopera.holycow.media/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.11.3:3:622869] undefined is not an object (evaluating 'B.model') 
JS: 2023-03-13 08:27:02 [error X 1][https://dennyopera.holycow.media/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.11.4:3:931388] undefined is not an object (evaluating 'T.settings') 
JS: 2023-03-13 08:38:46 [error X 16][https://dennyopera.holycow.media/wp-admin/load-scripts.php?c=1&loadchunk_0=jquery-core,jquery-migrate,underscore,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&loadchunk_1=hooks&ver=6.1.1:2:51823] undefined is not an object (evaluating 'a.replace') 
JS: 2023-03-13 09:43:09 [error X 1][https://dennyopera.holycow.media/wp-content/plugins/elementor/assets/js/admin.min.js?ver=3.11.4:2:10991] undefined is not an object (evaluating 'this.getExperimentSelect(e).value=t') 
JS: 2023-03-13 14:37:23 [error X 1][https://dennyopera.holycow.media/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.11.4:3:127446] undefined is not an object (evaluating 'C.match') 
JS: 2023-03-14 07:05:44 [error X 454][https://dennyopera.holycow.media/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:40874] Attempted to assign to readonly property. 
JS: 2023-03-14 15:03:28 [error X 1][https://dennyopera.holycow.media/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.11.4:3:670951] this.model.isValidChild is not a function. (In 'this.model.isValidChild(C)', 'this.model.isValidChild' is undefined) 

Log: showing 20 of 202023-03-12 19:29:58 [info] elementor::elementor_updater Started 
2023-03-12 19:29:58 [info] Elementor/Upgrades - _on_each_version Start  
2023-03-12 19:29:58 [info] Elementor/Upgrades - _on_each_version Finished 
2023-03-12 19:29:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.3',
  'to' => '3.11.4',
)]
2023-03-12 19:29:58 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.3',
  'to' => '3.11.4',
)]
2023-03-13 11:10:34 [info] elementor-pro::elementor_pro_updater Started 
2023-03-13 11:10:34 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-03-13 11:10:34 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-03-13 11:10:34 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.4',
  'to' => '3.11.5',
)]
2023-03-13 11:10:34 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.4',
  'to' => '3.11.5',
)]
2023-03-14 19:05:25 [info] elementor-pro::elementor_pro_updater Started 
2023-03-14 19:05:25 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-03-14 19:05:25 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-03-14 19:05:25 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.5',
  'to' => '3.11.6',
)]
2023-03-14 19:05:25 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.5',
  'to' => '3.11.6',
)]
2023-03-14 19:05:25 [info] elementor::elementor_updater Started 
2023-03-14 19:05:25 [info] Elementor/Upgrades - _on_each_version Start  
2023-03-14 19:05:25 [info] Elementor/Upgrades - _on_each_version Finished 
2023-03-14 19:05:25 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.4',
  'to' => '3.11.5',
)]
2023-03-14 19:05:25 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.4',
  'to' => '3.11.5',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Kompatibel

== Elementor Pro - Compatibility Tag ==
	

				
````

</details>

**Comment by ncasedk** [comment]
Okay. Realized that Safari was the culprit, and apparently it has a problem with respecting z-index values. I've "hacked" a solution adding this to CSS and giving the elements that should appear on top of the image the class "element"

#element{
   -webkit-transform: translate3d(0,0,0);
   z-index: 999;
}

**Comment by nicholaszein** [comment]
Hello @ncasedk,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
It appears you are using the `Position: Absolute` for a few Elements inside your Loop Carousel template. When you change the position to absolute, elements that are added after the absolute positioned element will always appear in front of it. If you want them to appear before, you must increase the `z-index`. So it's not just Safari, but this is happening everywhere. 

### ✅ What you can do to solve your issue:
Your fix was correct. You needed to increase the `z-index` of the other elements that were placed before the one you wanted to show in the back, or simply use a negative `z-index` (-1 would be enough) for the image you wanted to be placed behind.

Also, just a heads up. You shouldn't use the same CSS ID for multiple elements. This is invalid HTML and will cause many issues for people who use assistive tools or have accessibility needs. For multiple elements always use CSS classes. You also don't need to use custom CSS if you don't want to. There is an option to change the z-index of each element in the Advanced tab.

![image](https://user-images.githubusercontent.com/113993460/230436460-fa581691-8d82-4fac-af06-43a77a86992b.png)



### 👍 For now, that's all we can help with. 

This is more of a support question, not something we can help you with here.

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
