### ISSUE TITLE
The Global value you are trying to use is not available.

### ISSUE THREAD

**Issue by jamieburchell** [elementor/elementor#21665]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

If you apply global typography to "Site Settings" > "Footer" > "Copyright text", then delete that global typography from "Global Fonts", the "Clear" option on the Color Picker under "Global Typography" produces the following error message and the action does not work:

`The Global value you are trying to use is not available.`

This is especially troublesome if you have also disabled the Headers and Footers experiment and have no idea that elements within it are/were referring to the deleted global typography. This happened to me after importing an Elementor Kit and removing some global typography and disabling the Headers and Footers experiment (the kit had custom headers and footers in the theme builder).

### Steps to reproduce

1. Make sure Headers and Footers experiment is on (it was by default for me)
2. Define a new global typography
3. Apply it to the copyright text in the "Footer" area under "Site Settings"
4. Delete the global typography
5. Disable the Headers and Footers experiment (possibly optional)
6. Try to clear the colour of e.g. body text colour in "Site Settings" > "Typography"

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

```

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.5.16
	PHP Version: 8.0.28
	PHP Memory Limit: 256M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 50M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: There are some writing permissions issues with the following directories/files:
		 - WordPress root directory
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://REDACTED/wp
	Home URL: https://REDACTED
	WP Multisite: No
	Max Upload Size: 40 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-GB
	Timezone: Europe/London
	Admin Email: REDACTED
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36

== Active Plugins ==
	Code Snippets
		Version: 3.3.0
		Author: Code Snippets Pro

	Converter for Media
		Version: 5.8.3
		Author: matt plugins

	Elementor
		Version: 3.11.5
		Author: Elementor.com

	Elementor Pro
		Version: 3.11.6
		Author: Elementor.com

	Pods - Custom Content Types and Fields
		Version: 2.9.12.2
		Author: Pods Framework Team

	Rank Math SEO
		Version: 1.0.110
		Author: Rank Math

	W3 Total Cache
		Version: 2.3.0
		Author: BoldGrid

	Wordfence Security
		Version: 7.9.1
		Author: Wordfence


== Must-Use Plugins ==
	Bedrock Autoloader
		Version: 1.0.3
		Author: Roots

	Disable status tests
		Version: 1.0.0
		Author: Roots

	Register Theme Directory
		Version: 1.0.0
		Author: Roots


== Features ==
	Custom Fonts: 1
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Optimised DOM Output: Active by default
	Improved asset loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility improvements: Active by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Editor V2: Inactive by default
	Landing pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default
	Save as Default: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Mega Menu: Inactive by default


== Log ==
	
PHP: showing 9 of 9PHP: 2023-02-10 11:01:17 [error X 1][/var/www/vhosts/REDACTED/releases/4/web/app/plugins/elementor/app/modules/import-export/module.php::401] Uncaught Error: no-write-permissionsin - wp_content in /var/www/vhosts/REDACTED/releases/4/web/app/plugins/elementor/app/modules/import-export/module.php:401
Stack trace:
#0 /var/www/vhosts/REDACTED/releases/4/web/app/plugins/elementor/app/modules/import-export/module.php(245): Elementor\App\Modules\ImportExport\Module-&gt;ensure_writing_permissions()
#1 /var/www/vhosts/REDACTED/releases/4/web/app/plugins/elementor/app/modules/import-export/module.php(499): Elementor\App\Modules\ImportExport\Module-&gt;upload_kit(&#039;/var/www/vhosts...&#039;, &#039;kit-library&#039;)
#2 /var/www/vhosts/REDACTED/releases/4/web/app/plugins/elementor/app/modules/import-export/module.php(443): Elementor\App\Modules\ImportExport\Module-&gt;handle_upload_kit()
#3 /var/www/vhosts/REDACTED/releases/4/web/app/plugins/elementor/app/modules/import-export/module.php(375): Elementor\App\Modules\ImportExport\Module-&gt;maybe_handle_ajax()
#4 /var/www/vhosts/REDACTED/releases/4/web/wp/wp-includes/class-wp-hook.php(308): Elementor\App\Modules\ImportExport\Module-&gt;Elementor\App\Modules\ImportExport\{closure}(&#039;&#039;)
#5 /var/www/vhosts/REDACTED/releases/4/web/wp/wp-includes/class-wp-hook.php(332): WP_Hook-&gt;apply_filters(NULL, Array)
#6 /var/www/vhosts/REDACTED/releases/4/web/wp/wp-includes/plugin.php(517): WP_Hook-&gt;do_action(Array)
#7 /var/www/vhosts/REDACTED/releases/4/web/wp/wp-admin/admin-ajax.php(45): do_action(&#039;admin_init&#039;)
#8 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-10 11:01:52 [warning X 28][/var/www/vhosts/REDACTED/releases/4/web/app/plugins/elementor/core/common/modules/ajax/module.php::172] Undefined array key &quot;data&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-10 11:02:34 [notice X 1][/var/www/vhosts/REDACTED/releases/4/web/app/plugins/elementor/core/utils/import-export/parsers/wxr-parser-simple-xml.php::53] Function libxml_disable_entity_loader() is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-10 11:05:36 [warning X 27][/var/www/vhosts/REDACTED/releases/4/web/app/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-15 12:53:09 [error X 1][/var/www/vhosts/REDACTED/releases/7/web/app/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::295] Uncaught Error: Call to a member function update_meta() on bool in /var/www/vhosts/REDACTED/releases/7/web/app/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:295
Stack trace:
#0 /var/www/vhosts/REDACTED/releases/7/web/app/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(168): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /var/www/vhosts/REDACTED/releases/7/web/app/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /var/www/vhosts/REDACTED/releases/7/web/wp/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module-&gt;handle_ajax_request(&#039;&#039;)
#4 /var/www/vhosts/REDACTED/releases/7/web/wp/wp-includes/class-wp-hook.php(332): WP_Hook-&gt;apply_filters(&#039;&#039;, Array)
#5 /var/www/vhosts/REDACTED/releases/7/web/wp/wp-includes/plugin.php(517): WP_Hook-&gt;do_action(Array)
#6 /var/www/vhosts/REDACTED/releases/7/web/wp/wp-admin/admin-ajax.php(188): do_action(&#039;wp_ajax_element...&#039;)
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-15 12:56:30 [warning X 10][/var/www/vhosts/REDACTED/releases/7/web/app/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key &quot;condition_type&quot; [array (
  'trace' => '
#0: /var/www/vhosts/REDACTED/releases/7/web/app/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /var/www/vhosts/REDACTED/releases/7/web/app/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /var/www/vhosts/REDACTED/releases/7/web/app/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /var/www/vhosts/REDACTED/releases/7/web/app/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2023-03-15 13:08:58 [warning X 1][/var/www/vhosts/REDACTED/releases/7/web/app/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::168] Undefined array key &quot;editor_post_id&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-15 14:17:48 [error X 1][/var/www/vhosts/REDACTED/releases/7/web/app/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::295] Uncaught Error: Call to a member function update_meta() on null in /var/www/vhosts/REDACTED/releases/7/web/app/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:295
Stack trace:
#0 /var/www/vhosts/REDACTED/releases/7/web/app/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(168): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;save_conditions(8, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /var/www/vhosts/REDACTED/releases/7/web/app/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /var/www/vhosts/REDACTED/releases/7/web/wp/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module-&gt;handle_ajax_request(&#039;&#039;)
#4 /var/www/vhosts/REDACTED/releases/7/web/wp/wp-includes/class-wp-hook.php(332): WP_Hook-&gt;apply_filters(&#039;&#039;, Array)
#5 /var/www/vhosts/REDACTED/releases/7/web/wp/wp-includes/plugin.php(517): WP_Hook-&gt;do_action(Array)
#6 /var/www/vhosts/REDACTED/releases/7/web/wp/wp-admin/admin-ajax.php(188): do_action(&#039;wp_ajax_element...&#039;)
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-15 14:36:48 [error X 2][/var/www/vhosts/REDACTED/releases/7/web/app/plugins/elementor/app/modules/import-export/module.php::401] Uncaught Error: no-write-permissionsin - wp_content in /var/www/vhosts/REDACTED/releases/7/web/app/plugins/elementor/app/modules/import-export/module.php:401
Stack trace:
#0 /var/www/vhosts/REDACTED/releases/7/web/app/plugins/elementor/app/modules/import-export/module.php(330): Elementor\App\Modules\ImportExport\Module-&gt;ensure_writing_permissions()
#1 /var/www/vhosts/REDACTED/releases/7/web/app/plugins/elementor/app/modules/import-export/module.php(567): Elementor\App\Modules\ImportExport\Module-&gt;export_kit(Array)
#2 /var/www/vhosts/REDACTED/releases/7/web/app/plugins/elementor/app/modules/import-export/module.php(439): Elementor\App\Modules\ImportExport\Module-&gt;handle_export_kit()
#3 /var/www/vhosts/REDACTED/releases/7/web/app/plugins/elementor/app/modules/import-export/module.php(375): Elementor\App\Modules\ImportExport\Module-&gt;maybe_handle_ajax()
#4 /var/www/vhosts/REDACTED/releases/7/web/wp/wp-includes/class-wp-hook.php(308): Elementor\App\Modules\ImportExport\Module-&gt;Elementor\App\Modules\ImportExport\{closure}(&#039;&#039;)
#5 /var/www/vhosts/REDACTED/releases/7/web/wp/wp-includes/class-wp-hook.php(332): WP_Hook-&gt;apply_filters(NULL, Array)
#6 /var/www/vhosts/REDACTED/releases/7/web/wp/wp-includes/plugin.php(517): WP_Hook-&gt;do_action(Array)
#7 /var/www/vhosts/REDACTED/releases/7/web/wp/wp-admin/admin-ajax.php(45): do_action(&#039;admin_init&#039;)
#8 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 5 of 5JS: 2023-02-10 11:28:00 [error X 1][https://REDACTED/wp/wp-admin/load-scripts.php?c=0&amp;loadchunk_0=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&amp;loadchunk_1=hooks&amp;ver=6.1.1:4:51824] Cannot read properties of undefined (reading &#039;replace&#039;) 
JS: 2023-03-15 12:22:01 [error X 3][https://REDACTED/app/plugins/elementor/assets/js/editor.min.js?ver=3.11.5:3:907724] Cannot read properties of undefined (reading &#039;route&#039;) 
JS: 2023-03-15 12:51:32 [error X 2][https://REDACTED/app/plugins/elementor-pro/assets/js/editor.min.js?ver=3.11.6:2:61340] Cannot read properties of undefined (reading &#039;createTemplate&#039;) 
JS: 2023-03-15 12:53:30 [error X 1][https://REDACTED/app/plugins/elementor/assets/js/editor.min.js?ver=3.11.5:3:1087291] Cannot read properties of null (reading &#039;getBoundingClientRect&#039;) 
JS: 2023-03-15 14:57:50 [error X 1][https://REDACTED/app/plugins/elementor/assets/js/editor.min.js?ver=3.11.5:3:719506] Cannot read properties of undefined (reading &#039;widgets_settings&#039;) 

Log: showing 8 of 82023-03-15 10:28:42 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.2',
  'to' => '3.11.5',
)]
2023-03-15 10:28:43 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.10.3',
  'to' => '3.11.6',
)]
2023-03-15 10:28:44 [info] elementor-pro::elementor_pro_updater Started 
2023-03-15 10:28:44 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-03-15 10:28:44 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-03-15 10:28:44 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.10.3',
  'to' => '3.11.6',
)]
2023-03-15 10:28:44 [info] Elementor/Upgrades - _on_each_version Finished 
2023-03-15 10:28:44 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.2',
  'to' => '3.11.5',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==
	

```

**Comment by nicholaszein** [comment]
Hello @jamieburchell! 

Thank you for submitting your issue! 🙏 

Please allow us some time to investigate it, and get back to you with our findings. 🧐 

🏷️ This issue has been labeled and will be forwarded to the team for validation and possible solution. Please keep in mind that we can't provide any ETA on when this issue could be fixed if it is validated. We ask for patience.

Best regards
