### ISSUE TITLE
Design not looking correct

### ISSUE THREAD

**Issue by vzionmedia** [elementor/elementor#21714]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

layout and design  not being published correctly.

### Steps to reproduce

Make a change to the design using elementor. 
save and publish
Changes are not showing on the front end

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.54 (Debian)
	MySQL version: mariadb.org binary distribution v10.4.20
	PHP Version: 7.4.27
	PHP Memory Limit: 256M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://gomborestaurant.com
	Home URL: https://gomborestaurant.com
	WP Multisite: No
	Max Upload Size: 100 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/New_York
	Admin Email: info@vzionmedia.com
	Debug Mode: Inactive

== Theme ==
	Name: Grand Restaurant
	Version: 6.7.3
	Author: ThemeGoods
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Product Fields for WooCommerce
		Version: 1.6
		Author: StudioWombat

	All-in-One WP Migration
		Version: 7.72
		Author: ServMask

	All in One SEO
		Version: 4.3.3
		Author: All in One SEO Team

	Breeze
		Version: 2.0.18
		Author: Cloudways

	Classic Widgets
		Version: 0.3
		Author: WordPress Contributors

	Coming Soon Chop Chop
		Version: 2.2.4
		Author: Chop-Chop.org

	Contact Form 7
		Version: 5.7.4
		Author: Takayuki Miyoshi

	Contact Form 7 Multilingual
		Version: 1.2.1
		Author: OnTheGoSystems

	Custom Fonts
		Version: 1.3.7
		Author: Brainstorm Force

	Duplicate Page
		Version: 4.5.1
		Author: mndpsingh287

	Elementor
		Version: 3.11.0
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Google Map Extended
		Version: 1.2.3
		Author: InternetCSS

	Elementor Pro
		Version: 3.11.6
		Author: Elementor.com

	Envato Market
		Version: 2.0.8
		Author: Envato

	Grand Restaurant Theme Custom Post Type
		Version: 3.8.4
		Author: ThemeGoods

	Grand Restaurant Theme Elements for Elementor
		Version: 1.8
		Author: ThemGoods

	Jetpack
		Version: 11.9.1
		Author: Automattic

	MailChimp for WordPress Multilingual
		Version: 0.0.3
		Author: OnTheGoSystems

	MalCare WordPress Security Plugin - Malware Scanner, Cleaner, Security Firewall
		Version: 4.86
		Author: MalCare Security

	MC4WP: Mailchimp for WordPress
		Version: 4.9.1
		Author: ibericode

	One Click Demo Import
		Version: 3.1.2
		Author: OCDI

	Simple Google reCAPTCHA
		Version: 4.0
		Author: Michal Novák

	Site Kit by Google
		Version: 1.96.0
		Author: Google

	Slider Revolution
		Version: 6.6.8
		Author: ThemePunch

	WooCommerce
		Version: 7.5.0
		Author: Automattic

	WooCommerce Food
		Version: 3.1.6
		Author: Ex-Themes

	WooCommerce Food Order Calendar
		Version: 1.0.2
		Author: Ex-Themes

	WooCommerce Multilingual & Multicurrency
		Version: 5.1.2
		Author: OnTheGoSystems

	WooCommerce Shipping & Tax
		Version: 2.2.4
		Author: WooCommerce

	WooCommerce Stripe Gateway
		Version: 7.2.0
		Author: WooCommerce

	WPForms Lite
		Version: 1.8.0.2
		Author: WPForms

	WPML Multilingual CMS
		Version: 4.6.1
		Author: OnTheGoSystems

	WPML String Translation
		Version: 3.2.4
		Author: OnTheGoSystems

== Must-Use Plugins ==
	Object Cache Pro (MU)
		Version: 1.18.0
		Author: Rhubarb Group

== Elements Usage ==
	
	section : 1
		heading : 3
		icon : 4
		spacer : 1
	widget : 0
		button : 1
	wp-post : 0
		button : 1
		grandrestaurant-navigation-menu : 4
		heading : 9
		icon-list : 11
		image : 21
		social-icons : 5
		text-editor : 2
	wp-page : 15
		button : 2
		grandrestaurant-animated-text : 3
		grandrestaurant-food-menu : 3
		grandrestaurant-gallery-justified : 6
		grandrestaurant-gallery-preview : 1
		heading : 17
		icon : 4
		shortcode : 2
		slider_revolution : 4
		spacer : 2
		text-editor : 7

== Settings ==
	
	cpt_support: post, page, product, galleries, menus, testimonials, team, pricing, header, footer, megamenu, fullmenu
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap

== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	
	woocommerce: Active

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active
	Default to New Theme Builder: Active
	Editor V2: Inactive by default
	Landing Pages: Active
	Nested Elements: Active
	Lazy Load Background Images: Active
	Save as Default: Active
	Page Transitions: Active
	Notes: Active
	Loop: Active
	Form Submissions: Active
	Scroll Snap: Active
	Mega Menu: Active by default

== Log ==
	
Log: showing 20 of 282023-03-01 16:46:11 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.1',
  'to' => '3.11.3',
)]
2023-03-01 16:46:13 [info] elementor-pro::elementor_pro_updater Started 
2023-03-01 16:46:13 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-03-01 16:46:13 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-03-01 16:46:13 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.1',
  'to' => '3.11.3',
)]
2023-03-13 08:42:48 [info] elementor-pro::elementor_pro_updater Started 
2023-03-13 08:42:48 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-03-13 08:42:48 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-03-13 08:42:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.3',
  'to' => '3.11.5',
)]
2023-03-13 08:42:48 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.3',
  'to' => '3.11.5',
)]
2023-03-16 15:06:23 [info] elementor-pro::elementor_pro_updater Started 
2023-03-16 15:06:23 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-03-16 15:06:23 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-03-16 15:06:23 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.5',
  'to' => '3.11.6',
)]
2023-03-16 15:06:23 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.5',
  'to' => '3.11.6',
)]
2023-03-18 13:47:22 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.0-dev4',
  'to' => '3.13.0-dev2',
)]
2023-03-18 13:47:22 [info] elementor::elementor_updater Started 
2023-03-18 13:47:22 [info] Elementor/Upgrades - _on_each_version Start  
2023-03-18 13:47:23 [info] Elementor/Upgrades - _on_each_version Finished 
2023-03-18 13:47:23 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.0-dev4',
  'to' => '3.13.0-dev2',
)]

PHP: showing 3 of 3PHP: 2023-02-20 16:31:41 [notice X 5][/home/855737.cloudwaysapps.com/qawnfbewza/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-13 16:16:56 [notice X 9][/home/855737.cloudwaysapps.com/qawnfbewza/public_html/wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-20 21:01:40 [error X 4][/home/855737.cloudwaysapps.com/qawnfbewza/public_html/wp-content/plugins/elementor-pro/modules/mega-menu/widgets/mega-menu.php::17] Uncaught Error: Class 'Elementor\Modules\NestedElements\Base\Widget_Nested_Base' not found in /home/855737.cloudwaysapps.com/qawnfbewza/public_html/wp-content/plugins/elementor-pro/modules/mega-menu/widgets/mega-menu.php:17
Stack trace:
#0 /home/855737.cloudwaysapps.com/qawnfbewza/public_html/wp-content/plugins/elementor-pro/plugin.php(159): include()
#1 [internal function]: ElementorPro\Plugin->autoload()
#2 /home/855737.cloudwaysapps.com/qawnfbewza/public_html/wp-content/plugins/elementor/core/base/module.php(325): spl_autoload_call()
#3 /home/855737.cloudwaysapps.com/qawnfbewza/public_html/wp-includes/class-wp-hook.php(308): Elementor\Core\Base\Module->init_widgets()
#4 /home/855737.cloudwaysapps.com/qawnfbewza/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#5 /home/855737.cloudwaysapps.com/qawnfbewza/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#6 /home/855737.cloudwaysapps.com/qawnfbewza/public_html/wp-content/plugins/elementor/includes/managers/widgets.php(119) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 11 of 11JS: 2023-03-01 20:00:07 [error X 9][https://woocommerce-855737-3189850.cloudwaysapps.com/wp-content/plugins/elementor/assets/js/frontend-modules.min.js:2:4825] Cannot read properties of undefined (reading 'attributes') 
JS: 2023-03-03 05:34:28 [error X 21][https://woocommerce-855737-3189850.cloudwaysapps.com/wp-content/plugins/elementor/assets/js/frontend.min.js:2:22339] The superclass is not a constructor. 
JS: 2023-03-13 20:44:30 [error X 2][https://woocommerce-855737-3189850.cloudwaysapps.com/wp-content/plugins/elementor/assets/js/editor.min.js:3:794636] Cannot read properties of undefined (reading 'localized') 
JS: 2023-03-14 06:10:13 [error X 12][https://woocommerce-855737-3189850.cloudwaysapps.com/wp-content/plugins/elementor/assets/js/editor.min.js:3:572273] Element type not found: 'container' 
JS: 2023-03-16 17:14:44 [error X 14][https://woocommerce-855737-3189850.cloudwaysapps.com/wp-content/plugins/elementor/assets/js/common-modules.min.js:2:54646] Model.isValidChild() should be implemented, please provide 'isValidChild' functionality. 
JS: 2023-03-16 21:33:45 [error X 4][https://woocommerce-855737-3189850.cloudwaysapps.com/wp-content/plugins/elementor/assets/js/editor.min.js:3:937592] undefined is not an object (evaluating 'this.container.view') 
JS: 2023-03-18 17:44:10 [error X 3][https://woocommerce-855737-3189850.cloudwaysapps.com/wp-content/plugins/elementor-pro/assets/js/editor.min.js:2:61411] Object.entries requires that input parameter not be null or undefined 
JS: 2023-03-20 01:42:45 [error X 1][https://gomborestaurant.com/wp-content/plugins/elementor/assets/js/editor.min.js:3:572138] Element type not found: 'grandrestaurant-gallery-justified' 
JS: 2023-03-20 02:15:23 [error X 3][https://gomborestaurant.com/wp-content/plugins/elementor-pro/assets/js/editor.min.js:2:61404] Cannot convert undefined or null to object 
JS: 2023-03-21 00:47:30 [error X 42][https://gomborestaurant.com/wp-content/plugins/elementor/assets/js/import-export-admin.min.js:2:5394] elementorImportExport is not defined 
JS: 2023-03-21 01:05:33 [error X 2][https://gomborestaurant.com/wp-content/plugins/elementor/assets/js/editor.min.js:3:561262] Cannot read properties of undefined (reading 'editorPreferences') 

== Elementor - Compatibility Tag ==
	
	Elementor Google Map Extended: Compatibility not specified
	Elementor Pro: Compatible
	Grand Restaurant Theme Elements for Elementor: Incompatible

== Elementor Pro - Compatibility Tag ==

**Comment by myekstarcy** [comment]
Pls i have same problem over 3 days now with no sleep,try to figure out why.i have played around with every setting on wordpress including elementor.Have downgraded from v3.12 to v3.7 which still doesnt help.The painful thing is ,the moment you opened a template to edit with elementor,the page u edited will never display correctly again.I have log-load of website to finsh but i can proceed because non publish correctly irregardless of template i use,provided its elementor-edited template. pls anyone with urgent solution will be appreciated
