### ISSUE TITLE
📚 ❓ API Question: Sending data to GA from new record hook returns parserror

### ISSUE THREAD

**Issue by hkalkhalifa** [elementor/elementor#21803]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I’m trying to execute a script inside elementor_pro/forms/new_record but I’m getting parse error, I tried resetting the response after executing the script but all I get is the script sent as a response and it doesn’t get executed anyway I can achieve this ?

```php

// Sending data to GA
//add_action( 'elementor_pro/forms/new_record', 'pass_data_to_GA', 10, 2);

function pass_data_to_GA( $record, $handler ) {
    //make sure its our form
    $form_settings = $record->get('form_settings');
    $form_id = $form_settings['form_id'];

    $raw_fields = $record->get( 'fields' );
    $fields = [];
    foreach ( $raw_fields as $id => $field ) {
        $fields[ $id ] = $field['value'];
    }

    $name = $fields['name'];
    $email = $fields['email'];
    $fullno = $fields['phone'];

    error_log(json_encode($name));

    ?>
    <script>
        if(jQuery("div.elementor-message-success").length)
        {
        // window.dataLayer = window.dataLayer || [];
        //     window.dataLayer.push({
        //     event: "formSubmission",
        //     formID: <?php echo $form_id;?>,
        //     fullName: <?php echo $name;?>,
        //     phone: <?php echo $fullno;?>,
        //     email: <?php echo $email;?>,
        //     });
            console.log("test")
        // submit an event to Google Analytics
        ga('send', 'event', <?php echo $form_id;?> , 'Submit');
        }
    </script>
    <?php

    $handler = null;
    $response = "The form was sent successfully.";
    $handler->is_success = true; 
    $handler->add_response_data(true, $response);

    return $handler;
}
````

### Steps to reproduce

By adding the above code to the functions.php

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v8.0.31
	PHP Version: 8.1.10
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 80M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: There are some writing permissions issues with the following directories/files:
		 - .htaccess file
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://preprod.darglobal.co.uk
	Home URL: https://preprod.darglobal.co.uk
	WP Multisite: No
	Max Upload Size: 80 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: digitizeitservices@gmail.com
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 6.0.5
		Author: WP Engine

	Bluehost
		Version: 2.12.13
		Author: Bluehost

	Checkout Field Editor for WooCommerce
		Version: 1.8.0
		Author: ThemeHigh

	Contact Form 7
		Version: 5.7.3
		Author: Takayuki Miyoshi

	Country & Phone Field Contact Form 7
		Version: 2.4.2
		Author: Narinder Singh Bisht

	Creative Mail by Newfold Digital
		Version: 1.6.5
		Author: Newfold Digital

	Custom Spinner for Contact Form 7
		Version: 2.0.1
		Author: Peter Raschendorfer

	Duplicator
		Version: 1.5.1
		Author: Snap Creek

	Ele Custom Skin
		Version: 3.1.7
		Author: Dudaster.com

	Ele Custom Skin Pro
		Version: 3.2.4
		Author: Dudaster.com

	Elementor
		Version: 3.8.1
		Author: Elementor.com

	Elementor Forms GSheetConnector
		Version: 1.0.4
		Author: GSheetConnector

	Elementor Pro
		Version: 3.8.0
		Author: Elementor.com

	File Manager Advanced
		Version: 5.0.1
		Author: modalweb

	Filter Everything PRO
		Version: 1.7.0
		Author: Andrii Stepasiuk

	GeoTargetingWP
		Version: 3.4.2.2
		Author: Timersys

	Interactive Geo Maps PRO
		Version: 1.5.7.2
		Author: Carlos Moreira

	PayTabs - WooCommerce Payment Gateway
		Version: 4.16.1
		Author: PayTabs

	Post Types Order
		Version: 1.9.9.2
		Author: Nsp Code

	Premium Addons for Elementor
		Version: 4.9.40
		Author: Leap13

	Premium Addons PRO
		Version: 2.8.13
		Author: Leap13

	Redirection for Contact Form 7
		Version: 2.7.0
		Author: Qube One

	Simple Custom CSS and JS
		Version: 3.41
		Author: SilkyPress.com

	Smart Slider 3
		Version: 3.5.1.12
		Author: Nextend

	Snazzy Maps
		Version: 1.4.0
		Author: Snazzy Maps

	WooCommerce
		Version: 7.1.0
		Author: Automattic

	WooCommerce Misha Payment Gateway Backup
		Version: 1.0.1
		Author: Misha Rudastyh

	WooCommerce Multilingual & Multicurrency
		Version: 5.1.2
		Author: OnTheGoSystems

	WooCommerce Tap Payment Gateway
		Version: 2.0
		Author: Waqas Zeeshan

	WPCode Lite
		Version: 2.0.5
		Author: WPCode

	WP Go Maps (formerly WP Google Maps)
		Version: 9.0.13
		Author: WP Go Maps

	WP Go Maps - Pro Add-on
		Version: 9.0.9
		Author: WP Google Maps

	WP Mail SMTP Pro
		Version: 3.7.0
		Author: WPForms

	WP Migrate Lite
		Version: 2.5.0
		Author: Delicious Brains

	WPML Multilingual CMS
		Version: 4.5.14
		Author: OnTheGoSystems

	WPML String Translation
		Version: 3.2.3
		Author: OnTheGoSystems

	WP Popups Lite
		Version: 2.1.4.6
		Author: timersys

	Yoast SEO
		Version: 19.11
		Author: Team Yoast


== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

	SSO
		Version: 0.2
		Author: Garth Mortensen, Mike Hansen


== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active
	Import Export Website Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Inactive
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default


== Log ==
	
JS: showing 20 of 20JS: 2023-01-16 13:33:44 [error X 5][https://preprod.darglobal.co.uk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.1:3:550109] Element type not found: \'premium-addon-tabs\' 
JS: 2023-01-17 06:57:27 [error X 177][https://preprod.darglobal.co.uk/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:51824] Cannot read properties of undefined (reading \'replace\') 
JS: 2023-01-19 21:42:07 [error X 2][https://preprod.darglobal.co.uk/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.8.0:3:99294] Cannot convert undefined or null to object 
JS: 2023-01-20 12:32:12 [error X 22][https://preprod.darglobal.co.uk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.1:3:610312] Cannot read properties of undefined (reading \'isDesignable\') 
JS: 2023-02-22 13:51:27 [error X 1][https://preprod.darglobal.co.uk/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view191097\") has already been destroyed and cannot be used. 
JS: 2023-02-22 13:51:27 [error X 1][https://preprod.darglobal.co.uk/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view191099\") has already been destroyed and cannot be used. 
JS: 2023-02-23 07:39:01 [error X 12][https://preprod.darglobal.co.uk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.1:3:1061530] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2023-02-24 06:45:24 [error X 2][https://preprod.darglobal.co.uk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.1:3:768952] Cannot read properties of undefined (reading \'toLowerCase\') 
JS: 2023-02-24 07:09:09 [error X 3][https://preprod.darglobal.co.uk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.1:3:295940] Cannot read properties of undefined (reading \'html\') 
JS: 2023-02-28 05:52:16 [error X 1][https://preprod.darglobal.co.uk/wp-content/plugins/elementor-pro/assets/lib/sticky/jquery.sticky.min.js?ver=3.8.0:1:1186] Failed to execute \'getComputedStyle\' on \'Window\': parameter 1 is not of type \'Element\'. 
JS: 2023-03-03 09:35:46 [error X 6][https://preprod.darglobal.co.uk/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view58057\") has already been destroyed and cannot be used. 
JS: 2023-03-03 09:58:45 [error X 8][https://preprod.darglobal.co.uk/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.8.1:2:14029] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `image` got as `image` value. Expected array or object.',
)]
JS: 2023-03-03 11:38:34 [error X 1][https://preprod.darglobal.co.uk/wp-content/plugins/oldpremium-addons-for-elementor/assets/editor/js/premium-cross-cp.js?ver=4.9.40:13:23] Cannot read properties of null (reading \'elecode\') 
JS: 2023-03-15 07:01:26 [error X 23][https://preprod.darglobal.co.uk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.1:3:634181] elementorFrontend.elements.window.jQuery is not a function 
JS: 2023-03-15 07:01:26 [error X 2][https://code.jquery.com/jquery-3.1.1.min.js:4:21901] Cannot read properties of null (reading \'clientHeight\') 
JS: 2023-03-15 07:01:32 [error X 10][https://preprod.darglobal.co.uk/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.8.1:2:4825] Cannot read properties of undefined (reading \'attributes\') 
JS: 2023-03-15 07:27:05 [error X 1][https://preprod.darglobal.co.uk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.1:3:726261] Cannot read properties of null (reading \'config\') 
JS: 2023-03-15 07:27:20 [error X 1][https://preprod.darglobal.co.uk/wp-admin/post.php?post=30106&action=elementor:7:51] Cannot read properties of undefined (reading \'tabs\') 
JS: 2023-03-16 15:57:40 [error X 155][https://code.jquery.com/jquery-3.1.1.min.js:3:8190] Cannot create property \'guid\' on string \'c6507widgetsticky\' 
JS: 2023-03-24 11:37:50 [error X 2][https://code.jquery.com/jquery-3.1.1.min.js:4:21901] Cannot read properties of null (reading \'clientWidth\') 

PHP: showing 20 of 22PHP: 2023-01-16 13:40:01 [warning X 1][/opt/bitnami/apache/htdocs/wp-content/plugins/elementor/core/files/uploads-manager.php::257] unlink(/opt/bitnami/apache/htdocs/wp-content/uploads/elementor/tmp/63c553b12e0c3): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-16 13:40:20 [warning X 1][/opt/bitnami/apache/htdocs/wp-content/plugins/elementor/core/files/uploads-manager.php::257] unlink(/opt/bitnami/apache/htdocs/wp-content/uploads/elementor/tmp/63c553c4f18f2): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-16 14:01:31 [warning X 1][/opt/bitnami/apache/htdocs/wp-content/plugins/elementor/core/files/uploads-manager.php::257] unlink(/opt/bitnami/apache/htdocs/wp-content/uploads/elementor/tmp/63c558bba8d87): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-17 05:32:27 [warning X 1][/opt/bitnami/apache/htdocs/wp-content/plugins/elementor/core/files/uploads-manager.php::257] unlink(/opt/bitnami/apache/htdocs/wp-content/uploads/elementor/tmp/63c632eb864da): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-17 07:41:15 [warning X 1][/opt/bitnami/apache/htdocs/wp-content/plugins/elementor/core/files/base.php::194] file_put_contents(/opt/bitnami/apache/htdocs/wp-content/uploads/elementor/css/post-1216.css): Failed to open stream: Permission denied [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-19 12:06:59 [error X 1][/opt/bitnami/apache/htdocs/wp-content/plugins/elementor/includes/template-library/sources/local.php::1080] Uncaught TypeError: Elementor\TemplateLibrary\Source_Local::on_save_post(): Argument #2 ($post) must be of type WP_Post, null given, called in /opt/bitnami/apache/htdocs/wp-includes/class-wp-hook.php on line 310 and defined in /opt/bitnami/apache/htdocs/wp-content/plugins/elementor/includes/template-library/sources/local.php:1080
Stack trace:
#0 /opt/bitnami/apache/htdocs/wp-includes/class-wp-hook.php(310): Elementor\TemplateLibrary\Source_Local->on_save_post()
#1 /opt/bitnami/apache/htdocs/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#2 /opt/bitnami/apache/htdocs/wp-includes/plugin.php(517): WP_Hook->do_action()
#3 /opt/bitnami/apache/htdocs/wp-includes/post.php(4717): do_action()
#4 /opt/bitnami/apache/htdocs/wp-includes/post.php(4819): wp_insert_post()
#5 /opt/bitnami/apache/htdocs/wp-content/plugins/elementor/includes/db.php(235): wp_update_post()
#6 /opt/bitnami/apache/htdocs/wp-content/plugins/elementor/core/base/document.php(1222): Elementor\DB->save_plain_text()
#7 /opt/bitnami/apache/htdocs/wp-content/plugins/elementor/core/base/document.php(742): Elementor\Core\Base\Document->save_elements()
#8 /opt/bitnami/apache/htdocs/wp-content/plugins/elementor/core/documents-manager.php(527): Elementor\Core\Base\Document->save()
#9 [internal function]: Elementor\Core\Documents_Manager->ajax_save()
#10 /opt/bitnami/apache/htdocs/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func()
#11 /opt/bitnami/apache/htdocs/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#12 /opt/bitnami/apache/htdocs/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#13 /opt/bitnami/apache/htdocs/wp-includes/plugin.php(517): WP_Hook->do_action()
#14 /opt/bitnami/apache/htdocs/wp-admin/admin-ajax.php(188): do_action()
#15 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-20 11:32:39 [warning X 1][/opt/bitnami/apache/htdocs/wp-content/plugins/elementor-pro/modules/forms/classes/ajax-handler.php::270] Undefined array key "post_id" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-25 10:31:25 [warning X 1][/opt/bitnami/apache/htdocs/wp-content/plugins/elementor/core/files/base.php::194] file_put_contents(/opt/bitnami/apache/htdocs/wp-content/uploads/elementor/css/post-2902.css): Failed to open stream: Permission denied [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-30 12:36:26 [warning X 1][/opt/bitnami/apache/htdocs/wp-content/plugins/elementor-pro/modules/posts/skins/skin-content-base.php::264] Attempt to read property "ID" on null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-02 13:22:25 [warning X 2][/opt/bitnami/apache/htdocs/wp-content/plugins/elementor/core/files/base.php::194] file_put_contents(/opt/bitnami/apache/htdocs/wp-content/uploads/elementor/css/post-4790.css): Failed to open stream: Permission denied [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-15 08:09:14 [notice X 1][/opt/bitnami/apache/htdocs/wp-content/plugins/elementor-pro/modules/woocommerce/module.php::553] parse_str(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-15 08:10:54 [notice X 250][/opt/bitnami/apache/htdocs/wp-content/plugins/elementor-pro/modules/custom-css/module.php::76] trim(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-24 07:12:10 [notice X 69][/opt/bitnami/apache/htdocs/wp-content/plugins/elementor-pro/license/updater.php::84] version_compare(): Passing null to parameter #2 ($version2) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-24 13:37:00 [warning X 24][/opt/bitnami/apache/htdocs/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-24 13:37:02 [warning X 44][/opt/bitnami/apache/htdocs/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key "condition_type" [array (
  'trace' => '
#0: /opt/bitnami/apache/htdocs/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /opt/bitnami/apache/htdocs/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /opt/bitnami/apache/htdocs/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /opt/bitnami/apache/htdocs/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2023-03-03 09:33:42 [notice X 1][/opt/bitnami/apache/htdocs/wp-content/plugins/elementor/includes/managers/image.php::97] Automatic conversion of false to array is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-14 12:32:35 [error X 2][/opt/bitnami/apache/htdocs/wp-content/plugins/elementor/includes/base/widget-base.php::176] Maximum execution time of 30 seconds exceeded [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-16 15:41:35 [notice X 9][/opt/bitnami/apache/htdocs/wp-content/plugins/elementor-pro/modules/custom-css/module.php::76] trim(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /opt/bitnami/apache/htdocs/wp-content/plugins/elementor-pro/modules/custom-css/module.php(76): class type trim()
#2: /opt/bitnami/apache/htdocs/wp-includes/class-wp-hook.php(308): ElementorPro\Modules\CustomCss\Module -> add_page_settings_css()
#3: /opt/bitnami/apache/htdocs/wp-includes/class-wp-hook.php(332): WP_Hook -> apply_filters()
#4: /opt/bitnami/apache/htdocs/wp-includes/plugin.php(517): WP_Hook -> do_action()
',
)]
PHP: 2023-03-20 07:31:51 [warning X 6][/opt/bitnami/apache/htdocs/wp-content/plugins/elementor/core/editor/editor.php::121] Cannot modify header information - headers already sent by (output started at /opt/bitnami/apache/htdocs/wp-content/plugins/wp-google-maps-pro/includes/custom-fields/class.custom-map-object-fields.php:10) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-24 11:39:03 [warning X 40][/opt/bitnami/apache/htdocs/wp-content/plugins/elementor/includes/db.php::267] foreach() argument must be of type array|object, string given [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Forms GSheetConnector: Compatibility not specified
	Elementor Pro: Compatibility not specified
	Premium Addons for Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==
	

				

````

</details>

**Comment by nicholaszein** [comment]
Hello @hkalkhalifa,

You are trying to run an action on the frontend, but executing a hook in the server. I believe that you need to add your script to the `wp_head()`, or `wp_body_end()` to make your GA script work.


This is more of a support question, not really something we can answer here.

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Regards,

Nick
