### ISSUE TITLE
⛔ 🐞 Bug Report: HTML WIDGET ISSUE IN ELEMENTOR

### ISSUE THREAD

**Issue by rbrns23** [elementor/elementor#21825]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Good day everyone,
I would appreciate a little help. We are trying to insert a custom code using the Elementor builder but getting an error. 
We are trying to insert a calendar snippet using a code HTML element in Elementor, but when we look at the live website, the calendar is not showing. It is in the first template but not in the other two.
Any insights? Thank you in advance
![screencapture-hotelhollyatx-wp-admin-post-php-2023-03-14-14_34_52](https://user-images.githubusercontent.com/129320148/228643464-3942494e-d8a2-4819-8145-dd25771e7d45.png)
![screencapture-hotelhollyatx-properties-2023-03-14-14_34_40](https://user-images.githubusercontent.com/129320148/228643478-803212c1-96e9-46ce-a584-7b65770f213f.png)

### Steps to reproduce

we need to have the calendar showing on the website

### Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release rel5.7, Revision 26 v5.7.26-29
	PHP Version: 8.0.27
	PHP Memory Limit: 256M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://hotelhollyatx.com
	Home URL: https://hotelhollyatx.com
	WP Multisite: No
	Max Upload Size: 100 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: info@virtualwaresolutions.com
	Debug Mode: Inactive

== Theme ==
	Name: Astra
	Version: 4.1.2
	Author: Brainstorm Force
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36

== Active Plugins ==
	CoBlocks
		Version: 3.0.2
		Author: GoDaddy

	Elementor
		Version: 3.12.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.11.7
		Author: Elementor.com

	Header Footer Code Manager
		Version: 1.1.32
		Author: 99robots

	Meta pixel for WordPress
		Version: 3.0.8
		Author: Facebook

	Sucuri Security - Auditing, Malware Scanner and Hardening
		Version: 1.8.37
		Author: Sucuri Inc.

	Zapier for WordPress
		Version: 1.0.4
		Author: Zapier


== Must-Use Plugins ==
	Object Cache Pro (MU)
		Version: 1.18.0
		Author: Rhubarb Group

	System Plugin
		Version: 4.68.1
		Author: 


== Elements Usage ==
	
	footer : 1
		button : 1
		form : 1
		heading : 5
		icon-list : 1
		image : 1
		nav-menu : 1
		social-icons : 1
		text-editor : 1
	header : 1
		button : 1
		image : 1
		nav-menu : 1
	popup : 2
		form : 1
		heading : 1
		icon : 1
		spacer : 1
		text-editor : 1
	section : 5
		heading : 8
		media-carousel : 3
		spacer : 6
	wp-page : 5
		button : 4
		call-to-action : 2
		gallery : 1
		google_maps : 1
		heading : 22
		html : 1
		icon-list : 4
		image : 4
		image-carousel : 1
		slides : 1
		social-icons : 1
		spacer : 2
		star-rating : 3
		testimonial-carousel : 3
		text-editor : 5
	error-404 : 1
		button : 1
		heading : 3
		social-icons : 1
		spacer : 3
		star-rating : 3
		testimonial-carousel : 3


== Settings ==
	
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Upgrade Swiper Library: Inactive by default
	Default to New Theme Builder: Active by default
	Editor Top Bar: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Mega Menu: Inactive by default


== Log ==
	
Log: showing 20 of 402023-03-14 09:38:21 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.4',
  'to' => '3.11.5',
)]
2023-03-14 09:38:21 [info] elementor::elementor_updater Started 
2023-03-14 09:38:21 [info] Elementor/Upgrades - _on_each_version Start  
2023-03-14 09:38:21 [info] Elementor/Upgrades - _on_each_version Finished 
2023-03-14 09:38:21 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.4',
  'to' => '3.11.5',
)]
2023-03-14 17:53:56 [info] elementor-pro::elementor_pro_updater Started 
2023-03-14 17:53:56 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-03-14 17:53:56 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-03-14 17:53:56 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.5',
  'to' => '3.11.6',
)]
2023-03-14 17:53:56 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.5',
  'to' => '3.11.6',
)]
2023-03-28 01:52:12 [info] elementor-pro::elementor_pro_updater Started 
2023-03-28 01:52:12 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-03-28 01:52:12 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-03-28 01:52:12 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.6',
  'to' => '3.11.7',
)]
2023-03-28 01:52:12 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.6',
  'to' => '3.11.7',
)]
2023-03-29 07:10:41 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.5',
  'to' => '3.12.0',
)]
2023-03-29 07:10:41 [info] elementor::elementor_updater Started 
2023-03-29 07:10:41 [info] Elementor/Upgrades - _on_each_version Start  
2023-03-29 07:10:42 [info] Elementor/Upgrades - _on_each_version Finished 
2023-03-29 07:10:42 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.5',
  'to' => '3.12.0',
)]

PHP: showing 2 of 2PHP: 2023-03-13 17:35:48 [warning X 3][/var/www/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-13 21:09:02 [error X 1][/var/www/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::295] Uncaught Error: Call to a member function update_meta() on bool in /var/www/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:295
Stack trace:
#0 /var/www/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(168): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /var/www/wp-content/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /var/www/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /var/www/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#5 /var/www/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /var/www/wp-admin/admin-ajax.php(188): do_action('wp_ajax_element...')
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 1 of 1JS: 2023-03-13 20:28:35 [error X 6][https://hotelhollyatx.com/wp-admin/load-scripts.php?c=0&loadchunk_0=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&loadchunk_1=hooks&ver=6.1.1:4:51824] Cannot read properties of undefined (reading 'replace') 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Incompatible

== Elementor Pro - Compatibility Tag ==
	

				

````

</details>

**Comment by nicholaszein** [comment]
Hello @rbrns23,

Thanks for contacting us! 🙏 

This is more of a support question, not really something we can answer here.

It is likely your code snippet might be missing something, is being sanitized by WordPress, or might be conflicting with the Elementor Editor.

In this case, it would be better if you used a plugin like [Code Snippets](https://wordpress.org/plugins/code-snippets/) to add your snippet as a [Shortcode](https://codex.wordpress.org/Shortcode_API), or use a plugin like [Shortcodes Ultimate](https://wordpress.org/plugins/shortcodes-ultimate/) instead. Make sure to read [this article](https://elementor.com/help/known-plugin-conflicts/) to understand the conflicts between Elementor and the Shortcodes Ultimate plugin.

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Regards,

Nick
