### ISSUE TITLE
LOOP Carousel - Not active product link

### ISSUE THREAD

**Issue by shumy92** [elementor/elementor#21857]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I've create a loop carousel in elementor for products. At the beggining was everything ok. After few hours products are not linkable

<img width="1198" alt="image" src="https://user-images.githubusercontent.com/41359647/228870446-25fd8e48-6d55-411a-92c9-9396470642cc.png">

### Steps to reproduce

1) go to home page https://www.gioiacasahome.it/
2) go down to "Novità" section

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.7.41
	PHP Version: 7.4.33
	PHP Memory Limit: 512M
	PHP Max Input Vars: 16000
	PHP Max Post Size: 130M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2
	Site URL: https://www.gioiacasahome.it
	Home URL: https://www.gioiacasahome.it
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: it-IT
	Timezone: Europe/Rome
	Admin Email: nicola.994@live.it
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child - AnimusLAB
	Version: 0.1.4
	Author: AnimusLAB
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.6.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: it_IT
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 6.0.3
		Author: WP Engine

	All-in-One WP Migration
		Version: 7.71
		Author: ServMask

	Catch Infinite Scroll
		Version: 2.0.4
		Author: Catch Plugins

	CookieYes | GDPR Cookie Consent
		Version: 3.0.5
		Author: CookieYes

	Elementor
		Version: 3.12.0
		Author: Elementor.com

	Elementor Header & Footer Builder
		Version: 1.6.13
		Author: Brainstorm Force, Nikhil Chavan

	Elementor Pro
		Version: 3.12.0
		Author: Elementor.com

	Facebook for WooCommerce
		Version: 2.6.29
		Author: Facebook

	FiboSearch - AJAX Search for WooCommerce
		Version: 1.20.0
		Author: FiboSearch Team

	J Cart Upsell and Cross-sell for WooCommerce
		Version: 2.8.0
		Author: Giacomo Zoffoli

	JetMenu
		Version: 2.1.8
		Author: Crocoblock

	Joinchat
		Version: 4.5.11
		Author: Creame

	Klarna Payments for WooCommerce
		Version: 2.12.1
		Author: krokedil, klarna, automattic

	Menu Duplicator
		Version: 0.6
		Author: Jeremy Ross

	Payment Plugins Braintree For WooCommerce
		Version: 3.2.41
		Author: Payment Plugins, support@paymentplugins.com

	Phlox Portfolio
		Version: 2.3.1
		Author: averta

	PixelYourSite
		Version: 9.2.1
		Author: PixelYourSite

	Plugins Garbage Collector (Database Cleanup) Old!
		Version: 0.14
		Author: Vladimir Garagulya

	Premmerce Permalink Manager for WooCommerce
		Version: 2.3.7
		Author: premmerce

	Product Carousel Slider & Grid Ultimate for WooCommerce
		Version: 1.9.2
		Author: wpWax

	Redirection
		Version: 5.3.5
		Author: John Godley

	Smash Balloon Instagram Feed
		Version: 6.1
		Author: Smash Balloon

	Translate Words
		Version: 1.2.4
		Author: Ben Gillbanks

	WooCommerce
		Version: 7.0.1
		Author: Automattic

	WooCommerce Cart Abandonment Recovery
		Version: 1.2.20
		Author: CartFlows Inc

	Wordfence Security
		Version: 7.7.1
		Author: Wordfence

	WPCode Lite
		Version: 2.0.8.1
		Author: WPCode

	WP Mail SMTP
		Version: 3.6.1
		Author: WPForms

	WP Rocket
		Version: 3.12.2.1
		Author: WP Media

	YellowPencil Pro
		Version: 7.5.7
		Author: WaspThemes

	YITH Infinite Scrolling
		Version: 1.7.0
		Author: YITH

	YITH WooCommerce Ajax Product Filter Premium
		Version: 4.20.1
		Author: YITH

	YITH WooCommerce Badge Management
		Version: 2.11.0
		Author: YITH

	Yoast SEO
		Version: 19.10
		Author: Team Yoast

== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	
	woocommerce: Active

== Esperimenti Elementor ==
	Uscita DOM ottimizzata: Attivo per impostazione predefinita
	Caricamento delle risorse migliorato: Attivo per impostazione predefinita
	Caricamento CSS migliorato: Attivo per impostazione predefinita
	Icone dei font in linea: Inattivo per impostazione predefinita
	Miglioramenti dell'accessibilità: Attivo per impostazione predefinita
	Punti di interruzione aggiuntivi: Attivo per impostazione predefinita
	admin_menu_rearrangement: Inattivo per impostazione predefinita
	Contenitore Flexbox: Attiva
	Upgrade Swiper Library: Inattivo per impostazione predefinita
	Default to New Theme Builder: Attivo per impostazione predefinita
	Header e Footer del tema Hello: Attivo per impostazione predefinita
	Editor Top Bar: Attiva
	Landing Page: Attivo per impostazione predefinita
	Nested Elements: Attiva
	Lazy Load Background Images: Inattivo per impostazione predefinita
	Page Transitions: Attivo per impostazione predefinita
	Notes: Attivo per impostazione predefinita
	Loop: Attivo per impostazione predefinita
	Scroll Snap: Attivo per impostazione predefinita
	Menu: Attiva

== Registro ==
	
Log: showing 20 of 242022-11-08 10:15:10 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Finished 
2022-11-08 10:15:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.8',
  'to' => '3.8.0',
)]
2022-11-08 10:15:12 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.8',
  'to' => '3.8.0',
)]
2023-01-10 11:59:32 [error] Save submission failed, db error: Errore database WordPress: elaborazione del valore per il seguente campo non riuscita: referer. Il valore fornito potrebbe essere troppo lungo o contenere dati non validi. 
2023-03-30 12:06:43 [info] elementor::elementor_updater Started 
2023-03-30 12:06:43 [info] Elementor/Upgrades - _on_each_version Start  
2023-03-30 12:06:43 [info] Elementor/Upgrades - _on_each_version Finished 
2023-03-30 12:06:43 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Start  
2023-03-30 12:06:43 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Finished 
2023-03-30 12:06:43 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0',
  'to' => '3.12.0',
)]
2023-03-30 12:06:51 [info] elementor::elementor_updater Started 
2023-03-30 12:06:51 [info] Elementor/Upgrades - _on_each_version Start  
2023-03-30 12:06:51 [info] Elementor/Upgrades - _on_each_version Finished 
2023-03-30 12:06:51 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0',
  'to' => '3.12.0',
)]
2023-03-30 12:06:51 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0',
  'to' => '3.12.0',
)]
2023-03-30 12:11:04 [info] elementor-pro::elementor_pro_updater Started 
2023-03-30 12:11:04 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-03-30 12:11:04 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-03-30 12:11:04 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.3',
  'to' => '3.12.0',
)]
2023-03-30 12:11:04 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.3',
  'to' => '3.12.0',
)]

JS: showing 8 of 8JS: 2022-11-24 10:50:56 [error X 1][https://www.gioiacasahome.it/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.0:3:768952] Cannot read properties of undefined (reading \'toLowerCase\') 
JS: 2023-01-09 18:22:01 [error X 3][https://www.gioiacasahome.it/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.0:3:595617] J is not a constructor 
JS: 2023-02-13 16:01:12 [error X 2][https://www.gioiacasahome.it/wp-includes/js/jquery/jquery.min.js?ver=3.6.0:2:31703] elementor_new_template_form_controls is not defined 
JS: 2023-03-03 18:15:12 [error X 1][https://www.gioiacasahome.it/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.0:3:1061530] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2023-03-10 09:10:03 [error X 10][https://www.gioiacasahome.it/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.0:3:769459] Cannot read properties of undefined (reading \'localized\') 
JS: 2023-03-30 09:56:27 [error X 1][https://www.gioiacasahome.it/wp-content/plugins/elementor/assets/js/admin-top-bar.min.js?ver=3.12.0:2:7838] ReactDOM is not defined 
JS: 2023-03-30 12:21:22 [error X 2][https://www.gioiacasahome.it/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.12.0:3:410136] Cannot read properties of null (reading 'history') 
JS: 2023-03-30 12:21:47 [error X 1][https://www.gioiacasahome.it/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.12.0:3:594206] Cannot read properties of null (reading 'id') 

PHP: showing 10 of 10PHP: 2022-11-24 13:08:05 [error X 2][/home/lngwebb/gioiacasa/www/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on bool in /home/lngwebb/gioiacasa/www/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /home/lngwebb/gioiacasa/www/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/lngwebb/gioiacasa/www/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/lngwebb/gioiacasa/www/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/lngwebb/gioiacasa/www/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#5 /home/lngweb [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-29 14:26:13 [notice X 274][/home/lngwebb/gioiacasa/www/wp-content/plugins/elementor/includes/controls/groups/base.php::497] Array to string conversion [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-30 12:11:02 [error X 1][/home/lngwebb/gioiacasa/www/wp-content/plugins/elementor-pro/core/modules-manager.php::74] Uncaught Error: Class '\ElementorPro\Modules\QueryControl\Module' not found in /home/lngwebb/gioiacasa/www/wp-content/plugins/elementor-pro/core/modules-manager.php:74
Stack trace:
#0 /home/lngwebb/gioiacasa/www/wp-content/plugins/elementor-pro/plugin.php(357): ElementorPro\Core\Modules_Manager->__construct()
#1 /home/lngwebb/gioiacasa/www/wp-includes/class-wp-hook.php(308): ElementorPro\Plugin->on_elementor_init('')
#2 /home/lngwebb/gioiacasa/www/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#3 /home/lngwebb/gioiacasa/www/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /home/lngwebb/gioiacasa/www/wp-content/plugins/elementor/includes/plugin.php(658): do_action('elementor/init')
#5 /home/lngwebb/gioiacasa/www/wp-includes/class-wp-hook.php(308): Elementor\Plugin->init('')
#6 /home/lngwebb/gioiacasa/www/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#7 /home/lngwebb/gioiacasa/www/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#8 /home/lngwebb/ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-30 12:11:02 [error X 1][/home/lngwebb/gioiacasa/www/wp-content/plugins/elementor-pro/modules/woocommerce/widgets/base-widget.php::43] Uncaught Error: Class 'ElementorPro\Modules\Woocommerce\Classes\Products_Renderer' not found in /home/lngwebb/gioiacasa/www/wp-content/plugins/elementor-pro/modules/woocommerce/widgets/base-widget.php:43
Stack trace:
#0 /home/lngwebb/gioiacasa/www/wp-content/plugins/elementor-pro/modules/woocommerce/widgets/products.php(128): ElementorPro\Modules\Woocommerce\Widgets\Base_Widget->add_columns_responsive_control()
#1 /home/lngwebb/gioiacasa/www/wp-content/plugins/elementor-pro/modules/woocommerce/widgets/archive-products.php(35): ElementorPro\Modules\Woocommerce\Widgets\Products->register_controls()
#2 /home/lngwebb/gioiacasa/www/wp-content/plugins/elementor/includes/base/controls-stack.php(2329): ElementorPro\Modules\Woocommerce\Widgets\Archive_Products->register_controls()
#3 /home/lngwebb/gioiacasa/www/wp-content/plugins/elementor/includes/base/controls-stack.php(496): Elementor\Controls_Stack->init_controls()
#4 /home/lngwebb/gioiacasa/www/wp-content/plugins/elementor/includes/base/widget-base.php(177): Elem [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-30 12:11:03 [error X 1][/home/lngwebb/gioiacasa/www/wp-content/plugins/elementor-pro/plugin.php::465] Uncaught Error: Class 'ElementorPro\Core\Connect\Manager' not found in /home/lngwebb/gioiacasa/www/wp-content/plugins/elementor-pro/plugin.php:465
Stack trace:
#0 /home/lngwebb/gioiacasa/www/wp-content/plugins/elementor-pro/plugin.php(121): ElementorPro\Plugin->__construct()
#1 /home/lngwebb/gioiacasa/www/wp-content/plugins/elementor-pro/plugin.php(508): ElementorPro\Plugin::instance()
#2 /home/lngwebb/gioiacasa/www/wp-content/plugins/elementor-pro/elementor-pro.php(63): require('/home/lngwebb/g...')
#3 /home/lngwebb/gioiacasa/www/wp-includes/class-wp-hook.php(308): elementor_pro_load_plugin('')
#4 /home/lngwebb/gioiacasa/www/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#5 /home/lngwebb/gioiacasa/www/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /home/lngwebb/gioiacasa/www/wp-settings.php(486): do_action('plugins_loaded')
#7 /home/lngwebb/gioiacasa/www/wp-config.php(103): require_once('/home/lngwebb/g...')
#8 /home/lngwebb/gioiacasa/www/wp-load.php(50): require_once('/ho [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-30 12:35:34 [notice X 10][/home/lngwebb/gioiacasa/www/wp-content/plugins/elementor-pro/modules/woocommerce/classes/products-renderer.php::150] Trying to get property 'taxonomy' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-30 12:51:09 [notice X 3][/home/lngwebb/gioiacasa/www/wp-content/plugins/elementor/includes/conditions.php::87] Undefined index: checkout_layout [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-30 14:20:34 [notice X 7][/home/lngwebb/gioiacasa/www/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-30 14:28:32 [notice X 12][/home/lngwebb/gioiacasa/www/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined index: condition_type [array (
  'trace' => '
#0: /home/lngwebb/gioiacasa/www/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /home/lngwebb/gioiacasa/www/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /home/lngwebb/gioiacasa/www/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /home/lngwebb/gioiacasa/www/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2023-03-30 16:06:17 [notice X 1][/home/lngwebb/gioiacasa/www/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::168] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Header & Footer Builder: Incompatibile
	Elementor Pro: Incompatibile

== Elementor Pro - Compatibility Tag ==
	
	Elementor Header & Footer Builder: Incompatibile

**Comment by shumy92** [comment]
I've already add a button to have a possibility to work with products, but other elements (like photo etc.) aren't linkable.

**Comment by nicholaszein** [comment]
Hello @shumy92, 

Thank you for submitting your report! 🙏 

### ❌ While reviewing your report, we noticed it was missing some key pieces of information:

- 👣 **Steps to replicate:** Think of it as explaining to someone over the phone how to replicate your issue. They can't see the problem, so explain it in detail in a way that we can try to replicate your issue in our own environments. Be thorough.

- 🗑️ **Clear the cache:** Always clear the cache after any update (WordPress, Theme, Plugins, Posts, and Pages). This includes but is not limited to server cache, site cache, CDN cache, and browser cache.

Check the video below, and let me know if you added links to both the product featured image, and the product title.


https://user-images.githubusercontent.com/113993460/229165674-aa0f199d-d6ab-4891-8a5a-59f46998ea80.mp4



### 🧐 Please provide the missing information above so we can troubleshoot your issue faster and better.

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

Please follow the guidelines for opening a new [🐞 Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml), so we can help you better.

Best regards,

Nick
