### ISSUE TITLE
🐞 🐘 Bug Report: Elementor crash after upgrade to PHP8

### ISSUE THREAD

**Issue by danbalaban** [elementor/elementor#21908]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

After upgrading PHP from 7.4 to 8.0 i'm not able to access the editor due to a critical error crash. 

The WP Engine error logs gives this:

PHP Fatal error:  Uncaught TypeError: in_array(): Argument #2 ($haystack) must be of type array, null given in /nas/content/live/sitehidden/wp-content/plugins/elementor/includes/conditions.php:46\nStack trace:\n#0 /nas/content/live/sitehidden/wp-content/plugins/elementor/includes/conditions.php(46): in_array('viewport_tablet', NULL, true)\n#1 /nas/content/live/sitehidden/wp-content/plugins/elementor/includes/conditions.php(99): Elementor\\Conditions::compare(NULL, 'viewport_tablet', 'contains')\n#2 /nas/content/live/sitehidden/wp-content/plugins/elementor/includes/base/controls-stack.php(1385): Elementor\\Conditions::check(Array, Array)\n#3 /nas/content/live/sitehidden/wp-content/plugins/elementor/includes/base/controls-stack.
2:36 pm
php(1171): Elementor\\Controls_Stack->is_control_visible(Array, Array)\n#4 /nas/content/live/sitehidden/wp-content/plugins/elementor/includes/base/controls-stack.php(1212): Elementor\\Controls_Stack->get_active_settings(Array, Array)\n#5 /nas/content/live/sitehidden/wp-content/plugins/analogwp-templates/inc/elementor/globals/class-colors.php(22): Elementor\\Controls_Stack->get_settings_for_display('system_colors')\n#6 /nas/content/live/sitehidden/wp-content/plugins/elementor/core/editor/data/globals/endpoints/base.php(31)

### Steps to reproduce

1. Upgrade PHP7.4 to PHP8.0
2. Go to WordPress and open a page with Elementor
3. Critical error appears

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>Click to reveal</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release '43', Revision 'c1b94a6cfd7' v5.7.40-43
	PHP Version: 8.0.28
	PHP Memory Limit: 512M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2
	Site URL: https://sitehidden.com
	Home URL: https://sitehidden.com
	WP Multisite: No
	Max Upload Size: 50 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/New_York
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.0
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.7.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36

== Active Plugins ==
	Agile Store Locator
		Version: 4.8.26
		Author: AGILELOGIX

	Better Search Replace
		Version: 1.4.2
		Author: WP Engine

	Classic Editor
		Version: 1.6.3
		Author: WordPress Contributors

	Elementor
		Version: 3.12.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.12.1
		Author: Elementor.com

	Enable Media Replace
		Version: 4.1.0
		Author: ShortPixel

	Gravity Forms
		Version: 2.7.3
		Author: Gravity Forms

	Header Footer Code Manager
		Version: 1.1.32
		Author: 99robots

	JetEngine
		Version: 3.1.3.1
		Author: Crocoblock

	Make Column Clickable Elementor
		Version: 1.4.0
		Author: Fernando Acosta

	Simple Custom Post Order
		Version: 2.5.6
		Author: Colorlib

	Style Kits for Elementor
		Version: 2.0.1
		Author: AnalogWP

	Style Kits Pro
		Version: 2.0.1
		Author: AnalogWP

	Ultimate Addons for Elementor
		Version: 1.36.14
		Author: Brainstorm Force

	WP Paint - WordPress Image Editor
		Version: 0.5.3
		Author: ZetaMatic

	Yoast SEO
		Version: 20.4
		Author: Team Yoast


== Must-Use Plugins ==
	Force Strong Passwords - WPE Edition
		Version: 1.8.0
		Author: Jason Cosper

	WP Engine Cache Plugin
		Version: 1.1.2
		Author: WP Engine

	WP Engine Seamless Login Plugin
		Version: 1.6.0
		Author: WP Engine

	WP Engine Security Auditor
		Version: 1.0.10
		Author: wpengine

	WP Engine System
		Version: 5.0.1
		Author: WP Engine


== Features ==
	Custom Fonts: 3
	Custom Icons: 1

== Integrations ==
	


== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Inactive
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Upgrade Swiper Library: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Inactive by default
	Editor Top Bar: Inactive by default
	Landing Pages: Active
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active by default
	Form Submissions: Inactive
	Scroll Snap: Active by default
	Menu: Inactive by default


== Log ==
	
Log: showing 20 of 412023-04-03 08:08:00 [info] elementor-pro::elementor_pro_updater Started 
2023-04-03 08:08:00 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-04-03 08:08:00 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-04-03 08:08:00 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.0',
  'to' => '3.12.1',
)]
2023-04-03 08:08:00 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.0',
  'to' => '3.12.1',
)]
2023-04-03 08:08:08 [info] elementor-pro::elementor_pro_updater Started 
2023-04-03 08:08:08 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-04-03 08:08:08 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-04-03 08:08:08 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.0',
  'to' => '3.12.1',
)]
2023-04-03 08:08:08 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.0',
  'to' => '3.12.1',
)]
2023-04-03 08:08:11 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.0',
  'to' => '3.12.1',
)]
2023-04-03 08:08:11 [info] elementor-pro::elementor_pro_updater Started 
2023-04-03 08:08:11 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-04-03 08:08:11 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-04-03 08:08:11 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.0',
  'to' => '3.12.1',
)]
2023-04-03 08:08:12 [info] elementor-pro::elementor_pro_updater Started 
2023-04-03 08:08:12 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-04-03 08:08:12 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-04-03 08:08:12 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.0',
  'to' => '3.12.1',
)]
2023-04-03 08:08:12 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.0',
  'to' => '3.12.1',
)]

PHP: showing 1 of 1PHP: 2023-04-03 08:08:03 [error X 4][../wp-content/plugins/elementor/includes/conditions.php::46] Uncaught TypeError: in_array(): Argument #2 ($haystack) must be of type array, null given in ../wp-content/plugins/elementor/includes/conditions.php:46
Stack trace:
#0 ../wp-content/plugins/elementor/includes/conditions.php(46): in_array('viewport_tablet', NULL, true)
#1 ../wp-content/plugins/elementor/includes/conditions.php(99): Elementor\Conditions::compare(NULL, 'viewport_tablet', 'contains')
#2 ../wp-content/plugins/elementor/includes/base/controls-stack.php(1385): Elementor\Conditions::check(Array, Array)
#3 ../wp-content/plugins/elementor/includes/base/controls-stack.php(1171): Elementor\Controls_Stack->is_control_visible(Array, Array)
#4 ../wp-content/plugins/elementor/includes/base/controls-stack.php(1212): Elementor\Controls_Stack->get_active_settings(Array, Array)
#5 ../wp-content/plugins/analogwp-templates/inc/elementor/globals/class-colors.php(22): Elementor\Controls_Stack->get_settings_for_display('system_colors')
#6 ../wp-content/plugins/elementor/core/editor/data/globals/endpoints/base.php(31): Analog\Elementor\Globals\Colors->get_kit_items()
#7 ../wp-content/plugins/elementor/data/v2/base/base-route.php(329): Elementor\Core\Editor\Data\Globals\Endpoints\Base->get_item('ae1d040', Object(WP_REST_Request))
#8 ../wp-content/plugins/elementor/data/v2/base/base-route.php(233): Elementor\Data\V2\Base\Base_Route->base_callback('GET', Object(WP_REST_Request), false)
#9 ../wp-includes/rest-api/class-wp-rest-server.php(1181): Elementor\Data\V2\Base\Base_Route->Elementor\Data\V2\Base\{closure}(Object(WP_REST_Request))
#10 ../wp-includes/rest-api/class-wp-rest-server.php(1028): WP_REST_Server->respond_to_request(Object(WP_REST_Request), '/elementor/v1/g...', Array, NULL)
#11 ../wp-includes/rest-api.php(535): WP_REST_Server->dispatch(Object(WP_REST_Request))
#12 ../wp-content/plugins/elementor/data/v2/manager.php(318): rest_do_request(Object(WP_REST_Request))
#13 ../wp-content/plugins/elementor/data/v2/manager.php(383): Elementor\Data\V2\Manager->run_request('/elementor/v1/g...', Array, 'GET')
#14 ../wp-content/plugins/elementor/core/files/css/base.php(837): Elementor\Data\V2\Manager->run('globals/colors')
#15 ../wp-content/plugins/elementor/core/files/css/base.php(336): Elementor\Core\Files\CSS\Base->get_selector_global_value(Array, 'globals/colors?...')
#16 ../wp-content/plugins/elementor/core/files/css/base.php(689): Elementor\Core\Files\CSS\Base->add_control_rules(Array, Array, Object(Closure), Array, Array, Array)
#17 ../wp-content/plugins/elementor/core/files/css/base.php(558): Elementor\Core\Files\CSS\Base->add_control_style_rules(Array, Array, Array, Array, Array)
#18 ../wp-content/plugins/elementor/core/files/css/post.php(222): Elementor\Core\Files\CSS\Base->add_controls_stack_style_rules(Object(Elementor\Element_Section), Array, Array, Array, Array, Array)
#19 ../wp-content/plugins/elementor/core/files/css/post.php(298): Elementor\Core\Files\CSS\Post->add_controls_stack_style_rules(Object(Elementor\Element_Section), Array, Array, Array, Array)
#20 ../wp-content/plugins/elementor/core/files/css/post.php(178): Elementor\Core\Files\CSS\Post->render_styles(Object(Elementor\Element_Section))
#21 ../wp-content/plugins/elementor/core/files/css/base.php(651): Elementor\Core\Files\CSS\Post->render_css()
#22 ../wp-content/plugins/elementor/core/files/base.php(180): Elementor\Core\Files\CSS\Base->parse_content()
#23 ../wp-content/plugins/elementor/core/files/css/base.php(130): Elementor\Core\Files\Base->update_file()
#24 ../wp-content/plugins/elementor/core/files/css/base.php(217): Elementor\Core\Files\CSS\Base->update()
#25 ../wp-content/plugins/elementor/core/files/css/post.php(201): Elementor\Core\Files\CSS\Base->enqueue()
#26 ../wp-content/plugins/elementor/includes/frontend.php(1155): Elementor\Core\Files\CSS\Post->enqueue()
#27 ../wp-content/plugins/elementor/includes/frontend.php(1247): Elementor\Frontend->get_builder_content('539', true)
#28 ../wp-content/plugins/elementor-pro/modules/library/widgets/template.php(97): Elementor\Frontend->get_builder_content_for_display('539')
#29 ../wp-content/plugins/elementor/includes/base/controls-stack.php(2268): ElementorPro\Modules\Library\Widgets\Template->render()
#30 ../wp-content/plugins/elementor/includes/base/widget-base.php(609): Elementor\Controls_Stack->render_by_mode()
#31 ../wp-content/plugins/elementor/includes/base/widget-base.php(733): Elementor\Widget_Base->render_content()
#32 ../wp-content/plugins/elementor/includes/base/element-base.php(536): Elementor\Widget_Base->get_raw_data(true)
#33 ../wp-content/plugins/elementor/includes/base/element-base.php(536): Elementor\Element_Base->get_raw_data(true)
#34 ../wp-content/plugins/elementor/core/base/document.php(977): Elementor\Element_Base->get_raw_data(true)
#35 ../wp-content/plugins/elementor/core/base/document.php(643): Elementor\Core\Base\Document->get_elements_raw_data(Array, true)
#36 ../wp-content/plugins/elementor/includes/base/controls-stack.php(1021): Elementor\Core\Base\Document->get_initial_config()
#37 ../wp-content/plugins/elementor/core/editor/config-providers/editor-common-client-settings.php(36): Elementor\Controls_Stack->get_config()
#38 ../wp-content/plugins/elementor/core/editor/config-providers/editor-common-configs.php(169): Elementor\Core\Editor\Config_Providers\Editor_Common_Client_Settings::get_client_settings()
#39 ../wp-content/plugins/elementor/core/editor/config-providers/editor-v1-config-provider.php(41): Elementor\Core\Editor\Config_Providers\Editor_Common_Configs::get_client_settings()
#40 ../wp-content/plugins/elementor/core/editor/editor-loader.php(57): Elementor\Core\Editor\Config_Providers\Editor_V1_Config_Provider->get_client_settings()
#41 ../wp-content/plugins/elementor/core/editor/editor.php(357): Elementor\Core\Editor\Editor_Loader->print_client_settings()
#42 ../wp-includes/class-wp-hook.php(308): Elementor\Core\Editor\Editor->enqueue_scripts('')
#43 ../wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#44 ../wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#45 ../wp-includes/script-loader.php(2194): do_action('wp_enqueue_scri...')
#46 ../wp-includes/class-wp-hook.php(308): wp_enqueue_scripts('')
#47 ../wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#48 ../wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#49 ../wp-includes/general-template.php(3049): do_action('wp_head')
#50 ../wp-content/plugins/elementor/includes/editor-templates/editor-wrapper.php(31): wp_head()
#51 ../wp-content/plugins/elementor/core/editor/editor-loader.php(135): include('/nas/content/li...')
#52 ../wp-content/plugins/elementor/core/editor/editor.php(162): Elementor\Core\Editor\Editor_Loader->print_root_template()
#53 ../wp-includes/class-wp-hook.php(308): Elementor\Core\Editor\Editor->init('')
#54 ../wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#55 ../wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#56 ../wp-admin/admin.php(419): do_action('admin_action_el...')
#57 ../wp-admin/post.php(12): require_once('/nas/content/li...')
#58 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	Make Column Clickable Elementor: Compatibility not specified
	Style Kits for Elementor: Compatibility not specified
	Ultimate Addons for Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==
	

				

````

</details>

**Comment by sugapablo** [comment]
I'm having the same issues.  PHP >= 8 and I get the errors above.  PHP 7.4 and everything works.
Elementor Pro 3.14.1

**Comment by micmiller-apptio** [comment]
I think this bug has to do with the Style Kits plugin, I have the same problem with PHP 8.0, but it goes away if I define and activate one custom breakpoint in Elementor.

**Comment by KingYes** [comment]
It should be fixed in one of the late versions of Elementor Pro. Please reopen this if you see this error again and tell us how to reproduce it.

Make sure all other plugins/theme are up to date, too.
