### ISSUE TITLE
✅ 🐞 Bug Report: Responsive button don't work properly

### ISSUE THREAD

**Issue by JGH-WEB** [elementor/elementor#21936]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hello !
So the problem is pretty simple, when I want to clic on the responsive button, I have to click exactly on the icon. If I clic not exactly on the icon, nothing happen.
On the other buttons (like nav, preview etc...) I can clic anywhere around the icon, not only the icons.
![image](https://user-images.githubusercontent.com/115219047/230020578-d64d848f-c4ee-4abf-a1a6-9ed4930ac04f.png)

### Steps to reproduce

This bug appear since 3.20 (and still here with 3.21 lastest update).
All my website with 3.20+ is affected by this bug so I suppose it's the same for all.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>Click to reveal</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release '24', Revision 'e5c6e9d2' v8.0.32-24
	PHP Version: 7.4.33
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://www.hotel-les-agapanthes.com.preprod.eliophot.fr
	Home URL: https://www.hotel-les-agapanthes.com.preprod.eliophot.fr
	WP Multisite: No
	Max Upload Size: 2 Mo
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: fr-FR
	Timezone: Europe/Paris
	Debug Mode: Inactive

== Theme ==
	Name: Eliophot Base Theme Child
	Version: 2.5.0
	Author: Eliophot
	Child Theme: Yes
	Parent Theme Name: Eliophot Base Theme
	Parent Theme Version: 2.5.0-2
	Parent Theme Author: Eliophot

== User ==
	Role: administrator
	WP Profile lang: fr_FR
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36

== Active Plugins ==
	All In One WP Security
		Version: 5.1.4
		Author: All In One WP Security & Firewall Team

	CMP - Coming Soon & Maintenance Plugin
		Version: 4.1.6
		Author: NiteoThemes

	Duplicate Page
		Version: 4.5
		Author: mndpsingh287

	Duplicator Pro
		Version: 4.5.9.1
		Author: Snap Creek

	Elementor
		Version: 3.12.0
		Author: Elementor.com

	Elementor Eliophot
		Version: 1.4.1
		Author: Eliophot

	Elementor Pro
		Version: 3.12.0
		Author: Elementor.com

	Eliophot
		Version: 1.6.6
		Author: Eliophot

	Eliophot Resources
		Version: 1.1
		Author: Eliophot

	Eliophot Updater
		Version: 10.0.5
		Author: Eliophot

	Enable Media Replace
		Version: 4.0.1
		Author: ShortPixel

	Health Check & Troubleshooting
		Version: 1.5.1
		Author: The WordPress.org community

	JWT Authentication for WP-API
		Version: 1.3.2
		Author: Enrique Chavez

	NinjaFirewall (WP Edition)
		Version: 4.5.5
		Author: The Ninja Technologies Network

	Rank Math SEO
		Version: 1.0.106
		Author: Rank Math

	Rank Math SEO PRO
		Version: 3.0.28
		Author: Rank Math

	SVG Support
		Version: 2.5.5
		Author: Benbodhi

	TranslatePress - Developer
		Version: 1.2.3
		Author: Cozmoslabs, Razvan Mocanu, Madalin Ungureanu

	TranslatePress - Multilingual
		Version: 2.4.4
		Author: Cozmoslabs, Razvan Mocanu, Madalin Ungureanu, Cristophor Hurduban

	WP Rocket
		Version: 3.12.4
		Author: WP Media


== Must-Use Plugins ==
	0-ninjafirewall.php
		Version: 1.0
		Author: The Ninja Technologies Network


== Fonctionnalités ==
	Custom Fonts: 0
	Custom Icons: 1

== Intégrations ==
	


== Expériences d’Elementor ==
	Sortie DOM optimisée: Inactif par défaut
	Amélioration du chargement des ressources: Inactif par défaut
	Optimisation du chargement du CSS: Inactif par défaut
	Icônes de police « inline »: Inactif par défaut
	Améliorations de l’accessibilité: Actif par défaut
	Points d’arrêt personnalisés supplémentaires: Actif par défaut
	admin_menu_rearrangement: Inactif par défaut
	Conteneur Flexbox: Inactif par défaut
	Mettre à niveau la bibliothèque Swiper: Inactif par défaut
	Par défaut vers le Nouveau constructeur de thème: Actif par défaut
	Hello Theme Header & Footer: Inactif par défaut
	Editor Top Bar: Inactif par défaut
	Page d’atterrissage: Actif par défaut
	Éléments imbriqués: Inactif par défaut
	Chargement différé des images d’arrière-plan: Inactif par défaut
	Transitions des pages: Actif par défaut
	Notes: Actif par défaut
	Boucle: Actif par défaut
	Accroche de défilement: Actif par défaut
	Menu: Inactif par défaut


== Journal ==
	
Log: showing 20 of 332023-02-23 12:21:13 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.0',
  'to' => '3.11.2',
)]
2023-02-23 12:21:13 [info] elementor::elementor_updater Started 
2023-02-23 12:21:13 [info] Elementor/Upgrades - _on_each_version Start  
2023-02-23 12:21:13 [info] Elementor/Upgrades - _on_each_version Finished 
2023-02-23 12:21:13 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.0',
  'to' => '3.11.2',
)]
2023-02-23 12:21:14 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.0',
  'to' => '3.11.2',
)]
2023-02-23 12:25:59 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.10.1',
  'to' => '3.11.2',
)]
2023-02-23 12:25:59 [info] elementor-pro::elementor_pro_updater Started 
2023-02-23 12:25:59 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-02-23 12:25:59 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-02-23 12:25:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.10.1',
  'to' => '3.11.2',
)]
2023-02-23 12:26:00 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.10.1',
  'to' => '3.11.2',
)]
2023-03-30 14:40:31 [info] elementor::elementor_updater Started 
2023-03-30 14:40:31 [info] Elementor/Upgrades - _on_each_version Start  
2023-03-30 14:40:31 [info] Elementor/Upgrades - _on_each_version Finished 
2023-03-30 14:40:31 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.2',
  'to' => '3.12.0',
)]
2023-03-30 14:40:36 [info] elementor-pro::elementor_pro_updater Started 
2023-03-30 14:40:36 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-03-30 14:40:36 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-03-30 14:40:36 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.2',
  'to' => '3.12.0',
)]

JS: showing 6 of 6JS: 2023-02-14 13:04:58 [error X 2][https://www.hotel-les-agapanthes.com.preprod.eliophot.fr/wp-content/plugins/elementor/assets/js/new-template.min.js?ver=3.10.0:2:2932] elementor_new_template_form_controls is not defined 
JS: 2023-02-17 09:23:41 [error X 8][https://www.hotel-les-agapanthes.com.preprod.eliophot.fr/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.10.0:3:1075047] Cannot read properties of null (reading 'getBoundingClientRect') 
JS: 2023-02-23 11:10:30 [error X 35][https://www.hotel-les-agapanthes.com.preprod.eliophot.fr/wp-admin/load-scripts.php?c=0&loadchunk_0=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&loadchunk_1=hooks&ver=6.1.1:4:51824] Cannot read properties of undefined (reading 'replace') 
JS: 2023-02-23 11:16:29 [error X 2][https://www.hotel-les-agapanthes.com.preprod.eliophot.fr/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.10.0:3:582690] Cannot read properties of null (reading 'id') 
JS: 2023-02-23 11:16:30 [error X 1][https://www.hotel-les-agapanthes.com.preprod.eliophot.fr/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.10.0:3:738754] Cannot read properties of null (reading 'config') 
JS: 2023-03-31 12:46:59 [error X 4][https://www.hotel-les-agapanthes.com.preprod.eliophot.fr/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.12.0:3:785745] Cannot read properties of undefined (reading 'localized') 

PHP: showing 3 of 3PHP: 2023-02-14 14:13:32 [notice X 1][../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::168] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-14 14:14:08 [notice X 8][../wp-content/plugins/elementor/core/common/modules/ajax/module.php::172] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-23 12:20:28 [error X 1][../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::295] Uncaught Error: Call to a member function update_meta() on bool in /../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:295
Stack trace:
#0 ../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(168): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions()
#2 ../wp-content/plugins/elementor/core/common/modules/ajax/module.php(172): call_user_func()
#3 ../wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#4 ../wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#5 ../wp-includes/plugin.php(517): WP_Hook->do_ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Eliophot: Compatibilité non spécifiée
	Elementor Pro: Compatibilité non spécifiée

== Elementor Pro - Compatibility Tag ==
	

				

````

</details>

**Comment by nicholaszein** [comment]
Hello there!

### 📢 We're happy to announce that the issue you raised was resolved in Elementor v3.12.2! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
