### ISSUE TITLE
Share Buttons - Column and Row gaps setting not working

### ISSUE THREAD

**Issue by acornavi** [elementor/elementor#21944]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Share widget column and row gaps settings don't work; also, the alignment setting, when justified, doesn't work as well.
You can see it in the Elementor editor, but the front-end share buttons are squished together. The problem is persistent in desktop, tablet, and mobile.
This is a 5-year-old problem. 

### Steps to reproduce

You know how to reproduce it.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.39-42
	PHP Version: 7.4.33
	PHP Memory Limit: 768M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2
	Site URL: https://www.biotherapy.asia
	Home URL: https://www.biotherapy.asia
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 768M
	Max Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Asia/Bangkok
	Admin Email: acornavi@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.7.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/111.0

== Active Plugins ==
	ACF Photo Gallery Field
		Version: 1.8.1
		Author: Navneil Naicker

	Advanced Custom Fields
		Version: 6.1.2
		Author: WP Engine

	Advanced Custom Fields Multilingual
		Version: 2.0.3
		Author: OnTheGoSystems

	Change Mail Sender
		Version: 1.3.0
		Author: WP Mail SMTP

	Change WordPress Login Logo
		Version: 1.1.9
		Author: Boopathi Rajan

	Classic Editor
		Version: 1.6.3
		Author: WordPress Contributors

	Code Snippets
		Version: 3.3.0
		Author: Code Snippets Pro

	Custom Post Type UI
		Version: 1.13.5
		Author: WebDevStudios

	Duplicate Menu
		Version: 0.2.2
		Author: Jonathan Christopher

	Duplicate Page
		Version: 4.5.1
		Author: mndpsingh287

	e-addons DISPLAY
		Version: 2.1.3
		Author: Nerds Farm

	e-addons EXTENDED
		Version: 2.4
		Author: Nerds Farm

	e-addons for Elementor
		Version: 3.3.1
		Author: Nerds Farm

	e-addons MAPS
		Version: 2.0.2
		Author: Nerds Farm

	e-addons PRO FORM ACTIONS
		Version: 2.2.2
		Author: Nerds Farm

	e-addons PRO FORM CONDITIONS
		Version: 2.2.1
		Author: Nerds Farm

	e-addons PRO FORM EXTENDED
		Version: 2.4.2
		Author: Nerds Farm

	e-addons QUERY
		Version: 2.1.6
		Author: Nerds Farm

	e-addons TWIG
		Version: 2.3.1
		Author: Nerds Farm

	e-addons UI
		Version: 2.2.2
		Author: Nerds Farm

	Elementor
		Version: 3.12.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.12.1
		Author: Elementor.com

	Email Encoder - Protect Email Addresses
		Version: 2.1.3
		Author: Ironikus

	Enable Media Replace
		Version: 4.1.0
		Author: ShortPixel

	Extras for Elementor
		Version: 2.2.51
		Author: Namogo

	Favicon by RealFaviconGenerator
		Version: 1.3.27
		Author: Philippe Bernard

	Flexible Elementor Panel
		Version: 2.3.9
		Author: WebMat

	HappyFiles Pro
		Version: 1.8.2
		Author: Codeer

	Health Check & Troubleshooting
		Version: 1.6.0
		Author: The WordPress.org community

	Inactive Logout
		Version: 3.0.14
		Author: Deepen Bajracharya

	Interactive World Maps
		Version: 2.3.3.1
		Author: Carlos Moreira

	MailChimp for WordPress Multilingual
		Version: 0.0.3
		Author: OnTheGoSystems

	Newsletter
		Version: 7.6.9
		Author: Stefano Lissa & The Newsletter Team

	Newsletter - Addons Manager
		Version: 1.2.0
		Author: The Newsletter Team

	Newsletter - Archive
		Version: 4.0.8
		Author: The Newsletter Team

	Newsletter - Autoresponder
		Version: 1.3.8
		Author: The Newsletter Team

	Newsletter - Bounce Management
		Version: 1.2.1
		Author: The Newsletter Team

	Newsletter - Elementor Addon
		Version: 1.0.4
		Author: The Newsletter Team

	Newsletter - Extended Composer Blocks
		Version: 1.4.1
		Author: The Newsletter Team

	Newsletter - Geolocation
		Version: 1.1.8
		Author: The Newsletter Team

	Newsletter - Google Analytics
		Version: 1.1.8
		Author: The Newsletter Team

	Newsletter - Import
		Version: 1.3.7
		Author: The Newsletter Team

	Newsletter - Instasend (BETA)
		Version: 1.0.3
		Author: The Newsletter Team

	Newsletter - Reports and Retargeting
		Version: 4.4.5
		Author: The Newsletter Team

	Newsletter - Webhooks
		Version: 1.0.6
		Author: The Newsletter Team

	One Click Accessibility
		Version: 2.1.0
		Author: One Click Accessibility

	OneSignal Push Notifications
		Version: 2.4.0
		Author: OneSignal

	Piotnet Addons For Elementor
		Version: 2.4.23
		Author: Piotnet

	Piotnet Addons For Elementor Pro
		Version: 7.1.0
		Author: Piotnet Team

	PixelYourSite
		Version: 9.3.5
		Author: PixelYourSite

	Presto Player
		Version: 1.13.0
		Author: Presto Made, Inc

	Presto Player Pro
		Version: 1.2.1
		Author: Presto Player

	Rank Math SEO
		Version: 1.0.110.2
		Author: Rank Math

	Relevanssi
		Version: 4.18.4
		Author: Mikko Saari

	SiteGround Optimizer
		Version: 7.3.1
		Author: SiteGround

	SiteGround Security
		Version: 1.4.1
		Author: SiteGround

	Site Kit by Google
		Version: 1.96.0
		Author: Google

	SMTP for AmazonSES - YaySMTP
		Version: 1.5
		Author: YayCommerce

	Temporary Login Without Password
		Version: 1.8.1.1
		Author: StoreApps

	Toolbar Extras
		Version: 1.4.9
		Author: David Decker - DECKERWEB

	ToolKit For Elementor
		Version: 1.4.9
		Author: ToolKit For Elementor

	User Role Editor
		Version: 4.63.3
		Author: Vladimir Garagulya

	WP Copy Content Protection
		Version: 1.3
		Author: Blogger PNG

	WP Disable Automatic Updates
		Version: 1.1
		Author: Daniele De Rosa

	WPML CMS Nav
		Version: 1.5.5
		Author: OnTheGoSystems

	WPML Media
		Version: 2.7.2
		Author: OnTheGoSystems

	WPML Multilingual CMS
		Version: 4.6.3
		Author: OnTheGoSystems

	WPML SEO
		Version: 2.1.0
		Author: OnTheGoSystems

	WPML Sticky Links
		Version: 1.5.4
		Author: OnTheGoSystems

	WPML String Translation
		Version: 3.2.5
		Author: OnTheGoSystems

== Must-Use Plugins ==
	Health Check Troubleshooting Mode
		Version: 1.8.1
		Author: 

== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	
	google_maps: Active
	recaptcha_v3: Active
	facebook_sdk: Active

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Inactive
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Inactive
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive
	Upgrade Swiper Library: Inactive by default
	Default to New Theme Builder: Inactive
	Hello Theme Header & Footer: Inactive
	Editor Top Bar: Inactive by default
	Landing Pages: Inactive
	Nested Elements: Inactive
	Lazy Load Background Images: Inactive
	Page Transitions: Active
	Notes: Inactive
	Loop: Inactive
	Form Submissions: Active
	Scroll Snap: Inactive
	Menu: Inactive by default

== Log ==
	
JS: showing 18 of 18JS: 2023-03-24 15:37:32 [error X 1][https://www.biotherapy.asia/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:40864] can't assign to property "guid" on "c57360widgetsticky": not an object 
JS: 2023-03-24 15:37:32 [error X 1][https://www.biotherapy.asia/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:40864] can't assign to property "guid" on "c57363widgetsticky": not an object 
JS: 2023-03-24 15:37:32 [error X 1][https://www.biotherapy.asia/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:40864] can't assign to property "guid" on "c57366widgetsticky": not an object 
JS: 2023-03-24 15:37:32 [error X 1][https://www.biotherapy.asia/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:40864] can't assign to property "guid" on "c57369widgetsticky": not an object 
JS: 2023-03-24 15:37:32 [error X 1][https://www.biotherapy.asia/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:40864] can't assign to property "guid" on "c57372widgetsticky": not an object 
JS: 2023-03-24 15:37:32 [error X 1][https://www.biotherapy.asia/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:40864] can't assign to property "guid" on "c57375widgetsticky": not an object 
JS: 2023-03-24 15:37:32 [error X 1][https://www.biotherapy.asia/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:40864] can't assign to property "guid" on "c57378widgetsticky": not an object 
JS: 2023-03-24 15:37:32 [error X 1][https://www.biotherapy.asia/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:40864] can't assign to property "guid" on "c57381widgetsticky": not an object 
JS: 2023-03-24 15:37:32 [error X 1][https://www.biotherapy.asia/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:40864] can't assign to property "guid" on "c57384widgetsticky": not an object 
JS: 2023-03-24 15:37:32 [error X 1][https://www.biotherapy.asia/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:40864] can't assign to property "guid" on "c57387widgetsticky": not an object 
JS: 2023-03-24 15:37:32 [error X 1][https://www.biotherapy.asia/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:40864] can't assign to property "guid" on "c57396widgetsticky": not an object 
JS: 2023-03-24 15:37:32 [error X 1][https://www.biotherapy.asia/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:40864] can't assign to property "guid" on "c57399widgetsticky": not an object 
JS: 2023-03-24 15:37:32 [error X 1][https://www.biotherapy.asia/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:40864] can't assign to property "guid" on "c57402widgetsticky": not an object 
JS: 2023-03-24 15:37:32 [error X 1][https://www.biotherapy.asia/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:40864] can't assign to property "guid" on "c57405widgetsticky": not an object 
JS: 2023-03-24 15:37:32 [error X 1][https://www.biotherapy.asia/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:40864] can't assign to property "guid" on "c57408widgetsticky": not an object 
JS: 2023-03-24 15:37:32 [error X 1][https://www.biotherapy.asia/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:40864] can't assign to property "guid" on "c57427widgetsticky": not an object 
JS: 2023-03-24 15:37:32 [error X 1][https://www.biotherapy.asia/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:40864] can't assign to property "guid" on "c57436widgetsticky": not an object 
JS: 2023-03-24 15:38:22 [error X 6][https://www.biotherapy.asia/wp-admin/load-scripts.php?c=0&loadchunk_0=jquery-core,jquery-migrate,utils,moxiejs,plupload&ver=6.1.1:2:51816] a is undefined 

PHP: showing 4 of 4PHP: 2023-03-26 01:30:09 [notice X 2][/home/customer/www/biotherapy.asia/public_html/wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-29 01:31:33 [notice X 2][/home/customer/www/biotherapy.asia/public_html/wp-content/plugins/elementor-pro/modules/posts/skins/skin-content-base.php::219] Trying to get property 'ID' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-29 02:19:54 [error X 1][/home/customer/www/biotherapy.asia/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::295] Uncaught Error: Call to a member function update_meta() on bool in /home/customer/www/biotherapy.asia/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:295
Stack trace:
#0 /home/customer/www/biotherapy.asia/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(168): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/customer/www/biotherapy.asia/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/customer/www/biotherapy.asia/public_html/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/customer/www/biotherapy.asia/pu [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-04 23:42:38 [notice X 8][/home/customer/www/biotherapy.asia/public_html/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-number.php::33] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 20 of 202023-03-29 21:59:51 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.5',
  'to' => '3.12.0',
)]
2023-03-29 21:59:52 [info] elementor-pro::elementor_pro_updater Started 
2023-03-29 21:59:52 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-03-29 21:59:52 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-03-29 21:59:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.7',
  'to' => '3.12.0',
)]
2023-03-29 21:59:52 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.7',
  'to' => '3.12.0',
)]
2023-03-29 21:59:52 [info] elementor::elementor_updater Started 
2023-03-29 21:59:52 [info] Elementor/Upgrades - _on_each_version Start  
2023-03-29 21:59:52 [info] Elementor/Upgrades - _on_each_version Finished 
2023-03-29 21:59:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.5',
  'to' => '3.12.0',
)]
2023-04-04 19:30:52 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.0',
  'to' => '3.12.1',
)]
2023-04-04 19:30:53 [info] elementor-pro::elementor_pro_updater Started 
2023-04-04 19:30:53 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-04-04 19:30:53 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-04-04 19:30:53 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.0',
  'to' => '3.12.1',
)]
2023-04-04 19:30:53 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.0',
  'to' => '3.12.1',
)]
2023-04-04 19:30:53 [info] elementor::elementor_updater Started 
2023-04-04 19:30:53 [info] Elementor/Upgrades - _on_each_version Start  
2023-04-04 19:30:53 [info] Elementor/Upgrades - _on_each_version Finished 
2023-04-04 19:30:53 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.0',
  'to' => '3.12.1',
)]

== Elementor - Compatibility Tag ==
	
	e-addons for Elementor: Compatibility unknown
	Elementor Pro: Incompatible
	Extras for Elementor: Incompatible
	Flexible Elementor Panel: Compatibility not specified
	Newsletter - Elementor Addon: Incompatible
	Piotnet Addons For Elementor: Incompatible
	Piotnet Addons For Elementor Pro: Incompatible
	ToolKit For Elementor: Incompatible

== Elementor Pro - Compatibility Tag ==
	
	e-addons for Elementor: Compatibility unknown
	Extras for Elementor: Incompatible
	Newsletter - Elementor Addon: Incompatible
	Piotnet Addons For Elementor: Incompatible
	Piotnet Addons For Elementor Pro: Incompatible
	ToolKit For Elementor: Incompatible

**Comment by simon-womersley** [comment]
Hi @acornavi, 

thanks for reporting this! 

I too have the some problem. I spent forever trying to fix it until I found your bug report. At least it's not just me! 

I'm on the 08th May release, Version 3.12.3 and it still has the error. Luckily @nicholaszein has kindly responded.

**Comment by acornavi** [comment]
There are many new features, which is good, but older widgets are somehow
not updated or upgraded with new functionality, fancy features, and more
detailed styling options. Hopefully, it will be done soon.

**Comment by softstackio** [comment]
`.elementor-grid-0 .elementor-grid .elementor-grid-item {
margin-right: 5px !important;
}`
