### ISSUE TITLE
Code Highlight widget is wrongly interpreting code as HTML entities 

### ISSUE THREAD

**Issue by Dudeney95** [elementor/elementor#21952]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

My website is all about helping people customise their WooCommerce store with code snippets.

As good conventional practice, I am saving the code snippets to each post as postmeta via a post meta field (Pay close attention to the symbol **=>** which is association operator and is typically used to define key-value pairs within an array):
![image](https://user-images.githubusercontent.com/123473359/230298174-4221dfbf-38e0-48c4-b837-1fd8ec9c1435.png)

As you can see from the database, the code snippet is stored exactly how I've entered it in the post meta field (again, pay close attention to the symbol **=>** ):
![image](https://user-images.githubusercontent.com/123473359/230294548-b6c4b36f-e377-4725-9fb2-f1519e4e5c18.png)

When using the dynamic data function to display this code snippet in the Code Highlight widget, characters like those from my example, are wrongly output as HTML entities:
![image](https://user-images.githubusercontent.com/123473359/230295229-f1e4b432-54e9-4a48-8514-a345839ac83c.png)

This breaks the code snippet as it is not being output correctly by the Code Highlight widget.

For context, I am using meta fields by Crocoblock's JetEngine plugin HOWEVER, this is not a third-party plugin issue or the code saved in the database would output HTML entities. The issue is how the dynamic data function pulls data from the database. I can reproduce using multiple plugins which save postmeta to the database. I can reproduce using Wordpress' own custom fields feature. I can even reproduce without a meta field plugin and edit the database directly and the same issue occurs.

### Steps to reproduce

1) Save a code snippet as postmeta to your database, one which uses these symbols for example **=>** (either directly or by using a meta field plugin like JetEngine by Crocoblock).
2) Insert the Code Highlight widget onto an Elementor edited page.
3) Use the dynamic data function to pull the saved code snippet into the Code Highlight widget.
4) Observe that some characters are being output as HTML entites rather than as they are saved to the database.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.4.28
	PHP Version: 7.4.33
	PHP Memory Limit: 128M
	PHP Max Input Vars: 2500
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2
	Site URL: https://www.ecommercehints.co.uk
	Home URL: https://www.ecommercehints.co.uk
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%
	Language: en-GB
	Timezone: Europe/London
	Admin Email: alexdudeney@hotmail.co.uk
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.7.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.1661.62

== Active Plugins ==
	Code Snippets
		Version: 3.3.0
		Author: Code Snippets Pro

	Elementor
		Version: 3.12.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.12.1
		Author: Elementor.com

	JetEngine
		Version: 3.1.3.1
		Author: Crocoblock

	JetSearch
		Version: 3.0.3
		Author: Crocoblock

	MC4WP: Mailchimp for WordPress
		Version: 4.9.3
		Author: ibericode

	Perfmatters
		Version: 2.0.9
		Author: forgemedia

	Rank Math SEO
		Version: 1.0.111
		Author: Rank Math

	Really Simple CSV Importer
		Version: 1.3
		Author: Takuro Hishikawa

	WooCommerce
		Version: 7.5.1
		Author: Automattic

	WooCommerce Cart Abandonment Recovery
		Version: 1.2.24
		Author: CartFlows Inc

	WooCommerce PayPal Payments
		Version: 2.0.4
		Author: WooCommerce

	WooCommerce Stripe Gateway
		Version: 7.2.0
		Author: WooCommerce

== Must-Use Plugins ==
	StackCache
		Version: 
		Author: Stack CP

== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	
	woocommerce: Active

== Elementor Experiments ==
	Optimised DOM Output: Active
	Improved asset loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility improvements: Active
	Additional Custom Breakpoints: Inactive
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active
	Default to New Theme Builder: Inactive
	Hello Theme Header & Footer: Inactive
	Editor Top Bar: Inactive by default
	Landing pages: Inactive
	Nested Elements: Active
	Lazy Load Background Images: Active
	Page Transitions: Inactive
	Notes: Inactive
	Loop: Active
	Form Submissions: Active
	Scroll Snap: Inactive
	Menu: Inactive

== Log ==
	
Log: showing 20 of 222023-03-27 14:40:30 [info] Elementor/Upgrades - _on_each_version Start  
2023-03-27 14:40:30 [info] Elementor/Upgrades - _on_each_version Finished 
2023-03-27 14:40:30 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.4',
  'to' => '3.11.5',
)]
2023-03-29 18:44:22 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.5',
  'to' => '3.12.0',
)]
2023-03-29 18:44:23 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.5',
  'to' => '3.12.0',
)]
2023-03-29 18:44:25 [info] elementor::elementor_updater Started 
2023-03-29 18:44:25 [info] Elementor/Upgrades - _on_each_version Start  
2023-03-29 18:44:25 [info] Elementor/Upgrades - _on_each_version Finished 
2023-03-29 18:44:25 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-03-29 18:44:25 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-03-29 18:44:26 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.5',
  'to' => '3.12.0',
)]
2023-04-06 07:09:45 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.0',
  'to' => '3.12.1',
)]
2023-04-06 07:09:46 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.0',
  'to' => '3.12.1',
)]
2023-04-06 07:09:49 [info] elementor::elementor_updater Started 
2023-04-06 07:09:49 [info] Elementor/Upgrades - _on_each_version Start  
2023-04-06 07:09:49 [info] Elementor/Upgrades - _on_each_version Finished 
2023-04-06 07:09:49 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.0',
  'to' => '3.12.1',
)]
2023-04-06 07:09:49 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.0',
  'to' => '3.12.1',
)]
2023-04-06 07:09:50 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.0',
  'to' => '3.12.1',
)]
2023-04-06 07:09:51 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.0',
  'to' => '3.12.1',
)]

JS: showing 4 of 4JS: 2023-03-27 14:39:09 [error X 8][https://www.ecommercehints.co.uk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.11.5:3:791668] Cannot read properties of undefined (reading 'localized') 
JS: 2023-03-30 12:24:19 [error X 2][https://www.ecommercehints.co.uk/wp-content/plugins/elementor/assets/js/df16c9d56464dd4f0800.bundle.min.js:2:7826] Cannot read properties of null (reading 'dataset') 
JS: 2023-03-30 13:17:00 [error X 1][https://www.ecommercehints.co.uk/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.12.0:2:63893] Cannot convert undefined or null to object 
JS: 2023-03-30 13:32:28 [error X 3][https://www.ecommercehints.co.uk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.12.0:3:785238] Cannot read properties of undefined (reading 'toLowerCase') 

PHP: showing 6 of 6PHP: 2023-03-27 16:17:04 [notice X 1][/home/sites/25b/d/df14622ead/public_html/wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-27 16:27:57 [notice X 10][/home/sites/25b/d/df14622ead/public_html/wp-content/plugins/elementor/app/modules/import-export/module.php::629] Trying to get property 'label' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-27 16:27:58 [notice X 8][/home/sites/25b/d/df14622ead/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-27 21:37:01 [error X 1][/home/sites/25b/d/df14622ead/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::295] Uncaught Error: Call to a member function update_meta() on bool in /home/sites/25b/d/df14622ead/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:295
Stack trace:
#0 /home/sites/25b/d/df14622ead/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(168): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/sites/25b/d/df14622ead/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/sites/25b/d/df14622ead/public_html/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/sites/25b/d/df14622ead/public_html/wp-includes/class-wp [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-01 10:44:27 [notice X 4][/home/sites/25b/d/df14622ead/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined index: condition_type [array (
  'trace' => '
#0: /home/sites/25b/d/df14622ead/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /home/sites/25b/d/df14622ead/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /home/sites/25b/d/df14622ead/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /home/sites/25b/d/df14622ead/public_html/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2023-04-01 10:45:19 [notice X 3][/home/sites/25b/d/df14622ead/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::168] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Incompatible

== Elementor Pro - Compatibility Tag ==

**Comment by Dudeney95** [comment]
Thank you @nicholaszein 🙏 I don't suppose you know when there will be a patch rolled out to fix the bug?

**Comment by aureliePrd** [comment]
+1 
I am having a similar bug happening only **when connected as an Editor**
When I save the Elementor page where I have a custom CSS : 
`selector > div {...}`

It changes the sign to & gt;
I am developing a multisite wordpress using Elementor Pro and my Hello Theme Child.
Thanks for the feedback
