### ISSUE TITLE
Elementor Pro Editor not working, only shows header and footer. Disable pro and it works fine.

### ISSUE THREAD

**Issue by AaronSageAge** [elementor/elementor#21960]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

1. Turned off all plugins but elementor and elem pro
2. Changed theme
3. Fell back on Elementor and pro
4. Safe Mode in Elementor didn't fix it
5. Replaced all plugins and theme files
6. Turned off all cache on the site
7. Updated Elementor to the latest and still no joy
8. Disabled all plugins in browser
9. Tried all different browser, and a different computer
10. Combed over logs and fixed other issues that I thought might be related but still no

### Steps to reproduce

Login try to edit a page and get only the header and footer, no page content. Disable Elementor Pro and it works fine. 

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

== Server Environment ==
	Operating System: FreeBSD
	Software: Apache/2.4.52 (FreeBSD) OpenSSL/1.1.1d-freebsd mpm-itk/2.4.7-04
	MySQL version: Source distribution v5.7.28
	PHP Version: 7.4.27
	PHP Memory Limit: 512M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 1024M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2
	Site URL: https://freedomvillage-dev.sageage.site
	Home URL: https://freedomvillage-dev.sageage.site
	WP Multisite: No
	Max Upload Size: 1 GB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: admin@sageage.com
	Debug Mode: Active

== Theme ==
	Name: Oaktrix
	Version: 1.0.5
	Author: Opal Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36

== Active Plugins ==
	Akismet Anti-Spam: Spam Protection
		Version: 5.1
		Author: Automattic - Anti Spam Team

	Breadcrumb NavXT
		Version: 7.2.0
		Author: John Havlik

	Classic Editor
		Version: 1.6.3
		Author: WordPress Contributors

	CSS &amp; JavaScript Toolbox
		Version: 11.6
		Author: Wipeout Media

	CSS &amp; JavaScript Toolbox PLUS
		Version: 11.6
		Author: Wipeout Media

	Disable Gutenberg
		Version: 2.9
		Author: Jeff Starr

	Elementor
		Version: 3.12.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.12.1
		Author: Elementor.com

	Emfluence GForms
		Version: 1.2
		Author: Sage Age

	Gravity Forms
		Version: 2.7.3
		Author: Gravity Forms

	Gravity Forms Event Tracking
		Version: 2.4.14
		Author: Ronald Huereca

	Gravity Forms reCAPTCHA Add-On
		Version: 1.1
		Author: Gravity Forms

	Oaktrix Core
		Version: 1.3.2
		Author: 

	Simple 301 Redirects
		Version: 2.0.7
		Author: WPDeveloper

	Slider Revolution
		Version: 6.1.5
		Author: ThemePunch

	SVG Support
		Version: 2.5.5
		Author: Benbodhi

== Features ==
	Custom Fonts: 3
	Custom Icons: 0

== Integrations ==
	

== Elementor Experiments ==
	Optimized DOM Output: Inactive
	Improved Asset Loading: Inactive
	Improved CSS Loading: Inactive
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Inactive
	Additional Custom Breakpoints: Inactive
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Upgrade Swiper Library: Inactive
	Default to New Theme Builder: Inactive
	Editor Top Bar: Inactive by default
	Landing Pages: Inactive
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default
	Page Transitions: Inactive
	Notes: Inactive
	Loop: Inactive
	Form Submissions: Inactive
	Scroll Snap: Inactive
	Menu: Inactive by default

== Log ==
	
Log: showing 20 of 382023-03-30 13:39:58 [info] Elementor/Upgrades - _on_each_version Finished 
2023-03-30 13:39:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.3',
  'to' => '3.12.0',
)]
2023-03-30 13:39:58 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.3',
  'to' => '3.12.0',
)]
2023-04-06 15:39:08 [info] elementor::elementor_updater Started 
2023-04-06 15:39:09 [info] Elementor/Upgrades - _on_each_version Start  
2023-04-06 15:39:09 [info] Elementor/Upgrades - _on_each_version Finished 
2023-04-06 15:39:09 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.0',
  'to' => '3.12.1',
)]
2023-04-06 15:39:09 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.0',
  'to' => '3.12.1',
)]
2023-04-06 19:39:53 [notice] Re-migrate 3.0.0 globals: Start 
2023-04-06 19:39:53 [notice] Re-migrate 3.0.0 globals: _v_3_0_0_move_default_typography_to_kit 
2023-04-06 19:39:53 [notice] Re-migrate 3.0.0 globals: _v_3_0_0_move_default_colors_to_kit 
2023-04-06 19:39:53 [notice] Re-migrate 3.0.0 globals: _v_3_0_0_move_saved_colors_to_kit 
2023-04-06 19:39:53 [notice] Re-migrate 3.0.0 globals: End 
2023-04-06 19:45:06 [notice] System typography already exist. nothing to do. 
2023-04-06 19:45:06 [notice] System colors already exist. nothing to do. 
2023-04-06 19:45:06 [notice] Custom colors already exist. nothing to do. 
2023-04-06 20:39:17 [info] elementor-pro::elementor_pro_updater Started 
2023-04-06 20:39:17 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-04-06 20:39:17 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-04-06 20:39:17 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.3',
  'to' => '3.12.1',
)]

PHP: showing 3 of 3PHP: 2023-03-03 22:58:08 [notice X 22][/host/wh_4me2t9/docroot/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-30 13:42:37 [error X 1][/host/wh_4me2t9/docroot/wp-content/plugins/elementor-pro/modules/posts/data/controller.php::12] Uncaught Error: Class &#039;ElementorPro\Data\Base\Controller&#039; not found in /host/wh_4me2t9/docroot/wp-content/plugins/elementor-pro/modules/posts/data/controller.php:12
Stack trace:
#0 /host/wh_4me2t9/docroot/wp-content/plugins/elementor-pro/plugin.php(159): include()
#1 [internal function]: ElementorPro\Plugin-&gt;autoload(&#039;ElementorPro\\Mo...&#039;)
#2 /host/wh_4me2t9/docroot/wp-content/plugins/elementor/data/manager.php(88): spl_autoload_call(&#039;ElementorPro\\Mo...&#039;)
#3 /host/wh_4me2t9/docroot/wp-content/plugins/elementor-pro/modules/posts/module.php(99): Elementor\Data\Manager-&gt;register_controller(&#039;ElementorPro\\Mo...&#039;)
#4 /host/wh_4me2t9/docroot/wp-content/plugins/elementor/core/base/module.php(85): ElementorPro\Modules\Posts\Module-&gt;__construct()
#5 /host/wh_4me2t9/docroot/wp-content/plugins/elementor-pro/core/modules-manager.php(87): Elementor\Core\Base\Module::instance()
#6 /host/wh_4me2t9/docroot/wp-content/plugins/elementor-pro/plugin.php(363): ElementorPro\Core\Modules_Manager-&gt;__construct()
#7 /host/wh_4me2t9/d [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-06 19:39:53 [notice X 2][/host/wh_4me2t9/docroot/wp-content/plugins/elementor/core/upgrade/elementor-3-re-migrate-globals.php::102] Undefined variable: active_kit_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 2 of 2JS: 2023-03-30 14:19:52 [error X 18][https://freedomvillage-dev.sageage.site/wp-content/plugins/granular-controls-for-elementor/assets/js/granular-editor.min.js?ver=1.0.5:4:4] Cannot read properties of undefined (reading &#039;each&#039;) 
JS: 2023-04-06 20:00:02 [error X 1][https://freedomvillage-dev.sageage.site/wp-content/plugins/elementor/assets/js/import-export-admin.min.js?ver=3.8.0:2:5394] elementorImportExport is not defined 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Incompatible

== Elementor Pro - Compatibility Tag ==

**Comment by macornwell** [comment]
I think I am having the same issue. I have a page, but I cannot edit it because the Footer is overlapping the page contents.
If I go into the browsers developer tools and delete the footer edit node, it allows me to edit the page. Having said that the entire contents of the page are blocked by the invisible div for the footer. (Which is at the bottom of the screen).

**Comment by silentnov** [comment]
does anyone know the solution to it i am having the same error
