### ISSUE TITLE
Elementor Pro / Flexbox / Theme Builder / Woocommerce Subscription / Product Bundles BROKEN

### ISSUE THREAD

**Issue by berkmh** [elementor/elementor#21961]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of E
- lementor.

### Description

using theme builder and flexbox with subscription or bundles breaks the sub/bundle product pages. 

### Steps to reproduce

1. Activate flex box containers
2. Activate Woocommerce and Woocommerce Subscriptions or Product Bundles 
3. Create Subscription or Bundle product 
4. Create regular single product
5. Build product page on theme builder with at least 2 containers side by side row and an accordion widget
6.  compare regular product to subscription (or bundle) 
7.  deactivate woocommerce subscritptions and check the product again 

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release '43', Revision 'c1b94a6cfd7' v5.7.40-43
	PHP Version: 8.0.28
	PHP Memory Limit: 512M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2
	Site URL: https://cb420.wpengine.com
	Home URL: https://cb420.wpengine.com
	WP Multisite: No
	Max Upload Size: 50 MB
	Memory limit: 256M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/Phoenix
	Debug Mode: Active

== Theme ==
	Name: child
	Version: 0.1
	Child Theme: Yes
	Parent Theme Name: GeneratePress
	Parent Theme Version: 3.3.0
	Parent Theme Author: Tom Usborne

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.4 Safari/605.1.15

== Active Plugins ==
	Add To Cart Redirect for WooCommerce
		Version: 1.1.3
		Author: Jeroen Sormani

	CheckoutWC
		Version: 7.10.5
		Author: Objectiv

	Elementor
		Version: 3.11.5
		Author: Elementor.com

	Elementor Pro
		Version: 3.11.6
		Author: Elementor.com

	Post Types Order
		Version: 2.0.2
		Author: Nsp Code

	SOGO Add Script Header Footer
		Version: 3.9
		Author: orenhav (SOGO)

	Stop Emails
		Version: 1.2.1
		Author: Sal Ferrarello

	WooCommerce
		Version: 7.5.1
		Author: Automattic

	WooCommerce Load More Products
		Version: 3.1.7.7
		Author: BeRocket

	WooCommerce Subscriptions
		Version: 4.6.0
		Author: WooCommerce

== Must-Use Plugins ==
	Force Strong Passwords - WPE Edition
		Version: 1.8.0
		Author: Jason Cosper

	Health Check Troubleshooting Mode
		Version: 1.8.1
		Author: 

	Perfmatters MU
		Version: 2.0.9
		Author: forgemedia

	WP Engine Cache Plugin
		Version: 1.1.2
		Author: WP Engine

	WP Engine Seamless Login Plugin
		Version: 1.6.0
		Author: WP Engine

	WP Engine Security Auditor
		Version: 1.0.10
		Author: wpengine

	WP Engine System
		Version: 5.0.1
		Author: WP Engine

== Elements Usage ==
	
	container : 24
		accordion : 2
		button : 4
		container : 29
		divider : 2
		heading : 35
		html : 1
		icon : 5
		icon-list : 1
		image : 22
		image-box : 3
		nav-menu : 13
		posts : 4
		search-form : 4
		share-buttons : 3
		shortcode : 8
		social-icons : 1
		text-editor : 31
		theme-site-logo : 4
		woocommerce-breadcrumb : 1
		woocommerce-product-add-to-cart : 2
		woocommerce-product-images : 1
		woocommerce-product-meta : 1
		woocommerce-product-price : 2
		woocommerce-product-short-description : 1
		woocommerce-product-title : 2
	footer : 2
		container : 1
		heading : 1
		icon : 1
		icon-list : 1
		text-editor : 1
	header : 4
		container : 3
		html : 1
		icon : 3
		nav-menu : 4
		theme-site-logo : 1
	page : 13
		accordion : 4
		button : 24
		container : 25
		divider : 15
		heading : 50
		html : 1
		image : 36
		image-box : 29
		posts : 4
		share-buttons : 1
		spacer : 3
		star-rating : 3
		testimonial-carousel : 3
		text-editor : 85
	popup : 2
		container : 1
		image-box : 1
	product : 1
		accordion : 1
		container : 5
		heading : 4
		image : 8
		posts : 1
		shortcode : 4
		text-editor : 2
		woocommerce-breadcrumb : 1
		woocommerce-product-add-to-cart : 1
		woocommerce-product-images : 1
		woocommerce-product-price : 1
		woocommerce-product-title : 1
	section : 53
		button : 9
		divider : 9
		heading : 31
		html : 3
		image : 21
		media-carousel : 1
		nav-menu : 12
		posts : 3
		search-form : 3
		share-buttons : 1
		shortcode : 8
		slides : 1
		text-editor : 52
		theme-site-logo : 3
		woocommerce-breadcrumb : 4
		woocommerce-product-add-to-cart : 1
		woocommerce-product-meta : 1
		woocommerce-product-price : 1
		woocommerce-product-short-description : 1
		woocommerce-product-title : 1
	widget : 0
		divider : 1
		form : 1
		heading : 1
		image : 2
		posts : 4
		social-icons : 1
		text-editor : 2
		woocommerce-product-images : 1
		woocommerce-products : 1
	wp-post : 44
		accordion : 2
		button : 13
		container : 21
		divider : 2
		heading : 36
		html : 12
		image : 38
		image-box : 6
		menu-anchor : 1
		posts : 2
		star-rating : 2
		testimonial-carousel : 2
		text-editor : 67
	wp-page : 31
		button : 2
		container : 12
		countdown : 1
		divider : 6
		heading : 13
		html : 2
		image : 17
		image-box : 40
		posts : 1
		share-buttons : 4
		shortcode : 1
		sitemap : 1
		social-icons : 1
		spacer : 6
		text-editor : 29
		video : 1
		woocommerce-breadcrumb : 1
	product-archive : 4
		container : 2
		heading : 4
		image : 3
		posts : 1
		text-editor : 2
		theme-archive-title : 1
		wc-archive-products : 1
		woocommerce-breadcrumb : 1

== Settings ==
	
	cpt_support: post, page, product
	disable_color_schemes: yes
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap

== Features ==
	Custom Fonts: 3
	Custom Icons: 1

== Integrations ==
	
	recaptcha_v3: Active
	woocommerce: Active

== Elementor Experiments ==
	Optimized DOM Output: Inactive
	Improved Asset Loading: Inactive
	Improved CSS Loading: Inactive
	Inline Font Icons: Inactive
	Accessibility Improvements: Inactive
	Additional Custom Breakpoints: Inactive
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Inactive
	Default to New Theme Builder: Inactive
	Editor V2: Inactive by default
	Landing Pages: Inactive
	Nested Elements: Inactive
	Lazy Load Background Images: Inactive by default
	Save as Default: Inactive
	Page Transitions: Inactive
	Notes: Inactive
	Loop: Inactive
	Form Submissions: Inactive
	Scroll Snap: Inactive
	Mega Menu: Inactive by default

== Log ==
	
Log: showing 20 of 332023-04-05 15:41:36 [info] elementor-pro::elementor_pro_updater Started 
2023-04-05 15:41:36 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-04-05 15:41:36 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-04-05 15:41:36 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.0',
  'to' => '3.12.1',
)]
2023-04-05 15:41:39 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.0',
  'to' => '3.12.1',
)]
2023-04-05 15:41:39 [info] elementor-pro::elementor_pro_updater Started 
2023-04-05 15:41:39 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-04-05 15:41:39 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-04-05 15:41:39 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.0',
  'to' => '3.12.1',
)]
2023-04-05 15:41:41 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.0',
  'to' => '3.12.1',
)]
2023-04-05 15:42:17 [info] elementor-pro::elementor_pro_updater Started 
2023-04-05 15:42:17 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-04-05 15:42:17 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-04-05 15:42:17 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.0',
  'to' => '3.12.1',
)]
2023-04-05 15:42:22 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.0',
  'to' => '3.12.1',
)]
2023-04-05 15:42:22 [info] elementor-pro::elementor_pro_updater Started 
2023-04-05 15:42:22 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-04-05 15:42:22 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-04-05 15:42:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.0',
  'to' => '3.12.1',
)]
2023-04-05 15:42:23 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.0',
  'to' => '3.12.1',
)]

PHP: showing 3 of 3PHP: 2023-04-05 15:58:25 [error X 1][/nas/content/live/cb420/wp-content/plugins/elementor/core/modules-manager.php::53] Uncaught Error: Class "Elementor\Modules\Announcements\Module" not found in /nas/content/live/cb420/wp-content/plugins/elementor/core/modules-manager.php:53
Stack trace:
#0 /nas/content/live/cb420/wp-content/plugins/elementor/includes/plugin.php(730): Elementor\Core\Modules_Manager->__construct()
#1 /nas/content/live/cb420/wp-content/plugins/elementor/includes/plugin.php(647): Elementor\Plugin->init_components()
#2 /nas/content/live/cb420/wp-includes/class-wp-hook.php(308): Elementor\Plugin->init('')
#3 /nas/content/live/cb420/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#4 /nas/content/live/cb420/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#5 /nas/content/live/cb420/wp-settings.php(623): do_action('init')
#6 /nas/content/live/cb420/wp-config.php(129): require_once('/nas/content/li...')
#7 /nas/content/live/cb420/wp-load.php(50): require_once('/nas/content/li...')
#8 /nas/content/live/cb420/wp-admin/admin.php(34): require_once('/nas/content/li...')
#9 /nas/content/live/cb420/wp-admin/update.php(16): require_once('/nas/content/li...')
#10 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-05 15:58:28 [error X 2][/nas/content/live/cb420/wp-content/plugins/elementor/core/modules-manager.php::53] Uncaught Error: Class "Elementor\Modules\Announcements\Module" not found in /nas/content/live/cb420/wp-content/plugins/elementor/core/modules-manager.php:53
Stack trace:
#0 /nas/content/live/cb420/wp-content/plugins/elementor/includes/plugin.php(730): Elementor\Core\Modules_Manager->__construct()
#1 /nas/content/live/cb420/wp-content/plugins/elementor/includes/plugin.php(647): Elementor\Plugin->init_components()
#2 /nas/content/live/cb420/wp-includes/class-wp-hook.php(308): Elementor\Plugin->init('')
#3 /nas/content/live/cb420/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#4 /nas/content/live/cb420/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#5 /nas/content/live/cb420/wp-settings.php(623): do_action('init')
#6 /nas/content/live/cb420/wp-config.php(129): require_once('/nas/content/li...')
#7 /nas/content/live/cb420/wp-load.php(50): require_once('/nas/content/li...')
#8 /nas/content/live/cb420/wp-admin/admin.php(34): require_once('/nas/content/li...')
#9 /nas/content/live/cb420/wp-admin/plugins.php(10): require_once('/nas/content/li...')
#10 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-05 15:58:30 [error X 2][/nas/content/live/cb420/wp-content/plugins/elementor/core/modules-manager.php::53] Uncaught Error: Class "Elementor\Modules\Announcements\Module" not found in /nas/content/live/cb420/wp-content/plugins/elementor/core/modules-manager.php:53
Stack trace:
#0 /nas/content/live/cb420/wp-content/plugins/elementor/includes/plugin.php(730): Elementor\Core\Modules_Manager->__construct()
#1 /nas/content/live/cb420/wp-content/plugins/elementor/includes/plugin.php(647): Elementor\Plugin->init_components()
#2 /nas/content/live/cb420/wp-includes/class-wp-hook.php(308): Elementor\Plugin->init('')
#3 /nas/content/live/cb420/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#4 /nas/content/live/cb420/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#5 /nas/content/live/cb420/wp-settings.php(623): do_action('init')
#6 /nas/content/live/cb420/wp-config.php(129): require_once('/nas/content/li...')
#7 /nas/content/live/cb420/wp-load.php(50): require_once('/nas/content/li...')
#8 /nas/content/live/cb420/wp-admin/admin-ajax.php(22): require_once('/nas/content/li...')
#9 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 7 of 7JS: 2023-04-07 03:22:24 [error X 10][https://cb420.wpengine.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.11.5:3:791668] undefined is not an object (evaluating 'this.store.find((function(T){return T.original===C})).localized') 
JS: 2023-04-07 03:32:36 [error X 1][https://cb420.wpengine.com/wp-content/plugins/elementor/assets/js/common.min.js?ver=3.11.5:3:156434] Can't find variable: DialogsManager 
JS: 2023-04-07 03:32:36 [error X 1][https://cb420.wpengine.com/wp-content/plugins/elementor/assets/js/app-loader.min.js?ver=3.11.5:2:49420] Can't find variable: $e 
JS: 2023-04-07 03:32:36 [error X 1][https://cb420.wpengine.com/wp-content/plugins/elementor-pro/assets/js/editor.min.js:2:61411] Object.entries requires that input parameter not be null or undefined 
JS: 2023-04-07 03:32:37 [error X 1][https://cb420.wpengine.com/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.11.5:2:4812] undefined is not an object (evaluating 'elementorFrontend.config.elements.data') 
JS: 2023-04-07 04:53:29 [error X 1][https://cb420.wpengine.com/wp-content/plugins/elementor/assets/js/new-template.min.js?ver=3.11.5:2:2968] Can't find variable: elementor_new_template_form_controls 
JS: 2023-04-07 05:00:11 [error X 1][https://cb420.wpengine.com/wp-content/plugins/elementor/assets/js/admin.min.js?ver=3.11.5:2:10991] undefined is not an object (evaluating 'this.getExperimentSelect(e).value=t') 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

**Comment by berkmh** [comment]
please close. was other issue.
