### ISSUE TITLE
Sticky effects not working properly in Chrome Related, postion of Header Changes on Scroll (Chrome Only)

### ISSUE THREAD

**Issue by HasaanCh** [elementor/elementor#21970]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi There,
I checked there are several issues opened for Stick Feature for the Containers. 
I am here to add one more.

If I scroll down in Mobile the header moves upwards, it's only happening in Chrome.
On some pages, it's working fine but on some pages, it's not.

This issue persists Even If I try to use custom CSS => 
```
#header
{
position:sticky;
top:0px;
}
```

https://user-images.githubusercontent.com/13096541/230689769-2f58c740-a06e-4bf4-941b-a32558b8cb3d.mp4

This issue occurs when any of the elements on the Page is overflowing. 

### Steps to reproduce

1) Add header
2) Enable sticky for mobile 
3) Add overflowing content on the page (Image and add 20px margin on all sides to its container)

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.3.38
	PHP Version: 7.4.33
	PHP Memory Limit: 1024M
	PHP Max Input Vars: 2000
	PHP Max Post Size: 1024M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2
	Site URL: https://demotest.broadwaytheatreleague.org
	Home URL: https://demotest.broadwaytheatreleague.org
	WP Multisite: No
	Max Upload Size: 1 GB
	Memory limit: 40M
	Max Memory limit: 1024M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/Chicago
	Admin Email: kelsey@lawrencemediaatl.com
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor Child
	Version: 2.3.1.1622736063
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.7.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0

== Active Plugins ==
	Admin Menu Editor
		Version: 1.11
		Author: Janis Elsts

	Advanced Custom Fields PRO
		Version: 5.11.4
		Author: Delicious Brains

	Better Search Replace
		Version: 1.4.2
		Author: WP Engine

	Bulk Actions for Gravity Forms
		Version: 1.1.2
		Author: JetSloth

	Child Theme Configurator
		Version: 2.6.0
		Author: Lilaea Media

	Classic Editor
		Version: 1.6.3
		Author: WordPress Contributors

	Custom JavaScript & CSS in Pages!
		Version: 2.9
		Author: Lagudi Domenico

	Custom Post Type UI
		Version: 1.13.5
		Author: WebDevStudios

	Custom Users Data import by Hasaan Jamil
		Version: 
		Author: 

	Duplicate Page
		Version: 4.5.1
		Author: mndpsingh287

	Easy Updates Manager
		Version: 9.0.14
		Author: Easy Updates Manager Team

	Elementor
		Version: 3.12.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.12.1
		Author: Elementor.com

	Gmail SMTP
		Version: 1.2.3.6
		Author: naa986

	Google Analytics Dashboard for WP (GADWP)
		Version: 7.14.1
		Author: ExactMetrics

	Gravity Forms
		Version: 2.5.16.3
		Author: Gravity Forms

	Gravity Forms Survey Add-On
		Version: 3.7
		Author: Gravity Forms

	Gravity PDF
		Version: 6.5.5
		Author: Blue Liquid Designs

	Members
		Version: 3.2.4
		Author: MemberPress

	Meta pixel for WordPress
		Version: 3.0.8
		Author: Facebook

	Multiple Columns for Gravity Forms
		Version: 4.0.6
		Author: WebHolism

	Rank Math SEO
		Version: 1.0.110.2
		Author: Rank Math

	Unlimited Elements for Elementor (Premium)
		Version: 1.5.58
		Author: Unlimited Elements

	UpdraftPlus - Backup/Restore
		Version: 2.16.56.25
		Author: UpdraftPlus.Com, DavidAnderson

	User Roles and Capabilities
		Version: 1.2.6
		Author: mahabub

	WebP Express
		Version: 0.25.5
		Author: Bjørn Rosell

	WordPress Backup & Security Plugin - BlogVault
		Version: 4.97
		Author: Backup by BlogVault

	WP Cerber Security, Anti-spam & Malware Scan
		Version: 9.0
		Author: Cerber Tech Inc.

	WP File Manager
		Version: 7.1.8
		Author: mndpsingh287

	WP phpMyAdmin
		Version: 5.2.1.02
		Author: Puvox.software

	WP Rollback
		Version: 1.7.3
		Author: GiveWP.com

	WP Test Email
		Version: 1.1.6
		Author: Boopathi Rajan

== Must-Use Plugins ==
	aaa-wp-cerber.php
		Version: 1.0
		Author: Cerber Tech Inc.

== Elements Usage ==
	
	footer : 2
		container : 5
		form : 1
		heading : 16
		icon-box : 4
		icon-list : 12
		image : 8
		image-carousel : 2
		nav-menu : 2
		search-form : 1
		spacer : 1
		text-editor : 1
	header : 4
		button : 12
		container : 14
		icon : 1
		icon-list : 8
		image : 5
		nav-menu : 4
	page : 11
		button : 3
		divider : 1
		form : 2
		heading : 27
		icon : 1
		icon-list : 20
		image : 10
		image-carousel : 2
		nav-menu : 3
		search-form : 1
		share-buttons : 1
		slides : 1
		spacer : 5
		text-editor : 17
	popup : 13
		button : 1
		form : 8
		heading : 16
		icon-list : 2
		image : 2
		nav-menu : 2
		search-form : 1
		share-buttons : 1
		text-editor : 1
	section : 8
		button : 8
		form : 2
		google_maps : 1
		heading : 13
		icon-box : 4
		image : 9
		slides : 1
		text-editor : 7
		toggle : 1
		video : 1
	widget : 0
		button : 1
		form : 1
	wp-post : 6
		button : 21
		container : 2
		divider : 4
		form : 3
		gallery : 1
		google_maps : 3
		heading : 66
		html : 1
		icon-box : 6
		icon-list : 10
		image : 15
		image-box : 7
		share-buttons : 1
		shortcode : 2
		slides : 3
		spacer : 8
		template : 5
		text-editor : 58
		theme-post-title : 1
		toggle : 1
	wp-page : 57
		button : 68
		container : 197
		divider : 19
		form : 1
		heading : 199
		html : 5
		icon : 3
		icon-box : 3
		icon-list : 30
		image : 115
		image-carousel : 2
		nav-menu : 2
		posts : 2
		search-form : 2
		shortcode : 2
		spacer : 1
		template : 6
		text-editor : 147
		ucaddon_mega_slider : 1
		ucaddon_uc_card_post_carousel : 1
		ucaddon_uc_video_content_slider : 1
	single-post : 4
		button : 1
		container : 3
		gallery : 1
		heading : 9
		icon-box : 2
		icon-list : 1
		image : 1
		image-carousel : 2
		posts : 1
		share-buttons : 2
		shortcode : 3
		template : 1
		text-editor : 5
		theme-post-content : 2
		theme-post-featured-image : 1
		theme-post-title : 3
		ucaddon_uc_card_post_carousel : 1
		video : 2

== Settings ==
	
	cpt_support: post, page
	allow_tracking: yes
	css_print_method: internal
	load_fa4_shim: yes

== Features ==
	Custom Fonts: 1
	Custom Icons: 0

== Integrations ==
	
	recaptcha_v3: Active

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active
	Default to New Theme Builder: Active
	Hello Theme Header & Footer: Active
	Editor Top Bar: Active
	Landing Pages: Active
	Nested Elements: Active
	Lazy Load Background Images: Active
	Page Transitions: Active
	Notes: Active
	Loop: Active
	Form Submissions: Active
	Scroll Snap: Active
	Menu: Active

== Log ==
	
JS: showing 4 of 4JS: 2023-03-03 13:27:28 [error X 13][https://demotest.broadwaytheatreleague.org/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:51824] Cannot read properties of undefined (reading 'replace') 
JS: 2023-03-14 11:05:22 [error X 80][https://demotest.broadwaytheatreleague.org/wp-content/plugins/elementor-pro/assets/js/frontend.min.js:2:19893] can't access property "handlers", elementorModules.frontend is undefined 
JS: 2023-04-04 21:16:46 [error X 4][https://demotest.broadwaytheatreleague.org/wp-content/plugins/elementor/assets/js/editor.min.js:3:302880] can't access property "id", T.params.args.data is undefined 
JS: 2023-04-05 20:04:34 [error X 191][https://demotest.broadwaytheatreleague.org/wp-content/plugins/elementor/assets/js/editor.min.js:3:624519] can't access property "get", B is undefined 

Log: showing 20 of 302023-03-14 21:42:42 [info] elementor::elementor_updater Started 
2023-03-14 21:42:42 [info] Elementor/Upgrades - _on_each_version Start  
2023-03-14 21:42:43 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.4',
  'to' => '3.11.5',
)]
2023-03-14 21:42:44 [info] Elementor/Upgrades - _on_each_version Finished 
2023-03-14 21:42:44 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.4',
  'to' => '3.11.5',
)]
2023-03-29 21:47:12 [info] elementor::elementor_updater Started 
2023-03-29 21:47:12 [info] Elementor/Upgrades - _on_each_version Start  
2023-03-29 21:47:12 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.5',
  'to' => '3.12.0',
)]
2023-03-29 21:47:14 [info] Elementor/Upgrades - _on_each_version Finished 
2023-03-29 21:47:14 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.5',
  'to' => '3.12.0',
)]
2023-04-02 21:40:51 [info] elementor::elementor_updater Started 
2023-04-02 21:40:51 [info] Elementor/Upgrades - _on_each_version Start  
2023-04-02 21:40:52 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.0',
  'to' => '3.12.1',
)]
2023-04-02 21:40:52 [info] Elementor/Upgrades - _on_each_version Finished 
2023-04-02 21:40:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.0',
  'to' => '3.12.1',
)]
2023-04-04 07:09:05 [info] elementor-pro::elementor_pro_updater Started 
2023-04-04 07:09:05 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-04-04 07:09:05 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-04-04 07:09:05 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.3',
  'to' => '3.12.1',
)]
2023-04-04 07:09:05 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.3',
  'to' => '3.12.1',
)]

PHP: showing 8 of 8PHP: 2023-04-04 06:58:19 [notice X 28][/home/broadwaytheatre/demotest.broadwaytheatreleague.org/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-image.php::59] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-04 06:59:07 [notice X 52][/home/broadwaytheatre/demotest.broadwaytheatreleague.org/wp-content/plugins/elementor/includes/widgets/video.php::1236] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-04 07:00:26 [notice X 17][/home/broadwaytheatre/demotest.broadwaytheatreleague.org/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-04 07:02:06 [notice X 1][/home/broadwaytheatre/demotest.broadwaytheatreleague.org/wp-content/plugins/elementor/includes/widgets/video.php::1236] Trying to access array offset on value of type null [array (
  'trace' => '
#0: /home/broadwaytheatre/demotest.broadwaytheatreleague.org/wp-content/plugins/elementor/includes/widgets/video.php(1236): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/broadwaytheatre/demotest.broadwaytheatreleague.org/wp-content/plugins/elementor/includes/widgets/video.php(1052): Elementor\Widget_Video -> get_hosted_video_url()
#2: /home/broadwaytheatre/demotest.broadwaytheatreleague.org/wp-content/plugins/elementor/includes/db.php(202): Elementor\Widget_Video -> render_plain_content()
#3: /home/broadwaytheatre/demotest.broadwaytheatreleague.org/wp-content/plugins/elementor/includes/db.php(208): Elementor\DB -> render_element_plain_content()
#4: /home/broadwaytheatre/demotest.broadwaytheatreleague.org/wp-content/plugins/elementor/includes/db.php(208): Elementor\DB -> render_element_plain_content()
',
)]
PHP: 2023-04-04 07:09:40 [notice X 1][/home/broadwaytheatre/demotest.broadwaytheatreleague.org/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-image.php::40] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-04 10:32:49 [error X 3][/home/broadwaytheatre/demotest.broadwaytheatreleague.org/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::295] Uncaught Error: Call to a member function update_meta() on bool in /home/broadwaytheatre/demotest.broadwaytheatreleague.org/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:295
Stack trace:
#0 /home/broadwaytheatre/demotest.broadwaytheatreleague.org/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(168): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/broadwaytheatre/demotest.broadwaytheatreleague.org/wp-content/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/broadwaytheatre/demotest.broadwaytheatreleague.org/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-05 14:54:03 [notice X 1][/home/broadwaytheatre/demotest.broadwaytheatreleague.org/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::168] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-07 13:20:08 [notice X 16][/home/broadwaytheatre/demotest.broadwaytheatreleague.org/wp-content/plugins/elementor-pro/modules/posts/skins/skin-content-base.php::265] Trying to get property 'ID' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	Unlimited Elements for Elementor (Premium): Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by sinanisler** [comment]
selector{
position:fixed
width:100%
height:90px 
}

try this on container
sticky doesn't work properly anymore.

**Comment by Thomas-Boi** [comment]
@sinanisler glad it's not just me noticing it. I recently updated mine and found that it stops working in Desktop on both Chrome and Firefox. Considering opening an issue but I found a CSS solution so it doesn't affect me much.

**Comment by Thomas-Boi** [comment]
> @sinanisler glad it's not just me noticing it. I recently updated mine and found that it stops working in Desktop on both Chrome and Firefox. Considering opening an issue but I found a CSS solution so it doesn't affect me much.

Just to note that I recently updated Elementor to Version 3.12.1 and Elementor Pro to Version 3.12.2 and this issue hasn't occured to me again. Try upgrading your plugins to the latest versions.
