### ISSUE TITLE
⛔ 🐞 Bug Report: Mini Cart show empty

### ISSUE THREAD

**Issue by weshcanneapeche** [elementor/elementor#21994]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Mini cart is empty when Elementor PRO 3.12.2 is active with Woodmart 7.1.4 theme
Mini cart work perfecly when Elementor PRO is disable

Same problem as https://github.com/elementor/elementor/issues/21836

PROBLEM IS NOT RESOLVE WITH VERSION 3.12.2 

### Steps to reproduce

1) Use Woodmart theme
2) Activate Elementor PRO 3.12.2
3) Open mini cart

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MySQL Community Server - GPL v8.0.32
	PHP Version: 7.4.33
	PHP Memory Limit: 
	PHP Max Input Vars: 10000
	PHP Max Post Size: 1024M
	GD Installed: Yes
	ZIP Installed: No
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2
	Site URL: https://sosilky.store
	Home URL: https://sosilky.store
	WP Multisite: No
	Max Upload Size: 1 Go
	Memory limit: 256M
	Max Memory limit: 1024M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: fr-FR
	Timezone: Europe/Paris
	Admin Email: admin@sosilky.store
	Debug Mode: Inactive

== Theme ==
	Name: Woodmart
	Version: 7.1.4
	Author: XTemos
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: fr_FR
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36

== Active Plugins ==
	Contact Form 7
		Version: 5.7.5.1
		Author: Takayuki Miyoshi

	Elementor
		Version: 3.12.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.12.2
		Author: Elementor.com

	MC4WP: Mailchimp for WordPress
		Version: 4.9.3
		Author: ibericode

	WooCommerce
		Version: 7.5.1
		Author: Automattic

	WooCommerce PayPal Payments
		Version: 2.0.4
		Author: WooCommerce

	WooCommerce Stripe Gateway
		Version: 7.2.0
		Author: WooCommerce

	Woodmart Core
		Version: 1.0.36
		Author: 


== Utilisation des éléments ==
	
	wp-post : 0
		accordion : 1
		spacer : 1
		video : 2
		wd_accordion : 1
		wd_button : 7
		wd_contact_form_7 : 1
		wd_image_or_svg : 11
		wd_images_gallery : 12
		wd_infobox : 37
		wd_list : 5
		wd_products_brands : 1
		wd_social_buttons : 5
		wd_text_block : 24
		wd_title : 16
	wp-page : 3
		animated-headline : 1
		divider : 1
		heading : 1
		html : 2
		image : 7
		image-carousel : 3
		reviews : 1
		text-editor : 5
		video : 3
		wc-add-to-cart : 3
		wd_accordion : 1
		wd_button : 1
		wd_contact_form_7 : 2
		wd_counter : 6
		wd_google_map : 1
		wd_image_or_svg : 1
		wd_infobox : 5
		wd_mailchimp : 1
		wd_popup : 1
		wd_products_brands : 1
		wd_social_buttons : 2
		wd_team_member : 4
		wd_text_block : 4
		wd_title : 15


== Réglages ==
	
	cpt_support: post, page, product, portfolio, cms_block, woodmart_slide, woodmart_layout
	disable_color_schemes: yes
	disable_typography_schemes: yes
	allow_tracking: yes
	editor_break_lines: 1
	unfiltered_files_upload: 1
	font_display: swap
	load_fa4_shim: yes


== Fonctionnalités ==
	Custom Fonts: 0
	Custom Icons: 0

== Intégrations ==
	
	woocommerce: Actif


== Expériences d’Elementor ==
	Sortie DOM optimisée: Actif par défaut
	Amélioration du chargement des ressources: Actif par défaut
	Optimisation du chargement du CSS: Actif par défaut
	Icônes de police « inline »: Inactif par défaut
	Améliorations de l’accessibilité: Actif par défaut
	Points d’arrêt personnalisés supplémentaires: Actif par défaut
	admin_menu_rearrangement: Inactif par défaut
	Conteneur Flexbox: Inactif par défaut
	Mettre à niveau la bibliothèque Swiper: Actif par défaut
	Par défaut vers le Nouveau constructeur de thème: Actif par défaut
	Editor Top Bar: Inactif par défaut
	Page d’atterrissage: Actif par défaut
	Éléments imbriqués: Inactif par défaut
	Chargement différé des images d’arrière-plan: Inactif par défaut
	Transitions des pages: Actif par défaut
	Notes: Actif par défaut
	Boucle: Actif par défaut
	Envois de formulaire: Actif par défaut
	Accroche de défilement: Actif par défaut
	Menu: Inactif par défaut


== Journal ==
	
PHP: showing 4 of 4PHP: 2023-04-04 12:25:27 [notice X 11][/home/sosilkys/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-04 13:19:40 [error X 3][/home/sosilkys/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::295] Uncaught Error: Call to a member function update_meta() on bool in /home/sosilkys/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:295
Stack trace:
#0 /home/sosilkys/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(168): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/sosilkys/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/sosilkys/public_html/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/sosilkys/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#5 /home/sosilkys/pu [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-05 10:58:28 [warning X 1][/home/sosilkys/public_html/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/icons/custom-icons.php::199] unlink(trustpilot-1.svg): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-10 18:08:21 [error X 1][/home/sosilkys/public_html/wp-content/plugins/elementor-pro/modules/woocommerce/module.php::873] syntax error, unexpected 'add_action' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 3 of 3JS: 2023-04-04 17:20:15 [error X 1][https://sosilky.store/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view186567") has already been destroyed and cannot be used. 
JS: 2023-04-04 17:46:38 [error X 1][https://sosilky.store/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view7952") has already been destroyed and cannot be used. 
JS: 2023-04-08 09:26:50 [error X 2][https://sosilky.store/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.12.1:3:632658] Cannot read properties of undefined (reading 'isDesignable') 

Log: showing 6 of 62023-04-10 16:48:54 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.1',
  'to' => '3.12.2',
)]
2023-04-10 16:48:55 [info] elementor-pro::elementor_pro_updater Started 
2023-04-10 16:48:55 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-04-10 16:48:55 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-04-10 16:48:55 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.1',
  'to' => '3.12.2',
)]
2023-04-10 16:48:57 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.1',
  'to' => '3.12.2',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Non compatible

== Elementor Pro - Compatibility Tag ==
	

				

````

</details>

**Comment by nicholaszein** [comment]
Hello @weshcanneapeche,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
- If you're using the Mini Cart from your theme, or from another plugin, you need to remember to turn off the WooCommerce integration option in your `Dashboard` > `Elementor` > `Settings` > `Advanced` page.
- We see in your System Info that the option in question is currently active:
![image](https://user-images.githubusercontent.com/113993460/230959154-40248fac-da4c-4d2c-810d-83361264aa26.png)


### ✅ What you can do to solve your issue:
- Turn the option off as explained at the end of [this article](https://elementor.com/help/menu-cart-widget-pro/).
![image](https://user-images.githubusercontent.com/113993460/230959482-679fac07-9b36-4235-ae4f-e52f029ec0a5.png)


### 👍 For now, that's all we can help with. 

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
