### ISSUE TITLE
The multi select feature does not work in certain situations.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#22115]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi elementor tem!

The multi select feature does not work in certain situations, which I will explain below.

If we click on this part (image below) to select several widgets, the widgets will be selected without any problem.

![1](https://user-images.githubusercontent.com/77163248/233050157-2b5ad0a6-3b84-49c5-80f2-4ddc511b9b61.png)

But if we click on this part (image below) to select multiple widgets, the multiple selection feature does not work.

![2](https://user-images.githubusercontent.com/77163248/233050450-345e8bfe-b2ca-40b8-b475-de2a003c87bb.png)

**It should be noted that this method works well in some widgets, but not in most widgets.**

### Steps to reproduce

According to the two images above, try to select multiple widgets. According to the second image, the multi-select feature is not working.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

					
== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.38 (Win32) OpenSSL/1.1.1a PHP/7.3.2
	MySQL version: mariadb.org binary distribution v5.6.42-84.2
	PHP Version: 7.3.2
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2
	Site URL: http://localhost:85/elementor
	Home URL: http://localhost:85/elementor
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: Asia/Tehran
	Admin Email: hosein.site.98@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.7.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.12.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.12.2
		Author: Elementor.com

== Features ==
	Custom Fonts: 2
	Custom Icons: 0

== Integrations ==
	

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Inactive
	Accessibility Improvements: Inactive
	Additional Custom Breakpoints: Inactive
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Inactive
	Default to New Theme Builder: Inactive
	Hello Theme Header & Footer: Inactive
	Editor Top Bar: Active
	Landing Pages: Inactive
	Nested Elements: Active
	Lazy Load Background Images: Inactive
	Page Transitions: Inactive
	Notes: Inactive
	Loop: Active
	Form Submissions: Active by default
	Scroll Snap: Inactive
	Menu: Active

== Log ==
	
PHP: showing 10 of 10PHP: 2023-04-02 19:17:32 [notice X 3][C:\xampp\htdocs\elementor\wp-content\plugins\elementor\app\modules\import-export\module.php::695] Trying to get property 'label' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-03 00:45:43 [notice X 18][C:\xampp\htdocs\elementor\wp-content\plugins\elementor-pro\core\app\modules\site-editor\data\endpoints\templates.php::150] Undefined index: condition_type [array (
  'trace' => '
#0: C:\xampp\htdocs\elementor\wp-content\plugins\elementor-pro\core\app\modules\site-editor\data\endpoints\templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: C:\xampp\htdocs\elementor\wp-content\plugins\elementor-pro\core\app\modules\site-editor\data\endpoints\templates.php(120): class type array_map()
#3: C:\xampp\htdocs\elementor\wp-content\plugins\elementor-pro\core\app\modules\site-editor\data\endpoints\templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: C:\xampp\htdocs\elementor\wp-content\plugins\elementor\data\base\endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2023-04-05 03:05:55 [error X 3][C:\xampp\htdocs\elementor\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-manager.php::295] Uncaught Error: Call to a member function update_meta() on null in C:\xampp\htdocs\elementor\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-manager.php:295
Stack trace:
#0 C:\xampp\htdocs\elementor\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-manager.php(168): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(794, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 C:\xampp\htdocs\elementor\wp-content\plugins\elementor\core\common\modules\ajax\module.php(175): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 C:\xampp\htdocs\elementor\wp-includes\class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 C:\xampp\htdocs\elementor\wp-includes\class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#5 C:\xampp\htdocs\element [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-06 14:59:54 [error X 1][C:\xampp\htdocs\elementor\wp-content\plugins\elementor\includes\template-library\sources\local.php::1080] Uncaught TypeError: Argument 2 passed to Elementor\TemplateLibrary\Source_Local::on_save_post() must be an instance of WP_Post, null given, called in C:\xampp\htdocs\elementor\wp-includes\class-wp-hook.php on line 310 and defined in C:\xampp\htdocs\elementor\wp-content\plugins\elementor\includes\template-library\sources\local.php:1080
Stack trace:
#0 C:\xampp\htdocs\elementor\wp-includes\class-wp-hook.php(310): Elementor\TemplateLibrary\Source_Local->on_save_post(4998, NULL)
#1 C:\xampp\htdocs\elementor\wp-includes\class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#2 C:\xampp\htdocs\elementor\wp-includes\plugin.php(517): WP_Hook->do_action(Array)
#3 C:\xampp\htdocs\elementor\wp-includes\post.php(4717): do_action('save_post', 4998, NULL, true)
#4 C:\xampp\htdocs\elementor\wp-includes\post.php(4819): wp_insert_post(Array, false, true)
#5 C:\xampp\htdocs\elementor\wp-content\plugins\elementor\includes\db.php(235): wp_update_post(Array)
#6 C:\xampp\htdocs\elementor\wp-content\plugins\elementor\core\base [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-06 15:21:59 [notice X 2][C:\xampp\htdocs\elementor\wp-content\plugins\elementor\includes\managers\image.php::36] Undefined index: id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-07 16:19:35 [notice X 1][C:\xampp\htdocs\elementor\wp-content\plugins\elementor\core\logger\items\js.php::17] Undefined index: url [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-07 19:20:44 [error X 21][C:\xampp\htdocs\elementor\wp-content\plugins\elementor\core\files\assets\manager.php::6] Maximum execution time of 30 seconds exceeded [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-09 05:42:42 [notice X 4][C:\xampp\htdocs\elementor\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-manager.php::168] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-12 20:25:15 [error X 1][C:\xampp\htdocs\elementor\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-manager.php::295] Uncaught Error: Call to a member function update_meta() on bool in C:\xampp\htdocs\elementor\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-manager.php:295
Stack trace:
#0 C:\xampp\htdocs\elementor\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-manager.php(168): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 C:\xampp\htdocs\elementor\wp-content\plugins\elementor\core\common\modules\ajax\module.php(175): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 C:\xampp\htdocs\elementor\wp-includes\class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 C:\xampp\htdocs\elementor\wp-includes\class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#5 C:\xampp\htdocs\elemen [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-17 01:49:20 [notice X 1][C:\xampp\htdocs\elementor\wp-content\plugins\elementor\core\common\modules\ajax\module.php::175] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 16 of 162023-04-03 02:09:15 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.0',
  'to' => '3.12.1',
)]
2023-04-03 02:09:16 [info] elementor-pro::elementor_pro_updater Started 
2023-04-03 02:09:16 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-04-03 02:09:16 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-04-03 02:09:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.0',
  'to' => '3.12.1',
)]
2023-04-03 03:28:01 [info] elementor::elementor_updater Started 
2023-04-03 03:28:01 [info] Elementor/Upgrades - _on_each_version Start  
2023-04-03 03:28:01 [info] Elementor/Upgrades - _on_each_version Finished 
2023-04-03 03:28:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.0',
  'to' => '3.12.1',
)]
2023-04-03 03:28:01 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.0',
  'to' => '3.12.1',
)]
2023-04-09 09:26:57 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.1',
  'to' => '3.12.2',
)]
2023-04-09 09:27:00 [info] elementor-pro::elementor_pro_updater Started 
2023-04-09 09:27:00 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-04-09 09:27:00 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-04-09 09:27:00 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.1',
  'to' => '3.12.2',
)]
2023-04-09 09:27:01 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.1',
  'to' => '3.12.2',
)]

JS: showing 16 of 16JS: 2023-04-02 21:45:56 [error X 4][http://localhost:85/elementor/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.12.0:3:632658] Cannot read properties of undefined (reading 'isDesignable') 
JS: 2023-04-06 10:59:16 [error X 4][http://localhost:85/elementor/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.12.1:3:928670] Cannot read properties of undefined (reading 'view') 
JS: 2023-04-06 19:16:27 [error X 4][http://localhost:85/elementor/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.12.1:3:925514] Cannot read properties of undefined (reading 'settings') 
JS: 2023-04-07 11:45:22 [error X 1440][http://localhost:85/elementor/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:16820] Cannot read properties of null (reading 'clone') 
JS: 2023-04-07 11:45:47 [error X 30][http://localhost:85/elementor/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:21012] Cannot read properties of null (reading 'changestop') 
JS: 2023-04-08 16:00:53 [error X 3][http://localhost:85/elementor/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.12.1:3:785745] Cannot read properties of undefined (reading 'localized') 
JS: 2023-04-12 15:46:39 [error X 2][http://localhost:85/elementor/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.12.1:3:594206] Cannot read properties of null (reading 'id') 
JS: 2023-04-13 09:19:21 [error X 7][http://localhost:85/elementor/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view1351") has already been destroyed and cannot be used. 
JS: 2023-04-14 07:42:58 [error X 4][http://localhost:85/elementor/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view1356") has already been destroyed and cannot be used. 
JS: 2023-04-14 08:57:25 [error X 1][http://localhost:85/elementor/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view4056") has already been destroyed and cannot be used. 
JS: 2023-04-14 09:26:20 [error X 1][http://localhost:85/elementor/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.12.1:3:410136] Cannot read properties of null (reading 'history') 
JS: 2023-04-14 09:27:18 [error X 2][http://localhost:85/elementor/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.12.1:3:1081267] Cannot read properties of null (reading 'getBoundingClientRect') 
JS: 2023-04-14 13:45:59 [error X 1][http://localhost:85/elementor/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view2041") has already been destroyed and cannot be used. 
JS: 2023-04-14 18:33:15 [error X 1][http://localhost:85/elementor/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view14527") has already been destroyed and cannot be used. 
JS: 2023-04-15 15:45:29 [error X 1][http://localhost:85/elementor/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view1519") has already been destroyed and cannot be used. 
JS: 2023-04-16 21:21:24 [error X 1][http://localhost:85/elementor/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view7212") has already been destroyed and cannot be used. 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Incompatible

== Elementor Pro - Compatibility Tag ==

**Comment by jeshuavegas** [comment]
Any solution? Prety bad responsive on desktop
