### ISSUE TITLE
🚧 🐞 Bug Report: Only first condition is imported for templates

### ISSUE THREAD

**Issue by vladninja** [elementor/elementor#22194]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

### Description

![image](https://user-images.githubusercontent.com/76119088/234323469-26e20cd4-35bc-4635-b460-76ddcee40ca6.png)

### Steps to reproduce

1.  Create a template on site 1
2. Add multiple conditions to that template
3. Export Elementor Kit
4. Import Elementor kit to website 2
5. Only the first condition will be imported

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt

== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.54 (Debian)
	MySQL version: MySQL Community Server - GPL v8.0.31
	PHP Version: 7.4.33
	PHP Memory Limit: 
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: No
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: http://localhost:8083
	Home URL: http://localhost:8083
	WP Multisite: No
	Max Upload Size: 2 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: pl-PL
	Timezone: Europe/Warsaw
	Admin Email: [REDACTED]
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: pl_PL
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36

== Active Plugins ==

	Elementor
		Version: 3.10.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.10.2
		Author: Elementor.com

	Polylang
		Version: 3.3.1
		Author: WP SYNTEX

	Polylang Connect for Elementor
		Version: 2.3.5
		Author: Creame


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Landing Pages: Active by default
	Nested Elements: Active
	Lazy Load Background Images: Inactive by default
	Save as Default: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active by default
	Loop Carousel: Inactive by default
	Form Submissions: Active by default
	Scroll Snap: Active by default


== Log ==
	
PHP: showing 5 of 5PHP: 2023-02-15 12:01:58 [notice X 9][/var/www/html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::172] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-15 12:02:02 [notice X 8][/var/www/html/wp-content/plugins/elementor-pro/core/app/modules/import-export/runners/import/templates.php::103] Undefined index: conditions [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-15 12:02:03 [notice X 16][/var/www/html/wp-content/plugins/elementor/core/base/document.php::1563] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-15 12:02:59 [notice X 36][/var/www/html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined index: condition_type [array (
  'trace' => '
#0: /var/www/html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /var/www/html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /var/www/html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /var/www/html/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2023-02-15 12:03:28 [error X 1][/var/www/html/wp-content/plugins/elementor/core/frontend/render-modes/render-mode-base.php::88] Uncaught Error: Call to a member function is_editable_by_current_user() on bool in /var/www/html/wp-content/plugins/elementor/core/frontend/render-modes/render-mode-base.php:88
Stack trace:
#0 /var/www/html/wp-content/plugins/elementor/core/frontend/render-mode-manager.php(133): Elementor\Core\Frontend\RenderModes\Render_Mode_Base->get_permissions_callback()
#1 /var/www/html/wp-content/plugins/elementor/core/frontend/render-mode-manager.php(157): Elementor\Core\Frontend\Render_Mode_Manager->add_current_actions()
#2 /var/www/html/wp-content/plugins/elementor/includes/frontend.php(194): Elementor\Core\Frontend\Render_Mode_Manager->__construct()
#3 /var/www/html/wp-includes/class-wp-hook.php(308): Elementor\Frontend->init_render_mode('')
#4 /var/www/html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#5 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /var/www/html/wp-includes/template-loader.php(13): do_action('template_redire...')
#7 /var/www/html/wp-blog-header. [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible
	Polylang Connect for Elementor: Compatible

== Elementor Pro - Compatibility Tag ==
	
	Polylang Connect for Elementor: Compatible
				
				
````

</details>

**Comment by nicholaszein** [comment]
Hello @vladninja, 

Thank you for submitting your report! 🙏 

### ❌ While reviewing your report, we noticed it was missing some key pieces of information:

- 🆕 **Stay Up-to-date:** Make sure you are using the most recent and stable versions of [Elementor](https://wordpress.org/plugins/elementor/#developers), [Elementor Pro](https://elementor.com/pro/changelog/), [WordPress](https://wordpress.org/download/releases/), and your theme.

- 🔬 **Isolate the problem:** Deactivate all of your plugins (except Elementor/Pro), and temporarily change your WordPress theme to [Hello theme](https://wordpress.org/themes/hello-elementor/). If this solves the problem, gradually activate your plugins and theme one by one, until you spot the conflicting plugin or theme.

- 💬 **Description:**In your description, provide examples, screenshots, and screen recordings (just drag and drop in the field), and save time by describing in detail what happened. The more information you provide, the faster we can find a solution!

Without them, we simply can't help. 😕 

### 🧐 Please provide the missing information above so we can troubleshoot your issue faster and better.

Best regards,

Nick

**Comment by nicholaszein** [comment]
Hello there @vladninja, 

### 🕙 It's been a while since we answered you, and we haven't received any feedback. 

## 🚧 For this reason, we are closing this issue because of no activity.

👉 If you wish to continue this discussion, please follow the guidelines for opening a new [🐞 Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml).

Kind regards
