### ISSUE TITLE
⛔ 🧩 🐞 Bug Report: Woodmart theme conflicting with Elementor 3.13-dev3

### ISSUE THREAD

**Issue by classphoneshop** [elementor/elementor#22192]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

 Error is : 
Parse error: syntax error, unexpected token ";", expecting ")" in /home/clients/fa4546171ffa04b2c5acd403d7e08b4e/sites/classphoneshop.ch/wp-content/themes/woodmart/inc/integrations/elementor/elements/class-google-map.php on line 430

### Steps to reproduce

HI ,i have this problem in my website my site is not working but I can enter my website from the admin panel without any problems and provide full control, but I could not find the problem in any way , When I turn off elementor's plugins, my website works, but since I'm designing with elementor, it must be active all the time, otherwise the page designs are missing can you help me thanks in advance. 

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.7.32
	PHP Version: 8.0.27
	PHP Memory Limit: 512M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 300M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2
	Site URL: https://classphoneshop.ch
	Home URL: https://classphoneshop.ch
	WP Multisite: No
	Max Upload Size: 300 Mo
	Memory limit: 640M
	Max Memory limit: 640M
	Permalink Structure: /%postname%/
	Language: fr-FR
	Timezone: Europe/Zurich
	Admin Email: infos@classphone.ch
	Debug Mode: Inactive

== Theme ==
	Name: Woodmart
	Version: 7.1.4
	Author: XTemos
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: fr_FR
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36

== Active Plugins ==
	Blogger Importer
		Version: 0.9.1
		Author: wordpressdotorg

	Categories to Tags Converter Importer
		Version: 0.6
		Author: wordpressdotorg

	Classic Editor
		Version: 1.6.3
		Author: WordPress Contributors

	Contact Form 7
		Version: 5.7.6
		Author: Takayuki Miyoshi

	Debug Bar
		Version: 1.1.4
		Author: wordpressdotorg

	Divi Builder
		Version: 4.20.4
		Author: Elegant Themes

	Easy HTTPS (SSL) Redirection
		Version: 1.9.1
		Author: Tips and Tricks HQ

	Elementor
		Version: 3.13.0-dev3
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.12.3
		Author: Elementor.com

	Extra product options For WooCommerce | Custom Product Addons and Fields
		Version: 3.2.0
		Author: ThemeHigh

	Instant Images
		Version: 5.2.1
		Author: Darren Cooney

	Jetpack
		Version: 12.0
		Author: Automattic

	Jetpack Boost
		Version: 1.8.0
		Author: Automattic - Jetpack Site Speed team

	Jetpack Protect
		Version: 1.3.0
		Author: Automattic - Jetpack Security team

	Loco Automatic Translate Addon PRO
		Version: 1.5
		Author: Cool Plugins

	Loco Translate
		Version: 2.6.4
		Author: Tim Whitlock

	MC4WP: Mailchimp for WordPress
		Version: 4.9.3
		Author: ibericode

	Safe SVG
		Version: 2.1.1
		Author: 10up

	Slider Revolution
		Version: 6.6.12
		Author: ThemePunch

	VOD Infomaniak
		Version: 1.5.3
		Author: Infomaniak Staff

	WooCommerce
		Version: 7.6.0
		Author: Automattic

	WooCommerce Payments
		Version: 5.7.0
		Author: Automattic

	Woodmart Core
		Version: 1.0.36
		Author: 

	WordPress Importer
		Version: 0.8
		Author: wordpressdotorg

	WP All Import
		Version: 3.7.2
		Author: Soflyy

	WP Armour - Honeypot Anti Spam
		Version: 2.1.3
		Author: Dnesscarkey

	WP Maintenance
		Version: 6.1.3
		Author: Florent Maillefaud

	WP Super Cache
		Version: 1.9.4
		Author: Automattic

	Yoast Duplicate Post
		Version: 4.5
		Author: Enrico Battocchi & Team Yoast


== Fonctionnalités ==
	Custom Fonts: 0
	Custom Icons: 0

== Intégrations ==
	
	google_maps: Actif
	recaptcha_v3: Actif
	woocommerce: Actif


== Expériences d’Elementor ==
	Sortie DOM optimisée: Actif
	Amélioration du chargement des ressources: Actif
	Optimisation du chargement du CSS: Actif
	Icônes de police « inline »: Actif
	Améliorations de l’accessibilité: Actif
	Points d’arrêt personnalisés supplémentaires: Actif
	admin_menu_rearrangement: Inactif par défaut
	Conteneur Flexbox: Actif
	Mettre à niveau la bibliothèque Swiper: Actif
	Grid Container: Actif
	Par défaut vers le Nouveau constructeur de thème: Actif
	Editor Top Bar: Actif
	Page d’atterrissage: Actif
	Éléments imbriqués: Actif
	Chargement différé des images d’arrière-plan: Actif
	Transitions des pages: Actif
	Notes: Actif
	Boucle: Actif
	Envois de formulaire: Actif
	Accroche de défilement: Actif
	Menu: Actif


== Journal ==
	
PHP: showing 7 of 7PHP: 2023-03-23 11:34:20 [warning X 1][/home/clients/fa4546171ffa04b2c5acd403d7e08b4e/sites/classphoneshop.ch/wp-content/plugins/elementor/core/upgrade/elementor-3-re-migrate-globals.php::102] Undefined variable $active_kit_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-23 14:45:39 [error X 2][/home/clients/fa4546171ffa04b2c5acd403d7e08b4e/sites/classphoneshop.ch/wp-content/plugins/elementor/includes/controls/base-multiple.php::59] Allowed memory size of 671088640 bytes exhausted (tried to allocate 20480 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-29 15:48:39 [notice X 1][/home/clients/fa4546171ffa04b2c5acd403d7e08b4e/sites/classphoneshop.ch/wp-content/plugins/elementor-pro/modules/loop-builder/module.php::204] strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-09 17:51:20 [warning X 16][/home/clients/fa4546171ffa04b2c5acd403d7e08b4e/sites/classphoneshop.ch/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined array key &quot;data&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-09 18:58:55 [error X 2][/home/clients/fa4546171ffa04b2c5acd403d7e08b4e/sites/classphoneshop.ch/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::295] Uncaught Error: Call to a member function update_meta() on bool in /home/clients/fa4546171ffa04b2c5acd403d7e08b4e/sites/classphoneshop.ch/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:295
Stack trace:
#0 /home/clients/fa4546171ffa04b2c5acd403d7e08b4e/sites/classphoneshop.ch/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(168): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/clients/fa4546171ffa04b2c5acd403d7e08b4e/sites/classphoneshop.ch/wp-content/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/clients/fa4546171ffa04b2c5acd403d7e08b4e/sites/classphoneshop.ch/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module-&gt;handle_ajax_request(&#039;&#039;)
#4 /home/clients/fa4546171ffa04b2c5acd403d7e08b4e/sites/classphoneshop.ch/wp-includes/class-wp-hook.php(332): WP_Hook-&gt;apply_filters(&#039;&#039;, Array)
#5 /home/clients/fa4546171ffa04b2c5acd403d7e08b4e/sites/classphoneshop.ch/wp-includes/plugin.php(517): WP_Hook-&gt;do_action(Array)
#6 /home/clients/fa4546171ffa04b2c5acd403d7e08b4e/sites/classphoneshop.ch/wp-admin/admin-ajax.php(188): do_action(&#039;wp_ajax_element...&#039;)
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-09 19:02:27 [warning X 1][/home/clients/fa4546171ffa04b2c5acd403d7e08b4e/sites/classphoneshop.ch/wp-content/plugins/elementor/includes/managers/image.php::36] Undefined array key &quot;size&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-09 19:02:50 [warning X 2][/home/clients/fa4546171ffa04b2c5acd403d7e08b4e/sites/classphoneshop.ch/wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 10 of 10JS: 2023-03-24 13:18:50 [error X 2][https://classphoneshop.ch/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.13.0-dev2:3:618331] Cannot read properties of undefined (reading &#039;models&#039;) 
JS: 2023-03-26 15:50:34 [error X 2][https://classphoneshop.ch/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.13.0-dev2:3:618338] Cannot read properties of undefined (reading &#039;0&#039;) 
JS: 2023-03-28 08:28:32 [error X 1][https://classphoneshop.ch/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view10972&quot;) has already been destroyed and cannot be used. 
JS: 2023-03-28 15:56:49 [error X 1][https://classphoneshop.ch/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view13271&quot;) has already been destroyed and cannot be used. 
JS: 2023-04-09 15:06:51 [error X 1][https://classphoneshop.ch/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view32333&quot;) has already been destroyed and cannot be used. 
JS: 2023-04-09 15:24:08 [error X 1][https://classphoneshop.ch/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view10815&quot;) has already been destroyed and cannot be used. 
JS: 2023-04-09 20:17:46 [error X 1][https://classphoneshop.ch/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.13.0-dev2:3:790484] Cannot read properties of undefined (reading &#039;toLowerCase&#039;) 
JS: 2023-04-10 16:58:02 [error X 10][https://classphoneshop.ch/wp-content/plugins/elementor/assets/js/packages/documents.min.js?ver=3.13.0-dev2:1:718] Cannot read properties of null (reading &#039;config&#039;) 
JS: 2023-04-10 16:59:17 [error X 1][https://classphoneshop.ch/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.13.0-dev2:3:564986] Cannot read properties of undefined (reading &#039;preview&#039;) 
JS: 2023-04-23 19:04:02 [error X 1][https://classphoneshop.ch/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.13.0-dev2:3:595047] Cannot read properties of null (reading &#039;id&#039;) 

Log: showing 20 of 262023-04-02 17:43:36 [info] elementor-pro::elementor_pro_updater Started 
2023-04-02 17:43:36 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-04-02 17:43:36 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-04-02 17:43:36 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.0',
  'to' => '3.12.1',
)]
2023-04-10 14:46:20 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.1',
  'to' => '3.12.2',
)]
2023-04-10 14:46:21 [info] elementor-pro::elementor_pro_updater Started 
2023-04-10 14:46:21 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-04-10 14:46:21 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-04-10 14:46:21 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.1',
  'to' => '3.12.2',
)]
2023-04-23 13:27:10 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.2',
  'to' => '3.12.3',
)]
2023-04-23 13:27:11 [info] elementor-pro::elementor_pro_updater Started 
2023-04-23 13:27:11 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-04-23 13:27:11 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-04-23 13:27:11 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.2',
  'to' => '3.12.3',
)]
2023-04-24 20:12:21 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.0-dev2',
  'to' => '3.13.0-dev3',
)]
2023-04-24 20:12:22 [info] elementor::elementor_updater Started 
2023-04-24 20:12:22 [info] Elementor/Upgrades - _on_each_version Start  
2023-04-24 20:12:22 [info] Elementor/Upgrades - _on_each_version Finished 
2023-04-24 20:12:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.0-dev2',
  'to' => '3.13.0-dev3',
)]
2023-04-24 20:12:24 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.0-dev2',
  'to' => '3.13.0-dev3',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Non compatible

== Elementor Pro - Compatibility Tag ==
	


````

</details>

**Comment by nicholaszein** [comment]
Hello @classphoneshop,

Thank you for reaching out! 🙏 

### ⛔ 🧩 Please note that while we do welcome bug reports, we can't provide support for 3rd-party themes/plugins/add-ons/extensions.

It seems that your theme (Woodmart) is conflicting with the version of Elementor you're using.

If your issue is specifically happening only when you're using a feature from a 3rd-party software, or only when the 3rd-party software is active, you'll need to contact the support for that specific software or its developers.

You need first to deactivate and uninstall the Elementor Beta (Developer Edition) plugin, as this plugin is not meant to be used on production websites, and should only be used by plugin developers to test their plugins with Elementor.

Then [rollback](https://elementor.com/help/rolling-back-to-a-previous-version-of-elementor/) Elementor to the latest stable version.

Finally, contact the Woodmart theme support and report the error to them, as they should be the ones fixing the incompatibility caused by their theme.

### 👍 For now that's all we can help with.

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Regards
