### ISSUE TITLE
⛔ 🐞 Bug Report: Margin being added INSIDE the element when using Flexbox

### ISSUE THREAD

**Issue by simonclay** [elementor/elementor#22205]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

If you add an element to the page, give the element a boarder and then add margin you expect the margin to be added outside the boarder of the element. 

However, when Flexbox is activated, margin is added inside the element, therefore pushing the border away from the item within.

Demonstration here:
https://www.loom.com/share/8fcfa1fc53844a29a0b69212b0a67214

### Steps to reproduce

1) Activate Flexbox feature.

2) Add an element to the page, eg Heading, Text, Button.

3) In the Advanced tab add a border

4) In the Advanced tab add margin and see that it is added INSIDE the border, not OUTSIDE as expected.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.3.36
	PHP Version: 8.1.17
	PHP Memory Limit: 768M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2
	Site URL: https://thinktwice.developmentandtesting.co.uk
	Home URL: https://thinktwice.developmentandtesting.co.uk
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 40M
	Max Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: en-GB
	Timezone: Europe/London
	Admin Email: simon@sly-design.co.uk
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.7.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36

== Active Plugins ==
	All-in-One WP Migration
		Version: 7.73
		Author: ServMask

	All-in-One WP Migration Unlimited Extension
		Version: 2.49
		Author: ServMask

	Elementor
		Version: 3.12.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.12.3
		Author: Elementor.com

	Wordfence Security
		Version: 7.9.2
		Author: Wordfence


== Elements Usage ==
	
	page : 1
		heading : 1
		image : 1
	wp-page : 2
		container : 2
		heading : 2
		text-editor : 2


== Settings ==
	
	cpt_support: post, page
	disable_color_schemes: yes
	disable_typography_schemes: yes
	allow_tracking: yes


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Optimised DOM Output: Active by default
	Improved asset loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility improvements: Active by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Editor Top Bar: Inactive by default
	Landing pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Menu: Inactive by default


== Log ==
	
Log: showing 20 of 412023-03-15 19:51:50 [info] elementor-pro::elementor_pro_updater Started 
2023-03-15 19:51:50 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-03-15 19:51:50 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-03-15 19:51:50 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.5',
  'to' => '3.11.6',
)]
2023-03-15 19:51:50 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.5',
  'to' => '3.11.6',
)]
2023-03-15 19:51:51 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.5',
  'to' => '3.11.6',
)]
2023-04-26 11:55:25 [info] elementor::elementor_updater Started 
2023-04-26 11:55:25 [info] Elementor/Upgrades - _on_each_version Start  
2023-04-26 11:55:25 [info] Elementor/Upgrades - _on_each_version Finished 
2023-04-26 11:55:25 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.0',
  'to' => '3.12.2',
)]
2023-04-26 11:55:30 [info] elementor-pro::elementor_pro_updater Started 
2023-04-26 11:55:30 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-04-26 11:55:30 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-04-26 11:55:30 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.6',
  'to' => '3.12.2',
)]
2023-04-26 11:59:44 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.2',
  'to' => '3.12.3',
)]
2023-04-26 11:59:44 [info] elementor-pro::elementor_pro_updater Started 
2023-04-26 11:59:44 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-04-26 11:59:44 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-04-26 11:59:44 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.2',
  'to' => '3.12.3',
)]
2023-04-26 11:59:46 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.2',
  'to' => '3.12.3',
)]

PHP: showing 2 of 2PHP: 2023-03-07 18:53:56 [notice X 273][/home/slydesig/thinktwice.developmentandtesting.co.uk/wp-content/plugins/elementor-pro/modules/loop-builder/module.php::200] strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-29 17:08:13 [error X 2][/home/slydesig/thinktwice.developmentandtesting.co.uk/wp-content/plugins/elementor/core/wp-api.php::26] Uncaught Error: Call to undefined function Elementor\Core\get_plugins() in /home/slydesig/thinktwice.developmentandtesting.co.uk/wp-content/plugins/elementor/core/wp-api.php:26
Stack trace:
#0 /home/slydesig/thinktwice.developmentandtesting.co.uk/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(96): Elementor\Core\Wp_Api->get_plugins()
#1 /home/slydesig/thinktwice.developmentandtesting.co.uk/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(58): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_with_header()
#2 /home/slydesig/thinktwice.developmentandtesting.co.uk/wp-content/plugins/elementor/modules/compatibility-tag/module.php(57): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_to_check()
#3 /home/slydesig/thinktwice.developmentandtesting.co.uk/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(148): Elementor\Modules\CompatibilityTag\Module->get_plugins_to_check()
#4 /home/slydesig/thinktwice.developmentandtesting.co.uk/wp-includes/class-wp-hook.php(308): Elementor\Modules\CompatibilityTag\Base_Module->Elementor\Modules\CompatibilityTag\{closure}()
#5 /home/slydesig/thinktwice.developmentandtesting.co.uk/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#6 /home/slydesig/thinktwice.developmentandtesting.co.uk/wp-includes/plugin.php(517): WP_Hook->do_action()
#7 /home/slydesig/thinktwice.developmentandtesting.co.uk/wp-content/plugins/elementor/modules/system-info/module.php(334): do_action()
#8 /home/slydesig/thinktwice.developmentandtesting.co.uk/wp-content/plugins/elementor/includes/tracker.php(241): Elementor\Modules\System_Info\Module::get_allowed_reports()
#9 /home/slydesig/thinktwice.developmentandtesting.co.uk/wp-content/plugins/elementor/includes/tracker.php(530): Elementor\Tracker::get_system_reports_data()
#10 /home/slydesig/thinktwice.developmentandtesting.co.uk/wp-content/plugins/elementor/includes/tracker.php(141): Elementor\Tracker::get_tracking_data()
#11 /home/slydesig/thinktwice.developmentandtesting.co.uk/wp-includes/class-wp-hook.php(308): Elementor\Tracker::send_tracking_data()
#12 /home/slydesig/thinktwice.developmentandtesting.co.uk/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#13 /home/slydesig/thinktwice.developmentandtesting.co.uk/wp-includes/plugin.php(565): WP_Hook->do_action()
#14 /home/slydesig/thinktwice.developmentandtesting.co.uk/wp-cron.php(188): do_action_ref_array()
#15 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Incompatible

== Elementor Pro - Compatibility Tag ==
	

				
````

</details>

**Comment by Daveden2** [comment]
Exactly 💯 

This makes using custom units like Margin-left: auto, on the widget not possible without writing custom CSS

**Comment by nicholaszein** [comment]
Hello @simonclay,

Thank you for reaching out, and for taking the time to explain the issue in detail! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
Currently, all widgets with the exception of the Container will have margins and paddings added to the `.elementor-widget-container` wrapper. This is why you see the margin inside the element. What you are trying to do is still not supported. We are aware of this issue, but it is not a bug. This was always meant to be this way, and it is still there for backward compatibility.

We have plans to change this in the future, but we don't have an ETA yet as to when this will happen.

### ✅ What you can do to solve your issue:
For now, if you really need to add margins to elements, please use the Custom CSS option.

Please understand that changing this behavior affects all websites using Elementor, and we will need to be very careful to avoid breaking existing websites. This is a big change and it won't happen before we finish restructuring our framework. We ask for your patience and consideration.

Kind regards
