### ISSUE TITLE
⛔ 🧩 🐞 Elementor Popups causing duplicate content with the Draw Attention plugin

### ISSUE THREAD

**Issue by gnarza** [elementor/elementor#22266]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Elementor Popups causing duplicate content with the Draw Attention plugin

The Draw Attention image map content is duplicated after an Elementor popup occurs on the page. If the user resizes their browsing window or turns their mobile device, duplicate content is shown and makes the content difficult to navigate.

Loom explanation: https://www.loom.com/share/b3ab06dd623942278be98e19c7c4c125

Test site:  https://elementor-bug-popup-testing.sandbox.ssa.rocks

### Added technical details
The Draw Attention divs that hold the interactive image components are duplicated after the popup occurs. 

Specifically .hotspots-map-container

![Screenshot 2023-05-01 at 12 59 07 PM](https://user-images.githubusercontent.com/24639396/235502102-c39f8663-e786-47d5-856a-ec67ae1e236e.png)

### Other notes

- This happens with both the free and paid versions of Draw Attention
- Pages with Draw Attention that don't include the elementor popups work as expected
- We've had this happen on various websites

### Steps to reproduce

1. Install and activate the free Draw Attention (DA) plugin https://wordpress.org/plugins/draw-attention/
2. Create a simple image map with DA: https://youtu.be/74yvCnYQDPE
3. Place the DA image map on a page
4. Install Elementor Pro
5. Create a new popup template in Elementor
6. Set up the popup to trigger over the DA image page
7. Set the triggers to page load, 1s
11. View the DA image page in either responsive desktop mode or view on your phone
12. Close the new elementor popup on the page
13. Change the orientation of the page (ex. flip phone sideways)

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt

					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.20.2
	MySQL version: mariadb.org binary distribution v10.6.7
	PHP Version: 8.0.17
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 40M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2
	Site URL: https://elementor-bug-popup-testing.sandbox.ssa.rocks
	Home URL: https://elementor-bug-popup-testing.sandbox.ssa.rocks
	WP Multisite: No
	Max Upload Size: 40 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: ssatest@ssahq.com
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Twenty-Two
	Version: 1.4
	Author: the WordPress team
	Child Theme: No
<br />
<b>Warning</b>:  Undefined array key 0 in <b>/home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor/modules/system-info/reporters/user.php</b> on line <b>75</b><br />

== User ==
	Role: 
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15

== Active Plugins ==
	CLI Backup
		Version: 1.2.18
		Author: NSquared

	Draw Attention
		Version: 2.0.9
		Author: N Squared

	Elementor
		Version: 3.12.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.12.3
		Author: Elementor.com

	Members
		Version: 3.2.5
		Author: MemberPress

	PHP Stack Trace: Enable detailed debug logging
		Version: 1.0.0
		Author: Simply Schedule Appointments

	Plugin Detective - Troubleshooting
		Version: 1.2.12
		Author: NSquared

	Temporary Login Without Password
		Version: 1.8.1.1
		Author: StoreApps


== Elements Usage ==
	
	popup : 1
		form : 1
		heading : 2
		icon : 1
		spacer : 1


== Settings ==
	
	allow_tracking: yes
	font_display: swap


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Upgrade Swiper Library: Inactive by default
	Default to New Theme Builder: Active by default
	Editor Top Bar: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Menu: Inactive by default


== Log ==
	
PHP: showing 6 of 6PHP: 2023-05-01 16:19:45 [error X 1][/home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php::48] Uncaught ReflectionException: Method ElementorPro\Modules\ThemeBuilder\Documents\Section::get_site_editor_type() does not exist in /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php:48
Stack trace:
#0 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(48): ReflectionClass->getMethod()
#1 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(129): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document::get_site_editor_type_bc()
#2 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor/core/common/modules/finder/categories/create.php(94): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document::get_create_url()
#3 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor/core/common/modules/finder/categories/create.php(67): Elementor\Core\Common\Modules\Finder\Categories\Create->create_item_url_by_document_class()
#4 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor/core/common/modules/finder/base-category.php(92): Elementor\Core\Common\Modules\Finder\Categories\Create->get_category_items()
#5 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor/core/base/base-object.php(142): Elementor\Core\Common\Modules\Finder\Base_Category->get_init_settings()
#6 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor/core/base/base-object.php(40): Elementor\Core\Base\Base_Object->ensure_settings()
#7 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor/core/common/modules/finder/module.php(107): Elementor\Core\Base\Base_Object->get_settings()
#8 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor/core/base/base-object.php(142): Elementor\Core\Common\Modules\Finder\Module->get_init_settings()
#9 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor/core/base/base-object.php(40): Elementor\Core\Base\Base_Object->ensure_settings()
#10 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor/core/base/app.php(59): Elementor\Core\Base\Base_Object->get_settings()
#11 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor/core/base/app.php(36): Elementor\Core\Base\App->get_components_config()
#12 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor/core/common/app.php(155): Elementor\Core\Base\App->print_config()
#13 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor/app/app.php(144): Elementor\Core\Common\App->register_scripts()
#14 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor/app/app.php(74): Elementor\App\App->enqueue_assets()
#15 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-includes/class-wp-hook.php(308): Elementor\App\App->admin_init()
#16 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#17 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-includes/plugin.php(517): WP_Hook->do_action()
#18 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-admin/admin.php(175): do_action()
#19 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-01 16:19:52 [error X 1][/home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php::48] Uncaught ReflectionException: Method ElementorPro\Modules\ThemeBuilder\Documents\Section::get_site_editor_type() does not exist in /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php:48
Stack trace:
#0 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(48): ReflectionClass->getMethod()
#1 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(129): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document::get_site_editor_type_bc()
#2 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor/core/common/modules/finder/categories/create.php(94): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document::get_create_url()
#3 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor/core/common/modules/finder/categories/create.php(67): Elementor\Core\Common\Modules\Finder\Categories\Create->create_item_url_by_document_class()
#4 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor/core/common/modules/finder/base-category.php(92): Elementor\Core\Common\Modules\Finder\Categories\Create->get_category_items()
#5 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor/core/base/base-object.php(142): Elementor\Core\Common\Modules\Finder\Base_Category->get_init_settings()
#6 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor/core/base/base-object.php(40): Elementor\Core\Base\Base_Object->ensure_settings()
#7 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor/core/common/modules/finder/module.php(107): Elementor\Core\Base\Base_Object->get_settings()
#8 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor/core/base/base-object.php(142): Elementor\Core\Common\Modules\Finder\Module->get_init_settings()
#9 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor/core/base/base-object.php(40): Elementor\Core\Base\Base_Object->ensure_settings()
#10 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor/core/base/app.php(59): Elementor\Core\Base\Base_Object->get_settings()
#11 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor/core/base/app.php(36): Elementor\Core\Base\App->get_components_config()
#12 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor/core/common/app.php(155): Elementor\Core\Base\App->print_config()
#13 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\App->register_scripts()
#14 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#15 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-includes/plugin.php(517): WP_Hook->do_action()
#16 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-admin/admin-header.php(118): do_action()
#17 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-admin/update.php(132): require_once('...')
#18 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-01 16:21:03 [error X 9][/home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php::48] Uncaught ReflectionException: Method ElementorPro\Modules\ThemeBuilder\Documents\Section::get_site_editor_type() does not exist in /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php:48
Stack trace:
#0 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(48): ReflectionClass->getMethod()
#1 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(129): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document::get_site_editor_type_bc()
#2 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor/core/common/modules/finder/categories/create.php(94): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document::get_create_url()
#3 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor/core/common/modules/finder/categories/create.php(67): Elementor\Core\Common\Modules\Finder\Categories\Create->create_item_url_by_document_class()
#4 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor/core/common/modules/finder/base-category.php(92): Elementor\Core\Common\Modules\Finder\Categories\Create->get_category_items()
#5 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor/core/base/base-object.php(142): Elementor\Core\Common\Modules\Finder\Base_Category->get_init_settings()
#6 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor/core/base/base-object.php(40): Elementor\Core\Base\Base_Object->ensure_settings()
#7 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor/core/common/modules/finder/module.php(107): Elementor\Core\Base\Base_Object->get_settings()
#8 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor/core/base/base-object.php(142): Elementor\Core\Common\Modules\Finder\Module->get_init_settings()
#9 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor/core/base/base-object.php(40): Elementor\Core\Base\Base_Object->ensure_settings()
#10 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor/core/base/app.php(59): Elementor\Core\Base\Base_Object->get_settings()
#11 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor/core/base/app.php(36): Elementor\Core\Base\App->get_components_config()
#12 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor/core/common/app.php(155): Elementor\Core\Base\App->print_config()
#13 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\App->register_scripts()
#14 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#15 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-includes/plugin.php(517): WP_Hook->do_action()
#16 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-includes/script-loader.php(2194): do_action()
#17 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-includes/class-wp-hook.php(308): wp_enqueue_scripts()
#18 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#19 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-includes/plugin.php(517): WP_Hook->do_action()
#20 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-includes/general-template.php(3049): do_action()
#21 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-includes/template-canvas.php(17): wp_head()
#22 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-includes/template-loader.php(106): include('...')
#23 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-blog-header.php(19): require_once('...')
#24 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/index.php(17): require('...')
#25 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-01 16:21:46 [error X 6][/home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php::48] Uncaught ReflectionException: Method ElementorPro\Modules\ThemeBuilder\Documents\Section::get_site_editor_type() does not exist in /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php:48
Stack trace:
#0 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(48): ReflectionClass->getMethod()
#1 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(129): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document::get_site_editor_type_bc()
#2 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor/core/common/modules/finder/categories/create.php(94): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document::get_create_url()
#3 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor/core/common/modules/finder/categories/create.php(67): Elementor\Core\Common\Modules\Finder\Categories\Create->create_item_url_by_document_class()
#4 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor/core/common/modules/finder/base-category.php(92): Elementor\Core\Common\Modules\Finder\Categories\Create->get_category_items()
#5 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor/core/base/base-object.php(142): Elementor\Core\Common\Modules\Finder\Base_Category->get_init_settings()
#6 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor/core/base/base-object.php(40): Elementor\Core\Base\Base_Object->ensure_settings()
#7 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor/core/common/modules/finder/module.php(107): Elementor\Core\Base\Base_Object->get_settings()
#8 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor/core/base/base-object.php(142): Elementor\Core\Common\Modules\Finder\Module->get_init_settings()
#9 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor/core/base/base-object.php(40): Elementor\Core\Base\Base_Object->ensure_settings()
#10 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor/core/base/app.php(59): Elementor\Core\Base\Base_Object->get_settings()
#11 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor/core/base/app.php(36): Elementor\Core\Base\App->get_components_config()
#12 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor/core/common/app.php(155): Elementor\Core\Base\App->print_config()
#13 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\App->register_scripts()
#14 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#15 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-includes/plugin.php(517): WP_Hook->do_action()
#16 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-admin/admin-header.php(118): do_action()
#17 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-admin/index.php(137): require_once('...')
#18 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-01 16:23:24 [error X 2][/home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php::48] Uncaught ReflectionException: Method ElementorPro\Modules\ThemeBuilder\Documents\Section::get_site_editor_type() does not exist in /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php:48
Stack trace:
#0 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(48): ReflectionClass->getMethod()
#1 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(129): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document::get_site_editor_type_bc()
#2 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor/core/common/modules/finder/categories/create.php(94): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document::get_create_url()
#3 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor/core/common/modules/finder/categories/create.php(67): Elementor\Core\Common\Modules\Finder\Categories\Create->create_item_url_by_document_class()
#4 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor/core/common/modules/finder/base-category.php(92): Elementor\Core\Common\Modules\Finder\Categories\Create->get_category_items()
#5 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor/core/base/base-object.php(142): Elementor\Core\Common\Modules\Finder\Base_Category->get_init_settings()
#6 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor/core/base/base-object.php(40): Elementor\Core\Base\Base_Object->ensure_settings()
#7 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor/core/common/modules/finder/module.php(107): Elementor\Core\Base\Base_Object->get_settings()
#8 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor/core/base/base-object.php(142): Elementor\Core\Common\Modules\Finder\Module->get_init_settings()
#9 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor/core/base/base-object.php(40): Elementor\Core\Base\Base_Object->ensure_settings()
#10 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor/core/base/app.php(59): Elementor\Core\Base\Base_Object->get_settings()
#11 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor/core/base/app.php(36): Elementor\Core\Base\App->get_components_config()
#12 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor/core/common/app.php(155): Elementor\Core\Base\App->print_config()
#13 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\App->register_scripts()
#14 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#15 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-includes/plugin.php(517): WP_Hook->do_action()
#16 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-admin/admin-header.php(118): do_action()
#17 /home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-admin/plugins.php(605): require_once('...')
#18 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-01 17:02:14 [warning X 1][/home/forge/elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor/modules/system-info/reporters/user.php::75] Undefined array key 0 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 9 of 92023-05-01 17:01:36 [info] elementor-pro::elementor_pro_updater Started 
2023-05-01 17:01:36 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-05-01 17:01:36 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-05-01 17:01:36 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Start  
2023-05-01 17:01:36 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Finished 
2023-05-01 17:01:36 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Start  
2023-05-01 17:01:36 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Finished 
2023-05-01 17:01:36 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.4.1',
  'to' => '3.12.3',
)]
2023-05-01 17:01:36 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.4.1',
  'to' => '3.12.3',
)]

JS: showing 1 of 1JS: 2023-05-01 17:05:09 [error X 2][https://elementor-bug-popup-testing.sandbox.ssa.rocks/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.12.2:2:19881] undefined is not an object (evaluating 'e.offset().top') 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Incompatible

== Elementor Pro - Compatibility Tag ==
	

				

````

</details>

**Comment by nicholaszein** [comment]
Hello @gnarza,

Thank you for reaching out! 🙏 

### ⛔ 🧩 Please note that while we do welcome bug reports, we can't provide support for 3rd-party themes/plugins/add-ons/extensions.

If your issue is specifically happening only when you're using a feature from a 3rd-party software, or only when the 3rd-party software is active, you'll need to contact the support for that specific software or its developers.

Regards
