### ISSUE TITLE
[⌛ Awaiting Feedback] 🐞 Bug Report: Using the add to cart widget in a popup template for variable products does not work

### ISSUE THREAD

**Issue by HuthDev** [elementor/elementor#22297]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Using a shortcode or add to cart widget in a popup template breaks functionality of the add to cart for variable products.

### Steps to reproduce

- Blank theme
- Install elementor
- Install woocommerce
- Create popup
- Add an add to cart widget in the popup for a variable product
- Try to add to cart all the variations using the add to cart widget in the popup
- Only one variation will ever add (the first in the pick list)

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.21.5
	MySQL version: mariadb.org binary distribution v10.5.19
	PHP Version: 8.1.18
	PHP Memory Limit: 256M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 2048M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Scentina
	Version: 1.0.1
	Author: Themes Kingdom
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.13.0-dev3
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.13.0-beta2
		Author: Elementor.com

	Google Tag Manager for WooCommerce PRO
		Version: 1.10.0
		Author: Handcraft Byte

	Jetpack
		Version: 12.1
		Author: Automattic

	Redirection
		Version: 5.3.10
		Author: John Godley

	UPS Live Rates and Access Points
		Version: 1.23.5
		Author: Octolize

	WooCommerce
		Version: 7.6.1
		Author: Automattic

	Woocommerce Add to cart Ajax for variable products
		Version: 2.2
		Author: Rishi Mehta - Rcreators Websolutions

	WooCommerce Payments
		Version: 5.8.0
		Author: Automattic

	WooCommerce Shipping & Tax
		Version: 2.2.4
		Author: WooCommerce

	WooCommerce Stripe Gateway
		Version: 7.3.0
		Author: WooCommerce

	WPCode Lite
		Version: 2.0.10
		Author: WPCode

	Yoast SEO
		Version: 20.6
		Author: Team Yoast


== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

	Kinsta Must-use Plugins
		Version: 3.0.0
		Author: Kinsta Team


== Elements Usage ==
	
	footer : 1
		button : 1
		container : 12
		heading : 7
		html : 1
		icon : 1
		social-icons : 1
		text-editor : 1
	header : 1
		button : 1
		container : 7
		heading : 2
		html : 1
		icon : 3
		image : 2
		woocommerce-menu-cart : 1
	page : 27
		container : 189
		heading : 63
		icon-box : 122
		text-editor : 36
	popup : 4
		button : 29
		container : 76
		divider : 1
		heading : 53
		hotspot : 2
		html : 7
		icon : 33
		image : 12
		nested-tabs : 1
		text-editor : 15
		wc-add-to-cart : 3
		woocommerce-cart : 1
	wp-page : 14
		button : 44
		container : 468
		divider : 7
		form : 1
		heading : 237
		html : 9
		icon : 50
		icon-list : 2
		image : 80
		image-box : 7
		menu-anchor : 3
		nested-tabs : 8
		shortcode : 1
		slides : 1
		spacer : 1
		testimonial-carousel : 10
		text-editor : 86
		toggle : 12
		video : 2
		wc-add-to-cart : 3


== Settings ==
	
	cpt_support: post, page, e-landing-page, product
	disable_color_schemes: yes
	disable_typography_schemes: yes
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	
	woocommerce: Active


== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active
	Grid Container: Inactive by default
	Default to New Theme Builder: Active by default
	Editor Top Bar: Active
	Landing Pages: Active by default
	Nested Elements: Active
	Lazy Load Background Images: Active
	Page Transitions: Inactive
	Notes: Inactive
	Loop: Inactive
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Menu: Inactive by default


== Log ==
	
Log: showing 20 of 262023-04-11 23:24:16 [info] elementor-pro::elementor_pro_updater Started 
2023-04-11 23:24:16 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-04-11 23:24:16 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-04-11 23:24:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.1',
  'to' => '3.12.2',
)]
2023-04-11 23:24:16 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.1',
  'to' => '3.12.2',
)]
2023-04-24 15:36:56 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.2',
  'to' => '3.12.3',
)]
2023-04-24 15:36:56 [info] elementor-pro::elementor_pro_updater Started 
2023-04-24 15:36:56 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-04-24 15:36:56 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-04-24 15:36:56 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.2',
  'to' => '3.12.3',
)]
2023-04-24 15:36:57 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.2',
  'to' => '3.12.3',
)]
2023-04-25 14:59:47 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.0-dev2',
  'to' => '3.13.0-dev3',
)]
2023-04-25 14:59:47 [info] elementor::elementor_updater Started 
2023-04-25 14:59:47 [info] Elementor/Upgrades - _on_each_version Start  
2023-04-25 14:59:48 [info] Elementor/Upgrades - _on_each_version Finished 
2023-04-25 14:59:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.0-dev2',
  'to' => '3.13.0-dev3',
)]
2023-05-02 19:26:52 [info] elementor-pro::elementor_pro_updater Started 
2023-05-02 19:26:52 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-05-02 19:26:52 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-05-02 19:26:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.3',
  'to' => '3.13.0-beta2',
)]

JS: showing 10 of 10JS: 2023-04-04 23:01:19 [error X 5][https://fount.kinsta.cloud/wp-content/plugins/elementor-pro/assets/js/elements-handlers.min.js?ver=3.12.1:2:9161] Cannot read properties of undefined (reading 'size') 
JS: 2023-04-13 19:50:29 [error X 2][https://fount.kinsta.cloud/wp-content/plugins/elementor/assets/js/editor.js?ver=3.13.0-dev2:2454:409] this.model.isValidChild is not a function 
JS: 2023-04-24 20:35:29 [error X 71][https://fount.kinsta.cloud/wp-content/plugins/elementor/assets/js/frontend.js?ver=3.13.0-dev2:48:515] Cannot read properties of undefined (reading 'tools') 
JS: 2023-04-25 01:38:13 [error X 6][https://fount.kinsta.cloud/wp-content/plugins/elementor/assets/js/editor.js?ver=3.13.0-dev2:31147:31] Cannot read properties of undefined (reading 'isDesignable') 
JS: 2023-04-25 21:22:01 [error X 4][https://fount.kinsta.cloud/wp-content/plugins/elementor/assets/js/editor.js?ver=3.13.0-dev3:2862:229] Cannot read properties of undefined (reading 'toLowerCase') 
JS: 2023-04-26 17:42:59 [error X 11][https://fount.kinsta.cloud/wp-content/plugins/elementor-pro/assets/js/editor.js?ver=3.12.3:3831:12] Cannot convert undefined or null to object 
JS: 2023-04-27 01:58:26 [error X 54][https://fount.kinsta.cloud/wp-content/plugins/elementor/assets/js/editor.js?ver=3.13.0-dev3:39394:11] Cannot read properties of undefined (reading 'localized') 
JS: 2023-04-27 14:31:48 [error X 1][https://fount.kinsta.cloud/wp-content/plugins/elementor/assets/js/new-template.js?ver=3.13.0-dev3:6:1438] elementor_new_template_form_controls is not defined 
JS: 2023-05-02 18:16:29 [error X 1][https://fount.kinsta.cloud/wp-content/plugins/elementor/assets/js/editor.js?ver=3.13.0-dev3:33408:21] Cannot read properties of undefined (reading 'attr') 
JS: 2023-05-02 20:12:40 [error X 2][https://fount.kinsta.cloud/wp-content/plugins/elementor/assets/js/editor.js?ver=3.13.0-dev3:14794:29] Cannot read properties of null (reading 'fire') 

PHP: showing 6 of 6PHP: 2023-04-13 22:51:58 [error X 2][/www/fount_447/public/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::295] Uncaught Error: Call to a member function update_meta() on null in /www/fount_447/public/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:295
Stack trace:
#0 /www/fount_447/public/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(168): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(11, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /www/fount_447/public/wp-content/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /www/fount_447/public/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /www/fount_447/public/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#5 /www/fount_447/public/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /www/fount_447/public/wp-admin/admin-ajax.php(188): do_action('wp_ajax_element...')
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-17 21:05:24 [error X 1][/www/fount_447/public/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::295] Uncaught Error: Call to a member function update_meta() on bool in /www/fount_447/public/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:295
Stack trace:
#0 /www/fount_447/public/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(168): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /www/fount_447/public/wp-content/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /www/fount_447/public/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /www/fount_447/public/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#5 /www/fount_447/public/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /www/fount_447/public/wp-admin/admin-ajax.php(188): do_action('wp_ajax_element...')
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-25 00:19:20 [warning X 10][/www/fount_447/public/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-27 15:58:57 [warning X 30][/www/fount_447/public/wp-content/plugins/elementor-pro/modules/woocommerce/widgets/cart.php::2383] Undefined array key "section_coupon_display" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-01 05:38:00 [warning X 1488][/www/fount_447/public/wp-content/plugins/elementor-pro/modules/woocommerce/module.php::381] Undefined array key 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-01 19:46:12 [notice X 44][/www/fount_447/public/wp-content/plugins/elementor-pro/modules/woocommerce/module.php::611] parse_str(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==
	

				
````

</details>

**Comment by nicholaszein** [comment]
Hello @HuthDev,

thank you for reaching out! 🙏 

Can you please elaborate a little on your issue? 
1. Are you trying to use the add-to-cart widget inside a Popup that loads on Product pages, or that loads anywhere? 
2. Which add-to-cart widget are you trying to use? Is it the [Custom Add to Cart (Pro)](https://elementor.com/help/custom-add-to-cart-pro/) widget, or the [WooCommerce Add to Cart](https://elementor.com/help/woocommerce-single-add-to-cart-pro/) widget available in the Single Product template?
3. What shortcode are you trying to use?
4. What are the triggers and Advanced Rules you are applying to your Pop-up?

Please provide a screen recording if possible.

Kind regards

**Comment by HuthDev** [comment]
1. Are you trying to use the add-to-cart widget inside a Popup that loads on Product pages, or that loads anywhere?
**Inside a popup that loads anywhere**
3. Which add-to-cart widget are you trying to use? Is it the [Custom Add to Cart (Pro)](https://elementor.com/help/custom-add-to-cart-pro/) widget, or the [WooCommerce Add to Cart](https://elementor.com/help/woocommerce-single-add-to-cart-pro/) widget available in the Single Product template?
**custom add to cart pro**
5. What shortcode are you trying to use?

**not using a short code in this instance**
7. What are the triggers and Advanced Rules you are applying to your Pop-up?
**opening popup on click, visible on all pages**

**Comment by nicholaszein** [comment]
Hi @HuthDev,

Thank you for the feedback! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
The Custom Add to Cart (Pro) widget, does not support variation selection. You need to define a default variable for the product or choose an individual variable to be the one selected. This is a limitation related to how WooCommerce handles adding variations, which does not work outside WooCommerce pages, or outside the WooCommerce catalog. Please 

### ✅ What you can do to solve your issue:
Add a button for each variation.

### 👍 For now, that's all we can help with. 

If you think this should be an Elementor feature, please submit a new [🚀 Feature Request](https://github.com/orgs/elementor/discussions/new?category=feature-request), we will consider it in the future if there is enough demand (votes) from other users.

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
