### ISSUE TITLE
⛔ 🧩 🐞 Bug Report: Elementor AE unable to select subfield in flexible content template

### ISSUE THREAD

**Issue by wyattsimpson98-code** [elementor/elementor#22322]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When creating a flexible content block in anywhere elementor pro, using ae acf fields widget, we are unable to drill down to sub field. We can select parent field type and parent field but subfield cannot locate the child elements with the flexible content layout. 

### Steps to reproduce

Create AE flexible content block
Use AE acf fields widget
select image (or text it really doesn't matter)
choose layout type as flexible content
select flexible content parent
TRY choose a subfield - it won't be able to find any subfields

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v10.6.11
	PHP Version: 8.1.13
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 80M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2
	Site URL: http://44.224.232.20
	Home URL: http://44.224.232.20
	WP Multisite: No
	Max Upload Size: 80 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: user@example.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.7.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 6.1.5
		Author: WP Engine

	AnyWhere Elementor Pro (Premium)
		Version: 2.25.7
		Author: WP Vibes

	Classic Editor
		Version: 1.6.3
		Author: WordPress Contributors

	Elementor
		Version: 3.13.0-dev3
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.12.3
		Author: Elementor.com

	Modula
		Version: 2.7.4
		Author: WPChill

	Premium Starter Templates
		Version: 3.2.1
		Author: Brainstorm Force

	Ultimate Addons for Elementor
		Version: 1.36.15
		Author: Brainstorm Force

	WPBruiser
		Version: 3.1.43
		Author: Mihai Chelaru

	WP Mail SMTP
		Version: 3.8.0
		Author: WP Mail SMTP

	Yoast Duplicate Post
		Version: 4.5
		Author: Enrico Battocchi & Team Yoast


== Elements Usage ==
	
	container : 4
		container : 7
		divider : 2
		heading : 5
		html : 2
		icon-box : 1
		image : 1
		loop-grid : 1
		shortcode : 1
		text-editor : 1
	wp-post : 0
		ae-acf : 1
		container : 6
		image : 1
		spacer : 1
		text-editor : 1
	wp-page : 6
		blockquote : 2
		button : 2
		container : 94
		divider : 7
		form : 1
		heading : 30
		html : 8
		icon : 2
		icon-box : 15
		image : 11
		loop-carousel : 1
		loop-grid : 7
		shortcode : 3
		social-icons : 2
		text-editor : 18
		uael-image-gallery : 1
	single-post : 1
		ae-acf-flexible-content : 1
		ae-acf-repeater : 1
		container : 13
		divider : 1
		gallery : 1
		heading : 2
		image : 1
		loop-grid : 2
		post-comments : 1
		post-info : 1
		share-buttons : 1
		text-editor : 2
	loop-item : 9
		button : 4
		container : 13
		divider : 1
		gallery : 1
		heading : 8
		image : 3
		spacer : 4
		text-editor : 4


== Settings ==
	
	cpt_support: post, page
	disable_color_schemes: yes
	disable_typography_schemes: yes
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active by default
	Grid Container: Active
	Default to New Theme Builder: Active
	Hello Theme Header & Footer: Active by default
	Editor Top Bar: Active
	Landing Pages: Active by default
	Nested Elements: Active
	Lazy Load Background Images: Active
	Page Transitions: Active
	Notes: Active by default
	Loop: Active
	Form Submissions: Active
	Scroll Snap: Active by default
	Menu: Inactive


== Log ==
	
Log: showing 20 of 252023-04-18 06:01:20 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-04-18 06:01:20 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-04-18 06:01:20 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.10.3',
  'to' => '3.12.2',
)]
2023-04-18 06:01:20 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.10.3',
  'to' => '3.12.2',
)]
2023-04-27 02:01:34 [info] elementor::elementor_updater Started 
2023-04-27 02:01:34 [info] Elementor/Upgrades - _on_each_version Start  
2023-04-27 02:01:34 [info] Elementor/Upgrades - _on_each_version Finished 
2023-04-27 02:01:34 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.0-dev2',
  'to' => '3.13.0-dev3',
)]
2023-04-27 02:01:34 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.0-dev2',
  'to' => '3.13.0-dev3',
)]
2023-04-27 02:01:47 [info] elementor-pro::elementor_pro_updater Started 
2023-04-27 02:01:47 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-04-27 02:01:47 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-04-27 02:01:47 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.2',
  'to' => '3.12.3',
)]
2023-04-27 02:01:47 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.2',
  'to' => '3.12.3',
)]
2023-05-01 07:22:25 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'AnyWhere Elementor Pro',
  'from' => false,
  'to' => '2.25.7',
)]
2023-05-01 07:22:25 [info] ae-pro::aepro_updater Started 
2023-05-01 07:22:25 [info] AnyWhere Elementor Pro/Upgrades - _v_2_21_0 Start  
2023-05-01 07:22:26 [info] AnyWhere Elementor Pro/Upgrades - _v_2_21_0 Finished 
2023-05-01 07:22:26 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'AnyWhere Elementor Pro',
  'from' => '0.1',
  'to' => '2.25.7',
)]
2023-05-01 07:22:28 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'AnyWhere Elementor Pro',
  'from' => '0.1',
  'to' => '2.25.7',
)]

PHP: showing 10 of 10PHP: 2023-04-18 06:01:20 [notice X 8859][/bitnami/wordpress/wp-content/plugins/elementor-pro/modules/loop-builder/module.php::204] strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-19 07:33:32 [warning X 17][/bitnami/wordpress/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-19 07:35:39 [notice X 20][/bitnami/wordpress/wp-content/plugins/elementor-pro/modules/loop-builder/module.php::204] strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /bitnami/wordpress/wp-content/plugins/elementor-pro/modules/loop-builder/module.php(204): class type strpos()
#2: /bitnami/wordpress/wp-content/plugins/elementor-pro/modules/loop-builder/module.php(216): ElementorPro\Modules\LoopBuilder\Module -> is_editing_existing_loop_item()
#3: /bitnami/wordpress/wp-content/plugins/elementor-pro/modules/loop-builder/module.php(60): ElementorPro\Modules\LoopBuilder\Module -> is_loop_theme_builder()
#4: /bitnami/wordpress/wp-content/plugins/elementor-pro/modules/loop-builder/documents/loop.php(406): ElementorPro\Modules\LoopBuilder\Module -> __construct()
',
)]
PHP: 2023-04-19 07:35:39 [notice X 20][/bitnami/wordpress/wp-content/plugins/elementor-pro/modules/loop-builder/module.php::204] strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /bitnami/wordpress/wp-content/plugins/elementor-pro/modules/loop-builder/module.php(204): class type strpos()
#2: /bitnami/wordpress/wp-content/plugins/elementor-pro/modules/loop-builder/module.php(216): ElementorPro\Modules\LoopBuilder\Module -> is_editing_existing_loop_item()
#3: /bitnami/wordpress/wp-content/plugins/elementor-pro/modules/loop-builder/module.php(60): ElementorPro\Modules\LoopBuilder\Module -> is_loop_theme_builder()
#4: /bitnami/wordpress/wp-content/plugins/elementor-pro/modules/loop-builder/documents/loop.php(328): ElementorPro\Modules\LoopBuilder\Module -> __construct()
',
)]
PHP: 2023-04-19 07:35:40 [warning X 8][/bitnami/wordpress/wp-content/plugins/elementor/includes/db.php::267] foreach() argument must be of type array|object, int given [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-20 04:36:31 [warning X 20][/bitnami/wordpress/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-gallery.php::36] Undefined array key 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-20 04:40:29 [warning X 11][/bitnami/wordpress/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::168] Undefined array key "editor_post_id" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-01 07:36:26 [warning X 75][/bitnami/wordpress/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key "condition_type" [array (
  'trace' => '
#0: /bitnami/wordpress/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /bitnami/wordpress/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /bitnami/wordpress/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /bitnami/wordpress/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2023-05-03 08:47:50 [error X 1][/bitnami/wordpress/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::295] Uncaught Error: Call to a member function update_meta() on null in /bitnami/wordpress/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:295
Stack trace:
#0 /bitnami/wordpress/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(168): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions()
#2 /bitnami/wordpress/wp-content/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func()
#3 /opt/bitnami/wordpress/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#4 /opt/bitnami/wordpress/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#5 /opt/bitnami/wordpress/wp-includes/plugin.php(517): WP_Hook->do_action()
#6 /opt/bitnami/wordpress/wp-admin/admin-ajax.php(188): do_action()
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-04 05:34:03 [error X 3][/bitnami/wordpress/wp-content/plugins/elementor/includes/base/widget-base.php::183] Maximum execution time of 30 seconds exceeded [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 7 of 7JS: 2023-04-19 07:38:16 [error X 16][http://44.224.232.20/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.13.0-dev2:3:790991] undefined is not an object (evaluating 'this.store.find((function(T){return T.original===C})).localized') 
JS: 2023-04-20 04:35:31 [error X 3][http://44.224.232.20/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.12.2:2:63837] undefined is not an object (evaluating 'this.getEditorControlView("template_id").createTemplate') 
JS: 2023-04-27 03:30:29 [error X 6][http://44.224.232.20/wp-content/plugins/elementor-pro/assets/js/loop-carousel.ca3af34f494108c4dcd8.bundle.min.js:2:3456] undefined is not an object (evaluating 'this.swiper.params') 
JS: 2023-05-01 07:55:08 [error X 2][http://44.224.232.20/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.13.0-dev3:3:793024] undefined is not an object (evaluating 'T.originalEvent.key.toLowerCase') 
JS: 2023-05-01 09:01:52 [error X 45][http://44.224.232.20/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:17922] null is not an object (evaluating 'this.getColorRepresentation().toLowerCase') 
JS: 2023-05-03 09:11:01 [error X 1][http://44.224.232.20/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.13.0-dev3:3:634705] undefined is not an object (evaluating 'this.view.container.isDesignable') 
JS: 2023-05-04 05:42:50 [error X 2][http://44.224.232.20/wp-content/plugins/elementor/assets/lib/e-select2/js/e-select2.full.min.js?ver=4.0.6-rc.1:1:20459] undefined is not an object (evaluating 'this.placeholder.id') 



== Elementor - Compatibility Tag ==
	
	AnyWhere Elementor Pro (Premium): Incompatible
	Elementor Pro: Incompatible
	Ultimate Addons for Elementor: Incompatible

== Elementor Pro - Compatibility Tag ==
	
	AnyWhere Elementor Pro (Premium): Compatible
	Ultimate Addons for Elementor: Compatible
				
````

</details>

**Comment by nicholaszein** [comment]
Hello @wyattsimpson98-code,

Thank you for reaching out! 🙏 

### ⛔ 🧩 Please note that while we do welcome bug reports, we can't provide support for 3rd-party themes/plugins/add-ons/extensions.

If your issue is specifically happening only when you're using a feature from a 3rd-party software, or only when the 3rd-party software is active, you'll need to contact the support for that specific software or its developers.

Regards
