### ISSUE TITLE
Issue with Flexbox Container not resizing properly between tablet & mobile responsive breakpoints

### ISSUE THREAD

**Issue by zachnicodemous** [elementor/elementor#22334]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

With the new flexbox containers active, there is an issue with resizing between the tablet and mobile responsive breakpoints. Sometimes the last item in a column appears cut off. A video demonstrating the issue on a client website can be viewed here: https://zach-thewebdeveloper.tinytake.com/msc/ODE5NjE5OF8yMTQwNDM3Mg

### Steps to reproduce

1. Enable flexbox containers.
2. Create a complex post page layout in Elementor builder.
3. View the page in your browser.
4. Switch to tablet view in responsive mode & look for the last post in a column.
5. Gradually resize the window down to the mobile breakpoint. The last item in the column will sometimes appear cut off.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.39-42
	PHP Version: 7.4.33
	PHP Memory Limit: 768M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2
	Site URL: https://www.staging8.webtruth.org
	Home URL: https://www.staging8.webtruth.org
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 256M
	Max Memory limit: 768M
	Permalink Structure: /%category%/%postname%/
	Language: en
	Timezone: Europe/London
	Admin Email: mjpenfold@hotmail.co.uk
	Debug Mode: Inactive

== Theme ==
	Name: Web Truth
	Version: 1.0.1
	Author: Zach Nicodemous
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0

== Active Plugins ==
	Classic Editor
		Version: 1.6.3
		Author: WordPress Contributors

	CookieYes | GDPR Cookie Consent
		Version: 3.0.9
		Author: CookieYes

	Ele Custom Skin
		Version: 3.1.7
		Author: Dudaster.com

	Elementor
		Version: 3.12.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.12.3
		Author: Elementor.com

	Favicon by RealFaviconGenerator
		Version: 1.3.27
		Author: Philippe Bernard

	Jetpack
		Version: 12.1
		Author: Automattic

	Limit Login Attempts Reloaded
		Version: 2.25.16
		Author: Limit Login Attempts Reloaded

	WPCode Lite
		Version: 2.0.11
		Author: WPCode

	Yoast SEO
		Version: 20.6
		Author: Team Yoast

== Must-Use Plugins ==
	installatron_hide_status_test.php
		Version: 
		Author: 

== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Active
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active by default
	Default to New Theme Builder: Active by default
	Editor Top Bar: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Active
	Lazy Load Background Images: Active
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Menu: Inactive by default

== Log ==
	
Log: showing 20 of 202023-03-30 20:38:36 [info] elementor::elementor_updater Started 
2023-03-30 20:38:36 [info] Elementor/Upgrades - _on_each_version Start  
2023-03-30 20:38:36 [info] Elementor/Upgrades - _on_each_version Finished 
2023-03-30 20:38:36 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.5',
  'to' => '3.12.0',
)]
2023-03-30 20:38:36 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.5',
  'to' => '3.12.0',
)]
2023-04-03 21:27:34 [info] elementor::elementor_updater Started 
2023-04-03 21:27:34 [info] Elementor/Upgrades - _on_each_version Start  
2023-04-03 21:27:34 [info] Elementor/Upgrades - _on_each_version Finished 
2023-04-03 21:27:34 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.0',
  'to' => '3.12.1',
)]
2023-04-03 21:27:34 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.0',
  'to' => '3.12.1',
)]
2023-05-05 21:29:32 [info] elementor::elementor_updater Started 
2023-05-05 21:29:32 [info] Elementor/Upgrades - _on_each_version Start  
2023-05-05 21:29:32 [info] Elementor/Upgrades - _on_each_version Finished 
2023-05-05 21:29:32 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.1',
  'to' => '3.12.2',
)]
2023-05-05 21:29:32 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.1',
  'to' => '3.12.2',
)]
2023-05-05 21:39:15 [info] elementor-pro::elementor_pro_updater Started 
2023-05-05 21:39:15 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-05-05 21:39:15 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-05-05 21:39:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.7',
  'to' => '3.12.3',
)]
2023-05-05 21:39:15 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.7',
  'to' => '3.12.3',
)]

PHP: showing 3 of 3PHP: 2023-04-04 00:47:44 [notice X 15][/home/customer/www/staging8.webtruth.org/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-04 17:09:13 [notice X 1][/home/customer/www/staging8.webtruth.org/public_html/wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-04 17:09:15 [error X 3][/home/customer/www/staging8.webtruth.org/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::295] Uncaught Error: Call to a member function update_meta() on bool in /home/customer/www/staging8.webtruth.org/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:295
Stack trace:
#0 /home/customer/www/staging8.webtruth.org/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(168): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/customer/www/staging8.webtruth.org/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/customer/www/staging8.webtruth.org/public_html/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/custome [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 2 of 2JS: 2023-04-04 16:09:56 [error X 12][https://www.staging8.webtruth.org/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.12.1:2:30905] elementor.settings.page is undefined 
JS: 2023-04-18 22:06:35 [error X 2][https://www.staging8.webtruth.org/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.12.1:3:785202] T.originalEvent.key is undefined 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello, @zachnicodemous! 

Thank you for submitting your issue! 🙏 

Please allow us some time to investigate it, and get back to you with our findings. 🧐 

Best regards

**Comment by guy01992** [comment]
I had similar problem. I thought I mastered the new container system. Then I went into mobile. I tried to set the column to 50%, 50% for 2 columns on mobile. But 1 column was still going to next line or getting cut off. It's because I had a 2 containers in a container. I needed it like this because it needed a title above the 2 containers. I set the main container to 0px padding, 0px margin. But the 2 inner containers would not sit on the same row. I had to change to 45% and then 45% and then it would. But then would not site center. I gave up and went back to the old system. A css grid may much much better. I cant understand how this is an improvement

**Comment by bassakirou** [comment]
I have the same isssue. It is impossible for me to have two columns containers into one row on mobile.
> I had similar problem. I thought I mastered the new container system. Then I went into mobile. I tried to set the column to 50%, 50% for 2 columns on mobile. But 1 column was still going to next line or getting cut off. It's because I had a 2 containers in a container. I needed it like this because it needed a title above the 2 containers. I set the main container to 0px padding, 0px margin. But the 2 inner containers would not sit on the same row. I had to change to 45% and then 45% and then it would. But then would not sit center. I gave up and went back to the old system. A css grid may much much better. I cant understand how this is an improvement

**Comment by bassakirou** [comment]
One solution is to couple grid container with flex container. Activate both in the settings.

**Comment by bassakirou** [comment]
Finally I solved the problem with responsive on flexbox. You just have to activate the nowrap and remove all the padding on containers.

> ### Prerequisites
> * [x]  I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
> * [x]  The issue still exists against the latest stable version of Elementor.
> 
> ### Description
> With the new flexbox containers active, there is an issue with resizing between the tablet and mobile responsive breakpoints. Sometimes the last item in a column appears cut off. A video demonstrating the issue on a client website can be viewed here: https://zach-thewebdeveloper.tinytake.com/msc/ODE5NjE5OF8yMTQwNDM3Mg
> 
> ### Steps to reproduce
> 1. Enable flexbox containers.
> 2. Create a complex post page layout in Elementor builder.
> 3. View the page in your browser.
> 4. Switch to tablet view in responsive mode & look for the last post in a column.
> 5. Gradually resize the window down to the mobile breakpoint. The last item in the column will sometimes appear cut off.
> 
> ### Isolating the problem
> * [x]  This bug happens with only Elementor plugin active (and Elementor Pro).
> * [x]  This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
> * [x]  I can reproduce this bug consistently following the steps above.
> 
> ### System Info
> System Info
