### ISSUE TITLE
Lottie SVG animations not playing to 100%

### ISSUE THREAD

**Issue by bellamystudio** [elementor/elementor#22330]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I have a page with some lottie animations on - some of them aren't playing through to 100% even though they're set to play from 0 to 100

I have tested these lottie json files on the lottie site and they play perfectly, but in elementor they stop at around 80%

Is there a limit to animation length or complexity?

### Steps to reproduce

Visit this page to see the issue: https://staging2.otherwherecollective.com/lottietest/

All of the nodes that fall should end up along the 'floor' but many stop in mid-air, at around 80% into the animation.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.39-42
	PHP Version: 7.4.33
	PHP Memory Limit: 768M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2
	Site URL: https://staging2.otherwherecollective.com
	Home URL: https://staging2.otherwherecollective.com
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 192M
	Max Memory limit: 768M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: America/New_York
	Admin Email: admin@otherwherecollective.com
	Debug Mode: Inactive

== Theme ==
	Name: Otherwhere Theme
	Version: 1.0.4
	Author: Paul Bellamy
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.7.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/113.0

== Active Plugins ==
	3D Viewer
		Version: 1.3.3
		Author: bPlugins LLC

	Advanced Scripts
		Version: 2.3.5
		Author: Clean Plugins

	Duplicate Page
		Version: 4.5.1
		Author: mndpsingh287

	Easy 3D Viewer
		Version: 1.8.4
		Author: Sergey Burkov

	Elementor
		Version: 3.12.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.12.2
		Author: Elementor.com

	Header Footer Code Manager
		Version: 1.1.32
		Author: 99robots

	Matomo Analytics - Ethical Stats. Powerful Insights.
		Version: 4.14.1
		Author: Matomo

	Otherwhere™
		Version: 2.0.0
		Author: Paul Bellamy

	PDF Invoices & Packing Slips for WooCommerce
		Version: 3.5.2
		Author: WP Overnight

	Presto Player
		Version: 1.13.0
		Author: Presto Made, Inc

	Redirection
		Version: 5.3.10
		Author: John Godley

	SiteGround Optimizer
		Version: 7.3.1
		Author: SiteGround

	SiteGround Security
		Version: 1.4.1
		Author: SiteGround

	Vrm360
		Version: 1.2.1
		Author: Maurice

	WooCommerce
		Version: 7.6.0
		Author: Automattic

	Yoast SEO
		Version: 20.5
		Author: Team Yoast

== Elements Usage ==
	
	footer : 1
		button : 1
		divider : 2
		heading : 32
	header : 1
		heading : 2
		nav-menu : 1
		woocommerce-menu-cart : 1
	page : 3
		heading : 31
		image : 11
		media-carousel : 1
		slides : 1
		tabs : 1
		text-editor : 21
		video : 1
	product : 1
		container : 3
		woocommerce-product-add-to-cart : 1
		woocommerce-product-content : 1
		woocommerce-product-price : 1
		woocommerce-product-title : 1
	section : 2
		heading : 1
		image : 2
	single : 1
		image : 3
		text-editor : 2
		theme-post-title : 1
	wp-post : 0
		button : 38
		divider : 302
		form : 5
		heading : 221
		image : 281
		image-carousel : 13
		media-carousel : 6
		scrolling-marquee : 1
		shortcode : 2
		spacer : 1
		text-editor : 144
		toggle : 7
		type-tester : 5
		variable-type-tester : 17
		video : 8
		wc-add-to-cart : 1
	wp-page : 33
		animated-text : 6
		container : 52
		counter : 2
		divider : 55
		form : 1
		glyph-browser : 4
		heading : 33
		image : 66
		image-box : 2
		lottie : 18
		media-carousel : 2
		pointer-text : 10
		quicktype-showcase : 6
		scrolling-marquee : 6
		singleline-showcase : 2
		table-of-contents : 1
		text-editor : 27
		toggle : 1
		variable-type-tester : 5
		video : 3
		waterfall-text : 5
		wc-add-to-cart : 1
		woocommerce-cart : 1
		woocommerce-checkout-page : 1

== Settings ==
	
	cpt_support: post, page
	allow_tracking: yes
	unfiltered_files_upload: 1

== Features ==
	Custom Fonts: 35
	Custom Icons: 0

== Integrations ==
	
	woocommerce: Active

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Inactive by default
	Editor Top Bar: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Active
	Lazy Load Background Images: Active
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Menu: Inactive by default

== Log ==
	
JS: showing 13 of 13JS: 2023-01-30 17:21:05 [error X 30][https://staging2.otherwherecollective.com/wp-content/plugins/elementor-otherwhere/assets/js/pointer-text.js?ver=6.1.1:22:24] undefined is not an object (evaluating 'axisAname.replace') 
JS: 2023-01-30 17:21:05 [error X 5][https://staging2.otherwherecollective.com/wp-content/plugins/elementor-otherwhere/assets/js/waterfall-text.js?ver=6.1.1:80:13] undefined is not an object (evaluating 'fontSizes.split') 
JS: 2023-01-30 17:34:07 [error X 1][https://staging2.otherwherecollective.com/wp-content/plugins/elementor-otherwhere/assets/js/animated-text.js?ver=6.1.1:57:17] can't access property "querySelector", parent is null 
JS: 2023-01-30 17:34:07 [error X 1][https://staging2.otherwherecollective.com/wp-content/plugins/elementor-otherwhere/assets/js/pointer-text.js?ver=6.1.1:12:22] can't access property "replace", ft.data(...) is undefined 
JS: 2023-01-30 17:34:07 [error X 1][https://staging2.otherwherecollective.com/wp-content/plugins/elementor-otherwhere/assets/js/waterfall-text.js?ver=6.1.1:80:4] can't access property "split", fontSizes is undefined 
JS: 2023-04-14 16:14:40 [error X 89247][https://staging2.otherwherecollective.com/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:16820] Cannot read properties of null (reading 'clone') 
JS: 2023-04-14 16:14:41 [error X 1240][https://staging2.otherwherecollective.com/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:21012] Cannot read properties of null (reading 'changestop') 
JS: 2023-04-18 09:12:06 [error X 2][https://staging2.otherwherecollective.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.12.1:3:785703] can't access property "localized", this.store.find(...) is undefined 
JS: 2023-04-20 18:21:45 [error X 2][https://staging2.otherwherecollective.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.12.1:3:785238] Cannot read properties of undefined (reading 'toLowerCase') 
JS: 2023-04-20 18:25:04 [error X 30][https://staging2.otherwherecollective.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.12.1:3:785745] Cannot read properties of undefined (reading 'localized') 
JS: 2023-04-20 19:17:52 [error X 4][https://staging2.otherwherecollective.com/wp-content/plugins/elementor-pro/assets/lib/sticky/jquery.sticky.min.js?ver=3.12.2:1:1162] Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'. 
JS: 2023-05-03 14:35:45 [error X 188][https://staging2.otherwherecollective.com/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:19643] can't access property "toLowerCase", this.getColorRepresentation() is null 
JS: 2023-05-04 12:16:49 [error X 4][https://staging2.otherwherecollective.com/wp-content/plugins/elementor-pro/assets/js/lottie.147bf20db94f86cc4295.bundle.min.js:2:10886] can't access property "setSpeed", this.lottie is null 

PHP: showing 5 of 5PHP: 2023-01-30 12:35:35 [notice X 364][/home/customer/www/staging2.otherwherecollective.com/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-30 12:40:39 [notice X 15][/home/customer/www/staging2.otherwherecollective.com/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::172] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-14 13:27:23 [notice X 42][/home/customer/www/staging2.otherwherecollective.com/public_html/wp-content/plugins/elementor/core/logger/items/js.php::16] Undefined index: column [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-18 05:10:35 [notice X 118][/home/customer/www/staging2.otherwherecollective.com/public_html/wp-content/plugins/elementor-otherwhere/widgets/variable-type-tester.php::547] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-18 05:39:03 [error X 1][/home/customer/www/staging2.otherwherecollective.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::295] Uncaught Error: Call to a member function update_meta() on bool in /home/customer/www/staging2.otherwherecollective.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:295
Stack trace:
#0 /home/customer/www/staging2.otherwherecollective.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(168): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/customer/www/staging2.otherwherecollective.com/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/customer/www/staging2.otherwherecollective.com/public_html/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 20 of 242023-02-24 06:29:14 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.2',
  'to' => '3.11.2',
)]
2023-02-24 06:30:16 [info] elementor-pro::elementor_pro_updater Started 
2023-02-24 06:30:16 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-02-24 06:30:16 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-02-24 06:30:16 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Start  
2023-02-24 06:30:16 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Finished 
2023-02-24 06:30:16 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Start  
2023-02-24 06:30:16 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Finished 
2023-02-24 06:30:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.3.5',
  'to' => '3.11.2',
)]
2023-02-24 06:30:16 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.3.5',
  'to' => '3.11.2',
)]
2023-04-18 04:15:09 [info] elementor::elementor_updater Started 
2023-04-18 04:15:09 [info] Elementor/Upgrades - _on_each_version Start  
2023-04-18 04:15:09 [info] Elementor/Upgrades - _on_each_version Finished 
2023-04-18 04:15:09 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.2',
  'to' => '3.12.1',
)]
2023-04-18 04:15:09 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.2',
  'to' => '3.12.1',
)]
2023-04-18 04:16:18 [info] elementor-pro::elementor_pro_updater Started 
2023-04-18 04:16:18 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-04-18 04:16:18 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-04-18 04:16:18 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.2',
  'to' => '3.12.2',
)]
2023-04-18 04:16:18 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.2',
  'to' => '3.12.2',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @bellamystudio, 

Thank you for submitting your report! 🙏 

### ❌ While reviewing your report, we noticed it was missing some key pieces of information:

- 🆕 **Stay Up-to-date:** Make sure you are using the most recent and stable versions of [Elementor](https://wordpress.org/plugins/elementor/#developers), [Elementor Pro](https://elementor.com/pro/changelog/), [WordPress](https://wordpress.org/download/releases/), and your theme.

- 🔬 **Isolate the problem:** Deactivate all of your plugins (except Elementor/Pro), and temporarily change your WordPress theme to [Hello theme](https://wordpress.org/themes/hello-elementor/). If this solves the problem, gradually activate your plugins and theme one by one, until you spot the conflicting plugin or theme. We also see errors in the console related to matomo.js. Temporarily remove the Matomo Analytics to rule out possible conflicts, and any other added script.

- 🕵️ **Validate Your Issue:** If the issue can't be recreated consistently or reproduced on other sites, it's likely not an Elementor bug. In that case, your issue is likely caused by a conflict with something else. We tested Lottie animations on our testing server and it works as expected.

- 👣 **Steps to replicate:** Think of it as explaining to someone over the phone how to replicate your issue. They can't see the problem, so explain it in detail in a way that we can try to replicate your issue in our environments. Be thorough.

- 🗑️ **Clear the cache:** Always clear the cache after any update (WordPress, Theme, Plugins, Posts, and Pages). This includes but is not limited to server cache, site cache, CDN cache, and browser cache.

Without them, we simply can't help. 😕 

### 🧐 Please provide the missing information above so we can troubleshoot your issue faster and better.

Best regards,

Nick
