### ISSUE TITLE
Elementor 3.13 : SVG icon size does not change in Mega Menu widget.

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#22372]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

If you use an SVG icon for megamenu items, the size of this icon will not change. But if you use the same icon in the nested tabs widget, its size changes well and there is no problem. Also, if we use the icons of the Elementor library, their size changes without any problem, and in fact, the mega menu widget only has problems with SVG icons.

### Steps to reproduce

Add the Mega menu widget and choose an SVG icon for one of its items. Then try to increase the icon size. It does not change anything.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.38 (Win32) OpenSSL/1.1.1a PHP/7.3.2
	MySQL version: mariadb.org binary distribution v5.6.42-84.2
	PHP Version: 7.3.2
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2
	Site URL: http://localhost:80/elementor
	Home URL: http://localhost:80/elementor
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: Europe/Berlin
	Admin Email: Michaelgimii@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.7.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.13.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.13.0
		Author: Elementor.com

== Features ==
	Custom Fonts: 2
	Custom Icons: 0

== Integrations ==
	

== Elementor Experiments ==
	Optimized DOM Output: Inactive
	Improved Asset Loading: Inactive
	Improved CSS Loading: Inactive
	Inline Font Icons: Inactive
	Accessibility Improvements: Inactive
	Additional Custom Breakpoints: Inactive
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Inactive
	Grid Container: Inactive by default
	Default to New Theme Builder: Inactive
	Hello Theme Header & Footer: Inactive
	Editor Top Bar: Active
	Landing Pages: Inactive
	Nested Elements: Active
	Lazy Load Background Images: Inactive
	Page Transitions: Inactive
	Notes: Inactive
	Loop: Active
	Form Submissions: Active by default
	Scroll Snap: Inactive
	Menu: Active

== Log ==
	
Log: showing 20 of 252023-04-23 12:42:48 [info] elementor::elementor_updater Started 
2023-04-23 12:42:48 [info] Elementor/Upgrades - _on_each_version Start  
2023-04-23 12:42:48 [info] Elementor/Upgrades - _on_each_version Finished 
2023-04-23 12:42:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.1',
  'to' => '3.12.2',
)]
2023-04-23 16:55:55 [info] elementor-pro::elementor_pro_updater Started 
2023-04-23 16:55:55 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-04-23 16:55:55 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-04-23 16:55:55 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.2',
  'to' => '3.12.3',
)]
2023-05-09 02:13:55 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.2',
  'to' => '3.13.0',
)]
2023-05-09 02:13:57 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.3',
  'to' => '3.13.0',
)]
2023-05-09 02:13:58 [info] elementor::elementor_updater Started 
2023-05-09 02:13:58 [info] Elementor/Upgrades - _on_each_version Start  
2023-05-09 02:13:58 [info] Elementor/Upgrades - _on_each_version Finished 
2023-05-09 02:13:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.2',
  'to' => '3.13.0',
)]
2023-05-09 02:13:59 [info] elementor-pro::elementor_pro_updater Started 
2023-05-09 02:13:59 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-05-09 02:13:59 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-05-09 02:13:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.3',
  'to' => '3.13.0',
)]
2023-05-09 02:14:00 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.2',
  'to' => '3.13.0',
)]
2023-05-09 02:14:01 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.3',
  'to' => '3.13.0',
)]

JS: showing 11 of 11JS: 2023-04-12 15:46:39 [error X 2][http://localhost:85/elementor/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.12.1:3:594206] Cannot read properties of null (reading 'id') 
JS: 2023-04-13 09:19:21 [error X 7][http://localhost:85/elementor/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view1351") has already been destroyed and cannot be used. 
JS: 2023-04-14 07:42:58 [error X 4][http://localhost:85/elementor/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view1356") has already been destroyed and cannot be used. 
JS: 2023-04-14 08:57:25 [error X 1][http://localhost:85/elementor/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view4056") has already been destroyed and cannot be used. 
JS: 2023-04-14 09:26:20 [error X 1][http://localhost:85/elementor/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.12.1:3:410136] Cannot read properties of null (reading 'history') 
JS: 2023-04-14 09:27:18 [error X 2][http://localhost:85/elementor/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.12.1:3:1081267] Cannot read properties of null (reading 'getBoundingClientRect') 
JS: 2023-04-14 13:45:59 [error X 1][http://localhost:85/elementor/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view2041") has already been destroyed and cannot be used. 
JS: 2023-04-14 18:33:15 [error X 1][http://localhost:85/elementor/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view14527") has already been destroyed and cannot be used. 
JS: 2023-04-15 15:45:29 [error X 1][http://localhost:85/elementor/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view1519") has already been destroyed and cannot be used. 
JS: 2023-04-16 21:21:24 [error X 1][http://localhost:85/elementor/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view7212") has already been destroyed and cannot be used. 
JS: 2023-04-22 10:57:41 [error X 6][http://localhost:85/elementor/wp-content/plugins/elementor/assets/js/df16c9d56464dd4f0800.bundle.min.js:2:7826] Cannot read properties of null (reading 'dataset') 

PHP: showing 6 of 6PHP: 2023-04-12 20:25:15 [error X 1][C:\xampp\htdocs\elementor\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-manager.php::295] Uncaught Error: Call to a member function update_meta() on bool in C:\xampp\htdocs\elementor\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-manager.php:295
Stack trace:
#0 C:\xampp\htdocs\elementor\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-manager.php(168): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 C:\xampp\htdocs\elementor\wp-content\plugins\elementor\core\common\modules\ajax\module.php(175): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 C:\xampp\htdocs\elementor\wp-includes\class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 C:\xampp\htdocs\elementor\wp-includes\class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#5 C:\xampp\htdocs\elemen [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-17 01:49:20 [notice X 8][C:\xampp\htdocs\elementor\wp-content\plugins\elementor\core\common\modules\ajax\module.php::175] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-02 03:35:48 [notice X 65][C:\xampp\htdocs\elementor\wp-content\plugins\elementor-pro\modules\woocommerce\module.php::381] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-05 16:15:36 [notice X 1][C:\xampp\htdocs\elementor\wp-content\plugins\elementor\app\modules\import-export\module.php::695] Trying to get property 'label' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-05 16:15:51 [notice X 2][C:\xampp\htdocs\elementor\wp-content\plugins\elementor-pro\core\app\modules\site-editor\data\endpoints\templates.php::150] Undefined index: condition_type [array (
  'trace' => '
#0: C:\xampp\htdocs\elementor\wp-content\plugins\elementor-pro\core\app\modules\site-editor\data\endpoints\templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: C:\xampp\htdocs\elementor\wp-content\plugins\elementor-pro\core\app\modules\site-editor\data\endpoints\templates.php(120): class type array_map()
#3: C:\xampp\htdocs\elementor\wp-content\plugins\elementor-pro\core\app\modules\site-editor\data\endpoints\templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: C:\xampp\htdocs\elementor\wp-content\plugins\elementor\data\base\endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2023-05-09 16:28:31 [error X 4][C:\xampp\htdocs\elementor\wp-content\plugins\elementor\data\v2\manager.php::8] Maximum execution time of 30 seconds exceeded [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

<details>

**Comment by nicholaszein** [comment]
Hello @Michaelgimii ! 

Thank you for submitting your issue! 🙏 

Please allow us some time to investigate it, and get back to you with our findings. 🧐 

Best regards

**Comment by ziich** [comment]
Does the SVG in question have an anchor tag? If so, it may be related to this issue which has FRUSTRATINGLY still not been fixed since 2020: https://github.com/elementor/elementor/issues/11031.

SVGs with anchor tags are hardcoded to a width of 48px. The current solution is to override this value.

**Comment by milan-ematic** [comment]
@nicholaszein Hi, any updates on this issue? It's been almost 4 years since this was first reported.
