### ISSUE TITLE
⛔ 🐞 Bug Report: Picked hsla color gets displayed as hex in the front end

### ISSUE THREAD

**Issue by mateitudor** [elementor/elementor#22382]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Setting a hsla color in Site Settngs converts it to hex in the frontend. Is this the implementation or is it a bug?

### Steps to reproduce

1) Set a color in hsla
2) See frontend

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt


					
== Server Environment ==
	Operating System: Darwin
	Software: nginx/1.16.0
	MySQL version: MySQL Community Server - GPL v8.0.16
	PHP Version: 8.1.9
	PHP Memory Limit: 256M
	PHP Max Input Vars: 4000
	PHP Max Post Size: 1000M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2
	Site URL: https://washlinks.local
	Home URL: https://washlinks.local
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/Toronto
	Admin Email: mateitudor@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Washlinks
	Version: 0.0.2
	Author: Matei Tudor
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.7.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.4 Safari/605.1.15

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 6.1.6
		Author: WP Engine

	All-in-One WP Migration
		Version: 7.74
		Author: ServMask

	All-in-One WP Migration Unlimited Extension
		Version: 2.50
		Author: ServMask

	Custom Post Type Permalinks
		Version: 3.4.5
		Author: Toro_Unit

	Elementor
		Version: 3.13.0-dev4
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.13.0
		Author: Elementor.com

	FakerPress
		Version: 0.6.1
		Author: Gustavo Bordoni

	LiteSpeed Cache
		Version: 5.4
		Author: LiteSpeed Technologies

	Nested Pages
		Version: 3.2.3
		Author: Kyle Phillips

	Post Type Switcher
		Version: 3.2.1
		Author: Triple J Software, Inc.

	Rank Math SEO
		Version: 1.0.114
		Author: Rank Math

	Rank Math SEO PRO
		Version: 3.0.32.1
		Author: Rank Math


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Active
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active by default
	Grid Container: Active
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Editor Top Bar: Active
	Landing Pages: Active by default
	Nested Elements: Active
	Lazy Load Background Images: Active
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Menu: Active


== Log ==
	
PHP: showing 10 of 10PHP: 2023-05-04 17:59:29 [notice X 1][/Users/mateitudor/Studio/Code/Sites/washlinks/app/public/wp-content/plugins/elementor/core/upgrade/manager.php::63] version_compare(): Passing null to parameter #1 ($version1) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-04 18:01:01 [notice X 3224][/Users/mateitudor/Studio/Code/Sites/washlinks/app/public/wp-content/plugins/elementor-pro/modules/loop-builder/module.php::204] strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-06 19:19:48 [warning X 8][/Users/mateitudor/Studio/Code/Sites/washlinks/app/public/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-06 19:20:17 [warning X 13][/Users/mateitudor/Studio/Code/Sites/washlinks/app/public/wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-06 21:11:47 [warning X 1][/Users/mateitudor/Studio/Code/Sites/washlinks/app/public/wp-content/plugins/elementor/core/files/file-types/svg.php::234] simplexml_load_file(): I/O warning : failed to load external entity "https://washlinks.local/wp-content/uploads/2023/05/washlinks-id-color.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-06 21:20:22 [warning X 1][/Users/mateitudor/Studio/Code/Sites/washlinks/app/public/wp-content/plugins/elementor/core/files/file-types/svg.php::234] simplexml_load_file(): I/O warning : failed to load external entity "https://washlinks.local/wp-content/uploads/2023/05/washlinks-favicon.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-07 10:42:42 [error X 1][/Users/mateitudor/Studio/Code/Sites/washlinks/app/public/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::295] Uncaught Error: Call to a member function update_meta() on null in /Users/mateitudor/Studio/Code/Sites/washlinks/app/public/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:295
Stack trace:
#0 /Users/mateitudor/Studio/Code/Sites/washlinks/app/public/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(168): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(5, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /Users/mateitudor/Studio/Code/Sites/washlinks/app/public/wp-content/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /Users/mateitudor/Studio/Code/Sites/washlinks/app/public/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /Users/mateitudor/Studio/Code/Sites/washlinks/app/public/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#5 /Users/mateitudor/Studio/Code/Sites/washlinks/app/public/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /Users/mateitudor/Studio/Code/Sites/washlinks/app/public/wp-admin/admin-ajax.php(188): do_action('wp_ajax_element...')
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-08 07:29:54 [notice X 6][/Users/mateitudor/Studio/Code/Sites/washlinks/app/public/wp-content/plugins/elementor-pro/modules/loop-builder/module.php::204] strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /Users/mateitudor/Studio/Code/Sites/washlinks/app/public/wp-content/plugins/elementor-pro/modules/loop-builder/module.php(204): class type strpos()
#2: /Users/mateitudor/Studio/Code/Sites/washlinks/app/public/wp-content/plugins/elementor-pro/modules/loop-builder/module.php(216): ElementorPro\Modules\LoopBuilder\Module -> is_editing_existing_loop_item()
#3: /Users/mateitudor/Studio/Code/Sites/washlinks/app/public/wp-content/plugins/elementor-pro/modules/loop-builder/module.php(60): ElementorPro\Modules\LoopBuilder\Module -> is_loop_theme_builder()
#4: /Users/mateitudor/Studio/Code/Sites/washlinks/app/public/wp-content/plugins/elementor-pro/modules/loop-builder/documents/loop.php(406): ElementorPro\Modules\LoopBuilder\Module -> __construct()
',
)]
PHP: 2023-05-08 07:29:54 [notice X 6][/Users/mateitudor/Studio/Code/Sites/washlinks/app/public/wp-content/plugins/elementor-pro/modules/loop-builder/module.php::204] strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /Users/mateitudor/Studio/Code/Sites/washlinks/app/public/wp-content/plugins/elementor-pro/modules/loop-builder/module.php(204): class type strpos()
#2: /Users/mateitudor/Studio/Code/Sites/washlinks/app/public/wp-content/plugins/elementor-pro/modules/loop-builder/module.php(216): ElementorPro\Modules\LoopBuilder\Module -> is_editing_existing_loop_item()
#3: /Users/mateitudor/Studio/Code/Sites/washlinks/app/public/wp-content/plugins/elementor-pro/modules/loop-builder/module.php(60): ElementorPro\Modules\LoopBuilder\Module -> is_loop_theme_builder()
#4: /Users/mateitudor/Studio/Code/Sites/washlinks/app/public/wp-content/plugins/elementor-pro/modules/loop-builder/documents/loop.php(328): ElementorPro\Modules\LoopBuilder\Module -> __construct()
',
)]
PHP: 2023-05-08 11:57:10 [warning X 10][/Users/mateitudor/Studio/Code/Sites/washlinks/app/public/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key "condition_type" [array (
  'trace' => '
#0: /Users/mateitudor/Studio/Code/Sites/washlinks/app/public/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /Users/mateitudor/Studio/Code/Sites/washlinks/app/public/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /Users/mateitudor/Studio/Code/Sites/washlinks/app/public/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /Users/mateitudor/Studio/Code/Sites/washlinks/app/public/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]

Log: showing 10 of 102023-05-06 19:11:22 [info] elementor::elementor_updater Started 
2023-05-06 19:11:22 [info] Elementor/Upgrades - _on_each_version Start  
2023-05-06 19:11:22 [info] Elementor/Upgrades - _on_each_version Finished 
2023-05-06 19:11:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.0-dev3',
  'to' => '3.13.0-dev4',
)]
2023-05-06 19:11:22 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.0-dev3',
  'to' => '3.13.0-dev4',
)]
2023-05-08 14:16:11 [info] elementor-pro::elementor_pro_updater Started 
2023-05-08 14:16:11 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-05-08 14:16:11 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-05-08 14:16:11 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.13.0-beta1',
  'to' => '3.13.0',
)]
2023-05-08 14:16:11 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.13.0-beta1',
  'to' => '3.13.0',
)]

JS: showing 3 of 3JS: 2023-05-08 11:29:55 [error X 1][https://washlinks.local/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.13.0-dev4:3:411982] null is not an object (evaluating 'elementor.documents.getCurrent().history') 
JS: 2023-05-08 11:29:58 [error X 3][https://washlinks.local/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.13.0-dev4:3:1097308] null is not an object (evaluating '$.getBoundingClientRect') 
JS: 2023-05-08 16:13:51 [error X 1][https://washlinks.local/wp-content/plugins/elementor/assets/js/web-cli.min.js?ver=3.13.0-dev4:3:82346] Data commands: `undefined` not found. 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==
	

				
````

</details>

**Comment by nicholaszein** [comment]
Hello @mateitudor! 

Thank you for submitting your issue! 🙏 

### ❌ While reviewing your report, we noticed it was missing some key pieces of information:

- 🆕 **Stay Up-to-date:** Make sure you are using the most recent and stable versions of [Elementor](https://wordpress.org/plugins/elementor/#developers), [Elementor Pro](https://elementor.com/pro/changelog/), [WordPress](https://wordpress.org/download/releases/), and your theme. The current stable version of Elementor Core is 3.13.1, and for Elementor Pro is 3.13.0. Please uninstall the Developer Edition plugin and [rollback](https://elementor.com/help/revert-to-release-from-developer-edition/) to the stable versions.

- 🔬 **Isolate the problem:** Deactivate all of your plugins (except Elementor/Pro), and temporarily change your WordPress theme to [Hello theme](https://wordpress.org/themes/hello-elementor/). If this solves the problem, gradually activate your plugins and theme one by one, until you spot the conflicting plugin or theme.

- 🕵️ **Validate Your Issue:** If the issue can't be recreated consistently or reproduced on other sites, it's likely not an Elementor bug. In that case, your issue is likely caused by a conflict with something else.

- 🗑️ **Clear the cache:** Always clear the cache after any update (WordPress, Theme, Plugins, Posts, and Pages). This includes but is not limited to server cache, site cache, CDN cache, and browser cache.

Without them, we simply can't help. 😕 

### 🧐 Please provide the missing information above so we can troubleshoot your issue faster and better.

Kind regards

**Comment by perks98** [comment]
Hi @nicholaszein I can replicate the issue on the frontend and in the editor, see the video below. I can understand it converts the value to the HEX colour value version but I think when users set a value they don't expect it to change or go back and find another value. To replicate in the editor change away from the style tab to another tab or another widget then back and it would be converted.


https://github.com/elementor/elementor/assets/55829113/c820715e-aefb-486c-8f89-49a4511c3a66

**Comment by nicholaszein** [comment]
Hello @mateitudor, @perks98,

Thank you for your patience! 🙏 

### ⛔ After reviewing your report we concluded this is not a bug caused by Elementor. The feature you're referring to is not yet supported.

If you think this should be an Elementor feature, please submit a new [🚀 Feature Request](https://github.com/orgs/elementor/discussions/new?category=feature-request), and we will consider it in the future if there is enough demand (votes) from other users.

Kind regards
