### ISSUE TITLE
[BUG] Dot infront of the Icon-List

### ISSUE THREAD

**Issue by YavuzPilan** [elementor/elementor#22399]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

After the Last Update there are alot Issues with the Icon-List. 

- There is a diffrent between Edito View and the end View
- The Editor View shows everythink right. When you update it to the Website it changes drastically.
- Dots Appear infront of the The Icons
- The place of the Icon changes

### Steps to reproduce

I just make a Icon list. Filled it up and update the Live side and boom. its there

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: mariadb.org binary distribution v10.5.19
	PHP Version: 7.4.33
	PHP Memory Limit: 128M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 200M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2
	Site URL: https://exello.de
	Home URL: https://exello.de
	WP Multisite: No
	Max Upload Size: 200 MB
	Memory limit: 256M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: de-DE
	Timezone: Europe/Berlin
	Admin Email: uo@exello.de
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36

== Active Plugins ==
	Akismet Anti-Spam
		Version: 5.1
		Author: Automattic

	Antispam Bee
		Version: 2.11.3
		Author: pluginkollektiv

	AutomatorWP
		Version: 2.6.3
		Author: AutomatorWP

	BackUpWordPress
		Version: 3.13
		Author: XIBO Ltd

	Elementor
		Version: 3.13.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.13.0
		Author: Elementor.com

	Hide Admin Bar From Front End
		Version: 3.5.2
		Author: Ankit Panchal

	LearnDash LMS
		Version: 4.5.1.2
		Author: LearnDash

	LearnDash LMS - Course Grid
		Version: 2.0.7
		Author: LearnDash

	LearnDash LMS - Elementor
		Version: 1.0.3
		Author: LearnDash

	LearnDash LMS - Restrict Content Pro
		Version: 1.1.0
		Author: LearnDash

	Loco Translate
		Version: 2.6.4
		Author: Tim Whitlock

	Nav Menu Roles
		Version: 2.1.2
		Author: Kathy Darling

	Post Password Token
		Version: 2.0.2
		Author: shawnparker, gordonbrander

	WP-Polls
		Version: 2.77.0
		Author: Lester 'GaMerZ' Chan

	WP BackItUp Community Edition
		Version: 1.43
		Author: WPBackItUp

	WP Mail SMTP
		Version: 3.8.0
		Author: WP Mail SMTP

	WPO365 | LOGIN
		Version: 21.8
		Author: marco@wpo365.com

== Elemente Verwendung ==
	
	footer : 1
		button : 1
		text-editor : 2
		theme-site-logo : 1
	header : 3
		nav-menu : 2
		theme-site-logo : 2
	page : 1
		spacer : 1
		text-editor : 1
	section : 25
		button : 5
		form : 2
		gallery : 4
		icon-list : 1
		image : 21
		image-gallery : 1
		nav-menu : 1
		text-editor : 30
		theme-site-logo : 1
		toggle : 16
	single : 2
		divider : 2
		shortcode : 3
		text-editor : 2
		theme-post-content : 2
	wp-post : 1
		button : 2
		icon-list : 1
		image : 20
		posts : 1
		text-editor : 45
		video : 1
	wp-page : 14
		button : 22
		form : 2
		gallery : 4
		icon-box : 17
		icon-list : 7
		image : 67
		image-gallery : 2
		login : 1
		nav-menu : 6
		shortcode : 4
		spacer : 2
		text-editor : 153
		theme-site-logo : 9
		toggle : 38
		video : 4
	sfwd-topic : 1
		ld-course-content : 1
		ld-course-infobar : 1
		theme-post-content : 1
		theme-post-title : 1
	sfwd-quiz : 1
		ld-course-infobar : 1
		theme-post-content : 1
		theme-post-title : 1
	sfwd-lessons : 1
		ld-course-content : 1
		ld-course-infobar : 1
		theme-post-content : 1
		theme-post-title : 1
	sfwd-courses : 1
		ld-course-certificate : 1
		ld-course-content : 1
		ld-course-infobar : 1
		theme-post-content : 1
		theme-post-title : 1
	error-404 : 1
		heading : 2
		icon-list : 1

== Einstellungen ==
	
	cpt_support: post, page, e-landing-page, sfwd-courses, sfwd-lessons, sfwd-topic, sfwd-quiz, ld-exam, sfwd-certificates, groups, sfwd-transactions, sfwd-essays, sfwd-assignment
	allow_tracking: yes
	unfiltered_files_upload: 1

== Eigenschaften ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	

== Elementor-Experimente ==
	Optimierte DOM Ausgabe: Standardmäßig aktiviert
	Verbessertes Laden von Assets: Standardmäßig aktiviert
	Verbessertes Laden von CSS: Standardmäßig aktiviert
	Inline-Schriftarten-Symbole: Standardmäßig deaktiviert
	Verbesserungen der Zugänglichkeit: Standardmäßig aktiviert
	Zusätzliche benutzerdefinierte Breakpoints: Standardmäßig aktiviert
	admin_menu_rearrangement: Standardmäßig deaktiviert
	Flexbox Container: Standardmäßig deaktiviert
	Upgrade Swiper Library: Standardmäßig deaktiviert
	Grid Container: Standardmäßig deaktiviert
	Default to New Theme Builder: Standardmäßig aktiviert
	Hello Theme Header & Footer: Standardmäßig aktiviert
	Editor Top Bar: Standardmäßig deaktiviert
	Startseiten: Standardmäßig aktiviert
	Nested Elements: Standardmäßig deaktiviert
	Lazy Load Background Images: Standardmäßig deaktiviert
	Page Transitions: Standardmäßig aktiviert
	Notes: Standardmäßig aktiviert
	Loop: Standardmäßig aktiviert
	Form Submissions: Standardmäßig aktiviert
	Scroll Snap: Standardmäßig aktiviert
	Menü: Standardmäßig deaktiviert

== Protokoll ==
	
Log: showing 20 of 342023-04-02 17:37:19 [info] Elementor/Upgrades - _on_each_version Start  
2023-04-02 17:37:20 [info] Elementor/Upgrades - _on_each_version Finished 
2023-04-02 17:37:20 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.0',
  'to' => '3.12.1',
)]
2023-04-02 17:37:21 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.0',
  'to' => '3.12.1',
)]
2023-04-03 05:40:54 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.0',
  'to' => '3.12.1',
)]
2023-04-03 05:40:56 [info] elementor-pro::elementor_pro_updater Started 
2023-04-03 05:40:56 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-04-03 05:40:56 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-04-03 05:40:56 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.0',
  'to' => '3.12.1',
)]
2023-04-10 17:21:58 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.1',
  'to' => '3.12.2',
)]
2023-04-10 17:21:58 [info] elementor-pro::elementor_pro_updater Started 
2023-04-10 17:21:58 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-04-10 17:21:58 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-04-10 17:21:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.1',
  'to' => '3.12.2',
)]
2023-04-24 05:34:13 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.2',
  'to' => '3.12.3',
)]
2023-04-24 05:34:14 [info] elementor-pro::elementor_pro_updater Started 
2023-04-24 05:34:14 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-04-24 05:34:14 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-04-24 05:34:14 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.2',
  'to' => '3.12.3',
)]
2023-04-24 05:34:14 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.2',
  'to' => '3.12.3',
)]

JS: showing 5 of 5JS: 2023-03-28 08:54:11 [error X 1][https://exello.de/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.11.5:3:656177] elementorFrontend.elements.window.jQuery is not a function 
JS: 2023-03-28 08:54:25 [error X 1][https://exello.de/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.11.5:2:4825] Cannot read properties of undefined (reading &#039;attributes&#039;) 
JS: 2023-03-28 10:46:40 [error X 1][https://exello.de/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:17421] Could not find template: &quot;#tmpl-elementor-templates-modal__header&quot; 
JS: 2023-03-28 10:49:08 [error X 1][https://exello.de/wp-admin/load-scripts.php?c=1&amp;loadchunk_0=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&amp;loadchunk_1=hooks&amp;ver=6.1.1:4:51824] Cannot read properties of undefined (reading &#039;replace&#039;) 
JS: 2023-04-06 09:50:43 [error X 1][https://exello.de/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.12.1:3:561779] Blocked a frame with origin &quot;https://exello.de&quot; from accessing a cross-origin frame. 

PHP: showing 3 of 3PHP: 2023-03-28 10:54:41 [error X 1][/www/htdocs/w00fba8d/Exello_WP/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::295] Uncaught Error: Call to a member function update_meta() on bool in /www/htdocs/w00fba8d/Exello_WP/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:295
Stack trace:
#0 /www/htdocs/w00fba8d/Exello_WP/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(168): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /www/htdocs/w00fba8d/Exello_WP/wp-content/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /www/htdocs/w00fba8d/Exello_WP/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module-&gt;handle_ajax_request(&#039;&#039;)
#4 /www/htdocs/w00fba8d/Exello_WP/wp-includes/class-wp-hook.php(332): WP_Hook-&gt;apply_filters(&#039;&#039;, Array)
 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-03 16:18:16 [notice X 2][/www/htdocs/w00fba8d/Exello_WP/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-04 16:50:31 [notice X 7][/www/htdocs/w00fba8d/Exello_WP/wp-content/plugins/elementor/includes/widgets/video.php::1095] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Die Kompatibilität ist nicht angegeben
	LearnDash LMS - Elementor: Die Kompatibilität ist nicht angegeben

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @YavuzPilan,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
After testing with only the latest versions of Elementor, Elementor Pro, and the Hello Elementor theme, we couldn't reproduce your issue.
It is likely that either custom CSS, another plugin, or some sort of performance optimization solution is causing your issue.

### ✅ What you can do to solve your issue:

#### ⚠️ Make a Backup of your website before proceeding, and if possible do it in a staging environment!

1. Disable/Deactivate all your plugins except **Elementor** (and **Elementor Pro**).
    - If this solves the problem, gradually re-activate plugin-by-plugin (and check if the problem returns) to identify the problematic or conflicting plugin. In this case, contact the 3rd-party plugin support as we don't provide support for 3rd party plugins.
    - If it doesn't solve your problem, try the next step:
2. Clear all cache levels, including but not limited to **Server cache**, **WordPress (optimization plugin) cache**, **CDN cache**, and **Browser cache**. Also, try visiting the front page of your website in **incognito/private** mode.
3. Make sure the server resources allocated to your site and WordPress installation meet our [Requirements](https://elementor.com/help/requirements/). 
    - To check this information go to your WordPress `Dashboard` > `Elementor` > `System info` [learn how to copy it here](https://elementor.com/help/hare-my-system-info/). We can't accept issues without it.

### 👍 For now, that's all we can help with. 

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
