### ISSUE TITLE
✅ 🐞 Bug Report: Using Flip Box in Loop Grid, excerpt pulls in the image.

### ISSUE THREAD

**Issue by hparsons56** [elementor/elementor#22438]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

My posts are created using Gutenberg, and have an image at the beginning of the post, so the text wraps around the post.

I'm trying to create a Flip Box using the Loop Grid. On the front, the Flip Box has the following dynamic items the front: Featured Image, Post Title, and Post Date.  On the Back, the Flip Box has the following dynamic items, (no title), Post Excerpt, and button. The Post Excerpt has the additional settings of length 25, and Apply to post content set to Yes.

When displayed, the back shows the excerpt, but also includes the image that is in the original post (at the beginning). I've not seen any other instance of using an excerpt that includes the image, so I suspect this is unexpected behavior.

### Steps to reproduce

1. Create a template using Flip Box
2. Flip Box should have content consisting of Excerpt, with the advance settings set to **Length** 25 and **Apply to post content** set to Yes.
3. Create a page using the Loop Grid element using the previously created template.
4. View page.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2
	MySQL version: Percona Server (GPL), Release 89.0, Revision d043d30 v5.6.49-89.0
	PHP Version: 7.4.10
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 20M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: There are some writing permissions issues with the following directories/files:
		 - WordPress root directory
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2
	Site URL: https://parsonsys.com
	Home URL: https://parsonsys.com
	WP Multisite: Yes
	Max Upload Size: 1 MB
	Memory limit: 64M
	Max Memory limit: 512M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: America/Chicago
	Admin Email: hparsons@parsonsys.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.7.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: 
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36

== Active Plugins ==
	Akismet Anti-Spam
		Version: 5.1
		Author: Automattic

	Bulk Media Register
		Version: 1.26
		Author: Katsushi Kawamori

	Elementor
		Version: 3.13.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.13.0
		Author: Elementor.com

	Folders
		Version: 2.9.2
		Author: Premio

	PublishPress Blocks
		Version: 3.1.4.2
		Author: PublishPress

	WordPress Importer
		Version: 0.8.1
		Author: wordpressdotorg


== Network Plugins ==
	Better Search Replace
		Version: 1.4.2
		Author: WP Engine

	Code Snippets
		Version: 3.3.0
		Author: Code Snippets Pro

	Manage Notification E-mails
		Version: 1.8.4
		Author: Virgial Berveling

	WordPress Importer
		Version: 0.8.1
		Author: wordpressdotorg

	WordPress Multisite Posts, Pages and Custom Post Type Posts Sync
		Version: 1.4.0
		Author: Obtain Infotech


== Elements Usage ==
	
	archive : 1
		archive-posts : 1
		heading : 1
		search-form : 1
		theme-archive-title : 1
		wp-widget-archives : 1
	header : 1
		html : 1
		icon : 2
		icon-list : 1
		image : 1
		search-form : 1
	wp-page : 7
		divider : 1
		flip-box : 2
		form : 1
		heading : 10
		loop-grid : 1
		menu-anchor : 4
		nav-menu : 2
		posts : 4
		social-icons : 1
		text-editor : 4
	single-post : 2
		search-form : 1
		text-editor : 1
		theme-post-content : 1
		theme-post-title : 1
		wp-widget-archives : 1
	loop-item : 1
		flip-box : 1
	error-404 : 3
		divider : 1
		heading : 5
		search-form : 1


== Settings ==
	
	cpt_support: post, page
	disable_color_schemes: yes
	disable_typography_schemes: yes
	allow_tracking: yes
	font_display: swap


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Upgrade Swiper Library: Active by default
	Grid Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Editor Top Bar: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Menu: Inactive by default


== Log ==
	
Log: showing 12 of 122023-05-10 15:05:52 [info] Elementor custom task(s) process has been queued. [array (
  0 => 
  array (
    0 => 
    array (
      0 => 'Elementor\Core\Upgrade\Custom_Tasks',
      1 => 'opt_in_recalculate_usage',
    ),
    1 => 
    array (
      0 => 'Elementor\Core\Upgrade\Custom_Tasks',
      1 => 'opt_in_send_tracking_data',
    ),
  ),
)]
2023-05-10 15:05:53 [info] elementor::custom_task_manger Started 
2023-05-10 15:05:53 [info] Elementor/Tasks - opt_in_recalculate_usage Start  
2023-05-10 15:05:53 [info] Elementor/Tasks - opt_in_recalculate_usage Finished 
2023-05-10 15:05:53 [info] Elementor/Tasks - opt_in_send_tracking_data Start  
2023-05-10 15:05:53 [info] Elementor/Tasks - opt_in_send_tracking_data Finished 
2023-05-10 15:05:53 [info] elementor::custom_task_manger Completed 
2023-05-11 20:01:59 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.1',
  'to' => '3.13.2',
)]
2023-05-11 20:02:00 [info] elementor::elementor_updater Started 
2023-05-11 20:02:00 [info] Elementor/Upgrades - _on_each_version Start  
2023-05-11 20:02:00 [info] Elementor/Upgrades - _on_each_version Finished 
2023-05-11 20:02:00 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.1',
  'to' => '3.13.2',
)]

PHP: showing 9 of 9PHP: 2023-05-10 15:44:00 [notice X 31][/hermes/bosnacweb08/bosnacweb08aq/b1835/ipg.hparsons/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-10 15:44:15 [notice X 42][/hermes/bosnacweb08/bosnacweb08aq/b1835/ipg.hparsons/wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-11 09:52:53 [error X 6][/hermes/bosnacweb08/bosnacweb08aq/b1835/ipg.hparsons/wp-content/plugins/elementor/includes/base/widget-base.php::183] Allowed memory size of 67108864 bytes exhausted (tried to allocate 81920 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-11 12:29:46 [error X 1][/hermes/bosnacweb08/bosnacweb08aq/b1835/ipg.hparsons/wp-content/plugins/elementor/includes/base/widget-base.php::183] Allowed memory size of 67108864 bytes exhausted (tried to allocate 20480 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-11 15:02:40 [error X 1][/hermes/bosnacweb08/bosnacweb08aq/b1835/ipg.hparsons/wp-content/plugins/elementor/core/wp-api.php::26] Uncaught Error: Call to undefined function Elementor\Core\get_plugins() in /hermes/bosnacweb08/bosnacweb08aq/b1835/ipg.hparsons/wp-content/plugins/elementor/core/wp-api.php:26
Stack trace:
#0 /hermes/bosnacweb08/bosnacweb08aq/b1835/ipg.hparsons/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(96): Elementor\Core\Wp_Api->get_plugins()
#1 /hermes/bosnacweb08/bosnacweb08aq/b1835/ipg.hparsons/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(58): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_with_header()
#2 /hermes/bosnacweb08/bosnacweb08aq/b1835/ipg.hparsons/wp-content/plugins/elementor/modules/compatibility-tag/module.php(57): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_to_check()
#3 /hermes/bosnacweb08/bosnacweb08aq/b1835/ipg.hparsons/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(148): Elementor\Modules\CompatibilityTag\Module->get_plugins_to_check()
#4 /hermes/bosnacweb08/bosnacweb08aq/b1835/ipg.hparsons/wp-incl [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-11 23:20:35 [error X 1][/hermes/bosnacweb08/bosnacweb08aq/b1835/ipg.hparsons/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::295] Uncaught Error: Call to a member function update_meta() on bool in /hermes/bosnacweb08/bosnacweb08aq/b1835/ipg.hparsons/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:295
Stack trace:
#0 /hermes/bosnacweb08/bosnacweb08aq/b1835/ipg.hparsons/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(168): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /hermes/bosnacweb08/bosnacweb08aq/b1835/ipg.hparsons/wp-content/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /hermes/bosnacweb08/bosnacweb08aq/b1835/ipg.hparsons/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /hermes/bosna [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-12 02:25:23 [notice X 1][/hermes/bosnacweb08/bosnacweb08aq/b1835/ipg.hparsons/wp-content/plugins/elementor/modules/history/revisions-manager.php::363] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-12 02:29:22 [notice X 1][/hermes/bosnacweb08/bosnacweb08aq/b1835/ipg.hparsons/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::168] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-12 02:30:22 [notice X 8][/hermes/bosnacweb08/bosnacweb08aq/b1835/ipg.hparsons/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined index: condition_type [array (
  'trace' => '
#0: /hermes/bosnacweb08/bosnacweb08aq/b1835/ipg.hparsons/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /hermes/bosnacweb08/bosnacweb08aq/b1835/ipg.hparsons/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /hermes/bosnacweb08/bosnacweb08aq/b1835/ipg.hparsons/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /hermes/bosnacweb08/bosnacweb08aq/b1835/ipg.hparsons/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]

JS: showing 8 of 8JS: 2023-05-10 20:44:26 [error X 2][https://parsonsys.com/wp-includes/js/jquery/jquery.js?ver=3.6.3:5257:17] Cannot create property 'guid' on string 'c37widgetsticky' 
JS: 2023-05-11 15:04:24 [error X 2][https://parsonsys.com/wp-includes/js/jquery/jquery.js?ver=3.6.3:5257:17] Cannot create property 'guid' on string 'c54widgetsticky' 
JS: 2023-05-11 15:04:24 [error X 2][https://parsonsys.com/wp-includes/js/jquery/jquery.js?ver=3.6.3:5257:17] Cannot create property 'guid' on string 'c67widgetsticky' 
JS: 2023-05-11 15:04:25 [error X 10][https://parsonsys.com/wp-includes/js/jquery/jquery.js?ver=3.6.3:5257:17] Cannot create property 'guid' on string 'c38widgetsticky' 
JS: 2023-05-11 15:04:31 [error X 55][https://parsonsys.com/wp-includes/js/jquery/jquery.js?ver=3.6.3:5257:17] Cannot create property 'guid' on string 'c47widgetsticky' 
JS: 2023-05-11 16:46:06 [error X 7][https://parsonsys.com/wp-content/plugins/elementor/assets/js/editor.js?ver=3.13.1:15086:59] Cannot read properties of undefined (reading 'id') 
JS: 2023-05-11 20:34:02 [error X 6][https://parsonsys.com/wp-content/plugins/elementor/assets/js/editor.js?ver=3.13.1:55698:44] Cannot read properties of null (reading 'getBoundingClientRect') 
JS: 2023-05-12 17:15:00 [error X 1][https://parsonsys.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.13.2:3:794943] Cannot read properties of undefined (reading 'toLowerCase') 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==
	

				
````

</details>

**Comment by nicholaszein** [comment]
Hello there @hparsons56!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro **v3.13.1**! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

Cheers 🥂
