### ISSUE TITLE
⛔ 🐞 Bug Report: Popup loading with full scroll instead of loading on top.

### ISSUE THREAD

**Issue by ofmarconi** [elementor/elementor#22444]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I'm having a problem on a site where the popup has scrolling, it's loading with full scrolling, an inappropriate behavior, because it needs to load at the top and not at the bottom.

You could check if you enter this URL: [https://evolmgmt.com.br/](https://evolmgmt.com.br/)

It happened after I updated to the latest version.

### Steps to reproduce

Screenrecord: https://www.loom.com/share/a0234d9aa2d246e1992d918b08ab8cc3
You could check if you enter this URL: [https://evolmgmt.com.br/](https://evolmgmt.com.br/)

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: Ubuntu 20.04 v10.3.38
	PHP Version: 7.4.33
	PHP Memory Limit: 256M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2
	Site URL: https://evolmgmt.com.br
	Home URL: https://evolmgmt.com.br
	WP Multisite: No
	Max Upload Size: 100 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: pt-BR
	Timezone: -3
	Admin Email: marconi@marks.art.br
	Debug Mode: Inactive

== Theme ==
	Name: By Marks.art.br
	Version: 1.1.4.1632168674
	Author: Marconi
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.7.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: pt_BR
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36

== Active Plugins ==
	Admin Columns Pro
		Version: 5.6.4
		Author: AdminColumns.com

	Advanced Database Cleaner PRO
		Version: 3.1.7
		Author: Younes JFR.

	Duplicate Page
		Version: 4.5.2
		Author: mndpsingh287

	Elementor
		Version: 3.13.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.13.1
		Author: Elementor.com

	JetElements For Elementor
		Version: 2.6.9
		Author: Crocoblock

	JetEngine
		Version: 3.1.5
		Author: Crocoblock

	JetSearch
		Version: 3.0.3
		Author: Crocoblock

	ManageWP - Worker
		Version: 4.9.17
		Author: GoDaddy

	Page scroll to id
		Version: 1.7.7
		Author: malihu

	Perfmatters
		Version: 1.8.6
		Author: forgemedia

	Query Monitor
		Version: 3.12.2
		Author: John Blackbourn

	Rank Math SEO
		Version: 1.0.114
		Author: Rank Math

	Redirection
		Version: 5.3.10
		Author: John Godley

	Retarget Marks
		Version: 2.2
		Author: Marconi

	Super Page Cache for Cloudflare
		Version: 4.7.3
		Author: Optimole

	WP Offload SES Lite
		Version: 1.6.3
		Author: Delicious Brains

	WPS Hide Login
		Version: 1.9.8
		Author: WPServeur, NicolasKulka, wpformation


== Must-Use Plugins ==
	ManageWP - Worker Loader
		Version: 1.0.0
		Author: GoDaddy


== Recursos ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrações ==
	
	recaptcha_v3: Ativo


== Experimentos do Elementor ==
	Saída DOM otimizada: Ativo
	Carregamento melhorado de recursos: Ativo
	Carregamento melhorado de CSS: Ativo
	Ícones da fonte inline: Inativo
	Melhorias na acessibilidade: Ativo
	Pontos de quebra adicionais personalizados: Inativo
	admin_menu_rearrangement: Inativo por padrão
	Flexbox Container: Ativo
	Atualize a biblioteca Swiper: Inativo por padrão
	Grid Container: Inativo por padrão
	Padrão para Novo Construtor de Tema: Inativo
	Tema Hello - Cabeçalho & Rodapé: Inativo
	Editor Top Bar: Inativo por padrão
	Landing Pages: Inativo
	Elementos aninhados: Inativo por padrão
	Imagens com carregamento gradual: Inativo por padrão
	Transições da página: Ativo por padrão
	Atividades Desempenhadas: Ativo por padrão
	Repetir: Ativo por padrão
	Envios do formulário: Ativo por padrão
	Pressão da Rolagem: Ativo por padrão
	Menu: Inativo por padrão


== Registo ==
	
JS: showing 14 of 14JS: 2022-05-11 17:25:28 [error X 1][https://evolmgmt.com.br/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view80\") has already been destroyed and cannot be used. 
JS: 2022-05-11 18:15:06 [error X 1][https://evolmgmt.com.br/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view83\") has already been destroyed and cannot be used. 
JS: 2022-05-11 19:07:32 [error X 2][https://evolmgmt.com.br/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view112\") has already been destroyed and cannot be used. 
JS: 2022-05-11 22:33:47 [error X 1][https://evolmgmt.com.br/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view75\") has already been destroyed and cannot be used. 
JS: 2022-05-11 22:42:08 [error X 2][https://evolmgmt.com.br/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view104\") has already been destroyed and cannot be used. 
JS: 2022-05-11 23:44:12 [error X 8][https://evolmgmt.com.br/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view86\") has already been destroyed and cannot be used. 
JS: 2022-05-25 22:14:15 [error X 3][https://evolmgmt.com.br/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view102\") has already been destroyed and cannot be used. 
JS: 2022-05-30 18:29:58 [error X 1][https://evolmgmt.com.br/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view109\") has already been destroyed and cannot be used. 
JS: 2022-05-30 19:01:22 [error X 2][https://evolmgmt.com.br/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view134\") has already been destroyed and cannot be used. 
JS: 2022-05-30 20:27:00 [error X 9][https://evolmgmt.com.br/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view93\") has already been destroyed and cannot be used. 
JS: 2022-06-09 20:11:39 [error X 3][https://evolmgmt.com.br/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view119\") has already been destroyed and cannot be used. 
JS: 2022-06-10 01:27:38 [error X 4][https://evolmgmt.com.br/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view120\") has already been destroyed and cannot be used. 
JS: 2022-08-11 18:22:36 [error X 1][https://evolmgmt.com.br/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view2093\") has already been destroyed and cannot be used. 
JS: 2022-08-11 18:44:25 [error X 1][https://evolmgmt.com.br/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view9819\") has already been destroyed and cannot be used. 

PHP: showing 13 of 13PHP: 2022-05-11 14:41:47 [error X 1][/home/evolmgmt.com.br/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::286] Uncaught Error: Call to a member function update_meta() on bool in /home/evolmgmt.com.br/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:286
Stack trace:
#0 /home/evolmgmt.com.br/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions()
#2 /home/evolmgmt.com.br/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func()
#3 /home/evolmgmt.com.br/public_html/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#4 /home/evolmgmt.com.br/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#5 /home/evolmgmt.com.br/public_html/wp-includes/plugin.php(474): WP_Hook->do_action()
#6 /home/evolmgmt.com.br/public_html/wp-admin/admin-ajax.php(187): do_action()
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-11 16:07:34 [notice X 136378][/home/evolmgmt.com.br/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] O argumento $control_id está obsoleto desde a versão 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-11 16:08:10 [notice X 232][/home/evolmgmt.com.br/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] O argumento $control_id está obsoleto desde a versão 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/evolmgmt.com.br/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /home/evolmgmt.com.br/public_html/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home/evolmgmt.com.br/public_html/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home/evolmgmt.com.br/public_html/wp-content/plugins/jet-elements/includes/class-jet-elements-integration.php(247): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-05-11 16:08:10 [notice X 233][/home/evolmgmt.com.br/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] O argumento $control_id está obsoleto desde a versão 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/evolmgmt.com.br/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /home/evolmgmt.com.br/public_html/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home/evolmgmt.com.br/public_html/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home/evolmgmt.com.br/public_html/wp-content/plugins/jet-elements/includes/class-jet-elements-integration.php(285): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-05-11 16:08:10 [notice X 233][/home/evolmgmt.com.br/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] O argumento $control_id está obsoleto desde a versão 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/evolmgmt.com.br/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /home/evolmgmt.com.br/public_html/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home/evolmgmt.com.br/public_html/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home/evolmgmt.com.br/public_html/wp-content/plugins/jet-elements/includes/modules/jet-elementor-extension/jet-elementor-extension.php(95): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-05-11 16:08:10 [notice X 233][/home/evolmgmt.com.br/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] O argumento $control_id está obsoleto desde a versão 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/evolmgmt.com.br/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /home/evolmgmt.com.br/public_html/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home/evolmgmt.com.br/public_html/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home/evolmgmt.com.br/public_html/wp-content/plugins/jet-elements/includes/modules/jet-elementor-extension/jet-elementor-extension.php(96): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-05-11 16:08:10 [notice X 233][/home/evolmgmt.com.br/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] O argumento $control_id está obsoleto desde a versão 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/evolmgmt.com.br/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /home/evolmgmt.com.br/public_html/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home/evolmgmt.com.br/public_html/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home/evolmgmt.com.br/public_html/wp-content/plugins/jet-search/includes/integration.php(108): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-05-26 08:17:28 [error X 1][/home/evolmgmt.com.br/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::286] Uncaught Error: Call to a member function update_meta() on bool in /home/evolmgmt.com.br/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:286
Stack trace:
#0 /home/evolmgmt.com.br/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions()
#2 /home/evolmgmt.com.br/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func()
#3 /home/evolmgmt.com.br/public_html/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#4 /home/evolmgmt.com.br/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#5 /home/evolmgmt.com.br/public_html/wp-includes/plugin.php(476): WP_Hook->do_action()
#6 /home/evolmgmt.com.br/public_html/wp-admin/admin-ajax.php(187): do_action()
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-26 08:51:24 [error X 1][/home/evolmgmt.com.br/public_html/wp-content/plugins/elementor-pro/modules/popup/module.php::102] Uncaught Error: Call to a member function save_display_settings_data() on bool in /home/evolmgmt.com.br/public_html/wp-content/plugins/elementor-pro/modules/popup/module.php:102
Stack trace:
#0 [internal function]: ElementorPro\Modules\Popup\Module->save_display_settings()
#1 /home/evolmgmt.com.br/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func()
#2 /home/evolmgmt.com.br/public_html/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#3 /home/evolmgmt.com.br/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#4 /home/evolmgmt.com.br/public_html/wp-includes/plugin.php(476): WP_Hook->do_action()
#5 /home/evolmgmt.com.br/public_html/wp-admin/admin-ajax.php(187): do_action()
#6 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-06 16:47:29 [warning X 490][/home/evolmgmt.com.br/public_html/wp-content/plugins/elementor-pro/modules/forms/classes/form-record.php::179] Undefined array key "referrer" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-29 16:47:06 [notice X 2978][/home/evolmgmt.com.br/public_html/wp-content/plugins/elementor-pro/modules/forms/classes/form-record.php::179] Undefined index: referrer [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-27 13:29:03 [notice X 1][/home/evolmgmt.com.br/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-13 14:23:54 [notice X 4][/home/evolmgmt.com.br/public_html/wp-content/plugins/elementor-pro/modules/forms/classes/recaptcha-v3-handler.php::124] Undefined index: score [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 16 of 162023-05-13 21:50:15 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.5',
  'to' => '3.13.2',
)]
2023-05-13 21:50:15 [info] elementor::elementor_updater Started 
2023-05-13 21:50:15 [info] Elementor/Upgrades - _on_each_version Start  
2023-05-13 21:50:15 [info] Elementor/Upgrades - _on_each_version Finished 
2023-05-13 21:50:15 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Start  
2023-05-13 21:50:15 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Finished 
2023-05-13 21:50:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.5',
  'to' => '3.13.2',
)]
2023-05-13 23:32:21 [info] elementor-pro::elementor_pro_updater Started 
2023-05-13 23:32:21 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-05-13 23:32:21 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-05-13 23:32:21 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.5',
  'to' => '3.12.2',
)]
2023-05-13 23:41:24 [info] elementor-pro::elementor_pro_updater Started 
2023-05-13 23:41:24 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-05-13 23:41:24 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-05-13 23:41:24 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.2',
  'to' => '3.13.1',
)]
2023-05-13 23:41:24 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.2',
  'to' => '3.13.1',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibilidade não especificada
	JetElements For Elementor: Compatibilidade não especificada

== Elementor Pro - Compatibility Tag ==
	

				
````

</details>

**Comment by nicholaszein** [comment]
Hi, @ofmarconi! 

Thank you for submitting your issue! 🙏 

Please allow us some time to investigate it, and get back to you with our findings. 🧐 

Best regards

**Comment by nicholaszein** [comment]
Hello @ofmarconi,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
- The Popup is doing what it was supposed to do when the option for `Accessible navigation` is active in the Popup `Settings` ⚙️ > Advanced tab > Advanced section.
- Since you have a link at the bottom of your Popup (Models), it will focus on that link, as it is the first focusable link inside the Popup.

### ✅ What you can do to solve your issue:
- Deactivate the option for `Accessible navigation` in the Popup Settings ⚙️ 
![image](https://github.com/elementor/elementor/assets/113993460/1238e4e9-9aa4-41b1-b879-2eb6b53f421b)


### 👍 For now, that's all we can help with. 

Note that this is more of a support question, not really something we can help with here. Please remember to check the Help Center or contact Elementor Support before submitting an issue.

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
