### ISSUE TITLE
Woocommerce checkout widget loading issue

### ISSUE THREAD

**Issue by OppositeFool** [elementor/elementor#22483]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Recently, elementor and wocommerce checkout page started hating each other and stopped working.
I have an elementor page with the checkout widget. In the your order section the widget struggles to load and eventually displays the error.
While I have the latest elementor, elementor pro and woocommerce plugins, the issue still exists.

The error is about a _check_layout_ index which is not found in a comparison array in the conditions.php script.

### Steps to reproduce

1. Install the Elementor, Elementor Pro and Woocommerce plugins
2. Create the checkout page with the checkout widget.
3. Assign the checkout page in the site settings as the base checkout page.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.5.19
	PHP Version: 7.4.33
	PHP Memory Limit: 512M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2.1
	Site URL: https://maginstruments.mashupdigital.hu
	Home URL: https://maginstruments.mashupdigital.hu
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: pgddedi2@gmail.com
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.7.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36

== Active Plugins ==
	ACF QuickEdit Fields
		Version: 3.2.6
		Author: Jörn Lund

	Advanced Custom Fields
		Version: 6.1.6
		Author: WP Engine

	Advanced Post Queries
		Version: 1.1.1
		Author: Shabti Kaplan

	Custom Post Type UI
		Version: 1.13.5
		Author: WebDevStudios

	Dynamic Visibility for Elementor
		Version: 5.0.4
		Author: Dynamic.ooo

	Elementor
		Version: 3.13.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.13.1
		Author: Elementor.com

	Extra Product Options & Add-Ons for WooCommerce
		Version: 6.3.2
		Author: ThemeComplete

	FiboSearch - AJAX Search for WooCommerce
		Version: 1.23.0
		Author: FiboSearch Team

	Filter Everything PRO
		Version: 1.7.6
		Author: Andrii Stepasiuk

	Qty Increment Buttons for WooCommerce
		Version: 2.7.5
		Author: taisho

	WooCommerce
		Version: 7.7.0
		Author: Automattic

== Elements Usage ==
	
	container : 1
		container : 2
		heading : 2
		icon : 1
	footer : 1
		container : 2
		divider : 1
		heading : 2
		image : 2
		nav-menu : 1
		social-icons : 1
	header : 1
		container : 6
		icon : 3
		image : 2
		nav-menu : 2
		shortcode : 1
	popup : 1
		container : 4
		heading : 4
		image : 3
		text-editor : 1
	product : 1
		button : 1
		container : 12
		heading : 14
		icon : 3
		loop-carousel : 1
		loop-grid : 1
		text-editor : 1
		video : 1
		woocommerce-product-add-to-cart : 2
		woocommerce-product-images : 1
	wp-page : 13
		button : 6
		container : 120
		divider : 6
		form : 1
		gallery : 1
		heading : 39
		image : 65
		loop-carousel : 2
		loop-grid : 4
		slides : 1
		text-editor : 59
		toggle : 1
		woocommerce-cart : 1
		woocommerce-checkout-page : 1
		woocommerce-my-account : 1
		woocommerce-purchase-summary : 1
		wp-widget-wpc_filters_widget : 1
	product-archive : 3
		button : 2
		container : 21
		form : 1
		heading : 9
		image : 10
		loop-grid : 3
		shortcode : 1
		text-editor : 5
		wp-widget-wpc_filters_widget : 1
		wp-widget-wpc_sorting_widget : 1
	loop-item : 12
		container : 6
		heading : 10
		image : 5
		social-icons : 2
		woocommerce-product-price : 1

== Settings ==
	
	cpt_support: post, page
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap

== Features ==
	Custom Fonts: 1
	Custom Icons: 0

== Integrations ==
	
	woocommerce: Active

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active by default
	Grid Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Editor Top Bar: Active
	Landing Pages: Active by default
	Nested Elements: Active
	Lazy Load Background Images: Inactive by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Menu: Active

== Log ==
	
PHP: showing 11 of 11PHP: 2023-04-04 08:52:02 [notice X 34][/home/jgscuuol/maginstruments.mashupdigital.hu/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-04 09:01:07 [notice X 23][/home/jgscuuol/maginstruments.mashupdigital.hu/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::168] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-04 09:02:02 [notice X 1][/home/jgscuuol/maginstruments.mashupdigital.hu/wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-04 09:06:22 [error X 4][/home/jgscuuol/maginstruments.mashupdigital.hu/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::295] Uncaught Error: Call to a member function update_meta() on bool in /home/jgscuuol/maginstruments.mashupdigital.hu/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:295
Stack trace:
#0 /home/jgscuuol/maginstruments.mashupdigital.hu/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(168): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/jgscuuol/maginstruments.mashupdigital.hu/wp-content/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/jgscuuol/maginstruments.mashupdigital.hu/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/jgscuuol/maginstruments.mashupd [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-05 10:36:41 [notice X 2][/home/jgscuuol/maginstruments.mashupdigital.hu/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php::33] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-05 11:53:21 [notice X 105][/home/jgscuuol/maginstruments.mashupdigital.hu/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined index: condition_type [array (
  'trace' => '
#0: /home/jgscuuol/maginstruments.mashupdigital.hu/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /home/jgscuuol/maginstruments.mashupdigital.hu/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /home/jgscuuol/maginstruments.mashupdigital.hu/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /home/jgscuuol/maginstruments.mashupdigital.hu/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2023-05-02 12:35:21 [warning X 87][/home/jgscuuol/maginstruments.mashupdigital.hu/wp-content/plugins/elementor-pro/modules/woocommerce/module.php::1487] A non-numeric value encountered [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-12 14:34:04 [notice X 58][/home/jgscuuol/maginstruments.mashupdigital.hu/wp-content/plugins/elementor/includes/conditions.php::87] Undefined index: checkout_layout [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-17 11:44:34 [notice X 6][/home/jgscuuol/maginstruments.mashupdigital.hu/wp-content/plugins/elementor/modules/history/revisions-manager.php::363] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-18 12:30:16 [error X 1][/home/jgscuuol/maginstruments.mashupdigital.hu/wp-content/plugins/elementor/includes/conditions.php::87] syntax error, unexpected ')', expecting ']' [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-18 12:30:29 [error X 1][/home/jgscuuol/maginstruments.mashupdigital.hu/wp-content/plugins/elementor/includes/conditions.php::87] syntax error, unexpected '{' [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 8 of 8JS: 2023-04-04 09:02:12 [error X 9][https://maginstruments.mashupdigital.hu/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.12.1:3:785238] Cannot read properties of undefined (reading 'toLowerCase') 
JS: 2023-04-04 10:33:06 [error X 1][https://maginstruments.mashupdigital.hu/wp-content/plugins/elementor/assets/js/df16c9d56464dd4f0800.bundle.min.js:2:7826] Cannot read properties of null (reading 'dataset') 
JS: 2023-04-05 09:11:41 [error X 31][https://maginstruments.mashupdigital.hu/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.12.1:3:785745] Cannot read properties of undefined (reading 'localized') 
JS: 2023-04-05 09:12:35 [error X 2][https://maginstruments.mashupdigital.hu/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.12.1:3:1081267] Cannot read properties of null (reading 'getBoundingClientRect') 
JS: 2023-04-21 09:46:18 [error X 1][https://maginstruments.mashupdigital.hu/wp-content/plugins/elementor/assets/js/editor-document.min.js?ver=3.12.1:2:4095] Cannot read properties of null (reading 'history') 
JS: 2023-05-05 13:39:37 [error X 4][https://maginstruments.mashupdigital.hu/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.12.2:3:310955] Cannot read properties of undefined (reading 'html') 
JS: 2023-05-17 13:48:22 [error X 1][https://maginstruments.mashupdigital.hu/wp-content/plugins/elementor/assets/js/packages/documents.min.js?ver=3.13.2:1:718] Cannot read properties of null (reading 'config') 
JS: 2023-05-17 13:52:21 [error X 3][https://maginstruments.mashupdigital.hu/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.13.2:3:612474] Cannot read properties of undefined (reading 'isEditable') 

Log: showing 20 of 202023-04-25 13:38:20 [info] elementor::elementor_updater Started 
2023-04-25 13:38:20 [info] Elementor/Upgrades - _on_each_version Start  
2023-04-25 13:38:21 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.1',
  'to' => '3.12.2',
)]
2023-04-25 13:38:21 [info] Elementor/Upgrades - _on_each_version Finished 
2023-04-25 13:38:21 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.1',
  'to' => '3.12.2',
)]
2023-05-09 13:08:30 [info] elementor::elementor_updater Started 
2023-05-09 13:08:30 [info] Elementor/Upgrades - _on_each_version Start  
2023-05-09 13:08:30 [info] Elementor/Upgrades - _on_each_version Finished 
2023-05-09 13:08:30 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.2',
  'to' => '3.13.1',
)]
2023-05-09 13:08:30 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.2',
  'to' => '3.13.1',
)]
2023-05-16 08:01:54 [info] elementor-pro::elementor_pro_updater Started 
2023-05-16 08:01:54 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-05-16 08:01:54 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-05-16 08:01:54 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.1',
  'to' => '3.13.1',
)]
2023-05-16 08:01:54 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.1',
  'to' => '3.13.1',
)]
2023-05-16 08:02:05 [info] elementor::elementor_updater Started 
2023-05-16 08:02:05 [info] Elementor/Upgrades - _on_each_version Start  
2023-05-16 08:02:05 [info] Elementor/Upgrades - _on_each_version Finished 
2023-05-16 08:02:05 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.1',
  'to' => '3.13.2',
)]
2023-05-16 08:02:05 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.1',
  'to' => '3.13.2',
)]

== Elementor - Compatibility Tag ==
	
	Dynamic Visibility for Elementor: Incompatible
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==
	
	Dynamic Visibility for Elementor: Incompatible

**Comment by nicholaszein** [comment]
Hello @OppositeFool! 

Thank you for submitting your issue! 🙏 

Please allow us some time to investigate it, and get back to you with our findings. 🧐 

Best regards

**Comment by aleksJ351** [comment]
Similar issue, happens on an Elementor made custom Shop page

"Warning: A non-numeric value encountered in /home/customer/www/***.com/public_html/wp-content/plugins/elementor-pro/modules/woocommerce/module.php on line 1544"

Happens with recent Elementor versions, with different themes, caches cleared... Please recommend actions

**Comment by relima** [comment]
i am also having this problem with the latest elementor pro version

**Comment by vHeemstra** [comment]
Some info around the error (from Query Monitor plugin):
```js
{
    "key": "0d5d19445a8c4517c11de15eb61d97bb",
    "type": "warning",
    "message": "Undefined array key \"checkout_layout\"",
    "file": "wp-content/plugins/elementor/includes/conditions.php",
    "line": 87,
    "stack": [
        "Elementor\\Conditions::check()",
        "Elementor\\Controls_Stack->is_control_visible()",
        "Elementor\\Controls_Stack->get_active_settings()",
        "Elementor\\Controls_Stack->get_settings_for_display()",
        "ElementorPro\\M\\W\\W\\Checkout->init_gettext_modifications()",
        "ElementorPro\\M\\W\\W\\Base_Widget->filter_gettext()",
        "apply_filters('gettext')",
        "translate()",
        "esc_html_e()",
        "wc_get_template()",
        "woocommerce_order_review()",
        "WC_AJAX::update_order_review()",
        "do_action('wc_ajax_update_order_review')",
        "WC_AJAX::do_wc_ajax()",
        "do_action('template_redirect')"
    ],
    "component": "Plugin: elementor"
}
```

**Comment by vHeemstra** [comment]
### Problem 1: fix typo in widget condition definition
`wp-content\plugins\elementor-pro\modules\woocommerce\widgets\checkout.php` @ line 114:

```php
'operator' => '=', // <--- Should be: '=='
```
According to the [official documentation](https://developers.elementor.com/docs/editor-controls/conditional-display/#available-values), this value is wrong. Should be double equal sign.

### Problem 2: Not all settings are being sent to the back-end to save
The `save_builder` object has no `checkout_layout` key at all (which should be the setting for 1 or 2 column layout for this widget). Logically this results in a saved/stored settings array/object without a value for `checkout_layout`.

This widget has more problems with settings not getting saved at all or properly. Like the text transform property/setting on form labels, but there are more. In the Thank you page Widget as well...
So maybe there is a larger bug or problem with the way settings are collected/stored/etc? Maybe a local browser storage limit to the amount of data that can be stored in client?

**Comment by Maiload-Sas** [comment]
We are experiencing the same issue in a production environment, specifically when using the Elementor Checkout widget with WooCommerce.

The warnings are triggered during AJAX requests (/?wc-ajax=update_order_review) and occur very frequently on active stores.

Environment:
- WordPress: latest
- Elementor / Pro: latest
- PHP: 8.5
- WooCommerce: active
- Server: Nginx (Kinsta)

Impact:
- Significant log flooding in production
- Makes real errors harder to detect
- Affects a critical part of the site (checkout flow)

This is not just a generic PHP warning, but a reproducible issue tied to Elementor's handling of conditions without checking array keys.

Would it be possible to prioritize this, given the impact on live e-commerce environments?

Happy to provide additional logs or test cases if needed.
