### ISSUE TITLE
⛔ 🛟 Support Request: Unable to save on elementor

### ISSUE THREAD

**Issue by vibi23** [elementor/elementor#22494]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I cant able to save on elementor, i try to disable all the plugin, everthing. If i create a new page the problem disappear, but if i copy the element from the page that i cant save. I see this error "Error server 403 or 413 Forbidden". How i can fix this?  
 

### Steps to reproduce

1)Every page publish cant save when i update.
2) If i create a new page i can save
3)When i copy the container or an elements from a public page i cant save and i see error server (403 Request)

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Debian 11 v10.5.19
	PHP Version: 7.3.33-10+0~20230409.104+debian11~1.gbp88ff76
	PHP Memory Limit: 128M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 40M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2.1
	Site URL: https://www.sagis.tn.it
	Home URL: https://www.sagis.tn.it
	WP Multisite: No
	Max Upload Size: 40 MB
	Memory limit: 256M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: it-IT
	Timezone: Europe/Rome
	Admin Email: valentinaboselli@live.com
	Debug Mode: Inactive

== Theme ==
	Name: Phlox Pro Child
	Version: 1.0
	Author: averta
	Child Theme: Yes
	Parent Theme Name: Phlox Pro
	Parent Theme Version: 5.9.1
	Parent Theme Author: averta

== User ==
	Role: administrator
	WP Profile lang: it_IT
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36

== Active Plugins ==
	Akismet Anti-Spam: Spam Protection
		Version: 5.1
		Author: Automattic - Anti Spam Team

	Cookie Notice & Compliance for GDPR / CCPA
		Version: 2.4.8
		Author: Hu-manity.co

	Elementor
		Version: 3.13.2
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Element Pack Pro
		Version: 6.10.0
		Author: BdThemes

	Health Check & Troubleshooting
		Version: 1.6.0
		Author: The WordPress.org community

	LiteSpeed Cache
		Version: 5.4
		Author: LiteSpeed Technologies

	Master Slider Pro
		Version: 3.2.11
		Author: averta

	Phlox Core Elements
		Version: 2.12.0
		Author: averta

	Site Kit by Google
		Version: 1.99.0
		Author: Google

	Smush
		Version: 3.12.6
		Author: WPMU DEV

	Wordfence Security
		Version: 7.9.2
		Author: Wordfence

	WP-Sweep
		Version: 1.1.8
		Author: Lester 'GaMerZ' Chan

	Yoast SEO
		Version: 20.7
		Author: Team Yoast


== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

	Health Check Troubleshooting Mode
		Version: 1.9.0
		Author: 


== Utilizzo degli elementi ==
	
	footer : 7
		aux_icon_list : 1
		text-editor : 3
	header : 4
		aux_button : 2
		aux_logo : 4
		aux_menu_box : 4
	page : 4
		aux_image : 1
		aux_text : 1
		social-icons : 1
		text-editor : 1
	section : 16
		aux-gallery : 2
		aux_icon_list : 3
		aux_mailchimp : 2
		aux_masterslider : 1
		aux_modern_heading : 6
		aux_recent_posts : 2
		text-editor : 9
	wp-post : 6
		aux-gallery : 7
		aux_icon_list : 2
		aux_image : 6
		aux_mailchimp : 1
		aux_masterslider : 2
		aux_modern_heading : 48
		aux_recent_posts : 4
		aux_text : 23
		bdt-table : 4
		button : 7
		html : 1
		image : 2
		text-editor : 37
		toggle : 18
		video : 1
	wp-page : 14
		aux_text : 1
		container : 4
		text-editor : 1


== Impostazioni ==
	
	cpt_support: post, page
	allow_tracking: yes
	css_print_method: internal
	editor_break_lines: 1
	load_fa4_shim: yes


== Esperimenti Elementor ==
	Uscita DOM ottimizzata: Attivo per impostazione predefinita
	Caricamento delle risorse migliorato: Attivo per impostazione predefinita
	Caricamento CSS migliorato: Attivo per impostazione predefinita
	Icone dei font in linea: Attivo per impostazione predefinita
	Miglioramenti dell'accessibilità: Attivo per impostazione predefinita
	Punti di interruzione aggiuntivi: Attivo per impostazione predefinita
	admin_menu_rearrangement: Inattivo per impostazione predefinita
	Contenitore Flexbox: Attiva
	Upgrade Swiper Library: Attivo per impostazione predefinita
	Grid Container: Inattivo per impostazione predefinita
	Editor Top Bar: Inattivo per impostazione predefinita
	Landing Page: Attivo per impostazione predefinita
	Nested Elements: Attivo per impostazione predefinita
	Lazy Load Background Images: Attiva


== Registro ==
	
PHP: showing 4 of 4PHP: 2022-12-24 10:02:27 [error X 1][/home/web/www.sagis.tn.it/www/wp-content/plugins/elementor/includes/template-library/sources/local.php::1080] Uncaught TypeError: Argument 2 passed to Elementor\TemplateLibrary\Source_Local::on_save_post() must be an instance of WP_Post, null given, called in /home/web/www.sagis.tn.it/www/wp-includes/class-wp-hook.php on line 310 and defined in /home/web/www.sagis.tn.it/www/wp-content/plugins/elementor/includes/template-library/sources/local.php:1080
Stack trace:
#0 /home/web/www.sagis.tn.it/www/wp-includes/class-wp-hook.php(310): Elementor\TemplateLibrary\Source_Local->on_save_post(6906, NULL)
#1 /home/web/www.sagis.tn.it/www/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#2 /home/web/www.sagis.tn.it/www/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#3 /home/web/www.sagis.tn.it/www/wp-includes/post.php(4717): do_action('save_post', 6906, NULL, true)
#4 /home/web/www.sagis.tn.it/www/wp-includes/post.php(4819): wp_insert_post(Array, false, true)
#5 /home/web/www.sagis.tn.it/www/wp-content/plugins/elementor/includes/db.php(235): wp_update_post(Array)
#6 /home/web/www.sagis.tn.it/www/wp [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-04 14:04:11 [notice X 33985][/home/web/www.sagis.tn.it/www/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] L'argomento $control_id è deprecato dalla versione 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-03 15:05:35 [notice X 4][/home/web/www.sagis.tn.it/www/wp-content/plugins/elementor/includes/template-library/sources/local.php::1031] Trying to get property 'post_type' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-09 19:51:49 [notice X 40][/home/web/www.sagis.tn.it/www/wp-content/plugins/elementor/includes/widgets/toggle.php::595] Undefined index: icon_active [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 20 of 352023-04-27 13:18:51 [info] Elementor/Upgrades - _on_each_version Start  
2023-04-27 13:18:52 [info] Elementor/Upgrades - _on_each_version Finished 
2023-04-27 13:18:52 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Start  
2023-04-27 13:18:52 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Finished 
2023-04-27 13:18:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.2',
  'to' => '3.12.2',
)]
2023-05-08 21:06:05 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.2',
  'to' => '3.13.0',
)]
2023-05-08 21:06:06 [info] elementor::elementor_updater Started 
2023-05-08 21:06:06 [info] Elementor/Upgrades - _on_each_version Start  
2023-05-08 21:06:07 [info] Elementor/Upgrades - _on_each_version Finished 
2023-05-08 21:06:07 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.2',
  'to' => '3.13.0',
)]
2023-05-09 17:56:10 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.0',
  'to' => '3.13.1',
)]
2023-05-09 17:56:10 [info] elementor::elementor_updater Started 
2023-05-09 17:56:10 [info] Elementor/Upgrades - _on_each_version Start  
2023-05-09 17:56:11 [info] Elementor/Upgrades - _on_each_version Finished 
2023-05-09 17:56:11 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.0',
  'to' => '3.13.1',
)]
2023-05-11 22:31:32 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.1',
  'to' => '3.13.2',
)]
2023-05-11 22:31:33 [info] elementor::elementor_updater Started 
2023-05-11 22:31:33 [info] Elementor/Upgrades - _on_each_version Start  
2023-05-11 22:31:35 [info] Elementor/Upgrades - _on_each_version Finished 
2023-05-11 22:31:35 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.1',
  'to' => '3.13.2',
)]

JS: showing 4 of 4JS: 2023-04-04 14:54:18 [error X 4][https://www.sagis.tn.it/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.12.1:3:632658] Cannot read properties of undefined (reading 'isDesignable') 
JS: 2023-05-03 11:07:30 [error X 3][https://www.sagis.tn.it/wp-content/plugins/bdthemes-element-pack/assets/vendor/js/datatables.min.js:4:6426] Cannot read properties of undefined (reading 'mData') 
JS: 2023-05-03 11:17:32 [error X 1][https://www.sagis.tn.it/wp-content/plugins/bdthemes-element-pack/assets/vendor/js/datatables.min.js:4:21364] Cannot read properties of undefined (reading 'cell') 
JS: 2023-05-19 16:49:11 [error X 1][https://www.sagis.tn.it/wp-content/plugins/elementor/assets/js/new-template.min.js?ver=3.13.2:2:2932] elementor_new_template_form_controls is not defined 



== Elementor - Compatibility Tag ==
	

````

</details>

**Comment by nicholaszein** [comment]
Hello @vibi23,

Thanks for contacting us! 🙏 

### 🛟 This is more of a support question, not really something we can help with here. 

👉 Please remember to check the Help Center or contact Elementor Support before submitting an issue.

The errors 403 and 413 are caused by your Web Application Firewall (WAF). This could be a security plugin like Wordfence, or a firewall from your server.

Follow the instructions in the article about this issue on the Help Center:
https://elementor.com/help/publish-update-button-not-work/


### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Regards,

Nick
