### ISSUE TITLE
Video widget appears half of the height in Firefox and Chrome (v. 3.13.3)

### ISSUE THREAD

**Issue by andishanti** [elementor/elementor#22574]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

The issue I have was already mentioned here (https://github.com/elementor/elementor/issues/21454), which seemed to be solved with 3.13., but it still occurs on my webpage.

Issue can be seen at the bottom of: https://praxisfischer-mm.de/
In the backend, everything looks like it should, but on the frontend, the video dimensions are wrong.

Backend:
![grafik](https://github.com/elementor/elementor/assets/134847611/b2006a0f-9404-4646-a588-fb95f0df400c)

Frontend:
![grafik](https://github.com/elementor/elementor/assets/134847611/0e7db2c7-e32d-40d9-b80f-b9657269f6a5)

### Steps to reproduce

1) Use Elementor Video Widget
2) Preview in Browser

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.7.36
	PHP Version: 7.4.33
	PHP Memory Limit: 256M
	PHP Max Input Vars: 8192
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2.2
	Site URL: https://praxisfischer-mm.de
	Home URL: https://praxisfischer-mm.de
	WP Multisite: Yes
	Max Upload Size: 1 MB
	Memory limit: 64M
	Max Memory limit: 256M
	Permalink Structure: /blog/%year%/%monthnum%/%day%/%postname%/
	Language: de-DE
	Timezone: 1
	Admin Email: sieben.fischer@online.de
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.7.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/113.0

== Active Plugins ==
	Borlabs Cookie - Cookie Opt-in
		Version: 2.2.63
		Author: Borlabs GmbH

	Easy PayPal Events
		Version: 1.1.7
		Author: Scott Paterson

	Elementor
		Version: 3.13.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.12.2
		Author: Elementor.com

	Site Kit by Google
		Version: 1.101.0
		Author: Google

	WP Mail SMTP
		Version: 3.8.0
		Author: WP Mail SMTP

	Yoast SEO
		Version: 20.8
		Author: Team Yoast

== Network Plugins ==
	Borlabs Cookie - Cookie Opt-in
		Version: 2.2.63
		Author: Borlabs GmbH

	Elementor
		Version: 3.13.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.12.2
		Author: Elementor.com

	WP Mail SMTP
		Version: 3.8.0
		Author: WP Mail SMTP

	Yoast SEO
		Version: 20.8
		Author: Team Yoast

== Eigenschaften ==
	Custom Fonts: 1
	Custom Icons: 0

== Integrations ==
	
	recaptcha_v3: Aktiv

== Elementor-Experimente ==
	Optimierte DOM Ausgabe: Standardmäßig aktiviert
	Verbessertes Laden von Assets: Standardmäßig deaktiviert
	Verbessertes Laden von CSS: Standardmäßig deaktiviert
	Inline-Schriftarten-Symbole: Standardmäßig deaktiviert
	Verbesserungen der Zugänglichkeit: Standardmäßig aktiviert
	Zusätzliche benutzerdefinierte Breakpoints: Standardmäßig aktiviert
	admin_menu_rearrangement: Standardmäßig deaktiviert
	Flexbox Container: Aktiv
	Upgrade Swiper Library: Standardmäßig deaktiviert
	Grid Container: Standardmäßig deaktiviert
	Default to New Theme Builder: Standardmäßig aktiviert
	Hello Theme Header &amp; Footer: Standardmäßig deaktiviert
	Editor Top Bar: Standardmäßig deaktiviert
	Startseiten: Standardmäßig aktiviert
	Nested Elements: Standardmäßig deaktiviert
	Lazy Load Background Images: Standardmäßig deaktiviert
	Page Transitions: Standardmäßig aktiviert
	Notes: Standardmäßig aktiviert
	Loop: Standardmäßig aktiviert
	Form Submissions: Standardmäßig aktiviert
	Scroll Snap: Standardmäßig aktiviert
	Menü: Standardmäßig deaktiviert

== Protokoll ==
	
Log: showing 20 of 332023-04-15 12:22:39 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.2',
  'to' => '3.12.1',
)]
2023-04-15 12:22:40 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.12.2',
)]
2023-04-15 12:22:41 [info] elementor::elementor_updater Started 
2023-04-15 12:22:41 [info] Elementor/Upgrades - _on_each_version Start  
2023-04-15 12:22:41 [info] Elementor/Upgrades - _on_each_version Finished 
2023-04-15 12:22:41 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.2',
  'to' => '3.12.1',
)]
2023-04-15 12:22:42 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.2',
  'to' => '3.12.1',
)]
2023-04-15 12:22:42 [info] elementor-pro::elementor_pro_updater Started 
2023-04-15 12:22:42 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-04-15 12:22:42 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-04-15 12:22:42 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.12.2',
)]
2023-05-18 11:21:26 [info] elementor::elementor_updater Started 
2023-05-18 11:21:26 [info] Elementor/Upgrades - _on_each_version Start  
2023-05-18 11:21:26 [info] Elementor/Upgrades - _on_each_version Finished 
2023-05-18 11:21:26 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.1',
  'to' => '3.13.2',
)]
2023-05-28 11:27:46 [info] elementor::elementor_updater Started 
2023-05-28 11:27:46 [info] Elementor/Upgrades - _on_each_version Start  
2023-05-28 11:27:46 [info] Elementor/Upgrades - _on_each_version Finished 
2023-05-28 11:27:46 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.2',
  'to' => '3.13.3',
)]
2023-05-28 11:27:46 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.2',
  'to' => '3.13.3',
)]

JS: showing 4 of 4JS: 2022-11-24 07:08:00 [error X 1][https://praxisfischer-mm.de/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.7.8:2:30926] elementor.settings.page is undefined 
JS: 2023-04-15 11:30:21 [error X 1][https://praxisfischer-mm.de/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.12.1:3:1081265] $ is null 
JS: 2023-05-18 11:28:30 [error X 1][https://praxisfischer-mm.de/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.13.2:3:916296] $e.routes.getHistory(...).reverse()[0] is undefined 
JS: 2023-05-19 16:13:05 [error X 1][https://praxisfischer-mm.de/wp-content/plugins/elementor/assets/js/common.min.js?ver=3.13.2:3:75804] C is undefined 

PHP: showing 6 of 6PHP: 2023-03-23 19:34:57 [notice X 2][/var/www/web22643449/html/wp-content/plugins/elementor-pro/modules/forms/classes/form-record.php::179] Undefined index: referrer [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-15 18:27:15 [error X 1][/var/www/web22643449/html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::295] Uncaught Error: Call to a member function update_meta() on bool in /var/www/web22643449/html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:295
Stack trace:
#0 /var/www/web22643449/html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(168): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /var/www/web22643449/html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /var/www/web22643449/html/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module-&gt;handle_ajax_request(&#039;&#039;)
#4 /var/www/web22643449/html/wp-includes/class-wp-hook.php(331): WP_Hook-&gt;apply_filters(&#039;&#039;, Array)
#5 /var/www/web22643449/h [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-19 14:18:48 [error X 3][/var/www/vhosts/h119451.web69.alfahosting-server.de/html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::295] Uncaught Error: Call to a member function update_meta() on bool in /var/www/vhosts/h119451.web69.alfahosting-server.de/html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:295
Stack trace:
#0 /var/www/vhosts/h119451.web69.alfahosting-server.de/html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(168): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /var/www/vhosts/h119451.web69.alfahosting-server.de/html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /var/www/vhosts/h119451.web69.alfahosting-server.de/html/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module-&gt;handle_ajax_request(&#039;&#039;)
 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-20 18:27:07 [notice X 2][/var/www/vhosts/h119451.web69.alfahosting-server.de/html/wp-content/plugins/elementor/modules/history/revisions-manager.php::363] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-26 16:43:40 [notice X 1][/var/www/vhosts/h119451.web69.alfahosting-server.de/html/wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-28 12:58:44 [notice X 1][/var/www/vhosts/h119451.web69.alfahosting-server.de/html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Die Kompatibilität ist nicht angegeben

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello, @andishanti!

Thank you for submitting your issue! 🙏 

Can you please confirm what Operating System and Browser versions are you using? 

Best regards

**Comment by andishanti** [comment]
> Hello, @andishanti!
> 
> Thank you for submitting your issue! 🙏
> 
> Can you please confirm what Operating System and Browser versions are you using?
> 
> Best regards

Hi,

I use Firefox 113.0.2 (64-Bit) and Chorme (Version 113.0.5672.127) (32-bit) with Windows 11.

Edition	Windows 11 Home
Version	22H2
Betriebssystembuild	22621.1778
Leistung	Windows Feature Experience Pack 1000.22642.1000.0

**Comment by andishanti** [comment]
@nicholaszein: Hi, any update? Is the feedback enough?

**Comment by andishanti** [comment]
@nicholaszein : Hi, issue still appears. any update?
