### ISSUE TITLE
Filter elementor/editor/localize_settings not fired upon switching to header/footer

### ISSUE THREAD

**Issue by iJorji** [elementor/elementor#22603]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

The filter '_elementor/editor/localize_settings_' isn't fired upon switching between a page and a header/footer.

### Steps to reproduce

1) For example, set the 'button' widget to hidden with the '_elementor/editor/localize_settings_' filter. 
```
function manage_widgets($settings): array {

        $settings['initial_document']['widgets']['button']['show_in_panel'] = false;
        return $settings;
}
add_filter('elementor/editor/localize_settings', 'manage_widgets');
```
2) Open a page in the Elementor editor
3) See that the button element is hidden
4) Switch to a header of footer
5) Button element is visible again

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.21.4
	MySQL version: mariadb.org binary distribution v10.4.29
	PHP Version: 8.0.28
	PHP Memory Limit: 256M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2.2
	Site URL: http://elementor.websiteretraite.nl
	Home URL: http://elementor.websiteretraite.nl
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: support@sysplatform.nl
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.12.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.12.3
		Author: Elementor.com

	Localize settings test
		Version: 1.0.0
		Author: Jordi

== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Editor Top Bar: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Menu: Inactive by default

== Log ==
	
PHP: showing 4 of 4PHP: 2023-05-19 11:48:21 [error X 3][/home/runcloud/webapps/elementor/wp-content/plugins/elementor-test/elementor-test.php::13] syntax error, unexpected token "public", expecting end of file [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-19 11:48:48 [error X 1][/home/runcloud/webapps/elementor/wp-content/plugins/elementor-test/elementor-test.php::24] Uncaught Error: Using $this when not in object context in /home/runcloud/webapps/elementor/wp-content/plugins/elementor-test/elementor-test.php:24
Stack trace:
#0 /home/runcloud/webapps/elementor/wp-admin/includes/plugin.php(2314): include_once()
#1 /home/runcloud/webapps/elementor/wp-admin/includes/plugin.php(661): plugin_sandbox_scrape()
#2 /home/runcloud/webapps/elementor/wp-admin/plugins.php(58): activate_plugin()
#3 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-19 11:48:48 [error X 2][/home/runcloud/webapps/elementor/wp-content/plugins/elementor-test/elementor-test.php::24] Uncaught Error: Using $this when not in object context in /home/runcloud/webapps/elementor/wp-content/plugins/elementor-test/elementor-test.php:24
Stack trace:
#0 /home/runcloud/webapps/elementor/wp-admin/includes/plugin.php(2314): include_once()
#1 /home/runcloud/webapps/elementor/wp-admin/plugins.php(192): plugin_sandbox_scrape()
#2 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-19 11:50:34 [warning X 5][/home/runcloud/webapps/elementor/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Incompatible

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @iJorji! 

Thank you for submitting your issue! 🙏 

Please allow us some time to investigate it, and get back to you with our findings. 🧐 

Best regards

**Comment by mikewww19** [comment]
Hey there,

Have you guys got any updates on this issue?
We'd love to hear back from y'all on this :)
