### ISSUE TITLE
⛔ 🐞 Bug Report: Loop Grid Pagination does not work with ACF Custom Post Types inside Archive Templates

### ISSUE THREAD

**Issue by sanholo177** [elementor/elementor#22630]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When using Loop Grid to display ACF Custom Post Types on a Custom Archive, the pagination does not work. If you select the Pagination option as a Numbers and go to other pages, a 404 error is returned. 

Example: yourdomain.com/projects/page/2/ - 404 Error

/projects/ is a Elementor Archive - Display Condition =>Categories =>Projects
/page/2/ - Loop Grid Pagination

### Steps to reproduce

1) Create a New Post Type in ACF - Projects
2) Use Category, Type as Taxonomies
3) Go To Projects and Add a New Post in Projects. Create at least 10 new dummy posts.
4) Go to Elementor Theme Builder and create a new Archive Template
5) Add a Loop Grid. 
6) Create a Loop Grid Template
7) Set Number of Post to Display as 5
8) Set any pagination type (Numbers, Infinity Scroll, etc)
9)Set the Display Condition to Include =>Categories=>Projects. (There are no option to Select any other ACF related Page Type or Post Type)
10)Publish the Archive
11)Preview the Archive Page and the issue is replicated

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.57 (Debian)
	MySQL version: mariadb.org binary distribution v10.4.20
	PHP Version: 8.1.18
	PHP Memory Limit: 256M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 200M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2.2
	Site URL: 
	Home URL: 
	WP Multisite: No
	Max Upload Size: 200 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%category%/%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: [REDACTED]
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.7.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36

== Active Plugins ==
	ACF Photo Gallery Field
		Version: 1.9
		Author: Navneil Naicker

	Advanced Custom Fields
		Version: 6.1.6
		Author: WP Engine

	Elementor
		Version: 3.13.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.13.2
		Author: Elementor.com

	MalCare WordPress Security Plugin - Malware Scanner, Cleaner, Security Firewall
		Version: 5.09
		Author: MalCare Security

	Rank Math SEO
		Version: 1.0.115
		Author: Rank Math

	Sticky Header Effects for Elementor
		Version: 1.6.5
		Author: Rwattner

	Unlimited Elements for Elementor (Premium)
		Version: 1.5.64
		Author: Unlimited Elements

	WP-Optimize - Clean, Compress, Cache
		Version: 3.2.15
		Author: David Anderson, Ruhani Rabin, Team Updraft


== Must-Use Plugins ==
	Object Cache Pro (MU)
		Version: 1.18.0
		Author: Rhubarb Group


== Features ==
	Custom Fonts: 1
	Custom Icons: 0

== Integrations ==
	
	google_maps: Active
	recaptcha_v3: Active


== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active
	Grid Container: Active
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Editor Top Bar: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Active
	Lazy Load Background Images: Inactive
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active
	Form Submissions: Active
	Scroll Snap: Active by default
	Menu: Active


== Log ==
	
JS: showing 19 of 19JS: 2023-05-18 07:39:11 [error X 18][https://wordpress-890000-3240324.cloudwaysapps.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.13.2:3:795450] Cannot read properties of undefined (reading 'localized') 
JS: 2023-05-18 07:39:16 [error X 3][https://wordpress-890000-3240324.cloudwaysapps.com/wp-includes/js/jquery/jquery.min.js?ver=3.6.4:2:40999] Cannot create property 'guid' on string 'c127631containersticky' 
JS: 2023-05-18 07:39:32 [error X 4][https://wordpress-890000-3240324.cloudwaysapps.com/wp-includes/js/jquery/jquery.min.js?ver=3.6.4:2:40999] Cannot create property 'guid' on string 'c131075widgetsticky' 
JS: 2023-05-18 10:58:44 [error X 3][https://wordpress-890000-3240324.cloudwaysapps.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.13.2:3:794943] Cannot read properties of undefined (reading 'toLowerCase') 
JS: 2023-05-25 04:49:51 [error X 44][https://wordpress-890000-3240324.cloudwaysapps.com/wp-includes/js/jquery/jquery.min.js?ver=3.6.4:2:40999] Cannot create property 'guid' on string 'c27652widgetsticky' 
JS: 2023-05-25 05:04:08 [error X 136][https://wordpress-890000-3240324.cloudwaysapps.com/wp-includes/js/jquery/jquery.min.js?ver=3.6.4:2:40999] Cannot create property 'guid' on string 'c28882widgetsticky' 
JS: 2023-05-25 05:04:19 [error X 5][https://wordpress-890000-3240324.cloudwaysapps.com/wp-includes/js/jquery/jquery.min.js?ver=3.6.4:2:40999] Cannot create property 'guid' on string 'c31492widgetsticky' 
JS: 2023-05-25 05:26:47 [error X 1][https://wordpress-890000-3240324.cloudwaysapps.com/wp-includes/js/jquery/jquery.min.js?ver=3.6.4:2:40999] Cannot create property 'guid' on string 'c41643containersticky' 
JS: 2023-05-25 05:26:49 [error X 25][https://wordpress-890000-3240324.cloudwaysapps.com/wp-includes/js/jquery/jquery.min.js?ver=3.6.4:2:40999] Cannot create property 'guid' on string 'c43182containersticky' 
JS: 2023-05-25 05:26:52 [error X 135][https://wordpress-890000-3240324.cloudwaysapps.com/wp-includes/js/jquery/jquery.min.js?ver=3.6.4:2:40999] Cannot create property 'guid' on string 'c45102widgetsticky' 
JS: 2023-05-25 05:26:57 [error X 25][https://wordpress-890000-3240324.cloudwaysapps.com/wp-includes/js/jquery/jquery.min.js?ver=3.6.4:2:40999] Cannot create property 'guid' on string 'c46769widgetsticky' 
JS: 2023-05-25 05:27:43 [error X 20][https://wordpress-890000-3240324.cloudwaysapps.com/wp-includes/js/jquery/jquery.min.js?ver=3.6.4:2:40999] Cannot create property 'guid' on string 'c17755containersticky' 
JS: 2023-05-25 05:33:21 [error X 1][https://wordpress-890000-3240324.cloudwaysapps.com/wp-includes/js/jquery/jquery.min.js?ver=3.6.4:2:40999] Cannot create property 'guid' on string 'c57194widgetsticky' 
JS: 2023-05-25 05:34:28 [error X 175][https://wordpress-890000-3240324.cloudwaysapps.com/wp-includes/js/jquery/jquery.min.js?ver=3.6.4:2:40999] Cannot create property 'guid' on string 'c59876widgetsticky' 
JS: 2023-05-25 05:36:00 [error X 6][https://wordpress-890000-3240324.cloudwaysapps.com/wp-includes/js/jquery/jquery.min.js?ver=3.6.4:2:40999] Cannot create property 'guid' on string 'c67010widgetsticky' 
JS: 2023-05-25 05:37:37 [error X 19][https://wordpress-890000-3240324.cloudwaysapps.com/wp-includes/js/jquery/jquery.min.js?ver=3.6.4:2:40999] Cannot create property 'guid' on string 'c71986widgetsticky' 
JS: 2023-05-25 07:20:24 [error X 146][https://wordpress-890000-3240324.cloudwaysapps.com/wp-includes/js/jquery/jquery.min.js?ver=3.6.4:2:33929] Maximum call stack size exceeded 
JS: 2023-05-29 02:08:05 [error X 8][https://wordpress-890000-3240324.cloudwaysapps.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.13.3:3:916308] Cannot read properties of undefined (reading 'route') 
JS: 2023-05-29 02:11:20 [error X 3][https://wordpress-890000-3240324.cloudwaysapps.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.13.3:3:634710] Cannot read properties of undefined (reading 'isDesignable') 

PHP: showing 8 of 8PHP: 2023-05-23 01:21:10 [warning X 17][/home/890000.cloudwaysapps.com/ssfmfwqchq/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-23 01:21:10 [warning X 65][/home/890000.cloudwaysapps.com/ssfmfwqchq/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key "condition_type" [array (
  'trace' => '
#0: /home/890000.cloudwaysapps.com/ssfmfwqchq/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /home/890000.cloudwaysapps.com/ssfmfwqchq/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /home/890000.cloudwaysapps.com/ssfmfwqchq/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /home/890000.cloudwaysapps.com/ssfmfwqchq/public_html/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2023-05-24 00:52:04 [warning X 10][/home/890000.cloudwaysapps.com/ssfmfwqchq/public_html/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-image.php::40] Undefined array key 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-24 08:29:29 [warning X 6][/home/890000.cloudwaysapps.com/ssfmfwqchq/public_html/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/fonts-manager.php::252] Undefined array key "editor_post_id" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-24 09:47:15 [error X 3][/home/890000.cloudwaysapps.com/ssfmfwqchq/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::304] Uncaught Error: Call to a member function update_meta() on null in /home/890000.cloudwaysapps.com/ssfmfwqchq/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:304
Stack trace:
#0 /home/890000.cloudwaysapps.com/ssfmfwqchq/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(177): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions()
#2 /home/890000.cloudwaysapps.com/ssfmfwqchq/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func()
#3 /home/890000.cloudwaysapps.com/ssfmfwqchq/public_html/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#4 /home/890000.cloudwaysapps.com/ssfmfwqchq/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#5 /home/890000.cloudwaysapps.com/ssfmfwqchq/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#6 /home/890000.cloudwaysapps.com/ssfmfwqchq/public_html/wp-admin/admin-ajax.php(188): do_action()
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-25 01:10:57 [warning X 6][/home/890000.cloudwaysapps.com/ssfmfwqchq/public_html/wp-content/plugins/elementor/modules/history/revisions-manager.php::363] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-29 06:24:01 [warning X 4][/home/890000.cloudwaysapps.com/ssfmfwqchq/public_html/wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-31 07:40:54 [error X 1][/home/890000.cloudwaysapps.com/ssfmfwqchq/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php::1112] Uncaught TypeError: Elementor\TemplateLibrary\Source_Local::on_save_post(): Argument #2 ($post) must be of type WP_Post, null given, called in /home/890000.cloudwaysapps.com/ssfmfwqchq/public_html/wp-includes/class-wp-hook.php on line 310 and defined in /home/890000.cloudwaysapps.com/ssfmfwqchq/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php:1112
Stack trace:
#0 /home/890000.cloudwaysapps.com/ssfmfwqchq/public_html/wp-includes/class-wp-hook.php(310): Elementor\TemplateLibrary\Source_Local->on_save_post()
#1 /home/890000.cloudwaysapps.com/ssfmfwqchq/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#2 /home/890000.cloudwaysapps.com/ssfmfwqchq/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#3 /home/890000.cloudwaysapps.com/ssfmfwqchq/public_html/wp-includes/post.php(4715): do_action()
#4 /home/890000.cloudwaysapps.com/ssfmfwqchq/public_html/wp-includes/post.php(4817): wp_insert_post()
#5 /home/890000.cloudwaysapps.com/ssfmfwqchq/public_html/wp-content/plugins/elementor/includes/db.php(235): wp_update_post()
#6 /home/890000.cloudwaysapps.com/ssfmfwqchq/public_html/wp-content/plugins/elementor/core/base/document.php(1272): Elementor\DB->save_plain_text()
#7 /home/890000.cloudwaysapps.com/ssfmfwqchq/public_html/wp-content/plugins/elementor/core/base/document.php(753): Elementor\Core\Base\Document->save_elements()
#8 /home/890000.cloudwaysapps.com/ssfmfwqchq/public_html/wp-content/plugins/elementor/core/documents-manager.php(545): Elementor\Core\Base\Document->save()
#9 [internal function]: Elementor\Core\Documents_Manager->ajax_save()
#10 /home/890000.cloudwaysapps.com/ssfmfwqchq/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func()
#11 /home/890000.cloudwaysapps.com/ssfmfwqchq/public_html/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#12 /home/890000.cloudwaysapps.com/ssfmfwqchq/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#13 /home/890000.cloudwaysapps.com/ssfmfwqchq/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#14 /home/890000.cloudwaysapps.com/ssfmfwqchq/public_html/wp-admin/admin-ajax.php(188): do_action()
#15 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 15 of 152023-05-25 00:48:04 [info] elementor::elementor_updater Started 
2023-05-25 00:48:04 [info] Elementor/Upgrades - _on_each_version Start  
2023-05-25 00:48:04 [info] Elementor/Upgrades - _on_each_version Finished 
2023-05-25 00:48:04 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.2',
  'to' => '3.13.3',
)]
2023-05-25 00:48:04 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.2',
  'to' => '3.13.3',
)]
2023-05-25 00:48:17 [info] elementor-pro::elementor_pro_updater Started 
2023-05-25 00:48:17 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-05-25 00:48:17 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-05-25 00:48:17 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.13.1',
  'to' => '3.13.2',
)]
2023-05-25 00:48:17 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.13.1',
  'to' => '3.13.2',
)]
2023-05-29 06:22:49 [info] elementor::elementor_updater Started 
2023-05-29 06:22:49 [info] Elementor/Upgrades - _on_each_version Start  
2023-05-29 06:22:49 [info] Elementor/Upgrades - _on_each_version Finished 
2023-05-29 06:22:49 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.3',
  'to' => '3.13.4',
)]
2023-05-29 06:22:49 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.3',
  'to' => '3.13.4',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	Sticky Header Effects for Elementor: Compatibility not specified
	Unlimited Elements for Elementor (Premium): Compatibility not specified

== Elementor Pro - Compatibility Tag ==
	

				

````

</details>

**Comment by nicholaszein** [comment]
Hello @sanholo177,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
When building Archive Templates with the Loop Builder, please always set the Query to "Current Query", and configure the number of posts in your `Dashboard` > `Settings` > `Reading` page. Due to WordPress limitations, you can't set custom queries (which include the number of posts) in Archive templates. The pagination will only work if you follow these steps.

### 👍 For now, that's all we can help with. 

Kind regards
