### ISSUE TITLE
Trying to get property 'post_type' of non-object

### ISSUE THREAD

**Issue by confile** [elementor/elementor#22654]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When I update a page I get the following notice: 

Notice: Trying to get property 'post_type' of non-object in /kunden/365999_20251/webseiten/michaelgorski.net/wp-dmg-www-v4/wp-content/plugins/wordpress-seo/src/integrations/third-party/elementor.php on line 151

### Steps to reproduce

Update a page

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: mariadb.org binary distribution v10.4.28
	PHP Version: 7.4.33
	PHP Memory Limit: 128M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 75M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2.2
	Site URL: https://www.michaelgorski.net
	Home URL: https://www.michaelgorski.net
	WP Multisite: No
	Max Upload Size: 75 MB
	Memory limit: 512M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Europe/Berlin
	Admin Email: mg@michaelgorski.net
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.7.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36

== Active Plugins ==
	All In One WP Security
		Version: 5.1.9
		Author: All In One WP Security & Firewall Team

	BlogLentor for Elementor
		Version: 1.0.8
		Author: wpsurface

	Borlabs Cookie - Cookie Opt-in
		Version: 2.2.63
		Author: Borlabs GmbH

	Code Snippets
		Version: 3.4.0
		Author: Code Snippets Pro

	Docs Viewer Add-On for WP Job Openings
		Version: 1.0
		Author: AWSM Innovations

	Duplicator Pro
		Version: 4.5.11.1
		Author: Duplicator

	Elementor
		Version: 3.13.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.13.2
		Author: Elementor.com

	Embed Plus YouTube WordPress Plugin
		Version: 14.1.6.2
		Author: Embed Plus YouTube Plugin Team

	Enable Media Replace
		Version: 4.1.2
		Author: ShortPixel

	Error Log Monitor
		Version: 1.7.6
		Author: Janis Elsts

	Instant Indexing
		Version: 1.1.17
		Author: Rank Math

	Meta Tag Manager
		Version: 3.0.2
		Author: Pixelite

	Page Generator Pro
		Version: 4.2.2
		Author: WP Zinc

	PDF Block
		Version: 1.1.0
		Author: henryholtgeerts

	Resize Image After Upload
		Version: 1.8.6
		Author: ShortPixel

	Seriously Simple Podcasting
		Version: 2.21.0
		Author: Castos

	Site Kit by Google
		Version: 1.101.0
		Author: Google

	Sticky Side Buttons
		Version: 1.0.9
		Author: Maeve Lander

	Tf Youtube Widgets Addon For Elementor
		Version: 1.0.2
		Author: Themesflat

	Two Factor Authentication
		Version: 1.14.16
		Author: David Anderson, original plugin by Oskar Hane and enhanced by Dee Nutbourne

	User Role Editor
		Version: 4.63.3
		Author: Vladimir Garagulya

	WP Activity Log
		Version: 4.5.2
		Author: WP White Security

	WP Activity Log for Yoast SEO
		Version: 1.3.1
		Author: WP White Security

	WP Anti-Clickjack
		Version: 1.7.6
		Author: Andy Feliciotti

	WP Armour - Honeypot Anti Spam
		Version: 2.1.4
		Author: Dnesscarkey

	WP Htaccess Editor
		Version: 1.71
		Author: WebFactory Ltd

	WP Job Openings
		Version: 3.3.3
		Author: AWSM Innovations

	WP Mail SMTP
		Version: 3.8.0
		Author: WP Mail SMTP

	WP Rocket
		Version: 3.13.3
		Author: WP Media

	WP Rocket | Change Parameters
		Version: 
		Author: WP Rocket Support Team

	WPS Hide Login
		Version: 1.9.8
		Author: WPServeur, NicolasKulka, wpformation

	Yoast Duplicate Post
		Version: 4.5
		Author: Enrico Battocchi & Team Yoast

	Yoast SEO
		Version: 20.8
		Author: Team Yoast

	Yoast SEO: Video
		Version: 14.7
		Author: Team Yoast

	Yoast SEO Premium
		Version: 20.8
		Author: Team Yoast

	Yoast Test Helper
		Version: 1.17
		Author: Team Yoast

== Must-Use Plugins ==
	Page Generator Pro: Performance Addon
		Version: 2.9.3
		Author: WP Zinc

== Features ==
	Custom Fonts: 2
	Custom Icons: 0

== Integrations ==
	

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Upgrade Swiper Library: Inactive by default
	Grid Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Editor Top Bar: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Menu: Inactive by default

== Log ==
	
Log: showing 20 of 342023-05-11 22:41:57 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-05-11 22:41:57 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-05-11 22:41:57 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.13.0',
  'to' => '3.13.1',
)]
2023-05-11 22:41:57 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.13.0',
  'to' => '3.13.1',
)]
2023-05-23 21:10:59 [info] elementor::elementor_updater Started 
2023-05-23 21:10:59 [info] Elementor/Upgrades - _on_each_version Start  
2023-05-23 21:10:59 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.2',
  'to' => '3.13.3',
)]
2023-05-23 21:10:59 [info] Elementor/Upgrades - _on_each_version Finished 
2023-05-23 21:10:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.2',
  'to' => '3.13.3',
)]
2023-05-23 21:11:16 [info] elementor-pro::elementor_pro_updater Started 
2023-05-23 21:11:16 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-05-23 21:11:16 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-05-23 21:11:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.13.1',
  'to' => '3.13.2',
)]
2023-05-23 21:11:16 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.13.1',
  'to' => '3.13.2',
)]
2023-05-28 19:33:36 [info] elementor::elementor_updater Started 
2023-05-28 19:33:36 [info] Elementor/Upgrades - _on_each_version Start  
2023-05-28 19:33:36 [info] Elementor/Upgrades - _on_each_version Finished 
2023-05-28 19:33:36 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.3',
  'to' => '3.13.4',
)]
2023-05-28 19:33:36 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.3',
  'to' => '3.13.4',
)]
2023-05-28 19:33:37 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.3',
  'to' => '3.13.4',
)]

JS: showing 4 of 4JS: 2023-05-11 17:05:17 [error X 1][https://www.michaelgorski.net/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.13.1:2:8297] Cannot read properties of undefined (reading 'attributes') 
JS: 2023-05-28 12:27:41 [error X 16][https://www.michaelgorski.net/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.13.3:3:311291] Cannot read properties of undefined (reading 'menu') 
JS: 2023-05-29 06:28:33 [error X 12][https://www.michaelgorski.net/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.13.4:3:1097282] Cannot read properties of null (reading 'getBoundingClientRect') 
JS: 2023-05-29 11:45:27 [error X 4][https://www.michaelgorski.net/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.13.4:3:634710] Cannot read properties of undefined (reading 'isDesignable') 

PHP: showing 4 of 4PHP: 2023-05-24 19:07:26 [notice X 49][/kunden/365999_20251/webseiten/michaelgorski.net/wp-dmg-www-v4/wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-25 00:05:31 [error X 1][/kunden/365999_20251/webseiten/michaelgorski.net/wp-dmg-www-v4/wp-content/plugins/elementor/includes/template-library/sources/local.php::1108] Uncaught TypeError: Argument 2 passed to Elementor\TemplateLibrary\Source_Local::on_save_post() must be an instance of WP_Post, instance of stdClass given, called in /kunden/365999_20251/webseiten/michaelgorski.net/wp-dmg-www-v4/wp-includes/class-wp-hook.php on line 310 and defined in /kunden/365999_20251/webseiten/michaelgorski.net/wp-dmg-www-v4/wp-content/plugins/elementor/includes/template-library/sources/local.php:1108
Stack trace:
#0 /kunden/365999_20251/webseiten/michaelgorski.net/wp-dmg-www-v4/wp-includes/class-wp-hook.php(310): Elementor\TemplateLibrary\Source_Local->on_save_post()
#1 /kunden/365999_20251/webseiten/michaelgorski.net/wp-dmg-www-v4/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#2 /kunden/365999_20251/webseiten/michaelgorski.net/wp-dmg-www-v4/wp-includes/plugin.php(517): WP_Hook->do_action()
#3 /kunden/365999_20251/webseiten/michaelgorski.net/wp-dmg-www-v4/wp-includes/post.php(4715): do_action()
#4 /kunden/365999_20251/webseiten/michaelgorski.net/wp-dmg-www-v4/wp-includes/ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-28 19:40:12 [notice X 6][/kunden/365999_20251/webseiten/michaelgorski.net/wp-dmg-www-v4/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-28 21:37:03 [notice X 6][/kunden/365999_20251/webseiten/michaelgorski.net/wp-dmg-www-v4/wp-content/plugins/elementor-pro/core/utils.php::373] Undefined index: name [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	BlogLentor for Elementor: Compatibility not specified
	Elementor Pro: Compatibility not specified
	Tf Youtube Widgets Addon For Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @confile! 

Thank you for submitting your issue! 🙏 

This seems like a known issue from Yoast SEO, and they seem to be working on a fix right as we speak. Please keep an eye on their GitHub [issue](https://github.com/Yoast/wordpress-seo/issues/20162) for more information.

Since this is not a bug caused by Elementor specifically, I am closing this issue.

Kind regards
