### ISSUE TITLE
The units are always on PX even though they are not actually PX

### ISSUE THREAD

**Issue by Reialesa** [elementor/elementor#22793]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

The units in Elementor, no matter the widget, are set to PX EVEN if they are NOT set to px. If you set a new unit, it often doesn't change in the dropdown/selection - it does change the unit, though. Sometimes, even though it works and functions as the correct unit, when you type in a new value, it begins functioning like pixels.

Even if it does go to other units, when you re-open the widget/container, it's set to PX again. It's pretty confusing.

### Steps to reproduce

Open a widget/container and set units to something other than px. Re-open if needed.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

[system-info-wearewizardsofwebcraft.com-16-06-2023.txt](https://github.com/elementor/elementor/files/11764305/system-info-wearewizardsofwebcraft.com-16-06-2023.txt)

**Comment by nicholaszein** [comment]
Hello @Reialesa,

thank you for your report! 🙏 

### ⛔ While reviewing your issue, we couldn't find a way to reproduce it. The units remain the same after selecting them.

Can you please share more insights on what you are experiencing? I've recorded a video testing the container units, and as you can see, everything is working as expected.


https://github.com/elementor/elementor/assets/113993460/2f7215eb-72cf-4786-9e62-1b8fae94df46



----

Alternatively, you can always use the option to **Save as default** available when you `right-click` an element. All you have to do is to configure your elements the way you want them to be styled, and then `right-click` them to **Save as default**. This will save the option you've set up for each element, so you don't need to do it again later. 

One thing to note, this will not work with containers added from the preview by clicking the pink plus (➕) icon. These containers are preset depending on the options you choose, and they will not use the default settings you defined. It only works for containers added from the widget panel. 

See the video below for an example of the **Save as default** feature.



https://github.com/elementor/elementor/assets/113993460/38af4103-547a-4f43-bdcc-7d703d2251cc


----

Please, explain in more detail what is the issue you're experiencing, and if possible share a screen recording. You can use a free service like [Loom](https://www.loom.com/) to do that. This will help us understand better what is the issue.

Best regards

**Comment by hein-obox** [comment]
@nicholaszein I think I have the same problem, e.g. when I edit the Loop Grid styling of the template: https://watch.screencastify.com/v/cxbRrssZuVckRueAkghH.

					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.57 (Debian)
	MySQL version: mariadb.org binary distribution v10.4.20
	PHP Version: 7.4.33
	PHP Memory Limit: 512M
	PHP Max Input Vars: 2500
	PHP Max Post Size: 10M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2.2
	Site URL: https://smarting2023.abanganimedia.co.za
	Home URL: https://smarting2023.abanganimedia.co.za
	WP Multisite: No
	Max Upload Size: 10 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /artikel/%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: heinvanvlastuin@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Abangani Media
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.7.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 6.1.6
		Author: WP Engine

	Classic Editor
		Version: 1.6.3
		Author: WordPress Contributors

	Code Snippets
		Version: 3.4.0
		Author: Code Snippets Pro

	Custom Post Type UI
		Version: 1.13.5
		Author: WebDevStudios

	Elementor
		Version: 3.13.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.13.1
		Author: Elementor.com

	Essential Addons for Elementor
		Version: 5.7.2
		Author: WPDeveloper

	File Manager Advanced
		Version: 5.0.4
		Author: modalweb

	Gravity Forms
		Version: 2.7.8
		Author: Gravity Forms

	Gravity Forms Zero Spam
		Version: 1.4
		Author: GravityKit

	iframe
		Version: 4.5
		Author: webvitaly

	JWT Authentication for WP-API
		Version: 1.3.2
		Author: Enrique Chavez

	One User Avatar
		Version: 2.3.9
		Author: One Designs

	PublishPress Capabilities
		Version: 2.8.1
		Author: PublishPress

	Relevanssi
		Version: 4.20.0
		Author: Mikko Saari

	Safe SVG
		Version: 2.1.1
		Author: 10up

	WP Login Form
		Version: 1.0.10
		Author: naa986

	Yoast Duplicate Post
		Version: 4.5
		Author: Enrico Battocchi & Team Yoast

	Yoast SEO
		Version: 20.7
		Author: Team Yoast


== Must-Use Plugins ==
	Object Cache Pro (MU)
		Version: 1.18.2
		Author: Rhubarb Group


== Elements Usage ==
	
	archive : 2
		breadcrumbs : 2
		container : 11
		divider : 1
		heading : 1
		image : 1
		loop-grid : 2
		share-buttons : 1
		text-editor : 1
	container : 6
		breadcrumbs : 2
		button : 1
		container : 10
		heading : 1
		image : 2
		post-info : 1
		share-buttons : 1
		shortcode : 1
		text-editor : 4
		video : 1
	footer : 1
		container : 10
		divider : 1
		heading : 2
		nav-menu : 2
		shortcode : 1
		social-icons : 1
		text-editor : 5
		theme-site-logo : 1
	header : 1
		container : 3
		divider : 1
		icon : 1
		nav-menu : 3
		search-form : 1
		share-buttons : 1
		text-editor : 2
		theme-site-logo : 2
	widget : 0
		breadcrumbs : 1
		share-buttons : 1
	wp-page : 4
		breadcrumbs : 3
		button : 3
		container : 33
		divider : 1
		eael-gravity-form : 1
		heading : 5
		icon : 4
		image : 2
		loop-carousel : 1
		loop-grid : 7
		shortcode : 2
		text-editor : 11
		video : 3
	single-post : 2
		breadcrumbs : 2
		button : 3
		container : 34
		divider : 2
		heading : 5
		icon : 5
		icon-list : 1
		image : 4
		loop-grid : 4
		post-info : 3
		share-buttons : 2
		shortcode : 1
		text-editor : 11
		theme-post-content : 1
		theme-post-title : 2
	search-results : 1
		archive-posts : 1
		container : 1
		heading : 1
	loop-item : 12
		button : 3
		container : 25
		divider : 4
		icon : 1
		image : 1
		post-info : 19
		text-editor : 1
		theme-post-excerpt : 2
		theme-post-featured-image : 5
		theme-post-title : 11


== Settings ==
	
	cpt_support: post, page
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap


== Features ==
	Custom Fonts: 1
	Custom Icons: 2

== Integrations ==
	


== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Inactive by default
	Grid Container: Inactive by default
	Default to New Theme Builder: Active
	Hello Theme Header & Footer: Active
	Editor Top Bar: Inactive by default
	Landing Pages: Active
	Nested Elements: Active
	Lazy Load Background Images: Active
	Page Transitions: Active
	Notes: Active
	Loop: Active
	Form Submissions: Active
	Scroll Snap: Active
	Menu: Inactive by default


== Log ==
	
Log: showing 20 of 272023-05-01 11:20:09 [info] elementor::elementor_updater Started 
2023-05-01 11:20:09 [info] Elementor/Upgrades - _on_each_version Start  
2023-05-01 11:20:09 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.0-beta2',
  'to' => '3.12.2',
)]
2023-05-01 11:20:09 [info] Elementor/Upgrades - _on_each_version Finished 
2023-05-01 11:20:09 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.0-beta2',
  'to' => '3.12.2',
)]
2023-05-01 11:21:59 [info] elementor::elementor_updater Started 
2023-05-01 11:21:59 [info] Elementor/Upgrades - _on_each_version Start  
2023-05-01 11:21:59 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.2',
  'to' => '3.13.0-beta3',
)]
2023-05-01 11:21:59 [info] Elementor/Upgrades - _on_each_version Finished 
2023-05-01 11:21:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.2',
  'to' => '3.13.0-beta3',
)]
2023-05-19 17:32:39 [info] elementor::elementor_updater Started 
2023-05-19 17:32:39 [info] Elementor/Upgrades - _on_each_version Start  
2023-05-19 17:32:40 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.0-beta3',
  'to' => '3.13.2',
)]
2023-05-19 17:32:40 [info] Elementor/Upgrades - _on_each_version Finished 
2023-05-19 17:32:40 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.0-beta3',
  'to' => '3.13.2',
)]
2023-05-19 17:34:04 [info] elementor-pro::elementor_pro_updater Started 
2023-05-19 17:34:04 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-05-19 17:34:04 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-05-19 17:34:04 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.2',
  'to' => '3.13.1',
)]
2023-05-19 17:34:04 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.2',
  'to' => '3.13.1',
)]

JS: showing 4 of 4JS: 2023-02-24 07:54:01 [error X 1][https://smarting2023.abanganimedia.co.za/wp-content/plugins/elementor-pro/assets/js/loop-carousel.e7d573cc61a4613d5eaa.bundle.min.js:2:3355] Cannot read properties of undefined (reading 'params') 
JS: 2023-02-24 09:34:04 [error X 2][https://smarting2023.abanganimedia.co.za/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.11.2:3:300820] Cannot read properties of undefined (reading 'id') 
JS: 2023-04-07 16:29:47 [error X 1][https://smarting2023.abanganimedia.co.za/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.12.0-beta2:3:785268] Cannot read properties of undefined (reading 'toLowerCase') 
JS: 2023-05-01 12:22:58 [error X 3][https://smarting2023.abanganimedia.co.za/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.13.0-beta3:3:634706] Cannot read properties of undefined (reading 'isDesignable') 

PHP: showing 11 of 11PHP: 2023-02-24 08:22:40 [notice X 5][/home/579068.cloudwaysapps.com/whpmjudzdt/public_html/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php::33] Undefined offset: 0 [array (
  'trace' => '
#0: /home/579068.cloudwaysapps.com/whpmjudzdt/public_html/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php(33): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/579068.cloudwaysapps.com/whpmjudzdt/public_html/wp-content/plugins/elementor/core/dynamic-tags/tag.php(35): ElementorPro\Modules\DynamicTags\ACF\Tags\ACF_Text -> render()
#2: /home/579068.cloudwaysapps.com/whpmjudzdt/public_html/wp-content/plugins/elementor/core/dynamic-tags/manager.php(216): Elementor\Core\DynamicTags\Tag -> get_content()
#3: Elementor\Core\DynamicTags\Manager -> get_tag_data_content()
#4: /home/579068.cloudwaysapps.com/whpmjudzdt/public_html/wp-content/plugins/elementor/core/dynamic-tags/manager.php(109): class type call_user_func_array()
',
)]
PHP: 2023-02-24 08:22:40 [notice X 5][/home/579068.cloudwaysapps.com/whpmjudzdt/public_html/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php::33] Undefined offset: 1 [array (
  'trace' => '
#0: /home/579068.cloudwaysapps.com/whpmjudzdt/public_html/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php(33): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/579068.cloudwaysapps.com/whpmjudzdt/public_html/wp-content/plugins/elementor/core/dynamic-tags/tag.php(35): ElementorPro\Modules\DynamicTags\ACF\Tags\ACF_Text -> render()
#2: /home/579068.cloudwaysapps.com/whpmjudzdt/public_html/wp-content/plugins/elementor/core/dynamic-tags/manager.php(216): Elementor\Core\DynamicTags\Tag -> get_content()
#3: Elementor\Core\DynamicTags\Manager -> get_tag_data_content()
#4: /home/579068.cloudwaysapps.com/whpmjudzdt/public_html/wp-content/plugins/elementor/core/dynamic-tags/manager.php(109): class type call_user_func_array()
',
)]
PHP: 2023-03-01 08:09:11 [error X 10][/home/579068.cloudwaysapps.com/whpmjudzdt/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::295] Uncaught Error: Call to a member function update_meta() on bool in /home/579068.cloudwaysapps.com/whpmjudzdt/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:295
Stack trace:
#0 /home/579068.cloudwaysapps.com/whpmjudzdt/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(168): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions()
#2 /home/579068.cloudwaysapps.com/whpmjudzdt/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func()
#3 /home/579068.cloudwaysapps.com/whpmjudzdt/public_html/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#4 /home/579068.cloudwaysapps.com/whpmjudzdt/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#5 /home/579068.cloudwaysa [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-18 11:33:15 [notice X 51][/home/579068.cloudwaysapps.com/whpmjudzdt/public_html/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-image.php::59] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-24 18:05:50 [warning X 52][/home/579068.cloudwaysapps.com/whpmjudzdt/public_html/wp-content/plugins/elementor/core/files/file-types/svg.php::191] SimpleXMLElement::__construct():                                                                                ^ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-01 11:44:52 [notice X 12][/home/579068.cloudwaysapps.com/whpmjudzdt/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-10 09:54:50 [notice X 513][/home/579068.cloudwaysapps.com/whpmjudzdt/public_html/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php::33] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-10 09:54:57 [notice X 2][/home/579068.cloudwaysapps.com/whpmjudzdt/public_html/wp-content/plugins/elementor/core/page-assets/data-managers/font-icon-svg/font-awesome.php::50] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-19 17:35:23 [notice X 33][/home/579068.cloudwaysapps.com/whpmjudzdt/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined index: condition_type [array (
  'trace' => '
#0: /home/579068.cloudwaysapps.com/whpmjudzdt/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /home/579068.cloudwaysapps.com/whpmjudzdt/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /home/579068.cloudwaysapps.com/whpmjudzdt/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /home/579068.cloudwaysapps.com/whpmjudzdt/public_html/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2023-06-08 19:46:48 [notice X 2][/home/579068.cloudwaysapps.com/whpmjudzdt/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::171] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-06-09 07:00:16 [notice X 1][/home/579068.cloudwaysapps.com/whpmjudzdt/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined index: condition_type [array (
  'trace' => '
#0: /home/579068.cloudwaysapps.com/whpmjudzdt/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/579068.cloudwaysapps.com/whpmjudzdt/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(84): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /home/579068.cloudwaysapps.com/whpmjudzdt/public_html/wp-content/plugins/elementor/data/base/endpoint.php(166): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> update_item()
#3: /home/579068.cloudwaysapps.com/whpmjudzdt/public_html/wp-content/plugins/elementor/data/base/endpoint.php(307): Elementor\Data\Base\Endpoint -> base_callback()
#4: /home/579068.cloudwaysapps.com/whpmjudzdt/public_html/wp-includes/rest-api/class-wp-rest-server.php(1181): Elementor\Data\Base\Endpoint -> Elementor\Data\Base\{closure}()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	Essential Addons for Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by hitsgee** [comment]
I have experienced the same issue always defaulting to px for font size when I use em.

You can replicate by adding a title customise the font size for desktop to rem or em and then check mobile size it defaults to px even though it inherits from desktop.

**Comment by nicholaszein** [comment]
> @nicholaszein I think I have the same problem, e.g. when I edit the Loop Grid styling of the template: https://watch.screencastify.com/v/cxbRrssZuVckRueAkghH.
> 
> System Info

@hein-obox, please update Elementor to the latest version, and test it without any other plugin, especially if it's an add-on. I still can't reproduce this on my testing website. We need to rule out possible conflicts.

**Comment by nicholaszein** [comment]
> I have experienced the same issue always defaulting to px for font size when I use em.
> 
> You can replicate by adding a title customise the font size for desktop to rem or em and then check mobile size it defaults to px even though it inherits from desktop.

@hitsgee, this is actually the expected behavior. All controls, unless defined otherwise will always default to PX. As the unit, including responsive ones. What can't happen is when you set a value and the unit is wrong. When it's an inherited value it's not the same thing. I understand this is not ideal, and we might change this behavior in the future. We can’t say exactly when and if it'll be sorted out, but we kindly ask for your patience. Thanks for understanding! 😉

Best regards

**Comment by bombarda-rpd** [comment]
Hi Nicholas. I shared this issue on Facebook. It happens when you return to the editor page.
![Captura de ecrã 2024-10-30, às 12 11 47](https://github.com/user-attachments/assets/3f8700e3-2b89-42dd-8378-82fca550e8a8)
