### ISSUE TITLE
Their aren't any styles for the New Mega Menu Dropdown Indicator

### ISSUE THREAD

**Issue by erok415** [elementor/elementor#22791]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I've tried modifying every style to get the dropdown indicator to change size, color, or spacing between the indicator and the text.

### Steps to reproduce

1. Drag the new "Menu" onto a container.
2. Toggle the first menu item "Dropdown Content" to "On".
3. Go to the styles window and try to modify the Dropdown Indicator styles. You'll find that there aren't any styles for this feature.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.21.6
	MySQL version: MariaDB Server v10.4.25
	PHP Version: 7.4.30
	PHP Memory Limit: 256M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2
	Site URL: https://theme-kit-extole.pantheonsite.io
	Home URL: https://theme-kit-extole.pantheonsite.io
	WP Multisite: No
	Max Upload Size: 100 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /blog/%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: erik@mollyduggan.io
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 2.6.1.1680024010
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.7.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.13.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.13.2
		Author: Elementor.com

	Media Sync
		Version: 1.3.1
		Author: Erol Živina

	Pantheon Advanced Page Cache
		Version: 1.3.0
		Author: Pantheon

	Regenerate Thumbnails
		Version: 3.1.5
		Author: Alex Mills (Viper007Bond)

	WordPress Importer
		Version: 0.8.1
		Author: wordpressdotorg

	Yoast Duplicate Post
		Version: 4.5
		Author: Enrico Battocchi & Team Yoast

== Must-Use Plugins ==
	Pantheon MU Plugin Loader
		Version: 1.0
		Author: Pantheon Systems

== Elements Usage ==
	
	archive : 1
		archive-posts : 1
		container : 1
	container : 2
		button : 2
		container : 4
		heading : 2
		image : 1
		text-editor : 2
	footer : 2
		container : 24
		heading : 12
		icon-list : 12
		image : 2
		social-icons : 2
	header : 2
		button : 3
		container : 27
		heading : 21
		icon-box : 7
		icon-list : 2
		image : 4
		mega-menu : 1
		nav-menu : 2
		theme-site-logo : 1
	page : 3
		button : 35
		container : 33
		heading : 32
		text-editor : 8
	section : 1
		button : 2
		container : 2
		heading : 1
	wp-post : 2
		button : 9
		container : 24
		heading : 28
		html : 2
		image : 1
	wp-page : 13
		button : 73
		container : 334
		form : 1
		heading : 144
		icon : 22
		image : 62
		loop-grid : 12
		shortcode : 3
		text-editor : 78
		theme-post-excerpt : 6
		video : 7
	single-page : 1
		button : 1
		container : 13
		heading : 3
		image : 1
		loop-grid : 1
		post-info : 2
		share-buttons : 1
		theme-post-content : 1
		theme-post-featured-image : 1
		theme-post-title : 1
	loop-item : 7
		container : 30
		heading : 1
		icon : 5
		image : 4
		text-editor : 4
		theme-post-excerpt : 5
		theme-post-featured-image : 2
		theme-post-title : 7

== Settings ==
	
	cpt_support: post, page
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap

== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Inactive by default
	Grid Container: Active
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Editor Top Bar: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Active
	Lazy Load Background Images: Inactive by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Menu: Active

== Log ==
	
Log: showing 19 of 192023-05-09 20:55:22 [info] Elementor/Upgrades - _on_each_version Start  
2023-05-09 20:55:22 [info] Elementor/Upgrades - _on_each_version Finished 
2023-05-09 20:55:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.1',
  'to' => '3.13.1',
)]
2023-05-09 20:55:22 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.1',
  'to' => '3.13.1',
)]
2023-05-09 20:59:31 [info] elementor-pro::elementor_pro_updater Started 
2023-05-09 20:59:31 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-05-09 20:59:31 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-05-09 20:59:31 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.2',
  'to' => '3.13.0',
)]
2023-05-09 20:59:31 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.2',
  'to' => '3.13.0',
)]
2023-05-29 19:33:18 [info] elementor::elementor_updater Started 
2023-05-29 19:33:18 [info] Elementor/Upgrades - _on_each_version Start  
2023-05-29 19:33:19 [info] Elementor/Upgrades - _on_each_version Finished 
2023-05-29 19:33:19 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.1',
  'to' => '3.13.4',
)]
2023-05-29 19:33:19 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.1',
  'to' => '3.13.4',
)]
2023-05-29 19:33:48 [info] elementor-pro::elementor_pro_updater Started 
2023-05-29 19:33:48 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-05-29 19:33:48 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-05-29 19:33:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.13.0',
  'to' => '3.13.2',
)]
2023-05-29 19:33:49 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.13.0',
  'to' => '3.13.2',
)]

JS: showing 11 of 11JS: 2023-05-09 21:20:35 [error X 2][https://theme-kit-extole.pantheonsite.io/wp-content/plugins/elementor/assets/js/df16c9d56464dd4f0800.bundle.min.js:2:7826] Cannot read properties of null (reading 'dataset') 
JS: 2023-05-22 04:11:34 [error X 1][https://theme-kit-extole.pantheonsite.io/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.13.1:3:795450] Cannot read properties of undefined (reading 'localized') 
JS: 2023-05-25 20:30:59 [error X 1][https://theme-kit-extole.pantheonsite.io/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view1121") has already been destroyed and cannot be used. 
JS: 2023-05-29 18:33:04 [error X 1][https://theme-kit-extole.pantheonsite.io/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.13.1:3:794943] Cannot read properties of undefined (reading 'toLowerCase') 
JS: 2023-05-29 22:55:03 [error X 4][https://theme-kit-extole.pantheonsite.io/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.13.4:3:634710] Cannot read properties of undefined (reading 'isDesignable') 
JS: 2023-05-30 23:13:38 [error X 1][https://theme-kit-extole.pantheonsite.io/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view1598") has already been destroyed and cannot be used. 
JS: 2023-06-08 01:34:42 [error X 1][https://theme-kit-extole.pantheonsite.io/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.13.4:3:144843] Cannot read properties of null (reading 'scrollTo') 
JS: 2023-06-15 04:49:13 [error X 1][https://theme-kit-extole.pantheonsite.io/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view128") has already been destroyed and cannot be used. 
JS: 2023-06-15 04:51:07 [error X 1][https://theme-kit-extole.pantheonsite.io/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view6249") has already been destroyed and cannot be used. 
JS: 2023-06-15 04:52:07 [error X 1][https://theme-kit-extole.pantheonsite.io/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view1131") has already been destroyed and cannot be used. 
JS: 2023-06-15 04:57:11 [error X 1][https://theme-kit-extole.pantheonsite.io/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view20993") has already been destroyed and cannot be used. 

PHP: showing 12 of 12PHP: 2023-05-09 22:18:12 [error X 1][/code/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::295] Uncaught Error: Call to a member function update_meta() on null in /code/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:295
Stack trace:
#0 /code/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(168): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(209, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /code/wp-content/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /code/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /code/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#5 /code/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /code/wp-admin/admin-ajax.php(188): do_action('wp_ajax_elem [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-25 20:15:33 [error X 16][/code/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::295] Uncaught Error: Call to a member function update_meta() on bool in /code/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:295
Stack trace:
#0 /code/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(168): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /code/wp-content/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /code/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /code/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#5 /code/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /code/wp-admin/admin-ajax.php(188): do_action('wp_ajax_ele [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-25 20:42:05 [error X 7][/code/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::295] Uncaught Error: Call to a member function update_meta() on null in /code/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:295
Stack trace:
#0 /code/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(168): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(16208, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /code/wp-content/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /code/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /code/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#5 /code/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /code/wp-admin/admin-ajax.php(188): do_action('wp_ajax_el [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-25 21:42:11 [notice X 12][/code/wp-content/plugins/elementor-pro/modules/dynamic-tags/tags/post-featured-image.php::36] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: /code/wp-content/plugins/elementor-pro/modules/dynamic-tags/tags/post-featured-image.php(36): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /code/wp-content/plugins/elementor/core/dynamic-tags/data-tag.php(44): ElementorPro\Modules\DynamicTags\Tags\Post_Featured_Image -> get_value()
#2: /code/wp-content/plugins/elementor/core/dynamic-tags/manager.php(216): Elementor\Core\DynamicTags\Data_Tag -> get_content()
#3: Elementor\Core\DynamicTags\Manager -> get_tag_data_content()
#4: /code/wp-content/plugins/elementor/core/dynamic-tags/manager.php(109): class type call_user_func_array()
',
)]
PHP: 2023-05-25 21:55:53 [error X 5][/code/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::295] Uncaught Error: Call to a member function update_meta() on null in /code/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:295
Stack trace:
#0 /code/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(168): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(16319, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /code/wp-content/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /code/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /code/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#5 /code/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /code/wp-admin/admin-ajax.php(188): do_action('wp_ajax_el [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-29 16:29:25 [notice X 9][/code/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::168] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-29 19:19:09 [error X 1][/code/wp-content/plugins/elementor/includes/managers/widgets.php::406] Uncaught Error: Call to a member function is_editable_by_current_user() on bool in /code/wp-content/plugins/elementor/includes/managers/widgets.php:406
Stack trace:
#0 [internal function]: Elementor\Widgets_Manager->ajax_render_widget(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#1 /code/wp-content/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /code/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#3 /code/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#4 /code/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#5 /code/wp-admin/admin-ajax.php(188): do_action('wp_ajax_element...')
#6 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-29 19:20:04 [notice X 10][/code/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-29 19:20:24 [notice X 222][/code/wp-content/plugins/elementor-pro/modules/dynamic-tags/tags/post-featured-image.php::36] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-29 19:57:49 [error X 7][/code/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::304] Uncaught Error: Call to a member function update_meta() on null in /code/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:304
Stack trace:
#0 /code/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(177): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(16208, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /code/wp-content/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /code/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /code/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#5 /code/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /code/wp-admin/admin-ajax.php(188): do_action('wp_ajax_el [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-29 19:58:42 [notice X 5][/code/wp-content/plugins/elementor/modules/history/revisions-manager.php::363] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-06-15 04:59:51 [notice X 14][/code/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined index: condition_type [array (
  'trace' => '
#0: /code/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /code/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /code/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /code/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hi, @erok415,

Thank you for reaching out! 🙏 

### ⛔ After reviewing your report we concluded this is not a bug caused by Elementor. The feature you're referring to is not yet supported.

If you think this should be an Elementor feature, please submit a new [🚀 Feature Request](https://github.com/orgs/elementor/discussions/new?category=feature-request), and we will consider it in the future if there is enough demand (votes) from other users.

Kind regards
