### ISSUE TITLE
⛔ 🐞 Bug Report: X-frame Option not working on Elementor Hosting website

### ISSUE THREAD

**Issue by MD-SEAM** [elementor/elementor#22813]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I used "WP Anti-Clickjack" WordPress plugin and enable the x-frame option but not working. this site builds by Elementor and the hosting is also taken from Elementor cloud.

### Steps to reproduce

Just need to fix the O-Frame option not working problem.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.20.2
	MySQL version: (Google) v8.0.26
	PHP Version: 7.4.33
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2.2
	Site URL: https://effectiv.ai
	Home URL: https://effectiv.ai
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 512M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: [REDACTED]
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.7.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 6.1.6
		Author: WP Engine

	Better Font Awesome
		Version: 2.0.4
		Author: Mickey Kay

	Classic Editor
		Version: 1.6.3
		Author: WordPress Contributors

	Custom Post Type UI
		Version: 1.13.5
		Author: WebDevStudios

	Easy Updates Manager
		Version: 9.0.16
		Author: Easy Updates Manager Team

	Ele Custom Skin
		Version: 3.1.7
		Author: Dudaster.com

	Ele Custom Skin Pro
		Version: 3.2.1
		Author: Dudaster.com

	Elementor
		Version: 3.15.0-cloud2
		Author: Elementor.com

	Elementor Pro
		Version: 3.15.0-cloud2
		Author: Elementor.com

	Essential Addons for Elementor
		Version: 5.8.0
		Author: WPDeveloper

	Flying Scripts
		Version: 1.2.3
		Author: WP Speed Matters

	Header Footer Code Manager
		Version: 1.1.32
		Author: 99robots

	HTTP Headers
		Version: 1.18.11
		Author: Dimitar Ivanov

	HubSpot All-In-One Marketing - Forms, Popups, Live Chat
		Version: 10.1.23
		Author: HubSpot

	NotificationX
		Version: 2.7.1
		Author: WPDeveloper

	Permalink Manager Lite
		Version: 2.4.1
		Author: Maciej Bis

	Redirection
		Version: 5.3.10
		Author: John Godley

	The Plus Addons for Elementor
		Version: 5.1.12
		Author: POSIMYTH

	The Plus Addons for Elementor - Pro
		Version: 5.0.8
		Author: POSIMYTH

	Unlimited Elements for Elementor (Premium)
		Version: 1.4.86
		Author: Unlimited Elements

	WP Anti-Clickjack
		Version: 1.7.6
		Author: Andy Feliciotti

	WP Htaccess Editor
		Version: 1.71
		Author: WebFactory Ltd

	WP Rocket
		Version: 3.10.7
		Author: WP Media

	WP User Profile Avatar
		Version: 1.0
		Author: WP Event Manager

	Yoast SEO
		Version: 20.8
		Author: Team Yoast


== Elements Usage ==
	
	container : 1
		container : 4
		divider : 1
		heading : 1
		image : 1
		text-editor : 2
	footer : 1
		divider : 1
		heading : 6
		icon-list : 4
		image : 2
		social-icons : 1
	header : 1
		button : 2
		icon : 1
		image : 2
		tp-navigation-menu : 1
	loop : 6
		author-box : 1
		button : 3
		heading : 11
		image : 7
		post-info : 4
		text-editor : 1
		theme-post-excerpt : 2
		theme-post-title : 2
	page : 2
		heading : 2
		icon-list : 1
		posts : 1
	popup : 1
		button : 2
		divider : 1
		image : 1
		nav-menu : 1
	section : 16
		author-box : 2
		button : 4
		form : 2
		heading : 55
		image : 21
		media-carousel : 2
		post-info : 1
		posts : 5
		template : 1
		text-editor : 4
		theme-page-title : 1
	widget : 0
		author-box : 1
		button : 2
		icon-list : 1
		image-carousel : 1
	wp-post : 2
		button : 3
		heading : 3
		icon-list : 4
		text-editor : 7
	wp-page : 19
		author-box : 3
		button : 37
		container : 51
		divider : 7
		heading : 270
		icon-list : 19
		image : 129
		media-carousel : 2
		post-info : 4
		posts : 7
		shortcode : 1
		template : 10
		text-editor : 35
	single-post : 3
		author-box : 1
		button : 1
		heading : 2
		post-info : 1
		template : 1
		theme-post-content : 1
		theme-post-excerpt : 1
	landing-page : 0
		button : 11
		form : 2
		heading : 36
		image : 23
		media-carousel : 2
		posts : 2
		text-editor : 19


== Settings ==
	
	cpt_support: post, page
	disable_color_schemes: yes
	disable_typography_schemes: yes
	allow_tracking: yes
	editor_break_lines: 1
	unfiltered_files_upload: 1


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	
	recaptcha: Active


== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Inactive by default
	Grid Container: Inactive by default
	AI Images: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Editor Top Bar: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Active
	Nested Accordion: Inactive by default
	Lazy Load Background Images: Active
	Global Style Guide: Inactive by default
	Improved Page Actions Layout: Inactive by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Menu: Active


== Log ==
	
Log: showing 20 of 352023-05-27 05:08:05 [info] elementor::elementor_updater Started 
2023-05-27 05:08:05 [info] Elementor/Upgrades - _on_each_version Start  
2023-05-27 05:08:06 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.14.0-cloud2',
  'to' => '3.14.0-cloud3',
)]
2023-05-27 05:08:07 [info] Elementor/Upgrades - _on_each_version Finished 
2023-05-27 05:08:07 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.14.0-cloud2',
  'to' => '3.14.0-cloud3',
)]
2023-05-27 05:08:14 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.14.0-cloud2',
  'to' => '3.14.0-cloud3',
)]
2023-05-27 05:09:39 [info] elementor-pro::elementor_pro_updater Started 
2023-05-27 05:09:39 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-05-27 05:09:39 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-05-27 05:09:39 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.14.0-cloud2',
  'to' => '3.14.0-cloud3',
)]
2023-06-19 06:41:37 [info] elementor-pro::elementor_pro_updater Started 
2023-06-19 06:41:37 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-06-19 06:41:37 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-06-19 06:41:37 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.14.0-cloud3',
  'to' => '3.15.0-cloud2',
)]
2023-06-19 06:41:37 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.14.0-cloud3',
  'to' => '3.15.0-cloud2',
)]
2023-06-19 06:42:31 [info] elementor::elementor_updater Started 
2023-06-19 06:42:31 [info] Elementor/Upgrades - _on_each_version Start  
2023-06-19 06:42:31 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.14.0-cloud3',
  'to' => '3.15.0-cloud2',
)]
2023-06-19 06:42:33 [info] Elementor/Upgrades - _on_each_version Finished 
2023-06-19 06:42:33 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.14.0-cloud3',
  'to' => '3.15.0-cloud2',
)]

PHP: showing 6 of 6PHP: 2023-05-12 09:00:18 [error X 1][/mnt/customers-6/customers-el-4041309-33812-effectiv-wordpress-pvc-62e9e3777aa6920020f68e38/wp-content/wp-content/plugins/elementor/includes/plugin.php::706] Uncaught Error: Class 'Elementor\Core\Experiments\Manager' not found in /mnt/customers-6/customers-el-4041309-33812-effectiv-wordpress-pvc-62e9e3777aa6920020f68e38/wp-content/wp-content/plugins/elementor/includes/plugin.php:706
Stack trace:
#0 /mnt/customers-6/customers-el-4041309-33812-effectiv-wordpress-pvc-62e9e3777aa6920020f68e38/wp-content/wp-content/plugins/elementor/includes/plugin.php(647): Elementor\Plugin->init_components()
#1 /mnt/customers-6/customers-el-4041309-33812-effectiv-wordpress-pvc-62e9e3777aa6920020f68e38/wp-content/wp-includes/class-wp-hook.php(308): Elementor\Plugin->init()
#2 /mnt/customers-6/customers-el-4041309-33812-effectiv-wordpress-pvc-62e9e3777aa6920020f68e38/wp-content/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#3 /mnt/customers-6/customers-el-4041309-33812-effectiv-wordpress-pvc-62e9e3777aa6920020f68e38/wp-content/wp-includes/plugin.php(517): WP_Hook->do_action()
#4 /mnt/customers-6/customers-el-4041309-33812-effectiv-wordpress-pvc-62e9e3777aa6920020f68e38/w [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-16 05:01:15 [notice X 5][/mnt/customers-6/customers-el-4041309-33812-effectiv-wordpress-pvc-62e9e3777aa6920020f68e38/wp-content/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php::33] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-17 17:05:06 [notice X 1][/mnt/customers/customers-6/customers-el-4041309-33812-effectiv-wordpress-pvc-62e9e3777aa6920020f68e38/wp-content/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::171] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-17 17:32:54 [notice X 1][/mnt/customers/customers-6/customers-el-4041309-33812-effectiv-wordpress-pvc-62e9e3777aa6920020f68e38/wp-content/wp-content/plugins/elementor/modules/history/revisions-manager.php::363] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-30 20:16:03 [notice X 9][/mnt/customers/customers-6/customers-el-4041309-33812-effectiv-wordpress-pvc-62e9e3777aa6920020f68e38/wp-content/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-06-14 04:16:30 [warning X 1][/mnt/customers/customers-6/customers-el-4041309-33812-effectiv-wordpress-pvc-62e9e3777aa6920020f68e38/wp-content/wp-content/plugins/elementor/core/files/base.php::203] unlink(/mnt/customers/customers-6/customers-el-4041309-33812-effectiv-wordpress-pvc-62e9e3777aa6920020f68e38/wp-content/wp-content/uploads/elementor/css/post-6735.css): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 2 of 2JS: 2023-05-16 05:03:14 [error X 1][https://effectiv.ai/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.14.0-cloud2:2:88664] Cannot read properties of undefined (reading 'settings') 
JS: 2023-05-25 17:42:32 [error X 3][https://effectiv.ai/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.14.0-cloud2:3:1106494] Cannot read properties of null (reading 'getBoundingClientRect') 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	Essential Addons for Elementor: Compatibility not specified
	The Plus Addons for Elementor: Compatibility not specified
	The Plus Addons for Elementor - Pro: Compatibility not specified
	Unlimited Elements for Elementor (Premium): Compatibility not specified

== Elementor Pro - Compatibility Tag ==
	

				

````

</details>

**Comment by nicholaszein** [comment]
Hello @MD-SEAM! 

Thank you for submitting your issue! 🙏 

Please allow us some time to investigate it, and get back to you with our findings. 🧐 

Best regards

**Comment by nicholaszein** [comment]
Hi @MD-SEAM,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
We tested the plugin in question and it worked without any issues. If you are experiencing issues with the plugin, you should either check for a conflict with other plugins or reach out to the plugin developer for help.

However, you should know that Elementor Hosting already serves `X-frame Options` headers set as `SAMEORIGIN` **by default**!
So you really don't need an additional plugin for securing your website.

![image](https://github.com/elementor/elementor/assets/113993460/7065f4dc-a569-4845-a67a-61398e9e89b8)

### 👍 For now, that's all we can help with. 

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
