### ISSUE TITLE
🔗 🐞 Bug Report: Responsive styles are not generated for Container templates (Related to #19394) - [ED-11103]

### ISSUE THREAD

**Issue by siteservice** [elementor/elementor#22829]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

As of 3.14, CSS is not generating for container templates after doing a tools > regenerate files.  Responsive controls are not saving to the template CSS even after re-saving.

Rolling back to 3.13.2 resolves the issue

### Steps to reproduce

1. Create a template for a page section (container)
2. Add responsive settings, where you would have the mobile width override the desktop settings
3. Perform a Tools > Regenerate files call
4. Notice that the CSS is no longer being generated
5. Edit and re-save the template and CSS will be restored (without responsive)
6

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.21.4
	MySQL version: mariadb.org binary distribution v10.11.3-MariaDB-1:10.11.3+maria~ubu2204
	PHP Version: 8.0.28
	PHP Memory Limit: 768M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2.2
	Site URL: XXXXXXXXXXXXXXXXXX
	Home URL: XXXXXXXXXXXXXXXXXX
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 256M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: [REDACTED]
	Debug Mode: Active

== Theme ==
	Name: Web Programming Solutions
	Version: 1.0
	Author: Web Programming Solutions
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.13.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.13.2
		Author: Elementor.com


== Features ==
	Custom Fonts: 2
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active by default
	Grid Container: Inactive by default
	Default to New Theme Builder: Active by default
	Editor Top Bar: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Menu: Inactive by default


== Log ==
	
JS: showing 5 of 5JS: 2023-06-05 19:09:43 [error X 18][https://XXXXXXXXXXXXXXXXX/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.13.4:3:795450] Cannot read properties of undefined (reading 'localized') 
JS: 2023-06-13 14:37:45 [error X 1][https://XXXXXXXXXXXXXXXXX/wp-admin/post.php?post=152&action=elementor:1:1] "undefined" is not valid JSON 
JS: 2023-06-15 16:29:26 [error X 1][https://XXXXXXXXXXXXXXXXX/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.13.4:3:907878] elementorFrontend is not defined 
JS: 2023-06-15 18:09:19 [error X 1][https://XXXXXXXXXXXXXXXXX/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.13.4:2:14266] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `ucaddon_topic_list` got as `gap` value. Expected array or object.',
)]
JS: 2023-06-15 18:17:50 [error X 2][https://XXXXXXXXXXXXXXXXX/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.13.4:2:14266] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `ucaddon_topic_list` got as `content_max_width` value. Expected array or object.',
)]

PHP: showing 4 of 4PHP: 2023-06-06 12:30:27 [warning X 40][/home/XXXXXXXXXXXXXXXXX/htdocs/XXXXXXXXXXXXXXXXX/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-06-06 13:00:26 [error X 6][/home/XXXXXXXXXXXXXXXXX/htdocs/XXXXXXXXXXXXXXXXX/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::304] Uncaught Error: Call to a member function update_meta() on null in /home/XXXXXXXXXXXXXXXXX/htdocs/XXXXXXXXXXXXXXXXX/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:304
Stack trace:
#0 /home/XXXXXXXXXXXXXXXXX/htdocs/XXXXXXXXXXXXXXXXX/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(177): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions()
#2 /home/XXXXXXXXXXXXXXXXX/htdocs/XXXXXXXXXXXXXXXXX/wp-content/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func()
#3 /home/XXXXXXXXXXXXXXXXX/htdocs/XXXXXXXXXXXXXXXXX/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#4 /home/XXXXXXXXXXXXXXXXX/htdocs/XXXXXXXXXXXXXXXXX/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#5 /home/XXXXXXXXXXXXXXXXX/htdocs/XXXXXXXXXXXXXXXXX/wp-includes/plugin.php(517): WP_Hook->do_action()
#6 /home/XXXXXXXXXXXXXXXXX/htdocs/XXXXXXXXXXXXXXXXX/wp-admin/admin-ajax.php(188): do_action()
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-06-13 13:54:37 [warning X 16][/home/XXXXXXXXXXXXXXXXX/htdocs/XXXXXXXXXXXXXXXXX/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/fonts-manager.php::252] Undefined array key "editor_post_id" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-06-13 15:43:18 [warning X 5][/home/XXXXXXXXXXXXXXXXX/htdocs/XXXXXXXXXXXXXXXXX/wp-content/plugins/elementor-pro/modules/posts/skins/skin-content-base.php::265] Attempt to read property "ID" on null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 10 of 102023-06-19 12:17:54 [info] elementor-pro::elementor_pro_updater Started 
2023-06-19 12:17:54 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-06-19 12:17:54 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-06-19 12:17:54 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.13.2',
  'to' => '3.14.0',
)]
2023-06-19 12:17:54 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.13.2',
  'to' => '3.14.0',
)]
2023-06-19 12:17:54 [info] elementor::elementor_updater Started 
2023-06-19 12:17:54 [info] Elementor/Upgrades - _on_each_version Start  
2023-06-19 12:17:54 [info] Elementor/Upgrades - _on_each_version Finished 
2023-06-19 12:17:54 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.4',
  'to' => '3.14.0',
)]
2023-06-19 12:17:54 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.4',
  'to' => '3.14.0',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==
	

				

````

</details>

**Comment by torchsmith** [comment]
Same issue for me

**Comment by ldentzien** [comment]
Same issue for me

**Comment by torchsmith** [comment]
I can't update Elementor on hundreds of websites right now because of this bug. Pro user. Can you guys prioritize this in any way @nicholaszein ?

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Core v.3.15.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
