### ISSUE TITLE
⛔ 🐞 Bug Report: There is always black log in bar showing elementor debugger issue

### ISSUE THREAD

**Issue by Umairsher** [elementor/elementor#22859]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

There is always black log in bar showing elementor debugger issue. How to fix it and remove the log in bar that is shown to everyone who visits our site.

### Steps to reproduce

I have tried every step but could not find any solution

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt



== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.6.12
	PHP Version: 8.0.28
	PHP Memory Limit: 1536M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 1536M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2.2
	Site URL: https://learnonlineschool.info
	Home URL: https://learnonlineschool.info
	WP Multisite: No
	Max Upload Size: 2 GB
	Memory limit: 40M
	Max Memory limit: 1536M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 5
	Admin Email: [REDACTED]
	Debug Mode: Inactive

== Theme ==
	Name: Astra
	Version: 4.1.5
	Author: Brainstorm Force
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

== Active Plugins ==
	Ad Inserter
		Version: 2.7.29
		Author: Igor Funa

	Ads.txt Manager
		Version: 1.4.2
		Author: 10up

	Astra Pro
		Version: 4.1.5
		Author: Brainstorm Force

	Auto Approve Comments
		Version: 2.8
		Author: Federico Andrioli

	AzonPress
		Version: 2.0.8
		Author: WPManageNinja

	BackupGuard Pro
		Version: 1.7.0
		Author: BackupGuard

	BuddyPress
		Version: 11.2.0
		Author: The BuddyPress Community

	Contact Form 7
		Version: 5.7.7
		Author: Takayuki Miyoshi

	CookieYes | GDPR Cookie Consent
		Version: 3.0.9
		Author: CookieYes

	Elementor
		Version: 3.14.0
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.14.0
		Author: Elementor.com

	Jetpack
		Version: 12.2
		Author: Automattic

	JoomDev WP Pros &amp; Cons
		Version: 2.0.9
		Author: MightyThemes

	Jotform Online Forms
		Version: 1.3.1
		Author: Jotform

	Lazy Load - Optimize Images
		Version: 2.3.6
		Author: WP Rocket

	Link Whisper Free
		Version: 0.6.4
		Author: Link Whisper

	Page Views Count
		Version: 2.8.1
		Author: a3rev Software

	Performance Lab
		Version: 2.3.0
		Author: WordPress Performance Team

	Premium Starter Templates
		Version: 3.2.3
		Author: Brainstorm Force

	Query Monitor
		Version: 3.12.3
		Author: John Blackbourn

	Quiz Maker
		Version: 6.4.3.7
		Author: Quiz Maker team

	Rank Math SEO
		Version: 1.0.117.1
		Author: Rank Math

	Recent Posts Widget With Thumbnails
		Version: 7.1.1
		Author: Kybernetik Services

	ShortPixel Image Optimizer
		Version: 5.2.3
		Author: ShortPixel - Convert WebP/AVIF & Optimize Images

	Simple Author Box
		Version: 2.51
		Author: WebFactory Ltd

	Site Kit by Google
		Version: 1.103.0
		Author: Google

	Spectra
		Version: 2.6.4
		Author: Brainstorm Force

	Tutor LMS
		Version: 2.2.1
		Author: Themeum

	WPCode Lite
		Version: 2.0.12
		Author: WPCode

	WPForms Lite
		Version: 1.8.2.1
		Author: WPForms

	WP Headers And Footers
		Version: 2.0.1
		Author: WPBrigade

	WP Reset
		Version: 1.97
		Author: WebFactory Ltd

	WP Rocket
		Version: 3.13.4
		Author: WP Media


== Elements Usage ==
	
	container : 0
		heading : 7
		social-icons : 3
	header : 3
		nav-menu : 1
		social-icons : 1
		theme-site-logo : 1
	page : 1
		button : 1
		container : 1
	section : 6
		button : 2
		heading : 4
		icon-box : 1
		icon-list : 1
		image : 2
		social-icons : 4
	wp-post : 2
		button : 1
		container : 1
		text-editor : 1
	wp-page : 1
		button : 1
		call-to-action : 4
		container : 8
		heading : 1
		icon : 1
		image : 1
		posts : 1
		text-editor : 1
	single-post : 3
		container : 1
		facebook-page : 1
		heading : 3
		post-comments : 1
		post-info : 1
		posts : 1
		search-form : 1
		social-icons : 1
		theme-post-content : 1
		theme-post-featured-image : 1
		theme-post-title : 1


== Settings ==
	
	cpt_support: post, page, courses, lesson, tutor_quiz, tutor_assignments
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active
	Grid Container: Inactive by default
	Default to New Theme Builder: Active
	Editor Top Bar: Inactive
	Landing Pages: Active
	Nested Elements: Active
	Nested Accordion: Inactive by default
	Lazy Load Background Images: Active
	Global Style Guide: Inactive by default
	Page Transitions: Active
	Notes: Active
	Loop: Active
	Form Submissions: Active
	Scroll Snap: Active
	Menu: Inactive by default


== Log ==
	
Log: showing 20 of 312023-04-14 13:27:55 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.2',
  'to' => '3.12.2',
)]
2023-06-06 18:40:09 [info] elementor::elementor_updater Started 
2023-06-06 18:40:09 [info] Elementor/Upgrades - _on_each_version Start  
2023-06-06 18:40:09 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.0-dev2',
  'to' => '3.13.4',
)]
2023-06-06 18:40:10 [info] Elementor/Upgrades - _on_each_version Finished 
2023-06-06 18:40:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.0-dev2',
  'to' => '3.13.4',
)]
2023-06-06 18:40:14 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.0-dev2',
  'to' => '3.13.4',
)]
2023-06-10 11:31:10 [info] elementor-pro::elementor_pro_updater Started 
2023-06-10 11:31:10 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-06-10 11:31:10 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-06-10 11:31:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.2',
  'to' => '3.13.2',
)]
2023-06-10 11:31:12 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.2',
  'to' => '3.13.2',
)]
2023-06-20 14:51:26 [info] elementor::elementor_updater Started 
2023-06-20 14:51:26 [info] Elementor/Upgrades - _on_each_version Start  
2023-06-20 14:51:26 [info] Elementor/Upgrades - _on_each_version Finished 
2023-06-20 14:51:26 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.4',
  'to' => '3.14.0',
)]
2023-06-20 14:51:30 [info] elementor-pro::elementor_pro_updater Started 
2023-06-20 14:51:30 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-06-20 14:51:30 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-06-20 14:51:30 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.13.2',
  'to' => '3.14.0',
)]

PHP: showing 8 of 8PHP: 2023-04-15 12:28:58 [error X 3][/home/u968933765/domains/learnonlineschool.info/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::295] Uncaught Error: Call to a member function update_meta() on bool in /home/u968933765/domains/learnonlineschool.info/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:295
Stack trace:
#0 /home/u968933765/domains/learnonlineschool.info/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(168): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;ajax_save_theme_template_conditions()
#2 /home/u968933765/domains/learnonlineschool.info/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func()
#3 /home/u968933765/domains/learnonlineschool.info/public_html/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module-&gt;handle_ajax_request()
#4 /home/u968933765/domains/learnonlineschool.info/public_html/wp-includes/class-wp-hook.php(332): WP_Hook-&gt;apply_filters()
#5 /home/u968933765/domains/learnonlineschool.info/public_html/wp-includes/plugin.php(517): WP_Hook-&gt;do_action()
#6 /home/u968933765/domains/learnonlineschool.info/public_html/wp-admin/admin-ajax.php(188): do_action()
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-06-08 10:59:54 [error X 2][/home/u968933765/domains/learnonlineschool.info/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::295] Uncaught Error: Call to a member function update_meta() on null in /home/u968933765/domains/learnonlineschool.info/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:295
Stack trace:
#0 /home/u968933765/domains/learnonlineschool.info/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(168): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;ajax_save_theme_template_conditions()
#2 /home/u968933765/domains/learnonlineschool.info/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func()
#3 /home/u968933765/domains/learnonlineschool.info/public_html/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module-&gt;handle_ajax_request()
#4 /home/u968933765/domains/learnonlineschool.info/public_html/wp-includes/class-wp-hook.php(332): WP_Hook-&gt;apply_filters()
#5 /home/u968933765/domains/learnonlineschool.info/public_html/wp-includes/plugin.php(517): WP_Hook-&gt;do_action()
#6 /home/u968933765/domains/learnonlineschool.info/public_html/wp-admin/admin-ajax.php(188): do_action()
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-06-10 11:30:52 [error X 1][/home/u968933765/domains/learnonlineschool.info/public_html/wp-content/plugins/elementor/core/base/module.php::331] Uncaught Error: Class &quot;ElementorPro\Modules\GlobalWidget\Widgets\Global_Widget&quot; not found in /home/u968933765/domains/learnonlineschool.info/public_html/wp-content/plugins/elementor/core/base/module.php:331
Stack trace:
#0 /home/u968933765/domains/learnonlineschool.info/public_html/wp-includes/class-wp-hook.php(308): Elementor\Core\Base\Module-&gt;init_widgets()
#1 /home/u968933765/domains/learnonlineschool.info/public_html/wp-includes/class-wp-hook.php(332): WP_Hook-&gt;apply_filters()
#2 /home/u968933765/domains/learnonlineschool.info/public_html/wp-includes/plugin.php(517): WP_Hook-&gt;do_action()
#3 /home/u968933765/domains/learnonlineschool.info/public_html/wp-content/plugins/elementor/includes/managers/widgets.php(122): do_action()
#4 /home/u968933765/domains/learnonlineschool.info/public_html/wp-content/plugins/elementor/includes/managers/widgets.php(308): Elementor\Widgets_Manager-&gt;init_widgets()
#5 /home/u968933765/domains/learnonlineschool.info/public_html/wp-content/plugins/elementor/includes/elements/container.php(304): Elementor\Widgets_Manager-&gt;get_widget_types()
#6 /home/u968933765/domains/learnonlineschool.info/public_html/wp-content/plugins/elementor/includes/base/element-base.php(1414): Elementor\Includes\Elements\Container-&gt;_get_default_child_type()
#7 /home/u968933765/domains/learnonlineschool.info/public_html/wp-content/plugins/elementor/includes/base/element-base.php(340): Elementor\Element_Base-&gt;get_child_type()
#8 /home/u968933765/domains/learnonlineschool.info/public_html/wp-content/plugins/elementor/includes/base/element-base.php(1459): Elementor\Element_Base-&gt;add_child()
#9 /home/u968933765/domains/learnonlineschool.info/public_html/wp-content/plugins/elementor/includes/base/element-base.php(300): Elementor\Element_Base-&gt;init_children()
#10 /home/u968933765/domains/learnonlineschool.info/public_html/wp-content/plugins/elementor/core/dynamic-tags/dynamic-css.php(35): Elementor\Element_Base-&gt;get_children()
#11 /home/u968933765/domains/learnonlineschool.info/public_html/wp-content/plugins/elementor/core/files/css/post.php(178): Elementor\Core\DynamicTags\Dynamic_CSS-&gt;render_styles()
#12 /home/u968933765/domains/learnonlineschool.info/public_html/wp-content/plugins/elementor/core/files/css/base.php(659): Elementor\Core\Files\CSS\Post-&gt;render_css()
#13 /home/u968933765/domains/learnonlineschool.info/public_html/wp-content/plugins/elementor/core/files/base.php(180): Elementor\Core\Files\CSS\Base-&gt;parse_content()
#14 /home/u968933765/domains/learnonlineschool.info/public_html/wp-content/plugins/elementor/core/files/css/base.php(130): Elementor\Core\Files\Base-&gt;update_file()
#15 /home/u968933765/domains/learnonlineschool.info/public_html/wp-content/plugins/elementor/core/files/css/base.php(217): Elementor\Core\Files\CSS\Base-&gt;update()
#16 /home/u968933765/domains/learnonlineschool.info/public_html/wp-content/plugins/elementor/core/files/css/post.php(201): Elementor\Core\Files\CSS\Base-&gt;enqueue()
#17 /home/u968933765/domains/learnonlineschool.info/public_html/wp-content/plugins/elementor/core/dynamic-tags/manager.php(488): Elementor\Core\Files\CSS\Post-&gt;enqueue()
#18 /home/u968933765/domains/learnonlineschool.info/public_html/wp-includes/class-wp-hook.php(308): Elementor\Core\DynamicTags\Manager-&gt;after_enqueue_post_css()
#19 /home/u968933765/domains/learnonlineschool.info/public_html/wp-includes/class-wp-hook.php(332): WP_Hook-&gt;apply_filters()
#20 /home/u968933765/domains/learnonlineschool.info/public_html/wp-includes/plugin.php(517): WP_Hook-&gt;do_action()
#21 /home/u968933765/domains/learnonlineschool.info/public_html/wp-content/plugins/elementor/core/files/css/base.php(264): do_action()
#22 /home/u968933765/domains/learnonlineschool.info/public_html/wp-content/plugins/elementor/core/files/css/post.php(201): Elementor\Core\Files\CSS\Base-&gt;enqueue()
#23 /home/u968933765/domains/learnonlineschool.info/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/locations-manager.php(93): Elementor\Core\Files\CSS\Post-&gt;enqueue()
#24 /home/u968933765/domains/learnonlineschool.info/public_html/wp-includes/class-wp-hook.php(308): ElementorPro\Modules\ThemeBuilder\Classes\Locations_Manager-&gt;enqueue_styles()
#25 /home/u968933765/domains/learnonlineschool.info/public_html/wp-includes/class-wp-hook.php(332): WP_Hook-&gt;apply_filters()
#26 /home/u968933765/domains/learnonlineschool.info/public_html/wp-includes/plugin.php(517): WP_Hook-&gt;do_action()
#27 /home/u968933765/domains/learnonlineschool.info/public_html/wp-includes/script-loader.php(2194): do_action()
#28 /home/u968933765/domains/learnonlineschool.info/public_html/wp-includes/class-wp-hook.php(308): wp_enqueue_scripts()
#29 /home/u968933765/domains/learnonlineschool.info/public_html/wp-includes/class-wp-hook.php(332): WP_Hook-&gt;apply_filters()
#30 /home/u968933765/domains/learnonlineschool.info/public_html/wp-includes/plugin.php(517): WP_Hook-&gt;do_action()
#31 /home/u968933765/domains/learnonlineschool.info/public_html/wp-includes/general-template.php(3049): do_action()
#32 /home/u968933765/domains/learnonlineschool.info/public_html/wp-content/themes/astra/header.php(31): wp_head()
#33 /home/u968933765/domains/learnonlineschool.info/public_html/wp-includes/template.php(783): require_once(&#039;/home/u96893376...&#039;)
#34 /home/u968933765/domains/learnonlineschool.info/public_html/wp-includes/template.php(718): load_template()
#35 /home/u968933765/domains/learnonlineschool.info/public_html/wp-includes/general-template.php(48): locate_template()
#36 /home/u968933765/domains/learnonlineschool.info/public_html/wp-content/themes/astra/page.php(20): get_header()
#37 /home/u968933765/domains/learnonlineschool.info/public_html/wp-includes/template-loader.php(106): include(&#039;/home/u96893376...&#039;)
#38 /home/u968933765/domains/learnonlineschool.info/public_html/wp-blog-header.php(19): require_once(&#039;/home/u96893376...&#039;)
#39 /home/u968933765/domains/learnonlineschool.info/public_html/index.php(17): require(&#039;/home/u96893376...&#039;)
#40 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-06-10 11:32:43 [warning X 12][/home/u968933765/domains/learnonlineschool.info/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined array key &quot;data&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-06-10 20:46:40 [error X 6][/home/u968933765/domains/learnonlineschool.info/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::304] Uncaught Error: Call to a member function update_meta() on null in /home/u968933765/domains/learnonlineschool.info/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:304
Stack trace:
#0 /home/u968933765/domains/learnonlineschool.info/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(177): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;ajax_save_theme_template_conditions()
#2 /home/u968933765/domains/learnonlineschool.info/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func()
#3 /home/u968933765/domains/learnonlineschool.info/public_html/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module-&gt;handle_ajax_request()
#4 /home/u968933765/domains/learnonlineschool.info/public_html/wp-includes/class-wp-hook.php(332): WP_Hook-&gt;apply_filters()
#5 /home/u968933765/domains/learnonlineschool.info/public_html/wp-includes/plugin.php(517): WP_Hook-&gt;do_action()
#6 /home/u968933765/domains/learnonlineschool.info/public_html/wp-admin/admin-ajax.php(188): do_action()
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-06-10 21:09:27 [warning X 2][/home/u968933765/domains/learnonlineschool.info/public_html/wp-content/plugins/elementor/modules/history/revisions-manager.php::363] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-06-15 17:44:27 [warning X 4][/home/u968933765/domains/learnonlineschool.info/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::171] Undefined array key &quot;editor_post_id&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-06-15 18:34:55 [warning X 2][/home/u968933765/domains/learnonlineschool.info/public_html/wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 3 of 3JS: 2023-06-10 18:20:02 [error X 12][https://learnonlineschool.info/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.13.4:3:634710] Cannot read properties of undefined (reading &#039;isDesignable&#039;) 
JS: 2023-06-15 13:37:29 [error X 1][https://learnonlineschool.info/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.13.4:3:794943] Cannot read properties of undefined (reading &#039;toLowerCase&#039;) 
JS: 2023-06-15 13:39:18 [error X 4][https://learnonlineschool.info/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.13.4:3:795450] Cannot read properties of undefined (reading &#039;localized&#039;) 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==
	



````

</details>

**Comment by hitsgee** [comment]
You can turn off debugger within Elementor > Tools. This will remove this from the admin bar.

**Comment by nicholaszein** [comment]
Hello @Umairsher,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
We cannot reproduce your issue using **<ins>ONLY</ins>** Elementor and Elementor Pro activated with the Hello Elementor theme also installed and activated.

Your issue is likely caused by a conflict with another plugin, or cache.

### ✅ What you can do to solve your issue:

#### ⚠️ Make a Backup of your website before proceeding, and if possible do it in a staging environment!

1. Deactivate the Elementor Debugger by following the instructions in [this article](https://elementor.com/help/elementor-debugger/).
2. Disable/Deactivate all your plugins except **Elementor** (and **Elementor Pro**).
    - If this solves the problem, gradually re-activate plugin-by-plugin (and check if the problem returns) to identify the problematic or conflicting plugin. In this case, contact the 3rd-party plugin support as we don't provide support for 3rd party plugins.
    - If it doesn't solve your problem, try the next step:
3. Change your WordPress theme to the [Hello Elementor](https://wordpress.org/themes/hello-elementor/) theme and check if the problem is solved.
4. Clear all cache types, including but not limited to **Server cache**, **WordPress (optimization plugin) cache**, **CDN cache**, and **Browser cache**. Also, try visiting the front page of your website in **incognito/private** mode.
5. Make sure the server resources allocated to your site and WordPress installation meet our [Requirements](https://elementor.com/help/requirements/). 
    - To check this information go to your WordPress `Dashboard` > `Elementor` > `System info` [learn how to copy it here](https://elementor.com/help/hare-my-system-info/). We can't accept issues without it.

### 👍 For now, that's all we can help with. 

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
