### ISSUE TITLE
⛔ 🐞 Bug Report: Pop-Up highlights main menu link when open

### ISSUE THREAD

**Issue by rsmasi** [elementor/elementor#22884]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

After creating a canvas menu using the pop-up method. We implemented the WordPress Menu inside the pop-up, as a drop down. 

When a sub-menu exists, and you click on the menu to drop down open. After hovering the mouse to the main menu link, it highlights the previous opened link.

Please see attached file
<img width="460" alt="Screenshot 2023-06-23 at 4 12 00 PM" src="https://github.com/elementor/elementor/assets/137570884/7110a7db-17dd-4da8-9ebc-6101d2bfdc64">

### Steps to reproduce

1) Create a pop-up 
2) Drag and drop WordPress Menu ( be sure to have sub menus)
3) Edit the menu to drop down, with full width OFF.
4) Create a button and link the pop-up Menu
5) Try opening the submenu drop down, and then hover to main menu items

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: mariadb.org binary distribution v10.9.4
	PHP Version: 8.1.14
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2.2
	Site URL: https://www.apexgruppe.com
	Home URL: https://www.apexgruppe.com
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: [REDACTED]
	Debug Mode: Inactive

== Theme ==
	Name: Apex Gruppe
	Version: 2.7.1.1687294842
	Author: N/A
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.7.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5 Safari/605.1.15

== Active Plugins ==
	Akismet Anti-Spam: Spam Protection
		Version: 5.2
		Author: Automattic - Anti Spam Team

	All-in-One WP Migration
		Version: 7.75
		Author: ServMask

	DoLogin Security
		Version: 3.5.2
		Author: WPDO

	Elementor
		Version: 3.14.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.14.0
		Author: Elementor.com

	LiteSpeed Cache
		Version: 5.5
		Author: LiteSpeed Technologies

	Payment Plugins for Stripe WooCommerce
		Version: 3.3.43
		Author: Payment Plugins, support@paymentplugins.com

	The SEO Framework
		Version: 4.2.8
		Author: The SEO Framework Team

	WooCommerce
		Version: 7.8.0
		Author: Automattic


== Elements Usage ==
	
	footer : 1
		divider : 3
		form : 1
		heading : 1
		image : 1
		loop-carousel : 1
		spacer : 4
		text-editor : 3
	header : 1
		button : 1
		theme-site-logo : 1
	page : 2
		button : 1
		heading : 2
		icon : 1
	popup : 2
		form : 1
		heading : 2
		nav-menu : 1
		search-form : 1
		spacer : 3
	product : 1
		button : 2
		spacer : 2
		woocommerce-product-add-to-cart : 1
		woocommerce-product-images : 1
		woocommerce-product-meta : 1
		woocommerce-product-price : 1
		woocommerce-product-short-description : 1
		woocommerce-product-stock : 1
		woocommerce-product-title : 1
	wp-page : 4
		heading : 1
		image-carousel : 1
		text-editor : 1
		woocommerce-cart : 1
		woocommerce-checkout-page : 1
	single-post : 1
		author-box : 1
		divider : 1
		post-info : 2
		post-navigation : 1
		spacer : 1
		theme-post-content : 1
		theme-post-title : 1
	product-archive : 1
		wc-archive-products : 1
		woocommerce-notices : 1
	loop-item : 6
		button : 1
		theme-post-featured-image : 2
		theme-post-title : 1
		woocommerce-product-price : 1
		woocommerce-product-title : 1
		woocommerce-products : 4
	error-404 : 1
		button : 1
		divider : 1
		heading : 3


== Settings ==
	
	cpt_support: post, page
	allow_tracking: yes
	font_display: swap
	load_fa4_shim: yes


== Features ==
	Custom Fonts: 1
	Custom Icons: 0

== Integrations ==
	
	woocommerce: Active


== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Upgrade Swiper Library: Active by default
	Grid Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Editor Top Bar: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Inactive by default
	Nested Accordion: Inactive by default
	Lazy Load Background Images: Inactive by default
	Global Style Guide: Inactive by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Menu: Inactive by default


== Log ==
	
Log: showing 18 of 182023-05-23 20:18:48 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.13.1',
  'to' => '3.13.2',
)]
2023-05-23 20:18:48 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-05-23 20:18:48 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-05-23 20:18:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.13.1',
  'to' => '3.13.2',
)]
2023-06-07 03:26:27 [info] elementor::elementor_updater Started 
2023-06-07 03:26:27 [info] Elementor/Upgrades - _on_each_version Start  
2023-06-07 03:26:27 [info] Elementor/Upgrades - _on_each_version Finished 
2023-06-07 03:26:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.3',
  'to' => '3.13.4',
)]
2023-06-20 20:33:10 [info] elementor-pro::elementor_pro_updater Started 
2023-06-20 20:33:10 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-06-20 20:33:10 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-06-20 20:33:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.13.2',
  'to' => '3.14.0',
)]
2023-06-20 20:33:10 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.13.2',
  'to' => '3.14.0',
)]
2023-06-20 20:33:10 [info] elementor::elementor_updater Started 
2023-06-20 20:33:10 [info] Elementor/Upgrades - _on_each_version Start  
2023-06-20 20:33:10 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.4',
  'to' => '3.14.0',
)]
2023-06-20 20:33:11 [info] Elementor/Upgrades - _on_each_version Finished 
2023-06-20 20:33:11 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.4',
  'to' => '3.14.0',
)]

PHP: showing 11 of 11PHP: 2023-05-23 20:43:07 [warning X 169][/var/www/html/wp-content/plugins/elementor-pro/modules/woocommerce/module.php::381] Undefined array key 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-06-15 19:56:34 [warning X 1][/var/www/html/wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-06-15 20:07:05 [notice X 52][/var/www/html/wp-content/plugins/elementor-pro/modules/woocommerce/module.php::591] parse_str(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-06-16 22:27:44 [warning X 32][/var/www/html/wp-content/plugins/elementor/core/logger/items/js.php::17] Undefined array key "url" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-06-16 22:47:18 [warning X 7][/var/www/html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-06-16 22:55:17 [error X 1][/var/www/html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::304] Uncaught Error: Call to a member function update_meta() on null in /var/www/html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:304
Stack trace:
#0 /var/www/html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(177): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions()
#2 /var/www/html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func()
#3 /var/www/html/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#4 /var/www/html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#5 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action()
#6 /var/www/html/wp-admin/admin-ajax.php(188): do_action()
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-06-20 20:37:13 [warning X 1][/var/www/html/wp-content/plugins/elementor/modules/history/revisions-manager.php::363] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-06-21 01:45:55 [warning X 9][/var/www/html/wp-content/plugins/elementor-pro/modules/forms/fields/upload.php::466] foreach() argument must be of type array|object, null given [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-06-21 19:45:22 [error X 8][/var/www/html/wp-content/plugins/elementor-pro/modules/popup/module.php::126] Uncaught Error: Call to undefined method ElementorPro\Modules\LoopBuilder\Documents\Loop::save_display_settings_data() in /var/www/html/wp-content/plugins/elementor-pro/modules/popup/module.php:126
Stack trace:
#0 [internal function]: ElementorPro\Modules\Popup\Module->save_display_settings()
#1 /var/www/html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func()
#2 /var/www/html/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#3 /var/www/html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#4 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action()
#5 /var/www/html/wp-admin/admin-ajax.php(188): do_action()
#6 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-06-21 19:54:29 [warning X 3][/var/www/html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::171] Undefined array key "editor_post_id" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-06-21 20:19:18 [warning X 16][/var/www/html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key "condition_type" [array (
  'trace' => '
#0: /var/www/html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /var/www/html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /var/www/html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /var/www/html/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]

JS: showing 13 of 13JS: 2023-06-15 19:56:24 [error X 1][https://www.apexgruppe.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.13.4:3:907878] elementorFrontend is not defined 
JS: 2023-06-16 22:27:37 [error X 11058][https://www.apexgruppe.com/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:14798] null is not an object (evaluating 'this._lastColor.clone') 
JS: 2023-06-16 22:27:38 [error X 93][https://www.apexgruppe.com/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:19552] null is not an object (evaluating 'this._eventListener[t]') 
JS: 2023-06-16 22:42:03 [error X 3][https://www.apexgruppe.com/wp-content/plugins/elementor-pro/assets/js/editor.min.js:2:63900] Object.entries requires that input parameter not be null or undefined 
JS: 2023-06-16 23:10:34 [error X 2][https://www.apexgruppe.com/wp-content/plugins/elementor/assets/js/web-cli.min.js?ver=3.13.4:3:113639] null is not an object (evaluating 'L.classList') 
JS: 2023-06-20 21:37:20 [error X 59][https://www.apexgruppe.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.14.0:3:806416] undefined is not an object (evaluating 'this.store.find((function(T){return T.original===C})).localized') 
JS: 2023-06-20 23:26:08 [error X 29][https://www.apexgruppe.com/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.14.0:2:20078] undefined is not an object (evaluating 'e.offset().top') 
JS: 2023-06-21 00:46:42 [error X 17][https://www.apexgruppe.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.14.0:3:1110434] null is not an object (evaluating 'V.getBoundingClientRect') 
JS: 2023-06-21 19:45:01 [error X 6][https://www.apexgruppe.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.14.0:3:805908] undefined is not an object (evaluating 'T.originalEvent.key.toLowerCase') 
JS: 2023-06-21 20:18:37 [error X 1][https://www.apexgruppe.com/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.14.0:2:5687] undefined is not an object (evaluating 'this.swiper.autoplay') 
JS: 2023-06-22 22:27:56 [error X 1][https://www.apexgruppe.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.14.0:3:639877] undefined is not an object (evaluating 'this.view.container.isDesignable') 
JS: 2023-06-22 22:28:52 [error X 1][https://www.apexgruppe.com/wp-content/plugins/elementor/assets/js/web-cli.min.js?ver=3.14.0:3:107491] Routes: `panel/editor/settings` not found. 
JS: 2023-06-23 21:57:21 [error X 1][https://www.apexgruppe.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.14.0:3:601348] null is not an object (evaluating 'elementor.documents.getCurrent().id') 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

````

</details>

**Comment by nicholaszein** [comment]
Hello @rsmasi ,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
This is the expected behavior of the Popup. By default, Elementor Popups now have an **Accessibility** feature that will automatically focus on the first focusable element inside the Popup (in this case a link).

### ✅ What you can do to solve your issue:
If you don't like this behavior, you can turn off the `Accessible Navigation` option in the Popup's **`Settings` > `Advanced`** tab.

### 👍 For now, that's all we can help with. 

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
