### ISSUE TITLE
Uncaught ReferenceError: elementor is not defined on a button click

### ISSUE THREAD

**Issue by SoPH89** [elementor/elementor#22907]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I created a simple calculator in JS and when I add the code into Elementor Pro I get an error once I click on the button in the console that says: "Uncaught ReferenceError: elementor is not defined"

This is the calculator in codepen and as you can see it works well.
https://codepen.io/SoPH89/pen/yLRGjqB

What can cause this issue?
Thank you.

### Steps to reproduce

1) Create a new template
2) Add an HTML widget
3) Insert the HTML code, and the JS code between the <script> tags.
4) Add the CSS code inside the "Custom CSS" tab

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.57 (Debian)
	MySQL version: mariadb.org binary distribution v10.4.20
	PHP Version: 7.4.33
	PHP Memory Limit: 512M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2.2
	Site URL: https://mzian.co.il
	Home URL: https://mzian.co.il
	WP Multisite: No
	Max Upload Size: 100 MB
	Memory limit: 256M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: he-IL
	Timezone: 2
	Admin Email: ilanedri1@gmail.com
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor
	Version: 2.7.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: he_IL
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

== Active Plugins ==
	Autoptimize
		Version: 3.1.7
		Author: Frank Goossens (futtta)

	Elementor
		Version: 3.13.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.13.2
		Author: Elementor.com

	Hotjar
		Version: 1.0.15
		Author: Hotjar

	Imagify
		Version: 2.1.1
		Author: Imagify – Optimize Images & Convert WebP

	LTR &lt;=&gt; RTL Admin content
		Version: 0.6.2
		Author: Ronny Sherer

	MalCare WordPress Security Plugin - Malware Scanner, Cleaner, Security Firewall
		Version: 5.09
		Author: MalCare Security

	One Click Accessibility
		Version: 2.1.0
		Author: One Click Accessibility

	Rank Math SEO
		Version: 1.0.117.1
		Author: Rank Math

	Rank Math SEO PRO
		Version: 3.0.38
		Author: Rank Math

	Simple CSS
		Version: 1.1.1
		Author: Tom Usborne

	Site Kit by Google
		Version: 1.103.0
		Author: Google

	Sucuri Security - Auditing, Malware Scanner and Hardening
		Version: 1.8.39
		Author: Sucuri Inc.

	UpdraftPlus - Backup/Restore
		Version: 1.23.4
		Author: UpdraftPlus.Com, DavidAnderson

	WP Rocket
		Version: 3.13.4
		Author: WP Media

== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

	SSO
		Version: 0.3
		Author: Garth Mortensen, Mike Hansen

== שימוש באלמנטים ==
	
	archive : 8
		heading : 1
		nav-menu : 8
		posts : 8
	container : 1
		container : 2
		html : 1
	footer : 1
		form : 1
		heading : 3
		nav-menu : 1
		social-icons : 1
		text-editor : 1
		theme-site-logo : 1
	header : 2
		button : 1
		icon-list : 1
		image : 1
		nav-menu : 1
		search-form : 1
	page : 3
		button : 5
		heading : 8
		icon-list : 3
		image : 1
		spacer : 2
		star-rating : 1
		tabs : 1
		text-editor : 7
	popup : 2
		form : 2
		heading : 3
		text-editor : 1
	section : 9
		container : 5
		form : 2
		gallery : 1
		heading : 14
		icon : 3
		icon-list : 4
		image : 2
		media-carousel : 1
		spacer : 4
		text-editor : 8
		toggle : 1
	single : 3
		form : 3
		heading : 6
		post-comments : 1
		post-info : 4
		posts : 5
		share-buttons : 3
		spacer : 8
		table-of-contents : 3
		theme-post-content : 3
		theme-post-title : 3
	widget : 0
		accordion : 1
		button : 1
	wp-post : 31
		accordion : 1
		button : 22
		container : 12
		divider : 1
		form : 9
		google_maps : 23
		heading : 384
		icon : 17
		icon-list : 9
		image : 219
		shortcode : 3
		spacer : 12
		tabs : 2
		text-editor : 368
	wp-page : 5
		button : 4
		container : 1
		divider : 1
		form : 4
		heading : 22
		html : 1
		icon-box : 3
		image : 4
		image-box : 2
		nav-menu : 1
		posts : 3
		spacer : 6
		template : 1
		text-editor : 21

== הגדרות ==
	
	cpt_support: post, page
	disable_color_schemes: yes
	disable_typography_schemes: yes
	allow_tracking: yes
	css_print_method: internal
	editor_break_lines: 1
	unfiltered_files_upload: 1

== תכונות ==
	Custom Fonts: 0
	Custom Icons: 3

== אינטגרציות ==
	

== הניסויים של אלמנטור ==
	פלט DOM שעבר אופטימיזציה: פעיל
	טעינת נכסים משופרת: פעיל
	טעינת CSS משופרת: לא פעיל
	איקון פונטס בשורה: פעיל
	שיפורי נגישות: פעיל
	Additional Custom Breakpoints: פעיל
	admin_menu_rearrangement: לא פעיל כברירת מחדל
	פלקסבוקס קונטיינר: פעיל
	שדרג ספריית Swiper: לא פעיל כברירת מחדל
	גריד קונטיינר: לא פעיל כברירת מחדל
	ברירת מחדל לממשק החדש של בונה התבנית: פעיל
	עיצוב כותרת עליונה ותחתונה: פעיל
	תפריט עליון של העורך: לא פעיל כברירת מחדל
	דפי נחיתה: פעיל
	אלמנטים מקוננים: לא פעיל כברירת מחדל
	טעינה עצלה של תמונות רקע: פעיל
	מעבר עמוד: פעיל
	פתקים: פעיל
	לולאה: פעיל כברירת מחדל
	לידים: פעיל
	קפיצת גלילה: פעיל
	תפריט: לא פעיל כברירת מחדל

== יומן שינויים ==
	
Log: showing 20 of 392023-05-18 14:22:14 [info] elementor::elementor_updater Started 
2023-05-18 14:22:14 [info] אלמנטור/Upgrades - _on_each_version Start  
2023-05-18 14:22:14 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'אלמנטור',
  'from' => '3.12.1',
  'to' => '3.13.2',
)]
2023-05-18 14:22:15 [info] אלמנטור/Upgrades - _on_each_version Finished 
2023-05-18 14:22:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור',
  'from' => '3.12.1',
  'to' => '3.13.2',
)]
2023-05-19 10:37:03 [info] elementor-pro::elementor_pro_updater Started 
2023-05-19 10:37:03 [info] אלמנטור פרו/Upgrades - _on_each_version Start  
2023-05-19 10:37:03 [info] אלמנטור פרו/Upgrades - _on_each_version Finished 
2023-05-19 10:37:03 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '3.12.2',
  'to' => '3.13.1',
)]
2023-05-19 10:37:03 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '3.12.2',
  'to' => '3.13.1',
)]
2023-05-31 10:39:42 [info] elementor::elementor_updater Started 
2023-05-31 10:39:42 [info] אלמנטור/Upgrades - _on_each_version Start  
2023-05-31 10:39:43 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'אלמנטור',
  'from' => '3.13.2',
  'to' => '3.13.4',
)]
2023-05-31 10:39:43 [info] אלמנטור/Upgrades - _on_each_version Finished 
2023-05-31 10:39:43 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור',
  'from' => '3.13.2',
  'to' => '3.13.4',
)]
2023-06-10 09:31:16 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '3.13.1',
  'to' => '3.13.2',
)]
2023-06-10 09:31:20 [info] elementor-pro::elementor_pro_updater Started 
2023-06-10 09:31:20 [info] אלמנטור פרו/Upgrades - _on_each_version Start  
2023-06-10 09:31:20 [info] אלמנטור פרו/Upgrades - _on_each_version Finished 
2023-06-10 09:31:20 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '3.13.1',
  'to' => '3.13.2',
)]

JS: showing 3 of 3JS: 2023-03-22 10:57:47 [error X 6][https://mzian.co.il/wp-content/plugins/elementor/assets/js/common-modules.min.js?ver=3.11.5:2:53736] Model.isValidChild() should be implemented, please provide &#039;isValidChild&#039; functionality. 
JS: 2023-04-18 13:21:42 [error X 3][https://mzian.co.il/wp-content/plugins/elementor/assets/js/frontend.min.js:2:22374] Class extends value undefined is not a constructor or null 
JS: 2023-05-18 15:01:37 [error X 6][https://mzian.co.il/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.13.2:3:795450] Cannot read properties of undefined (reading &#039;localized&#039;) 

PHP: showing 1 of 1PHP: 2023-03-28 10:58:43 [error X 1][/home/750671.cloudwaysapps.com/rcaxpwjvjf/public_html/wp-content/plugins/elementor-pro/modules/screenshots/module.php::212] Uncaught Requests_Exception_HTTP_403: 403 Forbidden in /home/750671.cloudwaysapps.com/rcaxpwjvjf/public_html/wp-content/plugins/elementor-pro/modules/screenshots/module.php:212
Stack trace:
#0 /home/750671.cloudwaysapps.com/rcaxpwjvjf/public_html/wp-content/plugins/elementor-pro/modules/screenshots/module.php(232): ElementorPro\Modules\Screenshots\Module-&gt;is_screenshot_proxy_mode()
#1 /home/750671.cloudwaysapps.com/rcaxpwjvjf/public_html/wp-content/plugins/elementor/core/base/module.php(85): ElementorPro\Modules\Screenshots\Module-&gt;__construct()
#2 /home/750671.cloudwaysapps.com/rcaxpwjvjf/public_html/wp-content/plugins/elementor-pro/core/modules-manager.php(87): Elementor\Core\Base\Module::instance()
#3 /home/750671.cloudwaysapps.com/rcaxpwjvjf/public_html/wp-content/plugins/elementor-pro/plugin.php(363): ElementorPro\Core\Modules_Manager-&gt;__construct()
#4 /home/750671.cloudwaysapps.com/rcaxpwjvjf/public_html/wp-includes/class-wp-hook.php(308): ElementorPro\Plugin-&gt;on_elementor_init()
#5 /home/750671.cloudwa [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== אלמנטור - Compatibility Tag ==
	
	Elementor Pro: תואם

== אלמנטור פרו - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @SoPH89! 

Thank you for submitting your issue! 🙏 

I've used the code from the link you provided, and it worked for me without any issues. This means that somewhere somehow on your website there is something causing the issue you're experiencing. Although the script you're using does not wait for the DOM or jQuery to be completed, which may cause issues...

Make sure you are not including the opening and closing `<!DOCTYPE html>`, `<html>`, `<head>`, and `<body>` tags in your custom code, that you are making the CSS more specific and not generic as it currently is (add `selector` and you should be good to go), and that your script is correctly wrapped by the `<script>` tag, and does wait for the DOM to be completed before running.

Also, ensure your other plugins are not causing conflicts by temporarily deactivating them.

### ⛔ 🧩 Please note that while we do welcome bug reports, we can't provide support for 3rd-party code.

If your issue is specifically happening only when you're using a feature from a 3rd-party code, or only when the 3rd-party code is active, you'll need to contact the support for that specific software or its developers.

Make sure the code you're using is valid, and that it works as expected.

Also, it's not recommended to use the HTML widget for this sort of component. Instead, you should create a [Custom Shortcode](https://codex.wordpress.org/Shortcode_API) and then use the shortcode to display only on the frontend. This way con can [properly enqueue the script and styles using the correct methods from WordPress](https://developer.wordpress.org/reference/hooks/wp_enqueue_scripts/). Trying to run scripts within Elementor can be dangerous and can break the builder's functionality.

### 🛟 This is more of a support question, not really something we can help with here. 

👉 Please remember to check the Help Center or contact Elementor Support before submitting an issue.

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
