### ISSUE TITLE
transition

### ISSUE THREAD

**Issue by francoiscreastic** [elementor/elementor#22930]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

The progress tracker widget don't working in archive page.

In Console there is : 

```
progress-tracker.e19e2547639d7d9dac17.bundle.min.js:2 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'scroll_snap')
    at ProgressTracker.isScrollSnap (progress-tracker.e19e2547639d7d9dac17.bundle.min.js:2:4303)
    at ProgressTracker.addScrollSnapContainer (progress-tracker.e19e2547639d7d9dac17.bundle.min.js:2:4346)
    at ProgressTracker.scrollHandler (progress-tracker.e19e2547639d7d9dac17.bundle.min.js:2:4492)
    at ProgressTracker.onInit (progress-tracker.e19e2547639d7d9dac17.bundle.min.js:2:3761)
    at Module.trigger (frontend-modules.min.js?ver=3.14.1:2:20591)
    at Module.e.each.n.<computed> [as trigger] (frontend-modules.min.js?ver=3.14.1:2:20779)
    at ProgressTracker.Module (frontend-modules.min.js?ver=3.14.1:2:20877)
    at ProgressTracker.child [as constructor] (frontend-modules.min.js?ver=3.14.1:2:21142)
    at new child (frontend-modules.min.js?ver=3.14.1:2:21142)
    at new ProgressTracker (progress-tracker.e19e2547639d7d9dac17.bundle.min.js:2:3408)
```

### Steps to reproduce

1) Add progress tracker in Elementor header or in archive template
2) test the page of this page archive

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.6.14
	PHP Version: 7.4.33
	PHP Memory Limit: 512M
	PHP Max Input Vars: 250000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2.2
	Site URL: https://www.xxx.fr
	Home URL: https://www.xxx.fr
	WP Multisite: No
	Max Upload Size: 512 Mo
	Memory limit: 256M
	Max Memory limit: 512M
	Permalink Structure: /%category%/%postname%/
	Language: fr-FR
	Timezone: 1
	Admin Email: webmaster@xxxxc.fr
	Debug Mode: Inactive

== Theme ==
	Name: Astra
	Version: 4.1.5
	Author: Brainstorm Force
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: fr_FR
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

== Active Plugins ==
	Akismet Anti-Spam: Spam Protection
		Version: 5.2
		Author: Automattic - Anti Spam Team

	Astra Pro
		Version: 4.1.5
		Author: Brainstorm Force

	Complianz - Terms and Conditions
		Version: 1.2.3
		Author: Really Simple Plugins

	Complianz | GDPR/CCPA Cookie Consent
		Version: 6.4.7
		Author: Really Simple Plugins

	Disable Gutenberg
		Version: 2.9
		Author: Jeff Starr

	Elementor
		Version: 3.14.1
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.14.1
		Author: Elementor.com

	Enable Virtual Card Upload - Vcard,Vcf
		Version: 1.0.0
		Author: Amit verma

	Forminator
		Version: 1.24.1
		Author: WPMU DEV

	MouseWheel Smooth Scroll
		Version: 6.0
		Author: KubiQ

	o2switch - WpTiger
		Version: 23-02-23
		Author: 

	Optimize Database after Deleting Revisions
		Version: 5.0.110
		Author: CAGE Web Design | Rolf van Gelder, Eindhoven, The Netherlands

	Rank Math SEO
		Version: 1.0.118
		Author: Rank Math

	Ultimate Addons for Elementor
		Version: 1.36.17
		Author: Brainstorm Force

== Fonctionnalités ==
	Custom Fonts: 0
	Custom Icons: 0

== Intégrations ==
	

== Expériences d’Elementor ==
	Sortie DOM optimisée: Actif
	Amélioration du chargement des ressources: Actif
	Optimisation du chargement du CSS: Actif
	Icônes de police « inline »: Actif
	Améliorations de l’accessibilité: Actif
	Points d’arrêt personnalisés supplémentaires: Inactif
	admin_menu_rearrangement: Inactif par défaut
	Conteneur Flexbox: Actif
	Mettre à niveau la bibliothèque Swiper: Actif par défaut
	Grid Container: Inactif par défaut
	Par défaut vers le Nouveau constructeur de thème: Actif
	Editor Top Bar: Inactif par défaut
	Page d’atterrissage: Inactif
	Éléments imbriqués: Actif par défaut
	Nested Accordion: Inactif par défaut
	Chargement différé des images d’arrière-plan: Actif
	Global Style Guide: Inactif par défaut
	Transitions des pages: Inactif
	Notes: Inactif
	Boucle: Inactif
	Envois de formulaire: Inactif
	Accroche de défilement: Inactif
	Menu: Inactif par défaut

== Journal ==
	
Log: showing 20 of 322023-06-19 14:05:16 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.13.2',
  'to' => '3.14.0',
)]
2023-06-19 14:05:16 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-06-19 14:05:16 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-06-19 14:05:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.13.2',
  'to' => '3.14.0',
)]
2023-06-19 14:05:17 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.13.2',
  'to' => '3.14.0',
)]
2023-06-20 08:25:08 [info] elementor::elementor_updater Started 
2023-06-20 08:25:08 [info] Elementor/Upgrades - _on_each_version Start  
2023-06-20 08:25:08 [info] Elementor/Upgrades - _on_each_version Finished 
2023-06-20 08:25:08 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.14.0-dev5',
  'to' => '3.14.0',
)]
2023-06-20 08:25:08 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.14.0-dev5',
  'to' => '3.14.0',
)]
2023-06-27 08:22:15 [info] elementor::elementor_updater Started 
2023-06-27 08:22:15 [info] Elementor/Upgrades - _on_each_version Start  
2023-06-27 08:22:15 [info] Elementor/Upgrades - _on_each_version Finished 
2023-06-27 08:22:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.14.0',
  'to' => '3.14.1',
)]
2023-06-27 08:22:15 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.14.0',
  'to' => '3.14.1',
)]
2023-06-27 08:22:16 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.14.0',
  'to' => '3.14.1',
)]
2023-06-28 15:56:16 [info] elementor-pro::elementor_pro_updater Started 
2023-06-28 15:56:16 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-06-28 15:56:16 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-06-28 15:56:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.14.0',
  'to' => '3.14.1',
)]

JS: showing 7 of 7JS: 2023-06-03 05:15:50 [error X 2][https://www.xxx.fr/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.14.0-dev2:3:54034] Cannot read properties of undefined (reading &#039;activate&#039;) 
JS: 2023-06-03 05:40:36 [error X 12][https://www.xxx.fr/wp-content/plugins/elementor/assets/js/7fada1a61d72da6d46ab.bundle.min.js:2:7826] Cannot read properties of null (reading &#039;dataset&#039;) 
JS: 2023-06-15 09:35:11 [error X 1][https://www.xxx.fr/wp-content/plugins/ultimate-elementor/assets/min-js/uael-posts.min.js?ver=1.36.16:1:2714] e.imagesLoaded is not a function 
JS: 2023-06-19 12:32:29 [error X 1][https://www.xxx.fr/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.14.0-dev5:3:920652] elementorFrontend is not defined 
JS: 2023-06-20 08:43:44 [error X 4][https://www.xxx.fr/wp-content/plugins/elementor/assets/js/web-cli.min.js?ver=3.14.0:3:107466] Routes: `panel/editor/settings` not found. 
JS: 2023-06-28 16:42:59 [error X 1][https://www.xxx.fr/wp-admin/load-scripts.php?c=0&amp;loadchunk_0=jquery-core,jquery-migrate,utils,wp-polyfill-inert,regenerator-runtime,wp-polyfill,wp-hooks&amp;ver=6.2.2:2:31823] Cannot read properties of undefined (reading &#039;value&#039;) 
JS: 2023-06-29 06:46:45 [error X 2][https://www.xxx.fr/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.14.1:3:807522] Cannot read properties of undefined (reading &#039;localized&#039;) 

PHP: showing 3 of 3PHP: 2023-06-19 10:52:42 [notice X 9][/home/vahn0302/public_html/wp-content/plugins/elementor/app/modules/import-export/module.php::734] Trying to get property &#039;label&#039; of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-06-19 10:52:43 [notice X 9][/home/vahn0302/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-06-20 08:41:54 [notice X 2][/home/vahn0302/public_html/wp-content/plugins/elementor/core/page-assets/loader.php::87] Undefined index: version [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible
	Ultimate Addons for Elementor: Compatible

== Elementor Pro - Compatibility Tag ==
	
	Ultimate Addons for Elementor: Compatible

**Comment by nicholaszein** [comment]
Hello @francoiscreastic ! 

Thank you for submitting your issue! 🙏 

Please allow us some time to investigate it, and get back to you with our findings. 🧐 

Best regards

**Comment by francoiscreastic** [comment]
Did you investigate ?

**Comment by ioGadgets** [comment]
Hello everyone I too am now experiencing this exact same issue with the same steps involved.
I am running Wordpress 6.3.1 With the latest PHP Version.

I'm using Elementor Pro with the Hello Elementor Theme works everywhere except for the woocommerce Shop and archive/category pages.

I really hope they investigated this by now.

**Comment by Slaaap13** [comment]
Hello,

I am also experiencing the same issue on my website. 

Here are the details :
- Elementor Version: 3.16.4
- Elementor Pro Version: 3.16.2
- WordPress Version: 6.3.1
- PHP Version: 8.2.5
- Theme: Hello Elementor (child theme)

Thanks in advance for the fix :)

**Comment by pmochine** [comment]
It's still there in June 2024.

Wordpress Version: 6.5.4
Elementor Version: 3.21.8
Elementor Pro Version: 3.21.2
PHP Version 8.2.19
Theme Hello Elementor (with child theme) 3.0.2

**Comment by foxergr** [comment]
Still here. Progress tracker doesn't work on Archive Template Page with the above mentioned error

**Comment by Scythe-Kosiarz** [comment]
any hotfix?

**Comment by Scythe-Kosiarz** [comment]
bump

**Comment by Scythe-Kosiarz** [comment]
bump

**Comment by mgiannopoulos24** [comment]
I think I have a proposed fix. The patch below (file `elementor-pro/assets/js/progress-tracker.<some hash>.bundle.min.js`) prevents this crash by adding a simple check to ensure the `page` object exists before attempting to access its properties. This allows the widget to function correctly on all page types.

Original code:
```js
isScrollSnap() {
    const scrollSnapStatus = this.isEdit ? elementor.settings.page.model.attributes.scroll_snap : elementorFrontend.config.settings.page.scroll_snap;
    return 'yes' === scrollSnapStatus ? true : false;
}
```

Patch:
```js
isScrollSnap() {
    const scrollSnapStatus = this.isEdit ? elementor.settings.page.model.attributes.scroll_snap : elementorFrontend.config.settings.page && elementorFrontend.config.settings.page.scroll_snap;
    return 'yes' === scrollSnapStatus ? true : false;
  }
```

**Comment by Scythe-Kosiarz** [comment]
Code snippets fix based on @mgiannopoulos24 
```php
add_action('wp_enqueue_scripts', function () {
    $js = <<<JS
(function(){
  function ensurePageConfig(){
    try{
      var cfg = window.elementorFrontend && elementorFrontend.config;
      if (cfg && cfg.settings && !cfg.settings.page) {
        cfg.settings.page = {}; 
      }
    }catch(e){}
  } 
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', ensurePageConfig);
  } else {
    ensurePageConfig();
  }
  if (window.jQuery) {
    jQuery(window).on('elementor/frontend/init', ensurePageConfig);
  } else {
    window.addEventListener('elementor/frontend/init', ensurePageConfig);
  }
})();
JS;
    foreach (['elementor-pro-frontend', 'elementor-frontend', 'elementor-pro'] as $handle) {
        if (wp_script_is($handle, 'enqueued') || wp_script_is($handle, 'registered')) {
            wp_add_inline_script($handle, $js, 'after');
            return;
        }
    }  
    wp_add_inline_script('jquery', $js, 'after');
}, 50);
```
