### ISSUE TITLE
⛔ 🐞 Bug Report: Can't select an Elementor Landing Page in WordPress `Settings` > `Reading` > `Your homepage displays: A static page (select below)`

### ISSUE THREAD

**Issue by BoBBer446** [elementor/elementor#22950]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I created a Start / Landing Page "Template > Landingpage"
![image](https://github.com/elementor/elementor/assets/10163536/98aa2593-076c-477c-a894-a5f206e8c6c0)

But this Site is now shown on Wordpress to make them as default page:
![image](https://github.com/elementor/elementor/assets/10163536/3b828ac0-fc45-4aac-ad33-472c2a136d1c)

Feels like a Bug.

Is watch a few videos and no video explain how i can use a landing page 

### Steps to reproduce

1) Create a Start/Landing page
2) Make em published
3) try to set it as Startpage

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server - GPL v8.0.33
	PHP Version: 8.1.20
	PHP Memory Limit: 512M
	PHP Max Input Vars: 4000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2.2
	Site URL: https://meine-webseite.net
	Home URL: https://meine-webseite.net
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: [REDACTED]
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.7.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

== Active Plugins ==
	Complianz - Terms and Conditions
		Version: 1.2.4
		Author: Really Simple Plugins

	Complianz Privacy Suite (GDPR/CCPA) premium
		Version: 6.4.9
		Author: Really Simple Plugins

	Complianz Privacy Suite (GDPR/CCPA) premium
		Version: 6.5.0
		Author: Really Simple Plugins

	Elementor
		Version: 3.14.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.14.1
		Author: Elementor.com

	Local Google Fonts
		Version: 0.21.0
		Author: EverPress


== Elements Usage ==
	
	footer : 1
		heading : 1
		social-icons : 1
	header : 4
		image : 1
		nav-menu : 2
		social-icons : 1
	page : 1
		image : 1
		image-carousel : 3
		spacer : 1
		text-editor : 5
	widget : 0
		form : 1
		image-carousel : 1
	wp-page : 12
		animated-headline : 1
		form : 2
		gallery : 7
		heading : 2
		image : 32
		image-carousel : 3
		text-editor : 52
	landing-page : 0
		button : 1
		form : 1
		gallery : 1
		heading : 15
		icon : 2
		icon-box : 9
		image : 1
		nav-menu : 1
		spacer : 14
		testimonial-carousel : 2
		text-editor : 4
		toggle : 1


== Settings ==
	
	cpt_support: post, page
	allow_tracking: yes
	font_display: swap


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	
	recaptcha_v3: Active


== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Upgrade Swiper Library: Active by default
	Grid Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Editor Top Bar: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Inactive by default
	Nested Accordion: Inactive by default
	Lazy Load Background Images: Inactive by default
	Global Style Guide: Inactive by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Menu: Inactive by default


== Log ==
	
Log: showing 20 of 292023-05-30 18:19:56 [info] elementor::elementor_updater Started 
2023-05-30 18:19:56 [info] Elementor/Upgrades - _on_each_version Start  
2023-05-30 18:19:56 [info] Elementor/Upgrades - _on_each_version Finished 
2023-05-30 18:19:56 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.3',
  'to' => '3.13.4',
)]
2023-05-30 18:19:56 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.3',
  'to' => '3.13.4',
)]
2023-06-20 15:53:09 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.4',
  'to' => '3.14.0',
)]
2023-06-20 15:53:10 [info] elementor::elementor_updater Started 
2023-06-20 15:53:10 [info] Elementor/Upgrades - _on_each_version Start  
2023-06-20 15:53:10 [info] Elementor/Upgrades - _on_each_version Finished 
2023-06-20 15:53:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.4',
  'to' => '3.14.0',
)]
2023-06-27 03:52:01 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.14.0',
  'to' => '3.14.1',
)]
2023-06-27 03:52:01 [info] elementor::elementor_updater Started 
2023-06-27 03:52:01 [info] Elementor/Upgrades - _on_each_version Start  
2023-06-27 03:52:02 [info] Elementor/Upgrades - _on_each_version Finished 
2023-06-27 03:52:02 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.14.0',
  'to' => '3.14.1',
)]
2023-06-27 19:40:41 [info] elementor-pro::elementor_pro_updater Started 
2023-06-27 19:40:41 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-06-27 19:40:41 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-06-27 19:40:41 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.14.0',
  'to' => '3.14.1',
)]
2023-06-27 19:40:41 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.14.0',
  'to' => '3.14.1',
)]

PHP: showing 8 of 8PHP: 2023-06-20 15:53:10 [warning X 1][/var/www/vhosts/meinhosting.subhost.hoster.net/httpdocs/meine-webseite.net/wp-content/plugins/elementor/core/files/manager.php::111] unlink(/var/www/vhosts/meinhosting.subhost.hoster.net/httpdocs/meine-webseite.net/wp-content/uploads/elementor/css/post-4.css): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-06-20 15:53:10 [warning X 1][/var/www/vhosts/meinhosting.subhost.hoster.net/httpdocs/meine-webseite.net/wp-content/plugins/elementor/core/files/manager.php::111] unlink(/var/www/vhosts/meinhosting.subhost.hoster.net/httpdocs/meine-webseite.net/wp-content/uploads/elementor/css/global.css): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-06-20 15:53:10 [warning X 1][/var/www/vhosts/meinhosting.subhost.hoster.net/httpdocs/meine-webseite.net/wp-content/plugins/elementor/core/files/uploads-manager.php::618] rmdir(/var/www/vhosts/meinhosting.subhost.hoster.net/httpdocs/meine-webseite.net/wp-content/uploads/elementor/tmp/): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-06-21 09:40:37 [warning X 29][/var/www/vhosts/meinhosting.subhost.hoster.net/httpdocs/meine-webseite.net/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-06-21 13:10:11 [warning X 2][/var/www/vhosts/meinhosting.subhost.hoster.net/httpdocs/meine-webseite.net/wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-06-22 06:52:12 [notice X 2][/var/www/vhosts/meinhosting.subhost.hoster.net/httpdocs/meine-webseite.net/wp-content/plugins/elementor-pro/modules/custom-css/module.php::76] trim(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-06-24 19:43:50 [warning X 1][/var/www/vhosts/meinhosting.subhost.hoster.net/httpdocs/meine-webseite.net/wp-content/plugins/elementor/modules/history/revisions-manager.php::363] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-06-28 15:53:20 [error X 1][/var/www/vhosts/meinhosting.subhost.hoster.net/httpdocs/meine-webseite.net/wp-content/plugins/elementor/core/wp-api.php::26] Uncaught Error: Call to undefined function Elementor\Core\get_plugins() in /var/www/vhosts/meinhosting.subhost.hoster.net/httpdocs/meine-webseite.net/wp-content/plugins/elementor/core/wp-api.php:26
Stack trace:
#0 /var/www/vhosts/meinhosting.subhost.hoster.net/httpdocs/meine-webseite.net/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(96): Elementor\Core\Wp_Api->get_plugins()
#1 /var/www/vhosts/meinhosting.subhost.hoster.net/httpdocs/meine-webseite.net/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(58): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_with_header()
#2 /var/www/vhosts/meinhosting.subhost.hoster.net/httpdocs/meine-webseite.net/wp-content/plugins/elementor/modules/compatibility-tag/module.php(57): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_to_check()
#3 /var/www/vhosts/meinhosting.subhost.hoster.net/httpdocs/meine-webseite.net/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(148): Elementor\Modules\CompatibilityTag\Module->get_plugins_to_check()
#4 /var/www/vhosts/meinhosting.subhost.hoster.net/httpdocs/meine-webseite.net/wp-includes/class-wp-hook.php(308): Elementor\Modules\CompatibilityTag\Base_Module->Elementor\Modules\CompatibilityTag\{closure}('')
#5 /var/www/vhosts/meinhosting.subhost.hoster.net/httpdocs/meine-webseite.net/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#6 /var/www/vhosts/meinhosting.subhost.hoster.net/httpdocs/meine-webseite.net/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#7 /var/www/vhosts/meinhosting.subhost.hoster.net/httpdocs/meine-webseite.net/wp-content/plugins/elementor/modules/system-info/module.php(334): do_action('elementor/syste...')
#8 /var/www/vhosts/meinhosting.subhost.hoster.net/httpdocs/meine-webseite.net/wp-content/plugins/elementor/includes/tracker.php(241): Elementor\Modules\System_Info\Module::get_allowed_reports()
#9 /var/www/vhosts/meinhosting.subhost.hoster.net/httpdocs/meine-webseite.net/wp-content/plugins/elementor/includes/tracker.php(530): Elementor\Tracker::get_system_reports_data()
#10 /var/www/vhosts/meinhosting.subhost.hoster.net/httpdocs/meine-webseite.net/wp-content/plugins/elementor/includes/tracker.php(141): Elementor\Tracker::get_tracking_data(false)
#11 /var/www/vhosts/meinhosting.subhost.hoster.net/httpdocs/meine-webseite.net/wp-includes/class-wp-hook.php(308): Elementor\Tracker::send_tracking_data()
#12 /var/www/vhosts/meinhosting.subhost.hoster.net/httpdocs/meine-webseite.net/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#13 /var/www/vhosts/meinhosting.subhost.hoster.net/httpdocs/meine-webseite.net/wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#14 /var/www/vhosts/meinhosting.subhost.hoster.net/httpdocs/meine-webseite.net/wp-cron.php(188): do_action_ref_array('elementor/track...', Array)
#15 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 5 of 5JS: 2023-06-20 16:13:21 [error X 8][https://meine-webseite.net/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.14.0:3:639878] Cannot read properties of undefined (reading 'isDesignable') 
JS: 2023-06-21 12:54:09 [error X 1][https://meine-webseite.net/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.14.0:3:687578] this.model.isValidChild is not a function 
JS: 2023-06-21 18:57:49 [error X 1][https://meine-webseite.net/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.14.0:2:32828] id invalid type: string. 
JS: 2023-06-21 19:01:58 [error X 3][https://meine-webseite.net/wp-content/plugins/elementor/assets/js/common-modules.min.js?ver=3.14.0:2:55595] Model.isValidChild() should be implemented, please provide 'isValidChild' functionality. 
JS: 2023-06-23 06:17:50 [error X 2][https://meine-webseite.net/wp-content/plugins/elementor-pro/assets/js/form.72b77b99d67b130634d2.bundle.min.js:2:16966] Cannot read properties of undefined (reading 'children') 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==
	

				

````

</details>

**Comment by nicholaszein** [comment]
Hello @BoBBer446,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
- This is the expected behavior. Elementor Landing Pages are a Custom Post Type and cannot appear in the Pages list. This is a WordPress limitation. In WordPress `Settings` > `Reading` > `Your homepage displays: A static page (select below)` you can only select native WordPress Pages. Elementor won't change this behavior.

### ✅ What you can do to solve your issue:
- You can open your Landing Page, and save it as a template, then import the template to a normal WordPress page. Then you can use it as your homepage in WordPress settings.

### 👍 For now, that's all we can help with. 

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
