### ISSUE TITLE
Fatal error: Uncaught TypeError when creating a header template

### ISSUE THREAD

**Issue by lxbrz** [elementor/elementor#22961]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

After creating a simple header template and setting its display conditions to "Entire Site", something seems to be crashing:

`Fatal error: Uncaught TypeError: Cannot access offset of type string on string in C:\Users\alex\Local Sites\adfc\app\public\wp-content\plugins\elementor\core\page-assets\data-managers\base.php:242`

For full stacktrace see attached system info.

I encountered this error for the second time now. I asked the support about the first error and they could not help. I am just experimenting with a fresh new site, so I created a completely new local (localwp.com) environment and installed only elementor and elementor pro plugins. After creating a couple of pages and a "main menu" in wordpress, I created a header template and the same fatal error shown above occured again.

Running Elementor -> tools -> "Regenerate Files & Data" a couple of times temporarily "fixes" the problem. "Fatal error" is not displayed, but on my mobile the menu is broken:

<img src="https://github.com/elementor/elementor/assets/48349588/aad7e98a-905b-42f1-9866-cd6460001e09" width=50% height=50%>

This is of course not the case in the responsive view in Elementor.

After some time the "fatal error" just comes back, I'm not sure if it happens because I edit the header template again or because I ran  "Regenerate Files & Data" again. Running  "Regenerate Files & Data" a couple of times also seems to temporarily fix the broken burger menu an my mobile.

To be completely fair, I also should mention that I exported Site Settings (Global Colors, Global Fonts, Theme Style settings, Layout Settings, Lightbox Settings, Background Settings) from my site where the error occured for the first time and imported these site settings into the fresh environment where I encountered the same error again now.

I'm a new user of Elementor Pro and wordpress, so far it's amazing, but this error really sets me off, please help.

Larger backtrace:

```
PHP: 2023-07-03 18:03:25 [error X 2][C:\Users\alex\Local Sites\adfc\app\public\wp-content\plugins\elementor\core\page-assets\data-managers\base.php::242] Uncaught TypeError: Cannot access offset of type string on string in C:\Users\alex\Local Sites\adfc\app\public\wp-content\plugins\elementor\core\page-assets\data-managers\base.php:242
Stack trace:
#0 C:\Users\alex\Local Sites\adfc\app\public\wp-content\plugins\elementor\core\page-assets\data-managers\base.php(338): Elementor\Core\Page_Assets\Data_Managers\Base-&gt;get_saved_assets_data()
#1 C:\Users\alex\Local Sites\adfc\app\public\wp-content\plugins\elementor\includes\base\widget-base.php(1224): Elementor\Core\Page_Assets\Data_Managers\Base-&gt;__construct()
#2 C:\Users\alex\Local Sites\adfc\app\public\wp-content\plugins\elementor\includes\base\widget-base.php(1166): Elementor\Widget_Base-&gt;get_widgets_css_data_manager()
#3 C:\Users\alex\Local Sites\adfc\app\public\wp-content\plugins\elementor\includes\base\widget-base.php(1219): Elementor\Widget_Base-&gt;get_widget_css()
#4 C:\Users\alex\Local Sites\adfc\app\public\wp-content\plugins\elementor\includes\base\widget-base.php(624): Elementor\Widget_Base-&gt;print_widget_css()
#5 C:\Users\alex\Local Sites\adfc\app\public\wp-content\plugins\elementor\includes\base\widget-base.php(750): Elementor\Widget_Base-&gt;render_content()
#6 C:\Users\alex\Local Sites\adfc\app\public\wp-content\plugins\elementor\includes\base\element-base.php(449): Elementor\Widget_Base-&gt;print_content()
#7 C:\Users\alex\Local Sites\adfc\app\public\wp-content\plugins\elementor\includes\base\element-base.php(1354): Elementor\Element_Base-&gt;print_element()
#8 C:\Users\alex\Local Sites\adfc\app\public\wp-content\plugins\elementor\includes\base\element-base.php(449): Elementor\Element_Base-&gt;print_content()
#9 C:\Users\alex\Local Sites\adfc\app\public\wp-content\plugins\elementor\core\base\document.php(1711): Elementor\Element_Base-&gt;print_element()
#10 C:\Users\alex\Local Sites\adfc\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\documents\theme-document.php(418): Elementor\Core\Base\Document-&gt;print_elements(Array)
#11 C:\Users\alex\Local Sites\adfc\app\public\wp-content\plugins\elementor\includes\frontend.php(1179): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document-&gt;print_elements_with_wrapper(Array)
#12 C:\Users\alex\Local Sites\adfc\app\public\wp-content\plugins\elementor\includes\frontend.php(1074): Elementor\Frontend-&gt;get_builder_content(67)
#13 C:\Users\alex\Local Sites\adfc\app\public\wp-includes\class-wp-hook.php(308): Elementor\Frontend-&gt;apply_builder_in_content(&#039;Allgemeiner Deu...&#039;)
#14 C:\Users\alex\Local Sites\adfc\app\public\wp-includes\plugin.php(205): WP_Hook-&gt;apply_filters(&#039;Allgemeiner Deu...&#039;, Array)
#15 C:\Users\alex\Local Sites\adfc\app\public\wp-includes\post-template.php(255): apply_filters(&#039;the_content&#039;, &#039;Allgemeiner Deu...&#039;)
#16 C:\Users\alex\Local Sites\adfc\app\public\wp-content\plugins\elementor\modules\page-templates\module.php(190): the_content()
#17 [internal function]: Elementor\Modules\PageTemplates\Module-&gt;print_callback()
#18 C:\Users\alex\Local Sites\adfc\app\public\wp-content\plugins\elementor\modules\page-templates\module.php(207): call_user_func(Array)
#19 C:\Users\alex\Local Sites\adfc\app\public\wp-content\plugins\elementor\modules\page-templates\templates\canvas.php(38): Elementor\Modules\PageTemplates\Module-&gt;print_content()
#20 C:\Users\alex\Local Sites\adfc\app\public\wp-includes\template-loader.php(106): include(&#039;C:\\Users\\alex\\L...&#039;)
#21 C:\Users\alex\Local Sites\adfc\app\public\wp-blog-header.php(19): require_once(&#039;C:\\Users\\alex\\L...&#039;)
#22 C:\Users\alex\Local Sites\adfc\app\public\index.php(17): require(&#039;C:\\Users\\alex\\L...&#039;)
#23 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
``` 

### Steps to reproduce

1. Create a completely new wordpress + elementor pro environment using localwp
2. Add a couple of pages
3. Create a menu in wordpress
4. Create header template in elementor, add some style
5. Add wordpress menu widget to header, choose the created menu. 

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.43 (Win32) mod_fcgid/2.3.9a
	MySQL version: MySQL Community Server - GPL v8.0.16
	PHP Version: 8.1.9
	PHP Memory Limit: 256M
	PHP Max Input Vars: 4000
	PHP Max Post Size: 1000M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2.2
	Site URL: http://adfc.local
	Home URL: http://adfc.local
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Europe/Berlin
	Admin Email: alex@bereza.email
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.7.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.14.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.14.1
		Author: Elementor.com

== Must-Use Plugins ==
	Local WP Live Link Helper
		Version: 2.0
		Author: Flywheel

== Elements Usage ==
	
	header : 1
		container : 2
		nav-menu : 1
		text-editor : 1
		theme-site-logo : 1
	wp-page : 7
		container : 8
		heading : 1
		text-editor : 7

== Settings ==
	
	cpt_support: post, page
	allow_tracking: yes
	font_display: swap

== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active by default
	Grid Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header &amp; Footer: Active by default
	Editor Top Bar: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Inactive by default
	Nested Accordion: Inactive by default
	Lazy Load Background Images: Inactive by default
	Global Style Guide: Inactive by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Menu: Inactive by default

== Log ==
	
PHP: showing 4 of 4PHP: 2023-07-03 18:01:59 [notice X 1][C:\Users\alex\Local Sites\adfc\app\public\wp-content\plugins\elementor\core\page-assets\data-managers\base.php::242] Automatic conversion of false to array is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-03 18:02:09 [error X 5][C:\Users\alex\Local Sites\adfc\app\public\wp-content\plugins\elementor\core\page-assets\data-managers\base.php::242] Uncaught TypeError: Cannot access offset of type string on string in C:\Users\alex\Local Sites\adfc\app\public\wp-content\plugins\elementor\core\page-assets\data-managers\base.php:242
Stack trace:
#0 C:\Users\alex\Local Sites\adfc\app\public\wp-content\plugins\elementor\core\page-assets\data-managers\base.php(338): Elementor\Core\Page_Assets\Data_Managers\Base-&gt;get_saved_assets_data()
#1 C:\Users\alex\Local Sites\adfc\app\public\wp-content\plugins\elementor\includes\base\widget-base.php(1224): Elementor\Core\Page_Assets\Data_Managers\Base-&gt;__construct()
#2 C:\Users\alex\Local Sites\adfc\app\public\wp-content\plugins\elementor\includes\base\widget-base.php(1166): Elementor\Widget_Base-&gt;get_widgets_css_data_manager()
#3 C:\Users\alex\Local Sites\adfc\app\public\wp-content\plugins\elementor\includes\base\widget-base.php(1219): Elementor\Widget_Base-&gt;get_widget_css()
#4 C:\Users\alex\Local Sites\adfc\app\public\wp-content\plugins\elementor\includes\base\widget-base.php(624): Elementor\Widget_Base-&gt;print_widget_css()
#5 C:\Users\alex\Local Sites\adfc\app\public\wp-content\plugins\elementor\includes\base\widget-base.php(750): Elementor\Widget_Base-&gt;render_content()
#6 C:\Users\alex\Local Sites\adfc\app\public\wp-content\plugins\elementor\includes\base\element-base.php(449): Elementor\Widget_Base-&gt;print_content()
#7 C:\Users\alex\Local Sites\adfc\app\public\wp-content\plugins\elementor\includes\base\element-base.php(1354): Elementor\Element_Base-&gt;print_element()
#8 C:\Users\alex\Local Sites\adfc\app\public\wp-content\plugins\elementor\includes\base\element-base.php(449): Elementor\Element_Base-&gt;print_content()
#9 C:\Users\alex\Local Sites\adfc\app\public\wp-content\plugins\elementor\core\base\document.php(1711): Elementor\Element_Base-&gt;print_element()
#10 C:\Users\alex\Local Sites\adfc\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\documents\theme-document.php(418): Elementor\Core\Base\Document-&gt;print_elements(Array)
#11 C:\Users\alex\Local Sites\adfc\app\public\wp-content\plugins\elementor\includes\frontend.php(1179): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document-&gt;print_elements_with_wrapper(Array)
#12 C:\Users\alex\Local Sites\adfc\app\public\wp-content\plugins\elementor\core\base\document.php(1155): Elementor\Frontend-&gt;get_builder_content(67, false)
#13 C:\Users\alex\Local Sites\adfc\app\public\wp-content\plugins\elementor\modules\library\documents\library-document.php(76): Elementor\Core\Base\Document-&gt;get_content(false)
#14 C:\Users\alex\Local Sites\adfc\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\documents\theme-document.php(158): Elementor\Modules\Library\Documents\Library_Document-&gt;get_content(false)
#15 C:\Users\alex\Local Sites\adfc\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\documents\theme-document.php(173): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document-&gt;get_content()
#16 C:\Users\alex\Local Sites\adfc\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\classes\locations-manager.php(315): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document-&gt;print_content()
#17 C:\Users\alex\Local Sites\adfc\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\api.php(13): ElementorPro\Modules\ThemeBuilder\Classes\Locations_Manager-&gt;do_location(&#039;header&#039;)
#18 C:\Users\alex\Local Sites\adfc\app\public\wp-content\themes\hello-elementor\header.php(35): elementor_theme_do_location(&#039;header&#039;)
#19 C:\Users\alex\Local Sites\adfc\app\public\wp-includes\template.php(783): require_once(&#039;C:\\Users\\alex\\L...&#039;)
#20 C:\Users\alex\Local Sites\adfc\app\public\wp-includes\template.php(718): load_template(&#039;C:\\Users\\alex\\L...&#039;, true, Array)
#21 C:\Users\alex\Local Sites\adfc\app\public\wp-includes\general-template.php(48): locate_template(Array, true, true, Array)
#22 C:\Users\alex\Local Sites\adfc\app\public\wp-content\themes\hello-elementor\index.php(15): get_header()
#23 C:\Users\alex\Local Sites\adfc\app\public\wp-includes\template-loader.php(106): include(&#039;C:\\Users\\alex\\L...&#039;)
#24 C:\Users\alex\Local Sites\adfc\app\public\wp-blog-header.php(19): require_once(&#039;C:\\Users\\alex\\L...&#039;)
#25 C:\Users\alex\Local Sites\adfc\app\public\index.php(17): require(&#039;C:\\Users\\alex\\L...&#039;)
#26 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-03 18:03:23 [warning X 1][C:\Users\alex\Local Sites\adfc\app\public\wp-content\plugins\elementor\core\common\modules\ajax\module.php::175] Undefined array key &quot;data&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-03 18:03:25 [error X 2][C:\Users\alex\Local Sites\adfc\app\public\wp-content\plugins\elementor\core\page-assets\data-managers\base.php::242] Uncaught TypeError: Cannot access offset of type string on string in C:\Users\alex\Local Sites\adfc\app\public\wp-content\plugins\elementor\core\page-assets\data-managers\base.php:242
Stack trace:
#0 C:\Users\alex\Local Sites\adfc\app\public\wp-content\plugins\elementor\core\page-assets\data-managers\base.php(338): Elementor\Core\Page_Assets\Data_Managers\Base-&gt;get_saved_assets_data()
#1 C:\Users\alex\Local Sites\adfc\app\public\wp-content\plugins\elementor\includes\base\widget-base.php(1224): Elementor\Core\Page_Assets\Data_Managers\Base-&gt;__construct()
#2 C:\Users\alex\Local Sites\adfc\app\public\wp-content\plugins\elementor\includes\base\widget-base.php(1166): Elementor\Widget_Base-&gt;get_widgets_css_data_manager()
#3 C:\Users\alex\Local Sites\adfc\app\public\wp-content\plugins\elementor\includes\base\widget-base.php(1219): Elementor\Widget_Base-&gt;get_widget_css()
#4 C:\Users\alex\Local Sites\adfc\app\public\wp-content\plugins\elementor\includes\base\widget-base.php(624): Elementor\Widget_Base-&gt;print_widget_css()
#5 C:\Users\alex\Local Sites\adfc\app\public\wp-content\plugins\elementor\includes\base\widget-base.php(750): Elementor\Widget_Base-&gt;render_content()
#6 C:\Users\alex\Local Sites\adfc\app\public\wp-content\plugins\elementor\includes\base\element-base.php(449): Elementor\Widget_Base-&gt;print_content()
#7 C:\Users\alex\Local Sites\adfc\app\public\wp-content\plugins\elementor\includes\base\element-base.php(1354): Elementor\Element_Base-&gt;print_element()
#8 C:\Users\alex\Local Sites\adfc\app\public\wp-content\plugins\elementor\includes\base\element-base.php(449): Elementor\Element_Base-&gt;print_content()
#9 C:\Users\alex\Local Sites\adfc\app\public\wp-content\plugins\elementor\core\base\document.php(1711): Elementor\Element_Base-&gt;print_element()
#10 C:\Users\alex\Local Sites\adfc\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\documents\theme-document.php(418): Elementor\Core\Base\Document-&gt;print_elements(Array)
#11 C:\Users\alex\Local Sites\adfc\app\public\wp-content\plugins\elementor\includes\frontend.php(1179): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document-&gt;print_elements_with_wrapper(Array)
#12 C:\Users\alex\Local Sites\adfc\app\public\wp-content\plugins\elementor\includes\frontend.php(1074): Elementor\Frontend-&gt;get_builder_content(67)
#13 C:\Users\alex\Local Sites\adfc\app\public\wp-includes\class-wp-hook.php(308): Elementor\Frontend-&gt;apply_builder_in_content(&#039;Allgemeiner Deu...&#039;)
#14 C:\Users\alex\Local Sites\adfc\app\public\wp-includes\plugin.php(205): WP_Hook-&gt;apply_filters(&#039;Allgemeiner Deu...&#039;, Array)
#15 C:\Users\alex\Local Sites\adfc\app\public\wp-includes\post-template.php(255): apply_filters(&#039;the_content&#039;, &#039;Allgemeiner Deu...&#039;)
#16 C:\Users\alex\Local Sites\adfc\app\public\wp-content\plugins\elementor\modules\page-templates\module.php(190): the_content()
#17 [internal function]: Elementor\Modules\PageTemplates\Module-&gt;print_callback()
#18 C:\Users\alex\Local Sites\adfc\app\public\wp-content\plugins\elementor\modules\page-templates\module.php(207): call_user_func(Array)
#19 C:\Users\alex\Local Sites\adfc\app\public\wp-content\plugins\elementor\modules\page-templates\templates\canvas.php(38): Elementor\Modules\PageTemplates\Module-&gt;print_content()
#20 C:\Users\alex\Local Sites\adfc\app\public\wp-includes\template-loader.php(106): include(&#039;C:\\Users\\alex\\L...&#039;)
#21 C:\Users\alex\Local Sites\adfc\app\public\wp-blog-header.php(19): require_once(&#039;C:\\Users\\alex\\L...&#039;)
#22 C:\Users\alex\Local Sites\adfc\app\public\index.php(17): require(&#039;C:\\Users\\alex\\L...&#039;)
#23 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

**Comment by lxbrz** [comment]
I have retraced and written down the steps to reproduce this error from a completely new install of WP and elementor:

- create new site using local (localwp)
- install and activate hello theme
- remove all other themes (twenty twenty three or so, etc.)
- install elementor plugin
- exit from elementor generated page
- delete all pages
- activate flexboxes feature
- install and activate elementor pro plugin

---------------------------------------------------

System Info Log already shows some error:

```
PHP: 2023-07-04 08:17:37 [notice X 1][C:\Users\alex\Local Sites\test\app\public\wp-content\plugins\elementor\core\upgrade\manager.php::63] version_compare(): Passing null to parameter #1 ($version1) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
```
----------------------------------------------------

- go to appearance -> menu, create a "main menu"
- go to pages, create three pages, edit all of them with elementor, add a simple container with a single text editor widget to all of them
- go to appearance -> menu, add all 3 new pages to menu, make one page a sub item of the other
- go to theme builder, create empty header template, add container, add text in container, add second container (below first one), this container is left to right, add site logo, upload a site logo (.png), add wordpress menu widget 
- set image max width to 200 px, set parent container to space between
- publish, condition is entire site
- create live link in local (localwp.com)
- visit site on mobile, see that menu is broken (same as in screenshot above)

----------------------------------------------------

By now system log shows these errors:

```
PHP: showing 4 of 4
PHP: 2023-07-04 08:17:37 [notice X 1][C:\Users\alex\Local Sites\test\app\public\wp-content\plugins\elementor\core\upgrade\manager.php::63] version_compare(): Passing null to parameter #1 ($version1) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-04 08:26:45 [warning X 1][C:\Users\alex\Local Sites\test\app\public\wp-content\plugins\elementor\core\common\modules\ajax\module.php::175] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-04 08:28:43 [warning X 1][C:\Users\alex\Local Sites\test\app\public\wp-content\plugins\elementor\includes\managers\image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-04 08:29:01 [warning X 1][C:\Users\alex\Local Sites\test\app\public\wp-content\plugins\elementor\modules\history\revisions-manager.php::363] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
JS: showing 1 of 1
JS: 2023-07-04 08:32:57 [error X 1][http://test.local/wp-admin/load-scripts.php?c=1&loadchunk_0=jquery-core,jquery-migrate,utils,moxiejs,plupload&ver=6.2.2:2:31823] Cannot read properties of undefined (reading 'value') 
```

------------------------------------------------------

- Go to elementor -> tools -> Regenerate Files & Data
- Refresh page on mobile, hamburger menu is fixed
- Refresh page again, now the error that is described above surfaces (fatal error: uncaught type error)

--------------------------------------------------------

System info log now is:

```
PHP: showing 5 of 5
PHP: 2023-07-04 08:17:37 [notice X 1][C:\Users\alex\Local Sites\test\app\public\wp-content\plugins\elementor\core\upgrade\manager.php::63] version_compare(): Passing null to parameter #1 ($version1) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-04 08:26:45 [warning X 1][C:\Users\alex\Local Sites\test\app\public\wp-content\plugins\elementor\core\common\modules\ajax\module.php::175] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-04 08:28:43 [warning X 1][C:\Users\alex\Local Sites\test\app\public\wp-content\plugins\elementor\includes\managers\image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-04 08:29:01 [warning X 1][C:\Users\alex\Local Sites\test\app\public\wp-content\plugins\elementor\modules\history\revisions-manager.php::363] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-04 08:37:11 [error X 1][C:\Users\alex\Local Sites\test\app\public\wp-content\plugins\elementor\core\page-assets\data-managers\base.php::242] Uncaught TypeError: Cannot access offset of type string on string in C:\Users\alex\Local Sites\test\app\public\wp-content\plugins\elementor\core\page-assets\data-managers\base.php:242
Stack trace:
#0 C:\Users\alex\Local Sites\test\app\public\wp-content\plugins\elementor\core\page-assets\data-managers\base.php(338): Elementor\Core\Page_Assets\Data_Managers\Base->get_saved_assets_data()
#1 C:\Users\alex\Local Sites\test\app\public\wp-content\plugins\elementor\includes\base\widget-base.php(1224): Elementor\Core\Page_Assets\Data_Managers\Base->__construct()
#2 C:\Users\alex\Local Sites\test\app\public\wp-content\plugins\elementor\includes\base\widget-base.php(1166): Elementor\Widget_Base->get_widgets_css_data_manager()
#3 C:\Users\alex\Local Sites\test\app\public\wp-content\plugins\elementor\includes\base\widget-base.php(1219): Elementor\Widget_Base->get_widget_css()
#4 C:\Users\alex\Local Sites\test\app\public\wp-content\plugins\elementor\includes\base\widget-base.php(624): Elementor\Widget_Base->print_widget_css()
#5 C:\Users\alex\Local Sites\test\app\public\wp-content\plugins\elementor\includes\base\widget-base.php(750): Elementor\Widget_Base->render_content()
#6 C:\Users\alex\Local Sites\test\app\public\wp-content\plugins\elementor\includes\base\element-base.php(449): Elementor\Widget_Base->print_content()
#7 C:\Users\alex\Local Sites\test\app\public\wp-content\plugins\elementor\includes\base\element-base.php(1354): Elementor\Element_Base->print_element()
#8 C:\Users\alex\Local Sites\test\app\public\wp-content\plugins\elementor\includes\base\element-base.php(449): Elementor\Element_Base->print_content()
#9 C:\Users\alex\Local Sites\test\app\public\wp-content\plugins\elementor\core\base\document.php(1711): Elementor\Element_Base->print_element()
#10 C:\Users\alex\Local Sites\test\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\documents\theme-document.php(418): Elementor\Core\Base\Document->print_elements(Array)
#11 C:\Users\alex\Local Sites\test\app\public\wp-content\plugins\elementor\includes\frontend.php(1179): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document->print_elements_with_wrapper(Array)
#12 C:\Users\alex\Local Sites\test\app\public\wp-content\plugins\elementor\core\base\document.php(1155): Elementor\Frontend->get_builder_content(29, false)
#13 C:\Users\alex\Local Sites\test\app\public\wp-content\plugins\elementor\modules\library\documents\library-document.php(76): Elementor\Core\Base\Document->get_content(false)
#14 C:\Users\alex\Local Sites\test\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\documents\theme-document.php(158): Elementor\Modules\Library\Documents\Library_Document->get_content(false)
#15 C:\Users\alex\Local Sites\test\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\documents\theme-document.php(173): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document->get_content()
#16 C:\Users\alex\Local Sites\test\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\classes\locations-manager.php(315): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document->print_content()
#17 C:\Users\alex\Local Sites\test\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\api.php(13): ElementorPro\Modules\ThemeBuilder\Classes\Locations_Manager->do_location('header')
#18 C:\Users\alex\Local Sites\test\app\public\wp-content\themes\hello-elementor\header.php(35): elementor_theme_do_location('header')
#19 C:\Users\alex\Local Sites\test\app\public\wp-includes\template.php(783): require_once('C:\\Users\\alex\\L...')
#20 C:\Users\alex\Local Sites\test\app\public\wp-includes\template.php(718): load_template('C:\\Users\\alex\\L...', true, Array)
#21 C:\Users\alex\Local Sites\test\app\public\wp-includes\general-template.php(48): locate_template(Array, true, true, Array)
#22 C:\Users\alex\Local Sites\test\app\public\wp-content\themes\hello-elementor\index.php(15): get_header()
#23 C:\Users\alex\Local Sites\test\app\public\wp-includes\template-loader.php(106): include('C:\\Users\\alex\\L...')
#24 C:\Users\alex\Local Sites\test\app\public\wp-blog-header.php(19): require_once('C:\\Users\\alex\\L...')
#25 C:\Users\alex\Local Sites\test\app\public\index.php(17): require('C:\\Users\\alex\\L...')
#26 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
JS: showing 1 of 1
JS: 2023-07-04 08:32:57 [error X 1][http://test.local/wp-admin/load-scripts.php?c=1&loadchunk_0=jquery-core,jquery-migrate,utils,moxiejs,plupload&ver=6.2.2:2:31823] Cannot read properties of undefined (reading 'value') 
```

**Comment by nicholaszein** [comment]
Hello @lxbrz! 

Thank you for submitting your issue! 🙏 

Please allow us some time to investigate it, and get back to you with our findings. 🧐 

Best regards

**Comment by lxbrz** [comment]
Thanks @nicholaszein . In the meantime a guy named Rabina Silwal from "Tier 2 Support" investigated the test site that I set using the step described in previous comment. He tried to turn off all experimental features and found that turning off "Experiment feature > Hello Theme Header & Footer" silenced the crash. There is apparently no fatal error anymore, but the site renders completely wrong. The elementor WYSIWYG editor renders the site ok, but in the browser and on my mobile it is rendered incorrectly. Please see:

In Elementor:

![Screenshot 2023-07-05 195649](https://github.com/elementor/elementor/assets/48349588/d5c67d9b-1211-4ba0-abb3-6e32f08934a1)

In the browser on desktop:

![Screenshot 2023-07-05 195719](https://github.com/elementor/elementor/assets/48349588/cd9c3604-7f44-4a18-88b3-faa07f7f2ed4)

On mobile:

<img src="https://github.com/elementor/elementor/assets/48349588/25d7dbc3-606d-4180-b096-c0da8d45e95e" width=50% height=50%>

So the crash seems gone turning that thing off, but the rendering still comes out wrong as it was the case before the crash happens.

**Comment by lxbrz** [comment]
I digged around a bit myself, although I must admit I have no clue about php and so on. I found in `app/sql/local.sql` of my wordpress folder the line:

```
INSERT INTO `wp_options` VALUES (480,'_elementor_assets_data','','yes');
```

And I printed to error log the values of

```
		error_log(print_r($assets_data, TRUE));
		error_log(print_r($content_type, TRUE));
```

from within the function `get_saved_assets_data()` in `elementor\core\page-assets\data-managers\base.php` where the crash occurs on 

$assets_data[ $content_type ] = [];

This returned:

```
[07-Jul-2023 16:57:28 UTC] 
[07-Jul-2023 16:57:28 UTC] css
```

in the error log. So it seems to be indexing an empty string with the value `css` and then crash with the described error "Fatal error: Uncaught TypeError: Cannot access offset of type string on string"

**Comment by nicholaszein** [comment]
Hi @lxbrz,

thanks for the updates and detailed information! We really appreciate it!

I've labeled this issue and our team will take a look at it. If there is indeed a problem, they'll work on fixing it. We can't say exactly when it'll be sorted out, but we kindly ask for your patience. Thanks for understanding!

Best regards

**Comment by WeirdBob** [comment]
Hi,
I had the exact same issue. I had to add this check in base.php l242 to make it work again: 
```		
if ( ! isset($asset_data)) {
	$assets_data = [];
}
```
which doesn't make a lot of sense since the get_option should return an empty array already if not set.
I have no idea how it happened, nothing new apart from creating/editing pages in the site, but maybe this can help some others with the bug while waiting for a fix.

**Comment by digitalmurph** [comment]
Hello, has there been any solutution for this please? I have the exact same issue. Help!
Thanks

**Comment by alieberweb** [comment]
Hello, just ran into the same problem. Any news on this issue?
Thank you.

**Comment by thd-creative** [comment]
Hi, I ran into the same problem when using local-wp and enabled the live link.
The wp-admin still worked, but the preview of all pages of the site were having this fatal error.
I resolved it by recreating/regenerating elementor CSS files (elementor > tools > general > recreate/regenerate CSS and data).

**Comment by JPabloPena** [comment]
Hello, has anyone found the solution to this problem?
