### ISSUE TITLE
⛔ 🐞 Bug Report: Video Playlist Widget is missing from Elementor Pro 3.14.1

### ISSUE THREAD

**Issue by Mulli** [elementor/elementor#23057]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Video Playlist Widget is missing from Elementor Pro 3.14.1
Its a new website, I have deactivated other plugins, and tested on Twenty* template
Instead of Hello Child that I use

### Steps to reproduce

1. Just install WP 6.2.2, Elemetor & Pro 3.14.1
2. Open a post template
3. Try to locate Video Playlist
4. BOOOM - its not showing

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.3.39
	PHP Version: 7.4.33
	PHP Memory Limit: 512M
	PHP Max Input Vars: 10240
	PHP Max Post Size: 24M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2.2
	Site URL: https://new2.snepling.co.il
	Home URL: https://new2.snepling.co.il
	WP Multisite: No
	Max Upload Size: 24 MB
	Memory limit: 1024M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: he-IL
	Timezone: 0
	Admin Email: [REDACTED]
	Debug Mode: Active

== Theme ==
	Name: Twenty Twenty-Three
	Version: 1.1
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: he_IL
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 6.1.7
		Author: WP Engine

	Classic Editor
		Version: 1.6.3
		Author: WordPress Contributors

	Duplicate Page
		Version: 4.5.2
		Author: mndpsingh287

	Elementor
		Version: 3.14.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.14.1
		Author: Elementor.com

	WordPress Importer
		Version: 0.8.1
		Author: wordpressdotorg

	Yoast SEO
		Version: 20.11
		Author: Team Yoast


== שימוש באלמנטים ==
	
	archive : 1
		archive-posts : 1
		form : 1
		heading : 2
		theme-archive-title : 1
	footer : 1
		button : 4
		heading : 5
		icon-list : 4
	header : 1
		icon-list : 1
		image : 1
		nav-menu : 1
	section : 23
		button : 2
		form : 2
		heading : 14
		icon-box : 4
		icon-list : 1
		image : 17
		jet-animated-text : 11
		lottie : 4
		text-editor : 5
	wp-page : 6
		button : 2
		form : 1
		gallery : 2
		heading : 14
		icon-list : 2
		image : 3
		jet-animated-box : 10
		menu-anchor : 1
		posts : 1
		slides : 2
		template : 1
		testimonial-carousel : 1
		text-editor : 5
		toggle : 1
		video-playlist : 1
	single-post : 2
		breadcrumbs : 2
		form : 2
		gallery : 3
		heading : 6
		post-navigation : 2
		posts : 2
		theme-post-content : 2
		theme-post-title : 2


== הגדרות ==
	
	cpt_support: post, page
	allow_tracking: yes
	meta_generator_tag: 1


== תכונות ==
	Custom Fonts: 0
	Custom Icons: 0

== אינטגרציות ==
	


== הניסויים של אלמנטור ==
	פלט DOM שעבר אופטימיזציה: פעיל כברירת מחדל
	טעינת נכסים משופרת: פעיל כברירת מחדל
	טעינת CSS משופרת: פעיל כברירת מחדל
	איקון פונטס בשורה: לא פעיל כברירת מחדל
	שיפורי נגישות: פעיל כברירת מחדל
	Additional Custom Breakpoints: פעיל כברירת מחדל
	admin_menu_rearrangement: לא פעיל כברירת מחדל
	פלקסבוקס קונטיינר: לא פעיל כברירת מחדל
	שדרג ספריית Swiper: פעיל
	גריד קונטיינר: לא פעיל כברירת מחדל
	ברירת מחדל לממשק החדש של בונה התבנית: פעיל כברירת מחדל
	תפריט עליון של העורך: לא פעיל כברירת מחדל
	דפי נחיתה: פעיל כברירת מחדל
	אלמנטים מקוננים: לא פעיל כברירת מחדל
	Nested Accordion: לא פעיל כברירת מחדל
	טעינה עצלה של תמונות רקע: לא פעיל כברירת מחדל
	הגדרות עיצוב גלובליות: לא פעיל כברירת מחדל
	מעבר עמוד: פעיל כברירת מחדל
	פתקים: פעיל כברירת מחדל
	לולאה: פעיל כברירת מחדל
	לידים: פעיל כברירת מחדל
	קפיצת גלילה: פעיל כברירת מחדל
	תפריט: לא פעיל כברירת מחדל


== יומן שינויים ==
	
Log: showing 20 of 372023-06-20 03:47:51 [info] elementor::elementor_updater Started 
2023-06-20 03:47:51 [info] אלמנטור/Upgrades - _on_each_version Start  
2023-06-20 03:47:51 [info] אלמנטור/Upgrades - _on_each_version Finished 
2023-06-20 03:47:51 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור',
  'from' => '3.13.4',
  'to' => '3.14.0',
)]
2023-06-20 03:47:51 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'אלמנטור',
  'from' => '3.13.4',
  'to' => '3.14.0',
)]
2023-06-26 03:47:30 [info] elementor-pro::elementor_pro_updater Started 
2023-06-26 03:47:30 [info] אלמנטור פרו/Upgrades - _on_each_version Start  
2023-06-26 03:47:30 [info] אלמנטור פרו/Upgrades - _on_each_version Finished 
2023-06-26 03:47:30 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '3.13.2',
  'to' => '3.14.0',
)]
2023-06-26 03:47:30 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '3.13.2',
  'to' => '3.14.0',
)]
2023-06-27 03:49:39 [info] elementor::elementor_updater Started 
2023-06-27 03:49:39 [info] אלמנטור/Upgrades - _on_each_version Start  
2023-06-27 03:49:40 [info] אלמנטור/Upgrades - _on_each_version Finished 
2023-06-27 03:49:40 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור',
  'from' => '3.14.0',
  'to' => '3.14.1',
)]
2023-06-27 03:49:40 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'אלמנטור',
  'from' => '3.14.0',
  'to' => '3.14.1',
)]
2023-06-28 03:48:50 [info] elementor-pro::elementor_pro_updater Started 
2023-06-28 03:48:50 [info] אלמנטור פרו/Upgrades - _on_each_version Start  
2023-06-28 03:48:50 [info] אלמנטור פרו/Upgrades - _on_each_version Finished 
2023-06-28 03:48:50 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '3.14.0',
  'to' => '3.14.1',
)]
2023-06-28 03:48:50 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '3.14.0',
  'to' => '3.14.1',
)]

PHP: showing 4 of 4PHP: 2023-06-08 21:37:51 [notice X 5][../wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-06-11 13:23:17 [error X 1][../wp-content/plugins/elementor/core/wp-api.php::26] Uncaught Error: Call to undefined function Elementor\Core\get_plugins() in ../wp-content/plugins/elementor/core/wp-api.php:26
Stack trace:
#0 ../wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(96): Elementor\Core\Wp_Api->get_plugins()
#1 ../wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(58): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_with_header()
#2 ../wp-content/plugins/elementor/modules/compatibility-tag/module.php(57): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_to_check()
#3 ../wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(148): Elementor\Modules\CompatibilityTag\Module->get_plugins_to_check()
#4 ../wp-includes/class-wp-hook.php(308): Elementor\Modules\CompatibilityTag\Base_Module->Elementor\Modules\CompatibilityTag\{closure}('')
#5 /ho [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-06-17 05:36:21 [notice X 2][../wp-content/plugins/elementor-pro/modules/dynamic-tags/tags/post-featured-image.php::36] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-13 23:54:47 [notice X 14][../wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-gallery.php::36] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 1 of 1JS: 2023-07-13 15:23:10 [error X 2][https://new2.snepling.co.il/wp-includes/js/jquery/jquery.js?ver=3.6.4:4095:3] Cannot read properties of undefined (reading 'value')




== אלמנטור - Compatibility Tag ==
	
	Elementor Pro: תאימות לא הוגדרה

== אלמנטור פרו - Compatibility Tag ==
	

				

````

</details>

**Comment by nicholaszein** [comment]
Hello @Mulli,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
- We tested with the latest stable versions of both Elementor (3.14.1) and Elementor Pro (3.14.1) and the Video Playlist widget is available in any instance of the editor.

![image](https://github.com/elementor/elementor/assets/113993460/4cff18aa-1773-43a0-a7e7-b6cb43afb871)


### ✅ What you can do to solve your issue:
- Please troubleshoot your website by temporarily deactivating all plugins except Elementor and Elementor Pro, and by switching to the Hello Elementor theme. Make sure to backup your website before proceeding, or testing on a staging environment.
- If you still can't see the widget, contact Elementor support, since GitHub issues are reserved only for Bug Reports.

### 👍 For now, that's all we can help with. 

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
