### ISSUE TITLE
⛔ 🧩 🛟 Support Request: WooCommerce Measurement Price Calculator does not work with Elementor after migrating from staging environment

### ISSUE THREAD

**Issue by StudioAvatar** [elementor/elementor#23089]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I am using elementor pro license. I have installed elementor to the latest version. I'm also using the hello template, which is also updated to the latest version. On the online store created on Wordpress, I used the woocommerce price measurement calculator plugin to configure the products. In the draft version, the plug-in worked fine. After moving to the main domain and hosting and updating elementor to the latest version, the plugin stopped working properly.

Currently, the plugin is updated to the latest version 3.22.0 and elementor and elementor pro 3.14.1

At this point, the plugin allows you to set all the values important for the product configuration, but after entering the number of meters of ceramic tiles the customer needs, the plugin does not react, does not recalculate and does not change the price of the product.

Could someone help me solve the problem?

### Steps to reproduce

1. I made a copy of the old page
2. I disabled the plugins that functioned on the old template (the site previously functioned with WPBakery Page Builder)
3. I uninstalled the template that worked before (BeTheme)
4. Installed elementor and elementor pro.
5. I used a demo template from the elementor library
6. I have enabled the woocommerce measurement price calculator plugin
6. I prepared the website, bookmarks and product card template.
7. Everything after setup worked until I moved the site to a new domain and updated elementor to the latest version.
8. It turned out that the measurement price calculator plugin did not work in the latest version. I initially updated it to version 3.21.1, but after a few days I noticed that the plugin is in version 3.22.0 and updated to that. The problem has not resolved.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: nginx
	MySQL version: Percona Server (GPL), Release '43', Revision 'c1b94a6cfd7' v5.7.40-43
	PHP Version: 7.4.33
	PHP Memory Limit: 2G
	PHP Max Input Vars: 20000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2.2
	Site URL: https://www.sklep.estile.pl
	Home URL: https://www.sklep.estile.pl
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 256M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: pl-PL
	Timezone: Europe/Warsaw
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.8.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: pl_PL
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.14.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.14.1
		Author: Elementor.com

	WooCommerce
		Version: 7.8.2
		Author: Automattic

	WooCommerce Measurement Price Calculator
		Version: 3.22.0
		Author: SkyVerge


== Must-Use Plugins ==
	Integrations with JDM.pl hosting
		Version: 4.0.4
		Author: JDM


== Wykorzystanie elementów ==
	
	footer : 1
		divider : 1
		heading : 15
		icon-list : 9
		image : 3
		text-editor : 3
	header : 3
		icon-list : 4
		jet-wishlist-count-button : 4
		nav-menu : 4
		search-form : 2
		theme-site-logo : 4
		woocommerce-menu-cart : 4
	page : 4
		call-to-action : 1
		divider : 4
		heading : 11
		icon-box : 4
		icon-list : 4
		image : 5
		image-box : 4
		image-carousel : 2
		shortcode : 3
		spacer : 3
		text-editor : 4
		woocommerce-cart : 1
		woocommerce-checkout-page : 1
		woocommerce-my-account : 1
	section : 3
		eael-login-register : 2
		jet-smart-filters-range : 1
		jet-smart-filters-search : 1
		jet-smart-filters-select : 1
		loop-grid : 1
		text-editor : 3
	widget : 0
		jet-smart-filters-search : 1
	wp-post : 2
		icon-list : 4
		jet-wishlist-count-button : 4
		nav-menu : 4
		search-form : 1
		theme-site-logo : 4
		woocommerce-menu-cart : 4
	wp-page : 22
		button : 10
		call-to-action : 1
		divider : 9
		eael-adv-tabs : 2
		form : 2
		heading : 24
		icon : 2
		icon-box : 17
		image : 3
		jet-wishlist : 1
		login : 1
		loop-carousel : 5
		lottie : 2
		slides : 2
		social-icons : 2
		spacer : 7
		text-editor : 34
		toggle : 1
		woocommerce-cart : 1
		woocommerce-my-account : 1
	single-post : 1
		spacer : 4
		theme-post-content : 2
		theme-post-featured-image : 2
		theme-post-title : 2
	search-results : 1
		search-form : 1
		theme-archive-title : 1
		wc-archive-products : 1
	product-archive : 78
		heading : 12
		jet-smart-filters-range : 140
		jet-smart-filters-search : 140
		jet-smart-filters-select : 140
		loop-grid : 140
		search-form : 3
		text-editor : 425
		theme-archive-title : 61
		woocommerce-archive-description : 140
		woocommerce-products : 3
	loop-item : 1
		jet-wishlist-button : 1
		theme-post-featured-image : 1
		woocommerce-product-price : 1
		woocommerce-product-title : 1


== Ustawienia ==
	
	allow_tracking: yes
	unfiltered_files_upload: 1


== Składniki oferty ==
	Custom Fonts: 0
	Custom Icons: 0

== Integracje ==
	
	woocommerce: Aktywny


== Eksperymenty z Elementorem ==
	Zoptymalizowany wynik DOM: Domyślnie aktywne
	Ulepszone ładowanie zasobów: Domyślnie aktywne
	Poprawione ładowanie CSS: Domyślnie aktywne
	Czcionka ikon: Domyślnie nieaktywne
	Ulepszenia w zakresie dostępności: Domyślnie aktywne
	Dodatkowe niestandardowe punkty zmiany: Domyślnie aktywne
	admin_menu_rearrangement: Domyślnie nieaktywne
	Flexbox Container: Domyślnie nieaktywne
	Upgrade Swiper Library: Domyślnie nieaktywne
	Grid Container: Domyślnie nieaktywne
	Default to New Theme Builder: Domyślnie aktywne
	Hello Theme Header & Footer: Domyślnie aktywne
	Editor Top Bar: Domyślnie nieaktywne
	Strony docelowe: Domyślnie aktywne
	Elementy zagnieżdżone: Domyślnie nieaktywne
	Nested Accordion: Domyślnie nieaktywne
	Leniwe ładowanie obrazów tła: Domyślnie nieaktywne
	Global Style Guide: Domyślnie nieaktywne
	Page Transitions: Domyślnie aktywne
	Notes: Domyślnie aktywne
	Loop: Domyślnie aktywne
	Form Submissions: Domyślnie aktywne
	Scroll Snap: Domyślnie aktywne
	Menu: Domyślnie nieaktywne


== Dziennik ==
	
PHP: showing 9 of 9PHP: 2023-06-05 14:18:28 [warning X 1][../wp-content/plugins/elementor/core/files/file-types/svg.php::234] simplexml_load_file(): I/O warning : failed to load external entity "https://www.estile.jdmsite.com/wp-content/uploads/2023/06/4_home_doctors_online_consultation-chevron_up.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-06-11 17:36:11 [notice X 31][../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined index: condition_type [array (
  'trace' => '
#0: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: ../wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2023-06-15 19:17:14 [notice X 1620][../wp-content/plugins/elementor-pro/modules/woocommerce/module.php::381] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-06-17 19:43:48 [warning X 1][../wp-content/plugins/elementor-pro/modules/woocommerce/module.php::1458] A non-numeric value encountered [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-06-20 13:55:02 [error X 6][../wp-content/plugins/elementor-pro/modules/screenshots/module.php::229] Uncaught WpOrg\Requests\Exception\Http\Status403: 403 Forbidden in ../wp-content/plugins/elementor-pro/modules/screenshots/module.php:229
Stack trace:
#0 ../wp-content/plugins/elementor-pro/modules/screenshots/module.php(264): ElementorPro\Modules\Screenshots\Module->is_screenshot_proxy_mode(Array)
#1 ../wp-content/plugins/elementor/core/base/module.php(85): ElementorPro\Modules\Screenshots\Module->__construct()
#2 ../wp-content/plugins/elementor-pro/core/modules-manager.php(87): Elementor\Core\Base\Module::instance()
#3 ../wp-content/plugins/elementor-pro/plugin.php(369): ElementorPro\Core\Modules_Manager->__construct()
#4 ../wp-includes/class-wp-hook.php(308): ElementorPro\Plugin->on_elementor_init('')
#5 ../wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#6 ../wp-includes/plugin.php(517): WP_Ho [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-06-22 16:03:34 [notice X 2][../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::171] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-06-24 13:14:44 [notice X 6][../wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-06-26 14:47:58 [error X 6][../wp-content/plugins/elementor-pro/modules/screenshots/module.php::229] Uncaught WpOrg\Requests\Exception\Http\Status403: 403 Forbidden in ../wp-content/plugins/elementor-pro/modules/screenshots/module.php:229
Stack trace:
#0 ../wp-content/plugins/elementor-pro/modules/screenshots/module.php(264): ElementorPro\Modules\Screenshots\Module->is_screenshot_proxy_mode(Array)
#1 ../wp-content/plugins/elementor/core/base/module.php(85): ElementorPro\Modules\Screenshots\Module->__construct()
#2 ../wp-content/plugins/elementor-pro/core/modules-manager.php(88): Elementor\Core\Base\Module::instance()
#3 ../wp-content/plugins/elementor-pro/plugin.php(369): ElementorPro\Core\Modules_Manager->__construct()
#4 ../wp-includes/class-wp-hook.php(308): ElementorPro\Plugin->on_elementor_init('')
#5 ../wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#6 ../wp-includes/plugin.php(517): WP_Ho [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-05 01:14:38 [notice X 17][../wp-content/plugins/elementor/core/page-assets/loader.php::87] Undefined index: version [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 14 of 14JS: 2023-06-14 18:51:36 [error X 1][https://www.estile.jdmsite.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view26150") has already been destroyed and cannot be used. 
JS: 2023-06-15 15:32:47 [error X 1][https://www.estile.jdmsite.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view3922") has already been destroyed and cannot be used. 
JS: 2023-06-15 15:51:27 [error X 1][https://www.estile.jdmsite.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view26129") has already been destroyed and cannot be used. 
JS: 2023-06-15 15:52:58 [error X 1][https://www.estile.jdmsite.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view27850") has already been destroyed and cannot be used. 
JS: 2023-06-15 15:53:31 [error X 1][https://www.estile.jdmsite.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view28393") has already been destroyed and cannot be used. 
JS: 2023-06-15 15:54:03 [error X 5][https://www.estile.jdmsite.com/wp-content/plugins/elementor/assets/js/common-modules.min.js?ver=3.13.4:2:55595] Model.isValidChild() should be implemented, please provide 'isValidChild' functionality. 
JS: 2023-06-15 15:54:26 [error X 1][https://www.estile.jdmsite.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view34460") has already been destroyed and cannot be used. 
JS: 2023-06-15 15:54:41 [error X 1][https://www.estile.jdmsite.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view35096") has already been destroyed and cannot be used. 
JS: 2023-06-15 15:54:58 [error X 1][https://www.estile.jdmsite.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view35729") has already been destroyed and cannot be used. 
JS: 2023-06-15 17:35:37 [error X 2][https://www.estile.jdmsite.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.13.4:3:1097282] Cannot read properties of null (reading 'getBoundingClientRect') 
JS: 2023-06-18 17:35:19 [error X 1][https://www.estile.jdmsite.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view7061") has already been destroyed and cannot be used. 
JS: 2023-06-22 09:33:42 [error X 3][https://www.estile.pl/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.13.4:3:304714] Cannot read properties of undefined (reading 'id') 
JS: 2023-06-23 15:29:11 [error X 16][https://www.estile.pl/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.14.0:2:7603] undefined is not an object (evaluating 'event?.target?.classList.contains') 
JS: 2023-06-25 07:50:33 [error X 11][https://www.estile.pl/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.14.0:2:7603] Cannot read properties of undefined (reading 'contains') 

Log: showing 20 of 202023-06-23 16:03:49 [info] elementor::elementor_updater Started 
2023-06-23 16:03:49 [info] Elementor/Upgrades - _on_each_version Start  
2023-06-23 16:03:50 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.4',
  'to' => '3.14.0',
)]
2023-06-23 16:03:50 [info] Elementor/Upgrades - _on_each_version Finished 
2023-06-23 16:03:50 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.4',
  'to' => '3.14.0',
)]
2023-06-23 16:05:04 [info] elementor-pro::elementor_pro_updater Started 
2023-06-23 16:05:04 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-06-23 16:05:04 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-06-23 16:05:04 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.13.2',
  'to' => '3.14.0',
)]
2023-06-23 16:05:04 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.13.2',
  'to' => '3.14.0',
)]
2023-06-26 13:13:13 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.14.0',
  'to' => '3.14.1',
)]
2023-06-26 13:13:17 [info] elementor::elementor_updater Started 
2023-06-26 13:13:17 [info] Elementor/Upgrades - _on_each_version Start  
2023-06-26 13:13:19 [info] Elementor/Upgrades - _on_each_version Finished 
2023-06-26 13:13:19 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.14.0',
  'to' => '3.14.1',
)]
2023-07-12 00:18:39 [info] elementor-pro::elementor_pro_updater Started 
2023-07-12 00:18:39 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-07-12 00:18:39 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-07-12 00:18:39 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.14.0',
  'to' => '3.14.1',
)]
2023-07-12 00:18:39 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.14.0',
  'to' => '3.14.1',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Kompatybilny

== Elementor Pro - Compatibility Tag ==
	

				
````

</details>

**Comment by nicholaszein** [comment]
Hello @StudioAvatar,

Thank you for reaching out! 🙏 

### ⛔ 🧩 Please note that while we do welcome bug reports, we can't provide support for 3rd-party plugins.

If your issue is specifically happening only when you're using a feature from a 3rd-party software, or only when the 3rd-party software is active, you'll need to contact the support for that specific software or its developers.

### Currently, Elementor does not provide integration with the plugin in question. You will need to contact the 3rd-party developer to help solve your issue.

You also mentioned that you migrated from a `staging` environment to a `production` environment with another domain. Make sure you follow the instructions in [this article](https://elementor.com/help/site-migration/) to finish your [Site Migration](https://elementor.com/help/site-migration/) process. You should always perform this procedure when migrating from one domain to another, even if you're just switching the `http` protocol to `https`.

### 🛟 This is more of a support question, not really something we can help with here. 

👉 Please remember to check the Help Center or contact Elementor Support before submitting an issue.


### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
