### ISSUE TITLE
⛔ 🐞 Bug Report: Duplicate Form names appear in the Submissions filters after converting a Section with a Form to a Container with a Form

### ISSUE THREAD

**Issue by hitsgee** [elementor/elementor#23100]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi there, 

When I go to Elementor Submissions, I am seeing duplicate forms despite only having 1 form.

It seems that when you convert a page to flexbox from classic a duplicate form is created.

This is annoying as I have no way of removing the old forms despite them not being on the site.

Example here:
![Submissions-‹-The-Lifestyle-Card-—-WordPress](https://github.com/elementor/elementor/assets/40209785/d804ebe4-4d28-4e6d-87d2-c50c4c7795f8)

### Steps to reproduce

1) Disable Flexbox Container in Elementor Settings.
2) Create a page with a basic form & give it a title.
3) Enable Flexbox Container in Elementor Settings.
4) Convert the page to Flexbox using the option in Elementor page settings, being sure to remove the non-flexbox versions.
5) Open Elementor Submissions and you will see a new form has been added called the same.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.21.3
	MySQL version: mariadb.org binary distribution v10.5.12
	PHP Version: 8.1.21
	PHP Memory Limit: 256M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2.2
	Site URL: https://www.thelifestylecard.co.uk
	Home URL: https://www.thelifestylecard.co.uk
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-GB
	Timezone: Europe/London
	Debug Mode: Inactive

== Theme ==
	Name: HITS Core Child
	Version: 1.0.1
	Author: HITS
	Child Theme: Yes
	Parent Theme Name: HITS Core
	Parent Theme Version: 2.8.1
	Parent Theme Author: HITS

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 6.1.7
		Author: WP Engine

	Dynamic.ooo - Dynamic Content for Elementor
		Version: 2.10.4
		Author: Dynamic.ooo

	Elementor
		Version: 3.14.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.14.1
		Author: Elementor.com

	Frontend Reset Password
		Version: 1.2.1
		Author: WP Enhanced

	HITS CMS
		Version: 3.2.3
		Author: HITS

	JetFormBuilder
		Version: 3.0.9
		Author: Crocoblock

	JetFormBuilder WooCommerce Cart & Checkout Action
		Version: 1.0.4
		Author: Crocoblock

	JetSearch
		Version: 3.1.0
		Author: Crocoblock

	JetSmartFilters
		Version: 3.1.2
		Author: Crocoblock

	JetSmartFilters - Elementor Pro Loop Grid provider
		Version: 1.0.0-beta3
		Author: Crocoblock

	ManageWP - Worker
		Version: 4.9.17
		Author: GoDaddy

	PowerPack Pro for Elementor
		Version: 2.9.22
		Author: Team IdeaBox - PowerPack Elements

	Teams for WooCommerce Memberships
		Version: 1.7.0
		Author: SkyVerge

	WooCommerce
		Version: 7.9.0
		Author: Automattic

	WooCommerce Checkout Field Editor
		Version: 1.7.9
		Author: WooCommerce

	WooCommerce Memberships
		Version: 1.25.0
		Author: SkyVerge

	WooCommerce Stripe Gateway
		Version: 7.4.1
		Author: WooCommerce

	WooCommerce Subscriptions
		Version: 5.2.0
		Author: WooCommerce

	WP Mail SMTP
		Version: 3.8.0
		Author: WP Mail SMTP

	Yoast SEO
		Version: 20.11
		Author: Team Yoast

	Yoast SEO Premium
		Version: 20.11
		Author: Team Yoast


== Must-Use Plugins ==
	Kinsta Must-use Plugins
		Version: 3.0.0
		Author: Kinsta Team

	ManageWP - Worker Loader
		Version: 
		Author: GoDaddy


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	
	google_maps: Active
	recaptcha_v3: Active
	woocommerce: Active


== Elementor Experiments ==
	Optimised DOM Output: Active
	Improved asset loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility improvements: Active
	Additional Custom Breakpoints: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active
	Grid Container: Active
	Default to New Theme Builder: Inactive
	Hello Theme Header & Footer: Inactive
	Editor Top Bar: Inactive
	Landing pages: Inactive
	Nested Elements: Active
	Nested Accordion: Inactive by default
	Lazy Load Background Images: Inactive
	Global Style Guide: Inactive
	Page Transitions: Inactive
	Notes: Inactive
	Loop: Active
	Form Submissions: Active
	Scroll Snap: Inactive
	Menu: Active


== Log ==
	
Log: showing 20 of 222023-06-26 13:31:57 [info] elementor::elementor_updater Started 
2023-06-26 13:31:57 [info] Elementor/Upgrades - _on_each_version Start  
2023-06-26 13:31:57 [info] Elementor/Upgrades - _on_each_version Finished 
2023-06-26 13:31:57 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.14.0',
  'to' => '3.14.1',
)]
2023-06-26 13:41:20 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.14.0',
  'to' => '3.14.1',
)]
2023-06-26 13:41:21 [info] elementor-pro::elementor_pro_updater Started 
2023-06-26 13:41:21 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-06-26 13:41:21 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-06-26 13:41:21 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.14.0',
  'to' => '3.14.1',
)]
2023-07-10 10:28:16 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.14.1',
  'to' => '3.15.0-beta2',
)]
2023-07-10 10:28:17 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.14.1',
  'to' => '3.15.0-beta1',
)]
2023-07-10 10:28:20 [info] elementor::elementor_updater Started 
2023-07-10 10:28:20 [info] Elementor/Upgrades - _on_each_version Start  
2023-07-10 10:28:20 [info] Elementor/Upgrades - _on_each_version Finished 
2023-07-10 10:28:20 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.14.1',
  'to' => '3.15.0-beta2',
)]
2023-07-10 10:28:21 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.14.1',
  'to' => '3.15.0-beta2',
)]
2023-07-10 10:28:21 [info] elementor-pro::elementor_pro_updater Started 
2023-07-10 10:28:21 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-07-10 10:28:21 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-07-10 10:28:21 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.14.1',
  'to' => '3.15.0-beta1',
)]

PHP: showing 16 of 16PHP: 2023-06-26 12:07:42 [notice X 197][../wp-content/plugins/elementor-pro/modules/woocommerce/module.php::591] parse_str(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-06-26 14:03:32 [warning X 480][../wp-content/plugins/elementor/core/dynamic-tags/manager.php::73] Array to string conversion [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-06-27 15:44:50 [notice X 24][../wp-content/plugins/elementor-pro/modules/custom-css/module.php::76] trim(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ../wp-content/plugins/elementor-pro/modules/custom-css/module.php(76): class type trim()
#2: ../wp-includes/class-wp-hook.php(308): ElementorPro\Modules\CustomCss\Module -> add_page_settings_css()
#3: ../wp-includes/class-wp-hook.php(332): WP_Hook -> apply_filters()
#4: ../wp-includes/plugin.php(517): WP_Hook -> do_action()
',
)]
PHP: 2023-06-29 14:47:26 [warning X 6][../wp-content/plugins/elementor/app/modules/import-export/module.php::734] Attempt to read property "label" on null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-06-29 14:47:27 [warning X 4][../wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-06-29 14:47:27 [warning X 20][../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key "condition_type" [array (
  'trace' => '
#0: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: ../wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2023-07-10 10:28:20 [warning X 12][../wp-content/plugins/elementor/core/files/manager.php::111] unlink(../wp-content/uploads/elementor/css/min): Is a directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-10 10:33:17 [error X 1][../wp-content/plugins/elementor/includes/managers/elements.php::71] Uncaught TypeError: Elementor\Elements_Manager::create_element_instance(): Argument #1 ($element_data) must be of type array, bool given, called in ../wp-content/plugins/powerpack-elements/modules/posts/module.php on line 137 and defined in ../wp-content/plugins/elementor/includes/managers/elements.php:71
Stack trace:
#0 ../wp-content/plugins/powerpack-elements/modules/posts/module.php(137): Elementor\Elements_Manager->create_element_instance(false)
#1 ../wp-includes/class-wp-hook.php(308): PowerpackElements\Modules\Posts\Module->get_post_data('')
#2 ../wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#3 ../wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 ../wp-admin/admin-ajax.php(188): do_action('wp_ajax_pp_get_...')
#5 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-10 10:58:07 [notice X 11][../wp-content/plugins/elementor-pro/modules/custom-css/module.php::76] trim(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-11 12:47:27 [error X 1][../wp-content/plugins/elementor-pro/modules/popup/document.php::66] Uncaught Error: Class "ElementorPro\Modules\Popup\DisplaySettings\Triggers" not found in ../wp-content/plugins/elementor-pro/modules/popup/document.php:66
Stack trace:
#0 ../wp-content/plugins/elementor-pro/modules/popup/document.php(120): ElementorPro\Modules\Popup\Document->get_display_settings()
#1 ../wp-content/plugins/elementor/core/base/document.php(325): ElementorPro\Modules\Popup\Document->get_frontend_settings()
#2 ../wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(186): Elementor\Core\Base\Document->get_container_attributes()
#3 ../wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(414): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document->get_container_attributes()
#4 ../wp-content/plugins/elementor/includes/frontend.php(1179): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document->print_elements_with_wrapper(Array)
#5 ../wp-content/plugins/elementor/core/base/document.php(1155): Elementor\Frontend->get_builder_content(26133, false)
#6 ../wp-content/plugins/elementor/modules/library/documents/library-document.php(76): Elementor\Core\Base\Document->get_content(false)
#7 ../wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(158): Elementor\Modules\Library\Documents\Library_Document->get_content(false)
#8 ../wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(173): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document->get_content()
#9 ../wp-content/plugins/elementor-pro/modules/theme-builder/classes/locations-manager.php(364): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document->print_content()
#10 ../wp-content/plugins/elementor-pro/modules/theme-builder/api.php(13): ElementorPro\Modules\ThemeBuilder\Classes\Locations_Manager->do_location('popup')
#11 ../wp-content/plugins/elementor-pro/modules/popup/module.php(97): elementor_theme_do_location('popup')
#12 ../wp-includes/class-wp-hook.php(308): ElementorPro\Modules\Popup\Module->print_popups('')
#13 ../wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#14 ../wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#15 ../wp-includes/general-template.php(3065): do_action('wp_footer')
#16 ../wp-content/themes/HITS-Core/footer.php(23): wp_footer()
#17 ../wp-includes/template.php(783): require_once('/www/thelifesty...')
#18 ../wp-includes/template.php(718): load_template('/www/thelifesty...', true, Array)
#19 ../wp-includes/general-template.php(92): locate_template(Array, true, true, Array)
#20 ../wp-content/plugins/elementor/modules/page-templates/templates/header-footer.php(30): get_footer()
#21 ../wp-includes/template-loader.php(106): include('/www/thelifesty...')
#22 ../wp-blog-header.php(19): require_once('/www/thelifesty...')
#23 ../index.php(17): require('/www/thelifesty...')
#24 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-11 12:51:47 [warning X 2][../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::171] Undefined array key "editor_post_id" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-12 14:20:38 [notice X 114][../wp-content/plugins/elementor-pro/modules/loop-builder/files/css/loop.php::58] Creation of dynamic property ElementorPro\Modules\LoopBuilder\Files\Css\Loop::$post_id is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-12 15:19:40 [notice X 6][../wp-content/plugins/elementor-pro/modules/loop-builder/files/css/loop.php::58] Creation of dynamic property ElementorPro\Modules\LoopBuilder\Files\Css\Loop::$post_id is deprecated [array (
  'trace' => '
#0: ../wp-content/plugins/elementor-pro/modules/loop-builder/files/css/loop.php(58): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Modules\LoopBuilder\Files\Css\Loop -> __construct()
#2: ../wp-content/plugins/elementor/core/files/manager.php(45): ReflectionClass -> newInstanceArgs()
#3: ../wp-content/plugins/elementor/core/files/base.php(74): Elementor\Core\Files\Manager -> get()
#4: ../wp-content/plugins/elementor-pro/modules/loop-builder/documents/loop.php(250): Elementor\Core\Files\Base :: create()
',
)]
PHP: 2023-07-13 12:12:45 [error X 1][../wp-content/plugins/elementor-pro/modules/popup/module.php::126] Uncaught Error: Call to undefined method Elementor\Core\Kits\Documents\Kit::save_display_settings_data() in ../wp-content/plugins/elementor-pro/modules/popup/module.php:126
Stack trace:
#0 [internal function]: ElementorPro\Modules\Popup\Module->save_display_settings(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#1 ../wp-content/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 ../wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#3 ../wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#4 ../wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#5 ../wp-admin/admin-ajax.php(188): do_action('wp_ajax_element...')
#6 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-18 10:49:51 [warning X 3][../wp-content/plugins/elementor/includes/embed.php::176] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-18 11:50:26 [warning X 28][../wp-content/plugins/elementor/includes/conditions.php::87] Undefined array key "checkout_layout" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 4 of 4JS: 2023-07-10 09:28:01 [error X 1][https://www.thelifestylecard.co.uk/wp-content/plugins/elementor/assets/js/editor.min.js:3:1106176] Cannot read properties of null (reading 'getBoundingClientRect') 
JS: 2023-07-12 14:17:28 [error X 2][https://www.thelifestylecard.co.uk/wp-content/plugins/elementor/assets/js/editor.min.js:3:640984] Cannot read properties of undefined (reading 'isDesignable') 
JS: 2023-07-14 12:19:02 [error X 3][https://www.thelifestylecard.co.uk/wp-includes/js/jquery/jquery.min.js:2:31823] Cannot read properties of undefined (reading 'value') 
JS: 2023-07-17 11:16:09 [error X 1][https://www.thelifestylecard.co.uk/wp-content/plugins/dynamic-content-for-elementor/assets/js/acf-repeater.min.js:9:161] mySwiper is not defined



== Elementor - Compatibility Tag ==
	
	Dynamic.ooo - Dynamic Content for Elementor: Compatibility not specified
	Elementor Pro: Compatibility not specified
	JetSmartFilters - Elementor Pro Loop Grid provider: Compatibility not specified
	PowerPack Pro for Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==
	

				

````

</details>

**Comment by nicholaszein** [comment]
Hello @hitsgee,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
- When you convert a Section to a Container, Elementor will **<ins>duplicate</ins>** all elements inside the section, not move them. This will create new elements with new IDs, including forms. This is why you are seeing two forms with different IDs but with the same name.
- The Submissions list will show submissions from all forms used on your website, even those you have already removed, unless you remove the submissions from those forms. For this reason, the filter list will show old forms if there are submissions related to them. This is the expected behavior.

### ✅ What you can do to solve your issue:
- If you wish to maintain the same form ID, you should delete the newly created form, and drag the old one from the section to the container when making the conversion.

### 🛟 This is more of a support question, not really something we can help with here. 

👉 Please remember to check the Help Center or contact Elementor Support before submitting an issue.

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
