### ISSUE TITLE
[⌛ Awaiting Feedback] 🐞 Bug Report: Slider background image wobbles on initial page load

### ISSUE THREAD

**Issue by jamieburchell** [elementor/elementor#23118]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

The background image in a slider wobbles for a short time on initial page load as can be observed in the screencast here:

[Here's a screencast](https://www.dropbox.com/scl/fi/qnbztt68rj7qw67fny4o2/23118-elementor-slide-wobble-bug.mp4?rlkey=ud1keb80l5cqeax59i223x43v&st=vo5kgzjb&dl=0).

I believe this is due to the background image being centred and JavaScript initially changing the width of the `.swiper-slide` container. I was able to fix the issue by forcing the width of `.swiper-slide` to 100%.

### Steps to reproduce

1) Add a slider
2) On the first slide, upload an image 850px x 480px and set to contain. Remove any text content for the slide.
3) Add another slide so that the slider renders on the page
4) Set the height of the slider to 600px
5) View the slider on the page (my viewport size was 1920x1080)

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt

					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.52 (Ubuntu)
	MySQL version: Ubuntu 22.04 v10.6.12
	PHP Version: 8.0.29
	PHP Memory Limit: 256M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2.2
	Site URL: https://example.local.test/wp
	Home URL: https://example.local.test
	WP Multisite: No
	Max Upload Size: 16 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%category%/%postname%/
	Language: en-GB
	Timezone: Europe/London
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.8.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.14.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.14.1
		Author: Elementor.com


== Must-Use Plugins ==
	Bedrock Autoloader
		Version: 1.0.3
		Author: Roots

	Disable status tests
		Version: 1.0.0
		Author: Roots

	Register Theme Directory
		Version: 1.0.0
		Author: Roots


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	
	google_maps: Active
	recaptcha_v3: Active


== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Active
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Inactive
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Inactive by default
	Grid Container: Inactive
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Inactive
	Editor Top Bar: Inactive
	Landing Pages: Inactive
	Nested Elements: Inactive
	Nested Accordion: Inactive by default
	Lazy Load Background Images: Inactive
	Global Style Guide: Inactive by default
	Page Transitions: Inactive
	Notes: Inactive
	Loop: Active by default
	Form Submissions: Active by default
	Scroll Snap: Inactive
	Menu: Inactive


== Log ==
	
JS: showing 7 of 7JS: 2023-04-27 09:16:03 [error X 1][https://example.local.test/app/plugins/elementor/assets/js/editor.min.js?ver=3.12.2:3:310955] Cannot read properties of undefined (reading 'html') 
JS: 2023-04-27 10:19:59 [error X 4][https://example.local.test/app/plugins/elementor/assets/js/frontend-modules.min.js?x39665&ver=3.12.2:2:5009] Cannot read properties of undefined (reading 'attributes') 
JS: 2023-04-27 10:29:14 [error X 1][https://example.local.test/app/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view6076") has already been destroyed and cannot be used. 
JS: 2023-04-27 10:31:24 [error X 1][https://example.local.test/app/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view20022") has already been destroyed and cannot be used. 
JS: 2023-04-27 11:47:17 [error X 2][https://example.local.test/app/plugins/elementor/assets/js/editor.min.js?ver=3.12.2:3:673293] this.model.isValidChild is not a function 
JS: 2023-04-27 12:25:23 [error X 1][https://example.local.test/wp/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10:23751] Cannot read properties of null (reading 'getOptions') 
JS: 2023-07-14 08:31:06 [error X 7][https://example.local.test/wp/wp-admin/load-scripts.php?c=0&loadchunk_0=jquery-core,jquery-migrate,utils&ver=6.2.2:2:31823] Cannot read properties of undefined (reading 'value') 

PHP: showing 6 of 6PHP: 2023-04-27 11:31:35 [warning X 3][/var/www/vhosts/example.local.test/releases/74/web/app/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::168] Undefined array key "editor_post_id" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-27 13:59:25 [error X 2][/var/www/vhosts/example.local.test/releases/74/web/app/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::295] Uncaught Error: Call to a member function update_meta() on bool in /var/www/vhosts/example.local.test/releases/74/web/app/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:295
Stack trace:
#0 /var/www/vhosts/example.local.test/releases/74/web/app/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(168): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /var/www/vhosts/example.local.test/releases/74/web/app/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /var/www/vhosts/example.local.test/releases/74/web/wp/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /var/www/vhosts/example.local.test/releases/74/web/wp/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#5 /var/www/vhosts/example.local.test/releases/74/web/wp/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /var/www/vhosts/example.local.test/releases/74/web/wp/wp-admin/admin-ajax.php(188): do_action('wp_ajax_element...')
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-06-19 13:31:53 [warning X 22][/var/www/vhosts/example.local.test/releases/81/web/app/plugins/elementor/app/modules/import-export/module.php::717] Attempt to read property "label" on null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-06-26 14:27:02 [warning X 19][/var/www/vhosts/example.local.test/releases/84/web/app/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-17 15:13:27 [warning X 4][/var/www/vhosts/example.local.test/releases/88/web/app/plugins/elementor/modules/history/revisions-manager.php::363] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-20 11:46:04 [error X 1][/home/jamie/projects/example.local.test/web/app/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::304] Uncaught Error: Call to a member function update_meta() on null in /home/jamie/projects/example.local.test/web/app/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:304
Stack trace:
#0 /home/jamie/projects/example.local.test/web/app/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(177): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions()
#2 /home/jamie/projects/example.local.test/web/app/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func()
#3 /home/jamie/projects/example.local.test/web/wp/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#4 /home/jamie/projects/example.local.test/web/wp/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#5 /home/jamie/projects/example.local.test/web/wp/wp-includes/plugin.php(517): WP_Hook->do_action()
#6 /home/jamie/projects/example.local.test/web/wp/wp-admin/admin-ajax.php(188): do_action()
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 20 of 302023-05-30 10:15:47 [info] Update DB has been started [array (
  'plugin' => 'Elementor',
  'from' => '3.13.2',
  'to' => '3.13.4',
)]
2023-05-30 10:15:47 [info] elementor::elementor_updater Started 
2023-05-30 10:15:47 [info] Elementor/Upgrades - _on_each_version Start  
2023-05-30 10:15:48 [info] Elementor/Upgrades - _on_each_version Finished 
2023-05-30 10:15:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.2',
  'to' => '3.13.4',
)]
2023-05-30 10:15:51 [info] Update DB has been started [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.13.1',
  'to' => '3.13.2',
)]
2023-05-30 10:15:51 [info] elementor-pro::elementor_pro_updater Started 
2023-05-30 10:15:51 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-05-30 10:15:51 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-05-30 10:15:51 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.13.1',
  'to' => '3.13.2',
)]
2023-06-26 14:09:24 [info] Update DB has been started [array (
  'plugin' => 'Elementor',
  'from' => '3.13.4',
  'to' => '3.14.1',
)]
2023-06-26 14:09:24 [info] elementor::elementor_updater Started 
2023-06-26 14:09:24 [info] Elementor/Upgrades - _on_each_version Start  
2023-06-26 14:09:24 [info] Elementor/Upgrades - _on_each_version Finished 
2023-06-26 14:09:24 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.4',
  'to' => '3.14.1',
)]
2023-06-26 14:09:28 [info] Update DB has been started [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.13.2',
  'to' => '3.14.1',
)]
2023-06-26 14:09:28 [info] elementor-pro::elementor_pro_updater Started 
2023-06-26 14:09:28 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-06-26 14:09:28 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-06-26 14:09:28 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.13.2',
  'to' => '3.14.1',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==
	

				


````

</details>

**Comment by nicholaszein** [comment]
Hello @jamieburchell! 

Thank you for submitting your issue! 🙏 

While reviewing your issue, I was not able to reproduce the problem you are reporting. Could you please share a little more about how you set your slider and the wrapping container? If possible, share a link with us so we can see the problem on a live website.

Also, I see you have the `Upgrade Swiper Library: Inactive by default` feature. Could you test if this issue is happening in your environment also if this feature is active?

Here's a video of my test. I even tried to throttle the connection to see if it was more apparent, but I don't see any "wooble".


https://github.com/elementor/elementor/assets/113993460/922903d9-423c-4d75-888c-7043bac45cde

Thank you in advance! 🙂 

Best regards

**Comment by jamieburchell** [comment]
Hi @nicholaszein 

Thank you for taking the time to look at this report and for your feedback.

I can confirm that enabling the Upgrade Swiper Experiment resolves the issue. Also, setting the PHP constant SCRIPT_DEBUG to `true` also resolves the issue (I had this enabled briefly in testing).

I will come back to you with a live example when time permits.

**Comment by jamieburchell** [comment]
Here you go @nicholaszein 

https://elementor-test.ib3.uk/

**Comment by StenderIternum** [comment]
Can confirm, that upgrading slider library removed my the shaking of the slider. 
Thank you.

**Comment by jamieburchell** [comment]
Closing this as the upgraded/new swiper library resolved whatever the issue was here.
