### ISSUE TITLE
⛔ 🛟 Support Request: The Progress Bar is not animating on the front-end

### ISSUE THREAD

**Issue by theodoreimperato** [elementor/elementor#23159]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hello, the progress bar animation doesn't work, so you can't see the progress. Here's a photo to show you the problem.
![Capture d'écran 2023-07-24 180029](https://github.com/elementor/elementor/assets/64660960/07418527-db63-4ab8-b941-ef7063136db9)

### Steps to reproduce

Step 1 : You select the progress bar 
Step 2 : Put the progress bar on your website
Step 3 : You publish it and look at the result. The animation doesn't work

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>Click to reveal</summary>

````txt

					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.57 (Unix)
	MySQL version: Source distribution v10.3.37
	PHP Version: 8.0.28
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 32M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://theodore-imperato.fr
	Home URL: https://theodore-imperato.fr
	WP Multisite: No
	Max Upload Size: 32 Mo
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: fr-FR
	Timezone: Europe/Paris
	Debug Mode: Inactive

== Theme ==
	Name: Perfect Portfolio
	Version: 1.2.0
	Author: Rara Theme
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: fr_FR
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36

== Active Plugins ==
	Better Search Replace
		Version: 1.4.2
		Author: WP Engine

	Contact Form 7
		Version: 5.7.7
		Author: Takayuki Miyoshi

	Elementor
		Version: 3.14.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.14.1
		Author: Elementor.com

	RARA One Click Demo Import
		Version: 1.3.3
		Author: raratheme

	RaraTheme Companion
		Version: 1.4.2
		Author: Rara Theme


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Expériences d’Elementor ==
	Sortie DOM optimisée: Actif par défaut
	Amélioration du chargement des ressources: Actif par défaut
	Optimisation du chargement du CSS: Actif par défaut
	Icônes de police « inline »: Inactif par défaut
	Améliorations de l’accessibilité: Actif par défaut
	Points d’arrêt personnalisés supplémentaires: Actif par défaut
	admin_menu_rearrangement: Inactif par défaut
	Conteneur Flexbox: Inactif par défaut
	Mettre à niveau la bibliothèque Swiper: Actif par défaut
	Conteneur grille: Inactif par défaut
	Default to New Theme Builder: Actif par défaut
	Barre supérieure de l’éditeur: Inactif par défaut
	Page d’atterrissage: Actif par défaut
	Éléments imbriqués: Inactif par défaut
	Accordéon imbriqué: Inactif par défaut
	Chargement différé des images d’arrière-plan: Inactif par défaut
	Guide de style global: Inactif par défaut
	Page Transitions: Actif par défaut
	Notes: Actif par défaut
	Loop: Actif par défaut
	Form Submissions: Actif par défaut
	Scroll Snap: Actif par défaut
	Menu: Inactif par défaut


== Journal ==
	
Log: showing 5 of 52023-07-02 12:27:36 [info] elementor::elementor_updater Started 
2023-07-02 12:27:36 [info] Elementor/Upgrades - _on_each_version Start  
2023-07-02 12:27:36 [info] Elementor/Upgrades - _on_each_version Finished 
2023-07-02 12:27:36 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.14.0',
  'to' => '3.14.1',
)]
2023-07-02 12:27:37 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.14.0',
  'to' => '3.14.1',
)]

JS: showing 14 of 14JS: 2023-07-12 13:15:51 [error X 2][https://192-168-1-43.amboisetransport.direct.quickconnect.to/wordpress/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.14.1:3:318607] Cannot read properties of undefined (reading 'html') 
JS: 2023-07-12 14:53:15 [error X 24391][https://192-168-1-43.amboisetransport.direct.quickconnect.to/wordpress/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:14799] Cannot read properties of null (reading 'clone') 
JS: 2023-07-12 14:53:16 [error X 235][https://192-168-1-43.amboisetransport.direct.quickconnect.to/wordpress/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:19552] Cannot read properties of null (reading 'changestop') 
JS: 2023-07-12 16:09:57 [error X 20][https://192-168-1-43.amboisetransport.direct.quickconnect.to/wordpress/wp-admin/load-scripts.php?c=1&loadchunk_0=jquery-core,jquery-migrate,utils,moxiejs,plupload&ver=6.1.1:2:31703] Cannot read properties of undefined (reading 'value') 
JS: 2023-07-13 16:13:25 [error X 6][https://192-168-1-43.amboisetransport.direct.quickconnect.to/wordpress/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.14.1:3:569946] Blocked a frame with origin "https://192-168-1-43.amboisetransport.direct.quickconnect.to" from accessing a cross-origin frame. 
JS: 2023-07-13 23:07:17 [error X 43][https://192-168-1-43.amboisetransport.direct.quickconnect.to/wordpress/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.14.1:3:625527] Cannot read properties of null (reading 'data') 
JS: 2023-07-13 23:09:06 [error X 6][https://192-168-1-43.amboisetransport.direct.quickconnect.to/wordpress/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.14.1:3:1113620] Cannot read properties of null (reading 'getBoundingClientRect') 
JS: 2023-07-13 23:48:08 [error X 1][https://192-168-1-43.amboisetransport.direct.quickconnect.to/wordpress/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.14.1:2:63957] elementor.getPanelView(...).getCurrentPageView(...).activateSection is not a function 
JS: 2023-07-13 23:48:15 [error X 1][https://192-168-1-43.amboisetransport.direct.quickconnect.to/wordpress/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.14.1:3:22701] Cannot read properties of undefined (reading 'cid') 
JS: 2023-07-14 00:08:32 [error X 3][https://192-168-1-43.amboisetransport.direct.quickconnect.to/wordpress/wp-admin/post.php?post=8&action=elementor:10:14] Cannot read properties of undefined (reading 'title') 
JS: 2023-07-14 00:08:51 [error X 1][https://192-168-1-43.amboisetransport.direct.quickconnect.to/wordpress/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.14.1:3:210449] C.ui.sync.removeClass is not a function 
JS: 2023-07-14 00:11:28 [error X 4][https://192-168-1-43.amboisetransport.direct.quickconnect.to/wordpress/wp-admin/load-scripts.php?c=1&loadchunk_0=underscore,shortcode,utils,jquery-core,jquery-migrate,backbone,wp-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jqu&loadchunk_1=ery-ui-core,jquery-ui-mouse,jquery-ui-sortable&ver=6.1.1:8:51824] Cannot read properties of undefined (reading 'replace') 
JS: 2023-07-14 21:48:52 [error X 5][https://theodore-imperato.fr/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.14.1:3:640984] Cannot read properties of undefined (reading 'isDesignable') 
JS: 2023-07-14 23:00:48 [error X 6][https://theodore-imperato.fr/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.14.1:3:807522] Cannot read properties of undefined (reading 'localized') 

PHP: showing 9 of 9PHP: 2023-07-12 15:27:41 [warning X 7][../wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-12 16:53:38 [warning X 73][../wp-content/plugins/elementor/core/logger/items/js.php::17] Undefined array key "url" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-12 17:27:31 [warning X 1][../wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-13 18:14:00 [warning X 4][../wp-content/plugins/elementor/core/debug/classes/htaccess.php::32] file_exists(): open_basedir restriction in effect. File(/.htaccess) is not within the allowed path(s): (/var/services/web_packages/wordpress:/tmp:/var/services/tmp) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-13 19:12:13 [warning X 1][../wp-content/plugins/elementor-pro/modules/forms/classes/recaptcha-v3-handler.php::124] Undefined array key "score" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-13 19:59:25 [error X 3][../wp-content/plugins/elementor-pro/modules/payments/module.php::142] Uncaught Error: Call to undefined method ElementorPro\Core\Utils::_unstable_check_document_permissions() in ../wp-content/plugins/elementor-pro/modules/payments/module.php:142
Stack trace:
#0 [internal function]: ElementorPro\Modules\Payments\Module->get_stripe_tax_rates(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#1 ../wp-content/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 ../wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#3 ../wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#4 ../wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#5 ../wp-admin/admin-ajax.php(188): do_action('wp_ajax_element...')
#6 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-14 01:01:12 [warning X 14][../wp-content/plugins/elementor/modules/history/revisions-manager.php::363] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-14 01:22:46 [warning X 2][../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::171] Undefined array key "editor_post_id" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-15 01:11:38 [warning X 6][../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key "condition_type" [array (
  'trace' => '
#0: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: ../wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]




== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==
	

				


````

</details>

**Comment by nicholaszein** [comment]
Hello @theodoreimperato ,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
- We tested on a live website and the Progress Bars animated as expected.


https://github.com/elementor/elementor/assets/113993460/91aa64bc-8767-4082-a7b1-e77ab27b8c8c



- We visited your site and we can see the Progress Bar correctly showing the percentages.


https://github.com/elementor/elementor/assets/113993460/ee838cf6-e8f0-488d-bd69-368cd8123304



- It seems you have a cache problem or a conflict with another plugin or your theme.

### ✅ What you can do to solve your issue:

#### ⚠️ Make a Backup of your website before proceeding, and if possible do it in a staging environment!

1. Disable/Deactivate all your plugins except **Elementor** (and **Elementor Pro**).
    - If this solves the problem, gradually re-activate plugin-by-plugin (and check if the problem returns) to identify the problematic or conflicting plugin. In this case, contact the 3rd-party plugin support as we don't provide support for 3rd party plugins.
    - If it doesn't solve your problem, try the next step:
2. Change your WordPress theme to the [Hello Elementor](https://wordpress.org/themes/hello-elementor/) theme and check if the problem is solved.
3. Clear all cache types, including but not limited to **Server cache**, **WordPress (optimization plugin) cache**, **CDN cache**, and **Browser cache**. Also, try visiting the front page of your website in **incognito/private** mode.
4. Make sure the server resources allocated to your site and WordPress installation meet our [Requirements](https://elementor.com/help/requirements/). 
    - To check this information go to your WordPress `Dashboard` > `Elementor` > `System info` [learn how to copy it here](https://elementor.com/help/hare-my-system-info/). We can't accept issues without it.

### 🛟 This is more of a support question, not really something we can help with here. 

👉 Please remember to check the [Help Center](https://elementor.com/help) or contact [Elementor Support](https://elementor.com/contact) before submitting an issue.


### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
