### ISSUE TITLE
⛔ 🛟 Support Request: Logo (Customizer) doesn't stay

### ISSUE THREAD

**Issue by LorenaFlyy** [elementor/elementor#23231]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

In the last 2 Websites I made, I always had problems for to logo staying put. It constantly changes back to a previous version I loaded up before. 

### Steps to reproduce

Change logo via Customizer

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>Click to reveal</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Ubuntu 22.04 v10.6.12
	PHP Version: 8.0.28
	PHP Memory Limit: 256M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 200M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2.2
	Site URL: ...
	Home URL: ...
	WP Multisite: No
	Max Upload Size: 200 MB
	Memory limit: 256M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: de-DE
	Timezone: Europe/Berlin
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.8.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.14.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.14.1
		Author: Elementor.com

	UpdraftPlus - Backup/Restore
		Version: 1.23.7
		Author: UpdraftPlus.Com, DavidAnderson


== Eigenschaften ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor-Experimente ==
	Optimierte DOM Ausgabe: Standardmäßig aktiviert
	Verbessertes Laden von Assets: Standardmäßig aktiviert
	Verbessertes Laden von CSS: Standardmäßig aktiviert
	Inline-Schriftarten-Symbole: Standardmäßig deaktiviert
	Verbesserungen der Zugänglichkeit: Standardmäßig aktiviert
	Zusätzliche benutzerdefinierte Breakpoints: Standardmäßig aktiviert
	admin_menu_rearrangement: Standardmäßig deaktiviert
	Flexbox Container: Aktiv
	Upgrade Swiper Library: Standardmäßig aktiviert
	Grid Container: Standardmäßig deaktiviert
	Default to New Theme Builder: Standardmäßig aktiviert
	Hello Theme Header & Footer: Inaktiv
	Editor Top Bar: Standardmäßig deaktiviert
	Startseiten: Inaktiv
	Nested Elements: Aktiv
	Nested Accordion: Standardmäßig deaktiviert
	Hintergrundbilder nachladen: Standardmäßig deaktiviert
	Global Style Guide: Standardmäßig deaktiviert
	Page Transitions: Inaktiv
	Notes: Inaktiv
	Loop: Standardmäßig aktiviert
	Form Submissions: Standardmäßig aktiviert
	Scroll Snap: Inaktiv
	Menü: Standardmäßig deaktiviert


== Protokoll ==
	
Log: showing 20 of 262023-05-12 09:10:43 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.13.0',
  'to' => '3.13.1',
)]
2023-05-12 09:11:30 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.1',
  'to' => '3.13.2',
)]
2023-05-12 09:18:13 [info] elementor-pro::elementor_pro_updater Started 
2023-05-12 09:18:13 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-05-12 09:18:13 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-05-12 09:18:13 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.13.0',
  'to' => '3.13.1',
)]
2023-05-12 09:18:14 [info] elementor::elementor_updater Started 
2023-05-12 09:18:14 [info] Elementor/Upgrades - _on_each_version Start  
2023-05-12 09:18:14 [info] Elementor/Upgrades - _on_each_version Finished 
2023-05-12 09:18:14 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.1',
  'to' => '3.13.2',
)]
2023-07-19 11:21:27 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.2',
  'to' => '3.14.1',
)]
2023-07-19 11:21:31 [info] elementor::elementor_updater Started 
2023-07-19 11:21:31 [info] Elementor/Upgrades - _on_each_version Start  
2023-07-19 11:21:31 [info] Elementor/Upgrades - _on_each_version Finished 
2023-07-19 11:21:31 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.2',
  'to' => '3.14.1',
)]
2023-07-19 11:21:59 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.13.1',
  'to' => '3.14.1',
)]
2023-07-19 11:22:05 [info] elementor-pro::elementor_pro_updater Started 
2023-07-19 11:22:05 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-07-19 11:22:05 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-07-19 11:22:05 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.13.1',
  'to' => '3.14.1',
)]

PHP: showing 10 of 10PHP: 2023-05-10 19:02:01 [warning X 4][/.../wp-content/plugins/elementor-pro/modules/query-control/module.php::749] Attempt to read property "name" on null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-10 20:20:02 [error X 3][/.../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::295] Uncaught Error: Call to a member function update_meta() on bool in /.../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:295
Stack trace:
#0 /.../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(168): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /.../wp-content/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /.../wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /.../wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#5 /.../wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /.../wp-admin/admin-ajax.php(188): do_action('wp_ajax_element...')
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-10 23:10:32 [error X 2][/.../wp-content/plugins/elementor/includes/managers/widgets.php::406] Uncaught Error: Call to a member function is_editable_by_current_user() on bool in /.../wp-content/plugins/elementor/includes/managers/widgets.php:406
Stack trace:
#0 [internal function]: Elementor\Widgets_Manager->ajax_render_widget(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#1 /.../wp-content/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /.../wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#3 /.../wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#4 /.../wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#5 /.../wp-admin/admin-ajax.php(188): do_action('wp_ajax_element...')
#6 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-21 23:04:15 [warning X 23][/.../wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-21 23:04:16 [warning X 342][/.../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key "condition_type" [array (
  'trace' => '
#0: /.../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /.../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /.../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /.../wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2023-07-25 22:27:39 [warning X 15][/.../wp-content/plugins/elementor/app/modules/import-export/module.php::734] Attempt to read property "label" on null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-29 12:00:45 [warning X 20][/.../wp-content/plugins/elementor/modules/history/revisions-manager.php::363] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-29 21:42:10 [warning X 16][/.../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::171] Undefined array key "editor_post_id" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-29 21:50:00 [error X 1][/.../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::304] Uncaught Error: Call to a member function update_meta() on null in /.../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:304
Stack trace:
#0 /.../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(177): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(18, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /.../wp-content/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /.../wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /.../wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#5 /.../wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /.../wp-admin/admin-ajax.php(188): do_action('wp_ajax_element...')
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-30 22:10:05 [warning X 3][/.../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key "condition_type" [array (
  'trace' => '
#0: /.../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /.../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(84): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /.../wp-content/plugins/elementor/data/base/endpoint.php(166): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> update_item()
#3: /.../wp-content/plugins/elementor/data/base/endpoint.php(307): Elementor\Data\Base\Endpoint -> base_callback()
#4: /.../wp-includes/rest-api/class-wp-rest-server.php(1181): Elementor\Data\Base\Endpoint -> Elementor\Data\Base\{closure}()
',
)]

JS: showing 6 of 6JS: 2023-07-21 21:10:06 [error X 2][.../wp-admin/load-scripts.php?c=0&loadchunk_0=jquery-core,jquery-migrate,utils&ver=6.2.2:2:31823] Cannot read properties of undefined (reading 'value') 
JS: 2023-07-25 20:26:29 [error X 1][.../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.14.1:3:923837] elementorFrontend is not defined 
JS: 2023-07-30 17:56:45 [error X 2][.../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.14.1:3:54034] Cannot read properties of undefined (reading 'activate') 
JS: 2023-07-30 19:36:52 [error X 3][.../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.14.1:3:1113620] Cannot read properties of null (reading 'getBoundingClientRect') 
JS: 2023-07-30 20:02:33 [error X 1][.../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.14.1:3:417985] Cannot read properties of null (reading 'history') 
JS: 2023-07-30 20:07:56 [error X 2][.../wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.14.1:3:22701] Cannot read properties of undefined (reading 'cid') 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Kompatibel

== Elementor Pro - Compatibility Tag ==
	

				

````

</details>

**Comment by nicholaszein** [comment]
Hello @LorenaFlyy,

Thanks for contacting us! 🙏 

### 🛟 This is more of a support question, not really something we can help with here. 

We've tested the feature on our testing environment and it worked as expected:

https://github.com/elementor/elementor/assets/113993460/7a3a4165-f142-4f90-a8b6-9dddfbbd06f6



As you can see, every time we change the logo the changes take effect.

Your issue is likely related to cache. This can happen when you use the same name of the new image file as the image file you're replacing.

👉 Please remember to check the [Help Center](https://elementor.com/help) or contact [Elementor Support](https://elementor.com/contact) before submitting an issue.


### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
