### ISSUE TITLE
⛔ 🛟 Support Request: During automated updates, elementor deletes itself

### ISSUE THREAD

**Issue by x4000** [elementor/elementor#23238]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

### Description

This has happened twice to me, and I have no idea why.  I have Elementor Pro, but I think the license is expired.  

Every time a new update is pushed out, my folder "D:\web\arcen\wp-content\plugins\elementor" is either completely erased, or is erased except for the includes folder.  The "D:\web\arcen\wp-content\plugins\elementor-pro" companion folder is untouched.

After this happens, I have to go in and manually delete the "D:\web\arcen\wp-content\plugins\elementor" folder via the file system (this is windows server), because wordpress cannot activate or install the elementor plugin "because that folder already exists" (though it is empty, or empty but for one other subfolder).

The actual website is basically stripped of most of itself, as you might expect, and displays in a mostly-CSS-less way.  Wordpress's plugin interface says "elementor is required to use elementor pro!"

For the time being, I have disabled automatic updates to elementor.

There is sufficient disk space (tens or hundreds of GB free on all disks), and there does not appear to be a problem with permissions when I inspect the folders that are left-behind.  My best guess is that perhaps this is some sort of niche issues since windows server is less common; I don't know if that's in the update scripts on your end, or as part of wordpress itself, but I have a variety of other plugins and themes that all update themself without incident, as does wordpress itself.  Have been running this specific setup for a bit over a year, after migrating servers.

I don't have a clean way of duplicating this since it only happens with automatic updates.  Since I am presently on the latest version, I also cannot trigger a manual update to see if it happens with manual updates.

### Steps to reproduce

Thus far, it has been "automatic update occurs, and the problem happens."

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>Click to reveal</summary>

````txt


					
== Server Environment ==
	Operating System: WINNT
	Software: Microsoft-IIS/10.0
	MySQL version: MySQL Community Server - GPL v8.0.28
	PHP Version: 7.4.13
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2.2
	Site URL: https://arcengames.com
	Home URL: https://arcengames.com
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: -5
	Debug Mode: Inactive

== Theme ==
	Name: The7
	Version: 11.7.3
	Author: Dream-Theme
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

== Active Plugins ==
	Anti-Spam by CleanTalk
		Version: 6.14.2
		Author: СleanTalk <welcome@cleantalk.org>

	Contact Form 7
		Version: 5.7.7
		Author: Takayuki Miyoshi

	Elementor
		Version: 3.15.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.14.1
		Author: Elementor.com

	Extendify
		Version: 1.7.0
		Author: Extendify

	Plugin Update Checker Library
		Version: 4.4
		Author: Janis Elsts

	Redux Framework
		Version: 4.4.4
		Author: Team Redux

	The7 CLI
		Version: 1.0.0
		Author: Dream-Theme

	The7 Elements
		Version: 2.7.5
		Author: Dream-Theme

	WP Mail SMTP
		Version: 3.8.2
		Author: WP Mail SMTP


== Elements Usage ==
	
	archive : 1
		archive-posts : 1
		theme-archive-title : 1
		wp-widget-categories : 1
		wp-widget-search : 1
	header : 1
		icon-list : 1
		nav-menu : 1
		social-icons : 1
		theme-site-logo : 1
	wp-post : 0
		blockquote : 1
		divider : 2
		heading : 54
		html : 1
		image : 31
		table-of-contents : 4
		text-editor : 94
		video : 27
	wp-page : 30
		button : 1
		call-to-action : 5
		heading : 32
		image : 4
		image-carousel : 2
		social-icons : 1
		spacer : 4
		table-of-contents : 1
		text-editor : 47
		the7_content_carousel : 1
		the7_elements_carousel : 1
		video : 4


== Settings ==
	
	allow_tracking: yes


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Additional Custom Breakpoints: Inactive by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Upgrade Swiper Library: Inactive by default
	Grid Container: Inactive by default
	Default to New Theme Builder: Active by default
	Editor Top Bar: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default
	Global Style Guide: Inactive by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Menu: Inactive by default


== Log ==
	
Log: showing 20 of 302022-08-30 03:19:19 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.3',
  'to' => '3.7.4',
)]
2022-09-01 03:20:18 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.4',
  'to' => '3.7.5',
)]
2022-09-01 03:20:19 [info] elementor-pro::elementor_pro_updater Started 
2022-09-01 03:20:19 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-09-01 03:20:19 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-09-01 03:20:19 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.4',
  'to' => '3.7.5',
)]
2022-09-01 03:20:20 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.4',
  'to' => '3.7.5',
)]
2023-07-22 10:57:46 [info] elementor-pro::elementor_pro_updater Started 
2023-07-22 10:57:46 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-07-22 10:57:47 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-07-22 10:57:47 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.5',
  'to' => '3.14.1',
)]
2023-07-22 10:57:50 [info] elementor::elementor_updater Started 
2023-07-22 10:57:50 [info] Elementor/Upgrades - _on_each_version Start  
2023-07-22 10:57:52 [info] Elementor/Upgrades - _on_each_version Finished 
2023-07-22 10:57:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.4',
  'to' => '3.14.1',
)]
2023-07-31 15:49:55 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.14.1',
  'to' => '3.15.0',
)]
2023-07-31 15:49:56 [info] elementor::elementor_updater Started 
2023-07-31 15:49:56 [info] Elementor/Upgrades - _on_each_version Start  
2023-07-31 15:49:59 [info] Elementor/Upgrades - _on_each_version Finished 
2023-07-31 15:49:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.14.1',
  'to' => '3.15.0',
)]

PHP: showing 13 of 13PHP: 2022-06-15 15:23:04 [notice X 353660][D:\web\arcen\wp-content\plugins\elementor\includes\conditions.php::87] Undefined index: motion_fx_transform_x_anchor_point [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-18 14:04:44 [notice X 38][D:\web\arcen\wp-content\plugins\elementor\modules\dev-tools\deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: D:\web\arcen\wp-content\plugins\elementor\modules\dev-tools\deprecation.php(301): class type trigger_error()
#2: D:\web\arcen\wp-content\plugins\elementor\includes\managers\controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: D:\web\arcen\wp-content\plugins\elementor\includes\managers\controls.php(501): Elementor\Controls_Manager -> register()
#4: D:\web\arcen\wp-content\themes\dt-the7\inc\mods\compatibility\elementor\pro\modules\query-control\class-the7-query-control-module.php(803): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-06-18 20:50:01 [notice X 8][D:\web\arcen\wp-content\plugins\elementor\includes\conditions.php::87] Undefined index: motion_fx_transform_x_anchor_point [array (
  'trace' => '
#0: D:\web\arcen\wp-content\plugins\elementor\includes\conditions.php(87): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: D:\web\arcen\wp-content\plugins\elementor\includes\base\controls-stack.php(1368): Elementor\Conditions :: check()
#2: D:\web\arcen\wp-content\plugins\elementor\includes\base\controls-stack.php(1167): Elementor\Controls_Stack -> is_control_visible()
#3: D:\web\arcen\wp-content\plugins\elementor\includes\base\controls-stack.php(1208): Elementor\Controls_Stack -> get_active_settings()
#4: D:\web\arcen\wp-content\plugins\elementor\includes\base\element-base.php(628): Elementor\Controls_Stack -> get_settings_for_display()
',
)]
PHP: 2022-07-25 05:00:34 [notice X 2][D:\web\arcen\wp-content\plugins\elementor\includes\conditions.php::87] Undefined index: motion_fx_transform_x_anchor_point [array (
  'trace' => '
#0: D:\web\arcen\wp-content\plugins\elementor\includes\conditions.php(87): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: D:\web\arcen\wp-content\plugins\elementor\includes\base\controls-stack.php(1368): Elementor\Conditions :: check()
#2: D:\web\arcen\wp-content\plugins\elementor\includes\base\controls-stack.php(1167): Elementor\Controls_Stack -> is_control_visible()
#3: D:\web\arcen\wp-content\plugins\elementor\includes\base\controls-stack.php(1208): Elementor\Controls_Stack -> get_active_settings()
#4: D:\web\arcen\wp-content\plugins\elementor\includes\base\element-base.php(648): Elementor\Controls_Stack -> get_settings_for_display()
',
)]
PHP: 2022-08-10 08:04:36 [notice X 418][D:\web\arcen\wp-content\plugins\elementor\modules\dev-tools\deprecation.php::304] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: D:\web\arcen\wp-content\plugins\elementor\modules\dev-tools\deprecation.php(304): class type trigger_error()
#2: D:\web\arcen\wp-content\plugins\elementor\includes\managers\controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: D:\web\arcen\wp-content\plugins\elementor\includes\managers\controls.php(501): Elementor\Controls_Manager -> register()
#4: D:\web\arcen\wp-content\themes\dt-the7\inc\mods\compatibility\elementor\pro\modules\query-control\class-the7-query-control-module.php(803): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-08-10 08:04:40 [notice X 32][D:\web\arcen\wp-content\plugins\elementor\includes\conditions.php::87] Undefined index: motion_fx_transform_x_anchor_point [array (
  'trace' => '
#0: D:\web\arcen\wp-content\plugins\elementor\includes\conditions.php(87): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: D:\web\arcen\wp-content\plugins\elementor\includes\base\controls-stack.php(1370): Elementor\Conditions :: check()
#2: D:\web\arcen\wp-content\plugins\elementor\includes\base\controls-stack.php(1169): Elementor\Controls_Stack -> is_control_visible()
#3: D:\web\arcen\wp-content\plugins\elementor\includes\base\controls-stack.php(1210): Elementor\Controls_Stack -> get_active_settings()
#4: D:\web\arcen\wp-content\plugins\elementor\includes\base\element-base.php(648): Elementor\Controls_Stack -> get_settings_for_display()
',
)]
PHP: 2022-09-15 19:25:01 [notice X 2][D:\web\arcen\wp-content\plugins\elementor\includes\conditions.php::87] Undefined index: motion_fx_transform_x_anchor_point [array (
  'trace' => '
#0: D:\web\arcen\wp-content\plugins\elementor\includes\conditions.php(87): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: D:\web\arcen\wp-content\plugins\elementor\includes\base\controls-stack.php(1388): Elementor\Conditions :: check()
#2: D:\web\arcen\wp-content\plugins\elementor\includes\base\controls-stack.php(1169): Elementor\Controls_Stack -> is_control_visible()
#3: D:\web\arcen\wp-content\plugins\elementor\includes\base\controls-stack.php(1210): Elementor\Controls_Stack -> get_active_settings()
#4: D:\web\arcen\wp-content\plugins\elementor\includes\base\element-base.php(648): Elementor\Controls_Stack -> get_settings_for_display()
',
)]
PHP: 2022-09-17 22:38:56 [notice X 5][D:\web\arcen\wp-content\plugins\elementor\core\common\modules\ajax\module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-01 16:31:09 [notice X 8][D:\web\arcen\wp-content\plugins\elementor\includes\conditions.php::87] Undefined index: motion_fx_transform_x_anchor_point [array (
  'trace' => '
#0: D:\web\arcen\wp-content\plugins\elementor\includes\conditions.php(87): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: D:\web\arcen\wp-content\plugins\elementor\includes\base\controls-stack.php(1383): Elementor\Conditions :: check()
#2: D:\web\arcen\wp-content\plugins\elementor\includes\base\controls-stack.php(1169): Elementor\Controls_Stack -> is_control_visible()
#3: D:\web\arcen\wp-content\plugins\elementor\includes\base\controls-stack.php(1210): Elementor\Controls_Stack -> get_active_settings()
#4: D:\web\arcen\wp-content\plugins\elementor\includes\base\element-base.php(648): Elementor\Controls_Stack -> get_settings_for_display()
',
)]
PHP: 2022-12-15 15:19:28 [error X 1][D:\web\arcen\wp-content\plugins\elementor-pro\plugin.php::358] Uncaught Error: Class 'ElementorPro\Core\Modules_Manager' not found in D:\web\arcen\wp-content\plugins\elementor-pro\plugin.php:358
Stack trace:
#0 D:\web\arcen\wp-includes\class-wp-hook.php(308): ElementorPro\Plugin->on_elementor_init()
#1 D:\web\arcen\wp-includes\class-wp-hook.php(332): WP_Hook->apply_filters()
#2 D:\web\arcen\wp-includes\plugin.php(517): WP_Hook->do_action()
#3 D:\web\arcen\wp-content\plugins\elementor\includes\plugin.php(652): do_action()
#4 D:\web\arcen\wp-includes\class-wp-hook.php(308): Elementor\Plugin->init()
#5 D:\web\arcen\wp-includes\class-wp-hook.php(332): WP_Hook->apply_filters()
#6 D:\web\arcen\wp-includes\plugin.php(517): WP_Hook->do_action()
#7 D:\web\arcen\wp-settings.php(617): do_action()
#8 D:\web\arcen\wp-config.php(96): require_once('D:\\web\\arcen\\wp...')
#9 D:\web\arcen\wp-load.php(50): require_once('D:\\web\\arcen\\wp...')
#10 D:\web\arcen\wp-blog-header.php(13): require_once('D:\\web\\arcen\\wp...')
#11 D:\web\arcen\index.php(17): require('D:\\web\\arcen\\wp...')
#1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-29 03:19:11 [error X 1][D:\web\arcen\wp-content\plugins\elementor\includes\plugin.php::744] Uncaught Error: Class 'Elementor\App\App' not found in D:\web\arcen\wp-content\plugins\elementor\includes\plugin.php:744
Stack trace:
#0 D:\web\arcen\wp-content\plugins\elementor\includes\plugin.php(641): Elementor\Plugin->init_components()
#1 D:\web\arcen\wp-includes\class-wp-hook.php(308): Elementor\Plugin->init()
#2 D:\web\arcen\wp-includes\class-wp-hook.php(332): WP_Hook->apply_filters()
#3 D:\web\arcen\wp-includes\plugin.php(517): WP_Hook->do_action()
#4 D:\web\arcen\wp-settings.php(617): do_action()
#5 D:\web\arcen\wp-config.php(96): require_once('D:\\web\\arcen\\wp...')
#6 D:\web\arcen\wp-load.php(50): require_once('D:\\web\\arcen\\wp...')
#7 D:\web\arcen\wp-login.php(12): require('D:\\web\\arcen\\wp...')
#8 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-05 18:45:06 [error X 7][D:\web\arcen\wp-content\plugins\elementor\core\wp-api.php::26] Uncaught Error: Call to undefined function Elementor\Core\get_plugins() in D:\web\arcen\wp-content\plugins\elementor\core\wp-api.php:26
Stack trace:
#0 D:\web\arcen\wp-content\plugins\elementor\modules\compatibility-tag\base-module.php(96): Elementor\Core\Wp_Api->get_plugins()
#1 D:\web\arcen\wp-content\plugins\elementor\modules\compatibility-tag\base-module.php(58): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_with_header()
#2 D:\web\arcen\wp-content\plugins\elementor\modules\compatibility-tag\module.php(57): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_to_check()
#3 D:\web\arcen\wp-content\plugins\elementor\modules\compatibility-tag\base-module.php(148): Elementor\Modules\CompatibilityTag\Module->get_plugins_to_check()
#4 D:\web\arcen\wp-includes\class-wp-hook.php(308): Elementor\Modules\CompatibilityTag\Base_Module->Elementor\Modules\CompatibilityTag\{closure}()
#5 D:\web\arcen\wp-includes\class-wp-hook.php(332): WP_Hook->apply_filters()
#6 D:\web\arcen\wp-includes\plugin.php( [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-31 15:50:12 [notice X 1][D:\web\arcen\wp-content\plugins\elementor\core\kits\manager.php::323] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Incompatible

== Elementor Pro - Compatibility Tag ==

````

</details>

**Comment by nicholaszein** [comment]
Hello @x4000,

Thanks for contacting us! 🙏 

### 🛟 This is more of a support question, not really something we can help with here. 

👉 Please remember to check the [Help Center](https://elementor.com/help) or contact [Elementor Support](https://elementor.com/contact) before submitting an issue.

Elementor does not have the capability of deleting itself. Your issue seems to be caused by server limitations. This usually happens when your server resources and configuration are too limited, and the installation times out and fails. 

You can try to update the plugin manually by downloading and installing a copy from the [WordPress repository](https://wordpress.org/plugins/elementor/), or increasing the following settings:

- PHP Max Execution time >= 60
- PHP Max Input Time >= 60
- PHP Max Input Vars >= 5000
- PHP Memory Limit >= 256M
- PHP Max Post Size >= 256M
- WordPress Memory Limit >= 256M
- WordPress Max Memory Limit >= 256M
- WordPress Max Upload Size >= 128M

#### 👍 For now, that's all we can help with. 

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

### ⚠️ As a gentle reminder, support request issues may need to be closed without troubleshooting. Remember to always follow our [Bug Report Guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&projects=&template=bug.yml).

Kind regards
