### ISSUE TITLE
3:15 : bug in nested carousel widget and loop carousel

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#23250]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

If we set the Space From slides option to none in the nested carousel > pagination widget settings, it will cause the navigation icons not to be centered vertically (They are placed about 10px above the center). This bug probably also occurs in the loop carousel widget. I have not checked it.

### Steps to reproduce

In the pagination settings of this widget, set the Space From slides option to none. If you check the result in the front end, the arrows are slightly above the center.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

					
== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.38 (Win32) OpenSSL/1.1.1a PHP/7.3.2
	MySQL version: mariadb.org binary distribution v5.6.42-84.2
	PHP Version: 7.3.2
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2.2
	Site URL: http://localhost:80/elementor
	Home URL: http://localhost:80/elementor
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 60M
	Max Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: Europe/Berlin
	Admin Email: Michaelgimii@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.7.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.15.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.15.0
		Author: Elementor.com

== Features ==
	Custom Fonts: 1
	Custom Icons: 0

== Integrations ==
	

== Elementor Experiments ==
	Optimized DOM Output: Inactive
	Improved Asset Loading: Inactive
	Improved CSS Loading: Inactive
	Inline Font Icons: Inactive
	Additional Custom Breakpoints: Inactive
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active
	Grid Container: Active
	Default to New Theme Builder: Inactive
	Hello Theme Header & Footer: Inactive
	Editor Top Bar: Active
	Landing Pages: Inactive
	Nested Elements: Active
	Lazy Load Background Images: Inactive
	Global Style Guide: Inactive by default
	Page Transitions: Inactive
	Notes: Inactive
	Loop: Active
	Form Submissions: Active by default
	Scroll Snap: Inactive
	Menu: Active
	Taxonomy Filter: Inactive by default

== Log ==
	
JS: showing 12 of 12JS: 2023-05-19 07:47:47 [error X 8][http://localhost:85/elementor/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.13.2:3:1097282] Cannot read properties of null (reading 'getBoundingClientRect') 
JS: 2023-05-19 08:28:21 [error X 5][http://localhost:85/elementor/wp-content/plugins/elementor/assets/js/7fada1a61d72da6d46ab.bundle.min.js:2:7826] Cannot read properties of null (reading 'dataset') 
JS: 2023-05-27 22:07:09 [error X 1][http://localhost:85/elementor/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view3596") has already been destroyed and cannot be used. 
JS: 2023-05-29 13:06:40 [error X 1][http://localhost:85/elementor/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view1682") has already been destroyed and cannot be used. 
JS: 2023-05-29 13:20:42 [error X 3][http://localhost:85/elementor/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view1250") has already been destroyed and cannot be used. 
JS: 2023-06-01 13:21:06 [error X 1][http://localhost:85/elementor/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view1791") has already been destroyed and cannot be used. 
JS: 2023-06-01 22:27:06 [error X 1][http://localhost:85/elementor/wp-content/plugins/elementor/assets/js/7fada1a61d72da6d46ab.bundle.min.js:2:8038] Cannot read properties of undefined (reading 'view') 
JS: 2023-06-04 10:03:41 [error X 6][http://localhost:85/elementor/wp-admin/load-scripts.php?c=1&loadchunk_0=jquery-ui-draggable,react,react-dom,mce-view,imgareaselect&ver=6.2.2:29:23751] Cannot read properties of undefined (reading 'setValue') 
JS: 2023-06-11 14:54:44 [error X 1][http://localhost:85/elementor/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view6962") has already been destroyed and cannot be used. 
JS: 2023-06-11 14:56:46 [error X 1][http://localhost:85/elementor/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view10324") has already been destroyed and cannot be used. 
JS: 2023-06-21 14:54:50 [error X 1][http://localhost:85/elementor/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.14.0:3:284423] Cannot read properties of undefined (reading 'toggleClass') 
JS: 2023-07-10 22:15:21 [error X 2][http://localhost:85/elementor/wp-content/plugins/elementor-pro/assets/js/preloaded-elements-handlers.min.js?ver=3.14.0:2:116074] Failed to execute 'observe' on 'IntersectionObserver': parameter 1 is not of type 'Element'. 

PHP: showing 6 of 6PHP: 2023-05-19 12:19:14 [notice X 33][C:\xampp\htdocs\elementor\wp-content\plugins\elementor\core\common\modules\ajax\module.php::175] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-19 12:52:24 [notice X 4][C:\xampp\htdocs\elementor\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-manager.php::171] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-06-11 21:14:35 [notice X 9][C:\xampp\htdocs\elementor\wp-content\plugins\elementor-pro\modules\woocommerce\module.php::381] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-06-24 01:11:13 [error X 1][C:\xampp\htdocs\elementor\wp-content\plugins\elementor\includes\template-library\sources\local.php::1112] Uncaught TypeError: Argument 2 passed to Elementor\TemplateLibrary\Source_Local::on_save_post() must be an instance of WP_Post, instance of stdClass given, called in C:\xampp\htdocs\elementor\wp-includes\class-wp-hook.php on line 310 and defined in C:\xampp\htdocs\elementor\wp-content\plugins\elementor\includes\template-library\sources\local.php:1112
Stack trace:
#0 C:\xampp\htdocs\elementor\wp-includes\class-wp-hook.php(310): Elementor\TemplateLibrary\Source_Local->on_save_post(8138, Object(stdClass))
#1 C:\xampp\htdocs\elementor\wp-includes\class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#2 C:\xampp\htdocs\elementor\wp-includes\plugin.php(517): WP_Hook->do_action(Array)
#3 C:\xampp\htdocs\elementor\wp-includes\post.php(4715): do_action('save_post', 8138, Object(stdClass), true)
#4 C:\xampp\htdocs\elementor\wp-includes\post.php(4817): wp_insert_post(Array, false, true)
#5 C:\xampp\htdocs\elementor\wp-content\plugins\elementor\includes\db.php(235): wp_update_post(Array)
#6 C:\xampp\htdocs\elemento [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-11 02:45:11 [error X 1][C:\xampp\htdocs\elementor\wp-content\plugins\elementor\includes\template-library\sources\local.php::1112] Uncaught TypeError: Argument 2 passed to Elementor\TemplateLibrary\Source_Local::on_save_post() must be an instance of WP_Post, null given, called in C:\xampp\htdocs\elementor\wp-includes\class-wp-hook.php on line 310 and defined in C:\xampp\htdocs\elementor\wp-content\plugins\elementor\includes\template-library\sources\local.php:1112
Stack trace:
#0 C:\xampp\htdocs\elementor\wp-includes\class-wp-hook.php(310): Elementor\TemplateLibrary\Source_Local->on_save_post(8269, NULL)
#1 C:\xampp\htdocs\elementor\wp-includes\class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#2 C:\xampp\htdocs\elementor\wp-includes\plugin.php(517): WP_Hook->do_action(Array)
#3 C:\xampp\htdocs\elementor\wp-includes\post.php(4715): do_action('save_post', 8269, NULL, true)
#4 C:\xampp\htdocs\elementor\wp-includes\post.php(4817): wp_insert_post(Array, false, true)
#5 C:\xampp\htdocs\elementor\wp-content\plugins\elementor\includes\db.php(235): wp_update_post(Array)
#6 C:\xampp\htdocs\elementor\wp-content\plugins\elementor\core\base [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-13 00:25:14 [error X 10][C:\xampp\htdocs\elementor\wp-content\plugins\elementor-pro\modules\woocommerce\tags\product-rating.php::6] Maximum execution time of 30 seconds exceeded [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 20 of 252023-06-19 18:54:54 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.13.1',
  'to' => '3.14.0',
)]
2023-06-19 18:55:26 [info] elementor::elementor_updater Started 
2023-06-19 18:55:26 [info] Elementor/Upgrades - _on_each_version Start  
2023-06-19 18:55:26 [info] Elementor/Upgrades - _on_each_version Finished 
2023-06-19 18:55:26 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.2',
  'to' => '3.14.0',
)]
2023-06-19 18:55:27 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.2',
  'to' => '3.14.0',
)]
2023-07-27 17:40:04 [info] elementor::elementor_updater Started 
2023-07-27 17:40:05 [info] Elementor/Upgrades - _on_each_version Start  
2023-07-27 17:40:05 [info] Elementor/Upgrades - _on_each_version Finished 
2023-07-27 17:40:05 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.14.0',
  'to' => '3.14.1',
)]
2023-07-27 17:40:08 [info] elementor-pro::elementor_pro_updater Started 
2023-07-27 17:40:08 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-07-27 17:40:08 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-07-27 17:40:08 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.14.0',
  'to' => '3.14.1',
)]
2023-07-27 17:40:10 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.14.0',
  'to' => '3.14.1',
)]
2023-08-01 14:55:35 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.14.1',
  'to' => '3.15.0',
)]
2023-08-01 14:55:39 [info] elementor::elementor_updater Started 
2023-08-01 14:55:39 [info] Elementor/Upgrades - _on_each_version Start  
2023-08-01 14:55:39 [info] Elementor/Upgrades - _on_each_version Finished 
2023-08-01 14:55:39 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.14.1',
  'to' => '3.15.0',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hi @Michaelgimii! 

Thank you for submitting your issue! 🙏 

We are aware of this issue and our team is already working on a fix. We can’t say exactly when it'll be sorted out, but we kindly ask for your patience. Thanks for understanding! 😉

Best regards
