### ISSUE TITLE
Stripe Button widget fails to use dynamic tags

### ISSUE THREAD

**Issue by Dudeney95** [elementor/elementor#23254]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hey Elementor,

I am using the Stripe Button widget to take payment for products.

Each product has a different name and a different price so I am using the dynamic tags feature to populate the "Product Name" field and the "Product Price" field.

However, when clicking the stripe button to make payment, neither fields using the dynamic tags show the dynamic data properly.

Sadly, only static values seem to work.

### Steps to reproduce

1) Import some products
2) Create single product templates for these products
3) Add a Stripe button widget to the templates
4) Use the dynamic tags function to populate the:
- Product Name. I used the "Post Title" tag
- Product Price. I used the "WooCommerce Product Price" tag
5) Save the template
6) As a front-end user, view the published product and click the button.
7) You'll be taken to stripe but notice the product name is not the post title, but in fact the template title.
8) You'll notice the Stripe checkout will not open with a dynamic price tag added.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.39-42
	PHP Version: 7.4.33
	PHP Memory Limit: 768M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2.2
	Site URL: https://shop.triggerhub.org
	Home URL: https://shop.triggerhub.org
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 256M
	Max Memory limit: 768M
	Permalink Structure: /%postname%
	Language: en-GB
	Timezone: 0
	Admin Email: elementor@triggerhub.org
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.8.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.188

== Active Plugins ==
	AffiliateWP
		Version: 2.15.0
		Author: AffiliateWP

	AffiliateWP - Affiliate Area Shortcodes
		Version: 1.3.1
		Author: AffiliateWP

	Code Snippets
		Version: 3.4.2
		Author: Code Snippets Pro

	Elementor
		Version: 3.14.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.14.1
		Author: Elementor.com

	Glassboxx for WooCommerce
		Version: 2.0.6
		Author: Glassboxx

	JetEngine
		Version: 3.2.2
		Author: Crocoblock

	JetPopup
		Version: 2.0.0
		Author: Crocoblock

	JetSearch
		Version: 3.1.0
		Author: Crocoblock

	JetSmartFilters
		Version: 3.1.2
		Author: Crocoblock

	Perfmatters
		Version: 2.1.3
		Author: forgemedia

	Radio Buttons for Taxonomies
		Version: 2.4.7
		Author: helgatheviking

	Rank Math SEO
		Version: 1.0.119.1
		Author: Rank Math

	SiteGround Security
		Version: 1.4.5
		Author: SiteGround

	WooCommerce
		Version: 7.9.0
		Author: Automattic

	WooCommerce PayPal Payments
		Version: 2.2.0
		Author: WooCommerce

	WooCommerce Stripe Gateway
		Version: 7.4.2
		Author: WooCommerce

	WP All Export - WooCommerce Export Add-On Pro
		Version: 1.0.6
		Author: Soflyy

	WP All Export Pro
		Version: 1.8.3
		Author: Soflyy

== Elements Usage ==
	
	container : 1
		container : 7
		nested-tabs : 1
		text-editor : 7
	footer : 1
		container : 7
		heading : 2
		icon-list : 1
		image : 4
		nav-menu : 2
		social-icons : 1
		text-editor : 1
		theme-site-logo : 1
	header : 1
		button : 2
		container : 9
		icon : 1
		jet-ajax-search : 1
		mega-menu : 1
		nav-menu : 1
		theme-site-logo : 1
		woocommerce-menu-cart : 1
	page : 1
		button : 6
		container : 33
		form : 1
		heading : 10
		html : 1
		image : 7
		image-carousel : 3
		menu-anchor : 3
		nested-tabs : 3
		testimonial-carousel : 1
		text-editor : 11
		toggle : 1
	popup : 4
		container : 5
		form : 1
		heading : 7
		icon-box : 6
		jet-listing-dynamic-field : 1
		stripe-button : 1
		text-editor : 4
	product : 7
		button : 8
		container : 69
		heading : 35
		icon-box : 42
		icon-list : 4
		image : 7
		jet-listing-dynamic-field : 67
		jet-listing-dynamic-terms : 26
		jet-listing-grid : 7
		share-buttons : 7
		stripe-button : 1
		tabs : 7
		woocommerce-breadcrumb : 7
		woocommerce-product-add-to-cart : 6
		woocommerce-product-price : 6
		woocommerce-product-title : 14
	wp-page : 11
		button : 6
		call-to-action : 2
		container : 31
		divider : 2
		form : 2
		heading : 22
		icon : 1
		icon-list : 1
		image : 8
		image-carousel : 1
		jet-listing-grid : 7
		jet-smart-filters-check-range : 1
		jet-smart-filters-checkboxes : 1
		jet-smart-filters-pagination : 2
		jet-smart-filters-sorting : 1
		share-buttons : 1
		text-editor : 8
		wc-categories : 1
		woocommerce-breadcrumb : 1
		woocommerce-cart : 1
		woocommerce-checkout-page : 1
		woocommerce-my-account : 1
		woocommerce-purchase-summary : 1
	search-results : 1
		container : 1
		jet-listing-grid : 1
		theme-archive-title : 1
	product-archive : 2
		author-box : 1
		button : 1
		call-to-action : 2
		container : 9
		heading : 2
		jet-listing-dynamic-field : 2
		jet-listing-dynamic-link : 1
		jet-listing-grid : 2
		jet-smart-filters-check-range : 1
		jet-smart-filters-checkboxes : 1
		jet-smart-filters-pagination : 2
		jet-smart-filters-sorting : 2
		theme-archive-title : 1
		woocommerce-archive-description : 1
		woocommerce-breadcrumb : 2
	jet-popup : 1
		container : 1
		heading : 1
		jet-smart-filters-check-range : 1
		jet-smart-filters-checkboxes : 1
	jet-listing-items : 0
		author-box : 1
		button : 1
		container : 4
		heading : 5
		image : 1
		jet-listing-dynamic-image : 1
		post-info : 1
		text-editor : 1
		theme-post-featured-image : 1
		theme-post-title : 1
	error-404 : 1
		container : 1
		heading : 1
		jet-ajax-search : 1
		text-editor : 1

== Settings ==
	
	cpt_support: post, page, jet-popup, jet-popup
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap

== Features ==
	Custom Fonts: 1
	Custom Icons: 0

== Integrations ==
	
	woocommerce: Active

== Elementor Experiments ==
	Optimised DOM Output: Active
	Improved asset loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility improvements: Active
	Additional Custom Breakpoints: Inactive
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Inactive by default
	Grid Container: Inactive by default
	Default to New Theme Builder: Inactive
	Hello Theme Header & Footer: Inactive
	Editor Top Bar: Inactive by default
	Landing pages: Inactive
	Nested Elements: Active
	Nested Accordion: Inactive by default
	Lazy Load Background Images: Inactive
	Global Style Guide: Active
	Page Transitions: Inactive
	Notes: Inactive
	Loop: Inactive
	Form Submissions: Active
	Scroll Snap: Inactive
	Menu: Active

== Log ==
	
Log: showing 20 of 292023-06-26 09:04:37 [info] elementor::elementor_updater Started 
2023-06-26 09:04:37 [info] Elementor/Upgrades - _on_each_version Start  
2023-06-26 09:04:37 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.4',
  'to' => '3.14.0',
)]
2023-06-26 09:04:38 [info] Elementor/Upgrades - _on_each_version Finished 
2023-06-26 09:04:38 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.4',
  'to' => '3.14.0',
)]
2023-06-26 09:04:42 [info] elementor-pro::elementor_pro_updater Started 
2023-06-26 09:04:42 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-06-26 09:04:42 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-06-26 09:04:42 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.13.2',
  'to' => '3.14.0',
)]
2023-06-26 09:04:42 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.13.2',
  'to' => '3.14.0',
)]
2023-06-28 10:16:03 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.14.0',
  'to' => '3.14.1',
)]
2023-06-28 10:16:04 [info] elementor::elementor_updater Started 
2023-06-28 10:16:04 [info] Elementor/Upgrades - _on_each_version Start  
2023-06-28 10:16:05 [info] Elementor/Upgrades - _on_each_version Finished 
2023-06-28 10:16:05 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.14.0',
  'to' => '3.14.1',
)]
2023-06-28 10:16:09 [info] elementor-pro::elementor_pro_updater Started 
2023-06-28 10:16:09 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-06-28 10:16:09 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-06-28 10:16:09 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.14.0',
  'to' => '3.14.1',
)]
2023-06-28 10:16:09 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.14.0',
  'to' => '3.14.1',
)]

JS: showing 5 of 5JS: 2023-06-13 10:08:12 [error X 4][https://shop.triggerhub.org/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.13.4:3:794943] Cannot read properties of undefined (reading 'toLowerCase') 
JS: 2023-06-13 10:08:21 [error X 6][https://shop.triggerhub.org/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.13.4:3:795450] Cannot read properties of undefined (reading 'localized') 
JS: 2023-06-13 10:16:21 [error X 3][https://shop.triggerhub.org/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.13.4:3:634710] Cannot read properties of undefined (reading 'isDesignable') 
JS: 2023-07-14 09:55:39 [error X 1][https://shop.triggerhub.org/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view3624") has already been destroyed and cannot be used. 
JS: 2023-08-01 11:21:14 [error X 1][https://shop.triggerhub.org/wp-content/plugins/elementor/assets/js/new-template.min.js?ver=3.14.1:2:2932] elementor_new_template_form_controls is not defined 

PHP: showing 8 of 8PHP: 2023-06-16 08:10:14 [notice X 1][/home/customer/www/shop.triggerhub.org/public_html/wp-content/plugins/elementor/modules/history/revisions-manager.php::363] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-06-16 08:18:21 [notice X 4][/home/customer/www/shop.triggerhub.org/public_html/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/fonts-manager.php::252] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-06-26 11:50:46 [notice X 6][/home/customer/www/shop.triggerhub.org/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-06-28 10:16:53 [notice X 118][/home/customer/www/shop.triggerhub.org/public_html/wp-content/plugins/elementor/includes/conditions.php::87] Undefined index: checkout_layout [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-01 09:25:47 [notice X 2][/home/customer/www/shop.triggerhub.org/public_html/wp-content/plugins/elementor/app/modules/import-export/module.php::734] Trying to get property 'label' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-01 09:26:15 [error X 12][/home/customer/www/shop.triggerhub.org/public_html/wp-content/plugins/elementor-pro/modules/payments/module.php::142] Uncaught Error: Call to undefined method ElementorPro\Core\Utils::_unstable_check_document_permissions() in /home/customer/www/shop.triggerhub.org/public_html/wp-content/plugins/elementor-pro/modules/payments/module.php:142
Stack trace:
#0 [internal function]: ElementorPro\Modules\Payments\Module->get_stripe_tax_rates(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#1 /home/customer/www/shop.triggerhub.org/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/customer/www/shop.triggerhub.org/public_html/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#3 /home/customer/www/shop.triggerhub.org/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#4 /home/customer/www/shop.triggerhub.org/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#5 /home/customer/www/shop.triggerhub.org/public_ht [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-01 11:25:53 [notice X 5][/home/customer/www/shop.triggerhub.org/public_html/wp-content/plugins/elementor-pro/modules/payments/module.php::309] Undefined index: stripe_live_env_tax_rates_list [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-01 11:26:31 [warning X 2][/home/customer/www/shop.triggerhub.org/public_html/wp-content/plugins/elementor-pro/modules/payments/module.php::250] A non-numeric value encountered [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

**Comment by Dudeney95** [comment]
Hey @nicholaszein 

Any update on this one please? Support confirm they experience the issue too.

Or any code snippet workarounds for the time being?

Cheers

**Comment by phonefuck** [comment]
Hi, any fix please? 
Cheers

**Comment by harrissetyawan** [comment]
Any fix yet?
I also faced the same problem.
I use shortcode within dynamic tag to populate the price.
In my shortcode, it contains calculations logic from query parameters as variables then return the calculations result.
When i test it using shortcode widget or other widget, it does return the actual value. But when I use this shortcode in dynamic tag within stripe button widget. It returns $0.0 in stripe checkout page.
And there's also something strange, when i write return value using fixed value in my shortcode. The checkout page catch it.
I hope there's someone figuring this out.

**Comment by Connessioni-Creative** [comment]
I have the same problem using for product name a dynamic tag with get parameter: any solution?
