### ISSUE TITLE
⛔ 🧩 🐞 Bug Report: Pods fields with "allow multiple" crash Elementor editor when used in Dynamic Tags

### ISSUE THREAD

**Issue by Erudition** [elementor/elementor#23283]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When I use Dynamic Tags to select a Pods field, it normally works fine, but I found one day my page was never able to be opened again in the Elementor editor (just an internal server error). I had to export the template, manually remove all dynamic tags from the JSON, and re-import it to fix.

I now know the source of the error: Elementor is not aware of multiple-valued Pods fields, yet it lets you select them; when you do, there is a PHP warning about unknown array index (in Elementor) and a subsequent PHP error about $haystack not being a string (in Wordpress main loop). The tell-tale sign is that the block is lightened in transparency (as it usually does when you make a change) permanently rather than temporarily (though reversing the change and selecting elsewhere brings it back). If you save the page in this state, the editor can no longer open this page.

Switching the pods fields to be single-valued allows me to use everything normally.

### Steps to reproduce

1) Create  pod with a field that has "allow multiple" checked
2) Add value(s) to the field
3) Use the field in Elementor via Dynamic Tags

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>Click to reveal</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: h2o/2.2.6
	MySQL version: MySQL Community Server (GPL) v5.7.12
	PHP Version: 8.0.29
	PHP Memory Limit: 1024M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 518M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2.2
	Site URL: https://3215b04c-84e4-4a42-8132-902bb6d4b51e.static.getshifter.net
	Home URL: https://3215b04c-84e4-4a42-8132-902bb6d4b51e.static.getshifter.net
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 256M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/Chicago
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.7.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/113.0

== Active Plugins ==
	Code Snippets
		Version: 3.4.2
		Author: Code Snippets Pro

	DynamicConditions
		Version: 1.6.2
		Author: RTO GmbH

	Elementor
		Version: 3.15.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.15.0
		Author: Elementor.com

	Enable Media Replace
		Version: 4.1.2
		Author: ShortPixel

	Pods - Custom Content Types and Fields
		Version: 2.9.19
		Author: Pods Framework Team

	Regenerate Thumbnails Advanced
		Version: 2.4.1
		Author: ShortPixel

	WP File Manager
		Version: 7.1.9
		Author: mndpsingh287

	WP Import Export Lite
		Version: 3.9.24
		Author: VJInfotech


== Must-Use Plugins ==
	EVA
		Version: 1.6.4
		Author: DigitalCube


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Additional Custom Breakpoints: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active
	Grid Container: Active
	Default to New Theme Builder: Active
	Hello Theme Header & Footer: Active
	Editor Top Bar: Active
	Landing Pages: Active
	Nested Elements: Active
	Lazy Load Background Images: Active
	Global Style Guide: Inactive by default
	Page Transitions: Active
	Notes: Active
	Loop: Active
	Form Submissions: Active
	Scroll Snap: Active
	Menu: Active
	Taxonomy Filter: Inactive by default


== Log ==
	
Log: showing 20 of 282023-07-12 01:45:12 [info] elementor-pro::elementor_pro_updater Started 
2023-07-12 01:45:12 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-07-12 01:45:12 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-07-12 01:45:12 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.14.0',
  'to' => '3.14.1',
)]
2023-07-12 01:45:12 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.14.0',
  'to' => '3.14.1',
)]
2023-08-02 09:37:50 [info] elementor::elementor_updater Started 
2023-08-02 09:37:50 [info] Elementor/Upgrades - _on_each_version Start  
2023-08-02 09:37:50 [info] Elementor/Upgrades - _on_each_version Finished 
2023-08-02 09:37:50 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.14.1',
  'to' => '3.15.0',
)]
2023-08-02 09:37:50 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.14.1',
  'to' => '3.15.0',
)]
2023-08-02 13:47:07 [info] elementor::elementor_updater Started 
2023-08-02 13:47:07 [info] Elementor/Upgrades - _on_each_version Start  
2023-08-02 13:47:07 [info] Elementor/Upgrades - _on_each_version Finished 
2023-08-02 13:47:07 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.15.0',
  'to' => '3.15.1',
)]
2023-08-02 13:47:07 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.15.0',
  'to' => '3.15.1',
)]
2023-08-02 13:48:44 [info] elementor-pro::elementor_pro_updater Started 
2023-08-02 13:48:44 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-08-02 13:48:44 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-08-02 13:48:44 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.14.1',
  'to' => '3.15.0',
)]
2023-08-02 13:48:44 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.14.1',
  'to' => '3.15.0',
)]

JS: showing 4 of 4JS: 2023-06-22 16:15:42 [error X 2][https://3215b04c-84e4-4a42-8132-902bb6d4b51e.static.getshifter.net/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.14.0:3:601336] elementor.documents.getCurrent() is null 
JS: 2023-07-12 05:45:33 [error X 12][https://3215b04c-84e4-4a42-8132-902bb6d4b51e.static.getshifter.net/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.14.0:3:1110046] V is null 
JS: 2023-07-12 06:58:08 [error X 7][https://3215b04c-84e4-4a42-8132-902bb6d4b51e.static.getshifter.net/wp-content/plugins/elementor/assets/js/admin.min.js?ver=3.14.1:3:48021] l[0] is undefined 
JS: 2023-07-12 15:14:05 [error X 1][https://3215b04c-84e4-4a42-8132-902bb6d4b51e.static.getshifter.net/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.14.1:2:31128] elementor.settings.page is undefined 

PHP: showing 10 of 10PHP: 2023-06-22 11:18:23 [warning X 90][../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key "condition_type" [array (
  'trace' => '
#0: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: ../wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2023-06-22 11:41:53 [warning X 5][../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::171] Undefined array key "editor_post_id" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-12 00:14:31 [warning X 1][../wp-content/plugins/elementor/core/files/file-types/svg.php::234] simplexml_load_file(): I/O warning : failed to load external entity "/wp-content/uploads/2023/07/insta-icon.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-12 00:14:56 [warning X 1][../wp-content/plugins/elementor/core/files/file-types/svg.php::234] simplexml_load_file(): I/O warning : failed to load external entity "/wp-content/uploads/2023/07/shark-logo_white.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-12 01:02:25 [error X 2][../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::304] Uncaught Error: Call to a member function update_meta() on null in ../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:304
Stack trace:
#0 ../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(177): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(311, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 ../wp-content/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 ../wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 ../wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#5 ../wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 ../wp-admin/admin-ajax.php(188): do_action('wp_ajax_element...')
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-12 01:03:38 [error X 2][../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::304] Uncaught Error: Call to a member function update_meta() on null in ../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:304
Stack trace:
#0 ../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(177): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(394, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 ../wp-content/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 ../wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 ../wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#5 ../wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 ../wp-admin/admin-ajax.php(188): do_action('wp_ajax_element...')
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-20 23:15:21 [warning X 3][../wp-content/plugins/elementor-pro/modules/query-control/module.php::767] Attempt to read property "name" on null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-02 12:37:42 [warning X 10][../wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-02 13:52:15 [warning X 1][../wp-content/plugins/elementor-pro/modules/dynamic-tags/pods/tags/pods-text.php::20] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-02 15:16:21 [warning X 18][../wp-content/plugins/elementor-pro/modules/dynamic-tags/pods/tags/pods-url.php::56] Array to string conversion [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==
	

				

````

</details>

**Comment by nicholaszein** [comment]
Hi, @Erudition,

Thank you for reaching out! 🙏 

### ⛔ After reviewing your report we concluded this is not a bug caused by Elementor. The feature you're referring to is not yet supported.

Elementor does not support repeatable fields. You should not use this feature with Dynamic Tags. Make sure you check the [documentation](https://elementor.com/help/elementor-integration-with-pods/) to learn what fields are supported. Any field in the list that has the "allow multiple" feature will not work.

If you think this should be an Elementor feature, please submit a new [🚀 Feature Request](https://github.com/orgs/elementor/discussions/new?category=feature-request), and we will consider it in the future if there is enough demand (votes) from other users.

Kind regards
