### ISSUE TITLE
Uncaught TypeError: array_merge(): Argument #2 must be of type array, bool given in elementor/includes/managers/controls.php:810

### ISSUE THREAD

**Issue by nelero** [elementor/elementor#23294]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

With the latest version of Elementor, an Fatal error happens
Uncaught TypeError: array_merge(): Argument #2 must be of type array, bool given in /htdocs/wp-content/plugins/elementor/includes/managers/controls.php:810

It seems related to Addons or Themes. And that's not the point of this issue. 

In order to prevent this, could you secure your call on line 810 and check if argument 2 is_array ? before array_merge it ?

### Steps to reproduce

Use elementor with a theme or addon wich doesn't provide all the args waited by Elementor.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.6.14
	PHP Version: 8.2.8
	PHP Memory Limit: 512M
	PHP Max Input Vars: 250000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2.2
	Site URL: https://mywebsite
	Home URL: https://mywebsite.fr
	WP Multisite: No
	Max Upload Size: 512 Mo
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: fr-FR
	Timezone: Europe/Paris
	Admin Email: webmaster@mywebsite.fr
	Debug Mode: Inactive

== Theme ==
	Name: Bridge
	Version: 29.1
	Author: Qode Interactive
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: fr_FR
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36

== Active Plugins ==
	Akismet Anti-Spam: Spam Protection
		Version: 5.2
		Author: Automattic - Anti Spam Team

	BackWPup
		Version: 4.0.0
		Author: Inpsyde GmbH

	Bridge Core
		Version: 3.0.5
		Author: Qode

	Contact Form 7
		Version: 5.7.7
		Author: Takayuki Miyoshi

	Duplicate Page
		Version: 4.5.2
		Author: mndpsingh287

	Elementor
		Version: 3.15.1
		Author: Elementor.com

	Envato Market
		Version: 2.0.10
		Author: Envato

	LayerSlider
		Version: 7.6.9
		Author: Kreatura Media

	Loco Translate
		Version: 2.6.4
		Author: Tim Whitlock

	MainWP Child
		Version: 4.4.1.3
		Author: MainWP

	Qi Addons For Elementor
		Version: 1.6.2
		Author: Qode Interactive

	Qi Blocks
		Version: 1.2.2
		Author: Qode Interactive

	Qode Instagram Widget
		Version: 2.1.3
		Author: Qode Themes

	Qode Twitter Feed
		Version: 2.0.4
		Author: Qode Themes

	Redirection
		Version: 5.3.10
		Author: John Godley

	Slider Revolution
		Version: 6.6.14
		Author: ThemePunch

	Smash Balloon Instagram Feed
		Version: 6.1.6
		Author: Smash Balloon

	Wordfence Security
		Version: 7.10.3
		Author: Wordfence

	WP-Matomo Integration
		Version: 1.0.28
		Author: André Bräkling

	WPBakery Page Builder
		Version: 6.13.0
		Author: Michael M - WPBakery.com

	WPS Hide Login
		Version: 1.9.8
		Author: WPServeur, NicolasKulka, wpformation

== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

== Expériences d’Elementor ==
	Sortie DOM optimisée: Actif par défaut
	Amélioration du chargement des ressources: Actif par défaut
	Optimisation du chargement du CSS: Actif par défaut
	Polices d’icônes « inline »: Inactif par défaut
	Points d’arrêt personnalisés supplémentaires: Actif par défaut
	admin_menu_rearrangement: Inactif par défaut
	Conteneur Flexbox: Inactif par défaut
	Mettre à niveau la bibliothèque Swiper: Inactif par défaut
	Conteneur grille: Inactif par défaut
	Barre supérieure de l’éditeur: Inactif par défaut
	Page d’atterrissage: Actif par défaut
	Éléments imbriqués: Inactif par défaut
	Chargement différé des images d’arrière-plan: Inactif par défaut
	Guide de style global: Inactif par défaut

== Journal ==
	
Log: showing 20 of 382023-06-19 14:35:28 [info] elementor::elementor_updater Started 
2023-06-19 14:35:28 [info] Elementor/Upgrades - _on_each_version Start  
2023-06-19 14:35:28 [info] Elementor/Upgrades - _on_each_version Finished 
2023-06-19 14:35:28 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.4',
  'to' => '3.14.0',
)]
2023-06-26 15:15:40 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.14.0',
  'to' => '3.14.1',
)]
2023-06-26 15:15:40 [info] elementor::elementor_updater Started 
2023-06-26 15:15:40 [info] Elementor/Upgrades - _on_each_version Start  
2023-06-26 15:15:40 [info] Elementor/Upgrades - _on_each_version Finished 
2023-06-26 15:15:40 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.14.0',
  'to' => '3.14.1',
)]
2023-07-31 16:02:55 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.14.1',
  'to' => '3.15.0',
)]
2023-07-31 16:02:56 [info] elementor::elementor_updater Started 
2023-07-31 16:02:56 [info] Elementor/Upgrades - _on_each_version Start  
2023-07-31 16:02:56 [info] Elementor/Upgrades - _on_each_version Finished 
2023-07-31 16:02:56 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.14.1',
  'to' => '3.15.0',
)]
2023-08-02 17:30:09 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.15.0',
  'to' => '3.15.1',
)]
2023-08-02 17:30:10 [info] elementor::elementor_updater Started 
2023-08-02 17:30:10 [info] Elementor/Upgrades - _on_each_version Start  
2023-08-02 17:30:10 [info] Elementor/Upgrades - _on_each_version Finished 
2023-08-02 17:30:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.15.0',
  'to' => '3.15.1',
)]
2023-08-02 17:30:11 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.15.0',
  'to' => '3.15.1',
)]

PHP: showing 3 of 3PHP: 2023-05-10 10:22:31 [warning X 1][/home/www/wp-content/plugins/elementor/includes/managers/controls.php::797] array_merge(): Expected parameter 2 to be an array, bool given [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-31 16:05:49 [error X 10][/home/poau6733/mywebsite.fr/www/htdocs/wp-content/plugins/elementor/includes/managers/controls.php::810] Uncaught TypeError: array_merge(): Argument #2 must be of type array, bool given in /home/poau6733/mywebsite.fr/www/htdocs/wp-content/plugins/elementor/includes/managers/controls.php:810
Stack trace:
#0 /home/poau6733/mywebsite.fr/www/htdocs/wp-content/plugins/elementor/includes/managers/controls.php(810): array_merge()
#1 /home/poau6733/mywebsite.fr/www/htdocs/wp-content/plugins/elementor/includes/base/controls-stack.php(420): Elementor\Controls_Manager->add_control_to_stack()
#2 /home/poau6733/mywebsite.fr/www/htdocs/wp-content/plugins/elementor/includes/elements/repeater.php(117): Elementor\Controls_Stack->add_control()
#3 /home/poau6733/mywebsite.fr/www/htdocs/wp-content/plugins/qi-addons-for-elementor/inc/admin/inc/shortcodes/translators/elementor/class-qiaddonsforelementor-framework-elementor-translator.php(675): Elementor\Repeater->add_control()
#4 /home/poau6733/mywebsite.fr/www/htdocs/wp-content/plugins/qi-addons-for-elementor/inc/plugins/elementor/class-qiaddonsforelementor-elementor-widget-base.php(55): QiAddonsForElementor_Framework_Elementor_Translator->create_controls()
#5 /home/poau6733/mywebsite.fr/www/htdocs/wp-content/plugins/elementor/includes/base/controls-stack.php(2304): QiAddonsForElementor_Elementor_Widget_Base->register_controls()
#6 /home/poau6733/mywebsite.fr/www/htdocs/wp-content/plugins/elementor/includes/base/widget-base.php(1039): Elementor\Controls_Stack->init_controls()
#7 /home/poau6733/mywebsite.fr/www/htdocs/wp-content/plugins/elementor/includes/base/controls-stack.php(495): Elementor\Widget_Base->init_controls()
#8 /home/poau6733/mywebsite.fr/www/htdocs/wp-content/plugins/elementor/includes/base/widget-base.php(177): Elementor\Controls_Stack->get_stack()
#9 /home/poau6733/mywebsite.fr/www/htdocs/wp-content/plugins/elementor/includes/base/controls-stack.php(299): Elementor\Widget_Base->get_stack()
#10 /home/poau6733/mywebsite.fr/www/htdocs/wp-content/plugins/elementor/core/files/css/global-css.php(120): Elementor\Controls_Stack->get_controls()
#11 /home/poau6733/mywebsite.fr/www/htdocs/wp-content/plugins/elementor/core/files/css/global-css.php(66): Elementor\Core\Files\CSS\Global_CSS->render_schemes_and_globals_css()
#12 /home/poau6733/mywebsite.fr/www/htdocs/wp-content/plugins/elementor/core/files/css/base.php(675): Elementor\Core\Files\CSS\Global_CSS->render_css()
#13 /home/poau6733/mywebsite.fr/www/htdocs/wp-content/plugins/elementor/core/files/base.php(180): Elementor\Core\Files\CSS\Base->parse_content()
#14 /home/poau6733/mywebsite.fr/www/htdocs/wp-content/plugins/elementor/core/files/css/base.php(144): Elementor\Core\Files\Base->update_file()
#15 /home/poau6733/mywebsite.fr/www/htdocs/wp-content/plugins/elementor/core/files/css/base.php(231): Elementor\Core\Files\CSS\Base->update()
#16 /home/poau6733/mywebsite.fr/www/htdocs/wp-content/plugins/elementor/includes/frontend.php(1048): Elementor\Core\Files\CSS\Base->enqueue()
#17 /home/poau6733/mywebsite.fr/www/htdocs/wp-content/plugins/elementor/includes/frontend.php(670): Elementor\Frontend->parse_global_css_code()
#18 /home/poau6733/mywebsite.fr/www/htdocs/wp-includes/class-wp-hook.php(308): Elementor\Frontend->enqueue_styles()
#19 /home/poau6733/mywebsite.fr/www/htdocs/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#20 /home/poau6733/mywebsite.fr/www/htdocs/wp-includes/plugin.php(517): WP_Hook->do_action()
#21 /home/poau6733/mywebsite.fr/www/htdocs/wp-includes/script-loader.php(2194): do_action()
#22 /home/poau6733/mywebsite.fr/www/htdocs/wp-includes/class-wp-hook.php(308): wp_enqueue_scripts()
#23 /home/poau6733/mywebsite.fr/www/htdocs/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#24 /home/poau6733/mywebsite.fr/www/htdocs/wp-includes/plugin.php(517): WP_Hook->do_action()
#25 /home/poau6733/mywebsite.fr/www/htdocs/wp-includes/general-template.php(3049): do_action()
#26 /home/poau6733/mywebsite.fr/www/htdocs/wp-content/themes/bridge/header.php(28): wp_head()
#27 /home/poau6733/mywebsite.fr/www/htdocs/wp-includes/template.php(783): require_once('/home/poau6733/...')
#28 /home/poau6733/mywebsite.fr/www/htdocs/wp-includes/template.php(718): load_template()
#29 /home/poau6733/mywebsite.fr/www/htdocs/wp-includes/general-template.php(48): locate_template()
#30 /home/poau6733/mywebsite.fr/www/htdocs/wp-content/themes/bridge/page.php(30): get_header()
#31 /home/poau6733/mywebsite.fr/www/htdocs/wp-includes/template-loader.php(106): include('/home/poau6733/...')
#32 /home/poau6733/mywebsite.fr/www/htdocs/wp-blog-header.php(19): require_once('/home/poau6733/...')
#33 /home/poau6733/mywebsite.fr/www/htdocs/index.php(17): require('/home/poau6733/...')
#34 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-31 16:17:50 [error X 121][/home/poau6733/mywebsite.fr/www/htdocs/wp-content/plugins/elementor/includes/managers/controls.php::810] Uncaught TypeError: array_merge(): Argument #2 must be of type array, bool given in /home/poau6733/mywebsite.fr/www/htdocs/wp-content/plugins/elementor/includes/managers/controls.php:810
Stack trace:
#0 /home/poau6733/mywebsite.fr/www/htdocs/wp-content/plugins/elementor/includes/managers/controls.php(810): array_merge()
#1 /home/poau6733/mywebsite.fr/www/htdocs/wp-content/plugins/elementor/includes/base/controls-stack.php(420): Elementor\Controls_Manager->add_control_to_stack()
#2 /home/poau6733/mywebsite.fr/www/htdocs/wp-content/plugins/elementor/includes/elements/repeater.php(117): Elementor\Controls_Stack->add_control()
#3 /home/poau6733/mywebsite.fr/www/htdocs/wp-content/plugins/qi-addons-for-elementor/inc/admin/inc/shortcodes/translators/elementor/class-qiaddonsforelementor-framework-elementor-translator.php(675): Elementor\Repeater->add_control()
#4 /home/poau6733/mywebsite.fr/www/htdocs/wp-content/plugins/qi-addons-for-elementor/inc/plugins/elementor/class-qiaddonsforelementor-elementor-widget-base.php(55): QiAddonsForElementor_Framework_Elementor_Translator->create_controls()
#5 /home/poau6733/mywebsite.fr/www/htdocs/wp-content/plugins/elementor/includes/base/controls-stack.php(2304): QiAddonsForElementor_Elementor_Widget_Base->register_controls()
#6 /home/poau6733/mywebsite.fr/www/htdocs/wp-content/plugins/elementor/includes/base/widget-base.php(1039): Elementor\Controls_Stack->init_controls()
#7 /home/poau6733/mywebsite.fr/www/htdocs/wp-content/plugins/elementor/includes/base/controls-stack.php(495): Elementor\Widget_Base->init_controls()
#8 /home/poau6733/mywebsite.fr/www/htdocs/wp-content/plugins/elementor/includes/base/widget-base.php(177): Elementor\Controls_Stack->get_stack()
#9 /home/poau6733/mywebsite.fr/www/htdocs/wp-content/plugins/elementor/includes/base/controls-stack.php(299): Elementor\Widget_Base->get_stack()
#10 /home/poau6733/mywebsite.fr/www/htdocs/wp-content/plugins/elementor/core/files/css/global-css.php(120): Elementor\Controls_Stack->get_controls()
#11 /home/poau6733/mywebsite.fr/www/htdocs/wp-content/plugins/elementor/core/files/css/global-css.php(66): Elementor\Core\Files\CSS\Global_CSS->render_schemes_and_globals_css()
#12 /home/poau6733/mywebsite.fr/www/htdocs/wp-content/plugins/elementor/core/files/css/base.php(675): Elementor\Core\Files\CSS\Global_CSS->render_css()
#13 /home/poau6733/mywebsite.fr/www/htdocs/wp-content/plugins/elementor/core/files/base.php(180): Elementor\Core\Files\CSS\Base->parse_content()
#14 /home/poau6733/mywebsite.fr/www/htdocs/wp-content/plugins/elementor/core/files/css/base.php(144): Elementor\Core\Files\Base->update_file()
#15 /home/poau6733/mywebsite.fr/www/htdocs/wp-content/plugins/elementor/core/files/css/base.php(231): Elementor\Core\Files\CSS\Base->update()
#16 /home/poau6733/mywebsite.fr/www/htdocs/wp-content/plugins/elementor/includes/frontend.php(1048): Elementor\Core\Files\CSS\Base->enqueue()
#17 /home/poau6733/mywebsite.fr/www/htdocs/wp-content/plugins/elementor/includes/frontend.php(670): Elementor\Frontend->parse_global_css_code()
#18 /home/poau6733/mywebsite.fr/www/htdocs/wp-includes/class-wp-hook.php(308): Elementor\Frontend->enqueue_styles()
#19 /home/poau6733/mywebsite.fr/www/htdocs/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#20 /home/poau6733/mywebsite.fr/www/htdocs/wp-includes/plugin.php(517): WP_Hook->do_action()
#21 /home/poau6733/mywebsite.fr/www/htdocs/wp-includes/script-loader.php(2194): do_action()
#22 /home/poau6733/mywebsite.fr/www/htdocs/wp-includes/class-wp-hook.php(308): wp_enqueue_scripts()
#23 /home/poau6733/mywebsite.fr/www/htdocs/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#24 /home/poau6733/mywebsite.fr/www/htdocs/wp-includes/plugin.php(517): WP_Hook->do_action()
#25 /home/poau6733/mywebsite.fr/www/htdocs/wp-includes/general-template.php(3049): do_action()
#26 /home/poau6733/mywebsite.fr/www/htdocs/wp-content/themes/bridge/header.php(28): wp_head()
#27 /home/poau6733/mywebsite.fr/www/htdocs/wp-includes/template.php(783): require_once('/home/poau6733/...')
#28 /home/poau6733/mywebsite.fr/www/htdocs/wp-includes/template.php(718): load_template()
#29 /home/poau6733/mywebsite.fr/www/htdocs/wp-includes/general-template.php(48): locate_template()
#30 /home/poau6733/mywebsite.fr/www/htdocs/wp-content/themes/bridge/full_width.php(35): get_header()
#31 /home/poau6733/mywebsite.fr/www/htdocs/wp-includes/template-loader.php(106): include('/home/poau6733/...')
#32 /home/poau6733/mywebsite.fr/www/htdocs/wp-blog-header.php(19): require_once('/home/poau6733/...')
#33 /home/poau6733/mywebsite.fr/www/htdocs/index.php(17): require('/home/poau6733/...')
#34 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 1 of 1JS: 2023-08-02 12:27:20 [error X 5][https://mywebsite.fr/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.15.0:3:802938] Cannot read properties of undefined (reading 'localized') 

== Elementor - Compatibility Tag ==
	
	Qi Addons For Elementor: Non compatible

**Comment by nicholaszein** [comment]
Hello @nelero,

Thank you for reaching out! 🙏 

### ⛔ 🧩 Please note that while we do welcome bug reports, we can't provide support for 3rd-party add-ons.

If your issue is specifically happening only when you're using a feature from a 3rd-party software, or only when the 3rd-party software is active, you'll need to contact the support for that specific software or its developers.

In your case, at least one add-on is incompatible with the current version of Elementor installed. You need to reach out to the add-on developer and request them to fix the incompatibility.

However, I will check with the team if we will consider your PR. Either way, you should reach out to the add-on developer. Elementor announced the deprecation of the code being used a long time ago.

Allow us some time to investigate your issue.

Regards

**Comment by nelero** [comment]
Hi,
thanks for your comment! i already told them this bug too.
By the way, i hope the team will be ok to secure the access of this variable in case some plugins are messing up data, in order to provide the robustest code.
Regards,

**Comment by nelero** [comment]
Hi,
some of $control_data['default'] are not filled. I can debug values if you want but, as you check $control_default_value to be array, we need to check if $control_data['default'] to be set AND an array too.

**Comment by nelero** [comment]
@nicholaszein Hi,
i agree, a third party plugin messed up with the config of one element. But as the value is messy, it creates a bug because Elementor doesn't check if $control_data['default'] is an array before merging.
My code just add the type verification before merging to secure this.
Could you put someone to review my code ?
It's annoying cause every time there is an update, it crashes.
Thanks

**Comment by zaehlpixel** [comment]
Same issue here - Can please somone check @nelero s code??

**Comment by igorchernenko92** [comment]
Same issue on 8.2

**Comment by nelero** [comment]
Hi, 
a review is still planned in 2024 ? Nearly the anniversary for this PR.
Who will make the birthday cake for 2 lines of code changed ?
