### ISSUE TITLE
Gallery Widgets in Loop Item trigger the same lightbox-slideshow if gallery is pulled from dynamic content

### ISSUE THREAD

**Issue by rloes** [elementor/elementor#23448]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Possibly related to #11809

I put a gallery in a loop item, so that each item in the grid triggers an individual gallery. However the same gallery is triggered. I tried this with Gallery, Basic Gallery  and Image Carousel.

When inspecting with dev tools all data-elementor-lightbox-slideshow are the same in the loop grid

![ezgif-3-a94de4880c](https://github.com/elementor/elementor/assets/92471929/7e7f4e1b-82dc-4ef9-ac79-17a519dc8439)

### Steps to reproduce

1)  Create Posts with Gallery Field
2) Create Loop Grid
3) Create Loop Item with Gallery widget and pull content dynamically
4) Publish and open different galleries

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info (click)</summary>

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: mariadb.org binary distribution v10.11.4-MariaDB-1:10.11.4+maria~deb11-log
	PHP Version: 8.0.25
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 150M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.3
	WP Multisite: No
	Max Upload Size: 150 MB
	Memory limit: 512M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: de-DE
	Timezone: Europe/Berlin
	Admin Email: intern@undefined.de
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.8.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/116.0

== Active Plugins ==
	ACF Photo Gallery Field
		Version: 2.0
		Author: Navneil Naicker

	Advanced Custom Fields
		Version: 6.2.0
		Author: WP Engine

	Code Snippets
		Version: 3.4.2
		Author: Code Snippets Pro

	Duplicate Page
		Version: 4.5.2
		Author: mndpsingh287

	Elementor
		Version: 3.15.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.15.1
		Author: Elementor.com

== Elemente Verwendung ==
	
	footer : 1
		button : 2
		container : 7
		divider : 2
		heading : 4
		icon : 1
		nav-menu : 2
		text-editor : 1
	header : 1
		container : 2
		nav-menu : 1
		theme-site-logo : 1
	wp-post : 0
		button : 5
		container : 14
		counter : 4
		divider : 1
		heading : 11
		icon : 1
		icon-list : 4
		image : 7
		nested-carousel : 1
		spacer : 3
		text-editor : 1
	wp-page : 7
		button : 8
		container : 41
		divider : 2
		heading : 24
		icon : 1
		icon-list : 5
		image : 12
		loop-grid : 1
		nested-accordion : 1
		nested-tabs : 1
		spacer : 1
		text-editor : 14
	loop-item : 1
		container : 2
		gallery : 1
		heading : 1
		theme-post-title : 1

== Einstellungen ==
	
	cpt_support: post, page
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap

== Eigenschaften ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	

== Elementor-Experimente ==
	Optimierte DOM Ausgabe: Aktiv
	Verbessertes Laden von Assets: Aktiv
	Verbessertes Laden von CSS: Aktiv
	Inline-Schriftarten-Symbole: Aktiv
	Zusätzliche benutzerdefinierte Breakpoints: Inaktiv
	admin_menu_rearrangement: Standardmäßig deaktiviert
	Flexbox Container: Aktiv
	Upgrade Swiper Library: Aktiv
	Grid Container: Aktiv
	Default to New Theme Builder: Standardmäßig aktiviert
	Hello Theme Header &amp; Footer: Aktiv
	Editor Top Bar: Aktiv
	Startseiten: Aktiv
	Nested Elements: Aktiv
	Hintergrundbilder nachladen: Aktiv
	Global Style Guide: Aktiv
	Page Transitions: Standardmäßig aktiviert
	Notes: Standardmäßig aktiviert
	Loop: Standardmäßig aktiviert
	Form Submissions: Standardmäßig aktiviert
	Scroll Snap: Standardmäßig aktiviert
	Menü: Standardmäßig deaktiviert
	Taxonomy Filter: Standardmäßig deaktiviert

== Protokoll ==
	
PHP: showing 7 of 7PHP: 2023-08-11 14:25:29 [warning X 2][/home/www/undefined/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined array key &quot;data&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-11 14:34:30 [warning X 3][/home/www/undefined/wp-content/plugins/elementor/includes/managers/image.php::113] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-11 14:48:28 [error X 2][/home/www/undefined/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::304] Uncaught Error: Call to a member function update_meta() on null in /home/www/undefined/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:304
Stack trace:
#0 /home/www/undefined/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(177): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;save_conditions(5, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/www/undefined/wp-content/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/www/undefined/wp-includes/class-wp-hook.php(310): Elementor\Core\Common\Modules\Ajax\Module-&gt;handle_ajax_request(&#039;&#039;)
#4 /home/www/undefined/wp-includes/class-wp-hook.php(334): WP_Hook-&gt;apply_filters(&#039;&#039;, Array)
#5 /home/www/undefined/wp-includes/plugin.php(517): WP_Hook-&gt;do_action(Array)
#6 /home/www/undefined/wp-admin/admin-ajax.php(188): do_action(&#039;wp_ajax_element...&#039;)
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-11 22:08:02 [warning X 1][/home/www/undefined/wp-content/plugins/elementor/core/logger/items/js.php::17] Undefined array key &quot;url&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-12 20:40:56 [warning X 6][/home/www/undefined/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/fonts-manager.php::252] Undefined array key &quot;editor_post_id&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-13 22:57:41 [warning X 1][/home/www/undefined/wp-content/plugins/elementor/modules/history/revisions-manager.php::363] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-16 15:22:04 [error X 1][/home/www/undefined/wp-content/plugins/elementor/core/wp-api.php::26] Uncaught Error: Call to undefined function Elementor\Core\get_plugins() in /home/www/undefined/wp-content/plugins/elementor/core/wp-api.php:26
Stack trace:
#0 /home/www/undefined/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(96): Elementor\Core\Wp_Api-&gt;get_plugins()
#1 /home/www/undefined/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(58): Elementor\Modules\CompatibilityTag\Base_Module-&gt;get_plugins_with_header()
#2 /home/www/undefined/wp-content/plugins/elementor/modules/compatibility-tag/module.php(57): Elementor\Modules\CompatibilityTag\Base_Module-&gt;get_plugins_to_check()
#3 /home/www/undefined/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(148): Elementor\Modules\CompatibilityTag\Module-&gt;get_plugins_to_check()
#4 /home/www/undefined/wp-includes/class-wp-hook.php(310): Elementor\Modules\CompatibilityTag\Base_Module-&gt;Elementor\Modules\CompatibilityTag\{closure}(&#039;&#039;)
#5 /home/www/undefined/wp-includes/class-wp-hook.php(334): WP_Hook-&gt;apply_filters(&#039;&#039;, Array)
#6 /home/www/undefined/wp-includes/plugin.php(517): WP_Hook-&gt;do_action(Array)
#7 /home/www/undefined/wp-content/plugins/elementor/modules/system-info/module.php(334): do_action(&#039;elementor/syste...&#039;)
#8 /home/www/undefined/wp-content/plugins/elementor/includes/tracker.php(241): Elementor\Modules\System_Info\Module::get_allowed_reports()
#9 /home/www/undefined/wp-content/plugins/elementor/includes/tracker.php(530): Elementor\Tracker::get_system_reports_data()
#10 /home/www/undefined/wp-content/plugins/elementor/includes/tracker.php(141): Elementor\Tracker::get_tracking_data(true)
#11 /home/www/undefined/wp-includes/class-wp-hook.php(310): Elementor\Tracker::send_tracking_data()
#12 /home/www/undefined/wp-includes/class-wp-hook.php(334): WP_Hook-&gt;apply_filters(&#039;&#039;, Array)
#13 /home/www/undefined/wp-includes/plugin.php(565): WP_Hook-&gt;do_action(Array)
#14 /home/www/undefined/wp-cron.php(191): do_action_ref_array(&#039;elementor/track...&#039;, Array)
#15 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 11 of 11JS: 2023-08-11 12:25:32 [error X 3][http://undefined.undefined.de/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.15.2:2:31060] elementor.settings.page is undefined 
JS: 2023-08-11 12:35:13 [error X 1][http://undefined.undefined.de/wp-content/plugins/elementor/assets/js/admin.min.js?ver=3.15.2:3:48021] l[0] is undefined 
JS: 2023-08-11 19:15:18 [error X 4][http://undefined.undefined.de/wp-content/plugins/elementor/assets/js/7fada1a61d72da6d46ab.bundle.min.js:2:7805] t.target.closest(...) is null 
JS: 2023-08-11 20:07:55 [error X 24][http://undefined.undefined.de/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:19552] Cannot read properties of null (reading &#039;changestop&#039;) 
JS: 2023-08-11 20:07:55 [error X 866][http://undefined.undefined.de/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:14799] Cannot read properties of null (reading &#039;clone&#039;) 
JS: 2023-08-12 13:03:42 [error X 4][http://undefined.undefined.de/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.15.2:3:690230] this.model.isValidChild is not a function 
JS: 2023-08-13 12:25:26 [error X 1][http://undefined.undefined.de/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:19533] this._eventListener is null 
JS: 2023-08-14 20:38:22 [error X 3][http://undefined.undefined.de/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.15.2:3:802896] this.store.find(...) is undefined 
JS: 2023-08-16 15:26:44 [error X 2][http://undefined.undefined.de/wp-admin/load-scripts.php?c=0&amp;loadchunk_0=jquery-core,jquery-migrate,utils,moxiejs,plupload&amp;ver=6.3:2:28722] Cannot read properties of undefined (reading &#039;value&#039;) 
JS: 2023-08-16 17:20:18 [error X 1][http://undefined.undefined.de/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.15.2:3:695563] C.getControlModel(...) is undefined 
JS: 2023-08-16 19:09:24 [error X 1][http://undefined.undefined.de/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.15.2:3:802395] T.originalEvent.key is undefined 

Log: showing 7 of 72023-08-15 19:18:00 [info] Elementor custom task(s) process has been queued. [array (
  0 => 
  array (
    0 => 
    array (
      0 => 'Elementor\Core\Upgrade\Custom_Tasks',
      1 => 'opt_in_recalculate_usage',
    ),
    1 => 
    array (
      0 => 'Elementor\Core\Upgrade\Custom_Tasks',
      1 => 'opt_in_send_tracking_data',
    ),
  ),
)]
2023-08-15 19:18:01 [info] elementor::custom_task_manger Started 
2023-08-15 19:18:01 [info] Elementor/Tasks - opt_in_recalculate_usage Start  
2023-08-15 19:18:01 [info] Elementor/Tasks - opt_in_recalculate_usage Finished 
2023-08-15 19:18:01 [info] Elementor/Tasks - opt_in_send_tracking_data Start  
2023-08-15 19:18:01 [info] Elementor/Tasks - opt_in_send_tracking_data Finished 
2023-08-15 19:18:01 [info] elementor::custom_task_manger Completed 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Kompatibel

== Elementor Pro - Compatibility Tag ==
	

</details>

**Comment by nicholaszein** [comment]
Hello @rloes, 

Thank you for submitting your report! 🙏 

### ❌ While reviewing your report, we noticed it was missing some key pieces of information:

Can you please elaborate more about your case?

Please answer the following questions:

1. Describe how you created your Gallery Field and what plugins you used. Preferably give a step-by-step so we can reproduce it on our end exactly how you did.
2. Describe what widgets you used on your Loop Item template, and what settings you've selected.
3. Clarify if you added any link wrapping your gallery widget.
4. Clarify what is the expected outcome, as from the gif you shared it wasn't clear if you wish for the lightbox to show all images from all loop items, or if you wish for each loop item to show different images.

### 🧐 Please provide the missing information above so we can troubleshoot your issue faster and better.

Best regards

**Comment by rloes** [comment]
Hi @nicholaszein,

thanks for looking into the issue. I have updated the step by step description to hopefully clarify my issue. I couldnt test it yet but I can imagine this issue could also happen displaying woocommerce product galleries in loops.

In the gif  after I leave the editor, you can see three loop items on the site. Each of them contains only one image but opening any of them opens a lightbox gallery that contains all images of the page. I guess the problem is that they have the same slightshow id attribute.

I can provide more information if needed.

**Comment by chasperlisimba** [comment]
I have the exact same problem. Is there a fix coming soon? :-/

**Comment by rloes** [comment]
@chasperlisimba I hope they will check this issue soon, as it's still on "waiting for  feedback".

However, I guess you could make a temporary fix by changing the ids of each gallery widget using JavaScript.

**Comment by chasperlisimba** [comment]
@rloes do you have any script already for this?

**Comment by rloes** [comment]
@chasperlisimba I think my script wont fit your situation perfectly, because my gallery is invisible and i have an image-ling that will trigger the gallery. I hope you can atleast use it as an starting point:

``` html
<script>
	function addGalleryDataToLoopItemLinks(){
		const links = document.querySelectorAll('.elementor-469 > a.e-con'); 
		const loopItems = document.querySelectorAll('.elementor-469');
		//loop over each gallery
		for(let i=0; i<loopItems.length; i++){
			// get id
			let id = loopItems[i].querySelector('.e-gallery-item')?.dataset?.elementorLightboxSlideshow
			if(i > 0){
				// get id and make it unique
				id += String(i);
				const galleryItems = loopItems[i].querySelectorAll('.e-gallery-item');
				// and loop over each image and set id
				for(let j=0; j < galleryItems.length; j++){
					galleryItems[j].dataset.elementorLightboxSlideshow = id;
				}
			}
			// set id to link that will trigger lightbox gallery
			links[i].dataset.elementorLightboxSlideshow= id
		}
	}
	window.addEventListener('load', addGalleryDataToLoopItemLinks)
</script>
```

**Comment by chasperlisimba** [comment]
@rloes Thank you. It's not workig for me. I have a custom posttype with a custom gallery field (all created with ACF)... In the loop item I have added the elementor gallery widget and then it happens with the wrong IDs or what ever... @nicholaszein do you have any plans to fix this asap?

**Comment by okeydoak** [comment]
Same problem. Please fix this.

**Comment by rloes** [comment]
This is still a problem. The following snippet works for me. You just have to change the selector of the loop-item to fit yours:

```javascript
function addGalleryDataToLoopItemLinks(){
        const loopItems = document.querySelectorAll('.elementor-159');
        //loop over each gallery
        for(let i=0; i<loopItems.length; i++){
            // get id
            let id = loopItems[i].querySelector('a[data-elementor-lightbox-slideshow]')?.dataset?.elementorLightboxSlideshow
            if(i > 0){
                // each but first make id unique
                id += String(i);
                const galleryItems = loopItems[i].querySelectorAll('a[data-elementor-lightbox-slideshow]');
                // and loop over each image and set id
                for(let j=0; j < galleryItems.length; j++){
                    galleryItems[j].dataset.elementorLightboxSlideshow = id;
                }
            }
        }
    }
    window.addEventListener('load', addGalleryDataToLoopItemLinks);
```
