### ISSUE TITLE
SVG Icon Not Working Properly 

### ISSUE THREAD

**Issue by aminul-xs** [elementor/elementor#23451]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

how to support custom icon SVG??
https://prnt.sc/b52WPDoXgMEq

### Steps to reproduce

**IcoMoon** not working IcoMoon SVG or custom
https://prnt.sc/VaBhOPcXBwSN

**font awesome** Working is well
https://prnt.sc/01uCuJbKF8Zg

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.51 (Win64) PHP/7.4.26
	MySQL version: MySQL Community Server (GPL) v5.7.36
	PHP Version: 7.4.26
	PHP Memory Limit: 128M
	PHP Max Input Vars: 2500
	PHP Max Post Size: 32M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2.2
	Site URL: http://localhost/wp-plugin/elementskit/dev
	Home URL: http://localhost/wp-plugin/elementskit/dev
	WP Multisite: No
	Max Upload Size: 32 MB
	Memory limit: 556M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Asia/Dhaka
	Admin Email: ai.xpeedstudio@gmail.com
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor
	Version: 2.8.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.15.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.14.1
		Author: Elementor.com

	ElementsKit Lite
		Version: 2.9.0
		Author: Wpmet

	ElementsKit Pro
		Version: 3.3.0
		Author: Wpmet

== Elements Usage ==
	
	page : 1
		elementskit-button : 1
		elementskit-contact-form7 : 1
		elementskit-gallery : 1
		elementskit-heading : 7
		elementskit-icon-box : 11
		elementskit-pricing : 3
		elementskit-tab : 1
		elementskit-testimonial : 1
		heading : 1
		image : 3
		spacer : 1
	section : 1
		elementskit-heading : 1
		elementskit-image-accordion : 1
		heading : 1
	wp-post : 0
		accordion : 3
		blockquote : 2
		container : 6
		elementskit-accordion : 2
		elementskit-advance-accordion : 1
		elementskit-client-logo : 1
		elementskit-team-slider : 1
		heading : 60
		html : 14
		image : 31
		shortcode : 6
		text-editor : 88
		video : 3
	wp-page : 35
		accordion : 2
		container : 5
		ekit-nav-menu : 1
		ekit-vertical-menu : 1
		elementskit-accordion : 1
		elementskit-advanced-search : 1
		elementskit-advanced-slider : 2
		elementskit-advanced-toggle : 1
		elementskit-audio-player : 1
		elementskit-back-to-top : 3
		elementskit-blog-posts : 1
		elementskit-button : 1
		elementskit-client-logo : 3
		elementskit-contact-form7 : 1
		elementskit-creative-button : 1
		elementskit-dribble-feed : 1
		elementskit-facebook-feed : 1
		elementskit-facebook-review : 2
		elementskit-fancy-animated-text : 1
		elementskit-gallery : 1
		elementskit-header-offcanvas : 2
		elementskit-heading : 10
		elementskit-icon-box : 14
		elementskit-image-accordion : 1
		elementskit-mail-chimp : 1
		elementskit-page-list : 1
		elementskit-piechart : 1
		elementskit-price-menu : 3
		elementskit-pricing : 6
		elementskit-simple-tab : 1
		elementskit-social-media : 1
		elementskit-tab : 1
		elementskit-team-slider : 2
		elementskit-testimonial : 3
		elementskit-twitter-feed : 1
		elementskit-video-gallery : 3
		elementskit-whatsapp : 1
		elementskit-yelp : 3
		heading : 5
		icon : 2
		image : 4
		slides : 1
		tabs : 1
		text-editor : 9

== Settings ==
	
	cpt_support: post, page, e-landing-page, elementskit_content, elementskit_template, elementskit_widget
	disable_color_schemes: yes
	disable_typography_schemes: yes
	allow_tracking: yes
	editor_break_lines: 1
	unfiltered_files_upload: 1
	font_display: swap
	meta_generator_tag: 1

== Features ==
	Custom Fonts: 1
	Custom Icons: 0

== Integrations ==
	
	recaptcha: Active
	recaptcha_v3: Active

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Active
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive
	Upgrade Swiper Library: Active
	Grid Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header &amp; Footer: Inactive by default
	Editor Top Bar: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Inactive
	Lazy Load Background Images: Inactive by default
	Global Style Guide: Inactive by default
	Page Transitions: Active
	Notes: Active by default
	Loop: Active by default
	Form Submissions: Active
	Scroll Snap: Active
	Menu: Inactive

== Log ==
	
Log: showing 13 of 132023-07-24 15:07:47 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-07-24 15:07:48 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-07-24 15:07:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.13.2',
  'to' => '3.14.1',
)]
2023-08-09 10:24:42 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.14.1',
  'to' => '3.15.1',
)]
2023-08-09 10:24:49 [info] elementor::elementor_updater Started 
2023-08-09 10:24:49 [info] Elementor/Upgrades - _on_each_version Start  
2023-08-09 10:24:57 [info] Elementor/Upgrades - _on_each_version Finished 
2023-08-09 10:24:57 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.14.1',
  'to' => '3.15.1',
)]
2023-08-13 09:27:30 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.15.1',
  'to' => '3.15.2',
)]
2023-08-13 09:27:48 [info] elementor::elementor_updater Started 
2023-08-13 09:27:48 [info] Elementor/Upgrades - _on_each_version Start  
2023-08-13 09:28:02 [info] Elementor/Upgrades - _on_each_version Finished 
2023-08-13 09:28:02 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.15.1',
  'to' => '3.15.2',
)]

PHP: showing 17 of 17PHP: 2023-07-24 15:19:51 [notice X 21][D:\WAMP\www\wp-plugin\elementskit\dev\wp-content\plugins\elementor\core\page-assets\data-managers\font-icon-svg\font-awesome.php::50] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-24 15:27:27 [notice X 409][D:\WAMP\www\wp-plugin\elementskit\dev\wp-content\plugins\elementor\core\page-assets\data-managers\font-icon-svg\font-awesome.php::19] Undefined offset: 0 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-26 09:10:02 [error X 1][D:\WAMP\www\wp-plugin\elementskit\dev\wp-content\plugins\elementor\core\page-assets\data-managers\font-icon-svg\manager.php::33] syntax error, unexpected &#039;return&#039; (T_RETURN) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-30 10:23:28 [error X 2][D:\WAMP\www\wp-plugin\elementskit\dev\wp-content\plugins\elementor\includes\base\controls-stack.php::1211] Uncaught Error: Using $this when not in object context in D:\WAMP\www\wp-plugin\elementskit\dev\wp-content\plugins\elementor\includes\base\controls-stack.php:1211
Stack trace:
#0 D:\WAMP\www\wp-plugin\elementskit\dev\wp-content\plugins\elementskit\widgets\advanced-search\advanced-search-result.php(27): Elementor\Controls_Stack::get_settings_for_display()
#1 D:\WAMP\www\wp-plugin\elementskit\dev\wp-content\plugins\elementskit\widgets\advanced-search\advanced-search-handler.php(45): include(&#039;D:\\WAMP\\www\\wp-...&#039;)
#2 D:\WAMP\www\wp-plugin\elementskit\dev\wp-includes\rest-api\class-wp-rest-server.php(1181): Elementor\ElementsKit_Widget_Advanced_Search_Handler-&gt;get_the_search_result(Object(WP_REST_Request))
#3 D:\WAMP\www\wp-plugin\elementskit\dev\wp-includes\rest-api\class-wp-rest-server.php(1028): WP_REST_Server-&gt;respond_to_request(Object(WP_REST_Request), &#039;/elementskit/v1...&#039;, Array, NULL)
#4 D:\WAMP\www\wp-plugin\elementskit\dev\wp-includes\rest-api\class-wp-rest-server.php(442): WP_REST_Server-&gt;dispatch(Obj [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-31 11:44:31 [warning X 2][D:\WAMP\www\wp-plugin\elementskit\dev\wp-content\plugins\elementor\core\common\modules\ajax\module.php::273] Cannot modify header information - headers already sent by (output started at D:\WAMP\www\wp-plugin\elementskit\dev\wp-content\plugins\elementskit\widgets\advanced-search\advanced-search.php:245) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-07 11:49:05 [notice X 4][D:\WAMP\www\wp-plugin\elementskit\dev\wp-content\plugins\elementor\includes\controls\base-multiple.php::87] Undefined index: size [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-09 10:52:48 [notice X 134][D:\WAMP\www\wp-plugin\elementskit\dev\wp-content\plugins\elementor\core\files\css\base.php::776] Undefined index: padding_mobile [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-09 11:01:42 [error X 2][D:\WAMP\www\wp-plugin\elementskit\dev\wp-content\plugins\elementor\core\wp-api.php::26] Uncaught Error: Call to undefined function Elementor\Core\get_plugins() in D:\WAMP\www\wp-plugin\elementskit\dev\wp-content\plugins\elementor\core\wp-api.php:26
Stack trace:
#0 D:\WAMP\www\wp-plugin\elementskit\dev\wp-content\plugins\elementor\modules\compatibility-tag\base-module.php(96): Elementor\Core\Wp_Api-&gt;get_plugins()
#1 D:\WAMP\www\wp-plugin\elementskit\dev\wp-content\plugins\elementor\modules\compatibility-tag\base-module.php(58): Elementor\Modules\CompatibilityTag\Base_Module-&gt;get_plugins_with_header()
#2 D:\WAMP\www\wp-plugin\elementskit\dev\wp-content\plugins\elementor\modules\compatibility-tag\module.php(57): Elementor\Modules\CompatibilityTag\Base_Module-&gt;get_plugins_to_check()
#3 D:\WAMP\www\wp-plugin\elementskit\dev\wp-content\plugins\elementor\modules\compatibility-tag\base-module.php(148): Elementor\Modules\CompatibilityTag\Module-&gt;get_plugins_to_check()
#4 D:\WAMP\www\wp-plugin\elementskit\dev\wp-includes\class-wp-hook.php(308): Elementor\Modules\CompatibilityTag\Base_Module-&gt;Elementor\Mod [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-09 11:12:04 [notice X 9][D:\WAMP\www\wp-plugin\elementskit\dev\wp-content\plugins\elementor\core\files\css\base.php::776] Undefined index: margin_mobile [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-14 09:41:19 [notice X 1][D:\WAMP\www\wp-plugin\elementskit\dev\wp-content\plugins\elementor\core\files\css\base.php::776] Undefined index: force_stop_mobile [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-15 10:41:14 [warning X 4][D:\WAMP\www\wp-plugin\elementskit\dev\wp-content\plugins\elementor\core\base\base-object.php::111] Illegal offset type in isset or empty [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-16 09:26:33 [notice X 4][D:\WAMP\www\wp-plugin\elementskit\dev\wp-content\plugins\elementor\core\page-assets\data-managers\font-icon-svg\font-awesome.php::19] Undefined offset: 0 [array (
  'trace' => '
#0: D:\WAMP\www\wp-plugin\elementskit\dev\wp-content\plugins\elementor\core\page-assets\data-managers\font-icon-svg\font-awesome.php(19): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: D:\WAMP\www\wp-plugin\elementskit\dev\wp-content\plugins\elementor\core\page-assets\data-managers\base.php(332): Elementor\Core\Page_Assets\Data_Managers\Font_Icon_Svg\Font_Awesome -> get_config()
#2: D:\WAMP\www\wp-plugin\elementskit\dev\wp-content\plugins\elementor\core\page-assets\data-managers\font-icon-svg\manager.php(42): Elementor\Core\Page_Assets\Data_Managers\Base -> get_asset_data()
#3: D:\WAMP\www\wp-plugin\elementskit\dev\wp-content\plugins\elementor\includes\managers\icons.php(271): Elementor\Core\Page_Assets\Data_Managers\Font_Icon_Svg\Manager :: get_font_icon_svg_data()
#4: D:\WAMP\www\wp-plugin\elementskit\dev\wp-content\plugins\elementor\includes\managers\icons.php(282): Elementor\Icons_Manager :: get_icon_svg_data()
',
)]
PHP: 2023-08-16 09:26:33 [notice X 2][D:\WAMP\www\wp-plugin\elementskit\dev\wp-content\plugins\elementor\core\page-assets\data-managers\font-icon-svg\font-awesome.php::45] Undefined index: fasicon icon-money-bag [array (
  'trace' => '
#0: D:\WAMP\www\wp-plugin\elementskit\dev\wp-content\plugins\elementor\core\page-assets\data-managers\font-icon-svg\font-awesome.php(45): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: D:\WAMP\www\wp-plugin\elementskit\dev\wp-content\plugins\elementor\core\page-assets\data-managers\base.php(139): Elementor\Core\Page_Assets\Data_Managers\Font_Icon_Svg\Font_Awesome -> get_asset_content()
#2: D:\WAMP\www\wp-plugin\elementskit\dev\wp-content\plugins\elementor\core\page-assets\data-managers\base.php(290): Elementor\Core\Page_Assets\Data_Managers\Base -> set_asset_data()
#3: D:\WAMP\www\wp-plugin\elementskit\dev\wp-content\plugins\elementor\core\page-assets\data-managers\base.php(312): Elementor\Core\Page_Assets\Data_Managers\Base -> init_asset_data()
#4: D:\WAMP\www\wp-plugin\elementskit\dev\wp-content\plugins\elementor\core\page-assets\data-managers\base.php(334): Elementor\Core\Page_Assets\Data_Managers\Base -> get_asset_data_from_config()
',
)]
PHP: 2023-08-16 09:26:33 [notice X 4][D:\WAMP\www\wp-plugin\elementskit\dev\wp-content\plugins\elementor\core\page-assets\data-managers\font-icon-svg\font-awesome.php::48] Trying to access array offset on value of type null [array (
  'trace' => '
#0: D:\WAMP\www\wp-plugin\elementskit\dev\wp-content\plugins\elementor\core\page-assets\data-managers\font-icon-svg\font-awesome.php(48): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: D:\WAMP\www\wp-plugin\elementskit\dev\wp-content\plugins\elementor\core\page-assets\data-managers\base.php(139): Elementor\Core\Page_Assets\Data_Managers\Font_Icon_Svg\Font_Awesome -> get_asset_content()
#2: D:\WAMP\www\wp-plugin\elementskit\dev\wp-content\plugins\elementor\core\page-assets\data-managers\base.php(290): Elementor\Core\Page_Assets\Data_Managers\Base -> set_asset_data()
#3: D:\WAMP\www\wp-plugin\elementskit\dev\wp-content\plugins\elementor\core\page-assets\data-managers\base.php(312): Elementor\Core\Page_Assets\Data_Managers\Base -> init_asset_data()
#4: D:\WAMP\www\wp-plugin\elementskit\dev\wp-content\plugins\elementor\core\page-assets\data-managers\base.php(334): Elementor\Core\Page_Assets\Data_Managers\Base -> get_asset_data_from_config()
',
)]
PHP: 2023-08-16 09:26:33 [notice X 4][D:\WAMP\www\wp-plugin\elementskit\dev\wp-content\plugins\elementor\core\page-assets\data-managers\font-icon-svg\font-awesome.php::49] Trying to access array offset on value of type null [array (
  'trace' => '
#0: D:\WAMP\www\wp-plugin\elementskit\dev\wp-content\plugins\elementor\core\page-assets\data-managers\font-icon-svg\font-awesome.php(49): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: D:\WAMP\www\wp-plugin\elementskit\dev\wp-content\plugins\elementor\core\page-assets\data-managers\base.php(139): Elementor\Core\Page_Assets\Data_Managers\Font_Icon_Svg\Font_Awesome -> get_asset_content()
#2: D:\WAMP\www\wp-plugin\elementskit\dev\wp-content\plugins\elementor\core\page-assets\data-managers\base.php(290): Elementor\Core\Page_Assets\Data_Managers\Base -> set_asset_data()
#3: D:\WAMP\www\wp-plugin\elementskit\dev\wp-content\plugins\elementor\core\page-assets\data-managers\base.php(312): Elementor\Core\Page_Assets\Data_Managers\Base -> init_asset_data()
#4: D:\WAMP\www\wp-plugin\elementskit\dev\wp-content\plugins\elementor\core\page-assets\data-managers\base.php(334): Elementor\Core\Page_Assets\Data_Managers\Base -> get_asset_data_from_config()
',
)]
PHP: 2023-08-16 09:26:33 [notice X 4][D:\WAMP\www\wp-plugin\elementskit\dev\wp-content\plugins\elementor\core\page-assets\data-managers\font-icon-svg\font-awesome.php::50] Trying to access array offset on value of type null [array (
  'trace' => '
#0: D:\WAMP\www\wp-plugin\elementskit\dev\wp-content\plugins\elementor\core\page-assets\data-managers\font-icon-svg\font-awesome.php(50): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: D:\WAMP\www\wp-plugin\elementskit\dev\wp-content\plugins\elementor\core\page-assets\data-managers\base.php(139): Elementor\Core\Page_Assets\Data_Managers\Font_Icon_Svg\Font_Awesome -> get_asset_content()
#2: D:\WAMP\www\wp-plugin\elementskit\dev\wp-content\plugins\elementor\core\page-assets\data-managers\base.php(290): Elementor\Core\Page_Assets\Data_Managers\Base -> set_asset_data()
#3: D:\WAMP\www\wp-plugin\elementskit\dev\wp-content\plugins\elementor\core\page-assets\data-managers\base.php(312): Elementor\Core\Page_Assets\Data_Managers\Base -> init_asset_data()
#4: D:\WAMP\www\wp-plugin\elementskit\dev\wp-content\plugins\elementor\core\page-assets\data-managers\base.php(334): Elementor\Core\Page_Assets\Data_Managers\Base -> get_asset_data_from_config()
',
)]
PHP: 2023-08-16 09:26:34 [notice X 2][D:\WAMP\www\wp-plugin\elementskit\dev\wp-content\plugins\elementor\core\page-assets\data-managers\font-icon-svg\font-awesome.php::45] Undefined index: fasicon icon-thumbs-up [array (
  'trace' => '
#0: D:\WAMP\www\wp-plugin\elementskit\dev\wp-content\plugins\elementor\core\page-assets\data-managers\font-icon-svg\font-awesome.php(45): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: D:\WAMP\www\wp-plugin\elementskit\dev\wp-content\plugins\elementor\core\page-assets\data-managers\base.php(139): Elementor\Core\Page_Assets\Data_Managers\Font_Icon_Svg\Font_Awesome -> get_asset_content()
#2: D:\WAMP\www\wp-plugin\elementskit\dev\wp-content\plugins\elementor\core\page-assets\data-managers\base.php(290): Elementor\Core\Page_Assets\Data_Managers\Base -> set_asset_data()
#3: D:\WAMP\www\wp-plugin\elementskit\dev\wp-content\plugins\elementor\core\page-assets\data-managers\base.php(312): Elementor\Core\Page_Assets\Data_Managers\Base -> init_asset_data()
#4: D:\WAMP\www\wp-plugin\elementskit\dev\wp-content\plugins\elementor\core\page-assets\data-managers\base.php(334): Elementor\Core\Page_Assets\Data_Managers\Base -> get_asset_data_from_config()
',
)]

JS: showing 12 of 12JS: 2023-07-30 05:44:27 [error X 1][http://localhost/wp-plugin/elementskit/dev/wp-content/plugins/elementskit/widgets/init/assets/js/elementor.js?ver=3.2.0:2137:30] Cannot read properties of undefined (reading &#039;data&#039;) 
JS: 2023-07-30 09:07:23 [error X 1][http://localhost/wp-plugin/elementskit/dev/wp-content/plugins/elementskit/widgets/init/assets/js/elementor.js?ver=3.2.0:2139:17] $settings is not defined 
JS: 2023-08-01 09:32:45 [error X 1][http://localhost/wp-plugin/elementskit/dev/wp-content/plugins/elementskit-lite/widgets/init/assets/js/elementor.js?ver=2.9.0:741:30] disable_bodyscroll is not defined 
JS: 2023-08-06 04:37:44 [error X 1][http://localhost/wp-plugin/elementskit/dev/wp-content/plugins/elementskit/widgets/init/assets/js/elementor.js?ver=3.2.0:2148:18] keywordButton.on is not a function 
JS: 2023-08-06 05:06:20 [error X 1][http://localhost/wp-plugin/elementskit/dev/wp-content/plugins/elementskit/widgets/init/assets/js/elementor.js?ver=3.2.0:2146:15] keywordID is not defined 
JS: 2023-08-06 05:11:39 [error X 1][http://localhost/wp-plugin/elementskit/dev/wp-content/plugins/elementskit/widgets/init/assets/js/elementor.js?ver=3.2.0:2150:18] keywordDataId.on is not a function 
JS: 2023-08-09 05:31:56 [error X 1][http://localhost/wp-plugin/elementskit/dev/wp-includes/js/dist/vendor/react-dom.js?ver=18.2.0:22849:9] Cannot read properties of undefined (reading &#039;responseId&#039;) 
JS: 2023-08-14 03:34:32 [error X 22][http://localhost/wp-plugin/elementskit/dev/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:19552] Cannot read properties of null (reading &#039;changestop&#039;) 
JS: 2023-08-14 03:34:33 [error X 811][http://localhost/wp-plugin/elementskit/dev/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:14799] Cannot read properties of null (reading &#039;clone&#039;) 
JS: 2023-08-16 03:24:06 [error X 4][http://localhost/wp-plugin/elementskit/dev/wp-content/plugins/elementor-pro/assets/js/packages/editor-documents-extended.js?ver=3.15.2:293:36] Cannot read properties of undefined (reading &#039;entities&#039;) 
JS: 2023-08-16 05:38:28 [error X 6][http://localhost/wp-plugin/elementskit/dev/wp-content/plugins/elementor/assets/js/editor.js?ver=3.15.2:39880:11] Cannot read properties of undefined (reading &#039;localized&#039;) 
JS: 2023-08-16 06:14:01 [error X 1][http://localhost/wp-plugin/elementskit/dev/wp-content/plugins/elementskit/widgets/init/assets/js/elementor.js?ver=3.3.0:1578:25] Cannot read properties of undefined (reading &#039;playerIcons&#039;) 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Incompatible

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @aminul-xs,

Thank you for reaching out! 🙏 

### ⛔ 🧩 Please note that while we do welcome bug reports, we can't provide support for 3rd-party add-ons/extensions.

If your issue is specifically happening only when you're using a feature from a 3rd-party software, or only when the 3rd-party software is active, you'll need to contact the support for that specific software or its developers.

It seems you're both using a widget from the ElementsKit add-on, as well as trying to use a custom icon font from the same add-on. If you want to add custom SVG icons, you need to follow the instructions in the documentation here: 
https://elementor.com/academy/how-to-add-svg-files-to-elementor/

However, we cannot guarantee it will work using a 3rd-party widget. You'll need to check with the ElementsKit team.

### 🛟 This is more of a support question, not really something we can help with here. 

👉 Please remember to check the [Help Center](https://elementor.com/help) or contact [Elementor Support](https://elementor.com/contact) before submitting an issue.


### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

### ⚠️ As a gentle reminder, **🛟 Support Request issues** may need to be closed without troubleshooting. 
Remember to always follow our **[🐞 Bug Report Guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&projects=&template=bug.yml)** to save time and ensure smooth troubleshooting.

Thank you for understanding! 🙏 

Kind regards
