### ISSUE TITLE
⛔ 🐞 Bug Report: Taxonomy filter doesn't look at custom query in post loop

### ISSUE THREAD

**Issue by steveindzine** [elementor/elementor#23614]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When you create a post loop that has a custom query, for instance an ACF relationship field that is on an options page, which limits which posts appear in the loop, if you then use a Taxonomy Filter the terms displayed are not always relevant to the posts displayed in the loop. In Taxonomy Filter widget settings, Empty Items is set to false.

### Steps to reproduce

1) Create an ACF options page and add a relationship field
2) Assign different posts on the options page
3) Create a custom query that displays these posts:
`function home_featured_racedays_query( $query ) {
	$events = get_field('featured_events', 'option');
	if( $events ) {
		$query->set( 'post__in', $events );
		$query->set( 'orderby', 'post__in' );
		$query->set( 'order', 'ASC' );
	}
}
add_action( 'elementor/query/home_featured_racedays', 'home_featured_racedays_query' );`
4) On an Elementor page add a post loop and set the query to use the custom query.
5) Add a taxonomy widget to the page and select the taxonomy to display, maing sure Empty Items is false.
6) Test the page, you will see all terms that have been assigned to posts, not just the terms that have been assigned to the posts in the loop.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>Click to reveal</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.57 (Debian)
	MySQL version: mariadb.org binary distribution v10.4.20
	PHP Version: 8.0.30
	PHP Memory Limit: 512M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.3.1
	Site URL: https://staging.newburyracecourse.co.uk
	Home URL: https://staging.newburyracecourse.co.uk
	WP Multisite: No
	Max Upload Size: 100 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-GB
	Timezone: Europe/London
	Debug Mode: Inactive

== Theme ==
	Name: Newbury Racecourse
	Version: 1.0.0
	Author: InDzine
	Child Theme: Yes
	Parent Theme Name: Astra
	Parent Theme Version: 4.3.0
	Parent Theme Author: Brainstorm Force

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields: Font Awesome
		Version: 4.0.6
		Author: Matt Keys

	Advanced Custom Fields PRO
		Version: 6.2.0
		Author: WP Engine

	Astra Pro
		Version: 4.3.0
		Author: Brainstorm Force

	Breeze
		Version: 2.0.29
		Author: Cloudways

	Custom Fonts
		Version: 2.1.0
		Author: Brainstorm Force

	Delete Expired Transients
		Version: 2.0.7
		Author: WebAware

	Disable Gutenberg
		Version: 3.0
		Author: Jeff Starr

	DynamicConditions
		Version: 1.6.2
		Author: RTO GmbH

	Elementor
		Version: 3.15.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.15.1
		Author: Elementor.com

	iThemes Security
		Version: 8.1.7
		Author: iThemes

	MalCare WordPress Security Plugin - Malware Scanner, Cleaner, Security Firewall
		Version: 5.24
		Author: MalCare Security

	Max Mega Menu
		Version: 3.2.2
		Author: megamenu.com

	Newbury Racecourse Elementor
		Version: 1.0.0
		Author: InDzine

	Permalink Manager Lite
		Version: 2.4.1.3
		Author: Maciej Bis

	Query Monitor
		Version: 3.13.1
		Author: John Blackbourn

	Regenerate Thumbnails
		Version: 3.1.6
		Author: Alex Mills (Viper007Bond)

	Ultimate Addons for Elementor
		Version: 1.36.19
		Author: Brainstorm Force

	YIKES Simple Taxonomy Ordering
		Version: 2.3.4
		Author: YIKES, Inc.

	Yoast Duplicate Post
		Version: 4.5
		Author: Enrico Battocchi & Team Yoast

	Yoast SEO
		Version: 21.0
		Author: Team Yoast


== Must-Use Plugins ==
	Object Cache Pro (MU)
		Version: 1.18.2
		Author: Rhubarb Group


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Optimised DOM Output: Active by default
	Improved asset loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Active
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active by default
	Grid Container: Active
	Default to New Theme Builder: Active by default
	Editor Top Bar: Inactive by default
	Landing pages: Inactive
	Nested Elements: Active
	Lazy Load Background Images: Active
	Global Style Guide: Active
	Page Transitions: Inactive
	Notes: Inactive
	Loop: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Menu: Active
	Taxonomy Filter: Active


== Log ==
	
Log: showing 20 of 242023-08-03 11:12:07 [info] elementor::elementor_updater Started 
2023-08-03 11:12:07 [info] Elementor/Upgrades - _on_each_version Start  
2023-08-03 11:12:07 [info] Elementor/Upgrades - _on_each_version Finished 
2023-08-03 11:12:07 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.14.1',
  'to' => '3.15.1',
)]
2023-08-03 11:12:07 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.14.1',
  'to' => '3.15.1',
)]
2023-08-09 16:04:44 [info] elementor-pro::elementor_pro_updater Started 
2023-08-09 16:04:44 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-08-09 16:04:44 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-08-09 16:04:44 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.15.0',
  'to' => '3.15.1',
)]
2023-08-09 16:04:44 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.15.0',
  'to' => '3.15.1',
)]
2023-08-09 16:04:44 [info] elementor::elementor_updater Started 
2023-08-09 16:04:44 [info] Elementor/Upgrades - _on_each_version Start  
2023-08-09 16:04:44 [info] Elementor/Upgrades - _on_each_version Finished 
2023-08-09 16:04:44 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.15.1',
  'to' => '3.15.2',
)]
2023-08-09 16:04:44 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.15.1',
  'to' => '3.15.2',
)]
2023-08-21 11:42:45 [info] elementor::elementor_updater Started 
2023-08-21 11:42:45 [info] Elementor/Upgrades - _on_each_version Start  
2023-08-21 11:42:45 [info] Elementor/Upgrades - _on_each_version Finished 
2023-08-21 11:42:45 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.15.2',
  'to' => '3.15.3',
)]
2023-08-21 11:42:45 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.15.2',
  'to' => '3.15.3',
)]

PHP: showing 12 of 12PHP: 2023-08-03 12:03:32 [warning X 13][../wp-content/plugins/elementor/app/modules/import-export/module.php::738] Attempt to read property "label" on null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-03 12:03:33 [warning X 12][../wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-03 12:03:40 [warning X 198][../wp-content/plugins/elementor/includes/base/element-base.php::137] foreach() argument must be of type array|object, null given [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-03 12:33:09 [error X 1][../wp-content/plugins/elementor-pro/modules/theme-builder/conditions/condition-base.php::63] Uncaught TypeError: ElementorPro\Modules\ThemeBuilder\Conditions\Condition_Base::__construct(): Argument #1 ($data) must be of type array, WP_Term given, called in ../wp-content/plugins/newbury-elementor/includes/conditions/section.php on line 40 and defined in ../wp-content/plugins/elementor-pro/modules/theme-builder/conditions/condition-base.php:63
Stack trace:
#0 ../wp-content/plugins/newbury-elementor/includes/conditions/section.php(40): ElementorPro\Modules\ThemeBuilder\Conditions\Condition_Base->__construct()
#1 ../wp-content/plugins/elementor-pro/modules/theme-builder/conditions/condition-base.php(66): Elementor_Section_Condition->register_sub_conditions()
#2 ../wp-content/plugins/newbury-elementor/includes/plugin.php(311): ElementorPro\Modules\ThemeBuilder\Conditions\Condition_Base->__construct()
#3 ../wp-includes/class-wp-hook.php(308): Newbury_Elementor_Addon\Plugin->register_conditions()
#4 ../wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#5 ../wp-includes/plugin.php(517): WP_Hook->do_action()
#6 ../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(284): do_action()
#7 ../wp-includes/class-wp-hook.php(308): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->register_conditions()
#8 ../wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#9 ../wp-includes/plugin.php(517): WP_Hook->do_action()
#10 ../wp-settings.php(645): do_action()
#11 ../wp-config.php(100): require_once('/home/1071172.c...')
#12 ../wp-load.php(50): require_once('/home/1071172.c...')
#13 ../wp-admin/admin.php(34): require_once('/home/1071172.c...')
#14 ../wp-admin/post.php(12): require_once('/home/1071172.c...')
#15 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-03 12:33:09 [error X 1][../wp-content/plugins/elementor-pro/modules/theme-builder/conditions/condition-base.php::63] Uncaught TypeError: ElementorPro\Modules\ThemeBuilder\Conditions\Condition_Base::__construct(): Argument #1 ($data) must be of type array, WP_Term given, called in ../wp-content/plugins/newbury-elementor/includes/conditions/section.php on line 40 and defined in ../wp-content/plugins/elementor-pro/modules/theme-builder/conditions/condition-base.php:63
Stack trace:
#0 ../wp-content/plugins/newbury-elementor/includes/conditions/section.php(40): ElementorPro\Modules\ThemeBuilder\Conditions\Condition_Base->__construct()
#1 ../wp-content/plugins/elementor-pro/modules/theme-builder/conditions/condition-base.php(66): Elementor_Section_Condition->register_sub_conditions()
#2 ../wp-content/plugins/newbury-elementor/includes/plugin.php(311): ElementorPro\Modules\ThemeBuilder\Conditions\Condition_Base->__construct()
#3 ../wp-includes/class-wp-hook.php(308): Newbury_Elementor_Addon\Plugin->register_conditions()
#4 ../wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#5 ../wp-includes/plugin.php(517): WP_Hook->do_action()
#6 ../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(284): do_action()
#7 ../wp-includes/class-wp-hook.php(308): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->register_conditions()
#8 ../wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#9 ../wp-includes/plugin.php(517): WP_Hook->do_action()
#10 ../wp-settings.php(645): do_action()
#11 ../wp-config.php(100): require_once('/home/1071172.c...')
#12 ../wp-load.php(50): require_once('/home/1071172.c...')
#13 ../wp-blog-header.php(13): require_once('/home/1071172.c...')
#14 ../index.php(17): require('/home/1071172.c...')
#15 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-04 12:09:33 [warning X 1][../wp-content/plugins/elementor/includes/managers/image.php::113] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-04 12:17:25 [error X 1][../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::304] Uncaught Error: Call to a member function update_meta() on null in ../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:304
Stack trace:
#0 ../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(177): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions()
#2 ../wp-content/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func()
#3 ../wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#4 ../wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#5 ../wp-includes/plugin.php(517): WP_Hook->do_action()
#6 ../wp-admin/admin-ajax.php(188): do_action()
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-10 13:25:32 [warning X 3][../wp-content/plugins/elementor/includes/db.php::267] foreach() argument must be of type array|object, int given [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-10 13:25:34 [warning X 7][../wp-content/plugins/elementor/modules/history/revisions-manager.php::363] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-10 14:24:40 [warning X 13][../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::171] Undefined array key "editor_post_id" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-10 14:57:27 [warning X 4][../wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php::33] Undefined array key 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-11 14:18:55 [warning X 4][../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key "condition_type" [array (
  'trace' => '
#0: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: ../wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]

JS: showing 6 of 6JS: 2023-08-03 12:02:51 [error X 10][https://staging.newburyracecourse.co.uk/wp-includes/js/jquery/jquery.min.js?ver=3.6.4:2:31823] Cannot read properties of undefined (reading 'value') 
JS: 2023-08-04 16:41:59 [error X 1][https://staging.newburyracecourse.co.uk/wp-content/plugins/elementor/assets/js/web-cli.min.js?ver=3.15.1:3:107466] Routes: `panel/editor/settings` not found. 
JS: 2023-08-10 12:25:46 [error X 1][https://staging.newburyracecourse.co.uk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.15.2:3:1106990] Cannot read properties of null (reading 'getBoundingClientRect') 
JS: 2023-08-10 14:30:20 [error X 7][https://staging.newburyracecourse.co.uk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.15.2:3:949697] Cannot read properties of undefined (reading 'settings') 
JS: 2023-08-11 08:58:04 [error X 2][https://staging.newburyracecourse.co.uk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.15.2:3:802938] Cannot read properties of undefined (reading 'localized') 
JS: 2023-08-22 10:14:35 [error X 2][https://staging.newburyracecourse.co.uk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.15.3:3:620456] Cannot read properties of undefined (reading 'isEditable') 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	Newbury Racecourse Elementor: Compatibility not specified
	Ultimate Addons for Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==
	

				

````

</details>

**Comment by nicholaszein** [comment]
Hi, @steveindzine,

Thank you for reaching out! 🙏 

### ⛔ After reviewing your report we concluded this is not a bug caused by Elementor. The feature you're referring to is not yet supported.

If you think this should be an Elementor feature, please submit a new [🚀 Feature Request](https://github.com/orgs/elementor/discussions/new?category=feature-request), and we will consider it in the future if there is enough demand (votes) from other users.

Kind regards

**Comment by nicholaszein** [comment]
This issue is related to #23360
