### ISSUE TITLE
⛔ 🛟 Support Request: Custom Icon font won't finish uploading

### ISSUE THREAD

**Issue by stucooper77084** [elementor/elementor#23632]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Custom Icons won't upload. The name of the icons shows up in the list as a draft. But as the icons didn't upload I didn't have a publish button.

### Steps to reproduce

1) went to Custom Icons and tried uploading with upload button.
2) tired to upload icons by dragging and dropping the .zip file on the upload area
3) Nothing happened.

I am trying to upload a zip file from Fontello.

### Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [x] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>Click to reveal</summary>

````txt


					
== Server Environment ==
	Operating System: WINNT
	Software: nginx/1.16.0
	MySQL version: MySQL Community Server - GPL v8.0.16
	PHP Version: 8.1.9
	PHP Memory Limit: 256M
	PHP Max Input Vars: 4000
	PHP Max Post Size: 1000M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.3.1
	Site URL: http://localhost:10064
	Home URL: http://localhost:10064
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: AstraChild
	Version: 1.0.0
	Author: Brainstorm Force
	Child Theme: Yes
	Parent Theme Name: Astra
	Parent Theme Version: 4.3.0
	Parent Theme Author: Brainstorm Force

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.15.3
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.15.1
		Author: Elementor.com


== Features ==
	Custom Fonts: 1
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active by default
	Grid Container: Inactive by default
	Default to New Theme Builder: Active by default
	Editor Top Bar: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Active by default
	Lazy Load Background Images: Inactive by default
	Global Style Guide: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Menu: Inactive by default
	Taxonomy Filter: Inactive by default


== Log ==
	
PHP: showing 2 of 2PHP: 2023-08-31 16:30:55 [notice X 1][C:\Users\stuco\Local Sites\learn-elementor\app\public\wp-content\plugins\elementor\core\upgrade\manager.php::63] version_compare(): Passing null to parameter #1 ($version1) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-31 19:40:23 [error X 19][C:\Users\stuco\Local Sites\learn-elementor\app\public\wp-content\plugins\elementor-pro\modules\assets-manager\asset-types\icons\custom-icons.php::285] Uncaught TypeError: array_keys(): Argument #1 ($array) must be of type array, bool given in C:\Users\stuco\Local Sites\learn-elementor\app\public\wp-content\plugins\elementor-pro\modules\assets-manager\asset-types\icons\custom-icons.php:285
Stack trace:
#0 C:\Users\stuco\Local Sites\learn-elementor\app\public\wp-content\plugins\elementor-pro\modules\assets-manager\asset-types\icons\custom-icons.php(285): array_keys(false)
#1 C:\Users\stuco\Local Sites\learn-elementor\app\public\wp-content\plugins\elementor-pro\modules\assets-manager\asset-types\icons\custom-icons.php(307): ElementorPro\Modules\AssetsManager\AssetTypes\Icons\Custom_Icons->upload_and_extract_zip()
#2 [internal function]: ElementorPro\Modules\AssetsManager\AssetTypes\Icons\Custom_Icons->custom_icons_upload_handler(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 C:\Users\stuco\Local Sites\learn-elementor\app\public\wp-content\plugins\elementor\core\common\modules\ajax\module.php(175): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#4 C:\Users\stuco\Local Sites\learn-elementor\app\public\wp-includes\class-wp-hook.php(310): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#5 C:\Users\stuco\Local Sites\learn-elementor\app\public\wp-includes\class-wp-hook.php(334): WP_Hook->apply_filters('', Array)
#6 C:\Users\stuco\Local Sites\learn-elementor\app\public\wp-includes\plugin.php(517): WP_Hook->do_action(Array)
#7 C:\Users\stuco\Local Sites\learn-elementor\app\public\wp-admin\admin-ajax.php(188): do_action('wp_ajax_element...')
#8 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 1 of 1JS: 2023-08-31 20:36:35 [error X 1][http://localhost:10064/wp-admin/load-scripts.php?c=0&loadchunk_0=jquery-core,jquery-migrate,utils,wp-polyfill-inert,regenerator-runtime,wp-polyfill,wp-hooks&ver=6.3.1:2:28722] Cannot read properties of undefined (reading 'value') 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==
	

				

````

</details>

**Comment by nicholaszein** [comment]
Hello @stucooper77084,

Thanks for contacting us! 🙏 

### 🛟 This is more of a support question, not really something we can help with here. 

👉 Please remember to check the [Help Center](https://elementor.com/help) or contact [Elementor Support](https://elementor.com/contact) before submitting an issue.


### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

### ⚠️ As a gentle reminder, **🛟 Support Request issues** may need to be closed without troubleshooting. 
Remember to always follow our **[🐞 Bug Report Guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&projects=&template=bug.yml)** to save time and ensure smooth troubleshooting.

Thank you for understanding! 🙏 

Kind regards
