### ISSUE TITLE
Elementor - Tabs Heading Duplicate Bug

### ISSUE THREAD

**Issue by daunkesum** [elementor/elementor#23643]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

The Tabs Widget With Elementor has a bug that has the Tabs Title show twice
the Tabs seems to be duplicated inside the tab section. Photos for idea, 
https://ibb.co/HKd1nC6
https://ibb.co/xqvt05v

### Steps to reproduce

1) Create A Page / Post / Any Template with Elementor Editor
 (Currently Working on Page called "Home"
2)Add a New container Full Width
3) Inside Drag the "Tabs" Widget"
4) Add the Tabs Title (I have added in 3 so far), In the tabs Direction I have put in Left
5) Inside the Tabs add in your Widgets, which I have added Loop Carousel in all 3. 
6) Click on Preview and you will see that the titles are showed twice. 

*Note that on the editor page the issue is not showing but once your preview it or look at the updated page in another broswer tab or browser itself The issue is shown. 

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.39-42
	PHP Version: 7.4.33
	PHP Memory Limit: 768M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.3.1
	Site URL: https://1567dream.com
	Home URL: https://1567dream.com
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 256M
	Max Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: fabrice@requin.biz
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.8.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 6.2.0
		Author: WP Engine

	Advanced Post Queries
		Version: 1.1.1
		Author: Shabti Kaplan

	Akismet Anti-Spam: Spam Protection
		Version: 5.2
		Author: Automattic - Anti Spam Team

	Contact Form 7
		Version: 5.8
		Author: Takayuki Miyoshi

	Elementor
		Version: 3.15.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.15.1
		Author: Elementor.com

	Essential Addons for Elementor
		Version: 5.8.7
		Author: WPDeveloper

	Essential Addons for Elementor - Pro
		Version: 5.4.2
		Author: WPDeveloper

	JetSearch
		Version: 3.1.1
		Author: Crocoblock

	JetSmartFilters
		Version: 3.2.0
		Author: Crocoblock

	MC4WP: Mailchimp for WordPress
		Version: 4.9.7
		Author: ibericode

	One Click Demo Import
		Version: 3.1.2
		Author: OCDI

	SiteGround Optimizer
		Version: 7.4.0
		Author: SiteGround

	SiteGround Security
		Version: 1.4.5
		Author: SiteGround

	WordPress Importer
		Version: 0.8.1
		Author: wordpressdotorg

	WP All Import
		Version: 3.7.2
		Author: Soflyy

	Yoast SEO
		Version: 21.0
		Author: Team Yoast

== Elements Usage ==
	
	container : 0
		button : 8
		container : 51
		eael-filterable-gallery : 1
		heading : 26
		icon : 1
		image : 7
		jet-ajax-search : 1
		jet-smart-filters-active : 2
		jet-smart-filters-remove-filters : 2
		jet-smart-filters-search : 3
		nested-accordion : 2
		text-editor : 16
	header : 4
		button : 4
		container : 7
		heading : 2
		image : 4
		nav-menu : 2
		theme-page-title : 2
	page : 1
		container : 3
		heading : 1
		jet-smart-filters-active : 1
		jet-smart-filters-remove-filters : 1
		jet-smart-filters-search : 1
		text-editor : 1
	wp-post : 
		container : 4
		loop-grid : 1
		nav-menu : 1
		text-editor : 1
	wp-page : 8
		container : 43
		heading : 7
		icon-list : 1
		jet-smart-filters-active : 3
		jet-smart-filters-alphabet : 2
		jet-smart-filters-check-range : 2
		jet-smart-filters-radio : 6
		jet-smart-filters-remove-filters : 3
		jet-smart-filters-search : 3
		loop-carousel : 3
		loop-grid : 4
		mega-menu : 1
		nav-menu : 1
		nested-accordion : 1
		nested-tabs : 1
		text-editor : 5
	loop-item : 15
		container : 4
		heading : 4
		post-info : 1
		text-editor : 2
		theme-post-excerpt : 4
		theme-post-featured-image : 5
		theme-post-title : 5
	landing-page : 0
		heading : 3

== Settings ==
	
	cpt_support: post, page, e-landing-page, collection, emblem, learn, portraits, woodblock-print
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap

== Features ==
	Custom Fonts: 6
	Custom Icons: 0

== Integrations ==
	

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Additional Custom Breakpoints: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Inactive by default
	Grid Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Editor Top Bar: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Active
	Lazy Load Background Images: Inactive by default
	Global Style Guide: Inactive by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Menu: Active
	Taxonomy Filter: Inactive by default

== Log ==
	
Log: showing 10 of 102023-08-11 16:50:26 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.15.1',
  'to' => '3.15.2',
)]
2023-08-11 16:50:26 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.15.1',
  'to' => '3.15.2',
)]
2023-08-15 04:35:32 [info] elementor-pro::elementor_pro_updater Started 
2023-08-15 04:35:32 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-08-15 04:35:32 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-08-15 04:35:32 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.15.0',
  'to' => '3.15.1',
)]
2023-08-23 01:24:14 [info] elementor::elementor_updater Started 
2023-08-23 01:24:14 [info] Elementor/Upgrades - _on_each_version Start  
2023-08-23 01:24:14 [info] Elementor/Upgrades - _on_each_version Finished 
2023-08-23 01:24:14 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.15.2',
  'to' => '3.16.0-dev1',
)]

PHP: showing 14 of 14PHP: 2023-08-12 03:19:00 [notice X 795][/home/customer/www/1567dream.com/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined index: condition_type [array (
  'trace' => '
#0: /home/customer/www/1567dream.com/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /home/customer/www/1567dream.com/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /home/customer/www/1567dream.com/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /home/customer/www/1567dream.com/public_html/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2023-08-15 03:38:31 [notice X 3][/home/customer/www/1567dream.com/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined index: condition_type [array (
  'trace' => '
#0: /home/customer/www/1567dream.com/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/customer/www/1567dream.com/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(84): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /home/customer/www/1567dream.com/public_html/wp-content/plugins/elementor/data/base/endpoint.php(166): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> update_item()
#3: /home/customer/www/1567dream.com/public_html/wp-content/plugins/elementor/data/base/endpoint.php(307): Elementor\Data\Base\Endpoint -> base_callback()
#4: /home/customer/www/1567dream.com/public_html/wp-includes/rest-api/class-wp-rest-server.php(1188): Elementor\Data\Base\Endpoint -> Elementor\Data\Base\{closure}()
',
)]
PHP: 2023-08-15 04:02:58 [notice X 26][/home/customer/www/1567dream.com/public_html/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php::33] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-17 03:44:03 [notice X 37][/home/customer/www/1567dream.com/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-21 00:20:27 [error X 1][/home/customer/www/1567dream.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::304] Uncaught Error: Call to a member function update_meta() on null in /home/customer/www/1567dream.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:304
Stack trace:
#0 /home/customer/www/1567dream.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(177): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(3170, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/customer/www/1567dream.com/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/customer/www/1567dream.com/public_html/wp-includes/class-wp-hook.php(310): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/customer/www/1567dream.com/public_html/ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-21 04:41:10 [notice X 3][/home/customer/www/1567dream.com/public_html/wp-content/plugins/elementor-pro/modules/query-control/module.php::767] Trying to get property 'name' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-22 14:27:16 [notice X 1][/home/customer/www/1567dream.com/public_html/wp-content/plugins/elementor/core/page-assets/data-managers/font-icon-svg/font-awesome.php::45] Undefined index: tags [array (
  'trace' => '
#0: /home/customer/www/1567dream.com/public_html/wp-content/plugins/elementor/core/page-assets/data-managers/font-icon-svg/font-awesome.php(45): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/customer/www/1567dream.com/public_html/wp-content/plugins/elementor/core/page-assets/data-managers/base.php(139): Elementor\Core\Page_Assets\Data_Managers\Font_Icon_Svg\Font_Awesome -> get_asset_content()
#2: /home/customer/www/1567dream.com/public_html/wp-content/plugins/elementor/core/page-assets/data-managers/base.php(290): Elementor\Core\Page_Assets\Data_Managers\Base -> set_asset_data()
#3: /home/customer/www/1567dream.com/public_html/wp-content/plugins/elementor/core/page-assets/data-managers/base.php(312): Elementor\Core\Page_Assets\Data_Managers\Base -> init_asset_data()
#4: /home/customer/www/1567dream.com/public_html/wp-content/plugins/elementor/core/page-assets/data-managers/base.php(334): Elementor\Core\Page_Assets\Data_Managers\Base -> get_asset_data_from_config()
',
)]
PHP: 2023-08-22 14:27:16 [notice X 1][/home/customer/www/1567dream.com/public_html/wp-content/plugins/elementor/core/page-assets/data-managers/font-icon-svg/font-awesome.php::48] Trying to access array offset on value of type null [array (
  'trace' => '
#0: /home/customer/www/1567dream.com/public_html/wp-content/plugins/elementor/core/page-assets/data-managers/font-icon-svg/font-awesome.php(48): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/customer/www/1567dream.com/public_html/wp-content/plugins/elementor/core/page-assets/data-managers/base.php(139): Elementor\Core\Page_Assets\Data_Managers\Font_Icon_Svg\Font_Awesome -> get_asset_content()
#2: /home/customer/www/1567dream.com/public_html/wp-content/plugins/elementor/core/page-assets/data-managers/base.php(290): Elementor\Core\Page_Assets\Data_Managers\Base -> set_asset_data()
#3: /home/customer/www/1567dream.com/public_html/wp-content/plugins/elementor/core/page-assets/data-managers/base.php(312): Elementor\Core\Page_Assets\Data_Managers\Base -> init_asset_data()
#4: /home/customer/www/1567dream.com/public_html/wp-content/plugins/elementor/core/page-assets/data-managers/base.php(334): Elementor\Core\Page_Assets\Data_Managers\Base -> get_asset_data_from_config()
',
)]
PHP: 2023-08-22 14:27:16 [notice X 1][/home/customer/www/1567dream.com/public_html/wp-content/plugins/elementor/core/page-assets/data-managers/font-icon-svg/font-awesome.php::49] Trying to access array offset on value of type null [array (
  'trace' => '
#0: /home/customer/www/1567dream.com/public_html/wp-content/plugins/elementor/core/page-assets/data-managers/font-icon-svg/font-awesome.php(49): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/customer/www/1567dream.com/public_html/wp-content/plugins/elementor/core/page-assets/data-managers/base.php(139): Elementor\Core\Page_Assets\Data_Managers\Font_Icon_Svg\Font_Awesome -> get_asset_content()
#2: /home/customer/www/1567dream.com/public_html/wp-content/plugins/elementor/core/page-assets/data-managers/base.php(290): Elementor\Core\Page_Assets\Data_Managers\Base -> set_asset_data()
#3: /home/customer/www/1567dream.com/public_html/wp-content/plugins/elementor/core/page-assets/data-managers/base.php(312): Elementor\Core\Page_Assets\Data_Managers\Base -> init_asset_data()
#4: /home/customer/www/1567dream.com/public_html/wp-content/plugins/elementor/core/page-assets/data-managers/base.php(334): Elementor\Core\Page_Assets\Data_Managers\Base -> get_asset_data_from_config()
',
)]
PHP: 2023-08-22 14:27:16 [notice X 1][/home/customer/www/1567dream.com/public_html/wp-content/plugins/elementor/core/page-assets/data-managers/font-icon-svg/font-awesome.php::50] Trying to access array offset on value of type null [array (
  'trace' => '
#0: /home/customer/www/1567dream.com/public_html/wp-content/plugins/elementor/core/page-assets/data-managers/font-icon-svg/font-awesome.php(50): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/customer/www/1567dream.com/public_html/wp-content/plugins/elementor/core/page-assets/data-managers/base.php(139): Elementor\Core\Page_Assets\Data_Managers\Font_Icon_Svg\Font_Awesome -> get_asset_content()
#2: /home/customer/www/1567dream.com/public_html/wp-content/plugins/elementor/core/page-assets/data-managers/base.php(290): Elementor\Core\Page_Assets\Data_Managers\Base -> set_asset_data()
#3: /home/customer/www/1567dream.com/public_html/wp-content/plugins/elementor/core/page-assets/data-managers/base.php(312): Elementor\Core\Page_Assets\Data_Managers\Base -> init_asset_data()
#4: /home/customer/www/1567dream.com/public_html/wp-content/plugins/elementor/core/page-assets/data-managers/base.php(334): Elementor\Core\Page_Assets\Data_Managers\Base -> get_asset_data_from_config()
',
)]
PHP: 2023-08-27 00:16:53 [notice X 8][/home/customer/www/1567dream.com/public_html/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/fonts-manager.php::252] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-27 12:49:07 [notice X 6][/home/customer/www/1567dream.com/public_html/wp-content/plugins/elementor/modules/history/revisions-manager.php::363] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-02 10:02:51 [error X 1][/home/customer/www/1567dream.com/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php::1113] Uncaught TypeError: Argument 2 passed to Elementor\TemplateLibrary\Source_Local::on_save_post() must be an instance of WP_Post, instance of stdClass given, called in /home/customer/www/1567dream.com/public_html/wp-includes/class-wp-hook.php on line 312 and defined in /home/customer/www/1567dream.com/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php:1113
Stack trace:
#0 /home/customer/www/1567dream.com/public_html/wp-includes/class-wp-hook.php(312): Elementor\TemplateLibrary\Source_Local->on_save_post(13602, Object(stdClass))
#1 /home/customer/www/1567dream.com/public_html/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters(NULL, Array)
#2 /home/customer/www/1567dream.com/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#3 /home/customer/www/1567dream.com/public_html/wp-includes/post.php(4751): do_action('save_post', 13602, Object(stdClass), true)
#4 /home/customer/www/1567dream.com/public_html/wp-includes/post.php(4853): wp_insert_post(Array, false,  [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-02 10:19:52 [notice X 1][/home/customer/www/1567dream.com/public_html/wp-content/plugins/elementor/modules/usage/module.php::80] Undefined index: publish [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 19 of 19JS: 2023-08-13 12:26:31 [error X 12][https://1567dream.com/wp-content/plugins/elementor-pro/assets/js/gallery.8ca9a354ce039d1ba641.bundle.min.js:2:5674] Cannot read properties of undefined (reading 'setSettings') 
JS: 2023-08-14 01:29:00 [error X 5][https://1567dream.com/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:19552] Cannot read properties of null (reading 'save') 
JS: 2023-08-15 09:37:04 [error X 2][https://1567dream.com/wp-content/plugins/elementor/assets/js/web-cli.min.js?ver=3.15.2:3:107466] Routes: `panel/editor/settings` not found. 
JS: 2023-08-15 11:57:10 [error X 6][https://1567dream.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.15.2:3:670611] elementorFrontend.elements.window.jQuery is not a function 
JS: 2023-08-15 11:57:10 [error X 2][https://1567dream.com/wp-content/uploads/essential-addons-elementor/eael.js?ver=1692092364:10:219602] Cannot read properties of undefined (reading 'hasOwnProperty') 
JS: 2023-08-17 03:26:47 [error X 12][https://1567dream.com/wp-content/plugins/jet-smart-filters/assets/js/public.js?ver=3.2.0:1:156667] Cannot read properties of undefined (reading 'filtersList') 
JS: 2023-08-17 03:26:47 [error X 1][https://1567dream.com/wp-includes/js/jquery/jquery.min.js?ver=3.7.0:2:85515] Cannot read properties of null (reading 'clientHeight') 
JS: 2023-08-17 08:17:28 [error X 8][https://1567dream.com/wp-content/plugins/elementor/assets/js/admin.min.js?ver=3.15.2:3:48021] can't access property "value", l[0] is undefined 
JS: 2023-08-17 09:28:50 [error X 3][https://1567dream.com/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:17898] can't access property "toLowerCase", this.getColorRepresentation() is null 
JS: 2023-08-19 12:23:08 [error X 2][https://1567dream.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.15.2:3:1106988] can't access property "getBoundingClientRect", $ is null 
JS: 2023-08-21 04:02:39 [error X 2][https://1567dream.com/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.15.1:2:64105] can't convert undefined to object 
JS: 2023-08-21 04:52:34 [error X 3][https://1567dream.com/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.15.1:2:64105] Cannot convert undefined or null to object 
JS: 2023-08-22 15:14:33 [error X 19][https://1567dream.com/wp-content/plugins/elementor/assets/js/editor-document.min.js?ver=3.16.0-dev1:2:26663] elementorDevTools is not defined 
JS: 2023-08-23 02:02:20 [error X 6][https://1567dream.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.16.0-dev1:3:1107182] Cannot read properties of null (reading 'getBoundingClientRect') 
JS: 2023-08-23 05:55:11 [error X 2][https://1567dream.com/wp-content/plugins/elementor-pro/assets/lib/sticky/jquery.sticky.min.js?ver=3.15.1:1:1162] Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'. 
JS: 2023-08-26 14:17:14 [error X 2][https://1567dream.com/wp-includes/js/jquery/jquery.min.js?ver=3.7.0:2:28722] Cannot read properties of undefined (reading 'value') 
JS: 2023-08-30 04:34:03 [error X 2][https://1567dream.com/wp-content/plugins/elementor/assets/js/4fdaa70e951ad90db2f2.bundle.min.js:2:7998] Cannot read properties of undefined (reading 'view') 
JS: 2023-09-02 09:55:39 [error X 1][https://1567dream.com/wp-content/plugins/elementor/assets/js/7fada1a61d72da6d46ab.bundle.min.js:2:7780] Cannot read properties of null (reading 'id') 
JS: 2023-09-02 10:08:23 [error X 2][https://1567dream.com/wp-content/plugins/elementor/assets/js/7fada1a61d72da6d46ab.bundle.min.js:2:7826] Cannot read properties of null (reading 'dataset') 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	Essential Addons for Elementor: Compatibility not specified
	Essential Addons for Elementor - Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by daunkesum** [comment]
Update, the only I could fix it is by adding this css code:
.e-n-tab-title.e-collapse {
    display: none;
}

But still this should be looked at if its a bug

**Comment by nicholaszein** [comment]
Hello @daunkesum,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not exactly an issue caused by Elementor. Here's what we found out:
Currently, the new nested Tabs widget has two instances of the Title: one for Desktop, and one for Table/Mobile, when it scales gracefully to an Accordion (if enabled) for better accessibility on smaller screens. This means there is some crucial CSS that needs to be loaded in order to prevent the title from appearing two times for each tab.

Unfortunately, some performance optimization solutions like the Site Ground Optimizer plugin you are using, if defined will try to optimize the CSS by removing unused CSS, or creating critical CSS files. This ends up also removing essential CSS declarations like the one we use to hide the second title and only show it when necessary. It appears in your case that the performance optimization plugin you are using is removing this essential CSS.

However, we have great news! Starting with Elementor 3.16.0, which is currently in Beta Testing, we have optimized the nested Tabs widget and removed the second title altogether. This improves reliability, avoids issues like yours, and also improves Accessibility. You can read more about it in the **[3.16 Beta Announcement](https://github.com/orgs/elementor/discussions/23486#:~:text=Menu%20%26%20Tabs%20Widgets%20Update)**.

### ✅ What you can do to solve your issue:
- Disable the CSS optimization features in your performance optimization plugin (Siteground Optimizer) and clear;purge all levels of cache;
- Use a Custom CSS (as you did) to temporarily hide the second titles (make sure you remove the custom CSS once you update to 3.16, as the HTML infrastructure will change, and custom CSS may break);
- Wait for the 3.16 release which is estimated to be released on **`Semptember, 12`** (Next Week).

### 👍 For now, that's all we can help with. 

Kind regards

**Comment by nicholaszein** [comment]
Hello there @daunkesum!

We have great news! 🙌 

After a revision of our HTML markup, now nested Tabs have only one title, preventing this issue from happening even if you have issues with the cache. This new markup not only is more semantic but is also compliant with accessibility. Therefore...

### 📢 We're happy to announce that the issue you raised was resolved in Elementor v3.16! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
