### ISSUE TITLE
⛔ 🛟 Support Request: Unable to Edit Search Result Page Title in my Child Theme search.php

### ISSUE THREAD

**Issue by morteza-homapour** [elementor/elementor#23642]
### Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I'm facing a persistent issue when attempting to edit the search result page title on my WordPress website by editing the search.php file. Despite following the provided instructions and troubleshooting steps, the changes I make to the search result page title do not take effect.
![Screenshot 2023-09-01 142648](https://github.com/elementor/elementor/assets/143868287/7568aa31-64ae-476f-b669-406b41426065)

### Steps to reproduce

1) Edit search.php File:
Access your WordPress theme directory and locate the search.php file within the Hello Theme.
Edit the search.php file, which involves customizing the search result page title wrapped in h1 directly in the template file.

2) Save search.php Changes:
Save the changes made to the search.php file in your theme directory.

3) View Search Result Page:
Visit the search result page on your live website: (yoursite.com/?s=example) and check if the changes made to the search.php file are reflected in the page title.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [x] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>Click to reveal</summary>

````txt



== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MySQL Community Server (GPL) v5.7.40
	PHP Version: 7.4.33
	PHP Memory Limit: 512M
	PHP Max Input Vars: 8000
	PHP Max Post Size: 500M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.3.1
	Site URL: https://www.visamondial.com
	Home URL: https://www.visamondial.com
	WP Multisite: No
	Max Upload Size: 500 MB
	Memory limit: 3072M
	Max Memory limit: 512M
	Permalink Structure: /%year%/%monthnum%/%postname%/
	Language: en-US
	Timezone: Asia/Tehran
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 2.0.0
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.8.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: fa_IR
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/117.0

== Active Plugins ==
	Advanced Access Manager
		Version: 6.9.14
		Author: Vasyl Martyniuk <vasyl@vasyltech.com>

	Bookly
		Version: 22.2
		Author: Bookly

	Bookly Advanced Google Calendar (Add-on)
		Version: 2.5
		Author: Bookly

	Bookly Customer Cabinet (Add-on)
		Version: 5.5
		Author: Bookly

	Bookly Custom Fields (Add-on)
		Version: 3.7
		Author: Bookly

	Bookly Locations (Add-on)
		Version: 5.5
		Author: Bookly

	Bookly Pro (Add-on)
		Version: 6.7
		Author: Bookly

	Bookly Read Rest API
		Version: 2.3
		Author: wpintegrate.com

	Bookly Service Schedule (Add-on)
		Version: 3.4
		Author: Bookly

	Bookly Special Days (Add-on)
		Version: 5.0
		Author: Bookly

	Bookly Staff Cabinet (Add-on)
		Version: 4.9
		Author: Bookly

	Category Ajax Filter
		Version: 2.7.2.1
		Author: Trusty Plugins

	Custom Post Type UI
		Version: 1.14.0
		Author: WebDevStudios

	Disable Bloat for WordPress &amp; WooCommerce
		Version: 3.2.11
		Author: Disable Bloat

	Elementor
		Version: 3.15.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.15.1
		Author: Elementor.com

	GP Advanced Calculations
		Version: 1.0.12
		Author: Gravity Wiz

	GP Date Time Calculator
		Version: 1.0-beta-4.15
		Author: Gravity Wiz

	GP Limit Dates
		Version: 1.1.24
		Author: Gravity Wiz

	Gravity Forms
		Version: 2.7.13
		Author: Gravity Forms

	Gravity Forms MailerLite Add-On
		Version: 1.0.0
		Author: hannansoft

	Gravity Perks
		Version: 2.3.4
		Author: Gravity Wiz

	IDPay payment gateway for Woocommerce
		Version: 2.2.3
		Author: IDPay

	Legal Signing for Gravity Forms
		Version: 3.2
		Author: CosmicGiant

	NextMove Lite - Thank You Page for WooCommerce
		Version: 2.17.0
		Author: XLPlugins

	Perfmatters
		Version: 2.0.5
		Author: forgemedia

	TablePress
		Version: 2.1.7
		Author: Tobias Bäthge

	TablePress Extension: Responsive Tables
		Version: 1.8
		Author: Tobias Bäthge

	Ultimate 410
		Version: 1.1.5
		Author: tinyweb, 7iebenschlaefer, alpipego

	Visualizer: Tables and Charts for WordPress
		Version: 3.10.4
		Author: Themeisle

	Widget Disable
		Version: 3.0.0
		Author: required

	WooCommerce
		Version: 8.0.3
		Author: Automattic

	WooCommerce Checkout Manager
		Version: 7.2.3
		Author: QuadLayers

	WP-Parsidate
		Version: 4.0.2
		Author: WP-Parsi Team

	wpDiscuz
		Version: 7.6.3
		Author: gVectors Team

	WP Mail SMTP Pro
		Version: 3.8.2
		Author: WP Mail SMTP

	WP Rocket
		Version: 3.14.4.2
		Author: WP Media

	WP Rocket | Disable WP Rocket&#039;s Emoji optimization
		Version: 
		Author: WP Rocket Support Team

	Yoast SEO
		Version: 21.0
		Author: Team Yoast

	Yoast SEO Premium
		Version: 19.1
		Author: Team Yoast

	افزونه پرداخت امن زرین‌پال برای ووکامرس
		Version: 4.8.1
		Author: Masoud Amini , alireza yousefi

	درگاه زرین پال گرویتی فرم
		Version: 2.3.0
		Author: گرویتی فرم پارسی

	مدیریت لایسنس راستچین
		Version: 1.6.5
		Author: RTL-Theme

	گرویتی فرم فارسی
		Version: 2.7.7.1
		Author: گرویتی فرم فارسی


== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com


== Features ==
	Custom Fonts: 0
	Custom Icons: 1

== Integrations ==
	
	woocommerce: Active


== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Inactive
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Inactive by default
	Grid Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header &amp; Footer: Inactive by default
	Editor Top Bar: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Active
	Lazy Load Background Images: Active
	Global Style Guide: Inactive by default
	Page Transitions: Active by default
	Notes: Inactive
	Loop: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Menu: Active
	Taxonomy Filter: Inactive by default


== Log ==
	
PHP: showing 14 of 14PHP: 2023-08-12 14:36:55 [notice X 282][../wp-content/plugins/elementor/includes/utils.php::727] strtolower(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-12 15:11:35 [error X 1][../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::192] Uncaught Error: Class &quot;\ElementorPro\Modules\ThemeBuilder\Conditions\General&quot; not found in ../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:192
Stack trace:
#0 ../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(274): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;register_condition()
#1 ../wp-includes/class-wp-hook.php(308): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;register_conditions()
#2 ../wp-includes/class-wp-hook.php(332): WP_Hook-&gt;apply_filters()
#3 ../wp-includes/plugin.php(517): WP_Hook-&gt;do_action()
#4 ../wp-settings.php(639): do_action()
#5 ../wp-config.php(88): require_once(&#039;...&#039;)
#6 ../wp-load.php(50): require_once(&#039;...&#039;)
#7 ../wp-blog-header.php(13): require_once(&#039;...&#039;)
#8 ../index.php(17): require(&#039;...&#039;)
#9 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-12 19:04:23 [notice X 11][../wp-content/plugins/elementor-pro/core/utils.php::373] Undefined index: name [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-13 13:08:05 [notice X 3][../wp-content/plugins/elementor-pro/modules/woocommerce/module.php::607] parse_str(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-21 18:31:33 [notice X 17][../wp-content/plugins/elementor-pro/modules/dynamic-tags/tags/post-featured-image.php::36] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-24 10:48:34 [notice X 1268][../wp-content/plugins/elementor/includes/conditions.php::87] Undefined index: checkout_layout [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-26 17:06:07 [error X 1][../wp-content/plugins/elementor-pro/modules/theme-builder/module.php::23] Uncaught Error: Class &#039;ElementorPro\Base\Module_Base&#039; not found in ../wp-content/plugins/elementor-pro/modules/theme-builder/module.php:23
Stack trace:
#0 ../wp-content/plugins/elementor-pro/plugin.php(165): include()
#1 [internal function]: ElementorPro\Plugin-&gt;autoload()
#2 ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/module.php(205): spl_autoload_call()
#3 ../wp-content/plugins/elementor-pro/core/app/app.php(86): ElementorPro\Core\App\Modules\SiteEditor\Module-&gt;__construct()
#4 ../wp-content/plugins/elementor-pro/plugin.php(487): ElementorPro\Core\App\App-&gt;__construct()
#5 ../wp-content/plugins/elementor-pro/plugin.php(133): ElementorPro\Plugin-&gt;__construct()
#6 /home/visamondial/domain [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-27 16:19:09 [notice X 1][../wp-content/plugins/elementor/modules/history/revisions-manager.php::363] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-27 17:05:14 [notice X 3][../wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-29 17:53:26 [warning X 2][../wp-content/plugins/elementor-pro/modules/dynamic-tags/tags/post-featured-image.php::36] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-29 17:54:22 [warning X 166][../wp-content/plugins/elementor/includes/conditions.php::87] Undefined array key &quot;checkout_layout&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-30 05:10:12 [notice X 1][../wp-content/plugins/elementor/includes/utils.php::727] strtolower(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ../wp-content/plugins/elementor/includes/utils.php(727): class type strtolower()
#2: ../wp-content/plugins/elementor-pro/modules/call-to-action/widgets/call-to-action.php(1594): Elementor\Utils :: validate_html_tag()
#3: ../wp-content/plugins/elementor/includes/base/controls-stack.php(2243): ElementorPro\Modules\CallToAction\Widgets\Call_To_Action -> render()
#4: ../wp-content/plugins/elementor/includes/base/widget-base.php(609): Elementor\Controls_Stack -> render_by_mode()
',
)]
PHP: 2023-08-30 10:52:33 [warning X 1][../wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined array key &quot;data&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-30 16:48:35 [notice X 1][../wp-content/plugins/elementor/includes/managers/widgets.php::429] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 20 of 232023-08-12 15:10:11 [info] المنتور/Upgrades - _on_each_version Start  
2023-08-12 16:15:12 [info] elementor::elementor_updater Started 
2023-08-12 16:15:12 [info] المنتور/Upgrades - _on_each_version Start  
2023-08-12 16:17:38 [info] elementor::elementor_updater Started 
2023-08-12 16:17:38 [info] المنتور/Upgrades - _on_each_version Start  
2023-08-12 16:18:14 [info] المنتور/Upgrades - _on_each_version Finished 
2023-08-12 16:18:14 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'المنتور',
  'from' => '3.11.2',
  'to' => '3.15.2',
)]
2023-08-12 16:18:16 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'المنتور',
  'from' => '3.11.2',
  'to' => '3.15.2',
)]
2023-08-12 16:28:12 [info] elementor-pro::elementor_pro_updater Started 
2023-08-12 16:28:12 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-08-12 16:28:12 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-08-12 16:28:12 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.3',
  'to' => '3.15.1',
)]
2023-08-12 16:28:16 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.3',
  'to' => '3.15.1',
)]
2023-08-21 12:28:09 [info] elementor::elementor_updater Started 
2023-08-21 12:28:09 [info] المنتور/Upgrades - _on_each_version Start  
2023-08-21 17:20:58 [info] elementor::elementor_updater Started 
2023-08-21 17:20:58 [info] المنتور/Upgrades - _on_each_version Start  
2023-08-21 17:21:00 [info] المنتور/Upgrades - _on_each_version Finished 
2023-08-21 17:21:00 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'المنتور',
  'from' => '3.15.2',
  'to' => '3.15.3',
)]
2023-08-21 17:21:02 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'المنتور',
  'from' => '3.15.2',
  'to' => '3.15.3',
)]

JS: showing 5 of 5JS: 2023-08-13 10:58:37 [error X 1][https://www.visamondial.com/wp-content/plugins/elementor/assets/js/web-cli.min.js?ver=3.15.2:3:107466] Routes: `panel/editor/categories` not found. 
JS: 2023-08-13 10:59:19 [error X 17][https://www.visamondial.com/wp-content/plugins/elementor/assets/js/7fada1a61d72da6d46ab.bundle.min.js:2:7826] Cannot read properties of null (reading &#039;dataset&#039;) 
JS: 2023-08-14 14:51:05 [error X 2][https://www.visamondial.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.15.2:3:802431] Cannot read properties of undefined (reading &#039;toLowerCase&#039;) 
JS: 2023-08-22 09:27:46 [error X 1][https://www.visamondial.com/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.15.3:2:8570] Cannot read properties of undefined (reading &#039;contains&#039;) 
JS: 2023-08-26 11:43:04 [error X 18][https://www.visamondial.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.15.3:3:803140] Cannot read properties of undefined (reading &#039;localized&#039;) 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==
	



````

</details>

**Comment by nicholaszein** [comment]
Hello @morteza-homapour,

Thanks for contacting us! 🙏 

### 🛟 This is more of a support question, not really something we can help with here. 

I see you have Elementor Pro. In this case you could create a **Search Results Archive Template** using Elementor Pro's **Theme Builder**. You don't need to edit the PHP files, and it's recommended you don't. Editing theme files is also not under Elementor's Terms of Services, and we can't provide support for that.

Check this article that teaches you how you can build a **Search Results Archive Template** with Elementor:

https://elementor.com/help/search-results-site-part/

In this case, instead of using the Archive Title widget to set your Search Archive Title, you could use the **Heading Title** widget and give your own title.

👉 Please remember to check the [Help Center](https://elementor.com/help) or contact [Elementor Support](https://elementor.com/contact) before submitting an issue.


### ⚠️ Note that GitHub issues are reserved for <ins>Elementor 🐞 Bug Reports only</ins>, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

### ⚠️ As a gentle reminder, **🛟 Support Request issues** may need to be closed without troubleshooting. 
Remember to always follow our **[🐞 Bug Report Guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&projects=&template=bug.yml)** to save time and ensure smooth troubleshooting.

Thank you for understanding! 🙏 

Kind regards
