### ISSUE TITLE
thanke you page need login to see thanke you

### ISSUE THREAD

**Issue by sepidev** [elementor/elementor#23645]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

hello

Using Elementor, I created a thank you page for your purchase, but this page is not displayed correctly to the user and needs to be logged in. Is there a way to show the order information to the user without login on this page?
On this website, WooCommerce’option to buy as a guest is active.

I contacted elementor pro and they said post my problem in github.

### Steps to reproduce

1)buy something 2)after pay, thanke you page

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MySQL Community Server (GPL) v5.7.40
	PHP Version: 7.4.33
	PHP Memory Limit: 512M
	PHP Max Input Vars: 8000
	PHP Max Post Size: 500M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.3.1
	Site URL: https://www.visamondial.com
	Home URL: https://www.visamondial.com
	WP Multisite: No
	Max Upload Size: 500 مگابایت
	Memory limit: 3072M
	Max Memory limit: 512M
	Permalink Structure: /%year%/%monthnum%/%postname%/
	Language: fa-IR
	Timezone: Asia/Tehran
	Admin Email: info@visamondial.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 2.0.0
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.8.1
	Parent Theme Author: Elementor Team

== User ==
	Role: 
	WP Profile lang: fa_IR
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Access Manager
		Version: 6.9.14
		Author: Vasyl Martyniuk <vasyl@vasyltech.com>

	Bookly
		Version: 22.2
		Author: Bookly

	Bookly Advanced Google Calendar (Add-on)
		Version: 2.5
		Author: Bookly

	Bookly Customer Cabinet (Add-on)
		Version: 5.5
		Author: Bookly

	Bookly Custom Fields (Add-on)
		Version: 3.7
		Author: Bookly

	Bookly Locations (Add-on)
		Version: 5.5
		Author: Bookly

	Bookly Pro (Add-on)
		Version: 6.7
		Author: Bookly

	Bookly Read Rest API
		Version: 2.3
		Author: wpintegrate.com

	Bookly Service Schedule (Add-on)
		Version: 3.4
		Author: Bookly

	Bookly Special Days (Add-on)
		Version: 5.0
		Author: Bookly

	Bookly Staff Cabinet (Add-on)
		Version: 4.9
		Author: Bookly

	Category Ajax Filter
		Version: 2.7.2.1
		Author: Trusty Plugins

	Custom Post Type UI
		Version: 1.14.0
		Author: WebDevStudios

	Disable Bloat for WordPress &amp; WooCommerce
		Version: 3.2.11
		Author: Disable Bloat

	Elementor
		Version: 3.15.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.15.1
		Author: Elementor.com

	GP Advanced Calculations
		Version: 1.0.12
		Author: Gravity Wiz

	GP Date Time Calculator
		Version: 1.0-beta-4.15
		Author: Gravity Wiz

	GP Limit Dates
		Version: 1.1.24
		Author: Gravity Wiz

	Gravity Forms
		Version: 2.7.13
		Author: Gravity Forms

	Gravity Forms MailerLite Add-On
		Version: 1.0.0
		Author: hannansoft

	Gravity Perks
		Version: 2.3.4
		Author: Gravity Wiz

	IDPay payment gateway for Woocommerce
		Version: 2.2.3
		Author: IDPay

	Legal Signing for Gravity Forms
		Version: 3.2
		Author: CosmicGiant

	NextMove Lite - Thank You Page for WooCommerce
		Version: 2.17.0
		Author: XLPlugins

	Perfmatters
		Version: 2.0.5
		Author: forgemedia

	TablePress
		Version: 2.1.7
		Author: Tobias Bäthge

	TablePress Extension: Responsive Tables
		Version: 1.8
		Author: Tobias Bäthge

	Ultimate 410
		Version: 1.1.5
		Author: tinyweb, 7iebenschlaefer, alpipego

	Visualizer: Tables and Charts for WordPress
		Version: 3.10.4
		Author: Themeisle

	Widget Disable
		Version: 3.0.0
		Author: required

	WooCommerce
		Version: 8.0.3
		Author: Automattic

	WooCommerce Checkout Manager
		Version: 7.2.3
		Author: QuadLayers

	WP-Parsidate
		Version: 4.0.2
		Author: WP-Parsi Team

	wpDiscuz
		Version: 7.6.3
		Author: gVectors Team

	WP Mail SMTP Pro
		Version: 3.8.2
		Author: WP Mail SMTP

	WP Rocket
		Version: 3.14.4.2
		Author: WP Media

	WP Rocket | Disable WP Rocket&#039;s Emoji optimization
		Version: 
		Author: WP Rocket Support Team

	Yoast SEO
		Version: 21.0
		Author: Team Yoast

	Yoast SEO Premium
		Version: 19.1
		Author: Team Yoast

	افزونه پرداخت امن زرین‌پال برای ووکامرس
		Version: 4.8.1
		Author: Masoud Amini , alireza yousefi

	درگاه زرین پال گرویتی فرم
		Version: 2.3.0
		Author: گرویتی فرم پارسی

	مدیریت لایسنس راستچین
		Version: 1.6.5
		Author: RTL-Theme

	گرویتی فرم فارسی
		Version: 2.7.7.1
		Author: گرویتی فرم فارسی

== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

== Features ==
	Custom Fonts: 0
	Custom Icons: 1

== Integrations ==
	
	woocommerce: Active

== آزمایشات عنصر ==
	بهینه سازی خروجی DOM: فعال
	بارگذاری دارایی بهبود یافته: فعال
	بارگذاری CSS بهبود یافته: فعال
	نمادهای فونت درون خطی: غیرفعال
	نقاط قطع سفارشی اضافی (جهت رسپانسیو سایت به کار میره): به صورت پیشفرض فعال است
	admin_menu_rearrangement: به صورت پیشفرض غیرفعال است
	کانتینر فلکس باکس: فعال
	ارتقای کتابخانه Swiper: به صورت پیشفرض غیرفعال است
	کانتینر شبکه: به صورت پیشفرض غیرفعال است
	Default to New Theme Builder: به صورت پیشفرض فعال است
	سربرگ و فوتر پوسته سلام: به صورت پیشفرض غیرفعال است
	نوار بالا ویرایشگر: به صورت پیشفرض غیرفعال است
	صفحات فرود: به صورت پیشفرض فعال است
	عناصر تو در تو: فعال
	تصاویر پس زمینه بار تنبل: فعال
	راهنمای سبک جهانی: به صورت پیشفرض غیرفعال است
	Page Transitions: به صورت پیشفرض فعال است
	Notes: غیرفعال
	Loop: به صورت پیشفرض فعال است
	Form Submissions: به صورت پیشفرض فعال است
	Scroll Snap: به صورت پیشفرض فعال است
	Menu: فعال
	Taxonomy Filter: به صورت پیشفرض غیرفعال است

== گزارش ==
	
Log: showing 20 of 232023-08-12 15:10:11 [info] المنتور/Upgrades - _on_each_version Start  
2023-08-12 16:15:12 [info] elementor::elementor_updater Started 
2023-08-12 16:15:12 [info] المنتور/Upgrades - _on_each_version Start  
2023-08-12 16:17:38 [info] elementor::elementor_updater Started 
2023-08-12 16:17:38 [info] المنتور/Upgrades - _on_each_version Start  
2023-08-12 16:18:14 [info] المنتور/Upgrades - _on_each_version Finished 
2023-08-12 16:18:14 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'المنتور',
  'from' => '3.11.2',
  'to' => '3.15.2',
)]
2023-08-12 16:18:16 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'المنتور',
  'from' => '3.11.2',
  'to' => '3.15.2',
)]
2023-08-12 16:28:12 [info] elementor-pro::elementor_pro_updater Started 
2023-08-12 16:28:12 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-08-12 16:28:12 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-08-12 16:28:12 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.3',
  'to' => '3.15.1',
)]
2023-08-12 16:28:16 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.3',
  'to' => '3.15.1',
)]
2023-08-21 12:28:09 [info] elementor::elementor_updater Started 
2023-08-21 12:28:09 [info] المنتور/Upgrades - _on_each_version Start  
2023-08-21 17:20:58 [info] elementor::elementor_updater Started 
2023-08-21 17:20:58 [info] المنتور/Upgrades - _on_each_version Start  
2023-08-21 17:21:00 [info] المنتور/Upgrades - _on_each_version Finished 
2023-08-21 17:21:00 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'المنتور',
  'from' => '3.15.2',
  'to' => '3.15.3',
)]
2023-08-21 17:21:02 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'المنتور',
  'from' => '3.15.2',
  'to' => '3.15.3',
)]

PHP: showing 14 of 14PHP: 2023-08-12 15:11:35 [error X 1][/home/visamondial/domains/visamondial.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::192] Uncaught Error: Class &quot;\ElementorPro\Modules\ThemeBuilder\Conditions\General&quot; not found in /home/visamondial/domains/visamondial.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:192
Stack trace:
#0 /home/visamondial/domains/visamondial.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(274): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;register_condition()
#1 /home/visamondial/domains/visamondial.com/public_html/wp-includes/class-wp-hook.php(308): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;register_conditions()
#2 /home/visamondial/domains/visamondial.com/public_html/wp-includes/class-wp-hook.php(332): WP_Hook-&gt;apply_filters()
#3 /home/visamondial/domains/visamondial.com/public_html/wp-includes/plugin.php(517): WP_Hook-&gt;do_action()
#4 /home/visamondial/domains/visamondial.com/public_html/wp-settings.php(639): do_action()
#5 /home/visamondial/domains/visamondial.com/public_html/wp-config.php(88): require_once(&#039;...&#039;)
#6 /home/visamondial/domains/visamondial.com/public_html/wp-load.php(50): require_once(&#039;...&#039;)
#7 /home/visamondial/domains/visamondial.com/public_html/wp-blog-header.php(13): require_once(&#039;...&#039;)
#8 /home/visamondial/domains/visamondial.com/public_html/index.php(17): require(&#039;...&#039;)
#9 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-12 19:04:23 [notice X 12][/home/visamondial/domains/visamondial.com/public_html/wp-content/plugins/elementor-pro/core/utils.php::373] Undefined index: name [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-13 13:08:05 [notice X 3][/home/visamondial/domains/visamondial.com/public_html/wp-content/plugins/elementor-pro/modules/woocommerce/module.php::607] parse_str(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-21 18:31:33 [notice X 17][/home/visamondial/domains/visamondial.com/public_html/wp-content/plugins/elementor-pro/modules/dynamic-tags/tags/post-featured-image.php::36] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-24 10:48:34 [notice X 1364][/home/visamondial/domains/visamondial.com/public_html/wp-content/plugins/elementor/includes/conditions.php::87] Undefined index: checkout_layout [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-26 17:06:07 [error X 1][/home/visamondial/domains/visamondial.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/module.php::23] Uncaught Error: Class &#039;ElementorPro\Base\Module_Base&#039; not found in /home/visamondial/domains/visamondial.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/module.php:23
Stack trace:
#0 /home/visamondial/domains/visamondial.com/public_html/wp-content/plugins/elementor-pro/plugin.php(165): include()
#1 [internal function]: ElementorPro\Plugin-&gt;autoload()
#2 /home/visamondial/domains/visamondial.com/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/module.php(205): spl_autoload_call()
#3 /home/visamondial/domains/visamondial.com/public_html/wp-content/plugins/elementor-pro/core/app/app.php(86): ElementorPro\Core\App\Modules\SiteEditor\Module-&gt;__construct()
#4 /home/visamondial/domains/visamondial.com/public_html/wp-content/plugins/elementor-pro/plugin.php(487): ElementorPro\Core\App\App-&gt;__construct()
#5 /home/visamondial/domains/visamondial.com/public_html/wp-content/plugins/elementor-pro/plugin.php(133): ElementorPro\Plugin-&gt;__construct()
#6 /home/visamondial/domain [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-27 16:19:09 [notice X 1][/home/visamondial/domains/visamondial.com/public_html/wp-content/plugins/elementor/modules/history/revisions-manager.php::363] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-27 17:05:14 [notice X 4][/home/visamondial/domains/visamondial.com/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-29 17:53:26 [warning X 2][/home/visamondial/domains/visamondial.com/public_html/wp-content/plugins/elementor-pro/modules/dynamic-tags/tags/post-featured-image.php::36] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-29 17:54:22 [warning X 166][/home/visamondial/domains/visamondial.com/public_html/wp-content/plugins/elementor/includes/conditions.php::87] Undefined array key &quot;checkout_layout&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-30 05:10:12 [notice X 1][/home/visamondial/domains/visamondial.com/public_html/wp-content/plugins/elementor/includes/utils.php::727] strtolower(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/visamondial/domains/visamondial.com/public_html/wp-content/plugins/elementor/includes/utils.php(727): class type strtolower()
#2: /home/visamondial/domains/visamondial.com/public_html/wp-content/plugins/elementor-pro/modules/call-to-action/widgets/call-to-action.php(1594): Elementor\Utils :: validate_html_tag()
#3: /home/visamondial/domains/visamondial.com/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(2243): ElementorPro\Modules\CallToAction\Widgets\Call_To_Action -> render()
#4: /home/visamondial/domains/visamondial.com/public_html/wp-content/plugins/elementor/includes/base/widget-base.php(609): Elementor\Controls_Stack -> render_by_mode()
',
)]
PHP: 2023-08-30 10:52:33 [warning X 1][/home/visamondial/domains/visamondial.com/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined array key &quot;data&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-30 16:48:35 [notice X 1][/home/visamondial/domains/visamondial.com/public_html/wp-content/plugins/elementor/includes/managers/widgets.php::429] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-02 17:59:07 [notice X 1][/home/visamondial/domains/visamondial.com/public_html/wp-content/plugins/elementor/modules/system-info/reporters/user.php::75] Undefined offset: 0 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 6 of 6JS: 2023-08-13 10:58:37 [error X 1][https://www.visamondial.com/wp-content/plugins/elementor/assets/js/web-cli.min.js?ver=3.15.2:3:107466] Routes: `panel/editor/categories` not found. 
JS: 2023-08-13 10:59:19 [error X 18][https://www.visamondial.com/wp-content/plugins/elementor/assets/js/7fada1a61d72da6d46ab.bundle.min.js:2:7826] Cannot read properties of null (reading &#039;dataset&#039;) 
JS: 2023-08-14 14:51:05 [error X 2][https://www.visamondial.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.15.2:3:802431] Cannot read properties of undefined (reading &#039;toLowerCase&#039;) 
JS: 2023-08-22 09:27:46 [error X 1][https://www.visamondial.com/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.15.3:2:8570] Cannot read properties of undefined (reading &#039;contains&#039;) 
JS: 2023-08-26 11:43:04 [error X 18][https://www.visamondial.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.15.3:3:803140] Cannot read properties of undefined (reading &#039;localized&#039;) 
JS: 2023-09-02 10:23:26 [error X 3][https://www.visamondial.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.15.3:3:620456] Cannot read properties of undefined (reading &#039;isEditable&#039;) 

== المنتور - Compatibility Tag ==
	
	Elementor Pro: هیچ سازگاری تعیین نشده

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @sepidev! 

Thank you for submitting your issue! 🙏 

While reviewing your issue, I couldn't reproduce the problem you are reporting. Please see the attached video below:


https://github.com/elementor/elementor/assets/113993460/0b8e0a86-6564-439f-aa83-25d87ebcabc7

----

In this video you see me walking through the process of enabling guest purchases in the WooCommerce settings. I then open the "Thank You" page with the Elementor Editor, show you the **`Purchase Summary`** widget working, and open the Site Settings to indicate that the "Thank You" page is selected as the Purchase Summary option.

Next, I open the store in an Incognito/Private window and proceed to make a purchase. Finally, we are redirected to the Purchase Summary page, where you can see the information.

> _Please note that some of the information in the video is in Brazilian Portuguese, and I also have redacted sensitive information._

----

In this installation I have the following active plugins:

```txt

== Active Plugins ==
	Admin and Site Enhancements
		Version: 5.7.0
		Author: Bowo

	All-in-One WP Migration
		Version: 7.78
		Author: ServMask

	All-in-One WP Migration Unlimited Extension
		Version: 2.53
		Author: ServMask

	Elementor
		Version: 3.15.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.15.1
		Author: Elementor.com

	FluentSMTP
		Version: 2.2.5
		Author: FluentSMTP & WPManageNinja Team

	WooCommerce
		Version: 8.0.3
		Author: Automattic

```

The website is running on an NginX server, without any cache enabled.

Could you please try the following and get back to us with your feedback?

#### ⚠️ Make a Backup of your website before proceeding, and if possible do it in a staging environment!

1. 🔬 **Isolate the problem:** Deactivate all of your plugins (except Elementor/Pro and WooCommerce).

2. 🗑️ **Clear the cache:** Clear/Purge, and Disable all levels of cache applicable to your installation, including but not limited to **Server cache** (LiteSpeed), **WordPress (optimization plugin) cache**, **CDN cache**, and **Browser cache**.

3. 🕵️ **Test in Private/Incognito:** Try making a test purchase in a Private/Incognito browser window, and see if the problem still persist.

After following those steps, please share the results with us, and if possible, record your steps using a tool like Loom (free).

We want to make sure this is not a consistent problem caused by Elementor. From what I can gather the issue in question might be local, caused either by cache or by a conflict with another plugin. If the problem does not happen after following those steps, the next step is to slowly re-activate the other plugins one-by-one, while testing to see if the issue happens again each time. If it happens after activating one of the plugins, you'll know the root of the issue. Otherwise, this might be cache-related.

I'll wait for your feedback.

Kind regards

**Comment by sepidev** [comment]
problem solved, thanke you for your support, problem was an option in bookly plugin. this option make all users a wordpress account.
