### ISSUE TITLE
✅ 🐞 Bug Report: Container gap reverts to zero after updating to 3.16

### ISSUE THREAD

**Issue by gabrinascimben** [elementor/elementor#23746]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

After the upgrade to Elementor 3.16, all previously defined column gaps (in every container, unit: rem) are set to 0, and it's necessary to reset them manually

### Steps to reproduce

1) Enable container
2) Set column gap (in rem)
3) Upgrade to Elementor 3.16

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>Click to reveal</summary>

````txt



== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.39-42
	PHP Version: 7.4.33
	PHP Memory Limit: 768M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.3.1
	Site URL: https://headsd12.sg-host.com
	Home URL: https://headsd12.sg-host.com
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 256M
	Max Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: it-IT
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.8.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: it_IT
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 6.2.1.1
		Author: WP Engine

	Advanced Editor Tools
		Version: 5.9.2
		Author: Automattic

	Category Order and Taxonomy Terms Order
		Version: 1.7.9
		Author: Nsp-Code

	Duplicator
		Version: 1.5.5.1
		Author: Duplicator

	Dynamic.ooo - Dynamic Content for Elementor
		Version: 2.11.1
		Author: Dynamic.ooo

	Elementor
		Version: 3.16.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.16.0
		Author: Elementor.com

	SiteGround Optimizer
		Version: 7.4.1
		Author: SiteGround

	SiteGround Security
		Version: 1.4.5
		Author: SiteGround

	WPCode Lite
		Version: 2.1.2
		Author: WPCode

	WPML Multilingual CMS
		Version: 4.6.5
		Author: OnTheGoSystems

	WPML String Translation
		Version: 3.2.7
		Author: OnTheGoSystems

	Yoast SEO
		Version: 21.1
		Author: Team Yoast


== Caratteristiche ==
	Custom Fonts: 1
	Custom Icons: 0

== Integrazioni ==
	


== Esperimenti Elementor ==
	Uscita DOM ottimizzata: Inattivo
	Caricamento delle risorse migliorato: Attivo per impostazione predefinita
	Caricamento CSS migliorato: Attivo per impostazione predefinita
	Icone dei font in linea: Attiva
	Punti di interruzione aggiuntivi: Attivo per impostazione predefinita
	admin_menu_rearrangement: Inattivo per impostazione predefinita
	Contenitore Flexbox: Attiva
	Aggiorna la libreria Swiper: Inattivo per impostazione predefinita
	Contenitore Griglia: Attiva
	Predefinito per Nuovo generatore di temi: Attivo per impostazione predefinita
	Header e Footer del tema Hello: Inattivo per impostazione predefinita
	Barra unificata degli strumenti dell&#039;editor: Inattivo per impostazione predefinita
	Landing Page: Attivo per impostazione predefinita
	Elementi annidati: Attiva
	Lazy Load immagini di sfondo: Attiva
	Guida di stile globale: Attiva
	Transizioni pagine: Attivo per impostazione predefinita
	Notes: Attivo per impostazione predefinita
	Invii forms: Attivo per impostazione predefinita
	Snap scroll: Attivo per impostazione predefinita
	Menu: Attiva
	Taxonomy Filter: Attiva


== Registro ==
	
JS: showing 20 of 22JS: 2023-08-29 09:26:45 [error X 1][https://headsd12.sg-host.com/wp-includes/js/jquery/jquery.min.js?ver=3.7.0:2:37795] Cannot create property &#039;guid&#039; on string &#039;c9939widgetsticky&#039; 
JS: 2023-08-29 09:26:45 [error X 1][https://headsd12.sg-host.com/wp-includes/js/jquery/jquery.min.js?ver=3.7.0:2:37795] Cannot create property &#039;guid&#039; on string &#039;c9945widgetsticky&#039; 
JS: 2023-08-29 09:26:45 [error X 1][https://headsd12.sg-host.com/wp-includes/js/jquery/jquery.min.js?ver=3.7.0:2:37795] Cannot create property &#039;guid&#039; on string &#039;c9954widgetsticky&#039; 
JS: 2023-08-29 09:26:45 [error X 1][https://headsd12.sg-host.com/wp-includes/js/jquery/jquery.min.js?ver=3.7.0:2:37795] Cannot create property &#039;guid&#039; on string &#039;c9966widgetsticky&#039; 
JS: 2023-08-29 09:26:45 [error X 1][https://headsd12.sg-host.com/wp-includes/js/jquery/jquery.min.js?ver=3.7.0:2:37795] Cannot create property &#039;guid&#039; on string &#039;c9972widgetsticky&#039; 
JS: 2023-08-29 09:26:45 [error X 1][https://headsd12.sg-host.com/wp-includes/js/jquery/jquery.min.js?ver=3.7.0:2:37795] Cannot create property &#039;guid&#039; on string &#039;c9981widgetsticky&#039; 
JS: 2023-08-29 09:26:45 [error X 1][https://headsd12.sg-host.com/wp-includes/js/jquery/jquery.min.js?ver=3.7.0:2:37795] Cannot create property &#039;guid&#039; on string &#039;c9990widgetsticky&#039; 
JS: 2023-08-29 09:26:45 [error X 1][https://headsd12.sg-host.com/wp-includes/js/jquery/jquery.min.js?ver=3.7.0:2:37795] Cannot create property &#039;guid&#039; on string &#039;c9998widgetsticky&#039; 
JS: 2023-08-29 09:26:45 [error X 1][https://headsd12.sg-host.com/wp-includes/js/jquery/jquery.min.js?ver=3.7.0:2:37795] Cannot create property &#039;guid&#039; on string &#039;c10006widgetsticky&#039; 
JS: 2023-08-29 09:26:45 [error X 1][https://headsd12.sg-host.com/wp-includes/js/jquery/jquery.min.js?ver=3.7.0:2:37795] Cannot create property &#039;guid&#039; on string &#039;c9623widgetsticky&#039; 
JS: 2023-08-29 09:26:45 [error X 1][https://headsd12.sg-host.com/wp-includes/js/jquery/jquery.min.js?ver=3.7.0:2:37795] Cannot create property &#039;guid&#039; on string &#039;c9725widgetsticky&#039; 
JS: 2023-08-29 09:59:16 [error X 3][https://headsd12.sg-host.com/wp-includes/js/jquery/jquery.min.js?ver=3.7.0:2:37795] Cannot create property &#039;guid&#039; on string &#039;c50690widgetsticky&#039; 
JS: 2023-08-29 10:01:44 [error X 4][https://headsd12.sg-host.com/wp-includes/js/jquery/jquery.min.js?ver=3.7.0:2:28722] e.dispatchEvent is not a function 
JS: 2023-08-30 12:24:36 [error X 1][https://headsd12.sg-host.com/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.15.1:2:64105] Cannot convert undefined or null to object 
JS: 2023-09-07 12:20:33 [error X 1][https://headsd12.sg-host.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.15.3:3:802633] Cannot read properties of undefined (reading &#039;toLowerCase&#039;) 
JS: 2023-09-11 07:44:39 [error X 3][https://headsd12.sg-host.com/wp-includes/js/jquery/jquery.min.js?ver=3.7.0:2:28722] Cannot read properties of undefined (reading &#039;value&#039;) 
JS: 2023-09-11 07:55:48 [error X 4][https://headsd12.sg-host.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.15.3:3:803140] Cannot read properties of undefined (reading &#039;localized&#039;) 
JS: 2023-09-11 07:56:48 [error X 1][https://headsd12.sg-host.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.15.3:3:742356] Cannot read properties of undefined (reading &#039;widgets_settings&#039;) 
JS: 2023-09-11 07:56:52 [error X 4][https://headsd12.sg-host.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.15.3:3:1107192] Cannot read properties of null (reading &#039;getBoundingClientRect&#039;) 
JS: 2023-09-11 10:11:14 [error X 2][https://headsd12.sg-host.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.15.3:3:54034] Cannot read properties of undefined (reading &#039;activate&#039;) 

PHP: showing 6 of 6PHP: 2023-08-30 08:46:19 [notice X 7][../wp-content/plugins/elementor/modules/history/revisions-manager.php::363] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-30 12:49:58 [notice X 6][../wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-30 12:49:59 [notice X 14][../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined index: condition_type [array (
  'trace' => '
#0: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: ../wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2023-09-05 07:55:21 [notice X 1][../wp-content/plugins/elementor/includes/template-library/sources/local.php::780] ob_end_clean(): failed to delete buffer. No buffer to delete [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-11 07:56:49 [notice X 3][../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::171] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-11 10:41:07 [error X 1][../wp-content/plugins/elementor/includes/base/controls-stack.php::2389] Uncaught TypeError: Argument 1 passed to Elementor\Controls_Stack::sanitize_settings() must be of the type array, string given, called in ../wp-content/plugins/elementor/includes/base/controls-stack.php on line 1084 and defined in ../wp-content/plugins/elementor/includes/base/controls-stack.php:2389
Stack trace:
#0 ../wp-content/plugins/elementor/includes/base/controls-stack.php(1084): Elementor\Controls_Stack-&gt;sanitize_settings(&#039;e:10:{s:17:&quot;ani...&#039;)
#1 ../wp-content/plugins/elementor/includes/base/controls-stack.php(2138): Elementor\Controls_Stack-&gt;get_data(&#039;settings&#039;)
#2 ../wp-content/plugins/elementor/core/base/base-object.php(142): Elementor\Controls_Stack-&gt;get_init_settings()
#3 ../wp-content/plugins/elementor/core/ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 14 of 142023-09-11 07:35:47 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Dynamic.ooo - Dynamic Content for Elementor',
  'from' => '2.11.0',
  'to' => '2.11.1',
)]
2023-09-12 13:26:25 [info] elementor::elementor_updater Started 
2023-09-12 13:26:25 [info] Elementor/Upgrades - _on_each_version Start  
2023-09-12 13:26:25 [info] Elementor/Upgrades - _on_each_version Finished 
2023-09-12 13:26:25 [info] Elementor/Upgrades - _v_3_16_0_container_updates Start  
2023-09-12 13:26:26 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.15.3',
  'to' => '3.16.0',
)]
2023-09-12 13:26:29 [info] Elementor/Upgrades - _v_3_16_0_container_updates Finished 
2023-09-12 13:26:29 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Start  
2023-09-12 13:26:29 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Finished 
2023-09-12 13:26:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.15.3',
  'to' => '3.16.0',
)]
2023-09-12 14:57:42 [info] elementor-pro::elementor_pro_updater Started 
2023-09-12 14:57:42 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-09-12 14:57:42 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-09-12 14:57:42 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.15.1',
  'to' => '3.16.0',
)]



== Elementor - Compatibility Tag ==
	
	Dynamic.ooo - Dynamic Content for Elementor: Compatibilità non specificata
	Elementor Pro: Compatibilità non specificata

== Elementor Pro - Compatibility Tag ==
	




````

</details>

**Comment by nicholaszein** [comment]
Hello @gabrinascimben ,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
We tried to reproduce your issue using only Elementor and Elementor Pro version 3.16.0 (both) and could not reproduce the issue. Make sure any add-on you might be using is not causing a conflict with container gaps. As you know, this new version introduced different fields for row and column gaps on Flexbox Containers. By default, after you update and perform the **Data Updater** procedure, Elementor will translate the existing value for the gap to both new separate fields.

![image](https://github.com/elementor/elementor/assets/113993460/36c98a3d-9d2f-4687-ac3b-be22ffe5042a)


You can watch this short recording I made from the process of updating from 3.15 to 3.16.


https://github.com/elementor/elementor/assets/113993460/87dcec28-a279-45ca-89cb-62ece9549a40



### 👍 For now, that's all we can help with. 

If you think this is still an issue caused by Elementor after following the troubleshooting steps above, feel free to open a new 🐞 [Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml).

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards

**Comment by nicholaszein** [comment]
Hello, I'm just passing to let you know that after a review of the script used to migrate gap values in version 3.16.3, this issue should be solved as well.

Thank you for taking the time to share your feedback! 🙏 

Please feel free to update to the latest version.

Kind regards!
