### ISSUE TITLE
⛔ 🐞 Bug Report: Sticky Containers appear over the mega Menu item content on scroll

### ISSUE THREAD

**Issue by bellamystudio** [elementor/elementor#23802]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

If you have a container that is set to stick and you have an elementor mega menu, the sticky container always sits over the mega menu even if you try to set a higher z-index for the menu

https://github.com/elementor/elementor/assets/457677/aaa2eee9-c8ac-4c51-a846-f068aac48135

### Steps to reproduce

1) Create a mega menu
2) Create a long page with an element that should stick to top

The sticky element will appear over the megamenu

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>Click to reveal</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.7.43
	PHP Version: 7.4.33
	PHP Memory Limit: 1024M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 200M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.3.1
	Site URL: https://hamiltonmercer.co.uk
	Home URL: https://hamiltonmercer.co.uk
	WP Multisite: No
	Max Upload Size: 200 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /insights/%postname%/
	Language: en-US
	Timezone: 1
	Debug Mode: Inactive

== Theme ==
	Name: Hamilton Mercer
	Version: 1.0.832
	Author: 
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.8.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/118.0

== Active Plugins ==
	ActiveCampaign Postmark (Official)
		Version: 1.19.1
		Author: Andrew Yates & Matt Gibbs

	Arlo
		Version: 4.2.0
		Author: Arlo

	Elementor
		Version: 3.16.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.16.0
		Author: Elementor.com

	Essential Addons for Elementor
		Version: 5.8.9
		Author: WPDeveloper

	Essential Addons for Elementor - Pro
		Version: 5.4.7
		Author: WPDeveloper

	GA Google Analytics
		Version: 20230721
		Author: Jeff Starr

	Header and Footer Scripts
		Version: 2.2.1
		Author: Digital Liberation

	JetTabs For Elementor
		Version: 2.1.16
		Author: Crocoblock

	JetTricks
		Version: 1.4.1
		Author: Crocoblock

	Shortcoder
		Version: 6.3
		Author: Aakash Chakravarthy

	UpdraftPlus - Backup/Restore
		Version: 1.23.10
		Author: UpdraftPlus.Com, DavidAnderson

	Wordfence Security
		Version: 7.10.3
		Author: Wordfence

	WP Activity Log
		Version: 4.5.3
		Author: WP White Security

	WP Rocket
		Version: 3.14.3
		Author: WP Media

	Wufoo Shortcode Plugin
		Version: 1.55
		Author: Wufoo

	Yoast Duplicate Post
		Version: 4.5
		Author: Enrico Battocchi & Team Yoast

	Yoast SEO
		Version: 21.1
		Author: Team Yoast


== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com


== Elements Usage ==
	
	container : 0
		button : 1
		container : 2
		heading : 4
		image : 1
		jet-tabs : 2
		shortcode : 1
		spacer : 3
		text-editor : 2
	header : 1
		button : 1
		container : 26
		heading : 10
		html : 1
		icon : 1
		icon-list : 1
		image : 1
		mega-menu : 1
		nav-menu : 12
		spacer : 4
		testimonial-carousel : 2
		text-editor : 1
	page : 20
		button : 2
		heading : 4
		icon-list : 2
		shortcode : 1
		spacer : 1
	section : 91
		button : 51
		container : 1
		divider : 16
		heading : 97
		icon-box : 48
		icon-list : 31
		image : 3
		jet-tabs : 2
		shortcode : 5
		spacer : 10
		star-rating : 3
		text-editor : 34
	wp-post : 1
		heading : 12
		image : 2
		spacer : 2
		text-editor : 14
	wp-page : 28
		button : 41
		container : 33
		counter : 3
		divider : 21
		heading : 167
		html : 7
		icon-box : 40
		icon-list : 51
		image : 10
		image-box : 7
		jet-accordion : 5
		jet-tabs : 4
		shortcode : 23
		social-icons : 2
		spacer : 62
		star-rating : 5
		testimonial : 1
		text-editor : 67


== Settings ==
	
	cpt_support: post, page, arlo_upcoming, arlo_event, arlo_venue, arlo_presenter, arlo_eventsearch, arlo_schedule, arlo_oa
	allow_tracking: yes
	unfiltered_files_upload: 1
	load_fa4_shim: yes


== Features ==
	Custom Fonts: 0
	Custom Icons: 2

== Integrations ==
	
	recaptcha_v3: Active


== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active
	Grid Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Inactive by default
	Editor Top Bar: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Active
	Lazy Load Background Images: Inactive by default
	Global Style Guide: Inactive by default
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Menu: Active
	Taxonomy Filter: Inactive by default


== Log ==
	
Log: showing 20 of 322023-09-12 22:38:04 [info] Elementor/Upgrades - _on_each_version Start  
2023-09-12 22:38:05 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.15.1',
  'to' => '3.16.0',
)]
2023-09-12 22:38:06 [info] Elementor/Upgrades - _on_each_version Finished 
2023-09-12 22:38:06 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Start  
2023-09-12 22:38:06 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Finished 
2023-09-12 22:38:06 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.16.0',
  'to' => '3.16.1',
)]
2023-09-13 16:04:15 [info] elementor::elementor_updater Started 
2023-09-13 16:04:15 [info] Elementor/Upgrades - _on_each_version Start  
2023-09-13 16:04:16 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.16.1',
  'to' => '3.16.2',
)]
2023-09-13 16:04:18 [info] Elementor/Upgrades - _on_each_version Finished 
2023-09-13 16:04:18 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Start  
2023-09-13 16:04:18 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Finished 
2023-09-13 16:04:18 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.16.1',
  'to' => '3.16.2',
)]
2023-09-13 16:04:20 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.16.1',
  'to' => '3.16.2',
)]
2023-09-14 16:53:00 [info] elementor::elementor_updater Started 
2023-09-14 16:53:01 [info] Elementor/Upgrades - _on_each_version Start  
2023-09-14 16:53:04 [info] Elementor/Upgrades - _on_each_version Finished 
2023-09-14 16:53:04 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Start  
2023-09-14 16:53:04 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Finished 
2023-09-14 16:53:04 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.16.2',
  'to' => '3.16.3',
)]

JS: showing 8 of 8JS: 2023-08-11 09:43:12 [error X 6][https://hamiltonmercer.co.uk/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.15.2:2:8546] can't access property "contains", event.target.classList is undefined 
JS: 2023-08-24 08:56:28 [error X 4][https://hamiltonmercer.co.uk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.15.3:3:949899] Cannot read properties of undefined (reading 'settings') 
JS: 2023-09-12 15:58:42 [error X 14][https://hamiltonmercer.co.uk/wp-content/plugins/elementor/assets/js/admin.min.js?ver=3.16.0:3:48021] can't access property "value", l[0] is undefined 
JS: 2023-09-12 21:38:54 [error X 3][https://hamiltonmercer.co.uk/wp-content/plugins/elementor/assets/js/4fdaa70e951ad90db2f2.bundle.min.js:2:7765] can't access property "dataset", t.target.closest(...) is null 
JS: 2023-09-13 14:31:42 [error X 43][https://hamiltonmercer.co.uk/wp-content/plugins/elementor/assets/js/common.min.js?ver=3.16.1:3:95814] can't access property "toLowerCase", C.get(...) is undefined 
JS: 2023-09-13 14:31:52 [error X 1][https://hamiltonmercer.co.uk/wp-content/plugins/elementor/assets/js/common.min.js?ver=3.16.1:3:95814] can't access property "toLowerCase" of undefined 
JS: 2023-09-13 16:56:00 [error X 12][https://hamiltonmercer.co.uk/wp-content/plugins/elementor/assets/js/common.min.js?ver=3.16.2:3:95826] Cannot read properties of undefined (reading 'toLowerCase') 
JS: 2023-09-14 08:15:38 [error X 1][https://hamiltonmercer.co.uk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.16.2:3:1108933] can't access property "getBoundingClientRect", V is null 

PHP: showing 2 of 2PHP: 2023-08-31 09:44:59 [error X 1][../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::304] Uncaught Error: Call to a member function update_meta() on null in ../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:304
Stack trace:
#0 ../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(177): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(489, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 ../wp-content/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 ../wp-includes/class-wp-hook.php(310): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 ../wp-includes/class-wp-hook.php(334): WP_Hook->apply_ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-12 17:00:59 [notice X 11][../wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	Essential Addons for Elementor: Compatibility not specified
	Essential Addons for Elementor - Pro: Compatibility not specified
	JetTabs For Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==


````

</details>

**Comment by nicholaszein** [comment]
Hello @bellamystudio! 

Thank you for submitting your issue! 🙏 

Please allow us some time to investigate it, and get back to you with our findings. 🧐 

Best regards

**Comment by nicholaszein** [comment]
Hello @bellamystudio,

Thank you for your patience! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
- You are trying to apply z-index to the wrong element. You need to apply the z-index to the container that is at the **<ins>same level</ins>** as the other containers that follow it.
- Z-index works on a multi-level basis. This means that elements on the same level that come _after_ other elements will always have a higher z-index than the elements before them unless you apply a higher z-index to them.
- However, each element will have its own z-index context as well, which is also isolated from other elements. For example, in the video I am sharing below, if I apply a higher z-index to my menu inside a container, it will only appear in front of other elements that are on the same level it is, only inside his parent container. If there are other containers after its parent container, they will still appear in front of the first container unless you increase the z-index of that first container.
- Your problem is that you are trying to apply the z-index to the wrong element, which in this case is the Menu widget inside a container that is placed before another container that by default will always have a higher z-index.


https://github.com/elementor/elementor/assets/113993460/70659966-c4c0-4559-89b2-242f14955721



### ✅ What you can do to solve your issue:
- Instead of applying the z-index to the Menu widget, apply it to the container that wraps it, and is at the same level as the other sticky container.

Please note that this is the default behavior of the z-index property. And it is more complex than what I'm trying to explain here. **You also need to keep in mind that Elementor will apply a z-index of 99 to any sticky element by default.** So if you want to show elements in front of sticky elements, please use a value that is higher than 99.

If it's still difficult to understand z-index, I suggest you check [this article](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_positioned_layout/Understanding_z-index) and also watch [this video](https://www.youtube.com/watch?v=uS8l4YRXbaw) from Kevin Powell. 

There is also a [cool 3D DevTool in Microsoft Edge](https://devtoolstips.org/tips/en/see-the-page-in-3d/) that helps you visualize the z-index stacking context more clearly!

### 👍 For now, that's all we can help with. 

If you think this is still an issue caused by Elementor after following the troubleshooting steps above, feel free to open a new 🐞 [Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml).

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
