### ISSUE TITLE
⛔ 🐞 Bug Report: Tab titles not changing colour when in the style menu

### ISSUE THREAD

**Issue by Star1Outdoor** [elementor/elementor#23827]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When creating or editing the tabs and trying to change the colour of the titles in the style tab, the 'normal' remains white regardless of the colour selected while hover and active styling works. This seems to only be affecting the colour and it happened as soon as I updated to 3.16.0.

### Steps to reproduce

1) add tabs widget
2) go to styling
3) select titles
4) change normal colour to anything other than white
5) colour does not change at all

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>Click to reveal</summary>

````txt



== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.7.43
	PHP Version: 7.4.33
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 16M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.3.1
	Site URL: https://staroutdoor.com.au
	Home URL: https://staroutdoor.com.au
	WP Multisite: No
	Max Upload Size: 16 MB
	Memory limit: 256M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-AU
	Timezone: Australia/Brisbane
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Twenty One Child Theme
	Version: 1.0
	Author: Your Name
	Child Theme: Yes
	Parent Theme Name: Twenty Twenty-One
	Parent Theme Version: 1.8
	Parent Theme Author: the WordPress team

== User ==
	Role: administrator
	WP Profile lang: en_AU
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.31

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 6.2.1.1
		Author: WP Engine

	All In One WP Security
		Version: 5.2.4
		Author: All In One WP Security & Firewall Team

	Conditional Fields for Contact Form 7
		Version: 2.3.10
		Author: Jules Colle

	Contact Form 7
		Version: 5.8
		Author: Takayuki Miyoshi

	Controls for Contact Form 7
		Version: 0.8.0
		Author: Kaspars Dambis

	Converter for Media
		Version: 5.10.1
		Author: matt plugins

	Duplicate Page
		Version: 4.5.3
		Author: mndpsingh287

	Elementor
		Version: 3.16.3
		Author: Elementor.com

	Elementor Header &amp; Footer Builder
		Version: 1.6.16
		Author: Brainstorm Force, Nikhil Chavan

	Elementor Pro
		Version: 3.16.1
		Author: Elementor.com

	Essential Addons for Elementor
		Version: 5.8.9
		Author: WPDeveloper

	GTM4WP
		Version: 1.18.1
		Author: Thomas Geiger

	Honeypot for Contact Form 7
		Version: 2.1.1
		Author: Nocean

	MultiLine files for Contact Form 7
		Version: 2.6
		Author: Zluck Solutions

	Post SMTP
		Version: 2.6.0
		Author: Post SMTP

	Redirection
		Version: 5.3.10
		Author: John Godley

	Simple History
		Version: 4.5.0
		Author: Pär Thernström

	Sticky Header Effects for Elementor
		Version: 1.6.9
		Author: Rwattner

	Twentig
		Version: 1.6.2
		Author: Twentig.com

	UpdraftPlus - Backup/Restore
		Version: 1.23.10
		Author: UpdraftPlus.Com, DavidAnderson

	Void Contact Form 7 Widget For Elementor Page Builder
		Version: 2.3
		Author: voidCoders

	WP Super Cache
		Version: 1.10.0
		Author: Automattic

	Yoast SEO
		Version: 21.1
		Author: Team Yoast


== Must-Use Plugins ==
	aios-firewall-loader.php
		Version: 
		Author: 

	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

	ManageWP - Worker Loader
		Version: 1.0.0
		Author: GoDaddy


== Features ==
	Custom Fonts: 1
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Optimised DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Inactive by default
	Grid Container: Inactive by default
	Default to New Theme Builder: Active by default
	Editor Top Bar: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Active
	Lazy Load Background Images: Inactive by default
	Global Style Guide: Inactive by default
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Menu: Inactive by default
	Taxonomy Filter: Inactive by default


== Log ==
	
PHP: showing 20 of 22PHP: 2023-09-14 11:32:57 [error X 1][../wp-content/plugins/elementor-pro/modules/forms/registrars/form-fields-registrar.php::38] Uncaught Error: Class &#039;ElementorPro\Modules\Forms\Fields\Acceptance&#039; not found in ../wp-content/plugins/elementor-pro/modules/forms/registrars/form-fields-registrar.php:38
Stack trace:
#0 ../wp-content/plugins/elementor-pro/modules/forms/registrars/form-fields-registrar.php(25): ElementorPro\Modules\Forms\Registrars\Form_Fields_Registrar-&gt;init()
#1 ../wp-content/plugins/elementor-pro/modules/forms/module.php(182): ElementorPro\Modules\Forms\Registrars\Form_Fields_Registrar-&gt;__construct()
#2 ../wp-content/plugins/elementor/core/base/module.php(85): ElementorPro\Modules\Forms\Module-&gt;__construct()
#3 ../wp-content/plugins/elementor-pro/core/modules-manager.php(89): Elementor\Core\Base\Module::instance()
#4 ../wp-content/plugins/elementor-pro/plugin.php(369): ElementorPro\Core\Modules_Manager-&gt;__construct()
#5 ../wp-includes/class-wp-hook.php(310) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-14 11:33:08 [error X 1][../wp-content/plugins/elementor/includes/autoloader.php::294] require(): Failed opening required &#039;../wp-content/plugins/elementor//includes/settings/settings-page.php&#039; (include_path=&#039;.:/opt/alt/php74/usr/share/pear&#039;) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-14 11:33:09 [error X 1][../wp-content/plugins/elementor-pro/core/modules-manager.php::78] Uncaught Error: Class &#039;\ElementorPro\Modules\CustomCode\Module&#039; not found in ../wp-content/plugins/elementor-pro/core/modules-manager.php:78
Stack trace:
#0 ../wp-content/plugins/elementor-pro/plugin.php(369): ElementorPro\Core\Modules_Manager-&gt;__construct()
#1 ../wp-includes/class-wp-hook.php(310): ElementorPro\Plugin-&gt;on_elementor_init(&#039;&#039;)
#2 ../wp-includes/class-wp-hook.php(334): WP_Hook-&gt;apply_filters(NULL, Array)
#3 ../wp-includes/plugin.php(517): WP_Hook-&gt;do_action(Array)
#4 ../wp-content/plugins/elementor/includes/plugin.php(658): do_action(&#039;elementor/init&#039;)
#5 ../wp-includes/class-wp-hook.php(310): Elementor\Plugin-&gt;init(&#039;&#039;)
#6 ../wp-includes/class-wp-hook.php(334): WP_Hook-&gt;apply_filters(NULL, Array)
#7 ../wp-includes/plugin.php(517): WP_Hook-&gt;do_action(Array)
#8 /home/staroutd/public_htm [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-14 11:33:13 [error X 1][../wp-content/plugins/elementor/includes/autoloader.php::294] require(): Failed opening required &#039;../wp-content/plugins/elementor//includes/controls/button.php&#039; (include_path=&#039;.:/opt/alt/php74/usr/share/pear&#039;) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-14 11:33:15 [error X 1][../wp-content/plugins/elementor/core/modules-manager.php::53] Uncaught Error: Class &#039;Elementor\Modules\WebCli\Module&#039; not found in ../wp-content/plugins/elementor/core/modules-manager.php:53
Stack trace:
#0 ../wp-content/plugins/elementor/includes/plugin.php(730): Elementor\Core\Modules_Manager-&gt;__construct()
#1 ../wp-content/plugins/elementor/includes/plugin.php(647): Elementor\Plugin-&gt;init_components()
#2 ../wp-includes/class-wp-hook.php(310): Elementor\Plugin-&gt;init(&#039;&#039;)
#3 ../wp-includes/class-wp-hook.php(334): WP_Hook-&gt;apply_filters(NULL, Array)
#4 ../wp-includes/plugin.php(517): WP_Hook-&gt;do_action(Array)
#5 ../wp-settings.php(632): do_action(&#039;init&#039;)
#6 ../wp-config.php(85): require_once(&#039;/home/staroutd/...&#039;)
#7 ../wp-load.php(50): require_once(&#039;/home/staroutd/...&#039;)
#8 ../wp-blog-header.php(13): require_once(&#039;/home/staroutd/...&#039;)
# [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-14 11:33:22 [error X 1][../wp-content/plugins/elementor/includes/autoloader.php::294] require(): Failed opening required &#039;../wp-content/plugins/elementor/modules/compatibility-tag/module.php&#039; (include_path=&#039;.:/opt/alt/php74/usr/share/pear&#039;) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-14 11:33:27 [error X 1][../wp-content/plugins/elementor-pro/modules/theme-builder/skins/posts-archive-skin-classic.php::10] Trait &#039;ElementorPro\Modules\ThemeBuilder\Skins\Posts_Archive_Skin_Base&#039; not found [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-14 11:33:31 [error X 1][../wp-content/plugins/elementor-pro/modules/forms/module.php::73] Uncaught Error: Class &#039;ElementorPro\Modules\Forms\Controls\Fields_Repeater&#039; not found in ../wp-content/plugins/elementor-pro/modules/forms/module.php:73
Stack trace:
#0 ../wp-includes/class-wp-hook.php(310): ElementorPro\Modules\Forms\Module-&gt;register_controls(Object(Elementor\Controls_Manager))
#1 ../wp-includes/class-wp-hook.php(334): WP_Hook-&gt;apply_filters(NULL, Array)
#2 ../wp-includes/plugin.php(517): WP_Hook-&gt;do_action(Array)
#3 ../wp-content/plugins/elementor/includes/managers/controls.php(496): do_action(&#039;elementor/contr...&#039;, Object(Elementor\Controls_Manager))
#4 ../wp-content/plugins/elementor/includes/managers/controls.php(609): Elementor\Controls_Manager-&gt;register_controls()
#5 ../wp-content/plugins/elementor/includes/managers/controls.php(628): Elementor\Controls_Manager-&gt;get_controls()
#6 ../wp-content/plug [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-14 11:33:37 [error X 1][../wp-content/plugins/elementor/includes/autoloader.php::294] require(): Failed opening required &#039;../wp-content/plugins/elementor/core/base/background-task.php&#039; (include_path=&#039;.:/opt/alt/php74/usr/share/pear&#039;) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-14 11:33:39 [error X 1][../wp-content/plugins/elementor/includes/autoloader.php::294] require(): Failed opening required &#039;../wp-content/plugins/elementor/modules/kit-elements-defaults/data/controller.php&#039; (include_path=&#039;.:/opt/alt/php74/usr/share/pear&#039;) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-14 11:33:43 [error X 1][../wp-content/plugins/elementor-pro/modules/theme-builder/conditions/post-type-archive.php::65] Uncaught Error: Class &#039;ElementorPro\Modules\ThemeBuilder\Conditions\Child_Of_Term&#039; not found in ../wp-content/plugins/elementor-pro/modules/theme-builder/conditions/post-type-archive.php:65
Stack trace:
#0 ../wp-content/plugins/elementor-pro/modules/theme-builder/conditions/condition-base.php(66): ElementorPro\Modules\ThemeBuilder\Conditions\Post_Type_Archive-&gt;register_sub_conditions()
#1 ../wp-content/plugins/elementor-pro/modules/theme-builder/conditions/post-type-archive.php(29): ElementorPro\Modules\ThemeBuilder\Conditions\Condition_Base-&gt;__construct()
#2 ../wp-content/plugins/elementor-pro/modules/theme-builder/conditions/archive.php(47): ElementorPro\Modules\ThemeBuilder\Conditions\Post_Type_Archive-&gt;__construct(Array)
#3 ../wp-content/plugins/elementor-pro/modules/theme-builder/conditions/condition-base.php(66): ElementorPro\Modules\ThemeBuilder\Conditions\Archive-&gt;register_sub_condit [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-14 11:33:50 [error X 1][../wp-content/plugins/elementor-pro/plugin.php::369] Uncaught Error: Class &#039;ElementorPro\Core\Modules_Manager&#039; not found in ../wp-content/plugins/elementor-pro/plugin.php:369
Stack trace:
#0 ../wp-includes/class-wp-hook.php(310): ElementorPro\Plugin-&gt;on_elementor_init(&#039;&#039;)
#1 ../wp-includes/class-wp-hook.php(334): WP_Hook-&gt;apply_filters(NULL, Array)
#2 ../wp-includes/plugin.php(517): WP_Hook-&gt;do_action(Array)
#3 ../wp-content/plugins/elementor/includes/plugin.php(658): do_action(&#039;elementor/init&#039;)
#4 ../wp-includes/class-wp-hook.php(310): Elementor\Plugin-&gt;init(&#039;&#039;)
#5 ../wp-includes/class-wp-hook.php(334): WP_Hook-&gt;apply_filters(NULL, Array)
#6 ../wp-includes/plugin.php(517): WP_Hook-&gt;do_action(Array)
#7 ../wp-settings.php(632): do_action(&#039;init&#039;)
#8 ../wp-config.php(85): require_once(&#039;/home/staroutd/...&#039;)
#9 /home/staroutd/publ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-14 11:33:50 [error X 1][../wp-content/plugins/elementor/includes/autoloader.php::294] require(): Failed opening required &#039;../wp-content/plugins/elementor//includes/controls/groups/typography.php&#039; (include_path=&#039;.:/opt/alt/php74/usr/share/pear&#039;) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-14 11:33:53 [notice X 1][../wp-content/plugins/elementor/includes/autoloader.php::294] require(): read of 9511 bytes failed with errno=12 Cannot allocate memory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-14 12:00:06 [error X 1][../wp-content/plugins/elementor-pro/modules/forms/module.php::174] Uncaught Error: Class &#039;ElementorPro\Modules\Forms\Classes\Recaptcha_Handler&#039; not found in ../wp-content/plugins/elementor-pro/modules/forms/module.php:174
Stack trace:
#0 ../wp-content/plugins/elementor/core/base/module.php(85): ElementorPro\Modules\Forms\Module-&gt;__construct()
#1 ../wp-content/plugins/elementor-pro/core/modules-manager.php(90): Elementor\Core\Base\Module::instance()
#2 ../wp-content/plugins/elementor-pro/plugin.php(369): ElementorPro\Core\Modules_Manager-&gt;__construct()
#3 ../wp-includes/class-wp-hook.php(310): ElementorPro\Plugin-&gt;on_elementor_init(&#039;&#039;)
#4 ../wp-includes/class-wp-hook.php(334): WP_Hook-&gt;apply_filters(NULL, Array)
#5 ../wp-includes/plugin.php(517): WP_Hook-&gt;do_action(Array)
#6 ../wp-content/plugins/elementor/includes/plugin.php(658): do_action(&#039;elementor/init&#039;)
#7 /home/staroutd/public_htm [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-14 14:07:05 [notice X 21][../wp-content/plugins/elementor-pro/core/utils.php::373] Undefined index: name [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-15 01:02:59 [error X 1][../wp-content/plugins/elementor-pro/modules/forms/registrars/form-actions-registrar.php::46] Uncaught Error: Class &#039;ElementorPro\Modules\Forms\Actions\Mailerlite&#039; not found in ../wp-content/plugins/elementor-pro/modules/forms/registrars/form-actions-registrar.php:46
Stack trace:
#0 ../wp-includes/class-wp-hook.php(310): ElementorPro\Modules\Forms\Registrars\Form_Actions_Registrar-&gt;ElementorPro\Modules\Forms\Registrars\{closure}(Object(ElementorPro\Modules\Forms\Registrars\Form_Actions_Registrar))
#1 ../wp-includes/class-wp-hook.php(334): WP_Hook-&gt;apply_filters(NULL, Array)
#2 ../wp-includes/plugin.php(517): WP_Hook-&gt;do_action(Array)
#3 ../wp-content/plugins/elementor-pro/modules/forms/registrars/form-actions-registrar.php(74): do_action(&#039;elementor_pro/f...&#039;, Object(ElementorPro\Modules\Forms\Registrars\Form_Actions_Registrar))
#4 ../wp-content/plugins/elementor-pro/modules/forms/registrars/form-actions-registrar.php(26): ElementorPro\Modules\Forms\Registrars\ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-15 02:38:21 [error X 1][../wp-content/plugins/elementor/includes/autoloader.php::294] require(): Failed opening required &#039;../wp-content/plugins/elementor/app/app.php&#039; (include_path=&#039;.:/opt/alt/php74/usr/share/pear&#039;) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-15 13:54:34 [notice X 6][../wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-15 13:54:35 [notice X 18][../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined index: condition_type [array (
  'trace' => '
#0: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: ../wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]

JS: showing 1 of 1JS: 2023-09-14 01:48:47 [error X 1][https://staroutdoor.com.au/wp-content/plugins/elementor/assets/js/web-cli.min.js?ver=3.16.1:3:82386] Data commands: `` not found. 

Log: showing 20 of 202023-09-15 10:00:12 [info] elementor::elementor_updater Started 
2023-09-15 10:00:13 [info] Elementor/Upgrades - _on_each_version Start  
2023-09-15 10:00:13 [info] Elementor/Upgrades - _on_each_version Finished 
2023-09-15 10:00:13 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.14.1',
  'to' => '3.16.2',
)]
2023-09-15 10:00:18 [info] elementor-pro::elementor_pro_updater Started 
2023-09-15 10:00:18 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-09-15 10:00:18 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-09-15 10:00:18 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.14.1',
  'to' => '3.16.0',
)]
2023-09-18 11:58:25 [info] elementor::elementor_updater Started 
2023-09-18 11:58:25 [info] Elementor/Upgrades - _on_each_version Start  
2023-09-18 11:58:25 [info] Elementor/Upgrades - _on_each_version Finished 
2023-09-18 11:58:25 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Start  
2023-09-18 11:58:26 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Finished 
2023-09-18 11:58:26 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.16.2',
  'to' => '3.16.3',
)]
2023-09-18 11:58:26 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.16.2',
  'to' => '3.16.3',
)]
2023-09-18 11:58:48 [info] elementor-pro::elementor_pro_updater Started 
2023-09-18 11:58:48 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-09-18 11:58:49 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-09-18 11:58:49 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.16.0',
  'to' => '3.16.1',
)]
2023-09-18 11:58:49 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.16.0',
  'to' => '3.16.1',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Header & Footer Builder: Compatibility not specified
	Elementor Pro: Compatibility not specified
	Essential Addons for Elementor: Compatibility not specified
	Sticky Header Effects for Elementor: Compatibility not specified
	Void Contact Form 7 Widget For Elementor Page Builder: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

````

</details>

**Comment by nicholaszein** [comment]
Hello @Star1Outdoor,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
The nested **Tabs** widget received fundamental changes to its markup in the **3.16** version. These changes included applying a more semantical and simplified HTML markup along with new classes for all elements to improve both **Performance** and **Accessibility**.
For websites without any cache or performance optimization solution like the one in the video below, the change was seamless. However, for websites with any performance optimization solution, or any level of cache employed the transition between the old version and the new, could have issues, since the cache will still show the old markup and old styles for this widget.

As you can see in the video below, I have no issues setting colors for the Tab Titles.


https://github.com/elementor/elementor/assets/113993460/514ee160-2ed8-437c-bef1-f63018793eb7



### ✅ What you can do to solve your issue:
Hey @XXX! 

Thanks for the feedback! 🙏 

### 🧐 Before we continue, and in order to solve your issue, please try these **Troubleshooting steps**:

#### ⚠️ Make a Backup of your website before proceeding, and if possible do it in a staging environment!

1. 🔴 **Improved CSS Loading:** Go to your WordPress **`Dashboard`** > **`Elementor`** > **`Settings`** > **`Features`** page and set the **`Improved CSS Loading`** experimental feature to **`Inactive`**. This will help force your browser to re-download the Tabs assets.
2. 🔄 **Regenerate CSS:** Go to your WordPress **`Dashboard`** > **`Elementor`** > **`Tools`** > **`General`** and click to **`Regenerate CSS & Data`**.
3. 🗑️ **Clear the cache:** Clear all levels of cache, including but not limited to **Server cache**, **WordPress (optimization plugin) cache**, **CDN cache**, and **Browser cache**. Also, try visiting the front page of your website in **incognito/private** mode.

### 👍 For now, that's all we can help with. 

If you think this is still an issue caused by Elementor after following the troubleshooting steps above, please contact Elementor Support.

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
