### ISSUE TITLE
⛔ 🐞 Bug Report: Taxonomy Filter does not work with a Products Loop Grid with a custom query

### ISSUE THREAD

**Issue by gstarwd** [elementor/elementor#23865]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Taxonomy filter does not work on Elementor Loop Grid ，activate any Taxonomy ，it also stay with the all content。
https://ai-all-in.one/  

I find this request be 404：https://ai-all-in.one/wp-json/elementor-pro/v1/refresh-loop
{"code":"rest_no_route","message":"No route was found matching the URL and request method.","data":{"status":404}}

how can i Fix it？

### Steps to reproduce

https://ai-all-in.one/   activate any Taxonomy ，it also stay with the all content。

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>Click to reveal</summary>

````txt



== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.6.14
	PHP Version: 8.1.18
	PHP Memory Limit: 2048M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 2048M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.3.1
	Site URL: https://ai-all-in.one
	Home URL: https://ai-all-in.one
	WP Multisite: No
	Max Upload Size: 2 GB
	Memory limit: 40M
	Max Memory limit: 2048M
	Permalink Structure: /%postname%/
	Language: en-GB
	Timezone: Europe/London
	Debug Mode: Inactive

== Theme ==
	Name: GeneratePress
	Version: 3.3.1
	Author: Tom Usborne
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

== Active Plugins ==
	Auto Upload Images
		Version: 3.3.2
		Author: Ali Irani

	BEAR – Bulk Editor and Products Manager Professional for WooCommerce
		Version: 1.1.3.3
		Author: realmag777

	Classic Editor
		Version: 1.6.3
		Author: WordPress Contributors

	Display Posts
		Version: 3.0.2
		Author: Bill Erickson

	DoLogin Security
		Version: 3.7.1
		Author: WPDO

	Elementor
		Version: 3.16.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.16.1
		Author: Elementor.com

	Essential Addons for Elementor
		Version: 5.8.8
		Author: WPDeveloper

	Essential Blocks
		Version: 4.2.5
		Author: WPDeveloper

	FiboSearch - AJAX Search for WooCommerce
		Version: 1.25.0
		Author: FiboSearch Team

	GenerateBlocks
		Version: 1.8.2
		Author: Tom Usborne

	Google Listings and Ads
		Version: 2.5.5
		Author: WooCommerce

	Hostinger
		Version: 1.7.0
		Author: Hostinger

	Hostinger AI Assistant
		Version: 1.4.0
		Author: Hostinger

	Jetpack
		Version: 12.5
		Author: Automattic

	Jetpack Protect
		Version: 1.4.1
		Author: Automattic - Jetpack Security team

	LiteSpeed Cache
		Version: 5.6
		Author: LiteSpeed Technologies

	MailPoet
		Version: 4.26.1
		Author: MailPoet

	Pinterest for WooCommerce
		Version: 1.3.9
		Author: WooCommerce

	Premium Addons for Elementor
		Version: 4.10.7
		Author: Leap13

	Product Filter by WBW
		Version: 2.4.5
		Author: WBW

	Product Import Export for WooCommerce
		Version: 2.3.3
		Author: WebToffee

	Rank Math SEO
		Version: 1.0.201.1
		Author: Rank Math

	Royal Elementor Addons
		Version: 1.3.77
		Author: WP Royal

	Site Kit by Google
		Version: 1.108.0
		Author: Google

	Spectra
		Version: 2.7.8
		Author: Brainstorm Force

	Starter Templates
		Version: 3.4.0
		Author: Brainstorm Force

	Templately
		Version: 2.2.4
		Author: Templately

	Unlimited Elements for Elementor
		Version: 1.5.82
		Author: Unlimited Elements

	WooCommerce
		Version: 8.0.3
		Author: Automattic

	WooCommerce External Product New Tab
		Version: 1.0.4
		Author: Stuart Duff

	WooCommerce Product Table Lite
		Version: 2.6.1
		Author: WC Product Table

	WPForms Lite
		Version: 1.8.3.1
		Author: WPForms

	WP Import Export Lite
		Version: 3.9.25
		Author: VJInfotech


== Elements Usage ==
	
	wp-page : 5
		animated-headline : 1
		container : 9
		fibosearch : 1
		loop-grid : 1
		premium-addon-blog : 1
		premium-woo-products : 1
		taxonomy-filter : 1
		text-editor : 1
		wpr-mega-menu : 1
		wpr-posts-timeline : 1
	loop-item : 1
		container : 1
		theme-post-featured-image : 1
		theme-post-title : 1


== Settings ==
	
	cpt_support: post, page, product, wpr_templates, wpr_mega_menu, wpr_mega_menu
	allow_tracking: yes
	font_display: swap


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	
	woocommerce: Active


== Elementor Experiments ==
	Optimised DOM Output: Active by default
	Improved asset loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active by default
	Grid Container: Active
	Default to New Theme Builder: Active by default
	Editor Top Bar: Active
	Landing pages: Active
	Nested Elements: Active
	Lazy Load Background Images: Inactive by default
	Pages Panel: Inactive by default
	Global Style Guide: Active
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Menu: Active
	Taxonomy Filter: Active


== Log ==
	
PHP: showing 3 of 3PHP: 2023-09-11 15:22:10 [notice X 3][../wp-content/plugins/elementor/core/upgrade/manager.php::63] version_compare(): Passing null to parameter #1 ($version1) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-12 15:24:16 [warning X 14][../wp-content/plugins/elementor/modules/history/revisions-manager.php::363] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-20 05:43:04 [error X 1][../wp-content/plugins/elementor-pro/modules/woocommerce/module.php::1519] Uncaught TypeError: Unsupported operand types: string / int in ../wp-content/plugins/elementor-pro/modules/woocommerce/module.php:1519
Stack trace:
#0 ../wp-content/plugins/elementor-pro/modules/woocommerce/module.php(1481): ElementorPro\Modules\Woocommerce\Module-&gt;adjust_setting_for_product_renderer()
#1 ../wp-content/plugins/elementor-pro/modules/woocommerce/module.php(1471): ElementorPro\Modules\Woocommerce\Module-&gt;parse_loop_query_args()
#2 ../wp-content/plugins/elementor-pro/modules/woocommerce/module.php(1422): ElementorPro\Modules\Woocommerce\Module-&gt;loop_query()
#3 ../wp-includes/class-wp-hook.php(310): ElementorPro\Modules\Woocommerce\Module-&gt;ElementorPro\Modules\Woocommerce\{closure}()
#4 ../wp-includes/plugin.php(205): WP_Hook-&gt;apply_filters()
#5 ../wp-content/plugins/elementor-pro/modules/query-control/classes/elementor-post-query.php(147): apply_filters()
#6 ../wp-content/plugins/elementor-pro/modules/query-control/classes/elementor-post-query.php(49): ElementorPro\Modules\QueryControl\Classes\Elementor_Post_Query-&gt;get_query_args()
#7 ../wp-content/plugins/elementor-pro/modules/query-control/module.php(959): ElementorPro\Modules\QueryControl\Classes\Elementor_Post_Query-&gt;get_query()
#8 ../wp-content/plugins/elementor-pro/modules/posts/widgets/posts.php(72): ElementorPro\Modules\QueryControl\Module-&gt;get_query()
#9 ../wp-content/plugins/elementor-pro/modules/loop-builder/widgets/base.php(57): ElementorPro\Modules\Posts\Widgets\Posts-&gt;query_posts()
#10 ../wp-content/plugins/elementor-pro/modules/posts/skins/skin-base.php(856): ElementorPro\Modules\LoopBuilder\Widgets\Base-&gt;query_posts()
#11 ../wp-content/plugins/elementor-pro/modules/loop-builder/skins/skin-loop-base.php(89): ElementorPro\Modules\Posts\Skins\Skin_Base-&gt;render()
#12 ../wp-content/plugins/elementor-pro/modules/woocommerce/skins/skin-loop-product.php(36): ElementorPro\Modules\LoopBuilder\Skins\Skin_Loop_Base-&gt;render()
#13 ../wp-content/plugins/elementor/includes/base/skin-base.php(79): ElementorPro\Modules\WooCommerce\Skins\Skin_Loop_Product-&gt;render()
#14 ../wp-content/plugins/elementor/includes/base/widget-base.php(607): Elementor\Skin_Base-&gt;render_by_mode()
#15 ../wp-content/plugins/elementor/core/base/document.php(328): Elementor\Widget_Base-&gt;render_content()
#16 ../wp-content/plugins/elementor/includes/managers/widgets.php(445): Elementor\Core\Base\Document-&gt;render_element()
#17 [internal function]: Elementor\Widgets_Manager-&gt;ajax_render_widget()
#18 ../wp-content/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func()
#19 ../wp-includes/class-wp-hook.php(310): Elementor\Core\Common\Modules\Ajax\Module-&gt;handle_ajax_request()
#20 ../wp-includes/class-wp-hook.php(334): WP_Hook-&gt;apply_filters()
#21 ../wp-includes/plugin.php(517): WP_Hook-&gt;do_action()
#22 ../wp-admin/admin-ajax.php(188): do_action()
#23 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 18 of 182023-09-12 00:08:13 [info] elementor::elementor_updater Started 
2023-09-12 00:08:13 [info] Elementor/Upgrades - _on_each_version Start  
2023-09-12 00:08:13 [info] Elementor/Upgrades - _on_each_version Finished 
2023-09-12 00:08:13 [info] Elementor/Upgrades - _v_3_16_0_container_updates Start  
2023-09-12 00:08:13 [info] Elementor/Upgrades - _v_3_16_0_container_updates Finished 
2023-09-12 00:08:13 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Start  
2023-09-12 00:08:13 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Finished 
2023-09-12 00:08:13 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.15.3',
  'to' => '3.16.0-dev4',
)]
2023-09-12 00:08:13 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.15.3',
  'to' => '3.16.0-dev4',
)]
2023-09-20 09:18:21 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.16.0-dev4',
  'to' => '3.16.3',
)]
2023-09-20 09:20:29 [info] elementor::elementor_updater Started 
2023-09-20 09:20:29 [info] Elementor/Upgrades - _on_each_version Start  
2023-09-20 09:20:30 [info] Elementor/Upgrades - _on_each_version Finished 
2023-09-20 09:20:30 [info] Elementor/Upgrades - _v_3_16_0_container_updates Start  
2023-09-20 09:20:30 [info] Elementor/Upgrades - _v_3_16_0_container_updates Finished 
2023-09-20 09:20:30 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Start  
2023-09-20 09:20:30 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Finished 
2023-09-20 09:20:30 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.16.0-dev4',
  'to' => '3.16.3',
)]

JS: showing 5 of 5JS: 2023-09-12 04:26:39 [error X 3][https://ai-all-in.one/wp-content/plugins/unlimited-elements-for-elementor/provider/core/plugins/unlimited_elements/elementor/assets/uc_front_admin.js?ver=1.5.83:107:76] elementorFrontend is not defined 
JS: 2023-09-14 14:24:15 [error X 2][https://ai-all-in.one/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.16.0-dev4:3:803958] Cannot read properties of undefined (reading &#039;localized&#039;) 
JS: 2023-09-17 07:01:07 [error X 2][https://ai-all-in.one/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.16.0-dev4:3:1108935] Cannot read properties of null (reading &#039;getBoundingClientRect&#039;) 
JS: 2023-09-17 09:22:11 [error X 13673][https://ai-all-in.one/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:14799] Cannot read properties of null (reading &#039;clone&#039;) 
JS: 2023-09-17 09:29:12 [error X 302][https://ai-all-in.one/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:19552] Cannot read properties of null (reading &#039;changestop&#039;) 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	Essential Addons for Elementor: Compatibility not specified
	Premium Addons for Elementor: Compatibility not specified
	Royal Elementor Addons: Compatibility not specified
	Unlimited Elements for Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==
	



````

</details>

**Comment by nicholaszein** [comment]
Hi, @gstarwd,

Thank you for reaching out! 🙏 

### ⛔ After reviewing your report we concluded this is not a bug caused by Elementor. The feature you're referring to is not yet supported.

You are trying to filter a Loop Grid that has a custom query for a specific category (`product_cat-ai-navigation-web`). The <ins>experimental feature</ins> of the Taxonomy Filter currently only works with general queries. It will not work if you **`Include`** or **`Exclude`** specific taxonomy terms, or authors. It also doesn't work on archive templates using the **`Current Query`** Query Source. We have plans to improve this widget's functionality, but for now, if you wish to use it, you need to remove the conditions to include or exclude terms in your Loop Grid widget.

If you think this should be an Elementor feature, please cast your ⬆️ **Upvote** in #23418 and we will consider it in the future if there is enough demand (votes) from other users.

### 🔗 🐞 This issue is a Duplicate of #23614

Which is on the same subject. 

### 🔍 Please, in the future, remember to check if there isn't any thread similar to yours already opened. 

Kind regards

**Comment by gstarwd** [comment]
but i dont set any Include or Exclude specific taxonomy terms, or authors.

**Comment by gstarwd** [comment]
i  really  dont admire your reply .
it runs well in  the preview mode~

**Comment by gstarwd** [comment]
which souce should choose  in the query section?
