### ISSUE TITLE
⛔ 🐞 Bug Report: Border radius does not change for Hover and Active states in the nested Tabs widget

### ISSUE THREAD

**Issue by WilsonCorreia** [elementor/elementor#23884]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

the values applied are not obeyed in the "hover" and "active" states

![tabs_hover](https://github.com/elementor/elementor/assets/32497674/a5d991c7-735f-4eb9-8037-516052bffd9f)
![tabs_ativo](https://github.com/elementor/elementor/assets/32497674/718e1c23-c94d-4e4c-b759-8b9a34afa002)
![tabs_normal](https://github.com/elementor/elementor/assets/32497674/2278490a-6807-406a-8554-f0640f11d21a)

### Steps to reproduce

1) Insert widget "Tabs"
2) In styles, the values entered in the rounding fields, the same for the 3 states (normal, hover and active) are applied correctly only in the "normal" state, in the others they adopt a default value, something close to 20/25 px

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [x] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>Click to reveal</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release 23, Revision 500fcf5 v5.7.23-23
	PHP Version: 8.1.23
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 516M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.3.1
	Site URL: https://m1gp.com.br
	Home URL: https://m1gp.com.br
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: pt-BR
	Timezone: America/Sao_Paulo
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.8.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: pt_BR
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Access Manager
		Version: 6.9.15
		Author: Vasyl Martyniuk <vasyl@vasyltech.com>

	Advanced Custom Fields
		Version: 6.2.1
		Author: WP Engine

	Elementor
		Version: 3.16.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.16.2
		Author: Elementor.com

	ElementsKit Lite
		Version: 2.9.2
		Author: Wpmet

	Envato Elements
		Version: 2.0.12
		Author: Envato

	Microsoft Clarity
		Version: 0.9.3
		Author: Microsoft

	Photo Gallery
		Version: 1.8.18
		Author: Photo Gallery Team

	PixelYourSite
		Version: 9.4.5.1
		Author: PixelYourSite

	Redirection
		Version: 5.3.10
		Author: John Godley

	Site Kit by Google
		Version: 1.109.0
		Author: Google

	TablePress
		Version: 2.1.7
		Author: Tobias Bäthge

	WooCommerce
		Version: 8.1.1
		Author: Automattic

	WPForms Lite
		Version: 1.8.3.1
		Author: WPForms

	WP Mail SMTP
		Version: 3.9.0
		Author: WP Mail SMTP

	Yoast Duplicate Post
		Version: 4.5
		Author: Enrico Battocchi & Team Yoast

	Yoast SEO
		Version: 21.2
		Author: Team Yoast


== Uso dos elementos ==
	
	archive : 4
		archive-posts : 1
		divider : 3
		heading : 4
		image-carousel : 1
		nav-menu : 1
		posts : 1
		share-buttons : 1
	container : 6
		button : 3
		container : 19
		countdown : 1
		divider : 2
		elementskit-heading : 1
		elementskit-icon-box : 4
		heading : 9
		icon-list : 1
		image : 1
		image-carousel : 2
		slides : 2
		text-editor : 19
	footer : 4
		button : 9
		container : 14
		elementskit-back-to-top : 3
		form : 3
		heading : 3
		icon-list : 5
		image : 5
		social-icons : 4
		text-editor : 11
	header : 4
		button : 2
		container : 19
		elementskit-header-search : 1
		image : 19
		image-carousel : 1
		nav-menu : 4
		social-icons : 3
	page : 25
		button : 9
		container : 48
		divider : 10
		elementskit-heading : 10
		elementskit-icon-box : 6
		form : 2
		heading : 30
		icon-box : 2
		icon-list : 1
		image : 12
		image-carousel : 3
		loop-grid : 9
		nav-menu : 1
		posts : 1
		share-buttons : 4
		slides : 1
		theme-archive-title : 1
		video-playlist : 3
	section : 7
		button : 1
		container : 2
		divider : 4
		elementskit-heading : 2
		elementskit-icon-box : 1
		heading : 4
		loop-grid : 2
		nav-menu : 2
		share-buttons : 1
	widget : 0
		button : 3
		divider : 1
		elementskit-heading : 2
		elementskit-icon-box : 2
		heading : 2
		image-carousel : 2
		loop-grid : 4
		share-buttons : 1
		video-playlist : 1
	wp-page : 42
		accordion : 24
		animated-headline : 11
		button : 66
		call-to-action : 4
		container : 219
		countdown : 5
		divider : 88
		elementskit-heading : 27
		elementskit-icon-box : 10
		elementskit-tablepress : 44
		form : 6
		google_maps : 5
		heading : 251
		html : 17
		icon : 9
		icon-box : 33
		icon-list : 68
		image : 19
		image-carousel : 24
		loop-grid : 13
		nav-menu : 2
		nested-tabs : 18
		posts : 2
		price-table : 21
		share-buttons : 21
		slides : 5
		spacer : 74
		text-editor : 80
		theme-archive-title : 2
		video-playlist : 1
	single-post : 7
		button : 1
		container : 28
		divider : 13
		elementskit-icon-box : 4
		heading : 20
		image : 2
		image-carousel : 5
		nav-menu : 3
		post-comments : 3
		post-info : 3
		post-navigation : 3
		posts : 3
		share-buttons : 5
		text-editor : 4
		theme-archive-title : 3
		theme-post-content : 6
		theme-post-excerpt : 2
		theme-post-featured-image : 2
		theme-post-title : 1
	single-page : 4
		button : 2
		container : 8
		divider : 2
		elementskit-heading : 1
		elementskit-icon-box : 2
		heading : 4
		html : 1
		image-carousel : 2
		share-buttons : 1
	search-results : 1
		archive-posts : 1
		heading : 2
		search-form : 1
		theme-archive-title : 1
	loop-item : 8
		container : 7
		heading : 6
		image : 4
		post-info : 2
		spacer : 3
		text-editor : 11
		theme-post-excerpt : 1
		theme-post-featured-image : 5
		theme-post-title : 7


== Configurações ==
	
	cpt_support: post, page
	disable_color_schemes: yes
	disable_typography_schemes: yes
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap


== Recursos ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrações ==
	
	woocommerce: Ativo


== Experimentos do Elementor ==
	Saída DOM otimizada: Ativo por padrão
	Carregamento melhorado de recursos: Ativo por padrão
	Carregamento melhorado de CSS: Ativo por padrão
	Ícones da fonte inline: Inativo por padrão
	Pontos de quebra adicionais personalizados: Ativo por padrão
	admin_menu_rearrangement: Inativo por padrão
	Contêiner Flexível: Ativo
	Atualize a biblioteca Swiper: Ativo por padrão
	Grid Container: Ativo
	Padrão para Novo Construtor de Tema: Ativo por padrão
	Tema Hello - Cabeçalho & Rodapé: Ativo por padrão
	Barra Superior do Editor: Ativo
	Landing Pages: Ativo por padrão
	Elementos aninhados: Ativo
	Imagens com carregamento gradual: Ativo
	Pages Panel: Inativo por padrão
	Global Style Guide: Ativo
	Transições da página: Ativo por padrão
	Atividades Desempenhadas: Ativo por padrão
	Envios do formulário: Ativo por padrão
	Pressão da Rolagem: Ativo por padrão
	Menu: Inativo por padrão
	Taxonomy Filter: Ativo


== Registo ==
	
Log: showing 20 of 272023-08-11 17:46:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.15.1',
  'to' => '3.15.2',
)]
2023-08-11 17:50:34 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.15.0',
  'to' => '3.15.1',
)]
2023-08-11 17:50:34 [info] elementor-pro::elementor_pro_updater Started 
2023-08-11 17:50:34 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-08-11 17:50:34 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-08-11 17:50:34 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.15.0',
  'to' => '3.15.1',
)]
2023-09-21 18:01:11 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.15.2',
  'to' => '3.16.4',
)]
2023-09-21 18:01:11 [info] elementor::elementor_updater Started 
2023-09-21 18:01:11 [info] Elementor/Upgrades - _on_each_version Start  
2023-09-21 18:01:13 [info] Elementor/Upgrades - _on_each_version Finished 
2023-09-21 18:01:13 [info] Elementor/Upgrades - _v_3_16_0_container_updates Start  
2023-09-21 18:01:15 [info] Elementor/Upgrades - _v_3_16_0_container_updates Finished 
2023-09-21 18:01:15 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Start  
2023-09-21 18:01:15 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Finished 
2023-09-21 18:01:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.15.2',
  'to' => '3.16.4',
)]
2023-09-21 18:06:22 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.15.1',
  'to' => '3.16.2',
)]
2023-09-21 18:06:22 [info] elementor-pro::elementor_pro_updater Started 
2023-09-21 18:06:22 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-09-21 18:06:22 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-09-21 18:06:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.15.1',
  'to' => '3.16.2',
)]

PHP: showing 9 of 9PHP: 2023-08-14 19:28:22 [warning X 144][../wp-content/plugins/elementor-pro/modules/dynamic-tags/tags/site-logo.php::32] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-25 19:28:13 [warning X 24][../wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-25 19:36:21 [warning X 1][../wp-content/plugins/elementor-pro/modules/loop-filter/module.php::133] Undefined array key "post_type" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-27 14:05:39 [notice X 21044][../wp-content/plugins/elementor-pro/modules/loop-builder/files/css/loop.php::58] Creation of dynamic property ElementorPro\Modules\LoopBuilder\Files\Css\Loop::$post_id is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-27 16:00:52 [notice X 21][../wp-content/plugins/elementor-pro/modules/screenshots/module.php::33] Function utf8_decode() is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-27 16:01:16 [warning X 1][../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key "condition_type" [array (
  'trace' => '
#0: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(83): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: ../wp-content/plugins/elementor/data/base/endpoint.php(166): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> update_item()
#3: ../wp-content/plugins/elementor/data/base/endpoint.php(307): Elementor\Data\Base\Endpoint -> base_callback()
#4: ../wp-includes/rest-api/class-wp-rest-server.php(1188): Elementor\Data\Base\Endpoint -> Elementor\Data\Base\{closure}()
',
)]
PHP: 2023-08-27 18:55:35 [notice X 11][../wp-content/plugins/elementor-pro/modules/loop-builder/files/css/loop.php::58] Creation of dynamic property ElementorPro\Modules\LoopBuilder\Files\Css\Loop::$post_id is deprecated [array (
  'trace' => '
#0: ../wp-content/plugins/elementor-pro/modules/loop-builder/files/css/loop.php(58): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Modules\LoopBuilder\Files\Css\Loop -> __construct()
#2: ../wp-content/plugins/elementor/core/files/manager.php(45): ReflectionClass -> newInstanceArgs()
#3: ../wp-content/plugins/elementor/core/files/base.php(74): Elementor\Core\Files\Manager -> get()
#4: ../wp-content/plugins/elementor-pro/modules/loop-builder/documents/loop.php(250): Elementor\Core\Files\Base :: create()
',
)]
PHP: 2023-09-01 18:08:21 [error X 6][../wp-content/plugins/elementor-pro/modules/screenshots/module.php::229] Uncaught WpOrg\Requests\Exception\Http\Status403: 403 Forbidden in ../wp-content/plugins/elementor-pro/modules/screenshots/module.php:229
Stack trace:
#0 ../wp-content/plugins/elementor-pro/modules/screenshots/module.php(264): ElementorPro\Modules\Screenshots\Module->is_screenshot_proxy_mode(Array)
#1 ../wp-content/plugins/elementor/core/base/module.php(85): ElementorPro\Modules\Screenshots\Module->__construct()
#2 ../wp-content/plugins/elementor-pro/core/modules-manager.php(89): Elementor\Core\Base\Module::instance()
#3 ../wp-content/plugins/elementor-pro/plugin.php(369): ElementorPro\Core\Modules_Manager->__construct()
#4 ../wp-includes/class-wp-hook.php(310): ElementorPro\Plugin->on_elementor_init('')
#5 ../wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters('', Array)
#6 ../wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#7 ../wp-content/plugins/elementor/includes/plugin.php(658): do_action('elementor/init')
#8 ../wp-includes/class-wp-hook.php(310): Elementor\Plugin->init('')
#9 ../wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters(NULL, Array)
#10 ../wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#11 ../wp-settings.php(632): do_action('init')
#12 ../wp-config.php(97): require_once('/home1/m1gpco36...')
#13 ../wp-load.php(50): require_once('/home1/m1gpco36...')
#14 ../wp-blog-header.php(13): require_once('/home1/m1gpco36...')
#15 ../index.php(17): require('/home1/m1gpco36...')
#16 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-21 11:28:43 [error X 1][../wp-content/plugins/elementor/includes/template-library/sources/local.php::1113] Uncaught TypeError: Elementor\TemplateLibrary\Source_Local::on_save_post(): Argument #2 ($post) must be of type WP_Post, null given, called in ../wp-includes/class-wp-hook.php on line 312 and defined in ../wp-content/plugins/elementor/includes/template-library/sources/local.php:1113
Stack trace:
#0 ../wp-includes/class-wp-hook.php(312): Elementor\TemplateLibrary\Source_Local->on_save_post(8363, NULL)
#1 ../wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters(NULL, Array)
#2 ../wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#3 ../wp-includes/post.php(4751): do_action('save_post', 8363, NULL, true)
#4 ../wp-includes/post.php(4853): wp_insert_post(Array, false, true)
#5 ../wp-content/plugins/elementor/includes/db.php(235): wp_update_post(Array)
#6 ../wp-content/plugins/elementor/core/base/document.php(1272): Elementor\DB->save_plain_text(8363)
#7 ../wp-content/plugins/elementor/core/base/document.php(753): Elementor\Core\Base\Document->save_elements(Array)
#8 ../wp-content/plugins/elementor/core/documents-manager.php(545): Elementor\Core\Base\Document->save(Array)
#9 [internal function]: Elementor\Core\Documents_Manager->ajax_save(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#10 ../wp-content/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#11 ../wp-includes/class-wp-hook.php(310): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#12 ../wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters('', Array)
#13 ../wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#14 ../wp-admin/admin-ajax.php(188): do_action('wp_ajax_element...')
#15 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 6 of 6JS: 2023-08-22 14:13:15 [error X 2][https://m1gp.com.br/wp-content/plugins/elementor/assets/js/common-modules.min.js?ver=3.15.2:2:55595] Model.isValidChild() should be implemented, please provide 'isValidChild' functionality. 
JS: 2023-08-26 13:47:00 [error X 1][https://m1gp.com.br/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.15.2:3:290587] Cannot read properties of undefined (reading 'css') 
JS: 2023-08-26 15:03:40 [error X 1][https://m1gp.com.br/wp-content/plugins/elementor/assets/js/web-cli.min.js?ver=3.15.2:3:107466] Routes: `panel/editor/actions` not found. 
JS: 2023-08-27 19:42:26 [error X 1][https://m1gp.com.br/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.15.2:3:690230] this.model.isValidChild is not a function 
JS: 2023-09-15 20:55:57 [error X 1][https://m1gp.com.br/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.15.2:3:642490] Cannot read properties of undefined (reading 'isDesignable') 
JS: 2023-09-21 14:18:23 [error X 2][https://m1gp.com.br/wp-content/plugins/elementor/assets/js/7fada1a61d72da6d46ab.bundle.min.js:2:7826] Cannot read properties of null (reading 'dataset') 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibilidade não especificada

== Elementor Pro - Compatibility Tag ==
	

				

````

</details>

**Comment by nicholaszein** [comment]
Hi, @WilsonCorreia,

Thank you for reaching out! 🙏 

### ⛔ After reviewing your report we concluded this is not a bug caused by Elementor. The feature you're referring to is not supported.

As you can see, there is a **separator** between the Border Radius options and the options above it. This means that below that separator the settings are applied globally to that element, and are not context-aware. In other words, you can't change the Border Radius for different states. They apply to all states, "Normal", "Hover", and "Active".

![image](https://github.com/elementor/elementor/assets/113993460/2103f8d9-94a3-4b48-b44f-60a58fbfa506)


If you think this should be an Elementor feature, please submit a new [🚀 Feature Request](https://github.com/orgs/elementor/discussions/new?category=feature-request), and we will consider it in the future if there is enough demand (votes) from other users.

Kind regards
