### ISSUE TITLE
Tel Input Validation Error in Firefox

### ISSUE THREAD

**Issue by buckmanhands** [elementor/elementor#23894]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When using the Tel Input to gather a phone number and you use the Browser validation mode to validate the telephone number, the `pattern` attribute which contains a regex the browser should use to validate the phone number throws an error in Firefox. So if a person puts in a phone number such as (123) 456-7890, which should not be valid according to the regex in the pattern attribute, they are able to submit the form. It is then tossed back after going server side that the phone number is invalid. 

### Steps to reproduce

Prerequesite, use Firefox to check

1. Create a form with a Tel input and make it required.

2. Submit the form with characters that are not allowed according to your regex pattern such as `( ) a x z`

3. Check for the error in your console that appears on blur out of the Tel field

4. Submit the form, it will be allowed to submit.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: (Ubuntu) v8.0.28
	PHP Version: 8.1.17
	PHP Memory Limit: 512M
	PHP Max Input Vars: 4000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.3.1
	Site URL: https://mothersfordemocracy.org
	Home URL: https://mothersfordemocracy.org
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: -5
	Admin Email: rudy@ethos7.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.8.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/117.0

== Active Plugins ==
	Advanced Form Integration Professional
		Version: 1.73.1
		Author: nasirahmed

	Code Snippets
		Version: 3.5.0
		Author: Code Snippets Pro

	Disable Gutenberg
		Version: 3.0
		Author: Jeff Starr

	Elementor
		Version: 3.16.4
		Author: Elementor.com

	Elementor Mailcoach Integration
		Version: 1.0.0
		Author: Rudy Preston

	Elementor Pro
		Version: 3.16.2
		Author: Elementor.com

	Elementor Spam Breaker
		Version: 1.0.0
		Author: Rudy Preston

	Link Library
		Version: 7.5.9
		Author: Yannick Lefebvre

	Open External Links in a New Window
		Version: 1.44
		Author: WebFactory Ltd

	Post SMTP
		Version: 2.6.0
		Author: Post SMTP

	Premium Addons for Elementor
		Version: 4.10.9
		Author: Leap13

	Premium Addons PRO
		Version: 2.9.6
		Author: Leap13

	Printful Integration for WooCommerce
		Version: 2.2.4
		Author: Printful

	Print Invoice & Delivery Notes for WooCommerce
		Version: 4.7.3
		Author: Tyche Softwares

	Real Custom Post Order
		Version: 1.3.64
		Author: devowl.io

	The SEO Framework
		Version: 4.2.8
		Author: The SEO Framework Team

	The SEO Framework - Extension Manager
		Version: 2.6.2
		Author: The SEO Framework Team

	Variation Swatches for WooCommerce
		Version: 2.0.26
		Author: Emran Ahmed

	WooCommerce
		Version: 8.1.1
		Author: Automattic

	WooCommerce - ShipStation Integration
		Version: 4.3.9
		Author: WooCommerce

	WooCommerce Stripe Gateway
		Version: 7.6.0
		Author: WooCommerce

	WooCommerce Tiered Price Table (Premium)
		Version: 3.6.2
		Author: bycrik

	Wordfence Security
		Version: 7.10.3
		Author: Wordfence

== Elements Usage ==
	
	container : 10
		blockquote : 1
		button : 3
		container : 17
		countdown : 1
		divider : 2
		form : 1
		heading : 10
		image : 2
		mega-menu : 1
		premium-addon-video-box : 3
		text-editor : 3
		theme-site-logo : 1
		woocommerce-products : 1
	footer : 1
		button : 8
		container : 16
		divider : 2
		heading : 2
		image : 4
		loop-carousel : 1
		nav-menu : 1
		social-icons : 1
		spacer : 1
		text-editor : 10
	header : 1
		button : 3
		container : 12
		icon-list : 3
		mega-menu : 1
		social-icons : 1
		theme-site-logo : 1
		woocommerce-menu-cart : 1
	page : 1
		container : 1
		countdown : 1
		heading : 1
		image : 1
	widget : 0
		social-icons : 1
	wp-page : 12
		animated-headline : 3
		blockquote : 4
		button : 6
		container : 71
		divider : 13
		form : 5
		heading : 71
		html : 1
		icon-list : 2
		image : 39
		nested-accordion : 1
		premium-addon-button : 1
		premium-addon-video-box : 7
		premium-icon-list : 3
		text-editor : 38
		video : 2
	single-page : 1
		container : 1
		theme-post-content : 1
		theme-post-title : 1
	loop-item : 1
		container : 1
		theme-post-featured-image : 1
		woocommerce-product-title : 1

== Settings ==
	
	cpt_support: post, page
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap

== Features ==
	Custom Fonts: 0
	Custom Icons: 2

== Integrations ==
	
	recaptcha: Active
	woocommerce: Active

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active by default
	Grid Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Editor Top Bar: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Active
	Lazy Load Background Images: Inactive by default
	Global Style Guide: Inactive by default
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Menu: Active
	Taxonomy Filter: Inactive by default

== Log ==
	
Log: showing 14 of 142023-09-15 15:48:41 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Start  
2023-09-15 15:48:41 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Finished 
2023-09-15 15:48:41 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.15.3',
  'to' => '3.16.3',
)]
2023-09-22 15:31:10 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.16.3',
  'to' => '3.16.4',
)]
2023-09-22 15:31:14 [info] elementor::elementor_updater Started 
2023-09-22 15:31:14 [info] Elementor/Upgrades - _on_each_version Start  
2023-09-22 15:31:15 [info] Elementor/Upgrades - _on_each_version Finished 
2023-09-22 15:31:15 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Start  
2023-09-22 15:31:15 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Finished 
2023-09-22 15:31:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.16.3',
  'to' => '3.16.4',
)]
2023-09-22 15:31:22 [info] elementor-pro::elementor_pro_updater Started 
2023-09-22 15:31:22 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-09-22 15:31:22 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-09-22 15:31:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.16.1',
  'to' => '3.16.2',
)]

PHP: showing 16 of 16PHP: 2023-09-15 15:50:26 [notice X 131][/home/dh_837g4y/mothersfordemocracy.org/wp-content/plugins/elementor/includes/base/controls-stack.php::228] hexdec(): Passing null to parameter #1 ($hex_string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-16 11:19:03 [warning X 1][/home/dh_837g4y/mothersfordemocracy.org/wp-content/plugins/elementor/includes/db.php::267] foreach() argument must be of type array|object, null given [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-16 12:00:00 [warning X 10][/home/dh_837g4y/mothersfordemocracy.org/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-16 12:01:14 [warning X 241][/home/dh_837g4y/mothersfordemocracy.org/wp-content/plugins/elementor/includes/db.php::267] foreach() argument must be of type array|object, string given [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-19 22:05:13 [warning X 2][/home/dh_837g4y/mothersfordemocracy.org/wp-content/plugins/elementor/includes/managers/image.php::113] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-22 15:32:21 [warning X 1][/home/dh_837g4y/mothersfordemocracy.org/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key "condition_type" [array (
  'trace' => '
#0: /home/dh_837g4y/mothersfordemocracy.org/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /home/dh_837g4y/mothersfordemocracy.org/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /home/dh_837g4y/mothersfordemocracy.org/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /home/dh_837g4y/mothersfordemocracy.org/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2023-09-23 13:11:47 [warning X 11][/home/dh_837g4y/mothersfordemocracy.org/wp-content/plugins/elementor-spam-breaker/form-actions/spam-breaker.php::159] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-23 15:56:36 [error X 1][/home/dh_837g4y/mothersfordemocracy.org/wp-content/plugins/elementor-spam-breaker/elementor-spam-breaker-action.php::30] Uncaught Error: Class "Spam_Breaker_Action_After_Submit" not found in /home/dh_837g4y/mothersfordemocracy.org/wp-content/plugins/elementor-spam-breaker/elementor-spam-breaker-action.php:30
Stack trace:
#0 /home/dh_837g4y/mothersfordemocracy.org/wp-includes/class-wp-hook.php(310): add_new_spam_breaker_action(Object(ElementorPro\Modules\Forms\Registrars\Form_Actions_Registrar))
#1 /home/dh_837g4y/mothersfordemocracy.org/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters(NULL, Array)
#2 /home/dh_837g4y/mothersfordemocracy.org/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#3 /home/dh_837g4y/mothersfordemocracy.org/wp-content/plugins/elementor-pro/modules/forms/registrars/form-actions-registrar.php(74): do_action('elementor_pro/f...', Object(ElementorPro\Modules\Forms\Registrars\Form_Actions_Registrar))
#4 /home/dh_837g4y/mothersfordemocracy.org/wp-content/plugins/elementor-pro/modules/forms/registrars/form-actions-registrar.php(26): ElementorPro\Modules\Forms\Registrars\Form_Actions_Registrar->init()
#5 /home/dh_837g4y/mothersfordemocracy.org/wp-content/plugins/elementor-pro/modules/forms/module.php(181): ElementorPro\Modules\Forms\Registrars\Form_Actions_Registrar->__construct()
#6 /home/dh_837g4y/mothersfordemocracy.org/wp-content/plugins/elementor/core/base/module.php(85): ElementorPro\Modules\Forms\Module->__construct()
#7 /home/dh_837g4y/mothersfordemocracy.org/wp-content/plugins/elementor-pro/core/modules-manager.php(90): Elementor\Core\Base\Module::instance()
#8 /home/dh_837g4y/mothersfordemocracy.org/wp-content/plugins/elementor-pro/plugin.php(369): ElementorPro\Core\Modules_Manager->__construct()
#9 /home/dh_837g4y/mothersfordemocracy.org/wp-includes/class-wp-hook.php(310): ElementorPro\Plugin->on_elementor_init('')
#10 /home/dh_837g4y/mothersfordemocracy.org/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters(NULL, Array)
#11 /home/dh_837g4y/mothersfordemocracy.org/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#12 /home/dh_837g4y/mothersfordemocracy.org/wp-content/plugins/elementor/includes/plugin.php(658): do_action('elementor/init')
#13 /home/dh_837g4y/mothersfordemocracy.org/wp-includes/class-wp-hook.php(310): Elementor\Plugin->init('')
#14 /home/dh_837g4y/mothersfordemocracy.org/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters(NULL, Array)
#15 /home/dh_837g4y/mothersfordemocracy.org/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#16 /home/dh_837g4y/mothersfordemocracy.org/wp-settings.php(632): do_action('init')
#17 /home/dh_837g4y/mothersfordemocracy.org/wp-config.php(108): require_once('/home/dh_837g4y...')
#18 /home/dh_837g4y/mothersfordemocracy.org/wp-load.php(50): require_once('/home/dh_837g4y...')
#19 /home/dh_837g4y/mothersfordemocracy.org/wp-blog-header.php(13): require_once('/home/dh_837g4y...')
#20 /home/dh_837g4y/mothersfordemocracy.org/index.php(17): require('/home/dh_837g4y...')
#21 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-23 15:56:52 [error X 2][/home/dh_837g4y/mothersfordemocracy.org/wp-content/plugins/elementor-mailcoach-integration/elementor-mailcoach-integration-action.php::30] Uncaught Error: Class "Mailcoach_Action_After_Submit" not found in /home/dh_837g4y/mothersfordemocracy.org/wp-content/plugins/elementor-mailcoach-integration/elementor-mailcoach-integration-action.php:30
Stack trace:
#0 /home/dh_837g4y/mothersfordemocracy.org/wp-includes/class-wp-hook.php(310): add_new_mailcoach_form_action(Object(ElementorPro\Modules\Forms\Registrars\Form_Actions_Registrar))
#1 /home/dh_837g4y/mothersfordemocracy.org/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters(NULL, Array)
#2 /home/dh_837g4y/mothersfordemocracy.org/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#3 /home/dh_837g4y/mothersfordemocracy.org/wp-content/plugins/elementor-pro/modules/forms/registrars/form-actions-registrar.php(74): do_action('elementor_pro/f...', Object(ElementorPro\Modules\Forms\Registrars\Form_Actions_Registrar))
#4 /home/dh_837g4y/mothersfordemocracy.org/wp-content/plugins/elementor-pro/modules/forms/registrars/form-actions-registrar.php(26): ElementorPro\Modules\Forms\Registrars\Form_Actions_Registrar->init()
#5 /home/dh_837g4y/mothersfordemocracy.org/wp-content/plugins/elementor-pro/modules/forms/module.php(181): ElementorPro\Modules\Forms\Registrars\Form_Actions_Registrar->__construct()
#6 /home/dh_837g4y/mothersfordemocracy.org/wp-content/plugins/elementor/core/base/module.php(85): ElementorPro\Modules\Forms\Module->__construct()
#7 /home/dh_837g4y/mothersfordemocracy.org/wp-content/plugins/elementor-pro/core/modules-manager.php(90): Elementor\Core\Base\Module::instance()
#8 /home/dh_837g4y/mothersfordemocracy.org/wp-content/plugins/elementor-pro/plugin.php(369): ElementorPro\Core\Modules_Manager->__construct()
#9 /home/dh_837g4y/mothersfordemocracy.org/wp-includes/class-wp-hook.php(310): ElementorPro\Plugin->on_elementor_init('')
#10 /home/dh_837g4y/mothersfordemocracy.org/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters(NULL, Array)
#11 /home/dh_837g4y/mothersfordemocracy.org/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#12 /home/dh_837g4y/mothersfordemocracy.org/wp-content/plugins/elementor/includes/plugin.php(658): do_action('elementor/init')
#13 /home/dh_837g4y/mothersfordemocracy.org/wp-includes/class-wp-hook.php(310): Elementor\Plugin->init('')
#14 /home/dh_837g4y/mothersfordemocracy.org/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters(NULL, Array)
#15 /home/dh_837g4y/mothersfordemocracy.org/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#16 /home/dh_837g4y/mothersfordemocracy.org/wp-settings.php(632): do_action('init')
#17 /home/dh_837g4y/mothersfordemocracy.org/wp-config.php(108): require_once('/home/dh_837g4y...')
#18 /home/dh_837g4y/mothersfordemocracy.org/wp-load.php(50): require_once('/home/dh_837g4y...')
#19 /home/dh_837g4y/mothersfordemocracy.org/wp-admin/admin.php(34): require_once('/home/dh_837g4y...')
#20 /home/dh_837g4y/mothersfordemocracy.org/wp-admin/post.php(12): require_once('/home/dh_837g4y...')
#21 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-23 16:01:35 [error X 5][/home/dh_837g4y/mothersfordemocracy.org/wp-content/plugins/elementor-mailcoach-integration/elementor-mailcoach-integration-action.php::30] Uncaught Error: Class "Mailcoach_Action_After_Submit" not found in /home/dh_837g4y/mothersfordemocracy.org/wp-content/plugins/elementor-mailcoach-integration/elementor-mailcoach-integration-action.php:30
Stack trace:
#0 /home/dh_837g4y/mothersfordemocracy.org/wp-includes/class-wp-hook.php(310): add_new_mailcoach_form_action(Object(ElementorPro\Modules\Forms\Registrars\Form_Actions_Registrar))
#1 /home/dh_837g4y/mothersfordemocracy.org/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters(NULL, Array)
#2 /home/dh_837g4y/mothersfordemocracy.org/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#3 /home/dh_837g4y/mothersfordemocracy.org/wp-content/plugins/elementor-pro/modules/forms/registrars/form-actions-registrar.php(74): do_action('elementor_pro/f...', Object(ElementorPro\Modules\Forms\Registrars\Form_Actions_Registrar))
#4 /home/dh_837g4y/mothersfordemocracy.org/wp-content/plugins/elementor-pro/modules/forms/registrars/form-actions-registrar.php(26): ElementorPro\Modules\Forms\Registrars\Form_Actions_Registrar->init()
#5 /home/dh_837g4y/mothersfordemocracy.org/wp-content/plugins/elementor-pro/modules/forms/module.php(181): ElementorPro\Modules\Forms\Registrars\Form_Actions_Registrar->__construct()
#6 /home/dh_837g4y/mothersfordemocracy.org/wp-content/plugins/elementor/core/base/module.php(85): ElementorPro\Modules\Forms\Module->__construct()
#7 /home/dh_837g4y/mothersfordemocracy.org/wp-content/plugins/elementor-pro/core/modules-manager.php(90): Elementor\Core\Base\Module::instance()
#8 /home/dh_837g4y/mothersfordemocracy.org/wp-content/plugins/elementor-pro/plugin.php(369): ElementorPro\Core\Modules_Manager->__construct()
#9 /home/dh_837g4y/mothersfordemocracy.org/wp-includes/class-wp-hook.php(310): ElementorPro\Plugin->on_elementor_init('')
#10 /home/dh_837g4y/mothersfordemocracy.org/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters(NULL, Array)
#11 /home/dh_837g4y/mothersfordemocracy.org/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#12 /home/dh_837g4y/mothersfordemocracy.org/wp-content/plugins/elementor/includes/plugin.php(658): do_action('elementor/init')
#13 /home/dh_837g4y/mothersfordemocracy.org/wp-includes/class-wp-hook.php(310): Elementor\Plugin->init('')
#14 /home/dh_837g4y/mothersfordemocracy.org/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters(NULL, Array)
#15 /home/dh_837g4y/mothersfordemocracy.org/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#16 /home/dh_837g4y/mothersfordemocracy.org/wp-settings.php(632): do_action('init')
#17 /home/dh_837g4y/mothersfordemocracy.org/wp-config.php(108): require_once('/home/dh_837g4y...')
#18 /home/dh_837g4y/mothersfordemocracy.org/wp-load.php(50): require_once('/home/dh_837g4y...')
#19 /home/dh_837g4y/mothersfordemocracy.org/wp-blog-header.php(13): require_once('/home/dh_837g4y...')
#20 /home/dh_837g4y/mothersfordemocracy.org/index.php(17): require('/home/dh_837g4y...')
#21 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-23 16:43:35 [error X 2][/home/dh_837g4y/mothersfordemocracy.org/wp-content/plugins/elementor-spam-breaker/form-actions/spam-breaker.php::281] syntax error, unexpected token "public" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-23 16:51:01 [error X 1][/home/dh_837g4y/mothersfordemocracy.org/wp-content/plugins/elementor-spam-breaker/form-actions/spam-breaker.php::265] Uncaught Error: Call to undefined method Spam_Breaker_Action_After_Submit::_unstable_get_super_global_value() in /home/dh_837g4y/mothersfordemocracy.org/wp-content/plugins/elementor-spam-breaker/form-actions/spam-breaker.php:265
Stack trace:
#0 /home/dh_837g4y/mothersfordemocracy.org/wp-content/plugins/elementor-spam-breaker/form-actions/spam-breaker.php(244): Spam_Breaker_Action_After_Submit::get_client_ip()
#1 /home/dh_837g4y/mothersfordemocracy.org/wp-content/plugins/elementor-spam-breaker/form-actions/spam-breaker.php(134): Spam_Breaker_Action_After_Submit->get_form_meta()
#2 /home/dh_837g4y/mothersfordemocracy.org/wp-content/plugins/elementor-pro/modules/forms/classes/ajax-handler.php(159): Spam_Breaker_Action_After_Submit->run(Object(ElementorPro\Modules\Forms\Classes\Form_Record), Object(ElementorPro\Modules\Forms\Classes\Ajax_Handler))
#3 /home/dh_837g4y/mothersfordemocracy.org/wp-includes/class-wp-hook.php(310): ElementorPro\Modules\Forms\Classes\Ajax_Handler->ajax_send_form('')
#4 /home/dh_837g4y/mothersfordemocracy.org/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters('', Array)
#5 /home/dh_837g4y/mothersfordemocracy.org/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /home/dh_837g4y/mothersfordemocracy.org/wp-admin/admin-ajax.php(188): do_action('wp_ajax_element...')
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-23 18:20:04 [warning X 1][/home/dh_837g4y/mothersfordemocracy.org/wp-content/plugins/elementor-spam-breaker/form-actions/spam-breaker.php::127] Undefined array key "spambreaker" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-23 19:36:25 [error X 5][/home/dh_837g4y/mothersfordemocracy.org/wp-content/plugins/elementor-mailcoach-integration/form-actions/mailcoach.php::115] syntax error, unexpected identifier "form_settings", expecting ")" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-23 23:09:25 [warning X 5][/home/dh_837g4y/mothersfordemocracy.org/wp-content/plugins/elementor-mailcoach-integration/form-actions/mailcoach.php::196] Undefined variable $spammer [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-24 00:35:20 [warning X 1][/home/dh_837g4y/mothersfordemocracy.org/wp-content/plugins/elementor-spam-breaker/form-actions/spam-breaker.php::128] Undefined array key "breaker" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 12 of 12JS: 2023-09-15 20:54:53 [error X 61][https://mothersfordemocracy.org/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.16.3:2:33764] e is null 
JS: 2023-09-16 03:34:41 [error X 3][https://mothersfordemocracy.org/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.16.3:2:33772] null is not an object (evaluating 'e.getAttribute') 
JS: 2023-09-16 16:17:59 [error X 2][https://mothersfordemocracy.org/wp-content/plugins/premium-addons-for-elementor/assets/editor/js/premium-cross-cp.js?ver=4.10.7:13:21] b is null 
JS: 2023-09-16 16:56:47 [error X 5][https://mothersfordemocracy.org/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.16.3:2:30893] elementor.settings.page is undefined 
JS: 2023-09-16 17:02:03 [error X 4][https://mothersfordemocracy.org/wp-content/plugins/wpsyncsheets-elementor/assets/js/wpssle-custom-elementor.js?ver=1.3:49:36] can't convert undefined to object 
JS: 2023-09-17 18:02:42 [error X 17][https://mothersfordemocracy.org/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.16.3:2:33773] Cannot read properties of null (reading 'getAttribute') 
JS: 2023-09-20 01:27:07 [error X 4841][https://mothersfordemocracy.org/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:14757] this._lastColor is null 
JS: 2023-09-20 01:27:23 [error X 53][https://mothersfordemocracy.org/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:19533] this._eventListener is null 
JS: 2023-09-20 04:03:41 [error X 1][https://mothersfordemocracy.org/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.16.3:3:601252] elementor.documents.getCurrent() is null 
JS: 2023-09-20 05:00:14 [error X 1][https://mothersfordemocracy.org/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.16.3:3:1108873] V is null 
JS: 2023-09-20 20:04:00 [error X 2][https://mothersfordemocracy.org/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.16.3:3:804243] this.store.find(...) is undefined 
JS: 2023-09-20 22:32:56 [error X 2][https://mothersfordemocracy.org/wp-content/plugins/elementor/assets/js/4fdaa70e951ad90db2f2.bundle.min.js:2:7765] t.target.closest(...) is null 

== Elementor - Compatibility Tag ==
	
	Elementor Mailcoach Integration: Incompatible
	Elementor Pro: Compatible
	Elementor Spam Breaker: Incompatible
	Premium Addons for Elementor: Compatible
	Premium Addons PRO: Compatible

== Elementor Pro - Compatibility Tag ==
	
	Elementor Mailcoach Integration: Incompatible
	Elementor Spam Breaker: Incompatible
	Premium Addons for Elementor: Compatible
	Premium Addons PRO: Compatible

**Comment by nicholaszein** [comment]
Hello @buckmanhands ! 

Thank you for submitting your issue! 🙏 

Please allow us some time to investigate it, and get back to you with our findings. 🧐 

Best regards
