### ISSUE TITLE
elementorFrontend.utils.lightbox.showModal is not a function

### ISSUE THREAD

**Issue by jasper-totalstudio** [elementor/elementor#23902]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

In a recent update around version 3.14.0, the function ElementorFrontend.utils.lightbox.showModal() seems to have become unavailable in JavaScript. This function was utilized in a custom script on our website to open a video in a lightbox when a specific element is clicked. Below is the snippet of the custom code used:

`$('.medipro_video_2').on('click',function( event ){
	event.preventDefault();
	elementorFrontend.utils.lightbox.showModal({
		url: 'https://www.youtube.com/embed/kB6dWoMlVMI?feature=oembed&rel=0&controls=0&showinfo=0&mute=0&wmode=opaque',
		videoAspectRatio: '169',
		type: 'video',
	});
});
`

With the absence of ElementorFrontend.utils.lightbox.showModal() function, the custom script fails to execute as intended, thus affecting the functionality of opening a video in a lightbox on our website. It's crucial to have this function restored or an alternative solution provided to maintain the website's functionality.

Any assistance or guidance on how to resolve this issue would be greatly appreciated.

### Steps to reproduce

in the console 

elementorFrontend.utils.lightbox.showModal

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Ubuntu 22.04 v10.6.12
	PHP Version: 8.0.30
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.3.1
	Site URL: https://www.prostop.nl
	Home URL: https://www.prostop.nl
	WP Multisite: No
	Max Upload Size: 2 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: nl-NL
	Timezone: Europe/Amsterdam
	Admin Email: michiel@prostop.nl
	Debug Mode: Inactive

== Theme ==
	Name: Prostop Nederland
	Version: 2.0
	Author: M. van Mameren
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: nl_NL
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Automatic Updates
		Version: 1.0.2
		Author: pento

	Contact Form 7
		Version: 5.8
		Author: Takayuki Miyoshi

	Cookiebeleid
		Version: 1.0.
		Author: Jasper Cobussen

	Elementor
		Version: 3.14.0
		Author: Elementor.com

	Lazy Load - Optimize Images
		Version: 2.3.6
		Author: WP Rocket

	Motivatietest
		Version: 1.0
		Author: Prostop - De stoppen met roken specialist

	Prostop - Online Boeken
		Version: 0.0.3
		Author: M.C.H. van Mameren

	Redirection
		Version: 5.3.10
		Author: John Godley

	Salus Service Contactform 7 extensie
		Version: 2.2.0
		Author: M.C.H. van Mameren

	Salus Service Online - Vestigingen en Medewerkers
		Version: 0.0.1
		Author: M.C.H. van Mameren

	Salus Service Tracking
		Version: 1.0.0
		Author: M.C.H. van Mameren

	SMS Coach
		Version: 1.0.0
		Author: M.C.H. van Mameren

	Web Stories
		Version: 1.34.0
		Author: Google

	Yoast SEO
		Version: 21.1
		Author: Team Yoast

== Elementor experimenten ==
	Geoptimaliseerde DOM-uitvoer: Standaard inactief
	Verbeterd laden van assets: Standaard inactief
	Verbeterd laden van CSS: Standaard inactief
	Pictogrammen inline lettertype: Standaard inactief
	Accessibility Improvements: Standaard actief
	Extra aangepaste onderbrekingspunten: Standaard actief
	admin_menu_rearrangement: Standaard inactief
	Flexbox container: Standaard inactief
	Upgrade Swiper bibliotheek: Standaard inactief
	Raster container: Standaard inactief
	Editor top balk: Standaard inactief
	Landingspagina's: Standaard actief
	Geneste elementen: Standaard inactief
	Nested Accordion: Standaard inactief
	Lazy-load achtergrondafbeeldingen: Standaard inactief
	Globale stijlgids: Standaard inactief

== Log ==
	
PHP: showing 2 of 2PHP: 2021-11-24 11:16:02 [error X 3][/data/www/prostop_nl/website/htdocs/wp-content/plugins/elementor/core/modules-manager.php::53] Uncaught Error: Class "Elementor\Modules\ElementsColorPicker\Module" not found in /data/www/prostop_nl/website/htdocs/wp-content/plugins/elementor/core/modules-manager.php:53
Stack trace:
#0 /data/www/prostop_nl/website/htdocs/wp-content/plugins/elementor/includes/plugin.php(755): Elementor\Core\Modules_Manager->__construct()
#1 /data/www/prostop_nl/website/htdocs/wp-content/plugins/elementor/includes/plugin.php(671): Elementor\Plugin->init_components()
#2 /data/www/prostop_nl/website/htdocs/wp-includes/class-wp-hook.php(292): Elementor\Plugin->init()
#3 /data/www/prostop_nl/website/htdocs/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters()
#4 /data/www/prostop_nl/website/htdocs/wp-includes/plugin.php(484): WP_Hook->do_action()
#5 /data/www/prostop_nl/website/htdocs/wp-settings.php(560): do_action()
#6 /data/www/prostop_nl/website/htdocs/wp-config.php(74): require_once('...')
#7 /data/www/prostop_nl/website/htdocs/wp-load.php(37): require_once('...')
#8 /data/www/prostop_nl/website/htdocs/wp-blog-header.php(13): require_once('...')
#9 /data/www/prostop_nl/website/htdocs/index.php(17): require('...')
#10 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-11-24 11:16:22 [error X 1][/data/www/prostop_nl/website/htdocs/wp-content/plugins/elementor/core/files/uploads-manager.php::50] Uncaught Error: Class "Elementor\Core\Files\File_Types\Json" not found in /data/www/prostop_nl/website/htdocs/wp-content/plugins/elementor/core/files/uploads-manager.php:50
Stack trace:
#0 /data/www/prostop_nl/website/htdocs/wp-content/plugins/elementor/core/files/uploads-manager.php(402): Elementor\Core\Files\Uploads_Manager->register_file_types()
#1 /data/www/prostop_nl/website/htdocs/wp-content/plugins/elementor/includes/plugin.php(763): Elementor\Core\Files\Uploads_Manager->__construct()
#2 /data/www/prostop_nl/website/htdocs/wp-content/plugins/elementor/includes/plugin.php(671): Elementor\Plugin->init_components()
#3 /data/www/prostop_nl/website/htdocs/wp-includes/class-wp-hook.php(292): Elementor\Plugin->init()
#4 /data/www/prostop_nl/website/htdocs/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters()
#5 /data/www/prostop_nl/website/htdocs/wp-includes/plugin.php(484): WP_Hook->do_action()
#6 /data/www/prostop_nl/website/htdocs/wp-settings.php(560): do_action()
#7 /data/www/prostop_nl/website/htdocs/wp-config.php(74): require_once('...')
#8 /data/www/prostop_nl/website/htdocs/wp-load.php(37): require_once('...')
#9 /data/www/prostop_nl/website/htdocs/wp-blog-header.php(13): require_once('...')
#10 /data/www/prostop_nl/website/htdocs/index.php(17): require('...')
#11 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 20 of 402023-02-23 10:10:29 [info] Elementor/Upgrades - _on_each_version Finished 
2023-02-23 10:10:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.2',
  'to' => '3.11.2',
)]
2023-02-23 10:10:29 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.2',
  'to' => '3.11.2',
)]
2023-04-18 09:13:29 [info] elementor::elementor_updater Started 
2023-04-18 09:13:29 [info] Elementor/Upgrades - _on_each_version Start  
2023-04-18 09:13:29 [info] Elementor/Upgrades - _on_each_version Finished 
2023-04-18 09:13:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.2',
  'to' => '3.12.1',
)]
2023-04-18 09:13:29 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.2',
  'to' => '3.12.1',
)]
2023-04-18 09:13:30 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.2',
  'to' => '3.12.1',
)]
2023-09-14 09:16:10 [info] elementor::elementor_updater Started 
2023-09-14 09:16:10 [info] Elementor/Upgrades - _on_each_version Start  
2023-09-14 09:16:10 [info] Elementor/Upgrades - _on_each_version Finished 
2023-09-14 09:16:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.1',
  'to' => '3.16.2',
)]
2023-09-26 15:34:25 [info] elementor::elementor_updater Started 
2023-09-26 15:34:25 [info] Elementor/Upgrades - _on_each_version Start  
2023-09-26 15:34:25 [info] Elementor/Upgrades - _on_each_version Finished 
2023-09-26 15:34:25 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Start  
2023-09-26 15:34:25 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Finished 
2023-09-26 15:34:25 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.16.2',
  'to' => '3.16.4',
)]
2023-09-26 15:34:25 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.16.2',
  'to' => '3.16.4',
)]

JS: showing 1 of 1JS: 2023-04-18 07:13:31 [error X 1][https://www.prostop.nl/wp-content/plugins/elementor/assets/js/import-export-admin.min.js?ver=3.11.2:2:5394] elementorImportExport is not defined 

== Elementor - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @jasper-totalstudio! 

Thank you for submitting your issue! 🙏 

Please allow us some time to investigate it, and get back to you with our findings. 🧐 

Best regards

**Comment by mikodigital** [comment]
Hello,
I had the same problem and i could access the lightbox as a promise. 
This is my updated code. 
it helps? 
`<a data-video-id="luKquWe89jo"class="play-video"></a>
<script type="text/javascript">
	jQuery( document ).ready(function($){
		async function getLightbox(){
			return await elementorFrontend.utils.lightbox; 
		}
		var myLightbox;
		var myVideoId;
		$('.play-video').on('click',function( event ){
			event.preventDefault();
			myLightbox= getLightbox();
			myVideoId=$(this).attr('data-video-id');
			myLightbox.then(function(result){
				console.log('then');
				console.log(result);
				result.showModal({
					url: 'https://www.youtube.com/embed/'+myVideoId+'?feature=oembed&rel=0&controls=1&showinfo=0&mute=0&wmode=opaque',
					videoAspectRatio: '169',
					type: 'video',
				});
			});
		});
	});
</script>`
