### ISSUE TITLE
⛔ 🐞 Taxonomy filter doesn't work if post grid is set according to another taxonomy

### ISSUE THREAD

**Issue by bartoopl** [elementor/elementor#23917]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Using ACF, I created a custom post type with two taxonomy: locality and specialty. On the frontend, I created a loop grid displaying the custom post type with the value of taxonomy: specialty. I created a taxonomy filter with a filter setting based on the value of taxonomy: locality. When setting up the page, the taxonomies display and work properly. After saving- on the frontend there is no taxonomy filter with corresponding values (shows first item only)

Error in the console:
```
taxonomy-filter.9df78f10e131a7423313.bundle.min.js:2 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'parentNode')
    at getChildrenWidth (taxonomy-filter.9df78f10e131a7423313.bundle.min.js:2:158)
    at isHorizontalScroll (taxonomy-filter.9df78f10e131a7423313.bundle.min.js:2:736)
    at setHorizontalScrollAlignment (taxonomy-filter.9df78f10e131a7423313.bundle.min.js:2:779)
    at TaxonomyFilter.onInit (taxonomy-filter.9df78f10e131a7423313.bundle.min.js:2:5937)
    at Module.trigger (frontend-modules.min.js?ver=3.16.4:2:27244)
    at Module.e.each.n.<computed> [as trigger] (frontend-modules.min.js?ver=3.16.4:2:27432)
    at TaxonomyFilter.Module (frontend-modules.min.js?ver=3.16.4:2:27530)
    at TaxonomyFilter.child [as constructor] (frontend-modules.min.js?ver=3.16.4:2:27795)
    at new child (frontend-modules.min.js?ver=3.16.4:2:27795)
    at new TaxonomyFilter (taxonomy-filter.9df78f10e131a7423313.bundle.min.js:2:1591)
```

### Steps to reproduce

1) Create a CPT with two taxonomies
2) Create a loop grid with CPT display with one of the taxonomies
3) Create a taxonomy filter with the other taxonomy

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>Click to reveal</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.4.27
	PHP Version: 7.4.33
	PHP Memory Limit: 1024M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.3.1
	Site URL: http://mediraj.owli.co
	Home URL: http://mediraj.owli.co
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 128M
	Max Memory limit: 1024M
	Permalink Structure: /%postname%/
	Language: pl-PL
	Timezone: Europe/Warsaw
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 2.0.0
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.8.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: pl_PL
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15

== Active Plugins ==
	Advanced Custom Fields
		Version: 6.2.1
		Author: WP Engine

	Advanced Post Queries
		Version: 1.1.1
		Author: Shabti Kaplan

	Code Snippets
		Version: 3.5.0
		Author: Code Snippets Pro

	Dynamic Visibility for Elementor
		Version: 5.0.6
		Author: Dynamic.ooo

	Elementor
		Version: 3.16.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.16.2
		Author: Elementor.com

	Orphans
		Version: 3.2.3
		Author: Marcin Pietrzak

	Redirection
		Version: 5.3.10
		Author: John Godley

	Search & Filter Pro
		Version: 2.5.16
		Author: Code Amp

	Simple Custom CSS and JS
		Version: 3.44
		Author: SilkyPress.com

	Temporary Login Without Password
		Version: 1.8.2
		Author: StoreApps

	Unlimited Elements for Elementor (Premium)
		Version: 1.5.85
		Author: Unlimited Elements

	Yoast SEO
		Version: 21.2
		Author: Team Yoast


== Wykorzystanie elementów ==
	
	archive : 1
		container : 2
		loop-grid : 1
		text-editor : 2
	container : 1
		container : 4
		heading : 1
		html : 1
		icon : 1
		icon-box : 1
	footer : 1
		container : 12
		heading : 8
		icon-list : 8
		image : 1
		theme-site-logo : 1
	header : 1
		button : 5
		container : 14
		icon-list : 5
		mega-menu : 1
		nav-menu : 1
		nested-tabs : 1
		search-form : 1
		social-icons : 1
		theme-site-logo : 1
	wp-page : 15
		button : 60
		call-to-action : 5
		container : 479
		form : 1
		google_maps : 6
		heading : 68
		html : 1
		icon : 1
		icon-box : 91
		icon-list : 27
		image : 72
		loop-carousel : 12
		loop-grid : 8
		nested-accordion : 22
		nested-carousel : 3
		nested-tabs : 2
		posts : 6
		taxonomy-filter : 7
		text-editor : 185
	single-post : 1
		container : 11
		html : 1
		image : 1
		nested-accordion : 1
		text-editor : 6
		theme-post-title : 1
	search-results : 1
		container : 1
		loop-grid : 1
	loop-item : 3
		button : 2
		container : 6
		heading : 1
		star-rating : 1
		text-editor : 2
		theme-post-content : 1
		theme-post-featured-image : 2
		theme-post-title : 2


== Ustawienia ==
	
	cpt_support: post, page, e-landing-page, lekarz
	allow_tracking: yes
	css_print_method: internal
	editor_break_lines: 1
	unfiltered_files_upload: 1
	font_display: swap


== Składniki oferty ==
	Custom Fonts: 0
	Custom Icons: 0

== Integracje ==
	


== Eksperymenty z Elementorem ==
	Zoptymalizowany wynik DOM: Domyślnie aktywne
	Ulepszone ładowanie zasobów: Domyślnie aktywne
	Poprawione ładowanie CSS: Nieaktywne
	Czcionka ikon: Włączono
	Dodatkowe niestandardowe punkty zmiany: Domyślnie aktywne
	admin_menu_rearrangement: Domyślnie nieaktywne
	Flexbox Container: Włączono
	Upgrade Swiper Library: Włączono
	Grid Container: Włączono
	Default to New Theme Builder: Domyślnie aktywne
	Nagłówek i stopka motywu Hello: Domyślnie aktywne
	Editor Top Bar: Włączono
	Strony docelowe: Domyślnie aktywne
	Elementy zagnieżdżone: Włączono
	Leniwe ładowanie obrazów tła: Włączono
	Pages Panel: Domyślnie nieaktywne
	Global Style Guide: Włączono
	Page Transitions: Domyślnie aktywne
	Notes: Domyślnie aktywne
	Form Submissions: Domyślnie aktywne
	Scroll Snap: Domyślnie aktywne
	Menu: Włączono
	Taxonomy Filter: Włączono


== Dziennik ==
	
Log: showing 20 of 302023-09-15 10:39:01 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Start  
2023-09-15 10:39:01 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Finished 
2023-09-15 10:39:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.16.2',
  'to' => '3.16.3',
)]
2023-09-15 10:40:07 [info] elementor-pro::elementor_pro_updater Started 
2023-09-15 10:40:07 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-09-15 10:40:07 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-09-15 10:40:07 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.16.0',
  'to' => '3.16.1',
)]
2023-09-15 10:40:07 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.16.0',
  'to' => '3.16.1',
)]
2023-09-20 20:12:29 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.16.3',
  'to' => '3.16.4',
)]
2023-09-20 20:12:29 [info] elementor-pro::elementor_pro_updater Started 
2023-09-20 20:12:29 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-09-20 20:12:29 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-09-20 20:12:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.16.1',
  'to' => '3.16.2',
)]
2023-09-20 20:12:29 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.16.1',
  'to' => '3.16.2',
)]
2023-09-20 20:12:30 [info] elementor::elementor_updater Started 
2023-09-20 20:12:30 [info] Elementor/Upgrades - _on_each_version Start  
2023-09-20 20:12:31 [info] Elementor/Upgrades - _on_each_version Finished 
2023-09-20 20:12:31 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Start  
2023-09-20 20:12:31 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Finished 
2023-09-20 20:12:31 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.16.3',
  'to' => '3.16.4',
)]

JS: showing 5 of 5JS: 2023-09-13 21:29:58 [error X 6][http://mediraj.owli.co/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.16.2:3:803450] undefined is not an object (evaluating 'T.originalEvent.key.toLowerCase') 
JS: 2023-09-17 20:28:12 [error X 7][http://mediraj.owli.co/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.16.3:3:804285] undefined is not an object (evaluating 'this.store.find((function(T){return T.original===C})).localized') 
JS: 2023-09-25 18:45:09 [error X 2][http://mediraj.owli.co/wp-includes/js/jquery/jquery.min.js?ver=3.7.0:2:28729] undefined is not an object (evaluating 'l[0].value') 
JS: 2023-09-27 21:01:23 [error X 2][http://mediraj.owli.co/wp-content/plugins/elementor-pro/assets/js/taxonomy-filter.9df78f10e131a7423313.bundle.min.js:2:157] undefined is not an object (evaluating 'e[0].parentNode') 
JS: 2023-09-28 20:56:57 [error X 1][http://mediraj.owli.co/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.16.4:3:312655] undefined is not an object (evaluating 'T.params.args.data.id') 

PHP: showing 7 of 7PHP: 2023-09-14 19:05:59 [notice X 20][../wp-content/plugins/elementor/modules/history/revisions-manager.php::363] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-14 23:21:20 [notice X 13][../wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php::33] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-18 22:55:22 [error X 1][../wp-content/plugins/elementor/core/wp-api.php::26] Uncaught Error: Call to undefined function Elementor\Core\get_plugins() in ../wp-content/plugins/elementor/core/wp-api.php:26
Stack trace:
#0 ../wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(96): Elementor\Core\Wp_Api->get_plugins()
#1 ../wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(58): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_with_header()
#2 ../wp-content/plugins/elementor/modules/compatibility-tag/module.php(57): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_to_check()
#3 ../wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(148): Elementor\Modules\CompatibilityTag\Module->get_plugins_to_check()
#4 ../wp-includes/class-wp-hook [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-25 23:20:36 [notice X 5][../wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-25 23:20:36 [notice X 15][../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined index: condition_type [array (
  'trace' => '
#0: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: ../wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2023-09-27 21:23:10 [notice X 1][../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::171] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-28 22:44:54 [notice X 9][../wp-content/plugins/elementor/includes/elements/container.php::43] Creation of dynamic property Elementor\Includes\Elements\Container::$logical_dimensions_inline_end is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Dynamic Visibility for Elementor: Kompatybilność nieokreślona
	Elementor Pro: Kompatybilność nieokreślona
	Unlimited Elements for Elementor (Premium): Kompatybilność nieokreślona

== Elementor Pro - Compatibility Tag ==
	

				
````

</details>

**Comment by bartoopl** [comment]
In edit mode all is good
![Zrzut ekranu 2023-09-29 o 00 31 36](https://github.com/elementor/elementor/assets/75386469/2dabca7b-be9d-4b23-969b-d4d46622c8ad)

Front:
![Zrzut ekranu 2023-09-29 o 00 33 07](https://github.com/elementor/elementor/assets/75386469/32df0f8d-3c6b-431a-9d87-3b9eb0f573af)

**Comment by Cormick** [comment]
Hello, I have exactly the same problem when using the taxonomy filter for the first time. This bug is also reproducible for me. Is there a solution?

**Comment by nicholaszein** [comment]
Hi, @bartoopl, and @Cormick,

Thank you for reaching out! 🙏 

### ⛔ After reviewing your report we concluded this is not a bug caused by Elementor. The feature you're referring to is not yet supported.

If you think this should be an Elementor feature, please cast your ⬆️ **Upvote** in #23418 and we will consider it in the future if there is enough demand (votes) from other users.

Kind regards
