### ISSUE TITLE
PODS shortcode does not work in Archive template

### ISSUE THREAD

**Issue by jamieburchell** [elementor/elementor#24048]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

These PODS shortcodes do not work when used in a Loop Grid template where the Loop Grid is added to an Archive page:

`[pods field="example_field"]`

`[pods]{@example_field}[/pods]`

They _do_ work when adding the Loop Grid to a non-archive template.

### Steps to reproduce

1) Create a new POD "Services" and make sure to enable the archive page
2) Add a required number field named "example_field"
3) Add a few example Services
4) Create a Loop Item Template e.g. "Services Loop Item"
5) Add a Shortcode widget to the Loop Item Template with either of the shortcodes mentioned in the description above
6) Add a new Archive Template for "Services"
7) Add a new Loop Grid to the Archive Template, choosing "Services Loop Item" and current query as the source
8) Observe the example_field is not output

Try the same again, but add the Loop Grid to any other page and use "Services" as the source and you will see it works as expected.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.5.22
	PHP Version: 8.1.24
	PHP Memory Limit: 256M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 50M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: There are some writing permissions issues with the following directories/files:
		 - WordPress root directory
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.3.2
	Site URL: https://example.local/wp
	Home URL: https://example.local
	WP Multisite: No
	Max Upload Size: 40 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-GB
	Timezone: Europe/London
	Admin Email: jamie@example.local
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.8.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36

== Active Plugins ==
	Code Snippets
		Version: 3.5.0
		Author: Code Snippets Pro

	Converter for Media
		Version: 5.11.2
		Author: matt plugins

	Elementor
		Version: 3.16.5
		Author: Elementor.com

	Elementor Pro
		Version: 3.16.2
		Author: Elementor.com

	Pods - Custom Content Types and Fields
		Version: 3.0.6
		Author: Pods Framework Team

	Rank Math SEO
		Version: 1.0.203
		Author: Rank Math

	W3 Total Cache
		Version: 2.5.0
		Author: BoldGrid

	Wordfence Security
		Version: 7.10.4
		Author: Wordfence


== Must-Use Plugins ==
	Bedrock Autoloader
		Version: 1.0.3
		Author: Roots

	Disable status tests
		Version: 1.0.0
		Author: Roots

	Register Theme Directory
		Version: 1.0.0
		Author: Roots


== Features ==
	Custom Fonts: 1
	Custom Icons: 0

== Integrations ==
	
	recaptcha_v3: Active


== Elementor Experiments ==
	Optimised DOM Output: Active
	Improved asset loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Inactive
	Additional Custom Breakpoints: Inactive
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active
	Grid Container: Inactive
	Default to New Theme Builder: Active
	Hello Theme Header & Footer: Inactive
	Editor Top Bar: Inactive
	Landing pages: Inactive
	Nested Elements: Inactive
	Lazy Load Background Images: Inactive
	Global Style Guide: Inactive
	Page Transitions: Inactive
	Notes: Inactive
	Form Submissions: Active
	Scroll Snap: Inactive
	Menu: Inactive
	Taxonomy Filter: Inactive


== Log ==
	
JS: showing 5 of 5JS: 2023-10-02 11:46:34 [error X 1][https://example.local/app/plugins/elementor-pro/assets/js/editor.min.js?ver=3.16.2:2:88666] Cannot read properties of undefined (reading 'settings') 
JS: 2023-10-02 21:43:43 [error X 4][https://example.local/app/plugins/elementor/assets/js/editor.min.js?ver=3.16.4:3:639823] Cannot read properties of undefined (reading 'isDesignable') 
JS: 2023-10-03 12:57:24 [error X 4][https://example.local/app/plugins/elementor/assets/js/editor.min.js?ver=3.16.4:3:689234] this.model.isValidChild is not a function 
JS: 2023-10-17 13:20:44 [error X 2][https://example.local/app/plugins/elementor/assets/js/editor.min.js?ver=3.16.5:3:54034] Cannot read properties of undefined (reading 'activate') 
JS: 2023-10-18 11:38:26 [error X 1][https://example.local/app/plugins/elementor/assets/js/editor.min.js?ver=3.16.5:3:601333] Cannot read properties of null (reading 'id') 

PHP: showing 20 of 30PHP: 2023-10-02 17:49:50 [warning X 1][/var/www/releases/10/web/app/plugins/elementor/core/files/file-types/svg.php::234] simplexml_load_file(): I/O warning : failed to load external entity "https://example.local/app/uploads/2023/10/british-red-cross-logo.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-10-02 17:51:33 [warning X 2][/var/www/releases/10/web/app/plugins/elementor/core/files/file-types/svg.php::234] simplexml_load_file(): I/O warning : failed to load external entity "https://example.local/app/uploads/2023/10/kiva-logo.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-10-02 21:38:41 [warning X 114][/var/www/releases/11/web/app/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key "condition_type" [array (
  'trace' => '
#0: /var/www/releases/11/web/app/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /var/www/releases/11/web/app/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /var/www/releases/11/web/app/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /var/www/releases/11/web/app/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2023-10-02 22:12:51 [warning X 9][/var/www/releases/11/web/app/plugins/elementor/modules/history/revisions-manager.php::363] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-10-02 22:38:38 [error X 10][/var/www/releases/11/web/app/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::304] Uncaught Error: Call to a member function update_meta() on null in /var/www/releases/11/web/app/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:304
Stack trace:
#0 /var/www/releases/11/web/app/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(177): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(6, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /var/www/releases/11/web/app/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /var/www/releases/11/web/wp/wp-includes/class-wp-hook.php(310): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /var/www/releases/11/web/wp/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters('', Array)
#5 /var/www/releases/11/web/wp/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /var/www/releases/11/web/wp/wp-admin/admin-ajax.php(188): do_action('wp_ajax_element...')
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-10-03 13:00:41 [warning X 1][/var/www/releases/11/web/app/plugins/elementor/core/files/file-types/svg.php::234] simplexml_load_file(): I/O warning : failed to load external entity "https://example.local/app/uploads/2023/10/icon-arrow-up.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-10-04 10:07:40 [warning X 1][/var/www/releases/11/web/app/plugins/elementor/core/files/file-types/svg.php::234] simplexml_load_file(): I/O warning : failed to load external entity "https://example.local/app/uploads/2023/10/icon-chevron-left.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-10-04 10:07:53 [warning X 1][/var/www/releases/11/web/app/plugins/elementor/core/files/file-types/svg.php::234] simplexml_load_file(): I/O warning : failed to load external entity "https://example.local/app/uploads/2023/10/icon-chevron-right.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-10-04 10:08:36 [warning X 1][/var/www/releases/11/web/app/plugins/elementor/core/files/file-types/svg.php::234] simplexml_load_file(): I/O warning : failed to load external entity "https://example.local/app/uploads/2023/10/icon-chevron-up.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-10-04 12:22:37 [warning X 1][/var/www/releases/11/web/app/plugins/elementor/core/files/file-types/svg.php::234] simplexml_load_file(): I/O warning : failed to load external entity "https://example.local/app/uploads/2023/10/logo.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-10-13 12:12:56 [warning X 2][/var/www/releases/14/web/app/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key "condition_type" [array (
  'trace' => '
#0: /var/www/releases/14/web/app/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /var/www/releases/14/web/app/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /var/www/releases/14/web/app/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /var/www/releases/14/web/app/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2023-10-17 10:21:46 [warning X 171][/var/www/releases/15/web/app/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key "condition_type" [array (
  'trace' => '
#0: /var/www/releases/15/web/app/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /var/www/releases/15/web/app/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /var/www/releases/15/web/app/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /var/www/releases/15/web/app/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2023-10-17 12:07:26 [warning X 2][/var/www/releases/15/web/app/plugins/elementor-pro/modules/posts/skins/skin-content-base.php::265] Attempt to read property "ID" on null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-10-17 12:19:38 [warning X 1][/var/www/releases/15/web/app/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key "condition_type" [array (
  'trace' => '
#0: /var/www/releases/15/web/app/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /var/www/releases/15/web/app/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(84): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /var/www/releases/15/web/app/plugins/elementor/data/base/endpoint.php(166): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> update_item()
#3: /var/www/releases/15/web/app/plugins/elementor/data/base/endpoint.php(307): Elementor\Data\Base\Endpoint -> base_callback()
#4: /var/www/releases/15/web/wp/wp-includes/rest-api/class-wp-rest-server.php(1194): Elementor\Data\Base\Endpoint -> Elementor\Data\Base\{closure}()
',
)]
PHP: 2023-10-17 12:43:22 [warning X 1][/var/www/releases/15/web/app/plugins/elementor-pro/modules/query-control/module.php::756] Undefined array key "filter_type" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-10-17 15:35:54 [warning X 27][/var/www/releases/15/web/app/plugins/elementor/app/modules/import-export/module.php::753] Attempt to read property "label" on null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-10-17 15:35:55 [warning X 27][/var/www/releases/15/web/app/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-10-17 15:36:03 [warning X 31][/var/www/releases/15/web/app/plugins/elementor-pro/modules/dynamic-tags/tags/site-logo.php::32] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-10-17 17:30:16 [error X 3][/var/www/releases/15/web/app/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::304] Uncaught Error: Call to a member function update_meta() on null in /var/www/releases/15/web/app/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:304
Stack trace:
#0 /var/www/releases/15/web/app/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(177): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(6, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /var/www/releases/15/web/app/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /var/www/releases/15/web/wp/wp-includes/class-wp-hook.php(310): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /var/www/releases/15/web/wp/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters('', Array)
#5 /var/www/releases/15/web/wp/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /var/www/releases/15/web/wp/wp-admin/admin-ajax.php(188): do_action('wp_ajax_element...')
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-10-18 11:52:49 [notice X 6][/var/www/releases/15/web/app/plugins/elementor-pro/modules/custom-css/module.php::76] trim(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 7 of 72023-10-17 09:29:18 [info] Update DB has been started [array (
  'plugin' => 'Elementor',
  'from' => '3.16.4',
  'to' => '3.16.5',
)]
2023-10-17 09:29:18 [info] elementor::elementor_updater Started 
2023-10-17 09:29:18 [info] Elementor/Upgrades - _on_each_version Start  
2023-10-17 09:29:18 [info] Elementor/Upgrades - _on_each_version Finished 
2023-10-17 09:29:19 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Start  
2023-10-17 09:29:19 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Finished 
2023-10-17 09:29:19 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.16.4',
  'to' => '3.16.5',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==
	

				
```

**Comment by jamieburchell** [comment]
@nicholaszein Bitten by this again today. Any ETA on a fix?

**Comment by ellengardt** [comment]
Same

**Comment by sc0ttkclark** [comment]
FYI -- Pods uses the `in_the_loop()` conditional to detect the post type / ID from a given item.

**Comment by jamieburchell** [comment]
The developers of PODS have very kindly added a workaround for this in 3.2.0. By adding `bypass_detect_loop="1"` to the shortcode, it will work inside loop elements added to an archive template.
