### ISSUE TITLE
While updating the page getting server error 500

### ISSUE THREAD

**Issue by satyammishra0** [elementor/elementor#24052]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I have currently shifter my hosting C panel and now in my new website i can't edit my page with elementor it's giving server error 500 and too much errors in console too.
I have changed the wp memory limit increased and all and my normal wordpress editor is working fine but only elimentor plugin is creating issue  

### Steps to reproduce

After shifting i am facing the issue

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release 23, Revision 500fcf5 v5.7.23-23
	PHP Version: 7.4.33
	PHP Memory Limit: 512M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 32M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2.2
	Site URL: https://saaol.com
	Home URL: https://saaol.com
	WP Multisite: No
	Max Upload Size: 32 MB
	Memory limit: 768M
	Max Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 5.5
	Admin Email: sawan.jain@saaol.co.in
	Debug Mode: Inactive

== Theme ==
	Name: Astra
	Version: 3.7.3
	Author: Brainstorm Force
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 6.1.7
		Author: WP Engine

	AnWP Post Grid and Post Carousel Slider for Elementor
		Version: 1.2.0
		Author: Andrei Strekozov <anwppro>

	CC BMI Calculator
		Version: 2.0.1
		Author: Calculators World

	Classic Editor
		Version: 1.6.3
		Author: WordPress Contributors

	Conditional Fields for Contact Form 7
		Version: 2.3.9
		Author: Jules Colle

	Contact Form 7
		Version: 5.7.7
		Author: Takayuki Miyoshi

	Contact Form 7 Captcha
		Version: 0.1.2
		Author: 247wd

	Country State City Dropdown CF7
		Version: 2.7.1
		Author: Trusty Plugins

	Custom Post Type UI
		Version: 1.13.6
		Author: WebDevStudios

	Ele Custom Skin
		Version: 3.1.7
		Author: Dudaster.com

	Elementor
		Version: 3.6.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.4.1
		Author: Elementor.com

	Essential Addons for Elementor
		Version: 5.8.0
		Author: WPDeveloper

	Fitness Calculators
		Version: 2.0.4
		Author: Gurcharan Singh

	Formidable Forms Pro
		Version: 5.0.15
		Author: Strategy11

	Forminator
		Version: 1.24.4
		Author: WPMU DEV

	Google Language Translator
		Version: 6.0.19
		Author: Translate AI Multilingual Solutions

	Loginizer
		Version: 1.7.9
		Author: Softaculous

	Mailjet for WordPress
		Version: 5.4.7
		Author: Mailjet SAS

	Polylang
		Version: 3.4.3
		Author: WP SYNTEX

	PowerPack Lite for Elementor
		Version: 2.7.7
		Author: IdeaBox Creations

	Premium Addons for Elementor
		Version: 4.10.1
		Author: Leap13

	Redirection
		Version: 5.3.10
		Author: John Godley

	Search Widget Post Types for Elementor
		Version: 1.0.3
		Author: 

	Simple Custom CSS and JS
		Version: 3.44
		Author: SilkyPress.com

	Site Kit by Google
		Version: 1.104.0
		Author: Google

	video carousel slider with lightbox
		Version: 1.0.23
		Author: I Thirteen Web Solution

	W3 Total Cache
		Version: 2.3.3
		Author: BoldGrid

	WP-Ban
		Version: 1.69.1
		Author: Lester 'GaMerZ' Chan

	WP Call Button
		Version: 1.3.1
		Author: Syed Balkhi

	WPCode Lite
		Version: 2.0.13
		Author: WPCode

	WP File Manager
		Version: 7.1.9
		Author: mndpsingh287

	WPForms
		Version: 1.6.7
		Author: WPForms

	WPForms Custom Captcha
		Version: 1.2.0
		Author: WPForms

	WPForms Signatures
		Version: 1.1.3
		Author: WPForms

	Yoast SEO
		Version: 20.10
		Author: Team Yoast

	Yoast Test Helper
		Version: 1.17
		Author: Team Yoast

== Elements Usage ==
	
	footer : 1
		button : 1
		heading : 2
		icon-list : 3
		image : 2
		social-icons : 1
		spacer : 1
	header : 2554
		button : 216
		icon : 216
		icon-list : 108
		image : 216
		nav-menu : 216
	page : 7
		button : 28
		counter : 16
		eael-adv-tabs : 3
		google_maps : 1
		heading : 71
		icon-box : 29
		icon-list : 7
		image : 39
		shortcode : 1
		spacer : 1
		text-editor : 24
	popup : 2
		heading : 3
		icon-box : 27
	section : 15
		button : 6
		eael-data-table : 1
		heading : 14
		icon : 2
		icon-box : 25
		icon-list : 22
		image : 4
		social-icons : 1
		spacer : 1
		text-editor : 14
	wp-post : 3
		heading : 3
		image : 11
		text-editor : 14
	wp-page : 383
		animated-headline : 1
		anwp-pg-classic-slider : 7
		author-box : 8
		button : 289
		counter : 8
		eael-adv-tabs : 4
		form : 1
		google_maps : 114
		heading : 290
		html : 12
		icon-box : 138
		icon-list : 7
		image : 110
		posts : 1
		pp-buttons : 5
		search-form : 1
		shortcode : 111
		slides : 2
		social-icons : 1
		spacer : 3
		template : 3
		testimonial-carousel : 14
		text-editor : 197
		video : 16
	single-post : 1
		heading : 1
		posts : 1
		theme-post-content : 1
		theme-post-title : 1
	landing-page : 0
		button : 520
		counter : 8
		eael-adv-tabs : 4
		google_maps : 10
		heading : 1223
		icon-box : 12
		image : 661
		image-box : 8
		image-gallery : 1
		shortcode : 241
		spacer : 22
		testimonial-carousel : 96
		text-editor : 1218

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Inactive by default
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Inactive by default
	Hide native WordPress widgets from search results: Active by default
	: Inactive by default
	Flexbox Container: Inactive by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Form Submissions: Active by default

== Log ==
	
PHP: showing 19 of 19PHP: 2023-10-18 14:23:03 [error X 6][/home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/core/base/document.php::1629] Uncaught Error: Call to a member function get_settings() on bool in /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/core/base/document.php:1629
Stack trace:
#0 /home3/saaoldelhiind545/public_html/wp-includes/class-wp-hook.php(308): Elementor\Core\Base\Document->handle_revisions_changed(false, Object(WP_Post), Object(WP_Post))
#1 /home3/saaoldelhiind545/public_html/wp-includes/plugin.php(205): WP_Hook->apply_filters(false, Array)
#2 /home3/saaoldelhiind545/public_html/wp-includes/revision.php(182): apply_filters('wp_save_post_re...', false, Object(WP_Post), Object(WP_Post))
#3 /home3/saaoldelhiind545/public_html/wp-includes/class-wp-hook.php(310): wp_save_post_revision(7)
#4 /home3/saaoldelhiind545/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#5 /home3/saaoldelhiind545/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /home3/saaoldelhiind545/public_html/wp-includes/post.php(4684): do_action('post_updated', 7, Object(WP_Post), Object(WP_Post))
#7 /home3/saaoldelhiind545/public_html/wp-includes/post.php(4817): wp_insert_post(Array, false, true)
#8 /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/core/settings/page/manager.php(342): wp_update_post(Array)
#9 /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/core/settings/page/manager.php(118): Elementor\Core\Settings\Page\Manager->save_post_status(7, 'publish')
#10 /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/core/base/document.php(1542): Elementor\Core\Settings\Page\Manager->ajax_before_save_settings(Array, 7)
#11 /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/core/base/document.php(670): Elementor\Core\Base\Document->save_settings(Array)
#12 /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/core/documents-manager.php(527): Elementor\Core\Base\Document->save(Array)
#13 [internal function]: Elementor\Core\Documents_Manager->ajax_save(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#14 /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#15 /home3/saaoldelhiind545/public_html/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#16 /home3/saaoldelhiind545/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#17 /home3/saaoldelhiind545/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#18 /home3/saaoldelhiind545/public_html/wp-admin/admin-ajax.php(188): do_action('wp_ajax_element...')
#19 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-10-18 14:24:03 [error X 6][/home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/core/base/document.php::467] Uncaught Error: Call to a member function save_template_type() on bool in /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/core/base/document.php:467
Stack trace:
#0 /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/core/documents-manager.php(512): Elementor\Core\Base\Document->get_autosave(437, true)
#1 [internal function]: Elementor\Core\Documents_Manager->ajax_save(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home3/saaoldelhiind545/public_html/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home3/saaoldelhiind545/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#5 /home3/saaoldelhiind545/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /home3/saaoldelhiind545/public_html/wp-admin/admin-ajax.php(188): do_action('wp_ajax_element...')
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-10-18 15:02:04 [notice X 19][/home3/saaoldelhiind545/public_html/wp-content/plugins/elementor-pro/modules/forms/submissions/database/query.php::103] Using ${var} in strings is deprecated, use {$var} instead [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-10-18 15:21:51 [notice X 59][/home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::294] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-10-18 15:21:56 [notice X 10][/home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::294] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(294): class type trigger_error()
#2: /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/includes/managers/controls.php(522): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor-pro/modules/query-control/module.php(826): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2023-10-18 15:21:56 [notice X 10][/home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::294] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(294): class type trigger_error()
#2: /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/includes/managers/controls.php(522): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/module.php(162): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2023-10-18 15:21:56 [notice X 10][/home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::294] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(294): class type trigger_error()
#2: /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/includes/managers/controls.php(522): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor-pro/modules/forms/module.php(72): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2023-10-18 15:21:56 [notice X 10][/home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::294] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(294): class type trigger_error()
#2: /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/includes/managers/controls.php(522): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor-pro/modules/forms/module.php(73): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2023-10-18 15:22:12 [error X 4][/home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/core/base/document.php::1629] Uncaught Error: Call to a member function get_settings() on bool in /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/core/base/document.php:1629
Stack trace:
#0 /home3/saaoldelhiind545/public_html/wp-includes/class-wp-hook.php(308): Elementor\Core\Base\Document->handle_revisions_changed(false, Object(WP_Post), Object(WP_Post))
#1 /home3/saaoldelhiind545/public_html/wp-includes/plugin.php(205): WP_Hook->apply_filters(false, Array)
#2 /home3/saaoldelhiind545/public_html/wp-includes/revision.php(182): apply_filters('wp_save_post_re...', false, Object(WP_Post), Object(WP_Post))
#3 /home3/saaoldelhiind545/public_html/wp-includes/class-wp-hook.php(310): wp_save_post_revision(6601)
#4 /home3/saaoldelhiind545/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#5 /home3/saaoldelhiind545/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /home3/saaoldelhiind545/public_html/wp-includes/post.php(4684): do_action('post_updated', 6601, Object(WP_Post), Object(WP_Post))
#7 /home3/saaoldelhiind545/public_html/wp-includes/post.php(4817): wp_insert_post(Array, false, true)
#8 /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/core/settings/page/manager.php(342): wp_update_post(Array)
#9 /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/core/settings/page/manager.php(118): Elementor\Core\Settings\Page\Manager->save_post_status(6601, 'publish')
#10 /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/core/base/document.php(1542): Elementor\Core\Settings\Page\Manager->ajax_before_save_settings(Array, 6601)
#11 /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/core/base/document.php(670): Elementor\Core\Base\Document->save_settings(Array)
#12 /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/core/documents-manager.php(527): Elementor\Core\Base\Document->save(Array)
#13 [internal function]: Elementor\Core\Documents_Manager->ajax_save(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#14 /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#15 /home3/saaoldelhiind545/public_html/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#16 /home3/saaoldelhiind545/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#17 /home3/saaoldelhiind545/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#18 /home3/saaoldelhiind545/public_html/wp-admin/admin-ajax.php(188): do_action('wp_ajax_element...')
#19 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-10-18 16:17:50 [error X 1][/home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/core/base/document.php::1629] Uncaught Error: Call to a member function get_settings() on bool in /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/core/base/document.php:1629
Stack trace:
#0 /home3/saaoldelhiind545/public_html/wp-includes/class-wp-hook.php(308): Elementor\Core\Base\Document->handle_revisions_changed(false, Object(WP_Post), Object(WP_Post))
#1 /home3/saaoldelhiind545/public_html/wp-includes/plugin.php(205): WP_Hook->apply_filters(false, Array)
#2 /home3/saaoldelhiind545/public_html/wp-includes/revision.php(182): apply_filters('wp_save_post_re...', false, Object(WP_Post), Object(WP_Post))
#3 /home3/saaoldelhiind545/public_html/wp-includes/class-wp-hook.php(310): wp_save_post_revision(20)
#4 /home3/saaoldelhiind545/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#5 /home3/saaoldelhiind545/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /home3/saaoldelhiind545/public_html/wp-includes/post.php(4684): do_action('post_updated', 20, Object(WP_Post), Object(WP_Post))
#7 /home3/saaoldelhiind545/public_html/wp-includes/post.php(4817): wp_insert_post(Array, false, true)
#8 /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/core/settings/page/manager.php(122): wp_update_post(Array)
#9 /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/core/base/document.php(1542): Elementor\Core\Settings\Page\Manager->ajax_before_save_settings(Array, 20)
#10 /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/core/base/document.php(670): Elementor\Core\Base\Document->save_settings(Array)
#11 /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/core/documents-manager.php(527): Elementor\Core\Base\Document->save(Array)
#12 [internal function]: Elementor\Core\Documents_Manager->ajax_save(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#13 /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#14 /home3/saaoldelhiind545/public_html/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#15 /home3/saaoldelhiind545/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#16 /home3/saaoldelhiind545/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#17 /home3/saaoldelhiind545/public_html/wp-admin/admin-ajax.php(188): do_action('wp_ajax_element...')
#18 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-10-18 16:23:06 [notice X 1][/home3/saaoldelhiind545/public_html/wp-content/plugins/elementor-pro/modules/forms/submissions/database/entities/form-snapshot.php::70] Return type of ElementorPro\Modules\Forms\Submissions\Database\Entities\Form_Snapshot::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor-pro/modules/forms/submissions/database/entities/form-snapshot.php(15): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor-pro/plugin.php(141): class type include()array (
  0 => '/home3/saaoldelhiind545/public_html/wp-content/plugins/elementor-pro/modules/forms/submissions/database/entities/form-snapshot.php',
)
#2: /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor-pro/modules/forms/submissions/database/repositories/form-snapshot-repository.php(144): ElementorPro\Plugin -> autoload()
#3: ElementorPro\Modules\Forms\Submissions\Database\Repositories\Form_Snapshot_Repository -> ElementorPro\Modules\Forms\Submissions\Database\Repositories\{closure}()
#4: /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/core/utils/collection.php(116): class type array_map()
',
)]
PHP: 2023-10-19 02:02:56 [notice X 3][/home3/saaoldelhiind545/public_html/wp-content/plugins/elementor-pro/modules/forms/submissions/database/entities/form-snapshot.php::70] Return type of ElementorPro\Modules\Forms\Submissions\Database\Entities\Form_Snapshot::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-10-19 09:32:38 [notice X 1][/home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-10-19 09:33:05 [notice X 1][/home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor-pro/modules/query-control/module.php(826): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2023-10-19 09:33:05 [notice X 1][/home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/module.php(162): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2023-10-19 09:33:05 [notice X 1][/home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor-pro/modules/forms/module.php(72): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2023-10-19 09:33:05 [notice X 1][/home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor-pro/modules/forms/module.php(73): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2023-10-19 09:35:24 [error X 2][/home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/core/base/document.php::1629] Uncaught Error: Call to a member function get_settings() on bool in /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/core/base/document.php:1629
Stack trace:
#0 /home3/saaoldelhiind545/public_html/wp-includes/class-wp-hook.php(308): Elementor\Core\Base\Document->handle_revisions_changed(false, Object(WP_Post), Object(WP_Post))
#1 /home3/saaoldelhiind545/public_html/wp-includes/plugin.php(205): WP_Hook->apply_filters(false, Array)
#2 /home3/saaoldelhiind545/public_html/wp-includes/revision.php(182): apply_filters('wp_save_post_re...', false, Object(WP_Post), Object(WP_Post))
#3 /home3/saaoldelhiind545/public_html/wp-includes/class-wp-hook.php(310): wp_save_post_revision(7)
#4 /home3/saaoldelhiind545/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#5 /home3/saaoldelhiind545/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /home3/saaoldelhiind545/public_html/wp-includes/post.php(4684): do_action('post_updated', 7, Object(WP_Post), Object(WP_P [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-10-19 09:36:06 [error X 1][/home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/core/base/document.php::467] Uncaught Error: Call to a member function save_template_type() on bool in /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/core/base/document.php:467
Stack trace:
#0 /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/core/documents-manager.php(512): Elementor\Core\Base\Document->get_autosave(437, true)
#1 [internal function]: Elementor\Core\Documents_Manager->ajax_save(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home3/saaoldelhiind545/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home3/saaoldelhiind545/public_html/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home3/saaoldelhiind545/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#5 /home3/saaoldelhiind545/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /home3/saaoldelhiind545/pu [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 1 of 12023-10-19 02:00:46 [error] Save submission failed, db error: Duplicate entry '0' for key 'PRIMARY' 

== Elementor - Compatibility Tag ==
	
	AnWP Post Grid and Post Carousel Slider for Elementor: Compatibility not specified
	Elementor Pro: Compatibility not specified
	Essential Addons for Elementor: Compatibility not specified
	PowerPack Lite for Elementor: Compatibility not specified
	Premium Addons for Elementor: Compatibility not specified
	Search Widget Post Types for Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag =

**Comment by dev-Asifemon** [comment]
+1 having same issue with 7 of my sites
