### ISSUE TITLE
✅ 🐞 Nested Accordion inside another Nested Accordion always shows the collapse icon on all items

### ISSUE THREAD

**Issue by panaiotis** [elementor/elementor#24086]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

### Description

The state of all collapse/expand icons in an accordion that is nested inside a parent accordion always show the Collapse  icon regardless of the inner accordion items' state.

### Steps to reproduce

1. Create a new Elementor page
2. Add a container
3. Add an accordion widget inside the container
4. Open any of the items of the accordion (it defaults with item #1 opened, so no need to do anything)
5. Add an inner accordion to the item

All collapse/expand icons in the nested inner accordion show the Collapse icon, regardless if the item's open/close state.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>Click to reveal</summary>

````txt

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Debian 11 v10.5.19
	PHP Version: 7.4.33
	PHP Memory Limit: 512M
	PHP Max Input Vars: 4000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.3.2
	Site URL: https://www.panaiotis.us
	Home URL: https://www.panaiotis.us
	WP Multisite: No
	Max Upload Size: 100 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 2.0.0
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.8.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/118.0

== Active Plugins ==
	Advanced Custom Fields
		Version: 6.2.1
		Author: WP Engine

	Advanced Editor Tools
		Version: 5.9.2
		Author: Automattic

	All In One WP Security
		Version: 5.2.4
		Author: All In One WP Security & Firewall Team

	BetterDocs
		Version: 2.5.6
		Author: WPDeveloper

	Collapse-O-Matic
		Version: 1.8.5.5
		Author: twinpictures, baden03

	Elementor
		Version: 3.16.6
		Author: Elementor.com

	Elementor Pro
		Version: 3.16.2
		Author: Elementor.com

	EmbedPress
		Version: 3.9.1
		Author: WPDeveloper

	Essential Addons for Elementor
		Version: 5.8.12
		Author: WPDeveloper

	Essential Addons for Elementor - Pro
		Version: 5.8.0
		Author: WPDeveloper

	Exclusive Addons Elementor
		Version: 2.6.8
		Author: Exclusive Addons

	FileBird Lite
		Version: 5.5.3
		Author: Ninja Team

	File Manager Advanced
		Version: 5.1.2
		Author: modalweb

	Premium Addons for Elementor
		Version: 4.10.11
		Author: Leap13

	Theme My Login
		Version: 7.1.6
		Author: Theme My Login

	UpdraftPlus - Backup/Restore
		Version: 1.23.10
		Author: UpdraftPlus.Com, DavidAnderson

	WP-Optimize - Clean, Compress, Cache
		Version: 3.2.21
		Author: David Anderson, Ruhani Rabin, Team Updraft


== Must-Use Plugins ==
	aios-firewall-loader.php
		Version: 
		Author: 

	SWCP Disable Gravity Forms Htaccess Rule
		Version: 1.0
		Author: 

	SWCP Plug Leaks
		Version: 1.0
		Author: 

	SWCP WP Fail2Ban
		Version: 1.13
		Author: 


== Elements Usage ==
	
	container : 3
		container : 16
		eael-divider : 1
		eael-lightbox : 2
		heading : 7
		icon-list : 8
		premium-addon-button : 1
		premium-addon-title : 2
		text-editor : 1
	header : 1
		container : 2
		image : 1
		premium-nav-menu : 1
		theme-site-title : 1
	wp-post : 0
		alert : 1
		container : 5
		nested-accordion : 1
		wp-widget-media_audio : 1
	wp-page : 25
		betterdocs-content : 1
		button : 1
		container : 677
		counter : 1
		divider : 4
		eael-adv-accordion : 2
		eael-adv-tabs : 1
		eael-advanced-data-table : 1
		eael-advanced-menu : 1
		eael-creative-button : 2
		eael-data-table : 1
		eael-divider : 5
		eael-dual-color-header : 1
		eael-feature-list : 9
		eael-lightbox : 4
		eael-tooltip : 28
		exad-dual-button : 1
		exad-exclusive-accordion : 1
		exad-exclusive-alert : 1
		exad-exclusive-button : 1
		exad-exclusive-dual-heading : 1
		exad-exclusive-heading : 1
		exad-exclusive-tabs : 1
		exad-list-group : 1
		exad-modal-popup : 3
		exad-tooltip : 1
		gallery : 1
		heading : 112
		icon : 2
		icon-list : 37
		image : 1
		image-gallery : 1
		mega-menu : 1
		nested-accordion : 31
		nested-tabs : 20
		premium-addon-button : 1
		premium-addon-fancy-text : 1
		premium-addon-modal-box : 3
		premium-addon-title : 32
		premium-countdown-timer : 1
		premium-icon-list : 1
		premium-nav-menu : 3
		sidebar : 1
		template : 13
		text-editor : 131
		wp-widget-block : 1
		wp-widget-media_audio : 255
		wp-widget-text : 28


== Settings ==
	
	cpt_support: post, page, e-landing-page, docs
	disable_color_schemes: yes
	disable_typography_schemes: yes
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active by default
	Upgrade Swiper Library: Active by default
	Grid Container: Active
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Editor Top Bar: Active
	Landing Pages: Active by default
	Nested Elements: Active
	Lazy Load Background Images: Active
	Pages Panel: Inactive by default
	Global Style Guide: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Menu: Active
	Taxonomy Filter: Inactive by default


== Log ==
	
PHP: showing 5 of 5PHP: 2023-09-29 23:50:48 [notice X 1][/wp-content/plugins/elementor/includes/template-library/classes/class-import-images.php::199] Undefined index: url [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-10-11 04:37:18 [notice X 13][/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-10-11 04:41:56 [notice X 2][/wp-content/plugins/elementor/modules/history/revisions-manager.php::363] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-10-11 05:00:12 [notice X 1][/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::171] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-10-18 02:34:02 [error X 9][/wp-content/plugins/elementor/modules/nested-tabs/widgets/nested-tabs.php::1153] Uncaught Error: Call to a member function print_element() on null in /wp-content/plugins/elementor/modules/nested-tabs/widgets/nested-tabs.php:1153
Stack trace:
#0 /wp-content/plugins/elementor/modules/nested-tabs/widgets/nested-tabs.php(1124): Elementor\Modules\NestedTabs\Widgets\NestedTabs->print_child()
#1 /wp-content/plugins/elementor/modules/nested-tabs/widgets/nested-tabs.php(1207): Elementor\Modules\NestedTabs\Widgets\NestedTabs->render_tab_containers_html()
#2 /wp-content/plugins/elementor/includes/base/controls-stack.php(2265): Elementor\Modules\NestedTabs\Widgets\NestedTabs->render()
#3 /wp-content/plugins/elementor/includes/base/widget-base.php(609): Elementor\Controls_Stack->render_by_mode()
#4 /wp-content/plugins/elementor/includes/base/widget-base. [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 20 of 20JS: 2023-09-30 00:05:01 [error X 2][https://www.panaiotis.us/wp-content/plugins/elementor/assets/js/new-template.min.js?ver=3.16.4:2:2869] elementor_new_template_form_controls is not defined 
JS: 2023-09-30 00:10:40 [error X 15][https://www.panaiotis.us/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.16.4:3:919115] elementorFrontend is not defined 
JS: 2023-09-30 00:31:53 [error X 22][https://www.panaiotis.us/wp-content/plugins/elementor/assets/js/admin.min.js?ver=3.16.4:3:48021] l[0] is undefined 
JS: 2023-09-30 02:12:26 [error X 9][https://www.panaiotis.us/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.16.4:2:30893] elementor.settings.page is undefined 
JS: 2023-09-30 15:13:32 [error X 4][https://www.panaiotis.us/wp-content/plugins/elementor/assets/js/4fdaa70e951ad90db2f2.bundle.min.js:2:7765] t.target.closest(...) is null 
JS: 2023-09-30 17:47:04 [error X 1][https://www.panaiotis.us/wp-content/plugins/elementor/assets/lib/inline-editor/js/inline-editor.min.js?ver=3.16.4:1:12656] O is null 
JS: 2023-09-30 23:38:19 [error X 1][https://www.panaiotis.us/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.16.4:2:33010] n is null 
JS: 2023-10-03 00:15:42 [error X 66][https://www.panaiotis.us/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.16.4:3:321651] C.ui.form is undefined 
JS: 2023-10-04 03:32:58 [error X 2][https://www.panaiotis.us/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.16.4:3:639803] this.view.container is undefined 
JS: 2023-10-07 17:37:48 [error X 20][https://www.panaiotis.us/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.16.4:3:804647] this.store.find(...) is undefined 
JS: 2023-10-07 20:22:35 [error X 9][https://www.panaiotis.us/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.16.4:3:14266] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got as `exad_modal_image_gallery` value. Expected array or object.',
)]
JS: 2023-10-08 19:58:18 [error X 1][https://www.panaiotis.us/wp-content/uploads/essential-addons-elementor/eael.js?ver=1696786608:7:0]  
JS: 2023-10-14 18:12:30 [error X 2][https://www.panaiotis.us/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.16.5:3:54022] $ is undefined 
JS: 2023-10-17 01:11:57 [error X 1][https://www.panaiotis.us/wp-content/uploads/essential-addons-elementor/eael.js?ver=1697505091:13:350234] a.replace is not a function 
JS: 2023-10-17 03:30:14 [error X 1][https://www.panaiotis.us/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.16.5:3:4197] this.children.clear is not a function 
JS: 2023-10-17 18:25:43 [error X 2][https://www.panaiotis.us/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.16.5:3:146950] C.props.parentRef.current is null 
JS: 2023-10-17 21:49:45 [error X 7][https://www.panaiotis.us/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.16.5:3:624403] this.$currentEditingArea is null 
JS: 2023-10-19 13:32:45 [error X 2][https://www.panaiotis.us/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.16.6:3:395269] B[0] is undefined 
JS: 2023-10-19 17:57:09 [error X 3][https://www.panaiotis.us/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.16.6:3:689303] this.model.isValidChild is not a function 
JS: 2023-10-20 16:09:13 [error X 2][https://www.panaiotis.us/wp-content/plugins/elementor/assets/js/packages/editor-documents/editor-documents.min.js?ver=3.16.6:1:4267] r().getCurrent() is null 

Log: showing 14 of 142023-10-10 14:10:40 [info] elementor::elementor_updater Started 
2023-10-10 14:10:40 [info] Elementor/Upgrades - _on_each_version Start  
2023-10-10 14:10:41 [info] Elementor/Upgrades - _on_each_version Finished 
2023-10-10 14:10:41 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Start  
2023-10-10 14:10:41 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Finished 
2023-10-10 14:10:41 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.16.4',
  'to' => '3.16.5',
)]
2023-10-10 14:10:41 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.16.4',
  'to' => '3.16.5',
)]
2023-10-18 02:07:27 [info] elementor::elementor_updater Started 
2023-10-18 02:07:27 [info] Elementor/Upgrades - _on_each_version Start  
2023-10-18 02:07:28 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.16.5',
  'to' => '3.16.6',
)]
2023-10-18 02:07:29 [info] Elementor/Upgrades - _on_each_version Finished 
2023-10-18 02:07:29 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Start  
2023-10-18 02:07:29 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Finished 
2023-10-18 02:07:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.16.5',
  'to' => '3.16.6',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	Essential Addons for Elementor: Compatibility not specified
	Essential Addons for Elementor - Pro: Compatibility not specified
	Exclusive Addons Elementor: Compatibility not specified
	Premium Addons for Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==
	

		

````

</details>

**Comment by nicholaszein** [comment]
Hello, @panaiotis! 

Thank you for submitting your issue! 🙏 

🏷️ We've labeled this issue and our team will take a look at it. If there is indeed a problem, they'll work on fixing it. We can't say exactly when it'll be sorted out, but we kindly ask for your patience. Thanks for understanding!

Best regards

**Comment by simplicity17** [comment]
I just reported this issue in a support ticket and they did tell me it was a bug and needed to be elevated to the dev team. So many months and this is still a problem!!

**Comment by jfbwebmarketing** [comment]
Problem reported date : October 24, 2023
Today's date : May 6, 2024

Why taking so long to fix this!?

**Comment by mrdweb** [comment]
Have just come across this issue too. Would be good to ultimately get this bug fixed in the next update, or at least a code snippet we could use for now.

**Comment by mrdweb** [comment]
> Have just come across this issue too. Would be good to ultimately get this bug fixed in the next update, or at least a code snippet we could use for now.

Made a really elegant bunch of CSS to fix this problem. Add this into your themes' custom style.

`.elementor-widget-n-accordion .e-n-accordion-item > summary > .e-n-accordion-item-title-icon > .e-opened {
    display: none!important;
}
.elementor-widget-n-accordion .e-n-accordion-item > summary > .e-n-accordion-item-title-icon > .e-closed {
    display: flex!important;
}
.elementor-widget-n-accordion .e-n-accordion-item[open] > summary > .e-n-accordion-item-title-icon > .e-opened {
    display: flex!important;
}
.elementor-widget-n-accordion .e-n-accordion-item[open] > summary > .e-n-accordion-item-title-icon > .e-closed {
    display: none!important;
}`
