### ISSUE TITLE
Elementor Pro's popup feature adds localStorage entry even if popup is not used.

### ISSUE THREAD

**Issue by davidpfahler** [elementor/elementor#24189]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I have summarized the problem here: https://github.com/elementor/elementor/issues/7151#issuecomment-1792932276

But I have been blocked from adding further comments so I have to add this issue.

This issues can be hotfixed by checking for the existence of a popup in the `setViewsAndSessions` method in `elementor-pro/assets/js/elements-handlers.js`:

```
setViewsAndSessions() {
    // check for existence of popup
    const popup = elementorFrontend.documentsManager.documents[settings.id];
    if (!popup) {
      return;
    }
    // ...
```

An even better fix would be to add the popup feature to the improved asset loading feature and not even load the javascript if the feature is not used.

### Steps to reproduce

Use elementor pro without using the popup feature on any page, there is still an entry in localStorage which is not technically necessary and violates the European Union ePrivacy-Directive and Germany implementation of this directive (https://www.gesetze-im-internet.de/ttdsg/__25.html).

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.52 (Ubuntu)
	MySQL version: (Ubuntu) v8.0.35
	PHP Version: 8.1.2-1ubuntu2.14
	PHP Memory Limit: 256M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 50M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.3.2
	Site URL: 
	Home URL: 
	WP Multisite: No
	Max Upload Size: 50 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: de-DE
	Timezone: 2
	Admin Email: 
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.9.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36

== Active Plugins ==
	Duplicate Page
		Version: 4.5.3
		Author: mndpsingh287

	Elementor
		Version: 3.17.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.17.1
		Author: Elementor.com

	Starter Templates
		Version: 3.4.5
		Author: Brainstorm Force

	Yoast SEO
		Version: 21.5
		Author: Team Yoast

== Eigenschaften ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	

== Elementor-Experimente ==
	Optimierte DOM Ausgabe: Standardmäßig aktiviert
	Verbessertes Laden von Assets: Standardmäßig aktiviert
	Verbessertes Laden von CSS: Standardmäßig aktiviert
	Inline-Schriftarten-Symbole: Standardmäßig deaktiviert
	Zusätzliche benutzerdefinierte Breakpoints: Standardmäßig aktiviert
	admin_menu_rearrangement: Standardmäßig deaktiviert
	Flexbox Container: Standardmäßig aktiviert
	Upgrade Swiper Library: Standardmäßig aktiviert
	Grid Container: Standardmäßig deaktiviert
	Default to New Theme Builder: Standardmäßig aktiviert
	Hello Theme Header & Footer: Standardmäßig aktiviert
	Editor Top Bar: Standardmäßig deaktiviert
	Optimized Gutenberg Loading: Standardmäßig deaktiviert
	Build with AI: Standardmäßig deaktiviert
	Startseiten: Standardmäßig aktiviert
	Nested Elements: Standardmäßig deaktiviert
	Hintergrundbilder nachladen: Standardmäßig deaktiviert
	Optimize Image Loading: Standardmäßig deaktiviert
	Globaler Styleguide: Standardmäßig aktiviert
	Page Transitions: Standardmäßig aktiviert
	Notes: Standardmäßig aktiviert
	Form Submissions: Standardmäßig aktiviert
	Scroll Snap: Standardmäßig aktiviert
	Menü: Standardmäßig deaktiviert
	Taxonomy Filter: Standardmäßig deaktiviert

== Protokoll ==
	
PHP: showing 4 of 4PHP: 2023-09-28 15:53:13 [error X 12][/var/www/html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::304] Uncaught Error: Call to a member function update_meta() on null in /var/www/html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:304
Stack trace:
#0 /var/www/html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(177): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions()
#2 /var/www/html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func()
#3 /var/www/html/wp-includes/class-wp-hook.php(310): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#4 /var/www/html/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters()
#5 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action()
#6 /var/www/html/wp-admin/admin-ajax.php(188): do_action()
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-28 21:50:51 [warning X 30][/var/www/html/wp-content/plugins/elementor-pro/modules/dynamic-tags/tags/post-featured-image.php::36] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-10-13 15:46:30 [error X 1][/var/www/html/wp-content/plugins/elementor/core/wp-api.php::26] Uncaught Error: Call to undefined function Elementor\Core\get_plugins() in /var/www/html/wp-content/plugins/elementor/core/wp-api.php:26
Stack trace:
#0 /var/www/html/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(96): Elementor\Core\Wp_Api->get_plugins()
#1 /var/www/html/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(58): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_with_header()
#2 /var/www/html/wp-content/plugins/elementor/modules/compatibility-tag/module.php(57): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_to_check()
#3 /var/www/html/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(148): Elementor\Modules\CompatibilityTag\Module->get_plugins_to_check()
#4 /var/www/html/wp-includes/class-wp-hook.php(310): Elementor\Modules\CompatibilityTag\Base_Module->Elementor\Modules\CompatibilityTag\{closure}()
#5 /var/www/html/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters()
#6 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action()
#7 /var/www/html/wp-content/plugins/elementor/modules/system-info/module.php(340): do_action()
#8 /var/www/html/wp-content/plugins/elementor/includes/tracker.php(241): Elementor\Modules\System_Info\Module::get_allowed_reports()
#9 /var/www/html/wp-content/plugins/elementor/includes/tracker.php(530): Elementor\Tracker::get_system_reports_data()
#10 /var/www/html/wp-content/plugins/elementor/includes/tracker.php(141): Elementor\Tracker::get_tracking_data()
#11 /var/www/html/wp-includes/class-wp-hook.php(310): Elementor\Tracker::send_tracking_data()
#12 /var/www/html/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters()
#13 /var/www/html/wp-includes/plugin.php(565): WP_Hook->do_action()
#14 /var/www/html/wp-cron.php(191): do_action_ref_array()
#15 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-10-30 13:46:39 [error X 2][/var/www/html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::304] Uncaught Error: Call to a member function update_meta() on null in /var/www/html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:304
Stack trace:
#0 /var/www/html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(177): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions()
#2 /var/www/html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(176): call_user_func()
#3 /var/www/html/wp-includes/class-wp-hook.php(310): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#4 /var/www/html/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters()
#5 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action()
#6 /var/www/html/wp-admin/admin-ajax.php(188): do_action()
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 7 of 7JS: 2023-09-28 14:41:57 [error X 4][https://stegerpfahler.de/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.16.4:3:804689] Cannot read properties of undefined (reading 'localized') 
JS: 2023-09-28 14:45:56 [error X 7][https://stegerpfahler.de/wp-admin/load-scripts.php?c=0&loadchunk_0=jquery-core,jquery-migrate,utils,moxiejs,plupload&ver=6.3.1:2:28722] Cannot read properties of undefined (reading 'value') 
JS: 2023-09-28 15:15:49 [error X 3][https://stegerpfahler.de/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.16.2:2:64105] Cannot convert undefined or null to object 
JS: 2023-10-13 13:29:16 [error X 2][https://stegerpfahler.de/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.16.5:3:919184] elementorFrontend is not defined 
JS: 2023-10-25 15:26:49 [error X 1][https://stegerpfahler.de/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.16.6:3:639892] Cannot read properties of undefined (reading 'isDesignable') 
JS: 2023-10-28 20:01:29 [error X 2][https://stegerpfahler.de/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.16.6:3:804231] T.originalEvent.key is undefined 
JS: 2023-10-28 20:01:30 [error X 32][https://stegerpfahler.de/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.16.6:3:804716] this.store.find(...) is undefined 

Log: showing 20 of 312023-10-19 11:59:36 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Finished 
2023-10-19 11:59:36 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.16.5',
  'to' => '3.16.6',
)]
2023-10-19 11:59:36 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.16.5',
  'to' => '3.16.6',
)]
2023-10-30 11:30:48 [info] elementor::elementor_updater Started 
2023-10-30 11:30:48 [info] Elementor/Upgrades - _on_each_version Start  
2023-10-30 11:30:49 [info] Elementor/Upgrades - _on_each_version Finished 
2023-10-30 11:30:49 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Start  
2023-10-30 11:30:49 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Finished 
2023-10-30 11:30:49 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.16.6',
  'to' => '3.17.1',
)]
2023-10-30 11:30:49 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.16.6',
  'to' => '3.17.1',
)]
2023-11-03 20:25:21 [info] elementor-pro::elementor_pro_updater Started 
2023-11-03 20:25:21 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-11-03 20:25:21 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-11-03 20:25:21 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.16.2',
  'to' => '3.17.1',
)]
2023-11-03 20:25:21 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.16.2',
  'to' => '3.17.1',
)]
2023-11-03 20:25:21 [info] elementor::elementor_updater Started 
2023-11-03 20:25:21 [info] Elementor/Upgrades - _on_each_version Start  
2023-11-03 20:25:21 [info] Elementor/Upgrades - _on_each_version Finished 
2023-11-03 20:25:21 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.17.1',
  'to' => '3.17.2',
)]
2023-11-03 20:25:21 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.17.1',
  'to' => '3.17.2',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Die Kompatibilität ist nicht angegeben

== Elementor Pro - Compatibility Tag ==

**Comment by fido-hh** [comment]
This error has existed since February 2019. 
To mark the 5th anniversary, I wrote a short article explaining why the use of Elementor Pro is against the law in Germany:
https://dev3con.de/elementor-pro-in-deutschland-nicht-dsgvo-konform-nutzbar/
To be honest, i wrote it about a year ago. 
But since nothing hast changed, i now made it public.

**Comment by nicholaszein** [comment]
Hi @davidpfahler and @fido-hh!

We have great news! 🙌 

### 📢 We're happy to announce that this issue was resolved with the release Elementor Pro v3.25.0! 🥳 

Elementor Popup's Local Storage and Session Storage are now only used when Popups are in use.

It's important to emphasize that Elementor Popups do not store any identifiable user information, therefore it cannot be used to track visitors.

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
