### ISSUE TITLE
Elementor logo site bug

### ISSUE THREAD

**Issue by elennuyer** [elementor/elementor#24337]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

It show in my site this:
Warning: Undefined array key "options" in /home/u699801562/domains/ugocd.com/public_html/blog/wp-content/plugins/elementor-pro/modules/theme-builder/widgets/site-logo.php 

### Steps to reproduce

I've just detected right now it was ok last week.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.5.19
	PHP Version: 8.0.28
	PHP Memory Limit: 1536M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 1536M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.4.1
	Site URL: https://www.ugocd.com/blog
	Home URL: https://www.ugocd.com/blog
	WP Multisite: No
	Max Upload Size: 2 GB
	Memory limit: 40M
	Max Memory limit: 1536M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: es-PE
	Timezone: 0
	Admin Email: ugocd@ugocd.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.9.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: es_PE
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36

== Active Plugins ==
	Akismet Anti-spam: Spam Protection
		Version: 5.3
		Author: Automattic - Anti-spam Team

	Always Use Open Graph with Jetpack
		Version: 1.0.1
		Author: Brandon Kraft

	Category Posts Widget
		Version: 4.9.15
		Author: TipTopPress

	CookieYes | GDPR Cookie Consent
		Version: 3.1.7
		Author: CookieYes

	Elementor
		Version: 3.18.0-dev1
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.17.0
		Author: Elementor.com

	Hello Dolly
		Version: 1.7.2
		Author: Matt Mullenweg

	Jetpack
		Version: 12.8.1
		Author: Automattic

	LiteSpeed Cache
		Version: 5.7.0.1
		Author: LiteSpeed Technologies

	Yoast SEO
		Version: 21.5
		Author: Team Yoast

== Uso de los elementos ==
	
	archive : 2
		archive-posts : 1
		container : 2
		heading : 1
		text-editor : 2
	footer : 1
		container : 1
		image : 8
		nav-menu : 1
		text-editor : 2
		wp-widget-rss_links : 1
	header : 2
		container : 3
		image : 7
		nav-menu : 1
		text-editor : 1
		theme-site-logo : 1
	single : 1
		container : 3
		facebook-comments : 1
		post-comments : 1
		post-info : 1
		post-navigation : 1
		progress-tracker : 1
		share-buttons : 1
		text-editor : 1
		theme-post-content : 1
		theme-post-featured-image : 1
		theme-post-title : 1
		wp-widget-categories : 1
		wp-widget-category-posts : 1
	wp-post : 1
		container : 1
		text-editor : 2
	wp-page : 3
		container : 4
		heading : 2
		nav-menu : 1
		posts : 1
		search-form : 1
		text-editor : 5
	search-results : 1
		archive-posts : 1
		container : 3
		heading : 1
		nav-menu : 1
		search-form : 1
		text-editor : 1
	error-404 : 1
		button : 1
		container : 1
		image : 1
		text-editor : 4

== Ajustes ==
	
	cpt_support: post, page
	allow_tracking: yes
	editor_break_lines: 1
	unfiltered_files_upload: 1
	load_fa4_shim: yes

== Features ==
	Custom Fonts: 1
	Custom Icons: 0

== Integrations ==
	

== Experimentos de Elementor ==
	Salida del DOM optimizada: Activo
	Carga de recursos mejorada: Activo
	Carga de CSS mejorada: Activo
	Fuentes de iconos integradas: Activo
	Puntos de ruptura personalizados adicionales: Activo
	admin_menu_rearrangement: Inactivo por defecto
	Contenedor Flexbox: Activo
	Actualizar la librería Swiper: Activo por defecto
	Contenedor Grid: Activo por defecto
	Default to New Theme Builder: Activo por defecto
	Encabezado y pie de página del tema Hello: Activo
	Barra superior del editor: Inactivo por defecto
	Optimized Gutenberg Loading: Activo por defecto
	Build with AI: Inactivo por defecto
	Páginas de destino: Activo
	Elementos anidados: Activo
	Carga diferida de imágenes de fondo: Activo
	Optimize Image Loading: Activo por defecto
	Guía de estilo global: Activo por defecto
	Page Transitions: Activo por defecto
	Notes: Activo por defecto
	Form Submissions: Activo por defecto
	Scroll Snap: Activo por defecto
	Menu: Inactivo por defecto
	Taxonomy Filter: Inactivo por defecto

== Registro ==
	
Log: showing 20 of 312023-10-18 16:25:20 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Finished 
2023-10-18 16:25:20 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.17.0-dev3',
  'to' => '3.17.0-dev4',
)]
2023-10-25 19:11:20 [info] elementor-pro::elementor_pro_updater Started 
2023-10-25 19:11:20 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-10-25 19:11:20 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-10-25 19:11:20 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.15.0',
  'to' => '3.17.0',
)]
2023-10-25 19:11:20 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.15.0',
  'to' => '3.17.0',
)]
2023-10-25 19:11:21 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.15.0',
  'to' => '3.17.0',
)]
2023-10-28 09:02:25 [info] elementor::elementor_updater Started 
2023-10-28 09:02:25 [info] Elementor/Upgrades - _on_each_version Start  
2023-10-28 09:02:25 [info] Elementor/Upgrades - _on_each_version Finished 
2023-10-28 09:02:25 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Start  
2023-10-28 09:02:25 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Finished 
2023-10-28 09:02:25 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.17.0-dev4',
  'to' => '3.17.1',
)]
2023-10-28 09:02:25 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.17.0-dev4',
  'to' => '3.17.1',
)]
2023-11-14 05:47:43 [info] elementor::elementor_updater Started 
2023-11-14 05:47:43 [info] Elementor/Upgrades - _on_each_version Start  
2023-11-14 05:47:43 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.17.1',
  'to' => '3.18.0-dev1',
)]
2023-11-14 05:47:43 [info] Elementor/Upgrades - _on_each_version Finished 
2023-11-14 05:47:43 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.17.1',
  'to' => '3.18.0-dev1',
)]

PHP: showing 4 of 4PHP: 2023-10-25 19:29:50 [warning X 5][/home/u699801562/domains/ugocd.com/public_html/blog/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-10-25 20:31:57 [error X 2][/home/u699801562/domains/ugocd.com/public_html/blog/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::312] Uncaught Error: Call to a member function update_meta() on null in /home/u699801562/domains/ugocd.com/public_html/blog/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:312
Stack trace:
#0 /home/u699801562/domains/ugocd.com/public_html/blog/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(185): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions()
#2 /home/u699801562/domains/ugocd.com/public_html/blog/wp-content/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func()
#3 /home/u699801562/domains/ugocd.com/public_html/blog/wp-includes/class-wp-hook.php(310): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#4 /home/u699801562/domains/ugocd.com/public_html/blog/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters()
#5 /home/u699801562/domains/ugocd.com/public_html/blog/wp-includes/plugin.php(517): WP_Hook->do_action()
#6 /home/u699801562/domains/ugocd.com/public_html/blog/wp-admin/admin-ajax.php(188): do_action()
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-10-28 15:54:50 [warning X 1][/home/u699801562/domains/ugocd.com/public_html/blog/wp-content/plugins/elementor/core/page-assets/data-managers/font-icon-svg/font-awesome.php::50] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-11-14 06:14:11 [warning X 130][/home/u699801562/domains/ugocd.com/public_html/blog/wp-content/plugins/elementor-pro/modules/theme-builder/widgets/site-logo.php::192] Undefined array key "options" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 7 of 7JS: 2023-10-25 20:33:23 [error X 2][https://www.ugocd.com/blog/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.17.0-dev4:2:16880] Cannot read properties of undefined (reading 'attributes') 
JS: 2023-10-27 14:41:45 [error X 1][https://www.ugocd.com/blog/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.17.0-dev4:3:54034] Cannot read properties of undefined (reading 'activate') 
JS: 2023-10-28 10:38:27 [error X 1][https://www.ugocd.com/blog/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.17.1:3:632725] Cannot read properties of undefined (reading 'model') 
JS: 2023-10-28 16:16:20 [error X 1][https://www.ugocd.com/blog/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.17.1:3:805504] Cannot read properties of undefined (reading 'toLowerCase') 
JS: 2023-10-28 18:03:16 [error X 2][https://www.ugocd.com/blog/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.17.1:3:312727] Cannot read properties of undefined (reading 'id') 
JS: 2023-10-28 18:09:22 [error X 1][https://www.ugocd.com/blog/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.17.1:3:689408] this.model.isValidChild is not a function 
JS: 2023-10-31 11:37:07 [error X 6][https://www.ugocd.com/blog/wp-includes/js/jquery/jquery.min.js?ver=3.7.0:2:28722] Cannot read properties of undefined (reading 'value') 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibilidad no especificada

== Elementor Pro - Compatibility Tag ==

**Comment by jeremybourqui** [comment]
Its happened to me as well since the update "Updated plugin "Elementor" to version 3.18.0 from 3.17.3"

**Comment by inesgraphiste** [comment]
same here 👎

**Comment by d3cline** [comment]
Same, please do more testing before rolling out updates.

**Comment by foolstuck** [comment]
Same thing here. Any solutions?

**Comment by A1Allan** [comment]
I found a temporary workaround - turning off php error reporting. This isn't a solution, but if you need to make the errors go away so your business can function, it may be a good option for now while elementor investigates.

**Comment by jeremybourqui** [comment]
I got it working by downgrading the version back to 3.17.3, updating wordpress to 6.4.1 from 6.3.2 , and installing the update again.

**Comment by ramosol** [comment]
By chance does anyone found a solution please?

**Comment by AM1NT** [comment]
Same here. Downgrading from PHP 8.2 to 8.0 makes no difference.

**Comment by narnyworld** [comment]
> I got it working by downgrading the version back to 3.17.3, updating wordpress to 6.4.1 from 6.3.2 , and installing the update again.

I installed an update after installing wordpress 6.4.1 and still have the issue.

Temporary workaround:
exchange the logo in menu for an image of logo 🥵

**Comment by youradds** [comment]
Same issue. Any official fix?

**Comment by thegorilla** [comment]
To resolve this on one of my sites I did the following:

- Download the latest version of Elementor Pro from elementor.com

Then in my website:

- Deactivate Elementor Pro.
- Delete Elementor Pro Plugin.
- Upload Elementor Pro.
- Activate.

**Comment by rhnullah** [comment]
To resolve please update the elementor to latest v

**Comment by GianniNotari** [comment]
Must be something with cache or database.

Just change a tiny thing on all your pages, like add a space to a text, and then save. This solved not only the php error, but all the styling problems I had too.

**Comment by sulosp** [comment]
I was able to resolve this by rolling back to version elementor 3.17.3

**Comment by Malinowo** [comment]
What helped me was **updating the "Pro Elements" plugin** to version 3.18.1

**Comment by qrtgw** [comment]
Hi! To resolve this issue change the domein PHP to 7.4. It works for me!

**Comment by warbringer2015** [comment]
Found the issue, you have 2 elementors pro and normal, and for some reason if you update one in dashboard update won't show up the other one for update. So go plugins addons and update there the second one aswell.
Solved the problem for me.

**Comment by ikke-zelf** [comment]
I downloaded the 3.18.2 pro plugin from the website of elementor. installed that one over the 3.15.0 version (which wordpress indicated as latest available version) and that solved the issue.

**Comment by klecka** [comment]
> Hi! To resolve this issue change the domein **PHP to 7.4**. It works for me!

Same for me, but using end of life PHP versions doesn't feel like a fix

**Comment by MattrCoUk** [comment]
Her’s a dirty workaround as this error message was spamming my error log like mad. (I’ve run the latest Eliminator Pro on PHP 7.4)
 
– amended the method get_caption_source_options() in the site-logo.php


`private function get_caption_source_options() {
    $controls = $this->get_controls('caption_source');

    // Check if 'caption_source' control exists and if it has 'options' key
    if (isset($controls['options'])) {
        $caption_source_options = $controls['options'];

        // Remove the 'custom' key from the options
        unset($caption_source_options['custom']);

        return $caption_source_options;
    } else {
        // Handle the case where 'options' key does not exist
        // You can set a default value, log an error, or take appropriate action
        return array(); // Set a default value or handle accordingly
    }
}
`

**Comment by charvakanand** [comment]
@MattrCoUk 's solution worked for me. Much easier than up/down grading plugins, although I'm wondering if there will be any other issues because of this.

**Comment by MDFOYSALMap2u** [comment]
I am facing this error. Warning: Undefined array key 0 in C:\laragon\www\map2u\wp-content\plugins\elementor\core\page-assets\data-managers\font-icon-svg\font-awesome.php on line 19

**Comment by ezific** [comment]
I had this issue in Elementor Pro 3.7.7 (Elementor 3.22.1)
Here is a quick dirty plugin modification solution. Hopefully the Elementor team adds this or simlar so we can avoid plugin modification
`	private function get_caption_source_options() {
		$caption_source_options = $this->get_controls( 'caption_source' )['options'] ?? array();
		unset( $caption_source_options['custom'] );
		return $caption_source_options;
	}`

**Comment by imRichBrain** [comment]
🟩 : solution 

Just upgrade elementor pro to the latest version .
it will fix all the errors 

this error occures when elementor version is newer than elementor pro version .

**Comment by kouassikonan57** [comment]
Comment régler car je trouve la même erreur.

**Comment by imRichBrain** [comment]
> Comment régler car je trouve la même erreur.

just upgrade your Elementor pro to the latest version , it should works.

if version of elementor and elementor pro were latest version , those errors never occures .
