### ISSUE TITLE
The Post Navigation widget does not show arrows if the inline font icons Experiment is enabled.

### ISSUE THREAD

**Issue by vovkasolovev** [elementor/elementor#24367]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

The Post Navigation widget does not show arrows if the inline font icons Experiment is enabled.

### Steps to reproduce

1. Create post template. Add Post Navigation widget, select Show arrows. 
2. Enable inline font icons Experiment
3. Add some posts.
4. Check post page. 

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.5.23
	PHP Version: 7.4.33
	PHP Memory Limit: 1024M
	PHP Max Input Vars: 2000
	PHP Max Post Size: 4096M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.4.1
	Site URL: https://dobromore.eu
	Home URL: https://dobromore.eu
	WP Multisite: No
	Max Upload Size: 1 GB
	Memory limit: 40M
	Max Memory limit: 1024M
	Permalink Structure: /%category%/%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: yuli.nazarov.delft@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.9.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0

== Active Plugins ==
	Akismet Anti-spam: Spam Protection
		Version: 5.3
		Author: Automattic - Anti-spam Team

	Connect Polylang for Elementor
		Version: 2.4.3
		Author: Creame

	Contact Form 7
		Version: 5.8.3
		Author: Takayuki Miyoshi

	Cyr-To-Lat
		Version: 6.0.5
		Author: Sergey Biryukov, Mikhail Kobzarev, Igor Gergel

	Elementor
		Version: 3.17.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.17.1
		Author: Elementor.com

	Enable Media Replace
		Version: 4.1.4
		Author: ShortPixel

	Flamingo
		Version: 2.4
		Author: Takayuki Miyoshi

	JetEngine
		Version: 3.3.0
		Author: Crocoblock

	JetSearch
		Version: 3.1.3.1
		Author: Crocoblock

	Podhod.com
		Version: 2.11.23
		Author: Vladimir Solovev

	Polylang
		Version: 3.5.2
		Author: WP SYNTEX

	Polylang String Shortcode
		Version: 
		Author: 

	Solid Security Basic
		Version: 9.0.3
		Author: SolidWP

	User Switching
		Version: 1.7.0
		Author: John Blackbourn & contributors

	Yoast SEO
		Version: 21.5
		Author: Team Yoast

== Elements Usage ==
	
	archive : 5
		button : 1
		container : 11
		icon : 1
		jet-listing-grid : 3
		nav-menu : 5
		search-form : 1
		theme-archive-title : 2
	footer : 1
		container : 2
		heading : 2
		icon-list : 1
		social-icons : 1
	header : 1
		container : 3
		image : 1
		nav-menu : 5
		polylang-language-switcher : 1
		search-form : 1
		spacer : 1
	page : 1
		button : 9
		call-to-action : 4
		container : 35
		heading : 10
		icon-list : 1
		image : 4
		image-box : 12
		nav-menu : 1
		social-icons : 2
		testimonial : 3
		text-editor : 2
		video : 1
	single : 1
		container : 10
		google_maps : 1
		icon : 1
		jet-listing-dynamic-field : 11
		jet-listing-dynamic-image : 1
		jet-listing-dynamic-link : 1
		jet-listing-dynamic-repeater : 1
		share-buttons : 1
		theme-post-content : 1
	widget : 0
		image : 1
		jet-ajax-search : 1
		nav-menu : 1
		polylang-language-switcher : 1
	wp-page : 9
		button : 19
		call-to-action : 16
		container : 33
		heading : 13
		image : 2
		image-box : 7
		jet-listing-grid : 1
		loop-grid : 12
		shortcode : 1
		text-editor : 3
		video : 1
	single-post : 1
		container : 4
		jet-listing-dynamic-terms : 1
		post-info : 1
		post-navigation : 1
		theme-post-content : 1
		theme-post-featured-image : 1
		theme-post-title : 1
	single-page : 1
		container : 2
		theme-post-content : 1
		theme-post-title : 1
	loop-item : 4
		container : 4
		image-box : 3
		testimonial : 1
	jet-listing-items : 0
		container : 8
		jet-listing-dynamic-field : 6
		jet-listing-dynamic-image : 2
		jet-listing-dynamic-link : 2
		jet-listing-dynamic-terms : 1
		text-editor : 1
	error-404 : 1
		button : 1
		container : 1
		heading : 1

== Settings ==
	
	cpt_support: post, page
	disable_color_schemes: yes
	disable_typography_schemes: yes
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap

== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active by default
	Grid Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Editor Top Bar: Inactive by default
	Optimized Gutenberg Loading: Inactive by default
	Build with AI: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default
	Optimize Image Loading: Inactive by default
	Global Style Guide: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Menu: Inactive by default
	Taxonomy Filter: Inactive by default

== Log ==
	
PHP: showing 9 of 9PHP: 2023-07-23 12:46:09 [error X 2][/home/dobromor/public_html/wordpress/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::304] Uncaught Error: Call to a member function update_meta() on null in /home/dobromor/public_html/wordpress/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:304
Stack trace:
#0 /home/dobromor/public_html/wordpress/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(177): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(151, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/dobromor/public_html/wordpress/wp-content/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/dobromor/public_html/wordpress/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/dobromor/public_html/wordpress/wp-includes/class-wp-hook.php(332): WP_Ho [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-23 14:13:11 [notice X 1][/home/dobromor/public_html/wordpress/wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-02 19:24:09 [error X 1][/home/dobromor/public_html/wordpress/wp-content/plugins/elementor/core/wp-api.php::26] Uncaught Error: Call to undefined function Elementor\Core\get_plugins() in /home/dobromor/public_html/wordpress/wp-content/plugins/elementor/core/wp-api.php:26
Stack trace:
#0 /home/dobromor/public_html/wordpress/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(96): Elementor\Core\Wp_Api->get_plugins()
#1 /home/dobromor/public_html/wordpress/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(58): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_with_header()
#2 /home/dobromor/public_html/wordpress/wp-content/plugins/elementor/modules/compatibility-tag/module.php(57): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_to_check()
#3 /home/dobromor/public_html/wordpress/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(148): Elementor\Modules\CompatibilityTag\Module->get_plugins_to_check()
#4 /home/dobromor/public_html/wordpress/wp-includes/class-wp-hook.php(308): Elementor\Modules\CompatibilityTag\Base_Module->Elementor\Modules\C [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-01 13:08:31 [error X 7][/home/dobromor/public_html/wordpress/wp-content/plugins/elementor/core/wp-api.php::26] Uncaught Error: Call to undefined function Elementor\Core\get_plugins() in /home/dobromor/public_html/wordpress/wp-content/plugins/elementor/core/wp-api.php:26
Stack trace:
#0 /home/dobromor/public_html/wordpress/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(96): Elementor\Core\Wp_Api->get_plugins()
#1 /home/dobromor/public_html/wordpress/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(58): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_with_header()
#2 /home/dobromor/public_html/wordpress/wp-content/plugins/elementor/modules/compatibility-tag/module.php(57): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_to_check()
#3 /home/dobromor/public_html/wordpress/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(148): Elementor\Modules\CompatibilityTag\Module->get_plugins_to_check()
#4 /home/dobromor/public_html/wordpress/wp-includes/class-wp-hook.php(310): Elementor\Modules\CompatibilityTag\Base_Module->Elementor\Modules\C [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-17 09:14:16 [error X 2][/home/dobromor/public_html/wordpress/wp-content/plugins/elementor/includes/autoloader.php::294] require(): Failed opening required '/home/dobromor/public_html/wordpress/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php' (include_path='.:/opt/alt/php74/usr/share/pear') [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-11-14 00:04:28 [notice X 3][/home/dobromor/public_html/wp-content/plugins/elementor/includes/widgets/testimonial.php::432] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-11-14 09:22:02 [notice X 8][/home/dobromor/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined index: condition_type [array (
  'trace' => '
#0: /home/dobromor/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /home/dobromor/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /home/dobromor/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /home/dobromor/public_html/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2023-11-15 13:18:00 [error X 1][/home/dobromor/public_html/wp-content/plugins/elementor/core/wp-api.php::26] Uncaught Error: Call to undefined function Elementor\Core\get_plugins() in /home/dobromor/public_html/wp-content/plugins/elementor/core/wp-api.php:26
Stack trace:
#0 /home/dobromor/public_html/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(96): Elementor\Core\Wp_Api->get_plugins()
#1 /home/dobromor/public_html/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(58): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_with_header()
#2 /home/dobromor/public_html/wp-content/plugins/elementor/modules/compatibility-tag/module.php(57): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_to_check()
#3 /home/dobromor/public_html/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(148): Elementor\Modules\CompatibilityTag\Module->get_plugins_to_check()
#4 /home/dobromor/public_html/wp-includes/class-wp-hook.php(324): Elementor\Modules\CompatibilityTag\Base_Module->Elementor\Modules\CompatibilityTag\{closure}('')
#5 /home/dobromor/public_html/ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-11-21 12:32:22 [error X 1][/home/dobromor/public_html/wp-content/plugins/elementor/includes/autoloader.php::294] require(): Failed opening required '/home/dobromor/public_html/wp-content/plugins/elementor/core/kits/documents/kit.php' (include_path='.:/opt/alt/php74/usr/share/pear') [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 20 of 252023-08-26 09:42:16 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.14.1',
  'to' => '3.15.3',
)]
2023-09-03 11:18:44 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.14.1',
  'to' => '3.15.1',
)]
2023-09-03 11:18:45 [info] elementor-pro::elementor_pro_updater Started 
2023-09-03 11:18:45 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-09-03 11:18:45 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-09-03 11:18:45 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.14.1',
  'to' => '3.15.1',
)]
2023-11-01 21:30:07 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.15.1',
  'to' => '3.17.1',
)]
2023-11-01 21:30:08 [info] elementor-pro::elementor_pro_updater Started 
2023-11-01 21:30:08 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-11-01 21:30:08 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-11-01 21:30:08 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.15.1',
  'to' => '3.17.1',
)]
2023-11-01 21:31:05 [info] elementor::elementor_updater Started 
2023-11-01 21:31:05 [info] Elementor/Upgrades - _on_each_version Start  
2023-11-01 21:31:05 [info] Elementor/Upgrades - _on_each_version Finished 
2023-11-01 21:31:05 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.15.3',
  'to' => '3.17.2',
)]
2023-11-13 21:29:39 [info] elementor::elementor_updater Started 
2023-11-13 21:29:39 [info] Elementor/Upgrades - _on_each_version Start  
2023-11-13 21:29:40 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.17.2',
  'to' => '3.17.3',
)]
2023-11-13 21:29:41 [info] Elementor/Upgrades - _on_each_version Finished 
2023-11-13 21:29:41 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.17.2',
  'to' => '3.17.3',
)]

JS: showing 9 of 9JS: 2023-08-26 13:18:06 [error X 1][https://new.dobromore.eu/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view2641") has already been destroyed and cannot be used. 
JS: 2023-08-26 16:40:19 [error X 1][https://new.dobromore.eu/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view10532") has already been destroyed and cannot be used. 
JS: 2023-08-26 16:55:14 [error X 9][https://new.dobromore.eu/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.15.3:3:642692] Cannot read properties of undefined (reading 'isDesignable') 
JS: 2023-08-26 17:58:16 [error X 22][https://new.dobromore.eu/wp-content/plugins/elementor/assets/js/common-modules.min.js?ver=3.15.3:2:55595] Model.isValidChild() should be implemented, please provide 'isValidChild' functionality. 
JS: 2023-08-26 20:07:46 [error X 9][https://new.dobromore.eu/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.14.1:2:64105] Cannot convert undefined or null to object 
JS: 2023-08-26 20:12:08 [error X 24][https://new.dobromore.eu/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.15.3:2:12908] Cannot read properties of undefined (reading 'data') 
JS: 2023-09-02 17:38:57 [error X 1][https://new.dobromore.eu/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view5804") has already been destroyed and cannot be used. 
JS: 2023-09-02 17:38:57 [error X 1][https://new.dobromore.eu/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view5729") has already been destroyed and cannot be used. 
JS: 2023-09-02 19:57:14 [error X 6][https://new.dobromore.eu/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.15.3:3:620456] Cannot read properties of undefined (reading 'isEditable') 

== Elementor - Compatibility Tag ==
	
	Connect Polylang for Elementor: Compatibility not specified
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by wiesty** [comment]
Is there a fix yet?

**Comment by philrp** [comment]
This should be fixed.

But a workaround is to enable "Load Font Awesome 4 Support" under Settings > advanced. This loads some Js, not ideal, but...

**Comment by flaviuscalin** [comment]
Inline Font Icons is now moved to "Stable features" but is not stable at all. 
When enabled, several components don't display theyr Icons anymore. 

For the navigation arrows, enable "Load Font Awesome 4 Support" is a workaround. 
But we enable the Inline Font Icons to save font loading, and have to load another 150kb to fix it. 

There is no point. 

Inline Font Icons should be moved back to Experiments, or fixed. My guess is they will have to check every single Elementor widget that uses icons, in order to fix it. 

They make progress with loading speed, but they don't fix an immportant bug that spares lots of load time by eliminating fonts.

**Comment by SornyKonst** [comment]
+

**Comment by nicholaszein** [comment]
Hello there everyone!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro v3.30.0! 🥳 

Post Navigation widgets now render inline SVG icons when **Inline Font Icons** is active! 💪 

Thank you for your contribution! 🙏 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
