### ISSUE TITLE
After elementor pro update header and footer templates dissapeared and not showing in both front and backend of Hello theme

### ISSUE THREAD

**Issue by gerlod** [elementor/elementor#24394]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

After updating Elementor pro version lost all my header and footer templates. I am using the Hello theme. They do not show and when I go to the backend and open the footer or headers in elementor nothing is showing. It is as if all templates are suddenly empty. 

### Steps to reproduce

Updated my site twice (just after release of the upgrade and a week later after restore) but happened again. 
The second time I turned off all other plugins before installing, turned off the cache.
I went to WP Admin > Elementor > Tools to Regenerate Files & Data.
Deactivate features by going to WP Admin > Elementor > Settings > Features.
Turned plugins back on 
But with the templates looking as if they are empty ofcourse they will not reappear
As I did the update in the ghost site I also imported the templates from the main site but still nothing. 

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.5.23
	PHP Version: 8.2.12
	PHP Memory Limit: 512M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.4.1
	Site URL: https://golfclubheelsum.com
	Home URL: https://golfclubheelsum.com
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: nl-NL
	Timezone: Europe/Amsterdam
	Admin Email: info@internass.nl
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.9.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: nl_NL
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0

== Active Plugins ==
	DethemeKit for Elementor
		Version: 2.0.2
		Author: deTheme

	Elementor
		Version: 3.17.3
		Author: Elementor.com

	Elementor Header &amp; Footer Builder
		Version: 1.6.17
		Author: Brainstorm Force, Nikhil Chavan

	Elementor Pro
		Version: 3.17.1
		Author: Elementor.com

	ElementsKit Lite
		Version: 3.0.2
		Author: Wpmet

	Elfsight Weather CC
		Version: 1.3.1
		Author: Elfsight

	Envato Elements
		Version: 2.0.12
		Author: Envato

	Essential Addons for Elementor
		Version: 5.8.18
		Author: WPDeveloper

	MetForm
		Version: 3.8.0
		Author: Wpmet

	Skyboot Custom Icons for Elementor - Elementor Icons library
		Version: 1.0.7
		Author: Skybootstrap

	Sticky Header Effects for Elementor
		Version: 1.6.10
		Author: Rwattner

	Templately
		Version: 2.2.10
		Author: Templately

== Gebruik van elementen ==
	
	footer : 3
		button : 1
		container : 7
		heading : 4
		icon-list : 2
		image : 1
		nav-menu : 1
		social-icons : 1
		spacer : 1
	header : 3
		container : 3
		image : 1
		nav-menu : 1
	page : 60
		button : 211
		container : 30
		counter : 16
		divider : 33
		eael-content-ticker : 2
		elementskit-accordion : 2
		elementskit-blog-posts : 4
		elementskit-button : 5
		elementskit-heading : 4
		elementskit-team : 6
		elementskit-testimonial : 3
		google_maps : 3
		heading : 235
		hotspot : 6
		icon : 47
		icon-box : 6
		icon-list : 25
		image : 30
		image-box : 8
		media-carousel : 2
		metform : 2
		nav-menu : 3
		navigation-menu : 3
		post-info : 6
		posts : 4
		price-list : 4
		social-icons : 5
		spacer : 25
		tabs : 2
		testimonial-carousel : 2
		text-editor : 100
	section : 29
		button : 18
		divider : 2
		elementskit-header-search : 2
		heading : 68
		icon : 3
		icon-box : 3
		icon-list : 15
		image : 9
		mf-email : 1
		mf-text : 1
		mf-textarea : 1
		navigation-menu : 2
		post-comments : 1
		post-info : 3
		share-buttons : 1
		shortcode : 1
		social-icons : 1
		spacer : 6
		text-editor : 16
	wp-post : 187
		button : 63
		container : 66
		divider : 4
		elementskit-heading : 2
		heading : 42
		image : 29
		image-box : 1
		image-carousel : 3
		mf-button : 22
		mf-checkbox : 74
		mf-date : 52
		mf-email : 24
		mf-number : 32
		mf-radio : 24
		mf-telephone : 82
		mf-text : 222
		nav-menu : 2
		post-comments : 1
		post-info : 1
		post-navigation : 1
		posts : 4
		share-buttons : 4
		shortcode : 1
		spacer : 69
		text-editor : 111
		theme-post-title : 1
		video : 2
	wp-page : 113
		accordion : 3
		button : 83
		container : 55
		divider : 9
		eael-data-table : 8
		elementskit-accordion : 1
		elementskit-blog-posts : 2
		elementskit-button : 4
		elementskit-heading : 2
		form : 1
		google_maps : 2
		heading : 395
		hotspot : 19
		html : 4
		icon : 13
		icon-list : 26
		image : 62
		image-box : 8
		image-carousel : 1
		image-gallery : 1
		media-carousel : 2
		metform : 11
		post-info : 3
		posts : 37
		price-list : 8
		spacer : 150
		tabs : 4
		testimonial-carousel : 2
		text-editor : 177
		toggle : 2
		video : 1
	single-post : 3
		button : 2
		divider : 1
		heading : 2
		navigation-menu : 1
		post-comments : 1
		posts : 1
		share-buttons : 1
		text-editor : 2
		theme-post-title : 1
	loop-item : 3
		container : 1
		theme-post-featured-image : 1

== Instellingen ==
	
	cpt_support: post, page, e-landing-page, elementskit_content, elementor-hf
	disable_color_schemes: yes
	disable_typography_schemes: yes
	allow_tracking: yes
	unfiltered_files_upload: 1

== Eigenschappen ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	
	recaptcha: Active
	recaptcha_v3: Active

== Elementor experimenten ==
	Geoptimaliseerde DOM-uitvoer: Standaard actief
	Verbeterd laden van assets: Standaard actief
	Verbeterd laden van CSS: Standaard inactief
	Pictogrammen inline lettertype: Standaard inactief
	Extra aangepaste onderbrekingspunten: Standaard actief
	admin_menu_rearrangement: Standaard inactief
	Flexbox container: Standaard inactief
	Upgrade Swiper bibliotheek: Standaard inactief
	Raster container: Standaard inactief
	Default to New Theme Builder: Standaard actief
	Hello Theme header &amp; footer: Standaard inactief
	Editor top balk: Standaard inactief
	Geoptimaliseerd laden van Gutenberg: Standaard inactief
	Bouwen met AI: Standaard inactief
	Landingspagina&#039;s: Standaard actief
	Geneste elementen: Standaard inactief
	Lazy-load achtergrondafbeeldingen: Standaard inactief
	Afbeelding laden optimaliseren: Standaard inactief
	Globale stijlgids: Standaard inactief
	Page Transitions: Standaard actief
	Notes: Standaard actief
	Form Submissions: Standaard actief
	Scroll Snap: Standaard actief
	Menu: Standaard inactief
	Taxonomy Filter: Standaard inactief

== Log ==
	
Log: showing 20 of 362023-10-30 15:29:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.16.1',
  'to' => '3.17.0',
)]
2023-11-23 11:31:49 [info] elementor::elementor_updater Started 
2023-11-23 11:31:49 [info] Elementor/Upgrades - _on_each_version Start  
2023-11-23 11:31:50 [info] Elementor/Upgrades - _on_each_version Finished 
2023-11-23 11:31:50 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.17.1',
  'to' => '3.17.3',
)]
2023-11-23 11:31:50 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.17.1',
  'to' => '3.17.3',
)]
2023-11-23 11:34:10 [info] elementor-pro::elementor_pro_updater Started 
2023-11-23 11:34:10 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-11-23 11:34:10 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-11-23 11:34:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.17.0',
  'to' => '3.17.1',
)]
2023-11-23 11:34:10 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.17.0',
  'to' => '3.17.1',
)]
2023-11-23 11:34:11 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.17.0',
  'to' => '3.17.1',
)]
2023-11-23 12:35:31 [info] Uploading Kit:  [array (
  'kit_id' => 'undefined',
  'referrer' => 'local',
)]
2023-11-23 12:35:50 [info] Selected import runners: site-settings, plugins, templates, taxonomies, elementor-content, wp-content, elements-default-values 
2023-11-23 12:35:50 [info] Import runner completed: site-settings ✓ 
2023-11-23 12:35:50 [info] Import runner completed: plugins ✓ 
2023-11-23 12:36:20 [info] Import runner completed: templates ✓ 
2023-11-23 12:36:21 [info] Import runner completed: taxonomies ✓ 
2023-11-23 12:38:32 [info] Import runner completed: elementor-content ✓ 
2023-11-23 12:38:34 [info] Import runner completed: wp-content ✓ 

PHP: showing 7 of 7PHP: 2023-10-17 18:42:48 [notice X 36][/home/golfclubheelsum/public_html/wp-content/plugins/elementor/includes/elements/container.php::42] Creation of dynamic property Elementor\Includes\Elements\Container::$logical_dimensions_inline_start is deprecated [array (
  'trace' => '
#0: /home/golfclubheelsum/public_html/wp-content/plugins/elementor/includes/elements/container.php(42): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/golfclubheelsum/public_html/wp-content/plugins/elementor/includes/managers/elements.php(89): Elementor\Includes\Elements\Container -> __construct()
#2: /home/golfclubheelsum/public_html/wp-content/plugins/elementor/includes/base/element-base.php(361): Elementor\Elements_Manager -> create_element_instance()
#3: /home/golfclubheelsum/public_html/wp-content/plugins/elementor/includes/base/element-base.php(1480): Elementor\Element_Base -> add_child()
#4: /home/golfclubheelsum/public_html/wp-content/plugins/elementor/includes/base/element-base.php(300): Elementor\Element_Base -> init_children()
',
)]
PHP: 2023-10-17 18:42:48 [notice X 36][/home/golfclubheelsum/public_html/wp-content/plugins/elementor/includes/elements/container.php::43] Creation of dynamic property Elementor\Includes\Elements\Container::$logical_dimensions_inline_end is deprecated [array (
  'trace' => '
#0: /home/golfclubheelsum/public_html/wp-content/plugins/elementor/includes/elements/container.php(43): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/golfclubheelsum/public_html/wp-content/plugins/elementor/includes/managers/elements.php(89): Elementor\Includes\Elements\Container -> __construct()
#2: /home/golfclubheelsum/public_html/wp-content/plugins/elementor/includes/base/element-base.php(361): Elementor\Elements_Manager -> create_element_instance()
#3: /home/golfclubheelsum/public_html/wp-content/plugins/elementor/includes/base/element-base.php(1480): Elementor\Element_Base -> add_child()
#4: /home/golfclubheelsum/public_html/wp-content/plugins/elementor/includes/base/element-base.php(300): Elementor\Element_Base -> init_children()
',
)]
PHP: 2023-11-23 11:31:50 [notice X 9][/home/golfclubheelsum/public_html/wp-content/plugins/elementor/includes/elements/container.php::43] Creation of dynamic property Elementor\Includes\Elements\Container::$logical_dimensions_inline_end is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-11-23 11:34:30 [notice X 4][/home/golfclubheelsum/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php::228] hexdec(): Passing null to parameter #1 ($hex_string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-11-23 12:05:40 [warning X 2][/home/golfclubheelsum/public_html/wp-content/plugins/elementor/app/modules/import-export/module.php::753] Attempt to read property &quot;label&quot; on null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-11-23 12:36:20 [warning X 1][/home/golfclubheelsum/public_html/wp-content/plugins/elementor-pro/core/app/modules/import-export/runners/import/templates.php::103] Undefined array key &quot;conditions&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-11-23 12:38:34 [notice X 1][/home/golfclubheelsum/public_html/wp-content/plugins/elementor/core/utils/import-export/parsers/wxr-parser-simple-xml.php::53] Function libxml_disable_entity_loader() is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	DethemeKit for Elementor: Compatibiliteit niet gespecificeerd
	Elementor Header & Footer Builder: Compatibel
	Elementor Pro: Compatibel
	Envato Elements: Niet compatibel
	Essential Addons for Elementor: Compatibel
	Skyboot Custom Icons for Elementor - Elementor Icons library: Compatibiliteit niet gespecificeerd
	Sticky Header Effects for Elementor: Compatibiliteit niet gespecificeerd

== Elementor Pro - Compatibility Tag ==
	
	Elementor Header & Footer Builder: Compatibel
	Envato Elements: Niet compatibel
	Essential Addons for Elementor: Compatibel

**Comment by gerlod** [comment]
I just received automated wordpress mail that there is a problem with the header and footer Builder plugin. 
With the following error detail, I assume it is connected to the above:

E_ERROR caused by line number 195 file /home/golfclubheelsum/public_html/wp-content/plugins/header-footer-elementor/admin/class-hfe-admin.php. Foutmelding: Uncaught TypeError: Cannot access offset of type string on string in /home/golfclubheelsum/public_html/wp-content/plugins/header-footer-elementor/admin/class-hfe-admin.php:195
Stack trace:
#0 /home/golfclubheelsum/public_html/wp-content/plugins/header-footer-elementor/admin/class-hfe-admin.php(158): HFE_Admin->column_display_location_rules()
#1 /home/golfclubheelsum/public_html/wp-includes/class-wp-hook.php(324): HFE_Admin->column_content()
#2 /home/golfclubheelsum/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#3 /home/golfclubheelsum/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#4 /home/golfclubheelsum/public_html/wp-admin/includes/class-wp-posts-list-table.php(1398): do_action()
#5 /home/golfclubheelsum/public_html/wp-admin/includes/class-wp-list-table.php(1799): WP_Posts_List_Table->column_default()
#6 /home/golfclubheelsum/public_html/wp-admin/includes/class-wp-posts-list-table.php(1432): WP_List_Table->single_row_columns()
#7 /home/golfclubheelsum/public_html/wp-admin/includes/class-wp-posts-list-table.php(834): WP_Posts_List_Table->single_row()
#8 /home/golfclubheelsum/public_html/wp-admin/includes/class-wp-posts-list-table.php(810): WP_Posts_List_Table->_display_rows()
#9 /home/golfclubheelsum/public_html/wp-admin/includes/class-wp-list-table.php(1709): WP_Posts_List_Table->display_rows()
#10 /home/golfclubheelsum/public_html/wp-admin/includes/class-wp-list-table.php(1636): WP_List_Table->display_rows_or_placeholder()
#11 /home/golfclubheelsum/public_html/wp-admin/edit.php(503): WP_List_Table->display()
#12 {main}
  thrown


WordPress version 6.4.1
Active thema: Hello Elementor (versie 2.9.0) Current plugin: Elementor Header & Footer Builder (versie 1.6.17) PHP versie 8.2.12

**Comment by m1ga** [comment]
Why do you have `Elementor Header & Footer Builder` installed if you have Elementor Pro? You only need that for the free version and build your header/footer with the Pro builder.

**Comment by gerlod** [comment]
Thank you for your reply...I came to the same conclusion late last night..I deleted the plugin ThanksOp 24 nov. 2023 12:37 schreef Michael Gangolf ***@***.***>:
Why do you have Elementor Header & Footer Builder installed if you have Elementor Pro? You only need that for the free version and build your header/footer with the Pro builder.
