### ISSUE TITLE
Elementor: You can't start tabs before the end of the previous tabs "tabs_link_style". 

### ISSUE THREAD

**Issue by DaStanzel** [elementor/elementor#24449]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

After updating to Elementor 3.17 i encounter a critical error called: Elementor: You can't start tabs before the end of the previous tabs "tabs_link_style". 

### Steps to reproduce

Update Elementor 3.17

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release '38', Revision '3692a61' v5.7.35-38
	PHP Version: 7.4.33
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1500
	PHP Max Post Size: 32M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.4.1
	Site URL: https://www.woodchecker.com
	Home URL: https://www.woodchecker.com
	WP Multisite: No
	Max Upload Size: 32 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: de-DE
	Timezone: 0
	Admin Email: stefan.stanzel@woodchecker.com
	Debug Mode: Inactive

== Theme ==
	Name: The7
	Version: 10.10.1
	Author: Dream-Theme
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36

== Active Plugins ==
	3D FlipBook : Dflip Lite
		Version: 2.0.86
		Author: DearHive

	Beautiful taxonomy filter
		Version: 2.4.3
		Author: Jonathan de Jong

	Broken Link Checker
		Version: 2.2.3
		Author: WPMU DEV

	Classic Editor
		Version: 1.6.3
		Author: WordPress Contributors

	CoCart - Decoupling WooCommerce Made Easy
		Version: 3.9.0
		Author: Sébastien Dumont

	Contact Form 7
		Version: 5.8.3
		Author: Takayuki Miyoshi

	Custom Order Status for WooCommerce
		Version: 2.3.0
		Author: Tyche Softwares

	Disable &amp; Remove Google Fonts
		Version: 1.5.7
		Author: Fonts Plugin

	Elementor
		Version: 3.16.6
		Author: Elementor.com

	Elementor Pro
		Version: 3.17.1
		Author: Elementor.com

	Essential Addons for Elementor
		Version: 5.9
		Author: WPDeveloper

	EWWW Image Optimizer
		Version: 7.2.1
		Author: Exactly WWW

	Facebook for WooCommerce
		Version: 3.1.4
		Author: Facebook

	Flexible Shipping
		Version: 4.23.3
		Author: Octolize

	Google XML Sitemaps Generator
		Version: 1.7.2
		Author: WPGrim

	GTM4WP
		Version: 1.18.1
		Author: Thomas Geiger

	Import Export WordPress Users and WooCommerce Customers
		Version: 2.4.7
		Author: WebToffee

	Jetpack
		Version: 12.8.1
		Author: Automattic

	Judge.me Product Reviews for WooCommerce
		Version: 1.3.22
		Author: Judge.me

	Klarna Order Management for WooCommerce
		Version: 1.8.3
		Author: klarna, krokedil

	Klarna Payments for WooCommerce
		Version: 3.2.3
		Author: krokedil, klarna, automattic

	Members
		Version: 3.2.8
		Author: MemberPress

	NitroPack
		Version: 1.10.3
		Author: NitroPack Inc.

	Omnisend for Woocommerce
		Version: 1.13.10
		Author: Omnisend

	Order Delivery Date Pro for WooCommerce
		Version: 9.30.0
		Author: Tyche Softwares

	Order Export &amp; Order Import for WooCommerce
		Version: 2.4.2
		Author: WebToffee

	PDF Invoices &amp; Packing Slips for WooCommerce
		Version: 3.7.2
		Author: WP Overnight

	Piotnet Addons For Elementor
		Version: 2.4.25
		Author: Piotnet

	Premmerce Permalink Manager for WooCommerce
		Version: 2.3.10
		Author: Premmerce

	ReactPress
		Version: 3.2.0
		Author: Rockiger

	Redirection
		Version: 5.3.10
		Author: John Godley

	Search By SKU - for Woocommerce
		Version: 0.8.0
		Author: Unroll Digital

	The7 disable web fonts
		Version: 1.0.1
		Author: Dream Theme

	The7 Elements
		Version: 2.7.7
		Author: Dream-Theme

	UpdraftPlus - Backup/Restore
		Version: 2.23.13.26
		Author: UpdraftPlus.Com, DavidAnderson

	weLaunch Framework
		Version: 1.0.19
		Author: weLaunch.io

	WooCommerce
		Version: 8.3.1
		Author: Automattic

	WooCommerce Attribute Images
		Version: 1.3.2
		Author: weLaunch

	WooCommerce Google Feed Manager
		Version: 3.1.0
		Author: WP Marketing Robot

	WooCommerce PayPal Payments
		Version: 2.4.1
		Author: WooCommerce

	WooCommerce Stripe Gateway
		Version: 7.7.0
		Author: WooCommerce

	WooCommerce Zapier
		Version: 2.9.0
		Author: OM4 Software

	Woo Discount Rules
		Version: 2.6.2
		Author: Flycart

	Woo Discount Rules PRO 2.0
		Version: 2.5.4
		Author: Flycart

	WP HTML Mail - Email Template Designer
		Version: 3.4.5
		Author: Hannes Etzelstorfer // codemiq

	WP HTML Mail - WooCommerce
		Version: 2.9.15
		Author: Hannes Etzelstorfer // codemiq

	WP Mail Logging
		Version: 1.12.0
		Author: WP Mail Logging Team

	WP Rollback
		Version: 1.7.3
		Author: GiveWP.com

	Yoast SEO
		Version: 21.5
		Author: Team Yoast

	Yoast SEO Premium
		Version: 21.5
		Author: Team Yoast

== Must-Use Plugins ==
	WP Migrate DB Pro Compatibility
		Version: 1.2
		Author: Delicious Brains

== Features ==
	Custom Fonts: 2
	Custom Icons: 1

== Integrations ==
	
	recaptcha_v3: Active
	woocommerce: Active

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Inactive
	Inline Font Icons: Active
	Additional Custom Breakpoints: Inactive
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Upgrade Swiper Library: Inactive by default
	Grid Container: Inactive by default
	Default to New Theme Builder: Active by default
	Editor Top Bar: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Active
	Global Style Guide: Inactive by default
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Menu: Inactive by default
	Taxonomy Filter: Inactive by default

== Log ==
	
JS: showing 6 of 6JS: 2023-10-23 10:41:18 [error X 2][https://www.woodchecker.com/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.16.2:2:7835] Cannot read properties of null (reading &#039;config&#039;) 
JS: 2023-10-23 10:41:21 [error X 2][https://www.woodchecker.com/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.16.6:2:30930] Cannot read properties of undefined (reading &#039;model&#039;) 
JS: 2023-11-02 10:19:45 [error X 1][https://www.woodchecker.com/wp-includes/js/jquery/jquery.min.js?ver=3.7.0:2:28722] Cannot read properties of undefined (reading &#039;value&#039;) 
JS: 2023-11-02 10:19:57 [error X 46][https://www.woodchecker.com/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.16.6:3:14266] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got as `link` value. Expected array or object.',
)]
JS: 2023-11-24 08:51:33 [error X 1][https://www.woodchecker.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.16.6:3:639892] Cannot read properties of undefined (reading &#039;isDesignable&#039;) 
JS: 2023-11-27 06:22:11 [error X 1][https://www.woodchecker.com/wp-admin/post.php?post=65097&amp;action=elementor:1:4] Unexpected non-whitespace character after JSON at position 3 (line 1 column 4) 

Log: showing 20 of 242023-10-31 06:43:15 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.16.2',
  'to' => '3.17.0',
)]
2023-10-31 06:43:15 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.16.6',
  'to' => '3.17.1',
)]
2023-10-31 06:43:15 [info] elementor::elementor_updater Started 
2023-10-31 06:43:15 [info] Elementor/Upgrades - _on_each_version Start  
2023-10-31 06:43:15 [info] Elementor/Upgrades - _on_each_version Finished 
2023-10-31 06:43:15 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Start  
2023-10-31 06:43:15 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Finished 
2023-10-31 06:43:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.16.6',
  'to' => '3.17.1',
)]
2023-10-31 06:43:16 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.16.6',
  'to' => '3.17.1',
)]
2023-10-31 06:43:16 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.16.2',
  'to' => '3.17.0',
)]
2023-11-21 05:58:56 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.17.1',
  'to' => '3.17.3',
)]
2023-11-21 05:58:57 [info] elementor-pro::elementor_pro_updater Started 
2023-11-21 05:58:57 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-11-21 05:58:57 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-11-21 05:58:57 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.17.0',
  'to' => '3.17.1',
)]
2023-11-21 05:58:57 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.17.0',
  'to' => '3.17.1',
)]
2023-11-21 05:58:57 [info] elementor::elementor_updater Started 
2023-11-21 05:58:57 [info] Elementor/Upgrades - _on_each_version Start  
2023-11-21 05:58:57 [info] Elementor/Upgrades - _on_each_version Finished 
2023-11-21 05:58:57 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.17.1',
  'to' => '3.17.3',
)]

PHP: showing 12 of 12PHP: 2023-10-31 06:43:34 [notice X 1890][/html/wp-content/plugins/elementor-pro/modules/woocommerce/wc-templates/cart/mini-cart.php::186] Undefined index: has_door [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-11-02 10:52:09 [notice X 5][/html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-11-02 19:01:43 [notice X 8][/html/wp-content/plugins/elementor-pro/core/utils.php::373] Undefined index: name [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-11-02 19:12:46 [notice X 54][/html/wp-content/plugins/elementor-pro/modules/woocommerce/module.php::1435] Undefined index: pages [array (
  'trace' => '
#0: /html/wp-content/plugins/elementor-pro/modules/woocommerce/module.php(1435): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /html/wp-content/plugins/elementor-pro/modules/woocommerce/module.php(1426): ElementorPro\Modules\Woocommerce\Module -> add_system_status_data()
#2: /html/wp-includes/class-wp-hook.php(310): ElementorPro\Modules\Woocommerce\Module -> ElementorPro\Modules\Woocommerce\{closure}()
#3: /html/wp-includes/plugin.php(205): WP_Hook -> apply_filters()
#4: /html/wp-content/plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-system-status-v2-controller.php(1443): class type apply_filters()
',
)]
PHP: 2023-11-02 19:12:46 [warning X 54][/html/wp-content/plugins/elementor-pro/modules/woocommerce/module.php::1435] Invalid argument supplied for foreach() [array (
  'trace' => '
#0: /html/wp-content/plugins/elementor-pro/modules/woocommerce/module.php(1435): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /html/wp-content/plugins/elementor-pro/modules/woocommerce/module.php(1426): ElementorPro\Modules\Woocommerce\Module -> add_system_status_data()
#2: /html/wp-includes/class-wp-hook.php(310): ElementorPro\Modules\Woocommerce\Module -> ElementorPro\Modules\Woocommerce\{closure}()
#3: /html/wp-includes/plugin.php(205): WP_Hook -> apply_filters()
#4: /html/wp-content/plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-system-status-v2-controller.php(1443): class type apply_filters()
',
)]
PHP: 2023-11-08 08:27:18 [notice X 131][/html/wp-content/plugins/elementor-pro/modules/woocommerce/module.php::1435] Undefined index: pages [array (
  'trace' => '
#0: /html/wp-content/plugins/elementor-pro/modules/woocommerce/module.php(1435): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /html/wp-content/plugins/elementor-pro/modules/woocommerce/module.php(1426): ElementorPro\Modules\Woocommerce\Module -> add_system_status_data()
#2: /html/wp-includes/class-wp-hook.php(324): ElementorPro\Modules\Woocommerce\Module -> ElementorPro\Modules\Woocommerce\{closure}()
#3: /html/wp-includes/plugin.php(205): WP_Hook -> apply_filters()
#4: /html/wp-content/plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-system-status-v2-controller.php(1443): class type apply_filters()
',
)]
PHP: 2023-11-08 08:27:18 [warning X 131][/html/wp-content/plugins/elementor-pro/modules/woocommerce/module.php::1435] Invalid argument supplied for foreach() [array (
  'trace' => '
#0: /html/wp-content/plugins/elementor-pro/modules/woocommerce/module.php(1435): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /html/wp-content/plugins/elementor-pro/modules/woocommerce/module.php(1426): ElementorPro\Modules\Woocommerce\Module -> add_system_status_data()
#2: /html/wp-includes/class-wp-hook.php(324): ElementorPro\Modules\Woocommerce\Module -> ElementorPro\Modules\Woocommerce\{closure}()
#3: /html/wp-includes/plugin.php(205): WP_Hook -> apply_filters()
#4: /html/wp-content/plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-system-status-v2-controller.php(1443): class type apply_filters()
',
)]
PHP: 2023-11-21 07:25:51 [notice X 76][/html/wp-content/plugins/elementor-pro/modules/woocommerce/module.php::1435] Undefined index: pages [array (
  'trace' => '
#0: /html/wp-content/plugins/elementor-pro/modules/woocommerce/module.php(1435): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /html/wp-content/plugins/elementor-pro/modules/woocommerce/module.php(1426): ElementorPro\Modules\Woocommerce\Module -> add_system_status_data()
#2: /html/wp-includes/class-wp-hook.php(324): ElementorPro\Modules\Woocommerce\Module -> ElementorPro\Modules\Woocommerce\{closure}()
#3: /html/wp-includes/plugin.php(205): WP_Hook -> apply_filters()
#4: /html/wp-content/plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-system-status-v2-controller.php(1448): class type apply_filters()
',
)]
PHP: 2023-11-21 07:25:51 [warning X 76][/html/wp-content/plugins/elementor-pro/modules/woocommerce/module.php::1435] Invalid argument supplied for foreach() [array (
  'trace' => '
#0: /html/wp-content/plugins/elementor-pro/modules/woocommerce/module.php(1435): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /html/wp-content/plugins/elementor-pro/modules/woocommerce/module.php(1426): ElementorPro\Modules\Woocommerce\Module -> add_system_status_data()
#2: /html/wp-includes/class-wp-hook.php(324): ElementorPro\Modules\Woocommerce\Module -> ElementorPro\Modules\Woocommerce\{closure}()
#3: /html/wp-includes/plugin.php(205): WP_Hook -> apply_filters()
#4: /html/wp-content/plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-system-status-v2-controller.php(1448): class type apply_filters()
',
)]
PHP: 2023-11-27 08:29:07 [warning X 1][/html/wp-content/plugins/elementor/includes/db.php::267] Invalid argument supplied for foreach() [array (
  'trace' => '
#0: /html/wp-content/plugins/elementor/includes/db.php(267): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /html/wp-content/plugins/essential-addons-for-elementor-lite/includes/Classes/Bootstrap.php(314): Elementor\DB -> iterate_data()
#2: /html/wp-includes/class-wp-hook.php(326): Essential_Addons_Elementor\Classes\Bootstrap -> Essential_Addons_Elementor\Classes\{closure}()
#3: /html/wp-includes/plugin.php(205): WP_Hook -> apply_filters()
#4: /html/wp-content/plugins/elementor/core/base/document.php(749): class type apply_filters()
',
)]
PHP: 2023-11-27 11:21:05 [error X 4][/html/wp-content/plugins/elementor-pro/modules/screenshots/module.php::229] Uncaught WpOrg\Requests\Exception\Http\Status403: 403 Forbidden in /html/wp-content/plugins/elementor-pro/modules/screenshots/module.php:229
Stack trace:
#0 /html/wp-content/plugins/elementor-pro/modules/screenshots/module.php(264): ElementorPro\Modules\Screenshots\Module-&gt;is_screenshot_proxy_mode(Array)
#1 /html/wp-content/plugins/elementor/core/base/module.php(85): ElementorPro\Modules\Screenshots\Module-&gt;__construct()
#2 /html/wp-content/plugins/elementor-pro/core/modules-manager.php(90): Elementor\Core\Base\Module::instance()
#3 /html/wp-content/plugins/elementor-pro/plugin.php(369): ElementorPro\Core\Modules_Manager-&gt;__construct()
#4 /html/wp-includes/class-wp-hook.php(324): ElementorPro\Plugin-&gt;on_elementor_init(&#039;&#039;)
#5 /html/wp-includes/class-wp-hook.php(348): WP_Hook-&gt;apply_filters(&#039;&#039;, Array)
#6 /html/wp-includes/plugin.php(517): WP_Hook-&gt;do_action(Array)
#7 /html/wp-content/plugins/elementor/includes/plugin.php(658): do_action(&#039;elementor/init&#039;)
#8 /html/wp-includes/class-wp-hook.php(324): Elementor\Pl [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-11-28 06:52:27 [warning X 2][/html/wp-content/plugins/elementor-pro/modules/forms/fields/upload.php::308] Invalid argument supplied for foreach() [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	Essential Addons for Elementor: Compatibility not specified
	Piotnet Addons For Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by mehmetonline** [comment]
Hello, I'm having the same problem. Has a solution been found to this problem?

**Comment by araujo-maria** [comment]
Hello! I have the same problem. If someone finds a solution (apart from restoring backup), can you please let me know?

**Comment by knalleDK** [comment]
same here

**Comment by luckyduck** [comment]
Same happened here. Auto update even... Please Help!

**Comment by andrew-fcx** [comment]
Same issue here.

**Comment by laurent23** [comment]
Seems like this issue comes with the last update of the Elementor plugin. 
I solved this issue by rollingback to Version 16.0 of the Elementor plugin.
I disabled autoupdate for this plugin, but somehow the plugin autoupdates from time to time without my knowledge and i have to manually downgrade the plugin again. 

![elementor](https://github.com/elementor/elementor/assets/44318882/1d74f4ef-e2cd-42c9-b99f-e06f6058e4cc)

**Comment by Faabrisgro** [comment]
This solve the issue, thanks Laurent23.

I downloaded WP Rollback and downgraded elementor  to v 16.0.0
