### ISSUE TITLE
Laptop breakpoints width not changing

### ISSUE THREAD

**Issue by matthewmurdoch** [elementor/elementor#24544]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

![3474e0be-d3ab-4753-a218-5433fce09804](https://github.com/elementor/elementor/assets/14326452/352245fb-d933-4128-9162-f94ddf830a8a)
![ebb8ecfd-4c62-429a-98a9-1ea033e8ddd7](https://github.com/elementor/elementor/assets/14326452/7fb21a30-75fd-4d72-baf8-ea67e088503a)

### Steps to reproduce

1) Change to responsive view - change to laptop

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.54 (Debian)
	MySQL version: mariadb.org binary distribution v10.5.17
	PHP Version: 8.1.24
	PHP Memory Limit: 512M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.4.2
	Site URL: https://dev.radiantweb.co.za/waypoint
	Home URL: https://dev.radiantweb.co.za/waypoint
	WP Multisite: No
	Max Upload Size: 100 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /news/%postname%/
	Language: en-ZA
	Timezone: Africa/Johannesburg
	Admin Email: notify@radiantweb.digital
	Debug Mode: Inactive

== Theme ==
	Name: Waypoint Digital Child
	Version: 2.0.0.1689085805
	Author: radiantWEB
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.9.0
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_ZA
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0

== Active Plugins ==
	Better Search Replace
		Version: 1.4.3
		Author: WP Engine

	Duplicate Page
		Version: 4.5.3
		Author: mndpsingh287

	Elementor
		Version: 3.18.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.18.1
		Author: Elementor.com

	JetElements For Elementor
		Version: 2.6.14
		Author: Crocoblock

	JetEngine
		Version: 3.3.1
		Author: Crocoblock

	JetEngine - Custom visibility conditions
		Version: 1.1.2
		Author: Crocoblock

	JetSmartFilters
		Version: 3.2.4
		Author: Crocoblock

	ManageWP - Worker
		Version: 4.9.17
		Author: GoDaddy

	Rank Math SEO
		Version: 1.0.208.1
		Author: Rank Math

	Smart Slider 3 Pro
		Version: 3.5.1.21
		Author: Nextend

	User Profile Picture
		Version: 2.6.1
		Author: Cozmoslabs

	WordPress Importer
		Version: 0.8.1
		Author: wordpressdotorg

== Must-Use Plugins ==
	ManageWP - Worker Loader
		Version: 1.0.0
		Author: GoDaddy

== Elements Usage ==
	
	footer : 1
		form : 1
		heading : 14
		html : 1
		icon-list : 2
		jet-button : 1
		jet-listing-grid : 2
		shortcode : 10
		social-icons : 2
		text-editor : 16
	header : 1
		icon : 4
		image : 2
		theme-site-logo : 3
	popup : 2
		heading : 8
		html : 2
		icon : 6
		image : 1
		text-editor : 7
	wp-page : 9
		button : 18
		heading : 97
		image : 26
		jet-button : 51
		jet-listing-grid : 1
		jet-smart-filters-radio : 1
		lottie : 6
		spacer : 2
		text-editor : 82
	single-post : 3
		heading : 10
		image : 7
		text-editor : 5
		theme-post-content : 1
	jet-listing-items : 0
		heading : 1
		image : 2
		text-editor : 2

== Settings ==
	
	cpt_support: post, page
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap

== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	

== Elementor Experiments ==
	Optimised DOM Output: Active
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Additional Custom Breakpoints: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive
	Upgrade Swiper Library: Active by default
	Grid Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header &amp; Footer: Active by default
	Editor Top Bar: Inactive by default
	Optimized Gutenberg Loading: Active by default
	Build with AI: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default
	Optimize Image Loading: Active by default
	Global Style Guide: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Inactive
	Menu: Inactive by default
	Taxonomy Filter: Inactive by default

== Log ==
	
Log: showing 20 of 262023-12-05 07:59:38 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.17.3',
  'to' => '3.18.0',
)]
2023-12-05 07:59:48 [info] elementor::elementor_updater Started 
2023-12-05 07:59:48 [info] Elementor/Upgrades - _on_each_version Start  
2023-12-05 07:59:49 [info] Elementor/Upgrades - _on_each_version Finished 
2023-12-05 07:59:49 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.17.3',
  'to' => '3.18.0',
)]
2023-12-05 12:21:00 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.17.1',
  'to' => '3.18.0',
)]
2023-12-05 12:21:00 [info] elementor-pro::elementor_pro_updater Started 
2023-12-05 12:21:00 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-12-05 12:21:00 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-12-05 12:21:00 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.17.1',
  'to' => '3.18.0',
)]
2023-12-05 12:21:01 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.17.1',
  'to' => '3.18.0',
)]
2023-12-07 08:19:47 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.18.0',
  'to' => '3.18.1',
)]
2023-12-07 08:19:57 [info] elementor::elementor_updater Started 
2023-12-07 08:19:57 [info] Elementor/Upgrades - _on_each_version Start  
2023-12-07 08:19:57 [info] Elementor/Upgrades - _on_each_version Finished 
2023-12-07 08:19:57 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.18.0',
  'to' => '3.18.1',
)]
2023-12-07 08:39:43 [info] elementor-pro::elementor_pro_updater Started 
2023-12-07 08:39:43 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-12-07 08:39:43 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-12-07 08:39:43 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.18.0',
  'to' => '3.18.1',
)]

PHP: showing 6 of 6PHP: 2023-11-15 13:20:35 [notice X 342][/var/www/dev_radiantw_usr/data/www/dev.radiantweb.co.za/waypoint/wp-content/plugins/elementor-pro/modules/custom-css/module.php::76] trim(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-11-15 16:29:09 [warning X 6][/var/www/dev_radiantw_usr/data/www/dev.radiantweb.co.za/waypoint/wp-content/plugins/elementor/modules/history/revisions-manager.php::363] Undefined array key &quot;editor_post_id&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-11-27 14:42:24 [error X 1][/var/www/dev_radiantw_usr/data/www/dev.radiantweb.co.za/waypoint/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::312] Uncaught Error: Call to a member function update_meta() on null in /var/www/dev_radiantw_usr/data/www/dev.radiantweb.co.za/waypoint/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:312
Stack trace:
#0 /var/www/dev_radiantw_usr/data/www/dev.radiantweb.co.za/waypoint/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(185): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;save_conditions(2, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /var/www/dev_radiantw_usr/data/www/dev.radiantweb.co.za/waypoint/wp-content/plugins/elementor/core/common/modules/ajax/module.php(176): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /var/www/dev_radiantw_usr/data/www/dev.radiantweb.co.za/waypoint/wp-includes/class-wp-hook.php(324): Elementor\Core\Common\Modules\Ajax\Module-&gt;handle_ajax_request(&#039;&#039;)
#4 /var/www/dev_radiantw_usr/data/www/dev.radiantweb.co.za/waypoint/wp-includes/class-wp-hook.php(348): WP_Hook-&gt;apply_filters(NULL, Array)
#5 /var/www/dev_radiantw_usr/data/www/dev.radiantweb.co.za/waypoint/wp-includes/plugin.php(517): WP_Hook-&gt;do_action(Array)
#6 /var/www/dev_radiantw_usr/data/www/dev.radiantweb.co.za/waypoint/wp-admin/admin-ajax.php(188): do_action(&#039;wp_ajax_element...&#039;)
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-11-30 13:56:58 [warning X 17][/var/www/dev_radiantw_usr/data/www/dev.radiantweb.co.za/waypoint/wp-content/plugins/elementor-pro/modules/dynamic-tags/tags/post-featured-image.php::36] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-12-04 10:37:14 [warning X 1][/var/www/dev_radiantw_usr/data/www/dev.radiantweb.co.za/waypoint/wp-content/plugins/elementor/core/dynamic-tags/manager.php::73] Array to string conversion [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-12-05 07:59:49 [warning X 1][/var/www/dev_radiantw_usr/data/www/dev.radiantweb.co.za/waypoint/wp-content/plugins/elementor-pro/modules/theme-builder/widgets/site-logo.php::192] Undefined array key &quot;options&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 10 of 10JS: 2023-11-15 11:24:52 [error X 3][https://dev.radiantweb.co.za/waypoint/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.17.3:3:890462] Cannot read properties of undefined (reading &#039;route&#039;) 
JS: 2023-11-21 11:18:14 [error X 1][https://dev.radiantweb.co.za/waypoint/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view942&quot;) has already been destroyed and cannot be used. 
JS: 2023-11-21 11:18:14 [error X 1][https://dev.radiantweb.co.za/waypoint/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view1003&quot;) has already been destroyed and cannot be used. 
JS: 2023-11-21 11:18:14 [error X 1][https://dev.radiantweb.co.za/waypoint/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view1244&quot;) has already been destroyed and cannot be used. 
JS: 2023-11-21 12:07:37 [error X 5][https://dev.radiantweb.co.za/waypoint/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.17.3:3:806011] Cannot read properties of undefined (reading &#039;localized&#039;) 
JS: 2023-11-28 09:31:06 [error X 4][https://dev.radiantweb.co.za/waypoint/wp-admin/load-scripts.php?c=0&amp;loadchunk_0=jquery-core,jquery-migrate,utils,moxiejs,plupload&amp;ver=6.4.1:2:28760] Cannot read properties of undefined (reading &#039;value&#039;) 
JS: 2023-11-30 12:35:42 [error X 1][https://dev.radiantweb.co.za/waypoint/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.17.3:3:1112069] Cannot read properties of null (reading &#039;getBoundingClientRect&#039;) 
JS: 2023-12-08 10:18:10 [error X 6550][https://dev.radiantweb.co.za/waypoint/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:14799] Cannot read properties of null (reading &#039;clone&#039;) 
JS: 2023-12-08 10:18:11 [error X 229][https://dev.radiantweb.co.za/waypoint/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:19552] Cannot read properties of null (reading &#039;changestop&#039;) 
JS: 2023-12-08 10:42:13 [error X 1][https://dev.radiantweb.co.za/waypoint/wp-content/plugins/elementor/assets/js/responsive-bar.min.js?ver=3.18.1:2:5951] Cannot read properties of null (reading &#039;config&#039;) 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible
	JetElements For Elementor: Incompatible

== Elementor Pro - Compatibility Tag ==
	
	JetElements For Elementor: Incompatible

**Comment by matthewmurdoch** [comment]
Bump

**Comment by matthewmurdoch** [comment]
But the main problem we are facing [

https://github.com/elementor/elementor/assets/14326452/eceb9017-0545-4f35-a417-d82b65b67bf2

is I cannot adjust certain elements on the page.. without giving each element its own @media min max width.
So client is looking on his laptop saying "Elements not aligning correctly" - but i actually cannot edit it at all. as the editor wont allow me to to view it in that resolution and if i edit it in that given resolution - it changes for both 1366 and 1024... meaning 1 will be correct and 1 will be wrong
So the only solution i can think of.. is.. giving every element on the website a class and doing @media css and previewing it manually.

 at width, change that value to say 1366px, it will effect multiple breakpoints and when you swap back to that responsive view, value of width resets.

**Comment by AmityTek** [comment]
Hey,

i have the same issue with this website : https://www.alanage.be/
Breakpoint for mobile aren't loadings o_o ... 

Any idea why ?

Thanks
