### ISSUE TITLE
Reload Loop Grid on demand (not just pagination or infinite scroll)

### ISSUE THREAD

**Issue by mayurjobanputra** [elementor/elementor#24567]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

I'm using a loop grid + a form on my page. The form runs in Gravity with the "Post creation" addon. 

**What I want to do:** Refresh the loop grid on demand when I add a new post. Either trigger the refresh from Gravity or some other undocumented method.

**Current Workaround:** I have to configure Gravity forms to revisit the same page in order to see the new item I just added

### Steps to reproduce

1. Create a form that creates a post (custom or blog post)
2. Add a loop grid on the same page
3. Notice that the loop grid doesn't update after ajax form submit

### Expected behavior

Ability to trigger a loop grid update with some JS or an ajax call

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [ ] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.58 (Debian)
	MySQL version: mariadb.org binary distribution v10.4.20
	PHP Version: 7.4.33
	PHP Memory Limit: 512M
	PHP Max Input Vars: 2500
	PHP Max Post Size: 25M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.4.2
	Site URL: https://littlewinsapp.com
	Home URL: https://littlewinsapp.com
	WP Multisite: No
	Max Upload Size: 25 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /blog/%postname%/
	Language: en-US
	Timezone: America/Vancouver
	Admin Email: hello@mayur.ca
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.9.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 6.2.4
		Author: WP Engine

	Alphabetize Admin
		Version: 1.0
		Author: Mayur Jobanputra

	Classic Editor
		Version: 1.6.3
		Author: WordPress Contributors

	Default featured image
		Version: 1.7.3
		Author: Jan Willem Oostendorp

	Duplicate Page
		Version: 4.5.3
		Author: mndpsingh287

	Dynamic Visibility for Elementor
		Version: 5.0.10
		Author: Dynamic.ooo

	Elementor
		Version: 3.18.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.18.1
		Author: Elementor.com

	Essential Addons for Elementor
		Version: 5.9
		Author: WPDeveloper

	External links new tab - nofollow
		Version: 1.1.5
		Author: Vagelis P.

	Favicon by RealFaviconGenerator
		Version: 1.3.28
		Author: Philippe Bernard

	Featured Image Admin Thumb
		Version: 1.6
		Author: Sean Hayes

	Gravity Forms
		Version: 2.8.0
		Author: Gravity Forms

	Gravity Forms + Custom Post Types
		Version: 3.1.29
		Author: Gravity Wiz

	Gravity Forms Advanced Post Creation Add-On
		Version: 1.4.0
		Author: Gravity Forms

	Gravity Forms User Registration Add-On
		Version: 5.3.0
		Author: Gravity Forms

	MalCare WordPress Security Plugin - Malware Scanner, Cleaner, Security Firewall
		Version: 5.42
		Author: MalCare Security

	ManageWP - Worker
		Version: 4.9.17
		Author: GoDaddy

	Permalink Manager Lite
		Version: 2.4.1.6
		Author: Maciej Bis

	Simple add pages or posts
		Version: 2.0.0
		Author: Simon Dirlik, Ramon Fincken

	Simple Membership After Login Redirection
		Version: v1.6
		Author: smp7, wp.insider

	Simple Membership Form Shortcode
		Version: 1.1
		Author: wp.insider

	Simple Membership Google recaptcha
		Version: 2.0
		Author: smp7, wp.insider

	Simple WordPress Membership
		Version: 4.3.8
		Author: smp7, wp.insider

	Site Kit by Google
		Version: 1.115.0
		Author: Google

	User Role Editor
		Version: 4.64.1
		Author: Vladimir Garagulya

	W3 Total Cache
		Version: 2.6.1
		Author: BoldGrid

	WPCode Lite
		Version: 2.1.6
		Author: WPCode

	WP Mail SMTP
		Version: 3.10.0
		Author: WP Mail SMTP

	Yoast SEO
		Version: 21.6
		Author: Team Yoast


== Must-Use Plugins ==
	ManageWP - Worker Loader
		Version: 1.0.0
		Author: GoDaddy

	Object Cache Pro (MU)
		Version: 1.20.0
		Author: Rhubarb Group


== Elements Usage ==
	
	container : 9
		button : 4
		container : 24
		countdown : 1
		heading : 7
		html : 2
		icon : 9
		icon-list : 1
		image : 2
		lottie : 1
		price-table : 3
		slides : 1
		spacer : 8
		text-editor : 9
		toggle : 1
	footer : 1
		container : 4
		heading : 3
		social-icons : 1
		text-editor : 2
	header : 1
		button : 2
		container : 4
		heading : 1
		icon : 1
		lottie : 1
		nav-menu : 1
	page : 1
		container : 2
		form : 1
		heading : 1
		image : 1
		text-editor : 1
	popup : 5
		button : 2
		container : 6
		form : 1
		heading : 3
		image : 1
		nav-menu : 2
		spacer : 1
		text-editor : 2
	wp-page : 13
		container : 70
		eael-gravity-form : 3
		heading : 13
		html : 2
		icon : 1
		icon-list : 1
		login : 1
		loop-grid : 5
		posts : 1
		shortcode : 13
		spacer : 23
		tabs : 1
		text-editor : 26
		toggle : 2
	single-post : 2
		author-box : 1
		container : 12
		eael-gravity-form : 1
		icon : 1
		image : 1
		post-comments : 2
		post-info : 2
		shortcode : 2
		spacer : 14
		text-editor : 8
		theme-post-content : 2
		theme-post-title : 1
	single-page : 1
		container : 1
		theme-post-content : 1
	loop-item : 3
		container : 7
		post-info : 1
		shortcode : 1
		text-editor : 2
		theme-post-content : 1
		theme-post-title : 2
	error-404 : 1
		container : 1
		spacer : 1
		text-editor : 2


== Settings ==
	
	cpt_support: post, page
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	
	recaptcha: Active


== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Active by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active by default
	Upgrade Swiper Library: Active by default
	Grid Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header &amp; Footer: Active by default
	Editor Top Bar: Inactive by default
	Optimized Gutenberg Loading: Active by default
	Build with AI: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default
	Optimize Image Loading: Active by default
	Global Style Guide: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Menu: Inactive by default
	Taxonomy Filter: Inactive by default


== Log ==
	
JS: showing 20 of 23JS: 2023-12-05 04:34:31 [error X 1][https://littlewinsapp.com/wp-includes/js/jquery/jquery.min.js?ver=3.7.1:2:37833] Cannot create property &#039;guid&#039; on string &#039;c12190widgetsticky&#039; 
JS: 2023-12-05 04:35:02 [error X 1][https://littlewinsapp.com/wp-includes/js/jquery/jquery.min.js?ver=3.7.1:2:37833] Cannot create property &#039;guid&#039; on string &#039;c13124containersticky&#039; 
JS: 2023-12-05 04:35:02 [error X 1][https://littlewinsapp.com/wp-includes/js/jquery/jquery.min.js?ver=3.7.1:2:37833] Cannot create property &#039;guid&#039; on string &#039;c13133containersticky&#039; 
JS: 2023-12-05 04:35:02 [error X 1][https://littlewinsapp.com/wp-includes/js/jquery/jquery.min.js?ver=3.7.1:2:37833] Cannot create property &#039;guid&#039; on string &#039;c13142containersticky&#039; 
JS: 2023-12-05 04:35:02 [error X 1][https://littlewinsapp.com/wp-includes/js/jquery/jquery.min.js?ver=3.7.1:2:37833] Cannot create property &#039;guid&#039; on string &#039;c13123containersticky&#039; 
JS: 2023-12-05 04:35:02 [error X 1][https://littlewinsapp.com/wp-includes/js/jquery/jquery.min.js?ver=3.7.1:2:37833] Cannot create property &#039;guid&#039; on string &#039;c13154containersticky&#039; 
JS: 2023-12-05 04:35:02 [error X 1][https://littlewinsapp.com/wp-includes/js/jquery/jquery.min.js?ver=3.7.1:2:37833] Cannot create property &#039;guid&#039; on string &#039;c13125widgetsticky&#039; 
JS: 2023-12-05 04:35:02 [error X 1][https://littlewinsapp.com/wp-includes/js/jquery/jquery.min.js?ver=3.7.1:2:37833] Cannot create property &#039;guid&#039; on string &#039;c13128widgetsticky&#039; 
JS: 2023-12-05 04:35:02 [error X 1][https://littlewinsapp.com/wp-includes/js/jquery/jquery.min.js?ver=3.7.1:2:37833] Cannot create property &#039;guid&#039; on string &#039;c13134widgetsticky&#039; 
JS: 2023-12-05 04:35:02 [error X 22][https://littlewinsapp.com/wp-includes/js/jquery/jquery.min.js?ver=3.7.1:2:37833] Cannot create property &#039;guid&#039; on string &#039;c13137widgetsticky&#039; 
JS: 2023-12-05 04:35:02 [error X 1][https://littlewinsapp.com/wp-includes/js/jquery/jquery.min.js?ver=3.7.1:2:37833] Cannot create property &#039;guid&#039; on string &#039;c13143widgetsticky&#039; 
JS: 2023-12-05 04:35:02 [error X 1][https://littlewinsapp.com/wp-includes/js/jquery/jquery.min.js?ver=3.7.1:2:37833] Cannot create property &#039;guid&#039; on string &#039;c13146widgetsticky&#039; 
JS: 2023-12-05 04:35:02 [error X 1][https://littlewinsapp.com/wp-includes/js/jquery/jquery.min.js?ver=3.7.1:2:37833] Cannot create property &#039;guid&#039; on string &#039;c13155widgetsticky&#039; 
JS: 2023-12-05 04:35:02 [error X 1][https://littlewinsapp.com/wp-includes/js/jquery/jquery.min.js?ver=3.7.1:2:37833] Cannot create property &#039;guid&#039; on string &#039;c13158widgetsticky&#039; 
JS: 2023-12-05 04:40:15 [error X 27][https://littlewinsapp.com/wp-admin/load-scripts.php?c=0&amp;loadchunk_0=jquery-core,jquery-migrate,utils,moxiejs,plupload&amp;ver=6.4.1:2:28760] Cannot read properties of undefined (reading &#039;value&#039;) 
JS: 2023-12-07 23:04:19 [error X 6][https://littlewinsapp.com/wp-content/plugins/dynamic-visibility-for-elementor/assets/js/editor-dynamic-visibility.js?ver=5.0.10:77:19] dce_model_cid is not defined 
JS: 2023-12-07 23:55:11 [error X 15][https://littlewinsapp.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.18.1:3:625303] Cannot read properties of null (reading &#039;data&#039;) 
JS: 2023-12-09 19:32:16 [error X 1][https://littlewinsapp.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.18.2:3:690171] this.model.isValidChild is not a function 
JS: 2023-12-09 21:13:26 [error X 1][https://littlewinsapp.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.18.2:3:640760] Cannot read properties of undefined (reading &#039;isDesignable&#039;) 
JS: 2023-12-09 23:43:54 [error X 2][https://littlewinsapp.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.18.2:3:806906] Cannot read properties of undefined (reading &#039;localized&#039;) 

PHP: showing 4 of 4PHP: 2023-12-05 04:36:51 [notice X 19][/home/538237.cloudwaysapps.com/xtgqvkpxny/public_html/wp-content/plugins/elementor/modules/history/revisions-manager.php::363] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-12-06 22:53:19 [notice X 37][/home/538237.cloudwaysapps.com/xtgqvkpxny/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined index: condition_type [array (
  'trace' => '
#0: /home/538237.cloudwaysapps.com/xtgqvkpxny/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /home/538237.cloudwaysapps.com/xtgqvkpxny/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /home/538237.cloudwaysapps.com/xtgqvkpxny/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /home/538237.cloudwaysapps.com/xtgqvkpxny/public_html/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2023-12-07 02:10:43 [notice X 277][/home/538237.cloudwaysapps.com/xtgqvkpxny/public_html/wp-content/plugins/elementor-pro/modules/posts/skins/skin-content-base.php::265] Trying to get property &#039;ID&#039; of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-12-07 00:06:19 [error X 1][/home/538237.cloudwaysapps.com/xtgqvkpxny/public_html/wp-content/plugins/elementor-pro/modules/screenshots/module.php::229] Uncaught WpOrg\Requests\Exception\Http\Status403: 403 Forbidden in /home/538237.cloudwaysapps.com/xtgqvkpxny/public_html/wp-content/plugins/elementor-pro/modules/screenshots/module.php:229
Stack trace:
#0 /home/538237.cloudwaysapps.com/xtgqvkpxny/public_html/wp-content/plugins/elementor-pro/modules/screenshots/module.php(264): ElementorPro\Modules\Screenshots\Module-&gt;is_screenshot_proxy_mode()
#1 /home/538237.cloudwaysapps.com/xtgqvkpxny/public_html/wp-content/plugins/elementor/core/base/module.php(85): ElementorPro\Modules\Screenshots\Module-&gt;__construct()
#2 /home/538237.cloudwaysapps.com/xtgqvkpxny/public_html/wp-content/plugins/elementor-pro/core/modules-manager.php(91): Elementor\Core\Base\Module::instance()
#3 /home/538237.cloudwaysapps.com/xtgqvkpxny/public_html/wp-content/plugins/elementor-pro/plugin.php(375): ElementorPro\Core\Modules_Manager-&gt;__construct()
#4 /home/538237.cloudwaysapps.com/xtgqvkpxny/public_html/wp-includes/class-wp-hook.php(324): ElementorPro\Plugin-&gt;on_elementor_init()
#5 /home/53 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 15 of 152023-12-06 20:46:20 [info] elementor::elementor_updater Started 
2023-12-06 20:46:20 [info] Elementor/Upgrades - _on_each_version Start  
2023-12-06 20:46:20 [info] Elementor/Upgrades - _on_each_version Finished 
2023-12-06 20:46:20 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.18.0',
  'to' => '3.18.1',
)]
2023-12-06 20:46:20 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.18.0',
  'to' => '3.18.1',
)]
2023-12-06 21:51:52 [info] elementor-pro::elementor_pro_updater Started 
2023-12-06 21:51:52 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-12-06 21:51:52 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-12-06 21:51:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.18.0',
  'to' => '3.18.1',
)]
2023-12-06 21:51:52 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.18.0',
  'to' => '3.18.1',
)]
2023-12-09 10:51:30 [info] elementor::elementor_updater Started 
2023-12-09 10:51:31 [info] Elementor/Upgrades - _on_each_version Start  
2023-12-09 10:51:31 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.18.1',
  'to' => '3.18.2',
)]
2023-12-09 10:51:31 [info] Elementor/Upgrades - _on_each_version Finished 
2023-12-09 10:51:31 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.18.1',
  'to' => '3.18.2',
)]



== Elementor - Compatibility Tag ==
	
	Dynamic Visibility for Elementor: Compatibility not specified
	Elementor Pro: Compatibility not specified
	Essential Addons for Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by adxmeliora** [comment]
Literally scouring the internet for a solution to this EXACT problem :)

**Comment by hellodanevans** [comment]
Any luck with this guys? We have a custom query loading in post content but it only works when loading the page and we want to refresh it using ajax.

**Comment by hellodanevans** [comment]
Any luck with this guys? We are looking to reload the Loop Grid via ajax instead of a page reload when the user clicks #somehashlink.

**Comment by hellodanevans** [comment]
That’s really cool. Thanks for posting. We have someone working on an idea. Care to share your code?

Dan Evans
grb.uk.com
________________________________

**Comment by MohsenReyhani** [comment]
I thought Elemento already had this, but now I know I have to build the loop myself. :(
