### ISSUE TITLE
Semantic HTML Issue: Header widget gets duplicated when the the container is set to sticky.

### ISSUE THREAD

**Issue by Henzxon** [elementor/elementor#24622]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

When a container is set to sticky, the heading widget gets duplicated and the other item gets hidden.
<img width="331" alt="image" src="https://github.com/elementor/elementor/assets/102000469/a714992f-8ec4-44ed-95cb-e44e7941915a">

### Steps to reproduce

1. Create a container with two columns inside
2. Add a heading and text widget inside the first container
3. Set the first container to sticky to top
4. User SEO Meta-in-1-Click or Similar and it will report 2 heading 

### Expected behavior

I expect the widget to be as is with no duplicate. I don't know why this should happen on sticky containers. I tried disabling sticky container and that problem disappears. 

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [ ] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.39-42
	PHP Version: 7.4.33
	PHP Memory Limit: 768M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.4.2
	Site URL: https://btbperformance.com.au
	Home URL: https://btbperformance.com.au
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 256M
	Max Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: 
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 2.0.0
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.9.0
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Editor Tools
		Version: 5.9.2
		Author: Automattic

	Elementor
		Version: 3.18.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.18.2
		Author: Elementor.com

	Rank Math SEO
		Version: 1.0.209
		Author: Rank Math

	Security Optimizer
		Version: 1.4.9
		Author: SiteGround

	Smash Balloon Instagram Feed
		Version: 6.2.6
		Author: Smash Balloon

	Speed Optimizer
		Version: 7.4.5
		Author: SiteGround

	UpdraftPlus - Backup/Restore
		Version: 2.23.14.26
		Author: UpdraftPlus.Com, DavidAnderson

	Widgets for Google Reviews
		Version: 11.2.2
		Author: Trustindex.io <support@trustindex.io>


== Elements Usage ==
	
	archive : 1
		archive-posts : 1
		container : 2
		heading : 1
	container : 8
		button : 15
		container : 82
		divider : 2
		form : 1
		google_maps : 1
		heading : 56
		icon-list : 43
		image : 7
		image-carousel : 1
		nested-tabs : 1
		text-editor : 13
	footer : 1
		button : 2
		container : 6
		divider : 1
		heading : 4
		icon-list : 4
		image : 1
		nav-menu : 2
		shortcode : 1
		text-editor : 3
	header : 4
		button : 4
		container : 9
		html : 1
		icon : 1
		image : 2
		nav-menu : 3
		theme-site-logo : 2
	popup : 1
		button : 1
		container : 1
		icon : 1
		nav-menu : 1
	widget : 0
		form : 1
	wp-page : 7
		button : 28
		container : 113
		divider : 6
		form : 3
		google_maps : 1
		heading : 58
		html : 1
		icon-list : 20
		image : 18
		image-carousel : 2
		nested-tabs : 2
		shortcode : 2
		social-icons : 6
		template : 2
		text-editor : 54
	single-post : 1
		author-box : 1
		container : 5
		heading : 1
		post-comments : 1
		post-info : 1
		post-navigation : 1
		posts : 1
		progress-tracker : 1
		share-buttons : 1
		table-of-contents : 2
		text-editor : 1
		theme-post-content : 1
		theme-post-featured-image : 1
		theme-post-title : 1
	single-page : 1
		container : 1
		divider : 1
		heading : 1
		theme-post-content : 1
	search-results : 1
		archive-posts : 1
		container : 3
		heading : 1
		search-form : 1
	error-404 : 1
		button : 2
		container : 1
		heading : 2
		html : 1
		text-editor : 1


== Settings ==
	
	cpt_support: post, page
	disable_color_schemes: yes
	disable_typography_schemes: yes
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap
	disabled_elements: inner-section, video, spacer, image-box, icon-box, image-gallery, counter, progress, testimonial, alert, audio, menu-anchor, sidebar, read-more, rating, wp-widget-pages, wp-widget-calendar, wp-widget-archives, wp-widget-media_audio, wp-widget-media_image, wp-widget-media_gallery, wp-widget-media_video, wp-widget-meta, wp-widget-search, wp-widget-text, wp-widget-categories, wp-widget-recent-posts, wp-widget-recent-comments, wp-widget-rss, wp-widget-tag_cloud, wp-widget-nav_menu, wp-widget-custom_html, wp-widget-block, wp-widget-instagram-feed-widget, text-path, nested-accordion, theme-site-title, theme-page-title, theme-post-excerpt, theme-archive-title, loop-grid, loop-carousel, portfolio, gallery, login, slides, animated-headline, hotspot, price-list, price-table, flip-box, call-to-action, media-carousel, testimonial-carousel, reviews, countdown, sitemap, blockquote, facebook-button, facebook-comments, facebook-embed, facebook-page, lottie, code-highlight, video-playlist, paypal-button, stripe-button, nested-carousel


== Features ==
	Custom Fonts: 1
	Custom Icons: 0

== Integrations ==
	
	recaptcha_v3: Active


== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Inactive
	Inline Font Icons: Active by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active by default
	Upgrade Swiper Library: Active by default
	Grid Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Editor Top Bar: Inactive by default
	Optimized Gutenberg Loading: Active by default
	Build with AI: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Active
	Lazy Load Background Images: Inactive by default
	Optimize Image Loading: Active by default
	Global Style Guide: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Menu: Inactive by default
	Taxonomy Filter: Inactive by default


== Log ==
	
Log: showing 20 of 332023-12-07 04:37:53 [info] elementor-pro::elementor_pro_updater Started 
2023-12-07 04:37:53 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-12-07 04:37:53 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-12-07 04:37:53 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.17.1',
  'to' => '3.18.1',
)]
2023-12-07 04:37:53 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.17.1',
  'to' => '3.18.1',
)]
2023-12-09 03:17:28 [info] elementor::elementor_updater Started 
2023-12-09 03:17:28 [info] Elementor/Upgrades - _on_each_version Start  
2023-12-09 03:17:29 [info] Elementor/Upgrades - _on_each_version Finished 
2023-12-09 03:17:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.18.1',
  'to' => '3.18.2',
)]
2023-12-09 03:17:29 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.18.1',
  'to' => '3.18.2',
)]
2023-12-21 00:03:36 [info] elementor::elementor_updater Started 
2023-12-21 00:03:36 [info] Elementor/Upgrades - _on_each_version Start  
2023-12-21 00:03:37 [info] Elementor/Upgrades - _on_each_version Finished 
2023-12-21 00:03:37 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.18.2',
  'to' => '3.18.3',
)]
2023-12-21 00:03:37 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.18.2',
  'to' => '3.18.3',
)]
2023-12-21 00:32:12 [info] elementor-pro::elementor_pro_updater Started 
2023-12-21 00:32:12 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-12-21 00:32:12 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-12-21 00:32:12 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.18.1',
  'to' => '3.18.2',
)]
2023-12-21 00:32:12 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.18.1',
  'to' => '3.18.2',
)]

PHP: showing 5 of 5PHP: 2023-11-07 03:48:38 [notice X 3][/home/customer/www/shannonb138.sg-host.com/public_html/wp-content/plugins/elementor/includes/managers/image.php::113] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-11-07 03:49:26 [notice X 4][/home/customer/www/shannonb138.sg-host.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::179] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-11-08 00:12:21 [error X 1][/home/customer/www/shannonb138.sg-host.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::312] Uncaught Error: Call to a member function update_meta() on null in /home/customer/www/shannonb138.sg-host.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:312
Stack trace:
#0 /home/customer/www/shannonb138.sg-host.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(185): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(16, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/customer/www/shannonb138.sg-host.com/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(176): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/customer/www/shannonb138.sg-host.com/public_html/wp-includes/class-wp-hook.php(310): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/c [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-11-08 09:32:51 [notice X 5][/home/customer/www/shannonb138.sg-host.com/public_html/wp-content/plugins/elementor-pro/modules/posts/skins/skin-content-base.php::220] Trying to get property 'ID' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-12-07 05:15:19 [notice X 1][/home/customer/www/shannonb138.sg-host.com/public_html/wp-content/plugins/elementor/includes/elements/container.php::1849] Undefined index: size [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 5 of 5JS: 2023-11-07 04:02:55 [error X 42][https://shannonb138.sg-host.com/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.17.2:3:7470] Cannot read properties of null (reading 'editor') 
JS: 2023-11-07 04:21:58 [error X 170][https://shannonb138.sg-host.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.17.2:3:805504] Cannot read properties of undefined (reading 'toLowerCase') 
JS: 2023-11-07 04:35:29 [error X 2][https://shannonb138.sg-host.com/wp-admin/load-scripts.php?c=0&loadchunk_0=jquery-core,jquery-migrate,utils,moxiejs,plupload&ver=6.3.2:2:28722] Cannot read properties of undefined (reading 'value') 
JS: 2023-11-07 05:21:02 [error X 1][https://shannonb138.sg-host.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.17.2:3:601335] Cannot read properties of null (reading 'id') 
JS: 2023-11-08 00:12:09 [error X 21][https://shannonb138.sg-host.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.17.2:3:806011] Cannot read properties of undefined (reading 'localized') 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by dennismenken** [comment]
WTF. What have I gotten myself into? This is unbelievable. Is there at least a sensible workaround? I'm stunned. How can you just leave something like this as it is?
