### ISSUE TITLE
Two steps are shown at a time in a multi-step form when there is an error with image upload

### ISSUE THREAD

**Issue by thetypist** [elementor/elementor#24629]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

We are using a popup multi-step form. The form has 5 steps. One of the steps requires image uploading. If we upload the wrong image types, errors are shown when we try to submit the form. 

Then we are taken to the step where the error is produced. BUT at the bottom of the error step, previous step is also shown. 

Clicking on next button fixes the issue. Check the video for further clarification - https://www.loom.com/share/430613cf3079423cba9a62bd7e2742d4

### Steps to reproduce

Go to the website available in the loom video. 

Click on "Post a Job". In the file upload step, upload  files that are not images. Upload JSON or CSV. 
Then try to submit the form. You will the error step. Just below the error step, you will see previous step as well. 

Clicking on next button fixes the issue. 

### Expected behavior

Two steps should not be shown if an error is produced in any step.

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [ ] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.58 (Debian)
	MySQL version: mariadb.org binary distribution v10.4.20
	PHP Version: 7.4.33
	PHP Memory Limit: 1024M
	PHP Max Input Vars: 2500
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.4.2
	Site URL: https://toptradies.co.uk
	Home URL: https://toptradies.co.uk
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 40M
	Max Memory limit: 1024M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: support@toptradies.co.uk
	Debug Mode: Inactive

== Theme ==
	Name: Top Tradies
	Version: 1.1
	Author: Kristifor Pirkovikj
	Child Theme: Yes
	Parent Theme Name: Listingpro
	Parent Theme Version: 2.7.2
	Parent Theme Author: Team of CridioStudio

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 6.2.4
		Author: WP Engine

	Code Snippets
		Version: 3.6.2
		Author: Code Snippets Pro

	Colorlib Login Customizer
		Version: 1.3.1
		Author: Colorlib

	Elementor
		Version: 3.18.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.18.2
		Author: Elementor.com

	Email Templates
		Version: 1.4.3
		Author: wpexpertsio

	Flexible Checkout Fields
		Version: 3.5.18
		Author: WP Desk

	FluentSMTP
		Version: 2.2.6
		Author: FluentSMTP & WPManageNinja Team

	Front End PM PRO
		Version: 11.4.3
		Author: Shamim Hasan

	Insert PHP Code Snippet
		Version: 1.3.4
		Author: xyzscripts.com

	JetEngine
		Version: 3.3.2.1
		Author: Crocoblock

	JetSmartFilters
		Version: 3.3.0
		Author: Crocoblock

	ListingPro Ads
		Version: 1.3
		Author: CridioStudio (Dev Team)

	ListingPro Plugin
		Version: 2.7.2
		Author: CridioStudio (Dev Team)

	ListingPro Reviews
		Version: 1.4
		Author: CridioStudio (Dev Team)

	Login or Logout Menu Item
		Version: 1.2.3
		Author: cartpauj

	Payment Plugins for Stripe WooCommerce
		Version: 3.3.54
		Author: Payment Plugins, support@paymentplugins.com

	Permalink Manager Lite
		Version: 2.4.1.6
		Author: Maciej Bis

	Redux Framework
		Version: 4.4.11
		Author: Team Redux

	reSmush.it Image Optimizer
		Version: 0.4.13
		Author: reSmush.it

	TopTradies
		Version: 1.0
		Author: Nur Hossain

	User Menus
		Version: 1.3.2
		Author: Code Atlantic

	WebP Express
		Version: 0.25.8
		Author: Bjørn Rosell

	WooCommerce
		Version: 8.4.0
		Author: Automattic

	WP Redis
		Version: 1.4.4
		Author: Pantheon, Josh Koenig, Matthew Boynes, Daniel Bachhuber, Alley Interactive

	WP Rocket
		Version: 3.15.6
		Author: WP Media

	Yoast SEO
		Version: 21.7
		Author: Team Yoast

	Yoast SEO Premium
		Version: 21.7
		Author: Team Yoast


== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	
	woocommerce: Active


== Elementor Experiments ==
	Optimized DOM Output: Inactive
	Improved Asset Loading: Inactive
	Improved CSS Loading: Inactive
	Inline Font Icons: Inactive by default
	Additional Custom Breakpoints: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Inactive
	Grid Container: Active
	Default to New Theme Builder: Inactive
	Editor Top Bar: Inactive by default
	Optimized Gutenberg Loading: Inactive
	Build with AI: Inactive by default
	Landing Pages: Inactive
	Nested Elements: Inactive
	Lazy Load Background Images: Inactive
	Optimize Image Loading: Inactive
	Global Style Guide: Inactive
	Page Transitions: Inactive
	Notes: Inactive
	Form Submissions: Active
	Scroll Snap: Inactive
	Menu: Inactive by default
	Taxonomy Filter: Inactive by default


== Log ==
	
Log: showing 20 of 252023-12-07 09:52:54 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-12-07 09:52:54 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-12-07 09:52:54 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.18.0',
  'to' => '3.18.1',
)]
2023-12-08 17:49:40 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.18.1',
  'to' => '3.18.2',
)]
2023-12-08 17:59:29 [info] elementor::elementor_updater Started 
2023-12-08 17:59:29 [info] Elementor/Upgrades - _on_each_version Start  
2023-12-08 17:59:29 [info] Elementor/Upgrades - _on_each_version Finished 
2023-12-08 17:59:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.18.1',
  'to' => '3.18.2',
)]
2023-12-21 04:37:52 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.18.2',
  'to' => '3.18.3',
)]
2023-12-21 04:37:52 [info] elementor::elementor_updater Started 
2023-12-21 04:37:52 [info] Elementor/Upgrades - _on_each_version Start  
2023-12-21 04:37:52 [info] Elementor/Upgrades - _on_each_version Finished 
2023-12-21 04:37:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.18.2',
  'to' => '3.18.3',
)]
2023-12-21 04:37:54 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.18.2',
  'to' => '3.18.3',
)]
2023-12-21 04:38:09 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.18.1',
  'to' => '3.18.2',
)]
2023-12-21 04:38:10 [info] elementor-pro::elementor_pro_updater Started 
2023-12-21 04:38:10 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-12-21 04:38:10 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-12-21 04:38:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.18.1',
  'to' => '3.18.2',
)]
2023-12-21 04:38:11 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.18.1',
  'to' => '3.18.2',
)]

PHP: showing 6 of 6PHP: 2023-12-07 09:52:45 [error X 2][/home/491197.cloudwaysapps.com/euvaajssgm/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::200] Uncaught Error: Class &#039;\ElementorPro\Modules\ThemeBuilder\Conditions\General&#039; not found in /home/491197.cloudwaysapps.com/euvaajssgm/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:200
Stack trace:
#0 /home/491197.cloudwaysapps.com/euvaajssgm/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(282): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;register_condition()
#1 /home/491197.cloudwaysapps.com/euvaajssgm/public_html/wp-includes/class-wp-hook.php(324): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;register_conditions()
#2 /home/491197.cloudwaysapps.com/euvaajssgm/public_html/wp-includes/class-wp-hook.php(348): WP_Hook-&gt;apply_filters()
#3 /home/491197.cloudwaysapps.com/euvaajssgm/public_html/wp-includes/plugin.php(517): WP_Hook-&gt;do_action()
#4 /home/491197.cloudwaysapps.com/euvaajssgm/public_html/wp-settings.php(665): do_action()
#5 /home/491197.cloudwaysapps.com/euvaajssgm/public [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-12-13 07:11:06 [notice X 1983][/home/491197.cloudwaysapps.com/euvaajssgm/public_html/wp-content/plugins/elementor-pro/modules/woocommerce/widgets/checkout.php::4103] Undefined index: coupon_section_display [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-12-20 13:21:40 [notice X 7][/home/491197.cloudwaysapps.com/euvaajssgm/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php::1459] Undefined index: _flex_size_tablet [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-12-20 17:02:57 [notice X 6][/home/491197.cloudwaysapps.com/euvaajssgm/public_html/wp-content/plugins/elementor-pro/modules/woocommerce/widgets/checkout.php::4103] Undefined index: coupon_section_display [array (
  'trace' => '
#0: /home/491197.cloudwaysapps.com/euvaajssgm/public_html/wp-content/plugins/elementor-pro/modules/woocommerce/widgets/checkout.php(4103): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/491197.cloudwaysapps.com/euvaajssgm/public_html/wp-content/plugins/elementor-pro/modules/woocommerce/widgets/checkout.php(4197): ElementorPro\Modules\Woocommerce\Widgets\Checkout -> should_render_coupon()
#2: /home/491197.cloudwaysapps.com/euvaajssgm/public_html/wp-includes/class-wp-hook.php(324): ElementorPro\Modules\Woocommerce\Widgets\Checkout -> woocommerce_checkout_order_review()
#3: /home/491197.cloudwaysapps.com/euvaajssgm/public_html/wp-includes/class-wp-hook.php(348): WP_Hook -> apply_filters()
#4: /home/491197.cloudwaysapps.com/euvaajssgm/public_html/wp-includes/plugin.php(517): WP_Hook -> do_action()
',
)]
PHP: 2023-12-21 04:37:54 [error X 1][/home/491197.cloudwaysapps.com/euvaajssgm/public_html/wp-content/plugins/elementor/core/base/module.php::331] Uncaught Error: Class &#039;ElementorPro\Modules\GlobalWidget\Widgets\Global_Widget&#039; not found in /home/491197.cloudwaysapps.com/euvaajssgm/public_html/wp-content/plugins/elementor/core/base/module.php:331
Stack trace:
#0 /home/491197.cloudwaysapps.com/euvaajssgm/public_html/wp-includes/class-wp-hook.php(324): Elementor\Core\Base\Module-&gt;init_widgets()
#1 /home/491197.cloudwaysapps.com/euvaajssgm/public_html/wp-includes/class-wp-hook.php(348): WP_Hook-&gt;apply_filters()
#2 /home/491197.cloudwaysapps.com/euvaajssgm/public_html/wp-includes/plugin.php(517): WP_Hook-&gt;do_action()
#3 /home/491197.cloudwaysapps.com/euvaajssgm/public_html/wp-content/plugins/elementor/includes/managers/widgets.php(139): do_action()
#4 /home/491197.cloudwaysapps.com/euvaajssgm/public_html/wp-content/plugins/elementor/includes/managers/widgets.php(342): Elementor\Widgets_Manager-&gt;init_widgets()
#5 /home/491197.cloudwaysapps.com/euvaajssgm/public_html/wp-content/plugins/elementor/includes/managers/elements.php(74): Elementor\Widgets_Manager-&gt;ge [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-12-21 04:37:54 [error X 1][/home/491197.cloudwaysapps.com/euvaajssgm/public_html/wp-content/plugins/elementor-pro/plugin.php::375] Uncaught Error: Class &#039;ElementorPro\Core\Modules_Manager&#039; not found in /home/491197.cloudwaysapps.com/euvaajssgm/public_html/wp-content/plugins/elementor-pro/plugin.php:375
Stack trace:
#0 /home/491197.cloudwaysapps.com/euvaajssgm/public_html/wp-includes/class-wp-hook.php(324): ElementorPro\Plugin-&gt;on_elementor_init()
#1 /home/491197.cloudwaysapps.com/euvaajssgm/public_html/wp-includes/class-wp-hook.php(348): WP_Hook-&gt;apply_filters()
#2 /home/491197.cloudwaysapps.com/euvaajssgm/public_html/wp-includes/plugin.php(517): WP_Hook-&gt;do_action()
#3 /home/491197.cloudwaysapps.com/euvaajssgm/public_html/wp-content/plugins/elementor/includes/plugin.php(658): do_action()
#4 /home/491197.cloudwaysapps.com/euvaajssgm/public_html/wp-includes/class-wp-hook.php(324): Elementor\Plugin-&gt;init()
#5 /home/491197.cloudwaysapps.com/euvaajssgm/public_html/wp-includes/class-wp-hook.php(348): WP_Hook-&gt;apply_filters()
#6 /home/491197.cloudwaysapps.com/euvaajssgm/public_html/wp-includes/plugin.php(517): WP_Hook-&gt;do_action()
#7 /home/491 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 11 of 11JS: 2023-12-13 06:02:34 [error X 4][https://toptradies.co.uk/wp-includes/js/jquery/jquery.js?ver=3.7.1:3793:3] Cannot read properties of undefined (reading &#039;value&#039;) 
JS: 2023-12-13 07:10:24 [error X 1][https://toptradies.co.uk/wp-content/plugins/elementor/assets/js/editor.js?ver=3.18.2:31566:31] Cannot read properties of undefined (reading &#039;isDesignable&#039;) 
JS: 2023-12-16 06:28:15 [error X 1][https://toptradies.co.uk/wp-admin/post.php?post=14871&amp;action=elementor:6:39] Cannot read properties of undefined (reading &#039;needHelpUrl&#039;) 
JS: 2023-12-16 07:10:24 [error X 1][https://toptradies.co.uk/wp-content/plugins/elementor/assets/js/editor.js?ver=3.18.2:14455:26] Cannot read properties of undefined (reading &#039;css&#039;) 
JS: 2023-12-16 13:25:01 [error X 3][https://toptradies.co.uk/wp-includes/js/jquery/jquery.js?ver=3.7.1:3793:3] Syntax error, unrecognized expression: #038;settings-updated=true 
JS: 2023-12-16 13:25:01 [error X 3][https://toptradies.co.uk/wp-includes/js/jquery/jquery.js?ver=3.7.1:3793:3] elementorAdmin is not defined 
JS: 2023-12-17 18:10:52 [error X 1][https://toptradies.co.uk/wp-content/plugins/elementor-pro/assets/js/frontend.js?ver=3.18.1:1281:19] this.$element.sticky is not a function 
JS: 2023-12-18 04:46:10 [error X 2][https://toptradies.co.uk/wp-content/plugins/elementor/assets/js/frontend-modules.js?ver=3.18.2:838:31] Cannot read properties of undefined (reading &#039;attributes&#039;) 
JS: 2023-12-20 10:51:43 [error X 4][https://toptradies.co.uk/wp-content/plugins/elementor-pro/assets/js/preloaded-elements-handlers.min.js?ver=3.18.1:3:41572] Cannot read properties of undefined (reading &#039;match&#039;) 
JS: 2023-12-21 04:58:24 [error X 4][https://toptradies.co.uk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.18.3:3:806846] Cannot read properties of undefined (reading &#039;localized&#039;) 
JS: 2023-12-21 09:16:34 [error X 1][https://toptradies.co.uk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.18.3:3:690111] this.model.isValidChild is not a function 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by dmytropetrash** [comment]
Hi there! Thanks for reporting this issue with the multi-step form showing two steps at once when there's an image upload error. To help troubleshoot, I recommend first clearing your browser cache and disabling any conflicting plugins to rule out conflicts. Additionally, please try reproducing the error in a staging environment with the latest version of Elementor and WordPress. If the problem persists, could you provide steps to replicate the issue along with any console errors? This info will help us pinpoint the cause and work on a fix. Looking forward to your update!
