### ISSUE TITLE
Background images not on AJAX call on Load more Button Click

### ISSUE THREAD

**Issue by JatinZindex** [elementor/elementor#24701]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

"NOTE: I am aware that Elementor offers the 'Load More' feature, but I chose not to use it because I wanted to implement both post filtering and the 'Load More' button for the same loop grid template. Elementor doesn't support both functionalities simultaneously – 'Load More' and post filtering. Using Elementor's 'Load More' interferes with the filtering functionality, hence the reason for creating a custom 'Load More' button."

"I initially utilized the loop grid Elementor widget to showcase the initial six posts when the page loads. Subsequently, I incorporated a Button Widget labeled 'Load More' to retrieve additional posts upon clicking. Additionally, I've integrated an option for filtering posts within this layout."

Below Image indicates that i have filtering option in my layout.
![filter](https://github.com/elementor/elementor/assets/155709577/9b732a82-60c8-4681-960b-d35d5d4edc8b)

Below image indicates that i make button with Load More name.
![load](https://github.com/elementor/elementor/assets/155709577/bfe06e3b-443f-43a4-8339-4b65d1f2b080)

Below image indicates that background images not displaying on click of load more button.
![posts](https://github.com/elementor/elementor/assets/155709577/06f15663-a09c-4c8e-aa54-48a441133b32)

The problem lies in the fact that, upon the initial page load, the first six posts display correctly. However, when clicking the 'Load More' button, triggering an AJAX call to fetch additional posts, all the data is retrieved, but the background images fail to display. Similarly, when filtering through the dropdown options, the posts are successfully filtered, but the background images do not appear. All other data, apart from the background images, is being displayed as expected.

This is my AJAX and Filtering Code
![case](https://github.com/elementor/elementor/assets/155709577/541aa3c7-5873-4011-a456-ce0249b0ef2f)

This is my functions.php file code to get content of posts
![case-function](https://github.com/elementor/elementor/assets/155709577/a061663c-6fe8-42df-8f15-a5be81bae035)

In this function, I utilize the Elementor loop template shortcode as the content for posts. While all the data is successfully displayed, the issue arises as background images fail to appear.

![image](https://github.com/elementor/elementor/assets/155709577/138e733c-def6-4ff2-8019-dcadd6415f4f)
I use this elementor loop template short code in my function to get content of posts in while loop.

In conclusion, my primary concern is that background images fail to display when triggering the 'Load More' button or when applying filters to the posts.

### Steps to reproduce

"NOTE: I am aware that Elementor offers the 'Load More' feature, but I chose not to use it because I wanted to implement both post filtering and the 'Load More' button for the same loop grid template. Elementor doesn't support both functionalities simultaneously – 'Load More' and post filtering. Using Elementor's 'Load More' interferes with the filtering functionality, hence the reason for creating a custom 'Load More' button."

"I initially utilized the loop grid Elementor widget to showcase the initial six posts when the page loads. Subsequently, I incorporated a Button Widget labeled 'Load More' to retrieve additional posts upon clicking. Additionally, I've integrated an option for filtering posts within this layout."

Below Image indicates that i have filtering option in my layout.
![filter](https://github.com/elementor/elementor/assets/155709577/9b732a82-60c8-4681-960b-d35d5d4edc8b)

Below image indicates that i make button with Load More name.
![load](https://github.com/elementor/elementor/assets/155709577/bfe06e3b-443f-43a4-8339-4b65d1f2b080)

Below image indicates that background images not displaying on click of load more button.
![posts](https://github.com/elementor/elementor/assets/155709577/06f15663-a09c-4c8e-aa54-48a441133b32)

The problem lies in the fact that, upon the initial page load, the first six posts display correctly. However, when clicking the 'Load More' button, triggering an AJAX call to fetch additional posts, all the data is retrieved, but the background images fail to display. Similarly, when filtering through the dropdown options, the posts are successfully filtered, but the background images do not appear. All other data, apart from the background images, is being displayed as expected.

This is my AJAX and Filtering Code
![case](https://github.com/elementor/elementor/assets/155709577/541aa3c7-5873-4011-a456-ce0249b0ef2f)

This is my functions.php file code to get content of posts
![case-function](https://github.com/elementor/elementor/assets/155709577/a061663c-6fe8-42df-8f15-a5be81bae035)

In this function, I utilize the Elementor loop template shortcode as the content for posts. While all the data is successfully displayed, the issue arises as background images fail to appear.

![image](https://github.com/elementor/elementor/assets/155709577/138e733c-def6-4ff2-8019-dcadd6415f4f)
I use this elementor loop template short code in my function to get content of posts in while loop.

In conclusion, my primary concern is that background images fail to display when triggering the 'Load More' button or when applying filters to the posts.

### Expected behavior

I aim to ensure that, when clicking the 'Load More' button and changing the dropdown options, the posts are filtered, and, crucially, the background images are displayed instead of being hidden.

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release '23', Revision '71449379' v8.0.31-23
	PHP Version: 7.4.33.4
	PHP Memory Limit: 512M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.4.2
	Site URL: https://sandtechdev.wpenginepowered.com
	Home URL: https://sandtechdev.wpenginepowered.com
	WP Multisite: No
	Max Upload Size: 50 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: drcoders1@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Sand Technologies
	Version: 1.0
	Author: 
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.9.0
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

== Active Plugins ==
	AddToAny Share Buttons
		Version: 1.8.9
		Author: AddToAny

	Advanced Custom Fields PRO
		Version: 6.2.4
		Author: WP Engine

	Classic Editor
		Version: 1.6.3
		Author: WordPress Contributors

	Cookie Notice &amp; Compliance for GDPR / CCPA
		Version: 2.4.13
		Author: Hu-manity.co

	Copy &amp; Delete Posts
		Version: 1.4.4
		Author: Copy Delete Posts

	Current Menu Item for Custom Post Types
		Version: 1.6
		Author: Roland Murg

	Custom Fonts
		Version: 2.1.1
		Author: Brainstorm Force

	Elementor
		Version: 3.18.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.18.2
		Author: Elementor.com

	JetSmartFilters
		Version: 3.2.4
		Author: Crocoblock

	Post Types Order
		Version: 2.1.2
		Author: Nsp Code

	Premium Addons for Elementor
		Version: 4.10.16
		Author: Leap13

	Simple Custom CSS and JS
		Version: 3.45
		Author: SilkyPress.com

	WP Migrate Lite
		Version: 2.6.9
		Author: WP Engine

	Yoast SEO
		Version: 21.7
		Author: Team Yoast


== Must-Use Plugins ==
	Force Strong Passwords - WPE Edition
		Version: 1.8.0
		Author: Jason Cosper

	WP Engine Cache Plugin
		Version: 1.1.5
		Author: WP Engine

	WP Engine Seamless Login Plugin
		Version: 1.6.1
		Author: WP Engine

	WP Engine Security Auditor
		Version: 1.1.1
		Author: wpengine

	WP Engine System
		Version: 5.0.1
		Author: WP Engine

	WP Migrate Lite Compatibility
		Version: 1.3
		Author: Delicious Brains


== Elements Usage ==
	
	container : 25
		button : 2
		container : 103
		heading : 44
		html : 1
		image : 5
		jet-smart-filters-select : 4
		loop-carousel : 1
		loop-grid : 11
		shortcode : 3
		text-editor : 37
	footer : 1
		button : 1
		container : 16
		heading : 3
		nav-menu : 2
		premium-addon-modal-box : 1
		shortcode : 1
		social-icons : 1
		text-editor : 2
	header : 4
		button : 4
		container : 30
		image : 5
		nav-menu : 4
		premium-addon-modal-box : 5
		premium-nav-menu : 5
	page : 14
		button : 2
		container : 128
		heading : 52
		html : 4
		image : 6
		jet-smart-filters-select : 4
		loop-carousel : 1
		loop-grid : 12
		text-editor : 39
	popup : 1
		container : 8
		heading : 1
		html : 1
		image : 1
	wp-post : 5
		button : 13
		container : 962
		counter : 6
		divider : 17
		heading : 310
		html : 35
		icon-list : 5
		image : 62
		loop-grid : 30
		shortcode : 22
		text-editor : 167
	wp-page : 12
		button : 3
		container : 41
		heading : 7
		html : 1
		image : 1
		jet-smart-filters-select : 2
		loop-carousel : 1
		loop-grid : 6
		shortcode : 6
		text-editor : 6
	single-post : 6
		button : 6
		container : 154
		counter : 3
		divider : 2
		heading : 45
		html : 5
		icon-list : 1
		image : 13
		image-carousel : 1
		loop-grid : 6
		shortcode : 3
		text-editor : 28
	loop-item : 14
		button : 11
		container : 36
		heading : 21
		icon-list : 1
		image : 8
		text-editor : 2


== Settings ==
	
	cpt_support: post, page, case-study, event, industries, insights, services
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap
	load_fa4_shim: yes


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Active by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active by default
	Grid Container: Active
	Default to New Theme Builder: Active by default
	Hello Theme Header &amp; Footer: Active by default
	Editor Top Bar: Inactive by default
	Optimized Gutenberg Loading: Active by default
	Build with AI: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default
	Optimize Image Loading: Active by default
	Global Style Guide: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Menu: Inactive by default
	Taxonomy Filter: Active


== Log ==
	
JS: showing 16 of 16JS: 2023-12-13 06:11:45 [error X 6][https://sandtechdev.wpenginepowered.com/wp-admin/post.php?post=13&amp;action=elementor:10:14] Cannot read properties of undefined (reading &#039;title&#039;) 
JS: 2023-12-13 06:12:28 [error X 1][https://sandtechdev.wpenginepowered.com/wp-content/plugins/elementor/assets/js/web-cli.min.js?ver=3.18.0:3:108027] Routes: `false` not found. 
JS: 2023-12-13 06:32:01 [error X 1][https://sandtechdev.wpenginepowered.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view11945&quot;) has already been destroyed and cannot be used. 
JS: 2023-12-13 06:33:26 [error X 1][https://sandtechdev.wpenginepowered.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view145&quot;) has already been destroyed and cannot be used. 
JS: 2023-12-17 14:58:47 [error X 4][https://sandtechdev.wpenginepowered.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.18.2:3:842857] Cannot convert undefined or null to object 
JS: 2023-12-18 22:32:46 [error X 1][https://sandtechdev.wpenginepowered.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view9873&quot;) has already been destroyed and cannot be used. 
JS: 2023-12-19 10:14:48 [error X 14][https://sandtechdev.wpenginepowered.com/wp-includes/js/jquery/jquery.min.js?ver=3.7.1:2:28760] Cannot read properties of undefined (reading &#039;value&#039;) 
JS: 2023-12-19 12:17:51 [error X 1][https://sandtechdev.wpenginepowered.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view19091&quot;) has already been destroyed and cannot be used. 
JS: 2023-12-19 17:43:59 [error X 2][https://sandtechdev.wpenginepowered.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view3294&quot;) has already been destroyed and cannot be used. 
JS: 2023-12-20 04:32:39 [error X 1][https://sandtechdev.wpenginepowered.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view3313&quot;) has already been destroyed and cannot be used. 
JS: 2023-12-20 22:09:28 [error X 2][https://sandtechdev.wpenginepowered.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view1751&quot;) has already been destroyed and cannot be used. 
JS: 2023-12-21 17:39:37 [error X 2][https://sandtechdev.wpenginepowered.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view1730&quot;) has already been destroyed and cannot be used. 
JS: 2023-12-22 04:36:08 [error X 1][https://sandtechdev.wpenginepowered.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view9192&quot;) has already been destroyed and cannot be used. 
JS: 2023-12-22 04:47:00 [error X 1][https://sandtechdev.wpenginepowered.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view1727&quot;) has already been destroyed and cannot be used. 
JS: 2023-12-27 05:34:27 [error X 4][https://sandtechdev.wpenginepowered.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.18.2:3:806906] Cannot read properties of undefined (reading &#039;localized&#039;) 
JS: 2023-12-30 09:39:06 [error X 4][https://sandtechdev.wpenginepowered.com/wp-content/plugins/premium-addons-for-elementor/assets/frontend/min-js/premium-global-tooltips.min.js?ver=4.10.16:1:5276] Cannot read properties of undefined (reading &#039;desktop&#039;) 

Log: showing 20 of 202023-12-15 07:07:41 [info] elementor::elementor_updater Started 
2023-12-15 07:07:41 [info] Elementor/Upgrades - _on_each_version Start  
2023-12-15 07:07:41 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.18.0',
  'to' => '3.18.2',
)]
2023-12-15 07:07:42 [info] Elementor/Upgrades - _on_each_version Finished 
2023-12-15 07:07:42 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.18.0',
  'to' => '3.18.2',
)]
2023-12-15 07:08:25 [info] elementor-pro::elementor_pro_updater Started 
2023-12-15 07:08:25 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-12-15 07:08:25 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-12-15 07:08:25 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.18.0',
  'to' => '3.18.1',
)]
2023-12-15 07:08:25 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.18.0',
  'to' => '3.18.1',
)]
2023-12-27 08:37:16 [info] elementor-pro::elementor_pro_updater Started 
2023-12-27 08:37:16 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-12-27 08:37:16 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-12-27 08:37:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.18.1',
  'to' => '3.18.2',
)]
2023-12-27 08:37:16 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.18.1',
  'to' => '3.18.2',
)]
2023-12-27 08:37:27 [info] elementor::elementor_updater Started 
2023-12-27 08:37:28 [info] Elementor/Upgrades - _on_each_version Start  
2023-12-27 08:37:28 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.18.2',
  'to' => '3.18.3',
)]
2023-12-27 08:37:29 [info] Elementor/Upgrades - _on_each_version Finished 
2023-12-27 08:37:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.18.2',
  'to' => '3.18.3',
)]

PHP: showing 6 of 6PHP: 2023-12-15 08:56:51 [notice X 211][/nas/content/live/sandtechdev/wp-content/plugins/elementor-pro/modules/query-control/classes/elementor-post-query.php::254] Undefined property: WP_Error::$taxonomy [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-12-15 16:32:13 [notice X 76][/nas/content/live/sandtechdev/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined index: condition_type [array (
  'trace' => '
#0: /nas/content/live/sandtechdev/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /nas/content/live/sandtechdev/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /nas/content/live/sandtechdev/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /nas/content/live/sandtechdev/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2023-12-16 01:59:09 [notice X 18][/nas/content/live/sandtechdev/wp-content/plugins/elementor/modules/history/revisions-manager.php::363] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-12-17 21:00:56 [error X 1][/nas/content/live/sandtechdev/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::312] Uncaught Error: Call to a member function update_meta() on null in /nas/content/live/sandtechdev/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:312
Stack trace:
#0 /nas/content/live/sandtechdev/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(185): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;save_conditions(13, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /nas/content/live/sandtechdev/wp-content/plugins/elementor/core/common/modules/ajax/module.php(176): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /nas/content/live/sandtechdev/wp-includes/class-wp-hook.php(324): Elementor\Core\Common\Modules\Ajax\Module-&gt;handle_ajax_request(&#039;&#039;)
#4 /nas/content/live/sandtechdev/wp-includes/class-wp-hook.php(348): WP_Hook-&gt;apply_filters(&#039;&#039;, Array)
#5 /nas [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-12-18 05:06:34 [notice X 19][/nas/content/live/sandtechdev/wp-content/plugins/elementor-pro/modules/query-control/module.php::767] Trying to get property &#039;name&#039; of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-12-29 03:42:58 [notice X 1][/nas/content/live/sandtechdev/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-image.php::40] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	Premium Addons for Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by Sagarshekh0024** [comment]
I have fixed this issue,

In an Elementor Loop Grid template, Elementor generates a separate style for each loop grid item. However, this style might not be generated when we create a custom 'load more' button and perform an AJAX call to append data to the HTML

In this scenario, we should append the style above the point where we retrieve the content for posts and concatenate it with the content in the functions.php file, where the function for the load more button is written.


![image_2024_01_06T04_41_53_260Z](https://github.com/elementor/elementor/assets/155797124/903f24da-7988-466a-8754-e12c09743b10)

**Comment by JatinZindex** [comment]
Thank you so much for providing me with this solution; your assistance is greatly appreciated.
