### ISSUE TITLE
✅ 🔗 🐞 Scroll Snap experiment breaks Sticky Container Effects (Duplicate of #22474)

### ISSUE THREAD

**Issue by NicolaPavan** [elementor/elementor#24738]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Following the elementor guide to change background color of the navbar I found a issue.
Only in the page with Snap Scroll is active the scrolling effects don't produce constant result.

Guide - [https://elementor.com/help/change-sticky-header-color-scroll/](https://elementor.com/help/change-sticky-header-color-scroll/)

### Steps to reproduce

1. Create a navbar from Elementor templates
2. set z-index to 99 or 999
3. Apply a sticky or fixed, to maintain the navbar present during scroll
4. Set the main container background-color (from Style Tab > Background)
5. Enable a scrolling effects of same section (Style Tab > Background)
7. Set Transparency from Bottom 1% to Top 2% ([image](https://elementor.com/help/wp-content/uploads/2021/06/Sticky-Header-Color-Step-Nine.png))
8. Set the "Effects Relative To" -> "Entire Page"
9. Save and Apply navbar to every page
10. Create a new page with some sections with height = 100vh
11. Apply to page the snap scroll

### Expected behavior

The expected behavior is during scrolling the navbar change background color during the first scroll pixels in a snap

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt

== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.6.16
	PHP Version: 8.1.26
	PHP Memory Limit: 512M
	PHP Max Input Vars: 100000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.4.2
	Site URL: https://xxx.quantobastadev.biz
	Home URL: https://xxx.quantobastadev.biz
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 2.0.0
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.8.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 6.2.3
		Author: WP Engine

	BulkPress
		Version: 0.3.5
		Author: Jesper van Engelen

	Custom Post Type UI
		Version: 1.15.1
		Author: WebDevStudios

	Elementor
		Version: 3.18.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.17.1
		Author: Elementor.com

	Safe SVG
		Version: 2.2.2
		Author: 10up

	WOLF - WordPress Posts Bulk Editor and Manager Professional
		Version: 1.0.8
		Author: realmag777

	WP All Import Pro
		Version: 4.7.3-beta-1.2
		Author: Soflyy


== Elements Usage ==
	
	footer : 1
		container : 15
		heading : 4
		icon : 1
		icon-list : 8
		social-icons : 1
	header : 1
		button : 1
		container : 8
		mega-menu : 1
		social-icons : 1
		theme-site-logo : 1
	wp-page : 17
		animated-headline : 1
		button : 14
		call-to-action : 1
		container : 395
		counter : 5
		divider : 13
		form : 5
		heading : 113
		icon-box : 36
		icon-list : 25
		image : 19
		loop-carousel : 1
		loop-grid : 4
		nested-accordion : 14
		nested-carousel : 1
		nested-tabs : 1
		spacer : 2
		taxonomy-filter : 1
		text-editor : 118
	single-post : 1
		button : 2
		container : 28
		form : 1
		heading : 13
		image : 2
		image-carousel : 1
		loop-carousel : 1
		nested-carousel : 1
		text-editor : 4
		theme-post-title : 1
	loop-item : 4
		container : 12
		heading : 5
		image : 3
		text-editor : 3
		theme-post-featured-image : 1
		theme-post-title : 1


== Settings ==
	
	cpt_support: post, page, e-landing-page, products
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active by default
	Upgrade Swiper Library: Active by default
	Grid Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Editor Top Bar: Inactive by default
	Optimized Gutenberg Loading: Active by default
	Build with AI: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Active
	Lazy Load Background Images: Inactive by default
	Optimize Image Loading: Active by default
	Global Style Guide: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Menu: Active
	Taxonomy Filter: Active


== Log ==
	
PHP: showing 14 of 14PHP: 2023-10-17 10:53:46 [warning X 36][/home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-image.php::40] Undefined array key 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-10-18 07:17:41 [warning X 51][/home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key "condition_type" [array (
  'trace' => '
#0: /home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2023-10-24 07:57:15 [warning X 1][/home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor-pro/modules/carousel/widgets/base.php::576] Undefined array key "url" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-11-27 16:39:17 [error X 3][/home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-gallery.php::48] Uncaught TypeError: Cannot access offset of type string on string in /home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-gallery.php:48
Stack trace:
#0 /home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor/core/dynamic-tags/data-tag.php(44): ElementorPro\Modules\DynamicTags\ACF\Tags\ACF_Gallery->get_value(Array)
#1 /home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor/core/dynamic-tags/manager.php(216): Elementor\Core\DynamicTags\Data_Tag->get_content()
#2 [internal function]: Elementor\Core\DynamicTags\Manager->get_tag_data_content('1d6e53c', 'acf-gallery', Array)
#3 /home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor/core/dynamic-tags/manager.php(109): call_user_func_array(Array, Array)
#4 /home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor/core/dynamic-tags/manager.php(70): Elementor\Core\DynamicTags\Manager->parse_tag_text('[elementor-tag ...', Array, Array)
#5 /home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor/includes/controls/base-data.php(91): Elementor\Core\DynamicTags\Manager->parse_tags_text('[elementor-tag ...', Array, Array)
#6 /home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor/includes/base/controls-stack.php(1269): Elementor\Base_Data_Control->parse_tags('[elementor-tag ...', Array)
#7 /home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor/includes/base/controls-stack.php(1116): Elementor\Controls_Stack->parse_dynamic_settings(Array)
#8 /home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor/includes/base/controls-stack.php(1203): Elementor\Controls_Stack->get_parsed_dynamic_settings()
#9 /home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor/includes/widgets/image-carousel.php(840): Elementor\Controls_Stack->get_settings_for_display()
#10 /home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor/includes/base/controls-stack.php(2265): Elementor\Widget_Image_Carousel->render()
#11 /home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor/includes/base/widget-base.php(609): Elementor\Controls_Stack->render_by_mode()
#12 /home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor/includes/base/widget-base.php(733): Elementor\Widget_Base->render_content()
#13 /home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor/includes/base/element-base.php(551): Elementor\Widget_Base->get_raw_data(true)
#14 /home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor/includes/base/element-base.php(551): Elementor\Element_Base->get_raw_data(true)
#15 /home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor/core/base/document.php(1013): Elementor\Element_Base->get_raw_data(true)
#16 /home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(444): Elementor\Core\Base\Document->get_elements_raw_data(Array, true)
#17 /home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor/core/base/document.php(679): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document->get_elements_raw_data(NULL, true)
#18 /home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor/modules/library/documents/library-document.php(66): Elementor\Core\Base\Document->get_initial_config()
#19 /home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(666): Elementor\Modules\Library\Documents\Library_Document->get_initial_config()
#20 /home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor/includes/base/controls-stack.php(1010): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document->get_initial_config()
#21 /home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor/core/editor/loader/common/editor-common-scripts-settings.php(34): Elementor\Controls_Stack->get_config()
#22 /home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor/core/editor/loader/v1/editor-v1-loader.php(76): Elementor\Core\Editor\Loader\Common\Editor_Common_Scripts_Settings::get()
#23 /home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor/core/editor/editor.php(358): Elementor\Core\Editor\Loader\V1\Editor_V1_Loader->enqueue_scripts()
#24 /home/cionaedj/xxx.quantobastadev.biz/wp-includes/class-wp-hook.php(324): Elementor\Core\Editor\Editor->enqueue_scripts('')
#25 /home/cionaedj/xxx.quantobastadev.biz/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#26 /home/cionaedj/xxx.quantobastadev.biz/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#27 /home/cionaedj/xxx.quantobastadev.biz/wp-includes/script-loader.php(2262): do_action('wp_enqueue_scri...')
#28 /home/cionaedj/xxx.quantobastadev.biz/wp-includes/class-wp-hook.php(324): wp_enqueue_scripts('')
#29 /home/cionaedj/xxx.quantobastadev.biz/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#30 /home/cionaedj/xxx.quantobastadev.biz/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#31 /home/cionaedj/xxx.quantobastadev.biz/wp-includes/general-template.php(3052): do_action('wp_head')
#32 /home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor/includes/editor-templates/editor-wrapper.php(31): wp_head()
#33 /home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor/core/editor/loader/v1/editor-v1-loader.php(110): include('/home/cionaedj/...')
#34 /home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor/core/editor/editor.php(163): Elementor\Core\Editor\Loader\V1\Editor_V1_Loader->print_root_template()
#35 /home/cionaedj/xxx.quantobastadev.biz/wp-includes/class-wp-hook.php(324): Elementor\Core\Editor\Editor->init('')
#36 /home/cionaedj/xxx.quantobastadev.biz/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#37 /home/cionaedj/xxx.quantobastadev.biz/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#38 /home/cionaedj/xxx.quantobastadev.biz/wp-admin/admin.php(419): do_action('admin_action_el...')
#39 /home/cionaedj/xxx.quantobastadev.biz/wp-admin/post.php(12): require_once('/home/cionaedj/...')
#40 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-11-27 16:39:36 [warning X 10][/home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor/app/modules/import-export/module.php::753] Attempt to read property "label" on null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-11-27 16:45:33 [error X 1][/home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-gallery.php::48] Uncaught TypeError: Cannot access offset of type string on string in /home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-gallery.php:48
Stack trace:
#0 /home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor/core/dynamic-tags/data-tag.php(44): ElementorPro\Modules\DynamicTags\ACF\Tags\ACF_Gallery->get_value(Array)
#1 /home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor/core/dynamic-tags/manager.php(444): Elementor\Core\DynamicTags\Data_Tag->get_content()
#2 [internal function]: Elementor\Core\DynamicTags\Manager->ajax_render_tags(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor/core/common/modules/ajax/module.php(176): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#4 /home/cionaedj/xxx.quantobastadev.biz/wp-includes/class-wp-hook.php(324): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#5 /home/cionaedj/xxx.quantobastadev.biz/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#6 /home/cionaedj/xxx.quantobastadev.biz/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#7 /home/cionaedj/xxx.quantobastadev.biz/wp-admin/admin-ajax.php(188): do_action('wp_ajax_element...')
#8 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-11-27 16:45:33 [error X 1][/home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-gallery.php::48] Uncaught TypeError: Cannot access offset of type string on string in /home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-gallery.php:48
Stack trace:
#0 /home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor/core/dynamic-tags/data-tag.php(44): ElementorPro\Modules\DynamicTags\ACF\Tags\ACF_Gallery->get_value(Array)
#1 /home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor/core/dynamic-tags/manager.php(216): Elementor\Core\DynamicTags\Data_Tag->get_content()
#2 [internal function]: Elementor\Core\DynamicTags\Manager->get_tag_data_content('060861e', 'acf-gallery', Array)
#3 /home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor/core/dynamic-tags/manager.php(109): call_user_func_array(Array, Array)
#4 /home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor/core/dynamic-tags/manager.php(70): Elementor\Core\DynamicTags\Manager->parse_tag_text('[elementor-tag ...', Array, Array)
#5 /home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor/includes/controls/base-data.php(91): Elementor\Core\DynamicTags\Manager->parse_tags_text('[elementor-tag ...', Array, Array)
#6 /home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor/includes/base/controls-stack.php(1269): Elementor\Base_Data_Control->parse_tags('[elementor-tag ...', Array)
#7 /home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor/includes/base/controls-stack.php(1116): Elementor\Controls_Stack->parse_dynamic_settings(Array)
#8 /home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor/includes/base/controls-stack.php(1203): Elementor\Controls_Stack->get_parsed_dynamic_settings()
#9 /home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor/includes/widgets/image-carousel.php(840): Elementor\Controls_Stack->get_settings_for_display()
#10 /home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor/includes/base/controls-stack.php(2265): Elementor\Widget_Image_Carousel->render()
#11 /home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor/includes/base/widget-base.php(609): Elementor\Controls_Stack->render_by_mode()
#12 /home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor/core/base/document.php(328): Elementor\Widget_Base->render_content()
#13 /home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(456): Elementor\Core\Base\Document->render_element(Array)
#14 /home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor/includes/managers/widgets.php(446): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document->render_element(Array)
#15 [internal function]: Elementor\Widgets_Manager->ajax_render_widget(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#16 /home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor/core/common/modules/ajax/module.php(176): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#17 /home/cionaedj/xxx.quantobastadev.biz/wp-includes/class-wp-hook.php(324): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#18 /home/cionaedj/xxx.quantobastadev.biz/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#19 /home/cionaedj/xxx.quantobastadev.biz/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#20 /home/cionaedj/xxx.quantobastadev.biz/wp-admin/admin-ajax.php(188): do_action('wp_ajax_element...')
#21 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-12-05 23:13:42 [warning X 2][/home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::179] Undefined array key "editor_post_id" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-12-06 08:23:10 [warning X 715][/home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor-pro/modules/theme-builder/widgets/site-logo.php::192] Undefined array key "options" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-12-18 15:07:56 [warning X 1][/home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/icons/custom-icons.php::199] unlink(Group-5.svg): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-12-18 19:23:49 [notice X 4][/home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor/includes/utils.php::727] strtolower(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-12-19 09:54:00 [warning X 7][/home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-url.php::34] Undefined array key 0 [array (
  'trace' => '
#0: /home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-url.php(34): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor/core/dynamic-tags/data-tag.php(44): ElementorPro\Modules\DynamicTags\ACF\Tags\ACF_URL -> get_value()
#2: /home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor/core/dynamic-tags/manager.php(216): Elementor\Core\DynamicTags\Data_Tag -> get_content()
#3: Elementor\Core\DynamicTags\Manager -> get_tag_data_content()
#4: /home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor/core/dynamic-tags/manager.php(109): class type call_user_func_array()
',
)]
PHP: 2023-12-19 09:54:00 [warning X 7][/home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-url.php::34] Undefined array key 1 [array (
  'trace' => '
#0: /home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-url.php(34): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor/core/dynamic-tags/data-tag.php(44): ElementorPro\Modules\DynamicTags\ACF\Tags\ACF_URL -> get_value()
#2: /home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor/core/dynamic-tags/manager.php(216): Elementor\Core\DynamicTags\Data_Tag -> get_content()
#3: Elementor\Core\DynamicTags\Manager -> get_tag_data_content()
#4: /home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor/core/dynamic-tags/manager.php(109): class type call_user_func_array()
',
)]
PHP: 2024-01-08 10:55:07 [notice X 2][/home/cionaedj/xxx.quantobastadev.biz/wp-content/plugins/elementor/includes/base/controls-stack.php::228] hexdec(): Passing null to parameter #1 ($hex_string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 2 of 2JS: 2023-10-23 15:50:24 [error X 18][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.16.4:3:804689] Cannot read properties of undefined (reading 'localized') 
JS: 2023-10-24 09:32:24 [error X 28][../wp-content/plugins/elementor/assets/js/4fdaa70e951ad90db2f2.bundle.min.js:2:7786] Cannot read properties of null (reading 'dataset') 

Log: showing 20 of 262023-11-27 14:50:55 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.16.4',
  'to' => '3.17.3',
)]
2023-11-27 14:50:55 [info] Elementor/Upgrades - _on_each_version Finished 
2023-11-27 14:50:55 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Start  
2023-11-27 14:50:55 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Finished 
2023-11-27 14:50:55 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.16.4',
  'to' => '3.17.3',
)]
2023-11-27 15:46:05 [info] elementor-pro::elementor_pro_updater Started 
2023-11-27 15:46:05 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-11-27 15:46:05 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-11-27 15:46:05 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.16.2',
  'to' => '3.17.1',
)]
2023-11-27 15:46:05 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.16.2',
  'to' => '3.17.1',
)]
2023-12-06 08:22:49 [info] elementor::elementor_updater Started 
2023-12-06 08:22:49 [info] Elementor/Upgrades - _on_each_version Start  
2023-12-06 08:22:50 [info] Elementor/Upgrades - _on_each_version Finished 
2023-12-06 08:22:50 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.17.3',
  'to' => '3.18.0',
)]
2023-12-06 08:22:50 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.17.3',
  'to' => '3.18.0',
)]
2024-01-08 10:49:16 [info] elementor::elementor_updater Started 
2024-01-08 10:49:16 [info] Elementor/Upgrades - _on_each_version Start  
2024-01-08 10:49:17 [info] Elementor/Upgrades - _on_each_version Finished 
2024-01-08 10:49:17 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.18.0',
  'to' => '3.18.3',
)]
2024-01-08 10:49:17 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.18.0',
  'to' => '3.18.3',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Incompatible

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hi @NicolaPavan!

We have great news! 🙌 

### 📢 We're happy to announce that this issue was resolved with the release of Elementor Pro v3.26.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂

----
PS: If you still experience the same issue after updating to the latest version, and can reproduce it consistently even after troubleshooting it and clearing all levels of cache, please [open a new Bug Report](https://elemn.to/gh-new-bug-report) with detailed information so we can investigate it further.
