### ISSUE TITLE
Add controls to video in lightbox

### ISSUE THREAD

**Issue by smaxx1337** [elementor/elementor#24845]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

When you create a button with a dynamic tag and choose Lightbox, you can insert a video link:
![grafik](https://github.com/elementor/elementor/assets/8495515/ac67f874-7a23-4739-9f33-008493c1b514)
![grafik](https://github.com/elementor/elementor/assets/8495515/9d5b0930-26e3-4d9c-af0a-d6ff74668a50)

However, the <video> tag has no controls attribute which can result in users not watching the video at all or closing it because the user can not stop the video.

Is it possible to insert a toggle button in the settings of the lightbox, so the website creator can decide if he wants the controls to show or not?

### Steps to reproduce

1. Create a button
2. Choose dynamic tag
3. Choose lightbox
4. Insert a video URL
5. Save it, click the button and see that there are no controls available

### Expected behavior

Show controls, depending on if the website creator allows it or not. Just like the Video widget on its own.

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Ubuntu 18.04 v5.6.49-89.0
	PHP Version: 8.2.14
	PHP Memory Limit: 1G
	PHP Max Input Vars: 1000
	PHP Max Post Size: 1G
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.4.2
	Site URL: x
	Home URL: x
	WP Multisite: No
	Max Upload Size: 1 GB
	Memory limit: 40M
	Max Memory limit: 1G
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: de-DE
	Timezone: Europe/Berlin
	Admin Email: x
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Twenty-Three
	Version: 1.2
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

== Active Plugins ==
	Complianz | GDPR/CCPA Cookie Consent
		Version: 6.5.5
		Author: Really Simple Plugins

	Elementor
		Version: 3.18.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.18.1
		Author: Elementor.com

	Redis Object Cache
		Version: 2.5.0
		Author: Till Krüss

	Yoast SEO
		Version: 21.8
		Author: Team Yoast


== Elemente Verwendung ==
	
	footer : 2
		container : 9
		heading : 5
		image : 2
		nav-menu : 3
		social-icons : 1
		text-editor : 1
	header : 1
		container : 1
		image : 1
		theme-site-logo : 1
	page : 1
		button : 2
		container : 13
		divider : 5
		heading : 8
		icon : 2
		icon-box : 10
		icon-list : 1
		image-box : 10
		text-editor : 3
	wp-page : 4
		button : 5
		container : 49
		divider : 5
		form : 2
		heading : 19
		html : 1
		icon : 2
		icon-box : 11
		icon-list : 1
		image : 7
		image-box : 11
		image-carousel : 1
		menu-anchor : 1
		spacer : 7
		testimonial : 3
		text-editor : 19
		toggle : 1
		video : 2
	error-404 : 1
		button : 1
		container : 3
		heading : 1
		image : 3
		text-editor : 1


== Einstellungen ==
	
	cpt_support: post, page
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap


== Eigenschaften ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	
	recaptcha_v3: Aktiv


== Elementor-Experimente ==
	Optimierte DOM Ausgabe: Standardmäßig aktiviert
	Verbessertes Laden von Assets: Standardmäßig aktiviert
	Verbessertes Laden von CSS: Standardmäßig aktiviert
	Inline-Schriftarten-Symbole: Standardmäßig deaktiviert
	Zusätzliche benutzerdefinierte Breakpoints: Standardmäßig aktiviert
	admin_menu_rearrangement: Standardmäßig deaktiviert
	Flexbox Container: Standardmäßig aktiviert
	Upgrade Swiper Library: Standardmäßig aktiviert
	Grid Container: Standardmäßig deaktiviert
	Default to New Theme Builder: Standardmäßig aktiviert
	Editor Top Bar: Standardmäßig deaktiviert
	Optimized Gutenberg Loading: Standardmäßig aktiviert
	Build with AI: Standardmäßig deaktiviert
	Startseiten: Standardmäßig aktiviert
	Nested Elements: Standardmäßig deaktiviert
	Hintergrundbilder nachladen: Standardmäßig deaktiviert
	Optimize Image Loading: Standardmäßig aktiviert
	Globaler Styleguide: Standardmäßig aktiviert
	Page Transitions: Standardmäßig aktiviert
	Notes: Standardmäßig aktiviert
	Form Submissions: Standardmäßig aktiviert
	Scroll Snap: Standardmäßig aktiviert
	Menü: Standardmäßig deaktiviert
	Taxonomy Filter: Standardmäßig deaktiviert


== Protokoll ==
	
PHP: showing 11 of 11PHP: 2023-10-05 19:20:26 [notice X 172][/var/www/vhosts/x.de/httpdocs/wp-content/plugins/elementor/includes/elements/container.php::42] Creation of dynamic property Elementor\Includes\Elements\Container::$logical_dimensions_inline_start is deprecated [array (
  'trace' => '
#0: /var/www/vhosts/x.de/httpdocs/wp-content/plugins/elementor/includes/elements/container.php(42): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /var/www/vhosts/x.de/httpdocs/wp-content/plugins/elementor/includes/managers/elements.php(89): Elementor\Includes\Elements\Container -> __construct()
#2: /var/www/vhosts/x.de/httpdocs/wp-content/plugins/elementor/core/base/document.php(1733): Elementor\Elements_Manager -> create_element_instance()
#3: /var/www/vhosts/x.de/httpdocs/wp-content/plugins/elementor/core/base/document.php(1134): Elementor\Core\Base\Document -> print_elements()
#4: /var/www/vhosts/x.de/httpdocs/wp-content/plugins/elementor/includes/frontend.php(1179): Elementor\Core\Base\Document -> print_elements_with_wrapper()
',
)]
PHP: 2023-10-05 19:20:26 [notice X 172][/var/www/vhosts/x.de/httpdocs/wp-content/plugins/elementor/includes/elements/container.php::43] Creation of dynamic property Elementor\Includes\Elements\Container::$logical_dimensions_inline_end is deprecated [array (
  'trace' => '
#0: /var/www/vhosts/x.de/httpdocs/wp-content/plugins/elementor/includes/elements/container.php(43): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /var/www/vhosts/x.de/httpdocs/wp-content/plugins/elementor/includes/managers/elements.php(89): Elementor\Includes\Elements\Container -> __construct()
#2: /var/www/vhosts/x.de/httpdocs/wp-content/plugins/elementor/core/base/document.php(1733): Elementor\Elements_Manager -> create_element_instance()
#3: /var/www/vhosts/x.de/httpdocs/wp-content/plugins/elementor/core/base/document.php(1134): Elementor\Core\Base\Document -> print_elements()
#4: /var/www/vhosts/x.de/httpdocs/wp-content/plugins/elementor/includes/frontend.php(1179): Elementor\Core\Base\Document -> print_elements_with_wrapper()
',
)]
PHP: 2023-10-05 19:20:29 [notice X 1][/var/www/vhosts/x.de/httpdocs/wp-content/plugins/elementor/includes/utils.php::727] strtolower(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /var/www/vhosts/x.de/httpdocs/wp-content/plugins/elementor/includes/utils.php(727): class type strtolower()
#2: /var/www/vhosts/x.de/httpdocs/wp-content/plugins/elementor-pro/modules/call-to-action/widgets/call-to-action.php(1594): Elementor\Utils :: validate_html_tag()
#3: /var/www/vhosts/x.de/httpdocs/wp-content/plugins/elementor/includes/base/controls-stack.php(2265): ElementorPro\Modules\CallToAction\Widgets\Call_To_Action -> render()
#4: /var/www/vhosts/x.de/httpdocs/wp-content/plugins/elementor/includes/base/widget-base.php(609): Elementor\Controls_Stack -> render_by_mode()
',
)]
PHP: 2023-10-06 19:30:44 [warning X 2][/var/www/vhosts/x.de/httpdocs/wp-content/plugins/elementor/includes/managers/widgets.php::362] Undefined array key &quot;editor_post_id&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-10-08 12:11:21 [notice X 4][/var/www/vhosts/x.de/httpdocs/wp-content/plugins/elementor-pro/modules/screenshots/module.php::33] Function utf8_decode() is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-10-16 21:16:22 [warning X 1][/var/www/vhosts/x.de/httpdocs/wp-content/plugins/elementor/core/files/file-types/svg.php::161] simplexml_load_file(): I/O warning : failed to load external entity &quot;https://x.de/wp-content/uploads/2023/10/polygon-scatter-haikei.svg&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-10-16 21:18:00 [warning X 1][/var/www/vhosts/x.de/httpdocs/wp-content/plugins/elementor/core/files/file-types/svg.php::161] simplexml_load_file(): I/O warning : failed to load external entity &quot;https://x.de/wp-content/uploads/2023/10/circle-scatter-haikei.svg&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-10-24 20:44:30 [notice X 953][/var/www/vhosts/x.de/httpdocs/wp-content/plugins/elementor/includes/elements/container.php::43] Creation of dynamic property Elementor\Includes\Elements\Container::$logical_dimensions_inline_end is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-10-31 08:05:07 [notice X 5][/var/www/vhosts/x.de/httpdocs/wp-content/plugins/elementor-pro/core/editor/editor.php::118] Using ${var} in strings is deprecated, use {$var} instead [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-01-14 15:32:25 [error X 1][/var/www/vhosts/x.de/httpdocs/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::312] Uncaught Error: Call to a member function update_meta() on null in /var/www/vhosts/x.de/httpdocs/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:312
Stack trace:
#0 /var/www/vhosts/x.de/httpdocs/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(185): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;ajax_save_theme_template_conditions()
#2 /var/www/vhosts/x.de/httpdocs/wp-content/plugins/elementor/core/common/modules/ajax/module.php(176): call_user_func()
#3 /var/www/vhosts/x.de/httpdocs/wp-includes/class-wp-hook.php(324): Elementor\Core\Common\Modules\Ajax\Module-&gt;handle_ajax_request()
#4 /var/www/vhosts/x.de/httpdocs/wp-includes/class-wp-hook.php(348): WP_Hook-&gt;apply_filters()
#5 /var/www/vhosts/x.de/httpdocs/wp-includes/plugin.php(517): WP_Hook-&gt;do_action()
#6 /var/www/vhosts/x.de/httpdocs/wp-admin/admin-ajax.php(188): do_action()
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-01-16 13:59:45 [warning X 1][/var/www/vhosts/x.de/httpdocs/wp-content/plugins/elementor/includes/embed.php::185] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 7 of 7JS: 2023-10-08 10:10:56 [error X 7][https://x.de/wp-admin/load-scripts.php?c=0&amp;loadchunk_0=jquery-core,jquery-migrate,utils,moxiejs,plupload&amp;ver=6.3.1:2:28722] Cannot read properties of undefined (reading &#039;value&#039;) 
JS: 2023-10-08 10:11:08 [error X 1][https://x.de/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.16.4:3:919115] elementorFrontend is not defined 
JS: 2024-01-13 13:34:31 [error X 1][https://x.de/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.18.1:3:806399] Cannot read properties of undefined (reading &#039;toLowerCase&#039;) 
JS: 2024-01-13 13:37:34 [error X 6][https://x.de/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.18.1:3:640760] Cannot read properties of undefined (reading &#039;isDesignable&#039;) 
JS: 2024-01-13 13:39:41 [error X 3][https://x.de/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=3.18.1:2:12705] Failed to execute &#039;observe&#039; on &#039;IntersectionObserver&#039;: parameter 1 is not of type &#039;Element&#039;. 
JS: 2024-01-15 18:09:33 [error X 9][https://x.de/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.18.1:3:806906] Cannot read properties of undefined (reading &#039;localized&#039;) 
JS: 2024-01-15 19:27:56 [error X 1][https://x.de/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.18.1:3:54595] Cannot read properties of undefined (reading &#039;activate&#039;) 

Log: showing 20 of 252023-10-24 20:44:27 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Start  
2023-10-24 20:44:27 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Finished 
2023-10-24 20:44:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.16.4',
  'to' => '3.16.6',
)]
2023-10-30 21:40:16 [info] elementor::elementor_updater Started 
2023-10-30 21:40:16 [info] Elementor/Upgrades - _on_each_version Start  
2023-10-30 21:40:16 [info] Elementor/Upgrades - _on_each_version Finished 
2023-10-30 21:40:16 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Start  
2023-10-30 21:40:16 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Finished 
2023-10-30 21:40:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.16.6',
  'to' => '3.17.1',
)]
2023-10-30 21:40:16 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.16.6',
  'to' => '3.17.1',
)]
2023-12-07 21:02:45 [info] elementor-pro::elementor_pro_updater Started 
2023-12-07 21:02:45 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-12-07 21:02:45 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-12-07 21:02:45 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.16.2',
  'to' => '3.18.1',
)]
2023-12-07 21:02:45 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.16.2',
  'to' => '3.18.1',
)]
2023-12-07 21:02:45 [info] elementor::elementor_updater Started 
2023-12-07 21:02:45 [info] Elementor/Upgrades - _on_each_version Start  
2023-12-07 21:02:46 [info] Elementor/Upgrades - _on_each_version Finished 
2023-12-07 21:02:46 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.17.1',
  'to' => '3.18.1',
)]
2023-12-07 21:02:46 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.17.1',
  'to' => '3.18.1',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Die Kompatibilität ist nicht angegeben

== Elementor Pro - Compatibility Tag ==
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by portrayaloflife** [comment]
Also adding Dynamic Content for the Video URL here too would allow users to pull a youtube url or images from custom posts and could feature the lightbox in loops which would be awesome
