### ISSUE TITLE
Site Settings Hangs on Exit

### ISSUE THREAD

**Issue by bnovak99** [elementor/elementor#24856]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

In the page editor, when I click the site settings icon in the top bar the settings are quite slow to open and if click exit (even w/o making and changes) it hangs for at least one minute before closing site settings. I have no other plugins installed. I tried disabling all Elementor features and adding them back one by one. After disabling all features except (the top bar), the site settings opened and closed normally.  When I reactivated Flexbox Containers the issue came back (nested containers disabled). This issue occurs both on my local environment and on wp engine.

### Steps to reproduce

1. Open Elementor page Editor
2. Click site settings in upper left top bar
3. Close site settings
![sitesettings](https://github.com/elementor/elementor/assets/25965963/8f34db4f-5622-4002-8821-ff5f4ff3fffc)

### Expected behavior

I am expecting site settings to close in a 1-2 seconds instead on one minute.

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [ ] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
== Server Environment ==
	Operating System: Darwin
	Software: nginx/1.16.0
	MySQL version: MySQL Community Server - GPL v8.0.16
	PHP Version: 8.1.23
	PHP Memory Limit: 256M
	PHP Max Input Vars: 4000
	PHP Max Post Size: 1000M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.4.2
	Site URL: https://teamworks.local
	Home URL: https://teamworks.local
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: 
	Debug Mode: Inactive

== Theme ==
	Name: Teamworks
	Version: 2.0.0
	Author: Top Fox Marketing
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 3.0.0
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.18.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.18.3
		Author: Elementor.com

	Menu Icons
		Version: 0.13.8
		Author: ThemeIsle


== Elements Usage ==
	
	footer : 1
		button : 1
		container : 5
		heading : 5
		text-editor : 7
		theme-site-logo : 1
	header : 1
		button : 11
		container : 70
		heading : 23
		image : 13
		image-box : 10
		mega-menu : 1
		nav-menu : 1
		nested-tabs : 2
		text-editor : 17
		theme-site-logo : 1
	page : 1
		container : 34
		heading : 26
		image : 11
		nav-menu : 1
		spacer : 2
		text-editor : 3
	widget : 0
		button : 1
	wp-page : 6
		button : 9
		container : 207
		form : 2
		heading : 128
		image : 64
		image-box : 6
		image-carousel : 2
		nav-menu : 3
		spacer : 21
		testimonial-carousel : 2
		text-editor : 53


== Settings ==
	
	cpt_support: post, page
	disable_color_schemes: yes
	disable_typography_schemes: yes
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap
	load_fa4_shim: yes
	disabled_elements: facebook-page, facebook-embed, facebook-comments, facebook-button, animated-headline, wp-widget-rss, rating, reviews, audio, stripe-button, wp-widget-tag_cloud


== Features ==
	Custom Fonts: 1
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Active
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active by default
	Grid Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Editor Top Bar: Active
	Optimized Gutenberg Loading: Active by default
	Build with AI: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Inactive
	Lazy Load Background Images: Inactive by default
	Optimize Image Loading: Active by default
	Pages Panel: Inactive by default
	Global Style Guide: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Menu: Inactive
	Taxonomy Filter: Inactive by default


== Log ==
	
JS: showing 20 of 28JS: 2024-01-09 17:40:41 [error X 1][https://teamworksstg.wpenginepowered.com/wp-includes/js/jquery/jquery.min.js?ver=3.7.1:2:37833] Cannot create property 'guid' on string 'c18022widgetsticky' 
JS: 2024-01-09 17:41:02 [error X 1][https://teamworksstg.wpenginepowered.com/wp-includes/js/jquery/jquery.min.js?ver=3.7.1:2:37833] Cannot create property 'guid' on string 'c21603containersticky' 
JS: 2024-01-09 17:41:02 [error X 1][https://teamworksstg.wpenginepowered.com/wp-includes/js/jquery/jquery.min.js?ver=3.7.1:2:37833] Cannot create property 'guid' on string 'c21604widgetsticky' 
JS: 2024-01-09 17:41:02 [error X 1][https://teamworksstg.wpenginepowered.com/wp-includes/js/jquery/jquery.min.js?ver=3.7.1:2:37833] Cannot create property 'guid' on string 'c21607widgetsticky' 
JS: 2024-01-09 17:41:05 [error X 1][https://teamworksstg.wpenginepowered.com/wp-includes/js/jquery/jquery.min.js?ver=3.7.1:2:37833] Cannot create property 'guid' on string 'c22836containersticky' 
JS: 2024-01-09 17:41:05 [error X 1][https://teamworksstg.wpenginepowered.com/wp-includes/js/jquery/jquery.min.js?ver=3.7.1:2:37833] Cannot create property 'guid' on string 'c22837widgetsticky' 
JS: 2024-01-09 17:41:05 [error X 1][https://teamworksstg.wpenginepowered.com/wp-includes/js/jquery/jquery.min.js?ver=3.7.1:2:37833] Cannot create property 'guid' on string 'c22840widgetsticky' 
JS: 2024-01-09 19:01:03 [error X 5][https://teamworksstg.wpengine.com/wp-includes/js/jquery/jquery.min.js?ver=3.7.1:2:37833] Cannot create property 'guid' on string 'c31widgetsticky' 
JS: 2024-01-10 20:07:51 [error X 13][https://teamworks.local/wp-content/plugins/elementor/assets/js/common-modules.min.js?ver=3.18.3:2:56156] Model.isValidChild() should be implemented, please provide 'isValidChild' functionality. 
JS: 2024-01-11 01:27:27 [error X 6][https://teamworks.local/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.18.3:3:806846] Cannot read properties of undefined (reading 'localized') 
JS: 2024-01-11 01:27:57 [error X 10][https://teamworks.local/wp-content/plugins/elementor/assets/js/4fdaa70e951ad90db2f2.bundle.min.js:2:7786] Cannot read properties of null (reading 'dataset') 
JS: 2024-01-12 01:02:36 [error X 1][https://teamworks.local/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.18.3:3:806339] Cannot read properties of undefined (reading 'toLowerCase') 
JS: 2024-01-15 14:08:51 [error X 3][https://teamworks.local/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.18.3:3:54595] Cannot read properties of undefined (reading 'activate') 
JS: 2024-01-16 20:26:32 [error X 1][https://teamworks.local/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.18.3:3:690111] this.model.isValidChild is not a function 
JS: 2024-01-16 21:22:17 [error X 1][https://teamworks.local/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.18.3:3:640700] Cannot read properties of undefined (reading 'isDesignable') 
JS: 2024-01-16 21:24:55 [error X 1][https://teamworks.local/wp-content/plugins/elementor/assets/js/packages/editor-app-bar/editor-app-bar.min.js?ver=3.18.3:9:4652] Cannot read properties of undefined (reading '__privateListenTo') 
JS: 2024-01-16 21:24:55 [error X 2][https://teamworks.local/wp-content/plugins/elementor/assets/js/packages/editor-panels/editor-panels.min.js?ver=3.18.3:1:845] Cannot read properties of undefined (reading '__createSlice') 
JS: 2024-01-16 21:24:55 [error X 1][https://teamworks.local/wp-content/plugins/elementor/assets/js/packages/editor-site-navigation/editor-site-navigation.min.js?ver=3.18.3:1:13897] Cannot read properties of undefined (reading '__createPanel') 
JS: 2024-01-16 21:24:55 [error X 1][https://teamworks.local/wp-content/plugins/elementor/assets/js/packages/editor/editor.min.js?ver=3.18.3:1:1822] Cannot read properties of undefined (reading '__createStore') 
JS: 2024-01-18 18:46:10 [error X 1][https://teamworks.local/wp-admin/load-scripts.php?c=1&loadchunk_0=jquery-core,jquery-migrate,utils,moxiejs,plupload&ver=6.4.2:2:28760] Cannot read properties of undefined (reading 'value') 

PHP: showing 9 of 9PHP: 2024-01-09 19:00:37 [notice X 142][/nas/content/live/teamworksstg/wp-content/plugins/elementor/includes/base/controls-stack.php::228] hexdec(): Passing null to parameter #1 ($hex_string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-01-09 21:56:37 [warning X 5][/Users/ElevatedMedia/Local Sites/teamworks/app/public/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/fonts-manager.php::252] Undefined array key "editor_post_id" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-01-09 22:23:46 [warning X 1][/Users/ElevatedMedia/Local Sites/teamworks/app/public/wp-content/plugins/elementor/core/files/file-types/svg.php::161] simplexml_load_file(): I/O warning : failed to load external entity "https://teamworks.local/wp-content/uploads/Teamworks-Horizontal.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-01-09 23:10:29 [error X 2][/Users/ElevatedMedia/Local Sites/teamworks/app/public/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::312] Uncaught Error: Call to a member function update_meta() on null in /Users/ElevatedMedia/Local Sites/teamworks/app/public/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:312
Stack trace:
#0 /Users/ElevatedMedia/Local Sites/teamworks/app/public/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(185): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(8, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /Users/ElevatedMedia/Local Sites/teamworks/app/public/wp-content/plugins/elementor/core/common/modules/ajax/module.php(176): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /Users/ElevatedMedia/Local Sites/teamworks/app/public/wp-includes/class-wp-hook.php(324): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /Users/ElevatedMedia/Local Sites/teamworks/app/public/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#5 /Users/ElevatedMedia/Local Sites/teamworks/app/public/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /Users/ElevatedMedia/Local Sites/teamworks/app/public/wp-admin/admin-ajax.php(188): do_action('wp_ajax_element...')
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-01-10 23:36:16 [warning X 3][/Users/ElevatedMedia/Local Sites/teamworks/app/public/wp-content/plugins/elementor/includes/managers/image.php::113] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-01-11 20:01:23 [warning X 2][/Users/ElevatedMedia/Local Sites/teamworks/app/public/wp-content/plugins/elementor/core/files/file-types/svg.php::161] simplexml_load_file(): I/O warning : failed to load external entity "https://teamworks.local/wp-content/uploads/connect.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-01-11 20:01:23 [warning X 2][/Users/ElevatedMedia/Local Sites/teamworks/app/public/wp-content/plugins/elementor/core/files/file-types/svg.php::161] simplexml_load_file(): I/O warning : failed to load external entity "https://teamworks.local/wp-content/uploads/empower.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-01-11 20:01:23 [warning X 2][/Users/ElevatedMedia/Local Sites/teamworks/app/public/wp-content/plugins/elementor/core/files/file-types/svg.php::161] simplexml_load_file(): I/O warning : failed to load external entity "https://teamworks.local/wp-content/uploads/focus.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-01-17 03:55:56 [error X 1][/Users/ElevatedMedia/Local Sites/teamworks/app/public/wp-content/plugins/elementor/core/wp-api.php::26] Uncaught Error: Call to undefined function Elementor\Core\get_plugins() in /Users/ElevatedMedia/Local Sites/teamworks/app/public/wp-content/plugins/elementor/core/wp-api.php:26
Stack trace:
#0 /Users/ElevatedMedia/Local Sites/teamworks/app/public/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(96): Elementor\Core\Wp_Api->get_plugins()
#1 /Users/ElevatedMedia/Local Sites/teamworks/app/public/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(58): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_with_header()
#2 /Users/ElevatedMedia/Local Sites/teamworks/app/public/wp-content/plugins/elementor/modules/compatibility-tag/module.php(57): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_to_check()
#3 /Users/ElevatedMedia/Local Sites/teamworks/app/public/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(148): Elementor\Modules\CompatibilityTag\Module->get_plugins_to_check()
#4 /Users/ElevatedMedia/Local Sites/teamworks/app/public/wp-includes/class-wp-hook.php(324): Elementor\Modules\CompatibilityTag\Base_Module->Elementor\Modules\CompatibilityTag\{closure}('')
#5 /Users/ElevatedMedia/Local Sites/teamworks/app/public/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#6 /Users/ElevatedMedia/Local Sites/teamworks/app/public/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#7 /Users/ElevatedMedia/Local Sites/teamworks/app/public/wp-content/plugins/elementor/modules/system-info/module.php(340): do_action('elementor/syste...')
#8 /Users/ElevatedMedia/Local Sites/teamworks/app/public/wp-content/plugins/elementor/includes/tracker.php(241): Elementor\Modules\System_Info\Module::get_allowed_reports()
#9 /Users/ElevatedMedia/Local Sites/teamworks/app/public/wp-content/plugins/elementor/includes/tracker.php(530): Elementor\Tracker::get_system_reports_data()
#10 /Users/ElevatedMedia/Local Sites/teamworks/app/public/wp-content/plugins/elementor/includes/tracker.php(141): Elementor\Tracker::get_tracking_data(false)
#11 /Users/ElevatedMedia/Local Sites/teamworks/app/public/wp-includes/class-wp-hook.php(324): Elementor\Tracker::send_tracking_data()
#12 /Users/ElevatedMedia/Local Sites/teamworks/app/public/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#13 /Users/ElevatedMedia/Local Sites/teamworks/app/public/wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#14 /Users/ElevatedMedia/Local Sites/teamworks/app/public/wp-cron.php(191): do_action_ref_array('elementor/track...', Array)
#15 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 5 of 52024-01-17 14:57:12 [info] elementor-pro::elementor_pro_updater Started 
2024-01-17 14:57:12 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-01-17 14:57:12 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-01-17 14:57:13 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.18.2',
  'to' => '3.18.3',
)]
2024-01-17 14:57:13 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.18.2',
  'to' => '3.18.3',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hello @bnovak99!

Thank you for submitting your issue. 🙏 

Unfortunately, we were not able to reproduce your issue. After checking your Elementor System Info, we see your Memory Limit is set to 40M, which is not the [required value](https://elementor.com/help/requirements/#wp-memory-limit).

Please add the following PHP code snippet to your `wp-config.php` file right above the comment that says `/* That's all, stop editing! Happy publishing. */`:

```php

/** Define Server Resources Limits */
if ( ! defined( 'WP_MEMORY_LIMIT' ) ) {
    define( 'WP_MEMORY_LIMIT', '256M' );
}

```

And then try again. We also recommend testing on a Chromium-based browser.

Let us know if that works for you.

Kind regards

**Comment by bnovak99** [comment]
Hi Nicholas,

I tried using the memory limit to 256M and 512M. It did not see to resolve the issue. Were you able to recreate the issue if you have a mega menu or nested containers? Both?

When I have a mega menu and several content containers, going in and out of the site settings takes a while which is why I have resorted to using the child theme to make css updates.

--
Brian Novak
web developer
303-570-8904
