### ISSUE TITLE
Loop carousel widget and loop grid query problem

### ISSUE THREAD

**Issue by orizzontiholding** [elementor/elementor#24973]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

I'm using Loop carousel widget and loop grid widget to show products in my woocommerce website. Fortunately I'm not in production and during the layout develop, I've noticed that when I set infinite scroll I will have always the same products displayed into the carousel and into the grid. 

I have this settings for template in the loop grid widget
![image](https://github.com/elementor/elementor/assets/112951964/e1a737de-e0bd-4fe0-86a9-c69a0d9bf826)
And this settings for the query
![image](https://github.com/elementor/elementor/assets/112951964/66c338a4-ebf8-424c-b8fc-ba5584bc0f7e)

This is what the grid will show before the scroll
![image](https://github.com/elementor/elementor/assets/112951964/2a3a1bbf-6258-4545-9e21-9a09c73fd570)
And this after the scroll where I will see the same products of the first two rows
![image](https://github.com/elementor/elementor/assets/112951964/006ff103-dac8-4d0a-b1be-80d8e08b36e9)

For the carousel instead, I need to show all the products so I leave blank the slide number field
![image](https://github.com/elementor/elementor/assets/112951964/8f6f8882-bbf0-4309-9d4f-ffa7ca8df979)
And for the query as follow
![image](https://github.com/elementor/elementor/assets/112951964/1d88181d-659d-437f-9dbb-e4216e9c601d)
 

### Steps to reproduce

Create custom template for loop grid and loop carousel.
Set custom template and set a category to get the desired posts

### Expected behavior

What I was expecting is that on loop grid, when scrolling other products are loaded and not always the same of the first two row.
Is this a bug or I need to modify settings?

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
Operating System:	Linux	
Software:	Apache	
MySQL version:	MySQL Community Server (GPL) v5.6.51	
PHP Version:	8.0.30	
PHP Memory Limit:	-1	Si consiglia di impostare la memoria su almeno 128M. (256M o superiore è preferibile) Per ulteriori informazioni, leggere come aumentare la memoria allocata a PHP.
PHP Max Input Vars:	1000	
PHP Max Post Size:	8M	
GD Installed:	Yes	
ZIP Installed:	Yes	
Write Permissions:	All right	
Elementor Library:	Connected

Version:	6.4.2	
Site URL:	----	
Home URL:	----
WP Multisite:	No	
Max Upload Size:	5 MB	
Memory limit:	40M	
Max Memory limit:	-1	
Permalink Structure:	/%postname%/	
Language:	it-IT	
Timezone:	Europe/Rome	
Admin Email:	----	
Debug Mode:	Inactive

Name:	Hello Elementor	
Version:	3.0.0	
Author:	Elementor Team	
Child Theme:	No

Advanced Custom Fields - 6.2.5	By WP Engine	
Classic Editor - 1.6.3	By WordPress Contributors	
Elementor - 3.19.0	By Elementor.com	
Git Updater - 12.3.1	By Andy Fragen	
Health Check & Troubleshooting - 1.7.0	By The WordPress.org community	
Performance Lab - 2.8.0	By WordPress Performance Team	
PRO Elements - 3.18.1	By PROElements.org	
Site Kit by Google - 1.119.0	By Google	
WooCommerce - 8.5.2	By Automattic	
Woocommerce ipercheckout - 1.0.0		
WordPress Importer - 0.8.2	By wordpressdotorg	
Yoast SEO - 21.9.1	By Team Yoast
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hello @orizzontiholding,

can you please confirm the following?

1. Are you using these widgets on Archive Templates or on static Pages?
2. If using these widgets on Archive Templates, have you set the query Source to be the "Current Query"?

Can you also please submit the entire Elementor System Info as required in the Bug Submission form?

> Please copy and paste the full Elementor System Info report from your WordPress Dashboard > Elementor > System Info page (available at the bottom of the page).
> We won't accept issues without it. [Learn how to copy it here](https://elemn.to/help-system-info).

**Comment by yodyk** [comment]
This is happening for me as well. I set the "items per page" to 6, and instead of loading "more" items within the query, it loads the previously loaded 6. I also have "Avoid Duplicates" switch on. I have the loop queried by "Include by: Term – Categories: "My Category" 

My problem is occuring within a loop grid on a static page, nested inside of a Tabbed section. It is also occurring on the other Loop Grids set up in a similar fashion under different category queries.  

This was not happening about 2 weeks ago from today (Feb. 6, 2024)

**Comment by ichx123** [comment]
Happening here as well. We use "Load on Click" and use the Loop Grid to display Custom Post Types (CPT UI, ACF is used). We have the problem on static pages and on archive sites as well. Queries are on "Term" with a Category on the Static Pages and on the Archive Page is the Query "Search & Filter Query" -> from the "Search & Filter Pro - Plugin". 

The problem does not change, when we change the Queries and existed now for a while. We suspected a caching problem, because the problem sometimes (!) does not occur when the page is completely reloaded, but we don't have a caching plugin installed, so we discarded this idea... After the Update 3.19.0 it seemed to work, but now we have the problem again.

**Comment by DesertSunSal** [comment]
@everyone coming from google. Here is how to remedy this:

https://stackoverflow.com/questions/63552653/fix-pagination-after-wordpress-5-5-update

```
function pre_handle_404($preempt, $wp_query)
{
    if (isset($wp_query->query['page']) && $wp_query->query['page']) {
        return true;
    }

    return $preempt;
}
add_filter( 'pre_handle_404', 'pre_handle_404', 10, 2 );
```

**Comment by sergiy-talashko** [comment]
I had similar case:
Tabs with Grid Loop in each. Pagination like "infinite load" and "Load more btn" started working only when all Loop grids has enabled pagination.
If at least one has disabled pagination - other grids start return duplicate posts. 

Elementor - 3.20.2 Elementor Pro - 3.20.1

**Comment by dvdstrk** [comment]
Thank you, @DesertSunSal 


> @everyone coming from google. Here is how to remedy this:
> 
> https://stackoverflow.com/questions/63552653/fix-pagination-after-wordpress-5-5-update
> 
> ```
> function pre_handle_404($preempt, $wp_query)
> {
>     if (isset($wp_query->query['page']) && $wp_query->query['page']) {
>         return true;
>     }
> 
>     return $preempt;
> }
> add_filter( 'pre_handle_404', 'pre_handle_404', 10, 2 );
> ```

**Comment by lioncatde** [comment]
Same here. Unfortunately the snippet from @DesertSunSal  didn't work for me

**Comment by Exion98** [comment]
I have the same, identical problem, but I noticed a little thing, @orizzontiholding can you tell me if it happens to you too?
If I try to verify that the infinite scroll widget works on a PUBLISHED page or post, the problem obviously occurs. However, if the post or page IS NOT PUBLISHED, and is therefore a draft, then if I try to preview it, the loop grid widget and infinite scroll work correctly.

**Comment by junghee1128** [comment]
I am having the same issue after I add 2 more loop grids in a static template. "Load more" pagination keeps of loading the first set of posts. All loop grids have different sources, like everyone, I am using ACF Pro for custom post types.

Is there a fix to this?

**Comment by Exion98** [comment]
@junghee1128 I tried to replicate your situation and indeed this seems to be the problem, i.e. having more than one loop grid widget on the same page/post

**Comment by portrayaloflife** [comment]
Same issue here :[

**Comment by portrayaloflife** [comment]
@doronwolf Hey! Yeah still seeing it in 3.24, specifically the load more, just loads a bunch of copies of things already loaded. I saw randomly on reddit a fix worked where if ALL query loops you have on your site set Load On Click for their pagination it then works correctly. Which did work as a fix on one of our sites but not others. Happy to connect and share screen or make a clone sandbox for you to investigate.

**Comment by doronwolf** [comment]
Hi @portrayaloflife thank you very much for your replay - if you can record a video with detailed steps for reproducing the issue and past it here - I would really appreciate it and it will greatly help me to trying promote a fix🙏

**Comment by portrayaloflife** [comment]
@doronwolf Is there a private chat or email we could? Don't want to reveal client in the Github

**Comment by doronwolf** [comment]
I'm not sure..🤔
Hi @nicholaszein do we have a procedure for this kind of situation?

**Comment by nicholaszein** [comment]
@portrayaloflife, @doronwolf.

In this case, it'll require you to reach out to Elementor Support, mentioning this issue, and explaining that I asked you to reach out to share sensitive information.

It would be great if you could provide temporary access to the website in question using the [Temporary Login](https://wordpress.org/plugins/temporary-login/) so we could take a look ourselves, and make some tests.

We would be creating a copy of the site on a closed and safe environment, and once finished, delete the copy.

All the information shared would be protected under the confidentiality of the Elementor Support service.

All you have to ask them is to mention me in the ticket, and I'll be able to access the information.

Let me know if that is OK with you @portrayaloflife! 😉

**Comment by portrayaloflife** [comment]
On it!

**Comment by wachalala** [comment]
Same issue here... since month nothing has change :(

**Comment by sirmedina** [comment]
Same issue here, but with some (maybe) additional errors. Testing with more loops in page we notice that:

1. If the page is a draft, returns this error in the console and nothing happens:

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'getAttribute')
    at LoopLoadMore.handleSuccessFetch (load-more.376b5bcb2e56386f470e.bundle.min.js:2:4613)
    at load-more.376b5bcb2e56386f470e.bundle.min.js:2:5162
```

2. If the page is published, it just repeats posts in the loop.
3. On the page I'm testing, there is a Taxonomy Filter. After try to load more, filter stops to work, even on draft page.
4. **Removing other loops resolves the issue**, but we need more loops on page.

## Elementor System Info
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.11.9-MariaDB
	PHP Version: 8.1.27
	PHP Memory Limit: 6144M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 6144M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.6.2
	WP Multisite: No
	Max Upload Size: 6 GB
	Memory limit: 40M
	Max Memory limit: 6144M
	Permalink Structure: /blog/%postname%/
	Language: pt_BR
	Timezone: America/Sao_Paulo
	Admin Email: falecom@douglasmedina.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 3.1.1
	Author: Elementor Team
	Child Theme: No

== Active Plugins ==
	Advanced Post Queries Version: 1.1.3 Author: Shabti Kaplan
	Elementor Version: 3.24.7 Author: Elementor.com
	Elementor Pro Version: 3.24.4 Author: Elementor.com
	LiteSpeed Cache Version: 6.5.2 Author: LiteSpeed Technologies
	Meta pixel for WordPress Version: 4.0.1 Author: Facebook
	Redirection Version: 5.5.0 Author: John Godley
	Web Stories Version: 1.37.0 Author: Google
	WP-PostViews Version: 1.77 Author: Lester 'GaMerZ' Chan
	WP Activity Log Version: 5.2.1 Author: Melapress
	WPvivid Backup Plugin Version: 0.9.107 Author: WPvivid Team
	Yoast Duplicate Post Version: 4.5 Author: Enrico Battocchi & Team Yoast
	Yoast SEO Version: 23.7	Author: Team Yoast

== Configurações ==
	cpt_support: post, page, e-landing-page
	allow_tracking: yes
	editor_break_lines: 1
	unfiltered_files_upload: 1
	font_display: swap
	load_fa4_shim: yes

== Experimentos do Elementor ==
	Carregamento de CSS melhorado: Inativo por padrão
	Ícones de fontes em linha: Ativo
	Pontos de interrupção personalizados adicionais: Ativo
	Contêiner Flexbox: Ativo
	Contêiner de grade: Ativo
	Atualizar a biblioteca Swiper: Ativo
	Desempenho de elementos aninhados: Ativo por padrão
	Carregamento de controle otimizado: Ativo
	Marcação otimizada: Inativo por padrão
	Carregar condicionalmente os arquivos CSS do Swiper: Inativo por padrão
	Integração de plugins: Ativo por padrão
	Padrão para Novo Construtor de Tema: Ativo
	Cabeçalho e rodapé: Ativo
	Tela inicial do Elementor: Ativo por padrão
	Construa com IA: Inativo
	Páginas de destino: Ativo
	Lista de verificação do Launchpad: Inativo por padrão
	Elementos aninhados: Ativo
	Barra superior do editor: Ativo
	Painel de páginas: Inativo por padrão
	Cache de elementos: Ativo
	Link na biografia: Ativo por padrão
	Botões flutuantes: Ativo por padrão
	Eventos do editor do Elementor: Inativo por padrão
	Widgets atômicos: Inativo por padrão
	Exibir condições: Ativo
	Envios do formulário: Ativo
	Menu: Ativo

**Comment by colinosterndorf** [comment]
Experience this exact same problem. The provided code is working for one of my loop grids, but has stopped working on another.

**Comment by portrayaloflife** [comment]
@doronwolf Spun up the test site for you to review > Case #TSR1NU729465

**Comment by doronwolf** [comment]
Hi @portrayaloflife I'm trying to log in but it seems like your test site is down :(  
@nicholaszein is it working for you? 
![Screenshot 2024-11-03 at 8 38 13](https://github.com/user-attachments/assets/240aafa8-882e-4718-a13c-58f86f12f4a8)

**Comment by portrayaloflife** [comment]
Support already logged in and confirmed the bug and that dev team is aware
and working on a fix so we took it down.  :[


<https://apolloartistry.com/>

**Comment by doronwolf** [comment]
oh..bummer, o.k, 
but if you do want me to take a look, please bring it up again

**Comment by doronwolf** [comment]
right now I'm still failing to reproduce the issue on my end, I was hoping that picking in your site will help me understand what I'm missing

**Comment by portrayaloflife** [comment]
Support was able to reproduce so i’d recommend discussing internally, if you read the rest of the case they were able to reproduce. 

Elementor support:
“I could recreate the issue on my end as well. Seems like this is a bug. I have reported this to our dev team, and hopefully, they will fix it soon.”

“After extensive checking I have concluded that this is a bug with Infinite scrolling and Loading more functionalities in pagination options (infinite scroll, load on click) duplicates existing posts (single post template).

I found similar issues already reported to our development team. Please be assured that our development team is already working on fixing the bug, and we will include the fix in the upcoming updates.”

**Comment by doronwolf** [comment]
Cool, I'll try to reach the support agent who worked on it and take it from there

**Comment by portrayaloflife** [comment]
@doronwolf just revived it for ya actually. Let me know if you see it. Can review the bug on the “speakers” page. And site lock user/pass is “elementor”

**Comment by portrayaloflife** [comment]
bumping this @doronwolf

**Comment by doronwolf** [comment]
Hi @portrayaloflife sorry it took me so long to respond - I wasn't near any computer in the last few days and only now saw your bump
anyways.. logged in and started investigating and got stuck because a few strange things were going on (which might be related to the bug you are experiencing)

1. although the site is to use the 'Post name' structure (as it should) - all the links in the 'speakers' loop grid are using a 'Plain' permalink structure (and all lead to a 404 error), this is very odd
2. although the loop template and the loop grid display the speakers I can't find any 'speakers' posts/taxonomy/CPT and also the the query settings don't show them (see attached screenshot) so ..I can't look in the backend to check them
are they dependent on one of the deactivated plugins? 

I'm also asking this because I want to test if by recreating the loop I can eliminate the issue (because a new loop grid using v3.25 shouldn't have the issue) - but I can't recreate it because I can't replicate the same settings)

**Comment by portrayaloflife** [comment]
Strange I'm seeing it on my end >> 
<img width="339" alt="image" src="https://github.com/user-attachments/assets/c6a27d9b-5002-4465-9ba1-319cb8e26a38">

Also not seeing 404 pages. The slug and Post type in the back end is all visible for me. Can you connect with me in the ticketing system or via email? Can talk more in detail. 

ACF is there and the post type is working as expected on my end. 
<img width="176" alt="image" src="https://github.com/user-attachments/assets/50ad4233-a2ed-494d-ae7f-fde9196b38ef">

**Comment by doronwolf** [comment]
Hi @portrayaloflife ..o.k - so... I activated ACF and now the 'speakers' CPT is back!
after refreshing the permalink settings and refreshing the Speakers page it's back to normal.. I can now go on with the investigating

**Comment by portrayaloflife** [comment]
Great to hear!

**Comment by doronwolf** [comment]
@portrayaloflife how long can you keep this staging site alive, do we have a few more days? I need more time to consult with the members of our dev team 🙏

**Comment by portrayaloflife** [comment]
Of course! Just ping me end of week if possible!

**Comment by doronwolf** [comment]
can I edit the page with the issue? .. I might have a solution but it seems it's currently been edited by someone else

**Comment by portrayaloflife** [comment]
Yep! Sorry that was me investigating your earlier message, this is a sandbox just for this bug so make any edits you need!

**Comment by doronwolf** [comment]
O.K ..so for now it seems the issue is very likely related to the following facts

1. It happens only when there is more than one loop on the page (as you already mentioned)
2. the loop grid widget source is CPT (and not the native WordPress Posts)

I'm still looking for a solution but it will probably have to be in a patch release, I'll try to update here once I know more

**Comment by portrayaloflife** [comment]
Aye! Narrowing it down though! This is great, can't thank you enough!

**Comment by doronwolf** [comment]
as a temporary workaround - if you can maybe load the sponsors in an image gallery (instead of the loop) then the first loop will probably work fine (but we just for now, we will still try to provide a solution)

**Comment by ValUmali** [comment]
Hi, I also ran across this issue, but on the post widget, also have repeating posts with load more pagination. Looks like Elementor does not yet fix this?

As a workaround, I just added another post widget and just hid it and this fixed the duplicate issue.

**Comment by doronwolf** [comment]
Hi @portrayaloflife, I am just updating you that I was able to reproduce the issue on your site (as you already know) but I'm miserably failing to reproduce it on other sites and I'm not sure why, this is very weird ..so I'm still investigating

**Comment by gwillings** [comment]
We have a similar issue with a load more button, where the pagination repeatedly loads the same set of items.

Our page is `/news/`

When clicking on the "load more" button I see a network attempt to `/news/2/`.
This 301 redirects to `/news/` hence the continuous loop of pages. Are you also being 301 redirected?

In our case, the correct URL for us should be `/news/page/2/`. 

The URL for pagination is being returned from `get_wp_link_page` in `post-base.php` (as far as I can see).

**Comment by daveedbach** [comment]
Same here, also already contacted the support multiple times in the hope of speeding up the solution to this major problem:

https://www.all-active.net/wandern/
Also when you tap on "Fischen" where I only have 4 posts so far, it sometimes doesnt show them all but rather randomly decides, how many  to show...

And the "Load More" Button appears pressed after clicking it for the first time, which is also looking rather not cool.
Thanks in advance for your saving help!

**Comment by asen0v** [comment]
Thank you @gwillings this worked for me!!!! LEGEND

**Comment by dmcneary** [comment]
I am also seeing this issue when using the Posts widget. I have a blog page which loads standard Posts with a "Blog" category assigned and Load on Click pagination, along with a Spotlight Posts section which loads Blog Posts with a tag of "spotlight". Removing the 2nd "spotlight" Posts widget does not fix the issue of duplicate posts appearing in the "Blog" Posts widget when pagination is enabled and the Load on Click button is clicked.

**Comment by gary-SA** [comment]
Same issue again for me. It's been working fine until the recent update of Elementor Pro to 3.25.4. I also tried php provided by @DesertSunSal, but it doesn't work when filtering category unfortunately.

**Comment by nimaaghdaei** [comment]
I had a similar problem with the load more button, then I created one of the loops in the section template and called its shortcode inside the page and my problem was solved.
Maybe this will help you.

**Comment by GeminiKiller** [comment]
> Thank you, [@DesertSunSal](https://github.com/DesertSunSal)
> 
> > [@everyone](https://github.com/everyone) coming from google. Here is how to remedy this:
> > https://stackoverflow.com/questions/63552653/fix-pagination-after-wordpress-5-5-update
> > ```
> > function pre_handle_404($preempt, $wp_query)
> > {
> >     if (isset($wp_query->query['page']) && $wp_query->query['page']) {
> >         return true;
> >     }
> > 
> >     return $preempt;
> > }
> > add_filter( 'pre_handle_404', 'pre_handle_404', 10, 2 );
> > ```

THIS MADE MY DAY. it worked to fix the looping repeated post for loop grid issue!
