### ISSUE TITLE
⛔ 🧩 🐞 CSS files not generated (nor regenerate) with W3 Total Cache Azure CDN

### ISSUE THREAD

**Issue by shane-js** [elementor/elementor#25075]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Hello team - thank you for your hard work on this product. I am a bit new to Wordpress in general and even more so to Elementor so I apologize in advance if I do not get something right. I have tried for days on my own to figure this out and have ended up here.

I have bought a theme which uses Elementor. When I've installed the theme on a basically off the shelf instance of Azure Wordpress with the checkbox to use Azure CDN which uses W3 Total Cache (again everything as configured by Microsoft) I get 404s on the CSS files for posts made in Elementor.

Even if I attempt to regenerate them. In fact there is no "elementor" directory even made in the wp-content/uploads path in the blob storage account. The only thing I have found that works is if I switch 'CSS Print Method' from 'external file' to 'internal embedding'.

It seems Azure Wordpress ships with "Organize my uploads into month- and year-based folders" so all my directories in uploads are year folders. Not sure if that is relevant.

These are the most fitting items I've found and commented on but did not hear back so after a bit thought it would be okay to open this:
1. Closed issue:  https://github.com/elementor/elementor/issues/7237
2. Discussion: https://github.com/orgs/elementor/discussions/18987

For step: "This bug happens when only the Elementor (and Elementor Pro) plugins are active." I cannot in good faith check this because of course it relies on the W3 setup but I feel that this is not atypical use case (W3 seems massively popular and Azure is a pretty large cloud offering).

Note: I will be unavailable for a few days.

### Steps to reproduce

1. Create a default Azure Wordpress service (believe this is free)
2. Install Elementor based theme that has posts already made (I used Stratus from Themeforest)
3. Note 404s on the post's CSS calls
(4 optional: Note switching to Hello theme at this point has same issue)

### Expected behavior

1. Create a default Azure Wordpress service (believe this is free)
2. Install Elementor based theme that has posts already made (I used Stratus from Themeforest)
3. post's CSS calls are successful

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt

== Server Environment ==
	Operating System: Linux
	Software: nginx/1.24.0
	MySQL version: Source distribution v8.0.34
	PHP Version: 8.2.15
	PHP Memory Limit: 512M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.4.3
	Site URL: redacted
	Home URL: redacted
	WP Multisite: No
	Max Upload Size: 50 MB
	Memory limit: 128M
	Max Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Stratus - Child Theme
	Version: 4.0
	Author: Themovation
	Child Theme: Yes
	Parent Theme Name: Stratus
	Parent Theme Version: 4.2.4
	Parent Theme Author: Themovation

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36

== Active Plugins ==
	App Service Email
		Version: 1.0.0
		Author: Microsoft

	Elementor
		Version: 3.19.1
		Author: Elementor.com

	Envato Market
		Version: 2.0.9
		Author: Envato

	Kirki Customizer Framework
		Version: 5.0.0
		Author: Themeum

	OptionTree
		Version: 2.7.3
		Author: Derek Herman

	Page Builder Widget Pack
		Version: 2.2.6
		Author: Themovation

	W3 Total Cache
		Version: 2.6.1
		Author: BoldGrid


== Elementor Experiments ==
	Improved Asset Loading: Active by default
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Upgrade Swiper Library: Inactive by default
	Grid Container: Inactive by default
	Editor Top Bar: Inactive by default
	Optimized Gutenberg Loading: Active by default
	Build with AI: Active by default
	Landing Pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default
	Optimize Image Loading: Active by default
	Global Style Guide: Active by default


== Log ==
	
Log: showing 20 of 402024-02-06 03:48:43 [info] elementor::elementor_updater Started 
2024-02-06 03:48:43 [info] Elementor/Upgrades - _on_each_version Start  
2024-02-06 03:48:49 [info] Elementor/Upgrades - _on_each_version Finished 
2024-02-06 03:48:49 [info] Elementor/Upgrades - _v_3_2_0_migrate_breakpoints_to_new_system Start  
2024-02-06 03:53:40 [info] elementor::elementor_updater Started 
2024-02-06 03:53:40 [info] Elementor/Upgrades - _on_each_version Start  
2024-02-06 03:53:43 [info] Elementor/Upgrades - _on_each_version Finished 
2024-02-06 03:53:43 [info] Elementor/Upgrades - _v_3_2_0_migrate_breakpoints_to_new_system Start  
2024-02-06 03:53:43 [info] Elementor/Upgrades - _v_3_2_0_migrate_breakpoints_to_new_system Finished 
2024-02-06 03:53:43 [info] Elementor/Upgrades - _v_3_4_8_fix_font_awesome_default_value_from_1_to_yes Start  
2024-02-06 03:53:43 [info] Elementor/Upgrades - _v_3_4_8_fix_font_awesome_default_value_from_1_to_yes Finished 
2024-02-06 03:53:43 [info] Elementor/Upgrades - _v_3_5_0_remove_old_elementor_scheme Start  
2024-02-06 03:53:43 [info] Elementor/Upgrades - _v_3_5_0_remove_old_elementor_scheme Finished 
2024-02-06 03:53:44 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Start  
2024-02-06 03:53:44 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Finished 
2024-02-06 03:53:44 [info] Elementor/Upgrades - _v_3_16_0_container_updates Start  
2024-02-06 03:53:44 [info] Elementor/Upgrades - _v_3_16_0_container_updates Finished 
2024-02-06 03:53:44 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Start  
2024-02-06 03:53:44 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Finished 
2024-02-06 03:53:44 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.14',
  'to' => '3.19.1',
)]

PHP: showing 3 of 3PHP: 2024-02-06 03:24:24 [error X 5][../wp-content/plugins/elementor/core/upgrade/upgrades.php::736] Uncaught Error: Call to a member function get_meta() on bool in ../wp-content/plugins/elementor/core/upgrade/upgrades.php:736
Stack trace:
#0 ../wp-content/plugins/elementor/core/upgrade/upgrades.php(909): Elementor\Core\Upgrade\Upgrades::Elementor\Core\Upgrade\{closure}('4973')
#1 ../wp-content/plugins/elementor/core/upgrade/upgrades.php(770): Elementor\Core\Upgrade\Upgrades::move_settings_to_kit(Object(Closure), Object(Elementor\Core\Upgrade\Updater), true)
#2 [internal function]: Elementor\Core\Upgrade\Upgrades::_v_3_2_0_migrate_breakpoints_to_new_system(Object(Elementor\Core\Upgrade\Updater))
#3 ../wp-content/plugins/elementor/core/base/background-task.php(274): call_user_func(Array, Object(Elementor\Core\Upgrade\Updater))
#4 ../wp-content/plugins/elementor/core/base/background-task.php(178): Elementor\Core\Base\Background_Task->task(Array)
#5 ../wp-content/plugins/elementor/core/base/background-task.php(133): Elementor\Core\Base\Background_Task->handle()
#6 ../wp-includes/class-wp-hook.php(324): Elementor\Core\Base\Background_Task->handle_cron_healthcheck()
#7 ../wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#8 ../wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#9 ../wp-cron.php(191): do_action_ref_array('elementor_1_ele...', Array)
#10 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-02-06 03:31:16 [error X 1][../wp-content/plugins/elementor/core/upgrade/upgrades.php::736] Uncaught Error: Call to a member function get_meta() on bool in ../wp-content/plugins/elementor/core/upgrade/upgrades.php:736
Stack trace:
#0 ../wp-content/plugins/elementor/core/upgrade/upgrades.php(909): Elementor\Core\Upgrade\Upgrades::Elementor\Core\Upgrade\{closure}('4973')
#1 ../wp-content/plugins/elementor/core/upgrade/upgrades.php(770): Elementor\Core\Upgrade\Upgrades::move_settings_to_kit(Object(Closure), Object(Elementor\Core\Upgrade\Updater), true)
#2 [internal function]: Elementor\Core\Upgrade\Upgrades::_v_3_2_0_migrate_breakpoints_to_new_system(Object(Elementor\Core\Upgrade\Updater))
#3 ../wp-content/plugins/elementor/core/base/background-task.php(274): call_user_func(Array, Object(Elementor\Core\Upgrade\Updater))
#4 ../wp-content/plugins/elementor/core/base/background-task.php(178): Elementor\Core\Base\Background_Task->task(Array)
#5 ../wp-content/plugins/elementor/core/base/background-task.php(133): Elementor\Core\Base\Background_Task->handle()
#6 ../wp-includes/class-wp-hook.php(324): Elementor\Core\Base\Background_Task->handle_cron_healthcheck()
#7 ../wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#8 ../wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#9 ../wp-cron.php(191): do_action_ref_array('elementor_1_ele...', Array)
#10 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-02-06 03:31:51 [error X 1][../wp-content/plugins/elementor/includes/managers/controls.php::476] Uncaught Error: Class "Elementor\Group_Control_Box_Shadow" not found in ../wp-content/plugins/elementor/includes/managers/controls.php:476
Stack trace:
#0 ../wp-content/plugins/elementor/includes/managers/controls.php(621): Elementor\Controls_Manager->register_controls()
#1 ../wp-content/plugins/elementor/includes/managers/controls.php(640): Elementor\Controls_Manager->get_controls()
#2 ../wp-content/plugins/elementor/includes/managers/controls.php(812): Elementor\Controls_Manager->get_control('section')
#3 ../wp-content/plugins/elementor/includes/base/controls-stack.php(453): Elementor\Controls_Manager->add_control_to_stack(Object(Elementor\Core\Kits\Documents\Kit), 'document_settin...', Array, Array)
#4 ../wp-content/plugins/elementor/includes/base/controls-stack.php(1547): Elementor\Controls_Stack->add_control('document_settin...', Array)
#5 ../wp-content/plugins/elementor/core/base/document.php(1745): Elementor\Controls_Stack->start_controls_section('document_settin...', Array)
#6 ../wp-content/plugins/elementor/core/kits/documents/kit.php(146): Elementor\Core\Base\Document->register_document_controls()
#7 ../wp-content/plugins/elementor/includes/base/controls-stack.php(2358): Elementor\Core\Kits\Documents\Kit->register_controls()
#8 ../wp-content/plugins/elementor/includes/base/controls-stack.php(541): Elementor\Controls_Stack->init_controls()
#9 ../wp-content/plugins/elementor/includes/base/controls-stack.php(313): Elementor\Controls_Stack->get_stack()
#10 ../wp-content/plugins/elementor/includes/base/controls-stack.php(2445): Elementor\Controls_Stack->get_controls()
#11 ../wp-content/plugins/elementor/includes/base/controls-stack.php(1130): Elementor\Controls_Stack->sanitize_settings(Array)
#12 ../wp-content/plugins/elementor/includes/base/controls-stack.php(2190): Elementor\Controls_Stack->get_data('settings')
#13 ../wp-content/plugins/elementor/core/base/base-object.php(142): Elementor\Controls_Stack->get_init_settings()
#14 ../wp-content/plugins/elementor/core/base/base-object.php(40): Elementor\Core\Base\Base_Object->ensure_settings()
#15 ../wp-content/plugins/elementor/core/kits/manager.php(117): Elementor\Core\Base\Base_Object->get_settings('viewport_mobile')
#16 ../wp-content/plugins/elementor/core/breakpoints/breakpoint.php(130): Elementor\Core\Kits\Manager->get_current_settings('viewport_mobile')
#17 ../wp-content/plugins/elementor/core/breakpoints/breakpoint.php(71): Elementor\Core\Breakpoints\Breakpoint->init_value()
#18 ../wp-content/plugins/elementor/core/breakpoints/breakpoint.php(88): Elementor\Core\Breakpoints\Breakpoint->get_value()
#19 ../wp-content/plugins/elementor/core/breakpoints/manager.php(195): Elementor\Core\Breakpoints\Breakpoint->is_custom()
#20 ../wp-content/plugins/elementor/includes/frontend.php(540): Elementor\Core\Breakpoints\Manager->has_custom_breakpoints()
#21 ../wp-includes/class-wp-hook.php(324): Elementor\Frontend->register_styles('')
#22 ../wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#23 ../wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#24 ../wp-includes/script-loader.php(2262): do_action('wp_enqueue_scri...')
#25 ../wp-includes/class-wp-hook.php(324): wp_enqueue_scripts('')
#26 ../wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#27 ../wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#28 ../wp-includes/general-template.php(3052): do_action('wp_head')
#29 ../wp-content/themes/stratusx/templates/head.php(10): wp_head()
#30 ../wp-includes/template.php(792): require('/home/site/wwwr...')
#31 ../wp-includes/template.php(725): load_template('/home/site/wwwr...', false, Array)
#32 ../wp-includes/general-template.php(206): locate_template(Array, true, false, Array)
#33 ../wp-content/themes/stratusx/base.php(10): get_template_part('templates/head')
#34 ../wp-includes/template-loader.php(106): include('/home/site/wwwr...')
#35 ../wp-blog-header.php(19): require_once('/home/site/wwwr...')
#36 ../index.php(17): require('/home/site/wwwr...')
#37 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hello @shane-js,

Thank you for reaching out! 🙏 

### ⛔ 🧩 Please note that while we do welcome bug reports, we can't provide support for 3rd-party services.

From your report, it seems there is some misconfiguration with your Azure CDN integration with WordPress. Something specific to your website. I would re-check all the settings, and would also check writing permissions on your server, could be that it might be blocking Elementor from creating the required folder (check your server logs). The files should at least be found locally.

The "CSS Print Method" setting was created to deal with cases just like yours, so switching it to "Internal Embedding" would be the only solution we can recommend here.

Regards
