### ISSUE TITLE
⛔ 🐞 No more "Size" option dropdown in Heading Widget in last update 3.19

### ISSUE THREAD

**Issue by APEWAW** [elementor/elementor#25080]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Hello, 

The "Size" option dropdown in Heading Widget disappeared with the last 3.19 update.
I had to roll back to 18.3 to fix the problem.

![Capture d’écran 2024-02-09 à 12 03 45](https://github.com/elementor/elementor/assets/17066439/9a0429b8-77fa-46df-8bf9-0c7371fb654f)

### Steps to reproduce

The "Size" option dropdown in Heading Widget disappeared with the last 3.19 update.

### Expected behavior

I had to roll back to 18.3 to fix the problem.

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [ ] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt

== Server Environment ==
	Operating System: Darwin
	Software: nginx/1.16.0
	MySQL version: MySQL Community Server - GPL v8.0.16
	PHP Version: 8.1.23
	PHP Memory Limit: 256M
	PHP Max Input Vars: 4000
	PHP Max Post Size: 1000M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.4.3
	Site URL: http://csc.local
	Home URL: http://csc.local
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-GB
	Timezone: Europe/Brussels
	Debug Mode: Inactive

== Theme ==
	Name: Anesta Child
	Version: 1.0
	Author: AncoraThemes
	Child Theme: Yes
	Parent Theme Name: Anesta
	Parent Theme Version: 1.1.1
	Parent Theme Author: AncoraThemes

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0

== Active Plugins ==
	Advanced Custom Fields
		Version: 6.2.6.1
		Author: WP Engine

	Contact Form 7
		Version: 5.8.7
		Author: Takayuki Miyoshi

	Duplicate Page
		Version: 4.5.3
		Author: mndpsingh287

	Elementor
		Version: 3.18.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.19.0
		Author: Elementor.com

	List Custom Taxonomy Widget
		Version: 4.1
		Author: Nick Halsey

	Media Library Helper by Codexin
		Version: 1.3.0
		Author: Codexin Technologies

	ShareThis Share Buttons
		Version: 2.2.0
		Author: ShareThis

	The Events Calendar
		Version: 6.3.2
		Author: The Events Calendar

	ThemeREX Addons
		Version: 2.27.5
		Author: ThemeREX

	Widget Context
		Version: 1.3.2
		Author: Kaspars Dambis

	Yoast SEO
		Version: 22.0
		Author: Team Yoast


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved asset loading: Active
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Active
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Inactive by default
	Grid Container: Inactive by default
	Default to New Theme Builder: Active by default
	Editor Top Bar: Inactive by default
	Optimized Gutenberg Loading: Active by default
	Build with AI: Inactive
	Landing pages: Inactive
	Nested Elements: Active
	Lazy Load Background Images: Active
	Optimize Image Loading: Active by default
	Global Style Guide: Active by default
	Page Transitions: Active by default
	Notes: Inactive
	Display Conditions: Active
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Menu: Inactive by default
	Taxonomy Filter: Active


== Log ==
	
JS: showing 11 of 11JS: 2024-01-04 14:54:36 [error X 14][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.18.3:3:806804] this.store.find(...) is undefined 
JS: 2024-01-09 13:43:51 [error X 10][../wp-content/plugins/elementor/assets/js/admin.min.js?ver=3.18.3:3:47920] l[0] is undefined 
JS: 2024-01-11 12:55:14 [error X 2][../wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.18.2:2:64227] can&#039;t convert undefined to object 
JS: 2024-01-11 12:59:11 [error X 14][../wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.18.3:3:14246] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got as `bg_image` value. Expected array or object.',
)]
JS: 2024-01-11 14:48:43 [error X 5][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.18.3:3:930190] $e.routes.getHistory(...).reverse()[0] is undefined 
JS: 2024-01-11 16:01:27 [error X 2][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.18.3:3:690111] this.model.isValidChild is not a function 
JS: 2024-01-17 08:31:27 [error X 11][../wp-content/plugins/elementor/assets/js/4fdaa70e951ad90db2f2.bundle.min.js:2:7765] t.target.closest(...) is null 
JS: 2024-01-26 13:44:40 [error X 2][http://csc.local/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.18.3:3:640680] this.view.container is undefined 
JS: 2024-01-30 14:07:49 [error X 1][http://csc.local/wp-content/plugins/wordpress-seo/js/dist/elementor.js?ver=426995690b492d03001cb1ba67c1f4d7:584:3872] e is null 
JS: 2024-01-31 12:57:04 [error X 2][http://csc.local/wp-content/plugins/elementor/assets/js/admin.min.js?ver=3.19.0:3:47917] c[0] is undefined 
JS: 2024-02-09 10:54:47 [error X 4][http://csc.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10:96134] Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&amp;args[]=undefined&amp;args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 

PHP: showing 6 of 6PHP: 2024-01-08 16:47:15 [warning X 3][../wp-content/plugins/elementor/modules/history/revisions-manager.php::363] Undefined array key &quot;editor_post_id&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-01-09 14:45:42 [notice X 2][../wp-content/plugins/elementor-pro/modules/screenshots/module.php::33] Function utf8_decode() is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-01-11 11:43:22 [error X 2][../wp-content/plugins/elementor/core/wp-api.php::26] Uncaught Error: Call to undefined function Elementor\Core\get_plugins() in ../wp-content/plugins/elementor/core/wp-api.php:26
Stack trace:
#0 ../wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(96): Elementor\Core\Wp_Api-&gt;get_plugins()
#1 ../wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(58): Elementor\Modules\CompatibilityTag\Base_Module-&gt;get_plugins_with_header()
#2 ../wp-content/plugins/elementor/modules/compatibility-tag/module.php(57): Elementor\Modules\CompatibilityTag\Base_Module-&gt;get_plugins_to_check()
#3 ../wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(148): Elementor\Modules\CompatibilityTag\Module-&gt;get_plugins_to_check()
#4 ../wp-includes/class-wp-hook.php(324): Elementor\Modules\CompatibilityTag\Base_Module-&gt;Elementor\Modules\CompatibilityTag\{closure}()
#5 ../wp-includes/class-wp-hook.php(348): WP_Hook-&gt;apply_filters()
#6 ../wp-includes/plugin.php(517): WP_Hook-&gt;do_action()
#7 ../wp-content/plugins/elementor/modules/system-info/module.php(340): do_action()
#8 ../wp-content/plugins/elementor/includes/tracker.php(241): Elementor\Modules\System_Info\Module::get_allowed_reports()
#9 ../wp-content/plugins/elementor/includes/tracker.php(530): Elementor\Tracker::get_system_reports_data()
#10 ../wp-content/plugins/elementor/includes/tracker.php(141): Elementor\Tracker::get_tracking_data()
#11 ../wp-includes/class-wp-hook.php(324): Elementor\Tracker::send_tracking_data()
#12 ../wp-includes/class-wp-hook.php(348): WP_Hook-&gt;apply_filters()
#13 ../wp-includes/plugin.php(565): WP_Hook-&gt;do_action()
#14 ../wp-cron.php(191): do_action_ref_array()
#15 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-01-11 14:02:24 [warning X 3][../wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-url.php::34] Undefined array key 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-01-22 17:09:15 [warning X 9][../wp-content/plugins/elementor-pro/modules/posts/skins/skin-content-base.php::265] Attempt to read property &quot;ID&quot; on null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-01-26 15:51:44 [warning X 13][../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key &quot;condition_type&quot; [array (
  'trace' => '
#0: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: ../wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]

Log: showing 20 of 252024-01-19 10:29:42 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.18.2',
  'to' => '3.18.3',
)]
2024-01-19 10:29:44 [info] elementor-pro::elementor_pro_updater Started 
2024-01-19 10:29:44 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-01-19 10:29:44 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-01-19 10:29:44 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.18.2',
  'to' => '3.18.3',
)]
2024-01-30 10:59:14 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.18.3',
  'to' => '3.19.0',
)]
2024-01-30 10:59:14 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.18.3',
  'to' => '3.19.0',
)]
2024-01-30 10:59:14 [info] elementor::elementor_updater Started 
2024-01-30 10:59:14 [info] Elementor/Upgrades - _on_each_version Start  
2024-01-30 10:59:15 [info] Elementor/Upgrades - _on_each_version Finished 
2024-01-30 10:59:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.18.3',
  'to' => '3.19.0',
)]
2024-01-30 10:59:15 [info] elementor-pro::elementor_pro_updater Started 
2024-01-30 10:59:15 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-01-30 10:59:15 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-01-30 10:59:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.18.3',
  'to' => '3.19.0',
)]
2024-02-09 11:48:00 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.19.0',
  'to' => '3.19.2',
)]
2024-02-09 11:48:00 [info] elementor::elementor_updater Started 
2024-02-09 11:48:00 [info] Elementor/Upgrades - _on_each_version Start  
2024-02-09 11:48:00 [info] Elementor/Upgrades - _on_each_version Finished 
2024-02-09 11:48:00 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.19.0',
  'to' => '3.19.2',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by Daveden2** [comment]
@APEWAW, this isn't a bug. The feature was deprecated and has been removed. You're encouraged to use the Global Typography instead

You can see it in the changelog for Elementor Free 3.19.0 - https://wordpress.org/plugins/elementor/#developers

**Comment by nicholaszein** [comment]
Hello @APEWAW,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. 
This feature was discontinued on the Heading and other widgets with different size options. You'll only see it in existing widgets that have that setting changed. Otherwise, it won't be available for new instances of the Heading widget.

### 👍 For now, that's all we can help with. 

Kind regards
