### ISSUE TITLE
⛔ WooCommerce My Account widget styles are not appearing in the frontend

### ISSUE THREAD

**Issue by StenderIternum** [elementor/elementor#25134]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

The widget for displaying "my account" in woocommerce doesn't seem to work - No matter what styles I apply, or what page I put it on - connected to woocommerce or not, it just keeps the styling from hello theme. 

![ftOX6VokV1](https://github.com/elementor/elementor/assets/91883306/4210cd9e-cc19-43fd-9983-f12d5b6c859f)

I have tried to disable most plugins, and there is nothing in the debug_log.

### Steps to reproduce

1) install woocommerce and elementor pro and Hello theme (I am using hello theme child found here on github)
2) Set up a my-account page in woocommerce - 
3) Edit that page with elementor
4) Use the elementor pro widget for displaying account. 
5) Save the page
6) Go to the frontend
7) See it fail. 

### Expected behavior

The styling looks fine in the editor - But not on frontend - I would expect that those two would correlate 

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt

== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: Percona Server (GPL), Release 48, Revision 497f936a373 v5.7.44-48
	PHP Version: 8.1.26
	PHP Memory Limit: 512M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.4.3
	Site URL: xxxxxxxx
	Home URL: xxxxxxxxx
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: da-DK
	Timezone: 1
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 3.0.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: da_DK
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36

== Active Plugins ==
	Crocoblock Wizard
		Version: 1.2.8
		Author: Crocoblock

	Elementor
		Version: 3.19.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.19.2
		Author: Elementor.com

	Envato Elements
		Version: 2.0.12
		Author: Envato

	JetElements For Elementor
		Version: 2.6.15
		Author: Crocoblock

	JetEngine
		Version: 3.3.5
		Author: Crocoblock

	JetTabs For Elementor
		Version: 2.2.1
		Author: Crocoblock

	JetTricks
		Version: 1.4.8
		Author: Crocoblock

	UpdraftPlus - Backup/Restore
		Version: 1.23.16
		Author: UpdraftPlus.Com, DavidAnderson

	VVS time ekstra felter
		Version: 0.4
		Author: Iternum Digital

	WooCommerce
		Version: 8.5.1
		Author: Automattic

	WooCommerce to webCRM Integration
		Version: 1.1
		Author: Iternum Digital

	Woo Subscriptions
		Version: 5.8.0
		Author: WooCommerce

	Yoast Duplicate Post
		Version: 4.5
		Author: Enrico Battocchi & Team Yoast


== Elements Usage ==
	
	footer : 1
		container : 9
		heading : 2
		icon-list : 3
		image : 1
		social-icons : 1
		text-editor : 2
	header : 1
		button : 6
		container : 7
		icon-list : 1
		image : 1
		nav-menu : 1
		woocommerce-menu-cart : 1
	page : 4
		button : 10
		container : 1
		divider : 2
		google_maps : 1
		heading : 18
		icon : 5
		icon-box : 11
		icon-list : 4
		image : 9
		spacer : 2
		text-editor : 20
	popup : 1
		button : 1
		container : 3
		divider : 1
		heading : 1
		image : 1
		jet-headline : 1
		text-editor : 1
	section : 4
		button : 2
		divider : 3
		heading : 6
		icon-box : 1
		icon-list : 5
		image : 2
		image-carousel : 1
		price-list : 1
		slides : 1
		social-icons : 1
		spacer : 1
		text-editor : 6
	wp-page : 9
		button : 24
		container : 170
		divider : 18
		form : 2
		heading : 32
		icon : 3
		icon-box : 33
		icon-list : 20
		image : 11
		jet-animated-text : 1
		jet-headline : 29
		jet-progress-bar : 2
		jet-timeline : 1
		lottie : 1
		nested-accordion : 3
		nested-carousel : 1
		nested-tabs : 3
		text-editor : 48
		woocommerce-cart : 1
		woocommerce-checkout-page : 1
		woocommerce-my-account : 1
	product-post : 0
		button : 1
		container : 9
		divider : 1
		heading : 4
		icon-list : 3
		jet-headline : 2
		shortcode : 1
		text-editor : 4
		wc-add-to-cart : 1


== Indstillinger ==
	
	cpt_support: post, page, product
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap


== Funktioner ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrationer ==
	
	woocommerce: Aktiv


== Elementor Experiments ==
	Forbedret ressourceindlæsning : Aktiv som standard
	Forbedret indlæsning af CSS ressourcer: Aktiv som standard
	Inline Font Icons: Aktiv som standard
	Additional Custom Breakpoints: Aktiv som standard
	admin_menu_rearrangement: Inaktiv som standard
	Flexbox Container: Aktiv som standard
	Upgrade Swiper Library: Aktiv som standard
	Grid Container: Inaktiv som standard
	Default to New Theme Builder: Aktiv som standard
	Hello sidehoved og sidefod: Aktiv som standard
	Editor Top Bar: Inaktiv som standard
	Optimeret Gutenberg-indlæsning: Aktiv som standard
	Build with AI: Inaktiv
	Landingsside: Aktiv som standard
	Nested Elements: Aktiv
	Lazy Load baggrundsbilleder: Inaktiv som standard
	Optimize Image Loading: Aktiv som standard
	Global Style Guide: Aktiv som standard
	Page Transitions: Inaktiv
	Notes: Aktiv som standard
	Visningsbetingelser: Inaktiv som standard
	Modtagne formularer: Aktiv som standard
	Scroll Snap: Aktiv som standard
	Menu: Inaktiv som standard
	Taxonomy Filter: Inaktiv som standard


== Log ==
	
Log: showing 20 of 342024-02-06 14:58:12 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.18.3',
  'to' => '3.19.1',
)]
2024-02-06 14:58:23 [info] elementor-pro::elementor_pro_updater Started 
2024-02-06 14:58:23 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-02-06 14:58:23 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-02-06 14:58:23 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.18.3',
  'to' => '3.19.1',
)]
2024-02-06 14:58:23 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.18.3',
  'to' => '3.19.1',
)]
2024-02-06 15:02:03 [info] elementor::elementor_updater Started 
2024-02-06 15:02:03 [info] Elementor/Upgrades - _on_each_version Start  
2024-02-06 15:02:03 [info] Elementor/Upgrades - _on_each_version Finished 
2024-02-06 15:02:03 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.18.3',
  'to' => '3.19.1',
)]
2024-02-14 15:02:20 [info] elementor-pro::elementor_pro_updater Started 
2024-02-14 15:02:20 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-02-14 15:02:20 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-02-14 15:02:20 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.19.1',
  'to' => '3.19.2',
)]
2024-02-14 15:02:20 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.19.1',
  'to' => '3.19.2',
)]
2024-02-14 15:02:44 [info] elementor::elementor_updater Started 
2024-02-14 15:02:44 [info] Elementor/Upgrades - _on_each_version Start  
2024-02-14 15:02:45 [info] Elementor/Upgrades - _on_each_version Finished 
2024-02-14 15:02:45 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.19.1',
  'to' => '3.19.2',
)]
2024-02-14 15:02:45 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.19.1',
  'to' => '3.19.2',
)]

JS: showing 5 of 5JS: 2024-01-04 09:41:46 [error X 1][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.18.3:3:54595] Cannot read properties of undefined (reading 'activate') 
JS: 2024-01-24 13:58:00 [error X 4][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.18.3:3:690111] this.model.isValidChild is not a function 
JS: 2024-01-25 10:08:48 [error X 16665][../wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:14799] Cannot read properties of null (reading 'clone') 
JS: 2024-01-25 10:08:49 [error X 284][../wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:19552] Cannot read properties of null (reading 'changestop') 
JS: 2024-02-14 13:31:08 [error X 1][../wp-content/plugins/jet-tricks/assets/js/jet-tricks-frontend.js?ver=1.4.8:660:28] Cannot read properties of undefined (reading 'hasOwnProperty') 

PHP: showing 4 of 4PHP: 2024-01-23 10:16:18 [notice X 4][../wp-content/plugins/elementor/includes/utils.php::727] strtolower(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-01-25 13:22:56 [warning X 6][../wp-content/plugins/elementor/includes/managers/image.php::113] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-01-26 08:01:53 [error X 1][../wp-content/plugins/elementor/data/v2/base/controller.php::227] Uncaught Elementor\Data\V2\Base\Exceptions\WP_Error_Exception: Method 'WP_REST_Controller::get_item_permissions_check' not implemented. Must be overridden in subclass. in ../wp-content/plugins/elementor/data/v2/base/controller.php:227
Stack trace:
#0 ../wp-content/plugins/elementor/data/v2/base/base-route.php(105): Elementor\Data\V2\Base\Controller->get_permission_callback()
#1 ../wp-content/plugins/elementor/data/v2/base/base-route.php(242): Elementor\Data\V2\Base\Base_Route->get_permission_callback()
#2 ../wp-includes/rest-api/class-wp-rest-server.php(1160): Elementor\Data\V2\Base\Base_Route->Elementor\Data\V2\Base\{closure}()
#3 ../wp-includes/rest-api/class-wp-rest-server.php(1041): WP_REST_Server->respond_to_request()
#4 ../wp-includes/rest-api/class-wp-rest-server.php(431): WP_REST_Server->dispatch()
#5 ../wp-includes/rest-api.php(424): WP_REST_Server->serve_request()
#6 ../wp-includes/class-wp-hook.php(324): rest_api_loaded()
#7 ../wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#8 ../wp-includes/plugin.php(565): WP_Hook->do_action()
#9 ../wp-includes/class-wp.php(418): do_action_ref_array()
#10 ../wp-includes/class-wp.php(813): WP->parse_request()
#11 ../wp-includes/functions.php(1336): WP->main()
#12 ../wp-blog-header.php(16): wp()
#13 ../index.php(17): require('/var/www/www.vv...')
#14 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-02-05 11:32:36 [notice X 31][../wp-content/plugins/elementor-pro/modules/woocommerce/module.php::626] parse_str(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Kompatibilitet ikke specificeret
	JetElements For Elementor: Kompatibilitet ikke specificeret
	JetTabs For Elementor: Kompatibilitet ikke specificeret

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by StenderIternum** [comment]
Okay - Apparently it happens every time that the cart is empty

**Comment by hein-obox** [comment]
Is this related to the Woocommerce Blocks approach? @nicholaszein

**Comment by nicholaszein** [comment]
I'm not sure @hein-obox, I could not reproduce this issue. I'm still trying to test it out. The my account styles have no correlation with the mini cart.

**Comment by nicholaszein** [comment]
Hello @StenderIternum,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
As you can see in the video below, we have no problems seeing the My Account styles in the frontend of our site.
We also made a lot of tests, and the only case we could reproduce this issue was when enabling cache. Which means your problem is not caused by Elementor, but actually by your server cache. The reason why you can see the changes when the cart has products, is because the LiteSpeed cache only cached the pages without products in the cart. When there are products in the cart, it needs to download the styles again, so it shows the correct styles.


https://github.com/elementor/elementor/assets/113993460/78cc68bc-9670-41ea-a956-070e6a65b936



### ✅ What you can do to solve your issue:
The solution for this issue is already well documented in our Help Center. https://elementor.com/help/changes-dont-appear-online/

Clear your cache, and if possible temporarily deactivate it until you have finished building your website, otherwise you will always have to purge and clear the LiteSpeed cache every time you make changes to any page.

If you don't like to follow this procedure, consider changing the **CSS Print Method** to **`Internal Embedded`** in your WordPress Dashboard > Elementor > Settings > Advanced page.

Please, next time follow the instructions and troubleshoot your issue before posting.

### 👍 For now, that's all we can help with. 

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
