### ISSUE TITLE
⛔ 📚 !important is not added to global color selector css

### ISSUE THREAD

**Issue by Luke-SF** [elementor/elementor#25136]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

The !important is not kept when a color selector is global. On standard colors it is. on "Global colors", the button to left of it, choosing a color sets the color but not !important, making it inconsistent.

### Steps to reproduce

Make a widget with ->add_control.... with

```
 'selectors' => [
                    '{{WRAPPER}} .yourselector' => 'color: {{VALUE}} !important'
                ],
```

Note that a specific color may work in cases that a _global color will not_, because global color plugs in css that is not !important.

### Expected behavior

It seems like it should be consistent and !important for every color chosen.

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.3.39
	PHP Version: 7.4.33
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.4.3
	Site URL: https://sfwm4.sharefaithwebsites.net/~sf576868/X5TrnuG5PU
	Home URL: https://sfwm4.sharefaithwebsites.net/~sf576868/X5TrnuG5PU
	WP Multisite: No
	Max Upload Size: 100 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.2.2
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0

== Active Plugins ==
	Duplicate Page
		Version: 4.5.3
		Author: mndpsingh287

	Ekklesia360
		Version: 1.0.7
		Author: Ekklesia360

	Elementor
		Version: 3.8.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.8.2
		Author: Elementor.com

	FMS Forms Plugin
		Version: 1.2.4
		Author: Sharefaith

	Galleries by Angie Makes
		Version: 1.62
		Author: Chris Baldelomar

	Prayer Cloud
		Version: 1.1.7
		Author: Sharefaith

	Sharefaith Media Library Plugin
		Version: 1.3.3
		Author: Sharefaith

	Style Kits for Elementor
		Version: 1.9.8
		Author: AnalogWP

	W3 Total Cache
		Version: 2.6.1
		Author: BoldGrid

	WP Statistics
		Version: 14.3.4
		Author: VeronaLabs

	Yoast SEO
		Version: 21.5
		Author: Team Yoast


== Must-Use Plugins ==
	Sharefaith
		Version: 2.4.11
		Author: Sharefaith


== Elementor Experiments ==
	Optimized DOM Output: Inactive by default
	Improved Asset Loading: Inactive by default
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Inactive by default
	Additional Custom Breakpoints: Inactive by default
	Import Export Website Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Inactive by default
	Form Submissions: Active by default
	Scroll Snap: Active by default


== Log ==
	
Log: showing 20 of 302022-12-01 23:43:57 [info] Elementor/Upgrades - _on_each_version Start  
2022-12-01 23:43:57 [info] Elementor/Upgrades - _on_each_version Finished 
2022-12-01 23:43:57 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Start  
2022-12-01 23:43:57 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Finished 
2022-12-01 23:43:57 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.6',
  'to' => '3.8.1',
)]
2022-12-01 23:43:58 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.6',
  'to' => '3.8.1',
)]
2022-12-01 23:44:00 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Finished 
2022-12-01 23:44:00 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon Start  
2022-12-01 23:44:02 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon callback needs to run more 2 times 
2022-12-01 23:44:02 [info] Elementor Pro/Upgrades - _v_3_3_0_recalc_usage_data Start  
2022-12-01 23:44:02 [info] Elementor Pro/Upgrades - _v_3_3_0_recalc_usage_data Finished 
2022-12-01 23:44:02 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Start  
2022-12-01 23:44:02 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list callback needs to run more 2 times 
2022-12-01 23:44:02 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon Start (2 of 3, 67%) 
2022-12-01 23:44:03 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Start (2 of 3, 67%) 
2022-12-01 23:44:03 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon Start (3 of 3, 100%) 
2022-12-01 23:44:04 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon Finished 
2022-12-01 23:44:05 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Start (3 of 3, 100%) 
2022-12-01 23:44:05 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Finished 
2022-12-01 23:44:05 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.2.0',
  'to' => '3.8.2',
)]

PHP: showing 7 of 7PHP: 2022-12-01 02:06:52 [notice X 1][../wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-21 19:00:26 [notice X 517][../wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] The $finder_category_name argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-29 16:25:51 [notice X 11][../wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-04 22:56:16 [notice X 121][../wp-content/plugins/elementor-pro/core/utils.php::227] Trying to get property 'post_author' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-05 22:12:34 [notice X 5][../wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-09 21:13:47 [notice X 1][../wp-content/plugins/elementor-pro/modules/wp-cli/license-command.php::32] Undefined index: license [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-02-13 18:43:31 [error X 1][../wp-content/plugins/elementor/includes/template-library/sources/local.php::1080] Uncaught TypeError: Argument 2 passed to Elementor\TemplateLibrary\Source_Local::on_save_post() must be an instance of WP_Post, null given, called in ../wp-includes/class-wp-hook.php on line 326 and defined in ../wp-content/plugins/elementor/includes/template-library/sources/local.php:1080
Stack trace:
#0 ../wp-includes/class-wp-hook.php(326): Elementor\TemplateLibrary\Source_Local->on_save_post(4398, NULL)
#1 ../wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#2 ../wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#3 ../wp-includes/post.php(4760): do_action('save_post', 4398, NULL, true)
#4 ../wp-includes/post.php(4862): wp_insert_post(Array, false, true)
#5 ../wp-content/plugins/elementor/includes/db.php [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 6 of 6JS: 2023-03-30 21:02:06 [error X 3][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.1:3:883015] Cannot read properties of undefined (reading \'route\') 
JS: 2023-03-30 21:36:47 [error X 5][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.1:3:1061530] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2023-04-03 22:48:43 [error X 9][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.1:3:694254] T.getContainer is not a function 
JS: 2023-04-05 21:42:09 [error X 1][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.1:3:588274] Cannot read properties of undefined (reading \'isEditable\') 
JS: 2023-04-13 22:19:57 [error X 1][../wp-content/plugins/elementor/assets/js/new-template.min.js?ver=3.8.1:2:2932] elementor_new_template_form_controls is not defined 
JS: 2024-02-14 19:18:31 [error X 1][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.1:3:1061528] $ is null 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	Style Kits for Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by Luke-SF** [comment]
Is this the intended behavior?

**Comment by nicholaszein** [comment]
Hello @Luke-SF,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
This is the intended behavior. We do not support, and will not support the use of !important on control settings. Not only this is not recommended, you are also not using the correct scheme for applying styles. Please follow our [developer documentation](https://elemn.to/gh-to-dev-center).

### 👍 For now, that's all we can help with. 

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
