### ISSUE TITLE
Taxonomy Filter fails on refreshing Loop Grid if pagination_base_url contains non-latin characters (400 Bad Request)

### ISSUE THREAD

**Issue by yyahav** [elementor/elementor#25222]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Using Taxonomy Filter to filter the Loop Grid widget, while URLs contain non-latin characters, results in the following error in the browser console when clicking through the various filters on the frontend:
`POST https://fivecenterof.me/wp-json/elementor-pro/v1/refresh-loop 400 (Bad Request)`

The URL changes to include: `?e-filter-02e732d-category=....` but other than that the Loop Grid shows all posts and won't refresh.

The Loop Grid query is set up for a Custom Post Type, that has its slug changed to include hebrew letters.

Looking into the payload and response of this REST API call this is what I see:
Payload:
```
{
    "post_id": "5647",
    "widget_filters": {
        "taxonomy": {
            "category": {
                "terms": ["מעבדות-חקר"]
            }
        }
    },
    "widget_id": "02e732d",
    "pagination_base_url": "https://<mywebsite.url>/הקורסים-שלנו/"
}
```
Response:
```
{
    "code": "rest_invalid_param",
    "message": "Invalid parameter: pagination_base_url",
    "data": {
        "status": 400,
        "params": {
            "pagination_base_url": "Invalid parameter."
        },
        "details": []
    }
}
```

When I changed the CPT slug to latin the taxonomy filter works as expected.

### Steps to reproduce

1. Using CPT-UI create a CPT and:
- Change its `Custom Rewrite Slug` to include hebrew letters.
- Under `Taxonomies` enable WP-Core Categories, and enable `Has Archive`.
- Save the CPT.
2. Create some CPT posts and configure various categories.
3. Create an Archive Template settings its Conditions to All Archives.
4. In the template add the Taxonomy Filter and the Loop Grid.
5. Point the taxonomy filter to the loop grid.
6. Configure the loop grid query source for the CPT.
7. Open browser console (dev tools).
8. Preview the page and click all the filters one by one.

After this test go back to the CPT-UI, edit the CPT and change its Custom Rewrite Slug to include latin characters only.
Go back to the previewed page and try to filter the grid again - works.

### Expected behavior

Taxonomy Filter should refresh the Loop Grid showing only the relevant posts.

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.5.24
	PHP Version: 7.4.33
	PHP Memory Limit: 768M
	PHP Max Input Vars: 6200
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.4.3
	Site URL: https://<mysite.url>
	Home URL: https://<mysite.url>
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 40M
	Max Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 3
	Admin Email: <hidden>
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Seventeen
	Version: 3.4
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: he_IL
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 6.2.6.1
		Author: WP Engine

	Asset Queue Manager
		Version: 1.0.3
		Author: Nate Wright

	Custom Post Type UI
		Version: 1.15.1
		Author: WebDevStudios

	Duplicator
		Version: 1.5.8.1
		Author: Duplicator

	Elementor
		Version: 3.19.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.19.2
		Author: Elementor.com

	Enable Accessibility
		Version: 1.4.1
		Author: uPress

	Envato Elements
		Version: 2.0.12
		Author: Envato

	Extras for Elementor
		Version: 2.2.51
		Author: Namogo

	Meta pixel for WordPress
		Version: 3.0.14
		Author: Facebook

	Redirection
		Version: 5.4.2
		Author: John Godley

	Table Generator
		Version: 1.3.0
		Author: WPGurus

	Timetable and Event Schedule
		Version: 2.4.10
		Author: MotoPress

	W3 Total Cache
		Version: 2.7.0
		Author: BoldGrid

	WeSafe by uPress
		Version: 1.7.2
		Author: uPress

	WooCommerce
		Version: 8.6.0
		Author: Automattic

	WPCode Lite
		Version: 2.1.8
		Author: WPCode

	Yoast Duplicate Post
		Version: 4.5
		Author: Enrico Battocchi & Team Yoast

	Yoast SEO
		Version: 22.1
		Author: Team Yoast


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	
	woocommerce: Active


== Elementor Experiments ==
	Improved Asset Loading: Active by default
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Active
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Inactive by default
	Grid Container: Inactive by default
	Default to New Theme Builder: Active by default
	Editor Top Bar: Active
	Optimized Gutenberg Loading: Active by default
	Build with AI: Active by default
	Landing Pages: Active by default
	Nested Elements: Active
	Lazy Load Background Images: Active
	Optimize Image Loading: Active by default
	Pages Panel: Inactive by default
	Global Style Guide: Active
	Page Transitions: Active by default
	Notes: Active by default
	Display Conditions: Inactive by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Menu: Inactive by default
	Taxonomy Filter: Active


== Log ==
	
Log: showing 20 of 242023-12-05 20:38:29 [info] Elementor/Upgrades - _on_each_version Start  
2023-12-05 20:38:29 [info] Elementor/Upgrades - _on_each_version Finished 
2023-12-05 20:38:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.17.3',
  'to' => '3.18.0',
)]
2023-12-05 20:38:29 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.17.3',
  'to' => '3.18.0',
)]
2024-01-14 20:00:44 [info] elementor::elementor_updater Started 
2024-01-14 20:00:44 [info] Elementor/Upgrades - _on_each_version Start  
2024-01-14 20:00:44 [info] Elementor/Upgrades - _on_each_version Finished 
2024-01-14 20:00:44 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.18.0',
  'to' => '3.18.3',
)]
2024-01-14 20:00:44 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.18.0',
  'to' => '3.18.3',
)]
2024-01-14 20:00:45 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'אלמנטור',
  'from' => '3.18.0',
  'to' => '3.18.3',
)]
2024-02-11 22:33:42 [info] elementor-pro::elementor_pro_updater Started 
2024-02-11 22:33:42 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-02-11 22:33:42 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-02-11 22:33:42 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.17.1',
  'to' => '3.19.2',
)]
2024-02-11 22:33:42 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.17.1',
  'to' => '3.19.2',
)]
2024-02-11 22:33:43 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '3.17.1',
  'to' => '3.19.2',
)]
2024-02-11 22:34:17 [info] elementor::elementor_updater Started 
2024-02-11 22:34:17 [info] Elementor/Upgrades - _on_each_version Start  
2024-02-11 22:34:17 [info] Elementor/Upgrades - _on_each_version Finished 
2024-02-11 22:34:17 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.18.3',
  'to' => '3.19.2',
)]

PHP: showing 11 of 11PHP: 2023-12-05 14:12:53 [error X 7][/home/testacc/public_html/wp-content/plugins/elementor-forms-lead-action/form-actions/lead-action.php::6] require_once(): Failed opening required 'vendor/autoload.php' (include_path='.:/opt/cpanel/ea-php74/root/usr/share/pear') [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-12-05 14:18:26 [error X 6][/home/testacc/public_html/wp-content/plugins/elementor-forms-lead-action/vendor/composer/platform_check.php::24] Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0". You are running 7.4.33. [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-12-05 20:39:29 [notice X 1][/home/testacc/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/widgets/site-logo.php::192] Undefined index: options [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-01-31 13:17:50 [error X 1][/home/testacc/public_html/wp-content/plugins/elementor/data/v2/base/controller.php::227] Uncaught Elementor\Data\V2\Base\Exceptions\WP_Error_Exception: המתודה "WP_REST_Controller::get_item_permissions_check" אינה מיושמת. יש לדרוס על ידי תת-מחלקה. in /home/testacc/public_html/wp-content/plugins/elementor/data/v2/base/controller.php:227
Stack trace:
#0 /home/testacc/public_html/wp-content/plugins/elementor/data/v2/base/base-route.php(105): Elementor\Data\V2\Base\Controller->get_permission_callback(Object(WP_REST_Request))
#1 /home/testacc/public_html/wp-content/plugins/elementor/data/v2/base/base-route.php(242): Elementor\Data\V2\Base\Base_Route->get_permission_callback(Object(WP_REST_Request))
#2 /home/testacc/public_html/wp-includes/rest-api/class-wp-rest-server.php(1160): Elementor\Data\V2\Base\Base_Route->Elementor\Data\V2\Base\{closure}(Object(WP_REST_Request))
#3 /home/testacc/public_html/wp-includes/rest-api/class-wp-rest-server.php(1041): WP_REST_Server->respond_to_request(Object(WP_REST_Request), '/elementor/v1/f...', Array, NULL)
#4 /home/testacc/public_ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-02-12 20:14:11 [notice X 6][/home/testacc/public_html/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php::33] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-02-12 20:42:30 [notice X 10][/home/testacc/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::179] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-02-15 21:25:01 [notice X 13][/home/testacc/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined index: condition_type [array (
  'trace' => '
#0: /home/testacc/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /home/testacc/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /home/testacc/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /home/testacc/public_html/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2024-02-15 22:14:50 [notice X 6][/home/testacc/public_html/wp-content/plugins/elementor-extras/modules/query-control/types/posts.php::38] Undefined index: object_type [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-02-15 22:56:20 [error X 6][/home/testacc/public_html/wp-content/plugins/elementor-pro/modules/screenshots/module.php::229] Uncaught WpOrg\Requests\Exception\Http\Status403: 403 Forbidden in /home/testacc/public_html/wp-content/plugins/elementor-pro/modules/screenshots/module.php:229
Stack trace:
#0 /home/testacc/public_html/wp-content/plugins/elementor-pro/modules/screenshots/module.php(264): ElementorPro\Modules\Screenshots\Module->is_screenshot_proxy_mode(Array)
#1 /home/testacc/public_html/wp-content/plugins/elementor/core/base/module.php(85): ElementorPro\Modules\Screenshots\Module->__construct()
#2 /home/testacc/public_html/wp-content/plugins/elementor-pro/core/modules-manager.php(93): Elementor\Core\Base\Module::instance()
#3 /home/testacc/public_html/wp-content/plugins/elementor-pro/plugin.php(375): ElementorPro\Core\Modules_Manager->__construct()
#4 /home/testacc/public_html/wp-includes/class-wp-hook.php(324): ElementorPro\Plugin->on_elementor_init('')
#5 /home/testacc/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#6 /home/testacc/public_html/wp-includes/plugin.php(517): WP_Hook->do_a [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-02-19 20:45:27 [notice X 1][/home/testacc/public_html/wp-content/plugins/elementor/core/page-assets/data-managers/font-icon-svg/font-awesome.php::50] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-02-19 22:24:57 [notice X 5][/home/testacc/public_html/wp-content/plugins/elementor-pro/modules/loop-filter/query/taxonomy-manager.php::150] Undefined index: logicalJoin [array (
  'trace' => '
#0: /home/testacc/public_html/wp-content/plugins/elementor-pro/modules/loop-filter/query/taxonomy-manager.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/testacc/public_html/wp-content/plugins/elementor-pro/modules/loop-filter/query/taxonomy-query-builder.php(33): ElementorPro\Modules\LoopFilter\Query\Taxonomy_Manager -> get_hierarchy_of_selected_terms()
#2: /home/testacc/public_html/wp-content/plugins/elementor-pro/modules/loop-filter/module.php(124): ElementorPro\Modules\LoopFilter\Query\Taxonomy_Query_Builder -> get_merged_queries()
#3: /home/testacc/public_html/wp-includes/class-wp-hook.php(324): ElementorPro\Modules\LoopFilter\Module -> filter_loop_query()
#4: /home/testacc/public_html/wp-includes/plugin.php(205): WP_Hook -> apply_filters()
',
)]

JS: showing 7 of 7JS: 2024-02-06 16:46:28 [error X 1][https://<mysite.url>/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.18.3:3:640700] Cannot read properties of undefined (reading 'isDesignable') 
JS: 2024-02-15 18:16:22 [error X 22][https://<mysite.url>/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.19.2:3:677568] elementorFrontend.elements.window.jQuery is not a function 
JS: 2024-02-15 18:16:22 [error X 43][https://<mysite.url>/wp-content/plugins/elementor-extras/assets/js/frontend.min.js?ver=2.2.51:1:4462] Cannot read properties of undefined (reading '$previewContents') 
JS: 2024-02-15 18:55:29 [error X 10][https://<mysite.url>/wp-includes/js/jquery/jquery.min.js?ver=3.7.1:2:28760] Cannot read properties of undefined (reading 'value') 
JS: 2024-02-15 19:12:04 [error X 8][https://<mysite.url>/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.19.2:2:16880] Cannot read properties of undefined (reading 'attributes') 
JS: 2024-02-18 19:01:58 [error X 4][https://<mysite.url>/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.19.2:3:814672] Cannot read properties of undefined (reading 'localized') 
JS: 2024-02-19 17:28:02 [error X 2][https://<mysite.url>/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.19.2:3:609436] Cannot read properties of null (reading 'id') 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	Extras for Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hello @yyahav! 

Thank you for submitting your issue! 🙏 

🏷️ We've labeled this issue and our team will take a look at it. If there is indeed a problem, they'll work on fixing it. We can't say exactly when it'll be sorted out, but we kindly ask for your patience. Thanks for understanding!

Best regards

**Comment by ivelinjp** [comment]
Hello @nicholaszein, I'm facing the same issue with Cyrillic characters. There is definitely a problem for the Tax Filter to handle non-latin characters. Any news, expectations, updates? I see 6 months have passed since the last activity on the issue, and today I confirm the issue still exists.

**Comment by jwywiol** [comment]
Hi, Evidently this is a page link error. Change it to make the filtering work. This is the only reasonably quick solution I can share for the moment. I also lost a few hours debugging and testing, but only this discussion gave a surespective solution. 

Cheers

**Comment by ghost** [comment]
Hi there! Custom post-types had a 8-digit ID. You will find a working solution here: https://github.com/elementor/elementor/issues/27614#issuecomment-2737203250
