### ISSUE TITLE
📚 Inline Editor not loading exiting value for editing when elements load in modal

### ISSUE THREAD

**Issue by shafiqhossain** [elementor/elementor#25359]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

I have two custom widget - "Quote" and "Member Popup". Member profile is showing in popup when user click a link "Bio" inside Quote widget. Inside Quote, user select a Member and when click on "Bio" link, that's member's profile shows in modal.

Member Popup widget, I am rending programmatically inside render() function of Quote widget. Member popup controls like First name, Last name, email, Designation etc are inline enabled. Everything works file as designed. Only issue is that, when I add the widget Quote and select the member and opened the dialog for member and clicked on First name or Last name or any control for editing, it shows placeholder "Type Here..." and blank! Not showing the existing values. 
Note that, I did not saved the page yet. If I save the page and reload the page and then again go for edit, now it shows the existing value for editing.  

What I see that, there is a javascript variable called "ElementorConfig" which actually always loading blank information for the fields when Editor first preview the widget.

Please note that, I am working on local environment. We have both Elementor and Elemento Pro plugins enabled. But pro version is not activated locally.

### Steps to reproduce

1. I have rendered the Member Popup widget programmatically and added to render() function of Quote as follows:
```php					
<?php
popup_widget = \Elementor\Plugin::instance()->elements_manager->create_element_instance(
    [
      'elType' => 'widget',
      'widgetType' => 'smma-member-popup',
      'id' => 'pop'.rand(8,8),
      'settings' => [
        'title' => !empty($author->post_title) ? $author->post_title : '',
        'content' => !empty($author_content) ? $author_content : '',
        'first_name' => !empty($first_name) ? $first_name : '',
        'last_name' => !empty($last_name) ? $last_name : '',
        'sub_title' => !empty($sub_title) ? $sub_title : '',
        'email' => !empty($email) ? $email : '',
        'contact_number' => !empty($phone) ? $phone : '',
        'education' => !empty($education) ? $education : '',
        'affiliation' => !empty($affiliation) ? $affiliation : '',
        'featured_image' => array(
          'id' => !empty($author) ? get_post_thumbnail_id( $author->ID ) : '',
          'url' => !empty($author_image['url']) ? $author_image['url'] : '',
        ),
      ],
    ],
    [
      'quote_post_id' => $quote_id,
      'member_post_id' => $author_id,
    ]
  );
  ?>
  <?php $popup_widget->print_element(); ?>
```
2. Here is a video for the issue
https://www.awesomescreenshot.com/video/25502143?key=84941b5594230f02e5fa0f530fb31043
 

### Expected behavior

1. As we expected, when click on element for editing, for first time, even the post is not saved, it should show the existing value in place for edit.

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt

== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.54 (Win64) OpenSSL/1.1.1p mod_fcgid/2.3.10-dev
	MySQL version: mariadb.org binary distribution v10.8.3
	PHP Version: 8.1.14
	PHP Memory Limit: 4G
	PHP Max Input Vars: 10000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.4.2
	Site URL: https://smma.local.com:4433
	Home URL: https://smma.local.com:4433
	WP Multisite: No
	Max Upload Size: 50 MB
	Memory limit: 40M
	Max Memory limit: 4G
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Active

== Theme ==
	Name: SMMA
	Version: 2.9.0.1702370870
	Author: Chintan Kotadia, Knectar
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.9.0
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 6.2.4
		Author: WP Engine

	Child Theme Configurator
		Version: 2.6.3
		Author: Lilaea Media

	Classic Editor
		Version: 1.6.3
		Author: WordPress Contributors

	Duplicator
		Version: 1.5.7
		Author: Duplicator

	Elementor
		Version: 3.18.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.18.1
		Author: Elementor.com

	Gravity Forms
		Version: 2.7.15
		Author: Gravity Forms

	Newsletter
		Version: 8.0.2
		Author: Stefano Lissa & The Newsletter Team

	SMMA Elementor Widgets
		Version: 1.0.0
		Author: Knectar

	SVG Support
		Version: 2.5.5
		Author: Benbodhi


== Must-Use Plugins ==
	Pantheon MU Plugin Loader
		Version: 1.0
		Author: Pantheon Systems


== Elements Usage ==
	
	container : 2
		button : 1
		container : 6
		heading : 1
		icon : 2
		nested-carousel : 1
		text-editor : 1
	footer : 2
		container : 4
		image : 4
		nav-menu : 6
		spacer : 7
		wp-widget-newsletterwidget : 2
	header : 3
		container : 9
		icon : 3
		theme-site-logo : 3
	popup : 6
		container : 14
		form : 1
		html : 1
		icon : 2
		image : 6
		nav-menu : 2
		search-form : 1
		slides : 1
		text-editor : 2
	section : 27
		button : 5
		container : 102
		heading : 33
		html : 2
		image : 26
		image-box : 2
		image-carousel : 1
		nested-carousel : 4
		text-editor : 14
		video : 3
	widget : 0
		call_to_action : 3
		oembed : 1
	wp-post : 1
		call_to_action : 3
		container : 27
		image-with-deep-dive : 1
		image-with-story : 2
		nested-carousel : 1
		smma-large-image : 1
		smma-media-gallery : 1
		smma-render-reality : 1
		smma-single-image : 6
		smma-single-video : 1
		smma-stats : 1
		smma-testimonials : 1
		smma-two-image : 1
		text-editor : 2
		video : 1
	wp-page : 34
		button : 7
		call-to-action : 1
		call_to_action : 7
		container : 113
		divider : 5
		downloadable_content : 1
		heading : 13
		icon : 6
		image : 5
		image-box : 4
		image-with-deep-dive : 2
		image-with-story : 4
		image-with-text : 3
		nested-carousel : 1
		oembed : 1
		smma-accordion : 3
		smma-featured-text : 5
		smma-image-carousel : 3
		smma-large-image : 3
		smma-markets : 2
		smma-media-gallery : 3
		smma-multiple-images : 3
		smma-quotes : 2
		smma-related_projects_and_perspectives : 2
		smma-render-reality : 3
		smma-services : 4
		smma-single-image : 7
		smma-single-video : 9
		smma-stats : 2
		smma-thing-link : 2
		smma-two-image : 3
		social-icons : 1
		spacer : 2
		template : 5
		text-editor : 9
		wysiwyg : 3
	single-post : 14
		call_to_action : 4
		container : 50
		downloadable_content : 6
		oembed : 4
		post-info : 1
		shortcode : 26
		smma-related_projects_and_perspectives : 3
		spacer : 10
		theme-post-content : 7
		theme-post-title : 7
	single-page : 3
		container : 6
		shortcode : 4
		spacer : 2


== Settings ==
	
	cpt_support: post, page, e-landing-page, gallery, our-people, perspective, project, services
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Active by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active by default
	Grid Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header &amp; Footer: Active by default
	Editor Top Bar: Inactive by default
	Optimized Gutenberg Loading: Active by default
	Build with AI: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Active
	Lazy Load Background Images: Inactive by default
	Optimize Image Loading: Active by default
	Global Style Guide: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Menu: Inactive by default
	Taxonomy Filter: Inactive by default


== Log ==
	
JS: showing 17 of 17JS: 2023-11-14 07:45:00 [error X 43][../wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.17.1:2:16878] e is undefined 
JS: 2023-11-14 10:36:47 [error X 12][../wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.17.1:2:7115] elementorModules.frontend is undefined 
JS: 2023-11-15 07:39:45 [error X 3][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.17.1:3:639977] this.view.container is undefined 
JS: 2023-11-15 13:23:48 [error X 18][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.17.1:3:805504] Cannot read properties of undefined (reading &#039;toLowerCase&#039;) 
JS: 2023-11-22 14:23:34 [error X 2][../wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.17.1:3:30945] id invalid type: string. 
JS: 2023-11-23 11:24:04 [error X 1][../wp-content/plugins/elementor/assets/js/web-cli.min.js?ver=3.17.1:3:107466] Routes: `false` not found. 
JS: 2023-11-28 14:36:47 [error X 1][../wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.17.1:2:16880] Cannot read properties of undefined (reading &#039;attributes&#039;) 
JS: 2023-12-13 14:12:45 [error X 458][../wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.18.2:3:16127] Cannot read properties of undefined (reading &#039;global&#039;) 
JS: 2023-12-14 15:07:37 [error X 250][../wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.18.2:3:16120] r[a] is undefined 
JS: 2023-12-14 15:09:16 [error X 9][../wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.18.2:3:14266] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got as `image` value. Expected array or object.',
)]
JS: 2023-12-18 13:41:05 [error X 2][../wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.18.2:3:16120] undefined has no properties 
JS: 2024-01-01 14:22:38 [error X 29][../wp-admin/load-scripts.php?c=1&amp;loadchunk_0=jquery-core,jquery-migrate,utils,wp-polyfill-inert,regenerator-runtime,wp-polyfill,wp-hooks&amp;ver=6.4.2:2:28760] Cannot read properties of undefined (reading &#039;value&#039;) 
JS: 2024-01-04 09:42:27 [error X 1][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.18.2:3:806379] T.originalEvent.key is undefined 
JS: 2024-01-08 12:34:54 [error X 2][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.18.2:3:640760] Cannot read properties of undefined (reading &#039;isDesignable&#039;) 
JS: 2024-02-15 12:50:04 [error X 3][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.18.2:3:690171] this.model.isValidChild is not a function 
JS: 2024-03-04 09:28:09 [error X 1][../wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.18.2:2:17195] Cannot read properties of undefined (reading &#039;toJSON&#039;) 
JS: 2024-03-04 16:38:26 [error X 2][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.18.2:3:806906] Cannot read properties of undefined (reading &#039;localized&#039;) 

PHP: showing 9 of 9PHP: 2023-11-16 05:58:59 [notice X 1][../wp-content/plugins/elementor/includes/utils.php::727] strtolower(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-11-21 06:36:53 [warning X 1][../wp-content/plugins/elementor/core/common/modules/connect/module.php::225] Attempt to read property &quot;email&quot; on null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-11-22 13:25:43 [warning X 12][../wp-content/plugins/elementor/modules/usage/module.php::80] Undefined array key &quot;publish&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-12-09 09:22:28 [warning X 36][../wp-content/plugins/elementor-pro/modules/theme-builder/widgets/site-logo.php::192] Undefined array key &quot;options&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-12-21 07:24:26 [warning X 1][../wp-content/plugins/elementor/core/files/css/base.php::833] Undefined array key &quot;_id&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-02-22 16:07:11 [warning X 2][..\wp-content\plugins\elementor-pro\modules\assets-manager\asset-types\fonts-manager.php::252] Undefined array key &quot;editor_post_id&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-03-01 17:49:39 [error X 3][..\wp-content\plugins\elementor\includes\base\controls-stack.php::2443] Uncaught TypeError: Elementor\Controls_Stack::sanitize_settings(): Argument #1 ($settings) must be of type array, null given, called in ..\wp-content\plugins\elementor\includes\base\controls-stack.php on line 1130 and defined in ..\wp-content\plugins\elementor\includes\base\controls-stack.php:2443
Stack trace:
#0 ..\wp-content\plugins\elementor\includes\base\controls-stack.php(1130): Elementor\Controls_Stack-&gt;sanitize_settings(NULL)
#1 ..\wp-content\plugins\elementor\includes\base\controls-stack.php(2190): Elementor\Controls_Stack-&gt;get_data(&#039;settings&#039;)
#2 ..\wp-content\plugins\elementor\core\base\base-object.php(142): Elementor\Controls_Stack-&gt;get_init_settings()
#3 ..\wp-content\plugins\elementor\core\base\base-object.php(40): Elementor\Core\Base\Base_Object-&gt;ensure_settings()
#4 ..\wp-content\plugins\smma-elementor-widgets\widgets\member-popup\widget.php(48): Elementor\Core\Base\Base_Object-&gt;get_settings()
#5 ..\wp-content\plugins\elementor\includes\managers\elements.php(89): SMMA_MemberPopup_Widget-&gt;__construct(Array, Array)
#6 ..\wp-content\plugins\smma-elementor-widgets\widgets\quotes\view.php(81): Elementor\Elements_Manager-&gt;create_element_instance(Array, Array)
#7 ..\wp-content\plugins\smma-elementor-widgets\widgets\quotes\widget.php(207): require(&#039;C:\\MyWorks\\src\\...&#039;)
#8 ..\wp-content\plugins\elementor\includes\base\controls-stack.php(2297): SMMA_Quotes_Widget-&gt;render()
#9 ..\wp-content\plugins\elementor\includes\base\widget-base.php(614): Elementor\Controls_Stack-&gt;render_by_mode()
#10 ..\wp-content\plugins\elementor\core\base\document.php(328): Elementor\Widget_Base-&gt;render_content()
#11 ..\wp-content\plugins\elementor\includes\managers\widgets.php(459): Elementor\Core\Base\Document-&gt;render_element(Array)
#12 [internal function]: Elementor\Widgets_Manager-&gt;ajax_render_widget(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#13 ..\wp-content\plugins\elementor\core\common\modules\ajax\module.php(176): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#14 ..\wp-includes\class-wp-hook.php(324): Elementor\Core\Common\Modules\Ajax\Module-&gt;handle_ajax_request(&#039;&#039;)
#15 ..\wp-includes\class-wp-hook.php(348): WP_Hook-&gt;apply_filters(&#039;&#039;, Array)
#16 ..\wp-includes\plugin.php(517): WP_Hook-&gt;do_action(Array)
#17 ..\wp-admin\admin-ajax.php(188): do_action(&#039;wp_ajax_element...&#039;)
#18 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-03-01 17:50:03 [error X 1][..\wp-content\plugins\elementor\includes\base\controls-stack.php::2443] Uncaught TypeError: Elementor\Controls_Stack::sanitize_settings(): Argument #1 ($settings) must be of type array, null given, called in ..\wp-content\plugins\elementor\includes\base\controls-stack.php on line 1130 and defined in ..\wp-content\plugins\elementor\includes\base\controls-stack.php:2443
Stack trace:
#0 ..\wp-content\plugins\elementor\includes\base\controls-stack.php(1130): Elementor\Controls_Stack-&gt;sanitize_settings(NULL)
#1 ..\wp-content\plugins\elementor\includes\base\controls-stack.php(2190): Elementor\Controls_Stack-&gt;get_data(&#039;settings&#039;)
#2 ..\wp-content\plugins\elementor\core\base\base-object.php(142): Elementor\Controls_Stack-&gt;get_init_settings()
#3 ..\wp-content\plugins\elementor\core\base\base-object.php(40): Elementor\Core\Base\Base_Object-&gt;ensure_settings()
#4 ..\wp-content\plugins\smma-elementor-widgets\widgets\member-popup\widget.php(48): Elementor\Core\Base\Base_Object-&gt;get_settings()
#5 ..\wp-content\plugins\elementor\includes\managers\elements.php(89): SMMA_MemberPopup_Widget-&gt;__construct(Array, Array)
#6 ..\wp-content\plugins\smma-elementor-widgets\widgets\quotes\view.php(81): Elementor\Elements_Manager-&gt;create_element_instance(Array, Array)
#7 ..\wp-content\plugins\smma-elementor-widgets\widgets\quotes\widget.php(207): require(&#039;C:\\MyWorks\\src\\...&#039;)
#8 ..\wp-content\plugins\elementor\includes\base\controls-stack.php(2297): SMMA_Quotes_Widget-&gt;render()
#9 ..\wp-content\plugins\elementor\includes\base\widget-base.php(614): Elementor\Controls_Stack-&gt;render_by_mode()
#10 ..\wp-content\plugins\elementor\includes\base\widget-base.php(678): Elementor\Widget_Base-&gt;render_content()
#11 ..\wp-content\plugins\elementor\includes\db.php(202): Elementor\Widget_Base-&gt;render_plain_content()
#12 ..\wp-content\plugins\elementor\includes\db.php(208): Elementor\DB-&gt;render_element_plain_content(Array)
#13 ..\wp-content\plugins\elementor\includes\db.php(558): Elementor\DB-&gt;render_element_plain_content(Array)
#14 ..\wp-content\plugins\elementor\includes\db.php(539): Elementor\DB-&gt;get_plain_text_from_data(Array)
#15 ..\wp-content\plugins\elementor\includes\db.php(230): Elementor\DB-&gt;get_plain_text(3278)
#16 ..\wp-content\plugins\elementor\core\base\document.php(1310): Elementor\DB-&gt;save_plain_text(3278)
#17 ..\wp-content\plugins\elementor\core\base\document.php(797): Elementor\Core\Base\Document-&gt;save_elements(Array)
#18 ..\wp-content\plugins\elementor\core\documents-manager.php(545): Elementor\Core\Base\Document-&gt;save(Array)
#19 [internal function]: Elementor\Core\Documents_Manager-&gt;ajax_save(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#20 ..\wp-content\plugins\elementor\core\common\modules\ajax\module.php(176): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#21 ..\wp-includes\class-wp-hook.php(324): Elementor\Core\Common\Modules\Ajax\Module-&gt;handle_ajax_request(&#039;&#039;)
#22 ..\wp-includes\class-wp-hook.php(348): WP_Hook-&gt;apply_filters(&#039;&#039;, Array)
#23 ..\wp-includes\plugin.php(517): WP_Hook-&gt;do_action(Array)
#24 ..\wp-admin\admin-ajax.php(188): do_action(&#039;wp_ajax_element...&#039;)
#25 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-03-01 17:50:41 [error X 1][..\wp-content\plugins\elementor\includes\base\controls-stack.php::2443] Uncaught TypeError: Elementor\Controls_Stack::sanitize_settings(): Argument #1 ($settings) must be of type array, null given, called in ..\wp-content\plugins\elementor\includes\base\controls-stack.php on line 1130 and defined in ..\wp-content\plugins\elementor\includes\base\controls-stack.php:2443
Stack trace:
#0 ..\wp-content\plugins\elementor\includes\base\controls-stack.php(1130): Elementor\Controls_Stack-&gt;sanitize_settings(NULL)
#1 ..\wp-content\plugins\elementor\includes\base\controls-stack.php(2190): Elementor\Controls_Stack-&gt;get_data(&#039;settings&#039;)
#2 ..\wp-content\plugins\elementor\core\base\base-object.php(142): Elementor\Controls_Stack-&gt;get_init_settings()
#3 ..\wp-content\plugins\elementor\core\base\base-object.php(40): Elementor\Core\Base\Base_Object-&gt;ensure_settings()
#4 ..\wp-content\plugins\smma-elementor-widgets\widgets\member-popup\widget.php(48): Elementor\Core\Base\Base_Object-&gt;get_settings()
#5 ..\wp-content\plugins\elementor\includes\managers\elements.php(89): SMMA_MemberPopup_Widget-&gt;__construct(Array, Array)
#6 ..\wp-content\plugins\smma-elementor-widgets\widgets\quotes\view.php(81): Elementor\Elements_Manager-&gt;create_element_instance(Array, Array)
#7 ..\wp-content\plugins\smma-elementor-widgets\widgets\quotes\widget.php(207): require(&#039;C:\\MyWorks\\src\\...&#039;)
#8 ..\wp-content\plugins\elementor\includes\base\controls-stack.php(2297): SMMA_Quotes_Widget-&gt;render()
#9 ..\wp-content\plugins\elementor\includes\base\widget-base.php(614): Elementor\Controls_Stack-&gt;render_by_mode()
#10 ..\wp-content\plugins\elementor\includes\base\widget-base.php(678): Elementor\Widget_Base-&gt;render_content()
#11 ..\wp-content\plugins\elementor\includes\db.php(202): Elementor\Widget_Base-&gt;render_plain_content()
#12 ..\wp-content\plugins\elementor\includes\db.php(208): Elementor\DB-&gt;render_element_plain_content(Array)
#13 ..\wp-content\plugins\elementor\includes\db.php(558): Elementor\DB-&gt;render_element_plain_content(Array)
#14 ..\wp-content\plugins\elementor\includes\db.php(539): Elementor\DB-&gt;get_plain_text_from_data(Array)
#15 ..\wp-content\plugins\elementor\includes\db.php(230): Elementor\DB-&gt;get_plain_text(3344)
#16 ..\wp-content\plugins\elementor\core\base\document.php(1310): Elementor\DB-&gt;save_plain_text(3344)
#17 ..\wp-content\plugins\elementor\core\base\document.php(797): Elementor\Core\Base\Document-&gt;save_elements(Array)
#18 ..\wp-content\plugins\elementor\core\documents-manager.php(545): Elementor\Core\Base\Document-&gt;save(Array)
#19 [internal function]: Elementor\Core\Documents_Manager-&gt;ajax_save(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#20 ..\wp-content\plugins\elementor\core\common\modules\ajax\module.php(176): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#21 ..\wp-includes\class-wp-hook.php(324): Elementor\Core\Common\Modules\Ajax\Module-&gt;handle_ajax_request(&#039;&#039;)
#22 ..\wp-includes\class-wp-hook.php(348): WP_Hook-&gt;apply_filters(&#039;&#039;, Array)
#23 ..\wp-includes\plugin.php(517): WP_Hook-&gt;do_action(Array)
#24 ..\wp-admin\admin-ajax.php(188): do_action(&#039;wp_ajax_element...&#039;)
#25 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 16 of 162023-11-23 07:06:52 [info] elementor-pro::elementor_pro_updater Started 
2023-11-23 07:06:52 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-11-23 07:06:52 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-11-23 07:06:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.17.0',
  'to' => '3.17.1',
)]
2023-11-23 07:06:52 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.17.0',
  'to' => '3.17.1',
)]
2023-11-23 08:28:34 [error] no-write-permissions [array (
  'trace' => '#0 ../wp-content/plugins/elementor/app/modules/import-export/module.php(389): Elementor\App\Modules\ImportExport\Module->ensure_writing_permissions()
#1 ../wp-content/plugins/elementor/app/modules/import-export/module.php(689): Elementor\App\Modules\ImportExport\Module->export_kit(Array)
#2 ../wp-content/plugins/elementor/app/modules/import-export/module.php(524): Elementor\App\Modules\ImportExport\Module->handle_export_kit()
#3 ../wp-content/plugins/elementor/app/modules/import-export/module.php(434): Elementor\App\Modules\ImportExport\Module->maybe_handle_ajax()
#4 ../wp-includes/class-wp-hook.php(310): Elementor\App\Modules\ImportExport\Module->Elementor\App\Modules\ImportExport\{closure}('')
#5 ../wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters(NULL, Array)
#6 ../wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#7 ../wp-admin/admin-ajax.php(45): do_action('admin_init')
#8 {main}',
)]
2023-12-09 09:22:26 [info] elementor::elementor_updater Started 
2023-12-09 09:22:26 [info] Elementor/Upgrades - _on_each_version Start  
2023-12-09 09:22:27 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.17.1',
  'to' => '3.18.2',
)]
2023-12-09 09:22:27 [info] Elementor/Upgrades - _on_each_version Finished 
2023-12-09 09:22:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.17.1',
  'to' => '3.18.2',
)]
2023-12-12 07:04:14 [info] elementor-pro::elementor_pro_updater Started 
2023-12-12 07:04:14 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-12-12 07:04:14 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-12-12 07:04:14 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.17.1',
  'to' => '3.18.1',
)]
2023-12-12 07:04:14 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.17.1',
  'to' => '3.18.1',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible
	SMMA Elementor Widgets: Incompatible

== Elementor Pro - Compatibility Tag ==
	
	SMMA Elementor Widgets: Incompatible

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by shafiqhossain** [comment]
```
$popup_widget = \Elementor\Plugin::instance()->elements_manager->create_element_instance(
	[
		'elType' => 'widget',
		'widgetType' => 'smma-member-popup',
		'id' => 'pop'.rand(8,8),
		'settings' => [
			'title' => !empty($author->post_title) ? $author->post_title : '',
			'content' => !empty($author_content) ? $author_content : '',
			'first_name' => !empty($first_name) ? $first_name : '',
			'last_name' => !empty($last_name) ? $last_name : '',
			'sub_title' => !empty($sub_title) ? $sub_title : '',
			'email' => !empty($email) ? $email : '',
			'contact_number' => !empty($phone) ? $phone : '',
			'education' => !empty($education) ? $education : '',
			'affiliation' => !empty($affiliation) ? $affiliation : '',
			'featured_image' => array(
				'id' => !empty($author) ? get_post_thumbnail_id( $author->ID ) : '',
				'url' => !empty($author_image['url']) ? $author_image['url'] : '',
			),
		],
	],
	[
		'quote_post_id' => $quote_id,
		'member_post_id' => $author_id,
	]
);
$popup_widget->print_element();
```

**Comment by nicholaszein** [comment]
Hello @shafiqhossain.

It seems you are not using the correct methods to create your custom widgets. Please refer to the [Developers Documentation](https://developers.elementor.com/docs/) to know how to properly build your custom widgets.

Unfortunately, we do not provide any help for 3rd-party code or plugin, and can't guide you on how you should build your addon. All the information you need is in the [Developers Documentation](https://developers.elementor.com/docs/).

I am migrating this issue to the Developer Community. Perhaps someone can help you there.

Best regards.
