### ISSUE TITLE
⛔ Slides Inactive since update to 3.20.0

### ISSUE THREAD

**Issue by millerpete** [elementor/elementor#25419]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Since upgrading to Elementor 3.20.0 our slides are not running and cannot be clicked to move on. 

### Steps to reproduce

1. Open homepage
2. Wait for slider to move
3. No movement, click icon to change slides, no activity

### Expected behavior

1. Open homepage
2. Slider moves automatically
4. Slider navigation works clicking left or right

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.7.44
	PHP Version: 7.4.33
	PHP Memory Limit: 256M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.4.3
	Site URL: https://test.bamboo-haus.com
	Home URL: https://test.bamboo-haus.com
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 256M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en_US
	Timezone: Australia/Sydney
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 3.0.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36

== Active Plugins ==
	Addressfinder
		Version: 1.5.9
		Author: Addressfinder

	Advanced Coupons for WooCommerce Free
		Version: 4.5.9.2
		Author: Rymera Web Co

	Advanced Coupons for WooCommerce Premium
		Version: 3.5.8.1
		Author: Rymera Web Co

	Akismet Anti-spam: Spam Protection
		Version: 5.3.1
		Author: Automattic - Anti-spam Team

	Child Theme Configurator
		Version: 2.6.5
		Author: Lilaea Media

	Coupon X Discount Pop Up Pro
		Version: 1.2.7
		Author: Premio

	Customer Reviews for WooCommerce
		Version: 5.38.10
		Author: CusRev

	Elementor
		Version: 3.20.0
		Author: Elementor.com

	Elementor Addons Widget
		Version: 1.0.0
		Author: Developer Debasis

	Elementor Pro
		Version: 3.20.0
		Author: Elementor.com

	FunnelKit Cart for WooCommerce
		Version: 1.4.0
		Author: FunnelKit

	ManageWP - Worker
		Version: 4.9.19
		Author: GoDaddy

	Product Code for WooCommerce
		Version: 1.4.5
		Author: Artios Media

	Product Gallery Slider for WooCommerce
		Version: 2.3.3
		Author: Codeixer

	Simple Custom CSS and JS
		Version: 3.45
		Author: SilkyPress.com

	SVG Support
		Version: 2.5.5
		Author: Benbodhi

	Use Any Font
		Version: 6.3.05
		Author: Dnesscarkey

	Variation Swatches for WooCommerce
		Version: 2.0.30
		Author: Emran Ahmed

	Variation Swatches for WooCommerce
		Version: 1.0.7
		Author: CartFlows

	Variation Swatches for WooCommerce - Pro
		Version: 2.0.30
		Author: Emran Ahmed

	WooCommerce
		Version: 8.5.2
		Author: Automattic

	WooCommerce Additional Variation Images
		Version: 2.3.2
		Author: WooCommerce

	WooCommerce Product Filters
		Version: 1.4.13
		Author: Barn2 Plugins

	WooCommerce Show Single Variations by Iconic
		Version: 1.16.2
		Author: Iconic

	Woo Product Add-ons
		Version: 6.5.2
		Author: Woo

	Woo Product Bundles
		Version: 6.22.6
		Author: Woo

	WPB Product Size Charts for WooCommerce
		Version: 1.07
		Author: wpbean

	WP Crontrol
		Version: 1.16.1
		Author: John Blackbourn & crontributors

	WPS Hide Login
		Version: 1.9.13
		Author: WPServeur, NicolasKulka, wpformation

	Yoast SEO
		Version: 21.9.1
		Author: Team Yoast

	Yoast SEO Premium
		Version: 21.8
		Author: Team Yoast


== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

	ManageWP - Worker Loader
		Version: 1.0.0
		Author: GoDaddy


== Elements Usage ==
	
	footer : 2
		heading : 3
		html : 1
		icon-list : 3
		image : 2
		image-box : 1
		social-icons : 1
	header : 2
		heading : 7
		icon : 4
		image : 6
		nav-menu : 2
		search-form : 2
		slides : 1
		social-icons : 2
		woocommerce-menu-cart : 2
	page : 10
		button : 34
		call-to-action : 4
		divider : 2
		heading : 163
		html : 4
		icon : 12
		icon-list : 5
		image : 172
		image-box : 110
		image-carousel : 2
		menu-anchor : 3
		posts : 3
		search-form : 1
		shortcode : 3
		slides : 3
		slides_addons : 2
		spacer : 36
		star-rating : 6
		testimonial-carousel : 5
		text-editor : 61
		toggle : 3
		woocommerce-products : 3
	product : 40
		button : 1
		heading : 121
		icon-list : 25
		image : 121
		image-box : 15
		image-gallery : 1
		menu-anchor : 8
		shortcode : 46
		spacer : 12
		star-rating : 8
		text-editor : 125
		toggle : 26
		woocommerce-product-add-to-cart : 30
		woocommerce-product-images : 30
		woocommerce-product-price : 27
		woocommerce-product-rating : 21
		woocommerce-product-short-description : 30
		woocommerce-product-title : 30
		woocommerce-product-upsell : 2
		woocommerce-products : 2
	section : 43
		button : 5
		call-to-action : 2
		heading : 46
		icon : 3
		icon-box : 1
		icon-list : 2
		image : 47
		image-box : 74
		loop-carousel : 1
		loop-grid : 1
		shortcode : 1
		slides : 1
		slides_addons : 3
		spacer : 9
		text-editor : 6
		toggle : 3
		woocommerce-product-add-to-cart : 1
		woocommerce-product-images : 1
		woocommerce-product-rating : 1
		woocommerce-product-short-description : 1
		woocommerce-product-title : 1
	wp-post : 110
		heading : 455
		image : 82
		spacer : 21
		text-editor : 554
	wp-page : 37
		button : 17
		call-to-action : 6
		divider : 2
		heading : 235
		html : 4
		icon : 3
		icon-box : 1
		icon-list : 2
		image : 215
		image-box : 166
		menu-anchor : 7
		posts : 3
		search-form : 1
		shortcode : 5
		slides_addons : 3
		spacer : 76
		star-rating : 5
		testimonial-carousel : 1
		text-editor : 156
		toggle : 9
		video : 5
		wc-archive-products : 1
		woocommerce-cart : 1
		woocommerce-checkout-page : 1
		woocommerce-my-account : 1
		woocommerce-product-upsell : 1
		woocommerce-products : 8
	single-post : 2
		divider : 4
		heading : 4
		image : 2
		posts : 2
		search-form : 2
		theme-post-content : 2
		theme-post-excerpt : 2
		theme-post-featured-image : 2
		theme-post-title : 2
	product-archive : 2
		woocommerce-products : 1
	loop-item : 4
		button : 2
		heading : 2
		spacer : 2
		theme-post-featured-image : 1
		wc-add-to-cart : 1
		woocommerce-product-images : 1
		woocommerce-product-title : 1
	landing-page : 1
		button : 1
		text-editor : 1
		woocommerce-products : 1


== Settings ==
	
	cpt_support: post, page, product
	allow_tracking: yes
	unfiltered_files_upload: 1


== Features ==
	Custom Fonts: 1
	Custom Icons: 0

== Integrations ==
	
	woocommerce: Active


== Elementor Experiments ==
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Upgrade Swiper Library: Active by default
	Grid Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header &amp; Footer: Active by default
	Editor Top Bar: Inactive by default
	Optimized Gutenberg Loading: Active by default
	Build with AI: Active by default
	Landing Pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default
	Optimize Image Loading: Active by default
	Notes: Active by default
	Display Conditions: Inactive by default
	Form Submissions: Active by default
	Menu: Inactive by default
	Taxonomy Filter: Inactive by default


== Log ==
	
Log: showing 20 of 282023-12-21 10:57:04 [info] elementor-pro::elementor_pro_updater Started 
2023-12-21 10:57:04 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-12-21 10:57:04 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-12-21 10:57:04 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.18.1',
  'to' => '3.18.2',
)]
2023-12-21 10:57:05 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.18.1',
  'to' => '3.18.2',
)]
2024-01-19 10:29:06 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.18.2',
  'to' => '3.18.3',
)]
2024-01-19 10:29:07 [info] elementor-pro::elementor_pro_updater Started 
2024-01-19 10:29:07 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-01-19 10:29:07 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-01-19 10:29:07 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.18.2',
  'to' => '3.18.3',
)]
2024-01-19 10:29:08 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.18.2',
  'to' => '3.18.3',
)]
2024-03-13 09:47:18 [info] elementor::elementor_updater Started 
2024-03-13 09:47:18 [info] Elementor/Upgrades - _on_each_version Start  
2024-03-13 09:47:19 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.18.3',
  'to' => '3.20.0',
)]
2024-03-13 09:47:23 [info] Elementor/Upgrades - _on_each_version Finished 
2024-03-13 09:47:23 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.18.3',
  'to' => '3.20.0',
)]
2024-03-13 14:03:56 [info] elementor-pro::elementor_pro_updater Started 
2024-03-13 14:03:56 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-03-13 14:03:56 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-03-13 14:03:56 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.18.3',
  'to' => '3.20.0',
)]

PHP: showing 11 of 11PHP: 2023-12-14 13:14:20 [warning X 48][../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key &quot;condition_type&quot; [array (
  'trace' => '
#0: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: ../wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2023-12-14 14:24:12 [error X 6][../wp-content/plugins/elementor-pro/modules/screenshots/module.php::229] Uncaught WpOrg\Requests\Exception\Http\Status403: 403 Forbidden in ../wp-content/plugins/elementor-pro/modules/screenshots/module.php:229
Stack trace:
#0 ../wp-content/plugins/elementor-pro/modules/screenshots/module.php(264): ElementorPro\Modules\Screenshots\Module-&gt;is_screenshot_proxy_mode(Array)
#1 ../wp-content/plugins/elementor/core/base/module.php(85): ElementorPro\Modules\Screenshots\Module-&gt;__construct()
#2 ../wp-content/plugins/elementor-pro/core/modules-manager.php(91): Elementor\Core\Base\Module::instance()
#3 ../wp-content/plugins/elementor-pro/plugin.php(375): ElementorPro\Core\Modules_Manager-&gt;__construct()
#4 ../wp-includes/class-wp-hook.php(324): ElementorPro\Plugin-&gt;on_elementor_init(&#039;&#039;)
#5 ../wp-includes/class-wp-hook.php(348): WP_Hook-&gt;apply_filters(NULL, Array)
#6 ../wp-includes/plugin.php(517): WP_Hook-&gt;do_action(Array)
#7 ../wp-content/plugins/elementor/includes/plugin.php(658): do_action(&#039;elementor/init&#039;)
#8 ../wp-includes/class-wp-hook.php(324): Elementor\Plugin-&gt;init(&#039;&#039;)
#9 ../wp-includes/class-wp-hook.php(348): WP_Hook-&gt;apply_filters(NULL, Array)
#10 ../wp-includes/plugin.php(517): WP_Hook-&gt;do_action(Array)
#11 ../wp-settings.php(643): do_action(&#039;init&#039;)
#12 ../wp-config.php(109): require_once(&#039;/home/bamboohau...&#039;)
#13 ../wp-load.php(50): require_once(&#039;/home/bamboohau...&#039;)
#14 ../wp-blog-header.php(13): require_once(&#039;/home/bamboohau...&#039;)
#15 ../index.php(17): require(&#039;/home/bamboohau...&#039;)
#16 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-12-21 11:17:33 [error X 16][../wp-content/plugins/elementor-pro/modules/screenshots/module.php::229] Uncaught WpOrg\Requests\Exception\Http\Status403: 403 Forbidden in ../wp-content/plugins/elementor-pro/modules/screenshots/module.php:229
Stack trace:
#0 ../wp-content/plugins/elementor-pro/modules/screenshots/module.php(264): ElementorPro\Modules\Screenshots\Module-&gt;is_screenshot_proxy_mode(Array)
#1 ../wp-content/plugins/elementor/core/base/module.php(85): ElementorPro\Modules\Screenshots\Module-&gt;__construct()
#2 ../wp-content/plugins/elementor-pro/core/modules-manager.php(91): Elementor\Core\Base\Module::instance()
#3 ../wp-content/plugins/elementor-pro/plugin.php(375): ElementorPro\Core\Modules_Manager-&gt;__construct()
#4 ../wp-includes/class-wp-hook.php(324): ElementorPro\Plugin-&gt;on_elementor_init(&#039;&#039;)
#5 ../wp-includes/class-wp-hook.php(348): WP_Hook-&gt;apply_filters(NULL, Array)
#6 ../wp-includes/plugin.php(517): WP_Hook-&gt;do_action(Array)
#7 ../wp-content/plugins/elementor/includes/plugin.php(658): do_action(&#039;elementor/init&#039;)
#8 ../wp-includes/class-wp-hook.php(324): Elementor\Plugin-&gt;init(&#039;&#039;)
#9 ../wp-includes/class-wp-hook.php(348): WP_Hook-&gt;apply_filters(NULL, Array)
#10 ../wp-includes/plugin.php(517): WP_Hook-&gt;do_action(Array)
#11 ../wp-settings.php(643): do_action(&#039;init&#039;)
#12 ../wp-config.php(108): require_once(&#039;/home/bamboohau...&#039;)
#13 ../wp-load.php(50): require_once(&#039;/home/bamboohau...&#039;)
#14 ../wp-blog-header.php(13): require_once(&#039;/home/bamboohau...&#039;)
#15 ../index.php(17): require(&#039;/home/bamboohau...&#039;)
#16 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-12-21 15:04:52 [warning X 451][../wp-content/plugins/elementor-pro/modules/woocommerce/module.php::1460] Undefined array key &quot;pages&quot; [array (
  'trace' => '
#0: ../wp-content/plugins/elementor-pro/modules/woocommerce/module.php(1460): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ../wp-content/plugins/elementor-pro/modules/woocommerce/module.php(1451): ElementorPro\Modules\Woocommerce\Module -> add_system_status_data()
#2: ../wp-includes/class-wp-hook.php(324): ElementorPro\Modules\Woocommerce\Module -> ElementorPro\Modules\Woocommerce\{closure}()
#3: ../wp-includes/plugin.php(205): WP_Hook -> apply_filters()
#4: ../wp-content/plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-system-status-v2-controller.php(1455): class type apply_filters()
',
)]
PHP: 2023-12-21 15:04:52 [warning X 451][../wp-content/plugins/elementor-pro/modules/woocommerce/module.php::1460] foreach() argument must be of type array|object, null given [array (
  'trace' => '
#0: ../wp-content/plugins/elementor-pro/modules/woocommerce/module.php(1460): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ../wp-content/plugins/elementor-pro/modules/woocommerce/module.php(1451): ElementorPro\Modules\Woocommerce\Module -> add_system_status_data()
#2: ../wp-includes/class-wp-hook.php(324): ElementorPro\Modules\Woocommerce\Module -> ElementorPro\Modules\Woocommerce\{closure}()
#3: ../wp-includes/plugin.php(205): WP_Hook -> apply_filters()
#4: ../wp-content/plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-system-status-v2-controller.php(1455): class type apply_filters()
',
)]
PHP: 2024-01-19 11:50:11 [notice X 97][../wp-content/plugins/elementor-pro/modules/woocommerce/module.php::626] parse_str(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-01-23 15:19:44 [error X 1][../wp-content/plugins/elementor-pro/modules/woocommerce/widgets/cart.php::2614] Uncaught Error: Call to a member function get_cart_contents_count() on null in ../wp-content/plugins/elementor-pro/modules/woocommerce/widgets/cart.php:2614
Stack trace:
#0 ../wp-content/plugins/elementor/includes/base/controls-stack.php(2297): ElementorPro\Modules\Woocommerce\Widgets\Cart-&gt;render()
#1 ../wp-content/plugins/elementor/includes/base/widget-base.php(614): Elementor\Controls_Stack-&gt;render_by_mode()
#2 ../wp-content/plugins/elementor/includes/base/widget-base.php(755): Elementor\Widget_Base-&gt;render_content()
#3 ../wp-content/plugins/elementor/includes/base/element-base.php(464): Elementor\Widget_Base-&gt;print_content()
#4 ../wp-content/plugins/elementor/includes/base/element-base.php(1375): Elementor\Element_Base-&gt;print_element()
#5 ../wp-content/plugins/elementor/includes/base/element-base.php(464): Elementor\Element_Base-&gt;print_content()
#6 ../wp-content/plugins/elementor/includes/base/element-base.php(1375): Elementor\Element_Base-&gt;print_element()
#7 ../wp-content/plugins/elementor/includes/base/element-base.php(464): Elementor\Element_Base-&gt;print_content()
#8 ../wp-content/plugins/elementor/core/base/document.php(1749): Elementor\Element_Base-&gt;print_element()
#9 ../wp-content/plugins/elementor/core/base/document.php(1144): Elementor\Core\Base\Document-&gt;print_elements(Array)
#10 ../wp-content/plugins/elementor/includes/frontend.php(1179): Elementor\Core\Base\Document-&gt;print_elements_with_wrapper(Array)
#11 ../wp-content/plugins/elementor/includes/frontend.php(1074): Elementor\Frontend-&gt;get_builder_content(399)
#12 ../wp-includes/class-wp-hook.php(324): Elementor\Frontend-&gt;apply_builder_in_content(&#039;&lt;h1&gt;Shopping Ca...&#039;)
#13 ../wp-includes/plugin.php(205): WP_Hook-&gt;apply_filters(&#039;&lt;h1&gt;Shopping Ca...&#039;, Array)
#14 ../wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php(1863): apply_filters(&#039;the_content&#039;, &#039;&lt;h1&gt;Shopping Ca...&#039;)
#15 ../wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php(569): WP_REST_Posts_Controller-&gt;prepare_item_for_response(Object(WP_Post), Object(WP_REST_Request))
#16 ../wp-includes/rest-api/class-wp-rest-server.php(1193): WP_REST_Posts_Controller-&gt;get_item(Object(WP_REST_Request))
#17 ../wp-includes/rest-api/class-wp-rest-server.php(1041): WP_REST_Server-&gt;respond_to_request(Object(WP_REST_Request), &#039;/wp/v2/pages/(?...&#039;, Array, NULL)
#18 ../wp-includes/rest-api/class-wp-rest-server.php(431): WP_REST_Server-&gt;dispatch(Object(WP_REST_Request))
#19 ../wp-includes/rest-api.php(424): WP_REST_Server-&gt;serve_request(&#039;/wp/v2/pages/39...&#039;)
#20 ../wp-includes/class-wp-hook.php(324): rest_api_loaded(Object(WP))
#21 ../wp-includes/class-wp-hook.php(348): WP_Hook-&gt;apply_filters(NULL, Array)
#22 ../wp-includes/plugin.php(565): WP_Hook-&gt;do_action(Array)
#23 ../wp-includes/class-wp.php(418): do_action_ref_array(&#039;parse_request&#039;, Array)
#24 ../wp-includes/class-wp.php(813): WP-&gt;parse_request(&#039;&#039;)
#25 ../wp-includes/functions.php(1336): WP-&gt;main(&#039;&#039;)
#26 ../wp-blog-header.php(16): wp()
#27 ../index.php(17): require(&#039;/home/bamboohau...&#039;)
#28 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-01-23 16:11:45 [notice X 2][../wp-content/plugins/elementor/includes/utils.php::727] strtolower(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ../wp-content/plugins/elementor/includes/utils.php(727): class type strtolower()
#2: ../wp-content/plugins/elementor-pro/modules/call-to-action/widgets/call-to-action.php(1594): Elementor\Utils :: validate_html_tag()
#3: ../wp-content/plugins/elementor/includes/base/controls-stack.php(2297): ElementorPro\Modules\CallToAction\Widgets\Call_To_Action -> render()
#4: ../wp-content/plugins/elementor/includes/base/widget-base.php(614): Elementor\Controls_Stack -> render_by_mode()
',
)]
PHP: 2024-01-29 13:34:16 [notice X 140][../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined index: condition_type [array (
  'trace' => '
#0: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: ../wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2024-01-30 14:22:11 [notice X 1][../wp-content/plugins/elementor/modules/history/revisions-manager.php::363] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-02-11 23:36:19 [error X 1][../wp-content/plugins/elementor-pro/modules/woocommerce/widgets/cart.php::2614] Uncaught Error: Call to a member function get_cart_contents_count() on null in ../wp-content/plugins/elementor-pro/modules/woocommerce/widgets/cart.php:2614
Stack trace:
#0 ../wp-content/plugins/elementor/includes/base/controls-stack.php(2297): ElementorPro\Modules\Woocommerce\Widgets\Cart-&gt;render()
#1 ../wp-content/plugins/elementor/includes/base/widget-base.php(614): Elementor\Controls_Stack-&gt;render_by_mode()
#2 ../wp-content/plugins/elementor/includes/base/widget-base.php(755): Elementor\Widget_Base-&gt;render_content()
#3 ../wp-content/plugins/elementor/includes/base/element-base.php(464): Elementor\Widget_Base-&gt;print_content()
#4 ../wp-content/plugins/elementor/includes/base/element-base.php(1375): Elementor\Element_Base-&gt;print_element()
#5 ../wp-content/plugins/elementor/includes/base/element-base.php(464): Elementor\Element_Base-&gt;print_content()
#6 ../wp-c [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 4 of 4JS: 2024-01-21 21:58:14 [error X 13][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.18.3:3:640700] Cannot read properties of undefined (reading &#039;isDesignable&#039;) 
JS: 2024-01-21 21:58:55 [error X 18][../wp-includes/js/jquery/jquery.min.js?ver=3.7.1:2:28760] Cannot read properties of undefined (reading &#039;value&#039;) 
JS: 2024-01-29 12:15:02 [error X 2][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.18.3:3:806339] Cannot read properties of undefined (reading &#039;toLowerCase&#039;) 
JS: 2024-01-30 03:35:54 [error X 1][../wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.18.3:2:16880] Cannot read properties of undefined (reading &#039;attributes&#039;) 



== Elementor - Compatibility Tag ==
	
	Elementor Addons Widget: Compatibility not specified
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hello @millerpete,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
We visited your site and could see the Slides widget working without any problem. Additionally, there have been no changes to the components of the Slides widget or related between versions 3.19 and 3.20 that would cause any issues. These component remain unchanged.


https://github.com/elementor/elementor/assets/113993460/dc989652-9936-4860-8c76-f5d6be81bbb3



### ✅ What you can do to solve your issue:
You issue is most likely caused by cache. I also see in the browser console some errors related to CORS policies, which means that the Site Migration process wasn't performed on your staging environment after migrating. Please check the article below to understand what needs to be done after migrating your site, even if it's on a staging environment:

https://elementor.com/help/site-migration/

### 👍 For now, that's all we can help with. 

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
