### ISSUE TITLE
Bug in container direction icons (Align Items and Justify Content)

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#25447]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Hi elementor team,

After updating to 3.20, this bug returned to Elementor. While it was fixed in previous versions. The problem is that in **tablet** and **mobile** mode, the Justify Content and Align Items icons do not display the correct direction.

![Screenshot](https://github.com/elementor/elementor/assets/77163248/1ec7cb03-b6fb-45f6-9560-44089aaa942c)

### Steps to reproduce

1. Add a container and add two desired element such as icons.
2. Check the Justify Content and Align Items controls on the desktop mode. It works well.
3. Now try it in tablet or mobile mode. The directions of the Align Items and Justify Content icons show the wrong directions.

### Expected behavior

-

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.54 (Win64) OpenSSL/1.1.1q PHP/8.1.10
	MySQL version: MySQL Community Server - GPL v8.0.30
	PHP Version: 8.1.10
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 2G
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.4.3
	Site URL: http://test-website.test
	Home URL: http://test-website.test
	WP Multisite: No
	Max Upload Size: 2 GB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en_US
	Timezone: 0
	Admin Email: hosein.site@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.9.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.20.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.20.0
		Author: Elementor.com


== Features ==
	Custom Fonts: 1
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Improved Asset Loading: Active
	Improved CSS Loading: Inactive
	Inline Font Icons: Inactive
	Additional Custom Breakpoints: Inactive
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active
	Grid Container: Active
	Default to New Theme Builder: Inactive
	Hello Theme Header & Footer: Inactive
	Editor Top Bar: Active
	Optimized Gutenberg Loading: Active
	Build with AI: Inactive
	Landing Pages: Inactive
	Nested Elements: Active
	Lazy Load Background Images: Active
	Optimize Image Loading: Active
	Pages Panel: Inactive by default
	Notes: Inactive
	Display Conditions: Active
	Form Submissions: Active
	Menu: Active
	Taxonomy Filter: Active


== Log ==
	
JS: showing 13 of 13JS: 2024-01-08 20:33:47 [error X 1145][http://test-website.test/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:14799] Cannot read properties of null (reading 'clone') 
JS: 2024-01-08 20:33:47 [error X 31][http://test-website.test/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:19552] Cannot read properties of null (reading 'changestop') 
JS: 2024-01-09 09:14:20 [error X 1][http://test-website.test/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.18.1:2:64171] Cannot read properties of undefined (reading 'createTemplate') 
JS: 2024-01-09 09:19:50 [error X 2][http://test-website.test/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.18.2:3:954553] Cannot read properties of undefined (reading 'settings') 
JS: 2024-01-09 21:17:49 [error X 108][http://test-website.test/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.18.2:3:7470] Cannot read properties of null (reading 'editor') 
JS: 2024-01-24 23:44:23 [error X 6][http://test-website.test/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.18.2:3:806906] Cannot read properties of undefined (reading 'localized') 
JS: 2024-02-16 12:39:51 [error X 1][http://test-website.test/wp-content/plugins/elementor/assets/js/web-cli.min.js?ver=3.19.2:3:82947] Data commands: `` not found. 
JS: 2024-02-17 12:03:39 [error X 2][http://test-website.test/wp-admin/load-scripts.php?c=1&loadchunk_0=jquery-core,jquery-migrate,utils,moxiejs,plupload&ver=6.4.3:2:28760] Cannot read properties of undefined (reading 'value') 
JS: 2024-03-06 20:17:07 [error X 1][http://test-website.test/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view1442") has already been destroyed and cannot be used. 
JS: 2024-03-06 20:28:04 [error X 1][http://test-website.test/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view1446") has already been destroyed and cannot be used. 
JS: 2024-03-07 19:37:10 [error X 1][http://test-website.test/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view7226") has already been destroyed and cannot be used. 
JS: 2024-03-07 19:47:56 [error X 1][http://test-website.test/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view8697") has already been destroyed and cannot be used. 
JS: 2024-03-07 20:04:20 [error X 1][http://test-website.test/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.19.2:3:814165] Cannot read properties of undefined (reading 'toLowerCase') 

PHP: showing 4 of 4PHP: 2024-01-08 20:36:29 [warning X 1][C:\laragon\www\test-website\wp-content\plugins\elementor\core\logger\items\js.php::17] Undefined array key "url" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-02-14 22:20:16 [error X 1][C:\laragon\www\test-website\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-manager.php::200] Uncaught Error: Class "\ElementorPro\Modules\ThemeBuilder\Conditions\General" not found in C:\laragon\www\test-website\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-manager.php:200
Stack trace:
#0 C:\laragon\www\test-website\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-manager.php(282): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->register_condition('general')
#1 C:\laragon\www\test-website\wp-includes\class-wp-hook.php(324): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->register_conditions('')
#2 C:\laragon\www\test-website\wp-includes\class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#3 C:\laragon\www\test-website\wp-includes\plugin.php(517): WP_Hook->do_action(Array)
#4 C:\laragon\www\test-website\wp-settings.php(665): do_action('wp_loaded')
#5 C:\laragon\www\test-website\wp-config.php(103): require_once('C:\\laragon\\www\\...')
#6 C:\laragon\www\test-website\wp-load.php(50): require_once('C:\\laragon\\www\\...')
#7 C:\laragon\www\test-website\wp-admin\admin-ajax.php(22): require_once('C:\\laragon\\www\\...')
#8 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-03-06 20:07:33 [notice X 75][C:\laragon\www\test-website\wp-content\plugins\elementor-pro\modules\custom-css\module.php::96] trim(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-03-11 23:24:11 [notice X 7][C:\laragon\www\test-website\wp-content\plugins\elementor\includes\base\controls-stack.php::228] hexdec(): Passing null to parameter #1 ($hex_string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 20 of 252024-02-14 22:22:17 [info] elementor-pro::elementor_pro_updater Started 
2024-02-14 22:22:17 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-02-14 22:22:17 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-02-14 22:22:17 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.18.1',
  'to' => '3.19.2',
)]
2024-03-11 23:19:19 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.19.2',
  'to' => '3.20.0',
)]
2024-03-11 23:19:19 [info] elementor-pro::elementor_pro_updater Started 
2024-03-11 23:19:19 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-03-11 23:19:19 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-03-11 23:19:19 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.19.2',
  'to' => '3.20.0',
)]
2024-03-11 23:21:18 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.19.2',
  'to' => '3.20.0',
)]
2024-03-11 23:21:20 [info] elementor::elementor_updater Started 
2024-03-11 23:21:20 [info] Elementor/Upgrades - _on_each_version Start  
2024-03-11 23:21:20 [info] Elementor/Upgrades - _on_each_version Finished 
2024-03-11 23:21:20 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.19.2',
  'to' => '3.20.0',
)]
2024-03-15 23:06:11 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.20.0',
  'to' => '3.20.1',
)]
2024-03-15 23:06:14 [info] elementor::elementor_updater Started 
2024-03-15 23:06:14 [info] Elementor/Upgrades - _on_each_version Start  
2024-03-15 23:06:14 [info] Elementor/Upgrades - _on_each_version Finished 
2024-03-15 23:06:14 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.20.0',
  'to' => '3.20.1',
)]
2024-03-15 23:06:16 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.20.0',
  'to' => '3.20.1',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hi @79ho3ein!

Thank you for submitting your issue! 🙏 

Can you please share some additional information with me? Please open the Elementor Editor, then go to **`Site Settings`** > **`Layout`** > **`Breakpoints`** and take a screenshot of the widget panel just like the below example? It would help a lot!

![image](https://github.com/elementor/elementor/assets/113993460/1ca43ff0-fac4-4c18-b3ba-cc8f56bc78dc)

**Comment by 79ho3ein** [comment]
Hi @nicholaszein,

![Uploading Screenshot.png…]()

**Comment by nicholaszein** [comment]
Thank you @79ho3ein!

We are investigating this issue, and will get back to you as soon as we have more information. This might take a real while, since this seems something deeper that needs extensive research. We suspect there is an issue, but cannot confirm yet.

Thank you for understanding! 🙏 

Kind regards
