### ISSUE TITLE
⛔ Grow animation triggers twice when used inside a Loop Grid Item template

### ISSUE THREAD

**Issue by michaelbabic** [elementor/elementor#25463]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

I am using the image animation "grow" on hover in a loop item. When I hover over the image, it grows and then suddenly returns to its starting position and grows again. The reload of the animation only happens once on every image, but every time I reload the page. I tried different image sizes, de- and reactivating lazy load, different browsers, deactivated all plugins except for Elementor and Elementor Pro, clearing the cache, creating new grid items.. the issue still exists, not just with the "grow" animation but with all animation types.

### Steps to reproduce

1. Create a loop grid and a loop grid item
2. in the loop grid item, use an image
3. in the image settings under Style / Hover choose Animation -> Grow

https://github.com/elementor/elementor/assets/71852892/509d00dd-e2e8-4b34-bb64-edfb9fc9762a

### Expected behavior

The Grow animation should play once on hover

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt

== Server Environment ==
	Operating System: Darwin
	Software: nginx/1.16.0
	MySQL version: MySQL Community Server - GPL v8.0.16
	PHP Version: 8.2.10
	PHP Memory Limit: 256M
	PHP Max Input Vars: 4000
	PHP Max Post Size: 1000M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.4.3
	Site URL: http://michael-babic.local
	Home URL: http://michael-babic.local
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: de_DE
	Timezone: Europe/Berlin
	Debug Mode: Inactive

== Theme ==
	Name: Babic
	Version: 1.0.1
	Author: Michael Babic
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 3.0.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: de-DE
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15

== Active Plugins ==
	Advanced Custom Fields
		Version: 6.2.7
		Author: WP Engine

	Classic Editor
		Version: 1.6.3
		Author: WordPress Contributors

	Custom Post Type UI
		Version: 1.15.1
		Author: WebDevStudios

	Debug Bar
		Version: 1.1.6
		Author: wordpressdotorg

	Elementor
		Version: 3.20.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.20.0
		Author: Elementor.com

	Safe SVG
		Version: 2.2.2
		Author: 10up

	WP Rocket
		Version: 3.15.9
		Author: WP Media


== Eigenschaften ==
	Custom Fonts: 2
	Custom Icons: 0

== Integrations ==
	


== Elementor-Experimente ==
	Verbessertes Laden von Assets: Standardmäßig aktiviert
	Verbessertes Laden von CSS: Aktiv
	Inline-Schriftarten-Symbole: Standardmäßig deaktiviert
	Additional Custom Breakpoints: Standardmäßig aktiviert
	admin_menu_rearrangement: Standardmäßig deaktiviert
	Flexbox Container: Aktiv
	Upgrade Swiper Library: Standardmäßig aktiviert
	Grid Container: Aktiv
	Default to New Theme Builder: Standardmäßig aktiviert
	Hello Theme Header & Footer: Standardmäßig deaktiviert
	Editor Top Bar: Standardmäßig deaktiviert
	Optimized Gutenberg Loading: Inaktiv
	Build with AI: Inaktiv
	Startseiten: Inaktiv
	Nested Elements: Aktiv
	Hintergrundbilder nachladen: Standardmäßig deaktiviert
	Optimize Image Loading: Aktiv
	Notes: Inaktiv
	Bedingungen anzeigen: Standardmäßig deaktiviert
	Form Submissions: Standardmäßig aktiviert
	Menü: Aktiv
	Taxonomy Filter: Standardmäßig deaktiviert


== Protokoll ==
	
PHP: showing 8 of 8PHP: 2024-01-23 10:26:02 [warning X 15][../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key "condition_type" [array (
  'trace' => '
#0: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: ../wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2024-01-23 10:54:07 [warning X 37][../wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-color.php::34] Undefined array key 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-02-29 15:27:29 [warning X 21][../wp-content/plugins/elementor/modules/history/revisions-manager.php::363] Undefined array key "editor_post_id" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-03-13 17:32:44 [error X 1][../wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/fonts/typekit-fonts.php::249] Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, bool given in ../wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/fonts/typekit-fonts.php:249
Stack trace:
#0 ../wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/fonts/typekit-fonts.php(249): count(false)
#1 ../wp-includes/class-wp-hook.php(324): ElementorPro\Modules\AssetsManager\AssetTypes\Fonts\Typekit_Fonts->integrations_admin_ajax_handler('')
#2 ../wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#3 ../wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 ../wp-admin/admin-ajax.php(188): do_action('wp_ajax_element...')
#5 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-03-14 10:03:11 [notice X 63][../wp-content/plugins/elementor/includes/base/controls-stack.php::228] hexdec(): Passing null to parameter #1 ($hex_string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-03-14 10:03:11 [warning X 562][../wp-content/plugins/elementor/includes/utils.php::506] Array to string conversion [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-03-14 11:08:45 [notice X 2][../wp-content/plugins/elementor-pro/modules/screenshots/module.php::33] Function utf8_decode() is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-03-14 12:18:13 [warning X 1][../wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/icons/custom-icons.php::199] unlink(malt-svgrepo-com.svg): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 9 of 9JS: 2024-01-23 09:28:18 [error X 3][../wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.18.3:2:10612] undefined is not an object (evaluating 'this.swiper.autoplay') 
JS: 2024-01-23 09:47:02 [error X 1][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.18.3:3:921789] Can't find variable: elementorFrontend 
JS: 2024-01-23 14:40:44 [error X 1][../wp-content/plugins/elementor-pro/assets/lib/sticky/jquery.sticky.min.js:1:1178] Argument 1 ('element') to Window.getComputedStyle must be an instance of Element 
JS: 2024-02-27 10:38:11 [error X 2][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.19.3:3:424230] null is not an object (evaluating 'elementor.documents.getCurrent().history') 
JS: 2024-02-27 10:39:54 [error X 1][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:20082] View (cid: "view4447") has already been destroyed and cannot be used. 
JS: 2024-02-27 12:49:55 [error X 1][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.19.3:3:697117] this.model.isValidChild is not a function. (In 'this.model.isValidChild(C)', 'this.model.isValidChild' is undefined) 
JS: 2024-02-28 11:13:27 [error X 1][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.19.3:3:814742] undefined is not an object (evaluating 'T.originalEvent.key.toLowerCase') 
JS: 2024-03-07 13:15:17 [error X 1][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:20082] View (cid: "view14318") has already been destroyed and cannot be used. 
JS: 2024-03-07 13:20:26 [error X 3][../wp-content/plugins/elementor-pro/assets/js/editor.min.js:2:64503] Object.entries requires that input parameter not be null or undefined 

Log: showing 20 of 252024-02-27 11:32:42 [info] elementor-pro::elementor_pro_updater Started 
2024-02-27 11:32:42 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-02-27 11:32:42 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-02-27 11:32:42 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.18.3',
  'to' => '3.19.3',
)]
2024-02-27 11:32:42 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.18.3',
  'to' => '3.19.3',
)]
2024-02-29 10:50:39 [info] elementor::elementor_updater Started 
2024-02-29 10:50:39 [info] Elementor/Upgrades - _on_each_version Start  
2024-02-29 10:50:39 [info] Elementor/Upgrades - _on_each_version Finished 
2024-02-29 10:50:39 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.19.3',
  'to' => '3.19.4',
)]
2024-02-29 10:50:39 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.19.3',
  'to' => '3.19.4',
)]
2024-03-13 17:33:15 [info] elementor::elementor_updater Started 
2024-03-13 17:33:15 [info] Elementor/Upgrades - _on_each_version Start  
2024-03-13 17:33:15 [info] Elementor/Upgrades - _on_each_version Finished 
2024-03-13 17:33:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.19.4',
  'to' => '3.20.1',
)]
2024-03-13 17:33:15 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.19.4',
  'to' => '3.20.1',
)]
2024-03-14 09:59:33 [info] elementor-pro::elementor_pro_updater Started 
2024-03-14 09:59:33 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-03-14 09:59:33 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-03-14 09:59:33 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.19.3',
  'to' => '3.20.0',
)]
2024-03-14 09:59:33 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.19.3',
  'to' => '3.20.0',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Kompatibel

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by michaelbabic** [comment]
Also: The glitch / issue / bug is not limited to the "grow" animation. It happens with the other animations too.

**Comment by nicholaszein** [comment]
Hello @michaelbabic ,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
We followed your steps to reproduce and even tested using Ajax enabled pagination to see if the problem could be caused by js reloading styles, but still we could not reproduce your issue. See the video below:


https://github.com/elementor/elementor/assets/113993460/c5643a8d-cd94-43ad-9186-35fd296f230d



### ✅ What you can do to solve your issue:
Your issue is most likely caused by cache. We see you are using WP Rocket on a local installation. 

Please, when submitting a bug report, make sure you have troubleshooted the issue first by isolating the problem and only loading Elementor and Elementor Pro as indicated in the Bug Report Form. Check your cache settings to avoid this from happening.

### 👍 For now, that's all we can help with. 

Kind regards
