### ISSUE TITLE
🧩 Elementor's Yoast SEO Google preview: Snippet variable not outputting the value

### ISSUE THREAD

**Issue by Apfelbiss** [elementor/elementor#25494]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Snippet variables of the Yoast SEO Google preview are not outputting the value – this does only happen within the Elementor editor.

I saw a reported issue at Yoast SEO repository, but searching for "elementor-editor-wrapper"*, I could only find it within the Elementor code, not within the Yoast SEO code.

https://github.com/Yoast/wordpress-seo/issues/20908

_* Edit: Okay, my fault: Maybe I'm not already awake. I now recognized that this wasn't the best phrase to search for. But I'm irritated because this happens only in Elementor editor. Therefor I thought this could also be a problem caused by Elementor?_ 

### Steps to reproduce

1. Edit the page via the Elementor editor
2. Select search appearance > and add snippets like "Site title"
3. You can notice that the Google preview shows the **%%sitetitle%%** within the Google Preview

### Expected behavior

The **value** of the snippet variable should be shown correctly within the Google Preview

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server - GPL v8.0.36
	PHP Version: 8.2.17
	PHP Memory Limit: 2048M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 2048M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.4.3
	Site URL: 
	Home URL: 
	WP Multisite: No
	Max Upload Size: 2 GB
	Memory limit: 40M
	Max Memory limit: 2048M
	Permalink Structure: /%category%/%postname%/
	Language: en_US
	Timezone: Europe/Berlin
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 3.0.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:123.0) Gecko/20100101 Firefox/123.0

== Active Plugins ==
	Elementor
		Version: 3.20.2
		Author: Elementor.com

	Yoast SEO
		Version: 22.3
		Author: Team Yoast


== Elementor Experiments ==
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Additional Custom Breakpoints: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Upgrade Swiper Library: Active by default
	Grid Container: Inactive by default
	Hello Theme Header &amp; Footer: Active by default
	Editor Top Bar: Inactive by default
	Optimized Gutenberg Loading: Active by default
	Build with AI: Active by default
	Landing Pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default
	Optimize Image Loading: Active by default


== Log ==
	
JS: showing 20 of 25JS: 2024-02-15 09:14:57 [error X 1][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:0] View (cid: &quot;view7824&quot;) has already been destroyed and cannot be used. 
JS: 2024-02-15 09:14:58 [error X 1][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:0] View (cid: &quot;view7822&quot;) has already been destroyed and cannot be used. 
JS: 2024-02-15 09:30:05 [error X 1][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:0] View (cid: &quot;view7779&quot;) has already been destroyed and cannot be used. 
JS: 2024-02-15 09:30:35 [error X 1][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:0] View (cid: &quot;view12222&quot;) has already been destroyed and cannot be used. 
JS: 2024-02-15 09:35:50 [error X 1][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:0] View (cid: &quot;view6103&quot;) has already been destroyed and cannot be used. 
JS: 2024-02-15 09:37:52 [error X 1][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:0] View (cid: &quot;view6036&quot;) has already been destroyed and cannot be used. 
JS: 2024-02-15 09:57:54 [error X 1][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:0] View (cid: &quot;view5309&quot;) has already been destroyed and cannot be used. 
JS: 2024-02-15 10:00:10 [error X 1][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:0] View (cid: &quot;view5595&quot;) has already been destroyed and cannot be used. 
JS: 2024-02-15 10:00:10 [error X 1][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:0] View (cid: &quot;view5597&quot;) has already been destroyed and cannot be used. 
JS: 2024-02-15 10:12:22 [error X 1][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:0] View (cid: &quot;view5992&quot;) has already been destroyed and cannot be used. 
JS: 2024-02-15 10:20:05 [error X 1][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:0] View (cid: &quot;view18846&quot;) has already been destroyed and cannot be used. 
JS: 2024-02-15 10:30:26 [error X 1][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:0] View (cid: &quot;view7736&quot;) has already been destroyed and cannot be used. 
JS: 2024-02-15 10:41:11 [error X 1][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:0] View (cid: &quot;view6031&quot;) has already been destroyed and cannot be used. 
JS: 2024-02-15 10:42:59 [error X 1][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:0] View (cid: &quot;view9769&quot;) has already been destroyed and cannot be used. 
JS: 2024-02-15 10:44:28 [error X 1][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:0] View (cid: &quot;view6436&quot;) has already been destroyed and cannot be used. 
JS: 2024-02-15 10:45:20 [error X 1][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:0] View (cid: &quot;view9407&quot;) has already been destroyed and cannot be used. 
JS: 2024-02-15 10:47:29 [error X 1][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:0] View (cid: &quot;view6963&quot;) has already been destroyed and cannot be used. 
JS: 2024-02-15 10:49:00 [error X 1][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:0] View (cid: &quot;view12924&quot;) has already been destroyed and cannot be used. 
JS: 2024-02-29 09:40:18 [error X 1][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.19.2:3:632673] this.$currentEditingArea is null 
JS: 2024-03-01 10:36:06 [error X 1][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view4872&quot;) has already been destroyed and cannot be used. 

PHP: showing 3 of 3PHP: 2024-02-11 09:05:27 [error X 3][../wp-content/plugins/elementor/data/v2/base/controller.php::227] Uncaught Elementor\Data\V2\Base\Exceptions\WP_Error_Exception: Die Methode ‚WP_REST_Controller::get_item_permissions_check‘ wurde nicht implementiert. Sie muss in der Unterklasse überschrieben werden. in ../wp-content/plugins/elementor/data/v2/base/controller.php:227
Stack trace:
#0 ../wp-content/plugins/elementor/data/v2/base/base-route.php(105): Elementor\Data\V2\Base\Controller-&gt;get_permission_callback()
#1 ../wp-content/plugins/elementor/data/v2/base/base-route.php(242): Elementor\Data\V2\Base\Base_Route-&gt;get_permission_callback()
#2 ../wp-includes/rest-api/class-wp-rest-server.php(1160): Elementor\Data\V2\Base\Base_Route-&gt;Elementor\Data\V2\Base\{closure}()
#3 ../wp-includes/rest-api/class-wp-rest-server.php(1041): WP_REST_Server-&gt;respond_to_request()
#4 ../wp-includes/rest-api/class-wp-rest-server.php(431): WP_REST_Server-&gt;dispatch()
#5 ../wp-includes/rest-api.php(424): WP_REST_Server-&gt;serve_request()
#6 ../wp-includes/class-wp-hook.php(324): rest_api_loaded()
#7 ../wp-includes/class-wp-hook.php(348): WP_Hook-&gt;apply_filters()
#8 ../wp-includes/plugin.php(565): WP_Hook-&gt;do_action()
#9 ../wp-includes/class-wp.php(418): do_action_ref_array()
#10 ../wp-includes/class-wp.php(813): WP-&gt;parse_request()
#11 ../wp-includes/functions.php(1336): WP-&gt;main()
#12 ../wp-blog-header.php(16): wp()
#13 ../index.php(17): require(&#039;...&#039;)
#14 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-02-12 09:09:17 [notice X 44][../wp-content/plugins/elementor-pro/modules/custom-css/module.php::96] trim(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-02-13 13:52:26 [notice X 1852][../wp-content/plugins/elementor-pro/modules/woocommerce/module.php::626] parse_str(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 15 of 152024-02-13 11:51:25 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.18.3',
  'to' => '3.19.2',
)]
2024-02-13 11:51:29 [info] elementor::elementor_updater Started 
2024-02-13 11:51:29 [info] Elementor/Upgrades - _on_each_version Start  
2024-02-13 11:51:29 [info] Elementor/Upgrades - _on_each_version Finished 
2024-02-13 11:51:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.18.3',
  'to' => '3.19.2',
)]
2024-03-05 14:28:16 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.19.2',
  'to' => '3.19.4',
)]
2024-03-05 14:28:18 [info] elementor::elementor_updater Started 
2024-03-05 14:28:18 [info] Elementor/Upgrades - _on_each_version Start  
2024-03-05 14:28:18 [info] Elementor/Upgrades - _on_each_version Finished 
2024-03-05 14:28:18 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.19.2',
  'to' => '3.19.4',
)]
2024-03-05 14:28:20 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.19.2',
  'to' => '3.19.4',
)]
2024-03-22 09:00:31 [info] elementor::elementor_updater Started 
2024-03-22 09:00:31 [info] Elementor/Upgrades - _on_each_version Start  
2024-03-22 09:00:31 [info] Elementor/Upgrades - _on_each_version Finished 
2024-03-22 09:00:31 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.19.4',
  'to' => '3.20.2',
)]



== Elementor - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hello @Apfelbiss!

Thank you for reaching out! 🙏 

I reached out to the Yoast team, as this isn't really a bug caused by Elementor. And they informed they already have an issue related to this bug on their repository. [#20908](https://github.com/Yoast/wordpress-seo/issues/20908)

Please continue the conversation there.

As a reminder, we only deal with Elementor bugs here. Anything else, especially caused by 3rd-party plugins should be posted on their respective support channels!

Kind regards
