### ISSUE TITLE
Background color cannot be overridden when global color is assigned.

### ISSUE THREAD

**Issue by Henzxon** [elementor/elementor#25569]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Global color cannot be overridden once set.

https://app.screencast.com/UleqSnJGU9Ykk

### Steps to reproduce

1. Set global color
2. Override

### Expected behavior

Global color should automatically be unset once a custom value is added.

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.44-48
	PHP Version: 7.4.33
	PHP Memory Limit: 768M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.4.3
	Site URL: https://shannonb159.sg-host.com
	Home URL: https://shannonb159.sg-host.com
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 256M
	Max Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: en_AU
	Timezone: Australia/Brisbane
	Admin Email: admin@eastbound.digital
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 3.0.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en-AU
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.20.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.20.2
		Author: Elementor.com


== Elements Usage ==
	
	archive : 1
		container : 1
		loop-grid : 1
		theme-archive-title : 1
	footer : 1
		button : 1
		container : 6
		divider : 1
		heading : 5
		icon-list : 5
		image : 1
		social-icons : 1
		text-editor : 4
	header : 1
		button : 1
		container : 1
		image : 1
		nav-menu : 1
	wp-page : 4
		button : 15
		container : 29
		form : 1
		heading : 37
		html : 1
		icon-box : 8
		icon-list : 3
		image : 3
		nested-accordion : 1
		text-editor : 23
	single-post : 1
		author-box : 1
		container : 5
		form : 1
		heading : 2
		loop-grid : 1
		post-comments : 1
		post-info : 1
		post-navigation : 1
		progress-tracker : 1
		share-buttons : 1
		table-of-contents : 2
		theme-post-content : 1
		theme-post-featured-image : 1
		theme-post-title : 1
	single-page : 1
		container : 1
		divider : 1
		heading : 1
		theme-post-content : 1
	search-results : 1
		container : 1
		loop-grid : 1
		search-form : 1
		theme-archive-title : 1
	loop-item : 1
		container : 2
		image : 1
		post-info : 1
		theme-post-excerpt : 1
		theme-post-title : 1
	error-404 : 1
		button : 2
		container : 1
		heading : 1
		html : 1
		text-editor : 1


== Settings ==
	
	cpt_support: post, page
	disable_color_schemes: yes
	disable_typography_schemes: yes
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap
	load_fa4_shim: yes
	disabled_elements: wp-widget-pages, wp-widget-calendar, wp-widget-archives, wp-widget-media_audio, wp-widget-media_image, wp-widget-media_gallery, wp-widget-media_video, wp-widget-meta, wp-widget-search, wp-widget-text, wp-widget-categories, wp-widget-recent-posts, wp-widget-recent-comments, wp-widget-rss, wp-widget-tag_cloud, wp-widget-nav_menu, wp-widget-custom_html, wp-widget-block, facebook-page, facebook-embed, facebook-comments, facebook-button, login, audio, paypal-button, stripe-button, lottie


== Features ==
	Custom Fonts: 2
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Improved Asset Loading: Inactive
	Improved CSS Loading: Inactive
	Inline Font Icons: Active
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active by default
	Upgrade Swiper Library: Active by default
	Grid Container: Inactive by default
	Default to New Theme Builder: Inactive
	Hello Theme Header & Footer: Inactive
	Editor Top Bar: Active
	Optimized Gutenberg Loading: Active by default
	Build with AI: Inactive
	Landing Pages: Active by default
	Nested Elements: Active
	Lazy Load Background Images: Inactive by default
	Optimize Image Loading: Active by default
	Pages Panel: Inactive by default
	Notes: Inactive
	Display Conditions: Inactive by default
	Form Submissions: Active by default
	Menu: Inactive by default
	Taxonomy Filter: Inactive by default


== Log ==
	
Log: showing 20 of 362024-03-14 05:32:47 [info] elementor::elementor_updater Started 
2024-03-14 05:32:47 [info] Elementor/Upgrades - _on_each_version Start  
2024-03-14 05:32:47 [info] Elementor/Upgrades - _on_each_version Finished 
2024-03-14 05:32:47 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.20.0',
  'to' => '3.20.1',
)]
2024-03-14 05:32:47 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.20.0',
  'to' => '3.20.1',
)]
2024-03-21 23:21:55 [info] elementor::elementor_updater Started 
2024-03-21 23:21:55 [info] Elementor/Upgrades - _on_each_version Start  
2024-03-21 23:21:55 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.20.1',
  'to' => '3.20.2',
)]
2024-03-21 23:21:56 [info] Elementor/Upgrades - _on_each_version Finished 
2024-03-21 23:21:56 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.20.1',
  'to' => '3.20.2',
)]
2024-03-27 06:13:15 [info] elementor::elementor_updater Started 
2024-03-27 06:13:15 [info] Elementor/Upgrades - _on_each_version Start  
2024-03-27 06:13:15 [info] Elementor/Upgrades - _on_each_version Finished 
2024-03-27 06:13:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.20.2',
  'to' => '3.20.3',
)]
2024-03-27 06:13:15 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.20.2',
  'to' => '3.20.3',
)]
2024-03-28 17:52:59 [info] elementor-pro::elementor_pro_updater Started 
2024-03-28 17:52:59 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-03-28 17:52:59 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-03-28 17:52:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.20.0',
  'to' => '3.20.2',
)]
2024-03-28 17:52:59 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.20.0',
  'to' => '3.20.2',
)]

PHP: showing 4 of 4PHP: 2024-03-20 02:17:27 [error X 1][/home/customer/www/shannonb159.sg-host.com/public_html/wp-content/plugins/elementor/core/wp-api.php::26] Uncaught Error: Call to undefined function Elementor\Core\get_plugins() in /home/customer/www/shannonb159.sg-host.com/public_html/wp-content/plugins/elementor/core/wp-api.php:26
Stack trace:
#0 /home/customer/www/shannonb159.sg-host.com/public_html/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(96): Elementor\Core\Wp_Api->get_plugins()
#1 /home/customer/www/shannonb159.sg-host.com/public_html/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(58): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_with_header()
#2 /home/customer/www/shannonb159.sg-host.com/public_html/wp-content/plugins/elementor/modules/compatibility-tag/module.php(57): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_to_check()
#3 /home/customer/www/shannonb159.sg-host.com/public_html/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(148): Elementor\Modules\CompatibilityTag\Module->get_plugins_to_check()
#4 /home/customer/www/shannonb159.sg-host.com/public_ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-03-28 18:25:17 [notice X 1][/home/customer/www/shannonb159.sg-host.com/public_html/wp-content/plugins/elementor/includes/elements/container.php::1845] Undefined index: size [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-03-28 19:45:22 [notice X 9][/home/customer/www/shannonb159.sg-host.com/public_html/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/fonts-manager.php::252] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-03-28 20:10:18 [notice X 3][/home/customer/www/shannonb159.sg-host.com/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined index: condition_type [array (
  'trace' => '
#0: /home/customer/www/shannonb159.sg-host.com/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /home/customer/www/shannonb159.sg-host.com/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /home/customer/www/shannonb159.sg-host.com/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /home/customer/www/shannonb159.sg-host.com/public_html/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]

JS: showing 2 of 2JS: 2024-03-28 08:07:03 [error X 12][https://shannonb159.sg-host.com/wp-content/plugins/elementor/assets/js/ai.min.js?ver=3.20.3:3:7564] ReactUtils is not defined 
JS: 2024-03-28 08:22:09 [error X 2][https://shannonb159.sg-host.com/wp-admin/load-scripts.php?c=0&loadchunk_0=jquery-core,jquery-migrate,utils,moxiejs,plupload&ver=6.4.3:2:28760] Cannot read properties of undefined (reading 'value') 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hello @Henzxon! 

Thank you for submitting your issue! 🙏 

Please allow us some time to investigate it, and get back to you with our findings. 🧐 

Although, I'm pretty sure this is not a bug in Elementor. I add and remove global colors from container backgrounds all the time. But I'll record a video to check if this could be reproduced. 😉 

Best regards
