### ISSUE TITLE
Post Excerpt in Loop Grid showing HTML if Excerpt Length set and image in Woocommerce Short Description

### ISSUE THREAD

**Issue by awebguy99** [elementor/elementor#25607]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

I've already logged a support ticket with Elementor. **They managed to reproduce the issue and have passed it onto the Elementor developers**. But when I asked later if there was an update, I was advised to log a issue on Github.

The issue is when you have a Woocommerce product, with an embedded image in the Short Description, with the Loop Grid.
The way I build the loop template was quite common for ecommerce products; Product image, price, add to cart etc.
Also I need to display a short part of the product's Short Description. I had to use the Post Excerpt widget for this, as I needed to set a Excerpt Length (otherwise, the loop items would be very large height / look terrible).

This all works but for products that has embedded image(s) in the Short Description, when the Excerpt Length is fairly short (around 10), it breaks the front end / shows the partial HTML of the embedded image.

I think the solution will be to have an option to ignore HTML in product Short Descriptions.

### Steps to reproduce

1. Create a Woocommerce product and add/embed an image (near or at the top) into the Short Description.
2. Create a loop grid, in the item template, add a Post Excerpt widget.
3. Set a Excerpt Length of 10.
4. Save and look at the grid on the front end. That product will show the HTML of the image, not the image (attached)
![Loop-grid-item-showing-partial-HTML](https://github.com/elementor/elementor/assets/59077593/cd971ede-a217-4e34-920a-adafe73d0248)
.

### Expected behavior

It should either show the image or ideally there should be an option to ignore images (maybe even ignore/strip out all HTML) in Short Description and only display the text.

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.58 (Debian)
	MySQL version: mariadb.org binary distribution v10.4.33
	PHP Version: 8.1.27
	PHP Memory Limit: 512M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.4.3
	Site URL: xxxxxxxx
	Home URL: xxxxxxxx
	WP Multisite: No
	Max Upload Size: 100 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en_NZ
	Timezone: 12
	Admin Email: xxxxxx
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 3.0.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en-NZ
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36

== Active Plugins ==
	
	Elementor
		Version: 3.20.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.20.2
		Author: Elementor.com

	WooCommerce
		Version: 8.7.0
		Author: Automattic


== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

	NinjaFirewall WP (mu-plugin)
		Version: 1.0
		Author: The Ninja Technologies Network

	Object Cache Pro (MU)
		Version: 1.20.2
		Author: Rhubarb Group


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	
	recaptcha_v3: Active
	woocommerce: Active


== Elementor Experiments ==
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Inactive by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active by default
	Grid Container: Active
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Inactive by default
	Editor Top Bar: Inactive by default
	Optimized Gutenberg Loading: Active by default
	Build with AI: Active by default
	Landing Pages: Active by default
	Nested Elements: Active
	Lazy Load Background Images: Inactive by default
	Optimize Image Loading: Active by default
	Notes: Inactive
	Display Conditions: Inactive by default
	Form Submissions: Active by default
	Menu: Inactive by default
	Taxonomy Filter: Inactive by default


== Log ==
	
Log: showing 20 of 342024-03-19 12:57:50 [info] elementor-pro::elementor_pro_updater Started 
2024-03-19 12:57:50 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-03-19 12:57:50 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-03-19 12:57:50 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.19.3',
  'to' => '3.20.0',
)]
2024-03-26 09:59:38 [info] elementor-pro::elementor_pro_updater Started 
2024-03-26 09:59:38 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.20.0',
  'to' => '3.20.1',
)]
2024-03-26 09:59:38 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-03-26 09:59:38 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-03-26 09:59:38 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.20.0',
  'to' => '3.20.1',
)]
2024-03-26 09:59:56 [info] elementor::elementor_updater Started 
2024-03-26 09:59:56 [info] Elementor/Upgrades - _on_each_version Start  
2024-03-26 09:59:56 [info] Elementor/Upgrades - _on_each_version Finished 
2024-03-26 09:59:56 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.20.1',
  'to' => '3.20.2',
)]
2024-04-02 14:20:03 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.20.2',
  'to' => '3.20.3',
)]
2024-04-02 14:20:04 [info] elementor-pro::elementor_pro_updater Started 
2024-04-02 14:20:04 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-04-02 14:20:04 [info] Elementor/Upgrades - _on_each_version Finished 
2024-04-02 14:20:04 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.20.1',
  'to' => '3.20.2',
)]
2024-04-02 14:20:04 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.20.2',
  'to' => '3.20.3',
)]
2024-04-02 14:20:04 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.20.1',
  'to' => '3.20.2',
)]

JS: showing 4 of 4JS: 2024-03-19 01:10:33 [error X 21][https://xxxxxxxxxxx/wp-includes/js/jquery/jquery.min.js?ver=3.7.1:2:28760] Cannot read properties of undefined (reading 'value') 
JS: 2024-03-19 01:51:30 [error X 5][https://xxxxxxxxxxx/wp-content/plugins/elementor/assets/js/common-modules.min.js?ver=3.20.1:2:56156] Model.isValidChild() should be implemented, please provide 'isValidChild' functionality. 
JS: 2024-04-02 02:31:36 [error X 10][https://xxxxxxxxxxx/wp-content/plugins/elementor/assets/js/ai.min.js?ver=3.20.3:3:7564] ReactUtils is not defined 
JS: 2024-04-02 03:15:00 [error X 1][https://xxxxxxxxxxx/wp-admin/post.php?post=2923&action=elementor:10:14] Cannot read properties of undefined (reading 'title') 

PHP: showing 4 of 4PHP: 2024-03-19 13:11:40 [warning X 8][xxxxxxxxxxx/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key "condition_type" [array (
  'trace' => '
#0: xxxxxxxxxxx/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: xxxxxxxxxxx/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: xxxxxxxxxxx/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: xxxxxxxxxxx/public_html/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2024-03-19 13:15:15 [warning X 6][xxxxxxxxxxx/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::179] Undefined array key "editor_post_id" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-03-19 13:51:45 [warning X 1][xxxxxxxxxxx/public_html/wp-content/plugins/elementor/includes/elements/container.php::1845] Undefined array key "size" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-03-21 03:30:52 [error X 1][xxxxxxxxxxx/public_html/wp-content/plugins/elementor-pro/modules/woocommerce/widgets/cart.php::2647] Uncaught Error: Call to a member function get_cart_contents_count() on null in xxxxxxxxxxx/public_html/wp-content/plugins/elementor-pro/modules/woocommerce/widgets/cart.php:2647
Stack trace:
#0 xxxxxxxxxxx/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(2321): ElementorPro\Modules\Woocommerce\Widgets\Cart->render()
#1 xxxxxxxxxxx/public_html/wp-content/plugins/elementor/includes/base/widget-base.php(634): Elementor\Controls_Stack->render_by_mode()
#2 xxxxxxxxxxx/public_html/wp-content/plugins/elementor/includes/base/widget-base.php(775): Elementor\Widget_Base->render_content()
#3 xxxxxxxxxxx/public_html/wp-content/plugins/elementor/includes/base/element-base.php(464): Elementor\Widget_Base->print_content()
#4 xxxxxxxxxxx/public_html/wp-content/plugins/elementor/includes/base/element-base.php(1375): Elementor\Element_Base->print_element()
#5 xxxxxxxxxxx/public_html/wp-content/plugins/elementor/includes/base/element-base.php(464): Elementor\Element_Base->print_content()
#6 xxxxxxxxxxx/public_html/wp-content/plugins/elementor/core/base/document.php(1795): Elementor\Element_Base->print_element()
#7 xxxxxxxxxxx/public_html/wp-content/plugins/elementor/core/base/document.php(1183): Elementor\Core\Base\Document->print_elements()
#8 xxxxxxxxxxx/public_html/wp-content/plugins/elementor/includes/frontend.php(1165): Elementor\Core\Base\Document->print_elements_with_wrapper()
#9 xxxxxxxxxxx/public_html/wp-content/plugins/elementor/includes/frontend.php(1060): Elementor\Frontend->get_builder_content()
#10 xxxxxxxxxxx/public_html/wp-includes/class-wp-hook.php(324): Elementor\Frontend->apply_builder_in_content()
#11 xxxxxxxxxxx/public_html/wp-includes/plugin.php(205): WP_Hook->apply_filters()
#12 xxxxxxxxxxx/public_html/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php(1863): apply_filters()
#13 xxxxxxxxxxx/public_html/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php(569): WP_REST_Posts_Controller->prepare_item_for_response()
#14 xxxxxxxxxxx/public_html/wp-includes/rest-api/class-wp-rest-server.php(1193): WP_REST_Posts_Controller->get_item()
#15 xxxxxxxxxxx/public_html/wp-includes/rest-api/class-wp-rest-server.php(1041): WP_REST_Server->respond_to_request()
#16 xxxxxxxxxxx/public_html/wp-includes/rest-api/class-wp-rest-server.php(431): WP_REST_Server->dispatch()
#17 xxxxxxxxxxx/public_html/wp-includes/rest-api.php(424): WP_REST_Server->serve_request()
#18 xxxxxxxxxxx/public_html/wp-includes/class-wp-hook.php(324): rest_api_loaded()
#19 xxxxxxxxxxx/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#20 xxxxxxxxxxx/public_html/wp-includes/plugin.php(565): WP_Hook->do_action()
#21 xxxxxxxxxxx/public_html/wp-includes/class-wp.php(418): do_action_ref_array()
#22 xxxxxxxxxxx/public_html/wp-includes/class-wp.php(813): WP->parse_request()
#23 xxxxxxxxxxx/public_html/wp-includes/functions.php(1336): WP->main()
#24 xxxxxxxxxxx/public_html/wp-blog-header.php(16): wp()
#25 xxxxxxxxxxx/public_html/index.php(17): require('/home/xxxxxxxxxxx...')
#26 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by awebguy99** [comment]
If an Elementor dev wants to direct message me (is that a thing in Github?), I can send URL to show the issue, plus the Elementor support ticket ref (where they confirmed it's an issue).

**Comment by awebguy99** [comment]
Hey Elementor, any update on this please? It's definitely a reproducible bug.

**Comment by nicholaszein** [comment]
Hello @awebguy99 ! 

Thank you for submitting your issue! 🙏 

Please allow us some time to investigate it, and get back to you with our findings. 🧐 

Best regards
