### ISSUE TITLE
⛔ 🧩 Support for product types in the product add to cart module

### ISSUE THREAD

**Issue by leeszeek** [elementor/elementor#25675]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Support for product types in the product adding module to the card on the example of plugins: Woocommerce, WooCommerce Stripe Payment Gateway, Elementor and Elementor Pro.

The WooCommerce plugin creates four types of products: simple, variable, grouped and external.
The WooCommerce Stripe Payment Gateway plugin creates the fifth type of product: variable-subscription.
In Elementor Pro in a file _elementor-pro/modules/woocommerce/widgets/product-add-to-cart.php_ in function _public _function should_add_container()_ there is support for four product types (default ones from WooCommerce), while due to the lack of specified product types in line 129 _case 'woocommerce_after_add_to_cart_button':_ a problem arises.

Opening element `<div class="e-atc-qty-button-holder">` from function _public function before_add_to_cart_quantity()_ (line 145) it is added only for two types of products: simple, variable.

The problem is to add a closing element `</div>` in function _public function after_add_to_cart_button()_ (line 159) in each product type (in the four default ones from the WooCommerce plugin and an infinite number of other types). In this case, the variable-subscription product type will receive a closing element but not an opening element. This creates a problem in the HTML structure.

### Steps to reproduce

1. Install WooCommerce.
2. Install WooCommerce Stripe Payment Gateway.
3. Install Elementor.
4. Install Elementor Pro.
5. Add product and change type to variable subscription.
6. Check front product page.

### Expected behavior

1. Add `return in_array( $product->get_type(), [ 'simple', 'variable', 'grouped', 'external' ], true );` in _elementor-pro/modules/woocommerce/widgets/product-add-to-cart.php_ in line 130.

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt

== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.6.16
	PHP Version: 8.0.30
	PHP Memory Limit: 1000M
	PHP Max Input Vars: 100000
	PHP Max Post Size: 500M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.4.3
	Site URL: https://arturprzybylowski.pl
	Home URL: https://arturprzybylowski.pl
	WP Multisite: No
	Max Upload Size: 500 MB
	Memory limit: 512M
	Max Memory limit: 1000M
	Permalink Structure: /%postname%/
	Language: pl_PL
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: OceanWP Child Theme
	Version: 1.0
	Author: OceanWP
	Child Theme: Yes
	Parent Theme Name: OceanWP
	Parent Theme Version: 3.5.5
	Parent Theme Author: OceanWP

== User ==
	Role: administrator
	WP Profile lang: pl-PL
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:125.0) Gecko/20100101 Firefox/125.0

== Active Plugins ==
	Business Bloomer WooCommerce Toggle Payments By Category
		Version: 4.2.20231009
		Author: Business Bloomer

	Elementor
		Version: 3.20.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.20.2
		Author: Elementor.com

	Essential Addons for Elementor
		Version: 5.9.14
		Author: WPDeveloper

	FiboSearch - AJAX Search for WooCommerce
		Version: 1.27.0
		Author: FiboSearch Team

	Google Listings and Ads
		Version: 2.6.4
		Author: WooCommerce

	Imagify
		Version: 2.2.1
		Author: Imagify – Optimize Images & Convert WebP & Avif

	Loco Translate
		Version: 2.6.7
		Author: Tim Whitlock

	Maintenance
		Version: 4.08
		Author: WebFactory Ltd

	Ocean Extra
		Version: 2.2.6
		Author: OceanWP

	PixelYourSite
		Version: 9.5.4
		Author: PixelYourSite

	Timeline Widget For Elementor
		Version: 1.5.7
		Author: Cool Plugins

	UpdraftPlus - Backup/Restore
		Version: 1.24.2
		Author: UpdraftPlus.Com, DavidAnderson

	WooCommerce
		Version: 8.7.0
		Author: Automattic

	WooCommerce Przelewy24 Payment Gateway
		Version: 1.0.16
		Author: Przelewy24 Sp. z o.o.

	WooCommerce Stripe Gateway
		Version: 8.1.0
		Author: WooCommerce

	Woo Subscriptions
		Version: 6.0.0
		Author: WooCommerce

	WP Calorie Calculator Pro
		Version: 4.4.0
		Author: Belov Digital Agency

	WP Rocket
		Version: 3.15.9
		Author: WP Media


== Must-Use Plugins ==
	WordPress automation by Installatron
		Version: 
		Author: 


== Składniki oferty ==
	Custom Fonts: 0
	Custom Icons: 0

== Integracje ==
	
	woocommerce: Aktywny


== Eksperymenty z Elementorem ==
	Ulepszone ładowanie zasobów: Domyślnie aktywne
	Poprawione ładowanie CSS: Domyślnie aktywne
	Czcionka ikon: Domyślnie nieaktywne
	Dodatkowe niestandardowe punkty zmiany: Domyślnie aktywne
	admin_menu_rearrangement: Domyślnie nieaktywne
	Flexbox Container: Domyślnie nieaktywne
	Upgrade Swiper Library: Domyślnie aktywne
	Grid Container: Domyślnie nieaktywne
	Default to New Theme Builder: Domyślnie aktywne
	Editor Top Bar: Domyślnie nieaktywne
	Optimized Gutenberg Loading: Domyślnie aktywne
	Build with AI: Domyślnie aktywne
	Strony docelowe: Domyślnie aktywne
	Elementy zagnieżdżone: Domyślnie nieaktywne
	Leniwe ładowanie obrazów tła: Domyślnie nieaktywne
	Optimize Image Loading: Domyślnie aktywne
	Notes: Domyślnie aktywne
	Wyświetl warunki: Domyślnie nieaktywne
	Form Submissions: Domyślnie aktywne
	Menu: Domyślnie nieaktywne
	Taxonomy Filter: Domyślnie nieaktywne


== Dziennik ==
	
Log: showing 20 of 302023-12-06 11:40:47 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.17.3',
  'to' => '3.18.0',
)]
2023-12-06 11:46:32 [info] elementor-pro::elementor_pro_updater Started 
2023-12-06 11:46:32 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-12-06 11:46:32 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-12-06 11:46:32 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.17.1',
  'to' => '3.18.0',
)]
2024-03-13 12:31:47 [info] elementor::elementor_updater Started 
2024-03-13 12:31:47 [info] Elementor/Upgrades - _on_each_version Start  
2024-03-13 12:31:48 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.18.0',
  'to' => '3.20.1',
)]
2024-03-13 12:31:48 [info] Elementor/Upgrades - _on_each_version Finished 
2024-03-13 12:31:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.18.0',
  'to' => '3.20.1',
)]
2024-03-27 21:18:28 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.20.1',
  'to' => '3.20.3',
)]
2024-03-27 21:18:28 [info] elementor::elementor_updater Started 
2024-03-27 21:18:28 [info] Elementor/Upgrades - _on_each_version Start  
2024-03-27 21:18:29 [info] Elementor/Upgrades - _on_each_version Finished 
2024-03-27 21:18:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.20.1',
  'to' => '3.20.3',
)]
2024-03-27 21:18:34 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.18.0',
  'to' => '3.20.2',
)]
2024-03-27 21:18:34 [info] elementor-pro::elementor_pro_updater Started 
2024-03-27 21:18:34 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-03-27 21:18:34 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-03-27 21:18:34 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.18.0',
  'to' => '3.20.2',
)]

PHP: showing 2 of 2PHP: 2023-12-06 16:03:59 [warning X 1][../wp-content/plugins/elementor/core/files/manager.php::111] unlink(../wp-content/uploads/elementor/css/post-71.css): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-03-30 22:01:59 [error X 2][../wp-content/plugins/elementor-pro/modules/woocommerce/widgets/product-add-to-cart.php::56] Uncaught Error: Call to undefined method ElementorPro\Modules\Woocommerce\Widgets\Product_Add_To_Cart::render_form_button() in ../wp-content/plugins/elementor-pro/modules/woocommerce/widgets/product-add-to-cart.php:56
Stack trace:
#0 ../wp-content/plugins/elementor/includes/base/controls-stack.php(2321): ElementorPro\Modules\Woocommerce\Widgets\Product_Add_To_Cart-&gt;render()
#1 ../wp-content/plugins/elementor/includes/base/widget-base.php(634): Elementor\Controls_Stack-&gt;render_by_mode()
#2 ../wp-content/plugins/elementor/includes/base/widget-base.php(775): Elementor\Widget_Base-&gt;render_content()
#3 ../wp-content/plugins/elementor/includes/base/element-base.php(464): Elementor\Widget_Base-&gt;print_content()
#4 ../wp-content/plugins/elementor/includes/base/element-base.php(1375): Elementor\Element_Base-&gt;print_element()
#5 ../wp-content/plugins/elementor/includes/base/element-base.php(464): Elementor\Element_Base-&gt;print_content()
#6 ../wp-content/plugins/elementor/includes/base/element-base.php(1375): Elementor\Element_Base-&gt;print_element()
#7 ../wp-content/plugins/elementor/includes/base/element-base.php(464): Elementor\Element_Base-&gt;print_content()
#8 ../wp-content/plugins/elementor/core/base/document.php(1795): Elementor\Element_Base-&gt;print_element()
#9 ../wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(412): Elementor\Core\Base\Document-&gt;print_elements(Array)
#10 ../wp-content/plugins/elementor/includes/frontend.php(1165): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document-&gt;print_elements_with_wrapper(Array)
#11 ../wp-content/plugins/elementor/core/base/document.php(1231): Elementor\Frontend-&gt;get_builder_content(2778, false)
#12 ../wp-content/plugins/elementor/modules/library/documents/library-document.php(76): Elementor\Core\Base\Document-&gt;get_content(false)
#13 ../wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(158): Elementor\Modules\Library\Documents\Library_Document-&gt;get_content(false)
#14 ../wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(173): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document-&gt;get_content()
#15 ../wp-content/plugins/elementor-pro/modules/theme-builder/documents/single-base.php(93): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document-&gt;print_content()
#16 ../wp-content/plugins/elementor-pro/modules/woocommerce/documents/product.php(133): ElementorPro\Modules\ThemeBuilder\Documents\Single_Base-&gt;print_content()
#17 ../wp-content/plugins/elementor-pro/modules/theme-builder/classes/locations-manager.php(364): ElementorPro\Modules\Woocommerce\Documents\Product-&gt;print_content()
#18 ../wp-content/plugins/elementor-pro/modules/theme-builder/classes/locations-manager.php(240): ElementorPro\Modules\ThemeBuilder\Classes\Locations_Manager-&gt;do_location(&#039;single&#039;)
#19 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Locations_Manager-&gt;ElementorPro\Modules\ThemeBuilder\Classes\{closure}()
#20 ../wp-content/plugins/elementor/modules/page-templates/module.php(207): call_user_func(Object(Closure))
#21 ../wp-content/plugins/elementor/modules/page-templates/templates/header-footer.php(19): Elementor\Modules\PageTemplates\Module-&gt;print_content()
#22 ../wp-includes/template-loader.php(106): include(&#039;/home/srv52798/...&#039;)
#23 ../wp-blog-header.php(19): require_once(&#039;/home/srv52798/...&#039;)
#24 ../index.php(17): require(&#039;/home/srv52798/...&#039;)
#25 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 10 of 10JS: 2024-02-10 12:16:41 [error X 4][../wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.18.0:2:64227] Cannot convert undefined or null to object 
JS: 2024-03-25 12:26:09 [error X 5][../wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.18.0:2:64227] can&#039;t convert undefined to object 
JS: 2024-03-25 15:44:43 [error X 2][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.20.1:3:816027] can&#039;t access property &quot;localized&quot;, this.store.find(...) is undefined 
JS: 2024-03-29 12:15:03 [error X 8][../wp-content/plugins/elementor/assets/js/ai.min.js?ver=3.20.3:3:7564] ReactUtils is not defined 
JS: 2024-03-29 12:25:14 [error X 10][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.20.3:3:648673] Cannot read properties of undefined (reading &#039;isDesignable&#039;) 
JS: 2024-03-30 21:20:02 [error X 2][../wp-content/plugins/elementor/assets/js/admin.min.js?ver=3.20.3:3:48028] can&#039;t access property &quot;value&quot;, c[0] is undefined 
JS: 2024-04-04 14:22:21 [error X 3][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.20.3:3:971148] Cannot read properties of undefined (reading &#039;view&#039;) 
JS: 2024-04-04 14:51:48 [error X 4][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.20.3:3:1145118] Cannot read properties of null (reading &#039;getBoundingClientRect&#039;) 
JS: 2024-04-08 14:45:07 [error X 1594][../wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:14799] Cannot read properties of null (reading &#039;clone&#039;) 
JS: 2024-04-08 14:45:08 [error X 35][../wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:19552] Cannot read properties of null (reading &#039;changestop&#039;) 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Kompatybilność nieokreślona
	Essential Addons for Elementor: Kompatybilność nieokreślona
	Timeline Widget For Elementor: Kompatybilność nieokreślona

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hi, @leeszeek,

Thank you for reaching out! 🙏 

### ⛔ After reviewing your report we concluded this is not a bug caused by Elementor. The feature you're referring to is not supported.

Elementor does not provide support for 3rd-party WooCommerce addons. What you are reporting here is more of a Feature Request than anything else.

If you think this should be an Elementor feature, please submit a new [🚀 Feature Request](https://github.com/orgs/elementor/discussions/new?category=feature-request), and we will consider it in the future if there is enough demand (votes) from other users.

## Please use GitHub Issues only to report Bugs in the code of Elementor. GitHub issues are not for requesting support for integration with 3rd-party plugins.

Kind regards
