### ISSUE TITLE
🐞 Vertical Alignment for the Icon Box Position does not work on mobile

### ISSUE THREAD

**Issue by ajoah** [elementor/elementor#25713]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

On mobile preview, if you align the icon on the left, you can not change the vertical align, the buttons do nothing.

It seems due to these lines (vertical align is ignored on mobile by css media queries) : https://github.com/elementor/elementor/blob/836150299806a6bdb4ef08c1fb22b4cd12e2624d/assets/dev/scss/frontend/widgets/icon-box.scss#L79-L104

### Steps to reproduce

![elementor-icon-box](https://github.com/elementor/elementor/assets/10757301/a619838f-4411-4bf6-8dc6-45b6d5dace61)

### Expected behavior

Vertical align changes when I click on the buttons

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: (Ubuntu) v5.7.42
	PHP Version: 8.0.30
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 20M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.5.2
	Site URL: https://www.elementor.unikmedia.fr
	Home URL: https://www.elementor.unikmedia.fr
	WP Multisite: No
	Max Upload Size: 20 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en_US
	Timezone: Europe/Paris
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor
	Version: 3.0.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 6.2.9
		Author: WP Engine

	Elementor
		Version: 3.21.0-dev3
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.21.0-beta3
		Author: Elementor.com


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Active by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active by default
	Upgrade Swiper Library: Active by default
	Grid Container: Active by default
	Nested Elements Performance: Inactive by default
	Optimized Control Loading: Active by default
	Default to New Theme Builder: Active by default
	Hello Theme Header &amp; Footer: Active by default
	Elementor Home Screen: Inactive by default
	Editor Top Bar: Active by default
	Build with AI: Active by default
	Landing Pages: Active by default
	Nested Elements: Active by default
	Lazy Load Background Images: Active by default
	Pages Panel: Inactive by default
	Display Conditions: Active by default
	Form Submissions: Active by default
	Menu: Active by default
	Taxonomy Filter: Active by default


== Log ==
	
JS: showing 13 of 13JS: 2024-01-08 20:33:47 [error X 1145][../wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:14799] Cannot read properties of null (reading 'clone') 
JS: 2024-01-08 20:33:47 [error X 31][../wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:19552] Cannot read properties of null (reading 'changestop') 
JS: 2024-01-09 09:14:20 [error X 1][../wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.18.1:2:64171] Cannot read properties of undefined (reading 'createTemplate') 
JS: 2024-01-09 09:19:50 [error X 2][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.18.2:3:954553] Cannot read properties of undefined (reading 'settings') 
JS: 2024-01-09 21:17:49 [error X 108][../wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.18.2:3:7470] Cannot read properties of null (reading 'editor') 
JS: 2024-01-24 23:44:23 [error X 6][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.18.2:3:806906] Cannot read properties of undefined (reading 'localized') 
JS: 2024-02-16 12:39:51 [error X 1][../wp-content/plugins/elementor/assets/js/web-cli.min.js?ver=3.19.2:3:82947] Data commands: `` not found. 
JS: 2024-02-17 12:03:39 [error X 2][../wp-admin/load-scripts.php?c=1&loadchunk_0=jquery-core,jquery-migrate,utils,moxiejs,plupload&ver=6.4.3:2:28760] Cannot read properties of undefined (reading 'value') 
JS: 2024-03-06 20:17:07 [error X 1][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view1442") has already been destroyed and cannot be used. 
JS: 2024-03-06 20:28:04 [error X 1][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view1446") has already been destroyed and cannot be used. 
JS: 2024-03-07 19:37:10 [error X 1][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view7226") has already been destroyed and cannot be used. 
JS: 2024-03-07 19:47:56 [error X 1][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view8697") has already been destroyed and cannot be used. 
JS: 2024-03-07 20:04:20 [error X 1][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.19.2:3:814165] Cannot read properties of undefined (reading 'toLowerCase') 

PHP: showing 4 of 4PHP: 2024-01-08 20:36:29 [warning X 1][..\wp-content\plugins\elementor\core\logger\items\js.php::17] Undefined array key "url" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-02-14 22:20:16 [error X 1][..\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-manager.php::200] Uncaught Error: Class "\ElementorPro\Modules\ThemeBuilder\Conditions\General" not found in ..\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-manager.php:200
Stack trace:
#0 ..\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-manager.php(282): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->register_condition('general')
#1 ..\wp-includes\class-wp-hook.php(324): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->register_conditions('')
#2 ..\wp-includes\class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#3 ..\wp-includes\plugin.php(517): WP_Hook->do_action(Array)
#4 ..\wp-settings.php(665): do_action('wp_loaded')
#5 ..\wp-config.php(103): require_once('C:\\laragon\\www\\...')
#6 ..\wp-load.php(50): require_once('C:\\laragon\\www\\...')
#7 ..\wp-admin\admin-ajax.php(22): require_once('C:\\laragon\\www\\...')
#8 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-03-06 20:07:33 [notice X 75][..\wp-content\plugins\elementor-pro\modules\custom-css\module.php::96] trim(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-03-11 23:24:11 [notice X 7][..\wp-content\plugins\elementor\includes\base\controls-stack.php::228] hexdec(): Passing null to parameter #1 ($hex_string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 20 of 252024-02-14 22:22:17 [info] elementor-pro::elementor_pro_updater Started 
2024-02-14 22:22:17 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-02-14 22:22:17 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-02-14 22:22:17 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.18.1',
  'to' => '3.19.2',
)]
2024-03-11 23:19:19 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.19.2',
  'to' => '3.20.0',
)]
2024-03-11 23:19:19 [info] elementor-pro::elementor_pro_updater Started 
2024-03-11 23:19:19 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-03-11 23:19:19 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-03-11 23:19:19 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.19.2',
  'to' => '3.20.0',
)]
2024-03-11 23:21:18 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.19.2',
  'to' => '3.20.0',
)]
2024-03-11 23:21:20 [info] elementor::elementor_updater Started 
2024-03-11 23:21:20 [info] Elementor/Upgrades - _on_each_version Start  
2024-03-11 23:21:20 [info] Elementor/Upgrades - _on_each_version Finished 
2024-03-11 23:21:20 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.19.2',
  'to' => '3.20.0',
)]
2024-03-15 23:06:11 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.20.0',
  'to' => '3.20.1',
)]
2024-03-15 23:06:14 [info] elementor::elementor_updater Started 
2024-03-15 23:06:14 [info] Elementor/Upgrades - _on_each_version Start  
2024-03-15 23:06:14 [info] Elementor/Upgrades - _on_each_version Finished 
2024-03-15 23:06:14 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.20.0',
  'to' => '3.20.1',
)]
2024-03-15 23:06:16 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.20.0',
  'to' => '3.20.1',
)]== Log ==
	
Log: showing 20 of 372023-01-14 10:45:53 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.0-dev2',
  'to' => '3.11.0-dev3',
)]
2023-02-16 14:29:43 [info] elementor::elementor_updater Started 
2023-02-16 14:29:43 [info] Elementor/Upgrades - _on_each_version Start  
2023-02-16 14:29:43 [info] Elementor/Upgrades - _on_each_version Finished 
2023-02-16 14:29:43 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.0-dev3',
  'to' => '3.12.0-dev4',
)]
2023-02-16 14:29:43 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.0-dev3',
  'to' => '3.12.0-dev4',
)]
2024-04-12 09:58:30 [info] elementor::elementor_updater Started 
2024-04-12 09:58:30 [info] Elementor/Upgrades - _on_each_version Start  
2024-04-12 09:58:30 [info] Elementor/Upgrades - _on_each_version Finished 
2024-04-12 09:58:30 [info] Elementor/Upgrades - _v_3_16_0_container_updates Start  
2024-04-12 09:58:31 [info] Elementor/Upgrades - _v_3_16_0_container_updates Finished 
2024-04-12 09:58:31 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Start  
2024-04-12 09:58:31 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Finished 
2024-04-12 09:58:31 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.0-dev4',
  'to' => '3.21.0-dev3',
)]
2024-04-12 09:58:31 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.0-dev4',
  'to' => '3.21.0-dev3',
)]
2024-04-12 09:59:30 [info] elementor-pro::elementor_pro_updater Started 
2024-04-12 09:59:30 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-04-12 09:59:30 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-04-12 09:59:30 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.0-dev2',
  'to' => '3.21.0-beta3',
)]
2024-04-12 09:59:30 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.0-dev2',
  'to' => '3.21.0-beta3',
)]

PHP: showing 4 of 4PHP: 2022-12-28 07:51:19 [notice X 31][../wp-content/plugins/elementor/includes/base/controls-stack.php::229] Invalid characters passed for attempted conversion, these have been ignored [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-28 07:51:21 [notice X 1][../wp-content/plugins/elementor/includes/base/controls-stack.php::229] Invalid characters passed for attempted conversion, these have been ignored [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ../wp-content/plugins/elementor/includes/base/controls-stack.php(229): class type hexdec()
#2: ../wp-content/plugins/elementor/includes/widgets/accordion.php(531): Elementor\Controls_Stack -> get_id_int()
#3: ../wp-content/plugins/elementor/includes/base/controls-stack.php(2266): Elementor\Widget_Accordion -> render()
#4: ../wp-content/plugins/elementor/includes/base/widget-base.php(609): Elementor\Controls_Stack -> render_by_mode()
',
)]
PHP: 2022-12-28 17:12:55 [warning X 6][../wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key &quot;data&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-12-05 01:50:58 [notice X 1][../wp-content/plugins/elementor/includes/base/controls-stack.php::229] Invalid characters passed for attempted conversion, these have been ignored [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ../wp-content/plugins/elementor/includes/base/controls-stack.php(229): class type hexdec()
#2: ../wp-content/plugins/elementor/includes/widgets/accordion.php(534): Elementor\Controls_Stack -> get_id_int()
#3: ../wp-content/plugins/elementor/includes/base/controls-stack.php(2268): Elementor\Widget_Accordion -> render()
#4: ../wp-content/plugins/elementor/includes/base/widget-base.php(609): Elementor\Controls_Stack -> render_by_mode()
',
)]

JS: showing 1 of 1JS: 2024-04-12 08:06:54 [error X 1][../wp-content/plugins/elementor/assets/js/editor.js?ver=3.21.0-dev3:40584:71] Cannot read properties of undefined (reading &#039;toLowerCase&#039;) 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hello @ajoah! 

Thank you for submitting your issue! 🙏 

🏷️ We've labeled this issue and our team will take a look at it. If there is indeed a problem, they'll work on fixing it. We can't say exactly when it'll be sorted out, but we kindly ask for your patience. Thanks for understanding!

Best regards

**Comment by dkiryakov** [comment]
I have the same exact issue.

**Comment by saulposel** [comment]
The .elementor-vertical-align-middle class only applies for @media (min-width: 768px), and the mobile (dynamic) class does not appear to be set for the mobile vertical align setting, so `align-items: center;` never applies to the mobile viewport sizes.

**Comment by tporter90** [comment]
I've just added the following into the Additional CSS box as a temporary fix.

@media only screen and (max-width: 768px) {.elementor-icon-box-content {
	align-self:center;
	margin-top:-10px
	}}

**Comment by wesleyv010** [comment]
it works but now there is a problem with the alignment when you are on a tablet. So unfortunatly not a great fix :(

**Comment by JanWebofka** [comment]
> it works but now there is a problem with the alignment when you are on a tablet. So unfortunatly not a great fix :(

I used this workaroud:

/* Fix Icon box aligment */

    .elementor-vertical-align-middle .elementor-icon-box-icon {
    display: flex!important;
    align-items: center;
    }
    .elementor-vertical-align-middle .elementor-icon-box-content {
    display: flex!important;
    align-items: center;
    }
    .elementor-position-left .elementor-widget-container {
    display: flex;
    align-items: center;
    
Be awere of these classes  .elementor-vertical-align-middle and .elementor-position-left

**Comment by ProtoUI** [comment]
Similar bug with #25401? Maybe they can fix both at the same time?

**Comment by Novavamp** [comment]
I used this workaround to fix the issue:

```
@media (max-width: 767px) {
    .elementor-widget-image-box .elementor-image-box-wrapper {
        display: flex;
        align-items: center; /* Vertical alignment */
        justify-content: flex-start; /* Ensures left alignment */
        flex-wrap: nowrap; /* Prevents wrapping */
    }

    .elementor-widget-image-box .elementor-image-box-img {
        margin-right: 10px; /* Adds spacing between the image and text */
    }

    .elementor-widget-image-box .elementor-image-box-content {
        text-align: left; /* Ensures text aligns properly */
    }
}
```

**Comment by nicholaszein** [comment]
Hey everyone!

It finally happened! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor v3.31.0! 🥳 

Icon alignment for the Icon Box on mobile should work as intended now! Thank you for your patience! 🙏 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂 

----

If you think this is still an issue caused by Elementor after updating to the latest version, and can reproduce it consistently after following our [Contribution Guidelines](https://elemn.to/gh-contributing-bug-reports), feel free to open a new 🐞 [Bug Report](https://elemn.to/gh-new-bug-report), and we will be happy to review your case.
