### ISSUE TITLE
TypeKit Get Project ID throws 500 Server Error

### ISSUE THREAD

**Issue by puregraphx** [elementor/elementor#25829]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

I am working on a brand new site with only E and E Pro. I have started to tweak the Style Kit and now entered my Adobe TypeKit ID, but when I hit "Get Project ID", I see a 500 server error for admin-ajax.php.

In the server log, I see:

[STDERR] PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, bool given in /var/www/stelina.studiomecaro.com/htdocs/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/fonts/typekit-fonts.php:249
Stack trace:
#0 /var/www/stelina.studiomecaro.com/htdocs/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/fonts/typekit-fonts.php(249): count()
#1 /var/www/stelina.studiomecaro.com/htdocs/wp-includes/class-wp-hook.php(324): ElementorPro\Modules\AssetsManager\AssetTypes\Fonts\Typekit_Fonts->integrations_admin_ajax_handler()
#2 /var/www/stelina.studiomecaro.com/htdocs/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#3 /var/www/stelina.studiomecaro.com/htdocs/wp-includes/plugin.php(517): WP_Hook->do_action()
#4 /var/www/stelina.studiomecaro.com/htdocs/wp-admin/admin-ajax.php(192): do_action()
#5 {main}
  thrown in /var/www/stelina.studiomecaro.com/htdocs/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/fonts/typekit-fonts.php on line 249

I have rolled back to previous versions, but it does not fix the issue. I have checked with other sites on the same VPS, using the same Elementor versions, it works on other sites.

### Steps to reproduce

1. Go to /wp-admin/admin.php?page=elementor-settings#tab-integrations
2. Enter a valid TypeKit ID
3. Hit "Get Project ID"

### Expected behavior

Did not expect 500 Server Error as this works on other sites on the same server with the same E and E Pro versions.

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: Ubuntu 22.04 v10.6.16
	PHP Version: 8.2.18
	PHP Memory Limit: 256M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.5.2
	Site URL: https://stelina.studiomecaro.com
	Home URL: https://stelina.studiomecaro.com
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: nl_NL
	Timezone: Europe/Brussels
	Admin Email: info@puregraphx.be
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 2.0.0
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 3.0.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en-GB
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.21.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.21.0
		Author: Elementor.com

	WP SVG Images
		Version: 4.2
		Author: ShortPixel


== Must-Use Plugins ==
	WP CLI Login Command Server
		Version: 1.5
		Author: Evan Mattson

	WP fail2ban
		Version: 5.2.2.1
		Author: Charles Lecklider


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Improved asset loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Active by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active by default
	Upgrade Swiper Library: Active by default
	Grid Container: Active by default
	Nested Elements Performance: Inactive by default
	Optimized Control Loading: Active
	Default to New Theme Builder: Inactive
	Hello Theme Header &amp; Footer: Inactive
	Elementor Home Screen: Active by default
	Editor Top Bar: Inactive by default
	Build with AI: Inactive
	Landing pages: Inactive
	Nested Elements: Inactive by default
	Lazy Load Background Images: Active by default
	Display Conditions: Active by default
	Form Submissions: Inactive
	Menu: Inactive by default
	Taxonomy Filter: Inactive


== Log ==
	
PHP: showing 2 of 2PHP: 2024-04-24 10:32:03 [warning X 11][/var/www/stelina.studiomecaro.com/htdocs/wp-content/plugins/elementor/includes/managers/image.php::113] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-04-24 11:31:32 [error X 12][/var/www/stelina.studiomecaro.com/htdocs/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/fonts/typekit-fonts.php::249] Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, bool given in /var/www/stelina.studiomecaro.com/htdocs/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/fonts/typekit-fonts.php:249
Stack trace:
#0 /var/www/stelina.studiomecaro.com/htdocs/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/fonts/typekit-fonts.php(249): count()
#1 /var/www/stelina.studiomecaro.com/htdocs/wp-includes/class-wp-hook.php(324): ElementorPro\Modules\AssetsManager\AssetTypes\Fonts\Typekit_Fonts-&gt;integrations_admin_ajax_handler()
#2 /var/www/stelina.studiomecaro.com/htdocs/wp-includes/class-wp-hook.php(348): WP_Hook-&gt;apply_filters()
#3 /var/www/stelina.studiomecaro.com/htdocs/wp-includes/plugin.php(517): WP_Hook-&gt;do_action()
#4 /var/www/stelina.studiomecaro.com/htdocs/wp-admin/admin-ajax.php(192): do_action()
#5 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 5 of 52024-04-24 10:56:23 [info] elementor-pro::elementor_pro_updater Started 
2024-04-24 10:56:23 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-04-24 10:56:23 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-04-24 10:56:23 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.20.0',
  'to' => '3.21.0',
)]
2024-04-24 10:56:23 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.20.0',
  'to' => '3.21.0',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by xhuljojakup** [comment]
The error you're encountering is due to calling count() on a variable that is false. This happens because fetch_typekit_data() returns false on failure, and count() requires an array or a Countable object.

To fix this, you need to ensure that fetch_typekit_data() returns an empty array instead of false when it fails. Here’s how you can modify the relevant part of your code:
Modify the fetch_typekit_data method

### Change the return value from false to an empty array when the fetch operation fails:

File location: elementor-pro/modules/assets-manager/asset-types/fonts/typekit-fonts.php 

private function fetch_typekit_data() {
    $kit_id = $this->get_typekit_kit_id();
    if ( ! $kit_id ) {
        return [];
    }

    $response = wp_remote_get( $this->api_base . '/' . $kit_id . '/published' );

    // Response is a WP_Error object
    if ( is_wp_error( $response ) ) {
        return [];
    }

    // Response code is not success
    $response_code = (int) wp_remote_retrieve_response_code( $response );
    $response_body = json_decode( wp_remote_retrieve_body( $response ) );
    if ( 200 !== $response_code ) {
        switch ( $response_code ) {
            case 404:
                $this->error = esc_html__( 'Project not found.', 'elementor-pro' );
                break;
            default:
                $this->error = $response_code;
                if ( isset( $response_body->errors ) ) {
                    $this->error .= ': ' . implode( ', ', $response_body->errors );
                }
                break;
        }

        return [];
    }

    if ( ! $response_body ) {
        $this->error = esc_html__( 'No project data was returned.', 'elementor-pro' );
        return [];
    }

    if ( ! is_object( $response_body ) || ! isset( $response_body->kit ) || ! isset( $response_body->kit->families ) || ! is_array( $response_body->kit->families ) ) {
        return [];
    }

    $families = [];
    foreach ( $response_body->kit->families as $font_family ) {
        $font_css = isset( $font_family->css_names[0] ) ? $font_family->css_names[0] : $font_family->slug;
        $families[ $font_css ] = $this->get_type();
    }
    update_option( self::TYPEKIT_FONTS_OPTION_NAME, $families );

    return $families;
}


### Modify the integrations_admin_ajax_handler method

Add a check to ensure $fonts is an array before calling count():

public function integrations_admin_ajax_handler() {
    check_ajax_referer( self::TYPEKIT_KIT_ID_OPTION_NAME, '_nonce' );

    if ( ! current_user_can( Fonts_Manager::CAPABILITY ) ) {
        wp_send_json_error( 'Permission denied' );
    }

    $kit_id = Utils::_unstable_get_super_global_value( $_POST, 'kit_id' );

    if ( ! $kit_id ) {
        wp_send_json_error();
    }
    
    $fonts = [];
    try {
        update_option( 'elementor_' . self::TYPEKIT_KIT_ID_OPTION_NAME, sanitize_text_field( $kit_id ) );
        $fonts = $this->fetch_typekit_data();
    } catch ( \Exception $exception ) {
        wp_send_json_error();
    }

    if (!is_array($fonts)) {
        $fonts = [];
    }

    wp_send_json_success( [
        'fonts' => $fonts,
        'count' => count( $fonts ),
    ] );
}


While this solution works, it is recommended to ensure that the Typekit project contains fonts.

**Comment by puregraphx** [comment]
Thank you for a workaround, but with the current rate of updates released by Elementor, changing core files is not something we consider. We have not created the Typekit, but will ask our client why it doesn't seem to contain any fonts.

**Comment by puregraphx** [comment]
I have discussed this with GridPane because the issue is present on certain servers, but non existing on different servers. GridPane support thinks that some of our Hetzner servers' IPs might be blocked from connecting to the Adobe API.
For sites that really need the Adobe Fonts, we have moved them to another server that succeeds in connecting to Above API and then it works.

I don't get a 403 when I visit my typekit.com link directly, or curl it.

**Comment by xhuljojakup** [comment]
I can't fully agree, as I've encountered this issue on both Digital Ocean
and WP Engine servers as well.

**Comment by puregraphx** [comment]
@gjportegies we have 7 servers at GridPane, 6 of them are Hetzner, 1 is Vultr.
Three of those Hetzners servers are showing issues with Adobe Fonts, all three are in the 128.140.*.* range. The other 3 servers without issues start with 49, 157 and 116.
That is consistent with your findings.

**Comment by puregraphx** [comment]
This is the answer I got from Hetzner

> The change or assignment of desired IP addresses is not offered from our side. Among other things, this is because we want to prevent abuse of these.
In your case, there is accordingly the possibility to create a new server, however there is no influence from our side on the blocking of third parties like national Firewalls or similar.
Please note we have to intervene in case of excessive creation of servers to change IP addresses.

So even if you clone a server via a snapshot, there is no guarantee that the new server will be outside of the blocked 128.140 range. And if you trial/error this too often, they will intervene.

**Comment by ircoony** [comment]
I have exactly the same problem with a website on a hetzner server within this ip range. Is this issue caused by Adobe blocking this ip range?

**Comment by ircoony** [comment]
@gjportegies ah okay. And there is nothing Adobe can do to correct this?

I was able to connect adobe fonts the first time with Elementor. Since I added new fonts and try to sync the fonts I get this error. I have also tried third party plugins. These also give error. If the ip is blocked the first time would also give an error or not?

**Comment by puregraphx** [comment]
>@gjportegies ah okay. And there is nothing Adobe can do to correct this?

Adobe is only using the GeoIP databases, they can't change anything in these databases. If anything, it should be Hetzner trying to delist or try to correctly identify the IPs origin in the GeoIP database. 

>I was able to connect adobe fonts the first time with Elementor. Since I added new fonts and try to sync the fonts I get this error. I have also tried third party plugins. These also give error. If the ip is blocked the first time would also give an error or not?

It depends, an IP can get blocked at a certain moment, maybe your first sync dates from before the ban.

**Comment by ircoony** [comment]
It was somewhere in july I first connected the website with Adobe fonts. I just have moved the website to a new Hetzner server with a different ip range and it is working now. 
Very easy to do btw with ploi as server management tool.

**Comment by puregraphx** [comment]
> It was somewhere in july I first connected the website with Adobe fonts. I just have moved the website to a new Hetzner server with a different ip range and it is working now. Very easy to do btw with ploi as server management tool.

yeah, that what I also do, deploy sites where I'll need Adobe Fonts to a Hetzner server that isn't blocked. Site move / Server clone is also very easy via GridPane.

**Comment by asleepwithdreams** [comment]
Hi, I came here to say that this happens on all three servers I have with Hetzner. I opened a ticket with Elementor in July 2023 about this issue, and the problem still needs to be resolved. The servers are in Ashburn, VA and Hillsboro, OR. IP addresses 5.78.126.* 5.78.110.* 5.161.144.* I tested this on Vultr and was able to connect TypeKit without error. I am not sure what geolocation db Adobe is referencing, but when I check, they show up in the USA.

**Comment by puregraphx** [comment]
I don't think this is an issue that Elementor can/should fix, this is between Hetzner and Adobe (via geolocation database in the middle).

**Comment by ircoony** [comment]
No I agree, it has nothing to do with Elementor. I've tried other ways to get it working, but that didn't work too. The only thing that helped, is migrating to a different server (ip). It's probably a minor issue for Hertzner and adobe :-)
