### ISSUE TITLE
video player in lightbox does not recognize default aspect ratio in v3.21.3

### ISSUE THREAD

**Issue by joehdevwp** [elementor/elementor#25880]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

The elementor video widget defaults to an aspect ratio of 16:9. However when viewing the video in the elementor lightbox on the front end, the variable --video-aspect-ratio used in this elementor css returns 'null' and does not use the 1.777 fallback, resulting in an iframe box that is full vh but only 300px wide: 

elementor-lightbox .elementor-video-container .elementor-video-landscape iframe, .elementor-lightbox .elementor-video-container .elementor-video-landscape video, .elementor-lightbox .elementor-video-container .elementor-video-portrait iframe, .elementor-lightbox .elementor-video-container .elementor-video-portrait video, .elementor-lightbox .elementor-video-container .elementor-video-square iframe, .elementor-lightbox .elementor-video-container .elementor-video-square video {
    aspect-ratio: var(--video-aspect-ratio, 1.77777);
}

from /wp-content/plugins/elementor/assets/css/frontend-lite.min.css?ver=3.21.3

If the aspect ratio is changed to something other than the 16:9 default, it seems to work correctly. 

Error from Sys Info:
PHP: 2024-04-27 22:05:43 [warning X 43][/www/wp-content/plugins/elementor/includes/widgets/video.php::1076] Undefined array key "aspect_ratio" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

### Steps to reproduce

1. add an elementor video widget to a page and set to display with 16:9 and view in lightbox
2. inspect on front end

### Expected behavior

video in lightbox should have a 16:9 aspect ratio when the 16:9 aspect ratio is selected. 

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
== Server Environment ==
	Operating System: Linux
	Software: Flywheel/5.1.0
	MySQL version: (Google) v5.7.44
	PHP Version: 8.2.18
	PHP Memory Limit: 128M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 300M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: There are some writing permissions issues with the following directories/files:
		 - WordPress root directory
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.5.2
	Site URL: 
	Home URL: 
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 128M
	Max Memory limit: 128M
	Permalink Structure: /%postname%/
	Language: en_US
	Timezone: 0
	Admin Email: 
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 3.0.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36

== Active Plugins ==
	Admin and Site Enhancements (ASE)
		Version: 6.9.9
		Author: wpase.com

	Elementor
		Version: 3.21.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.21.1
		Author: Elementor.com

	JetEngine
		Version: 3.4.3
		Author: Crocoblock

	JetPopup
		Version: 2.0.4
		Author: Crocoblock

	JetTabs For Elementor
		Version: 2.2.2
		Author: Crocoblock

	TinyPNG - JPEG, PNG & WebP image compression
		Version: 3.4.3
		Author: TinyPNG

	WP-Sweep
		Version: 1.1.8
		Author: Lester 'GaMerZ' Chan


== Elements Usage ==
	
	container : 1
		button : 5
		container : 9
		heading : 4
		icon : 3
		icon-list : 1
		image : 1
		social-icons : 1
		text-editor : 1
	header : 1
		container : 6
		icon : 1
		mega-menu : 1
		nav-menu : 1
		theme-site-logo : 1
	popup : 1
		container : 1
		heading : 1
		nav-menu : 2
		theme-site-logo : 1
	widget : 0
		icon : 2
	wp-page : 3
		call-to-action : 5
		container : 16
		heading : 4
		image : 2
		jet-image-accordion : 2
		template : 3
		text-editor : 1
		theme-page-title : 1
		video : 1
	jet-popup : 2
		container : 2
		heading : 4
		html : 2
		icon : 4


== Settings ==
	
	cpt_support: page, jet-popup
	disable_color_schemes: yes
	disable_typography_schemes: yes
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Active by default
	Additional Custom Breakpoints: Inactive
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active by default
	Upgrade Swiper Library: Active by default
	Grid Container: Active by default
	Nested Elements Performance: Inactive by default
	Optimized Control Loading: Active
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Inactive
	Elementor Home Screen: Active by default
	Editor Top Bar: Active
	Build with AI: Inactive
	Landing Pages: Inactive
	Nested Elements: Active
	Lazy Load Background Images: Active by default
	Pages Panel: Inactive by default
	Display Conditions: Active by default
	Form Submissions: Inactive
	Menu: Active
	Taxonomy Filter: Inactive


== Log ==
	
PHP: showing 6 of 6PHP: 2024-04-20 23:51:33 [notice X 40][/www/wp-content/plugins/elementor/includes/base/controls-stack.php::229] hexdec(): Passing null to parameter #1 ($hex_string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-04-21 03:34:53 [warning X 2][/www/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::179] Undefined array key "editor_post_id" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-04-21 03:37:42 [notice X 1][/www/wp-content/plugins/elementor-pro/modules/screenshots/module.php::33] Function utf8_decode() is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-04-26 23:46:56 [error X 1][/www/wp-content/plugins/elementor-pro/elementor-pro.php::68] Uncaught Error: Failed opening required '/www/wp-content/plugins/elementor-pro/plugin.php' (include_path='.:/usr/share/php') in /www/wp-content/plugins/elementor-pro/elementor-pro.php:68
Stack trace:
#0 /wordpress/wp-includes/class-wp-hook.php(324): elementor_pro_load_plugin('')
#1 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#2 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#3 /wordpress/wp-settings.php(553): do_action('plugins_loaded')
#4 /www/wp-config.php(115): require_once('/wordpress/wp-s...')
#5 /wordpress/wp-config.php(5): require('/www/wp-config....')
#6 /wordpress/wp-load.php(50): require_once('/wordpress/wp-c...')
#7 /wordpress/wp-admin/admin-ajax.php(22): require_once('/wordpress/wp-l...')
#8 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-04-27 05:12:03 [warning X 1][/www/wp-content/plugins/elementor/includes/managers/image.php::113] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-04-27 22:05:43 [warning X 43][/www/wp-content/plugins/elementor/includes/widgets/video.php::1076] Undefined array key "aspect_ratio" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 2 of 2JS: 2024-04-21 01:45:08 [error X 8][/wp-admin/load-scripts.php?c=0&loadchunk_0=jquery-core,jquery-migrate,utils,moxiejs,plupload&ver=6.5.2:2:28760] Cannot read properties of undefined (reading 'value') 
JS: 2024-04-27 23:15:15 [error X 2][/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.21.3:3:821594] Cannot read properties of undefined (reading 'localized') 

Log: showing 10 of 102024-04-26 01:31:44 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.21.1',
  'to' => '3.21.3',
)]
2024-04-26 01:32:23 [info] elementor::elementor_updater Started 
2024-04-26 01:32:23 [info] Elementor/Upgrades - _on_each_version Start  
2024-04-26 01:32:23 [info] Elementor/Upgrades - _on_each_version Finished 
2024-04-26 01:32:23 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.21.1',
  'to' => '3.21.3',
)]
2024-04-26 23:47:09 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.21.0',
  'to' => '3.21.1',
)]
2024-04-26 23:47:13 [info] elementor-pro::elementor_pro_updater Started 
2024-04-26 23:47:13 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-04-26 23:47:13 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-04-26 23:47:13 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.21.0',
  'to' => '3.21.1',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible
	JetTabs For Elementor: Incompatible

== Elementor Pro - Compatibility Tag ==
	
	JetTabs For Elementor: Incompatible
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by T4ngml** [comment]
Just noticed this as well after Elementor plugins update.
Same with standard storefront theme, and most plugins deactivated.
![elementor-bug-yt-300px-wide-only](https://github.com/elementor/elementor/assets/3415579/81dda725-74a4-4e45-bccf-03fb86bdecf9)

**Comment by T4ngml** [comment]
Hi,
Can we have some update on this issue?

I've noticed today that this issue occurs on a local environment, but not on a staging environment, while both share the same code base and parameters.
I've disabled ALL the plugins but Elementor and moved to the storefront theme, on the local environment, and the issue still occurs. 
Comparing the case of a specific video embedded in a lighbox, I've noticed that:
- on the staging environment, the lightbox outputs as **landscape**, which comes with the (expected) 
`--video-aspect-ratio: 1.777; ` parameter (I suppose, retrived from the video setting)
- on the local and live environment, for some reason, it outputs as **portrait**, which comes with the 
`--video-aspect-ratio: null;`  parameter

![compare-outputs](https://github.com/elementor/elementor/assets/3415579/6be5ff40-2d28-4fa2-a195-b042afed18e1)

**Which setting is responsible for adding this CSS class?**

Any help would be greatly appreciated, since our live website is impacted by this issue for over 2 weeks now. 

Thank you.

**Comment by T4ngml** [comment]
Ok, I finally found the guilty setting.
Once Feature > Optimized Control Loading  is set back from Active to Default, the issue doesn't occur anymore.

**Comment by PaulinaJalou** [comment]
Thanks T4ngml for sharing your workaround - have the same issue - when I set Optimized Control Loading from Active back to Default setting the Lightbox it´s working as it should again
