### ISSUE TITLE
History not correctly saved

### ISSUE THREAD

**Issue by wi-kro** [elementor/elementor#27252]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

If you copy-paste an element on a same page, or from a different page, Elementor stop recording history.

### Steps to reproduce

On the blank page
1. Add a container
2. Add Hedling Text
3. Add a button
4. Add Video
5. Copy Video
6. Paste the video e.g. 3 times
7. Add image / or something else
8. Add icon or something else
9. If you now go back using shortcuts or in history, it will take you to point 4 instead of point 8

### Expected behavior

After copying and pasting the item, the history should show each action.

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.6.17
	PHP Version: 8.2.16
	PHP Memory Limit: 768M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.5.3
	Site URL: https://-.com
	Home URL: https://-.com
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 768M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: pl_PL
	Timezone: Europe/Warsaw
	Admin Email: dev@-.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 3.0.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: pl-PL
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36

== Active Plugins ==
	Crocoblock Wizard
		Version: 1.2.12
		Author: Crocoblock

	Duplicator
		Version: 1.5.9
		Author: Duplicator

	Elementor
		Version: 3.21.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.21.2
		Author: Elementor.com

	JetBlocks For Elementor
		Version: 1.3.12
		Author: Crocoblock

	JetElements For Elementor
		Version: 2.6.17.1
		Author: Crocoblock

	JetFormBuilder
		Version: 3.3.3
		Author: Crocoblock

	JetProductGallery
		Version: 2.1.15
		Author: Crocoblock

	WooCommerce
		Version: 8.8.3
		Author: Automattic

	WP-Sweep
		Version: 1.1.8
		Author: Lester 'GaMerZ' Chan

	WP Super Cache
		Version: 1.12.0
		Author: Automattic

	Yoast SEO
		Version: 22.6
		Author: Team Yoast


== Wykorzystanie elementów ==
	
	container : 4
		button : 7
		container : 40
		heading : 19
		html : 1
		icon : 2
		icon-box : 1
		image : 6
		spacer : 7
	header : 2
		container : 8
		heading : 3
		icon : 3
		image : 2
		spacer : 3
	popup : 2
		button : 1
		container : 24
		heading : 28
		icon-box : 1
		spacer : 6
	section : 1
		heading : 3
		spacer : 20
	wp-page : 7
		animated-headline : 1
		button : 18
		container : 228
		heading : 120
		html : 4
		icon : 10
		icon-box : 3
		icon-list : 33
		image : 10
		jet-form-builder-form : 2
		jet-timeline : 4
		menu-anchor : 4
		nested-accordion : 2
		spacer : 18
		template : 4
		toggle : 3
	single-page : 1
		container : 1
		theme-post-content : 1


== Ustawienia ==
	
	cpt_support: post, page, e-landing-page, jet-form-builder
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap
	load_fa4_shim: yes
	meta_generator_tag: 1


== Składniki oferty ==
	Custom Fonts: 0
	Custom Icons: 0

== Integracje ==
	


== Eksperymenty z Elementorem ==
	Ulepszone ładowanie zasobów: Domyślnie aktywne
	Poprawione ładowanie CSS: Domyślnie aktywne
	Czcionka ikon: Domyślnie aktywne
	Dodatkowe niestandardowe punkty zmiany: Domyślnie aktywne
	admin_menu_rearrangement: Domyślnie nieaktywne
	Flexbox Container: Włączono
	Upgrade Swiper Library: Domyślnie aktywne
	Grid Container: Włączono
	Nested Elements Performance: Domyślnie nieaktywne
	Optimized Control Loading: Włączono
	Default to New Theme Builder: Włączono
	Nagłówek i stopka motywu Hello: Domyślnie aktywne
	Elementor Home Screen: Domyślnie aktywne
	Editor Top Bar: Włączono
	Build with AI: Włączono
	Strony docelowe: Domyślnie aktywne
	Elementy zagnieżdżone: Włączono
	Leniwe ładowanie obrazów tła: Nieaktywne
	Pages Panel: Domyślnie nieaktywne
	Wyświetl warunki: Włączono
	Form Submissions: Włączono
	Menu: Włączono
	Taxonomy Filter: Włączono


== Dziennik ==
	
Log: showing 20 of 312024-04-18 13:57:25 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.21.0',
  'to' => '3.21.1',
)]
2024-04-29 08:06:47 [info] elementor::elementor_updater Started 
2024-04-29 08:06:47 [info] Elementor/Upgrades - _on_each_version Start  
2024-04-29 08:06:48 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.21.1',
  'to' => '3.21.3',
)]
2024-04-29 08:06:48 [info] Elementor/Upgrades - _on_each_version Finished 
2024-04-29 08:06:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.21.1',
  'to' => '3.21.3',
)]
2024-04-29 08:06:55 [info] elementor-pro::elementor_pro_updater Started 
2024-04-29 08:06:55 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-04-29 08:06:55 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-04-29 08:06:55 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.21.0',
  'to' => '3.21.1',
)]
2024-05-01 21:54:53 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.21.3',
  'to' => '3.21.4',
)]
2024-05-01 21:54:53 [info] elementor-pro::elementor_pro_updater Started 
2024-05-01 21:54:53 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-05-01 21:54:53 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-05-01 21:54:53 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.21.1',
  'to' => '3.21.2',
)]
2024-05-01 21:54:53 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.21.1',
  'to' => '3.21.2',
)]
2024-05-01 21:54:54 [info] elementor::elementor_updater Started 
2024-05-01 21:54:54 [info] Elementor/Upgrades - _on_each_version Start  
2024-05-01 21:54:54 [info] Elementor/Upgrades - _on_each_version Finished 
2024-05-01 21:54:54 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.21.3',
  'to' => '3.21.4',
)]

JS: showing 5 of 5JS: 2024-04-17 12:15:07 [error X 2][https://-.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.21.0:3:974310] Cannot read properties of undefined (reading &#039;settings&#039;) 
JS: 2024-04-18 15:10:59 [error X 6][https://-.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.21.1:3:654174] Cannot read properties of undefined (reading &#039;isDesignable&#039;) 
JS: 2024-04-28 21:21:59 [error X 4][https://-.com/wp-content/plugins/elementor/assets/js/0e842fae60df2bcb2a30.bundle.min.js:2:7789] Cannot read properties of null (reading &#039;dataset&#039;) 
JS: 2024-04-29 17:06:15 [error X 3][https://-.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.21.3:3:703312] this.model.isValidChild is not a function 
JS: 2024-04-29 17:20:32 [error X 1][https://-.com/wp-includes/js/jquery/jquery.min.js?ver=3.7.1:2:28760] Cannot read properties of undefined (reading &#039;value&#039;) 

PHP: showing 6 of 6PHP: 2024-04-18 14:15:52 [warning X 1][/home/-genics/domains/-.com/public_html/wp-content/plugins/elementor/includes/elements/container.php::1831] Undefined array key &quot;size&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-04-22 20:38:17 [error X 1][/home/-genics/domains/-.com/public_html/wp-content/plugins/elementor/core/wp-api.php::26] Uncaught Error: Call to undefined function Elementor\Core\get_plugins() in /home/-genics/domains/-.com/public_html/wp-content/plugins/elementor/core/wp-api.php:26
Stack trace:
#0 /home/-genics/domains/-.com/public_html/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(96): Elementor\Core\Wp_Api-&gt;get_plugins()
#1 /home/-genics/domains/-.com/public_html/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(58): Elementor\Modules\CompatibilityTag\Base_Module-&gt;get_plugins_with_header()
#2 /home/-genics/domains/-.com/public_html/wp-content/plugins/elementor/modules/compatibility-tag/module.php(57): Elementor\Modules\CompatibilityTag\Base_Module-&gt;get_plugins_to_check()
#3 /home/-genics/domains/-.com/public_html/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(148): Elementor\Modules\CompatibilityTag\Module-&gt;get_plugins_to_check()
#4 /home/-genics/domains/-.com/public_html/wp-includes/class-wp-hook.php(324): Elementor\Modules\CompatibilityTag\Base_Module-&gt;Elementor\Modules\CompatibilityTag\{closure}(&#039;&#039;)
#5 /home/-genics/domains/-.com/public_html/wp-includes/class-wp-hook.php(348): WP_Hook-&gt;apply_filters(&#039;&#039;, Array)
#6 /home/-genics/domains/-.com/public_html/wp-includes/plugin.php(517): WP_Hook-&gt;do_action(Array)
#7 /home/-genics/domains/-.com/public_html/wp-content/plugins/elementor/modules/system-info/module.php(340): do_action(&#039;elementor/syste...&#039;)
#8 /home/-genics/domains/-.com/public_html/wp-content/plugins/elementor/includes/tracker.php(241): Elementor\Modules\System_Info\Module::get_allowed_reports()
#9 /home/-genics/domains/-.com/public_html/wp-content/plugins/elementor/includes/tracker.php(530): Elementor\Tracker::get_system_reports_data()
#10 /home/-genics/domains/-.com/public_html/wp-content/plugins/elementor/includes/tracker.php(141): Elementor\Tracker::get_tracking_data(false)
#11 /home/-genics/domains/-.com/public_html/wp-includes/class-wp-hook.php(324): Elementor\Tracker::send_tracking_data()
#12 /home/-genics/domains/-.com/public_html/wp-includes/class-wp-hook.php(348): WP_Hook-&gt;apply_filters(&#039;&#039;, Array)
#13 /home/-genics/domains/-.com/public_html/wp-includes/plugin.php(565): WP_Hook-&gt;do_action(Array)
#14 /home/-genics/domains/-.com/public_html/wp-cron.php(191): do_action_ref_array(&#039;elementor/track...&#039;, Array)
#15 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-04-29 18:56:02 [notice X 2][/home/-genics/domains/-.com/public_html/wp-content/plugins/elementor-pro/modules/screenshots/module.php::33] Function utf8_decode() is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-04-29 18:58:44 [notice X 60][/home/-genics/domains/-.com/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php::229] hexdec(): Passing null to parameter #1 ($hex_string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-04-30 11:26:53 [warning X 6][/home/-genics/domains/-.com/public_html/wp-content/plugins/elementor/includes/managers/image.php::113] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-05-08 17:47:36 [warning X 6][/home/-genics/domains/-.com/public_html/wp-content/plugins/elementor/modules/ai/connect/ai.php::546] Undefined array key &quot;label&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Kompatybilność nieokreślona
	JetBlocks For Elementor: Kompatybilność nieokreślona
	JetElements For Elementor: Kompatybilność nieokreślona

== Elementor Pro - Compatibility Tag ==
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by wi-kro** [comment]
I noticed that the problem only occurs when the Grid Container function is running!

**Comment by toineenzo** [comment]
This has been fixed in the latest version
