### ISSUE TITLE
Conditional Display with ACF relationship field

### ISSUE THREAD

**Issue by thedesigngroup** [elementor/elementor#27358]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

If you use a relationship field as the display conditional, and a operator of "is empty" or "is not empty", elementor gets the value of the field using the post id, then checks it againts a function that requires the value to be a string, but since it a relationship field, it returns an array. This causes the function to fail.

I have created a screencast here

https://www.loom.com/share/5cc92f5e2682472187f49e2bb4fb5ac0?sid=2eb7ead8-db8a-477c-8fcd-9ce1f6b86318

https://blank.elementor.tdgrepo.com/index.php/2024/05/15/post-3-with-relation/

### Steps to reproduce

create relationship field in ACF and add it the default "post" type
then add it to a post
then create a single post template, adding a section that is display conditionaly
then set it to "Dynamic Tags" then select your custom field slug, then set compare to is empty or is not empty.
then save the template and assign it to all posts.
then vire the post

### Expected behavior

when the field is checked for empty/not empty it should be able to check arrays and strings

if the empty(array) is false then it is not empty
if the empty(array) is true then it is empty

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server - GPL v8.0.37
	PHP Version: 8.1.28
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 20M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.5.3
	Site URL: https://blank.elementor.tdgrepo.com
	Home URL: https://blank.elementor.tdgrepo.com
	WP Multisite: No
	Max Upload Size: 20 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /index.php/%year%/%monthnum%/%day%/%postname%/
	Language: en_US
	Timezone: 0
	Admin Email: chris@thedesigngrouponline.com
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor
	Version: 3.0.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 6.2.10
		Author: WP Engine

	Elementor
		Version: 3.21.5
		Author: Elementor.com

	Elementor Pro
		Version: 3.21.2
		Author: Elementor.com


== Elements Usage ==
	
	wp-post : 4
		container : 1
		heading : 1
	single-post : 1
		container : 6
		heading : 5
		theme-post-content : 1
		theme-post-title : 1


== Settings ==
	
	allow_tracking: yes
	font_display: swap


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Active by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active by default
	Upgrade Swiper Library: Active by default
	Grid Container: Active by default
	Nested Elements Performance: Inactive by default
	Optimized Control Loading: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header &amp; Footer: Active by default
	Elementor Home Screen: Active by default
	Editor Top Bar: Inactive by default
	Build with AI: Active by default
	Landing Pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Active by default
	Display Conditions: Active by default
	Form Submissions: Active by default
	Menu: Inactive by default
	Taxonomy Filter: Active by default


== Log ==
	
PHP: showing 1 of 1PHP: 2024-05-15 15:09:54 [error X 2][/home/elementortdgrepo/blank.elementor.tdgrepo.com/wp-content/plugins/elementor-pro/modules/display-conditions/classes/comparators-checker.php::76] Uncaught TypeError: ElementorPro\Modules\DisplayConditions\Classes\Comparators_Checker::check_string_contains_and_empty(): Argument #3 ($actual_value) must be of type string, array given, called in /home/elementortdgrepo/blank.elementor.tdgrepo.com/wp-content/plugins/elementor-pro/modules/display-conditions/conditions/dynamic-tags-condition.php on line 54 and defined in /home/elementortdgrepo/blank.elementor.tdgrepo.com/wp-content/plugins/elementor-pro/modules/display-conditions/classes/comparators-checker.php:76
Stack trace:
#0 /home/elementortdgrepo/blank.elementor.tdgrepo.com/wp-content/plugins/elementor-pro/modules/display-conditions/conditions/dynamic-tags-condition.php(54): ElementorPro\Modules\DisplayConditions\Classes\Comparators_Checker::check_string_contains_and_empty(&#039;is_not_empty&#039;, &#039;&#039;, Array)
#1 /home/elementortdgrepo/blank.elementor.tdgrepo.com/wp-content/plugins/elementor-pro/modules/display-conditions/classes/and-condition.php(38): ElementorPro\Modules\DisplayConditions\Conditions\Dynamic_Tags_Condition-&gt;check(Array)
#2 /home/elementortdgrepo/blank.elementor.tdgrepo.com/wp-content/plugins/elementor-pro/modules/display-conditions/classes/and-condition.php(24): ElementorPro\Modules\DisplayConditions\Classes\And_Condition-&gt;is_condition_passing_check(Array)
#3 /home/elementortdgrepo/blank.elementor.tdgrepo.com/wp-content/plugins/elementor-pro/modules/display-conditions/classes/or-condition.php(27): ElementorPro\Modules\DisplayConditions\Classes\And_Condition-&gt;check()
#4 /home/elementortdgrepo/blank.elementor.tdgrepo.com/wp-content/plugins/elementor-pro/modules/display-conditions/module.php(188): ElementorPro\Modules\DisplayConditions\Classes\Or_Condition-&gt;check()
#5 /home/elementortdgrepo/blank.elementor.tdgrepo.com/wp-includes/class-wp-hook.php(324): ElementorPro\Modules\DisplayConditions\Module-&gt;before_element_render(Object(Elementor\Includes\Elements\Container))
#6 /home/elementortdgrepo/blank.elementor.tdgrepo.com/wp-includes/class-wp-hook.php(348): WP_Hook-&gt;apply_filters(&#039;&#039;, Array)
#7 /home/elementortdgrepo/blank.elementor.tdgrepo.com/wp-includes/plugin.php(517): WP_Hook-&gt;do_action(Array)
#8 /home/elementortdgrepo/blank.elementor.tdgrepo.com/wp-content/plugins/elementor/includes/base/element-base.php(455): do_action(&#039;elementor/front...&#039;, Object(Elementor\Includes\Elements\Container))
#9 /home/elementortdgrepo/blank.elementor.tdgrepo.com/wp-content/plugins/elementor/core/base/document.php(1795): Elementor\Element_Base-&gt;print_element()
#10 /home/elementortdgrepo/blank.elementor.tdgrepo.com/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(412): Elementor\Core\Base\Document-&gt;print_elements(Array)
#11 /home/elementortdgrepo/blank.elementor.tdgrepo.com/wp-content/plugins/elementor/includes/frontend.php(1157): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document-&gt;print_elements_with_wrapper(Array)
#12 /home/elementortdgrepo/blank.elementor.tdgrepo.com/wp-content/plugins/elementor/core/base/document.php(1231): Elementor\Frontend-&gt;get_builder_content(42, false)
#13 /home/elementortdgrepo/blank.elementor.tdgrepo.com/wp-content/plugins/elementor/modules/library/documents/library-document.php(76): Elementor\Core\Base\Document-&gt;get_content(false)
#14 /home/elementortdgrepo/blank.elementor.tdgrepo.com/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(158): Elementor\Modules\Library\Documents\Library_Document-&gt;get_content(false)
#15 /home/elementortdgrepo/blank.elementor.tdgrepo.com/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(173): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document-&gt;get_content()
#16 /home/elementortdgrepo/blank.elementor.tdgrepo.com/wp-content/plugins/elementor-pro/modules/theme-builder/documents/single-base.php(93): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document-&gt;print_content()
#17 /home/elementortdgrepo/blank.elementor.tdgrepo.com/wp-content/plugins/elementor-pro/modules/theme-builder/classes/locations-manager.php(364): ElementorPro\Modules\ThemeBuilder\Documents\Single_Base-&gt;print_content()
#18 /home/elementortdgrepo/blank.elementor.tdgrepo.com/wp-content/plugins/elementor-pro/modules/theme-builder/api.php(13): ElementorPro\Modules\ThemeBuilder\Classes\Locations_Manager-&gt;do_location(&#039;single&#039;)
#19 /home/elementortdgrepo/blank.elementor.tdgrepo.com/wp-content/themes/hello-elementor/index.php(20): elementor_theme_do_location(&#039;single&#039;)
#20 /home/elementortdgrepo/blank.elementor.tdgrepo.com/wp-includes/template-loader.php(106): include(&#039;/home/elementor...&#039;)
#21 /home/elementortdgrepo/blank.elementor.tdgrepo.com/wp-blog-header.php(19): require_once(&#039;/home/elementor...&#039;)
#22 /home/elementortdgrepo/blank.elementor.tdgrepo.com/index.php(17): require(&#039;/home/elementor...&#039;)
#23 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by smarttecsamuel** [comment]
+1 This caused a fatal error for me awell. If we are able to select relationship fields in dynamic tags they should work and not produce an error.

**Comment by magesticmojo** [comment]
+1 Same problem here. This is an important feature for me, please fix

**Comment by RuNThomasRichter** [comment]
+1 Same problem. Condition works with a text field (empty / not empty), checkbox or relation array field keeps the page crashing. ( using Current Elementor Pro, ACF and Wordpress)

**Comment by anisurrahman99** [comment]
+1 same problem here. Please fix this issue.

**Comment by joelbutaoadansw** [comment]
+1 same problem here. Please fix this issue.

**Comment by chris-jut-so** [comment]
+1 same issue. Please fix.

**Comment by jordan-webdev** [comment]
+1 for the ACF gallery field too. I guess it's just for any field that would produce an array since it checks for a single string.

**Comment by magesticmojo** [comment]
So frustrating no one is working on this. Elementor PRO is a paid plugin :-(

**Comment by yodyk** [comment]
Critical Error here as well. Tried a number of trial-and-error function codes and still no workarounds

**Comment by annacolomar** [comment]
I've been having a similar / almost identical issue with Elementor and ACF since the last upload. 
As other users already stated, the problem mainly came when "is empty" are "is not empty" were evaluating something other that wasn't a true/false field or statement.

Here's the code snippet that worked for me. 
I had a custom plugin where I added my custom functions for the project, I created this file and then included it in the main plugin file. Guess it might work similarly if you add it in your theme's functions.php.

Hope this helps! ✨

`<?php
// Prevent direct access.
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

add_action( 'elementor/init', function() {
    add_action( 'elementor/dynamic_tags/register', function( $dynamic_tags ) {
        // Ensure the Elementor dynamic tag class exists.
        if ( ! class_exists( '\Elementor\Core\DynamicTags\Tag' ) ) {
            return;
        }
        
        // Only declare the class if it hasn't been declared already.
        if ( ! class_exists( 'ACF_Text_Boolean_Dynamic_Tag' ) ) {
            class ACF_Text_Boolean_Dynamic_Tag extends \Elementor\Core\DynamicTags\Tag {

                public function get_name() {
                    return 'acf_text_boolean';
                }
                
                public function get_title() {
                    return __( 'ACF Text (Boolean)', 'plugin-name' );
                }
                
                // Instead of using the undefined constant, return a hardcoded group name.
                public function get_group() {
                    return 'text';
                }
                
                // Similarly, return a hardcoded category.
                public function get_categories() {
                    return [ 'text' ];
                }
                
                protected function register_controls() {
                    $this->add_control(
                        'field_key',
                        [
                            'label'       => __( 'ACF Field Key', 'plugin-name' ),
                            'type'        => \Elementor\Controls_Manager::TEXT,
                            'placeholder' => __( 'Enter the ACF field key', 'plugin-name' ),
                        ]
                    );
                }
                
                public function render() {
                    $field_key = $this->get_settings( 'field_key' );
                    
                    // Determine the current post ID.
                    $post_id = get_the_ID();
                    if ( empty( $post_id ) && function_exists( 'get_queried_object_id' ) ) {
                        $post_id = get_queried_object_id();
                    }
                    
                    if ( empty( $field_key ) ) {
                        echo '';
                        return;
                    }
                    
                    // Retrieve the ACF field value.
                    $field_value = get_field( $field_key, $post_id );
                    
                    // If a valid field value is found (or '0' is valid), output "1" (truthy); otherwise, output an empty string.
                    if ( $field_value !== null && $field_value !== '' ) {
                        echo '1';
                    } else {
                        echo '';
                    }
                }
            }
        }
        
        // Register the new dynamic tag.
        $dynamic_tags->register_tag( 'ACF_Text_Boolean_Dynamic_Tag' );
    });
});
`


Don't forget to include it in your own plugin if you need to:
include_once plugin_dir_path( __FILE__ ) . 'acf-text-boolean-tag.php';

**Comment by demijan-ha** [comment]
+1 Don't get how is this not fixed after almost a year.

**Comment by DimaMinka** [comment]
+1 :(
same issue. any news @elementor???
