### ISSUE TITLE
⛔ WordPress Menu Widget Hover Not Working Correctly on Frontend

### ISSUE THREAD

**Issue by ricardoaraujo330** [elementor/elementor#27672]
### Prerequisites

- [ ] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Hello Elementor Team,

I'm experiencing an issue with the WordPress menu widget using the Hello Elementor theme. The hover effect works correctly in the Elementor editor, but on the frontend, the menu color doesn't change on hover. I've inspected the CSS while activating hover, and it appears that there is no CSS related to the hover action on the a.elementor-item.

### Steps to reproduce

1. Create a menu using the WordPress menu widget.
2. Set a hover color in the Elementor editor.
3. Save and view the frontend.

### Expected behavior

1. The menu color should change on hover in the frontend as it does in the editor.

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt

== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.59 (Debian)
	MySQL version: mariadb.org binary distribution v10.4.34
	PHP Version: 7.4.33
	PHP Memory Limit: 900M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 250M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.5.4
	Site URL: https://wordpress-1090615-3846767.cloudwaysapps.com
	Home URL: https://wordpress-1090615-3846767.cloudwaysapps.com
	WP Multisite: No
	Max Upload Size: 200 MB
	Memory limit: 900M
	Max Memory limit: 900M
	Permalink Structure: /blog/%postname%/
	Language: pt_PT
	Timezone: Europe/Lisbon
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor Child
	Version: 2.0.0
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 3.0.2
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: pt-PT
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36

== Active Plugins ==
	Admin and Site Enhancements (ASE)
		Version: 7.0.3
		Author: wpase.com

	Admin Menu Editor Pro
		Version: 2.24.3
		Author: Janis Elsts

	Elementor
		Version: 3.21.8
		Author: Elementor.com

	Elementor Pro
		Version: 3.21.3
		Author: Elementor.com

	Invoicing with InvoiceXpress for WooCommerce - Pro
		Version: 5.6
		Author: PT Woo Plugins (by Webdados)

	JetBlog For Elementor
		Version: 2.3.7.1
		Author: Crocoblock

	JetElements For Elementor
		Version: 2.6.18
		Author: Crocoblock

	JetEngine
		Version: 3.4.6
		Author: Crocoblock

	JetProductGallery
		Version: 2.1.16
		Author: Crocoblock

	JetSmartFilters
		Version: 3.4.5
		Author: Crocoblock

	JetTabs For Elementor
		Version: 2.2.3
		Author: Crocoblock

	JetWooBuilder - Products Grid Load More
		Version: 1.2.0
		Author: Crocoblock

	JetWooBuilder For Elementor
		Version: 2.1.12
		Author: Crocoblock

	Multibanco, MB WAY, Credit card, Payshop and Cofidis Pay (IfthenPay) for WooCommerce
		Version: 9.4.0
		Author: PT Woo Plugins (by Webdados)

	Order Delivery Date Pro for WooCommerce
		Version: 10.13.0
		Author: Tyche Softwares

	Portuguese Postcodes for WooCommerce
		Version: 4.1
		Author: PT Woo Plugins (by Webdados)

	Smash Balloon Instagram Feed
		Version: 6.4.1
		Author: Smash Balloon

	Stock Dependencies for WooCommerce
		Version: 1.6.2
		Author: Kevin McCall

	Variation Swatches for WooCommerce
		Version: 2.1.0
		Author: Emran Ahmed

	Variation Swatches for WooCommerce - Pro
		Version: 2.1.2
		Author: Emran Ahmed

	WooCommerce
		Version: 8.9.3
		Author: Automattic

	WooCommerce Email Customizer
		Version: 3.33
		Author: cxThemes

	WooCommerce Sequential Order Numbers Pro
		Version: 1.21.2
		Author: SkyVerge

	WooCommerce Shipment Tracking
		Version: 2.4.8
		Author: WooCommerce

	WooCommerce Smart Coupons
		Version: 9.1.0
		Author: StoreApps

	WooCommerce Stripe Gateway
		Version: 8.3.1
		Author: WooCommerce

	WooCommerce Subscriptions
		Version: 6.3.2
		Author: WooCommerce

	WooCommerce Waitlist
		Version: 2.4.11
		Author: Neil Pie

	Woo Conditional Shipping and Payments
		Version: 1.15.11
		Author: Woo

	WP Mail SMTP Pro
		Version: 4.0.2
		Author: WP Mail SMTP

	YITH WooCommerce Product Add-ons &amp; Extra Options Premium
		Version: 4.13.0
		Author: YITH

	Yoast Duplicate Post
		Version: 4.5
		Author: Enrico Battocchi & Team Yoast


== Features ==
	Custom Fonts: 3
	Custom Icons: 2

== Integrations ==
	
	google_maps: Active
	recaptcha: Active
	recaptcha_v3: Active
	woocommerce: Active


== Elementor Experiments ==
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Additional Custom Breakpoints: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Atualizar Biblioteca Swiper.: Active
	Grid Container: Active
	Nested Elements Performance: Inactive by default
	Optimized Control Loading: Active
	Default to New Theme Builder: Active
	Tema Hello - Cabeçalho &amp; Rodapé: Active by default
	Elementor Home Screen: Active by default
	Editor Top Bar: Active
	Build with AI: Active
	Landing Pages: Active
	Nested Elements: Active
	Lazy Load Background Images: Active
	Pages Panel: Inactive by default
	Display Conditions: Active
	Form Submissions: Inactive
	Menu: Active
	Taxonomy Filter: Active


== Log ==
	
JS: showing 20 of 28JS: 2024-06-06 15:52:58 [error X 1][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view22433&quot;) has already been destroyed and cannot be used. 
JS: 2024-06-06 15:52:58 [error X 1][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view22470&quot;) has already been destroyed and cannot be used. 
JS: 2024-06-06 20:37:10 [error X 1][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view39188&quot;) has already been destroyed and cannot be used. 
JS: 2024-06-07 10:40:37 [error X 3][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.21.8:3:937754] elementorFrontend is not defined 
JS: 2024-06-07 21:59:56 [error X 1][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view25199&quot;) has already been destroyed and cannot be used. 
JS: 2024-06-07 21:59:56 [error X 1][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view25125&quot;) has already been destroyed and cannot be used. 
JS: 2024-06-07 22:25:05 [error X 1][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view87291&quot;) has already been destroyed and cannot be used. 
JS: 2024-06-07 22:25:06 [error X 1][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view87254&quot;) has already been destroyed and cannot be used. 
JS: 2024-06-08 14:19:18 [error X 1][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view5740&quot;) has already been destroyed and cannot be used. 
JS: 2024-06-08 17:48:32 [error X 1][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view85966&quot;) has already been destroyed and cannot be used. 
JS: 2024-06-08 17:48:33 [error X 1][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view85929&quot;) has already been destroyed and cannot be used. 
JS: 2024-06-08 19:43:24 [error X 1][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view137917&quot;) has already been destroyed and cannot be used. 
JS: 2024-06-08 19:47:42 [error X 1][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view165066&quot;) has already been destroyed and cannot be used. 
JS: 2024-06-08 19:47:45 [error X 1][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view169419&quot;) has already been destroyed and cannot be used. 
JS: 2024-06-08 21:39:00 [error X 1][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view204923&quot;) has already been destroyed and cannot be used. 
JS: 2024-06-08 21:39:00 [error X 1][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view204960&quot;) has already been destroyed and cannot be used. 
JS: 2024-06-10 09:37:29 [error X 2][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.21.8:3:54583] Cannot read properties of undefined (reading &#039;activate&#039;) 
JS: 2024-06-10 14:06:03 [error X 48][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.21.8:3:821087] Cannot read properties of undefined (reading &#039;toLowerCase&#039;) 
JS: 2024-06-11 21:42:52 [error X 314][../wp-content/uploads/essential-addons-elementor/eael.js?ver=1718143107:28:489022] Cannot read properties of undefined (reading &#039;size&#039;) 
JS: 2024-06-11 22:02:13 [error X 32][../wp-content/plugins/instagram-feed/admin/assets/js/callout.js:26:60] Cannot read properties of null (reading &#039;addEventListener&#039;) 

PHP: showing 8 of 8PHP: 2024-05-24 12:12:26 [notice X 1][../wp-content/plugins/elementor-pro/modules/loop-filter/module.php::155] Undefined index: post_type [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-05-24 12:13:01 [error X 1][../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::200] Uncaught Error: Class &#039;\ElementorPro\Modules\ThemeBuilder\Conditions\By_author&#039; not found in ../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:200
Stack trace:
#0 ../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(211): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;register_condition()
#1 ../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(211): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;register_condition()
#2 ../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(282): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;register_condition()
#3 ../wp-includes/clas [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-05-24 17:30:15 [notice X 418][../wp-content/plugins/elementor-pro/modules/dynamic-tags/tags/site-logo.php::32] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-06-04 14:51:18 [notice X 24][../wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/fonts-manager.php::252] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-06-04 23:42:10 [notice X 27][../wp-content/plugins/elementor/includes/conditions.php::87] Undefined index: background_color_b [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-06-07 08:18:19 [error X 1][../wp-content/plugins/elementor-pro/modules/forms/registrars/form-actions-registrar.php::57] Uncaught Error: Class &#039;ElementorPro\Modules\Forms\Actions\Discord&#039; not found in ../wp-content/plugins/elementor-pro/modules/forms/registrars/form-actions-registrar.php:57
Stack trace:
#0 ../wp-includes/class-wp-hook.php(324): ElementorPro\Modules\Forms\Registrars\Form_Actions_Registrar-&gt;ElementorPro\Modules\Forms\Registrars\{closure}()
#1 ../wp-includes/class-wp-hook.php(348): WP_Hook-&gt;apply_filters()
#2 ../wp-includes/plugin.php(517): WP_Hook-&gt;do_action()
#3 ../wp-content/plugins/elementor-pro/modules/forms/registrars/form-actions-registrar.php(84): do_action()
#4 ../wp-content/plugins/elementor-pro/modules/forms/registrars/form-actions-registrar.php(42): ElementorPro\Modules\Forms\Registrars\Form_Acti [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-06-10 00:46:09 [error X 2][../wp-content/plugins/elementor/includes/managers/elements.php::71] Uncaught TypeError: Argument 1 passed to Elementor\Elements_Manager::create_element_instance() must be of the type array, bool given, called in ../wp-content/plugins/jupiterx-core/includes/extensions/raven/includes/modules/product-gallery/module.php on line 111 and defined in ../wp-content/plugins/elementor/includes/managers/elements.php:71
Stack trace:
#0 ../wp-content/plugins/jupiterx-core/includes/extensions/raven/includes/modules/product-gallery/module.php(111): Elementor\Elements_Manager-&gt;create_element_instance()
#1 ../wp-includes/class-wp-hook.php(324): JupiterX_Core\Raven\Modules\Product_Gallery\Module-&gt;get_gallery_items()
#2 ../wp-includes/class-wp-hook.php(348): WP_Hook-&gt;apply_filters()
#3 ../ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-06-10 11:03:58 [notice X 6][../wp-content/plugins/elementor/includes/conditions.php::87] Undefined index: mailerlite_list [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 6 of 62024-05-28 08:03:04 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.21.7',
  'to' => '3.21.8',
)]
2024-05-29 18:26:51 [info] elementor::elementor_updater Started 
2024-05-29 18:26:51 [info] Elementor/Upgrades - _on_each_version Start  
2024-05-29 18:26:51 [info] Elementor/Upgrades - _on_each_version Finished 
2024-05-29 18:26:51 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.21.7',
  'to' => '3.21.8',
)]
2024-05-29 18:26:52 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.21.7',
  'to' => '3.21.8',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	JetBlog For Elementor: Compatibility not specified
	JetElements For Elementor: Compatibility not specified
	JetTabs For Elementor: Compatibility not specified
	JetWooBuilder For Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by ricardoaraujo330** [comment]
After some testes, noticed that it is the "normal" color that is overlaying the hover color, and it shouldn't, since the widget allows customizing the normal, hover and active status. 

The only workaround is custom css, but i think you should fix this small issue.

Thank you

**Comment by nicholaszein** [comment]
Hello @ricardoaraujo330,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
We tested the WordPress Menu widget using all pointer options following your steps to reproduce, with only Elementor, Elementor Pro, WooCommerce and the Hello Elementor theme installed, and we could not reproduce your issue. The widget is working as expected.

https://github.com/user-attachments/assets/c7b648be-707e-4777-b283-82874210547d

It is likely your issue is related to cache or a conflict with one of your many plugins, some of which are Elementor addons. We also noticed you've been using the JupiterX theme and companion plugin, and this can also directly affect the styles of the menu items in the widget.


### ✅ What you can do to solve your issue:
Make sure you have cleared, purged and flushed all levels of cache on your site, and that you have isolated the problem as required in the Bug Report form by deactivating all plugins to exclude potential conflicts.

This is also the type of problem more suited to be handled by Elementor Support. Please consider reaching out to Elementor Support before submitting an issue.

### 👍 For now, that's all we can help with.

### ⚠️ Note that GitHub issues are reserved for troubleshooted and validated Elementor 🐞 Bug Reports only, and should not be used for personal support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
