### ISSUE TITLE
`wp_enqueue_media()` leads to a fatal error `Call to a member function get_component() on null`

### ISSUE THREAD

**Issue by matzeeable** [elementor/elementor#27693]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

When using [`wp_enqueue_media()`](https://developer.wordpress.org/reference/functions/wp_enqueue_media/) the Elementor page builder does no longer load:

![image](https://github.com/elementor/elementor/assets/1008534/a2afb86e-d099-4ceb-b9f8-5349c4e8a182)

```
Uncaught Error: Call to a member function get_component() on null in /var/www/html/wp-content/plugins/elementor/modules/ai/module.php:442
Stack trace:
#0 /var/www/html/wp-content/plugins/elementor/modules/ai/module.php(301): Elementor\Modules\Ai\Module->get_ai_app()
#1 /var/www/html/wp-content/plugins/elementor/modules/ai/module.php(182): Elementor\Modules\Ai\Module->get_ai_connect_url()
#2 /var/www/html/wp-includes/class-wp-hook.php(324): Elementor\Modules\Ai\Module->enqueue_ai_media_library('')
#3 /var/www/html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#4 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#5 /var/www/html/wp-includes/media.php(4957): do_action('wp_enqueue_medi...')
#6 /var/www/html/wp-content/plugins/real-media-library/inc/Assets.php(112): wp_enqueue_media(Array)
#7 /var/www/html/wp-content/wordpress-packages/utils/src/Assets.php(686): MatthiasWeb\RealMediaLibrary\Assets->enqueue_scripts_and_styles('wp_enqueue_scri...')
#8 /var/www/html/wp-includes/class-wp-hook.php(324): MatthiasWeb\RealMediaLibrary\Assets->wp_enqueue_scripts('')
#9 /var/www/html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#10 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#11 /var/www/html/wp-includes/script-loader.php(2265): do_action('wp_enqueue_scri...')
#12 /var/www/html/wp-includes/class-wp-hook.php(324): wp_enqueue_scripts('')
#13 /var/www/html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#14 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#15 /var/www/html/wp-includes/general-template.php(3050): do_action('wp_head')
#16 /var/www/html/wp-includes/template-canvas.php(17): wp_head()
#17 /var/www/html/wp-includes/template-loader.php(106): include('/var/www/html/w...')
#18 /var/www/html/wp-blog-header.php(19): require_once('/var/www/html/w...')
#19 /var/www/html/index.php(17): require('/var/www/html/w...')
#20 {main}
  thrown
```

### Steps to reproduce

1. Install Elementor free version
2. Install the plugin "Real Media Library" in free version
3. Create an Elementor page
4. You cannot edit it

But this also happens with Elementor-only active when using [`wp_enqueue_media()`](https://developer.wordpress.org/reference/functions/wp_enqueue_media/).

### Expected behavior

Allow to edit the pages

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.59 (Debian)
	MySQL version: MySQL Community Server - GPL v8.0.21
	PHP Version: 8.2.19
	PHP Memory Limit: 256M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.5.4
	Site URL: https://my.local
	Home URL: https://my.local
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%postname%/
	Language: en_US
	Timezone: 0
	Admin Email: admin@test.com
	Debug Mode: Active

== Theme ==
	Name: Twenty Twenty-Four
	Version: 1.1
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.22.0
		Author: Elementor.com

	Real Media Library
		Version: 4.22.16
		Author: devowl.io


== Elementor Experiments ==
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Active by default
	Additional Custom Breakpoints: Active by default
	Flexbox Container: Active by default
	Grid Container: Active by default
	Upgrade Swiper Library: Active by default
	Nested Elements Performance: Inactive by default
	Optimized Control Loading: Active by default
	Optimized Markup: Inactive by default
	Plugin Onboarding: Active by default
	Elementor Home Screen: Active by default
	Editor Top Bar: Inactive by default
	Build with AI: Active by default
	Landing Pages: Inactive by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Active by default
	Element Caching: Inactive by default
	Conversion Center: Inactive by default


== Log ==
	
PHP: showing 1 of 1PHP: 2024-06-17 06:39:53 [error X 7][/var/www/html/wp-content/plugins/elementor/modules/ai/module.php::442] Uncaught Error: Call to a member function get_component() on null in /var/www/html/wp-content/plugins/elementor/modules/ai/module.php:442
Stack trace:
#0 /var/www/html/wp-content/plugins/elementor/modules/ai/module.php(301): Elementor\Modules\Ai\Module->get_ai_app()
#1 /var/www/html/wp-content/plugins/elementor/modules/ai/module.php(182): Elementor\Modules\Ai\Module->get_ai_connect_url()
#2 /var/www/html/wp-includes/class-wp-hook.php(324): Elementor\Modules\Ai\Module->enqueue_ai_media_library('')
#3 /var/www/html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#4 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#5 /var/www/html/wp-includes/media.php(4957): do_action('wp_enqueue_medi...')
#6 /var/www/html/wp-content/plugins/real-media-library/inc/Assets.php(112): wp_enqueue_media(Array)
#7 /var/www/html/wp-content/wordpress-packages/utils/src/Assets.php(686): MatthiasWeb\RealMediaLibrary\Assets->enqueue_scripts_and_styles('wp_enqueue_scri...')
#8 /var/www/html/wp-includes/class-wp-hook.php(324): MatthiasWeb\RealMediaLibrary\Assets->wp_enqueue_scripts('')
#9 /var/www/html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#10 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#11 /var/www/html/wp-includes/script-loader.php(2265): do_action('wp_enqueue_scri...')
#12 /var/www/html/wp-includes/class-wp-hook.php(324): wp_enqueue_scripts('')
#13 /var/www/html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#14 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#15 /var/www/html/wp-includes/general-template.php(3050): do_action('wp_head')
#16 /var/www/html/wp-includes/template-canvas.php(17): wp_head()
#17 /var/www/html/wp-includes/template-loader.php(106): include('/var/www/html/w...')
#18 /var/www/html/wp-blog-header.php(19): require_once('/var/www/html/w...')
#19 /var/www/html/index.php(17): require('/var/www/html/w...')
#20 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
This issue was solved with the release of Elementor v3.22.1.
