### ISSUE TITLE
Loop Carousel Widget Bug: Slides Displayed Incorrectly

### ISSUE THREAD

**Issue by ricardoaraujo330** [elementor/elementor#27760]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

I am experiencing an issue with the Loop Carousel widget in Elementor Pro. I have configured the widget to display 1 slide at a time and to scroll 1 slide with each scroll. I set the total number of slides to 6. However, instead of displaying the slides as a carousel, all 6 slides are being displayed stacked on top of each other.
<img width="1566" alt="Screenshot at Jun 20 16-02-26" src="https://github.com/elementor/elementor/assets/29624839/ed541986-1c63-4a76-b932-a2ee1e04f14e">

### Steps to reproduce

Add the Loop Carousel widget to a page.
Set the total number of slides to 6.
Configure the widget to display 1 slide at a time and to scroll 1 slide with each scroll.
View the page and observe the stacking of slides.
<img width="537" alt="Screenshot at Jun 20 16-03-53" src="https://github.com/elementor/elementor/assets/29624839/864bbfbd-8417-4db0-abbe-e0abe717da6e">

### Expected behavior

The expected behavior is for the Loop Carousel to display 1 slide at a time and to scroll 1 slide with each scroll, smoothly transitioning between the slides in a horizontal carousel format.

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.59 (Debian)
	MySQL version: mariadb.org binary distribution v10.4.34
	PHP Version: 7.4.33
	PHP Memory Limit: 900M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 250M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.5.4
	Site URL: https://wordpress-1090615-3846767.cloudwaysapps.com
	Home URL: https://wordpress-1090615-3846767.cloudwaysapps.com
	WP Multisite: No
	Max Upload Size: 200 MB
	Memory limit: 900M
	Max Memory limit: 900M
	Permalink Structure: /blog/%postname%/
	Language: pt_PT
	Timezone: Europe/Lisbon
	Admin Email: ola@floresnocais.pt
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor Child
	Version: 2.0.0
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 3.0.2
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: pt-PT
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36

== Active Plugins ==
	Admin and Site Enhancements (ASE) Pro
		Version: 7.0.3
		Author: wpase.com

	Admin Menu Editor Pro
		Version: 2.24.3
		Author: Janis Elsts

	Elementor
		Version: 3.22.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.22.0
		Author: Elementor.com

	Invoicing with InvoiceXpress for WooCommerce - Pro
		Version: 5.6
		Author: PT Woo Plugins (by Webdados)

	JetBlog For Elementor
		Version: 2.3.7.1
		Author: Crocoblock

	JetElements For Elementor
		Version: 2.6.18
		Author: Crocoblock

	JetEngine
		Version: 3.4.6
		Author: Crocoblock

	JetFormBuilder
		Version: 3.3.4.1
		Author: Crocoblock

	JetFormBuilder User Login Action
		Version: 2.0.4
		Author: Crocoblock

	JetProductGallery
		Version: 2.1.16
		Author: Crocoblock

	JetSmartFilters
		Version: 3.5.0
		Author: Crocoblock

	JetTabs For Elementor
		Version: 2.2.3
		Author: Crocoblock

	JetWooBuilder - Products Grid Load More
		Version: 1.2.0
		Author: Crocoblock

	JetWooBuilder For Elementor
		Version: 2.1.12
		Author: Crocoblock

	Multibanco, MB WAY, Credit card, Payshop and Cofidis Pay (IfthenPay) for WooCommerce
		Version: 9.4.0
		Author: PT Woo Plugins (by Webdados)

	Order Delivery Date Pro for WooCommerce
		Version: 10.13.0
		Author: Tyche Softwares

	Portuguese Postcodes for WooCommerce
		Version: 4.1
		Author: PT Woo Plugins (by Webdados)

	Refer a Friend for WooCommerce PREMIUM
		Version: 4.1.0
		Author: WPGens

	Variation Swatches for WooCommerce
		Version: 2.1.0
		Author: Emran Ahmed

	Variation Swatches for WooCommerce - Pro
		Version: 2.1.3
		Author: Emran Ahmed

	WooCommerce
		Version: 8.9.3
		Author: Automattic

	WooCommerce Email Customizer
		Version: 3.33
		Author: cxThemes

	WooCommerce Sequential Order Numbers Pro
		Version: 1.21.2
		Author: SkyVerge

	WooCommerce Shipment Tracking
		Version: 2.4.8
		Author: WooCommerce

	WooCommerce Smart Coupons
		Version: 9.1.0
		Author: StoreApps

	WooCommerce Stripe Gateway
		Version: 8.4.0
		Author: WooCommerce

	WooCommerce Subscriptions
		Version: 6.4.0
		Author: WooCommerce

	WooCommerce Waitlist
		Version: 2.4.11
		Author: Neil Pie

	Woo Conditional Shipping and Payments
		Version: 1.15.11
		Author: Woo

	WP Mail SMTP Pro
		Version: 4.0.2
		Author: WP Mail SMTP

	YITH WooCommerce Product Add-ons &amp; Extra Options Premium
		Version: 4.13.0
		Author: YITH

	Yoast Duplicate Post
		Version: 4.5
		Author: Enrico Battocchi & Team Yoast


== Features ==
	Custom Fonts: 3
	Custom Icons: 2

== Integrations ==
	
	google_maps: Active
	recaptcha: Active
	recaptcha_v3: Active
	woocommerce: Active


== Elementor Experiments ==
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Additional Custom Breakpoints: Active
	Flexbox Container: Active
	Grid Container: Active
	Atualizar Biblioteca Swiper.: Active
	Nested Elements Performance: Inactive by default
	Optimized Control Loading: Active
	Optimized Markup: Inactive by default
	Plugin Onboarding: Active by default
	Default to New Theme Builder: Active
	Tema Hello - Cabeçalho &amp; Rodapé: Active by default
	Elementor Home Screen: Active by default
	Editor Top Bar: Active
	Build with AI: Active
	Landing Pages: Active
	Nested Elements: Active
	Lazy Load Background Images: Active
	Pages Panel: Inactive by default
	Element Caching: Inactive by default
	Conversion Center: Inactive by default
	Display Conditions: Active
	Form Submissions: Inactive
	Menu: Active
	Taxonomy Filter: Active


== Log ==
	
JS: showing 20 of 26JS: 2024-06-07 22:25:05 [error X 1][https://wordpress-1090615-3846767.cloudwaysapps.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view87291&quot;) has already been destroyed and cannot be used. 
JS: 2024-06-07 22:25:06 [error X 1][https://wordpress-1090615-3846767.cloudwaysapps.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view87254&quot;) has already been destroyed and cannot be used. 
JS: 2024-06-08 14:19:18 [error X 1][https://wordpress-1090615-3846767.cloudwaysapps.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view5740&quot;) has already been destroyed and cannot be used. 
JS: 2024-06-08 17:48:32 [error X 1][https://wordpress-1090615-3846767.cloudwaysapps.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view85966&quot;) has already been destroyed and cannot be used. 
JS: 2024-06-08 17:48:33 [error X 1][https://wordpress-1090615-3846767.cloudwaysapps.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view85929&quot;) has already been destroyed and cannot be used. 
JS: 2024-06-08 19:43:24 [error X 1][https://wordpress-1090615-3846767.cloudwaysapps.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view137917&quot;) has already been destroyed and cannot be used. 
JS: 2024-06-08 19:47:42 [error X 1][https://wordpress-1090615-3846767.cloudwaysapps.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view165066&quot;) has already been destroyed and cannot be used. 
JS: 2024-06-08 19:47:45 [error X 1][https://wordpress-1090615-3846767.cloudwaysapps.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view169419&quot;) has already been destroyed and cannot be used. 
JS: 2024-06-08 21:39:00 [error X 1][https://wordpress-1090615-3846767.cloudwaysapps.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view204923&quot;) has already been destroyed and cannot be used. 
JS: 2024-06-08 21:39:00 [error X 1][https://wordpress-1090615-3846767.cloudwaysapps.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view204960&quot;) has already been destroyed and cannot be used. 
JS: 2024-06-10 09:37:29 [error X 3][https://wordpress-1090615-3846767.cloudwaysapps.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.21.8:3:54583] Cannot read properties of undefined (reading &#039;activate&#039;) 
JS: 2024-06-10 14:06:03 [error X 49][https://wordpress-1090615-3846767.cloudwaysapps.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.21.8:3:821087] Cannot read properties of undefined (reading &#039;toLowerCase&#039;) 
JS: 2024-06-11 21:42:52 [error X 314][https://wordpress-1090615-3846767.cloudwaysapps.com/wp-content/uploads/essential-addons-elementor/eael.js?ver=1718143107:28:489022] Cannot read properties of undefined (reading &#039;size&#039;) 
JS: 2024-06-11 22:02:13 [error X 32][https://wordpress-1090615-3846767.cloudwaysapps.com/wp-content/plugins/instagram-feed/admin/assets/js/callout.js:26:60] Cannot read properties of null (reading &#039;addEventListener&#039;) 
JS: 2024-06-13 21:23:36 [error X 1][https://wordpress-1090615-3846767.cloudwaysapps.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.21.8:3:326165] Cannot read properties of undefined (reading &#039;id&#039;) 
JS: 2024-06-14 14:18:38 [error X 3][https://wordpress-1090615-3846767.cloudwaysapps.com/wp-admin/load-scripts.php?c=0&amp;loadchunk_0=jquery-core,jquery-migrate,utils,moxiejs,plupload&amp;ver=6.5.4:2:28760] Cannot read properties of undefined (reading &#039;value&#039;) 
JS: 2024-06-17 14:37:24 [error X 14][https://wordpress-1090615-3846767.cloudwaysapps.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.22.1:3:825635] Cannot read properties of undefined (reading &#039;localized&#039;) 
JS: 2024-06-17 15:50:55 [error X 63][https://wordpress-1090615-3846767.cloudwaysapps.com/wp-content/plugins/jetformbuilder/assets/js/frontend/main.js?ver=250b7174e5f50c1b4a7a:1:41134] Cannot read properties of undefined (reading &#039;getName&#039;) 
JS: 2024-06-20 13:28:44 [error X 1][https://wordpress-1090615-3846767.cloudwaysapps.com/wp-content/plugins/elementor/assets/js/editor-document.min.js?ver=3.22.1:2:4095] Cannot read properties of null (reading &#039;history&#039;) 
JS: 2024-06-20 13:30:26 [error X 3][https://wordpress-1090615-3846767.cloudwaysapps.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.22.1:3:1176313] Cannot read properties of null (reading &#039;getBoundingClientRect&#039;) 

PHP: showing 7 of 7PHP: 2024-06-07 08:18:19 [error X 1][/home/1090615.cloudwaysapps.com/gbtjwgxrjc/public_html/wp-content/plugins/elementor-pro/modules/forms/registrars/form-actions-registrar.php::57] Uncaught Error: Class &#039;ElementorPro\Modules\Forms\Actions\Discord&#039; not found in /home/1090615.cloudwaysapps.com/gbtjwgxrjc/public_html/wp-content/plugins/elementor-pro/modules/forms/registrars/form-actions-registrar.php:57
Stack trace:
#0 /home/1090615.cloudwaysapps.com/gbtjwgxrjc/public_html/wp-includes/class-wp-hook.php(324): ElementorPro\Modules\Forms\Registrars\Form_Actions_Registrar-&gt;ElementorPro\Modules\Forms\Registrars\{closure}()
#1 /home/1090615.cloudwaysapps.com/gbtjwgxrjc/public_html/wp-includes/class-wp-hook.php(348): WP_Hook-&gt;apply_filters()
#2 /home/1090615.cloudwaysapps.com/gbtjwgxrjc/public_html/wp-includes/plugin.php(517): WP_Hook-&gt;do_action()
#3 /home/1090615.cloudwaysapps.com/gbtjwgxrjc/public_html/wp-content/plugins/elementor-pro/modules/forms/registrars/form-actions-registrar.php(84): do_action()
#4 /home/1090615.cloudwaysapps.com/gbtjwgxrjc/public_html/wp-content/plugins/elementor-pro/modules/forms/registrars/form-actions-registrar.php(42): ElementorPro\Modules\Forms\Registrars\Form_Acti [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-06-10 00:46:09 [error X 2][/home/1090615.cloudwaysapps.com/gbtjwgxrjc/public_html/wp-content/plugins/elementor/includes/managers/elements.php::71] Uncaught TypeError: Argument 1 passed to Elementor\Elements_Manager::create_element_instance() must be of the type array, bool given, called in /home/1090615.cloudwaysapps.com/gbtjwgxrjc/public_html/wp-content/plugins/jupiterx-core/includes/extensions/raven/includes/modules/product-gallery/module.php on line 111 and defined in /home/1090615.cloudwaysapps.com/gbtjwgxrjc/public_html/wp-content/plugins/elementor/includes/managers/elements.php:71
Stack trace:
#0 /home/1090615.cloudwaysapps.com/gbtjwgxrjc/public_html/wp-content/plugins/jupiterx-core/includes/extensions/raven/includes/modules/product-gallery/module.php(111): Elementor\Elements_Manager-&gt;create_element_instance()
#1 /home/1090615.cloudwaysapps.com/gbtjwgxrjc/public_html/wp-includes/class-wp-hook.php(324): JupiterX_Core\Raven\Modules\Product_Gallery\Module-&gt;get_gallery_items()
#2 /home/1090615.cloudwaysapps.com/gbtjwgxrjc/public_html/wp-includes/class-wp-hook.php(348): WP_Hook-&gt;apply_filters()
#3 /home/1090615.cloudwaysapps.com/gbtjwgxrjc/public_html/ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-06-10 11:03:58 [notice X 6][/home/1090615.cloudwaysapps.com/gbtjwgxrjc/public_html/wp-content/plugins/elementor/includes/conditions.php::87] Undefined index: mailerlite_list [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-06-14 17:25:36 [notice X 1][/home/1090615.cloudwaysapps.com/gbtjwgxrjc/public_html/wp-content/plugins/elementor-pro/modules/loop-filter/module.php::155] Undefined index: post_type [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-06-17 11:13:45 [error X 1][/home/1090615.cloudwaysapps.com/gbtjwgxrjc/public_html/wp-content/plugins/elementor-pro/core/modules-manager.php::84] Uncaught Error: Class &#039;\ElementorPro\Modules\OffCanvas\Module&#039; not found in /home/1090615.cloudwaysapps.com/gbtjwgxrjc/public_html/wp-content/plugins/elementor-pro/core/modules-manager.php:84
Stack trace:
#0 /home/1090615.cloudwaysapps.com/gbtjwgxrjc/public_html/wp-content/plugins/elementor-pro/plugin.php(361): ElementorPro\Core\Modules_Manager-&gt;__construct()
#1 /home/1090615.cloudwaysapps.com/gbtjwgxrjc/public_html/wp-includes/class-wp-hook.php(324): ElementorPro\Plugin-&gt;on_elementor_init()
#2 /home/1090615.cloudwaysapps.com/gbtjwgxrjc/public_html/wp-includes/class-wp-hook.php(348): WP_Hook-&gt;apply_filters()
#3 /home/1090615.cloudwaysapps.com/gbtjwgxrjc/public_html/wp-includes/plugin.php(517): WP_Hook-&gt;do_action()
#4 /home/1090615.cloudwaysapps.com/gbtjwgxrjc/public_html/wp-content/plugins/elementor/includes/plugin.php(658): do_action()
#5 /home/1090615.cloudwaysapps.com/gbtjwgxrjc/public_html/wp-includes/class-wp-hook.php(324): Elementor\Plugin-&gt;init()
#6 /home/1090615.cloudwaysapps.com/gbtjwgxrjc/public_htm [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-06-17 11:38:06 [notice X 72][/home/1090615.cloudwaysapps.com/gbtjwgxrjc/public_html/wp-content/plugins/elementor-pro/modules/dynamic-tags/tags/site-logo.php::32] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-06-17 17:10:50 [notice X 13][/home/1090615.cloudwaysapps.com/gbtjwgxrjc/public_html/wp-content/plugins/elementor/modules/history/revisions-manager.php::363] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 9 of 92024-06-17 11:14:45 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.21.3',
  'to' => '3.22.0',
)]
2024-06-17 11:41:04 [info] elementor-pro::elementor_pro_updater Started 
2024-06-17 11:41:04 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-06-17 11:41:04 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-06-17 11:41:04 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.21.3',
  'to' => '3.22.0',
)]
2024-06-17 11:41:10 [info] elementor::elementor_updater Started 
2024-06-17 11:41:10 [info] Elementor/Upgrades - _on_each_version Start  
2024-06-17 11:41:10 [info] Elementor/Upgrades - _on_each_version Finished 
2024-06-17 11:41:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.21.8',
  'to' => '3.22.1',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	JetBlog For Elementor: Compatibility not specified
	JetElements For Elementor: Compatibility not specified
	JetTabs For Elementor: Compatibility not specified
	JetWooBuilder For Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by schusterdragon** [comment]
Hello Elementor Dev's! We got nearly the same issue and I was searching for a thread to contribute which has been already opened and just found this one.

It occured first in 12_2024, when we updated to Elementor 3.26.0 / Elementor Pro 3.26.1 and it seems to be caused by the experimental Elementor setting: "element caching". The issue has something to do with dynamic content, woocommerce and the carousel widgets. no matter if i use image carousel or the other, loaded with an image widget for each slide. 

I am able to reproduce the error when i set the experimental element caching back from inactive to default for widgets which are showing dynamic content, like my carousel sliders with woocommerce content and change the element caching for my static image carousel from active to default as well. 

If done so, the dynamic carousels will hide instantly and the static imace carousel looks exactly like OP's screenshot - but only woocommerce-shop pages seems to be affected (and of course, only frontend is affected). My static Homepage and other static pages are not harmed. Some of them also have the same dynamic and static carousels. 

My static image carousel is part of some kind of a sindebar-like container template and this is part of most page and shop templates. The carousel has also 1 slide to display and 1 slide to scroll and spreads up downwards but after a few seconds it will disappear and leave behind a huge gap in the page alignment.

Now i realized, that i also have the issue within the checkout pages and the only workaround is to set the element caching inactive at the backend elementor settings in the features tab.

Really looking forward to a bugfix :-)
Greetings and kind regards, Sebastian

**Comment by stuartstfield** [comment]
Sebastian, 
I am having the same issue.  Have you found a fix?

**Comment by schusterdragon** [comment]
Hi, actually I am waiting for our next update session. However, in my case, setting the element caching globally inactive (in the backend Elementor settings under the features tab) will do the job and literally won't affect the webshop's performance noticeably. 

Maybe, you could  search for every widget which maybe has been feeded by dynamic content and set the caching to inactive manually. Btw did you read this Elementor article about the feature? https://elementor.com/help/element-caching-help/

Anyway, sometimes Elementor runs in some bizarre errors where de- and reactivating the whole elementor plugin will cause some kind of initialisation and hopefully clearing the bug, but of course without permission...

**Comment by schusterdragon** [comment]
Elementor 3.27 has been rolled ou now but I'm afraid to activate the element caching again, because i could not find a bugfix adressing the error in the Patchlog. Has anyone already tested element caching regarding the issue in 3.27?

**Comment by Orion2193** [comment]
I tried update to 3.29 today of both Elementor and Elementor Pro but the issue seems to be still present, has anyone found a fix / workaround?
