### ISSUE TITLE
⛔ 🧩 Conflict between "Element cache" and the "Dynamic visibily" of the JetEngine

### ISSUE THREAD

**Issue by cabez0n275** [elementor/elementor#27978]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

When activating the new Elementor "Element cache" function, we detected problems with the elements to which we had applied the "Dynamic visibilty" conditional of "JetEngine". 

### Steps to reproduce

When activating the new Elementor "Element cache" function, we detected problems with the elements to which we had applied the "Dynamic visibilty" conditional of "JetEngine". 

### Expected behavior

The visibility of these elements behaves arbitrarily, by deactivating the function everything has been solved.

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [ ] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: mariadb.org binary distribution v10.11.7-MariaDB-1:10.11.7+maria~deb11-log
	PHP Version: 7.4.33
	PHP Memory Limit: 256M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 20M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.5.5
	Site URL: https://ingennus.com
	Home URL: https://ingennus.com
	WP Multisite: No
	Max Upload Size: 20 MB
	Memory limit: 256M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: es_ES
	Timezone: Europe/Madrid
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 3.1.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: es
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36

== Active Plugins ==
	All In One WP Security
		Version: 5.3.1
		Author: All In One WP Security & Firewall Team

	BackWPup
		Version: 4.1.3
		Author: BackWPup – WordPress Backup & Restore Plugin

	Elementor
		Version: 3.22.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.22.1
		Author: Elementor.com

	Enable Media Replace
		Version: 4.1.5
		Author: ShortPixel

	Hide admin menu
		Version: 1.1.2
		Author: Bhavin Thummar & Maulik Patel (BM Studio)

	Imagify
		Version: 2.2.2
		Author: Imagify – Optimize Images & Convert WebP & Avif

	JetElements For Elementor
		Version: 2.6.18
		Author: Crocoblock

	JetEngine
		Version: 3.5.1
		Author: Crocoblock

	JetMenu
		Version: 2.4.4
		Author: Crocoblock

	JetTabs For Elementor
		Version: 2.2.3
		Author: Crocoblock

	Language Switcher for Elementor
		Version: 1.0.5
		Author: wepic

	Make Column Clickable Elementor
		Version: 1.4.0
		Author: Fernando Acosta

	Redirection
		Version: 5.4.2
		Author: John Godley

	Regenerate Thumbnails Advanced
		Version: 2.5.0
		Author: ShortPixel

	Simple CSS
		Version: 1.1.1
		Author: Tom Usborne

	Simple Custom Post Order
		Version: 2.5.7
		Author: Colorlib

	Sticky Header Effects for Elementor
		Version: 1.4.8
		Author: Rwattner

	User Role Editor
		Version: 4.64.2
		Author: Vladimir Garagulya

	WeePie Cookie Allow
		Version: 3.4.7
		Author: WeePie Plugins

	WP Excerpt Generator
		Version: 2.6.1
		Author: Mathieu Chartier

	WPML Multilingual CMS
		Version: 4.6.11
		Author: OnTheGoSystems

	WPML String Translation
		Version: 3.2.12
		Author: OnTheGoSystems

	WP Rocket
		Version: 3.16.1.1
		Author: WP Media

	Yoast SEO
		Version: 23.0
		Author: Team Yoast


== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com


== Uso de los elementos ==
	
	container : 1
		button : 12
		container : 21
		divider : 1
		heading : 41
		image : 11
		image-carousel : 4
		jet-accordion : 2
		jet-listing-dynamic-field : 1
		jet-listing-dynamic-terms : 1
		jet-listing-grid : 9
		jet-mobile-menu : 1
		jet-tabs : 1
		language-switcher : 1
		social-icons : 1
		text-editor : 18
		video : 3
	page : 1
		button : 2
		divider : 1
		heading : 3
		image : 2
		text-editor : 3
	section : 18
		container : 2
		heading : 3
		image : 1
		jet-listing-grid : 3
	single : 9
		button : 5
		container : 3
		heading : 16
		image : 2
		image-carousel : 4
		jet-listing-dynamic-field : 1
		jet-listing-grid : 1
		template : 1
		text-editor : 13
	wp-post : 4
		text-editor : 2
	wp-page : 45
		button : 13
		container : 15
		counter : 6
		heading : 62
		icon : 7
		image : 20
		jet-listing-grid : 4
		jet-table : 1
		jet-tabs : 1
		text-editor : 57
		video : 2
	jet-listing-items : 0
		container : 1
		heading : 1
		image : 1


== Ajustes ==
	
	cpt_support: post, page, jet-menu
	disable_color_schemes: yes
	allow_tracking: yes
	unfiltered_files_upload: 1
	load_fa4_shim: yes


== Caracteristicas ==
	Custom Fonts: 1
	Custom Icons: 0

== Integraciones ==
	


== Experimentos de Elementor ==
	Carga de recursos mejorada: Activo por defecto
	Carga de CSS mejorada: Activo
	Fuentes de iconos integradas: Inactivo por defecto
	Puntos de ruptura personalizados adicionales: Activo por defecto
	Contenedor Flexbox: Activo
	Contenedor Grid: Activo por defecto
	Actualizar la librería Swiper: Activo por defecto
	Rendimiento de los elementos anidados: Inactivo por defecto
	Carga de controles optimizada: Inactivo por defecto
	Marcado optimizado: Inactivo por defecto
	Puesta en marcha del plugin: Activo por defecto
	Por defecto, el nuevo constructor de temas: Activo por defecto
	Cabecera y pie de página: Inactivo por defecto
	Pantalla de inicio de Elementor: Activo por defecto
	Barra superior del editor: Inactivo por defecto
	Construir con IA: Activo por defecto
	Páginas de destino: Activo por defecto
	Elementos anidados: Activo
	Carga diferida de imágenes de fondo: Activo
	Caché de elementos: Inactivo
	Centro de conversión: Inactivo por defecto
	Condiciones de visualización: Inactivo
	Envíos de formulario: Activo por defecto
	Menú: Inactivo por defecto
	Filtro de taxonomía: Activo por defecto


== Registro ==
	
Log: showing 20 of 372024-06-19 13:04:56 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.21.8',
  'to' => '3.22.1',
)]
2024-06-19 13:04:57 [info] elementor::elementor_updater Started 
2024-06-19 13:04:57 [info] Elementor/Upgrades - _on_each_version Start  
2024-06-19 13:04:57 [info] Elementor/Upgrades - _on_each_version Finished 
2024-06-19 13:04:57 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.21.8',
  'to' => '3.22.1',
)]
2024-06-19 13:04:58 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.21.8',
  'to' => '3.22.1',
)]
2024-06-20 14:07:14 [info] elementor-pro::elementor_pro_updater Started 
2024-06-20 14:07:14 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-06-20 14:07:14 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-06-20 14:07:14 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.21.3',
  'to' => '3.22.0',
)]
2024-06-20 14:07:16 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.21.3',
  'to' => '3.22.0',
)]
2024-07-08 07:31:01 [info] elementor::elementor_updater Started 
2024-07-08 07:31:01 [info] Elementor/Upgrades - _on_each_version Start  
2024-07-08 07:31:01 [info] Elementor/Upgrades - _on_each_version Finished 
2024-07-08 07:31:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.22.1',
  'to' => '3.22.3',
)]
2024-07-08 07:31:05 [info] elementor-pro::elementor_pro_updater Started 
2024-07-08 07:31:05 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-07-08 07:31:05 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-07-08 07:31:05 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.22.0',
  'to' => '3.22.1',
)]
2024-07-08 07:31:06 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.22.0',
  'to' => '3.22.1',
)]

PHP: showing 4 of 4PHP: 2024-05-10 13:05:49 [error X 1][../wp-content/plugins/elementor/data/base/controller.php::210] Uncaught Error: Class 'ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates' not found in ../wp-content/plugins/elementor/data/base/controller.php:210
Stack trace:
#0 ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/controller.php(17): Elementor\Data\Base\Controller->register_endpoint('ElementorPro\\Co...')
#1 ../wp-content/plugins/elementor/data/base/controller.php(265): ElementorPro\Core\App\Modules\SiteEditor\Data\Controller->register_endpoints()
#2 ../wp-content/plugins/elementor/data/base/controller.php(49): Elementor\Data\Base\Controller->register()
#3 ../wp-includes/class-wp-hook.php(324): Elementor\Data\Base\Controller->Elementor\Data\Base\{closure}(Object(WP_REST_Server))
#4 ../wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#5 ../wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 ../wp-includes/rest-api.php(597) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-05-28 17:07:40 [notice X 1][../wp-content/plugins/elementor/includes/base/controls-stack.php::1477] Undefined index: _flex_size_tablet [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-05-30 08:32:05 [warning X 2][../wp-content/plugins/elementor/includes/db.php::267] Invalid argument supplied for foreach() [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-06-20 14:09:16 [notice X 2067][../wp-content/plugins/elementor/core/dynamic-tags/manager.php::73] Array to string conversion [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 1 of 1JS: 2024-07-08 05:31:36 [error X 297][../wp-content/plugins/jet-elements/assets/js/jet-elements.min.js?ver=2.6.18:1:64312] Cannot read properties of undefined (reading 'size') 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibilidad no especificada
	JetElements For Elementor: Compatibilidad no especificada
	JetTabs For Elementor: Compatibilidad no especificada
	Language Switcher for Elementor: Compatibilidad no especificada
	Make Column Clickable Elementor: Compatibilidad no especificada
	Sticky Header Effects for Elementor: Compatibilidad no especificada

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hello @cabez0n275,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
The Element Caching feature cannot be used on elements that contain Dynamic Tags or any other type of Dynamic Content as explained in the [Documentation](https://elementor.com/help/element-caching-help/).

3rd-Party Addons need to make their plugins compatible with this feature (by opting out of caching) in order for their plugins to work properly. Make sure the addons you are using added compatibility with this feature.

### 👍 For now, that's all we can help with. 

If you think this is still an issue caused by Elementor after following the troubleshooting steps above, feel free to open a new 🐞 [Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml).

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
