### ISSUE TITLE
⛔ 🧩 Elementor Loop grid images do not load in correctly after the first image when a taxonomy filter is selected

### ISSUE THREAD

**Issue by najaficompute** [elementor/elementor#27990]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Im facing a problem with the combination of the Elementor loop grid and taxonomy filters where the loop grid images are being loading in with the src replaced with "data:image/svg+xml;charset=utf-8,%3Csvg xmlns%3D'http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg' viewBox%3D'0 0 1024 1024'%2F%3E" instead of the actual product image src. This does not occur on the first page load into a taxonomy filter link address, but it does occur when any of the taxonomy filter options are selected. Only the first image will load correctly the rest of the loop grid images will have the incorrect src code.

### Steps to reproduce

1. enter [lussomodernhome.com/shop](https://lussomodernhome.com/shop/) , notice how all the loop grid product images load in as expected.
2. click any of the taxonomy filter product selection options. The page will update and load in the correct items but only the first loop grid objects image will load in correctly. the rest will have the image src replaced with "data:image/svg+xml;charset=utf-8,%3Csvg xmlns%3D'http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg' viewBox%3D'0 0 1024 1024'%2F%3E"

<img width="1645" alt="Screenshot 2024-07-08 at 3 03 05 PM" src="https://github.com/elementor/elementor/assets/50119760/559262f2-0d1f-4189-b902-6b1c4aa49638">
<img width="1670" alt="Screenshot 2024-07-08 at 3 02 54 PM" src="https://github.com/elementor/elementor/assets/50119760/f01755b7-7715-4674-a8a9-cea337fe619e">

### Expected behavior

the expected behaviour is for the product loop grid image src to match the srcset url when a taxonomy filter option is selected.

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt


== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.6.18
	PHP Version: 7.4.33
	PHP Memory Limit: 512M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.5.5
	Site URL: https://lussomodernhome.com
	Home URL: https://lussomodernhome.com
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en_US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: ArcHub
	Version: 1.2.5
	Author: Liquid Themes
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36

== Active Plugins ==
	ArcHub Core
		Version: 1.2.5
		Author: Liquid Themes

	ArcHub Elementor Addons
		Version: 1.2.5
		Author: Liquid Themes

	ArcHub Portfolio
		Version: 1.0
		Author: Liquid Themes

	Backuply
		Version: 1.3.0
		Author: Softaculous

	Better Search Replace
		Version: 1.4.7
		Author: WP Engine

	Contact Form 7
		Version: 5.9.6
		Author: Takayuki Miyoshi

	Elementor
		Version: 3.22.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.20.0
		Author: Elementor.com

	ElementsKit Lite
		Version: 3.2.0
		Author: Wpmet

	ElementsKit Pro
		Version: 3.6.1
		Author: Wpmet

	Essential Addons for Elementor
		Version: 5.9.24
		Author: WPDeveloper

	Essential Addons for Elementor - Pro
		Version: 5.8.11
		Author: WPDeveloper

	External Importer
		Version: 2.7.1
		Author: keywordrush.com

	Image Optimizer by Elementor – Compress, Resize and Optimize Images
		Version: 1.3.0
		Author: Elementor.com

	Integration of Zoho Books with WooCommerce Pro
		Version: 1.4
		Author: Forms Integrations

	Liquid GDPR Box
		Version: 1.0.2
		Author: LiquidThemes

	Loginizer
		Version: 1.8.4
		Author: Softaculous

	Merchant
		Version: 1.9.12
		Author: aThemes

	Premium Addons for Elementor
		Version: 4.10.31
		Author: Leap13

	Premium Addons PRO
		Version: 2.9.17
		Author: Leap13

	PRO Elements
		Version: 3.20.2
		Author: PROElements.org

	SiteSEO
		Version: 1.0.7
		Author: Softaculous

	Slider Revolution
		Version: 6.7.9
		Author: ThemePunch

	SpeedyCache
		Version: 1.1.7
		Author: Softaculous Team

	SpeedyCache Pro
		Version: 1.1.6
		Author: Softaculous Team

	Store Toolkit for WooCommerce
		Version: 2.3.10
		Author: Visser Labs

	Templately
		Version: 3.0.8
		Author: Templately

	Variation Swatches for WooCommerce
		Version: 2.1.0
		Author: Emran Ahmed

	Variation Swatches for WooCommerce - Pro
		Version: 2.1.3
		Author: Emran Ahmed

	WooCommerce
		Version: 9.0.2
		Author: Automattic

	WooCommerce.com Update Manager
		Version: 1.0.3
		Author: Automattic

	WooCommerce Shipping &amp; Tax
		Version: 2.6.1
		Author: WooCommerce

	WooPayments
		Version: 7.8.1
		Author: Automattic

	WP Activity Log
		Version: 4.6.4
		Author: Melapress

	WP Bulk Delete
		Version: 1.2.8
		Author: Xylus Themes


== Features ==
	Custom Fonts: 3
	Custom Icons: 0

== Integrations ==
	
	woocommerce: Active


== Elementor Experiments ==
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Active by default
	Additional Custom Breakpoints: Active by default
	Flexbox Container: Active
	Grid Container: Active by default
	Upgrade Swiper Library: Active by default
	Nested Elements Performance: Inactive by default
	Optimized Control Loading: Inactive by default
	Optimized Markup: Inactive by default
	Plugin Onboarding: Active by default
	Default to New Theme Builder: Active by default
	Elementor Home Screen: Active by default
	Editor Top Bar: Inactive by default
	Build with AI: Active by default
	Landing Pages: Active by default
	Nested Elements: Active
	Lazy Load Background Images: Active by default
	Element Caching: Inactive by default
	Conversion Center: Inactive by default
	Notes: Active by default
	Display Conditions: Active by default
	Form Submissions: Active by default
	Menu: Active
	Taxonomy Filter: Active


== Log ==
	
JS: showing 8 of 8JS: 2024-06-14 23:51:28 [error X 1][../wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.21.8:3:14246] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got as `image` value. Expected array or object.',
)]
JS: 2024-06-15 02:47:16 [error X 2][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.21.8:3:1161578] Cannot read properties of null (reading &#039;getBoundingClientRect&#039;) 
JS: 2024-06-25 19:23:09 [error X 4][../wp-content/plugins/elementor/assets/js/0e842fae60df2bcb2a30.bundle.min.js:2:7789] Cannot read properties of null (reading &#039;dataset&#039;) 
JS: 2024-06-26 21:05:42 [error X 18][../wp-content/uploads/essential-addons-elementor/eael.js?ver=1719358586:28:491036] Cannot read properties of undefined (reading &#039;hasOwnProperty&#039;) 
JS: 2024-06-28 17:15:23 [error X 1180][../wp-content/uploads/essential-addons-elementor/eael.js?ver=1719445819:28:488607] Cannot read properties of undefined (reading &#039;size&#039;) 
JS: 2024-06-28 17:15:28 [error X 3][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.22.3:3:584964] Failed to read a named property &#039;elementorFrontend&#039; from &#039;Window&#039;: Blocked a frame with origin &quot;..&quot; from accessing a cross-origin frame. 
JS: 2024-06-28 19:09:27 [error X 2][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.22.3:3:825635] Cannot read properties of undefined (reading &#039;localized&#039;) 
JS: 2024-06-30 19:16:55 [error X 1][../wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.22.3:3:14246] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `spacer` got as `_background_image` value. Expected array or object.',
)]

PHP: showing 19 of 19PHP: 2024-06-15 02:46:11 [notice X 10][../wp-content/plugins/elementor/modules/history/revisions-manager.php::363] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-06-15 03:06:27 [notice X 14][../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined index: condition_type [array (
  'trace' => '
#0: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: ../wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2024-06-15 03:17:28 [notice X 18][../wp-content/plugins/elementor-pro/modules/loop-filter/query/taxonomy-manager.php::150] Undefined index: logicalJoin [array (
  'trace' => '
#0: ../wp-content/plugins/elementor-pro/modules/loop-filter/query/taxonomy-manager.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ../wp-content/plugins/elementor-pro/modules/loop-filter/query/taxonomy-query-builder.php(33): ElementorPro\Modules\LoopFilter\Query\Taxonomy_Manager -> get_hierarchy_of_selected_terms()
#2: ../wp-content/plugins/elementor-pro/modules/loop-filter/module.php(128): ElementorPro\Modules\LoopFilter\Query\Taxonomy_Query_Builder -> get_merged_queries()
#3: ../wp-includes/class-wp-hook.php(324): ElementorPro\Modules\LoopFilter\Module -> filter_loop_query()
#4: ../wp-includes/plugin.php(205): WP_Hook -> apply_filters()
',
)]
PHP: 2024-06-16 23:22:29 [notice X 19][../wp-content/plugins/elementor/includes/managers/image.php::113] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-06-20 23:14:26 [notice X 3][../wp-content/plugins/elementor-pro/elementor-pro.php::60] Constant ELEMENTOR_PRO_MODULES_URL already defined [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-06-24 23:28:18 [notice X 7][../wp-content/plugins/elementor-pro/modules/loop-filter/query/query-types/hierarchy-or-query.php::77] Undefined property: ElementorPro\Modules\LoopFilter\Query\QueryTypes\Hierarchy_Or_Query::$taxonomy_manager [array (
  'trace' => '
#0: ../wp-content/plugins/elementor-pro/modules/loop-filter/query/query-types/hierarchy-or-query.php(77): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ../wp-content/plugins/elementor-pro/modules/loop-filter/query/query-types/hierarchy-or-query.php(32): ElementorPro\Modules\LoopFilter\Query\QueryTypes\Hierarchy_Or_Query -> get_hierarchy_query()
#2: ../wp-content/plugins/elementor-pro/modules/loop-filter/query/taxonomy-query-builder.php(79): ElementorPro\Modules\LoopFilter\Query\QueryTypes\Hierarchy_Or_Query -> get_query()
#3: ../wp-content/plugins/elementor-pro/modules/loop-filter/query/taxonomy-query-builder.php(56): ElementorPro\Modules\LoopFilter\Query\Taxonomy_Query_Builder -> get_query()
#4: ../wp-content/plugins/elementor-pro/modules/loop-filter/query/taxonomy-query-builder.php(40): ElementorPro\Modules\LoopFilter\Query\Taxonomy_Query_Builder -> get_multiple_selection_query()
',
)]
PHP: 2024-06-24 23:28:18 [error X 7][../wp-content/plugins/elementor-pro/modules/loop-filter/query/query-types/hierarchy-or-query.php::77] Uncaught Error: Call to a member function is_parent_term_with_children() on null in ../wp-content/plugins/elementor-pro/modules/loop-filter/query/query-types/hierarchy-or-query.php:77
Stack trace:
#0 ../wp-content/plugins/elementor-pro/modules/loop-filter/query/query-types/hierarchy-or-query.php(32): ElementorPro\Modules\LoopFilter\Query\QueryTypes\Hierarchy_Or_Query-&gt;get_hierarchy_query(Array)
#1 ../wp-content/plugins/elementor-pro/modules/loop-filter/query/taxonomy-query-builder.php(79): ElementorPro\Modules\LoopFilter\Query\QueryTypes\Hierarchy_Or_Query-&gt;get_query()
#2 ../wp-content/plugins/elementor-pro/modules/loop-filter/query/taxonomy-query-builder.php(56): ElementorPro\Modules\LoopFilter\Query\Taxonomy_Query_Builder-&gt;get_query(Object(ElementorPro\Modules\LoopFilter\Query\QueryTypes\Hierarchy_Or_Query))
#3 /home/eminenf4/public_html/LussoModernH [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-06-26 19:29:34 [error X 2][../wp-content/plugins/elementor/core/common/modules/ajax/module.php::270] Allowed memory size of 536870912 bytes exhausted (tried to allocate 59252136 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-06-26 19:46:17 [error X 1][../wp-content/plugins/elementor/core/common/modules/ajax/module.php::270] Allowed memory size of 536870912 bytes exhausted (tried to allocate 59281552 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-06-27 23:21:33 [error X 1][../wp-content/plugins/elementor/core/common/modules/ajax/module.php::270] Allowed memory size of 536870912 bytes exhausted (tried to allocate 59283312 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-06-28 17:20:05 [notice X 10][../wp-content/plugins/elementor-pro/modules/loop-filter/query/query-types/hierarchy-or-query.php::77] Undefined property: ElementorPro\Modules\LoopFilter\Query\QueryTypes\Hierarchy_Or_Query::$taxonomy_manager [array (
  'trace' => '
#0: ../wp-content/plugins/elementor-pro/modules/loop-filter/query/query-types/hierarchy-or-query.php(77): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ../wp-content/plugins/elementor-pro/modules/loop-filter/query/query-types/hierarchy-or-query.php(32): ElementorPro\Modules\LoopFilter\Query\QueryTypes\Hierarchy_Or_Query -> get_hierarchy_query()
#2: ../wp-content/plugins/elementor-pro/modules/loop-filter/query/taxonomy-query-builder.php(79): ElementorPro\Modules\LoopFilter\Query\QueryTypes\Hierarchy_Or_Query -> get_query()
#3: ../wp-content/plugins/elementor-pro/modules/loop-filter/query/taxonomy-query-builder.php(56): ElementorPro\Modules\LoopFilter\Query\Taxonomy_Query_Builder -> get_query()
#4: ../wp-content/plugins/elementor-pro/modules/loop-filter/query/taxonomy-query-builder.php(40): ElementorPro\Modules\LoopFilter\Query\Taxonomy_Query_Builder -> get_multiple_selection_query()
',
)]
PHP: 2024-06-28 17:20:05 [error X 16][../wp-content/plugins/elementor-pro/modules/loop-filter/query/query-types/hierarchy-or-query.php::77] Uncaught Error: Call to a member function is_parent_term_with_children() on null in ../wp-content/plugins/elementor-pro/modules/loop-filter/query/query-types/hierarchy-or-query.php:77
Stack trace:
#0 ../wp-content/plugins/elementor-pro/modules/loop-filter/query/query-types/hierarchy-or-query.php(32): ElementorPro\Modules\LoopFilter\Query\QueryTypes\Hierarchy_Or_Query-&gt;get_hierarchy_query(Array)
#1 ../wp-content/plugins/elementor-pro/modules/loop-filter/query/taxonomy-query-builder.php(79): ElementorPro\Modules\LoopFilter\Query\QueryTypes\Hierarchy_Or_Query-&gt;get_query()
#2 ../wp-content/plugins/elementor-pro/modules/loop-filter/query/taxonomy-query-builder.php(56): ElementorPro\Modules\LoopFilter\Query\Taxonomy_Query_Builder-&gt;get_query(Object(ElementorPro\Modules\LoopFilter\Query\QueryTypes\Hierarchy_Or_Query))
#3 ../wp-content/plugins/elementor-pro/mod [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-06-28 19:02:11 [notice X 3][../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined index: condition_type [array (
  'trace' => '
#0: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: ../wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2024-06-29 21:34:18 [error X 3][../wp-content/plugins/elementor/core/common/modules/ajax/module.php::270] Allowed memory size of 536870912 bytes exhausted (tried to allocate 59273904 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-06-30 01:34:03 [error X 4][../wp-content/plugins/elementor/core/common/modules/ajax/module.php::270] Allowed memory size of 536870912 bytes exhausted (tried to allocate 59273888 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-06-30 19:16:55 [notice X 1][../wp-content/plugins/elementor/includes/elements/container.php::1835] Undefined index: size [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-06-30 19:30:26 [notice X 94][../wp-content/plugins/elementor/core/files/css/base.php::783] Undefined index: padding_mobile [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-06-30 21:23:41 [notice X 166][../wp-content/plugins/elementor-pro/modules/loop-filter/query/taxonomy-manager.php::150] Undefined index: logicalJoin [array (
  'trace' => '
#0: ../wp-content/plugins/elementor-pro/modules/loop-filter/query/taxonomy-manager.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ../wp-content/plugins/elementor-pro/modules/loop-filter/query/taxonomy-query-builder.php(33): ElementorPro\Modules\LoopFilter\Query\Taxonomy_Manager -> get_hierarchy_of_selected_terms()
#2: ../wp-content/plugins/elementor-pro/modules/loop-filter/module.php(128): ElementorPro\Modules\LoopFilter\Query\Taxonomy_Query_Builder -> get_merged_queries()
#3: ../wp-includes/class-wp-hook.php(324): ElementorPro\Modules\LoopFilter\Module -> filter_loop_query()
#4: ../wp-includes/plugin.php(205): WP_Hook -> apply_filters()
',
)]
PHP: 2024-07-03 23:05:57 [error X 1][../wp-content/plugins/elementor/core/common/modules/ajax/module.php::270] Allowed memory size of 536870912 bytes exhausted (tried to allocate 59273848 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 15 of 152024-06-20 23:13:23 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.21.8',
  'to' => '3.22.1',
)]
2024-06-20 23:13:23 [info] elementor::elementor_updater Started 
2024-06-20 23:13:23 [info] Elementor/Upgrades - _on_each_version Start  
2024-06-20 23:13:23 [info] Elementor/Upgrades - _on_each_version Finished 
2024-06-20 23:13:23 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.21.8',
  'to' => '3.22.1',
)]
2024-06-20 23:13:25 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.21.8',
  'to' => '3.22.1',
)]
2024-06-20 23:13:53 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.20.0',
  'to' => '3.20.2',
)]
2024-06-20 23:13:54 [info] elementor-pro::elementor_pro_updater Started 
2024-06-20 23:13:54 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-06-20 23:13:54 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-06-20 23:13:54 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.20.0',
  'to' => '3.20.2',
)]
2024-06-28 15:16:39 [info] elementor::elementor_updater Started 
2024-06-28 15:16:39 [info] Elementor/Upgrades - _on_each_version Start  
2024-06-28 15:16:39 [info] Elementor/Upgrades - _on_each_version Finished 
2024-06-28 15:16:39 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.22.1',
  'to' => '3.22.3',
)]



== Elementor - Compatibility Tag ==
	
	ArcHub Elementor Addons: Incompatible
	Elementor Pro: Incompatible
	Essential Addons for Elementor: Compatible
	Essential Addons for Elementor - Pro: Incompatible
	Image Optimizer by Elementor – Compress, Resize and Optimize Images: Compatibility not specified
	Premium Addons for Elementor: Incompatible
	Premium Addons PRO: Incompatible
	PRO Elements: Incompatible

== Elementor Pro - Compatibility Tag ==
	
	ArcHub Elementor Addons: Incompatible
	Essential Addons for Elementor: Compatible
	Essential Addons for Elementor - Pro: Compatible
	Premium Addons for Elementor: Compatible
	Premium Addons PRO: Compatible

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hello @najaficompute,

Thank you for reaching out, and apologies for the delay! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
We reproduced your Loop Item template by applying Dynamic Background Images, and also trying to use the Product Image widget, and in both cases we could use the Taxonomy Filter correctly without any issue. When we checked your System Info, it seems you are using multiple plugins, and multiple performance optimization solutions that may be the root cause of the issue.

You can see in the video below the Taxonomy Filter working correctly:

https://github.com/user-attachments/assets/378cfc60-4b93-4dba-be02-629853674e2f



### ✅ What you can do to solve your issue:
As instructed and required in the Bug Report form:
- Isolate the problem by temporarily switching to the Hello Elementor Theme, and deactivating **<ins>ALL PLUGINS</ins>** except Elementor, Elementor Pro, and WooCommerce.
- Troubleshoot the issue by clearing, purging and temporarily deactivating all levels of cache, and ensuring you don't have any Elementor addons active either. Test on other browsers and different devices.

As a gentle reminder, we cannot provide support for 3rd-party plugins that may conflict with our features.

**👍 For now, that's all we can help with.** 

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for personal or 3rd-party support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
