### ISSUE TITLE
⛔ 🚀 Global Widgets - No Ability to Rename

### ISSUE THREAD

**Issue by wpturnedup** [elementor/elementor#28032]
### Prerequisites

- [ ] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Unlike other templates, we do not have the option to rename Global Widgets.

### Steps to reproduce

1. Add a Global Widget to the site.
2. There's no ability to rename.

### Expected behavior

The ability to rename Global Widgets without going into the database.

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [ ] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal>/summary>

```txt
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.25.5
	MySQL version: mariadb.org binary distribution v10.11.5-MariaDB-1:10.11.5+maria~ubu2004
	PHP Version: 8.3.8
	PHP Memory Limit: 512M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.5.5
	Site URL: https://mylisting.club
	Home URL: https://mylisting.club
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 512M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en_US
	Timezone: America/New_York

	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 3.1.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36

== Active Plugins ==
	AutomateWoo
		Version: 6.0.29
		Author: WooCommerce

	Elementor
		Version: 3.22.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.22.1
		Author: Elementor.com

	Enable Media Replace
		Version: 4.1.5
		Author: ShortPixel

	Free Downloads WooCommerce Pro
		Version: 3.5.8.3
		Author: WP Enhanced

	JetTabs For Elementor
		Version: 2.2.3
		Author: Crocoblock

	Loco Translate
		Version: 2.6.10
		Author: Tim Whitlock

	MailPoet
		Version: 4.55.0
		Author: MailPoet

	Perfmatters
		Version: 2.3.1
		Author: forgemedia

	SEOPress
		Version: 7.9.2
		Author: The SEO Guys at SEOPress

	SEOPress PRO
		Version: 7.9.2
		Author: The SEO Guys at SEOPress

	Simple Cloudflare Turnstile
		Version: 1.26.2
		Author: Elliot Sowersby, RelyWP

	Solid Affiliate
		Version: 2.1.2
		Author: Solid Plugins

	Two Factor
		Version: 0.9.1
		Author: Plugin Contributors

	WooCommerce
		Version: 9.0.2
		Author: Automattic

	WooCommerce Memberships
		Version: 1.26.6
		Author: SkyVerge

	WooCommerce Stripe Gateway
		Version: 8.4.0
		Author: WooCommerce

	WooCommerce Subscriptions
		Version: 6.4.1
		Author: WooCommerce

	WPCodeBox 2
		Version: 1.1.1
		Author: WPCodeBox

	WP Grid Builder
		Version: 1.9.0
		Author: Loïc Blascos

	WP Software License
		Version: 3.3.8
		Author: Nsp Code

	WP Term Order
		Version: 2.1.0
		Author: John James Jacoby

	WP Umbrella
		Version: 2.15.4
		Author: WP Umbrella - Backup & Manage WordPress


== Must-Use Plugins ==
	Kinsta Must-use Plugins
		Version: 3.1.1
		Author: Kinsta Team

	Perfmatters MU
		Version: 2.3.1
		Author: forgemedia

	WP Umbrella
		Version: 1.0.0
		Author: WP Umbrella

	_WPHealthHandlerMU.php
		Version: 
		Author: 


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	
	woocommerce: Active


== Elementor Experiments ==
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Additional Custom Breakpoints: Active
	Flexbox Container: Active
	Grid Container: Active
	Upgrade Swiper Library: Inactive
	Nested Elements Performance: Inactive by default
	Optimized Control Loading: Inactive
	Optimized Markup: Inactive by default
	Plugin Onboarding: Active by default
	Default to New Theme Builder: Inactive
	Header & Footer: Inactive
	Elementor Home Screen: Active by default
	Editor Top Bar: Inactive
	Build with AI: Inactive
	Landing Pages: Inactive
	Nested Elements: Active
	Lazy Load Background Images: Inactive
	Element Caching: Inactive by default
	Conversion Center: Inactive by default
	Display Conditions: Inactive
	Form Submissions: Inactive
	Menu: Active
	Taxonomy Filter: Inactive


== Log ==
	
Log: showing 20 of 322024-05-22 07:13:23 [info] Elementor/Upgrades - _on_each_version Start  
2024-05-22 07:13:23 [info] Elementor/Upgrades - _on_each_version Finished 
2024-05-22 07:13:23 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.21.6',
  'to' => '3.21.7',
)]
2024-05-22 07:13:23 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.21.6',
  'to' => '3.21.7',
)]
2024-05-26 09:00:53 [info] elementor::elementor_updater Started 
2024-05-26 09:00:53 [info] Elementor/Upgrades - _on_each_version Start  
2024-05-26 09:00:53 [info] Elementor/Upgrades - _on_each_version Finished 
2024-05-26 09:00:53 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.21.7',
  'to' => '3.21.8',
)]
2024-05-26 09:00:53 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.21.7',
  'to' => '3.21.8',
)]
2024-07-05 16:14:39 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.21.8',
  'to' => '3.22.3',
)]
2024-07-05 16:14:51 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.21.3',
  'to' => '3.22.1',
)]
2024-07-05 16:14:57 [info] elementor::elementor_updater Started 
2024-07-05 16:14:57 [info] Elementor/Upgrades - _on_each_version Start  
2024-07-05 16:14:57 [info] Elementor/Upgrades - _on_each_version Finished 
2024-07-05 16:14:57 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.21.8',
  'to' => '3.22.3',
)]
2024-07-05 16:15:01 [info] elementor-pro::elementor_pro_updater Started 
2024-07-05 16:15:01 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-07-05 16:15:01 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-07-05 16:15:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.21.3',
  'to' => '3.22.1',
)]
2024-07-05 16:15:02 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.21.3',
  'to' => '3.22.1',
)]

PHP: showing 1 of 1PHP: 2024-05-20 10:49:54 [error X 1][../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::200] Uncaught Error: Class "\ElementorPro\Modules\ThemeBuilder\Conditions\General" not found in ../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:200
Stack trace:
#0 ../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(282): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->register_condition('general')
#1 ../wp-includes/class-wp-hook.php(324): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->register_conditions('')
#2 ../wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#3 ../wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 ../public/wp-settings.php(717): do_action('wp_loaded')
#5 ../wp-config.php(84): require_once('...')
#6 ../wp-load.php(50): require_once('...')
#7 ../wp-blog-header.php(13): require_once('...')
#8 ../index.php(17): require('...')
#9 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 9 of 9JS: 2024-05-23 14:07:37 [error X 12][../wp-admin/load-scripts.php?c=1&loadchunk_0=jquery-core,jquery-migrate,utils,wp-polyfill-inert,regenerator-runtime,wp-polyfill,wp-hooks&ver=6.5.3:2:28760] Cannot read properties of undefined (reading 'value') 
JS: 2024-06-20 18:24:05 [error X 21][.. /wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.21.8:3:54583] Cannot read properties of undefined (reading 'activate') 
JS: 2024-07-06 14:53:21 [error X 1][.. /wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view7855") has already been destroyed and cannot be used. 
JS: 2024-07-06 14:53:21 [error X 1][.. /wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view7843") has already been destroyed and cannot be used. 
JS: 2024-07-06 14:53:22 [error X 1][.. /wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view9126") has already been destroyed and cannot be used. 
JS: 2024-07-06 14:53:22 [error X 1][.. /wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view9138") has already been destroyed and cannot be used. 
JS: 2024-07-07 12:31:06 [error X 3][.. /wp-content/plugins/elementor/assets/js/common-modules.min.js?ver=3.22.3:2:56144] Model.isValidChild() should be implemented, please provide 'isValidChild' functionality. 
JS: 2024-07-10 00:42:12 [error X 4][.. /wp-content/plugins/elementor/assets/js/0e842fae60df2bcb2a30.bundle.min.js:2:8001] Cannot read properties of undefined (reading 'view') 
JS: 2024-07-11 12:57:28 [error X 1][.. /wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.22.3:3:657336] Cannot read properties of undefined (reading 'isDesignable') 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	JetTabs For Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==
```
</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hi, @wpturnedup,

Thank you for reaching out! 🙏 

### ⛔ After reviewing your report we concluded this is not a bug caused by Elementor. The feature you're referring to is not yet supported.

If you think this should be an Elementor feature, please submit a new [🚀 Feature Request](https://github.com/orgs/elementor/discussions/new?category=feature-request), and we will consider it in the future if there is enough demand (votes) from other users.


Kind regards
