### ISSUE TITLE
Links Within Elementor Loop Carousel - Functionality Issues (Slide Advances Instead of Following Link)

### ISSUE THREAD

**Issue by bradymills** [elementor/elementor#28075]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

I have the following issue. 

I've created a custom post type for neighborhoods. To display these, we've created an Elementor Loop Carousel. Within the carousel, we have a couple of hyperlinks. These links should lead to their respective page; however, they are only working occasionally. They instead cause the slide to advance forward or backward. 

Any help is appreciated. 

Links with issues: "Learn More" & "Schedule a Visit"

![Screenshot 2024-07-15 at 2 54 00 PM](https://github.com/user-attachments/assets/a1141e6c-9ae5-40f6-87c7-19572bb181f8)

P.S. In adding the system report, I'm also seeing errors with System Compatibility with Elementor Pro. Not sure why.

### Steps to reproduce

1. Create Carousel Loop
2. Add Content & Links
3. Save & View
4. Click Link

### Expected behavior

1. Use Arrows or Dots to Navigate Slides
2. Click Links within Slide Content
3. Be directed to the Link URL

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
== Server Environment ==
	Operating System: Linux
	Software: nginx
	MySQL version: Percona Server (GPL), Release '28', Revision '47601f19'$ v8.0.36-28
	PHP Version: 8.2.19
	PHP Memory Limit: 512M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.5.5
	Site URL: https://WEBSITEURL.com
	Home URL: https://WEBSITEURL.com
	WP Multisite: No
	Max Upload Size: 50 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en_US
	Timezone: America/New_York
	Admin Email: myemail@myemail.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 3.1.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 6.3.3
		Author: WP Engine

	Advanced Heading for Elementor
		Version: 1.0.4
		Author: DynamicLayers

	Advanced Post Queries
		Version: 1.1.3
		Author: Shabti Kaplan

	Classic Editor
		Version: 1.6.3
		Author: WordPress Contributors

	Draw Attention Pro
		Version: 3.0.11
		Author: N Squared

	Elementor
		Version: 3.23.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.23.0
		Author: Elementor.com

	Essential Addons for Elementor
		Version: 5.9.26
		Author: WPDeveloper

	Genesis Blocks
		Version: 3.1.5
		Author: StudioPress

	ManageWP - Worker
		Version: 4.9.20
		Author: GoDaddy

	WPCode Lite
		Version: 2.1.14
		Author: WPCode

	WP Grid Builder
		Version: 2.0.6
		Author: Loïc Blascos

	WP Grid Builder - Elementor
		Version: 1.3.1
		Author: Loïc Blascos


== Must-Use Plugins ==
	Force Strong Passwords - WPE Edition
		Version: 1.8.0
		Author: Jason Cosper

	ManageWP - Worker Loader
		Version: 1.0.0
		Author: GoDaddy

	WP Engine Cache Plugin
		Version: 1.3.1
		Author: WP Engine

	WP Engine Seamless Login Plugin
		Version: 1.6.1
		Author: WP Engine

	WP Engine Security Auditor
		Version: 1.1.1
		Author: wpengine

	WP Engine System
		Version: 5.0.1
		Author: WP Engine


== Elements Usage ==
	
	archive : 2
		archive-posts : 2
		container : 3
	container : 2
		container : 8
		icon : 4
		spacer : 1
		text-editor : 5
	footer : 1
		container : 9
		form : 1
		heading : 2
		icon : 1
		image : 1
		nav-menu : 2
	header : 2
		button : 2
		container : 6
		image : 1
		nav-menu : 2
		theme-site-logo : 1
	wp-post : 8
		container : 10
		text-editor : 10
	wp-page : 1
		button : 1
		container : 25
		divider : 1
		heading : 14
		html : 1
		image : 3
		loop-carousel : 2
		loop-grid : 2
		text-editor : 3
	single-post : 3
		button : 4
		container : 78
		heading : 22
		icon : 4
		image : 6
		image-carousel : 4
		image-gallery : 1
		loop-carousel : 2
		loop-grid : 4
		shortcode : 3
		spacer : 7
		text-editor : 17
		theme-post-content : 2
		theme-post-featured-image : 1
		theme-post-title : 3
		video : 3
		wpgb-facet : 5
	loop-item : 6
		button : 2
		container : 16
		eael-flip-box : 1
		flip-box : 1
		heading : 1
		html : 1
		icon : 4
		image : 2
		post-info : 1
		spacer : 3
		text-editor : 6
		theme-post-excerpt : 1
		theme-post-featured-image : 2
		theme-post-title : 1


== Settings ==
	
	cpt_support: page
	disable_color_schemes: yes
	disable_typography_schemes: yes
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap
	load_fa4_shim: yes


== Features ==
	Custom Fonts: 2
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Improved CSS Loading: Active by default
	Inline Font Icons: Active by default
	Additional Custom Breakpoints: Active by default
	Flexbox Container: Active
	Grid Container: Active by default
	Upgrade Swiper Library: Active by default
	Nested Elements Performance: Active by default
	Optimized Control Loading: Active by default
	Optimized Markup: Inactive by default
	Plugin Onboarding: Active by default
	Default to New Theme Builder: Active by default
	Header & Footer: Active by default
	Elementor Home Screen: Active by default
	Editor Top Bar: Inactive by default
	Build with AI: Active by default
	Landing Pages: Inactive by default
	Nested Elements: Active
	Lazy Load Background Images: Active by default
	Element Caching: Active
	Link In Bio: Inactive by default
	Floating Buttons: Inactive by default
	Elementor Editor Events: Inactive by default
	Display Conditions: Active by default
	Form Submissions: Active by default
	Menu: Active
	Taxonomy Filter: Active by default
	Search: Inactive by default


== Log ==
	
PHP: showing 12 of 12PHP: 2024-06-24 12:20:12 [warning X 1][/nas/content/live/USER/wp-content/plugins/elementor/includes/managers/image.php::113] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-06-24 12:24:10 [notice X 457][/nas/content/live/USER/wp-content/plugins/elementor/includes/base/controls-stack.php::229] hexdec(): Passing null to parameter #1 ($hex_string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-06-24 19:53:35 [warning X 1][/nas/content/live/USER/wp-content/plugins/elementor/includes/conditions.php::87] Undefined array key "background_color" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-06-25 10:27:59 [notice X 20][/nas/content/live/USER/wp-content/plugins/elementor-pro/modules/screenshots/module.php::33] Function utf8_decode() is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-06-26 10:38:21 [warning X 25][/nas/content/live/USER/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-image.php::40] Undefined array key 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-06-26 10:41:17 [warning X 25][/nas/content/live/USER/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::179] Undefined array key "editor_post_id" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-06-26 14:22:06 [warning X 31][/nas/content/live/USER/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key "condition_type" [array (
  'trace' => '
#0: /nas/content/live/USER/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /nas/content/live/USER/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /nas/content/live/USER/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /nas/content/live/USER/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2024-07-15 14:43:22 [error X 1][/nas/content/live/USER/wp-content/plugins/elementor/core/modules-manager.php::53] Uncaught Error: Class "Elementor\Modules\ConversionCenter\Module" not found in /nas/content/live/USER/wp-content/plugins/elementor/core/modules-manager.php:53
Stack trace:
#0 /nas/content/live/USER/wp-content/plugins/elementor/includes/plugin.php(730): Elementor\Core\Modules_Manager->__construct()
#1 /nas/content/live/USER/wp-content/plugins/elementor/includes/plugin.php(647): Elementor\Plugin->init_components()
#2 /nas/content/live/USER/wp-includes/class-wp-hook.php(324): Elementor\Plugin->init('')
#3 /nas/content/live/USER/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#4 /nas/content/live/USER/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#5 /nas/content/live/USER/wp-settings.php(695): do_action('init')
#6 /nas/content/live/USER/wp-config.php(119): require_once('/nas/content/li...')
#7 /nas/content/live/USER/wp-load.php(50): require_once('/nas/content/li...')
#8 /nas/content/live/USER/wp-admin/admin-ajax.php(22): require_once('/nas/content/li...')
#9 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-07-15 14:43:25 [error X 1][/nas/content/live/USER/wp-content/plugins/elementor/core/modules-manager.php::53] Uncaught Error: Class "Elementor\Modules\ConversionCenter\Module" not found in /nas/content/live/USER/wp-content/plugins/elementor/core/modules-manager.php:53
Stack trace:
#0 /nas/content/live/USER/wp-content/plugins/elementor/includes/plugin.php(730): Elementor\Core\Modules_Manager->__construct()
#1 /nas/content/live/USER/wp-content/plugins/elementor/includes/plugin.php(647): Elementor\Plugin->init_components()
#2 /nas/content/live/USER/wp-includes/class-wp-hook.php(324): Elementor\Plugin->init('')
#3 /nas/content/live/USER/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#4 /nas/content/live/USER/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#5 /nas/content/live/USER/wp-settings.php(695): do_action('init')
#6 /nas/content/live/USER/wp-config.php(119): require_once('/nas/content/li...')
#7 /nas/content/live/USER/wp-load.php(50): require_once('/nas/content/li...')
#8 /nas/content/live/USER/wp-admin/admin.php(34): require_once('/nas/content/li...')
#9 /nas/content/live/USER/wp-admin/plugins.php(10): require_once('/nas/content/li...')
#10 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-07-15 14:43:47 [error X 1][/nas/content/live/USER/wp-content/plugins/elementor-pro/core/modules-manager.php::84] Uncaught Error: Class "\ElementorPro\Modules\ConversionCenter\Module" not found in /nas/content/live/USER/wp-content/plugins/elementor-pro/core/modules-manager.php:84
Stack trace:
#0 /nas/content/live/USER/wp-content/plugins/elementor-pro/plugin.php(361): ElementorPro\Core\Modules_Manager->__construct()
#1 /nas/content/live/USER/wp-includes/class-wp-hook.php(324): ElementorPro\Plugin->on_elementor_init('')
#2 /nas/content/live/USER/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#3 /nas/content/live/USER/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /nas/content/live/USER/wp-content/plugins/elementor/includes/plugin.php(658): do_action('elementor/init')
#5 /nas/content/live/USER/wp-includes/class-wp-hook.php(324): Elementor\Plugin->init('')
#6 /nas/content/live/USER/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#7 /nas/content/live/USER/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#8 /nas/content/live/USER/wp-settings.php(695): do_action('init')
#9 /nas/content/live/USER/wp-config.php(119): require_once('/nas/content/li...')
#10 /nas/content/live/USER/wp-load.php(50): require_once('/nas/content/li...')
#11 /nas/content/live/USER/wp-admin/admin-ajax.php(22): require_once('/nas/content/li...')
#12 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-07-15 14:43:49 [error X 1][/nas/content/live/USER/wp-content/plugins/elementor-pro/core/modules-manager.php::84] Uncaught Error: Class "\ElementorPro\Modules\ConversionCenter\Module" not found in /nas/content/live/USER/wp-content/plugins/elementor-pro/core/modules-manager.php:84
Stack trace:
#0 /nas/content/live/USER/wp-content/plugins/elementor-pro/plugin.php(361): ElementorPro\Core\Modules_Manager->__construct()
#1 /nas/content/live/USER/wp-includes/class-wp-hook.php(324): ElementorPro\Plugin->on_elementor_init('')
#2 /nas/content/live/USER/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#3 /nas/content/live/USER/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /nas/content/live/USER/wp-content/plugins/elementor/includes/plugin.php(658): do_action('elementor/init')
#5 /nas/content/live/USER/wp-includes/class-wp-hook.php(324): Elementor\Plugin->init('')
#6 /nas/content/live/USER/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#7 /nas/content/live/USER/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#8 /nas/content/live/USER/wp-settings.php(695): do_action('init')
#9 /nas/content/live/USER/wp-config.php(119): require_once('/nas/content/li...')
#10 /nas/content/live/USER/wp-load.php(50): require_once('/nas/content/li...')
#11 /nas/content/live/USER/wp-blog-header.php(13): require_once('/nas/content/li...')
#12 /nas/content/live/USER/index.php(17): require('/nas/content/li...')
#13 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-07-15 14:43:50 [error X 2][/nas/content/live/USER/wp-content/plugins/elementor-pro/core/modules-manager.php::84] Uncaught Error: Class "\ElementorPro\Modules\ConversionCenter\Module" not found in /nas/content/live/USER/wp-content/plugins/elementor-pro/core/modules-manager.php:84
Stack trace:
#0 /nas/content/live/USER/wp-content/plugins/elementor-pro/plugin.php(361): ElementorPro\Core\Modules_Manager->__construct()
#1 /nas/content/live/USER/wp-includes/class-wp-hook.php(324): ElementorPro\Plugin->on_elementor_init('')
#2 /nas/content/live/USER/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#3 /nas/content/live/USER/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /nas/content/live/USER/wp-content/plugins/elementor/includes/plugin.php(658): do_action('elementor/init')
#5 /nas/content/live/USER/wp-includes/class-wp-hook.php(324): Elementor\Plugin->init('')
#6 /nas/content/live/USER/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#7 /nas/content/live/USER/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#8 /nas/content/live/USER/wp-settings.php(695): do_action('init')
#9 /nas/content/live/USER/wp-config.php(119): require_once('/nas/content/li...')
#10 /nas/content/live/USER/wp-load.php(50): require_once('/nas/content/li...')
#11 /nas/content/live/USER/wp-admin/admin.php(34): require_once('/nas/content/li...')
#12 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 9 of 9JS: 2024-06-24 20:17:19 [error X 14][https://WEBSITEURL.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.22.2:3:825635] Cannot read properties of undefined (reading 'localized') 
JS: 2024-06-25 16:09:54 [error X 9][https://WEBSITEURL.com/wp-admin/load-scripts.php?c=1&loadchunk_0=jquery-core,jquery-migrate,jquery-ui-core,utils,moxiejs,plupload&ver=6.5.4:2:28760] Cannot read properties of undefined (reading 'value') 
JS: 2024-06-26 02:00:26 [error X 4][https://WEBSITEURL.com/wp-content/plugins/elementor/assets/js/0e842fae60df2bcb2a30.bundle.min.js:2:7789] Cannot read properties of null (reading 'dataset') 
JS: 2024-06-26 06:02:31 [error X 1][https://WEBSITEURL.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.22.2:3:941844] elementorFrontend is not defined 
JS: 2024-07-01 23:49:44 [error X 2][https://WEBSITEURL.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.22.3:3:1176313] Cannot read properties of null (reading 'getBoundingClientRect') 
JS: 2024-07-02 00:05:50 [error X 2][https://WEBSITEURL.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.22.3:3:431223] Cannot read properties of null (reading 'history') 
JS: 2024-07-09 04:58:15 [error X 2][https://WEBSITEURL.com/wp-admin/load-scripts.php?c=1&loadchunk_0=jquery-core,jquery-migrate,jquery-ui-core,utils,wp-polyfill-inert,regenerator-runtime,wp-polyfill,wp-hooks&ver=6.5.5:2:28767] undefined is not an object (evaluating 'c[0].value') 
JS: 2024-07-09 16:42:53 [error X 3][https://WEBSITEURL.com/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.22.3:2:11814] Cannot read properties of undefined (reading 'params') 
JS: 2024-07-14 21:56:26 [error X 1][https://WEBSITEURL.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.22.3:3:618437] Cannot read properties of null (reading 'id') 

Log: showing 15 of 152024-06-26 10:23:01 [info] elementor::elementor_updater Started 
2024-06-26 10:23:01 [info] Elementor/Upgrades - _on_each_version Start  
2024-06-26 10:23:02 [info] Elementor/Upgrades - _on_each_version Finished 
2024-06-26 10:23:02 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.22.2',
  'to' => '3.22.3',
)]
2024-06-26 10:23:02 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.22.2',
  'to' => '3.22.3',
)]
2024-07-15 14:43:31 [info] elementor::elementor_updater Started 
2024-07-15 14:43:31 [info] Elementor/Upgrades - _on_each_version Start  
2024-07-15 14:43:31 [info] Elementor/Upgrades - _on_each_version Finished 
2024-07-15 14:43:31 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.22.3',
  'to' => '3.23.1',
)]
2024-07-15 14:43:31 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.22.3',
  'to' => '3.23.1',
)]
2024-07-15 14:43:58 [info] elementor-pro::elementor_pro_updater Started 
2024-07-15 14:43:58 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-07-15 14:43:58 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-07-15 14:43:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.22.1',
  'to' => '3.23.0',
)]
2024-07-15 14:43:58 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.22.1',
  'to' => '3.23.0',
)]



== Elementor - Compatibility Tag ==
	
	Advanced Heading for Elementor: Incompatible
	Elementor Pro: Incompatible
	Essential Addons for Elementor: Incompatible
	WP Grid Builder - Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==
	
	Essential Addons for Elementor: Incompatible
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by Musab911** [comment]
Hi, I was also facing the same issue and the only solution I figured out was that you'll have to go to the link settings and have to select "Open in new window" option, It'll work fine.

**Comment by fernando-partridge** [comment]
I have the same problem. Once you have tried to click for the first time and the carousel has moved one item across, it is sometimes possible to successfully click a loop item button/link. It's not good though.

**Comment by enuzzo** [comment]
Hello. Same problem here: Elementor Pro 3.25.2 / Elementor 3.25.4.

![SCR-20241111-sdhe](https://github.com/user-attachments/assets/3036664d-8cb9-46da-be4a-0c81fd694c6b)

**Comment by BLB94** [comment]
I was also experiencing this issue and got it to work with the following code:

`jQuery(document).ready(function ($) {
    $(window).on('elementor/frontend/init', function () {
        elementorFrontend.hooks.addAction('frontend/element_ready/global', function ($scope) {
            // Use a more targeted selector to avoid affecting unrelated elements
            const loopCarouselSwiper = document.querySelector('.swiper');

            if (loopCarouselSwiper && loopCarouselSwiper.swiper) {
                const swiperInstance = loopCarouselSwiper.swiper;

                // Disable touch/mouse swipe interactions
                if (swiperInstance.allowTouchMove) {
                    swiperInstance.allowTouchMove = false;
                }

                // Ensure clicks are not blocked
                if (!swiperInstance.allowClick) {
                    swiperInstance.allowClick = true;
                }

                // Avoid redundant updates
                if (swiperInstance.params.preventClicks || swiperInstance.params.preventClicksPropagation) {
                    swiperInstance.params.preventClicks = false;
                    swiperInstance.params.preventClicksPropagation = false;
                    swiperInstance.update(); // Update only if parameters are changed
                }
            }
        });
    });
});
`

**Comment by Foureveur** [comment]
I'm getting the same problem but i didn't manage to make it work. Where did you add the code ?

**Comment by design219** [comment]
> I'm getting the same problem but i didn't manage to make it work. Where did you add the code ?

I used the Code Snippets plugin. Weird thing is, this worked on one site, but I have another site with the same issue and it doesn't work there. I'm not a coder so not sure how to troubleshoot further. Good luck!

**Comment by franzuu** [comment]
Same issue here. Tried the code hack suggested here, but no success. Any hope for official fix?

**Comment by antonio-guido** [comment]
Hi everyone,

I managed to work around the “first-click does nothing” issue on desktop mice by:

1. Waiting for each Swiper instance to initialize.
2. Disabling swipe and the default `slideToClickedSlide` behavior on pointer: fine (mouse) devices.
3. Installing a global `click` listener in capture phase that intercepts any click on `.swiper-slide`, prevents Swiper from handling it, and immediately navigates to the first `[href]` inside the slide.

Here’s the minimal script I used (insert into your page footer or Custom Code):

```html
<script>
document.addEventListener('DOMContentLoaded', function () {
  // 1) Disable swipe & slide-to-click on desktop
  function fixCarousels() {
    document.querySelectorAll('.swiper-initialized').forEach(function (container) {
      if (container._clickFixed) return;

      var swiper = container.swiper;
      if (!swiper) return;

      if (window.matchMedia('(pointer: fine)').matches) {
        swiper.allowTouchMove = false;
        swiper.params.slideToClickedSlide = false;
      }
      swiper.params.preventClicks = false;
      swiper.params.preventClicksPropagation = false;
      swiper.update();

      container._clickFixed = true;
    });
  }

  var interval = setInterval(function () {
    fixCarousels();
    if (document.querySelectorAll('.swiper-initialized[data-click-fixed]').length) {
      clearInterval(interval);
    }
  }, 200);

  // 2) Intercept click in capture phase and force navigation
  document.addEventListener('click', function (e) {
    if (!window.matchMedia('(pointer: fine)').matches) return;
    var slide = e.target.closest('.swiper-slide');
    if (!slide) return;

    var linkEl = slide.querySelector('[href]');
    if (!linkEl) return;

    e.preventDefault();
    e.stopPropagation();
    window.location.href = linkEl.getAttribute('href');
  }, true);
});
</script>
```

This ensures that on desktop with a mouse, the very first click always opens the link and the carousel never moves itself. Hope it helps!

**Comment by Oboquin** [comment]
The code worked for me, thank you! I used the code snippet plugin in elementor, created new code and selected Javascriot Snippet. pasted the code as it is and worked like magic.
