### ISSUE TITLE
⛔ 🚀 🧩 Using the Query Filter in combination with a Ajax call does not render any posts in the Loop Grid widget

### ISSUE THREAD

**Issue by pingram3541** [elementor/elementor#28295]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Following the guide lines here -> https://developers.elementor.com/docs/hooks/custom-query-filter/, I am using an ajax method to pass a search term $string to this filter elementor/query/query_by_name

Here is the query modification:
```php
function my_name_query( $query ) {
    $search_string = get_field( 'selected_name' ); //write_log($selected_name); <- good!
    $meta_query = $query->get( 'meta_query' );
    if ( ! $meta_query ) {
        $meta_query = [];
    }
    $meta_query = [
        'relation' => 'OR',
    ];
    $meta_query[] = [
        'key' => 'first_name',
        'value' => $search_string,
        'compare' => 'LIKE',
    ];
    $meta_query[] = [
        'key' => 'last_name',
        'value' => $search_string,
        'compare' => 'LIKE',
    ];
    $query->set( 'post_type', [ 'my-post-type' ] );
    $query->set( 'meta_query', $meta_query );

    //write_log($query);
}
add_action( 'elementor/query/query_by_name', 'my_name_query' );
```

This yields no results on the front end. 

" seems we can’t find any certified leaders based on the criteria you are looking for. Please try again."

I've verified my search $string is passed via debug logging as well. Additionally when I log out the query object I can see my modifications to the query are indeed showing within the query object.

So I write my own query using the same exact parameters and it yields results:

```php
$search_string = 'Bob';
$meta_query = [
    'relation' => 'OR',
];
$meta_query[] = [
    'key' => 'first_name',
    'value' => $search_string,
    'compare' => 'LIKE',
];
$meta_query[] = [
    'key' => 'last_name',
    'value' => $search_string,
    'compare' => 'LIKE',
];
$users = new WP_User_Query( array(
    'post_type' => 'my-post-type',
    'meta_query' => $meta_query
) );
_dump($users);
```
The results are rendered w/ same exact query options.

So then I tried the search and search_columns method using '*' wildcards, and it results in all posts rendering irregardless of a match (irregardless of using wildcards or not):

```php
function my_name_query( $query ) {
    $search_string = get_field( 'selected_name' ); write_log($selected_name);
    $search_query = [
        'user_nicename',
        'display_name'
    ];
    $query->set( 'post_type', [ 'my-post-type' ] );
    $query->set( 'search', "*{$search_string}*" );
    //$query->set( 'search', $search_string );
    $query->set( 'search_columns', $search_query );
    
    write_log($query);
}
add_action( 'elementor/query/query_by_name', 'my_name_query' );
```

Again, I check the query object after being modified and it shows the same structure and modifications that my successful manual query uses and renders correctly. The Elementor query filter does not render any results.

Here is the manual query that works just fine, again, logging the query object and I see the modifications are the same.
```php
$search_string = 'Joy';
$users = new WP_User_Query( array(
    'post_type' => 'my-post-type',
    'search'  => "*{$search_string}*",
    'search_columns' => [
        'user_nicename',
        'display_name'
    ]
) );
_dump($users);
```

Here is an example of the query object after being modified via my `elementor/query/query_by_name` filter:

<details>
<summary>Click to reveal</summary>

````txt


[05-Aug-2024 23:25:51 UTC] WP_Query Object
(
    [query] => Array
        (
            [posts_per_page] => 12
            [paged] => 1
            [has_custom_pagination] => 1
            [post_status] => publish
            [post_type] => post
            [orderby] => post_date
            [order] => asc
            [ignore_sticky_posts] => 1
            [post__not_in] => Array
                (
                )

            [date_query] => Array
                (
                )

        )

    [query_vars] => Array
        (
            [posts_per_page] => 12
            [paged] => 1
            [has_custom_pagination] => 1
            [post_status] => publish
            [post_type] => Array
                (
                    [0] => my-post-type
                )

            [orderby] => title
            [order] => ASC
            [ignore_sticky_posts] => 1
            [post__not_in] => Array
                (
                )

            [date_query] => Array
                (
                )

            [error] => 
            [m] => 
            [p] => 0
            [post_parent] => 
            [subpost] => 
            [subpost_id] => 
            [attachment] => 
            [attachment_id] => 0
            [name] => 
            [pagename] => 
            [page_id] => 0
            [second] => 
            [minute] => 
            [hour] => 
            [day] => 0
            [monthnum] => 0
            [year] => 0
            [w] => 0
            [category_name] => 
            [tag] => 
            [cat] => 
            [tag_id] => 
            [author] => 
            [author_name] => 
            [feed] => 
            [tb] => 
            [meta_key] => 
            [meta_value] => 
            [preview] => 
            [s] => 
            [sentence] => 
            [title] => 
            [fields] => 
            [menu_order] => 
            [embed] => 
            [category__in] => Array
                (
                )

            [category__not_in] => Array
                (
                )

            [category__and] => Array
                (
                )

            [post__in] => Array
                (
                )

            [post_name__in] => Array
                (
                )

            [tag__in] => Array
                (
                )

            [tag__not_in] => Array
                (
                )

            [tag__and] => Array
                (
                )

            [tag_slug__in] => Array
                (
                )

            [tag_slug__and] => Array
                (
                )

            [post_parent__in] => Array
                (
                )

            [post_parent__not_in] => Array
                (
                )

            [author__in] => Array
                (
                )

            [author__not_in] => Array
                (
                )

            [search_columns] => Array
                (
                )

            [meta_query] => Array
                (
                    [relation] => OR
                    [0] => Array
                        (
                            [key] => first_name
                            [value] => Bob
                            [compare] => LIKE
                        )

                    [1] => Array
                        (
                            [key] => last_name
                            [value] => Bob
                            [compare] => LIKE
                        )

                )

        )

    [tax_query] => WP_Tax_Query Object
        (
            [queries] => Array
                (
                )

            [relation] => AND
            [table_aliases:protected] => Array
                (
                )

            [queried_terms] => Array
                (
                )

            [primary_table] => 
            [primary_id_column] => 
        )

    [meta_query] => 
    [date_query] => 
    [post_count] => 0
    [current_post] => -1
    [before_loop] => 1
    [in_the_loop] => 
    [comment_count] => 0
    [current_comment] => -1
    [found_posts] => 0
    [max_num_pages] => 0
    [max_num_comment_pages] => 0
    [is_single] => 
    [is_preview] => 
    [is_page] => 
    [is_archive] => 
    [is_date] => 
    [is_year] => 
    [is_month] => 
    [is_day] => 
    [is_time] => 
    [is_author] => 
    [is_category] => 
    [is_tag] => 
    [is_tax] => 
    [is_search] => 
    [is_feed] => 
    [is_comment_feed] => 
    [is_trackback] => 
    [is_home] => 
    [is_privacy_policy] => 
    [is_404] => 
    [is_embed] => 
    [is_paged] => 
    [is_admin] => 1
    [is_attachment] => 
    [is_singular] => 
    [is_robots] => 
    [is_favicon] => 
    [is_posts_page] => 
    [is_post_type_archive] => 
    [query_vars_hash:WP_Query:private] => eb00de1ca754988e8b8484af8aee70b0a
    [query_vars_changed:WP_Query:private] => 
    [thumbnails_cached] => 
    [allow_query_attachment_by_filename:protected] => 
    [stopwords:WP_Query:private] => 
    [compat_fields:WP_Query:private] => Array
        (
            [0] => query_vars_hash
            [1] => query_vars_changed
        )

    [compat_methods:WP_Query:private] => Array
        (
            [0] => init_query_flags
            [1] => parse_tax_query
        )

)

````

</details>

### Steps to reproduce

1. Create an input and button to pass a search string to our ajax handler
2. Back end ajax handler passes search string to function that re-renders the post grid widget (by widget id), passing the custom search query as well.
3. Custom query filter `elementor/query/query_by_name` retrieves search string and modifies the query as outlined above.

### Expected behavior

1. Type in anything in the search field and hit submit
2. If matches, render matches

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt


== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.62 (Debian)
	MySQL version: mariadb.org binary distribution v10.5.25
	PHP Version: 7.4.33
	PHP Memory Limit: 3600M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 200M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected
== WordPress Environment ==
	Version: 6.6.1
	Site URL: https://mysite.com
	Home URL: https://mysite.com
	WP Multisite: No
	Max Upload Size: 200 MB
	Memory limit: 40M
	Max Memory limit: 3600M
	Permalink Structure: /%postname%/
	Language: en_US
	Timezone: America/Phoenix
	Debug Mode: Active
== Theme ==
	Name: Custom Child Theme
	Version: 2.0.0
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 3.1.0
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
== Active Plugins ==

	ACF Content Analysis for Yoast SEO
		Version: 3.1
		Author: Thomas Kräftner, ViktorFroberg, marol87, pekz0r, angrycreative, Team Yoast

	Advanced Custom Fields PRO
		Version: 6.3.5
		Author: WP Engine

	Advanced Custom Fields PRO Extra
		Version: 1.0.0
		Author: Tellatek

	Breeze
		Version: 2.1.11
		Author: Cloudways

	Elementor
		Version: 3.23.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.23.3
		Author: Elementor.com

	GDPR Cookie Consent
		Version: 2.3.9
		Author: WebToffee

	Jetpack
		Version: 13.6
		Author: Automattic

	MalCare WordPress Security Plugin - Malware Scanner, Cleaner, Security Firewall
		Version: 5.65
		Author: MalCare Security

	Object Cache Pro
		Version: 1.21.2
		Author: Rhubarb Group

	Preview E-mails for WooCommerce
		Version: 2.2.13
		Author: Digamber Pradhan


	WooCommerce
		Version: 9.1.4
		Author: Automattic

	WooCommerce.com Update Manager
		Version: 1.0.3
		Author: Automattic

	WooCommerce AutoComplete Orders
		Version: 1.0.0
		Author: Tellatek

	WooCommerce DiscipleMedia Integration
		Version: 1.0.0
		Author: Philip Ingram and Sirena Bernal

	WooCommerce Mailchimp Pro
		Version: 2.4.6
		Author: Saint Systems

	WooCommerce PayPal Payments
		Version: 2.8.2
		Author: WooCommerce

	WooPayments
		Version: 8.0.1
		Author: WooCommerce

	WPC Frequently Bought Together for WooCommerce
		Version: 7.2.0
		Author: WPClever


	WP WooCommerce Mailchimp
		Version: 2.4.12
		Author: Saint Systems

	Yoast SEO
		Version: 23.1
		Author: Team Yoast


== Features ==
	Custom Fonts: 4
	Custom Icons: 0

== Integrations ==
	
	recaptcha: Active
	recaptcha_v3: Active
	woocommerce: Active


== Elementor Experiments ==
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Additional Custom Breakpoints: Active
	Flexbox Container: Active
	Grid Container: Active
	Upgrade Swiper Library: Active
	Nested Elements Performance: Active by default
	Optimized Control Loading: Active
	Optimized Markup: Inactive by default
	Plugin Onboarding: Active by default
	Default to New Theme Builder: Active
	Header & Footer: Active by default
	Elementor Home Screen: Active by default
	Editor Top Bar: Active
	Build with AI: Active
	Landing Pages: Active
	Nested Elements: Active
	Lazy Load Background Images: Active
	Pages Panel: Inactive by default
	Element Caching: Inactive by default
	Link In Bio: Inactive by default
	Floating Buttons: Inactive by default
	Elementor Editor Events: Inactive by default
	Display Conditions: Active
	Form Submissions: Active
	Menu: Active
	Taxonomy Filter: Active
	Search: Inactive by default

== Log ==
	
Log: showing 20 of 342024-08-05 13:30:08 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.1',
  'to' => '3.23.3',
)]
2024-08-05 13:30:10 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.1',
  'to' => '3.23.3',
)]
2024-08-05 13:30:14 [info] elementor-pro::elementor_pro_updater Started 
2024-08-05 13:30:15 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-08-05 13:30:15 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-08-05 13:30:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.0',
  'to' => '3.23.2',
)]
2024-08-05 13:30:18 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.0',
  'to' => '3.23.2',
)]
2024-08-05 13:30:18 [info] elementor-pro::elementor_pro_updater Started 
2024-08-05 13:30:18 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-08-05 13:30:18 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-08-05 13:30:18 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.0',
  'to' => '3.23.2',
)]
2024-08-05 13:31:31 [info] elementor-pro::elementor_pro_updater Started 
2024-08-05 13:31:31 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-08-05 13:31:31 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-08-05 13:31:31 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.2',
  'to' => '3.23.3',
)]
2024-08-05 13:31:31 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.2',
  'to' => '3.23.3',
)]
2024-08-05 13:33:46 [info] elementor::elementor_updater Started 
2024-08-05 13:33:46 [info] Elementor/Upgrades - _on_each_version Start  
2024-08-05 13:33:46 [info] Elementor/Upgrades - _on_each_version Finished 
2024-08-05 13:33:46 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.3',
  'to' => '3.23.4',
)]

PHP: showing 7 of 7PHP: 2024-07-16 21:34:21 [notice X 42][../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined index: condition_type [array (
  'trace' => '
#0: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: ../wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2024-07-18 18:44:26 [error X 4][../wp-content/plugins/elementor/core/documents-manager.php::515] Uncaught Error: Call to a member function is_built_with_elementor() on bool in ../wp-content/plugins/elementor/core/documents-manager.php:515
Stack trace:
#0 [internal function]: Elementor\Core\Documents_Manager->ajax_save()
#1 ../wp-content/plugins/elementor/core/common/modules/ajax/module.php(176): call_user_func()
#2 ../wp-includes/class-wp-hook.php(324): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#3 ../wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#4 ../wp-includes/plugin.php(517): WP_Hook->do_action()
#5 ../wp-admin/admin-ajax.php(192): do_action()
#6 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hello @pingram3541!

Thank you for reaching out! 🙏 

I'm afraid I might be missing something here. Just to make sure, can you clarify a few points for me?

1. Please clarify what exactly is your goal. Are you trying to create something like an Ajax (faceted) search?
2. Please, share your entire custom code, including the Ajax handler calls you're making to update the Loop Grid query on the frontend.
3. Please clarify from where exactly you are fetching the `$search_string`. As the `get_field()` function from ACF will fetch the value from the field in the database **for each post _<ins>before the query is loaded</ins>_** (just like `pre_get_posts()` method works). If there is nothing to be fetched, then your filter will return nothing. 

If the answer to the first question is yes, please note that the Query Filter was not created to be used in the way you are using it (Ajax search), and there are no mechanisms in place to listen to ajax updates in this filter. It works exactly as `pre_get_posts()` before the page is rendered.

If this is indeed the case, we recommend using the new Search Widget instead, which was build for this exact purpose.
Announcement: https://elementor.com/blog/elementor-323-ajax-search-floating-buttons-link-in-bio/
Documentation: https://elementor.com/help/search-widget/

Kind regards

**Comment by pingram3541** [comment]
Hello thank you Nicholas.

The goal is a Certified User Directory page using a Loop Grid widget that can display ACF field meta data per WP User and with the ability to filter the grid based on User ACF field meta such as region or first/last name, nickname or display name.

I realize now why the query is failing.

The Posts Grid does NOT perform a User query but rather it performs a Posts query. **It would be great if we could somehow tell the widget to perform a certain "type" of query such as User vs Post. Maybe we can revise this ticket to allow this?**

My workaround is a bit over the top.

1. Tapping into the "User" WordPress "crud" so that identical CPT for each "certified" User is created, updated or removed, passing along identical custom field and user field data from the user to the paired cpt.
2. Create a Loop Grid widget w/ a custom query ID which sets the custom post type (this works but not sure why I can't do this via the GUI, my CPT are created via ACF Pro, but is not listed in any Loop Grid widget options, yes this post type is Elementor builder enabled in back end)
3. Create a Search Field and Button and an ajax mechanism to post the string to php admin-ajax.php. HTML widget + script enqueue.
4. Create ajax php handler to receive the post string from the front end submission and save to the database for later retrieval (milliseconds later, I realize this creates a race condition, we are not expecting a ton of traffic to this page)
5. Also pass the page post ID and the widget instance ID + nonce and search/region terms via ajax to the php handler which then reinitializes the Loop Grid widget using the instance id, grabs it's settings object and changes the custom query ID to either the initial cpt (all certified users), region query or name search query.
6. Create 3 custom Loop Grid query_id action/functions such as 'elementor/query/scl_by_name' and within this modify the Loop Grid posts query after grabbing the posted search term(s) from the database.
7. Reinitialize the widget and re-render it again using the new settings and capture the rendered html and pass back to our ajax success.
8. Fade out/in Loop Grid container after replacing the inner contents w/ the newly rendered Loop Grid widget html.
9. Via javascript rebuild pagination nav links w/ correct urls, for some reason they include the admin-ajax.php in the url.
10. Voila! Everything works, except the first pagination click results in a full page load because the click event handlers are missing and I can't find how to reinit them (help here would be extremely appreciated). Future pagination link clicks work just fine as the page load seems to add proper click event handlers.
11. So Yes, filter by ajax DOES work, just needs to be a little more accessible and w/ pagination click event handlers working.

Again, thanks for being an ear and hearing my challenges. Ultimately being able to list users in a grid for a directory would be nice to have as a native capability of the Loop Grid widget. Or maybe duplicating this module entirely and work out a User Grid widget to be available in the toolset.

Cheers!

**Comment by nicholaszein** [comment]
Hi @pingram3541!

Thank you for your detailed explanation, and apologies for the delay! 🙏 

I understand now what you were trying to achieve. Unfortunately, we only support querying Posts, CPTs, and Taxonomies. We do have plans to improve our Query Builder in the future, and include other types of content, but for the time being, this is not a priority.

I suggest creating a shortcode for your case, as what you are trying to do is too complex to be something that would be worth pursuing by "hacking" your way around our components to achieve what you want (for the lack of a better word). I hope you can understand that I mean well.

If you think this should be an Elementor feature, please submit a new [🚀 Feature Request](https://github.com/orgs/elementor/discussions/new?category=feature-request), and we will consider it in the future if there is enough demand (votes) from other users.

I'm closing this issue as it is not a bug.

Kind regards
