### ISSUE TITLE
LOOP CAROUSEL LAYOUT (IN SIDEBAR TEMPLATE) DISPLAYED INCORRECTLY ON POST PAGES

### ISSUE THREAD

**Issue by ivanverona1** [elementor/elementor#28324]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Hi everyone. I got this problem and i've tried letterally everything but really nothing seems work to solve it.
In the sidebar existing on my project, i've created a loop carousel that display post queried in a custom post type.
If the sidebar is opened by the homepage or any other archive page, the loop carousel it's displayed correctly, if it get opened by any post page, the loop carousel is showed larger than it should has to be. I've tried letterally everything. Disabling every plugin, restoring, everything. 
I would be really glad if somebody want to help me to sort it out because i'm stucking on it.
Thanks in advance.

### Steps to reproduce

1. Open the sidebar clicking on the right top corner of the page
2. Scroll the slides\
3. Try this by homepage, archive pages and post pages

### Expected behavior

1. The slides should keep the same width in every part of the project

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v8.0.36-28
	PHP Version: 7.4.33
	PHP Memory Limit: 768M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.6.1
	Site URL: https://onlygamers.it
	Home URL: https://onlygamers.it
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 512M
	Max Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: it_IT
	Timezone: Europe/Rome
	Admin Email: ivaninter1@onlygamers.it
	Debug Mode: Inactive

== Theme ==
	Name: Astra Child
	Version: 3.5.0.1680512088
	Author: Brainstorm Force
	Child Theme: Yes
	Parent Theme Name: Astra
	Parent Theme Version: 4.7.3
	Parent Theme Author: Brainstorm Force

== User ==
	Role: administrator
	WP Profile lang: it-IT
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 Edg/127.0.0.0

== Active Plugins ==
	Admin Columns Pro
		Version: 6.4.10
		Author: AdminColumns.com

	Adminimize
		Version: 1.11.11
		Author: WP Media

	Admin Menu Editor Pro
		Version: 2.26
		Author: Janis Elsts

	Advanced Custom Fields: Extended PRO
		Version: 0.9.0.6
		Author: ACF Extended

	Advanced Custom Fields PRO
		Version: 6.3.4
		Author: WP Engine

	Advanced Database Cleaner PRO
		Version: 3.2.9
		Author: Younes JFR.

	Advanced Editor Tools
		Version: 5.9.2
		Author: Automattic

	Advanced Post Queries
		Version: 1.1.3
		Author: Shabti Kaplan

	Asset CleanUp Pro: Page Speed Booster
		Version: 1.2.5.4
		Author: Gabe Livan

	Auto Image Attributes From Filename With Bulk Updater
		Version: 4.4
		Author: Arun Basil Lal

	Auto Image Attributes Pro
		Version: 4.5
		Author: Arun Basil Lal

	Bulk Move
		Version: 1.3.0
		Author: Sudar

	Child Theme Configurator
		Version: 2.6.6
		Author: Lilaea Media

	Classic Editor
		Version: 1.6.4
		Author: WordPress Contributors

	Copy Move posts
		Version: 1.6
		Author: Ujjaval Jani

	Custom Icons for Elementor
		Version: 0.3.1
		Author: Michael Bourne

	Custom Post Type UI
		Version: 1.17.1
		Author: WebDevStudios

	Disable Admin Notices Individually
		Version: 1.3.2
		Author: Creative Motion <info@cm-wp.com>

	Disable Admin Notices premium
		Version: 1.1.0
		Author: CreativeMotion <wordpress.webraftic@gmail.com>

	Easy remove item menu
		Version: 1.0.6
		Author: Camilo

	Easy Theme and Plugin Upgrades
		Version: 2.0.2
		Author: Chris Jean

	Easy Updates Manager Premium
		Version: 9.0.18
		Author: Easy Updates Manager Team

	Ele Custom Skin
		Version: 3.1.7
		Author: Dudaster.com

	Ele Custom Skin Pro
		Version: 3.2.4
		Author: Dudaster.com

	Elementor
		Version: 3.23.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.23.3
		Author: Elementor.com

	FileBird Pro
		Version: 6.3.3
		Author: Ninja Team

	Hide titles on hover
		Version: 0.0.5
		Author: Jose Mortellaro

	JetElements For Elementor
		Version: 2.6.20
		Author: Crocoblock

	JetEngine
		Version: 3.5.3
		Author: Crocoblock

	JetSearch
		Version: 3.5.2
		Author: Crocoblock

	JetSmartFilters
		Version: 3.5.3
		Author: Crocoblock

	Lazy Load Control For Elementor
		Version: 0.0.3
		Author: Jose Mortellaro

	Make Column Clickable Elementor
		Version: 1.4.0
		Author: Fernando Acosta

	Media Cleaner (Pro)
		Version: 6.7.8
		Author: Jordy Meow

	Media File Renamer: Rename for better SEO (AI-Powered) (Pro)
		Version: 5.9.4
		Author: Jordy Meow

	New User Approve
		Version: 2.6.1
		Author: WPExpertsio

	Permalink Manager Pro
		Version: 2.4.4
		Author: Maciej Bis

	PowerPack Pro for Elementor
		Version: 2.10.24
		Author: Team IdeaBox - PowerPack Elements

	Premium Addons for Elementor
		Version: 4.10.39
		Author: Leap13

	Smoother
		Version: 2.0.3
		Author: Merkulove

	TaxoPress
		Version: 3.23.0
		Author: TaxoPress

	Term Taxonomy Converter
		Version: 1.2
		Author: Dhanendran

	Unlimited Elementor Inner Sections By BoomDevs
		Version: 1.0.6
		Author: BoomDevs

	Unlimited Elements for Elementor (Premium)
		Version: 1.5.114
		Author: Unlimited Elements

	UpdraftPlus - Backup/Restore
		Version: 2.24.4.26
		Author: UpdraftPlus.Com, DavidAnderson

	Username Changer
		Version: 3.2.2
		Author: Widgit Team

	User Profile Picture
		Version: 2.6.3
		Author: Cozmoslabs

	User Role Editor Pro
		Version: 4.64.2
		Author: Vladimir Garagulia

	Wordfence Security
		Version: 7.11.7
		Author: Wordfence

	Wordfence Security Activ@tor
		Version: 1.4.0
		Author: moh@medhk2

	WPCode Pro
		Version: 2.2.0
		Author: WPCode

	WP Crontrol
		Version: 1.17.0
		Author: John Blackbourn

	wpDiscuz
		Version: 7.6.22
		Author: gVectors Team

	WP OPcache
		Version: 4.2.0
		Author: nierdz

	WP Rollback
		Version: 2.0.7
		Author: WP Rollback

	WPS Hide Login
		Version: 1.9.16.7
		Author: WPServeur, NicolasKulka, wpformation

	Yoast SEO
		Version: 23.2
		Author: Team Yoast

	Yoast SEO Premium
		Version: 23.2
		Author: Team Yoast


== Must-Use Plugins ==
	Asset CleanUp Pro: Plugin Filtering
		Version: 1.0
		Author: Gabriel Livan


== Features ==
	Custom Fonts: 3
	Custom Icons: 0

== Integrations ==
	
	recaptcha_v3: Active


== Esperimenti Elementor ==
	Caricamento CSS migliorato: Attiva
	Icone dei font in linea: Inattivo per impostazione predefinita
	Punti di interruzione aggiuntivi: Attivo per impostazione predefinita
	Contenitore Flexbox: Attiva
	Contenitore Griglia: Attivo per impostazione predefinita
	Aggiorna la libreria Swiper: Attiva
	Nested Elements Performance: Attivo per impostazione predefinita
	Optimized Control Loading: Inattivo per impostazione predefinita
	Optimized Markup: Inattivo per impostazione predefinita
	Plugin Onboarding: Attivo per impostazione predefinita
	Default to New Theme Builder: Attivo per impostazione predefinita
	Elementor Home Screen: Attivo per impostazione predefinita
	Barra unificata degli strumenti dell&#039;editor: Inattivo per impostazione predefinita
	Costruisci con l&#039;AI: Inattivo
	Landing Page: Attivo per impostazione predefinita
	Elementi annidati: Attiva
	Lazy Load immagini di sfondo: Attivo per impostazione predefinita
	Element Caching: Inattivo per impostazione predefinita
	Link In Bio: Inattivo per impostazione predefinita
	Floating Buttons: Inattivo per impostazione predefinita
	Elementor Editor Events: Inattivo per impostazione predefinita
	Display Conditions: Attivo per impostazione predefinita
	Form Submissions: Attivo per impostazione predefinita
	Menu: Attiva
	Taxonomy Filter: Attivo per impostazione predefinita
	Search: Inattivo per impostazione predefinita


== Registro ==
	
Log: showing 20 of 352024-07-26 11:37:41 [info] Elementor/Upgrades - _on_each_version Start  
2024-07-26 11:37:41 [info] Elementor/Upgrades - _on_each_version Finished 
2024-07-26 11:37:41 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.2',
  'to' => '3.23.3',
)]
2024-07-30 11:27:22 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.1',
  'to' => '3.23.2',
)]
2024-07-30 11:27:22 [info] elementor-pro::elementor_pro_updater Started 
2024-07-30 11:27:22 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-07-30 11:27:22 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-07-30 11:27:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.1',
  'to' => '3.23.2',
)]
2024-08-06 17:14:51 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.3',
  'to' => '3.23.4',
)]
2024-08-06 17:14:52 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.2',
  'to' => '3.23.3',
)]
2024-08-06 17:14:52 [info] elementor::elementor_updater Started 
2024-08-06 17:14:52 [info] Elementor/Upgrades - _on_each_version Start  
2024-08-06 17:14:52 [info] Elementor/Upgrades - _on_each_version Finished 
2024-08-06 17:14:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.3',
  'to' => '3.23.4',
)]
2024-08-06 17:14:52 [info] elementor-pro::elementor_pro_updater Started 
2024-08-06 17:14:52 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-08-06 17:14:52 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-08-06 17:14:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.2',
  'to' => '3.23.3',
)]
2024-08-06 17:14:53 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.3',
  'to' => '3.23.4',
)]
2024-08-06 17:14:54 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.2',
  'to' => '3.23.3',
)]

PHP: showing 6 of 6PHP: 2024-07-19 12:36:18 [error X 1][/home/customer/www/onlygamers.it/public_html/wp-content/plugins/elementor/app/app.php::249] Uncaught Error: Class &#039;Elementor\App\Modules\ImportExport\Module&#039; not found in /home/customer/www/onlygamers.it/public_html/wp-content/plugins/elementor/app/app.php:249
Stack trace:
#0 /home/customer/www/onlygamers.it/public_html/wp-content/plugins/elementor/includes/plugin.php(750): Elementor\App\App-&gt;__construct()
#1 /home/customer/www/onlygamers.it/public_html/wp-content/plugins/elementor/includes/plugin.php(647): Elementor\Plugin-&gt;init_components()
#2 /home/customer/www/onlygamers.it/public_html/wp-includes/class-wp-hook.php(324): Elementor\Plugin-&gt;init(&#039;&#039;)
#3 /home/customer/www/onlygamers.it/public_html/wp-includes/class-wp-hook.php(348): WP_Hook-&gt;apply_filters(NULL, Array)
#4 /home/customer/www/onlygamers.it/public_html/wp-includes/plugin.php(517): WP_Hook-&gt;do_action(Array)
#5 /home/customer/www/onlygamers.it/public_html/wp-settings.php(700): do_action(&#039;init&#039;)
#6 /home/customer/www/onlygamers.it/public_html/wp-config.php(105): require_once(&#039;/home/customer/...&#039;)
#7 /home/customer/www/onlygamers.it/public [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-07-19 12:36:25 [error X 2][/home/customer/www/onlygamers.it/public_html/wp-content/plugins/elementor/includes/plugin.php::750] Uncaught Error: Class &#039;Elementor\App\App&#039; not found in /home/customer/www/onlygamers.it/public_html/wp-content/plugins/elementor/includes/plugin.php:750
Stack trace:
#0 /home/customer/www/onlygamers.it/public_html/wp-content/plugins/elementor/includes/plugin.php(647): Elementor\Plugin-&gt;init_components()
#1 /home/customer/www/onlygamers.it/public_html/wp-includes/class-wp-hook.php(324): Elementor\Plugin-&gt;init(&#039;&#039;)
#2 /home/customer/www/onlygamers.it/public_html/wp-includes/class-wp-hook.php(348): WP_Hook-&gt;apply_filters(NULL, Array)
#3 /home/customer/www/onlygamers.it/public_html/wp-includes/plugin.php(517): WP_Hook-&gt;do_action(Array)
#4 /home/customer/www/onlygamers.it/public_html/wp-settings.php(700): do_action(&#039;init&#039;)
#5 /home/customer/www/onlygamers.it/public_html/wp-config.php(105): require_once(&#039;/home/customer/...&#039;)
#6 /home/customer/www/onlygamers.it/public_html/wp-load.php(50): require_once(&#039;/home/customer/...&#039;)
#7 /home/customer/www/onlygamers.it/public_html/wp-admin/admin.php(34): require_once(&#039;/home/cu [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-07-19 12:36:26 [error X 2][/home/customer/www/onlygamers.it/public_html/wp-content/plugins/elementor/includes/plugin.php::750] Uncaught Error: Class &#039;Elementor\App\App&#039; not found in /home/customer/www/onlygamers.it/public_html/wp-content/plugins/elementor/includes/plugin.php:750
Stack trace:
#0 /home/customer/www/onlygamers.it/public_html/wp-content/plugins/elementor/includes/plugin.php(647): Elementor\Plugin-&gt;init_components()
#1 /home/customer/www/onlygamers.it/public_html/wp-includes/class-wp-hook.php(324): Elementor\Plugin-&gt;init(&#039;&#039;)
#2 /home/customer/www/onlygamers.it/public_html/wp-includes/class-wp-hook.php(348): WP_Hook-&gt;apply_filters(NULL, Array)
#3 /home/customer/www/onlygamers.it/public_html/wp-includes/plugin.php(517): WP_Hook-&gt;do_action(Array)
#4 /home/customer/www/onlygamers.it/public_html/wp-settings.php(700): do_action(&#039;init&#039;)
#5 /home/customer/www/onlygamers.it/public_html/wp-config.php(105): require_once(&#039;/home/customer/...&#039;)
#6 /home/customer/www/onlygamers.it/public_html/wp-load.php(50): require_once(&#039;/home/customer/...&#039;)
#7 /home/customer/www/onlygamers.it/public_html/wp-blog-header.php(13): require_once(&#039;/home/cu [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-07-19 12:36:30 [error X 3][/home/customer/www/onlygamers.it/public_html/wp-content/plugins/elementor/includes/plugin.php::750] Uncaught Error: Class &#039;Elementor\App\App&#039; not found in /home/customer/www/onlygamers.it/public_html/wp-content/plugins/elementor/includes/plugin.php:750
Stack trace:
#0 /home/customer/www/onlygamers.it/public_html/wp-content/plugins/elementor/includes/plugin.php(647): Elementor\Plugin-&gt;init_components()
#1 /home/customer/www/onlygamers.it/public_html/wp-includes/class-wp-hook.php(324): Elementor\Plugin-&gt;init(&#039;&#039;)
#2 /home/customer/www/onlygamers.it/public_html/wp-includes/class-wp-hook.php(348): WP_Hook-&gt;apply_filters(NULL, Array)
#3 /home/customer/www/onlygamers.it/public_html/wp-includes/plugin.php(517): WP_Hook-&gt;do_action(Array)
#4 /home/customer/www/onlygamers.it/public_html/wp-settings.php(700): do_action(&#039;init&#039;)
#5 /home/customer/www/onlygamers.it/public_html/wp-config.php(105): require_once(&#039;/home/customer/...&#039;)
#6 /home/customer/www/onlygamers.it/public_html/wp-load.php(50): require_once(&#039;/home/customer/...&#039;)
#7 /home/customer/www/onlygamers.it/public_html/wp-admin/admin-ajax.php(22): require_once(&#039;/ho [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-07-19 12:38:31 [error X 1][/home/customer/www/onlygamers.it/public_html/wp-content/plugins/elementor/includes/plugin.php::740] Uncaught Error: Class &#039;Elementor\Core\Admin\Menu\Admin_Menu_Manager&#039; not found in /home/customer/www/onlygamers.it/public_html/wp-content/plugins/elementor/includes/plugin.php:740
Stack trace:
#0 /home/customer/www/onlygamers.it/public_html/wp-content/plugins/elementor/includes/plugin.php(647): Elementor\Plugin-&gt;init_components()
#1 /home/customer/www/onlygamers.it/public_html/wp-includes/class-wp-hook.php(324): Elementor\Plugin-&gt;init(&#039;&#039;)
#2 /home/customer/www/onlygamers.it/public_html/wp-includes/class-wp-hook.php(348): WP_Hook-&gt;apply_filters(NULL, Array)
#3 /home/customer/www/onlygamers.it/public_html/wp-includes/plugin.php(517): WP_Hook-&gt;do_action(Array)
#4 /home/customer/www/onlygamers.it/public_html/wp-settings.php(700): do_action(&#039;init&#039;)
#5 /home/customer/www/onlygamers.it/public_html/wp-config.php(105): require_once(&#039;/home/customer/...&#039;)
#6 /home/customer/www/onlygamers.it/public_html/wp-load.php(50): require_once(&#039;/home/customer/...&#039;)
#7 /home/customer/www/onlygamers.it/public_html/wp-admin/admin-ajax [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-07-19 13:51:10 [notice X 455][/home/customer/www/onlygamers.it/public_html/wp-content/plugins/elementor/core/dynamic-tags/manager.php::73] Array to string conversion [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 1 of 1JS: 2024-07-19 12:15:06 [error X 4][https://onlygamers.it/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.3.1:2:46708] Cannot read properties of undefined (reading &#039;chevron-down&#039;) 



== Elementor - Compatibility Tag ==
	
	Custom Icons for Elementor: Compatibilità non specificata
	Elementor Pro: Compatibilità non specificata
	JetElements For Elementor: Compatibilità non specificata
	Lazy Load Control For Elementor: Compatibilità non specificata
	Make Column Clickable Elementor: Compatibilità non specificata
	PowerPack Pro for Elementor: Compatibilità non specificata
	Premium Addons for Elementor: Compatibilità non specificata
	Unlimited Elementor Inner Sections By BoomDevs: Compatibilità non specificata
	Unlimited Elements for Elementor (Premium): Compatibilità non specificata

== Elementor Pro - Compatibility Tag ==
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hi @ivanverona1!

Thank you for submitting your issue! 🙏 

Can you please explain how you've added the Loop Carousel to your sidebar, and what are the settings for this widget?

We need to be able to create the same scenario on our own websites to understand what is the problem. Without this information we are unable to validate your issue.

Please, provide better steps to reproduce the issue, and if possible show screenshots, a screen recording of the issue, or share a link to a page where we can see the issue ourselves.

Kind regards

**Comment by v-neuhaus** [comment]
I have a very similar issue when I use an image carousel widget (or generally one of the elementor carousel widgets) in connection with the post content widget. To be specific, the carousel is used in a _post_ which in turn is being displayed on a _page_ through a loop grid template. The carousel is perfectly fine when you open the post itself, whereas on the page it isn't being contained by the default content width and instead breaks through it, resulting in the page getting extremely wide.

Here's how to reproduce the bug:

1. Create a **post** with an image carousel (or any other carousel) widget
2. Create a **page** with a loop grid and set it to display all posts in 1 column
3. In the loop grid template editor, choose the post content widget to display all of the post's content including the carousel
4. Save and open the page
