### ISSUE TITLE
⛔ 🛟 Support Request: Edit elementor page error 404 show

### ISSUE THREAD

**Issue by faisal-rehman03** [elementor/elementor#28461]
### Prerequisites

- [ ] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

When I edit the elementor pages then error show 404 page not found 
<img width="960" alt="Screenshot_19" src="https://github.com/user-attachments/assets/636f2474-2a38-47de-8477-74039afc6066">

### Steps to reproduce

https://github.com/user-attachments/assets/051df0fd-7814-4afc-9066-2c419e32d6ca

### Expected behavior

I expect open a elementor edit page

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt


== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.6.18
	PHP Version: 8.2.20
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 32M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.6.1
	Site URL: https://zeromaxrentacar.com
	Home URL: https://zeromaxrentacar.com
	WP Multisite: No
	Max Upload Size: 32 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Bosa Rental Car
	Version: 1.0.1
	Author: Bosa Themes
	Child Theme: Yes
	Parent Theme Name: Bosa
	Parent Theme Version: 1.5.3
	Parent Theme Author: Bosa Themes

== User ==
	Role: administrator
	WP Profile lang: en
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Import
		Version: 1.4.2
		Author: AddonsPress

	Akismet Anti-spam: Spam Protection
		Version: 5.3.3
		Author: Automattic - Anti-spam Team

	Breadcrumb NavXT
		Version: 7.3.1
		Author: John Havlik

	Contact Form 7
		Version: 5.9.8
		Author: Takayuki Miyoshi

	Elementor
		Version: 3.23.4
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.23.3
		Author: Elementor.com

	ElementsKit Lite
		Version: 3.2.5
		Author: Wpmet

	Image Optimizer by Elementor – Compress, Resize and Optimize Images
		Version: 1.5.1
		Author: Elementor.com

	Keon Toolset
		Version: 1.8.6
		Author: Keon Themes

	Kirki Customizer Framework
		Version: 5.1.0
		Author: Themeum

	Social Chat
		Version: 7.4.4
		Author: QuadLayers


== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

	WordPress automation by Installatron
		Version: 
		Author: 


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Improved CSS Loading: Active by default
	Inline Font Icons: Active by default
	Additional Custom Breakpoints: Active by default
	Flexbox Container: Active by default
	Grid Container: Active by default
	Upgrade Swiper Library: Active by default
	Nested Elements Performance: Active by default
	Optimized Control Loading: Active by default
	Optimized Markup: Inactive by default
	Plugin Onboarding: Active by default
	Default to New Theme Builder: Active by default
	Elementor Home Screen: Active by default
	Editor Top Bar: Active by default
	Build with AI: Active by default
	Landing Pages: Active by default
	Nested Elements: Active by default
	Lazy Load Background Images: Active by default
	Pages Panel: Inactive by default
	Element Caching: Active by default
	Link In Bio: Active by default
	Floating Buttons: Active by default
	Elementor Editor Events: Inactive by default
	Display Conditions: Active by default
	Form Submissions: Active by default
	Menu: Active by default
	Taxonomy Filter: Active by default
	Search: Active by default


== Log ==
	
PHP: showing 5 of 5PHP: 2024-08-16 13:59:29 [warning X 7][../wp-content/plugins/elementor/includes/managers/image.php::113] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-08-16 15:49:04 [warning X 1][../wp-content/plugins/elementor/core/page-assets/data-managers/font-icon-svg/font-awesome.php::50] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-08-19 16:26:29 [warning X 1][../wp-content/plugins/elementor/includes/widgets/image-carousel.php::875] Undefined array key &quot;id&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-08-20 15:41:51 [error X 1][../wp-content/plugins/elementor/core/files/manager.php::203] Uncaught Error: Class &quot;Elementor\Core\Page_Assets\Data_Managers\Base&quot; not found in ../wp-content/plugins/elementor/core/files/manager.php:203
Stack trace:
#0 ../wp-content/plugins/elementor/core/files/manager.php(121): Elementor\Core\Files\Manager-&gt;reset_assets_data()
#1 ../wp-content/plugins/elementor/modules/element-cache/module.php(156): Elementor\Core\Files\Manager-&gt;clear_cache()
#2 ../wp-includes/class-wp-hook.php(326): Elementor\Modules\ElementCache\Module-&gt;clear_cache()
#3 ../wp-includes/class-wp-hook.php(348): WP_Hook-&gt;apply_filters()
#4 ../wp-includes/plugin.php(517): WP_Hook-&gt;do_action()
#5 ../wp-admin/includes/class-wp-upgrader.php(970): do_action()
#6 ../wp-admin/includes/class-plugin-upgrader.php(135): WP_Upgrader-&gt;run()
#7 ../wp-admin/update.php(180): Plugin_Upgrader-&gt;install()
#8 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-08-20 15:50:58 [notice X 3][../wp-content/plugins/elementor/includes/base/controls-stack.php::229] hexdec(): Passing null to parameter #1 ($hex_string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 1 of 1JS: 2024-08-16 14:21:18 [error X 1]../wp-content/plugins/elementskit-lite/widgets/init/assets/js/elementor.js?ver=3.2.5:1:17445] n.find(...).mediaelementplayer is not a function 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible
	Image Optimizer by Elementor – Compress, Resize and Optimize Images: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hello @faisal-rehman03,

Thanks for contacting us! 🙏 

### 🛟 This is more of a support question, not really something we can help with here. 

👉 Please remember to check the [Help Center](https://elementor.com/help) or contact [Elementor Support](https://elementor.com/contact) before submitting an issue.


### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

### ⚠️ As a gentle reminder, **🛟 Support Request issues** may need to be closed without troubleshooting. 
Remember to always follow our **[🐞 Bug Report Guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&projects=&template=bug.yml)** to save time and ensure smooth troubleshooting.

Thank you for understanding! 🙏 

Kind regards
