### ISSUE TITLE
⛔ 🛟 website now working when using the Elementor Developer Edition plugin

### ISSUE THREAD

**Issue by TECKPRO1** [elementor/elementor#28525]
### Prerequisites

- [ ] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Before my website works fine and then yesterday when i checked my website, it appears differently to my home page. Please help me to resolve this issues.
![home page edit](https://github.com/user-attachments/assets/21dafab3-32f8-49df-9583-323d0947fdd6)
![website published](https://github.com/user-attachments/assets/45c7b6a9-789b-4b88-98af-27a0c2e3dd59)

### Steps to reproduce

please check the video attachment
https://github.com/user-attachments/assets/816843de-3c47-4330-bc31-7d29ef45dd42

### Expected behavior

my homepage website was different when i publish it.
![home page edit](https://github.com/user-attachments/assets/14ac923a-39b6-4c9c-98b0-6ab656916520)
![website published](https://github.com/user-attachments/assets/da506f6f-5196-44e4-b29e-c562c0fea81f)

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [ ] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt


== Server Environment ==
	Operating System: Linux
	Software: nginx
	MySQL version: MariaDB Server v10.6.18
	PHP Version: 8.1.29
	PHP Memory Limit: 512M
	PHP Max Input Vars: 6144
	PHP Max Post Size: 2047M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.6.1
	Site URL: https://teckpro.com.au
	Home URL: https://teckpro.com.au
	WP Multisite: No
	Max Upload Size: 2 GB
	Memory limit: 512M
	Max Memory limit: 512M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en_US
	Timezone: Australia/Brisbane
	Debug Mode: Inactive

== Theme ==
	Name: Astra
	Version: 4.8.0
	Author: Brainstorm Force
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 CCleaner/127.0.0.0

== Active Plugins ==
	Admin and Site Enhancements (ASE)
		Version: 7.3.2
		Author: wpase.com

	Advanced Custom Fields
		Version: 6.3.5
		Author: WP Engine

	Akismet Anti-spam: Spam Protection
		Version: 5.3.3
		Author: Automattic - Anti-spam Team

	Classic Editor +
		Version: 4.4.0
		Author: <a href="https://so-wp.com">Pieter Bos</a>, <a href="https://gschoppe.com">Greg Schoppe</a>

	Crowdsignal Forms
		Version: 1.7.2
		Author: Automattic

	Crowdsignal Polls & Ratings
		Version: 3.1.2
		Author: Automattic, Inc.

	Elementor
		Version: 3.24.0-dev1
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.23.3
		Author: Elementor.com

	Gutenberg
		Version: 19.0.0
		Author: Gutenberg Team

	Image Optimizer by Elementor – Compress, Resize and Optimize Images
		Version: 1.5.2
		Author: Elementor.com

	Independent Analytics
		Version: 2.7.3
		Author: Independent Analytics

	Jetpack
		Version: 13.8-a.7
		Author: Automattic

	Layout Grid
		Version: 1.8.4
		Author: Automattic

	ManageWP - Worker
		Version: 4.9.20
		Author: GoDaddy

	Page Optimize
		Version: 0.5.5
		Author: Automattic

	Safe SVG
		Version: 2.2.5
		Author: 10up

	WordPress.com Editing Toolkit
		Version: 4.30504
		Author: Automattic


== Must-Use Plugins ==
	ManageWP - Worker Loader
		Version: 1.0.0
		Author: GoDaddy

	wpcomsh-loader.php
		Version: 
		Author: 


== Elements Usage ==
	
	archive : 2
		archive-posts : 1
		button : 1
		container : 7
		heading : 4
		posts : 1
		text-editor : 1
	footer : 2
		call-to-action : 1
		container : 13
		form : 1
		heading : 9
		icon-list : 3
		image-box : 1
		nav-menu : 2
		social-icons : 2
		text-editor : 1
		theme-site-logo : 1
	header : 9
		button : 3
		container : 9
		nav-menu : 4
		theme-site-logo : 4
	wp-post : 1
		container : 1
		heading : 1
		text-editor : 9
	wp-page : 28
		button : 56
		call-to-action : 12
		container : 363
		divider : 57
		form : 2
		google_maps : 1
		heading : 202
		icon : 8
		icon-box : 43
		icon-list : 7
		image : 49
		image-box : 82
		image-carousel : 2
		posts : 1
		social-icons : 1
		spacer : 8
		testimonial : 27
		text-editor : 144
		theme-site-logo : 2
		toggle : 6
		video : 4
	single-post : 3
		button : 1
		container : 12
		heading : 4
		post-info : 2
		post-navigation : 2
		posts : 2
		share-buttons : 2
		theme-post-content : 2
		theme-post-excerpt : 1
		theme-post-title : 2
	single-page : 5
		container : 9
		heading : 2
		image : 2
		post-info : 1
		post-navigation : 1
		posts : 1
		share-buttons : 1
		theme-post-content : 4
		theme-post-excerpt : 2
		theme-post-title : 1
	error-404 : 2
		button : 2
		container : 6
		heading : 4
		testimonial : 3
		text-editor : 1


== Settings ==
	
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap


== Features ==
	Custom Fonts: 4
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Improved CSS Loading: Active by default
	Inline Font Icons: Active by default
	Additional Custom Breakpoints: Active by default
	Flexbox Container: Active by default
	Grid Container: Active by default
	Upgrade Swiper Library: Active by default
	Nested Elements Performance: Active by default
	Optimized Control Loading: Active by default
	Optimized Markup: Inactive by default
	Conditionally load Swiper CSS files: Inactive by default
	Plugin Onboarding: Active by default
	Default to New Theme Builder: Active by default
	Elementor Home Screen: Active by default
	Build with AI: Active by default
	Landing Pages: Active by default
	Launchpad Checklist: Inactive by default
	Nested Elements: Active by default
	Editor Top Bar: Active by default
	Pages Panel: Inactive by default
	Element Caching: Active by default
	Elementor Editor Events: Inactive by default
	Atomic Widgets: Inactive by default
	Menu: Active by default
	Taxonomy Filter: Active by default
	Search: Active by default


== Log ==
	
Log: showing 20 of 352024-07-30 19:22:33 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.1',
  'to' => '3.23.2',
)]
2024-07-30 19:22:33 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.1',
  'to' => '3.23.2',
)]
2024-08-06 20:07:20 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.2',
  'to' => '3.23.3',
)]
2024-08-06 20:07:21 [info] elementor-pro::elementor_pro_updater Started 
2024-08-06 20:07:21 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-08-06 20:07:21 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-08-06 20:07:21 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.2',
  'to' => '3.23.3',
)]
2024-08-26 07:45:10 [info] elementor::elementor_updater Started 
2024-08-26 07:45:10 [info] Elementor/Upgrades - _on_each_version Start  
2024-08-26 07:45:10 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.1',
  'to' => '3.24.0-dev1',
)]
2024-08-26 07:45:11 [info] Elementor/Upgrades - _on_each_version Finished 
2024-08-26 07:45:11 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.1',
  'to' => '3.24.0-dev1',
)]
2024-08-27 18:09:32 [info] Uploading Kit:  [array (
  'kit_id' => '64916b33962f1cf79903c007',
  'referrer' => 'kit-library',
)]
2024-08-27 18:09:33 [info] Selected import runners: site-settings, plugins, templates, taxonomies, elementor-content, wp-content, elements-default-values 
2024-08-27 18:09:33 [info] Import runner completed: site-settings ✓ 
2024-08-27 18:09:35 [info] Import runner completed: plugins ✓ 
2024-08-27 18:09:35 [info] Import runner completed: templates ✓ 
2024-08-27 18:09:36 [info] Import runner completed: taxonomies ✓ 
2024-08-27 18:09:38 [info] Import runner completed: elementor-content ✓ 
2024-08-27 18:09:39 [info] Import runner completed: wp-content ✓ 

PHP: showing 5 of 5PHP: 2024-07-26 05:11:03 [error X 1][../wp-content/plugins/elementor/core/documents-manager.php::515] Uncaught Error: Call to a member function is_built_with_elementor() on bool in ../wp-content/plugins/elementor/core/documents-manager.php:515
Stack trace:
#0 [internal function]: Elementor\Core\Documents_Manager->ajax_save(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#1 ../wp-content/plugins/elementor/core/common/modules/ajax/module.php(176): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /wordpress/core/6.6.1/wp-includes/class-wp-hook.php(324): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#3 /wordpress/core/6.6.1/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#4 /wordpress/core/6.6.1/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#5 /wordpress/core/6.6.1/wp-admin/admin-ajax.php(192): do_action('wp_ajax_element...')
#6 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-07-30 20:05:39 [warning X 22][../wp-content/plugins/elementor/includes/managers/image.php::113] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-07-30 20:07:18 [notice X 55][../wp-content/plugins/elementor/includes/base/controls-stack.php::229] hexdec(): Passing null to parameter #1 ($hex_string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-08-26 07:46:13 [warning X 13][../wp-content/plugins/elementor/includes/conditions.php::87] Undefined array key "background_color" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-08-27 18:09:40 [notice X 1][../wp-content/plugins/elementor/core/utils/import-export/parsers/wxr-parser-simple-xml.php::53] Function libxml_disable_entity_loader() is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 2 of 2JS: 2024-07-27 09:59:43 [error X 1][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.23.1:3:831442] Cannot read properties of undefined (reading 'toLowerCase') 
JS: 2024-07-28 11:33:19 [error X 2][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.23.1:3:949412] elementorFrontend is not defined 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Incompatible
	Image Optimizer by Elementor – Compress, Resize and Optimize Images: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by crowlsyong** [comment]
Did you mean to say "no**t** working" in your title? Right now it says "website now working"

**Comment by nicholaszein** [comment]
Hello @TECKPRO1 and @crowlsyong!

Thank you for reaching out! 🙏 

We noticed that you're using the **_Elementor Beta (Developer Edition)_** plugin. This edition is a playground for developers to test their plugins and themes with the most recent features of Elementor, and **<ins>it's not quite intended for use on live websites.</ins>**

In the most recent release of this Developer Edition plugin, a conflict between the Core version (3.24.0-dev3) and older versions of the Pro plugin has caused an incompatibility in the rendering of the CSS. This should be fixed with the release of the Elementor Core (Free) version 3.24.0, and Elementor Pro version 3.24.0 tomorrow.

### 🧪 Due to the experimental nature of this Developer Edition plugin, we're unable to provide support for it. 

But don't worry! Our stable versions are full of great features that are ready for prime time on your website.

### 🔄 Please, [revert back to a stable version of Elementor](https://elementor.com/help/revert-to-release-from-developer-edition/) if you're working on a production site.

Kind regards
