### ISSUE TITLE
⛔ 🛟 My site stopped working after it got updated when using the Elementor Developer Edition plugin

### ISSUE THREAD

**Issue by emelieolin** [elementor/elementor#28558]
### Prerequisites

- [ ] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

My site broke after it was updated automatically. 
![Screenshot 2024-08-26 155140](https://github.com/user-attachments/assets/eb26ae36-c52f-42e1-9f9a-9aa2b5488b88)

### Steps to reproduce

N/A i have no idea how to fix it

### Expected behavior

I need to get it fixed since my site isn't working properly

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [ ] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt


== Server Environment ==
	Operating System: Linux
	Software: nginx
	MySQL version: MariaDB Server v10.6.18
	PHP Version: 8.1.29
	PHP Memory Limit: 512M
	PHP Max Input Vars: 6144
	PHP Max Post Size: 2047M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.6.1
	Site URL: https://twintermitesocal.com
	Home URL: https://twintermitesocal.com
	WP Multisite: No
	Max Upload Size: 2 GB
	Memory limit: 512M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en_US
	Timezone: America/Los_Angeles
	Debug Mode: Inactive

== Theme ==
	Name: Astra
	Version: 4.6.9
	Author: Brainstorm Force
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36

== Active Plugins ==
	Akismet Anti-spam: Spam Protection
		Version: 5.3.3
		Author: Automattic - Anti-spam Team

	All-in-One WP Migration
		Version: 7.86
		Author: ServMask

	AutomateWoo
		Version: 6.0.33
		Author: WooCommerce

	Blaze Ads
		Version: 0.4.1
		Author: Automattic

	Code Snippets
		Version: 3.6.5.1
		Author: Code Snippets Pro

	Copy &amp; Delete Posts
		Version: 1.4.8
		Author: Inisev

	Elementor
		Version: 3.24.0-dev1
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.23.3
		Author: Elementor.com

	Facebook for WooCommerce
		Version: 3.2.7
		Author: Facebook

	Favicon by RealFaviconGenerator
		Version: 1.3.32
		Author: Philippe Bernard

	Google Analytics for WooCommerce
		Version: 2.1.6
		Author: WooCommerce

	Google for WooCommerce
		Version: 2.8.4
		Author: WooCommerce

	Gutenberg
		Version: 19.1.0
		Author: Gutenberg Team

	Jetpack
		Version: 13.8-a.7
		Author: Automattic

	Jetpack Boost
		Version: 3.4.7
		Author: Automattic - Jetpack Site Speed team

	Layout Grid
		Version: 1.8.4
		Author: Automattic

	Lazy Load - Optimize Images
		Version: 2.3.9
		Author: WP Rocket

	Mailchimp for WooCommerce
		Version: 4.3.1
		Author: Mailchimp

	NitroPack
		Version: 1.16.8
		Author: NitroPack Inc.

	One Click Accessibility
		Version: 2.1.0
		Author: One Click Accessibility

	Page Optimize
		Version: 0.5.5
		Author: Automattic

	Site Kit by Google
		Version: 1.134.0
		Author: Google

	Starter Templates
		Version: 4.4.1
		Author: Brainstorm Force

	Woo AI
		Version: 0.6.0
		Author: WooCommerce

	Woo Back In Stock Notifications
		Version: 2.0.2
		Author: Woo

	WooCommerce
		Version: 9.2.3
		Author: Automattic

	WooCommerce Brands
		Version: 1.7.5
		Author: WooCommerce

	WooCommerce Product Add-Ons
		Version: 7.0.2
		Author: Woo

	WooCommerce Product Bundles
		Version: 8.0.2
		Author: Woo

	WooCommerce Shipment Tracking
		Version: 2.5.0
		Author: WooCommerce

	WooCommerce Shipping &amp; Tax
		Version: 2.7.0
		Author: WooCommerce

	WooCommerce Stripe Gateway
		Version: 8.6.1
		Author: WooCommerce

	Woo Gift Cards
		Version: 2.0.2
		Author: Woo

	Woo Min/Max Quantities
		Version: 5.0.1
		Author: Woo

	Woo Product Recommendations
		Version: 4.0.2
		Author: Woo

	WordPress.com Editing Toolkit
		Version: 4.30504
		Author: Automattic

	WPCode Lite
		Version: 2.2.1
		Author: WPCode

	WPForms
		Version: 1.9.0.2
		Author: WPForms

	WPForms Form Locker
		Version: 2.8.0
		Author: WPForms

	WPForms Geolocation
		Version: 2.10.0
		Author: WPForms

	WPForms Mailchimp
		Version: 2.3.0
		Author: WPForms

	WPForms Stripe Pro
		Version: 3.4.0
		Author: WPForms

	WP Mail SMTP
		Version: 4.1.1
		Author: WP Mail SMTP

	YayMail - WooCommerce Email Customizer
		Version: 3.5.5
		Author: YayCommerce

	Yoast SEO
		Version: 23.3
		Author: Team Yoast


== Must-Use Plugins ==
	wpcomsh-loader.php
		Version: 
		Author: 


== Elements Usage ==
	
	archive : 1
		archive-posts : 1
		heading : 1
	footer : 1
		button : 1
		container : 9
		heading : 5
		image : 1
		nav-menu : 1
		social-icons : 1
		text-editor : 5
	header : 1
		container : 3
		heading : 1
		icon-list : 1
		nav-menu : 1
		theme-site-logo : 1
	product : 1
		blockquote : 2
		container : 9
		heading : 1
		star-rating : 2
		theme-site-logo : 1
		woocommerce-menu-cart : 1
		woocommerce-notices : 1
		woocommerce-product-add-to-cart : 1
		woocommerce-product-content : 1
		woocommerce-product-images : 1
		woocommerce-product-price : 1
		woocommerce-product-title : 1
	wp-post : 16
		button : 5
		container : 437
		divider : 1
		gallery : 1
		heading : 16
		icon : 3
		icon-list : 1
		image : 143
		social-icons : 16
		text-editor : 189
		wpforms : 1
	wp-page : 15
		button : 10
		container : 207
		divider : 2
		heading : 51
		icon : 67
		icon-list : 3
		image : 12
		image-carousel : 2
		image-gallery : 1
		nav-menu : 2
		nested-accordion : 3
		posts : 1
		price-table : 3
		social-icons : 1
		table-of-contents : 1
		testimonial-carousel : 2
		text-editor : 176
		theme-site-logo : 3
		wc-add-to-cart : 6
		woocommerce-cart : 1
		woocommerce-checkout-page : 1
		woocommerce-menu-cart : 3
		wpforms : 1
	single-post : 3
		heading : 1
		post-navigation : 1
		posts : 1
		table-of-contents : 1
		theme-post-content : 1
		theme-post-title : 1
	landing-page : 0
		button : 3
		container : 25
		countdown : 1
		divider : 2
		heading : 10
		icon-list : 5
		image : 5
		social-icons : 1
		star-rating : 3
		text-editor : 4
		video : 1
		woocommerce-menu-cart : 1
	error-404 : 1
		button : 1
		heading : 2
		testimonial : 3
		text-editor : 1


== Settings ==
	
	cpt_support: post, page, e-landing-page
	disable_color_schemes: yes
	disable_typography_schemes: yes
	allow_tracking: yes
	editor_break_lines: 1
	unfiltered_files_upload: 1
	font_display: swap


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	
	woocommerce: Active


== Elementor Experiments ==
	Improved CSS Loading: Active
	Inline Font Icons: Active by default
	Additional Custom Breakpoints: Active
	Flexbox Container: Active by default
	Grid Container: Active by default
	Upgrade Swiper Library: Active by default
	Nested Elements Performance: Active by default
	Optimized Control Loading: Active by default
	Optimized Markup: Inactive by default
	Conditionally load Swiper CSS files: Inactive by default
	Plugin Onboarding: Active by default
	Default to New Theme Builder: Active by default
	Elementor Home Screen: Active by default
	Build with AI: Active by default
	Landing Pages: Active by default
	Launchpad Checklist: Inactive by default
	Nested Elements: Active by default
	Editor Top Bar: Active by default
	Pages Panel: Inactive by default
	Element Caching: Active by default
	Elementor Editor Events: Inactive by default
	Atomic Widgets: Inactive by default
	Display Conditions: Active by default
	Form Submissions: Active by default
	Menu: Active by default
	Taxonomy Filter: Active by default
	Search: Active by default


== Log ==
	
Log: showing 20 of 362024-07-24 23:48:59 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-07-24 23:48:59 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-07-24 23:48:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.0',
  'to' => '3.23.1',
)]
2024-07-29 23:42:49 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.1',
  'to' => '3.23.2',
)]
2024-07-29 23:42:50 [info] elementor-pro::elementor_pro_updater Started 
2024-07-29 23:42:50 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-07-29 23:42:50 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-07-29 23:42:50 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.1',
  'to' => '3.23.2',
)]
2024-08-07 23:44:53 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.2',
  'to' => '3.23.3',
)]
2024-08-07 23:44:54 [info] elementor-pro::elementor_pro_updater Started 
2024-08-07 23:44:54 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-08-07 23:44:54 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-08-07 23:44:54 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.2',
  'to' => '3.23.3',
)]
2024-08-07 23:44:55 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.2',
  'to' => '3.23.3',
)]
2024-08-25 11:39:48 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.0-dev6',
  'to' => '3.24.0-dev1',
)]
2024-08-25 11:39:49 [info] elementor::elementor_updater Started 
2024-08-25 11:39:49 [info] Elementor/Upgrades - _on_each_version Start  
2024-08-25 11:39:50 [info] Elementor/Upgrades - _on_each_version Finished 
2024-08-25 11:39:50 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.0-dev6',
  'to' => '3.24.0-dev1',
)]
2024-08-25 11:39:52 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.0-dev6',
  'to' => '3.24.0-dev1',
)]

JS: showing 3 of 3JS: 2024-07-03 17:10:14 [error X 1][../_jb_static/??-eJyVjEEKgzAQRW/TVTVqka6kZ4nJVMZmJiGTELx9rUixm4K7ecx7v4QK2bhsQdQsisCiBgcEnH6gIpyiTlATcj3Ltfzp1t+RD4nxnD5GcHlCFrUbPiotAmmbKjAGbV51zJyQ4GT9jJtkK/I2O5AzucNRFb0Ej7zS99onHjS0965pulvb9xczDu0bQzt3eQ==:6:17146] Cannot read properties of undefined (reading &#039;attributes&#039;) 
JS: 2024-08-14 23:54:55 [error X 1][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.23.0-dev6:3:622208] Cannot read properties of null (reading &#039;id&#039;) 
JS: 2024-08-29 21:10:04 [error X 1][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.24.0-dev1:3:816931] Cannot read properties of undefined (reading &#039;get&#039;) 

PHP: showing 4 of 4PHP: 2024-07-15 13:56:30 [error X 1][../wp-content/plugins/elementor-pro/elementor-pro.php::68] Uncaught Error: Failed opening required &#039;../wp-content/plugins/elementor-pro/plugin.php&#039; (include_path=&#039;/:.&#039;) in ../wp-content/plugins/elementor-pro/elementor-pro.php:68
Stack trace:
#0 /wordpress/core/6.5.5/wp-includes/class-wp-hook.php(324): elementor_pro_load_plugin(&#039;&#039;)
#1 /wordpress/core/6.5.5/wp-includes/class-wp-hook.php(348): WP_Hook-&gt;apply_filters(NULL, Array)
#2 /wordpress/core/6.5.5/wp-includes/plugin.php(517): WP_Hook-&gt;do_action(Array)
#3 /wordpress/core/6.5.5/wp-settings.php(550): do_action(&#039;plugins_loaded&#039;)
#4 ../wp-config.php(83): require_once(&#039;/wordpress/core...&#039;)
#5 /wordpress/core/6.5.5/wp-load.php(55): require_once(&#039;../wp-...&#039;)
#6 /wordpress/core/6.5.5/wp-admin/admin.php(34): require_once(&#039;/wordpress/core...&#039;)
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-08-14 15:47:16 [warning X 1][../wp-content/plugins/elementor/modules/history/revisions-manager.php::363] Undefined array key &quot;editor_post_id&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-08-29 13:35:47 [warning X 2][../wp-content/plugins/elementor/includes/db.php::267] foreach() argument must be of type array|object, string given [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-08-29 14:48:19 [error X 1][../wp-content/plugins/elementor/core/dynamic-tags/manager.php::435] Uncaught Error: Call to a member function get_content() on null in ../wp-content/plugins/elementor/core/dynamic-tags/manager.php:435
Stack trace:
#0 [internal function]: Elementor\Core\DynamicTags\Manager-&gt;ajax_render_tags(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#1 ../wp-content/plugins/elementor/core/common/modules/ajax/module.php(176): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /wordpress/core/6.6.1/wp-includes/class-wp-hook.php(324): Elementor\Core\Common\Modules\Ajax\Module-&gt;handle_ajax_request(&#039;&#039;)
#3 /wordpress/core/6.6.1/wp-includes/class-wp-hook.php(348): WP_Hook-&gt;apply_filters(NULL, Array)
#4 /wordpress/core/6.6.1/wp-includes/plugin.php(517): WP_Hook-&gt;do_action(Array)
#5 /wordpress/core/6.6.1/wp-admin/admin-ajax.php(192): do_action(&#039;wp_ajax_element...&#039;)
#6 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by spasauna** [comment]
Regenerate CSS in Elementor > Tools.

**Comment by radarhere** [comment]
Hi. Rolling back the version worked for me - https://github.com/elementor/elementor/issues/28533#issuecomment-2314116068

**Comment by nicholaszein** [comment]
Hello @emelieolin, and @radarhere!

Thank you for reaching out! 🙏 

We noticed that you're using the **_Elementor Beta (Developer Edition)_** plugin. This edition is a playground for developers to test their plugins and themes with the most recent features of Elementor, and **<ins>it's not quite intended for use on live websites.</ins>**

In the most recent release of this Developer Edition plugin, a conflict between the Core version (3.24.0-dev3) and older versions of the Pro plugin has caused an incompatibility in the rendering of the CSS. This should be fixed with the release of the Elementor Core (Free) version 3.24.0, and Elementor Pro version 3.24.0 tomorrow.

### 🧪 Due to the experimental nature of this Developer Edition plugin, we're unable to provide support for it. 

But don't worry! Our stable versions are full of great features that are ready for prime time on your website.

### 🔄 Please, [revert back to a stable version of Elementor](https://elementor.com/help/revert-to-release-from-developer-edition/) if you're working on a production site.

Kind regards
