### ISSUE TITLE
⛔ 🛟 Menu Widget is not displaying properly and breaking website when using the Elementor Developer Edition plugin

### ISSUE THREAD

**Issue by AYarb96** [elementor/elementor#28586]
### Prerequisites

- [ ] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

The menu header on the website is not displaying properly and is causing the website to look completely broken. 
<img width="1335" alt="Screen Shot 2024-09-01 at 6 54 18 PM" src="https://github.com/user-attachments/assets/b40ceae0-d9e2-480c-bf9a-8b0627979313">
If I roll the site back, it temporarily fixes it but breaks again once it syncs up the following day.  I can't roll back my site every day.  And we've tried other menus trying to get it to display correctly, but nothing is working.

### Steps to reproduce

We've deactivated plugins and have both Elementor and Elementor Pro installed.  And we have the Hello Elementor theme.

### Expected behavior

The website should load normally and display correctly when visited.  Everything looks fine within the Elementor edit tool but not the actual live site.  Please help us fix this!

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [ ] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt


== Server Environment ==
	Operating System: Linux
	Software: nginx
	MySQL version: MariaDB Server v10.6.18
	PHP Version: 8.1.29
	PHP Memory Limit: 512M
	PHP Max Input Vars: 6144
	PHP Max Post Size: 2047M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.6.1
	Site URL: https://tuzerballet.org
	Home URL: https://tuzerballet.org
	WP Multisite: No
	Max Upload Size: 2 GB
	Memory limit: 512M
	Max Memory limit: 512M
	Permalink Structure: /%year%/%monthnum%/%postname%/
	Language: en_US
	Timezone: America/Chicago
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 3.1.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36

== Active Plugins ==
	Akismet Anti-spam: Spam Protection
		Version: 5.3.3
		Author: Automattic - Anti-spam Team

	Crowdsignal Forms
		Version: 1.7.2
		Author: Automattic

	Crowdsignal Polls &amp; Ratings
		Version: 3.1.2
		Author: Automattic, Inc.

	Easy Google Fonts
		Version: 2.0.4
		Author: Titanium Themes

	Elementor
		Version: 3.24.0-dev1
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.23.3
		Author: Elementor.com

	Jetpack
		Version: 13.8-a.7
		Author: Automattic

	Layout Grid
		Version: 1.8.4
		Author: Automattic

	Map Block for Google Maps
		Version: 1.35
		Author: WebFactory Ltd

	Page Optimize
		Version: 0.5.5
		Author: Automattic

	Premium Addons for Elementor
		Version: 4.10.49
		Author: Leap13

	Redirect Redirection
		Version: 1.2.3
		Author: Inisev

	WordPress.com Editing Toolkit
		Version: 4.30504
		Author: Automattic

	WP Google Map
		Version: 1.9.2
		Author: WP Google Map


== Must-Use Plugins ==
	wpcomsh-loader.php
		Version: 
		Author: 


== Elements Usage ==
	
	container : 16
		button : 1
		container : 52
		divider : 2
		heading : 2
		image : 5
		image-box : 18
		nav-menu : 4
		social-icons : 1
		spacer : 3
		text-editor : 11
	footer : 1
		container : 8
		heading : 1
		social-icons : 1
		text-editor : 2
	header : 4
		container : 4
		image : 1
		nav-menu : 1
	wp-page : 11
		call-to-action : 3
		container : 74
		divider : 4
		form : 1
		gallery : 1
		google_maps : 2
		heading : 7
		image : 10
		loop-carousel : 1
		premium-addon-modal-box : 1
		spacer : 12
		text-editor : 27


== Settings ==
	
	cpt_support: page
	disable_color_schemes: yes
	disable_typography_schemes: yes
	allow_tracking: yes
	editor_break_lines: 1
	unfiltered_files_upload: 1


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Additional Custom Breakpoints: Active
	Flexbox Container: Active
	Grid Container: Active
	Upgrade Swiper Library: Active
	Nested Elements Performance: Active by default
	Optimized Control Loading: Active by default
	Optimized Markup: Inactive by default
	Conditionally load Swiper CSS files: Inactive by default
	Plugin Onboarding: Active by default
	Default to New Theme Builder: Active by default
	Header &amp; Footer: Active by default
	Elementor Home Screen: Active by default
	Build with AI: Active by default
	Landing Pages: Active
	Launchpad Checklist: Inactive by default
	Nested Elements: Active
	Editor Top Bar: Active
	Pages Panel: Inactive by default
	Element Caching: Active by default
	Elementor Editor Events: Inactive by default
	Atomic Widgets: Inactive by default
	Menu: Active
	Taxonomy Filter: Active by default
	Search: Active by default


== Log ==
	
Log: showing 20 of 282024-07-30 20:25:16 [info] elementor::elementor_updater Started 
2024-07-30 20:25:16 [info] Elementor/Upgrades - _on_each_version Start  
2024-07-30 20:25:16 [info] Elementor/Upgrades - _on_each_version Finished 
2024-07-30 20:25:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.18.2',
  'to' => '3.23.0-dev6',
)]
2024-07-31 17:00:48 [info] elementor-pro::elementor_pro_updater Started 
2024-07-31 17:00:48 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-07-31 17:00:48 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-07-31 17:00:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.1',
  'to' => '3.23.2',
)]
2024-07-31 17:00:49 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.1',
  'to' => '3.23.2',
)]
2024-08-06 17:02:13 [info] elementor-pro::elementor_pro_updater Started 
2024-08-06 17:02:13 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-08-06 17:02:13 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-08-06 17:02:13 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.2',
  'to' => '3.23.3',
)]
2024-08-06 17:02:14 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.2',
  'to' => '3.23.3',
)]
2024-08-27 11:07:17 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.0-dev6',
  'to' => '3.24.0-dev1',
)]
2024-08-27 11:07:29 [info] elementor::elementor_updater Started 
2024-08-27 11:07:29 [info] Elementor/Upgrades - _on_each_version Start  
2024-08-27 11:07:29 [info] Elementor/Upgrades - _on_each_version Finished 
2024-08-27 11:07:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.0-dev6',
  'to' => '3.24.0-dev1',
)]
2024-08-30 16:34:04 [error] Error fetching document in conditions manager. Template:  

PHP: showing 6 of 6PHP: 2024-08-01 15:39:09 [warning X 1][../wp-content/plugins/elementor/core/common/modules/connect/module.php::255] Attempt to read property &quot;email&quot; on null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-08-27 11:27:44 [notice X 87][../wp-content/plugins/elementor/includes/base/controls-stack.php::229] hexdec(): Passing null to parameter #1 ($hex_string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-08-28 12:05:49 [warning X 24][../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key &quot;condition_type&quot; [array (
  'trace' => '
#0: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: ../wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2024-08-30 15:55:08 [error X 6][../wp-content/plugins/elementor/core/documents-manager.php::515] Uncaught Error: Call to a member function is_built_with_elementor() on bool in ../wp-content/plugins/elementor/core/documents-manager.php:515
Stack trace:
#0 [internal function]: Elementor\Core\Documents_Manager-&gt;ajax_save(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#1 ../wp-content/plugins/elementor/core/common/modules/ajax/module.php(176): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /wordpress/core/6.6.1/wp-includes/class-wp-hook.php(324): Elementor\Core\Common\Modules\Ajax\Module-&gt;handle_ajax_request(&#039;&#039;)
#3 /wordpress/core/6.6.1/wp-includes/class-wp-hook.php(348): WP_Hook-&gt;apply_filters(NULL, Array)
#4 /wordpress/core/6.6.1/wp-includes/plugin.php(517): WP_Hook-&gt;do_action(Array)
#5 /wordpress/core/6.6.1/wp-admin/admin-ajax.php(192): do_action(&#039;wp_ajax_element...&#039;)
#6 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-08-30 16:34:04 [error X 1][../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::155] Uncaught Error: Call to a member function get_edit_url() on bool in ../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:155
Stack trace:
#0 ../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(175): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;get_conditions_conflicts_by_location(&#039;include/general&#039;, &#039;header&#039;, 3712)
#1 ../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(112): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;get_conditions_conflicts(3712, &#039;include/general&#039;)
#2 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;ajax_check_conditions_conflicts(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 ../wp-content/plugins/elementor/core/common/modules/ajax/module.php(176): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#4 /wordpress/core/6.6.1/wp-includes/class-wp-hook.php(324): Elementor\Core\Common\Modules\Ajax\Module-&gt;handle_ajax_request(&#039;&#039;)
#5 /wordpress/core/6.6.1/wp-includes/class-wp-hook.php(348): WP_Hook-&gt;apply_filters(NULL, Array)
#6 /wordpress/core/6.6.1/wp-includes/plugin.php(517): WP_Hook-&gt;do_action(Array)
#7 /wordpress/core/6.6.1/wp-admin/admin-ajax.php(192): do_action(&#039;wp_ajax_element...&#039;)
#8 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-08-30 16:37:03 [warning X 2][../wp-content/plugins/elementor/modules/history/revisions-manager.php::363] Undefined array key &quot;editor_post_id&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 8 of 8JS: 2024-08-27 16:27:44 [error X 12]../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.24.0-dev1:3:955422] elementorFrontend is not defined 
JS: 2024-08-27 16:30:39 [error X 1]../_static/??-eJyVjEEOwiAQRS8kEJUEN8azIIzNVGYgDITrq00X7caky5f/3h9FIYfUI4iZxRBE9JCAgNsOFOFUfQNNyHqW0/jTfbctb5KQuf2MkvqELGY1cjVeBNpyNeBZfHjr2rkhwcH6VRcpKsqxJ5A1f9D97C7WOXu72g/aWVvw:6:17146] Cannot read properties of undefined (reading &#039;attributes&#039;) 
JS: 2024-08-30 21:04:38 [error X 1]../wp-content/plugins/elementor-pro/assets/js/nav-menu.e65811186e94a386ba7b.bundle.min.js:2:3894] Cannot read properties of null (reading &#039;stretch&#039;) 
JS: 2024-08-30 21:04:41 [error X 1]../wp-content/plugins/elementor-pro/assets/js/nav-menu.e65811186e94a386ba7b.bundle.min.js:2:4004] Cannot read properties of null (reading &#039;reset&#039;) 
JS: 2024-08-30 21:06:12 [error X 32]../wp-content/plugins/elementor/assets/js/web-cli.min.js?ver=3.24.0-dev1:3:82935] Data commands: `undefined` not found. 
JS: 2024-08-30 21:13:57 [error X 3]../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.24.0-dev1:3:714318] this.model.isValidChild is not a function 
JS: 2024-08-30 22:10:54 [error X 1]../wp-content/plugins/elementor/assets/js/packages/editor-documents/editor-documents.min.js?ver=3.24.0-dev1:1:2102] Cannot read properties of null (reading &#039;config&#039;) 
JS: 2024-08-30 23:13:14 [error X 1]../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.24.0-dev1:3:664837] Cannot read properties of undefined (reading &#039;isDesignable&#039;) 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Incompatible
	Premium Addons for Elementor: Incompatible

== Elementor Pro - Compatibility Tag ==
	
	Premium Addons for Elementor: Compatible

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by Daveden2** [comment]
Try deactivating **Improved CSS Loading** under **Elementor > Settings > Features**.

Then go to **Elementor > Tools** and regenerate your files and data.

Or start with the second option. It is most likely a caching issue.

**Comment by AYarb96** [comment]
It's still not working.  I've tried what you suggested above as well as rebuilding the menu several different ways, changing themes etc.  None of it fixes the issue.  I'm completely stumped.

**Comment by Daveden2** [comment]
Oh, wait a minute. I just checked your server information and it shows that you are using Elementor 3.24 dev-1. 
The developer edition should not be used on a production site. Please delete the developer plugin and roll back your elementor version to the stable release of Elementor 3.23.x under Elementor > Tools > Version Control. 
Then you can just clear your cache or regenerate CSS.

**Comment by AYarb96** [comment]
You are the best!  That fixed it.  Thank you so much!!!

**Comment by nicholaszein** [comment]
Hello @AYarb96!

Thank you for reaching out! 🙏 

We noticed that you're using the **_Elementor Beta (Developer Edition)_** plugin. This edition is a playground for developers to test their plugins and themes with the most recent features of Elementor, and **<ins>it's not quite intended for use on live websites.</ins>**

In the most recent release of this Developer Edition plugin, a conflict between the Core version (3.24.0-dev3) and older versions of the Pro plugin has caused an incompatibility in the rendering of the CSS. This should be fixed with the release of the Elementor Core (Free) version 3.24.0, and Elementor Pro version 3.24.0 tomorrow.

### 🧪 Due to the experimental nature of this Developer Edition plugin, we're unable to provide support for it. 

But don't worry! Our stable versions are full of great features that are ready for prime time on your website.

### 🔄 Please, [revert back to a stable version of Elementor](https://elementor.com/help/revert-to-release-from-developer-edition/) if you're working on a production site.

Kind regards
