### ISSUE TITLE
✅🐞 Social Icons Widget displaying incorrectly

### ISSUE THREAD

**Issue by maxms** [elementor/elementor#28676]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

The settings in the style tab of this widget don't seem to be passing to the rendered code. The size and padding are not correct in the page view in the editor or on the live page. See below.
<img width="151" alt="Screenshot 2024-09-11 at 3 33 55 PM" src="https://github.com/user-attachments/assets/eeb84fc6-2499-40f8-bdec-27c4fcd14b5a">

These are the settings I have:
<img width="360" alt="Screenshot 2024-09-11 at 3 44 22 PM" src="https://github.com/user-attachments/assets/a0a53ade-2b2c-4754-ac03-9579610e2f6f">

I was able to fix the display with this custom css:
```
selector .elementor-social-icon i {
    width: auto;
    height: auto;
}

selector .elementor-icon i:before {
    padding: .9em;
}
```

### Steps to reproduce

1. Add a Social Icons widget to a page
2. Style the widget and apply updates
3. View the styled widget in the editor or on the front end

### Expected behavior

Icon should be centered within padded background.

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt


== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.7.44
	PHP Version: 8.0.30
	PHP Memory Limit: 1G
	PHP Max Input Vars: 2000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.6.2
	Site URL: https://rdkcentral.com
	Home URL: https://rdkcentral.com
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 40M
	Max Memory limit: 1G
	Permalink Structure: /%postname%/
	Language: en_US
	Timezone: America/New_York
	Debug Mode: Inactive

== Theme ==
	Name: RDK
	Version: 0.1
	Author: Mary Makowsky for Actualize Marketing
	Child Theme: Yes
	Parent Theme Name: GeneratePress
	Parent Theme Version: 3.5.1
	Parent Theme Author: Tom Usborne

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36

== Active Plugins ==
	Better Search Replace
		Version: 1.4.7
		Author: WP Engine

	Check & Log Email
		Version: 2.0.1
		Author: checkemail

	Classic Editor
		Version: 1.6.4
		Author: WordPress Contributors

	Ele Custom Skin
		Version: 3.1.9
		Author: Dudaster.com

	Elementor
		Version: 3.24.0
		Author: Elementor.com

	Elementor Custom RDK Widgets
		Version: 1.0.0
		Author: Max Media Solutions

	Elementor Pro
		Version: 3.24.0
		Author: Elementor.com

	Enable Media Replace
		Version: 4.1.5
		Author: ShortPixel

	Essential Addons for Elementor
		Version: 6.0.4
		Author: WPDeveloper

	Essential Addons for Elementor - Pro
		Version: 6.0.3
		Author: WPDeveloper

	GP Premium
		Version: 2.5.0
		Author: Tom Usborne

	Health Check & Troubleshooting
		Version: 1.7.1
		Author: The WordPress.org community

	Lazy Load Control For Elementor
		Version: 0.0.3
		Author: Jose Mortellaro

	Ninja Forms
		Version: 3.8.15
		Author: Saturday Drive

	Ninja Forms - Conditional Logic
		Version: 3.1
		Author: The WP Ninjas

	Ninja Forms - Constant Contact
		Version: 3.1.1
		Author: The WP Ninjas

	Ninja Forms - Excel Export
		Version: 3.3.5
		Author: Saturday Drive

	Ninja Forms - File Uploads
		Version: 3.3.20
		Author: Saturday Drive

	Ninja Forms - Layout & Styles
		Version: 3.0.30
		Author: Saturday Drive

	Ninja Forms - PayPal
		Version: 3.0.4
		Author: Saturday Drive

	Ninja Forms - PayPal Express
		Version: 3.1.3
		Author: The WP Ninjas

	Orbit Fox Companion
		Version: 2.10.37
		Author: Themeisle

	Popup Maker
		Version: 1.19.2
		Author: Popup Maker

	Premium Addons for Elementor
		Version: 4.10.50
		Author: Leap13

	Redis Object Cache
		Version: 2.5.3
		Author: Till Krüss

	Safe Redirect Manager
		Version: 2.1.2
		Author: 10up

	Temporary Login Without Password
		Version: 1.8.3
		Author: StoreApps

	Track The Click
		Version: 0.4.0
		Author: Track The Click

	UpdraftPlus - Backup/Restore
		Version: 1.24.4
		Author: UpdraftPlus.Com, DavidAnderson

	Wordfence Security
		Version: 7.11.7
		Author: Wordfence

	WP-Optimize - Clean, Compress, Cache
		Version: 3.5.0
		Author: David Anderson, Ruhani Rabin, Team Updraft

	WP Webhooks
		Version: 3.3.2
		Author: Ironikus

	Yoast SEO
		Version: 23.4
		Author: Team Yoast


== Must-Use Plugins ==
	Health Check Troubleshooting Mode
		Version: 1.9.2
		Author: 

	WP.com Site Helper
		Version: 
		Author: 


== Elements Usage ==
	
	footer : 3
		button : 1
		container : 6
		heading : 1
		icon : 1
		nav-menu : 2
		search-form : 1
		social-icons : 1
		text-editor : 2
		theme-site-logo : 1
	page : 53
		divider : 8
		heading : 12
		image : 12
		spacer : 6
		text-editor : 26
		video : 1
	section : 35
		eael-team-member : 4
		heading : 2
		image : 43
	widget : 0
		eael-team-member : 1
	wp-post : 193
		button : 2
		container : 24
		divider : 18
		heading : 53
		icon : 8
		image : 51
		shortcode : 1
		spacer : 9
		text-editor : 136
		video : 9
	wp-page : 95
		button : 42
		divider : 78
		eael-lightbox : 27
		eael-team-member : 81
		form : 4
		heading : 226
		image : 399
		image-carousel : 2
		spacer : 4
		template : 2
		text-editor : 312
		video : 1


== Settings ==
	
	cpt_support: post, page
	disable_color_schemes: yes
	disable_typography_schemes: yes
	allow_tracking: yes
	unfiltered_files_upload: 1
	meta_generator_tag: 1


== Features ==
	Custom Fonts: 1
	Custom Icons: 4

== Integrations ==
	


== Elementor Experiments ==
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Additional Custom Breakpoints: Active by default
	Flexbox Container: Active
	Grid Container: Active by default
	Upgrade Swiper Library: Active by default
	Nested Elements Performance: Active by default
	Optimized Control Loading: Inactive by default
	Optimized Markup: Inactive by default
	Conditionally load Swiper CSS files: Inactive by default
	Plugin Onboarding: Active by default
	Default to New Theme Builder: Active by default
	Elementor Home Screen: Active by default
	Build with AI: Active by default
	Landing Pages: Active by default
	Launchpad Checklist: Inactive by default
	Nested Elements: Inactive by default
	Editor Top Bar: Inactive by default
	Element Caching: Inactive by default
	Link In Bio: Active by default
	Floating Buttons: Active by default
	Elementor Editor Events: Inactive by default
	Atomic Widgets: Inactive by default
	Display Conditions: Active by default
	Form Submissions: Active by default
	Menu: Inactive by default


== Log ==
	
Log: showing 20 of 282024-08-12 14:00:16 [info] Elementor/Upgrades - _on_each_version Finished 
2024-08-12 14:00:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.1',
  'to' => '3.23.4',
)]
2024-08-12 14:00:25 [info] elementor-pro::elementor_pro_updater Started 
2024-08-12 14:00:26 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-08-12 14:00:26 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-08-12 14:00:27 [info] elementor-pro::elementor_pro_updater Started 
2024-08-12 14:00:27 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-08-12 14:00:27 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-08-12 14:00:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.0',
  'to' => '3.23.3',
)]
2024-08-12 14:00:29 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.0',
  'to' => '3.23.3',
)]
2024-09-11 16:54:48 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.4',
  'to' => '3.24.0',
)]
2024-09-11 16:54:49 [info] elementor::elementor_updater Started 
2024-09-11 16:54:49 [info] Elementor/Upgrades - _on_each_version Start  
2024-09-11 16:54:52 [info] Elementor/Upgrades - _on_each_version Finished 
2024-09-11 16:54:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.4',
  'to' => '3.24.0',
)]
2024-09-11 16:54:53 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.4',
  'to' => '3.24.0',
)]
2024-09-11 16:57:48 [info] elementor-pro::elementor_pro_updater Started 
2024-09-11 16:57:48 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-09-11 16:57:48 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-09-11 16:57:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.3',
  'to' => '3.24.0',
)]

JS: showing 6 of 6JS: 2024-08-07 14:38:15 [error X 1][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.23.4:3:588967] Failed to read a named property 'elementorFrontend' from 'Window': Blocked a frame with origin ".." from accessing a cross-origin frame. 
JS: 2024-08-12 18:27:37 [error X 3][../wp-content/plugins/elementor/assets/js/common-modules.min.js?ver=3.23.4:2:56144] Model.isValidChild() should be implemented, please provide 'isValidChild' functionality. 
JS: 2024-08-12 18:34:11 [error X 4][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.23.4:3:1265357] Cannot read properties of null (reading 'getBoundingClientRect') 
JS: 2024-08-15 14:03:38 [error X 4][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.23.4:3:663451] Cannot read properties of undefined (reading 'isDesignable') 
JS: 2024-08-28 19:19:15 [error X 1][../wp-includes/js/underscore.min.js?ver=1.13.4:2:14731] Cannot read properties of undefined (reading 'replace') 
JS: 2024-09-03 15:00:50 [error X 1][../wp-includes/js/jquery/jquery.min.js?ver=3.7.1:2:28760] Cannot read properties of undefined (reading 'value') 

PHP: showing 9 of 9PHP: 2024-08-08 18:25:27 [error X 3][../wp-content/plugins/elementor/includes/compatibility.php::267] Uncaught TypeError: strpos(): Argument #1 ($haystack) must be of type string, array given in ../wp-content/plugins/elementor/includes/compatibility.php:267
Stack trace:
#0 ../wp-content/plugins/elementor/includes/compatibility.php(267): strpos(Array, 'elementor')
#1 ../wp-content/plugins/elementor/includes/compatibility.php(35): Elementor\Compatibility::polylang_compatibility()
#2 ../wp-content/plugins/elementor/includes/plugin.php(761): Elementor\Compatibility::register_actions()
#3 ../wp-content/plugins/elementor/includes/plugin.php(510): Elementor\Plugin->__construct()
#4 ../wp-content/plugins/elementor/includes/plugin.php(774): Elementor\Plugin::instance()
#5 ../wp-content/plugins/elementor/elementor.php(54): require('/home/rdkdev5/p...')
#6 ../wp-settings.php(391): include_once('/home/rdkdev5/p...')
#7 ../wp-config.php(91): require_once('/home/rdkdev5/p...')
#8 ../wp-load.php(37): require_once('/home/rdkdev5/p...')
#9 ../wp-blog-header.php(13): require_once('/home/rdkdev5/p...')
#10 ../index.php(17): require('/home/rdkdev5/p...')
#11 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-08-12 14:35:08 [warning X 1][../wp-content/plugins/elementor/core/files/file-types/svg.php::161] simplexml_load_file(): I/O warning : failed to load external entity "../wp-content/uploads/2024/08/Control-app_icon.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-08-12 14:35:10 [warning X 1][../wp-content/plugins/elementor/core/files/file-types/svg.php::161] simplexml_load_file(): I/O warning : failed to load external entity "../wp-content/uploads/2024/08/Easier-onboarding_icon.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-08-12 14:35:13 [warning X 1][../wp-content/plugins/elementor/core/files/file-types/svg.php::161] simplexml_load_file(): I/O warning : failed to load external entity "../wp-content/uploads/2024/08/Increased-app-visibility_icon.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-08-12 14:35:15 [warning X 1][../wp-content/plugins/elementor/core/files/file-types/svg.php::161] simplexml_load_file(): I/O warning : failed to load external entity "../wp-content/uploads/2024/08/Increased-reach_icon.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-08-12 14:35:17 [warning X 1][../wp-content/plugins/elementor/core/files/file-types/svg.php::161] simplexml_load_file(): I/O warning : failed to load external entity "../wp-content/uploads/2024/08/Large-app-catalog_icon.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-08-12 14:35:19 [warning X 1][../wp-content/plugins/elementor/core/files/file-types/svg.php::161] simplexml_load_file(): I/O warning : failed to load external entity "../wp-content/uploads/2024/08/Lower-costs_icon.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-08-12 14:35:21 [warning X 1][../wp-content/plugins/elementor/core/files/file-types/svg.php::161] simplexml_load_file(): I/O warning : failed to load external entity "../wp-content/uploads/2024/08/Toos-and-support_icon.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-08-12 14:36:14 [warning X 1][../wp-content/plugins/elementor/core/files/file-types/svg.php::161] simplexml_load_file(): I/O warning : failed to load external entity "../wp-content/uploads/2024/08/fast-to-market.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Custom RDK Widgets: Compatibility not specified
	Elementor Pro: Compatibility not specified
	Essential Addons for Elementor: Compatibility not specified
	Essential Addons for Elementor - Pro: Compatibility not specified
	Lazy Load Control For Elementor: Compatibility not specified
	Premium Addons for Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hello @maxms! 

Thank you for submitting your issue! 🙏 

We are aware of this issue and our team has already worked on a fix. Expect a solution to this issue in Elementor version 3.24.1! 😉

Best regards

**Comment by toineenzo** [comment]
Good to see a quick fix @nicholaszein :)

**Comment by toineenzo** [comment]
Related? https://github.com/elementor/elementor/issues/17931

**Comment by rinibak** [comment]
Thanks for offering the code, although I don't think width and height on auto is going to work for Firefox browser. Also, the code didn't work in my case. In fact, in my case, the social icons widget which is placed at the footer, has the following 3 issues:

1. on Chrome, it doesn't show at all at the front end

2. on Firefox, it shows the icons as not in the center of the circle but up top and to the left

3. on Elementor editor in the back end, when I click on the widget with the navigator, it takes me to the top of the page (header) and I can't see the social icons widget at all anywhere on the page. So although it takes me to the header (remember the social widget is in the footer not the header) I still can't see the widget at all, so I can't see whatever changes I make to it.

The whole thing sucks, as is. Please fix it quickly.

Thanks

**Comment by toineenzo** [comment]
> Thanks for offering the code, although I don't think width and height on auto is going to work for Firefox browser. Also, the code didn't work in my case. In fact, in my case, the social icons widget which is placed at the footer, has the following 3 issues:
> 
>     1. on Chrome, it doesn't show at all at the front end
> 
>     2. on Firefox, it shows the icons as not in the center of the circle but up top and to the left
> 
>     3. on Elementor editor in the back end, when I click on the widget with the navigator, it takes me to the top of the page (header) and I can't see the social icons widget at all anywhere on the page. So although it takes me to the header (remember the social widget is in the footer not the header) I still can't see the widget at all, so I can't see whatever changes I make to it.
> 
> 
> The whole thing sucks, as is. Please fix it quickly.
> 
> Thanks

Try adding this
selector .elementor-icon{
    display: flex;
}

**Comment by rinibak** [comment]
Hey, this code fixed everything! 
Thank you!

**Comment by nicholaszein** [comment]
Hey @toineenzo!

Thank you for sharing your workaround! I should have added this when I gave my answer yesterday.

Actually, the best temporary workaround should be to use the CSS below instead. Safari still has some weird behaviors with `display: flex` in some cases.

This is our official temporary workaround:

```css

.elementor-icon.elementoe-social-icon {
    display: inline-flex;
}

```

Hope this helps!

**Comment by lisaschiffli** [comment]
Prior to 3.24.0 the css class .elementor-social-icon with display: inline-flex followed and superseded .elementor-icon display: inline-block. This update flipped the two classes.

**Comment by nicholaszein** [comment]
Hey everyone!

We have great news! 🙌 

### 📢 We're happy to announce that we just released a patch that solves this issue! 🥳 

✅ Feel free to update Elementor and Elementor Pro to version 3.24.1!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
