### ISSUE TITLE
Error messages for loading CSS files for custom animations added through the filter

### ISSUE THREAD

**Issue by VadymPogorelov** [elementor/elementor#28727]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

1) I added some custom animations to the list ( using the filter ‘elementor/controls/animations/additional_animations’ ) https://prnt.sc/wL1vUCBTP2x7
2) After updating Elementor 3.24.0, it tries to load the styles of each animation from a separate file. Since the styles of the added animations are not in the Elementor folder (they are described in the CSS file of the theme), the editor shows many warnings about the impossibility to load the file https://prnt.sc/_LVu01I6izz-

It would be nice to do checks for the existence of files before trying to plug them in.

### Steps to reproduce

1) Add an additional animation to the list with the filter ‘elementor/controls/animations/additional_animations’
2) Update or Install Elementor 3.24.0
3) Open any page in the Editor
4) Many warnings appears in the developer console (F12) about the impossibility to load the file https://prnt.sc/_LVu01I6izz-

### Expected behavior

Elementor should not try to load style files for additional animations (not from its folder)

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
== Server Environment ==
	Operating System: WINNT
	Software: Apache
	MySQL version: mariadb.org binary distribution v10.8.4
	PHP Version: 7.4.30
	PHP Memory Limit: 1536M
	PHP Max Input Vars: 4000
	PHP Max Post Size: 1000M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.6.2
	Site URL: http://trex3.dev.themerex.dnw
	Home URL: http://trex3.dev.themerex.dnw
	WP Multisite: No
	Max Upload Size: 1,000 MB
	Memory limit: 128M
	Max Memory limit: 1536M
	Permalink Structure: /%postname%/
	Language: en_US
	Timezone: 2
	Admin Email: support@themerex.dnw
	Debug Mode: Active

== Theme ==
	Name: BaseKit
	Version: 1.0.0
	Author: ThemeREX
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:130.0) Gecko/20100101 Firefox/130.0

== Active Plugins ==
	Contact Form 7
		Version: 5.9.8
		Author: Takayuki Miyoshi

	Elementor
		Version: 3.24.2
		Author: Elementor.com

	LearnPress
		Version: 4.2.7.1
		Author: ThimPress

	MC4WP: Mailchimp for WordPress
		Version: 4.9.16
		Author: ibericode

	The Events Calendar
		Version: 6.6.4
		Author: The Events Calendar

	ThemeREX Addons
		Version: 2.30.2.3
		Author: ThemeREX

	ThemeREX Updater
		Version: 2.1.4
		Author: ThemeREX

	WooCommerce
		Version: 9.3.1
		Author: Automattic

	WP-Optimize - Clean, Compress, Cache
		Version: 3.5.0
		Author: David Anderson, Ruhani Rabin, Team Updraft

	WPBakery Page Builder
		Version: 7.9
		Author: Michael M - WPBakery.com


== Elementor Experiments ==
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Additional Custom Breakpoints: Inactive
	Flexbox Container: Active
	Grid Container: Active
	Upgrade Swiper Library: Active
	Nested Elements Performance: Active by default
	Optimized Control Loading: Active
	Optimized Markup: Inactive by default
	Conditionally load Swiper CSS files: Inactive by default
	Plugin Onboarding: Active by default
	Elementor Home Screen: Active by default
	Build with AI: Inactive
	Landing Pages: Active by default
	Launchpad Checklist: Inactive by default
	Nested Elements: Inactive by default
	Editor Top Bar: Inactive by default
	Element Caching: Inactive by default
	Link In Bio: Active by default
	Floating Buttons: Active by default
	Elementor Editor Events: Inactive by default
	Atomic Widgets: Inactive by default


== Log ==
	
Log: showing 19 of 192024-07-02 09:50:48 [info] Elementor/Upgrades - _on_each_version Start  
2024-07-02 09:50:48 [info] Elementor/Upgrades - _on_each_version Finished 
2024-07-02 09:50:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.22.2',
  'to' => '3.22.3',
)]
2024-07-17 12:57:26 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.22.3',
  'to' => '3.23.1',
)]
2024-07-17 12:57:29 [info] elementor::elementor_updater Started 
2024-07-17 12:57:29 [info] Elementor/Upgrades - _on_each_version Start  
2024-07-17 12:57:29 [info] Elementor/Upgrades - _on_each_version Finished 
2024-07-17 12:57:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.22.3',
  'to' => '3.23.1',
)]
2024-07-17 12:57:32 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.22.3',
  'to' => '3.23.1',
)]
2024-08-09 13:58:23 [info] elementor::elementor_updater Started 
2024-08-09 13:58:23 [info] Elementor/Upgrades - _on_each_version Start  
2024-08-09 13:58:23 [info] Elementor/Upgrades - _on_each_version Finished 
2024-08-09 13:58:23 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.1',
  'to' => '3.23.4',
)]
2024-09-11 08:59:41 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.4',
  'to' => '3.24.0',
)]
2024-09-11 08:59:44 [info] elementor::elementor_updater Started 
2024-09-11 08:59:44 [info] Elementor/Upgrades - _on_each_version Start  
2024-09-11 08:59:44 [info] Elementor/Upgrades - _on_each_version Finished 
2024-09-11 08:59:44 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.4',
  'to' => '3.24.0',
)]
2024-09-11 08:59:47 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.4',
  'to' => '3.24.0',
)]

JS: showing 17 of 17JS: 2024-07-09 12:23:37 [error X 15][http://trex3.dev.themerex.dnw/wp-content/plugins/elementor/assets/js/editor.js?ver=3.22.3:13946:13] containerOffset is undefined 
JS: 2024-07-11 14:30:59 [error X 1][http://trex3.dev.themerex.dnw/wp-content/plugins/elementor/assets/js/editor.js?ver=3.22.3:39486:32] selector.match is not a function 
JS: 2024-07-12 12:50:21 [error X 4][http://trex3.dev.themerex.dnw/wp-content/plugins/elementor/assets/js/editor.js?ver=3.22.3:40758:31] this.store.find(...) is undefined 
JS: 2024-07-19 09:46:23 [error X 2][http://trex3.dev.themerex.dnw/wp-content/plugins/elementor/assets/js/editor.js?ver=3.23.1:2271:8] controlView is undefined 
JS: 2024-07-23 08:22:36 [error X 26][http://trex3.dev.themerex.dnw/wp-content/plugins/elementor/assets/js/editor-modules.js?ver=3.23.1:945:46] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got as `icon` value. Expected array or object.',
)]
JS: 2024-07-24 07:00:25 [error X 6][http://trex3.dev.themerex.dnw/wp-content/plugins/elementor/assets/js/editor-modules.js?ver=3.23.1:945:46] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got as `select_feature_icon` value. Expected array or object.',
)]
JS: 2024-08-02 08:04:34 [error X 1][http://trex3.dev.themerex.dnw/wp-content/plugins/elementor/assets/js/editor-modules.js?ver=3.23.1:945:46] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `trx_elm_posts` got as `classic_author_icon` value. Expected array or object.',
)]
JS: 2024-08-05 16:05:06 [error X 1][http://trex3.dev.themerex.dnw/wp-content/plugins/elementor/assets/js/responsive-bar.js?ver=3.23.3:239:61] elementor.documents.currentDocument is null 
JS: 2024-08-06 09:19:56 [error X 2][http://trex3.dev.themerex.dnw/wp-content/plugins/elementor/assets/js/editor.js?ver=3.23.3:39512:7] conditions.terms is undefined 
JS: 2024-08-08 14:47:24 [error X 1][http://trex3.dev.themerex.dnw/wp-content/plugins/elementor/assets/js/editor.js?ver=3.23.4:30445:67] elementor.documents.getCurrent() is null 
JS: 2024-08-20 13:14:23 [error X 2][http://trex3.dev.themerex.dnw/wp-includes/js/wp-auth-check.js?ver=6.6.1:165:41] wrap is undefined 
JS: 2024-09-05 14:05:42 [error X 6][http://trex3.dev.themerex.dnw/wp-content/plugins/trx_addons/js/trx_addons.utils.js?reload=924014836:1644:24] txt is undefined 
JS: 2024-09-09 09:24:28 [error X 1][http://trex3.dev.themerex.dnw/wp-content/plugins/trx_addons/js/trx_addons.utils.js?reload=1401641499:1697:12] assignment to undeclared variable token 
JS: 2024-09-12 10:39:46 [error X 3][http://trex3.dev.themerex.dnw/wp-content/plugins/trx_addons/js/color-picker/lc_color_picker/lc_color_picker.js?reload=1243481886:1106:17] gradient_data.steps[0] is undefined 
JS: 2024-09-12 11:50:21 [error X 1][http://trex3.dev.themerex.dnw/wp-content/plugins/trx_addons/js/color-picker/lc_color_picker/lc_color_picker.js?reload=1101219611:266:0] Element.querySelector: &#039;#6qni6kzab&#039; is not a valid selector 
JS: 2024-09-13 10:13:05 [error X 3][http://trex3.dev.themerex.dnw/wp-content/plugins/trx_addons/components/api/elementor/params/trx-gradient/trx-gradient-control.js?reload=1099080574:27:13] this.setValue is not a function 
JS: 2024-09-13 12:35:35 [error X 1][http://trex3.dev.themerex.dnw/wp-content/plugins/trx_addons/js/color-picker/lc_color_picker/lc_color_picker.js?reload=1965632753:1132:4] el.classList is undefined 

PHP: showing 6 of 6PHP: 2024-07-17 12:57:18 [error X 1][C:\OSPanel\domains\trex3.dev.themerex.dnw\wp-content\plugins\elementor\includes\controls\repeater.php::20] Uncaught Error: Interface &#039;Elementor\Has_Validation&#039; not found in C:\OSPanel\domains\trex3.dev.themerex.dnw\wp-content\plugins\elementor\includes\controls\repeater.php:20
Stack trace:
#0 C:\OSPanel\domains\trex3.dev.themerex.dnw\wp-content\plugins\elementor\includes\autoloader.php(294): require()
#1 C:\OSPanel\domains\trex3.dev.themerex.dnw\wp-content\plugins\elementor\includes\autoloader.php(330): Elementor\Autoloader::load_class()
#2 [internal function]: Elementor\Autoloader::autoload()
#3 C:\OSPanel\domains\trex3.dev.themerex.dnw\wp-content\plugins\elementor\includes\managers\controls.php(470): spl_autoload_call()
#4 C:\OSPanel\domains\trex3.dev.themerex.dnw\wp-content\plugins\elementor\includes\managers\controls.php(623): Elementor\Controls_Manager-&gt;register_controls()
#5 C:\OSPanel\domains\trex3.dev.themerex.dnw\wp-content\plugins\elementor\includes\managers\controls.php(642): Elementor\Controls_Manager-&gt;get_controls()
#6 C:\OSPanel\domains\trex3.dev.themerex.dnw\wp-content\plugins\elementor\includes\man [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-07-17 16:09:00 [warning X 2][C:\OSPanel\domains\trex3.dev.themerex.dnw\wp-content\plugins\elementor\core\common\modules\ajax\module.php::274] Cannot modify header information - headers already sent by (output started at C:\OSPanel\domains\trex3.dev.themerex.dnw\wp-content\plugins\trx_addons\includes\plugin.debug.php:27) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-08-02 10:01:18 [error X 1][C:\OSPanel\domains\trex3.dev.themerex.dnw\wp-content\plugins\elementor\includes\managers\controls.php::844] Uncaught TypeError: array_merge(): Argument #2 must be of type array, string given in C:\OSPanel\domains\trex3.dev.themerex.dnw\wp-content\plugins\elementor\includes\managers\controls.php:844
Stack trace:
#0 C:\OSPanel\domains\trex3.dev.themerex.dnw\wp-content\plugins\elementor\includes\managers\controls.php(844): array_merge()
#1 C:\OSPanel\domains\trex3.dev.themerex.dnw\wp-content\plugins\elementor\includes\base\controls-stack.php(494): Elementor\Controls_Manager-&gt;add_control_to_stack()
#2 C:\OSPanel\domains\trex3.dev.themerex.dnw\wp-content\plugins\elementor\includes\base\sub-controls-stack.php(86): Elementor\Controls_Stack-&gt;add_control()
#3 C:\OSPanel\domains\trex3.dev.themerex.dnw\wp-content\plugins\elementor\includes\base\skin-base.php(168): Elementor\Sub_Controls_Stack-&gt;add_control()
#4 C:\OSPanel\domains\trex3.dev.themerex.dnw\wp-content\plugins\trx_addons\addons\elementor-widgets\classes\Widgets\Posts\Skins\BaseSkin.php(923): Elementor\Skin_Base-&gt;add_control()
#5 C:\OSPanel\domains\trex3.dev.themerex.dnw\wp-content\plugins\trx_addons\addons\elementor-widgets\classes\Widgets\Posts\Skins\BaseSkin.php(57): TrxAddons\ElementorWidgets\Widgets\Posts\Skins\BaseSkin-&gt;register_meta_controls()
#6 C:\OSPanel\domains\trex3.dev.themerex.dnw\wp-includes\class-wp-hook.php(326): TrxAddons\ElementorWidgets\Widgets\Posts\Skins\BaseSkin-&gt;register_controls()
#7 C:\OSPanel\domains\trex3.dev.themerex.dnw\wp-includes\class-wp-hook.php(348): WP_Hook-&gt;apply_filters()
#8 C:\OSPanel\domains\trex3.dev.themerex.dnw\wp-includes\plugin.php(517): WP_Hook-&gt;do_action()
#9 C:\OSPanel\domains\trex3.dev.themerex.dnw\wp-content\plugins\elementor\includes\base\controls-stack.php(1690): do_action()
#10 C:\OSPanel\domains\trex3.dev.themerex.dnw\wp-content\plugins\trx_addons\addons\elementor-widgets\classes\Widgets\Posts\PostsWidget.php(617): Elementor\Controls_Stack-&gt;end_controls_section()
#11 C:\OSPanel\domains\trex3.dev.themerex.dnw\wp-content\plugins\trx_addons\addons\elementor-widgets\classes\Widgets\Posts\PostsWidget.php(73): TrxAddons\ElementorWidgets\Widgets\Posts\PostsWidget-&gt;register_query_section_controls()
#12 C:\OSPanel\domains\trex3.dev.themerex.dnw\wp-content\plugins\elementor\includes\base\controls-stack.php(2386): TrxAddons\ElementorWidgets\Widgets\Posts\PostsWidget-&gt;register_controls()
#13 C:\OSPanel\domains\trex3.dev.themerex.dnw\wp-content\plugins\elementor\includes\base\widget-base.php(1065): Elementor\Controls_Stack-&gt;init_controls()
#14 C:\OSPanel\domains\trex3.dev.themerex.dnw\wp-content\plugins\elementor\includes\base\controls-stack.php(569): Elementor\Widget_Base-&gt;init_controls()
#15 C:\OSPanel\domains\trex3.dev.themerex.dnw\wp-content\plugins\elementor\includes\base\widget-base.php(192): Elementor\Controls_Stack-&gt;get_stack()
#16 C:\OSPanel\domains\trex3.dev.themerex.dnw\wp-content\plugins\elementor\includes\base\controls-stack.php(314): Elementor\Widget_Base-&gt;get_stack()
#17 C:\OSPanel\domains\trex3.dev.themerex.dnw\wp-content\plugins\elementor\includes\base\controls-stack.php(2475): Elementor\Controls_Stack-&gt;get_controls()
#18 C:\OSPanel\domains\trex3.dev.themerex.dnw\wp-content\plugins\elementor\includes\base\controls-stack.php(1158): Elementor\Controls_Stack-&gt;sanitize_settings()
#19 C:\OSPanel\domains\trex3.dev.themerex.dnw\wp-content\plugins\elementor\includes\base\element-base.php(593): Elementor\Controls_Stack-&gt;get_data()
#20 C:\OSPanel\domains\trex3.dev.themerex.dnw\wp-content\plugins\elementor\includes\base\widget-base.php(750): Elementor\Element_Base-&gt;get_raw_data()
#21 C:\OSPanel\domains\trex3.dev.themerex.dnw\wp-content\plugins\elementor\includes\base\element-base.php(598): Elementor\Widget_Base-&gt;get_raw_data()
#22 C:\OSPanel\domains\trex3.dev.themerex.dnw\wp-content\plugins\elementor\includes\base\element-base.php(598): Elementor\Element_Base-&gt;get_raw_data()
#23 C:\OSPanel\domains\trex3.dev.themerex.dnw\wp-content\plugins\elementor\includes\base\element-base.php(617): Elementor\Element_Base-&gt;get_raw_data()
#24 C:\OSPanel\domains\trex3.dev.themerex.dnw\wp-content\plugins\elementor\core\base\document.php(1083): Elementor\Element_Base-&gt;get_data_for_save()
#25 C:\OSPanel\domains\trex3.dev.themerex.dnw\wp-content\plugins\elementor\core\base\document.php(1346): Elementor\Core\Base\Document-&gt;get_elements_raw_data()
#26 C:\OSPanel\domains\trex3.dev.themerex.dnw\wp-content\plugins\elementor\core\base\document.php(856): Elementor\Core\Base\Document-&gt;save_elements()
#27 C:\OSPanel\domains\trex3.dev.themerex.dnw\wp-content\plugins\elementor\core\documents-manager.php(549): Elementor\Core\Base\Document-&gt;save()
#28 [internal function]: Elementor\Core\Documents_Manager-&gt;ajax_save()
#29 C:\OSPanel\domains\trex3.dev.themerex.dnw\wp-content\plugins\elementor\core\common\modules\ajax\module.php(176): call_user_func()
#30 C:\OSPanel\domains\trex3.dev.themerex.dnw\wp-includes\class-wp-hook.php(324): Elementor\Core\Common\Modules\Ajax\Module-&gt;handle_ajax_request()
#31 C:\OSPanel\domains\trex3.dev.themerex.dnw\wp-includes\class-wp-hook.php(348): WP_Hook-&gt;apply_filters()
#32 C:\OSPanel\domains\trex3.dev.themerex.dnw\wp-includes\plugin.php(517): WP_Hook-&gt;do_action()
#33 C:\OSPanel\domains\trex3.dev.themerex.dnw\wp-admin\admin-ajax.php(192): do_action()
#34 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-08-06 11:19:06 [warning X 2][C:\OSPanel\domains\trex3.dev.themerex.dnw\wp-content\plugins\elementor\includes\conditions.php::81] foreach() argument must be of type array|object, null given [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-09-05 11:07:02 [notice X 478][C:\OSPanel\domains\trex3.dev.themerex.dnw\wp-content\plugins\elementor\includes\managers\image.php::41] Undefined index: size [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-09-06 10:17:27 [warning X 4][C:\OSPanel\domains\trex3.dev.themerex.dnw\wp-content\plugins\elementor\includes\managers\controls.php::844] array_merge(): Expected parameter 2 to be an array, string given [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	The Events Calendar: Incompatible
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hello @VadymPogorelov! 

Thank you for submitting your issue! 🙏 

We are aware of this issue and our team is already working on a fix. We can’t say exactly when it'll be sorted out, but we kindly ask for your patience. Thanks for understanding! 😉

Best regards

**Comment by VadymPogorelov** [comment]
Fixed in 3.24.3, thank you
