### ISSUE TITLE
New Search Widget: Padding on Focus + "Normal" Padding

### ISSUE THREAD

**Issue by ricardoaraujo330** [elementor/elementor#28767]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Hello!

I was trying to implement the new search widget on my site with the dynamic search results option, but before that, while designing the widget, I found some problems that need to be fixed.

1. The border radius that is set in the ‘normal’ state is not respected in ‘focus’ mode. In other words, the border radius field is not properly adapted to respect both states. Either define a single border radius for both states, which might make sense, or clearly define a radius field for each state.
Here's a video that better illustrates the problem: [https://www.loom.com/share/10ca5d3446524a559f09fb5ff6d4190d](https://www.loom.com/share/10ca5d3446524a559f09fb5ff6d4190d)

2. the second problem is related to padding. Padding works on all sides except the left. In this example, I tried setting the margin to the right and the wipe icon moved, but if I set the padding to the left, the text remains very close to the left margin, without changing at all: [https://www.loom.com/share/ed3460094aeb4fdf925ef6a78107a815](https://www.loom.com/share/ed3460094aeb4fdf925ef6a78107a815)

### Steps to reproduce

Problem 1:
1. Drag the new search widget onto the page
2. Start customising the widget
3. set a border radius
4. The border radius applied will only work in the normal state. 
5. clicking on the input field will force the border radius of 8 all the way round the box.

Problem 2:
1. in the same field, try typing something
2. set a padding for the entire border
3. check that the padding is applied all around the box, except on the left-hand side.

### Expected behavior

Problem 1:
It was expected that the border radius would be applied to both the normal and focus state OR that there would be a specific radius field for the normal and focus state

Problem 2:
It was expected that padding would work for the left side as well

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.59 (Debian)
	MySQL version: mariadb.org binary distribution v10.4.34
	PHP Version: 7.4.33
	PHP Memory Limit: 4000M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 428M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.6.2
	Site URL: https://domain.com
	Home URL: https://domain.com
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 4000M
	Max Memory limit: 4000M
	Permalink Structure: /blog/%postname%/
	Language: pt_PT
	Timezone: Europe/Lisbon
	Admin Email: ola@domain.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 2.0.0
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 3.1.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: pt-PT
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36

== Active Plugins ==
	Admin Menu Editor Pro
		Version: 2.26.1
		Author: Janis Elsts

	AutomateWoo
		Version: 6.1.0
		Author: WooCommerce

	Chaty Pro
		Version: 3.3
		Author: Premio

	Converter for Media
		Version: 6.1.0
		Author: matt plugins - Optimize images by convert WebP & AVIF

	Elementor
		Version: 3.24.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.24.1
		Author: Elementor.com

	Facebook for WooCommerce
		Version: 3.2.9
		Author: Facebook

	GTM4WP - A Google Tag Manager (GTM) plugin for WordPress
		Version: 1.20.2
		Author: Thomas Geiger

	Invoicing with InvoiceXpress for WooCommerce - Pro
		Version: 5.8
		Author: PT Woo Plugins (by Webdados)

	JetElements For Elementor
		Version: 2.6.20.1
		Author: Crocoblock

	JetEngine
		Version: 3.5.5
		Author: Crocoblock

	JetFormBuilder
		Version: 3.4.2
		Author: Crocoblock

	JetFormBuilder User Login Action
		Version: 2.0.5
		Author: Crocoblock

	JetProductGallery
		Version: 2.1.18
		Author: Crocoblock

	JetSmartFilters
		Version: 3.5.5
		Author: Crocoblock

	JetTabs For Elementor
		Version: 2.2.4
		Author: Crocoblock

	JetWooBuilder - Products Grid Load More
		Version: 1.2.0
		Author: Crocoblock

	JetWooBuilder For Elementor
		Version: 2.1.14
		Author: Crocoblock

	Mailchimp for WooCommerce
		Version: 4.4
		Author: Mailchimp

	MRW
		Version: 4.3.1
		Author: Webubi

	Multibanco, MB WAY, Credit card, Payshop and Cofidis Pay (IfthenPay) for WooCommerce
		Version: 9.4.4
		Author: PT Woo Plugins (by Webdados)

	Order Delivery Date Pro for WooCommerce
		Version: 11.3.0
		Author: Tyche Softwares

	Portuguese Postcodes for WooCommerce
		Version: 5.9
		Author: PT Woo Plugins (by Webdados)

	Refer a Friend for WooCommerce PREMIUM
		Version: 4.1.4
		Author: WPGens

	Stock Dependencies for WooCommerce
		Version: 1.6.2
		Author: Kevin McCall

	Variation Swatches for WooCommerce
		Version: 2.1.2
		Author: Emran Ahmed

	Variation Swatches for WooCommerce - Pro
		Version: 2.1.4
		Author: Emran Ahmed

	Weglot Translate
		Version: 4.2.8
		Author: Weglot Translate team

	WooCommerce
		Version: 9.3.2
		Author: Automattic

	WooCommerce Email Customizer
		Version: 3.33
		Author: cxThemes

	WooCommerce Google Product Feed
		Version: 11.0.13
		Author: Ademti Software Ltd.

	WooCommerce Helper
		Version: 1.0.0
		Author: RicardoDevDomingues

	WooCommerce Sequential Order Numbers Pro
		Version: 1.21.3
		Author: SkyVerge

	WooCommerce Shipment Tracking
		Version: 2.5.0
		Author: WooCommerce

	WooCommerce Smart Coupons
		Version: 9.9.0
		Author: StoreApps

	WooCommerce Stripe Gateway
		Version: 8.7.0
		Author: WooCommerce

	WooCommerce Subscriptions
		Version: 6.6.2
		Author: WooCommerce

	WooCommerce Subscriptions Compatibility Addon
		Version: 1.5.0
		Author: Tyche Softwares

	WooCommerce Waitlist
		Version: 2.4.15
		Author: Neil Pie

	Woo Conditional Shipping and Payments
		Version: 2.0.3
		Author: Woo

	Woo Reviews for Google
		Version: 1.0
		Author: ICREATOR

	WP Mail SMTP Pro
		Version: 4.1.1
		Author: WP Mail SMTP

	WP Rocket
		Version: 3.16.4
		Author: WP Media

	YITH WooCommerce Bulk Product Editing Premium
		Version: 3.11.0
		Author: YITH

	YITH WooCommerce Product Add-ons &amp; Extra Options Premium
		Version: 4.16.0
		Author: YITH

	Yoast Duplicate Post
		Version: 4.5
		Author: Enrico Battocchi & Team Yoast

	Yoast SEO
		Version: 23.4
		Author: Team Yoast

	Yoast SEO Premium
		Version: 23.4
		Author: Team Yoast


== Must-Use Plugins ==
	WP STAGING Optimizer
		Version: 1.5.6
		Author: WP STAGING


== Funcionalidades ==
	Custom Fonts: 2
	Custom Icons: 2

== Integrações ==
	
	google_maps: Activo
	recaptcha_v3: Activo
	woocommerce: Activo


== Experiências com o Elementor ==
	Carregamento de CSS melhorado: Inativo por defeito
	Inline Font Icons: Activo
	Pontos de Quebra Adicionais: Activo
	Contentor Flexbox: Activo
	Contentor de Grelha: Activo
	Atualizar a Biblioteca Swiper: Inativo
	Desempenho dos elementos aninhados: Ativo por defeito
	Carregamento de Controlo Otimizado: Activo
	Marcação otimizada: Inativo por defeito
	Conditionally load Swiper CSS files: Inativo por defeito
	Integração de plug-ins: Ativo por defeito
	Predefinição para New Theme Builder: Activo
	Cabeçalho &amp; Rodapé: Inativo
	Ecrã inicial do Elementor: Ativo por defeito
	Construir com IA: Activo
	Landing Pages: Activo
	Launchpad Checklist: Inativo por defeito
	Elementos Aninhados: Activo
	Barra Superior do Editor: Activo
	Páginas Painel: Inativo por defeito
	Cache de Elementos: Activo
	Link In Bio: Ativo por defeito
	Botões Flutuantes: Ativo por defeito
	Eventos do Editor Elementor: Inativo por defeito
	Atomic Widgets: Inativo por defeito
	Condições de Exibição: Activo
	Submissão de formulários: Inativo
	Menu: Activo


== Registos ==
	
PHP: showing 8 of 8PHP: 2024-09-11 21:06:37 [warning X 1][/home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-content/plugins/elementor-pro/modules/forms/actions/email.php::352] unlink(/home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-content/uploads/elementor/forms/66e1f84c54af1.pdf): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-09-12 23:13:07 [notice X 3][/home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined index: condition_type [array (
  'trace' => '
#0: /home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2024-09-16 22:57:18 [warning X 1][/home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-content/plugins/elementor-pro/modules/forms/actions/email.php::352] unlink(/home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-content/uploads/elementor/forms/66e8a9bc044e9.pdf): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-09-17 22:25:02 [error X 2][/home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-content/plugins/elementor-pro/modules/mega-menu/module.php::24] Uncaught Error: Class &#039;ElementorPro\Modules\MegaMenu\Controls\Control_Menu_Dropdown_Animation&#039; not found in /home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-content/plugins/elementor-pro/modules/mega-menu/module.php:24
Stack trace:
#0 /home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-includes/class-wp-hook.php(324): ElementorPro\Modules\MegaMenu\Module-&gt;ElementorPro\Modules\MegaMenu\{closure}()
#1 /home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-includes/class-wp-hook.php(348): WP_Hook-&gt;apply_filters()
#2 /home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-includes/plugin.php(517): WP_Hook-&gt;do_action()
#3 /home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-content/plugins/elementor/includes/managers/controls.php(510): do_action()
#4 /home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-content/plugins/elementor/includes/managers/controls.php(623): Elementor\Controls_Manager-&gt;register_controls()
#5 /home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-content/plugi [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-09-17 22:25:14 [error X 6][/home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-content/plugins/elementor-pro/modules/slides/module.php::21] Uncaught Error: Class &#039;ElementorPro\Modules\Slides\Controls\Control_Slides_Animation&#039; not found in /home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-content/plugins/elementor-pro/modules/slides/module.php:21
Stack trace:
#0 /home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-includes/class-wp-hook.php(324): ElementorPro\Modules\Slides\Module-&gt;ElementorPro\Modules\Slides\{closure}()
#1 /home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-includes/class-wp-hook.php(348): WP_Hook-&gt;apply_filters()
#2 /home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-includes/plugin.php(517): WP_Hook-&gt;do_action()
#3 /home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-content/plugins/elementor/includes/managers/controls.php(510): do_action()
#4 /home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-content/plugins/elementor/includes/managers/controls.php(623): Elementor\Controls_Manager-&gt;register_controls()
#5 /home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-content/plugins/elementor/inc [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-09-17 22:26:26 [error X 1][/home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-content/plugins/elementor/core/base/module.php::350] Uncaught Error: Class &#039;ElementorPro\Modules\Woocommerce\Widgets\Checkout&#039; not found in /home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-content/plugins/elementor/core/base/module.php:350
Stack trace:
#0 /home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-includes/class-wp-hook.php(324): Elementor\Core\Base\Module-&gt;init_widgets()
#1 /home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-includes/class-wp-hook.php(348): WP_Hook-&gt;apply_filters()
#2 /home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-includes/plugin.php(517): WP_Hook-&gt;do_action()
#3 /home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-content/plugins/elementor/includes/managers/widgets.php(145): do_action()
#4 /home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-content/plugins/elementor/includes/managers/widgets.php(344): Elementor\Widgets_Manager-&gt;init_widgets()
#5 /home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-content/plugins/elementor-pro/modules/posts/traits/pagination-trait.php(34): Elementor\Wid [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-09-18 00:51:25 [notice X 6][/home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-content/plugins/elementor/core/dynamic-tags/manager.php::64] Array to string conversion [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-content/plugins/elementor/core/dynamic-tags/manager.php(64): class type preg_replace_callback()
#2: /home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-content/plugins/elementor/includes/controls/base-data.php(91): Elementor\Core\DynamicTags\Manager -> parse_tags_text()
#3: /home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(1329): Elementor\Base_Data_Control -> parse_tags()
#4: /home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(1308): Elementor\Controls_Stack -> parse_dynamic_settings()
',
)]
PHP: 2024-09-19 10:30:07 [notice X 519][/home/1090615.cloudwaysapps.com/amqzkxvawh/public_html/wp-content/plugins/elementor/core/dynamic-tags/manager.php::64] Array to string conversion [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 18 of 18JS: 2024-09-12 22:51:54 [error X 1][https://domain.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view28053&quot;) has already been destroyed and cannot be used. 
JS: 2024-09-12 22:51:54 [error X 1][https://domain.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view28425&quot;) has already been destroyed and cannot be used. 
JS: 2024-09-12 22:51:54 [error X 1][https://domain.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view28515&quot;) has already been destroyed and cannot be used. 
JS: 2024-09-12 22:51:54 [error X 1][https://domain.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view28605&quot;) has already been destroyed and cannot be used. 
JS: 2024-09-12 22:51:54 [error X 1][https://domain.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view28698&quot;) has already been destroyed and cannot be used. 
JS: 2024-09-12 22:51:54 [error X 1][https://domain.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view28785&quot;) has already been destroyed and cannot be used. 
JS: 2024-09-12 22:51:54 [error X 1][https://domain.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view29066&quot;) has already been destroyed and cannot be used. 
JS: 2024-09-12 22:51:54 [error X 1][https://domain.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view29292&quot;) has already been destroyed and cannot be used. 
JS: 2024-09-12 22:51:54 [error X 1][https://domain.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view29894&quot;) has already been destroyed and cannot be used. 
JS: 2024-09-12 22:51:54 [error X 1][https://domain.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view29984&quot;) has already been destroyed and cannot be used. 
JS: 2024-09-12 22:51:54 [error X 1][https://domain.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view30074&quot;) has already been destroyed and cannot be used. 
JS: 2024-09-12 22:51:54 [error X 1][https://domain.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view30167&quot;) has already been destroyed and cannot be used. 
JS: 2024-09-12 22:51:54 [error X 1][https://domain.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view30254&quot;) has already been destroyed and cannot be used. 
JS: 2024-09-12 22:51:54 [error X 1][https://domain.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view30535&quot;) has already been destroyed and cannot be used. 
JS: 2024-09-12 22:53:10 [error X 60][https://domain.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.23.4:3:693233] elementorFrontend.elements.window.jQuery is not a function 
JS: 2024-09-12 22:53:10 [error X 20][https://domain.com/wp-includes/js/jquery/jquery.min.js?ver=3.7.1:2:85576] Cannot read properties of null (reading &#039;clientHeight&#039;) 
JS: 2024-09-16 15:13:56 [error X 1][https://domain.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.23.4:3:712932] this.model.isValidChild is not a function 
JS: 2024-09-18 21:56:27 [error X 1][https://domain.com/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.24.2:2:17146] Cannot read properties of undefined (reading &#039;attributes&#039;) 

Log: showing 16 of 162024-09-17 22:23:07 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.4',
  'to' => '3.24.2',
)]
2024-09-17 22:23:09 [info] elementor::elementor_updater Started 
2024-09-17 22:23:09 [info] Elementor/Upgrades - _on_each_version Start  
2024-09-17 22:23:09 [info] Elementor/Upgrades - _on_each_version Finished 
2024-09-17 22:23:09 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.4',
  'to' => '3.24.2',
)]
2024-09-17 22:23:10 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.4',
  'to' => '3.24.2',
)]
2024-09-17 22:24:46 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.3',
  'to' => '3.24.1',
)]
2024-09-17 22:24:47 [info] elementor-pro::elementor_pro_updater Started 
2024-09-17 22:24:47 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-09-17 22:24:47 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-09-17 22:24:47 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.3',
  'to' => '3.24.1',
)]
2024-09-19 10:28:00 [info] elementor::elementor_updater Started 
2024-09-19 10:28:00 [info] Elementor/Upgrades - _on_each_version Start  
2024-09-19 10:28:00 [info] Elementor/Upgrades - _on_each_version Finished 
2024-09-19 10:28:00 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.24.2',
  'to' => '3.24.3',
)]
2024-09-19 10:28:02 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.24.2',
  'to' => '3.24.3',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibilidade não especificada
	JetElements For Elementor: Compatibilidade não especificada
	JetTabs For Elementor: Compatibilidade não especificada
	JetWooBuilder For Elementor: Compatibilidade não especificada

== Elementor Pro - Compatibility Tag ==
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by Ahmed-khalil3** [comment]
try this
https://bit.ly/3TyLBMS

you may need to install the c compiler

**Comment by ricardoaraujo330** [comment]
Hello,

I just want to share that I've been investigating a bit more and:

1. regarding this point, it seems that the border radius is coming from the general settings of the elementor kit > form fields > border radius. I therefore think that the search field in this widget, allowing you to customise these parts, should have a more specific id or class to take precedence over the kit's general settings.

2. Regarding padding on the left, the problem is exactly the same, I just don't know why it only happens on the left and not with the others...
