### ISSUE TITLE
⛔ 🧩 Javascript error with custom widget's scripts in Elementor version 3.24.x when logged in

### ISSUE THREAD

**Issue by bdkoder** [elementor/elementor#28788]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

![image](https://github.com/user-attachments/assets/3bcac6e3-224c-4393-a892-bee61498e47e)

Please guys, don't talk about 3rd party, the issue is from your side.

#24047

@mccicorp

### Steps to reproduce

Simple, within the frontEnd

### Expected behavior

Not working widgets & global widgets

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
== Server Environment ==
	Operating System: Darwin
	Software: nginx/1.16.0
	MySQL version: MySQL Community Server - GPL v8.0.16
	PHP Version: 8.1.29
	PHP Memory Limit: 256M
	PHP Max Input Vars: 4000
	PHP Max Post Size: 1000M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.6.2
	Site URL: http://192.168.1.111
	Home URL: http://192.168.1.111
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en_US
	Timezone: Asia/Dhaka
	Admin Email: dev-email@wpengine.local
	Debug Mode: Active

== Theme ==
	Name: Astra Child
	Version: 1.0.0
	Author: Brainstorm Force
	Child Theme: Yes
	Parent Theme Name: Astra
	Parent Theme Version: 4.8.1
	Parent Theme Author: Brainstorm Force

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36

== Active Plugins ==
	Augmented Reality Viewer - 3D Model Viewer
		Version: 1.1.0
		Author: BdThemes

	Elementor
		Version: 3.24.3
		Author: Elementor.com

	Element Pack Pro
		Version: 7.15.7
		Author: BdThemes

	Wheel of Fortune
		Version: 0.0.1
		Author: bdthemes

	ZoloBlocks
		Version: 1.3.3
		Author: BdThemes


== Elements Usage ==
	
	section : 1
		button : 1
		container : 1
	wp-post : 0
		container : 1
		heading : 1
	wp-page : 6
		bdt-chart : 1
		bdt-circle-info : 1
		bdt-image-compare : 1
		bdt-panel-slider : 1
		button : 1
		container : 53
		heading : 12
		icon-list : 1
		image : 11
		text-editor : 4


== Settings ==
	
	cpt_support: post, page
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap


== Elementor Experiments ==
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Active by default
	Additional Custom Breakpoints: Active by default
	Flexbox Container: Active
	Grid Container: Active by default
	Upgrade Swiper Library: Active
	Nested Elements Performance: Active by default
	Optimized Control Loading: Active by default
	Optimized Markup: Inactive by default
	Conditionally load Swiper CSS files: Inactive by default
	Plugin Onboarding: Active by default
	Elementor Home Screen: Active by default
	Build with AI: Inactive
	Landing Pages: Inactive by default
	Launchpad Checklist: Inactive by default
	Nested Elements: Inactive by default
	Editor Top Bar: Inactive by default
	Element Caching: Inactive
	Link In Bio: Active by default
	Floating Buttons: Active by default
	Elementor Editor Events: Inactive by default
	Atomic Widgets: Inactive by default


== Log ==
	
Log: showing 20 of 242024-09-12 12:11:05 [info] elementor-pro::elementor_pro_updater Started 
2024-09-12 12:11:05 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-09-12 12:11:05 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-09-12 12:11:05 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.3',
  'to' => '3.24.0',
)]
2024-09-12 12:11:05 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.3',
  'to' => '3.24.0',
)]
2024-09-14 05:13:29 [info] elementor::elementor_updater Started 
2024-09-14 05:13:29 [info] Elementor/Upgrades - _on_each_version Start  
2024-09-14 05:13:29 [info] Elementor/Upgrades - _on_each_version Finished 
2024-09-14 05:13:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.24.0',
  'to' => '3.24.2',
)]
2024-09-14 05:13:29 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.24.0',
  'to' => '3.24.2',
)]
2024-09-14 05:13:39 [info] elementor-pro::elementor_pro_updater Started 
2024-09-14 05:13:39 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-09-14 05:13:39 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-09-14 05:13:39 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.24.0',
  'to' => '3.24.1',
)]
2024-09-14 05:13:39 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.24.0',
  'to' => '3.24.1',
)]
2024-09-22 17:13:36 [info] elementor::elementor_updater Started 
2024-09-22 17:13:36 [info] Elementor/Upgrades - _on_each_version Start  
2024-09-22 17:13:37 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.24.2',
  'to' => '3.24.3',
)]
2024-09-22 17:13:38 [info] Elementor/Upgrades - _on_each_version Finished 
2024-09-22 17:13:38 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.24.2',
  'to' => '3.24.3',
)]

PHP: showing 4 of 4PHP: 2024-09-11 05:27:35 [warning X 1][/Users/shahidul/Local Sites/ep-dev/app/public/wp-content/plugins/elementor/core/files/uploads-manager.php::647] rmdir(/Users/shahidul/Local Sites/ep-dev/app/public/wp-content/uploads/elementor/tmp/): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-09-12 06:23:33 [warning X 9][/Users/shahidul/Local Sites/ep-dev/app/public/wp-content/plugins/elementor/includes/elements/container.php::1874] Undefined array key "size" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-09-14 06:00:29 [warning X 5][/Users/shahidul/Local Sites/ep-dev/app/public/wp-content/plugins/elementor/core/page-assets/loader.php::97] Undefined array key "version" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-09-17 17:55:44 [error X 2][/Users/shahidul/Local Sites/ep-dev/app/public/wp-content/plugins/elementor/core/editor/editor.php::250] Uncaught Error: Call to a member function get_component() on null in /Users/shahidul/Local Sites/ep-dev/app/public/wp-content/plugins/elementor/core/editor/editor.php:250
Stack trace:
#0 /Users/shahidul/Local Sites/ep-dev/app/public/wp-content/plugins/bdthemes-element-pack/modules/particles/module.php(90): Elementor\Core\Editor\Editor->is_edit_mode(192)
#1 /Users/shahidul/Local Sites/ep-dev/app/public/wp-includes/class-wp-hook.php(324): ElementPack\Modules\Particles\Module->enqueue_scripts('')
#2 /Users/shahidul/Local Sites/ep-dev/app/public/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#3 /Users/shahidul/Local Sites/ep-dev/app/public/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /Users/shahidul/Local Sites/ep-dev/app/public/wp-includes/script-loader.php(2263): do_action('wp_enqueue_scri...')
#5 /Users/shahidul/Local Sites/ep-dev/app/public/wp-includes/class-wp-hook.php(324): wp_enqueue_scripts('')
#6 /Users/shahidul/Local Sites/ep-dev/app/public/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#7 /Users/shahidul/Local Sites/ep-dev/app/public/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#8 /Users/shahidul/Local Sites/ep-dev/app/public/wp-includes/general-template.php(3065): do_action('wp_head')
#9 /Users/shahidul/Local Sites/ep-dev/app/public/wp-content/themes/astra/header.php(31): wp_head()
#10 /Users/shahidul/Local Sites/ep-dev/app/public/wp-includes/template.php(810): require_once('/Users/shahidul...')
#11 /Users/shahidul/Local Sites/ep-dev/app/public/wp-includes/template.php(745): load_template('/Users/shahidul...', true, Array)
#12 /Users/shahidul/Local Sites/ep-dev/app/public/wp-includes/general-template.php(48): locate_template(Array, true, true, Array)
#13 /Users/shahidul/Local Sites/ep-dev/app/public/wp-content/plugins/elementor/modules/page-templates/templates/header-footer.php(9): get_header()
#14 /Users/shahidul/Local Sites/ep-dev/app/public/wp-includes/template-loader.php(106): include('/Users/shahidul...')
#15 /Users/shahidul/Local Sites/ep-dev/app/public/wp-blog-header.php(19): require_once('/Users/shahidul...')
#16 /Users/shahidul/Local Sites/ep-dev/app/public/index.php(17): require('/Users/shahidul...')
#17 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 14 of 14JS: 2024-09-12 10:43:10 [error X 4][http://192.168.1.111/wp-includes/js/underscore.min.js?ver=1.13.4:2:15198] Unexpected token ')' 
JS: 2024-09-12 11:24:09 [error X 2][http://192.168.1.111/wp-content/plugins/elementor/assets/js/editor.js?ver=3.24.0:41212:71] Cannot read properties of undefined (reading 'toLowerCase') 
JS: 2024-09-12 11:24:15 [error X 4][http://192.168.1.111/wp-content/plugins/elementor/assets/js/editor.js?ver=3.24.0:41240:11] Cannot read properties of undefined (reading 'localized') 
JS: 2024-09-14 05:12:30 [error X 1][http://192.168.1.111/wp-content/plugins/bdthemes-element-pack/assets/js/ep-scripts.js?ver=7.15.0:3516:28] GMaps is not defined 
JS: 2024-09-14 05:31:50 [error X 15][http://192.168.1.111/wp-content/plugins/bdthemes-element-pack/assets/js/modules/ep-marker.js?ver=7.15.1:21:4] tippy is not defined 
JS: 2024-09-17 05:55:39 [error X 37][http://192.168.1.111/wp-content/plugins/bdthemes-element-pack/assets/js/modules/ep-particles.js?ver=7.15.5:160:21] particlesJS is not defined 
JS: 2024-09-17 05:55:39 [error X 7][http://192.168.1.111/wp-content/plugins/bdthemes-element-pack/assets/js/modules/ep-animated-gradient-background.js?ver=7.15.5:48:30] Granim is not defined 
JS: 2024-09-17 05:55:39 [error X 9][http://192.168.1.111/wp-content/plugins/bdthemes-element-pack/assets/js/modules/ep-confetti-effects.js?ver=7.15.5:234:29] confetti is not defined 
JS: 2024-09-17 05:55:39 [error X 7][http://192.168.1.111/wp-content/plugins/bdthemes-element-pack/assets/js/modules/ep-cursor-effects.js?ver=7.15.5:63:13] Cotton is not defined 
JS: 2024-09-17 05:55:39 [error X 6][http://192.168.1.111/wp-content/plugins/bdthemes-element-pack/assets/js/modules/ep-ripple-effects.js?ver=7.15.5:77:44] $.ripple is not a function 
JS: 2024-09-17 05:55:39 [error X 6][http://192.168.1.111/wp-content/plugins/bdthemes-element-pack/assets/js/modules/ep-reveal-effects.js?ver=7.15.5:29:34] RevealFx is not defined 
JS: 2024-09-17 05:55:39 [error X 7][http://192.168.1.111/wp-content/plugins/bdthemes-element-pack/assets/js/modules/ep-threed-text.js?ver=7.15.5:71:28] Ztextify is not defined 
JS: 2024-09-17 06:17:08 [error X 77][http://192.168.1.111/wp-content/plugins/bdthemes-element-pack/assets/js/modules/ep-particles.js?ver=7.15.5:5:55] Cannot read properties of undefined (reading 'handlers') 
JS: 2024-09-17 06:17:13 [error X 73][http://192.168.1.111/wp-includes/js/jquery/jquery.js?ver=3.7.1:3793:3] Cannot read properties of undefined (reading 'tools') 



== Elementor - Compatibility Tag ==
	
	Element Pack Pro: Compatible
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by bdkoder** [comment]
The problems for Logged In users.

**Comment by rhino-corey** [comment]
Why is this closed? This problem is being reported by more and more devs. The 3.24.x releases have broken our widgets when a user is logged in. Can someone from Elementor please look into this.
