### ISSUE TITLE
hiding offcanvas doesn't work well with 2 or more. / problem shown in the video

### ISSUE THREAD

**Issue by DanielCyran** [elementor/elementor#28853]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

hiding offcanvas doesn't work well with 2 or more. / problem shown in the video

https://github.com/user-attachments/assets/0b76ddc0-6db7-4186-bc45-a78e1205c2d6

### Steps to reproduce

add for example two or more offcanvas widgets and try to open them and you will see that the previous one does not always close

### Expected behavior

I expect that when I open a new offcanvas, the old one will close before it

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.5.26
	PHP Version: 8.1.29
	PHP Memory Limit: 32G
	PHP Max Input Vars: 100000
	PHP Max Post Size: 10G
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.6.2
	Site URL: https://aderlo.pl
	Home URL: https://aderlo.pl
	WP Multisite: No
	Max Upload Size: 10 GB
	Memory limit: 32G
	Max Memory limit: 10G
	Permalink Structure: /%postname%/
	Language: pl_PL
	Timezone: 2
	Admin Email: danielcyran95@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 3.1.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: pl-PL
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0

== Active Plugins ==
        Classic Widgets
		Version: 0.3
		Author: WordPress Contributors

	Elementor
		Version: 3.25.0-latest-1727692321
		Author: Elementor.com

	Elementor Pro
		Version: 3.24.2
		Author: Elementor.com

	Klaviyo
		Version: 3.4.0
		Author: Klaviyo, Inc.

	LiteSpeed Cache
		Version: 6.5.1
		Author: LiteSpeed Technologies

	Loco Translate
		Version: 2.6.11
		Author: Tim Whitlock

	Query Monitor
		Version: 3.16.4
		Author: John Blackbourn

	ShopLentor Pro – WooCommerce Builder for Elementor &amp; Gutenberg
		Version: 2.5.0
		Author: HasThemes

	ShopLentor – WooCommerce Builder for Elementor &amp; Gutenberg
		Version: 2.9.8
		Author: HasThemes

	Tpay Payment Gateway
		Version: 1.7.1
		Author: Krajowy Integrator Płatności S.A.

	WooCommerce
		Version: 9.4.0-beta.1
		Author: Automattic

	WooCommerce Hurtownie - Zarządzanie i logowanie
		Version: 4.5
		Author: Twoje Imię

	Yoast SEO
		Version: 23.5
		Author: Team Yoast


== Must-Use Plugins ==
	Super Speedy Search Fast Ajax
		Version: 1.07
		Author: Dave Hilditch

	WordPress automation by Installatron
		Version: 
		Author: 

	wp-hide-loader.php
		Version: 
		Author: 


== Składniki oferty ==
	Custom Fonts: 0
	Custom Icons: 0

== Integracje ==
	woocommerce: Aktywny


== Eksperymenty z Elementorem ==
	Poprawione ładowanie CSS: Domyślnie nieaktywne
	Czcionka ikon: Włączono
	Dodatkowe niestandardowe punkty zmiany: Domyślnie aktywne
	Kontener: Włączono
	Upgrade Swiper Library: Domyślnie aktywne
	Nested Elements Performance: Domyślnie aktywne
	Optimized Control Loading: Włączono
	Optimized Markup: Domyślnie nieaktywne
	Conditionally load Swiper CSS files: Domyślnie nieaktywne
	Plugin Onboarding: Domyślnie aktywne
	CSS Smooth Scroll: Domyślnie aktywne
	Default to New Theme Builder: Domyślnie aktywne
	Header &amp; Footer: Nieaktywne
	Elementor Home Screen: Domyślnie aktywne
	Strony docelowe: Włączono
	Elementy zagnieżdżone: Włączono
	Editor Top Bar: Domyślnie aktywne
	Pages Panel: Domyślnie nieaktywne
	Element Caching: Włączono
	Link In Bio: Domyślnie aktywne
	Floating Buttons: Domyślnie aktywne
	Elementor Editor Events: Domyślnie nieaktywne
	Atomic Widgets: Domyślnie nieaktywne
	Launchpad Checklist: Domyślnie nieaktywne
	Wyświetl warunki: Włączono
	Form Submissions: Nieaktywne
	Menu: Włączono


== Dziennik ==
Log: showing 14 of 142024-09-18 17:24:51 [info] elementor-pro::elementor_pro_updater Started 
2024-09-18 17:24:51 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-09-18 17:24:51 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-09-18 17:24:51 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.24.1',
  'to' => '3.24.2',
)]
2024-09-23 15:09:59 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.24.3',
  'to' => '3.24.4',
)]
2024-09-23 15:12:02 [info] elementor::elementor_updater Started 
2024-09-23 15:12:02 [info] Elementor/Upgrades - _on_each_version Start  
2024-09-23 15:12:02 [info] Elementor/Upgrades - _on_each_version Finished 
2024-09-23 15:12:02 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.24.3',
  'to' => '3.24.4',
)]
2024-09-30 14:27:09 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.24.4',
  'to' => '3.25.0-latest-1727692321',
)]
2024-09-30 14:28:03 [info] elementor::elementor_updater Started 
2024-09-30 14:28:03 [info] Elementor/Upgrades - _on_each_version Start  
2024-09-30 14:28:03 [info] Elementor/Upgrades - _on_each_version Finished 
2024-09-30 14:28:03 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.24.4',
  'to' => '3.25.0-latest-1727692321',
)]

PHP: showing 7 of 7PHP: 2024-09-18 18:52:30 [notice X 283][/home/aderlopl/domains/aderlo.pl/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php::229] hexdec(): Passing null to parameter #1 ($hex_string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-09-20 18:35:30 [error X 1][/home/aderlopl/domains/aderlo.pl/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php::328] Out of memory (allocated 937775104) (tried to allocate 40960 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-09-20 22:24:03 [notice X 2][/home/aderlopl/domains/aderlo.pl/public_html/wp-content/plugins/elementor-pro/modules/screenshots/module.php::33] Function utf8_decode() is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-09-23 12:29:36 [error X 19][/home/aderlopl/domains/aderlo.pl/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php::945] Uncaught TypeError: Elementor\TemplateLibrary\Source_Local::post_row_actions(): Argument #2 ($post) must be of type WP_Post, null given, called in /home/aderlopl/domains/aderlo.pl/public_html/wp-includes/class-wp-hook.php on line 324 and defined in /home/aderlopl/domains/aderlo.pl/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php:945
Stack trace:
#0 /home/aderlopl/domains/aderlo.pl/public_html/wp-includes/class-wp-hook.php(324): Elementor\TemplateLibrary\Source_Local-&gt;post_row_actions()
#1 /home/aderlopl/domains/aderlo.pl/public_html/wp-includes/plugin.php(205): WP_Hook-&gt;apply_filters()
#2 /home/aderlopl/domains/aderlo.pl/public_html/wp-admin/includes/class-wp-posts-list-table.php(1595): apply_filters()
#3 /home/aderlopl/domains/aderlo.pl/public_html/wp-admin/includes/class-wp-list-table.php(1803): WP_Posts_List_Table-&gt;handle_row_actions()
#4 /home/aderlopl/domains/aderlo.pl/public_html/wp-admin/includes/class-wp-posts-list-table.php(1432): WP_List_Table-&gt;single_row_columns()
#5 /home/aderlopl/domains/aderlo.pl/public_html/wp-admin/includes/class-wp-posts-list-table.php(834): WP_Posts_List_Table-&gt;single_row()
#6 /home/aderlopl/domains/aderlo.pl/public_html/wp-admin/includes/class-wp-posts-list-table.php(810): WP_Posts_List_Table-&gt;_display_rows()
#7 /home/aderlopl/domains/aderlo.pl/public_html/wp-admin/includes/class-wp-list-table.php(1712): WP_Posts_List_Table-&gt;display_rows()
#8 /home/aderlopl/domains/aderlo.pl/public_html/wp-admin/includes/class-wp-list-table.php(1639): WP_List_Table-&gt;display_rows_or_placeholder()
#9 /home/aderlopl/domains/aderlo.pl/public_html/wp-admin/edit.php(503): WP_List_Table-&gt;display()
#10 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-09-23 15:18:41 [warning X 8355][/home/aderlopl/domains/aderlo.pl/public_html/wp-content/plugins/elementor-pro/modules/posts/skins/skin-content-base.php::271] Attempt to read property &quot;ID&quot; on null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-09-28 14:14:30 [warning X 2][/home/aderlopl/domains/aderlo.pl/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::182] Undefined array key &quot;editor_post_id&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-09-30 10:43:45 [warning X 2][/home/aderlopl/domains/aderlo.pl/public_html/wp-content/plugins/elementor-pro/modules/dynamic-tags/tags/post-featured-image.php::39] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 20 of 21JS: 2024-09-20 06:06:39 [error X 1][https://aderlo.pl/wp-content/plugins/elementor-pro/assets/lib/sticky/jquery.sticky.min.js?ver=3.24.2:1:1162] Failed to execute &#039;getComputedStyle&#039; on &#039;Window&#039;: parameter 1 is not of type &#039;Element&#039;. 
JS: 2024-09-21 17:43:17 [error X 2][https://aderlo.pl/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.24.2:3:66001] Cannot convert undefined or null to object 
JS: 2024-09-25 07:59:29 [error X 1][https://aderlo.pl/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.24.4:3:664925] Cannot read properties of undefined (reading &#039;isDesignable&#039;) 
JS: 2024-09-25 14:10:30 [error X 12][https://aderlo.pl/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.24.4:2:10877] Cannot read properties of undefined (reading &#039;autoplay&#039;) 
JS: 2024-09-25 14:42:32 [error X 1][https://aderlo.pl/wp-admin/load-scripts.php?c=1&amp;loadchunk_0=wp-hooks,jquery-core,jquery-migrate,utils,moxiejs,plupload,wp-polyfill&amp;ver=6.6.2:4:28760] elementorCommon is not defined 
JS: 2024-09-25 14:43:14 [error X 3][https://aderlo.pl/wp-content/plugins/elementor/assets/js/ai-media-library.min.js?ver=3.24.4:3:327982] Cannot read properties of undefined (reading &#039;MessageIcon&#039;) 
JS: 2024-09-25 14:44:00 [error X 1][https://aderlo.pl/wp-content/plugins/elementor/assets/js/ai-media-library.min.js?ver=3.24.4:3:491117] elementorV2 is not defined 
JS: 2024-09-25 14:46:47 [error X 1][https://aderlo.pl/wp-includes/js/jquery/jquery.min.js?ver=3.7.1:2:28760] Cannot read properties of undefined (reading &#039;tools&#039;) 
JS: 2024-09-25 16:37:41 [error X 1][https://aderlo.pl/wp-content/plugins/elementor/assets/js/packages/icons/icons.min.js?ver=3.24.4:1:3243] Cannot read properties of undefined (reading &#039;ui&#039;) 
JS: 2024-09-25 16:37:41 [error X 2][https://aderlo.pl/wp-content/plugins/elementor/assets/js/responsive-bar.min.js?ver=3.24.4:2:11756] elementor is not defined 
JS: 2024-09-25 16:37:41 [error X 1][https://aderlo.pl/wp-content/plugins/elementor/assets/js/editor-loader-v1.min.js?ver=3.24.4:2:37] Cannot read properties of undefined (reading &#039;start&#039;) 
JS: 2024-09-25 16:37:42 [error X 1][https://aderlo.pl/wp-content/plugins/elementor/assets/js/editor-notifications.min.js?ver=3.24.4:3:17565] Cannot read properties of undefined (reading &#039;SpeakerphoneIcon&#039;) 
JS: 2024-09-25 16:37:42 [error X 1][https://aderlo.pl/wp-content/plugins/elementor/assets/js/styleguide.min.js?ver=3.24.4:2:46297] Cannot read properties of undefined (reading &#039;addAction&#039;) 
JS: 2024-09-28 11:21:34 [error X 10][https://aderlo.pl/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.24.4:3:837409] Cannot read properties of undefined (reading &#039;localized&#039;) 
JS: 2024-09-29 12:22:38 [error X 1][https://aderlo.pl/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.24.4:3:836902] Cannot read properties of undefined (reading &#039;toLowerCase&#039;) 
JS: 2024-09-29 13:11:23 [error X 1][https://aderlo.pl/wp-content/plugins/elementor/assets/js/common-modules.min.js?ver=3.24.4:2:56144] Model.isValidChild() should be implemented, please provide &#039;isValidChild&#039; functionality. 
JS: 2024-09-29 17:48:17 [error X 1][https://aderlo.pl/wp-content/plugins/elementor/assets/js/web-cli.min.js?ver=3.24.4:3:82935] Data commands: `` not found. 
JS: 2024-09-30 07:45:10 [error X 1][https://aderlo.pl/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view66014&quot;) has already been destroyed and cannot be used. 
JS: 2024-09-30 07:45:53 [error X 1][https://aderlo.pl/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view66142&quot;) has already been destroyed and cannot be used. 
JS: 2024-09-30 07:45:53 [error X 1][https://aderlo.pl/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view71398&quot;) has already been destroyed and cannot be used. 



== Elementor - Compatibility Tag ==
	Elementor Pro: Kompatybilność nieokreślona
	ShopLentor Pro – WooCommerce Builder for Elementor & Gutenberg: Kompatybilność nieokreślona
	ShopLentor – WooCommerce Builder for Elementor & Gutenberg: Kompatybilność nieokreślona

== Elementor Pro - Compatibility Tag ==
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by DanielCyran** [comment]
also popup templates do not work correctly .... // the video shows the problem of how it closes after refreshing the page when first opening. 

https://github.com/user-attachments/assets/959224e9-bcb0-4488-ab9c-db4a5071272d

**Comment by ivstar2001** [comment]
You can add the HTML widget in your footer template where Off-Canvas triggers are nested and control Off-Canvas visibility on click event. For example, clicking on the Kategorie link will hide Filtry and vice versa... code example below:

<script>
jQuery("a#kategorie").click(function(){
     jQuery("#off-canvas-ab53fc0").attr("aria-hidden","true");
});
jQuery("a#filtry").click(function(){
     jQuery("#off-canvas-0b7de73").attr("aria-hidden","true");
});
</script>

**Comment by DanielCyran** [comment]
Thank you

**Comment by DanielCyran** [comment]
a temporary solution on offcanvas helped.

however, the problem with pop-ups persists and needs to be fixed

**Comment by TomRaraAvis** [comment]
+1
#8125 — Trigger to close popup
#27727 — Add an option to close the Off-Canvas widget when a link inside is clicked
#8125 — Trigger to close popup
#7085 — Popup - Close when you click on a button
