### ISSUE TITLE
Adding floating point/decimal in linked inputs with any unit

### ISSUE THREAD

**Issue by clevermissfox** [elementor/elementor#29140]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

In any instance of group of four inputs (top right bottom left) in the Elementor editor (eg padding, margin, border radius, border width etc) , when all four values are linked 🔗 and any unit is selected (originally noticed with EM but further testing showed I had the same issue with REM, PX, VW, %),  trying to use a decimal like “0.25” does not work as it should. If the values are unlinked and you’re just typing in value for one input (eg for ‘top’ or ‘right’) a decimal works as expected. 

I reported this many versions ago to support and was told it would be added to the backlog but it’s been long over a year with no changes. The behaviour is the same across Mac and windows devices and I have tested on chrome and Firefox which have two different issues. Not tested safari, opera or edge. 

when trying enter a value of “0.25”: 
In chrome:
type “0.”, the output is “0” and the cursor jumps to the left of the 0 ; if you try the decimal once it’s jumped to the left , you have to hit it twice to get the output of “.0”; at that point I can type “25” and the output is “.250” so have to move cursor to the end to delete the trailing “0” so output is “.25” , then jump to the start to add the “0” so the output is “0.25”. Using a value or starting digit other than 0 (like “2.125”) results in the same behaviour. 

In Firefox:
Enter cursor into input , type any digit eg “0” then type a decimal “.” The output is “0” no matter how many times you press the decimal. You have to manually move your cursor to the left of the 0 then you can type a decimal “.0” . It doesn’t jump to the start/left of the 0 like chrome does. 

When the values are NOT linked (and any unit is selected), behaviour is as expected; able to add a decimal wherever it is needed without any jumping or moving of cursor or pressing decimal key twice. 

### Steps to reproduce

1. Have elementor and Elementor pro installed 
2. Open the editor on any page , select any container or widget and navigate in the sidebar to any input with a group of four inputs for top bottom left and right
3. Ensure all the values are linked together 🔗 
4. Set unit to EM (or any unit really; the behaviour is the same with REM, PX, VW, and % as long as values are linked) 
5. Try typing any value with a decimal “0.25”, “2.25” “3.95” etc

### Expected behavior

1. Select linked values 
2. Select any unit
3. Type any number with a decimal without having to manually move the cursor, without the cursor jumping , without having to hit the decimal key more than once to output one decimal , without having to then add or delete extra digits 

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.6.17
	PHP Version: 8.1.27
	PHP Memory Limit: 1G
	PHP Max Input Vars: 1000
	PHP Max Post Size: 1G
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.6.2
	Site URL: https://cochiseharmreduction.org
	Home URL: https://cochiseharmreduction.org
	WP Multisite: No
	Max Upload Size: 1 GB
	Memory limit: 512M
	Max Memory limit: 1G
	Permalink Structure: /%postname%/
	Language: en_US
	Timezone: 0
	Admin Email: info@cochiseharmreduction.org
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.0
	Author: Stacey
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 3.1.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 17_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/130.0.6723.37 Mobile/15E148 Safari/604.1

== Active Plugins ==
	Activity Log
		Version: 2.11.0
		Author: Activity Log Team

	Advanced Custom Fields
		Version: 6.3.9
		Author: WP Engine

	Akismet Anti-spam: Spam Protection
		Version: 5.3.3
		Author: Automattic - Anti-spam Team

	All-in-One WP Migration
		Version: 7.87
		Author: ServMask

	Code Snippets
		Version: 3.6.5.1
		Author: Code Snippets Pro

	Elementor
		Version: 3.24.7
		Author: Elementor.com

	Elementor Pro
		Version: 3.24.2
		Author: Elementor.com

	Give - Donation Plugin
		Version: 3.17.1
		Author: GiveWP

	Google Analytics for WordPress by MonsterInsights
		Version: 9.2.0
		Author: MonsterInsights

	LiteSpeed Cache
		Version: 6.5.2
		Author: LiteSpeed Technologies

	Maspik - Advanced Spam Protection
		Version: 2.2.7
		Author: WpMaspik

	UpdraftPlus - Backup/Restore
		Version: 1.24.6
		Author: TeamUpdraft, DavidAnderson

	WP Mail SMTP
		Version: 4.1.1
		Author: WP Mail SMTP

	Yoast SEO
		Version: 23.7
		Author: Team Yoast


== Features ==
	Custom Fonts: 3
	Custom Icons: 0

== Integrations ==
	
	recaptcha_v3: Active


== Elementor Experiments ==
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Active
	Additional Custom Breakpoints: Active by default
	Flexbox Container: Active
	Grid Container: Active
	Upgrade Swiper Library: Active by default
	Nested Elements Performance: Active by default
	Optimized Control Loading: Inactive by default
	Optimized Markup: Inactive by default
	Conditionally load Swiper CSS files: Inactive by default
	Plugin Onboarding: Active by default
	Default to New Theme Builder: Active by default
	Header & Footer: Active by default
	Elementor Home Screen: Inactive
	Build with AI: Active by default
	Landing Pages: Active by default
	Launchpad Checklist: Inactive by default
	Nested Elements: Active
	Editor Top Bar: Active
	Pages Panel: Inactive by default
	Element Caching: Inactive by default
	Link In Bio: Active by default
	Floating Buttons: Active by default
	Elementor Editor Events: Inactive by default
	Atomic Widgets: Inactive by default
	Display Conditions: Active by default
	Form Submissions: Active by default
	Menu: Inactive by default


== Log ==
	
JS: showing 18 of 18JS: 2024-09-14 06:09:47 [error X 2][https://cochiseharmreduction.org/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view101") has already been destroyed and cannot be used. 
JS: 2024-09-14 09:17:28 [error X 1][https://cochiseharmreduction.org/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view4827") has already been destroyed and cannot be used. 
JS: 2024-09-15 04:44:36 [error X 1][https://cochiseharmreduction.org/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view3826") has already been destroyed and cannot be used. 
JS: 2024-09-15 04:52:50 [error X 1][https://cochiseharmreduction.org/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view858") has already been destroyed and cannot be used. 
JS: 2024-09-15 04:55:31 [error X 1][https://cochiseharmreduction.org/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view1556") has already been destroyed and cannot be used. 
JS: 2024-09-16 04:44:17 [error X 1][https://cochiseharmreduction.org/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view3500") has already been destroyed and cannot be used. 
JS: 2024-09-16 05:21:29 [error X 3][https://cochiseharmreduction.org/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.23.1:3:54583] Cannot read properties of undefined (reading 'activate') 
JS: 2024-09-17 07:58:13 [error X 3][https://cochiseharmreduction.org/wp-admin/load-scripts.php?c=1&loadchunk_0=jquery-ui-draggable,react,react-dom&ver=6.6.2:13:112013] Cannot read properties of undefined (reading 'toString') 
JS: 2024-09-18 04:58:57 [error X 73][https://cochiseharmreduction.org/wp-admin/load-scripts.php?c=1&loadchunk_0=jquery-core,jquery-migrate,utils,wp-hooks&ver=6.6.2:2:28760] Cannot read properties of undefined (reading 'value') 
JS: 2024-09-19 08:01:31 [error X 2][https://cochiseharmreduction.org/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view305") has already been destroyed and cannot be used. 
JS: 2024-09-20 02:25:29 [error X 1][https://cochiseharmreduction.org/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view1670") has already been destroyed and cannot be used. 
JS: 2024-09-20 02:40:31 [error X 1][https://cochiseharmreduction.org/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view205") has already been destroyed and cannot be used. 
JS: 2024-09-20 02:40:31 [error X 1][https://cochiseharmreduction.org/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view216") has already been destroyed and cannot be used. 
JS: 2024-09-20 02:41:02 [error X 1][https://cochiseharmreduction.org/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view1489") has already been destroyed and cannot be used. 
JS: 2024-09-20 02:41:02 [error X 1][https://cochiseharmreduction.org/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view1500") has already been destroyed and cannot be used. 
JS: 2024-09-29 03:53:33 [error X 1][https://cochiseharmreduction.org/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.24.3:2:17146] Cannot read properties of undefined (reading 'attributes') 
JS: 2024-10-01 03:31:13 [error X 1][https://cochiseharmreduction.org/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.24.3:3:714406] this.model.isValidChild is not a function 
JS: 2024-10-01 05:18:09 [error X 2][https://cochiseharmreduction.org/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.24.3:3:954984] elementorFrontend is not defined 

PHP: showing 10 of 10PHP: 2024-09-16 10:28:08 [warning X 34][/home/cochiseh/public_html/wp-content/plugins/elementor/modules/history/revisions-manager.php::363] Undefined array key "editor_post_id" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-09-18 05:01:19 [warning X 1051][/home/cochiseh/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key "condition_type" [array (
  'trace' => '
#0: /home/cochiseh/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /home/cochiseh/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /home/cochiseh/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /home/cochiseh/public_html/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2024-09-19 05:13:43 [error X 30][/home/cochiseh/public_html/wp-content/plugins/elementor-pro/modules/display-conditions/classes/comparators-checker.php::76] Uncaught TypeError: ElementorPro\Modules\DisplayConditions\Classes\Comparators_Checker::check_string_contains_and_empty(): Argument #3 ($actual_value) must be of type string, array given, called in /home/cochiseh/public_html/wp-content/plugins/elementor-pro/modules/display-conditions/conditions/dynamic-tags-condition.php on line 54 and defined in /home/cochiseh/public_html/wp-content/plugins/elementor-pro/modules/display-conditions/classes/comparators-checker.php:76
Stack trace:
#0 /home/cochiseh/public_html/wp-content/plugins/elementor-pro/modules/display-conditions/conditions/dynamic-tags-condition.php(54): ElementorPro\Modules\DisplayConditions\Classes\Comparators_Checker::check_string_contains_and_empty()
#1 /home/cochiseh/public_html/wp-content/plugins/elementor-pro/modules/display-conditions/classes/and-condition.php(38): ElementorPro\Modules\DisplayConditions\Conditions\Dynamic_Tags_Condition->check()
#2 /home/cochiseh/public_html/wp-content/plugins/elementor-pro/modules/display-conditions/classes/and-condition.php(24): ElementorPro\Modules\DisplayConditions\Classes\And_Condition->is_condition_passing_check()
#3 /home/cochiseh/public_html/wp-content/plugins/elementor-pro/modules/display-conditions/classes/or-condition.php(27): ElementorPro\Modules\DisplayConditions\Classes\And_Condition->check()
#4 /home/cochiseh/public_html/wp-content/plugins/elementor-pro/modules/display-conditions/module.php(189): ElementorPro\Modules\DisplayConditions\Classes\Or_Condition->check()
#5 /home/cochiseh/public_html/wp-includes/class-wp-hook.php(324): ElementorPro\Modules\DisplayConditions\Module->before_element_render()
#6 /home/cochiseh/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#7 /home/cochiseh/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#8 /home/cochiseh/public_html/wp-content/plugins/elementor/includes/base/element-base.php(474): do_action()
#9 /home/cochiseh/public_html/wp-content/plugins/elementor/includes/base/element-base.php(1422): Elementor\Element_Base->print_element()
#10 /home/cochiseh/public_html/wp-content/plugins/elementor/includes/base/element-base.php(483): Elementor\Element_Base->print_content()
#11 /home/cochiseh/public_html/wp-content/plugins/elementor/includes/base/element-base.php(1422): Elementor\Element_Base->print_element()
#12 /home/cochiseh/public_html/wp-content/plugins/elementor/includes/base/element-base.php(483): Elementor\Element_Base->print_content()
#13 /home/cochiseh/public_html/wp-content/plugins/elementor/core/base/document.php(1875): Elementor\Element_Base->print_element()
#14 /home/cochiseh/public_html/wp-content/plugins/elementor/core/base/document.php(1800): Elementor\Core\Base\Document->do_print_elements()
#15 /home/cochiseh/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(412): Elementor\Core\Base\Document->print_elements()
#16 /home/cochiseh/public_html/wp-content/plugins/elementor/includes/frontend.php(1158): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document->print_elements_with_wrapper()
#17 /home/cochiseh/public_html/wp-content/plugins/elementor/core/base/document.php(1249): Elementor\Frontend->get_builder_content()
#18 /home/cochiseh/public_html/wp-content/plugins/elementor/modules/library/documents/library-document.php(76): Elementor\Core\Base\Document->get_content()
#19 /home/cochiseh/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(158): Elementor\Modules\Library\Documents\Library_Document->get_content()
#20 /home/cochiseh/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(173): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document->get_content()
#21 /home/cochiseh/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/documents/single-base.php(93): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document->print_content()
#22 /home/cochiseh/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/locations-manager.php(364): ElementorPro\Modules\ThemeBuilder\Documents\Single_Base->print_content()
#23 /home/cochiseh/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/api.php(13): ElementorPro\Modules\ThemeBuilder\Classes\Locations_Manager->do_location()
#24 /home/cochiseh/public_html/wp-content/themes/hello-elementor/index.php(20): elementor_theme_do_location()
#25 /home/cochiseh/public_html/wp-includes/template-loader.php(106): include('/home/cochiseh/...')
#26 /home/cochiseh/public_html/wp-blog-header.php(19): require_once('/home/cochiseh/...')
#27 /home/cochiseh/public_html/index.php(17): require('/home/cochiseh/...')
#28 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-09-20 02:33:49 [error X 3][/home/cochiseh/public_html/wp-content/plugins/elementor-pro/modules/display-conditions/classes/comparators-checker.php::76] Uncaught TypeError: ElementorPro\Modules\DisplayConditions\Classes\Comparators_Checker::check_string_contains_and_empty(): Argument #3 ($actual_value) must be of type string, array given, called in /home/cochiseh/public_html/wp-content/plugins/elementor-pro/modules/display-conditions/conditions/dynamic-tags-condition.php on line 54 and defined in /home/cochiseh/public_html/wp-content/plugins/elementor-pro/modules/display-conditions/classes/comparators-checker.php:76
Stack trace:
#0 /home/cochiseh/public_html/wp-content/plugins/elementor-pro/modules/display-conditions/conditions/dynamic-tags-condition.php(54): ElementorPro\Modules\DisplayConditions\Classes\Comparators_Checker::check_string_contains_and_empty()
#1 /home/cochiseh/public_html/wp-content/plugins/elementor-pro/modules/display-conditions/classes/and-condition.php(38): ElementorPro\Modules\DisplayConditions\Conditions\Dynamic_Tags_Condition->check()
#2 /home/cochiseh/public_html/wp-content/plugins/elementor-pro/modules/display-conditions/classes/and-condition.php(24): ElementorPro\Modules\DisplayConditions\Classes\And_Condition->is_condition_passing_check()
#3 /home/cochiseh/public_html/wp-content/plugins/elementor-pro/modules/display-conditions/classes/or-condition.php(27): ElementorPro\Modules\DisplayConditions\Classes\And_Condition->check()
#4 /home/cochiseh/public_html/wp-content/plugins/elementor-pro/modules/display-conditions/module.php(189): ElementorPro\Modules\DisplayConditions\Classes\Or_Condition->check()
#5 /home/cochiseh/public_html/wp-includes/class-wp-hook.php(324): ElementorPro\Modules\DisplayConditions\Module->before_element_render()
#6 /home/cochiseh/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#7 /home/cochiseh/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#8 /home/cochiseh/public_html/wp-content/plugins/elementor/includes/base/element-base.php(474): do_action()
#9 /home/cochiseh/public_html/wp-content/plugins/elementor/includes/base/element-base.php(1422): Elementor\Element_Base->print_element()
#10 /home/cochiseh/public_html/wp-content/plugins/elementor/includes/base/element-base.php(483): Elementor\Element_Base->print_content()
#11 /home/cochiseh/public_html/wp-content/plugins/elementor/includes/base/element-base.php(1422): Elementor\Element_Base->print_element()
#12 /home/cochiseh/public_html/wp-content/plugins/elementor/includes/base/element-base.php(483): Elementor\Element_Base->print_content()
#13 /home/cochiseh/public_html/wp-content/plugins/elementor/includes/base/element-base.php(1422): Elementor\Element_Base->print_element()
#14 /home/cochiseh/public_html/wp-content/plugins/elementor/includes/base/element-base.php(483): Elementor\Element_Base->print_content()
#15 /home/cochiseh/public_html/wp-content/plugins/elementor/includes/base/element-base.php(1422): Elementor\Element_Base->print_element()
#16 /home/cochiseh/public_html/wp-content/plugins/elementor/includes/base/element-base.php(483): Elementor\Element_Base->print_content()
#17 /home/cochiseh/public_html/wp-content/plugins/elementor/core/base/document.php(1875): Elementor\Element_Base->print_element()
#18 /home/cochiseh/public_html/wp-content/plugins/elementor/core/base/document.php(1800): Elementor\Core\Base\Document->do_print_elements()
#19 /home/cochiseh/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(412): Elementor\Core\Base\Document->print_elements()
#20 /home/cochiseh/public_html/wp-content/plugins/elementor/includes/frontend.php(1158): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document->print_elements_with_wrapper()
#21 /home/cochiseh/public_html/wp-content/plugins/elementor/core/base/document.php(1249): Elementor\Frontend->get_builder_content()
#22 /home/cochiseh/public_html/wp-content/plugins/elementor/modules/library/documents/library-document.php(76): Elementor\Core\Base\Document->get_content()
#23 /home/cochiseh/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(158): Elementor\Modules\Library\Documents\Library_Document->get_content()
#24 /home/cochiseh/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(173): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document->get_content()
#25 /home/cochiseh/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/documents/single-base.php(93): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document->print_content()
#26 /home/cochiseh/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/locations-manager.php(364): ElementorPro\Modules\ThemeBuilder\Documents\Single_Base->print_content()
#27 /home/cochiseh/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/api.php(13): ElementorPro\Modules\ThemeBuilder\Classes\Locations_Manager->do_location()
#28 /home/cochiseh/public_html/wp-content/themes/hello-elementor/index.php(20): elementor_theme_do_location()
#29 /home/cochiseh/public_html/wp-includes/template-loader.php(106): include('/home/cochiseh/...')
#30 /home/cochiseh/public_html/wp-blog-header.php(19): require_once('/home/cochiseh/...')
#31 /home/cochiseh/public_html/index.php(17): require('/home/cochiseh/...')
#32 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-09-21 02:49:44 [error X 1][/home/cochiseh/public_html/wp-content/plugins/elementor-pro/modules/forms/submissions/component.php::169] Uncaught Error: Class "ElementorPro\Modules\Forms\Submissions\Database\Migration" not found in /home/cochiseh/public_html/wp-content/plugins/elementor-pro/modules/forms/submissions/component.php:169
Stack trace:
#0 /home/cochiseh/public_html/wp-includes/class-wp-hook.php(324): ElementorPro\Modules\Forms\Submissions\Component->ElementorPro\Modules\Forms\Submissions\{closure}()
#1 /home/cochiseh/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#2 /home/cochiseh/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#3 /home/cochiseh/public_html/wp-admin/admin-ajax.php(45): do_action()
#4 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-09-23 04:40:33 [error X 4][/home/cochiseh/public_html/wp-content/plugins/elementor-pro/modules/display-conditions/classes/comparators-checker.php::76] Uncaught TypeError: ElementorPro\Modules\DisplayConditions\Classes\Comparators_Checker::check_string_contains_and_empty(): Argument #3 ($actual_value) must be of type string, array given, called in /home/cochiseh/public_html/wp-content/plugins/elementor-pro/modules/display-conditions/conditions/dynamic-tags-condition.php on line 54 and defined in /home/cochiseh/public_html/wp-content/plugins/elementor-pro/modules/display-conditions/classes/comparators-checker.php:76
Stack trace:
#0 /home/cochiseh/public_html/wp-content/plugins/elementor-pro/modules/display-conditions/conditions/dynamic-tags-condition.php(54): ElementorPro\Modules\DisplayConditions\Classes\Comparators_Checker::check_string_contains_and_empty()
#1 /home/cochiseh/public_html/wp-content/plugins/elementor-pro/modules/display-conditions/classes/and-condition.php(38): ElementorPro\Modules\DisplayConditions\Conditions\Dynamic_Tags_Condition->check()
#2 /home/cochiseh/public_html/wp-content/plugins/elementor-pro/modules/display-conditions/classes/and-condition.php(24): ElementorPro\Modules\DisplayConditions\Classes\And_Condition->is_condition_passing_check()
#3 /home/cochiseh/public_html/wp-content/plugins/elementor-pro/modules/display-conditions/classes/or-condition.php(27): ElementorPro\Modules\DisplayConditions\Classes\And_Condition->check()
#4 /home/cochiseh/public_html/wp-content/plugins/elementor-pro/modules/display-conditions/module.php(189): ElementorPro\Modules\DisplayConditions\Classes\Or_Condition->check()
#5 /home/cochiseh/public_html/wp-includes/class-wp-hook.php(324): ElementorPro\Modules\DisplayConditions\Module->before_element_render()
#6 /home/cochiseh/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#7 /home/cochiseh/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#8 /home/cochiseh/public_html/wp-content/plugins/elementor/includes/base/element-base.php(474): do_action()
#9 /home/cochiseh/public_html/wp-content/plugins/elementor/includes/base/element-base.php(1442): Elementor\Element_Base->print_element()
#10 /home/cochiseh/public_html/wp-content/plugins/elementor/includes/base/element-base.php(483): Elementor\Element_Base->print_content()
#11 /home/cochiseh/public_html/wp-content/plugins/elementor/includes/base/element-base.php(1442): Elementor\Element_Base->print_element()
#12 /home/cochiseh/public_html/wp-content/plugins/elementor/includes/base/element-base.php(483): Elementor\Element_Base->print_content()
#13 /home/cochiseh/public_html/wp-content/plugins/elementor/core/base/document.php(1875): Elementor\Element_Base->print_element()
#14 /home/cochiseh/public_html/wp-content/plugins/elementor/core/base/document.php(1800): Elementor\Core\Base\Document->do_print_elements()
#15 /home/cochiseh/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(412): Elementor\Core\Base\Document->print_elements()
#16 /home/cochiseh/public_html/wp-content/plugins/elementor/includes/frontend.php(1200): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document->print_elements_with_wrapper()
#17 /home/cochiseh/public_html/wp-content/plugins/elementor/core/base/document.php(1249): Elementor\Frontend->get_builder_content()
#18 /home/cochiseh/public_html/wp-content/plugins/elementor/modules/library/documents/library-document.php(76): Elementor\Core\Base\Document->get_content()
#19 /home/cochiseh/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(158): Elementor\Modules\Library\Documents\Library_Document->get_content()
#20 /home/cochiseh/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(173): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document->get_content()
#21 /home/cochiseh/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/documents/single-base.php(93): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document->print_content()
#22 /home/cochiseh/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/locations-manager.php(364): ElementorPro\Modules\ThemeBuilder\Documents\Single_Base->print_content()
#23 /home/cochiseh/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/api.php(13): ElementorPro\Modules\ThemeBuilder\Classes\Locations_Manager->do_location()
#24 /home/cochiseh/public_html/wp-content/themes/hello-elementor/index.php(20): elementor_theme_do_location()
#25 /home/cochiseh/public_html/wp-includes/template-loader.php(106): include('/home/cochiseh/...')
#26 /home/cochiseh/public_html/wp-blog-header.php(19): require_once('/home/cochiseh/...')
#27 /home/cochiseh/public_html/index.php(17): require('/home/cochiseh/...')
#28 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-09-28 06:02:52 [warning X 5][/home/cochiseh/public_html/wp-content/plugins/elementor/includes/managers/image.php::113] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-09-29 03:48:17 [warning X 72][/home/cochiseh/public_html/wp-content/plugins/elementor/includes/widgets/video.php::1344] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-10-01 04:24:27 [warning X 1][/home/cochiseh/public_html/wp-content/plugins/elementor-pro/modules/forms/classes/ajax-handler.php::76] Undefined array key "form_id" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-10-05 03:00:12 [warning X 2][/home/cochiseh/public_html/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-color.php::34] Undefined array key 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 14 of 142024-09-21 02:49:46 [info] elementor-pro::elementor_pro_updater Started 
2024-09-21 02:49:46 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-09-21 02:49:46 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-09-21 02:49:46 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.0',
  'to' => '3.24.2',
)]
2024-09-21 02:49:46 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.0',
  'to' => '3.24.2',
)]
2024-09-29 03:46:07 [info] elementor::elementor_updater Started 
2024-09-29 03:46:07 [info] Elementor/Upgrades - _on_each_version Start  
2024-09-29 03:46:07 [info] Elementor/Upgrades - _on_each_version Finished 
2024-09-29 03:46:07 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.1',
  'to' => '3.24.3',
)]
2024-10-18 03:26:50 [info] elementor::elementor_updater Started 
2024-10-18 03:26:50 [info] Elementor/Upgrades - _on_each_version Start  
2024-10-18 03:26:50 [info] Elementor/Upgrades - _on_each_version Finished 
2024-10-18 03:26:50 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.24.3',
  'to' => '3.24.7',
)]
2024-10-18 03:26:50 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.24.3',
  'to' => '3.24.7',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by jdpoccorie** [comment]
Perhaps this solution will help you figure out the problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by nicholaszein** [comment]
Hello @clevermissfox! 

Thank you for submitting your issue! 🙏 

🏷️ We've labeled this issue and our team will take a look at it. If there is indeed a problem, they'll work on fixing it. We can't say exactly when it'll be sorted out, but we kindly ask for your patience. Thanks for understanding!

Best regards

**Comment by clevermissfox** [comment]
Even if they hadn't noticed it while testing, I reported it over a year ago
and was assured it was added to the list. It doesn't work on Mac or windows
on chrome nor Firefox. Since it works on unlinked values I'd love a look at
the code to see what the problem is when linked. But do not want to try to
find that code in the plugin either. It's very frustrating. It takes an
extra 3 steps so may as well add it unlinked if it takes the same amount of
keystrokes

**Comment by presstwooddesign** [comment]
Huge support for this... it's very frustrating not being able to use decimals for relative units.

**Comment by TalhaErenY** [comment]
This bug still exists as of Version 3.33.1, and this github issue is the first result on Google. I can confirm copy pasting the decimal number while in linked mode works, so this is one way of bypassing the bug.
