### ISSUE TITLE
Elementor Pro 3.25.1 Custom add to cart widget fails if the Toggle "Show quantity" is enabled

### ISSUE THREAD

**Issue by theitpyme** [elementor/elementor#29159]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

I think You have a bug in 3.25.1 pro version, regarding the Custom add to cart Widget, when you enable "Show Quantity" toggle, the issue is there. If you don't enable in each widget the show quantity toggle, no issue is present and everything works fine. Maybe this advice can give you a track to address the issue.
See the attached picture to see the effect (Sorry because the website is in spanish):
When you enabled into editor mode the toggle, the button are shaded and it doesn't work properly.
Steps to reproduce the issue:
1 - Create a page with Elementor without any Cache plugin activated, purge all caches and re-generate CSS.
2 - Add to this page a custom add to cart widget with the show quantity toggle enabled.
3 - If you have previously enabled this toggle and then update to 3.25.1 pro version, the website show "Critical Error" and styles of the page that contains those custom add to cart widgets, will be misconfigured.
Please, I recommend you and your developers team to investigate the issue because this issue is happening in at least 3 different sites where I am the admin.
If you don't enable the toggle, everything works fine, if you have previously custom add to cart widgets enabled in your website, when you update your site to 3.25.1. pro version, the pages where you have enabled those widgets with the toggle enabled, will be broken (Critical Error).

See attached pic to see the effect if you enable the toggle in the edit panel with 3.25.1 pro version:

![issue](https://github.com/user-attachments/assets/373e999a-828b-416f-a7c9-241e19ca888e)

### Steps to reproduce

1 - Create a page with Elementor without any Cache plugin activated, purge all caches and re-generate CSS.
2 - Add to this page a custom add to cart widget with the show quantity toggle enabled.
3 - If you have previously enabled this toggle in your widgets before upgrade and then update to 3.25.1 pro version, the website show "Critical Error" and styles of the page that contains those custom add to cart widgets, will be misconfigured.

### Expected behavior

Expected behavior is that if you add the custom add to cart widget everything must works fine enabling or not the show quantity toggle.

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MySQL Community Server - GPL v8.0.39
	PHP Version: 8.1.30
	PHP Memory Limit: 2048M
	PHP Max Input Vars: 40000
	PHP Max Post Size: 1000M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.6.2
	Site URL: https://www.sportcoa.com
	Home URL: https://www.sportcoa.com
	WP Multisite: No
	Max Upload Size: 1.000 MB
	Memory limit: 2048M
	Max Memory limit: 2048M
	Permalink Structure: /%category%/%postname%/
	Language: es_ES
	Timezone: Europe/Madrid
	Admin Email: info@sportcoa.com
	Debug Mode: Inactive

== Theme ==
	Name: GeneratePress
	Version: 3.5.1
	Author: Tom Usborne
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: es
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36

== Active Plugins ==
	Ajax Search Pro
		Version: 4.26.16
		Author: Ernest Marcinko

	Code Snippets
		Version: 3.6.5.1
		Author: Code Snippets Pro

	Colorlib Login Customizer
		Version: 1.3.2
		Author: Colorlib

	Elementor
		Version: 3.25.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.25.1
		Author: Elementor.com

	Facebook for WooCommerce
		Version: 3.2.10
		Author: Facebook

	GA Google Analytics
		Version: 20241019
		Author: Jeff Starr

	GDPR Cookie Compliance
		Version: 4.15.5
		Author: Moove Agency

	GP Premium
		Version: 2.5.0
		Author: Tom Usborne

	GTranslate
		Version: 3.0.7
		Author: Translate AI Multilingual Solutions

	Health Check & Troubleshooting
		Version: 1.7.1
		Author: The WordPress.org community

	Heartbeat Control by WP Rocket
		Version: 2.0.1
		Author: WP Rocket

	JetEngine
		Version: 3.5.7
		Author: Crocoblock

	JetFormBuilder
		Version: 3.4.2
		Author: Crocoblock

	JetPopup
		Version: 2.0.7
		Author: Crocoblock

	JetSmartFilters
		Version: 3.5.7.1
		Author: Crocoblock

	PDF Invoices & Packing Slips for WooCommerce
		Version: 3.9.0
		Author: WP Overnight

	PDF Invoices & Packing Slips for WooCommerce - Premium Templates
		Version: 2.21.0
		Author: WP Overnight

	Simple History
		Version: 5.0.4
		Author: Pär Thernström

	Store Credit for WooCommerce
		Version: 4.5.4
		Author: Kestrel

	WooCommerce
		Version: 9.3.3
		Author: Automattic

	WooCommerce Checkout Field Editor
		Version: 1.7.18
		Author: WooCommerce

	WooCommerce Email Customizer with Drag and Drop Email Builder
		Version: 1.5.16
		Author: Flycart Technologies LLP

	WooCommerce PayPal Payments
		Version: 2.9.3
		Author: WooCommerce

	WooCommerce Stripe Gateway
		Version: 8.8.1
		Author: Stripe

	WooCommerce Upload Files
		Version: 70.8
		Author: Lagudi Domenico

	WP Mail SMTP Pro
		Version: 3.5.2
		Author: WPForms

	Yoast SEO
		Version: 23.7
		Author: Team Yoast

	Yoast SEO Premium
		Version: 23.0
		Author: Team Yoast

	Yoast Test Helper
		Version: 1.18
		Author: Team Yoast


== Must-Use Plugins ==
	Health Check Troubleshooting Mode
		Version: 1.9.1
		Author: 


== Caracteristicas ==
	Custom Fonts: 0
	Custom Icons: 0

== Integraciones ==
	
	recaptcha_v3: Activo
	woocommerce: Activo


== Experimentos de Elementor ==
	Carga de CSS mejorada: Inactivo por defecto
	Fuentes de iconos integradas: Activo
	Puntos de ruptura personalizados adicionales: Inactivo
	Contenedor: Inactivo por defecto
	Actualizar la librería Swiper: Activo por defecto
	Rendimiento de los elementos anidados: Activo por defecto
	Carga de controles optimizada: Activo por defecto
	Marcado optimizado: Inactivo por defecto
	Carga condicional de archivos CSS Swiper: Inactivo por defecto
	Puesta en marcha del plugin: Activo por defecto
	Scroll suave por CSS: Activo por defecto
	Por defecto, el nuevo constructor de temas: Activo por defecto
	Pantalla de inicio de Elementor: Activo por defecto
	Páginas de destino: Activo por defecto
	Elementos anidados: Activo por defecto
	Barra superior del editor: Activo por defecto
	Panel de páginas: Inactivo por defecto
	Caché de elementos: Inactivo por defecto
	Enlace en la biografía: Activo por defecto
	Botones flotantes: Activo por defecto
	Eventos del editor de Elementor: Inactivo por defecto
	Widgets atómicos: Inactivo por defecto
	Lista de control del Launchpad: Inactivo por defecto
	Menú: Inactivo por defecto


== Registro ==
	
Log: showing 20 of 292024-10-28 12:45:53 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.24.8',
  'to' => '3.25.0',
)]
2024-10-28 12:56:05 [info] elementor-pro::elementor_pro_updater Started 
2024-10-28 12:56:05 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-10-28 12:56:05 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-10-28 12:56:05 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.24.4',
  'to' => '3.25.0',
)]
2024-10-28 12:56:06 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.24.4',
  'to' => '3.25.0',
)]
2024-10-29 21:02:26 [info] elementor::elementor_updater Started 
2024-10-29 21:02:26 [info] Elementor/Upgrades - _on_each_version Start  
2024-10-29 21:02:26 [info] Elementor/Upgrades - _on_each_version Finished 
2024-10-29 21:02:26 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.25.0',
  'to' => '3.25.2',
)]
2024-10-29 21:02:26 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.25.0',
  'to' => '3.25.2',
)]
2024-10-30 01:30:26 [info] elementor::elementor_updater Started 
2024-10-30 01:30:26 [info] Elementor/Upgrades - _on_each_version Start  
2024-10-30 01:30:26 [info] Elementor/Upgrades - _on_each_version Finished 
2024-10-30 01:30:26 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.25.2',
  'to' => '3.25.3',
)]
2024-10-30 01:30:26 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.25.2',
  'to' => '3.25.3',
)]
2024-11-01 00:38:26 [info] elementor-pro::elementor_pro_updater Started 
2024-11-01 00:38:26 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-11-01 00:38:26 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-11-01 00:38:26 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.25.0',
  'to' => '3.25.1',
)]

PHP: showing 7 of 7PHP: 2024-10-28 12:48:56 [warning X 45][/home/sportcoa/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php::695] Undefined array key -1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-10-28 13:42:34 [error X 23][/home/sportcoa/public_html/wp-content/plugins/elementor-pro/modules/global-widget/data/controller.php::31] Uncaught Error: Cannot use object of type WP_Error as array in /home/sportcoa/public_html/wp-content/plugins/elementor-pro/modules/global-widget/data/controller.php:31
Stack trace:
#0 /home/sportcoa/public_html/wp-includes/rest-api/class-wp-rest-server.php(1230): ElementorPro\Modules\GlobalWidget\Data\Controller->get_items(Object(WP_REST_Request))
#1 /home/sportcoa/public_html/wp-includes/rest-api/class-wp-rest-server.php(1063): WP_REST_Server->respond_to_request(Object(WP_REST_Request), '/elementor/v1/g...', Array, NULL)
#2 /home/sportcoa/public_html/wp-includes/rest-api/class-wp-rest-server.php(439): WP_REST_Server->dispatch(Object(WP_REST_Request))
#3 /home/sportcoa/public_html/wp-includes/rest-api.php(420): WP_REST_Server->serve_request('/elementor/v1/g...')
#4 /home/sportcoa/public_html/wp-includes/class-wp-hook.php(324): rest_api_loaded(Object(WP))
#5 /home/sportcoa/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#6 /home/sportcoa/public_html/wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#7 /home/sportcoa/public_html/wp-includes/class-wp.php(418): do_action_ref_array('parse_request', Array)
#8 /home/sportcoa/public_html/wp-includes/class-wp.php(813): WP->parse_request('')
#9 /home/sportcoa/public_html/wp-includes/functions.php(1336): WP->main('')
#10 /home/sportcoa/public_html/wp-blog-header.php(16): wp()
#11 /home/sportcoa/public_html/index.php(17): require('/home/sportcoa/...')
#12 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-10-29 21:15:23 [warning X 7][/home/sportcoa/public_html/wp-content/plugins/elementor/core/page-assets/data-managers/font-icon-svg/font-awesome.php::50] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-10-29 23:44:13 [warning X 3][/home/sportcoa/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::182] Undefined array key "editor_post_id" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-10-31 04:41:30 [error X 1][/home/sportcoa/public_html/wp-content/plugins/elementor-pro/modules/forms/fields/upload.php::329] Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /home/sportcoa/public_html/wp-content/plugins/elementor-pro/modules/forms/fields/upload.php:329
Stack trace:
#0 /home/sportcoa/public_html/wp-content/plugins/elementor-pro/modules/forms/fields/upload.php(329): count(NULL)
#1 /home/sportcoa/public_html/wp-includes/class-wp-hook.php(324): ElementorPro\Modules\Forms\Fields\Upload->validation(Array, Object(ElementorPro\Modules\Forms\Classes\Form_Record), Object(ElementorPro\Modules\Forms\Classes\Ajax_Handler))
#2 /home/sportcoa/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#3 /home/sportcoa/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /home/sportcoa/public_html/wp-content/plugins/elementor-pro/modules/forms/classes/form-record.php(65): do_action('elementor_pro/f...', Array, Object(ElementorPro\Modules\Forms\Classes\Form_Record), Object(ElementorPro\Modules\Forms\Classes\Ajax_Handler))
#5 /home/sportcoa/public_html/wp-content/plugins/elementor-pro/modules/forms/classes/ajax-handler.php(123): ElementorPro\Modules\Forms\Classes\Form_Record->validate(Object(ElementorPro\Modules\Forms\Classes\Ajax_Handler))
#6 /home/sportcoa/public_html/wp-includes/class-wp-hook.php(324): ElementorPro\Modules\Forms\Classes\Ajax_Handler->ajax_send_form('')
#7 /home/sportcoa/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#8 /home/sportcoa/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#9 /home/sportcoa/public_html/wp-admin/admin-ajax.php(207): do_action('wp_ajax_nopriv_...')
#10 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-11-01 08:59:36 [warning X 1][/home/sportcoa/public_html/wp-content/plugins/elementor/includes/base/widget-base.php::223] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: /home/sportcoa/public_html/wp-content/plugins/elementor/includes/base/widget-base.php(223): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/sportcoa/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(1828): Elementor\Widget_Base -> get_pointer_index()
#2: /home/sportcoa/public_html/wp-content/plugins/elementor/includes/controls/groups/base.php(130): Elementor\Controls_Stack -> end_popover()
#3: /home/sportcoa/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(780): Elementor\Group_Control_Base -> add_controls()
#4: /home/sportcoa/public_html/wp-content/plugins/elementor-pro/modules/carousel/widgets/media-carousel.php(493): Elementor\Controls_Stack -> add_group_control()
',
)]
PHP: 2024-11-01 08:59:36 [warning X 1][/home/sportcoa/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php::695] Undefined array key -1 [array (
  'trace' => '
#0: /home/sportcoa/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(695): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/sportcoa/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(1828): Elementor\Controls_Stack -> get_control_key()
#2: /home/sportcoa/public_html/wp-content/plugins/elementor/includes/controls/groups/base.php(130): Elementor\Controls_Stack -> end_popover()
#3: /home/sportcoa/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(780): Elementor\Group_Control_Base -> add_controls()
#4: /home/sportcoa/public_html/wp-content/plugins/elementor-pro/modules/carousel/widgets/media-carousel.php(493): Elementor\Controls_Stack -> add_group_control()
',
)]

JS: showing 6 of 6JS: 2024-10-28 12:05:23 [error X 8][https://www.sportcoa.com/wp-admin/load-scripts.php?c=0&loadchunk_0=jquery-core,jquery-migrate,utils,wp-hooks&ver=6.6.2:2:28760] Cannot read properties of undefined (reading 'value') 
JS: 2024-10-28 12:05:27 [error X 1][https://www.sportcoa.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.25.0:3:955964] elementorFrontend is not defined 
JS: 2024-10-28 12:42:57 [error X 5][https://www.sportcoa.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.24.8:3:664925] Cannot read properties of undefined (reading 'isDesignable') 
JS: 2024-10-28 13:05:29 [error X 22][https://www.sportcoa.com/wp-content/plugins/elementor/assets/js/common-modules.min.js?ver=3.25.0:2:56144] Model.isValidChild() should be implemented, please provide 'isValidChild' functionality. 
JS: 2024-11-01 13:22:03 [error X 1][https://www.sportcoa.com/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.25.1:3:67735] Cannot convert undefined or null to object 
JS: 2024-11-01 13:22:07 [error X 2][https://www.sportcoa.com/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.25.3:2:12909] Cannot read properties of undefined (reading 'data') 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibilidad no especificada

== Elementor Pro - Compatibility Tag ==
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hi @theitpyme (Cesar),

thank you so much for the detailed description. I was able to reproduce your issue, and I've already escalated it to our dev team. I'll make sure to update you as soon as I have more info. We are working on it! 🙏 

Kind regards

**Comment by nicholaszein** [comment]
Hi @theitpyme!

We have great news! 🙌 

### 📢 We're happy to announce that the issue was solved with the release of Elementor Core v3.25.4, and Elementor Pro v3.25.2! 🥳 

✅ Feel free to check it out and update both your plugins to the latest versions!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
