### ISSUE TITLE
⛔ 🧩 🛟 Support Request: Error sending an email

### ISSUE THREAD

**Issue by persianm** [elementor/elementor#29162]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Website: https://persianmarriagecelebrant.com.au/contact/

In the "Contact us" page, the below error message appears when submitting an email:
"There has been some error while submitting the form. Please verify all form fields again."

Please help,

[
![Screenshot WP Email error](https://github.com/user-attachments/assets/dfd2c187-4847-442c-b277-000779dd172b)
](url)

### Steps to reproduce

1. go to website: https://persianmarriagecelebrant.com.au/
2. Click on "CONTACT"
3. Fill in the name, email and a message
4. Click on "Send"

### Expected behavior

An email should be sent to **[the site admin email]**

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt


== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.5.22
	PHP Version: 8.2.11
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: No
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.6.2
	Site URL: https://persianmarriagecelebrant.com.au
	Home URL: https://persianmarriagecelebrant.com.au
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en_US
	Timezone: 11
	Debug Mode: Inactive

== Theme ==
	Name: Astra
	Version: 4.6.5
	Author: Brainstorm Force
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en-AU
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0

== Active Plugins ==
	Astra Widgets
		Version: 1.2.12
		Author: Brainstorm Force

	Better Search Replace
		Version: 1.4.5
		Author: WP Engine

	Elementor
		Version: 3.25.0-dev3
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.3
		Author: Elementor.com

	Elementor Header & Footer Builder
		Version: 1.6.45
		Author: Brainstorm Force, Nikhil Chavan

	ElementsKit Lite
		Version: 3.0.4
		Author: Wpmet

	Envira Gallery Lite
		Version: 1.8.8
		Author: Envira Gallery Team

	Essential Addons for Elementor
		Version: 5.9.10
		Author: WPDeveloper

	Essential Blocks
		Version: 4.5.1
		Author: WPDeveloper

	Google Analytics for WordPress by MonsterInsights
		Version: 8.24.0
		Author: MonsterInsights

	Gutenberg
		Version: 19.5.1
		Author: Gutenberg Team

	HubSpot All-In-One Marketing - Forms, Popups, Live Chat
		Version: 10.2.23
		Author: HubSpot

	Jetpack
		Version: 13.9.1
		Author: Automattic

	Media Library Helper by Codexin
		Version: 1.3.0
		Author: Codexin Technologies

	MetForm
		Version: 3.8.3
		Author: Wpmet

	Popup Maker
		Version: 1.18.2
		Author: Popup Maker

	Really Simple SSL
		Version: 7.2.3
		Author: Really Simple Plugins

	Site Kit by Google
		Version: 1.120.0
		Author: Google

	Spectra
		Version: 2.12.3
		Author: Brainstorm Force

	SSL Insecure Content Fixer
		Version: 2.7.2
		Author: WebAware

	Starter Templates
		Version: 4.0.13
		Author: Brainstorm Force

	UpdraftPlus - Backup/Restore
		Version: 1.24.6
		Author: TeamUpdraft, DavidAnderson

	WordPress Importer
		Version: 0.8.2
		Author: wordpressdotorg

	WP Call Button
		Version: 1.4.1
		Author: Syed Balkhi

	WP File Manager
		Version: 7.2.2
		Author: mndpsingh287

	WPForms Lite
		Version: 1.8.6.4
		Author: WPForms

	WP Go Maps (formerly WP Google Maps)
		Version: 9.0.32
		Author: WP Go Maps (formerly WP Google Maps)

	WP Mail SMTP
		Version: 4.1.1
		Author: WP Mail SMTP

	WP Rollback
		Version: 2.0.6
		Author: WP Rollback


== Elementor Experiments ==
	Improved CSS Loading: Active by default
	Inline Font Icons: Active by default
	Additional Custom Breakpoints: Active by default
	Container: Active by default
	Upgrade Swiper Library: Active by default
	Nested Elements Performance: Active by default
	Optimized Control Loading: Active by default
	Optimized Markup: Inactive by default
	Conditionally load Swiper CSS files: Inactive by default
	Plugin Onboarding: Active by default
	CSS Smooth Scroll: Active by default
	Elementor Home Screen: Active by default
	Landing Pages: Active by default
	Nested Elements: Active by default
	Editor Top Bar: Active by default
	Pages Panel: Inactive by default
	Element Caching: Active by default
	Link In Bio: Active by default
	Floating Buttons: Active by default
	Elementor Editor Events: Inactive by default
	Atomic Widgets: Inactive by default
	Launchpad Checklist: Inactive by default


== Log ==
	
Log: showing 20 of 382024-01-15 16:04:59 [info] elementor::elementor_updater Started 
2024-01-15 16:04:59 [info] Elementor/Upgrades - _on_each_version Start  
2024-01-15 16:04:59 [info] Elementor/Upgrades - _on_each_version Finished 
2024-01-15 16:04:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.18.0-dev4',
  'to' => '3.19.0-dev2',
)]
2024-01-16 08:19:42 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.19.0-dev2',
  'to' => '3.19.0-dev3',
)]
2024-01-16 08:19:43 [info] elementor::elementor_updater Started 
2024-01-16 08:19:43 [info] Elementor/Upgrades - _on_each_version Start  
2024-01-16 08:19:43 [info] Elementor/Upgrades - _on_each_version Finished 
2024-01-16 08:19:43 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.19.0-dev2',
  'to' => '3.19.0-dev3',
)]
2024-01-23 06:24:37 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.19.0-dev3',
  'to' => '3.19.0-dev5',
)]
2024-01-23 06:24:40 [info] elementor::elementor_updater Started 
2024-01-23 06:24:40 [info] Elementor/Upgrades - _on_each_version Start  
2024-01-23 06:24:40 [info] Elementor/Upgrades - _on_each_version Finished 
2024-01-23 06:24:40 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.19.0-dev3',
  'to' => '3.19.0-dev5',
)]
2024-01-28 17:29:40 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.19.0-dev5',
  'to' => '3.19.0-dev6',
)]
2024-01-28 17:29:42 [info] elementor::elementor_updater Started 
2024-01-28 17:29:42 [info] Elementor/Upgrades - _on_each_version Start  
2024-01-28 17:29:42 [info] Elementor/Upgrades - _on_each_version Finished 
2024-01-28 17:29:42 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.19.0-dev5',
  'to' => '3.19.0-dev6',
)]
2024-01-28 17:29:43 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.19.0-dev5',
  'to' => '3.19.0-dev6',
)]

PHP: showing 4 of 4PHP: 2023-10-13 12:16:10 [notice X 5][../wp-content/plugins/elementor/core/files/css/base.php::778] Undefined index: padding_mobile [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-01-03 21:32:14 [warning X 1][../wp-content/plugins/elementor/core/files/css/base.php::778] Undefined array key "padding_mobile" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-02-23 12:36:17 [warning X 39656][../wp-content/plugins/elementor/core/kits/manager.php::280] Attempt to read property "post_status" on null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-02-23 13:05:59 [error X 1][../wp-content/plugins/elementor/core/settings/page/manager.php::101] Uncaught Exception: Invalid post. in ../wp-content/plugins/elementor/core/settings/page/manager.php:101
Stack trace:
#0 ../wp-content/plugins/elementor/core/base/document.php(1737): Elementor\Core\Settings\Page\Manager->ajax_before_save_settings()
#1 ../wp-content/plugins/elementor/core/base/document.php(855): Elementor\Core\Base\Document->save_settings()
#2 ../wp-content/plugins/elementor/core/kits/manager.php(295): Elementor\Core\Base\Document->update_settings()
#3 ../wp-content/plugins/elementor/core/kits/manager.php(464): Elementor\Core\Kits\Manager->update_kit_settings_based_on_option()
#4 ../wp-includes/class-wp-hook.php(326): Elementor\Core\Kits\Manager->Elementor\Core\Kits\{closure}()
#5 ../wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#6 ../wp-includes/plugin.php(517): WP_Hook->do_action()
#7 ../wp-includes/option.php(883): do_action()
#8 ../wp-includes/class-wp-customize-setting.php(659): update_option()
#9 ../wp-includes/class-wp-customize-setting.php(685): WP_Customize_Setting->set_root_value()
#10 ../wp-includes/class-wp-customize-setting.php(541): WP_Customize_Setting->update()
#11 ../wp-includes/class-wp-customize-manager.php(3576): WP_Customize_Setting->save()
#12 ../wp-includes/theme.php(3637): WP_Customize_Manager->_publish_changeset_values()
#13 ../wp-includes/class-wp-hook.php(324): _wp_customize_publish_changeset()
#14 ../wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#15 ../wp-includes/plugin.php(517): WP_Hook->do_action()
#16 ../wp-includes/post.php(5390): do_action()
#17 ../wp-includes/post.php(4650): wp_transition_post_status()
#18 ../wp-includes/post.php(4862): wp_insert_post()
#19 ../wp-includes/class-wp-customize-manager.php(2969): wp_update_post()
#20 ../wp-includes/class-wp-customize-manager.php(2525): WP_Customize_Manager->save_changeset_post()
#21 ../wp-includes/class-wp-hook.php(324): WP_Customize_Manager->save()
#22 ../wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#23 ../wp-includes/plugin.php(517): WP_Hook->do_action()
#24 ../wp-admin/admin-ajax.php(188): do_action()
#25 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Header & Footer Builder: Compatibility not specified
	Essential Addons for Elementor: Compatibility not specified

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hello @persianm,

Thanks for contacting us! 🙏 

### 🛟 This is more of a support question, not really something we can help with here. 

The form you are having an error is not even from Elementor, it's from a plugin called UAG. Please, reach out to the plugin author to sort your problem.

This space if meant to be used to report confirmed and validated bugs in the Elementor Editor plugin, please don't use it for personal support. We are unable to provide personal support here, especially for 3rd-party plugins. Thank you for understanding.

Kind regards
