### ISSUE TITLE
❌ 🧩 Fixing Top-Right Popup Issue in Elementor After Update

### ISSUE THREAD

**Issue by hifisayed** [elementor/elementor#29179]
### Prerequisites

- [ ] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Experiencing issues with popups displaying in the top-right corner instead of the center after updating Elementor? Learn how to adjust settings for both mobile and desktop to restore your popup to its correct centered position. This guide walks you through troubleshooting and fixing display problems caused by recent updates.

### Steps to reproduce

![image](https://github.com/user-attachments/assets/085eb9d2-b68f-4e9d-88c2-d2e9501c4c95)

### Expected behavior

![image](https://github.com/user-attachments/assets/7a2c68f5-1aa6-4db7-91e4-7d7b93beac62)

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [ ] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt

== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.11.8-MariaDB-cll-lve
	PHP Version: 8.2.14
	PHP Memory Limit: 512M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.6.2
	Site URL: https://ouprephub.in
	Home URL: https://ouprephub.in
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en_US
	Timezone: Asia/Kolkata
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 3.1.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36

== Active Plugins ==
	Code Snippets
		Version: 3.6.5.1
		Author: Code Snippets Pro

	Elementor
		Version: 3.25.4
		Author: Elementor.com

	Instant Indexing
		Version: 1.1.21
		Author: Rank Math

	LiteSpeed Cache
		Version: 6.5.2
		Author: LiteSpeed Technologies

	PRO Elements
		Version: 3.25.0
		Author: PROElements.org

	Rank Math SEO
		Version: 1.0.231
		Author: Rank Math

	Site Kit by Google
		Version: 1.138.0
		Author: Google

	UpdraftPlus - Backup/Restore
		Version: 1.24.6
		Author: TeamUpdraft, DavidAnderson


== Must-Use Plugins ==
	Disable Auto Updates
		Version: 
		Author: 


== Elements Usage ==
	
	page : 19
		animated-headline : 12
		button : 96
		container : 32
		heading : 1
		nested-tabs : 1
		text-editor : 3
	popup : 116
		animated-headline : 97
		button : 291
		container : 194
		heading : 97
		image : 96
	wp-page : 6
		animated-headline : 12
		button : 96
		container : 32
		heading : 1
		nested-tabs : 1
		text-editor : 3
	single-post : 1
		container : 3
		image : 3
		post-info : 1
		table-of-contents : 1
		theme-post-content : 1
		theme-post-title : 1


== Settings ==
	
	cpt_support: post, page
	disable_color_schemes: yes
	disable_typography_schemes: yes
	allow_tracking: yes
	editor_break_lines: 1
	unfiltered_files_upload: 1
	font_display: swap


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Active
	Additional Custom Breakpoints: Active
	Container: Active
	Upgrade Swiper Library: Active
	Nested Elements Performance: Active by default
	Optimized Control Loading: Active
	Optimized Markup: Active
	Conditionally load Swiper CSS files: Inactive by default
	Plugin Onboarding: Active by default
	CSS Smooth Scroll: Active by default
	Default to New Theme Builder: Active
	Header & Footer: Active
	Elementor Home Screen: Active by default
	Landing Pages: Active
	Nested Elements: Active
	Editor Top Bar: Active
	Pages Panel: Inactive by default
	Element Caching: Active
	Link In Bio: Active by default
	Floating Buttons: Active by default
	Elementor Editor Events: Inactive by default
	Atomic Widgets: Inactive by default
	Launchpad Checklist: Inactive by default
	Menu: Active


== Log ==
	
PHP: showing 6 of 6PHP: 2024-09-19 17:56:35 [notice X 22][../wp-content/plugins/elementor-pro/modules/screenshots/module.php::33] Function utf8_decode() is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-09-20 14:32:27 [error X 3][../wp-content/plugins/elementor-pro/core/utils.php::81] Uncaught Error: Call to a member function get_main_id() on null in ../wp-content/plugins/elementor-pro/core/utils.php:81
Stack trace:
#0 ../wp-content/plugins/elementor-pro/modules/search/widgets/search.php(1714): ElementorPro\Core\Utils::get_current_post_id()
#1 ../wp-content/plugins/elementor-pro/modules/search/widgets/search.php(1591): ElementorPro\Modules\Search\Widgets\Search->add_render_attibutes()
#2 ../wp-content/plugins/elementor/includes/base/controls-stack.php(2325): ElementorPro\Modules\Search\Widgets\Search->render()
#3 ../wp-content/plugins/elementor/includes/base/widget-base.php(635): Elementor\Controls_Stack->render_by_mode()
#4 ../wp-content/plugins/elementor/includes/base/widget-base.php(699): Elementor\Widget_Base->render_content()
#5 ../wp-content/plugins/elementor/includes/db.php(202): Elementor\Widget_Base->render_plain_content()
#6 ../wp-content/plugins/elementor/includes/db.php(208): Elementor\DB->render_element_plain_content()
#7 ../wp-content/plugins/elementor/includes/db.php(558): Elementor\DB->render_element_plain_content()
#8 ../wp-content/plugins/elementor/includes/db.php(539): Elementor\DB->get_plain_text_from_data()
#9 ../wp-content/plugins/elementor/includes/db.php(230): Elementor\DB->get_plain_text()
#10 ../wp-content/plugins/elementor/core/base/document.php(1366): Elementor\DB->save_plain_text()
#11 ../wp-content/plugins/elementor/core/base/document.php(856): Elementor\Core\Base\Document->save_elements()
#12 ../wp-content/plugins/elementor/includes/template-library/sources/local.php(534): Elementor\Core\Base\Document->save()
#13 ../wp-content/plugins/elementor/includes/template-library/manager.php(269): Elementor\TemplateLibrary\Source_Local->save_item()
#14 [internal function]: Elementor\TemplateLibrary\Manager->save_template()
#15 ../wp-content/plugins/elementor/includes/template-library/manager.php(611): call_user_func()
#16 ../wp-content/plugins/elementor/includes/template-library/manager.php(644): Elementor\TemplateLibrary\Manager->handle_ajax_request()
#17 [internal function]: Elementor\TemplateLibrary\Manager->Elementor\TemplateLibrary\{closure}()
#18 ../wp-content/plugins/elementor/core/common/modules/ajax/module.php(176): call_user_func()
#19 ../wp-includes/class-wp-hook.php(324): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#20 ../wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#21 ../wp-includes/plugin.php(517): WP_Hook->do_action()
#22 ../wp-admin/admin-ajax.php(192): do_action()
#23 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-10-17 18:36:21 [warning X 1][../wp-content/plugins/elementor-pro/elementor-pro.php::63] Constant ELEMENTOR_PRO_MODULES_URL already defined [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-10-17 19:48:25 [warning X 50][../wp-content/plugins/elementor/includes/managers/image.php::113] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-10-17 20:28:00 [warning X 1][../wp-content/plugins/elementor/includes/base/controls-stack.php::1487] Undefined array key "_flex_size_tablet" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-11-01 17:50:27 [notice X 7][../wp-content/plugins/elementor/includes/base/controls-stack.php::229] hexdec(): Passing null to parameter #1 ($hex_string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 5 of 5JS: 2024-09-20 09:36:50 [error X 8][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.24.3:3:837409] Cannot read properties of undefined (reading 'localized') 
JS: 2024-09-23 10:51:25 [error X 1][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.24.3:3:836902] Cannot read properties of undefined (reading 'toLowerCase') 
JS: 2024-10-17 14:18:14 [error X 1][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.24.7:3:664925] Cannot read properties of undefined (reading 'isDesignable') 
JS: 2024-10-21 05:22:28 [error X 1][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.24.7:3:650276] J is not a constructor 
JS: 2024-11-02 16:58:25 [error X 1][../wp-content/plugins/elementor/assets/js/packages/editor-documents/editor-documents.min.js?ver=3.25.3:1:5030] Cannot read properties of null (reading 'editor') 

Log: showing 20 of 322024-11-01 17:44:09 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.24.4',
  'to' => '3.25.0',
)]
2024-11-01 17:44:09 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.24.4',
  'to' => '3.25.0',
)]
2024-11-01 17:46:32 [info] elementor::elementor_updater Started 
2024-11-01 17:46:32 [info] Elementor/Upgrades - _on_each_version Start  
2024-11-01 17:46:32 [info] Elementor/Upgrades - _on_each_version Finished 
2024-11-01 17:46:32 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.24.7',
  'to' => '3.25.3',
)]
2024-11-01 18:50:03 [info] Elementor custom task(s) process has been queued. [array (
  0 => 
  array (
    0 => 
    array (
      0 => 'Elementor\Core\Upgrade\Custom_Tasks',
      1 => 'opt_in_recalculate_usage',
    ),
    1 => 
    array (
      0 => 'Elementor\Core\Upgrade\Custom_Tasks',
      1 => 'opt_in_send_tracking_data',
    ),
  ),
)]
2024-11-01 18:50:03 [info] elementor::custom_task_manger Started 
2024-11-01 18:50:03 [info] Elementor/Tasks - opt_in_recalculate_usage Start  
2024-11-01 18:50:04 [info] Elementor/Tasks - opt_in_recalculate_usage callback needs to run again 
2024-11-01 18:50:04 [info] Elementor/Tasks - opt_in_send_tracking_data Start  
2024-11-01 18:50:04 [info] Elementor/Tasks - opt_in_send_tracking_data Finished 
2024-11-01 18:50:04 [info] Elementor/Tasks - opt_in_recalculate_usage Start (x2) 
2024-11-01 18:50:04 [info] Elementor/Tasks - opt_in_recalculate_usage Finished 
2024-11-01 18:50:04 [info] elementor::custom_task_manger Completed 
2024-11-04 06:37:03 [info] elementor::elementor_updater Started 
2024-11-04 06:37:03 [info] Elementor/Upgrades - _on_each_version Start  
2024-11-04 06:37:03 [info] Elementor/Upgrades - _on_each_version Finished 
2024-11-04 06:37:03 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.25.3',
  'to' => '3.25.4',
)]
2024-11-04 06:37:03 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.25.3',
  'to' => '3.25.4',
)]



== Elementor - Compatibility Tag ==
	
	PRO Elements: Compatible

== Elementor Pro - Compatibility Tag ==
````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hello @hifisayed.

You are using the PRO Elements plugin. We do not provide support for this plugin.
