### ISSUE TITLE
Site Settings link always 301 redirects to posts page

### ISSUE THREAD

**Issue by jamieburchell** [elementor/elementor#29194]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

When clicking the "Site Settings" link from the top bar when browsing the front end while logged in, the browser is always 302 redirected to the main posts screen.

[Here's a screencast](https://www.dropbox.com/scl/fi/g0s11udj6risihzsct3vg/elementor-site-settings-link-never-works.mp4?rlkey=njqyz6d4i8q1ecasd24j8u992&st=s4u67mxr&dl=0).

Note that the redirect is happening [here](https://github.com/WordPress/WordPress/blob/364a6c50a0d4ba440fca9d0087345b5b521b5d84/wp-admin/post.php#L365)

As an aside, the "Site Settings" link doesn't show at all if the front page is set as "Your latest posts" and not "A static page".

### Steps to reproduce

1. Click "Site Settings" link or copy/paste the URL manually in the address bar

### Expected behavior

Site settings link should work.

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [ ] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.52 (Ubuntu)
	MySQL version: Ubuntu 22.04 v10.6.18
	PHP Version: 8.2.24
	PHP Memory Limit: 256M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.6.2
	Site URL: https://example.local.test/wp
	Home URL: https://example.local.test
	WP Multisite: No
	Max Upload Size: 50 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /news/%postname%/
	Language: en_US
	Timezone: Europe/London
	Admin Email: jamie@ib3.uk
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 2.0.0
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 3.1.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.25.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.25.2
		Author: Elementor.com


== Must-Use Plugins ==
	Bedrock Autoloader
		Version: 1.0.3
		Author: Roots

	Disable status tests
		Version: 1.0.0
		Author: Roots

	Register Theme Directory
		Version: 1.0.0
		Author: Roots


== Features ==
	Custom Fonts: 1
	Custom Icons: 0

== Integrations ==
	
	google_maps: Active
	recaptcha_v3: Active


== Elementor Experiments ==
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Active
	Additional Custom Breakpoints: Inactive
	Container: Active
	Upgrade Swiper Library: Active
	Nested Elements Performance: Active by default
	Optimized Control Loading: Inactive
	Optimized Markup: Inactive by default
	Conditionally load Swiper CSS files: Inactive by default
	Plugin Onboarding: Active by default
	CSS Smooth Scroll: Active by default
	Default to New Theme Builder: Active
	Header & Footer: Inactive
	Elementor Home Screen: Active by default
	Landing Pages: Inactive
	Nested Elements: Inactive
	Editor Top Bar: Inactive
	Element Caching: Inactive
	Link In Bio: Active by default
	Floating Buttons: Active by default
	Elementor Editor Events: Inactive by default
	Atomic Widgets: Inactive by default
	Launchpad Checklist: Inactive by default
	Menu: Inactive


== Log ==
	
Log: showing 20 of 382024-11-05 13:18:32 [info] elementor-pro::elementor_pro_updater Started 
2024-11-05 13:18:32 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-11-05 13:18:32 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-11-05 13:18:32 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.24.4',
  'to' => '3.25.2',
)]
2024-11-05 13:18:32 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.24.4',
  'to' => '3.25.2',
)]
2024-11-05 13:18:36 [info] elementor-pro::elementor_pro_updater Started 
2024-11-05 13:18:36 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-11-05 13:18:36 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-11-05 13:18:36 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.24.4',
  'to' => '3.25.2',
)]
2024-11-05 13:18:36 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.24.4',
  'to' => '3.25.2',
)]
2024-11-05 13:18:45 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.24.4',
  'to' => '3.25.2',
)]
2024-11-05 13:18:45 [info] elementor-pro::elementor_pro_updater Started 
2024-11-05 13:18:45 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-11-05 13:18:45 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-11-05 13:18:45 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.24.4',
  'to' => '3.25.2',
)]
2024-11-05 13:18:48 [info] elementor-pro::elementor_pro_updater Started 
2024-11-05 13:18:48 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-11-05 13:18:48 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-11-05 13:18:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.24.4',
  'to' => '3.25.2',
)]
2024-11-05 13:18:48 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.24.4',
  'to' => '3.25.2',
)]

PHP: showing 4 of 4PHP: 2024-11-05 13:18:45 [warning X 1][/home/jamie/projects/example.local.test/web/app/plugins/elementor/core/files/manager.php::112] unlink(/home/jamie/projects/example.local.test/web/app/uploads/elementor/css/post-3118.css): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-11-05 13:19:57 [warning X 44][/home/jamie/projects/example.local.test/web/app/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key "condition_type" [array (
  'trace' => '
#0: /home/jamie/projects/example.local.test/web/app/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /home/jamie/projects/example.local.test/web/app/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /home/jamie/projects/example.local.test/web/app/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /home/jamie/projects/example.local.test/web/app/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2024-11-05 13:20:00 [error X 1][/home/jamie/projects/example.local.test/web/app/plugins/elementor-pro/modules/screenshots/module.php::229] Uncaught WpOrg\Requests\Exception\Http\Status403: 403 Forbidden in /home/jamie/projects/example.local.test/web/app/plugins/elementor-pro/modules/screenshots/module.php:229
Stack trace:
#0 /home/jamie/projects/example.local.test/web/app/plugins/elementor-pro/modules/screenshots/module.php(264): ElementorPro\Modules\Screenshots\Module->is_screenshot_proxy_mode()
#1 /home/jamie/projects/example.local.test/web/app/plugins/elementor/core/base/module.php(85): ElementorPro\Modules\Screenshots\Module->__construct()
#2 /home/jamie/projects/example.local.test/web/app/plugins/elementor-pro/core/modules-manager.php(98): Elementor\Core\Base\Module::instance()
#3 /home/jamie/projects/example.local.test/web/app/plugins/elementor-pro/plugin.php(366): ElementorPro\Core\Modules_Manager->__construct()
#4 /home/jamie/projects/example.local.test/web/wp/wp-includes/class-wp-hook.php(324): ElementorPro\Plugin->on_elementor_init()
#5 /home/jamie/projects/example.local.test/web/wp/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#6 /home/jamie/projects/example.local.test/web/wp/wp-includes/plugin.php(517): WP_Hook->do_action()
#7 /home/jamie/projects/example.local.test/web/app/plugins/elementor/includes/plugin.php(685): do_action()
#8 /home/jamie/projects/example.local.test/web/wp/wp-includes/class-wp-hook.php(324): Elementor\Plugin->init()
#9 /home/jamie/projects/example.local.test/web/wp/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#10 /home/jamie/projects/example.local.test/web/wp/wp-includes/plugin.php(517): WP_Hook->do_action()
#11 /home/jamie/projects/example.local.test/web/wp/wp-settings.php(700): do_action()
#12 /home/jamie/projects/example.local.test/web/wp-config.php(9): require_once('...')
#13 /home/jamie/projects/example.local.test/web/wp/wp-load.php(55): require_once('...')
#14 /home/jamie/projects/example.local.test/web/wp/wp-blog-header.php(13): require_once('...')
#15 /home/jamie/projects/example.local.test/web/index.php(6): require('...')
#16 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-11-05 13:28:11 [warning X 1][/home/jamie/projects/example.local.test/web/app/plugins/elementor-pro/modules/posts/skins/skin-content-base.php::271] Attempt to read property "ID" on null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hi @jamieburchell! How's it going?

Thank you for reaching out! 🙂 

I cannot reproduce your issue, when I try it on my testing site, I get correctly redirected to the Site Settings as expected. See the video below:

https://github.com/user-attachments/assets/63c70849-9b57-4cb6-bc9b-1d7280a705c7


Note that the video is sped-up to 2x its the regular speed just to reduce the viewing time.

I've watched your screencast, and I can see that when you hover over the Site Settings link, the redirect appears correctly as well:

![Captura de tela 2024-11-05 114759](https://github.com/user-attachments/assets/2f4d4e26-8a14-4ea6-8353-6d35d93f49d9)

![image](https://github.com/user-attachments/assets/a0e10362-9fd3-450a-9d37-e2a4c48be5e9)

You can see in the zoomed-in screenshot, that the link points to the current post ID + the "active-document", which would indicate the Site Settings post ID.

To make sure this was not a fluke on my part, I also tested on a page that was not previously edited with Elementor, as yours appear to be, and it still worked as expected. You can see that in the video above. In this case, as well as when you have the Homepage set as the Posts page, Elementor will open the last created document that was edited with Elementor (in this case with a title of "Nested Accordion"), and then open the Site Settings.

I see you are testing your site on a localhost. This might be a problem with your permalink structure, or rewrite rules. Try flushing the permalink transients, and check your localhost configuration to see if you're not having a problem with redirects.

**Comment by jamieburchell** [comment]
Hi @nicholaszein 

I tried flushing the permalink structure. Note that I only have Elementor free and Pro installed. I followed the code and the redirect takes place in the WordPress core code. I don't know what else to say.

**Comment by nicholaszein** [comment]
Hi @jamieburchell,

please test on a live website hosted on a public server and let me know.

**Comment by nicholaszein** [comment]
@jamieburchell preferably on a build that does not use Bedrock.

**Comment by jamieburchell** [comment]
Hi @nicholaszein 

It doesn't work on any of the public websites I manage either. I did the repro locally so I could troubleshoot further. Not really sure how Bedrock is relevant. I'll keep investigating.

**Comment by nicholaszein** [comment]
@jamieburchell,

I know you use Bedrock to build your sites. Bedrock is a highly modified version of WordPress, that changes a lot of default methods, including adding complex redirections to plugin and theme files due to the different file structure. It may indeed be the cause of your issue. 

I've just tested on two other different live websites and the link opens the Site Settings correctly every time. I also tested on two different local installations, one using LocalWP and the other using DevKinsta, both working as expected as well. 

Something on your side is not working as expected. It could be a compatibility issue with your stack. But we can only know if you test it in a different environment like I did, using both Chrome and Firefox to exclude possible browser conflicts. Usually, most of the issues you post are not reproducible on normal installations. I'm trying to give you the chance to check if we can find the root of these issues once and for all.

**Comment by jamieburchell** [comment]
I understand your comment @nicholaszein, but Bedrock really doesn't modify as much as you suggest it does. It certainly doesn't modify WordPress core files in any way.

I have just spent most of the day trying to figure out why Global Widgets suddenly broke in 24.8, so I'm a little tired already.

**Comment by nicholaszein** [comment]
I never said Bedrock modifies core WordPress files. What I said is that modifies the file structure and with that it implements deep changes on how WordPress behaves and handles permalink routing. Maybe the changes Bedrock makes cause conflicts with Elementor, which was not built to work with Bedrock. 

The latest versions of Elementor and Elementor Pro solve the issue with Global Widgets introduced after the security enhancement added to the Template Library (which includes Global Widgets).

**Comment by jamieburchell** [comment]
@nicholaszein It appears to be related to the post ID, since it works if I manually change the URL to:

https://example.local.test/wp/wp-admin/post.php?post=8&action=elementor&active-document=8

Then the "Default Kit" page appears to the right and the Site Settings bar to the left.

**Comment by nicholaszein** [comment]
@jamieburchell,

Do you have any page in this website that was previously edited with Elementor?

The ID of the post should never be the ID of the default kit. Only the active post can be the the same ID of the Default Kit, which is what is handled by the Site Settings.

**Comment by nicholaszein** [comment]
@jamieburchell, please watch my video to the end. I cover clicking on the link from a page that was not edited with Elementor. I also explained how Elementor handles these cases in my first comment.

**Comment by jamieburchell** [comment]
[Updated screencast](https://www.dropbox.com/scl/fi/hew3f52t037jljvcegv7x/elementor-site-settings-link-broken-when-not-elementor-post.mp4?rlkey=b777bckawu4lb4mce78yunbyx&st=5saf8ayt&dl=0)

**Comment by jamieburchell** [comment]
@nicholaszein 

> Usually, most of the issues you post are not reproducible on normal installations. I'm trying to give you the chance to check if we can find the root of these issues once and for all.

With respect, that is your opinion and not based on any evidence. If you feel that any of the issues I currently have open are caused by Roots Bedrock, kindly respond in those issues so that like with this issue, I can demonstrate otherwise.

**Comment by nicholaszein** [comment]
@jamieburchell,

I hope my comment hasn't offended you, as this was not my intention. If it has, I sincerely apologize. 🙏 

I can guarantee you, no issue submitted here is being ignored. All issues are being accounted for, even if they haven't received an answer yet. The answer will come. 😉 

We are working on some important changes to how issues are handled here, and due to the significant backlog, this is taking a lot longer than we wanted (me personally). Nonetheless, as soon as we have our tools finally deployed we'll start working on giving the feedback everyone deserves. We are getting there! 💪

**Comment by jamieburchell** [comment]
@nicholaszein I just felt that Bedrock was/is being used as a scapegoat and unfairly attributed as the cause of the issues I am reporting when I don't believe that is the case at all. In fact, I'm not aware of any issues from any plugins (including Elementor) that I can attribute to Bedrock.

Anyway, off topic. That's positive and much welcome news regarding future changes and I am glad that reported issues are being looked at.

**Comment by cookiemachine** [comment]
Hello! Just wanted to mention that I have a similar issue (Free Version of Elementor). I don't use Bedrock.
