### ISSUE TITLE
Full width social icons widget does not respect alignment change on mobile breakpoint on iOS Chrome/Safari

### ISSUE THREAD

**Issue by jamieburchell** [elementor/elementor#29200]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

The social icon widget does not properly respect the content alignment option in iOS Chrome/Safari.

[Here's a screencast](https://www.dropbox.com/scl/fi/3vx6inlp19h1z4oae4ggi/social-widget-alignment-issue-pt1.mp4?rlkey=bho3vsr0fphrkg6k5wpoh7cmn&st=8b318gi5&dl=0) demonstrating how the alignment changes between breakpoints works as expected on desktop Chrome/Safari

Here is the result on iOS Chrome/Safari:

![social-widget-alignment-issue-pt2](https://github.com/user-attachments/assets/00f64dc2-6952-41c7-a1cc-c36d76c53f9c)

Workaround: Set the widget to inline auto, the container to flex-direction column and align centrally.

### Steps to reproduce

1. Add social icon widget to container
2. Set social icon widget to full width
3. Desktop: content align right
4. Mobile: content align centre

### Expected behavior

Social icon widget should be aligned centre on mobile breakpoint on iOS Chrome/Safari

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.52 (Ubuntu)
	MySQL version: Ubuntu 22.04 v10.6.18
	PHP Version: 8.2.24
	PHP Memory Limit: 256M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.6.2
	Site URL: https://example.local.test/wp
	Home URL: https://example.local.test
	WP Multisite: No
	Max Upload Size: 50 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /news/%postname%/
	Language: en_US
	Timezone: Europe/London
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 2.0.0
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 3.1.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.25.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.25.2
		Author: Elementor.com


== Must-Use Plugins ==
	Bedrock Autoloader
		Version: 1.0.3
		Author: Roots

	Disable status tests
		Version: 1.0.0
		Author: Roots

	Register Theme Directory
		Version: 1.0.0
		Author: Roots


== Features ==
	Custom Fonts: 1
	Custom Icons: 0

== Integrations ==
	
	google_maps: Active
	recaptcha_v3: Active


== Elementor Experiments ==
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Active
	Additional Custom Breakpoints: Inactive
	Container: Active
	Upgrade Swiper Library: Active
	Nested Elements Performance: Active by default
	Optimized Control Loading: Inactive
	Optimized Markup: Inactive by default
	Conditionally load Swiper CSS files: Inactive by default
	Plugin Onboarding: Active by default
	CSS Smooth Scroll: Active by default
	Default to New Theme Builder: Active
	Header & Footer: Inactive
	Elementor Home Screen: Active by default
	Landing Pages: Inactive
	Nested Elements: Inactive
	Editor Top Bar: Inactive
	Element Caching: Inactive
	Link In Bio: Active by default
	Floating Buttons: Active by default
	Elementor Editor Events: Inactive by default
	Atomic Widgets: Inactive by default
	Launchpad Checklist: Inactive by default
	Menu: Inactive


== Log ==
	
Log: showing 20 of 382024-11-05 13:18:32 [info] elementor-pro::elementor_pro_updater Started 
2024-11-05 13:18:32 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-11-05 13:18:32 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-11-05 13:18:32 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.24.4',
  'to' => '3.25.2',
)]
2024-11-05 13:18:32 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.24.4',
  'to' => '3.25.2',
)]
2024-11-05 13:18:36 [info] elementor-pro::elementor_pro_updater Started 
2024-11-05 13:18:36 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-11-05 13:18:36 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-11-05 13:18:36 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.24.4',
  'to' => '3.25.2',
)]
2024-11-05 13:18:36 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.24.4',
  'to' => '3.25.2',
)]
2024-11-05 13:18:45 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.24.4',
  'to' => '3.25.2',
)]
2024-11-05 13:18:45 [info] elementor-pro::elementor_pro_updater Started 
2024-11-05 13:18:45 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-11-05 13:18:45 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-11-05 13:18:45 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.24.4',
  'to' => '3.25.2',
)]
2024-11-05 13:18:48 [info] elementor-pro::elementor_pro_updater Started 
2024-11-05 13:18:48 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-11-05 13:18:48 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-11-05 13:18:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.24.4',
  'to' => '3.25.2',
)]
2024-11-05 13:18:48 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.24.4',
  'to' => '3.25.2',
)]

PHP: showing 4 of 4PHP: 2024-11-05 13:18:45 [warning X 1][../plugins/elementor/core/files/manager.php::112] unlink(../uploads/elementor/css/post-3118.css): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-11-05 13:19:57 [warning X 44][../plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key "condition_type" [array (
  'trace' => '
#0: ../plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: ../plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: ../plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: ../plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2024-11-05 13:20:00 [error X 1][../plugins/elementor-pro/modules/screenshots/module.php::229] Uncaught WpOrg\Requests\Exception\Http\Status403: 403 Forbidden in ../plugins/elementor-pro/modules/screenshots/module.php:229
Stack trace:
#0 ../plugins/elementor-pro/modules/screenshots/module.php(264): ElementorPro\Modules\Screenshots\Module->is_screenshot_proxy_mode()
#1 ../plugins/elementor/core/base/module.php(85): ElementorPro\Modules\Screenshots\Module->__construct()
#2 ../plugins/elementor-pro/core/modules-manager.php(98): Elementor\Core\Base\Module::instance()
#3 ../plugins/elementor-pro/plugin.php(366): ElementorPro\Core\Modules_Manager->__construct()
#4 /home/jamie/projects/example.local.test/web/wp/wp-includes/class-wp-hook.php(324): ElementorPro\Plugin->on_elementor_init()
#5 /home/jamie/projects/example.local.test/web/wp/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#6 /home/jamie/projects/example.local.test/web/wp/wp-includes/plugin.php(517): WP_Hook->do_action()
#7 ../plugins/elementor/includes/plugin.php(685): do_action()
#8 /home/jamie/projects/example.local.test/web/wp/wp-includes/class-wp-hook.php(324): Elementor\Plugin->init()
#9 /home/jamie/projects/example.local.test/web/wp/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#10 /home/jamie/projects/example.local.test/web/wp/wp-includes/plugin.php(517): WP_Hook->do_action()
#11 /home/jamie/projects/example.local.test/web/wp/wp-settings.php(700): do_action()
#12 /home/jamie/projects/example.local.test/web/wp-config.php(9): require_once('...')
#13 /home/jamie/projects/example.local.test/web/wp/wp-load.php(55): require_once('...')
#14 /home/jamie/projects/example.local.test/web/wp/wp-blog-header.php(13): require_once('...')
#15 /home/jamie/projects/example.local.test/web/index.php(6): require('...')
#16 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-11-05 13:28:11 [warning X 1][../plugins/elementor-pro/modules/posts/skins/skin-content-base.php::271] Attempt to read property "ID" on null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hey @jamieburchell!

Thank you for reporting this issue! 🙏 

We are going to investigate it.

Kind regards

**Comment by jamieburchell** [comment]
@nicholaszein If you set the alignment for only the desktop breakpoint and don't change it for any other, the alignment choice is respected on iOS Chrome/Safari
