### ISSUE TITLE
⛔ 🛟 Support Request: Updating WordPress without clearing the cache prevents page styles from loading

### ISSUE THREAD

**Issue by PukingUnicorn** [elementor/elementor#29289]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Hi,
Following the lastest WP update, I can't have a working homepage with elementor: white page or broken menu on a white background + some rows just aren't there:
![image](https://github.com/user-attachments/assets/1fa995cc-52d2-4efb-bc7b-7facc39f19cd)
				

I went back to WP 6.6.2 for now as I didn't succeeded having a working homepage with 6.7.
NB: the website is REALLY slow when under 6.7 to the point I have error 500 and database error messages on the back office with this version on.
I contacted my host but they don't see any issue on their side.

### Steps to reproduce

Updating to Wordpress 6.7

### Expected behavior

The website is suddenly slow with error 500
Database error display when trying to update plugins under WP 6.7
Homepage design "broken" but some pages work for some reasons

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server - GPL v8.0.35
	PHP Version: 8.2.21
	PHP Memory Limit: 512M
	PHP Max Input Vars: 16000
	PHP Max Post Size: 130M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.6.2
	Site URL: https://europe-cloture.com
	Home URL: https://europe-cloture.com
	WP Multisite: No
	Max Upload Size: 128 Mo
	Memory limit: 500M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: fr_FR
	Timezone: Europe/Paris
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 3.1.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: fr-FR
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36

== Active Plugins ==
	Complianz Privacy Suite (GDPR/CCPA) premium
		Version: 7.3.0
		Author: Really Simple Plugins

	Elementor
		Version: 3.25.6
		Author: Elementor.com

	Elementor Pro
		Version: 3.25.3
		Author: Elementor.com

	PayPlug pour WooCommerce (Officiel)
		Version: 2.10.1
		Author: PayPlug

	WooCommerce
		Version: 9.4.1
		Author: Automattic

	WooCommerce Measurement Price Calculator
		Version: 3.23.6
		Author: SkyVerge

	WP Consent API
		Version: 1.0.7
		Author: RogierLankhorst

	WPC Variation Swatches for WooCommerce
		Version: 4.2.1
		Author: WPClever

	WP Downgrade | Specific Core Version
		Version: 1.2.6
		Author: Reisetiger

	WP Mail SMTP
		Version: 4.2.0
		Author: WP Mail SMTP


== Must-Use Plugins ==
	Health Check Troubleshooting Mode
		Version: 1.9.2
		Author: 


== Utilisation des éléments ==
	
	archive : 1
		archive-posts : 1
		button : 1
		container : 4
		heading : 2
		image-gallery : 1
		social-icons : 1
		text-editor : 2
	container : 2
		container : 4
		heading : 1
		text-editor : 5
	footer : 1
		button : 1
		container : 4
		icon-box : 5
		image : 1
		nav-menu : 1
		social-icons : 1
		text-editor : 1
	header : 1
		container : 14
		icon-box : 1
		image-box : 6
		mega-menu : 1
		nav-menu : 1
		search : 1
		text-editor : 1
		theme-site-logo : 1
		woocommerce-menu-cart : 1
	product : 5
		button : 1
		container : 57
		divider : 5
		heading : 14
		icon-box : 20
		image : 2
		posts : 5
		text-editor : 4
		woocommerce-breadcrumb : 5
		woocommerce-product-add-to-cart : 5
		woocommerce-product-additional-information : 5
		woocommerce-product-content : 5
		woocommerce-product-images : 5
		woocommerce-product-short-description : 5
		woocommerce-product-title : 5
		woocommerce-product-upsell : 5
	wp-post : 6
		button : 4
		container : 47
		divider : 1
		form : 1
		gallery : 1
		heading : 22
		image : 1
		image-box : 10
		text-editor : 32
		woocommerce-products : 2
	wp-page : 15
		button : 9
		container : 52
		divider : 1
		form : 1
		gallery : 1
		heading : 19
		html : 1
		icon-box : 12
		image : 6
		image-box : 3
		reviews : 1
		slides : 2
		text-editor : 21
		wc-elements : 1
		woocommerce-cart : 1
		woocommerce-checkout-page : 1
		woocommerce-products : 2
	single-post : 1
		container : 1
		text-editor : 1
		theme-post-content : 1
		theme-post-featured-image : 1
		theme-post-title : 1
	search-results : 1
		archive-posts : 1
		container : 2
		divider : 1
		heading : 1
		search : 1
		text-editor : 1
	product-archive : 1
		button : 1
		container : 6
		heading : 3
		icon-box : 4
		posts : 1
		search : 1
		text-editor : 1
		theme-archive-title : 1
		wc-archive-products : 1
		woocommerce-breadcrumb : 1


== Réglages ==
	
	cpt_support: post, page, product
	allow_tracking: yes
	editor_break_lines: 1
	unfiltered_files_upload: 1
	font_display: swap
	disabled_elements: audio


== Fonctionnalités ==
	Custom Fonts: 0
	Custom Icons: 1

== Intégrations ==
	
	recaptcha: Actif
	recaptcha_v3: Actif
	woocommerce: Actif


== Expériences d’Elementor ==
	Optimisation du chargement du CSS: Inactif par défaut
	Polices d’icônes « inline »: Actif par défaut
	Points d’arrêt personnalisés supplémentaires: Actif par défaut
	Conteneur: Actif
	Mettre à niveau la bibliothèque Swiper: Actif par défaut
	Performances des éléments imbriqués: Actif par défaut
	Chargement optimisé des contrôles: Actif par défaut
	Balisage optimisé: Inactif par défaut
	Conditionally load Swiper CSS files: Inactif par défaut
	Intégration d’extension: Actif par défaut
	CSS Smooth Scroll: Actif par défaut
	Par défaut vers le Nouveau constructeur de thème: Actif par défaut
	En-tête & pied de page: Actif par défaut
	Écran d’accueil Elementor: Actif par défaut
	Page d’atterrissage: Inactif par défaut
	Éléments imbriqués: Actif
	Barre supérieure de l’éditeur: Actif par défaut
	Panneau des pages: Inactif par défaut
	Mise en cache d’éléments: Actif par défaut
	Lien en bio: Actif par défaut
	Boutons flottants: Actif par défaut
	Évènements de l’éditeur Elementor: Inactif par défaut
	Atomic Widgets: Inactif par défaut
	Launchpad Checklist: Inactif par défaut
	Menu: Actif


== Journal ==
	
Log: showing 20 of 372024-11-04 17:11:45 [info] elementor-pro::elementor_pro_updater Started 
2024-11-04 17:11:45 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-11-04 17:11:45 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-11-04 17:11:45 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.25.0',
  'to' => '3.25.2',
)]
2024-11-04 17:11:45 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.25.0',
  'to' => '3.25.2',
)]
2024-11-04 17:11:45 [info] elementor::elementor_updater Started 
2024-11-04 17:11:45 [info] Elementor/Upgrades - _on_each_version Start  
2024-11-04 17:11:46 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.25.0',
  'to' => '3.25.2',
)]
2024-11-04 17:11:48 [info] Elementor/Upgrades - _on_each_version Finished 
2024-11-04 17:11:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.25.1',
  'to' => '3.25.4',
)]
2024-11-13 17:50:59 [info] elementor::elementor_updater Started 
2024-11-13 17:50:59 [info] Elementor/Upgrades - _on_each_version Start  
2024-11-13 17:50:59 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.25.4',
  'to' => '3.25.6',
)]
2024-11-13 17:51:00 [info] Elementor/Upgrades - _on_each_version Finished 
2024-11-13 17:51:00 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.25.4',
  'to' => '3.25.6',
)]
2024-11-13 17:51:26 [info] elementor-pro::elementor_pro_updater Started 
2024-11-13 17:51:26 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-11-13 17:51:26 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-11-13 17:51:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.25.2',
  'to' => '3.25.3',
)]
2024-11-13 17:51:28 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.25.2',
  'to' => '3.25.3',
)]

PHP: showing 5 of 5PHP: 2024-10-11 19:51:27 [error X 54][../plugins/elementor-pro/modules/woocommerce/widgets/cart.php::2647] Uncaught Error: Call to a member function get_cart_contents_count() on null in ../plugins/elementor-pro/modules/woocommerce/widgets/cart.php:2647
Stack trace:
#0 ../plugins/elementor/includes/base/controls-stack.php(2325): ElementorPro\Modules\Woocommerce\Widgets\Cart->render()
#1 ../plugins/elementor/includes/base/widget-base.php(635): Elementor\Controls_Stack->render_by_mode()
#2 ../plugins/elementor/includes/base/widget-base.php(776): Elementor\Widget_Base->render_content()
#3 ../plugins/elementor/includes/base/element-base.php(483): Elementor\Widget_Base->print_content()
#4 ../plugins/elementor/modules/element-cache/module.php(73): Elementor\Element_Base->print_element()
#5 ../wp-includes/shortcodes.php(434): Elementor\Modules\ElementCache\Module->Elementor\Modules\ElementCache\{closure}(Array, '', 'elementor-eleme...')
#6 [internal function]: do_shortcode_tag(Array)
#7 ../wp-includes/shortcodes.php(273): preg_replace_callback('/\\[(\\[?)(elemen...', 'do_shortcode_ta...', '<div class="ele...')
#8 ../plugins/elementor/core/base/document.php(1856): do_shortcode('<div class="ele...')
#9 ../plugins/elementor/core/base/document.php(1201): Elementor\Core\Base\Document->print_elements(Array)
#10 ../plugins/elementor/includes/frontend.php(1207): Elementor\Core\Base\Document->print_elements_with_wrapper(Array)
#11 ../plugins/elementor/includes/frontend.php(1102): Elementor\Frontend->get_builder_content(13)
#12 ../wp-includes/class-wp-hook.php(324): Elementor\Frontend->apply_builder_in_content('<link rel="styl...')
#13 ../wp-includes/plugin.php(205): WP_Hook->apply_filters('<link rel="styl...', Array)
#14 ../wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php(1871): apply_filters('the_content', '<link rel="styl...')
#15 ../wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php(575): WP_REST_Posts_Controller->prepare_item_for_response(Object(WP_Post), Object(WP_REST_Request))
#16 ../wp-includes/rest-api/class-wp-rest-server.php(1230): WP_REST_Posts_Controller->get_item(Object(WP_REST_Request))
#17 ../wp-includes/rest-api/class-wp-rest-server.php(1063): WP_REST_Server->respond_to_request(Object(WP_REST_Request), '/wp/v2/pages/(?...', Array, NULL)
#18 ../wp-includes/rest-api/class-wp-rest-server.php(439): WP_REST_Server->dispatch(Object(WP_REST_Request))
#19 ../wp-includes/rest-api.php(420): WP_REST_Server->serve_request('/wp/v2/pages/13')
#20 ../wp-includes/class-wp-hook.php(324): rest_api_loaded(Object(WP))
#21 ../wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#22 ../wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#23 ../wp-includes/class-wp.php(418): do_action_ref_array('parse_request', Array)
#24 ../wp-includes/class-wp.php(813): WP->parse_request('')
#25 ../wp-includes/functions.php(1336): WP->main('')
#26 ../wp-blog-header.php(16): wp()
#27 ../index.php(17): require('/home/sudxpnc/w...')
#28 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-10-29 14:54:57 [notice X 15][../plugins/elementor/includes/base/controls-stack.php::229] hexdec(): Passing null to parameter #1 ($hex_string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-11-13 16:46:52 [error X 6][../plugins/elementor-pro/vendor_prefixed/php-di/php-di/src/ContainerBuilder.php::119] Uncaught Error: Class "ElementorProDeps\DI\Definition\Source\ReflectionBasedAutowiring" not found in ../plugins/elementor-pro/vendor_prefixed/php-di/php-di/src/ContainerBuilder.php:119
Stack trace:
#0 ../plugins/elementor-pro/core/container/container.php(38): ElementorProDeps\DI\ContainerBuilder->build()
#1 ../plugins/elementor-pro/core/container/container.php(50): ElementorPro\Core\Container\Container::initialize()
#2 ../plugins/elementor-pro/plugin.php(151): ElementorPro\Core\Container\Container::get_instance()
#3 ../plugins/elementor-pro/plugin.php(553): ElementorPro\Plugin::instance()
#4 ../plugins/elementor-pro/elementor-pro.php(76): require('/home/sudxpnc/w...')
#5 ../wp-includes/class-wp-hook.php(324): elementor_pro_load_plugin('')
#6 ../wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#7 ../wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#8 ../wp-settings.php(555): do_action('plugins_loaded')
#9 ../wp-config.php(119): require_once('/home/sudxpnc/w...')
#10 ../wp-load.php(50): require_once('/home/sudxpnc/w...')
#11 ../wp-blog-header.php(13): require_once('/home/sudxpnc/w...')
#12 ../index.php(17): require('/home/sudxpnc/w...')
#13 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-11-13 16:46:53 [error X 1][../plugins/elementor-pro/vendor_prefixed/php-di/php-di/src/ContainerBuilder.php::119] Uncaught Error: Class "ElementorProDeps\DI\Definition\Source\ReflectionBasedAutowiring" not found in ../plugins/elementor-pro/vendor_prefixed/php-di/php-di/src/ContainerBuilder.php:119
Stack trace:
#0 ../plugins/elementor-pro/core/container/container.php(38): ElementorProDeps\DI\ContainerBuilder->build()
#1 ../plugins/elementor-pro/core/container/container.php(50): ElementorPro\Core\Container\Container::initialize()
#2 ../plugins/elementor-pro/plugin.php(151): ElementorPro\Core\Container\Container::get_instance()
#3 ../plugins/elementor-pro/plugin.php(553): ElementorPro\Plugin::instance()
#4 ../plugins/elementor-pro/elementor-pro.php(76): require('/home/sudxpnc/w...')
#5 ../wp-includes/class-wp-hook.php(324): elementor_pro_load_plugin('')
#6 ../wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#7 ../wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#8 ../wp-settings.php(555): do_action('plugins_loaded')
#9 ../wp-config.php(119): require_once('/home/sudxpnc/w...')
#10 ../wp-load.php(50): require_once('/home/sudxpnc/w...')
#11 ../wp-admin/admin-ajax.php(22): require_once('/home/sudxpnc/w...')
#12 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-11-13 17:49:07 [notice X 2][../plugins/elementor-pro/modules/screenshots/module.php::33] Function utf8_decode() is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==
````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hello @PukingUnicorn,

Thanks for contacting us! 🙏 

### 🛟 This is more of a support question, not really something we can help with here. 

You should **<ins>always</ins>** clear, purge, and flush all levels of cache after any update, including WordPress, plugins, and themes. 

👉 Please remember to check the [Help Center](https://elementor.com/help) or contact [Elementor Support](https://elementor.com/contact) before submitting an issue.

Here's an article that covers this issue:
https://elementor.com/help/site-update-troubleshooting/

### ⚠️ Note that GitHub issues are reserved for validated Elementor 🐞 Bug Reports only, and should not be used for personal support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

### ⚠️ As a gentle reminder, **🛟 Support Request issues** may need to be closed without troubleshooting. 
Remember to always follow our **[🐞 Bug Report Guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&projects=&template=bug.yml)** to save time and ensure smooth troubleshooting.

Thank you for understanding! 🙏 

Kind regards
