### ISSUE TITLE
Taxonomy Filter [tags] not working when having articles with both: categories and tags

### ISSUE THREAD

**Issue by pharni99** [elementor/elementor#29298]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

The taxonomy filter fails to work when categories are added to articles. Initially, filtering by tags alone worked as expected, but once categories were introduced to articles in the WordPress backend, the filter stopped functioning properly. The expected outcome is for the filter to apply both tags and categories seamlessly, but currently, it breaks when categories are included. It behaves like there would no function linked to the button at all, except for the different filter-URL.
Example: https://annikaner-unterwegs.de/alle-artikel-von-a-z/

### Steps to reproduce

1. create loop grid
2. add taxonomy filters
3. add tags to the articles and set up tag filtering in taxonomy filters
4. filter the articles (still working) 
5. now add categories to the already existing articles
6. include only articles with a certain category term 
7. try the filters: not working anymore

### Expected behavior

1. create loop grid
2. add taxonomy filters
3. add tags to the articles and set up tag filtering in taxonomy filters
4. filter the articles (still working) 
5. now add categories to the already existing articles
6. include only articles with a certain category term 
**7. try the filters: should be working**

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.62 (Unix)
	MySQL version: MariaDB Server v10.11.7-MariaDB-log
	PHP Version: 8.1.30
	PHP Memory Limit: 512M
	PHP Max Input Vars: 4000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.7
	Site URL: http://test.saxa-media.com
	Home URL: http://test.saxa-media.com
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%category%/%postname%/
	Language: de_DE
	Timezone: 0
	Admin Email: saxamedia.gbr@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 3.1.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: de
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36

== Active Plugins ==
	Admin and Site Enhancements (ASE)
		Version: 7.5.2
		Author: wpase.com

	Elementor
		Version: 3.25.6
		Author: Elementor.com

	Elementor Pro
		Version: 3.25.3
		Author: Elementor.com

	Event Tickets
		Version: 5.16.1
		Author: The Events Calendar

	Limit Login Attempts Reloaded
		Version: 2.26.16
		Author: Limit Login Attempts Reloaded

	Site Kit by Google
		Version: 1.139.0
		Author: Google

	Strato Assistant
		Version: 7.3.0
		Author: Strato

	The Events Calendar
		Version: 6.8.1
		Author: The Events Calendar

	WP Encryption - One Click SSL & Force HTTPS
		Version: 7.7.0
		Author: WP Encryption SSL HTTPS

	WPForms Lite
		Version: 1.9.2.1
		Author: WPForms


== Must-Use Plugins ==
	WordPress automation by Installatron
		Version: 
		Author: 

	WordPressSecureMode.php
		Version: 
		Author: 


== Elemente Verwendung ==
	
	container : 0
		button : 3
		container : 25
		google_maps : 1
		heading : 10
		icon-list : 4
		image : 1
		image-box : 2
		social-icons : 2
		tec_events_elementor_widget_event_calendar_link : 2
		tec_events_elementor_widget_event_categories : 2
		tec_events_elementor_widget_event_cost : 2
		tec_events_elementor_widget_event_datetime : 2
		tec_events_elementor_widget_event_export : 2
		tec_events_elementor_widget_event_image : 2
		tec_events_elementor_widget_event_navigation : 2
		tec_events_elementor_widget_event_organizer : 2
		tec_events_elementor_widget_event_status : 2
		tec_events_elementor_widget_event_tags : 2
		tec_events_elementor_widget_event_title : 2
		tec_events_elementor_widget_event_venue : 2
		tec_events_elementor_widget_event_website : 2
		text-editor : 2
	wp-page : 9
		button : 10
		container : 89
		divider : 5
		google_maps : 1
		heading : 37
		icon : 2
		icon-box : 14
		icon-list : 3
		image : 16
		image-box : 27
		loop-grid : 1
		taxonomy-filter : 1
		testimonial : 9
		text-editor : 17
	loop-item : 1
		container : 1
		theme-post-content : 1
		theme-post-featured-image : 1
		theme-post-title : 1


== Einstellungen ==
	
	cpt_support: post, page
	allow_tracking: yes
	font_display: swap


== Eigenschaften ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor-Experimente ==
	Verbessertes Laden von CSS: Standardmäßig deaktiviert
	Inline-Schriftarten-Symbole: Standardmäßig aktiviert
	Additional Custom Breakpoints: Standardmäßig aktiviert
	Container: Standardmäßig aktiviert
	Upgrade Swiper Library: Standardmäßig aktiviert
	Nested Elements Performance: Standardmäßig aktiviert
	Optimized Control Loading: Standardmäßig aktiviert
	Optimized Markup: Standardmäßig deaktiviert
	Conditionally load Swiper CSS files: Standardmäßig deaktiviert
	Plugin Onboarding: Standardmäßig aktiviert
	CSS Smooth Scroll: Standardmäßig aktiviert
	Default to New Theme Builder: Standardmäßig aktiviert
	Header und Footer: Standardmäßig aktiviert
	Elementor Home Screen: Standardmäßig aktiviert
	Startseiten: Standardmäßig deaktiviert
	Nested Elements: Standardmäßig aktiviert
	Editor Top Bar: Standardmäßig aktiviert
	Seiten Panel: Standardmäßig deaktiviert
	Element Caching: Standardmäßig aktiviert
	Link In Bio: Standardmäßig aktiviert
	Floating Buttons: Standardmäßig aktiviert
	Elementor Editor Events: Standardmäßig deaktiviert
	Atomic Widgets: Standardmäßig deaktiviert
	Launchpad Checklist: Standardmäßig deaktiviert
	Menü: Standardmäßig deaktiviert


== Protokoll ==
	
Log: showing 20 of 282024-08-17 12:53:52 [info] Import runner completed: elementor-content ✓ 
2024-08-17 12:53:54 [info] Import runner completed: wp-content ✓ 
2024-11-07 09:11:46 [info] elementor-pro::elementor_pro_updater Started 
2024-11-07 09:11:47 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-11-07 09:11:47 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-11-07 09:11:47 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.22.1',
  'to' => '3.25.2',
)]
2024-11-07 09:11:53 [info] elementor::elementor_updater Started 
2024-11-07 09:11:53 [info] Elementor/Upgrades - _on_each_version Start  
2024-11-07 09:11:53 [info] Elementor/Upgrades - _on_each_version Finished 
2024-11-07 09:11:53 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.3',
  'to' => '3.25.4',
)]
2024-11-13 06:59:36 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.25.4',
  'to' => '3.25.5',
)]
2024-11-14 21:20:28 [info] elementor::elementor_updater Started 
2024-11-14 21:20:29 [info] Elementor/Upgrades - _on_each_version Start  
2024-11-14 21:20:29 [info] Elementor/Upgrades - _on_each_version Finished 
2024-11-14 21:20:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.25.4',
  'to' => '3.25.6',
)]
2024-11-14 21:34:26 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.25.2',
  'to' => '3.25.3',
)]
2024-11-14 21:34:27 [info] elementor-pro::elementor_pro_updater Started 
2024-11-14 21:34:27 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-11-14 21:34:27 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-11-14 21:34:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.25.2',
  'to' => '3.25.3',
)]

PHP: showing 7 of 7PHP: 2024-08-17 12:45:32 [warning X 8][/mnt/web415/d2/69/549505769/htdocs/STRATO-apps/wordpress_03/app/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::182] Undefined array key "editor_post_id" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-08-17 12:53:54 [notice X 1][/mnt/web415/d2/69/549505769/htdocs/STRATO-apps/wordpress_03/app/wp-content/plugins/elementor/core/utils/import-export/parsers/wxr-parser-simple-xml.php::53] Function libxml_disable_entity_loader() is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-08-17 12:53:59 [warning X 1][/mnt/web415/d2/69/549505769/htdocs/STRATO-apps/wordpress_03/app/wp-content/plugins/elementor-pro/modules/popup/tag.php::41] Undefined array key "" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-08-17 13:01:00 [warning X 4][/mnt/web415/d2/69/549505769/htdocs/STRATO-apps/wordpress_03/app/wp-content/plugins/elementor/includes/managers/image.php::113] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-08-18 21:49:06 [warning X 9][/mnt/web415/d2/69/549505769/htdocs/STRATO-apps/wordpress_03/app/wp-content/plugins/elementor/includes/conditions.php::87] Undefined array key "background_color" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-11-14 21:21:08 [error X 1][/mnt/web415/d2/69/549505769/htdocs/STRATO-apps/wordpress_03/app/wp-content/plugins/elementor-pro/plugin.php::503] Uncaught Error: Class "ElementorPro\Core\Compatibility\Compatibility" not found in /mnt/web415/d2/69/549505769/htdocs/STRATO-apps/wordpress_03/app/wp-content/plugins/elementor-pro/plugin.php:503
Stack trace:
#0 /mnt/web415/d2/69/549505769/htdocs/STRATO-apps/wordpress_03/app/wp-content/plugins/elementor-pro/plugin.php(150): ElementorPro\Plugin->__construct()
#1 /mnt/web415/d2/69/549505769/htdocs/STRATO-apps/wordpress_03/app/wp-content/plugins/elementor-pro/plugin.php(553): ElementorPro\Plugin::instance()
#2 /mnt/web415/d2/69/549505769/htdocs/STRATO-apps/wordpress_03/app/wp-content/plugins/elementor-pro/elementor-pro.php(76): require('...')
#3 /mnt/web415/d2/69/549505769/htdocs/STRATO-apps/wordpress_03/app/wp-includes/class-wp-hook.php(324): elementor_pro_load_plugin()
#4 /mnt/web415/d2/69/549505769/htdocs/STRATO-apps/wordpress_03/app/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#5 /mnt/web415/d2/69/549505769/htdocs/STRATO-apps/wordpress_03/app/wp-includes/plugin.php(517): WP_Hook->do_action()
#6 /mnt/web415/d2/69/549505769/htdocs/STRATO-apps/wordpress_03/app/wp-settings.php(559): do_action()
#7 /mnt/web415/d2/69/549505769/htdocs/STRATO-apps/wordpress_03/app/wp-config.php(102): require_once('...')
#8 /mnt/web415/d2/69/549505769/htdocs/STRATO-apps/wordpress_03/app/wp-load.php(50): require_once('...')
#9 /mnt/web415/d2/69/549505769/htdocs/STRATO-apps/wordpress_03/app/wp-blog-header.php(13): require_once('...')
#10 /mnt/web415/d2/69/549505769/htdocs/STRATO-apps/wordpress_03/app/index.php(17): require('...')
#11 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-11-14 21:32:55 [warning X 13][/mnt/web415/d2/69/549505769/htdocs/STRATO-apps/wordpress_03/app/wp-content/plugins/elementor-pro/modules/loop-filter/query/taxonomy-manager.php::150] Undefined array key "logicalJoin" [array (
  'trace' => '
#0: /mnt/web415/d2/69/549505769/htdocs/STRATO-apps/wordpress_03/app/wp-content/plugins/elementor-pro/modules/loop-filter/query/taxonomy-manager.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /mnt/web415/d2/69/549505769/htdocs/STRATO-apps/wordpress_03/app/wp-content/plugins/elementor-pro/modules/loop-filter/query/taxonomy-query-builder.php(33): ElementorPro\Modules\LoopFilter\Query\Taxonomy_Manager -> get_hierarchy_of_selected_terms()
#2: /mnt/web415/d2/69/549505769/htdocs/STRATO-apps/wordpress_03/app/wp-content/plugins/elementor-pro/modules/loop-filter/module.php(122): ElementorPro\Modules\LoopFilter\Query\Taxonomy_Query_Builder -> get_merged_queries()
#3: /mnt/web415/d2/69/549505769/htdocs/STRATO-apps/wordpress_03/app/wp-includes/class-wp-hook.php(324): ElementorPro\Modules\LoopFilter\Module -> filter_loop_query()
#4: /mnt/web415/d2/69/549505769/htdocs/STRATO-apps/wordpress_03/app/wp-includes/plugin.php(205): WP_Hook -> apply_filters()
',
)]

JS: showing 2 of 2JS: 2024-08-17 12:50:33 [error X 1][http://test.saxa-media.com/wp-admin/load-scripts.php?c=1&loadchunk_0=jquery-core,jquery-migrate,utils,moxiejs,plupload&ver=6.6.1:2:28767] undefined is not an object (evaluating 'c[0].value') 
JS: 2024-11-14 21:32:03 [error X 1][http://test.saxa-media.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.25.6:3:1274746] Cannot read properties of null (reading 'getBoundingClientRect') 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Kompatibel
	Event Tickets: Unkompatibel
	The Events Calendar: Unkompatibel

== Elementor Pro - Compatibility Tag ==
	
	Event Tickets: Unkompatibel
	The Events Calendar: Unkompatibel
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hi @pharni99!

Thank you for submitting your issue! 🙏 

Can you please elaborate a little more about what you are experiencing? Just to confirm:

1. Are you using the Loop Grid on a static page, or is it an Archive Template?
2. Do you have more than one Loop Grid on the same document also using a filter?
3. Do you have pagination turned on?
4. Can you take a screenshot of the settings of the Loop Grid (the Query section in the Content tab)?
5. Can you take a screenshot of the settings of the Taxonomy Filter (both the Layout and Settings sections of the Content tab)?

We want to be able to reproduce your issue accurately.

Kind regards

**Comment by aliciaburke** [comment]
I am experiencing the exact same bug - creating a taxonomy filter by tag does not work when you have include by category as the loop grod posts query, but does work with exclude by. I have at least used the exclude by as a placeholder to launch my client's site, thank you.

**Comment by INT-010** [comment]
I have run into a similar issue with taxonomies filtering by category as well.  On first page load, the initial taxonomy filter/button that shows "All" posts comes up with the nothing found message.  Clicking another category button in the taxonomy filter will load posts, but with missing css styles from the loop grid template. Rolling Elementor Pro back to 3.26.3 fixes the issues.  Any of the more recent versions of Pro recreate the issue.
