### ISSUE TITLE
⛔ 🧩 Issue when trying to use VIDEO widget with arraylist url

### ISSUE THREAD

**Issue by JokerSSSS** [elementor/elementor#29310]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Hello, 

I tried to appear multiple videos with acf repeater, the result was to crashing Elementor.

### Steps to reproduce

ACF repeater, dynamic content, and elementor, 
 
ACF Repeater to a post for example, ACF title, acf ACF FILE video,

Elementor builder > ACF Repeater > New Template (Section) > Title & Video widgets

### Expected behavior

I found if i replace this lines it would fix it.

```php
	private function get_hosted_video_url() {
		$settings = $this->get_settings_for_display();

		if ( ! empty( $settings['insert_url'] ) ) {
			$video_url = $settings['external_url']['url'];
		} else {
			$video_url = $settings['hosted_url']['url'];
		}

		if ( empty( $video_url ) ) {
			return '';
		}

		if ( $settings['start'] || $settings['end'] ) {
			$video_url .= '#t=';
		}

		if ( $settings['start'] ) {
			$video_url .= $settings['start'];
		}

		if ( $settings['end'] ) {
			$video_url .= ',' . $settings['end'];
		}

		return $video_url;
	}
```

TO 

```php
private function get_hosted_video_url() {
    $settings = $this->get_settings_for_display();

    $video_url = '';

    if ( ! empty( $settings['insert_url'] ) ) {
        // Check if 'external_url' is an array and has the 'url' key
        if ( isset( $settings['external_url']['url'] ) ) {
            $video_url = $settings['external_url']['url'];
        } elseif ( is_string( $settings['external_url'] ) ) {
            $video_url = $settings['external_url']; // Fallback if it's a string
        }
    } else {
        // Check if 'hosted_url' is an array and has the 'url' key
        if ( isset( $settings['hosted_url']['url'] ) ) {
            $video_url = $settings['hosted_url']['url'];
        } elseif ( is_string( $settings['hosted_url'] ) ) {
            $video_url = $settings['hosted_url']; // Fallback if it's a string
        }
    }

    if ( empty( $video_url ) ) {
        return '';
    }

    if ( ! empty( $settings['start'] ) || ! empty( $settings['end'] ) ) {
        $video_url .= '#t=';
    }

    if ( ! empty( $settings['start'] ) ) {
        $video_url .= $settings['start'];
    }

    if ( ! empty( $settings['end'] ) ) {
        $video_url .= ',' . $settings['end'];
    }

    return $video_url;
}
```

Error message: 

```txt
../wp-content/plugins/elementor/includes/widgets/video.php. Error message: Uncaught TypeError: Cannot access offset of type string on string in ../wp-content/plugins/elementor/includes/widgets/video.php:1344 Stack trace: #0 ../wp-content/plugins/elementor/includes/widgets/video.php(1014): Elementor\Widget_Video->get_hosted_video_url() #1 ../wp-content/plugins/elementor/includes/base/controls-stack.php(2325): Elementor\Widget_Video->render() #2 ../wp-content/plugins/elementor/includes/base/widget-base.php(635): Elementor\Controls_Stack->render_by_mode() #3 ../wp-content/plugins/elementor/core/base/document.php(387): Elementor\Widget_Base->render_content() #4 ../wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(447): Elementor\Core\Base\Document->render_element() #5 ../wp-content/plugins/elementor/includes/managers/widgets.php(461): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document->render_element() #6 [internal function]: Elementor\Widgets_Manager->ajax_render_widget() #7 ../wp-content/plugins/elementor/core/common/modules/ajax/module.php(176): call_user_func() #8 ../wp-includes/class-wp-hook.php(324): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request() #9 ../wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters() #10 ../wp-includes/plugin.php(517): WP_Hook->do_action() #11 ../wp-admin/admin-ajax.php(192): do_action() #12 {main} thrown
```

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt


== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v11.4.4-MariaDB-log
	PHP Version: 8.3.13
	PHP Memory Limit: 1024M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 2048M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.7
	Site URL: https://login.test.com
	Home URL: https://login.test.com
	WP Multisite: No
	Max Upload Size: 2 GB
	Memory limit: 40M
	Max Memory limit: 1024M
	Permalink Structure: /%category%/%postname%/
	Language: el
	Timezone: Europe/Athens
	Debug Mode: Inactive

== Theme ==
	Name: 
	Version: 1.0.0
	Author: 
	Child Theme: Yes
	Parent Theme Name: Astra
	Parent Theme Version: 4.8.3
	Parent Theme Author: Brainstorm Force

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 6.3.6
		Author: WP Engine

	Classic Editor
		Version: 1.6.5
		Author: WordPress Contributors

	Custom Post Type UI
		Version: 1.17.1
		Author: WebDevStudios

	Disable All WordPress Updates
		Version: 1.7.1
		Author: Oliver Schlöbe

	Dynamic.ooo - Dynamic Content for Elementor
		Version: 3.1.2
		Author: Dynamic.ooo

	Dynamic.ooo - Dynamic Shortcodes
		Version: 1.5.8
		Author: Dynamic.ooo

	Elementor
		Version: 3.25.6
		Author: Elementor.com


== Elements Usage ==
	
	footer : 1
		container : 4
		google_maps : 1
		heading : 2
		icon-list : 1
		text-editor : 1
		theme-site-logo : 1
	header : 1
		container : 3
		nav-menu : 1
		theme-site-logo : 1
	page : 1
		container : 1
		heading : 1
	section : 5
		container : 8
		dce-acf-repeater-v2 : 1
		divider : 1
		dyncontel-acf : 1
		dyncontel-acfgallery : 1
		form : 1
		heading : 6
		video : 4
	wp-page : 5
		container : 9
		dce-dynamicposts-v2 : 2
		heading : 7
		shortcode : 5
		theme-site-logo : 3


== Settings ==
	
	cpt_support: post, page
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	
	recaptcha_v3: Active


== Elementor Experiments ==
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Active by default
	Additional Custom Breakpoints: Active by default
	Container: Active by default
	Upgrade Swiper Library: Active by default
	Nested Elements Performance: Active by default
	Optimized Control Loading: Active by default
	Optimized Markup: Inactive by default
	Conditionally load Swiper CSS files: Inactive by default
	Plugin Onboarding: Active by default
	CSS Smooth Scroll: Active by default
	Default to New Theme Builder: Active by default
	Elementor Home Screen: Active by default
	Landing Pages: Inactive by default
	Nested Elements: Active by default
	Editor Top Bar: Active by default
	Pages Panel: Inactive by default
	Element Caching: Active by default
	Link In Bio: Active by default
	Floating Buttons: Active by default
	Elementor Editor Events: Inactive by default
	Atomic Widgets: Inactive by default
	Launchpad Checklist: Inactive by default
	Menu: Inactive by default


== Log ==
	
PHP: 2024-11-18 02:19:16 [error X 2][../wp-content/plugins/elementor/includes/widgets/video.php::1344] Uncaught TypeError: Cannot access offset of type string on string in ../wp-content/plugins/elementor/includes/widgets/video.php:1344
Stack trace:
#0 ../wp-content/plugins/elementor/includes/widgets/video.php(1014): Elementor\Widget_Video->get_hosted_video_url()
#1 ../wp-content/plugins/elementor/includes/base/controls-stack.php(2325): Elementor\Widget_Video->render()
#2 ../wp-content/plugins/elementor/includes/base/widget-base.php(635): Elementor\Controls_Stack->render_by_mode()
#3 ../wp-content/plugins/elementor/includes/base/widget-base.php(759): Elementor\Widget_Base->render_content()
#4 ../wp-content/plugins/elementor/includes/base/element-base.php(618): Elementor\Widget_Base->get_raw_data()
#5 ../wp-content/plugins/elementor/core/base/document.php(1084): Elementor\Element_Base->get_raw_data()
#6 ../wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(435): Elementor\Core\Base\Document->get_elements_raw_data()
#7 ../wp-content/plugins/elementor/core/base/document.php(737): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document->get_elements_raw_data()
#8 ../wp-content/plugins/elementor/modules/library/documents/library-document.php(66): Elementor\Core\Base\Document->get_initial_config()
#9 ../wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(659): Elementor\Modules\Library\Documents\Library_Document->get_initial_config()
#10 ../wp-content/plugins/elementor/includes/base/controls-stack.php(1070): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document->get_initial_config()
#11 ../wp-content/plugins/elementor/core/editor/loader/common/editor-common-scripts-settings.php(38): Elementor\Controls_Stack->get_config()
#12 ../wp-content/plugins/elementor/core/editor/loader/v2/editor-v2-loader.php(145): Elementor\Core\Editor\Loader\Common\Editor_Common_Scripts_Settings::get()
#13 ../wp-content/plugins/elementor/core/editor/editor.php(364): Elementor\Core\Editor\Loader\V2\Editor_V2_Loader->enqueue_scripts()
#14 ../wp-includes/class-wp-hook.php(324): Elementor\Core\Editor\Editor->enqueue_scripts()
#15 ../wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#16 ../wp-includes/plugin.php(517): WP_Hook->do_action()
#17 ../wp-includes/script-loader.php(2272): do_action()
#18 ../wp-includes/class-wp-hook.php(324): wp_enqueue_scripts()
#19 ../wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#20 ../wp-includes/plugin.php(517): WP_Hook->do_action()
#21 ../wp-includes/general-template.php(3064): do_action()
#22 ../wp-content/plugins/elementor/includes/editor-templates/editor-wrapper.php(31): wp_head()
#23 ../wp-content/plugins/elementor/core/editor/loader/v2/editor-v2-loader.php(195): include('...')
#24 ../wp-content/plugins/elementor/core/editor/editor.php(169): Elementor\Core\Editor\Loader\V2\Editor_V2_Loader->print_root_template()
#25 ../wp-includes/class-wp-hook.php(324): Elementor\Core\Editor\Editor->init()
#26 ../wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#27 ../wp-includes/plugin.php(517): WP_Hook->do_action()
#28 ../wp-admin/admin.php(419): do_action()
#29 ../wp-admin/post.php(12): require_once('...')
#30 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

````

</details>

### Agreement

- [x] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hi, @JokerSSSS,

Thank you for reaching out! 🙏 

### ⛔ After reviewing your report we concluded this is not a bug caused by Elementor. The feature you're referring to is not yet supported.

Elementor does not support ACF Repeater fields. Please refer to the article below to learn which fields are supported:
https://elementor.com/help/elementor-acf/

If you think this should be an Elementor feature, please join the conversation in #5979  and we will consider it in the future if there is enough demand (votes) from other users.

Kind regards
