### ISSUE TITLE
🐞 Widget Display Conditions causes FATAL ERROR when using Dynamic Tags that is an Array-type

### ISSUE THREAD

**Issue by toineenzo** [elementor/elementor#29347]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

When setting up a dynamic condition to a widget, it will cause a fatal error on the post/page when the used dynamic tag outputs in an array type. It seems that due to the check_string_contains_and_empty() function inside ElementorPro\Modules\DisplayConditions\Classes\Comparators_Checker, only string-types will work.

### Steps to reproduce

1. Create an ACF field group with a field type that allows to select multiple values, like the Select field, and add multiple values to it. It doesn't matter what you choose at Return Format (Label, Value, Both(Array) or enabled 'Allow null'.
2. Link the ACF field group to any posts/pages/custom post types
3. Create a post/page and select multiple values inside the ACF field you just created and save the post/page
4. Edit the post/page or create a post/page template inside Elementor. Drag-in multiple elements you want to hide/show. 
5. Set-up each element with a display condition > dynamic tags > choose the dynamic tag, that's part of the ACF field you just created
6. Click save/publish inside Elementor and go to the post/page
7. You will always get a fatal error due to the dynamic tag/value being an array-type and not a string-type

**Please see the following video where I demonstrate this bug:**
https://github.com/user-attachments/assets/8a2060f6-8d36-4f14-9b1f-e7dbaa226e9b

**Error log:**
`Fatal error: Uncaught Error: ElementorPro\Modules\DisplayConditions\Classes\Comparators_Checker::check_string_contains_and_empty(): Argument #3 ($actual_value) must be of type string, array given, called in /home/u52543p64574/domains/toine.zip/dev/wp-content/plugins/elementor-pro/modules/display-conditions/conditions/dynamic-tags-condition.php on line 54
in /home/u52543p64574/domains/toine.zip/dev/wp-content/plugins/elementor-pro/modules/display-conditions/classes/comparators-checker.php on line 76

Call stack:

    ElementorPro\M\D\C\Comparators_Checker::check_string_contains_and_empty()
    wp-content/plugins/elementor-pro/modules/display-conditions/conditions/dynamic-tags-condition.php:54
    ElementorPro\M\D\C\Dynamic_Tags_Condition::check()
    wp-content/plugins/elementor-pro/modules/display-conditions/classes/and-condition.php:38
    ElementorPro\M\D\C\And_Condition::is_condition_passing_check()
    wp-content/plugins/elementor-pro/modules/display-conditions/classes/and-condition.php:24
    ElementorPro\M\D\C\And_Condition::check()
    wp-content/plugins/elementor-pro/modules/display-conditions/classes/or-condition.php:27
    ElementorPro\M\D\C\Or_Condition::check()
    wp-content/plugins/elementor-pro/modules/display-conditions/module.php:183
    ElementorPro\M\D\Module::before_element_render()
    wp-includes/class-wp-hook.php:324
    WP_Hook::apply_filters()
    wp-includes/class-wp-hook.php:348
    WP_Hook::do_action()
    wp-includes/plugin.php:517
    do_action()
    wp-content/plugins/elementor/includes/base/element-base.php:474
    Elementor\Element_Base::print_element()
    wp-content/plugins/elementor/modules/element-cache/module.php:73
    Elementor\M\E\Module::Elementor\M\E\{closure}()
    wp-includes/shortcodes.php:434
    do_shortcode_tag()
    preg_replace_callback()
    wp-includes/shortcodes.php:273
    do_shortcode()
    wp-content/plugins/elementor/core/base/document.php:1855
    Elementor\C\B\Document::print_elements()
    wp-content/plugins/elementor/core/base/document.php:1200
    Elementor\C\B\Document::print_elements_with_wrapper()
    wp-content/plugins/elementor/includes/frontend.php:1190
    Elementor\Frontend::get_builder_content()
    wp-content/plugins/elementor-pro/modules/posts/skins/skin-content-base.php:271
    ElementorPro\M\T\W\Post_Content::render_post_content()
    wp-content/plugins/elementor-pro/modules/theme-builder/widgets/post-content.php:111
    ElementorPro\M\T\W\Post_Content::render()
    wp-content/plugins/elementor/includes/base/controls-stack.php:2325
    Elementor\Controls_Stack::render_by_mode()
    wp-content/plugins/elementor/includes/base/widget-base.php:635
    Elementor\Widget_Base::render_content()
    wp-content/plugins/elementor/includes/base/widget-base.php:776
    Elementor\Widget_Base::print_content()
    wp-content/plugins/elementor/includes/base/element-base.php:483
    Elementor\Element_Base::print_element()
    wp-content/plugins/elementor/modules/element-cache/module.php:73
    Elementor\M\E\Module::Elementor\M\E\{closure}()
    wp-includes/shortcodes.php:434
    do_shortcode_tag()
    preg_replace_callback()
    wp-includes/shortcodes.php:273
    do_shortcode()
    wp-content/plugins/elementor/core/base/document.php:1855
    Elementor\C\B\Document::print_elements()
    wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php:412
    ElementorPro\M\T\D\Theme_Document::print_elements_with_wrapper()
    wp-content/plugins/elementor/includes/frontend.php:1190
    Elementor\Frontend::get_builder_content()
    wp-content/plugins/elementor/core/base/document.php:1248
    Elementor\C\B\Document::get_content()
    wp-content/plugins/elementor/modules/library/documents/library-document.php:76
    Elementor\M\L\D\Library_Document::get_content()
    wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php:158
    ElementorPro\M\T\D\Theme_Document::get_content()
    wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php:173
    ElementorPro\M\T\D\Theme_Document::print_content()
    wp-content/plugins/elementor-pro/modules/theme-builder/documents/single-base.php:100
    ElementorPro\M\T\D\Single_Base::print_content()
    wp-content/plugins/elementor-pro/modules/theme-builder/classes/locations-manager.php:370
    ElementorPro\M\T\C\Locations_Manager::do_location()
    wp-content/plugins/elementor-pro/modules/theme-builder/api.php:13
    elementor_theme_do_location()
    wp-content/themes/hello-elementor/index.php:20
    include()
    wp-includes/template-loader.php:106
    require_once()
    wp-blog-header.php:19
    require()
    index.php:17`

### Expected behavior

1. Able to use dynamic tags with an output as array-type with the display conditions function without getting a fatal error. 

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
== Server Environment ==
	Operating System: Linux
	Software: Apache/2
	MySQL version: MariaDB Server v10.6.18
	PHP Version: 8.1.28
	PHP Memory Limit: 2048M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.7
	Site URL: https://dev.toine.zip
	Home URL: https://dev.toine.zip
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 40M
	Max Memory limit: 2048M
	Permalink Structure: /%postname%/
	Language: en_US
	Timezone: Europe/Amsterdam
	Admin Email: hi@toine.zip
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor
	Version: 3.1.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:132.0) Gecko/20100101 Firefox/132.0

== Active Plugins ==
	Admin and Site Enhancements (ASE) Pro
		Version: 7.5.3
		Author: wpase.com

	Advanced Custom Fields PRO
		Version: 6.3.11
		Author: WP Engine

	Elementor
		Version: 3.25.9
		Author: Elementor.com

	Elementor Pro
		Version: 3.25.4
		Author: Elementor.com

	Query Monitor
		Version: 3.16.4
		Author: John Blackbourn


== Features ==
	Custom Fonts: 2
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Active
	Additional Custom Breakpoints: Active
	Container: Active
	Upgrade Swiper Library: Active
	Nested Elements Performance: Active
	Optimized Control Loading: Active
	Optimized Markup: Active
	Conditionally load Swiper CSS files: Active
	Plugin Onboarding: Active
	CSS Smooth Scroll: Active by default
	Default to New Theme Builder: Active
	Header &amp; Footer: Active
	Elementor Home Screen: Active by default
	Landing Pages: Active
	Nested Elements: Active
	Editor Top Bar: Active
	Pages Panel: Active
	Element Caching: Active
	Link In Bio: Active by default
	Floating Buttons: Active by default
	Elementor Editor Events: Active
	Atomic Widgets: Active
	Launchpad Checklist: Active
	Menu: Active


== Log ==
	
PHP: showing 2 of 2PHP: 2024-11-20 16:21:55 [notice X 5][/home/u52543p64574/domains/toine.zip/dev/wp-content/plugins/elementor/includes/base/controls-stack.php::229] hexdec(): Passing null to parameter #1 ($hex_string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-11-20 16:28:02 [error X 5][/home/u52543p64574/domains/toine.zip/dev/wp-content/plugins/elementor-pro/modules/display-conditions/classes/comparators-checker.php::76] Uncaught TypeError: ElementorPro\Modules\DisplayConditions\Classes\Comparators_Checker::check_string_contains_and_empty(): Argument #3 ($actual_value) must be of type string, array given, called in /home/u52543p64574/domains/toine.zip/dev/wp-content/plugins/elementor-pro/modules/display-conditions/conditions/dynamic-tags-condition.php on line 54 and defined in /home/u52543p64574/domains/toine.zip/dev/wp-content/plugins/elementor-pro/modules/display-conditions/classes/comparators-checker.php:76
Stack trace:
#0 /home/u52543p64574/domains/toine.zip/dev/wp-content/plugins/elementor-pro/modules/display-conditions/conditions/dynamic-tags-condition.php(54): ElementorPro\Modules\DisplayConditions\Classes\Comparators_Checker::check_string_contains_and_empty()
#1 /home/u52543p64574/domains/toine.zip/dev/wp-content/plugins/elementor-pro/modules/display-conditions/classes/and-condition.php(38): ElementorPro\Modules\DisplayConditions\Conditions\Dynamic_Tags_Condition-&gt;check()
#2 /home/u52543p64574/domains/toine.zip/dev/wp-content/plugins/elementor-pro/modules/display-conditions/classes/and-condition.php(24): ElementorPro\Modules\DisplayConditions\Classes\And_Condition-&gt;is_condition_passing_check()
#3 /home/u52543p64574/domains/toine.zip/dev/wp-content/plugins/elementor-pro/modules/display-conditions/classes/or-condition.php(27): ElementorPro\Modules\DisplayConditions\Classes\And_Condition-&gt;check()
#4 /home/u52543p64574/domains/toine.zip/dev/wp-content/plugins/elementor-pro/modules/display-conditions/module.php(183): ElementorPro\Modules\DisplayConditions\Classes\Or_Condition-&gt;check()
#5 /home/u52543p64574/domains/toine.zip/dev/wp-includes/class-wp-hook.php(324): ElementorPro\Modules\DisplayConditions\Module-&gt;before_element_render()
#6 /home/u52543p64574/domains/toine.zip/dev/wp-includes/class-wp-hook.php(348): WP_Hook-&gt;apply_filters()
#7 /home/u52543p64574/domains/toine.zip/dev/wp-includes/plugin.php(517): WP_Hook-&gt;do_action()
#8 /home/u52543p64574/domains/toine.zip/dev/wp-content/plugins/elementor/includes/base/element-base.php(474): do_action()
#9 /home/u52543p64574/domains/toine.zip/dev/wp-content/plugins/elementor/modules/element-cache/module.php(73): Elementor\Element_Base-&gt;print_element()
#10 /home/u52543p64574/domains/toine.zip/dev/wp-includes/shortcodes.php(434): Elementor\Modules\ElementCache\Module-&gt;Elementor\Modules\ElementCache\{closure}()
#11 [internal function]: do_shortcode_tag()
#12 /home/u52543p64574/domains/toine.zip/dev/wp-includes/shortcodes.php(273): preg_replace_callback()
#13 /home/u52543p64574/domains/toine.zip/dev/wp-content/plugins/elementor/core/base/document.php(1855): do_shortcode()
#14 /home/u52543p64574/domains/toine.zip/dev/wp-content/plugins/elementor/core/base/document.php(1200): Elementor\Core\Base\Document-&gt;print_elements()
#15 /home/u52543p64574/domains/toine.zip/dev/wp-content/plugins/elementor/includes/frontend.php(1190): Elementor\Core\Base\Document-&gt;print_elements_with_wrapper()
#16 /home/u52543p64574/domains/toine.zip/dev/wp-content/plugins/elementor-pro/modules/posts/skins/skin-content-base.php(271): Elementor\Frontend-&gt;get_builder_content()
#17 /home/u52543p64574/domains/toine.zip/dev/wp-content/plugins/elementor-pro/modules/theme-builder/widgets/post-content.php(111): ElementorPro\Modules\ThemeBuilder\Widgets\Post_Content-&gt;render_post_content()
#18 /home/u52543p64574/domains/toine.zip/dev/wp-content/plugins/elementor/includes/base/controls-stack.php(2325): ElementorPro\Modules\ThemeBuilder\Widgets\Post_Content-&gt;render()
#19 /home/u52543p64574/domains/toine.zip/dev/wp-content/plugins/elementor/includes/base/widget-base.php(635): Elementor\Controls_Stack-&gt;render_by_mode()
#20 /home/u52543p64574/domains/toine.zip/dev/wp-content/plugins/elementor/includes/base/widget-base.php(776): Elementor\Widget_Base-&gt;render_content()
#21 /home/u52543p64574/domains/toine.zip/dev/wp-content/plugins/elementor/includes/base/element-base.php(483): Elementor\Widget_Base-&gt;print_content()
#22 /home/u52543p64574/domains/toine.zip/dev/wp-content/plugins/elementor/modules/element-cache/module.php(73): Elementor\Element_Base-&gt;print_element()
#23 /home/u52543p64574/domains/toine.zip/dev/wp-includes/shortcodes.php(434): Elementor\Modules\ElementCache\Module-&gt;Elementor\Modules\ElementCache\{closure}()
#24 [internal function]: do_shortcode_tag()
#25 /home/u52543p64574/domains/toine.zip/dev/wp-includes/shortcodes.php(273): preg_replace_callback()
#26 /home/u52543p64574/domains/toine.zip/dev/wp-content/plugins/elementor/core/base/document.php(1855): do_shortcode()
#27 /home/u52543p64574/domains/toine.zip/dev/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(412): Elementor\Core\Base\Document-&gt;print_elements()
#28 /home/u52543p64574/domains/toine.zip/dev/wp-content/plugins/elementor/includes/frontend.php(1190): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document-&gt;print_elements_with_wrapper()
#29 /home/u52543p64574/domains/toine.zip/dev/wp-content/plugins/elementor/core/base/document.php(1248): Elementor\Frontend-&gt;get_builder_content()
#30 /home/u52543p64574/domains/toine.zip/dev/wp-content/plugins/elementor/modules/library/documents/library-document.php(76): Elementor\Core\Base\Document-&gt;get_content()
#31 /home/u52543p64574/domains/toine.zip/dev/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(158): Elementor\Modules\Library\Documents\Library_Document-&gt;get_content()
#32 /home/u52543p64574/domains/toine.zip/dev/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(173): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document-&gt;get_content()
#33 /home/u52543p64574/domains/toine.zip/dev/wp-content/plugins/elementor-pro/modules/theme-builder/documents/single-base.php(100): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document-&gt;print_content()
#34 /home/u52543p64574/domains/toine.zip/dev/wp-content/plugins/elementor-pro/modules/theme-builder/classes/locations-manager.php(370): ElementorPro\Modules\ThemeBuilder\Documents\Single_Base-&gt;print_content()
#35 /home/u52543p64574/domains/toine.zip/dev/wp-content/plugins/elementor-pro/modules/theme-builder/api.php(13): ElementorPro\Modules\ThemeBuilder\Classes\Locations_Manager-&gt;do_location()
#36 /home/u52543p64574/domains/toine.zip/dev/wp-content/themes/hello-elementor/index.php(20): elementor_theme_do_location()
#37 /home/u52543p64574/domains/toine.zip/dev/wp-includes/template-loader.php(106): include(&#039;/home/u52543p64...&#039;)
#38 /home/u52543p64574/domains/toine.zip/dev/wp-blog-header.php(19): require_once(&#039;/home/u52543p64...&#039;)
#39 /home/u52543p64574/domains/toine.zip/dev/index.php(17): require(&#039;/home/u52543p64...&#039;)
#40 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hey @toineenzo! How's it going?

Thank you for submitting this issue! 🙏 

Please, keep in mind that at the moment, element Display Conditions do not support ACF (or any other custom field framework) for reasons like the one you've just raised. While Dynamic Tags are supported, we only support strings, not arrays. So while this issue is valid, it's also not technically a bug because it's not the intended use case.

There are plans to improve the compatibility with ACF fields, but only on a future version. Since this is not the intended use case for this feature, we can't confirm we are going to work on this issue for the time being. We can’t say exactly when it'll be sorted out, but we kindly ask for your patience. Thanks for understanding! 😉

Best regards

**Comment by toineenzo** [comment]
Hi @nicholaszein !

Thank you for your quick response. I never thought about that that ACF fields weren't (officially) and only basis dynamic tags. Hopefully it will be added in the future. 👍
At least there's an issue created for it now so people can find it. I wasn't able to find any related issue here on GitHub.
But doing this with dynamic conditions honestly shouldn't create a fatal error and this should be changed to some time of "soft error" without crashing the whole site. Would that be possible?

**Comment by nicholaszein** [comment]
Hi @toineenzo!

Yes, you are correct, there is no validation at this moment.

We will discuss this further internally, and see if we can prevent these fatal errors.

**Comment by RCheesley** [comment]
Same problem here, looking forward to it being supported in the future!

**Comment by caspervoogt** [comment]
I second what @toineenzo said, because it isn't always obvious even to webmaster which ACF field is an array vs string. A soft error would make that obvious.

**Comment by Erudition** [comment]
Dang, I just spent all day triaging this, I got no error message in the logs. I just want to see if the variable is set - it works when it's not set (does not display) but when there's an actual array it crashes wordpress because it's not a string. This is counterintuitive because, whether arrays are supported or not, the type shouldn't matter when checking if a field is not empty...

**Comment by toineenzo** [comment]
@nicholaszein can you give me an update on this? Thanks!

**Comment by joegabby** [comment]
@toineenzo Thanks for making a post about this issue. I just had the same experience now and was glad I saw your post. I am really  looking forward to ACF being fully supported in the nearest feature; it would really increase productivity.

**Comment by rloes** [comment]
Please fix. Support of ACF is very important in WordPress ecosystem.

**Comment by tjtate** [comment]
Ditto. using ACF checkbox to toggle elements. would be extremely useful

**Comment by sstarzyk10** [comment]
This ticket was a life saver for me because this just happened to me and this saved me what I can assume would have been a lot of time debugging. I was trying to hide an element on the page if the user did _not_ check an ACF checkbox and got the critical error like everyone else.

I agree some sort of error message would be nice. Or if you don't support ACF fields, don't load them in the dropdown list of Dynamic Tags. BUT, support for ACF fields would be so much better!

That being said, in my case, I was able to do a work around. The dynamic functionality still works with strings. Since my needs were a simply yes/no, when creating the dynamic display, instead of choosing that a dynamic tag is or is not some value, I used the option "is not empty". Then I removed my checkbox option and put one of the sub fields that would be filled in if the checkbox was check "Yes" as the dynamic tag (it still gave a critical error when trying is/is not empty on the checkbox field).

Obviously work arounds aren't ideal, and it might not work for everyone. But if you have a list of checkboxes or a drop down menu, you could use conditional logic in ACF to populate/not populate _another_ text field based on the select, and then do a dynamic check on _that_ text field instead. I didn't test that myself, but it makes sense in my head!

**Comment by ybimp** [comment]
Almost 2 years and the Elementor team has not been able to apply this minor fix to prevent Fatal Error state.

For anyone experiencing this issue, this is a fix
File:
/elementor-pro/modules/display-conditions/classes/comparators-checker.php

Class:
ElementorPro\Modules\DisplayConditions\Classes\Comparators_Checker


```
public static function check_string_contains_and_empty( string $comparator, string $expected_value, string|array $actual_value ): bool {
    if ( $comparator === Comparator_Provider::COMPARATOR_IS_EMPTY ) {
        return is_array( $actual_value )
            ? empty( array_filter( $actual_value, static fn( $v ) => $v !== '' && $v !== null ) )
            : empty( $actual_value );
    }

    if ( $comparator === Comparator_Provider::COMPARATOR_IS_NOT_EMPTY ) {
        return ! self::check_string_contains_and_empty( Comparator_Provider::COMPARATOR_IS_EMPTY, $expected_value, $actual_value );
    }

    if ( is_array( $actual_value ) ) {
        foreach ( $actual_value as $value ) {
            if ( is_string( $value ) && self::check_string_contains( $comparator, $expected_value, $value ) ) {
                return true;
            }
        }
        return false;
    }

    return self::check_string_contains( $comparator, $expected_value, $actual_value );
} 
```
