### ISSUE TITLE
Issue with PHP 8 and greater

### ISSUE THREAD

**Issue by panilo** [elementor/elementor#29415]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

I'm running 
- WP 6.7.1 
- Elementor 3.25.10
- Elementor Pro 3.25.4
- Hello Elementor (Theme) 3.1.1

Updating to PHP 8 and greater cause the following issue 

```
[26-Nov-2024 08:29:21 UTC] PHP Fatal error:  Uncaught TypeError: ltrim(): Argument #1 ($string) must be of type string, WP_Error given in /home/customer/www/sandbox.colombogioiellieri.it/public_html/wp-includes/formatting.php:4467
Stack trace:
#0 /home/customer/www/sandbox.colombogioiellieri.it/public_html/wp-includes/formatting.php(4467): ltrim(Object(WP_Error))
#1 /home/customer/www/sandbox.colombogioiellieri.it/public_html/wp-content/plugins/elementor-pro/modules/theme-elements/widgets/post-info.php(1040): esc_url(Object(WP_Error))
#2 /home/customer/www/sandbox.colombogioiellieri.it/public_html/wp-content/plugins/elementor-pro/modules/theme-elements/widgets/post-info.php(950): ElementorPro\Modules\ThemeElements\Widgets\Post_Info->render_item_text(Array, '274b943')
#3 /home/customer/www/sandbox.colombogioiellieri.it/public_html/wp-content/plugins/elementor-pro/modules/theme-elements/widgets/post-info.php(1083): ElementorPro\Modules\ThemeElements\Widgets\Post_Info->render_item(Array)
#4 /home/customer/www/sandbox.colombogioiellieri.it/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(2325): ElementorPro\Modules\ThemeElements\Widgets\Post_Info->render()
#5 /home/customer/www/sandbox.colombogioiellieri.it/public_html/wp-content/plugins/elementor/includes/base/widget-base.php(635): Elementor\Controls_Stack->render_by_mode()
#6 /home/customer/www/sandbox.colombogioiellieri.it/public_html/wp-content/plugins/elementor/includes/base/widget-base.php(776): Elementor\Widget_Base->render_content()
#7 /home/customer/www/sandbox.colombogioiellieri.it/public_html/wp-content/plugins/elementor/includes/base/element-base.php(483): Elementor\Widget_Base->print_content()
#8 /home/customer/www/sandbox.colombogioiellieri.it/public_html/wp-content/plugins/elementor/includes/base/element-base.php(1443): Elementor\Element_Base->print_element()
#9 /home/customer/www/sandbox.colombogioiellieri.it/public_html/wp-content/plugins/elementor/includes/base/element-base.php(483): Elementor\Element_Base->print_content()
#10 /home/customer/www/sandbox.colombogioiellieri.it/public_html/wp-content/plugins/elementor/core/base/document.php(1874): Elementor\Element_Base->print_element()
#11 /home/customer/www/sandbox.colombogioiellieri.it/public_html/wp-content/plugins/elementor/core/base/document.php(1799): Elementor\Core\Base\Document->do_print_elements(Array)
#12 /home/customer/www/sandbox.colombogioiellieri.it/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(412): Elementor\Core\Base\Document->print_elements(Array)
#13 /home/customer/www/sandbox.colombogioiellieri.it/public_html/wp-content/plugins/elementor-pro/modules/loop-builder/documents/loop.php(260): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document->print_elements_with_wrapper(Array)
#14 /home/customer/www/sandbox.colombogioiellieri.it/public_html/wp-content/plugins/elementor/includes/frontend.php(1190): ElementorPro\Modules\LoopBuilder\Documents\Loop->print_elements_with_wrapper(Array)
#15 /home/customer/www/sandbox.colombogioiellieri.it/public_html/wp-content/plugins/elementor/core/base/document.php(1248): Elementor\Frontend->get_builder_content(566, false)
#16 /home/customer/www/sandbox.colombogioiellieri.it/public_html/wp-content/plugins/elementor/modules/library/documents/library-document.php(76): Elementor\Core\Base\Document->get_content(false)
#17 /home/customer/www/sandbox.colombogioiellieri.it/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(158): Elementor\Modules\Library\Documents\Library_Document->get_content(false)
#18 /home/customer/www/sandbox.colombogioiellieri.it/public_html/wp-content/plugins/elementor-pro/modules/loop-builder/documents/loop.php(290): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document->get_content()
#19 /home/customer/www/sandbox.colombogioiellieri.it/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(173): ElementorPro\Modules\LoopBuilder\Documents\Loop->get_content()
#20 /home/customer/www/sandbox.colombogioiellieri.it/public_html/wp-content/plugins/elementor-pro/modules/loop-builder/skins/skin-loop-base.php(202): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document->print_content()
#21 /home/customer/www/sandbox.colombogioiellieri.it/public_html/wp-content/plugins/elementor-pro/modules/loop-builder/skins/skin-loop-base.php(187): ElementorPro\Modules\LoopBuilder\Skins\Skin_Loop_Base->render_post_content(566)
#22 /home/customer/www/sandbox.colombogioiellieri.it/public_html/wp-content/plugins/elementor-pro/modules/posts/skins/skin-base.php(929): ElementorPro\Modules\LoopBuilder\Skins\Skin_Loop_Base->render_post()
#23 /home/customer/www/sandbox.colombogioiellieri.it/public_html/wp-content/plugins/elementor-pro/modules/loop-builder/skins/skin-loop-base.php(130): ElementorPro\Modules\Posts\Skins\Skin_Base->render()
#24 /home/customer/www/sandbox.colombogioiellieri.it/public_html/wp-content/plugins/elementor/includes/base/skin-base.php(79): ElementorPro\Modules\LoopBuilder\Skins\Skin_Loop_Base->render()
#25 /home/customer/www/sandbox.colombogioiellieri.it/public_html/wp-content/plugins/elementor/includes/base/widget-base.php(633): Elementor\Skin_Base->render_by_mode()
#26 /home/customer/www/sandbox.colombogioiellieri.it/public_html/wp-content/plugins/elementor/includes/base/widget-base.php(776): Elementor\Widget_Base->render_content()
#27 /home/customer/www/sandbox.colombogioiellieri.it/public_html/wp-content/plugins/elementor/includes/base/element-base.php(483): Elementor\Widget_Base->print_content()
#28 /home/customer/www/sandbox.colombogioiellieri.it/public_html/wp-content/plugins/elementor/includes/base/element-base.php(1443): Elementor\Element_Base->print_element()
#29 /home/customer/www/sandbox.colombogioiellieri.it/public_html/wp-content/plugins/elementor/includes/base/element-base.php(483): Elementor\Element_Base->print_content()
#30 /home/customer/www/sandbox.colombogioiellieri.it/public_html/wp-content/plugins/elementor/includes/base/element-base.php(1443): Elementor\Element_Base->print_element()
#31 /home/customer/www/sandbox.colombogioiellieri.it/public_html/wp-content/plugins/elementor/includes/base/element-base.php(483): Elementor\Element_Base->print_content()
#32 /home/customer/www/sandbox.colombogioiellieri.it/public_html/wp-content/plugins/elementor/core/base/document.php(1874): Elementor\Element_Base->print_element()
#33 /home/customer/www/sandbox.colombogioiellieri.it/public_html/wp-content/plugins/elementor/core/base/document.php(1799): Elementor\Core\Base\Document->do_print_elements(Array)
#34 /home/customer/www/sandbox.colombogioiellieri.it/public_html/wp-content/plugins/elementor/core/base/document.php(1200): Elementor\Core\Base\Document->print_elements(Array)
#35 /home/customer/www/sandbox.colombogioiellieri.it/public_html/wp-content/plugins/elementor/includes/frontend.php(1190): Elementor\Core\Base\Document->print_elements_with_wrapper(Array)
#36 /home/customer/www/sandbox.colombogioiellieri.it/public_html/wp-content/plugins/elementor/includes/frontend.php(1085): Elementor\Frontend->get_builder_content(317)
#37 /home/customer/www/sandbox.colombogioiellieri.it/public_html/wp-includes/class-wp-hook.php(324): Elementor\Frontend->apply_builder_in_content('I nostri valori...')
#38 /home/customer/www/sandbox.colombogioiellieri.it/public_html/wp-includes/plugin.php(205): WP_Hook->apply_filters('I nostri valori...', Array)
#39 /home/customer/www/sandbox.colombogioiellieri.it/public_html/wp-includes/post-template.php(256): apply_filters('the_content', 'I nostri valori...')
#40 /home/customer/www/sandbox.colombogioiellieri.it/public_html/wp-content/plugins/elementor/modules/page-templates/module.php(190): the_content()
#41 [internal function]: Elementor\Modules\PageTemplates\Module->print_callback()
#42 /home/customer/www/sandbox.colombogioiellieri.it/public_html/wp-content/plugins/elementor/modules/page-templates/module.php(207): call_user_func(Array)
#43 /home/customer/www/sandbox.colombogioiellieri.it/public_html/wp-content/plugins/elementor/modules/page-templates/templates/header-footer.php(19): Elementor\Modules\PageTemplates\Module->print_content()
#44 /home/customer/www/sandbox.colombogioiellieri.it/public_html/wp-includes/template-loader.php(106): include('/home/customer/...')
#45 /home/customer/www/sandbox.colombogioiellieri.it/public_html/wp-blog-header.php(19): require_once('/home/customer/...')
#46 /home/customer/www/sandbox.colombogioiellieri.it/public_html/index.php(17): require('/home/customer/...')
#47 {main}
  thrown in /home/customer/www/sandbox.colombogioiellieri.it/public_html/wp-includes/formatting.php on line 4467
```

Is someone able to help?

Website URL: sandbox.colombogioiellieri.it (no public DNS, use 35.204.119.129).

### Steps to reproduce

1. Install latest WP 
2. Install latest Elementor and Elementor Pro
3. Install Hello Elementor
4. Switch to PHP 8

### Expected behavior

Elementor should be compatible with PHP 8 and greater

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v8.0.36-28
	PHP Version: 7.4.33
	PHP Memory Limit: 768M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.7.1
	Site URL: https://sandbox.colombogioiellieri.it
	Home URL: https://sandbox.colombogioiellieri.it
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 256M
	Max Memory limit: 768M
	Permalink Structure: /%category%/%postname%/
	Language: it_IT
	Timezone: Europe/Rome
	Admin Email: webmastertoolid@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 2.0.0
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 3.1.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: it-IT
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 6.3.2.1
		Author: WP Engine

	Boxzilla
		Version: 3.3.3
		Author: ibericode

	Classic Editor
		Version: 1.6.6
		Author: WordPress Contributors

	Elementor
		Version: 3.25.10
		Author: Elementor.com

	Elementor Pro
		Version: 3.25.4
		Author: Elementor.com

	Enable Media Replace
		Version: 4.1.5
		Author: ShortPixel

	Filter Everything PRO
		Version: 1.8.8
		Author: Andrii Stepasiuk

	Gravity Forms
		Version: 2.9.0
		Author: Gravity Forms

	Redirection
		Version: 5.5.1
		Author: John Godley

	Safe SVG
		Version: 2.2.6
		Author: 10up

	Schema &amp; Structured Data for WP &amp; AMP
		Version: 1.38.1
		Author: Magazine3

	Simple History
		Version: 5.2.0
		Author: Pär Thernström

	Speed Optimizer
		Version: 7.7.1
		Author: SiteGround

	Unlimited Elements for Elementor (Premium)
		Version: 1.5.129
		Author: Unlimited Elements

	WP All Import - ACF Add-On
		Version: 3.3.9
		Author: Soflyy

	WP All Import Pro
		Version: 4.8.8
		Author: Soflyy

	Yoast Duplicate Post
		Version: 4.5
		Author: Enrico Battocchi & Team Yoast

	Yoast SEO
		Version: 23.9
		Author: Team Yoast


== Caratteristiche ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrazioni ==
	


== Esperimenti Elementor ==
	Caricamento CSS migliorato: Inattivo per impostazione predefinita
	Icone dei font in linea: Attivo per impostazione predefinita
	Punti di interruzione aggiuntivi: Attivo per impostazione predefinita
	Contenitore: Attiva
	Aggiorna la libreria Swiper: Attivo per impostazione predefinita
	Nested Elements Performance: Attivo per impostazione predefinita
	Optimized Control Loading: Attivo per impostazione predefinita
	Markup ottimizzato: Inattivo per impostazione predefinita
	Conditionally load Swiper CSS files: Inattivo per impostazione predefinita
	Plugin Onboarding: Attivo per impostazione predefinita
	CSS Smooth Scroll: Attivo per impostazione predefinita
	Predefinito per Nuovo generatore di temi: Attiva
	Header e Footer: Attivo per impostazione predefinita
	Schermata home di Elementor: Attivo per impostazione predefinita
	Landing Page: Attivo per impostazione predefinita
	Elementi annidati: Attivo per impostazione predefinita
	Barra unificata degli strumenti dell&#039;editor: Attivo per impostazione predefinita
	Pannello pagine: Inattivo per impostazione predefinita
	Cache degli elementi: Inattivo per impostazione predefinita
	Link In Bio: Attivo per impostazione predefinita
	Floating Buttons: Attivo per impostazione predefinita
	Elementor Editor Events: Inattivo per impostazione predefinita
	Atomic Widgets: Inattivo per impostazione predefinita
	Launchpad Checklist: Inattivo per impostazione predefinita
	Menu: Inattivo per impostazione predefinita


== Registro ==
	
JS: showing 11 of 11JS: 2024-07-10 10:56:50 [error X 2][https://staging4.colombogioiellieri.it/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.22.3:3:825635] Cannot read properties of undefined (reading &#039;localized&#039;) 
JS: 2024-07-30 13:13:59 [error X 1][https://staging4.colombogioiellieri.it/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.22.3:3:54583] Cannot read properties of undefined (reading &#039;activate&#039;) 
JS: 2024-07-30 13:40:14 [error X 2][https://staging4.colombogioiellieri.it/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.22.3:3:657336] Cannot read properties of undefined (reading &#039;isDesignable&#039;) 
JS: 2024-08-05 13:23:09 [error X 1][https://staging4.colombogioiellieri.it/wp-admin/post.php?post=1284&amp;action=elementor:6:39] Cannot read properties of undefined (reading &#039;needHelpUrl&#039;) 
JS: 2024-08-05 13:23:10 [error X 1][https://staging4.colombogioiellieri.it/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.22.3:3:760711] Cannot read properties of undefined (reading &#039;widgets_settings&#039;) 
JS: 2024-10-31 10:33:23 [error X 1][https://www.colombogioiellieri.it/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view1159&quot;) has already been destroyed and cannot be used. 
JS: 2024-11-19 14:16:10 [error X 10][https://www.colombogioiellieri.it/wp-content/plugins/elementor/assets/js/common-modules.min.js?ver=3.24.0:2:56144] Model.isValidChild() should be implemented, please provide &#039;isValidChild&#039; functionality. 
JS: 2024-11-25 11:43:04 [error X 12][https://sandbox.colombogioiellieri.it/wp-content/plugins/elementor/assets/js/common.min.js?ver=3.25.10:3:97101] Cannot read properties of undefined (reading &#039;toLowerCase&#039;) 
JS: 2024-11-25 11:43:05 [error X 1][https://sandbox.colombogioiellieri.it/wp-content/plugins/elementor/assets/js/common.min.js?ver=3.25.10:3:99538] Cannot read properties of undefined (reading &#039;$el&#039;) 
JS: 2024-11-25 11:43:07 [error X 2][https://sandbox.colombogioiellieri.it/wp-content/plugins/elementor/assets/js/common.min.js?ver=3.25.10:3:89737] Cannot read properties of undefined (reading &#039;$activeItem&#039;) 
JS: 2024-11-25 14:42:11 [error X 4][https://sandbox.colombogioiellieri.it/wp-admin/load-scripts.php?c=0&amp;loadchunk_0=jquery-core,jquery-migrate,utils,wp-dom-ready,wp-hooks&amp;ver=6.7.1:2:28760] Cannot read properties of undefined (reading &#039;value&#039;) 

PHP: showing 11 of 11PHP: 2024-08-09 09:16:10 [notice X 90][/home/customer/www/colombogioiellieri.it/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined index: condition_type [array (
  'trace' => '
#0: /home/customer/www/colombogioiellieri.it/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /home/customer/www/colombogioiellieri.it/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /home/customer/www/colombogioiellieri.it/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /home/customer/www/colombogioiellieri.it/public_html/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2024-08-11 20:02:51 [notice X 96][/home/customer/www/colombogioiellieri.it/public_html/wp-content/plugins/elementor-pro/modules/theme-elements/widgets/post-info.php::878] Trying to get property &#039;term_id&#039; of non-object [array (
  'trace' => '
#0: /home/customer/www/colombogioiellieri.it/public_html/wp-content/plugins/elementor-pro/modules/theme-elements/widgets/post-info.php(878): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/customer/www/colombogioiellieri.it/public_html/wp-content/plugins/elementor-pro/modules/theme-elements/widgets/post-info.php(910): ElementorPro\Modules\ThemeElements\Widgets\Post_Info -> get_meta_data()
#2: /home/customer/www/colombogioiellieri.it/public_html/wp-content/plugins/elementor-pro/modules/theme-elements/widgets/post-info.php(1083): ElementorPro\Modules\ThemeElements\Widgets\Post_Info -> render_item()
#3: /home/customer/www/colombogioiellieri.it/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(2325): ElementorPro\Modules\ThemeElements\Widgets\Post_Info -> render()
#4: /home/customer/www/colombogioiellieri.it/public_html/wp-content/plugins/elementor/includes/base/widget-base.php(635): Elementor\Controls_Stack -> render_by_mode()
',
)]
PHP: 2024-08-11 20:02:51 [notice X 96][/home/customer/www/colombogioiellieri.it/public_html/wp-content/plugins/elementor-pro/modules/theme-elements/widgets/post-info.php::878] Trying to get property &#039;name&#039; of non-object [array (
  'trace' => '
#0: /home/customer/www/colombogioiellieri.it/public_html/wp-content/plugins/elementor-pro/modules/theme-elements/widgets/post-info.php(878): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/customer/www/colombogioiellieri.it/public_html/wp-content/plugins/elementor-pro/modules/theme-elements/widgets/post-info.php(910): ElementorPro\Modules\ThemeElements\Widgets\Post_Info -> get_meta_data()
#2: /home/customer/www/colombogioiellieri.it/public_html/wp-content/plugins/elementor-pro/modules/theme-elements/widgets/post-info.php(1083): ElementorPro\Modules\ThemeElements\Widgets\Post_Info -> render_item()
#3: /home/customer/www/colombogioiellieri.it/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(2325): ElementorPro\Modules\ThemeElements\Widgets\Post_Info -> render()
#4: /home/customer/www/colombogioiellieri.it/public_html/wp-content/plugins/elementor/includes/base/widget-base.php(635): Elementor\Controls_Stack -> render_by_mode()
',
)]
PHP: 2024-08-11 20:02:51 [notice X 96][/home/customer/www/colombogioiellieri.it/public_html/wp-content/plugins/elementor-pro/modules/theme-elements/widgets/post-info.php::880] Trying to get property &#039;term_id&#039; of non-object [array (
  'trace' => '
#0: /home/customer/www/colombogioiellieri.it/public_html/wp-content/plugins/elementor-pro/modules/theme-elements/widgets/post-info.php(880): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/customer/www/colombogioiellieri.it/public_html/wp-content/plugins/elementor-pro/modules/theme-elements/widgets/post-info.php(910): ElementorPro\Modules\ThemeElements\Widgets\Post_Info -> get_meta_data()
#2: /home/customer/www/colombogioiellieri.it/public_html/wp-content/plugins/elementor-pro/modules/theme-elements/widgets/post-info.php(1083): ElementorPro\Modules\ThemeElements\Widgets\Post_Info -> render_item()
#3: /home/customer/www/colombogioiellieri.it/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(2325): ElementorPro\Modules\ThemeElements\Widgets\Post_Info -> render()
#4: /home/customer/www/colombogioiellieri.it/public_html/wp-content/plugins/elementor/includes/base/widget-base.php(635): Elementor\Controls_Stack -> render_by_mode()
',
)]
PHP: 2024-09-05 14:55:02 [notice X 1][/home/customer/www/colombogioiellieri.it/public_html/wp-content/plugins/elementor/includes/managers/image.php::113] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-11-25 12:40:50 [notice X 1][/home/customer/www/sandbox.colombogioiellieri.it/public_html/wp-content/plugins/elementor/vendor_prefixed/php-di/php-di/src/Definition/Resolver/ParameterResolver.php::34] ElementorDeps\DI\Definition\Resolver\ParameterResolver::resolveParameters(): Implicitly marking parameter $method as nullable is deprecated, the explicit nullable type must be used instead [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-11-25 12:50:43 [warning X 54][/home/customer/www/sandbox.colombogioiellieri.it/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key &quot;condition_type&quot; [array (
  'trace' => '
#0: /home/customer/www/sandbox.colombogioiellieri.it/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /home/customer/www/sandbox.colombogioiellieri.it/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /home/customer/www/sandbox.colombogioiellieri.it/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /home/customer/www/sandbox.colombogioiellieri.it/public_html/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2024-11-25 12:50:43 [notice X 8][/home/customer/www/sandbox.colombogioiellieri.it/public_html/wp-content/plugins/elementor/core/logger/manager.php::250] Constant E_STRICT is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-11-25 14:11:31 [notice X 1][/home/customer/www/sandbox.colombogioiellieri.it/public_html/wp-content/plugins/elementor/vendor_prefixed/php-di/php-di/src/Container.php::87] ElementorDeps\DI\Container::__construct(): Implicitly marking parameter $wrapperContainer as nullable is deprecated, the explicit nullable type must be used instead [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-11-25 14:11:33 [notice X 1][/home/customer/www/sandbox.colombogioiellieri.it/public_html/wp-content/plugins/elementor-pro/vendor_prefixed/php-di/php-di/src/Definition/Resolver/ParameterResolver.php::34] ElementorProDeps\DI\Definition\Resolver\ParameterResolver::resolveParameters(): Implicitly marking parameter $method as nullable is deprecated, the explicit nullable type must be used instead [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-11-25 14:11:33 [notice X 1][/home/customer/www/sandbox.colombogioiellieri.it/public_html/wp-content/plugins/elementor/core/files/css/base.php::949] Elementor\Core\Files\CSS\Base::get_style_controls(): Implicitly marking parameter $settings as nullable is deprecated, the explicit nullable type must be used instead [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 20 of 202024-09-11 00:01:12 [info] elementor::elementor_updater Started 
2024-09-11 00:01:12 [info] Elementor/Upgrades - _on_each_version Start  
2024-09-11 00:01:12 [info] Elementor/Upgrades - _on_each_version Finished 
2024-09-11 00:01:12 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.22.3',
  'to' => '3.24.0',
)]
2024-09-11 00:01:12 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.22.3',
  'to' => '3.24.0',
)]
2024-11-22 18:48:28 [info] elementor::elementor_updater Started 
2024-11-22 18:48:28 [info] Elementor/Upgrades - _on_each_version Start  
2024-11-22 18:48:28 [info] Elementor/Upgrades - _on_each_version Finished 
2024-11-22 18:48:28 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.24.0',
  'to' => '3.25.9',
)]
2024-11-22 18:48:28 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.24.0',
  'to' => '3.25.9',
)]
2024-11-25 12:36:01 [info] elementor::elementor_updater Started 
2024-11-25 12:36:01 [info] Elementor/Upgrades - _on_each_version Start  
2024-11-25 12:36:01 [info] Elementor/Upgrades - _on_each_version Finished 
2024-11-25 12:36:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.25.9',
  'to' => '3.25.10',
)]
2024-11-25 12:36:01 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.25.9',
  'to' => '3.25.10',
)]
2024-11-25 14:11:33 [info] elementor-pro::elementor_pro_updater Started 
2024-11-25 14:11:33 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-11-25 14:11:33 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-11-25 14:11:33 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.22.1',
  'to' => '3.25.4',
)]
2024-11-25 14:11:33 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.22.1',
  'to' => '3.25.4',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibilità non specificata
	Unlimited Elements for Elementor (Premium): Compatibilità non specificata

== Elementor Pro - Compatibility Tag ==
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by panilo** [comment]
> Did you manage to solve this? I'm getting the same error after adding the WooCommerce Brand Layered Nav widget to my template. Reverting to PHP 7.4 fixes the fatal error but the Elementor editor doesn't load.

Hi @bobhuf, no I did not... reverting was the only option.

**Comment by bobhuf** [comment]
Sheesh :/ Thanks for letting me know!

**Comment by caspervoogt** [comment]
I use this as an mu-plugin for now;

`<?php
/**
 * Fix Elementor BFI Thumb PHP 8+ fatal error.
 *
 * PHP 8 throws a ValueError when imagecreatetruecolor() receives 0 for
 * width or height. Elementor's bundled bfi-thumb library can produce zero
 * dimensions in certain resize scenarios. This mu-plugin hooks into the
 * WP image-editor pipeline to clamp dimensions to a minimum of 1px before
 * GD ever sees them.
 */

add_filter('image_resize_dimensions', function ($payload, $orig_w, $orig_h, $dest_w, $dest_h, $crop) {
    if ($payload === false) {
        return $payload;
    }

    // $payload is an array: [ $dst_x, $dst_y, $src_x, $src_y, $dst_w, $dst_h, $src_w, $src_h ]
    if (is_array($payload)) {
        // Clamp destination width and height to at least 1
        if (isset($payload[4]) && (int) $payload[4] < 1) {
            $payload[4] = 1;
        }
        if (isset($payload[5]) && (int) $payload[5] < 1) {
            $payload[5] = 1;
        }
    }

    return $payload;
}, 999, 6);
`
