### ISSUE TITLE
Learndash

### ISSUE THREAD

**Issue by CainaraBurton** [elementor/elementor#29453]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

The element tab is not oppening, I troubleshoot and it is Learndash that is crashing the system. 

### Steps to reproduce

https://github.com/user-attachments/assets/d6ac59df-4a39-40f7-9114-d4e8716921b7

### Expected behavior

The bar will be available 

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
== Server Environment ==
	Operating System: Linux
	Software: nginx
	MySQL version: MariaDB Server v10.6.18
	PHP Version: 8.1.31
	PHP Memory Limit: 512M
	PHP Max Input Vars: 6144
	PHP Max Post Size: 2047M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.7.1
	Site URL: https://yogacomcainara.com
	Home URL: https://yogacomcainara.com
	WP Multisite: No
	Max Upload Size: 2 GB
	Memory limit: 512M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: pt_BR
	Timezone: 0
	Admin Email: cainara@hotmail.co.uk
	Debug Mode: Inactive

== Theme ==
	Name: Neve
	Version: 3.8.15
	Author: ThemeIsle
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36

== Active Plugins ==
	Akismet Anti-spam: Spam Protection
		Version: 5.3.5
		Author: Automattic - Anti-spam Team

	Brazilian Market on WooCommerce
		Version: 4.0.2
		Author: Claudio Sanches

	Click to Chat
		Version: 4.12.1
		Author: HoliThemes

	Elementor
		Version: 3.26.0-dev2
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.25.4
		Author: Elementor.com

	Google Analytics Dashboard for WP (GADWP)
		Version: 8.2.2
		Author: ExactMetrics

	Google for WooCommerce
		Version: 2.9.0
		Author: WooCommerce

	GTM4WP - A Google Tag Manager (GTM) plugin for WordPress
		Version: 1.20.2
		Author: Thomas Geiger

	Gutenberg
		Version: 19.6.4
		Author: Gutenberg Team

	Head, Footer and Post Injections
		Version: 3.2.8
		Author: Stefano Lissa

	Header Footer Code Manager
		Version: 1.1.39
		Author: DraftPress

	Health Check &amp; Troubleshooting
		Version: 1.7.1
		Author: The WordPress.org community

	Image Optimizer - Compress, Resize and Optimize Images
		Version: 1.6.1
		Author: Elementor.com

	Jetpack
		Version: 14.1-a.7
		Author: Automattic

	LearnDash LMS
		Version: 4.18.1.1
		Author: LearnDash

	LearnDash LMS - Elementor
		Version: 1.0.9.1
		Author: LearnDash

	LearnDash LMS - MemberPress Integration
		Version: 2.2.2
		Author: LearnDash

	LearnDash LMS - Notifications
		Version: 1.6.4
		Author: LearnDash

	LearnDash LMS - Paid Memberships Pro
		Version: 1.3.5
		Author: LearnDash

	LearnDash LMS - Restrict Content Pro Integration
		Version: 1.1.1
		Author: LearnDash

	LearnDash LMS - Stripe Integration
		Version: 1.9.3
		Author: LearnDash

	LearnDash LMS - WooCommerce Integration
		Version: 2.0.1
		Author: LearnDash

	MailPoet
		Version: 5.4.1
		Author: MailPoet

	MailPoet Premium
		Version: 5.4.0
		Author: MailPoet

	PagBank Connect
		Version: 4.24.1
		Author: PagBank Integrações (Ricardo Martins)

	PagBank for WooCommerce
		Version: 1.2.1
		Author: PagBank

	Site Kit by Google
		Version: 1.140.0
		Author: Google

	Starter Sites &amp; Templates by Neve
		Version: 1.2.14
		Author: Themeisle

	UpdraftPlus - Backup/Restore
		Version: 1.24.11
		Author: TeamUpdraft, DavidAnderson

	User Menus
		Version: 1.3.2
		Author: Code Atlantic

	WooCommerce
		Version: 9.4.2
		Author: Automattic

	WooCommerce Stripe Gateway
		Version: 8.9.0
		Author: Stripe

	WooPayments
		Version: 8.5.1
		Author: WooCommerce

	WP-Sweep
		Version: 1.1.8
		Author: Lester 'GaMerZ' Chan

	WPForms Lite
		Version: 1.9.2.2
		Author: WPForms

	WP Mail Logging
		Version: 1.13.1
		Author: WP Mail Logging Team

	WP Mail SMTP
		Version: 4.2.0
		Author: WP Mail SMTP

	WPMU DEV Dashboard
		Version: 4.11.0
		Author: WPMU DEV

	Yoast SEO
		Version: 23.9
		Author: Team Yoast


== Must-Use Plugins ==
	Health Check Troubleshooting Mode
		Version: 1.9.2
		Author: 

	LearnDash LMS Multisite
		Version: 1.0.0
		Author: LearnDash

	wpcomsh-loader.php
		Version: 
		Author: 


== Elements Usage ==
	
	container : 1
		button : 1
		container : 7
		divider : 1
		heading : 13
		icon-box : 1
		image : 1
		social-icons : 2
		testimonial : 8
		text-editor : 2
	page : 21
		button : 62
		container : 180
		divider : 54
		heading : 431
		icon : 15
		icon-box : 21
		icon-list : 3
		image : 262
		image-box : 15
		menu-anchor : 9
		nested-accordion : 1
		shortcode : 1
		spacer : 204
		testimonial : 8
		text-editor : 375
		toggle : 1
		video : 17
	section : 1
		image : 1
		text-editor : 1
	wp-post : 22
		button : 1
		container : 33
		divider : 12
		heading : 44
		html : 2
		icon-box : 1
		image : 67
		social-icons : 1
		spacer : 6
		table-of-contents : 1
		text-editor : 160
		video : 6
	wp-page : 21
		button : 18
		container : 401
		counter : 3
		divider : 20
		heading : 279
		icon : 8
		icon-box : 27
		icon-list : 2
		image : 147
		image-box : 22
		image-carousel : 2
		menu-anchor : 1
		nested-accordion : 1
		shortcode : 3
		spacer : 149
		testimonial : 8
		text-editor : 282
		video : 50


== Settings ==
	
	allow_tracking: yes
	unfiltered_files_upload: 1
	load_fa4_shim: yes


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	
	woocommerce: Active


== Elementor Experiments ==
	Inline Font Icons: Active by default
	Additional Custom Breakpoints: Active by default
	Container: Active by default
	Upgrade Swiper Library: Active by default
	Nested Elements Performance: Active by default
	Optimized Markup: Inactive by default
	Plugin Onboarding: Active by default
	CSS Smooth Scroll: Active by default
	Default to New Theme Builder: Active by default
	Elementor Home Screen: Active by default
	Landing Pages: Active by default
	Nested Elements: Active by default
	Editor Top Bar: Active by default
	Pages Panel: Inactive by default
	Element Caching: Active by default
	Link In Bio: Active by default
	Floating Buttons: Active by default
	Elementor Editor Events: Inactive by default
	Atomic Widgets: Inactive by default
	Global Classes: Inactive by default
	Launchpad Checklist: Inactive by default
	Menu: Active by default


== Log ==
	
PHP: showing 20 of 20PHP: 2024-05-28 01:04:47 [notice X 4][/srv/htdocs/wp-content/plugins/elementor/includes/conditions.php::87] Undefined index: background_color_b [array (
  'trace' => '
#0: /srv/htdocs/wp-content/plugins/elementor/includes/conditions.php(87): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /srv/htdocs/wp-content/plugins/elementor/includes/conditions.php(83): Elementor\Conditions :: check()
#2: /srv/htdocs/wp-content/plugins/elementor/includes/base/controls-stack.php(1438): Elementor\Conditions :: check()
#3: /srv/htdocs/wp-content/plugins/elementor/includes/base/controls-stack.php(1222): Elementor\Controls_Stack -> is_control_visible()
#4: /srv/htdocs/wp-content/plugins/elementor/includes/base/controls-stack.php(1263): Elementor\Controls_Stack -> get_active_settings()
',
)]
PHP: 2024-05-28 01:04:47 [notice X 4][/srv/htdocs/wp-content/plugins/elementor/includes/conditions.php::87] Undefined index: background_color [array (
  'trace' => '
#0: /srv/htdocs/wp-content/plugins/elementor/includes/conditions.php(87): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /srv/htdocs/wp-content/plugins/elementor/includes/conditions.php(83): Elementor\Conditions :: check()
#2: /srv/htdocs/wp-content/plugins/elementor/includes/base/controls-stack.php(1438): Elementor\Conditions :: check()
#3: /srv/htdocs/wp-content/plugins/elementor/includes/base/controls-stack.php(1222): Elementor\Controls_Stack -> is_control_visible()
#4: /srv/htdocs/wp-content/plugins/elementor/includes/elements/section.php(1565): Elementor\Controls_Stack -> get_active_settings()
',
)]
PHP: 2024-05-28 01:04:47 [notice X 4][/srv/htdocs/wp-content/plugins/elementor/includes/conditions.php::87] Undefined index: background_color_b [array (
  'trace' => '
#0: /srv/htdocs/wp-content/plugins/elementor/includes/conditions.php(87): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /srv/htdocs/wp-content/plugins/elementor/includes/conditions.php(83): Elementor\Conditions :: check()
#2: /srv/htdocs/wp-content/plugins/elementor/includes/base/controls-stack.php(1438): Elementor\Conditions :: check()
#3: /srv/htdocs/wp-content/plugins/elementor/includes/base/controls-stack.php(1222): Elementor\Controls_Stack -> is_control_visible()
#4: /srv/htdocs/wp-content/plugins/elementor/includes/elements/section.php(1565): Elementor\Controls_Stack -> get_active_settings()
',
)]
PHP: 2024-05-28 01:08:40 [notice X 1][/srv/htdocs/wp-content/plugins/elementor/modules/history/revisions-manager.php::363] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-06-04 08:43:39 [warning X 4676][/srv/htdocs/wp-content/plugins/elementor/includes/conditions.php::87] Undefined array key &quot;background_color&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-06-04 10:30:26 [warning X 132][/srv/htdocs/wp-content/plugins/elementor/includes/conditions.php::87] Undefined array key &quot;background_color&quot; [array (
  'trace' => '
#0: /srv/htdocs/wp-content/plugins/elementor/includes/conditions.php(87): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /srv/htdocs/wp-content/plugins/elementor/includes/conditions.php(83): Elementor\Conditions :: check()
#2: /srv/htdocs/wp-content/plugins/elementor/includes/base/controls-stack.php(1438): Elementor\Conditions :: check()
#3: /srv/htdocs/wp-content/plugins/elementor/includes/base/controls-stack.php(1222): Elementor\Controls_Stack -> is_control_visible()
#4: /srv/htdocs/wp-content/plugins/elementor/includes/base/controls-stack.php(1263): Elementor\Controls_Stack -> get_active_settings()
',
)]
PHP: 2024-06-04 10:30:45 [warning X 84][/srv/htdocs/wp-content/plugins/elementor/includes/conditions.php::87] Undefined array key &quot;background_color_b&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-06-12 13:23:34 [warning X 8][/srv/htdocs/wp-content/plugins/elementor/includes/conditions.php::87] Undefined array key &quot;background_color_b&quot; [array (
  'trace' => '
#0: /srv/htdocs/wp-content/plugins/elementor/includes/conditions.php(87): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /srv/htdocs/wp-content/plugins/elementor/includes/conditions.php(83): Elementor\Conditions :: check()
#2: /srv/htdocs/wp-content/plugins/elementor/includes/base/controls-stack.php(1438): Elementor\Conditions :: check()
#3: /srv/htdocs/wp-content/plugins/elementor/includes/base/controls-stack.php(1222): Elementor\Controls_Stack -> is_control_visible()
#4: /srv/htdocs/wp-content/plugins/elementor/includes/base/controls-stack.php(1263): Elementor\Controls_Stack -> get_active_settings()
',
)]
PHP: 2024-06-12 13:23:35 [warning X 8][/srv/htdocs/wp-content/plugins/elementor/includes/conditions.php::87] Undefined array key &quot;background_color&quot; [array (
  'trace' => '
#0: /srv/htdocs/wp-content/plugins/elementor/includes/conditions.php(87): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /srv/htdocs/wp-content/plugins/elementor/includes/conditions.php(83): Elementor\Conditions :: check()
#2: /srv/htdocs/wp-content/plugins/elementor/includes/base/controls-stack.php(1438): Elementor\Conditions :: check()
#3: /srv/htdocs/wp-content/plugins/elementor/includes/base/controls-stack.php(1222): Elementor\Controls_Stack -> is_control_visible()
#4: /srv/htdocs/wp-content/plugins/elementor/includes/elements/section.php(1565): Elementor\Controls_Stack -> get_active_settings()
',
)]
PHP: 2024-06-12 13:23:35 [warning X 8][/srv/htdocs/wp-content/plugins/elementor/includes/conditions.php::87] Undefined array key &quot;background_color_b&quot; [array (
  'trace' => '
#0: /srv/htdocs/wp-content/plugins/elementor/includes/conditions.php(87): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /srv/htdocs/wp-content/plugins/elementor/includes/conditions.php(83): Elementor\Conditions :: check()
#2: /srv/htdocs/wp-content/plugins/elementor/includes/base/controls-stack.php(1438): Elementor\Conditions :: check()
#3: /srv/htdocs/wp-content/plugins/elementor/includes/base/controls-stack.php(1222): Elementor\Controls_Stack -> is_control_visible()
#4: /srv/htdocs/wp-content/plugins/elementor/includes/elements/section.php(1565): Elementor\Controls_Stack -> get_active_settings()
',
)]
PHP: 2024-07-23 00:56:38 [notice X 156][/srv/htdocs/wp-content/plugins/elementor/includes/base/controls-stack.php::229] hexdec(): Passing null to parameter #1 ($hex_string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-08-08 01:46:46 [error X 1][/srv/htdocs/wp-content/plugins/elementor-pro/modules/theme-builder/module.php::271] Uncaught Error: Class &quot;Elementor\Core\App\App&quot; not found in /srv/htdocs/wp-content/plugins/elementor-pro/modules/theme-builder/module.php:271
Stack trace:
#0 /wordpress/core/6.6.1/wp-includes/class-wp-hook.php(324): ElementorPro\Modules\ThemeBuilder\Module-&gt;hide_admin_app_submenu(Array)
#1 /wordpress/core/6.6.1/wp-includes/plugin.php(205): WP_Hook-&gt;apply_filters(Array, Array)
#2 /wordpress/core/6.6.1/wp-admin/includes/menu.php(270): apply_filters(&#039;add_menu_classe...&#039;, Array)
#3 /wordpress/core/6.6.1/wp-admin/includes/menu.php(383): add_menu_classes(Array)
#4 /wordpress/core/6.6.1/wp-admin/menu.php(412): require_once(&#039;/wordpress/core...&#039;)
#5 /wordpress/core/6.6.1/wp-admin/admin.php(158): require(&#039;/wordpress/core...&#039;)
#6 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-08-09 04:56:56 [warning X 2][/srv/htdocs/wp-content/plugins/elementor/modules/history/revisions-manager.php::363] Undefined array key &quot;editor_post_id&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-08-09 05:16:09 [warning X 89][/srv/htdocs/wp-content/plugins/elementor/includes/managers/image.php::113] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-10-17 01:34:21 [warning X 1][/srv/htdocs/wp-content/plugins/elementor-pro/modules/forms/classes/ajax-handler.php::76] Undefined array key &quot;form_id&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-10-29 04:09:23 [notice X 35][/srv/htdocs/wp-content/plugins/elementor/core/upgrade/manager.php::70] version_compare(): Passing null to parameter #1 ($version1) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /srv/htdocs/wp-content/plugins/elementor/core/upgrade/manager.php(70): class type version_compare()
#2: /srv/htdocs/wp-content/plugins/elementor-pro/modules/forms/module.php(228): Elementor\Core\Upgrade\Manager :: install_compare()
#3: /wordpress/core/6.6.2/wp-includes/class-wp-hook.php(324): ElementorPro\Modules\Forms\Module -> register_submissions_admin_notice()
#4: /wordpress/core/6.6.2/wp-includes/class-wp-hook.php(348): WP_Hook -> apply_filters()
',
)]
PHP: 2024-10-29 04:11:29 [notice X 167][/srv/htdocs/wp-content/plugins/elementor/core/upgrade/manager.php::70] version_compare(): Passing null to parameter #1 ($version1) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-11-13 22:18:24 [notice X 153][/srv/htdocs/wp-content/plugins/elementor/core/upgrade/manager.php::70] version_compare(): Passing null to parameter #1 ($version1) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /srv/htdocs/wp-content/plugins/elementor/core/upgrade/manager.php(70): class type version_compare()
#2: /srv/htdocs/wp-content/plugins/elementor-pro/modules/forms/module.php(228): Elementor\Core\Upgrade\Manager :: install_compare()
#3: /wordpress/core/6.7/wp-includes/class-wp-hook.php(324): ElementorPro\Modules\Forms\Module -> register_submissions_admin_notice()
#4: /wordpress/core/6.7/wp-includes/class-wp-hook.php(348): WP_Hook -> apply_filters()
',
)]
PHP: 2024-11-22 00:27:04 [notice X 63][/srv/htdocs/wp-content/plugins/elementor/core/upgrade/manager.php::70] version_compare(): Passing null to parameter #1 ($version1) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /srv/htdocs/wp-content/plugins/elementor/core/upgrade/manager.php(70): class type version_compare()
#2: /srv/htdocs/wp-content/plugins/elementor-pro/modules/forms/module.php(228): Elementor\Core\Upgrade\Manager :: install_compare()
#3: /wordpress/core/6.7.1/wp-includes/class-wp-hook.php(324): ElementorPro\Modules\Forms\Module -> register_submissions_admin_notice()
#4: /wordpress/core/6.7.1/wp-includes/class-wp-hook.php(348): WP_Hook -> apply_filters()
',
)]
PHP: 2024-11-24 10:11:42 [notice X 1][/srv/htdocs/wp-content/plugins/elementor-pro/core/connect/apps/activate.php::76] trim(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 14 of 14JS: 2024-05-28 01:11:49 [error X 1][https://yogacomcainara.com/wp-content/plugins/elementor/assets/js/packages/editor-documents/editor-documents.min.js?ver=3.22.0-dev1:1:1686] Cannot read properties of null (reading &#039;config&#039;) 
JS: 2024-08-09 07:16:01 [error X 6][https://yogacomcainara.com/wp-content/plugins/elementor/assets/js/common.min.js?ver=3.23.0-dev6:3:97101] Cannot read properties of undefined (reading &#039;toLowerCase&#039;) 
JS: 2024-08-09 07:16:07 [error X 1][https://yogacomcainara.com/wp-content/plugins/elementor/assets/js/common.min.js?ver=3.23.0-dev6:3:89737] Cannot read properties of undefined (reading &#039;$activeItem&#039;) 
JS: 2024-08-27 04:53:22 [error X 1][https://yogacomcainara.com/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=3.23.3:2:21897] this.$element.sticky is not a function 
JS: 2024-09-03 02:55:04 [error X 3][https://yogacomcainara.com/wp-content/plugins/elementor/assets/js/d91e4d7f57d57af2aab9.bundle.min.js:2:7789] Cannot read properties of null (reading &#039;dataset&#039;) 
JS: 2024-09-03 02:55:41 [error X 3][https://yogacomcainara.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.24.0-dev1:3:837847] Cannot read properties of undefined (reading &#039;localized&#039;) 
JS: 2024-10-10 06:32:21 [error X 10][https://yogacomcainara.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.24.0-dev3:3:779324] Cannot read properties of null (reading &#039;toLowerCase&#039;) 
JS: 2024-10-14 02:07:41 [error X 1][https://yogacomcainara.com/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=3.24.4:2:12630] Failed to execute &#039;observe&#039; on &#039;IntersectionObserver&#039;: parameter 1 is not of type &#039;Element&#039;. 
JS: 2024-10-14 05:02:08 [error X 2][https://yogacomcainara.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.24.0-dev3:3:714406] this.model.isValidChild is not a function 
JS: 2024-10-17 01:38:43 [error X 1][https://yogacomcainara.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.25.0-dev2:3:543212] Cannot read properties of undefined (reading &#039;have_a_look&#039;) 
JS: 2024-10-20 09:36:19 [error X 326][https://yogacomcainara.com/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.8.2:2:14799] Cannot read properties of null (reading &#039;clone&#039;) 
JS: 2024-10-20 09:36:20 [error X 5][https://yogacomcainara.com/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.8.2:2:19552] Cannot read properties of null (reading &#039;changestop&#039;) 
JS: 2024-10-29 03:17:28 [error X 1][https://yogacomcainara.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.25.0-dev3:3:874299] Cannot convert undefined or null to object 
JS: 2024-11-22 01:53:34 [error X 2][https://yogacomcainara.com/wp-content/plugins/elementor/assets/js/common-modules.min.js?ver=3.25.0-dev3:2:56144] Model.isValidChild() should be implemented, please provide &#039;isValidChild&#039; functionality. 

Log: showing 8 of 82024-11-28 05:41:19 [info] elementor-pro::elementor_pro_updater Started 
2024-11-28 05:41:19 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-11-28 05:41:19 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-11-28 05:41:19 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.0-dev13',
  'to' => '3.25.4',
)]
2024-11-28 05:41:45 [info] elementor::elementor_updater Started 
2024-11-28 05:41:45 [info] Elementor/Upgrades - _on_each_version Start  
2024-11-28 05:41:48 [info] Elementor/Upgrades - _on_each_version Finished 
2024-11-28 05:41:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.0-dev13',
  'to' => '3.26.0-dev2',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	LearnDash LMS - Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hello @CainaraBurton,

Thank you for reaching out! 🙏 

### ⛔ 🧩 Please note that while we do welcome bug reports, we can't provide support for 3rd-party themes/plugins/add-ons/extensions.

If your issue is specifically happening only when you're using a feature from a 3rd-party software, or only when the 3rd-party software is active, you'll need to contact the support for that specific software or its developers.

To make sure the issue is not being caused by Elementor and isolate this conflict please try these **Troubleshooting steps**:

#### ⚠️ Make a Backup of your website before proceeding, and if possible do it in a staging environment!

1. 🆕 **Stay Up-to-date:** Make sure you are using the most recent and stable versions of [Elementor](https://wordpress.org/plugins/elementor/#developers), [Elementor Pro](https://elementor.com/pro/changelog/), [WordPress](https://wordpress.org/download/releases/), and your theme.

2. 🔬 **Isolate the problem:** Deactivate all of your plugins (except Elementor/Pro), and temporarily change your WordPress theme to [Hello theme](https://wordpress.org/themes/hello-elementor/). If this solves the problem, gradually activate your plugins and theme one by one, until you spot the conflicting plugin or theme.

3. 🗑️ **Clear the cache:** Clear all levels of cache, including but not limited to **Server cache**, **WordPress (optimization plugin) cache**, **CDN cache**, and **Browser cache**. Also, try visiting the front page of your website in **incognito/private** mode.

4. 📋 **Meet the Requirements:** Make sure the server resources allocated to your site and WordPress installation meet our [Requirements](https://elementor.com/help/requirements/). 
    - To check this information go to your WordPress `Dashboard` > `Elementor` > `System info` [learn how to copy it here](https://elementor.com/help/hare-my-system-info/). We can't accept issues without it.

5. 🧩 **Contact 3rd-party support:** Reach out to the 3rd-party addon support and ask for assistance to ensure compatibility with the latest version of Elementor. 

Regards
