### ISSUE TITLE
⛔ 🚀 Icon List Widget: Links within inline list content are stacking

### ISSUE THREAD

**Issue by maxms** [elementor/elementor#29518]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Icon List widgets with inline display and links within the content are showing as stacked as of approximately beginning of Nov. We've seen it on two sites now. The offending css in the widget styles seems to be:
```css
.elementor-widget .elementor-icon-list-item, .elementor-widget .elementor-icon-list-item a {
    display: flex;
}
```

I've fixed temporarily on each widget with:
```css
selector .elementor-icon-list-text a {
    display: inline;
}
```

What it should look like:
<img width="1089" alt="Screenshot 2024-12-06 at 9 23 34 AM" src="https://github.com/user-attachments/assets/1d078a6a-36e9-440e-874d-0359e3db1c50">

What it looked like before my fix:
![image](https://github.com/user-attachments/assets/7a005186-e73e-442b-a4ad-fd7e3b648d94)

### Steps to reproduce

1. Add an icon list widget
2. Include multiple links in the item Text field or use a multiple result variable such as "Post Terms"
<img width="278" alt="Screenshot 2024-12-06 at 9 26 41 AM" src="https://github.com/user-attachments/assets/7a73f8cb-3ec7-4c9f-99c0-5aa86e0076f8">
<img width="287" alt="Screenshot 2024-12-06 at 9 26 22 AM" src="https://github.com/user-attachments/assets/c1e83e22-6650-4e92-867c-8a26c39a280d">

3. View widget on front end

### Expected behavior

Links should be inline with the icon and text.

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt


== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v8.0.39-30
	PHP Version: 8.2.26
	PHP Memory Limit: 768M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.7.1
	Site URL: https://getzwell.com
	Home URL: https://getzwell.com
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 256M
	Max Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: en_US
	Timezone: America/Los_Angeles
	Debug Mode: Inactive

== Theme ==
	Name: Astra Child
	Version: 2.0.1.1567731926
	Author: Brainstorm Force
	Child Theme: Yes
	Parent Theme Name: Astra
	Parent Theme Version: 4.8.7
	Parent Theme Author: Brainstorm Force

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36

== Active Plugins ==
	Admin Menu Editor Pro
		Version: 2.26.1
		Author: Janis Elsts

	All-in-One WP Migration
		Version: 7.87
		Author: ServMask

	Classic Editor
		Version: 1.6.7
		Author: WordPress Contributors

	Custom Icons for Elementor
		Version: 0.3.4
		Author: Michael Bourne

	Elementor
		Version: 3.25.10
		Author: Elementor.com

	Elementor Pro
		Version: 3.25.4
		Author: Elementor.com

	Essential Addons for Elementor
		Version: 6.0.11
		Author: WPDeveloper

	Essential Addons for Elementor - Pro
		Version: 6.0.9
		Author: WPDeveloper

	GTM4WP - A Google Tag Manager (GTM) plugin for WordPress
		Version: 1.20.2
		Author: Thomas Geiger

	Head & Footer Code
		Version: 1.3.7
		Author: Aleksandar Urošević

	Jetpack
		Version: 14.1
		Author: Automattic

	MC4WP: Mailchimp for WordPress
		Version: 4.9.19
		Author: ibericode

	PrettyLinks
		Version: 3.6.14
		Author: Pretty Links

	Redirection
		Version: 5.5.1
		Author: John Godley

	Relevanssi
		Version: 4.24.2
		Author: Mikko Saari

	Secure Custom Fields
		Version: 6.3.10.2
		Author: WordPress.org

	Security Optimizer
		Version: 1.5.7
		Author: SiteGround

	Site Kit by Google
		Version: 1.141.0
		Author: Google

	Spectra
		Version: 2.17.0
		Author: Brainstorm Force

	Speed Optimizer
		Version: 7.7.1
		Author: SiteGround

	Split Test For Elementor
		Version: 1.8.2
		Author: Rocket Elements

	SVG Support
		Version: 2.5.8
		Author: Benbodhi

	Ultimate Addons for Elementor
		Version: 1.37.2
		Author: Brainstorm Force

	User Role Editor
		Version: 4.64.3
		Author: Vladimir Garagulya

	Virtual Robots.txt
		Version: 1.10
		Author: Marios Alexandrou

	WP Activity Log
		Version: 5.2.2
		Author: Melapress

	Yoast SEO
		Version: 24.0
		Author: Team Yoast


== Features ==
	Custom Fonts: 0
	Custom Icons: 1

== Integrations ==
	
	recaptcha_v3: Active


== Elementor Experiments ==
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Additional Custom Breakpoints: Active by default
	Container: Inactive by default
	Upgrade Swiper Library: Active by default
	Nested Elements Performance: Active by default
	Optimized Control Loading: Active by default
	Optimized Markup: Inactive by default
	Conditionally load Swiper CSS files: Inactive by default
	Plugin Onboarding: Active by default
	CSS Smooth Scroll: Active by default
	Default to New Theme Builder: Active by default
	Elementor Home Screen: Active by default
	Landing Pages: Active by default
	Nested Elements: Active by default
	Editor Top Bar: Active by default
	Pages Panel: Inactive by default
	Element Caching: Inactive by default
	Link In Bio: Active by default
	Floating Buttons: Active by default
	Elementor Editor Events: Inactive by default
	Atomic Widgets: Inactive by default
	Launchpad Checklist: Inactive by default
	Menu: Inactive by default


== Log ==
	
Log: showing 20 of 392024-11-18 11:36:00 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.25.6',
  'to' => '3.25.7',
)]
2024-11-19 01:29:34 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.25.7',
  'to' => '3.25.8',
)]
2024-11-19 01:30:52 [info] elementor::elementor_updater Started 
2024-11-19 01:30:52 [info] Elementor/Upgrades - _on_each_version Start  
2024-11-19 01:30:52 [info] Elementor/Upgrades - _on_each_version Finished 
2024-11-19 01:30:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.25.7',
  'to' => '3.25.8',
)]
2024-11-20 11:36:12 [info] elementor::elementor_updater Started 
2024-11-20 11:36:12 [info] Elementor/Upgrades - _on_each_version Start  
2024-11-20 11:36:12 [info] Elementor/Upgrades - _on_each_version Finished 
2024-11-20 11:36:12 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.25.8',
  'to' => '3.25.9',
)]
2024-11-20 11:36:12 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.25.8',
  'to' => '3.25.9',
)]
2024-11-20 13:29:32 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.25.3',
  'to' => '3.25.4',
)]
2024-11-20 13:29:47 [info] elementor-pro::elementor_pro_updater Started 
2024-11-20 13:29:47 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-11-20 13:29:47 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-11-20 13:29:47 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.25.3',
  'to' => '3.25.4',
)]
2024-11-25 09:39:57 [info] elementor::elementor_updater Started 
2024-11-25 09:39:57 [info] Elementor/Upgrades - _on_each_version Start  
2024-11-25 09:39:57 [info] Elementor/Upgrades - _on_each_version Finished 
2024-11-25 09:39:57 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.25.9',
  'to' => '3.25.10',
)]

PHP: showing 3 of 3PHP: 2024-11-25 09:41:31 [notice X 5][../elementor-pro/modules/screenshots/module.php::33] Function utf8_decode() is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-11-26 10:46:43 [warning X 1][../elementor/includes/managers/image.php::113] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-11-27 12:37:59 [error X 5][../elementor-pro/modules/screenshots/module.php::229] Uncaught WpOrg\Requests\Exception\Http\Status403: 403 Forbidden in ../elementor-pro/modules/screenshots/module.php:229
Stack trace:
#0 ../elementor-pro/modules/screenshots/module.php(264): ElementorPro\Modules\Screenshots\Module->is_screenshot_proxy_mode(Array)
#1 ../elementor/core/base/module.php(85): ElementorPro\Modules\Screenshots\Module->__construct()
#2 ../elementor-pro/core/modules-manager.php(98): Elementor\Core\Base\Module::instance()
#3 ../elementor-pro/plugin.php(366): ElementorPro\Core\Modules_Manager->__construct()
#4 ../wp-includes/class-wp-hook.php(324): ElementorPro\Plugin->on_elementor_init('')
#5 ../wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#6 ../wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#7 ../elementor/includes/plugin.php(685): do_action('elementor/init')
#8 ../wp-includes/class-wp-hook.php(324): Elementor\Plugin->init('')
#9 ../wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#10 ../wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#11 ../wp-settings.php(704): do_action('init')
#12 ../wp-config.php(84): require_once('/home/customer/...')
#13 ../wp-load.php(50): require_once('/home/customer/...')
#14 ../wp-blog-header.php(13): require_once('/home/customer/...')
#15 ../index.php(17): require('/home/customer/...')
#16 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Custom Icons for Elementor: Compatibility not specified
	Elementor Pro: Compatibility not specified
	Essential Addons for Elementor: Compatibility not specified
	Essential Addons for Elementor - Pro: Compatibility not specified
	Split Test For Elementor: Compatibility not specified
	Ultimate Addons for Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hi, @maxms,

Thank you for reaching out! 🙏 

### ⛔ After reviewing your report we concluded this is not a bug caused by Elementor. The feature you're referring to is not yet supported.

The Icon List widget has an option to switch from list to inline exactly to address this necessity. The widget was not built with the intention of adding several links inside each item's text field. This is not the intended use for this widget.

If you think this should be an Elementor feature, please submit a new [🚀 Feature Request](https://github.com/orgs/elementor/discussions/new?category=feature-request), and we will consider it in the future if there is enough demand (votes) from other users.

Kind regards
