### ISSUE TITLE
Elementor stuck on loading icon

### ISSUE THREAD

**Issue by ssunner23** [elementor/elementor#29553]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

when editing a page my elementor is showing a loading icon and keeps loading for hours and doesnt work its stuck
i have deactivated the plugin and reactivated still no luck
<img width="455" alt="Screenshot 2024-12-10 at 18 33 48" src="https://github.com/user-attachments/assets/0cc533c5-3955-4507-aead-226c86d6bb26">

### Steps to reproduce

clicking on edit page with elementor and its stuck loading screenshot provided about

### Expected behavior

to be able to edit in elementor

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
== Server Environment ==
	Operating System: Linux
	Software: nginx
	MySQL version: MariaDB Server v10.11.10-MariaDB-log
	PHP Version: 8.2.26
	PHP Memory Limit: 512M
	PHP Max Input Vars: 6144
	PHP Max Post Size: 2047M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.7.1
	Site URL: https://ecom-deliciously-deepest-dreamer.wpcomstaging.com
	Home URL: https://ecom-deliciously-deepest-dreamer.wpcomstaging.com
	WP Multisite: No
	Max Upload Size: 2 GB
	Memory limit: 512M
	Max Memory limit: 512M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en_GB
	Timezone: Europe/London
	
	Debug Mode: Inactive

== Theme ==
	Name: Big Store
	Version: 1.7.8
	Author: ThemeHunk
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en-GB


== Active Plugins ==
	Advanced Product Fields for WooCommerce
		Version: 1.6.12
		Author: StudioWombat

	Advance Product Search
		Version: 1.2.7
		Author: ThemeHunk

	Akismet Anti-spam: Spam Protection
		Version: 5.3.5
		Author: Automattic - Anti-spam Team

	AutomateWoo
		Version: 6.1.3
		Author: WooCommerce

	Blaze Ads
		Version: 0.5.2
		Author: Automattic

	Classic Editor
		Version: 1.6.7
		Author: WordPress Contributors

	Classic Widgets
		Version: 0.3
		Author: WordPress Contributors

	Easy Mega Menu Plus
		Version: 1.1.1
		Author: Themehunk

	Elementor
		Version: 3.26.0-dev4
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.3
		Author: Elementor.com

	Envato Elements
		Version: 2.0.15
		Author: Envato

	Facebook for WooCommerce
		Version: 3.3.1
		Author: Facebook

	Google Analytics for WooCommerce
		Version: 2.1.8
		Author: WooCommerce

	Google for WooCommerce
		Version: 2.9.1
		Author: WooCommerce

	Gutenberg
		Version: 19.7.0
		Author: Gutenberg Team

	Image Optimizer - Compress, Resize and Optimize Images
		Version: 1.6.1
		Author: Elementor.com

	Jetpack
		Version: 14.2-a.1
		Author: Automattic

	Layout Grid
		Version: 1.8.4
		Author: Automattic

	Lead Form Builder
		Version: 1.9.8
		Author: ThemeHunk

	MailPoet
		Version: 5.5.0
		Author: MailPoet

	MailPoet Premium
		Version: 5.5.0
		Author: MailPoet

	MetaSlider
		Version: 3.93.0
		Author: MetaSlider

	Newsletter
		Version: 8.6.4
		Author: Stefano Lissa & The Newsletter Team

	Page Optimize
		Version: 0.5.6
		Author: Automattic

	Pinterest for WooCommerce
		Version: 1.4.13
		Author: WooCommerce

	Plugin for Google Reviews
		Version: 5.0
		Author: RichPlugins <support@richplugins.com>

	ThemeHunk Customizer
		Version: 2.7.9
		Author: ThemeHunk

	TH Variation Swatches
		Version: 1.3.2
		Author: ThemeHunk

	TikTok
		Version: 1.2.10
		Author: TikTok

	Woo AI
		Version: 0.6.0
		Author: WooCommerce

	WooCommerce
		Version: 9.4.3
		Author: Automattic

	WooCommerce Back In Stock Notifications
		Version: 2.0.6
		Author: Woo

	WooCommerce Brands
		Version: 1.7.7
		Author: WooCommerce

	WooCommerce Gift Cards
		Version: 2.1.1
		Author: Woo

	WooCommerce Min/Max Quantities
		Version: 5.0.4
		Author: Woo

	WooCommerce Product Add-Ons
		Version: 7.2.1
		Author: Woo

	WooCommerce Product Bundles
		Version: 8.2.1
		Author: Woo

	WooCommerce Product Recommendations
		Version: 4.1.2
		Author: Woo

	WooCommerce Shipment Tracking
		Version: 2.5.3
		Author: WooCommerce

	WooCommerce Shipping & Tax
		Version: 2.8.4
		Author: WooCommerce

	WooPayments
		Version: 8.6.0
		Author: WooCommerce

	WP Popup Builder
		Version: 1.3.6
		Author: ThemeHunk

	YITH WooCommerce Compare
		Version: 2.44.0
		Author: YITH

	YITH WooCommerce Wishlist
		Version: 4.0.1
		Author: YITH


== Must-Use Plugins ==
	wpcomsh-loader.php
		Version: 
		Author: 


== Elementor Experiments ==
	Inline Font Icons: Active by default
	Additional Custom Breakpoints: Active by default
	Container: Active by default
	Upgrade Swiper Library: Active by default
	Nested Elements Performance: Active by default
	Optimized Markup: Inactive by default
	Plugin Onboarding: Active by default
	CSS Smooth Scroll: Active by default
	Elementor Home Screen: Active by default
	Landing pages: Active by default
	Nested Elements: Active by default
	Editor Top Bar: Active by default
	Pages Panel: Inactive by default
	Element Caching: Active by default
	Link In Bio: Active by default
	Floating Buttons: Active by default
	Elementor Editor Events: Inactive by default
	Atomic Widgets: Inactive by default
	Global Classes: Inactive by default
	Launchpad Checklist: Active by default


== Log ==
	
JS: showing 1 of 1JS: 2024-12-09 15:13:22 [error X 8][https://ecom-deliciously-deepest-dreamer.wpcomstaging.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.25.10:3:838648] Cannot read properties of undefined (reading 'localized') 

PHP: showing 2 of 2PHP: 2024-12-09 16:02:18 [warning X 1][/srv/htdocs/wp-content/plugins/elementor/modules/history/revisions-manager.php::363] Undefined array key "editor_post_id" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-12-10 17:28:33 [error X 1][/srv/htdocs/wp-content/plugins/elementor/includes/api.php::129] Uncaught Error: Call to a member function get_component() on null in /srv/htdocs/wp-content/plugins/elementor/includes/api.php:129
Stack trace:
#0 /srv/htdocs/wp-content/plugins/elementor/includes/api.php(85): Elementor\Api::get_site_key()
#1 /srv/htdocs/wp-content/plugins/elementor/includes/api.php(178): Elementor\Api::get_info_data()
#2 /srv/htdocs/wp-content/plugins/elementor/modules/promotions/module.php(53): Elementor\Api::get_promotion_widgets()
#3 /wordpress/core/6.7.1/wp-includes/class-wp-hook.php(324): Elementor\Modules\Promotions\Module->Elementor\Modules\Promotions\{closure}(Object(Elementor\Widgets_Manager))
#4 /wordpress/core/6.7.1/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#5 /wordpress/core/6.7.1/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /srv/htdocs/wp-content/plugins/elementor/includes/managers/widgets.php(146): do_action('elementor/widge...', Object(Elementor\Widgets_Manager))
#7 /srv/htdocs/wp-content/plugins/elementor/includes/managers/widgets.php(345): Elementor\Widgets_Manager->init_widgets()
#8 /srv/htdocs/wp-content/plugins/elementor/includes/elements/column.php(1038): Elementor\Widgets_Manager->get_widget_types('slides')
#9 /srv/htdocs/wp-content/plugins/elementor/includes/base/element-base.php(1502): Elementor\Element_Column->_get_default_child_type(Array)
#10 /srv/htdocs/wp-content/plugins/elementor/includes/base/element-base.php(369): Elementor\Element_Base->get_child_type(Array)
#11 /srv/htdocs/wp-content/plugins/elementor/includes/base/element-base.php(1547): Elementor\Element_Base->add_child(Array)
#12 /srv/htdocs/wp-content/plugins/elementor/includes/base/element-base.php(314): Elementor\Element_Base->init_children()
#13 /srv/htdocs/wp-content/plugins/elementor/core/files/css/post.php(225): Elementor\Element_Base->get_children()
#14 /srv/htdocs/wp-content/plugins/elementor/core/files/css/post.php(313): Elementor\Core\Files\CSS\Post->add_controls_stack_style_rules(Object(Elementor\Element_Column), Array, Array, Array, Array)
#15 /srv/htdocs/wp-content/plugins/elementor/core/files/css/post.php(297): Elementor\Core\Files\CSS\Post->render_element_styles(Object(Elementor\Element_Column))
#16 /srv/htdocs/wp-content/plugins/elementor/core/files/css/post.php(226): Elementor\Core\Files\CSS\Post->render_styles(Object(Elementor\Element_Column))
#17 /srv/htdocs/wp-content/plugins/elementor/core/files/css/post.php(313): Elementor\Core\Files\CSS\Post->add_controls_stack_style_rules(Object(Elementor\Element_Section), Array, Array, Array, Array)
#18 /srv/htdocs/wp-content/plugins/elementor/core/files/css/post.php(297): Elementor\Core\Files\CSS\Post->render_element_styles(Object(Elementor\Element_Section))
#19 /srv/htdocs/wp-content/plugins/elementor/core/files/css/post.php(226): Elementor\Core\Files\CSS\Post->render_styles(Object(Elementor\Element_Section))
#20 /srv/htdocs/wp-content/plugins/elementor/core/files/css/post.php(313): Elementor\Core\Files\CSS\Post->add_controls_stack_style_rules(Object(Elementor\Element_Column), Array, Array, Array, Array)
#21 /srv/htdocs/wp-content/plugins/elementor/core/files/css/post.php(297): Elementor\Core\Files\CSS\Post->render_element_styles(Object(Elementor\Element_Column))
#22 /srv/htdocs/wp-content/plugins/elementor/core/files/css/post.php(226): Elementor\Core\Files\CSS\Post->render_styles(Object(Elementor\Element_Column))
#23 /srv/htdocs/wp-content/plugins/elementor/core/files/css/post.php(313): Elementor\Core\Files\CSS\Post->add_controls_stack_style_rules(Object(Elementor\Element_Section), Array, Array, Array, Array)
#24 /srv/htdocs/wp-content/plugins/elementor/core/files/css/post.php(297): Elementor\Core\Files\CSS\Post->render_element_styles(Object(Elementor\Element_Section))
#25 /srv/htdocs/wp-content/plugins/elementor/core/files/css/post.php(178): Elementor\Core\Files\CSS\Post->render_styles(Object(Elementor\Element_Section))
#26 /srv/htdocs/wp-content/plugins/elementor/core/files/css/base.php(687): Elementor\Core\Files\CSS\Post->render_css()
#27 /srv/htdocs/wp-content/plugins/elementor/core/files/base.php(180): Elementor\Core\Files\CSS\Base->parse_content()
#28 /srv/htdocs/wp-content/plugins/elementor/core/files/css/base.php(133): Elementor\Core\Files\Base->update_file()
#29 /srv/htdocs/wp-content/plugins/elementor/core/files/css/base.php(229): Elementor\Core\Files\CSS\Base->update()
#30 /srv/htdocs/wp-content/plugins/elementor/core/files/css/post.php(201): Elementor\Core\Files\CSS\Base->enqueue()
#31 /srv/htdocs/wp-content/plugins/elementor/includes/frontend.php(695): Elementor\Core\Files\CSS\Post->enqueue()
#32 /wordpress/core/6.7.1/wp-includes/class-wp-hook.php(324): Elementor\Frontend->enqueue_styles('')
#33 /wordpress/core/6.7.1/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#34 /wordpress/core/6.7.1/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#35 /wordpress/core/6.7.1/wp-includes/script-loader.php(2272): do_action('wp_enqueue_scri...')
#36 /wordpress/core/6.7.1/wp-includes/class-wp-hook.php(324): wp_enqueue_scripts('')
#37 /wordpress/core/6.7.1/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#38 /wordpress/core/6.7.1/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#39 /wordpress/core/6.7.1/wp-includes/general-template.php(3064): do_action('wp_head')
#40 /srv/htdocs/wp-content/themes/big-store/header.php(24): wp_head()
#41 /wordpress/core/6.7.1/wp-includes/template.php(810): require_once('/srv/htdocs/wp-...')
#42 /wordpress/core/6.7.1/wp-includes/template.php(745): load_template('/srv/htdocs/wp-...', true, Array)
#43 /wordpress/core/6.7.1/wp-includes/general-template.php(48): locate_template(Array, true, true, Array)
#44 /srv/htdocs/wp-content/plugins/elementor/modules/page-templates/templates/header-footer.php(9): get_header()
#45 /wordpress/core/6.7.1/wp-includes/template-loader.php(106): include('/srv/htdocs/wp-...')
#46 /wordpress/core/6.7.1/wp-blog-header.php(19): require_once('/wordpress/core...')
#47 /wordpress/core/6.7.1/index.php(17): require('/wordpress/core...')
#48 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 14 of 142024-12-10 04:29:11 [info] elementor::elementor_updater Started 
2024-12-10 04:29:11 [info] Elementor/Upgrades - _on_each_version Start  
2024-12-10 04:29:11 [info] Elementor/Upgrades - _on_each_version Finished 
2024-12-10 04:29:11 [info] Elementor/Upgrades - _v_3_26_0 Start  
2024-12-10 04:29:11 [info] Elementor/Upgrades - _v_3_26_0 Finished 
2024-12-10 04:29:11 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.25.10',
  'to' => '3.26.0-dev3',
)]
2024-12-10 04:29:11 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.25.10',
  'to' => '3.26.0-dev3',
)]
2024-12-10 17:27:17 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.26.0-dev3',
  'to' => '3.26.0-dev4',
)]
2024-12-10 17:27:17 [info] elementor::elementor_updater Started 
2024-12-10 17:27:17 [info] Elementor/Upgrades - _on_each_version Start  
2024-12-10 17:27:17 [info] Elementor/Upgrades - _on_each_version Finished 
2024-12-10 17:27:17 [info] Elementor/Upgrades - _v_3_26_0 Start  
2024-12-10 17:27:17 [info] Elementor/Upgrades - _v_3_26_0 Finished 
2024-12-10 17:27:17 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.26.0-dev3',
  'to' => '3.26.0-dev4',
)]



== Elementor - Compatibility Tag ==
	
	Envato Elements: Incompatible
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by eimaz5** [comment]
I manage few elementor sites, all of them after upgraded to 3.26 has same loading issues
