### ISSUE TITLE
Can't load section from Magic button, can't update page.

### ISSUE THREAD

**Issue by phradion** [elementor/elementor#7674]
## Prerequisites
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description
Can not insert any section using the Magical button, it throws JS error in the console
See screenshot: https://cl.ly/2cbfabbdceaf

I get this error alot 
this.options.model.getTitle is not a function. (In \'this.options.model.getTitle()\', \'this.options.model.getTitle\' is undefined) 

After this point, other part of the editor still works, I can still insert my previously saved templates.

## Steps to reproduce
1. load Elementor Editor for any page
2. Click the blue MAGIC BUTTON
3. Choose any section from the list 
4. Click INSERT BUTTON
5. Console will throws js error and the insertion won't work. 

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

I have deactivated every single plugins that not required by the theme Monstroid 2 (theme also updated to the latest version).

I tried with the TwentySeven theme, still same problem but different JS error.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.25 (Debian)
	MySQL version: MySQL Community Server (GPL) v5.7.24
	PHP Version: 7.2.13
	PHP Max Input Vars: 1000
	PHP Max Post Size: 500M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Not connected (HTTP Error (503))

== WordPress Environment ==
	Version: 5.1.1
	Site URL: https://v3.botstar.com
	Home URL: https://v3.botstar.com
	WP Multisite: No
	Max Upload Size: 500 MB
	Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 7
	Debug Mode: Inactive

== Theme ==
	Name: Monstroid2 Child
	Version: 1.0.0
	Author: Zemez
	Child Theme: Yes
	Parent Theme Name: Monstroid2
	Parent Theme Version: 1.0.2
	Parent Theme Author: Zemez

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.5.10
		Author: Elementor.com

	Elementor Pro
		Version: 2.4.8
		Author: Elementor.com

	JetBlocks For Elementor
		Version: 1.1.5
		Author: Zemez

	JetBlog For Elementor
		Version: 2.1.11
		Author: Zemez

	Jet Data Importer
		Version: 1.2.1
		Author: Zemez

	Jet Elements For Elementor
		Version: 1.15.5
		Author: Zemez

	JetMenu
		Version: 1.5.8.1
		Author: Zemez

	Jet Plugins Wizard
		Version: 1.2.1
		Author: Zemez

	JetTabs For Elementor
		Version: 1.1.6
		Author: Zemez

	JetThemeCore
		Version: 1.1.8
		Author: Zemez

	JetTricks
		Version: 1.1.8
		Author: Zemez

	Kava Extra
		Version: 1.0.1
		Author: Zemez

	M2ThemeWizard
		Version: 1.0.0
		Author: Zemez


== Log ==
	: 
Log: showing 13 of 132019-02-20 19:20:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.3.8',
  'to' => '2.4.7',
)]
2019-03-03 04:59:19 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.3.1',
  'to' => '2.4.5',
)]
2019-03-06 18:01:09 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.7',
  'to' => '2.5.2',
)]
2019-03-06 18:07:37 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.5',
  'to' => '2.4.6',
)]
2019-03-06 18:07:40 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.5',
  'to' => '2.4.6',
)]
2019-03-07 10:47:53 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.2',
  'to' => '2.5.3',
)]
2019-03-07 10:48:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.6',
  'to' => '2.4.7',
)]
2019-03-11 18:40:19 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.3',
  'to' => '2.5.4',
)]
2019-03-12 09:23:13 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.4',
  'to' => '2.5.5',
)]
2019-03-19 17:51:14 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.5',
  'to' => '2.5.9',
)]
2019-03-21 16:03:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.7',
  'to' => '2.4.8',
)]
2019-03-21 19:39:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.3.1',
  'to' => '2.4.8',
)]
2019-03-30 11:02:36 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.9',
  'to' => '2.5.10',
)]

JS: showing 20 of 20JS: 2019-02-25 09:54:05 [error X 4][https://v3.botstar.com/wp-content/plugins/elementor/assets/js/editor-modules.js?ver=2.4.7:733:35] self.attributes[control.name].each is not a function 
JS: 2019-02-27 13:38:01 [error X 1][https://v3.botstar.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.4.7:2:19616] Cannot read property \'hoverIntent\' of undefined 
JS: 2019-02-27 13:38:30 [error X 3][https://v3.botstar.com/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,underscore,backbone,shortcode,utils,wp-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jqu&load%5B%5D=ery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable&ver=5.0.3:16:5345] Cannot read property \'hide_tablet\' of undefined 
JS: 2019-02-27 13:39:50 [error X 2][https://v3.botstar.com/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,underscore,backbone,shortcode,utils,wp-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jqu&load%5B%5D=ery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable&ver=5.0.3:16:5345] Cannot read property \'hide_mobile\' of undefined 
JS: 2019-03-02 21:39:16 [error X 31][https://v3.botstar.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.4.7:2:11097] this.options.model.getTitle is not a function 
JS: 2019-03-02 21:56:59 [error X 107][https://v3.botstar.com/wp-content/plugins/jet-tricks/assets/js/jet-tricks-frontend.js?ver=1.1.8:320:37] Cannot read property \'models\' of undefined 
JS: 2019-03-02 22:49:38 [error X 7][https://v3.botstar.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.4.7:2:11105] this.options.model.getTitle is not a function. (In \'this.options.model.getTitle()\', \'this.options.model.getTitle\' is undefined) 
JS: 2019-03-21 14:12:15 [error X 1][https://v3.botstar.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view1164\") has already been destroyed and cannot be used. 
JS: 2019-03-30 08:44:51 [error X 3][https://v3.botstar.com/wp-content/plugins/elementor/assets/js/common.min.js?ver=2.5.10:2:11105] Cannot convert undefined or null to object 

PHP: showing 6 of 6PHP: 2019-03-03 04:40:17 [error X 45][/var/www/html/wp-content/plugins/elementor/includes/managers/elements.php::81] Uncaught Error: Call to a member function get_default_args() on array in /var/www/html/wp-content/plugins/elementor/includes/managers/elements.php:81
Stack trace:
#0 /var/www/html/wp-content/plugins/elementor/core/base/document.php(652): Elementor\Elements_Manager->create_element_instance(Array)
#1 /var/www/html/wp-content/plugins/elementor/core/base/document.php(846): Elementor\Core\Base\Document->get_elements_raw_data(Array)
#2 /var/www/html/wp-content/plugins/elementor/core/base/document.php(518): Elementor\Core\Base\Document->save_elements(Array)
#3 /var/www/html/wp-content/plugins/elementor/core/documents-manager.php(503): Elementor\Core\Base\Document->save(Array)
#4 [internal function]: Elementor\Core\Documents_Manager->ajax_save(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#5 /var/www/html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#6 /var/www/html/wp-includes/class-wp-hook.php(286): [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-03-21 16:00:15 [error X 3][/var/www/html/wp-content/plugins/elementor/includes/managers/elements.php::81] Uncaught Error: Call to a member function get_default_args() on array in /var/www/html/wp-content/plugins/elementor/includes/managers/elements.php:81
Stack trace:
#0 /var/www/html/wp-content/plugins/elementor/core/base/document.php(664): Elementor\Elements_Manager->create_element_instance(Array)
#1 /var/www/html/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(196): Elementor\Core\Base\Document->get_elements_raw_data(Array, false)
#2 /var/www/html/wp-content/plugins/elementor/core/base/document.php(858): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document->get_elements_raw_data(Array)
#3 /var/www/html/wp-content/plugins/elementor/core/base/document.php(525): Elementor\Core\Base\Document->save_elements(Array)
#4 /var/www/html/wp-content/plugins/elementor/core/documents-manager.php(504): Elementor\Core\Base\Document->save(Array)
#5 [internal function]: Elementor\Core\Documents_Manager->ajax_save(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#6 /var/www/html/ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-03-21 19:32:08 [error X 3][/var/www/html/wp-content/plugins/elementor/includes/managers/elements.php::81] Uncaught Error: Call to a member function get_default_args() on array in /var/www/html/wp-content/plugins/elementor/includes/managers/elements.php:81
Stack trace:
#0 /var/www/html/wp-content/plugins/elementor/core/base/document.php(652): Elementor\Elements_Manager->create_element_instance(Array)
#1 /var/www/html/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(196): Elementor\Core\Base\Document->get_elements_raw_data(Array, false)
#2 /var/www/html/wp-content/plugins/elementor/core/base/document.php(846): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document->get_elements_raw_data(Array)
#3 /var/www/html/wp-content/plugins/elementor/core/base/document.php(518): Elementor\Core\Base\Document->save_elements(Array)
#4 /var/www/html/wp-content/plugins/elementor/core/documents-manager.php(503): Elementor\Core\Base\Document->save(Array)
#5 [internal function]: Elementor\Core\Documents_Manager->ajax_save(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#6 /var/www/html/ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-03-21 19:41:55 [notice X 2][/var/www/html/wp-content/plugins/elementor-pro/modules/posts/widgets/posts.php::31] Undefined index: posts_post_type [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-03-21 20:21:23 [error X 2][/var/www/html/wp-content/plugins/elementor/includes/managers/elements.php::81] Uncaught Error: Call to a member function get_default_args() on array in /var/www/html/wp-content/plugins/elementor/includes/managers/elements.php:81
Stack trace:
#0 /var/www/html/wp-content/plugins/elementor/core/base/document.php(664): Elementor\Elements_Manager->create_element_instance(Array)
#1 /var/www/html/wp-content/plugins/elementor/core/base/document.php(858): Elementor\Core\Base\Document->get_elements_raw_data(Array)
#2 /var/www/html/wp-content/plugins/elementor/core/base/document.php(525): Elementor\Core\Base\Document->save_elements(Array)
#3 /var/www/html/wp-content/plugins/elementor/core/documents-manager.php(504): Elementor\Core\Base\Document->save(Array)
#4 [internal function]: Elementor\Core\Documents_Manager->ajax_save(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#5 /var/www/html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#6 /var/www/html/wp-includes/class-wp-hook.php(286): [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-03-30 15:37:26 [error X 2][/var/www/html/wp-content/plugins/elementor/includes/managers/elements.php::81] Uncaught Error: Call to a member function get_default_args() on array in /var/www/html/wp-content/plugins/elementor/includes/managers/elements.php:81
Stack trace:
#0 /var/www/html/wp-content/plugins/elementor/core/base/document.php(665): Elementor\Elements_Manager->create_element_instance(Array)
#1 /var/www/html/wp-content/plugins/elementor/core/base/document.php(859): Elementor\Core\Base\Document->get_elements_raw_data(Array)
#2 /var/www/html/wp-content/plugins/elementor/core/base/document.php(526): Elementor\Core\Base\Document->save_elements(Array)
#3 /var/www/html/wp-content/plugins/elementor/core/documents-manager.php(504): Elementor\Core\Base\Document->save(Array)
#4 [internal function]: Elementor\Core\Documents_Manager->ajax_save(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#5 /var/www/html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#6 /var/www/html/wp-includes/class-wp-hook.php(286): [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

```
</details>

**Comment by shilo-ey** [comment]
Hi @phradion 

Magic button is not a native feature of Elementor and most likely origins from one of your addons.

Thanks.
