### ISSUE TITLE
Copy Pasting Elements from other pages causes 500 error.

### ISSUE THREAD

**Issue by aqib-git** [elementor/elementor#7702]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

## Description

Hi, I was trying to copy paste my Revolution Slider element from one page to another and at that time on saving the page I encountered 500 error. It happened to me only once but one of my client faces this issue often. 

You can find the stacktrace related to this issue in **System info Logs** for the date  **2019-03-29**.
  
As per the stacktrace it seems the post doesn't exist but how is that possible I created a new post and copy paste the element in new post and the post type was page.

## Steps to reproduce

1. Create a revolution slider on page and copy paste into another page.
2. On save it throws 500 error.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>

```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.34 (Unix) OpenSSL/1.0.2g
	MySQL version: mariadb.org binary distribution v5.7.23
	PHP Version: 7.2.13
	PHP Max Input Vars: 1000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.1.1
	Site URL: https://aqib.artbees.team
	Home URL: https://aqib.artbees.team
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Active

== Theme ==
	Name: JupiterX
	Version: 1.2.1
	Author: Artbees
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 5.7.10
		Author: Elliot Condon

	Customizer Export/Import
		Version: 0.9
		Author: The Beaver Builder Team

	Elementor
		Version: 2.5.10
		Author: Elementor.com

	Jet Elements For Elementor
		Version: 1.15.5
		Author: Zemez

	Jupiter X Core
		Version: 1.1.0
		Author: Artbees

	Jupiter X Pro
		Version: 1.0.0
		Author: Artbees

	Raven
		Version: 1.1.1
		Author: Artbees

	Slider Revolution
		Version: 5.4.8.3
		Author: ThemePunch

	WooCommerce
		Version: 3.5.7
		Author: Automattic

	WP File Manager
		Version: 4.4
		Author: mndpsingh287


== Log ==
	: 
JS: showing 17 of 17JS: 2019-02-21 05:24:08 [error X 12][https://aqib.artbees.team/wp-content/plugins/raven/assets/js/frontend.min.js?ver=1.0.5:1:39857] Cannot read property \'indexOf\' of null 
JS: 2019-03-04 09:00:53 [error X 5][https://aqib.artbees.team/wp-admin/post.php?post=261&action=elementor:2:5] Unexpected token < 
JS: 2019-03-04 09:01:01 [error X 1][https://aqib.artbees.team/wp-admin/post.php?post=261&action=elementor:2:1] j is not defined 
JS: 2019-03-04 09:01:01 [error X 1][https://aqib.artbees.team/wp-admin/post.php?post=261&action=elementor:2:1] jQ is not defined 
JS: 2019-03-04 09:01:02 [error X 1][https://aqib.artbees.team/wp-admin/post.php?post=261&action=elementor:2:1] jQu is not defined 
JS: 2019-03-04 09:01:02 [error X 1][https://aqib.artbees.team/wp-admin/post.php?post=261&action=elementor:2:1] jQue is not defined 
JS: 2019-03-04 09:01:04 [error X 1][https://aqib.artbees.team/wp-admin/post.php?post=261&action=elementor:2:8] d is not defined 
JS: 2019-03-04 09:01:04 [error X 2][https://aqib.artbees.team/wp-admin/post.php?post=261&action=elementor:2:8] Unexpected token do 
JS: 2019-03-04 09:01:05 [error X 1][https://aqib.artbees.team/wp-admin/post.php?post=261&action=elementor:2:8] doc is not defined 
JS: 2019-03-04 09:01:07 [error X 1][https://aqib.artbees.team/wp-admin/post.php?post=261&action=elementor:3:1] Unexpected end of input 
JS: 2019-03-04 09:01:11 [error X 1][https://aqib.artbees.team/wp-admin/post.php?post=261&action=elementor:2:24] f is not defined 
JS: 2019-03-04 09:01:12 [error X 1][https://aqib.artbees.team/wp-admin/post.php?post=261&action=elementor:2:24] fu is not defined 
JS: 2019-03-04 09:01:12 [error X 1][https://aqib.artbees.team/wp-admin/post.php?post=261&action=elementor:2:24] func is not defined 
JS: 2019-03-04 09:01:12 [error X 1][https://aqib.artbees.team/wp-admin/post.php?post=261&action=elementor:2:24] functi is not defined 
JS: 2019-03-04 09:01:12 [error X 5][https://aqib.artbees.team/wp-admin/post.php?post=261&action=elementor:2:32] Unexpected token ) 
JS: 2019-03-04 09:01:53 [error X 1][https://aqib.artbees.team/wp-admin/post.php?post=261&action=elementor:4:1] Unexpected token } 
JS: 2019-04-02 02:53:46 [error X 2][https://aqib.artbees.team/wp-content/plugins/elementor/assets/js/editor.js?ver=2.5.10:14547:18] Cannot read property \'html\' of undefined 

Log: showing 2 of 22019-02-21 05:26:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.5',
  'to' => '2.4.7',
)]
2019-03-29 10:39:13 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.7',
  'to' => '2.5.10',
)]

PHP: showing 2 of 2PHP: 2019-03-12 06:00:16 [notice X 77][/home/runcloud/webapps/aqib/wp-content/plugins/elementor/includes/controls/groups/image-size.php::196] Undefined index: image_custom_dimension [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-03-29 12:12:37 [error X 5][/home/runcloud/webapps/aqib/wp-content/plugins/elementor/core/documents-manager.php::470] Uncaught Error: Call to a member function is_built_with_elementor() on boolean in /home/runcloud/webapps/aqib/wp-content/plugins/elementor/core/documents-manager.php:470
Stack trace:
#0 [internal function]: Elementor\Core\Documents_Manager->ajax_save(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#1 /home/runcloud/webapps/aqib/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/runcloud/webapps/aqib/wp-includes/class-wp-hook.php(286): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#3 /home/runcloud/webapps/aqib/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#4 /home/runcloud/webapps/aqib/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#5 /home/runcloud/webapps/aqib/wp-admin/admin-ajax.php(167): do_action('wp_ajax_element...')
#6 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
```
</details>

**Comment by shilo-ey** [comment]
Hi @aqib-git 

Thanks for your feedback.

We cannot replicate your issue.

Revolution slider is not an official Elementor widget, therefore it is possible that it has some compatibility issues.

Please try:

- Deactivate all your plugins besides Elementor. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
 - Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).

And see if the issue still persists.

Thanks.
