### ISSUE TITLE
Unable to get color controls data at 'before_render' and 'after_render' methods

### ISSUE THREAD

**Issue by tsabedin** [elementor/elementor#7889]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Hi,

I'm unable to get color controls data at 'before_render' and 'after_render' methods. All other controls data are reading properly, but  on "Controls_Manager::COLOR" data gives error.
"Notice: Undefined index: se_ttp_title_color(control name)"

Code snippet is as following

public function register_controls($section, $section_id) {
          static $se_section = [ '_section_style' ];

		if ( !in_array( $section_id, $se_section ) ) { return; }
           $section->add_control(
			'se_ttp_title_color',
		  	[
				'label'        => __( 'Title Color', 'super-elements' ),
				'type'         => Controls_Manager::COLOR,
                                'default'      => '#eee',
			]
          );
}

public function before_render( $section ) {
          $data               = $section->get_data();
          $type               = $data['elType'];
          $settings           = $data['settings'];
          
  
          if( 'widget' == $type){  
               $section->add_render_attribute( '_wrapper', 'style', 'color: ' .$settings['se_ttp_title_color'] );  /* Here $settings['se_ttp_title_color'] give null value */
          }
          
}
## Isolating the problem

- [X ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.33 (Win64) PHP/7.2.4
	MySQL version: MySQL Community Server (GPL) v5.7.21
	PHP Version: 7.2.4
	PHP Max Input Vars: 2500
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.1.1
	Site URL: http://localhost/my-works
	Home URL: http://localhost/my-works
	WP Multisite: No
	Max Upload Size: 2 MB
	Memory limit: 256M
	Permalink Structure: /%category%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Active

== Theme ==
	Name: Astra
	Version: 1.8.1
	Author: Brainstorm Force
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36

== Active Plugins ==
	Contact Form 7
		Version: 5.1.1
		Author: Takayuki Miyoshi

	DocsPress
		Version: 2.0.0
		Author: nK

	Elementor
		Version: 2.5.14
		Author: Elementor.com

	Optimize Database after Deleting Revisions
		Version: 4.7.4
		Author: CAGE Web Design | Rolf van Gelder, Eindhoven, The Netherlands

	Super Elements for Elementor
		Version: 1.7.5
		Author: ThemeRevealed

	WooCommerce
		Version: 3.5.8
		Author: Automattic

	WooCommerce Blocks
		Version: 1.4.0
		Author: Automattic


== Log ==
	: 
JS: showing 20 of 24JS: 2019-03-15 22:29:45 [error X 18][http://localhost/my-works/wp-content/plugins/super-elements-for-elementor/assets/js/super-elements.js?ver=1.7.5:701:13] particlesJS is not defined 
JS: 2019-03-21 07:43:15 [error X 52][http://localhost/my-works/wp-content/plugins/super-elements-for-elementor/assets/js/super-elements.js?ver=1.7.5:958:42] Cannot read property \'length\' of undefined 
JS: 2019-03-26 06:58:50 [error X 3][http://localhost/my-works/wp-admin/post.php?post=2956&action=elementor:6:8] color is not defined 
JS: 2019-03-26 14:52:31 [error X 2][http://localhost/my-works/wp-content/plugins/super-elements-for-elementor/assets/js/circle_progress.min.js?ver=1.7.5:10:1767] Failed to execute \'addColorStop\' on \'CanvasGradient\': The value provided (\'\') could not be parsed as a color. 
JS: 2019-03-26 15:03:02 [error X 1][http://localhost/my-works/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.9:2:73101] Cannot read property \'currentView\' of undefined 
JS: 2019-03-26 21:43:37 [error X 22][http://localhost/my-works/wp-content/plugins/super-elements-for-elementor/assets/js/super-elements.js?ver=1.7.5:1113:40] $(...).ripples is not a function 
JS: 2019-03-27 18:07:28 [error X 1][http://localhost/my-works/wp-content/plugins/super-elements-for-elementor/assets/js/super-elements.js?ver=1.7.5:1113:43] $(...).Ripples is not a function 
JS: 2019-03-27 19:19:35 [error X 1][http://localhost/my-works/wp-content/plugins/super-elements-for-elementor/assets/js/jquery.ripples.js?ver=1.7.5:872:15] $ is not a function 
JS: 2019-04-01 20:44:25 [error X 3][http://localhost/my-works/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,underscore,shortcode,utils,backbone,wp-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jqu&load%5B%5D=ery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable&ver=5.1.1:8:1314] e.toLowerCase is not a function 
JS: 2019-04-03 00:19:18 [error X 7][http://localhost/my-works/wp-content/plugins/super-elements-for-elementor/assets/js/super-elements.js?ver=1.7.5:1212:37] Cannot read property \'url\' of undefined 
JS: 2019-04-03 18:50:33 [error X 1][http://localhost/my-works/wp-content/plugins/super-elements-for-elementor/assets/js/super-elements.js?ver=1.7.5:1218:23] Cannot read property \'src\' of undefined 
JS: 2019-04-03 18:58:15 [error X 5][http://localhost/my-works/wp-content/plugins/super-elements-for-elementor/assets/js/super-elements.js?ver=1.7.5:1218:23] Cannot read property \'push\' of undefined 
JS: 2019-04-03 19:17:16 [error X 2][http://localhost/my-works/wp-content/plugins/super-elements-for-elementor/assets/js/super-elements.js?ver=1.7.5:1219:15] seSlide.push is not a function 
JS: 2019-04-03 19:29:33 [error X 1][http://localhost/my-works/wp-content/plugins/super-elements-for-elementor/assets/js/super-elements.js?ver=1.7.5:1234:15] seSlides.push is not a function 
JS: 2019-04-04 18:33:00 [error X 1][http://localhost/my-works/wp-content/plugins/super-elements-for-elementor/assets/js/super-elements.js?ver=1.7.5:641:72] SuperParticlesHandler is not defined 
JS: 2019-04-04 21:23:46 [error X 5][http://localhost/my-works/wp-content/plugins/super-elements-for-elementor/assets/js/super-extends.js?ver=1.7.5:10:20] settings is not defined 
JS: 2019-04-04 22:51:50 [error X 3][http://localhost/my-works/wp-content/plugins/super-elements-for-elementor/assets/js/super-extends.js?ver=1.7.5:615:26] seVideo is not defined 
JS: 2019-04-12 21:21:51 [error X 12][http://localhost/my-works/wp-content/plugins/super-elements-for-elementor/assets/js/super-extends.js?ver=1.7.5:697:31] animSection.hasClass is not a function 
JS: 2019-04-13 00:58:43 [error X 40][http://localhost/my-works/wp-content/plugins/super-elements-for-elementor/assets/js/super-extends.js?ver=1.7.5:717:82] Cannot read property \'elements\' of undefined 
JS: 2019-04-13 08:51:33 [error X 15][http://localhost/my-works/wp-content/plugins/super-elements-for-elementor/assets/js/super-extends.js?ver=1.7.5:736:26] col is not defined 

Log: showing 10 of 102019-03-10 18:49:31 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.3',
  'to' => '2.5.4',
)]
2019-03-11 19:30:08 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.4',
  'to' => '2.5.5',
)]
2019-03-14 16:51:26 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.5',
  'to' => '2.5.7',
)]
2019-03-15 18:56:08 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.7',
  'to' => '2.5.8',
)]
2019-03-19 09:30:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.8',
  'to' => '2.5.9',
)]
2019-03-27 14:35:28 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.9',
  'to' => '2.5.10',
)]
2019-03-31 17:39:09 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.10',
  'to' => '2.5.11',
)]
2019-04-08 18:33:19 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.11',
  'to' => '2.5.12',
)]
2019-04-10 18:03:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.12',
  'to' => '2.5.13',
)]
2019-04-16 20:04:23 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.13',
  'to' => '2.5.14',
)]

PHP: showing 9 of 9PHP: 2019-03-11 21:55:49 [notice X 1][C:\wamp64\www\my-works\wp-content\plugins\elementor-extras\modules\popup\widgets\popup.php::2259] Undefined index: popup_widget_template_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-03-11 22:14:40 [notice X 3][C:\wamp64\www\my-works\wp-content\plugins\elementor\includes\managers\image.php::33] Undefined index: size [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-03-12 21:26:54 [error X 2][C:\wamp64\www\my-works\wp-content\plugins\elementor\includes\managers\widgets.php::189] Uncaught TypeError: Argument 1 passed to Elementor\Widgets_Manager::register_widget_type() must be an instance of Elementor\Widget_Base, instance of Elementor\Super_Particles_Widget given, called in C:\wamp64\www\my-works\wp-content\plugins\super-elements-for-elementor\elements\super-particles.php on line 166 and defined in C:\wamp64\www\my-works\wp-content\plugins\elementor\includes\managers\widgets.php:189
Stack trace:
#0 C:\wamp64\www\my-works\wp-content\plugins\super-elements-for-elementor\elements\super-particles.php(166): Elementor\Widgets_Manager->register_widget_type(Object(Elementor\Super_Particles_Widget))
#1 C:\wamp64\www\my-works\wp-content\plugins\super-elements-for-elementor\super-element-class.php(271): require_once('C:\\wamp64\\www\\m...')
#2 C:\wamp64\www\my-works\wp-includes\class-wp-hook.php(286): Super_Element_Class->super_elements_widget_register(Object(Elementor\Widgets_Manager))
#3 C:\wamp64\www\my-works\wp-includes\class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#4 C:\w [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-04-01 20:43:18 [warning X 41][C:\wamp64\www\my-works\wp-content\plugins\elementor\includes\managers\controls.php::676] array_merge(): Argument #2 is not an array [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-04-08 19:10:17 [error X 1][C:\wamp64\www\my-works\wp-content\plugins\elementor\includes\managers\widgets.php::189] Argument 1 passed to Elementor\Widgets_Manager::register_widget_type() must be an instance of Elementor\Widget_Base, instance of SuperElements\Modules\SuperParallax\Module given, called in C:\wamp64\www\my-works\wp-content\plugins\super-elements-for-elementor\base\module-base.php on line 66 and defined [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-04-08 20:08:28 [error X 1][C:\wamp64\www\my-works\wp-content\plugins\elementor\core\base\module.php::146] Uncaught Error: Maximum function nesting level of '256' reached, aborting! in C:\wamp64\www\my-works\wp-content\plugins\elementor\core\base\module.php:146
Stack trace:
#0 C:\wamp64\www\my-works\wp-content\plugins\elementor\core\base\module.php(146): ReflectionClass->__construct(Object(SuperElements\Modules\SuperParallax\Module))
#1 C:\wamp64\www\my-works\wp-content\plugins\super-elements-for-elementor\base\module-base.php(60): Elementor\Core\Base\Module->get_reflection()
#2 C:\wamp64\www\my-works\wp-content\plugins\super-elements-for-elementor\modules\super-parallax\module.php(27): SuperElements\Base\Module_Base->__construct()
#3 C:\wamp64\www\my-works\wp-content\plugins\super-elements-for-elementor\base\module-base.php(61): SuperElements\Modules\SuperParallax\Module->__construct()
#4 C:\wamp64\www\my-works\wp-content\plugins\super-elements-for-elementor\modules\super-parallax\module.php(27): SuperElements\Base\Module_Base->__construct()
#5 C:\wamp64\www\my-works\wp-content\plugins\super-elements-for-e [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-04-08 20:18:55 [error X 2][C:\wamp64\www\my-works\wp-content\plugins\elementor\includes\managers\widgets.php::189] Argument 1 passed to Elementor\Widgets_Manager::register_widget_type() must be an instance of Elementor\Widget_Base, instance of SuperElements\Modules\SuperParallax\Module given, called in C:\wamp64\www\my-works\wp-content\plugins\super-elements-for-elementor\base\module-base.php on line 67 and defined [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-04-13 21:43:06 [error X 3][C:\wamp64\www\my-works\wp-content\plugins\elementor\core\base\base-object.php::99] Argument 1 passed to Elementor\Core\Base\Base_Object::get_items() must be of the type array, null given, called in C:\wamp64\www\my-works\wp-content\plugins\elementor\includes\base\controls-stack.php on line 1023 and defined [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-04-13 21:51:50 [error X 2][C:\wamp64\www\my-works\wp-content\plugins\elementor\includes\base\controls-stack.php::1952] Argument 1 passed to Elementor\Controls_Stack::sanitize_settings() must be of the type array, null given, called in C:\wamp64\www\my-works\wp-content\plugins\elementor\includes\base\controls-stack.php on line 1018 and defined [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]			

```
</details>

**Comment by tsabedin** [comment]
Solved!
