### ISSUE TITLE
Fatal error with get_settings on elementor hook

### ISSUE THREAD

**Issue by adan2g2f** [elementor/elementor#8698]
I am trying to check if widget has data settings from this hooks:
`
add_action( 'elementor/element/toggle/section_toggle/after_section_end', function ( $element )
{
  $settings = $element->get_settings();
  $get_data = $element->get_data();
}
`

If widget exist in the frontend, it's ok, I get the raw data, but i**f the page is empty**, I got the same error message from each function get_settings or get_data:

`[26-Jul-2019 16:36:22 UTC] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Elementor\Controls_Stack::sanitize_settings() must be of the type array, null given, called in /Applications/MAMP/htdocs/wordpress/wp-content/plugins/elementor/includes/base/controls-stack.php on line 1022 and defined in /Applications/MAMP/htdocs/wordpress/wp-content/plugins/elementor/includes/base/controls-stack.php:1933
Stack trace:
#0 /Applications/MAMP/htdocs/wordpress/wp-content/plugins/elementor/includes/base/controls-stack.php(1022): Elementor\Controls_Stack->sanitize_settings(NULL)
#1 /Applications/MAMP/htdocs/wordpress/wp-content/plugins/elementor/includes/base/controls-stack.php(1775): Elementor\Controls_Stack->get_data('settings')
#2 /Applications/MAMP/htdocs/wordpress/wp-content/plugins/elementor/core/base/base-object.php(132): Elementor\Controls_Stack->get_init_settings()
#3 /Applications/MAMP/htdocs/wordpress/wp-content/plugins/elementor/core/base/base-object.php(40): Elementor\Core\Base\Base_Object->ensure_settings()
#4 /Applications/MAMP/htdocs/wordpres in /Applications/MAMP/htdocs/wordpress/wp-content/plugins/elementor/includes/base/controls-stack.php on line 1933`

Could you help me to check if the element has data settings or not? I could use try catch but it is quite dirty.

Thank you for helping.

**Comment by bainternet** [comment]
@adan2g2f 	

This hook is called both in the frontend ( where usually you do have settings ) an in the editor which is before you have settings which is why you are getting that fatal error.

Either way, calling `get_settings` on this hook is **Wrong!**. Tell us what you are trying to do and we'll try to direct you to the right approach.

**Comment by TusharJoy** [comment]
Whats the last update here?

**Comment by hogash** [comment]
Also had this issue as well. I wanted to add an explication text label on the control section's title when the control inside had content. The element where i appended these controls was a Section.

All good until a new page was created/edited in Elementor.

I eventually used JS and i'm good, but i'm interested in knowing if there might have been any alternatives. From what i see the fatal error is generated because the `sanitize_settings ` expects an array and null is given. Wouldn't an `is_null` or `is_array` etc. would've solved this? I'm asking because as you said it's wrong to call `get_settings` on this hook, but i do have access to the instance and it's a bit strange.

@adan2g2f tried try/catch but still got the error.

cc @bainternet (Thanks!)

**Comment by oooh-boi** [comment]
There's something wrong here...
`$element->get_data()` with `after_section_end` hook works only if the widget exists on stage, otherwise Elementor editor hangs out.
Is there a way to `get_data()` on any other hook that's `elementor/element/` related?

Essentially, how am I supposed to get widget settings out of protected function `render()`?

**Comment by amyriounis** [comment]
Hello @bainternet, regarding this:
>Either way, calling get_settings on this hook is Wrong!. Tell us what you are trying to do and we'll try to direct you to the right approach.

 I need to generate a variable number of controls depending on a widget setting. How would I go about doing this? 

My initial attempt was to call  `get_settings()` inside a `elementor/element/{$section_name}/{$section_id}/before_section_start
` hook but I understand this is wrong. What's the correct approach?
