### ISSUE TITLE
WooCommerce pages not loading (preview could not be loaded)

### ISSUE THREAD

**Issue by noahkiss** [elementor/elementor#8759]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

WooCommerce shop page cannot be edited with Elementor. Message received is "we're sorry, something went wrong." Pages not attached to WooCommerce can be edited normally. Any page displayed with a shortcode can be edited (cart, account, etc.)

## Steps to reproduce

Make shop page. Assign to WooCommerce. Edit with Elementor.

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

I have also tried multiple rollbacks, editing the shop page before setting as default in woocommerce, (as mentioned) disabling plugins, etc. Safe mode does work to load framework but does not load inner page. This issue was not happening ~1-2 weeks ago when attempted with Oxygen + Elementor, but has not been revisited until now and is now non-working.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MySQL Community Server - (GPL) v5.7.27
	PHP Version: 7.3.7
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.2.2
	Site URL: [redacted]
	Home URL: [redacted]
	WP Multisite: No
	Max Upload Size: 2 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/New_York
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Nineteen
	Version: 1.4
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:68.0) Gecko/20100101 Firefox/68.0

== Active Plugins ==
	Duplicator Pro
		Version: 3.8.4.1
		Author: Snap Creek

	Elementor
		Version: 2.6.7
		Author: Elementor.com

	Elementor Pro
		Version: 2.6.2
		Author: Elementor.com

	Imagify
		Version: 1.9.6
		Author: WP Media

	Oxygen
		Version: 2.4
		Author: Soflyy

	WooCommerce
		Version: 3.6.5
		Author: Automattic

	WP Real Media Library
		Version: 4.5.1
		Author: Matthias Günter


== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

	WP Fail2Ban Redux
		Version: 0.5.0
		Author: Brandon Allen


== Log ==
	: 
Log: showing 14 of 142019-07-17 17:36:57 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.9',
  'to' => '2.5.14',
)]
2019-07-18 17:50:24 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.6.2',
  'to' => '2.6.5',
)]
2019-07-23 15:08:11 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.14',
  'to' => '2.6.0',
)]
2019-07-23 15:08:11 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.6.5',
  'to' => '2.6.6',
)]
2019-07-23 15:08:11 [info] elementor::elementor_updater Started 
2019-07-23 15:08:11 [info] Elementor/Upgrades - _v_2_6_6_fa4_migration_button Start  
2019-07-23 15:08:11 [info] Elementor/Upgrades - _v_2_6_6_fa4_migration_button Finished 
2019-07-23 15:08:11 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.6.5',
  'to' => '2.6.6',
)]
2019-07-23 15:08:12 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.6.5',
  'to' => '2.6.6',
)]
2019-08-01 00:17:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.6.0',
  'to' => '2.6.2',
)]
2019-08-01 01:31:53 [info] elementor::elementor_updater Started 
2019-08-01 01:31:53 [info] Elementor/Upgrades - _v_2_6_6_fa4_migration_button Start  
2019-08-01 01:31:53 [info] Elementor/Upgrades - _v_2_6_6_fa4_migration_button Finished 
2019-08-01 01:31:53 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.6.6',
  'to' => '2.6.7',
)]

PHP: showing 1 of 1PHP: 2019-08-03 03:50:28 [error X 3][/home/[redacted]/public_html/wp-content/plugins/elementor-pro/core/editor/notice-bar.php::12] Uncaught Error: Class 'Elementor\Core\Editor\Notice_Bar' not found in /home/[redacted]/public_html/wp-content/plugins/elementor-pro/core/editor/notice-bar.php:12
Stack trace:
#0 /home/[redacted]/public_html/wp-content/plugins/elementor-pro/plugin.php(145): include()
#1 [internal function]: ElementorPro\Plugin->autoload('ElementorPro\\Co...')
#2 /home/[redacted]/public_html/wp-content/plugins/elementor-pro/core/editor/editor.php(99): spl_autoload_call('ElementorPro\\Co...')
#3 /home/[redacted]/public_html/wp-includes/class-wp-hook.php(286): ElementorPro\Core\Editor\Editor->on_elementor_init('')
#4 /home/[redacted]/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#5 /home/[redacted]/public_html/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#6 /home/[redacted]/public_html/wp-content/plugins/elementor/includes/plugin.php(475): do_action('elementor/init')
#7 /home/[redacted]/public_html/wp-includes/class-wp-hook.php(286): Elementor\Plugin->init('')
#8 /home/[redacted]/public_html [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
```
</details>

**Comment by Spark3000** [comment]
Not sure if I'm understanding the bug properly. But what I have done is using Theme Builder, create a template of type Product Archive, then use the Products element in there with the query "current query". Then when you save you will be asked where to show it and you Include All Product Archives. And that's it. The shop page that you have set, because it's a product archive, will adopt this theme.

**Comment by noahkiss** [comment]
thanks @Spark3000 that's what I get for not double-checking how to theme Woo 🙄
