### ISSUE TITLE
Post_Custom_Field does not get metadata key on editor

### ISSUE THREAD

**Issue by satanasdiabolo** [elementor/elementor#9118]
![screen](https://user-images.githubusercontent.com/1850524/65138847-ebf97380-da0b-11e9-8e14-8ffefaf21d62.jpg)

## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

On the editor, I'm creating a single page template. I'd like to display some metadata with a text field with dynamic values using the tag, "Post Custom Field". The selector is always empty, even if I setup de preview parameters.

## Steps to reproduce

- Add a metadata to posts (like key:foo and value:bar)
- Create a single page template for posts
- Define preview parameters to see your post with metadata
- Add a text field
- click on Dynamic > Select "Post Custom Field"
- Click on the wrench to display settings, the "Key" selector is empty

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.29 (Ubuntu)
	MySQL version: (Ubuntu) v5.7.27
	PHP Version: 7.2.21-1+ubuntu18.04.1+deb.sury.org+1
	PHP Max Input Vars: 1000
	PHP Max Post Size: 20M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.2.3
	Site URL: http://127.0.0.1/lab/wordpress_dev
	Home URL: http://127.0.0.1/lab/wordpress_dev
	WP Multisite: No
	Max Upload Size: 20 MB
	Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: Europe/Paris
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.2.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.110 Safari/537.36 Vivaldi/2.7.1628.30

== Active Plugins ==
	Debug Bar
		Version: 1.0
		Author: wordpressdotorg

	Debug Elementor
		Version: 1.0.0
		Author: Rami Yushuvaev

	Elementor
		Version: 2.7.2
		Author: Elementor.com

	Elementor Pro
		Version: 2.6.5
		Author: Elementor.com

	Pods - Custom Content Types and Fields
		Version: 2.7.15
		Author: Pods Framework Team

	Trackmania Grand League
		Version: 0.0.1
		Author: Ubisoft Nadeo


== Log ==
	
PHP: showing 6 of 6PHP: 2019-09-13 15:11:32 [warning X 1][/vagrant/lab/wordpress_dev/wp-content/plugins/elementor/includes/elements/section.php::1533] include(): Failed opening 'http://127.0.0.1/lab/wordpress_dev/wp-content/plugins/trackmania-grand-league/foobar.svg' for inclusion (include_path='.:/usr/share/php') [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-09-13 15:20:43 [warning X 1][/vagrant/lab/wordpress_dev/wp-content/plugins/elementor/includes/elements/section.php::1533] include(): Failed opening '/vagrant/lab/wordpress_dev/wp-content/plugins/elementor/assets/shapes/foobar.svg' for inclusion (include_path='.:/usr/share/php') [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-09-17 16:36:34 [error X 1][/vagrant/lab/wordpress_dev/wp-content/plugins/elementor/includes/base/element-base.php::115] Uncaught ArgumentCountError: Too few arguments to function Elementor\Element_Base::add_style_depends(), 0 passed in /vagrant/lab/wordpress_dev/wp-content/plugins/trackmania-grand-league/src/Widget/RoundWidget.php on line 73 and exactly 1 expected in /vagrant/lab/wordpress_dev/wp-content/plugins/elementor/includes/base/element-base.php:115
Stack trace:
#0 /vagrant/lab/wordpress_dev/wp-content/plugins/trackmania-grand-league/src/Widget/RoundWidget.php(73): Elementor\Element_Base->add_style_depends()
#1 /vagrant/lab/wordpress_dev/wp-content/plugins/elementor/includes/base/widget-base.php(448): Nadeo\TrackmaniaGrandLeague\Widget\RoundWidget->render()
#2 /vagrant/lab/wordpress_dev/wp-content/plugins/elementor/includes/base/widget-base.php(578): Elementor\Widget_Base->render_content()
#3 /vagrant/lab/wordpress_dev/wp-content/plugins/elementor/includes/base/element-base.php(592): Elementor\Widget_Base->_print_content()
#4 /vagrant/lab/wordpress_dev/wp-content/plugins/elementor/includes/base/element-base.php(808): El [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-09-18 10:25:40 [warning X 1][/vagrant/lab/wordpress_dev/wp-content/plugins/elementor/core/common/modules/ajax/module.php::269] Cannot modify header information - headers already sent by (output started at /vagrant/lab/wordpress_dev/wp-content/plugins/trackmania-grand-league/src/Posts/Champion.php:59) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-09-18 10:35:49 [warning X 14][/vagrant/lab/wordpress_dev/wp-content/plugins/elementor/core/common/modules/ajax/module.php::269] Cannot modify header information - headers already sent by (output started at /vagrant/lab/wordpress_dev/wp-content/plugins/trackmania-grand-league/src/Posts/Champion.php:64) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-09-18 11:30:49 [notice X 1][/vagrant/lab/wordpress_dev/wp-content/plugins/elementor-pro/modules/dynamic-tags/tags/post-custom-field.php::62] Array to string conversion [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 1 of 12019-09-16 09:57:28 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.7.1',
  'to' => '2.7.2',
)]

JS: showing 2 of 2JS: 2019-09-16 11:13:18 [error X 8][http://127.0.0.1/lab/wordpress_dev/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.7.2:2:46150] Cannot read property \'select2\' of undefined 
JS: 2019-09-17 10:30:13 [error X 7][http://127.0.0.1/lab/wordpress_dev/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=2.7.2:2:38717] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got <http://127.0.0.1/lab/wordpress_dev/wp-content/plugins/essential-addons-elementor/assets/front-end/img/slide.png> as `eael_flip_carousel_slide` value. Expected array or object.',
)]



== Elements Usage ==
	
	archive
		button : 1
		champions_list : 1
		heading : 3
		image : 1
		theme-archive-title : 1
	header
		button : 1
		image : 1
		nav-menu : 1
	section
		heading : 2
		image : 4
		text-editor : 1
	single
		theme-post-content : 1
	wp-page
		divider : 1
		heading : 1
		image : 1
		posts : 1
```
</details>

**Comment by bainternet** [comment]
@satanasdiabolo 

We can't replicate this issue,

Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.
