### ISSUE TITLE
Looping lightbox width carousel

### ISSUE THREAD

**Issue by mrkarlson** [elementor/elementor#9198]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate. #6252
- [X] The issue still exists against the latest stable version of Elementor.

## Description

I did my own skin for doing loop some post types. And in that skin I put carousel with acf gallery and I activated lightbox option.

In front end carrousel is looking good with every gallery from self post gallery but if I click in some image for look that gallery in lightbox, the lightbox show me all images from all posts...

**I have some possible solution for this:** 

I detected problem in Line 678 from 'image-carousel.php' with adding get_the_ID() function from wordpress, I think it will be resolved and don't broke anything.

**Posible solution:**

**Actual line:**
`'data-elementor-lightbox-slideshow' => $this->get_id(),`

**New possible line:**
`'data-elementor-lightbox-slideshow' => $this->get_id().'-'.get_the_ID(),`

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: (Ubuntu) v5.5.61-MariaDB-38.13
	PHP Version: 7.3.4
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.2.3
	Site URL: ###
	Home URL: ###
	WP Multisite: No
	Max Upload Size: 2 MB
	Memory limit: 512M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: es
	Timezone: Europe/Madrid
	Debug Mode: Inactive

== Theme ==
	Name: Bonterra Theme
	Version: 1.0
	Author: Denis, Ernesto
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.2.0
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: es_ES
	User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 5.7.13
		Author: Elliot Condon

	Classic Editor
		Version: 1.5
		Author: WordPress Contributors

	Custom Post Type UI
		Version: 1.6.2
		Author: WebDevStudios

	Duplicate Post
		Version: 3.2.3
		Author: Enrico Battocchi

	DynamicConditions
		Version: 1.4.0
		Author: RTO GmbH

	Ele Custom Skin
		Version: 1.3.3
		Author: Dudaster.com

	Elementor
		Version: 2.7.3
		Author: Elementor.com

	Elementor Pro
		Version: 2.7.0
		Author: Elementor.com

	Elementor SuperCat
		Version: 2.2.4
		Author: Nicola Cavallazzi

	Instagram Feed
		Version: 1.12.2
		Author: Smash Balloon

	Lazy Load by WP Rocket
		Version: 2.3.2
		Author: WP Rocket

	Make Column Clickable Elementor
		Version: 1.3.0
		Author: Fernando Acosta

	Post Types Order
		Version: 1.9.4.1
		Author: Nsp Code

	Smush
		Version: 3.2.4
		Author: WPMU DEV

	Stachethemes Event Calendar
		Version: 2.6
		Author: Stachethemes

	TinyMCE Advanced
		Version: 5.2.1
		Author: Andrew Ozz

	WP Mail SMTP
		Version: 1.6.2
		Author: WPForms

	WPML Multilingual CMS
		Version: 4.2.9
		Author: OnTheGoSystems

	WPML String Translation
		Version: 2.10.7
		Author: OnTheGoSystems

	WPML Translation Management
		Version: 2.8.8
		Author: OnTheGoSystems


== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com


== Log<a href="/wp-admin/admin.php?page=elementor-system-info&elementor-clear-log=1&_wpnonce=b35acba214#elementor-clear-log" class="box-title-tool">Vaciar el registro</a><span id="elementor-clear-log"></span> ==
	
PHP: showing 6 of 6PHP: 2019-09-05 14:13:08 [warning X 1][/var/www/vhosts/bonterrapark.com/develop.bonterrapark.com/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/icons/custom-icons.php::180] unlink(Recepción.rar): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-09-05 14:13:20 [warning X 1][/var/www/vhosts/bonterrapark.com/develop.bonterrapark.com/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/icons/custom-icons.php::189] unlink(Recepción.zip): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-09-25 09:47:11 [warning X 13][/var/www/vhosts/bonterrapark.com/develop.bonterrapark.com/wp-content/plugins/elementor/modules/usage/module.php::481] Division by zero [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-09-25 09:47:25 [notice X 36][/var/www/vhosts/bonterrapark.com/develop.bonterrapark.com/wp-content/plugins/elementor-super-cat/widgets/dropdown-filter.php::98] Undefined offset: 0 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-09-25 09:52:40 [notice X 33][/var/www/vhosts/bonterrapark.com/develop.bonterrapark.com/wp-content/plugins/elementor-super-cat/widgets/dropdown-filter.php::217] Undefined variable: settings [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-09-25 12:13:05 [error X 1][/var/www/vhosts/bonterrapark.com/develop.bonterrapark.com/wp-content/plugins/elementor/includes/widgets/image-carousel.php::680] Uncaught Error: Call to undefined method WP_Post::get_id() in /var/www/vhosts/bonterrapark.com/develop.bonterrapark.com/wp-content/plugins/elementor/includes/widgets/image-carousel.php:680
Stack trace:
#0 /var/www/vhosts/bonterrapark.com/develop.bonterrapark.com/wp-content/plugins/elementor/includes/base/widget-base.php(448): Elementor\Widget_Image_Carousel->render()
#1 /var/www/vhosts/bonterrapark.com/develop.bonterrapark.com/wp-content/plugins/elementor/includes/base/widget-base.php(578): Elementor\Widget_Base->render_content()
#2 /var/www/vhosts/bonterrapark.com/develop.bonterrapark.com/wp-content/plugins/elementor/includes/base/element-base.php(592): Elementor\Widget_Base->_print_content()
#3 /var/www/vhosts/bonterrapark.com/develop.bonterrapark.com/wp-content/plugins/elementor/includes/base/element-base.php(808): Elementor\Element_Base->print_element()
#4 /var/www/vhosts/bonterrapark.com/develop.bonterrapark.com/wp-content/plugins/elementor/includes/base/element-base.php(592): Elementor\Element_Base->_pr [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 20 of 28JS: 2019-09-14 10:02:14 [error X 1][http://develop.bonterrapark.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.6.8:2:41610] Cannot read property \'select2\' of undefined 
JS: 2019-09-14 10:09:51 [error X 1][http://develop.bonterrapark.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view1428\") has already been destroyed and cannot be used. 
JS: 2019-09-21 15:16:52 [error X 1][http://develop.bonterrapark.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view692\") has already been destroyed and cannot be used. 
JS: 2019-09-21 15:32:45 [error X 10][http://develop.bonterrapark.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view477\") has already been destroyed and cannot be used. 
JS: 2019-09-21 16:11:48 [error X 4][http://develop.bonterrapark.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view372\") has already been destroyed and cannot be used. 
JS: 2019-09-23 14:16:04 [error X 1][http://develop.bonterrapark.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view725\") has already been destroyed and cannot be used. 
JS: 2019-09-23 14:36:25 [error X 1][http://develop.bonterrapark.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view374\") has already been destroyed and cannot be used. 
JS: 2019-09-23 14:39:14 [error X 1][http://develop.bonterrapark.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view406\") has already been destroyed and cannot be used. 
JS: 2019-09-23 16:07:27 [error X 1][http://develop.bonterrapark.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view2125\") has already been destroyed and cannot be used. 
JS: 2019-09-24 16:04:02 [error X 2][http://develop.bonterrapark.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view531\") has already been destroyed and cannot be used. 
JS: 2019-09-24 16:54:48 [error X 1][http://develop.bonterrapark.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view399\") has already been destroyed and cannot be used. 
JS: 2019-09-24 18:24:56 [error X 2][http://develop.bonterrapark.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view414\") has already been destroyed and cannot be used. 
JS: 2019-09-24 19:10:21 [error X 1][http://develop.bonterrapark.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view591\") has already been destroyed and cannot be used. 
JS: 2019-09-25 11:09:23 [error X 1][http://develop.bonterrapark.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view409\") has already been destroyed and cannot be used. 
JS: 2019-09-25 13:03:10 [error X 2][http://develop.bonterrapark.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view720\") has already been destroyed and cannot be used. 
JS: 2019-09-25 15:06:55 [error X 3][http://develop.bonterrapark.com/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=2.7.0:2:62217] Cannot read property \'get\' of undefined 
JS: 2019-09-25 15:28:54 [error X 1][http://develop.bonterrapark.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view514\") has already been destroyed and cannot be used. 
JS: 2019-09-25 15:32:53 [error X 3][http://develop.bonterrapark.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view723\") has already been destroyed and cannot be used. 
JS: 2019-09-25 16:08:49 [error X 3][http://develop.bonterrapark.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view430\") has already been destroyed and cannot be used. 
JS: 2019-09-25 16:21:31 [error X 1][http://develop.bonterrapark.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view463\") has already been destroyed and cannot be used. 

Log: showing 8 of 82019-09-25 09:47:10 [info] elementor::elementor_updater Started 
2019-09-25 09:47:11 [info] Elementor/Upgrades - _v_2_7_1_remove_old_usage_data Start  
2019-09-25 09:47:11 [info] Elementor/Upgrades - _v_2_7_1_remove_old_usage_data Finished 
2019-09-25 09:47:11 [info] Elementor/Upgrades - _v_2_7_1_recalc_usage_data Start  
2019-09-25 09:47:11 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.6.8',
  'to' => '2.7.3',
)]
2019-09-25 09:47:11 [info] Elementor/Upgrades - _v_2_7_1_recalc_usage_data Finished 
2019-09-25 09:47:11 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.6.8',
  'to' => '2.7.3',
)]
2019-09-25 16:54:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.6.1',
  'to' => '2.7.0',
)]



== Elements Usage ==
	
	archive
		archive-posts : 1
		button : 6
		global : 2
		heading : 13
		icon-box : 12
		posts : 2
	footer
		button : 1
		html : 1
		icon-list : 4
		social-icons : 1
		text-editor : 2
		theme-site-logo : 1
	header
		icon-box : 2
		image : 2
		nav-menu : 2
		shortcode : 2
		social-icons : 1
		theme-site-logo : 1
	loop
		button : 1
		heading : 2
		icon-box : 2
		image : 13
		image-carousel : 1
		text-editor : 15
		theme-post-title : 1
	page
		button : 3
		global : 1
		heading : 6
	popup
		heading : 1
		text-editor : 1
	section
		button : 6
		global : 1
		heading : 10
		image : 1
		text-editor : 1
	single
		button : 6
		global : 2
		heading : 11
		icon-box : 2
		icon-list : 1
		image : 15
		image-carousel : 1
		image-gallery : 1
		posts : 1
		spacer : 1
		text-editor : 18
		theme-post-content : 1
		theme-post-title : 1
		wp-widget-categories : 1
	wp-post
		button : 2
		form : 2
		google_maps : 1
		heading : -126
		image : 14
		image-box : -160
		image-carousel : 1
		posts : 2
		social-icons : 2
		spacer : 1
		text-editor : 10
		toggle : 1
		video : -35
		wp-widget-categories : 1

```
</details>

**Comment by catherinewiltshire** [comment]
I have the same issue. 
I am using crocoblock jetengine listing grid and pulling through galleries from a custom post type using elementor image carousel. 
I have about 5 different galleries in my custom post type and elementor is pulling them all in to one lightbox.

I recreated this on another wordpress installation also

2 galleries with 3 images in each

![galleries](https://user-images.githubusercontent.com/40239762/105507540-3905ed80-5cc3-11eb-84a8-2fa97ae60616.jpg)

The lightbox pulling in all photos

![lightbox-with-all-photos](https://user-images.githubusercontent.com/40239762/105507544-3a371a80-5cc3-11eb-9334-2aa537733653.jpg)

**Comment by mrkarlson** [comment]
> I have the same issue.
> I am using crocoblock jetengine listing grid and pulling through galleries from a custom post type using elementor image carousel.
> I have about 5 different galleries in my custom post type and elementor is pulling them all in to one lightbox.
> 
> I recreated this on another wordpress installation also
> 
> 2 galleries with 3 images in each
> 
> ![galleries](https://user-images.githubusercontent.com/40239762/105507540-3905ed80-5cc3-11eb-84a8-2fa97ae60616.jpg)
> 
> The lightbox pulling in all photos
> 
> ![lightbox-with-all-photos](https://user-images.githubusercontent.com/40239762/105507544-3a371a80-5cc3-11eb-9334-2aa537733653.jpg)

Try use my solution for that if you need this. It will be work :) but you will have a problem with updates :(

**Comment by catherinewiltshire** [comment]
> Try use my solution for that if you need this. It will be work :) but you will have a problem with updates :(

I'm not a developer lol, where would I put the code?

**Comment by mrkarlson** [comment]
> > Try use my solution for that if you need this. It will be work :) but you will have a problem with updates :(
> 
> I'm not a developer lol, where would I put the code?

I updated the issue and put PATH to file and line ;) and what you must to change :)

**Comment by catherinewiltshire** [comment]
> I updated the issue and put PATH to file and line ;) and what you must to change :)

Yes that fixed it thank you! I raised a support ticket with elementor directing them to this thread so hopefully they'll have a look and edit the widget in the same way save having to edit again on each update.

**Comment by catherinewiltshire** [comment]
Just an update for anyone else finding this the line you need to edit is now line 713.

**Comment by mrkarlson** [comment]
> Just an update for anyone else finding this the line you need to edit is now line 713.

Thank you. Done ;)

**Comment by catherinewiltshire** [comment]
The line to edit is now line 717.

**Comment by firepixi** [comment]
ACF Photo Gallery Field addon plugin has allowed me to get around this - it doesn't pull in all images from all posts.

**Comment by andreas-stricker** [comment]
please fix this ...
