### ISSUE TITLE
Counter multiplying number by 10

### ISSUE THREAD

**Issue by taropaa** [elementor/elementor#9232]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Really love that you guys included the options to use shortcodes as a data source for counters countdowns etc. 

I am having an issue with counters, however:
I have a toolset view with a shortcode that generates a number. 
If I use the shortcode for the view, it generates the correct number, but the counter multiplies it by 10.

Here is the code it generates:

```
<span class="elementor-counter-number" data-duration="2000" data-to-value="  114
" data-from-value="0" data-delimiter=",">1,140</span>
```
114 is the correct number it should be displaying.

## Steps to reproduce
1. Using WP Toolset create a view with the following code:
```
[wpv-layout-start][wpv-items-found]<!-- wpv-loop-start -->[wpv-found-count]<wpv-loop></wpv-loop><!-- wpv-loop-end -->[/wpv-items-found][wpv-no-items-found]0 [/wpv-no-items-found][wpv-layout-end]
```
2. In the Content Selection section, you can select pages (will count the number of pages you have)
Check the "Disable the wrapping DIV around the View "
3. Use the shortcode for the view, something like `[wpv-view name="slug-of-the-view"]` as the ending number source in the counter widget.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: (Google) v5.7.14
	PHP Version: 7.2.13
	PHP Max Input Vars: 5000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.2.3
	Site URL: 
	Home URL:
	WP Multisite: Yes
	Max Upload Size: 15 MB
	Memory limit: 1024M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 1
	Debug Mode: Inactive

== Theme ==
	Name: Hello
	Version: 1.0.0
	Author: 
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.2.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36

== Active Plugins ==
	Autoptimize
		Version: 2.5.1
		Author: Frank Goossens (futtta)

	CAOS
		Version: 2.8.0
		Author: Daan van den Bergh

	Clear Sucuri Cache
		Version: 1.4
		Author: WebRangers

	Cookie Notice
		Version: 1.2.46
		Author: dFactory

	Dynamic Content for Elementor
		Version: 1.5.3
		Author: Dynamic.ooo

	Elementor
		Version: 2.7.3
		Author: Elementor.com

	Elementor Extras
		Version: 2.1.8
		Author: Namogo

	Elementor Pro
		Version: 2.7.1
		Author: Elementor.com

	Format Price
		Version: 1.0
		Author: TD Labs Ltd.

	GeoIP Detection
		Version: 2.12.0
		Author: Yellow Tree (Benjamin Pick)

	Gravity Forms
		Version: 2.4.14
		Author: rocketgenius

	Gravity Forms MailChimp Add-On
		Version: 4.5
		Author: rocketgenius

	Gravity Forms User Registration Add-On
		Version: 4.0
		Author: rocketgenius

	JetTabs For Elementor
		Version: 2.0.3
		Author: Zemez

	Mailgun
		Version: 1.7.1
		Author: Mailgun

	Safe Redirect Manager
		Version: 1.9.2
		Author: 10up

	SEOPress
		Version: 3.6.5
		Author: Benjamin Denis

	SEOPress PRO
		Version: 3.6.5
		Author: Benjamin Denis

	Toolset Access
		Version: 2.8.1.2
		Author: OnTheGoSystems

	Toolset Types
		Version: 3.3.5
		Author: OnTheGoSystems

	Toolset Views
		Version: 2.9.2
		Author: OnTheGoSystems

	Ultimate Addons for Elementor
		Version: 1.15.0
		Author: Brainstorm Force

	User Role Editor Pro
		Version: 4.51.2
		Author: Vladimir Garagulia

	Webtemple Math
		Version: 1
		Author: TD Labs Ltd.

	Webtemple Zendesk Support Chat
		Version: 0.5
		Author: TD Labs Ltd.

	WordPress Importer
		Version: 0.6.4
		Author: wordpressdotorg

	WP All Import - User Import Add-On
		Version: 1.1.1
		Author: Soflyy

	WP All Import Pro
		Version: 4.5.7
		Author: Soflyy

	WP CDN Rewrite
		Version: 0.4.0
		Author: Chris Scott, Michael Pretty, Kevin Langley, Sean McCafferty


== Network Plugins ==
	Admin Menu Editor Pro
		Version: 2.9.1
		Author: Janis Elsts

	All-in-One WP Migration
		Version: 7.8
		Author: ServMask

	All-in-One WP Migration Google Drive Extension
		Version: 2.55
		Author: ServMask

	All-in-One WP Migration Multisite Extension
		Version: 3.80
		Author: ServMask

	Branda
		Version: 3.1.2
		Author: WPMU DEV

	Cache Enabler
		Version: 1.3.4
		Author: KeyCDN

	Compress JPEG & PNG images
		Version: 3.2.0
		Author: TinyPNG

	Elementor
		Version: 2.7.3
		Author: Elementor.com

	Elementor Pro
		Version: 2.7.1
		Author: Elementor.com

	Gravity Forms
		Version: 2.4.14
		Author: rocketgenius

	Safe SVG
		Version: 1.9.4
		Author: Daryll Doyle

	User Role Editor Pro
		Version: 4.51.2
		Author: Vladimir Garagulia

	Webtemple Tooltip.io Integration
		Version: 4.6
		Author: TD Labs Ltd.

	Wordfence Security
		Version: 7.4.0
		Author: Wordfence

	WP Missed Schedule (The Original)
		Version: 2014.1231.2017.12
		Author: sLaNGjIs Team

	WP Ultimo
		Version: 1.10.4
		Author: Arindo Duque - NextPress


== Log<a href="/wp-admin/admin.php?page=elementor-system-info&elementor-clear-log=1&_wpnonce=11a3e2c0ad#elementor-clear-log" class="box-title-tool">Clear Log</a><span id="elementor-clear-log"></span> ==
	
Log: showing 20 of 342019-07-24 17:24:46 [info] Page Builder/Upgrades - _v_2_6_0_fa4_migration_flag Finished 
2019-07-24 17:24:46 [info] Page Builder/Upgrades - _v_2_6_6_fa4_migration_button Start  
2019-07-24 17:24:51 [info] Page Builder/Upgrades - _v_2_6_6_fa4_migration_button Finished 
2019-07-24 17:24:51 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Page Builder',
  'from' => '2.5.16',
  'to' => '2.6.6',
)]
2019-07-29 18:21:17 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Webtemple Pro',
  'from' => '2.5.11',
  'to' => '2.6.1',
)]
2019-08-01 19:45:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Webtemple',
  'from' => '2.6.6',
  'to' => '2.6.7',
)]
2019-08-01 19:45:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Webtemple Pro',
  'from' => '2.6.1',
  'to' => '2.6.2',
)]
2019-08-09 12:40:25 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Webtemple',
  'from' => '2.6.7',
  'to' => '2.6.8',
)]
2019-08-20 23:39:12 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Webtemple Pro',
  'from' => '2.6.2',
  'to' => '2.6.3',
)]
2019-08-23 03:39:55 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Webtemple Pro',
  'from' => '2.6.3',
  'to' => '2.6.4',
)]
2019-08-27 03:50:21 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Webtemple Pro',
  'from' => '2.6.4',
  'to' => '2.6.5',
)]
2019-09-16 19:04:45 [info] elementor::elementor_updater Started 
2019-09-16 19:04:45 [info] Page Builder/Upgrades - _v_2_7_1_remove_old_usage_data Start  
2019-09-16 19:04:45 [info] Page Builder/Upgrades - _v_2_7_1_remove_old_usage_data Finished 
2019-09-16 19:04:45 [info] Page Builder/Upgrades - _v_2_7_1_recalc_usage_data Start  
2019-09-16 19:04:45 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Webtemple',
  'from' => '2.6.8',
  'to' => '2.7.2',
)]
2019-09-16 19:04:47 [info] Page Builder/Upgrades - _v_2_7_1_recalc_usage_data Finished 
2019-09-16 19:04:47 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Page Builder',
  'from' => '2.6.8',
  'to' => '2.7.2',
)]
2019-09-25 20:25:34 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Webtemple',
  'from' => '2.7.2',
  'to' => '2.7.3',
)]
2019-10-01 18:36:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Webtemple Pro',
  'from' => '2.6.5',
  'to' => '2.7.1',
)]

PHP: showing 5 of 5PHP: 2019-04-07 18:42:11 [notice X 27][/opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/elementor/core/files/css/global-css.php::129] Undefined index: scheme [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-07-24 17:23:56 [error X 1][/opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/elementor/includes/plugin.php::519] Uncaught Error: Class 'Elementor\Editor' not found in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/elementor/includes/plugin.php:519
Stack trace:
#0 /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/elementor/includes/plugin.php(465): Elementor\Plugin->init_components()
#1 /opt/bitnami/apps/wordpress/htdocs/wp-includes/class-wp-hook.php(286): Elementor\Plugin->init('')
#2 /opt/bitnami/apps/wordpress/htdocs/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#3 /opt/bitnami/apps/wordpress/htdocs/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#4 /opt/bitnami/apps/wordpress/htdocs/wp-settings.php(525): do_action('init')
#5 /opt/bitnami/apps/wordpress/htdocs/wp-config.php(125): require_once('/opt/bitnami/ap...')
#6 /opt/bitnami/apps/wordpress/htdocs/wp-load.php(37): require_once('/opt/bitnami/ap...')
#7 /opt/bitnami/apps/wordpress/htdocs/wp-blog-header.php(13): require_once('/opt/bitnami/ap...')
#8 /opt/bitnami/apps/wordpress/htdocs/index.php(17): require('/opt/bitnami/ap. [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-08-27 14:01:00 [warning X 1][/opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/elementor-extras/includes/updater.php::344] Invalid argument supplied for foreach() [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-08-27 14:21:13 [notice X 16][/opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/elementor-extras/includes/utils.php::240] Undefined offset: 0 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-10-01 18:49:46 [error X 1][/opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/elementor/includes/template-library/sources/local.php::1027] Uncaught TypeError: Argument 2 passed to Elementor\TemplateLibrary\Source_Local::on_save_post() must be an instance of WP_Post, instance of stdClass given, called in /opt/bitnami/apps/wordpress/htdocs/wp-includes/class-wp-hook.php on line 288 and defined in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/elementor/includes/template-library/sources/local.php:1027
Stack trace:
#0 /opt/bitnami/apps/wordpress/htdocs/wp-includes/class-wp-hook.php(288): Elementor\TemplateLibrary\Source_Local->on_save_post(99371, Object(stdClass))
#1 /opt/bitnami/apps/wordpress/htdocs/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#2 /opt/bitnami/apps/wordpress/htdocs/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#3 /opt/bitnami/apps/wordpress/htdocs/wp-includes/post.php(3951): do_action('save_post', 99371, Object(stdClass), true)
#4 /opt/bitnami/apps/wordpress/htdocs/wp-includes/post.php(4028): wp_insert_post(Array, false)
#5 /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/elementor/inc [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 4 of 4JS: 2019-04-15 20:41:21 [error X 1][/wp-content/plugins/elementor-extras/assets/js/frontend.min.js:2:23526] Cannot read property \'find\' of undefined 
JS: 2019-04-26 04:03:44 [error X 6][/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.14:2:157434] this.jqueryXhr.abort is not a function 
JS: 2019-04-26 13:16:01 [error X 1][/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.14:2:53511] Cannot read property \'noUiSlider\' of undefined 
JS: 2019-04-29 22:50:45 [error X 3][/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.14:2:212877] Cannot read property \'html\' of undefined 



== Elements Usage ==
	
	archive
		archive-posts : 1
		heading : 2
		social-icons : 1
		uael-gf-styler : 1
		wp-widget-calendar : 1
	footer
		heading : 5
		html : 1
		icon-list : 2
		posts : 1
		social-icons : 1
	header
		button : 6
		html : 2
		image : 5
		nav-menu : 2
		social-icons : 2
		theme-site-logo : 1
	page
		button : 2
		counter : 6
		divider : 3
		ee-breadcrumbs : 4
		ee-inline-svg : 1
		heading : 33
		html : 2
		icon-box : 15
		icon-list : 1
		image : 15
		image-box : 24
		media-carousel : 1
		text-editor : 28
		toggle : 2
	popup
		button : 3
		divider : 2
		ee-slide-menu : 1
		heading : 1
		image : 2
		login : 1
	section
		ee-inline-svg : 1
		heading : 4
		login : 1
		shortcode : 1
		text-editor : 1
		toolset-view : 1
		uael-gf-styler : 5
	single
		dce-breadcrumbs : 1
		heading : 14
		icon-list : 2
		image : 1
		post-info : 3
		posts : 1
		share-buttons : 2
		shortcode : 7
		theme-post-content : 2
		uael-gf-styler : 2
	wp-post
		button : 9
		counter : 5
		dce-breadcrumbs : 16
		divider : 11
		flip-box : 2
		google_maps : 1
		heading : 251
		html : 1
		icon-box : 33
		icon-list : 7
		image : 40
		image-box : 62
		jet-tabs : 2
		login : 1
		media-carousel : 2
		posts : 1
		shortcode : 1
		spacer : 5
		text-editor : 187
		toggle : 3
		toolset-view : 1
		uael-gf-styler : 3
		uael-image-gallery : 1
```
</details>

Thank you,
Adrian

**Comment by shilo-ey** [comment]
Hi @taropaa 

Thanks for your feedback

We looked into this issue, and it seems like Toolset shortcode adds a new line char when applying the Thousands separator option, therefore, the value returned is not numeric value.

Thanks!
