### ISSUE TITLE
PHP Fatal error: Uncaught Error: Call to undefined method Elementor\\Core\\DocumentTypes\\Post::get_location()

### ISSUE THREAD

**Issue by pquerner** [elementor/elementor#9355]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

We're using Elementor (Version 2.7.4) and Elementor Pro (2.7.2) with the theme called "Phlox" (Version 2.4.8).
When creating a custom theme for a single blog post entry, we want to add the blogs content via Elementor. In the preview in the backend it works and shows the blog content. In the actual frontend I will get no output and the site produces no page (endless page loader). I've looked at the error logs and found this:

```
Got error 'PHP message: PHP Fatal error: Uncaught Error: Call to undefined method Elementor\\Core\\DocumentTypes\\Post::get_location() in /var/www/vhosts/snip/wordpress/wp-content/plugins/auxin-elements/includes/elementor/modules/theme-builder/classes/locations-manager.php:150\nStack trace:\n#0 /var/www/vhosts/snip/wordpress/wp-includes/class-wp-hook.php(286): Auxin\\Plugin\\CoreElements\\Elementor\\Modules\\ThemeBuilder\\Classes\\Locations_Manager->builder_wrapper('<p>Hallo tolles...')\n#1 /var/www/vhosts/snip/wordpress/wp-includes/plugin.php(208): WP_Hook->apply_filters('<p>Hallo tolles...', Array)\n#2 /var/www/vhosts/snip/wordpress/wp-content/plugins/elementor-pro/modules/posts/skins/skin-content-base.php(257): apply_filters('the_content', 'Hallo tolles Ve...')\n#3 /var/www/vhosts/snip/...\n', referer: http://snip/blog/
```

By simply removing or commenting the lines in the named class like so
```
			/**
			if ( $document ) {
				$document_location = $document->get_location();
				$location_settings = $this->get_location( $document_location );
				// If is a `content` document or the theme is not support the document location (header/footer and etc.).
				if ( $location_settings && ! $location_settings['edit_in_content'] ) {
					$content = '<div class="elementor-theme-builder-content-area">' . __( 'Content Area', 'auxin-elements' ) . '</div>';
				}
			}
			**/
```

I was able to get the wanted output on the frontend and preview in the backend. 

Wordpress Installation is version 5.2.4.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v5.5.61-MariaDB-38.13
	PHP Version: 7.2.23
	PHP Max Input Vars: 1000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.2.4
	Site URL: http://snip
	Home URL: http://snip
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%postname%/
	Language: de-DE
	Timezone: Europe/Berlin
	Debug Mode: Inactive

== Theme ==
	Name: Phlox
	Version: 2.4.8
	Author: averta
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36

== Active Plugins ==
	Akeeba Backup for WordPress
		Version: 3.6.0
		Author: Akeeba Ltd

	Classic Editor
		Version: 1.5
		Author: WordPress Contributors

	Elementor
		Version: 2.7.4
		Author: Elementor.com

	Elementor Pro
		Version: 2.7.2
		Author: Elementor.com

	Flow-Flow Lite
		Version: 3.1.31
		Author: Looks Awesome

	Google Analytics for WordPress by MonsterInsights
		Version: 7.9.0
		Author: MonsterInsights

	Google Analytics Opt-Out
		Version: 2.2.5
		Author: WP-Buddy

	Phlox Core Elements
		Version: 2.4.9
		Author: averta

	Yoast SEO
		Version: 12.3
		Author: Team Yoast


== Must-Use Plugins ==
	akeeba-backup-coreupdate.php
		Version: 
		Author: 


== Log<a href="/wp-admin/admin.php?page=elementor-system-info&elementor-clear-log=1&_wpnonce=3dba67c54a#elementor-clear-log" class="box-title-tool">Protokoll löschen</a><span id="elementor-clear-log"></span> ==
	
JS: showing 4 of 4JS: 2019-10-11 09:10:00 [error X 2][http://snip/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.7.4:32:64106] this.ui.apply.add is not a function 
JS: 2019-10-14 06:50:21 [error X 1][http://snip/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.7.4:32:132492] e.ui.form is undefined 
JS: 2019-10-14 13:55:17 [error X 331][http://snip/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.7.4:2:78461] n is undefined 
JS: 2019-10-16 08:57:52 [error X 1][http://snip/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.7.4:2:46135] this.ui.select is undefined 

PHP: showing 1 of 1PHP: 2019-10-16 10:57:24 [notice X 3][/var/www/vhosts/snip/wordpress/wp-content/plugins/elementor-pro/modules/posts/widgets/posts.php::31] Undefined index: posts_post_type [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elements Usage ==
	
	single
		aux_modern_heading : 1
		spacer : 2
		theme-post-content : 1
		theme-post-featured-image : 1
		theme-post-title : 1
	wp-page
		aux_modern_heading : -309
		button : -87
		form : 1
		icon : 1
		icon-box : 6
		image : -212
		image-box : 4
		image-carousel : 1
		menu-anchor : 7
		posts : 1
		spacer : -163
		text-editor : -55
		wp-widget-ff_widget : 1

				
```
</details>

**Comment by deckerweb** [comment]
Based on your posted error message this error is coming from a plugin with the slug of "auxin-elements" ---> and that one actually is the "Phlox Core Elements" plugin by vendor "averta" (free plugin on wordpress.org repo). You need to contact this developer and they need to update their plugin.

**Comment by pquerner** [comment]
Ah, thank you this info.
