### ISSUE TITLE
Error on post-new.php

### ISSUE THREAD

**Issue by stefanpejcic** [elementor/elementor#9908]
Fatal error: Uncaught TypeError: Argument 2 passed to Elementor\TemplateLibrary\Source_Local::on_save_post() must be an instance of WP_Post, null given, called in /home1/wporb/public_html/wp-includes/class-wp-hook.php on line 290 and defined in /home1/wporb/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php:1044 Stack trace: #0 /home1/wporb/public_html/wp-includes/class-wp-hook.php(290): Elementor\TemplateLibrary\Source_Local->on_save_post(0, NULL) #1 /home1/wporb/public_html/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters(0, Array) #2 /home1/wporb/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array) #3 /home1/wporb/public_html/wp-includes/post.php(4119): do_action('save_post', 0, NULL, false) #4 /home1/wporb/public_html/wp-admin/includes/post.php(671): wp_insert_post(Array) #5 /home1/wporb/public_html/wp-admin/post-new.php(66): get_default_post_to_edit('post', true) #6 {main} thrown in /home1/wporb/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php on line 1044
" />

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Getting critical error after migrating to another hosting.
Tried everything from deactivating all plugins, default theme, database cleanup, increasing memorylimit, changing php version...

## Steps to reproduce

Migrate to another hosting?

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v5.7.28
	PHP Version: 7.3.12
	PHP Max Input Vars: 1000
	PHP Max Post Size: 180M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.3.1
	Site URL: https://wporb.com
	Home URL: https://wporb.com
	WP Multisite: No
	Max Upload Size: 120 MB
	Memory limit: 256M
	Permalink Structure: /%category%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Active

== Theme ==
	Name: WPorb
	Version: 1.9.4
	Author: meks
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36

== Active Plugins ==
	AffiliateWP
		Version: 2.3
		Author: Sandhills Development, LLC

	Antispam Bee
		Version: 2.9.1
		Author: pluginkollektiv

	Anywhere Elementor
		Version: 1.2.1
		Author: WPVibes

	Auto Login New User After Registration
		Version: 1.7.1
		Author: Jeff Sherk

	Classic Editor
		Version: 1.5
		Author: WordPress Contributors

	Comment Redirect by Yoast
		Version: 1.1.3
		Author: Team Yoast

	Contact Form 7
		Version: 5.1.6
		Author: Takayuki Miyoshi

	Contact Form CFDB7
		Version: 1.2.4.8
		Author: Arshid

	Easy Social Share Buttons for WordPress
		Version: 6.2.1
		Author: CreoApps

	Elementor
		Version: 2.8.2
		Author: Elementor.com

	Entry Views
		Version: 1.0.0
		Author: Justin Tadlock

	Essential Addons for Elementor
		Version: 3.6.2
		Author: WPDeveloper

	Fixed TOC
		Version: 3.1.14
		Author: wphigh

	Flexible Checkout Fields
		Version: 2.2.1
		Author: WP Desk

	Gridlove Buddy
		Version: 1.0.1
		Author: meks

	JetMenu
		Version: 1.5.15
		Author: Crocoblock

	Jetpack by WordPress.com
		Version: 8.0
		Author: Automattic

	JetPopup
		Version: 1.3.0
		Author: Crocoblock

	JS Help Desk
		Version: 2.1.8
		Author: Joom Sky

	LuckyWP Cookie Notice (GDPR)
		Version: 1.1.1
		Author: LuckyWP

	Meks Smart Social Widget
		Version: 1.4
		Author: Meks

	Meks Time Ago
		Version: 1.1.5
		Author: Meks

	Premium Addons for Elementor
		Version: 3.9.7
		Author: Leap13

	Reading Progress Bar
		Version: 1.2.1
		Author: Jb Audras, CTO @ Whodunit

	Redirection for Contact Form 7
		Version: 1.3.5
		Author: Query Solutions

	Redux Framework
		Version: 3.6.16
		Author: Team Redux

	Schema Pro
		Version: 1.3.0
		Author: Brainstorm Force

	Site Kit by Google
		Version: 1.1.3
		Author: Google

	SVG Support
		Version: 2.3.15
		Author: Benbodhi

	Tidio Chat
		Version: 4.2.1
		Author: Tidio Ltd.

	WebP Express
		Version: 0.17.2
		Author: Bjørn Rosell

	WooCommerce
		Version: 3.8.1
		Author: Automattic

	WooCommerce Direct Checkout
		Version: 2.3.1
		Author: QuadLayers

	WooCommerce PayPal Checkout Gateway
		Version: 1.6.18
		Author: WooCommerce

	WP Glossary - Encyclopedia / Lexicon / Knowledge Base / Wiki / Dictionary
		Version: 2.3
		Author: The WP Instinct Team

	WP Plugin Info Card
		Version: 3.1.16
		Author: Brice CAPOBIANCO, Ronald Huereca

	YellowPencil Pro
		Version: 7.2.1
		Author: WaspThemes

	YITH Custom Thank You Page for Woocommerce
		Version: 1.2.2
		Author: YITH


== Elements Usage ==
	
	section : 13
		button : 6
		eael-data-table : 1
		eael-post-grid : 1
		heading : 12
		image : 6
		jet-popup-action-button : 2
		premium-addon-fancy-text : 2
		social-icons : 1
		text-editor : 17
	wp-post : 1
		button : -71
		counter : -1
		divider : 6
		eael-cta-box : 1
		eael-data-table : 1
		eael-dual-color-header : 1
		eael-team-member : 6
		eael-twitter-feed : 1
		google_maps : 1
		heading : -254
		icon : 7
		icon-box : 6
		icon-list : 2
		image : -182
		image-box : 7
		premium-addon-dual-header : 2
		shortcode : 7
		social-icons : 1
		spacer : -3
		text-editor : -488
		toggle : 1
		wp-widget-gridlove_posts_widget : 2
	wp-page : 22
		button : 6
		eael-twitter-feed : 1
		eicon-woocommerce : 1
		text-editor : 6
		wp-widget-search : 1
	jet-popup : 2
		button : 1
		eael-countdown : 1
		heading : -4
		jet-popup-action-button : 2


== Log ==
	
Log: showing 2 of 22019-10-31 20:10:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.7.4',
  'to' => '2.7.5',
)]
2019-12-17 14:48:53 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.7.5',
  'to' => '2.8.2',
)]

JS: showing 8 of 8JS: 2019-10-31 20:17:41 [error X 1][https://wporb.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.7.5:32:138844] elementorFrontend.elements.window.jQuery is not a function 
JS: 2019-11-02 16:34:54 [error X 4][https://wporb.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.7.5:7:50317] Blocked a frame with origin \"https://wporb.com\" from accessing a cross-origin frame. 
JS: 2019-11-09 14:17:51 [error X 1][https://wporb.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.7.5:32:131011] Cannot read property \'prev\' of undefined 
JS: 2019-11-09 14:17:51 [error X 2][https://wporb.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.7.5:32:131259] Cannot read property \'menu\' of undefined 
JS: 2019-11-22 16:40:45 [error X 2][https://wporb.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.7.5:32:132502] Cannot read property \'html\' of undefined 
JS: 2019-11-22 18:26:50 [error X 1][https://wporb.com/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=2.7.5:2:46224] Cannot read property \'attributes\' of undefined 
JS: 2019-11-27 18:00:39 [error X 2][https://wporb.com/wp-admin/post.php?post=5311&action=elementor:2:5] google is not defined 
JS: 2019-11-27 18:03:05 [error X 1][https://wporb.com/wp-admin/post.php?post=3411&action=elementor:3:35] $(...).datepicker is not a function 

PHP: showing 5 of 5PHP: 2019-11-06 15:37:23 [notice X 27][/home/wporb/public_html/wp-content/plugins/elementor/includes/elements/column.php::1002] Undefined index: _column_size [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-12-17 14:22:56 [error X 8][/home1/wporb/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php::1040] Uncaught TypeError: Argument 2 passed to Elementor\TemplateLibrary\Source_Local::on_save_post() must be an instance of WP_Post, null given, called in /home1/wporb/public_html/wp-includes/class-wp-hook.php on line 290 and defined in /home1/wporb/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php:1040
Stack trace:
#0 /home1/wporb/public_html/wp-includes/class-wp-hook.php(290): Elementor\TemplateLibrary\Source_Local->on_save_post(0, NULL)
#1 /home1/wporb/public_html/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters(0, Array)
#2 /home1/wporb/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#3 /home1/wporb/public_html/wp-includes/post.php(4119): do_action('save_post', 0, NULL, false)
#4 /home1/wporb/public_html/wp-admin/includes/post.php(671): wp_insert_post(Array)
#5 /home1/wporb/public_html/wp-admin/post-new.php(66): get_default_post_to_edit('post', true)
#6 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-12-17 14:56:21 [error X 3][/home1/wporb/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php::1044] Uncaught TypeError: Argument 2 passed to Elementor\TemplateLibrary\Source_Local::on_save_post() must be an instance of WP_Post, null given, called in /home1/wporb/public_html/wp-includes/class-wp-hook.php on line 290 and defined in /home1/wporb/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php:1044
Stack trace:
#0 /home1/wporb/public_html/wp-includes/class-wp-hook.php(290): Elementor\TemplateLibrary\Source_Local->on_save_post(0, NULL)
#1 /home1/wporb/public_html/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters(0, Array)
#2 /home1/wporb/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#3 /home1/wporb/public_html/wp-includes/post.php(4119): do_action('save_post', 0, NULL, false)
#4 /home1/wporb/public_html/wp-admin/includes/post.php(671): wp_insert_post(Array)
#5 /home1/wporb/public_html/wp-admin/post-new.php(66): get_default_post_to_edit('post', true)
#6 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-12-17 14:58:09 [error X 1][/home1/wporb/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php::1044] Uncaught TypeError: Argument 2 passed to Elementor\TemplateLibrary\Source_Local::on_save_post() must be an instance of WP_Post, null given, called in /home1/wporb/public_html/wp-includes/class-wp-hook.php on line 290 and defined in /home1/wporb/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php:1044
Stack trace:
#0 /home1/wporb/public_html/wp-includes/class-wp-hook.php(290): Elementor\TemplateLibrary\Source_Local->on_save_post(0, NULL)
#1 /home1/wporb/public_html/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters(0, Array)
#2 /home1/wporb/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#3 /home1/wporb/public_html/wp-includes/post.php(4119): do_action('save_post', 0, NULL, false)
#4 /home1/wporb/public_html/wp-includes/revision.php(316): wp_insert_post(Array)
#5 /home1/wporb/public_html/wp-includes/revision.php(190): _wp_put_post_revision(Array)
#6 /home1/wporb/public_html/wp-includes/class-wp-hook.php(290): wp_save_post_revision(7241)
#7 /home1/wpor [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-12-17 15:02:42 [error X 1][/home1/wporb/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php::1044] Uncaught TypeError: Argument 2 passed to Elementor\TemplateLibrary\Source_Local::on_save_post() must be an instance of Elementor\TemplateLibrary\WP_Post, null given, called in /home1/wporb/public_html/wp-includes/class-wp-hook.php on line 290 and defined in /home1/wporb/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php:1044
Stack trace:
#0 /home1/wporb/public_html/wp-includes/class-wp-hook.php(290): Elementor\TemplateLibrary\Source_Local->on_save_post(0, NULL)
#1 /home1/wporb/public_html/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters(0, Array)
#2 /home1/wporb/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#3 /home1/wporb/public_html/wp-includes/post.php(4119): do_action('save_post', 0, NULL, false)
#4 /home1/wporb/public_html/wp-admin/includes/post.php(671): wp_insert_post(Array)
#5 /home1/wporb/public_html/wp-admin/post-new.php(66): get_default_post_to_edit('post', true)
#6 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]


				
```
</details>

**Comment by shilo-ey** [comment]
Hi @stefanpejcic 

It seems like some edge case scenario.
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.

**Comment by sitruc520** [comment]
Also receiving the same error. I suspect it's related to some other plugin or server configuration, as I do not get it on a local dev copy of the site, but I do on a production one.

**Comment by pradeesh72** [comment]
Am also getting the same error. We are using Nginx. I think the error is happening for non-apache web servers.

**Comment by eleazarherrera** [comment]
Tengo justo el mismo error y ya hice las pruebas mencionadas en el primer mensaje. Me pasa lo mismo tanto como con entradas como con páginas nuevas. El soporte del hosting no ha podido darme solución tampoco.

Lograron resolverte? @stefanpejcic

**Comment by stefanpejcic** [comment]
Hi @eleazarherrera for me it turned out to be a database related problem, after manually exporting the database and migrating, some empty tables got placed **NULL** value inside them..
After a few days of troubleshooting, and trying everything that I could think of, what I did was exporting everything from wp-admin (posts, pages, elementor templates, etc.) then starting fresh and importing the content.

I'd suggest doing it on a staging site until you migrate everything from the main one.
Hope this helps you as well

**Comment by allworld13** [comment]
I tend to agree with stefanpejcic's previous post! Has any tried fixing the corresponding backend tables?

**Comment by vinhgiang** [comment]
I found out that for some reason, after exporting and importing the database manually by PHPMyAdmin, some tables missed their primary keys and/or auto increase attribute, which leads to a lot of records have 0 as the value for the ID column. As a result, WP and Elementor did not work properly.

Solution:
- go through very tables to check whether they have primary key and auto increase or not. If not, set primary key for them, most likely the ID column.

*NOTE: you might need to remove the auto increase value first if that column has an auto increase attribute but not a primary key. Next, drop the index and after that set primary key then is auto increase.

**Comment by bmtriet** [comment]
> I found out that for some reason, after exporting and importing the database manually by PHPMyAdmin, some tables missed their primary keys and/or auto increase attribute, which leads to a lot of records have 0 as the value for the ID column. As a result, WP and Elementor did not work properly.
> 
> Solution:
> 
> * go through very tables to check whether they have primary key and auto increase or not. If not, set primary key for them, most likely the ID column.
> 
> *NOTE: you might need to remove the auto increase value first if that column has an auto increase attribute but not a primary key. Next, drop the index and after that set primary key then is auto increase.

This save my time alot... thx....

**Comment by adictoaj** [comment]
Muchisimas gracias, el actualizar la base de datos añadiendo el auto_increment y el primary_key fue la solucion para mi. En efecto al importar la base de datos de forma manual por phpmyadmin se produjo este error.
