### ISSUE TITLE
Action executes twice when within single template using post content

### ISSUE THREAD

**Issue by pingram3541** [elementor/elementor#9952]
## Prerequisites
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description
When an Elementor instance exists within an Elementor Single Template the action elementor/widget/render_content executes twice.

## Steps to reproduce
1. Create a single page template with a post content element and assign page to conditional
2. Edit said page that uses single template in Elementor and assign an ID to the desired widget to hook, i.e. an html widget
3. Hook this widget using something as follows:

```
add_action( 'elementor/widget/render_content', function( $content, $widget ) {
    if ( 'html' === $widget->get_name() && is_page( 'my-page' ) ) {
        $settings = $widget->get_settings();
        if ( ! empty( $settings['_element_id'] ) && $settings['_element_id'] === 'my_id' ) {
            write_log( 'action executed!' );
        }
    }
    return $content;
}
```

This results in "action executed!" logged twice.  The content itself renders only once which is good but otherwise, any database functions or other logic executes twice.  I have tried checking against the global post but even that returns true both times.

## Isolating the problem
- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

Tested multiple, apache, nginx, public/local host...

**Comment by pingram3541** [comment]
An additional issue has also been discovered as a result of this, when using the Posts widget and setting the query to avoid duplicates results in no posts rendering on the front end.  Disabling avoid duplicates and the posts render or removing the Theme Builder template from the post/page also resolves this issue.

It appears the theme builder loop logic causes the Posts widget to execute twice and upon second iteration it is seen as a duplicate and therefore nothing is returned to the front end.

**Comment by peteratdjeeni** [comment]
I have debugged sg. similar (if not the same) with the following steps:
- Enabled PHP debugging and used error_log at different locations of my code
- In my case the actions assigned to the 'parse_query' WP hook were performed several times
- I have logged the call_stack, too.
- I have actions added also to the 'the_content' WP hook and put error_log in it
- I have actions added also to the 'init' WP hook and put error_log in it
- For the first time in 'parse_query' my code have run without a problem, generating the correct result with NO elementor call in the call_stack
- The 'the_content' hook was never reached. The 'init' hook was only called once, before the first 'parse_query'.
- For the second time in 'parse_query' the call_stack was full with Elementor calls. Here you are:
#0 .../public_html/wp-includes/class-wp-hook.php(308): <MyActionFunction>()
#1 .../public_html/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters(NULL, Array)
#2 .../public_html/wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#3 .../public_html/wp-includes/class-wp-query.php(1140): do_action_ref_array(\'parse_query\', Array)
#4 .../public_html/wp-includes/class-wp-query.php(1868): WP_Query->parse_query()
#5 .../public_html/wp-includes/class-wp-query.php(3800): WP_Query->get_posts()
#6 .../public_html/wp-includes/class-wp-query.php(3932): WP_Query->query(Array)
#7 .../public_html/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/fonts-manager.php(399): WP_Query->__construct(Array)
#8 .../public_html/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/fonts-manager.php(338): ElementorPro\\Modules\\AssetsManager\\AssetTypes\\Fonts_Manager->generate_fonts_list()
#9 .../public_html/wp-includes/class-wp-hook.php(310): ElementorPro\\Modules\\AssetsManager\\AssetTypes\\Fonts_Manager->register_fonts_in_control(Array)
#10 .../public_html/wp-includes/plugin.php(205): WP_Hook->apply_filters(Array, Array)
#11 .../public_html/wp-content/plugins/elementor/includes/fonts.php(122): apply_filters(\'elementor/fonts...\', Array)
#12 .../public_html/wp-content/plugins/elementor/includes/controls/font.php(46): Elementor\\Fonts::get_fonts()
#13 .../public_html/wp-content/plugins/elementor/includes/controls/base.php(73): Elementor\\Control_Font->get_default_settings()
#14 .../public_html/wp-content/plugins/elementor/includes/controls/base-data.php(19): Elementor\\Base_Control->__construct()
#15 .../public_html/wp-content/plugins/elementor/includes/managers/controls.php(456): Elementor\\Base_Data_Control->__construct()
#16 .../public_html/wp-content/plugins/elementor/includes/managers/controls.php(609): Elementor\\Controls_Manager->register_controls()
#17 .../public_html/wp-content/plugins/elementor/includes/managers/controls.php(628): Elementor\\Controls_Manager->get_controls()
#18 .../public_html/wp-content/plugins/elementor/includes/managers/controls.php(800): Elementor\\Controls_Manager->get_control(\'section\')
#19 .../public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(434): Elementor\\Controls_Manager->add_control_to_stack(Object(Elementor\\Core\\Kits\\Documents\\Kit), \'document_settin...\', Array, Array)
#20 .../public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(1515): Elementor\\Controls_Stack->add_control(\'document_settin...\', Array)
#21 .../public_html/wp-content/plugins/elementor/core/base/document.php(1747): Elementor\\Controls_Stack->start_controls_section(\'document_settin...\', Array)
#22 .../public_html/wp-content/plugins/elementor/core/kits/documents/kit.php(146): Elementor\\Core\\Base\\Document->register_document_controls()
#23 .../public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(2326): Elementor\\Core\\Kits\\Documents\\Kit->register_controls()
#24 .../public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(509): Elementor\\Controls_Stack->init_controls()
#25 .../public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(313): Elementor\\Controls_Stack->get_stack()
#26 .../public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(2413): Elementor\\Controls_Stack->get_controls()
#27 .../public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(1098): Elementor\\Controls_Stack->sanitize_settings(Array)
#28 .../public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(2158): Elementor\\Controls_Stack->get_data(\'settings\')
#29 .../public_html/wp-content/plugins/elementor/core/base/base-object.php(142): Elementor\\Controls_Stack->get_init_settings()
#30 .../public_html/wp-content/plugins/elementor/core/base/base-object.php(40): Elementor\\Core\\Base\\Base_Object->ensure_settings()
#31 .../public_html/wp-content/plugins/elementor/core/kits/manager.php(117): Elementor\\Core\\Base\\Base_Object->get_settings(\'default_page_te...\')
#32 .../public_html/wp-content/plugins/elementor/modules/page-templates/module.php(92): Elementor\\Core\\Kits\\Manager->get_current_settings(\'default_page_te...\')
#33 .../public_html/wp-includes/class-wp-hook.php(310): Elementor\\Modules\\PageTemplates\\Module->template_include(\'/.../...\')
#34 .../public_html/wp-includes/plugin.php(205): WP_Hook->apply_filters(\'/.../...\', Array)
#35 .../public_html/wp-includes/template-loader.php(104): apply_filters(\'template_includ...\', \'/.../...\')
#36 .../public_html/wp-blog-header.php(19): require_once(\'/.../...\')
#37 .../public_html/index.php(17): require(\'/.../...\')
#38 {main}

- #7 constructs a WP_Query object and within the constructor the corresponding 'parse_query' hook is executed. This is a serious negative side-effect of Elementor. Please, evaluate the possibility of eliminating the creation of a WP_Query object for generating font_list.
